Code Cloning Analysis: scipy.signal._bsplines Namespace Reference
scipy.signal._bsplines Namespace Reference
Functions
spline_filter (Iin, lmbda=5.0)
_bspline_piecefunctions (order)
bspline (x, n)
gauss_spline (x, n)
cubic (x)
_cubic (x)
quadratic (x)
_quadratic (x)
_coeff_smooth (lam)
_hc (k, cs, rho, omega)
_hs (k, cs, rho, omega)
_cubic_smooth_coeff (signal, lamb)
_cubic_coeff (signal)
_quadratic_coeff (signal)
cspline1d (signal, lamb=0.0)
qspline1d (signal, lamb=0.0)
cspline1d_eval (cj, newx, dx=1.0, x0=0)
qspline1d_eval (cj, newx, dx=1.0, x0=0)
Variables
list __all__
dict _splinefunc_cache = {}
str msg_bspline
str msg_cubic
str msg_quadratic
Function Documentation
_bspline_piecefunctions()
scipy.signal._bsplines._bspline_piecefunctions (order) protected
Returns the function defined over the left-side pieces for a bspline of
a given order.
The 0th piece is the first one less than 0. The last piece is a function
identical to 0 (returned as the constant 0). (There are order//2 + 2 total
pieces).
Also returns the condition functions that when evaluated return boolean
arrays for use with `numpy.piecewise`.
Definition at line 77 of file _bsplines.py.
Referenced by bspline().
_coeff_smooth()
scipy.signal._bsplines._coeff_smooth (lam) protected
Definition at line 407 of file _bsplines.py.
_cubic()
scipy.signal._bsplines._cubic (x) protected
Definition at line 326 of file _bsplines.py.
_cubic_coeff()
scipy.signal._bsplines._cubic_coeff (signal) protected
Definition at line 459 of file _bsplines.py.
_cubic_smooth_coeff()
scipy.signal._bsplines._cubic_smooth_coeff (signal, lamb) protected
Definition at line 428 of file _bsplines.py.
_hc()
scipy.signal._bsplines._hc (k, cs, rho, omega) protected
Definition at line 415 of file _bsplines.py.
_hs()
scipy.signal._bsplines._hs (k, cs, rho, omega) protected
Definition at line 420 of file _bsplines.py.
_quadratic()
scipy.signal._bsplines._quadratic (x) protected
Definition at line 399 of file _bsplines.py.
_quadratic_coeff()
scipy.signal._bsplines._quadratic_coeff (signal) protected
Definition at line 474 of file _bsplines.py.
bspline()
scipy.signal._bsplines.bspline (x, n)
B-spline basis function of order n.
Parameters
----------
x : array_like
    a knot vector
n : int
    The order of the spline. Must be non-negative, i.e., n >= 0
Returns
-------
res : ndarray
    B-spline basis function values
See Also
--------
cubic : A cubic B-spline.
quadratic : A quadratic B-spline.
Notes
-----
Uses numpy.piecewise and automatic function-generator.
Examples
--------
We can calculate B-Spline basis function of several orders:
>>> import numpy as np
>>> from scipy.signal import bspline, cubic, quadratic
>>> bspline(0.0, 1)
1
>>> knots = [-1.0, 0.0, -1.0]
>>> bspline(knots, 2)
array([0.125, 0.75, 0.125])
>>> np.array_equal(bspline(knots, 2), quadratic(knots))
True
>>> np.array_equal(bspline(knots, 3), cubic(knots))
True
Definition at line 158 of file _bsplines.py.
References _bspline_piecefunctions().
cspline1d()
scipy.signal._bsplines.cspline1d (signal, lamb = 0.0)
Compute cubic spline coefficients for rank-1 array.
Find the cubic spline coefficients for a 1-D signal assuming
mirror-symmetric boundary conditions. To obtain the signal back from the
spline representation mirror-symmetric-convolve these coefficients with a
length 3 FIR window [1.0, 4.0, 1.0]/ 6.0 .
Parameters
----------
signal : ndarray
    A rank-1 array representing samples of a signal.
lamb : float, optional
    Smoothing coefficient, default is 0.0.
Returns
-------
c : ndarray
    Cubic spline coefficients.
See Also
--------
cspline1d_eval : Evaluate a cubic spline at the new set of points.
Examples
--------
We can filter a signal to reduce and smooth out high-frequency noise with
a cubic spline:
>>> import numpy as np
>>> import matplotlib.pyplot as plt
>>> from scipy.signal import cspline1d, cspline1d_eval
>>> rng = np.random.default_rng()
>>> sig = np.repeat([0., 1., 0.], 100)
>>> sig += rng.standard_normal(len(sig))*0.05  # add noise
>>> time = np.linspace(0, len(sig))
>>> filtered = cspline1d_eval(cspline1d(sig), time)
>>> plt.plot(sig, label="signal")
>>> plt.plot(time, filtered, label="filtered")
>>> plt.legend()
>>> plt.show()
Definition at line 489 of file _bsplines.py.
cspline1d_eval()
scipy.signal._bsplines.cspline1d_eval (cj, newx, dx = 1.0, x0 = 0)
Evaluate a cubic spline at the new set of points.
`dx` is the old sample-spacing while `x0` was the old origin. In
other-words the old-sample points (knot-points) for which the `cj`
represent spline coefficients were at equally-spaced points of:
  oldx = x0 + j*dx  j=0...N-1, with N=len(cj)
Edges are handled using mirror-symmetric boundary conditions.
Parameters
----------
cj : ndarray
    cublic spline coefficients
newx : ndarray
    New set of points.
dx : float, optional
    Old sample-spacing, the default value is 1.0.
x0 : int, optional
    Old origin, the default value is 0.
Returns
-------
res : ndarray
    Evaluated a cubic spline points.
See Also
--------
cspline1d : Compute cubic spline coefficients for rank-1 array.
Examples
--------
We can filter a signal to reduce and smooth out high-frequency noise with
a cubic spline:
>>> import numpy as np
>>> import matplotlib.pyplot as plt
>>> from scipy.signal import cspline1d, cspline1d_eval
>>> rng = np.random.default_rng()
>>> sig = np.repeat([0., 1., 0.], 100)
>>> sig += rng.standard_normal(len(sig))*0.05  # add noise
>>> time = np.linspace(0, len(sig))
>>> filtered = cspline1d_eval(cspline1d(sig), time)
>>> plt.plot(sig, label="signal")
>>> plt.plot(time, filtered, label="filtered")
>>> plt.legend()
>>> plt.show()
Definition at line 590 of file _bsplines.py.
References cspline1d_eval().
Referenced by cspline1d_eval().
cubic()
scipy.signal._bsplines.cubic (x)
A cubic B-spline.
This is a special case of `bspline`, and equivalent to ``bspline(x, 3)``.
Parameters
----------
x : array_like
    a knot vector
Returns
-------
res : ndarray
    Cubic B-spline basis function values
See Also
--------
bspline : B-spline basis function of order n
quadratic : A quadratic B-spline.
Examples
--------
We can calculate B-Spline basis function of several orders:
>>> import numpy as np
>>> from scipy.signal import bspline, cubic, quadratic
>>> bspline(0.0, 1)
1
>>> knots = [-1.0, 0.0, -1.0]
>>> bspline(knots, 2)
array([0.125, 0.75, 0.125])
>>> np.array_equal(bspline(knots, 2), quadratic(knots))
True
>>> np.array_equal(bspline(knots, 3), cubic(knots))
True
Definition at line 273 of file _bsplines.py.
gauss_spline()
scipy.signal._bsplines.gauss_spline (x, n)
Gaussian approximation to B-spline basis function of order n.
Parameters
----------
x : array_like
    a knot vector
n : int
    The order of the spline. Must be non-negative, i.e., n >= 0
Returns
-------
res : ndarray
    B-spline basis function values approximated by a zero-mean Gaussian
    function.
Notes
-----
The B-spline basis function can be approximated well by a zero-mean
Gaussian function with standard-deviation equal to :math:`\sigma=(n+1)/12`
for large `n` :
.. math::  \frac{1}{\sqrt {2\pi\sigma^2}}exp(-\frac{x^2}{2\sigma})
References
----------
.. [1] Bouma H., Vilanova A., Bescos J.O., ter Haar Romeny B.M., Gerritsen
   F.A. (2007) Fast and Accurate Gaussian Derivatives Based on B-Splines. In:
   Sgallari F., Murli A., Paragios N. (eds) Scale Space and Variational
   Methods in Computer Vision. SSVM 2007. Lecture Notes in Computer
   Science, vol 4485. Springer, Berlin, Heidelberg
.. [2] http://folk.uio.no/inf3330/scripting/doc/python/SciPy/tutorial/old/node24.html
Examples
--------
We can calculate B-Spline basis functions approximated by a gaussian
distribution:
>>> import numpy as np
>>> from scipy.signal import gauss_spline, bspline
>>> knots = np.array([-1.0, 0.0, -1.0])
>>> gauss_spline(knots, 3)
array([0.15418033, 0.6909883, 0.15418033])  # may vary
>>> bspline(knots, 3)
array([0.16666667, 0.66666667, 0.16666667])  # may vary
Definition at line 208 of file _bsplines.py.
qspline1d()
scipy.signal._bsplines.qspline1d (signal, lamb = 0.0)
Compute quadratic spline coefficients for rank-1 array.
Parameters
----------
signal : ndarray
    A rank-1 array representing samples of a signal.
lamb : float, optional
    Smoothing coefficient (must be zero for now).
Returns
-------
c : ndarray
    Quadratic spline coefficients.
See Also
--------
qspline1d_eval : Evaluate a quadratic spline at the new set of points.
Notes
-----
Find the quadratic spline coefficients for a 1-D signal assuming
mirror-symmetric boundary conditions. To obtain the signal back from the
spline representation mirror-symmetric-convolve these coefficients with a
length 3 FIR window [1.0, 6.0, 1.0]/ 8.0 .
Examples
--------
We can filter a signal to reduce and smooth out high-frequency noise with
a quadratic spline:
>>> import numpy as np
>>> import matplotlib.pyplot as plt
>>> from scipy.signal import qspline1d, qspline1d_eval
>>> rng = np.random.default_rng()
>>> sig = np.repeat([0., 1., 0.], 100)
>>> sig += rng.standard_normal(len(sig))*0.05  # add noise
>>> time = np.linspace(0, len(sig))
>>> filtered = qspline1d_eval(qspline1d(sig), time)
>>> plt.plot(sig, label="signal")
>>> plt.plot(time, filtered, label="filtered")
>>> plt.legend()
>>> plt.show()
Definition at line 539 of file _bsplines.py.
qspline1d_eval()
scipy.signal._bsplines.qspline1d_eval (cj, newx, dx = 1.0, x0 = 0)
Evaluate a quadratic spline at the new set of points.
Parameters
----------
cj : ndarray
    Quadratic spline coefficients
newx : ndarray
    New set of points.
dx : float, optional
    Old sample-spacing, the default value is 1.0.
x0 : int, optional
    Old origin, the default value is 0.
Returns
-------
res : ndarray
    Evaluated a quadratic spline points.
See Also
--------
qspline1d : Compute quadratic spline coefficients for rank-1 array.
Notes
-----
`dx` is the old sample-spacing while `x0` was the old origin. In
other-words the old-sample points (knot-points) for which the `cj`
represent spline coefficients were at equally-spaced points of::
  oldx = x0 + j*dx  j=0...N-1, with N=len(cj)
Edges are handled using mirror-symmetric boundary conditions.
Examples
--------
We can filter a signal to reduce and smooth out high-frequency noise with
a quadratic spline:
>>> import numpy as np
>>> import matplotlib.pyplot as plt
>>> from scipy.signal import qspline1d, qspline1d_eval
>>> rng = np.random.default_rng()
>>> sig = np.repeat([0., 1., 0.], 100)
>>> sig += rng.standard_normal(len(sig))*0.05  # add noise
>>> time = np.linspace(0, len(sig))
>>> filtered = qspline1d_eval(qspline1d(sig), time)
>>> plt.plot(sig, label="signal")
>>> plt.plot(time, filtered, label="filtered")
>>> plt.legend()
>>> plt.show()
Definition at line 664 of file _bsplines.py.
References qspline1d_eval().
Referenced by qspline1d_eval().
quadratic()
scipy.signal._bsplines.quadratic (x)
A quadratic B-spline.
This is a special case of `bspline`, and equivalent to ``bspline(x, 2)``.
Parameters
----------
x : array_like
    a knot vector
Returns
-------
res : ndarray
    Quadratic B-spline basis function values
See Also
--------
bspline : B-spline basis function of order n
cubic : A cubic B-spline.
Examples
--------
We can calculate B-Spline basis function of several orders:
>>> import numpy as np
>>> from scipy.signal import bspline, cubic, quadratic
>>> bspline(0.0, 1)
1
>>> knots = [-1.0, 0.0, -1.0]
>>> bspline(knots, 2)
array([0.125, 0.75, 0.125])
>>> np.array_equal(bspline(knots, 2), quadratic(knots))
True
>>> np.array_equal(bspline(knots, 3), cubic(knots))
True
Definition at line 346 of file _bsplines.py.
spline_filter()
scipy.signal._bsplines.spline_filter (Iin, lmbda = 5.0)
Smoothing spline (cubic) filtering of a rank-2 array.
Filter an input data set, `Iin`, using a (cubic) smoothing spline of
fall-off `lmbda`.
Parameters
----------
Iin : array_like
    input data set
lmbda : float, optional
    spline smooghing fall-off value, default is `5.0`.
Returns
-------
res : ndarray
    filterd input data
Examples
--------
We can filter an multi dimentional signal (ex: 2D image) using cubic
B-spline filter:
>>> import numpy as np
>>> from scipy.signal import spline_filter
>>> import matplotlib.pyplot as plt
>>> orig_img = np.eye(20)  # create an image
>>> orig_img[10, :] = 1.0
>>> sp_filter = spline_filter(orig_img, lmbda=0.1)
>>> f, ax = plt.subplots(1, 2, sharex=True)
>>> for ind, data in enumerate([[orig_img, "original image"],
...                             [sp_filter, "spline filter"]]):
...     ax[ind].imshow(data[0], cmap='gray_r')
...     ax[ind].set_title(data[1])
>>> plt.tight_layout()
>>> plt.show()
Definition at line 18 of file _bsplines.py.
Variable Documentation
__all__
list scipy.signal._bsplines.__all__ private
Initial value:
=  ['spline_filter', 'bspline', 'gauss_spline', 'cubic', 'quadratic',
           'cspline1d', 'qspline1d', 'cspline1d_eval', 'qspline1d_eval']
Definition at line 14 of file _bsplines.py.
_splinefunc_cache
dict scipy.signal._bsplines._splinefunc_cache = {} protected
Definition at line 74 of file _bsplines.py.
msg_bspline
str scipy.signal._bsplines.msg_bspline
Initial value:
=  """`scipy.signal.bspline` is deprecated in SciPy 1.11 and will be
removed in SciPy 1.13.
The exact equivalent (for a float array `x`) is
>>> from scipy.interpolate import BSpline
>>> knots = np.arange(-(n+1)/2, (n+3)/2)
>>> out = BSpline.basis_element(knots)(x)
>>> out[(x < knots[0]) | (x > knots[-1])] = 0.0
"""
Definition at line 145 of file _bsplines.py.
msg_cubic
str scipy.signal._bsplines.msg_cubic
Initial value:
=  """`scipy.signal.cubic` is deprecated in SciPy 1.11 and will be
removed in SciPy 1.13.
The exact equivalent (for a float array `x`) is
>>> from scipy.interpolate import BSpline
>>> out = BSpline.basis_element([-2, -1, 0, 1, 2])(x)
>>> out[(x < -2 | (x > 2)] = 0.0
"""
Definition at line 261 of file _bsplines.py.
msg_quadratic
str scipy.signal._bsplines.msg_quadratic
Initial value:
=  """`scipy.signal.quadratic` is deprecated in SciPy 1.11 and
will be removed in SciPy 1.13.
The exact equivalent (for a float array `x`) is
>>> from scipy.interpolate import BSpline
>>> out = BSpline.basis_element([-1.5, -0.5, 0.5, 1.5])(x)
>>> out[(x < -1.5 | (x > 1.5)] = 0.0
"""
Definition at line 334 of file _bsplines.py.