Code Cloning Analysis: sklearn.datasets._rcv1 Namespace Reference
sklearn.datasets._rcv1 Namespace Reference
Functions
fetch_rcv1 (*, data_home=None, subset="all", download_if_missing=True, random_state=None, shuffle=False, return_X_y=False, n_retries=3, delay=1.0)
_inverse_permutation (p)
_find_permutation (a, b)
Variables
tuple XY_METADATA
TOPICS_METADATA
logger = logging.getLogger(__name__)
Detailed Description
RCV1 dataset.
The dataset page is available at
    http://jmlr.csail.mit.edu/papers/volume5/lewis04a/
Function Documentation
_find_permutation()
sklearn.datasets._rcv1._find_permutation (a, b) protected
Find the permutation from a to b.
Definition at line 329 of file _rcv1.py.
References _inverse_permutation().
Referenced by fetch_rcv1().
_inverse_permutation()
sklearn.datasets._rcv1._inverse_permutation (p) protected
Inverse permutation p.
Definition at line 320 of file _rcv1.py.
Referenced by _find_permutation().
fetch_rcv1()
sklearn.datasets._rcv1.fetch_rcv1 (* , data_home = None, subset = "all", download_if_missing = True, random_state = None, shuffle = False, return_X_y = False, n_retries = 3, delay = 1.0)
Load the RCV1 multilabel dataset (classification).
Download it if necessary.
Version: RCV1-v2, vectors, full sets, topics multilabels.
=================   =====================
Classes                               103
Samples total                      804414
Dimensionality                      47236
Features            real, between 0 and 1
=================   =====================
Read more in the :ref:`User Guide <rcv1_dataset>`.
.. versionadded:: 0.17
Parameters
----------
data_home : str or path-like, default=None
    Specify another download and cache folder for the datasets. By default
    all scikit-learn data is stored in '~/scikit_learn_data' subfolders.
subset : {'train', 'test', 'all'}, default='all'
    Select the dataset to load: 'train' for the training set
    (23149 samples), 'test' for the test set (781265 samples),
    'all' for both, with the training samples first if shuffle is False.
    This follows the official LYRL2004 chronological split.
download_if_missing : bool, default=True
    If False, raise an OSError if the data is not locally available
    instead of trying to download the data from the source site.
random_state : int, RandomState instance or None, default=None
    Determines random number generation for dataset shuffling. Pass an int
    for reproducible output across multiple function calls.
    See :term:`Glossary <random_state>`.
shuffle : bool, default=False
    Whether to shuffle dataset.
return_X_y : bool, default=False
    If True, returns ``(dataset.data, dataset.target)`` instead of a Bunch
    object. See below for more information about the `dataset.data` and
    `dataset.target` object.
    .. versionadded:: 0.20
n_retries : int, default=3
    Number of retries when HTTP errors are encountered.
    .. versionadded:: 1.5
delay : float, default=1.0
    Number of seconds between retries.
    .. versionadded:: 1.5
Returns
-------
dataset : :class:`~sklearn.utils.Bunch`
    Dictionary-like object. Returned only if `return_X_y` is False.
    `dataset` has the following attributes:
    - data : sparse matrix of shape (804414, 47236), dtype=np.float64
        The array has 0.16% of non zero values. Will be of CSR format.
    - target : sparse matrix of shape (804414, 103), dtype=np.uint8
        Each sample has a value of 1 in its categories, and 0 in others.
        The array has 3.15% of non zero values. Will be of CSR format.
    - sample_id : ndarray of shape (804414,), dtype=np.uint32,
        Identification number of each sample, as ordered in dataset.data.
    - target_names : ndarray of shape (103,), dtype=object
        Names of each target (RCV1 topics), as ordered in dataset.target.
    - DESCR : str
        Description of the RCV1 dataset.
(data, target) : tuple
    A tuple consisting of `dataset.data` and `dataset.target`, as
    described above. Returned only if `return_X_y` is True.
    .. versionadded:: 0.20
Examples
--------
>>> from sklearn.datasets import fetch_rcv1
>>> rcv1 = fetch_rcv1()
>>> rcv1.data.shape
(804414, 47236)
>>> rcv1.target.shape
(804414, 103)
Definition at line 89 of file _rcv1.py.
References _find_permutation().
Variable Documentation
logger
sklearn.datasets._rcv1.logger = logging.getLogger(__name__)
Definition at line 73 of file _rcv1.py.
TOPICS_METADATA
sklearn.datasets._rcv1.TOPICS_METADATA
Initial value:
=  RemoteFileMetadata(
    url="https://ndownloader.figshare.com/files/5976048",
    checksum="2a98e5e5d8b770bded93afc8930d88299474317fe14181aee1466cc754d0d1c1",
    filename="rcv1v2.topics.qrels.gz",
)
Definition at line 67 of file _rcv1.py.
XY_METADATA
tuple sklearn.datasets._rcv1.XY_METADATA
Initial value:
=  (
    RemoteFileMetadata(
        url="https://ndownloader.figshare.com/files/5976069",
        checksum="ed40f7e418d10484091b059703eeb95ae3199fe042891dcec4be6696b9968374",
        filename="lyrl2004_vectors_test_pt0.dat.gz",
    ),
    RemoteFileMetadata(
        url="https://ndownloader.figshare.com/files/5976066",
        checksum="87700668ae45d45d5ca1ef6ae9bd81ab0f5ec88cc95dcef9ae7838f727a13aa6",
        filename="lyrl2004_vectors_test_pt1.dat.gz",
    ),
    RemoteFileMetadata(
        url="https://ndownloader.figshare.com/files/5976063",
        checksum="48143ac703cbe33299f7ae9f4995db49a258690f60e5debbff8995c34841c7f5",
        filename="lyrl2004_vectors_test_pt2.dat.gz",
    ),
    RemoteFileMetadata(
        url="https://ndownloader.figshare.com/files/5976060",
        checksum="dfcb0d658311481523c6e6ca0c3f5a3e1d3d12cde5d7a8ce629a9006ec7dbb39",
        filename="lyrl2004_vectors_test_pt3.dat.gz",
    ),
    RemoteFileMetadata(
        url="https://ndownloader.figshare.com/files/5976057",
        checksum="5468f656d0ba7a83afc7ad44841cf9a53048a5c083eedc005dcdb5cc768924ae",
        filename="lyrl2004_vectors_train.dat.gz",
    ),
)
Definition at line 37 of file _rcv1.py.