Code Cloning Analysis: matplotlib._mathtext.Output Class Reference
matplotlib._mathtext.Output Class Reference
Public Member Functions
__init__ (self, Box box)
VectorParse to_vector (self)
RasterParse to_raster (self, *, bool antialiased)
Public Attributes
box = box
list glyphs = []
list rects = []
Detailed Description
Result of `ship`\ping a box: lists of positioned glyphs and rectangles.
This class is not exposed to end users, but converted to a `VectorParse` or
a `RasterParse` by `.MathTextParser.parse`.
Definition at line 120 of file _mathtext.py.
Constructor & Destructor Documentation
__init__()
matplotlib._mathtext.Output.__init__ (self, Box box)
Definition at line 128 of file _mathtext.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
to_raster()
RasterParse matplotlib._mathtext.Output.to_raster (self, * , bool antialiased)
Definition at line 142 of file _mathtext.py.
to_vector()
VectorParse matplotlib._mathtext.Output.to_vector (self)
Definition at line 133 of file _mathtext.py.
Member Data Documentation
box
matplotlib._mathtext.Output.box = box
Definition at line 129 of file _mathtext.py.
Referenced by axes_grid1.anchored_artists.AnchoredDirectionArrows.__init__(), pip._vendor.rich.table.Table._extra_width(), pip._vendor.rich.table.Table._measure_column(), and pip._vendor.rich.panel.Panel.fit().
glyphs
list matplotlib._mathtext.Output.glyphs = []
Definition at line 130 of file _mathtext.py.
Referenced by fontTools.ttLib.woff2.WOFF2GlyfTable.reconstruct(), and fontTools.ttLib.woff2.WOFF2GlyfTable.transform().
rects
list matplotlib._mathtext.Output.rects = []
Definition at line 131 of file _mathtext.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/_mathtext.py