Code Cloning Analysis: scipy._lib._util.MapWrapper Class Reference
scipy._lib._util.MapWrapper Class Reference
Public Member Functions
__init__ (self, pool=1)
__enter__ (self)
terminate (self)
join (self)
close (self)
__exit__ (self, exc_type, exc_value, traceback)
__call__ (self, func, iterable)
Public Attributes
pool = None
Protected Attributes
_mapfunc = map
bool _own_pool = False
Detailed Description
Parallelisation wrapper for working with map-like callables, such as
`multiprocessing.Pool.map`.
Parameters
----------
pool : int or map-like callable
    If `pool` is an integer, then it specifies the number of threads to
    use for parallelization. If ``int(pool) == 1``, then no parallel
    processing is used and the map builtin is used.
    If ``pool == -1``, then the pool will utilize all available CPUs.
    If `pool` is a map-like callable that follows the same
    calling sequence as the built-in map function, then this callable is
    used for parallelization.
Definition at line 363 of file _util.py.
Constructor & Destructor Documentation
__init__()
scipy._lib._util.MapWrapper.__init__ (self, pool = 1)
Definition at line 379 of file _util.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
__call__()
scipy._lib._util.MapWrapper.__call__ (self, func, iterable)
Definition at line 427 of file _util.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), and scipy.interpolate._fitpack2.SphereBivariateSpline.ev().
__enter__()
scipy._lib._util.MapWrapper.__enter__ (self)
Definition at line 407 of file _util.py.
__exit__()
scipy._lib._util.MapWrapper.__exit__ (self, exc_type, exc_value, traceback)
Definition at line 422 of file _util.py.
close()
scipy._lib._util.MapWrapper.close (self)
Definition at line 418 of file _util.py.
Referenced by scipy.io._fortran.FortranFile.close(), and scipy.io._netcdf.netcdf_file.close().
join()
scipy._lib._util.MapWrapper.join (self)
Definition at line 414 of file _util.py.
terminate()
scipy._lib._util.MapWrapper.terminate (self)
Definition at line 410 of file _util.py.
Member Data Documentation
_mapfunc
scipy._lib._util.MapWrapper._mapfunc = map protected
Definition at line 381 of file _util.py.
_own_pool
bool scipy._lib._util.MapWrapper._own_pool = False protected
Definition at line 382 of file _util.py.
pool
scipy._lib._util.MapWrapper.pool = None
Definition at line 380 of file _util.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/_lib/_util.py