Code Cloning Analysis: pandas._version Namespace Reference
pandas._version Namespace Reference
Classes
class NotThisMethod
class VersioneerConfig
Functions
get_keywords ()
get_config ()
register_vcs_handler (vcs, method)
run_command (commands, args, cwd=None, verbose=False, hide_stderr=False, env=None)
versions_from_parentdir (parentdir_prefix, root, verbose)
git_get_keywords (versionfile_abs)
git_versions_from_keywords (keywords, tag_prefix, verbose)
git_pieces_from_vcs (tag_prefix, root, verbose, runner=run_command)
str plus_or_dot (pieces)
render_pep440 (pieces)
render_pep440_branch (pieces)
pep440_split_post (ver)
render_pep440_pre (pieces)
render_pep440_post (pieces)
render_pep440_post_branch (pieces)
render_pep440_old (pieces)
render_git_describe (pieces)
render_git_describe_long (pieces)
render (pieces, style)
get_versions ()
Detailed Description
Git implementation of _version.py.
Function Documentation
get_config()
pandas._version.get_config ()
Create, populate and return the VersioneerConfig() object.
Definition at line 39 of file _version.py.
Referenced by get_versions().
get_keywords()
pandas._version.get_keywords ()
Get the keywords needed to look up the version information.
Definition at line 22 of file _version.py.
Referenced by get_versions().
get_versions()
pandas._version.get_versions ()
Get version information or return default if unable to do so.
Definition at line 643 of file _version.py.
References get_config(), get_keywords(), git_pieces_from_vcs(), git_versions_from_keywords(), render(), and versions_from_parentdir().
git_get_keywords()
pandas._version.git_get_keywords (versionfile_abs)
Extract version information from the given file.
Definition at line 151 of file _version.py.
git_pieces_from_vcs()
pandas._version.git_pieces_from_vcs (tag_prefix, root, verbose, runner = run_command)
Get version from 'git describe' in the root of the source tree.
This only gets called if the git-archive 'subst' keywords were *not*
expanded, and _version.py hasn't already been rewritten with a short
version string, meaning we're inside a checked out source tree.
Definition at line 250 of file _version.py.
Referenced by get_versions().
git_versions_from_keywords()
pandas._version.git_versions_from_keywords (keywords, tag_prefix, verbose)
Get version information from git keywords.
Definition at line 179 of file _version.py.
Referenced by get_versions().
pep440_split_post()
pandas._version.pep440_split_post (ver)
Split pep440 version string at the post-release segment.
Returns the release segments before the post-release and the
post-release version number (or -1 if no post-release segment is present).
Definition at line 449 of file _version.py.
Referenced by render_pep440_pre().
plus_or_dot()
str pandas._version.plus_or_dot (pieces)
Return a + if we don't already have one, else return a .
Definition at line 389 of file _version.py.
Referenced by render_pep440(), render_pep440_branch(), render_pep440_post(), and render_pep440_post_branch().
register_vcs_handler()
pandas._version.register_vcs_handler (vcs, method)
Create decorator to mark a method as the handler of a VCS.
Definition at line 61 of file _version.py.
render()
pandas._version.render (pieces, style)
Render the given version pieces into the requested style.
Definition at line 601 of file _version.py.
References render_git_describe(), render_git_describe_long(), render_pep440(), render_pep440_branch(), render_pep440_old(), render_pep440_post(), render_pep440_post_branch(), and render_pep440_pre().
Referenced by get_versions().
render_git_describe()
pandas._version.render_git_describe (pieces)
TAG[-DISTANCE-gHEX][-dirty].
Like 'git describe --tags --dirty --always'.
Exceptions:
1: no tags. HEX[-dirty]  (note: no 'g' prefix)
Definition at line 561 of file _version.py.
Referenced by render().
render_git_describe_long()
pandas._version.render_git_describe_long (pieces)
TAG-DISTANCE-gHEX[-dirty].
Like 'git describe --tags --dirty --always -long'.
The distance/hash is unconditional.
Exceptions:
1: no tags. HEX[-dirty]  (note: no 'g' prefix)
Definition at line 581 of file _version.py.
Referenced by render().
render_pep440()
pandas._version.render_pep440 (pieces)
Build up version string, with post-release "local version identifier".
Our goal: TAG[+DISTANCE.gHEX[.dirty]] . Note that if you
get a tagged build and then dirty it, you'll get TAG+0.gHEX.dirty
Exceptions:
1: no tags. git_describe was just HEX. 0+untagged.DISTANCE.gHEX[.dirty]
Definition at line 396 of file _version.py.
References plus_or_dot().
Referenced by render().
render_pep440_branch()
pandas._version.render_pep440_branch (pieces)
TAG[[.dev0]+DISTANCE.gHEX[.dirty]] .
The ".dev0" means not master branch. Note that .dev0 sorts backwards
(a feature branch will appear "older" than the master branch).
Exceptions:
1: no tags. 0[.dev0]+untagged.DISTANCE.gHEX[.dirty]
Definition at line 420 of file _version.py.
References plus_or_dot().
Referenced by render().
render_pep440_old()
pandas._version.render_pep440_old (pieces)
TAG[.postDISTANCE[.dev0]] .
The ".dev0" means dirty.
Exceptions:
1: no tags. 0.postDISTANCE[.dev0]
Definition at line 539 of file _version.py.
Referenced by render().
render_pep440_post()
pandas._version.render_pep440_post (pieces)
TAG[.postDISTANCE[.dev0]+gHEX] .
The ".dev0" means dirty. Note that .dev0 sorts backwards
(a dirty tree will appear "older" than the corresponding clean one),
but you shouldn't be releasing software with -dirty anyways.
Exceptions:
1: no tags. 0.postDISTANCE[.dev0]
Definition at line 483 of file _version.py.
References plus_or_dot().
Referenced by render().
render_pep440_post_branch()
pandas._version.render_pep440_post_branch (pieces)
TAG[.postDISTANCE[.dev0]+gHEX[.dirty]] .
The ".dev0" means not master branch.
Exceptions:
1: no tags. 0.postDISTANCE[.dev0]+gHEX[.dirty]
Definition at line 510 of file _version.py.
References plus_or_dot().
Referenced by render().
render_pep440_pre()
pandas._version.render_pep440_pre (pieces)
TAG[.postN.devDISTANCE] -- No -dirty.
Exceptions:
1: no tags. 0.post0.devDISTANCE
Definition at line 459 of file _version.py.
References pep440_split_post().
Referenced by render().
run_command()
pandas._version.run_command (commands, args, cwd = None, verbose = False, hide_stderr = False, env = None)
Call the given command(s).
Definition at line 74 of file _version.py.
versions_from_parentdir()
pandas._version.versions_from_parentdir (parentdir_prefix, root, verbose)
Try to determine the version from the parent directory name.
Source tarballs conventionally unpack into a directory that includes both
the project name and a version string. We will also support searching up
two directory levels for an appropriately named parent directory
Definition at line 120 of file _version.py.
Referenced by get_versions().