Code Cloning Analysis: pandas.core.computation.engines.PythonEngine Class Reference
pandas.core.computation.engines.PythonEngine Class Reference
Public Member Functions
evaluate (self)
Public Member Functions inherited from pandas.core.computation.engines.AbstractEngine
None __init__ (self, expr)
str convert (self)
Static Public Attributes
dict ENGINES
Static Public Attributes inherited from pandas.core.computation.engines.AbstractEngine
bool has_neg_frac = False
Protected Member Functions
None _evaluate (self)
Protected Member Functions inherited from pandas.core.computation.engines.AbstractEngine
bool _is_aligned (self)
Additional Inherited Members
Public Attributes inherited from pandas.core.computation.engines.AbstractEngine
expr = expr
aligned_axes = None
result_type = None
Protected Attributes inherited from pandas.core.computation.engines.AbstractEngine
_is_aligned
Detailed Description
Evaluate an expression in Python space.
Mostly for testing purposes.
Definition at line 124 of file engines.py.
Member Function Documentation
_evaluate()
None pandas.core.computation.engines.PythonEngine._evaluate (self) protected
Return an evaluated expression.
Parameters
----------
env : Scope
    The local and global environment in which to evaluate an
    expression.
Notes
-----
Must be implemented by subclasses.
Reimplemented from pandas.core.computation.engines.AbstractEngine.
Definition at line 136 of file engines.py.
Referenced by scipy.interpolate._bsplines.BSpline.__call__(), scipy.interpolate._interpolate._PPolyBase.__call__(), and scipy.interpolate._polyint._Interpolator1D.__call__().
evaluate()
pandas.core.computation.engines.PythonEngine.evaluate (self)
Run the engine on the expression.
This method performs alignment which is necessary no matter what engine
is being used, thus its implementation is in the base class.
Returns
-------
object
    The result of the passed expression.
Reimplemented from pandas.core.computation.engines.AbstractEngine.
Definition at line 133 of file engines.py.
References pandas.core.computation.engines.AbstractEngine.expr.
Referenced by pip._vendor.distlib.markers.Evaluator.evaluate(), scipy.stats._kde.gaussian_kde.pdf(), and scipy.stats._survival.EmpiricalDistributionFunction.plot().
Member Data Documentation
ENGINES
dict pandas.core.computation.engines.PythonEngine.ENGINES static
Initial value:
=  {
    "numexpr": NumExprEngine,
    "python": PythonEngine,
}
Definition at line 140 of file engines.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/core/computation/engines.py