Code Cloning Analysis: scipy.spatial._kdtree Namespace Reference
scipy.spatial._kdtree Namespace Reference
Classes
class KDTree
class Rectangle
Functions
minkowski_distance_p (x, y, p=2)
minkowski_distance (x, y, p=2)
distance_matrix (x, y, p=2, threshold=1000000)
Variables
list __all__
Function Documentation
distance_matrix()
scipy.spatial._kdtree.distance_matrix (x, y, p = 2, threshold = 1000000)
Compute the distance matrix.
Returns the matrix of all pair-wise distances.
Parameters
----------
x : (M, K) array_like
    Matrix of M vectors in K dimensions.
y : (N, K) array_like
    Matrix of N vectors in K dimensions.
p : float, 1 <= p <= infinity
    Which Minkowski p-norm to use.
threshold : positive int
    If ``M * N * K`` > `threshold`, algorithm uses a Python loop instead
    of large temporary arrays.
Returns
-------
result : (M, N) ndarray
    Matrix containing the distance from every vector in `x` to every vector
    in `y`.
Examples
--------
>>> from scipy.spatial import distance_matrix
>>> distance_matrix([[0,0],[0,1]], [[1,0],[1,1]])
array([[ 1.        ,  1.41421356],
       [ 1.41421356,  1.        ]])
Definition at line 869 of file _kdtree.py.
References minkowski_distance().
minkowski_distance()
scipy.spatial._kdtree.minkowski_distance (x, y, p = 2)
Compute the L**p distance between two arrays.
The last dimensions of `x` and `y` must be the same length.  Any
other dimensions must be compatible for broadcasting.
Parameters
----------
x : (..., K) array_like
    Input array.
y : (..., K) array_like
    Input array.
p : float, 1 <= p <= infinity
    Which Minkowski p-norm to use.
Returns
-------
dist : ndarray
    Distance between the input arrays.
Examples
--------
>>> from scipy.spatial import minkowski_distance
>>> minkowski_distance([[0, 0], [0, 0]], [[1, 1], [0, 1]])
array([ 1.41421356,  1.        ])
Definition at line 63 of file _kdtree.py.
References minkowski_distance_p().
Referenced by distance_matrix(), scipy.spatial.tests.test_kdtree.KDTreeTest(), scipy.spatial._kdtree.Rectangle.max_distance_point(), scipy.spatial._kdtree.Rectangle.max_distance_rectangle(), scipy.spatial._kdtree.Rectangle.min_distance_point(), and scipy.spatial._kdtree.Rectangle.min_distance_rectangle().
minkowski_distance_p()
scipy.spatial._kdtree.minkowski_distance_p (x, y, p = 2)
Compute the pth power of the L**p distance between two arrays.
For efficiency, this function computes the L**p distance but does
not extract the pth root. If `p` is 1 or infinity, this is equal to
the actual L**p distance.
The last dimensions of `x` and `y` must be the same length.  Any
other dimensions must be compatible for broadcasting.
Parameters
----------
x : (..., K) array_like
    Input array.
y : (..., K) array_like
    Input array.
p : float, 1 <= p <= infinity
    Which Minkowski p-norm to use.
Returns
-------
dist : ndarray
    pth power of the distance between the input arrays.
Examples
--------
>>> from scipy.spatial import minkowski_distance_p
>>> minkowski_distance_p([[0, 0], [0, 0]], [[1, 1], [0, 1]])
array([2, 1])
Definition at line 11 of file _kdtree.py.
Referenced by minkowski_distance().
Variable Documentation
__all__
list scipy.spatial._kdtree.__all__ private
Initial value:
=  ['minkowski_distance_p', 'minkowski_distance',
           'distance_matrix',
           'Rectangle', 'KDTree']
Definition at line 6 of file _kdtree.py.