Code Cloning Analysis: scipy.stats.tests.test_fit.TestFit Class Reference
scipy.stats.tests.test_fit.TestFit Class Reference
Public Member Functions
opt (self, *args, **kwds)
test_dist_iv (self)
test_data_iv (self)
test_bounds_iv (self)
test_guess_iv (self)
basic_fit_test (self, dist_name, method)
test_basic_fit_mle (self, dist_name)
test_basic_fit_mse (self, dist_name)
test_argus (self)
test_foldnorm (self)
test_truncpareto (self)
test_truncweibull_min (self)
test_missing_shape_bounds (self)
test_fit_only_loc_scale (self)
test_everything_fixed (self)
test_failure (self)
test_guess (self)
test_mse_accuracy_1 (self)
test_mse_accuracy_2 (self)
Static Public Attributes
dist = stats.binom
int seed = 654634816187
rng = np.random.default_rng(seed)
data = stats.binom.rvs(5, 0.5, size=100, random_state=rng)
list shape_bounds_a = [(1, 10), (0, 1)]
dict shape_bounds_d = {'n': (1, 10), 'p': (0, 1)}
int atol = 5e-2
int rtol = 1e-2
dict tols = {'atol': atol, 'rtol': rtol}
Detailed Description
Definition at line 353 of file test_fit.py.
Member Function Documentation
basic_fit_test()
scipy.stats.tests.test_fit.TestFit.basic_fit_test (self, dist_name, method)
Definition at line 483 of file test_fit.py.
opt()
scipy.stats.tests.test_fit.TestFit.opt (self, * args, ** kwds)
Definition at line 364 of file test_fit.py.
test_argus()
scipy.stats.tests.test_fit.TestFit.test_argus (self)
Definition at line 525 of file test_fit.py.
test_basic_fit_mle()
scipy.stats.tests.test_fit.TestFit.test_basic_fit_mle (self, dist_name)
Definition at line 518 of file test_fit.py.
test_basic_fit_mse()
scipy.stats.tests.test_fit.TestFit.test_basic_fit_mse (self, dist_name)
Definition at line 522 of file test_fit.py.
test_bounds_iv()
scipy.stats.tests.test_fit.TestFit.test_bounds_iv (self)
Definition at line 385 of file test_fit.py.
test_data_iv()
scipy.stats.tests.test_fit.TestFit.test_data_iv (self)
Definition at line 372 of file test_fit.py.
test_dist_iv()
scipy.stats.tests.test_fit.TestFit.test_dist_iv (self)
Definition at line 367 of file test_fit.py.
test_everything_fixed()
scipy.stats.tests.test_fit.TestFit.test_everything_fixed (self)
Definition at line 631 of file test_fit.py.
test_failure()
scipy.stats.tests.test_fit.TestFit.test_failure (self)
Definition at line 656 of file test_fit.py.
test_fit_only_loc_scale()
scipy.stats.tests.test_fit.TestFit.test_fit_only_loc_scale (self)
Definition at line 602 of file test_fit.py.
test_foldnorm()
scipy.stats.tests.test_fit.TestFit.test_foldnorm (self)
Definition at line 539 of file test_fit.py.
test_guess()
scipy.stats.tests.test_fit.TestFit.test_guess (self)
Definition at line 673 of file test_fit.py.
test_guess_iv()
scipy.stats.tests.test_fit.TestFit.test_guess_iv (self)
Definition at line 436 of file test_fit.py.
test_missing_shape_bounds()
scipy.stats.tests.test_fit.TestFit.test_missing_shape_bounds (self)
Definition at line 581 of file test_fit.py.
test_mse_accuracy_1()
scipy.stats.tests.test_fit.TestFit.test_mse_accuracy_1 (self)
Definition at line 689 of file test_fit.py.
test_mse_accuracy_2()
scipy.stats.tests.test_fit.TestFit.test_mse_accuracy_2 (self)
Definition at line 700 of file test_fit.py.
test_truncpareto()
scipy.stats.tests.test_fit.TestFit.test_truncpareto (self)
Definition at line 553 of file test_fit.py.
test_truncweibull_min()
scipy.stats.tests.test_fit.TestFit.test_truncweibull_min (self)
Definition at line 567 of file test_fit.py.
Member Data Documentation
atol
int scipy.stats.tests.test_fit.TestFit.atol = 5e-2 static
Definition at line 360 of file test_fit.py.
Referenced by sklearn.neighbors._kde.KernelDensity.score_samples().
data
scipy.stats.tests.test_fit.TestFit.data = stats.binom.rvs(5, 0.5, size=100, random_state=rng) static
Definition at line 357 of file test_fit.py.
Referenced by pandas.tests.extension.decimal.array.DecimalArray._reduce(), matplotlib.backends.backend_svg.XMLWriter.element(), numpy.core._internal._ctypes.get_data(), and PIL.GifImagePlugin.GifImageFile.seek().
dist
scipy.stats.tests.test_fit.TestFit.dist = stats.binom static
Definition at line 354 of file test_fit.py.
rng
scipy.stats.tests.test_fit.TestFit.rng = np.random.default_rng(seed) static
Definition at line 356 of file test_fit.py.
Referenced by sklearn.gaussian_process._gpc._BinaryGaussianProcessClassifierLaplace.fit().
rtol
int scipy.stats.tests.test_fit.TestFit.rtol = 1e-2 static
Definition at line 361 of file test_fit.py.
Referenced by sklearn.neighbors._kde.KernelDensity.score_samples(), scipy.stats.tests.test_resampling.TestPermutationTest.test_against_spearmanr_in_R(), and scipy.stats.tests.test_resampling.TestPermutationTest.test_with_ties().
seed
int scipy.stats.tests.test_fit.TestFit.seed = 654634816187 static
Definition at line 355 of file test_fit.py.
shape_bounds_a
scipy.stats.tests.test_fit.TestFit.shape_bounds_a = [(1, 10), (0, 1)] static
Definition at line 358 of file test_fit.py.
shape_bounds_d
scipy.stats.tests.test_fit.TestFit.shape_bounds_d = {'n': (1, 10), 'p': (0, 1)} static
Definition at line 359 of file test_fit.py.
tols
scipy.stats.tests.test_fit.TestFit.tols = {'atol': atol, 'rtol': rtol} static
Definition at line 362 of file test_fit.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/stats/tests/test_fit.py