Code Cloning Analysis: pip._vendor.typing_extensions.Annotated Class Reference
pip._vendor.typing_extensions.Annotated Class Reference
Public Member Functions
__new__ (cls, *args, **kwargs)
__class_getitem__ (cls, params)
__init_subclass__ (cls, *args, **kwargs)
Static Private Attributes
tuple __slots__ = ()
Detailed Description
Add context specific metadata to a type.
Example: Annotated[int, runtime_check.Unsigned] indicates to the
hypothetical runtime_check module that this type is an unsigned int.
Every other consumer of this type can ignore this metadata and treat
this type as int.
The first argument to Annotated must be a valid type (and will be in
the __origin__ field), the remaining arguments are kept as a tuple in
the __extra__ field.
Details:
- It's an error to call `Annotated` with less than two arguments.
- Nested Annotated are flattened::
    Annotated[Annotated[T, Ann1, Ann2], Ann3] == Annotated[T, Ann1, Ann2, Ann3]
- Instantiating an annotated type is equivalent to instantiating the
underlying type::
    Annotated[C, Ann1](5) == C(5)
- Annotated can be used as a generic type alias::
    Optimized = Annotated[T, runtime.Optimize()]
    Optimized[int] == Annotated[int, runtime.Optimize()]
    OptimizedList = Annotated[List[T], runtime.Optimize()]
    OptimizedList[int] == Annotated[List[int], runtime.Optimize()]
Definition at line 1323 of file typing_extensions.py.
Member Function Documentation
__class_getitem__()
pip._vendor.typing_extensions.Annotated.__class_getitem__ (cls, params)
Definition at line 1362 of file typing_extensions.py.
__init_subclass__()
pip._vendor.typing_extensions.Annotated.__init_subclass__ (cls, * args, ** kwargs)
Definition at line 1376 of file typing_extensions.py.
__new__()
pip._vendor.typing_extensions.Annotated.__new__ (cls, * args, ** kwargs)
Definition at line 1358 of file typing_extensions.py.
Referenced by matplotlib.path.Path._fast_from_codes_and_verts(), pandas.core.generic.NDFrame._from_mgr(), pandas.core.arrays.string_.StringArray._from_sequence(), scipy.interpolate._fitpack2._BivariateSplineBase._from_tck(), scipy.interpolate._fitpack2.UnivariateSpline._from_tck(), matplotlib.colors.Colormap._get_rgba_and_mask(), pip._vendor.rich.style.Style.clear_meta_and_links(), matplotlib.colors.MultivarColormap.copy(), pip._vendor.rich.style.Style.copy(), pip._vendor.rich.style.Style.from_color(), pip._vendor.rich.json.JSON.from_data(), pip._vendor.rich.style.Style.from_meta(), matplotlib.colors.BivarColormap.lut(), pip._vendor.rich.style.Style.test(), pip._vendor.rich.style.Style.update_link(), and pip._vendor.rich.style.Style.without_color().
Member Data Documentation
__slots__
tuple pip._vendor.typing_extensions.Annotated.__slots__ = () static private
Definition at line 1356 of file typing_extensions.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pip/_vendor/typing_extensions.py