Code Cloning Analysis: pip._vendor.tenacity.wait.wait_random Class Reference
pip._vendor.tenacity.wait.wait_random Class Reference
Public Member Functions
None __init__ (self, _utils.time_unit_type min=0, _utils.time_unit_type max=1)
float __call__ (self, "RetryCallState" retry_state)
Public Member Functions inherited from pip._vendor.tenacity.wait.wait_base
float __call__ (self, "RetryCallState" retry_state)
"wait_combine" __add__ (self, "wait_base" other)
typing.Union["wait_combine", "wait_base"] __radd__ (self, "wait_base" other)
Public Attributes
wait_random_min = _utils.to_seconds(min)
wait_random_max = _utils.to_seconds(max)
Detailed Description
Wait strategy that waits a random amount of time between min/max.
Definition at line 64 of file wait.py.
Constructor & Destructor Documentation
__init__()
None pip._vendor.tenacity.wait.wait_random.__init__ (self, _utils.time_unit_type min = 0, _utils.time_unit_type max = 1)
Definition at line 67 of file wait.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
__call__()
float pip._vendor.tenacity.wait.wait_random.__call__ (self, "RetryCallState" retry_state)
Definition at line 71 of file wait.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), and scipy.interpolate._fitpack2.SphereBivariateSpline.ev().
Member Data Documentation
wait_random_max
pip._vendor.tenacity.wait.wait_random.wait_random_max = _utils.to_seconds(max)
Definition at line 69 of file wait.py.
wait_random_min
pip._vendor.tenacity.wait.wait_random.wait_random_min = _utils.to_seconds(min)
Definition at line 68 of file wait.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pip/_vendor/tenacity/wait.py