Code Cloning Analysis: sklearn.linear_model._ridge.RidgeCV Class Reference
sklearn.linear_model._ridge.RidgeCV Class Reference
Public Member Functions
fit (self, X, y, sample_weight=None, **params)
Public Member Functions inherited from sklearn.base.MultiOutputMixin
__sklearn_tags__ (self)
Public Member Functions inherited from sklearn.base.RegressorMixin
__sklearn_tags__ (self)
score (self, X, y, sample_weight=None)
Public Member Functions inherited from sklearn.linear_model._ridge._BaseRidgeCV
__init__ (self, alphas=(0.1, 1.0, 10.0), *, fit_intercept=True, scoring=None, cv=None, gcv_mode=None, store_cv_results=False, alpha_per_target=False)
get_metadata_routing (self)
__sklearn_tags__ (self)
Public Member Functions inherited from sklearn.linear_model._base.LinearModel
predict (self, X)
Public Member Functions inherited from sklearn.base.BaseEstimator
get_params (self, deep=True)
set_params (self, **params)
__sklearn_clone__ (self)
__repr__ (self, N_CHAR_MAX=700)
__getstate__ (self)
__setstate__ (self, state)
__sklearn_tags__ (self)
Public Member Functions inherited from sklearn.utils._metadata_requests._MetadataRequester
set_fit_request (self, **kwargs)
set_partial_fit_request (self, **kwargs)
set_predict_request (self, **kwargs)
set_predict_proba_request (self, **kwargs)
set_predict_log_proba_request (self, **kwargs)
set_decision_function_request (self, **kwargs)
set_score_request (self, **kwargs)
set_split_request (self, **kwargs)
set_transform_request (self, **kwargs)
set_inverse_transform_request (self, **kwargs)
__init_subclass__ (cls, **kwargs)
Additional Inherited Members
Public Attributes inherited from sklearn.linear_model._ridge._BaseRidgeCV
alphas = alphas
scoring = scoring
cv = cv
gcv_mode = gcv_mode
store_cv_results = store_cv_results
alpha_per_target = alpha_per_target
alpha_ = estimator.alpha_
best_score_ = estimator.best_score_
cv_results_ = estimator.cv_results_
coef_ = estimator.coef_
n_features_in_ = estimator.n_features_in_
feature_names_in_ = estimator.feature_names_in_
Public Attributes inherited from sklearn.linear_model._base.LinearModel
fit_intercept
float intercept_ = intercept_
Protected Member Functions inherited from sklearn.linear_model._ridge._BaseRidgeCV
_get_scorer (self)
Protected Member Functions inherited from sklearn.linear_model._base.LinearModel
_decision_function (self, X)
_set_intercept (self, X_offset, y_offset, X_scale)
Protected Member Functions inherited from sklearn.base.BaseEstimator
_get_param_names (cls)
_get_params_html (self, deep=True)
_validate_params (self)
Protected Member Functions inherited from sklearn.utils._repr_html.base.ReprHTMLMixin
_repr_html_ (self)
_repr_html_inner (self)
_repr_mimebundle_ (self, **kwargs)
Protected Member Functions inherited from sklearn.utils._repr_html.base._HTMLDocumentationLinkMixin
_doc_link_template (self)
_doc_link_template (self, value)
_get_doc_link (self)
Protected Member Functions inherited from sklearn.utils._metadata_requests._MetadataRequester
_build_request_for_signature (cls, router, method)
_get_default_requests (cls)
_get_metadata_request (self)
Protected Attributes inherited from sklearn.base.BaseEstimator
_parameter_constraints
Static Protected Attributes inherited from sklearn.base.RegressorMixin
str _estimator_type = "regressor"
Static Protected Attributes inherited from sklearn.base.BaseEstimator
_html_repr = estimator_html_repr
Static Protected Attributes inherited from sklearn.utils._repr_html.base._HTMLDocumentationLinkMixin
str _doc_link_module = "sklearn"
_doc_link_url_param_generator = None
Detailed Description
Ridge regression with built-in cross-validation.
See glossary entry for :term:`cross-validation estimator`.
By default, it performs efficient Leave-One-Out Cross-Validation.
Read more in the :ref:`User Guide <ridge_regression>`.
Parameters
----------
alphas : array-like of shape (n_alphas,), default=(0.1, 1.0, 10.0)
    Array of alpha values to try.
    Regularization strength; must be a positive float. Regularization
    improves the conditioning of the problem and reduces the variance of
    the estimates. Larger values specify stronger regularization.
    Alpha corresponds to ``1 / (2C)`` in other linear models such as
    :class:`~sklearn.linear_model.LogisticRegression` or
    :class:`~sklearn.svm.LinearSVC`.
    If using Leave-One-Out cross-validation, alphas must be strictly positive.
fit_intercept : bool, default=True
    Whether to calculate the intercept for this model. If set
    to false, no intercept will be used in calculations
    (i.e. data is expected to be centered).
scoring : str, callable, default=None
    The scoring method to use for cross-validation. Options:
    - str: see :ref:`scoring_string_names` for options.
    - callable: a scorer callable object (e.g., function) with signature
      ``scorer(estimator, X, y)``. See :ref:`scoring_callable` for details.
    - `None`: negative :ref:`mean squared error <mean_squared_error>` if cv is
      None (i.e. when using leave-one-out cross-validation), or
      :ref:`coefficient of determination <r2_score>` (:math:`R^2`) otherwise.
cv : int, cross-validation generator or an iterable, default=None
    Determines the cross-validation splitting strategy.
    Possible inputs for cv are:
    - None, to use the efficient Leave-One-Out cross-validation
    - integer, to specify the number of folds.
    - :term:`CV splitter`,
    - An iterable yielding (train, test) splits as arrays of indices.
    For integer/None inputs, if ``y`` is binary or multiclass,
    :class:`~sklearn.model_selection.StratifiedKFold` is used, else,
    :class:`~sklearn.model_selection.KFold` is used.
    Refer :ref:`User Guide <cross_validation>` for the various
    cross-validation strategies that can be used here.
gcv_mode : {'auto', 'svd', 'eigen'}, default='auto'
    Flag indicating which strategy to use when performing
    Leave-One-Out Cross-Validation. Options are::
        'auto' : use 'svd' if n_samples > n_features, otherwise use 'eigen'
        'svd' : force use of singular value decomposition of X when X is
            dense, eigenvalue decomposition of X^T.X when X is sparse.
        'eigen' : force computation via eigendecomposition of X.X^T
    The 'auto' mode is the default and is intended to pick the cheaper
    option of the two depending on the shape of the training data.
store_cv_results : bool, default=False
    Flag indicating if the cross-validation values corresponding to
    each alpha should be stored in the ``cv_results_`` attribute (see
    below). This flag is only compatible with ``cv=None`` (i.e. using
    Leave-One-Out Cross-Validation).
    .. versionchanged:: 1.5
        Parameter name changed from `store_cv_values` to `store_cv_results`.
alpha_per_target : bool, default=False
    Flag indicating whether to optimize the alpha value (picked from the
    `alphas` parameter list) for each target separately (for multi-output
    settings: multiple prediction targets). When set to `True`, after
    fitting, the `alpha_` attribute will contain a value for each target.
    When set to `False`, a single alpha is used for all targets.
    .. versionadded:: 0.24
Attributes
----------
cv_results_ : ndarray of shape (n_samples, n_alphas) or \
        shape (n_samples, n_targets, n_alphas), optional
    Cross-validation values for each alpha (only available if
    ``store_cv_results=True`` and ``cv=None``). After ``fit()`` has been
    called, this attribute will contain the mean squared errors if
    `scoring is None` otherwise it will contain standardized per point
    prediction values.
    .. versionchanged:: 1.5
        `cv_values_` changed to `cv_results_`.
coef_ : ndarray of shape (n_features) or (n_targets, n_features)
    Weight vector(s).
intercept_ : float or ndarray of shape (n_targets,)
    Independent term in decision function. Set to 0.0 if
    ``fit_intercept = False``.
alpha_ : float or ndarray of shape (n_targets,)
    Estimated regularization parameter, or, if ``alpha_per_target=True``,
    the estimated regularization parameter for each target.
best_score_ : float or ndarray of shape (n_targets,)
    Score of base estimator with best alpha, or, if
    ``alpha_per_target=True``, a score for each target.
    .. versionadded:: 0.23
n_features_in_ : int
    Number of features seen during :term:`fit`.
    .. versionadded:: 0.24
feature_names_in_ : ndarray of shape (`n_features_in_`,)
    Names of features seen during :term:`fit`. Defined only when `X`
    has feature names that are all strings.
    .. versionadded:: 1.0
See Also
--------
Ridge : Ridge regression.
RidgeClassifier : Classifier based on ridge regression on {-1, 1} labels.
RidgeClassifierCV : Ridge classifier with built-in cross validation.
Examples
--------
>>> from sklearn.datasets import load_diabetes
>>> from sklearn.linear_model import RidgeCV
>>> X, y = load_diabetes(return_X_y=True)
>>> clf = RidgeCV(alphas=[1e-3, 1e-2, 1e-1, 1]).fit(X, y)
>>> clf.score(X, y)
0.5166...
Definition at line 2515 of file _ridge.py.
Member Function Documentation
fit()
sklearn.linear_model._ridge.RidgeCV.fit (self, X, y, sample_weight = None, ** params)
Fit Ridge regression model with cv.
Parameters
----------
X : ndarray of shape (n_samples, n_features)
    Training data. If using GCV, will be cast to float64
    if necessary.
y : ndarray of shape (n_samples,) or (n_samples, n_targets)
    Target values. Will be cast to X's dtype if necessary.
sample_weight : float or ndarray of shape (n_samples,), default=None
    Individual weights for each sample. If given a float, every sample
    will have the same weight.
**params : dict, default=None
    Parameters to be passed to the underlying scorer.
    .. versionadded:: 1.5
        Only available if `enable_metadata_routing=True`,
        which can be set by using
        ``sklearn.set_config(enable_metadata_routing=True)``.
        See :ref:`Metadata Routing User Guide <metadata_routing>` for
        more details.
Returns
-------
self : object
    Fitted estimator.
Notes
-----
When sample_weight is provided, the selected hyperparameter may depend
on whether we use leave-one-out cross-validation (cv=None)
or another form of cross-validation, because only leave-one-out
cross-validation takes the sample weights into account when computing
the validation score.
Reimplemented from sklearn.linear_model._ridge._BaseRidgeCV.
Definition at line 2655 of file _ridge.py.
References fit().
Referenced by fit(), sklearn.cluster._kmeans._BaseKMeans.fit_predict(), sklearn.neighbors._lof.LocalOutlierFactor.fit_predict(), sklearn.cluster._kmeans._BaseKMeans.fit_transform(), sklearn.manifold._spectral_embedding.SpectralEmbedding.fit_transform(), sklearn.neighbors._graph.KNeighborsTransformer.fit_transform(), sklearn.neighbors._graph.RadiusNeighborsTransformer.fit_transform(), sklearn.preprocessing._label.LabelBinarizer.fit_transform(), sklearn.preprocessing._label.MultiLabelBinarizer.fit_transform(), sklearn.tests.metadata_routing_common.ConsumingTransformer.fit_transform(), and sklearn.utils.tests.test_estimator_checks.SparseTransformer.fit_transform().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/sklearn/linear_model/_ridge.py