Code Cloning Analysis: pip._vendor.requests.adapters.BaseAdapter Class Reference
pip._vendor.requests.adapters.BaseAdapter Class Reference
Public Member Functions
__init__ (self)
send (self, request, stream=False, timeout=None, verify=True, cert=None, proxies=None)
close (self)
Detailed Description
The Base Transport Adapter
Definition at line 70 of file adapters.py.
Constructor & Destructor Documentation
__init__()
pip._vendor.requests.adapters.BaseAdapter.__init__ (self)
Definition at line 73 of file adapters.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
close()
pip._vendor.requests.adapters.BaseAdapter.close (self)
Cleans up adapter specific items.
Reimplemented in pip._vendor.cachecontrol.adapter.CacheControlAdapter, and pip._vendor.requests.adapters.HTTPAdapter.
Definition at line 95 of file adapters.py.
Referenced by pip._vendor.urllib3.util.ssltransport.SSLTransport.__init__(), pip._vendor.urllib3.contrib.securetransport.WrappedSocket._custom_validate(), pip._vendor.urllib3.contrib.securetransport.WrappedSocket._raise_on_error(), scipy.io._fortran.FortranFile.close(), scipy.io._netcdf.netcdf_file.close(), pip._vendor.urllib3.contrib.securetransport.WrappedSocket.handshake(), and pip._vendor.urllib3.response.HTTPResponse.supports_chunked_reads().
send()
pip._vendor.requests.adapters.BaseAdapter.send (self, request, stream = False, timeout = None, verify = True, cert = None, proxies = None)
Sends PreparedRequest object. Returns Response object.
:param request: The :class:`PreparedRequest <PreparedRequest>` being sent.
:param stream: (optional) Whether to stream the request content.
:param timeout: (optional) How long to wait for the server to send
    data before giving up, as a float, or a :ref:`(connect timeout,
    read timeout) <timeouts>` tuple.
:type timeout: float or tuple
:param verify: (optional) Either a boolean, in which case it controls whether we verify
    the server's TLS certificate, or a string, in which case it must be a path
    to a CA bundle to use
:param cert: (optional) Any user-provided SSL certificate to be trusted.
:param proxies: (optional) The proxies dictionary to apply to the request.
Reimplemented in pip._vendor.cachecontrol.adapter.CacheControlAdapter, and pip._vendor.requests.adapters.HTTPAdapter.
Definition at line 76 of file adapters.py.
Referenced by pip._vendor.urllib3.util.ssltransport.SSLTransport.__init__(), pip._vendor.urllib3.contrib.securetransport.WrappedSocket.handshake(), pip._vendor.requests.sessions.Session.request(), pip._vendor.urllib3.connection.HTTPConnection.request_chunked(), and pip._vendor.requests.sessions.SessionRedirectMixin.resolve_redirects().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pip/_vendor/requests/adapters.py