Code Cloning Analysis: sklearn.calibration Namespace Reference
sklearn.calibration Namespace Reference
Classes
class _CalibratedClassifier
class _SigmoidCalibration
class CalibratedClassifierCV
class CalibrationDisplay
Functions
_fit_classifier_calibrator_pair (estimator, X, y, train, test, method, classes, sample_weight=None, fit_params=None)
_fit_calibrator (clf, predictions, y, classes, method, sample_weight=None)
_sigmoid_calibration (predictions, y, sample_weight=None, max_abs_prediction_threshold=30)
calibration_curve (y_true, y_prob, *, pos_label=None, n_bins=5, strategy="uniform")
Detailed Description
Methods for calibrating predicted probabilities.
Function Documentation
_fit_calibrator()
sklearn.calibration._fit_calibrator (clf, predictions, y, classes, method, sample_weight = None) protected
Fit calibrator(s) and return a `_CalibratedClassifier`
instance.
`n_classes` (i.e. `len(clf.classes_)`) calibrators are fitted.
However, if `n_classes` equals 2, one calibrator is fitted.
Parameters
----------
clf : estimator instance
    Fitted classifier.
predictions : array-like, shape (n_samples, n_classes) or (n_samples, 1) \
                when binary.
    Raw predictions returned by the un-calibrated base classifier.
y : array-like, shape (n_samples,)
    The targets.
classes : ndarray, shape (n_classes,)
    All the prediction classes.
method : {'sigmoid', 'isotonic'}
    The method to use for calibration.
sample_weight : ndarray, shape (n_samples,), default=None
    Sample weights. If None, then samples are equally weighted.
Returns
-------
pipeline : _CalibratedClassifier instance
Definition at line 650 of file calibration.py.
Referenced by _fit_classifier_calibrator_pair(), and sklearn.calibration.CalibratedClassifierCV.fit().
_fit_classifier_calibrator_pair()
sklearn.calibration._fit_classifier_calibrator_pair (estimator, X, y, train, test, method, classes, sample_weight = None, fit_params = None) protected
Fit a classifier/calibration pair on a given train/test split.
Fit the classifier on the train set, compute its predictions on the test
set and use the predictions as input to fit the calibrator along with the
test labels.
Parameters
----------
estimator : estimator instance
    Cloned base estimator.
X : array-like, shape (n_samples, n_features)
    Sample data.
y : array-like, shape (n_samples,)
    Targets.
train : ndarray, shape (n_train_indices,)
    Indices of the training subset.
test : ndarray, shape (n_test_indices,)
    Indices of the testing subset.
method : {'sigmoid', 'isotonic'}
    Method to use for calibration.
classes : ndarray, shape (n_classes,)
    The target classes.
sample_weight : array-like, default=None
    Sample weights for `X`.
fit_params : dict, default=None
    Parameters to pass to the `fit` method of the underlying
    classifier.
Returns
-------
calibrated_classifier : _CalibratedClassifier instance
Definition at line 571 of file calibration.py.
References _fit_calibrator().
_sigmoid_calibration()
sklearn.calibration._sigmoid_calibration (predictions, y, sample_weight = None, max_abs_prediction_threshold = 30) protected
Probability Calibration with sigmoid method (Platt 2000)
Parameters
----------
predictions : ndarray of shape (n_samples,)
    The decision function or predict proba for the samples.
y : ndarray of shape (n_samples,)
    The targets.
sample_weight : array-like of shape (n_samples,), default=None
    Sample weights. If None, then samples are equally weighted.
Returns
-------
a : float
    The slope.
b : float
    The intercept.
References
----------
Platt, "Probabilistic Outputs for Support Vector Machines"
Definition at line 788 of file calibration.py.
Referenced by sklearn.calibration._SigmoidCalibration.fit().
calibration_curve()
sklearn.calibration.calibration_curve (y_true, y_prob, * , pos_label = None, n_bins = 5, strategy = "uniform")
Compute true and predicted probabilities for a calibration curve.
The method assumes the inputs come from a binary classifier, and
discretize the [0, 1] interval into bins.
Calibration curves may also be referred to as reliability diagrams.
Read more in the :ref:`User Guide <calibration>`.
Parameters
----------
y_true : array-like of shape (n_samples,)
    True targets.
y_prob : array-like of shape (n_samples,)
    Probabilities of the positive class.
pos_label : int, float, bool or str, default=None
    The label of the positive class.
    .. versionadded:: 1.1
n_bins : int, default=5
    Number of bins to discretize the [0, 1] interval. A bigger number
    requires more data. Bins with no samples (i.e. without
    corresponding values in `y_prob`) will not be returned, thus the
    returned arrays may have less than `n_bins` values.
strategy : {'uniform', 'quantile'}, default='uniform'
    Strategy used to define the widths of the bins.
    uniform
        The bins have identical widths.
    quantile
        The bins have the same number of samples and depend on `y_prob`.
Returns
-------
prob_true : ndarray of shape (n_bins,) or smaller
    The proportion of samples whose class is the positive class, in each
    bin (fraction of positives).
prob_pred : ndarray of shape (n_bins,) or smaller
    The mean predicted probability in each bin.
See Also
--------
CalibrationDisplay.from_predictions : Plot calibration curve using true
    and predicted labels.
CalibrationDisplay.from_estimator : Plot calibration curve using an
    estimator and data.
References
----------
Alexandru Niculescu-Mizil and Rich Caruana (2005) Predicting Good
Probabilities With Supervised Learning, in Proceedings of the 22nd
International Conference on Machine Learning (ICML).
See section 4 (Qualitative Analysis of Predictions).
Examples
--------
>>> import numpy as np
>>> from sklearn.calibration import calibration_curve
>>> y_true = np.array([0, 0, 0, 0, 1, 1, 1, 1, 1])
>>> y_pred = np.array([0.1, 0.2, 0.3, 0.4, 0.65, 0.7, 0.8, 0.9,  1.])
>>> prob_true, prob_pred = calibration_curve(y_true, y_pred, n_bins=3)
>>> prob_true
array([0. , 0.5, 1. ])
>>> prob_pred
array([0.2  , 0.525, 0.85 ])
Definition at line 955 of file calibration.py.
Referenced by sklearn.calibration.CalibrationDisplay.from_predictions().