Code Cloning Analysis: scipy.stats.tests.test_binned_statistic.TestBinnedStatistic Class Reference
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic Class Reference
Public Member Functions
setup_class (cls)
test_1d_count (self)
test_gh5927 (self)
test_big_number_std (self)
test_empty_bins_std (self)
test_non_finite_inputs_and_int_bins (self)
test_1d_result_attributes (self)
test_1d_sum (self)
test_1d_mean (self)
test_1d_std (self)
test_1d_min (self)
test_1d_max (self)
test_1d_median (self)
test_1d_bincode (self)
test_1d_range_keyword (self)
test_1d_multi_values (self)
test_2d_count (self)
test_2d_result_attributes (self)
test_2d_sum (self)
test_2d_mean (self)
test_2d_mean_unicode (self)
test_2d_std (self)
test_2d_min (self)
test_2d_max (self)
test_2d_median (self)
test_2d_bincode (self)
test_2d_multi_values (self)
test_2d_binnumbers_unraveled (self)
test_dd_count (self)
test_dd_result_attributes (self)
test_dd_sum (self)
test_dd_mean (self)
test_dd_std (self)
test_dd_min (self)
test_dd_max (self)
test_dd_median (self)
test_dd_bincode (self)
test_dd_multi_values (self)
test_dd_binnumbers_unraveled (self)
test_dd_binned_statistic_result (self)
test_dd_zero_dedges (self)
test_dd_range_errors (self)
test_binned_statistic_float32 (self)
test_gh14332 (self)
test_dd_all (self, dtype, statistic)
Public Attributes
x = rng.uniform(size=100)
y = rng.uniform(size=100)
v = rng.uniform(size=100)
X = rng.uniform(size=(100, 3))
w = rng.uniform(size=100)
int u = rng.uniform(size=100) + 1e6
Detailed Description
Definition at line 12 of file test_binned_statistic.py.
Member Function Documentation
setup_class()
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.setup_class (cls)
Definition at line 15 of file test_binned_statistic.py.
test_1d_bincode()
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.test_1d_bincode (self)
Definition at line 147 of file test_binned_statistic.py.
test_1d_count()
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.test_1d_count (self)
Definition at line 24 of file test_binned_statistic.py.
test_1d_max()
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.test_1d_max (self)
Definition at line 127 of file test_binned_statistic.py.
test_1d_mean()
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.test_1d_mean (self)
Definition at line 97 of file test_binned_statistic.py.
test_1d_median()
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.test_1d_median (self)
Definition at line 137 of file test_binned_statistic.py.
test_1d_min()
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.test_1d_min (self)
Definition at line 117 of file test_binned_statistic.py.
test_1d_multi_values()
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.test_1d_multi_values (self)
Definition at line 175 of file test_binned_statistic.py.
test_1d_range_keyword()
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.test_1d_range_keyword (self)
Definition at line 160 of file test_binned_statistic.py.
test_1d_result_attributes()
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.test_1d_result_attributes (self)
Definition at line 79 of file test_binned_statistic.py.
test_1d_std()
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.test_1d_std (self)
Definition at line 107 of file test_binned_statistic.py.
test_1d_sum()
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.test_1d_sum (self)
Definition at line 87 of file test_binned_statistic.py.
test_2d_bincode()
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.test_2d_bincode (self)
Definition at line 296 of file test_binned_statistic.py.
test_2d_binnumbers_unraveled()
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.test_2d_binnumbers_unraveled (self)
Definition at line 331 of file test_binned_statistic.py.
test_2d_count()
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.test_2d_count (self)
Definition at line 189 of file test_binned_statistic.py.
test_2d_max()
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.test_2d_max (self)
Definition at line 270 of file test_binned_statistic.py.
test_2d_mean()
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.test_2d_mean (self)
Definition at line 223 of file test_binned_statistic.py.
test_2d_mean_unicode()
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.test_2d_mean_unicode (self)
Definition at line 235 of file test_binned_statistic.py.
test_2d_median()
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.test_2d_median (self)
Definition at line 282 of file test_binned_statistic.py.
test_2d_min()
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.test_2d_min (self)
Definition at line 258 of file test_binned_statistic.py.
test_2d_multi_values()
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.test_2d_multi_values (self)
Definition at line 312 of file test_binned_statistic.py.
test_2d_result_attributes()
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.test_2d_result_attributes (self)
Definition at line 202 of file test_binned_statistic.py.
test_2d_std()
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.test_2d_std (self)
Definition at line 246 of file test_binned_statistic.py.
test_2d_sum()
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.test_2d_sum (self)
Definition at line 211 of file test_binned_statistic.py.
test_big_number_std()
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.test_big_number_std (self)
Definition at line 43 of file test_binned_statistic.py.
test_binned_statistic_float32()
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.test_binned_statistic_float32 (self)
Definition at line 528 of file test_binned_statistic.py.
test_dd_all()
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.test_dd_all (self, dtype, statistic)
Definition at line 553 of file test_binned_statistic.py.
test_dd_bincode()
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.test_dd_bincode (self)
Definition at line 435 of file test_binned_statistic.py.
test_dd_binned_statistic_result()
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.test_dd_binned_statistic_result (self)
Definition at line 480 of file test_binned_statistic.py.
test_dd_binnumbers_unraveled()
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.test_dd_binnumbers_unraveled (self)
Definition at line 465 of file test_binned_statistic.py.
test_dd_count()
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.test_dd_count (self)
Definition at line 354 of file test_binned_statistic.py.
test_dd_max()
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.test_dd_max (self)
Definition at line 415 of file test_binned_statistic.py.
test_dd_mean()
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.test_dd_mean (self)
Definition at line 385 of file test_binned_statistic.py.
test_dd_median()
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.test_dd_median (self)
Definition at line 425 of file test_binned_statistic.py.
test_dd_min()
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.test_dd_min (self)
Definition at line 405 of file test_binned_statistic.py.
test_dd_multi_values()
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.test_dd_multi_values (self)
Definition at line 449 of file test_binned_statistic.py.
test_dd_range_errors()
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.test_dd_range_errors (self)
Definition at line 505 of file test_binned_statistic.py.
test_dd_result_attributes()
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.test_dd_result_attributes (self)
Definition at line 364 of file test_binned_statistic.py.
test_dd_std()
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.test_dd_std (self)
Definition at line 395 of file test_binned_statistic.py.
test_dd_sum()
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.test_dd_sum (self)
Definition at line 372 of file test_binned_statistic.py.
test_dd_zero_dedges()
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.test_dd_zero_dedges (self)
Definition at line 496 of file test_binned_statistic.py.
test_empty_bins_std()
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.test_empty_bins_std (self)
Definition at line 53 of file test_binned_statistic.py.
test_gh14332()
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.test_gh14332 (self)
Definition at line 533 of file test_binned_statistic.py.
test_gh5927()
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.test_gh5927 (self)
Definition at line 34 of file test_binned_statistic.py.
test_non_finite_inputs_and_int_bins()
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.test_non_finite_inputs_and_int_bins (self)
Definition at line 63 of file test_binned_statistic.py.
Member Data Documentation
u
int scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.u = rng.uniform(size=100) + 1e6
Definition at line 22 of file test_binned_statistic.py.
v
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.v = rng.uniform(size=100)
Definition at line 19 of file test_binned_statistic.py.
w
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.w = rng.uniform(size=100)
Definition at line 21 of file test_binned_statistic.py.
X
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.X = rng.uniform(size=(100, 3))
Definition at line 20 of file test_binned_statistic.py.
Referenced by sklearn.linear_model._ridge._X_CenterStackOp._matmat(), sklearn.linear_model._ridge._XT_CenterStackOp._matmat(), sklearn.linear_model._ridge._X_CenterStackOp._matvec(), sklearn.linear_model._ridge._XT_CenterStackOp._matvec(), and sklearn.linear_model._ridge._X_CenterStackOp._transpose().
x
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.x = rng.uniform(size=100)
Definition at line 17 of file test_binned_statistic.py.
Referenced by matplotlib.widgets.ToolHandles.closest().
y
scipy.stats.tests.test_binned_statistic.TestBinnedStatistic.y = rng.uniform(size=100)
Definition at line 18 of file test_binned_statistic.py.
Referenced by matplotlib.widgets.ToolHandles.closest().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/stats/tests/test_binned_statistic.py