Code Cloning Analysis: pandas.core.indexing Namespace Reference
pandas.core.indexing Namespace Reference
Classes
class _AtIndexer
class _iAtIndexer
class _iLocIndexer
class _IndexSlice
class _LocationIndexer
class _LocIndexer
class _ScalarAccessIndexer
class IndexingMixin
Functions
tuple[Hashable|slice,...] _tuplify (int ndim, Hashable loc)
tuple _tupleize_axis_indexer (int ndim, AxisInt axis, key)
np.ndarray check_bool_indexer (Index index, key)
convert_missing_indexer (indexer)
convert_from_missing_indexer_tuple (indexer, axes)
maybe_convert_ix (*args)
bool is_nested_tuple (tup, labels)
bool is_label_like (key)
bool need_slice (slice obj)
None check_dict_or_set_indexers (key)
Variables
T = TypeVar("T")
_NS = slice(None, None)
str _one_ellipsis_message = "indexer may only contain one '...' entry"
IndexSlice = _IndexSlice()
Function Documentation
_tupleize_axis_indexer()
tuple pandas.core.indexing._tupleize_axis_indexer (int ndim, AxisInt axis, key) protected
If we have an axis, adapt the given key to be axis-independent.
Definition at line 2623 of file indexing.py.
Referenced by pandas.core.indexing._iLocIndexer._get_setitem_indexer(), and pandas.core.indexing._LocationIndexer._get_setitem_indexer().
_tuplify()
tuple[Hashable | slice, ...] pandas.core.indexing._tuplify (int ndim, Hashable loc) protected
Given an indexer for the first dimension, create an equivalent tuple
for indexing over all dimensions.
Parameters
----------
ndim : int
loc : object
Returns
-------
tuple
Definition at line 2603 of file indexing.py.
Referenced by pandas.core.indexing._iLocIndexer._has_valid_setitem_indexer(), and pandas.core.indexing._iLocIndexer._setitem_with_indexer_split_path().
check_bool_indexer()
np.ndarray pandas.core.indexing.check_bool_indexer (Index index, key)
Check if key is a valid boolean indexer for an object with such index and
perform reindexing or conversion if needed.
This function assumes that is_bool_indexer(key) == True.
Parameters
----------
index : Index
    Index of the object on which the indexing is done.
key : list-like
    Boolean indexer to check.
Returns
-------
np.array
    Resulting key.
Raises
------
IndexError
    If the key does not have the same length as index.
IndexingError
    If the index of the key is unalignable to index.
Definition at line 2632 of file indexing.py.
Referenced by pandas.core.indexing._LocIndexer._convert_to_indexer(), and pandas.core.indexing._LocationIndexer._getitem_tuple_same_dim().
check_dict_or_set_indexers()
None pandas.core.indexing.check_dict_or_set_indexers (key)
Check if the indexer is or contains a dict or set, which is no longer allowed.
Definition at line 2765 of file indexing.py.
Referenced by pandas.core.indexing._LocationIndexer._ensure_listlike_indexer(), pandas.core.indexing._LocationIndexer._get_setitem_indexer(), and pandas.core.indexing._LocationIndexer._getitem_tuple_same_dim().
convert_from_missing_indexer_tuple()
pandas.core.indexing.convert_from_missing_indexer_tuple (indexer, axes)
Create a filtered indexer that doesn't have any missing indexers.
Definition at line 2700 of file indexing.py.
Referenced by pandas.core.indexing._iLocIndexer._setitem_with_indexer().
convert_missing_indexer()
pandas.core.indexing.convert_missing_indexer (indexer)
Reverse convert a missing indexer, which is a dict
return the scalar indexer and a boolean indicating if we converted
Definition at line 2684 of file indexing.py.
Referenced by pandas.core.indexing._iLocIndexer._setitem_with_indexer().
is_label_like()
bool pandas.core.indexing.is_label_like (key)
Returns
-------
bool
Definition at line 2738 of file indexing.py.
Referenced by pandas.core.indexing._LocationIndexer._getitem_tuple_same_dim().
is_nested_tuple()
bool pandas.core.indexing.is_nested_tuple (tup, labels)
Returns
-------
bool
Definition at line 2721 of file indexing.py.
Referenced by pandas.core.indexing._LocIndexer._convert_to_indexer(), pandas.core.indexing._LocIndexer._getitem_iterable(), and pandas.core.indexing._LocationIndexer._is_nested_tuple_indexer().
maybe_convert_ix()
pandas.core.indexing.maybe_convert_ix (* args)
We likely want to take the cross-product.
Definition at line 2711 of file indexing.py.
Referenced by pandas.core.indexing._iLocIndexer._setitem_single_block().
need_slice()
bool pandas.core.indexing.need_slice (slice obj)
Returns
-------
bool
Definition at line 2752 of file indexing.py.
Referenced by pandas.core.indexing._iLocIndexer._get_list_axis(), and pandas.core.indexing._LocIndexer._get_slice_axis().
Variable Documentation
_NS
pandas.core.indexing._NS = slice(None, None) protected
Definition at line 104 of file indexing.py.
_one_ellipsis_message
str pandas.core.indexing._one_ellipsis_message = "indexer may only contain one '...' entry" protected
Definition at line 105 of file indexing.py.
IndexSlice
pandas.core.indexing.IndexSlice = _IndexSlice()
Definition at line 153 of file indexing.py.
T
pandas.core.indexing.T = TypeVar("T")
Definition at line 102 of file indexing.py.