Code Cloning Analysis: fontTools.cu2qu.errors.IncompatibleSegmentTypesError Class Reference
fontTools.cu2qu.errors.IncompatibleSegmentTypesError Class Reference
Public Member Functions
__init__ (self, glyphs, segments)
__str__ (self)
Public Member Functions inherited from fontTools.cu2qu.errors.IncompatibleGlyphsError
__init__ (self, glyphs)
__repr__ (self)
Public Attributes
segments = segments
Public Attributes inherited from fontTools.cu2qu.errors.IncompatibleGlyphsError
glyphs = glyphs
str combined_name = "{%s}" % ", ".join(sorted(names))
Detailed Description
Definition at line 52 of file errors.py.
Constructor & Destructor Documentation
__init__()
fontTools.cu2qu.errors.IncompatibleSegmentTypesError.__init__ (self, glyphs, segments)
Definition at line 53 of file errors.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__str__()
fontTools.cu2qu.errors.IncompatibleSegmentTypesError.__str__ (self)
Definition at line 57 of file errors.py.
Referenced by numpy.polynomial._polybase.ABCPolyBase._get_coefficients().
Member Data Documentation
segments
fontTools.cu2qu.errors.IncompatibleSegmentTypesError.segments = segments
Definition at line 55 of file errors.py.
Referenced by fontTools.ttLib.tables._a_v_a_r.table__a_v_a_r.compile(), and fontTools.ttLib.tables._a_v_a_r.table__a_v_a_r.decompile().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/cu2qu/errors.py