Code Cloning Analysis: scipy.linalg.tests.test_lapack.TestTbtrs Class Reference
scipy.linalg.tests.test_lapack.TestTbtrs Class Reference
Public Member Functions
test_nag_example_f07vef_f07vsf (self, dtype)
test_random_matrices (self, dtype, trans, uplo, diag)
test_invalid_argument_raises_exception (self, uplo, trans, diag)
test_zero_element_in_diagonal (self)
test_invalid_matrix_shapes (self, ldab, n, ldb, nrhs)
Detailed Description
Definition at line 508 of file test_lapack.py.
Member Function Documentation
test_invalid_argument_raises_exception()
scipy.linalg.tests.test_lapack.TestTbtrs.test_invalid_argument_raises_exception (self, uplo, trans, diag)
Test if invalid values of uplo, trans and diag raise exceptions
Definition at line 611 of file test_lapack.py.
References scipy.linalg.lapack.get_lapack_funcs().
test_invalid_matrix_shapes()
scipy.linalg.tests.test_lapack.TestTbtrs.test_invalid_matrix_shapes (self, ldab, n, ldb, nrhs)
Test ?tbtrs fails correctly if shapes are invalid.
Definition at line 640 of file test_lapack.py.
References scipy.linalg.lapack._compute_lwork(), scipy.linalg.blas.get_blas_funcs(), and scipy.linalg.lapack.get_lapack_funcs().
test_nag_example_f07vef_f07vsf()
scipy.linalg.tests.test_lapack.TestTbtrs.test_nag_example_f07vef_f07vsf (self, dtype)
Test real (f07vef) and complex (f07vsf) examples from NAG
Examples available from:
* https://www.nag.com/numeric/fl/nagdoc_latest/html/f07/f07vef.html
* https://www.nag.com/numeric/fl/nagdoc_latest/html/f07/f07vsf.html
Definition at line 511 of file test_lapack.py.
References scipy.linalg.lapack.get_lapack_funcs().
test_random_matrices()
scipy.linalg.tests.test_lapack.TestTbtrs.test_random_matrices (self, dtype, trans, uplo, diag)
Definition at line 562 of file test_lapack.py.
test_zero_element_in_diagonal()
scipy.linalg.tests.test_lapack.TestTbtrs.test_zero_element_in_diagonal (self)
Test if a matrix with a zero diagonal element is singular
If the i-th diagonal of A is zero, ?tbtrs should return `i` in `info`
indicating the provided matrix is singular.
Note that ?tbtrs requires the matrix A to be stored in banded form.
In this form the diagonal corresponds to the last row.
Definition at line 620 of file test_lapack.py.
References scipy.linalg.lapack.get_lapack_funcs().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/linalg/tests/test_lapack.py