Code Cloning Analysis: sklearn.feature_selection._univariate_selection.GenericUnivariateSelect Class Reference
sklearn.feature_selection._univariate_selection.GenericUnivariateSelect Class Reference
Public Member Functions
__init__ (self, score_func=f_classif, *, mode="percentile", param=1e-5)
__sklearn_tags__ (self)
Public Member Functions inherited from sklearn.feature_selection._univariate_selection._BaseFilter
__init__ (self, score_func)
fit (self, X, y=None)
__sklearn_tags__ (self)
Public Member Functions inherited from sklearn.feature_selection._base.SelectorMixin
get_support (self, indices=False)
transform (self, X)
inverse_transform (self, X)
get_feature_names_out (self, input_features=None)
Public Member Functions inherited from sklearn.base.TransformerMixin
__sklearn_tags__ (self)
fit_transform (self, X, y=None, **fit_params)
Public Member Functions inherited from sklearn.utils._set_output._SetOutputMixin
__init_subclass__ (cls, auto_wrap_output_keys=("transform",), **kwargs)
set_output (self, *, transform=None)
Public Member Functions inherited from sklearn.base.BaseEstimator
get_params (self, deep=True)
set_params (self, **params)
__sklearn_clone__ (self)
__repr__ (self, N_CHAR_MAX=700)
__getstate__ (self)
__setstate__ (self, state)
__sklearn_tags__ (self)
Public Member Functions inherited from sklearn.utils._metadata_requests._MetadataRequester
set_fit_request (self, **kwargs)
set_partial_fit_request (self, **kwargs)
set_predict_request (self, **kwargs)
set_predict_proba_request (self, **kwargs)
set_predict_log_proba_request (self, **kwargs)
set_decision_function_request (self, **kwargs)
set_score_request (self, **kwargs)
set_split_request (self, **kwargs)
set_transform_request (self, **kwargs)
set_inverse_transform_request (self, **kwargs)
__init_subclass__ (cls, **kwargs)
get_metadata_routing (self)
Public Attributes
mode = mode
param = param
Public Attributes inherited from sklearn.feature_selection._univariate_selection._BaseFilter
score_func = score_func
scores_
pvalues_ = score_func_ret
Protected Member Functions
_make_selector (self)
_check_params (self, X, y)
_get_support_mask (self)
Protected Member Functions inherited from sklearn.feature_selection._base.SelectorMixin
_transform (self, X)
Protected Member Functions inherited from sklearn.base.BaseEstimator
_get_param_names (cls)
_get_params_html (self, deep=True)
_validate_params (self)
Protected Member Functions inherited from sklearn.utils._repr_html.base.ReprHTMLMixin
_repr_html_ (self)
_repr_html_inner (self)
_repr_mimebundle_ (self, **kwargs)
Protected Member Functions inherited from sklearn.utils._repr_html.base._HTMLDocumentationLinkMixin
_doc_link_template (self)
_doc_link_template (self, value)
_get_doc_link (self)
Protected Member Functions inherited from sklearn.utils._metadata_requests._MetadataRequester
_build_request_for_signature (cls, router, method)
_get_default_requests (cls)
_get_metadata_request (self)
Static Protected Attributes
dict _selection_modes
Static Protected Attributes inherited from sklearn.base.BaseEstimator
_html_repr = estimator_html_repr
Static Protected Attributes inherited from sklearn.utils._repr_html.base._HTMLDocumentationLinkMixin
str _doc_link_module = "sklearn"
_doc_link_url_param_generator = None
Additional Inherited Members
Protected Attributes inherited from sklearn.utils._set_output._SetOutputMixin
_sklearn_auto_wrap_output_keys = set()
dict _sklearn_output_config = {}
Protected Attributes inherited from sklearn.base.BaseEstimator
_parameter_constraints
Detailed Description
Univariate feature selector with configurable strategy.
Read more in the :ref:`User Guide <univariate_feature_selection>`.
Parameters
----------
score_func : callable, default=f_classif
    Function taking two arrays X and y, and returning a pair of arrays
    (scores, pvalues). For modes 'percentile' or 'kbest' it can return
    a single array scores.
mode : {'percentile', 'k_best', 'fpr', 'fdr', 'fwe'}, default='percentile'
    Feature selection mode. Note that the `'percentile'` and `'kbest'`
    modes are supporting unsupervised feature selection (when `y` is `None`).
param : "all", float or int, default=1e-5
    Parameter of the corresponding mode.
Attributes
----------
scores_ : array-like of shape (n_features,)
    Scores of features.
pvalues_ : array-like of shape (n_features,)
    p-values of feature scores, None if `score_func` returned scores only.
n_features_in_ : int
    Number of features seen during :term:`fit`.
    .. versionadded:: 0.24
feature_names_in_ : ndarray of shape (`n_features_in_`,)
    Names of features seen during :term:`fit`. Defined only when `X`
    has feature names that are all strings.
    .. versionadded:: 1.0
See Also
--------
f_classif : ANOVA F-value between label/feature for classification tasks.
mutual_info_classif : Mutual information for a discrete target.
chi2 : Chi-squared stats of non-negative features for classification tasks.
f_regression : F-value between label/feature for regression tasks.
mutual_info_regression : Mutual information for a continuous target.
SelectPercentile : Select features based on percentile of the highest
    scores.
SelectKBest : Select features based on the k highest scores.
SelectFpr : Select features based on a false positive rate test.
SelectFdr : Select features based on an estimated false discovery rate.
SelectFwe : Select features based on family-wise error rate.
Examples
--------
>>> from sklearn.datasets import load_breast_cancer
>>> from sklearn.feature_selection import GenericUnivariateSelect, chi2
>>> X, y = load_breast_cancer(return_X_y=True)
>>> X.shape
(569, 30)
>>> transformer = GenericUnivariateSelect(chi2, mode='k_best', param=20)
>>> X_new = transformer.fit_transform(X, y)
>>> X_new.shape
(569, 20)
Definition at line 1062 of file _univariate_selection.py.
Constructor & Destructor Documentation
__init__()
sklearn.feature_selection._univariate_selection.GenericUnivariateSelect.__init__ (self, score_func = f_classif, * , mode = "percentile", param = 1e-5)
Definition at line 1141 of file _univariate_selection.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params().
Member Function Documentation
__sklearn_tags__()
sklearn.feature_selection._univariate_selection.GenericUnivariateSelect.__sklearn_tags__ (self)
Definition at line 1157 of file _univariate_selection.py.
_check_params()
sklearn.feature_selection._univariate_selection.GenericUnivariateSelect._check_params (self, X, y) protected
Reimplemented from sklearn.feature_selection._univariate_selection._BaseFilter.
Definition at line 1162 of file _univariate_selection.py.
_get_support_mask()
sklearn.feature_selection._univariate_selection.GenericUnivariateSelect._get_support_mask (self) protected
Get the boolean mask indicating which features are selected
Returns
-------
support : boolean array of shape [# input features]
    An element is True iff its corresponding feature is selected for
    retention.
Reimplemented from sklearn.feature_selection._base.SelectorMixin.
Definition at line 1165 of file _univariate_selection.py.
References _make_selector(), sklearn.feature_selection._univariate_selection._BaseFilter.pvalues_, and sklearn.feature_selection._univariate_selection._BaseFilter.scores_.
_make_selector()
sklearn.feature_selection._univariate_selection.GenericUnivariateSelect._make_selector (self) protected
Definition at line 1146 of file _univariate_selection.py.
Referenced by _get_support_mask().
Member Data Documentation
_selection_modes
dict sklearn.feature_selection._univariate_selection.GenericUnivariateSelect._selection_modes static protected
Initial value:
=  {
        "percentile": SelectPercentile,
        "k_best": SelectKBest,
        "fpr": SelectFpr,
        "fdr": SelectFdr,
        "fwe": SelectFwe,
    }
Definition at line 1127 of file _univariate_selection.py.
mode
sklearn.feature_selection._univariate_selection.GenericUnivariateSelect.mode = mode
Definition at line 1143 of file _univariate_selection.py.
Referenced by sklearn.neighbors._graph.KNeighborsTransformer.transform(), and sklearn.neighbors._graph.RadiusNeighborsTransformer.transform().
param
sklearn.feature_selection._univariate_selection.GenericUnivariateSelect.param = param
Definition at line 1144 of file _univariate_selection.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/sklearn/feature_selection/_univariate_selection.py