Code Cloning Analysis: scipy._lib._gcutils Namespace Reference
scipy._lib._gcutils Namespace Reference
Classes
class ReferenceError
Functions
set_gc_state (state)
gc_state (state)
assert_deallocated (func, *args, **kwargs)
Variables
list __all__ = ['set_gc_state', 'gc_state', 'assert_deallocated']
str IS_PYPY = 'PyPy'
Detailed Description
Module for testing automatic garbage collection of objects
.. autosummary::
   :toctree: generated/
   set_gc_state - enable or disable garbage collection
   gc_state - context manager for given state of garbage collector
   assert_deallocated - context manager to check for circular references on object
Function Documentation
assert_deallocated()
scipy._lib._gcutils.assert_deallocated (func, * args, ** kwargs)
Context manager to check that object is deallocated
This is useful for checking that an object can be freed directly by
reference counting, without requiring gc to break reference cycles.
GC is disabled inside the context manager.
This check is not available on PyPy.
Parameters
----------
func : callable
    Callable to create object to check
\\*args : sequence
    positional arguments to `func` in order to create object to check
\\*\\*kwargs : dict
    keyword arguments to `func` in order to create object to check
Examples
--------
>>> class C: pass
>>> with assert_deallocated(C) as c:
...     # do something
...     del c
>>> class C:
...     def __init__(self):
...         self._circular = self # Make circular reference
>>> with assert_deallocated(C) as c: #doctest: +IGNORE_EXCEPTION_DETAIL
...     # do something
...     del c
Traceback (most recent call last):
    ...
ReferenceError: Remaining reference(s) to object
Definition at line 61 of file _gcutils.py.
References gc_state().
gc_state()
scipy._lib._gcutils.gc_state (state)
 Context manager to set state of garbage collector to `state`
Parameters
----------
state : bool
    True for gc enabled, False for disabled
Examples
--------
>>> with gc_state(False):
...     assert not gc.isenabled()
>>> with gc_state(True):
...     assert gc.isenabled()
Definition at line 39 of file _gcutils.py.
References set_gc_state().
Referenced by assert_deallocated().
set_gc_state()
scipy._lib._gcutils.set_gc_state (state)
 Set status of garbage collector
Definition at line 28 of file _gcutils.py.
Referenced by gc_state().
Variable Documentation
__all__
list scipy._lib._gcutils.__all__ = ['set_gc_state', 'gc_state', 'assert_deallocated'] private
Definition at line 18 of file _gcutils.py.
IS_PYPY
str scipy._lib._gcutils.IS_PYPY = 'PyPy'
Definition at line 21 of file _gcutils.py.