Code Cloning Analysis: matplotlib.testing.widgets Namespace Reference
matplotlib.testing.widgets Namespace Reference
Functions
get_ax ()
noop (*args, **kwargs)
mock_event (ax, button=1, xdata=0, ydata=0, key=None, step=1)
do_event (tool, etype, button=1, xdata=0, ydata=0, key=None, step=1)
click_and_drag (tool, start, end, key=None)
Detailed Description
========================
Widget testing utilities
========================
See also :mod:`matplotlib.tests.test_widgets`.
Function Documentation
click_and_drag()
matplotlib.testing.widgets.click_and_drag (tool, start, end, key = None)
Helper to simulate a mouse drag operation.
Parameters
----------
tool : `~matplotlib.widgets.Widget`
start : [float, float]
    Starting point in data coordinates.
end : [float, float]
    End point in data coordinates.
key : None or str
     An optional key that is pressed during the whole operation
     (see also `.KeyEvent`).
Definition at line 93 of file widgets.py.
References do_event().
do_event()
matplotlib.testing.widgets.do_event (tool, etype, button = 1, xdata = 0, ydata = 0, key = None, step = 1)
Trigger an event on the given tool.
Parameters
----------
tool : matplotlib.widgets.AxesWidget
etype : str
    The event to trigger.
xdata : float
    x coord of mouse in data coords.
ydata : float
    y coord of mouse in data coords.
button : None or `MouseButton` or {'up', 'down'}
    The mouse button pressed in this event (see also `.MouseEvent`).
key : None or str
    The key pressed when the mouse event triggered (see also `.KeyEvent`).
step : int
    Number of scroll steps (positive for 'up', negative for 'down').
Definition at line 68 of file widgets.py.
References mock_event().
Referenced by click_and_drag().
get_ax()
matplotlib.testing.widgets.get_ax ()
Create a plot and return its Axes.
Definition at line 14 of file widgets.py.
mock_event()
matplotlib.testing.widgets.mock_event (ax, button = 1, xdata = 0, ydata = 0, key = None, step = 1)
Create a mock event that can stand in for `.Event` and its subclasses.
This event is intended to be used in tests where it can be passed into
event handling functions.
Parameters
----------
ax : `~matplotlib.axes.Axes`
    The Axes the event will be in.
xdata : float
    x coord of mouse in data coords.
ydata : float
    y coord of mouse in data coords.
button : None or `MouseButton` or {'up', 'down'}
    The mouse button pressed in this event (see also `.MouseEvent`).
key : None or str
    The key pressed when the mouse event triggered (see also `.KeyEvent`).
step : int
    Number of scroll steps (positive for 'up', negative for 'down').
Returns
-------
event
    A `.Event`\-like Mock instance.
Definition at line 27 of file widgets.py.
Referenced by do_event().
noop()
matplotlib.testing.widgets.noop (* args, ** kwargs)
Definition at line 23 of file widgets.py.