Code Cloning Analysis: sklearn.tests.metadata_routing_common.NonConsumingClassifier Class Reference
sklearn.tests.metadata_routing_common.NonConsumingClassifier Class Reference
Public Member Functions
__init__ (self, alpha=0.0)
fit (self, X, y)
partial_fit (self, X, y, classes=None)
decision_function (self, X)
predict (self, X)
predict_proba (self, X)
predict_log_proba (self, X)
Public Member Functions inherited from sklearn.base.ClassifierMixin
__sklearn_tags__ (self)
score (self, X, y, sample_weight=None)
Public Member Functions inherited from sklearn.base.BaseEstimator
get_params (self, deep=True)
set_params (self, **params)
__sklearn_clone__ (self)
__repr__ (self, N_CHAR_MAX=700)
__getstate__ (self)
__setstate__ (self, state)
__sklearn_tags__ (self)
Public Member Functions inherited from sklearn.utils._metadata_requests._MetadataRequester
set_fit_request (self, **kwargs)
set_partial_fit_request (self, **kwargs)
set_predict_request (self, **kwargs)
set_predict_proba_request (self, **kwargs)
set_predict_log_proba_request (self, **kwargs)
set_decision_function_request (self, **kwargs)
set_score_request (self, **kwargs)
set_split_request (self, **kwargs)
set_transform_request (self, **kwargs)
set_inverse_transform_request (self, **kwargs)
__init_subclass__ (cls, **kwargs)
get_metadata_routing (self)
Public Attributes
alpha = alpha
classes_ = np.unique(y)
coef_ = np.ones_like(X)
Additional Inherited Members
Protected Member Functions inherited from sklearn.base.BaseEstimator
_get_param_names (cls)
_get_params_html (self, deep=True)
_validate_params (self)
Protected Member Functions inherited from sklearn.utils._repr_html.base.ReprHTMLMixin
_repr_html_ (self)
_repr_html_inner (self)
_repr_mimebundle_ (self, **kwargs)
Protected Member Functions inherited from sklearn.utils._repr_html.base._HTMLDocumentationLinkMixin
_doc_link_template (self)
_doc_link_template (self, value)
_get_doc_link (self)
Protected Member Functions inherited from sklearn.utils._metadata_requests._MetadataRequester
_build_request_for_signature (cls, router, method)
_get_default_requests (cls)
_get_metadata_request (self)
Protected Attributes inherited from sklearn.base.BaseEstimator
_parameter_constraints
Static Protected Attributes inherited from sklearn.base.ClassifierMixin
str _estimator_type = "classifier"
Static Protected Attributes inherited from sklearn.base.BaseEstimator
_html_repr = estimator_html_repr
Static Protected Attributes inherited from sklearn.utils._repr_html.base._HTMLDocumentationLinkMixin
str _doc_link_module = "sklearn"
_doc_link_url_param_generator = None
Detailed Description
A classifier which accepts no metadata on any method.
Definition at line 196 of file metadata_routing_common.py.
Constructor & Destructor Documentation
__init__()
sklearn.tests.metadata_routing_common.NonConsumingClassifier.__init__ (self, alpha = 0.0)
Definition at line 199 of file metadata_routing_common.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params().
Member Function Documentation
decision_function()
sklearn.tests.metadata_routing_common.NonConsumingClassifier.decision_function (self, X)
Definition at line 210 of file metadata_routing_common.py.
fit()
sklearn.tests.metadata_routing_common.NonConsumingClassifier.fit (self, X, y)
Definition at line 202 of file metadata_routing_common.py.
Referenced by sklearn.cluster._kmeans._BaseKMeans.fit_predict(), sklearn.cluster._kmeans._BaseKMeans.fit_transform(), sklearn.tests.metadata_routing_common.ConsumingTransformer.fit_transform(), and sklearn.utils.tests.test_estimator_checks.SparseTransformer.fit_transform().
partial_fit()
sklearn.tests.metadata_routing_common.NonConsumingClassifier.partial_fit (self, X, y, classes = None)
Definition at line 207 of file metadata_routing_common.py.
predict()
sklearn.tests.metadata_routing_common.NonConsumingClassifier.predict (self, X)
Definition at line 213 of file metadata_routing_common.py.
predict_log_proba()
sklearn.tests.metadata_routing_common.NonConsumingClassifier.predict_log_proba (self, X)
Definition at line 226 of file metadata_routing_common.py.
predict_proba()
sklearn.tests.metadata_routing_common.NonConsumingClassifier.predict_proba (self, X)
Definition at line 219 of file metadata_routing_common.py.
Referenced by sklearn.tree._classes.DecisionTreeClassifier.predict_log_proba().
Member Data Documentation
alpha
sklearn.tests.metadata_routing_common.NonConsumingClassifier.alpha = alpha
Definition at line 200 of file metadata_routing_common.py.
Referenced by sklearn.decomposition._dict_learning._BaseSparseCoding._transform().
classes_
sklearn.tests.metadata_routing_common.NonConsumingClassifier.classes_ = np.unique(y)
Definition at line 203 of file metadata_routing_common.py.
Referenced by sklearn.ensemble._hist_gradient_boosting.gradient_boosting.BaseHistGradientBoosting._check_early_stopping_scorer(), sklearn.tree._classes.BaseDecisionTree._compute_missing_values_in_feature_mask(), sklearn.utils._mocking.CheckingClassifier.decision_function(), sklearn.utils._mocking.CheckingClassifier.fit(), sklearn.naive_bayes._BaseNB.predict(), sklearn.tree._classes.BaseDecisionTree.predict(), sklearn.utils._mocking.CheckingClassifier.predict(), and sklearn.utils._mocking.CheckingClassifier.predict_proba().
coef_
sklearn.tests.metadata_routing_common.NonConsumingClassifier.coef_ = np.ones_like(X)
Definition at line 204 of file metadata_routing_common.py.
Referenced by sklearn.linear_model._base.LinearModel._set_intercept(), and sklearn.linear_model._base.LinearClassifierMixin.decision_function().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/sklearn/tests/metadata_routing_common.py