Code Cloning Analysis: pandas.core.indexes.accessors.CombinedDatetimelikeProperties Class Reference
pandas.core.indexes.accessors.CombinedDatetimelikeProperties Class Reference
Public Member Functions
__new__ (cls, Series data)
Public Member Functions inherited from pandas.core.indexes.accessors.DatetimeProperties
np.ndarray to_pydatetime (self)
freq (self)
DataFrame isocalendar (self)
Public Member Functions inherited from pandas.core.indexes.accessors.Properties
None __init__ (self, Series data, orig)
Public Member Functions inherited from pandas.core.base.PandasObject
str __repr__ (self)
int __sizeof__ (self)
Public Member Functions inherited from pandas.core.accessor.DirNamesMixin
list[str] __dir__ (self)
Public Member Functions inherited from pandas.core.base.NoNewAttributesMixin
None __setattr__ (self, str key, value)
Public Member Functions inherited from pandas.core.indexes.accessors.TimedeltaProperties
np.ndarray to_pytimedelta (self)
components (self)
freq (self)
Additional Inherited Members
Public Attributes inherited from pandas.core.indexes.accessors.Properties
orig = orig
name = getattr(data, "name", None)
Static Public Attributes inherited from pandas.core.indexes.accessors.Properties
delegate = ArrowExtensionArray,
accessors = TimedeltaArray._datetimelike_ops,
str typ = "property",
f accessor_mapping = lambda x"_dt_{x}",
bool raise_on_missing = False,
Protected Member Functions inherited from pandas.core.indexes.accessors.Properties
_get_values (self)
_delegate_property_get (self, str name)
_delegate_property_set (self, str name, value, *args, **kwargs)
_delegate_method (self, str name, *args, **kwargs)
Protected Member Functions inherited from pandas.core.accessor.PandasDelegate
None _add_delegate_accessors (cls, delegate, list[str] accessors, str typ, bool overwrite=False, Callable[[str], str] accessor_mapping=lambda x:x, bool raise_on_missing=True)
Protected Member Functions inherited from pandas.core.base.PandasObject
_constructor (self)
None _reset_cache (self, str|None key=None)
Protected Member Functions inherited from pandas.core.accessor.DirNamesMixin
set[str] _dir_deletions (self)
set[str] _dir_additions (self)
Protected Member Functions inherited from pandas.core.base.NoNewAttributesMixin
None _freeze (self)
Protected Attributes inherited from pandas.core.indexes.accessors.Properties
_parent = data
Static Protected Attributes inherited from pandas.core.base.PandasObject
dict _cache [str, Any]
Static Protected Attributes inherited from pandas.core.accessor.DirNamesMixin
set _accessors = set()
frozenset _hidden_attrs = frozenset()
Detailed Description
Definition at line 608 of file accessors.py.
Member Function Documentation
__new__()
pandas.core.indexes.accessors.CombinedDatetimelikeProperties.__new__ (cls, Series data)
Definition at line 611 of file accessors.py.
Referenced by matplotlib.path.Path._fast_from_codes_and_verts(), pandas.core.generic.NDFrame._from_mgr(), pandas.core.arrays.string_.StringArray._from_sequence(), scipy.interpolate._fitpack2._BivariateSplineBase._from_tck(), scipy.interpolate._fitpack2.UnivariateSpline._from_tck(), matplotlib.colors.Colormap._get_rgba_and_mask(), pip._vendor.rich.style.Style.clear_meta_and_links(), matplotlib.colors.MultivarColormap.copy(), pip._vendor.rich.style.Style.copy(), pip._vendor.rich.style.Style.from_color(), pip._vendor.rich.json.JSON.from_data(), pip._vendor.rich.style.Style.from_meta(), matplotlib.colors.BivarColormap.lut(), pip._vendor.rich.style.Style.test(), pip._vendor.rich.style.Style.update_link(), and pip._vendor.rich.style.Style.without_color().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/core/indexes/accessors.py