Code Cloning Analysis: sklearn.neighbors._graph Namespace Reference
sklearn.neighbors._graph Namespace Reference
Classes
class KNeighborsTransformer
class RadiusNeighborsTransformer
Functions
_check_params (X, metric, p, metric_params)
_query_include_self (X, include_self, mode)
kneighbors_graph (X, n_neighbors, *, mode="connectivity", metric="minkowski", p=2, metric_params=None, include_self=False, n_jobs=None)
radius_neighbors_graph (X, radius, *, mode="connectivity", metric="minkowski", p=2, metric_params=None, include_self=False, n_jobs=None)
Detailed Description
Nearest Neighbors graph functions
Function Documentation
_check_params()
sklearn.neighbors._graph._check_params (X, metric, p, metric_params) protected
Check the validity of the input parameters
Definition at line 21 of file _graph.py.
Referenced by kneighbors_graph(), and radius_neighbors_graph().
_query_include_self()
sklearn.neighbors._graph._query_include_self (X, include_self, mode) protected
Return the query based on include_self param
Definition at line 33 of file _graph.py.
Referenced by kneighbors_graph(), and radius_neighbors_graph().
kneighbors_graph()
sklearn.neighbors._graph.kneighbors_graph (X, n_neighbors, * , mode = "connectivity", metric = "minkowski", p = 2, metric_params = None, include_self = False, n_jobs = None)
Compute the (weighted) graph of k-Neighbors for points in X.
Read more in the :ref:`User Guide <unsupervised_neighbors>`.
Parameters
----------
X : {array-like, sparse matrix} of shape (n_samples, n_features)
    Sample data.
n_neighbors : int
    Number of neighbors for each sample.
mode : {'connectivity', 'distance'}, default='connectivity'
    Type of returned matrix: 'connectivity' will return the connectivity
    matrix with ones and zeros, and 'distance' will return the distances
    between neighbors according to the given metric.
metric : str, default='minkowski'
    Metric to use for distance computation. Default is "minkowski", which
    results in the standard Euclidean distance when p = 2. See the
    documentation of `scipy.spatial.distance
    <https://docs.scipy.org/doc/scipy/reference/spatial.distance.html>`_ and
    the metrics listed in
    :class:`~sklearn.metrics.pairwise.distance_metrics` for valid metric
    values.
p : float, default=2
    Power parameter for the Minkowski metric. When p = 1, this is equivalent
    to using manhattan_distance (l1), and euclidean_distance (l2) for p = 2.
    For arbitrary p, minkowski_distance (l_p) is used. This parameter is expected
    to be positive.
metric_params : dict, default=None
    Additional keyword arguments for the metric function.
include_self : bool or 'auto', default=False
    Whether or not to mark each sample as the first nearest neighbor to
    itself. If 'auto', then True is used for mode='connectivity' and False
    for mode='distance'.
n_jobs : int, default=None
    The number of parallel jobs to run for neighbors search.
    ``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.
    ``-1`` means using all processors. See :term:`Glossary <n_jobs>`
    for more details.
Returns
-------
A : sparse matrix of shape (n_samples, n_samples)
    Graph where A[i, j] is assigned the weight of edge that
    connects i to j. The matrix is of CSR format.
See Also
--------
radius_neighbors_graph: Compute the (weighted) graph of Neighbors for points in X.
Examples
--------
>>> X = [[0], [3], [1]]
>>> from sklearn.neighbors import kneighbors_graph
>>> A = kneighbors_graph(X, 2, mode='connectivity', include_self=True)
>>> A.toarray()
array([[1., 0., 1.],
       [0., 1., 1.],
       [1., 0., 1.]])
Definition at line 58 of file _graph.py.
References _check_params(), and _query_include_self().
radius_neighbors_graph()
sklearn.neighbors._graph.radius_neighbors_graph (X, radius, * , mode = "connectivity", metric = "minkowski", p = 2, metric_params = None, include_self = False, n_jobs = None)
Compute the (weighted) graph of Neighbors for points in X.
Neighborhoods are restricted the points at a distance lower than
radius.
Read more in the :ref:`User Guide <unsupervised_neighbors>`.
Parameters
----------
X : {array-like, sparse matrix} of shape (n_samples, n_features)
    Sample data.
radius : float
    Radius of neighborhoods.
mode : {'connectivity', 'distance'}, default='connectivity'
    Type of returned matrix: 'connectivity' will return the connectivity
    matrix with ones and zeros, and 'distance' will return the distances
    between neighbors according to the given metric.
metric : str, default='minkowski'
    Metric to use for distance computation. Default is "minkowski", which
    results in the standard Euclidean distance when p = 2. See the
    documentation of `scipy.spatial.distance
    <https://docs.scipy.org/doc/scipy/reference/spatial.distance.html>`_ and
    the metrics listed in
    :class:`~sklearn.metrics.pairwise.distance_metrics` for valid metric
    values.
p : float, default=2
    Power parameter for the Minkowski metric. When p = 1, this is
    equivalent to using manhattan_distance (l1), and euclidean_distance
    (l2) for p = 2. For arbitrary p, minkowski_distance (l_p) is used.
metric_params : dict, default=None
    Additional keyword arguments for the metric function.
include_self : bool or 'auto', default=False
    Whether or not to mark each sample as the first nearest neighbor to
    itself. If 'auto', then True is used for mode='connectivity' and False
    for mode='distance'.
n_jobs : int, default=None
    The number of parallel jobs to run for neighbors search.
    ``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.
    ``-1`` means using all processors. See :term:`Glossary <n_jobs>`
    for more details.
Returns
-------
A : sparse matrix of shape (n_samples, n_samples)
    Graph where A[i, j] is assigned the weight of edge that connects
    i to j. The matrix is of CSR format.
See Also
--------
kneighbors_graph: Compute the weighted graph of k-neighbors for points in X.
Examples
--------
>>> X = [[0], [3], [1]]
>>> from sklearn.neighbors import radius_neighbors_graph
>>> A = radius_neighbors_graph(X, 1.5, mode='connectivity',
...                            include_self=True)
>>> A.toarray()
array([[1., 0., 1.],
       [0., 1., 0.],
       [1., 0., 1.]])
Definition at line 163 of file _graph.py.
References _check_params(), and _query_include_self().