Code Cloning Analysis: pandas.io.formats.excel.CSSToExcelConverter Class Reference
pandas.io.formats.excel.CSSToExcelConverter Class Reference
Public Member Functions
None __init__ (self, str|None inherited=None)
dict[str, dict[str, str]] __call__ (self, str|frozenset[tuple[str, str]] declarations)
dict[str, dict[str, str]] build_xlstyle (self, Mapping[str, str] props)
dict[str, bool|str|None] build_alignment (self, Mapping[str, str] props)
dict[str, dict[str, str|None]] build_border (self, Mapping[str, str] props)
build_fill (self, Mapping[str, str] props)
dict[str, str|None] build_number_format (self, Mapping[str, str] props)
dict[str, bool|float|str|None] build_font (self, Mapping[str, str] props)
str|None color_to_excel (self, str|None val)
Static Public Attributes
NAMED_COLORS = CSS4_COLORS
dict VERTICAL_MAP
dict BOLD_MAP
dict ITALIC_MAP
dict FAMILY_MAP
dict BORDER_STYLE_MAP
dict inherited [str, str] | None
compute_css = CSSResolver()
Protected Member Functions
dict[str, dict[str, str]] _call_uncached (self, str|frozenset[tuple[str, str]] declarations)
str|None _get_vertical_alignment (self, Mapping[str, str] props)
bool|None _get_is_wrap_text (self, Mapping[str, str] props)
_border_style (self, str|None style, str|None width, str|None color)
str|None _get_width_name (self, str|None width_input)
float _width_to_float (self, str|None width)
float _pt_to_float (self, str pt_string)
bool|None _get_is_bold (self, Mapping[str, str] props)
bool|None _get_is_italic (self, Mapping[str, str] props)
Sequence[str] _get_decoration (self, Mapping[str, str] props)
str|None _get_underline (self, Sequence[str] decoration)
bool|None _get_shadow (self, Mapping[str, str] props)
Sequence[str] _get_font_names (self, Mapping[str, str] props)
float|None _get_font_size (self, Mapping[str, str] props)
int|None _select_font_family (self, Sequence[str] font_names)
bool _is_hex_color (self, str color_string)
str _convert_hex_to_excel (self, str color_string)
bool _is_shorthand_color (self, str color_string)
Protected Attributes
_call_cached = functools.cache(self._call_uncached)
Detailed Description
A callable for converting CSS declarations to ExcelWriter styles
Supports parts of CSS 2.2, with minimal CSS 3.0 support (e.g. text-shadow),
focusing on font styling, backgrounds, borders and alignment.
Operates by first computing CSS styles in a fairly generic
way (see :meth:`compute_css`) then determining Excel style
properties from CSS properties (see :meth:`build_xlstyle`).
Parameters
----------
inherited : str, optional
    CSS declarations understood to be the containing scope for the
    CSS processed by :meth:`__call__`.
Definition at line 109 of file excel.py.
Constructor & Destructor Documentation
__init__()
None pandas.io.formats.excel.CSSToExcelConverter.__init__ (self, str | None inherited = None)
Definition at line 190 of file excel.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__call__()
dict[str, dict[str, str]] pandas.io.formats.excel.CSSToExcelConverter.__call__ (self, str | frozenset[tuple[str, str]] declarations)
Convert CSS declarations to ExcelWriter style.
Parameters
----------
declarations : str | frozenset[tuple[str, str]]
    CSS string or set of CSS declaration tuples.
    e.g. "font-weight: bold; background: blue" or
    {("font-weight", "bold"), ("background", "blue")}
Returns
-------
xlstyle : dict
    A style as interpreted by ExcelWriter when found in
    ExcelCell.style.
Definition at line 202 of file excel.py.
References _border_style(), _call_cached, _convert_hex_to_excel(), _get_decoration(), _get_font_names(), pandas.io.formats.css.CSSResolver._get_font_size(), _get_font_size(), _get_is_bold(), _get_is_italic(), _get_is_wrap_text(), _get_shadow(), _get_vertical_alignment(), _get_width_name(), _is_hex_color(), _is_shorthand_color(), _pt_to_float(), _select_font_family(), _width_to_float(), BOLD_MAP, BORDER_STYLE_MAP, build_alignment(), build_border(), build_fill(), build_font(), build_number_format(), build_xlstyle(), color_to_excel(), compute_css, FAMILY_MAP, inherited, ITALIC_MAP, NAMED_COLORS, and VERTICAL_MAP.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), and scipy.interpolate._fitpack2.SphereBivariateSpline.ev().
_border_style()
pandas.io.formats.excel.CSSToExcelConverter._border_style (self, str | None style, str | None width, str | None color) protected
Definition at line 287 of file excel.py.
Referenced by __call__().
_call_uncached()
dict[str, dict[str, str]] pandas.io.formats.excel.CSSToExcelConverter._call_uncached (self, str | frozenset[tuple[str, str]] declarations) protected
Definition at line 223 of file excel.py.
_convert_hex_to_excel()
str pandas.io.formats.excel.CSSToExcelConverter._convert_hex_to_excel (self, str color_string) protected
Definition at line 481 of file excel.py.
Referenced by __call__().
_get_decoration()
Sequence[str] pandas.io.formats.excel.CSSToExcelConverter._get_decoration (self, Mapping[str, str] props) protected
Definition at line 403 of file excel.py.
Referenced by __call__().
_get_font_names()
Sequence[str] pandas.io.formats.excel.CSSToExcelConverter._get_font_names (self, Mapping[str, str] props) protected
Definition at line 420 of file excel.py.
Referenced by __call__().
_get_font_size()
float | None pandas.io.formats.excel.CSSToExcelConverter._get_font_size (self, Mapping[str, str] props) protected
Definition at line 446 of file excel.py.
Referenced by __call__().
_get_is_bold()
bool | None pandas.io.formats.excel.CSSToExcelConverter._get_is_bold (self, Mapping[str, str] props) protected
Definition at line 391 of file excel.py.
Referenced by __call__().
_get_is_italic()
bool | None pandas.io.formats.excel.CSSToExcelConverter._get_is_italic (self, Mapping[str, str] props) protected
Definition at line 397 of file excel.py.
Referenced by __call__().
_get_is_wrap_text()
bool | None pandas.io.formats.excel.CSSToExcelConverter._get_is_wrap_text (self, Mapping[str, str] props) protected
Definition at line 267 of file excel.py.
Referenced by __call__().
_get_shadow()
bool | None pandas.io.formats.excel.CSSToExcelConverter._get_shadow (self, Mapping[str, str] props) protected
Definition at line 415 of file excel.py.
Referenced by __call__().
_get_underline()
str | None pandas.io.formats.excel.CSSToExcelConverter._get_underline (self, Sequence[str] decoration) protected
Definition at line 410 of file excel.py.
_get_vertical_alignment()
str | None pandas.io.formats.excel.CSSToExcelConverter._get_vertical_alignment (self, Mapping[str, str] props) protected
Definition at line 261 of file excel.py.
Referenced by __call__().
_get_width_name()
str | None pandas.io.formats.excel.CSSToExcelConverter._get_width_name (self, str | None width_input) protected
Definition at line 342 of file excel.py.
Referenced by __call__().
_is_hex_color()
bool pandas.io.formats.excel.CSSToExcelConverter._is_hex_color (self, str color_string) protected
Definition at line 478 of file excel.py.
Referenced by __call__().
_is_shorthand_color()
bool pandas.io.formats.excel.CSSToExcelConverter._is_shorthand_color (self, str color_string) protected
Check if color code is shorthand.
#FFF is a shorthand as opposed to full #FFFFFF.
Definition at line 488 of file excel.py.
Referenced by __call__().
_pt_to_float()
float pandas.io.formats.excel.CSSToExcelConverter._pt_to_float (self, str pt_string) protected
Definition at line 357 of file excel.py.
Referenced by __call__().
_select_font_family()
int | None pandas.io.formats.excel.CSSToExcelConverter._select_font_family (self, Sequence[str] font_names) protected
Definition at line 452 of file excel.py.
Referenced by __call__().
_width_to_float()
float pandas.io.formats.excel.CSSToExcelConverter._width_to_float (self, str | None width) protected
Definition at line 352 of file excel.py.
Referenced by __call__().
build_alignment()
dict[str, bool | str | None] pandas.io.formats.excel.CSSToExcelConverter.build_alignment (self, Mapping[str, str] props)
Definition at line 253 of file excel.py.
Referenced by __call__().
build_border()
dict[str, dict[str, str | None]] pandas.io.formats.excel.CSSToExcelConverter.build_border (self, Mapping[str, str] props)
Definition at line 272 of file excel.py.
Referenced by __call__().
build_fill()
pandas.io.formats.excel.CSSToExcelConverter.build_fill (self, Mapping[str, str] props)
Definition at line 361 of file excel.py.
Referenced by __call__().
build_font()
dict[str, bool | float | str | None] pandas.io.formats.excel.CSSToExcelConverter.build_font (self, Mapping[str, str] props)
Definition at line 373 of file excel.py.
Referenced by __call__().
build_number_format()
dict[str, str | None] pandas.io.formats.excel.CSSToExcelConverter.build_number_format (self, Mapping[str, str] props)
Definition at line 368 of file excel.py.
Referenced by __call__().
build_xlstyle()
dict[str, dict[str, str]] pandas.io.formats.excel.CSSToExcelConverter.build_xlstyle (self, Mapping[str, str] props)
Definition at line 229 of file excel.py.
Referenced by __call__().
color_to_excel()
str | None pandas.io.formats.excel.CSSToExcelConverter.color_to_excel (self, str | None val)
Definition at line 461 of file excel.py.
Referenced by __call__().
Member Data Documentation
_call_cached
pandas.io.formats.excel.CSSToExcelConverter._call_cached = functools.cache(self._call_uncached) protected
Definition at line 198 of file excel.py.
Referenced by __call__().
BOLD_MAP
dict pandas.io.formats.excel.CSSToExcelConverter.BOLD_MAP static
Initial value:
=  {
        "bold": True,
        "bolder": True,
        "600": True,
        "700": True,
        "800": True,
        "900": True,
        "normal": False,
        "lighter": False,
        "100": False,
        "200": False,
        "300": False,
        "400": False,
        "500": False,
    }
Definition at line 139 of file excel.py.
Referenced by __call__().
BORDER_STYLE_MAP
dict pandas.io.formats.excel.CSSToExcelConverter.BORDER_STYLE_MAP static
Initial value:
=  {
        style.lower(): style
        for style in [
            "dashed",
            "mediumDashDot",
            "dashDotDot",
            "hair",
            "dotted",
            "mediumDashDotDot",
            "double",
            "dashDot",
            "slantDashDot",
            "mediumDashed",
        ]
    }
Definition at line 168 of file excel.py.
Referenced by __call__().
compute_css
pandas.io.formats.excel.CSSToExcelConverter.compute_css = CSSResolver() static
Definition at line 200 of file excel.py.
Referenced by __call__().
FAMILY_MAP
dict pandas.io.formats.excel.CSSToExcelConverter.FAMILY_MAP static
Initial value:
=  {
        "serif": 1,  # roman
        "sans-serif": 2,  # swiss
        "cursive": 4,  # script
        "fantasy": 5,  # decorative
    }
Definition at line 161 of file excel.py.
Referenced by __call__().
inherited
dict pandas.io.formats.excel.CSSToExcelConverter.inherited [str, str] | None static
Definition at line 188 of file excel.py.
Referenced by __call__().
ITALIC_MAP
dict pandas.io.formats.excel.CSSToExcelConverter.ITALIC_MAP static
Initial value:
=  {
        "normal": False,
        "italic": True,
        "oblique": True,
    }
Definition at line 155 of file excel.py.
Referenced by __call__().
NAMED_COLORS
pandas.io.formats.excel.CSSToExcelConverter.NAMED_COLORS = CSS4_COLORS static
Definition at line 127 of file excel.py.
Referenced by __call__().
VERTICAL_MAP
dict pandas.io.formats.excel.CSSToExcelConverter.VERTICAL_MAP static
Initial value:
=  {
        "top": "top",
        "text-top": "top",
        "middle": "center",
        "baseline": "bottom",
        "bottom": "bottom",
        "text-bottom": "bottom",
        # OpenXML also has 'justify', 'distributed'
    }
Definition at line 129 of file excel.py.
Referenced by __call__().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/io/formats/excel.py