Code Cloning Analysis: scipy.optimize._nonlin.BroydenFirst Class Reference
scipy.optimize._nonlin.BroydenFirst Class Reference
Public Member Functions
__init__ (self, alpha=None, reduction_method='restart', max_rank=None)
setup (self, x, F, func)
todense (self)
solve (self, f, tol=0)
matvec (self, f)
rsolve (self, f, tol=0)
rmatvec (self, f)
Public Member Functions inherited from scipy.optimize._nonlin.GenericBroyden
update (self, x, f)
Public Member Functions inherited from scipy.optimize._nonlin.Jacobian
__init__ (self, **kw)
aspreconditioner (self)
Public Attributes
Gm = None
max_rank = max_rank
Public Attributes inherited from scipy.optimize._nonlin.GenericBroyden
last_f = f0
last_x = x0
float alpha = 0.5*max(norm(x0), 1) / normf0
Public Attributes inherited from scipy.optimize._nonlin.Jacobian
func = func
tuple shape = (F.size, x.size)
dtype = F.dtype
Protected Member Functions
_update (self, x, f, dx, df, dx_norm, df_norm)
Protected Attributes
_reduce = lambda: self.Gm.svd_reduce(*reduce_params)
Detailed Description
Find a root of a function, using Broyden's first Jacobian approximation.
This method is also known as \"Broyden's good method\".
Parameters
----------
%(params_basic)s
%(broyden_params)s
%(params_extra)s
See Also
--------
root : Interface to root finding algorithms for multivariate
       functions. See ``method='broyden1'`` in particular.
Notes
-----
This algorithm implements the inverse Jacobian Quasi-Newton update
.. math:: H_+ = H + (dx - H df) dx^\dagger H / (dx^\dagger H df)
which corresponds to Broyden's first Jacobian update
.. math:: J_+ = J + (df - J dx) dx^\dagger / dx^\dagger dx
References
----------
.. [1] B.A. van der Rotten, PhD thesis,
   \"A limited memory Broyden method to solve high-dimensional
   systems of nonlinear equations\". Mathematisch Instituut,
   Universiteit Leiden, The Netherlands (2003).
   https://web.archive.org/web/20161022015821/http://www.math.leidenuniv.nl/scripties/Rotten.pdf
Examples
--------
The following functions define a system of nonlinear equations
>>> def fun(x):
...     return [x[0]  + 0.5 * (x[0] - x[1])**3 - 1.0,
...             0.5 * (x[1] - x[0])**3 + x[1]]
A solution can be obtained as follows.
>>> from scipy import optimize
>>> sol = optimize.broyden1(fun, [0, 0])
>>> sol
array([0.84116396, 0.15883641])
Definition at line 804 of file _nonlin.py.
Constructor & Destructor Documentation
__init__()
scipy.optimize._nonlin.BroydenFirst.__init__ (self, alpha = None, reduction_method = 'restart', max_rank = None)
Definition at line 858 of file _nonlin.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
_update()
scipy.optimize._nonlin.BroydenFirst._update (self, x, f, dx, df, dx_norm, df_norm) protected
Reimplemented from scipy.optimize._nonlin.GenericBroyden.
Definition at line 908 of file _nonlin.py.
matvec()
scipy.optimize._nonlin.BroydenFirst.matvec (self, f)
Definition at line 899 of file _nonlin.py.
Referenced by scipy.sparse.linalg._interface.LinearOperator._init_dtype(), scipy.sparse.linalg._interface.LinearOperator._matmat(), and scipy.sparse.linalg._interface.LinearOperator.dot().
rmatvec()
scipy.optimize._nonlin.BroydenFirst.rmatvec (self, f)
Definition at line 905 of file _nonlin.py.
Referenced by scipy.sparse.linalg._interface.LinearOperator._rmatmat().
rsolve()
scipy.optimize._nonlin.BroydenFirst.rsolve (self, f, tol = 0)
Definition at line 902 of file _nonlin.py.
setup()
scipy.optimize._nonlin.BroydenFirst.setup (self, x, F, func)
Reimplemented from scipy.optimize._nonlin.GenericBroyden.
Definition at line 884 of file _nonlin.py.
solve()
scipy.optimize._nonlin.BroydenFirst.solve (self, f, tol = 0)
Reimplemented from scipy.optimize._nonlin.Jacobian.
Definition at line 891 of file _nonlin.py.
todense()
scipy.optimize._nonlin.BroydenFirst.todense (self)
Definition at line 888 of file _nonlin.py.
Referenced by scipy.sparse._base._spbase._divide(), scipy.sparse._compressed._cs_matrix._maximum_minimum(), scipy.sparse._compressed._cs_matrix._scalar_binopt(), scipy.sparse._dok._dok_base.get(), and scipy.sparse._base._spbase.power().
Member Data Documentation
_reduce
scipy.optimize._nonlin.BroydenFirst._reduce = lambda: self.Gm.svd_reduce(*reduce_params) protected
Definition at line 875 of file _nonlin.py.
Referenced by pandas.core.series.Series._reduce(), pandas.core.arrays.arrow.array.ArrowExtensionArray.all(), pandas.core.arrays.arrow.array.ArrowExtensionArray.any(), and pandas.core.generic.NDFrame.pct_change().
Gm
scipy.optimize._nonlin.BroydenFirst.Gm = None
Definition at line 861 of file _nonlin.py.
max_rank
scipy.optimize._nonlin.BroydenFirst.max_rank = max_rank
Definition at line 865 of file _nonlin.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/optimize/_nonlin.py