Code Cloning Analysis: fontTools.voltLib.parser.SymbolTable Class Reference
fontTools.voltLib.parser.SymbolTable Class Reference
Public Member Functions
__init__ (self)
enter_scope (self)
exit_scope (self)
define (self, name, item)
resolve (self, name, case_insensitive=True)
Public Attributes
list scopes_ = [{}]
Detailed Description
Definition at line 623 of file parser.py.
Constructor & Destructor Documentation
__init__()
fontTools.voltLib.parser.SymbolTable.__init__ (self)
Definition at line 624 of file parser.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
define()
fontTools.voltLib.parser.SymbolTable.define (self, name, item)
Definition at line 633 of file parser.py.
enter_scope()
fontTools.voltLib.parser.SymbolTable.enter_scope (self)
Definition at line 627 of file parser.py.
exit_scope()
fontTools.voltLib.parser.SymbolTable.exit_scope (self)
Definition at line 630 of file parser.py.
resolve()
fontTools.voltLib.parser.SymbolTable.resolve (self, name, case_insensitive = True)
Definition at line 636 of file parser.py.
Referenced by pip._vendor.distlib.compat.BaseConfigurator.configure_custom(), and pip._vendor.distlib.compat.BaseConfigurator.ext_convert().
Member Data Documentation
scopes_
fontTools.voltLib.parser.SymbolTable.scopes_ = [{}]
Definition at line 625 of file parser.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/voltLib/parser.py