Code Cloning Analysis: sklearn._loss.loss.HalfTweedieLoss Class Reference
sklearn._loss.loss.HalfTweedieLoss Class Reference
Public Member Functions
__init__ (self, sample_weight=None, power=1.5)
constant_to_optimal_zero (self, y_true, sample_weight=None)
Public Member Functions inherited from sklearn._loss.loss.BaseLoss
__init__ (self, closs, link, n_classes=None)
in_y_true_range (self, y)
in_y_pred_range (self, y)
loss (self, y_true, raw_prediction, sample_weight=None, loss_out=None, n_threads=1)
loss_gradient (self, y_true, raw_prediction, sample_weight=None, loss_out=None, gradient_out=None, n_threads=1)
gradient (self, y_true, raw_prediction, sample_weight=None, gradient_out=None, n_threads=1)
gradient_hessian (self, y_true, raw_prediction, sample_weight=None, gradient_out=None, hessian_out=None, n_threads=1)
__call__ (self, y_true, raw_prediction, sample_weight=None, n_threads=1)
fit_intercept_only (self, y_true, sample_weight=None)
init_gradient_and_hessian (self, n_samples, dtype=np.float64, order="F")
Additional Inherited Members
Public Attributes inherited from sklearn._loss.loss.BaseLoss
closs = closs
link = link
bool approx_hessian = False
bool constant_hessian = False
n_classes = n_classes
interval_y_true = Interval(-np.inf, np.inf, False, False)
interval_y_pred = self.link.interval_y_pred
Static Public Attributes inherited from sklearn._loss.loss.BaseLoss
bool differentiable = True
bool need_update_leaves_values = False
bool is_multiclass = False
Detailed Description
Half Tweedie deviance loss with log-link, for regression.
Domain:
y_true in real numbers for power <= 0
y_true in non-negative real numbers for 0 < power < 2
y_true in positive real numbers for 2 <= power
y_pred in positive real numbers
power in real numbers
Link:
y_pred = exp(raw_prediction)
For a given sample x_i, half Tweedie deviance loss with p=power is defined
as::
    loss(x_i) = max(y_true_i, 0)**(2-p) / (1-p) / (2-p)
                - y_true_i * exp(raw_prediction_i)**(1-p) / (1-p)
                + exp(raw_prediction_i)**(2-p) / (2-p)
Taking the limits for p=0, 1, 2 gives HalfSquaredError with a log link,
HalfPoissonLoss and HalfGammaLoss.
We also skip constant terms, but those are different for p=0, 1, 2.
Therefore, the loss is not continuous in `power`.
Note furthermore that although no Tweedie distribution exists for
0 < power < 1, it still gives a strictly consistent scoring function for
the expectation.
Definition at line 779 of file loss.py.
Constructor & Destructor Documentation
__init__()
sklearn._loss.loss.HalfTweedieLoss.__init__ (self, sample_weight = None, power = 1.5)
Definition at line 810 of file loss.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params().
Member Function Documentation
constant_to_optimal_zero()
sklearn._loss.loss.HalfTweedieLoss.constant_to_optimal_zero (self, y_true, sample_weight = None)
Calculate term dropped in loss.
With this term added, the loss of perfect predictions is zero.
Reimplemented from sklearn._loss.loss.BaseLoss.
Definition at line 822 of file loss.py.
References sklearn._loss.loss.BaseLoss.closs, and constant_to_optimal_zero().
Referenced by constant_to_optimal_zero().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/sklearn/_loss/loss.py