Code Cloning Analysis: fontTools.misc.loggingTools.LogMixin Class Reference
fontTools.misc.loggingTools.LogMixin Class Reference
Public Member Functions
log (self)
Protected Attributes
_log = logging.getLogger(name)
Detailed Description
Mixin class that adds logging functionality to another class.
You can define a new class that subclasses from ``LogMixin`` as well as
other base classes through multiple inheritance.
All instances of that class will have a ``log`` property that returns
a ``logging.Logger`` named after their respective ``<module>.<class>``.
For example:
>>> class BaseClass(object):
...     pass
>>> class MyClass(LogMixin, BaseClass):
...     pass
>>> a = MyClass()
>>> isinstance(a.log, logging.Logger)
True
>>> print(a.log.name)
fontTools.misc.loggingTools.MyClass
>>> class AnotherClass(MyClass):
...     pass
>>> b = AnotherClass()
>>> isinstance(b.log, logging.Logger)
True
>>> print(b.log.name)
fontTools.misc.loggingTools.AnotherClass
Definition at line 481 of file loggingTools.py.
Member Function Documentation
log()
fontTools.misc.loggingTools.LogMixin.log (self)
Definition at line 510 of file loggingTools.py.
Referenced by fontTools.pens.basePen.DecomposingPen.addComponent(), fontTools.pens.pointPen.DecomposingPointPen.addComponent(), fontTools.pens.ttGlyphPen._TTGlyphBasePen.addComponent(), and fontTools.designspaceLib.BaseDocReader.readLocationElement().
Member Data Documentation
_log
fontTools.misc.loggingTools.LogMixin._log = logging.getLogger(name) protected
Definition at line 513 of file loggingTools.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/misc/loggingTools.py