Code Cloning Analysis: matplotlib.artist.ArtistInspector Class Reference
matplotlib.artist.ArtistInspector Class Reference
Public Member Functions
__init__ (self, o)
get_aliases (self)
get_valid_values (self, attr)
get_setters (self)
aliased_name (self, s)
aliased_name_rest (self, s, target)
pprint_setters (self, prop=None, leadingspace=2)
pprint_setters_rest (self, prop=None, leadingspace=4)
properties (self)
pprint_getters (self)
Static Public Member Functions
number_of_parameters (func)
is_alias (method)
Public Attributes
oorig = o
o = o
aliasd = self.get_aliases()
Protected Member Functions
_replace_path (self, source_class)
Static Protected Attributes
_get_valid_values_regex
dict _NOT_LINKABLE
Detailed Description
A helper class to inspect an `~matplotlib.artist.Artist` and return
information about its settable properties and their current values.
Definition at line 1407 of file artist.py.
Constructor & Destructor Documentation
__init__()
matplotlib.artist.ArtistInspector.__init__ (self, o)
    Initialize the artist inspector with an `Artist` or an iterable of
    `Artist`\s.  If an iterable is used, we assume it is a homogeneous
    sequence (all `Artist`\s are of the same type) and it is your
    responsibility to make sure this is so.
Definition at line 1413 of file artist.py.
References aliasd, get_aliases(), o, and oorig.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_replace_path()
matplotlib.artist.ArtistInspector._replace_path (self, source_class) protected
Changes the full path to the public API path that is used
in sphinx. This is needed for links to work.
Definition at line 1500 of file artist.py.
aliased_name()
matplotlib.artist.ArtistInspector.aliased_name (self, s)
Return 'PROPNAME or alias' if *s* has an alias, else return 'PROPNAME'.
For example, for the line markerfacecolor property, which has an
alias, return 'markerfacecolor or mfc' and for the transform
property, which does not, return 'transform'.
Definition at line 1549 of file artist.py.
References aliasd.
Referenced by pprint_getters(), and pprint_setters().
aliased_name_rest()
matplotlib.artist.ArtistInspector.aliased_name_rest (self, s, target)
Return 'PROPNAME or alias' if *s* has an alias, else return 'PROPNAME',
formatted for reST.
For example, for the line markerfacecolor property, which has an
alias, return 'markerfacecolor or mfc' and for the transform
property, which does not, return 'transform'.
Definition at line 1576 of file artist.py.
References _NOT_LINKABLE, and aliasd.
Referenced by pprint_setters_rest().
get_aliases()
matplotlib.artist.ArtistInspector.get_aliases (self)
Get a dict mapping property fullnames to sets of aliases for each alias
in the :class:`~matplotlib.artist.ArtistInspector`.
e.g., for lines::
  {'markerfacecolor': {'mfc'},
   'linewidth'      : {'lw'},
  }
Definition at line 1433 of file artist.py.
References is_alias(), and o.
Referenced by __init__().
get_setters()
matplotlib.artist.ArtistInspector.get_setters (self)
Get the attribute strings with setters for object.
For example, for a line, return ``['markerfacecolor', 'linewidth',
....]``.
Definition at line 1511 of file artist.py.
References is_alias(), number_of_parameters(), and o.
Referenced by pprint_setters(), and pprint_setters_rest().
get_valid_values()
matplotlib.artist.ArtistInspector.get_valid_values (self, attr)
Get the legal arguments for the setter associated with *attr*.
This is done by querying the docstring of the setter for a line that
begins with "ACCEPTS:" or ".. ACCEPTS:", and then by looking for a
numpydoc-style documentation for the setter's first argument.
Definition at line 1461 of file artist.py.
References _get_valid_values_regex, and o.
Referenced by pprint_setters(), and pprint_setters_rest().
is_alias()
matplotlib.artist.ArtistInspector.is_alias (method) static
Return whether the object *method* is an alias for another method.
Definition at line 1538 of file artist.py.
Referenced by get_aliases(), get_setters(), and properties().
number_of_parameters()
matplotlib.artist.ArtistInspector.number_of_parameters (func) static
Return number of parameters of the callable *func*.
Definition at line 1532 of file artist.py.
Referenced by get_setters().
pprint_getters()
matplotlib.artist.ArtistInspector.pprint_getters (self)
Return the getters and actual values as list of strings.
Definition at line 1693 of file artist.py.
References aliased_name(), properties(), and scipy._lib._docscrape.ClassDoc.properties.
pprint_setters()
matplotlib.artist.ArtistInspector.pprint_setters (self, prop = None, leadingspace = 2)
If *prop* is *None*, return a list of strings of all settable
properties and their valid values.
If *prop* is not *None*, it is a valid property name and that
property will be returned as a string of property : valid
values.
Definition at line 1593 of file artist.py.
References aliased_name(), get_setters(), and get_valid_values().
pprint_setters_rest()
matplotlib.artist.ArtistInspector.pprint_setters_rest (self, prop = None, leadingspace = 4)
If *prop* is *None*, return a list of reST-formatted strings of all
settable properties and their valid values.
If *prop* is not *None*, it is a valid property name and that
property will be returned as a string of "property : valid"
values.
Definition at line 1617 of file artist.py.
References aliased_name_rest(), get_setters(), get_valid_values(), and o.
properties()
matplotlib.artist.ArtistInspector.properties (self)
Return a dictionary mapping property name -> value.
Definition at line 1672 of file artist.py.
References is_alias(), and oorig.
Referenced by pprint_getters().
Member Data Documentation
_get_valid_values_regex
matplotlib.artist.ArtistInspector._get_valid_values_regex static protected
Initial value:
=  re.compile(
        r"\n\s*(?:\.\.\s+)?ACCEPTS:\s*((?:.|\n)*?)(?:$|(?:\n\n))"
    )
Definition at line 1457 of file artist.py.
Referenced by get_valid_values().
_NOT_LINKABLE
dict matplotlib.artist.ArtistInspector._NOT_LINKABLE static protected
Initial value:
=  {
        # A set of property setter methods that are not available in our
        # current docs. This is a workaround used to prevent trying to link
        # these setters which would lead to "target reference not found"
        # warnings during doc build.
        'matplotlib.image._ImageBase.set_alpha',
        'matplotlib.image._ImageBase.set_array',
        'matplotlib.image._ImageBase.set_data',
        'matplotlib.image._ImageBase.set_filternorm',
        'matplotlib.image._ImageBase.set_filterrad',
        'matplotlib.image._ImageBase.set_interpolation',
        'matplotlib.image._ImageBase.set_interpolation_stage',
        'matplotlib.image._ImageBase.set_resample',
        'matplotlib.text._AnnotationBase.set_annotation_clip',
    }
Definition at line 1560 of file artist.py.
Referenced by aliased_name_rest().
aliasd
matplotlib.artist.ArtistInspector.aliasd = self.get_aliases()
Definition at line 1431 of file artist.py.
Referenced by __init__(), aliased_name(), and aliased_name_rest().
o
matplotlib.artist.ArtistInspector.o = o
Definition at line 1429 of file artist.py.
Referenced by __init__(), get_aliases(), get_setters(), get_valid_values(), and pprint_setters_rest().
oorig
matplotlib.artist.ArtistInspector.oorig = o
Definition at line 1426 of file artist.py.
Referenced by __init__(), and properties().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/artist.py