Code Cloning Analysis: pip._internal.operations.install.wheel.ZipBackedFile Class Reference
pip._internal.operations.install.wheel.ZipBackedFile Class Reference
Public Member Functions
None __init__ (self, RecordPath src_record_path, str dest_path, ZipFile zip_file)
None save (self)
Public Attributes
src_record_path = src_record_path
dest_path = dest_path
bool changed = False
Protected Member Functions
ZipInfo _getinfo (self)
Protected Attributes
_zip_file = zip_file
Detailed Description
Definition at line 350 of file wheel.py.
Constructor & Destructor Documentation
__init__()
None pip._internal.operations.install.wheel.ZipBackedFile.__init__ (self, RecordPath src_record_path, str dest_path, ZipFile zip_file)
Definition at line 351 of file wheel.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
_getinfo()
ZipInfo pip._internal.operations.install.wheel.ZipBackedFile._getinfo (self) protected
Definition at line 359 of file wheel.py.
save()
None pip._internal.operations.install.wheel.ZipBackedFile.save (self)
Definition at line 362 of file wheel.py.
Referenced by joblib.externals.cloudpickle.cloudpickle.Pickler.reducer_override().
Member Data Documentation
_zip_file
pip._internal.operations.install.wheel.ZipBackedFile._zip_file = zip_file protected
Definition at line 356 of file wheel.py.
changed
bool pip._internal.operations.install.wheel.ZipBackedFile.changed = False
Definition at line 357 of file wheel.py.
Referenced by matplotlib.colorizer._ScalarMappable.__init__(), matplotlib.colorizer.ColorizingArtist.__init__(), matplotlib.contour.ContourSet.__init__(), matplotlib.colorizer.Colorizer._scale_norm(), and matplotlib.colorizer.Colorizer._set_cmap().
dest_path
pip._internal.operations.install.wheel.ZipBackedFile.dest_path = dest_path
Definition at line 355 of file wheel.py.
src_record_path
pip._internal.operations.install.wheel.ZipBackedFile.src_record_path = src_record_path
Definition at line 354 of file wheel.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pip/_internal/operations/install/wheel.py