Code Cloning Analysis: sklearn.metrics.cluster._unsupervised Namespace Reference
sklearn.metrics.cluster._unsupervised Namespace Reference
Functions
check_number_of_labels (n_labels, n_samples)
silhouette_score (X, labels, *, metric="euclidean", sample_size=None, random_state=None, **kwds)
_silhouette_reduce (D_chunk, start, labels, label_freqs)
silhouette_samples (X, labels, *, metric="euclidean", **kwds)
calinski_harabasz_score (X, labels)
davies_bouldin_score (X, labels)
Detailed Description
Unsupervised evaluation metrics.
Function Documentation
_silhouette_reduce()
sklearn.metrics.cluster._unsupervised._silhouette_reduce (D_chunk, start, labels, label_freqs) protected
Accumulate silhouette statistics for vertical chunk of X.
Parameters
----------
D_chunk : {array-like, sparse matrix} of shape (n_chunk_samples, n_samples)
    Precomputed distances for a chunk. If a sparse matrix is provided,
    only CSR format is accepted.
start : int
    First index in the chunk.
labels : array-like of shape (n_samples,)
    Corresponding cluster labels, encoded as {0, ..., n_clusters-1}.
label_freqs : array-like
    Distribution of cluster labels in ``labels``.
Definition at line 141 of file _unsupervised.py.
calinski_harabasz_score()
sklearn.metrics.cluster._unsupervised.calinski_harabasz_score (X, labels)
Compute the Calinski and Harabasz score.
It is also known as the Variance Ratio Criterion.
The score is defined as ratio of the sum of between-cluster dispersion and
of within-cluster dispersion.
Read more in the :ref:`User Guide <calinski_harabasz_index>`.
Parameters
----------
X : array-like of shape (n_samples, n_features)
    A list of ``n_features``-dimensional data points. Each row corresponds
    to a single data point.
labels : array-like of shape (n_samples,)
    Predicted labels for each sample.
Returns
-------
score : float
    The resulting Calinski-Harabasz score.
References
----------
.. [1] `T. Calinski and J. Harabasz, 1974. "A dendrite method for cluster
   analysis". Communications in Statistics
   <https://www.tandfonline.com/doi/abs/10.1080/03610927408827101>`_
Examples
--------
>>> from sklearn.datasets import make_blobs
>>> from sklearn.cluster import KMeans
>>> from sklearn.metrics import calinski_harabasz_score
>>> X, _ = make_blobs(random_state=0)
>>> kmeans = KMeans(n_clusters=3, random_state=0,).fit(X)
>>> calinski_harabasz_score(X, kmeans.labels_)
114.8...
Definition at line 325 of file _unsupervised.py.
References check_number_of_labels().
check_number_of_labels()
sklearn.metrics.cluster._unsupervised.check_number_of_labels (n_labels, n_samples)
Check that number of labels are valid.
Parameters
----------
n_labels : int
    Number of labels.
n_samples : int
    Number of samples.
Definition at line 23 of file _unsupervised.py.
Referenced by calinski_harabasz_score(), davies_bouldin_score(), and silhouette_samples().
davies_bouldin_score()
sklearn.metrics.cluster._unsupervised.davies_bouldin_score (X, labels)
Compute the Davies-Bouldin score.
The score is defined as the average similarity measure of each cluster with
its most similar cluster, where similarity is the ratio of within-cluster
distances to between-cluster distances. Thus, clusters which are farther
apart and less dispersed will result in a better score.
The minimum score is zero, with lower values indicating better clustering.
Read more in the :ref:`User Guide <davies-bouldin_index>`.
.. versionadded:: 0.20
Parameters
----------
X : array-like of shape (n_samples, n_features)
    A list of ``n_features``-dimensional data points. Each row corresponds
    to a single data point.
labels : array-like of shape (n_samples,)
    Predicted labels for each sample.
Returns
-------
score: float
    The resulting Davies-Bouldin score.
References
----------
.. [1] Davies, David L.; Bouldin, Donald W. (1979).
   `"A Cluster Separation Measure"
   <https://ieeexplore.ieee.org/document/4766909>`__.
   IEEE Transactions on Pattern Analysis and Machine Intelligence.
   PAMI-1 (2): 224-227
Examples
--------
>>> from sklearn.metrics import davies_bouldin_score
>>> X = [[0, 1], [1, 1], [3, 4]]
>>> labels = [0, 0, 1]
>>> davies_bouldin_score(X, labels)
0.12...
Definition at line 396 of file _unsupervised.py.
References check_number_of_labels().
silhouette_samples()
sklearn.metrics.cluster._unsupervised.silhouette_samples (X, labels, * , metric = "euclidean", ** kwds)
Compute the Silhouette Coefficient for each sample.
The Silhouette Coefficient is a measure of how well samples are clustered
with samples that are similar to themselves. Clustering models with a high
Silhouette Coefficient are said to be dense, where samples in the same
cluster are similar to each other, and well separated, where samples in
different clusters are not very similar to each other.
The Silhouette Coefficient is calculated using the mean intra-cluster
distance (``a``) and the mean nearest-cluster distance (``b``) for each
sample.  The Silhouette Coefficient for a sample is ``(b - a) / max(a,
b)``.
Note that Silhouette Coefficient is only defined if number of labels
is 2 ``<= n_labels <= n_samples - 1``.
This function returns the Silhouette Coefficient for each sample.
The best value is 1 and the worst value is -1. Values near 0 indicate
overlapping clusters.
Read more in the :ref:`User Guide <silhouette_coefficient>`.
Parameters
----------
X : {array-like, sparse matrix} of shape (n_samples_a, n_samples_a) if metric == \
        "precomputed" or (n_samples_a, n_features) otherwise
    An array of pairwise distances between samples, or a feature array. If
    a sparse matrix is provided, CSR format should be favoured avoiding
    an additional copy.
labels : array-like of shape (n_samples,)
    Label values for each sample.
metric : str or callable, default='euclidean'
    The metric to use when calculating distance between instances in a
    feature array. If metric is a string, it must be one of the options
    allowed by :func:`~sklearn.metrics.pairwise_distances`.
    If ``X`` is the distance array itself, use "precomputed" as the metric.
    Precomputed distance matrices must have 0 along the diagonal.
**kwds : optional keyword parameters
    Any further parameters are passed directly to the distance function.
    If using a ``scipy.spatial.distance`` metric, the parameters are still
    metric dependent. See the scipy docs for usage examples.
Returns
-------
silhouette : array-like of shape (n_samples,)
    Silhouette Coefficients for each sample.
References
----------
.. [1] `Peter J. Rousseeuw (1987). "Silhouettes: a Graphical Aid to the
   Interpretation and Validation of Cluster Analysis". Computational
   and Applied Mathematics 20: 53-65.
   <https://www.sciencedirect.com/science/article/pii/0377042787901257>`_
.. [2] `Wikipedia entry on the Silhouette Coefficient
   <https://en.wikipedia.org/wiki/Silhouette_(clustering)>`_
Examples
--------
>>> from sklearn.metrics import silhouette_samples
>>> from sklearn.datasets import make_blobs
>>> from sklearn.cluster import KMeans
>>> X, y = make_blobs(n_samples=50, random_state=42)
>>> kmeans = KMeans(n_clusters=3, random_state=42)
>>> labels = kmeans.fit_predict(X)
>>> silhouette_samples(X, labels)
array([...])
Definition at line 203 of file _unsupervised.py.
References check_number_of_labels().
Referenced by silhouette_score().
silhouette_score()
sklearn.metrics.cluster._unsupervised.silhouette_score (X, labels, * , metric = "euclidean", sample_size = None, random_state = None, ** kwds)
Compute the mean Silhouette Coefficient of all samples.
The Silhouette Coefficient is calculated using the mean intra-cluster
distance (``a``) and the mean nearest-cluster distance (``b``) for each
sample.  The Silhouette Coefficient for a sample is ``(b - a) / max(a,
b)``.  To clarify, ``b`` is the distance between a sample and the nearest
cluster that the sample is not a part of.
Note that Silhouette Coefficient is only defined if number of labels
is ``2 <= n_labels <= n_samples - 1``.
This function returns the mean Silhouette Coefficient over all samples.
To obtain the values for each sample, use :func:`silhouette_samples`.
The best value is 1 and the worst value is -1. Values near 0 indicate
overlapping clusters. Negative values generally indicate that a sample has
been assigned to the wrong cluster, as a different cluster is more similar.
Read more in the :ref:`User Guide <silhouette_coefficient>`.
Parameters
----------
X : {array-like, sparse matrix} of shape (n_samples_a, n_samples_a) if metric == \
        "precomputed" or (n_samples_a, n_features) otherwise
    An array of pairwise distances between samples, or a feature array.
labels : array-like of shape (n_samples,)
    Predicted labels for each sample.
metric : str or callable, default='euclidean'
    The metric to use when calculating distance between instances in a
    feature array. If metric is a string, it must be one of the options
    allowed by :func:`~sklearn.metrics.pairwise_distances`. If ``X`` is
    the distance array itself, use ``metric="precomputed"``.
sample_size : int, default=None
    The size of the sample to use when computing the Silhouette Coefficient
    on a random subset of the data.
    If ``sample_size is None``, no sampling is used.
random_state : int, RandomState instance or None, default=None
    Determines random number generation for selecting a subset of samples.
    Used when ``sample_size is not None``.
    Pass an int for reproducible results across multiple function calls.
    See :term:`Glossary <random_state>`.
**kwds : optional keyword parameters
    Any further parameters are passed directly to the distance function.
    If using a scipy.spatial.distance metric, the parameters are still
    metric dependent. See the scipy docs for usage examples.
Returns
-------
silhouette : float
    Mean Silhouette Coefficient for all samples.
References
----------
.. [1] `Peter J. Rousseeuw (1987). "Silhouettes: a Graphical Aid to the
   Interpretation and Validation of Cluster Analysis". Computational
   and Applied Mathematics 20: 53-65.
   <https://www.sciencedirect.com/science/article/pii/0377042787901257>`_
.. [2] `Wikipedia entry on the Silhouette Coefficient
       <https://en.wikipedia.org/wiki/Silhouette_(clustering)>`_
Examples
--------
>>> from sklearn.datasets import make_blobs
>>> from sklearn.cluster import KMeans
>>> from sklearn.metrics import silhouette_score
>>> X, y = make_blobs(random_state=42)
>>> kmeans = KMeans(n_clusters=2, random_state=42)
>>> silhouette_score(X, kmeans.fit_predict(X))
0.49...
Definition at line 51 of file _unsupervised.py.
References silhouette_samples().