Code Cloning Analysis: scipy.sparse.linalg.tests.test_expm_multiply Namespace Reference
scipy.sparse.linalg.tests.test_expm_multiply Namespace Reference
Classes
class TestExpmActionInterval
class TestExpmActionSimple
Functions
estimated (func)
less_than_or_close (a, b)
test_expm_multiply_dtype (dtype_a, dtype_b, b_is_matrix)
Variables
dict IMPRECISE = {np.single, np.csingle}
dict REAL_DTYPES
dict COMPLEX_DTYPES = {np.csingle, np.cdouble, np.clongdouble}
DTYPES = tuple(sorted(REAL_DTYPES ^ COMPLEX_DTYPES, key=str))
Detailed Description
Test functions for the sparse.linalg._expm_multiply module.
Function Documentation
estimated()
scipy.sparse.linalg.tests.test_expm_multiply.estimated (func)
If trace is estimated, it should warn.
We warn that estimation of trace might impact performance.
All result have to be correct nevertheless!
Definition at line 26 of file test_expm_multiply.py.
Referenced by test_expm_multiply_dtype().
less_than_or_close()
scipy.sparse.linalg.tests.test_expm_multiply.less_than_or_close (a, b)
Definition at line 40 of file test_expm_multiply.py.
test_expm_multiply_dtype()
scipy.sparse.linalg.tests.test_expm_multiply.test_expm_multiply_dtype (dtype_a, dtype_b, b_is_matrix)
Make sure `expm_multiply` handles all numerical dtypes correctly.
Definition at line 309 of file test_expm_multiply.py.
References scipy.sparse.linalg._interface.aslinearoperator(), estimated(), and scipy.sparse.linalg._expm_multiply.expm_multiply().
Variable Documentation
COMPLEX_DTYPES
dict scipy.sparse.linalg.tests.test_expm_multiply.COMPLEX_DTYPES = {np.csingle, np.cdouble, np.clongdouble}
Definition at line 21 of file test_expm_multiply.py.
DTYPES
scipy.sparse.linalg.tests.test_expm_multiply.DTYPES = tuple(sorted(REAL_DTYPES ^ COMPLEX_DTYPES, key=str))
Definition at line 23 of file test_expm_multiply.py.
IMPRECISE
dict scipy.sparse.linalg.tests.test_expm_multiply.IMPRECISE = {np.single, np.csingle}
Definition at line 18 of file test_expm_multiply.py.
REAL_DTYPES
dict scipy.sparse.linalg.tests.test_expm_multiply.REAL_DTYPES
Initial value:
=  {np.intc, np.int_, np.longlong,
               np.single, np.double, np.longdouble}
Definition at line 19 of file test_expm_multiply.py.