Code Cloning Analysis: pip._vendor.urllib3.contrib.appengine.AppEngineManager Class Reference
pip._vendor.urllib3.contrib.appengine.AppEngineManager Class Reference
Public Member Functions
__init__ (self, headers=None, retries=None, validate_certificate=True, urlfetch_retries=True)
__enter__ (self)
__exit__ (self, exc_type, exc_val, exc_tb)
urlopen (self, method, url, body=None, headers=None, retries=None, redirect=True, timeout=Timeout.DEFAULT_TIMEOUT, **response_kw)
Public Member Functions inherited from pip._vendor.urllib3.request.RequestMethods
__init__ (self, headers=None)
request (self, method, url, fields=None, headers=None, **urlopen_kw)
request_encode_url (self, method, url, fields=None, headers=None, **urlopen_kw)
request_encode_body (self, method, url, fields=None, headers=None, encode_multipart=True, multipart_boundary=None, **urlopen_kw)
Public Attributes
validate_certificate = validate_certificate
urlfetch_retries = urlfetch_retries
retries = retries or Retry.DEFAULT
Public Attributes inherited from pip._vendor.urllib3.request.RequestMethods
headers = headers or {}
Protected Member Functions
_urlfetch_response_to_http_response (self, urlfetch_resp, **response_kw)
_get_absolute_timeout (self, timeout)
_get_retries (self, retries, redirect)
Additional Inherited Members
Static Protected Attributes inherited from pip._vendor.urllib3.request.RequestMethods
dict _encode_url_methods = {"DELETE", "GET", "HEAD", "OPTIONS"}
Detailed Description
Connection manager for Google App Engine sandbox applications.
This manager uses the URLFetch service directly instead of using the
emulated httplib, and is subject to URLFetch limitations as described in
the App Engine documentation `here
<https://cloud.google.com/appengine/docs/python/urlfetch>`_.
Notably it will raise an :class:`AppEnginePlatformError` if:
    * URLFetch is not available.
    * If you attempt to use this on App Engine Flexible, as full socket
      support is available.
    * If a request size is more than 10 megabytes.
    * If a response size is more than 32 megabytes.
    * If you use an unsupported request method such as OPTIONS.
Beyond those cases, it will raise normal urllib3 errors.
Definition at line 79 of file appengine.py.
Constructor & Destructor Documentation
__init__()
pip._vendor.urllib3.contrib.appengine.AppEngineManager.__init__ (self, headers = None, retries = None, validate_certificate = True, urlfetch_retries = True)
Definition at line 99 of file appengine.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
__enter__()
pip._vendor.urllib3.contrib.appengine.AppEngineManager.__enter__ (self)
Definition at line 124 of file appengine.py.
__exit__()
pip._vendor.urllib3.contrib.appengine.AppEngineManager.__exit__ (self, exc_type, exc_val, exc_tb)
Definition at line 127 of file appengine.py.
_get_absolute_timeout()
pip._vendor.urllib3.contrib.appengine.AppEngineManager._get_absolute_timeout (self, timeout) protected
Definition at line 281 of file appengine.py.
_get_retries()
pip._vendor.urllib3.contrib.appengine.AppEngineManager._get_retries (self, retries, redirect) protected
Definition at line 294 of file appengine.py.
_urlfetch_response_to_http_response()
pip._vendor.urllib3.contrib.appengine.AppEngineManager._urlfetch_response_to_http_response (self, urlfetch_resp, ** response_kw) protected
Definition at line 245 of file appengine.py.
urlopen()
pip._vendor.urllib3.contrib.appengine.AppEngineManager.urlopen (self, method, url, body = None, headers = None, retries = None, redirect = True, timeout = Timeout.DEFAULT_TIMEOUT, ** response_kw)
Reimplemented from pip._vendor.urllib3.request.RequestMethods.
Definition at line 131 of file appengine.py.
Referenced by pip._vendor.urllib3.request.RequestMethods.request_encode_body(), pip._vendor.urllib3.request.RequestMethods.request_encode_url(), and pip._vendor.urllib3.poolmanager.PoolManager.urlopen().
Member Data Documentation
retries
pip._vendor.urllib3.contrib.appengine.AppEngineManager.retries = retries or Retry.DEFAULT
Definition at line 122 of file appengine.py.
Referenced by pip._vendor.urllib3.response.HTTPResponse.geturl().
urlfetch_retries
pip._vendor.urllib3.contrib.appengine.AppEngineManager.urlfetch_retries = urlfetch_retries
Definition at line 120 of file appengine.py.
validate_certificate
pip._vendor.urllib3.contrib.appengine.AppEngineManager.validate_certificate = validate_certificate
Definition at line 119 of file appengine.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pip/_vendor/urllib3/contrib/appengine.py