Code Cloning Analysis: matplotlib.image Namespace Reference
matplotlib.image Namespace Reference
Classes
class _ImageBase
class AxesImage
class BboxImage
class FigureImage
class NonUniformImage
class PcolorImage
Functions
composite_images (images, renderer, magnification=1.0)
_draw_list_compositing_images (renderer, parent, artists, suppress_composite=None)
_resample (image_obj, data, out_shape, transform, *, resample=None, alpha=1)
_rgb_to_rgba (A)
imread (fname, format=None)
imsave (fname, arr, vmin=None, vmax=None, cmap=None, format=None, origin=None, dpi=100, *, metadata=None, pil_kwargs=None)
pil_to_array (pilImage)
_pil_png_to_float_array (pil_png)
thumbnail (infile, thumbfile, scale=0.1, interpolation='bilinear', preview=False)
Variables
_log = logging.getLogger(__name__)
dict _interpd_
interpolations_names = set(_interpd_)
Detailed Description
The image module supports basic image loading, rescaling and display
operations.
Function Documentation
_draw_list_compositing_images()
matplotlib.image._draw_list_compositing_images (renderer, parent, artists, suppress_composite = None) protected
Draw a sorted list of artists, compositing images into a single
image where possible.
For internal Matplotlib use only: It is here to reduce duplication
between `Figure.draw` and `Axes.draw`, but otherwise should not be
generally useful.
Definition at line 116 of file image.py.
References composite_images().
_pil_png_to_float_array()
matplotlib.image._pil_png_to_float_array (pil_png) protected
Convert a PIL `PNGImageFile` to a 0-1 float array.
Definition at line 1695 of file image.py.
Referenced by imread().
_resample()
matplotlib.image._resample (image_obj, data, out_shape, transform, * , resample = None, alpha = 1) protected
Convenience wrapper around `._image.resample` to resample *data* to
*out_shape* (with a third dimension if *data* is RGBA) that takes care of
allocating the output array and fetching the relevant properties from the
Image object *image_obj*.
Definition at line 163 of file image.py.
_rgb_to_rgba()
matplotlib.image._rgb_to_rgba (A) protected
Convert an RGB image to RGBA, as required by the image resample C++
extension.
Definition at line 219 of file image.py.
Referenced by matplotlib.image._ImageBase._make_image().
composite_images()
matplotlib.image.composite_images (images, renderer, magnification = 1.0)
Composite a number of RGBA images into one.  The images are
composited in the order in which they appear in the *images* list.
Parameters
----------
images : list of Images
    Each must have a `make_image` method.  For each image,
    `can_composite` should return `True`, though this is not
    enforced by this function.  Each image must have a purely
    affine transformation with no shear.
renderer : `.RendererBase`
magnification : float, default: 1
    The additional magnification to apply for the renderer in use.
Returns
-------
image : (M, N, 4) `numpy.uint8` array
    The composited RGBA image.
offset_x, offset_y : float
    The (left, bottom) offset where the composited image should be placed
    in the output figure.
Definition at line 60 of file image.py.
Referenced by _draw_list_compositing_images().
imread()
matplotlib.image.imread (fname, format = None)
Read an image from a file into an array.
.. note::
    This function exists for historical reasons.  It is recommended to
    use `PIL.Image.open` instead for loading images.
Parameters
----------
fname : str or file-like
    The image file to read: a filename, a URL or a file-like object opened
    in read-binary mode.
    Passing a URL is deprecated.  Please open the URL
    for reading and pass the result to Pillow, e.g. with
    ``np.array(PIL.Image.open(urllib.request.urlopen(url)))``.
format : str, optional
    The image file format assumed for reading the data.  The image is
    loaded as a PNG file if *format* is set to "png", if *fname* is a path
    or opened file with a ".png" extension, or if it is a URL.  In all
    other cases, *format* is ignored and the format is auto-detected by
    `PIL.Image.open`.
Returns
-------
`numpy.array`
    The image data. The returned array has shape
    - (M, N) for grayscale images.
    - (M, N, 3) for RGB images.
    - (M, N, 4) for RGBA images.
    PNG images are returned as float arrays (0-1).  All other formats are
    returned as int arrays, with a bit depth determined by the file's
    contents.
Definition at line 1448 of file image.py.
References _pil_png_to_float_array(), and pil_to_array().
Referenced by matplotlib.pyplot.set_cmap(), and thumbnail().
imsave()
matplotlib.image.imsave (fname, arr, vmin = None, vmax = None, cmap = None, format = None, origin = None, dpi = 100, * , metadata = None, pil_kwargs = None)
Colormap and save an array as an image file.
RGB(A) images are passed through.  Single channel images will be
colormapped according to *cmap* and *norm*.
.. note::
   If you want to save a single channel image as gray scale please use an
   image I/O library (such as pillow, tifffile, or imageio) directly.
Parameters
----------
fname : str or path-like or file-like
    A path or a file-like object to store the image in.
    If *format* is not set, then the output format is inferred from the
    extension of *fname*, if any, and from :rc:`savefig.format` otherwise.
    If *format* is set, it determines the output format.
arr : array-like
    The image data. Accepts NumPy arrays or sequences
    (e.g., lists or tuples). The shape can be one of
    MxN (luminance), MxNx3 (RGB) or MxNx4 (RGBA).
vmin, vmax : float, optional
    *vmin* and *vmax* set the color scaling for the image by fixing the
    values that map to the colormap color limits. If either *vmin*
    or *vmax* is None, that limit is determined from the *arr*
    min/max value.
cmap : str or `~matplotlib.colors.Colormap`, default: :rc:`image.cmap`
    A Colormap instance or registered colormap name. The colormap
    maps scalar data to colors. It is ignored for RGB(A) data.
format : str, optional
    The file format, e.g. 'png', 'pdf', 'svg', ...  The behavior when this
    is unset is documented under *fname*.
origin : {'upper', 'lower'}, default: :rc:`image.origin`
    Indicates whether the ``(0, 0)`` index of the array is in the upper
    left or lower left corner of the Axes.
dpi : float
    The DPI to store in the metadata of the file.  This does not affect the
    resolution of the output image.  Depending on file format, this may be
    rounded to the nearest integer.
metadata : dict, optional
    Metadata in the image file.  The supported keys depend on the output
    format, see the documentation of the respective backends for more
    information.
    Currently only supported for "png", "pdf", "ps", "eps", and "svg".
pil_kwargs : dict, optional
    Keyword arguments passed to `PIL.Image.Image.save`.  If the 'pnginfo'
    key is present, it completely overrides *metadata*, including the
    default 'Software' key.
Definition at line 1526 of file image.py.
References PIL.Image.frombuffer(), and PIL.Image.new().
Referenced by matplotlib.pyplot.set_cmap().
pil_to_array()
matplotlib.image.pil_to_array (pilImage)
Load a `PIL image`_ and return it as a numpy int array.
.. _PIL image: https://pillow.readthedocs.io/en/latest/reference/Image.html
Returns
-------
numpy.array
    The array shape depends on the image type:
    - (M, N) for grayscale images.
    - (M, N, 3) for RGB images.
    - (M, N, 4) for RGBA images.
Definition at line 1660 of file image.py.
Referenced by imread(), and matplotlib.image._ImageBase.set_data().
thumbnail()
matplotlib.image.thumbnail (infile, thumbfile, scale = 0.1, interpolation = 'bilinear', preview = False)
Make a thumbnail of image in *infile* with output filename *thumbfile*.
See :doc:`/gallery/misc/image_thumbnail_sgskip`.
Parameters
----------
infile : str or file-like
    The image file. Matplotlib relies on Pillow_ for image reading, and
    thus supports a wide range of file formats, including PNG, JPG, TIFF
    and others.
    .. _Pillow: https://python-pillow.github.io
thumbfile : str or file-like
    The thumbnail filename.
scale : float, default: 0.1
    The scale factor for the thumbnail.
interpolation : str, default: 'bilinear'
    The interpolation scheme used in the resampling. See the
    *interpolation* parameter of `~.Axes.imshow` for possible values.
preview : bool, default: False
    If True, the default backend (presumably a user interface
    backend) will be used which will cause a figure to be raised if
    `~matplotlib.pyplot.show` is called.  If it is False, the figure is
    created using `.FigureCanvasBase` and the drawing backend is selected
    as `.Figure.savefig` would normally do.
Returns
-------
`.Figure`
    The figure instance containing the thumbnail.
Definition at line 1725 of file image.py.
References imread().
Variable Documentation
_interpd_
dict matplotlib.image._interpd_ protected
Initial value:
=  {
    'auto': _image.NEAREST,  # this will use nearest or Hanning...
    'none': _image.NEAREST,  # fall back to nearest when not supported
    'nearest': _image.NEAREST,
    'bilinear': _image.BILINEAR,
    'bicubic': _image.BICUBIC,
    'spline16': _image.SPLINE16,
    'spline36': _image.SPLINE36,
    'hanning': _image.HANNING,
    'hamming': _image.HAMMING,
    'hermite': _image.HERMITE,
    'kaiser': _image.KAISER,
    'quadric': _image.QUADRIC,
    'catrom': _image.CATROM,
    'gaussian': _image.GAUSSIAN,
    'bessel': _image.BESSEL,
    'mitchell': _image.MITCHELL,
    'sinc': _image.SINC,
    'lanczos': _image.LANCZOS,
    'blackman': _image.BLACKMAN,
    'antialiased': _image.NEAREST,  # this will use nearest or Hanning...
}
Definition at line 34 of file image.py.
_log
matplotlib.image._log = logging.getLogger(__name__) protected
Definition at line 31 of file image.py.
interpolations_names
matplotlib.image.interpolations_names = set(_interpd_)
Definition at line 57 of file image.py.