Code Cloning Analysis: sklearn.preprocessing.tests.test_target_encoder Namespace Reference
sklearn.preprocessing.tests.test_target_encoder Namespace Reference
Functions
_encode_target (X_ordinal, y_numeric, n_categories, smooth)
test_encoding (categories, unknown_value, global_random_seed, smooth, target_type)
test_encoding_multiclass (global_random_seed, categories, unknown_values, target_labels, smooth)
test_custom_categories (X, categories, smooth)
test_errors (y, msg)
test_use_regression_target ()
test_feature_names_out_set_output (y, feature_names)
test_multiple_features_quick (to_pandas, smooth, target_type)
test_constant_target_and_feature (y, y_mean, smooth)
test_fit_transform_not_associated_with_y_if_ordinal_categorical_is_not (global_random_seed)
test_smooth_zero ()
test_invariance_of_encoding_under_label_permutation (smooth, global_random_seed)
test_target_encoding_for_linear_regression (smooth, global_random_seed)
test_pandas_copy_on_write ()
Function Documentation
_encode_target()
sklearn.preprocessing.tests.test_target_encoder._encode_target (X_ordinal, y_numeric, n_categories, smooth) protected
Simple Python implementation of target encoding.
Definition at line 25 of file test_target_encoder.py.
Referenced by test_encoding(), test_encoding_multiclass(), and test_multiple_features_quick().
test_constant_target_and_feature()
sklearn.preprocessing.tests.test_target_encoder.test_constant_target_and_feature (y, y_mean, smooth)
Check edge case where feature and target is constant.
Definition at line 474 of file test_target_encoder.py.
test_custom_categories()
sklearn.preprocessing.tests.test_target_encoder.test_custom_categories (X, categories, smooth)
Custom categories with unknown categories that are not in training data.
Definition at line 293 of file test_target_encoder.py.
test_encoding()
sklearn.preprocessing.tests.test_target_encoder.test_encoding (categories, unknown_value, global_random_seed, smooth, target_type)
Check encoding for binary and continuous targets.
Compare the values returned by `TargetEncoder.fit_transform` against the
expected encodings for cv splits from a naive reference Python
implementation in _encode_target.
Definition at line 66 of file test_target_encoder.py.
References _encode_target().
test_encoding_multiclass()
sklearn.preprocessing.tests.test_target_encoder.test_encoding_multiclass (global_random_seed, categories, unknown_values, target_labels, smooth)
Check encoding for multiclass targets.
Definition at line 173 of file test_target_encoder.py.
References _encode_target().
test_errors()
sklearn.preprocessing.tests.test_target_encoder.test_errors (y, msg)
Check invalidate input.
Definition at line 319 of file test_target_encoder.py.
test_feature_names_out_set_output()
sklearn.preprocessing.tests.test_target_encoder.test_feature_names_out_set_output (y, feature_names)
Check TargetEncoder works with set_output.
Definition at line 360 of file test_target_encoder.py.
test_fit_transform_not_associated_with_y_if_ordinal_categorical_is_not()
sklearn.preprocessing.tests.test_target_encoder.test_fit_transform_not_associated_with_y_if_ordinal_categorical_is_not (global_random_seed)
Definition at line 490 of file test_target_encoder.py.
test_invariance_of_encoding_under_label_permutation()
sklearn.preprocessing.tests.test_target_encoder.test_invariance_of_encoding_under_label_permutation (smooth, global_random_seed)
Definition at line 554 of file test_target_encoder.py.
test_multiple_features_quick()
sklearn.preprocessing.tests.test_target_encoder.test_multiple_features_quick (to_pandas, smooth, target_type)
Check target encoder with multiple features.
Definition at line 382 of file test_target_encoder.py.
References _encode_target().
test_pandas_copy_on_write()
sklearn.preprocessing.tests.test_target_encoder.test_pandas_copy_on_write ()
Test target-encoder cython code when y is read-only.
The numpy array underlying df["y"] is read-only when copy-on-write is enabled.
Non-regression test for gh-27879.
Definition at line 704 of file test_target_encoder.py.
test_smooth_zero()
sklearn.preprocessing.tests.test_target_encoder.test_smooth_zero ()
Check edge case with zero smoothing and cv does not contain category.
Definition at line 536 of file test_target_encoder.py.
test_target_encoding_for_linear_regression()
sklearn.preprocessing.tests.test_target_encoder.test_target_encoding_for_linear_regression (smooth, global_random_seed)
Definition at line 590 of file test_target_encoder.py.
test_use_regression_target()
sklearn.preprocessing.tests.test_target_encoder.test_use_regression_target ()
Check inferred and specified `target_type` on regression target.
Definition at line 328 of file test_target_encoder.py.