Code Cloning Analysis: scipy.optimize.tests.test_minimize_constrained.Elec Class Reference
scipy.optimize.tests.test_minimize_constrained.Elec Class Reference
Public Member Functions
__init__ (self, n_electrons=200, random_state=0, constr_jac=None, constr_hess=None)
fun (self, x)
grad (self, x)
hess (self, x)
constr (self)
Public Attributes
n_electrons = n_electrons
rng = np.random.RandomState(random_state)
x0 = np.hstack((x, y, z))
x_opt = None
constr_jac = constr_jac
constr_hess = constr_hess
bounds = None
Protected Member Functions
_get_cordinates (self, x)
_compute_coordinate_deltas (self, x)
Detailed Description
Distribution of electrons on a sphere.
Problem no 2 from COPS collection [2]_. Find
the equilibrium state distribution (of minimal
potential) of the electrons positioned on a
conducting sphere.
References
----------
.. [1] E. D. Dolan, J. J. Mor\'{e}, and T. S. Munson,
       "Benchmarking optimization software with COPS 3.0.",
        Argonne National Lab., Argonne, IL (US), 2004.
Definition at line 319 of file test_minimize_constrained.py.
Constructor & Destructor Documentation
__init__()
scipy.optimize.tests.test_minimize_constrained.Elec.__init__ (self, n_electrons = 200, random_state = 0, constr_jac = None, constr_hess = None)
Definition at line 333 of file test_minimize_constrained.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
_compute_coordinate_deltas()
scipy.optimize.tests.test_minimize_constrained.Elec._compute_coordinate_deltas (self, x) protected
Definition at line 355 of file test_minimize_constrained.py.
_get_cordinates()
scipy.optimize.tests.test_minimize_constrained.Elec._get_cordinates (self, x) protected
Definition at line 349 of file test_minimize_constrained.py.
constr()
scipy.optimize.tests.test_minimize_constrained.Elec.constr (self)
Definition at line 421 of file test_minimize_constrained.py.
fun()
scipy.optimize.tests.test_minimize_constrained.Elec.fun (self, x)
Definition at line 362 of file test_minimize_constrained.py.
grad()
scipy.optimize.tests.test_minimize_constrained.Elec.grad (self, x)
Definition at line 369 of file test_minimize_constrained.py.
hess()
scipy.optimize.tests.test_minimize_constrained.Elec.hess (self, x)
Definition at line 382 of file test_minimize_constrained.py.
Member Data Documentation
bounds
scipy.optimize.tests.test_minimize_constrained.Elec.bounds = None
Definition at line 347 of file test_minimize_constrained.py.
Referenced by sklearn.gaussian_process.kernels.Kernel._check_bounds_params(), and matplotlib.transforms.BboxBase.anchored().
constr_hess
scipy.optimize.tests.test_minimize_constrained.Elec.constr_hess = constr_hess
Definition at line 346 of file test_minimize_constrained.py.
constr_jac
scipy.optimize.tests.test_minimize_constrained.Elec.constr_jac = constr_jac
Definition at line 345 of file test_minimize_constrained.py.
n_electrons
scipy.optimize.tests.test_minimize_constrained.Elec.n_electrons = n_electrons
Definition at line 335 of file test_minimize_constrained.py.
rng
scipy.optimize.tests.test_minimize_constrained.Elec.rng = np.random.RandomState(random_state)
Definition at line 336 of file test_minimize_constrained.py.
Referenced by scipy.stats._qmc.PoissonDisk._hypersphere_surface_sample(), scipy.stats._qmc.PoissonDisk._hypersphere_volume_sample(), scipy.stats._qmc.Halton._initialize_permutations(), scipy.stats._qmc.PoissonDisk._random(), scipy.stats._qmc.LatinHypercube._random_lhs(), scipy.stats._qmc.LatinHypercube._random_oa_lhs(), scipy.stats._qmc.Sobol._scramble(), sklearn.gaussian_process._gpc._BinaryGaussianProcessClassifierLaplace.fit(), and scipy.stats._qmc.QMCEngine.reset().
x0
scipy.optimize.tests.test_minimize_constrained.Elec.x0 = np.hstack((x, y, z))
Definition at line 343 of file test_minimize_constrained.py.
x_opt
scipy.optimize.tests.test_minimize_constrained.Elec.x_opt = None
Definition at line 344 of file test_minimize_constrained.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/optimize/tests/test_minimize_constrained.py