Code Cloning Analysis: fontTools.designspaceLib Namespace Reference
fontTools.designspaceLib Namespace Reference
Namespaces
namespace split
namespace statNames
Classes
class AbstractAxisDescriptor
class AsDictMixin
class AxisDescriptor
class AxisLabelDescriptor
class AxisMappingDescriptor
class BaseDocReader
class BaseDocWriter
class DesignSpaceDocument
class DesignSpaceDocumentError
class DiscreteAxisDescriptor
class InstanceDescriptor
class LocationLabelDescriptor
class RangeAxisSubsetDescriptor
class RuleDescriptor
class SimpleDescriptor
class SourceDescriptor
class ValueAxisSubsetDescriptor
class VariableFontDescriptor
Functions
posix (path)
posixpath_property (private_name)
evaluateRule (rule, location)
evaluateConditions (conditions, location)
processRules (rules, location, glyphNames)
tagForAxisName (name)
main (args=None)
Variables
list __all__
str XML_NS = "{http://www.w3.org/XML/1998/namespace}"
str XML_LANG = XML_NS + "lang"
AnisotropicLocationDict = Dict[str, Union[float, Tuple[float, float]]]
SimpleLocationDict = Dict[str, float]
Detailed Description
    designSpaceDocument
    - Read and write designspace files
Function Documentation
evaluateConditions()
fontTools.designspaceLib.evaluateConditions (conditions, location)
Return True if all the conditions matches the given location.
- If a condition has no minimum, check for < maximum.
- If a condition has no maximum, check for > minimum.
Definition at line 405 of file __init__.py.
Referenced by evaluateRule().
evaluateRule()
fontTools.designspaceLib.evaluateRule (rule, location)
Return True if any of the rule's conditionsets matches the given location.
Definition at line 400 of file __init__.py.
References evaluateConditions().
Referenced by processRules().
main()
fontTools.designspaceLib.main (args = None)
Roundtrip .designspace file through the DesignSpaceDocument class
Definition at line 3321 of file __init__.py.
posix()
fontTools.designspaceLib.posix (path)
Normalize paths using forward slash to work also on Windows.
Definition at line 49 of file __init__.py.
Referenced by posixpath_property(), and fontTools.designspaceLib.DesignSpaceDocument.write().
posixpath_property()
fontTools.designspaceLib.posixpath_property (private_name)
Generate a propery that holds a path always using forward slashes.
Definition at line 61 of file __init__.py.
References posix().
processRules()
fontTools.designspaceLib.processRules (rules, location, glyphNames)
Apply these rules at this location to these glyphnames.
Return a new list of glyphNames with substitutions applied.
- rule order matters
Definition at line 424 of file __init__.py.
References evaluateRule().
tagForAxisName()
fontTools.designspaceLib.tagForAxisName (name)
Definition at line 862 of file __init__.py.
Variable Documentation
__all__
list fontTools.designspaceLib.__all__ private
Initial value:
=  [
    "AxisDescriptor",
    "AxisLabelDescriptor",
    "AxisMappingDescriptor",
    "BaseDocReader",
    "BaseDocWriter",
    "DesignSpaceDocument",
    "DesignSpaceDocumentError",
    "DiscreteAxisDescriptor",
    "InstanceDescriptor",
    "LocationLabelDescriptor",
    "RangeAxisSubsetDescriptor",
    "RuleDescriptor",
    "SourceDescriptor",
    "ValueAxisSubsetDescriptor",
    "VariableFontDescriptor",
]
Definition at line 25 of file __init__.py.
AnisotropicLocationDict
fontTools.designspaceLib.AnisotropicLocationDict = Dict[str, Union[float, Tuple[float, float]]]
Definition at line 449 of file __init__.py.
SimpleLocationDict
fontTools.designspaceLib.DesignSpaceDocument.SimpleLocationDict = Dict[str, float]
Definition at line 450 of file __init__.py.
XML_LANG
str fontTools.designspaceLib.XML_LANG = XML_NS + "lang"
Definition at line 46 of file __init__.py.
XML_NS
str fontTools.designspaceLib.XML_NS = "{http://www.w3.org/XML/1998/namespace}"
Definition at line 45 of file __init__.py.