Code Cloning Analysis: scipy.sparse.linalg._eigen.lobpcg.tests.test_lobpcg Namespace Reference
scipy.sparse.linalg._eigen.lobpcg.tests.test_lobpcg Namespace Reference
Functions
sign_align (A, B)
ElasticRod (n)
MikotaPair (n)
compare_solutions (A, B, m)
test_Small ()
test_ElasticRod ()
test_MikotaPair ()
test_b_orthonormalize (n, m, Vdtype, Bdtype, BVdtype)
test_nonhermitian_warning (capsys)
test_regression ()
test_diagonal (n, m, m_excluded)
_check_eigen (M, w, V, rtol=1e-8, atol=1e-14)
_check_fiedler (n, p)
test_fiedler_small_8 ()
test_fiedler_large_12 ()
test_failure_to_run_iterations ()
test_failure_to_run_iterations_nonsymmetric ()
test_hermitian ()
test_eigs_consistency (n, atol)
test_verbosity ()
test_tolerance_float32 ()
test_dtypes (vdtype, mdtype, arr_type)
test_inplace_warning ()
test_maxit ()
test_diagonal_data_types (n, m)
Variables
tuple _IS_32BIT = (sys.maxsize < 2**32)
dict INT_DTYPES = {np.intc, np.int_, np.longlong, np.uintc, np.uint, np.ulonglong}
dict REAL_DTYPES = {np.single, np.double, np.longdouble}
dict COMPLEX_DTYPES = {np.csingle, np.cdouble, np.clongdouble}
VDTYPES = tuple(sorted(REAL_DTYPES ^ COMPLEX_DTYPES, key=str))
MDTYPES = tuple(sorted(INT_DTYPES ^ REAL_DTYPES ^ COMPLEX_DTYPES, key=str))
Detailed Description
 Test functions for the sparse.linalg._eigen.lobpcg module
Function Documentation
_check_eigen()
scipy.sparse.linalg._eigen.lobpcg.tests.test_lobpcg._check_eigen (M, w, V, rtol = 1e-8, atol = 1e-14) protected
Check if the eigenvalue residual is small.
Definition at line 263 of file test_lobpcg.py.
Referenced by _check_fiedler(), test_diagonal(), and test_eigs_consistency().
_check_fiedler()
scipy.sparse.linalg._eigen.lobpcg.tests.test_lobpcg._check_fiedler (n, p) protected
Check the Fiedler vector computation.
Definition at line 271 of file test_lobpcg.py.
References _check_eigen().
Referenced by test_fiedler_large_12(), and test_fiedler_small_8().
compare_solutions()
scipy.sparse.linalg._eigen.lobpcg.tests.test_lobpcg.compare_solutions (A, B, m)
Check eig vs. lobpcg consistency.
Definition at line 67 of file test_lobpcg.py.
References compare_solutions(), ElasticRod(), and MikotaPair().
Referenced by compare_solutions().
ElasticRod()
scipy.sparse.linalg._eigen.lobpcg.tests.test_lobpcg.ElasticRod (n)
Build the matrices for the generalized eigenvalue problem of the
fixed-free elastic rod vibration model.
Definition at line 38 of file test_lobpcg.py.
Referenced by compare_solutions().
MikotaPair()
scipy.sparse.linalg._eigen.lobpcg.tests.test_lobpcg.MikotaPair (n)
Build a pair of full diagonal matrices for the generalized eigenvalue
problem. The Mikota pair acts as a nice test since the eigenvalues are the
squares of the integers n, n=1,2,...
Definition at line 54 of file test_lobpcg.py.
Referenced by compare_solutions().
sign_align()
scipy.sparse.linalg._eigen.lobpcg.tests.test_lobpcg.sign_align (A, B)
Align signs of columns of A match those of B: column-wise remove
sign of A by multiplying with its sign then multiply in sign of B.
Definition at line 31 of file test_lobpcg.py.
Referenced by test_b_orthonormalize().
test_b_orthonormalize()
scipy.sparse.linalg._eigen.lobpcg.tests.test_lobpcg.test_b_orthonormalize (n, m, Vdtype, Bdtype, BVdtype)
Test B-orthonormalization by Cholesky with callable 'B'.
The function '_b_orthonormalize' is key in LOBPCG but may
lead to numerical instabilities. The input vectors are often
badly scaled, so the function needs scale-invariant Cholesky;
see https://netlib.org/lapack/lawnspdf/lawn14.pdf.
Definition at line 106 of file test_lobpcg.py.
References scipy.sparse.linalg._eigen.lobpcg.lobpcg._b_orthonormalize(), scipy.sparse._construct.diags(), and sign_align().
test_diagonal()
scipy.sparse.linalg._eigen.lobpcg.tests.test_lobpcg.test_diagonal (n, m, m_excluded)
Test ``m - m_excluded`` eigenvalues and eigenvectors of
diagonal matrices of the size ``n`` varying matrix formats:
dense array, spare matrix, and ``LinearOperator`` for both
matrixes in the generalized eigenvalue problem ``Av = cBv``
and for the preconditioner.
Definition at line 197 of file test_lobpcg.py.
References _check_eigen(), scipy.sparse._construct.diags(), and scipy.sparse._construct.eye().
test_diagonal_data_types()
scipy.sparse.linalg._eigen.lobpcg.tests.test_lobpcg.test_diagonal_data_types (n, m)
Check lobpcg for diagonal matrices for all matrix types.
Constraints are imposed, so a dense eigensolver eig cannot run.
Definition at line 536 of file test_lobpcg.py.
References scipy.sparse._construct.diags().
test_dtypes()
scipy.sparse.linalg._eigen.lobpcg.tests.test_lobpcg.test_dtypes (vdtype, mdtype, arr_type)
Test lobpcg in various dtypes.
Definition at line 461 of file test_lobpcg.py.
test_eigs_consistency()
scipy.sparse.linalg._eigen.lobpcg.tests.test_lobpcg.test_eigs_consistency (n, atol)
Check eigs vs. lobpcg consistency.
Definition at line 411 of file test_lobpcg.py.
References _check_eigen(), scipy.sparse.linalg._eigen.arpack.arpack.eigs(), and scipy.sparse._construct.spdiags().
test_ElasticRod()
scipy.sparse.linalg._eigen.lobpcg.tests.test_lobpcg.test_ElasticRod ()
Definition at line 90 of file test_lobpcg.py.
test_failure_to_run_iterations()
scipy.sparse.linalg._eigen.lobpcg.tests.test_lobpcg.test_failure_to_run_iterations ()
Check that the code exits gracefully without breaking. Issue #10974.
The code may or not issue a warning, filtered out. Issue #15935, #17954.
Definition at line 338 of file test_lobpcg.py.
test_failure_to_run_iterations_nonsymmetric()
scipy.sparse.linalg._eigen.lobpcg.tests.test_lobpcg.test_failure_to_run_iterations_nonsymmetric ()
Check that the code exists gracefully without breaking
if the matrix in not symmetric.
Definition at line 350 of file test_lobpcg.py.
test_fiedler_large_12()
scipy.sparse.linalg._eigen.lobpcg.tests.test_lobpcg.test_fiedler_large_12 ()
Check the dense workaround path avoided for non-small matrices.
Definition at line 328 of file test_lobpcg.py.
References _check_fiedler().
test_fiedler_small_8()
scipy.sparse.linalg._eigen.lobpcg.tests.test_lobpcg.test_fiedler_small_8 ()
Check the dense workaround path for small matrices.
Definition at line 320 of file test_lobpcg.py.
References _check_fiedler().
test_hermitian()
scipy.sparse.linalg._eigen.lobpcg.tests.test_lobpcg.test_hermitian ()
Check complex-value Hermitian cases.
Definition at line 363 of file test_lobpcg.py.
test_inplace_warning()
scipy.sparse.linalg._eigen.lobpcg.tests.test_lobpcg.test_inplace_warning ()
Check lobpcg gives a warning in '_b_orthonormalize'
that in-place orthogonalization is impossible due to dtype mismatch.
Definition at line 478 of file test_lobpcg.py.
References scipy.sparse._construct.diags().
test_maxit()
scipy.sparse.linalg._eigen.lobpcg.tests.test_lobpcg.test_maxit ()
Check lobpcg if maxit=maxiter runs maxiter iterations and
if maxit=None runs 20 iterations (the default)
by checking the size of the iteration history output, which should
be the number of iterations plus 3 (initial, final, and postprocessing)
typically when maxiter is small and the choice of the best is passive.
Definition at line 493 of file test_lobpcg.py.
References scipy.sparse._construct.diags().
test_MikotaPair()
scipy.sparse.linalg._eigen.lobpcg.tests.test_lobpcg.test_MikotaPair ()
Definition at line 96 of file test_lobpcg.py.
test_nonhermitian_warning()
scipy.sparse.linalg._eigen.lobpcg.tests.test_lobpcg.test_nonhermitian_warning (capsys)
Check the warning of a Ritz matrix being not Hermitian
by feeding a non-Hermitian input matrix.
Also check stdout since verbosityLevel=1 and lack of stderr.
Definition at line 163 of file test_lobpcg.py.
test_regression()
scipy.sparse.linalg._eigen.lobpcg.tests.test_lobpcg.test_regression ()
Check the eigenvalue of the identity matrix is one.
Definition at line 184 of file test_lobpcg.py.
test_Small()
scipy.sparse.linalg._eigen.lobpcg.tests.test_lobpcg.test_Small ()
Definition at line 81 of file test_lobpcg.py.
test_tolerance_float32()
scipy.sparse.linalg._eigen.lobpcg.tests.test_lobpcg.test_tolerance_float32 ()
Check lobpcg for attainable tolerance in float32.
Definition at line 441 of file test_lobpcg.py.
References scipy.sparse._construct.diags().
test_verbosity()
scipy.sparse.linalg._eigen.lobpcg.tests.test_lobpcg.test_verbosity ()
Check that nonzero verbosity level code runs.
Definition at line 425 of file test_lobpcg.py.
Variable Documentation
_IS_32BIT
tuple scipy.sparse.linalg._eigen.lobpcg.tests.test_lobpcg._IS_32BIT = (sys.maxsize < 2**32) protected
Definition at line 20 of file test_lobpcg.py.
COMPLEX_DTYPES
dict scipy.sparse.linalg._eigen.lobpcg.tests.test_lobpcg.COMPLEX_DTYPES = {np.csingle, np.cdouble, np.clongdouble}
Definition at line 25 of file test_lobpcg.py.
INT_DTYPES
dict scipy.sparse.linalg._eigen.lobpcg.tests.test_lobpcg.INT_DTYPES = {np.intc, np.int_, np.longlong, np.uintc, np.uint, np.ulonglong}
Definition at line 22 of file test_lobpcg.py.
MDTYPES
scipy.sparse.linalg._eigen.lobpcg.tests.test_lobpcg.MDTYPES = tuple(sorted(INT_DTYPES ^ REAL_DTYPES ^ COMPLEX_DTYPES, key=str))
Definition at line 28 of file test_lobpcg.py.
REAL_DTYPES
dict scipy.sparse.linalg._eigen.lobpcg.tests.test_lobpcg.REAL_DTYPES = {np.single, np.double, np.longdouble}
Definition at line 24 of file test_lobpcg.py.
VDTYPES
scipy.sparse.linalg._eigen.lobpcg.tests.test_lobpcg.VDTYPES = tuple(sorted(REAL_DTYPES ^ COMPLEX_DTYPES, key=str))
Definition at line 27 of file test_lobpcg.py.