Code Cloning Analysis: matplotlib.patches.ArrowStyle.BracketCurve Class Reference
matplotlib.patches.ArrowStyle.BracketCurve Class Reference
Public Member Functions
__init__ (self, widthA=1., lengthA=0.2, angleA=None)
Public Member Functions inherited from matplotlib.patches.ArrowStyle._Curve
__init__ (self, head_length=.4, head_width=.2, widthA=1., widthB=1., lengthA=0.2, lengthB=0.2, angleA=0, angleB=0, scaleA=None, scaleB=None)
transmute (self, path, mutation_size, linewidth)
Public Member Functions inherited from matplotlib.patches.ArrowStyle._Base
__call__ (self, path, mutation_size, linewidth, aspect_ratio=1.)
Additional Inherited Members
Static Public Member Functions inherited from matplotlib.patches.ArrowStyle._Base
ensure_quadratic_bezier (path)
Public Attributes inherited from matplotlib.patches.ArrowStyle._Curve
head_length
head_width = head_length, head_width
widthA
widthB = widthA, widthB
lengthA
lengthB = lengthA, lengthB
angleA
angleB = angleA, angleB
scaleA
scaleB = scaleA, scaleB
bool fillend = True
Static Public Attributes inherited from matplotlib.patches.ArrowStyle._Curve
str arrow = "-"
bool fillbegin = False
Protected Member Functions inherited from matplotlib.patches.ArrowStyle._Curve
_get_arrow_wedge (self, x0, y0, x1, y1, head_dist, cos_t, sin_t, linewidth)
_get_bracket (self, x0, y0, x1, y1, width, length, angle)
Protected Attributes inherited from matplotlib.patches.ArrowStyle._Curve
bool _beginarrow_head = False
bool _beginarrow_bracket = False
bool _endarrow_head = False
bool _endarrow_bracket = False
Detailed Description
An arrow with an outward square bracket at its start and a head at
the end.
Definition at line 3633 of file patches.py.
Constructor & Destructor Documentation
__init__()
matplotlib.patches.ArrowStyle.BracketCurve.__init__ (self, widthA = 1., lengthA = 0.2, angleA = None)
Parameters
----------
widthA : float, default: 1.0
    Width of the bracket.
lengthA : float, default: 0.2
    Length of the bracket.
angleA : float, default: 0 degrees
    Orientation of the bracket, as a counterclockwise angle.
    0 degrees means perpendicular to the line.
Definition at line 3640 of file patches.py.
References __init__().
Referenced by __init__(), sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/patches.py