Code Cloning Analysis: dateutil.tz.tz._tzicalvtz Class Reference
dateutil.tz.tz._tzicalvtz Class Reference
Public Member Functions
__init__ (self, tzid, comps=[])
utcoffset (self, dt)
dst (self, dt)
tzname (self, dt)
__repr__ (self)
Public Member Functions inherited from dateutil.tz._common._tzinfo
is_ambiguous (self, dt)
fromutc (self, dt)
Protected Member Functions
_find_comp (self, dt)
_find_compdt (self, comp, dt)
Protected Member Functions inherited from dateutil.tz._common._tzinfo
_fold_status (self, dt_utc, dt_wall)
_fold (self, dt)
_fromutc (self, dt)
Protected Attributes
_tzid = tzid
_comps = comps
list _cachedate = []
list _cachecomp = []
_cache_lock = _thread.allocate_lock()
Static Private Attributes
__reduce__ = object.__reduce__
Detailed Description
Definition at line 1167 of file tz.py.
Constructor & Destructor Documentation
__init__()
dateutil.tz.tz._tzicalvtz.__init__ (self, tzid, comps = [])
Definition at line 1168 of file tz.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__repr__()
dateutil.tz.tz._tzicalvtz.__repr__ (self)
Definition at line 1247 of file tz.py.
_find_comp()
dateutil.tz.tz._tzicalvtz._find_comp (self, dt) protected
Definition at line 1177 of file tz.py.
_find_compdt()
dateutil.tz.tz._tzicalvtz._find_compdt (self, comp, dt) protected
Definition at line 1222 of file tz.py.
dst()
dateutil.tz.tz._tzicalvtz.dst (self, dt)
Definition at line 1236 of file tz.py.
tzname()
dateutil.tz.tz._tzicalvtz.tzname (self, dt)
Definition at line 1244 of file tz.py.
utcoffset()
dateutil.tz.tz._tzicalvtz.utcoffset (self, dt)
Definition at line 1230 of file tz.py.
Member Data Documentation
__reduce__
dateutil.tz.tz._tzicalvtz.__reduce__ = object.__reduce__ static private
Definition at line 1250 of file tz.py.
_cache_lock
dateutil.tz.tz._tzicalvtz._cache_lock = _thread.allocate_lock() protected
Definition at line 1175 of file tz.py.
Referenced by dateutil.tz.tz.tzical.get().
_cachecomp
list dateutil.tz.tz._tzicalvtz._cachecomp = [] protected
Definition at line 1174 of file tz.py.
_cachedate
dateutil.tz.tz._tzicalvtz._cachedate = [] protected
Definition at line 1173 of file tz.py.
_comps
dateutil.tz.tz._tzicalvtz._comps = comps protected
Definition at line 1172 of file tz.py.
_tzid
dateutil.tz.tz._tzicalvtz._tzid = tzid protected
Definition at line 1171 of file tz.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/dateutil/tz/tz.py