Code Cloning Analysis: scipy.signal.tests.test_signaltools.TestSOSFiltFilt Class Reference
scipy.signal.tests.test_signaltools.TestSOSFiltFilt Class Reference
Public Member Functions
test_equivalence (self)
Public Member Functions inherited from scipy.signal.tests.test_signaltools.TestFiltFilt
filtfilt (self, zpk, x, axis=-1, padtype='odd', padlen=None, method='pad', irlen=None)
test_basic (self)
test_sine (self)
test_axis (self)
test_acoeff (self)
test_gust_simple (self)
test_gust_scalars (self)
Additional Inherited Members
Static Public Attributes inherited from scipy.signal.tests.test_signaltools.TestFiltFilt
str filtfilt_kind = 'tf'
Detailed Description
Definition at line 2367 of file test_signaltools.py.
Member Function Documentation
test_equivalence()
scipy.signal.tests.test_signaltools.TestSOSFiltFilt.test_equivalence (self)
Test equivalence between sosfiltfilt and filtfilt
Definition at line 2370 of file test_signaltools.py.
References scipy.signal._signaltools.sosfiltfilt(), scipy.signal._filter_design.zpk2sos(), and scipy.signal._filter_design.zpk2tf().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/signal/tests/test_signaltools.py