Code Cloning Analysis: joblib.externals.loky.backend.process.LokyInitMainProcess Class Reference
joblib.externals.loky.backend.process.LokyInitMainProcess Class Reference
Public Member Functions
__init__ (self, group=None, target=None, name=None, args=(), kwargs={}, daemon=None)
Public Member Functions inherited from joblib.externals.loky.backend.process.LokyProcess
__init__ (self, group=None, target=None, name=None, args=(), kwargs={}, daemon=None, init_main_module=False, env=None)
Additional Inherited Members
Public Attributes inherited from joblib.externals.loky.backend.process.LokyProcess
dict env = {} if env is None else env
authkey = self.authkey
init_main_module = init_main_module
Static Protected Member Functions inherited from joblib.externals.loky.backend.process.LokyProcess
_Popen (process_obj)
Static Protected Attributes inherited from joblib.externals.loky.backend.process.LokyProcess
str _start_method = "loky"
Detailed Description
Definition at line 48 of file process.py.
Constructor & Destructor Documentation
__init__()
joblib.externals.loky.backend.process.LokyInitMainProcess.__init__ (self, group = None, target = None, name = None, args = (), kwargs = {}, daemon = None)
Definition at line 51 of file process.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/joblib/externals/loky/backend/process.py