Code Cloning Analysis: pandas.util._validators Namespace Reference
pandas.util._validators Namespace Reference
Functions
None _check_arg_length (fname, args, max_fname_arg_count, compat_args)
None _check_for_default_values (fname, arg_val_dict, compat_args)
None validate_args (fname, args, max_fname_arg_count, compat_args)
None _check_for_invalid_keys (fname, kwargs, compat_args)
None validate_kwargs (fname, kwargs, compat_args)
None validate_args_and_kwargs (fname, args, kwargs, max_fname_arg_count, compat_args)
BoolishNoneT validate_bool_kwarg (BoolishNoneT value, str arg_name, bool none_allowed=True, bool int_allowed=False)
validate_fillna_kwargs (value, method, bool validate_scalar_dict_value=True)
np.ndarray validate_percentile (float|Iterable[float] q)
BoolishT validate_ascending (BoolishT ascending)
list[BoolishT] validate_ascending (Sequence[BoolishT] ascending)
bool|int|list[BoolishT] validate_ascending (bool|int|Sequence[BoolishT] ascending)
tuple[bool, bool] validate_endpoints (str|None closed)
tuple[bool, bool] validate_inclusive (str|None inclusive)
int validate_insert_loc (int loc, int length)
None check_dtype_backend (dtype_backend)
Variables
BoolishT = TypeVar("BoolishT", bool, int)
BoolishNoneT = TypeVar("BoolishNoneT", bool, int, None)
Detailed Description
Module that contains many useful utilities
for validating data or function arguments
Function Documentation
_check_arg_length()
None pandas.util._validators._check_arg_length (fname, args, max_fname_arg_count, compat_args) protected
Checks whether 'args' has length of at most 'compat_args'. Raises
a TypeError if that is not the case, similar to in Python when a
function is called with too many arguments.
Definition at line 29 of file _validators.py.
Referenced by validate_args(), and validate_args_and_kwargs().
_check_for_default_values()
None pandas.util._validators._check_for_default_values (fname, arg_val_dict, compat_args) protected
Check that the keys in `arg_val_dict` are mapped to their
default values as specified in `compat_args`.
Note that this function is to be called only when it has been
checked that arg_val_dict.keys() is a subset of compat_args
Definition at line 49 of file _validators.py.
Referenced by validate_args(), and validate_kwargs().
_check_for_invalid_keys()
None pandas.util._validators._check_for_invalid_keys (fname, kwargs, compat_args) protected
Checks whether 'kwargs' contains any keys that are not
in 'compat_args' and raises a TypeError if there is one.
Definition at line 128 of file _validators.py.
Referenced by validate_kwargs().
check_dtype_backend()
None pandas.util._validators.check_dtype_backend (dtype_backend)
Definition at line 450 of file _validators.py.
validate_args()
None pandas.util._validators.validate_args (fname, args, max_fname_arg_count, compat_args)
Checks whether the length of the `*args` argument passed into a function
has at most `len(compat_args)` arguments and whether or not all of these
elements in `args` are set to their default values.
Parameters
----------
fname : str
    The name of the function being passed the `*args` parameter
args : tuple
    The `*args` parameter passed into a function
max_fname_arg_count : int
    The maximum number of arguments that the function `fname`
    can accept, excluding those in `args`. Used for displaying
    appropriate error messages. Must be non-negative.
compat_args : dict
    A dictionary of keys and their associated default values.
    In order to accommodate buggy behaviour in some versions of `numpy`,
    where a signature displayed keyword arguments but then passed those
    arguments **positionally** internally when calling downstream
    implementations, a dict ensures that the original
    order of the keyword arguments is enforced.
Raises
------
TypeError
    If `args` contains more values than there are `compat_args`
ValueError
    If `args` contains values that do not correspond to those
    of the default values specified in `compat_args`
Definition at line 87 of file _validators.py.
References _check_arg_length(), and _check_for_default_values().
validate_args_and_kwargs()
None pandas.util._validators.validate_args_and_kwargs (fname, args, kwargs, max_fname_arg_count, compat_args)
Checks whether parameters passed to the *args and **kwargs argument in a
function `fname` are valid parameters as specified in `*compat_args`
and whether or not they are set to their default values.
Parameters
----------
fname: str
    The name of the function being passed the `**kwargs` parameter
args: tuple
    The `*args` parameter passed into a function
kwargs: dict
    The `**kwargs` parameter passed into `fname`
max_fname_arg_count: int
    The minimum number of arguments that the function `fname`
    requires, excluding those in `args`. Used for displaying
    appropriate error messages. Must be non-negative.
compat_args: dict
    A dictionary of keys that `kwargs` is allowed to
    have and their associated default values.
Raises
------
TypeError if `args` contains more values than there are
`compat_args` OR `kwargs` contains keys not in `compat_args`
ValueError if `args` contains values not at the default value (`None`)
`kwargs` contains keys in `compat_args` that do not map to the default
value as specified in `compat_args`
See Also
--------
validate_args : Purely args validation.
validate_kwargs : Purely kwargs validation.
Definition at line 168 of file _validators.py.
References _check_arg_length(), and validate_kwargs().
validate_ascending() [1/3]
BoolishT pandas.util._validators.validate_ascending (BoolishT ascending)
Definition at line 345 of file _validators.py.
validate_ascending() [2/3]
bool | int | list[BoolishT] pandas.util._validators.validate_ascending (bool | int | Sequence[BoolishT] ascending)
Validate ``ascending`` kwargs for ``sort_index`` method.
Definition at line 354 of file _validators.py.
References validate_bool_kwarg().
validate_ascending() [3/3]
list[BoolishT] pandas.util._validators.validate_ascending (Sequence[BoolishT] ascending)
Definition at line 350 of file _validators.py.
validate_bool_kwarg()
BoolishNoneT pandas.util._validators.validate_bool_kwarg (BoolishNoneT value, str arg_name, bool none_allowed = True, bool int_allowed = False)
Ensure that argument passed in arg_name can be interpreted as boolean.
Parameters
----------
value : bool
    Value to be validated.
arg_name : str
    Name of the argument. To be reflected in the error message.
none_allowed : bool, default True
    Whether to consider None to be a valid boolean.
int_allowed : bool, default False
    Whether to consider integer value to be a valid boolean.
Returns
-------
value
    The same value as input.
Raises
------
ValueError
    If the value is not a valid boolean.
Definition at line 226 of file _validators.py.
Referenced by validate_ascending().
validate_endpoints()
tuple[bool, bool] pandas.util._validators.validate_endpoints (str | None closed)
Check that the `closed` argument is among [None, "left", "right"]
Parameters
----------
closed : {None, "left", "right"}
Returns
-------
left_closed : bool
right_closed : bool
Raises
------
ValueError : if argument is not among valid values
Definition at line 365 of file _validators.py.
validate_fillna_kwargs()
pandas.util._validators.validate_fillna_kwargs (value, method, bool validate_scalar_dict_value = True)
Validate the keyword arguments to 'fillna'.
This checks that exactly one of 'value' and 'method' is specified.
If 'method' is specified, this validates that it's a valid method.
Parameters
----------
value, method : object
    The 'value' and 'method' keyword arguments for 'fillna'.
validate_scalar_dict_value : bool, default True
    Whether to validate that 'value' is a scalar or dict. Specifically,
    validate that it is not a list or tuple.
Returns
-------
value, method : object
Definition at line 271 of file _validators.py.
validate_inclusive()
tuple[bool, bool] pandas.util._validators.validate_inclusive (str | None inclusive)
Check that the `inclusive` argument is among {"both", "neither", "left", "right"}.
Parameters
----------
inclusive : {"both", "neither", "left", "right"}
Returns
-------
left_right_inclusive : tuple[bool, bool]
Raises
------
ValueError : if argument is not among valid values
Definition at line 398 of file _validators.py.
validate_insert_loc()
int pandas.util._validators.validate_insert_loc (int loc, int length)
Check that we have an integer between -length and length, inclusive.
Standardize negative loc to within [0, length].
The exceptions we raise on failure match np.insert.
Definition at line 432 of file _validators.py.
validate_kwargs()
None pandas.util._validators.validate_kwargs (fname, kwargs, compat_args)
Checks whether parameters passed to the **kwargs argument in a
function `fname` are valid parameters as specified in `*compat_args`
and whether or not they are set to their default values.
Parameters
----------
fname : str
    The name of the function being passed the `**kwargs` parameter
kwargs : dict
    The `**kwargs` parameter passed into `fname`
compat_args: dict
    A dictionary of keys that `kwargs` is allowed to have and their
    associated default values
Raises
------
TypeError if `kwargs` contains keys not in `compat_args`
ValueError if `kwargs` contains keys in `compat_args` that do not
map to the default values specified in `compat_args`
Definition at line 141 of file _validators.py.
References _check_for_default_values(), and _check_for_invalid_keys().
Referenced by validate_args_and_kwargs().
validate_percentile()
np.ndarray pandas.util._validators.validate_percentile (float | Iterable[float] q)
Validate percentiles (used by describe and quantile).
This function checks if the given float or iterable of floats is a valid percentile
otherwise raises a ValueError.
Parameters
----------
q: float or iterable of floats
    A single percentile or an iterable of percentiles.
Returns
-------
ndarray
    An ndarray of the percentiles if valid.
Raises
------
ValueError if percentiles are not in given interval([0, 1]).
Definition at line 310 of file _validators.py.
Variable Documentation
BoolishNoneT
pandas.util._validators.BoolishNoneT = TypeVar("BoolishNoneT", bool, int, None)
Definition at line 26 of file _validators.py.
BoolishT
pandas.util._validators.BoolishT = TypeVar("BoolishT", bool, int)
Definition at line 25 of file _validators.py.