Code Cloning Analysis: matplotlib.backends.qt_editor._formlayout.ColorLayout Class Reference
matplotlib.backends.qt_editor._formlayout.ColorLayout Class Reference
Public Member Functions
__init__ (self, color, parent=None)
update_color (self)
update_text (self, color)
text (self)
Public Attributes
lineedit
update_color
colorbtn = ColorButton(parent)
update_text
Detailed Description
Color-specialized QLineEdit layout
Definition at line 106 of file _formlayout.py.
Constructor & Destructor Documentation
__init__()
matplotlib.backends.qt_editor._formlayout.ColorLayout.__init__ (self, color, parent = None)
Definition at line 108 of file _formlayout.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
text()
matplotlib.backends.qt_editor._formlayout.ColorLayout.text (self)
Definition at line 128 of file _formlayout.py.
Referenced by matplotlib.figure.FigureBase._suplabels(), and PIL.ImageDraw.ImageDraw.text().
update_color()
matplotlib.backends.qt_editor._formlayout.ColorLayout.update_color (self)
Definition at line 120 of file _formlayout.py.
update_text()
matplotlib.backends.qt_editor._formlayout.ColorLayout.update_text (self, color)
Definition at line 125 of file _formlayout.py.
Member Data Documentation
colorbtn
matplotlib.backends.qt_editor._formlayout.ColorLayout.colorbtn = ColorButton(parent)
Definition at line 115 of file _formlayout.py.
lineedit
matplotlib.backends.qt_editor._formlayout.ColorLayout.lineedit
Initial value:
=  QtWidgets.QLineEdit(
            mcolors.to_hex(color.getRgbF(), keep_alpha=True), parent)
Definition at line 111 of file _formlayout.py.
update_color
matplotlib.backends.qt_editor._formlayout.ColorLayout.update_color
Definition at line 113 of file _formlayout.py.
update_text
matplotlib.backends.qt_editor._formlayout.ColorLayout.update_text
Definition at line 117 of file _formlayout.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/backends/qt_editor/_formlayout.py