Code Cloning Analysis: sklearn.utils.parallel.Parallel Class Reference
sklearn.utils.parallel.Parallel Class Reference
Public Member Functions
__call__ (self, iterable)
Public Member Functions inherited from joblib.parallel.Parallel
__init__ (self, n_jobs=default_parallel_config["n_jobs"], backend=default_parallel_config["backend"], return_as="list", verbose=default_parallel_config["verbose"], timeout=None, pre_dispatch="2 * n_jobs", batch_size="auto", temp_folder=default_parallel_config["temp_folder"], max_nbytes=default_parallel_config["max_nbytes"], mmap_mode=default_parallel_config["mmap_mode"], prefer=default_parallel_config["prefer"], require=default_parallel_config["require"], **backend_kwargs)
__enter__ (self)
__exit__ (self, exc_type, exc_value, traceback)
dispatch_next (self)
dispatch_one_batch (self, iterator)
print_progress (self)
__call__ (self, iterable)
__repr__ (self)
Public Member Functions inherited from joblib.logger.Logger
__init__ (self, depth=3, name=None)
warn (self, msg)
info (self, msg)
debug (self, msg)
format (self, obj, indent=0)
Additional Inherited Members
Public Attributes inherited from joblib.parallel.Parallel
verbose = _get_config_param(verbose, context_config, "verbose")
timeout = timeout
pre_dispatch = pre_dispatch
return_as = return_as
str return_generator = "list"
str return_ordered = "generator_unordered"
n_jobs = n_jobs
str batch_size = batch_size
int n_completed_tasks
int n_dispatched_batches = time.time() - self._start_time
int n_dispatched_tasks
n_tasks = len(iterable) if hasattr(iterable, "__len__") else None
Public Attributes inherited from joblib.logger.Logger
depth = depth
Protected Member Functions inherited from joblib.parallel.Parallel
_initialize_backend (self)
_effective_n_jobs (self)
_terminate_and_reset (self)
_dispatch (self, batch)
_register_new_job (self, batch_tracker)
_get_batch_size (self)
_print (self, msg)
_is_completed (self)
_abort (self)
_start (self, iterator, pre_dispatch)
_get_outputs (self, iterator, pre_dispatch)
_wait_retrieval (self)
_retrieve (self)
_raise_error_fast (self)
_warn_exit_early (self)
_get_sequential_output (self, iterable)
_reset_run_tracking (self)
Protected Attributes inherited from joblib.parallel.Parallel
dict _backend_kwargs
_lock = threading.RLock()
_jobs = collections.deque()
_jobs_set = set()
_pending_outputs = list()
_ready_batches = queue.Queue()
_reducer_callback = None
_backend = backend
bool _running = False
bool _managed_backend = False
_id = uuid4().hex
_call_ref = None
bool _calling = False
bool _aborting
_original_iterator
bool _iterating = False
bool _aborted = True
bool _exception = True
int _nb_consumed = 0
_start_time = time.time()
_call_id = uuid4().hex
_cached_effective_n_jobs = n_jobs
int _pre_dispatch_amount = 0
_pickle_cache = dict()
Protected Attributes inherited from joblib.logger.Logger
str _name = name if name else "joblib"
Detailed Description
Tweak of :class:`joblib.Parallel` that propagates the scikit-learn configuration.
This subclass of :class:`joblib.Parallel` ensures that the active configuration
(thread-local) of scikit-learn is propagated to the parallel workers for the
duration of the execution of the parallel tasks.
The API does not change and you can refer to :class:`joblib.Parallel`
documentation for more details.
.. versionadded:: 1.3
Definition at line 41 of file parallel.py.
Member Function Documentation
__call__()
sklearn.utils.parallel.Parallel.__call__ (self, iterable)
Dispatch the tasks and return the results.
Parameters
----------
iterable : iterable
    Iterable containing tuples of (delayed_function, args, kwargs) that should
    be consumed.
Returns
-------
results : list
    List of results of the tasks.
Definition at line 54 of file parallel.py.
References __call__(), and sklearn.utils.parallel._with_config_and_warning_filters().
Referenced by __call__().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/sklearn/utils/parallel.py