Code Cloning Analysis: joblib.test.test_parallel.MyBackend Class Reference
joblib.test.test_parallel.MyBackend Class Reference
Public Member Functions
get_nested_backend (self)
Public Member Functions inherited from joblib._parallel_backends.LokyBackend
configure (self, n_jobs=1, parallel=None, prefer=None, require=None, idle_worker_timeout=None, **memmapping_executor_kwargs)
effective_n_jobs (self, n_jobs)
submit (self, func, callback=None)
retrieve_result_callback (self, future)
terminate (self)
abort_everything (self, ensure_ready=True)
Public Member Functions inherited from joblib._parallel_backends.AutoBatchingMixin
__init__ (self, **kwargs)
compute_batch_size (self)
batch_completed (self, batch_size, duration)
reset_batch_stats (self)
Public Member Functions inherited from joblib._parallel_backends.ParallelBackendBase
supports_return_generator (self)
supports_timeout (self)
__init__ (self, nesting_level=None, inner_max_num_threads=None, **backend_kwargs)
apply_async (self, func, callback=None)
retrieve_result (self, out, timeout=None)
start_call (self)
stop_call (self)
compute_batch_size (self)
batch_completed (self, batch_size, duration)
retrieval_context (self)
Additional Inherited Members
Static Public Member Functions inherited from joblib._parallel_backends.ParallelBackendBase
in_main_thread ()
Public Attributes inherited from joblib._parallel_backends.ParallelBackendBase
inner_max_num_threads = inner_max_num_threads
backend_kwargs = backend_kwargs
supports_timeout
parallel = parallel
Static Public Attributes inherited from joblib._parallel_backends.AutoBatchingMixin
float MIN_IDEAL_BATCH_DURATION = 0.2
int MAX_IDEAL_BATCH_DURATION = 2
Static Public Attributes inherited from joblib._parallel_backends.ParallelBackendBase
int default_n_jobs = 1
bool supports_inner_max_num_threads = False
bool supports_retrieve_callback = False
nesting_level = None
list MAX_NUM_THREADS_VARS
str TBB_ENABLE_IPC_VAR = "ENABLE_IPC"
Protected Member Functions inherited from joblib._parallel_backends.ParallelBackendBase
_prepare_worker_env (self, n_jobs)
Protected Attributes inherited from joblib._parallel_backends.LokyBackend
_workers
Protected Attributes inherited from joblib._parallel_backends.AutoBatchingMixin
int _effective_batch_size = self._DEFAULT_EFFECTIVE_BATCH_SIZE
float _smoothed_batch_duration = self._DEFAULT_SMOOTHED_BATCH_DURATION
Static Protected Attributes inherited from joblib._parallel_backends.AutoBatchingMixin
int _DEFAULT_EFFECTIVE_BATCH_SIZE = 1
float _DEFAULT_SMOOTHED_BATCH_DURATION = 0.0
Detailed Description
Backend to test backward compatibility with older backends
Definition at line 942 of file test_parallel.py.
Member Function Documentation
get_nested_backend()
joblib.test.test_parallel.MyBackend.get_nested_backend (self)
Backend instance to be used by nested Parallel calls.
By default a thread-based backend is used for the first level of
nesting. Beyond, switch to sequential backend to avoid spawning too
many threads on the host.
Reimplemented from joblib._parallel_backends.ParallelBackendBase.
Definition at line 945 of file test_parallel.py.
References joblib._parallel_backends.LokyBackend.effective_n_jobs(), get_nested_backend(), and foo::a.i.
Referenced by get_nested_backend().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/joblib/test/test_parallel.py