Code Cloning Analysis: fontTools.pens.transformPen.TransformPen Class Reference
fontTools.pens.transformPen.TransformPen Class Reference
Public Member Functions
__init__ (self, outPen, transformation)
moveTo (self, pt)
lineTo (self, pt)
curveTo (self, *points)
qCurveTo (self, *points)
closePath (self)
endPath (self)
addComponent (self, glyphName, transformation)
Public Member Functions inherited from fontTools.pens.filterPen.FilterPen
__init__ (self, outPen)
Public Member Functions inherited from fontTools.pens.basePen.AbstractPen
None addVarComponent (self, str glyphName, DecomposedTransform transformation, Dict[str, float] location)
Protected Member Functions
_transformPoints (self, points)
Protected Attributes
_transformation = transformation
_transformPoint = transformation.transformPoint
list _stack = []
Protected Attributes inherited from fontTools.pens.filterPen.FilterPen
_outPen = outPen
Additional Inherited Members
Public Attributes inherited from fontTools.pens.filterPen.FilterPen
current_pt = None
Detailed Description
Pen that transforms all coordinates using a Affine transformation,
and passes them to another pen.
Definition at line 7 of file transformPen.py.
Constructor & Destructor Documentation
__init__()
fontTools.pens.transformPen.TransformPen.__init__ (self, outPen, transformation)
The 'outPen' argument is another pen object. It will receive the
transformed coordinates. The 'transformation' argument can either
be a six-tuple, or a fontTools.misc.transform.Transform object.
Definition at line 12 of file transformPen.py.
References __init__(), _stack, _transformation, and _transformPoint.
Referenced by __init__(), sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_transformPoints()
fontTools.pens.transformPen.TransformPen._transformPoints (self, points) protected
Definition at line 42 of file transformPen.py.
Referenced by curveTo(), and qCurveTo().
addComponent()
fontTools.pens.transformPen.TransformPen.addComponent (self, glyphName, transformation)
Reimplemented from fontTools.pens.filterPen._PassThruComponentsMixin.
Definition at line 52 of file transformPen.py.
closePath()
fontTools.pens.transformPen.TransformPen.closePath (self)
Close the current sub path. You must call either pen.closePath()
or pen.endPath() after each sub path.
Reimplemented from fontTools.pens.filterPen.FilterPen.
Definition at line 46 of file transformPen.py.
References fontTools.pens.filterPen.FilterPen._outPen, and closePath().
Referenced by closePath().
curveTo()
fontTools.pens.transformPen.TransformPen.curveTo (self, * points)
Draw a cubic bezier with an arbitrary number of control points.
The last point specified is on-curve, all others are off-curve
(control) points. If the number of control points is > 2, the
segment is split into multiple bezier segments. This works
like this:
Let n be the number of control points (which is the number of
arguments to this call minus 1). If n==2, a plain vanilla cubic
bezier is drawn. If n==1, we fall back to a quadratic segment and
if n==0 we draw a straight line. It gets interesting when n>2:
n-1 PostScript-style cubic segments will be drawn as if it were
one curve. See decomposeSuperBezierSegment().
The conversion algorithm used for n>2 is inspired by NURB
splines, and is conceptually equivalent to the TrueType "implied
points" principle. See also decomposeQuadraticSegment().
Reimplemented from fontTools.pens.filterPen.FilterPen.
Definition at line 32 of file transformPen.py.
References fontTools.pens.filterPen.FilterPen._outPen, _transformPoints(), and curveTo().
Referenced by curveTo().
endPath()
fontTools.pens.transformPen.TransformPen.endPath (self)
End the current sub path, but don't close it. You must call
either pen.closePath() or pen.endPath() after each sub path.
Reimplemented from fontTools.pens.filterPen.FilterPen.
Definition at line 49 of file transformPen.py.
References fontTools.pens.filterPen.FilterPen._outPen, _transformation, and endPath().
Referenced by endPath().
lineTo()
fontTools.pens.transformPen.TransformPen.lineTo (self, pt)
Draw a straight line from the current point to 'pt'.
Reimplemented from fontTools.pens.filterPen.FilterPen.
Definition at line 29 of file transformPen.py.
References fontTools.pens.filterPen.FilterPen._outPen, _transformPoint, and lineTo().
Referenced by lineTo().
moveTo()
fontTools.pens.transformPen.TransformPen.moveTo (self, pt)
Begin a new sub path, set the current point to 'pt'. You must
end each sub path with a call to pen.closePath() or pen.endPath().
Reimplemented from fontTools.pens.filterPen.FilterPen.
Definition at line 26 of file transformPen.py.
References fontTools.pens.filterPen.FilterPen._outPen, _transformPoint, and moveTo().
Referenced by moveTo().
qCurveTo()
fontTools.pens.transformPen.TransformPen.qCurveTo (self, * points)
Draw a whole string of quadratic curve segments.
The last point specified is on-curve, all others are off-curve
points.
This method implements TrueType-style curves, breaking up curves
using 'implied points': between each two consequtive off-curve points,
there is one implied point exactly in the middle between them. See
also decomposeQuadraticSegment().
The last argument (normally the on-curve point) may be None.
This is to support contours that have NO on-curve points (a rarely
seen feature of TrueType outlines).
Reimplemented from fontTools.pens.filterPen.FilterPen.
Definition at line 35 of file transformPen.py.
References fontTools.pens.filterPen.FilterPen._outPen, _transformPoint, _transformPoints(), and qCurveTo().
Referenced by qCurveTo().
Member Data Documentation
_stack
list fontTools.pens.transformPen.TransformPen._stack = [] protected
Definition at line 24 of file transformPen.py.
Referenced by __init__(), pip._vendor.rich.style.StyleStack.current(), pip._vendor.rich.style.StyleStack.pop(), and pip._vendor.rich.style.StyleStack.push().
_transformation
fontTools.pens.transformPen.TransformPen._transformation = transformation protected
Definition at line 22 of file transformPen.py.
Referenced by __init__(), fontTools.pens.transformPen.TransformPointPen.__init__(), fontTools.pens.transformPen.TransformPointPen.addPoint(), and endPath().
_transformPoint
fontTools.pens.transformPen.TransformPen._transformPoint = transformation.transformPoint protected
Definition at line 23 of file transformPen.py.
Referenced by __init__(), fontTools.pens.transformPen.TransformPointPen.__init__(), fontTools.pens.transformPen.TransformPointPen.addPoint(), lineTo(), moveTo(), and qCurveTo().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/pens/transformPen.py