Code Cloning Analysis: matplotlib.legend.DraggableLegend Class Reference
matplotlib.legend.DraggableLegend Class Reference
Public Member Functions
__init__ (self, legend, use_blit=False, update="loc")
finalize_offset (self)
Public Member Functions inherited from matplotlib.offsetbox.DraggableOffsetBox
__init__ (self, ref_artist, offsetbox, use_blit=False)
save_offset (self)
update_offset (self, dx, dy)
get_loc_in_canvas (self)
Public Member Functions inherited from matplotlib.offsetbox.DraggableBase
__init__ (self, ref_artist, use_blit=False)
on_motion (self, evt)
on_pick (self, evt)
on_release (self, event)
disconnect (self)
Public Attributes
legend = legend
Public Attributes inherited from matplotlib.offsetbox.DraggableOffsetBox
offsetbox = offsetbox
offsetbox_x
offsetbox_y = offset
Public Attributes inherited from matplotlib.offsetbox.DraggableBase
ref_artist = ref_artist
bool got_artist = False
background = evt.y - self.mouse_y
mouse_x = evt.mouseevent.x
mouse_y = evt.mouseevent.y
Protected Member Functions
_update_loc (self, loc_in_canvas)
_update_bbox_to_anchor (self, loc_in_canvas)
Protected Member Functions inherited from matplotlib.offsetbox.DraggableBase
_check_still_parented (self)
Protected Attributes
str _update = update
Protected Attributes inherited from matplotlib.offsetbox.DraggableBase
_picker
_use_blit = use_blit and self.canvas.supports_blit
list _disconnectors
Additional Inherited Members
Static Protected Member Functions inherited from matplotlib.offsetbox.DraggableBase
_picker (artist, mouseevent)
Properties inherited from matplotlib.offsetbox.DraggableBase
canvas = property(lambda self: self.ref_artist.get_figure(root=True).canvas)
cids
Detailed Description
Definition at line 54 of file legend.py.
Constructor & Destructor Documentation
__init__()
matplotlib.legend.DraggableLegend.__init__ (self, legend, use_blit = False, update = "loc")
Wrapper around a `.Legend` to support mouse dragging.
Parameters
----------
legend : `.Legend`
    The `.Legend` instance to wrap.
use_blit : bool, optional
    Use blitting for faster image composition. For details see
    :ref:`func-animation`.
update : {'loc', 'bbox'}, optional
    If "loc", update the *loc* parameter of the legend upon finalizing.
    If "bbox", update the *bbox_to_anchor* parameter.
Definition at line 55 of file legend.py.
References __init__(), _update, _update_bbox_to_anchor(), _update_loc(), matplotlib.offsetbox.DraggableOffsetBox.get_loc_in_canvas(), and legend.
Referenced by __init__(), sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_update_bbox_to_anchor()
matplotlib.legend.DraggableLegend._update_bbox_to_anchor (self, loc_in_canvas) protected
Definition at line 93 of file legend.py.
Referenced by __init__().
_update_loc()
matplotlib.legend.DraggableLegend._update_loc (self, loc_in_canvas) protected
Definition at line 83 of file legend.py.
Referenced by __init__().
finalize_offset()
matplotlib.legend.DraggableLegend.finalize_offset (self)
Reimplemented from matplotlib.offsetbox.DraggableBase.
Definition at line 77 of file legend.py.
Member Data Documentation
_update
str matplotlib.legend.DraggableLegend._update = update protected
Definition at line 73 of file legend.py.
Referenced by __init__(), and fontTools.pens.statisticsPen.StatisticsControlPen._qCurveToOne().
legend
matplotlib.legend.DraggableLegend.legend = legend
Definition at line 70 of file legend.py.
Referenced by __init__(), pandas.plotting._matplotlib.core.MPLPlot._append_legend_handles_labels(), and pandas.plotting._matplotlib.core.MPLPlot._kind().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/legend.py