Code Cloning Analysis: axes_grid1.axes_size._Base Class Reference
axes_grid1.axes_size._Base Class Reference
Public Member Functions
__rmul__ (self, other)
__mul__ (self, other)
__div__ (self, other)
__add__ (self, other)
__neg__ (self)
__radd__ (self, other)
__sub__ (self, other)
get_size (self, renderer)
Detailed Description
Definition at line 22 of file axes_size.py.
Member Function Documentation
__add__()
axes_grid1.axes_size._Base.__add__ (self, other)
Definition at line 34 of file axes_size.py.
Referenced by scipy.signal._ltisys.StateSpace.__add__(), scipy.sparse.linalg._interface.LinearOperator._rdot(), and scipy.sparse._base._spbase.power().
__div__()
axes_grid1.axes_size._Base.__div__ (self, other)
Definition at line 31 of file axes_size.py.
__mul__()
axes_grid1.axes_size._Base.__mul__ (self, other)
Definition at line 26 of file axes_size.py.
Referenced by pip._vendor.pyparsing.core.ParserElement.__mul__(), pyparsing.core.ParserElement.__mul__(), scipy.signal._ltisys.StateSpace.__truediv__(), and scipy.sparse.linalg._interface.LinearOperator.dot().
__neg__()
axes_grid1.axes_size._Base.__neg__ (self)
Definition at line 40 of file axes_size.py.
__radd__()
axes_grid1.axes_size._Base.__radd__ (self, other)
Definition at line 43 of file axes_size.py.
__rmul__()
axes_grid1.axes_size._Base.__rmul__ (self, other)
Definition at line 23 of file axes_size.py.
Referenced by scipy.sparse.linalg._interface.LinearOperator.dot().
__sub__()
axes_grid1.axes_size._Base.__sub__ (self, other)
Definition at line 48 of file axes_size.py.
get_size()
axes_grid1.axes_size._Base.get_size (self, renderer)
Return two-float tuple with relative and absolute sizes.
Reimplemented in axes_grid1.axes_size._AxesDecorationsSize, axes_grid1.axes_size.Add, axes_grid1.axes_size.AxesX, axes_grid1.axes_size.AxesY, axes_grid1.axes_size.Fixed, axes_grid1.axes_size.Fraction, axes_grid1.axes_size.MaxExtent, and axes_grid1.axes_size.Scaled.
Definition at line 51 of file axes_size.py.
Referenced by matplotlib.text.Text.set_bbox(), matplotlib.text.Text.update_bbox_position_size(), and matplotlib.text.Annotation.update_positions().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/mpl_toolkits/axes_grid1/axes_size.py