Code Cloning Analysis: matplotlib.projections.polar._AxisWrapper Class Reference
matplotlib.projections.polar._AxisWrapper Class Reference
Public Member Functions
__init__ (self, axis)
get_view_interval (self)
set_view_interval (self, vmin, vmax)
get_minpos (self)
get_data_interval (self)
set_data_interval (self, vmin, vmax)
get_tick_space (self)
Protected Attributes
_axis = axis
Detailed Description
Definition at line 274 of file polar.py.
Constructor & Destructor Documentation
__init__()
matplotlib.projections.polar._AxisWrapper.__init__ (self, axis)
Definition at line 275 of file polar.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
get_data_interval()
matplotlib.projections.polar._AxisWrapper.get_data_interval (self)
Definition at line 287 of file polar.py.
Referenced by mplot3d.axis3d.Axis.draw_pane().
get_minpos()
matplotlib.projections.polar._AxisWrapper.get_minpos (self)
Definition at line 284 of file polar.py.
get_tick_space()
matplotlib.projections.polar._AxisWrapper.get_tick_space (self)
Definition at line 293 of file polar.py.
get_view_interval()
matplotlib.projections.polar._AxisWrapper.get_view_interval (self)
Definition at line 278 of file polar.py.
Referenced by mplot3d.axis3d.Axis.draw_pane().
set_data_interval()
matplotlib.projections.polar._AxisWrapper.set_data_interval (self, vmin, vmax)
Definition at line 290 of file polar.py.
Referenced by mplot3d.axis3d.Axis.draw_pane().
set_view_interval()
matplotlib.projections.polar._AxisWrapper.set_view_interval (self, vmin, vmax)
Definition at line 281 of file polar.py.
Referenced by mplot3d.axis3d.Axis.draw_pane().
Member Data Documentation
_axis
matplotlib.projections.polar._AxisWrapper._axis = axis protected
Definition at line 276 of file polar.py.
Referenced by axisartist.axis_artist.GridlinesCollection.__init__(), axisartist.axis_artist.AxisLabel.get_ref_artist(), axisartist.axis_artist.TickLabels.get_ref_artist(), axisartist.axis_artist.Ticks.get_ref_artist(), axisartist.axis_artist.GridlinesCollection.set_axis(), and axisartist.axis_artist.GridlinesCollection.set_grid_helper().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/projections/polar.py