Code Cloning Analysis: fontTools.ttLib.tables._t_r_a_k.TrackData Class Reference
fontTools.ttLib.tables._t_r_a_k.TrackData Class Reference
Public Member Functions
__init__ (self, initialdata={})
compile (self, offset)
decompile (self, data, offset)
toXML (self, writer, ttFont)
fromXML (self, name, attrs, content, ttFont)
sizes (self)
__getitem__ (self, track)
__delitem__ (self, track)
__setitem__ (self, track, entry)
__len__ (self)
__iter__ (self)
keys (self)
__repr__ (self)
Public Attributes
nTracks
Static Public Attributes
tracks = keys
Protected Attributes
_map = dict(initialdata)
Detailed Description
Definition at line 131 of file _t_r_a_k.py.
Constructor & Destructor Documentation
__init__()
fontTools.ttLib.tables._t_r_a_k.TrackData.__init__ (self, initialdata = {})
Definition at line 132 of file _t_r_a_k.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__delitem__()
fontTools.ttLib.tables._t_r_a_k.TrackData.__delitem__ (self, track)
Definition at line 248 of file _t_r_a_k.py.
__getitem__()
fontTools.ttLib.tables._t_r_a_k.TrackData.__getitem__ (self, track)
Definition at line 245 of file _t_r_a_k.py.
__iter__()
fontTools.ttLib.tables._t_r_a_k.TrackData.__iter__ (self)
Definition at line 257 of file _t_r_a_k.py.
__len__()
fontTools.ttLib.tables._t_r_a_k.TrackData.__len__ (self)
Definition at line 254 of file _t_r_a_k.py.
__repr__()
fontTools.ttLib.tables._t_r_a_k.TrackData.__repr__ (self)
Definition at line 265 of file _t_r_a_k.py.
__setitem__()
fontTools.ttLib.tables._t_r_a_k.TrackData.__setitem__ (self, track, entry)
Definition at line 251 of file _t_r_a_k.py.
compile()
fontTools.ttLib.tables._t_r_a_k.TrackData.compile (self, offset)
Definition at line 135 of file _t_r_a_k.py.
Referenced by fontTools.ttLib.tables.TupleVariation.TupleVariation.getCoordWidth(), and PIL.FontFile.FontFile.save().
decompile()
fontTools.ttLib.tables._t_r_a_k.TrackData.decompile (self, data, offset)
Definition at line 171 of file _t_r_a_k.py.
Referenced by fontTools.ttLib.tables._c_m_a_p.CmapSubtable.newSubtable().
fromXML()
fontTools.ttLib.tables._t_r_a_k.TrackData.fromXML (self, name, attrs, content, ttFont)
Definition at line 224 of file _t_r_a_k.py.
keys()
fontTools.ttLib.tables._t_r_a_k.TrackData.keys (self)
Definition at line 260 of file _t_r_a_k.py.
Referenced by fontTools.ttLib.ttFont.TTFont._save(), sklearn.utils._bunch.Bunch._set_deprecated(), pandas.io.pytables.HDFStore.copy(), fontTools.ttLib.ttFont.TTFont.ensureDecompiled(), scipy.sparse._dok._dok_base.get(), pandas.io.pytables.HDFStore.info(), pandas.io.pytables.HDFStore.keys(), fontTools.varLib.instancer.AxisLimits.normalize(), pip._vendor.pyparsing.results.ParseResults.pprint(), pyparsing.results.ParseResults.pprint(), scipy.sparse._dok._dok_base.resize(), fontTools.ttLib.ttFont.TTFont.saveXML(), scipy.sparse._dok._dok_base.tocoo(), and pip._vendor.distlib.metadata.LegacyMetadata.todict().
sizes()
fontTools.ttLib.tables._t_r_a_k.TrackData.sizes (self)
Definition at line 231 of file _t_r_a_k.py.
toXML()
fontTools.ttLib.tables._t_r_a_k.TrackData.toXML (self, writer, ttFont)
Definition at line 214 of file _t_r_a_k.py.
Member Data Documentation
_map
fontTools.ttLib.tables._t_r_a_k.TrackData._map = dict(initialdata) protected
Definition at line 133 of file _t_r_a_k.py.
nTracks
fontTools.ttLib.tables._t_r_a_k.TrackData.nTracks
Definition at line 192 of file _t_r_a_k.py.
tracks
fontTools.ttLib.tables._t_r_a_k.TrackData.tracks = keys static
Definition at line 263 of file _t_r_a_k.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ttLib/tables/_t_r_a_k.py