Code Cloning Analysis: pip._vendor.chardet.escprober.EscCharSetProber Class Reference
pip._vendor.chardet.escprober.EscCharSetProber Class Reference
Public Member Functions
None __init__ (self, LanguageFilter lang_filter=LanguageFilter.NONE)
None reset (self)
Optional[str] charset_name (self)
Optional[str] language (self)
float get_confidence (self)
ProbingState feed (self, Union[bytes, bytearray] byte_str)
Public Member Functions inherited from pip._vendor.chardet.charsetprober.CharSetProber
None __init__ (self, LanguageFilter lang_filter=LanguageFilter.NONE)
ProbingState state (self)
Public Attributes
list coding_sm = []
int active_sm_count = 0
Public Attributes inherited from pip._vendor.chardet.charsetprober.CharSetProber
bool active = True
lang_filter = lang_filter
logger = logging.getLogger(__name__)
Protected Attributes
Optional[str] _detected_charset = None
Optional[str] _detected_language = None
Protected Attributes inherited from pip._vendor.chardet.charsetprober.CharSetProber
_state = ProbingState.DETECTING
Additional Inherited Members
Static Public Member Functions inherited from pip._vendor.chardet.charsetprober.CharSetProber
bytes filter_high_byte_only (Union[bytes, bytearray] buf)
bytearray filter_international_words (Union[bytes, bytearray] buf)
bytes remove_xml_tags (Union[bytes, bytearray] buf)
Static Public Attributes inherited from pip._vendor.chardet.charsetprober.CharSetProber
float SHORTCUT_THRESHOLD = 0.95
Detailed Description
This CharSetProber uses a "code scheme" approach for detecting encodings,
whereby easily recognizable escape or shift sequences are relied on to
identify these encodings.
Definition at line 41 of file escprober.py.
Constructor & Destructor Documentation
__init__()
None pip._vendor.chardet.escprober.EscCharSetProber.__init__ (self, LanguageFilter lang_filter = LanguageFilter.NONE)
Definition at line 48 of file escprober.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
charset_name()
Optional[str] pip._vendor.chardet.escprober.EscCharSetProber.charset_name (self)
Reimplemented from pip._vendor.chardet.charsetprober.CharSetProber.
Definition at line 74 of file escprober.py.
feed()
ProbingState pip._vendor.chardet.escprober.EscCharSetProber.feed (self, Union[bytes, bytearray] byte_str)
Reimplemented from pip._vendor.chardet.charsetprober.CharSetProber.
Definition at line 84 of file escprober.py.
get_confidence()
float pip._vendor.chardet.escprober.EscCharSetProber.get_confidence (self)
Reimplemented from pip._vendor.chardet.charsetprober.CharSetProber.
Definition at line 81 of file escprober.py.
language()
Optional[str] pip._vendor.chardet.escprober.EscCharSetProber.language (self)
Reimplemented from pip._vendor.chardet.charsetprober.CharSetProber.
Definition at line 78 of file escprober.py.
reset()
None pip._vendor.chardet.escprober.EscCharSetProber.reset (self)
Reimplemented from pip._vendor.chardet.charsetprober.CharSetProber.
Definition at line 64 of file escprober.py.
Referenced by scipy._lib._docscrape.Reader.__init__().
Member Data Documentation
_detected_charset
Optional[str] pip._vendor.chardet.escprober.EscCharSetProber._detected_charset = None protected
Definition at line 59 of file escprober.py.
_detected_language
Optional[str] pip._vendor.chardet.escprober.EscCharSetProber._detected_language = None protected
Definition at line 60 of file escprober.py.
active_sm_count
int pip._vendor.chardet.escprober.EscCharSetProber.active_sm_count = 0
Definition at line 58 of file escprober.py.
coding_sm
list pip._vendor.chardet.escprober.EscCharSetProber.coding_sm = []
Definition at line 50 of file escprober.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pip/_vendor/chardet/escprober.py