Code Cloning Analysis: pip._internal.commands.uninstall.UninstallCommand Class Reference
pip._internal.commands.uninstall.UninstallCommand Class Reference
Public Member Functions
None add_options (self)
int run (self, Values options, List[str] args)
Public Member Functions inherited from pip._internal.cli.base_command.Command
None __init__ (self, str name, str summary, bool isolated=False)
None handle_pip_version_check (self, Values options)
Tuple[Values, List[str]] parse_args (self, List[str] args)
int main (self, List[str] args)
Public Member Functions inherited from pip._internal.cli.command_context.CommandContextMixIn
None __init__ (self)
Generator[None, None, None] main_context (self)
_T enter_context (self, ContextManager[_T] context_provider)
Public Member Functions inherited from pip._internal.cli.req_command.SessionCommandMixin
None __init__ (self)
PipSession get_default_session (self, Values options)
Additional Inherited Members
Public Attributes inherited from pip._internal.cli.base_command.Command
name = name
summary = summary
parser
Optional[TempDirRegistry] tempdir_registry = None
cmd_opts = optparse.OptionGroup(self.parser, optgroup_name)
verbosity = options.verbose - options.quiet
Static Public Attributes inherited from pip._internal.cli.base_command.Command
str usage = ""
bool ignore_require_venv = False
Protected Member Functions inherited from pip._internal.cli.base_command.Command
int _main (self, List[str] args)
Protected Member Functions inherited from pip._internal.cli.req_command.SessionCommandMixin
Optional[List[str]] _get_index_urls (cls, Values options)
PipSession _build_session (self, Values options, Optional[int] retries=None, Optional[int] timeout=None, bool fallback_to_certifi=False)
Protected Attributes inherited from pip._internal.cli.command_context.CommandContextMixIn
bool _in_main_context = False
_main_context = ExitStack()
Protected Attributes inherited from pip._internal.cli.req_command.SessionCommandMixin
Optional[PipSession] _session = None
Detailed Description
Uninstall packages.
pip is able to uninstall most installed packages. Known exceptions are:
- Pure distutils packages installed with ``python setup.py install``, which
  leave behind no metadata to determine what files were installed.
- Script wrappers installed by ``python setup.py develop``.
Definition at line 25 of file uninstall.py.
Member Function Documentation
add_options()
None pip._internal.commands.uninstall.UninstallCommand.add_options (self)
Reimplemented from pip._internal.cli.base_command.Command.
Definition at line 40 of file uninstall.py.
run()
int pip._internal.commands.uninstall.UninstallCommand.run (self, Values options, List[str] args)
Reimplemented from pip._internal.cli.base_command.Command.
Definition at line 64 of file uninstall.py.
Referenced by scipy.odr._odrpack.ODR.restart(), scipy.integrate._ode.lsoda.run_relax(), scipy.integrate._ode.vode.run_relax(), scipy.integrate._ode.lsoda.step(), and scipy.integrate._ode.vode.step().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pip/_internal/commands/uninstall.py