Code Cloning Analysis: pandas.io.sql.PandasSQL Class Reference
pandas.io.sql.PandasSQL Class Reference
Public Member Functions
Self __enter__ (self)
None __exit__ (self, *args)
DataFrame|Iterator[DataFrame] read_table (self, str table_name, str|list[str]|None index_col=None, bool coerce_float=True, parse_dates=None, columns=None, str|None schema=None, int|None chunksize=None, DtypeBackend|Literal["numpy"] dtype_backend="numpy")
DataFrame|Iterator[DataFrame] read_query (self, str sql, str|list[str]|None index_col=None, bool coerce_float=True, parse_dates=None, params=None, int|None chunksize=None, DtypeArg|None dtype=None, DtypeBackend|Literal["numpy"] dtype_backend="numpy")
int|None to_sql (self, frame, str name, Literal["fail", "replace", "append"] if_exists="fail", bool index=True, index_label=None, schema=None, int|None chunksize=None, DtypeArg|None dtype=None, Literal["multi"]|Callable|None method=None, str engine="auto", **engine_kwargs)
execute (self, str|Select|TextClause sql, params=None)
bool has_table (self, str name, str|None schema=None)
Public Member Functions inherited from pandas.core.base.PandasObject
str __repr__ (self)
int __sizeof__ (self)
Public Member Functions inherited from pandas.core.accessor.DirNamesMixin
list[str] __dir__ (self)
Protected Member Functions
str _create_sql_schema (self, DataFrame frame, str table_name, list[str]|None keys=None, DtypeArg|None dtype=None, str|None schema=None)
Protected Member Functions inherited from pandas.core.base.PandasObject
_constructor (self)
None _reset_cache (self, str|None key=None)
Protected Member Functions inherited from pandas.core.accessor.DirNamesMixin
set[str] _dir_deletions (self)
set[str] _dir_additions (self)
Additional Inherited Members
Static Protected Attributes inherited from pandas.core.base.PandasObject
dict _cache [str, Any]
Static Protected Attributes inherited from pandas.core.accessor.DirNamesMixin
set _accessors = set()
frozenset _hidden_attrs = frozenset()
Detailed Description
Subclasses Should define read_query and to_sql.
Definition at line 1455 of file sql.py.
Member Function Documentation
__enter__()
Self pandas.io.sql.PandasSQL.__enter__ (self)
Definition at line 1460 of file sql.py.
__exit__()
None pandas.io.sql.PandasSQL.__exit__ (self, * args)
Definition at line 1463 of file sql.py.
_create_sql_schema()
str pandas.io.sql.PandasSQL._create_sql_schema (self, DataFrame frame, str table_name, list[str] | None keys = None, DtypeArg | None dtype = None, str | None schema = None) protected
Definition at line 1519 of file sql.py.
execute()
pandas.io.sql.PandasSQL.execute (self, str | Select | TextClause sql, params = None)
Reimplemented in pandas.io.sql.SQLDatabase.
Definition at line 1511 of file sql.py.
Referenced by pandas.io.sql.SQLiteDatabase._query_iterator(), pandas.io.sql.SQLDatabase.read_query(), and pandas.io.sql.SQLiteDatabase.to_sql().
has_table()
bool pandas.io.sql.PandasSQL.has_table (self, str name, str | None schema = None)
Definition at line 1515 of file sql.py.
Referenced by pandas.io.sql.ADBCDatabase.to_sql(), and pandas.io.sql.SQLDatabase.to_sql().
read_query()
DataFrame | Iterator[DataFrame] pandas.io.sql.PandasSQL.read_query (self, str sql, str | list[str] | None index_col = None, bool coerce_float = True, parse_dates = None, params = None, int | None chunksize = None, DtypeArg | None dtype = None, DtypeBackend | Literal["numpy"] dtype_backend = "numpy")
Reimplemented in pandas.io.sql.ADBCDatabase, and pandas.io.sql.SQLDatabase.
Definition at line 1480 of file sql.py.
read_table()
DataFrame | Iterator[DataFrame] pandas.io.sql.PandasSQL.read_table (self, str table_name, str | list[str] | None index_col = None, bool coerce_float = True, parse_dates = None, columns = None, str | None schema = None, int | None chunksize = None, DtypeBackend | Literal["numpy"] dtype_backend = "numpy")
Reimplemented in pandas.io.sql.ADBCDatabase, and pandas.io.sql.SQLDatabase.
Definition at line 1466 of file sql.py.
to_sql()
int | None pandas.io.sql.PandasSQL.to_sql (self, frame, str name, Literal["fail", "replace", "append"] if_exists = "fail", bool index = True, index_label = None, schema = None, int | None chunksize = None, DtypeArg | None dtype = None, Literal["multi"] | Callable | None method = None, str engine = "auto", ** engine_kwargs)
Reimplemented in pandas.io.sql.ADBCDatabase, pandas.io.sql.SQLDatabase, and pandas.io.sql.SQLiteDatabase.
Definition at line 1494 of file sql.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/io/sql.py