Code Cloning Analysis: scipy.special._mptestutils.ComplexArg Class Reference
scipy.special._mptestutils.ComplexArg Class Reference
Public Member Functions
__init__ (self, a=complex(-np.inf, -np.inf), b=complex(np.inf, np.inf))
values (self, n)
Public Attributes
real = Arg(a.real, b.real)
imag = Arg(a.imag, b.imag)
Detailed Description
Definition at line 141 of file _mptestutils.py.
Constructor & Destructor Documentation
__init__()
scipy.special._mptestutils.ComplexArg.__init__ (self, a = complex(-np.inf, -np.inf), b = complex(np.inf, np.inf))
Definition at line 142 of file _mptestutils.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
values()
scipy.special._mptestutils.ComplexArg.values (self, n)
Definition at line 146 of file _mptestutils.py.
Referenced by scipy.sparse._dok._dok_base.count_nonzero(), and scipy.sparse._dok._dok_base.tocoo().
Member Data Documentation
imag
scipy.special._mptestutils.ComplexArg.imag = Arg(a.imag, b.imag)
Definition at line 144 of file _mptestutils.py.
real
scipy.special._mptestutils.ComplexArg.real = Arg(a.real, b.real)
Definition at line 143 of file _mptestutils.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/special/_mptestutils.py