Code Cloning Analysis: matplotlib.tests.test_pickle.TransformBlob Class Reference
matplotlib.tests.test_pickle.TransformBlob Class Reference
Public Member Functions
__init__ (self)
Public Attributes
identity = mtransforms.IdentityTransform()
identity2 = mtransforms.IdentityTransform()
composite
wrapper = mtransforms.TransformWrapper(self.composite)
composite2
Detailed Description
Definition at line 221 of file test_pickle.py.
Constructor & Destructor Documentation
__init__()
matplotlib.tests.test_pickle.TransformBlob.__init__ (self)
Definition at line 222 of file test_pickle.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Data Documentation
composite
matplotlib.tests.test_pickle.TransformBlob.composite
Initial value:
=  mtransforms.CompositeGenericTransform(
            self.identity,
            self.identity2)
Definition at line 226 of file test_pickle.py.
composite2
matplotlib.tests.test_pickle.TransformBlob.composite2
Initial value:
=  mtransforms.CompositeGenericTransform(
            self.wrapper,
            self.identity)
Definition at line 232 of file test_pickle.py.
identity
matplotlib.tests.test_pickle.TransformBlob.identity = mtransforms.IdentityTransform()
Definition at line 223 of file test_pickle.py.
identity2
matplotlib.tests.test_pickle.TransformBlob.identity2 = mtransforms.IdentityTransform()
Definition at line 224 of file test_pickle.py.
wrapper
matplotlib.tests.test_pickle.TransformBlob.wrapper = mtransforms.TransformWrapper(self.composite)
Definition at line 230 of file test_pickle.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/tests/test_pickle.py