Code Cloning Analysis: axisartist.grid_finder.DictFormatter Class Reference
axisartist.grid_finder.DictFormatter Class Reference
Public Member Functions
__init__ (self, format_dict, formatter=None)
__call__ (self, direction, factor, values)
Protected Attributes
_format_dict = format_dict
_fallback_formatter = formatter
Detailed Description
Definition at line 306 of file grid_finder.py.
Constructor & Destructor Documentation
__init__()
axisartist.grid_finder.DictFormatter.__init__ (self, format_dict, formatter = None)
format_dict : dictionary for format strings to be used.
formatter : fall-back formatter
Definition at line 307 of file grid_finder.py.
References __init__(), _fallback_formatter, and _format_dict.
Referenced by __init__(), sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__call__()
axisartist.grid_finder.DictFormatter.__call__ (self, direction, factor, values)
factor is ignored if value is found in the dictionary
Definition at line 316 of file grid_finder.py.
References _fallback_formatter, and _format_dict.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), and scipy.interpolate._fitpack2.SphereBivariateSpline.ev().
Member Data Documentation
_fallback_formatter
axisartist.grid_finder.DictFormatter._fallback_formatter = formatter protected
Definition at line 314 of file grid_finder.py.
Referenced by __call__(), and __init__().
_format_dict
axisartist.grid_finder.DictFormatter._format_dict = format_dict protected
Definition at line 313 of file grid_finder.py.
Referenced by __call__(), and __init__().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/mpl_toolkits/axisartist/grid_finder.py