Code Cloning Analysis: scipy.stats._multivariate Namespace Reference
scipy.stats._multivariate Namespace Reference
Classes
class _PSD
class dirichlet_frozen
class dirichlet_gen
class dirichlet_multinomial_frozen
class dirichlet_multinomial_gen
class invwishart_frozen
class invwishart_gen
class matrix_normal_frozen
class matrix_normal_gen
class multi_rv_frozen
class multi_rv_generic
class multinomial_frozen
class multinomial_gen
class multivariate_hypergeom_frozen
class multivariate_hypergeom_gen
class multivariate_normal_frozen
class multivariate_normal_gen
class multivariate_t_frozen
class multivariate_t_gen
class ortho_group_frozen
class ortho_group_gen
class random_correlation_frozen
class random_correlation_gen
class random_table_frozen
class random_table_gen
class special_ortho_group_frozen
class special_ortho_group_gen
class uniform_direction_frozen
class uniform_direction_gen
class unitary_group_frozen
class unitary_group_gen
class vonmises_fisher_frozen
class vonmises_fisher_gen
class wishart_frozen
class wishart_gen
Functions
_squeeze_output (out)
_eigvalsh_to_eps (spectrum, cond=None, rcond=None)
_pinv_1d (v, eps=1e-5)
_dirichlet_check_parameters (alpha)
_dirichlet_check_input (alpha, x)
_lnB (alpha)
_cho_inv_batch (a, check_finite=True)
_docfill (obj, docdict, template=None)
_sample_uniform_direction (dim, size, random_state)
_dirichlet_multinomial_check_parameters (alpha, n, x=None)
Variables
list __all__
_LOG_2PI = np.log(2 * np.pi)
_LOG_2 = np.log(2)
_LOG_PI = np.log(np.pi)
str _doc_random_state
str _mvn_doc_default_callparams
str _mvn_doc_callparams_note
str _mvn_doc_frozen_callparams = ""
str _mvn_doc_frozen_callparams_note
dict mvn_docdict_params
dict mvn_docdict_noparams
multivariate_normal = multivariate_normal_gen()
method = multivariate_normal_gen.__dict__[name]
method_frozen = multivariate_normal_frozen.__dict__[name]
__doc__
str _matnorm_doc_default_callparams
str _matnorm_doc_callparams_note
str _matnorm_doc_frozen_callparams = ""
str _matnorm_doc_frozen_callparams_note
dict matnorm_docdict_params
dict matnorm_docdict_noparams
matrix_normal = matrix_normal_gen()
str _dirichlet_doc_default_callparams
str _dirichlet_doc_frozen_callparams = ""
str _dirichlet_doc_frozen_callparams_note
dict dirichlet_docdict_params
dict dirichlet_docdict_noparams
dirichlet = dirichlet_gen()
str _wishart_doc_default_callparams
str _wishart_doc_callparams_note = ""
str _wishart_doc_frozen_callparams = ""
str _wishart_doc_frozen_callparams_note
dict wishart_docdict_params
dict wishart_docdict_noparams
wishart = wishart_gen()
invwishart = invwishart_gen()
str _multinomial_doc_default_callparams
str _multinomial_doc_callparams_note
str _multinomial_doc_frozen_callparams = ""
str _multinomial_doc_frozen_callparams_note
dict multinomial_docdict_params
dict multinomial_docdict_noparams
multinomial = multinomial_gen()
special_ortho_group = special_ortho_group_gen()
ortho_group = ortho_group_gen()
random_correlation = random_correlation_gen()
unitary_group = unitary_group_gen()
str _mvt_doc_default_callparams
str _mvt_doc_callparams_note
str _mvt_doc_frozen_callparams_note
dict mvt_docdict_params
dict mvt_docdict_noparams
multivariate_t = multivariate_t_gen()
str _mhg_doc_default_callparams
str _mhg_doc_callparams_note
str _mhg_doc_frozen_callparams = ""
str _mhg_doc_frozen_callparams_note
dict mhg_docdict_params
dict mhg_docdict_noparams
multivariate_hypergeom = multivariate_hypergeom_gen()
random_table = random_table_gen()
str _ctab_doc_row_col
str _ctab_doc_x
str _ctab_doc_row_col_note
str _ctab_doc_mean_params
str _ctab_doc_row_col_note_frozen
dict _ctab_docdict
dict _ctab_docdict_frozen = _ctab_docdict.copy()
uniform_direction = uniform_direction_gen()
str _dirichlet_mn_doc_default_callparams
str _dirichlet_mn_doc_frozen_callparams = ""
str _dirichlet_mn_doc_frozen_callparams_note
dict dirichlet_mn_docdict_params
dict dirichlet_mn_docdict_noparams
dirichlet_multinomial = dirichlet_multinomial_gen()
vonmises_fisher = vonmises_fisher_gen()
Function Documentation
_cho_inv_batch()
scipy.stats._multivariate._cho_inv_batch (a, check_finite = True) protected
Invert the matrices a_i, using a Cholesky factorization of A, where
a_i resides in the last two dimensions of a and the other indices describe
the index i.
Overwrites the data in a.
Parameters
----------
a : array
    Array of matrices to invert, where the matrices themselves are stored
    in the last two dimensions.
check_finite : bool, optional
    Whether to check that the input matrices contain only finite numbers.
    Disabling may give a performance gain, but may result in problems
    (crashes, non-termination) if the inputs do contain infinities or NaNs.
Returns
-------
x : array
    Array of inverses of the matrices ``a_i``.
See Also
--------
scipy.linalg.cholesky : Cholesky factorization of a matrix
Definition at line 2469 of file _multivariate.py.
Referenced by scipy.stats._multivariate.invwishart_gen._logpdf(), and scipy.stats.tests.test_multivariate.TestInvwishart.test_cho_inv_batch().
_dirichlet_check_input()
scipy.stats._multivariate._dirichlet_check_input (alpha, x) protected
Definition at line 1397 of file _multivariate.py.
_dirichlet_check_parameters()
scipy.stats._multivariate._dirichlet_check_parameters (alpha) protected
Definition at line 1387 of file _multivariate.py.
_dirichlet_multinomial_check_parameters()
scipy.stats._multivariate._dirichlet_multinomial_check_parameters (alpha, n, x = None) protected
Definition at line 5904 of file _multivariate.py.
_docfill()
scipy.stats._multivariate._docfill (obj, docdict, template = None) protected
Definition at line 5691 of file _multivariate.py.
_eigvalsh_to_eps()
scipy.stats._multivariate._eigvalsh_to_eps (spectrum, cond = None, rcond = None) protected
Determine which eigenvalues are "small" given the spectrum.
This is for compatibility across various linear algebra functions
that should agree about whether or not a Hermitian matrix is numerically
singular and what is its numerical matrix rank.
This is designed to be compatible with scipy.linalg.pinvh.
Parameters
----------
spectrum : 1d ndarray
    Array of eigenvalues of a Hermitian matrix.
cond, rcond : float, optional
    Cutoff for small eigenvalues.
    Singular values smaller than rcond * largest_eigenvalue are
    considered zero.
    If None or -1, suitable machine precision is used.
Returns
-------
eps : float
    Magnitude cutoff for numerical negligibility.
Definition at line 67 of file _multivariate.py.
_lnB()
scipy.stats._multivariate._lnB (alpha) protected
Internal helper function to compute the log of the useful quotient.
.. math::
B(\alpha) = \frac{\prod_{i=1}{K}\Gamma(\alpha_i)}
{\Gamma\left(\sum_{i=1}^{K} \alpha_i \right)}
Parameters
----------
%(_dirichlet_doc_default_callparams)s
Returns
-------
B : scalar
Helper quotient, internal use only
Definition at line 1441 of file _multivariate.py.
Referenced by scipy.stats._multivariate.dirichlet_gen._logpdf(), and scipy.stats._multivariate.dirichlet_gen.entropy().
_pinv_1d()
scipy.stats._multivariate._pinv_1d (v, eps = 1e-5) protected
A helper function for computing the pseudoinverse.
Parameters
----------
v : iterable of numbers
    This may be thought of as a vector of eigenvalues or singular values.
eps : float
    Values with magnitude no greater than eps are considered negligible.
Returns
-------
v_pinv : 1d float ndarray
    A vector of pseudo-inverted numbers.
Definition at line 101 of file _multivariate.py.
_sample_uniform_direction()
scipy.stats._multivariate._sample_uniform_direction (dim, size, random_state) protected
Private method to generate uniform directions
Reference: Marsaglia, G. (1972). "Choosing a Point from the Surface of a
           Sphere". Annals of Mathematical Statistics. 43 (2): 645-646.
Definition at line 5867 of file _multivariate.py.
Referenced by scipy.stats._multivariate.vonmises_fisher_gen._rejection_sampling(), scipy.stats._multivariate.vonmises_fisher_gen._rvs_3d(), and scipy.stats._multivariate.uniform_direction_gen.rvs().
_squeeze_output()
scipy.stats._multivariate._squeeze_output (out) protected
Remove single-dimensional entries from array and convert to scalar,
if necessary.
Definition at line 56 of file _multivariate.py.
Referenced by scipy.stats._multivariate.invwishart_frozen.__init__(), scipy.stats._multivariate.multivariate_normal_frozen.__init__(), scipy.stats._multivariate.multivariate_normal_gen._cdf(), scipy.stats._multivariate.multivariate_t_gen._logpdf(), scipy.stats._multivariate.dirichlet_gen.entropy(), scipy.stats._multivariate.dirichlet_gen.logpdf(), scipy.stats._multivariate.invwishart_gen.logpdf(), scipy.stats._multivariate.matrix_normal_gen.logpdf(), scipy.stats._multivariate.multivariate_normal_gen.logpdf(), scipy.stats._multivariate.wishart_gen.logpdf(), scipy.stats._multivariate.dirichlet_gen.mean(), scipy.stats._multivariate.invwishart_gen.mean(), scipy.stats._multivariate.wishart_gen.mean(), scipy.stats._multivariate.invwishart_gen.mode(), scipy.stats._multivariate.wishart_gen.mode(), scipy.stats._multivariate.dirichlet_gen.pdf(), scipy.stats._multivariate.multivariate_normal_gen.pdf(), scipy.stats._multivariate.invwishart_gen.rvs(), scipy.stats._multivariate.multivariate_normal_gen.rvs(), scipy.stats._multivariate.multivariate_t_gen.rvs(), scipy.stats._multivariate.wishart_gen.rvs(), scipy.stats._multivariate.dirichlet_gen.var(), scipy.stats._multivariate.invwishart_gen.var(), and scipy.stats._multivariate.wishart_gen.var().
Variable Documentation
__all__
list scipy.stats._multivariate.__all__ private
Initial value:
=  ['multivariate_normal',
           'matrix_normal',
           'dirichlet',
           'dirichlet_multinomial',
           'wishart',
           'invwishart',
           'multinomial',
           'special_ortho_group',
           'ortho_group',
           'random_correlation',
           'unitary_group',
           'multivariate_t',
           'multivariate_hypergeom',
           'random_table',
           'uniform_direction',
           'vonmises_fisher']
Definition at line 22 of file _multivariate.py.
__doc__
scipy.stats._multivariate.__doc__ private
Definition at line 899 of file _multivariate.py.
_ctab_doc_mean_params
str scipy.stats._multivariate._ctab_doc_mean_params protected
Initial value:
=  f"""
Parameters
----------
{_ctab_doc_row_col}"""
Definition at line 5667 of file _multivariate.py.
_ctab_doc_row_col
str scipy.stats._multivariate._ctab_doc_row_col protected
Initial value:
=  """\
row : array_like
    Sum of table entries in each row.
col : array_like
    Sum of table entries in each column."""
Definition at line 5650 of file _multivariate.py.
_ctab_doc_row_col_note
str scipy.stats._multivariate._ctab_doc_row_col_note protected
Initial value:
=  """\
The row and column vectors must be one-dimensional, not empty,
and each sum up to the same value. They cannot contain negative
or noninteger entries."""
Definition at line 5662 of file _multivariate.py.
_ctab_doc_row_col_note_frozen
str scipy.stats._multivariate._ctab_doc_row_col_note_frozen protected
Initial value:
=  """\
See class definition for a detailed description of parameters."""
Definition at line 5672 of file _multivariate.py.
_ctab_doc_x
str scipy.stats._multivariate._ctab_doc_x protected
Initial value:
=  """\
x : array-like
   Two-dimensional table of non-negative integers, or a
   multi-dimensional array with the last two dimensions
   corresponding with the tables."""
Definition at line 5656 of file _multivariate.py.
_ctab_docdict
dict scipy.stats._multivariate._ctab_docdict protected
Initial value:
=  {
    "_doc_random_state": _doc_random_state,
    "_doc_row_col": _ctab_doc_row_col,
    "_doc_x": _ctab_doc_x,
    "_doc_mean_params": _ctab_doc_mean_params,
    "_doc_row_col_note": _ctab_doc_row_col_note,
}
Definition at line 5675 of file _multivariate.py.
_ctab_docdict_frozen
dict scipy.stats._multivariate._ctab_docdict_frozen = _ctab_docdict.copy() protected
Definition at line 5683 of file _multivariate.py.
_dirichlet_doc_default_callparams
str scipy.stats._multivariate._dirichlet_doc_default_callparams protected
Initial value:
=  """\
alpha : array_like
    The concentration parameters. The number of entries determines the
    dimensionality of the distribution.
"""
Definition at line 1366 of file _multivariate.py.
_dirichlet_doc_frozen_callparams
str scipy.stats._multivariate._dirichlet_doc_frozen_callparams = "" protected
Definition at line 1371 of file _multivariate.py.
_dirichlet_doc_frozen_callparams_note
str scipy.stats._multivariate._dirichlet_doc_frozen_callparams_note protected
Initial value:
=  """\
See class definition for a detailed description of parameters."""
Definition at line 1373 of file _multivariate.py.
_dirichlet_mn_doc_default_callparams
str scipy.stats._multivariate._dirichlet_mn_doc_default_callparams protected
Initial value:
=  """\
alpha : array_like
    The concentration parameters. The number of entries along the last axis
    determines the dimensionality of the distribution. Each entry must be
    strictly positive.
n : int or array_like
    The number of trials. Each element must be a strictly positive integer.
"""
Definition at line 5879 of file _multivariate.py.
_dirichlet_mn_doc_frozen_callparams
str scipy.stats._multivariate._dirichlet_mn_doc_frozen_callparams = "" protected
Definition at line 5888 of file _multivariate.py.
_dirichlet_mn_doc_frozen_callparams_note
str scipy.stats._multivariate._dirichlet_mn_doc_frozen_callparams_note protected
Initial value:
=  """\
See class definition for a detailed description of parameters."""
Definition at line 5890 of file _multivariate.py.
_doc_random_state
str scipy.stats._multivariate._doc_random_state protected
Initial value:
=  """\
seed : {None, int, np.random.RandomState, np.random.Generator}, optional
    Used for drawing random variates.
    If `seed` is `None`, the `~np.random.RandomState` singleton is used.
    If `seed` is an int, a new ``RandomState`` instance is used, seeded
    with seed.
    If `seed` is already a ``RandomState`` or ``Generator`` instance,
    then that object is used.
    Default is `None`.
"""
Definition at line 44 of file _multivariate.py.
_LOG_2
scipy.stats._multivariate._LOG_2 = np.log(2) protected
Definition at line 40 of file _multivariate.py.
_LOG_2PI
scipy.stats._multivariate._LOG_2PI = np.log(2 * np.pi) protected
Definition at line 39 of file _multivariate.py.
_LOG_PI
scipy.stats._multivariate._LOG_PI = np.log(np.pi) protected
Definition at line 41 of file _multivariate.py.
_matnorm_doc_callparams_note
str scipy.stats._multivariate._matnorm_doc_callparams_note protected
Initial value:
=  """\
If `mean` is set to `None` then a matrix of zeros is used for the mean.
The dimensions of this matrix are inferred from the shape of `rowcov` and
`colcov`, if these are provided, or set to `1` if ambiguous.
`rowcov` and `colcov` can be two-dimensional array_likes specifying the
covariance matrices directly. Alternatively, a one-dimensional array will
be be interpreted as the entries of a diagonal matrix, and a scalar or
zero-dimensional array will be interpreted as this value times the
identity matrix.
"""
Definition at line 912 of file _multivariate.py.
_matnorm_doc_default_callparams
str scipy.stats._multivariate._matnorm_doc_default_callparams protected
Initial value:
=  """\
mean : array_like, optional
    Mean of the distribution (default: `None`)
rowcov : array_like, optional
    Among-row covariance matrix of the distribution (default: `1`)
colcov : array_like, optional
    Among-column covariance matrix of the distribution (default: `1`)
"""
Definition at line 903 of file _multivariate.py.
_matnorm_doc_frozen_callparams
str scipy.stats._multivariate._matnorm_doc_frozen_callparams = "" protected
Definition at line 924 of file _multivariate.py.
_matnorm_doc_frozen_callparams_note
str scipy.stats._multivariate._matnorm_doc_frozen_callparams_note protected
Initial value:
=  """\
See class definition for a detailed description of parameters."""
Definition at line 926 of file _multivariate.py.
_mhg_doc_callparams_note
str scipy.stats._multivariate._mhg_doc_callparams_note protected
Initial value:
=  """\
`m` must be an array of positive integers. If the quantile
:math:`i` contains values out of the range :math:`[0, m_i]`
where :math:`m_i` is the number of objects of type :math:`i`
in the population or if the parameters are inconsistent with one
another (e.g. ``x.sum() != n``), methods return the appropriate
value (e.g. ``0`` for ``pmf``). If `m` or `n` contain negative
values, the result will contain ``nan`` there.
"""
Definition at line 4789 of file _multivariate.py.
_mhg_doc_default_callparams
str scipy.stats._multivariate._mhg_doc_default_callparams protected
Initial value:
=  """\
m : array_like
    The number of each type of object in the population.
    That is, :math:`m[i]` is the number of objects of
    type :math:`i`.
n : array_like
    The number of samples taken from the population.
"""
Definition at line 4780 of file _multivariate.py.
_mhg_doc_frozen_callparams
str scipy.stats._multivariate._mhg_doc_frozen_callparams = "" protected
Definition at line 4799 of file _multivariate.py.
_mhg_doc_frozen_callparams_note
str scipy.stats._multivariate._mhg_doc_frozen_callparams_note protected
Initial value:
=  """\
See class definition for a detailed description of parameters."""
Definition at line 4801 of file _multivariate.py.
_multinomial_doc_callparams_note
str scipy.stats._multivariate._multinomial_doc_callparams_note protected
Initial value:
=  """\
`n` should be a nonnegative integer. Each element of `p` should be in the
interval :math:`[0,1]` and the elements should sum to 1. If they do not sum to
1, the last element of the `p` array is not used and is replaced with the
remaining probability left over from the earlier elements.
"""
Definition at line 3050 of file _multivariate.py.
_multinomial_doc_default_callparams
str scipy.stats._multivariate._multinomial_doc_default_callparams protected
Initial value:
=  """\
n : int
    Number of trials
p : array_like
    Probability of a trial falling into each category; should sum to 1
"""
Definition at line 3043 of file _multivariate.py.
_multinomial_doc_frozen_callparams
str scipy.stats._multivariate._multinomial_doc_frozen_callparams = "" protected
Definition at line 3057 of file _multivariate.py.
_multinomial_doc_frozen_callparams_note
str scipy.stats._multivariate._multinomial_doc_frozen_callparams_note protected
Initial value:
=  """\
See class definition for a detailed description of parameters."""
Definition at line 3059 of file _multivariate.py.
_mvn_doc_callparams_note
str scipy.stats._multivariate._mvn_doc_callparams_note protected
Initial value:
=  """\
Setting the parameter `mean` to `None` is equivalent to having `mean`
be the zero-vector. The parameter `cov` can be a scalar, in which case
the covariance matrix is the identity times that value, a vector of
diagonal entries for the covariance matrix, a two-dimensional array_like,
or a `Covariance` object.
"""
Definition at line 266 of file _multivariate.py.
_mvn_doc_default_callparams
str scipy.stats._multivariate._mvn_doc_default_callparams protected
Initial value:
=  """\
mean : array_like, default: ``[0]``
    Mean of the distribution.
cov : array_like or `Covariance`, default: ``[1]``
    Symmetric positive (semi)definite covariance matrix of the distribution.
allow_singular : bool, default: ``False``
    Whether to allow a singular covariance matrix. This is ignored if `cov` is
    a `Covariance` object.
"""
Definition at line 256 of file _multivariate.py.
_mvn_doc_frozen_callparams
str scipy.stats._multivariate._mvn_doc_frozen_callparams = "" protected
Definition at line 274 of file _multivariate.py.
_mvn_doc_frozen_callparams_note
str scipy.stats._multivariate._mvn_doc_frozen_callparams_note protected
Initial value:
=  """\
See class definition for a detailed description of parameters."""
Definition at line 276 of file _multivariate.py.
_mvt_doc_callparams_note
str scipy.stats._multivariate._mvt_doc_callparams_note protected
Initial value:
=  """\
Setting the parameter `loc` to ``None`` is equivalent to having `loc`
be the zero-vector. The parameter `shape` can be a scalar, in which case
the shape matrix is the identity times that value, a vector of
diagonal entries for the shape matrix, or a two-dimensional array_like.
"""
Definition at line 4243 of file _multivariate.py.
_mvt_doc_default_callparams
str scipy.stats._multivariate._mvt_doc_default_callparams protected
Initial value:
=  """\
loc : array_like, optional
    Location of the distribution. (default ``0``)
shape : array_like, optional
    Positive semidefinite matrix of the distribution. (default ``1``)
df : float, optional
    Degrees of freedom of the distribution; must be greater than zero.
    If ``np.inf`` then results are multivariate normal. The default is ``1``.
allow_singular : bool, optional
    Whether to allow a singular matrix. (default ``False``)
"""
Definition at line 4231 of file _multivariate.py.
_mvt_doc_frozen_callparams_note
str scipy.stats._multivariate._mvt_doc_frozen_callparams_note protected
Initial value:
=  """\
See class definition for a detailed description of parameters."""
Definition at line 4250 of file _multivariate.py.
_wishart_doc_callparams_note
str scipy.stats._multivariate._wishart_doc_callparams_note = "" protected
Definition at line 1767 of file _multivariate.py.
_wishart_doc_default_callparams
str scipy.stats._multivariate._wishart_doc_default_callparams protected
Initial value:
=  """\
df : int
    Degrees of freedom, must be greater than or equal to dimension of the
    scale matrix
scale : array_like
    Symmetric positive definite scale matrix of the distribution
"""
Definition at line 1759 of file _multivariate.py.
_wishart_doc_frozen_callparams
str scipy.stats._multivariate._wishart_doc_frozen_callparams = "" protected
Definition at line 1769 of file _multivariate.py.
_wishart_doc_frozen_callparams_note
str scipy.stats._multivariate._wishart_doc_frozen_callparams_note protected
Initial value:
=  """\
See class definition for a detailed description of parameters."""
Definition at line 1771 of file _multivariate.py.
dirichlet
scipy.stats._multivariate.dirichlet = dirichlet_gen()
Definition at line 1722 of file _multivariate.py.
dirichlet_docdict_noparams
dict scipy.stats._multivariate.dirichlet_docdict_noparams
Initial value:
=  {
    '_dirichlet_doc_default_callparams': _dirichlet_doc_frozen_callparams,
    '_doc_random_state': _doc_random_state
}
Definition at line 1381 of file _multivariate.py.
dirichlet_docdict_params
dict scipy.stats._multivariate.dirichlet_docdict_params
Initial value:
=  {
    '_dirichlet_doc_default_callparams': _dirichlet_doc_default_callparams,
    '_doc_random_state': _doc_random_state
}
Definition at line 1376 of file _multivariate.py.
dirichlet_mn_docdict_noparams
dict scipy.stats._multivariate.dirichlet_mn_docdict_noparams
Initial value:
=  {
    '_dirichlet_mn_doc_default_callparams': _dirichlet_mn_doc_frozen_callparams, # noqa
    '_doc_random_state': _doc_random_state
}
Definition at line 5898 of file _multivariate.py.
dirichlet_mn_docdict_params
dict scipy.stats._multivariate.dirichlet_mn_docdict_params
Initial value:
=  {
    '_dirichlet_mn_doc_default_callparams': _dirichlet_mn_doc_default_callparams,  # noqa
    '_doc_random_state': _doc_random_state
}
Definition at line 5893 of file _multivariate.py.
dirichlet_multinomial
scipy.stats._multivariate.dirichlet_multinomial = dirichlet_multinomial_gen()
Definition at line 6156 of file _multivariate.py.
invwishart
scipy.stats._multivariate.invwishart = invwishart_gen()
Definition at line 2964 of file _multivariate.py.
matnorm_docdict_noparams
dict scipy.stats._multivariate.matnorm_docdict_noparams
Initial value:
=  {
    '_matnorm_doc_default_callparams': _matnorm_doc_frozen_callparams,
    '_matnorm_doc_callparams_note': _matnorm_doc_frozen_callparams_note,
    '_doc_random_state': _doc_random_state
}
Definition at line 935 of file _multivariate.py.
matnorm_docdict_params
dict scipy.stats._multivariate.matnorm_docdict_params
Initial value:
=  {
    '_matnorm_doc_default_callparams': _matnorm_doc_default_callparams,
    '_matnorm_doc_callparams_note': _matnorm_doc_callparams_note,
    '_doc_random_state': _doc_random_state
}
Definition at line 929 of file _multivariate.py.
matrix_normal
scipy.stats._multivariate.matrix_normal = matrix_normal_gen()
Definition at line 1297 of file _multivariate.py.
method
scipy.stats._multivariate.method = multivariate_normal_gen.__dict__[name]
Definition at line 897 of file _multivariate.py.
method_frozen
scipy.stats._multivariate.method_frozen = multivariate_normal_frozen.__dict__[name]
Definition at line 898 of file _multivariate.py.
mhg_docdict_noparams
dict scipy.stats._multivariate.mhg_docdict_noparams
Initial value:
=  {
    '_doc_default_callparams': _mhg_doc_frozen_callparams,
    '_doc_callparams_note': _mhg_doc_frozen_callparams_note,
    '_doc_random_state': _doc_random_state
}
Definition at line 4810 of file _multivariate.py.
mhg_docdict_params
dict scipy.stats._multivariate.mhg_docdict_params
Initial value:
=  {
    '_doc_default_callparams': _mhg_doc_default_callparams,
    '_doc_callparams_note': _mhg_doc_callparams_note,
    '_doc_random_state': _doc_random_state
}
Definition at line 4804 of file _multivariate.py.
multinomial
scipy.stats._multivariate.multinomial = multinomial_gen()
Definition at line 3405 of file _multivariate.py.
multinomial_docdict_noparams
dict scipy.stats._multivariate.multinomial_docdict_noparams
Initial value:
=  {
    '_doc_default_callparams': _multinomial_doc_frozen_callparams,
    '_doc_callparams_note': _multinomial_doc_frozen_callparams_note,
    '_doc_random_state': _doc_random_state
}
Definition at line 3068 of file _multivariate.py.
multinomial_docdict_params
dict scipy.stats._multivariate.multinomial_docdict_params
Initial value:
=  {
    '_doc_default_callparams': _multinomial_doc_default_callparams,
    '_doc_callparams_note': _multinomial_doc_callparams_note,
    '_doc_random_state': _doc_random_state
}
Definition at line 3062 of file _multivariate.py.
multivariate_hypergeom
scipy.stats._multivariate.multivariate_hypergeom = multivariate_hypergeom_gen()
Definition at line 5221 of file _multivariate.py.
multivariate_normal
scipy.stats._multivariate.multivariate_normal = multivariate_normal_gen()
Definition at line 790 of file _multivariate.py.
multivariate_t
scipy.stats._multivariate.multivariate_t = multivariate_t_gen()
Definition at line 4767 of file _multivariate.py.
mvn_docdict_noparams
dict scipy.stats._multivariate.mvn_docdict_noparams
Initial value:
=  {
    '_mvn_doc_default_callparams': _mvn_doc_frozen_callparams,
    '_mvn_doc_callparams_note': _mvn_doc_frozen_callparams_note,
    '_doc_random_state': _doc_random_state
}
Definition at line 285 of file _multivariate.py.
mvn_docdict_params
dict scipy.stats._multivariate.mvn_docdict_params
Initial value:
=  {
    '_mvn_doc_default_callparams': _mvn_doc_default_callparams,
    '_mvn_doc_callparams_note': _mvn_doc_callparams_note,
    '_doc_random_state': _doc_random_state
}
Definition at line 279 of file _multivariate.py.
mvt_docdict_noparams
dict scipy.stats._multivariate.mvt_docdict_noparams
Initial value:
=  {
    '_mvt_doc_default_callparams': "",
    '_mvt_doc_callparams_note': _mvt_doc_frozen_callparams_note,
    '_doc_random_state': _doc_random_state
}
Definition at line 4259 of file _multivariate.py.
mvt_docdict_params
dict scipy.stats._multivariate.mvt_docdict_params
Initial value:
=  {
    '_mvt_doc_default_callparams': _mvt_doc_default_callparams,
    '_mvt_doc_callparams_note': _mvt_doc_callparams_note,
    '_doc_random_state': _doc_random_state
}
Definition at line 4253 of file _multivariate.py.
ortho_group
scipy.stats._multivariate.ortho_group = ortho_group_gen()
Definition at line 3782 of file _multivariate.py.
random_correlation
scipy.stats._multivariate.random_correlation = random_correlation_gen()
Definition at line 4035 of file _multivariate.py.
random_table
scipy.stats._multivariate.random_table = random_table_gen()
Definition at line 5622 of file _multivariate.py.
special_ortho_group
scipy.stats._multivariate.special_ortho_group = special_ortho_group_gen()
Definition at line 3626 of file _multivariate.py.
uniform_direction
scipy.stats._multivariate.uniform_direction = uniform_direction_gen()
Definition at line 5832 of file _multivariate.py.
unitary_group
scipy.stats._multivariate.unitary_group = unitary_group_gen()
Definition at line 4198 of file _multivariate.py.
vonmises_fisher
scipy.stats._multivariate.vonmises_fisher = vonmises_fisher_gen()
Definition at line 6793 of file _multivariate.py.
wishart
scipy.stats._multivariate.wishart = wishart_gen()
Definition at line 2400 of file _multivariate.py.
wishart_docdict_noparams
dict scipy.stats._multivariate.wishart_docdict_noparams
Initial value:
=  {
    '_doc_default_callparams': _wishart_doc_frozen_callparams,
    '_doc_callparams_note': _wishart_doc_frozen_callparams_note,
    '_doc_random_state': _doc_random_state
}
Definition at line 1780 of file _multivariate.py.
wishart_docdict_params
dict scipy.stats._multivariate.wishart_docdict_params
Initial value:
=  {
    '_doc_default_callparams': _wishart_doc_default_callparams,
    '_doc_callparams_note': _wishart_doc_callparams_note,
    '_doc_random_state': _doc_random_state
}
Definition at line 1774 of file _multivariate.py.