Code Cloning Analysis: numpy.array_api._data_type_functions Namespace Reference
numpy.array_api._data_type_functions Namespace Reference
Classes
class finfo_object
class iinfo_object
Functions
Array astype (Array x, Dtype dtype, *, bool copy=True)
List[Array] broadcast_arrays (*Array arrays)
Array broadcast_to (Array x, Tuple[int,...] shape)
bool can_cast (Union[Dtype, Array] from_, Dtype to)
finfo_object finfo (Union[Dtype, Array] type)
iinfo_object iinfo (Union[Dtype, Array] type)
bool isdtype (Dtype dtype, Union[Dtype, str, Tuple[Union[Dtype, str],...]] kind)
Dtype result_type (*Union[Array, Dtype] arrays_and_dtypes)
Function Documentation
astype()
Array numpy.array_api._data_type_functions.astype (Array x, Dtype dtype, * , bool copy = True)
Definition at line 27 of file _data_type_functions.py.
broadcast_arrays()
List[Array] numpy.array_api._data_type_functions.broadcast_arrays (*Array arrays)
Array API compatible wrapper for :py:func:`np.broadcast_arrays <numpy.broadcast_arrays>`.
See its docstring for more information.
Definition at line 33 of file _data_type_functions.py.
broadcast_to()
Array numpy.array_api._data_type_functions.broadcast_to (Array x, Tuple[int, ...] shape)
Array API compatible wrapper for :py:func:`np.broadcast_to <numpy.broadcast_to>`.
See its docstring for more information.
Definition at line 46 of file _data_type_functions.py.
can_cast()
bool numpy.array_api._data_type_functions.can_cast (Union[Dtype, Array] from_, Dtype to)
Array API compatible wrapper for :py:func:`np.can_cast <numpy.can_cast>`.
See its docstring for more information.
Definition at line 57 of file _data_type_functions.py.
finfo()
finfo_object numpy.array_api._data_type_functions.finfo (Union[Dtype, Array] type)
Array API compatible wrapper for :py:func:`np.finfo <numpy.finfo>`.
See its docstring for more information.
Definition at line 104 of file _data_type_functions.py.
iinfo()
iinfo_object numpy.array_api._data_type_functions.iinfo (Union[Dtype, Array] type)
Array API compatible wrapper for :py:func:`np.iinfo <numpy.iinfo>`.
See its docstring for more information.
Definition at line 123 of file _data_type_functions.py.
isdtype()
bool numpy.array_api._data_type_functions.isdtype (Dtype dtype, Union[Dtype, str, Tuple[Union[Dtype, str], ...]] kind)
Returns a boolean indicating whether a provided dtype is of a specified data type ``kind``.
See
https://data-apis.org/array-api/latest/API_specification/generated/array_api.isdtype.html
for more details
Definition at line 134 of file _data_type_functions.py.
References numpy.core.fromnumeric.any(), and isdtype().
Referenced by isdtype().
result_type()
Dtype numpy.array_api._data_type_functions.result_type (*Union[Array, Dtype] arrays_and_dtypes)
Array API compatible wrapper for :py:func:`np.result_type <numpy.result_type>`.
See its docstring for more information.
Definition at line 171 of file _data_type_functions.py.