Code Cloning Analysis: matplotlib.backends._backend_pdf_ps.CharacterTracker Class Reference
matplotlib.backends._backend_pdf_ps.CharacterTracker Class Reference
Public Member Functions
__init__ (self)
track (self, font, s)
track_glyph (self, font, glyph)
Public Attributes
dict used = {}
Detailed Description
Helper for font subsetting by the pdf and ps backends.
Maintains a mapping of font paths to the set of character codepoints that
are being used from that font.
Definition at line 98 of file _backend_pdf_ps.py.
Constructor & Destructor Documentation
__init__()
matplotlib.backends._backend_pdf_ps.CharacterTracker.__init__ (self)
Definition at line 106 of file _backend_pdf_ps.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
track()
matplotlib.backends._backend_pdf_ps.CharacterTracker.track (self, font, s)
Record that string *s* is being typeset using font *font*.
Definition at line 109 of file _backend_pdf_ps.py.
References used.
track_glyph()
matplotlib.backends._backend_pdf_ps.CharacterTracker.track_glyph (self, font, glyph)
Record that codepoint *glyph* is being typeset using font *font*.
Definition at line 115 of file _backend_pdf_ps.py.
References used.
Member Data Documentation
used
dict matplotlib.backends._backend_pdf_ps.CharacterTracker.used = {}
Definition at line 107 of file _backend_pdf_ps.py.
Referenced by track(), and track_glyph().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/backends/_backend_pdf_ps.py