Code Cloning Analysis: sklearn.linear_model.tests.test_sgd Namespace Reference
sklearn.linear_model.tests.test_sgd Namespace Reference
Classes
class _SparseSGDClassifier
class _SparseSGDOneClassSVM
class _SparseSGDRegressor
Functions
_update_kwargs (kwargs)
SGDClassifier (**kwargs)
SGDRegressor (**kwargs)
SGDOneClassSVM (**kwargs)
SparseSGDClassifier (**kwargs)
SparseSGDRegressor (**kwargs)
SparseSGDOneClassSVM (**kwargs)
asgd (klass, X, y, eta, alpha, weight_init=None, intercept_init=0.0)
Common Test Case to classification and regression.
_test_warm_start (klass, X, Y, lr)
test_warm_start (klass, lr)
test_input_format (klass)
test_clone (klass)
test_plain_has_no_average_attr (klass)
test_late_onset_averaging_not_reached (klass)
test_late_onset_averaging_reached (klass)
test_early_stopping (klass)
test_adaptive_longer_than_constant (klass)
test_validation_set_not_used_for_training (klass)
test_n_iter_no_change (klass)
test_not_enough_sample_for_early_stopping (klass)
test_sgd_l1_ratio_not_used (Estimator, l1_ratio)
test_sgd_failing_penalty_validation (Estimator)
test_sgd_clf (klass)
Classification Test Case.
test_provide_coef (klass)
test_set_intercept_offset (klass, fit_params)
test_sgd_early_stopping_with_partial_fit (klass)
test_set_intercept_offset_binary (klass, fit_params)
test_average_binary_computed_correctly (klass)
test_set_intercept_to_intercept (klass)
test_sgd_at_least_two_labels (klass)
test_partial_fit_weight_class_balanced (klass)
test_sgd_multiclass (klass)
test_sgd_multiclass_average (klass)
test_sgd_multiclass_with_init_coef (klass)
test_sgd_multiclass_njobs (klass)
test_set_coef_multiclass (klass)
test_sgd_predict_proba_method_access (klass)
test_sgd_proba (klass)
test_sgd_l1 (klass)
test_class_weights (klass)
test_equal_class_weight (klass)
test_wrong_class_weight_label (klass)
test_weights_multiplied (klass)
test_balanced_weight (klass)
test_sample_weights (klass)
test_wrong_sample_weights (klass)
test_partial_fit_exception (klass)
test_partial_fit_binary (klass)
test_partial_fit_multiclass (klass)
test_partial_fit_multiclass_average (klass)
test_fit_then_partial_fit (klass)
test_partial_fit_equal_fit_classif (klass, lr)
test_regression_losses (klass)
test_warm_start_multiclass (klass)
test_multiple_fit (klass)
test_sgd_reg (klass)
Regression Test Case.
test_sgd_averaged_computed_correctly (klass)
test_sgd_averaged_partial_fit (klass)
test_average_sparse (klass)
test_sgd_least_squares_fit (klass)
test_sgd_epsilon_insensitive (klass)
test_sgd_huber_fit (klass)
test_elasticnet_convergence (klass)
test_partial_fit (klass)
test_partial_fit_equal_fit (klass, lr)
test_loss_function_epsilon (klass)
asgd_oneclass (klass, X, eta, nu, coef_init=None, offset_init=0.0)
SGD One Class SVM Test Case.
_test_warm_start_oneclass (klass, X, lr)
test_warm_start_oneclass (klass, lr)
test_clone_oneclass (klass)
test_partial_fit_oneclass (klass)
test_partial_fit_equal_fit_oneclass (klass, lr)
test_late_onset_averaging_reached_oneclass (klass)
test_sgd_averaged_computed_correctly_oneclass (klass)
test_sgd_averaged_partial_fit_oneclass (klass)
test_average_sparse_oneclass (klass)
test_sgd_oneclass ()
test_ocsvm_vs_sgdocsvm ()
test_l1_ratio ()
test_underflow_or_overlow ()
test_numerical_stability_large_gradient ()
test_large_regularization (penalty)
test_tol_parameter ()
_test_loss_common (loss_function, cases)
test_loss_hinge ()
test_gradient_squared_hinge ()
test_loss_modified_huber ()
test_loss_epsilon_insensitive ()
test_loss_squared_epsilon_insensitive ()
test_multi_thread_multi_class_and_early_stopping ()
test_multi_core_gridsearch_and_early_stopping ()
test_SGDClassifier_fit_for_all_backends (backend)
test_sgd_random_state (Estimator, global_random_seed)
test_validation_mask_correctly_subsets (monkeypatch)
test_sgd_error_on_zero_validation_weight ()
test_sgd_verbose (Estimator)
test_sgd_dtype_match (SGDEstimator, data_type)
test_sgd_numerical_consistency (SGDEstimator)
test_sgd_one_class_svm_estimator_type ()
Variables
X = np.array([[-2, -1], [-1, -1], [-1, -2], [1, 1], [1, 2], [2, 1]])
list Y = [1, 1, 1, 2, 2, 2]
T = np.array([[-1, -1], [2, 2], [3, 2]])
list true_result = [1, 2, 2]
X2
list Y2 = ["one"] * 3 + ["two"] * 3 + ["three"] * 3
T2 = np.array([[-1.5, 0.5], [1, 2], [0, -2]])
list true_result2 = ["one", "two", "three"]
X3
Y3 = np.array([1, 1, 1, 1, 2, 2, 2, 2])
X4
Y4 = np.array([1, 1, 1, 1, 2, 2, 2, 2])
iris = datasets.load_iris()
X5 = np.array([[-2, -1], [-1, -1], [-1, -2], [1, 1], [1, 2], [2, 1]])
list Y5 = [1, 1, 1, 2, 2, 2]
list true_result5 = [0, 1, 1]
Function Documentation
_test_loss_common()
sklearn.linear_model.tests.test_sgd._test_loss_common (loss_function, cases) protected
Definition at line 1879 of file test_sgd.py.
_test_warm_start()
sklearn.linear_model.tests.test_sgd._test_warm_start (klass, X, Y, lr) protected
Definition at line 223 of file test_sgd.py.
_test_warm_start_oneclass()
sklearn.linear_model.tests.test_sgd._test_warm_start_oneclass (klass, X, lr) protected
Definition at line 1474 of file test_sgd.py.
_update_kwargs()
sklearn.linear_model.tests.test_sgd._update_kwargs (kwargs) protected
Definition at line 32 of file test_sgd.py.
asgd()
sklearn.linear_model.tests.test_sgd.asgd (klass, X, y, eta, alpha, weight_init = None, intercept_init = 0.0)
Common Test Case to classification and regression.
Definition at line 189 of file test_sgd.py.
References asgd().
Referenced by asgd(), test_set_intercept_offset_binary(), and test_sgd_reg().
asgd_oneclass()
sklearn.linear_model.tests.test_sgd.asgd_oneclass (klass, X, eta, nu, coef_init = None, offset_init = 0.0)
SGD One Class SVM Test Case.
Definition at line 1435 of file test_sgd.py.
References asgd_oneclass().
Referenced by asgd_oneclass().
SGDClassifier()
sklearn.linear_model.tests.test_sgd.SGDClassifier (** kwargs)
Definition at line 89 of file test_sgd.py.
SGDOneClassSVM()
sklearn.linear_model.tests.test_sgd.SGDOneClassSVM (** kwargs)
Definition at line 99 of file test_sgd.py.
SGDRegressor()
sklearn.linear_model.tests.test_sgd.SGDRegressor (** kwargs)
Definition at line 94 of file test_sgd.py.
SparseSGDClassifier()
sklearn.linear_model.tests.test_sgd.SparseSGDClassifier (** kwargs)
Definition at line 104 of file test_sgd.py.
SparseSGDOneClassSVM()
sklearn.linear_model.tests.test_sgd.SparseSGDOneClassSVM (** kwargs)
Definition at line 114 of file test_sgd.py.
SparseSGDRegressor()
sklearn.linear_model.tests.test_sgd.SparseSGDRegressor (** kwargs)
Definition at line 109 of file test_sgd.py.
test_adaptive_longer_than_constant()
sklearn.linear_model.tests.test_sgd.test_adaptive_longer_than_constant (klass)
Definition at line 406 of file test_sgd.py.
test_average_binary_computed_correctly()
sklearn.linear_model.tests.test_sgd.test_average_binary_computed_correctly (klass)
Definition at line 585 of file test_sgd.py.
test_average_sparse()
sklearn.linear_model.tests.test_sgd.test_average_sparse (klass)
Definition at line 1245 of file test_sgd.py.
test_average_sparse_oneclass()
sklearn.linear_model.tests.test_sgd.test_average_sparse_oneclass (klass)
Definition at line 1646 of file test_sgd.py.
test_balanced_weight()
sklearn.linear_model.tests.test_sgd.test_balanced_weight (klass)
Definition at line 942 of file test_sgd.py.
test_class_weights()
sklearn.linear_model.tests.test_sgd.test_class_weights (klass)
Definition at line 879 of file test_sgd.py.
test_clone()
sklearn.linear_model.tests.test_sgd.test_clone (klass)
Definition at line 272 of file test_sgd.py.
test_clone_oneclass()
sklearn.linear_model.tests.test_sgd.test_clone_oneclass (klass)
Definition at line 1503 of file test_sgd.py.
test_early_stopping()
sklearn.linear_model.tests.test_sgd.test_early_stopping (klass)
Definition at line 392 of file test_sgd.py.
test_elasticnet_convergence()
sklearn.linear_model.tests.test_sgd.test_elasticnet_convergence (klass)
Definition at line 1356 of file test_sgd.py.
test_equal_class_weight()
sklearn.linear_model.tests.test_sgd.test_equal_class_weight (klass)
Definition at line 898 of file test_sgd.py.
test_fit_then_partial_fit()
sklearn.linear_model.tests.test_sgd.test_fit_then_partial_fit (klass)
Definition at line 1083 of file test_sgd.py.
test_gradient_squared_hinge()
sklearn.linear_model.tests.test_sgd.test_gradient_squared_hinge ()
Definition at line 1920 of file test_sgd.py.
test_input_format()
sklearn.linear_model.tests.test_sgd.test_input_format (klass)
Definition at line 258 of file test_sgd.py.
test_l1_ratio()
sklearn.linear_model.tests.test_sgd.test_l1_ratio ()
Definition at line 1733 of file test_sgd.py.
test_large_regularization()
sklearn.linear_model.tests.test_sgd.test_large_regularization (penalty)
Definition at line 1826 of file test_sgd.py.
test_late_onset_averaging_not_reached()
sklearn.linear_model.tests.test_sgd.test_late_onset_averaging_not_reached (klass)
Definition at line 325 of file test_sgd.py.
test_late_onset_averaging_reached()
sklearn.linear_model.tests.test_sgd.test_late_onset_averaging_reached (klass)
Definition at line 346 of file test_sgd.py.
test_late_onset_averaging_reached_oneclass()
sklearn.linear_model.tests.test_sgd.test_late_onset_averaging_reached_oneclass (klass)
Definition at line 1558 of file test_sgd.py.
test_loss_epsilon_insensitive()
sklearn.linear_model.tests.test_sgd.test_loss_epsilon_insensitive ()
Definition at line 1952 of file test_sgd.py.
test_loss_function_epsilon()
sklearn.linear_model.tests.test_sgd.test_loss_function_epsilon (klass)
Definition at line 1424 of file test_sgd.py.
test_loss_hinge()
sklearn.linear_model.tests.test_sgd.test_loss_hinge ()
Definition at line 1887 of file test_sgd.py.
test_loss_modified_huber()
sklearn.linear_model.tests.test_sgd.test_loss_modified_huber ()
Definition at line 1935 of file test_sgd.py.
test_loss_squared_epsilon_insensitive()
sklearn.linear_model.tests.test_sgd.test_loss_squared_epsilon_insensitive ()
Definition at line 1969 of file test_sgd.py.
test_multi_core_gridsearch_and_early_stopping()
sklearn.linear_model.tests.test_sgd.test_multi_core_gridsearch_and_early_stopping ()
Definition at line 2004 of file test_sgd.py.
test_multi_thread_multi_class_and_early_stopping()
sklearn.linear_model.tests.test_sgd.test_multi_thread_multi_class_and_early_stopping ()
Definition at line 1986 of file test_sgd.py.
test_multiple_fit()
sklearn.linear_model.tests.test_sgd.test_multiple_fit (klass)
Definition at line 1155 of file test_sgd.py.
test_n_iter_no_change()
sklearn.linear_model.tests.test_sgd.test_n_iter_no_change (klass)
Definition at line 461 of file test_sgd.py.
test_not_enough_sample_for_early_stopping()
sklearn.linear_model.tests.test_sgd.test_not_enough_sample_for_early_stopping (klass)
Definition at line 482 of file test_sgd.py.
test_numerical_stability_large_gradient()
sklearn.linear_model.tests.test_sgd.test_numerical_stability_large_gradient ()
Definition at line 1806 of file test_sgd.py.
test_ocsvm_vs_sgdocsvm()
sklearn.linear_model.tests.test_sgd.test_ocsvm_vs_sgdocsvm ()
Definition at line 1692 of file test_sgd.py.
test_partial_fit()
sklearn.linear_model.tests.test_sgd.test_partial_fit (klass)
Definition at line 1390 of file test_sgd.py.
test_partial_fit_binary()
sklearn.linear_model.tests.test_sgd.test_partial_fit_binary (klass)
Definition at line 1029 of file test_sgd.py.
test_partial_fit_equal_fit()
sklearn.linear_model.tests.test_sgd.test_partial_fit_equal_fit (klass, lr)
Definition at line 1408 of file test_sgd.py.
test_partial_fit_equal_fit_classif()
sklearn.linear_model.tests.test_sgd.test_partial_fit_equal_fit_classif (klass, lr)
Definition at line 1094 of file test_sgd.py.
test_partial_fit_equal_fit_oneclass()
sklearn.linear_model.tests.test_sgd.test_partial_fit_equal_fit_oneclass (klass, lr)
Definition at line 1538 of file test_sgd.py.
test_partial_fit_exception()
sklearn.linear_model.tests.test_sgd.test_partial_fit_exception (klass)
Definition at line 1021 of file test_sgd.py.
test_partial_fit_multiclass()
sklearn.linear_model.tests.test_sgd.test_partial_fit_multiclass (klass)
Definition at line 1050 of file test_sgd.py.
test_partial_fit_multiclass_average()
sklearn.linear_model.tests.test_sgd.test_partial_fit_multiclass_average (klass)
Definition at line 1068 of file test_sgd.py.
test_partial_fit_oneclass()
sklearn.linear_model.tests.test_sgd.test_partial_fit_oneclass (klass)
Definition at line 1517 of file test_sgd.py.
test_partial_fit_weight_class_balanced()
sklearn.linear_model.tests.test_sgd.test_partial_fit_weight_class_balanced (klass)
Definition at line 637 of file test_sgd.py.
test_plain_has_no_average_attr()
sklearn.linear_model.tests.test_sgd.test_plain_has_no_average_attr (klass)
Definition at line 296 of file test_sgd.py.
test_provide_coef()
sklearn.linear_model.tests.test_sgd.test_provide_coef (klass)
Check that the shape of `coef_init` is validated.
Definition at line 535 of file test_sgd.py.
test_regression_losses()
sklearn.linear_model.tests.test_sgd.test_regression_losses (klass)
Definition at line 1112 of file test_sgd.py.
test_sample_weights()
sklearn.linear_model.tests.test_sgd.test_sample_weights (klass)
Definition at line 989 of file test_sgd.py.
test_set_coef_multiclass()
sklearn.linear_model.tests.test_sgd.test_set_coef_multiclass (klass)
Definition at line 715 of file test_sgd.py.
test_set_intercept_offset()
sklearn.linear_model.tests.test_sgd.test_set_intercept_offset (klass, fit_params)
Check that `intercept_init` or `offset_init` is validated.
Definition at line 550 of file test_sgd.py.
test_set_intercept_offset_binary()
sklearn.linear_model.tests.test_sgd.test_set_intercept_offset_binary (klass, fit_params)
Check that we can pass a scaler with binary classification to
`intercept_init` or `offset_init`.
Definition at line 578 of file test_sgd.py.
References asgd().
test_set_intercept_to_intercept()
sklearn.linear_model.tests.test_sgd.test_set_intercept_to_intercept (klass)
Definition at line 619 of file test_sgd.py.
test_sgd_at_least_two_labels()
sklearn.linear_model.tests.test_sgd.test_sgd_at_least_two_labels (klass)
Definition at line 629 of file test_sgd.py.
test_sgd_averaged_computed_correctly()
sklearn.linear_model.tests.test_sgd.test_sgd_averaged_computed_correctly (klass)
Definition at line 1179 of file test_sgd.py.
test_sgd_averaged_computed_correctly_oneclass()
sklearn.linear_model.tests.test_sgd.test_sgd_averaged_computed_correctly_oneclass (klass)
Definition at line 1591 of file test_sgd.py.
test_sgd_averaged_partial_fit()
sklearn.linear_model.tests.test_sgd.test_sgd_averaged_partial_fit (klass)
Definition at line 1212 of file test_sgd.py.
test_sgd_averaged_partial_fit_oneclass()
sklearn.linear_model.tests.test_sgd.test_sgd_averaged_partial_fit_oneclass (klass)
Definition at line 1618 of file test_sgd.py.
test_sgd_clf()
sklearn.linear_model.tests.test_sgd.test_sgd_clf (klass)
Classification Test Case.
Definition at line 515 of file test_sgd.py.
test_sgd_dtype_match()
sklearn.linear_model.tests.test_sgd.test_sgd_dtype_match (SGDEstimator, data_type)
Definition at line 2154 of file test_sgd.py.
test_sgd_early_stopping_with_partial_fit()
sklearn.linear_model.tests.test_sgd.test_sgd_early_stopping_with_partial_fit (klass)
Check that we raise an error for `early_stopping` used with
`partial_fit`.
Definition at line 560 of file test_sgd.py.
test_sgd_epsilon_insensitive()
sklearn.linear_model.tests.test_sgd.test_sgd_epsilon_insensitive (klass)
Definition at line 1296 of file test_sgd.py.
test_sgd_error_on_zero_validation_weight()
sklearn.linear_model.tests.test_sgd.test_sgd_error_on_zero_validation_weight ()
Definition at line 2117 of file test_sgd.py.
test_sgd_failing_penalty_validation()
sklearn.linear_model.tests.test_sgd.test_sgd_failing_penalty_validation (Estimator)
Definition at line 502 of file test_sgd.py.
test_sgd_huber_fit()
sklearn.linear_model.tests.test_sgd.test_sgd_huber_fit (klass)
Definition at line 1332 of file test_sgd.py.
test_sgd_l1()
sklearn.linear_model.tests.test_sgd.test_sgd_l1 (klass)
Definition at line 842 of file test_sgd.py.
test_sgd_l1_ratio_not_used()
sklearn.linear_model.tests.test_sgd.test_sgd_l1_ratio_not_used (Estimator, l1_ratio)
Check that l1_ratio is not used when penalty is not 'elasticnet'
Definition at line 491 of file test_sgd.py.
test_sgd_least_squares_fit()
sklearn.linear_model.tests.test_sgd.test_sgd_least_squares_fit (klass)
Definition at line 1272 of file test_sgd.py.
test_sgd_multiclass()
sklearn.linear_model.tests.test_sgd.test_sgd_multiclass (klass)
Definition at line 654 of file test_sgd.py.
test_sgd_multiclass_average()
sklearn.linear_model.tests.test_sgd.test_sgd_multiclass_average (klass)
Definition at line 665 of file test_sgd.py.
test_sgd_multiclass_njobs()
sklearn.linear_model.tests.test_sgd.test_sgd_multiclass_njobs (klass)
Definition at line 704 of file test_sgd.py.
test_sgd_multiclass_with_init_coef()
sklearn.linear_model.tests.test_sgd.test_sgd_multiclass_with_init_coef (klass)
Definition at line 693 of file test_sgd.py.
test_sgd_numerical_consistency()
sklearn.linear_model.tests.test_sgd.test_sgd_numerical_consistency (SGDEstimator)
Definition at line 2173 of file test_sgd.py.
test_sgd_one_class_svm_estimator_type()
sklearn.linear_model.tests.test_sgd.test_sgd_one_class_svm_estimator_type ()
Check that SGDOneClassSVM has the correct estimator type.
Non-regression test for if the mixin was not on the left.
Definition at line 2189 of file test_sgd.py.
test_sgd_oneclass()
sklearn.linear_model.tests.test_sgd.test_sgd_oneclass ()
Definition at line 1670 of file test_sgd.py.
test_sgd_predict_proba_method_access()
sklearn.linear_model.tests.test_sgd.test_sgd_predict_proba_method_access (klass)
Definition at line 736 of file test_sgd.py.
test_sgd_proba()
sklearn.linear_model.tests.test_sgd.test_sgd_proba (klass)
Definition at line 770 of file test_sgd.py.
test_sgd_random_state()
sklearn.linear_model.tests.test_sgd.test_sgd_random_state (Estimator, global_random_seed)
Definition at line 2058 of file test_sgd.py.
test_sgd_reg()
sklearn.linear_model.tests.test_sgd.test_sgd_reg (klass)
Regression Test Case.
Definition at line 1171 of file test_sgd.py.
References asgd().
test_sgd_verbose()
sklearn.linear_model.tests.test_sgd.test_sgd_verbose (Estimator)
non-regression test for gh #25249
Definition at line 2137 of file test_sgd.py.
test_SGDClassifier_fit_for_all_backends()
sklearn.linear_model.tests.test_sgd.test_SGDClassifier_fit_for_all_backends (backend)
Definition at line 2020 of file test_sgd.py.
test_tol_parameter()
sklearn.linear_model.tests.test_sgd.test_tol_parameter ()
Definition at line 1843 of file test_sgd.py.
test_underflow_or_overlow()
sklearn.linear_model.tests.test_sgd.test_underflow_or_overlow ()
Definition at line 1768 of file test_sgd.py.
test_validation_mask_correctly_subsets()
sklearn.linear_model.tests.test_sgd.test_validation_mask_correctly_subsets (monkeypatch)
Test that data passed to validation callback correctly subsets.
Non-regression test for #23255.
Definition at line 2093 of file test_sgd.py.
test_validation_set_not_used_for_training()
sklearn.linear_model.tests.test_sgd.test_validation_set_not_used_for_training (klass)
Definition at line 417 of file test_sgd.py.
test_warm_start()
sklearn.linear_model.tests.test_sgd.test_warm_start (klass, lr)
Definition at line 251 of file test_sgd.py.
test_warm_start_multiclass()
sklearn.linear_model.tests.test_sgd.test_warm_start_multiclass (klass)
Definition at line 1150 of file test_sgd.py.
test_warm_start_oneclass()
sklearn.linear_model.tests.test_sgd.test_warm_start_oneclass (klass, lr)
Definition at line 1498 of file test_sgd.py.
test_weights_multiplied()
sklearn.linear_model.tests.test_sgd.test_weights_multiplied (klass)
Definition at line 923 of file test_sgd.py.
test_wrong_class_weight_label()
sklearn.linear_model.tests.test_sgd.test_wrong_class_weight_label (klass)
Definition at line 915 of file test_sgd.py.
test_wrong_sample_weights()
sklearn.linear_model.tests.test_sgd.test_wrong_sample_weights (klass)
Definition at line 1009 of file test_sgd.py.
Variable Documentation
iris
sklearn.linear_model.tests.test_sgd.iris = datasets.load_iris()
Definition at line 175 of file test_sgd.py.
T
sklearn.linear_model.tests.test_sgd.T = np.array([[-1, -1], [2, 2], [3, 2]])
Definition at line 124 of file test_sgd.py.
T2
sklearn.linear_model.tests.test_sgd.T2 = np.array([[-1.5, 0.5], [1, 2], [0, -2]])
Definition at line 142 of file test_sgd.py.
true_result
list sklearn.linear_model.tests.test_sgd.true_result = [1, 2, 2]
Definition at line 125 of file test_sgd.py.
true_result2
list sklearn.linear_model.tests.test_sgd.true_result2 = ["one", "two", "three"]
Definition at line 143 of file test_sgd.py.
true_result5
list sklearn.linear_model.tests.test_sgd.true_result5 = [0, 1, 1]
Definition at line 180 of file test_sgd.py.
X
sklearn.linear_model.tests.test_sgd.X = np.array([[-2, -1], [-1, -1], [-1, -2], [1, 1], [1, 2], [2, 1]])
Definition at line 122 of file test_sgd.py.
X2
sklearn.linear_model.tests.test_sgd.X2
Initial value:
=  np.array(
    [
        [-1, 1],
        [-0.75, 0.5],
        [-1.5, 1.5],
        [1, 1],
        [0.75, 0.5],
        [1.5, 1.5],
        [-1, -1],
        [0, -0.5],
        [1, -1],
    ]
)
Definition at line 128 of file test_sgd.py.
X3
sklearn.linear_model.tests.test_sgd.X3
Initial value:
=  np.array(
    [
        [1, 1, 0, 0, 0, 0],
        [1, 1, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 1, 1],
        [0, 0, 0, 0, 1, 1],
        [0, 0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0, 0],
    ]
)
Definition at line 146 of file test_sgd.py.
X4
sklearn.linear_model.tests.test_sgd.X4
Initial value:
=  np.array(
    [
        [1, 0.9, 0.8, 0, 0, 0],
        [1, 0.84, 0.98, 0, 0, 0],
        [1, 0.96, 0.88, 0, 0, 0],
        [1, 0.91, 0.99, 0, 0, 0],
        [0, 0, 0, 0.89, 0.91, 1],
        [0, 0, 0, 0.79, 0.84, 1],
        [0, 0, 0, 0.91, 0.95, 1],
        [0, 0, 0, 0.93, 1, 1],
    ]
)
Definition at line 161 of file test_sgd.py.
X5
sklearn.linear_model.tests.test_sgd.X5 = np.array([[-2, -1], [-1, -1], [-1, -2], [1, 1], [1, 2], [2, 1]])
Definition at line 178 of file test_sgd.py.
Y
list sklearn.linear_model.tests.test_sgd.Y = [1, 1, 1, 2, 2, 2]
Definition at line 123 of file test_sgd.py.
Y2
list sklearn.linear_model.tests.test_sgd.Y2 = ["one"] * 3 + ["two"] * 3 + ["three"] * 3
Definition at line 141 of file test_sgd.py.
Y3
sklearn.linear_model.tests.test_sgd.Y3 = np.array([1, 1, 1, 1, 2, 2, 2, 2])
Definition at line 158 of file test_sgd.py.
Y4
sklearn.linear_model.tests.test_sgd.Y4 = np.array([1, 1, 1, 1, 2, 2, 2, 2])
Definition at line 173 of file test_sgd.py.
Y5
list sklearn.linear_model.tests.test_sgd.Y5 = [1, 1, 1, 2, 2, 2]
Definition at line 179 of file test_sgd.py.