Code Cloning Analysis: sklearn.utils._testing.MinimalTransformer Class Reference
sklearn.utils._testing.MinimalTransformer Class Reference
Public Member Functions
__init__ (self, param=None)
get_params (self, deep=True)
set_params (self, **params)
fit (self, X, y=None)
transform (self, X, y=None)
fit_transform (self, X, y=None)
__sklearn_tags__ (self)
Public Attributes
param = param
bool is_fitted_ = True
Detailed Description
Minimal transformer implementation without inheriting from
BaseEstimator.
This estimator should be tested with:
* `check_estimator` in `test_estimator_checks.py`;
* within a `Pipeline` in `test_pipeline.py`;
* within a `SearchCV` in `test_search.py`.
Definition at line 1264 of file _testing.py.
Constructor & Destructor Documentation
__init__()
sklearn.utils._testing.MinimalTransformer.__init__ (self, param = None)
Definition at line 1275 of file _testing.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params().
Member Function Documentation
__sklearn_tags__()
sklearn.utils._testing.MinimalTransformer.__sklearn_tags__ (self)
Definition at line 1299 of file _testing.py.
fit()
sklearn.utils._testing.MinimalTransformer.fit (self, X, y = None)
Definition at line 1286 of file _testing.py.
Referenced by sklearn.cluster._kmeans._BaseKMeans.fit_predict(), sklearn.cluster._kmeans._BaseKMeans.fit_transform(), and sklearn.utils.tests.test_estimator_checks.SparseTransformer.fit_transform().
fit_transform()
sklearn.utils._testing.MinimalTransformer.fit_transform (self, X, y = None)
Definition at line 1296 of file _testing.py.
get_params()
sklearn.utils._testing.MinimalTransformer.get_params (self, deep = True)
Definition at line 1278 of file _testing.py.
set_params()
sklearn.utils._testing.MinimalTransformer.set_params (self, ** params)
Definition at line 1281 of file _testing.py.
transform()
sklearn.utils._testing.MinimalTransformer.transform (self, X, y = None)
Definition at line 1291 of file _testing.py.
Referenced by PIL.ImageCms.Flags.GRIDPOINTS(), and sklearn.ensemble._stacking._BaseStacking.predict().
Member Data Documentation
is_fitted_
bool sklearn.utils._testing.MinimalTransformer.is_fitted_ = True
Definition at line 1288 of file _testing.py.
param
sklearn.utils._testing.MinimalTransformer.param = param
Definition at line 1276 of file _testing.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/sklearn/utils/_testing.py