Code Cloning Analysis: matplotlib.ticker.LinearLocator Class Reference
matplotlib.ticker.LinearLocator Class Reference
Public Member Functions
__init__ (self, numticks=None, presets=None)
numticks (self)
numticks (self, numticks)
set_params (self, numticks=None, presets=None)
__call__ (self)
tick_values (self, vmin, vmax)
view_limits (self, vmin, vmax)
Public Member Functions inherited from matplotlib.ticker.Locator
__call__ (self)
raise_if_exceeds (self, locs)
nonsingular (self, v0, v1)
Public Member Functions inherited from matplotlib.ticker.TickHelper
set_axis (self, axis)
create_dummy_axis (self, **kwargs)
Public Attributes
int numticks = numticks
dict presets = {}
Protected Attributes
_numticks = numticks
Additional Inherited Members
Static Public Attributes inherited from matplotlib.ticker.Locator
int MAXTICKS = 1000
Static Public Attributes inherited from matplotlib.ticker.TickHelper
axis = None
Detailed Description
Place ticks at evenly spaced values.
The first time this function is called it will try to set the
number of ticks to make a nice tick partitioning.  Thereafter, the
number of ticks will be fixed so that interactive navigation will
be nice
Definition at line 1833 of file ticker.py.
Constructor & Destructor Documentation
__init__()
matplotlib.ticker.LinearLocator.__init__ (self, numticks = None, presets = None)
Parameters
----------
numticks : int or None, default None
    Number of ticks. If None, *numticks* = 11.
presets : dict or None, default: None
    Dictionary mapping ``(vmin, vmax)`` to an array of locations.
    Overrides *numticks* if there is an entry for the current
    ``(vmin, vmax)``.
Definition at line 1843 of file ticker.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__call__()
matplotlib.ticker.LinearLocator.__call__ (self)
Return the locations of the ticks.
Definition at line 1876 of file ticker.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), and scipy.interpolate._fitpack2.SphereBivariateSpline.ev().
numticks() [1/2]
matplotlib.ticker.LinearLocator.numticks (self)
Definition at line 1861 of file ticker.py.
numticks() [2/2]
matplotlib.ticker.LinearLocator.numticks (self, numticks)
Definition at line 1866 of file ticker.py.
set_params()
matplotlib.ticker.LinearLocator.set_params (self, numticks = None, presets = None)
Set parameters within this locator.
Reimplemented from matplotlib.ticker.Locator.
Definition at line 1869 of file ticker.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.theta().
tick_values()
matplotlib.ticker.LinearLocator.tick_values (self, vmin, vmax)
Return the values of the located ticks given **vmin** and **vmax**.
.. note::
    To get tick locations with the vmin and vmax values defined
    automatically for the associated ``axis`` simply call
    the Locator instance::
        >>> print(type(loc))
        <type 'Locator'>
        >>> print(loc())
        [1, 2, 3, 4]
Reimplemented from matplotlib.ticker.Locator.
Definition at line 1881 of file ticker.py.
view_limits()
matplotlib.ticker.LinearLocator.view_limits (self, vmin, vmax)
Try to choose the view limits intelligently.
Reimplemented from matplotlib.ticker.Locator.
Definition at line 1893 of file ticker.py.
Member Data Documentation
_numticks
matplotlib.ticker.LinearLocator._numticks = numticks protected
Definition at line 1867 of file ticker.py.
numticks
int matplotlib.ticker.LinearLocator.numticks = numticks
Definition at line 1854 of file ticker.py.
presets
dict matplotlib.ticker.LinearLocator.presets = {}
Definition at line 1856 of file ticker.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/ticker.py