Code Cloning Analysis: numpy.lib.index_tricks.ndindex Class Reference
numpy.lib.index_tricks.ndindex Class Reference
Public Member Functions
__init__ (self, *shape)
__iter__ (self)
ndincr (self)
__next__ (self)
Protected Attributes
_it
Detailed Description
An N-dimensional iterator object to index arrays.
Given the shape of an array, an `ndindex` instance iterates over
the N-dimensional index of the array. At each iteration a tuple
of indices is returned, the last dimension is iterated over first.
Parameters
----------
shape : ints, or a single tuple of ints
    The size of each dimension of the array can be passed as
    individual parameters or as the elements of a tuple.
See Also
--------
ndenumerate, flatiter
Examples
--------
Dimensions as individual arguments
>>> for index in np.ndindex(3, 2, 1):
...     print(index)
(0, 0, 0)
(0, 1, 0)
(1, 0, 0)
(1, 1, 0)
(2, 0, 0)
(2, 1, 0)
Same dimensions - but in a tuple ``(3, 2, 1)``
>>> for index in np.ndindex((3, 2, 1)):
...     print(index)
(0, 0, 0)
(0, 1, 0)
(1, 0, 0)
(1, 1, 0)
(2, 0, 0)
(2, 1, 0)
Definition at line 619 of file index_tricks.py.
Constructor & Destructor Documentation
__init__()
numpy.lib.index_tricks.ndindex.__init__ (self, * shape)
Definition at line 663 of file index_tricks.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__iter__()
numpy.lib.index_tricks.ndindex.__iter__ (self)
Definition at line 671 of file index_tricks.py.
__next__()
numpy.lib.index_tricks.ndindex.__next__ (self)
Standard iterator method, updates the index and returns the index
tuple.
Returns
-------
val : tuple of ints
    Returns a tuple containing the indices of the current
    iteration.
Definition at line 690 of file index_tricks.py.
References _it.
ndincr()
numpy.lib.index_tricks.ndindex.ndincr (self)
Increment the multi-dimensional index by one.
This method is for backward compatibility only: do not use.
.. deprecated:: 1.20.0
    This method has been advised against since numpy 1.8.0, but only
    started emitting DeprecationWarning as of this version.
Definition at line 674 of file index_tricks.py.
Member Data Documentation
_it
numpy.lib.index_tricks.ndindex._it protected
Initial value:
=  _nx.nditer(x, flags=['multi_index', 'zerosize_ok'],
                              order='C')
Definition at line 668 of file index_tricks.py.
Referenced by __next__().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/lib/index_tricks.py