Code Cloning Analysis: numpy.core.tests.test_multiarray.TestRepeat Class Reference
numpy.core.tests.test_multiarray.TestRepeat Class Reference
Public Member Functions
setup_method (self)
test_basic (self)
test_broadcast1 (self)
test_axis_spec (self)
test_broadcast2 (self)
Public Attributes
m = np.array([1, 2, 3, 4, 5, 6])
m_rect = self.m.reshape((2, 3))
Detailed Description
Definition at line 7397 of file test_multiarray.py.
Member Function Documentation
setup_method()
numpy.core.tests.test_multiarray.TestRepeat.setup_method (self)
Definition at line 7398 of file test_multiarray.py.
test_axis_spec()
numpy.core.tests.test_multiarray.TestRepeat.test_axis_spec (self)
Definition at line 7412 of file test_multiarray.py.
test_basic()
numpy.core.tests.test_multiarray.TestRepeat.test_basic (self)
Definition at line 7402 of file test_multiarray.py.
test_broadcast1()
numpy.core.tests.test_multiarray.TestRepeat.test_broadcast1 (self)
Definition at line 7407 of file test_multiarray.py.
test_broadcast2()
numpy.core.tests.test_multiarray.TestRepeat.test_broadcast2 (self)
Definition at line 7422 of file test_multiarray.py.
Member Data Documentation
m
numpy.core.tests.test_multiarray.TestRepeat.m = np.array([1, 2, 3, 4, 5, 6])
Definition at line 7399 of file test_multiarray.py.
Referenced by scipy.spatial._kdtree.Rectangle.__init__(), scipy.stats._morestats._ABW.__init__(), scipy.stats._morestats._ABW._recalc(), and scipy.signal._czt.CZT.points().
m_rect
numpy.core.tests.test_multiarray.TestRepeat.m_rect = self.m.reshape((2, 3))
Definition at line 7400 of file test_multiarray.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/core/tests/test_multiarray.py