Code Cloning Analysis: scipy.optimize._linprog_util Namespace Reference
scipy.optimize._linprog_util Namespace Reference
Functions
_check_sparse_inputs (options, meth, A_ub, A_eq)
_format_A_constraints (A, n_x, sparse_lhs=False)
_format_b_constraints (b)
_clean_inputs (lp)
_presolve (lp, rr, rr_method, tol=1e-9)
_parse_linprog (lp, options, meth)
_get_Abc (lp, c0)
_round_to_power_of_two (x)
_autoscale (A, b, c, x0)
_unscale (x, C, b_scale)
_display_summary (message, status, fun, iteration)
_postsolve (x, postsolve_args, complete=False)
_check_result (x, fun, status, slack, con, bounds, tol, message, integrality)
Variables
_LPProblem
__defaults__
__doc__
Detailed Description
Method agnostic utility functions for linear progamming
Function Documentation
_autoscale()
scipy.optimize._linprog_util._autoscale (A, b, c, x0) protected
Scales the problem according to equilibration from [12].
Also normalizes the right hand side vector by its maximum element.
Definition at line 1235 of file _linprog_util.py.
References _round_to_power_of_two().
_check_result()
scipy.optimize._linprog_util._check_result (x, fun, status, slack, con, bounds, tol, message, integrality) protected
Check the validity of the provided solution.
A valid (optimal) solution satisfies all bounds, all slack variables are
negative and all equality constraint residuals are strictly non-zero.
Further, the lower-bounds, upper-bounds, slack and residuals contain
no nan values.
Parameters
----------
x : 1-D array
    Solution vector to original linear programming problem
fun: float
    optimal objective value for original problem
status : int
    An integer representing the exit status of the optimization::
         0 : Optimization terminated successfully
         1 : Iteration limit reached
         2 : Problem appears to be infeasible
         3 : Problem appears to be unbounded
         4 : Serious numerical difficulties encountered
slack : 1-D array
    The (non-negative) slack in the upper bound constraints, that is,
    ``b_ub - A_ub @ x``
con : 1-D array
    The (nominally zero) residuals of the equality constraints, that is,
    ``b - A_eq @ x``
bounds : 2D array
    The bounds on the original variables ``x``
message : str
    A string descriptor of the exit status of the optimization.
tol : float
    Termination tolerance; see [1]_ Section 4.5.
Returns
-------
status : int
    An integer representing the exit status of the optimization::
         0 : Optimization terminated successfully
         1 : Iteration limit reached
         2 : Problem appears to be infeasible
         3 : Problem appears to be unbounded
         4 : Serious numerical difficulties encountered
message : str
    A string descriptor of the exit status of the optimization.
Definition at line 1419 of file _linprog_util.py.
_check_sparse_inputs()
scipy.optimize._linprog_util._check_sparse_inputs (options, meth, A_ub, A_eq) protected
Check the provided ``A_ub`` and ``A_eq`` matrices conform to the specified
optional sparsity variables.
Parameters
----------
A_ub : 2-D array, optional
    2-D array such that ``A_ub @ x`` gives the values of the upper-bound
    inequality constraints at ``x``.
A_eq : 2-D array, optional
    2-D array such that ``A_eq @ x`` gives the values of the equality
    constraints at ``x``.
options : dict
    A dictionary of solver options. All methods accept the following
    generic options:
        maxiter : int
            Maximum number of iterations to perform.
        disp : bool
            Set to True to print convergence messages.
    For method-specific options, see :func:`show_options('linprog')`.
method : str, optional
    The algorithm used to solve the standard form problem.
Returns
-------
A_ub : 2-D array, optional
    2-D array such that ``A_ub @ x`` gives the values of the upper-bound
    inequality constraints at ``x``.
A_eq : 2-D array, optional
    2-D array such that ``A_eq @ x`` gives the values of the equality
    constraints at ``x``.
options : dict
    A dictionary of solver options. All methods accept the following
    generic options:
        maxiter : int
            Maximum number of iterations to perform.
        disp : bool
            Set to True to print convergence messages.
    For method-specific options, see :func:`show_options('linprog')`.
Definition at line 91 of file _linprog_util.py.
Referenced by _parse_linprog().
_clean_inputs()
scipy.optimize._linprog_util._clean_inputs (lp) protected
Given user inputs for a linear programming problem, return the
objective vector, upper bound constraints, equality constraints,
and simple bounds in a preferred format.
Parameters
----------
lp : A `scipy.optimize._linprog_util._LPProblem` consisting of the following fields:
    c : 1D array
        The coefficients of the linear objective function to be minimized.
    A_ub : 2D array, optional
        The inequality constraint matrix. Each row of ``A_ub`` specifies the
        coefficients of a linear inequality constraint on ``x``.
    b_ub : 1D array, optional
        The inequality constraint vector. Each element represents an
        upper bound on the corresponding value of ``A_ub @ x``.
    A_eq : 2D array, optional
        The equality constraint matrix. Each row of ``A_eq`` specifies the
        coefficients of a linear equality constraint on ``x``.
    b_eq : 1D array, optional
        The equality constraint vector. Each element of ``A_eq @ x`` must equal
        the corresponding element of ``b_eq``.
    bounds : various valid formats, optional
        The bounds of ``x``, as ``min`` and ``max`` pairs.
        If bounds are specified for all N variables separately, valid formats are:
        * a 2D array (2 x N or N x 2);
        * a sequence of N sequences, each with 2 values.
        If all variables have the same bounds, a single pair of values can
        be specified. Valid formats are:
        * a sequence with 2 scalar values;
        * a sequence with a single element containing 2 scalar values.
        If all variables have a lower bound of 0 and no upper bound, the bounds
        parameter can be omitted (or given as None).
    x0 : 1D array, optional
        Guess values of the decision variables, which will be refined by
        the optimization algorithm. This argument is currently used only by the
        'revised simplex' method, and can only be used if `x0` represents a
        basic feasible solution.
Returns
-------
lp : A `scipy.optimize._linprog_util._LPProblem` consisting of the following fields:
    c : 1D array
        The coefficients of the linear objective function to be minimized.
    A_ub : 2D array, optional
        The inequality constraint matrix. Each row of ``A_ub`` specifies the
        coefficients of a linear inequality constraint on ``x``.
    b_ub : 1D array, optional
        The inequality constraint vector. Each element represents an
        upper bound on the corresponding value of ``A_ub @ x``.
    A_eq : 2D array, optional
        The equality constraint matrix. Each row of ``A_eq`` specifies the
        coefficients of a linear equality constraint on ``x``.
    b_eq : 1D array, optional
        The equality constraint vector. Each element of ``A_eq @ x`` must equal
        the corresponding element of ``b_eq``.
    bounds : 2D array
        The bounds of ``x``, as ``min`` and ``max`` pairs, one for each of the N
        elements of ``x``. The N x 2 array contains lower bounds in the first
        column and upper bounds in the 2nd. Unbounded variables have lower
        bound -np.inf and/or upper bound np.inf.
    x0 : 1D array, optional
        Guess values of the decision variables, which will be refined by
        the optimization algorithm. This argument is currently used only by the
        'revised simplex' method, and can only be used if `x0` represents a
        basic feasible solution.
Definition at line 213 of file _linprog_util.py.
References _format_A_constraints(), and _format_b_constraints().
Referenced by _parse_linprog().
_display_summary()
scipy.optimize._linprog_util._display_summary (message, status, fun, iteration) protected
Print the termination summary of the linear program
Parameters
----------
message : str
        A string descriptor of the exit status of the optimization.
status : int
    An integer representing the exit status of the optimization::
            0 : Optimization terminated successfully
            1 : Iteration limit reached
            2 : Problem appears to be infeasible
            3 : Problem appears to be unbounded
            4 : Serious numerical difficulties encountered
fun : float
    Value of the objective function.
iteration : iteration
    The number of iterations performed.
Definition at line 1288 of file _linprog_util.py.
_format_A_constraints()
scipy.optimize._linprog_util._format_A_constraints (A, n_x, sparse_lhs = False) protected
Format the left hand side of the constraints to a 2-D array
Parameters
----------
A : 2-D array
    2-D array such that ``A @ x`` gives the values of the upper-bound
    (in)equality constraints at ``x``.
n_x : int
    The number of variables in the linear programming problem.
sparse_lhs : bool
    Whether either of `A_ub` or `A_eq` are sparse. If true return a
    coo_matrix instead of a numpy array.
Returns
-------
np.ndarray or sparse.coo_matrix
    2-D array such that ``A @ x`` gives the values of the upper-bound
    (in)equality constraints at ``x``.
Definition at line 160 of file _linprog_util.py.
Referenced by _clean_inputs().
_format_b_constraints()
scipy.optimize._linprog_util._format_b_constraints (b) protected
Format the upper bounds of the constraints to a 1-D array
Parameters
----------
b : 1-D array
    1-D array of values representing the upper-bound of each (in)equality
    constraint (row) in ``A``.
Returns
-------
1-D np.array
    1-D array of values representing the upper-bound of each (in)equality
    constraint (row) in ``A``.
Definition at line 191 of file _linprog_util.py.
Referenced by _clean_inputs().
_get_Abc()
scipy.optimize._linprog_util._get_Abc (lp, c0) protected
Given a linear programming problem of the form:
Minimize::
    c @ x
Subject to::
    A_ub @ x <= b_ub
    A_eq @ x == b_eq
     lb <= x <= ub
where ``lb = 0`` and ``ub = None`` unless set in ``bounds``.
Return the problem in standard form:
Minimize::
    c @ x
Subject to::
    A @ x == b
        x >= 0
by adding slack variables and making variable substitutions as necessary.
Parameters
----------
lp : A `scipy.optimize._linprog_util._LPProblem` consisting of the following fields:
    c : 1D array
        The coefficients of the linear objective function to be minimized.
    A_ub : 2D array, optional
        The inequality constraint matrix. Each row of ``A_ub`` specifies the
        coefficients of a linear inequality constraint on ``x``.
    b_ub : 1D array, optional
        The inequality constraint vector. Each element represents an
        upper bound on the corresponding value of ``A_ub @ x``.
    A_eq : 2D array, optional
        The equality constraint matrix. Each row of ``A_eq`` specifies the
        coefficients of a linear equality constraint on ``x``.
    b_eq : 1D array, optional
        The equality constraint vector. Each element of ``A_eq @ x`` must equal
        the corresponding element of ``b_eq``.
    bounds : 2D array
        The bounds of ``x``, lower bounds in the 1st column, upper
        bounds in the 2nd column. The bounds are possibly tightened
        by the presolve procedure.
    x0 : 1D array, optional
        Guess values of the decision variables, which will be refined by
        the optimization algorithm. This argument is currently used only by the
        'revised simplex' method, and can only be used if `x0` represents a
        basic feasible solution.
c0 : float
    Constant term in objective function due to fixed (and eliminated)
    variables.
Returns
-------
A : 2-D array
    2-D array such that ``A`` @ ``x``, gives the values of the equality
    constraints at ``x``.
b : 1-D array
    1-D array of values representing the RHS of each equality constraint
    (row) in A (for standard form problem).
c : 1-D array
    Coefficients of the linear objective function to be minimized (for
    standard form problem).
c0 : float
    Constant term in objective function due to fixed (and eliminated)
    variables.
x0 : 1-D array
    Starting values of the independent variables, which will be refined by
    the optimization algorithm
References
----------
.. [9] Bertsimas, Dimitris, and J. Tsitsiklis. "Introduction to linear
       programming." Athena Scientific 1 (1997): 997.
Definition at line 1030 of file _linprog_util.py.
_parse_linprog()
scipy.optimize._linprog_util._parse_linprog (lp, options, meth) protected
Parse the provided linear programming problem
``_parse_linprog`` employs two main steps ``_check_sparse_inputs`` and
``_clean_inputs``. ``_check_sparse_inputs`` checks for sparsity in the
provided constraints (``A_ub`` and ``A_eq) and if these match the provided
sparsity optional values.
``_clean inputs`` checks of the provided inputs. If no violations are
identified the objective vector, upper bound constraints, equality
constraints, and simple bounds are returned in the expected format.
Parameters
----------
lp : A `scipy.optimize._linprog_util._LPProblem` consisting of the following fields:
    c : 1D array
        The coefficients of the linear objective function to be minimized.
    A_ub : 2D array, optional
        The inequality constraint matrix. Each row of ``A_ub`` specifies the
        coefficients of a linear inequality constraint on ``x``.
    b_ub : 1D array, optional
        The inequality constraint vector. Each element represents an
        upper bound on the corresponding value of ``A_ub @ x``.
    A_eq : 2D array, optional
        The equality constraint matrix. Each row of ``A_eq`` specifies the
        coefficients of a linear equality constraint on ``x``.
    b_eq : 1D array, optional
        The equality constraint vector. Each element of ``A_eq @ x`` must equal
        the corresponding element of ``b_eq``.
    bounds : various valid formats, optional
        The bounds of ``x``, as ``min`` and ``max`` pairs.
        If bounds are specified for all N variables separately, valid formats are:
        * a 2D array (2 x N or N x 2);
        * a sequence of N sequences, each with 2 values.
        If all variables have the same bounds, a single pair of values can
        be specified. Valid formats are:
        * a sequence with 2 scalar values;
        * a sequence with a single element containing 2 scalar values.
        If all variables have a lower bound of 0 and no upper bound, the bounds
        parameter can be omitted (or given as None).
    x0 : 1D array, optional
        Guess values of the decision variables, which will be refined by
        the optimization algorithm. This argument is currently used only by the
        'revised simplex' method, and can only be used if `x0` represents a
        basic feasible solution.
options : dict
    A dictionary of solver options. All methods accept the following
    generic options:
        maxiter : int
            Maximum number of iterations to perform.
        disp : bool
            Set to True to print convergence messages.
    For method-specific options, see :func:`show_options('linprog')`.
Returns
-------
lp : A `scipy.optimize._linprog_util._LPProblem` consisting of the following fields:
    c : 1D array
        The coefficients of the linear objective function to be minimized.
    A_ub : 2D array, optional
        The inequality constraint matrix. Each row of ``A_ub`` specifies the
        coefficients of a linear inequality constraint on ``x``.
    b_ub : 1D array, optional
        The inequality constraint vector. Each element represents an
        upper bound on the corresponding value of ``A_ub @ x``.
    A_eq : 2D array, optional
        The equality constraint matrix. Each row of ``A_eq`` specifies the
        coefficients of a linear equality constraint on ``x``.
    b_eq : 1D array, optional
        The equality constraint vector. Each element of ``A_eq @ x`` must equal
        the corresponding element of ``b_eq``.
    bounds : 2D array
        The bounds of ``x``, as ``min`` and ``max`` pairs, one for each of the N
        elements of ``x``. The N x 2 array contains lower bounds in the first
        column and upper bounds in the 2nd. Unbounded variables have lower
        bound -np.inf and/or upper bound np.inf.
    x0 : 1D array, optional
        Guess values of the decision variables, which will be refined by
        the optimization algorithm. This argument is currently used only by the
        'revised simplex' method, and can only be used if `x0` represents a
        basic feasible solution.
options : dict, optional
    A dictionary of solver options. All methods accept the following
    generic options:
        maxiter : int
            Maximum number of iterations to perform.
        disp : bool
            Set to True to print convergence messages.
    For method-specific options, see :func:`show_options('linprog')`.
Definition at line 919 of file _linprog_util.py.
References _check_sparse_inputs(), and _clean_inputs().
_postsolve()
scipy.optimize._linprog_util._postsolve (x, postsolve_args, complete = False) protected
Given solution x to presolved, standard form linear program x, add
fixed variables back into the problem and undo the variable substitutions
to get solution to original linear program. Also, calculate the objective
function value, slack in original upper bound constraints, and residuals
in original equality constraints.
Parameters
----------
x : 1-D array
    Solution vector to the standard-form problem.
postsolve_args : tuple
    Data needed by _postsolve to convert the solution to the standard-form
    problem into the solution to the original problem, including:
lp : A `scipy.optimize._linprog_util._LPProblem` consisting of the following fields:
    c : 1D array
        The coefficients of the linear objective function to be minimized.
    A_ub : 2D array, optional
        The inequality constraint matrix. Each row of ``A_ub`` specifies the
        coefficients of a linear inequality constraint on ``x``.
    b_ub : 1D array, optional
        The inequality constraint vector. Each element represents an
        upper bound on the corresponding value of ``A_ub @ x``.
    A_eq : 2D array, optional
        The equality constraint matrix. Each row of ``A_eq`` specifies the
        coefficients of a linear equality constraint on ``x``.
    b_eq : 1D array, optional
        The equality constraint vector. Each element of ``A_eq @ x`` must equal
        the corresponding element of ``b_eq``.
    bounds : 2D array
        The bounds of ``x``, lower bounds in the 1st column, upper
        bounds in the 2nd column. The bounds are possibly tightened
        by the presolve procedure.
    x0 : 1D array, optional
        Guess values of the decision variables, which will be refined by
        the optimization algorithm. This argument is currently used only by the
        'revised simplex' method, and can only be used if `x0` represents a
        basic feasible solution.
revstack: list of functions
    the functions in the list reverse the operations of _presolve()
    the function signature is x_org = f(x_mod), where x_mod is the result
    of a presolve step and x_org the value at the start of the step
complete : bool
    Whether the solution is was determined in presolve (``True`` if so)
Returns
-------
x : 1-D array
    Solution vector to original linear programming problem
fun: float
    optimal objective value for original problem
slack : 1-D array
    The (non-negative) slack in the upper bound constraints, that is,
    ``b_ub - A_ub @ x``
con : 1-D array
    The (nominally zero) residuals of the equality constraints, that is,
    ``b - A_eq @ x``
Definition at line 1316 of file _linprog_util.py.
References _unscale().
_presolve()
scipy.optimize._linprog_util._presolve (lp, rr, rr_method, tol = 1e-9) protected
Given inputs for a linear programming problem in preferred format,
presolve the problem: identify trivial infeasibilities, redundancies,
and unboundedness, tighten bounds where possible, and eliminate fixed
variables.
Parameters
----------
lp : A `scipy.optimize._linprog_util._LPProblem` consisting of the following fields:
    c : 1D array
        The coefficients of the linear objective function to be minimized.
    A_ub : 2D array, optional
        The inequality constraint matrix. Each row of ``A_ub`` specifies the
        coefficients of a linear inequality constraint on ``x``.
    b_ub : 1D array, optional
        The inequality constraint vector. Each element represents an
        upper bound on the corresponding value of ``A_ub @ x``.
    A_eq : 2D array, optional
        The equality constraint matrix. Each row of ``A_eq`` specifies the
        coefficients of a linear equality constraint on ``x``.
    b_eq : 1D array, optional
        The equality constraint vector. Each element of ``A_eq @ x`` must equal
        the corresponding element of ``b_eq``.
    bounds : 2D array
        The bounds of ``x``, as ``min`` and ``max`` pairs, one for each of the N
        elements of ``x``. The N x 2 array contains lower bounds in the first
        column and upper bounds in the 2nd. Unbounded variables have lower
        bound -np.inf and/or upper bound np.inf.
    x0 : 1D array, optional
        Guess values of the decision variables, which will be refined by
        the optimization algorithm. This argument is currently used only by the
        'revised simplex' method, and can only be used if `x0` represents a
        basic feasible solution.
rr : bool
    If ``True`` attempts to eliminate any redundant rows in ``A_eq``.
    Set False if ``A_eq`` is known to be of full row rank, or if you are
    looking for a potential speedup (at the expense of reliability).
rr_method : string
    Method used to identify and remove redundant rows from the
    equality constraint matrix after presolve.
tol : float
    The tolerance which determines when a solution is "close enough" to
    zero in Phase 1 to be considered a basic feasible solution or close
    enough to positive to serve as an optimal solution.
Returns
-------
lp : A `scipy.optimize._linprog_util._LPProblem` consisting of the following fields:
    c : 1D array
        The coefficients of the linear objective function to be minimized.
    A_ub : 2D array, optional
        The inequality constraint matrix. Each row of ``A_ub`` specifies the
        coefficients of a linear inequality constraint on ``x``.
    b_ub : 1D array, optional
        The inequality constraint vector. Each element represents an
        upper bound on the corresponding value of ``A_ub @ x``.
    A_eq : 2D array, optional
        The equality constraint matrix. Each row of ``A_eq`` specifies the
        coefficients of a linear equality constraint on ``x``.
    b_eq : 1D array, optional
        The equality constraint vector. Each element of ``A_eq @ x`` must equal
        the corresponding element of ``b_eq``.
    bounds : 2D array
        The bounds of ``x``, as ``min`` and ``max`` pairs, possibly tightened.
    x0 : 1D array, optional
        Guess values of the decision variables, which will be refined by
        the optimization algorithm. This argument is currently used only by the
        'revised simplex' method, and can only be used if `x0` represents a
        basic feasible solution.
c0 : 1D array
    Constant term in objective function due to fixed (and eliminated)
    variables.
x : 1D array
    Solution vector (when the solution is trivial and can be determined
    in presolve)
revstack: list of functions
    the functions in the list reverse the operations of _presolve()
    the function signature is x_org = f(x_mod), where x_mod is the result
    of a presolve step and x_org the value at the start of the step
    (currently, the revstack contains only one function)
complete: bool
    Whether the solution is complete (solved or determined to be infeasible
    or unbounded in presolve)
status : int
    An integer representing the exit status of the optimization::
     0 : Optimization terminated successfully
     1 : Iteration limit reached
     2 : Problem appears to be infeasible
     3 : Problem appears to be unbounded
     4 : Serious numerical difficulties encountered
message : str
    A string descriptor of the exit status of the optimization.
References
----------
.. [5] Andersen, Erling D. "Finding all linearly dependent rows in
       large-scale linear programming." Optimization Methods and Software
       6.3 (1995): 219-227.
.. [8] Andersen, Erling D., and Knud D. Andersen. "Presolving in linear
       programming." Mathematical Programming 71.2 (1995): 221-245.
Definition at line 477 of file _linprog_util.py.
_round_to_power_of_two()
scipy.optimize._linprog_util._round_to_power_of_two (x) protected
Round elements of the array to the nearest power of two.
Definition at line 1228 of file _linprog_util.py.
Referenced by _autoscale().
_unscale()
scipy.optimize._linprog_util._unscale (x, C, b_scale) protected
Converts solution to _autoscale problem -> solution to original problem.
Definition at line 1273 of file _linprog_util.py.
Referenced by _postsolve().
Variable Documentation
__defaults__
scipy.optimize._linprog_util.__defaults__ private
Definition at line 17 of file _linprog_util.py.
__doc__
scipy.optimize._linprog_util.__doc__ private
Definition at line 18 of file _linprog_util.py.
_LPProblem
scipy.optimize._linprog_util._LPProblem protected
Initial value:
=  namedtuple('_LPProblem',
                        'c A_ub b_ub A_eq b_eq bounds x0 integrality')
Definition at line 15 of file _linprog_util.py.