Code Cloning Analysis: scipy.stats._axis_nan_policy Namespace Reference
scipy.stats._axis_nan_policy Namespace Reference
Functions
_broadcast_arrays (arrays, axis=None)
_broadcast_array_shapes (arrays, axis=None)
_broadcast_shapes (shapes, axis=None)
_broadcast_array_shapes_remove_axis (arrays, axis=None)
_broadcast_shapes_remove_axis (shapes, axis=None)
_broadcast_concatenate (arrays, axis)
_remove_nans (samples, paired)
_remove_sentinel (samples, paired, sentinel)
_masked_arrays_2_sentinel_arrays (samples)
_check_empty_inputs (samples, axis)
_add_reduced_axes (res, reduced_axes, keepdims)
_get_axis_params (default_axis=0, _name=_name, _desc=_desc)
_axis_nan_policy_factory (tuple_to_result, default_axis=0, n_samples=1, paired=False, result_to_tuple=None, too_small=0, n_outputs=2, kwd_samples=[], override=None)
Variables
str _name = 'axis'
tuple _desc
str _type = "{'propagate', 'omit', 'raise'}"
_nan_policy_parameter_doc = Parameter(_name, _type, _desc)
_nan_policy_parameter
_keepdims_parameter_doc = Parameter(_name, _type, _desc)
_keepdims_parameter
tuple _standard_note_addition
Function Documentation
_add_reduced_axes()
scipy.stats._axis_nan_policy._add_reduced_axes (res, reduced_axes, keepdims) protected
Add reduced axes back to all the arrays in the result object
if keepdims = True.
Definition at line 241 of file _axis_nan_policy.py.
Referenced by _axis_nan_policy_factory().
_axis_nan_policy_factory()
scipy.stats._axis_nan_policy._axis_nan_policy_factory (tuple_to_result, default_axis = 0, n_samples = 1, paired = False, result_to_tuple = None, too_small = 0, n_outputs = 2, kwd_samples = [], override = None) protected
Factory for a wrapper that adds axis/nan_policy params to a function.
Parameters
----------
tuple_to_result : callable
    Callable that returns an object of the type returned by the function
    being wrapped (e.g. the namedtuple or dataclass returned by a
    statistical test) provided the separate components (e.g. statistic,
    pvalue).
default_axis : int, default: 0
    The default value of the axis argument. Standard is 0 except when
    backwards compatibility demands otherwise (e.g. `None`).
n_samples : int or callable, default: 1
    The number of data samples accepted by the function
    (e.g. `mannwhitneyu`), a callable that accepts a dictionary of
    parameters passed into the function and returns the number of data
    samples (e.g. `wilcoxon`), or `None` to indicate an arbitrary number
    of samples (e.g. `kruskal`).
paired : {False, True}
    Whether the function being wrapped treats the samples as paired (i.e.
    corresponding elements of each sample should be considered as different
    components of the same sample.)
result_to_tuple : callable, optional
    Function that unpacks the results of the function being wrapped into
    a tuple. This is essentially the inverse of `tuple_to_result`. Default
    is `None`, which is appropriate for statistical tests that return a
    statistic, pvalue tuple (rather than, e.g., a non-iterable datalass).
too_small : int, default: 0
    The largest unnacceptably small sample for the function being wrapped.
    For example, some functions require samples of size two or more or they
    raise an error. This argument prevents the error from being raised when
    input is not 1D and instead places a NaN in the corresponding element
    of the result.
n_outputs : int or callable, default: 2
    The number of outputs produced by the function given 1d sample(s). For
    example, hypothesis tests that return a namedtuple or result object
    with attributes ``statistic`` and ``pvalue`` use the default
    ``n_outputs=2``; summary statistics with scalar output use
    ``n_outputs=1``. Alternatively, may be a callable that accepts a
    dictionary of arguments passed into the wrapped function and returns
    the number of outputs corresponding with those arguments.
kwd_samples : sequence, default: []
    The names of keyword parameters that should be treated as samples. For
    example, `gmean` accepts as its first argument a sample `a` but
    also `weights` as a fourth, optional keyword argument. In this case, we
    use `n_samples=1` and kwd_samples=['weights'].
override : dict, default: {'vectorization': False, 'nan_propagation': True}
    Pass a dictionary with ``'vectorization': True`` to ensure that the
    decorator overrides the function's behavior for multimensional input.
    Use ``'nan_propagation': False`` to ensure that the decorator does not
    override the function's behavior for ``nan_policy='propagate'``.
    (See `scipy.stats.mode`, for example.)
Definition at line 309 of file _axis_nan_policy.py.
References _add_reduced_axes(), _broadcast_arrays(), _broadcast_concatenate(), and _check_empty_inputs().
_broadcast_array_shapes()
scipy.stats._axis_nan_policy._broadcast_array_shapes (arrays, axis = None) protected
Broadcast shapes of arrays, ignoring incompatibility of specified axes
Definition at line 25 of file _axis_nan_policy.py.
References _broadcast_shapes().
Referenced by _broadcast_arrays().
_broadcast_array_shapes_remove_axis()
scipy.stats._axis_nan_policy._broadcast_array_shapes_remove_axis (arrays, axis = None) protected
Broadcast shapes of arrays, dropping specified axes
Given a sequence of arrays `arrays` and an integer or tuple `axis`, find
the shape of the broadcast result after consuming/dropping `axis`.
In other words, return output shape of a typical hypothesis test on
`arrays` vectorized along `axis`.
Examples
--------
>>> import numpy as np
>>> a = np.zeros((5, 2, 1))
>>> b = np.zeros((9, 3))
>>> _broadcast_array_shapes((a, b), 1)
(5, 3)
Definition at line 93 of file _axis_nan_policy.py.
References _broadcast_shapes_remove_axis().
Referenced by _check_empty_inputs().
_broadcast_arrays()
scipy.stats._axis_nan_policy._broadcast_arrays (arrays, axis = None) protected
Broadcast shapes of arrays, ignoring incompatibility of specified axes
Definition at line 14 of file _axis_nan_policy.py.
References _broadcast_array_shapes().
Referenced by _axis_nan_policy_factory(), and _broadcast_concatenate().
_broadcast_concatenate()
scipy.stats._axis_nan_policy._broadcast_concatenate (arrays, axis) protected
Concatenate arrays along an axis with broadcasting.
Definition at line 130 of file _axis_nan_policy.py.
References _broadcast_arrays().
Referenced by _axis_nan_policy_factory().
_broadcast_shapes()
scipy.stats._axis_nan_policy._broadcast_shapes (shapes, axis = None) protected
Broadcast shapes, ignoring incompatibility of specified axes
Definition at line 33 of file _axis_nan_policy.py.
Referenced by _broadcast_array_shapes(), and _broadcast_shapes_remove_axis().
_broadcast_shapes_remove_axis()
scipy.stats._axis_nan_policy._broadcast_shapes_remove_axis (shapes, axis = None) protected
Broadcast shapes, dropping specified axes
Same as _broadcast_array_shapes, but given a sequence
of array shapes `shapes` instead of the arrays themselves.
Definition at line 116 of file _axis_nan_policy.py.
References _broadcast_shapes().
Referenced by _broadcast_array_shapes_remove_axis().
_check_empty_inputs()
scipy.stats._axis_nan_policy._check_empty_inputs (samples, axis) protected
Check for empty sample; return appropriate output for a vectorized hypotest
Definition at line 227 of file _axis_nan_policy.py.
References _broadcast_array_shapes_remove_axis().
Referenced by _axis_nan_policy_factory().
_get_axis_params()
scipy.stats._axis_nan_policy._get_axis_params (default_axis = 0, _name = _name, _desc = _desc) protected
Definition at line 260 of file _axis_nan_policy.py.
_masked_arrays_2_sentinel_arrays()
scipy.stats._axis_nan_policy._masked_arrays_2_sentinel_arrays (samples) protected
Definition at line 171 of file _axis_nan_policy.py.
_remove_nans()
scipy.stats._axis_nan_policy._remove_nans (samples, paired) protected
Definition at line 138 of file _axis_nan_policy.py.
_remove_sentinel()
scipy.stats._axis_nan_policy._remove_sentinel (samples, paired, sentinel) protected
Definition at line 153 of file _axis_nan_policy.py.
Variable Documentation
_desc
tuple scipy.stats._axis_nan_policy._desc protected
Initial value:
=  (
    .split('\n'))
Definition at line 252 of file _axis_nan_policy.py.
_keepdims_parameter
scipy.stats._axis_nan_policy._keepdims_parameter protected
Initial value:
=  inspect.Parameter(_name,
                                        inspect.Parameter.KEYWORD_ONLY,
                                        default=False)
Definition at line 296 of file _axis_nan_policy.py.
_keepdims_parameter_doc
scipy.stats._axis_nan_policy._keepdims_parameter_doc = Parameter(_name, _type, _desc) protected
Definition at line 295 of file _axis_nan_policy.py.
_name
str scipy.stats._axis_nan_policy._name = 'axis' protected
Definition at line 251 of file _axis_nan_policy.py.
_nan_policy_parameter
scipy.stats._axis_nan_policy._nan_policy_parameter protected
Initial value:
=  inspect.Parameter(_name,
                                          inspect.Parameter.KEYWORD_ONLY,
                                          default='propagate')
Definition at line 284 of file _axis_nan_policy.py.
_nan_policy_parameter_doc
scipy.stats._axis_nan_policy._nan_policy_parameter_doc = Parameter(_name, _type, _desc) protected
Definition at line 283 of file _axis_nan_policy.py.
_standard_note_addition
tuple scipy.stats._axis_nan_policy._standard_note_addition protected
Initial value:
=  (
    ).split('\n')
Definition at line 300 of file _axis_nan_policy.py.
_type
str scipy.stats._axis_nan_policy._type = "{'propagate', 'omit', 'raise'}" protected
Definition at line 270 of file _axis_nan_policy.py.