Code Cloning Analysis: scipy.interpolate.tests.test_polyint.TestCubicSpline Class Reference
scipy.interpolate.tests.test_polyint.TestCubicSpline Class Reference
Public Member Functions
check_all_bc (self, x, y, axis)
test_general (self)
test_periodic (self)
test_periodic_eval (self)
test_second_derivative_continuity_gh_11758 (self)
test_three_points (self)
test_dtypes (self)
test_small_dx (self)
test_incorrect_inputs (self)
Static Public Member Functions
check_correctness (S, bc_start='not-a-knot', bc_end='not-a-knot', tol=1e-14)
Detailed Description
Definition at line 525 of file test_polyint.py.
Member Function Documentation
check_all_bc()
scipy.interpolate.tests.test_polyint.TestCubicSpline.check_all_bc (self, x, y, axis)
Definition at line 586 of file test_polyint.py.
Referenced by check_correctness().
check_correctness()
scipy.interpolate.tests.test_polyint.TestCubicSpline.check_correctness (S, bc_start = 'not-a-knot', bc_end = 'not-a-knot', tol = 1e-14) static
Check that spline coefficients satisfy the continuity and boundary
conditions.
Definition at line 527 of file test_polyint.py.
References check_all_bc(), and check_correctness().
Referenced by check_correctness().
test_dtypes()
scipy.interpolate.tests.test_polyint.TestCubicSpline.test_dtypes (self)
Definition at line 664 of file test_polyint.py.
test_general()
scipy.interpolate.tests.test_polyint.TestCubicSpline.test_general (self)
Definition at line 609 of file test_polyint.py.
test_incorrect_inputs()
scipy.interpolate.tests.test_polyint.TestCubicSpline.test_incorrect_inputs (self)
Definition at line 688 of file test_polyint.py.
test_periodic()
scipy.interpolate.tests.test_polyint.TestCubicSpline.test_periodic (self)
Definition at line 622 of file test_polyint.py.
test_periodic_eval()
scipy.interpolate.tests.test_polyint.TestCubicSpline.test_periodic_eval (self)
Definition at line 637 of file test_polyint.py.
test_second_derivative_continuity_gh_11758()
scipy.interpolate.tests.test_polyint.TestCubicSpline.test_second_derivative_continuity_gh_11758 (self)
Definition at line 643 of file test_polyint.py.
test_small_dx()
scipy.interpolate.tests.test_polyint.TestCubicSpline.test_small_dx (self)
Definition at line 681 of file test_polyint.py.
test_three_points()
scipy.interpolate.tests.test_polyint.TestCubicSpline.test_three_points (self)
Definition at line 652 of file test_polyint.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/interpolate/tests/test_polyint.py