Code Cloning Analysis: numpy Namespace Reference
numpy Namespace Reference
Namespaces
namespace _core
namespace _distributor_init
namespace _globals
namespace _pytesttester
namespace _typing
namespace _utils
namespace array_api
namespace compat
namespace conftest
namespace core
namespace ctypeslib
namespace dtypes
namespace exceptions
namespace f2py
namespace fft
namespace lib
namespace linalg
namespace ma
namespace matrixlib
namespace polynomial
namespace random
namespace testing
namespace typing
Functions
__getattr__ (attr)
__dir__ ()
_sanity_check ()
_mac_os_check ()
_pyinstaller_hooks_dir ()
Variables
bool __NUMPY_SETUP__ = False
str msg
list __all__
dict __deprecated_attrs__ = {}
tuple _msg
tuple _specific_msg
tuple _int_extended_msg
list _type_info
dict __former_attrs__
dict __future_scalars__ = {"bool", "long", "ulong", "str", "bytes", "object"}
list _financial_names
dict __expired_functions__
message
str oldnumeric = 'removed'
str numarray = 'removed'
test = PytestTester(__name__)
record
str error_message = f"{_wn.category.__name__}: {str(_wn.message)}"
use_hugepage = os.environ.get("NUMPY_MADVISE_HUGEPAGE", None)
kernel_version = os.uname().release.split(".")[:2]
int use_hugepages = 0
Detailed Description
NumPy
=====
Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation
How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.
We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.
The docstring examples assume that `numpy` has been imported as ``np``::
  >>> import numpy as np
Code snippets are indicated by three greater-than signs::
  >>> x = 42
  >>> x = x + 1
Use the built-in ``help`` function to view a function's docstring::
  >>> help(np.sort)
  ... # doctest: +SKIP
For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly true if you see the line "Help on ufunc object:" at the top
of the help() page.  Ufuncs are implemented in C, not Python, for speed.
The native Python help() does not know how to view their help, but our
np.info() function does.
To search for documents containing a keyword, do::
  >>> np.lookfor('keyword')
  ... # doctest: +SKIP
General-purpose documents like a glossary and help on the basic concepts
of numpy are available under the ``doc`` sub-module::
  >>> from numpy import doc
  >>> help(doc)
  ... # doctest: +SKIP
Available subpackages
---------------------
lib
    Basic functions used by several sub-packages.
random
    Core Random Tools
linalg
    Core Linear Algebra Tools
fft
    Core FFT routines
polynomial
    Polynomial tools
testing
    NumPy testing tools
distutils
    Enhancements to distutils with support for
    Fortran compilers support and more  (for Python <= 3.11).
Utilities
---------
test
    Run numpy unittests
show_config
    Show numpy build configuration
matlib
    Make everything matrices.
__version__
    NumPy version string
Viewing documentation using IPython
-----------------------------------
Start IPython and import `numpy` usually under the alias ``np``: `import
numpy as np`.  Then, directly past or use the ``%cpaste`` magic to paste
examples into the shell.  To see which functions are available in `numpy`,
type ``np.<TAB>`` (where ``<TAB>`` refers to the TAB key), or use
``np.*cos*?<ENTER>`` (where ``<ENTER>`` refers to the ENTER key) to narrow
down the list.  To view the docstring for a function, use
``np.cos?<ENTER>`` (to view the docstring) and ``np.cos??<ENTER>`` (to view
the source code).
Copies vs. in-place operation
-----------------------------
Most of the functions in `numpy` return a copy of the array argument
(e.g., `np.sort`).  In-place versions of these functions are often
available as array methods, i.e. ``x = np.array([1,2,3]); x.sort()``.
Exceptions to this rule are documented.
Function Documentation
__dir__()
numpy.__dir__ ()
Definition at line 336 of file __init__.py.
__getattr__()
numpy.__getattr__ (attr)
Definition at line 290 of file __init__.py.
_mac_os_check()
numpy._mac_os_check () protected
Quick Sanity check for Mac OS look for accelerate build bugs.
Testing numpy polyfit calls init_dgelsd(LAPACK)
Definition at line 377 of file __init__.py.
References _mac_os_check(), numpy.core.function_base.linspace(), numpy.lib.polynomial.polyfit(), and numpy.lib.polynomial.polyval().
Referenced by _mac_os_check().
_pyinstaller_hooks_dir()
numpy._pyinstaller_hooks_dir () protected
Definition at line 452 of file __init__.py.
_sanity_check()
numpy._sanity_check () protected
Quick sanity checks for common bugs caused by environment.
There are some cases e.g. with wrong BLAS ABI that cause wrong
results under specific runtime conditions that are not necessarily
achieved during test suite runs, and it is useful to catch those early.
See https://github.com/numpy/numpy/issues/8577 and other
similar bug reports.
Definition at line 351 of file __init__.py.
References _sanity_check(), and numpy.core.numeric.ones().
Referenced by _sanity_check().
Variable Documentation
__all__
list numpy.__all__ private
Initial value:
=  [
        'exceptions', 'ModuleDeprecationWarning', 'VisibleDeprecationWarning',
        'ComplexWarning', 'TooHardError', 'AxisError']
Definition at line 137 of file __init__.py.
__deprecated_attrs__
dict numpy.__deprecated_attrs__ = {} private
Definition at line 142 of file __init__.py.
__expired_functions__
dict numpy.__expired_functions__ private
Initial value:
=  {
        name: (f'In accordance with NEP 32, the function {name} was removed '
               'from NumPy version 1.20.  A replacement for this function '
               'is available in the numpy_financial library: '
               'https://pypi.org/project/numpy-financial')
        for name in _financial_names}
Definition at line 273 of file __init__.py.
__former_attrs__
dict numpy.__former_attrs__ private
Initial value:
=  {
         n: _msg.format(n=n, extended_msg=extended_msg)
         for n, extended_msg in _type_info
     }
Definition at line 192 of file __init__.py.
__future_scalars__
dict numpy.__future_scalars__ = {"bool", "long", "ulong", "str", "bytes", "object"} private
Definition at line 219 of file __init__.py.
__NUMPY_SETUP__
bool numpy.__NUMPY_SETUP__ = False private
Definition at line 121 of file __init__.py.
_financial_names
list numpy._financial_names protected
Initial value:
=  ['fv', 'ipmt', 'irr', 'mirr', 'nper', 'npv', 'pmt',
                        'ppmt', 'pv', 'rate']
Definition at line 271 of file __init__.py.
_int_extended_msg
tuple numpy._int_extended_msg protected
Initial value:
=  (
        "When replacing `np.{}`, you may wish to use e.g. `np.int64` "
        "or `np.int32` to specify the precision. If you wish to review "
        "your current use, check the release note link for "
        "additional information.")
Definition at line 178 of file __init__.py.
_msg
tuple numpy._msg protected
Initial value:
=  (
        "module 'numpy' has no attribute '{n}'.\n"
        "`np.{n}` was a deprecated alias for the builtin `{n}`. "
        "To avoid this error in existing code, use `{n}` by itself. "
        "Doing this will not modify any behavior and is safe. {extended_msg}\n"
        "The aliases was originally deprecated in NumPy 1.20; for more "
        "details and guidance see the original release note at:\n"
        "    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations")
Definition at line 166 of file __init__.py.
_specific_msg
tuple numpy._specific_msg protected
Initial value:
=  (
        "If you specifically wanted the numpy scalar type, use `np.{}` here.")
Definition at line 175 of file __init__.py.
_type_info
list numpy._type_info protected
Initial value:
=  [
        ("object", ""),  # The NumPy scalar only exists by name.
        ("bool", _specific_msg.format("bool_")),
        ("float", _specific_msg.format("float64")),
        ("complex", _specific_msg.format("complex128")),
        ("str", _specific_msg.format("str_")),
        ("int", _int_extended_msg.format("int"))]
Definition at line 184 of file __init__.py.
error_message
str numpy.error_message = f"{_wn.category.__name__}: {str(_wn.message)}"
Definition at line 399 of file __init__.py.
kernel_version
numpy.kernel_version = os.uname().release.split(".")[:2]
Definition at line 425 of file __init__.py.
message
numpy.message
Definition at line 281 of file __init__.py.
msg
tuple numpy.msg
Initial value:
=  """Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there."""
Definition at line 132 of file __init__.py.
numarray
str numpy.numarray = 'removed'
Definition at line 288 of file __init__.py.
oldnumeric
str numpy.oldnumeric = 'removed'
Definition at line 287 of file __init__.py.
record
numpy.record
Definition at line 392 of file __init__.py.
test
numpy.test = PytestTester(__name__)
Definition at line 348 of file __init__.py.
use_hugepage
int numpy.use_hugepage = os.environ.get("NUMPY_MADVISE_HUGEPAGE", None)
Definition at line 417 of file __init__.py.
use_hugepages
int numpy.use_hugepages = 0
Definition at line 430 of file __init__.py.