Code Cloning Analysis: matplotlib.scale.ScaleBase Class Reference
matplotlib.scale.ScaleBase Class Reference
Public Member Functions
__init__ (self, axis)
get_transform (self)
set_default_locators_and_formatters (self, axis)
limit_range_for_scale (self, vmin, vmax, minpos)
Detailed Description
The base class for all scales.
Scales are separable transformations, working on a single dimension.
Subclasses should override
:attr:`name`
    The scale's name.
:meth:`get_transform`
    A method returning a `.Transform`, which converts data coordinates to
    scaled coordinates.  This transform should be invertible, so that e.g.
    mouse positions can be converted back to data coordinates.
:meth:`set_default_locators_and_formatters`
    A method that sets default locators and formatters for an `~.axis.Axis`
    that uses this scale.
:meth:`limit_range_for_scale`
    An optional method that "fixes" the axis range to acceptable values,
    e.g. restricting log-scaled axes to positive values.
Definition at line 46 of file scale.py.
Constructor & Destructor Documentation
__init__()
matplotlib.scale.ScaleBase.__init__ (self, axis)
    Construct a new scale.
    Notes
    -----
    The following note is for scale implementers.
    For back-compatibility reasons, scales take an `~matplotlib.axis.Axis`
    object as first argument.  However, this argument should not
    be used: a single scale object should be usable by multiple
    `~matplotlib.axis.Axis`\es at the same time.
Definition at line 68 of file scale.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
get_transform()
matplotlib.scale.ScaleBase.get_transform (self)
Return the `.Transform` object associated with this scale.
Reimplemented in matplotlib.scale.AsinhScale, matplotlib.scale.FuncScale, matplotlib.scale.FuncScaleLog, matplotlib.scale.LinearScale, matplotlib.scale.LogitScale, matplotlib.scale.LogScale, and matplotlib.scale.SymmetricalLogScale.
Definition at line 82 of file scale.py.
Referenced by matplotlib.quiver.QuiverKey.__init__(), matplotlib.table.Table.__setitem__(), matplotlib.image._ImageBase._check_unsampled_image(), matplotlib.table.Table._get_grid_bbox(), matplotlib.text.Text._get_wrap_line_width(), matplotlib.text.Text._get_wrapped_text(), matplotlib.text.Text._get_xy_display(), matplotlib.quiver.Quiver._init(), matplotlib.image._ImageBase._make_image(), matplotlib.legend.Legend._set_artist_props(), matplotlib.contour.ContourLabeler._split_path_and_get_label_rotation(), matplotlib.lines.Line2D._transform_path(), matplotlib.image._ImageBase.can_composite(), matplotlib.image._ImageBase.contains(), matplotlib.collections.TriMesh.convert_mesh_to_paths(), mplot3d.axis3d.Axis.draw_pane(), matplotlib.lines.Line2D.get_bbox(), matplotlib.image.AxesImage.get_cursor_data(), matplotlib.collections.FillBetweenPolyCollection.get_datalim(), matplotlib.text.Text.get_rotation(), axisartist.axis_artist.Ticks.get_ticksize(), matplotlib.text.Text.get_window_extent(), matplotlib.image.AxesImage.make_image(), matplotlib.contour.ContourLabeler.pop_label(), matplotlib.lines.Line2D.set_data(), matplotlib.scale.SymmetricalLogScale.set_default_locators_and_formatters(), matplotlib.collections.Collection.set_offset_transform(), and matplotlib.text.Text.update_bbox_position_size().
limit_range_for_scale()
matplotlib.scale.ScaleBase.limit_range_for_scale (self, vmin, vmax, minpos)
Return the range *vmin*, *vmax*, restricted to the
domain supported by this scale (if any).
*minpos* should be the minimum positive value in the data.
This is used by log scales to determine a minimum value.
Reimplemented in matplotlib.scale.LogitScale, and matplotlib.scale.LogScale.
Definition at line 95 of file scale.py.
set_default_locators_and_formatters()
matplotlib.scale.ScaleBase.set_default_locators_and_formatters (self, axis)
Set the locators and formatters of *axis* to instances suitable for
this scale.
Reimplemented in matplotlib.scale.AsinhScale, matplotlib.scale.FuncScale, matplotlib.scale.LinearScale, matplotlib.scale.LogitScale, matplotlib.scale.LogScale, and matplotlib.scale.SymmetricalLogScale.
Definition at line 88 of file scale.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/scale.py