Code Cloning Analysis: axes_grid1.axes_grid.CbarAxesBase Class Reference
axes_grid1.axes_grid.CbarAxesBase Class Reference
Public Member Functions
__init__ (self, *args, orientation, **kwargs)
colorbar (self, mappable, **kwargs)
Public Attributes
orientation = orientation
Detailed Description
Definition at line 14 of file axes_grid.py.
Constructor & Destructor Documentation
__init__()
axes_grid1.axes_grid.CbarAxesBase.__init__ (self, * args, orientation, ** kwargs)
Definition at line 15 of file axes_grid.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
colorbar()
axes_grid1.axes_grid.CbarAxesBase.colorbar (self, mappable, ** kwargs)
Definition at line 19 of file axes_grid.py.
Member Data Documentation
orientation
axes_grid1.axes_grid.CbarAxesBase.orientation = orientation
Definition at line 16 of file axes_grid.py.
Referenced by pandas.plotting._matplotlib.hist.HistPlot._post_plot_logic(), and pandas.plotting._matplotlib.core.MPLPlot._post_plot_logic_common().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/mpl_toolkits/axes_grid1/axes_grid.py