Code Cloning Analysis: fontTools.merge.util.GregariousIdentityDict Class Reference
fontTools.merge.util.GregariousIdentityDict Class Reference
Public Member Functions
__init__ (self, lst)
__getitem__ (self, v)
Public Attributes
l = lst
s = set(id(v) for v in lst)
Detailed Description
A dictionary-like object that welcomes guests without reservations and
adds them to the end of the guest list.
Definition at line 112 of file util.py.
Constructor & Destructor Documentation
__init__()
fontTools.merge.util.GregariousIdentityDict.__init__ (self, lst)
Definition at line 116 of file util.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__getitem__()
fontTools.merge.util.GregariousIdentityDict.__getitem__ (self, v)
Definition at line 120 of file util.py.
Member Data Documentation
l
fontTools.merge.util.GregariousIdentityDict.l = lst
Definition at line 117 of file util.py.
s
fontTools.merge.util.GregariousIdentityDict.s = set(id(v) for v in lst)
Definition at line 118 of file util.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/merge/util.py