Code Cloning Analysis: pandas.core.ops.mask_ops Namespace Reference
pandas.core.ops.mask_ops Namespace Reference
Functions
kleene_or (bool|np.ndarray|libmissing.NAType left, bool|np.ndarray|libmissing.NAType right, np.ndarray|None left_mask, np.ndarray|None right_mask)
kleene_xor (bool|np.ndarray|libmissing.NAType left, bool|np.ndarray|libmissing.NAType right, np.ndarray|None left_mask, np.ndarray|None right_mask)
kleene_and (bool|libmissing.NAType|np.ndarray left, bool|libmissing.NAType|np.ndarray right, np.ndarray|None left_mask, np.ndarray|None right_mask)
None raise_for_nan (value, str method)
Detailed Description
Ops for masked arrays.
Function Documentation
kleene_and()
pandas.core.ops.mask_ops.kleene_and (bool | libmissing.NAType | np.ndarray left, bool | libmissing.NAType | np.ndarray right, np.ndarray | None left_mask, np.ndarray | None right_mask)
Boolean ``and`` using Kleene logic.
Values are ``NA`` for ``NA & NA`` or ``True & NA``.
Parameters
----------
left, right : ndarray, NA, or bool
    The values of the array.
left_mask, right_mask : ndarray, optional
    The masks. Only one of these may be None, which implies that
    the associated `left` or `right` value is a scalar.
Returns
-------
result, mask: ndarray[bool]
    The result of the logical xor, and the new mask.
Definition at line 129 of file mask_ops.py.
References kleene_and().
Referenced by kleene_and().
kleene_or()
pandas.core.ops.mask_ops.kleene_or (bool | np.ndarray | libmissing.NAType left, bool | np.ndarray | libmissing.NAType right, np.ndarray | None left_mask, np.ndarray | None right_mask)
Boolean ``or`` using Kleene logic.
Values are NA where we have ``NA | NA`` or ``NA | False``.
``NA | True`` is considered True.
Parameters
----------
left, right : ndarray, NA, or bool
    The values of the array.
left_mask, right_mask : ndarray, optional
    The masks. Only one of these may be None, which implies that
    the associated `left` or `right` value is a scalar.
Returns
-------
result, mask: ndarray[bool]
    The result of the logical or, and the new mask.
Definition at line 14 of file mask_ops.py.
References kleene_or().
Referenced by kleene_or().
kleene_xor()
pandas.core.ops.mask_ops.kleene_xor (bool | np.ndarray | libmissing.NAType left, bool | np.ndarray | libmissing.NAType right, np.ndarray | None left_mask, np.ndarray | None right_mask)
Boolean ``xor`` using Kleene logic.
This is the same as ``or``, with the following adjustments
* True, True -> False
* True, NA   -> NA
Parameters
----------
left, right : ndarray, NA, or bool
    The values of the array.
left_mask, right_mask : ndarray, optional
    The masks. Only one of these may be None, which implies that
    the associated `left` or `right` value is a scalar.
Returns
-------
result, mask: ndarray[bool]
    The result of the logical xor, and the new mask.
Definition at line 76 of file mask_ops.py.
References kleene_xor().
Referenced by kleene_xor().
raise_for_nan()
None pandas.core.ops.mask_ops.raise_for_nan (value, str method)
Definition at line 187 of file mask_ops.py.