Code Cloning Analysis: pandas.core.arrays.arrow.array Namespace Reference
pandas.core.arrays.arrow.array Namespace Reference
Classes
class ArrowExtensionArray
Functions
tuple[pa.ChunkedArray, pa.Array|pa.Scalar] cast_for_truediv (pa.ChunkedArray arrow_array, pa.Array|pa.Scalar pa_object)
pa.ChunkedArray floordiv_compat (pa.ChunkedArray|pa.Array|pa.Scalar left, pa.ChunkedArray|pa.Array|pa.Scalar right)
get_unit_from_pa_dtype (pa_dtype)
pa.DataType|None to_pyarrow_type (ArrowDtype|pa.DataType|Dtype|None dtype)
list[ArrowExtensionArray] transpose_homogeneous_pyarrow (Sequence[ArrowExtensionArray] arrays)
Variables
dict ARROW_CMP_FUNCS
dict ARROW_LOGICAL_FUNCS
dict ARROW_BIT_WISE_FUNCS
dict ARROW_ARITHMETIC_FUNCS
Function Documentation
cast_for_truediv()
tuple[pa.ChunkedArray, pa.Array | pa.Scalar] pandas.core.arrays.arrow.array.cast_for_truediv (pa.ChunkedArray arrow_array, pa.Array | pa.Scalar pa_object)
Definition at line 113 of file array.py.
floordiv_compat()
pa.ChunkedArray pandas.core.arrays.arrow.array.floordiv_compat (pa.ChunkedArray | pa.Array | pa.Scalar left, pa.ChunkedArray | pa.Array | pa.Scalar right)
Definition at line 129 of file array.py.
get_unit_from_pa_dtype()
pandas.core.arrays.arrow.array.get_unit_from_pa_dtype (pa_dtype)
Definition at line 208 of file array.py.
to_pyarrow_type()
pa.DataType | None pandas.core.arrays.arrow.array.to_pyarrow_type (ArrowDtype | pa.DataType | Dtype | None dtype)
Convert dtype to a pyarrow type instance.
Definition at line 218 of file array.py.
Referenced by pandas.core.arrays.arrow.array.ArrowExtensionArray._from_sequence(), pandas.core.arrays.arrow.array.ArrowExtensionArray._from_sequence_of_strings(), and pandas.core.arrays.arrow.array.ArrowExtensionArray._reduce().
transpose_homogeneous_pyarrow()
list[ArrowExtensionArray] pandas.core.arrays.arrow.array.transpose_homogeneous_pyarrow (Sequence[ArrowExtensionArray] arrays)
Transpose arrow extension arrays in a list, but faster.
Input should be a list of arrays of equal length and all have the same
dtype. The caller is responsible for ensuring validity of input data.
Definition at line 2914 of file array.py.
Variable Documentation
ARROW_ARITHMETIC_FUNCS
dict pandas.core.arrays.arrow.array.ARROW_ARITHMETIC_FUNCS
Initial value:
=  {
        "add": pc.add_checked,
        "radd": lambda x, y: pc.add_checked(y, x),
        "sub": pc.subtract_checked,
        "rsub": lambda x, y: pc.subtract_checked(y, x),
        "mul": pc.multiply_checked,
        "rmul": lambda x, y: pc.multiply_checked(y, x),
        "truediv": lambda x, y: pc.divide(*cast_for_truediv(x, y)),
        "rtruediv": lambda x, y: pc.divide(*cast_for_truediv(y, x)),
        "floordiv": lambda x, y: floordiv_compat(x, y),
        "rfloordiv": lambda x, y: floordiv_compat(y, x),
        "mod": NotImplemented,
        "rmod": NotImplemented,
        "divmod": NotImplemented,
        "rdivmod": NotImplemented,
        "pow": pc.power_checked,
        "rpow": lambda x, y: pc.power_checked(y, x),
    }
Definition at line 161 of file array.py.
ARROW_BIT_WISE_FUNCS
dict pandas.core.arrays.arrow.array.ARROW_BIT_WISE_FUNCS
Initial value:
=  {
        "and_": pc.bit_wise_and,
        "rand_": lambda x, y: pc.bit_wise_and(y, x),
        "or_": pc.bit_wise_or,
        "ror_": lambda x, y: pc.bit_wise_or(y, x),
        "xor": pc.bit_wise_xor,
        "rxor": lambda x, y: pc.bit_wise_xor(y, x),
    }
Definition at line 104 of file array.py.
ARROW_CMP_FUNCS
dict pandas.core.arrays.arrow.array.ARROW_CMP_FUNCS
Initial value:
=  {
        "eq": pc.equal,
        "ne": pc.not_equal,
        "lt": pc.less,
        "gt": pc.greater,
        "le": pc.less_equal,
        "ge": pc.greater_equal,
    }
Definition at line 86 of file array.py.
ARROW_LOGICAL_FUNCS
dict pandas.core.arrays.arrow.array.ARROW_LOGICAL_FUNCS
Initial value:
=  {
        "and_": pc.and_kleene,
        "rand_": lambda x, y: pc.and_kleene(y, x),
        "or_": pc.or_kleene,
        "ror_": lambda x, y: pc.or_kleene(y, x),
        "xor": pc.xor,
        "rxor": lambda x, y: pc.xor(y, x),
    }
Definition at line 95 of file array.py.