Code Cloning Analysis: sklearn.linear_model._least_angle Namespace Reference
sklearn.linear_model._least_angle Namespace Reference
Classes
class Lars
Estimator classes.
class LarsCV
class LassoLars
class LassoLarsCV
class LassoLarsIC
Functions
lars_path (X, y, Xy=None, *, Gram=None, max_iter=500, alpha_min=0, method="lar", copy_X=True, eps=np.finfo(float).eps, copy_Gram=True, verbose=0, return_path=True, return_n_iter=False, positive=False)
lars_path_gram (Xy, Gram, *, n_samples, max_iter=500, alpha_min=0, method="lar", copy_X=True, eps=np.finfo(float).eps, copy_Gram=True, verbose=0, return_path=True, return_n_iter=False, positive=False)
_lars_path_solver (X, y, Xy=None, Gram=None, n_samples=None, max_iter=500, alpha_min=0, method="lar", copy_X=True, eps=np.finfo(float).eps, copy_Gram=True, verbose=0, return_path=True, return_n_iter=False, positive=False)
_check_copy_and_writeable (array, copy=False)
_lars_path_residues (X_train, y_train, X_test, y_test, Gram=None, copy=True, method="lar", verbose=False, fit_intercept=True, max_iter=500, eps=np.finfo(float).eps, positive=False)
Variables
dict SOLVE_TRIANGULAR_ARGS = {"check_finite": False}
Detailed Description
Least Angle Regression algorithm. See the documentation on the
Generalized Linear Model for a complete discussion.
Function Documentation
_check_copy_and_writeable()
sklearn.linear_model._least_angle._check_copy_and_writeable (array, copy = False) protected
Definition at line 1393 of file _least_angle.py.
_lars_path_residues()
sklearn.linear_model._least_angle._lars_path_residues (X_train, y_train, X_test, y_test, Gram = None, copy = True, method = "lar", verbose = False, fit_intercept = True, max_iter = 500, eps = np.finfo(float).eps, positive = False) protected
Compute the residues on left-out data for a full LARS path
Parameters
-----------
X_train : array-like of shape (n_samples, n_features)
    The data to fit the LARS on
y_train : array-like of shape (n_samples,)
    The target variable to fit LARS on
X_test : array-like of shape (n_samples, n_features)
    The data to compute the residues on
y_test : array-like of shape (n_samples,)
    The target variable to compute the residues on
Gram : None, 'auto' or array-like of shape (n_features, n_features), \
        default=None
    Precomputed Gram matrix (X' * X), if ``'auto'``, the Gram
    matrix is precomputed from the given X, if there are more samples
    than features
copy : bool, default=True
    Whether X_train, X_test, y_train and y_test should be copied;
    if False, they may be overwritten.
method : {'lar' , 'lasso'}, default='lar'
    Specifies the returned model. Select ``'lar'`` for Least Angle
    Regression, ``'lasso'`` for the Lasso.
verbose : bool or int, default=False
    Sets the amount of verbosity
fit_intercept : bool, default=True
    whether to calculate the intercept for this model. If set
    to false, no intercept will be used in calculations
    (i.e. data is expected to be centered).
positive : bool, default=False
    Restrict coefficients to be >= 0. Be aware that you might want to
    remove fit_intercept which is set True by default.
    See reservations for using this option in combination with method
    'lasso' for expected small values of alpha in the doc of LassoLarsCV
    and LassoLarsIC.
max_iter : int, default=500
    Maximum number of iterations to perform.
eps : float, default=np.finfo(float).eps
    The machine-precision regularization in the computation of the
    Cholesky diagonal factors. Increase this for very ill-conditioned
    systems. Unlike the ``tol`` parameter in some iterative
    optimization-based algorithms, this parameter does not control
    the tolerance of the optimization.
Returns
--------
alphas : array-like of shape (n_alphas,)
    Maximum of covariances (in absolute value) at each iteration.
    ``n_alphas`` is either ``max_iter`` or ``n_features``, whichever
    is smaller.
active : list
    Indices of active variables at the end of the path.
coefs : array-like of shape (n_features, n_alphas)
    Coefficients along the path
residues : array-like of shape (n_alphas, n_samples)
    Residues of the prediction on the test data
Definition at line 1399 of file _least_angle.py.
References lars_path().
_lars_path_solver()
sklearn.linear_model._least_angle._lars_path_solver (X, y, Xy = None, Gram = None, n_samples = None, max_iter = 500, alpha_min = 0, method = "lar", copy_X = True, eps = np.finfo(float).eps, copy_Gram = True, verbose = 0, return_path = True, return_n_iter = False, positive = False) protected
Compute Least Angle Regression or Lasso path using LARS algorithm [1]
The optimization objective for the case method='lasso' is::
(1 / (2 * n_samples)) * ||y - Xw||^2_2 + alpha * ||w||_1
in the case of method='lar', the objective function is only known in
the form of an implicit equation (see discussion in [1])
Read more in the :ref:`User Guide <least_angle_regression>`.
Parameters
----------
X : None or ndarray of shape (n_samples, n_features)
    Input data. Note that if X is None then Gram must be specified,
    i.e., cannot be None or False.
y : None or ndarray of shape (n_samples,)
    Input targets.
Xy : array-like of shape (n_features,), default=None
    `Xy = np.dot(X.T, y)` that can be precomputed. It is useful
    only when the Gram matrix is precomputed.
Gram : None, 'auto' or array-like of shape (n_features, n_features), \
        default=None
    Precomputed Gram matrix `(X' * X)`, if ``'auto'``, the Gram
    matrix is precomputed from the given X, if there are more samples
    than features.
n_samples : int or float, default=None
    Equivalent size of sample. If `None`, it will be `n_samples`.
max_iter : int, default=500
    Maximum number of iterations to perform, set to infinity for no limit.
alpha_min : float, default=0
    Minimum correlation along the path. It corresponds to the
    regularization parameter alpha parameter in the Lasso.
method : {'lar', 'lasso'}, default='lar'
    Specifies the returned model. Select ``'lar'`` for Least Angle
    Regression, ``'lasso'`` for the Lasso.
copy_X : bool, default=True
    If ``False``, ``X`` is overwritten.
eps : float, default=np.finfo(float).eps
    The machine-precision regularization in the computation of the
    Cholesky diagonal factors. Increase this for very ill-conditioned
    systems. Unlike the ``tol`` parameter in some iterative
    optimization-based algorithms, this parameter does not control
    the tolerance of the optimization.
copy_Gram : bool, default=True
    If ``False``, ``Gram`` is overwritten.
verbose : int, default=0
    Controls output verbosity.
return_path : bool, default=True
    If ``return_path==True`` returns the entire path, else returns only the
    last point of the path.
return_n_iter : bool, default=False
    Whether to return the number of iterations.
positive : bool, default=False
    Restrict coefficients to be >= 0.
    This option is only allowed with method 'lasso'. Note that the model
    coefficients will not converge to the ordinary-least-squares solution
    for small values of alpha. Only coefficients up to the smallest alpha
    value (``alphas_[alphas_ > 0.].min()`` when fit_path=True) reached by
    the stepwise Lars-Lasso algorithm are typically in congruence with the
    solution of the coordinate descent lasso_path function.
Returns
-------
alphas : array-like of shape (n_alphas + 1,)
    Maximum of covariances (in absolute value) at each iteration.
    ``n_alphas`` is either ``max_iter``, ``n_features`` or the
    number of nodes in the path with ``alpha >= alpha_min``, whichever
    is smaller.
active : array-like of shape (n_alphas,)
    Indices of active variables at the end of the path.
coefs : array-like of shape (n_features, n_alphas + 1)
    Coefficients along the path
n_iter : int
    Number of iterations run. Returned only if return_n_iter is set
    to True.
See Also
--------
lasso_path
LassoLars
Lars
LassoLarsCV
LarsCV
sklearn.decomposition.sparse_encode
References
----------
.. [1] "Least Angle Regression", Efron et al.
       http://statweb.stanford.edu/~tibs/ftp/lars.pdf
.. [2] `Wikipedia entry on the Least-angle regression
       <https://en.wikipedia.org/wiki/Least-angle_regression>`_
.. [3] `Wikipedia entry on the Lasso
       <https://en.wikipedia.org/wiki/Lasso_(statistics)>`_
Definition at line 411 of file _least_angle.py.
Referenced by lars_path(), and lars_path_gram().
lars_path()
sklearn.linear_model._least_angle.lars_path (X, y, Xy = None, * , Gram = None, max_iter = 500, alpha_min = 0, method = "lar", copy_X = True, eps = np.finfo(float).eps, copy_Gram = True, verbose = 0, return_path = True, return_n_iter = False, positive = False)
Compute Least Angle Regression or Lasso path using the LARS algorithm.
The optimization objective for the case method='lasso' is::
(1 / (2 * n_samples)) * ||y - Xw||^2_2 + alpha * ||w||_1
in the case of method='lar', the objective function is only known in
the form of an implicit equation (see discussion in [1]_).
Read more in the :ref:`User Guide <least_angle_regression>`.
Parameters
----------
X : None or ndarray of shape (n_samples, n_features)
    Input data. If X is `None`, Gram must also be `None`.
    If only the Gram matrix is available, use `lars_path_gram` instead.
y : None or ndarray of shape (n_samples,)
    Input targets.
Xy : array-like of shape (n_features,), default=None
    `Xy = X.T @ y` that can be precomputed. It is useful
    only when the Gram matrix is precomputed.
Gram : None, 'auto', bool, ndarray of shape (n_features, n_features), \
        default=None
    Precomputed Gram matrix `X.T @ X`, if `'auto'`, the Gram
    matrix is precomputed from the given X, if there are more samples
    than features.
max_iter : int, default=500
    Maximum number of iterations to perform, set to infinity for no limit.
alpha_min : float, default=0
    Minimum correlation along the path. It corresponds to the
    regularization parameter `alpha` in the Lasso.
method : {'lar', 'lasso'}, default='lar'
    Specifies the returned model. Select `'lar'` for Least Angle
    Regression, `'lasso'` for the Lasso.
copy_X : bool, default=True
    If `False`, `X` is overwritten.
eps : float, default=np.finfo(float).eps
    The machine-precision regularization in the computation of the
    Cholesky diagonal factors. Increase this for very ill-conditioned
    systems. Unlike the `tol` parameter in some iterative
    optimization-based algorithms, this parameter does not control
    the tolerance of the optimization.
copy_Gram : bool, default=True
    If `False`, `Gram` is overwritten.
verbose : int, default=0
    Controls output verbosity.
return_path : bool, default=True
    If `True`, returns the entire path, else returns only the
    last point of the path.
return_n_iter : bool, default=False
    Whether to return the number of iterations.
positive : bool, default=False
    Restrict coefficients to be >= 0.
    This option is only allowed with method 'lasso'. Note that the model
    coefficients will not converge to the ordinary-least-squares solution
    for small values of alpha. Only coefficients up to the smallest alpha
    value (`alphas_[alphas_ > 0.].min()` when fit_path=True) reached by
    the stepwise Lars-Lasso algorithm are typically in congruence with the
    solution of the coordinate descent `lasso_path` function.
Returns
-------
alphas : ndarray of shape (n_alphas + 1,)
    Maximum of covariances (in absolute value) at each iteration.
    `n_alphas` is either `max_iter`, `n_features`, or the
    number of nodes in the path with `alpha >= alpha_min`, whichever
    is smaller.
active : ndarray of shape (n_alphas,)
    Indices of active variables at the end of the path.
coefs : ndarray of shape (n_features, n_alphas + 1)
    Coefficients along the path.
n_iter : int
    Number of iterations run. Returned only if `return_n_iter` is set
    to True.
See Also
--------
lars_path_gram : Compute LARS path in the sufficient stats mode.
lasso_path : Compute Lasso path with coordinate descent.
LassoLars : Lasso model fit with Least Angle Regression a.k.a. Lars.
Lars : Least Angle Regression model a.k.a. LAR.
LassoLarsCV : Cross-validated Lasso, using the LARS algorithm.
LarsCV : Cross-validated Least Angle Regression model.
sklearn.decomposition.sparse_encode : Sparse coding.
References
----------
.. [1] "Least Angle Regression", Efron et al.
       http://statweb.stanford.edu/~tibs/ftp/lars.pdf
.. [2] `Wikipedia entry on the Least-angle regression
       <https://en.wikipedia.org/wiki/Least-angle_regression>`_
.. [3] `Wikipedia entry on the Lasso
       <https://en.wikipedia.org/wiki/Lasso_(statistics)>`_
Examples
--------
>>> from sklearn.linear_model import lars_path
>>> from sklearn.datasets import make_regression
>>> X, y, true_coef = make_regression(
...    n_samples=100, n_features=5, n_informative=2, coef=True, random_state=0
...)
>>> true_coef
array([ 0.        ,  0.        ,  0.        , 97.9, 45.7])
>>> alphas, _, estimated_coef = lars_path(X, y)
>>> alphas.shape
(3,)
>>> estimated_coef
array([[ 0.     ,  0.     ,  0.     ],
       [ 0.     ,  0.     ,  0.     ],
       [ 0.     ,  0.     ,  0.     ],
       [ 0.     , 46.96, 97.99],
       [ 0.     ,  0.     , 45.70]])
Definition at line 63 of file _least_angle.py.
References _lars_path_solver().
Referenced by sklearn.linear_model._least_angle.Lars._fit(), _lars_path_residues(), and sklearn.linear_model._least_angle.LassoLarsIC.fit().
lars_path_gram()
sklearn.linear_model._least_angle.lars_path_gram (Xy, Gram, * , n_samples, max_iter = 500, alpha_min = 0, method = "lar", copy_X = True, eps = np.finfo(float).eps, copy_Gram = True, verbose = 0, return_path = True, return_n_iter = False, positive = False)
The lars_path in the sufficient stats mode.
The optimization objective for the case method='lasso' is::
(1 / (2 * n_samples)) * ||y - Xw||^2_2 + alpha * ||w||_1
in the case of method='lar', the objective function is only known in
the form of an implicit equation (see discussion in [1]_).
Read more in the :ref:`User Guide <least_angle_regression>`.
Parameters
----------
Xy : ndarray of shape (n_features,)
    `Xy = X.T @ y`.
Gram : ndarray of shape (n_features, n_features)
    `Gram = X.T @ X`.
n_samples : int
    Equivalent size of sample.
max_iter : int, default=500
    Maximum number of iterations to perform, set to infinity for no limit.
alpha_min : float, default=0
    Minimum correlation along the path. It corresponds to the
    regularization parameter alpha parameter in the Lasso.
method : {'lar', 'lasso'}, default='lar'
    Specifies the returned model. Select `'lar'` for Least Angle
    Regression, ``'lasso'`` for the Lasso.
copy_X : bool, default=True
    If `False`, `X` is overwritten.
eps : float, default=np.finfo(float).eps
    The machine-precision regularization in the computation of the
    Cholesky diagonal factors. Increase this for very ill-conditioned
    systems. Unlike the `tol` parameter in some iterative
    optimization-based algorithms, this parameter does not control
    the tolerance of the optimization.
copy_Gram : bool, default=True
    If `False`, `Gram` is overwritten.
verbose : int, default=0
    Controls output verbosity.
return_path : bool, default=True
    If `return_path==True` returns the entire path, else returns only the
    last point of the path.
return_n_iter : bool, default=False
    Whether to return the number of iterations.
positive : bool, default=False
    Restrict coefficients to be >= 0.
    This option is only allowed with method 'lasso'. Note that the model
    coefficients will not converge to the ordinary-least-squares solution
    for small values of alpha. Only coefficients up to the smallest alpha
    value (`alphas_[alphas_ > 0.].min()` when `fit_path=True`) reached by
    the stepwise Lars-Lasso algorithm are typically in congruence with the
    solution of the coordinate descent lasso_path function.
Returns
-------
alphas : ndarray of shape (n_alphas + 1,)
    Maximum of covariances (in absolute value) at each iteration.
    `n_alphas` is either `max_iter`, `n_features` or the
    number of nodes in the path with `alpha >= alpha_min`, whichever
    is smaller.
active : ndarray of shape (n_alphas,)
    Indices of active variables at the end of the path.
coefs : ndarray of shape (n_features, n_alphas + 1)
    Coefficients along the path.
n_iter : int
    Number of iterations run. Returned only if `return_n_iter` is set
    to True.
See Also
--------
lars_path_gram : Compute LARS path.
lasso_path : Compute Lasso path with coordinate descent.
LassoLars : Lasso model fit with Least Angle Regression a.k.a. Lars.
Lars : Least Angle Regression model a.k.a. LAR.
LassoLarsCV : Cross-validated Lasso, using the LARS algorithm.
LarsCV : Cross-validated Least Angle Regression model.
sklearn.decomposition.sparse_encode : Sparse coding.
References
----------
.. [1] "Least Angle Regression", Efron et al.
       http://statweb.stanford.edu/~tibs/ftp/lars.pdf
.. [2] `Wikipedia entry on the Least-angle regression
       <https://en.wikipedia.org/wiki/Least-angle_regression>`_
.. [3] `Wikipedia entry on the Lasso
       <https://en.wikipedia.org/wiki/Lasso_(statistics)>`_
Examples
--------
>>> from sklearn.linear_model import lars_path_gram
>>> from sklearn.datasets import make_regression
>>> X, y, true_coef = make_regression(
...    n_samples=100, n_features=5, n_informative=2, coef=True, random_state=0
...)
>>> true_coef
array([ 0.        ,  0.        ,  0.        , 97.9, 45.7])
>>> alphas, _, estimated_coef = lars_path_gram(X.T @ y, X.T @ X, n_samples=100)
>>> alphas.shape
(3,)
>>> estimated_coef
array([[ 0.     ,  0.     ,  0.     ],
       [ 0.     ,  0.     ,  0.     ],
       [ 0.     ,  0.     ,  0.     ],
       [ 0.     , 46.96, 97.99],
       [ 0.     ,  0.     , 45.70]])
Definition at line 253 of file _least_angle.py.
References _lars_path_solver().
Variable Documentation
SOLVE_TRIANGULAR_ARGS
dict sklearn.linear_model._least_angle.SOLVE_TRIANGULAR_ARGS = {"check_finite": False}
Definition at line 41 of file _least_angle.py.