Code Cloning Analysis: scipy.sparse._data._minmax_mixin Class Reference
scipy.sparse._data._minmax_mixin Class Reference
Public Member Functions
max (self, axis=None, out=None)
min (self, axis=None, out=None)
nanmax (self, axis=None, out=None)
nanmin (self, axis=None, out=None)
argmax (self, axis=None, out=None)
argmin (self, axis=None, out=None)
Public Attributes
shape
int nnz = 0:
Protected Member Functions
_min_or_max_axis (self, axis, min_or_max)
_min_or_max (self, axis, out, min_or_max)
_arg_min_or_max_axis (self, axis, argmin_or_argmax, compare)
_arg_min_or_max (self, axis, out, argmin_or_argmax, compare)
Detailed Description
Mixin for min and max methods.
These are not implemented for dia_matrix, hence the separate class.
Definition at line 172 of file _data.py.
Member Function Documentation
_arg_min_or_max()
scipy.sparse._data._minmax_mixin._arg_min_or_max (self, axis, out, argmin_or_argmax, compare) protected
Definition at line 271 of file _data.py.
Referenced by argmax(), and argmin().
_arg_min_or_max_axis()
scipy.sparse._data._minmax_mixin._arg_min_or_max_axis (self, axis, argmin_or_argmax, compare) protected
Definition at line 234 of file _data.py.
_min_or_max()
scipy.sparse._data._minmax_mixin._min_or_max (self, axis, out, min_or_max) protected
Definition at line 207 of file _data.py.
Referenced by max(), min(), nanmax(), and nanmin().
_min_or_max_axis()
scipy.sparse._data._minmax_mixin._min_or_max_axis (self, axis, min_or_max) protected
Definition at line 178 of file _data.py.
argmax()
scipy.sparse._data._minmax_mixin.argmax (self, axis = None, out = None)
Return indices of maximum elements along an axis.
Implicit zero elements are also taken into account. If there are
several maximum values, the index of the first occurrence is returned.
Parameters
----------
axis : {-2, -1, 0, 1, None}, optional
    Axis along which the argmax is computed. If None (default), index
    of the maximum element in the flatten data is returned.
out : None, optional
    This argument is in the signature *solely* for NumPy
    compatibility reasons. Do not pass in anything except for
    the default value, as this argument is not used.
Returns
-------
ind : numpy.matrix or int
    Indices of maximum elements. If matrix, its size along `axis` is 1.
Definition at line 456 of file _data.py.
References _arg_min_or_max().
argmin()
scipy.sparse._data._minmax_mixin.argmin (self, axis = None, out = None)
Return indices of minimum elements along an axis.
Implicit zero elements are also taken into account. If there are
several minimum values, the index of the first occurrence is returned.
Parameters
----------
axis : {-2, -1, 0, 1, None}, optional
    Axis along which the argmin is computed. If None (default), index
    of the minimum element in the flatten data is returned.
out : None, optional
    This argument is in the signature *solely* for NumPy
    compatibility reasons. Do not pass in anything except for
    the default value, as this argument is not used.
Returns
-------
 ind : numpy.matrix or int
    Indices of minimum elements. If matrix, its size along `axis` is 1.
Definition at line 479 of file _data.py.
References _arg_min_or_max().
max()
scipy.sparse._data._minmax_mixin.max (self, axis = None, out = None)
Return the maximum of the matrix or maximum along an axis.
This takes all elements into account, not just the non-zero ones.
Parameters
----------
axis : {-2, -1, 0, 1, None} optional
    Axis along which the sum is computed. The default is to
    compute the maximum over all the matrix elements, returning
    a scalar (i.e., `axis` = `None`).
out : None, optional
    This argument is in the signature *solely* for NumPy
    compatibility reasons. Do not pass in anything except
    for the default value, as this argument is not used.
Returns
-------
amax : coo_matrix or scalar
    Maximum of `a`. If `axis` is None, the result is a scalar value.
    If `axis` is given, the result is a sparse.coo_matrix of dimension
    ``a.ndim - 1``.
See Also
--------
min : The minimum value of a sparse matrix along a given axis.
numpy.matrix.max : NumPy's implementation of 'max' for matrices
Definition at line 316 of file _data.py.
References _min_or_max().
Referenced by scipy.sparse._coo._coo_base._check(), scipy.sparse._csr._csr_base._getcol(), scipy.sparse._bsr._bsr_base.check_format(), scipy.sparse._compressed._cs_matrix.check_format(), scipy.sparse._bsr._bsr_base.diagonal(), scipy.sparse._compressed._cs_matrix.diagonal(), scipy.sparse._coo._coo_base.diagonal(), scipy.sparse._coo._coo_base.reshape(), scipy.sparse._csr._csr_base.tobsr(), scipy.sparse._bsr._bsr_base.tocoo(), scipy.sparse._coo._coo_base.tocsc(), scipy.sparse._csr._csr_base.tocsc(), scipy.sparse._bsr._bsr_base.tocsr(), scipy.sparse._coo._coo_base.tocsr(), scipy.sparse._csc._csc_base.tocsr(), and scipy.sparse._coo._coo_base.todia().
min()
scipy.sparse._data._minmax_mixin.min (self, axis = None, out = None)
Return the minimum of the matrix or maximum along an axis.
This takes all elements into account, not just the non-zero ones.
Parameters
----------
axis : {-2, -1, 0, 1, None} optional
    Axis along which the sum is computed. The default is to
    compute the minimum over all the matrix elements, returning
    a scalar (i.e., `axis` = `None`).
out : None, optional
    This argument is in the signature *solely* for NumPy
    compatibility reasons. Do not pass in anything except for
    the default value, as this argument is not used.
Returns
-------
amin : coo_matrix or scalar
    Minimum of `a`. If `axis` is None, the result is a scalar value.
    If `axis` is given, the result is a sparse.coo_matrix of dimension
    ``a.ndim - 1``.
See Also
--------
max : The maximum value of a sparse matrix along a given axis.
numpy.matrix.min : NumPy's implementation of 'min' for matrices
Definition at line 348 of file _data.py.
References _min_or_max().
Referenced by scipy.sparse._coo._coo_base._check(), scipy.sparse._compressed._cs_matrix._divide_sparse(), scipy.sparse._compressed._cs_matrix._setdiag(), scipy.sparse._coo._coo_base._setdiag(), scipy.sparse._bsr._bsr_base.check_format(), scipy.sparse._compressed._cs_matrix.check_format(), scipy.sparse._bsr._bsr_base.diagonal(), scipy.sparse._compressed._cs_matrix.diagonal(), and scipy.sparse._coo._coo_base.diagonal().
nanmax()
scipy.sparse._data._minmax_mixin.nanmax (self, axis = None, out = None)
Return the maximum of the matrix or maximum along an axis, ignoring any
NaNs. This takes all elements into account, not just the non-zero
ones.
.. versionadded:: 1.11.0
Parameters
----------
axis : {-2, -1, 0, 1, None} optional
    Axis along which the maximum is computed. The default is to
    compute the maximum over all the matrix elements, returning
    a scalar (i.e., `axis` = `None`).
out : None, optional
    This argument is in the signature *solely* for NumPy
    compatibility reasons. Do not pass in anything except
    for the default value, as this argument is not used.
Returns
-------
amax : coo_matrix or scalar
    Maximum of `a`. If `axis` is None, the result is a scalar value.
    If `axis` is given, the result is a sparse.coo_matrix of dimension
    ``a.ndim - 1``.
See Also
--------
nanmin : The minimum value of a sparse matrix along a given axis,
         ignoring NaNs.
max : The maximum value of a sparse matrix along a given axis,
      propagating NaNs.
numpy.nanmax : NumPy's implementation of 'nanmax'.
Definition at line 380 of file _data.py.
References _min_or_max().
nanmin()
scipy.sparse._data._minmax_mixin.nanmin (self, axis = None, out = None)
Return the minimum of the matrix or minimum along an axis, ignoring any
NaNs. This takes all elements into account, not just the non-zero
ones.
.. versionadded:: 1.11.0
Parameters
----------
axis : {-2, -1, 0, 1, None} optional
    Axis along which the minimum is computed. The default is to
    compute the minimum over all the matrix elements, returning
    a scalar (i.e., `axis` = `None`).
out : None, optional
    This argument is in the signature *solely* for NumPy
    compatibility reasons. Do not pass in anything except for
    the default value, as this argument is not used.
Returns
-------
amin : coo_matrix or scalar
    Minimum of `a`. If `axis` is None, the result is a scalar value.
    If `axis` is given, the result is a sparse.coo_matrix of dimension
    ``a.ndim - 1``.
See Also
--------
nanmax : The maximum value of a sparse matrix along a given axis,
         ignoring NaNs.
min : The minimum value of a sparse matrix along a given axis,
      propagating NaNs.
numpy.nanmin : NumPy's implementation of 'nanmin'.
Definition at line 418 of file _data.py.
References _min_or_max().
Member Data Documentation
nnz
int scipy.sparse._data._minmax_mixin.nnz = 0:
Definition at line 219 of file _data.py.
shape
scipy.sparse._data._minmax_mixin.shape
Definition at line 215 of file _data.py.
Referenced by scipy.sparse.linalg._interface.LinearOperator.__init__(), scipy.stats._multivariate.multivariate_t_frozen.__init__(), pandas.io.pytables.Fixed.__repr__(), scipy.sparse.linalg._interface._CustomLinearOperator._adjoint(), pandas.core.internals.managers.BaseBlockManager._combine(), scipy.sparse._index.IndexMixin._getcol(), scipy.sparse._index.IndexMixin._getrow(), scipy.sparse.linalg._interface.LinearOperator._init_dtype(), pandas.core.internals.managers.BlockManager._interleave(), sklearn.linear_model._ridge._XT_CenterStackOp._matmat(), sklearn.linear_model._ridge._XT_CenterStackOp._matvec(), scipy.sparse._index.IndexMixin._raise_on_1d_array_slice(), scipy.sparse.linalg._interface.LinearOperator._rdot(), pandas.core.arrays.timedeltas.TimedeltaArray._scalar_divlike_op(), pandas.core.internals.managers.BaseBlockManager._slice_take_blocks_ax0(), pandas.core.internals.array_manager.ArrayManager.as_array(), pandas.core.internals.managers.BlockManager.as_array(), pandas.core.internals.blocks.Block.astype(), pandas.core.internals.blocks.Block.convert(), pandas.core.indexes.multi.MultiIndex.drop(), numpy.core._internal._ctypes.get_shape(), pandas.core.internals.array_manager.ArrayManager.idelete(), pandas.core.internals.array_manager.SingleArrayManager.idelete(), pandas.core.internals.managers.BlockManager.idelete(), pandas.core.internals.managers.BlockManager.iset(), pandas.core.internals.blocks.Block.make_block_same_class(), scipy.sparse.linalg._interface.LinearOperator.matmat(), scipy.sparse.linalg._interface.LinearOperator.matvec(), scipy.sparse.linalg._interface.LinearOperator.rmatmat(), scipy.sparse.linalg._interface.LinearOperator.rmatvec(), numpy.lib.arrayterator.Arrayterator.shape(), pandas.core.internals.blocks.Block.split_and_operate(), pandas.core.internals.managers.BaseBlockManager.take(), and scipy.optimize._lbfgsb_py.LbfgsInvHessProduct.todense().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/sparse/_data.py