Code Cloning Analysis: joblib.hashing.Hasher Class Reference
joblib.hashing.Hasher Class Reference
Public Member Functions
__init__ (self, hash_name="md5")
hash (self, obj, return_digest=True)
save (self, obj)
memoize (self, obj)
save_global (self, obj, name=None, pack=struct.pack)
save_set (self, set_items)
Public Attributes
stream = io.BytesIO()
Static Public Attributes
dispatch = Pickler.dispatch.copy()
Protected Member Functions
_batch_setitems (self, items, *args)
Protected Attributes
_hash = hashlib.new(hash_name, usedforsecurity=False)
Detailed Description
A subclass of pickler, to do cryptographic hashing, rather than
pickling. This is used to produce a unique hash of the given
Python object that is not necessarily cryptographically secure.
Definition at line 47 of file hashing.py.
Constructor & Destructor Documentation
__init__()
joblib.hashing.Hasher.__init__ (self, hash_name = "md5")
Definition at line 53 of file hashing.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_batch_setitems()
joblib.hashing.Hasher._batch_setitems (self, items, * args) protected
Definition at line 136 of file hashing.py.
hash()
joblib.hashing.Hasher.hash (self, obj, return_digest = True)
Definition at line 62 of file hashing.py.
memoize()
joblib.hashing.Hasher.memoize (self, obj)
Definition at line 92 of file hashing.py.
save()
joblib.hashing.Hasher.save (self, obj)
Reimplemented in joblib.hashing.NumpyHasher.
Definition at line 73 of file hashing.py.
Referenced by PIL.Image.Image._repr_image(), PIL.Image.Image.close(), joblib.externals.cloudpickle.cloudpickle.Pickler.reducer_override(), matplotlib.animation.Animation.to_html5_video(), and matplotlib.animation.Animation.to_jshtml().
save_global()
joblib.hashing.Hasher.save_global (self, obj, name = None, pack = struct.pack)
Definition at line 103 of file hashing.py.
save_set()
joblib.hashing.Hasher.save_set (self, set_items)
Definition at line 151 of file hashing.py.
Member Data Documentation
_hash
joblib.hashing.Hasher._hash = hashlib.new(hash_name, usedforsecurity=False) protected
Definition at line 60 of file hashing.py.
Referenced by pip._vendor.rich.style.Style.clear_meta_and_links(), pip._vendor.rich.style.Style.copy(), pip._vendor.rich.style.Style.pick_first(), and joblib.hashing.NumpyHasher.save().
dispatch
joblib.hashing.Hasher.dispatch = Pickler.dispatch.copy() static
Definition at line 124 of file hashing.py.
Referenced by joblib.pool.CustomizablePickler.register().
stream
joblib.hashing.Hasher.stream = io.BytesIO()
Definition at line 54 of file hashing.py.
Referenced by pip._vendor.urllib3.response.HTTPResponse.geturl(), PIL.FpxImagePlugin.FpxImageFile.load(), pip._vendor.requests.sessions.Session.merge_environment_settings(), pip._vendor.requests.sessions.Session.send(), and pip._vendor.colorama.ansitowin32.AnsiToWin32.should_wrap().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/joblib/hashing.py