Code Cloning Analysis: pandas.core.arrays.categorical Namespace Reference
pandas.core.arrays.categorical Namespace Reference
Classes
class Categorical
class CategoricalAccessor
Functions
_cat_compare_op (op)
bool contains (cat, key, container)
np.ndarray _get_codes_for_values (Index|Series|ExtensionArray|np.ndarray values, Index categories)
np.ndarray recode_for_categories (np.ndarray codes, old_categories, new_categories, bool copy=True)
tuple[np.ndarray, Index] factorize_from_iterable (values)
tuple[list[np.ndarray], list[Index]] factorize_from_iterables (iterables)
Variables
ordered
categories = fill_value
Function Documentation
_cat_compare_op()
pandas.core.arrays.categorical._cat_compare_op (op) protected
Definition at line 122 of file categorical.py.
_get_codes_for_values()
np.ndarray pandas.core.arrays.categorical._get_codes_for_values (Index | Series | ExtensionArray | np.ndarray values, Index categories) protected
utility routine to turn values into codes given the specified categories
If `values` is known to be a Categorical, use recode_for_categories instead.
Definition at line 2982 of file categorical.py.
contains()
bool pandas.core.arrays.categorical.contains (cat, key, container)
Helper for membership check for ``key`` in ``cat``.
This is a helper method for :method:`__contains__`
and :class:`CategoricalIndex.__contains__`.
Returns True if ``key`` is in ``cat.categories`` and the
location of ``key`` in ``categories`` is in ``container``.
Parameters
----------
cat : :class:`Categorical`or :class:`categoricalIndex`
key : a hashable object
    The key to check membership for.
container : Container (e.g. list-like or mapping)
    The container to check for membership in.
Returns
-------
is_in : bool
    True if ``key`` is in ``self.categories`` and location of
    ``key`` in ``categories`` is in ``container``, else False.
Notes
-----
This method does not check for NaN values. Do that separately
before calling this method.
Definition at line 195 of file categorical.py.
Referenced by pandas.core.arrays.categorical.Categorical.__contains__().
factorize_from_iterable()
tuple[np.ndarray, Index] pandas.core.arrays.categorical.factorize_from_iterable (values)
Factorize an input `values` into `categories` and `codes`. Preserves
categorical dtype in `categories`.
Parameters
----------
values : list-like
Returns
-------
codes : ndarray
categories : Index
    If `values` has a categorical dtype, then `categories` is
    a CategoricalIndex keeping the categories and order of `values`.
Definition at line 3038 of file categorical.py.
Referenced by factorize_from_iterables().
factorize_from_iterables()
tuple[list[np.ndarray], list[Index]] pandas.core.arrays.categorical.factorize_from_iterables (iterables)
A higher-level wrapper over `factorize_from_iterable`.
Parameters
----------
iterables : list-like of list-likes
Returns
-------
codes : list of ndarrays
categories : list of Indexes
Notes
-----
See `factorize_from_iterable` for more info.
Definition at line 3081 of file categorical.py.
References factorize_from_iterable().
recode_for_categories()
np.ndarray pandas.core.arrays.categorical.recode_for_categories (np.ndarray codes, old_categories, new_categories, bool copy = True)
Convert a set of codes for to a new set of categories
Parameters
----------
codes : np.ndarray
old_categories, new_categories : Index
copy: bool, default True
    Whether to copy if the codes are unchanged.
Returns
-------
new_codes : np.ndarray[np.int64]
Examples
--------
>>> old_cat = pd.Index(['b', 'a', 'c'])
>>> new_cat = pd.Index(['a', 'b'])
>>> codes = np.array([0, 1, 1, 2])
>>> recode_for_categories(codes, old_cat, new_cat)
array([ 1,  0,  0, -1], dtype=int8)
Definition at line 2995 of file categorical.py.
Referenced by pandas.core.arrays.categorical.Categorical._encode_with_my_categories(), pandas.core.arrays.categorical.Categorical._from_inferred_categories(), pandas.core.arrays.categorical.Categorical._set_dtype(), pandas.core.arrays.categorical.Categorical.isin(), and pandas.core.arrays.categorical.Categorical.set_categories().
Variable Documentation
categories
pandas.core.arrays.categorical.categories = fill_value
Definition at line 161 of file categorical.py.
ordered
pandas.core.arrays.categorical.ordered
Definition at line 133 of file categorical.py.