Code Cloning Analysis: fontTools.ttLib.tables.otTables.RearrangementMorphAction Class Reference
fontTools.ttLib.tables.otTables.RearrangementMorphAction Class Reference
Public Member Functions
__init__ (self)
compile (self, writer, font, actionIndex)
decompile (self, reader, font, actionReader)
toXML (self, xmlWriter, font, attrs, name)
fromXML (self, name, attrs, content, font)
Public Attributes
int NewState = 0
int Verb = 0
bool MarkFirst = False
bool DontAdvance = False
bool MarkLast = False
int ReservedFlags = 0
Static Public Attributes
int staticSize = 4
int actionHeaderSize = 0
Static Protected Attributes
dict _VERBS
Static Protected Attributes inherited from fontTools.ttLib.tables.otTables.AATAction
_FLAGS = None
Additional Inherited Members
Static Public Member Functions inherited from fontTools.ttLib.tables.otTables.AATAction
compileActions (font, states)
Protected Member Functions inherited from fontTools.ttLib.tables.otTables.AATAction
_writeFlagsToXML (self, xmlWriter)
_setFlag (self, flag)
Detailed Description
Definition at line 471 of file otTables.py.
Constructor & Destructor Documentation
__init__()
fontTools.ttLib.tables.otTables.RearrangementMorphAction.__init__ (self)
Definition at line 495 of file otTables.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
compile()
fontTools.ttLib.tables.otTables.RearrangementMorphAction.compile (self, writer, font, actionIndex)
Definition at line 503 of file otTables.py.
Referenced by fontTools.ttLib.tables.TupleVariation.TupleVariation.getCoordWidth(), and PIL.FontFile.FontFile.save().
decompile()
fontTools.ttLib.tables.otTables.RearrangementMorphAction.decompile (self, reader, font, actionReader)
Definition at line 516 of file otTables.py.
Referenced by fontTools.ttLib.tables._c_m_a_p.CmapSubtable.newSubtable().
fromXML()
fontTools.ttLib.tables.otTables.RearrangementMorphAction.fromXML (self, name, attrs, content, font)
Definition at line 540 of file otTables.py.
toXML()
fontTools.ttLib.tables.otTables.RearrangementMorphAction.toXML (self, xmlWriter, font, attrs, name)
Definition at line 526 of file otTables.py.
Member Data Documentation
_VERBS
dict fontTools.ttLib.tables.otTables.RearrangementMorphAction._VERBS static protected
Initial value:
=  {
        0: "no change",
        1: "Ax ⇒ xA",
        2: "xD ⇒ Dx",
        3: "AxD ⇒ DxA",
        4: "ABx ⇒ xAB",
        5: "ABx ⇒ xBA",
        6: "xCD ⇒ CDx",
        7: "xCD ⇒ DCx",
        8: "AxCD ⇒ CDxA",
        9: "AxCD ⇒ DCxA",
        10: "ABxD ⇒ DxAB",
        11: "ABxD ⇒ DxBA",
        12: "ABxCD ⇒ CDxAB",
        13: "ABxCD ⇒ CDxBA",
        14: "ABxCD ⇒ DCxAB",
        15: "ABxCD ⇒ DCxBA",
    }
Definition at line 476 of file otTables.py.
actionHeaderSize
int fontTools.ttLib.tables.otTables.RearrangementMorphAction.actionHeaderSize = 0 static
Definition at line 473 of file otTables.py.
DontAdvance
bool fontTools.ttLib.tables.otTables.RearrangementMorphAction.DontAdvance = False
Definition at line 499 of file otTables.py.
MarkFirst
bool fontTools.ttLib.tables.otTables.RearrangementMorphAction.MarkFirst = False
Definition at line 498 of file otTables.py.
MarkLast
bool fontTools.ttLib.tables.otTables.RearrangementMorphAction.MarkLast = False
Definition at line 500 of file otTables.py.
NewState
fontTools.ttLib.tables.otTables.RearrangementMorphAction.NewState = 0
Definition at line 496 of file otTables.py.
ReservedFlags
int fontTools.ttLib.tables.otTables.RearrangementMorphAction.ReservedFlags = 0
Definition at line 501 of file otTables.py.
staticSize
int fontTools.ttLib.tables.otTables.RearrangementMorphAction.staticSize = 4 static
Definition at line 472 of file otTables.py.
Referenced by fontTools.ttLib.tables.otConverters.BaseConverter.readArray().
Verb
int fontTools.ttLib.tables.otTables.RearrangementMorphAction.Verb = 0
Definition at line 497 of file otTables.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ttLib/tables/otTables.py