Code Cloning Analysis: llama Namespace Reference
llama Namespace Reference
Classes
class Confidence
Defines the Confidence class, which is used to determine the structured ouput.
Functions
safe_parse_response (response)
Translates the given response from the model into the proper dictionary format.
truncate_code (code, max_lines=50)
Truncates code to a limited number of lines for prompt fitting.
ensemble_assessment (code1, code2, model_name, n=3)
Performs multiple assessments and aggregates predictions using voting.
determine_similarity (results)
Determines the predicted type and binary similarity from score dictionary.
rag_similarity_assessment (code1, code2, model_name)
Sends a prompt to the LLM to classify clone type and score similarities.
Variables
str DATA_DIR = "/projappl/project_2014646/shreya/data/data"
str PAIRS_CSV = "/projappl/project_2014646/shreya/pairs.csv"
str GROUND_TRUTH_CSV = "/projappl/project_2014646/shreya/ground_truth.csv"
list LLMS
pairs_df = pd.read_csv(PAIRS_CSV)
DataFrame of file pairs to compare.
ground_truth_df = pd.read_csv(GROUND_TRUTH_CSV)
DataFrame containing ground truth similarity labels.
ground_truth_map = dict(zip(ground_truth_df['pair-id'], ground_truth_df['similar']))
Dictionary mapping pair IDs to binary similarity values.
list all_truth = []
list all_preds = []
str output = f"/projappl/project_2014646/shreya/results/RAG_vs_CodeNet_binary_results_llama_iteration_{iteration}.csv"
newline
writer = csv.writer(outfile)
file1_path = os.path.join(DATA_DIR, row['file1'])
file2_path = os.path.join(DATA_DIR, row['file2'])
pair_id = row['pair-id']
encoding
errors
code1 = truncate_code(f1.read())
code2 = truncate_code(f2.read())
ground_truth_sim = ground_truth_map.get(pair_id, "Unknown")
results
predicted_type
predicted_sim
model_name
n
acc = accuracy_score(all_truth, all_preds)
Calculate and write evaluation metrics for the threshold.
prec = precision_score(all_truth, all_preds)
rec = recall_score(all_truth, all_preds)
f1 = f1_score(all_truth, all_preds)
mse = mean_squared_error(all_truth, all_preds)
file
Function Documentation
determine_similarity()
llama.determine_similarity (results)
Determines the predicted type and binary similarity from score dictionary.
Parameters
results Dictionary mapping clone types to similarity scores.
Returns
Tuple of (predicted type, binary similarity: 1 if above threshold, else 0).
Definition at line 112 of file llama.py.
Referenced by rag_similarity_assessment().
ensemble_assessment()
llama.ensemble_assessment (code1, code2, model_name, n = 3)
Performs multiple assessments and aggregates predictions using voting.
Parameters
code1 First code string.
code2 Second code string.
model_name The name of the LLM model to use.
thr Threshold for similarity.
n Number of repeated assessments for ensemble.
Returns
Tuple of (average type scores, majority predicted type, majority binary similarity).
Definition at line 88 of file llama.py.
References rag_similarity_assessment().
Referenced by rag_similarity_assessment().
rag_similarity_assessment()
llama.rag_similarity_assessment (code1, code2, model_name)
Sends a prompt to the LLM to classify clone type and score similarities.
Parameters
code1 First code snippet to evaluate.
code2 Second code snippet to evaluate.
model_name Name of the language model to query.
thr Threshold for determining clone similarity.
Returns
Tuple of (type score dictionary, predicted type, binary similarity).
Definition at line 123 of file llama.py.
References determine_similarity(), ensemble_assessment(), safe_parse_response(), and truncate_code().
Referenced by ensemble_assessment().
safe_parse_response()
llama.safe_parse_response (response)
Translates the given response from the model into the proper dictionary format.
Parameters
response The RAG output.
Definition at line 52 of file llama.py.
Referenced by rag_similarity_assessment().
truncate_code()
llama.truncate_code (code, max_lines = 50)
Truncates code to a limited number of lines for prompt fitting.
Parameters
code Full code string.
max_lines Maximum number of lines to retain.
Returns
Truncated code string.
Definition at line 78 of file llama.py.
Referenced by rag_similarity_assessment().
Variable Documentation
acc
llama.acc = accuracy_score(all_truth, all_preds)
Calculate and write evaluation metrics for the threshold.
Definition at line 216 of file llama.py.
all_preds
list llama.all_preds = []
Definition at line 178 of file llama.py.
all_truth
list llama.all_truth = []
Definition at line 177 of file llama.py.
code1
llama.code1 = truncate_code(f1.read())
Definition at line 193 of file llama.py.
code2
llama.code2 = truncate_code(f2.read())
Definition at line 194 of file llama.py.
DATA_DIR
str llama.DATA_DIR = "/projappl/project_2014646/shreya/data/data"
Definition at line 30 of file llama.py.
encoding
llama.encoding
Definition at line 191 of file llama.py.
errors
llama.errors
Definition at line 191 of file llama.py.
f1
llama.f1 = f1_score(all_truth, all_preds)
Definition at line 219 of file llama.py.
file
llama.file
Definition at line 222 of file llama.py.
file1_path
llama.file1_path = os.path.join(DATA_DIR, row['file1'])
Definition at line 187 of file llama.py.
file2_path
llama.file2_path = os.path.join(DATA_DIR, row['file2'])
Definition at line 188 of file llama.py.
GROUND_TRUTH_CSV
str llama.GROUND_TRUTH_CSV = "/projappl/project_2014646/shreya/ground_truth.csv"
Definition at line 32 of file llama.py.
ground_truth_df
llama.ground_truth_df = pd.read_csv(GROUND_TRUTH_CSV)
DataFrame containing ground truth similarity labels.
Definition at line 45 of file llama.py.
ground_truth_map
llama.ground_truth_map = dict(zip(ground_truth_df['pair-id'], ground_truth_df['similar']))
Dictionary mapping pair IDs to binary similarity values.
Definition at line 49 of file llama.py.
ground_truth_sim
llama.ground_truth_sim = ground_truth_map.get(pair_id, "Unknown")
Definition at line 199 of file llama.py.
LLMS
list llama.LLMS
Initial value:
=  [
    "llama3.1:latest"# < vllm model name
]
Definition at line 34 of file llama.py.
model_name
llama.model_name
Definition at line 204 of file llama.py.
mse
llama.mse = mean_squared_error(all_truth, all_preds)
Definition at line 220 of file llama.py.
n
llama.n
Definition at line 204 of file llama.py.
newline
llama.newline
Definition at line 180 of file llama.py.
output
str llama.output = f"/projappl/project_2014646/shreya/results/RAG_vs_CodeNet_binary_results_llama_iteration_{iteration}.csv"
Definition at line 179 of file llama.py.
pair_id
llama.pair_id = row['pair-id']
Definition at line 189 of file llama.py.
PAIRS_CSV
str llama.PAIRS_CSV = "/projappl/project_2014646/shreya/pairs.csv"
Definition at line 31 of file llama.py.
pairs_df
llama.pairs_df = pd.read_csv(PAIRS_CSV)
DataFrame of file pairs to compare.
Definition at line 41 of file llama.py.
prec
llama.prec = precision_score(all_truth, all_preds)
Definition at line 217 of file llama.py.
predicted_sim
llama.predicted_sim
Definition at line 204 of file llama.py.
predicted_type
llama.predicted_type
Definition at line 204 of file llama.py.
rec
llama.rec = recall_score(all_truth, all_preds)
Definition at line 218 of file llama.py.
results
llama.results
Definition at line 204 of file llama.py.
writer
llama.writer = csv.writer(outfile)
Definition at line 181 of file llama.py.