Code Cloning Analysis: fontTools.varLib.instancer.NormalizedAxisLimits Class Reference
fontTools.varLib.instancer.NormalizedAxisLimits Class Reference
Public Member Functions
__init__ (self, *args, **kwargs)
Public Member Functions inherited from fontTools.varLib.instancer._BaseAxisLimits
AxisTriple __getitem__ (self, str key)
Iterable[str] __iter__ (self)
int __len__ (self)
str __repr__ (self)
str __str__ (self)
Dict[str, float] defaultLocation (self)
Dict[str, float] pinnedLocation (self)
Public Member Functions inherited from fontTools.varLib.instancer.AxisTriple
__post_init__ (self)
__getitem__ (self, i)
__len__ (self)
__repr__ (self)
"AxisTriple" expand (cls, Union["AxisTriple", float, # pin axis at single value, same as min==default==max Tuple[float, float], #(min, max), restrict axis and keep default Tuple[float, float, float], #(min, default, max)] v)
"AxisTriple" limitRangeAndPopulateDefaults (self, fvarTriple)
Additional Inherited Members
Static Public Attributes inherited from fontTools.varLib.instancer.AxisTriple
Optional minimum [float]
Optional default [float]
Optional maximum [float]
Protected Member Functions inherited from fontTools.varLib.instancer.AxisTriple
_replace (self, **kwargs)
Protected Attributes inherited from fontTools.varLib.instancer._BaseAxisLimits
_data
Detailed Description
Maps axis tags (str) to NormalizedAxisTriple values.
Definition at line 465 of file __init__.py.
Constructor & Destructor Documentation
__init__()
fontTools.varLib.instancer.NormalizedAxisLimits.__init__ (self, * args, ** kwargs)
Definition at line 468 of file __init__.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/varLib/instancer/__init__.py