Code Cloning Analysis: fontTools.misc.loggingTools.LevelFormatter Class Reference
fontTools.misc.loggingTools.LevelFormatter Class Reference
Public Member Functions
__init__ (self, fmt=None, datefmt=None, style="%")
format (self, record)
Public Attributes
default_format = self._fmt
dict custom_formats = {}
Protected Attributes
_fmt = fmt
_style = PercentStyle(fmt)
Detailed Description
Log formatter with level-specific formatting.
Formatter class which optionally takes a dict of logging levels to
format strings, allowing to customise the log records appearance for
specific levels.
Attributes:
        fmt: A dictionary mapping logging levels to format strings.
                The ``*`` key identifies the default format string.
        datefmt: As per py:class:`logging.Formatter`
        style: As per py:class:`logging.Formatter`
>>> import sys
>>> handler = logging.StreamHandler(sys.stdout)
>>> formatter = LevelFormatter(
...     fmt={
...         '*':     '[%(levelname)s] %(message)s',
...         'DEBUG': '%(name)s [%(levelname)s] %(message)s',
...         'INFO':  '%(message)s',
...     })
>>> handler.setFormatter(formatter)
>>> log = logging.getLogger('test')
>>> log.setLevel(logging.DEBUG)
>>> log.addHandler(handler)
>>> log.debug('this uses a custom format string')
test [DEBUG] this uses a custom format string
>>> log.info('this also uses a custom format string')
this also uses a custom format string
>>> log.warning("this one uses the default format string")
[WARNING] this one uses the default format string
Definition at line 22 of file loggingTools.py.
Constructor & Destructor Documentation
__init__()
fontTools.misc.loggingTools.LevelFormatter.__init__ (self, fmt = None, datefmt = None, style = "%")
Definition at line 56 of file loggingTools.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
format()
fontTools.misc.loggingTools.LevelFormatter.format (self, record)
Definition at line 78 of file loggingTools.py.
Referenced by fontTools.ttLib.sfnt.SFNTReader.__getitem__(), scipy.io._mmio.MMFile._init_attrs(), scipy.sparse._base._spbase.asformat(), scipy.sparse._base._spbase.astype(), pip._internal.utils.logging.RichPipStreamHandler.emit(), pip._vendor.rich.logging.RichHandler.emit(), scipy.sparse._base._spbase.getformat(), scipy.sparse._matrix.spmatrix.getformat(), scipy.sparse._base._spbase.nnz(), scipy.sparse._base._spbase.set_shape(), scipy.sparse._dok.dok_matrix.set_shape(), and scipy.sparse._matrix.spmatrix.set_shape().
Member Data Documentation
_fmt
fontTools.misc.loggingTools.LevelFormatter._fmt = fmt protected
Definition at line 82 of file loggingTools.py.
Referenced by matplotlib.widgets.RangeSlider._format(), and matplotlib.widgets.Slider._format().
_style
fontTools.misc.loggingTools.LevelFormatter._style = PercentStyle(fmt) protected
Definition at line 85 of file loggingTools.py.
custom_formats
dict fontTools.misc.loggingTools.LevelFormatter.custom_formats = {}
Definition at line 73 of file loggingTools.py.
default_format
fontTools.misc.loggingTools.LevelFormatter.default_format = self._fmt
Definition at line 72 of file loggingTools.py.
Referenced by fontTools.misc.loggingTools.Timer.formatTime().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/misc/loggingTools.py