Code Cloning Analysis: first_prompt Namespace Reference
first_prompt Namespace Reference
Classes
class Confidence
Defines the Confidence class, which is used to determine the structured ouput.
Functions
safe_parse_response (response)
Translates the given response from the model into the proper dictionary format.
ensemble_assessment (code1, code2, model_name, prompt, n=3)
Performs multiple assessments and aggregates predictions using voting.
determine_similarity (results)
rag_similarity_assessment (code1, code2, model_name, prompt)
Sends a prompt to the LLM to classify clone type and score similarities.
Variables
str DATA_DIR = "./data/data"
Path to the directory containing code files for similarity comparison.
str PAIRS_CSV = "./pairs.csv"
CSV file containing file pairs to compare.
str GROUND_TRUTH_CSV = "./ground_truth.csv"
CSV file containing ground truth similarity labels for file pairs.
list LLMS
List of model names to use for clone detection.
list PROMPTS
The first prompt we tested on.
pairs_df = pd.read_csv(PAIRS_CSV)
DataFrame of file pairs to compare.
ground_truth_df = pd.read_csv(GROUND_TRUTH_CSV)
DataFrame containing ground truth similarity labels.
ground_truth_map = dict(zip(ground_truth_df['pair-id'], ground_truth_df['similar']))
Dictionary mapping pair IDs to binary similarity values.
dict results_by_prompt = {i: {'truth': [], 'preds': []} for i in range(len(PROMPTS))}
Executes evaluation over prompts and saves results and metrics.
str output = f"./results/prompt_first_results_{LLMS[0]}_iteration_{iteration}.csv"
newline
writer = csv.writer(outfile)
file1_path = os.path.join(DATA_DIR, row['file1'])
file2_path = os.path.join(DATA_DIR, row['file2'])
pair_id = row['pair-id']
encoding
errors
code1 = f1.read()
code2 = f2.read()
ground_truth_sim = ground_truth_map.get(pair_id, "Unknown")
results
predicted_type
predicted_sim
model_name
prompt
n
str metrics_output = f'./results/prompt_first{LLMS[0]}_iteration_{iteration}.txt'
Calculate and write evaluation metrics for the threshold.
dict truth = results_by_prompt[prompt_id]['truth']
dict preds = results_by_prompt[prompt_id]['preds']
acc = accuracy_score(truth, preds)
prec = precision_score(truth, preds, zero_division=0)
rec = recall_score(truth, preds, zero_division=0)
f1s = f1_score(truth, preds, zero_division=0)
mse = mean_squared_error(truth, preds, zero_division=0)
file
Function Documentation
determine_similarity()
first_prompt.determine_similarity (results)
Definition at line 160 of file first_prompt.py.
ensemble_assessment()
first_prompt.ensemble_assessment (code1, code2, model_name, thr, n = 3)
Performs multiple assessments and aggregates predictions using voting.
Parameters
code1 First code string.
code2 Second code string.
model_name The name of the LLM model to use.
thr Threshold for similarity.
n Number of repeated assessments for ensemble.
Returns
Tuple of (average type scores, majority predicted type, majority binary similarity).
Definition at line 115 of file first_prompt.py.
References rag_similarity_assessment().
rag_similarity_assessment()
first_prompt.rag_similarity_assessment (code1, code2, model_name, thr)
Sends a prompt to the LLM to classify clone type and score similarities.
Parameters
code1 First code snippet to evaluate.
code2 Second code snippet to evaluate.
model_name Name of the language model to query.
thr Threshold for determining clone similarity.
Returns
Tuple of (type score dictionary, predicted type, binary similarity).
Definition at line 177 of file first_prompt.py.
References safe_parse_response().
Referenced by ensemble_assessment().
safe_parse_response()
first_prompt.safe_parse_response (response)
Translates the given response from the model into the proper dictionary format.
Parameters
response The RAG output.
Definition at line 86 of file first_prompt.py.
Referenced by rag_similarity_assessment().
Variable Documentation
acc
first_prompt.acc = accuracy_score(truth, preds)
Definition at line 243 of file first_prompt.py.
code1
first_prompt.code1 = f1.read()
Definition at line 216 of file first_prompt.py.
code2
first_prompt.code2 = f2.read()
Definition at line 217 of file first_prompt.py.
DATA_DIR
str first_prompt.DATA_DIR = "./data/data"
Path to the directory containing code files for similarity comparison.
Definition at line 26 of file first_prompt.py.
encoding
first_prompt.encoding
Definition at line 214 of file first_prompt.py.
errors
first_prompt.errors
Definition at line 214 of file first_prompt.py.
f1s
first_prompt.f1s = f1_score(truth, preds, zero_division=0)
Definition at line 246 of file first_prompt.py.
file
first_prompt.file
Definition at line 248 of file first_prompt.py.
file1_path
first_prompt.file1_path = os.path.join(DATA_DIR, row['file1'])
Definition at line 210 of file first_prompt.py.
file2_path
first_prompt.file2_path = os.path.join(DATA_DIR, row['file2'])
Definition at line 211 of file first_prompt.py.
GROUND_TRUTH_CSV
str first_prompt.GROUND_TRUTH_CSV = "./ground_truth.csv"
CSV file containing ground truth similarity labels for file pairs.
Definition at line 34 of file first_prompt.py.
ground_truth_df
first_prompt.ground_truth_df = pd.read_csv(GROUND_TRUTH_CSV)
DataFrame containing ground truth similarity labels.
Definition at line 76 of file first_prompt.py.
ground_truth_map
first_prompt.ground_truth_map = dict(zip(ground_truth_df['pair-id'], ground_truth_df['similar']))
Dictionary mapping pair IDs to binary similarity values.
Definition at line 80 of file first_prompt.py.
ground_truth_sim
first_prompt.ground_truth_sim = ground_truth_map.get(pair_id, "Unknown")
Definition at line 221 of file first_prompt.py.
LLMS
list first_prompt.LLMS
Initial value:
=  [
    "llama3.1:latest"
]
List of model names to use for clone detection.
Definition at line 38 of file first_prompt.py.
metrics_output
str first_prompt.metrics_output = f'./results/prompt_first{LLMS[0]}_iteration_{iteration}.txt'
Calculate and write evaluation metrics for the threshold.
Definition at line 237 of file first_prompt.py.
model_name
first_prompt.model_name
Definition at line 226 of file first_prompt.py.
mse
first_prompt.mse = mean_squared_error(truth, preds, zero_division=0)
Definition at line 247 of file first_prompt.py.
n
first_prompt.n
Definition at line 226 of file first_prompt.py.
newline
first_prompt.newline
Definition at line 201 of file first_prompt.py.
output
str first_prompt.output = f"./results/prompt_first_results_{LLMS[0]}_iteration_{iteration}.csv"
Definition at line 200 of file first_prompt.py.
pair_id
first_prompt.pair_id = row['pair-id']
Definition at line 212 of file first_prompt.py.
PAIRS_CSV
str first_prompt.PAIRS_CSV = "./pairs.csv"
CSV file containing file pairs to compare.
Definition at line 30 of file first_prompt.py.
pairs_df
first_prompt.pairs_df = pd.read_csv(PAIRS_CSV)
DataFrame of file pairs to compare.
Definition at line 72 of file first_prompt.py.
prec
first_prompt.prec = precision_score(truth, preds, zero_division=0)
Definition at line 244 of file first_prompt.py.
predicted_sim
first_prompt.predicted_sim
Definition at line 226 of file first_prompt.py.
predicted_type
first_prompt.predicted_type
Definition at line 226 of file first_prompt.py.
preds
dict first_prompt.preds = results_by_prompt[prompt_id]['preds']
Definition at line 241 of file first_prompt.py.
prompt
first_prompt.prompt
Definition at line 226 of file first_prompt.py.
PROMPTS
list first_prompt.PROMPTS
Initial value:
=  [
    # Prompt 1
]
The first prompt we tested on.
Definition at line 51 of file first_prompt.py.
rec
first_prompt.rec = recall_score(truth, preds, zero_division=0)
Definition at line 245 of file first_prompt.py.
results
first_prompt.results
Definition at line 226 of file first_prompt.py.
results_by_prompt
dict first_prompt.results_by_prompt = {i: {'truth': [], 'preds': []} for i in range(len(PROMPTS))}
Executes evaluation over prompts and saves results and metrics.
Definition at line 195 of file first_prompt.py.
truth
dict first_prompt.truth = results_by_prompt[prompt_id]['truth']
Definition at line 240 of file first_prompt.py.
writer
first_prompt.writer = csv.writer(outfile)
Definition at line 202 of file first_prompt.py.