Code Cloning Analysis: scipy.optimize._linesearch Namespace Reference
scipy.optimize._linesearch Namespace Reference
Classes
class LineSearchWarning
Functions
line_search_wolfe1 (f, fprime, xk, pk, gfk=None, old_fval=None, old_old_fval=None, args=(), c1=1e-4, c2=0.9, amax=50, amin=1e-8, xtol=1e-14)
scalar_search_wolfe1 (phi, derphi, phi0=None, old_phi0=None, derphi0=None, c1=1e-4, c2=0.9, amax=50, amin=1e-8, xtol=1e-14)
line_search_wolfe2 (f, myfprime, xk, pk, gfk=None, old_fval=None, old_old_fval=None, args=(), c1=1e-4, c2=0.9, amax=None, extra_condition=None, maxiter=10)
scalar_search_wolfe2 (phi, derphi, phi0=None, old_phi0=None, derphi0=None, c1=1e-4, c2=0.9, amax=None, extra_condition=None, maxiter=10)
_cubicmin (a, fa, fpa, b, fb, c, fc)
_quadmin (a, fa, fpa, b, fb)
_zoom (a_lo, a_hi, phi_lo, phi_hi, derphi_lo, phi, derphi, phi0, derphi0, c1, c2, extra_condition)
line_search_armijo (f, xk, pk, gfk, old_fval, args=(), c1=1e-4, alpha0=1)
line_search_BFGS (f, xk, pk, gfk, old_fval, args=(), c1=1e-4, alpha0=1)
scalar_search_armijo (phi, phi0, derphi0, c1=1e-4, alpha0=1, amin=0)
_nonmonotone_line_search_cruz (f, x_k, d, prev_fs, eta, gamma=1e-4, tau_min=0.1, tau_max=0.5)
_nonmonotone_line_search_cheng (f, x_k, d, f_k, C, Q, eta, gamma=1e-4, tau_min=0.1, tau_max=0.5, nu=0.85)
Variables
list __all__
line_search = line_search_wolfe1
Detailed Description
Functions
---------
.. autosummary::
   :toctree: generated/
    line_search_armijo
    line_search_wolfe1
    line_search_wolfe2
    scalar_search_wolfe1
    scalar_search_wolfe2
Function Documentation
_cubicmin()
scipy.optimize._linesearch._cubicmin (a, fa, fpa, b, fb, c, fc) protected
Finds the minimizer for a cubic polynomial that goes through the
points (a,fa), (b,fb), and (c,fc) with derivative at a of fpa.
If no minimizer can be found, return None.
Definition at line 471 of file _linesearch.py.
Referenced by _zoom().
_nonmonotone_line_search_cheng()
scipy.optimize._linesearch._nonmonotone_line_search_cheng (f, x_k, d, f_k, C, Q, eta, gamma = 1e-4, tau_min = 0.1, tau_max = 0.5, nu = 0.85) protected
Nonmonotone line search from [1]
Parameters
----------
f : callable
    Function returning a tuple ``(f, F)`` where ``f`` is the value
    of a merit function and ``F`` the residual.
x_k : ndarray
    Initial position.
d : ndarray
    Search direction.
f_k : float
    Initial merit function value.
C, Q : float
    Control parameters. On the first iteration, give values
    Q=1.0, C=f_k
eta : float
    Allowed merit function increase, see [1]_
nu, gamma, tau_min, tau_max : float, optional
    Search parameters, see [1]_
Returns
-------
alpha : float
    Step length
xp : ndarray
    Next position
fp : float
    Merit function value at next position
Fp : ndarray
    Residual at next position
C : float
    New value for the control parameter C
Q : float
    New value for the control parameter Q
References
----------
.. [1] W. Cheng & D.-H. Li, ''A derivative-free nonmonotone line
       search and its application to the spectral residual
       method'', IMA J. Numer. Anal. 29, 814 (2009).
Definition at line 812 of file _linesearch.py.
_nonmonotone_line_search_cruz()
scipy.optimize._linesearch._nonmonotone_line_search_cruz (f, x_k, d, prev_fs, eta, gamma = 1e-4, tau_min = 0.1, tau_max = 0.5) protected
Nonmonotone backtracking line search as described in [1]_
Parameters
----------
f : callable
    Function returning a tuple ``(f, F)`` where ``f`` is the value
    of a merit function and ``F`` the residual.
x_k : ndarray
    Initial position.
d : ndarray
    Search direction.
prev_fs : float
    List of previous merit function values. Should have ``len(prev_fs) <= M``
    where ``M`` is the nonmonotonicity window parameter.
eta : float
    Allowed merit function increase, see [1]_
gamma, tau_min, tau_max : float, optional
    Search parameters, see [1]_
Returns
-------
alpha : float
    Step length
xp : ndarray
    Next position
fp : float
    Merit function value at next position
Fp : ndarray
    Residual at next position
References
----------
[1] "Spectral residual method without gradient information for solving
    large-scale nonlinear systems of equations." W. La Cruz,
    J.M. Martinez, M. Raydan. Math. Comp. **75**, 1429 (2006).
Definition at line 740 of file _linesearch.py.
_quadmin()
scipy.optimize._linesearch._quadmin (a, fa, fpa, b, fb) protected
Finds the minimizer for a quadratic polynomial that goes through
the points (a,fa), (b,fb) with derivative at a of fpa.
Definition at line 505 of file _linesearch.py.
Referenced by _zoom().
_zoom()
scipy.optimize._linesearch._zoom (a_lo, a_hi, phi_lo, phi_hi, derphi_lo, phi, derphi, phi0, derphi0, c1, c2, extra_condition) protected
Zoom stage of approximate linesearch satisfying strong Wolfe conditions.
Part of the optimization algorithm in `scalar_search_wolfe2`.
Notes
-----
Implements Algorithm 3.6 (zoom) in Wright and Nocedal,
'Numerical Optimization', 1999, pp. 61.
Definition at line 526 of file _linesearch.py.
References _cubicmin(), and _quadmin().
Referenced by scalar_search_wolfe2().
line_search_armijo()
scipy.optimize._linesearch.line_search_armijo (f, xk, pk, gfk, old_fval, args = (), c1 = 1e-4, alpha0 = 1)
Minimize over alpha, the function ``f(xk+alpha pk)``.
Parameters
----------
f : callable
    Function to be minimized.
xk : array_like
    Current point.
pk : array_like
    Search direction.
gfk : array_like
    Gradient of `f` at point `xk`.
old_fval : float
    Value of `f` at point `xk`.
args : tuple, optional
    Optional arguments.
c1 : float, optional
    Value to control stopping criterion.
alpha0 : scalar, optional
    Value of `alpha` at start of the optimization.
Returns
-------
alpha
f_count
f_val_at_alpha
Notes
-----
Uses the interpolation algorithm (Armijo backtracking) as suggested by
Wright and Nocedal in 'Numerical Optimization', 1999, pp. 56-57
Definition at line 617 of file _linesearch.py.
References scalar_search_armijo().
Referenced by line_search_BFGS().
line_search_BFGS()
scipy.optimize._linesearch.line_search_BFGS (f, xk, pk, gfk, old_fval, args = (), c1 = 1e-4, alpha0 = 1)
Compatibility wrapper for `line_search_armijo`
Definition at line 669 of file _linesearch.py.
References line_search_armijo().
line_search_wolfe1()
scipy.optimize._linesearch.line_search_wolfe1 (f, fprime, xk, pk, gfk = None, old_fval = None, old_old_fval = None, args = (), c1 = 1e-4, c2 = 0.9, amax = 50, amin = 1e-8, xtol = 1e-14)
As `scalar_search_wolfe1` but do a line search to direction `pk`
Parameters
----------
f : callable
    Function `f(x)`
fprime : callable
    Gradient of `f`
xk : array_like
    Current point
pk : array_like
    Search direction
gfk : array_like, optional
    Gradient of `f` at point `xk`
old_fval : float, optional
    Value of `f` at point `xk`
old_old_fval : float, optional
    Value of `f` at point preceding `xk`
The rest of the parameters are the same as for `scalar_search_wolfe1`.
Returns
-------
stp, f_count, g_count, fval, old_fval
    As in `line_search_wolfe1`
gval : array
    Gradient of `f` at the final point
Definition at line 31 of file _linesearch.py.
line_search_wolfe2()
scipy.optimize._linesearch.line_search_wolfe2 (f, myfprime, xk, pk, gfk = None, old_fval = None, old_old_fval = None, args = (), c1 = 1e-4, c2 = 0.9, amax = None, extra_condition = None, maxiter = 10)
Find alpha that satisfies strong Wolfe conditions.
Parameters
----------
f : callable f(x,*args)
    Objective function.
myfprime : callable f'(x,*args)
    Objective function gradient.
xk : ndarray
    Starting point.
pk : ndarray
    Search direction. The search direction must be a descent direction
    for the algorithm to converge.
gfk : ndarray, optional
    Gradient value for x=xk (xk being the current parameter
    estimate). Will be recomputed if omitted.
old_fval : float, optional
    Function value for x=xk. Will be recomputed if omitted.
old_old_fval : float, optional
    Function value for the point preceding x=xk.
args : tuple, optional
    Additional arguments passed to objective function.
c1 : float, optional
    Parameter for Armijo condition rule.
c2 : float, optional
    Parameter for curvature condition rule.
amax : float, optional
    Maximum step size
extra_condition : callable, optional
    A callable of the form ``extra_condition(alpha, x, f, g)``
    returning a boolean. Arguments are the proposed step ``alpha``
    and the corresponding ``x``, ``f`` and ``g`` values. The line search
    accepts the value of ``alpha`` only if this
    callable returns ``True``. If the callable returns ``False``
    for the step length, the algorithm will continue with
    new iterates. The callable is only called for iterates
    satisfying the strong Wolfe conditions.
maxiter : int, optional
    Maximum number of iterations to perform.
Returns
-------
alpha : float or None
    Alpha for which ``x_new = x0 + alpha * pk``,
    or None if the line search algorithm did not converge.
fc : int
    Number of function evaluations made.
gc : int
    Number of gradient evaluations made.
new_fval : float or None
    New function value ``f(x_new)=f(x0+alpha*pk)``,
    or None if the line search algorithm did not converge.
old_fval : float
    Old function value ``f(x0)``.
new_slope : float or None
    The local slope along the search direction at the
    new value ``<myfprime(x_new), pk>``,
    or None if the line search algorithm did not converge.
Notes
-----
Uses the line search algorithm to enforce strong Wolfe
conditions. See Wright and Nocedal, 'Numerical Optimization',
1999, pp. 59-61.
The search direction `pk` must be a descent direction (e.g.
``-myfprime(xk)``) to find a step length that satisfies the strong Wolfe
conditions. If the search direction is not a descent direction (e.g.
``myfprime(xk)``), then `alpha`, `new_fval`, and `new_slope` will be None.
Examples
--------
>>> import numpy as np
>>> from scipy.optimize import line_search
A objective function and its gradient are defined.
>>> def obj_func(x):
...     return (x[0])**2+(x[1])**2
>>> def obj_grad(x):
...     return [2*x[0], 2*x[1]]
We can find alpha that satisfies strong Wolfe conditions.
>>> start_point = np.array([1.8, 1.7])
>>> search_gradient = np.array([-1.0, -1.0])
>>> line_search(obj_func, obj_grad, start_point, search_gradient)
(1.0, 2, 1, 1.1300000000000001, 6.13, [1.6, 1.4])
Definition at line 183 of file _linesearch.py.
References scalar_search_wolfe2().
scalar_search_armijo()
scipy.optimize._linesearch.scalar_search_armijo (phi, phi0, derphi0, c1 = 1e-4, alpha0 = 1, amin = 0)
Minimize over alpha, the function ``phi(alpha)``.
Uses the interpolation algorithm (Armijo backtracking) as suggested by
Wright and Nocedal in 'Numerical Optimization', 1999, pp. 56-57
alpha > 0 is assumed to be a descent direction.
Returns
-------
alpha
phi1
Definition at line 678 of file _linesearch.py.
Referenced by line_search_armijo().
scalar_search_wolfe1()
scipy.optimize._linesearch.scalar_search_wolfe1 (phi, derphi, phi0 = None, old_phi0 = None, derphi0 = None, c1 = 1e-4, c2 = 0.9, amax = 50, amin = 1e-8, xtol = 1e-14)
Scalar function search for alpha that satisfies strong Wolfe conditions
alpha > 0 is assumed to be a descent direction.
Parameters
----------
phi : callable phi(alpha)
    Function at point `alpha`
derphi : callable phi'(alpha)
    Objective function derivative. Returns a scalar.
phi0 : float, optional
    Value of phi at 0
old_phi0 : float, optional
    Value of phi at previous point
derphi0 : float, optional
    Value derphi at 0
c1 : float, optional
    Parameter for Armijo condition rule.
c2 : float, optional
    Parameter for curvature condition rule.
amax, amin : float, optional
    Maximum and minimum step size
xtol : float, optional
    Relative tolerance for an acceptable step.
Returns
-------
alpha : float
    Step size, or None if no suitable step was found
phi : float
    Value of `phi` at the new point `alpha`
phi0 : float
    Value of `phi` at `alpha=0`
Notes
-----
Uses routine DCSRCH from MINPACK.
Definition at line 91 of file _linesearch.py.
scalar_search_wolfe2()
scipy.optimize._linesearch.scalar_search_wolfe2 (phi, derphi, phi0 = None, old_phi0 = None, derphi0 = None, c1 = 1e-4, c2 = 0.9, amax = None, extra_condition = None, maxiter = 10)
Find alpha that satisfies strong Wolfe conditions.
alpha > 0 is assumed to be a descent direction.
Parameters
----------
phi : callable phi(alpha)
    Objective scalar function.
derphi : callable phi'(alpha)
    Objective function derivative. Returns a scalar.
phi0 : float, optional
    Value of phi at 0.
old_phi0 : float, optional
    Value of phi at previous point.
derphi0 : float, optional
    Value of derphi at 0
c1 : float, optional
    Parameter for Armijo condition rule.
c2 : float, optional
    Parameter for curvature condition rule.
amax : float, optional
    Maximum step size.
extra_condition : callable, optional
    A callable of the form ``extra_condition(alpha, phi_value)``
    returning a boolean. The line search accepts the value
    of ``alpha`` only if this callable returns ``True``.
    If the callable returns ``False`` for the step length,
    the algorithm will continue with new iterates.
    The callable is only called for iterates satisfying
    the strong Wolfe conditions.
maxiter : int, optional
    Maximum number of iterations to perform.
Returns
-------
alpha_star : float or None
    Best alpha, or None if the line search algorithm did not converge.
phi_star : float
    phi at alpha_star.
phi0 : float
    phi at 0.
derphi_star : float or None
    derphi at alpha_star, or None if the line search algorithm
    did not converge.
Notes
-----
Uses the line search algorithm to enforce strong Wolfe
conditions. See Wright and Nocedal, 'Numerical Optimization',
1999, pp. 59-61.
Definition at line 325 of file _linesearch.py.
References _zoom().
Referenced by line_search_wolfe2().
Variable Documentation
__all__
list scipy.optimize._linesearch.__all__ private
Initial value:
=  ['LineSearchWarning', 'line_search_wolfe1', 'line_search_wolfe2',
           'scalar_search_wolfe1', 'scalar_search_wolfe2',
           'line_search_armijo']
Definition at line 19 of file _linesearch.py.
line_search
scipy.optimize._linesearch.line_search = line_search_wolfe1
Definition at line 174 of file _linesearch.py.