Code Cloning Analysis: pandas.io.formats.printing Namespace Reference
pandas.io.formats.printing Namespace Reference
Classes
class _EastAsianTextAdjustment
class _TextAdjustment
class PrettyDict
Functions
str adjoin (int space, *list[str] lists, **kwargs)
list[str] _adj_justify (Iterable[str] texts, int max_len, str mode="right")
str _pprint_seq (Sequence seq, int _nest_lvl=0, int|None max_seq_items=None, **kwds)
str _pprint_dict (Mapping seq, int _nest_lvl=0, int|None max_seq_items=None, **kwds)
str pprint_thing (Any thing, int _nest_lvl=0, EscapeChars|None escape_chars=None, bool default_escapes=False, bool quote_strings=False, int|None max_seq_items=None)
bytes pprint_thing_encoded (object, str encoding="utf-8", str errors="replace")
None enable_data_resource_formatter (bool enable)
str default_pprint (Any thing, int|None max_seq_items=None)
str format_object_summary (obj, Callable formatter, bool is_justify=True, str|None name=None, bool indent_for_name=True, bool line_break_each_value=False)
tuple[list[tuple[str,...]], list[tuple[str,...]]] _justify (list[Sequence[str]] head, list[Sequence[str]] tail)
_TextAdjustment get_adjustment ()
Variables
EscapeChars = Union[Mapping[str, str], Iterable[str]]
_KT = TypeVar("_KT")
_VT = TypeVar("_VT")
Detailed Description
Printing tools.
Function Documentation
_adj_justify()
list[str] pandas.io.formats.printing._adj_justify (Iterable[str] texts, int max_len, str mode = "right") protected
Perform ljust, center, rjust against string or list-like
Definition at line 63 of file printing.py.
_justify()
tuple[list[tuple[str, ...]], list[tuple[str, ...]]] pandas.io.formats.printing._justify (list[Sequence[str]] head, list[Sequence[str]] tail) protected
Justify items in head and tail, so they are right-aligned when stacked.
Parameters
----------
head : list-like of list-likes of strings
tail : list-like of list-likes of strings
Returns
-------
tuple of list of tuples of strings
    Same as head and tail, but items are right aligned when stacked
    vertically.
Examples
--------
>>> _justify([['a', 'b']], [['abc', 'abcd']])
([('  a', '   b')], [('abc', 'abcd')])
Definition at line 458 of file printing.py.
Referenced by format_object_summary().
_pprint_dict()
str pandas.io.formats.printing._pprint_dict (Mapping seq, int _nest_lvl = 0, int | None max_seq_items = None, ** kwds) protected
internal. pprinter for iterables. you should probably use pprint_thing()
rather than calling this directly.
Definition at line 134 of file printing.py.
References pprint_thing().
Referenced by pprint_thing().
_pprint_seq()
str pandas.io.formats.printing._pprint_seq (Sequence seq, int _nest_lvl = 0, int | None max_seq_items = None, ** kwds) protected
internal. pprinter for iterables. you should probably use pprint_thing()
rather than calling this directly.
bounds length of printed sequence, depending on options
Definition at line 99 of file printing.py.
References pprint_thing().
Referenced by format_object_summary(), and pprint_thing().
adjoin()
str pandas.io.formats.printing.adjoin (int space, *list[str] lists, ** kwargs)
Glues together two sets of strings using the amount of space requested.
The idea is to prettify.
----------
space : int
    number of spaces for padding
lists : str
    list of str which being joined
strlen : callable
    function used to calculate the length of each str. Needed for unicode
    handling.
justfunc : callable
    function used to justify str. Needed for unicode handling.
Definition at line 31 of file printing.py.
default_pprint()
str pandas.io.formats.printing.default_pprint (Any thing, int | None max_seq_items = None)
Definition at line 278 of file printing.py.
enable_data_resource_formatter()
None pandas.io.formats.printing.enable_data_resource_formatter (bool enable)
Definition at line 245 of file printing.py.
format_object_summary()
str pandas.io.formats.printing.format_object_summary (obj, Callable formatter, bool is_justify = True, str | None name = None, bool indent_for_name = True, bool line_break_each_value = False)
Return the formatted obj as a unicode string
Parameters
----------
obj : object
    must be iterable and support __getitem__
formatter : callable
    string formatter for an element
is_justify : bool
    should justify the display
name : name, optional
    defaults to the class name of the obj
indent_for_name : bool, default True
    Whether subsequent lines should be indented to
    align with the name.
line_break_each_value : bool, default False
    If True, inserts a line break for each value of ``obj``.
    If False, only break lines when the a line of values gets wider
    than the display width.
Returns
-------
summary string
Definition at line 287 of file printing.py.
References _justify(), and _pprint_seq().
get_adjustment()
_TextAdjustment pandas.io.formats.printing.get_adjustment ()
Definition at line 567 of file printing.py.
pprint_thing()
str pandas.io.formats.printing.pprint_thing (Any thing, int _nest_lvl = 0, EscapeChars | None escape_chars = None, bool default_escapes = False, bool quote_strings = False, int | None max_seq_items = None)
This function is the sanctioned way of converting objects
to a string representation and properly handles nested sequences.
Parameters
----------
thing : anything to be formatted
_nest_lvl : internal use only. pprint_thing() is mutually-recursive
    with pprint_sequence, this argument is used to keep track of the
    current nesting level, and limit it.
escape_chars : list or dict, optional
    Characters to escape. If a dict is passed the values are the
    replacements
default_escapes : bool, default False
    Whether the input escape characters replaces or adds to the defaults
max_seq_items : int or None, default None
    Pass through to other pretty printers to limit sequence printing
Returns
-------
str
Definition at line 165 of file printing.py.
References _pprint_dict(), _pprint_seq(), and pprint_thing().
Referenced by _pprint_dict(), _pprint_seq(), and pprint_thing().
pprint_thing_encoded()
bytes pandas.io.formats.printing.pprint_thing_encoded (object, str encoding = "utf-8", str errors = "replace")
Definition at line 238 of file printing.py.
Variable Documentation
_KT
pandas.io.formats.printing._KT = TypeVar("_KT") protected
Definition at line 27 of file printing.py.
_VT
pandas.io.formats.printing._VT = TypeVar("_VT") protected
Definition at line 28 of file printing.py.
EscapeChars
pandas.io.formats.printing.EscapeChars = Union[Mapping[str, str], Iterable[str]]
Definition at line 26 of file printing.py.