Code Cloning Analysis: pandas.core.accessor.PandasDelegate Class Reference
pandas.core.accessor.PandasDelegate Class Reference
Protected Member Functions
_delegate_property_get (self, str name, *args, **kwargs)
_delegate_property_set (self, str name, value, *args, **kwargs)
_delegate_method (self, str name, *args, **kwargs)
None _add_delegate_accessors (cls, delegate, list[str] accessors, str typ, bool overwrite=False, Callable[[str], str] accessor_mapping=lambda x:x, bool raise_on_missing=True)
Detailed Description
Abstract base class for delegating methods/properties.
Definition at line 49 of file accessor.py.
Member Function Documentation
_add_delegate_accessors()
None pandas.core.accessor.PandasDelegate._add_delegate_accessors (cls, delegate, list[str] accessors, str typ, bool overwrite = False, Callable[[str], str] accessor_mapping = lambda x: x, bool raise_on_missing = True) protected
Add accessors to cls from the delegate class.
Parameters
----------
cls
    Class to add the methods/properties to.
delegate
    Class to get methods/properties and doc-strings.
accessors : list of str
    List of accessors to add.
typ : {'property', 'method'}
overwrite : bool, default False
    Overwrite the method/property in the target class if it exists.
accessor_mapping: Callable, default lambda x: x
    Callable to map the delegate's function to the cls' function.
raise_on_missing: bool, default True
    Raise if an accessor does not exist on delegate.
    False skips the missing accessor.
Definition at line 64 of file accessor.py.
References _delegate_method(), _delegate_property_get(), and _delegate_property_set().
_delegate_method()
pandas.core.accessor.PandasDelegate._delegate_method (self, str name, * args, ** kwargs) protected
Definition at line 60 of file accessor.py.
Referenced by _add_delegate_accessors().
_delegate_property_get()
pandas.core.accessor.PandasDelegate._delegate_property_get (self, str name, * args, ** kwargs) protected
Definition at line 54 of file accessor.py.
Referenced by _add_delegate_accessors().
_delegate_property_set()
pandas.core.accessor.PandasDelegate._delegate_property_set (self, str name, value, * args, ** kwargs) protected
Definition at line 57 of file accessor.py.
Referenced by _add_delegate_accessors().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/core/accessor.py