Code Cloning Analysis: packaging.tags.Tag Class Reference
packaging.tags.Tag Class Reference
Public Member Functions
None __init__ (self, str interpreter, str abi, str platform)
str interpreter (self)
str abi (self)
str platform (self)
bool __eq__ (self, object other)
int __hash__ (self)
str __str__ (self)
str __repr__ (self)
Protected Attributes
str _interpreter = interpreter.lower()
str _abi = abi.lower()
str _platform = platform.lower()
_hash = hash((self._interpreter, self._abi, self._platform))
Static Private Attributes
list __slots__ = ["_abi", "_hash", "_interpreter", "_platform"]
Detailed Description
A representation of the tag triple for a wheel.
Instances are considered immutable and thus are hashable. Equality checking
is also supported.
Definition at line 42 of file tags.py.
Constructor & Destructor Documentation
__init__()
None packaging.tags.Tag.__init__ (self, str interpreter, str abi, str platform)
Definition at line 52 of file tags.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__eq__()
bool packaging.tags.Tag.__eq__ (self, object other)
Definition at line 75 of file tags.py.
Referenced by pandas.core.dtypes.base.ExtensionDtype.__eq__(), pandas.io.pytables.IndexCol.__eq__(), pip._vendor.msgpack.ext.Timestamp.__ne__(), pip._vendor.distlib.version.Matcher.match(), and pandas.core.dtypes.dtypes.PeriodDtype.na_value().
__hash__()
int packaging.tags.Tag.__hash__ (self)
Definition at line 86 of file tags.py.
Referenced by pip._vendor.rich.style.Style.pick_first().
__repr__()
str packaging.tags.Tag.__repr__ (self)
Definition at line 92 of file tags.py.
__str__()
str packaging.tags.Tag.__str__ (self)
Definition at line 89 of file tags.py.
abi()
str packaging.tags.Tag.abi (self)
Definition at line 68 of file tags.py.
interpreter()
str packaging.tags.Tag.interpreter (self)
Definition at line 64 of file tags.py.
platform()
str packaging.tags.Tag.platform (self)
Definition at line 72 of file tags.py.
Member Data Documentation
__slots__
list packaging.tags.Tag.__slots__ = ["_abi", "_hash", "_interpreter", "_platform"] static private
Definition at line 50 of file tags.py.
_abi
str packaging.tags.Tag._abi = abi.lower() protected
Definition at line 54 of file tags.py.
_hash
packaging.tags.Tag._hash = hash((self._interpreter, self._abi, self._platform)) protected
Definition at line 61 of file tags.py.
Referenced by pip._vendor.rich.style.Style.clear_meta_and_links(), pip._vendor.rich.style.Style.copy(), and pip._vendor.rich.style.Style.pick_first().
_interpreter
str packaging.tags.Tag._interpreter = interpreter.lower() protected
Definition at line 53 of file tags.py.
_platform
str packaging.tags.Tag._platform = platform.lower() protected
Definition at line 55 of file tags.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/packaging/tags.py