Code Cloning Analysis: numpy._globals._NoValueType Class Reference
numpy._globals._NoValueType Class Reference
Public Member Functions
__new__ (cls)
__repr__ (self)
Static Private Attributes
__instance = None
Detailed Description
Special keyword value.
The instance of this class may be used as the default value assigned to a
keyword if no other obvious default (e.g., `None`) is suitable,
Common reasons for using this keyword are:
- A new keyword is added to a function, and that function forwards its
  inputs to another function or method which can be defined outside of
  NumPy. For example, ``np.std(x)`` calls ``x.std``, so when a ``keepdims``
  keyword was added that could only be forwarded if the user explicitly
  specified ``keepdims``; downstream array libraries may not have added
  the same keyword, so adding ``x.std(..., keepdims=keepdims)``
  unconditionally could have broken previously working code.
- A keyword is being deprecated, and a deprecation warning must only be
  emitted when the keyword is used.
Definition at line 32 of file _globals.py.
Member Function Documentation
__new__()
numpy._globals._NoValueType.__new__ (cls)
Definition at line 52 of file _globals.py.
Referenced by matplotlib.path.Path._fast_from_codes_and_verts(), pandas.core.generic.NDFrame._from_mgr(), pandas.core.arrays.string_.StringArray._from_sequence(), scipy.interpolate._fitpack2._BivariateSplineBase._from_tck(), scipy.interpolate._fitpack2.UnivariateSpline._from_tck(), matplotlib.colors.Colormap._get_rgba_and_mask(), pip._vendor.rich.style.Style.clear_meta_and_links(), matplotlib.colors.MultivarColormap.copy(), pip._vendor.rich.style.Style.copy(), pip._vendor.rich.style.Style.from_color(), pip._vendor.rich.json.JSON.from_data(), pip._vendor.rich.style.Style.from_meta(), matplotlib.colors.BivarColormap.lut(), pip._vendor.rich.style.Style.test(), pip._vendor.rich.style.Style.update_link(), and pip._vendor.rich.style.Style.without_color().
__repr__()
numpy._globals._NoValueType.__repr__ (self)
Definition at line 58 of file _globals.py.
Member Data Documentation
__instance
numpy._globals._NoValueType.__instance = None static private
Definition at line 51 of file _globals.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/_globals.py