Code Cloning Analysis: matplotlib.backends.backend_svg Namespace Reference
matplotlib.backends.backend_svg Namespace Reference
Classes
class _BackendSVG
class FigureCanvasSVG
class RendererSVG
class XMLWriter
Functions
_escape_cdata (s)
_escape_comment (s)
_escape_attrib (s)
_quote_escape_attrib (s)
_short_float_fmt (x)
_generate_transform (transform_list)
_generate_css (attrib)
_check_is_str (info, key)
_check_is_iterable_of_str (infos, key)
Variables
_log = logging.getLogger(__name__)
_escape_xml_comment = re.compile(r'-(?=-)')
dict _capstyle_d = {'projecting': 'square', 'butt': 'butt', 'round': 'round'}
FigureManagerSVG = FigureManagerBase
str svgProlog
Function Documentation
_check_is_iterable_of_str()
matplotlib.backends.backend_svg._check_is_iterable_of_str (infos, key) protected
Definition at line 278 of file backend_svg.py.
_check_is_str()
matplotlib.backends.backend_svg._check_is_str (info, key) protected
Definition at line 272 of file backend_svg.py.
_escape_attrib()
matplotlib.backends.backend_svg._escape_attrib (s) protected
Definition at line 84 of file backend_svg.py.
_escape_cdata()
matplotlib.backends.backend_svg._escape_cdata (s) protected
Definition at line 69 of file backend_svg.py.
_escape_comment()
matplotlib.backends.backend_svg._escape_comment (s) protected
Definition at line 79 of file backend_svg.py.
_generate_css()
matplotlib.backends.backend_svg._generate_css (attrib) protected
Definition at line 265 of file backend_svg.py.
_generate_transform()
matplotlib.backends.backend_svg._generate_transform (transform_list) protected
Definition at line 251 of file backend_svg.py.
_quote_escape_attrib()
matplotlib.backends.backend_svg._quote_escape_attrib (s) protected
Definition at line 93 of file backend_svg.py.
_short_float_fmt()
matplotlib.backends.backend_svg._short_float_fmt (x) protected
Create a short string representation of a float, which is %f
formatting with trailing zeros and the decimal point removed.
Definition at line 99 of file backend_svg.py.
Referenced by matplotlib.backends.backend_svg.RendererSVG._draw_text_as_path(), matplotlib.backends.backend_svg.RendererSVG._get_style_dict(), matplotlib.backends.backend_svg.RendererSVG.draw_image(), matplotlib.backends.backend_svg.RendererSVG.draw_markers(), matplotlib.backends.backend_svg.RendererSVG.draw_path_collection(), and matplotlib.backends.backend_svg.XMLWriter.flush().
Variable Documentation
_capstyle_d
dict matplotlib.backends.backend_svg._capstyle_d = {'projecting': 'square', 'butt': 'butt', 'round': 'round'} protected
Definition at line 269 of file backend_svg.py.
_escape_xml_comment
matplotlib.backends.backend_svg._escape_xml_comment = re.compile(r'-(?=-)') protected
Definition at line 76 of file backend_svg.py.
_log
matplotlib.backends.backend_svg._log = logging.getLogger(__name__) protected
Definition at line 28 of file backend_svg.py.
FigureManagerSVG
matplotlib.backends.backend_svg.FigureManagerSVG = FigureManagerBase
Definition at line 1367 of file backend_svg.py.
svgProlog
str matplotlib.backends.backend_svg.svgProlog
Initial value:
=  """\
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
  "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
"""
Definition at line 1370 of file backend_svg.py.