Code Cloning Analysis: pip._vendor.urllib3.response.GzipDecoder Class Reference
pip._vendor.urllib3.response.GzipDecoder Class Reference
Public Member Functions
__init__ (self)
__getattr__ (self, name)
decompress (self, data)
Protected Attributes
_obj = zlib.decompressobj(16 + zlib.MAX_WBITS)
_state = GzipDecoderState.FIRST_MEMBER
Detailed Description
Definition at line 74 of file response.py.
Constructor & Destructor Documentation
__init__()
pip._vendor.urllib3.response.GzipDecoder.__init__ (self)
Definition at line 75 of file response.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
__getattr__()
pip._vendor.urllib3.response.GzipDecoder.__getattr__ (self, name)
Definition at line 79 of file response.py.
decompress()
pip._vendor.urllib3.response.GzipDecoder.decompress (self, data)
Definition at line 82 of file response.py.
Member Data Documentation
_obj
pip._vendor.urllib3.response.GzipDecoder._obj = zlib.decompressobj(16 + zlib.MAX_WBITS) protected
Definition at line 76 of file response.py.
Referenced by scipy._lib._docscrape.NumpyDocString._parse_summary().
_state
pip._vendor.urllib3.response.GzipDecoder._state = GzipDecoderState.FIRST_MEMBER protected
Definition at line 77 of file response.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pip/_vendor/urllib3/response.py