Code Cloning Analysis: pandas.core.sorting Namespace Reference
pandas.core.sorting Namespace Reference
Functions
npt.NDArray[np.intp]|None get_indexer_indexer (Index target, Level|list[Level]|None level, list[bool]|bool ascending, SortKind kind, NaPosition na_position, bool sort_remaining, IndexKeyFunc key)
npt.NDArray[np.int64] get_group_index (labels, Shape shape, bool sort, bool xnull)
tuple[npt.NDArray[np.intp], npt.NDArray[np.int64]] get_compressed_ids (labels, Shape sizes)
bool is_int64_overflow_possible (Shape shape)
list[npt.NDArray[np.intp]] _decons_group_index (npt.NDArray[np.intp] comp_labels, Shape shape)
list[npt.NDArray[np.intp]] decons_obs_group_ids (npt.NDArray[np.intp] comp_ids, npt.NDArray[np.intp] obs_ids, Shape shape, Sequence[npt.NDArray[np.signedinteger]] labels, bool xnull)
npt.NDArray[np.intp] lexsort_indexer (Sequence[ArrayLike|Index|Series] keys, orders=None, str na_position="last", Callable|None key=None, bool codes_given=False)
npt.NDArray[np.intp] nargsort (ArrayLike|Index|Series items, SortKind kind="quicksort", bool ascending=True, str na_position="last", Callable|None key=None, npt.NDArray[np.bool_]|None mask=None)
nargminmax (ExtensionArray values, str method, AxisInt axis=0)
int _nanargminmax (np.ndarray values, npt.NDArray[np.bool_] mask, func)
MultiIndex _ensure_key_mapped_multiindex (MultiIndex index, Callable key, level=None)
ArrayLike|Index|Series ensure_key_mapped (ArrayLike|Index|Series values, Callable|None key, levels=None)
list[tuple] get_flattened_list (npt.NDArray[np.intp] comp_ids, int ngroups, Iterable[Index] levels, Iterable[np.ndarray] labels)
dict[Hashable, npt.NDArray[np.intp]] get_indexer_dict (list[np.ndarray] label_list, list[Index] keys)
npt.NDArray[np.intp] get_group_index_sorter (npt.NDArray[np.intp] group_index, int|None ngroups=None)
tuple[npt.NDArray[np.int64], npt.NDArray[np.int64]] compress_group_index (npt.NDArray[np.int64] group_index, bool sort=True)
tuple[npt.NDArray[np.int64], npt.NDArray[np.intp]] _reorder_by_uniques (npt.NDArray[np.int64] uniques, npt.NDArray[np.intp] labels)
Detailed Description
 miscellaneous sorting / groupby utilities
Function Documentation
_decons_group_index()
list[npt.NDArray[np.intp]] pandas.core.sorting._decons_group_index (npt.NDArray[np.intp] comp_labels, Shape shape) protected
Definition at line 246 of file sorting.py.
_ensure_key_mapped_multiindex()
MultiIndex pandas.core.sorting._ensure_key_mapped_multiindex (MultiIndex index, Callable key, level = None) protected
Returns a new MultiIndex in which key has been applied
to all levels specified in level (or all levels if level
is None). Used for key sorting for MultiIndex.
Parameters
----------
index : MultiIndex
    Index to which to apply the key function on the
    specified levels.
key : Callable
    Function that takes an Index and returns an Index of
    the same shape. This key is applied to each level
    separately. The name of the level can be used to
    distinguish different levels for application.
level : list-like, int or str, default None
    Level or list of levels to apply the key function to.
    If None, key function is applied to all levels. Other
    levels are left unchanged.
Returns
-------
labels : MultiIndex
    Resulting MultiIndex with modified levels.
Definition at line 497 of file sorting.py.
References ensure_key_mapped().
Referenced by ensure_key_mapped().
_nanargminmax()
int pandas.core.sorting._nanargminmax (np.ndarray values, npt.NDArray[np.bool_] mask, func) protected
See nanargminmax.__doc__.
Definition at line 486 of file sorting.py.
Referenced by nargminmax().
_reorder_by_uniques()
tuple[npt.NDArray[np.int64], npt.NDArray[np.intp]] pandas.core.sorting._reorder_by_uniques (npt.NDArray[np.int64] uniques, npt.NDArray[np.intp] labels) protected
Parameters
----------
uniques : np.ndarray[np.int64]
labels : np.ndarray[np.intp]
Returns
-------
np.ndarray[np.int64]
np.ndarray[np.intp]
Definition at line 718 of file sorting.py.
Referenced by compress_group_index().
compress_group_index()
tuple[npt.NDArray[np.int64], npt.NDArray[np.int64]] pandas.core.sorting.compress_group_index (npt.NDArray[np.int64] group_index, bool sort = True)
Group_index is offsets into cartesian product of all possible labels. This
space can be huge, so this function compresses it, by computing offsets
(comp_ids) into the list of unique labels (obs_group_ids).
Definition at line 687 of file sorting.py.
References _reorder_by_uniques().
Referenced by get_compressed_ids(), and get_group_index().
decons_obs_group_ids()
list[npt.NDArray[np.intp]] pandas.core.sorting.decons_obs_group_ids (npt.NDArray[np.intp] comp_ids, npt.NDArray[np.intp] obs_ids, Shape shape, Sequence[npt.NDArray[np.signedinteger]] labels, bool xnull)
Reconstruct labels from observed group ids.
Parameters
----------
comp_ids : np.ndarray[np.intp]
obs_ids: np.ndarray[np.intp]
shape : tuple[int]
labels : Sequence[np.ndarray[np.signedinteger]]
xnull : bool
    If nulls are excluded; i.e. -1 labels are passed through.
Definition at line 268 of file sorting.py.
ensure_key_mapped()
ArrayLike | Index | Series pandas.core.sorting.ensure_key_mapped (ArrayLike | Index | Series values, Callable | None key, levels = None)
Applies a callable key function to the values function and checks
that the resulting value has the same shape. Can be called on Index
subclasses, Series, DataFrames, or ndarrays.
Parameters
----------
values : Series, DataFrame, Index subclass, or ndarray
key : Optional[Callable], key to be called on the values array
levels : Optional[List], if values is a MultiIndex, list of levels to
apply the key to.
Definition at line 546 of file sorting.py.
References _ensure_key_mapped_multiindex().
Referenced by _ensure_key_mapped_multiindex(), get_indexer_indexer(), lexsort_indexer(), and nargsort().
get_compressed_ids()
tuple[npt.NDArray[np.intp], npt.NDArray[np.int64]] pandas.core.sorting.get_compressed_ids (labels, Shape sizes)
Group_index is offsets into cartesian product of all possible labels. This
space can be huge, so this function compresses it, by computing offsets
(comp_ids) into the list of unique labels (obs_group_ids).
Parameters
----------
labels : list of label arrays
sizes : tuple[int] of size of the levels
Returns
-------
np.ndarray[np.intp]
    comp_ids
np.ndarray[np.int64]
    obs_group_ids
Definition at line 214 of file sorting.py.
References compress_group_index(), and get_group_index().
get_flattened_list()
list[tuple] pandas.core.sorting.get_flattened_list (npt.NDArray[np.intp] comp_ids, int ngroups, Iterable[Index] levels, Iterable[np.ndarray] labels)
Map compressed group id -> key tuple.
Definition at line 594 of file sorting.py.
get_group_index()
npt.NDArray[np.int64] pandas.core.sorting.get_group_index (labels, Shape shape, bool sort, bool xnull)
For the particular label_list, gets the offsets into the hypothetical list
representing the totally ordered cartesian product of all possible label
combinations, *as long as* this space fits within int64 bounds;
otherwise, though group indices identify unique combinations of
labels, they cannot be deconstructed.
- If `sort`, rank of returned ids preserve lexical ranks of labels.
  i.e. returned id's can be used to do lexical sort on labels;
- If `xnull` nulls (-1 labels) are passed through.
Parameters
----------
labels : sequence of arrays
    Integers identifying levels at each location
shape : tuple[int, ...]
    Number of unique levels at each location
sort : bool
    If the ranks of returned ids should match lexical ranks of labels
xnull : bool
    If true nulls are excluded. i.e. -1 values in the labels are
    passed through.
Returns
-------
An array of type int64 where two elements are equal if their corresponding
labels are equal at all location.
Notes
-----
The length of `labels` and `shape` must be identical.
Definition at line 122 of file sorting.py.
References compress_group_index().
Referenced by get_compressed_ids(), and get_indexer_dict().
get_group_index_sorter()
npt.NDArray[np.intp] pandas.core.sorting.get_group_index_sorter (npt.NDArray[np.intp] group_index, int | None ngroups = None)
algos.groupsort_indexer implements `counting sort` and it is at least
O(ngroups), where
    ngroups = prod(shape)
    shape = map(len, keys)
that is, linear in the number of combinations (cartesian product) of unique
values of groupby keys. This can be huge when doing multi-key groupby.
np.argsort(kind='mergesort') is O(count x log(count)) where count is the
length of the data-frame;
Both algorithms are `stable` sort and that is necessary for correctness of
groupby operations. e.g. consider:
    df.groupby(key)[col].transform('first')
Parameters
----------
group_index : np.ndarray[np.intp]
    signed integer dtype
ngroups : int or None, default None
Returns
-------
np.ndarray[np.intp]
Definition at line 644 of file sorting.py.
Referenced by get_indexer_dict().
get_indexer_dict()
dict[Hashable, npt.NDArray[np.intp]] pandas.core.sorting.get_indexer_dict (list[np.ndarray] label_list, list[Index] keys)
Returns
-------
dict:
    Labels mapped to indexers.
Definition at line 611 of file sorting.py.
References get_group_index(), and get_group_index_sorter().
get_indexer_indexer()
npt.NDArray[np.intp] | None pandas.core.sorting.get_indexer_indexer (Index target, Level | list[Level] | None level, list[bool] | bool ascending, SortKind kind, NaPosition na_position, bool sort_remaining, IndexKeyFunc key)
Helper method that return the indexer according to input parameters for
the sort_index method of DataFrame and Series.
Parameters
----------
target : Index
level : int or level name or list of ints or list of level names
ascending : bool or list of bools, default True
kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}
na_position : {'first', 'last'}
sort_remaining : bool
key : callable, optional
Returns
-------
Optional[ndarray[intp]]
    The indexer for the new index.
Definition at line 59 of file sorting.py.
References ensure_key_mapped(), lexsort_indexer(), and nargsort().
is_int64_overflow_possible()
bool pandas.core.sorting.is_int64_overflow_possible (Shape shape)
Definition at line 238 of file sorting.py.
lexsort_indexer()
npt.NDArray[np.intp] pandas.core.sorting.lexsort_indexer (Sequence[ArrayLike | Index | Series] keys, orders = None, str na_position = "last", Callable | None key = None, bool codes_given = False)
Performs lexical sorting on a set of keys
Parameters
----------
keys : Sequence[ArrayLike | Index | Series]
    Sequence of arrays to be sorted by the indexer
    Sequence[Series] is only if key is not None.
orders : bool or list of booleans, optional
    Determines the sorting order for each element in keys. If a list,
    it must be the same length as keys. This determines whether the
    corresponding element in keys should be sorted in ascending
    (True) or descending (False) order. if bool, applied to all
    elements as above. if None, defaults to True.
na_position : {'first', 'last'}, default 'last'
    Determines placement of NA elements in the sorted list ("last" or "first")
key : Callable, optional
    Callable key function applied to every element in keys before sorting
codes_given: bool, False
    Avoid categorical materialization if codes are already provided.
Returns
-------
np.ndarray[np.intp]
Definition at line 301 of file sorting.py.
References ensure_key_mapped().
Referenced by get_indexer_indexer().
nargminmax()
pandas.core.sorting.nargminmax (ExtensionArray values, str method, AxisInt axis = 0)
Implementation of np.argmin/argmax but for ExtensionArray and which
handles missing values.
Parameters
----------
values : ExtensionArray
method : {"argmax", "argmin"}
axis : int, default 0
Returns
-------
int
Definition at line 453 of file sorting.py.
References _nanargminmax().
nargsort()
npt.NDArray[np.intp] pandas.core.sorting.nargsort (ArrayLike | Index | Series items, SortKind kind = "quicksort", bool ascending = True, str na_position = "last", Callable | None key = None, npt.NDArray[np.bool_] | None mask = None)
Intended to be a drop-in replacement for np.argsort which handles NaNs.
Adds ascending, na_position, and key parameters.
(GH #6399, #5231, #27237)
Parameters
----------
items : np.ndarray, ExtensionArray, Index, or Series
kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, default 'quicksort'
ascending : bool, default True
na_position : {'first', 'last'}, default 'last'
key : Optional[Callable], default None
mask : Optional[np.ndarray[bool]], default None
    Passed when called by ExtensionArray.argsort.
Returns
-------
np.ndarray[np.intp]
Definition at line 369 of file sorting.py.
References ensure_key_mapped(), and nargsort().
Referenced by get_indexer_indexer(), and nargsort().