Code Cloning Analysis: numpy.lib.tests.test_io.TextIO Class Reference
numpy.lib.tests.test_io.TextIO Class Reference
Public Member Functions
__init__ (self, s="")
write (self, s)
writelines (self, lines)
Detailed Description
Helper IO class.
Writes encode strings to bytes if needed, reads return bytes.
This makes it easier to emulate files opened in binary mode
without needing to explicitly convert strings to bytes in
setting up the test data.
Definition at line 33 of file test_io.py.
Constructor & Destructor Documentation
__init__()
numpy.lib.tests.test_io.TextIO.__init__ (self, s = "")
Definition at line 42 of file test_io.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
write()
numpy.lib.tests.test_io.TextIO.write (self, s)
Definition at line 45 of file test_io.py.
Referenced by joblib.externals.cloudpickle.cloudpickle.Pickler.reducer_override(), scipy.io.matlab._mio5.VarWriter5.write_sparse(), pandas.io.formats.html.HTMLFormatter.write_th(), and scipy.io.matlab._mio5.VarWriter5.write_top().
writelines()
numpy.lib.tests.test_io.TextIO.writelines (self, lines)
Definition at line 48 of file test_io.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/lib/tests/test_io.py