Code Cloning Analysis: numpy.ma.core.MaskedIterator Class Reference
numpy.ma.core.MaskedIterator Class Reference
Public Member Functions
__init__ (self, ma)
__iter__ (self)
__getitem__ (self, indx)
__setitem__ (self, index, value)
__next__ (self)
Public Attributes
ma = ma
dataiter = ma._data.flat
maskiter = None
Detailed Description
Flat iterator object to iterate over masked arrays.
A `MaskedIterator` iterator is returned by ``x.flat`` for any masked array
`x`. It allows iterating over the array as if it were a 1-D array,
either in a for-loop or by calling its `next` method.
Iteration is done in C-contiguous style, with the last index varying the
fastest. The iterator can also be indexed using basic slicing or
advanced indexing.
See Also
--------
MaskedArray.flat : Return a flat iterator over an array.
MaskedArray.flatten : Returns a flattened copy of an array.
Notes
-----
`MaskedIterator` is not exported by the `ma` module. Instead of
instantiating a `MaskedIterator` directly, use `MaskedArray.flat`.
Examples
--------
>>> x = np.ma.array(arange(6).reshape(2, 3))
>>> fl = x.flat
>>> type(fl)
<class 'numpy.ma.core.MaskedIterator'>
>>> for item in fl:
...     print(item)
...
0
1
2
3
4
5
Extracting more than a single element b indexing the `MaskedIterator`
returns a masked array:
>>> fl[2:4]
masked_array(data = [2 3],
             mask = False,
       fill_value = 999999)
Definition at line 2589 of file core.py.
Constructor & Destructor Documentation
__init__()
numpy.ma.core.MaskedIterator.__init__ (self, ma)
Definition at line 2637 of file core.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__getitem__()
numpy.ma.core.MaskedIterator.__getitem__ (self, indx)
Definition at line 2649 of file core.py.
__iter__()
numpy.ma.core.MaskedIterator.__iter__ (self)
Definition at line 2646 of file core.py.
__next__()
numpy.ma.core.MaskedIterator.__next__ (self)
Return the next value, or raise StopIteration.
Examples
--------
>>> x = np.ma.array([3, 2], mask=[0, 1])
>>> fl = x.flat
>>> next(fl)
3
>>> next(fl)
masked
>>> next(fl)
Traceback (most recent call last):
  ...
StopIteration
Definition at line 2669 of file core.py.
References dataiter, ma, and maskiter.
__setitem__()
numpy.ma.core.MaskedIterator.__setitem__ (self, index, value)
Definition at line 2664 of file core.py.
Member Data Documentation
dataiter
numpy.ma.core.MaskedIterator.dataiter = ma._data.flat
Definition at line 2639 of file core.py.
Referenced by __next__().
ma
numpy.ma.core.MaskedIterator.ma = ma
Definition at line 2638 of file core.py.
Referenced by __next__().
maskiter
numpy.ma.core.MaskedIterator.maskiter = None
Definition at line 2642 of file core.py.
Referenced by __next__().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/ma/core.py