Code Cloning Analysis: numpy.core._exceptions._UFuncBinaryResolutionError Class Reference
numpy.core._exceptions._UFuncBinaryResolutionError Class Reference
Public Member Functions
__init__ (self, ufunc, dtypes)
__str__ (self)
Public Member Functions inherited from numpy.core._exceptions._UFuncNoLoopError
__init__ (self, ufunc, dtypes)
__str__ (self)
Public Member Functions inherited from numpy.core._exceptions.UFuncTypeError
__init__ (self, ufunc)
Additional Inherited Members
Public Attributes inherited from numpy.core._exceptions._UFuncNoLoopError
dtypes = tuple(dtypes)
Public Attributes inherited from numpy.core._exceptions.UFuncTypeError
ufunc = ufunc
Detailed Description
 Thrown when a binary resolution fails
Definition at line 57 of file _exceptions.py.
Constructor & Destructor Documentation
__init__()
numpy.core._exceptions._UFuncBinaryResolutionError.__init__ (self, ufunc, dtypes)
Definition at line 59 of file _exceptions.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__str__()
numpy.core._exceptions._UFuncBinaryResolutionError.__str__ (self)
Definition at line 63 of file _exceptions.py.
Referenced by numpy.polynomial._polybase.ABCPolyBase._get_coefficients().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/core/_exceptions.py