Code Cloning Analysis: scipy.fft._pocketfft.basic Namespace Reference
scipy.fft._pocketfft.basic Namespace Reference
Functions
c2c (forward, x, n=None, axis=-1, norm=None, overwrite_x=False, workers=None, *, plan=None)
r2c (forward, x, n=None, axis=-1, norm=None, overwrite_x=False, workers=None, *, plan=None)
c2r (forward, x, n=None, axis=-1, norm=None, overwrite_x=False, workers=None, *, plan=None)
fft2 (x, s=None, axes=(-2,-1), norm=None, overwrite_x=False, workers=None, *, plan=None)
ifft2 (x, s=None, axes=(-2,-1), norm=None, overwrite_x=False, workers=None, *, plan=None)
rfft2 (x, s=None, axes=(-2,-1), norm=None, overwrite_x=False, workers=None, *, plan=None)
irfft2 (x, s=None, axes=(-2,-1), norm=None, overwrite_x=False, workers=None, *, plan=None)
hfft2 (x, s=None, axes=(-2,-1), norm=None, overwrite_x=False, workers=None, *, plan=None)
ihfft2 (x, s=None, axes=(-2,-1), norm=None, overwrite_x=False, workers=None, *, plan=None)
c2cn (forward, x, s=None, axes=None, norm=None, overwrite_x=False, workers=None, *, plan=None)
r2cn (forward, x, s=None, axes=None, norm=None, overwrite_x=False, workers=None, *, plan=None)
c2rn (forward, x, s=None, axes=None, norm=None, overwrite_x=False, workers=None, *, plan=None)
r2r_fftpack (forward, x, n=None, axis=-1, norm=None, overwrite_x=False)
Variables
fft = functools.partial(c2c, True)
__name__
ifft = functools.partial(c2c, False)
rfft = functools.partial(r2c, True)
ihfft = functools.partial(r2c, False)
hfft = functools.partial(c2r, True)
irfft = functools.partial(c2r, False)
fftn = functools.partial(c2cn, True)
ifftn = functools.partial(c2cn, False)
rfftn = functools.partial(r2cn, True)
ihfftn = functools.partial(r2cn, False)
hfftn = functools.partial(c2rn, True)
irfftn = functools.partial(c2rn, False)
rfft_fftpack = functools.partial(r2r_fftpack, True)
irfft_fftpack = functools.partial(r2r_fftpack, False)
Detailed Description
Discrete Fourier Transforms - basic.py
Function Documentation
c2c()
scipy.fft._pocketfft.basic.c2c (forward, x, n = None, axis = -1, norm = None, overwrite_x = False, workers = None, * , plan = None)
 Return discrete Fourier transform of real or complex sequence.
Definition at line 11 of file basic.py.
References scipy.fft._pocketfft.helper._asfarray(), scipy.fft._pocketfft.helper._datacopied(), and scipy.fft._pocketfft.helper._normalization().
c2cn()
scipy.fft._pocketfft.basic.c2cn (forward, x, s = None, axes = None, norm = None, overwrite_x = False, workers = None, * , plan = None)
Return multidimensional discrete Fourier transform.
Definition at line 172 of file basic.py.
References scipy.fft._pocketfft.helper._asfarray(), scipy.fft._pocketfft.helper._datacopied(), scipy.fft._pocketfft.helper._fix_shape(), scipy.fft._pocketfft.helper._init_nd_shape_and_axes(), and scipy.fft._pocketfft.helper._normalization().
c2r()
scipy.fft._pocketfft.basic.c2r (forward, x, n = None, axis = -1, norm = None, overwrite_x = False, workers = None, * , plan = None)
Return inverse discrete Fourier transform of real sequence x.
Definition at line 71 of file basic.py.
References scipy.fft._pocketfft.helper._asfarray(), and scipy.fft._pocketfft.helper._normalization().
c2rn()
scipy.fft._pocketfft.basic.c2rn (forward, x, s = None, axes = None, norm = None, overwrite_x = False, workers = None, * , plan = None)
Multidimensional inverse discrete fourier transform with real output
Definition at line 232 of file basic.py.
References scipy.fft._pocketfft.helper._asfarray(), scipy.fft._pocketfft.helper._fix_shape(), scipy.fft._pocketfft.helper._init_nd_shape_and_axes(), and scipy.fft._pocketfft.helper._normalization().
fft2()
scipy.fft._pocketfft.basic.fft2 (x, s = None, axes = (-2,-1), norm = None, overwrite_x = False, workers = None, * , plan = None)
2-D discrete Fourier transform.
Definition at line 106 of file basic.py.
hfft2()
scipy.fft._pocketfft.basic.hfft2 (x, s = None, axes = (-2,-1), norm = None, overwrite_x = False, workers = None, * , plan = None)
2-D discrete Fourier transform of a Hermitian sequence
Definition at line 150 of file basic.py.
ifft2()
scipy.fft._pocketfft.basic.ifft2 (x, s = None, axes = (-2,-1), norm = None, overwrite_x = False, workers = None, * , plan = None)
2-D discrete inverse Fourier transform of real or complex sequence.
Definition at line 117 of file basic.py.
ihfft2()
scipy.fft._pocketfft.basic.ihfft2 (x, s = None, axes = (-2,-1), norm = None, overwrite_x = False, workers = None, * , plan = None)
2-D discrete inverse Fourier transform of a Hermitian sequence
Definition at line 161 of file basic.py.
irfft2()
scipy.fft._pocketfft.basic.irfft2 (x, s = None, axes = (-2,-1), norm = None, overwrite_x = False, workers = None, * , plan = None)
2-D discrete inverse Fourier transform of a real sequence
Definition at line 139 of file basic.py.
r2c()
scipy.fft._pocketfft.basic.r2c (forward, x, n = None, axis = -1, norm = None, overwrite_x = False, workers = None, * , plan = None)
Discrete Fourier transform of a real sequence.
Definition at line 40 of file basic.py.
References scipy.fft._pocketfft.helper._asfarray(), and scipy.fft._pocketfft.helper._normalization().
r2cn()
scipy.fft._pocketfft.basic.r2cn (forward, x, s = None, axes = None, norm = None, overwrite_x = False, workers = None, * , plan = None)
Return multidimensional discrete Fourier transform of real input
Definition at line 203 of file basic.py.
References scipy.fft._pocketfft.helper._asfarray(), scipy.fft._pocketfft.helper._fix_shape(), scipy.fft._pocketfft.helper._init_nd_shape_and_axes(), and scipy.fft._pocketfft.helper._normalization().
r2r_fftpack()
scipy.fft._pocketfft.basic.r2r_fftpack (forward, x, n = None, axis = -1, norm = None, overwrite_x = False)
FFT of a real sequence, returning fftpack half complex format
Definition at line 272 of file basic.py.
References scipy.fft._pocketfft.helper._asfarray(), scipy.fft._pocketfft.helper._datacopied(), and scipy.fft._pocketfft.helper._normalization().
rfft2()
scipy.fft._pocketfft.basic.rfft2 (x, s = None, axes = (-2,-1), norm = None, overwrite_x = False, workers = None, * , plan = None)
2-D discrete Fourier transform of a real sequence
Definition at line 128 of file basic.py.
Variable Documentation
__name__
scipy.fft._pocketfft.basic.__name__ private
Definition at line 35 of file basic.py.
fft
scipy.fft._pocketfft.basic.fft = functools.partial(c2c, True)
Definition at line 34 of file basic.py.
fftn
scipy.fft._pocketfft.basic.fftn = functools.partial(c2cn, True)
Definition at line 198 of file basic.py.
hfft
scipy.fft._pocketfft.basic.hfft = functools.partial(c2r, True)
Definition at line 100 of file basic.py.
hfftn
scipy.fft._pocketfft.basic.hfftn = functools.partial(c2rn, True)
Definition at line 266 of file basic.py.
ifft
scipy.fft._pocketfft.basic.ifft = functools.partial(c2c, False)
Definition at line 36 of file basic.py.
ifftn
scipy.fft._pocketfft.basic.ifftn = functools.partial(c2cn, False)
Definition at line 200 of file basic.py.
ihfft
scipy.fft._pocketfft.basic.ihfft = functools.partial(r2c, False)
Definition at line 67 of file basic.py.
ihfftn
scipy.fft._pocketfft.basic.ihfftn = functools.partial(r2cn, False)
Definition at line 228 of file basic.py.
irfft
scipy.fft._pocketfft.basic.irfft = functools.partial(c2r, False)
Definition at line 102 of file basic.py.
irfft_fftpack
scipy.fft._pocketfft.basic.irfft_fftpack = functools.partial(r2r_fftpack, False)
Definition at line 296 of file basic.py.
irfftn
scipy.fft._pocketfft.basic.irfftn = functools.partial(c2rn, False)
Definition at line 268 of file basic.py.
rfft
scipy.fft._pocketfft.basic.rfft = functools.partial(r2c, True)
Definition at line 65 of file basic.py.
rfft_fftpack
scipy.fft._pocketfft.basic.rfft_fftpack = functools.partial(r2r_fftpack, True)
Definition at line 294 of file basic.py.
rfftn
scipy.fft._pocketfft.basic.rfftn = functools.partial(r2cn, True)
Definition at line 226 of file basic.py.