Code Cloning Analysis: matplotlib.projections.polar.ThetaAxis Class Reference
matplotlib.projections.polar.ThetaAxis Class Reference
Public Member Functions
clear (self)
Public Attributes
bool isDefault_majloc = True
bool isDefault_majfmt = True
Static Public Attributes
str axis_name = 'theta'
Protected Member Functions
_wrap_locator_formatter (self)
_set_scale (self, value, **kwargs)
_copy_tick_props (self, src, dest)
Static Protected Attributes
_tick_class = ThetaTick
Static Private Attributes
str __name__ = 'thetaaxis'
Detailed Description
A theta Axis.
This overrides certain properties of an `.XAxis` to provide special-casing
for an angular axis.
Definition at line 418 of file polar.py.
Member Function Documentation
_copy_tick_props()
matplotlib.projections.polar.ThetaAxis._copy_tick_props (self, src, dest) protected
Copy the props from src tick to dest tick.
Definition at line 452 of file polar.py.
References _copy_tick_props().
Referenced by _copy_tick_props().
_set_scale()
matplotlib.projections.polar.ThetaAxis._set_scale (self, value, ** kwargs) protected
Definition at line 441 of file polar.py.
_wrap_locator_formatter()
matplotlib.projections.polar.ThetaAxis._wrap_locator_formatter (self) protected
Definition at line 429 of file polar.py.
clear()
matplotlib.projections.polar.ThetaAxis.clear (self)
Definition at line 435 of file polar.py.
Referenced by matplotlib.widgets.MultiCursor.connect(), matplotlib.projections.geo.AitoffAxes.InvertedAitoffTransform.inverted(), matplotlib.projections.geo.HammerAxes.InvertedHammerTransform.inverted(), matplotlib.projections.geo.LambertAxes.InvertedLambertTransform.inverted(), and matplotlib.projections.geo.MollweideAxes.InvertedMollweideTransform.inverted().
Member Data Documentation
__name__
str matplotlib.projections.polar.ThetaAxis.__name__ = 'thetaaxis' static private
Definition at line 425 of file polar.py.
Referenced by sklearn.utils.deprecation.deprecated.__call__(), pandas.tseries.holiday.Holiday._apply_rule(), sklearn.utils._metadata_requests._MetadataRequester._build_request_for_signature(), pandas.core.arrays.interval.IntervalArray._from_factorized(), sklearn.utils._metadata_requests._MetadataRequester._get_default_requests(), pandas.tests.extension.date.array.DateDtype.construct_from_string(), pip._vendor.pygments.sphinxext.PygmentsDoc.document_lexers_overview(), numpy.ma.extras._fromnxfunction.getdoc(), and matplotlib.patches._Style.pprint_styles().
_tick_class
matplotlib.projections.polar.ThetaAxis._tick_class = ThetaTick static protected
Definition at line 427 of file polar.py.
axis_name
str matplotlib.projections.polar.ThetaAxis.axis_name = 'theta' static
Definition at line 426 of file polar.py.
isDefault_majfmt
bool matplotlib.projections.polar.ThetaAxis.isDefault_majfmt = True
Definition at line 433 of file polar.py.
isDefault_majloc
bool matplotlib.projections.polar.ThetaAxis.isDefault_majloc = True
Definition at line 432 of file polar.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/projections/polar.py