Code Cloning Analysis: pandas.core.reshape.merge._OrderedMerge Class Reference
pandas.core.reshape.merge._OrderedMerge Class Reference
Public Member Functions
None __init__ (self, DataFrame|Series left, DataFrame|Series right, IndexLabel|None on=None, IndexLabel|None left_on=None, IndexLabel|None right_on=None, bool left_index=False, bool right_index=False, Suffixes suffixes=("_x", "_y"), str|None fill_method=None, JoinHow|Literal["asof"] how="outer")
DataFrame get_result (self, bool|None copy=True)
Public Member Functions inherited from pandas.core.reshape.merge._MergeOperation
None __init__ (self, DataFrame|Series left, DataFrame|Series right, JoinHow|Literal["asof"] how="inner", IndexLabel|AnyArrayLike|None on=None, IndexLabel|AnyArrayLike|None left_on=None, IndexLabel|AnyArrayLike|None right_on=None, bool left_index=False, bool right_index=False, bool sort=True, Suffixes suffixes=("_x", "_y"), str|bool indicator=False, str|None validate=None)
Public Attributes
str fill_method = fill_method
Public Attributes inherited from pandas.core.reshape.merge._MergeOperation
left = _left
tuple[DataFrame, DataFrame] right = _right
suffixes = suffixes
JoinHow sort = "outer"
left_index = left_index
right_index = right_index
Additional Inherited Members
Static Public Attributes inherited from pandas.core.reshape.merge._MergeOperation
JoinHow how | Literal["asof"]
IndexLabel on | None
Sequence left_on [Hashable | AnyArrayLike]
Sequence right_on [Hashable | AnyArrayLike]
str indicator | bool
str validate | None
list join_names [Hashable]
list right_join_keys [ArrayLike]
list left_join_keys [ArrayLike]
Protected Member Functions inherited from pandas.core.reshape.merge._MergeOperation
None _maybe_require_matching_dtypes (self, list[ArrayLike] left_join_keys, list[ArrayLike] right_join_keys)
None _validate_tolerance (self, list[ArrayLike] left_join_keys)
DataFrame _reindex_and_concat (self, Index join_index, npt.NDArray[np.intp]|None left_indexer, npt.NDArray[np.intp]|None right_indexer, bool|None copy)
str|None _indicator_name (self)
tuple[DataFrame, DataFrame] _indicator_pre_merge (self, DataFrame left, DataFrame right)
DataFrame _indicator_post_merge (self, DataFrame result)
None _maybe_restore_index_levels (self, DataFrame result)
None _maybe_add_join_keys (self, DataFrame result, npt.NDArray[np.intp]|None left_indexer, npt.NDArray[np.intp]|None right_indexer)
tuple[npt.NDArray[np.intp]|None, npt.NDArray[np.intp]|None] _get_join_indexers (self)
tuple[Index, npt.NDArray[np.intp]|None, npt.NDArray[np.intp]|None] _get_join_info (self)
Index _create_join_index (self, Index index, Index other_index, npt.NDArray[np.intp]|None indexer, JoinHow how="left")
tuple[ list[ArrayLike], list[ArrayLike], list[Hashable], list[Hashable], list[Hashable],] _get_merge_keys (self)
None _maybe_coerce_merge_keys (self)
_validate_left_right_on (self, left_on, right_on)
None _validate_validate_kwd (self, str validate)
Static Protected Attributes inherited from pandas.core.reshape.merge._MergeOperation
str _merge_type = "merge"
Detailed Description
Definition at line 1895 of file merge.py.
Constructor & Destructor Documentation
__init__()
None pandas.core.reshape.merge._OrderedMerge.__init__ (self, DataFrame | Series left, DataFrame | Series right, IndexLabel | None on = None, IndexLabel | None left_on = None, IndexLabel | None right_on = None, bool left_index = False, bool right_index = False, Suffixes suffixes = ("_x", "_y"), str | None fill_method = None, JoinHow | Literal["asof"] how = "outer")
Definition at line 1898 of file merge.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
get_result()
DataFrame pandas.core.reshape.merge._OrderedMerge.get_result (self, bool | None copy = True)
Reimplemented from pandas.core.reshape.merge._MergeOperation.
Definition at line 1926 of file merge.py.
Referenced by scipy.optimize._zeros_py.TOMS748Solver.solve().
Member Data Documentation
fill_method
str pandas.core.reshape.merge._OrderedMerge.fill_method = fill_method
Definition at line 1911 of file merge.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/core/reshape/merge.py