Code Cloning Analysis: pandas.core.ops.common Namespace Reference
pandas.core.ops.common Namespace Reference
Functions
Callable[[F], F] unpack_zerodim_and_defer (str name)
_unpack_zerodim_and_defer (method, str name)
get_op_result_name (left, right)
_maybe_match_name (a, b)
Variables
__pandas_priority__
Detailed Description
Boilerplate functions used in defining binary operations.
Function Documentation
_maybe_match_name()
pandas.core.ops.common._maybe_match_name (a, b) protected
Try to find a name to attach to the result of an operation between
a and b.  If only one of these has a `name` attribute, return that
name.  Otherwise return a consensus name if they match or None if
they have different names.
Parameters
----------
a : object
b : object
Returns
-------
name : str or None
See Also
--------
pandas.core.common.consensus_name_attr
Definition at line 103 of file common.py.
Referenced by get_op_result_name().
_unpack_zerodim_and_defer()
pandas.core.ops.common._unpack_zerodim_and_defer (method, str name) protected
Boilerplate for pandas conventions in arithmetic and comparison methods.
Ensure method returns NotImplemented when operating against "senior"
classes.  Ensure zero-dimensional ndarrays are always unpacked.
Parameters
----------
method : binary method
name : str
Returns
-------
method
Definition at line 43 of file common.py.
Referenced by unpack_zerodim_and_defer().
get_op_result_name()
pandas.core.ops.common.get_op_result_name (left, right)
Find the appropriate name to pin to an operation result.  This result
should always be either an Index or a Series.
Parameters
----------
left : {Series, Index}
right : object
Returns
-------
name : object
    Usually a string
Definition at line 81 of file common.py.
References _maybe_match_name().
unpack_zerodim_and_defer()
Callable[[F], F] pandas.core.ops.common.unpack_zerodim_and_defer (str name)
Boilerplate for pandas conventions in arithmetic and comparison methods.
Parameters
----------
name : str
Returns
-------
decorator
Definition at line 24 of file common.py.
References _unpack_zerodim_and_defer().
Variable Documentation
__pandas_priority__
pandas.core.ops.common.__pandas_priority__ private
Definition at line 70 of file common.py.