Code Cloning Analysis: sklearn.externals.array_api_extra._lib._testing Namespace Reference
sklearn.externals.array_api_extra._lib._testing Namespace Reference
Functions
ModuleType _check_ns_shape_dtype (Array actual, Array desired)
None xp_assert_equal (Array actual, Array desired, str err_msg="")
None xp_assert_close (Array actual, Array desired, *, float|None rtol=None, float atol=0, str err_msg="")
None xfail (pytest.FixtureRequest request, str reason)
Variables
list __all__ = ["xp_assert_close", "xp_assert_equal"]
Detailed Description
Testing utilities.
Note that this is private API; don't expect it to be stable.
See also ..testing for public testing utilities.
Function Documentation
_check_ns_shape_dtype()
ModuleType sklearn.externals.array_api_extra._lib._testing._check_ns_shape_dtype (Array actual, Array desired) protected
Assert that namespace, shape and dtype of the two arrays match.
Parameters
----------
actual : Array
    The array produced by the tested function.
desired : Array
    The expected array (typically hardcoded).
Returns
-------
Arrays namespace.
Definition at line 27 of file _testing.py.
Referenced by xp_assert_close(), and xp_assert_equal().
xfail()
None sklearn.externals.array_api_extra._lib._testing.xfail (pytest.FixtureRequest request, str reason)
XFAIL the currently running test.
Unlike ``pytest.xfail``, allow rest of test to execute instead of immediately
halting it, so that it may result in a XPASS.
xref https://github.com/pandas-dev/pandas/issues/38902
Parameters
----------
request : pytest.FixtureRequest
    ``request`` argument of the test function.
reason : str
    Reason for the expected failure.
Definition at line 205 of file _testing.py.
xp_assert_close()
None sklearn.externals.array_api_extra._lib._testing.xp_assert_close (Array actual, Array desired, * , float | None rtol = None, float atol = 0, str err_msg = "")
Array-API compatible version of `np.testing.assert_allclose`.
Parameters
----------
actual : Array
    The array produced by the tested function.
desired : Array
    The expected array (typically hardcoded).
rtol : float, optional
    Relative tolerance. Default: dtype-dependent.
atol : float, optional
    Absolute tolerance. Default: 0.
err_msg : str, optional
    Error message to display on failure.
See Also
--------
xp_assert_equal : Similar function for exact equality checks.
isclose : Public function for checking closeness.
numpy.testing.assert_allclose : Similar function for NumPy arrays.
Notes
-----
The default `atol` and `rtol` differ from `xp.all(xpx.isclose(a, b))`.
Definition at line 123 of file _testing.py.
References _check_ns_shape_dtype().
xp_assert_equal()
None sklearn.externals.array_api_extra._lib._testing.xp_assert_equal (Array actual, Array desired, str err_msg = "")
Array-API compatible version of `np.testing.assert_array_equal`.
Parameters
----------
actual : Array
    The array produced by the tested function.
desired : Array
    The expected array (typically hardcoded).
err_msg : str, optional
    Error message to display on failure.
See Also
--------
xp_assert_close : Similar function for inexact equality checks.
numpy.testing.assert_array_equal : Similar function for NumPy arrays.
Definition at line 68 of file _testing.py.
References _check_ns_shape_dtype().
Variable Documentation
__all__
list sklearn.externals.array_api_extra._lib._testing.__all__ = ["xp_assert_close", "xp_assert_equal"] private
Definition at line 24 of file _testing.py.