Code Cloning Analysis: numpy.lib.index_tricks.ndenumerate Class Reference
numpy.lib.index_tricks.ndenumerate Class Reference
Public Member Functions
__init__ (self, arr)
__next__ (self)
__iter__ (self)
Public Attributes
iter = np.asarray(arr).flat
Detailed Description
Multidimensional index iterator.
Return an iterator yielding pairs of array coordinates and values.
Parameters
----------
arr : ndarray
  Input array.
See Also
--------
ndindex, flatiter
Examples
--------
>>> a = np.array([[1, 2], [3, 4]])
>>> for index, x in np.ndenumerate(a):
...     print(index, x)
(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4
Definition at line 570 of file index_tricks.py.
Constructor & Destructor Documentation
__init__()
numpy.lib.index_tricks.ndenumerate.__init__ (self, arr)
Definition at line 597 of file index_tricks.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__iter__()
numpy.lib.index_tricks.ndenumerate.__iter__ (self)
Definition at line 614 of file index_tricks.py.
__next__()
numpy.lib.index_tricks.ndenumerate.__next__ (self)
Standard iterator method, returns the index tuple and array value.
Returns
-------
coords : tuple of ints
    The indices of the current iteration.
val : scalar
    The array element of the current iteration.
Definition at line 600 of file index_tricks.py.
References iter.
Member Data Documentation
iter
numpy.lib.index_tricks.ndenumerate.iter = np.asarray(arr).flat
Definition at line 598 of file index_tricks.py.
Referenced by __next__(), and pip._vendor.tenacity.BaseRetrying.wraps().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/lib/index_tricks.py