Code Cloning Analysis: matplotlib.offsetbox Namespace Reference
matplotlib.offsetbox Namespace Reference
Classes
class AnchoredOffsetbox
class AnchoredText
class AnnotationBbox
class AuxTransformBox
class DraggableAnnotation
class DraggableBase
class DraggableOffsetBox
class DrawingArea
class HPacker
class OffsetBox
class OffsetImage
class PackerBase
class PaddedBox
class TextArea
class VPacker
Functions
_compat_get_offset (meth)
_bbox_artist (*args, **kwargs)
_get_packed_offsets (widths, total, sep, mode="fixed")
_get_aligned_offsets (yspans, height, align="baseline")
_get_anchored_bbox (loc, bbox, parentbbox, borderpad)
Variables
bool DEBUG = False
Detailed Description
Container classes for `.Artist`\s.
`OffsetBox`
    The base of all container artists defined in this module.
`AnchoredOffsetbox`, `AnchoredText`
    Anchor and align an arbitrary `.Artist` or a text relative to the parent
    axes or a specific anchor point.
`DrawingArea`
    A container with fixed width and height. Children have a fixed position
    inside the container and may be clipped.
`HPacker`, `VPacker`
    Containers for layouting their children vertically or horizontally.
`PaddedBox`
    A container to add a padding around an `.Artist`.
`TextArea`
    Contains a single `.Text` instance.
Function Documentation
_bbox_artist()
matplotlib.offsetbox._bbox_artist (* args, ** kwargs) protected
Definition at line 65 of file offsetbox.py.
_compat_get_offset()
matplotlib.offsetbox._compat_get_offset (meth) protected
Decorator for the get_offset method of OffsetBox and subclasses, that
allows supporting both the new signature (self, bbox, renderer) and the old
signature (self, width, height, xdescent, ydescent, renderer).
Definition at line 45 of file offsetbox.py.
_get_aligned_offsets()
matplotlib.offsetbox._get_aligned_offsets (yspans, height, align = "baseline") protected
Align boxes each specified by their ``(y0, y1)`` spans.
For simplicity of the description, the terminology used here assumes a
horizontal layout (i.e., vertical alignment), but the function works
equally for a vertical layout.
Parameters
----------
yspans
    List of (y0, y1) spans of boxes to be aligned.
height : float or None
    Intended total height. If None, the maximum of the heights
    (``y1 - y0``) in *yspans* is used.
align : {'baseline', 'left', 'top', 'right', 'bottom', 'center'}
    The alignment anchor of the boxes.
Returns
-------
(y0, y1)
    y range spanned by the packing.  If a *height* was originally passed
    in, then for all alignments other than "baseline", a span of ``(0,
    height)`` is used without checking that it is actually large enough).
descent
    The descent of the packing.
offsets
    The bottom offsets of the boxes.
Definition at line 151 of file offsetbox.py.
Referenced by matplotlib.offsetbox.HPacker._get_bbox_and_child_offsets(), and matplotlib.offsetbox.VPacker._get_bbox_and_child_offsets().
_get_anchored_bbox()
matplotlib.offsetbox._get_anchored_bbox (loc, bbox, parentbbox, borderpad) protected
Return the (x, y) position of the *bbox* anchored at the *parentbbox* with
the *loc* code with the *borderpad*.
Definition at line 1089 of file offsetbox.py.
Referenced by matplotlib.offsetbox.AnchoredOffsetbox.get_offset().
_get_packed_offsets()
matplotlib.offsetbox._get_packed_offsets (widths, total, sep, mode = "fixed") protected
Pack boxes specified by their *widths*.
For simplicity of the description, the terminology used here assumes a
horizontal layout, but the function works equally for a vertical layout.
There are three packing *mode*\s:
- 'fixed': The elements are packed tight to the left with a spacing of
  *sep* in between. If *total* is *None* the returned total will be the
  right edge of the last box. A non-*None* total will be passed unchecked
  to the output. In particular this means that right edge of the last
  box may be further to the right than the returned total.
- 'expand': Distribute the boxes with equal spacing so that the left edge
  of the first box is at 0, and the right edge of the last box is at
  *total*. The parameter *sep* is ignored in this mode. A total of *None*
  is accepted and considered equal to 1. The total is returned unchanged
  (except for the conversion *None* to 1). If the total is smaller than
  the sum of the widths, the laid out boxes will overlap.
- 'equal': If *total* is given, the total space is divided in N equal
  ranges and each box is left-aligned within its subspace.
  Otherwise (*total* is *None*), *sep* must be provided and each box is
  left-aligned in its subspace of width ``(max(widths) + sep)``. The
  total width is then calculated to be ``N * (max(widths) + sep)``.
Parameters
----------
widths : list of float
    Widths of boxes to be packed.
total : float or None
    Intended total length. *None* if not used.
sep : float or None
    Spacing between boxes.
mode : {'fixed', 'expand', 'equal'}
    The packing mode.
Returns
-------
total : float
    The total width needed to accommodate the laid out boxes.
offsets : array of float
    The left offsets of the boxes.
Definition at line 70 of file offsetbox.py.
Referenced by matplotlib.offsetbox.HPacker._get_bbox_and_child_offsets(), and matplotlib.offsetbox.VPacker._get_bbox_and_child_offsets().
Variable Documentation
DEBUG
bool matplotlib.offsetbox.DEBUG = False
Definition at line 42 of file offsetbox.py.