Code Cloning Analysis: pandas.tests.frame.methods.test_dot.DotSharedTests Class Reference
pandas.tests.frame.methods.test_dot.DotSharedTests Class Reference
Public Member Functions
obj (self)
DataFrame other (self)
DataFrame expected (self, obj, other)
reduced_dim_assert (cls, result, expected)
test_dot_equiv_values_dot (self, obj, other, expected)
test_dot_2d_ndarray (self, obj, other, expected)
test_dot_1d_ndarray (self, obj, expected)
test_dot_series (self, obj, other, expected)
test_dot_series_alignment (self, obj, other, expected)
test_dot_aligns (self, obj, other, expected)
test_dot_shape_mismatch (self, obj)
test_dot_misaligned (self, obj, other)
Detailed Description
Definition at line 11 of file test_dot.py.
Member Function Documentation
expected()
DataFrame pandas.tests.frame.methods.test_dot.DotSharedTests.expected (self, obj, other)
The expected result of obj.dot(other)
Reimplemented in pandas.tests.frame.methods.test_dot.TestDataFrameDot, and pandas.tests.frame.methods.test_dot.TestSeriesDot.
Definition at line 24 of file test_dot.py.
obj()
pandas.tests.frame.methods.test_dot.DotSharedTests.obj (self)
Definition at line 13 of file test_dot.py.
Referenced by pandas.core.indexing._AtIndexer._convert_key().
other()
DataFrame pandas.tests.frame.methods.test_dot.DotSharedTests.other (self)
other is a DataFrame that is indexed so that obj.dot(other) is valid
Reimplemented in pandas.tests.frame.methods.test_dot.TestDataFrameDot, and pandas.tests.frame.methods.test_dot.TestSeriesDot.
Definition at line 17 of file test_dot.py.
reduced_dim_assert()
pandas.tests.frame.methods.test_dot.DotSharedTests.reduced_dim_assert (cls, result, expected)
Assertion about results with 1 fewer dimension that self.obj
Reimplemented in pandas.tests.frame.methods.test_dot.TestDataFrameDot, and pandas.tests.frame.methods.test_dot.TestSeriesDot.
Definition at line 31 of file test_dot.py.
References reduced_dim_assert().
Referenced by reduced_dim_assert().
test_dot_1d_ndarray()
pandas.tests.frame.methods.test_dot.DotSharedTests.test_dot_1d_ndarray (self, obj, expected)
Definition at line 48 of file test_dot.py.
test_dot_2d_ndarray()
pandas.tests.frame.methods.test_dot.DotSharedTests.test_dot_2d_ndarray (self, obj, other, expected)
Definition at line 42 of file test_dot.py.
test_dot_aligns()
pandas.tests.frame.methods.test_dot.DotSharedTests.test_dot_aligns (self, obj, other, expected)
Definition at line 65 of file test_dot.py.
test_dot_equiv_values_dot()
pandas.tests.frame.methods.test_dot.DotSharedTests.test_dot_equiv_values_dot (self, obj, other, expected)
Definition at line 37 of file test_dot.py.
test_dot_misaligned()
pandas.tests.frame.methods.test_dot.DotSharedTests.test_dot_misaligned (self, obj, other)
Definition at line 77 of file test_dot.py.
test_dot_series()
pandas.tests.frame.methods.test_dot.DotSharedTests.test_dot_series (self, obj, other, expected)
Definition at line 56 of file test_dot.py.
test_dot_series_alignment()
pandas.tests.frame.methods.test_dot.DotSharedTests.test_dot_series_alignment (self, obj, other, expected)
Definition at line 61 of file test_dot.py.
test_dot_shape_mismatch()
pandas.tests.frame.methods.test_dot.DotSharedTests.test_dot_shape_mismatch (self, obj)
Definition at line 71 of file test_dot.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/tests/frame/methods/test_dot.py