Code Cloning Analysis: scipy.fftpack.tests.test_basic.TestOverwrite Class Reference
scipy.fftpack.tests.test_basic.TestOverwrite Class Reference
Public Member Functions
test_fft_ifft (self, dtype, fftsize, overwrite_x, shape, axes)
test_rfft_irfft (self, dtype, fftsize, overwrite_x, shape, axes)
test_fftn_ifftn (self, dtype, overwrite_x, shape, axes)
Static Public Attributes
tuple real_dtypes = (np.float32, np.float64)
tuple dtypes = real_dtypes + (np.complex64, np.complex128)
list fftsizes = [8, 16, 32]
Protected Member Functions
_check (self, x, routine, fftsize, axis, overwrite_x)
_check_1d (self, routine, dtype, shape, axis, overwritable_dtypes, fftsize, overwrite_x)
_check_nd_one (self, routine, dtype, shape, axes, overwritable_dtypes, overwrite_x)
Detailed Description
Check input overwrite behavior of the FFT functions.
Definition at line 748 of file test_basic.py.
Member Function Documentation
_check()
scipy.fftpack.tests.test_basic.TestOverwrite._check (self, x, routine, fftsize, axis, overwrite_x) protected
Definition at line 755 of file test_basic.py.
Referenced by scipy.signal.tests.test_ltisys.TestPlacePoles._check().
_check_1d()
scipy.fftpack.tests.test_basic.TestOverwrite._check_1d (self, routine, dtype, shape, axis, overwritable_dtypes, fftsize, overwrite_x) protected
Definition at line 765 of file test_basic.py.
_check_nd_one()
scipy.fftpack.tests.test_basic.TestOverwrite._check_nd_one (self, routine, dtype, shape, axes, overwritable_dtypes, overwrite_x) protected
Definition at line 803 of file test_basic.py.
test_fft_ifft()
scipy.fftpack.tests.test_basic.TestOverwrite.test_fft_ifft (self, dtype, fftsize, overwrite_x, shape, axes)
Definition at line 783 of file test_basic.py.
test_fftn_ifftn()
scipy.fftpack.tests.test_basic.TestOverwrite.test_fftn_ifftn (self, dtype, overwrite_x, shape, axes)
Definition at line 847 of file test_basic.py.
test_rfft_irfft()
scipy.fftpack.tests.test_basic.TestOverwrite.test_rfft_irfft (self, dtype, fftsize, overwrite_x, shape, axes)
Definition at line 796 of file test_basic.py.
Member Data Documentation
dtypes
tuple scipy.fftpack.tests.test_basic.TestOverwrite.dtypes = real_dtypes + (np.complex64, np.complex128) static
Definition at line 752 of file test_basic.py.
Referenced by scipy.io.matlab._miobase.MatFileReader.__init__(), pandas.core.generic.NDFrame._consolidate(), pandas.core.frame.DataFrame._constructor(), pandas.core.generic.NDFrame._get_cleaned_column_resolvers(), pandas.core.frame.DataFrame.combine_first(), sklearn.externals.array_api_compat.torch._info.__array_namespace_info__.default_dtypes(), pandas.core.frame.DataFrame.dot(), sklearn.externals.array_api_compat.cupy._info.__array_namespace_info__.dtypes(), sklearn.externals.array_api_compat.dask.array._info.__array_namespace_info__.dtypes(), sklearn.externals.array_api_compat.numpy._info.__array_namespace_info__.dtypes(), pandas.core.generic.NDFrame.empty(), scipy.io.matlab._mio4.MatFile4Reader.initialize_read(), pandas.core.frame.DataFrame.quantile(), scipy.io.matlab._mio4.VarReader4.read_header(), and pandas.core.frame.DataFrame.transpose().
fftsizes
list scipy.fftpack.tests.test_basic.TestOverwrite.fftsizes = [8, 16, 32] static
Definition at line 753 of file test_basic.py.
real_dtypes
tuple scipy.fftpack.tests.test_basic.TestOverwrite.real_dtypes = (np.float32, np.float64) static
Definition at line 751 of file test_basic.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/fftpack/tests/test_basic.py