Code Cloning Analysis: sklearn.neighbors._base Namespace Reference
sklearn.neighbors._base Namespace Reference
Classes
class KNeighborsMixin
class NeighborsBase
class RadiusNeighborsMixin
Functions
_get_weights (dist, weights)
_is_sorted_by_data (graph)
_check_precomputed (X)
sort_graph_by_row_values (graph, copy=False, warn_when_not_sorted=True)
_kneighbors_from_graph (graph, n_neighbors, return_distance)
_radius_neighbors_from_graph (graph, radius, return_distance)
Variables
list SCIPY_METRICS
VALID_METRICS
VALID_METRICS_SPARSE
Detailed Description
Base and mixin classes for nearest neighbors.
Function Documentation
_check_precomputed()
sklearn.neighbors._base._check_precomputed (X) protected
Check precomputed distance matrix.
If the precomputed distance matrix is sparse, it checks that the non-zero
entries are sorted by distances. If not, the matrix is copied and sorted.
Parameters
----------
X : {sparse matrix, array-like}, (n_samples, n_samples)
    Distance matrix to other samples. X may be a sparse matrix, in which
    case only non-zero elements may be considered neighbors.
Returns
-------
X : {sparse matrix, array-like}, (n_samples, n_samples)
    Distance matrix to other samples. X may be a sparse matrix, in which
    case only non-zero elements may be considered neighbors.
Definition at line 154 of file _base.py.
References sort_graph_by_row_values().
Referenced by sklearn.neighbors._base.KNeighborsMixin.kneighbors(), and sklearn.neighbors._base.RadiusNeighborsMixin.radius_neighbors().
_get_weights()
sklearn.neighbors._base._get_weights (dist, weights) protected
Get the weights from an array of distances and a parameter ``weights``.
Assume weights have already been validated.
Parameters
----------
dist : ndarray
    The input distances.
weights : {'uniform', 'distance'}, callable or None
    The kind of weighting used.
Returns
-------
weights_arr : array of the same shape as ``dist``
    If ``weights == 'uniform'``, then returns None.
Definition at line 81 of file _base.py.
_is_sorted_by_data()
sklearn.neighbors._base._is_sorted_by_data (graph) protected
Return whether the graph's non-zero entries are sorted by data.
The non-zero entries are stored in graph.data and graph.indices.
For each row (or sample), the non-zero entries can be either:
    - sorted by indices, as after graph.sort_indices();
    - sorted by data, as after _check_precomputed(graph);
    - not sorted.
Parameters
----------
graph : sparse matrix of shape (n_samples, n_samples)
    Neighbors graph as given by `kneighbors_graph` or
    `radius_neighbors_graph`. Matrix should be of format CSR format.
Returns
-------
res : bool
    Whether input graph is sorted by data.
Definition at line 127 of file _base.py.
Referenced by sort_graph_by_row_values().
_kneighbors_from_graph()
sklearn.neighbors._base._kneighbors_from_graph (graph, n_neighbors, return_distance) protected
Decompose a nearest neighbors sparse graph into distances and indices.
Parameters
----------
graph : sparse matrix of shape (n_samples, n_samples)
    Neighbors graph as given by `kneighbors_graph` or
    `radius_neighbors_graph`. Matrix should be of format CSR format.
n_neighbors : int
    Number of neighbors required for each sample.
return_distance : bool
    Whether or not to return the distances.
Returns
-------
neigh_dist : ndarray of shape (n_samples, n_neighbors)
    Distances to nearest neighbors. Only present if `return_distance=True`.
neigh_ind : ndarray of shape (n_samples, n_neighbors)
    Indices of nearest neighbors.
Definition at line 294 of file _base.py.
Referenced by sklearn.neighbors._base.KNeighborsMixin.kneighbors().
_radius_neighbors_from_graph()
sklearn.neighbors._base._radius_neighbors_from_graph (graph, radius, return_distance) protected
Decompose a nearest neighbors sparse graph into distances and indices.
Parameters
----------
graph : sparse matrix of shape (n_samples, n_samples)
    Neighbors graph as given by `kneighbors_graph` or
    `radius_neighbors_graph`. Matrix should be of format CSR format.
radius : float
    Radius of neighborhoods which should be strictly positive.
return_distance : bool
    Whether or not to return the distances.
Returns
-------
neigh_dist : ndarray of shape (n_samples,) of arrays
    Distances to nearest neighbors. Only present if `return_distance=True`.
neigh_ind : ndarray of shape (n_samples,) of arrays
    Indices of nearest neighbors.
Definition at line 346 of file _base.py.
Referenced by sklearn.neighbors._base.RadiusNeighborsMixin.radius_neighbors().
sort_graph_by_row_values()
sklearn.neighbors._base.sort_graph_by_row_values (graph, copy = False, warn_when_not_sorted = True)
Sort a sparse graph such that each row is stored with increasing values.
.. versionadded:: 1.2
Parameters
----------
graph : sparse matrix of shape (n_samples, n_samples)
    Distance matrix to other samples, where only non-zero elements are
    considered neighbors. Matrix is converted to CSR format if not already.
copy : bool, default=False
    If True, the graph is copied before sorting. If False, the sorting is
    performed inplace. If the graph is not of CSR format, `copy` must be
    True to allow the conversion to CSR format, otherwise an error is
    raised.
warn_when_not_sorted : bool, default=True
    If True, a :class:`~sklearn.exceptions.EfficiencyWarning` is raised
    when the input graph is not sorted by row values.
Returns
-------
graph : sparse matrix of shape (n_samples, n_samples)
    Distance matrix to other samples, where only non-zero elements are
    considered neighbors. Matrix is in CSR format.
Examples
--------
>>> from scipy.sparse import csr_matrix
>>> from sklearn.neighbors import sort_graph_by_row_values
>>> X = csr_matrix(
...     [[0., 3., 1.],
...      [3., 0., 2.],
...      [1., 2., 0.]])
>>> X.data
array([3., 1., 3., 2., 1., 2.])
>>> X_ = sort_graph_by_row_values(X)
>>> X_.data
array([1., 3., 2., 3., 1., 2.])
Definition at line 203 of file _base.py.
References _is_sorted_by_data().
Referenced by _check_precomputed().
Variable Documentation
SCIPY_METRICS
list sklearn.neighbors._base.SCIPY_METRICS
Initial value:
=  [
    "braycurtis",
    "canberra",
    "chebyshev",
    "correlation",
    "cosine",
    "dice",
    "hamming",
    "jaccard",
    "mahalanobis",
    "minkowski",
    "rogerstanimoto",
    "russellrao",
    "seuclidean",
    "sokalsneath",
    "sqeuclidean",
    "yule",
]
Definition at line 38 of file _base.py.
VALID_METRICS
sklearn.neighbors._base.VALID_METRICS
Initial value:
=  dict(
    ball_tree=BallTree.valid_metrics,
    kd_tree=KDTree.valid_metrics,
    # The following list comes from the
    # sklearn.metrics.pairwise doc string
    brute=sorted(set(PAIRWISE_DISTANCE_FUNCTIONS).union(SCIPY_METRICS)),
)
Definition at line 66 of file _base.py.
VALID_METRICS_SPARSE
sklearn.neighbors._base.VALID_METRICS_SPARSE
Initial value:
=  dict(
    ball_tree=[],
    kd_tree=[],
    brute=(PAIRWISE_DISTANCE_FUNCTIONS.keys() - {"haversine", "nan_euclidean"}),
)
Definition at line 74 of file _base.py.