Code Cloning Analysis: scipy.integrate._ivp.base.DenseOutput Class Reference
scipy.integrate._ivp.base.DenseOutput Class Reference
Public Member Functions
__init__ (self, t_old, t)
__call__ (self, t)
Public Attributes
t_old = t_old
t = t
t_min = min(t, t_old)
t_max = max(t, t_old)
Protected Member Functions
_call_impl (self, t)
Detailed Description
Base class for local interpolant over step made by an ODE solver.
It interpolates between `t_min` and `t_max` (see Attributes below).
Evaluation outside this interval is not forbidden, but the accuracy is not
guaranteed.
Attributes
----------
t_min, t_max : float
    Time range of the interpolation.
Definition at line 233 of file base.py.
Constructor & Destructor Documentation
__init__()
scipy.integrate._ivp.base.DenseOutput.__init__ (self, t_old, t)
Definition at line 245 of file base.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
__call__()
scipy.integrate._ivp.base.DenseOutput.__call__ (self, t)
Evaluate the interpolant.
Parameters
----------
t : float or array_like with shape (n_points,)
    Points to evaluate the solution at.
Returns
-------
y : ndarray, shape (n,) or (n, n_points)
    Computed values. Shape depends on whether `t` was a scalar or a
    1-D array.
Definition at line 251 of file base.py.
References _call_impl().
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), and scipy.interpolate._fitpack2.SphereBivariateSpline.ev().
_call_impl()
scipy.integrate._ivp.base.DenseOutput._call_impl (self, t) protected
Definition at line 270 of file base.py.
Referenced by __call__().
Member Data Documentation
t
scipy.integrate._ivp.base.DenseOutput.t = t
Definition at line 247 of file base.py.
Referenced by scipy.interpolate._bsplines.BSpline.__call__(), scipy.interpolate._bsplines.BSpline._ensure_c_contiguous(), sklearn.neural_network._stochastic_optimizers.AdamOptimizer._get_updates(), scipy.interpolate._bsplines.BSpline.antiderivative(), scipy.interpolate._bsplines.BSpline.construct_fast(), scipy.interpolate._bsplines.BSpline.derivative(), scipy.integrate._ode.ode.integrate(), scipy.interpolate._bsplines.BSpline.integrate(), scipy.integrate._ode.ode.set_initial_value(), scipy.integrate._ode.ode.set_integrator(), scipy.interpolate._bsplines.BSpline.tck(), and scipy.linalg.tests.test_blas.TestBLAS3Symm.test_symm_wrong_uplo().
t_max
scipy.integrate._ivp.base.DenseOutput.t_max = max(t, t_old)
Definition at line 249 of file base.py.
t_min
scipy.integrate._ivp.base.DenseOutput.t_min = min(t, t_old)
Definition at line 248 of file base.py.
t_old
scipy.integrate._ivp.base.DenseOutput.t_old = t_old
Definition at line 246 of file base.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/integrate/_ivp/base.py