Code Cloning Analysis: fontTools.ttLib.ttGlyphSet._TTGlyphSetVARC Class Reference
fontTools.ttLib.ttGlyphSet._TTGlyphSetVARC Class Reference
Public Member Functions
__init__ (self, font, location, glyphSet)
__getitem__ (self, glyphName)
Public Member Functions inherited from fontTools.ttLib.ttGlyphSet._TTGlyphSet
__init__ (self, font, location, glyphsMapping, *, recalcBounds=True)
pushLocation (self, location, bool reset)
pushDepth (self)
__contains__ (self, glyphName)
__iter__ (self)
__len__ (self)
has_key (self, glyphName)
Public Attributes
glyphSet = glyphSet
varcTable = font["VARC"].table
Public Attributes inherited from fontTools.ttLib.ttGlyphSet._TTGlyphSet
recalcBounds = recalcBounds
font = font
tuple defaultLocationNormalized
list location = location if location is not None else {}
dict rawLocation = {}
originalLocation = location if location is not None else {}
int depth = 0
list locationStack = []
list rawLocationStack = []
glyphsMapping = glyphsMapping
hMetrics = font["hmtx"].metrics
vMetrics = getattr(font.get("vmtx"), "metrics", None)
hvarTable = None
hvarInstancer
Detailed Description
Definition at line 143 of file ttGlyphSet.py.
Constructor & Destructor Documentation
__init__()
fontTools.ttLib.ttGlyphSet._TTGlyphSetVARC.__init__ (self, font, location, glyphSet)
Definition at line 144 of file ttGlyphSet.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__getitem__()
fontTools.ttLib.ttGlyphSet._TTGlyphSetVARC.__getitem__ (self, glyphName)
Definition at line 149 of file ttGlyphSet.py.
Member Data Documentation
glyphSet
fontTools.ttLib.ttGlyphSet._TTGlyphSetVARC.glyphSet = glyphSet
Definition at line 145 of file ttGlyphSet.py.
Referenced by fontTools.ttLib.ttGlyphSet._TTGlyphVARC._draw(), fontTools.ttLib.ttGlyphSet._TTGlyphCFF.draw(), fontTools.ttLib.ttGlyphSet._TTGlyphGlyf.draw(), fontTools.ttLib.ttGlyphSet._TTGlyphGlyf.drawPoints(), and fontTools.ufoLib.glifLib.Glyph.drawPoints().
varcTable
fontTools.ttLib.ttGlyphSet._TTGlyphSetVARC.varcTable = font["VARC"].table
Definition at line 147 of file ttGlyphSet.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ttLib/ttGlyphSet.py