Code Cloning Analysis: matplotlib.axes._base._process_plot_var_args Class Reference
matplotlib.axes._base._process_plot_var_args Class Reference
Public Member Functions
__init__ (self, output='Line2D')
set_prop_cycle (self, cycler)
__call__ (self, axes, *args, data=None, return_kwargs=False, **kwargs)
get_next_color (self)
Public Attributes
str output = output
Protected Member Functions
_getdefaults (self, kw, ignore=frozenset())
_setdefaults (self, defaults, kw)
_make_line (self, axes, x, y, kw, kwargs)
_make_coordinates (self, axes, x, y, kw, kwargs)
_make_polygon (self, axes, x, y, kw, kwargs)
_plot_args (self, axes, tup, kwargs, *, return_kwargs=False, ambiguous_fmt_datakey=False)
Protected Attributes
int _idx = 0
list _cycler_items = [*cycler]
Detailed Description
Process variable length arguments to `~.Axes.plot`, to support ::
  plot(t, s)
  plot(t1, s1, t2, s2)
  plot(t1, s1, 'ko', t2, s2)
  plot(t1, s1, 'ko', t2, s2, 'r--', t3, e3)
an arbitrary number of *x*, *y*, *fmt* are allowed
Definition at line 204 of file _base.py.
Constructor & Destructor Documentation
__init__()
matplotlib.axes._base._process_plot_var_args.__init__ (self, output = 'Line2D')
Definition at line 216 of file _base.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__call__()
matplotlib.axes._base._process_plot_var_args.__call__ (self, axes, * args, data = None, return_kwargs = False, ** kwargs)
Definition at line 227 of file _base.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), scipy.interpolate._fitpack2.SphereBivariateSpline.ev(), matplotlib.ticker.Formatter.format_data(), and matplotlib.ticker.LogFormatter.format_data().
_getdefaults()
matplotlib.axes._base._process_plot_var_args._getdefaults (self, kw, ignore = frozenset()) protected
If some keys in the property cycle (excluding those in the set
*ignore*) are absent or set to None in the dict *kw*, return a copy
of the next entry in the property cycle, excluding keys in *ignore*.
Otherwise, don't advance the property cycle, and return an empty dict.
Definition at line 311 of file _base.py.
References _cycler_items, and _idx.
Referenced by _setdefaults().
_make_coordinates()
matplotlib.axes._base._process_plot_var_args._make_coordinates (self, axes, x, y, kw, kwargs) protected
Definition at line 341 of file _base.py.
Referenced by _plot_args().
_make_line()
matplotlib.axes._base._process_plot_var_args._make_line (self, axes, x, y, kw, kwargs) protected
Definition at line 335 of file _base.py.
Referenced by _plot_args().
_make_polygon()
matplotlib.axes._base._process_plot_var_args._make_polygon (self, axes, x, y, kw, kwargs) protected
Definition at line 346 of file _base.py.
Referenced by _plot_args().
_plot_args()
matplotlib.axes._base._process_plot_var_args._plot_args (self, axes, tup, kwargs, * , return_kwargs = False, ambiguous_fmt_datakey = False) protected
Process the arguments of ``plot([x], y, [fmt], **kwargs)`` calls.
This processes a single set of ([x], y, [fmt]) parameters; i.e. for
``plot(x, y, x2, y2)`` it will be called twice. Once for (x, y) and
once for (x2, y2).
x and y may be 2D and thus can still represent multiple datasets.
For multiple datasets, if the keyword argument *label* is a list, this
will unpack the list and assign the individual labels to the datasets.
Parameters
----------
tup : tuple
    A tuple of the positional parameters. This can be one of
    - (y,)
    - (x, y)
    - (y, fmt)
    - (x, y, fmt)
kwargs : dict
    The keyword arguments passed to ``plot()``.
return_kwargs : bool
    Whether to also return the effective keyword arguments after label
    unpacking as well.
ambiguous_fmt_datakey : bool
    Whether the format string in *tup* could also have been a
    misspelled data key.
Returns
-------
result
    If *return_kwargs* is false, a list of Artists representing the
    dataset(s).
    If *return_kwargs* is true, a list of (Artist, effective_kwargs)
    representing the dataset(s). See *return_kwargs*.
    The Artist is either `.Line2D` (if called from ``plot()``) or
    `.Polygon` otherwise.
Definition at line 396 of file _base.py.
References _make_coordinates(), _make_line(), _make_polygon(), matplotlib.axes._base._process_plot_format(), and output.
_setdefaults()
matplotlib.axes._base._process_plot_var_args._setdefaults (self, defaults, kw) protected
Add to the dict *kw* the entries in the dict *default* that are absent
or set to None in *kw*.
Definition at line 326 of file _base.py.
References _getdefaults(), and _setdefaults().
Referenced by _setdefaults().
get_next_color()
matplotlib.axes._base._process_plot_var_args.get_next_color (self)
Return the next color in the cycle.
Definition at line 302 of file _base.py.
References _cycler_items, and _idx.
set_prop_cycle()
matplotlib.axes._base._process_plot_var_args.set_prop_cycle (self, cycler)
Definition at line 221 of file _base.py.
Member Data Documentation
_cycler_items
list matplotlib.axes._base._process_plot_var_args._cycler_items = [*cycler] protected
Definition at line 225 of file _base.py.
Referenced by _getdefaults(), and get_next_color().
_idx
int matplotlib.axes._base._process_plot_var_args._idx = 0 protected
Definition at line 224 of file _base.py.
Referenced by sklearn.externals.array_api_extra._lib._at.at.__getitem__(), _getdefaults(), sklearn.externals.array_api_extra._lib._at.at._op(), and get_next_color().
output
str matplotlib.axes._base._process_plot_var_args.output = output
Definition at line 218 of file _base.py.
Referenced by matplotlib.backends.backend_pdf.PdfFile.__init__(), _plot_args(), matplotlib.backends.backend_pdf.PdfFile._soft_mask_state(), matplotlib.backends.backend_pdf.PdfFile.markerObject(), scipy.odr._odrpack.ODR.restart(), and scipy.odr._odrpack.ODR.run().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/axes/_base.py