Code Cloning Analysis: scipy.optimize._trustregion_constr.projections Namespace Reference
scipy.optimize._trustregion_constr.projections Namespace Reference
Functions
orthogonality (A, g)
normal_equation_projections (A, m, n, orth_tol, max_refin, tol)
augmented_system_projections (A, m, n, orth_tol, max_refin, tol)
qr_factorization_projections (A, m, n, orth_tol, max_refin, tol)
svd_factorization_projections (A, m, n, orth_tol, max_refin, tol)
projections (A, method=None, orth_tol=1e-12, max_refin=3, tol=1e-15)
Variables
bool sksparse_available = True
list __all__
Detailed Description
Basic linear factorizations needed by the solver.
Function Documentation
augmented_system_projections()
scipy.optimize._trustregion_constr.projections.augmented_system_projections (A, m, n, orth_tol, max_refin, tol)
Return linear operators for matrix A - ``AugmentedSystem``.
Definition at line 92 of file projections.py.
References orthogonality(), and svd_factorization_projections().
Referenced by projections().
normal_equation_projections()
scipy.optimize._trustregion_constr.projections.normal_equation_projections (A, m, n, orth_tol, max_refin, tol)
Return linear operators for matrix A using ``NormalEquation`` approach.
Definition at line 57 of file projections.py.
References orthogonality().
Referenced by projections().
orthogonality()
scipy.optimize._trustregion_constr.projections.orthogonality (A, g)
Measure orthogonality between a vector and the null space of a matrix.
Compute a measure of orthogonality between the null space
of the (possibly sparse) matrix ``A`` and a given vector ``g``.
The formula is a simplified (and cheaper) version of formula (3.13)
from [1]_.
``orth =  norm(A g, ord=2)/(norm(A, ord='fro')*norm(g, ord=2))``.
References
----------
.. [1] Gould, Nicholas IM, Mary E. Hribar, and Jorge Nocedal.
       "On the solution of equality constrained quadratic
        programming problems arising in optimization."
        SIAM Journal on Scientific Computing 23.4 (2001): 1376-1395.
Definition at line 22 of file projections.py.
Referenced by augmented_system_projections(), normal_equation_projections(), qr_factorization_projections(), and svd_factorization_projections().
projections()
scipy.optimize._trustregion_constr.projections.projections (A, method = None, orth_tol = 1e-12, max_refin = 3, tol = 1e-15)
Return three linear operators related with a given matrix A.
Parameters
----------
A : sparse matrix (or ndarray), shape (m, n)
    Matrix ``A`` used in the projection.
method : string, optional
    Method used for compute the given linear
    operators. Should be one of:
        - 'NormalEquation': The operators
           will be computed using the
           so-called normal equation approach
           explained in [1]_. In order to do
           so the Cholesky factorization of
           ``(A A.T)`` is computed. Exclusive
           for sparse matrices.
        - 'AugmentedSystem': The operators
           will be computed using the
           so-called augmented system approach
           explained in [1]_. Exclusive
           for sparse matrices.
        - 'QRFactorization': Compute projections
           using QR factorization. Exclusive for
           dense matrices.
        - 'SVDFactorization': Compute projections
           using SVD factorization. Exclusive for
           dense matrices.
orth_tol : float, optional
    Tolerance for iterative refinements.
max_refin : int, optional
    Maximum number of iterative refinements.
tol : float, optional
    Tolerance for singular values.
Returns
-------
Z : LinearOperator, shape (n, n)
    Null-space operator. For a given vector ``x``,
    the null space operator is equivalent to apply
    a projection matrix ``P = I - A.T inv(A A.T) A``
    to the vector. It can be shown that this is
    equivalent to project ``x`` into the null space
    of A.
LS : LinearOperator, shape (m, n)
    Least-squares operator. For a given vector ``x``,
    the least-squares operator is equivalent to apply a
    pseudoinverse matrix ``pinv(A.T) = inv(A A.T) A``
    to the vector. It can be shown that this vector
    ``pinv(A.T) x`` is the least_square solution to
    ``A.T y = x``.
Y : LinearOperator, shape (n, m)
    Row-space operator. For a given vector ``x``,
    the row-space operator is equivalent to apply a
    projection matrix ``Q = A.T inv(A A.T)``
    to the vector.  It can be shown that this
    vector ``y = Q x``  the minimum norm solution
    of ``A y = x``.
Notes
-----
Uses iterative refinements described in [1]
during the computation of ``Z`` in order to
cope with the possibility of large roundoff errors.
References
----------
.. [1] Gould, Nicholas IM, Mary E. Hribar, and Jorge Nocedal.
    "On the solution of equality constrained quadratic
    programming problems arising in optimization."
    SIAM Journal on Scientific Computing 23.4 (2001): 1376-1395.
Definition at line 289 of file projections.py.
References augmented_system_projections(), normal_equation_projections(), qr_factorization_projections(), and svd_factorization_projections().
qr_factorization_projections()
scipy.optimize._trustregion_constr.projections.qr_factorization_projections (A, m, n, orth_tol, max_refin, tol)
Return linear operators for matrix A using ``QRFactorization`` approach.
Definition at line 174 of file projections.py.
References orthogonality(), and svd_factorization_projections().
Referenced by projections().
svd_factorization_projections()
scipy.optimize._trustregion_constr.projections.svd_factorization_projections (A, m, n, orth_tol, max_refin, tol)
Return linear operators for matrix A using ``SVDFactorization`` approach.
Definition at line 235 of file projections.py.
References orthogonality().
Referenced by augmented_system_projections(), projections(), and qr_factorization_projections().
Variable Documentation
__all__
list scipy.optimize._trustregion_constr.projections.__all__ private
Initial value:
=  [
    'orthogonality',
    'projections',
]
Definition at line 16 of file projections.py.
sksparse_available
bool scipy.optimize._trustregion_constr.projections.sksparse_available = True
Definition at line 9 of file projections.py.