Code Cloning Analysis: pandas.util._print_versions Namespace Reference
pandas.util._print_versions Namespace Reference
Functions
str|None _get_commit_hash ()
dict[str, JSONSerializable] _get_sys_info ()
dict[str, JSONSerializable] _get_dependency_info ()
None show_versions (str|bool as_json=False)
Function Documentation
_get_commit_hash()
str | None pandas.util._print_versions._get_commit_hash () protected
Use vendored versioneer code to get git hash, which handles
git worktree correctly.
Definition at line 22 of file _print_versions.py.
Referenced by _get_sys_info().
_get_dependency_info()
dict[str, JSONSerializable] pandas.util._print_versions._get_dependency_info () protected
Returns dependency information as a JSON serializable dictionary.
Definition at line 62 of file _print_versions.py.
Referenced by show_versions().
_get_sys_info()
dict[str, JSONSerializable] pandas.util._print_versions._get_sys_info () protected
Returns system information as a JSON serializable dictionary.
Definition at line 40 of file _print_versions.py.
References _get_commit_hash().
Referenced by show_versions().
show_versions()
None pandas.util._print_versions.show_versions (str | bool as_json = False)
Provide useful information, important for bug reports.
It comprises info about hosting operation system, pandas version,
and versions of other installed relative packages.
Parameters
----------
as_json : str or bool, default False
    * If False, outputs info in a human readable form to the console.
    * If str, it will be considered as a path to a file.
      Info will be written to that file in JSON format.
    * If True, outputs info in JSON format to the console.
Examples
--------
>>> pd.show_versions()  # doctest: +SKIP
Your output may look something like this:
INSTALLED VERSIONS
------------------
commit           : 37ea63d540fd27274cad6585082c91b1283f963d
python           : 3.10.6.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.102.1-microsoft-standard-WSL2
Version          : #1 SMP Wed Mar 2 00:30:59 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8
pandas           : 2.0.1
numpy            : 1.24.3
...
Definition at line 95 of file _print_versions.py.
References _get_dependency_info(), and _get_sys_info().