Code Cloning Analysis: scipy.sparse.linalg._dsolve.tests.test_linsolve.TestSplu Class Reference
scipy.sparse.linalg._dsolve.tests.test_linsolve.TestSplu Class Reference
Public Member Functions
setup_method (self)
test_splu_smoketest (self)
test_spilu_smoketest (self)
test_spilu_drop_rule (self)
test_splu_nnz0 (self)
test_spilu_nnz0 (self)
test_splu_basic (self)
test_splu_perm (self)
test_natural_permc (self, splu_fun, rtol)
test_lu_refcount (self)
test_bad_inputs (self)
test_superlu_dlamch_i386_nan (self)
test_lu_attr (self)
test_threads_parallel (self)
Public Attributes
n = n
A = spdiags((d, 2*d, d[::-1]), (-3, 0, 5), n, n, format='csc')
Protected Member Functions
_smoketest (self, spxlu, check, dtype, idx_dtype)
_internal_test_splu_smoketest (self)
_internal_test_spilu_smoketest (self)
Detailed Description
Definition at line 441 of file test_linsolve.py.
Member Function Documentation
_internal_test_spilu_smoketest()
scipy.sparse.linalg._dsolve.tests.test_linsolve.TestSplu._internal_test_spilu_smoketest (self) protected
Definition at line 504 of file test_linsolve.py.
_internal_test_splu_smoketest()
scipy.sparse.linalg._dsolve.tests.test_linsolve.TestSplu._internal_test_splu_smoketest (self) protected
Definition at line 489 of file test_linsolve.py.
_smoketest()
scipy.sparse.linalg._dsolve.tests.test_linsolve.TestSplu._smoketest (self, spxlu, check, dtype, idx_dtype) protected
Definition at line 450 of file test_linsolve.py.
setup_method()
scipy.sparse.linalg._dsolve.tests.test_linsolve.TestSplu.setup_method (self)
Definition at line 442 of file test_linsolve.py.
test_bad_inputs()
scipy.sparse.linalg._dsolve.tests.test_linsolve.TestSplu.test_bad_inputs (self)
Definition at line 629 of file test_linsolve.py.
test_lu_attr()
scipy.sparse.linalg._dsolve.tests.test_linsolve.TestSplu.test_lu_attr (self)
Definition at line 665 of file test_linsolve.py.
test_lu_refcount()
scipy.sparse.linalg._dsolve.tests.test_linsolve.TestSplu.test_lu_refcount (self)
Definition at line 611 of file test_linsolve.py.
test_natural_permc()
scipy.sparse.linalg._dsolve.tests.test_linsolve.TestSplu.test_natural_permc (self, splu_fun, rtol)
Definition at line 586 of file test_linsolve.py.
test_spilu_drop_rule()
scipy.sparse.linalg._dsolve.tests.test_linsolve.TestSplu.test_spilu_drop_rule (self)
Definition at line 521 of file test_linsolve.py.
test_spilu_nnz0()
scipy.sparse.linalg._dsolve.tests.test_linsolve.TestSplu.test_spilu_nnz0 (self)
Definition at line 538 of file test_linsolve.py.
test_spilu_smoketest()
scipy.sparse.linalg._dsolve.tests.test_linsolve.TestSplu.test_spilu_smoketest (self)
Definition at line 501 of file test_linsolve.py.
test_splu_basic()
scipy.sparse.linalg._dsolve.tests.test_linsolve.TestSplu.test_splu_basic (self)
Definition at line 542 of file test_linsolve.py.
test_splu_nnz0()
scipy.sparse.linalg._dsolve.tests.test_linsolve.TestSplu.test_splu_nnz0 (self)
Definition at line 534 of file test_linsolve.py.
test_splu_perm()
scipy.sparse.linalg._dsolve.tests.test_linsolve.TestSplu.test_splu_perm (self)
Definition at line 562 of file test_linsolve.py.
test_splu_smoketest()
scipy.sparse.linalg._dsolve.tests.test_linsolve.TestSplu.test_splu_smoketest (self)
Definition at line 486 of file test_linsolve.py.
test_superlu_dlamch_i386_nan()
scipy.sparse.linalg._dsolve.tests.test_linsolve.TestSplu.test_superlu_dlamch_i386_nan (self)
Definition at line 648 of file test_linsolve.py.
test_threads_parallel()
scipy.sparse.linalg._dsolve.tests.test_linsolve.TestSplu.test_threads_parallel (self)
Definition at line 701 of file test_linsolve.py.
Member Data Documentation
A
scipy.sparse.linalg._dsolve.tests.test_linsolve.TestSplu.A = spdiags((d, 2*d, d[::-1]), (-3, 0, 5), n, n, format='csc')
Definition at line 447 of file test_linsolve.py.
Referenced by scipy.sparse.linalg._matfuncs._ExpmPadeHelper.__init__(), scipy.sparse.linalg.tests.test_onenormest.MatrixProductOperator._matmat(), scipy.sparse.linalg._eigen.tests.test_svds.CheckingLinearOperator._matvec(), scipy.sparse.linalg.tests.test_onenormest.MatrixProductOperator._matvec(), scipy.sparse.linalg._eigen.tests.test_svds.CheckingLinearOperator._rmatvec(), and scipy.sparse.linalg.tests.test_onenormest.MatrixProductOperator._rmatvec().
n
scipy.sparse.linalg._dsolve.tests.test_linsolve.TestSplu.n = n
Definition at line 446 of file test_linsolve.py.
Referenced by scipy.stats._morestats._ABW.__init__(), scipy.stats._morestats._ABW._recalc(), scipy.stats._kde.gaussian_kde.integrate_kde(), scipy.stats._kde.gaussian_kde.marginal(), scipy.stats._binomtest.BinomTestResult.proportion_ci(), and scipy.stats._kde.gaussian_kde.resample().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/sparse/linalg/_dsolve/tests/test_linsolve.py