Code Cloning Analysis: numpy.testing.tests.test_utils.TestArrayEqual Class Reference
numpy.testing.tests.test_utils.TestArrayEqual Class Reference
Public Member Functions
setup_method (self)
test_generic_rank1 (self)
test_0_ndim_array (self)
test_generic_rank3 (self)
test_nan_array (self)
test_string_arrays (self)
test_recarrays (self)
test_masked_nan_inf (self)
test_subclass_that_overrides_eq (self)
test_subclass_that_does_not_implement_npall (self)
test_suppress_overflow_warnings (self)
test_array_vs_scalar_is_equal (self)
test_array_vs_scalar_not_equal (self)
test_array_vs_scalar_strict (self)
test_array_vs_array_strict (self)
test_array_vs_float_array_strict (self)
Public Member Functions inherited from numpy.testing.tests.test_utils._GenericTest
test_array_rank1_eq (self)
test_array_rank1_noteq (self)
test_array_rank2_eq (self)
test_array_diffshape (self)
test_objarray (self)
test_array_likes (self)
Protected Attributes
_assert_func = assert_array_equal
Additional Inherited Members
Protected Member Functions inherited from numpy.testing.tests.test_utils._GenericTest
_test_equal (self, a, b)
_test_not_equal (self, a, b)
Detailed Description
Definition at line 65 of file test_utils.py.
Member Function Documentation
setup_method()
numpy.testing.tests.test_utils.TestArrayEqual.setup_method (self)
Definition at line 67 of file test_utils.py.
test_0_ndim_array()
numpy.testing.tests.test_utils.TestArrayEqual.test_0_ndim_array (self)
Definition at line 89 of file test_utils.py.
test_array_vs_array_strict()
numpy.testing.tests.test_utils.TestArrayEqual.test_array_vs_array_strict (self)
Test comparing two arrays with strict option.
Definition at line 236 of file test_utils.py.
References numpy.testing._private.utils.assert_array_equal().
test_array_vs_float_array_strict()
numpy.testing.tests.test_utils.TestArrayEqual.test_array_vs_float_array_strict (self)
Test comparing two arrays with strict option.
Definition at line 243 of file test_utils.py.
References numpy.testing._private.utils.assert_array_equal().
test_array_vs_scalar_is_equal()
numpy.testing.tests.test_utils.TestArrayEqual.test_array_vs_scalar_is_equal (self)
Test comparing an array with a scalar when all values are equal.
Definition at line 214 of file test_utils.py.
References numpy.testing.tests.test_utils._GenericTest._test_equal().
test_array_vs_scalar_not_equal()
numpy.testing.tests.test_utils.TestArrayEqual.test_array_vs_scalar_not_equal (self)
Test comparing an array with a scalar when not all values equal.
Definition at line 221 of file test_utils.py.
References numpy.testing.tests.test_utils._GenericTest._test_not_equal().
test_array_vs_scalar_strict()
numpy.testing.tests.test_utils.TestArrayEqual.test_array_vs_scalar_strict (self)
Test comparing an array with a scalar with strict option.
Definition at line 228 of file test_utils.py.
References numpy.testing._private.utils.assert_array_equal().
test_generic_rank1()
numpy.testing.tests.test_utils.TestArrayEqual.test_generic_rank1 (self)
Test rank 1 array for all dtypes.
Definition at line 70 of file test_utils.py.
References _assert_func, numpy.testing.tests.test_utils._GenericTest._test_equal(), numpy.testing.tests.test_utils._GenericTest._test_not_equal(), and numpy.testing._private.utils.assert_raises().
test_generic_rank3()
numpy.testing.tests.test_utils.TestArrayEqual.test_generic_rank3 (self)
Test rank 3 array for all dtypes.
Definition at line 104 of file test_utils.py.
References numpy.testing.tests.test_utils._GenericTest._test_equal(), and numpy.testing.tests.test_utils._GenericTest._test_not_equal().
test_masked_nan_inf()
numpy.testing.tests.test_utils.TestArrayEqual.test_masked_nan_inf (self)
Definition at line 161 of file test_utils.py.
test_nan_array()
numpy.testing.tests.test_utils.TestArrayEqual.test_nan_array (self)
Test arrays with nan values in them.
Definition at line 123 of file test_utils.py.
References numpy.testing.tests.test_utils._GenericTest._test_equal(), and numpy.testing.tests.test_utils._GenericTest._test_not_equal().
test_recarrays()
numpy.testing.tests.test_utils.TestArrayEqual.test_recarrays (self)
Test record arrays.
Definition at line 144 of file test_utils.py.
References numpy.testing.tests.test_utils._GenericTest._test_equal(), numpy.testing.tests.test_utils._GenericTest._test_not_equal(), numpy.core.fromnumeric.all(), numpy.testing._private.utils.assert_(), and numpy.testing._private.utils.assert_raises().
test_string_arrays()
numpy.testing.tests.test_utils.TestArrayEqual.test_string_arrays (self)
Test two arrays with different shapes are found not equal.
Definition at line 133 of file test_utils.py.
References numpy.testing.tests.test_utils._GenericTest._test_equal(), and numpy.testing.tests.test_utils._GenericTest._test_not_equal().
test_subclass_that_does_not_implement_npall()
numpy.testing.tests.test_utils.TestArrayEqual.test_subclass_that_does_not_implement_npall (self)
Definition at line 193 of file test_utils.py.
test_subclass_that_overrides_eq()
numpy.testing.tests.test_utils.TestArrayEqual.test_subclass_that_overrides_eq (self)
Definition at line 172 of file test_utils.py.
test_suppress_overflow_warnings()
numpy.testing.tests.test_utils.TestArrayEqual.test_suppress_overflow_warnings (self)
Definition at line 206 of file test_utils.py.
Member Data Documentation
_assert_func
numpy.testing.tests.test_utils.TestArrayEqual._assert_func = assert_array_equal protected
Definition at line 68 of file test_utils.py.
Referenced by numpy.testing.tests.test_utils.TestAlmostEqual.test_error_message(), numpy.testing.tests.test_utils.TestAlmostEqual.test_error_message_2(), and test_generic_rank1().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/testing/tests/test_utils.py