Code Cloning Analysis: axisartist.floating_axes.ExtremeFinderFixed Class Reference
axisartist.floating_axes.ExtremeFinderFixed Class Reference
Public Member Functions
__init__ (self, extremes)
__call__ (self, transform_xy, x1, y1, x2, y2)
Public Member Functions inherited from axisartist.grid_finder.ExtremeFinderSimple
__init__ (self, nx, ny)
__call__ (self, transform_xy, x1, y1, x2, y2)
Protected Attributes
_extremes = extremes
Additional Inherited Members
Public Attributes inherited from axisartist.grid_finder.ExtremeFinderSimple
nx = nx
ny = ny
Protected Member Functions inherited from axisartist.grid_finder.ExtremeFinderSimple
_add_pad (self, x_min, x_max, y_min, y_max)
Detailed Description
Definition at line 116 of file floating_axes.py.
Constructor & Destructor Documentation
__init__()
axisartist.floating_axes.ExtremeFinderFixed.__init__ (self, extremes)
This subclass always returns the same bounding box.
Parameters
----------
extremes : (float, float, float, float)
    The bounding box that this helper always returns.
Definition at line 119 of file floating_axes.py.
References _extremes.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__call__()
axisartist.floating_axes.ExtremeFinderFixed.__call__ (self, transform_xy, x1, y1, x2, y2)
Definition at line 130 of file floating_axes.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), and scipy.interpolate._fitpack2.SphereBivariateSpline.ev().
Member Data Documentation
_extremes
axisartist.floating_axes.ExtremeFinderFixed._extremes = extremes protected
Definition at line 128 of file floating_axes.py.
Referenced by __init__(), axisartist.grid_helper_curvelinear.FloatingAxisArtistHelper.__init__(), and axisartist.grid_helper_curvelinear.FloatingAxisArtistHelper.get_tick_iterators().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/mpl_toolkits/axisartist/floating_axes.py