Code Cloning Analysis: pandas.core.indexers.objects.BaseIndexer Class Reference
pandas.core.indexers.objects.BaseIndexer Class Reference
Public Member Functions
None __init__ (self, np.ndarray|None index_array=None, int window_size=0, **kwargs)
tuple[np.ndarray, np.ndarray] get_window_bounds (self, int num_values=0, int|None min_periods=None, bool|None center=None, str|None closed=None, int|None step=None)
Public Attributes
index_array = index_array
window_size = window_size
Detailed Description
Base class for window bounds calculations.
Examples
--------
>>> from pandas.api.indexers import BaseIndexer
>>> class CustomIndexer(BaseIndexer):
...     def get_window_bounds(self, num_values, min_periods, center, closed, step):
...         start = np.empty(num_values, dtype=np.int64)
...         end = np.empty(num_values, dtype=np.int64)
...         for i in range(num_values):
...             start[i] = i
...             end[i] = i + self.window_size
...         return start, end
>>> df = pd.DataFrame({"values": range(5)})
>>> indexer = CustomIndexer(window_size=2)
>>> df.rolling(indexer).sum()
    values
0   1.0
1   3.0
2   5.0
3   7.0
4   4.0
Definition at line 46 of file objects.py.
Constructor & Destructor Documentation
__init__()
None pandas.core.indexers.objects.BaseIndexer.__init__ (self, np.ndarray | None index_array = None, int window_size = 0, ** kwargs)
Definition at line 72 of file objects.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
get_window_bounds()
tuple[np.ndarray, np.ndarray] pandas.core.indexers.objects.BaseIndexer.get_window_bounds (self, int num_values = 0, int | None min_periods = None, bool | None center = None, str | None closed = None, int | None step = None)
Definition at line 82 of file objects.py.
Member Data Documentation
index_array
pandas.core.indexers.objects.BaseIndexer.index_array = index_array
Definition at line 75 of file objects.py.
Referenced by pandas.core.indexers.objects.GroupbyIndexer.__init__().
window_size
pandas.core.indexers.objects.BaseIndexer.window_size = window_size
Definition at line 76 of file objects.py.
Referenced by pandas.core.indexers.objects.GroupbyIndexer.__init__().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/core/indexers/objects.py