Code Cloning Analysis: numpy.ma.tests.test_mrecords.TestMRecords Class Reference
numpy.ma.tests.test_mrecords.TestMRecords Class Reference
Public Member Functions
test_byview (self)
test_get (self)
test_set_fields (self)
test_set_fields_mask (self)
test_set_mask (self)
test_set_mask_fromarray (self)
test_set_mask_fromfields (self)
test_set_elements (self)
test_setslices_hardmask (self)
test_hardmask (self)
test_pickling (self)
test_filled (self)
test_tolist (self)
test_withnames (self)
test_exotic_formats (self)
Static Public Attributes
list ilist = [1, 2, 3, 4, 5]
list flist = [1.1, 2.2, 3.3, 4.4, 5.5]
list slist = [b'one', b'two', b'three', b'four', b'five']
list ddtype = [('a', int), ('b', float), ('c', '|S8')]
list mask = [0, 1, 0, 0, 1]
base = ma.array(list(zip(ilist, flist, slist)), mask=mask, dtype=ddtype)
Detailed Description
Definition at line 27 of file test_mrecords.py.
Member Function Documentation
test_byview()
numpy.ma.tests.test_mrecords.TestMRecords.test_byview (self)
Definition at line 36 of file test_mrecords.py.
test_exotic_formats()
numpy.ma.tests.test_mrecords.TestMRecords.test_exotic_formats (self)
Definition at line 329 of file test_mrecords.py.
test_filled()
numpy.ma.tests.test_mrecords.TestMRecords.test_filled (self)
Definition at line 295 of file test_mrecords.py.
test_get()
numpy.ma.tests.test_mrecords.TestMRecords.test_get (self)
Definition at line 48 of file test_mrecords.py.
test_hardmask()
numpy.ma.tests.test_mrecords.TestMRecords.test_hardmask (self)
Definition at line 266 of file test_mrecords.py.
test_pickling()
numpy.ma.tests.test_mrecords.TestMRecords.test_pickling (self)
Definition at line 283 of file test_mrecords.py.
test_set_elements()
numpy.ma.tests.test_mrecords.TestMRecords.test_set_elements (self)
Definition at line 205 of file test_mrecords.py.
test_set_fields()
numpy.ma.tests.test_mrecords.TestMRecords.test_set_fields (self)
Definition at line 88 of file test_mrecords.py.
test_set_fields_mask()
numpy.ma.tests.test_mrecords.TestMRecords.test_set_fields_mask (self)
Definition at line 143 of file test_mrecords.py.
test_set_mask()
numpy.ma.tests.test_mrecords.TestMRecords.test_set_mask (self)
Definition at line 158 of file test_mrecords.py.
test_set_mask_fromarray()
numpy.ma.tests.test_mrecords.TestMRecords.test_set_mask_fromarray (self)
Definition at line 174 of file test_mrecords.py.
test_set_mask_fromfields()
numpy.ma.tests.test_mrecords.TestMRecords.test_set_mask_fromfields (self)
Definition at line 188 of file test_mrecords.py.
test_setslices_hardmask()
numpy.ma.tests.test_mrecords.TestMRecords.test_setslices_hardmask (self)
Definition at line 237 of file test_mrecords.py.
test_tolist()
numpy.ma.tests.test_mrecords.TestMRecords.test_tolist (self)
Definition at line 310 of file test_mrecords.py.
test_withnames()
numpy.ma.tests.test_mrecords.TestMRecords.test_withnames (self)
Definition at line 323 of file test_mrecords.py.
Member Data Documentation
base
numpy.ma.tests.test_mrecords.TestMRecords.base = ma.array(list(zip(ilist, flist, slist)), mask=mask, dtype=ddtype) static
Definition at line 34 of file test_mrecords.py.
Referenced by pandas.plotting._matplotlib.converter.TimeSeries_DateLocator.__call__(), pip._internal.resolution.resolvelib.candidates.ExtrasCandidate.__init__(), pip._vendor.distlib.manifest.Manifest.__init__(), pip._vendor.distlib.util.Cache.__init__(), pip._internal.resolution.resolvelib.candidates.ExtrasCandidate._calculate_valid_requested_extras(), scipy.stats._qmc.Halton._initialize_permutations(), scipy.stats._qmc.Halton._random(), pip._vendor.distlib.manifest.Manifest._translate_pattern(), pip._internal.resolution.resolvelib.candidates.ExtrasCandidate._warn_invalid_extras(), pip._vendor.distlib.manifest.Manifest.add(), pip._vendor.distlib.util.Cache.clear(), pip._vendor.distlib.manifest.Manifest.findall(), pip._vendor.distlib.resources.ResourceCache.get(), pip._internal.resolution.resolvelib.candidates.ExtrasCandidate.name(), pip._internal.resolution.resolvelib.candidates.ExtrasCandidate.project_name(), and pip._vendor.distlib.manifest.Manifest.sorted().
ddtype
list numpy.ma.tests.test_mrecords.TestMRecords.ddtype = [('a', int), ('b', float), ('c', '|S8')] static
Definition at line 32 of file test_mrecords.py.
flist
list numpy.ma.tests.test_mrecords.TestMRecords.flist = [1.1, 2.2, 3.3, 4.4, 5.5] static
Definition at line 30 of file test_mrecords.py.
ilist
list numpy.ma.tests.test_mrecords.TestMRecords.ilist = [1, 2, 3, 4, 5] static
Definition at line 29 of file test_mrecords.py.
mask
list numpy.ma.tests.test_mrecords.TestMRecords.mask = [0, 1, 0, 0, 1] static
Definition at line 33 of file test_mrecords.py.
Referenced by pandas.core.series.Series.combine_first().
slist
list numpy.ma.tests.test_mrecords.TestMRecords.slist = [b'one', b'two', b'three', b'four', b'five'] static
Definition at line 31 of file test_mrecords.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/ma/tests/test_mrecords.py