Code Cloning Analysis: joblib.externals.cloudpickle.cloudpickle Namespace Reference
joblib.externals.cloudpickle.cloudpickle Namespace Reference
Classes
class _empty_cell_value
class Pickler
Functions
_get_or_create_tracker_id (class_def)
_lookup_class_or_track (class_tracker_id, class_def)
register_pickle_by_value (module)
unregister_pickle_by_value (module)
list_registry_pickle_by_value ()
_is_registered_pickle_by_value (module)
_getattribute (obj, name)
_whichmodule (obj, name)
_should_pickle_by_reference (obj, name=None)
_lookup_module_and_qualname (obj, name=None)
_extract_code_globals (co)
_find_imported_submodules (code, top_level_dependencies)
_builtin_type (name)
_walk_global_ops (code)
_extract_class_dict (cls)
is_tornado_coroutine (func)
subimport (name)
dynamic_subimport (name, vars)
_get_cell_contents (cell)
instance (cls)
_make_function (code, globals, name, argdefs, closure)
_make_empty_cell ()
_make_cell (value=_empty_cell_value)
_make_skeleton_class (type_constructor, name, bases, type_kwargs, class_tracker_id, extra)
_make_skeleton_enum (bases, name, qualname, members, module, class_tracker_id, extra)
_make_typevar (name, bound, constraints, covariant, contravariant, class_tracker_id)
_decompose_typevar (obj)
_typevar_reduce (obj)
_get_bases (typ)
_make_dict_keys (obj, is_ordered=False)
_make_dict_values (obj, is_ordered=False)
_make_dict_items (obj, is_ordered=False)
_class_getnewargs (obj)
_enum_getnewargs (obj)
_file_reconstructor (retval)
_function_getstate (func)
_class_getstate (obj)
_enum_getstate (obj)
_code_reduce (obj)
_cell_reduce (obj)
_classmethod_reduce (obj)
_file_reduce (obj)
_getset_descriptor_reduce (obj)
_mappingproxy_reduce (obj)
_memoryview_reduce (obj)
_module_reduce (obj)
_method_reduce (obj)
_logger_reduce (obj)
_root_logger_reduce (obj)
_property_reduce (obj)
_weakset_reduce (obj)
_dynamic_class_reduce (obj)
_class_reduce (obj)
_dict_keys_reduce (obj)
_dict_values_reduce (obj)
_dict_items_reduce (obj)
_odict_keys_reduce (obj)
_odict_values_reduce (obj)
_odict_items_reduce (obj)
_dataclass_field_base_reduce (obj)
_function_setstate (obj, state)
_class_setstate (obj, state)
_get_dataclass_field_type_sentinel (name)
dump (obj, file, protocol=None, buffer_callback=None)
dumps (obj, protocol=None, buffer_callback=None)
Variables
DEFAULT_PROTOCOL = pickle.HIGHEST_PROTOCOL
_PICKLE_BY_VALUE_MODULES = set()
_DYNAMIC_CLASS_TRACKER_BY_CLASS = weakref.WeakKeyDictionary()
_DYNAMIC_CLASS_TRACKER_BY_ID = weakref.WeakValueDictionary()
_DYNAMIC_CLASS_TRACKER_LOCK = threading.Lock()
str PYPY = "PyPy"
builtin_code_type = None
_extract_code_globals_cache = weakref.WeakKeyDictionary()
STORE_GLOBAL = opcode.opmap["STORE_GLOBAL"]
DELETE_GLOBAL = opcode.opmap["DELETE_GLOBAL"]
LOAD_GLOBAL = opcode.opmap["LOAD_GLOBAL"]
tuple GLOBAL_OPS = (STORE_GLOBAL, DELETE_GLOBAL, LOAD_GLOBAL)
HAVE_ARGUMENT = dis.HAVE_ARGUMENT
EXTENDED_ARG = dis.EXTENDED_ARG
dict _BUILTIN_TYPE_NAMES = {}
dict _DATACLASSE_FIELD_TYPE_SENTINELS
load
loads
CloudPickler = Pickler
__bases__ = {}
Detailed Description
Pickler class to extend the standard pickle.Pickler functionality
The main objective is to make it natural to perform distributed computing on
clusters (such as PySpark, Dask, Ray...) with interactively defined code
(functions, classes, ...) written in notebooks or console.
In particular this pickler adds the following features:
- serialize interactively-defined or locally-defined functions, classes,
  enums, typevars, lambdas and nested functions to compiled byte code;
- deal with some other non-serializable objects in an ad-hoc manner where
  applicable.
This pickler is therefore meant to be used for the communication between short
lived Python processes running the same version of Python and libraries. In
particular, it is not meant to be used for long term storage of Python objects.
It does not include an unpickler, as standard Python unpickling suffices.
This module was extracted from the `cloud` package, developed by `PiCloud, Inc.
<https://web.archive.org/web/20140626004012/http://www.picloud.com/>`_.
Copyright (c) 2012-now, CloudPickle developers and contributors.
Copyright (c) 2012, Regents of the University of California.
Copyright (c) 2009 `PiCloud, Inc. <https://web.archive.org/web/20140626004012/http://www.picloud.com/>`_.
All rights reserved.
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of the University of California, Berkeley nor the
      names of its contributors may be used to endorse or promote
      products derived from this software without specific prior written
      permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Function Documentation
_builtin_type()
joblib.externals.cloudpickle.cloudpickle._builtin_type (name) protected
Definition at line 402 of file cloudpickle.py.
_cell_reduce()
joblib.externals.cloudpickle.cloudpickle._cell_reduce (obj) protected
Cell (containing values of a function's free variables) reducer.
Definition at line 932 of file cloudpickle.py.
_class_getnewargs()
joblib.externals.cloudpickle.cloudpickle._class_getnewargs (obj) protected
Definition at line 665 of file cloudpickle.py.
_class_getstate()
joblib.externals.cloudpickle.cloudpickle._class_getstate (obj) protected
Definition at line 750 of file cloudpickle.py.
_class_reduce()
joblib.externals.cloudpickle.cloudpickle._class_reduce (obj) protected
Select the reducer depending on the dynamic nature of the class obj.
Definition at line 1063 of file cloudpickle.py.
References _dynamic_class_reduce(), and _should_pickle_by_reference().
Referenced by joblib.externals.cloudpickle.cloudpickle.Pickler.reducer_override().
_class_setstate()
joblib.externals.cloudpickle.cloudpickle._class_setstate (obj, state) protected
Definition at line 1158 of file cloudpickle.py.
_classmethod_reduce()
joblib.externals.cloudpickle.cloudpickle._classmethod_reduce (obj) protected
Definition at line 942 of file cloudpickle.py.
_code_reduce()
joblib.externals.cloudpickle.cloudpickle._code_reduce (obj) protected
code object reducer.
Definition at line 821 of file cloudpickle.py.
_dataclass_field_base_reduce()
joblib.externals.cloudpickle.cloudpickle._dataclass_field_base_reduce (obj) protected
Definition at line 1114 of file cloudpickle.py.
_decompose_typevar()
joblib.externals.cloudpickle.cloudpickle._decompose_typevar (obj) protected
Definition at line 602 of file cloudpickle.py.
_dict_items_reduce()
joblib.externals.cloudpickle.cloudpickle._dict_items_reduce (obj) protected
Definition at line 1092 of file cloudpickle.py.
_dict_keys_reduce()
joblib.externals.cloudpickle.cloudpickle._dict_keys_reduce (obj) protected
Definition at line 1078 of file cloudpickle.py.
_dict_values_reduce()
joblib.externals.cloudpickle.cloudpickle._dict_values_reduce (obj) protected
Definition at line 1085 of file cloudpickle.py.
_dynamic_class_reduce()
joblib.externals.cloudpickle.cloudpickle._dynamic_class_reduce (obj) protected
Save a class that can't be referenced as a module attribute.
This method is used to serialize classes that are defined inside
functions, or that otherwise can't be serialized as attribute lookups
from importable modules.
Definition at line 1036 of file cloudpickle.py.
Referenced by _class_reduce(), and joblib.externals.cloudpickle.cloudpickle.Pickler.save_global().
_enum_getnewargs()
joblib.externals.cloudpickle.cloudpickle._enum_getnewargs (obj) protected
Definition at line 684 of file cloudpickle.py.
_enum_getstate()
joblib.externals.cloudpickle.cloudpickle._enum_getstate (obj) protected
Definition at line 789 of file cloudpickle.py.
_extract_class_dict()
joblib.externals.cloudpickle.cloudpickle._extract_class_dict (cls) protected
Retrieve a copy of the dict of a class without the inherited method.
Definition at line 419 of file cloudpickle.py.
Referenced by _make_skeleton_enum().
_extract_code_globals()
joblib.externals.cloudpickle.cloudpickle._extract_code_globals (co) protected
Find all globals names read or written to by codeblock co.
Definition at line 313 of file cloudpickle.py.
References _extract_code_globals(), and _walk_global_ops().
Referenced by _extract_code_globals(), and _make_skeleton_enum().
_file_reconstructor()
joblib.externals.cloudpickle.cloudpickle._file_reconstructor (retval) protected
Definition at line 699 of file cloudpickle.py.
_file_reduce()
joblib.externals.cloudpickle.cloudpickle._file_reduce (obj) protected
Save a file.
Definition at line 947 of file cloudpickle.py.
References _should_pickle_by_reference().
_find_imported_submodules()
joblib.externals.cloudpickle.cloudpickle._find_imported_submodules (code, top_level_dependencies) protected
Find currently imported submodules used by a function.
Submodules used by a function need to be detected and referenced for the
function to work correctly at depickling time. Because submodules can be
referenced as attribute of their parent package (``package.submodule``), we
need a special introspection technique that does not rely on GLOBAL-related
opcodes to find references of them in a code object.
Example:
```
import concurrent.futures
import cloudpickle
def func():
    x = concurrent.futures.ThreadPoolExecutor
if __name__ == '__main__':
    cloudpickle.dumps(func)
```
The globals extracted by cloudpickle in the function's state include the
concurrent package, but not its submodule (here, concurrent.futures), which
is the module used by func. Find_imported_submodules will detect the usage
of concurrent.futures. Saving this module alongside with func will ensure
that calling func once depickled does not fail due to concurrent.futures
not being imported
Definition at line 338 of file cloudpickle.py.
Referenced by _make_skeleton_enum().
_function_getstate()
joblib.externals.cloudpickle.cloudpickle._function_getstate (func) protected
Definition at line 707 of file cloudpickle.py.
_function_setstate()
joblib.externals.cloudpickle.cloudpickle._function_setstate (obj, state) protected
Update the state of a dynamic function.
As __closure__ and __globals__ are readonly attributes of a function, we
cannot rely on the native setstate routine of pickle.load_build, that calls
setattr on items of the slotstate. Instead, we have to modify them inplace.
Definition at line 1124 of file cloudpickle.py.
_get_bases()
joblib.externals.cloudpickle.cloudpickle._get_bases (typ) protected
Definition at line 626 of file cloudpickle.py.
_get_cell_contents()
joblib.externals.cloudpickle.cloudpickle._get_cell_contents (cell) protected
Definition at line 480 of file cloudpickle.py.
_get_dataclass_field_type_sentinel()
joblib.externals.cloudpickle.cloudpickle._get_dataclass_field_type_sentinel (name) protected
Definition at line 1210 of file cloudpickle.py.
_get_or_create_tracker_id()
joblib.externals.cloudpickle.cloudpickle._get_or_create_tracker_id (class_def) protected
Definition at line 108 of file cloudpickle.py.
_getattribute()
joblib.externals.cloudpickle.cloudpickle._getattribute (obj, name) protected
Definition at line 196 of file cloudpickle.py.
_getset_descriptor_reduce()
joblib.externals.cloudpickle.cloudpickle._getset_descriptor_reduce (obj) protected
Definition at line 991 of file cloudpickle.py.
_is_registered_pickle_by_value()
joblib.externals.cloudpickle.cloudpickle._is_registered_pickle_by_value (module) protected
Definition at line 181 of file cloudpickle.py.
_logger_reduce()
joblib.externals.cloudpickle.cloudpickle._logger_reduce (obj) protected
Definition at line 1020 of file cloudpickle.py.
_lookup_class_or_track()
joblib.externals.cloudpickle.cloudpickle._lookup_class_or_track (class_tracker_id, class_def) protected
Definition at line 118 of file cloudpickle.py.
_lookup_module_and_qualname()
joblib.externals.cloudpickle.cloudpickle._lookup_module_and_qualname (obj, name = None) protected
Definition at line 273 of file cloudpickle.py.
_make_cell()
joblib.externals.cloudpickle.cloudpickle._make_cell (value = _empty_cell_value) protected
Definition at line 528 of file cloudpickle.py.
_make_dict_items()
joblib.externals.cloudpickle.cloudpickle._make_dict_items (obj, is_ordered = False) protected
Definition at line 654 of file cloudpickle.py.
_make_dict_keys()
joblib.externals.cloudpickle.cloudpickle._make_dict_keys (obj, is_ordered = False) protected
Definition at line 640 of file cloudpickle.py.
_make_dict_values()
joblib.externals.cloudpickle.cloudpickle._make_dict_values (obj, is_ordered = False) protected
Definition at line 647 of file cloudpickle.py.
_make_empty_cell()
joblib.externals.cloudpickle.cloudpickle._make_empty_cell () protected
Definition at line 519 of file cloudpickle.py.
_make_function()
joblib.externals.cloudpickle.cloudpickle._make_function (code, globals, name, argdefs, closure) protected
Definition at line 513 of file cloudpickle.py.
_make_skeleton_class()
joblib.externals.cloudpickle.cloudpickle._make_skeleton_class (type_constructor, name, bases, type_kwargs, class_tracker_id, extra) protected
Build dynamic class with an empty __dict__ to be filled once memoized
If class_tracker_id is not None, try to lookup an existing class definition
matching that id. If none is found, track a newly reconstructed class
definition under that id so that other instances stemming from the same
class id will also reuse this class definition.
The "extra" variable is meant to be a dict (or None) that can be used for
forward compatibility shall the need arise.
Definition at line 535 of file cloudpickle.py.
_make_skeleton_enum()
joblib.externals.cloudpickle.cloudpickle._make_skeleton_enum (bases, name, qualname, members, module, class_tracker_id, extra) protected
Build dynamic enum with an empty __dict__ to be filled once memoized
The creation of the enum class is inspired by the code of
EnumMeta._create_.
If class_tracker_id is not None, try to lookup an existing enum definition
matching that id. If none is found, track a newly reconstructed enum
definition under that id so that other instances stemming from the same
class id will also reuse this enum definition.
The "extra" variable is meant to be a dict (or None) that can be used for
forward compatibility shall the need arise.
Definition at line 560 of file cloudpickle.py.
References _extract_class_dict(), _extract_code_globals(), and _find_imported_submodules().
_make_typevar()
joblib.externals.cloudpickle.cloudpickle._make_typevar (name, bound, constraints, covariant, contravariant, class_tracker_id) protected
Definition at line 591 of file cloudpickle.py.
_mappingproxy_reduce()
joblib.externals.cloudpickle.cloudpickle._mappingproxy_reduce (obj) protected
Definition at line 995 of file cloudpickle.py.
_memoryview_reduce()
joblib.externals.cloudpickle.cloudpickle._memoryview_reduce (obj) protected
Definition at line 999 of file cloudpickle.py.
_method_reduce()
joblib.externals.cloudpickle.cloudpickle._method_reduce (obj) protected
Definition at line 1016 of file cloudpickle.py.
_module_reduce()
joblib.externals.cloudpickle.cloudpickle._module_reduce (obj) protected
Definition at line 1003 of file cloudpickle.py.
_odict_items_reduce()
joblib.externals.cloudpickle.cloudpickle._odict_items_reduce (obj) protected
Definition at line 1110 of file cloudpickle.py.
_odict_keys_reduce()
joblib.externals.cloudpickle.cloudpickle._odict_keys_reduce (obj) protected
Definition at line 1096 of file cloudpickle.py.
_odict_values_reduce()
joblib.externals.cloudpickle.cloudpickle._odict_values_reduce (obj) protected
Definition at line 1103 of file cloudpickle.py.
_property_reduce()
joblib.externals.cloudpickle.cloudpickle._property_reduce (obj) protected
Definition at line 1028 of file cloudpickle.py.
_root_logger_reduce()
joblib.externals.cloudpickle.cloudpickle._root_logger_reduce (obj) protected
Definition at line 1024 of file cloudpickle.py.
_should_pickle_by_reference()
joblib.externals.cloudpickle.cloudpickle._should_pickle_by_reference (obj, name = None) protected
Test whether an function or a class should be pickled by reference
Pickling by reference means by that the object (typically a function or a
class) is an attribute of a module that is assumed to be importable in the
target Python environment. Loading will therefore rely on importing the
module and then calling `getattr` on it to access the function or class.
Pickling by reference is the only option to pickle functions and classes
in the standard library. In cloudpickle the alternative option is to
pickle by value (for instance for interactively or locally defined
functions and classes or for attributes of modules that have been
explicitly registered to be pickled by value.
Definition at line 237 of file cloudpickle.py.
References _whichmodule().
Referenced by _class_reduce(), _file_reduce(), joblib.externals.cloudpickle.cloudpickle.Pickler._function_reduce(), joblib.externals.cloudpickle.cloudpickle.Pickler.save_function(), and joblib.externals.cloudpickle.cloudpickle.Pickler.save_global().
_typevar_reduce()
joblib.externals.cloudpickle.cloudpickle._typevar_reduce (obj) protected
Definition at line 613 of file cloudpickle.py.
_walk_global_ops()
joblib.externals.cloudpickle.cloudpickle._walk_global_ops (code) protected
Yield referenced name for global-referencing instructions in code.
Definition at line 411 of file cloudpickle.py.
Referenced by _extract_code_globals().
_weakset_reduce()
joblib.externals.cloudpickle.cloudpickle._weakset_reduce (obj) protected
Definition at line 1032 of file cloudpickle.py.
_whichmodule()
joblib.externals.cloudpickle.cloudpickle._whichmodule (obj, name) protected
Find the module an object belongs to.
This function differs from ``pickle.whichmodule`` in two ways:
- it does not mangle the cases where obj's module is __main__ and obj was
  not found in any module.
- Errors arising during module introspection are ignored, as those errors
  are considered unwanted side effects.
Definition at line 203 of file cloudpickle.py.
Referenced by _should_pickle_by_reference().
dump()
joblib.externals.cloudpickle.cloudpickle.dump (obj, file, protocol = None, buffer_callback = None)
Serialize obj as bytes streamed into file
protocol defaults to cloudpickle.DEFAULT_PROTOCOL which is an alias to
pickle.HIGHEST_PROTOCOL. This setting favors maximum communication
speed between processes running the same Python version.
Set protocol=pickle.DEFAULT_PROTOCOL instead if you need to ensure
compatibility with older versions of Python (although this is not always
guaranteed to work because cloudpickle relies on some internal
implementation details that can change from one Python version to the
next).
Definition at line 1506 of file cloudpickle.py.
References dump().
Referenced by dump().
dumps()
joblib.externals.cloudpickle.cloudpickle.dumps (obj, protocol = None, buffer_callback = None)
Serialize obj as a string of bytes allocated in memory
protocol defaults to cloudpickle.DEFAULT_PROTOCOL which is an alias to
pickle.HIGHEST_PROTOCOL. This setting favors maximum communication
speed between processes running the same Python version.
Set protocol=pickle.DEFAULT_PROTOCOL instead if you need to ensure
compatibility with older versions of Python (although this is not always
guaranteed to work because cloudpickle relies on some internal
implementation details that can change from one Python version to the
next).
Definition at line 1522 of file cloudpickle.py.
dynamic_subimport()
joblib.externals.cloudpickle.cloudpickle.dynamic_subimport (name, vars)
Definition at line 473 of file cloudpickle.py.
instance()
joblib.externals.cloudpickle.cloudpickle.instance (cls)
Create a new instance of a class.
Parameters
----------
cls : type
    The class to create an instance of.
Returns
-------
instance : cls
    A new instance of ``cls``.
Definition at line 488 of file cloudpickle.py.
is_tornado_coroutine()
joblib.externals.cloudpickle.cloudpickle.is_tornado_coroutine (func)
Return whether `func` is a Tornado coroutine function.
Running coroutines are not supported.
Definition at line 444 of file cloudpickle.py.
list_registry_pickle_by_value()
joblib.externals.cloudpickle.cloudpickle.list_registry_pickle_by_value ()
Definition at line 177 of file cloudpickle.py.
register_pickle_by_value()
joblib.externals.cloudpickle.cloudpickle.register_pickle_by_value (module)
Register a module to make its functions and classes picklable by value.
By default, functions and classes that are attributes of an importable
module are to be pickled by reference, that is relying on re-importing
the attribute from the module at load time.
If `register_pickle_by_value(module)` is called, all its functions and
classes are subsequently to be pickled by value, meaning that they can
be loaded in Python processes where the module is not importable.
This is especially useful when developing a module in a distributed
execution environment: restarting the client Python process with the new
source code is enough: there is no need to re-install the new version
of the module on all the worker nodes nor to restart the workers.
Note: this feature is considered experimental. See the cloudpickle
README.md file for more details and limitations.
Definition at line 128 of file cloudpickle.py.
subimport()
joblib.externals.cloudpickle.cloudpickle.subimport (name)
Definition at line 464 of file cloudpickle.py.
unregister_pickle_by_value()
joblib.externals.cloudpickle.cloudpickle.unregister_pickle_by_value (module)
Unregister that the input module should be pickled by value.
Definition at line 167 of file cloudpickle.py.
Variable Documentation
__bases__
joblib.externals.cloudpickle.cloudpickle.__bases__ = {} private
Definition at line 425 of file cloudpickle.py.
_BUILTIN_TYPE_NAMES
dict joblib.externals.cloudpickle.cloudpickle._BUILTIN_TYPE_NAMES = {} protected
Definition at line 396 of file cloudpickle.py.
_DATACLASSE_FIELD_TYPE_SENTINELS
dict joblib.externals.cloudpickle.cloudpickle._DATACLASSE_FIELD_TYPE_SENTINELS protected
Initial value:
=  {
    dataclasses._FIELD.name: dataclasses._FIELD,
    dataclasses._FIELD_CLASSVAR.name: dataclasses._FIELD_CLASSVAR,
    dataclasses._FIELD_INITVAR.name: dataclasses._FIELD_INITVAR,
}
Definition at line 1203 of file cloudpickle.py.
_DYNAMIC_CLASS_TRACKER_BY_CLASS
joblib.externals.cloudpickle.cloudpickle._DYNAMIC_CLASS_TRACKER_BY_CLASS = weakref.WeakKeyDictionary() protected
Definition at line 94 of file cloudpickle.py.
_DYNAMIC_CLASS_TRACKER_BY_ID
joblib.externals.cloudpickle.cloudpickle._DYNAMIC_CLASS_TRACKER_BY_ID = weakref.WeakValueDictionary() protected
Definition at line 95 of file cloudpickle.py.
_DYNAMIC_CLASS_TRACKER_LOCK
joblib.externals.cloudpickle.cloudpickle._DYNAMIC_CLASS_TRACKER_LOCK = threading.Lock() protected
Definition at line 96 of file cloudpickle.py.
_extract_code_globals_cache
joblib.externals.cloudpickle.cloudpickle._extract_code_globals_cache = weakref.WeakKeyDictionary() protected
Definition at line 105 of file cloudpickle.py.
_PICKLE_BY_VALUE_MODULES
joblib.externals.cloudpickle.cloudpickle._PICKLE_BY_VALUE_MODULES = set() protected
Definition at line 89 of file cloudpickle.py.
builtin_code_type
joblib.externals.cloudpickle.cloudpickle.builtin_code_type = None
Definition at line 100 of file cloudpickle.py.
CloudPickler
joblib.externals.cloudpickle.cloudpickle.CloudPickler = Pickler
Definition at line 1545 of file cloudpickle.py.
DEFAULT_PROTOCOL
joblib.externals.cloudpickle.cloudpickle.DEFAULT_PROTOCOL = pickle.HIGHEST_PROTOCOL
Definition at line 86 of file cloudpickle.py.
DELETE_GLOBAL
joblib.externals.cloudpickle.cloudpickle.DELETE_GLOBAL = opcode.opmap["DELETE_GLOBAL"]
Definition at line 389 of file cloudpickle.py.
EXTENDED_ARG
joblib.externals.cloudpickle.cloudpickle.EXTENDED_ARG = dis.EXTENDED_ARG
Definition at line 393 of file cloudpickle.py.
GLOBAL_OPS
tuple joblib.externals.cloudpickle.cloudpickle.GLOBAL_OPS = (STORE_GLOBAL, DELETE_GLOBAL, LOAD_GLOBAL)
Definition at line 391 of file cloudpickle.py.
HAVE_ARGUMENT
joblib.externals.cloudpickle.cloudpickle.HAVE_ARGUMENT = dis.HAVE_ARGUMENT
Definition at line 392 of file cloudpickle.py.
load
joblib.externals.cloudpickle.cloudpickle.load
Definition at line 1542 of file cloudpickle.py.
LOAD_GLOBAL
joblib.externals.cloudpickle.cloudpickle.LOAD_GLOBAL = opcode.opmap["LOAD_GLOBAL"]
Definition at line 390 of file cloudpickle.py.
loads
joblib.externals.cloudpickle.cloudpickle.loads
Definition at line 1542 of file cloudpickle.py.
PYPY
str joblib.externals.cloudpickle.cloudpickle.PYPY = "PyPy"
Definition at line 98 of file cloudpickle.py.
STORE_GLOBAL
joblib.externals.cloudpickle.cloudpickle.STORE_GLOBAL = opcode.opmap["STORE_GLOBAL"]
Definition at line 388 of file cloudpickle.py.