Code Cloning Analysis: pandas.core.computation.scope.Scope Class Reference
pandas.core.computation.scope.Scope Class Reference
Public Member Functions
None __init__ (self, int level, global_dict=None, local_dict=None, resolvers=(), target=None)
str __repr__ (self)
bool has_resolvers (self)
resolve (self, str key, bool is_local)
None swapkey (self, str old_key, str new_key, new_value=None)
str add_tmp (self, value)
int ntemps (self)
DeepChainMap full_scope (self)
Public Attributes
int level = level + 1
scope = DeepChainMap(DEFAULT_GLOBALS.copy())
target = target
resolvers = DeepChainMap(*resolvers)
dict temps = {}
has_resolvers
Protected Member Functions
None _get_vars (self, stack, list[str] scopes)
None _update (self, int level)
Static Private Attributes
list __slots__ = ["level", "scope", "target", "resolvers", "temps"]
Detailed Description
Object to hold scope, with a few bells to deal with some custom syntax
and contexts added by pandas.
Parameters
----------
level : int
global_dict : dict or None, optional, default None
local_dict : dict or Scope or None, optional, default None
resolvers : list-like or None, optional, default None
target : object
Attributes
----------
level : int
scope : DeepChainMap
target : object
temps : dict
Definition at line 121 of file scope.py.
Constructor & Destructor Documentation
__init__()
None pandas.core.computation.scope.Scope.__init__ (self, int level, global_dict = None, local_dict = None, resolvers = (), target = None)
Definition at line 148 of file scope.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__repr__()
str pandas.core.computation.scope.Scope.__repr__ (self)
Definition at line 188 of file scope.py.
_get_vars()
None pandas.core.computation.scope.Scope._get_vars (self, stack, list[str] scopes) protected
Get specifically scoped variables from a list of stack frames.
Parameters
----------
stack : list
    A list of stack frames as returned by ``inspect.stack()``
scopes : sequence of strings
    A sequence containing valid stack frame attribute names that
    evaluate to a dictionary. For example, ('locals', 'globals')
Definition at line 271 of file scope.py.
References scope.
Referenced by _update().
_update()
None pandas.core.computation.scope.Scope._update (self, int level) protected
Update the current scope by going back `level` levels.
Parameters
----------
level : int
Definition at line 294 of file scope.py.
References _get_vars().
add_tmp()
str pandas.core.computation.scope.Scope.add_tmp (self, value)
Add a temporary variable to the scope.
Parameters
----------
value : object
    An arbitrary object to be assigned to a temporary variable.
Returns
-------
str
    The name of the temporary variable created.
Definition at line 314 of file scope.py.
References temps.
full_scope()
DeepChainMap pandas.core.computation.scope.Scope.full_scope (self)
Return the full scope for use with passing to engines transparently
as a mapping.
Returns
-------
vars : DeepChainMap
    All variables in this scope.
Definition at line 344 of file scope.py.
References resolvers, scope, and temps.
has_resolvers()
bool pandas.core.computation.scope.Scope.has_resolvers (self)
Return whether we have any extra scope.
For example, DataFrames pass Their columns as resolvers during calls to
``DataFrame.eval()`` and ``DataFrame.query()``.
Returns
-------
hr : bool
Definition at line 194 of file scope.py.
References resolvers.
ntemps()
int pandas.core.computation.scope.Scope.ntemps (self)
The number of temporary variables in this scope
Definition at line 339 of file scope.py.
References temps.
resolve()
pandas.core.computation.scope.Scope.resolve (self, str key, bool is_local)
Resolve a variable name in a possibly local context.
Parameters
----------
key : str
    A variable name
is_local : bool
    Flag indicating whether the variable is local or not (prefixed with
    the '@' symbol)
Returns
-------
value : object
    The value of a particular variable
Definition at line 207 of file scope.py.
References has_resolvers, resolvers, scope, and temps.
Referenced by pip._vendor.distlib.compat.BaseConfigurator.configure_custom(), and pip._vendor.distlib.compat.BaseConfigurator.ext_convert().
swapkey()
None pandas.core.computation.scope.Scope.swapkey (self, str old_key, str new_key, new_value = None)
Replace a variable name, with a potentially new value.
Parameters
----------
old_key : str
    Current variable name to replace
new_key : str
    New variable name to replace `old_key` with
new_value : object
    Value to be replaced along with the possible renaming
Definition at line 246 of file scope.py.
References has_resolvers, resolvers, scope, and temps.
Member Data Documentation
__slots__
list pandas.core.computation.scope.Scope.__slots__ = ["level", "scope", "target", "resolvers", "temps"] static private
Definition at line 142 of file scope.py.
has_resolvers
pandas.core.computation.scope.Scope.has_resolvers
Definition at line 230 of file scope.py.
Referenced by resolve(), and swapkey().
level
int pandas.core.computation.scope.Scope.level = level + 1
Definition at line 151 of file scope.py.
Referenced by pandas.core.groupby.groupby.BaseGroupBy.__iter__(), pandas.core.groupby.grouper.Grouper._get_grouper(), pandas.core.groupby.generic.DataFrameGroupBy._gotitem(), pandas.core.groupby.grouper.Grouping._ilevel(), pandas.core.groupby.grouper.Grouper._set_grouper(), and pandas.core.groupby.groupby.BaseGroupBy.get_group().
resolvers
pandas.core.computation.scope.Scope.resolvers = DeepChainMap(*resolvers)
Definition at line 185 of file scope.py.
Referenced by full_scope(), has_resolvers(), resolve(), and swapkey().
scope
pandas.core.computation.scope.Scope.scope = DeepChainMap(DEFAULT_GLOBALS.copy())
Definition at line 155 of file scope.py.
Referenced by _get_vars(), full_scope(), resolve(), and swapkey().
target
pandas.core.computation.scope.Scope.target = target
Definition at line 156 of file scope.py.
temps
pandas.core.computation.scope.Scope.temps = {}
Definition at line 186 of file scope.py.
Referenced by add_tmp(), full_scope(), ntemps(), resolve(), and swapkey().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/core/computation/scope.py