Code Cloning Analysis: scipy.stats.tests.test_hypotests.TestBarnardExact Class Reference
scipy.stats.tests.test_hypotests.TestBarnardExact Class Reference
Public Member Functions
test_precise (self, input_sample, expected)
test_pooled_param (self, input_sample, expected)
test_raises (self)
test_edge_cases (self, input_sample, expected)
test_row_or_col_zero (self, input_sample, expected)
test_less_greater (self, input_sample, expected, alternative)
Detailed Description
Some tests to show that barnard_exact() works correctly.
Definition at line 1023 of file test_hypotests.py.
Member Function Documentation
test_edge_cases()
scipy.stats.tests.test_hypotests.TestBarnardExact.test_edge_cases (self, input_sample, expected)
Definition at line 1116 of file test_hypotests.py.
test_less_greater()
scipy.stats.tests.test_hypotests.TestBarnardExact.test_less_greater (self, input_sample, expected, alternative)
"The expected values have been generated by R, using a resolution
for the nuisance parameter of 1e-6 :
```R
library(Barnard)
options(digits=10)
a = barnard.test(2, 7, 8, 2, dp=1e-6, pooled=TRUE)
a$p.value[1]
```
In this test, we are using the "one-sided" return value `a$p.value[1]`
to test our pvalue.
Definition at line 1144 of file test_hypotests.py.
References scipy.stats._hypotests.barnard_exact().
test_pooled_param()
scipy.stats.tests.test_hypotests.TestBarnardExact.test_pooled_param (self, input_sample, expected)
The expected values have been generated by R, using a resolution
for the nuisance parameter of 1e-6 :
```R
library(Barnard)
options(digits=10)
barnard.test(43, 40, 10, 39, dp=1e-6, pooled=FALSE)
```
Definition at line 1071 of file test_hypotests.py.
References scipy.stats._hypotests.barnard_exact().
test_precise()
scipy.stats.tests.test_hypotests.TestBarnardExact.test_precise (self, input_sample, expected)
The expected values have been generated by R, using a resolution
for the nuisance parameter of 1e-6 :
```R
library(Barnard)
options(digits=10)
barnard.test(43, 40, 10, 39, dp=1e-6, pooled=TRUE)
```
Definition at line 1042 of file test_hypotests.py.
References scipy.stats._hypotests.barnard_exact().
test_raises()
scipy.stats.tests.test_hypotests.TestBarnardExact.test_raises (self)
Definition at line 1084 of file test_hypotests.py.
test_row_or_col_zero()
scipy.stats.tests.test_hypotests.TestBarnardExact.test_row_or_col_zero (self, input_sample, expected)
Definition at line 1129 of file test_hypotests.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/stats/tests/test_hypotests.py