Code Cloning Analysis: fontTools.feaLib.ast.GlyphClassName Class Reference
fontTools.feaLib.ast.GlyphClassName Class Reference
Public Member Functions
__init__ (self, glyphclass, location=None)
glyphSet (self)
asFea (self, indent="")
Public Member Functions inherited from fontTools.feaLib.ast.Element
__init__ (self, location=None)
build (self, builder)
__str__ (self)
Public Attributes
glyphclass = glyphclass
Public Attributes inherited from fontTools.feaLib.ast.Element
location = location
Detailed Description
A glyph class name, such as ``@FRENCH_MARKS``. This must be instantiated
with a :class:`GlyphClassDefinition` object.
Definition at line 292 of file ast.py.
Constructor & Destructor Documentation
__init__()
fontTools.feaLib.ast.GlyphClassName.__init__ (self, glyphclass, location = None)
Definition at line 296 of file ast.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
asFea()
fontTools.feaLib.ast.GlyphClassName.asFea (self, indent = "")
Returns this element as a string of feature code. For block-type
elements (such as :class:`FeatureBlock`), the `indent` string is
added to the start of each line in the output.
Reimplemented from fontTools.feaLib.ast.Element.
Definition at line 305 of file ast.py.
References glyphclass.
glyphSet()
fontTools.feaLib.ast.GlyphClassName.glyphSet (self)
The glyphs in this class as a tuple of :class:`GlyphName` objects.
Definition at line 301 of file ast.py.
References glyphclass, and glyphSet().
Referenced by glyphSet().
Member Data Documentation
glyphclass
fontTools.feaLib.ast.GlyphClassName.glyphclass = glyphclass
Definition at line 299 of file ast.py.
Referenced by fontTools.feaLib.ast.CursivePosStatement.asFea(), asFea(), fontTools.feaLib.ast.CursivePosStatement.build(), and glyphSet().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/feaLib/ast.py