Code Cloning Analysis: pandas.core.dtypes.missing Namespace Reference
pandas.core.dtypes.missing Namespace Reference
Functions
bool isna (Scalar|Pattern obj)
npt.NDArray[np.bool_] isna (ArrayLike|Index|list obj)
NDFrameT isna (NDFrameT obj)
NDFrameT|npt.NDArray[np.bool_] isna (NDFrameT|ArrayLike|Index|list obj)
bool|npt.NDArray[np.bool_]|NDFrame isna (object obj)
_isna (obj, bool inf_as_na=False)
None _use_inf_as_na (key)
_isna_array (ArrayLike values, bool inf_as_na=False)
npt.NDArray[np.bool_] _isna_string_dtype (np.ndarray values, bool inf_as_na)
np.bool_ _has_record_inf_value (np.ndarray record_as_array)
npt.NDArray[np.bool_] _isna_recarray_dtype (np.rec.recarray values, bool inf_as_na)
bool notna (Scalar obj)
npt.NDArray[np.bool_] notna (ArrayLike|Index|list obj)
NDFrameT notna (NDFrameT obj)
NDFrameT|npt.NDArray[np.bool_] notna (NDFrameT|ArrayLike|Index|list obj)
bool|npt.NDArray[np.bool_]|NDFrame notna (object obj)
bool array_equivalent (left, right, bool strict_nan=False, bool dtype_equal=False)
bool _array_equivalent_float (np.ndarray left, np.ndarray right)
_array_equivalent_datetimelike (np.ndarray left, np.ndarray right)
_array_equivalent_object (np.ndarray left, np.ndarray right, bool strict_nan)
bool array_equals (ArrayLike left, ArrayLike right)
infer_fill_value (val)
ArrayLike construct_1d_array_from_inferred_fill_value (object value, int length)
np.ndarray maybe_fill (np.ndarray arr)
na_value_for_dtype (DtypeObj dtype, bool compat=True)
remove_na_arraylike (Series|Index|np.ndarray arr)
bool is_valid_na_for_dtype (obj, DtypeObj dtype)
bool isna_all (ArrayLike arr)
Variables
isposinf_scalar = libmissing.isposinf_scalar
isneginf_scalar = libmissing.isneginf_scalar
nan_checker = np.isnan
bool INF_AS_NA = False
_dtype_object = np.dtype("object")
_dtype_str = np.dtype(str)
bool isnull = isna
bool notnull = notna
Detailed Description
missing types & inference
Function Documentation
_array_equivalent_datetimelike()
pandas.core.dtypes.missing._array_equivalent_datetimelike (np.ndarray left, np.ndarray right) protected
Definition at line 560 of file missing.py.
_array_equivalent_float()
bool pandas.core.dtypes.missing._array_equivalent_float (np.ndarray left, np.ndarray right) protected
Definition at line 556 of file missing.py.
_array_equivalent_object()
pandas.core.dtypes.missing._array_equivalent_object (np.ndarray left, np.ndarray right, bool strict_nan) protected
Definition at line 564 of file missing.py.
_has_record_inf_value()
np.bool_ pandas.core.dtypes.missing._has_record_inf_value (np.ndarray record_as_array) protected
Definition at line 322 of file missing.py.
_isna()
pandas.core.dtypes.missing._isna (obj, bool inf_as_na = False) protected
Detect missing values, treating None, NaN or NA as null. Infinite
values will also be treated as null if inf_as_na is True.
Parameters
----------
obj: ndarray or object value
    Input array or scalar value.
inf_as_na: bool
    Whether to treat infinity as null.
Returns
-------
boolean ndarray or boolean
Definition at line 184 of file missing.py.
References _isna_array().
Referenced by isna().
_isna_array()
pandas.core.dtypes.missing._isna_array (ArrayLike values, bool inf_as_na = False) protected
Return an array indicating which values of the input array are NaN / NA.
Parameters
----------
obj: ndarray or ExtensionArray
    The input array whose elements are to be checked.
inf_as_na: bool
    Whether or not to treat infinite values as NA.
Returns
-------
array-like
    Array of boolean values denoting the NA status of each element.
Definition at line 261 of file missing.py.
References isna_all().
Referenced by _isna(), and isna_all().
_isna_recarray_dtype()
npt.NDArray[np.bool_] pandas.core.dtypes.missing._isna_recarray_dtype (np.rec.recarray values, bool inf_as_na) protected
Definition at line 335 of file missing.py.
_isna_string_dtype()
npt.NDArray[np.bool_] pandas.core.dtypes.missing._isna_string_dtype (np.ndarray values, bool inf_as_na) protected
Definition at line 305 of file missing.py.
_use_inf_as_na()
None pandas.core.dtypes.missing._use_inf_as_na (key) protected
Option change callback for na/inf behaviour.
Choose which replacement for numpy.isnan / -numpy.isfinite is used.
Parameters
----------
flag: bool
    True means treat None, NaN, INF, -INF as null (old way),
    False means None and NaN are null, but INF, -INF are not null
    (new way).
Notes
-----
This approach to setting global module values is discussed and
approved here:
* https://stackoverflow.com/questions/4859217/
  programmatically-creating-variables-in-python/4859312#4859312
Definition at line 230 of file missing.py.
array_equals()
bool pandas.core.dtypes.missing.array_equals (ArrayLike left, ArrayLike right)
ExtensionArray-compatible implementation of array_equivalent.
Definition at line 615 of file missing.py.
References array_equivalent().
array_equivalent()
bool pandas.core.dtypes.missing.array_equivalent (left, right, bool strict_nan = False, bool dtype_equal = False)
True if two arrays, left and right, have equal non-NaN elements, and NaNs
in corresponding locations.  False otherwise. It is assumed that left and
right are NumPy arrays of the same dtype. The behavior of this function
(particularly with respect to NaNs) is not defined if the dtypes are
different.
Parameters
----------
left, right : ndarrays
strict_nan : bool, default False
    If True, consider NaN and None to be different.
dtype_equal : bool, default False
    Whether `left` and `right` are known to have the same dtype
    according to `is_dtype_equal`. Some methods like `BlockManager.equals`.
    require that the dtypes match. Setting this to ``True`` can improve
    performance, but will give different results for arrays that are
    equal but different dtypes.
Returns
-------
b : bool
    Returns True if the arrays are equivalent.
Examples
--------
>>> array_equivalent(
...     np.array([1, 2, np.nan]),
...     np.array([1, 2, np.nan]))
True
>>> array_equivalent(
...     np.array([1, np.nan, 2]),
...     np.array([1, 2, np.nan]))
False
Definition at line 466 of file missing.py.
Referenced by array_equals().
construct_1d_array_from_inferred_fill_value()
ArrayLike pandas.core.dtypes.missing.construct_1d_array_from_inferred_fill_value (object value, int length)
Definition at line 650 of file missing.py.
infer_fill_value()
pandas.core.dtypes.missing.infer_fill_value (val)
infer the fill value for the nan/NaT from the provided
scalar/ndarray/list-like if we are a NaT, return the correct dtyped
element to provide proper block construction
Definition at line 627 of file missing.py.
is_valid_na_for_dtype()
bool pandas.core.dtypes.missing.is_valid_na_for_dtype (obj, DtypeObj dtype)
isna check that excludes incompatible dtypes
Parameters
----------
obj : object
dtype : np.datetime64, np.timedelta64, DatetimeTZDtype, or PeriodDtype
Returns
-------
bool
Definition at line 728 of file missing.py.
References is_valid_na_for_dtype().
Referenced by is_valid_na_for_dtype().
isna() [1/5]
npt.NDArray[np.bool_] pandas.core.dtypes.missing.isna (ArrayLike | Index | list obj)
Definition at line 79 of file missing.py.
isna() [2/5]
NDFrameT pandas.core.dtypes.missing.isna (NDFrameT obj)
Definition at line 86 of file missing.py.
isna() [3/5]
NDFrameT | npt.NDArray[np.bool_] pandas.core.dtypes.missing.isna (NDFrameT | ArrayLike | Index | list obj)
Definition at line 92 of file missing.py.
isna() [4/5]
bool | npt.NDArray[np.bool_] | NDFrame pandas.core.dtypes.missing.isna (object obj)
Detect missing values for an array-like object.
This function takes a scalar or array-like object and indicates
whether values are missing (``NaN`` in numeric arrays, ``None`` or ``NaN``
in object arrays, ``NaT`` in datetimelike).
Parameters
----------
obj : scalar or array-like
    Object to check for null or missing values.
Returns
-------
bool or array-like of bool
    For scalar input, returns a scalar boolean.
    For array input, returns an array of boolean indicating whether each
    corresponding element is missing.
See Also
--------
notna : Boolean inverse of pandas.isna.
Series.isna : Detect missing values in a Series.
DataFrame.isna : Detect missing values in a DataFrame.
Index.isna : Detect missing values in an Index.
Examples
--------
Scalar arguments (including strings) result in a scalar boolean.
>>> pd.isna('dog')
False
>>> pd.isna(pd.NA)
True
>>> pd.isna(np.nan)
True
ndarrays result in an ndarray of booleans.
>>> array = np.array([[1, np.nan, 3], [4, 5, np.nan]])
>>> array
array([[ 1., nan,  3.],
       [ 4.,  5., nan]])
>>> pd.isna(array)
array([[False,  True, False],
       [False, False,  True]])
For indexes, an ndarray of booleans is returned.
>>> index = pd.DatetimeIndex(["2017-07-05", "2017-07-06", None,
...                           "2017-07-08"])
>>> index
DatetimeIndex(['2017-07-05', '2017-07-06', 'NaT', '2017-07-08'],
              dtype='datetime64[ns]', freq=None)
>>> pd.isna(index)
array([False, False,  True, False])
For Series and DataFrame, the same type is returned, containing booleans.
>>> df = pd.DataFrame([['ant', 'bee', 'cat'], ['dog', None, 'fly']])
>>> df
     0     1    2
0  ant   bee  cat
1  dog  None  fly
>>> pd.isna(df)
       0      1      2
0  False  False  False
1  False   True  False
>>> pd.isna(df[1])
0    False
1     True
Name: 1, dtype: bool
Definition at line 97 of file missing.py.
References _isna().
isna() [5/5]
bool pandas.core.dtypes.missing.isna (Scalar | Pattern obj)
Definition at line 74 of file missing.py.
isna_all()
bool pandas.core.dtypes.missing.isna_all (ArrayLike arr)
Optimized equivalent to isna(arr).all()
Definition at line 779 of file missing.py.
References _isna_array().
Referenced by _isna_array().
maybe_fill()
np.ndarray pandas.core.dtypes.missing.maybe_fill (np.ndarray arr)
Fill numpy.ndarray with NaN, unless we have a integer or boolean dtype.
Definition at line 664 of file missing.py.
na_value_for_dtype()
pandas.core.dtypes.missing.na_value_for_dtype (DtypeObj dtype, bool compat = True)
Return a dtype compat na value
Parameters
----------
dtype : string / dtype
compat : bool, default True
Returns
-------
np.dtype or a pandas dtype
Examples
--------
>>> na_value_for_dtype(np.dtype('int64'))
0
>>> na_value_for_dtype(np.dtype('int64'), compat=False)
nan
>>> na_value_for_dtype(np.dtype('float64'))
nan
>>> na_value_for_dtype(np.dtype('bool'))
False
>>> na_value_for_dtype(np.dtype('datetime64[ns]'))
numpy.datetime64('NaT')
Definition at line 673 of file missing.py.
notna() [1/5]
npt.NDArray[np.bool_] pandas.core.dtypes.missing.notna (ArrayLike | Index | list obj)
Definition at line 358 of file missing.py.
notna() [2/5]
NDFrameT pandas.core.dtypes.missing.notna (NDFrameT obj)
Definition at line 365 of file missing.py.
notna() [3/5]
NDFrameT | npt.NDArray[np.bool_] pandas.core.dtypes.missing.notna (NDFrameT | ArrayLike | Index | list obj)
Definition at line 371 of file missing.py.
notna() [4/5]
bool | npt.NDArray[np.bool_] | NDFrame pandas.core.dtypes.missing.notna (object obj)
Detect non-missing values for an array-like object.
This function takes a scalar or array-like object and indicates
whether values are valid (not missing, which is ``NaN`` in numeric
arrays, ``None`` or ``NaN`` in object arrays, ``NaT`` in datetimelike).
Parameters
----------
obj : array-like or object value
    Object to check for *not* null or *non*-missing values.
Returns
-------
bool or array-like of bool
    For scalar input, returns a scalar boolean.
    For array input, returns an array of boolean indicating whether each
    corresponding element is valid.
See Also
--------
isna : Boolean inverse of pandas.notna.
Series.notna : Detect valid values in a Series.
DataFrame.notna : Detect valid values in a DataFrame.
Index.notna : Detect valid values in an Index.
Examples
--------
Scalar arguments (including strings) result in a scalar boolean.
>>> pd.notna('dog')
True
>>> pd.notna(pd.NA)
False
>>> pd.notna(np.nan)
False
ndarrays result in an ndarray of booleans.
>>> array = np.array([[1, np.nan, 3], [4, 5, np.nan]])
>>> array
array([[ 1., nan,  3.],
       [ 4.,  5., nan]])
>>> pd.notna(array)
array([[ True, False,  True],
       [ True,  True, False]])
For indexes, an ndarray of booleans is returned.
>>> index = pd.DatetimeIndex(["2017-07-05", "2017-07-06", None,
...                          "2017-07-08"])
>>> index
DatetimeIndex(['2017-07-05', '2017-07-06', 'NaT', '2017-07-08'],
              dtype='datetime64[ns]', freq=None)
>>> pd.notna(index)
array([ True,  True, False,  True])
For Series and DataFrame, the same type is returned, containing booleans.
>>> df = pd.DataFrame([['ant', 'bee', 'cat'], ['dog', None, 'fly']])
>>> df
     0     1    2
0  ant   bee  cat
1  dog  None  fly
>>> pd.notna(df)
      0      1     2
0  True   True  True
1  True  False  True
>>> pd.notna(df[1])
0     True
1    False
Name: 1, dtype: bool
Definition at line 376 of file missing.py.
notna() [5/5]
bool pandas.core.dtypes.missing.notna (Scalar obj)
Definition at line 353 of file missing.py.
remove_na_arraylike()
pandas.core.dtypes.missing.remove_na_arraylike (Series | Index | np.ndarray arr)
Return array-like containing only true/non-NaN values, possibly empty.
Definition at line 718 of file missing.py.
Variable Documentation
_dtype_object
pandas.core.dtypes.missing._dtype_object = np.dtype("object") protected
Definition at line 69 of file missing.py.
_dtype_str
pandas.core.dtypes.missing._dtype_str = np.dtype(str) protected
Definition at line 70 of file missing.py.
INF_AS_NA
bool pandas.core.dtypes.missing.INF_AS_NA = False
Definition at line 68 of file missing.py.
isneginf_scalar
pandas.core.dtypes.missing.isneginf_scalar = libmissing.isneginf_scalar
Definition at line 65 of file missing.py.
isnull
bool pandas.core.dtypes.missing.isnull = isna
Definition at line 181 of file missing.py.
isposinf_scalar
pandas.core.dtypes.missing.isposinf_scalar = libmissing.isposinf_scalar
Definition at line 64 of file missing.py.
nan_checker
pandas.core.dtypes.missing.nan_checker = np.isnan
Definition at line 67 of file missing.py.
notnull
bool pandas.core.dtypes.missing.notnull = notna
Definition at line 463 of file missing.py.