Code Cloning Analysis: fontTools.ttLib.tables.otConverters.ValueFormat Class Reference
fontTools.ttLib.tables.otConverters.ValueFormat Class Reference
Public Member Functions
__init__ (self, name, repeat, aux, tableClass=None, *, description="")
read (self, reader, font, tableDict)
write (self, writer, font, tableDict, format, repeatIndex=None)
Public Member Functions inherited from fontTools.ttLib.tables.otConverters.SimpleValue
xmlWrite (self, xmlWriter, font, value, name, attrs)
xmlRead (self, attrs, content, font)
Public Member Functions inherited from fontTools.ttLib.tables.otConverters.BaseConverter
__init__ (self, name, repeat, aux, tableClass=None, *, description="")
readArray (self, reader, font, tableDict, count)
getRecordSize (self, reader)
writeArray (self, writer, font, tableDict, values)
Optional[int] getVarIndexOffset (self)
Public Attributes
str which = "ValueFormat" + ("2" if name[-1] == "2" else "1")
Public Attributes inherited from fontTools.ttLib.tables.otConverters.BaseConverter
name = name
repeat = repeat
aux = aux
tableClass = tableClass
isCount
str isLookupType = "MorphType"
isPropagated
description = description
Static Public Attributes
int staticSize = 2
Static Public Attributes inherited from fontTools.ttLib.tables.otConverters.BaseConverter
varIndexBasePlusOffsetRE = re.compile(r"VarIndexBase\s*\+\s*(\d+)")
Additional Inherited Members
Static Public Member Functions inherited from fontTools.ttLib.tables.otConverters.IntValue
fromString (value)
Static Public Member Functions inherited from fontTools.ttLib.tables.otConverters.SimpleValue
toString (value)
Detailed Description
Definition at line 783 of file otConverters.py.
Constructor & Destructor Documentation
__init__()
fontTools.ttLib.tables.otConverters.ValueFormat.__init__ (self, name, repeat, aux, tableClass = None, * , description = "")
Definition at line 786 of file otConverters.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
read()
fontTools.ttLib.tables.otConverters.ValueFormat.read (self, reader, font, tableDict)
Read a value from the reader.
Reimplemented from fontTools.ttLib.tables.otConverters.BaseConverter.
Reimplemented in fontTools.ttLib.tables.otConverters.ValueRecord.
Definition at line 792 of file otConverters.py.
References which.
Referenced by pandas.io.parsers.python_parser.PythonParser.__init__(), pip._vendor.urllib3.util.ssltransport.SSLTransport.__init__(), pandas.io.sas.sas7bdat.SAS7BDATReader.column_types(), packaging._tokenizer.Tokenizer.consume(), pip._vendor.urllib3.response.HTTPResponse.drain_conn(), packaging._tokenizer.Tokenizer.expect(), pip._vendor.urllib3.response.HTTPResponse.from_httplib(), pandas.io.sas.sas_xport.XportReader.get_chunk(), packaging._tokenizer.Tokenizer.raise_syntax_error(), PIL.ContainerIO.ContainerIO.readline(), and pip._vendor.urllib3.response.HTTPResponse.stream().
write()
fontTools.ttLib.tables.otConverters.ValueFormat.write (self, writer, font, tableDict, value, repeatIndex = None)
Write a value to the writer.
Reimplemented from fontTools.ttLib.tables.otConverters.BaseConverter.
Reimplemented in fontTools.ttLib.tables.otConverters.ValueRecord.
Definition at line 797 of file otConverters.py.
References which.
Referenced by matplotlib.backends.backend_pdf.PdfFile.addGouraudTriangles(), matplotlib.backends.backend_pdf.PdfFile.close(), joblib.externals.cloudpickle.cloudpickle.Pickler.reducer_override(), scipy.io.matlab._mio5.VarWriter5.write_sparse(), pandas.io.formats.html.HTMLFormatter.write_th(), scipy.io.matlab._mio5.VarWriter5.write_top(), matplotlib.backends.backend_pdf.PdfFile.writeTrailer(), and matplotlib.backends.backend_pdf.PdfFile.writeXref().
Member Data Documentation
staticSize
int fontTools.ttLib.tables.otConverters.ValueFormat.staticSize = 2 static
Definition at line 784 of file otConverters.py.
Referenced by fontTools.ttLib.tables.otConverters.BaseConverter.readArray().
which
str fontTools.ttLib.tables.otConverters.ValueFormat.which = "ValueFormat" + ("2" if name[-1] == "2" else "1")
Definition at line 790 of file otConverters.py.
Referenced by read(), fontTools.ttLib.tables.otConverters.ValueRecord.read(), write(), and fontTools.ttLib.tables.otConverters.ValueRecord.write().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ttLib/tables/otConverters.py