Code Cloning Analysis: fontTools.varLib.iup Namespace Reference
fontTools.varLib.iup Namespace Reference
Functions
iup_segment (_PointSegment coords, _Point rc1, _Delta rd1, _Point rc2, _Delta rd2)
_DeltaSegment iup_contour (_DeltaOrNoneSegment deltas, _PointSegment coords)
_DeltaSegment iup_delta (_DeltaOrNoneSegment deltas, _PointSegment coords, _Endpoints ends)
can_iup_in_between (_DeltaSegment deltas, _PointSegment coords, Integral i, Integral j, Real tolerance)
set _iup_contour_bound_forced_set (_DeltaSegment deltas, _PointSegment coords, Real tolerance=0)
_iup_contour_optimize_dp (_DeltaSegment deltas, _PointSegment coords, forced=set(), Real tolerance=0, Integral lookback=None)
_rot_list (list l, int k)
_rot_set (set s, int k, int n)
_DeltaOrNoneSegment iup_contour_optimize (_DeltaSegment deltas, _PointSegment coords, Real tolerance=0.0)
_DeltaOrNoneSegment iup_delta_optimize (_DeltaSegment deltas, _PointSegment coords, _Endpoints ends, Real tolerance=0.0)
Variables
COMPILED = cython.compiled
_Point = Tuple[Real, Real]
_Delta = Tuple[Real, Real]
_PointSegment = Sequence[_Point]
_DeltaSegment = Sequence[_Delta]
_DeltaOrNone = Union[_Delta, None]
_DeltaOrNoneSegment = Sequence[_DeltaOrNone]
_Endpoints = Sequence[Integral]
int MAX_LOOKBACK = 8
Function Documentation
_iup_contour_bound_forced_set()
set fontTools.varLib.iup._iup_contour_bound_forced_set (_DeltaSegment deltas, _PointSegment coords, Real tolerance = 0) protected
The forced set is a conservative set of points on the contour that must be encoded
explicitly (ie. cannot be interpolated).  Calculating this set allows for significantly
speeding up the dynamic-programming, as well as resolve circularity in DP.
The set is precise; that is, if an index is in the returned set, then there is no way
that IUP can generate delta for that point, given `coords` and `deltas`.
Definition at line 212 of file iup.py.
Referenced by iup_contour_optimize().
_iup_contour_optimize_dp()
fontTools.varLib.iup._iup_contour_optimize_dp (_DeltaSegment deltas, _PointSegment coords, forced = set(), Real tolerance = 0, Integral lookback = None) protected
Straightforward Dynamic-Programming.  For each index i, find least-costly encoding of
points 0 to i where i is explicitly encoded.  We find this by considering all previous
explicit points j and check whether interpolation can fill points between j and i.
Note that solution always encodes last point explicitly.  Higher-level is responsible
for removing that restriction.
As major speedup, we stop looking further whenever we see a "forced" point.
Definition at line 302 of file iup.py.
References can_iup_in_between().
Referenced by iup_contour_optimize().
_rot_list()
fontTools.varLib.iup._rot_list (list l, int k) protected
Rotate list by k items forward.  Ie. item at position 0 will be
at position k in returned list.  Negative k is allowed.
Definition at line 346 of file iup.py.
Referenced by iup_contour_optimize().
_rot_set()
fontTools.varLib.iup._rot_set (set s, int k, int n) protected
Definition at line 356 of file iup.py.
can_iup_in_between()
fontTools.varLib.iup.can_iup_in_between (_DeltaSegment deltas, _PointSegment coords, Integral i, Integral j, Real tolerance)
Return true if the deltas for points at `i` and `j` (`i < j`) can be
successfully used to interpolate deltas for points in between them within
provided error tolerance.
Definition at line 181 of file iup.py.
References iup_segment().
Referenced by _iup_contour_optimize_dp().
iup_contour()
_DeltaSegment fontTools.varLib.iup.iup_contour (_DeltaOrNoneSegment deltas, _PointSegment coords)
For the contour given in `coords`, interpolate any missing
delta values in delta vector `deltas`.
Returns fully filled-out delta vector.
Definition at line 91 of file iup.py.
References iup_segment().
Referenced by iup_delta().
iup_contour_optimize()
_DeltaOrNoneSegment fontTools.varLib.iup.iup_contour_optimize (_DeltaSegment deltas, _PointSegment coords, Real tolerance = 0.0)
For contour with coordinates `coords`, optimize a set of delta
values `deltas` within error `tolerance`.
Returns delta vector that has most number of None items instead of
the input delta.
Definition at line 363 of file iup.py.
References _iup_contour_bound_forced_set(), _iup_contour_optimize_dp(), and _rot_list().
Referenced by iup_delta_optimize().
iup_delta()
_DeltaSegment fontTools.varLib.iup.iup_delta (_DeltaOrNoneSegment deltas, _PointSegment coords, _Endpoints ends)
For the outline given in `coords`, with contour endpoints given
in sorted increasing order in `ends`, interpolate any missing
delta values in delta vector `deltas`.
Returns fully filled-out delta vector.
Definition at line 143 of file iup.py.
References iup_contour().
iup_delta_optimize()
_DeltaOrNoneSegment fontTools.varLib.iup.iup_delta_optimize (_DeltaSegment deltas, _PointSegment coords, _Endpoints ends, Real tolerance = 0.0)
For the outline given in `coords`, with contour endpoints given
in sorted increasing order in `ends`, optimize a set of delta
values `deltas` within error `tolerance`.
Returns delta vector that has most number of None items instead of
the input delta.
Definition at line 464 of file iup.py.
References iup_contour_optimize().
iup_segment()
fontTools.varLib.iup.iup_segment (_PointSegment coords, _Point rc1, _Delta rd1, _Point rc2, _Delta rd2)
Given two reference coordinates `rc1` & `rc2` and their respective
delta vectors `rd1` & `rd2`, returns interpolated deltas for the set of
coordinates `coords`.
Definition at line 40 of file iup.py.
Referenced by can_iup_in_between(), and iup_contour().
Variable Documentation
_Delta
fontTools.varLib.iup._Delta = Tuple[Real, Real] protected
Definition at line 17 of file iup.py.
_DeltaOrNone
fontTools.varLib.iup._DeltaOrNone = Union[_Delta, None] protected
Definition at line 20 of file iup.py.
_DeltaOrNoneSegment
fontTools.varLib.iup._DeltaOrNoneSegment = Sequence[_DeltaOrNone] protected
Definition at line 21 of file iup.py.
_DeltaSegment
fontTools.varLib.iup._DeltaSegment = Sequence[_Delta] protected
Definition at line 19 of file iup.py.
_Endpoints
fontTools.varLib.iup._Endpoints = Sequence[Integral] protected
Definition at line 22 of file iup.py.
_Point
fontTools.varLib.iup._Point = Tuple[Real, Real] protected
Definition at line 16 of file iup.py.
_PointSegment
fontTools.varLib.iup._PointSegment = Sequence[_Point] protected
Definition at line 18 of file iup.py.
COMPILED
fontTools.varLib.iup.COMPILED = cython.compiled
Definition at line 6 of file iup.py.
MAX_LOOKBACK
int fontTools.varLib.iup.MAX_LOOKBACK = 8
Definition at line 25 of file iup.py.