Code Cloning Analysis: scipy._lib._testutils.PytestTester Class Reference
scipy._lib._testutils.PytestTester Class Reference
Public Member Functions
__init__ (self, module_name)
__call__ (self, label="fast", verbose=1, extra_argv=None, doctests=False, coverage=False, tests=None, parallel=None)
Public Attributes
module_name = module_name
Detailed Description
Run tests for this namespace
``scipy.test()`` runs tests for all of SciPy, with the default settings.
When used from a submodule (e.g., ``scipy.cluster.test()``, only the tests
for that namespace are run.
Parameters
----------
label : {'fast', 'full'}, optional
    Whether to run only the fast tests, or also those marked as slow.
    Default is 'fast'.
verbose : int, optional
    Test output verbosity. Default is 1.
extra_argv : list, optional
    Arguments to pass through to Pytest.
doctests : bool, optional
    Whether to run doctests or not. Default is False.
coverage : bool, optional
    Whether to run tests with code coverage measurements enabled.
    Default is False.
tests : list of str, optional
    List of module names to run tests for. By default, uses the module
    from which the ``test`` function is called.
parallel : int, optional
    Run tests in parallel with pytest-xdist, if number given is larger than
    1. Default is 1.
Definition at line 21 of file _testutils.py.
Constructor & Destructor Documentation
__init__()
scipy._lib._testutils.PytestTester.__init__ (self, module_name)
Definition at line 51 of file _testutils.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
__call__()
scipy._lib._testutils.PytestTester.__call__ (self, label = "fast", verbose = 1, extra_argv = None, doctests = False, coverage = False, tests = None, parallel = None)
Definition at line 54 of file _testutils.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), and scipy.interpolate._fitpack2.SphereBivariateSpline.ev().
Member Data Documentation
module_name
scipy._lib._testutils.PytestTester.module_name = module_name
Definition at line 52 of file _testutils.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/_lib/_testutils.py