Code Cloning Analysis: matplotlib.streamplot Namespace Reference
matplotlib.streamplot Namespace Reference
Classes
class DomainMap
class Grid
class InvalidIndexError
class OutOfBounds
class StreamMask
class StreamplotSet
class TerminateTrajectory
Functions
streamplot (axes, x, y, u, v, density=1, linewidth=None, color=None, cmap=None, norm=None, arrowsize=1, arrowstyle='-|>', minlength=0.1, transform=None, zorder=None, start_points=None, maxlength=4.0, integration_direction='both', broken_streamlines=True)
_get_integrator (u, v, dmap, minlength, maxlength, integration_direction)
_integrate_rk12 (x0, y0, dmap, f, maxlength, broken_streamlines=True)
_euler_step (xyf_traj, dmap, f)
interpgrid (a, xi, yi)
_gen_starting_points (shape)
Variables
list __all__ = ['streamplot']
Detailed Description
Streamline plotting for 2D vector fields.
Function Documentation
_euler_step()
matplotlib.streamplot._euler_step (xyf_traj, dmap, f) protected
Simple Euler integration step that extends streamline to boundary.
Definition at line 610 of file streamplot.py.
_gen_starting_points()
matplotlib.streamplot._gen_starting_points (shape) protected
Yield starting points for streamlines.
Trying points on the boundary first gives higher quality streamlines.
This algorithm starts with a point on the mask corner and spirals inward.
This algorithm is inefficient, but fast compared to rest of streamplot.
Definition at line 675 of file streamplot.py.
Referenced by streamplot().
_get_integrator()
matplotlib.streamplot._get_integrator (u, v, dmap, minlength, maxlength, integration_direction) protected
Definition at line 445 of file streamplot.py.
_integrate_rk12()
matplotlib.streamplot._integrate_rk12 (x0, y0, dmap, f, maxlength, broken_streamlines = True) protected
2nd-order Runge-Kutta algorithm with adaptive step size.
This method is also referred to as the improved Euler's method, or Heun's
method. This method is favored over higher-order methods because:
1. To get decent looking trajectories and to sample every mask cell
   on the trajectory we need a small timestep, so a lower order
   solver doesn't hurt us unless the data is *very* high resolution.
   In fact, for cases where the user inputs
   data smaller or of similar grid size to the mask grid, the higher
   order corrections are negligible because of the very fast linear
   interpolation used in `interpgrid`.
2. For high resolution input data (i.e. beyond the mask
   resolution), we must reduce the timestep. Therefore, an adaptive
   timestep is more suited to the problem as this would be very hard
   to judge automatically otherwise.
This integrator is about 1.5 - 2x as fast as RK4 and RK45 solvers (using
similar Python implementations) in most setups.
Definition at line 514 of file streamplot.py.
interpgrid()
matplotlib.streamplot.interpgrid (a, xi, yi)
Fast 2D, linear interpolation on an integer grid
Definition at line 635 of file streamplot.py.
Referenced by streamplot().
streamplot()
matplotlib.streamplot.streamplot (axes, x, y, u, v, density = 1, linewidth = None, color = None, cmap = None, norm = None, arrowsize = 1, arrowstyle = '-|>', minlength = 0.1, transform = None, zorder = None, start_points = None, maxlength = 4.0, integration_direction = 'both', broken_streamlines = True)
Draw streamlines of a vector flow.
Parameters
----------
x, y : 1D/2D arrays
    Evenly spaced strictly increasing arrays to make a grid.  If 2D, all
    rows of *x* must be equal and all columns of *y* must be equal; i.e.,
    they must be as if generated by ``np.meshgrid(x_1d, y_1d)``.
u, v : 2D arrays
    *x* and *y*-velocities. The number of rows and columns must match
    the length of *y* and *x*, respectively.
density : float or (float, float)
    Controls the closeness of streamlines. When ``density = 1``, the domain
    is divided into a 30x30 grid. *density* linearly scales this grid.
    Each cell in the grid can have, at most, one traversing streamline.
    For different densities in each direction, use a tuple
    (density_x, density_y).
linewidth : float or 2D array
    The width of the streamlines. With a 2D array the line width can be
    varied across the grid. The array must have the same shape as *u*
    and *v*.
color : :mpltype:`color` or 2D array
    The streamline color. If given an array, its values are converted to
    colors using *cmap* and *norm*.  The array must have the same shape
    as *u* and *v*.
cmap, norm
    Data normalization and colormapping parameters for *color*; only used
    if *color* is an array of floats. See `~.Axes.imshow` for a detailed
    description.
arrowsize : float
    Scaling factor for the arrow size.
arrowstyle : str
    Arrow style specification.
    See `~matplotlib.patches.FancyArrowPatch`.
minlength : float
    Minimum length of streamline in axes coordinates.
start_points : (N, 2) array
    Coordinates of starting points for the streamlines in data coordinates
    (the same coordinates as the *x* and *y* arrays).
zorder : float
    The zorder of the streamlines and arrows.
    Artists with lower zorder values are drawn first.
maxlength : float
    Maximum length of streamline in axes coordinates.
integration_direction : {'forward', 'backward', 'both'}, default: 'both'
    Integrate the streamline in forward, backward or both directions.
data : indexable object, optional
    DATA_PARAMETER_PLACEHOLDER
broken_streamlines : boolean, default: True
    If False, forces streamlines to continue until they
    leave the plot domain.  If True, they may be terminated if they
    come too close to another streamline.
Returns
-------
StreamplotSet
    Container object with attributes
    - ``lines``: `.LineCollection` of streamlines
    - ``arrows``: `.PatchCollection` containing `.FancyArrowPatch`
      objects representing the arrows half-way along streamlines.
    This container will probably change in the future to allow changes
    to the colormap, alpha, etc. for both lines and arrows, but these
    changes should be backward compatible.
Definition at line 18 of file streamplot.py.
References _gen_starting_points(), and interpgrid().
Variable Documentation
__all__
list matplotlib.streamplot.__all__ = ['streamplot'] private
Definition at line 15 of file streamplot.py.