Code Cloning Analysis: pandas.tests.indexes.datetimes.test_timezones.FixedOffset Class Reference
pandas.tests.indexes.datetimes.test_timezones.FixedOffset Class Reference
Public Member Functions
None __init__ (self, offset, name)
utcoffset (self, dt)
tzname (self, dt)
dst (self, dt)
Private Attributes
__offset = timedelta(minutes=offset)
__name = name
Detailed Description
Fixed offset in minutes east from UTC.
Definition at line 33 of file test_timezones.py.
Constructor & Destructor Documentation
__init__()
None pandas.tests.indexes.datetimes.test_timezones.FixedOffset.__init__ (self, offset, name)
Definition at line 36 of file test_timezones.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
dst()
pandas.tests.indexes.datetimes.test_timezones.FixedOffset.dst (self, dt)
Definition at line 46 of file test_timezones.py.
tzname()
pandas.tests.indexes.datetimes.test_timezones.FixedOffset.tzname (self, dt)
Definition at line 43 of file test_timezones.py.
utcoffset()
pandas.tests.indexes.datetimes.test_timezones.FixedOffset.utcoffset (self, dt)
Definition at line 40 of file test_timezones.py.
Member Data Documentation
__name
pandas.tests.indexes.datetimes.test_timezones.FixedOffset.__name = name private
Definition at line 38 of file test_timezones.py.
__offset
pandas.tests.indexes.datetimes.test_timezones.FixedOffset.__offset = timedelta(minutes=offset) private
Definition at line 37 of file test_timezones.py.
Referenced by PIL.FliImagePlugin.FliImageFile.seek(), PIL.GifImagePlugin.GifImageFile.seek(), and PIL.ImImagePlugin.ImImageFile.seek().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/tests/indexes/datetimes/test_timezones.py