Code Cloning Analysis: pandas.io.pytables.GenericIndexCol Class Reference
pandas.io.pytables.GenericIndexCol Class Reference
Public Member Functions
bool is_indexed (self)
tuple[Index, Index] convert (self, np.ndarray values, nan_rep, str encoding, str errors)
None set_attr (self)
Public Member Functions inherited from pandas.io.pytables.IndexCol
None __init__ (self, str name, values=None, kind=None, typ=None, str|None cname=None, axis=None, pos=None, freq=None, tz=None, index_name=None, ordered=None, table=None, meta=None, metadata=None)
int itemsize (self)
str kind_attr (self)
None set_pos (self, int pos)
str __repr__ (self)
bool __eq__ (self, object other)
bool __ne__ (self, other)
take_data (self)
attrs (self)
description (self)
col (self)
cvalues (self)
Iterator __iter__ (self)
None maybe_set_size (self, min_itemsize=None)
None validate_names (self)
None validate_and_set (self, AppendableTable handler, bool append)
validate_col (self, itemsize=None)
None validate_attr (self, bool append)
None update_info (self, info)
None set_info (self, info)
None validate_metadata (self, AppendableTable handler)
None write_metadata (self, AppendableTable handler)
Additional Inherited Members
Public Attributes inherited from pandas.io.pytables.IndexCol
values = values
kind = kind
typ = typ
name = name
cname = cname or name
axis = axis
pos = pos
freq = freq
tz = tz
index_name = index_name
ordered = ordered
table = table
str meta = meta
metadata = metadata
description
attrs
kind_attr
Static Public Attributes inherited from pandas.io.pytables.IndexCol
bool is_an_indexable = True
bool is_data_indexable = True
Static Protected Attributes inherited from pandas.io.pytables.IndexCol
list _info_fields = ["freq", "tz", "index_name"]
Detailed Description
an index which is not represented in the data of the table
Definition at line 2357 of file pytables.py.
Member Function Documentation
convert()
tuple[Index, Index] pandas.io.pytables.GenericIndexCol.convert (self, np.ndarray values, nan_rep, str encoding, str errors)
Convert the data from this selection to the appropriate pandas type.
Parameters
----------
values : np.ndarray
nan_rep : str
encoding : str
errors : str
Reimplemented from pandas.io.pytables.IndexCol.
Definition at line 2364 of file pytables.py.
Referenced by PIL.Image.Image.reduce(), PIL.Image.Image.resize(), and PIL.Image.Image.transform().
is_indexed()
bool pandas.io.pytables.GenericIndexCol.is_indexed (self)
return whether I am an indexed column
Reimplemented from pandas.io.pytables.IndexCol.
Definition at line 2361 of file pytables.py.
set_attr()
None pandas.io.pytables.GenericIndexCol.set_attr (self)
set the kind for this column
Reimplemented from pandas.io.pytables.IndexCol.
Definition at line 2382 of file pytables.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/io/pytables.py