Code Cloning Analysis: scipy.integrate._quad_vec.LRUDict Class Reference
scipy.integrate._quad_vec.LRUDict Class Reference
Public Member Functions
__init__ (self, max_size)
__setitem__ (self, key, value)
update (self, other)
Private Attributes
__max_size = max_size
Detailed Description
Definition at line 12 of file _quad_vec.py.
Constructor & Destructor Documentation
__init__()
scipy.integrate._quad_vec.LRUDict.__init__ (self, max_size)
Definition at line 13 of file _quad_vec.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
__setitem__()
scipy.integrate._quad_vec.LRUDict.__setitem__ (self, key, value)
Definition at line 16 of file _quad_vec.py.
update()
scipy.integrate._quad_vec.LRUDict.update (self, other)
Definition at line 24 of file _quad_vec.py.
Referenced by matplotlib.patches.Shadow.__init__(), matplotlib.backends.backend_macosx.FigureCanvasMac.blit(), matplotlib.backends.backend_macosx.FigureCanvasMac.draw(), and matplotlib.backends.backend_qt.FigureCanvasQT.draw().
Member Data Documentation
__max_size
scipy.integrate._quad_vec.LRUDict.__max_size = max_size private
Definition at line 14 of file _quad_vec.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/integrate/_quad_vec.py