Code Cloning Analysis: numpy.matrixlib.defmatrix Namespace Reference
numpy.matrixlib.defmatrix Namespace Reference
Classes
class matrix
Functions
_convert_from_string (data)
asmatrix (data, dtype=None)
_from_string (str, gdict, ldict)
bmat (obj, ldict=None, gdict=None)
Variables
list __all__ = ['matrix', 'bmat', 'mat', 'asmatrix']
mat = asmatrix
Function Documentation
_convert_from_string()
numpy.matrixlib.defmatrix._convert_from_string (data) protected
Definition at line 15 of file defmatrix.py.
_from_string()
numpy.matrixlib.defmatrix._from_string (str, gdict, ldict) protected
Definition at line 1011 of file defmatrix.py.
asmatrix()
numpy.matrixlib.defmatrix.asmatrix (data, dtype = None)
Interpret the input as a matrix.
Unlike `matrix`, `asmatrix` does not make a copy if the input is already
a matrix or an ndarray.  Equivalent to ``matrix(data, copy=False)``.
Parameters
----------
data : array_like
    Input data.
dtype : data-type
   Data-type of the output matrix.
Returns
-------
mat : matrix
    `data` interpreted as a matrix.
Examples
--------
>>> x = np.array([[1, 2], [3, 4]])
>>> m = np.asmatrix(x)
>>> x[0,0] = 5
>>> m
matrix([[5, 2],
        [3, 4]])
Definition at line 38 of file defmatrix.py.
Referenced by numpy.matlib.eye(), numpy.matrixlib.defmatrix.matrix.I(), numpy.matlib.rand(), numpy.matlib.randn(), and numpy.matrixlib.tests.test_defmatrix.TestProperties.test_sum().
bmat()
numpy.matrixlib.defmatrix.bmat (obj, ldict = None, gdict = None)
Build a matrix object from a string, nested sequence, or array.
Parameters
----------
obj : str or array_like
    Input data. If a string, variables in the current scope may be
    referenced by name.
ldict : dict, optional
    A dictionary that replaces local operands in current frame.
    Ignored if `obj` is not a string or `gdict` is None.
gdict : dict, optional
    A dictionary that replaces global operands in current frame.
    Ignored if `obj` is not a string.
Returns
-------
out : matrix
    Returns a matrix object, which is a specialized 2-D array.
See Also
--------
block :
    A generalization of this function for N-d arrays, that returns normal
    ndarrays.
Examples
--------
>>> A = np.mat('1 1; 1 1')
>>> B = np.mat('2 2; 2 2')
>>> C = np.mat('3 4; 5 6')
>>> D = np.mat('7 8; 9 0')
All the following expressions construct the same block matrix:
>>> np.bmat([[A, B], [C, D]])
matrix([[1, 1, 2, 2],
        [1, 1, 2, 2],
        [3, 4, 7, 8],
        [5, 6, 9, 0]])
>>> np.bmat(np.r_[np.c_[A, B], np.c_[C, D]])
matrix([[1, 1, 2, 2],
        [1, 1, 2, 2],
        [3, 4, 7, 8],
        [5, 6, 9, 0]])
>>> np.bmat('A,B; C,D')
matrix([[1, 1, 2, 2],
        [1, 1, 2, 2],
        [3, 4, 7, 8],
        [5, 6, 9, 0]])
Definition at line 1037 of file defmatrix.py.
Variable Documentation
__all__
list numpy.matrixlib.defmatrix.__all__ = ['matrix', 'bmat', 'mat', 'asmatrix'] private
Definition at line 1 of file defmatrix.py.
mat
numpy.matrixlib.defmatrix.mat = asmatrix
Definition at line 1114 of file defmatrix.py.