Code Cloning Analysis: matplotlib.tests.test_collections Namespace Reference
matplotlib.tests.test_collections Namespace Reference
Functions
pcfunc (request)
generate_EventCollection_plot ()
test__EventCollection__get_props ()
test__EventCollection__set_positions ()
test__EventCollection__add_positions ()
test__EventCollection__append_positions ()
test__EventCollection__extend_positions ()
test__EventCollection__switch_orientation ()
test__EventCollection__switch_orientation_2x ()
test__EventCollection__set_orientation ()
test__EventCollection__set_linelength ()
test__EventCollection__set_lineoffset ()
test__EventCollection__set_prop ()
test__EventCollection__set_color ()
check_segments (coll, positions, linelength, lineoffset, orientation)
test_collection_norm_autoscale ()
test_null_collection_datalim ()
test_no_offsets_datalim ()
test_add_collection ()
test_collection_log_datalim (fig_test, fig_ref)
test_quiver_limits ()
test_barb_limits ()
test_EllipseCollection ()
test_EllipseCollection_setter_getter ()
test_polycollection_close ()
test_regularpolycollection_rotate ()
test_regularpolycollection_scale ()
test_picking ()
test_quadmesh_contains ()
test_quadmesh_contains_concave ()
test_quadmesh_cursor_data ()
test_quadmesh_cursor_data_multiple_points ()
test_linestyle_single_dashes ()
test_size_in_xy ()
test_pandas_indexing (pd)
test_lslw_bcast ()
test_set_wrong_linestyle ()
test_capstyle ()
test_joinstyle ()
test_cap_and_joinstyle_image ()
test_scatter_post_alpha ()
test_scatter_alpha_array ()
test_pathcollection_legend_elements ()
test_EventCollection_nosort ()
test_collection_set_verts_array ()
test_fill_between_poly_collection_set_data (fig_test, fig_ref, kwargs)
test_fill_between_poly_collection_raise (t_direction, f1, shape, where, msg)
test_collection_set_array ()
test_blended_collection_autolim ()
test_singleton_autolim ()
test_autolim_with_zeros (transform, expected)
test_quadmesh_set_array_validation (pcfunc)
test_polyquadmesh_masked_vertices_array ()
test_quadmesh_get_coordinates (pcfunc)
test_quadmesh_set_array ()
test_quadmesh_vmin_vmax (pcfunc)
test_quadmesh_alpha_array (pcfunc)
test_alpha_validation (pcfunc)
test_legend_inverse_size_label_relationship ()
test_color_logic (pcfunc)
test_LineCollection_args ()
test_array_dimensions (pcfunc)
test_get_segments ()
test_set_offsets_late ()
test_set_offset_transform ()
test_set_offset_units ()
test_check_masked_offsets ()
test_masked_set_offsets (fig_ref, fig_test)
test_check_offsets_dtype ()
test_striped_lines (fig_test, fig_ref, gapcolor)
test_hatch_linewidth (fig_test, fig_ref)
Function Documentation
check_segments()
matplotlib.tests.test_collections.check_segments (coll, positions, linelength, lineoffset, orientation)
Test helper checking that all values in the segment are correct, given a
particular set of inputs.
Definition at line 271 of file test_collections.py.
Referenced by generate_EventCollection_plot(), and test__EventCollection__switch_orientation_2x().
generate_EventCollection_plot()
matplotlib.tests.test_collections.generate_EventCollection_plot ()
Generate the initial collection and plot it.
Definition at line 29 of file test_collections.py.
References check_segments(), and generate_EventCollection_plot().
Referenced by generate_EventCollection_plot(), and test__EventCollection__switch_orientation_2x().
pcfunc()
matplotlib.tests.test_collections.pcfunc (request)
Definition at line 25 of file test_collections.py.
test__EventCollection__add_positions()
matplotlib.tests.test_collections.test__EventCollection__add_positions ()
Definition at line 110 of file test_collections.py.
test__EventCollection__append_positions()
matplotlib.tests.test_collections.test__EventCollection__append_positions ()
Definition at line 128 of file test_collections.py.
test__EventCollection__extend_positions()
matplotlib.tests.test_collections.test__EventCollection__extend_positions ()
Definition at line 144 of file test_collections.py.
test__EventCollection__get_props()
matplotlib.tests.test_collections.test__EventCollection__get_props ()
Definition at line 70 of file test_collections.py.
test__EventCollection__set_color()
matplotlib.tests.test_collections.test__EventCollection__set_color ()
Definition at line 262 of file test_collections.py.
test__EventCollection__set_linelength()
matplotlib.tests.test_collections.test__EventCollection__set_linelength ()
Definition at line 215 of file test_collections.py.
test__EventCollection__set_lineoffset()
matplotlib.tests.test_collections.test__EventCollection__set_lineoffset ()
Definition at line 230 of file test_collections.py.
test__EventCollection__set_orientation()
matplotlib.tests.test_collections.test__EventCollection__set_orientation ()
Definition at line 198 of file test_collections.py.
test__EventCollection__set_positions()
matplotlib.tests.test_collections.test__EventCollection__set_positions ()
Definition at line 96 of file test_collections.py.
test__EventCollection__set_prop()
matplotlib.tests.test_collections.test__EventCollection__set_prop ()
Definition at line 249 of file test_collections.py.
test__EventCollection__switch_orientation()
matplotlib.tests.test_collections.test__EventCollection__switch_orientation ()
Definition at line 160 of file test_collections.py.
test__EventCollection__switch_orientation_2x()
matplotlib.tests.test_collections.test__EventCollection__switch_orientation_2x ()
Check that calling switch_orientation twice sets the orientation back to
the default.
Definition at line 177 of file test_collections.py.
References check_segments(), and generate_EventCollection_plot().
test_add_collection()
matplotlib.tests.test_collections.test_add_collection ()
Definition at line 325 of file test_collections.py.
test_alpha_validation()
matplotlib.tests.test_collections.test_alpha_validation (pcfunc)
Definition at line 1094 of file test_collections.py.
test_array_dimensions()
matplotlib.tests.test_collections.test_array_dimensions (pcfunc)
Definition at line 1214 of file test_collections.py.
test_autolim_with_zeros()
matplotlib.tests.test_collections.test_autolim_with_zeros (transform, expected)
Definition at line 904 of file test_collections.py.
test_barb_limits()
matplotlib.tests.test_collections.test_barb_limits ()
Definition at line 379 of file test_collections.py.
test_blended_collection_autolim()
matplotlib.tests.test_collections.test_blended_collection_autolim ()
Definition at line 879 of file test_collections.py.
test_cap_and_joinstyle_image()
matplotlib.tests.test_collections.test_cap_and_joinstyle_image ()
Definition at line 704 of file test_collections.py.
test_capstyle()
matplotlib.tests.test_collections.test_capstyle ()
Definition at line 684 of file test_collections.py.
test_check_masked_offsets()
matplotlib.tests.test_collections.test_check_masked_offsets ()
Definition at line 1292 of file test_collections.py.
test_check_offsets_dtype()
matplotlib.tests.test_collections.test_check_offsets_dtype ()
Definition at line 1326 of file test_collections.py.
test_collection_log_datalim()
matplotlib.tests.test_collections.test_collection_log_datalim (fig_test, fig_ref)
Definition at line 338 of file test_collections.py.
test_collection_norm_autoscale()
matplotlib.tests.test_collections.test_collection_norm_autoscale ()
Definition at line 297 of file test_collections.py.
test_collection_set_array()
matplotlib.tests.test_collections.test_collection_set_array ()
Definition at line 863 of file test_collections.py.
test_collection_set_verts_array()
matplotlib.tests.test_collections.test_collection_set_verts_array ()
Definition at line 816 of file test_collections.py.
test_color_logic()
matplotlib.tests.test_collections.test_color_logic (pcfunc)
Definition at line 1131 of file test_collections.py.
test_EllipseCollection()
matplotlib.tests.test_collections.test_EllipseCollection ()
Definition at line 395 of file test_collections.py.
test_EllipseCollection_setter_getter()
matplotlib.tests.test_collections.test_EllipseCollection_setter_getter ()
Definition at line 414 of file test_collections.py.
test_EventCollection_nosort()
matplotlib.tests.test_collections.test_EventCollection_nosort ()
Definition at line 809 of file test_collections.py.
test_fill_between_poly_collection_raise()
matplotlib.tests.test_collections.test_fill_between_poly_collection_raise (t_direction, f1, shape, where, msg)
Definition at line 853 of file test_collections.py.
test_fill_between_poly_collection_set_data()
matplotlib.tests.test_collections.test_fill_between_poly_collection_set_data (fig_test, fig_ref, kwargs)
Definition at line 836 of file test_collections.py.
test_get_segments()
matplotlib.tests.test_collections.test_get_segments ()
Definition at line 1230 of file test_collections.py.
test_hatch_linewidth()
matplotlib.tests.test_collections.test_hatch_linewidth (fig_test, fig_ref)
Definition at line 1367 of file test_collections.py.
test_joinstyle()
matplotlib.tests.test_collections.test_joinstyle ()
Definition at line 694 of file test_collections.py.
test_legend_inverse_size_label_relationship()
matplotlib.tests.test_collections.test_legend_inverse_size_label_relationship ()
Ensure legend markers scale appropriately when label and size are
inversely related.
Here label = 5 / size
Definition at line 1103 of file test_collections.py.
test_LineCollection_args()
matplotlib.tests.test_collections.test_LineCollection_args ()
Definition at line 1200 of file test_collections.py.
test_linestyle_single_dashes()
matplotlib.tests.test_collections.test_linestyle_single_dashes ()
Definition at line 624 of file test_collections.py.
test_lslw_bcast()
matplotlib.tests.test_collections.test_lslw_bcast ()
Definition at line 664 of file test_collections.py.
test_masked_set_offsets()
matplotlib.tests.test_collections.test_masked_set_offsets (fig_ref, fig_test)
Definition at line 1310 of file test_collections.py.
test_no_offsets_datalim()
matplotlib.tests.test_collections.test_no_offsets_datalim ()
Definition at line 314 of file test_collections.py.
test_null_collection_datalim()
matplotlib.tests.test_collections.test_null_collection_datalim ()
Definition at line 307 of file test_collections.py.
test_pandas_indexing()
matplotlib.tests.test_collections.test_pandas_indexing (pd)
Definition at line 646 of file test_collections.py.
test_pathcollection_legend_elements()
matplotlib.tests.test_collections.test_pathcollection_legend_elements ()
Definition at line 760 of file test_collections.py.
test_picking()
matplotlib.tests.test_collections.test_picking ()
Definition at line 539 of file test_collections.py.
test_polycollection_close()
matplotlib.tests.test_collections.test_polycollection_close ()
Definition at line 458 of file test_collections.py.
test_polyquadmesh_masked_vertices_array()
matplotlib.tests.test_collections.test_polyquadmesh_masked_vertices_array ()
Definition at line 964 of file test_collections.py.
test_quadmesh_alpha_array()
matplotlib.tests.test_collections.test_quadmesh_alpha_array (pcfunc)
Definition at line 1070 of file test_collections.py.
test_quadmesh_contains()
matplotlib.tests.test_collections.test_quadmesh_contains ()
Definition at line 549 of file test_collections.py.
test_quadmesh_contains_concave()
matplotlib.tests.test_collections.test_quadmesh_contains_concave ()
Definition at line 571 of file test_collections.py.
test_quadmesh_cursor_data()
matplotlib.tests.test_collections.test_quadmesh_cursor_data ()
Definition at line 592 of file test_collections.py.
test_quadmesh_cursor_data_multiple_points()
matplotlib.tests.test_collections.test_quadmesh_cursor_data_multiple_points ()
Definition at line 612 of file test_collections.py.
test_quadmesh_get_coordinates()
matplotlib.tests.test_collections.test_quadmesh_get_coordinates (pcfunc)
Definition at line 1012 of file test_collections.py.
test_quadmesh_set_array()
matplotlib.tests.test_collections.test_quadmesh_set_array ()
Definition at line 1024 of file test_collections.py.
test_quadmesh_set_array_validation()
matplotlib.tests.test_collections.test_quadmesh_set_array_validation (pcfunc)
Definition at line 916 of file test_collections.py.
test_quadmesh_vmin_vmax()
matplotlib.tests.test_collections.test_quadmesh_vmin_vmax (pcfunc)
Definition at line 1054 of file test_collections.py.
test_quiver_limits()
matplotlib.tests.test_collections.test_quiver_limits ()
Definition at line 362 of file test_collections.py.
test_regularpolycollection_rotate()
matplotlib.tests.test_collections.test_regularpolycollection_rotate ()
Definition at line 496 of file test_collections.py.
test_regularpolycollection_scale()
matplotlib.tests.test_collections.test_regularpolycollection_scale ()
Definition at line 511 of file test_collections.py.
test_scatter_alpha_array()
matplotlib.tests.test_collections.test_scatter_alpha_array ()
Definition at line 731 of file test_collections.py.
test_scatter_post_alpha()
matplotlib.tests.test_collections.test_scatter_post_alpha ()
Definition at line 725 of file test_collections.py.
test_set_offset_transform()
matplotlib.tests.test_collections.test_set_offset_transform ()
Definition at line 1260 of file test_collections.py.
test_set_offset_units()
matplotlib.tests.test_collections.test_set_offset_units ()
Definition at line 1270 of file test_collections.py.
test_set_offsets_late()
matplotlib.tests.test_collections.test_set_offsets_late ()
Definition at line 1239 of file test_collections.py.
test_set_wrong_linestyle()
matplotlib.tests.test_collections.test_set_wrong_linestyle ()
Definition at line 677 of file test_collections.py.
test_singleton_autolim()
matplotlib.tests.test_collections.test_singleton_autolim ()
Definition at line 893 of file test_collections.py.
test_size_in_xy()
matplotlib.tests.test_collections.test_size_in_xy ()
Definition at line 630 of file test_collections.py.
test_striped_lines()
matplotlib.tests.test_collections.test_striped_lines (fig_test, fig_ref, gapcolor)
Definition at line 1344 of file test_collections.py.