Code Cloning Analysis: pandas.core.apply.NDFrameApply Class Reference
pandas.core.apply.NDFrameApply Class Reference
Public Member Functions
Index index (self)
Index agg_axis (self)
DataFrame|Series agg_or_apply_list_like (self, Literal["agg", "apply"] op_name)
DataFrame|Series agg_or_apply_dict_like (self, Literal["agg", "apply"] op_name)
Public Member Functions inherited from pandas.core.apply.Apply
None __init__ (self, AggObjType obj, AggFuncType func, bool raw, str|None result_type, *, Literal[False, "compat", "_compat"] by_row="compat", str engine="python", dict[str, bool]|None engine_kwargs=None, args, kwargs)
DataFrame|Series apply (self)
DataFrame|Series|None agg (self)
DataFrame|Series transform (self)
DataFrame transform_dict_like (self, func)
DataFrame|Series transform_str_or_callable (self, func)
DataFrame|Series agg_list_like (self)
tuple[list[Hashable]|Index, list[Any]] compute_list_like (self, Literal["agg", "apply"] op_name, Series|DataFrame selected_obj, dict[str, Any] kwargs)
wrap_results_list_like (self, Iterable[Hashable] keys, list[Series|DataFrame] results)
DataFrame|Series agg_dict_like (self)
tuple[list[Hashable], list[Any]] compute_dict_like (self, Literal["agg", "apply"] op_name, Series|DataFrame selected_obj, Hashable|Sequence[Hashable] selection, dict[str, Any] kwargs)
wrap_results_dict_like (self, Series|DataFrame selected_obj, list[Hashable] result_index, list result_data)
DataFrame|Series apply_str (self)
DataFrame|Series apply_list_or_dict_like (self)
AggFuncTypeDict normalize_dictlike_arg (self, str how, DataFrame|Series obj, AggFuncTypeDict func)
Additional Inherited Members
Public Attributes inherited from pandas.core.apply.Apply
obj = obj
raw = raw
by_row = by_row
args = args or ()
kwargs = kwargs or {}
str engine = engine
dict engine_kwargs = {} if engine_kwargs is None else engine_kwargs
result_type = result_type
func = func
int axis = 1 and isinstance(self.obj, ABCDataFrame):
Protected Member Functions inherited from pandas.core.apply.Apply
_apply_str (self, obj, str func, *args, **kwargs)
Detailed Description
Methods shared by FrameApply and SeriesApply but
not GroupByApply or ResamplerWindowApply
Definition at line 709 of file apply.py.
Member Function Documentation
agg_axis()
Index pandas.core.apply.NDFrameApply.agg_axis (self)
Definition at line 722 of file apply.py.
agg_or_apply_dict_like()
DataFrame | Series pandas.core.apply.NDFrameApply.agg_or_apply_dict_like (self, Literal["agg", "apply"] op_name)
Reimplemented from pandas.core.apply.Apply.
Definition at line 748 of file apply.py.
agg_or_apply_list_like()
DataFrame | Series pandas.core.apply.NDFrameApply.agg_or_apply_list_like (self, Literal["agg", "apply"] op_name)
Reimplemented from pandas.core.apply.Apply.
Definition at line 725 of file apply.py.
index()
Index pandas.core.apply.NDFrameApply.index (self)
Definition at line 718 of file apply.py.
Referenced by pandas.core.apply.FrameApply.apply(), pandas.core.apply.FrameApply.apply_raw(), and pandas.core.internals.array_manager.SingleArrayManager.array_values().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/core/apply.py