Code Cloning Analysis: pandas.core.interchange.dataframe_protocol.Column Class Reference
pandas.core.interchange.dataframe_protocol.Column Class Reference
Public Member Functions
int size (self)
int offset (self)
tuple[DtypeKind, int, str, str] dtype (self)
CategoricalDescription describe_categorical (self)
tuple[ColumnNullType, Any] describe_null (self)
int|None null_count (self)
dict[str, Any] metadata (self)
int num_chunks (self)
Iterable[Column] get_chunks (self, int|None n_chunks=None)
ColumnBuffers get_buffers (self)
Detailed Description
A column object, with only the methods and properties required by the
interchange protocol defined.
A column can contain one or more chunks. Each chunk can contain up to three
buffers - a data buffer, a mask buffer (depending on null representation),
and an offsets buffer (if variable-size binary; e.g., variable-length
strings).
TBD: Arrow has a separate "null" dtype, and has no separate mask concept.
     Instead, it seems to use "children" for both columns with a bit mask,
     and for nested dtypes. Unclear whether this is elegant or confusing.
     This design requires checking the null representation explicitly.
     The Arrow design requires checking:
     1. the ARROW_FLAG_NULLABLE (for sentinel values)
     2. if a column has two children, combined with one of those children
        having a null dtype.
     Making the mask concept explicit seems useful. One null dtype would
     not be enough to cover both bit and byte masks, so that would mean
     even more checking if we did it the Arrow way.
TBD: there's also the "chunk" concept here, which is implicit in Arrow as
     multiple buffers per array (= column here). Semantically it may make
     sense to have both: chunks were meant for example for lazy evaluation
     of data which doesn't fit in memory, while multiple buffers per column
     could also come from doing a selection operation on a single
     contiguous buffer.
     Given these concepts, one would expect chunks to be all of the same
     size (say a 10,000 row dataframe could have 10 chunks of 1,000 rows),
     while multiple buffers could have data-dependent lengths. Not an issue
     in pandas if one column is backed by a single NumPy array, but in
     Arrow it seems possible.
     Are multiple chunks *and* multiple buffers per column necessary for
     the purposes of this interchange protocol, or must producers either
     reuse the chunk concept for this or copy the data?
Note: this Column object can only be produced by ``__dataframe__``, so
      doesn't need its own version or ``__column__`` protocol.
Definition at line 174 of file dataframe_protocol.py.
Member Function Documentation
describe_categorical()
CategoricalDescription pandas.core.interchange.dataframe_protocol.Column.describe_categorical (self)
If the dtype is categorical, there are two options:
- There are only values in the data buffer.
- There is a separate non-categorical Column encoding for categorical values.
Raises TypeError if the dtype is not categorical
Returns the dictionary with description on how to interpret the data buffer:
    - "is_ordered" : bool, whether the ordering of dictionary indices is
                     semantically meaningful.
    - "is_dictionary" : bool, whether a mapping of
                        categorical values to other objects exists
    - "categories" : Column representing the (implicit) mapping of indices to
                     category values (e.g. an array of cat1, cat2, ...).
                     None if not a dictionary-style categorical.
TBD: are there any other in-memory representations that are needed?
Reimplemented in pandas.core.interchange.column.PandasColumn.
Definition at line 271 of file dataframe_protocol.py.
describe_null()
tuple[ColumnNullType, Any] pandas.core.interchange.dataframe_protocol.Column.describe_null (self)
Return the missing value (or "null") representation the column dtype
uses, as a tuple ``(kind, value)``.
Value : if kind is "sentinel value", the actual value. If kind is a bit
mask or a byte mask, the value (0 or 1) indicating a missing value. None
otherwise.
Reimplemented in pandas.core.interchange.column.PandasColumn.
Definition at line 293 of file dataframe_protocol.py.
dtype()
tuple[DtypeKind, int, str, str] pandas.core.interchange.dataframe_protocol.Column.dtype (self)
Dtype description as a tuple ``(kind, bit-width, format string, endianness)``.
Bit-width : the number of bits as an integer
Format string : data type description format string in Apache Arrow C
                Data Interface format.
Endianness : current only native endianness (``=``) is supported
Notes:
    - Kind specifiers are aligned with DLPack where possible (hence the
      jump to 20, leave enough room for future extension)
    - Masks must be specified as boolean with either bit width 1 (for bit
      masks) or 8 (for byte masks).
    - Dtype width in bits was preferred over bytes
    - Endianness isn't too useful, but included now in case in the future
      we need to support non-native endianness
    - Went with Apache Arrow format strings over NumPy format strings
      because they're more complete from a dataframe perspective
    - Format strings are mostly useful for datetime specification, and
      for categoricals.
    - For categoricals, the format string describes the type of the
      categorical in the data buffer. In case of a separate encoding of
      the categorical (e.g. an integer to string mapping), this can
      be derived from ``self.describe_categorical``.
    - Data types not included: complex, Arrow-style null, binary, decimal,
      and nested (list, struct, map, union) dtypes.
Reimplemented in pandas.core.interchange.column.PandasColumn.
Definition at line 240 of file dataframe_protocol.py.
Referenced by pandas.core.arrays.base.ExtensionScalarOpsMixin._create_method(), scipy.sparse._index.IndexMixin._getcol(), pandas.core.generic.NDFrame._inplace_method(), scipy.sparse._index.IndexMixin._raise_on_1d_array_slice(), pandas.core.strings.object_array.ObjectStringArrayMixin._str_map(), numpy.matrixlib.defmatrix.matrix.H(), pandas.core.internals.array_manager.SingleArrayManager.make_empty(), numpy.core.records.record.pprint(), pandas.core.frame.DataFrame.quantile(), pandas.core.generic.NDFrame.rank(), pandas.io.pytables.AppendableTable.write_data(), and pandas.io.pytables.AppendableTable.write_data_chunk().
get_buffers()
ColumnBuffers pandas.core.interchange.dataframe_protocol.Column.get_buffers (self)
Return a dictionary containing the underlying buffers.
The returned dictionary has the following contents:
    - "data": a two-element tuple whose first element is a buffer
              containing the data and whose second element is the data
              buffer's associated dtype.
    - "validity": a two-element tuple whose first element is a buffer
                  containing mask values indicating missing data and
                  whose second element is the mask value buffer's
                  associated dtype. None if the null representation is
                  not a bit or byte mask.
    - "offsets": a two-element tuple whose first element is a buffer
                 containing the offset values for variable-size binary
                 data (e.g., variable-length strings) and whose second
                 element is the offsets buffer's associated dtype. None
                 if the data buffer does not have an associated offsets
                 buffer.
Reimplemented in pandas.core.interchange.column.PandasColumn.
Definition at line 334 of file dataframe_protocol.py.
get_chunks()
Iterable[Column] pandas.core.interchange.dataframe_protocol.Column.get_chunks (self, int | None n_chunks = None)
Return an iterator yielding the chunks.
See `DataFrame.get_chunks` for details on ``n_chunks``.
Reimplemented in pandas.core.interchange.column.PandasColumn.
Definition at line 326 of file dataframe_protocol.py.
metadata()
dict[str, Any] pandas.core.interchange.dataframe_protocol.Column.metadata (self)
The metadata for the column. See `DataFrame.metadata` for more details.
Reimplemented in pandas.core.interchange.column.PandasColumn.
Definition at line 314 of file dataframe_protocol.py.
Referenced by pip._internal.req.req_install.InstallRequirement._set_requirement(), pip._internal.req.req_install.InstallRequirement.archive(), and pip._internal.req.req_install.InstallRequirement.prepare_metadata().
null_count()
int | None pandas.core.interchange.dataframe_protocol.Column.null_count (self)
Number of null elements, if known.
Note: Arrow uses -1 to indicate "unknown", but None seems cleaner.
Reimplemented in pandas.core.interchange.column.PandasColumn.
Definition at line 305 of file dataframe_protocol.py.
num_chunks()
int pandas.core.interchange.dataframe_protocol.Column.num_chunks (self)
Return the number of chunks the column consists of.
Reimplemented in pandas.core.interchange.column.PandasColumn.
Definition at line 320 of file dataframe_protocol.py.
offset()
int pandas.core.interchange.dataframe_protocol.Column.offset (self)
Offset of first element.
May be > 0 if using chunks; for example for a column with N chunks of
equal size M (only the last chunk may be shorter),
``offset = n * M``, ``n = 0 .. N-1``.
Reimplemented in pandas.core.interchange.column.PandasColumn.
Definition at line 229 of file dataframe_protocol.py.
Referenced by fontTools.ttLib.sfnt.SFNTReader.__getitem__().
size()
int pandas.core.interchange.dataframe_protocol.Column.size (self)
Size of the column, in elements.
Corresponds to DataFrame.num_rows() if column is a single chunk;
equal to size of this current chunk otherwise.
Reimplemented in pandas.core.interchange.column.PandasColumn.
Definition at line 219 of file dataframe_protocol.py.
Referenced by pip._vendor.rich.console.Console.height(), pip._vendor.rich.console.Console.options(), and pip._vendor.rich.console.Console.width().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/core/interchange/dataframe_protocol.py