Code Cloning Analysis: pandas.core.dtypes.common Namespace Reference
pandas.core.dtypes.common Namespace Reference
Functions
str ensure_str (bytes|Any value)
int ensure_python_int (int|np.integer value)
Callable classes (*klasses)
Callable _classes_and_not_datetimelike (*klasses)
bool is_object_dtype (arr_or_dtype)
bool is_sparse (arr)
bool is_scipy_sparse (arr)
bool is_datetime64_dtype (arr_or_dtype)
bool is_datetime64tz_dtype (arr_or_dtype)
bool is_timedelta64_dtype (arr_or_dtype)
bool is_period_dtype (arr_or_dtype)
bool is_interval_dtype (arr_or_dtype)
bool is_categorical_dtype (arr_or_dtype)
bool is_string_or_object_np_dtype (np.dtype dtype)
bool is_string_dtype (arr_or_dtype)
bool is_dtype_equal (source, target)
bool is_integer_dtype (arr_or_dtype)
bool is_signed_integer_dtype (arr_or_dtype)
bool is_unsigned_integer_dtype (arr_or_dtype)
bool is_int64_dtype (arr_or_dtype)
bool is_datetime64_any_dtype (arr_or_dtype)
bool is_datetime64_ns_dtype (arr_or_dtype)
bool is_timedelta64_ns_dtype (arr_or_dtype)
bool is_numeric_v_string_like (ArrayLike a, b)
bool needs_i8_conversion (DtypeObj|None dtype)
bool is_numeric_dtype (arr_or_dtype)
bool is_any_real_numeric_dtype (arr_or_dtype)
bool is_float_dtype (arr_or_dtype)
bool is_bool_dtype (arr_or_dtype)
bool is_1d_only_ea_dtype (DtypeObj|None dtype)
bool is_extension_array_dtype (arr_or_dtype)
bool is_ea_or_datetimelike_dtype (DtypeObj|None dtype)
bool is_complex_dtype (arr_or_dtype)
bool _is_dtype (arr_or_dtype, condition)
DtypeObj _get_dtype (arr_or_dtype)
bool _is_dtype_type (arr_or_dtype, condition)
type infer_dtype_from_object (dtype)
None _validate_date_like_dtype (dtype)
None validate_all_hashable (*args, str|None error_name=None)
DtypeObj pandas_dtype (dtype)
bool is_all_strings (ArrayLike value)
Variables
DT64NS_DTYPE = conversion.DT64NS_DTYPE
TD64NS_DTYPE = conversion.TD64NS_DTYPE
INT64_DTYPE = np.dtype(np.int64)
_is_scipy_sparse = None
ensure_float64 = algos.ensure_float64
ensure_int64 = algos.ensure_int64
ensure_int32 = algos.ensure_int32
ensure_int16 = algos.ensure_int16
ensure_int8 = algos.ensure_int8
ensure_platform_int = algos.ensure_platform_int
ensure_object = algos.ensure_object
ensure_uint64 = algos.ensure_uint64
list __all__
Detailed Description
Common type operations.
Function Documentation
_classes_and_not_datetimelike()
Callable pandas.core.dtypes.common._classes_and_not_datetimelike (* klasses) protected
Evaluate if the tipo is a subclass of the klasses
and not a datetimelike.
Definition at line 128 of file common.py.
Referenced by is_integer_dtype(), is_numeric_dtype(), is_signed_integer_dtype(), and is_unsigned_integer_dtype().
_get_dtype()
DtypeObj pandas.core.dtypes.common._get_dtype (arr_or_dtype) protected
Get the dtype instance associated with an array
or dtype object.
Parameters
----------
arr_or_dtype : array-like or dtype
    The array-like or dtype object whose dtype we want to extract.
Returns
-------
obj_dtype : The extract dtype instance from the
            passed in array or dtype object.
Raises
------
TypeError : The passed in object is None.
Definition at line 1409 of file common.py.
References pandas_dtype().
Referenced by _is_dtype(), is_bool_dtype(), is_datetime64_any_dtype(), is_datetime64_ns_dtype(), is_dtype_equal(), and is_string_dtype().
_is_dtype()
bool pandas.core.dtypes.common._is_dtype (arr_or_dtype, condition) protected
Return true if the condition is satisfied for the arr_or_dtype.
Parameters
----------
arr_or_dtype : array-like, str, np.dtype, or ExtensionArrayType
    The array-like or dtype object whose dtype we want to extract.
condition : callable[Union[np.dtype, ExtensionDtype]]
Returns
-------
bool
Definition at line 1385 of file common.py.
References _get_dtype().
Referenced by is_float_dtype(), is_integer_dtype(), is_numeric_dtype(), is_signed_integer_dtype(), is_string_dtype(), is_timedelta64_ns_dtype(), and is_unsigned_integer_dtype().
_is_dtype_type()
bool pandas.core.dtypes.common._is_dtype_type (arr_or_dtype, condition) protected
Return true if the condition is satisfied for the arr_or_dtype.
Parameters
----------
arr_or_dtype : array-like or dtype
    The array-like or dtype object whose dtype we want to extract.
condition : callable[Union[np.dtype, ExtensionDtypeType]]
Returns
-------
bool : if the condition is satisfied for the arr_or_dtype
Definition at line 1444 of file common.py.
References pandas_dtype().
Referenced by is_complex_dtype(), is_datetime64_dtype(), is_float_dtype(), is_int64_dtype(), is_integer_dtype(), is_numeric_dtype(), is_object_dtype(), is_signed_integer_dtype(), is_timedelta64_dtype(), and is_unsigned_integer_dtype().
_validate_date_like_dtype()
None pandas.core.dtypes.common._validate_date_like_dtype (dtype) protected
Check whether the dtype is a date-like dtype. Raises an error if invalid.
Parameters
----------
dtype : dtype, type
    The dtype to check.
Raises
------
TypeError : The dtype could not be casted to a date-like dtype.
ValueError : The dtype is an illegal date-like dtype (e.g. the
             frequency provided is too specific)
Definition at line 1555 of file common.py.
Referenced by infer_dtype_from_object().
classes()
Callable pandas.core.dtypes.common.classes (* klasses)
Evaluate if the tipo is a subclass of the klasses.
Definition at line 123 of file common.py.
Referenced by is_complex_dtype(), is_datetime64_dtype(), is_float_dtype(), is_int64_dtype(), is_object_dtype(), and is_timedelta64_dtype().
ensure_python_int()
int pandas.core.dtypes.common.ensure_python_int (int | np.integer value)
Ensure that a value is a python int.
Parameters
----------
value: int or numpy.integer
Returns
-------
int
Raises
------
TypeError: if the value isn't an int or can't be converted to one.
Definition at line 93 of file common.py.
ensure_str()
str pandas.core.dtypes.common.ensure_str (bytes | Any value)
Ensure that bytes and non-strings get converted into ``str`` objects.
Definition at line 82 of file common.py.
infer_dtype_from_object()
type pandas.core.dtypes.common.infer_dtype_from_object (dtype)
Get a numpy dtype.type-style object for a dtype object.
This methods also includes handling of the datetime64[ns] and
datetime64[ns, TZ] objects.
If no dtype can be found, we return ``object``.
Parameters
----------
dtype : dtype, type
    The dtype object whose numpy dtype.type-style
    object we want to extract.
Returns
-------
type
Definition at line 1488 of file common.py.
References _validate_date_like_dtype(), infer_dtype_from_object(), and pandas_dtype().
Referenced by infer_dtype_from_object().
is_1d_only_ea_dtype()
bool pandas.core.dtypes.common.is_1d_only_ea_dtype (DtypeObj | None dtype)
Analogue to is_extension_array_dtype but excluding DatetimeTZDtype.
Definition at line 1272 of file common.py.
is_all_strings()
bool pandas.core.dtypes.common.is_all_strings (ArrayLike value)
Check if this is an array of strings that we should try parsing.
Includes object-dtype ndarray containing all-strings, StringArray,
and Categorical with all-string categories.
Does not include numpy string dtypes.
Definition at line 1689 of file common.py.
Referenced by is_string_dtype().
is_any_real_numeric_dtype()
bool pandas.core.dtypes.common.is_any_real_numeric_dtype (arr_or_dtype)
Check whether the provided array or dtype is of a real number dtype.
Parameters
----------
arr_or_dtype : array-like or dtype
    The array or dtype to check.
Returns
-------
boolean
    Whether or not the array or dtype is of a real number dtype.
Examples
--------
>>> from pandas.api.types import is_any_real_numeric_dtype
>>> is_any_real_numeric_dtype(int)
True
>>> is_any_real_numeric_dtype(float)
True
>>> is_any_real_numeric_dtype(object)
False
>>> is_any_real_numeric_dtype(str)
False
>>> is_any_real_numeric_dtype(complex(1, 2))
False
>>> is_any_real_numeric_dtype(bool)
False
Definition at line 1128 of file common.py.
References is_bool_dtype(), is_complex_dtype(), and is_numeric_dtype().
is_bool_dtype()
bool pandas.core.dtypes.common.is_bool_dtype (arr_or_dtype)
Check whether the provided array or dtype is of a boolean dtype.
Parameters
----------
arr_or_dtype : array-like or dtype
    The array or dtype to check.
Returns
-------
boolean
    Whether or not the array or dtype is of a boolean dtype.
Notes
-----
An ExtensionArray is considered boolean when the ``_is_boolean``
attribute is set to True.
Examples
--------
>>> from pandas.api.types import is_bool_dtype
>>> is_bool_dtype(str)
False
>>> is_bool_dtype(int)
False
>>> is_bool_dtype(bool)
True
>>> is_bool_dtype(np.bool_)
True
>>> is_bool_dtype(np.array(['a', 'b']))
False
>>> is_bool_dtype(pd.Series([1, 2]))
False
>>> is_bool_dtype(np.array([True, False]))
True
>>> is_bool_dtype(pd.Categorical([True, False]))
True
>>> is_bool_dtype(pd.arrays.SparseArray([True, False]))
True
Definition at line 1200 of file common.py.
References _get_dtype(), and is_bool_dtype().
Referenced by is_any_real_numeric_dtype(), and is_bool_dtype().
is_categorical_dtype()
bool pandas.core.dtypes.common.is_categorical_dtype (arr_or_dtype)
Check whether an array-like or dtype is of the Categorical dtype.
.. deprecated:: 2.2.0
    Use isinstance(dtype, pd.CategoricalDtype) instead.
Parameters
----------
arr_or_dtype : array-like or dtype
    The array-like or dtype to check.
Returns
-------
boolean
    Whether or not the array-like or dtype is of the Categorical dtype.
Examples
--------
>>> from pandas.api.types import is_categorical_dtype
>>> from pandas import CategoricalDtype
>>> is_categorical_dtype(object)
False
>>> is_categorical_dtype(CategoricalDtype())
True
>>> is_categorical_dtype([1, 2, 3])
False
>>> is_categorical_dtype(pd.Categorical([1, 2, 3]))
True
>>> is_categorical_dtype(pd.CategoricalIndex([1, 2, 3]))
True
Definition at line 483 of file common.py.
is_complex_dtype()
bool pandas.core.dtypes.common.is_complex_dtype (arr_or_dtype)
Check whether the provided array or dtype is of a complex dtype.
Parameters
----------
arr_or_dtype : array-like or dtype
    The array or dtype to check.
Returns
-------
boolean
    Whether or not the array or dtype is of a complex dtype.
Examples
--------
>>> from pandas.api.types import is_complex_dtype
>>> is_complex_dtype(str)
False
>>> is_complex_dtype(int)
False
>>> is_complex_dtype(np.complex128)
True
>>> is_complex_dtype(np.array(['a', 'b']))
False
>>> is_complex_dtype(pd.Series([1, 2]))
False
>>> is_complex_dtype(np.array([1 + 1j, 5]))
True
Definition at line 1352 of file common.py.
References _is_dtype_type(), and classes().
Referenced by is_any_real_numeric_dtype().
is_datetime64_any_dtype()
bool pandas.core.dtypes.common.is_datetime64_any_dtype (arr_or_dtype)
Check whether the provided array or dtype is of the datetime64 dtype.
Parameters
----------
arr_or_dtype : array-like or dtype
    The array or dtype to check.
Returns
-------
bool
    Whether or not the array or dtype is of the datetime64 dtype.
Examples
--------
>>> from pandas.api.types import is_datetime64_any_dtype
>>> from pandas.core.dtypes.dtypes import DatetimeTZDtype
>>> is_datetime64_any_dtype(str)
False
>>> is_datetime64_any_dtype(int)
False
>>> is_datetime64_any_dtype(np.datetime64)  # can be tz-naive
True
>>> is_datetime64_any_dtype(DatetimeTZDtype("ns", "US/Eastern"))
True
>>> is_datetime64_any_dtype(np.array(['a', 'b']))
False
>>> is_datetime64_any_dtype(np.array([1, 2]))
False
>>> is_datetime64_any_dtype(np.array([], dtype="datetime64[ns]"))
True
>>> is_datetime64_any_dtype(pd.DatetimeIndex([1, 2, 3], dtype="datetime64[ns]"))
True
Definition at line 864 of file common.py.
References _get_dtype().
is_datetime64_dtype()
bool pandas.core.dtypes.common.is_datetime64_dtype (arr_or_dtype)
Check whether an array-like or dtype is of the datetime64 dtype.
Parameters
----------
arr_or_dtype : array-like or dtype
    The array-like or dtype to check.
Returns
-------
boolean
    Whether or not the array-like or dtype is of the datetime64 dtype.
Examples
--------
>>> from pandas.api.types import is_datetime64_dtype
>>> is_datetime64_dtype(object)
False
>>> is_datetime64_dtype(np.datetime64)
True
>>> is_datetime64_dtype(np.array([], dtype=int))
False
>>> is_datetime64_dtype(np.array([], dtype=np.datetime64))
True
>>> is_datetime64_dtype([1, 2, 3])
False
Definition at line 265 of file common.py.
References _is_dtype_type(), and classes().
is_datetime64_ns_dtype()
bool pandas.core.dtypes.common.is_datetime64_ns_dtype (arr_or_dtype)
Check whether the provided array or dtype is of the datetime64[ns] dtype.
Parameters
----------
arr_or_dtype : array-like or dtype
    The array or dtype to check.
Returns
-------
bool
    Whether or not the array or dtype is of the datetime64[ns] dtype.
Examples
--------
>>> from pandas.api.types import is_datetime64_ns_dtype
>>> from pandas.core.dtypes.dtypes import DatetimeTZDtype
>>> is_datetime64_ns_dtype(str)
False
>>> is_datetime64_ns_dtype(int)
False
>>> is_datetime64_ns_dtype(np.datetime64)  # no unit
False
>>> is_datetime64_ns_dtype(DatetimeTZDtype("ns", "US/Eastern"))
True
>>> is_datetime64_ns_dtype(np.array(['a', 'b']))
False
>>> is_datetime64_ns_dtype(np.array([1, 2]))
False
>>> is_datetime64_ns_dtype(np.array([], dtype="datetime64"))  # no unit
False
>>> is_datetime64_ns_dtype(np.array([], dtype="datetime64[ps]"))  # wrong unit
False
>>> is_datetime64_ns_dtype(pd.DatetimeIndex([1, 2, 3], dtype="datetime64[ns]"))
True
Definition at line 913 of file common.py.
References _get_dtype().
is_datetime64tz_dtype()
bool pandas.core.dtypes.common.is_datetime64tz_dtype (arr_or_dtype)
Check whether an array-like or dtype is of a DatetimeTZDtype dtype.
.. deprecated:: 2.1.0
    Use isinstance(dtype, pd.DatetimeTZDtype) instead.
Parameters
----------
arr_or_dtype : array-like or dtype
    The array-like or dtype to check.
Returns
-------
boolean
    Whether or not the array-like or dtype is of a DatetimeTZDtype dtype.
Examples
--------
>>> from pandas.api.types import is_datetime64tz_dtype
>>> is_datetime64tz_dtype(object)
False
>>> is_datetime64tz_dtype([1, 2, 3])
False
>>> is_datetime64tz_dtype(pd.DatetimeIndex([1, 2, 3]))  # tz-naive
False
>>> is_datetime64tz_dtype(pd.DatetimeIndex([1, 2, 3], tz="US/Eastern"))
True
>>> from pandas.core.dtypes.dtypes import DatetimeTZDtype
>>> dtype = DatetimeTZDtype("ns", tz="US/Eastern")
>>> s = pd.Series([], dtype=dtype)
>>> is_datetime64tz_dtype(dtype)
True
>>> is_datetime64tz_dtype(s)
True
Definition at line 299 of file common.py.
is_dtype_equal()
bool pandas.core.dtypes.common.is_dtype_equal (source, target)
Check if two dtypes are equal.
Parameters
----------
source : The first dtype to compare
target : The second dtype to compare
Returns
-------
boolean
    Whether or not the two dtypes are equal.
Examples
--------
>>> is_dtype_equal(int, float)
False
>>> is_dtype_equal("int", int)
True
>>> is_dtype_equal(object, "category")
False
>>> is_dtype_equal(CategoricalDtype(), "category")
True
>>> is_dtype_equal(DatetimeTZDtype(tz="UTC"), "datetime64")
False
Definition at line 585 of file common.py.
References _get_dtype(), and is_dtype_equal().
Referenced by is_dtype_equal().
is_ea_or_datetimelike_dtype()
bool pandas.core.dtypes.common.is_ea_or_datetimelike_dtype (DtypeObj | None dtype)
Check for ExtensionDtype, datetime64 dtype, or timedelta64 dtype.
Notes
-----
Checks only for dtype objects, not dtype-castable strings or types.
Definition at line 1341 of file common.py.
is_extension_array_dtype()
bool pandas.core.dtypes.common.is_extension_array_dtype (arr_or_dtype)
Check if an object is a pandas extension array type.
See the :ref:`Use Guide <extending.extension-types>` for more.
Parameters
----------
arr_or_dtype : object
    For array-like input, the ``.dtype`` attribute will
    be extracted.
Returns
-------
bool
    Whether the `arr_or_dtype` is an extension array type.
Notes
-----
This checks whether an object implements the pandas extension
array interface. In pandas, this includes:
* Categorical
* Sparse
* Interval
* Period
* DatetimeArray
* TimedeltaArray
Third-party libraries may implement arrays or types satisfying
this interface as well.
Examples
--------
>>> from pandas.api.types import is_extension_array_dtype
>>> arr = pd.Categorical(['a', 'b'])
>>> is_extension_array_dtype(arr)
True
>>> is_extension_array_dtype(arr.dtype)
True
>>> arr = np.array(['a', 'b'])
>>> is_extension_array_dtype(arr.dtype)
False
Definition at line 1279 of file common.py.
References pandas_dtype().
is_float_dtype()
bool pandas.core.dtypes.common.is_float_dtype (arr_or_dtype)
Check whether the provided array or dtype is of a float dtype.
Parameters
----------
arr_or_dtype : array-like or dtype
    The array or dtype to check.
Returns
-------
boolean
    Whether or not the array or dtype is of a float dtype.
Examples
--------
>>> from pandas.api.types import is_float_dtype
>>> is_float_dtype(str)
False
>>> is_float_dtype(int)
False
>>> is_float_dtype(float)
True
>>> is_float_dtype(np.array(['a', 'b']))
False
>>> is_float_dtype(pd.Series([1, 2]))
False
>>> is_float_dtype(pd.Index([1, 2.]))
True
Definition at line 1165 of file common.py.
References _is_dtype(), _is_dtype_type(), and classes().
is_int64_dtype()
bool pandas.core.dtypes.common.is_int64_dtype (arr_or_dtype)
Check whether the provided array or dtype is of the int64 dtype.
.. deprecated:: 2.1.0
   is_int64_dtype is deprecated and will be removed in a future
   version. Use dtype == np.int64 instead.
Parameters
----------
arr_or_dtype : array-like or dtype
    The array or dtype to check.
Returns
-------
boolean
    Whether or not the array or dtype is of the int64 dtype.
Notes
-----
Depending on system architecture, the return value of `is_int64_dtype(
int)` will be True if the OS uses 64-bit integers and False if the OS
uses 32-bit integers.
Examples
--------
>>> from pandas.api.types import is_int64_dtype
>>> is_int64_dtype(str)  # doctest: +SKIP
False
>>> is_int64_dtype(np.int32)  # doctest: +SKIP
False
>>> is_int64_dtype(np.int64)  # doctest: +SKIP
True
>>> is_int64_dtype('int8')  # doctest: +SKIP
False
>>> is_int64_dtype('Int8')  # doctest: +SKIP
False
>>> is_int64_dtype(pd.Int64Dtype)  # doctest: +SKIP
True
>>> is_int64_dtype(float)  # doctest: +SKIP
False
>>> is_int64_dtype(np.uint64)  # unsigned  # doctest: +SKIP
False
>>> is_int64_dtype(np.array(['a', 'b']))  # doctest: +SKIP
False
>>> is_int64_dtype(np.array([1, 2], dtype=np.int64))  # doctest: +SKIP
True
>>> is_int64_dtype(pd.Index([1, 2.]))  # float  # doctest: +SKIP
False
>>> is_int64_dtype(np.array([1, 2], dtype=np.uint32))  # unsigned  # doctest: +SKIP
False
Definition at line 801 of file common.py.
References _is_dtype_type(), and classes().
is_integer_dtype()
bool pandas.core.dtypes.common.is_integer_dtype (arr_or_dtype)
Check whether the provided array or dtype is of an integer dtype.
Unlike in `is_any_int_dtype`, timedelta64 instances will return False.
The nullable Integer dtypes (e.g. pandas.Int64Dtype) are also considered
as integer by this function.
Parameters
----------
arr_or_dtype : array-like or dtype
    The array or dtype to check.
Returns
-------
boolean
    Whether or not the array or dtype is of an integer dtype and
    not an instance of timedelta64.
Examples
--------
>>> from pandas.api.types import is_integer_dtype
>>> is_integer_dtype(str)
False
>>> is_integer_dtype(int)
True
>>> is_integer_dtype(float)
False
>>> is_integer_dtype(np.uint64)
True
>>> is_integer_dtype('int8')
True
>>> is_integer_dtype('Int8')
True
>>> is_integer_dtype(pd.Int8Dtype)
True
>>> is_integer_dtype(np.datetime64)
False
>>> is_integer_dtype(np.timedelta64)
False
>>> is_integer_dtype(np.array(['a', 'b']))
False
>>> is_integer_dtype(pd.Series([1, 2]))
True
>>> is_integer_dtype(np.array([], dtype=np.timedelta64))
False
>>> is_integer_dtype(pd.Index([1, 2.]))  # float
False
Definition at line 635 of file common.py.
References _classes_and_not_datetimelike(), _is_dtype(), and _is_dtype_type().
is_interval_dtype()
bool pandas.core.dtypes.common.is_interval_dtype (arr_or_dtype)
Check whether an array-like or dtype is of the Interval dtype.
.. deprecated:: 2.2.0
    Use isinstance(dtype, pd.IntervalDtype) instead.
Parameters
----------
arr_or_dtype : array-like or dtype
    The array-like or dtype to check.
Returns
-------
boolean
    Whether or not the array-like or dtype is of the Interval dtype.
Examples
--------
>>> from pandas.core.dtypes.common import is_interval_dtype
>>> is_interval_dtype(object)
False
>>> is_interval_dtype(pd.IntervalDtype())
True
>>> is_interval_dtype([1, 2, 3])
False
>>>
>>> interval = pd.Interval(1, 2, closed="right")
>>> is_interval_dtype(interval)
False
>>> is_interval_dtype(pd.IntervalIndex([interval]))
True
Definition at line 434 of file common.py.
is_numeric_dtype()
bool pandas.core.dtypes.common.is_numeric_dtype (arr_or_dtype)
Check whether the provided array or dtype is of a numeric dtype.
Parameters
----------
arr_or_dtype : array-like or dtype
    The array or dtype to check.
Returns
-------
boolean
    Whether or not the array or dtype is of a numeric dtype.
Examples
--------
>>> from pandas.api.types import is_numeric_dtype
>>> is_numeric_dtype(str)
False
>>> is_numeric_dtype(int)
True
>>> is_numeric_dtype(float)
True
>>> is_numeric_dtype(np.uint64)
True
>>> is_numeric_dtype(np.datetime64)
False
>>> is_numeric_dtype(np.timedelta64)
False
>>> is_numeric_dtype(np.array(['a', 'b']))
False
>>> is_numeric_dtype(pd.Series([1, 2]))
True
>>> is_numeric_dtype(pd.Index([1, 2.]))
True
>>> is_numeric_dtype(np.array([], dtype=np.timedelta64))
False
Definition at line 1083 of file common.py.
References _classes_and_not_datetimelike(), _is_dtype(), and _is_dtype_type().
Referenced by is_any_real_numeric_dtype().
is_numeric_v_string_like()
bool pandas.core.dtypes.common.is_numeric_v_string_like (ArrayLike a, b)
Check if we are comparing a string-like object to a numeric ndarray.
NumPy doesn't like to compare such objects, especially numeric arrays
and scalar string-likes.
Parameters
----------
a : array-like, scalar
    The first object to check.
b : array-like, scalar
    The second object to check.
Returns
-------
boolean
    Whether we return a comparing a string-like object to a numeric array.
Examples
--------
>>> is_numeric_v_string_like(np.array([1]), "foo")
True
>>> is_numeric_v_string_like(np.array([1, 2]), np.array(["foo"]))
True
>>> is_numeric_v_string_like(np.array(["foo"]), np.array([1, 2]))
True
>>> is_numeric_v_string_like(np.array([1]), np.array([2]))
False
>>> is_numeric_v_string_like(np.array(["foo"]), np.array(["foo"]))
False
Definition at line 994 of file common.py.
is_object_dtype()
bool pandas.core.dtypes.common.is_object_dtype (arr_or_dtype)
Check whether an array-like or dtype is of the object dtype.
Parameters
----------
arr_or_dtype : array-like or dtype
    The array-like or dtype to check.
Returns
-------
boolean
    Whether or not the array-like or dtype is of the object dtype.
Examples
--------
>>> from pandas.api.types import is_object_dtype
>>> is_object_dtype(object)
True
>>> is_object_dtype(int)
False
>>> is_object_dtype(np.array([], dtype=object))
True
>>> is_object_dtype(np.array([], dtype=int))
False
>>> is_object_dtype([1, 2, 3])
False
Definition at line 139 of file common.py.
References _is_dtype_type(), and classes().
is_period_dtype()
bool pandas.core.dtypes.common.is_period_dtype (arr_or_dtype)
Check whether an array-like or dtype is of the Period dtype.
.. deprecated:: 2.2.0
    Use isinstance(dtype, pd.Period) instead.
Parameters
----------
arr_or_dtype : array-like or dtype
    The array-like or dtype to check.
Returns
-------
boolean
    Whether or not the array-like or dtype is of the Period dtype.
Examples
--------
>>> from pandas.core.dtypes.common import is_period_dtype
>>> is_period_dtype(object)
False
>>> is_period_dtype(pd.PeriodDtype(freq="D"))
True
>>> is_period_dtype([1, 2, 3])
False
>>> is_period_dtype(pd.Period("2017-01-01"))
False
>>> is_period_dtype(pd.PeriodIndex([], freq="Y"))
True
Definition at line 388 of file common.py.
is_scipy_sparse()
bool pandas.core.dtypes.common.is_scipy_sparse (arr)
Check whether an array-like is a scipy.sparse.spmatrix instance.
Parameters
----------
arr : array-like
    The array-like to check.
Returns
-------
boolean
    Whether or not the array-like is a scipy.sparse.spmatrix instance.
Notes
-----
If scipy is not installed, this function will always return False.
Examples
--------
>>> from scipy.sparse import bsr_matrix
>>> is_scipy_sparse(bsr_matrix([1, 2, 3]))
True
>>> is_scipy_sparse(pd.arrays.SparseArray([1, 2, 3]))
False
Definition at line 227 of file common.py.
is_signed_integer_dtype()
bool pandas.core.dtypes.common.is_signed_integer_dtype (arr_or_dtype)
Check whether the provided array or dtype is of a signed integer dtype.
Unlike in `is_any_int_dtype`, timedelta64 instances will return False.
The nullable Integer dtypes (e.g. pandas.Int64Dtype) are also considered
as integer by this function.
Parameters
----------
arr_or_dtype : array-like or dtype
    The array or dtype to check.
Returns
-------
boolean
    Whether or not the array or dtype is of a signed integer dtype
    and not an instance of timedelta64.
Examples
--------
>>> from pandas.core.dtypes.common import is_signed_integer_dtype
>>> is_signed_integer_dtype(str)
False
>>> is_signed_integer_dtype(int)
True
>>> is_signed_integer_dtype(float)
False
>>> is_signed_integer_dtype(np.uint64)  # unsigned
False
>>> is_signed_integer_dtype('int8')
True
>>> is_signed_integer_dtype('Int8')
True
>>> is_signed_integer_dtype(pd.Int8Dtype)
True
>>> is_signed_integer_dtype(np.datetime64)
False
>>> is_signed_integer_dtype(np.timedelta64)
False
>>> is_signed_integer_dtype(np.array(['a', 'b']))
False
>>> is_signed_integer_dtype(pd.Series([1, 2]))
True
>>> is_signed_integer_dtype(np.array([], dtype=np.timedelta64))
False
>>> is_signed_integer_dtype(pd.Index([1, 2.]))  # float
False
>>> is_signed_integer_dtype(np.array([1, 2], dtype=np.uint32))  # unsigned
False
Definition at line 692 of file common.py.
References _classes_and_not_datetimelike(), _is_dtype(), and _is_dtype_type().
is_sparse()
bool pandas.core.dtypes.common.is_sparse (arr)
Check whether an array-like is a 1-D pandas sparse array.
.. deprecated:: 2.1.0
    Use isinstance(dtype, pd.SparseDtype) instead.
Check that the one-dimensional array-like is a pandas sparse array.
Returns True if it is a pandas sparse array, not another type of
sparse array.
Parameters
----------
arr : array-like
    Array-like to check.
Returns
-------
bool
    Whether or not the array-like is a pandas sparse array.
Examples
--------
Returns `True` if the parameter is a 1-D pandas sparse array.
>>> from pandas.api.types import is_sparse
>>> is_sparse(pd.arrays.SparseArray([0, 0, 1, 0]))
True
>>> is_sparse(pd.Series(pd.arrays.SparseArray([0, 0, 1, 0])))
True
Returns `False` if the parameter is not sparse.
>>> is_sparse(np.array([0, 0, 1, 0]))
False
>>> is_sparse(pd.Series([0, 1, 0, 0]))
False
Returns `False` if the parameter is not a pandas sparse array.
>>> from scipy.sparse import bsr_matrix
>>> is_sparse(bsr_matrix([0, 1, 0, 0]))
False
Returns `False` if the parameter has more than one dimension.
Definition at line 170 of file common.py.
is_string_dtype()
bool pandas.core.dtypes.common.is_string_dtype (arr_or_dtype)
Check whether the provided array or dtype is of the string dtype.
If an array is passed with an object dtype, the elements must be
inferred as strings.
Parameters
----------
arr_or_dtype : array-like or dtype
    The array or dtype to check.
Returns
-------
boolean
    Whether or not the array or dtype is of the string dtype.
Examples
--------
>>> from pandas.api.types import is_string_dtype
>>> is_string_dtype(str)
True
>>> is_string_dtype(object)
True
>>> is_string_dtype(int)
False
>>> is_string_dtype(np.array(['a', 'b']))
True
>>> is_string_dtype(pd.Series([1, 2]))
False
>>> is_string_dtype(pd.Series([1, 2], dtype=object))
False
Definition at line 538 of file common.py.
References _get_dtype(), _is_dtype(), is_all_strings(), and is_string_or_object_np_dtype().
is_string_or_object_np_dtype()
bool pandas.core.dtypes.common.is_string_or_object_np_dtype (np.dtype dtype)
Faster alternative to is_string_dtype, assumes we have a np.dtype object.
Definition at line 531 of file common.py.
Referenced by is_string_dtype().
is_timedelta64_dtype()
bool pandas.core.dtypes.common.is_timedelta64_dtype (arr_or_dtype)
Check whether an array-like or dtype is of the timedelta64 dtype.
Parameters
----------
arr_or_dtype : array-like or dtype
    The array-like or dtype to check.
Returns
-------
boolean
    Whether or not the array-like or dtype is of the timedelta64 dtype.
Examples
--------
>>> from pandas.core.dtypes.common import is_timedelta64_dtype
>>> is_timedelta64_dtype(object)
False
>>> is_timedelta64_dtype(np.timedelta64)
True
>>> is_timedelta64_dtype([1, 2, 3])
False
>>> is_timedelta64_dtype(pd.Series([], dtype="timedelta64[ns]"))
True
>>> is_timedelta64_dtype('0 days')
False
Definition at line 353 of file common.py.
References _is_dtype_type(), and classes().
is_timedelta64_ns_dtype()
bool pandas.core.dtypes.common.is_timedelta64_ns_dtype (arr_or_dtype)
Check whether the provided array or dtype is of the timedelta64[ns] dtype.
This is a very specific dtype, so generic ones like `np.timedelta64`
will return False if passed into this function.
Parameters
----------
arr_or_dtype : array-like or dtype
    The array or dtype to check.
Returns
-------
boolean
    Whether or not the array or dtype is of the timedelta64[ns] dtype.
Examples
--------
>>> from pandas.core.dtypes.common import is_timedelta64_ns_dtype
>>> is_timedelta64_ns_dtype(np.dtype('m8[ns]'))
True
>>> is_timedelta64_ns_dtype(np.dtype('m8[ps]'))  # Wrong frequency
False
>>> is_timedelta64_ns_dtype(np.array([1, 2], dtype='m8[ns]'))
True
>>> is_timedelta64_ns_dtype(np.array([1, 2], dtype=np.timedelta64))
False
Definition at line 961 of file common.py.
References _is_dtype().
is_unsigned_integer_dtype()
bool pandas.core.dtypes.common.is_unsigned_integer_dtype (arr_or_dtype)
Check whether the provided array or dtype is of an unsigned integer dtype.
The nullable Integer dtypes (e.g. pandas.UInt64Dtype) are also
considered as integer by this function.
Parameters
----------
arr_or_dtype : array-like or dtype
    The array or dtype to check.
Returns
-------
boolean
    Whether or not the array or dtype is of an unsigned integer dtype.
Examples
--------
>>> from pandas.api.types import is_unsigned_integer_dtype
>>> is_unsigned_integer_dtype(str)
False
>>> is_unsigned_integer_dtype(int)  # signed
False
>>> is_unsigned_integer_dtype(float)
False
>>> is_unsigned_integer_dtype(np.uint64)
True
>>> is_unsigned_integer_dtype('uint8')
True
>>> is_unsigned_integer_dtype('UInt8')
True
>>> is_unsigned_integer_dtype(pd.UInt8Dtype)
True
>>> is_unsigned_integer_dtype(np.array(['a', 'b']))
False
>>> is_unsigned_integer_dtype(pd.Series([1, 2]))  # signed
False
>>> is_unsigned_integer_dtype(pd.Index([1, 2.]))  # float
False
>>> is_unsigned_integer_dtype(np.array([1, 2], dtype=np.uint32))
True
Definition at line 751 of file common.py.
References _classes_and_not_datetimelike(), _is_dtype(), and _is_dtype_type().
needs_i8_conversion()
bool pandas.core.dtypes.common.needs_i8_conversion (DtypeObj | None dtype)
Check whether the dtype should be converted to int64.
Dtype "needs" such a conversion if the dtype is of a datetime-like dtype
Parameters
----------
dtype : np.dtype, ExtensionDtype, or None
Returns
-------
boolean
    Whether or not the dtype should be converted to int64.
Examples
--------
>>> needs_i8_conversion(str)
False
>>> needs_i8_conversion(np.int64)
False
>>> needs_i8_conversion(np.datetime64)
False
>>> needs_i8_conversion(np.dtype(np.datetime64))
True
>>> needs_i8_conversion(np.array(['a', 'b']))
False
>>> needs_i8_conversion(pd.Series([1, 2]))
False
>>> needs_i8_conversion(pd.Series([], dtype="timedelta64[ns]"))
False
>>> needs_i8_conversion(pd.DatetimeIndex([1, 2, 3], tz="US/Eastern"))
False
>>> needs_i8_conversion(pd.DatetimeIndex([1, 2, 3], tz="US/Eastern").dtype)
True
Definition at line 1042 of file common.py.
pandas_dtype()
DtypeObj pandas.core.dtypes.common.pandas_dtype (dtype)
Convert input into a pandas only dtype object or a numpy dtype object.
Parameters
----------
dtype : object to be converted
Returns
-------
np.dtype or a pandas dtype
Raises
------
TypeError if not a dtype
Examples
--------
>>> pd.api.types.pandas_dtype(int)
dtype('int64')
Definition at line 1606 of file common.py.
Referenced by _get_dtype(), _is_dtype_type(), infer_dtype_from_object(), and is_extension_array_dtype().
validate_all_hashable()
None pandas.core.dtypes.common.validate_all_hashable (* args, str | None error_name = None)
Return None if all args are hashable, else raise a TypeError.
Parameters
----------
*args
    Arguments to validate.
error_name : str, optional
    The name to use if error
Raises
------
TypeError : If an argument is not hashable
Returns
-------
None
Definition at line 1581 of file common.py.
Variable Documentation
__all__
list pandas.core.dtypes.common.__all__ private
Definition at line 1711 of file common.py.
_is_scipy_sparse
pandas.core.dtypes.common._is_scipy_sparse = None protected
Definition at line 70 of file common.py.
DT64NS_DTYPE
pandas.core.dtypes.common.DT64NS_DTYPE = conversion.DT64NS_DTYPE
Definition at line 65 of file common.py.
ensure_float64
pandas.core.dtypes.common.ensure_float64 = algos.ensure_float64
Definition at line 72 of file common.py.
ensure_int16
pandas.core.dtypes.common.ensure_int16 = algos.ensure_int16
Definition at line 75 of file common.py.
ensure_int32
pandas.core.dtypes.common.ensure_int32 = algos.ensure_int32
Definition at line 74 of file common.py.
ensure_int64
pandas.core.dtypes.common.ensure_int64 = algos.ensure_int64
Definition at line 73 of file common.py.
ensure_int8
pandas.core.dtypes.common.ensure_int8 = algos.ensure_int8
Definition at line 76 of file common.py.
ensure_object
pandas.core.dtypes.common.ensure_object = algos.ensure_object
Definition at line 78 of file common.py.
ensure_platform_int
pandas.core.dtypes.common.ensure_platform_int = algos.ensure_platform_int
Definition at line 77 of file common.py.
ensure_uint64
pandas.core.dtypes.common.ensure_uint64 = algos.ensure_uint64
Definition at line 79 of file common.py.
INT64_DTYPE
pandas.core.dtypes.common.INT64_DTYPE = np.dtype(np.int64)
Definition at line 67 of file common.py.
TD64NS_DTYPE
pandas.core.dtypes.common.TD64NS_DTYPE = conversion.TD64NS_DTYPE
Definition at line 66 of file common.py.