Code Cloning Analysis: pandas.tests.plotting.test_converter.TestPeriodConverter Class Reference
pandas.tests.plotting.test_converter.TestPeriodConverter Class Reference
Public Member Functions
pc (self)
axis (self)
test_convert_accepts_unicode (self, pc, axis)
test_conversion (self, pc, axis)
test_integer_passthrough (self, pc, axis)
test_convert_nested (self, pc, axis)
Detailed Description
Definition at line 287 of file test_converter.py.
Member Function Documentation
axis()
pandas.tests.plotting.test_converter.TestPeriodConverter.axis (self)
Definition at line 293 of file test_converter.py.
Referenced by pandas.core.groupby.groupby.BaseGroupBy.__iter__(), axes_grid1.parasite_axes.HostAxesBase._add_twin_axes(), pandas.core.groupby.groupby.BaseGroupBy.get_group(), axes_grid1.parasite_axes.HostAxesBase.twin(), axes_grid1.parasite_axes.HostAxesBase.twinx(), and axes_grid1.parasite_axes.HostAxesBase.twiny().
pc()
pandas.tests.plotting.test_converter.TestPeriodConverter.pc (self)
Definition at line 289 of file test_converter.py.
test_conversion()
pandas.tests.plotting.test_converter.TestPeriodConverter.test_conversion (self, pc, axis)
Definition at line 306 of file test_converter.py.
test_convert_accepts_unicode()
pandas.tests.plotting.test_converter.TestPeriodConverter.test_convert_accepts_unicode (self, pc, axis)
Definition at line 301 of file test_converter.py.
test_convert_nested()
pandas.tests.plotting.test_converter.TestPeriodConverter.test_convert_nested (self, pc, axis)
Definition at line 348 of file test_converter.py.
test_integer_passthrough()
pandas.tests.plotting.test_converter.TestPeriodConverter.test_integer_passthrough (self, pc, axis)
Definition at line 342 of file test_converter.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/tests/plotting/test_converter.py