Code Cloning Analysis: fontTools.ttLib.tables.S__i_l_f.Silf Class Reference
fontTools.ttLib.tables.S__i_l_f.Silf Class Reference
Public Member Functions
__init__ (self)
decompile (self, data, ttFont, version=2.0)
compile (self, ttFont, version=2.0)
toXML (self, writer, ttFont, version=2.0)
fromXML (self, name, attrs, content, ttFont, version=2.0)
Public Attributes
list passes = []
list scriptTags = []
list critFeatures = []
list jLevels = []
dict pMap = {}
ruleVersion
numJLevels = sstruct.unpack2(Silf_part1_format, data, self)
numCritFeatures = sstruct.unpack2(Silf_part2_format, data, self)
lbGID = data[1 + 4 * numScriptTag :]
numPasses = struct.unpack(">H", data[:2])
oPasses
classes = Classes()
passOffset = len(data)
pseudosOffset = currpos + len(data1)
Detailed Description
A particular Silf subtable
Definition at line 429 of file S__i_l_f.py.
Constructor & Destructor Documentation
__init__()
fontTools.ttLib.tables.S__i_l_f.Silf.__init__ (self)
Definition at line 432 of file S__i_l_f.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
compile()
fontTools.ttLib.tables.S__i_l_f.Silf.compile (self, ttFont, version = 2.0)
Definition at line 506 of file S__i_l_f.py.
Referenced by fontTools.ttLib.tables.TupleVariation.TupleVariation.getCoordWidth(), and PIL.FontFile.FontFile.save().
decompile()
fontTools.ttLib.tables.S__i_l_f.Silf.decompile (self, data, ttFont, version = 2.0)
Definition at line 439 of file S__i_l_f.py.
Referenced by fontTools.ttLib.tables._c_m_a_p.CmapSubtable.newSubtable().
fromXML()
fontTools.ttLib.tables.S__i_l_f.Silf.fromXML (self, name, attrs, content, ttFont, version = 2.0)
Definition at line 605 of file S__i_l_f.py.
toXML()
fontTools.ttLib.tables.S__i_l_f.Silf.toXML (self, writer, ttFont, version = 2.0)
Definition at line 552 of file S__i_l_f.py.
Member Data Documentation
classes
fontTools.ttLib.tables.S__i_l_f.Silf.classes = Classes()
Definition at line 495 of file S__i_l_f.py.
Referenced by sklearn.preprocessing._label.MultiLabelBinarizer.fit(), sklearn.preprocessing._label.MultiLabelBinarizer.fit_transform(), sklearn.calibration._CalibratedClassifier.predict_proba(), and pandas.io.formats.html.HTMLFormatter.write_th().
critFeatures
fontTools.ttLib.tables.S__i_l_f.Silf.critFeatures = []
Definition at line 435 of file S__i_l_f.py.
jLevels
fontTools.ttLib.tables.S__i_l_f.Silf.jLevels = []
Definition at line 436 of file S__i_l_f.py.
lbGID
fontTools.ttLib.tables.S__i_l_f.Silf.lbGID = data[1 + 4 * numScriptTag :]
Definition at line 462 of file S__i_l_f.py.
numCritFeatures
fontTools.ttLib.tables.S__i_l_f.Silf.numCritFeatures = sstruct.unpack2(Silf_part2_format, data, self)
Definition at line 450 of file S__i_l_f.py.
numJLevels
fontTools.ttLib.tables.S__i_l_f.Silf.numJLevels = sstruct.unpack2(Silf_part1_format, data, self)
Definition at line 446 of file S__i_l_f.py.
numPasses
fontTools.ttLib.tables.S__i_l_f.Silf.numPasses = struct.unpack(">H", data[:2])
Definition at line 463 of file S__i_l_f.py.
oPasses
fontTools.ttLib.tables.S__i_l_f.Silf.oPasses
Initial value:
=  struct.unpack(
                (">%dL" % (self.numPasses + 1)), data[2 : 6 + 4 * self.numPasses]
            )
Definition at line 464 of file S__i_l_f.py.
passes
fontTools.ttLib.tables.S__i_l_f.Silf.passes = []
Definition at line 433 of file S__i_l_f.py.
passOffset
fontTools.ttLib.tables.S__i_l_f.Silf.passOffset = len(data)
Definition at line 527 of file S__i_l_f.py.
pMap
dict fontTools.ttLib.tables.S__i_l_f.Silf.pMap = {}
Definition at line 437 of file S__i_l_f.py.
pseudosOffset
fontTools.ttLib.tables.S__i_l_f.Silf.pseudosOffset = currpos + len(data1)
Definition at line 531 of file S__i_l_f.py.
ruleVersion
fontTools.ttLib.tables.S__i_l_f.Silf.ruleVersion
Initial value:
=  float(
                floatToFixedToStr(self.ruleVersion, precisionBits=16)
            )
Definition at line 442 of file S__i_l_f.py.
scriptTags
fontTools.ttLib.tables.S__i_l_f.Silf.scriptTags = []
Definition at line 434 of file S__i_l_f.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ttLib/tables/S__i_l_f.py