Code Cloning Analysis: fontTools.ttLib.tables.M_E_T_A_.table_M_E_T_A_ Class Reference
fontTools.ttLib.tables.M_E_T_A_.table_M_E_T_A_ Class Reference
Public Member Functions
decompile (self, data, ttFont)
compile (self, ttFont)
toXML (self, writer, ttFont)
fromXML (self, name, attrs, content, ttFont)
Public Member Functions inherited from fontTools.ttLib.tables.DefaultTable.DefaultTable
__init__ (self, tag=None)
__repr__ (self)
__eq__ (self, other)
__ne__ (self, other)
Public Attributes
list glyphRecords = []
nMetaRecs
int metaFlags = 0:
Public Attributes inherited from fontTools.ttLib.tables.DefaultTable.DefaultTable
tableTag = Tag(tag)
data = data
ERROR
Additional Inherited Members
Static Public Attributes inherited from fontTools.ttLib.tables.DefaultTable.DefaultTable
list dependencies = []
Detailed Description
Glyphlets META table
The ``META`` table is used by Adobe's SING Glyphlets.
See also https://web.archive.org/web/20080627183635/http://www.adobe.com/devnet/opentype/gdk/topic.html
Definition at line 70 of file M_E_T_A_.py.
Member Function Documentation
compile()
fontTools.ttLib.tables.M_E_T_A_.table_M_E_T_A_.compile (self, ttFont)
Reimplemented from fontTools.ttLib.tables.DefaultTable.DefaultTable.
Definition at line 116 of file M_E_T_A_.py.
Referenced by fontTools.ttLib.tables.TupleVariation.TupleVariation.getCoordWidth(), and PIL.FontFile.FontFile.save().
decompile()
fontTools.ttLib.tables.M_E_T_A_.table_M_E_T_A_.decompile (self, data, ttFont)
Reimplemented from fontTools.ttLib.tables.DefaultTable.DefaultTable.
Definition at line 80 of file M_E_T_A_.py.
Referenced by fontTools.ttLib.tables._c_m_a_p.CmapSubtable.newSubtable().
fromXML()
fontTools.ttLib.tables.M_E_T_A_.table_M_E_T_A_.fromXML (self, name, attrs, content, ttFont)
Reimplemented from fontTools.ttLib.tables.DefaultTable.DefaultTable.
Definition at line 197 of file M_E_T_A_.py.
toXML()
fontTools.ttLib.tables.M_E_T_A_.table_M_E_T_A_.toXML (self, writer, ttFont)
Reimplemented from fontTools.ttLib.tables.DefaultTable.DefaultTable.
Definition at line 184 of file M_E_T_A_.py.
Member Data Documentation
glyphRecords
list fontTools.ttLib.tables.M_E_T_A_.table_M_E_T_A_.glyphRecords = []
Definition at line 82 of file M_E_T_A_.py.
metaFlags
fontTools.ttLib.tables.M_E_T_A_.table_M_E_T_A_.metaFlags = 0:
Definition at line 87 of file M_E_T_A_.py.
nMetaRecs
fontTools.ttLib.tables.M_E_T_A_.table_M_E_T_A_.nMetaRecs
Definition at line 83 of file M_E_T_A_.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ttLib/tables/M_E_T_A_.py