Code Cloning Analysis: sklearn.utils.estimator_checks Namespace Reference
sklearn.utils.estimator_checks Namespace Reference
Classes
class _NotAnArray
Functions
_raise_for_missing_tags (estimator, tag_name, Mixin)
_yield_api_checks (estimator)
_yield_checks (estimator)
_yield_classifier_checks (classifier)
_yield_regressor_checks (regressor)
_yield_transformer_checks (transformer)
_yield_clustering_checks (clusterer)
_yield_outliers_checks (estimator)
_yield_array_api_checks (estimator)
_yield_all_checks (estimator, bool legacy)
_check_name (check)
_maybe_mark (estimator, check, dict[str, str]|None expected_failed_checks=None, Literal["xfail", "skip", None] mark=None, pytest=None)
tuple[bool, str] _should_be_skipped_or_marked (estimator, check, dict[str, str]|None expected_failed_checks=None)
estimator_checks_generator (estimator, *, bool legacy=True, dict[str, str]|None expected_failed_checks=None, Literal["xfail", "skip", None] mark=None)
parametrize_with_checks (estimators, *, bool legacy=True, Callable|None expected_failed_checks=None)
check_estimator (estimator=None, generate_only=False, *, bool legacy=True, dict[str, str]|None expected_failed_checks=None, Literal["warn"]|None on_skip="warn", Literal["raise", "warn"]|None on_fail="raise", Callable|None callback=None)
_regression_dataset ()
_is_pairwise_metric (estimator)
_generate_sparse_data (X_csr)
check_supervised_y_no_nan (name, estimator_orig)
check_array_api_input (name, estimator_orig, array_namespace, device=None, dtype_name="float64", check_values=False)
check_array_api_input_and_values (name, estimator_orig, array_namespace, device=None, dtype_name="float64")
check_estimator_sparse_tag (name, estimator_orig)
_check_estimator_sparse_container (name, estimator_orig, sparse_type)
check_estimator_sparse_matrix (name, estimator_orig)
check_estimator_sparse_array (name, estimator_orig)
check_f_contiguous_array_estimator (name, estimator_orig)
check_sample_weights_pandas_series (name, estimator_orig)
check_sample_weights_not_an_array (name, estimator_orig)
check_sample_weights_list (name, estimator_orig)
check_sample_weights_shape (name, estimator_orig)
_check_sample_weight_equivalence (name, estimator_orig, sparse_container)
check_sample_weight_equivalence_on_dense_data (name, estimator_orig)
check_sample_weight_equivalence_on_sparse_data (name, estimator_orig)
check_sample_weights_not_overwritten (name, estimator_orig)
check_dtype_object (name, estimator_orig)
check_complex_data (name, estimator_orig)
check_dict_unchanged (name, estimator_orig)
_is_public_parameter (attr)
check_dont_overwrite_parameters (name, estimator_orig)
check_fit2d_predict1d (name, estimator_orig)
_apply_on_subsets (func, X)
check_methods_subset_invariance (name, estimator_orig)
check_methods_sample_order_invariance (name, estimator_orig)
check_fit2d_1sample (name, estimator_orig)
check_fit2d_1feature (name, estimator_orig)
check_fit1d (name, estimator_orig)
check_transformer_general (name, transformer, readonly_memmap=False)
check_transformer_data_not_an_array (name, transformer)
check_transformers_unfitted (name, transformer)
check_transformers_unfitted_stateless (name, transformer)
_check_transformer (name, transformer_orig, X, y)
check_pipeline_consistency (name, estimator_orig)
check_mixin_order (name, estimator_orig)
check_fit_score_takes_y (name, estimator_orig)
check_estimators_dtypes (name, estimator_orig)
check_transformer_preserve_dtypes (name, transformer_orig)
check_estimators_empty_data_messages (name, estimator_orig)
check_estimators_nan_inf (name, estimator_orig)
check_nonsquare_error (name, estimator_orig)
check_estimators_pickle (name, estimator_orig, readonly_memmap=False)
check_estimators_partial_fit_n_features (name, estimator_orig)
check_classifier_multioutput (name, estimator_orig)
check_regressor_multioutput (name, estimator)
check_clustering (name, clusterer_orig, readonly_memmap=False)
check_clusterer_compute_labels_predict (name, clusterer_orig)
check_classifiers_one_label (name, classifier_orig)
check_classifiers_one_label_sample_weights (name, classifier_orig)
check_classifiers_train (name, classifier_orig, readonly_memmap=False, X_dtype="float64")
check_outlier_corruption (num_outliers, expected_outliers, decision)
check_outliers_train (name, estimator_orig, readonly_memmap=True)
check_outlier_contamination (name, estimator_orig)
check_classifiers_multilabel_representation_invariance (name, classifier_orig)
check_classifiers_multilabel_output_format_predict (name, classifier_orig)
check_classifiers_multilabel_output_format_predict_proba (name, classifier_orig)
check_classifiers_multilabel_output_format_decision_function (name, classifier_orig)
check_get_feature_names_out_error (name, estimator_orig)
check_estimators_fit_returns_self (name, estimator_orig)
check_readonly_memmap_input (name, estimator_orig)
check_estimators_unfitted (name, estimator_orig)
check_supervised_y_2d (name, estimator_orig)
check_classifiers_predictions (X, y, name, classifier_orig)
_choose_check_classifiers_labels (name, y, y_names)
check_classifiers_classes (name, classifier_orig)
check_regressors_int (name, regressor_orig)
check_regressors_train (name, regressor_orig, readonly_memmap=False, X_dtype=np.float64)
check_regressors_no_decision_function (name, regressor_orig)
check_class_weight_classifiers (name, classifier_orig)
check_class_weight_balanced_classifiers (name, classifier_orig, X_train, y_train, X_test, y_test, weights)
check_class_weight_balanced_linear_classifier (name, estimator_orig)
check_estimators_overwrite_params (name, estimator_orig)
check_no_attributes_set_in_init (name, estimator_orig)
check_sparsify_coefficients (name, estimator_orig)
check_classifier_data_not_an_array (name, estimator_orig)
check_regressor_data_not_an_array (name, estimator_orig)
check_estimators_data_not_an_array (name, estimator_orig, X, y, obj_type)
check_estimator_cloneable (name, estimator_orig)
check_estimator_repr (name, estimator_orig)
check_parameters_default_constructible (name, estimator_orig)
_enforce_estimator_tags_y (estimator, y)
_enforce_estimator_tags_X (estimator, X, X_test=None, kernel=linear_kernel)
check_positive_only_tag_during_fit (name, estimator_orig)
check_non_transformer_estimators_n_iter (name, estimator_orig)
check_transformer_n_iter (name, estimator_orig)
check_get_params_invariance (name, estimator_orig)
check_set_params (name, estimator_orig)
check_classifiers_regression_target (name, estimator_orig)
check_decision_proba_consistency (name, estimator_orig)
check_outliers_fit_predict (name, estimator_orig)
check_fit_non_negative (name, estimator_orig)
check_fit_idempotent (name, estimator_orig)
check_fit_check_is_fitted (name, estimator_orig)
check_n_features_in (name, estimator_orig)
check_requires_y_none (name, estimator_orig)
check_n_features_in_after_fitting (name, estimator_orig)
check_valid_tag_types (name, estimator)
check_estimator_tags_renamed (name, estimator_orig)
check_dataframe_column_names_consistency (name, estimator_orig)
check_transformer_get_feature_names_out (name, transformer_orig)
check_transformer_get_feature_names_out_pandas (name, transformer_orig)
check_param_validation (name, estimator_orig)
check_set_output_transform (name, transformer_orig)
_output_from_fit_transform (transformer, name, X, df, y)
_check_generated_dataframe (name, case, index, outputs_default, outputs_dataframe_lib, is_supported_dataframe, create_dataframe, assert_frame_equal)
_check_set_output_transform_dataframe (name, transformer_orig, *, dataframe_lib, is_supported_dataframe, create_dataframe, assert_frame_equal, context)
_check_set_output_transform_pandas_context (name, transformer_orig, context)
check_set_output_transform_pandas (name, transformer_orig)
check_global_output_transform_pandas (name, transformer_orig)
_check_set_output_transform_polars_context (name, transformer_orig, context)
check_set_output_transform_polars (name, transformer_orig)
check_global_set_output_transform_polars (name, transformer_orig)
check_inplace_ensure_writeable (name, estimator_orig)
check_do_not_raise_errors_in_init_or_set_params (name, estimator_orig)
check_classifier_not_supporting_multiclass (name, estimator_orig)
Variables
REGRESSION_DATASET = None
Detailed Description
Various utilities to check the compatibility of estimators with scikit-learn API.
Function Documentation
_apply_on_subsets()
sklearn.utils.estimator_checks._apply_on_subsets (func, X) protected
Definition at line 1787 of file estimator_checks.py.
_check_estimator_sparse_container()
sklearn.utils.estimator_checks._check_estimator_sparse_container (name, estimator_orig, sparse_type) protected
Definition at line 1292 of file estimator_checks.py.
_check_generated_dataframe()
sklearn.utils.estimator_checks._check_generated_dataframe (name, case, index, outputs_default, outputs_dataframe_lib, is_supported_dataframe, create_dataframe, assert_frame_equal) protected
Check if the generated DataFrame by the transformer is valid.
The DataFrame implementation is specified through the parameters of this function.
Parameters
----------
name : str
    The name of the transformer.
case : str
    A single case from the cases generated by `_output_from_fit_transform`.
index : index or None
    The index of the DataFrame. `None` if the library does not implement a DataFrame
    with an index.
outputs_default : tuple
    A tuple containing the output data and feature names for the default output.
outputs_dataframe_lib : tuple
    A tuple containing the output data and feature names for the pandas case.
is_supported_dataframe : callable
    A callable that takes a DataFrame instance as input and return whether or
    E.g. `lambda X: isintance(X, pd.DataFrame)`.
create_dataframe : callable
    A callable taking as parameters `data`, `columns`, and `index` and returns
    a callable. Be aware that `index` can be ignored. For example, polars dataframes
    would ignore the idnex.
assert_frame_equal : callable
    A callable taking 2 dataframes to compare if they are equal.
Definition at line 5041 of file estimator_checks.py.
Referenced by _check_set_output_transform_dataframe().
_check_name()
sklearn.utils.estimator_checks._check_name (check) protected
Definition at line 417 of file estimator_checks.py.
_check_sample_weight_equivalence()
sklearn.utils.estimator_checks._check_sample_weight_equivalence (name, estimator_orig, sparse_container) protected
Definition at line 1506 of file estimator_checks.py.
_check_set_output_transform_dataframe()
sklearn.utils.estimator_checks._check_set_output_transform_dataframe (name, transformer_orig, * , dataframe_lib, is_supported_dataframe, create_dataframe, assert_frame_equal, context) protected
Check that a transformer can output a DataFrame when requested.
The DataFrame implementation is specified through the parameters of this function.
Parameters
----------
name : str
    The name of the transformer.
transformer_orig : estimator
    The original transformer instance.
dataframe_lib : str
    The name of the library implementing the DataFrame.
is_supported_dataframe : callable
    A callable that takes a DataFrame instance as input and returns whether or
    not it is supported by the dataframe library.
    E.g. `lambda X: isintance(X, pd.DataFrame)`.
create_dataframe : callable
    A callable taking as parameters `data`, `columns`, and `index` and returns
    a callable. Be aware that `index` can be ignored. For example, polars dataframes
    will ignore the index.
assert_frame_equal : callable
    A callable taking 2 dataframes to compare if they are equal.
context : {"local", "global"}
    Whether to use a local context by setting `set_output(...)` on the transformer
    or a global context by using the `with config_context(...)`
Definition at line 5102 of file estimator_checks.py.
References _check_generated_dataframe(), _check_set_output_transform_dataframe(), and _output_from_fit_transform().
Referenced by _check_set_output_transform_dataframe().
_check_set_output_transform_pandas_context()
sklearn.utils.estimator_checks._check_set_output_transform_pandas_context (name, transformer_orig, context) protected
Definition at line 5192 of file estimator_checks.py.
_check_set_output_transform_polars_context()
sklearn.utils.estimator_checks._check_set_output_transform_polars_context (name, transformer_orig, context) protected
Definition at line 5219 of file estimator_checks.py.
_check_transformer()
sklearn.utils.estimator_checks._check_transformer (name, transformer_orig, X, y) protected
Definition at line 2046 of file estimator_checks.py.
_choose_check_classifiers_labels()
sklearn.utils.estimator_checks._choose_check_classifiers_labels (name, y, y_names) protected
Definition at line 3346 of file estimator_checks.py.
_enforce_estimator_tags_X()
sklearn.utils.estimator_checks._enforce_estimator_tags_X (estimator, X, X_test = None, kernel = linear_kernel) protected
Definition at line 3942 of file estimator_checks.py.
_enforce_estimator_tags_y()
sklearn.utils.estimator_checks._enforce_estimator_tags_y (estimator, y) protected
Definition at line 3921 of file estimator_checks.py.
_generate_sparse_data()
sklearn.utils.estimator_checks._generate_sparse_data (X_csr) protected
Generate sparse matrices or arrays with {32,64}bit indices of diverse format.
Parameters
----------
X_csr: scipy.sparse.csr_matrix or scipy.sparse.csr_array
    Input in CSR format.
Returns
-------
out: iter(Matrices) or iter(Arrays)
    In format['dok', 'lil', 'dia', 'bsr', 'csr', 'csc', 'coo',
    'coo_64', 'csc_64', 'csr_64']
Definition at line 977 of file estimator_checks.py.
Referenced by check_estimator_sparse_tag().
_is_pairwise_metric()
sklearn.utils.estimator_checks._is_pairwise_metric (estimator) protected
Returns True if estimator accepts pairwise metric.
Parameters
----------
estimator : object
    Estimator object to test.
Returns
-------
out : bool
    True if _pairwise is set to True and False otherwise.
Definition at line 959 of file estimator_checks.py.
Referenced by check_estimator_repr(), and check_estimators_pickle().
_is_public_parameter()
sklearn.utils.estimator_checks._is_public_parameter (attr) protected
Definition at line 1702 of file estimator_checks.py.
_maybe_mark()
sklearn.utils.estimator_checks._maybe_mark (estimator, check, dict[str, str] | None expected_failed_checks = None, Literal["xfail", "skip", None] mark = None, pytest = None) protected
Mark the test as xfail or skip if needed.
Parameters
----------
estimator : estimator object
    Estimator instance for which to generate checks.
check : partial or callable
    Check to be marked.
expected_failed_checks : dict[str, str], default=None
    Dictionary of the form {check_name: reason} for checks that are expected to
    fail.
mark : "xfail" or "skip" or None
    Whether to mark the check as xfail or skip.
pytest : pytest module, default=None
    Pytest module to use to mark the check. This is only needed if ``mark`` is
    `"xfail"`. Note that one can run `check_estimator` without having `pytest`
    installed. This is used in combination with `parametrize_with_checks` only.
Definition at line 423 of file estimator_checks.py.
References _should_be_skipped_or_marked().
Referenced by estimator_checks_generator().
_output_from_fit_transform()
sklearn.utils.estimator_checks._output_from_fit_transform (transformer, name, X, df, y) protected
Generate output to test `set_output` for different configuration:
- calling either `fit.transform` or `fit_transform`;
- passing either a dataframe or a numpy array to fit;
- passing either a dataframe or a numpy array to transform.
Definition at line 4996 of file estimator_checks.py.
Referenced by _check_set_output_transform_dataframe().
_raise_for_missing_tags()
sklearn.utils.estimator_checks._raise_for_missing_tags (estimator, tag_name, Mixin) protected
Definition at line 113 of file estimator_checks.py.
_regression_dataset()
sklearn.utils.estimator_checks._regression_dataset () protected
Definition at line 922 of file estimator_checks.py.
_should_be_skipped_or_marked()
tuple[bool, str] sklearn.utils.estimator_checks._should_be_skipped_or_marked (estimator, check, dict[str, str] | None expected_failed_checks = None) protected
Check whether a check should be skipped or marked as xfail.
Parameters
----------
estimator : estimator object
    Estimator instance for which to generate checks.
check : partial or callable
    Check to be marked.
expected_failed_checks : dict[str, str], default=None
    Dictionary of the form {check_name: reason} for checks that are expected to
    fail.
Returns
-------
should_be_marked : bool
    Whether the check should be marked as xfail or skipped.
reason : str
    Reason for skipping the check.
Definition at line 468 of file estimator_checks.py.
Referenced by _maybe_mark(), and check_estimator().
_yield_all_checks()
sklearn.utils.estimator_checks._yield_all_checks (estimator, bool legacy) protected
Definition at line 355 of file estimator_checks.py.
_yield_api_checks()
sklearn.utils.estimator_checks._yield_api_checks (estimator) protected
Definition at line 125 of file estimator_checks.py.
_yield_array_api_checks()
sklearn.utils.estimator_checks._yield_array_api_checks (estimator) protected
Definition at line 341 of file estimator_checks.py.
_yield_checks()
sklearn.utils.estimator_checks._yield_checks (estimator) protected
Definition at line 153 of file estimator_checks.py.
_yield_classifier_checks()
sklearn.utils.estimator_checks._yield_classifier_checks (classifier) protected
Definition at line 208 of file estimator_checks.py.
_yield_clustering_checks()
sklearn.utils.estimator_checks._yield_clustering_checks (clusterer) protected
Definition at line 310 of file estimator_checks.py.
_yield_outliers_checks()
sklearn.utils.estimator_checks._yield_outliers_checks (estimator) protected
Definition at line 323 of file estimator_checks.py.
_yield_regressor_checks()
sklearn.utils.estimator_checks._yield_regressor_checks (regressor) protected
Definition at line 255 of file estimator_checks.py.
_yield_transformer_checks()
sklearn.utils.estimator_checks._yield_transformer_checks (transformer) protected
Definition at line 279 of file estimator_checks.py.
check_array_api_input()
sklearn.utils.estimator_checks.check_array_api_input (name, estimator_orig, array_namespace, device = None, dtype_name = "float64", check_values = False)
Check that the estimator can work consistently with the Array API
By default, this just checks that the types and shapes of the arrays are
consistent with calling the same estimator with numpy arrays.
When check_values is True, it also checks that calling the estimator on the
array_api Array gives the same results as ndarrays.
Definition at line 1045 of file estimator_checks.py.
References check_array_api_input().
Referenced by check_array_api_input().
check_array_api_input_and_values()
sklearn.utils.estimator_checks.check_array_api_input_and_values (name, estimator_orig, array_namespace, device = None, dtype_name = "float64")
Definition at line 1223 of file estimator_checks.py.
check_class_weight_balanced_classifiers()
sklearn.utils.estimator_checks.check_class_weight_balanced_classifiers (name, classifier_orig, X_train, y_train, X_test, y_test, weights)
Definition at line 3532 of file estimator_checks.py.
check_class_weight_balanced_linear_classifier()
sklearn.utils.estimator_checks.check_class_weight_balanced_linear_classifier (name, estimator_orig)
Test class weights with non-contiguous class labels.
Definition at line 3554 of file estimator_checks.py.
check_class_weight_classifiers()
sklearn.utils.estimator_checks.check_class_weight_classifiers (name, classifier_orig)
Definition at line 3487 of file estimator_checks.py.
check_classifier_data_not_an_array()
sklearn.utils.estimator_checks.check_classifier_data_not_an_array (name, estimator_orig)
Definition at line 3697 of file estimator_checks.py.
check_classifier_multioutput()
sklearn.utils.estimator_checks.check_classifier_multioutput (name, estimator_orig)
Definition at line 2471 of file estimator_checks.py.
check_classifier_not_supporting_multiclass()
sklearn.utils.estimator_checks.check_classifier_not_supporting_multiclass (name, estimator_orig)
Check that if the classifier has tags.classifier_tags.multi_class=False,
then it should raise a ValueError when calling fit with a multiclass dataset.
This test is not yielded if the tag is not False.
Definition at line 5313 of file estimator_checks.py.
check_classifiers_classes()
sklearn.utils.estimator_checks.check_classifiers_classes (name, classifier_orig)
Definition at line 3356 of file estimator_checks.py.
check_classifiers_multilabel_output_format_decision_function()
sklearn.utils.estimator_checks.check_classifiers_multilabel_output_format_decision_function (name, classifier_orig)
Check the output of the `decision_function` method for classifiers supporting
multilabel-indicator targets.
Definition at line 3128 of file estimator_checks.py.
check_classifiers_multilabel_output_format_predict()
sklearn.utils.estimator_checks.check_classifiers_multilabel_output_format_predict (name, classifier_orig)
Check the output of the `predict` method for classifiers supporting
multilabel-indicator targets.
Definition at line 2997 of file estimator_checks.py.
check_classifiers_multilabel_output_format_predict_proba()
sklearn.utils.estimator_checks.check_classifiers_multilabel_output_format_predict_proba (name, classifier_orig)
Check the output of the `predict_proba` method for classifiers supporting
multilabel-indicator targets.
Definition at line 3043 of file estimator_checks.py.
check_classifiers_multilabel_representation_invariance()
sklearn.utils.estimator_checks.check_classifiers_multilabel_representation_invariance (name, classifier_orig)
Definition at line 2955 of file estimator_checks.py.
check_classifiers_one_label()
sklearn.utils.estimator_checks.check_classifiers_one_label (name, classifier_orig)
Definition at line 2634 of file estimator_checks.py.
check_classifiers_one_label_sample_weights()
sklearn.utils.estimator_checks.check_classifiers_one_label_sample_weights (name, classifier_orig)
Check that classifiers accepting sample_weight fit or throws a ValueError with
an explicit message if the problem is reduced to one class.
Definition at line 2658 of file estimator_checks.py.
check_classifiers_predictions()
sklearn.utils.estimator_checks.check_classifiers_predictions (X, y, name, classifier_orig)
Definition at line 3288 of file estimator_checks.py.
check_classifiers_regression_target()
sklearn.utils.estimator_checks.check_classifiers_regression_target (name, estimator_orig)
Definition at line 4146 of file estimator_checks.py.
check_classifiers_train()
sklearn.utils.estimator_checks.check_classifiers_train (name, classifier_orig, readonly_memmap = False, X_dtype = "float64")
Definition at line 2695 of file estimator_checks.py.
check_clusterer_compute_labels_predict()
sklearn.utils.estimator_checks.check_clusterer_compute_labels_predict (name, clusterer_orig)
Check that predict is invariant of compute_labels.
Definition at line 2619 of file estimator_checks.py.
check_clustering()
sklearn.utils.estimator_checks.check_clustering (name, clusterer_orig, readonly_memmap = False)
Definition at line 2559 of file estimator_checks.py.
check_complex_data()
sklearn.utils.estimator_checks.check_complex_data (name, estimator_orig)
Definition at line 1667 of file estimator_checks.py.
check_dataframe_column_names_consistency()
sklearn.utils.estimator_checks.check_dataframe_column_names_consistency (name, estimator_orig)
Definition at line 4588 of file estimator_checks.py.
check_decision_proba_consistency()
sklearn.utils.estimator_checks.check_decision_proba_consistency (name, estimator_orig)
Definition at line 4166 of file estimator_checks.py.
check_dict_unchanged()
sklearn.utils.estimator_checks.check_dict_unchanged (name, estimator_orig)
Definition at line 1682 of file estimator_checks.py.
check_do_not_raise_errors_in_init_or_set_params()
sklearn.utils.estimator_checks.check_do_not_raise_errors_in_init_or_set_params (name, estimator_orig)
Check that init or set_param does not raise errors.
Definition at line 5297 of file estimator_checks.py.
check_dont_overwrite_parameters()
sklearn.utils.estimator_checks.check_dont_overwrite_parameters (name, estimator_orig)
Definition at line 1707 of file estimator_checks.py.
check_dtype_object()
sklearn.utils.estimator_checks.check_dtype_object (name, estimator_orig)
Definition at line 1625 of file estimator_checks.py.
check_estimator()
sklearn.utils.estimator_checks.check_estimator (estimator = None, generate_only = False, * , bool legacy = True, dict[str, str] | None expected_failed_checks = None, Literal["warn"] | None on_skip = "warn", Literal["raise", "warn"] | None on_fail = "raise", Callable | None callback = None)
Check if estimator adheres to scikit-learn conventions.
This function will run an extensive test-suite for input validation,
shapes, etc, making sure that the estimator complies with `scikit-learn`
conventions as detailed in :ref:`rolling_your_own_estimator`.
Additional tests for classifiers, regressors, clustering or transformers
will be run if the Estimator class inherits from the corresponding mixin
from sklearn.base.
scikit-learn also provides a pytest specific decorator,
:func:`~sklearn.utils.estimator_checks.parametrize_with_checks`, making it
easier to test multiple estimators.
Checks are categorised into the following groups:
- API checks: a set of checks to ensure API compatibility with scikit-learn.
  Refer to https://scikit-learn.org/dev/developers/develop.html a requirement of
  scikit-learn estimators.
- legacy: a set of checks which gradually will be grouped into other categories.
Parameters
----------
estimator : estimator object
    Estimator instance to check.
generate_only : bool, default=False
    When `False`, checks are evaluated when `check_estimator` is called.
    When `True`, `check_estimator` returns a generator that yields
    (estimator, check) tuples. The check is run by calling
    `check(estimator)`.
    .. versionadded:: 0.22
    .. deprecated:: 1.6
        `generate_only` will be removed in 1.8. Use
        :func:`~sklearn.utils.estimator_checks.estimator_checks_generator` instead.
legacy : bool, default=True
    Whether to include legacy checks. Over time we remove checks from this category
    and move them into their specific category.
    .. versionadded:: 1.6
expected_failed_checks : dict, default=None
    A dictionary of the form::
        {
            "check_name": "this check is expected to fail because ...",
        }
    Where `"check_name"` is the name of the check, and `"my reason"` is why
    the check fails.
    .. versionadded:: 1.6
on_skip : "warn", None, default="warn"
    This parameter controls what happens when a check is skipped.
    - "warn": A :class:`~sklearn.exceptions.SkipTestWarning` is logged
      and running tests continue.
    - None: No warning is logged and running tests continue.
    .. versionadded:: 1.6
on_fail : {"raise", "warn"}, None, default="raise"
    This parameter controls what happens when a check fails.
    - "raise": The exception raised by the first failing check is raised and
      running tests are aborted. This does not included tests that are expected
      to fail.
    - "warn": A :class:`~sklearn.exceptions.EstimatorCheckFailedWarning` is logged
      and running tests continue.
    - None: No exception is raised and no warning is logged.
    Note that if ``on_fail != "raise"``, no exception is raised, even if the checks
    fail. You'd need to inspect the return result of ``check_estimator`` to check
    if any checks failed.
    .. versionadded:: 1.6
callback : callable, or None, default=None
    This callback will be called with the estimator and the check name,
    the exception (if any), the status of the check (xfail, failed, skipped,
    passed), and the reason for the expected failure if the check is
    expected to fail. The callable's signature needs to be::
        def callback(
            estimator,
            check_name: str,
            exception: Exception,
            status: Literal["xfail", "failed", "skipped", "passed"],
            expected_to_fail: bool,
            expected_to_fail_reason: str,
        )
    ``callback`` cannot be provided together with ``on_fail="raise"``.
    .. versionadded:: 1.6
Returns
-------
test_results : list
    List of dictionaries with the results of the failing tests, of the form::
        {
            "estimator": estimator,
            "check_name": check_name,
            "exception": exception,
            "status": status (one of "xfail", "failed", "skipped", "passed"),
            "expected_to_fail": expected_to_fail,
            "expected_to_fail_reason": expected_to_fail_reason,
        }
estimator_checks_generator : generator
    Generator that yields (estimator, check) tuples. Returned when
    `generate_only=True`.
    ..
        TODO(1.8): remove return value
    .. deprecated:: 1.6
        ``generate_only`` will be removed in 1.8. Use
        :func:`~sklearn.utils.estimator_checks.estimator_checks_generator` instead.
Raises
------
Exception
    If ``on_fail="raise"``, the exception raised by the first failing check is
    raised and running tests are aborted.
    Note that if ``on_fail != "raise"``, no exception is raised, even if the checks
    fail. You'd need to inspect the return result of ``check_estimator`` to check
    if any checks failed.
See Also
--------
parametrize_with_checks : Pytest specific decorator for parametrizing estimator
    checks.
estimator_checks_generator : Generator that yields (estimator, check) tuples.
Examples
--------
>>> from sklearn.utils.estimator_checks import check_estimator
>>> from sklearn.linear_model import LogisticRegression
>>> check_estimator(LogisticRegression())
[...]
Definition at line 668 of file estimator_checks.py.
References _should_be_skipped_or_marked(), and estimator_checks_generator().
check_estimator_cloneable()
sklearn.utils.estimator_checks.check_estimator_cloneable (name, estimator_orig)
Checks whether the estimator can be cloned.
Definition at line 3777 of file estimator_checks.py.
check_estimator_repr()
sklearn.utils.estimator_checks.check_estimator_repr (name, estimator_orig)
Check that the estimator has a functioning repr.
Definition at line 3785 of file estimator_checks.py.
References _is_pairwise_metric().
check_estimator_sparse_array()
sklearn.utils.estimator_checks.check_estimator_sparse_array (name, estimator_orig)
Definition at line 1350 of file estimator_checks.py.
check_estimator_sparse_matrix()
sklearn.utils.estimator_checks.check_estimator_sparse_matrix (name, estimator_orig)
Definition at line 1346 of file estimator_checks.py.
check_estimator_sparse_tag()
sklearn.utils.estimator_checks.check_estimator_sparse_tag (name, estimator_orig)
Check that estimator tag related with accepting sparse data is properly set.
Definition at line 1240 of file estimator_checks.py.
References _generate_sparse_data().
check_estimator_tags_renamed()
sklearn.utils.estimator_checks.check_estimator_tags_renamed (name, estimator_orig)
Definition at line 4566 of file estimator_checks.py.
check_estimators_data_not_an_array()
sklearn.utils.estimator_checks.check_estimators_data_not_an_array (name, estimator_orig, X, y, obj_type)
Definition at line 3731 of file estimator_checks.py.
check_estimators_dtypes()
sklearn.utils.estimator_checks.check_estimators_dtypes (name, estimator_orig)
Definition at line 2242 of file estimator_checks.py.
check_estimators_empty_data_messages()
sklearn.utils.estimator_checks.check_estimators_empty_data_messages (name, estimator_orig)
Definition at line 2299 of file estimator_checks.py.
check_estimators_fit_returns_self()
sklearn.utils.estimator_checks.check_estimators_fit_returns_self (name, estimator_orig)
Check if self is returned when calling fit.
Definition at line 3191 of file estimator_checks.py.
check_estimators_nan_inf()
sklearn.utils.estimator_checks.check_estimators_nan_inf (name, estimator_orig)
Definition at line 2323 of file estimator_checks.py.
check_estimators_overwrite_params()
sklearn.utils.estimator_checks.check_estimators_overwrite_params (name, estimator_orig)
Definition at line 3595 of file estimator_checks.py.
check_estimators_partial_fit_n_features()
sklearn.utils.estimator_checks.check_estimators_partial_fit_n_features (name, estimator_orig)
Definition at line 2442 of file estimator_checks.py.
check_estimators_pickle()
sklearn.utils.estimator_checks.check_estimators_pickle (name, estimator_orig, readonly_memmap = False)
Test that we can pickle all estimators.
Definition at line 2388 of file estimator_checks.py.
References _is_pairwise_metric().
check_estimators_unfitted()
sklearn.utils.estimator_checks.check_estimators_unfitted (name, estimator_orig)
Check that predict raises an exception in an unfitted estimator.
Unfitted estimators should raise a NotFittedError.
Definition at line 3223 of file estimator_checks.py.
check_f_contiguous_array_estimator()
sklearn.utils.estimator_checks.check_f_contiguous_array_estimator (name, estimator_orig)
Definition at line 1354 of file estimator_checks.py.
check_fit1d()
sklearn.utils.estimator_checks.check_fit1d (name, estimator_orig)
Definition at line 1960 of file estimator_checks.py.
check_fit2d_1feature()
sklearn.utils.estimator_checks.check_fit2d_1feature (name, estimator_orig)
Definition at line 1929 of file estimator_checks.py.
check_fit2d_1sample()
sklearn.utils.estimator_checks.check_fit2d_1sample (name, estimator_orig)
Definition at line 1888 of file estimator_checks.py.
check_fit2d_predict1d()
sklearn.utils.estimator_checks.check_fit2d_predict1d (name, estimator_orig)
Definition at line 1764 of file estimator_checks.py.
check_fit_check_is_fitted()
sklearn.utils.estimator_checks.check_fit_check_is_fitted (name, estimator_orig)
Definition at line 4323 of file estimator_checks.py.
check_fit_idempotent()
sklearn.utils.estimator_checks.check_fit_idempotent (name, estimator_orig)
Definition at line 4263 of file estimator_checks.py.
check_fit_non_negative()
sklearn.utils.estimator_checks.check_fit_non_negative (name, estimator_orig)
Definition at line 4253 of file estimator_checks.py.
check_fit_score_takes_y()
sklearn.utils.estimator_checks.check_fit_score_takes_y (name, estimator_orig)
Definition at line 2212 of file estimator_checks.py.
check_get_feature_names_out_error()
sklearn.utils.estimator_checks.check_get_feature_names_out_error (name, estimator_orig)
Check the error raised by get_feature_names_out when called before fit.
Unfitted estimators with get_feature_names_out should raise a NotFittedError.
Definition at line 3175 of file estimator_checks.py.
check_get_params_invariance()
sklearn.utils.estimator_checks.check_get_params_invariance (name, estimator_orig)
Definition at line 4078 of file estimator_checks.py.
check_global_output_transform_pandas()
sklearn.utils.estimator_checks.check_global_output_transform_pandas (name, transformer_orig)
Definition at line 5215 of file estimator_checks.py.
check_global_set_output_transform_polars()
sklearn.utils.estimator_checks.check_global_set_output_transform_polars (name, transformer_orig)
Definition at line 5247 of file estimator_checks.py.
check_inplace_ensure_writeable()
sklearn.utils.estimator_checks.check_inplace_ensure_writeable (name, estimator_orig)
Check that estimators able to do inplace operations can work on read-only
input data even if a copy is not explicitly requested by the user.
Make sure that a copy is made and consequently that the input array and its
writeability are not modified by the estimator.
Definition at line 5252 of file estimator_checks.py.
check_methods_sample_order_invariance()
sklearn.utils.estimator_checks.check_methods_sample_order_invariance (name, estimator_orig)
Definition at line 1843 of file estimator_checks.py.
check_methods_subset_invariance()
sklearn.utils.estimator_checks.check_methods_subset_invariance (name, estimator_orig)
Definition at line 1806 of file estimator_checks.py.
check_mixin_order()
sklearn.utils.estimator_checks.check_mixin_order (name, estimator_orig)
Check that mixins are inherited in the correct order.
Definition at line 2171 of file estimator_checks.py.
check_n_features_in()
sklearn.utils.estimator_checks.check_n_features_in (name, estimator_orig)
Definition at line 4362 of file estimator_checks.py.
check_n_features_in_after_fitting()
sklearn.utils.estimator_checks.check_n_features_in_after_fitting (name, estimator_orig)
Definition at line 4415 of file estimator_checks.py.
check_no_attributes_set_in_init()
sklearn.utils.estimator_checks.check_no_attributes_set_in_init (name, estimator_orig)
Check setting during init.
Definition at line 3629 of file estimator_checks.py.
check_non_transformer_estimators_n_iter()
sklearn.utils.estimator_checks.check_non_transformer_estimators_n_iter (name, estimator_orig)
Definition at line 4023 of file estimator_checks.py.
check_nonsquare_error()
sklearn.utils.estimator_checks.check_nonsquare_error (name, estimator_orig)
Test that error is thrown when non-square data provided.
Definition at line 2372 of file estimator_checks.py.
check_outlier_contamination()
sklearn.utils.estimator_checks.check_outlier_contamination (name, estimator_orig)
Definition at line 2927 of file estimator_checks.py.
check_outlier_corruption()
sklearn.utils.estimator_checks.check_outlier_corruption (num_outliers, expected_outliers, decision)
Definition at line 2833 of file estimator_checks.py.
check_outliers_fit_predict()
sklearn.utils.estimator_checks.check_outliers_fit_predict (name, estimator_orig)
Definition at line 4210 of file estimator_checks.py.
check_outliers_train()
sklearn.utils.estimator_checks.check_outliers_train (name, estimator_orig, readonly_memmap = True)
Definition at line 2855 of file estimator_checks.py.
check_param_validation()
sklearn.utils.estimator_checks.check_param_validation (name, estimator_orig)
Definition at line 4834 of file estimator_checks.py.
check_parameters_default_constructible()
sklearn.utils.estimator_checks.check_parameters_default_constructible (name, estimator_orig)
Definition at line 3794 of file estimator_checks.py.
check_pipeline_consistency()
sklearn.utils.estimator_checks.check_pipeline_consistency (name, estimator_orig)
Definition at line 2138 of file estimator_checks.py.
check_positive_only_tag_during_fit()
sklearn.utils.estimator_checks.check_positive_only_tag_during_fit (name, estimator_orig)
Test that the estimator correctly sets the tags.input_tags.positive_only
If the tag is False, the estimator should accept negative input regardless of the
tags.input_tags.pairwise flag.
Definition at line 3987 of file estimator_checks.py.
check_readonly_memmap_input()
sklearn.utils.estimator_checks.check_readonly_memmap_input (name, estimator_orig)
Check that the estimator can handle readonly memmap backed data.
This is particularly needed to support joblib parallelisation.
Definition at line 3204 of file estimator_checks.py.
check_regressor_data_not_an_array()
sklearn.utils.estimator_checks.check_regressor_data_not_an_array (name, estimator_orig)
Definition at line 3722 of file estimator_checks.py.
check_regressor_multioutput()
sklearn.utils.estimator_checks.check_regressor_multioutput (name, estimator)
Definition at line 2533 of file estimator_checks.py.
check_regressors_int()
sklearn.utils.estimator_checks.check_regressors_int (name, regressor_orig)
Definition at line 3391 of file estimator_checks.py.
check_regressors_no_decision_function()
sklearn.utils.estimator_checks.check_regressors_no_decision_function (name, regressor_orig)
Definition at line 3470 of file estimator_checks.py.
check_regressors_train()
sklearn.utils.estimator_checks.check_regressors_train (name, regressor_orig, readonly_memmap = False, X_dtype = np.float64)
Definition at line 3419 of file estimator_checks.py.
check_requires_y_none()
sklearn.utils.estimator_checks.check_requires_y_none (name, estimator_orig)
Definition at line 4388 of file estimator_checks.py.
check_sample_weight_equivalence_on_dense_data()
sklearn.utils.estimator_checks.check_sample_weight_equivalence_on_dense_data (name, estimator_orig)
Definition at line 1576 of file estimator_checks.py.
check_sample_weight_equivalence_on_sparse_data()
sklearn.utils.estimator_checks.check_sample_weight_equivalence_on_sparse_data (name, estimator_orig)
Definition at line 1580 of file estimator_checks.py.
check_sample_weights_list()
sklearn.utils.estimator_checks.check_sample_weights_list (name, estimator_orig)
Definition at line 1454 of file estimator_checks.py.
check_sample_weights_not_an_array()
sklearn.utils.estimator_checks.check_sample_weights_not_an_array (name, estimator_orig)
Definition at line 1424 of file estimator_checks.py.
check_sample_weights_not_overwritten()
sklearn.utils.estimator_checks.check_sample_weights_not_overwritten (name, estimator_orig)
Definition at line 1584 of file estimator_checks.py.
check_sample_weights_pandas_series()
sklearn.utils.estimator_checks.check_sample_weights_pandas_series (name, estimator_orig)
Definition at line 1377 of file estimator_checks.py.
check_sample_weights_shape()
sklearn.utils.estimator_checks.check_sample_weights_shape (name, estimator_orig)
Definition at line 1469 of file estimator_checks.py.
check_set_output_transform()
sklearn.utils.estimator_checks.check_set_output_transform (name, transformer_orig)
Definition at line 4948 of file estimator_checks.py.
check_set_output_transform_pandas()
sklearn.utils.estimator_checks.check_set_output_transform_pandas (name, transformer_orig)
Definition at line 5211 of file estimator_checks.py.
check_set_output_transform_polars()
sklearn.utils.estimator_checks.check_set_output_transform_polars (name, transformer_orig)
Definition at line 5243 of file estimator_checks.py.
check_set_params()
sklearn.utils.estimator_checks.check_set_params (name, estimator_orig)
Definition at line 4089 of file estimator_checks.py.
check_sparsify_coefficients()
sklearn.utils.estimator_checks.check_sparsify_coefficients (name, estimator_orig)
Definition at line 3662 of file estimator_checks.py.
check_supervised_y_2d()
sklearn.utils.estimator_checks.check_supervised_y_2d (name, estimator_orig)
Definition at line 3253 of file estimator_checks.py.
check_supervised_y_no_nan()
sklearn.utils.estimator_checks.check_supervised_y_no_nan (name, estimator_orig)
Definition at line 1011 of file estimator_checks.py.
check_transformer_data_not_an_array()
sklearn.utils.estimator_checks.check_transformer_data_not_an_array (name, transformer)
Definition at line 1997 of file estimator_checks.py.
check_transformer_general()
sklearn.utils.estimator_checks.check_transformer_general (name, transformer, readonly_memmap = False)
Definition at line 1979 of file estimator_checks.py.
check_transformer_get_feature_names_out()
sklearn.utils.estimator_checks.check_transformer_get_feature_names_out (name, transformer_orig)
Definition at line 4729 of file estimator_checks.py.
check_transformer_get_feature_names_out_pandas()
sklearn.utils.estimator_checks.check_transformer_get_feature_names_out_pandas (name, transformer_orig)
Definition at line 4777 of file estimator_checks.py.
check_transformer_n_iter()
sklearn.utils.estimator_checks.check_transformer_n_iter (name, estimator_orig)
Definition at line 4047 of file estimator_checks.py.
check_transformer_preserve_dtypes()
sklearn.utils.estimator_checks.check_transformer_preserve_dtypes (name, transformer_orig)
Definition at line 2264 of file estimator_checks.py.
check_transformers_unfitted()
sklearn.utils.estimator_checks.check_transformers_unfitted (name, transformer)
Definition at line 2015 of file estimator_checks.py.
check_transformers_unfitted_stateless()
sklearn.utils.estimator_checks.check_transformers_unfitted_stateless (name, transformer)
Check that using transform without prior fitting
doesn't raise a NotFittedError for stateless transformers.
Definition at line 2032 of file estimator_checks.py.
check_valid_tag_types()
sklearn.utils.estimator_checks.check_valid_tag_types (name, estimator)
Check that estimator tags are valid.
Definition at line 4513 of file estimator_checks.py.
estimator_checks_generator()
sklearn.utils.estimator_checks.estimator_checks_generator (estimator, * , bool legacy = True, dict[str, str] | None expected_failed_checks = None, Literal["xfail", "skip", None] mark = None)
Iteratively yield all check callables for an estimator.
This function is used by
:func:`~sklearn.utils.estimator_checks.parametrize_with_checks` and
:func:`~sklearn.utils.estimator_checks.check_estimator` to yield all check callables
for an estimator. In most cases, these functions should be used instead. When
implementing a custom equivalent, please refer to their source code to
understand how `estimator_checks_generator` is intended to be used.
.. versionadded:: 1.6
Parameters
----------
estimator : estimator object
    Estimator instance for which to generate checks.
legacy : bool, default=True
    Whether to include legacy checks. Over time we remove checks from this category
    and move them into their specific category.
expected_failed_checks : dict[str, str], default=None
    Dictionary of the form {check_name: reason} for checks that are expected to
    fail.
mark : {"xfail", "skip"} or None, default=None
    Whether to mark the checks that are expected to fail as
    xfail(`pytest.mark.xfail`) or skip. Marking a test as "skip" is done via
    wrapping the check in a function that raises a
    :class:`~sklearn.exceptions.SkipTest` exception.
Returns
-------
estimator_checks_generator : generator
    Generator that yields (estimator, check) tuples.
Definition at line 500 of file estimator_checks.py.
References _maybe_mark().
Referenced by check_estimator(), and parametrize_with_checks().
parametrize_with_checks()
sklearn.utils.estimator_checks.parametrize_with_checks (estimators, * , bool legacy = True, Callable | None expected_failed_checks = None)
Pytest specific decorator for parametrizing estimator checks.
Checks are categorised into the following groups:
- API checks: a set of checks to ensure API compatibility with scikit-learn.
  Refer to https://scikit-learn.org/dev/developers/develop.html a requirement of
  scikit-learn estimators.
- legacy: a set of checks which gradually will be grouped into other categories.
The `id` of each check is set to be a pprint version of the estimator
and the name of the check with its keyword arguments.
This allows to use `pytest -k` to specify which tests to run::
    pytest test_check_estimators.py -k check_estimators_fit_returns_self
Parameters
----------
estimators : list of estimators instances
    Estimators to generated checks for.
    .. versionchanged:: 0.24
       Passing a class was deprecated in version 0.23, and support for
       classes was removed in 0.24. Pass an instance instead.
    .. versionadded:: 0.24
legacy : bool, default=True
    Whether to include legacy checks. Over time we remove checks from this category
    and move them into their specific category.
    .. versionadded:: 1.6
expected_failed_checks : callable, default=None
    A callable that takes an estimator as input and returns a dictionary of the
    form::
        {
            "check_name": "my reason",
        }
    Where `"check_name"` is the name of the check, and `"my reason"` is why
    the check fails. These tests will be marked as xfail if the check fails.
    .. versionadded:: 1.6
Returns
-------
decorator : `pytest.mark.parametrize`
See Also
--------
check_estimator : Check if estimator adheres to scikit-learn conventions.
Examples
--------
>>> from sklearn.utils.estimator_checks import parametrize_with_checks
>>> from sklearn.linear_model import LogisticRegression
>>> from sklearn.tree import DecisionTreeRegressor
>>> @parametrize_with_checks([LogisticRegression(),
...                           DecisionTreeRegressor()])
... def test_sklearn_compatible_estimator(estimator, check):
...     check(estimator)
Definition at line 560 of file estimator_checks.py.
References estimator_checks_generator().
Variable Documentation
REGRESSION_DATASET
sklearn.utils.estimator_checks.REGRESSION_DATASET = None
Definition at line 110 of file estimator_checks.py.