Code Cloning Analysis: ufunclike.Object Class Reference
ufunclike.Object Class Reference
Public Member Functions
Object __ceil__ (self)
Object __floor__ (self)
bool __ge__ (self, object value)
np.ndarray[Any, np.dtype[np.object_]] __array__ (self)
Detailed Description
Definition at line 6 of file ufunclike.py.
Member Function Documentation
__array__()
np.ndarray[Any, np.dtype[np.object_]] ufunclike.Object.__array__ (self)
Definition at line 16 of file ufunclike.py.
Referenced by numpy.matrixlib.defmatrix.matrix.A(), numpy.matrixlib.defmatrix.matrix.A1(), numpy.core.defchararray.chararray.argsort(), numpy.matrixlib.defmatrix.matrix.tolist(), and numpy.ma.mrecords.MaskedRecords.view().
__ceil__()
Object ufunclike.Object.__ceil__ (self)
Definition at line 7 of file ufunclike.py.
__floor__()
Object ufunclike.Object.__floor__ (self)
Definition at line 10 of file ufunclike.py.
__ge__()
bool ufunclike.Object.__ge__ (self, object value)
Definition at line 13 of file ufunclike.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/typing/tests/data/pass/ufunclike.py