Code Cloning Analysis: fontTools.ttLib.tables.T_S_I__5.table_T_S_I__5 Class Reference
fontTools.ttLib.tables.T_S_I__5.table_T_S_I__5 Class Reference
Public Member Functions
decompile (self, data, ttFont)
compile (self, ttFont)
toXML (self, writer, ttFont)
fromXML (self, name, attrs, content, ttFont)
Public Member Functions inherited from fontTools.ttLib.tables.DefaultTable.DefaultTable
__init__ (self, tag=None)
__repr__ (self)
__eq__ (self, other)
__ne__ (self, other)
Public Attributes
dict glyphGrouping = {}
Public Attributes inherited from fontTools.ttLib.tables.DefaultTable.DefaultTable
tableTag = Tag(tag)
data = data
ERROR
Additional Inherited Members
Static Public Attributes inherited from fontTools.ttLib.tables.DefaultTable.DefaultTable
list dependencies = []
Detailed Description
Definition at line 20 of file T_S_I__5.py.
Member Function Documentation
compile()
fontTools.ttLib.tables.T_S_I__5.table_T_S_I__5.compile (self, ttFont)
Reimplemented from fontTools.ttLib.tables.DefaultTable.DefaultTable.
Definition at line 38 of file T_S_I__5.py.
Referenced by fontTools.ttLib.tables.TupleVariation.TupleVariation.getCoordWidth(), and PIL.FontFile.FontFile.save().
decompile()
fontTools.ttLib.tables.T_S_I__5.table_T_S_I__5.decompile (self, data, ttFont)
Reimplemented from fontTools.ttLib.tables.DefaultTable.DefaultTable.
Definition at line 21 of file T_S_I__5.py.
Referenced by fontTools.ttLib.tables._c_m_a_p.CmapSubtable.newSubtable().
fromXML()
fontTools.ttLib.tables.T_S_I__5.table_T_S_I__5.fromXML (self, name, attrs, content, ttFont)
Reimplemented from fontTools.ttLib.tables.DefaultTable.DefaultTable.
Definition at line 55 of file T_S_I__5.py.
toXML()
fontTools.ttLib.tables.T_S_I__5.table_T_S_I__5.toXML (self, writer, ttFont)
Reimplemented from fontTools.ttLib.tables.DefaultTable.DefaultTable.
Definition at line 47 of file T_S_I__5.py.
Member Data Documentation
glyphGrouping
dict fontTools.ttLib.tables.T_S_I__5.table_T_S_I__5.glyphGrouping = {}
Definition at line 27 of file T_S_I__5.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ttLib/tables/T_S_I__5.py