Code Cloning Analysis: fontTools.pens.boundsPen.ControlBoundsPen Class Reference
fontTools.pens.boundsPen.ControlBoundsPen Class Reference
Public Member Functions
__init__ (self, glyphSet, ignoreSinglePoints=False)
init (self)
Public Member Functions inherited from fontTools.pens.basePen.BasePen
__init__ (self, glyphSet=None)
closePath (self)
endPath (self)
moveTo (self, pt)
lineTo (self, pt)
curveTo (self, *points)
qCurveTo (self, *points)
Public Member Functions inherited from fontTools.pens.basePen.DecomposingPen
__init__ (self, glyphSet, *args, skipMissingComponents=None, reverseFlipped=False, **kwargs)
addComponent (self, glyphName, transformation)
addVarComponent (self, glyphName, transformation, location)
Public Member Functions inherited from fontTools.misc.loggingTools.LogMixin
log (self)
Public Attributes
ignoreSinglePoints = ignoreSinglePoints
tuple bounds = None
Public Attributes inherited from fontTools.pens.basePen.DecomposingPen
glyphSet = glyphSet
reverseFlipped = reverseFlipped
Protected Member Functions
_moveTo (self, pt)
_addMoveTo (self)
_lineTo (self, pt)
_curveToOne (self, bcp1, bcp2, pt)
_qCurveToOne (self, bcp, pt)
Protected Member Functions inherited from fontTools.pens.basePen.BasePen
_closePath (self)
_endPath (self)
_getCurrentPoint (self)
Protected Attributes
_start = None
Protected Attributes inherited from fontTools.misc.loggingTools.LogMixin
_log = logging.getLogger(name)
Additional Inherited Members
Static Public Attributes inherited from fontTools.pens.basePen.DecomposingPen
bool skipMissingComponents = True
MissingComponentError = MissingComponentError
Detailed Description
Pen to calculate the "control bounds" of a shape. This is the
bounding box of all control points, so may be larger than the
actual bounding box if there are curves that don't have points
on their extremes.
When the shape has been drawn, the bounds are available as the
``bounds`` attribute of the pen object. It's a 4-tuple::
        (xMin, yMin, xMax, yMax).
If ``ignoreSinglePoints`` is True, single points are ignored.
Definition at line 9 of file boundsPen.py.
Constructor & Destructor Documentation
__init__()
fontTools.pens.boundsPen.ControlBoundsPen.__init__ (self, glyphSet, ignoreSinglePoints = False)
Definition at line 23 of file boundsPen.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_addMoveTo()
fontTools.pens.boundsPen.ControlBoundsPen._addMoveTo (self) protected
Definition at line 37 of file boundsPen.py.
Referenced by fontTools.pens.boundsPen.BoundsPen._qCurveToOne(), and _qCurveToOne().
_curveToOne()
fontTools.pens.boundsPen.ControlBoundsPen._curveToOne (self, bcp1, bcp2, pt) protected
Reimplemented from fontTools.pens.basePen.BasePen.
Definition at line 52 of file boundsPen.py.
_lineTo()
fontTools.pens.boundsPen.ControlBoundsPen._lineTo (self, pt) protected
Reimplemented from fontTools.pens.basePen.BasePen.
Definition at line 48 of file boundsPen.py.
_moveTo()
fontTools.pens.boundsPen.ControlBoundsPen._moveTo (self, pt) protected
Reimplemented from fontTools.pens.basePen.BasePen.
Definition at line 32 of file boundsPen.py.
_qCurveToOne()
fontTools.pens.boundsPen.ControlBoundsPen._qCurveToOne (self, pt1, pt2) protected
This method implements the basic quadratic curve type. The
default implementation delegates the work to the cubic curve
function. Optionally override with a native implementation.
Reimplemented from fontTools.pens.basePen.BasePen.
Reimplemented in fontTools.pens.boundsPen.BoundsPen.
Definition at line 60 of file boundsPen.py.
References _addMoveTo(), and bounds.
init()
fontTools.pens.boundsPen.ControlBoundsPen.init (self)
Definition at line 28 of file boundsPen.py.
Referenced by fontTools.pens.ttGlyphPen._TTGlyphBasePen.__init__(), and fontTools.pens.ttGlyphPen._TTGlyphBasePen.glyph().
Member Data Documentation
_start
fontTools.pens.boundsPen.ControlBoundsPen._start = None protected
Definition at line 30 of file boundsPen.py.
Referenced by joblib.parallel.Parallel._get_outputs().
bounds
tuple fontTools.pens.boundsPen.ControlBoundsPen.bounds = None
Definition at line 29 of file boundsPen.py.
Referenced by sklearn.gaussian_process.kernels.Kernel._check_bounds_params(), fontTools.pens.boundsPen.BoundsPen._qCurveToOne(), _qCurveToOne(), matplotlib.transforms.BboxBase.anchored(), scipy.optimize._shgo.SHGO.construct_lcb_delaunay(), scipy.optimize._shgo.SHGO.construct_lcb_simplicial(), scipy.optimize._shgo.SHGO.init_options(), scipy.optimize._shgo_lib._complex.Complex.refine_all(), scipy.optimize._shgo.SHGO.sampling_custom(), scipy.optimize._shgo_lib._complex.Complex.triangulate(), scipy.optimize._constraints.PreparedConstraint.violation(), and scipy.optimize._differentialevolution._ConstraintWrapper.violation().
ignoreSinglePoints
fontTools.pens.boundsPen.ControlBoundsPen.ignoreSinglePoints = ignoreSinglePoints
Definition at line 25 of file boundsPen.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/pens/boundsPen.py