Code Cloning Analysis: numpy.ma.core._DomainGreaterEqual Class Reference
numpy.ma.core._DomainGreaterEqual Class Reference
Public Member Functions
__init__ (self, critical_value)
__call__ (self, x)
Public Attributes
critical_value = critical_value
Detailed Description
DomainGreaterEqual(v)(x) is True where x < v.
Definition at line 877 of file core.py.
Constructor & Destructor Documentation
__init__()
numpy.ma.core._DomainGreaterEqual.__init__ (self, critical_value)
Definition at line 883 of file core.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__call__()
numpy.ma.core._DomainGreaterEqual.__call__ (self, x)
Definition at line 887 of file core.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), and scipy.interpolate._fitpack2.SphereBivariateSpline.ev().
Member Data Documentation
critical_value
numpy.ma.core._DomainGreaterEqual.critical_value = critical_value
Definition at line 885 of file core.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/ma/core.py