Code Cloning Analysis: matplotlib.backends.backend_webagg_core.FigureCanvasWebAggCore Class Reference
matplotlib.backends.backend_webagg_core.FigureCanvasWebAggCore Class Reference
Public Member Functions
__init__ (self, *args, **kwargs)
show (self)
draw (self)
blit (self, bbox=None)
draw_idle (self)
set_cursor (self, cursor)
set_image_mode (self, mode)
get_diff_image (self)
handle_event (self, event)
handle_unknown_event (self, event)
handle_ack (self, event)
handle_draw (self, event)
handle_toolbar_button (self, event)
handle_refresh (self, event)
handle_resize (self, event)
handle_send_image_mode (self, event)
handle_set_device_pixel_ratio (self, event)
handle_set_dpi_ratio (self, event)
send_event (self, event_type, **kwargs)
Public Member Functions inherited from matplotlib.backends.backend_agg.FigureCanvasAgg
copy_from_bbox (self, bbox)
restore_region (self, region, bbox=None, xy=None)
get_renderer (self)
tostring_argb (self)
buffer_rgba (self)
print_raw (self, filename_or_obj, *, metadata=None)
print_png (self, filename_or_obj, *, metadata=None, pil_kwargs=None)
print_to_buffer (self)
print_jpg (self, filename_or_obj, *, metadata=None, pil_kwargs=None)
print_tif (self, filename_or_obj, *, metadata=None, pil_kwargs=None)
print_webp (self, filename_or_obj, *, metadata=None, pil_kwargs=None)
Public Member Functions inherited from matplotlib.backend_bases.FigureCanvasBase
supports_blit (cls)
__init__ (self, figure=None)
new_manager (cls, figure, num)
is_saving (self)
inaxes (self, xy)
grab_mouse (self, ax)
release_mouse (self, ax)
device_pixel_ratio (self)
get_width_height (self, *, physical=False)
get_supported_filetypes (cls)
get_supported_filetypes_grouped (cls)
print_figure (self, filename, dpi=None, facecolor=None, edgecolor=None, orientation='portrait', format=None, *, bbox_inches=None, pad_inches=None, bbox_extra_artists=None, backend=None, **kwargs)
get_default_filetype (cls)
get_default_filename (self)
mpl_connect (self, s, func)
mpl_disconnect (self, cid)
new_timer (self, interval=None, callbacks=None)
flush_events (self)
start_event_loop (self, timeout=0)
stop_event_loop (self)
Static Public Attributes
handle_button_press = _handle_mouse
handle_key_press = _handle_key
Static Public Attributes inherited from matplotlib.backends.backend_agg.FigureCanvasAgg
print_rgba = print_raw
print_jpeg = print_jpg
print_tiff = print_tif
Static Public Attributes inherited from matplotlib.backend_bases.FigureCanvasBase
required_interactive_framework = None
manager_class = _api.classproperty(lambda cls: FigureManagerBase)
list events
fixed_dpi = None
filetypes = _default_filetypes
Protected Member Functions
_handle_mouse (self, event)
_handle_key (self, event)
_handle_set_device_pixel_ratio (self, device_pixel_ratio)
Protected Member Functions inherited from matplotlib.backends.backend_agg.FigureCanvasAgg
_print_pil (self, filename_or_obj, fmt, pil_kwargs, metadata=None)
Protected Member Functions inherited from matplotlib.backend_bases.FigureCanvasBase
_fix_ipython_backend2gui (cls)
_idle_draw_cntx (self)
_set_device_pixel_ratio (self, ratio)
_switch_canvas_and_return_print_method (self, fmt, backend=None)
Protected Attributes
bool _png_is_old = True
bool _force_full = True
_last_buff = np.empty((0, 0))
str _current_image_mode = 'full'
tuple _last_mouse_xy = (None, None)
Protected Attributes inherited from matplotlib.backend_bases.FigureCanvasBase
bool _is_idle_drawing = True
bool _is_saving = False
_button = None
_key = None
int _device_pixel_ratio = 1
bool _looping = True
Additional Inherited Members
Public Attributes inherited from matplotlib.backends.backend_agg.FigureCanvasAgg
renderer = self.get_renderer()
Public Attributes inherited from matplotlib.backend_bases.FigureCanvasBase
figure = figure
manager = None
widgetlock = widgets.LockDraw()
mouse_grabber = None
toolbar = None
device_pixel_ratio
Static Protected Attributes inherited from matplotlib.backends.backend_agg.FigureCanvasAgg
_lastKey = None
Static Protected Attributes inherited from matplotlib.backend_bases.FigureCanvasBase
_timer_cls = TimerBase
Properties inherited from matplotlib.backend_bases.FigureCanvasBase
callbacks = property(lambda self: self.figure._canvas_callbacks)
button_pick_id = property(lambda self: self.figure._button_pick_id)
scroll_pick_id = property(lambda self: self.figure._scroll_pick_id)
Detailed Description
Definition at line 155 of file backend_webagg_core.py.
Constructor & Destructor Documentation
__init__()
matplotlib.backends.backend_webagg_core.FigureCanvasWebAggCore.__init__ (self, * args, ** kwargs)
Definition at line 163 of file backend_webagg_core.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_handle_key()
matplotlib.backends.backend_webagg_core.FigureCanvasWebAggCore._handle_key (self, event) protected
Definition at line 320 of file backend_webagg_core.py.
_handle_mouse()
matplotlib.backends.backend_webagg_core.FigureCanvasWebAggCore._handle_mouse (self, event) protected
Definition at line 281 of file backend_webagg_core.py.
_handle_set_device_pixel_ratio()
matplotlib.backends.backend_webagg_core.FigureCanvasWebAggCore._handle_set_device_pixel_ratio (self, device_pixel_ratio) protected
Definition at line 367 of file backend_webagg_core.py.
blit()
matplotlib.backends.backend_webagg_core.FigureCanvasWebAggCore.blit (self, bbox = None)
Blit the canvas in bbox (default entire canvas).
Reimplemented from matplotlib.backend_bases.FigureCanvasBase.
Definition at line 193 of file backend_webagg_core.py.
References _png_is_old, and matplotlib.backend_bases.FigureCanvasBase.manager.
draw()
matplotlib.backends.backend_webagg_core.FigureCanvasWebAggCore.draw (self)
Render the `.Figure`.
This method must walk the artist tree, even if no output is produced,
because it triggers deferred work that users may want to access
before saving output to disk. For example computing limits,
auto-limits, and tick values.
Reimplemented from matplotlib.backends.backend_agg.FigureCanvasAgg.
Definition at line 186 of file backend_webagg_core.py.
References _png_is_old, draw(), and matplotlib.backend_bases.FigureCanvasBase.manager.
Referenced by draw().
draw_idle()
matplotlib.backends.backend_webagg_core.FigureCanvasWebAggCore.draw_idle (self)
Request a widget redraw once control returns to the GUI event loop.
Even if multiple calls to `draw_idle` occur before control returns
to the GUI event loop, the figure will only be rendered once.
Notes
-----
Backends may choose to override the method and implement their own
strategy to prevent multiple renderings.
Reimplemented from matplotlib.backend_bases.FigureCanvasBase.
Definition at line 197 of file backend_webagg_core.py.
References send_event().
get_diff_image()
matplotlib.backends.backend_webagg_core.FigureCanvasWebAggCore.get_diff_image (self)
Definition at line 227 of file backend_webagg_core.py.
handle_ack()
matplotlib.backends.backend_webagg_core.FigureCanvasWebAggCore.handle_ack (self, event)
Definition at line 269 of file backend_webagg_core.py.
handle_draw()
matplotlib.backends.backend_webagg_core.FigureCanvasWebAggCore.handle_draw (self, event)
Definition at line 278 of file backend_webagg_core.py.
handle_event()
matplotlib.backends.backend_webagg_core.FigureCanvasWebAggCore.handle_event (self, event)
Definition at line 260 of file backend_webagg_core.py.
handle_refresh()
matplotlib.backends.backend_webagg_core.FigureCanvasWebAggCore.handle_refresh (self, event)
Definition at line 330 of file backend_webagg_core.py.
handle_resize()
matplotlib.backends.backend_webagg_core.FigureCanvasWebAggCore.handle_resize (self, event)
Definition at line 342 of file backend_webagg_core.py.
handle_send_image_mode()
matplotlib.backends.backend_webagg_core.FigureCanvasWebAggCore.handle_send_image_mode (self, event)
Definition at line 356 of file backend_webagg_core.py.
Referenced by set_image_mode().
handle_set_device_pixel_ratio()
matplotlib.backends.backend_webagg_core.FigureCanvasWebAggCore.handle_set_device_pixel_ratio (self, event)
Definition at line 360 of file backend_webagg_core.py.
handle_set_dpi_ratio()
matplotlib.backends.backend_webagg_core.FigureCanvasWebAggCore.handle_set_dpi_ratio (self, event)
Definition at line 363 of file backend_webagg_core.py.
handle_toolbar_button()
matplotlib.backends.backend_webagg_core.FigureCanvasWebAggCore.handle_toolbar_button (self, event)
Definition at line 326 of file backend_webagg_core.py.
handle_unknown_event()
matplotlib.backends.backend_webagg_core.FigureCanvasWebAggCore.handle_unknown_event (self, event)
Definition at line 266 of file backend_webagg_core.py.
Referenced by set_image_mode().
send_event()
matplotlib.backends.backend_webagg_core.FigureCanvasWebAggCore.send_event (self, event_type, ** kwargs)
Definition at line 372 of file backend_webagg_core.py.
Referenced by draw_idle(), and set_cursor().
set_cursor()
matplotlib.backends.backend_webagg_core.FigureCanvasWebAggCore.set_cursor (self, cursor)
Set the current cursor.
This may have no effect if the backend does not display anything.
If required by the backend, this method should trigger an update in
the backend event loop after the cursor is set, as this method may be
called e.g. before a long-running task during which the GUI is not
updated.
Parameters
----------
cursor : `.Cursors`
    The cursor to display over the canvas. Note: some backends may
    change the cursor for the entire window.
Reimplemented from matplotlib.backend_bases.FigureCanvasBase.
Definition at line 200 of file backend_webagg_core.py.
References send_event().
set_image_mode()
matplotlib.backends.backend_webagg_core.FigureCanvasWebAggCore.set_image_mode (self, mode)
Set the image mode for any subsequent images which will be sent
to the clients. The modes may currently be either 'full' or 'diff'.
Note: diff images may not contain transparency, therefore upon
draw this mode may be changed if the resulting image has any
transparent component.
Definition at line 213 of file backend_webagg_core.py.
References _current_image_mode, _force_full, _last_buff, _png_is_old, matplotlib.backends.backend_agg.FigureCanvasAgg.get_renderer(), handle_send_image_mode(), handle_unknown_event(), and set_image_mode().
Referenced by set_image_mode().
show()
matplotlib.backends.backend_webagg_core.FigureCanvasWebAggCore.show (self)
Definition at line 181 of file backend_webagg_core.py.
Member Data Documentation
_current_image_mode
str matplotlib.backends.backend_webagg_core.FigureCanvasWebAggCore._current_image_mode = 'full' protected
Definition at line 177 of file backend_webagg_core.py.
Referenced by set_image_mode().
_force_full
bool matplotlib.backends.backend_webagg_core.FigureCanvasWebAggCore._force_full = True protected
Definition at line 170 of file backend_webagg_core.py.
Referenced by set_image_mode().
_last_buff
matplotlib.backends.backend_webagg_core.FigureCanvasWebAggCore._last_buff = np.empty((0, 0)) protected
Definition at line 172 of file backend_webagg_core.py.
Referenced by set_image_mode().
_last_mouse_xy
matplotlib.backends.backend_webagg_core.FigureCanvasWebAggCore._last_mouse_xy = (None, None) protected
Definition at line 179 of file backend_webagg_core.py.
_png_is_old
bool matplotlib.backends.backend_webagg_core.FigureCanvasWebAggCore._png_is_old = True protected
Definition at line 167 of file backend_webagg_core.py.
Referenced by blit(), draw(), and set_image_mode().
handle_button_press
matplotlib.backends.backend_webagg_core.FigureCanvasWebAggCore.handle_button_press = _handle_mouse static
Definition at line 316 of file backend_webagg_core.py.
handle_key_press
matplotlib.backends.backend_webagg_core.FigureCanvasWebAggCore.handle_key_press = _handle_key static
Definition at line 324 of file backend_webagg_core.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/backends/backend_webagg_core.py