Code Cloning Analysis: sklearn.utils._encode Namespace Reference
sklearn.utils._encode Namespace Reference
Classes
class _NaNCounter
class _nandict
class MissingValues
Functions
_unique (values, *, return_inverse=False, return_counts=False)
_unique_np (values, return_inverse=False, return_counts=False)
_extract_missing (values)
_map_to_integer (values, uniques)
_unique_python (values, *, return_inverse, return_counts)
_encode (values, *, uniques, check_unknown=True)
_check_unknown (values, known_values, return_mask=False)
_get_counts (values, uniques)
Function Documentation
_check_unknown()
sklearn.utils._encode._check_unknown (values, known_values, return_mask = False) protected
Helper function to check for unknowns in values to be encoded.
Uses pure python method for object dtype, and numpy method for
all other dtypes.
Parameters
----------
values : array
    Values to check for unknowns.
known_values : array
    Known values. Must be unique.
return_mask : bool, default=False
    If True, return a mask of the same shape as `values` indicating
    the valid values.
Returns
-------
diff : list
    The unique values present in `values` and not in `know_values`.
valid_mask : boolean array
    Additionally returned if ``return_mask=True``.
Definition at line 246 of file _encode.py.
References _extract_missing().
Referenced by _encode().
_encode()
sklearn.utils._encode._encode (values, * , uniques, check_unknown = True) protected
Helper function to encode values into [0, n_uniques - 1].
Uses pure python method for object dtype, and numpy method for
all other dtypes.
The numpy method has the limitation that the `uniques` need to
be sorted. Importantly, this is not checked but assumed to already be
the case. The calling method needs to ensure this for all non-object
values.
Parameters
----------
values : ndarray
    Values to encode.
uniques : ndarray
    The unique values in `values`. If the dtype is not object, then
    `uniques` needs to be sorted.
check_unknown : bool, default=True
    If True, check for values in `values` that are not in `unique`
    and raise an error. This is ignored for object dtype, and treated as
    True in this case. This parameter is useful for
    _BaseEncoder._transform() to avoid calling _check_unknown()
    twice.
Returns
-------
encoded : ndarray
    Encoded values
Definition at line 203 of file _encode.py.
References _check_unknown(), and _map_to_integer().
_extract_missing()
sklearn.utils._encode._extract_missing (values) protected
Extract missing values from `values`.
Parameters
----------
values: set
    Set of values to extract missing from.
Returns
-------
output: set
    Set with missing values extracted.
missing_values: MissingValues
    Object with missing value information.
Definition at line 116 of file _encode.py.
Referenced by _check_unknown(), and _map_to_integer().
_get_counts()
sklearn.utils._encode._get_counts (values, uniques) protected
Get the count of each of the `uniques` in `values`.
The counts will use the order passed in by `uniques`. For non-object dtypes,
`uniques` is assumed to be sorted and `np.nan` is at the end.
Definition at line 352 of file _encode.py.
References _unique_np().
Referenced by _map_to_integer().
_map_to_integer()
sklearn.utils._encode._map_to_integer (values, uniques) protected
Map values based on its position in uniques.
Definition at line 170 of file _encode.py.
References _extract_missing(), _get_counts(), and _map_to_integer().
Referenced by _encode(), and _map_to_integer().
_unique()
sklearn.utils._encode._unique (values, * , return_inverse = False, return_counts = False) protected
Helper function to find unique values with support for python objects.
Uses pure python method for object dtype, and numpy method for
all other dtypes.
Parameters
----------
values : ndarray
    Values to check for unknowns.
return_inverse : bool, default=False
    If True, also return the indices of the unique values.
return_counts : bool, default=False
    If True, also return the number of times each unique item appears in
    values.
Returns
-------
unique : ndarray
    The sorted unique values.
unique_inverse : ndarray
    The indices to reconstruct the original array from the unique array.
    Only provided if `return_inverse` is True.
unique_counts : ndarray
    The number of times each of the unique values comes up in the original
    array. Only provided if `return_counts` is True.
Definition at line 20 of file _encode.py.
References _unique_np().
_unique_np()
sklearn.utils._encode._unique_np (values, return_inverse = False, return_counts = False) protected
Helper function to find unique values for numpy arrays that correctly
accounts for nans. See `_unique` documentation for details.
Definition at line 61 of file _encode.py.
Referenced by _get_counts(), and _unique().
_unique_python()
sklearn.utils._encode._unique_python (values, * , return_inverse, return_counts) protected
Definition at line 177 of file _encode.py.