Code Cloning Analysis: scipy.signal.tests.test_peak_finding.TestPeakProminences Class Reference
scipy.signal.tests.test_peak_finding.TestPeakProminences Class Reference
Public Member Functions
test_empty (self)
test_basic (self)
test_edge_cases (self)
test_non_contiguous (self)
test_wlen (self)
test_exceptions (self)
test_warnings (self)
Detailed Description
Definition at line 321 of file test_peak_finding.py.
Member Function Documentation
test_basic()
scipy.signal.tests.test_peak_finding.TestPeakProminences.test_basic (self)
Test if height of prominences is correctly calculated in signal with
rising baseline (peak widths are 1 sample).
Definition at line 337 of file test_peak_finding.py.
References scipy.signal._peak_finding.peak_prominences().
test_edge_cases()
scipy.signal.tests.test_peak_finding.TestPeakProminences.test_edge_cases (self)
Test edge cases.
Definition at line 354 of file test_peak_finding.py.
References scipy.signal._peak_finding.peak_prominences().
test_empty()
scipy.signal.tests.test_peak_finding.TestPeakProminences.test_empty (self)
Test if an empty array is returned if no peaks are provided.
Definition at line 323 of file test_peak_finding.py.
References scipy.signal._peak_finding.peak_prominences().
test_exceptions()
scipy.signal.tests.test_peak_finding.TestPeakProminences.test_exceptions (self)
Verify that exceptions and warnings are raised.
Definition at line 396 of file test_peak_finding.py.
References scipy.signal._peak_finding.peak_prominences().
test_non_contiguous()
scipy.signal.tests.test_peak_finding.TestPeakProminences.test_non_contiguous (self)
Test with non-C-contiguous input arrays.
Definition at line 374 of file test_peak_finding.py.
References scipy.signal._peak_finding.peak_prominences().
test_warnings()
scipy.signal.tests.test_peak_finding.TestPeakProminences.test_warnings (self)
Verify that appropriate warnings are raised.
Definition at line 426 of file test_peak_finding.py.
References scipy.signal._peak_finding.peak_prominences().
test_wlen()
scipy.signal.tests.test_peak_finding.TestPeakProminences.test_wlen (self)
Test if wlen actually shrinks the evaluation range correctly.
Definition at line 385 of file test_peak_finding.py.
References scipy.signal._peak_finding.peak_prominences().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/signal/tests/test_peak_finding.py