Code Cloning Analysis: pip._vendor.distlib.resources.ZipResourceFinder Class Reference
pip._vendor.distlib.resources.ZipResourceFinder Class Reference
Public Member Functions
__init__ (self, module)
get_cache_info (self, resource)
get_bytes (self, resource)
get_stream (self, resource)
get_size (self, resource)
get_resources (self, resource)
Public Member Functions inherited from pip._vendor.distlib.resources.ResourceFinder
__init__ (self, module)
find (self, resource_name)
is_container (self, resource)
iterator (self, resource_name)
Public Attributes
int prefix_len = 1 + len(archive)
index = sorted(self._files)
Public Attributes inherited from pip._vendor.distlib.resources.ResourceFinder
module = module
loader = getattr(module, '__loader__', None)
base = os.path.dirname(getattr(module, '__file__', ''))
Protected Member Functions
_adjust_path (self, path)
_find (self, path)
_is_directory (self, path)
Protected Member Functions inherited from pip._vendor.distlib.resources.ResourceFinder
_make_path (self, resource_name)
Protected Attributes
_files = self.loader._files
Additional Inherited Members
Static Public Attributes inherited from pip._vendor.distlib.resources.ResourceFinder
tuple skipped_extensions = ('.pyc', '.pyo', '.class')
Detailed Description
Resource finder for resources in .zip files.
Definition at line 208 of file resources.py.
Constructor & Destructor Documentation
__init__()
pip._vendor.distlib.resources.ZipResourceFinder.__init__ (self, module)
Definition at line 212 of file resources.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
_adjust_path()
pip._vendor.distlib.resources.ZipResourceFinder._adjust_path (self, path) protected
Reimplemented from pip._vendor.distlib.resources.ResourceFinder.
Definition at line 223 of file resources.py.
_find()
pip._vendor.distlib.resources.ZipResourceFinder._find (self, path) protected
Reimplemented from pip._vendor.distlib.resources.ResourceFinder.
Definition at line 226 of file resources.py.
_is_directory()
pip._vendor.distlib.resources.ZipResourceFinder._is_directory (self, path) protected
Reimplemented from pip._vendor.distlib.resources.ResourceFinder.
Definition at line 274 of file resources.py.
get_bytes()
pip._vendor.distlib.resources.ZipResourceFinder.get_bytes (self, resource)
Reimplemented from pip._vendor.distlib.resources.ResourceFinder.
Definition at line 249 of file resources.py.
get_cache_info()
pip._vendor.distlib.resources.ZipResourceFinder.get_cache_info (self, resource)
Reimplemented from pip._vendor.distlib.resources.ResourceFinder.
Definition at line 244 of file resources.py.
get_resources()
pip._vendor.distlib.resources.ZipResourceFinder.get_resources (self, resource)
Reimplemented from pip._vendor.distlib.resources.ResourceFinder.
Definition at line 259 of file resources.py.
get_size()
pip._vendor.distlib.resources.ZipResourceFinder.get_size (self, resource)
Reimplemented from pip._vendor.distlib.resources.ResourceFinder.
Definition at line 255 of file resources.py.
Referenced by matplotlib.text.Text.set_bbox(), matplotlib.text.Text.update_bbox_position_size(), and matplotlib.text.Annotation.update_positions().
get_stream()
pip._vendor.distlib.resources.ZipResourceFinder.get_stream (self, resource)
Reimplemented from pip._vendor.distlib.resources.ResourceFinder.
Definition at line 252 of file resources.py.
Member Data Documentation
_files
pip._vendor.distlib.resources.ZipResourceFinder._files = self.loader._files protected
Definition at line 218 of file resources.py.
index
pip._vendor.distlib.resources.ZipResourceFinder.index = sorted(self._files)
Definition at line 221 of file resources.py.
Referenced by scipy.optimize._shgo_lib._vertex.VertexBase.__init__(), scipy.optimize._shgo_lib._vertex.VertexCacheField.__init__(), scipy.optimize._shgo_lib._vertex.VertexCacheIndex.__init__(), pandas.core.apply.FrameApply.apply(), pandas.core.apply.FrameApply.apply_raw(), pandas.core.internals.array_manager.SingleArrayManager.array_values(), pip._vendor.pyparsing.diagram.ConverterState.generate_index(), pyparsing.diagram.ConverterState.generate_index(), and scipy.optimize._shgo_lib._vertex.VertexCacheBase.size().
prefix_len
int pip._vendor.distlib.resources.ZipResourceFinder.prefix_len = 1 + len(archive)
Definition at line 215 of file resources.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pip/_vendor/distlib/resources.py