Code Cloning Analysis: pandas.core.algorithms Namespace Reference
pandas.core.algorithms Namespace Reference
Functions
np.ndarray _ensure_data (ArrayLike values)
ArrayLike _reconstruct_data (ArrayLike values, DtypeObj dtype, AnyArrayLike original)
ArrayLike _ensure_arraylike (values, str func_name)
_get_hashtable_algo (np.ndarray values)
str _check_object_for_strings (np.ndarray values)
unique (values)
int nunique_ints (ArrayLike values)
unique_with_mask (values, npt.NDArray[np.bool_]|None mask=None)
npt.NDArray[np.bool_] isin (ListLike comps, ListLike values)
tuple[npt.NDArray[np.intp], np.ndarray] factorize_array (np.ndarray values, bool use_na_sentinel=True, int|None size_hint=None, object na_value=None, npt.NDArray[np.bool_]|None mask=None)
tuple[np.ndarray, np.ndarray|Index] factorize (values, bool sort=False, bool use_na_sentinel=True, int|None size_hint=None)
Series value_counts (values, bool sort=True, bool ascending=False, bool normalize=False, bins=None, bool dropna=True)
Series value_counts_internal (values, bool sort=True, bool ascending=False, bool normalize=False, bins=None, bool dropna=True)
tuple[ArrayLike, npt.NDArray[np.int64], int] value_counts_arraylike (np.ndarray values, bool dropna, npt.NDArray[np.bool_]|None mask=None)
npt.NDArray[np.bool_] duplicated (ArrayLike values, Literal["first", "last", False] keep="first", npt.NDArray[np.bool_]|None mask=None)
ArrayLike mode (ArrayLike values, bool dropna=True, npt.NDArray[np.bool_]|None mask=None)
npt.NDArray[np.float64] rank (ArrayLike values, AxisInt axis=0, str method="average", str na_option="keep", bool ascending=True, bool pct=False)
take (arr, TakeIndexer indices, AxisInt axis=0, bool allow_fill=False, fill_value=None)
npt.NDArray[np.intp]|np.intp searchsorted (ArrayLike arr, NumpyValueArrayLike|ExtensionArray value, Literal["left", "right"] side="left", NumpySorter|None sorter=None)
diff (arr, int n, AxisInt axis=0)
AnyArrayLike|tuple[AnyArrayLike, np.ndarray] safe_sort (Index|ArrayLike values, npt.NDArray[np.intp]|None codes=None, bool use_na_sentinel=True, bool assume_unique=False, bool verify=True)
AnyArrayLike _sort_mixed (values)
np.ndarray _sort_tuples (np.ndarray values)
ArrayLike|Index union_with_duplicates (ArrayLike|Index lvals, ArrayLike|Index rvals)
np.ndarray|ExtensionArray|Index map_array (ArrayLike arr, mapper, Literal["ignore"]|None na_action=None, bool convert=True)
Variables
dict _hashtables
unique1d = unique
int _MINIMUM_COMP_ARR_LEN = 1_000_000
dict _diff_special = {"float64", "float32", "int64", "int32", "int16", "int8"}
Detailed Description
Generic data algorithms. This module is experimental at the moment and not
intended for public consumption
Function Documentation
_check_object_for_strings()
str pandas.core.algorithms._check_object_for_strings (np.ndarray values) protected
Check if we can use string hashtable instead of object hashtable.
Parameters
----------
values : ndarray
Returns
-------
str
Definition at line 280 of file algorithms.py.
Referenced by _get_hashtable_algo().
_ensure_arraylike()
ArrayLike pandas.core.algorithms._ensure_arraylike (values, str func_name) protected
ensure that we are arraylike if not already
Definition at line 217 of file algorithms.py.
Referenced by factorize(), isin(), mode(), unique_with_mask(), and value_counts().
_ensure_data()
np.ndarray pandas.core.algorithms._ensure_data (ArrayLike values) protected
routine to ensure that our data is of the correct
input dtype for lower-level routines
This will coerce:
- ints -> int64
- uint -> uint64
- bool -> uint8
- datetimelike -> i8
- datetime64tz -> i8 (in local tz)
- categorical -> codes
Parameters
----------
values : np.ndarray or ExtensionArray
Returns
-------
np.ndarray
Definition at line 106 of file algorithms.py.
References _ensure_data().
Referenced by _ensure_data(), _get_hashtable_algo(), duplicated(), mode(), nunique_ints(), rank(), and value_counts_arraylike().
_get_hashtable_algo()
pandas.core.algorithms._get_hashtable_algo (np.ndarray values) protected
Parameters
----------
values : np.ndarray
Returns
-------
htable : HashTable subclass
values : ndarray
Definition at line 262 of file algorithms.py.
References _check_object_for_strings(), and _ensure_data().
Referenced by factorize_array(), safe_sort(), and unique_with_mask().
_reconstruct_data()
ArrayLike pandas.core.algorithms._reconstruct_data (ArrayLike values, DtypeObj dtype, AnyArrayLike original) protected
reverse of _ensure_data
Parameters
----------
values : np.ndarray or ExtensionArray
dtype : np.dtype or ExtensionDtype
original : AnyArrayLike
Returns
-------
ExtensionArray or np.ndarray
Definition at line 184 of file algorithms.py.
Referenced by factorize(), factorize_array(), mode(), unique_with_mask(), and value_counts_arraylike().
_sort_mixed()
AnyArrayLike pandas.core.algorithms._sort_mixed (values) protected
order ints before strings before nulls in 1d arrays
Definition at line 1582 of file algorithms.py.
References take().
Referenced by safe_sort().
_sort_tuples()
np.ndarray pandas.core.algorithms._sort_tuples (np.ndarray values) protected
Convert array of tuples (1d) to array of arrays (2d).
We need to keep the columns separately as they contain different types and
nans (can't use `np.sort` as it may fail when str and nan are mixed in a
column as types cannot be compared).
Definition at line 1597 of file algorithms.py.
Referenced by safe_sort().
diff()
pandas.core.algorithms.diff (arr, int n, AxisInt axis = 0)
difference of n between self,
analogous to s-s.shift(n)
Parameters
----------
arr : ndarray or ExtensionArray
n : int
    number of periods
axis : {0, 1}
    axis to shift on
stacklevel : int, default 3
    The stacklevel for the lost dtype warning.
Returns
-------
shifted
Definition at line 1339 of file algorithms.py.
duplicated()
npt.NDArray[np.bool_] pandas.core.algorithms.duplicated (ArrayLike values, Literal["first", "last", False] keep = "first", npt.NDArray[np.bool_] | None mask = None)
Return boolean ndarray denoting duplicate values.
Parameters
----------
values : np.ndarray or ExtensionArray
    Array over which to check for duplicate values.
keep : {'first', 'last', False}, default 'first'
    - ``first`` : Mark duplicates as ``True`` except for the first
      occurrence.
    - ``last`` : Mark duplicates as ``True`` except for the last
      occurrence.
    - False : Mark all duplicates as ``True``.
mask : ndarray[bool], optional
    array indicating which elements to exclude from checking
Returns
-------
duplicated : ndarray[bool]
Definition at line 994 of file algorithms.py.
References _ensure_data().
factorize()
tuple[np.ndarray, np.ndarray | Index] pandas.core.algorithms.factorize (values, bool sort = False, bool use_na_sentinel = True, int | None size_hint = None)
Encode the object as an enumerated type or categorical variable.
This method is useful for obtaining a numeric representation of an
array when all that matters is identifying distinct values. `factorize`
is available as both a top-level function :func:`pandas.factorize`,
and as a method :meth:`Series.factorize` and :meth:`Index.factorize`.
Parameters
----------
{values}{sort}
use_na_sentinel : bool, default True
    If True, the sentinel -1 will be used for NaN values. If False,
    NaN values will be encoded as non-negative integers and will not drop the
    NaN from the uniques of the values.
    .. versionadded:: 1.5.0
{size_hint}\
Returns
-------
codes : ndarray
    An integer ndarray that's an indexer into `uniques`.
    ``uniques.take(codes)`` will have the same values as `values`.
uniques : ndarray, Index, or Categorical
    The unique valid values. When `values` is Categorical, `uniques`
    is a Categorical. When `values` is some other pandas object, an
    `Index` is returned. Otherwise, a 1-D ndarray is returned.
    .. note::
       Even if there's a missing value in `values`, `uniques` will
       *not* contain an entry for it.
See Also
--------
cut : Discretize continuous-valued array.
unique : Find the unique value in an array.
Notes
-----
Reference :ref:`the user guide <reshaping.factorize>` for more examples.
Examples
--------
These examples all show factorize as a top-level method like
``pd.factorize(values)``. The results are identical for methods like
:meth:`Series.factorize`.
>>> codes, uniques = pd.factorize(np.array(['b', 'b', 'a', 'c', 'b'], dtype="O"))
>>> codes
array([0, 0, 1, 2, 0])
>>> uniques
array(['b', 'a', 'c'], dtype=object)
With ``sort=True``, the `uniques` will be sorted, and `codes` will be
shuffled so that the relationship is the maintained.
>>> codes, uniques = pd.factorize(np.array(['b', 'b', 'a', 'c', 'b'], dtype="O"),
...                               sort=True)
>>> codes
array([1, 1, 0, 2, 1])
>>> uniques
array(['a', 'b', 'c'], dtype=object)
When ``use_na_sentinel=True`` (the default), missing values are indicated in
the `codes` with the sentinel value ``-1`` and missing values are not
included in `uniques`.
>>> codes, uniques = pd.factorize(np.array(['b', None, 'a', 'c', 'b'], dtype="O"))
>>> codes
array([ 0, -1,  1,  2,  0])
>>> uniques
array(['b', 'a', 'c'], dtype=object)
Thus far, we've only factorized lists (which are internally coerced to
NumPy arrays). When factorizing pandas objects, the type of `uniques`
will differ. For Categoricals, a `Categorical` is returned.
>>> cat = pd.Categorical(['a', 'a', 'c'], categories=['a', 'b', 'c'])
>>> codes, uniques = pd.factorize(cat)
>>> codes
array([0, 0, 1])
>>> uniques
['a', 'c']
Categories (3, object): ['a', 'b', 'c']
Notice that ``'b'`` is in ``uniques.categories``, despite not being
present in ``cat.values``.
For all other pandas objects, an Index of the appropriate type is
returned.
>>> cat = pd.Series(['a', 'a', 'c'])
>>> codes, uniques = pd.factorize(cat)
>>> codes
array([0, 0, 1])
>>> uniques
Index(['a', 'c'], dtype='object')
If NaN is in the values, and we want to include NaN in the uniques of the
values, it can be achieved by setting ``use_na_sentinel=False``.
>>> values = np.array([1, 2, 1, np.nan])
>>> codes, uniques = pd.factorize(values)  # default: use_na_sentinel=True
>>> codes
array([ 0,  1,  0, -1])
>>> uniques
array([1., 2.])
>>> codes, uniques = pd.factorize(values, use_na_sentinel=False)
>>> codes
array([0, 1, 0, 2])
>>> uniques
array([ 1.,  2., nan])
Definition at line 632 of file algorithms.py.
References _ensure_arraylike(), _reconstruct_data(), factorize_array(), and safe_sort().
factorize_array()
tuple[npt.NDArray[np.intp], np.ndarray] pandas.core.algorithms.factorize_array (np.ndarray values, bool use_na_sentinel = True, int | None size_hint = None, object na_value = None, npt.NDArray[np.bool_] | None mask = None)
Factorize a numpy array to codes and uniques.
This doesn't do any coercion of types or unboxing before factorization.
Parameters
----------
values : ndarray
use_na_sentinel : bool, default True
    If True, the sentinel -1 will be used for NaN values. If False,
    NaN values will be encoded as non-negative integers and will not drop the
    NaN from the uniques of the values.
size_hint : int, optional
    Passed through to the hashtable's 'get_labels' method
na_value : object, optional
    A value in `values` to consider missing. Note: only use this
    parameter when you know that you don't have any values pandas would
    consider missing in the array (NaN for float data, iNaT for
    datetimes, etc.).
mask : ndarray[bool], optional
    If not None, the mask is used as indicator for missing values
    (True = missing, False = valid) instead of `na_value` or
    condition "val != val".
Returns
-------
codes : ndarray[np.intp]
uniques : ndarray
Definition at line 548 of file algorithms.py.
References _get_hashtable_algo(), and _reconstruct_data().
Referenced by factorize().
isin()
npt.NDArray[np.bool_] pandas.core.algorithms.isin (ListLike comps, ListLike values)
Compute the isin boolean array.
Parameters
----------
comps : list-like
values : list-like
Returns
-------
ndarray[bool]
    Same length as `comps`.
Definition at line 457 of file algorithms.py.
References _ensure_arraylike(), and isin().
Referenced by isin().
map_array()
np.ndarray | ExtensionArray | Index pandas.core.algorithms.map_array (ArrayLike arr, mapper, Literal["ignore"] | None na_action = None, bool convert = True)
Map values using an input mapping or function.
Parameters
----------
mapper : function, dict, or Series
    Mapping correspondence.
na_action : {None, 'ignore'}, default None
    If 'ignore', propagate NA values, without passing them to the
    mapping correspondence.
convert : bool, default True
    Try to find better dtype for elementwise function results. If
    False, leave as dtype=object.
Returns
-------
Union[ndarray, Index, ExtensionArray]
    The output of the mapping function applied to the array.
    If the function returns a tuple with more than one element
    a MultiIndex will be returned.
Definition at line 1667 of file algorithms.py.
mode()
ArrayLike pandas.core.algorithms.mode (ArrayLike values, bool dropna = True, npt.NDArray[np.bool_] | None mask = None)
Returns the mode(s) of an array.
Parameters
----------
values : array-like
    Array over which to check for duplicate values.
dropna : bool, default True
    Don't consider counts of NaN/NaT.
Returns
-------
np.ndarray or ExtensionArray
Definition at line 1023 of file algorithms.py.
References _ensure_arraylike(), _ensure_data(), _reconstruct_data(), and safe_sort().
nunique_ints()
int pandas.core.algorithms.nunique_ints (ArrayLike values)
Return the number of unique values for integer array-likes.
Significantly faster than pandas.unique for long enough sequences.
No checks are done to ensure input is integral.
Parameters
----------
values : 1d array-like
Returns
-------
int : The number of unique values in ``values``
Definition at line 404 of file algorithms.py.
References _ensure_data().
rank()
npt.NDArray[np.float64] pandas.core.algorithms.rank (ArrayLike values, AxisInt axis = 0, str method = "average", str na_option = "keep", bool ascending = True, bool pct = False)
Rank the values along a given axis.
Parameters
----------
values : np.ndarray or ExtensionArray
    Array whose values will be ranked. The number of dimensions in this
    array must not exceed 2.
axis : int, default 0
    Axis over which to perform rankings.
method : {'average', 'min', 'max', 'first', 'dense'}, default 'average'
    The method by which tiebreaks are broken during the ranking.
na_option : {'keep', 'top'}, default 'keep'
    The method by which NaNs are placed in the ranking.
    - ``keep``: rank each NaN value with a NaN ranking
    - ``top``: replace each NaN with either +/- inf so that they
               there are ranked at the top
ascending : bool, default True
    Whether or not the elements should be ranked in ascending order.
pct : bool, default False
    Whether or not to the display the returned rankings in integer form
    (e.g. 1, 2, 3) or in percentile form (e.g. 0.333..., 0.666..., 1).
Definition at line 1067 of file algorithms.py.
References _ensure_data().
safe_sort()
AnyArrayLike | tuple[AnyArrayLike, np.ndarray] pandas.core.algorithms.safe_sort (Index | ArrayLike values, npt.NDArray[np.intp] | None codes = None, bool use_na_sentinel = True, bool assume_unique = False, bool verify = True)
Sort ``values`` and reorder corresponding ``codes``.
``values`` should be unique if ``codes`` is not None.
Safe for use with mixed types (int, str), orders ints before strs.
Parameters
----------
values : list-like
    Sequence; must be unique if ``codes`` is not None.
codes : np.ndarray[intp] or None, default None
    Indices to ``values``. All out of bound indices are treated as
    "not found" and will be masked with ``-1``.
use_na_sentinel : bool, default True
    If True, the sentinel -1 will be used for NaN values. If False,
    NaN values will be encoded as non-negative integers and will not drop the
    NaN from the uniques of the values.
assume_unique : bool, default False
    When True, ``values`` are assumed to be unique, which can speed up
    the calculation. Ignored when ``codes`` is None.
verify : bool, default True
    Check if codes are out of bound for the values and put out of bound
    codes equal to ``-1``. If ``verify=False``, it is assumed there
    are no out of bound codes. Ignored when ``codes`` is None.
Returns
-------
ordered : AnyArrayLike
    Sorted ``values``
new_codes : ndarray
    Reordered ``codes``; returned when ``codes`` is not None.
Raises
------
TypeError
    * If ``values`` is not list-like or if ``codes`` is neither None
    nor list-like
    * If ``values`` cannot be sorted
ValueError
    * If ``codes`` is not None and ``values`` contain duplicates.
Definition at line 1452 of file algorithms.py.
References _get_hashtable_algo(), _sort_mixed(), _sort_tuples(), and unique().
Referenced by factorize(), and mode().
searchsorted()
npt.NDArray[np.intp] | np.intp pandas.core.algorithms.searchsorted (ArrayLike arr, NumpyValueArrayLike | ExtensionArray value, Literal["left", "right"] side = "left", NumpySorter | None sorter = None)
Find indices where elements should be inserted to maintain order.
Find the indices into a sorted array `arr` (a) such that, if the
corresponding elements in `value` were inserted before the indices,
the order of `arr` would be preserved.
Assuming that `arr` is sorted:
======  ================================
`side`  returned index `i` satisfies
======  ================================
left    ``arr[i-1] < value <= self[i]``
right   ``arr[i-1] <= value < self[i]``
======  ================================
Parameters
----------
arr: np.ndarray, ExtensionArray, Series
    Input array. If `sorter` is None, then it must be sorted in
    ascending order, otherwise `sorter` must be an array of indices
    that sort it.
value : array-like or scalar
    Values to insert into `arr`.
side : {'left', 'right'}, optional
    If 'left', the index of the first suitable location found is given.
    If 'right', return the last such index.  If there is no suitable
    index, return either 0 or N (where N is the length of `self`).
sorter : 1-D array-like, optional
    Optional array of integer indices that sort array a into ascending
    order. They are typically the result of argsort.
Returns
-------
array of ints or int
    If value is array-like, array of insertion points.
    If value is scalar, a single integer.
See Also
--------
numpy.searchsorted : Similar method from NumPy.
Definition at line 1248 of file algorithms.py.
take()
pandas.core.algorithms.take (arr, TakeIndexer indices, AxisInt axis = 0, bool allow_fill = False, fill_value = None)
Take elements from an array.
Parameters
----------
arr : array-like or scalar value
    Non array-likes (sequences/scalars without a dtype) are coerced
    to an ndarray.
    .. deprecated:: 2.1.0
        Passing an argument other than a numpy.ndarray, ExtensionArray,
        Index, or Series is deprecated.
indices : sequence of int or one-dimensional np.ndarray of int
    Indices to be taken.
axis : int, default 0
    The axis over which to select values.
allow_fill : bool, default False
    How to handle negative values in `indices`.
    * False: negative values in `indices` indicate positional indices
      from the right (the default). This is similar to :func:`numpy.take`.
    * True: negative values in `indices` indicate
      missing values. These values are set to `fill_value`. Any other
      negative values raise a ``ValueError``.
fill_value : any, optional
    Fill value to use for NA-indices when `allow_fill` is True.
    This may be ``None``, in which case the default NA value for
    the type (``self.dtype.na_value``) is used.
    For multi-dimensional `arr`, each *element* is filled with
    `fill_value`.
Returns
-------
ndarray or ExtensionArray
    Same type as the input.
Raises
------
IndexError
    When `indices` is out of bounds for the array.
ValueError
    When the indexer contains negative values other than ``-1``
    and `allow_fill` is True.
Notes
-----
When `allow_fill` is False, `indices` may be whatever dimensionality
is accepted by NumPy for `arr`.
When `allow_fill` is True, `indices` should be 1-D.
See Also
--------
numpy.take : Take elements from an array along an axis.
Examples
--------
>>> import pandas as pd
With the default ``allow_fill=False``, negative numbers indicate
positional indices from the right.
>>> pd.api.extensions.take(np.array([10, 20, 30]), [0, 0, -1])
array([10, 10, 30])
Setting ``allow_fill=True`` will place `fill_value` in those positions.
>>> pd.api.extensions.take(np.array([10, 20, 30]), [0, 0, -1], allow_fill=True)
array([10., 10., nan])
>>> pd.api.extensions.take(np.array([10, 20, 30]), [0, 0, -1], allow_fill=True,
...      fill_value=-10)
array([ 10,  10, -10])
Definition at line 1131 of file algorithms.py.
Referenced by _sort_mixed().
union_with_duplicates()
ArrayLike | Index pandas.core.algorithms.union_with_duplicates (ArrayLike | Index lvals, ArrayLike | Index rvals)
Extracts the union from lvals and rvals with respect to duplicates and nans in
both arrays.
Parameters
----------
lvals: np.ndarray or ExtensionArray
    left values which is ordered in front.
rvals: np.ndarray or ExtensionArray
    right values ordered after lvals.
Returns
-------
np.ndarray or ExtensionArray
    Containing the unsorted union of both arrays.
Notes
-----
Caller is responsible for ensuring lvals.dtype == rvals.dtype.
Definition at line 1612 of file algorithms.py.
References unique().
unique()
pandas.core.algorithms.unique (values)
Return unique values based on a hash table.
Uniques are returned in order of appearance. This does NOT sort.
Significantly faster than numpy.unique for long enough sequences.
Includes NA values.
Parameters
----------
values : 1d array-like
Returns
-------
numpy.ndarray or ExtensionArray
    The return can be:
    * Index : when the input is an Index
    * Categorical : when the input is a Categorical dtype
    * ndarray : when the input is a Series/ndarray
    Return numpy.ndarray or ExtensionArray.
See Also
--------
Index.unique : Return unique values from an Index.
Series.unique : Return unique values of Series object.
Examples
--------
>>> pd.unique(pd.Series([2, 1, 3, 3]))
array([2, 1, 3])
>>> pd.unique(pd.Series([2] + [1] * 5))
array([2, 1])
>>> pd.unique(pd.Series([pd.Timestamp("20160101"), pd.Timestamp("20160101")]))
array(['2016-01-01T00:00:00.000000000'], dtype='datetime64[ns]')
>>> pd.unique(
...     pd.Series(
...         [
...             pd.Timestamp("20160101", tz="US/Eastern"),
...             pd.Timestamp("20160101", tz="US/Eastern"),
...         ]
...)
...)
<DatetimeArray>
['2016-01-01 00:00:00-05:00']
Length: 1, dtype: datetime64[ns, US/Eastern]
>>> pd.unique(
...     pd.Index(
...         [
...             pd.Timestamp("20160101", tz="US/Eastern"),
...             pd.Timestamp("20160101", tz="US/Eastern"),
...         ]
...)
...)
DatetimeIndex(['2016-01-01 00:00:00-05:00'],
        dtype='datetime64[ns, US/Eastern]',
        freq=None)
>>> pd.unique(np.array(list("baabc"), dtype="O"))
array(['b', 'a', 'c'], dtype=object)
An unordered Categorical will return categories in the
order of appearance.
>>> pd.unique(pd.Series(pd.Categorical(list("baabc"))))
['b', 'a', 'c']
Categories (3, object): ['a', 'b', 'c']
>>> pd.unique(pd.Series(pd.Categorical(list("baabc"), categories=list("abc"))))
['b', 'a', 'c']
Categories (3, object): ['a', 'b', 'c']
An ordered Categorical preserves the category ordering.
>>> pd.unique(
...     pd.Series(
...         pd.Categorical(list("baabc"), categories=list("abc"), ordered=True)
...)
...)
['b', 'a', 'c']
Categories (3, object): ['a' < 'b' < 'c']
An array of tuples
>>> pd.unique(pd.Series([("a", "b"), ("b", "a"), ("a", "c"), ("b", "a")]).values)
array([('a', 'b'), ('b', 'a'), ('a', 'c')], dtype=object)
Definition at line 307 of file algorithms.py.
References unique_with_mask().
Referenced by safe_sort(), and union_with_duplicates().
unique_with_mask()
pandas.core.algorithms.unique_with_mask (values, npt.NDArray[np.bool_] | None mask = None)
See algorithms.unique for docs. Takes a mask for masked arrays.
Definition at line 427 of file algorithms.py.
References _ensure_arraylike(), _get_hashtable_algo(), and _reconstruct_data().
Referenced by unique().
value_counts()
Series pandas.core.algorithms.value_counts (values, bool sort = True, bool ascending = False, bool normalize = False, bins = None, bool dropna = True)
Compute a histogram of the counts of non-null values.
Parameters
----------
values : ndarray (1-d)
sort : bool, default True
    Sort by values
ascending : bool, default False
    Sort in ascending order
normalize: bool, default False
    If True then compute a relative histogram
bins : integer, optional
    Rather than count values, group them into half-open bins,
    convenience for pd.cut, only works with numeric data
dropna : bool, default True
    Don't include counts of NaN
Returns
-------
Series
Definition at line 815 of file algorithms.py.
References _ensure_arraylike(), and value_counts_arraylike().
value_counts_arraylike()
tuple[ArrayLike, npt.NDArray[np.int64], int] pandas.core.algorithms.value_counts_arraylike (np.ndarray values, bool dropna, npt.NDArray[np.bool_] | None mask = None)
Parameters
----------
values : np.ndarray
dropna : bool
mask : np.ndarray[bool] or None, default None
Returns
-------
uniques : np.ndarray
counts : np.ndarray[np.int64]
Definition at line 963 of file algorithms.py.
References _ensure_data(), and _reconstruct_data().
Referenced by value_counts().
value_counts_internal()
Series pandas.core.algorithms.value_counts_internal (values, bool sort = True, bool ascending = False, bool normalize = False, bins = None, bool dropna = True)
Definition at line 862 of file algorithms.py.
Variable Documentation
_diff_special
dict pandas.core.algorithms._diff_special = {"float64", "float32", "int64", "int32", "int16", "int8"} protected
Definition at line 1336 of file algorithms.py.
_hashtables
dict pandas.core.algorithms._hashtables protected
Initial value:
=  {
    "complex128": htable.Complex128HashTable,
    "complex64": htable.Complex64HashTable,
    "float64": htable.Float64HashTable,
    "float32": htable.Float32HashTable,
    "uint64": htable.UInt64HashTable,
    "uint32": htable.UInt32HashTable,
    "uint16": htable.UInt16HashTable,
    "uint8": htable.UInt8HashTable,
    "int64": htable.Int64HashTable,
    "int32": htable.Int32HashTable,
    "int16": htable.Int16HashTable,
    "int8": htable.Int8HashTable,
    "string": htable.StringHashTable,
    "object": htable.PyObjectHashTable,
}
Definition at line 244 of file algorithms.py.
_MINIMUM_COMP_ARR_LEN
int pandas.core.algorithms._MINIMUM_COMP_ARR_LEN = 1_000_000 protected
Definition at line 454 of file algorithms.py.
unique1d
pandas.core.algorithms.unique1d = unique
Definition at line 451 of file algorithms.py.