Code Cloning Analysis: axes_grid1.inset_locator.BboxConnectorPatch Class Reference
axes_grid1.inset_locator.BboxConnectorPatch Class Reference
Public Member Functions
__init__ (self, bbox1, bbox2, loc1a, loc2a, loc1b, loc2b, **kwargs)
get_path (self)
Public Member Functions inherited from axes_grid1.inset_locator.BboxConnector
__init__ (self, bbox1, bbox2, loc1, loc2=None, **kwargs)
Public Member Functions inherited from matplotlib.patches.Patch
__init__ (self, *, edgecolor=None, facecolor=None, color=None, linewidth=None, linestyle=None, antialiased=None, hatch=None, fill=True, capstyle=None, joinstyle=None, **kwargs)
get_verts (self)
contains (self, mouseevent, radius=None)
contains_point (self, point, radius=None)
contains_points (self, points, radius=None)
update_from (self, other)
get_extents (self)
get_transform (self)
get_data_transform (self)
get_patch_transform (self)
get_antialiased (self)
get_edgecolor (self)
get_facecolor (self)
get_linewidth (self)
get_linestyle (self)
set_antialiased (self, aa)
set_edgecolor (self, color)
set_facecolor (self, color)
set_color (self, c)
set_alpha (self, alpha)
set_linewidth (self, w)
set_linestyle (self, ls)
set_fill (self, b)
get_fill (self)
set_capstyle (self, s)
get_capstyle (self)
set_joinstyle (self, s)
get_joinstyle (self)
set_hatch (self, hatch)
get_hatch (self)
set_hatch_linewidth (self, lw)
get_hatch_linewidth (self)
draw (self, renderer)
get_window_extent (self, renderer=None)
Public Member Functions inherited from matplotlib.artist.Artist
__init_subclass__ (cls)
Public Attributes
loc1b = loc1b
loc2b = loc2b
Public Attributes inherited from axes_grid1.inset_locator.BboxConnector
bbox1 = bbox1
bbox2 = bbox2
loc1 = loc1
loc2 = loc2
Public Attributes inherited from matplotlib.patches.Patch
bool stale = True
Public Attributes inherited from matplotlib.artist.Artist
set = _prevent_rasterization(cls.draw)
Additional Inherited Members
Static Public Member Functions inherited from axes_grid1.inset_locator.BboxConnector
get_bbox_edge_pos (bbox, loc)
connect_bbox (bbox1, bbox2, loc1, loc2=None)
Static Public Attributes inherited from matplotlib.artist.Artist
int zorder = 0
Protected Member Functions inherited from matplotlib.patches.Patch
_process_radius (self, radius)
_set_edgecolor (self, color)
_set_facecolor (self, color)
_draw_paths_with_artist_properties (self, renderer, draw_path_args_list)
_convert_xy_units (self, xy)
Protected Attributes inherited from matplotlib.patches.Patch
_hatch_color = colors.to_rgba(mpl.rcParams['hatch.color'])
_hatch_linewidth = mpl.rcParams['hatch.linewidth']
_fill = bool(fill)
int _linewidth = 0
tuple _unscaled_dash_pattern = (0, None)
tuple _dash_pattern = (0, None)
_picker
_edgecolor = other._edgecolor
_facecolor = other._facecolor
_original_edgecolor = other._original_edgecolor
_original_facecolor = other._original_facecolor
_hatch = other._hatch
_transformSet = other.is_transform_set()
_antialiased = aa
_linestyle = ls
_capstyle = cs
_joinstyle = js
_url
_alpha
Static Protected Attributes inherited from matplotlib.patches.Patch
bool _edge_default = False
Properties inherited from matplotlib.patches.Patch
fill = property(get_fill, set_fill)
Detailed Description
Definition at line 194 of file inset_locator.py.
Constructor & Destructor Documentation
__init__()
axes_grid1.inset_locator.BboxConnectorPatch.__init__ (self, bbox1, bbox2, loc1a, loc2a, loc1b, loc2b, ** kwargs)
Connect two bboxes with a quadrilateral.
The quadrilateral is specified by two lines that start and end at
corners of the bboxes. The four sides of the quadrilateral are defined
by the two lines given, the line between the two corners specified in
*bbox1* and the line between the two corners specified in *bbox2*.
Parameters
----------
bbox1, bbox2 : `~matplotlib.transforms.Bbox`
    Bounding boxes to connect.
loc1a, loc2a, loc1b, loc2b : {1, 2, 3, 4}
    The first line connects corners *loc1a* of *bbox1* and *loc2a* of
    *bbox2*; the second line connects corners *loc1b* of *bbox1* and
    *loc2b* of *bbox2*.  Valid values are::
        'upper right'  : 1,
        'upper left'   : 2,
        'lower left'   : 3,
        'lower right'  : 4
**kwargs
    Patch properties for the line drawn:
    %(Patch:kwdoc)s
Definition at line 196 of file inset_locator.py.
References __init__(), loc1b, and loc2b.
Referenced by __init__(), sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
get_path()
axes_grid1.inset_locator.BboxConnectorPatch.get_path (self)
Return the path of this patch.
Reimplemented from axes_grid1.inset_locator.BboxConnector.
Definition at line 231 of file inset_locator.py.
References axes_grid1.inset_locator.BboxConnector.bbox1, axes_grid1.inset_locator.BboxConnector.bbox2, axes_grid1.inset_locator.BboxConnector.connect_bbox(), axes_grid1.inset_locator.BboxConnector.loc1, loc1b, axes_grid1.inset_locator.BboxConnector.loc2, and loc2b.
Member Data Documentation
loc1b
axes_grid1.inset_locator.BboxConnectorPatch.loc1b = loc1b
Definition at line 228 of file inset_locator.py.
Referenced by __init__(), and get_path().
loc2b
axes_grid1.inset_locator.BboxConnectorPatch.loc2b = loc2b
Definition at line 229 of file inset_locator.py.
Referenced by __init__(), and get_path().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/mpl_toolkits/axes_grid1/inset_locator.py