Code Cloning Analysis: matplotlib.category.StrCategoryConverter Class Reference
matplotlib.category.StrCategoryConverter Class Reference
Static Public Member Functions
convert (value, unit, axis)
axisinfo (unit, axis)
default_units (data, axis)
Static Protected Member Functions
_validate_unit (unit)
Detailed Description
Definition at line 26 of file category.py.
Member Function Documentation
_validate_unit()
matplotlib.category.StrCategoryConverter._validate_unit (unit) static protected
Definition at line 112 of file category.py.
axisinfo()
matplotlib.category.StrCategoryConverter.axisinfo (unit, axis) static
Set the default axis ticks and labels.
Parameters
----------
unit : `.UnitData`
    object string unit information for value
axis : `~matplotlib.axis.Axis`
    axis for which information is being set
    .. note:: *axis* is not used
Returns
-------
`~matplotlib.units.AxisInfo`
    Information to support default tick labeling
Reimplemented from matplotlib.units.ConversionInterface.
Definition at line 62 of file category.py.
convert()
matplotlib.category.StrCategoryConverter.convert (value, unit, axis) static
Convert strings in *value* to floats using mapping information stored
in the *unit* object.
Parameters
----------
value : str or iterable
    Value or list of values to be converted.
unit : `.UnitData`
    An object mapping strings to integers.
axis : `~matplotlib.axis.Axis`
    The axis on which the converted value is plotted.
    .. note:: *axis* is unused.
Returns
-------
float or `~numpy.ndarray` of float
Reimplemented from matplotlib.units.ConversionInterface.
Definition at line 28 of file category.py.
Referenced by matplotlib.testing.jpl_units.Epoch.Epoch.__add__(), matplotlib.testing.jpl_units.Epoch.Epoch.__init__(), matplotlib.testing.jpl_units.Epoch.Epoch.__sub__(), matplotlib.testing.jpl_units.Epoch.Epoch._cmp(), pandas.core.computation.engines.NumExprEngine._evaluate(), pandas.core.internals.blocks.Block.convert(), PIL.Image.Image.reduce(), PIL.Image.Image.resize(), and PIL.Image.Image.transform().
default_units()
matplotlib.category.StrCategoryConverter.default_units (data, axis) static
Set and update the `~matplotlib.axis.Axis` units.
Parameters
----------
data : str or iterable of str
axis : `~matplotlib.axis.Axis`
    axis on which the data is plotted
Returns
-------
`.UnitData`
    object storing string to integer mapping
Reimplemented from matplotlib.units.ConversionInterface.
Definition at line 89 of file category.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/category.py