Code Cloning Analysis: numpy.lib.tests.test_arraysetops.TestSetOps Class Reference
numpy.lib.tests.test_arraysetops.TestSetOps Class Reference
Public Member Functions
test_intersect1d (self)
test_intersect1d_array_like (self)
test_intersect1d_indices (self)
test_setxor1d (self)
test_ediff1d (self)
test_ediff1d_forbidden_type_casts (self, ary, prepend, append, expected)
test_ediff1d_scalar_handling (self, ary, prepend, append, expected)
test_isin (self, kind)
test_in1d (self, kind)
test_in1d_char_array (self)
test_in1d_invert (self, kind)
test_in1d_ravel (self, kind)
test_in1d_hit_alternate_algorithm (self)
test_in1d_boolean (self, kind)
test_in1d_timedelta (self, kind)
test_in1d_table_timedelta_fails (self)
test_in1d_mixed_dtype (self, dtype1, dtype2, kind)
test_in1d_mixed_boolean (self, kind)
test_in1d_first_array_is_object (self)
test_in1d_second_array_is_object (self)
test_in1d_both_arrays_are_object (self)
test_in1d_both_arrays_have_structured_dtype (self)
test_in1d_with_arrays_containing_tuples (self)
test_in1d_errors (self)
test_union1d (self)
test_setdiff1d (self)
test_setdiff1d_unique (self)
test_setdiff1d_char_array (self)
test_manyways (self)
Detailed Description
Definition at line 14 of file test_arraysetops.py.
Member Function Documentation
test_ediff1d()
numpy.lib.tests.test_arraysetops.TestSetOps.test_ediff1d (self)
Definition at line 109 of file test_arraysetops.py.
test_ediff1d_forbidden_type_casts()
numpy.lib.tests.test_arraysetops.TestSetOps.test_ediff1d_forbidden_type_casts (self, ary, prepend, append, expected)
Definition at line 151 of file test_arraysetops.py.
test_ediff1d_scalar_handling()
numpy.lib.tests.test_arraysetops.TestSetOps.test_ediff1d_scalar_handling (self, ary, prepend, append, expected)
Definition at line 184 of file test_arraysetops.py.
test_in1d()
numpy.lib.tests.test_arraysetops.TestSetOps.test_in1d (self, kind)
Definition at line 260 of file test_arraysetops.py.
test_in1d_boolean()
numpy.lib.tests.test_arraysetops.TestSetOps.test_in1d_boolean (self, kind)
Test that in1d works for boolean input
Definition at line 389 of file test_arraysetops.py.
References numpy.lib.arraysetops.in1d().
test_in1d_both_arrays_are_object()
numpy.lib.tests.test_arraysetops.TestSetOps.test_in1d_both_arrays_are_object (self)
Definition at line 479 of file test_arraysetops.py.
test_in1d_both_arrays_have_structured_dtype()
numpy.lib.tests.test_arraysetops.TestSetOps.test_in1d_both_arrays_have_structured_dtype (self)
Definition at line 486 of file test_arraysetops.py.
test_in1d_char_array()
numpy.lib.tests.test_arraysetops.TestSetOps.test_in1d_char_array (self)
Definition at line 321 of file test_arraysetops.py.
test_in1d_errors()
numpy.lib.tests.test_arraysetops.TestSetOps.test_in1d_errors (self)
Test that in1d raises expected errors.
Definition at line 529 of file test_arraysetops.py.
References numpy.lib.arraysetops.intersect1d(), numpy.lib.arraysetops.setdiff1d(), numpy.lib.arraysetops.setxor1d(), and numpy.lib.arraysetops.union1d().
test_in1d_first_array_is_object()
numpy.lib.tests.test_arraysetops.TestSetOps.test_in1d_first_array_is_object (self)
Definition at line 465 of file test_arraysetops.py.
test_in1d_hit_alternate_algorithm()
numpy.lib.tests.test_arraysetops.TestSetOps.test_in1d_hit_alternate_algorithm (self)
Hit the standard isin code with integers
Definition at line 372 of file test_arraysetops.py.
References numpy.lib.arraysetops.in1d().
test_in1d_invert()
numpy.lib.tests.test_arraysetops.TestSetOps.test_in1d_invert (self, kind)
Definition at line 331 of file test_arraysetops.py.
test_in1d_mixed_boolean()
numpy.lib.tests.test_arraysetops.TestSetOps.test_in1d_mixed_boolean (self, kind)
Test that in1d works as expected for bool/int input.
Definition at line 453 of file test_arraysetops.py.
References numpy.lib.arraysetops.in1d().
test_in1d_mixed_dtype()
numpy.lib.tests.test_arraysetops.TestSetOps.test_in1d_mixed_dtype (self, dtype1, dtype2, kind)
Test that in1d works as expected for mixed dtype input.
Definition at line 429 of file test_arraysetops.py.
References numpy.core.fromnumeric.any(), and numpy.lib.arraysetops.in1d().
test_in1d_ravel()
numpy.lib.tests.test_arraysetops.TestSetOps.test_in1d_ravel (self, kind)
Definition at line 352 of file test_arraysetops.py.
test_in1d_second_array_is_object()
numpy.lib.tests.test_arraysetops.TestSetOps.test_in1d_second_array_is_object (self)
Definition at line 472 of file test_arraysetops.py.
test_in1d_table_timedelta_fails()
numpy.lib.tests.test_arraysetops.TestSetOps.test_in1d_table_timedelta_fails (self)
Definition at line 410 of file test_arraysetops.py.
test_in1d_timedelta()
numpy.lib.tests.test_arraysetops.TestSetOps.test_in1d_timedelta (self, kind)
Test that in1d works for timedelta input
Definition at line 400 of file test_arraysetops.py.
References numpy.lib.arraysetops.in1d().
test_in1d_with_arrays_containing_tuples()
numpy.lib.tests.test_arraysetops.TestSetOps.test_in1d_with_arrays_containing_tuples (self)
Definition at line 496 of file test_arraysetops.py.
test_intersect1d()
numpy.lib.tests.test_arraysetops.TestSetOps.test_intersect1d (self)
Definition at line 16 of file test_arraysetops.py.
test_intersect1d_array_like()
numpy.lib.tests.test_arraysetops.TestSetOps.test_intersect1d_array_like (self)
Definition at line 34 of file test_arraysetops.py.
test_intersect1d_indices()
numpy.lib.tests.test_arraysetops.TestSetOps.test_intersect1d_indices (self)
Definition at line 46 of file test_arraysetops.py.
test_isin()
numpy.lib.tests.test_arraysetops.TestSetOps.test_isin (self, kind)
Definition at line 199 of file test_arraysetops.py.
test_manyways()
numpy.lib.tests.test_arraysetops.TestSetOps.test_manyways (self)
Definition at line 611 of file test_arraysetops.py.
test_setdiff1d()
numpy.lib.tests.test_arraysetops.TestSetOps.test_setdiff1d (self)
Definition at line 581 of file test_arraysetops.py.
test_setdiff1d_char_array()
numpy.lib.tests.test_arraysetops.TestSetOps.test_setdiff1d_char_array (self)
Definition at line 606 of file test_arraysetops.py.
test_setdiff1d_unique()
numpy.lib.tests.test_arraysetops.TestSetOps.test_setdiff1d_unique (self)
Definition at line 599 of file test_arraysetops.py.
test_setxor1d()
numpy.lib.tests.test_arraysetops.TestSetOps.test_setxor1d (self)
Definition at line 85 of file test_arraysetops.py.
test_union1d()
numpy.lib.tests.test_arraysetops.TestSetOps.test_union1d (self)
Definition at line 563 of file test_arraysetops.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/lib/tests/test_arraysetops.py