Code Cloning Analysis: numpy.lib.tests.test_function_base.TestInterp Class Reference
numpy.lib.tests.test_function_base.TestInterp Class Reference
Public Member Functions
test_exceptions (self)
test_basic (self)
test_right_left_behavior (self)
test_scalar_interpolation_point (self)
test_non_finite_behavior_exact_x (self)
sc (self, request)
test_non_finite_any_nan (self, sc)
test_non_finite_inf (self, sc)
test_non_finite_half_inf_xf (self, sc)
test_non_finite_half_inf_x (self, sc)
test_non_finite_half_inf_f (self, sc)
test_complex_interp (self)
test_zero_dimensional_interpolation_point (self)
test_if_len_x_is_small (self)
test_period (self)
Detailed Description
Definition at line 2816 of file test_function_base.py.
Member Function Documentation
sc()
numpy.lib.tests.test_function_base.TestInterp.sc (self, request)
 scale function used by the below tests
Definition at line 2902 of file test_function_base.py.
Referenced by test_non_finite_any_nan(), test_non_finite_half_inf_f(), test_non_finite_half_inf_x(), test_non_finite_half_inf_xf(), and test_non_finite_inf().
test_basic()
numpy.lib.tests.test_function_base.TestInterp.test_basic (self)
Definition at line 2825 of file test_function_base.py.
test_complex_interp()
numpy.lib.tests.test_function_base.TestInterp.test_complex_interp (self)
Definition at line 2949 of file test_function_base.py.
test_exceptions()
numpy.lib.tests.test_function_base.TestInterp.test_exceptions (self)
Definition at line 2818 of file test_function_base.py.
test_if_len_x_is_small()
numpy.lib.tests.test_function_base.TestInterp.test_if_len_x_is_small (self)
Definition at line 2994 of file test_function_base.py.
test_non_finite_any_nan()
numpy.lib.tests.test_function_base.TestInterp.test_non_finite_any_nan (self, sc)
 test that nans are propagated
Definition at line 2906 of file test_function_base.py.
References sc().
test_non_finite_behavior_exact_x()
numpy.lib.tests.test_function_base.TestInterp.test_non_finite_behavior_exact_x (self)
Definition at line 2883 of file test_function_base.py.
test_non_finite_half_inf_f()
numpy.lib.tests.test_function_base.TestInterp.test_non_finite_half_inf_f (self, sc)
 Test interp where the f axis has a bound at inf
Definition at line 2940 of file test_function_base.py.
References numpy.core.fromnumeric.reshape(), and sc().
test_non_finite_half_inf_x()
numpy.lib.tests.test_function_base.TestInterp.test_non_finite_half_inf_x (self, sc)
 Test interp where the x axis has a bound at inf
Definition at line 2933 of file test_function_base.py.
References sc().
test_non_finite_half_inf_xf()
numpy.lib.tests.test_function_base.TestInterp.test_non_finite_half_inf_xf (self, sc)
 Test that interp where both axes have a bound at inf gives nan
Definition at line 2922 of file test_function_base.py.
References sc().
test_non_finite_inf()
numpy.lib.tests.test_function_base.TestInterp.test_non_finite_inf (self, sc)
 Test that interp between opposite infs gives nan
Definition at line 2913 of file test_function_base.py.
References sc().
test_period()
numpy.lib.tests.test_function_base.TestInterp.test_period (self)
Definition at line 2999 of file test_function_base.py.
test_right_left_behavior()
numpy.lib.tests.test_function_base.TestInterp.test_right_left_behavior (self)
Definition at line 2831 of file test_function_base.py.
test_scalar_interpolation_point()
numpy.lib.tests.test_function_base.TestInterp.test_scalar_interpolation_point (self)
Definition at line 2869 of file test_function_base.py.
test_zero_dimensional_interpolation_point()
numpy.lib.tests.test_function_base.TestInterp.test_zero_dimensional_interpolation_point (self)
Definition at line 2977 of file test_function_base.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/lib/tests/test_function_base.py