Code Cloning Analysis: fontTools.misc.psCharStrings.T1OutlineExtractor Class Reference
fontTools.misc.psCharStrings.T1OutlineExtractor Class Reference
Public Member Functions
__init__ (self, pen, subrs)
reset (self)
endPath (self)
popallWidth (self, evenOdd=0)
exch (self)
op_rmoveto (self, index)
op_hmoveto (self, index)
op_vmoveto (self, index)
op_closepath (self, index)
op_setcurrentpoint (self, index)
op_endchar (self, index)
op_hsbw (self, index)
op_sbw (self, index)
op_callsubr (self, index)
op_callothersubr (self, index)
op_pop (self, index)
doFlex (self)
op_dotsection (self, index)
op_hstem3 (self, index)
op_seac (self, index)
op_vstem3 (self, index)
Public Member Functions inherited from fontTools.misc.psCharStrings.T2OutlineExtractor
__init__ (self, pen, localSubrs, globalSubrs, nominalWidthX, defaultWidthX, private=None, blender=None)
execute (self, charString)
rMoveTo (self, point)
rLineTo (self, point)
rCurveTo (self, pt1, pt2, pt3)
closePath (self)
op_rlineto (self, index)
op_hlineto (self, index)
op_vlineto (self, index)
op_rrcurveto (self, index)
op_rcurveline (self, index)
op_rlinecurve (self, index)
op_vvcurveto (self, index)
op_hhcurveto (self, index)
op_vhcurveto (self, index)
op_hvcurveto (self, index)
op_hflex (self, index)
op_flex (self, index)
op_hflex1 (self, index)
op_flex1 (self, index)
op_and (self, index)
op_or (self, index)
op_not (self, index)
op_store (self, index)
op_abs (self, index)
op_add (self, index)
op_sub (self, index)
op_div (self, index)
op_load (self, index)
op_neg (self, index)
op_eq (self, index)
op_drop (self, index)
op_put (self, index)
op_get (self, index)
op_ifelse (self, index)
op_random (self, index)
op_mul (self, index)
op_sqrt (self, index)
op_dup (self, index)
op_exch (self, index)
op_index (self, index)
op_roll (self, index)
alternatingLineto (self, isHorizontal)
vcurveto (self, args)
hcurveto (self, args)
Public Member Functions inherited from fontTools.misc.psCharStrings.T2WidthExtractor
__init__ (self, localSubrs, globalSubrs, nominalWidthX, defaultWidthX, private=None, blender=None)
countHints (self)
Public Member Functions inherited from fontTools.misc.psCharStrings.SimpleT2Decompiler
__init__ (self, localSubrs, globalSubrs, private=None, blender=None)
pop (self)
popall (self)
push (self, value)
op_return (self, index)
op_ignore (self, index)
op_callgsubr (self, index)
op_hstem (self, index)
op_vstem (self, index)
op_hstemhm (self, index)
op_vstemhm (self, index)
op_hintmask (self, index)
op_blend (self, index)
op_vsindex (self, index)
Public Attributes
subrs = subrs
int flexing = 0
int sbx = 0
Public Attributes inherited from fontTools.misc.psCharStrings.T2OutlineExtractor
pen = pen
int subrLevel = 0
tuple currentPoint = (0, 0)
int sawMoveTo = 0
Public Attributes inherited from fontTools.misc.psCharStrings.T2WidthExtractor
nominalWidthX = nominalWidthX
defaultWidthX = defaultWidthX
int gotWidth = 0
int width = 0
Public Attributes inherited from fontTools.misc.psCharStrings.SimpleT2Decompiler
localSubrs = localSubrs
localBias = calcSubrBias(localSubrs)
globalSubrs = globalSubrs
globalBias = calcSubrBias(globalSubrs)
private = private
blender = blender
list callingStack = []
list operandStack = []
int hintCount = 0
int hintMaskBytes = 0
int numRegions = 0
int vsIndex = 0
Additional Inherited Members
Static Public Attributes inherited from fontTools.misc.psCharStrings.SimpleT2Decompiler
op_cntrmask = op_hintmask
Protected Member Functions inherited from fontTools.misc.psCharStrings.T2OutlineExtractor
_nextPoint (self, point)
Detailed Description
Definition at line 961 of file psCharStrings.py.
Constructor & Destructor Documentation
__init__()
fontTools.misc.psCharStrings.T1OutlineExtractor.__init__ (self, pen, subrs)
Definition at line 962 of file psCharStrings.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
doFlex()
fontTools.misc.psCharStrings.T1OutlineExtractor.doFlex (self)
Definition at line 1051 of file psCharStrings.py.
endPath()
fontTools.misc.psCharStrings.T1OutlineExtractor.endPath (self)
Reimplemented from fontTools.misc.psCharStrings.T2OutlineExtractor.
Definition at line 973 of file psCharStrings.py.
exch()
fontTools.misc.psCharStrings.T1OutlineExtractor.exch (self)
Definition at line 981 of file psCharStrings.py.
op_callothersubr()
fontTools.misc.psCharStrings.T1OutlineExtractor.op_callothersubr (self, index)
Definition at line 1037 of file psCharStrings.py.
op_callsubr()
fontTools.misc.psCharStrings.T1OutlineExtractor.op_callsubr (self, index)
Reimplemented from fontTools.misc.psCharStrings.SimpleT2Decompiler.
Definition at line 1032 of file psCharStrings.py.
op_closepath()
fontTools.misc.psCharStrings.T1OutlineExtractor.op_closepath (self, index)
Definition at line 1011 of file psCharStrings.py.
op_dotsection()
fontTools.misc.psCharStrings.T1OutlineExtractor.op_dotsection (self, index)
Definition at line 1093 of file psCharStrings.py.
op_endchar()
fontTools.misc.psCharStrings.T1OutlineExtractor.op_endchar (self, index)
Reimplemented from fontTools.misc.psCharStrings.T2OutlineExtractor.
Definition at line 1019 of file psCharStrings.py.
op_hmoveto()
fontTools.misc.psCharStrings.T1OutlineExtractor.op_hmoveto (self, index)
Reimplemented from fontTools.misc.psCharStrings.T2OutlineExtractor.
Definition at line 994 of file psCharStrings.py.
op_hsbw()
fontTools.misc.psCharStrings.T1OutlineExtractor.op_hsbw (self, index)
Definition at line 1022 of file psCharStrings.py.
op_hstem3()
fontTools.misc.psCharStrings.T1OutlineExtractor.op_hstem3 (self, index)
Definition at line 1096 of file psCharStrings.py.
op_pop()
fontTools.misc.psCharStrings.T1OutlineExtractor.op_pop (self, index)
Definition at line 1048 of file psCharStrings.py.
op_rmoveto()
fontTools.misc.psCharStrings.T1OutlineExtractor.op_rmoveto (self, index)
Reimplemented from fontTools.misc.psCharStrings.T2OutlineExtractor.
Definition at line 988 of file psCharStrings.py.
op_sbw()
fontTools.misc.psCharStrings.T1OutlineExtractor.op_sbw (self, index)
Definition at line 1028 of file psCharStrings.py.
op_seac()
fontTools.misc.psCharStrings.T1OutlineExtractor.op_seac (self, index)
Definition at line 1099 of file psCharStrings.py.
op_setcurrentpoint()
fontTools.misc.psCharStrings.T1OutlineExtractor.op_setcurrentpoint (self, index)
Definition at line 1014 of file psCharStrings.py.
op_vmoveto()
fontTools.misc.psCharStrings.T1OutlineExtractor.op_vmoveto (self, index)
Reimplemented from fontTools.misc.psCharStrings.T2OutlineExtractor.
Definition at line 1002 of file psCharStrings.py.
op_vstem3()
fontTools.misc.psCharStrings.T1OutlineExtractor.op_vstem3 (self, index)
Definition at line 1110 of file psCharStrings.py.
popallWidth()
fontTools.misc.psCharStrings.T1OutlineExtractor.popallWidth (self, evenOdd = 0)
Reimplemented from fontTools.misc.psCharStrings.T2WidthExtractor.
Definition at line 978 of file psCharStrings.py.
reset()
fontTools.misc.psCharStrings.T1OutlineExtractor.reset (self)
Reimplemented from fontTools.misc.psCharStrings.T2OutlineExtractor.
Definition at line 967 of file psCharStrings.py.
Referenced by PIL.TiffImagePlugin.ImageFileDirectory_v2.__init__(), scipy._lib._docscrape.Reader.__init__(), and PIL.TiffImagePlugin.ImageFileDirectory_v2.named().
Member Data Documentation
flexing
int fontTools.misc.psCharStrings.T1OutlineExtractor.flexing = 0
Definition at line 968 of file psCharStrings.py.
sbx
int fontTools.misc.psCharStrings.T1OutlineExtractor.sbx = 0
Definition at line 970 of file psCharStrings.py.
subrs
fontTools.misc.psCharStrings.T1OutlineExtractor.subrs = subrs
Definition at line 964 of file psCharStrings.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/misc/psCharStrings.py