Code Cloning Analysis: fontTools.varLib.cff.MergeOutlineExtractor Class Reference
fontTools.varLib.cff.MergeOutlineExtractor Class Reference
Public Member Functions
__init__ (self, pen, localSubrs, globalSubrs, nominalWidthX, defaultWidthX, private=None, blender=None)
countHints (self)
op_hstem (self, index)
op_vstem (self, index)
op_hstemhm (self, index)
op_vstemhm (self, index)
op_hintmask (self, index)
op_cntrmask (self, index)
Public Member Functions inherited from fontTools.varLib.cff.CFFToCFF2OutlineExtractor
popallWidth (self, evenOdd=0)
Public Member Functions inherited from fontTools.misc.psCharStrings.T2OutlineExtractor
__init__ (self, pen, localSubrs, globalSubrs, nominalWidthX, defaultWidthX, private=None, blender=None)
reset (self)
execute (self, charString)
rMoveTo (self, point)
rLineTo (self, point)
rCurveTo (self, pt1, pt2, pt3)
closePath (self)
endPath (self)
op_rmoveto (self, index)
op_hmoveto (self, index)
op_vmoveto (self, index)
op_endchar (self, index)
op_rlineto (self, index)
op_hlineto (self, index)
op_vlineto (self, index)
op_rrcurveto (self, index)
op_rcurveline (self, index)
op_rlinecurve (self, index)
op_vvcurveto (self, index)
op_hhcurveto (self, index)
op_vhcurveto (self, index)
op_hvcurveto (self, index)
op_hflex (self, index)
op_flex (self, index)
op_hflex1 (self, index)
op_flex1 (self, index)
op_and (self, index)
op_or (self, index)
op_not (self, index)
op_store (self, index)
op_abs (self, index)
op_add (self, index)
op_sub (self, index)
op_div (self, index)
op_load (self, index)
op_neg (self, index)
op_eq (self, index)
op_drop (self, index)
op_put (self, index)
op_get (self, index)
op_ifelse (self, index)
op_random (self, index)
op_mul (self, index)
op_sqrt (self, index)
op_dup (self, index)
op_exch (self, index)
op_index (self, index)
op_roll (self, index)
alternatingLineto (self, isHorizontal)
vcurveto (self, args)
hcurveto (self, args)
Public Member Functions inherited from fontTools.misc.psCharStrings.T2WidthExtractor
__init__ (self, localSubrs, globalSubrs, nominalWidthX, defaultWidthX, private=None, blender=None)
Public Member Functions inherited from fontTools.misc.psCharStrings.SimpleT2Decompiler
__init__ (self, localSubrs, globalSubrs, private=None, blender=None)
pop (self)
popall (self)
push (self, value)
op_return (self, index)
op_ignore (self, index)
op_callsubr (self, index)
op_callgsubr (self, index)
op_blend (self, index)
op_vsindex (self, index)
Protected Member Functions
_hint_op (self, type, args)
_get_hintmask (self, index)
Protected Member Functions inherited from fontTools.misc.psCharStrings.T2OutlineExtractor
_nextPoint (self, point)
Additional Inherited Members
Public Attributes inherited from fontTools.misc.psCharStrings.T2OutlineExtractor
pen = pen
int subrLevel = 0
tuple currentPoint = (0, 0)
int sawMoveTo = 0
Public Attributes inherited from fontTools.misc.psCharStrings.T2WidthExtractor
nominalWidthX = nominalWidthX
defaultWidthX = defaultWidthX
int gotWidth = 0
int width = 0
Public Attributes inherited from fontTools.misc.psCharStrings.SimpleT2Decompiler
localSubrs = localSubrs
localBias = calcSubrBias(localSubrs)
globalSubrs = globalSubrs
globalBias = calcSubrBias(globalSubrs)
private = private
blender = blender
list callingStack = []
list operandStack = []
int hintCount = 0
int hintMaskBytes = 0
int numRegions = 0
int vsIndex = 0
Detailed Description
Used to extract the charstring commands - including hints - from a
CFF charstring in order to merge it as another set of region data
into a CFF2 variable font charstring.
Definition at line 402 of file cff.py.
Constructor & Destructor Documentation
__init__()
fontTools.varLib.cff.MergeOutlineExtractor.__init__ (self, pen, localSubrs, globalSubrs, nominalWidthX, defaultWidthX, private = None, blender = None)
Definition at line 407 of file cff.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_get_hintmask()
fontTools.varLib.cff.MergeOutlineExtractor._get_hintmask (self, index) protected
Definition at line 445 of file cff.py.
_hint_op()
fontTools.varLib.cff.MergeOutlineExtractor._hint_op (self, type, args) protected
Definition at line 426 of file cff.py.
countHints()
fontTools.varLib.cff.MergeOutlineExtractor.countHints (self)
Reimplemented from fontTools.misc.psCharStrings.T2WidthExtractor.
Definition at line 421 of file cff.py.
op_cntrmask()
fontTools.varLib.cff.MergeOutlineExtractor.op_cntrmask (self, index)
Reimplemented from fontTools.misc.psCharStrings.SimpleT2Decompiler.
Definition at line 459 of file cff.py.
op_hintmask()
fontTools.varLib.cff.MergeOutlineExtractor.op_hintmask (self, index)
Reimplemented from fontTools.misc.psCharStrings.SimpleT2Decompiler.
Definition at line 454 of file cff.py.
op_hstem()
fontTools.varLib.cff.MergeOutlineExtractor.op_hstem (self, index)
Reimplemented from fontTools.misc.psCharStrings.SimpleT2Decompiler.
Definition at line 429 of file cff.py.
op_hstemhm()
fontTools.varLib.cff.MergeOutlineExtractor.op_hstemhm (self, index)
Reimplemented from fontTools.misc.psCharStrings.SimpleT2Decompiler.
Definition at line 437 of file cff.py.
op_vstem()
fontTools.varLib.cff.MergeOutlineExtractor.op_vstem (self, index)
Reimplemented from fontTools.misc.psCharStrings.SimpleT2Decompiler.
Definition at line 433 of file cff.py.
op_vstemhm()
fontTools.varLib.cff.MergeOutlineExtractor.op_vstemhm (self, index)
Reimplemented from fontTools.misc.psCharStrings.SimpleT2Decompiler.
Definition at line 441 of file cff.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/varLib/cff.py