Code Cloning Analysis: axisartist.axislines.GridHelperBase Class Reference
axisartist.axislines.GridHelperBase Class Reference
Public Member Functions
__init__ (self)
update_lim (self, axes)
get_gridlines (self, which, axis)
Protected Member Functions
_update_grid (self, x1, y1, x2, y2)
Protected Attributes
tuple _old_limits = None
Detailed Description
Definition at line 278 of file axislines.py.
Constructor & Destructor Documentation
__init__()
axisartist.axislines.GridHelperBase.__init__ (self)
Definition at line 280 of file axislines.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_update_grid()
axisartist.axislines.GridHelperBase._update_grid (self, x1, y1, x2, y2) protected
Cache relevant computations when the axes limits have changed.
Reimplemented in axisartist.floating_axes.GridHelperCurveLinear, and axisartist.grid_helper_curvelinear.GridHelperCurveLinear.
Definition at line 291 of file axislines.py.
get_gridlines()
axisartist.axislines.GridHelperBase.get_gridlines (self, which, axis)
Return list of grid lines as a list of paths (list of points).
Parameters
----------
which : {"both", "major", "minor"}
axis : {"both", "x", "y"}
Reimplemented in axisartist.axislines.GridHelperRectlinear, axisartist.floating_axes.GridHelperCurveLinear, and axisartist.grid_helper_curvelinear.GridHelperCurveLinear.
Definition at line 294 of file axislines.py.
update_lim()
axisartist.axislines.GridHelperBase.update_lim (self, axes)
Definition at line 284 of file axislines.py.
Member Data Documentation
_old_limits
tuple axisartist.axislines.GridHelperBase._old_limits = None protected
Definition at line 281 of file axislines.py.
Referenced by axisartist.grid_helper_curvelinear.GridHelperCurveLinear.__init__().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/mpl_toolkits/axisartist/axislines.py