Code Cloning Analysis: scipy.signal.tests.mpsig Namespace Reference
scipy.signal.tests.mpsig Namespace Reference
Functions
_prod (seq)
_relative_degree (z, p)
_zpkbilinear (z, p, k, fs)
_zpklp2lp (z, p, k, wo=1)
_butter_analog_poles (n)
butter_lp (n, Wn)
zpkfreqz (z, p, k, worN=None)
Variables
mpmath = None
Detailed Description
Some signal functions implemented using mpmath.
Function Documentation
_butter_analog_poles()
scipy.signal.tests.mpsig._butter_analog_poles (n) protected
Poles of an analog Butterworth lowpass filter.
This is the same calculation as scipy.signal.buttap(n) or
scipy.signal.butter(n, 1, analog=True, output='zpk'), but mpmath is used,
and only the poles are returned.
Definition at line 71 of file mpsig.py.
Referenced by butter_lp().
_prod()
scipy.signal.tests.mpsig._prod (seq) protected
Returns the product of the elements in the sequence `seq`.
Definition at line 11 of file mpsig.py.
Referenced by _zpkbilinear(), and zpkfreqz().
_relative_degree()
scipy.signal.tests.mpsig._relative_degree (z, p) protected
Return relative degree of transfer function from zeros and poles.
This is simply len(p) - len(z), which must be nonnegative.
A ValueError is raised if len(p) < len(z).
Definition at line 19 of file mpsig.py.
Referenced by _zpkbilinear(), and _zpklp2lp().
_zpkbilinear()
scipy.signal.tests.mpsig._zpkbilinear (z, p, k, fs) protected
Bilinear transformation to convert a filter from analog to digital.
Definition at line 33 of file mpsig.py.
References _prod(), and _relative_degree().
Referenced by butter_lp().
_zpklp2lp()
scipy.signal.tests.mpsig._zpklp2lp (z, p, k, wo = 1) protected
Transform a lowpass filter to a different cutoff frequency.
Definition at line 55 of file mpsig.py.
References _relative_degree().
Referenced by butter_lp().
butter_lp()
scipy.signal.tests.mpsig.butter_lp (n, Wn)
Lowpass Butterworth digital filter design.
This computes the same result as scipy.signal.butter(n, Wn, output='zpk'),
but it uses mpmath, and the results are returned in lists instead of NumPy
arrays.
Definition at line 83 of file mpsig.py.
References _butter_analog_poles(), _zpkbilinear(), and _zpklp2lp().
zpkfreqz()
scipy.signal.tests.mpsig.zpkfreqz (z, p, k, worN = None)
Frequency response of a filter in zpk format, using mpmath.
This is the same calculation as scipy.signal.freqz, but the input is in
zpk format, the calculation is performed using mpath, and the results are
returned in lists instead of NumPy arrays.
Definition at line 101 of file mpsig.py.
References _prod().
Variable Documentation
mpmath
scipy.signal.tests.mpsig.mpmath = None
Definition at line 8 of file mpsig.py.