Code Cloning Analysis: sklearn.model_selection.tests.test_successive_halving.SometimesFailClassifier Class Reference
sklearn.model_selection.tests.test_successive_halving.SometimesFailClassifier Class Reference
Public Member Functions
__init__ (self, strategy="stratified", random_state=None, constant=None, n_estimators=10, fail_fit=False, fail_predict=False, a=0)
fit (self, X, y)
predict (self, X)
Public Member Functions inherited from sklearn.dummy.DummyClassifier
__init__ (self, *, strategy="prior", random_state=None, constant=None)
predict_proba (self, X)
predict_log_proba (self, X)
__sklearn_tags__ (self)
score (self, X, y, sample_weight=None)
Public Member Functions inherited from sklearn.base.MultiOutputMixin
__sklearn_tags__ (self)
Public Member Functions inherited from sklearn.base.ClassifierMixin
__sklearn_tags__ (self)
Public Member Functions inherited from sklearn.base.BaseEstimator
get_params (self, deep=True)
set_params (self, **params)
__sklearn_clone__ (self)
__repr__ (self, N_CHAR_MAX=700)
__getstate__ (self)
__setstate__ (self, state)
__sklearn_tags__ (self)
Public Member Functions inherited from sklearn.utils._metadata_requests._MetadataRequester
set_fit_request (self, **kwargs)
set_partial_fit_request (self, **kwargs)
set_predict_request (self, **kwargs)
set_predict_proba_request (self, **kwargs)
set_predict_log_proba_request (self, **kwargs)
set_decision_function_request (self, **kwargs)
set_score_request (self, **kwargs)
set_split_request (self, **kwargs)
set_transform_request (self, **kwargs)
set_inverse_transform_request (self, **kwargs)
__init_subclass__ (cls, **kwargs)
get_metadata_routing (self)
Public Attributes
fail_fit = fail_fit
fail_predict = fail_predict
n_estimators = n_estimators
a = a
Public Attributes inherited from sklearn.dummy.DummyClassifier
strategy = strategy
random_state = random_state
constant = constant
sparse_output_ = sp.issparse(y)
int n_outputs_ = y.shape[1]
classes_ = self.n_outputs_:
n_classes_
class_prior_
Additional Inherited Members
Protected Member Functions inherited from sklearn.base.BaseEstimator
_get_param_names (cls)
_get_params_html (self, deep=True)
_validate_params (self)
Protected Member Functions inherited from sklearn.utils._repr_html.base.ReprHTMLMixin
_repr_html_ (self)
_repr_html_inner (self)
_repr_mimebundle_ (self, **kwargs)
Protected Member Functions inherited from sklearn.utils._repr_html.base._HTMLDocumentationLinkMixin
_doc_link_template (self)
_doc_link_template (self, value)
_get_doc_link (self)
Protected Member Functions inherited from sklearn.utils._metadata_requests._MetadataRequester
_build_request_for_signature (cls, router, method)
_get_default_requests (cls)
_get_metadata_request (self)
Protected Attributes inherited from sklearn.dummy.DummyClassifier
str _strategy = self.strategy
Protected Attributes inherited from sklearn.base.BaseEstimator
_parameter_constraints
Static Protected Attributes inherited from sklearn.base.ClassifierMixin
str _estimator_type = "classifier"
Static Protected Attributes inherited from sklearn.base.BaseEstimator
_html_repr = estimator_html_repr
Static Protected Attributes inherited from sklearn.utils._repr_html.base._HTMLDocumentationLinkMixin
str _doc_link_module = "sklearn"
_doc_link_url_param_generator = None
Detailed Description
Definition at line 59 of file test_successive_halving.py.
Constructor & Destructor Documentation
__init__()
sklearn.model_selection.tests.test_successive_halving.SometimesFailClassifier.__init__ (self, strategy = "stratified", random_state = None, constant = None, n_estimators = 10, fail_fit = False, fail_predict = False, a = 0)
Definition at line 60 of file test_successive_halving.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params().
Member Function Documentation
fit()
sklearn.model_selection.tests.test_successive_halving.SometimesFailClassifier.fit (self, X, y)
Fit the baseline classifier.
Parameters
----------
X : array-like of shape (n_samples, n_features)
    Training data.
y : array-like of shape (n_samples,) or (n_samples, n_outputs)
    Target values.
sample_weight : array-like of shape (n_samples,), default=None
    Sample weights.
Returns
-------
self : object
    Returns the instance itself.
Reimplemented from sklearn.dummy.DummyClassifier.
Definition at line 79 of file test_successive_halving.py.
References fail_fit, and fit().
Referenced by fit(), sklearn.cluster._kmeans._BaseKMeans.fit_predict(), sklearn.neighbors._lof.LocalOutlierFactor.fit_predict(), sklearn.cluster._kmeans._BaseKMeans.fit_transform(), sklearn.neighbors._graph.KNeighborsTransformer.fit_transform(), sklearn.neighbors._graph.RadiusNeighborsTransformer.fit_transform(), sklearn.preprocessing._label.LabelBinarizer.fit_transform(), sklearn.preprocessing._label.MultiLabelBinarizer.fit_transform(), sklearn.tests.metadata_routing_common.ConsumingTransformer.fit_transform(), and sklearn.utils.tests.test_estimator_checks.SparseTransformer.fit_transform().
predict()
sklearn.model_selection.tests.test_successive_halving.SometimesFailClassifier.predict (self, X)
Perform classification on test vectors X.
Parameters
----------
X : array-like of shape (n_samples, n_features)
    Test data.
Returns
-------
y : array-like of shape (n_samples,) or (n_samples, n_outputs)
    Predicted target values for X.
Reimplemented from sklearn.dummy.DummyClassifier.
Definition at line 84 of file test_successive_halving.py.
References fail_predict, and predict().
Referenced by predict(), and sklearn.multioutput.MultiOutputClassifier.score().
Member Data Documentation
a
sklearn.model_selection.tests.test_successive_halving.SometimesFailClassifier.a = a
Definition at line 73 of file test_successive_halving.py.
Referenced by sklearn.model_selection.tests.test_validation.MockClassifier.get_params(), sklearn.tests.test_pipeline.NoTrans.get_params(), sklearn.model_selection.tests.test_validation.MockClassifier.score(), sklearn.tests.test_pipeline.NoTrans.set_params(), and sklearn.utils.tests.test_estimator_checks.ModifiesAnotherValue.set_params().
fail_fit
sklearn.model_selection.tests.test_successive_halving.SometimesFailClassifier.fail_fit = fail_fit
Definition at line 70 of file test_successive_halving.py.
Referenced by fit().
fail_predict
sklearn.model_selection.tests.test_successive_halving.SometimesFailClassifier.fail_predict = fail_predict
Definition at line 71 of file test_successive_halving.py.
Referenced by predict().
n_estimators
sklearn.model_selection.tests.test_successive_halving.SometimesFailClassifier.n_estimators = n_estimators
Definition at line 72 of file test_successive_halving.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/sklearn/model_selection/tests/test_successive_halving.py