Code Cloning Analysis: pandas.core.groupby.indexing.GroupByNthSelector Class Reference
pandas.core.groupby.indexing.GroupByNthSelector Class Reference
Public Member Functions
None __init__ (self, groupby.GroupBy groupby_object)
DataFrame|Series __call__ (self, PositionalIndexer|tuple n, Literal["any", "all", None] dropna=None)
DataFrame|Series __getitem__ (self, PositionalIndexer|tuple n)
Public Attributes
groupby_object = groupby_object
Detailed Description
Dynamically substituted for GroupBy.nth to enable both call and index
Definition at line 288 of file indexing.py.
Constructor & Destructor Documentation
__init__()
None pandas.core.groupby.indexing.GroupByNthSelector.__init__ (self, groupby.GroupBy groupby_object)
Definition at line 293 of file indexing.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__call__()
DataFrame | Series pandas.core.groupby.indexing.GroupByNthSelector.__call__ (self, PositionalIndexer | tuple n, Literal["any", "all", None] dropna = None)
Definition at line 296 of file indexing.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), and scipy.interpolate._fitpack2.SphereBivariateSpline.ev().
__getitem__()
DataFrame | Series pandas.core.groupby.indexing.GroupByNthSelector.__getitem__ (self, PositionalIndexer | tuple n)
Definition at line 303 of file indexing.py.
Member Data Documentation
groupby_object
pandas.core.groupby.indexing.GroupByNthSelector.groupby_object = groupby_object
Definition at line 294 of file indexing.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/core/groupby/indexing.py