Code Cloning Analysis: pandas.core.reshape.reshape._Unstacker Class Reference
pandas.core.reshape.reshape._Unstacker Class Reference
Public Member Functions
None __init__ (self, MultiIndex index, Level level, constructor, bool sort=True)
list[np.ndarray] sorted_labels (self)
bool mask_all (self)
tuple[npt.NDArray[np.intp], npt.NDArray[np.bool_]] arange_result (self)
DataFrame get_result (self, values, value_columns, fill_value)
get_new_values (self, values, fill_value=None)
get_new_columns (self, Index|None value_columns)
MultiIndex new_index (self)
Public Attributes
constructor = constructor
sort = sort
index = index.remove_unused_levels()
level = self.index._get_level_number(level)
int lift = 1 if -1 in self.index.codes[self.level] else 0
new_index_levels = list(self.index.levels)
new_index_names = list(self.index.names)
removed_name = self.new_index_names.pop(self.level)
removed_level = self.new_index_levels.pop(self.level)
removed_level_full = index.levels[self.level]
full_shape = ngroups, stride
group_index = comp_index
mask = mask
compressor = comp_index.searchsorted(np.arange(ngroups))
Protected Member Functions
tuple[ npt.NDArray[np.intp], list[np.ndarray], # each has _some_ signed integer dtype] _indexer_and_to_sort (self)
np.ndarray _make_sorted_values (self, np.ndarray values)
_make_selectors (self)
np.ndarray _repeater (self)
Detailed Description
Helper class to unstack data / pivot with multi-level index
Parameters
----------
index : MultiIndex
level : int or str, default last level
    Level to "unstack". Accepts a name for the level.
fill_value : scalar, optional
    Default value to fill in missing values if subgroups do not have the
    same set of labels. By default, missing values will be replaced with
    the default fill value for that data type, NaN for float, NaT for
    datetimelike, etc. For integer types, by default data will converted to
    float and missing values will be set to NaN.
constructor : object
    Pandas ``DataFrame`` or subclass used to create unstacked
    response.  If None, DataFrame will be used.
Examples
--------
>>> index = pd.MultiIndex.from_tuples([('one', 'a'), ('one', 'b'),
...                                    ('two', 'a'), ('two', 'b')])
>>> s = pd.Series(np.arange(1, 5, dtype=np.int64), index=index)
>>> s
one  a    1
     b    2
two  a    3
     b    4
dtype: int64
>>> s.unstack(level=-1)
     a  b
one  1  2
two  3  4
>>> s.unstack(level=0)
   one  two
a    1    3
b    2    4
Returns
-------
unstacked : DataFrame
Definition at line 64 of file reshape.py.
Constructor & Destructor Documentation
__init__()
None pandas.core.reshape.reshape._Unstacker.__init__ (self, MultiIndex index, Level level, constructor, bool sort = True)
Definition at line 110 of file reshape.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_indexer_and_to_sort()
tuple[ npt.NDArray[np.intp], list[np.ndarray], # each has _some_ signed integer dtype ] pandas.core.reshape.reshape._Unstacker._indexer_and_to_sort (self) protected
Definition at line 157 of file reshape.py.
_make_selectors()
pandas.core.reshape.reshape._Unstacker._make_selectors (self) protected
Definition at line 191 of file reshape.py.
_make_sorted_values()
np.ndarray pandas.core.reshape.reshape._Unstacker._make_sorted_values (self, np.ndarray values) protected
Definition at line 183 of file reshape.py.
_repeater()
np.ndarray pandas.core.reshape.reshape._Unstacker._repeater (self) protected
Definition at line 364 of file reshape.py.
arange_result()
tuple[npt.NDArray[np.intp], npt.NDArray[np.bool_]] pandas.core.reshape.reshape._Unstacker.arange_result (self)
Definition at line 224 of file reshape.py.
get_new_columns()
pandas.core.reshape.reshape._Unstacker.get_new_columns (self, Index | None value_columns)
Definition at line 325 of file reshape.py.
get_new_values()
pandas.core.reshape.reshape._Unstacker.get_new_values (self, values, fill_value = None)
Definition at line 246 of file reshape.py.
get_result()
DataFrame pandas.core.reshape.reshape._Unstacker.get_result (self, values, value_columns, fill_value)
Definition at line 231 of file reshape.py.
Referenced by scipy.optimize._zeros_py.TOMS748Solver.solve().
mask_all()
bool pandas.core.reshape.reshape._Unstacker.mask_all (self)
Definition at line 220 of file reshape.py.
new_index()
MultiIndex pandas.core.reshape.reshape._Unstacker.new_index (self)
Definition at line 379 of file reshape.py.
sorted_labels()
list[np.ndarray] pandas.core.reshape.reshape._Unstacker.sorted_labels (self)
Definition at line 177 of file reshape.py.
Member Data Documentation
compressor
pandas.core.reshape.reshape._Unstacker.compressor = comp_index.searchsorted(np.arange(ngroups))
Definition at line 215 of file reshape.py.
constructor
pandas.core.reshape.reshape._Unstacker.constructor = constructor
Definition at line 113 of file reshape.py.
full_shape
pandas.core.reshape.reshape._Unstacker.full_shape = ngroups, stride
Definition at line 203 of file reshape.py.
group_index
pandas.core.reshape.reshape._Unstacker.group_index = comp_index
Definition at line 212 of file reshape.py.
index
pandas.core.reshape.reshape._Unstacker.index = index.remove_unused_levels()
Definition at line 116 of file reshape.py.
Referenced by pandas.io.json._json.JSONTableWriter.__init__(), scipy.optimize._shgo_lib._vertex.VertexBase.__init__(), scipy.optimize._shgo_lib._vertex.VertexCacheField.__init__(), scipy.optimize._shgo_lib._vertex.VertexCacheIndex.__init__(), pandas.io.sql.SQLTable._execute_insert_multi(), pandas.io.formats.style_render.StylerRenderer._generate_col_header_row(), pandas.io.formats.xml._BaseXMLFormatter._handle_indexes(), pandas.io.formats.csvs.CSVFormatter._number_format(), pandas.io.formats.xml._BaseXMLFormatter._process_dataframe(), pandas.io.sql.SQLTable._query_iterator(), pandas.io.formats.style_render.StylerRenderer._render(), pandas.io.formats.style_render.StylerRenderer._translate(), pandas.io.formats.style_render.StylerRenderer._translate_latex(), pandas.io.formats.format.DataFrameFormatter._truncate_vertically(), pandas.io.formats.style.Styler._update_ctx(), pandas.core.apply.FrameApply.apply(), pandas.io.formats.style.Styler.apply(), pandas.core.apply.FrameApply.apply_raw(), pandas.core.internals.array_manager.SingleArrayManager.array_values(), pandas.io.sas.sas7bdat.SAS7BDATReader.column_types(), pandas.io.formats.style_render.StylerRenderer.format(), pandas.io.formats.style_render.StylerRenderer.format_index(), pip._vendor.pyparsing.diagram.ConverterState.generate_index(), pyparsing.diagram.ConverterState.generate_index(), pandas.tseries.frequencies._FrequencyInferer.get_freq(), pandas.io.formats.format.DataFrameFormatter.get_strcols(), pandas.io.formats.style_render.StylerRenderer.relabel_index(), pandas.io.formats.csvs.CSVFormatter.save(), pandas.io.formats.style.Styler.set_sticky(), scipy.optimize._shgo_lib._vertex.VertexCacheBase.size(), pandas.tests.indexes.interval.test_interval.TestIntervalIndex.test_is_unique_interval(), and pandas.io.formats.style.Styler.to_latex().
level
pandas.core.reshape.reshape._Unstacker.level = self.index._get_level_number(level)
Definition at line 118 of file reshape.py.
lift
int pandas.core.reshape.reshape._Unstacker.lift = 1 if -1 in self.index.codes[self.level] else 0
Definition at line 121 of file reshape.py.
mask
pandas.core.reshape.reshape._Unstacker.mask = mask
Definition at line 213 of file reshape.py.
Referenced by pandas.core.series.Series.combine_first().
new_index_levels
pandas.core.reshape.reshape._Unstacker.new_index_levels = list(self.index.levels)
Definition at line 124 of file reshape.py.
new_index_names
pandas.core.reshape.reshape._Unstacker.new_index_names = list(self.index.names)
Definition at line 125 of file reshape.py.
removed_level
pandas.core.reshape.reshape._Unstacker.removed_level = self.new_index_levels.pop(self.level)
Definition at line 128 of file reshape.py.
removed_level_full
pandas.core.reshape.reshape._Unstacker.removed_level_full = index.levels[self.level]
Definition at line 129 of file reshape.py.
removed_name
pandas.core.reshape.reshape._Unstacker.removed_name = self.new_index_names.pop(self.level)
Definition at line 127 of file reshape.py.
sort
pandas.core.reshape.reshape._Unstacker.sort = sort
Definition at line 114 of file reshape.py.
Referenced by pip._vendor.rich._inspect.Inspect._render(), and sklearn.feature_extraction._dict_vectorizer.DictVectorizer.fit().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/core/reshape/reshape.py