Code Cloning Analysis: numpy.core.tests.test_regression.TestRegression Class Reference
numpy.core.tests.test_regression.TestRegression Class Reference
Public Member Functions
test_invalid_round (self)
test_mem_empty (self)
test_pickle_transposed (self)
test_dtype_names (self)
test_reduce (self)
test_zeros_order (self)
test_asarray_with_order (self)
test_ravel_with_order (self)
test_sort_bigendian (self)
test_negative_nd_indexing (self)
test_char_dump (self)
test_noncontiguous_fill (self)
test_bool (self)
test_indexing1 (self)
test_indexing2 (self)
test_round (self)
test_scalar_compare (self)
test_unicode_swapping (self)
test_object_array_fill (self)
test_mem_dtype_align (self)
test_endian_bool_indexing (self)
test_endian_where (self)
test_endian_recarray (self)
test_mem_dot (self)
test_arange_endian (self)
test_arange_inf_step (self)
test_arange_underflow_stop_and_step (self)
test_argmax (self)
test_mem_divmod (self)
test_hstack_invalid_dims (self)
test_squeeze_type (self)
test_add_identity (self)
test_numpy_float_python_long_addition (self)
test_binary_repr_0 (self)
test_rec_iterate (self)
test_unicode_string_comparison (self)
test_tobytes_FORTRANORDER_discontiguous (self)
test_flat_assignment (self)
test_broadcast_flat_assignment (self)
test_nonarray_assignment (self, index)
test_unpickle_dtype_with_object (self)
test_mem_array_creation_invalid_specification (self)
test_recarray_single_element (self)
test_zero_sized_array_indexing (self)
test_chararray_rstrip (self)
test_object_array_shape (self)
test_mem_around (self)
test_character_array_strip (self)
test_lexsort (self)
test_lexsort_invalid_sequence (self)
test_lexsort_zerolen_custom_strides (self)
test_lexsort_zerolen_custom_strides_2d (self)
test_lexsort_invalid_axis (self)
test_lexsort_zerolen_element (self)
test_pickle_py2_bytes_encoding (self)
test_pickle_dtype (self)
test_swap_real (self)
test_object_array_from_list (self)
test_multiple_assign (self)
test_empty_array_type (self)
test_void_copyswap (self)
test_method_args (self)
test_mem_lexsort_strings (self)
test_fancy_index (self)
test_recarray_copy (self)
test_rec_fromarray (self)
test_object_array_assign (self)
test_ndmin_float64 (self)
test_ndmin_order (self)
test_mem_axis_minimization (self)
test_mem_float_imag (self)
test_dtype_tuple (self)
test_dtype_posttuple (self)
test_numeric_carray_compare (self)
test_string_array_size (self)
test_dtype_repr (self)
test_reshape_order (self)
test_reshape_zero_strides (self)
test_reshape_zero_size (self)
test_reshape_trailing_ones_strides (self)
test_repeat_discont (self)
test_array_index (self)
test_object_argmax (self)
test_recarray_fields (self)
test_random_shuffle (self)
test_refcount_vdot (self)
test_startswith (self)
test_noncommutative_reduce_accumulate (self)
test_convolve_empty (self)
test_multidim_byteswap (self)
test_string_NULL (self)
test_junk_in_string_fields_of_recarray (self)
test_take_output (self)
test_take_object_fail (self)
test_array_str_64bit (self)
test_frompyfunc_endian (self)
test_mem_string_arr (self)
test_arr_transpose (self)
test_string_mergesort (self)
test_argmax_byteorder (self)
test_rand_seed (self)
test_mem_deallocation_leak (self)
test_mem_on_invalid_dtype (self)
test_dot_negative_stride (self)
test_object_casting (self)
test_unicode_scalar (self)
test_arange_non_native_dtype (self)
test_bool_flat_indexing_invalid_nr_elements (self)
test_mem_scalar_indexing (self)
test_binary_repr_0_width (self)
test_fromstring (self)
test_searchsorted_variable_length (self)
test_string_argsort_with_zeros (self)
test_string_sort_with_zeros (self)
test_copy_detection_zero_dim (self)
test_flat_byteorder (self)
test_sign_bit (self)
test_flat_index_byteswap (self)
test_copy_detection_corner_case (self)
test_copy_detection_corner_case2 (self)
test_object_array_refcounting (self)
test_mem_custom_float_to_array (self)
test_object_array_refcount_self_assign (self)
test_mem_fromiter_invalid_dtype_string (self)
test_reduce_big_object_array (self)
test_mem_0d_array_index (self)
test_nonnative_endian_fill (self)
test_dot_alignment_sse2 (self)
test_astype_copy (self)
test_compress_small_type (self)
test_attributes (self)
test_recarray_tolist (self)
test_nonscalar_item_method (self)
test_char_array_creation (self)
test_unaligned_unicode_access (self)
test_sign_for_complex_nan (self)
test_for_equal_names (self)
test_for_object_scalar_creation (self)
test_array_resize_method_system_error (self)
test_for_zero_length_in_choose (self)
test_array_ndmin_overflow (self)
test_void_scalar_with_titles (self)
test_void_scalar_constructor (self)
test_blasdot_uninitialized_memory (self)
test_zeros (self)
test_huge_arange (self)
test_fromiter_bytes (self)
test_array_from_sequence_scalar_array (self)
test_array_from_sequence_scalar_array2 (self)
test_array_too_big (self)
test_dtype_keyerrors_ (self)
test_lexsort_buffer_length (self)
test_object_array_to_fixed_string (self)
test_unicode_to_string_cast (self)
test_unicode_to_string_cast_error (self)
test_mixed_string_byte_array_creation (self)
test_misaligned_objects_segfault (self)
test_misaligned_scalars_segfault (self)
test_misaligned_dot_product_objects (self)
test_byteswap_complex_scalar (self)
test_structured_arrays_with_objects1 (self)
test_structured_arrays_with_objects2 (self)
test_duplicate_title_and_name (self)
test_signed_integer_division_overflow (self)
test_buffer_hashlib (self)
test_0d_string_scalar (self)
test_log1p_compiler_shenanigans (self)
test_fromiter_comparison (self)
test_fromstring_crash (self)
test_ticket_1539 (self)
test_ticket_1538 (self)
test_ticket_1434 (self)
test_complex_nan_maximum (self)
test_subclass_int_tuple_assignment (self)
test_ufunc_no_unnecessary_views (self)
test_take_refcount (self)
test_fromfile_tofile_seeks (self)
test_complex_scalar_warning (self)
test_complex_scalar_complex_cast (self)
test_complex_boolean_cast (self)
test_uint_int_conversion (self)
test_duplicate_field_names_assign (self)
test_eq_string_and_object_array (self)
test_nonzero_byteswap (self)
test_find_common_type_boolean (self)
test_empty_mul (self)
test_array_side_effect (self)
test_any_float (self)
test_large_float_sum (self)
test_ufunc_casting_out (self)
test_array_scalar_contiguous (self)
test_squeeze_contiguous (self)
test_squeeze_axis_handling (self)
test_reduce_contiguous (self)
test_object_array_self_reference (self)
test_object_array_circular_reference (self)
test_object_array_nested (self)
test_object_array_self_copy (self)
test_zerosize_accumulate (self)
test_objectarray_setfield (self)
test_setting_rank0_string (self)
test_string_astype (self)
test_ticket_1756 (self)
test_fields_strides (self)
test_alignment_update (self)
test_ticket_1770 (self)
test_ticket_1608 (self)
test_pickle_string_overwrite (self)
test_pickle_bytes_overwrite (self)
test_pickle_py2_array_latin1_hack (self)
test_pickle_py2_scalar_latin1_hack (self)
test_structured_type_to_object (self)
test_assign_obj_listoflists (self)
test_memoryleak (self)
test_ufunc_reduce_memoryleak (self)
test_search_sorted_invalid_arguments (self)
test_string_truncation (self)
test_string_truncation_ucs2 (self)
test_unique_stable (self)
test_unicode_alloc_dealloc_match (self)
test_refcount_error_in_clip (self)
test_searchsorted_wrong_dtype (self)
test_complex64_alignment (self)
test_structured_count_nonzero (self)
test_copymodule_preserves_f_contiguity (self)
test_fortran_order_buffer (self)
test_assign_from_sequence_error (self)
test_format_on_flex_array_element (self)
test_deepcopy_on_0d_array (self)
test_deepcopy_F_order_object_array (self)
test_deepcopy_empty_object_array (self)
test_bool_subscript_crash (self)
test_richcompare_crash (self)
test_richcompare_scalar_and_subclass (self)
test_pickle_empty_string (self)
test_frompyfunc_many_args (self)
test_repeat_broadcasting (self)
test_frompyfunc_nout_0 (self)
test_leak_in_structured_dtype_comparison (self)
test_empty_percentile (self)
test_void_compare_segfault (self)
test_reshape_size_overflow (self)
test_invalid_structured_dtypes (self)
test_correct_hash_dict (self)
test_scalar_copy (self)
test_void_item_memview (self)
test_void_getitem (self)
test_structarray_title (self)
test_dtype_scalar_squeeze (self)
test_field_access_by_title (self)
test_pickle_module (self, protocol, val)
test_object_casting_errors (self)
test_eff1d_casting (self)
test_pickle_datetime64_array (self)
test_bad_array_interface (self)
test_2d__array__shape (self)
test_to_ctypes (self)
test_complex_conversion_error (self)
test__array_interface__descr (self)
test_dot_big_stride (self)
test_frompyfunc_name (self)
test_ufunc_order (self, operation, order)
test_nonbool_logical (self)
Public Attributes
bool deleted = True
info = getattr(obj, 'info', '')
Detailed Description
Definition at line 21 of file test_regression.py.
Member Function Documentation
test_0d_string_scalar()
numpy.core.tests.test_regression.TestRegression.test_0d_string_scalar (self)
Definition at line 1504 of file test_regression.py.
test_2d__array__shape()
numpy.core.tests.test_regression.TestRegression.test_2d__array__shape (self)
Definition at line 2461 of file test_regression.py.
test__array_interface__descr()
numpy.core.tests.test_regression.TestRegression.test__array_interface__descr (self)
Definition at line 2495 of file test_regression.py.
test_add_identity()
numpy.core.tests.test_regression.TestRegression.test_add_identity (self)
Definition at line 272 of file test_regression.py.
test_alignment_update()
numpy.core.tests.test_regression.TestRegression.test_alignment_update (self)
Definition at line 1890 of file test_regression.py.
test_any_float()
numpy.core.tests.test_regression.TestRegression.test_any_float (self)
Definition at line 1693 of file test_regression.py.
test_arange_endian()
numpy.core.tests.test_regression.TestRegression.test_arange_endian (self)
Definition at line 204 of file test_regression.py.
test_arange_inf_step()
numpy.core.tests.test_regression.TestRegression.test_arange_inf_step (self)
Definition at line 212 of file test_regression.py.
test_arange_non_native_dtype()
numpy.core.tests.test_regression.TestRegression.test_arange_non_native_dtype (self)
Definition at line 830 of file test_regression.py.
test_arange_underflow_stop_and_step()
numpy.core.tests.test_regression.TestRegression.test_arange_underflow_stop_and_step (self)
Definition at line 229 of file test_regression.py.
test_argmax()
numpy.core.tests.test_regression.TestRegression.test_argmax (self)
Definition at line 248 of file test_regression.py.
test_argmax_byteorder()
numpy.core.tests.test_regression.TestRegression.test_argmax_byteorder (self)
Definition at line 783 of file test_regression.py.
test_arr_transpose()
numpy.core.tests.test_regression.TestRegression.test_arr_transpose (self)
Definition at line 773 of file test_regression.py.
test_array_from_sequence_scalar_array()
numpy.core.tests.test_regression.TestRegression.test_array_from_sequence_scalar_array (self)
Definition at line 1335 of file test_regression.py.
test_array_from_sequence_scalar_array2()
numpy.core.tests.test_regression.TestRegression.test_array_from_sequence_scalar_array2 (self)
Definition at line 1350 of file test_regression.py.
test_array_index()
numpy.core.tests.test_regression.TestRegression.test_array_index (self)
Definition at line 663 of file test_regression.py.
test_array_ndmin_overflow()
numpy.core.tests.test_regression.TestRegression.test_array_ndmin_overflow (self)
Definition at line 1250 of file test_regression.py.
test_array_resize_method_system_error()
numpy.core.tests.test_regression.TestRegression.test_array_resize_method_system_error (self)
Definition at line 1240 of file test_regression.py.
test_array_scalar_contiguous()
numpy.core.tests.test_regression.TestRegression.test_array_scalar_contiguous (self)
Definition at line 1710 of file test_regression.py.
test_array_side_effect()
numpy.core.tests.test_regression.TestRegression.test_array_side_effect (self)
Definition at line 1683 of file test_regression.py.
test_array_str_64bit()
numpy.core.tests.test_regression.TestRegression.test_array_str_64bit (self)
Definition at line 752 of file test_regression.py.
test_array_too_big()
numpy.core.tests.test_regression.TestRegression.test_array_too_big (self)
Definition at line 1356 of file test_regression.py.
test_asarray_with_order()
numpy.core.tests.test_regression.TestRegression.test_asarray_with_order (self)
Definition at line 56 of file test_regression.py.
test_assign_from_sequence_error()
numpy.core.tests.test_regression.TestRegression.test_assign_from_sequence_error (self)
Definition at line 2142 of file test_regression.py.
test_assign_obj_listoflists()
numpy.core.tests.test_regression.TestRegression.test_assign_obj_listoflists (self)
Definition at line 2012 of file test_regression.py.
test_astype_copy()
numpy.core.tests.test_regression.TestRegression.test_astype_copy (self)
Definition at line 1082 of file test_regression.py.
test_attributes()
numpy.core.tests.test_regression.TestRegression.test_attributes (self)
Definition at line 1108 of file test_regression.py.
test_bad_array_interface()
numpy.core.tests.test_regression.TestRegression.test_bad_array_interface (self)
Definition at line 2454 of file test_regression.py.
test_binary_repr_0()
numpy.core.tests.test_regression.TestRegression.test_binary_repr_0 (self)
Definition at line 281 of file test_regression.py.
test_binary_repr_0_width()
numpy.core.tests.test_regression.TestRegression.test_binary_repr_0_width (self)
Definition at line 858 of file test_regression.py.
test_blasdot_uninitialized_memory()
numpy.core.tests.test_regression.TestRegression.test_blasdot_uninitialized_memory (self)
Definition at line 1289 of file test_regression.py.
test_bool()
numpy.core.tests.test_regression.TestRegression.test_bool (self)
Definition at line 100 of file test_regression.py.
test_bool_flat_indexing_invalid_nr_elements()
numpy.core.tests.test_regression.TestRegression.test_bool_flat_indexing_invalid_nr_elements (self)
Definition at line 838 of file test_regression.py.
test_bool_subscript_crash()
numpy.core.tests.test_regression.TestRegression.test_bool_subscript_crash (self)
Definition at line 2190 of file test_regression.py.
test_broadcast_flat_assignment()
numpy.core.tests.test_regression.TestRegression.test_broadcast_flat_assignment (self)
Definition at line 313 of file test_regression.py.
test_buffer_hashlib()
numpy.core.tests.test_regression.TestRegression.test_buffer_hashlib (self)
Definition at line 1498 of file test_regression.py.
test_byteswap_complex_scalar()
numpy.core.tests.test_regression.TestRegression.test_byteswap_complex_scalar (self)
Definition at line 1443 of file test_regression.py.
test_char_array_creation()
numpy.core.tests.test_regression.TestRegression.test_char_array_creation (self)
Definition at line 1195 of file test_regression.py.
test_char_dump()
numpy.core.tests.test_regression.TestRegression.test_char_dump (self)
Definition at line 81 of file test_regression.py.
test_character_array_strip()
numpy.core.tests.test_regression.TestRegression.test_character_array_strip (self)
Definition at line 400 of file test_regression.py.
test_chararray_rstrip()
numpy.core.tests.test_regression.TestRegression.test_chararray_rstrip (self)
Definition at line 377 of file test_regression.py.
test_complex64_alignment()
numpy.core.tests.test_regression.TestRegression.test_complex64_alignment (self)
Definition at line 2106 of file test_regression.py.
test_complex_boolean_cast()
numpy.core.tests.test_regression.TestRegression.test_complex_boolean_cast (self)
Definition at line 1640 of file test_regression.py.
test_complex_conversion_error()
numpy.core.tests.test_regression.TestRegression.test_complex_conversion_error (self)
Definition at line 2490 of file test_regression.py.
test_complex_nan_maximum()
numpy.core.tests.test_regression.TestRegression.test_complex_nan_maximum (self)
Definition at line 1563 of file test_regression.py.
test_complex_scalar_complex_cast()
numpy.core.tests.test_regression.TestRegression.test_complex_scalar_complex_cast (self)
Definition at line 1635 of file test_regression.py.
test_complex_scalar_warning()
numpy.core.tests.test_regression.TestRegression.test_complex_scalar_warning (self)
Definition at line 1627 of file test_regression.py.
test_compress_small_type()
numpy.core.tests.test_regression.TestRegression.test_compress_small_type (self)
Definition at line 1094 of file test_regression.py.
test_convolve_empty()
numpy.core.tests.test_regression.TestRegression.test_convolve_empty (self)
Definition at line 710 of file test_regression.py.
test_copy_detection_corner_case()
numpy.core.tests.test_regression.TestRegression.test_copy_detection_corner_case (self)
Definition at line 901 of file test_regression.py.
test_copy_detection_corner_case2()
numpy.core.tests.test_regression.TestRegression.test_copy_detection_corner_case2 (self)
Definition at line 910 of file test_regression.py.
test_copy_detection_zero_dim()
numpy.core.tests.test_regression.TestRegression.test_copy_detection_zero_dim (self)
Definition at line 882 of file test_regression.py.
test_copymodule_preserves_f_contiguity()
numpy.core.tests.test_regression.TestRegression.test_copymodule_preserves_f_contiguity (self)
Definition at line 2125 of file test_regression.py.
test_correct_hash_dict()
numpy.core.tests.test_regression.TestRegression.test_correct_hash_dict (self)
Definition at line 2333 of file test_regression.py.
test_deepcopy_empty_object_array()
numpy.core.tests.test_regression.TestRegression.test_deepcopy_empty_object_array (self)
Definition at line 2183 of file test_regression.py.
test_deepcopy_F_order_object_array()
numpy.core.tests.test_regression.TestRegression.test_deepcopy_F_order_object_array (self)
Definition at line 2167 of file test_regression.py.
test_deepcopy_on_0d_array()
numpy.core.tests.test_regression.TestRegression.test_deepcopy_on_0d_array (self)
Definition at line 2156 of file test_regression.py.
test_dot_alignment_sse2()
numpy.core.tests.test_regression.TestRegression.test_dot_alignment_sse2 (self)
Definition at line 1072 of file test_regression.py.
test_dot_big_stride()
numpy.core.tests.test_regression.TestRegression.test_dot_big_stride (self)
Definition at line 2505 of file test_regression.py.
test_dot_negative_stride()
numpy.core.tests.test_regression.TestRegression.test_dot_negative_stride (self)
Definition at line 803 of file test_regression.py.
test_dtype_keyerrors_()
numpy.core.tests.test_regression.TestRegression.test_dtype_keyerrors_ (self)
Definition at line 1361 of file test_regression.py.
test_dtype_names()
numpy.core.tests.test_regression.TestRegression.test_dtype_names (self)
Definition at line 41 of file test_regression.py.
test_dtype_posttuple()
numpy.core.tests.test_regression.TestRegression.test_dtype_posttuple (self)
Definition at line 607 of file test_regression.py.
test_dtype_repr()
numpy.core.tests.test_regression.TestRegression.test_dtype_repr (self)
Definition at line 620 of file test_regression.py.
test_dtype_scalar_squeeze()
numpy.core.tests.test_regression.TestRegression.test_dtype_scalar_squeeze (self)
Definition at line 2383 of file test_regression.py.
test_dtype_tuple()
numpy.core.tests.test_regression.TestRegression.test_dtype_tuple (self)
Definition at line 603 of file test_regression.py.
test_duplicate_field_names_assign()
numpy.core.tests.test_regression.TestRegression.test_duplicate_field_names_assign (self)
Definition at line 1652 of file test_regression.py.
test_duplicate_title_and_name()
numpy.core.tests.test_regression.TestRegression.test_duplicate_title_and_name (self)
Definition at line 1483 of file test_regression.py.
test_eff1d_casting()
numpy.core.tests.test_regression.TestRegression.test_eff1d_casting (self)
Definition at line 2435 of file test_regression.py.
test_empty_array_type()
numpy.core.tests.test_regression.TestRegression.test_empty_array_type (self)
Definition at line 507 of file test_regression.py.
test_empty_mul()
numpy.core.tests.test_regression.TestRegression.test_empty_mul (self)
Definition at line 1678 of file test_regression.py.
test_empty_percentile()
numpy.core.tests.test_regression.TestRegression.test_empty_percentile (self)
Definition at line 2282 of file test_regression.py.
test_endian_bool_indexing()
numpy.core.tests.test_regression.TestRegression.test_endian_bool_indexing (self)
Definition at line 151 of file test_regression.py.
test_endian_recarray()
numpy.core.tests.test_regression.TestRegression.test_endian_recarray (self)
Definition at line 174 of file test_regression.py.
test_endian_where()
numpy.core.tests.test_regression.TestRegression.test_endian_where (self)
Definition at line 164 of file test_regression.py.
test_eq_string_and_object_array()
numpy.core.tests.test_regression.TestRegression.test_eq_string_and_object_array (self)
Definition at line 1658 of file test_regression.py.
test_fancy_index()
numpy.core.tests.test_regression.TestRegression.test_fancy_index (self)
Definition at line 556 of file test_regression.py.
test_field_access_by_title()
numpy.core.tests.test_regression.TestRegression.test_field_access_by_title (self)
Definition at line 2399 of file test_regression.py.
test_fields_strides()
numpy.core.tests.test_regression.TestRegression.test_fields_strides (self)
Definition at line 1882 of file test_regression.py.
test_find_common_type_boolean()
numpy.core.tests.test_regression.TestRegression.test_find_common_type_boolean (self)
Definition at line 1672 of file test_regression.py.
test_flat_assignment()
numpy.core.tests.test_regression.TestRegression.test_flat_assignment (self)
Definition at line 305 of file test_regression.py.
test_flat_byteorder()
numpy.core.tests.test_regression.TestRegression.test_flat_byteorder (self)
Definition at line 886 of file test_regression.py.
test_flat_index_byteswap()
numpy.core.tests.test_regression.TestRegression.test_flat_index_byteswap (self)
Definition at line 896 of file test_regression.py.
test_for_equal_names()
numpy.core.tests.test_regression.TestRegression.test_for_equal_names (self)
Definition at line 1216 of file test_regression.py.
test_for_object_scalar_creation()
numpy.core.tests.test_regression.TestRegression.test_for_object_scalar_creation (self)
Definition at line 1226 of file test_regression.py.
test_for_zero_length_in_choose()
numpy.core.tests.test_regression.TestRegression.test_for_zero_length_in_choose (self)
Definition at line 1245 of file test_regression.py.
test_format_on_flex_array_element()
numpy.core.tests.test_regression.TestRegression.test_format_on_flex_array_element (self)
Definition at line 2149 of file test_regression.py.
test_fortran_order_buffer()
numpy.core.tests.test_regression.TestRegression.test_fortran_order_buffer (self)
Definition at line 2134 of file test_regression.py.
test_fromfile_tofile_seeks()
numpy.core.tests.test_regression.TestRegression.test_fromfile_tofile_seeks (self)
Definition at line 1600 of file test_regression.py.
test_fromiter_bytes()
numpy.core.tests.test_regression.TestRegression.test_fromiter_bytes (self)
Definition at line 1328 of file test_regression.py.
test_fromiter_comparison()
numpy.core.tests.test_regression.TestRegression.test_fromiter_comparison (self)
Definition at line 1512 of file test_regression.py.
test_frompyfunc_endian()
numpy.core.tests.test_regression.TestRegression.test_frompyfunc_endian (self)
Definition at line 758 of file test_regression.py.
test_frompyfunc_many_args()
numpy.core.tests.test_regression.TestRegression.test_frompyfunc_many_args (self)
Definition at line 2234 of file test_regression.py.
test_frompyfunc_name()
numpy.core.tests.test_regression.TestRegression.test_frompyfunc_name (self)
Definition at line 2516 of file test_regression.py.
test_frompyfunc_nout_0()
numpy.core.tests.test_regression.TestRegression.test_frompyfunc_nout_0 (self)
Definition at line 2248 of file test_regression.py.
test_fromstring()
numpy.core.tests.test_regression.TestRegression.test_fromstring (self)
Definition at line 861 of file test_regression.py.
test_fromstring_crash()
numpy.core.tests.test_regression.TestRegression.test_fromstring_crash (self)
Definition at line 1518 of file test_regression.py.
test_hstack_invalid_dims()
numpy.core.tests.test_regression.TestRegression.test_hstack_invalid_dims (self)
Definition at line 259 of file test_regression.py.
test_huge_arange()
numpy.core.tests.test_regression.TestRegression.test_huge_arange (self)
Definition at line 1319 of file test_regression.py.
test_indexing1()
numpy.core.tests.test_regression.TestRegression.test_indexing1 (self)
Definition at line 104 of file test_regression.py.
test_indexing2()
numpy.core.tests.test_regression.TestRegression.test_indexing2 (self)
Definition at line 111 of file test_regression.py.
test_invalid_round()
numpy.core.tests.test_regression.TestRegression.test_invalid_round (self)
Definition at line 22 of file test_regression.py.
test_invalid_structured_dtypes()
numpy.core.tests.test_regression.TestRegression.test_invalid_structured_dtypes (self)
Definition at line 2308 of file test_regression.py.
test_junk_in_string_fields_of_recarray()
numpy.core.tests.test_regression.TestRegression.test_junk_in_string_fields_of_recarray (self)
Definition at line 726 of file test_regression.py.
test_large_float_sum()
numpy.core.tests.test_regression.TestRegression.test_large_float_sum (self)
Definition at line 1699 of file test_regression.py.
test_leak_in_structured_dtype_comparison()
numpy.core.tests.test_regression.TestRegression.test_leak_in_structured_dtype_comparison (self)
Definition at line 2261 of file test_regression.py.
test_lexsort()
numpy.core.tests.test_regression.TestRegression.test_lexsort (self)
Definition at line 406 of file test_regression.py.
test_lexsort_buffer_length()
numpy.core.tests.test_regression.TestRegression.test_lexsort_buffer_length (self)
Definition at line 1368 of file test_regression.py.
test_lexsort_invalid_axis()
numpy.core.tests.test_regression.TestRegression.test_lexsort_invalid_axis (self)
Definition at line 441 of file test_regression.py.
test_lexsort_invalid_sequence()
numpy.core.tests.test_regression.TestRegression.test_lexsort_invalid_sequence (self)
Definition at line 411 of file test_regression.py.
test_lexsort_zerolen_custom_strides()
numpy.core.tests.test_regression.TestRegression.test_lexsort_zerolen_custom_strides (self)
Definition at line 422 of file test_regression.py.
test_lexsort_zerolen_custom_strides_2d()
numpy.core.tests.test_regression.TestRegression.test_lexsort_zerolen_custom_strides_2d (self)
Definition at line 430 of file test_regression.py.
test_lexsort_zerolen_element()
numpy.core.tests.test_regression.TestRegression.test_lexsort_zerolen_element (self)
Definition at line 446 of file test_regression.py.
test_log1p_compiler_shenanigans()
numpy.core.tests.test_regression.TestRegression.test_log1p_compiler_shenanigans (self)
Definition at line 1508 of file test_regression.py.
test_mem_0d_array_index()
numpy.core.tests.test_regression.TestRegression.test_mem_0d_array_index (self)
Definition at line 1057 of file test_regression.py.
test_mem_around()
numpy.core.tests.test_regression.TestRegression.test_mem_around (self)
Definition at line 393 of file test_regression.py.
test_mem_array_creation_invalid_specification()
numpy.core.tests.test_regression.TestRegression.test_mem_array_creation_invalid_specification (self)
Definition at line 352 of file test_regression.py.
test_mem_axis_minimization()
numpy.core.tests.test_regression.TestRegression.test_mem_axis_minimization (self)
Definition at line 594 of file test_regression.py.
test_mem_custom_float_to_array()
numpy.core.tests.test_regression.TestRegression.test_mem_custom_float_to_array (self)
Definition at line 1019 of file test_regression.py.
test_mem_deallocation_leak()
numpy.core.tests.test_regression.TestRegression.test_mem_deallocation_leak (self)
Definition at line 793 of file test_regression.py.
test_mem_divmod()
numpy.core.tests.test_regression.TestRegression.test_mem_divmod (self)
Definition at line 254 of file test_regression.py.
test_mem_dot()
numpy.core.tests.test_regression.TestRegression.test_mem_dot (self)
Definition at line 190 of file test_regression.py.
test_mem_dtype_align()
numpy.core.tests.test_regression.TestRegression.test_mem_dtype_align (self)
Definition at line 146 of file test_regression.py.
test_mem_empty()
numpy.core.tests.test_regression.TestRegression.test_mem_empty (self)
Definition at line 27 of file test_regression.py.
test_mem_float_imag()
numpy.core.tests.test_regression.TestRegression.test_mem_float_imag (self)
Definition at line 599 of file test_regression.py.
test_mem_fromiter_invalid_dtype_string()
numpy.core.tests.test_regression.TestRegression.test_mem_fromiter_invalid_dtype_string (self)
Definition at line 1045 of file test_regression.py.
test_mem_lexsort_strings()
numpy.core.tests.test_regression.TestRegression.test_mem_lexsort_strings (self)
Definition at line 551 of file test_regression.py.
test_mem_on_invalid_dtype()
numpy.core.tests.test_regression.TestRegression.test_mem_on_invalid_dtype (self)
Definition at line 799 of file test_regression.py.
test_mem_scalar_indexing()
numpy.core.tests.test_regression.TestRegression.test_mem_scalar_indexing (self)
Definition at line 852 of file test_regression.py.
test_mem_string_arr()
numpy.core.tests.test_regression.TestRegression.test_mem_string_arr (self)
Definition at line 767 of file test_regression.py.
test_memoryleak()
numpy.core.tests.test_regression.TestRegression.test_memoryleak (self)
Definition at line 2029 of file test_regression.py.
test_method_args()
numpy.core.tests.test_regression.TestRegression.test_method_args (self)
Definition at line 516 of file test_regression.py.
test_misaligned_dot_product_objects()
numpy.core.tests.test_regression.TestRegression.test_misaligned_dot_product_objects (self)
Definition at line 1435 of file test_regression.py.
test_misaligned_objects_segfault()
numpy.core.tests.test_regression.TestRegression.test_misaligned_objects_segfault (self)
Definition at line 1414 of file test_regression.py.
test_misaligned_scalars_segfault()
numpy.core.tests.test_regression.TestRegression.test_misaligned_scalars_segfault (self)
Definition at line 1428 of file test_regression.py.
test_mixed_string_byte_array_creation()
numpy.core.tests.test_regression.TestRegression.test_mixed_string_byte_array_creation (self)
Definition at line 1402 of file test_regression.py.
test_multidim_byteswap()
numpy.core.tests.test_regression.TestRegression.test_multidim_byteswap (self)
Definition at line 715 of file test_regression.py.
test_multiple_assign()
numpy.core.tests.test_regression.TestRegression.test_multiple_assign (self)
Definition at line 502 of file test_regression.py.
test_ndmin_float64()
numpy.core.tests.test_regression.TestRegression.test_ndmin_float64 (self)
Definition at line 581 of file test_regression.py.
test_ndmin_order()
numpy.core.tests.test_regression.TestRegression.test_ndmin_order (self)
Definition at line 587 of file test_regression.py.
test_negative_nd_indexing()
numpy.core.tests.test_regression.TestRegression.test_negative_nd_indexing (self)
Definition at line 73 of file test_regression.py.
test_nonarray_assignment()
numpy.core.tests.test_regression.TestRegression.test_nonarray_assignment (self, index)
Definition at line 330 of file test_regression.py.
test_nonbool_logical()
numpy.core.tests.test_regression.TestRegression.test_nonbool_logical (self)
Definition at line 2559 of file test_regression.py.
test_noncommutative_reduce_accumulate()
numpy.core.tests.test_regression.TestRegression.test_noncommutative_reduce_accumulate (self)
Definition at line 699 of file test_regression.py.
test_noncontiguous_fill()
numpy.core.tests.test_regression.TestRegression.test_noncontiguous_fill (self)
Definition at line 90 of file test_regression.py.
test_nonnative_endian_fill()
numpy.core.tests.test_regression.TestRegression.test_nonnative_endian_fill (self)
Definition at line 1061 of file test_regression.py.
test_nonscalar_item_method()
numpy.core.tests.test_regression.TestRegression.test_nonscalar_item_method (self)
Definition at line 1190 of file test_regression.py.
test_nonzero_byteswap()
numpy.core.tests.test_regression.TestRegression.test_nonzero_byteswap (self)
Definition at line 1665 of file test_regression.py.
test_numeric_carray_compare()
numpy.core.tests.test_regression.TestRegression.test_numeric_carray_compare (self)
Definition at line 611 of file test_regression.py.
test_numpy_float_python_long_addition()
numpy.core.tests.test_regression.TestRegression.test_numpy_float_python_long_addition (self)
Definition at line 276 of file test_regression.py.
test_object_argmax()
numpy.core.tests.test_regression.TestRegression.test_object_argmax (self)
Definition at line 669 of file test_regression.py.
test_object_array_assign()
numpy.core.tests.test_regression.TestRegression.test_object_array_assign (self)
Definition at line 576 of file test_regression.py.
test_object_array_circular_reference()
numpy.core.tests.test_regression.TestRegression.test_object_array_circular_reference (self)
Definition at line 1804 of file test_regression.py.
test_object_array_fill()
numpy.core.tests.test_regression.TestRegression.test_object_array_fill (self)
Definition at line 141 of file test_regression.py.
test_object_array_from_list()
numpy.core.tests.test_regression.TestRegression.test_object_array_from_list (self)
Definition at line 498 of file test_regression.py.
test_object_array_nested()
numpy.core.tests.test_regression.TestRegression.test_object_array_nested (self)
Definition at line 1820 of file test_regression.py.
test_object_array_refcount_self_assign()
numpy.core.tests.test_regression.TestRegression.test_object_array_refcount_self_assign (self)
Definition at line 1028 of file test_regression.py.
test_object_array_refcounting()
numpy.core.tests.test_regression.TestRegression.test_object_array_refcounting (self)
Definition at line 916 of file test_regression.py.
test_object_array_self_copy()
numpy.core.tests.test_regression.TestRegression.test_object_array_self_copy (self)
Definition at line 1828 of file test_regression.py.
test_object_array_self_reference()
numpy.core.tests.test_regression.TestRegression.test_object_array_self_reference (self)
Definition at line 1795 of file test_regression.py.
test_object_array_shape()
numpy.core.tests.test_regression.TestRegression.test_object_array_shape (self)
Definition at line 384 of file test_regression.py.
test_object_array_to_fixed_string()
numpy.core.tests.test_regression.TestRegression.test_object_array_to_fixed_string (self)
Definition at line 1375 of file test_regression.py.
test_object_casting()
numpy.core.tests.test_regression.TestRegression.test_object_casting (self)
Definition at line 811 of file test_regression.py.
test_object_casting_errors()
numpy.core.tests.test_regression.TestRegression.test_object_casting_errors (self)
Definition at line 2429 of file test_regression.py.
test_objectarray_setfield()
numpy.core.tests.test_regression.TestRegression.test_objectarray_setfield (self)
Definition at line 1842 of file test_regression.py.
test_pickle_bytes_overwrite()
numpy.core.tests.test_regression.TestRegression.test_pickle_bytes_overwrite (self)
Definition at line 1929 of file test_regression.py.
test_pickle_datetime64_array()
numpy.core.tests.test_regression.TestRegression.test_pickle_datetime64_array (self)
Definition at line 2446 of file test_regression.py.
test_pickle_dtype()
numpy.core.tests.test_regression.TestRegression.test_pickle_dtype (self)
Definition at line 486 of file test_regression.py.
test_pickle_empty_string()
numpy.core.tests.test_regression.TestRegression.test_pickle_empty_string (self)
Definition at line 2227 of file test_regression.py.
test_pickle_module()
numpy.core.tests.test_regression.TestRegression.test_pickle_module (self, protocol, val)
Definition at line 2419 of file test_regression.py.
test_pickle_py2_array_latin1_hack()
numpy.core.tests.test_regression.TestRegression.test_pickle_py2_array_latin1_hack (self)
Definition at line 1937 of file test_regression.py.
test_pickle_py2_bytes_encoding()
numpy.core.tests.test_regression.TestRegression.test_pickle_py2_bytes_encoding (self)
Definition at line 452 of file test_regression.py.
test_pickle_py2_scalar_latin1_hack()
numpy.core.tests.test_regression.TestRegression.test_pickle_py2_scalar_latin1_hack (self)
Definition at line 1952 of file test_regression.py.
test_pickle_string_overwrite()
numpy.core.tests.test_regression.TestRegression.test_pickle_string_overwrite (self)
Definition at line 1915 of file test_regression.py.
test_pickle_transposed()
numpy.core.tests.test_regression.TestRegression.test_pickle_transposed (self)
Definition at line 31 of file test_regression.py.
test_rand_seed()
numpy.core.tests.test_regression.TestRegression.test_rand_seed (self)
Definition at line 788 of file test_regression.py.
test_random_shuffle()
numpy.core.tests.test_regression.TestRegression.test_random_shuffle (self)
Definition at line 684 of file test_regression.py.
test_ravel_with_order()
numpy.core.tests.test_regression.TestRegression.test_ravel_with_order (self)
Definition at line 61 of file test_regression.py.
test_rec_fromarray()
numpy.core.tests.test_regression.TestRegression.test_rec_fromarray (self)
Definition at line 569 of file test_regression.py.
test_rec_iterate()
numpy.core.tests.test_regression.TestRegression.test_rec_iterate (self)
Definition at line 285 of file test_regression.py.
test_recarray_copy()
numpy.core.tests.test_regression.TestRegression.test_recarray_copy (self)
Definition at line 561 of file test_regression.py.
test_recarray_fields()
numpy.core.tests.test_regression.TestRegression.test_recarray_fields (self)
Definition at line 673 of file test_regression.py.
test_recarray_single_element()
numpy.core.tests.test_regression.TestRegression.test_recarray_single_element (self)
Definition at line 360 of file test_regression.py.
test_recarray_tolist()
numpy.core.tests.test_regression.TestRegression.test_recarray_tolist (self)
Definition at line 1180 of file test_regression.py.
test_reduce()
numpy.core.tests.test_regression.TestRegression.test_reduce (self)
Definition at line 46 of file test_regression.py.
test_reduce_big_object_array()
numpy.core.tests.test_regression.TestRegression.test_reduce_big_object_array (self)
Definition at line 1050 of file test_regression.py.
test_reduce_contiguous()
numpy.core.tests.test_regression.TestRegression.test_reduce_contiguous (self)
Definition at line 1786 of file test_regression.py.
test_refcount_error_in_clip()
numpy.core.tests.test_regression.TestRegression.test_refcount_error_in_clip (self)
Definition at line 2086 of file test_regression.py.
test_refcount_vdot()
numpy.core.tests.test_regression.TestRegression.test_refcount_vdot (self)
Definition at line 691 of file test_regression.py.
test_repeat_broadcasting()
numpy.core.tests.test_regression.TestRegression.test_repeat_broadcasting (self)
Definition at line 2242 of file test_regression.py.
test_repeat_discont()
numpy.core.tests.test_regression.TestRegression.test_repeat_discont (self)
Definition at line 658 of file test_regression.py.
test_reshape_order()
numpy.core.tests.test_regression.TestRegression.test_reshape_order (self)
Definition at line 626 of file test_regression.py.
test_reshape_size_overflow()
numpy.core.tests.test_regression.TestRegression.test_reshape_size_overflow (self)
Definition at line 2291 of file test_regression.py.
test_reshape_trailing_ones_strides()
numpy.core.tests.test_regression.TestRegression.test_reshape_trailing_ones_strides (self)
Definition at line 649 of file test_regression.py.
test_reshape_zero_size()
numpy.core.tests.test_regression.TestRegression.test_reshape_zero_size (self)
Definition at line 640 of file test_regression.py.
test_reshape_zero_strides()
numpy.core.tests.test_regression.TestRegression.test_reshape_zero_strides (self)
Definition at line 634 of file test_regression.py.
test_richcompare_crash()
numpy.core.tests.test_regression.TestRegression.test_richcompare_crash (self)
Definition at line 2198 of file test_regression.py.
test_richcompare_scalar_and_subclass()
numpy.core.tests.test_regression.TestRegression.test_richcompare_scalar_and_subclass (self)
Definition at line 2216 of file test_regression.py.
test_round()
numpy.core.tests.test_regression.TestRegression.test_round (self)
Definition at line 118 of file test_regression.py.
test_scalar_compare()
numpy.core.tests.test_regression.TestRegression.test_scalar_compare (self)
Definition at line 123 of file test_regression.py.
test_scalar_copy()
numpy.core.tests.test_regression.TestRegression.test_scalar_copy (self)
Definition at line 2346 of file test_regression.py.
test_search_sorted_invalid_arguments()
numpy.core.tests.test_regression.TestRegression.test_search_sorted_invalid_arguments (self)
Definition at line 2043 of file test_regression.py.
test_searchsorted_variable_length()
numpy.core.tests.test_regression.TestRegression.test_searchsorted_variable_length (self)
Definition at line 865 of file test_regression.py.
test_searchsorted_wrong_dtype()
numpy.core.tests.test_regression.TestRegression.test_searchsorted_wrong_dtype (self)
Definition at line 2095 of file test_regression.py.
test_setting_rank0_string()
numpy.core.tests.test_regression.TestRegression.test_setting_rank0_string (self)
Definition at line 1847 of file test_regression.py.
test_sign_bit()
numpy.core.tests.test_regression.TestRegression.test_sign_bit (self)
Definition at line 892 of file test_regression.py.
test_sign_for_complex_nan()
numpy.core.tests.test_regression.TestRegression.test_sign_for_complex_nan (self)
Definition at line 1208 of file test_regression.py.
test_signed_integer_division_overflow()
numpy.core.tests.test_regression.TestRegression.test_signed_integer_division_overflow (self)
Definition at line 1488 of file test_regression.py.
test_sort_bigendian()
numpy.core.tests.test_regression.TestRegression.test_sort_bigendian (self)
Definition at line 66 of file test_regression.py.
test_squeeze_axis_handling()
numpy.core.tests.test_regression.TestRegression.test_squeeze_axis_handling (self)
Definition at line 1725 of file test_regression.py.
test_squeeze_contiguous()
numpy.core.tests.test_regression.TestRegression.test_squeeze_contiguous (self)
Definition at line 1717 of file test_regression.py.
test_squeeze_type()
numpy.core.tests.test_regression.TestRegression.test_squeeze_type (self)
Definition at line 265 of file test_regression.py.
test_startswith()
numpy.core.tests.test_regression.TestRegression.test_startswith (self)
Definition at line 695 of file test_regression.py.
test_string_argsort_with_zeros()
numpy.core.tests.test_regression.TestRegression.test_string_argsort_with_zeros (self)
Definition at line 870 of file test_regression.py.
test_string_array_size()
numpy.core.tests.test_regression.TestRegression.test_string_array_size (self)
Definition at line 615 of file test_regression.py.
test_string_astype()
numpy.core.tests.test_regression.TestRegression.test_string_astype (self)
Definition at line 1863 of file test_regression.py.
test_string_mergesort()
numpy.core.tests.test_regression.TestRegression.test_string_mergesort (self)
Definition at line 778 of file test_regression.py.
test_string_NULL()
numpy.core.tests.test_regression.TestRegression.test_string_NULL (self)
Definition at line 721 of file test_regression.py.
test_string_sort_with_zeros()
numpy.core.tests.test_regression.TestRegression.test_string_sort_with_zeros (self)
Definition at line 876 of file test_regression.py.
test_string_truncation()
numpy.core.tests.test_regression.TestRegression.test_string_truncation (self)
Definition at line 2048 of file test_regression.py.
test_string_truncation_ucs2()
numpy.core.tests.test_regression.TestRegression.test_string_truncation_ucs2 (self)
Definition at line 2064 of file test_regression.py.
test_structarray_title()
numpy.core.tests.test_regression.TestRegression.test_structarray_title (self)
Definition at line 2373 of file test_regression.py.
test_structured_arrays_with_objects1()
numpy.core.tests.test_regression.TestRegression.test_structured_arrays_with_objects1 (self)
Definition at line 1459 of file test_regression.py.
test_structured_arrays_with_objects2()
numpy.core.tests.test_regression.TestRegression.test_structured_arrays_with_objects2 (self)
Definition at line 1472 of file test_regression.py.
test_structured_count_nonzero()
numpy.core.tests.test_regression.TestRegression.test_structured_count_nonzero (self)
Definition at line 2120 of file test_regression.py.
test_structured_type_to_object()
numpy.core.tests.test_regression.TestRegression.test_structured_type_to_object (self)
Definition at line 1996 of file test_regression.py.
test_subclass_int_tuple_assignment()
numpy.core.tests.test_regression.TestRegression.test_subclass_int_tuple_assignment (self)
Definition at line 1567 of file test_regression.py.
test_swap_real()
numpy.core.tests.test_regression.TestRegression.test_swap_real (self)
Definition at line 491 of file test_regression.py.
test_take_object_fail()
numpy.core.tests.test_regression.TestRegression.test_take_object_fail (self)
Definition at line 739 of file test_regression.py.
test_take_output()
numpy.core.tests.test_regression.TestRegression.test_take_output (self)
Definition at line 731 of file test_regression.py.
test_take_refcount()
numpy.core.tests.test_regression.TestRegression.test_take_refcount (self)
Definition at line 1586 of file test_regression.py.
test_ticket_1434()
numpy.core.tests.test_regression.TestRegression.test_ticket_1434 (self)
Definition at line 1550 of file test_regression.py.
test_ticket_1538()
numpy.core.tests.test_regression.TestRegression.test_ticket_1538 (self)
Definition at line 1544 of file test_regression.py.
test_ticket_1539()
numpy.core.tests.test_regression.TestRegression.test_ticket_1539 (self)
Definition at line 1523 of file test_regression.py.
test_ticket_1608()
numpy.core.tests.test_regression.TestRegression.test_ticket_1608 (self)
Definition at line 1909 of file test_regression.py.
test_ticket_1756()
numpy.core.tests.test_regression.TestRegression.test_ticket_1756 (self)
Definition at line 1873 of file test_regression.py.
test_ticket_1770()
numpy.core.tests.test_regression.TestRegression.test_ticket_1770 (self)
Definition at line 1897 of file test_regression.py.
test_to_ctypes()
numpy.core.tests.test_regression.TestRegression.test_to_ctypes (self)
Definition at line 2483 of file test_regression.py.
test_tobytes_FORTRANORDER_discontiguous()
numpy.core.tests.test_regression.TestRegression.test_tobytes_FORTRANORDER_discontiguous (self)
Definition at line 299 of file test_regression.py.
test_ufunc_casting_out()
numpy.core.tests.test_regression.TestRegression.test_ufunc_casting_out (self)
Definition at line 1703 of file test_regression.py.
test_ufunc_no_unnecessary_views()
numpy.core.tests.test_regression.TestRegression.test_ufunc_no_unnecessary_views (self)
Definition at line 1577 of file test_regression.py.
test_ufunc_order()
numpy.core.tests.test_regression.TestRegression.test_ufunc_order (self, operation, order)
Definition at line 2545 of file test_regression.py.
test_ufunc_reduce_memoryleak()
numpy.core.tests.test_regression.TestRegression.test_ufunc_reduce_memoryleak (self)
Definition at line 2037 of file test_regression.py.
test_uint_int_conversion()
numpy.core.tests.test_regression.TestRegression.test_uint_int_conversion (self)
Definition at line 1648 of file test_regression.py.
test_unaligned_unicode_access()
numpy.core.tests.test_regression.TestRegression.test_unaligned_unicode_access (self)
Definition at line 1200 of file test_regression.py.
test_unicode_alloc_dealloc_match()
numpy.core.tests.test_regression.TestRegression.test_unicode_alloc_dealloc_match (self)
Definition at line 2079 of file test_regression.py.
test_unicode_scalar()
numpy.core.tests.test_regression.TestRegression.test_unicode_scalar (self)
Definition at line 822 of file test_regression.py.
test_unicode_string_comparison()
numpy.core.tests.test_regression.TestRegression.test_unicode_string_comparison (self)
Definition at line 293 of file test_regression.py.
test_unicode_swapping()
numpy.core.tests.test_regression.TestRegression.test_unicode_swapping (self)
Definition at line 134 of file test_regression.py.
test_unicode_to_string_cast()
numpy.core.tests.test_regression.TestRegression.test_unicode_to_string_cast (self)
Definition at line 1388 of file test_regression.py.
test_unicode_to_string_cast_error()
numpy.core.tests.test_regression.TestRegression.test_unicode_to_string_cast_error (self)
Definition at line 1395 of file test_regression.py.
test_unique_stable()
numpy.core.tests.test_regression.TestRegression.test_unique_stable (self)
Definition at line 2071 of file test_regression.py.
test_unpickle_dtype_with_object()
numpy.core.tests.test_regression.TestRegression.test_unpickle_dtype_with_object (self)
Definition at line 342 of file test_regression.py.
test_void_compare_segfault()
numpy.core.tests.test_regression.TestRegression.test_void_compare_segfault (self)
Definition at line 2286 of file test_regression.py.
test_void_copyswap()
numpy.core.tests.test_regression.TestRegression.test_void_copyswap (self)
Definition at line 510 of file test_regression.py.
test_void_getitem()
numpy.core.tests.test_regression.TestRegression.test_void_getitem (self)
Definition at line 2366 of file test_regression.py.
test_void_item_memview()
numpy.core.tests.test_regression.TestRegression.test_void_item_memview (self)
Definition at line 2359 of file test_regression.py.
test_void_scalar_constructor()
numpy.core.tests.test_regression.TestRegression.test_void_scalar_constructor (self)
Definition at line 1262 of file test_regression.py.
test_void_scalar_with_titles()
numpy.core.tests.test_regression.TestRegression.test_void_scalar_with_titles (self)
Definition at line 1254 of file test_regression.py.
test_zero_sized_array_indexing()
numpy.core.tests.test_regression.TestRegression.test_zero_sized_array_indexing (self)
Definition at line 368 of file test_regression.py.
test_zeros()
numpy.core.tests.test_regression.TestRegression.test_zeros (self)
Definition at line 1311 of file test_regression.py.
test_zeros_order()
numpy.core.tests.test_regression.TestRegression.test_zeros_order (self)
Definition at line 50 of file test_regression.py.
test_zerosize_accumulate()
numpy.core.tests.test_regression.TestRegression.test_zerosize_accumulate (self)
Definition at line 1837 of file test_regression.py.
Member Data Documentation
deleted
bool numpy.core.tests.test_regression.TestRegression.deleted = True
Definition at line 1034 of file test_regression.py.
info
numpy.core.tests.test_regression.TestRegression.info = getattr(obj, 'info', '')
Definition at line 1118 of file test_regression.py.
Referenced by pandas.core.frame.DataFrame.__repr__(), PIL.BmpImagePlugin.BmpImageFile._bitmap(), joblib.memory.MemorizedFunc._cached_call(), pandas.io.pytables.Table._create_axes(), pandas.io.formats.info._DataFrameInfoPrinter._create_table_builder(), pandas.io.formats.info._SeriesInfoPrinter._create_table_builder(), pandas.io.pytables.Table._read_axes(), pandas.core.frame.DataFrame._repr_html_(), PIL.Image.Image._repr_jpeg_(), PIL.Image.Image.apply_transparency(), PIL.Image.Image.close(), pandas.io.formats.info._DataFrameInfoPrinter.col_count(), pandas.io.formats.info._DataFrameTableBuilder.col_count(), pandas.io.formats.info._DataFrameTableBuilder.data(), pandas.io.formats.info._SeriesTableBuilder.data(), pandas.io.formats.info._TableBuilderAbstract.display_memory_usage(), PIL.JpegImagePlugin.JpegImageFile.draft(), pandas.io.formats.info._TableBuilderAbstract.dtype_counts(), pandas.io.formats.info._TableBuilderAbstract.dtypes(), pandas.io.pytables.Table.get_attrs(), pandas.io.formats.info._TableBuilderAbstract.get_lines(), pandas.io.pytables.AppendableFrameTable.get_object(), PIL.Image.Image.getexif(), PIL.Image.Image.getxmp(), PIL.Image.Image.has_transparency_data(), pandas.io.formats.info._DataFrameTableBuilder.ids(), pip._vendor.distlib.wheel.Wheel.install(), PIL.AvifImagePlugin.AvifImageFile.load(), PIL.IcoImagePlugin.IcoImageFile.load(), PIL.Image.Image.load(), PIL.WebPImagePlugin.WebPImageFile.load(), PIL.WmfImagePlugin.WmfStubImageFile.load(), pandas.io.formats.info._TableBuilderAbstract.memory_usage_string(), pandas.io.pytables.Table.read_column(), pip._internal.models.direct_url.DirectUrl.redacted_url(), PIL.Image.Image.remap_palette(), PIL.GifImagePlugin.GifImageFile.seek(), PIL.MpoImagePlugin.MpoImageFile.seek(), PIL.TiffImagePlugin.TiffImageFile.seek(), pandas.io.pytables.Table.set_attrs(), PIL.Image.Image.transform(), and pandas.io.pytables.Table.validate_data_columns().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/core/tests/test_regression.py