Code Cloning Analysis: matplotlib.units.DecimalConverter Class Reference
matplotlib.units.DecimalConverter Class Reference
Static Public Member Functions
convert (value, unit, axis)
Static Public Member Functions inherited from matplotlib.units.ConversionInterface
axisinfo (unit, axis)
default_units (x, axis)
Detailed Description
Converter for decimal.Decimal data to float.
Definition at line 135 of file units.py.
Member Function Documentation
convert()
matplotlib.units.DecimalConverter.convert (value, unit, axis) static
Convert Decimals to floats.
The *unit* and *axis* arguments are not used.
Parameters
----------
value : decimal.Decimal or iterable
    Decimal or list of Decimal need to be converted
Reimplemented from matplotlib.units.ConversionInterface.
Definition at line 139 of file units.py.
Referenced by pandas.core.computation.engines.NumExprEngine._evaluate(), pandas.core.internals.blocks.Block.convert(), PIL.Image.Image.reduce(), PIL.Image.Image.resize(), and PIL.Image.Image.transform().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/units.py