Code Cloning Analysis: sklearn.decomposition.tests.test_fastica Namespace Reference
sklearn.decomposition.tests.test_fastica Namespace Reference
Functions
center_and_norm (x, axis=-1)
test_gs (global_random_seed)
test_fastica_attributes_dtypes (global_dtype)
test_fastica_return_dtypes (global_dtype)
test_fastica_simple (add_noise, global_random_seed, global_dtype)
test_fastica_nowhiten ()
test_fastica_convergence_fail (global_random_seed)
test_non_square_fastica (global_random_seed, add_noise)
test_fit_transform (global_random_seed, global_dtype)
test_inverse_transform (whiten, n_components, expected_mixing_shape, global_random_seed, global_dtype)
test_fastica_errors ()
test_fastica_whiten_unit_variance (global_random_seed)
test_fastica_output_shape (whiten, return_X_mean, return_n_iter)
test_fastica_simple_different_solvers (add_noise, global_random_seed)
test_fastica_eigh_low_rank_warning (global_random_seed)
Detailed Description
Test the fastica algorithm.
Function Documentation
center_and_norm()
sklearn.decomposition.tests.test_fastica.center_and_norm (x, axis = -1)
Centers and norms x **in place**
Parameters
-----------
x: ndarray
    Array with an axis of observations (statistical units) measured on
    random variables.
axis: int, optional
    Axis along which the mean and variance are calculated.
Definition at line 19 of file test_fastica.py.
References center_and_norm().
Referenced by center_and_norm(), and test_fastica_simple_different_solvers().
test_fastica_attributes_dtypes()
sklearn.decomposition.tests.test_fastica.test_fastica_attributes_dtypes (global_dtype)
Definition at line 49 of file test_fastica.py.
test_fastica_convergence_fail()
sklearn.decomposition.tests.test_fastica.test_fastica_convergence_fail (global_random_seed)
Definition at line 191 of file test_fastica.py.
test_fastica_eigh_low_rank_warning()
sklearn.decomposition.tests.test_fastica.test_fastica_eigh_low_rank_warning (global_random_seed)
Test FastICA eigh solver raises warning for low-rank data.
Definition at line 444 of file test_fastica.py.
test_fastica_errors()
sklearn.decomposition.tests.test_fastica.test_fastica_errors ()
Definition at line 361 of file test_fastica.py.
test_fastica_nowhiten()
sklearn.decomposition.tests.test_fastica.test_fastica_nowhiten ()
Definition at line 180 of file test_fastica.py.
test_fastica_output_shape()
sklearn.decomposition.tests.test_fastica.test_fastica_output_shape (whiten, return_X_mean, return_n_iter)
Definition at line 392 of file test_fastica.py.
test_fastica_return_dtypes()
sklearn.decomposition.tests.test_fastica.test_fastica_return_dtypes (global_dtype)
Definition at line 61 of file test_fastica.py.
test_fastica_simple()
sklearn.decomposition.tests.test_fastica.test_fastica_simple (add_noise, global_random_seed, global_dtype)
Definition at line 73 of file test_fastica.py.
test_fastica_simple_different_solvers()
sklearn.decomposition.tests.test_fastica.test_fastica_simple_different_solvers (add_noise, global_random_seed)
Test FastICA is consistent between whiten_solvers.
Definition at line 410 of file test_fastica.py.
References center_and_norm().
test_fastica_whiten_unit_variance()
sklearn.decomposition.tests.test_fastica.test_fastica_whiten_unit_variance (global_random_seed)
Test unit variance of transformed data using FastICA algorithm.
Bug #13056
Definition at line 375 of file test_fastica.py.
test_fit_transform()
sklearn.decomposition.tests.test_fastica.test_fit_transform (global_random_seed, global_dtype)
Test unit variance of transformed data using FastICA algorithm.
Check that `fit_transform` gives the same result as applying
`fit` and then `transform`.
Bug #13056
Definition at line 267 of file test_fastica.py.
test_gs()
sklearn.decomposition.tests.test_fastica.test_gs (global_random_seed)
Definition at line 35 of file test_fastica.py.
test_inverse_transform()
sklearn.decomposition.tests.test_fastica.test_inverse_transform (whiten, n_components, expected_mixing_shape, global_random_seed, global_dtype)
Definition at line 329 of file test_fastica.py.
test_non_square_fastica()
sklearn.decomposition.tests.test_fastica.test_non_square_fastica (global_random_seed, add_noise)
Definition at line 222 of file test_fastica.py.