Code Cloning Analysis: sklearn.utils._testing.MinimalClassifier Class Reference
sklearn.utils._testing.MinimalClassifier Class Reference
Public Member Functions
__init__ (self, param=None)
get_params (self, deep=True)
set_params (self, **params)
fit (self, X, y)
predict_proba (self, X)
predict (self, X)
score (self, X, y)
__sklearn_tags__ (self)
Public Attributes
param = param
classes_
Protected Attributes
_most_frequent_class_idx = counts.argmax()
Detailed Description
Minimal classifier implementation without inheriting from BaseEstimator.
This estimator should be tested with:
* `check_estimator` in `test_estimator_checks.py`;
* within a `Pipeline` in `test_pipeline.py`;
* within a `SearchCV` in `test_search.py`.
Definition at line 1161 of file _testing.py.
Constructor & Destructor Documentation
__init__()
sklearn.utils._testing.MinimalClassifier.__init__ (self, param = None)
Definition at line 1171 of file _testing.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params().
Member Function Documentation
__sklearn_tags__()
sklearn.utils._testing.MinimalClassifier.__sklearn_tags__ (self)
Definition at line 1207 of file _testing.py.
fit()
sklearn.utils._testing.MinimalClassifier.fit (self, X, y)
Definition at line 1182 of file _testing.py.
Referenced by sklearn.cluster._kmeans._BaseKMeans.fit_predict(), sklearn.cluster._kmeans._BaseKMeans.fit_transform(), and sklearn.utils.tests.test_estimator_checks.SparseTransformer.fit_transform().
get_params()
sklearn.utils._testing.MinimalClassifier.get_params (self, deep = True)
Definition at line 1174 of file _testing.py.
predict()
sklearn.utils._testing.MinimalClassifier.predict (self, X)
Definition at line 1197 of file _testing.py.
predict_proba()
sklearn.utils._testing.MinimalClassifier.predict_proba (self, X)
Definition at line 1189 of file _testing.py.
score()
sklearn.utils._testing.MinimalClassifier.score (self, X, y)
Definition at line 1202 of file _testing.py.
set_params()
sklearn.utils._testing.MinimalClassifier.set_params (self, ** params)
Definition at line 1177 of file _testing.py.
Member Data Documentation
_most_frequent_class_idx
sklearn.utils._testing.MinimalClassifier._most_frequent_class_idx = counts.argmax() protected
Definition at line 1186 of file _testing.py.
classes_
sklearn.utils._testing.MinimalClassifier.classes_
Definition at line 1185 of file _testing.py.
Referenced by sklearn.ensemble._hist_gradient_boosting.gradient_boosting.BaseHistGradientBoosting._check_early_stopping_scorer(), and sklearn.naive_bayes._BaseNB.predict().
param
sklearn.utils._testing.MinimalClassifier.param = param
Definition at line 1172 of file _testing.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/sklearn/utils/_testing.py