Code Cloning Analysis: scipy.interpolate._interpolate Namespace Reference
scipy.interpolate._interpolate Namespace Reference
Classes
class _PPolyBase
class BPoly
class interp1d
class interp2d
class NdPPoly
class PPoly
Functions
lagrange (x, w)
_check_broadcast_up_to (arr_from, shape_to, name)
_do_extrapolate (fill_value)
Variables
list __all__ = ['interp1d', 'interp2d', 'lagrange', 'PPoly', 'BPoly', 'NdPPoly']
str dep_mesg
Function Documentation
_check_broadcast_up_to()
scipy.interpolate._interpolate._check_broadcast_up_to (arr_from, shape_to, name) protected
Helper to check that arr_from broadcasts up to shape_to
Definition at line 361 of file _interpolate.py.
Referenced by scipy.interpolate._interpolate.interp1d.fill_value().
_do_extrapolate()
scipy.interpolate._interpolate._do_extrapolate (fill_value) protected
Helper to check if fill_value == "extrapolate" without warnings
Definition at line 378 of file _interpolate.py.
Referenced by scipy.interpolate._interpolate.interp1d.__init__(), and scipy.interpolate._interpolate.interp1d.fill_value().
lagrange()
scipy.interpolate._interpolate.lagrange (x, w)
    Return a Lagrange interpolating polynomial.
    Given two 1-D arrays `x` and `w,` returns the Lagrange interpolating
    polynomial through the points ``(x, w)``.
    Warning: This implementation is numerically unstable. Do not expect to
    be able to use more than about 20 points even if they are chosen optimally.
    Parameters
    ----------
    x : array_like
        `x` represents the x-coordinates of a set of datapoints.
    w : array_like
        `w` represents the y-coordinates of a set of datapoints, i.e., f(`x`).
    Returns
    -------
    lagrange : `numpy.poly1d` instance
        The Lagrange interpolating polynomial.
    Examples
    --------
    Interpolate :math:`f(x) = x^3` by 3 points.
    >>> import numpy as np
    >>> from scipy.interpolate import lagrange
    >>> x = np.array([0, 1, 2])
    >>> y = x**3
    >>> poly = lagrange(x, y)
    Since there are only 3 points, Lagrange polynomial has degree 2. Explicitly,
    it is given by
    .. math::
        \begin{aligned}
            L(x) &= 1\times \frac{x (x - 2)}{-1} + 8\times \frac{x (x-1)}{2} \\
                 &= x (-2 + 3x)
        \end{aligned}
    >>> from numpy.polynomial.polynomial import Polynomial
    >>> Polynomial(poly.coef[::-1]).coef
    array([ 0., -2.,  3.])
    >>> import matplotlib.pyplot as plt
    >>> x_new = np.arange(0, 2.1, 0.1)
    >>> plt.scatter(x, y, label='data')
    >>> plt.plot(x_new, Polynomial(poly.coef[::-1])(x_new), label='Polynomial')
    >>> plt.plot(x_new, 3*x_new**2 - 2*x_new + 0*x_new,
    ...          label=r"$3 x^2 - 2 x$", linestyle='-.')
    >>> plt.legend()
    >>> plt.show()
Definition at line 20 of file _interpolate.py.
Variable Documentation
__all__
list scipy.interpolate._interpolate.__all__ = ['interp1d', 'interp2d', 'lagrange', 'PPoly', 'BPoly', 'NdPPoly'] private
Definition at line 1 of file _interpolate.py.
dep_mesg
str scipy.interpolate._interpolate.dep_mesg
Initial value:
=  """\
`interp2d` is deprecated in SciPy 1.10 and will be removed in SciPy 1.13.0.
For legacy code, nearly bug-for-bug compatible replacements are
`RectBivariateSpline` on regular grids, and `bisplrep`/`bisplev` for
scattered 2D data.
In new code, for regular grids use `RegularGridInterpolator` instead.
For scattered data, prefer `LinearNDInterpolator` or
`CloughTocher2DInterpolator`.
For more details see
`https://scipy.github.io/devdocs/notebooks/interp_transition_guide.html`
"""
Definition at line 94 of file _interpolate.py.