Code Cloning Analysis: sklearn.ensemble._bagging Namespace Reference
sklearn.ensemble._bagging Namespace Reference
Classes
class BaggingClassifier
class BaggingRegressor
class BaseBagging
Functions
_generate_indices (random_state, bootstrap, n_population, n_samples)
_generate_bagging_indices (random_state, bootstrap_features, bootstrap_samples, n_features, n_samples, max_features, max_samples)
_parallel_build_estimators (n_estimators, ensemble, X, y, seeds, total_n_estimators, verbose, check_input, fit_params)
_parallel_predict_proba (estimators, estimators_features, X, n_classes, predict_params=None, predict_proba_params=None)
_parallel_predict_log_proba (estimators, estimators_features, X, n_classes, params)
_parallel_decision_function (estimators, estimators_features, X, params)
_parallel_predict_regression (estimators, estimators_features, X, params)
Variables
list __all__ = ["BaggingClassifier", "BaggingRegressor"]
MAX_INT = np.iinfo(np.int32).max
Detailed Description
Bagging meta-estimator.
Function Documentation
_generate_bagging_indices()
sklearn.ensemble._bagging._generate_bagging_indices (random_state, bootstrap_features, bootstrap_samples, n_features, n_samples, max_features, max_samples) protected
Randomly draw feature and sample indices.
Definition at line 67 of file _bagging.py.
References _generate_indices().
Referenced by _parallel_build_estimators().
_generate_indices()
sklearn.ensemble._bagging._generate_indices (random_state, bootstrap, n_population, n_samples) protected
Draw randomly sampled indices.
Definition at line 54 of file _bagging.py.
Referenced by _generate_bagging_indices().
_parallel_build_estimators()
sklearn.ensemble._bagging._parallel_build_estimators (n_estimators, ensemble, X, y, seeds, total_n_estimators, verbose, check_input, fit_params) protected
Private function used to build a batch of estimators within a job.
Definition at line 91 of file _bagging.py.
References _generate_bagging_indices().
_parallel_decision_function()
sklearn.ensemble._bagging._parallel_decision_function (estimators, estimators_features, X, params) protected
Private function used to compute decisions within a job.
Definition at line 266 of file _bagging.py.
_parallel_predict_log_proba()
sklearn.ensemble._bagging._parallel_predict_log_proba (estimators, estimators_features, X, n_classes, params) protected
Private function used to compute log probabilities within a job.
Definition at line 241 of file _bagging.py.
_parallel_predict_proba()
sklearn.ensemble._bagging._parallel_predict_proba (estimators, estimators_features, X, n_classes, predict_params = None, predict_proba_params = None) protected
Private function used to compute (proba-)predictions within a job.
Definition at line 203 of file _bagging.py.
_parallel_predict_regression()
sklearn.ensemble._bagging._parallel_predict_regression (estimators, estimators_features, X, params) protected
Private function used to compute predictions within a job.
Definition at line 274 of file _bagging.py.
Variable Documentation
__all__
list sklearn.ensemble._bagging.__all__ = ["BaggingClassifier", "BaggingRegressor"] private
Definition at line 49 of file _bagging.py.
MAX_INT
sklearn.ensemble._bagging.MAX_INT = np.iinfo(np.int32).max
Definition at line 51 of file _bagging.py.