Code Cloning Analysis: matplotlib.colors.ColorSequenceRegistry Class Reference
matplotlib.colors.ColorSequenceRegistry Class Reference
Public Member Functions
__init__ (self)
__getitem__ (self, item)
__iter__ (self)
__len__ (self)
__str__ (self)
register (self, name, color_list)
unregister (self, name)
Protected Attributes
dict _color_sequences = {**self._BUILTIN_COLOR_SEQUENCES}
Static Protected Attributes
dict _BUILTIN_COLOR_SEQUENCES
Detailed Description
Container for sequences of colors that are known to Matplotlib by name.
The universal registry instance is `matplotlib.color_sequences`. There
should be no need for users to instantiate `.ColorSequenceRegistry`
themselves.
Read access uses a dict-like interface mapping names to lists of colors::
    import matplotlib as mpl
    colors = mpl.color_sequences['tab10']
For a list of built in color sequences, see :doc:`/gallery/color/color_sequences`.
The returned lists are copies, so that their modification does not change
the global definition of the color sequence.
Additional color sequences can be added via
`.ColorSequenceRegistry.register`::
    mpl.color_sequences.register('rgb', ['r', 'g', 'b'])
Definition at line 98 of file colors.py.
Constructor & Destructor Documentation
__init__()
matplotlib.colors.ColorSequenceRegistry.__init__ (self)
Definition at line 137 of file colors.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__getitem__()
matplotlib.colors.ColorSequenceRegistry.__getitem__ (self, item)
Definition at line 140 of file colors.py.
__iter__()
matplotlib.colors.ColorSequenceRegistry.__iter__ (self)
Definition at line 146 of file colors.py.
__len__()
matplotlib.colors.ColorSequenceRegistry.__len__ (self)
Definition at line 149 of file colors.py.
__str__()
matplotlib.colors.ColorSequenceRegistry.__str__ (self)
Definition at line 152 of file colors.py.
Referenced by numpy.polynomial._polybase.ABCPolyBase._get_coefficients().
register()
matplotlib.colors.ColorSequenceRegistry.register (self, name, color_list)
Register a new color sequence.
The color sequence registry stores a copy of the given *color_list*, so
that future changes to the original list do not affect the registered
color sequence. Think of this as the registry taking a snapshot
of *color_list* at registration.
Parameters
----------
name : str
    The name for the color sequence.
color_list : list of :mpltype:`color`
    An iterable returning valid Matplotlib colors when iterating over.
    Note however that the returned color sequence will always be a
    list regardless of the input type.
Definition at line 156 of file colors.py.
References _BUILTIN_COLOR_SEQUENCES, _color_sequences, and matplotlib.colors.to_rgba().
unregister()
matplotlib.colors.ColorSequenceRegistry.unregister (self, name)
Remove a sequence from the registry.
You cannot remove built-in color sequences.
If the name is not registered, returns with no error.
Definition at line 190 of file colors.py.
References _BUILTIN_COLOR_SEQUENCES, and _color_sequences.
Member Data Documentation
_BUILTIN_COLOR_SEQUENCES
dict matplotlib.colors.ColorSequenceRegistry._BUILTIN_COLOR_SEQUENCES static protected
Initial value:
=  {
        'tab10': _cm._tab10_data,
        'tab20': _cm._tab20_data,
        'tab20b': _cm._tab20b_data,
        'tab20c': _cm._tab20c_data,
        'Pastel1': _cm._Pastel1_data,
        'Pastel2': _cm._Pastel2_data,
        'Paired': _cm._Paired_data,
        'Accent': _cm._Accent_data,
        'Dark2': _cm._Dark2_data,
        'Set1': _cm._Set1_data,
        'Set2': _cm._Set2_data,
        'Set3': _cm._Set3_data,
        'petroff10': _cm._petroff10_data,
    }
Definition at line 121 of file colors.py.
Referenced by register(), and unregister().
_color_sequences
matplotlib.colors.ColorSequenceRegistry._color_sequences = {**self._BUILTIN_COLOR_SEQUENCES} protected
Definition at line 138 of file colors.py.
Referenced by register(), and unregister().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/colors.py