Code Cloning Analysis: matplotlib.legend Namespace Reference
matplotlib.legend Namespace Reference
Classes
class DraggableLegend
class Legend
Functions
_get_legend_handles (axs, legend_handler_map=None)
_get_legend_handles_labels (axs, legend_handler_map=None)
_parse_legend_args (axs, *args, handles=None, labels=None, **kwargs)
Variables
str _legend_kw_doc_base
str _loc_doc_base
str _loc_doc_best
tuple _legend_kw_axes_st
_legend_kw_axes
str _outside_doc
tuple _legend_kw_figure_st
_legend_kw_figure
tuple _legend_kw_both_st
_legend_kw_doc
tuple _legend_kw_set_loc_st
_legend_kw_set_loc_doc
Detailed Description
The legend module defines the Legend class, which is responsible for
drawing legends associated with Axes and/or figures.
.. important::
    It is unlikely that you would ever create a Legend instance manually.
    Most users would normally create a legend via the `~.Axes.legend`
    function. For more details on legends there is also a :ref:`legend guide
    <legend_guide>`.
The `Legend` class is a container of legend handles and legend texts.
The legend handler map specifies how to create legend handles from artists
(lines, patches, etc.) in the Axes or figures. Default legend handlers are
defined in the :mod:`~matplotlib.legend_handler` module. While not all artist
types are covered by the default legend handlers, custom legend handlers can be
defined to support arbitrary objects.
See the :ref`<legend_guide>` for more
information.
Function Documentation
_get_legend_handles()
matplotlib.legend._get_legend_handles (axs, legend_handler_map = None) protected
Yield artists that can be used as handles in a legend.
Definition at line 1229 of file legend.py.
Referenced by _get_legend_handles_labels(), and _parse_legend_args().
_get_legend_handles_labels()
matplotlib.legend._get_legend_handles_labels (axs, legend_handler_map = None) protected
Return handles and labels for legend.
Definition at line 1263 of file legend.py.
References _get_legend_handles().
Referenced by _parse_legend_args().
_parse_legend_args()
matplotlib.legend._parse_legend_args (axs, * args, handles = None, labels = None, ** kwargs) protected
Get the handles and labels from the calls to either ``figure.legend``
or ``axes.legend``.
The parser is a bit involved because we support::
    legend()
    legend(labels)
    legend(handles, labels)
    legend(labels=labels)
    legend(handles=handles)
    legend(handles=handles, labels=labels)
The behavior for a mixture of positional and keyword handles and labels
is undefined and issues a warning; it will be an error in the future.
Parameters
----------
axs : list of `.Axes`
    If handles are not given explicitly, the artists in these Axes are
    used as handles.
*args : tuple
    Positional parameters passed to ``legend()``.
handles
    The value of the keyword argument ``legend(handles=...)``, or *None*
    if that keyword argument was not used.
labels
    The value of the keyword argument ``legend(labels=...)``, or *None*
    if that keyword argument was not used.
**kwargs
    All other keyword arguments passed to ``legend()``.
Returns
-------
handles : list of (`.Artist` or tuple of `.Artist`)
    The legend handles.
labels : list of str
    The legend labels.
kwargs : dict
    *kwargs* with keywords handles and labels removed.
Definition at line 1275 of file legend.py.
References _get_legend_handles(), and _get_legend_handles_labels().
Variable Documentation
_legend_kw_axes
matplotlib.legend._legend_kw_axes protected
Definition at line 308 of file legend.py.
_legend_kw_axes_st
tuple matplotlib.legend._legend_kw_axes_st protected
Initial value:
=  (
    _loc_doc_base.format(parent='axes', default=':rc:`legend.loc`',
                         best=_loc_doc_best, outside='') +
    _legend_kw_doc_base)
Definition at line 304 of file legend.py.
_legend_kw_both_st
tuple matplotlib.legend._legend_kw_both_st protected
Initial value:
=  (
    _loc_doc_base.format(parent='axes/figure',
                         default=":rc:`legend.loc` for Axes, 'upper right' for Figure",
                         best=_loc_doc_best, outside=_outside_doc) +
    _legend_kw_doc_base)
Definition at line 328 of file legend.py.
_legend_kw_doc
matplotlib.legend._legend_kw_doc protected
Definition at line 333 of file legend.py.
_legend_kw_doc_base
str matplotlib.legend._legend_kw_doc_base protected
Definition at line 98 of file legend.py.
_legend_kw_figure
matplotlib.legend._legend_kw_figure protected
Definition at line 326 of file legend.py.
_legend_kw_figure_st
tuple matplotlib.legend._legend_kw_figure_st protected
Initial value:
=  (
    _loc_doc_base.format(parent='figure', default="'upper right'",
                         best='', outside=_outside_doc) +
    _legend_kw_doc_base)
Definition at line 322 of file legend.py.
_legend_kw_set_loc_doc
matplotlib.legend._legend_kw_set_loc_doc protected
Definition at line 339 of file legend.py.
_legend_kw_set_loc_st
tuple matplotlib.legend._legend_kw_set_loc_st protected
Initial value:
=  (
    _loc_doc_base.format(parent='axes/figure',
                         default=":rc:`legend.loc` for Axes, 'upper right' for Figure",
                         best=_loc_doc_best, outside=_outside_doc))
Definition at line 335 of file legend.py.
_loc_doc_base
str matplotlib.legend._loc_doc_base protected
Definition at line 258 of file legend.py.
_loc_doc_best
str matplotlib.legend._loc_doc_best protected
Initial value:
=  """
    The string ``'best'`` places the legend at the location, among the nine
    locations defined so far, with the minimum overlap with other drawn
    artists.  This option can be quite slow for plots with large amounts of
    data; your plotting speed may benefit from providing a specific location.
"""
Definition at line 297 of file legend.py.
_outside_doc
str matplotlib.legend._outside_doc protected
Initial value:
=  """
    If a figure is using the constrained layout manager, the string codes
    of the *loc* keyword argument can get better layout behaviour using the
    prefix 'outside'. There is ambiguity at the corners, so 'outside
    upper right' will make space for the legend above the rest of the
    axes in the layout, and 'outside right upper' will make space on the
    right side of the layout.  In addition to the values of *loc*
    listed above, we have 'outside right upper', 'outside right lower',
    'outside left upper', and 'outside left lower'.  See
    :ref:`legend_guide` for more details.
"""
Definition at line 310 of file legend.py.