Code Cloning Analysis: scipy.fft._pocketfft.realtransforms Namespace Reference
scipy.fft._pocketfft.realtransforms Namespace Reference
Functions
_r2r (forward, transform, x, type=2, n=None, axis=-1, norm=None, overwrite_x=False, workers=None, orthogonalize=None)
_r2rn (forward, transform, x, type=2, s=None, axes=None, norm=None, overwrite_x=False, workers=None, orthogonalize=None)
Variables
dct = functools.partial(_r2r, True, pfft.dct)
__name__
idct = functools.partial(_r2r, False, pfft.dct)
dst = functools.partial(_r2r, True, pfft.dst)
idst = functools.partial(_r2r, False, pfft.dst)
dctn = functools.partial(_r2rn, True, pfft.dct)
idctn = functools.partial(_r2rn, False, pfft.dct)
dstn = functools.partial(_r2rn, True, pfft.dst)
idstn = functools.partial(_r2rn, False, pfft.dst)
Function Documentation
_r2r()
scipy.fft._pocketfft.realtransforms._r2r (forward, transform, x, type = 2, n = None, axis = -1, norm = None, overwrite_x = False, workers = None, orthogonalize = None) protected
Forward or backward 1-D DCT/DST
Parameters
----------
forward : bool
    Transform direction (determines type and normalisation)
transform : {pypocketfft.dct, pypocketfft.dst}
    The transform to perform
Definition at line 8 of file realtransforms.py.
References scipy.fft._pocketfft.helper._asfarray(), scipy.fft._pocketfft.helper._datacopied(), and scipy.fft._pocketfft.helper._normalization().
_r2rn()
scipy.fft._pocketfft.realtransforms._r2rn (forward, transform, x, type = 2, s = None, axes = None, norm = None, overwrite_x = False, workers = None, orthogonalize = None) protected
Forward or backward nd DCT/DST
Parameters
----------
forward : bool
    Transform direction (determines type and normalisation)
transform : {pypocketfft.dct, pypocketfft.dst}
    The transform to perform
Definition at line 60 of file realtransforms.py.
References scipy.fft._pocketfft.helper._asfarray(), scipy.fft._pocketfft.helper._datacopied(), scipy.fft._pocketfft.helper._fix_shape(), scipy.fft._pocketfft.helper._init_nd_shape_and_axes(), and scipy.fft._pocketfft.helper._normalization().
Variable Documentation
__name__
scipy.fft._pocketfft.realtransforms.__name__ private
Definition at line 50 of file realtransforms.py.
dct
scipy.fft._pocketfft.realtransforms.dct = functools.partial(_r2r, True, pfft.dct)
Definition at line 49 of file realtransforms.py.
dctn
scipy.fft._pocketfft.realtransforms.dctn = functools.partial(_r2rn, True, pfft.dct)
Definition at line 102 of file realtransforms.py.
dst
scipy.fft._pocketfft.realtransforms.dst = functools.partial(_r2r, True, pfft.dst)
Definition at line 54 of file realtransforms.py.
dstn
scipy.fft._pocketfft.realtransforms.dstn = functools.partial(_r2rn, True, pfft.dst)
Definition at line 107 of file realtransforms.py.
idct
scipy.fft._pocketfft.realtransforms.idct = functools.partial(_r2r, False, pfft.dct)
Definition at line 51 of file realtransforms.py.
idctn
scipy.fft._pocketfft.realtransforms.idctn = functools.partial(_r2rn, False, pfft.dct)
Definition at line 104 of file realtransforms.py.
idst
scipy.fft._pocketfft.realtransforms.idst = functools.partial(_r2r, False, pfft.dst)
Definition at line 56 of file realtransforms.py.
idstn
scipy.fft._pocketfft.realtransforms.idstn = functools.partial(_r2rn, False, pfft.dst)
Definition at line 109 of file realtransforms.py.