Code Cloning Analysis: fontTools.ttLib.tables._c_m_a_p.cmap_format_12_or_13 Class Reference
fontTools.ttLib.tables._c_m_a_p.cmap_format_12_or_13 Class Reference
Public Member Functions
__init__ (self, format)
decompileHeader (self, data, ttFont)
decompile (self, data, ttFont)
compile (self, ttFont)
toXML (self, writer, ttFont)
fromXML (self, name, attrs, content, ttFont)
Public Member Functions inherited from fontTools.ttLib.tables._c_m_a_p.CmapSubtable
__init__ (self, format)
ensureDecompiled (self, recurse=False)
__getattr__ (self, attr)
getEncoding (self, default=None)
isUnicode (self)
isSymbol (self)
__lt__ (self, other)
Public Attributes
int reserved = 0
nGroups = nGroups
dict cmap = _make_map(self.ttFont, charCodes, gids)
Public Attributes inherited from fontTools.ttLib.tables._c_m_a_p.CmapSubtable
format = format
data = None
ttFont = None
int platformID = None
platEncID = None
tuple language
length = int(length)
Additional Inherited Members
Static Public Member Functions inherited from fontTools.ttLib.tables._c_m_a_p.CmapSubtable
getSubtableClass (format)
newSubtable (format)
Protected Member Functions inherited from fontTools.ttLib.tables._c_m_a_p.CmapSubtable
_writeCodes (self, codes, writer)
Detailed Description
Definition at line 1136 of file _c_m_a_p.py.
Constructor & Destructor Documentation
__init__()
fontTools.ttLib.tables._c_m_a_p.cmap_format_12_or_13.__init__ (self, format)
Definition at line 1137 of file _c_m_a_p.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
compile()
fontTools.ttLib.tables._c_m_a_p.cmap_format_12_or_13.compile (self, ttFont)
Definition at line 1189 of file _c_m_a_p.py.
Referenced by fontTools.ttLib.tables.TupleVariation.TupleVariation.getCoordWidth(), and PIL.FontFile.FontFile.save().
decompile()
fontTools.ttLib.tables._c_m_a_p.cmap_format_12_or_13.decompile (self, data, ttFont)
Definition at line 1160 of file _c_m_a_p.py.
Referenced by fontTools.ttLib.tables._c_m_a_p.CmapSubtable.newSubtable().
decompileHeader()
fontTools.ttLib.tables._c_m_a_p.cmap_format_12_or_13.decompileHeader (self, data, ttFont)
Reimplemented from fontTools.ttLib.tables._c_m_a_p.CmapSubtable.
Definition at line 1143 of file _c_m_a_p.py.
fromXML()
fontTools.ttLib.tables._c_m_a_p.cmap_format_12_or_13.fromXML (self, name, attrs, content, ttFont)
Definition at line 1289 of file _c_m_a_p.py.
toXML()
fontTools.ttLib.tables._c_m_a_p.cmap_format_12_or_13.toXML (self, writer, ttFont)
Reimplemented from fontTools.ttLib.tables._c_m_a_p.CmapSubtable.
Definition at line 1270 of file _c_m_a_p.py.
Member Data Documentation
cmap
dict fontTools.ttLib.tables._c_m_a_p.cmap_format_12_or_13.cmap = _make_map(self.ttFont, charCodes, gids)
Definition at line 1187 of file _c_m_a_p.py.
Referenced by matplotlib.colorbar.Colorbar.__init__(), matplotlib.colorbar.Colorbar._add_solids(), matplotlib.colorbar.Colorbar._do_extends(), matplotlib.contour.ContourSet._process_colors(), matplotlib.colorbar.Colorbar._process_values(), matplotlib.colorizer._ColorizerInterface.colorbar(), matplotlib.collections.PathCollection.legend_elements(), fontTools.ttLib.tables._c_m_a_p.CmapSubtable.newSubtable(), matplotlib.colorizer._ColorizerInterface.set_cmap(), matplotlib.colorizer.Colorizer.to_rgba(), matplotlib.collections.Collection.update_from(), and matplotlib.colorbar.Colorbar.update_normal().
nGroups
fontTools.ttLib.tables._c_m_a_p.cmap_format_12_or_13.nGroups = nGroups
Definition at line 1156 of file _c_m_a_p.py.
reserved
fontTools.ttLib.tables._c_m_a_p.cmap_format_12_or_13.reserved = 0
Definition at line 1139 of file _c_m_a_p.py.
Referenced by fontTools.ttLib.sfnt.SFNTReader.__getitem__(), fontTools.ttLib.woff2.WOFF2Writer.close(), and fontTools.ttLib.tables._g_v_a_r.table__g_v_a_r.compileOffsets_().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ttLib/tables/_c_m_a_p.py