Code Cloning Analysis: sklearn.covariance._shrunk_covariance Namespace Reference
sklearn.covariance._shrunk_covariance Namespace Reference
Classes
class LedoitWolf
class OAS
class ShrunkCovariance
Functions
_ledoit_wolf (X, *, assume_centered, block_size)
_oas (X, *, assume_centered=False)
shrunk_covariance (emp_cov, shrinkage=0.1)
Public API ShrunkCovariance estimator.
ledoit_wolf_shrinkage (X, assume_centered=False, block_size=1000)
ledoit_wolf (X, *, assume_centered=False, block_size=1000)
oas (X, *, assume_centered=False)
Detailed Description
Covariance estimators using shrinkage.
Shrinkage corresponds to regularising `cov` using a convex combination:
shrunk_cov = (1-shrinkage)*cov + shrinkage*structured_estimate.
Function Documentation
_ledoit_wolf()
sklearn.covariance._shrunk_covariance._ledoit_wolf (X, * , assume_centered, block_size) protected
Estimate the shrunk Ledoit-Wolf covariance matrix.
Definition at line 25 of file _shrunk_covariance.py.
References ledoit_wolf_shrinkage().
Referenced by sklearn.covariance._shrunk_covariance.LedoitWolf.fit().
_oas()
sklearn.covariance._shrunk_covariance._oas (X, * , assume_centered = False) protected
Estimate covariance with the Oracle Approximating Shrinkage algorithm.
The formulation is based on [1]_.
[1] "Shrinkage algorithms for MMSE covariance estimation.",
    Chen, Y., Wiesel, A., Eldar, Y. C., & Hero, A. O.
    IEEE Transactions on Signal Processing, 58(10), 5016-5029, 2010.
    https://arxiv.org/pdf/0907.4698.pdf
Definition at line 46 of file _shrunk_covariance.py.
Referenced by sklearn.covariance._shrunk_covariance.OAS.fit().
ledoit_wolf()
sklearn.covariance._shrunk_covariance.ledoit_wolf (X, * , assume_centered = False, block_size = 1000)
Estimate the shrunk Ledoit-Wolf covariance matrix.
Read more in the :ref:`User Guide <shrunk_covariance>`.
Parameters
----------
X : array-like of shape (n_samples, n_features)
    Data from which to compute the covariance estimate.
assume_centered : bool, default=False
    If True, data will not be centered before computation.
    Useful to work with data whose mean is significantly equal to
    zero but is not exactly zero.
    If False, data will be centered before computation.
block_size : int, default=1000
    Size of blocks into which the covariance matrix will be split.
    This is purely a memory optimization and does not affect results.
Returns
-------
shrunk_cov : ndarray of shape (n_features, n_features)
    Shrunk covariance.
shrinkage : float
    Coefficient in the convex combination used for the computation
    of the shrunk estimate.
Notes
-----
The regularized (shrunk) covariance is:
(1 - shrinkage) * cov + shrinkage * mu * np.identity(n_features)
where mu = trace(cov) / n_features
Examples
--------
>>> import numpy as np
>>> from sklearn.covariance import empirical_covariance, ledoit_wolf
>>> real_cov = np.array([[.4, .2], [.2, .8]])
>>> rng = np.random.RandomState(0)
>>> X = rng.multivariate_normal(mean=[0, 0], cov=real_cov, size=50)
>>> covariance, shrinkage = ledoit_wolf(X)
>>> covariance
array([[0.44, 0.16],
       [0.16, 0.80]])
>>> shrinkage
np.float64(0.23)
Definition at line 407 of file _shrunk_covariance.py.
ledoit_wolf_shrinkage()
sklearn.covariance._shrunk_covariance.ledoit_wolf_shrinkage (X, assume_centered = False, block_size = 1000)
Estimate the shrunk Ledoit-Wolf covariance matrix.
Read more in the :ref:`User Guide <shrunk_covariance>`.
Parameters
----------
X : array-like of shape (n_samples, n_features)
    Data from which to compute the Ledoit-Wolf shrunk covariance shrinkage.
assume_centered : bool, default=False
    If True, data will not be centered before computation.
    Useful to work with data whose mean is significantly equal to
    zero but is not exactly zero.
    If False, data will be centered before computation.
block_size : int, default=1000
    Size of blocks into which the covariance matrix will be split.
Returns
-------
shrinkage : float
    Coefficient in the convex combination used for the computation
    of the shrunk estimate.
Notes
-----
The regularized (shrunk) covariance is:
(1 - shrinkage) * cov + shrinkage * mu * np.identity(n_features)
where mu = trace(cov) / n_features
Examples
--------
>>> import numpy as np
>>> from sklearn.covariance import ledoit_wolf_shrinkage
>>> real_cov = np.array([[.4, .2], [.2, .8]])
>>> rng = np.random.RandomState(0)
>>> X = rng.multivariate_normal(mean=[0, 0], cov=real_cov, size=50)
>>> shrinkage_coefficient = ledoit_wolf_shrinkage(X)
>>> shrinkage_coefficient
np.float64(0.23)
Definition at line 297 of file _shrunk_covariance.py.
Referenced by _ledoit_wolf().
oas()
sklearn.covariance._shrunk_covariance.oas (X, * , assume_centered = False)
Estimate covariance with the Oracle Approximating Shrinkage.
Read more in the :ref:`User Guide <shrunk_covariance>`.
Parameters
----------
X : array-like of shape (n_samples, n_features)
    Data from which to compute the covariance estimate.
assume_centered : bool, default=False
  If True, data will not be centered before computation.
  Useful to work with data whose mean is significantly equal to
  zero but is not exactly zero.
  If False, data will be centered before computation.
Returns
-------
shrunk_cov : array-like of shape (n_features, n_features)
    Shrunk covariance.
shrinkage : float
    Coefficient in the convex combination used for the computation
    of the shrunk estimate.
Notes
-----
The regularised covariance is:
(1 - shrinkage) * cov + shrinkage * mu * np.identity(n_features),
where mu = trace(cov) / n_features and shrinkage is given by the OAS formula
(see [1]_).
The shrinkage formulation implemented here differs from Eq. 23 in [1]_. In
the original article, formula (23) states that 2/p (p being the number of
features) is multiplied by Trace(cov*cov) in both the numerator and
denominator, but this operation is omitted because for a large p, the value
of 2/p is so small that it doesn't affect the value of the estimator.
References
----------
.. [1] :arxiv:`"Shrinkage algorithms for MMSE covariance estimation.",
       Chen, Y., Wiesel, A., Eldar, Y. C., & Hero, A. O.
       IEEE Transactions on Signal Processing, 58(10), 5016-5029, 2010.
       <0907.4698>`
Examples
--------
>>> import numpy as np
>>> from sklearn.covariance import oas
>>> rng = np.random.RandomState(0)
>>> real_cov = [[.8, .3], [.3, .4]]
>>> X = rng.multivariate_normal(mean=[0, 0], cov=real_cov, size=500)
>>> shrunk_cov, shrinkage = oas(X)
>>> shrunk_cov
array([[0.7533, 0.2763],
       [0.2763, 0.3964]])
>>> shrinkage
np.float64(0.0195)
Definition at line 621 of file _shrunk_covariance.py.
shrunk_covariance()
sklearn.covariance._shrunk_covariance.shrunk_covariance (emp_cov, shrinkage = 0.1)
Public API ShrunkCovariance estimator.
Calculate covariance matrices shrunk on the diagonal.
Read more in the :ref:`User Guide <shrunk_covariance>`.
Parameters
----------
emp_cov : array-like of shape (..., n_features, n_features)
    Covariance matrices to be shrunk, at least 2D ndarray.
shrinkage : float, default=0.1
    Coefficient in the convex combination used for the computation
    of the shrunk estimate. Range is [0, 1].
Returns
-------
shrunk_cov : ndarray of shape (..., n_features, n_features)
    Shrunk covariance matrices.
Notes
-----
The regularized (shrunk) covariance is given by::
    (1 - shrinkage) * cov + shrinkage * mu * np.identity(n_features)
where `mu = trace(cov) / n_features`.
Examples
--------
>>> import numpy as np
>>> from sklearn.datasets import make_gaussian_quantiles
>>> from sklearn.covariance import empirical_covariance, shrunk_covariance
>>> real_cov = np.array([[.8, .3], [.3, .4]])
>>> rng = np.random.RandomState(0)
>>> X = rng.multivariate_normal(mean=[0, 0], cov=real_cov, size=500)
>>> shrunk_covariance(empirical_covariance(X))
array([[0.739, 0.254],
       [0.254, 0.411]])
Definition at line 109 of file _shrunk_covariance.py.
Referenced by sklearn.covariance._shrunk_covariance.ShrunkCovariance.fit().