Code Cloning Analysis: matplotlib.backends.backend_nbagg.CommSocket Class Reference
matplotlib.backends.backend_nbagg.CommSocket Class Reference
Public Member Functions
__init__ (self, manager)
is_open (self)
on_close (self)
send_json (self, content)
send_binary (self, blob)
on_message (self, message)
Public Attributes
supports_binary = None
manager = manager
uuid = str(uuid.uuid4())
comm = Comm('matplotlib', data={'id': self.uuid})
on_message
Protected Attributes
bool _ext_close = False
Detailed Description
Manages the Comm connection between IPython and the browser (client).
Comms are 2 way, with the CommSocket being able to publish a message
via the send_json method, and handle a message with on_message. On the
JS side figure.send_message and figure.ws.onmessage do the sending and
receiving respectively.
Definition at line 163 of file backend_nbagg.py.
Constructor & Destructor Documentation
__init__()
matplotlib.backends.backend_nbagg.CommSocket.__init__ (self, manager)
Definition at line 173 of file backend_nbagg.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
is_open()
matplotlib.backends.backend_nbagg.CommSocket.is_open (self)
Definition at line 198 of file backend_nbagg.py.
on_close()
matplotlib.backends.backend_nbagg.CommSocket.on_close (self)
Definition at line 201 of file backend_nbagg.py.
on_message()
matplotlib.backends.backend_nbagg.CommSocket.on_message (self, message)
Definition at line 224 of file backend_nbagg.py.
send_binary()
matplotlib.backends.backend_nbagg.CommSocket.send_binary (self, blob)
Definition at line 214 of file backend_nbagg.py.
send_json()
matplotlib.backends.backend_nbagg.CommSocket.send_json (self, content)
Definition at line 211 of file backend_nbagg.py.
Member Data Documentation
_ext_close
bool matplotlib.backends.backend_nbagg.CommSocket._ext_close = False protected
Definition at line 189 of file backend_nbagg.py.
comm
matplotlib.backends.backend_nbagg.CommSocket.comm = Comm('matplotlib', data={'id': self.uuid})
Definition at line 181 of file backend_nbagg.py.
manager
matplotlib.backends.backend_nbagg.CommSocket.manager = manager
Definition at line 175 of file backend_nbagg.py.
on_message
matplotlib.backends.backend_nbagg.CommSocket.on_message
Definition at line 186 of file backend_nbagg.py.
supports_binary
matplotlib.backends.backend_nbagg.CommSocket.supports_binary = None
Definition at line 174 of file backend_nbagg.py.
uuid
matplotlib.backends.backend_nbagg.CommSocket.uuid = str(uuid.uuid4())
Definition at line 176 of file backend_nbagg.py.
Referenced by pandas.io.formats.style_render.StylerRenderer._translate(), pandas.io.formats.style.Styler.clear(), and pandas.io.formats.style.Styler.set_uuid().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/backends/backend_nbagg.py