Code Cloning Analysis: sklearn.metrics._scorer._CurveScorer Class Reference
sklearn.metrics._scorer._CurveScorer Class Reference
Public Member Functions
__init__ (self, score_func, sign, kwargs, thresholds, response_method)
from_scorer (cls, scorer, response_method, thresholds)
Public Member Functions inherited from sklearn.metrics._scorer._BaseScorer
__init__ (self, score_func, sign, kwargs, response_method="predict")
__repr__ (self)
__call__ (self, estimator, X, y_true, sample_weight=None, **kwargs)
set_score_request (self, **kwargs)
Protected Member Functions
_score (self, method_caller, estimator, X, y_true, **kwargs)
Protected Member Functions inherited from sklearn.metrics._scorer._BaseScorer
_get_pos_label (self)
_accept_sample_weight (self)
_warn_overlap (self, message, kwargs)
Protected Attributes
_thresholds = thresholds
Protected Attributes inherited from sklearn.metrics._scorer._BaseScorer
_score_func = score_func
_sign = sign
_kwargs = kwargs
_response_method = response_method
_deprecation_msg = None
_metadata_request = MetadataRequest(owner=self.__class__.__name__)
Detailed Description
Scorer taking a continuous response and output a score for each threshold.
Parameters
----------
score_func : callable
    The score function to use. It will be called as
    `score_func(y_true, y_pred, **kwargs)`.
sign : int
    Either 1 or -1 to returns the score with `sign * score_func(estimator, X, y)`.
    Thus, `sign` defined if higher scores are better or worse.
kwargs : dict
    Additional parameters to pass to the score function.
thresholds : int or array-like
    Related to the number of decision thresholds for which we want to compute the
    score. If an integer, it will be used to generate `thresholds` thresholds
    uniformly distributed between the minimum and maximum predicted scores. If an
    array-like, it will be used as the thresholds.
response_method : str
    The method to call on the estimator to get the response values.
Definition at line 1064 of file _scorer.py.
Constructor & Destructor Documentation
__init__()
sklearn.metrics._scorer._CurveScorer.__init__ (self, score_func, sign, kwargs, thresholds, response_method)
Definition at line 1090 of file _scorer.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params().
Member Function Documentation
_score()
sklearn.metrics._scorer._CurveScorer._score (self, method_caller, estimator, X, y_true, ** kwargs) protected
Evaluate predicted target values for X relative to y_true.
Parameters
----------
method_caller : callable
    Returns predictions given an estimator, method name, and other
    arguments, potentially caching results.
estimator : object
    Trained estimator to use for scoring.
X : {array-like, sparse matrix} of shape (n_samples, n_features)
    Test data that will be fed to estimator.predict.
y_true : array-like of shape (n_samples,)
    Gold standard target values for X.
**kwargs : dict
    Other parameters passed to the scorer. Refer to
    :func:`set_score_request` for more details.
Returns
-------
scores : ndarray of shape (thresholds,)
    The scores associated to each threshold.
potential_thresholds : ndarray of shape (thresholds,)
    The potential thresholds used to compute the scores.
Definition at line 1113 of file _scorer.py.
References sklearn.metrics._scorer._BaseScorer._get_pos_label(), sklearn.metrics._scorer._BaseScorer._kwargs, sklearn.metrics._scorer._BaseScorer._response_method, sklearn.metrics._scorer._BaseScorer._score_func, sklearn.metrics._scorer._BaseScorer._sign, sklearn.metrics._scorer._threshold_scores_to_class_labels(), and _thresholds.
Referenced by sklearn.metrics._scorer._BaseScorer.__call__(), and sklearn.neural_network._multilayer_perceptron.BaseMultilayerPerceptron._backprop().
from_scorer()
sklearn.metrics._scorer._CurveScorer.from_scorer (cls, scorer, response_method, thresholds)
Create a continuous scorer from a normal scorer.
Definition at line 1100 of file _scorer.py.
Member Data Documentation
_thresholds
sklearn.metrics._scorer._CurveScorer._thresholds = thresholds protected
Definition at line 1097 of file _scorer.py.
Referenced by _score().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/sklearn/metrics/_scorer.py