Code Cloning Analysis: scipy.fft._pocketfft.helper Namespace Reference
scipy.fft._pocketfft.helper Namespace Reference
Functions
_iterable_of_int (x, name=None)
_init_nd_shape_and_axes (x, shape, axes)
_asfarray (x)
_datacopied (arr, original)
_fix_shape (x, shape, axes)
_fix_shape_1d (x, n, axis)
_normalization (norm, forward)
_workers (workers)
set_workers (workers)
get_workers ()
Variables
_config = threading.local()
_cpu_count = os.cpu_count()
dict _NORM_MAP = {None: 0, 'backward': 0, 'ortho': 1, 'forward': 2}
Function Documentation
_asfarray()
scipy.fft._pocketfft.helper._asfarray (x) protected
Convert to array with floating or complex dtype.
float16 values are also promoted to float32.
Definition at line 80 of file helper.py.
Referenced by scipy.fft._pocketfft.realtransforms._r2r(), scipy.fft._pocketfft.realtransforms._r2rn(), scipy.fft._pocketfft.basic.c2c(), scipy.fft._pocketfft.basic.c2cn(), scipy.fft._pocketfft.basic.c2r(), scipy.fft._pocketfft.basic.c2rn(), scipy.fft._pocketfft.basic.r2c(), scipy.fft._pocketfft.basic.r2cn(), and scipy.fft._pocketfft.basic.r2r_fftpack().
_datacopied()
scipy.fft._pocketfft.helper._datacopied (arr, original) protected
Strict check for `arr` not sharing any data with `original`,
under the assumption that arr = asarray(original)
Definition at line 100 of file helper.py.
Referenced by scipy.fft._pocketfft.realtransforms._r2r(), scipy.fft._pocketfft.realtransforms._r2rn(), scipy.fft._pocketfft.basic.c2c(), scipy.fft._pocketfft.basic.c2cn(), and scipy.fft._pocketfft.basic.r2r_fftpack().
_fix_shape()
scipy.fft._pocketfft.helper._fix_shape (x, shape, axes) protected
Internal auxiliary function for _raw_fft, _raw_fftnd.
Definition at line 112 of file helper.py.
References _fix_shape().
Referenced by _fix_shape(), scipy.fft._pocketfft.realtransforms._r2rn(), scipy.fft._pocketfft.basic.c2cn(), scipy.fft._pocketfft.basic.c2rn(), and scipy.fft._pocketfft.basic.r2cn().
_fix_shape_1d()
scipy.fft._pocketfft.helper._fix_shape_1d (x, n, axis) protected
Definition at line 139 of file helper.py.
_init_nd_shape_and_axes()
scipy.fft._pocketfft.helper._init_nd_shape_and_axes (x, shape, axes) protected
Handles shape and axes arguments for nd transforms
Definition at line 41 of file helper.py.
References _iterable_of_int().
Referenced by scipy.fft._pocketfft.realtransforms._r2rn(), scipy.fft._pocketfft.basic.c2cn(), scipy.fft._pocketfft.basic.c2rn(), and scipy.fft._pocketfft.basic.r2cn().
_iterable_of_int()
scipy.fft._pocketfft.helper._iterable_of_int (x, name = None) protected
Convert ``x`` to an iterable sequence of int
Parameters
----------
x : value, or sequence of values, convertible to int
name : str, optional
    Name of the argument being converted, only used in the error message
Returns
-------
y : ``List[int]``
Definition at line 15 of file helper.py.
Referenced by _init_nd_shape_and_axes().
_normalization()
scipy.fft._pocketfft.helper._normalization (norm, forward) protected
Returns the pypocketfft normalization mode from the norm argument
Definition at line 150 of file helper.py.
Referenced by scipy.fft._pocketfft.realtransforms._r2r(), scipy.fft._pocketfft.realtransforms._r2rn(), scipy.fft._pocketfft.basic.c2c(), scipy.fft._pocketfft.basic.c2cn(), scipy.fft._pocketfft.basic.c2r(), scipy.fft._pocketfft.basic.c2rn(), scipy.fft._pocketfft.basic.r2c(), scipy.fft._pocketfft.basic.r2cn(), and scipy.fft._pocketfft.basic.r2r_fftpack().
_workers()
scipy.fft._pocketfft.helper._workers (workers) protected
Definition at line 161 of file helper.py.
get_workers()
scipy.fft._pocketfft.helper.get_workers ()
Returns the default number of workers within the current context
Examples
--------
>>> from scipy import fft
>>> fft.get_workers()
1
>>> with fft.set_workers(4):
...     fft.get_workers()
4
Definition at line 204 of file helper.py.
Referenced by set_workers().
set_workers()
scipy.fft._pocketfft.helper.set_workers (workers)
Context manager for the default number of workers used in `scipy.fft`
Parameters
----------
workers : int
    The default number of workers to use
Examples
--------
>>> import numpy as np
>>> from scipy import fft, signal
>>> rng = np.random.default_rng()
>>> x = rng.standard_normal((128, 64))
>>> with fft.set_workers(4):
...     y = signal.fftconvolve(x, x)
Definition at line 178 of file helper.py.
References get_workers().
Variable Documentation
_config
scipy.fft._pocketfft.helper._config = threading.local() protected
Definition at line 11 of file helper.py.
_cpu_count
scipy.fft._pocketfft.helper._cpu_count = os.cpu_count() protected
Definition at line 12 of file helper.py.
_NORM_MAP
dict scipy.fft._pocketfft.helper._NORM_MAP = {None: 0, 'backward': 0, 'ortho': 1, 'forward': 2} protected
Definition at line 147 of file helper.py.