Code Cloning Analysis: fontTools.ttLib.tables.otTables.AATState Class Reference
fontTools.ttLib.tables.otTables.AATState Class Reference
Public Member Functions
__init__ (self)
Public Attributes
dict Transitions = {}
Detailed Description
Definition at line 445 of file otTables.py.
Constructor & Destructor Documentation
__init__()
fontTools.ttLib.tables.otTables.AATState.__init__ (self)
Definition at line 446 of file otTables.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Data Documentation
Transitions
dict fontTools.ttLib.tables.otTables.AATState.Transitions = {}
Definition at line 447 of file otTables.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ttLib/tables/otTables.py