Code Cloning Analysis: fontTools.ufoLib Namespace Reference
fontTools.ufoLib Namespace Reference
Namespaces
namespace converters
namespace etree
namespace filenames
namespace glifLib
namespace plistlib
namespace pointPen
namespace utils
namespace validators
Classes
class _UFOBaseIO
class UFOFileStructure
class UFOFormatVersion
class UFOReader
class UFOWriter
Functions
_sniffFileStructure (ufo_path)
makeUFOPath (path)
validateFontInfoVersion2ValueForAttribute (attr, value)
validateInfoVersion2Data (infoData)
validateFontInfoVersion3ValueForAttribute (attr, value)
validateInfoVersion3Data (infoData)
_flipDict (d)
convertFontInfoValueForAttributeFromVersion1ToVersion2 (attr, value)
convertFontInfoValueForAttributeFromVersion2ToVersion1 (attr, value)
_convertFontInfoDataVersion1ToVersion2 (data)
_convertFontInfoDataVersion2ToVersion1 (data)
convertFontInfoValueForAttributeFromVersion2ToVersion3 (attr, value)
convertFontInfoValueForAttributeFromVersion3ToVersion2 (attr, value)
_convertFontInfoDataVersion3ToVersion2 (data)
_convertFontInfoDataVersion2ToVersion3 (data)
Variables
haveFS = fs._haveFS
list __all__
str __version__ = "3.0.0"
logger = logging.getLogger(__name__)
str DEFAULT_GLYPHS_DIRNAME = "glyphs"
str DATA_DIRNAME = "data"
str IMAGES_DIRNAME = "images"
str METAINFO_FILENAME = "metainfo.plist"
str FONTINFO_FILENAME = "fontinfo.plist"
str LIB_FILENAME = "lib.plist"
str GROUPS_FILENAME = "groups.plist"
str KERNING_FILENAME = "kerning.plist"
str FEATURES_FILENAME = "features.fea"
str LAYERCONTENTS_FILENAME = "layercontents.plist"
str LAYERINFO_FILENAME = "layerinfo.plist"
str DEFAULT_LAYER_NAME = "public.default"
UFOReaderWriter = UFOWriter
fontInfoOpenTypeHeadFlagsOptions = list(range(0, 15))
list fontInfoOpenTypeOS2SelectionOptions = [1, 2, 3, 4, 7, 8, 9]
fontInfoOpenTypeOS2UnicodeRangesOptions = list(range(0, 128))
fontInfoOpenTypeOS2CodePageRangesOptions = list(range(0, 64))
list fontInfoOpenTypeOS2TypeOptions = [0, 1, 2, 3, 8, 9]
dict fontInfoAttributesVersion1
dict fontInfoAttributesVersion2ValueData
fontInfoAttributesVersion2 = set(fontInfoAttributesVersion2ValueData.keys())
fontInfoAttributesVersion3ValueData = deepcopy(fontInfoAttributesVersion2ValueData)
fontInfoAttributesVersion3 = set(fontInfoAttributesVersion3ValueData.keys())
dict fontInfoAttributesVersion1To2
fontInfoAttributesVersion2To1 = _flipDict(fontInfoAttributesVersion1To2)
deprecatedFontInfoAttributesVersion2 = set(fontInfoAttributesVersion1To2.keys())
dict _fontStyle1To2 = {64: "regular", 1: "italic", 32: "bold", 33: "bold italic"}
_fontStyle2To1 = _flipDict(_fontStyle1To2)
dict _widthName1To2
_widthName2To1 = _flipDict(_widthName1To2)
dict _msCharSet1To2
_msCharSet2To1 = _flipDict(_msCharSet1To2)
dict _ufo2To3NonNegativeInt
dict _ufo2To3NonNegativeIntOrFloat
dict _ufo2To3FloatToInt
Detailed Description
A library for importing .ufo files and their descendants.
Refer to http://unifiedfontobject.org for the UFO specification.
The main interfaces are the :class:`.UFOReader` and :class:`.UFOWriter`
classes, which support versions 1, 2, and 3 of the UFO specification.
Set variables are available for external use that list the font
info attribute names for the `fontinfo.plist` formats. These are:
- :obj:`.fontInfoAttributesVersion1`
- :obj:`.fontInfoAttributesVersion2`
- :obj:`.fontInfoAttributesVersion3`
A set listing the `fontinfo.plist` attributes that were deprecated
in version 2 is available for external use:
- :obj:`.deprecatedFontInfoAttributesVersion2`
Functions that do basic validation on values for `fontinfo.plist`
are available for external use. These are
- :func:`.validateFontInfoVersion2ValueForAttribute`
- :func:`.validateFontInfoVersion3ValueForAttribute`
Value conversion functions are available for converting
`fontinfo.plist` values between the possible format versions.
- :func:`.convertFontInfoValueForAttributeFromVersion1ToVersion2`
- :func:`.convertFontInfoValueForAttributeFromVersion2ToVersion1`
- :func:`.convertFontInfoValueForAttributeFromVersion2ToVersion3`
- :func:`.convertFontInfoValueForAttributeFromVersion3ToVersion2`
Function Documentation
_convertFontInfoDataVersion1ToVersion2()
fontTools.ufoLib._convertFontInfoDataVersion1ToVersion2 (data) protected
Definition at line 2328 of file __init__.py.
_convertFontInfoDataVersion2ToVersion1()
fontTools.ufoLib._convertFontInfoDataVersion2ToVersion1 (data) protected
Definition at line 2352 of file __init__.py.
_convertFontInfoDataVersion2ToVersion3()
fontTools.ufoLib._convertFontInfoDataVersion2ToVersion3 (data) protected
Definition at line 2459 of file __init__.py.
_convertFontInfoDataVersion3ToVersion2()
fontTools.ufoLib._convertFontInfoDataVersion3ToVersion2 (data) protected
Definition at line 2447 of file __init__.py.
_flipDict()
fontTools.ufoLib._flipDict (d) protected
Definition at line 2181 of file __init__.py.
_sniffFileStructure()
fontTools.ufoLib._sniffFileStructure (ufo_path) protected
Return UFOFileStructure.ZIP if the UFO at path 'ufo_path' (str)
is a zip file, else return UFOFileStructure.PACKAGE if 'ufo_path' is a
directory.
Raise UFOLibError if it is a file with unknown structure, or if the path
does not exist.
Definition at line 1743 of file __init__.py.
convertFontInfoValueForAttributeFromVersion1ToVersion2()
fontTools.ufoLib.convertFontInfoValueForAttributeFromVersion1ToVersion2 (attr, value)
Convert value from version 1 to version 2 format.
Returns the new attribute name and the converted value.
If the value is None, None will be returned for the new value.
Definition at line 2275 of file __init__.py.
Referenced by convertFontInfoValueForAttributeFromVersion2ToVersion1().
convertFontInfoValueForAttributeFromVersion2ToVersion1()
fontTools.ufoLib.convertFontInfoValueForAttributeFromVersion2ToVersion1 (attr, value)
Convert value from version 2 to version 1 format.
Returns the new attribute name and the converted value.
If the value is None, None will be returned for the new value.
Definition at line 2311 of file __init__.py.
References convertFontInfoValueForAttributeFromVersion1ToVersion2(), and convertFontInfoValueForAttributeFromVersion2ToVersion1().
Referenced by convertFontInfoValueForAttributeFromVersion2ToVersion1().
convertFontInfoValueForAttributeFromVersion2ToVersion3()
fontTools.ufoLib.convertFontInfoValueForAttributeFromVersion2ToVersion3 (attr, value)
Convert value from version 2 to version 3 format.
Returns the new attribute name and the converted value.
If the value is None, None will be returned for the new value.
Definition at line 2410 of file __init__.py.
Referenced by convertFontInfoValueForAttributeFromVersion3ToVersion2().
convertFontInfoValueForAttributeFromVersion3ToVersion2()
fontTools.ufoLib.convertFontInfoValueForAttributeFromVersion3ToVersion2 (attr, value)
Convert value from version 3 to version 2 format.
Returns the new attribute name and the converted value.
If the value is None, None will be returned for the new value.
Definition at line 2438 of file __init__.py.
References convertFontInfoValueForAttributeFromVersion2ToVersion3(), and convertFontInfoValueForAttributeFromVersion3ToVersion2().
Referenced by convertFontInfoValueForAttributeFromVersion3ToVersion2().
makeUFOPath()
fontTools.ufoLib.makeUFOPath (path)
Return a .ufo pathname.
>>> makeUFOPath("directory/something.ext") == (
...     os.path.join('directory', 'something.ufo'))
True
>>> makeUFOPath("directory/something.another.thing.ext") == (
...     os.path.join('directory', 'something.another.thing.ufo'))
True
Definition at line 1762 of file __init__.py.
validateFontInfoVersion2ValueForAttribute()
fontTools.ufoLib.validateFontInfoVersion2ValueForAttribute (attr, value)
This performs very basic validation of the value for attribute
following the UFO 2 fontinfo.plist specification. The results
of this should not be interpretted as *correct* for the font
that they are part of. This merely indicates that the value
is of the proper type and, where the specification defines
a set range of possible values for an attribute, that the
value is in the accepted range.
Definition at line 1789 of file __init__.py.
Referenced by validateInfoVersion2Data().
validateFontInfoVersion3ValueForAttribute()
fontTools.ufoLib.validateFontInfoVersion3ValueForAttribute (attr, value)
This performs very basic validation of the value for attribute
following the UFO 3 fontinfo.plist specification. The results
of this should not be interpretted as *correct* for the font
that they are part of. This merely indicates that the value
is of the proper type and, where the specification defines
a set range of possible values for an attribute, that the
value is in the accepted range.
Definition at line 1835 of file __init__.py.
Referenced by validateInfoVersion3Data().
validateInfoVersion2Data()
fontTools.ufoLib.validateInfoVersion2Data (infoData)
This performs very basic validation of the value for infoData
following the UFO 2 fontinfo.plist specification. The results
of this should not be interpretted as *correct* for the font
that they are part of. This merely indicates that the values
are of the proper type and, where the specification defines
a set range of possible values for an attribute, that the
value is in the accepted range.
Definition at line 1815 of file __init__.py.
References validateFontInfoVersion2ValueForAttribute().
Referenced by fontTools.ufoLib.UFOWriter.writeInfo().
validateInfoVersion3Data()
fontTools.ufoLib.validateInfoVersion3Data (infoData)
This performs very basic validation of the value for infoData
following the UFO 3 fontinfo.plist specification. The results
of this should not be interpretted as *correct* for the font
that they are part of. This merely indicates that the values
are of the proper type and, where the specification defines
a set range of possible values for an attribute, that the
value is in the accepted range.
Definition at line 1861 of file __init__.py.
References validateFontInfoVersion3ValueForAttribute().
Referenced by fontTools.ufoLib.UFOReader.readInfo(), and fontTools.ufoLib.UFOWriter.writeInfo().
Variable Documentation
__all__
list fontTools.ufoLib.__all__ private
Initial value:
=  [
    "haveFS",
    "makeUFOPath",
    "UFOLibError",
    "UFOReader",
    "UFOWriter",
    "UFOReaderWriter",
    "UFOFileStructure",
    "fontInfoAttributesVersion1",
    "fontInfoAttributesVersion2",
    "fontInfoAttributesVersion3",
    "deprecatedFontInfoAttributesVersion2",
    "validateFontInfoVersion2ValueForAttribute",
    "validateFontInfoVersion3ValueForAttribute",
    "convertFontInfoValueForAttributeFromVersion1ToVersion2",
    "convertFontInfoValueForAttributeFromVersion2ToVersion1",
]
Definition at line 54 of file __init__.py.
__version__
str fontTools.ufoLib.__version__ = "3.0.0" private
Definition at line 72 of file __init__.py.
_fontStyle1To2
dict fontTools.ufoLib._fontStyle1To2 = {64: "regular", 1: "italic", 32: "bold", 33: "bold italic"} protected
Definition at line 2220 of file __init__.py.
_fontStyle2To1
fontTools.ufoLib._fontStyle2To1 = _flipDict(_fontStyle1To2) protected
Definition at line 2221 of file __init__.py.
_msCharSet1To2
dict fontTools.ufoLib._msCharSet1To2 protected
Initial value:
=  {
    0: 1,
    1: 2,
    2: 3,
    77: 4,
    128: 5,
    129: 6,
    130: 7,
    134: 8,
    136: 9,
    161: 10,
    162: 11,
    163: 12,
    177: 13,
    178: 14,
    186: 15,
    200: 16,
    204: 17,
    222: 18,
    238: 19,
    255: 20,
}
Definition at line 2248 of file __init__.py.
_msCharSet2To1
fontTools.ufoLib._msCharSet2To1 = _flipDict(_msCharSet1To2) protected
Definition at line 2270 of file __init__.py.
_ufo2To3FloatToInt
dict fontTools.ufoLib._ufo2To3FloatToInt protected
Initial value:
=  {
    "openTypeHeadLowestRecPPEM",
    "openTypeHheaAscender",
    "openTypeHheaDescender",
    "openTypeHheaLineGap",
    "openTypeHheaCaretOffset",
    "openTypeOS2TypoAscender",
    "openTypeOS2TypoDescender",
    "openTypeOS2TypoLineGap",
    "openTypeOS2WinAscent",
    "openTypeOS2WinDescent",
    "openTypeOS2SubscriptXSize",
    "openTypeOS2SubscriptYSize",
    "openTypeOS2SubscriptXOffset",
    "openTypeOS2SubscriptYOffset",
    "openTypeOS2SuperscriptXSize",
    "openTypeOS2SuperscriptYSize",
    "openTypeOS2SuperscriptXOffset",
    "openTypeOS2SuperscriptYOffset",
    "openTypeOS2StrikeoutSize",
    "openTypeOS2StrikeoutPosition",
    "openTypeVheaVertTypoAscender",
    "openTypeVheaVertTypoDescender",
    "openTypeVheaVertTypoLineGap",
    "openTypeVheaCaretOffset",
}
Definition at line 2382 of file __init__.py.
_ufo2To3NonNegativeInt
dict fontTools.ufoLib._ufo2To3NonNegativeInt protected
Initial value:
=  {
    "versionMinor",
    "openTypeHeadLowestRecPPEM",
    "openTypeOS2WinAscent",
    "openTypeOS2WinDescent",
}
Definition at line 2373 of file __init__.py.
_ufo2To3NonNegativeIntOrFloat
dict fontTools.ufoLib._ufo2To3NonNegativeIntOrFloat protected
Initial value:
=  {
    "unitsPerEm",
}
Definition at line 2379 of file __init__.py.
_widthName1To2
dict fontTools.ufoLib._widthName1To2 protected
Initial value:
=  {
    "Ultra-condensed": 1,
    "Extra-condensed": 2,
    "Condensed": 3,
    "Semi-condensed": 4,
    "Medium (normal)": 5,
    "Semi-expanded": 6,
    "Expanded": 7,
    "Extra-expanded": 8,
    "Ultra-expanded": 9,
}
Definition at line 2225 of file __init__.py.
_widthName2To1
fontTools.ufoLib._widthName2To1 = _flipDict(_widthName1To2) protected
Definition at line 2236 of file __init__.py.
DATA_DIRNAME
str fontTools.ufoLib.DATA_DIRNAME = "data"
Definition at line 83 of file __init__.py.
DEFAULT_GLYPHS_DIRNAME
str fontTools.ufoLib.DEFAULT_GLYPHS_DIRNAME = "glyphs"
Definition at line 82 of file __init__.py.
DEFAULT_LAYER_NAME
str fontTools.ufoLib.DEFAULT_LAYER_NAME = "public.default"
Definition at line 94 of file __init__.py.
deprecatedFontInfoAttributesVersion2
fontTools.ufoLib.deprecatedFontInfoAttributesVersion2 = set(fontInfoAttributesVersion1To2.keys())
Definition at line 2218 of file __init__.py.
FEATURES_FILENAME
str fontTools.ufoLib.FEATURES_FILENAME = "features.fea"
Definition at line 90 of file __init__.py.
FONTINFO_FILENAME
str fontTools.ufoLib.FONTINFO_FILENAME = "fontinfo.plist"
Definition at line 86 of file __init__.py.
fontInfoAttributesVersion1
dict fontTools.ufoLib.fontInfoAttributesVersion1
Definition at line 1894 of file __init__.py.
fontInfoAttributesVersion1To2
dict fontTools.ufoLib.fontInfoAttributesVersion1To2
Initial value:
=  {
    "menuName": "styleMapFamilyName",
    "designer": "openTypeNameDesigner",
    "designerURL": "openTypeNameDesignerURL",
    "createdBy": "openTypeNameManufacturer",
    "vendorURL": "openTypeNameManufacturerURL",
    "license": "openTypeNameLicense",
    "licenseURL": "openTypeNameLicenseURL",
    "ttVersion": "openTypeNameVersion",
    "ttUniqueID": "openTypeNameUniqueID",
    "notice": "openTypeNameDescription",
    "otFamilyName": "openTypeNamePreferredFamilyName",
    "otStyleName": "openTypeNamePreferredSubfamilyName",
    "otMacName": "openTypeNameCompatibleFullName",
    "weightName": "postscriptWeightName",
    "weightValue": "openTypeOS2WeightClass",
    "ttVendor": "openTypeOS2VendorID",
    "uniqueID": "postscriptUniqueID",
    "fontName": "postscriptFontName",
    "fondID": "macintoshFONDFamilyID",
    "fondName": "macintoshFONDName",
    "defaultWidth": "postscriptDefaultWidthX",
    "slantAngle": "postscriptSlantAngle",
    "fullName": "postscriptFullName",
    # require special value conversion
    "fontStyle": "styleMapStyleName",
    "widthName": "openTypeOS2WidthClass",
    "msCharSet": "postscriptWindowsCharacterSet",
}
Definition at line 2188 of file __init__.py.
fontInfoAttributesVersion2
fontTools.ufoLib.fontInfoAttributesVersion2 = set(fontInfoAttributesVersion2ValueData.keys())
Definition at line 2079 of file __init__.py.
fontInfoAttributesVersion2To1
fontTools.ufoLib.fontInfoAttributesVersion2To1 = _flipDict(fontInfoAttributesVersion1To2)
Definition at line 2217 of file __init__.py.
fontInfoAttributesVersion2ValueData
dict fontTools.ufoLib.fontInfoAttributesVersion2ValueData
Definition at line 1937 of file __init__.py.
fontInfoAttributesVersion3
fontTools.ufoLib.fontInfoAttributesVersion3 = set(fontInfoAttributesVersion3ValueData.keys())
Definition at line 2164 of file __init__.py.
fontInfoAttributesVersion3ValueData
fontTools.ufoLib.fontInfoAttributesVersion3ValueData = deepcopy(fontInfoAttributesVersion2ValueData)
Definition at line 2081 of file __init__.py.
fontInfoOpenTypeHeadFlagsOptions
fontTools.ufoLib.fontInfoOpenTypeHeadFlagsOptions = list(range(0, 15))
Definition at line 1883 of file __init__.py.
fontInfoOpenTypeOS2CodePageRangesOptions
fontTools.ufoLib.fontInfoOpenTypeOS2CodePageRangesOptions = list(range(0, 64))
Definition at line 1886 of file __init__.py.
fontInfoOpenTypeOS2SelectionOptions
list fontTools.ufoLib.fontInfoOpenTypeOS2SelectionOptions = [1, 2, 3, 4, 7, 8, 9]
Definition at line 1884 of file __init__.py.
fontInfoOpenTypeOS2TypeOptions
list fontTools.ufoLib.fontInfoOpenTypeOS2TypeOptions = [0, 1, 2, 3, 8, 9]
Definition at line 1887 of file __init__.py.
fontInfoOpenTypeOS2UnicodeRangesOptions
fontTools.ufoLib.fontInfoOpenTypeOS2UnicodeRangesOptions = list(range(0, 128))
Definition at line 1885 of file __init__.py.
GROUPS_FILENAME
str fontTools.ufoLib.GROUPS_FILENAME = "groups.plist"
Definition at line 88 of file __init__.py.
haveFS
fontTools.ufoLib.haveFS = fs._haveFS
Definition at line 52 of file __init__.py.
IMAGES_DIRNAME
str fontTools.ufoLib.IMAGES_DIRNAME = "images"
Definition at line 84 of file __init__.py.
KERNING_FILENAME
str fontTools.ufoLib.KERNING_FILENAME = "kerning.plist"
Definition at line 89 of file __init__.py.
LAYERCONTENTS_FILENAME
str fontTools.ufoLib.LAYERCONTENTS_FILENAME = "layercontents.plist"
Definition at line 91 of file __init__.py.
LAYERINFO_FILENAME
str fontTools.ufoLib.LAYERINFO_FILENAME = "layerinfo.plist"
Definition at line 92 of file __init__.py.
LIB_FILENAME
str fontTools.ufoLib.LIB_FILENAME = "lib.plist"
Definition at line 87 of file __init__.py.
logger
fontTools.ufoLib.logger = logging.getLogger(__name__)
Definition at line 75 of file __init__.py.
METAINFO_FILENAME
str fontTools.ufoLib.METAINFO_FILENAME = "metainfo.plist"
Definition at line 85 of file __init__.py.
UFOReaderWriter
fontTools.ufoLib.UFOReaderWriter = UFOWriter
Definition at line 1735 of file __init__.py.