Code Cloning Analysis: fontTools.pens.qu2cuPen.Qu2CuPen Class Reference
fontTools.pens.qu2cuPen.Qu2CuPen Class Reference
Public Member Functions
__init__ (self, other_pen, max_err, all_cubic=False, reverse_direction=False, stats=None)
filterContour (self, contour)
Public Member Functions inherited from fontTools.pens.filterPen.ContourFilterPen
__init__ (self, outPen)
closePath (self)
endPath (self)
Public Member Functions inherited from fontTools.pens.filterPen._PassThruComponentsMixin
addComponent (self, glyphName, transformation, **kwargs)
Public Member Functions inherited from fontTools.pens.recordingPen.RecordingPen
__init__ (self)
moveTo (self, p0)
lineTo (self, p1)
qCurveTo (self, *points)
curveTo (self, *points)
addComponent (self, glyphName, transformation)
addVarComponent (self, glyphName, transformation, location)
replay (self, pen)
Public Attributes
all_cubic = all_cubic
max_err = max_err
stats = stats
Public Attributes inherited from fontTools.pens.recordingPen.RecordingPen
list value = []
Protected Member Functions
_quadratics_to_curve (self, q)
Protected Member Functions inherited from fontTools.pens.filterPen.ContourFilterPen
_flushContour (self)
Additional Inherited Members
Static Public Attributes inherited from fontTools.pens.recordingPen.RecordingPen
draw = replay
Protected Attributes inherited from fontTools.pens.filterPen.ContourFilterPen
_outPen = outPen
Detailed Description
A filter pen to convert quadratic bezier splines to cubic curves
using the FontTools SegmentPen protocol.
Args:
    other_pen: another SegmentPen used to draw the transformed outline.
    max_err: maximum approximation error in font units. For optimal results,
        if you know the UPEM of the font, we recommend setting this to a
        value equal, or close to UPEM / 1000.
    reverse_direction: flip the contours' direction but keep starting point.
    stats: a dictionary counting the point numbers of cubic segments.
Definition at line 22 of file qu2cuPen.py.
Constructor & Destructor Documentation
__init__()
fontTools.pens.qu2cuPen.Qu2CuPen.__init__ (self, other_pen, max_err, all_cubic = False, reverse_direction = False, stats = None)
Definition at line 36 of file qu2cuPen.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_quadratics_to_curve()
fontTools.pens.qu2cuPen.Qu2CuPen._quadratics_to_curve (self, q) protected
Definition at line 51 of file qu2cuPen.py.
Referenced by filterContour().
filterContour()
fontTools.pens.qu2cuPen.Qu2CuPen.filterContour (self, contour)
Subclasses must override this to perform the filtering.
The contour is a list of pen (operator, operands) tuples.
Operators are strings corresponding to the AbstractPen methods:
"moveTo", "lineTo", "curveTo", "qCurveTo", "closePath" and
"endPath". The operands are the positional arguments that are
passed to each method.
If the method doesn't return a value (i.e. returns None), it's
assumed that the argument was modified in-place.
Otherwise, the return value is drawn with the output pen.
Reimplemented from fontTools.pens.filterPen.ContourFilterPen.
Definition at line 63 of file qu2cuPen.py.
References _quadratics_to_curve(), and all_cubic.
Member Data Documentation
all_cubic
fontTools.pens.qu2cuPen.Qu2CuPen.all_cubic = all_cubic
Definition at line 47 of file qu2cuPen.py.
Referenced by filterContour().
max_err
fontTools.pens.qu2cuPen.Qu2CuPen.max_err = max_err
Definition at line 48 of file qu2cuPen.py.
stats
fontTools.pens.qu2cuPen.Qu2CuPen.stats = stats
Definition at line 49 of file qu2cuPen.py.
Referenced by scipy.stats._distn_infrastructure.rv_continuous.fit_loc_scale(), scipy.stats._distn_infrastructure.rv_generic.mean(), scipy.stats._distn_infrastructure.rv_generic.std(), and scipy.stats._distn_infrastructure.rv_generic.var().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/pens/qu2cuPen.py