Code Cloning Analysis: codestral Namespace Reference
codestral Namespace Reference
Functions
truncate_code (code, max_lines=50)
Truncates code to a limited number of lines for prompt fitting.
ensemble_assessment (code1, code2, model_name, n=3)
Performs multiple assessments and aggregates predictions using voting.
determine_similarity (results)
Determines the predicted type and binary similarity from score dictionary.
rag_similarity_assessment (code1, code2, model_name)
Sends a prompt to the LLM to classify clone type and score similarities.
Variables
str DATA_DIR = "./Project_CodeNet_experimentation_dataset/data"
str PAIRS_CSV = "./Project_CodeNet_experimentation_dataset/pairs.csv"
str GROUND_TRUTH_CSV = "./Project_CodeNet_experimentation_dataset/ground_truth.csv"
str OUTPUT_DIR = "./"
list LLMS
List of model names to use for clone detection.
pairs_df = pd.read_csv(PAIRS_CSV)
ground_truth_df = pd.read_csv(GROUND_TRUTH_CSV)
ground_truth_map = dict(zip(ground_truth_df['pair-id'], ground_truth_df['similar']))
int iteration = 1
Executes evaluation over prompts and saves results and metrics.
list all_truth = []
list all_preds = []
str output = f"{OUTPUT_DIR}/RAG_vs_CodeNet_binary_results_mistral_codestral22b_iteration_{iteration}.csv"
newline
writer = csv.writer(outfile)
file1_path = os.path.join(DATA_DIR, row['file1'])
file2_path = os.path.join(DATA_DIR, row['file2'])
pair_id = row['pair-id']
encoding
errors
code1 = truncate_code(f1.read())
code2 = truncate_code(f2.read())
ground_truth_sim = ground_truth_map.get(pair_id, "Unknown")
results
predicted_type
predicted_sim
model_name
n
acc = accuracy_score(all_truth, all_preds)
Calculate and write evaluation metrics for the threshold.
prec = precision_score(all_truth, all_preds)
rec = recall_score(all_truth, all_preds)
f1 = f1_score(all_truth, all_preds)
mse = mean_squared_error(all_truth, all_preds)
file
Function Documentation
determine_similarity()
codestral.determine_similarity (results)
Determines the predicted type and binary similarity from score dictionary.
Parameters
results Dictionary mapping clone types to similarity scores.
Returns
Tuple of (predicted type, binary similarity: 1 if above threshold, else 0).
Definition at line 69 of file codestral.py.
Referenced by rag_similarity_assessment().
ensemble_assessment()
codestral.ensemble_assessment (code1, code2, model_name, n = 3)
Performs multiple assessments and aggregates predictions using voting.
Parameters
code1 First code string.
code2 Second code string.
model_name The name of the LLM model to use.
thr Threshold for similarity.
n Number of repeated assessments for ensemble.
Returns
Tuple of (average type scores, majority predicted type, majority binary similarity).
Definition at line 44 of file codestral.py.
References rag_similarity_assessment().
rag_similarity_assessment()
codestral.rag_similarity_assessment (code1, code2, model_name)
Sends a prompt to the LLM to classify clone type and score similarities.
Parameters
code1 First code snippet to evaluate.
code2 Second code snippet to evaluate.
model_name Name of the language model to query.
thr Threshold for determining clone similarity.
Returns
Tuple of (type score dictionary, predicted type, binary similarity).
Definition at line 80 of file codestral.py.
References determine_similarity().
Referenced by ensemble_assessment().
truncate_code()
codestral.truncate_code (code, max_lines = 50)
Truncates code to a limited number of lines for prompt fitting.
Parameters
code Full code string.
max_lines Maximum number of lines to retain.
Returns
Truncated code string.
Definition at line 34 of file codestral.py.
Variable Documentation
acc
codestral.acc = accuracy_score(all_truth, all_preds)
Calculate and write evaluation metrics for the threshold.
Definition at line 177 of file codestral.py.
all_preds
list codestral.all_preds = []
Definition at line 139 of file codestral.py.
all_truth
list codestral.all_truth = []
Definition at line 138 of file codestral.py.
code1
codestral.code1 = truncate_code(f1.read())
Definition at line 154 of file codestral.py.
code2
codestral.code2 = truncate_code(f2.read())
Definition at line 155 of file codestral.py.
DATA_DIR
str codestral.DATA_DIR = "./Project_CodeNet_experimentation_dataset/data"
Definition at line 17 of file codestral.py.
encoding
codestral.encoding
Definition at line 152 of file codestral.py.
errors
codestral.errors
Definition at line 152 of file codestral.py.
f1
codestral.f1 = f1_score(all_truth, all_preds)
Definition at line 180 of file codestral.py.
file
codestral.file
Definition at line 185 of file codestral.py.
file1_path
codestral.file1_path = os.path.join(DATA_DIR, row['file1'])
Definition at line 148 of file codestral.py.
file2_path
codestral.file2_path = os.path.join(DATA_DIR, row['file2'])
Definition at line 149 of file codestral.py.
GROUND_TRUTH_CSV
str codestral.GROUND_TRUTH_CSV = "./Project_CodeNet_experimentation_dataset/ground_truth.csv"
Definition at line 19 of file codestral.py.
ground_truth_df
codestral.ground_truth_df = pd.read_csv(GROUND_TRUTH_CSV)
Definition at line 30 of file codestral.py.
ground_truth_map
codestral.ground_truth_map = dict(zip(ground_truth_df['pair-id'], ground_truth_df['similar']))
Definition at line 31 of file codestral.py.
ground_truth_sim
codestral.ground_truth_sim = ground_truth_map.get(pair_id, "Unknown")
Definition at line 160 of file codestral.py.
iteration
int codestral.iteration = 1
Executes evaluation over prompts and saves results and metrics.
This is the number of times you want to run the testing.
Definition at line 137 of file codestral.py.
LLMS
list codestral.LLMS
Initial value:
=  [
    "mistralai/codestral-22b-v0.1"
]
List of model names to use for clone detection.
Definition at line 24 of file codestral.py.
model_name
codestral.model_name
Definition at line 165 of file codestral.py.
mse
codestral.mse = mean_squared_error(all_truth, all_preds)
Definition at line 181 of file codestral.py.
n
codestral.n
Definition at line 165 of file codestral.py.
newline
codestral.newline
Definition at line 141 of file codestral.py.
output
str codestral.output = f"{OUTPUT_DIR}/RAG_vs_CodeNet_binary_results_mistral_codestral22b_iteration_{iteration}.csv"
Definition at line 140 of file codestral.py.
OUTPUT_DIR
str codestral.OUTPUT_DIR = "./"
Definition at line 20 of file codestral.py.
pair_id
codestral.pair_id = row['pair-id']
Definition at line 150 of file codestral.py.
PAIRS_CSV
str codestral.PAIRS_CSV = "./Project_CodeNet_experimentation_dataset/pairs.csv"
Definition at line 18 of file codestral.py.
pairs_df
codestral.pairs_df = pd.read_csv(PAIRS_CSV)
Definition at line 29 of file codestral.py.
prec
codestral.prec = precision_score(all_truth, all_preds)
Definition at line 178 of file codestral.py.
predicted_sim
codestral.predicted_sim
Definition at line 165 of file codestral.py.
predicted_type
codestral.predicted_type
Definition at line 165 of file codestral.py.
rec
codestral.rec = recall_score(all_truth, all_preds)
Definition at line 179 of file codestral.py.
results
codestral.results
Definition at line 165 of file codestral.py.
writer
codestral.writer = csv.writer(outfile)
Definition at line 142 of file codestral.py.