Code Cloning Analysis: fontTools.cffLib.CharStrings Class Reference
fontTools.cffLib.CharStrings Class Reference
Public Member Functions
__init__ (self, file, charset, globalSubrs, private, fdSelect, fdArray, isCFF2=None, varStore=None)
keys (self)
values (self)
has_key (self, name)
__len__ (self)
__getitem__ (self, name)
__setitem__ (self, name, charString)
getItemAndSelector (self, name)
toXML (self, xmlWriter)
fromXML (self, name, attrs, content)
Public Attributes
globalSubrs = globalSubrs
varStore = varStore
charStringsIndex
dict charStrings = {}
int charStringsAreIndexed = 1
private = private
fdSelect = fdSelect
fdArray = fdArray
Static Private Attributes
__contains__ = has_key
Detailed Description
The ``CharStrings`` in the font represent the instructions for drawing
each glyph. This object presents a dictionary interface to the font's
CharStrings, indexed by glyph name:
.. code:: python
        tt["CFF "].cff[0].CharStrings["a"]
        # <T2CharString (bytecode) at 103451e90>
See :class:`fontTools.misc.psCharStrings.T1CharString` and
:class:`fontTools.misc.psCharStrings.T2CharString` for how to decompile,
compile and interpret the glyph drawing instructions in the returned objects.
Definition at line 977 of file __init__.py.
Constructor & Destructor Documentation
__init__()
fontTools.cffLib.CharStrings.__init__ (self, file, charset, globalSubrs, private, fdSelect, fdArray, isCFF2 = None, varStore = None)
Definition at line 993 of file __init__.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__getitem__()
fontTools.cffLib.CharStrings.__getitem__ (self, name)
Definition at line 1043 of file __init__.py.
__len__()
fontTools.cffLib.CharStrings.__len__ (self)
Definition at line 1040 of file __init__.py.
__setitem__()
fontTools.cffLib.CharStrings.__setitem__ (self, name, charString)
Definition at line 1049 of file __init__.py.
fromXML()
fontTools.cffLib.CharStrings.fromXML (self, name, attrs, content)
Definition at line 1090 of file __init__.py.
getItemAndSelector()
fontTools.cffLib.CharStrings.getItemAndSelector (self, name)
Definition at line 1056 of file __init__.py.
has_key()
fontTools.cffLib.CharStrings.has_key (self, name)
Definition at line 1035 of file __init__.py.
keys()
fontTools.cffLib.CharStrings.keys (self)
Definition at line 1026 of file __init__.py.
Referenced by fontTools.ttLib.ttFont.TTFont._save(), sklearn.utils._bunch.Bunch._set_deprecated(), pandas.io.pytables.HDFStore.copy(), fontTools.ttLib.ttFont.TTFont.ensureDecompiled(), scipy.sparse._dok._dok_base.get(), pandas.io.pytables.HDFStore.info(), pandas.io.pytables.HDFStore.keys(), fontTools.varLib.instancer.AxisLimits.normalize(), pip._vendor.pyparsing.results.ParseResults.pprint(), pyparsing.results.ParseResults.pprint(), scipy.sparse._dok._dok_base.resize(), fontTools.ttLib.ttFont.TTFont.saveXML(), scipy.sparse._dok._dok_base.tocoo(), and pip._vendor.distlib.metadata.LegacyMetadata.todict().
toXML()
fontTools.cffLib.CharStrings.toXML (self, xmlWriter)
Definition at line 1070 of file __init__.py.
values()
fontTools.cffLib.CharStrings.values (self)
Definition at line 1029 of file __init__.py.
Referenced by pandas.core.apply.FrameApply.apply_raw(), scipy.sparse._dok._dok_base.count_nonzero(), pandas.core.series.Series.dot(), and scipy.sparse._dok._dok_base.tocoo().
Member Data Documentation
__contains__
fontTools.cffLib.CharStrings.__contains__ = has_key static private
Definition at line 1038 of file __init__.py.
charStrings
fontTools.cffLib.CharStrings.charStrings = {}
Definition at line 1010 of file __init__.py.
charStringsAreIndexed
int fontTools.cffLib.CharStrings.charStringsAreIndexed = 1
Definition at line 1015 of file __init__.py.
charStringsIndex
fontTools.cffLib.CharStrings.charStringsIndex
Initial value:
=  SubrsIndex(
                file, globalSubrs, private, fdSelect, fdArray, isCFF2=isCFF2
            )
Definition at line 1007 of file __init__.py.
fdArray
fontTools.cffLib.CharStrings.fdArray = fdArray
Definition at line 1024 of file __init__.py.
fdSelect
fontTools.cffLib.CharStrings.fdSelect = fdSelect
Definition at line 1022 of file __init__.py.
globalSubrs
fontTools.cffLib.CharStrings.globalSubrs = globalSubrs
Definition at line 1004 of file __init__.py.
private
fontTools.cffLib.CharStrings.private = private
Definition at line 1020 of file __init__.py.
Referenced by pip._vendor.rich._inspect.Inspect._render().
varStore
fontTools.cffLib.CharStrings.varStore = varStore
Definition at line 1005 of file __init__.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/cffLib/__init__.py