Code Cloning Analysis: pandas.tests.util.test_assert_series_equal Namespace Reference
pandas.tests.util.test_assert_series_equal Namespace Reference
Functions
_assert_series_equal_both (a, b, **kwargs)
_assert_not_series_equal (a, b, **kwargs)
_assert_not_series_equal_both (a, b, **kwargs)
test_series_equal (data)
test_series_not_equal_value_mismatch (data1, data2)
test_series_not_equal_metadata_mismatch (kwargs)
test_less_precise (data1, data2, dtype, decimals)
test_series_equal_index_dtype (s1, s2, msg, check_index_type)
test_series_equal_order_mismatch (check_like)
test_series_equal_index_mismatch (check_index)
test_series_invalid_param_combination ()
test_series_equal_length_mismatch (rtol)
test_series_equal_numeric_values_mismatch (rtol)
test_series_equal_categorical_values_mismatch (rtol, using_infer_string)
test_series_equal_datetime_values_mismatch (rtol)
test_series_equal_categorical_mismatch (check_categorical, using_infer_string)
test_assert_series_equal_extension_dtype_mismatch ()
test_assert_series_equal_interval_dtype_mismatch ()
test_series_equal_series_type ()
test_series_equal_exact_for_nonnumeric ()
test_assert_series_equal_ignore_extension_dtype_mismatch ()
test_assert_series_equal_ignore_extension_dtype_mismatch_cross_class ()
test_allows_duplicate_labels ()
test_assert_series_equal_identical_na (nulls_fixture)
test_identical_nested_series_is_equal ()
test_check_dtype_false_different_reso (dtype)
test_large_unequal_ints (dtype)
test_ea_and_numpy_no_dtype_check (val, check_exact, dtype)
test_assert_series_equal_int_tol ()
test_assert_series_equal_index_exact_default ()
Function Documentation
_assert_not_series_equal()
pandas.tests.util.test_assert_series_equal._assert_not_series_equal (a, b, ** kwargs) protected
Check that two Series are not equal.
Parameters
----------
a : Series
    The first Series to compare.
b : Series
    The second Series to compare.
kwargs : dict
    The arguments passed to `tm.assert_series_equal`.
Definition at line 32 of file test_assert_series_equal.py.
Referenced by _assert_not_series_equal_both().
_assert_not_series_equal_both()
pandas.tests.util.test_assert_series_equal._assert_not_series_equal_both (a, b, ** kwargs) protected
Check that two Series are not equal.
This check is performed commutatively.
Parameters
----------
a : Series
    The first Series to compare.
b : Series
    The second Series to compare.
kwargs : dict
    The arguments passed to `tm.assert_series_equal`.
Definition at line 54 of file test_assert_series_equal.py.
References _assert_not_series_equal(), _assert_not_series_equal_both(), and _assert_series_equal_both().
Referenced by _assert_not_series_equal_both().
_assert_series_equal_both()
pandas.tests.util.test_assert_series_equal._assert_series_equal_both (a, b, ** kwargs) protected
Check that two Series equal.
This check is performed commutatively.
Parameters
----------
a : Series
    The first Series to compare.
b : Series
    The second Series to compare.
kwargs : dict
    The arguments passed to `tm.assert_series_equal`.
Definition at line 13 of file test_assert_series_equal.py.
Referenced by _assert_not_series_equal_both().
test_allows_duplicate_labels()
pandas.tests.util.test_assert_series_equal.test_allows_duplicate_labels ()
Definition at line 379 of file test_assert_series_equal.py.
test_assert_series_equal_extension_dtype_mismatch()
pandas.tests.util.test_assert_series_equal.test_assert_series_equal_extension_dtype_mismatch ()
Definition at line 282 of file test_assert_series_equal.py.
test_assert_series_equal_identical_na()
pandas.tests.util.test_assert_series_equal.test_assert_series_equal_identical_na (nulls_fixture)
Definition at line 394 of file test_assert_series_equal.py.
test_assert_series_equal_ignore_extension_dtype_mismatch()
pandas.tests.util.test_assert_series_equal.test_assert_series_equal_ignore_extension_dtype_mismatch ()
Definition at line 365 of file test_assert_series_equal.py.
test_assert_series_equal_ignore_extension_dtype_mismatch_cross_class()
pandas.tests.util.test_assert_series_equal.test_assert_series_equal_ignore_extension_dtype_mismatch_cross_class ()
Definition at line 372 of file test_assert_series_equal.py.
test_assert_series_equal_index_exact_default()
pandas.tests.util.test_assert_series_equal.test_assert_series_equal_index_exact_default ()
Definition at line 479 of file test_assert_series_equal.py.
test_assert_series_equal_int_tol()
pandas.tests.util.test_assert_series_equal.test_assert_series_equal_int_tol ()
Definition at line 467 of file test_assert_series_equal.py.
test_assert_series_equal_interval_dtype_mismatch()
pandas.tests.util.test_assert_series_equal.test_assert_series_equal_interval_dtype_mismatch ()
Definition at line 299 of file test_assert_series_equal.py.
test_check_dtype_false_different_reso()
pandas.tests.util.test_assert_series_equal.test_check_dtype_false_different_reso (dtype)
Definition at line 431 of file test_assert_series_equal.py.
test_ea_and_numpy_no_dtype_check()
pandas.tests.util.test_assert_series_equal.test_ea_and_numpy_no_dtype_check (val, check_exact, dtype)
Definition at line 460 of file test_assert_series_equal.py.
test_identical_nested_series_is_equal()
pandas.tests.util.test_assert_series_equal.test_identical_nested_series_is_equal ()
Definition at line 404 of file test_assert_series_equal.py.
test_large_unequal_ints()
pandas.tests.util.test_assert_series_equal.test_large_unequal_ints (dtype)
Definition at line 449 of file test_assert_series_equal.py.
test_less_precise()
pandas.tests.util.test_assert_series_equal.test_less_precise (data1, data2, dtype, decimals)
Definition at line 111 of file test_assert_series_equal.py.
test_series_equal()
pandas.tests.util.test_assert_series_equal.test_series_equal (data)
Definition at line 74 of file test_assert_series_equal.py.
test_series_equal_categorical_mismatch()
pandas.tests.util.test_assert_series_equal.test_series_equal_categorical_mismatch (check_categorical, using_infer_string)
Definition at line 259 of file test_assert_series_equal.py.
test_series_equal_categorical_values_mismatch()
pandas.tests.util.test_assert_series_equal.test_series_equal_categorical_values_mismatch (rtol, using_infer_string)
Definition at line 217 of file test_assert_series_equal.py.
test_series_equal_datetime_values_mismatch()
pandas.tests.util.test_assert_series_equal.test_series_equal_datetime_values_mismatch (rtol)
Definition at line 244 of file test_assert_series_equal.py.
test_series_equal_exact_for_nonnumeric()
pandas.tests.util.test_assert_series_equal.test_series_equal_exact_for_nonnumeric ()
Definition at line 337 of file test_assert_series_equal.py.
test_series_equal_index_dtype()
pandas.tests.util.test_assert_series_equal.test_series_equal_index_dtype (s1, s2, msg, check_index_type)
Definition at line 145 of file test_assert_series_equal.py.
test_series_equal_index_mismatch()
pandas.tests.util.test_assert_series_equal.test_series_equal_index_mismatch (check_index)
Definition at line 168 of file test_assert_series_equal.py.
test_series_equal_length_mismatch()
pandas.tests.util.test_assert_series_equal.test_series_equal_length_mismatch (rtol)
Definition at line 188 of file test_assert_series_equal.py.
test_series_equal_numeric_values_mismatch()
pandas.tests.util.test_assert_series_equal.test_series_equal_numeric_values_mismatch (rtol)
Definition at line 202 of file test_assert_series_equal.py.
test_series_equal_order_mismatch()
pandas.tests.util.test_assert_series_equal.test_series_equal_order_mismatch (check_like)
Definition at line 156 of file test_assert_series_equal.py.
test_series_equal_series_type()
pandas.tests.util.test_assert_series_equal.test_series_equal_series_type ()
Definition at line 316 of file test_assert_series_equal.py.
test_series_invalid_param_combination()
pandas.tests.util.test_assert_series_equal.test_series_invalid_param_combination ()
Definition at line 179 of file test_assert_series_equal.py.
test_series_not_equal_metadata_mismatch()
pandas.tests.util.test_assert_series_equal.test_series_not_equal_metadata_mismatch (kwargs)
Definition at line 100 of file test_assert_series_equal.py.
test_series_not_equal_value_mismatch()
pandas.tests.util.test_assert_series_equal.test_series_not_equal_value_mismatch (data1, data2)
Definition at line 88 of file test_assert_series_equal.py.