Code Cloning Analysis: matplotlib Namespace Reference
matplotlib Namespace Reference
Namespaces
namespace _afm
namespace _api
namespace _cm
namespace _constrained_layout
namespace _enums
namespace _fontconfig_pattern
namespace _internal_utils
namespace _layoutgrid
namespace _mathtext
namespace _mathtext_data
namespace _pylab_helpers
namespace _text_helpers
namespace _tight_bbox
namespace _tight_layout
namespace _type1font
namespace axis
namespace backend_bases
namespace backend_tools
namespace bezier
namespace category
namespace cbook
namespace cm
namespace collections
namespace colorbar
namespace colorizer
namespace colors
namespace contour
namespace dates
namespace dviread
namespace figure
namespace font_manager
namespace gridspec
namespace hatch
namespace image
namespace inset
namespace layout_engine
namespace legend
namespace legend_handler
namespace lines
namespace markers
namespace mathtext
namespace mlab
namespace offsetbox
namespace patches
namespace path
namespace patheffects
namespace projections
namespace pylab
namespace pyplot
namespace quiver
namespace rcsetup
namespace sankey
namespace scale
namespace stackplot
namespace streamplot
namespace table
namespace testing
namespace texmanager
namespace text
namespace ticker
namespace transforms
namespace tri
namespace typing
namespace units
namespace widgets
Classes
class __getattr__
class ExecutableNotFoundError
class RcParams
Functions
_parse_to_version_info (version_str)
_get_version ()
_check_versions ()
_ensure_handler ()
set_loglevel (level)
_logged_cached (fmt, func=None)
_get_executable_info (name)
_get_xdg_config_dir ()
_get_xdg_cache_dir ()
_get_config_or_cache_dir (xdg_base_getter)
get_configdir ()
get_cachedir ()
get_data_path ()
matplotlib_fname ()
rc_params (fail_on_error=False)
_get_ssl_context ()
_open_file_or_url (fname)
_rc_params_in_file (fname, transform=lambda x:x, fail_on_error=False)
rc_params_from_file (fname, fail_on_error=False, use_default_template=True)
rc (group, **kwargs)
rcdefaults ()
rc_file_defaults ()
rc_file (fname, *, use_default_template=True)
rc_context (rc=None, fname=None)
use (backend, *, force=True)
get_backend (*, auto_select=True)
interactive (b)
is_interactive ()
_val_or_rc (val, rc_name)
_init_tests ()
_replacer (data, value)
_label_from_arg (y, default_name)
_add_data_doc (docstring, replace_names)
_preprocess_data (func=None, *, replace_names=None, label_namer=None)
sanitize_sequence (data)
validate_backend (s)
Variables
list __all__
_log = logging.getLogger(__name__)
str __bibtex__
_VersionInfo
_ExecInfo = namedtuple("_ExecInfo", "executable raw_version version")
dict _deprecated_map = {}
dict _deprecated_ignore_map = {}
dict _deprecated_remain_as_none = {}
rcParamsDefault
rcParams = RcParams()
rcParamsOrig = rcParams.copy()
dict defaultParams
Detailed Description
An object-oriented plotting library.
A procedural interface is provided by the companion pyplot module,
which may be imported directly, e.g.::
    import matplotlib.pyplot as plt
or using ipython::
    ipython
at your terminal, followed by::
    In [1]: %matplotlib
    In [2]: import matplotlib.pyplot as plt
at the ipython shell prompt.
For the most part, direct use of the explicit object-oriented library is
encouraged when programming; the implicit pyplot interface is primarily for
working interactively. The exceptions to this suggestion are the pyplot
functions `.pyplot.figure`, `.pyplot.subplot`, `.pyplot.subplots`, and
`.pyplot.savefig`, which can greatly simplify scripting.  See
:ref:`api_interfaces` for an explanation of the tradeoffs between the implicit
and explicit interfaces.
Modules include:
:mod:`matplotlib.axes`
    The `~.axes.Axes` class.  Most pyplot functions are wrappers for
    `~.axes.Axes` methods.  The axes module is the highest level of OO
    access to the library.
:mod:`matplotlib.figure`
    The `.Figure` class.
:mod:`matplotlib.artist`
    The `.Artist` base class for all classes that draw things.
:mod:`matplotlib.lines`
    The `.Line2D` class for drawing lines and markers.
:mod:`matplotlib.patches`
    Classes for drawing polygons.
:mod:`matplotlib.text`
    The `.Text` and `.Annotation` classes.
:mod:`matplotlib.image`
    The `.AxesImage` and `.FigureImage` classes.
:mod:`matplotlib.collections`
    Classes for efficient drawing of groups of lines or polygons.
:mod:`matplotlib.colors`
    Color specifications and making colormaps.
:mod:`matplotlib.cm`
    Colormaps, and the `.ScalarMappable` mixin class for providing color
    mapping functionality to other classes.
:mod:`matplotlib.ticker`
    Calculation of tick mark locations and formatting of tick labels.
:mod:`matplotlib.backends`
    A subpackage with modules for various GUI libraries and output formats.
The base matplotlib namespace includes:
`~matplotlib.rcParams`
    Default configuration settings; their defaults may be overridden using
    a :file:`matplotlibrc` file.
`~matplotlib.use`
    Setting the Matplotlib backend.  This should be called before any
    figure is created, because it is not possible to switch between
    different GUI backends after that.
The following environment variables can be used to customize the behavior:
:envvar:`MPLBACKEND`
    This optional variable can be set to choose the Matplotlib backend. See
    :ref:`what-is-a-backend`.
:envvar:`MPLCONFIGDIR`
    This is the directory used to store user customizations to
    Matplotlib, as well as some caches to improve performance. If
    :envvar:`MPLCONFIGDIR` is not defined, :file:`{HOME}/.config/matplotlib`
    and :file:`{HOME}/.cache/matplotlib` are used on Linux, and
    :file:`{HOME}/.matplotlib` on other platforms, if they are
    writable. Otherwise, the Python standard library's `tempfile.gettempdir`
    is used to find a base directory in which the :file:`matplotlib`
    subdirectory is created.
Matplotlib was initially written by John D. Hunter (1968-2012) and is now
developed and maintained by a host of others.
Occasionally the internal documentation (python docstrings) will refer
to MATLAB®, a registered trademark of The MathWorks, Inc.
Function Documentation
_add_data_doc()
matplotlib._add_data_doc (docstring, replace_names) protected
Add documentation for a *data* field to the given docstring.
Parameters
----------
docstring : str
    The input docstring.
replace_names : list of str or None
    The list of parameter names which arguments should be replaced by
    ``data[name]`` (if ``data[name]`` does not throw an exception).  If
    None, replacement is attempted for all arguments.
Returns
-------
str
    The augmented docstring.
Definition at line 1403 of file __init__.py.
Referenced by _preprocess_data().
_check_versions()
matplotlib._check_versions () protected
Definition at line 245 of file __init__.py.
_ensure_handler()
matplotlib._ensure_handler () protected
The first time this function is called, attach a `StreamHandler` using the
same format as `logging.basicConfig` to the Matplotlib root logger.
Return this handler every time this function is called.
Definition at line 270 of file __init__.py.
Referenced by set_loglevel().
_get_config_or_cache_dir()
matplotlib._get_config_or_cache_dir (xdg_base_getter) protected
Definition at line 519 of file __init__.py.
_get_executable_info()
matplotlib._get_executable_info (name) protected
Get the version of some executable that Matplotlib optionally depends on.
.. warning::
   The list of executables that this function supports is set according to
   Matplotlib's internal needs, and may change without notice.
Parameters
----------
name : str
    The executable to query.  The following values are currently supported:
    "dvipng", "gs", "inkscape", "magick", "pdftocairo", "pdftops".  This
    list is subject to change without notice.
Returns
-------
tuple
    A namedtuple with fields ``executable`` (`str`) and ``version``
    (`packaging.Version`, or ``None`` if the version cannot be determined).
Raises
------
ExecutableNotFoundError
    If the executable is not found or older than the oldest version
    supported by Matplotlib.  For debugging purposes, it is also
    possible to "hide" an executable from Matplotlib by adding it to the
    :envvar:`_MPLHIDEEXECUTABLES` environment variable (a comma-separated
    list), which must be set prior to any calls to this function.
ValueError
    If the executable is not one that we know how to query.
Definition at line 360 of file __init__.py.
_get_ssl_context()
matplotlib._get_ssl_context () protected
Definition at line 856 of file __init__.py.
_get_version()
matplotlib._get_version () protected
Return the version string used for __version__.
Definition at line 212 of file __init__.py.
_get_xdg_cache_dir()
matplotlib._get_xdg_cache_dir () protected
Return the XDG cache directory, according to the XDG base directory spec:
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
Definition at line 510 of file __init__.py.
_get_xdg_config_dir()
matplotlib._get_xdg_config_dir () protected
Return the XDG configuration directory, according to the XDG base
directory spec:
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
Definition at line 500 of file __init__.py.
_init_tests()
matplotlib._init_tests () protected
Definition at line 1358 of file __init__.py.
_label_from_arg()
matplotlib._label_from_arg (y, default_name) protected
Definition at line 1394 of file __init__.py.
_logged_cached()
matplotlib._logged_cached (fmt, func = None) protected
Decorator that logs a function's return value, and memoizes that value.
After ::
    @_logged_cached(fmt)
    def func(): ...
the first call to *func* will log its return value at the DEBUG level using
%-format string *fmt*, and memoize it; later calls to *func* will directly
return that value.
Definition at line 317 of file __init__.py.
_open_file_or_url()
matplotlib._open_file_or_url (fname) protected
Definition at line 867 of file __init__.py.
_parse_to_version_info()
matplotlib._parse_to_version_info (version_str) protected
Parse a version string to a namedtuple analogous to sys.version_info.
See:
https://packaging.pypa.io/en/latest/version.html#packaging.version.parse
https://docs.python.org/3/library/sys.html#sys.version_info
Definition at line 188 of file __init__.py.
Referenced by matplotlib.pyplot.switch_backend().
_preprocess_data()
matplotlib._preprocess_data (func = None, * , replace_names = None, label_namer = None) protected
A decorator to add a 'data' kwarg to a function.
When applied::
    @_preprocess_data()
    def func(ax, *args, **kwargs): ...
the signature is modified to ``decorated(ax, *args, data=None, **kwargs)``
with the following behavior:
- if called with ``data=None``, forward the other arguments to ``func``;
- otherwise, *data* must be a mapping; for any argument passed in as a
  string ``name``, replace the argument by ``data[name]`` (if this does not
  throw an exception), then forward the arguments to ``func``.
In either case, any argument that is a `MappingView` is also converted to a
list.
Parameters
----------
replace_names : list of str or None, default: None
    The list of parameter names for which lookup into *data* should be
    attempted. If None, replacement is attempted for all arguments.
label_namer : str, default: None
    If set e.g. to "namer" (which must be a kwarg in the function's
    signature -- not as ``**kwargs``), if the *namer* argument passed in is
    a (string) key of *data* and no *label* kwarg is passed, then use the
    (string) value of the *namer* as *label*. ::
        @_preprocess_data(label_namer="foo")
        def func(foo, label=None): ...
        func("key", data={"key": value})
        # is equivalent to
        func.__wrapped__(value, label="key")
Definition at line 1447 of file __init__.py.
References _add_data_doc(), _replacer(), and is_interactive().
Referenced by matplotlib.axes._axes.Axes._fill_between_process_units(), matplotlib.tests.test_preprocess_data.test_compiletime_checks(), and matplotlib.axes._axes.Axes.violin().
_rc_params_in_file()
matplotlib._rc_params_in_file (fname, transform = lambda x: x, fail_on_error = False) protected
Construct a `RcParams` instance from file *fname*.
Unlike `rc_params_from_file`, the configuration class only contains the
parameters specified in the file (i.e. default values are not filled in).
Parameters
----------
fname : path-like
    The loaded file.
transform : callable, default: the identity function
    A function called on each individual line of the file to transform it,
    before further parsing.
fail_on_error : bool, default: False
    Whether invalid entries should result in an exception or a warning.
Definition at line 884 of file __init__.py.
Referenced by rc_params_from_file(), matplotlib.style.core.read_style_directory(), and matplotlib.style.core.use().
_replacer()
matplotlib._replacer (data, value) protected
Either returns ``data[value]`` or passes ``data`` back, converts either to
a sequence.
Definition at line 1378 of file __init__.py.
Referenced by _preprocess_data().
_val_or_rc()
matplotlib._val_or_rc (val, rc_name) protected
If *val* is None, return ``mpl.rcParams[rc_name]``, otherwise return val.
Definition at line 1351 of file __init__.py.
get_backend()
matplotlib.get_backend (* , auto_select = True)
Return the name of the current backend.
Parameters
----------
auto_select : bool, default: True
    Whether to trigger backend resolution if no backend has been
    selected so far. If True, this ensures that a valid backend
    is returned. If False, this returns None if no backend has been
    selected so far.
    .. versionadded:: 3.10
    .. admonition:: Provisional
       The *auto_select* flag is provisional. It may be changed or removed
       without prior warning.
See Also
--------
matplotlib.use
Definition at line 1299 of file __init__.py.
Referenced by matplotlib.pyplot.install_repl_displayhook(), and matplotlib.backends.registry.BackendRegistry.resolve_backend().
get_cachedir()
matplotlib.get_cachedir ()
Return the string path of the cache directory.
The procedure used to find the directory is the same as for
`get_configdir`, except using ``$XDG_CACHE_HOME``/``$HOME/.cache`` instead.
Definition at line 580 of file __init__.py.
get_configdir()
matplotlib.get_configdir ()
Return the string path of the configuration directory.
The directory is chosen as follows:
1. If the MPLCONFIGDIR environment variable is supplied, choose that.
2. On Linux, follow the XDG specification and look first in
   ``$XDG_CONFIG_HOME``, if defined, or ``$HOME/.config``.  On other
   platforms, choose ``$HOME/.matplotlib``.
3. If the chosen directory exists and is writable, use that as the
   configuration directory.
4. Else, create a temporary directory, and use it as the configuration
   directory.
Definition at line 561 of file __init__.py.
Referenced by matplotlib_fname().
get_data_path()
matplotlib.get_data_path ()
Return the path to Matplotlib data.
Definition at line 591 of file __init__.py.
Referenced by matplotlib.cbook._get_data_path(), and matplotlib_fname().
interactive()
matplotlib.interactive (b)
Set whether to redraw after every plotting command (e.g. `.pyplot.xlabel`).
Definition at line 1332 of file __init__.py.
Referenced by matplotlib.pyplot.ioff(), and matplotlib.pyplot.ion().
is_interactive()
matplotlib.is_interactive ()
Return whether to redraw after every plotting command.
.. note::
    This function is only intended for use in backends. End users should
    use `.pyplot.isinteractive` instead.
Definition at line 1339 of file __init__.py.
Referenced by matplotlib.pyplot._auto_draw_if_interactive(), _preprocess_data(), matplotlib.backends.backend_nbagg.connection_info(), matplotlib.backends.backend_nbagg.FigureManagerNbAgg.create_with_canvas(), matplotlib.pyplot.isinteractive(), matplotlib.backend_bases._Backend.new_figure_manager_given_figure(), matplotlib.pyplot.pause(), matplotlib.backend_bases.FigureManagerBase.pyplot_show(), matplotlib.backend_bases._Backend.show(), matplotlib.backends.backend_nbagg.FigureManagerNbAgg.show(), and matplotlib.pyplot.switch_backend().
matplotlib_fname()
matplotlib.matplotlib_fname ()
Get the location of the config file.
The file location is determined in the following order
- ``$PWD/matplotlibrc``
- ``$MATPLOTLIBRC`` if it is not a directory
- ``$MATPLOTLIBRC/matplotlibrc``
- ``$MPLCONFIGDIR/matplotlibrc``
- On Linux,
    - ``$XDG_CONFIG_HOME/matplotlib/matplotlibrc`` (if ``$XDG_CONFIG_HOME``
      is defined)
    - or ``$HOME/.config/matplotlib/matplotlibrc`` (if ``$XDG_CONFIG_HOME``
      is not defined)
- On other platforms,
  - ``$HOME/.matplotlib/matplotlibrc`` if ``$HOME`` is defined
- Lastly, it looks in ``$MATPLOTLIBDATA/matplotlibrc``, which should always
  exist.
Definition at line 596 of file __init__.py.
References get_configdir(), and get_data_path().
Referenced by rc_params(), and rc_params_from_file().
rc()
matplotlib.rc (group, ** kwargs)
Set the current `.rcParams`.  *group* is the grouping for the rc, e.g.,
for ``lines.linewidth`` the group is ``lines``, for
``axes.facecolor``, the group is ``axes``, and so on.  Group may
also be a list or tuple of group names, e.g., (*xtick*, *ytick*).
*kwargs* is a dictionary attribute name/value pairs, e.g.,::
  rc('lines', linewidth=2, color='r')
sets the current `.rcParams` and is equivalent to::
  rcParams['lines.linewidth'] = 2
  rcParams['lines.color'] = 'r'
The following aliases are available to save typing for interactive users:
=====   =================
Alias   Property
=====   =================
'lw'    'linewidth'
'ls'    'linestyle'
'c'     'color'
'fc'    'facecolor'
'ec'    'edgecolor'
'mew'   'markeredgewidth'
'aa'    'antialiased'
=====   =================
Thus you could abbreviate the above call as::
      rc('lines', lw=2, c='r')
Note you can use python's kwargs dictionary facility to store
dictionaries of default parameters.  e.g., you can customize the
font rc as follows::
  font = {'family' : 'monospace',
          'weight' : 'bold',
          'size'   : 'larger'}
  rc('font', **font)  # pass in the font dict as kwargs
This enables you to easily switch between several configurations.  Use
``matplotlib.style.use('default')`` or :func:`~matplotlib.rcdefaults` to
restore the default `.rcParams` after changes.
Notes
-----
Similar functionality is available by using the normal dict interface, i.e.
``rcParams.update({"lines.linewidth": 2, ...})`` (but ``rcParams.update``
does not support abbreviations or grouping).
Definition at line 1022 of file __init__.py.
Referenced by matplotlib.pyplot.pause().
rc_context()
matplotlib.rc_context (rc = None, fname = None)
Return a context manager for temporarily changing rcParams.
The :rc:`backend` will not be reset by the context manager.
rcParams changed both through the context manager invocation and
in the body of the context will be reset on context exit.
Parameters
----------
rc : dict
    The rcParams to temporarily set.
fname : str or path-like
    A file with Matplotlib rc settings. If both *fname* and *rc* are given,
    settings from *rc* take precedence.
See Also
--------
:ref:`customizing-with-matplotlibrc-files`
Examples
--------
Passing explicit values via a dict::
    with mpl.rc_context({'interactive': False}):
        fig, ax = plt.subplots()
        ax.plot(range(3), range(3))
        fig.savefig('example.png')
        plt.close(fig)
Loading settings from a file::
     with mpl.rc_context(fname='print.rc'):
         plt.plot(x, y)  # uses 'print.rc'
Setting in the context body::
    with mpl.rc_context():
        # will be reset
        mpl.rcParams['lines.linewidth'] = 5
        plt.plot(x, y)
Definition at line 1166 of file __init__.py.
References rc_file().
Referenced by matplotlib.tests.test_axes.color_boxes(), matplotlib.pyplot.pause(), matplotlib.tests.test_colorbar.test_cbar_minorticks_for_rc_xyminortickvisible(), matplotlib.tests.test_dates.test_drange(), matplotlib.tests.test_legend.test_empty_bar_chart_with_legend(), matplotlib.tests.test_colorbar.test_remove_from_figure_cl(), matplotlib.tests.test_axes.test_scatter_c_facecolor_warning_integration(), matplotlib.tests.test_axes.test_set_ticks_with_labels(), and matplotlib.tests.test_axes.test_tickdirs().
rc_file()
matplotlib.rc_file (fname, * , use_default_template = True)
Update `.rcParams` from file.
Style-blacklisted `.rcParams` (defined in
``matplotlib.style.core.STYLE_BLACKLIST``) are not updated.
Parameters
----------
fname : str or path-like
    A file with Matplotlib rc settings.
use_default_template : bool
    If True, initialize with default parameters before updating with those
    in the given file. If False, the current configuration persists
    and only the parameters specified in the file are updated.
Definition at line 1138 of file __init__.py.
References rc_params_from_file().
Referenced by rc_context().
rc_file_defaults()
matplotlib.rc_file_defaults ()
Restore the `.rcParams` from the original rc file loaded by Matplotlib.
Style-blacklisted `.rcParams` (defined in
``matplotlib.style.core.STYLE_BLACKLIST``) are not updated.
Definition at line 1123 of file __init__.py.
rc_params()
matplotlib.rc_params (fail_on_error = False)
Construct a `RcParams` instance from the default Matplotlib rc file.
Definition at line 850 of file __init__.py.
References matplotlib_fname(), and rc_params_from_file().
rc_params_from_file()
matplotlib.rc_params_from_file (fname, fail_on_error = False, use_default_template = True)
Construct a `RcParams` from file *fname*.
Parameters
----------
fname : str or path-like
    A file with Matplotlib rc settings.
fail_on_error : bool
    If True, raise an error when the parser fails to convert a parameter.
use_default_template : bool
    If True, initialize with default parameters before updating with those
    in the given file. If False, the configuration class only contains the
    parameters specified in the file. (Useful for updating dicts.)
Definition at line 961 of file __init__.py.
References _rc_params_in_file(), and matplotlib_fname().
Referenced by rc_file(), and rc_params().
rcdefaults()
matplotlib.rcdefaults ()
Restore the `.rcParams` from Matplotlib's internal default style.
Style-blacklisted `.rcParams` (defined in
``matplotlib.style.core.STYLE_BLACKLIST``) are not updated.
See Also
--------
matplotlib.rc_file_defaults
    Restore the `.rcParams` from the rc file originally loaded by
    Matplotlib.
matplotlib.style.use
    Use a specific style file.  Call ``style.use('default')`` to restore
    the default style.
Definition at line 1098 of file __init__.py.
Referenced by matplotlib.pyplot.pause().
sanitize_sequence()
matplotlib.sanitize_sequence (data)
Definition at line 1562 of file __init__.py.
set_loglevel()
matplotlib.set_loglevel (level)
Configure Matplotlib's logging levels.
Matplotlib uses the standard library `logging` framework under the root
logger 'matplotlib'.  This is a helper function to:
- set Matplotlib's root logger level
- set the root logger handler's level, creating the handler
  if it does not exist yet
Typically, one should call ``set_loglevel("info")`` or
``set_loglevel("debug")`` to get additional debugging information.
Users or applications that are installing their own logging handlers
may want to directly manipulate ``logging.getLogger('matplotlib')`` rather
than use this function.
Parameters
----------
level : {"notset", "debug", "info", "warning", "error", "critical"}
    The log level of the handler.
Notes
-----
The first time this function is called, an additional handler is attached
to Matplotlib's root handler; this handler is reused every time and this
function simply manipulates the logger and handler's level.
Definition at line 283 of file __init__.py.
References _ensure_handler().
Referenced by matplotlib.pyplot.uninstall_repl_displayhook().
use()
matplotlib.use (backend, * , force = True)
Select the backend used for rendering and GUI integration.
If pyplot is already imported, `~matplotlib.pyplot.switch_backend` is used
and if the new backend is different than the current backend, all Figures
will be closed.
Parameters
----------
backend : str
    The backend to switch to.  This can either be one of the standard
    backend names, which are case-insensitive:
    - interactive backends:
      GTK3Agg, GTK3Cairo, GTK4Agg, GTK4Cairo, MacOSX, nbAgg, notebook, QtAgg,
      QtCairo, TkAgg, TkCairo, WebAgg, WX, WXAgg, WXCairo, Qt5Agg, Qt5Cairo
    - non-interactive backends:
      agg, cairo, pdf, pgf, ps, svg, template
    or a string of the form: ``module://my.module.name``.
    notebook is a synonym for nbAgg.
    Switching to an interactive backend is not possible if an unrelated
    event loop has already been started (e.g., switching to GTK3Agg if a
    TkAgg window has already been opened).  Switching to a non-interactive
    backend is always possible.
force : bool, default: True
    If True (the default), raise an `ImportError` if the backend cannot be
    set up (either because it fails to import, or because an incompatible
    GUI interactive framework is already running); if False, silently
    ignore the failure.
See Also
--------
:ref:`backends`
matplotlib.get_backend
matplotlib.pyplot.switch_backend
Definition at line 1222 of file __init__.py.
Referenced by sklearn.conftest.pytest_generate_tests().
validate_backend()
matplotlib.validate_backend (s)
Definition at line 1567 of file __init__.py.
Variable Documentation
__all__
list matplotlib.__all__ private
Definition at line 104 of file __init__.py.
__bibtex__
str matplotlib.__bibtex__ private
Initial value:
=  r"""@Article{Hunter:2007,
  Author    = {Hunter, J. D.},
  Title     = {Matplotlib: A 2D graphics environment},
  Journal   = {Computing in Science \& Engineering},
  Volume    = {9},
  Number    = {3},
  Pages     = {90--95},
  abstract  = {Matplotlib is a 2D graphics package used for Python
  for application development, interactive scripting, and
  publication-quality image generation across user
  interfaces and operating systems.},
  publisher = {IEEE COMPUTER SOC},
  year      = 2007
}"""
Definition at line 168 of file __init__.py.
_deprecated_ignore_map
dict matplotlib._deprecated_ignore_map = {} protected
Definition at line 646 of file __init__.py.
_deprecated_map
dict matplotlib._deprecated_map = {} protected
Definition at line 643 of file __init__.py.
_deprecated_remain_as_none
dict matplotlib._deprecated_remain_as_none = {} protected
Definition at line 650 of file __init__.py.
_ExecInfo
matplotlib._ExecInfo = namedtuple("_ExecInfo", "executable raw_version version") protected
Definition at line 348 of file __init__.py.
_log
matplotlib._log = logging.getLogger(__name__) protected
Definition at line 166 of file __init__.py.
_VersionInfo
matplotlib._VersionInfo protected
Initial value:
=  namedtuple('_VersionInfo',
                          'major, minor, micro, releaselevel, serial')
Definition at line 184 of file __init__.py.
defaultParams
dict matplotlib.defaultParams
Initial value:
=  {
        # We want to resolve deprecated rcParams, but not backend...
        key: [(rcsetup._auto_backend_sentinel if key == "backend" else
               rcParamsDefault[key]),
              validator]
        for key, validator in rcsetup._validators.items()}
Definition at line 1012 of file __init__.py.
rcParams
matplotlib.rcParams = RcParams()
Definition at line 1005 of file __init__.py.
rcParamsDefault
matplotlib.rcParamsDefault
Initial value:
=  _rc_params_in_file(
    cbook._get_data_path("matplotlibrc"),
    # Strip leading comment.
    transform=lambda line: line[1:] if line.startswith("#") else line,
    fail_on_error=True)
Definition at line 997 of file __init__.py.
rcParamsOrig
matplotlib.rcParamsOrig = rcParams.copy()
Definition at line 1008 of file __init__.py.