Code Cloning Analysis: dateutil.rrule.rrule Class Reference
dateutil.rrule.rrule Class Reference
Public Member Functions
__init__ (self, freq, dtstart=None, interval=1, wkst=None, count=None, until=None, bysetpos=None, bymonth=None, bymonthday=None, byyearday=None, byeaster=None, byweekno=None, byweekday=None, byhour=None, byminute=None, bysecond=None, cache=False)
__str__ (self)
replace (self, **kwargs)
Public Member Functions inherited from dateutil.rrule.rrulebase
__init__ (self, cache=False)
__iter__ (self)
__getitem__ (self, item)
__contains__ (self, item)
count (self)
before (self, dt, inc=False)
after (self, dt, inc=False)
xafter (self, dt, count=None, inc=False)
between (self, after, before, inc=False, count=1)
Protected Member Functions
_iter (self)
Protected Member Functions inherited from dateutil.rrule.rrulebase
_invalidate_cache (self)
_iter_cached (self)
Protected Attributes
_dtstart = dtstart
_tzinfo = dtstart.tzinfo
_freq = freq
_interval = interval
_count = count
dict _original_rule = {}
_until = until
_wkst = calendar.firstweekday()
tuple _bysetpos = None
_bymonth = None
_byyearday = None
tuple _byeaster = (byeaster,)
tuple _bymonthday = ()
tuple _bynmonthday = ()
_byweekno = None
_byweekday = None
_bynweekday = None
dict _byhour = {dtstart.hour}
dict _byminute = {dtstart.minute}
tuple _bysecond = ((dtstart.second,))
list _timeset = None
Protected Attributes inherited from dateutil.rrule.rrulebase
list _cache = []
_cache_lock = _thread.allocate_lock()
bool _cache_complete = False
_len = None
_cache_gen = self._iter()
Private Member Functions
__construct_byset (self, start, byxxx, base)
__mod_distance (self, value, byxxx, base)
Detailed Description
That's the base of the rrule operation. It accepts all the keywords
defined in the RFC as its constructor parameters (except byday,
which was renamed to byweekday) and more. The constructor prototype is::
        rrule(freq)
Where freq must be one of YEARLY, MONTHLY, WEEKLY, DAILY, HOURLY, MINUTELY,
or SECONDLY.
.. note::
    Per RFC section 3.3.10, recurrence instances falling on invalid dates
    and times are ignored rather than coerced:
        Recurrence rules may generate recurrence instances with an invalid
        date (e.g., February 30) or nonexistent local time (e.g., 1:30 AM
        on a day where the local time is moved forward by an hour at 1:00
        AM).  Such recurrence instances MUST be ignored and MUST NOT be
        counted as part of the recurrence set.
    This can lead to possibly surprising behavior when, for example, the
    start date occurs at the end of the month:
    >>> from dateutil.rrule import rrule, MONTHLY
    >>> from datetime import datetime
    >>> start_date = datetime(2014, 12, 31)
    >>> list(rrule(freq=MONTHLY, count=4, dtstart=start_date))
    ... # doctest: +NORMALIZE_WHITESPACE
    [datetime.datetime(2014, 12, 31, 0, 0),
     datetime.datetime(2015, 1, 31, 0, 0),
     datetime.datetime(2015, 3, 31, 0, 0),
     datetime.datetime(2015, 5, 31, 0, 0)]
Additionally, it supports the following keyword arguments:
:param dtstart:
    The recurrence start. Besides being the base for the recurrence,
    missing parameters in the final recurrence instances will also be
    extracted from this date. If not given, datetime.now() will be used
    instead.
:param interval:
    The interval between each freq iteration. For example, when using
    YEARLY, an interval of 2 means once every two years, but with HOURLY,
    it means once every two hours. The default interval is 1.
:param wkst:
    The week start day. Must be one of the MO, TU, WE constants, or an
    integer, specifying the first day of the week. This will affect
    recurrences based on weekly periods. The default week start is got
    from calendar.firstweekday(), and may be modified by
    calendar.setfirstweekday().
:param count:
    If given, this determines how many occurrences will be generated.
    .. note::
        As of version 2.5.0, the use of the keyword ``until`` in conjunction
        with ``count`` is deprecated, to make sure ``dateutil`` is fully
        compliant with `RFC-5545 Sec. 3.3.10 <https://tools.ietf.org/
        html/rfc5545#section-3.3.10>`_. Therefore, ``until`` and ``count``
        **must not** occur in the same call to ``rrule``.
:param until:
    If given, this must be a datetime instance specifying the upper-bound
    limit of the recurrence. The last recurrence in the rule is the greatest
    datetime that is less than or equal to the value specified in the
    ``until`` parameter.
    .. note::
        As of version 2.5.0, the use of the keyword ``until`` in conjunction
        with ``count`` is deprecated, to make sure ``dateutil`` is fully
        compliant with `RFC-5545 Sec. 3.3.10 <https://tools.ietf.org/
        html/rfc5545#section-3.3.10>`_. Therefore, ``until`` and ``count``
        **must not** occur in the same call to ``rrule``.
:param bysetpos:
    If given, it must be either an integer, or a sequence of integers,
    positive or negative. Each given integer will specify an occurrence
    number, corresponding to the nth occurrence of the rule inside the
    frequency period. For example, a bysetpos of -1 if combined with a
    MONTHLY frequency, and a byweekday of (MO, TU, WE, TH, FR), will
    result in the last work day of every month.
:param bymonth:
    If given, it must be either an integer, or a sequence of integers,
    meaning the months to apply the recurrence to.
:param bymonthday:
    If given, it must be either an integer, or a sequence of integers,
    meaning the month days to apply the recurrence to.
:param byyearday:
    If given, it must be either an integer, or a sequence of integers,
    meaning the year days to apply the recurrence to.
:param byeaster:
    If given, it must be either an integer, or a sequence of integers,
    positive or negative. Each integer will define an offset from the
    Easter Sunday. Passing the offset 0 to byeaster will yield the Easter
    Sunday itself. This is an extension to the RFC specification.
:param byweekno:
    If given, it must be either an integer, or a sequence of integers,
    meaning the week numbers to apply the recurrence to. Week numbers
    have the meaning described in ISO8601, that is, the first week of
    the year is that containing at least four days of the new year.
:param byweekday:
    If given, it must be either an integer (0 == MO), a sequence of
    integers, one of the weekday constants (MO, TU, etc), or a sequence
    of these constants. When given, these variables will define the
    weekdays where the recurrence will be applied. It's also possible to
    use an argument n for the weekday instances, which will mean the nth
    occurrence of this weekday in the period. For example, with MONTHLY,
    or with YEARLY and BYMONTH, using FR(+1) in byweekday will specify the
    first friday of the month where the recurrence happens. Notice that in
    the RFC documentation, this is specified as BYDAY, but was renamed to
    avoid the ambiguity of that keyword.
:param byhour:
    If given, it must be either an integer, or a sequence of integers,
    meaning the hours to apply the recurrence to.
:param byminute:
    If given, it must be either an integer, or a sequence of integers,
    meaning the minutes to apply the recurrence to.
:param bysecond:
    If given, it must be either an integer, or a sequence of integers,
    meaning the seconds to apply the recurrence to.
:param cache:
    If given, it must be a boolean value specifying to enable or disable
    caching of results. If you will use the same rrule instance multiple
    times, enabling caching will improve the performance considerably.
Definition at line 305 of file rrule.py.
Constructor & Destructor Documentation
__init__()
dateutil.rrule.rrule.__init__ (self, freq, dtstart = None, interval = 1, wkst = None, count = None, until = None, bysetpos = None, bymonth = None, bymonthday = None, byyearday = None, byeaster = None, byweekno = None, byweekday = None, byhour = None, byminute = None, bysecond = None, cache = False)
Definition at line 428 of file rrule.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__construct_byset()
dateutil.rrule.rrule.__construct_byset (self, start, byxxx, base) private
If a `BYXXX` sequence is passed to the constructor at the same level as
`FREQ` (e.g. `FREQ=HOURLY,BYHOUR={2,4,7},INTERVAL=3`), there are some
specifications which cannot be reached given some starting conditions.
This occurs whenever the interval is not coprime with the base of a
given unit and the difference between the starting position and the
ending position is not coprime with the greatest common denominator
between the interval and the base. For example, with a FREQ of hourly
starting at 17:00 and an interval of 4, the only valid values for
BYHOUR would be {21, 1, 5, 9, 13, 17}, because 4 and 24 are not
coprime.
:param start:
    Specifies the starting position.
:param byxxx:
    An iterable containing the list of allowed values.
:param base:
    The largest allowable value for the specified frequency (e.g.
    24 hours, 60 minutes).
This does not preserve the type of the iterable, returning a set, since
the values should be unique and the order is irrelevant, this will
speed up later lookups.
In the event of an empty set, raises a :exception:`ValueError`, as this
results in an empty rrule.
Definition at line 1032 of file rrule.py.
References _interval.
__mod_distance()
dateutil.rrule.rrule.__mod_distance (self, value, byxxx, base) private
Calculates the next value in a sequence where the `FREQ` parameter is
specified along with a `BYXXX` parameter at the same "level"
(e.g. `HOURLY` specified with `BYHOUR`).
:param value:
    The old value of the component.
:param byxxx:
    The `BYXXX` set, which should have been generated by
    `rrule._construct_byset`, or something else which checks that a
    valid rule is present.
:param base:
    The largest allowable value for the specified frequency (e.g.
    24 hours, 60 minutes).
If a valid value is not found after `base` iterations (the maximum
number before the sequence would start to repeat), this raises a
:exception:`ValueError`, as no valid values were found.
This returns a tuple of `divmod(n*interval, base)`, where `n` is the
smallest number of `interval` repetitions until the next specified
value in `byxxx` is found.
Definition at line 1079 of file rrule.py.
References _interval.
Referenced by replace().
__str__()
dateutil.rrule.rrule.__str__ (self)
Output a string that would generate this RRULE if passed to rrulestr.
This is mostly compatible with RFC5545, except for the
dateutil-specific extension BYEASTER.
Definition at line 700 of file rrule.py.
References _count, _dtstart, _freq, _interval, _original_rule, _until, and _wkst.
Referenced by numpy.polynomial._polybase.ABCPolyBase._get_coefficients().
_iter()
dateutil.rrule.rrule._iter (self) protected
Definition at line 776 of file rrule.py.
Referenced by sklearn.compose._column_transformer.ColumnTransformer._call_func_on_transformers(), sklearn.pipeline.Pipeline._fit(), sklearn.compose._column_transformer.ColumnTransformer._get_empty_routing(), sklearn.compose._column_transformer.ColumnTransformer._hstack(), sklearn.pipeline.FeatureUnion._parallel_func(), sklearn.compose._column_transformer.ColumnTransformer._record_output_indices(), sklearn.compose._column_transformer.ColumnTransformer._update_fitted_transformers(), sklearn.compose._column_transformer.ColumnTransformer._validate_output(), sklearn.pipeline.Pipeline.decision_function(), sklearn.pipeline.FeatureUnion.feature_names_in_(), sklearn.compose._column_transformer.ColumnTransformer.get_feature_names_out(), sklearn.pipeline.FeatureUnion.get_feature_names_out(), sklearn.pipeline.Pipeline.get_feature_names_out(), sklearn.pipeline.Pipeline.get_metadata_routing(), sklearn.pipeline.Pipeline.inverse_transform(), sklearn.pipeline.Pipeline.predict(), sklearn.pipeline.Pipeline.predict_log_proba(), sklearn.pipeline.Pipeline.predict_proba(), sklearn.pipeline.Pipeline.score(), sklearn.pipeline.Pipeline.score_samples(), sklearn.pipeline.FeatureUnion.set_output(), sklearn.pipeline.Pipeline.set_output(), sklearn.pipeline.FeatureUnion.transform(), and sklearn.pipeline.Pipeline.transform().
replace()
dateutil.rrule.rrule.replace (self, ** kwargs)
Return new rrule with same attributes except for those attributes given new
   values by whichever keyword arguments are specified.
Definition at line 762 of file rrule.py.
References __mod_distance(), _byeaster, _byhour, _byminute, _bymonth, _bymonthday, _bynmonthday, _bysecond, _bysetpos, _byweekday, _byweekno, _byyearday, dateutil.rrule.rrulebase._cache, _count, _dtstart, _freq, _interval, dateutil.rrule.rrulebase._len, _original_rule, _timeset, _until, and _wkst.
Referenced by pandas.core.generic.NDFrame.backfill().
Member Data Documentation
_byeaster
tuple dateutil.rrule.rrule._byeaster = (byeaster,) protected
Definition at line 546 of file rrule.py.
Referenced by replace().
_byhour
dateutil.rrule.rrule._byhour = {dtstart.hour} protected
Definition at line 628 of file rrule.py.
Referenced by replace().
_byminute
dateutil.rrule.rrule._byminute = {dtstart.minute} protected
Definition at line 648 of file rrule.py.
Referenced by replace().
_bymonth
dateutil.rrule.rrule._bymonth = None protected
Definition at line 521 of file rrule.py.
Referenced by replace().
_bymonthday
tuple dateutil.rrule.rrule._bymonthday = () protected
Definition at line 556 of file rrule.py.
Referenced by replace().
_bynmonthday
tuple dateutil.rrule.rrule._bynmonthday = () protected
Definition at line 557 of file rrule.py.
Referenced by replace().
_bynweekday
dateutil.rrule.rrule._bynweekday = None protected
Definition at line 586 of file rrule.py.
_bysecond
dateutil.rrule.rrule._bysecond = ((dtstart.second,)) protected
Definition at line 668 of file rrule.py.
Referenced by replace().
_bysetpos
tuple dateutil.rrule.rrule._bysetpos = None protected
Definition at line 488 of file rrule.py.
Referenced by replace().
_byweekday
dateutil.rrule.rrule._byweekday = None protected
Definition at line 585 of file rrule.py.
Referenced by replace().
_byweekno
dateutil.rrule.rrule._byweekno = None protected
Definition at line 574 of file rrule.py.
Referenced by replace().
_byyearday
dateutil.rrule.rrule._byyearday = None protected
Definition at line 533 of file rrule.py.
Referenced by replace().
_count
dateutil.rrule.rrule._count = count protected
Definition at line 449 of file rrule.py.
Referenced by __str__(), sklearn.naive_bayes._BaseDiscreteNB.fit(), matplotlib.tests.test_animation.NullMovieWriter.grab_frame(), sklearn.naive_bayes._BaseDiscreteNB.partial_fit(), replace(), and matplotlib.tests.test_animation.NullMovieWriter.setup().
_dtstart
dateutil.rrule.rrule._dtstart = dtstart protected
Definition at line 445 of file rrule.py.
Referenced by __str__(), and replace().
_freq
dateutil.rrule.rrule._freq = freq protected
Definition at line 447 of file rrule.py.
Referenced by matplotlib.dates.AutoDateLocator.__init__(), __str__(), matplotlib.dates.AutoDateLocator._get_unit(), pandas.core.arrays.datetimelike.TimelikeOps._maybe_pin_freq(), pandas.core.arrays.datetimelike.TimelikeOps._validate_frequency(), pandas.core.arrays.datetimelike.TimelikeOps.freq(), pandas.core.dtypes.dtypes.PeriodDtype.freq(), matplotlib.dates.AutoDateLocator.get_locator(), pandas.plotting._matplotlib.converter.PandasAutoDateLocator.get_locator(), and replace().
_interval
dateutil.rrule.rrule._interval = interval protected
Definition at line 448 of file rrule.py.
Referenced by __construct_byset(), matplotlib.dates.MicrosecondLocator.__init__(), scipy.stats._censored_data.CensoredData.__len__(), __mod_distance(), __str__(), matplotlib.dates.MicrosecondLocator._get_interval(), matplotlib.backends._backend_tk.TimerTk._on_timer(), matplotlib.animation.TimedAnimation._step(), scipy.stats._censored_data.CensoredData._supported(), matplotlib.backends.backend_qt.TimerQT._timer_set_interval(), scipy.stats._censored_data.CensoredData._uncensor(), matplotlib.backend_bases.TimerBase.interval(), scipy.stats._censored_data.CensoredData.num_censored(), replace(), matplotlib.animation.Animation.save(), matplotlib.animation.Animation.to_html5_video(), and matplotlib.animation.Animation.to_jshtml().
_original_rule
dateutil.rrule.rrule._original_rule = {} protected
Definition at line 455 of file rrule.py.
Referenced by __str__(), and replace().
_timeset
list dateutil.rrule.rrule._timeset = None protected
Definition at line 688 of file rrule.py.
Referenced by replace().
_tzinfo
dateutil.rrule.rrule._tzinfo = dtstart.tzinfo protected
Definition at line 446 of file rrule.py.
Referenced by matplotlib.dates.rrulewrapper._aware_return_wrapper(), and matplotlib.dates.rrulewrapper.set().
_until
dateutil.rrule.rrule._until = until protected
Definition at line 459 of file rrule.py.
Referenced by __str__(), and replace().
_wkst
dateutil.rrule.rrule._wkst = calendar.firstweekday() protected
Definition at line 481 of file rrule.py.
Referenced by __str__(), and replace().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/dateutil/rrule.py