Code Cloning Analysis: fontTools.varLib.merger.MutatorMerger Class Reference
fontTools.varLib.merger.MutatorMerger Class Reference
Public Member Functions
__init__ (self, font, instancer, deleteVariations=True)
Public Member Functions inherited from fontTools.varLib.merger.Merger
__init__ (self, font=None)
merger (celf, clazzes, attrs=(None,))
mergersFor (celf, thing, _default={})
mergeObjects (self, out, lst, exclude=())
mergeLists (self, out, lst)
mergeThings (self, out, lst)
mergeTables (self, font, master_ttfs, tableTags)
Public Attributes
instancer = instancer
deleteVariations = deleteVariations
Public Attributes inherited from fontTools.varLib.merger.Merger
font = font
ttfs = None
Detailed Description
A merger that takes a variable font, and instantiates
an instance.  While there's no "merging" to be done per se,
the operation can benefit from many operations that the
aligning merger does.
Definition at line 1118 of file merger.py.
Constructor & Destructor Documentation
__init__()
fontTools.varLib.merger.MutatorMerger.__init__ (self, font, instancer, deleteVariations = True)
Definition at line 1124 of file merger.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Data Documentation
deleteVariations
fontTools.varLib.merger.MutatorMerger.deleteVariations = deleteVariations
Definition at line 1127 of file merger.py.
instancer
fontTools.varLib.merger.MutatorMerger.instancer = instancer
Definition at line 1126 of file merger.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/varLib/merger.py