Code Cloning Analysis: pandas._config.config.CallableDynamicDoc Class Reference
pandas._config.config.CallableDynamicDoc Class Reference
Public Member Functions
None __init__ (self, Callable[..., T] func, str doc_tmpl)
T __call__ (self, *args, **kwds)
str __doc__ (self)
Private Attributes
__doc_tmpl__ = doc_tmpl
__func__ = func
Detailed Description
Definition at line 268 of file config.py.
Constructor & Destructor Documentation
__init__()
None pandas._config.config.CallableDynamicDoc.__init__ (self, Callable[..., T] func, str doc_tmpl)
Definition at line 269 of file config.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__call__()
T pandas._config.config.CallableDynamicDoc.__call__ (self, * args, ** kwds)
Definition at line 273 of file config.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), and scipy.interpolate._fitpack2.SphereBivariateSpline.ev().
__doc__()
str pandas._config.config.CallableDynamicDoc.__doc__ (self)
Definition at line 278 of file config.py.
Member Data Documentation
__doc_tmpl__
pandas._config.config.CallableDynamicDoc.__doc_tmpl__ = doc_tmpl private
Definition at line 270 of file config.py.
__func__
pandas._config.config.CallableDynamicDoc.__func__ = func private
Definition at line 271 of file config.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/_config/config.py