Code Cloning Analysis: fontTools.cffLib.FontDictCompiler Class Reference
fontTools.cffLib.FontDictCompiler Class Reference
Public Member Functions
__init__ (self, dictObj, strings, parent, isCFF2=None)
getChildren (self, strings)
Public Member Functions inherited from fontTools.cffLib.DictCompiler
__init__ (self, dictObj, strings, parent, isCFF2=None)
setPos (self, pos, endPos)
getDataLength (self)
compile (self, reason)
toFile (self, file)
arg_number (self, num)
arg_SID (self, s)
arg_array (self, value)
arg_delta (self, value)
arg_delta_blend (self, value)
Static Public Attributes
opcodes = buildOpcodeDict(topDictOperators)
Static Public Attributes inherited from fontTools.cffLib.DictCompiler
int maxBlendStack = 0
Additional Inherited Members
Public Attributes inherited from fontTools.cffLib.DictCompiler
isCFF2 = isCFF2
dictObj = dictObj
strings = strings
parent = parent
rawDict = rawDict
Detailed Description
Definition at line 2408 of file __init__.py.
Constructor & Destructor Documentation
__init__()
fontTools.cffLib.FontDictCompiler.__init__ (self, dictObj, strings, parent, isCFF2 = None)
Definition at line 2411 of file __init__.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
getChildren()
fontTools.cffLib.FontDictCompiler.getChildren (self, strings)
Definition at line 2444 of file __init__.py.
Member Data Documentation
opcodes
fontTools.cffLib.FontDictCompiler.opcodes = buildOpcodeDict(topDictOperators) static
Definition at line 2409 of file __init__.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/cffLib/__init__.py