Code Cloning Analysis: matplotlib.layout_engine.PlaceHolderLayoutEngine Class Reference
matplotlib.layout_engine.PlaceHolderLayoutEngine Class Reference
Public Member Functions
__init__ (self, adjust_compatible, colorbar_gridspec, **kwargs)
execute (self, fig)
Public Member Functions inherited from matplotlib.layout_engine.LayoutEngine
__init__ (self, **kwargs)
set (self, **kwargs)
colorbar_gridspec (self)
adjust_compatible (self)
get (self)
Additional Inherited Members
Protected Attributes inherited from matplotlib.layout_engine.LayoutEngine
dict _params = {}
Static Protected Attributes inherited from matplotlib.layout_engine.LayoutEngine
_adjust_compatible = None
_colorbar_gridspec = None
Detailed Description
This layout engine does not adjust the figure layout at all.
The purpose of this `.LayoutEngine` is to act as a placeholder when the user removes
a layout engine to ensure an incompatible `.LayoutEngine` cannot be set later.
Parameters
----------
adjust_compatible, colorbar_gridspec : bool
    Allow the PlaceHolderLayoutEngine to mirror the behavior of whatever
    layout engine it is replacing.
Definition at line 111 of file layout_engine.py.
Constructor & Destructor Documentation
__init__()
matplotlib.layout_engine.PlaceHolderLayoutEngine.__init__ (self, adjust_compatible, colorbar_gridspec, ** kwargs)
Definition at line 125 of file layout_engine.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
execute()
matplotlib.layout_engine.PlaceHolderLayoutEngine.execute (self, fig)
Do nothing.
Reimplemented from matplotlib.layout_engine.LayoutEngine.
Definition at line 130 of file layout_engine.py.
Referenced by pandas.io.sql.SQLiteDatabase._query_iterator(), pandas.io.sql.SQLDatabase.read_query(), and pandas.io.sql.SQLiteDatabase.to_sql().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/layout_engine.py