Code Cloning Analysis: fontTools.cffLib.specializer Namespace Reference
fontTools.cffLib.specializer Namespace Reference
Classes
class _GeneralizerDecombinerCommandsMap
Functions
stringToProgram (string)
programToString (program)
programToCommands (program, getNumRegions=None)
_flattenBlendArgs (args)
commandsToProgram (commands)
_everyN (el, n)
_convertBlendOpToArgs (blendList)
generalizeCommands (commands, ignoreErrors=False)
generalizeProgram (program, getNumRegions=None, **kwargs)
_categorizeVector (v)
_mergeCategories (a, b)
_negateCategory (a)
_convertToBlendCmds (args)
_addArgs (a, b)
_argsStackUse (args)
specializeCommands (commands, ignoreErrors=False, generalizeFirst=True, preserveTopology=False, maxstack=48)
specializeProgram (program, getNumRegions=None, **kwargs)
Variables
parser
metavar
nargs
help
default
type
options = parser.parse_args(sys.argv[1:])
tuple getNumRegions
program = stringToProgram(options.program)
commands = programToCommands(program, getNumRegions)
program2 = commandsToProgram(commands)
font = TTFont(options.font)
cff2 = font["CFF2"].cff.topDictIndex[0]
charstrings = cff2.CharStrings
charstring = charstrings[glyphName]
maxstack
outfile
Detailed Description
T2CharString operator specializer and generalizer.
PostScript glyph drawing operations can be expressed in multiple different
ways. For example, as well as the ``lineto`` operator, there is also a
``hlineto`` operator which draws a horizontal line, removing the need to
specify a ``dx`` coordinate, and a ``vlineto`` operator which draws a
vertical line, removing the need to specify a ``dy`` coordinate. As well
as decompiling :class:`fontTools.misc.psCharStrings.T2CharString` objects
into lists of operations, this module allows for conversion between general
and specific forms of the operation.
Function Documentation
_addArgs()
fontTools.cffLib.specializer._addArgs (a, b) protected
Definition at line 507 of file specializer.py.
_argsStackUse()
fontTools.cffLib.specializer._argsStackUse (args) protected
Definition at line 521 of file specializer.py.
_categorizeVector()
fontTools.cffLib.specializer._categorizeVector (v) protected
Takes X,Y vector v and returns one of r, h, v, or 0 depending on which
of X and/or Y are zero, plus tuple of nonzero ones.  If both are zero,
it returns a single zero still.
>>> _categorizeVector((0,0))
('0', (0,))
>>> _categorizeVector((1,0))
('h', (1,))
>>> _categorizeVector((0,2))
('v', (2,))
>>> _categorizeVector((1,2))
('r', (1, 2))
Definition at line 403 of file specializer.py.
References _categorizeVector(), commandsToProgram(), and programToCommands().
Referenced by _categorizeVector().
_convertBlendOpToArgs()
fontTools.cffLib.specializer._convertBlendOpToArgs (blendList) protected
Definition at line 314 of file specializer.py.
_convertToBlendCmds()
fontTools.cffLib.specializer._convertToBlendCmds (args) protected
Definition at line 449 of file specializer.py.
_everyN()
fontTools.cffLib.specializer._everyN (el, n) protected
Group the list el into groups of size n
Definition at line 155 of file specializer.py.
_flattenBlendArgs()
fontTools.cffLib.specializer._flattenBlendArgs (args) protected
Definition at line 131 of file specializer.py.
_mergeCategories()
fontTools.cffLib.specializer._mergeCategories (a, b) protected
Definition at line 430 of file specializer.py.
_negateCategory()
fontTools.cffLib.specializer._negateCategory (a) protected
Definition at line 440 of file specializer.py.
commandsToProgram()
fontTools.cffLib.specializer.commandsToProgram (commands)
Takes a commands list as returned by programToCommands() and converts
it back to a T2CharString program list.
Definition at line 142 of file specializer.py.
Referenced by _categorizeVector().
generalizeCommands()
fontTools.cffLib.specializer.generalizeCommands (commands, ignoreErrors = False)
Definition at line 356 of file specializer.py.
generalizeProgram()
fontTools.cffLib.specializer.generalizeProgram (program, getNumRegions = None, ** kwargs)
Definition at line 397 of file specializer.py.
programToCommands()
fontTools.cffLib.specializer.programToCommands (program, getNumRegions = None)
Takes a T2CharString program list and returns list of commands.
Each command is a two-tuple of commandname,arg-list.  The commandname might
be empty string if no commandname shall be emitted (used for glyph width,
hintmask/cntrmask argument, as well as stray arguments at the end of the
program (🤷).
'getNumRegions' may be None, or a callable object. It must return the
number of regions. 'getNumRegions' takes a single argument, vsindex. It
returns the numRegions for the vsindex.
The Charstring may or may not start with a width value. If the first
non-blend operator has an odd number of arguments, then the first argument is
a width, and is popped off. This is complicated with blend operators, as
there may be more than one before the first hint or moveto operator, and each
one reduces several arguments to just one list argument. We have to sum the
number of arguments that are not part of the blend arguments, and all the
'numBlends' values. We could instead have said that by definition, if there
is a blend operator, there is no width value, since CFF2 Charstrings don't
have width values. I discussed this with Behdad, and we are allowing for an
initial width value in this case because developers may assemble a CFF2
charstring from CFF Charstrings, which could have width values.
Definition at line 39 of file specializer.py.
Referenced by _categorizeVector().
programToString()
fontTools.cffLib.specializer.programToString (program)
Definition at line 35 of file specializer.py.
specializeCommands()
fontTools.cffLib.specializer.specializeCommands (commands, ignoreErrors = False, generalizeFirst = True, preserveTopology = False, maxstack = 48)
Definition at line 534 of file specializer.py.
specializeProgram()
fontTools.cffLib.specializer.specializeProgram (program, getNumRegions = None, ** kwargs)
Definition at line 836 of file specializer.py.
stringToProgram()
fontTools.cffLib.specializer.stringToProgram (string)
Definition at line 19 of file specializer.py.
Variable Documentation
cff2
fontTools.cffLib.specializer.cff2 = font["CFF2"].cff.topDictIndex[0]
Definition at line 907 of file specializer.py.
charstring
fontTools.cffLib.specializer.charstring = charstrings[glyphName]
Definition at line 910 of file specializer.py.
charstrings
fontTools.cffLib.specializer.charstrings = cff2.CharStrings
Definition at line 908 of file specializer.py.
commands
fontTools.cffLib.specializer.commands = programToCommands(program, getNumRegions)
Definition at line 891 of file specializer.py.
default
fontTools.cffLib.specializer.default
Definition at line 861 of file specializer.py.
font
fontTools.cffLib.specializer.font = TTFont(options.font)
Definition at line 906 of file specializer.py.
getNumRegions
tuple fontTools.cffLib.specializer.getNumRegions
Initial value:
=  (
            None
            if options.num_regions is None
            else lambda vsIndex: int(
                options.num_regions[0 if vsIndex is None else vsIndex]
            )
        )
Definition at line 880 of file specializer.py.
help
fontTools.cffLib.specializer.help
Definition at line 856 of file specializer.py.
maxstack
fontTools.cffLib.specializer.maxstack
Definition at line 914 of file specializer.py.
metavar
fontTools.cffLib.specializer.metavar
Definition at line 856 of file specializer.py.
nargs
fontTools.cffLib.specializer.nargs
Definition at line 856 of file specializer.py.
options
fontTools.cffLib.specializer.options = parser.parse_args(sys.argv[1:])
Definition at line 877 of file specializer.py.
outfile
fontTools.cffLib.specializer.outfile
Initial value:
=  makeOutputFileName(
                options.font, overWrite=True, suffix=".specialized"
            )
Definition at line 920 of file specializer.py.
parser
fontTools.cffLib.specializer.parser
Initial value:
=  argparse.ArgumentParser(
        "fonttools cffLib.specializer",
        description="CFF CharString generalizer/specializer",
    )
Definition at line 852 of file specializer.py.
program
fontTools.cffLib.specializer.program = stringToProgram(options.program)
Definition at line 888 of file specializer.py.
program2
fontTools.cffLib.specializer.program2 = commandsToProgram(commands)
Definition at line 894 of file specializer.py.
type
fontTools.cffLib.specializer.type
Definition at line 873 of file specializer.py.