Code Cloning Analysis: pip._vendor.tenacity.RetryAction Class Reference
pip._vendor.tenacity.RetryAction Class Reference
Public Member Functions
None __init__ (self, t.SupportsFloat sleep)
Public Member Functions inherited from pip._vendor.tenacity.BaseAction
str __repr__ (self)
str __str__ (self)
Public Attributes
sleep = float(sleep)
Additional Inherited Members
Static Public Attributes inherited from pip._vendor.tenacity.BaseAction
tuple REPR_FIELDS = ()
t NAME = None
Detailed Description
Definition at line 136 of file __init__.py.
Constructor & Destructor Documentation
__init__()
None pip._vendor.tenacity.RetryAction.__init__ (self, t.SupportsFloat sleep)
Definition at line 140 of file __init__.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Data Documentation
sleep
pip._vendor.tenacity.RetryAction.sleep = float(sleep)
Definition at line 141 of file __init__.py.
Referenced by pip._vendor.tenacity.BaseRetrying.copy(), and pip._vendor.tenacity.BaseRetrying.wraps().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pip/_vendor/tenacity/__init__.py