Code Cloning Analysis: sklearn.tests.test_docstrings Namespace Reference
sklearn.tests.test_docstrings Namespace Reference
Functions
get_all_methods ()
get_all_functions_names ()
filter_errors (errors, method, Klass=None)
str repr_errors (res, Klass=None, Optional[str] method=None)
test_function_docstring (function_name, request)
test_docstring (Klass, method, request)
Variables
parser = argparse.ArgumentParser(description="Validate docstring with numpydoc.")
help
args = parser.parse_args()
res = numpydoc_validation.validate(args.import_path)
import_path_sections = args.import_path.split(".")
method = import_path_sections[-1]
str msg = repr_errors(res, method=args.import_path)
Function Documentation
filter_errors()
sklearn.tests.test_docstrings.filter_errors (errors, method, Klass = None)
Ignore some errors based on the method type.
These rules are specific for scikit-learn.
Definition at line 45 of file test_docstrings.py.
Referenced by test_function_docstring().
get_all_functions_names()
sklearn.tests.test_docstrings.get_all_functions_names ()
Definition at line 37 of file test_docstrings.py.
get_all_methods()
sklearn.tests.test_docstrings.get_all_methods ()
Definition at line 17 of file test_docstrings.py.
repr_errors()
str sklearn.tests.test_docstrings.repr_errors (res, Klass = None, Optional[str] method = None)
Pretty print original docstring and the obtained errors
Parameters
----------
res : dict
    result of numpydoc.validate.validate
Klass : {Estimator, Display, None}
    estimator object or None
method : str
    if estimator is not None, either the method name or None.
Returns
-------
str
   String representation of the error.
Definition at line 90 of file test_docstrings.py.
Referenced by test_function_docstring().
test_docstring()
sklearn.tests.test_docstrings.test_docstring (Klass, method, request)
Definition at line 159 of file test_docstrings.py.
test_function_docstring()
sklearn.tests.test_docstrings.test_function_docstring (function_name, request)
Check function docstrings using numpydoc.
Definition at line 146 of file test_docstrings.py.
References filter_errors(), and repr_errors().
Variable Documentation
args
sklearn.tests.test_docstrings.args = parser.parse_args()
Definition at line 184 of file test_docstrings.py.
help
sklearn.tests.test_docstrings.help
Definition at line 182 of file test_docstrings.py.
import_path_sections
sklearn.tests.test_docstrings.import_path_sections = args.import_path.split(".")
Definition at line 188 of file test_docstrings.py.
method
sklearn.tests.test_docstrings.method = import_path_sections[-1]
Definition at line 196 of file test_docstrings.py.
msg
str sklearn.tests.test_docstrings.msg = repr_errors(res, method=args.import_path)
Definition at line 203 of file test_docstrings.py.
parser
sklearn.tests.test_docstrings.parser = argparse.ArgumentParser(description="Validate docstring with numpydoc.")
Definition at line 181 of file test_docstrings.py.
res
sklearn.tests.test_docstrings.res = numpydoc_validation.validate(args.import_path)
Definition at line 186 of file test_docstrings.py.