Code Cloning Analysis: packaging._tokenizer.ParserSyntaxError Class Reference
packaging._tokenizer.ParserSyntaxError Class Reference
Public Member Functions
None __init__ (self, str message, *, str source, tuple[int, int] span)
str __str__ (self)
Public Attributes
span = span
message = message
source = source
Static Public Attributes
dict DEFAULT_RULES
Detailed Description
The provided source text could not be parsed correctly.
Definition at line 18 of file _tokenizer.py.
Constructor & Destructor Documentation
__init__()
None packaging._tokenizer.ParserSyntaxError.__init__ (self, str message, * , str source, tuple[int, int] span)
Definition at line 21 of file _tokenizer.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__str__()
str packaging._tokenizer.ParserSyntaxError.__str__ (self)
Definition at line 34 of file _tokenizer.py.
Member Data Documentation
DEFAULT_RULES
dict packaging._tokenizer.ParserSyntaxError.DEFAULT_RULES static
Definition at line 39 of file _tokenizer.py.
message
packaging._tokenizer.ParserSyntaxError.message = message
Definition at line 29 of file _tokenizer.py.
Referenced by matplotlib.backends._backend_gtk._NavigationToolbar2GTK.set_message().
source
packaging._tokenizer.ParserSyntaxError.source = source
Definition at line 30 of file _tokenizer.py.
Referenced by packaging._tokenizer.Tokenizer.check(), and packaging._tokenizer.Tokenizer.raise_syntax_error().
span
packaging._tokenizer.ParserSyntaxError.span = span
Definition at line 28 of file _tokenizer.py.
Referenced by pandas.core.window.ewm.ExponentialMovingWindow.online().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/packaging/_tokenizer.py