Code Cloning Analysis: contourpy.convert Namespace Reference
contourpy.convert Namespace Reference
Functions
cpy.FillReturn _convert_filled_from_OuterCode (cpy.FillReturn_OuterCode filled, FillType fill_type_to)
cpy.FillReturn _convert_filled_from_OuterOffset (cpy.FillReturn_OuterOffset filled, FillType fill_type_to)
cpy.FillReturn _convert_filled_from_ChunkCombinedCode (cpy.FillReturn_ChunkCombinedCode filled, FillType fill_type_to)
cpy.FillReturn _convert_filled_from_ChunkCombinedOffset (cpy.FillReturn_ChunkCombinedOffset filled, FillType fill_type_to)
cpy.FillReturn _convert_filled_from_ChunkCombinedCodeOffset (cpy.FillReturn_ChunkCombinedCodeOffset filled, FillType fill_type_to)
cpy.FillReturn _convert_filled_from_ChunkCombinedOffsetOffset (cpy.FillReturn_ChunkCombinedOffsetOffset filled, FillType fill_type_to)
cpy.FillReturn convert_filled (cpy.FillReturn filled, FillType|str fill_type_from, FillType|str fill_type_to)
cpy.LineReturn _convert_lines_from_Separate (cpy.LineReturn_Separate lines, LineType line_type_to)
cpy.LineReturn _convert_lines_from_SeparateCode (cpy.LineReturn_SeparateCode lines, LineType line_type_to)
cpy.LineReturn _convert_lines_from_ChunkCombinedCode (cpy.LineReturn_ChunkCombinedCode lines, LineType line_type_to)
cpy.LineReturn _convert_lines_from_ChunkCombinedOffset (cpy.LineReturn_ChunkCombinedOffset lines, LineType line_type_to)
cpy.LineReturn _convert_lines_from_ChunkCombinedNan (cpy.LineReturn_ChunkCombinedNan lines, LineType line_type_to)
cpy.LineReturn convert_lines (cpy.LineReturn lines, LineType|str line_type_from, LineType|str line_type_to)
list[cpy.FillReturn] convert_multi_filled (list[cpy.FillReturn] multi_filled, FillType|str fill_type_from, FillType|str fill_type_to)
list[cpy.LineReturn] convert_multi_lines (list[cpy.LineReturn] multi_lines, LineType|str line_type_from, LineType|str line_type_to)
Function Documentation
_convert_filled_from_ChunkCombinedCode()
cpy.FillReturn contourpy.convert._convert_filled_from_ChunkCombinedCode (cpy.FillReturn_ChunkCombinedCode filled, FillType fill_type_to) protected
Definition at line 94 of file convert.py.
_convert_filled_from_ChunkCombinedCodeOffset()
cpy.FillReturn contourpy.convert._convert_filled_from_ChunkCombinedCodeOffset (cpy.FillReturn_ChunkCombinedCodeOffset filled, FillType fill_type_to) protected
Definition at line 129 of file convert.py.
_convert_filled_from_ChunkCombinedOffset()
cpy.FillReturn contourpy.convert._convert_filled_from_ChunkCombinedOffset (cpy.FillReturn_ChunkCombinedOffset filled, FillType fill_type_to) protected
Definition at line 108 of file convert.py.
_convert_filled_from_ChunkCombinedOffsetOffset()
cpy.FillReturn contourpy.convert._convert_filled_from_ChunkCombinedOffsetOffset (cpy.FillReturn_ChunkCombinedOffsetOffset filled, FillType fill_type_to) protected
Definition at line 189 of file convert.py.
_convert_filled_from_OuterCode()
cpy.FillReturn contourpy.convert._convert_filled_from_OuterCode (cpy.FillReturn_OuterCode filled, FillType fill_type_to) protected
Definition at line 18 of file convert.py.
_convert_filled_from_OuterOffset()
cpy.FillReturn contourpy.convert._convert_filled_from_OuterOffset (cpy.FillReturn_OuterOffset filled, FillType fill_type_to) protected
Definition at line 54 of file convert.py.
_convert_lines_from_ChunkCombinedCode()
cpy.LineReturn contourpy.convert._convert_lines_from_ChunkCombinedCode (cpy.LineReturn_ChunkCombinedCode lines, LineType line_type_to) protected
Definition at line 380 of file convert.py.
_convert_lines_from_ChunkCombinedNan()
cpy.LineReturn contourpy.convert._convert_lines_from_ChunkCombinedNan (cpy.LineReturn_ChunkCombinedNan lines, LineType line_type_to) protected
Definition at line 463 of file convert.py.
_convert_lines_from_ChunkCombinedOffset()
cpy.LineReturn contourpy.convert._convert_lines_from_ChunkCombinedOffset (cpy.LineReturn_ChunkCombinedOffset lines, LineType line_type_to) protected
Definition at line 421 of file convert.py.
_convert_lines_from_Separate()
cpy.LineReturn contourpy.convert._convert_lines_from_Separate (cpy.LineReturn_Separate lines, LineType line_type_to) protected
Definition at line 315 of file convert.py.
_convert_lines_from_SeparateCode()
cpy.LineReturn contourpy.convert._convert_lines_from_SeparateCode (cpy.LineReturn_SeparateCode lines, LineType line_type_to) protected
Definition at line 349 of file convert.py.
convert_filled()
cpy.FillReturn contourpy.convert.convert_filled (cpy.FillReturn filled, FillType | str fill_type_from, FillType | str fill_type_to)
Convert filled contours from one :class:`~.FillType` to another.
Args:
    filled (sequence of arrays): Filled contour polygons to convert, such as those returned by
        :meth:`.ContourGenerator.filled`.
    fill_type_from (FillType or str): :class:`~.FillType` to convert from as enum or
        string equivalent.
    fill_type_to (FillType or str): :class:`~.FillType` to convert to as enum or string
        equivalent.
Return:
    Converted filled contour polygons.
When converting non-chunked fill types (``FillType.OuterCode`` or ``FillType.OuterOffset``) to
chunked ones, all polygons are placed in the first chunk. When converting in the other
direction, all chunk information is discarded. Converting a fill type that is not aware of the
relationship between outer boundaries and contained holes (``FillType.ChunkCombinedCode`` or
``FillType.ChunkCombinedOffset``) to one that is will raise a ``ValueError``.
.. versionadded:: 1.2.0
Definition at line 256 of file convert.py.
Referenced by convert_multi_filled().
convert_lines()
cpy.LineReturn contourpy.convert.convert_lines (cpy.LineReturn lines, LineType | str line_type_from, LineType | str line_type_to)
Convert contour lines from one :class:`~.LineType` to another.
Args:
    lines (sequence of arrays): Contour lines to convert, such as those returned by
        :meth:`.ContourGenerator.lines`.
    line_type_from (LineType or str): :class:`~.LineType` to convert from as enum or
        string equivalent.
    line_type_to (LineType or str): :class:`~.LineType` to convert to as enum or string
        equivalent.
Return:
    Converted contour lines.
When converting non-chunked line types (``LineType.Separate`` or ``LineType.SeparateCode``) to
chunked ones (``LineType.ChunkCombinedCode``, ``LineType.ChunkCombinedOffset`` or
``LineType.ChunkCombinedNan``), all lines are placed in the first chunk. When converting in the
other direction, all chunk information is discarded.
.. versionadded:: 1.2.0
Definition at line 507 of file convert.py.
Referenced by convert_multi_lines().
convert_multi_filled()
list[cpy.FillReturn] contourpy.convert.convert_multi_filled (list[cpy.FillReturn] multi_filled, FillType | str fill_type_from, FillType | str fill_type_to)
Convert multiple sets of filled contours from one :class:`~.FillType` to another.
Args:
    multi_filled (nested sequence of arrays): Filled contour polygons to convert, such as those
        returned by :meth:`.ContourGenerator.multi_filled`.
    fill_type_from (FillType or str): :class:`~.FillType` to convert from as enum or
        string equivalent.
    fill_type_to (FillType or str): :class:`~.FillType` to convert to as enum or string
        equivalent.
Return:
    Converted sets filled contour polygons.
When converting non-chunked fill types (``FillType.OuterCode`` or ``FillType.OuterOffset``) to
chunked ones, all polygons are placed in the first chunk. When converting in the other
direction, all chunk information is discarded. Converting a fill type that is not aware of the
relationship between outer boundaries and contained holes (``FillType.ChunkCombinedCode`` or
``FillType.ChunkCombinedOffset``) to one that is will raise a ``ValueError``.
.. versionadded:: 1.3.0
Definition at line 561 of file convert.py.
References convert_filled().
convert_multi_lines()
list[cpy.LineReturn] contourpy.convert.convert_multi_lines (list[cpy.LineReturn] multi_lines, LineType | str line_type_from, LineType | str line_type_to)
Convert multiple sets of contour lines from one :class:`~.LineType` to another.
Args:
    multi_lines (nested sequence of arrays): Contour lines to convert, such as those returned by
        :meth:`.ContourGenerator.multi_lines`.
    line_type_from (LineType or str): :class:`~.LineType` to convert from as enum or
        string equivalent.
    line_type_to (LineType or str): :class:`~.LineType` to convert to as enum or string
        equivalent.
Return:
    Converted set of contour lines.
When converting non-chunked line types (``LineType.Separate`` or ``LineType.SeparateCode``) to
chunked ones (``LineType.ChunkCombinedCode``, ``LineType.ChunkCombinedOffset`` or
``LineType.ChunkCombinedNan``), all lines are placed in the first chunk. When converting in the
other direction, all chunk information is discarded.
.. versionadded:: 1.3.0
Definition at line 593 of file convert.py.
References convert_lines().