Code Cloning Analysis: fontTools.varLib.avarPlanner Namespace Reference
fontTools.varLib.avarPlanner Namespace Reference
Functions
normalizeLinear (value, rangeMin, rangeMax)
interpolateLinear (t, a, b)
normalizeLog (value, rangeMin, rangeMax)
interpolateLog (t, a, b)
normalizeDegrees (value, rangeMin, rangeMax)
measureWeight (glyphset, glyphs=None)
measureWidth (glyphset, glyphs=None)
measureSlant (glyphset, glyphs=None)
sanitizeWidth (userTriple, designTriple, pins, measurements)
sanitizeWeight (userTriple, designTriple, pins, measurements)
sanitizeSlant (userTriple, designTriple, pins, measurements)
planAxis (measureFunc, normalizeFunc, interpolateFunc, glyphSetFunc, axisTag, axisLimits, values, samples=None, glyphs=None, designLimits=None, pins=None, sanitizeFunc=None)
planWeightAxis (glyphSetFunc, axisLimits, weights=None, samples=None, glyphs=None, designLimits=None, pins=None, sanitize=False)
planWidthAxis (glyphSetFunc, axisLimits, widths=None, samples=None, glyphs=None, designLimits=None, pins=None, sanitize=False)
planSlantAxis (glyphSetFunc, axisLimits, slants=None, samples=None, glyphs=None, designLimits=None, pins=None, sanitize=False)
planOpticalSizeAxis (glyphSetFunc, axisLimits, sizes=None, samples=None, glyphs=None, designLimits=None, pins=None, sanitize=False)
makeDesignspaceSnippet (axisTag, axisName, axisLimit, mapping)
addEmptyAvar (font)
processAxis (font, planFunc, axisTag, axisName, values, samples=None, glyphs=None, designLimits=None, pins=None, sanitize=False, plot=False)
main (args=None)
Variables
list __all__
log = logging.getLogger("fontTools.varLib.avarPlanner")
list WEIGHTS
list WIDTHS
SLANTS = list(math.degrees(math.atan(d / 20.0)) for d in range(-20, 21))
list SIZES
int SAMPLES = 8
Function Documentation
addEmptyAvar()
fontTools.varLib.avarPlanner.addEmptyAvar (font)
Add an empty `avar` table to the font.
Definition at line 704 of file avarPlanner.py.
Referenced by processAxis().
interpolateLinear()
fontTools.varLib.avarPlanner.interpolateLinear (t, a, b)
Linear interpolation between a and b, with t typically in [0, 1].
Definition at line 113 of file avarPlanner.py.
interpolateLog()
fontTools.varLib.avarPlanner.interpolateLog (t, a, b)
Logarithmic interpolation between a and b, with t typically in [0, 1].
Definition at line 125 of file avarPlanner.py.
main()
fontTools.varLib.avarPlanner.main (args = None)
Plan the standard axis mappings for a variable font
Definition at line 803 of file avarPlanner.py.
References processAxis().
makeDesignspaceSnippet()
fontTools.varLib.avarPlanner.makeDesignspaceSnippet (axisTag, axisName, axisLimit, mapping)
Make a designspace snippet for a single axis.
Definition at line 683 of file avarPlanner.py.
Referenced by processAxis().
measureSlant()
fontTools.varLib.avarPlanner.measureSlant (glyphset, glyphs = None)
Measure the perceptual average slant angle of the given glyphs.
Definition at line 195 of file avarPlanner.py.
measureWeight()
fontTools.varLib.avarPlanner.measureWeight (glyphset, glyphs = None)
Measure the perceptual average weight of the given glyphs.
Definition at line 139 of file avarPlanner.py.
measureWidth()
fontTools.varLib.avarPlanner.measureWidth (glyphset, glyphs = None)
Measure the average width of the given glyphs.
Definition at line 167 of file avarPlanner.py.
normalizeDegrees()
fontTools.varLib.avarPlanner.normalizeDegrees (value, rangeMin, rangeMax)
Angularly normalize value in [rangeMin, rangeMax] to [0, 1], with extrapolation.
Definition at line 132 of file avarPlanner.py.
normalizeLinear()
fontTools.varLib.avarPlanner.normalizeLinear (value, rangeMin, rangeMax)
Linearly normalize value in [rangeMin, rangeMax] to [0, 1], with extrapolation.
Definition at line 108 of file avarPlanner.py.
normalizeLog()
fontTools.varLib.avarPlanner.normalizeLog (value, rangeMin, rangeMax)
Logarithmically normalize value in [rangeMin, rangeMax] to [0, 1], with extrapolation.
Definition at line 118 of file avarPlanner.py.
planAxis()
fontTools.varLib.avarPlanner.planAxis (measureFunc, normalizeFunc, interpolateFunc, glyphSetFunc, axisTag, axisLimits, values, samples = None, glyphs = None, designLimits = None, pins = None, sanitizeFunc = None)
Plan an axis.
measureFunc: callable that takes a glyphset and an optional
list of glyphnames, and returns the glyphset-wide measurement
to be used for the axis.
normalizeFunc: callable that takes a measurement and a minimum
and maximum, and normalizes the measurement into the range 0..1,
possibly extrapolating too.
interpolateFunc: callable that takes a normalized t value, and a
minimum and maximum, and returns the interpolated value,
possibly extrapolating too.
glyphSetFunc: callable that takes a variations "location" dictionary,
and returns a glyphset.
axisTag: the axis tag string.
axisLimits: a triple of minimum, default, and maximum values for
the axis. Or an `fvar` Axis object.
values: a list of output values to map for this axis.
samples: the number of samples to use when sampling. Default 8.
glyphs: a list of glyph names to use when sampling. Defaults to None,
which will process all glyphs.
designLimits: an optional triple of minimum, default, and maximum values
represenging the "design" limits for the axis. If not provided, the
axisLimits will be used.
pins: an optional dictionary of before/after mapping entries to pin in
the output.
sanitizeFunc: an optional callable to call to sanitize the axis limits.
Definition at line 369 of file avarPlanner.py.
Referenced by planOpticalSizeAxis(), planSlantAxis(), planWeightAxis(), and planWidthAxis().
planOpticalSizeAxis()
fontTools.varLib.avarPlanner.planOpticalSizeAxis (glyphSetFunc, axisLimits, sizes = None, samples = None, glyphs = None, designLimits = None, pins = None, sanitize = False)
Plan a optical-size (`opsz`) axis.
sizes: A list of optical size values to plan for. If None, the default
values are used.
This function simply calls planAxis with values=sizes, and the appropriate
arguments. See documenation for planAxis for more information.
Definition at line 646 of file avarPlanner.py.
References planAxis().
planSlantAxis()
fontTools.varLib.avarPlanner.planSlantAxis (glyphSetFunc, axisLimits, slants = None, samples = None, glyphs = None, designLimits = None, pins = None, sanitize = False)
Plan a slant (`slnt`) axis.
slants: A list slant angles to plan for. If None, the default
values are used.
This function simply calls planAxis with values=slants, and the appropriate
arguments. See documenation for planAxis for more information.
Definition at line 608 of file avarPlanner.py.
References planAxis().
planWeightAxis()
fontTools.varLib.avarPlanner.planWeightAxis (glyphSetFunc, axisLimits, weights = None, samples = None, glyphs = None, designLimits = None, pins = None, sanitize = False)
Plan a weight (`wght`) axis.
weights: A list of weight values to plan for. If None, the default
values are used.
This function simply calls planAxis with values=weights, and the appropriate
arguments. See documenation for planAxis for more information.
Definition at line 532 of file avarPlanner.py.
References planAxis().
planWidthAxis()
fontTools.varLib.avarPlanner.planWidthAxis (glyphSetFunc, axisLimits, widths = None, samples = None, glyphs = None, designLimits = None, pins = None, sanitize = False)
Plan a width (`wdth`) axis.
widths: A list of width values (percentages) to plan for. If None, the default
values are used.
This function simply calls planAxis with values=widths, and the appropriate
arguments. See documenation for planAxis for more information.
Definition at line 570 of file avarPlanner.py.
References planAxis().
processAxis()
fontTools.varLib.avarPlanner.processAxis (font, planFunc, axisTag, axisName, values, samples = None, glyphs = None, designLimits = None, pins = None, sanitize = False, plot = False)
Process a single axis.
Definition at line 711 of file avarPlanner.py.
References addEmptyAvar(), and makeDesignspaceSnippet().
Referenced by main().
sanitizeSlant()
fontTools.varLib.avarPlanner.sanitizeSlant (userTriple, designTriple, pins, measurements)
Sanitize the slant axis limits.
Definition at line 336 of file avarPlanner.py.
sanitizeWeight()
fontTools.varLib.avarPlanner.sanitizeWeight (userTriple, designTriple, pins, measurements)
Sanitize the weight axis limits.
Definition at line 265 of file avarPlanner.py.
sanitizeWidth()
fontTools.varLib.avarPlanner.sanitizeWidth (userTriple, designTriple, pins, measurements)
Sanitize the width axis limits.
Definition at line 224 of file avarPlanner.py.
Variable Documentation
__all__
list fontTools.varLib.avarPlanner.__all__ private
Initial value:
=  [
    "planWeightAxis",
    "planWidthAxis",
    "planSlantAxis",
    "planOpticalSizeAxis",
    "planAxis",
    "sanitizeWeight",
    "sanitizeWidth",
    "sanitizeSlant",
    "measureWeight",
    "measureWidth",
    "measureSlant",
    "normalizeLinear",
    "normalizeLog",
    "normalizeDegrees",
    "interpolateLinear",
    "interpolateLog",
    "processAxis",
    "makeDesignspaceSnippet",
    "addEmptyAvar",
    "main",
]
Definition at line 12 of file avarPlanner.py.
log
fontTools.varLib.avarPlanner.log = logging.getLogger("fontTools.varLib.avarPlanner")
Definition at line 35 of file avarPlanner.py.
SAMPLES
int fontTools.varLib.avarPlanner.SAMPLES = 8
Definition at line 105 of file avarPlanner.py.
SIZES
list fontTools.varLib.avarPlanner.SIZES
Initial value:
=  [
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    14,
    18,
    24,
    30,
    36,
    48,
    60,
    72,
    96,
    120,
    144,
    192,
    240,
    288,
]
Definition at line 79 of file avarPlanner.py.
SLANTS
fontTools.varLib.avarPlanner.SLANTS = list(math.degrees(math.atan(d / 20.0)) for d in range(-20, 21))
Definition at line 77 of file avarPlanner.py.
WEIGHTS
list fontTools.varLib.avarPlanner.WEIGHTS
Initial value:
=  [
    50,
    100,
    150,
    200,
    250,
    300,
    350,
    400,
    450,
    500,
    550,
    600,
    650,
    700,
    750,
    800,
    850,
    900,
    950,
]
Definition at line 37 of file avarPlanner.py.
WIDTHS
list fontTools.varLib.avarPlanner.WIDTHS
Initial value:
=  [
    25.0,
    37.5,
    50.0,
    62.5,
    75.0,
    87.5,
    100.0,
    112.5,
    125.0,
    137.5,
    150.0,
    162.5,
    175.0,
    187.5,
    200.0,
]
Definition at line 59 of file avarPlanner.py.