Code Cloning Analysis: pyparsing.util._GroupConsecutive Class Reference
pyparsing.util._GroupConsecutive Class Reference
Public Member Functions
None __init__ (self)
int __call__ (self, str char)
Public Attributes
int prev = 0
counter = itertools.count()
int value = -1
Detailed Description
Used as a callable `key` for itertools.groupby to group
characters that are consecutive:
    itertools.groupby("abcdejkmpqrs", key=IsConsecutive())
    yields:
        (0, iter(['a', 'b', 'c', 'd', 'e']))
        (1, iter(['j', 'k']))
        (2, iter(['m']))
        (3, iter(['p', 'q', 'r', 's']))
Definition at line 185 of file util.py.
Constructor & Destructor Documentation
__init__()
None pyparsing.util._GroupConsecutive.__init__ (self)
Definition at line 197 of file util.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
__call__()
int pyparsing.util._GroupConsecutive.__call__ (self, str char)
Definition at line 202 of file util.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), and scipy.interpolate._fitpack2.SphereBivariateSpline.ev().
Member Data Documentation
counter
pyparsing.util._GroupConsecutive.counter = itertools.count()
Definition at line 199 of file util.py.
prev
pyparsing.util._GroupConsecutive.prev = 0
Definition at line 198 of file util.py.
value
int pyparsing.util._GroupConsecutive.value = -1
Definition at line 200 of file util.py.
Referenced by sklearn.externals.array_api_extra._lib._at._AtOp.__str__(), sklearn.externals.array_api_extra._lib._backends.Backend.__str__(), pip._internal.models.link.LinkHash.as_hashes(), pip._internal.models.link.LinkHash.find_hash_url_fragment(), and pip._internal.models.link.LinkHash.is_hash_allowed().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pyparsing/util.py