Code Cloning Analysis: joblib.backports.Version Class Reference
joblib.backports.Version Class Reference
Public Member Functions
__init__ (self, vstring=None)
__repr__ (self)
__eq__ (self, other)
__lt__ (self, other)
__le__ (self, other)
__gt__ (self, other)
__ge__ (self, other)
Detailed Description
Backport from deprecated distutils
We maintain this backport to avoid introducing a new dependency on
`packaging`.
We might rexplore this choice in the future if all major Python projects
introduce a dependency on packaging anyway.
Definition at line 12 of file backports.py.
Constructor & Destructor Documentation
__init__()
joblib.backports.Version.__init__ (self, vstring = None)
Definition at line 22 of file backports.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__eq__()
joblib.backports.Version.__eq__ (self, other)
Definition at line 29 of file backports.py.
Referenced by pandas.core.dtypes.base.ExtensionDtype.__eq__(), pandas.io.pytables.IndexCol.__eq__(), pip._vendor.msgpack.ext.Timestamp.__ne__(), numpy.polynomial._polybase.ABCPolyBase._str_term_ascii(), pip._vendor.distlib.version.Matcher.match(), pandas.core.dtypes.dtypes.PeriodDtype.na_value(), and numpy.lib.polynomial.poly1d.roots().
__ge__()
joblib.backports.Version.__ge__ (self, other)
Definition at line 53 of file backports.py.
__gt__()
joblib.backports.Version.__gt__ (self, other)
Definition at line 47 of file backports.py.
__le__()
joblib.backports.Version.__le__ (self, other)
Definition at line 41 of file backports.py.
__lt__()
joblib.backports.Version.__lt__ (self, other)
Definition at line 35 of file backports.py.
__repr__()
joblib.backports.Version.__repr__ (self)
Definition at line 26 of file backports.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/joblib/backports.py