Code Cloning Analysis: matplotlib._constrained_layout Namespace Reference
matplotlib._constrained_layout Namespace Reference
Functions
do_constrained_layout (fig, h_pad, w_pad, hspace=None, wspace=None, rect=(0, 0, 1, 1), compress=False)
make_layoutgrids (fig, layoutgrids, rect=(0, 0, 1, 1))
make_layoutgrids_gs (layoutgrids, gs)
check_no_collapsed_axes (layoutgrids, fig)
compress_fixed_aspect (layoutgrids, fig)
get_margin_from_padding (obj, *, w_pad=0, h_pad=0, hspace=0, wspace=0)
make_layout_margins (layoutgrids, fig, renderer, *, w_pad=0, h_pad=0, hspace=0, wspace=0)
make_margin_suptitles (layoutgrids, fig, renderer, *, w_pad=0, h_pad=0)
match_submerged_margins (layoutgrids, fig)
get_cb_parent_spans (cbax)
get_pos_and_bbox (ax, renderer)
reposition_axes (layoutgrids, fig, renderer, *, w_pad=0, h_pad=0, hspace=0, wspace=0)
reposition_colorbar (layoutgrids, cbax, renderer, *, offset=None)
reset_margins (layoutgrids, fig)
colorbar_get_pad (layoutgrids, cax)
Variables
_log = logging.getLogger(__name__)
Detailed Description
Adjust subplot layouts so that there are no overlapping Axes or Axes
decorations.  All Axes decorations are dealt with (labels, ticks, titles,
ticklabels) and some dependent artists are also dealt with (colorbar,
suptitle).
Layout is done via `~matplotlib.gridspec`, with one constraint per gridspec,
so it is possible to have overlapping Axes if the gridspecs overlap (i.e.
using `~matplotlib.gridspec.GridSpecFromSubplotSpec`).  Axes placed using
``figure.subplots()`` or ``figure.add_subplots()`` will participate in the
layout.  Axes manually placed via ``figure.add_axes()`` will not.
See Tutorial: :ref:`constrainedlayout_guide`
General idea:
-------------
First, a figure has a gridspec that divides the figure into nrows and ncols,
with heights and widths set by ``height_ratios`` and ``width_ratios``,
often just set to 1 for an equal grid.
Subplotspecs that are derived from this gridspec can contain either a
``SubPanel``, a ``GridSpecFromSubplotSpec``, or an ``Axes``.  The ``SubPanel``
and ``GridSpecFromSubplotSpec`` are dealt with recursively and each contain an
analogous layout.
Each ``GridSpec`` has a ``_layoutgrid`` attached to it.  The ``_layoutgrid``
has the same logical layout as the ``GridSpec``.   Each row of the grid spec
has a top and bottom "margin" and each column has a left and right "margin".
The "inner" height of each row is constrained to be the same (or as modified
by ``height_ratio``), and the "inner" width of each column is
constrained to be the same (as modified by ``width_ratio``), where "inner"
is the width or height of each column/row minus the size of the margins.
Then the size of the margins for each row and column are determined as the
max width of the decorators on each Axes that has decorators in that margin.
For instance, a normal Axes would have a left margin that includes the
left ticklabels, and the ylabel if it exists.  The right margin may include a
colorbar, the bottom margin the xaxis decorations, and the top margin the
title.
With these constraints, the solver then finds appropriate bounds for the
columns and rows.  It's possible that the margins take up the whole figure,
in which case the algorithm is not applied and a warning is raised.
See the tutorial :ref:`constrainedlayout_guide`
for more discussion of the algorithm with examples.
Function Documentation
check_no_collapsed_axes()
matplotlib._constrained_layout.check_no_collapsed_axes (layoutgrids, fig)
Check that no Axes have collapsed to zero size.
Definition at line 247 of file _constrained_layout.py.
References check_no_collapsed_axes().
Referenced by check_no_collapsed_axes(), and do_constrained_layout().
colorbar_get_pad()
matplotlib._constrained_layout.colorbar_get_pad (layoutgrids, cax)
Definition at line 789 of file _constrained_layout.py.
compress_fixed_aspect()
matplotlib._constrained_layout.compress_fixed_aspect (layoutgrids, fig)
Definition at line 267 of file _constrained_layout.py.
do_constrained_layout()
matplotlib._constrained_layout.do_constrained_layout (fig, h_pad, w_pad, hspace = None, wspace = None, rect = (0, 0, 1, 1), compress = False)
Do the constrained_layout.  Called at draw time in
 ``figure.constrained_layout()``
Parameters
----------
fig : `~matplotlib.figure.Figure`
    `.Figure` instance to do the layout in.
h_pad, w_pad : float
  Padding around the Axes elements in figure-normalized units.
hspace, wspace : float
   Fraction of the figure to dedicate to space between the
   Axes.  These are evenly spread between the gaps between the Axes.
   A value of 0.2 for a three-column layout would have a space
   of 0.1 of the figure width between each column.
   If h/wspace < h/w_pad, then the pads are used instead.
rect : tuple of 4 floats
    Rectangle in figure coordinates to perform constrained layout in
    [left, bottom, width, height], each from 0-1.
compress : bool
    Whether to shift Axes so that white space in between them is
    removed. This is useful for simple grids of fixed-aspect Axes (e.g.
    a grid of images).
Returns
-------
layoutgrid : private debugging structure
Definition at line 63 of file _constrained_layout.py.
References check_no_collapsed_axes(), make_layout_margins(), make_layoutgrids(), match_submerged_margins(), reposition_axes(), and reset_margins().
get_cb_parent_spans()
matplotlib._constrained_layout.get_cb_parent_spans (cbax)
Figure out which subplotspecs this colorbar belongs to.
Parameters
----------
cbax : `~matplotlib.axes.Axes`
    Axes for the colorbar.
Definition at line 596 of file _constrained_layout.py.
Referenced by make_layout_margins(), reposition_colorbar(), and reset_margins().
get_margin_from_padding()
matplotlib._constrained_layout.get_margin_from_padding (obj, * , w_pad = 0, h_pad = 0, hspace = 0, wspace = 0)
Definition at line 304 of file _constrained_layout.py.
get_pos_and_bbox()
matplotlib._constrained_layout.get_pos_and_bbox (ax, renderer)
Get the position and the bbox for the Axes.
Parameters
----------
ax : `~matplotlib.axes.Axes`
renderer : `~matplotlib.backend_bases.RendererBase` subclass.
Returns
-------
pos : `~matplotlib.transforms.Bbox`
    Position in figure coordinates.
bbox : `~matplotlib.transforms.Bbox`
    Tight bounding box in figure coordinates.
Definition at line 621 of file _constrained_layout.py.
Referenced by make_layout_margins(), and reposition_colorbar().
make_layout_margins()
matplotlib._constrained_layout.make_layout_margins (layoutgrids, fig, renderer, * , w_pad = 0, h_pad = 0, hspace = 0, wspace = 0)
For each Axes, make a margin between the *pos* layoutbox and the
*axes* layoutbox be a minimum size that can accommodate the
decorations on the axis.
Then make room for colorbars.
Parameters
----------
layoutgrids : dict
fig : `~matplotlib.figure.Figure`
    `.Figure` instance to do the layout in.
renderer : `~matplotlib.backend_bases.RendererBase` subclass.
    The renderer to use.
w_pad, h_pad : float, default: 0
    Width and height padding (in fraction of figure).
hspace, wspace : float, default: 0
    Width and height padding as fraction of figure size divided by
    number of columns or rows.
Definition at line 342 of file _constrained_layout.py.
References get_cb_parent_spans(), get_pos_and_bbox(), and make_layout_margins().
Referenced by do_constrained_layout(), and make_layout_margins().
make_layoutgrids()
matplotlib._constrained_layout.make_layoutgrids (fig, layoutgrids, rect = (0, 0, 1, 1))
Make the layoutgrid tree.
(Sub)Figures get a layoutgrid so we can have figure margins.
Gridspecs that are attached to Axes get a layoutgrid so Axes
can have margins.
Definition at line 156 of file _constrained_layout.py.
References make_layoutgrids(), and make_layoutgrids_gs().
Referenced by do_constrained_layout(), and make_layoutgrids().
make_layoutgrids_gs()
matplotlib._constrained_layout.make_layoutgrids_gs (layoutgrids, gs)
Make the layoutgrid for a gridspec (and anything nested in the gridspec)
Definition at line 201 of file _constrained_layout.py.
References make_layoutgrids_gs().
Referenced by make_layoutgrids(), and make_layoutgrids_gs().
make_margin_suptitles()
matplotlib._constrained_layout.make_margin_suptitles (layoutgrids, fig, renderer, * , w_pad = 0, h_pad = 0)
Definition at line 460 of file _constrained_layout.py.
match_submerged_margins()
matplotlib._constrained_layout.match_submerged_margins (layoutgrids, fig)
Make the margins that are submerged inside an Axes the same size.
This allows Axes that span two columns (or rows) that are offset
from one another to have the same size.
This gives the proper layout for something like::
    fig = plt.figure(constrained_layout=True)
    axs = fig.subplot_mosaic("AAAB\nCCDD")
Without this routine, the Axes D will be wider than C, because the
margin width between the two columns in C has no width by default,
whereas the margins between the two columns of D are set by the
width of the margin between A and B. However, obviously the user would
like C and D to be the same size, so we need to add constraints to these
"submerged" margins.
This routine makes all the interior margins the same, and the spacing
between the three columns in A and the two column in C are all set to the
margins between the two columns of D.
See test_constrained_layout::test_constrained_layout12 for an example.
Definition at line 499 of file _constrained_layout.py.
References match_submerged_margins().
Referenced by do_constrained_layout(), and match_submerged_margins().
reposition_axes()
matplotlib._constrained_layout.reposition_axes (layoutgrids, fig, renderer, * , w_pad = 0, h_pad = 0, hspace = 0, wspace = 0)
Reposition all the Axes based on the new inner bounding box.
Definition at line 649 of file _constrained_layout.py.
References reposition_axes(), and reposition_colorbar().
Referenced by do_constrained_layout(), and reposition_axes().
reposition_colorbar()
matplotlib._constrained_layout.reposition_colorbar (layoutgrids, cbax, renderer, * , offset = None)
Place the colorbar in its new place.
Parameters
----------
layoutgrids : dict
cbax : `~matplotlib.axes.Axes`
    Axes for the colorbar.
renderer : `~matplotlib.backend_bases.RendererBase` subclass.
    The renderer to use.
offset : array-like
    Offset the colorbar needs to be pushed to in order to
    account for multiple colorbars.
Definition at line 691 of file _constrained_layout.py.
References get_cb_parent_spans(), and get_pos_and_bbox().
Referenced by reposition_axes().
reset_margins()
matplotlib._constrained_layout.reset_margins (layoutgrids, fig)
Reset the margins in the layoutboxes of *fig*.
Margins are usually set as a minimum, so if the figure gets smaller
the minimum needs to be zero in order for it to grow again.
Definition at line 772 of file _constrained_layout.py.
References get_cb_parent_spans(), and reset_margins().
Referenced by do_constrained_layout(), and reset_margins().
Variable Documentation
_log
matplotlib._constrained_layout._log = logging.getLogger(__name__) protected
Definition at line 59 of file _constrained_layout.py.