Code Cloning Analysis: fontTools.ttLib.tables._n_a_m_e Namespace Reference
fontTools.ttLib.tables._n_a_m_e Namespace Reference
Classes
class NameRecord
class NameRecordVisitor
class table__n_a_m_e
Functions
makeName (string, nameID, platformID, platEncID, langID)
_makeWindowsName (name, nameID, language)
_makeMacName (name, nameID, language, font=None)
visit (visitor, obj, attr, value)
visit (visitor, obj)
visit (visitor, font, *args, **kwargs)
Variables
log = logging.getLogger(__name__)
str nameRecordFormat
nameRecordSize = sstruct.calcsize(nameRecordFormat)
dict _WINDOWS_LANGUAGES
dict _MAC_LANGUAGES
dict _WINDOWS_LANGUAGE_CODES
dict _MAC_LANGUAGE_CODES = {lang.lower(): code for code, lang in _MAC_LANGUAGES.items()}
dict _MAC_LANGUAGE_TO_SCRIPT
Function Documentation
_makeMacName()
fontTools.ttLib.tables._n_a_m_e._makeMacName (name, nameID, language, font = None) protected
Create a NameRecord for Apple platforms
'language' is an arbitrary IETF BCP 47 language identifier such
as 'en', 'de-CH', 'de-AT-1901', or 'fa-Latn'. When possible, we
create a Macintosh NameRecord that is understood by old applications
(platform ID 1 and an old-style Macintosh language enum). If this
is not possible, we create a Unicode NameRecord (platform ID 0)
whose language points to the font’s 'ltag' table. The latter
can encode any string in any language, but legacy applications
might not recognize the format (in which case they will ignore
those names).
'font' should be the TTFont for which you want to create a name.
If 'font' is None, we only return NameRecords for legacy Macintosh;
in that case, the result will be None for names that need to
be encoded with an 'ltag' table.
See the section “The language identifier” in Apple’s specification:
https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6name.html
Definition at line 444 of file _n_a_m_e.py.
References fontTools.ttLib.ttFont.newTable().
Referenced by fontTools.ttLib.tables._n_a_m_e.table__n_a_m_e.addMultilingualName(), and fontTools.ttLib.tables._n_a_m_e.table__n_a_m_e.findMultilingualName().
_makeWindowsName()
fontTools.ttLib.tables._n_a_m_e._makeWindowsName (name, nameID, language) protected
Create a NameRecord for the Microsoft Windows platform
'language' is an arbitrary IETF BCP 47 language identifier such
as 'en', 'de-CH', 'de-AT-1901', or 'fa-Latn'. If Microsoft Windows
does not support the desired language, the result will be None.
Future versions of fonttools might return a NameRecord for the
OpenType 'name' table format 1, but this is not implemented yet.
Definition at line 423 of file _n_a_m_e.py.
Referenced by fontTools.ttLib.tables._n_a_m_e.table__n_a_m_e.addMultilingualName(), and fontTools.ttLib.tables._n_a_m_e.table__n_a_m_e.findMultilingualName().
makeName()
fontTools.ttLib.tables._n_a_m_e.makeName (string, nameID, platformID, platEncID, langID)
Definition at line 411 of file _n_a_m_e.py.
visit() [1/3]
fontTools.ttLib.tables._n_a_m_e.visit (visitor, font, * args, ** kwargs)
Definition at line 1228 of file _n_a_m_e.py.
visit() [2/3]
fontTools.ttLib.tables._n_a_m_e.visit (visitor, obj)
Definition at line 1194 of file _n_a_m_e.py.
visit() [3/3]
fontTools.ttLib.tables._n_a_m_e.visit (visitor, obj, attr, value)
Definition at line 1189 of file _n_a_m_e.py.
Variable Documentation
_MAC_LANGUAGE_CODES
dict fontTools.ttLib.tables._n_a_m_e._MAC_LANGUAGE_CODES = {lang.lower(): code for code, lang in _MAC_LANGUAGES.items()} protected
Definition at line 1032 of file _n_a_m_e.py.
_MAC_LANGUAGE_TO_SCRIPT
dict fontTools.ttLib.tables._n_a_m_e._MAC_LANGUAGE_TO_SCRIPT protected
Definition at line 1047 of file _n_a_m_e.py.
_MAC_LANGUAGES
dict fontTools.ttLib.tables._n_a_m_e._MAC_LANGUAGES protected
Definition at line 906 of file _n_a_m_e.py.
_WINDOWS_LANGUAGE_CODES
dict fontTools.ttLib.tables._n_a_m_e._WINDOWS_LANGUAGE_CODES protected
Initial value:
=  {
    lang.lower(): code for code, lang in _WINDOWS_LANGUAGES.items()
}
Definition at line 1029 of file _n_a_m_e.py.
_WINDOWS_LANGUAGES
dict fontTools.ttLib.tables._n_a_m_e._WINDOWS_LANGUAGES protected
Definition at line 690 of file _n_a_m_e.py.
log
fontTools.ttLib.tables._n_a_m_e.log = logging.getLogger(__name__)
Definition at line 23 of file _n_a_m_e.py.
nameRecordFormat
str fontTools.ttLib.tables._n_a_m_e.nameRecordFormat
Initial value:
=  """
        >   # big endian
        platformID: H
        platEncID:  H
        langID:     H
        nameID:     H
        length:     H
        offset:     H
"""
Definition at line 25 of file _n_a_m_e.py.
nameRecordSize
fontTools.ttLib.tables._n_a_m_e.nameRecordSize = sstruct.calcsize(nameRecordFormat)
Definition at line 35 of file _n_a_m_e.py.