Code Cloning Analysis: sklearn.inspection._partial_dependence Namespace Reference
sklearn.inspection._partial_dependence Namespace Reference
Functions
_grid_from_X (X, percentiles, is_categorical, grid_resolution, custom_values)
_partial_dependence_recursion (est, grid, features)
_partial_dependence_brute (est, grid, features, X, response_method, sample_weight=None)
partial_dependence (estimator, X, features, *, sample_weight=None, categorical_features=None, feature_names=None, response_method="auto", percentiles=(0.05, 0.95), grid_resolution=100, custom_values=None, method="auto", kind="average")
Variables
list __all__
Detailed Description
Partial dependence plots for regression and classification models.
Function Documentation
_grid_from_X()
sklearn.inspection._partial_dependence._grid_from_X (X, percentiles, is_categorical, grid_resolution, custom_values) protected
Generate a grid of points based on the percentiles of X.
The grid is a cartesian product between the columns of ``values``. The
ith column of ``values`` consists in ``grid_resolution`` equally-spaced
points between the percentiles of the jth column of X.
If ``grid_resolution`` is bigger than the number of unique values in the
j-th column of X or if the feature is a categorical feature (by inspecting
`is_categorical`) , then those unique values will be used instead.
Parameters
----------
X : array-like of shape (n_samples, n_target_features)
    The data.
percentiles : tuple of float
    The percentiles which are used to construct the extreme values of
    the grid. Must be in [0, 1].
is_categorical : list of bool
    For each feature, tells whether it is categorical or not. If a feature
    is categorical, then the values used will be the unique ones
    (i.e. categories) instead of the percentiles.
grid_resolution : int
    The number of equally spaced points to be placed on the grid for each
    feature.
custom_values: dict
    Mapping from column index of X to an array-like of values where
    the partial dependence should be calculated for that feature
Returns
-------
grid : ndarray of shape (n_points, n_target_features)
    A value for each feature at each point in the grid. ``n_points`` is
    always ``<= grid_resolution ** X.shape[1]``.
values : list of 1d ndarrays
    The values with which the grid has been created. The size of each
    array ``values[j]`` is either ``grid_resolution``, the number of
    unique values in ``X[:, j]``, if j is not in ``custom_range``.
    If j is in ``custom_range``, then it is the length of ``custom_range[j]``.
Definition at line 40 of file _partial_dependence.py.
Referenced by partial_dependence().
_partial_dependence_brute()
sklearn.inspection._partial_dependence._partial_dependence_brute (est, grid, features, X, response_method, sample_weight = None) protected
Calculate partial dependence via the brute force method.
The brute method explicitly averages the predictions of an estimator over a
grid of feature values.
For each `grid` value, all the samples from `X` have their variables of
interest replaced by that specific `grid` value. The predictions are then made
and averaged across the samples.
This method is slower than the `'recursion'`
(:func:`~sklearn.inspection._partial_dependence._partial_dependence_recursion`)
version for estimators with this second option. However, with the `'brute'`
force method, the average will be done with the given `X` and not the `X`
used during training, as it is done in the `'recursion'` version. Therefore
the average can always accept `sample_weight` (even when the estimator was
fitted without).
Parameters
----------
est : BaseEstimator
    A fitted estimator object implementing :term:`predict`,
    :term:`predict_proba`, or :term:`decision_function`.
    Multioutput-multiclass classifiers are not supported.
grid : array-like of shape (n_points, n_target_features)
    The grid of feature values for which the partial dependence is calculated.
    Note that `n_points` is the number of points in the grid and `n_target_features`
    is the number of features you are doing partial dependence at.
features : array-like of {int, str}
    The feature (e.g. `[0]`) or pair of interacting features
    (e.g. `[(0, 1)]`) for which the partial dependency should be computed.
X : array-like of shape (n_samples, n_features)
    `X` is used to generate values for the complement features. That is, for
    each value in `grid`, the method will average the prediction of each
    sample from `X` having that grid value for `features`.
response_method : {'auto', 'predict_proba', 'decision_function'}, \
        default='auto'
    Specifies whether to use :term:`predict_proba` or
    :term:`decision_function` as the target response. For regressors
    this parameter is ignored and the response is always the output of
    :term:`predict`. By default, :term:`predict_proba` is tried first
    and we revert to :term:`decision_function` if it doesn't exist.
sample_weight : array-like of shape (n_samples,), default=None
    Sample weights are used to calculate weighted means when averaging the
    model output. If `None`, then samples are equally weighted. Note that
    `sample_weight` does not change the individual predictions.
Returns
-------
averaged_predictions : array-like of shape (n_targets, n_points)
    The averaged predictions for the given `grid` of features values.
    Note that `n_targets` is the number of targets (e.g. 1 for binary
    classification, `n_tasks` for multi-output regression, and `n_classes` for
    multiclass classification) and `n_points` is the number of points in the `grid`.
predictions : array-like
    The predictions for the given `grid` of features values over the samples
    from `X`. For non-multioutput regression and binary classification the
    shape is `(n_instances, n_points)` and for multi-output regression and
    multiclass classification the shape is `(n_targets, n_instances, n_points)`,
    where `n_targets` is the number of targets (`n_tasks` for multi-output
    regression, and `n_classes` for multiclass classification), `n_instances`
    is the number of instances in `X`, and `n_points` is the number of points
    in the `grid`.
Definition at line 218 of file _partial_dependence.py.
Referenced by partial_dependence().
_partial_dependence_recursion()
sklearn.inspection._partial_dependence._partial_dependence_recursion (est, grid, features) protected
Calculate partial dependence via the recursion method.
The recursion method is in particular enabled for tree-based estimators.
For each `grid` value, a weighted tree traversal is performed: if a split node
involves an input feature of interest, the corresponding left or right branch
is followed; otherwise both branches are followed, each branch being weighted
by the fraction of training samples that entered that branch. Finally, the
partial dependence is given by a weighted average of all the visited leaves
values.
This method is more efficient in terms of speed than the `'brute'` method
(:func:`~sklearn.inspection._partial_dependence._partial_dependence_brute`).
However, here, the partial dependence computation is done explicitly with the
`X` used during training of `est`.
Parameters
----------
est : BaseEstimator
    A fitted estimator object implementing :term:`predict` or
    :term:`decision_function`. Multioutput-multiclass classifiers are not
    supported. Note that `'recursion'` is only supported for some tree-based
    estimators (namely
    :class:`~sklearn.ensemble.GradientBoostingClassifier`,
    :class:`~sklearn.ensemble.GradientBoostingRegressor`,
    :class:`~sklearn.ensemble.HistGradientBoostingClassifier`,
    :class:`~sklearn.ensemble.HistGradientBoostingRegressor`,
    :class:`~sklearn.tree.DecisionTreeRegressor`,
    :class:`~sklearn.ensemble.RandomForestRegressor`,
    ).
grid : array-like of shape (n_points, n_target_features)
    The grid of feature values for which the partial dependence is calculated.
    Note that `n_points` is the number of points in the grid and `n_target_features`
    is the number of features you are doing partial dependence at.
features : array-like of {int, str}
    The feature (e.g. `[0]`) or pair of interacting features
    (e.g. `[(0, 1)]`) for which the partial dependency should be computed.
Returns
-------
averaged_predictions : array-like of shape (n_targets, n_points)
    The averaged predictions for the given `grid` of features values.
    Note that `n_targets` is the number of targets (e.g. 1 for binary
    classification, `n_tasks` for multi-output regression, and `n_classes` for
    multiclass classification) and `n_points` is the number of points in the `grid`.
Definition at line 160 of file _partial_dependence.py.
Referenced by partial_dependence().
partial_dependence()
sklearn.inspection._partial_dependence.partial_dependence (estimator, X, features, * , sample_weight = None, categorical_features = None, feature_names = None, response_method = "auto", percentiles = (0.05, 0.95), grid_resolution = 100, custom_values = None, method = "auto", kind = "average")
Partial dependence of ``features``.
Partial dependence of a feature (or a set of features) corresponds to
the average response of an estimator for each possible value of the
feature.
Read more in
:ref:`sphx_glr_auto_examples_inspection_plot_partial_dependence.py`
and the :ref:`User Guide <partial_dependence>`.
.. warning::
    For :class:`~sklearn.ensemble.GradientBoostingClassifier` and
    :class:`~sklearn.ensemble.GradientBoostingRegressor`, the
    `'recursion'` method (used by default) will not account for the `init`
    predictor of the boosting process. In practice, this will produce
    the same values as `'brute'` up to a constant offset in the target
    response, provided that `init` is a constant estimator (which is the
    default). However, if `init` is not a constant estimator, the
    partial dependence values are incorrect for `'recursion'` because the
    offset will be sample-dependent. It is preferable to use the `'brute'`
    method. Note that this only applies to
    :class:`~sklearn.ensemble.GradientBoostingClassifier` and
    :class:`~sklearn.ensemble.GradientBoostingRegressor`, not to
    :class:`~sklearn.ensemble.HistGradientBoostingClassifier` and
    :class:`~sklearn.ensemble.HistGradientBoostingRegressor`.
Parameters
----------
estimator : BaseEstimator
    A fitted estimator object implementing :term:`predict`,
    :term:`predict_proba`, or :term:`decision_function`.
    Multioutput-multiclass classifiers are not supported.
X : {array-like, sparse matrix or dataframe} of shape (n_samples, n_features)
    ``X`` is used to generate a grid of values for the target
    ``features`` (where the partial dependence will be evaluated), and
    also to generate values for the complement features when the
    `method` is 'brute'.
features : array-like of {int, str, bool} or int or str
    The feature (e.g. `[0]`) or pair of interacting features
    (e.g. `[(0, 1)]`) for which the partial dependency should be computed.
sample_weight : array-like of shape (n_samples,), default=None
    Sample weights are used to calculate weighted means when averaging the
    model output. If `None`, then samples are equally weighted. If
    `sample_weight` is not `None`, then `method` will be set to `'brute'`.
    Note that `sample_weight` is ignored for `kind='individual'`.
    .. versionadded:: 1.3
categorical_features : array-like of shape (n_features,) or shape \
        (n_categorical_features,), dtype={bool, int, str}, default=None
    Indicates the categorical features.
    - `None`: no feature will be considered categorical;
    - boolean array-like: boolean mask of shape `(n_features,)`
        indicating which features are categorical. Thus, this array has
        the same shape has `X.shape[1]`;
    - integer or string array-like: integer indices or strings
        indicating categorical features.
    .. versionadded:: 1.2
feature_names : array-like of shape (n_features,), dtype=str, default=None
    Name of each feature; `feature_names[i]` holds the name of the feature
    with index `i`.
    By default, the name of the feature corresponds to their numerical
    index for NumPy array and their column name for pandas dataframe.
    .. versionadded:: 1.2
response_method : {'auto', 'predict_proba', 'decision_function'}, \
        default='auto'
    Specifies whether to use :term:`predict_proba` or
    :term:`decision_function` as the target response. For regressors
    this parameter is ignored and the response is always the output of
    :term:`predict`. By default, :term:`predict_proba` is tried first
    and we revert to :term:`decision_function` if it doesn't exist. If
    ``method`` is 'recursion', the response is always the output of
    :term:`decision_function`.
percentiles : tuple of float, default=(0.05, 0.95)
    The lower and upper percentile used to create the extreme values
    for the grid. Must be in [0, 1].
    This parameter is overridden by `custom_values` if that parameter is set.
grid_resolution : int, default=100
    The number of equally spaced points on the grid, for each target
    feature.
    This parameter is overridden by `custom_values` if that parameter is set.
custom_values : dict
    A dictionary mapping the index of an element of `features` to an array
    of values where the partial dependence should be calculated
    for that feature. Setting a range of values for a feature overrides
    `grid_resolution` and `percentiles`.
    See :ref:`how to use partial_dependence
    <plt_partial_dependence_custom_values>` for an example of how this parameter can
    be used.
    .. versionadded:: 1.7
method : {'auto', 'recursion', 'brute'}, default='auto'
    The method used to calculate the averaged predictions:
    - `'recursion'` is only supported for some tree-based estimators
      (namely
      :class:`~sklearn.ensemble.GradientBoostingClassifier`,
      :class:`~sklearn.ensemble.GradientBoostingRegressor`,
      :class:`~sklearn.ensemble.HistGradientBoostingClassifier`,
      :class:`~sklearn.ensemble.HistGradientBoostingRegressor`,
      :class:`~sklearn.tree.DecisionTreeRegressor`,
      :class:`~sklearn.ensemble.RandomForestRegressor`,
      ) when `kind='average'`.
      This is more efficient in terms of speed.
      With this method, the target response of a
      classifier is always the decision function, not the predicted
      probabilities. Since the `'recursion'` method implicitly computes
      the average of the Individual Conditional Expectation (ICE) by
      design, it is not compatible with ICE and thus `kind` must be
      `'average'`.
    - `'brute'` is supported for any estimator, but is more
      computationally intensive.
    - `'auto'`: the `'recursion'` is used for estimators that support it,
      and `'brute'` is used otherwise. If `sample_weight` is not `None`,
      then `'brute'` is used regardless of the estimator.
    Please see :ref:`this note <pdp_method_differences>` for
    differences between the `'brute'` and `'recursion'` method.
kind : {'average', 'individual', 'both'}, default='average'
    Whether to return the partial dependence averaged across all the
    samples in the dataset or one value per sample or both.
    See Returns below.
    Note that the fast `method='recursion'` option is only available for
    `kind='average'` and `sample_weights=None`. Computing individual
    dependencies and doing weighted averages requires using the slower
    `method='brute'`.
    .. versionadded:: 0.24
Returns
-------
predictions : :class:`~sklearn.utils.Bunch`
    Dictionary-like object, with the following attributes.
    individual : ndarray of shape (n_outputs, n_instances, \
            len(values[0]), len(values[1]), ...)
        The predictions for all the points in the grid for all
        samples in X. This is also known as Individual
        Conditional Expectation (ICE).
        Only available when `kind='individual'` or `kind='both'`.
    average : ndarray of shape (n_outputs, len(values[0]), \
            len(values[1]), ...)
        The predictions for all the points in the grid, averaged
        over all samples in X (or over the training data if
        `method` is 'recursion').
        Only available when `kind='average'` or `kind='both'`.
    grid_values : seq of 1d ndarrays
        The values with which the grid has been created. The generated
        grid is a cartesian product of the arrays in `grid_values` where
        `len(grid_values) == len(features)`. The size of each array
        `grid_values[j]` is either `grid_resolution`, or the number of
        unique values in `X[:, j]`, whichever is smaller.
        .. versionadded:: 1.3
    `n_outputs` corresponds to the number of classes in a multi-class
    setting, or to the number of tasks for multi-output regression.
    For classical regression and binary classification `n_outputs==1`.
    `n_values_feature_j` corresponds to the size `grid_values[j]`.
See Also
--------
PartialDependenceDisplay.from_estimator : Plot Partial Dependence.
PartialDependenceDisplay : Partial Dependence visualization.
Examples
--------
>>> X = [[0, 0, 2], [1, 0, 0]]
>>> y = [0, 1]
>>> from sklearn.ensemble import GradientBoostingClassifier
>>> gb = GradientBoostingClassifier(random_state=0).fit(X, y)
>>> partial_dependence(gb, features=[0], X=X, percentiles=(0, 1),
...                    grid_resolution=2) # doctest: +SKIP
(array([[-4.52,  4.52]]), [array([ 0.,  1.])])
Definition at line 367 of file _partial_dependence.py.
References _grid_from_X(), _partial_dependence_brute(), and _partial_dependence_recursion().
Variable Documentation
__all__
list sklearn.inspection._partial_dependence.__all__ private
Initial value:
=  [
    "partial_dependence",
]
Definition at line 35 of file _partial_dependence.py.