Code Cloning Analysis: scipy.signal.tests.test_peak_finding.TestFindPeaksCwt Class Reference
scipy.signal.tests.test_peak_finding.TestFindPeaksCwt Class Reference
Public Member Functions
test_find_peaks_exact (self)
test_find_peaks_withnoise (self)
test_find_peaks_nopeak (self)
test_find_peaks_with_non_default_wavelets (self)
test_find_peaks_window_size (self)
test_find_peaks_with_one_width (self)
Detailed Description
Definition at line 794 of file test_peak_finding.py.
Member Function Documentation
test_find_peaks_exact()
scipy.signal.tests.test_peak_finding.TestFindPeaksCwt.test_find_peaks_exact (self)
Generate a series of gaussians and attempt to find the peak locations.
Definition at line 796 of file test_peak_finding.py.
References scipy.signal._peak_finding.find_peaks_cwt().
test_find_peaks_nopeak()
scipy.signal.tests.test_peak_finding.TestFindPeaksCwt.test_find_peaks_nopeak (self)
Verify that no peak is found in
data that's just noise.
Definition at line 831 of file test_peak_finding.py.
References scipy.signal._peak_finding.find_peaks_cwt().
test_find_peaks_window_size()
scipy.signal.tests.test_peak_finding.TestFindPeaksCwt.test_find_peaks_window_size (self)
Verify that window_size is passed correctly to private function and
affects the result.
Definition at line 851 of file test_peak_finding.py.
References scipy.signal._peak_finding.find_peaks_cwt().
test_find_peaks_with_non_default_wavelets()
scipy.signal.tests.test_peak_finding.TestFindPeaksCwt.test_find_peaks_with_non_default_wavelets (self)
Definition at line 844 of file test_peak_finding.py.
test_find_peaks_with_one_width()
scipy.signal.tests.test_peak_finding.TestFindPeaksCwt.test_find_peaks_with_one_width (self)
Verify that the `width` argument
in `find_peaks_cwt` can be a float
Definition at line 877 of file test_peak_finding.py.
References scipy.signal._peak_finding.find_peaks_cwt().
test_find_peaks_withnoise()
scipy.signal.tests.test_peak_finding.TestFindPeaksCwt.test_find_peaks_withnoise (self)
Verify that peak locations are (approximately) found
for a series of gaussians with added noise.
Definition at line 809 of file test_peak_finding.py.
References scipy.signal._peak_finding.find_peaks_cwt().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/signal/tests/test_peak_finding.py