Code Cloning Analysis: matplotlib.tests.test_category.FakeAxis Class Reference
matplotlib.tests.test_category.FakeAxis Class Reference
Public Member Functions
__init__ (self, units)
Public Attributes
units = units
Detailed Description
Definition at line 60 of file test_category.py.
Constructor & Destructor Documentation
__init__()
matplotlib.tests.test_category.FakeAxis.__init__ (self, units)
Definition at line 61 of file test_category.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Data Documentation
units
matplotlib.tests.test_category.FakeAxis.units = units
Definition at line 62 of file test_category.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/tests/test_category.py