Code Cloning Analysis: fontTools.pens.ttGlyphPen.TTGlyphPointPen Class Reference
fontTools.pens.ttGlyphPen.TTGlyphPointPen Class Reference
Public Member Functions
None init (self)
None beginPath (self, Optional[str] identifier=None, **Any kwargs)
None endPath (self)
None addPoint (self, Tuple[float, float] pt, Optional[str] segmentType=None, bool smooth=False, Optional[str] name=None, Optional[str] identifier=None, **Any kwargs)
Public Member Functions inherited from fontTools.pens.ttGlyphPen._TTGlyphBasePen
None __init__ (self, Optional[Dict[str, Any]] glyphSet, bool handleOverflowingTransforms=True)
None addComponent (self, str baseGlyphName, Tuple[float, float, float, float, float, float] transformation, Optional[str] identifier=None, **Any kwargs)
Glyph glyph (self, int componentFlags=0x04, bool dropImpliedOnCurves=False, *, Callable[[float], int] round=otRound)
Public Member Functions inherited from fontTools.misc.loggingTools.LogMixin
log (self)
Public Member Functions inherited from fontTools.pens.pointPen.AbstractPointPen
None addComponent (self, str baseGlyphName, Tuple[float, float, float, float, float, float] transformation, Optional[str] identifier=None, **Any kwargs)
None addVarComponent (self, str glyphName, DecomposedTransform transformation, Dict[str, float] location, Optional[str] identifier=None, **Any kwargs)
Static Public Attributes
transformPen = TransformPointPen
Protected Member Functions
bool _isClosed (self)
Protected Member Functions inherited from fontTools.pens.ttGlyphPen._TTGlyphBasePen
_decompose (self, str glyphName, Tuple[float, float, float, float, float, float] transformation)
_buildComponents (self, componentFlags)
Protected Attributes
_currentContourStartIndex = None
Protected Attributes inherited from fontTools.misc.loggingTools.LogMixin
_log = logging.getLogger(name)
Additional Inherited Members
Public Attributes inherited from fontTools.pens.ttGlyphPen._TTGlyphBasePen
glyphSet = glyphSet
handleOverflowingTransforms = handleOverflowingTransforms
drawMethod
list points = []
list endPts = []
list types = []
list components = []
Detailed Description
Point pen used for drawing to a TrueType glyph.
This pen can be used to construct or modify glyphs in a TrueType format
font. After using the pen to draw, use the ``.glyph()`` method to retrieve
a :py:class:`~._g_l_y_f.Glyph` object representing the glyph.
Definition at line 255 of file ttGlyphPen.py.
Member Function Documentation
_isClosed()
bool fontTools.pens.ttGlyphPen.TTGlyphPointPen._isClosed (self) protected
Check if the current path is closed.
Reimplemented from fontTools.pens.ttGlyphPen._TTGlyphBasePen.
Definition at line 271 of file ttGlyphPen.py.
References _currentContourStartIndex.
addPoint()
None fontTools.pens.ttGlyphPen.TTGlyphPointPen.addPoint (self, Tuple[float, float] pt, Optional[str] segmentType = None, bool smooth = False, Optional[str] name = None, Optional[str] identifier = None, **Any kwargs)
Add a point to the current sub path.
Reimplemented from fontTools.pens.pointPen.AbstractPointPen.
Definition at line 310 of file ttGlyphPen.py.
References fontTools.pens.ttGlyphPen._TTGlyphBasePen._isClosed(), fontTools.pens.ttGlyphPen._TTGlyphBasePen.points, and fontTools.pens.ttGlyphPen._TTGlyphBasePen.types.
beginPath()
None fontTools.pens.ttGlyphPen.TTGlyphPointPen.beginPath (self, Optional[str] identifier = None, **Any kwargs)
Start a new sub path.
Reimplemented from fontTools.pens.pointPen.AbstractPointPen.
Definition at line 274 of file ttGlyphPen.py.
References _currentContourStartIndex, fontTools.pens.ttGlyphPen._TTGlyphBasePen._isClosed(), and fontTools.pens.ttGlyphPen._TTGlyphBasePen.points.
endPath()
None fontTools.pens.ttGlyphPen.TTGlyphPointPen.endPath (self)
End the current sub path.
Reimplemented from fontTools.pens.pointPen.AbstractPointPen.
Definition at line 282 of file ttGlyphPen.py.
References _currentContourStartIndex, fontTools.pens.ttGlyphPen._TTGlyphBasePen._isClosed(), fontTools.pens.ttGlyphPen._TTGlyphBasePen.endPts, fontTools.pens.ttGlyphPen._TTGlyphBasePen.points, and fontTools.pens.ttGlyphPen._TTGlyphBasePen.types.
init()
None fontTools.pens.ttGlyphPen.TTGlyphPointPen.init (self)
Reimplemented from fontTools.pens.ttGlyphPen._TTGlyphBasePen.
Definition at line 267 of file ttGlyphPen.py.
Member Data Documentation
_currentContourStartIndex
fontTools.pens.ttGlyphPen.TTGlyphPointPen._currentContourStartIndex = None protected
Definition at line 269 of file ttGlyphPen.py.
Referenced by _isClosed(), beginPath(), and endPath().
transformPen
fontTools.pens.ttGlyphPen.TTGlyphPointPen.transformPen = TransformPointPen static
Definition at line 265 of file ttGlyphPen.py.
Referenced by fontTools.pens.ttGlyphPen._TTGlyphBasePen.__init__().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/pens/ttGlyphPen.py