Code Cloning Analysis: numpy.core.tests.test_multiarray.TestStats Class Reference
numpy.core.tests.test_multiarray.TestStats Class Reference
Public Member Functions
setup_method (self)
test_python_type (self)
test_keepdims (self)
test_out (self)
test_dtype_from_input (self)
test_dtype_from_dtype (self)
test_ddof (self)
test_ddof_too_big (self)
test_empty (self)
test_mean_values (self)
test_mean_float16 (self)
test_mean_axis_error (self)
test_mean_where (self)
test_var_values (self)
test_var_complex_values (self, complex_dtype, ndec)
test_var_dimensions (self)
test_var_complex_byteorder (self)
test_var_axis_error (self)
test_var_where (self)
test_std_values (self)
test_std_where (self)
test_subclass (self)
Public Attributes
rmat = np.random.random((4, 5))
int cmat = self.rmat + 1j * self.rmat
omat = np.array([Decimal(repr(r)) for r in self.rmat.flat])
info = getattr(obj, "info", '')
Static Public Attributes
list funcs = [_mean, _var, _std]
Detailed Description
Definition at line 6065 of file test_multiarray.py.
Member Function Documentation
setup_method()
numpy.core.tests.test_multiarray.TestStats.setup_method (self)
Definition at line 6069 of file test_multiarray.py.
test_ddof()
numpy.core.tests.test_multiarray.TestStats.test_ddof (self)
Definition at line 6182 of file test_multiarray.py.
test_ddof_too_big()
numpy.core.tests.test_multiarray.TestStats.test_ddof_too_big (self)
Definition at line 6196 of file test_multiarray.py.
test_dtype_from_dtype()
numpy.core.tests.test_multiarray.TestStats.test_dtype_from_dtype (self)
Definition at line 6155 of file test_multiarray.py.
test_dtype_from_input()
numpy.core.tests.test_multiarray.TestStats.test_dtype_from_input (self)
Definition at line 6106 of file test_multiarray.py.
test_empty()
numpy.core.tests.test_multiarray.TestStats.test_empty (self)
Definition at line 6207 of file test_multiarray.py.
test_keepdims()
numpy.core.tests.test_multiarray.TestStats.test_keepdims (self)
Definition at line 6082 of file test_multiarray.py.
test_mean_axis_error()
numpy.core.tests.test_multiarray.TestStats.test_mean_axis_error (self)
Definition at line 6237 of file test_multiarray.py.
test_mean_float16()
numpy.core.tests.test_multiarray.TestStats.test_mean_float16 (self)
Definition at line 6232 of file test_multiarray.py.
test_mean_values()
numpy.core.tests.test_multiarray.TestStats.test_mean_values (self)
Definition at line 6221 of file test_multiarray.py.
test_mean_where()
numpy.core.tests.test_multiarray.TestStats.test_mean_where (self)
Definition at line 6243 of file test_multiarray.py.
test_out()
numpy.core.tests.test_multiarray.TestStats.test_out (self)
Definition at line 6093 of file test_multiarray.py.
test_python_type()
numpy.core.tests.test_multiarray.TestStats.test_python_type (self)
Definition at line 6076 of file test_multiarray.py.
test_std_values()
numpy.core.tests.test_multiarray.TestStats.test_std_values (self)
Definition at line 6364 of file test_multiarray.py.
test_std_where()
numpy.core.tests.test_multiarray.TestStats.test_std_where (self)
Definition at line 6371 of file test_multiarray.py.
test_subclass()
numpy.core.tests.test_multiarray.TestStats.test_subclass (self)
Definition at line 6415 of file test_multiarray.py.
test_var_axis_error()
numpy.core.tests.test_multiarray.TestStats.test_var_axis_error (self)
Definition at line 6321 of file test_multiarray.py.
test_var_complex_byteorder()
numpy.core.tests.test_multiarray.TestStats.test_var_complex_byteorder (self)
Definition at line 6314 of file test_multiarray.py.
test_var_complex_values()
numpy.core.tests.test_multiarray.TestStats.test_var_complex_values (self, complex_dtype, ndec)
Definition at line 6293 of file test_multiarray.py.
test_var_dimensions()
numpy.core.tests.test_multiarray.TestStats.test_var_dimensions (self)
Definition at line 6303 of file test_multiarray.py.
test_var_values()
numpy.core.tests.test_multiarray.TestStats.test_var_values (self)
Definition at line 6279 of file test_multiarray.py.
test_var_where()
numpy.core.tests.test_multiarray.TestStats.test_var_where (self)
Definition at line 6327 of file test_multiarray.py.
Member Data Documentation
cmat
numpy.core.tests.test_multiarray.TestStats.cmat = self.rmat + 1j * self.rmat
Definition at line 6072 of file test_multiarray.py.
funcs
list numpy.core.tests.test_multiarray.TestStats.funcs = [_mean, _var, _std] static
Definition at line 6067 of file test_multiarray.py.
Referenced by numpy.core.tests.test_umath.TestComplexFunctions.test_loss_of_precision().
info
numpy.core.tests.test_multiarray.TestStats.info = getattr(obj, "info", '')
Definition at line 6424 of file test_multiarray.py.
Referenced by pandas.core.frame.DataFrame.__repr__(), PIL.BmpImagePlugin.BmpImageFile._bitmap(), joblib.memory.MemorizedFunc._cached_call(), pandas.io.pytables.Table._create_axes(), pandas.io.formats.info._DataFrameInfoPrinter._create_table_builder(), pandas.io.formats.info._SeriesInfoPrinter._create_table_builder(), pandas.io.pytables.Table._read_axes(), pandas.core.frame.DataFrame._repr_html_(), PIL.Image.Image._repr_jpeg_(), PIL.Image.Image.apply_transparency(), PIL.Image.Image.close(), pandas.io.formats.info._DataFrameInfoPrinter.col_count(), pandas.io.formats.info._DataFrameTableBuilder.col_count(), pandas.io.formats.info._DataFrameTableBuilder.data(), pandas.io.formats.info._SeriesTableBuilder.data(), pandas.io.formats.info._TableBuilderAbstract.display_memory_usage(), PIL.JpegImagePlugin.JpegImageFile.draft(), pandas.io.formats.info._TableBuilderAbstract.dtype_counts(), pandas.io.formats.info._TableBuilderAbstract.dtypes(), pandas.io.pytables.Table.get_attrs(), pandas.io.formats.info._TableBuilderAbstract.get_lines(), pandas.io.pytables.AppendableFrameTable.get_object(), PIL.Image.Image.getexif(), PIL.Image.Image.getxmp(), PIL.Image.Image.has_transparency_data(), pandas.io.formats.info._DataFrameTableBuilder.ids(), pip._vendor.distlib.wheel.Wheel.install(), PIL.AvifImagePlugin.AvifImageFile.load(), PIL.IcoImagePlugin.IcoImageFile.load(), PIL.Image.Image.load(), PIL.WebPImagePlugin.WebPImageFile.load(), PIL.WmfImagePlugin.WmfStubImageFile.load(), pandas.io.formats.info._TableBuilderAbstract.memory_usage_string(), pandas.io.pytables.Table.read_column(), pip._internal.models.direct_url.DirectUrl.redacted_url(), PIL.Image.Image.remap_palette(), PIL.GifImagePlugin.GifImageFile.seek(), PIL.MpoImagePlugin.MpoImageFile.seek(), PIL.TiffImagePlugin.TiffImageFile.seek(), pandas.io.pytables.Table.set_attrs(), PIL.Image.Image.transform(), and pandas.io.pytables.Table.validate_data_columns().
omat
numpy.core.tests.test_multiarray.TestStats.omat = np.array([Decimal(repr(r)) for r in self.rmat.flat])
Definition at line 6073 of file test_multiarray.py.
rmat
numpy.core.tests.test_multiarray.TestStats.rmat = np.random.random((4, 5))
Definition at line 6071 of file test_multiarray.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/core/tests/test_multiarray.py