Code Cloning Analysis: joblib.parallel Namespace Reference
joblib.parallel Namespace Reference
Classes
class BatchCompletionCallBack
class BatchedCalls
class Parallel
class parallel_backend
class parallel_config
Functions
_register_dask ()
_get_config_param (param, context_config, key)
get_active_backend (prefer=default_parallel_config["prefer"], require=default_parallel_config["require"], verbose=default_parallel_config["verbose"])
_get_active_backend (prefer=default_parallel_config["prefer"], require=default_parallel_config["require"], verbose=default_parallel_config["verbose"])
cpu_count (only_physical_cores=False)
CPU count that works also when multiprocessing has been disabled via the JOBLIB_MULTIPROCESSING environment variable.
_verbosity_filter (index, verbose)
For verbosity.
delayed (function)
register_parallel_backend (name, factory, make_default=False)
effective_n_jobs (n_jobs=-1)
Variables
str DEFAULT_BACKEND = "threading"
str DEFAULT_THREAD_BACKEND = "threading"
str DEFAULT_PROCESS_BACKEND = "threading"
dict MAYBE_AVAILABLE_BACKENDS = {"multiprocessing", "loky"}
_backend = threading.local()
dict EXTERNAL_BACKENDS
dict default_parallel_config
tuple VALID_BACKEND_HINTS = ("processes", "threads", None)
tuple VALID_BACKEND_CONSTRAINTS = ("sharedmem", None)
DEFAULT_MP_CONTEXT = None
method = os.environ.get("JOBLIB_START_METHOD", "").strip() or None
str TASK_DONE = "Done"
str TASK_ERROR = "Error"
str TASK_PENDING = "Pending"
Detailed Description
Helpers for embarrassingly parallel code.
Function Documentation
_get_active_backend()
joblib.parallel._get_active_backend (prefer = default_parallel_config["prefer"], require = default_parallel_config["require"], verbose = default_parallel_config["verbose"]) protected
Return the active default backend
Definition at line 141 of file parallel.py.
References _get_config_param().
Referenced by get_active_backend().
_get_config_param()
joblib.parallel._get_config_param (param, context_config, key) protected
Return the value of a parallel config parameter
Explicitly setting it in Parallel has priority over setting in a
parallel_(config/backend) context manager.
Definition at line 111 of file parallel.py.
Referenced by _get_active_backend(), and get_active_backend().
_register_dask()
joblib.parallel._register_dask () protected
Register Dask Backend if called with parallel_config(backend="dask")
Definition at line 72 of file parallel.py.
References register_parallel_backend().
_verbosity_filter()
joblib.parallel._verbosity_filter (index, verbose) protected
For verbosity.
Returns False for indices increasingly apart, the distance
depending on the value of verbose.
We use a lag increasing as the square of index
Definition at line 655 of file parallel.py.
Referenced by joblib.parallel.Parallel.print_progress().
cpu_count()
joblib.parallel.cpu_count (only_physical_cores = False)
CPU count that works also when multiprocessing has been disabled via the JOBLIB_MULTIPROCESSING environment variable.
Return the number of CPUs.
This delegates to loky.cpu_count that takes into account additional
constraints such as Linux CFS scheduler quotas (typically set by container
runtimes such as docker) and CPU affinity (for instance using the taskset
command on Linux).
Parameters
----------
only_physical_cores : boolean, default=False
    If True, does not take hyperthreading / SMT logical cores into account.
Definition at line 631 of file parallel.py.
delayed()
joblib.parallel.delayed (function)
Decorator used to capture the arguments of a function.
Definition at line 674 of file parallel.py.
effective_n_jobs()
joblib.parallel.effective_n_jobs (n_jobs = -1)
Determine the number of jobs that can actually run in parallel
n_jobs is the number of workers requested by the callers. Passing n_jobs=-1
means requesting all available workers for instance matching the number of
CPU cores on the worker host(s).
This method should return a guesstimate of the number of workers that can
actually perform work concurrently with the currently enabled default
backend. The primary use case is to make it possible for the caller to know
in how many chunks to slice the work.
In general working on larger data chunks is more efficient (less scheduling
overhead and better use of CPU cache prefetching heuristics) as long as all
the workers have enough work to do.
Warning: this function is experimental and subject to change in a future
version of joblib.
.. versionadded:: 0.10
Definition at line 927 of file parallel.py.
References get_active_backend().
Referenced by joblib.parallel.Parallel._initialize_backend().
get_active_backend()
joblib.parallel.get_active_backend (prefer = default_parallel_config["prefer"], require = default_parallel_config["require"], verbose = default_parallel_config["verbose"])
Return the active default backend
Definition at line 130 of file parallel.py.
References _get_active_backend(), and _get_config_param().
Referenced by effective_n_jobs().
register_parallel_backend()
joblib.parallel.register_parallel_backend (name, factory, make_default = False)
Register a new Parallel backend factory.
The new backend can then be selected by passing its name as the backend
argument to the :class:`~Parallel` class. Moreover, the default backend can
be overwritten globally by setting make_default=True.
The factory can be any callable that takes no argument and return an
instance of ``ParallelBackendBase``.
Warning: this function is experimental and subject to change in a future
version of joblib.
.. versionadded:: 0.10
Definition at line 906 of file parallel.py.
Referenced by _register_dask().
Variable Documentation
_backend
joblib.parallel._backend = threading.local() protected
Definition at line 69 of file parallel.py.
DEFAULT_BACKEND
str joblib.parallel.DEFAULT_BACKEND = "threading"
Definition at line 51 of file parallel.py.
DEFAULT_MP_CONTEXT
joblib.parallel.DEFAULT_MP_CONTEXT = None
Definition at line 579 of file parallel.py.
default_parallel_config
dict joblib.parallel.default_parallel_config
Initial value:
=  {
    "backend": _Sentinel(default_value=None),
    "n_jobs": _Sentinel(default_value=None),
    "verbose": _Sentinel(default_value=0),
    "temp_folder": _Sentinel(default_value=None),
    "max_nbytes": _Sentinel(default_value="1M"),
    "mmap_mode": _Sentinel(default_value="r"),
    "prefer": _Sentinel(default_value=None),
    "require": _Sentinel(default_value=None),
}
Definition at line 95 of file parallel.py.
DEFAULT_PROCESS_BACKEND
str joblib.parallel.DEFAULT_PROCESS_BACKEND = "threading"
Definition at line 53 of file parallel.py.
DEFAULT_THREAD_BACKEND
str joblib.parallel.DEFAULT_THREAD_BACKEND = "threading"
Definition at line 52 of file parallel.py.
EXTERNAL_BACKENDS
dict joblib.parallel.EXTERNAL_BACKENDS
Initial value:
=  {
    "dask": _register_dask,
}
Definition at line 88 of file parallel.py.
MAYBE_AVAILABLE_BACKENDS
dict joblib.parallel.MAYBE_AVAILABLE_BACKENDS = {"multiprocessing", "loky"}
Definition at line 55 of file parallel.py.
method
joblib.parallel.method = os.environ.get("JOBLIB_START_METHOD", "").strip() or None
Definition at line 581 of file parallel.py.
TASK_DONE
str joblib.parallel.TASK_DONE = "Done"
Definition at line 623 of file parallel.py.
TASK_ERROR
str joblib.parallel.TASK_ERROR = "Error"
Definition at line 624 of file parallel.py.
TASK_PENDING
str joblib.parallel.TASK_PENDING = "Pending"
Definition at line 625 of file parallel.py.
VALID_BACKEND_CONSTRAINTS
tuple joblib.parallel.VALID_BACKEND_CONSTRAINTS = ("sharedmem", None)
Definition at line 108 of file parallel.py.
VALID_BACKEND_HINTS
tuple joblib.parallel.VALID_BACKEND_HINTS = ("processes", "threads", None)
Definition at line 107 of file parallel.py.