Code Cloning Analysis: scipy.signal.tests.test_upfirdn.UpFIRDnCase Class Reference
scipy.signal.tests.test_upfirdn.UpFIRDnCase Class Reference
Public Member Functions
__init__ (self, up, down, h, x_dtype)
__call__ (self)
scrub (self, x, axis=-1)
Public Attributes
up = up
down = down
h = np.atleast_1d(h)
x_dtype = x_dtype
rng = np.random.RandomState(17)
Detailed Description
Test _UpFIRDn object
Definition at line 59 of file test_upfirdn.py.
Constructor & Destructor Documentation
__init__()
scipy.signal.tests.test_upfirdn.UpFIRDnCase.__init__ (self, up, down, h, x_dtype)
Definition at line 61 of file test_upfirdn.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
__call__()
scipy.signal.tests.test_upfirdn.UpFIRDnCase.__call__ (self)
Definition at line 68 of file test_upfirdn.py.
scrub()
scipy.signal.tests.test_upfirdn.UpFIRDnCase.scrub (self, x, axis = -1)
Definition at line 91 of file test_upfirdn.py.
Member Data Documentation
down
scipy.signal.tests.test_upfirdn.UpFIRDnCase.down = down
Definition at line 63 of file test_upfirdn.py.
h
scipy.signal.tests.test_upfirdn.UpFIRDnCase.h = np.atleast_1d(h)
Definition at line 64 of file test_upfirdn.py.
rng
scipy.signal.tests.test_upfirdn.UpFIRDnCase.rng = np.random.RandomState(17)
Definition at line 66 of file test_upfirdn.py.
Referenced by scipy.stats._qmc.PoissonDisk._hypersphere_surface_sample(), scipy.stats._qmc.PoissonDisk._hypersphere_volume_sample(), scipy.stats._qmc.Halton._initialize_permutations(), scipy.stats._qmc.PoissonDisk._random(), scipy.stats._qmc.LatinHypercube._random_lhs(), scipy.stats._qmc.LatinHypercube._random_oa_lhs(), scipy.stats._qmc.Sobol._scramble(), sklearn.gaussian_process._gpc._BinaryGaussianProcessClassifierLaplace.fit(), and scipy.stats._qmc.QMCEngine.reset().
up
scipy.signal.tests.test_upfirdn.UpFIRDnCase.up = up
Definition at line 62 of file test_upfirdn.py.
x_dtype
scipy.signal.tests.test_upfirdn.UpFIRDnCase.x_dtype = x_dtype
Definition at line 65 of file test_upfirdn.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/signal/tests/test_upfirdn.py