Code Cloning Analysis: sklearn.feature_extraction.image Namespace Reference
sklearn.feature_extraction.image Namespace Reference
Classes
class PatchExtractor
Functions
_make_edges_3d (n_x, n_y, n_z=1)
From an image to a graph.
_compute_gradient_3d (edges, img)
_mask_edges_weights (mask, edges, weights=None)
_to_graph (n_x, n_y, n_z, mask=None, img=None, return_as=sparse.coo_matrix, dtype=None)
img_to_graph (img, *, mask=None, return_as=sparse.coo_matrix, dtype=None)
grid_to_graph (n_x, n_y, n_z=1, *, mask=None, return_as=sparse.coo_matrix, dtype=int)
_compute_n_patches (i_h, i_w, p_h, p_w, max_patches=None)
From an image to a set of small image patches.
_extract_patches (arr, patch_shape=8, extraction_step=1)
extract_patches_2d (image, patch_size, *, max_patches=None, random_state=None)
reconstruct_from_patches_2d (patches, image_size)
Variables
list __all__
Detailed Description
Utilities to extract features from images.
Function Documentation
_compute_gradient_3d()
sklearn.feature_extraction.image._compute_gradient_3d (edges, img) protected
Definition at line 51 of file image.py.
_compute_n_patches()
sklearn.feature_extraction.image._compute_n_patches (i_h, i_w, p_h, p_w, max_patches = None) protected
From an image to a set of small image patches.
Compute the number of patches that will be extracted in an image.
Read more in the :ref:`User Guide <image_feature_extraction>`.
Parameters
----------
i_h : int
    The image height
i_w : int
    The image with
p_h : int
    The height of a patch
p_w : int
    The width of a patch
max_patches : int or float, default=None
    The maximum number of patches to extract. If `max_patches` is a float
    between 0 and 1, it is taken to be a proportion of the total number
    of patches. If `max_patches` is None, all possible patches are extracted.
Definition at line 254 of file image.py.
Referenced by extract_patches_2d(), and sklearn.feature_extraction.image.PatchExtractor.transform().
_extract_patches()
sklearn.feature_extraction.image._extract_patches (arr, patch_shape = 8, extraction_step = 1) protected
Extracts patches of any n-dimensional array in place using strides.
Given an n-dimensional array it will return a 2n-dimensional array with
the first n dimensions indexing patch position and the last n indexing
the patch content. This operation is immediate (O(1)). A reshape
performed on the first n dimensions will cause numpy to copy data, leading
to a list of extracted patches.
Read more in the :ref:`User Guide <image_feature_extraction>`.
Parameters
----------
arr : ndarray
    n-dimensional array of which patches are to be extracted
patch_shape : int or tuple of length arr.ndim.default=8
    Indicates the shape of the patches to be extracted. If an
    integer is given, the shape will be a hypercube of
    sidelength given by its value.
extraction_step : int or tuple of length arr.ndim, default=1
    Indicates step size at which extraction shall be performed.
    If integer is given, then the step is uniform in all dimensions.
Returns
-------
patches : strided ndarray
    2n-dimensional array indexing patches on first n dimensions and
    containing patches on the last n dimensions. These dimensions
    are fake, but this way no data is copied. A simple reshape invokes
    a copying operation to obtain a list of patches:
    result.reshape([-1] + list(patch_shape))
Definition at line 291 of file image.py.
Referenced by extract_patches_2d().
_make_edges_3d()
sklearn.feature_extraction.image._make_edges_3d (n_x, n_y, n_z = 1) protected
From an image to a graph.
Returns a list of edges for a 3D image.
Parameters
----------
n_x : int
    The size of the grid in the x direction.
n_y : int
    The size of the grid in the y direction.
n_z : integer, default=1
    The size of the grid in the z direction, defaults to 1
Definition at line 31 of file image.py.
Referenced by _to_graph().
_mask_edges_weights()
sklearn.feature_extraction.image._mask_edges_weights (mask, edges, weights = None) protected
Apply a mask to edges (weighted or not)
Definition at line 71 of file image.py.
Referenced by _to_graph().
_to_graph()
sklearn.feature_extraction.image._to_graph (n_x, n_y, n_z, mask = None, img = None, return_as = sparse.coo_matrix, dtype = None) protected
Auxiliary function for img_to_graph and grid_to_graph
Definition at line 91 of file image.py.
References _make_edges_3d(), and _mask_edges_weights().
Referenced by grid_to_graph(), and img_to_graph().
extract_patches_2d()
sklearn.feature_extraction.image.extract_patches_2d (image, patch_size, * , max_patches = None, random_state = None)
Reshape a 2D image into a collection of patches.
The resulting patches are allocated in a dedicated array.
Read more in the :ref:`User Guide <image_feature_extraction>`.
Parameters
----------
image : ndarray of shape (image_height, image_width) or \
    (image_height, image_width, n_channels)
    The original image data. For color images, the last dimension specifies
    the channel: a RGB image would have `n_channels=3`.
patch_size : tuple of int (patch_height, patch_width)
    The dimensions of one patch.
max_patches : int or float, default=None
    The maximum number of patches to extract. If `max_patches` is a float
    between 0 and 1, it is taken to be a proportion of the total number
    of patches. If `max_patches` is None it corresponds to the total number
    of patches that can be extracted.
random_state : int, RandomState instance, default=None
    Determines the random number generator used for random sampling when
    `max_patches` is not None. Use an int to make the randomness
    deterministic.
    See :term:`Glossary <random_state>`.
Returns
-------
patches : array of shape (n_patches, patch_height, patch_width) or \
    (n_patches, patch_height, patch_width, n_channels)
    The collection of patches extracted from the image, where `n_patches`
    is either `max_patches` or the total number of patches that can be
    extracted.
Examples
--------
>>> from sklearn.datasets import load_sample_image
>>> from sklearn.feature_extraction import image
>>> # Use the array data from the first image in this dataset:
>>> one_image = load_sample_image("china.jpg")
>>> print('Image shape: {}'.format(one_image.shape))
Image shape: (427, 640, 3)
>>> patches = image.extract_patches_2d(one_image, (2, 2))
>>> print('Patches shape: {}'.format(patches.shape))
Patches shape: (272214, 2, 2, 3)
>>> # Here are just two of these patches:
>>> print(patches[1])
[[[174 201 231]
  [174 201 231]]
 [[173 200 230]
  [173 200 230]]]
>>> print(patches[800])
[[[187 214 243]
  [188 215 244]]
 [[187 214 243]
  [188 215 244]]]
Definition at line 363 of file image.py.
References _compute_n_patches(), and _extract_patches().
Referenced by sklearn.feature_extraction.image.PatchExtractor.transform().
grid_to_graph()
sklearn.feature_extraction.image.grid_to_graph (n_x, n_y, n_z = 1, * , mask = None, return_as = sparse.coo_matrix, dtype = int)
Graph of the pixel-to-pixel connections.
Edges exist if 2 voxels are connected.
Read more in the :ref:`User Guide <connectivity_graph_image>`.
Parameters
----------
n_x : int
    Dimension in x axis.
n_y : int
    Dimension in y axis.
n_z : int, default=1
    Dimension in z axis.
mask : ndarray of shape (n_x, n_y, n_z), dtype=bool, default=None
    An optional mask of the image, to consider only part of the
    pixels.
return_as : np.ndarray or a sparse matrix class, \
        default=sparse.coo_matrix
    The class to use to build the returned adjacency matrix.
dtype : dtype, default=int
    The data of the returned sparse matrix. By default it is int.
Returns
-------
graph : np.ndarray or a sparse matrix class
    The computed adjacency matrix.
Examples
--------
>>> import numpy as np
>>> from sklearn.feature_extraction.image import grid_to_graph
>>> shape_img = (4, 4, 1)
>>> mask = np.zeros(shape=shape_img, dtype=bool)
>>> mask[[1, 2], [1, 2], :] = True
>>> graph = grid_to_graph(*shape_img, mask=mask)
>>> print(graph)
<COOrdinate sparse matrix of dtype 'int64'
  with 2 stored elements and shape (2, 2)>
  Coords    Values
  (0, 0)    1
  (1, 1)    1
Definition at line 201 of file image.py.
References _to_graph().
img_to_graph()
sklearn.feature_extraction.image.img_to_graph (img, * , mask = None, return_as = sparse.coo_matrix, dtype = None)
Graph of the pixel-to-pixel gradient connections.
Edges are weighted with the gradient values.
Read more in the :ref:`User Guide <image_feature_extraction>`.
Parameters
----------
img : array-like of shape (height, width) or (height, width, channel)
    2D or 3D image.
mask : ndarray of shape (height, width) or \
        (height, width, channel), dtype=bool, default=None
    An optional mask of the image, to consider only part of the
    pixels.
return_as : np.ndarray or a sparse matrix class, \
        default=sparse.coo_matrix
    The class to use to build the returned adjacency matrix.
dtype : dtype, default=None
    The data of the returned sparse matrix. By default it is the
    dtype of img.
Returns
-------
graph : ndarray or a sparse matrix class
    The computed adjacency matrix.
Examples
--------
>>> import numpy as np
>>> from sklearn.feature_extraction.image import img_to_graph
>>> img = np.array([[0, 0], [0, 1]])
>>> img_to_graph(img, return_as=np.ndarray)
array([[0, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 1, 1, 1]])
Definition at line 147 of file image.py.
References _to_graph().
reconstruct_from_patches_2d()
sklearn.feature_extraction.image.reconstruct_from_patches_2d (patches, image_size)
Reconstruct the image from all of its patches.
Patches are assumed to overlap and the image is constructed by filling in
the patches from left to right, top to bottom, averaging the overlapping
regions.
Read more in the :ref:`User Guide <image_feature_extraction>`.
Parameters
----------
patches : ndarray of shape (n_patches, patch_height, patch_width) or \
    (n_patches, patch_height, patch_width, n_channels)
    The complete set of patches. If the patches contain colour information,
    channels are indexed along the last dimension: RGB patches would
    have `n_channels=3`.
image_size : tuple of int (image_height, image_width) or \
    (image_height, image_width, n_channels)
    The size of the image that will be reconstructed.
Returns
-------
image : ndarray of shape image_size
    The reconstructed image.
Examples
--------
>>> from sklearn.datasets import load_sample_image
>>> from sklearn.feature_extraction import image
>>> one_image = load_sample_image("china.jpg")
>>> print('Image shape: {}'.format(one_image.shape))
Image shape: (427, 640, 3)
>>> image_patches = image.extract_patches_2d(image=one_image, patch_size=(10, 10))
>>> print('Patches shape: {}'.format(image_patches.shape))
Patches shape: (263758, 10, 10, 3)
>>> image_reconstructed = image.reconstruct_from_patches_2d(
...     patches=image_patches,
...     image_size=one_image.shape
...)
>>> print(f"Reconstructed shape: {image_reconstructed.shape}")
Reconstructed shape: (427, 640, 3)
Definition at line 465 of file image.py.
Variable Documentation
__all__
list sklearn.feature_extraction.image.__all__ private
Initial value:
=  [
    "PatchExtractor",
    "extract_patches_2d",
    "grid_to_graph",
    "img_to_graph",
    "reconstruct_from_patches_2d",
]
Definition at line 17 of file image.py.