Code Cloning Analysis: sklearn.gaussian_process.kernels.ConstantKernel Class Reference
sklearn.gaussian_process.kernels.ConstantKernel Class Reference
Public Member Functions
__init__ (self, constant_value=1.0, constant_value_bounds=(1e-5, 1e5))
hyperparameter_constant_value (self)
__call__ (self, X, Y=None, eval_gradient=False)
diag (self, X)
__repr__ (self)
Public Member Functions inherited from sklearn.gaussian_process.kernels.StationaryKernelMixin
is_stationary (self)
Public Member Functions inherited from sklearn.gaussian_process.kernels.GenericKernelMixin
requires_vector_input (self)
Public Member Functions inherited from sklearn.gaussian_process.kernels.Kernel
get_params (self, deep=True)
set_params (self, **params)
clone_with_theta (self, theta)
n_dims (self)
hyperparameters (self)
theta (self)
theta (self, theta)
bounds (self)
__add__ (self, b)
__radd__ (self, b)
__mul__ (self, b)
__rmul__ (self, b)
__pow__ (self, b)
__eq__ (self, b)
__repr__ (self)
__call__ (self, X, Y=None, eval_gradient=False)
is_stationary (self)
requires_vector_input (self)
Public Attributes
constant_value = constant_value
constant_value_bounds = constant_value_bounds
Public Attributes inherited from sklearn.gaussian_process.kernels.Kernel
hyperparameters
theta
Additional Inherited Members
Protected Member Functions inherited from sklearn.gaussian_process.kernels.Kernel
_check_bounds_params (self)
Detailed Description
Constant kernel.
Can be used as part of a product-kernel where it scales the magnitude of
the other factor (kernel) or as part of a sum-kernel, where it modifies
the mean of the Gaussian process.
.. math::
    k(x_1, x_2) = constant\\_value \\;\\forall\\; x_1, x_2
Adding a constant kernel is equivalent to adding a constant::
        kernel = RBF() + ConstantKernel(constant_value=2)
is the same as::
        kernel = RBF() + 2
Read more in the :ref:`User Guide <gp_kernels>`.
.. versionadded:: 0.18
Parameters
----------
constant_value : float, default=1.0
    The constant value which defines the covariance:
    k(x_1, x_2) = constant_value
constant_value_bounds : pair of floats >= 0 or "fixed", default=(1e-5, 1e5)
    The lower and upper bound on `constant_value`.
    If set to "fixed", `constant_value` cannot be changed during
    hyperparameter tuning.
Examples
--------
>>> from sklearn.datasets import make_friedman2
>>> from sklearn.gaussian_process import GaussianProcessRegressor
>>> from sklearn.gaussian_process.kernels import RBF, ConstantKernel
>>> X, y = make_friedman2(n_samples=500, noise=0, random_state=0)
>>> kernel = RBF() + ConstantKernel(constant_value=2)
>>> gpr = GaussianProcessRegressor(kernel=kernel, alpha=5,
...         random_state=0).fit(X, y)
>>> gpr.score(X, y)
0.3696
>>> gpr.predict(X[:1,:], return_std=True)
(array([606.1]), array([0.248]))
Definition at line 1182 of file kernels.py.
Constructor & Destructor Documentation
__init__()
sklearn.gaussian_process.kernels.ConstantKernel.__init__ (self, constant_value = 1.0, constant_value_bounds = (1e-5, 1e5))
Definition at line 1231 of file kernels.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params().
Member Function Documentation
__call__()
sklearn.gaussian_process.kernels.ConstantKernel.__call__ (self, X, Y = None, eval_gradient = False)
Return the kernel k(X, Y) and optionally its gradient.
Parameters
----------
X : array-like of shape (n_samples_X, n_features) or list of object
    Left argument of the returned kernel k(X, Y)
Y : array-like of shape (n_samples_X, n_features) or list of object, \
    default=None
    Right argument of the returned kernel k(X, Y). If None, k(X, X)
    is evaluated instead.
eval_gradient : bool, default=False
    Determines whether the gradient with respect to the log of
    the kernel hyperparameter is computed.
    Only supported when Y is None.
Returns
-------
K : ndarray of shape (n_samples_X, n_samples_Y)
    Kernel k(X, Y)
K_gradient : ndarray of shape (n_samples_X, n_samples_X, n_dims), \
    optional
    The gradient of the kernel k(X, X) with respect to the log of the
    hyperparameter of the kernel. Only returned when eval_gradient
    is True.
Definition at line 1239 of file kernels.py.
References constant_value, and hyperparameter_constant_value().
__repr__()
sklearn.gaussian_process.kernels.ConstantKernel.__repr__ (self)
Definition at line 1316 of file kernels.py.
diag()
sklearn.gaussian_process.kernels.ConstantKernel.diag (self, X)
Returns the diagonal of the kernel k(X, X).
The result of this method is identical to np.diag(self(X)); however,
it can be evaluated more efficiently since only the diagonal is
evaluated.
Parameters
----------
X : array-like of shape (n_samples_X, n_features) or list of object
    Argument to the kernel.
Returns
-------
K_diag : ndarray of shape (n_samples_X,)
    Diagonal of kernel k(X, X)
Reimplemented from sklearn.gaussian_process.kernels.Kernel.
Definition at line 1293 of file kernels.py.
References constant_value.
hyperparameter_constant_value()
sklearn.gaussian_process.kernels.ConstantKernel.hyperparameter_constant_value (self)
Definition at line 1236 of file kernels.py.
Referenced by __call__().
Member Data Documentation
constant_value
sklearn.gaussian_process.kernels.ConstantKernel.constant_value = constant_value
Definition at line 1232 of file kernels.py.
Referenced by __call__(), and diag().
constant_value_bounds
sklearn.gaussian_process.kernels.ConstantKernel.constant_value_bounds = constant_value_bounds
Definition at line 1233 of file kernels.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/sklearn/gaussian_process/kernels.py