Code Cloning Analysis: fontTools.misc.filesystem._zipfs.ZipFS Class Reference
fontTools.misc.filesystem._zipfs.ZipFS Class Reference
Public Member Functions
__new__ (cls, str|os.PathLike file, bool write=False, str encoding="utf-8")
__init__ (self, str|os.PathLike file, bool write=False, str encoding="utf-8")
Public Member Functions inherited from fontTools.misc.filesystem._base.FS
IO[Any] open (self, str path, str mode="rb", **kwargs)
bool exists (self, str path)
bool isdir (self, str path)
bool isfile (self, str path)
list[str] listdir (self, str path)
SubFS makedir (self, str path, bool recreate=False)
SubFS makedirs (self, str path, bool recreate=False)
Info getinfo (self, str path, Collection[str]|None namespaces=None)
None remove (self, str path)
None removedir (self, str path)
None removetree (self, str path)
None movedir (self, str src, str dst, bool create=False)
str getsyspath (self, str path)
close (self)
bool isclosed (self)
Self __enter__ (self)
__exit__ (self, exc_type, exc, tb)
check (self)
SubFS opendir (self, str path, *, Type[SubFS]|None factory=None)
Iterator[Info] scandir (self, str path, Collection[str]|None namespaces=None)
BoundWalker walk (self)
bytes readbytes (self, str path)
writebytes (self, str path, bytes data)
create (self, str path, bool wipe=False)
copy (self, str src_path, str dst_path, overwrite=False)
copydir (self, str src_path, str dst_path, create=False)
Additional Inherited Members
Static Protected Attributes inherited from fontTools.misc.filesystem._base.FS
bool _closed = False
Detailed Description
Read and write zip files.
Definition at line 24 of file _zipfs.py.
Constructor & Destructor Documentation
__init__()
fontTools.misc.filesystem._zipfs.ZipFS.__init__ (self, str | os.PathLike file, bool write = False, str encoding = "utf-8")
Definition at line 37 of file _zipfs.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__new__()
fontTools.misc.filesystem._zipfs.ZipFS.__new__ (cls, str | os.PathLike file, bool write = False, str encoding = "utf-8")
Definition at line 27 of file _zipfs.py.
Referenced by matplotlib.path.Path._fast_from_codes_and_verts(), pandas.core.generic.NDFrame._from_mgr(), pandas.core.arrays.string_.StringArray._from_sequence(), scipy.interpolate._fitpack2._BivariateSplineBase._from_tck(), scipy.interpolate._fitpack2.UnivariateSpline._from_tck(), matplotlib.colors.Colormap._get_rgba_and_mask(), pip._vendor.rich.style.Style.clear_meta_and_links(), matplotlib.colors.MultivarColormap.copy(), pip._vendor.rich.style.Style.copy(), pip._vendor.rich.style.Style.from_color(), pip._vendor.rich.json.JSON.from_data(), pip._vendor.rich.style.Style.from_meta(), matplotlib.colors.BivarColormap.lut(), pip._vendor.rich.style.Style.test(), pip._vendor.rich.style.Style.update_link(), and pip._vendor.rich.style.Style.without_color().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/misc/filesystem/_zipfs.py