Code Cloning Analysis: sklearn.model_selection._validation Namespace Reference
sklearn.model_selection._validation Namespace Reference
Functions
_check_params_groups_deprecation (fit_params, params, groups, version)
_check_groups_routing_disabled (groups)
cross_validate (estimator, X, y=None, *, groups=None, scoring=None, cv=None, n_jobs=None, verbose=0, params=None, pre_dispatch="2*n_jobs", return_train_score=False, return_estimator=False, return_indices=False, error_score=np.nan)
_insert_error_scores (results, error_score)
_normalize_score_results (scores, scaler_score_key="score")
_warn_or_raise_about_fit_failures (results, error_score)
cross_val_score (estimator, X, y=None, *, groups=None, scoring=None, cv=None, n_jobs=None, verbose=0, params=None, pre_dispatch="2*n_jobs", error_score=np.nan)
_fit_and_score (estimator, X, y, *, scorer, train, test, verbose, parameters, fit_params, score_params, return_train_score=False, return_parameters=False, return_n_test_samples=False, return_times=False, return_estimator=False, split_progress=None, candidate_progress=None, error_score=np.nan)
_score (estimator, X_test, y_test, scorer, score_params, error_score="raise")
cross_val_predict (estimator, X, y=None, *, groups=None, cv=None, n_jobs=None, verbose=0, params=None, pre_dispatch="2*n_jobs", method="predict")
_fit_and_predict (estimator, X, y, train, test, fit_params, method)
_enforce_prediction_order (classes, predictions, n_classes, method)
_check_is_permutation (indices, n_samples)
permutation_test_score (estimator, X, y, *, groups=None, cv=None, n_permutations=100, n_jobs=None, random_state=0, verbose=0, scoring=None, fit_params=None, params=None)
_permutation_test_score (estimator, X, y, cv, scorer, split_params, fit_params, score_params)
_shuffle (y, groups, random_state)
learning_curve (estimator, X, y, *, groups=None, train_sizes=np.linspace(0.1, 1.0, 5), cv=None, scoring=None, exploit_incremental_learning=False, n_jobs=None, pre_dispatch="all", verbose=0, shuffle=False, random_state=None, error_score=np.nan, return_times=False, fit_params=None, params=None)
_translate_train_sizes (train_sizes, n_max_training_samples)
_incremental_fit_estimator (estimator, X, y, classes, train, test, train_sizes, scorer, return_times, error_score, fit_params, score_params)
validation_curve (estimator, X, y, *, param_name, param_range, groups=None, cv=None, scoring=None, n_jobs=None, pre_dispatch="all", verbose=0, error_score=np.nan, fit_params=None, params=None)
_aggregate_score_dicts (scores)
Variables
list __all__
Detailed Description
The :mod:`sklearn.model_selection._validation` module includes classes and
functions to validate the model.
Function Documentation
_aggregate_score_dicts()
sklearn.model_selection._validation._aggregate_score_dicts (scores) protected
Aggregate the list of dict to dict of np ndarray
The aggregated output of _aggregate_score_dicts will be a list of dict
of form [{'prec': 0.1, 'acc':1.0}, {'prec': 0.1, 'acc':1.0}, ...]
Convert it to a dict of array {'prec': np.array([0.1 ...]), ...}
Parameters
----------
scores : list of dict
    List of dicts of the scores for all scorers. This is a flat list,
    assumed originally to be of row major order.
Example
-------
>>> scores = [{'a': 1, 'b':10}, {'a': 2, 'b':2}, {'a': 3, 'b':3},
...           {'a': 10, 'b': 10}]                         # doctest: +SKIP
>>> _aggregate_score_dicts(scores)                        # doctest: +SKIP
{'a': array([1, 2, 3, 10]),
 'b': array([10, 2, 3, 10])}
Definition at line 2500 of file _validation.py.
Referenced by _normalize_score_results(), cross_validate(), learning_curve(), and validation_curve().
_check_groups_routing_disabled()
sklearn.model_selection._validation._check_groups_routing_disabled (groups) protected
Definition at line 88 of file _validation.py.
_check_is_permutation()
sklearn.model_selection._validation._check_is_permutation (indices, n_samples) protected
Check whether indices is a reordering of the array np.arange(n_samples)
Parameters
----------
indices : ndarray
    int array to test
n_samples : int
    number of expected elements
Returns
-------
is_partition : bool
    True iff sorted(indices) is np.arange(n)
Definition at line 1414 of file _validation.py.
Referenced by cross_val_predict().
_check_params_groups_deprecation()
sklearn.model_selection._validation._check_params_groups_deprecation (fit_params, params, groups, version) protected
A helper function to check deprecations on `groups` and `fit_params`.
# TODO(SLEP6): To be removed when set_config(enable_metadata_routing=False) is not
# possible.
Definition at line 57 of file _validation.py.
Referenced by learning_curve(), permutation_test_score(), and validation_curve().
_enforce_prediction_order()
sklearn.model_selection._validation._enforce_prediction_order (classes, predictions, n_classes, method) protected
Ensure that prediction arrays have correct column order
When doing cross-validation, if one or more classes are
not present in the subset of data used for training,
then the output prediction array might not have the same
columns as other folds. Use the list of class names
(assumed to be ints) to enforce the correct column order.
Note that `classes` is the list of classes in this fold
(a subset of the classes in the full training set)
and `n_classes` is the number of classes in the full training set.
Definition at line 1348 of file _validation.py.
Referenced by _fit_and_predict().
_fit_and_predict()
sklearn.model_selection._validation._fit_and_predict (estimator, X, y, train, test, fit_params, method) protected
Fit estimator and predict values for a given dataset split.
Read more in the :ref:`User Guide <cross_validation>`.
Parameters
----------
estimator : estimator object implementing 'fit' and 'predict'
    The object to use to fit the data.
X : array-like of shape (n_samples, n_features)
    The data to fit.
    .. versionchanged:: 0.20
        X is only required to be an object with finite length or shape now
y : array-like of shape (n_samples,) or (n_samples, n_outputs) or None
    The target variable to try to predict in the case of
    supervised learning.
train : array-like of shape (n_train_samples,)
    Indices of training samples.
test : array-like of shape (n_test_samples,)
    Indices of test samples.
fit_params : dict or None
    Parameters that will be passed to ``estimator.fit``.
method : str
    Invokes the passed method name of the passed estimator.
Returns
-------
predictions : sequence
    Result of calling 'estimator.method'
Definition at line 1272 of file _validation.py.
References _enforce_prediction_order().
_fit_and_score()
sklearn.model_selection._validation._fit_and_score (estimator, X, y, * , scorer, train, test, verbose, parameters, fit_params, score_params, return_train_score = False, return_parameters = False, return_n_test_samples = False, return_times = False, return_estimator = False, split_progress = None, candidate_progress = None, error_score = np.nan) protected
Fit estimator and compute scores for a given dataset split.
Parameters
----------
estimator : estimator object implementing 'fit'
    The object to use to fit the data.
X : array-like of shape (n_samples, n_features)
    The data to fit.
y : array-like of shape (n_samples,) or (n_samples, n_outputs) or None
    The target variable to try to predict in the case of
    supervised learning.
scorer : A single callable or dict mapping scorer name to the callable
    If it is a single callable, the return value for ``train_scores`` and
    ``test_scores`` is a single float.
    For a dict, it should be one mapping the scorer name to the scorer
    callable object / function.
    The callable object / fn should have signature
    ``scorer(estimator, X, y)``.
train : array-like of shape (n_train_samples,)
    Indices of training samples.
test : array-like of shape (n_test_samples,)
    Indices of test samples.
verbose : int
    The verbosity level.
error_score : 'raise' or numeric, default=np.nan
    Value to assign to the score if an error occurs in estimator fitting.
    If set to 'raise', the error is raised.
    If a numeric value is given, FitFailedWarning is raised.
parameters : dict or None
    Parameters to be set on the estimator.
fit_params : dict or None
    Parameters that will be passed to ``estimator.fit``.
score_params : dict or None
    Parameters that will be passed to the scorer.
return_train_score : bool, default=False
    Compute and return score on training set.
return_parameters : bool, default=False
    Return parameters that has been used for the estimator.
split_progress : {list, tuple} of int, default=None
    A list or tuple of format (<current_split_id>, <total_num_of_splits>).
candidate_progress : {list, tuple} of int, default=None
    A list or tuple of format
    (<current_candidate_id>, <total_number_of_candidates>).
return_n_test_samples : bool, default=False
    Whether to return the ``n_test_samples``.
return_times : bool, default=False
    Whether to return the fit/score times.
return_estimator : bool, default=False
    Whether to return the fitted estimator.
Returns
-------
result : dict with the following attributes
    train_scores : dict of scorer name -> float
        Score on training set (for all the scorers),
        returned only if `return_train_score` is `True`.
    test_scores : dict of scorer name -> float
        Score on testing set (for all the scorers).
    n_test_samples : int
        Number of test samples.
    fit_time : float
        Time spent for fitting in seconds.
    score_time : float
        Time spent for scoring in seconds.
    parameters : dict or None
        The parameters that have been evaluated.
    estimator : estimator object
        The fitted estimator.
    fit_error : str or None
        Traceback str if the fit failed, None if the fit succeeded.
Definition at line 693 of file _validation.py.
References _score().
_incremental_fit_estimator()
sklearn.model_selection._validation._incremental_fit_estimator (estimator, X, y, classes, train, test, train_sizes, scorer, return_times, error_score, fit_params, score_params) protected
Train estimator on training subsets incrementally and compute scores.
Definition at line 2170 of file _validation.py.
References _score().
_insert_error_scores()
sklearn.model_selection._validation._insert_error_scores (results, error_score) protected
Insert error in `results` by replacing them inplace with `error_score`.
This only applies to multimetric scores because `_fit_and_score` will
handle the single metric case.
Definition at line 453 of file _validation.py.
Referenced by cross_validate().
_normalize_score_results()
sklearn.model_selection._validation._normalize_score_results (scores, scaler_score_key = "score") protected
Creates a scoring dictionary based on the type of `scores`
Definition at line 475 of file _validation.py.
References _aggregate_score_dicts().
Referenced by cross_validate().
_permutation_test_score()
sklearn.model_selection._validation._permutation_test_score (estimator, X, y, cv, scorer, split_params, fit_params, score_params) protected
Auxiliary function for permutation_test_score
Definition at line 1706 of file _validation.py.
Referenced by permutation_test_score().
_score()
sklearn.model_selection._validation._score (estimator, X_test, y_test, scorer, score_params, error_score = "raise") protected
Compute the score(s) of an estimator on a given test set.
Will return a dict of floats if `scorer` is a _MultiMetricScorer, otherwise a single
float is returned.
Definition at line 930 of file _validation.py.
Referenced by _fit_and_score(), and _incremental_fit_estimator().
_shuffle()
sklearn.model_selection._validation._shuffle (y, groups, random_state) protected
Return a shuffled copy of y eventually shuffle among same groups.
Definition at line 1725 of file _validation.py.
Referenced by permutation_test_score().
_translate_train_sizes()
sklearn.model_selection._validation._translate_train_sizes (train_sizes, n_max_training_samples) protected
Determine absolute sizes of training subsets and validate 'train_sizes'.
Examples:
    _translate_train_sizes([0.5, 1.0], 10) -> [5, 10]
    _translate_train_sizes([5, 10], 10) -> [5, 10]
Parameters
----------
train_sizes : array-like of shape (n_ticks,)
    Numbers of training examples that will be used to generate the
    learning curve. If the dtype is float, it is regarded as a
    fraction of 'n_max_training_samples', i.e. it has to be within (0, 1].
n_max_training_samples : int
    Maximum number of training samples (upper bound of 'train_sizes').
Returns
-------
train_sizes_abs : array of shape (n_unique_ticks,)
    Numbers of training examples that will be used to generate the
    learning curve. Note that the number of ticks might be less
    than n_ticks because duplicate entries will be removed.
Definition at line 2102 of file _validation.py.
Referenced by learning_curve().
_warn_or_raise_about_fit_failures()
sklearn.model_selection._validation._warn_or_raise_about_fit_failures (results, error_score) protected
Definition at line 484 of file _validation.py.
cross_val_predict()
sklearn.model_selection._validation.cross_val_predict (estimator, X, y = None, * , groups = None, cv = None, n_jobs = None, verbose = 0, params = None, pre_dispatch = "2*n_jobs", method = "predict")
Generate cross-validated estimates for each input data point.
The data is split according to the cv parameter. Each sample belongs
to exactly one test set, and its prediction is computed with an
estimator fitted on the corresponding training set.
Passing these predictions into an evaluation metric may not be a valid
way to measure generalization performance. Results can differ from
:func:`cross_validate` and :func:`cross_val_score` unless all tests sets
have equal size and the metric decomposes over samples.
Read more in the :ref:`User Guide <cross_validation>`.
Parameters
----------
estimator : estimator
    The estimator instance to use to fit the data. It must implement a `fit`
    method and the method given by the `method` parameter.
X : {array-like, sparse matrix} of shape (n_samples, n_features)
    The data to fit. Can be, for example a list, or an array at least 2d.
y : {array-like, sparse matrix} of shape (n_samples,) or (n_samples, n_outputs), \
        default=None
    The target variable to try to predict in the case of
    supervised learning.
groups : array-like of shape (n_samples,), default=None
    Group labels for the samples used while splitting the dataset into
    train/test set. Only used in conjunction with a "Group" :term:`cv`
    instance (e.g., :class:`GroupKFold`).
    .. versionchanged:: 1.4
        ``groups`` can only be passed if metadata routing is not enabled
        via ``sklearn.set_config(enable_metadata_routing=True)``. When routing
        is enabled, pass ``groups`` alongside other metadata via the ``params``
        argument instead. E.g.:
        ``cross_val_predict(..., params={'groups': groups})``.
cv : int, cross-validation generator or an iterable, default=None
    Determines the cross-validation splitting strategy.
    Possible inputs for cv are:
    - None, to use the default 5-fold cross validation,
    - int, to specify the number of folds in a `(Stratified)KFold`,
    - :term:`CV splitter`,
    - An iterable that generates (train, test) splits as arrays of indices.
    For int/None inputs, if the estimator is a classifier and ``y`` is
    either binary or multiclass, :class:`StratifiedKFold` is used. In all
    other cases, :class:`KFold` is used. These splitters are instantiated
    with `shuffle=False` so the splits will be the same across calls.
    Refer :ref:`User Guide <cross_validation>` for the various
    cross-validation strategies that can be used here.
    .. versionchanged:: 0.22
        ``cv`` default value if None changed from 3-fold to 5-fold.
n_jobs : int, default=None
    Number of jobs to run in parallel. Training the estimator and
    predicting are parallelized over the cross-validation splits.
    ``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.
    ``-1`` means using all processors. See :term:`Glossary <n_jobs>`
    for more details.
verbose : int, default=0
    The verbosity level.
params : dict, default=None
    Parameters to pass to the underlying estimator's ``fit`` and the CV
    splitter.
    .. versionadded:: 1.4
pre_dispatch : int or str, default='2*n_jobs'
    Controls the number of jobs that get dispatched during parallel
    execution. Reducing this number can be useful to avoid an
    explosion of memory consumption when more jobs get dispatched
    than CPUs can process. This parameter can be:
    - None, in which case all the jobs are immediately created and spawned. Use
      this for lightweight and fast-running jobs, to avoid delays due to on-demand
      spawning of the jobs
    - An int, giving the exact number of total jobs that are spawned
    - A str, giving an expression as a function of n_jobs, as in '2*n_jobs'
method : {'predict', 'predict_proba', 'predict_log_proba', \
          'decision_function'}, default='predict'
    The method to be invoked by `estimator`.
Returns
-------
predictions : ndarray
    This is the result of calling `method`. Shape:
    - When `method` is 'predict' and in special case where `method` is
      'decision_function' and the target is binary: (n_samples,)
    - When `method` is one of {'predict_proba', 'predict_log_proba',
      'decision_function'} (unless special case above):
      (n_samples, n_classes)
    - If `estimator` is :term:`multioutput`, an extra dimension
      'n_outputs' is added to the end of each shape above.
See Also
--------
cross_val_score : Calculate score for each CV split.
cross_validate : Calculate one or more scores and timings for each CV
    split.
Notes
-----
In the case that one or more classes are absent in a training portion, a
default score needs to be assigned to all instances for that class if
``method`` produces columns per class, as in {'decision_function',
'predict_proba', 'predict_log_proba'}.  For ``predict_proba`` this value is
0.  In order to ensure finite output, we approximate negative infinity by
the minimum finite float value for the dtype in other cases.
Examples
--------
>>> from sklearn import datasets, linear_model
>>> from sklearn.model_selection import cross_val_predict
>>> diabetes = datasets.load_diabetes()
>>> X = diabetes.data[:150]
>>> y = diabetes.target[:150]
>>> lasso = linear_model.Lasso()
>>> y_pred = cross_val_predict(lasso, X, y, cv=3)
For a detailed example of using ``cross_val_predict`` to visualize
prediction errors, please see
:ref:`sphx_glr_auto_examples_model_selection_plot_cv_predict.py`.
Definition at line 1024 of file _validation.py.
References _check_is_permutation().
cross_val_score()
sklearn.model_selection._validation.cross_val_score (estimator, X, y = None, * , groups = None, scoring = None, cv = None, n_jobs = None, verbose = 0, params = None, pre_dispatch = "2*n_jobs", error_score = np.nan)
Evaluate a score by cross-validation.
Read more in the :ref:`User Guide <cross_validation>`.
Parameters
----------
estimator : estimator object implementing 'fit'
    The object to use to fit the data.
X : {array-like, sparse matrix} of shape (n_samples, n_features)
    The data to fit. Can be for example a list, or an array.
y : array-like of shape (n_samples,) or (n_samples, n_outputs), \
        default=None
    The target variable to try to predict in the case of
    supervised learning.
groups : array-like of shape (n_samples,), default=None
    Group labels for the samples used while splitting the dataset into
    train/test set. Only used in conjunction with a "Group" :term:`cv`
    instance (e.g., :class:`GroupKFold`).
    .. versionchanged:: 1.4
        ``groups`` can only be passed if metadata routing is not enabled
        via ``sklearn.set_config(enable_metadata_routing=True)``. When routing
        is enabled, pass ``groups`` alongside other metadata via the ``params``
        argument instead. E.g.:
        ``cross_val_score(..., params={'groups': groups})``.
scoring : str or callable, default=None
    Strategy to evaluate the performance of the `estimator` across cross-validation
    splits.
    - str: see :ref:`scoring_string_names` for options.
    - callable: a scorer callable object (e.g., function) with signature
      ``scorer(estimator, X, y)``, which should return only a single value.
      See :ref:`scoring_callable` for details.
    - `None`: the `estimator`'s
      :ref:`default evaluation criterion <scoring_api_overview>` is used.
    Similar to the use of `scoring` in :func:`cross_validate` but only a
    single metric is permitted.
cv : int, cross-validation generator or an iterable, default=None
    Determines the cross-validation splitting strategy.
    Possible inputs for cv are:
    - `None`, to use the default 5-fold cross validation,
    - int, to specify the number of folds in a `(Stratified)KFold`,
    - :term:`CV splitter`,
    - An iterable that generates (train, test) splits as arrays of indices.
    For `int`/`None` inputs, if the estimator is a classifier and `y` is
    either binary or multiclass, :class:`StratifiedKFold` is used. In all
    other cases, :class:`KFold` is used. These splitters are instantiated
    with `shuffle=False` so the splits will be the same across calls.
    Refer :ref:`User Guide <cross_validation>` for the various
    cross-validation strategies that can be used here.
    .. versionchanged:: 0.22
        `cv` default value if `None` changed from 3-fold to 5-fold.
n_jobs : int, default=None
    Number of jobs to run in parallel. Training the estimator and computing
    the score are parallelized over the cross-validation splits.
    ``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.
    ``-1`` means using all processors. See :term:`Glossary <n_jobs>`
    for more details.
verbose : int, default=0
    The verbosity level.
params : dict, default=None
    Parameters to pass to the underlying estimator's ``fit``, the scorer,
    and the CV splitter.
    .. versionadded:: 1.4
pre_dispatch : int or str, default='2*n_jobs'
    Controls the number of jobs that get dispatched during parallel
    execution. Reducing this number can be useful to avoid an
    explosion of memory consumption when more jobs get dispatched
    than CPUs can process. This parameter can be:
    - ``None``, in which case all the jobs are immediately created and spawned. Use
      this for lightweight and fast-running jobs, to avoid delays due to on-demand
      spawning of the jobs
    - An int, giving the exact number of total jobs that are spawned
    - A str, giving an expression as a function of n_jobs, as in '2*n_jobs'
error_score : 'raise' or numeric, default=np.nan
    Value to assign to the score if an error occurs in estimator fitting.
    If set to 'raise', the error is raised.
    If a numeric value is given, FitFailedWarning is raised.
    .. versionadded:: 0.20
Returns
-------
scores : ndarray of float of shape=(len(list(cv)),)
    Array of scores of the estimator for each run of the cross validation.
See Also
--------
cross_validate : To run cross-validation on multiple metrics and also to
    return train scores, fit times and score times.
cross_val_predict : Get predictions from each split of cross-validation for
    diagnostic purposes.
sklearn.metrics.make_scorer : Make a scorer from a performance metric or
    loss function.
Examples
--------
>>> from sklearn import datasets, linear_model
>>> from sklearn.model_selection import cross_val_score
>>> diabetes = datasets.load_diabetes()
>>> X = diabetes.data[:150]
>>> y = diabetes.target[:150]
>>> lasso = linear_model.Lasso()
>>> print(cross_val_score(lasso, X, y, cv=3))
[0.3315057  0.08022103 0.03531816]
Definition at line 535 of file _validation.py.
References cross_validate().
cross_validate()
sklearn.model_selection._validation.cross_validate (estimator, X, y = None, * , groups = None, scoring = None, cv = None, n_jobs = None, verbose = 0, params = None, pre_dispatch = "2*n_jobs", return_train_score = False, return_estimator = False, return_indices = False, error_score = np.nan)
Evaluate metric(s) by cross-validation and also record fit/score times.
Read more in the :ref:`User Guide <multimetric_cross_validation>`.
Parameters
----------
estimator : estimator object implementing 'fit'
    The object to use to fit the data.
X : {array-like, sparse matrix} of shape (n_samples, n_features)
    The data to fit. Can be for example a list, or an array.
y : array-like of shape (n_samples,) or (n_samples, n_outputs), default=None
    The target variable to try to predict in the case of
    supervised learning.
groups : array-like of shape (n_samples,), default=None
    Group labels for the samples used while splitting the dataset into
    train/test set. Only used in conjunction with a "Group" :term:`cv`
    instance (e.g., :class:`GroupKFold`).
    .. versionchanged:: 1.4
        ``groups`` can only be passed if metadata routing is not enabled
        via ``sklearn.set_config(enable_metadata_routing=True)``. When routing
        is enabled, pass ``groups`` alongside other metadata via the ``params``
        argument instead. E.g.:
        ``cross_validate(..., params={'groups': groups})``.
scoring : str, callable, list, tuple, or dict, default=None
    Strategy to evaluate the performance of the `estimator` across cross-validation
    splits.
    If `scoring` represents a single score, one can use:
    - a single string (see :ref:`scoring_string_names`);
    - a callable (see :ref:`scoring_callable`) that returns a single value.
    - `None`, the `estimator`'s
      :ref:`default evaluation criterion <scoring_api_overview>` is used.
    If `scoring` represents multiple scores, one can use:
    - a list or tuple of unique strings;
    - a callable returning a dictionary where the keys are the metric
      names and the values are the metric scores;
    - a dictionary with metric names as keys and callables a values.
    See :ref:`multimetric_grid_search` for an example.
cv : int, cross-validation generator or an iterable, default=None
    Determines the cross-validation splitting strategy.
    Possible inputs for cv are:
    - None, to use the default 5-fold cross validation,
    - int, to specify the number of folds in a `(Stratified)KFold`,
    - :term:`CV splitter`,
    - An iterable yielding (train, test) splits as arrays of indices.
    For int/None inputs, if the estimator is a classifier and ``y`` is
    either binary or multiclass, :class:`StratifiedKFold` is used. In all
    other cases, :class:`KFold` is used. These splitters are instantiated
    with `shuffle=False` so the splits will be the same across calls.
    Refer :ref:`User Guide <cross_validation>` for the various
    cross-validation strategies that can be used here.
    .. versionchanged:: 0.22
        ``cv`` default value if None changed from 3-fold to 5-fold.
n_jobs : int, default=None
    Number of jobs to run in parallel. Training the estimator and computing
    the score are parallelized over the cross-validation splits.
    ``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.
    ``-1`` means using all processors. See :term:`Glossary <n_jobs>`
    for more details.
verbose : int, default=0
    The verbosity level.
params : dict, default=None
    Parameters to pass to the underlying estimator's ``fit``, the scorer,
    and the CV splitter.
    .. versionadded:: 1.4
pre_dispatch : int or str, default='2*n_jobs'
    Controls the number of jobs that get dispatched during parallel
    execution. Reducing this number can be useful to avoid an
    explosion of memory consumption when more jobs get dispatched
    than CPUs can process. This parameter can be:
    - An int, giving the exact number of total jobs that are spawned
    - A str, giving an expression as a function of n_jobs, as in '2*n_jobs'
return_train_score : bool, default=False
    Whether to include train scores.
    Computing training scores is used to get insights on how different
    parameter settings impact the overfitting/underfitting trade-off.
    However computing the scores on the training set can be computationally
    expensive and is not strictly required to select the parameters that
    yield the best generalization performance.
    .. versionadded:: 0.19
    .. versionchanged:: 0.21
        Default value was changed from ``True`` to ``False``
return_estimator : bool, default=False
    Whether to return the estimators fitted on each split.
    .. versionadded:: 0.20
return_indices : bool, default=False
    Whether to return the train-test indices selected for each split.
    .. versionadded:: 1.3
error_score : 'raise' or numeric, default=np.nan
    Value to assign to the score if an error occurs in estimator fitting.
    If set to 'raise', the error is raised.
    If a numeric value is given, FitFailedWarning is raised.
    .. versionadded:: 0.20
Returns
-------
scores : dict of float arrays of shape (n_splits,)
    Array of scores of the estimator for each run of the cross validation.
    A dict of arrays containing the score/time arrays for each scorer is
    returned. The possible keys for this ``dict`` are:
    ``test_score``
        The score array for test scores on each cv split.
        Suffix ``_score`` in ``test_score`` changes to a specific
        metric like ``test_r2`` or ``test_auc`` if there are
        multiple scoring metrics in the scoring parameter.
    ``train_score``
        The score array for train scores on each cv split.
        Suffix ``_score`` in ``train_score`` changes to a specific
        metric like ``train_r2`` or ``train_auc`` if there are
        multiple scoring metrics in the scoring parameter.
        This is available only if ``return_train_score`` parameter
        is ``True``.
    ``fit_time``
        The time for fitting the estimator on the train
        set for each cv split.
    ``score_time``
        The time for scoring the estimator on the test set for each
        cv split. (Note: time for scoring on the train set is not
        included even if ``return_train_score`` is set to ``True``).
    ``estimator``
        The estimator objects for each cv split.
        This is available only if ``return_estimator`` parameter
        is set to ``True``.
    ``indices``
        The train/test positional indices for each cv split. A dictionary
        is returned where the keys are either `"train"` or `"test"`
        and the associated values are a list of integer-dtyped NumPy
        arrays with the indices. Available only if `return_indices=True`.
See Also
--------
cross_val_score : Run cross-validation for single metric evaluation.
cross_val_predict : Get predictions from each split of cross-validation for
    diagnostic purposes.
sklearn.metrics.make_scorer : Make a scorer from a performance metric or
    loss function.
Examples
--------
>>> from sklearn import datasets, linear_model
>>> from sklearn.model_selection import cross_validate
>>> from sklearn.metrics import make_scorer
>>> from sklearn.metrics import confusion_matrix
>>> from sklearn.svm import LinearSVC
>>> diabetes = datasets.load_diabetes()
>>> X = diabetes.data[:150]
>>> y = diabetes.target[:150]
>>> lasso = linear_model.Lasso()
Single metric evaluation using ``cross_validate``
>>> cv_results = cross_validate(lasso, X, y, cv=3)
>>> sorted(cv_results.keys())
['fit_time', 'score_time', 'test_score']
>>> cv_results['test_score']
array([0.3315057 , 0.08022103, 0.03531816])
Multiple metric evaluation using ``cross_validate``
(please refer the ``scoring`` parameter doc for more information)
>>> scores = cross_validate(lasso, X, y, cv=3,
...                         scoring=('r2', 'neg_mean_squared_error'),
...                         return_train_score=True)
>>> print(scores['test_neg_mean_squared_error'])
[-3635.5 -3573.3 -6114.7]
>>> print(scores['train_r2'])
[0.28009951 0.3908844  0.22784907]
Definition at line 124 of file _validation.py.
References _aggregate_score_dicts(), _insert_error_scores(), and _normalize_score_results().
Referenced by cross_val_score().
learning_curve()
sklearn.model_selection._validation.learning_curve (estimator, X, y, * , groups = None, train_sizes = np.linspace(0.1, 1.0, 5), cv = None, scoring = None, exploit_incremental_learning = False, n_jobs = None, pre_dispatch = "all", verbose = 0, shuffle = False, random_state = None, error_score = np.nan, return_times = False, fit_params = None, params = None)
Learning curve.
Determines cross-validated training and test scores for different training
set sizes.
A cross-validation generator splits the whole dataset k times in training
and test data. Subsets of the training set with varying sizes will be used
to train the estimator and a score for each training subset size and the
test set will be computed. Afterwards, the scores will be averaged over
all k runs for each training subset size.
Read more in the :ref:`User Guide <learning_curve>`.
Parameters
----------
estimator : object type that implements the "fit" method
    An object of that type which is cloned for each validation. It must
    also implement "predict" unless `scoring` is a callable that doesn't
    rely on "predict" to compute a score.
X : {array-like, sparse matrix} of shape (n_samples, n_features)
    Training vector, where `n_samples` is the number of samples and
    `n_features` is the number of features.
y : array-like of shape (n_samples,) or (n_samples, n_outputs) or None
    Target relative to X for classification or regression;
    None for unsupervised learning.
groups : array-like of shape (n_samples,), default=None
    Group labels for the samples used while splitting the dataset into
    train/test set. Only used in conjunction with a "Group" :term:`cv`
    instance (e.g., :class:`GroupKFold`).
    .. versionchanged:: 1.6
        ``groups`` can only be passed if metadata routing is not enabled
        via ``sklearn.set_config(enable_metadata_routing=True)``. When routing
        is enabled, pass ``groups`` alongside other metadata via the ``params``
        argument instead. E.g.:
        ``learning_curve(..., params={'groups': groups})``.
train_sizes : array-like of shape (n_ticks,), \
        default=np.linspace(0.1, 1.0, 5)
    Relative or absolute numbers of training examples that will be used to
    generate the learning curve. If the dtype is float, it is regarded as a
    fraction of the maximum size of the training set (that is determined
    by the selected validation method), i.e. it has to be within (0, 1].
    Otherwise it is interpreted as absolute sizes of the training sets.
    Note that for classification the number of samples usually has to
    be big enough to contain at least one sample from each class.
cv : int, cross-validation generator or an iterable, default=None
    Determines the cross-validation splitting strategy.
    Possible inputs for cv are:
    - None, to use the default 5-fold cross validation,
    - int, to specify the number of folds in a `(Stratified)KFold`,
    - :term:`CV splitter`,
    - An iterable yielding (train, test) splits as arrays of indices.
    For int/None inputs, if the estimator is a classifier and ``y`` is
    either binary or multiclass, :class:`StratifiedKFold` is used. In all
    other cases, :class:`KFold` is used. These splitters are instantiated
    with `shuffle=False` so the splits will be the same across calls.
    Refer :ref:`User Guide <cross_validation>` for the various
    cross-validation strategies that can be used here.
    .. versionchanged:: 0.22
        ``cv`` default value if None changed from 3-fold to 5-fold.
scoring : str or callable, default=None
    Scoring method to use to evaluate the training and test sets.
    - str: see :ref:`scoring_string_names` for options.
    - callable: a scorer callable object (e.g., function) with signature
      ``scorer(estimator, X, y)``. See :ref:`scoring_callable` for details.
    - `None`: the `estimator`'s
      :ref:`default evaluation criterion <scoring_api_overview>` is used.
exploit_incremental_learning : bool, default=False
    If the estimator supports incremental learning, this will be
    used to speed up fitting for different training set sizes.
n_jobs : int, default=None
    Number of jobs to run in parallel. Training the estimator and computing
    the score are parallelized over the different training and test sets.
    ``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.
    ``-1`` means using all processors. See :term:`Glossary <n_jobs>`
    for more details.
pre_dispatch : int or str, default='all'
    Number of predispatched jobs for parallel execution (default is
    all). The option can reduce the allocated memory. The str can
    be an expression like '2*n_jobs'.
verbose : int, default=0
    Controls the verbosity: the higher, the more messages.
shuffle : bool, default=False
    Whether to shuffle training data before taking prefixes of it
    based on``train_sizes``.
random_state : int, RandomState instance or None, default=None
    Used when ``shuffle`` is True. Pass an int for reproducible
    output across multiple function calls.
    See :term:`Glossary <random_state>`.
error_score : 'raise' or numeric, default=np.nan
    Value to assign to the score if an error occurs in estimator fitting.
    If set to 'raise', the error is raised.
    If a numeric value is given, FitFailedWarning is raised.
    .. versionadded:: 0.20
return_times : bool, default=False
    Whether to return the fit and score times.
fit_params : dict, default=None
    Parameters to pass to the fit method of the estimator.
    .. deprecated:: 1.6
        This parameter is deprecated and will be removed in version 1.8. Use
        ``params`` instead.
params : dict, default=None
    Parameters to pass to the `fit` method of the estimator and to the scorer.
    - If `enable_metadata_routing=False` (default): Parameters directly passed to
      the `fit` method of the estimator.
    - If `enable_metadata_routing=True`: Parameters safely routed to the `fit`
      method of the estimator. See :ref:`Metadata Routing User Guide
      <metadata_routing>` for more details.
    .. versionadded:: 1.6
Returns
-------
train_sizes_abs : array of shape (n_unique_ticks,)
    Numbers of training examples that has been used to generate the
    learning curve. Note that the number of ticks might be less
    than n_ticks because duplicate entries will be removed.
train_scores : array of shape (n_ticks, n_cv_folds)
    Scores on training sets.
test_scores : array of shape (n_ticks, n_cv_folds)
    Scores on test set.
fit_times : array of shape (n_ticks, n_cv_folds)
    Times spent for fitting in seconds. Only present if ``return_times``
    is True.
score_times : array of shape (n_ticks, n_cv_folds)
    Times spent for scoring in seconds. Only present if ``return_times``
    is True.
See Also
--------
LearningCurveDisplay.from_estimator : Plot a learning curve using an
    estimator and data.
Examples
--------
>>> from sklearn.datasets import make_classification
>>> from sklearn.tree import DecisionTreeClassifier
>>> from sklearn.model_selection import learning_curve
>>> X, y = make_classification(n_samples=100, n_features=10, random_state=42)
>>> tree = DecisionTreeClassifier(max_depth=4, random_state=42)
>>> train_size_abs, train_scores, test_scores = learning_curve(
...     tree, X, y, train_sizes=[0.3, 0.6, 0.9]
...)
>>> for train_size, cv_train_scores, cv_test_scores in zip(
...     train_size_abs, train_scores, test_scores
...):
...     print(f"{train_size} samples were used to train the model")
...     print(f"The average train accuracy is {cv_train_scores.mean():.2f}")
...     print(f"The average test accuracy is {cv_test_scores.mean():.2f}")
24 samples were used to train the model
The average train accuracy is 1.00
The average test accuracy is 0.85
48 samples were used to train the model
The average train accuracy is 1.00
The average test accuracy is 0.90
72 samples were used to train the model
The average train accuracy is 1.00
The average test accuracy is 0.93
Definition at line 1759 of file _validation.py.
References _aggregate_score_dicts(), _check_params_groups_deprecation(), and _translate_train_sizes().
permutation_test_score()
sklearn.model_selection._validation.permutation_test_score (estimator, X, y, * , groups = None, cv = None, n_permutations = 100, n_jobs = None, random_state = 0, verbose = 0, scoring = None, fit_params = None, params = None)
Evaluate the significance of a cross-validated score with permutations.
Permutes targets to generate 'randomized data' and compute the empirical
p-value against the null hypothesis that features and targets are
independent.
The p-value represents the fraction of randomized data sets where the
estimator performed as well or better than on the original data. A small
p-value suggests that there is a real dependency between features and
targets which has been used by the estimator to give good predictions.
A large p-value may be due to lack of real dependency between features
and targets or the estimator was not able to use the dependency to
give good predictions.
Read more in the :ref:`User Guide <permutation_test_score>`.
Parameters
----------
estimator : estimator object implementing 'fit'
    The object to use to fit the data.
X : array-like of shape at least 2D
    The data to fit.
y : array-like of shape (n_samples,) or (n_samples, n_outputs) or None
    The target variable to try to predict in the case of
    supervised learning.
groups : array-like of shape (n_samples,), default=None
    Labels to constrain permutation within groups, i.e. ``y`` values
    are permuted among samples with the same group identifier.
    When not specified, ``y`` values are permuted among all samples.
    When a grouped cross-validator is used, the group labels are
    also passed on to the ``split`` method of the cross-validator. The
    cross-validator uses them for grouping the samples  while splitting
    the dataset into train/test set.
    .. versionchanged:: 1.6
        ``groups`` can only be passed if metadata routing is not enabled
        via ``sklearn.set_config(enable_metadata_routing=True)``. When routing
        is enabled, pass ``groups`` alongside other metadata via the ``params``
        argument instead. E.g.:
        ``permutation_test_score(..., params={'groups': groups})``.
cv : int, cross-validation generator or an iterable, default=None
    Determines the cross-validation splitting strategy.
    Possible inputs for cv are:
    - `None`, to use the default 5-fold cross validation,
    - int, to specify the number of folds in a `(Stratified)KFold`,
    - :term:`CV splitter`,
    - An iterable yielding (train, test) splits as arrays of indices.
    For `int`/`None` inputs, if the estimator is a classifier and `y` is
    either binary or multiclass, :class:`StratifiedKFold` is used. In all
    other cases, :class:`KFold` is used. These splitters are instantiated
    with `shuffle=False` so the splits will be the same across calls.
    Refer :ref:`User Guide <cross_validation>` for the various
    cross-validation strategies that can be used here.
    .. versionchanged:: 0.22
        `cv` default value if `None` changed from 3-fold to 5-fold.
n_permutations : int, default=100
    Number of times to permute ``y``.
n_jobs : int, default=None
    Number of jobs to run in parallel. Training the estimator and computing
    the cross-validated score are parallelized over the permutations.
    ``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.
    ``-1`` means using all processors. See :term:`Glossary <n_jobs>`
    for more details.
random_state : int, RandomState instance or None, default=0
    Pass an int for reproducible output for permutation of
    ``y`` values among samples. See :term:`Glossary <random_state>`.
verbose : int, default=0
    The verbosity level.
scoring : str or callable, default=None
    Scoring method to use to evaluate the predictions on the validation set.
    - str: see :ref:`scoring_string_names` for options.
    - callable: a scorer callable object (e.g., function) with signature
      ``scorer(estimator, X, y)``, which should return only a single value.
      See :ref:`scoring_callable` for details.
    - `None`: the `estimator`'s
      :ref:`default evaluation criterion <scoring_api_overview>` is used.
fit_params : dict, default=None
    Parameters to pass to the fit method of the estimator.
    .. deprecated:: 1.6
        This parameter is deprecated and will be removed in version 1.6. Use
        ``params`` instead.
params : dict, default=None
    Parameters to pass to the `fit` method of the estimator, the scorer
    and the cv splitter.
    - If `enable_metadata_routing=False` (default): Parameters directly passed to
      the `fit` method of the estimator.
    - If `enable_metadata_routing=True`: Parameters safely routed to the `fit`
      method of the estimator, `cv` object and `scorer`. See :ref:`Metadata Routing
      User Guide <metadata_routing>` for more details.
    .. versionadded:: 1.6
Returns
-------
score : float
    The true score without permuting targets.
permutation_scores : array of shape (n_permutations,)
    The scores obtained for each permutations.
pvalue : float
    The p-value, which approximates the probability that the score would
    be obtained by chance. This is calculated as:
    `(C + 1) / (n_permutations + 1)`
    Where C is the number of permutations whose score >= the true score.
    The best possible p-value is 1/(n_permutations + 1), the worst is 1.0.
Notes
-----
This function implements Test 1 in:
Ojala and Garriga. `Permutation Tests for Studying Classifier Performance
<http://www.jmlr.org/papers/volume11/ojala10a/ojala10a.pdf>`_. The
Journal of Machine Learning Research (2010) vol. 11
Examples
--------
>>> from sklearn.datasets import make_classification
>>> from sklearn.linear_model import LogisticRegression
>>> from sklearn.model_selection import permutation_test_score
>>> X, y = make_classification(random_state=0)
>>> estimator = LogisticRegression()
>>> score, permutation_scores, pvalue = permutation_test_score(
...     estimator, X, y, random_state=0
...)
>>> print(f"Original Score: {score:.3f}")
Original Score: 0.810
>>> print(
...     f"Permutation Scores: {permutation_scores.mean():.3f} +/- "
...     f"{permutation_scores.std():.3f}"
...)
Permutation Scores: 0.505 +/- 0.057
>>> print(f"P-value: {pvalue:.3f}")
P-value: 0.010
Definition at line 1455 of file _validation.py.
References _check_params_groups_deprecation(), _permutation_test_score(), and _shuffle().
validation_curve()
sklearn.model_selection._validation.validation_curve (estimator, X, y, * , param_name, param_range, groups = None, cv = None, scoring = None, n_jobs = None, pre_dispatch = "all", verbose = 0, error_score = np.nan, fit_params = None, params = None)
Validation curve.
Determine training and test scores for varying parameter values.
Compute scores for an estimator with different values of a specified
parameter. This is similar to grid search with one parameter. However, this
will also compute training scores and is merely a utility for plotting the
results.
Read more in the :ref:`User Guide <validation_curve>`.
Parameters
----------
estimator : object type that implements the "fit" method
    An object of that type which is cloned for each validation. It must
    also implement "predict" unless `scoring` is a callable that doesn't
    rely on "predict" to compute a score.
X : {array-like, sparse matrix} of shape (n_samples, n_features)
    Training vector, where `n_samples` is the number of samples and
    `n_features` is the number of features.
y : array-like of shape (n_samples,) or (n_samples, n_outputs) or None
    Target relative to X for classification or regression;
    None for unsupervised learning.
param_name : str
    Name of the parameter that will be varied.
param_range : array-like of shape (n_values,)
    The values of the parameter that will be evaluated.
groups : array-like of shape (n_samples,), default=None
    Group labels for the samples used while splitting the dataset into
    train/test set. Only used in conjunction with a "Group" :term:`cv`
    instance (e.g., :class:`GroupKFold`).
    .. versionchanged:: 1.6
        ``groups`` can only be passed if metadata routing is not enabled
        via ``sklearn.set_config(enable_metadata_routing=True)``. When routing
        is enabled, pass ``groups`` alongside other metadata via the ``params``
        argument instead. E.g.:
        ``validation_curve(..., params={'groups': groups})``.
cv : int, cross-validation generator or an iterable, default=None
    Determines the cross-validation splitting strategy.
    Possible inputs for cv are:
    - None, to use the default 5-fold cross validation,
    - int, to specify the number of folds in a `(Stratified)KFold`,
    - :term:`CV splitter`,
    - An iterable yielding (train, test) splits as arrays of indices.
    For int/None inputs, if the estimator is a classifier and ``y`` is
    either binary or multiclass, :class:`StratifiedKFold` is used. In all
    other cases, :class:`KFold` is used. These splitters are instantiated
    with `shuffle=False` so the splits will be the same across calls.
    Refer :ref:`User Guide <cross_validation>` for the various
    cross-validation strategies that can be used here.
    .. versionchanged:: 0.22
        ``cv`` default value if None changed from 3-fold to 5-fold.
scoring : str or callable, default=None
    Scoring method to use to evaluate the training and test sets.
    - str: see :ref:`scoring_string_names` for options.
    - callable: a scorer callable object (e.g., function) with signature
      ``scorer(estimator, X, y)``. See :ref:`scoring_callable` for details.
    - `None`: the `estimator`'s
      :ref:`default evaluation criterion <scoring_api_overview>` is used.
n_jobs : int, default=None
    Number of jobs to run in parallel. Training the estimator and computing
    the score are parallelized over the combinations of each parameter
    value and each cross-validation split.
    ``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.
    ``-1`` means using all processors. See :term:`Glossary <n_jobs>`
    for more details.
pre_dispatch : int or str, default='all'
    Number of predispatched jobs for parallel execution (default is
    all). The option can reduce the allocated memory. The str can
    be an expression like '2*n_jobs'.
verbose : int, default=0
    Controls the verbosity: the higher, the more messages.
error_score : 'raise' or numeric, default=np.nan
    Value to assign to the score if an error occurs in estimator fitting.
    If set to 'raise', the error is raised.
    If a numeric value is given, FitFailedWarning is raised.
    .. versionadded:: 0.20
fit_params : dict, default=None
    Parameters to pass to the fit method of the estimator.
    .. deprecated:: 1.6
        This parameter is deprecated and will be removed in version 1.8. Use
        ``params`` instead.
params : dict, default=None
    Parameters to pass to the estimator, scorer and cross-validation object.
    - If `enable_metadata_routing=False` (default): Parameters directly passed to
      the `fit` method of the estimator.
    - If `enable_metadata_routing=True`: Parameters safely routed to the `fit`
      method of the estimator, to the scorer and to the cross-validation object.
      See :ref:`Metadata Routing User Guide <metadata_routing>` for more details.
    .. versionadded:: 1.6
Returns
-------
train_scores : array of shape (n_ticks, n_cv_folds)
    Scores on training sets.
test_scores : array of shape (n_ticks, n_cv_folds)
    Scores on test set.
See Also
--------
ValidationCurveDisplay.from_estimator : Plot the validation curve
    given an estimator, the data, and the parameter to vary.
Notes
-----
See :ref:`sphx_glr_auto_examples_model_selection_plot_train_error_vs_test_error.py`
Examples
--------
>>> import numpy as np
>>> from sklearn.datasets import make_classification
>>> from sklearn.model_selection import validation_curve
>>> from sklearn.linear_model import LogisticRegression
>>> X, y = make_classification(n_samples=1_000, random_state=0)
>>> logistic_regression = LogisticRegression()
>>> param_name, param_range = "C", np.logspace(-8, 3, 10)
>>> train_scores, test_scores = validation_curve(
...     logistic_regression, X, y, param_name=param_name, param_range=param_range
...)
>>> print(f"The average train accuracy is {train_scores.mean():.2f}")
The average train accuracy is 0.81
>>> print(f"The average test accuracy is {test_scores.mean():.2f}")
The average test accuracy is 0.81
Definition at line 2263 of file _validation.py.
References _aggregate_score_dicts(), and _check_params_groups_deprecation().
Variable Documentation
__all__
list sklearn.model_selection._validation.__all__ private
Initial value:
=  [
    "cross_val_predict",
    "cross_val_score",
    "cross_validate",
    "learning_curve",
    "permutation_test_score",
    "validation_curve",
]
Definition at line 47 of file _validation.py.