Code Cloning Analysis: pandas.core.ops.array_ops Namespace Reference
pandas.core.ops.array_ops Namespace Reference
Functions
fill_binop (left, right, fill_value)
comp_method_OBJECT_ARRAY (op, x, y)
_masked_arith_op (np.ndarray x, y, op)
_na_arithmetic_op (np.ndarray left, right, op, bool is_cmp=False)
arithmetic_op (ArrayLike left, Any right, op)
ArrayLike comparison_op (ArrayLike left, Any right, op)
na_logical_op (np.ndarray x, y, op)
ArrayLike logical_op (ArrayLike left, Any right, op)
get_array_op (op)
maybe_prepare_scalar_for_op (obj, Shape shape)
_bool_arith_check (op, np.ndarray a, b)
Variables
dict _BOOL_OP_NOT_ALLOWED
Detailed Description
Functions for arithmetic and comparison operations on NumPy arrays and
ExtensionArrays.
Function Documentation
_bool_arith_check()
pandas.core.ops.array_ops._bool_arith_check (op, np.ndarray a, b) protected
In contrast to numpy, pandas raises an error for certain operations
with booleans.
Definition at line 594 of file array_ops.py.
Referenced by arithmetic_op().
_masked_arith_op()
pandas.core.ops.array_ops._masked_arith_op (np.ndarray x, y, op) protected
If the given arithmetic operation fails, attempt it again on
only the non-null elements of the input array(s).
Parameters
----------
x : np.ndarray
y : np.ndarray, Series, Index
op : binary operator
Definition at line 133 of file array_ops.py.
Referenced by _na_arithmetic_op().
_na_arithmetic_op()
pandas.core.ops.array_ops._na_arithmetic_op (np.ndarray left, right, op, bool is_cmp = False) protected
Return the result of evaluating op on the passed in values.
If native types are not compatible, try coercion to object dtype.
Parameters
----------
left : np.ndarray
right : np.ndarray or scalar
    Excludes DataFrame, Series, Index, ExtensionArray.
is_cmp : bool, default False
    If this a comparison operation.
Returns
-------
array-like
Raises
------
TypeError : invalid operation
Definition at line 189 of file array_ops.py.
References _masked_arith_op().
Referenced by arithmetic_op(), and comparison_op().
arithmetic_op()
pandas.core.ops.array_ops.arithmetic_op (ArrayLike left, Any right, op)
Evaluate an arithmetic operation `+`, `-`, `*`, `/`, `//`, `%`, `**`, ...
Note: the caller is responsible for ensuring that numpy warnings are
suppressed (with np.errstate(all="ignore")) if needed.
Parameters
----------
left : np.ndarray or ExtensionArray
right : object
    Cannot be a DataFrame or Index.  Series is *not* excluded.
op : {operator.add, operator.sub, ...}
    Or one of the reversed variants from roperator.
Returns
-------
ndarray or ExtensionArray
    Or a 2-tuple of these in the case of divmod or rdivmod.
Definition at line 240 of file array_ops.py.
References _bool_arith_check(), and _na_arithmetic_op().
comp_method_OBJECT_ARRAY()
pandas.core.ops.array_ops.comp_method_OBJECT_ARRAY (op, x, y)
Definition at line 113 of file array_ops.py.
comparison_op()
ArrayLike pandas.core.ops.array_ops.comparison_op (ArrayLike left, Any right, op)
Evaluate a comparison operation `=`, `!=`, `>=`, `>`, `<=`, or `<`.
Note: the caller is responsible for ensuring that numpy warnings are
suppressed (with np.errstate(all="ignore")) if needed.
Parameters
----------
left : np.ndarray or ExtensionArray
right : object
    Cannot be a DataFrame, Series, or Index.
op : {operator.eq, operator.ne, operator.gt, operator.ge, operator.lt, operator.le}
Returns
-------
ndarray or ExtensionArray
Definition at line 288 of file array_ops.py.
References _na_arithmetic_op().
fill_binop()
pandas.core.ops.array_ops.fill_binop (left, right, fill_value)
If a non-None fill_value is given, replace null entries in left and right
with this value, but only in positions where _one_ of left/right is null,
not both.
Parameters
----------
left : array-like
right : array-like
fill_value : object
Returns
-------
left : array-like
right : array-like
Notes
-----
Makes copies if fill_value is not None and NAs are present.
Definition at line 72 of file array_ops.py.
get_array_op()
pandas.core.ops.array_ops.get_array_op (op)
Return a binary array operation corresponding to the given operator op.
Parameters
----------
op : function
    Binary operator from operator or roperator module.
Returns
-------
functools.partial
Definition at line 464 of file array_ops.py.
logical_op()
ArrayLike pandas.core.ops.array_ops.logical_op (ArrayLike left, Any right, op)
Evaluate a logical operation `|`, `&`, or `^`.
Parameters
----------
left : np.ndarray or ExtensionArray
right : object
    Cannot be a DataFrame, Series, or Index.
op : {operator.and_, operator.or_, operator.xor}
    Or one of the reversed variants from roperator.
Returns
-------
ndarray or ExtensionArray
Definition at line 393 of file array_ops.py.
maybe_prepare_scalar_for_op()
pandas.core.ops.array_ops.maybe_prepare_scalar_for_op (obj, Shape shape)
Cast non-pandas objects to pandas types to unify behavior of arithmetic
and comparison operations.
Parameters
----------
obj: object
shape : tuple[int]
Returns
-------
out : object
Notes
-----
Be careful to call this *after* determining the `name` attribute to be
attached to the result of the arithmetic operation.
Definition at line 507 of file array_ops.py.
na_logical_op()
pandas.core.ops.array_ops.na_logical_op (np.ndarray x, y, op)
Definition at line 352 of file array_ops.py.
Variable Documentation
_BOOL_OP_NOT_ALLOWED
dict pandas.core.ops.array_ops._BOOL_OP_NOT_ALLOWED protected
Initial value:
=  {
    operator.truediv,
    roperator.rtruediv,
    operator.floordiv,
    roperator.rfloordiv,
    operator.pow,
    roperator.rpow,
}
Definition at line 584 of file array_ops.py.