Code Cloning Analysis: scipy.ndimage.tests.test_splines Namespace Reference
scipy.ndimage.tests.test_splines Namespace Reference
Functions
get_spline_knot_values (order)
make_spline_knot_matrix (n, order, mode='mirror')
test_spline_filter_vs_matrix_solution (order, mode)
Detailed Description
Tests for spline filtering.
Function Documentation
get_spline_knot_values()
scipy.ndimage.tests.test_splines.get_spline_knot_values (order)
Knot values to the right of a B-spline's center.
Definition at line 10 of file test_splines.py.
Referenced by make_spline_knot_matrix().
make_spline_knot_matrix()
scipy.ndimage.tests.test_splines.make_spline_knot_matrix (n, order, mode = 'mirror')
Matrix to invert to find the spline coefficients.
Definition at line 22 of file test_splines.py.
References get_spline_knot_values(), make_spline_knot_matrix(), and scipy.ndimage._measurements.sum().
Referenced by make_spline_knot_matrix().
test_spline_filter_vs_matrix_solution()
scipy.ndimage.tests.test_splines.test_spline_filter_vs_matrix_solution (order, mode)
Definition at line 56 of file test_splines.py.