Code Cloning Analysis: matplotlib.testing.jpl_units.Duration.Duration Class Reference
matplotlib.testing.jpl_units.Duration.Duration Class Reference
Public Member Functions
__init__ (self, frame, seconds)
frame (self)
__abs__ (self)
__neg__ (self)
seconds (self)
__bool__ (self)
__add__ (self, rhs)
__sub__ (self, rhs)
__mul__ (self, rhs)
__str__ (self)
__repr__ (self)
checkSameFrame (self, rhs, func)
Static Public Attributes
list allowed = ["ET", "UTC"]
Protected Member Functions
_cmp (self, op, rhs)
Protected Attributes
_frame = frame
_seconds = seconds
Static Private Attributes
__eq__ = functools.partialmethod(_cmp, operator.eq)
__ne__ = functools.partialmethod(_cmp, operator.ne)
__lt__ = functools.partialmethod(_cmp, operator.lt)
__le__ = functools.partialmethod(_cmp, operator.le)
__gt__ = functools.partialmethod(_cmp, operator.gt)
__ge__ = functools.partialmethod(_cmp, operator.ge)
__rmul__ = __mul__
Detailed Description
Class Duration in development.
Definition at line 9 of file Duration.py.
Constructor & Destructor Documentation
__init__()
matplotlib.testing.jpl_units.Duration.Duration.__init__ (self, frame, seconds)
Create a new Duration object.
= ERROR CONDITIONS
- If the input frame is not in the allowed list, an error is thrown.
= INPUT VARIABLES
- frame     The frame of the duration.  Must be 'ET' or 'UTC'
- seconds  The number of seconds in the Duration.
Definition at line 14 of file Duration.py.
References _frame, _seconds, and allowed.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__abs__()
matplotlib.testing.jpl_units.Duration.Duration.__abs__ (self)
Return the absolute value of the duration.
Definition at line 33 of file Duration.py.
References _frame, and _seconds.
__add__()
matplotlib.testing.jpl_units.Duration.Duration.__add__ (self, rhs)
Add two Durations.
= ERROR CONDITIONS
- If the input rhs is not in the same frame, an error is thrown.
= INPUT VARIABLES
- rhs     The Duration to add.
= RETURN VALUE
- Returns the sum of ourselves and the input Duration.
Definition at line 62 of file Duration.py.
References _frame, _seconds, and checkSameFrame().
Referenced by scipy.signal._ltisys.StateSpace.__add__(), scipy.sparse.linalg._interface.LinearOperator._rdot(), and scipy.sparse._base._spbase.power().
__bool__()
matplotlib.testing.jpl_units.Duration.Duration.__bool__ (self)
Definition at line 45 of file Duration.py.
__mul__()
matplotlib.testing.jpl_units.Duration.Duration.__mul__ (self, rhs)
Scale a UnitDbl by a value.
= INPUT VARIABLES
- rhs     The scalar to multiply by.
= RETURN VALUE
- Returns the scaled Duration.
Definition at line 100 of file Duration.py.
References _frame, and _seconds.
Referenced by pip._vendor.pyparsing.core.ParserElement.__mul__(), pyparsing.core.ParserElement.__mul__(), scipy.signal._ltisys.StateSpace.__truediv__(), and scipy.sparse.linalg._interface.LinearOperator.dot().
__neg__()
matplotlib.testing.jpl_units.Duration.Duration.__neg__ (self)
Return the negative value of this Duration.
Definition at line 37 of file Duration.py.
References _frame, and _seconds.
__repr__()
matplotlib.testing.jpl_units.Duration.Duration.__repr__ (self)
Print the Duration.
Definition at line 118 of file Duration.py.
__str__()
matplotlib.testing.jpl_units.Duration.Duration.__str__ (self)
Print the Duration.
Definition at line 114 of file Duration.py.
Referenced by numpy.polynomial._polybase.ABCPolyBase._get_coefficients().
__sub__()
matplotlib.testing.jpl_units.Duration.Duration.__sub__ (self, rhs)
Subtract two Durations.
= ERROR CONDITIONS
- If the input rhs is not in the same frame, an error is thrown.
= INPUT VARIABLES
- rhs     The Duration to subtract.
= RETURN VALUE
- Returns the difference of ourselves and the input Duration.
Definition at line 84 of file Duration.py.
References _frame, _seconds, and checkSameFrame().
_cmp()
matplotlib.testing.jpl_units.Duration.Duration._cmp (self, op, rhs) protected
Check that *self* and *rhs* share frames; compare them using *op*.
Definition at line 48 of file Duration.py.
References _seconds, and checkSameFrame().
checkSameFrame()
matplotlib.testing.jpl_units.Duration.Duration.checkSameFrame (self, rhs, func)
Check to see if frames are the same.
= ERROR CONDITIONS
- If the frame of the rhs Duration is not the same as our frame,
  an error is thrown.
= INPUT VARIABLES
- rhs     The Duration to check for the same frame
- func    The name of the function doing the check.
Definition at line 122 of file Duration.py.
References _frame.
Referenced by __add__(), __sub__(), and _cmp().
frame()
matplotlib.testing.jpl_units.Duration.Duration.frame (self)
Return the frame the duration is in.
Definition at line 29 of file Duration.py.
References _frame.
Referenced by PIL.IcoImagePlugin.IcoFile.getimage().
seconds()
matplotlib.testing.jpl_units.Duration.Duration.seconds (self)
Return the number of seconds in the Duration.
Definition at line 41 of file Duration.py.
References _seconds.
Member Data Documentation
__eq__
matplotlib.testing.jpl_units.Duration.Duration.__eq__ = functools.partialmethod(_cmp, operator.eq) static private
Definition at line 55 of file Duration.py.
Referenced by fontTools.ttLib.tables.ttProgram.Program.__bool__(), pandas.core.dtypes.base.ExtensionDtype.__eq__(), pandas.io.pytables.IndexCol.__eq__(), fontTools.ttLib.tables._g_l_y_f.GlyphCoordinates.__ne__(), pip._vendor.msgpack.ext.Timestamp.__ne__(), numpy.polynomial._polybase.ABCPolyBase._str_term_ascii(), fontTools.ttLib.tables._g_l_y_f.Glyph.drawPoints(), fontTools.ttLib.tables.otBase.OTTableWriter.getDataForHarfbuzz(), pip._vendor.distlib.version.Matcher.match(), pandas.core.dtypes.dtypes.PeriodDtype.na_value(), dateutil.relativedelta.relativedelta.normalized(), and numpy.lib.polynomial.poly1d.roots().
__ge__
matplotlib.testing.jpl_units.Duration.Duration.__ge__ = functools.partialmethod(_cmp, operator.ge) static private
Definition at line 60 of file Duration.py.
__gt__
matplotlib.testing.jpl_units.Duration.Duration.__gt__ = functools.partialmethod(_cmp, operator.gt) static private
Definition at line 59 of file Duration.py.
__le__
matplotlib.testing.jpl_units.Duration.Duration.__le__ = functools.partialmethod(_cmp, operator.le) static private
Definition at line 58 of file Duration.py.
__lt__
matplotlib.testing.jpl_units.Duration.Duration.__lt__ = functools.partialmethod(_cmp, operator.lt) static private
Definition at line 57 of file Duration.py.
__ne__
matplotlib.testing.jpl_units.Duration.Duration.__ne__ = functools.partialmethod(_cmp, operator.ne) static private
Definition at line 56 of file Duration.py.
__rmul__
matplotlib.testing.jpl_units.Duration.Duration.__rmul__ = __mul__ static private
Definition at line 112 of file Duration.py.
Referenced by scipy.sparse.linalg._interface.LinearOperator.dot().
_frame
matplotlib.testing.jpl_units.Duration.Duration._frame = frame protected
Definition at line 26 of file Duration.py.
Referenced by __abs__(), __add__(), matplotlib.testing.jpl_units.Epoch.Epoch.__add__(), __init__(), matplotlib.testing.jpl_units.Epoch.Epoch.__init__(), __mul__(), __neg__(), __sub__(), matplotlib.testing.jpl_units.Epoch.Epoch.__sub__(), matplotlib.testing.jpl_units.Epoch.Epoch._cmp(), checkSameFrame(), and frame().
_seconds
matplotlib.testing.jpl_units.Duration.Duration._seconds = seconds protected
Definition at line 27 of file Duration.py.
Referenced by __abs__(), __add__(), __init__(), matplotlib.testing.jpl_units.Epoch.Epoch.__init__(), __mul__(), __neg__(), __sub__(), _cmp(), and seconds().
allowed
matplotlib.testing.jpl_units.Duration.Duration.allowed = ["ET", "UTC"] static
Definition at line 12 of file Duration.py.
Referenced by __init__(), matplotlib.testing.jpl_units.Epoch.Epoch.__init__(), matplotlib.testing.jpl_units.UnitDbl.UnitDbl.__init__(), and matplotlib.testing.jpl_units.UnitDbl.UnitDbl.convert().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/testing/jpl_units/Duration.py