Code Cloning Analysis: fontTools.varLib.interpolatablePlot.OverridingDict Class Reference
fontTools.varLib.interpolatablePlot.OverridingDict Class Reference
Public Member Functions
__init__ (self, parent_dict)
__missing__ (self, key)
Public Attributes
parent_dict = parent_dict
Detailed Description
Definition at line 31 of file interpolatablePlot.py.
Constructor & Destructor Documentation
__init__()
fontTools.varLib.interpolatablePlot.OverridingDict.__init__ (self, parent_dict)
Definition at line 32 of file interpolatablePlot.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__missing__()
fontTools.varLib.interpolatablePlot.OverridingDict.__missing__ (self, key)
Definition at line 35 of file interpolatablePlot.py.
Referenced by pip._vendor.distlib.compat.ChainMap.__init__().
Member Data Documentation
parent_dict
fontTools.varLib.interpolatablePlot.OverridingDict.parent_dict = parent_dict
Definition at line 33 of file interpolatablePlot.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/varLib/interpolatablePlot.py