Code Cloning Analysis: numpy.ctypeslib Namespace Reference
numpy.ctypeslib Namespace Reference
Classes
class _concrete_ndptr
class _ndptr
Functions
_dummy (*args, **kwds)
load_library (libname, loader_path)
_num_fromflags (flaglist)
_flags_fromnum (num)
ndpointer (dtype=None, ndim=None, shape=None, flags=None)
_ctype_ndarray (element_type, shape)
_get_scalar_type_map ()
_ctype_from_dtype_scalar (dtype)
_ctype_from_dtype_subarray (dtype)
_ctype_from_dtype_structured (dtype)
_ctype_from_dtype (dtype)
as_ctypes_type (dtype)
as_array (obj, shape=None)
as_ctypes (obj)
Variables
list __all__
ctypes = None
load_library = _dummy
as_ctypes = _dummy
as_array = _dummy
_ndptr_base = object
c_intp = nic._getintp_ctype()
list _flagnames
dict _pointer_type_cache = {}
_scalar_type_map = _get_scalar_type_map()
Detailed Description
============================
``ctypes`` Utility Functions
============================
See Also
--------
load_library : Load a C library.
ndpointer : Array restype/argtype with verification.
as_ctypes : Create a ctypes array from an ndarray.
as_array : Create an ndarray from a ctypes array.
References
----------
.. [1] "SciPy Cookbook: ctypes", https://scipy-cookbook.readthedocs.io/items/Ctypes.html
Examples
--------
Load the C library:
>>> _lib = np.ctypeslib.load_library('libmystuff', '.')     #doctest: +SKIP
Our result type, an ndarray that must be of type double, be 1-dimensional
and is C-contiguous in memory:
>>> array_1d_double = np.ctypeslib.ndpointer(
...                          dtype=np.double,
...                          ndim=1, flags='CONTIGUOUS')    #doctest: +SKIP
Our C-function typically takes an array and updates its values
in-place.  For example::
    void foo_func(double* x, int length)
    {
        int i;
        for (i = 0; i < length; i++) {
            x[i] = i*i;
        }
    }
We wrap it using:
>>> _lib.foo_func.restype = None                      #doctest: +SKIP
>>> _lib.foo_func.argtypes = [array_1d_double, c_int] #doctest: +SKIP
Then, we're ready to call ``foo_func``:
>>> out = np.empty(15, dtype=np.double)
>>> _lib.foo_func(out, len(out))                #doctest: +SKIP
Function Documentation
_ctype_from_dtype()
numpy.ctypeslib._ctype_from_dtype (dtype) protected
Definition at line 456 of file ctypeslib.py.
_ctype_from_dtype_scalar()
numpy.ctypeslib._ctype_from_dtype_scalar (dtype) protected
Definition at line 377 of file ctypeslib.py.
_ctype_from_dtype_structured()
numpy.ctypeslib._ctype_from_dtype_structured (dtype) protected
Definition at line 402 of file ctypeslib.py.
_ctype_from_dtype_subarray()
numpy.ctypeslib._ctype_from_dtype_subarray (dtype) protected
Definition at line 396 of file ctypeslib.py.
_ctype_ndarray()
numpy.ctypeslib._ctype_ndarray (element_type, shape) protected
 Create an ndarray of the given element type and shape
Definition at line 351 of file ctypeslib.py.
Referenced by _get_scalar_type_map(), as_array(), and as_ctypes().
_dummy()
numpy.ctypeslib._dummy (* args, ** kwds) protected
Dummy object that raises an ImportError if ctypes is not available.
Raises
------
ImportError
    If ctypes is not available.
Definition at line 67 of file ctypeslib.py.
_flags_fromnum()
numpy.ctypeslib._flags_fromnum (num) protected
Definition at line 172 of file ctypeslib.py.
_get_scalar_type_map()
numpy.ctypeslib._get_scalar_type_map () protected
Return a dictionary mapping native endian scalar dtype to ctypes types
Definition at line 360 of file ctypeslib.py.
References _ctype_ndarray(), _get_scalar_type_map(), numpy.core.fromnumeric.all(), and numpy.core.fromnumeric.max().
Referenced by _get_scalar_type_map().
_num_fromflags()
numpy.ctypeslib._num_fromflags (flaglist) protected
Definition at line 164 of file ctypeslib.py.
as_array()
numpy.ctypeslib.as_array (obj, shape = None)
Create a numpy array from a ctypes array or POINTER.
The numpy array shares the memory with the ctypes object.
The shape parameter must be given if converting from a ctypes POINTER.
The shape parameter is ignored if converting from a ctypes array
Definition at line 506 of file ctypeslib.py.
References _ctype_ndarray().
as_ctypes()
numpy.ctypeslib.as_ctypes (obj)
Create and return a ctypes object from a numpy array.  Actually
anything that exposes the __array_interface__ is accepted.
Definition at line 527 of file ctypeslib.py.
References _ctype_ndarray(), and as_ctypes_type().
as_ctypes_type()
numpy.ctypeslib.as_ctypes_type (dtype)
Convert a dtype into a ctypes type.
Parameters
----------
dtype : dtype
The dtype to convert
Returns
-------
ctype
A ctype scalar, union, array, or struct
Raises
------
NotImplementedError
If the conversion is not possible
Notes
-----
This function does not losslessly round-trip in either direction.
``np.dtype(as_ctypes_type(dt))`` will:
- insert padding fields
- reorder fields to be sorted by offset
- discard field titles
``as_ctypes_type(np.dtype(ctype))`` will:
- discard the class names of `ctypes.Structure`\ s and
`ctypes.Union`\ s
- convert single-element `ctypes.Union`\ s into single-element
`ctypes.Structure`\ s
- insert padding fields
Definition at line 465 of file ctypeslib.py.
Referenced by as_ctypes().
load_library()
numpy.ctypeslib.load_library (libname, loader_path)
It is possible to load a library using
>>> lib = ctypes.cdll[<full_path_name>] # doctest: +SKIP
But there are cross-platform considerations, such as library file extensions,
plus the fact Windows will just load the first library it finds with that name.
NumPy supplies the load_library function as a convenience.
.. versionchanged:: 1.20.0
    Allow libname and loader_path to take any
    :term:`python:path-like object`.
Parameters
----------
libname : path-like
    Name of the library, which can have 'lib' as a prefix,
    but without an extension.
loader_path : path-like
    Where the library can be found.
Returns
-------
ctypes.cdll[libpath] : library object
   A ctypes library object
Raises
------
OSError
    If there is no library with the expected extension, or the
    library is defective and cannot be loaded.
Definition at line 90 of file ctypeslib.py.
ndpointer()
numpy.ctypeslib.ndpointer (dtype = None, ndim = None, shape = None, flags = None)
Array-checking restype/argtypes.
An ndpointer instance is used to describe an ndarray in restypes
and argtypes specifications.  This approach is more flexible than
using, for example, ``POINTER(c_double)``, since several restrictions
can be specified, which are verified upon calling the ctypes function.
These include data type, number of dimensions, shape and flags.  If a
given array does not satisfy the specified restrictions,
a ``TypeError`` is raised.
Parameters
----------
dtype : data-type, optional
    Array data-type.
ndim : int, optional
    Number of array dimensions.
shape : tuple of ints, optional
    Array shape.
flags : str or tuple of str
    Array flags; may be one or more of:
      - C_CONTIGUOUS / C / CONTIGUOUS
      - F_CONTIGUOUS / F / FORTRAN
      - OWNDATA / O
      - WRITEABLE / W
      - ALIGNED / A
      - WRITEBACKIFCOPY / X
Returns
-------
klass : ndpointer type object
    A type object, which is an ``_ndtpr`` instance containing
    dtype, ndim, shape and flags information.
Raises
------
TypeError
    If a given array does not satisfy the specified restrictions.
Examples
--------
>>> clib.somefunc.argtypes = [np.ctypeslib.ndpointer(dtype=np.float64,
...                                                  ndim=1,
...                                                  flags='C_CONTIGUOUS')]
... #doctest: +SKIP
>>> clib.somefunc(np.array([1, 2, 3], dtype=np.float64))
... #doctest: +SKIP
Definition at line 233 of file ctypeslib.py.
Variable Documentation
__all__
list numpy.ctypeslib.__all__ private
Initial value:
=  ['load_library', 'ndpointer', 'c_intp', 'as_ctypes', 'as_array',
           'as_ctypes_type']
Definition at line 52 of file ctypeslib.py.
_flagnames
list numpy.ctypeslib._flagnames protected
Initial value:
=  ['C_CONTIGUOUS', 'F_CONTIGUOUS', 'ALIGNED', 'WRITEABLE',
              'OWNDATA', 'WRITEBACKIFCOPY']
Definition at line 170 of file ctypeslib.py.
_ndptr_base
numpy.ctypeslib._ndptr_base = object protected
Definition at line 82 of file ctypeslib.py.
_pointer_type_cache
dict numpy.ctypeslib._pointer_type_cache = {} protected
Definition at line 232 of file ctypeslib.py.
_scalar_type_map
numpy.ctypeslib._scalar_type_map = _get_scalar_type_map() protected
Definition at line 374 of file ctypeslib.py.
as_array
numpy.ctypeslib.as_array = _dummy
Definition at line 80 of file ctypeslib.py.
as_ctypes
numpy.ctypeslib.as_ctypes = _dummy
Definition at line 79 of file ctypeslib.py.
c_intp
numpy.ctypeslib.c_intp = nic._getintp_ctype()
Definition at line 85 of file ctypeslib.py.
ctypes
numpy.ctypeslib.ctypes = None
Definition at line 64 of file ctypeslib.py.
load_library
numpy.ctypeslib.load_library = _dummy
Definition at line 78 of file ctypeslib.py.