Code Cloning Analysis: sklearn.model_selection.tests.test_validation Namespace Reference
sklearn.model_selection.tests.test_validation Namespace Reference
Classes
class DataDependentFailingClassifier
class MockClassifier
class MockEstimatorWithParameter
class MockEstimatorWithSingleFitCallAllowed
class MockImprovingEstimator
class MockIncrementalImprovingEstimator
class RFWithDecisionFunction
Functions
test_cross_val_score (coo_container)
test_cross_validate_many_jobs ()
test_cross_validate_invalid_scoring_param ()
test_cross_validate_nested_estimator ()
test_cross_validate (bool use_sparse, csr_container)
check_cross_validate_single_metric (clf, X, y, scores, cv)
check_cross_validate_multi_metric (clf, X, y, scores, cv)
test_cross_val_score_predict_groups ()
test_cross_val_score_pandas ()
test_cross_val_score_mask ()
test_cross_val_score_precomputed ()
test_cross_val_score_fit_params (coo_container)
test_cross_val_score_score_func ()
test_cross_val_score_with_score_func_classification ()
test_cross_val_score_with_score_func_regression ()
test_permutation_score (coo_container)
test_permutation_test_score_allow_nans ()
test_permutation_test_score_params ()
test_cross_val_score_allow_nans ()
test_cross_val_score_multilabel ()
test_cross_val_predict (coo_container)
test_cross_val_predict_decision_function_shape ()
test_cross_val_predict_predict_proba_shape ()
test_cross_val_predict_predict_log_proba_shape ()
test_cross_val_predict_input_types (coo_container)
test_cross_val_predict_pandas ()
test_cross_val_predict_unbalanced ()
test_cross_val_predict_y_none ()
test_cross_val_score_sparse_fit_params (coo_container)
test_learning_curve ()
test_learning_curve_unsupervised ()
test_learning_curve_verbose ()
test_learning_curve_incremental_learning_not_possible ()
test_learning_curve_incremental_learning ()
test_learning_curve_incremental_learning_unsupervised ()
test_learning_curve_batch_and_incremental_learning_are_equal ()
test_learning_curve_n_sample_range_out_of_bounds ()
test_learning_curve_remove_duplicate_sample_sizes ()
test_learning_curve_with_boolean_indices ()
test_learning_curve_with_shuffle ()
test_learning_curve_params ()
test_learning_curve_incremental_learning_params ()
test_validation_curve ()
test_validation_curve_clone_estimator ()
test_validation_curve_cv_splits_consistency ()
test_validation_curve_params ()
test_check_is_permutation ()
test_cross_val_predict_sparse_prediction (csr_container)
check_cross_val_predict_binary (est, X, y, method)
check_cross_val_predict_multiclass (est, X, y, method)
check_cross_val_predict_multilabel (est, X, y, method)
check_cross_val_predict_with_method_binary (est)
check_cross_val_predict_with_method_multiclass (est)
test_cross_val_predict_with_method ()
test_cross_val_predict_method_checking ()
test_gridsearchcv_cross_val_predict_with_method ()
test_cross_val_predict_with_method_multilabel_ovr ()
test_cross_val_predict_with_method_multilabel_rf ()
test_cross_val_predict_with_method_rare_class ()
test_cross_val_predict_with_method_multilabel_rf_rare_class ()
get_expected_predictions (X, y, cv, classes, est, method)
test_cross_val_predict_class_subset ()
test_score_memmap ()
test_permutation_test_score_pandas ()
test_fit_and_score_failing ()
test_fit_and_score_working ()
test_cross_validate_some_failing_fits_warning (error_score)
test_cross_validate_all_failing_fits_error (error_score)
_failing_scorer (estimator, X, y, error_msg)
test_cross_val_score_failing_scorer (error_score)
test_cross_validate_failing_scorer (error_score, return_train_score, with_multimetric)
three_params_scorer (i, j, k)
test_fit_and_score_verbosity (capsys, train_score, scorer, verbose, split_prg, cdt_prg, expected)
test_score ()
test_callable_multimetric_confusion_matrix_cross_validate ()
test_learning_curve_partial_fit_regressors ()
test_learning_curve_some_failing_fits_warning (global_random_seed)
test_cross_validate_return_indices (global_random_seed)
test_fit_param_deprecation (func, extra_args)
test_groups_with_routing_validation (func, extra_args)
test_cross_validate_params_none (func, extra_args)
test_passed_unrequested_metadata (func, extra_args)
test_validation_functions_routing (func, extra_args)
test_learning_curve_exploit_incremental_learning_routing ()
Variables
X = np.ones((15, 2))
y = np.array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 6])
y2 = np.array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3])
P = np.eye(5)
Detailed Description
Test the validation module
Function Documentation
_failing_scorer()
sklearn.model_selection.tests.test_validation._failing_scorer (estimator, X, y, error_msg) protected
Definition at line 2196 of file test_validation.py.
check_cross_val_predict_binary()
sklearn.model_selection.tests.test_validation.check_cross_val_predict_binary (est, X, y, method)
Helper for tests of cross_val_predict with binary classification
Definition at line 1758 of file test_validation.py.
Referenced by check_cross_val_predict_multilabel().
check_cross_val_predict_multiclass()
sklearn.model_selection.tests.test_validation.check_cross_val_predict_multiclass (est, X, y, method)
Helper for tests of cross_val_predict with multiclass classification
Definition at line 1779 of file test_validation.py.
Referenced by check_cross_val_predict_multilabel().
check_cross_val_predict_multilabel()
sklearn.model_selection.tests.test_validation.check_cross_val_predict_multilabel (est, X, y, method)
Check the output of cross_val_predict for 2D targets using
Estimators which provide a predictions as a list with one
element per class.
Definition at line 1807 of file test_validation.py.
References check_cross_val_predict_binary(), and check_cross_val_predict_multiclass().
check_cross_val_predict_with_method_binary()
sklearn.model_selection.tests.test_validation.check_cross_val_predict_with_method_binary (est)
Definition at line 1859 of file test_validation.py.
check_cross_val_predict_with_method_multiclass()
sklearn.model_selection.tests.test_validation.check_cross_val_predict_with_method_multiclass (est)
Definition at line 1867 of file test_validation.py.
check_cross_validate_multi_metric()
sklearn.model_selection.tests.test_validation.check_cross_validate_multi_metric (clf, X, y, scores, cv)
Definition at line 530 of file test_validation.py.
check_cross_validate_single_metric()
sklearn.model_selection.tests.test_validation.check_cross_validate_single_metric (clf, X, y, scores, cv)
Definition at line 464 of file test_validation.py.
get_expected_predictions()
sklearn.model_selection.tests.test_validation.get_expected_predictions (X, y, cv, classes, est, method)
Definition at line 1974 of file test_validation.py.
test_callable_multimetric_confusion_matrix_cross_validate()
sklearn.model_selection.tests.test_validation.test_callable_multimetric_confusion_matrix_cross_validate ()
Definition at line 2382 of file test_validation.py.
test_check_is_permutation()
sklearn.model_selection.tests.test_validation.test_check_is_permutation ()
Definition at line 1725 of file test_validation.py.
test_cross_val_predict()
sklearn.model_selection.tests.test_validation.test_cross_val_predict (coo_container)
Definition at line 926 of file test_validation.py.
test_cross_val_predict_class_subset()
sklearn.model_selection.tests.test_validation.test_cross_val_predict_class_subset ()
Definition at line 1994 of file test_validation.py.
test_cross_val_predict_decision_function_shape()
sklearn.model_selection.tests.test_validation.test_cross_val_predict_decision_function_shape ()
Definition at line 982 of file test_validation.py.
test_cross_val_predict_input_types()
sklearn.model_selection.tests.test_validation.test_cross_val_predict_input_types (coo_container)
Definition at line 1055 of file test_validation.py.
test_cross_val_predict_method_checking()
sklearn.model_selection.tests.test_validation.test_cross_val_predict_method_checking ()
Definition at line 1880 of file test_validation.py.
test_cross_val_predict_pandas()
sklearn.model_selection.tests.test_validation.test_cross_val_predict_pandas ()
Definition at line 1108 of file test_validation.py.
test_cross_val_predict_predict_log_proba_shape()
sklearn.model_selection.tests.test_validation.test_cross_val_predict_predict_log_proba_shape ()
Definition at line 1042 of file test_validation.py.
test_cross_val_predict_predict_proba_shape()
sklearn.model_selection.tests.test_validation.test_cross_val_predict_predict_proba_shape ()
Definition at line 1030 of file test_validation.py.
test_cross_val_predict_sparse_prediction()
sklearn.model_selection.tests.test_validation.test_cross_val_predict_sparse_prediction (csr_container)
Definition at line 1740 of file test_validation.py.
test_cross_val_predict_unbalanced()
sklearn.model_selection.tests.test_validation.test_cross_val_predict_unbalanced ()
Definition at line 1126 of file test_validation.py.
test_cross_val_predict_with_method()
sklearn.model_selection.tests.test_validation.test_cross_val_predict_with_method ()
Definition at line 1875 of file test_validation.py.
test_cross_val_predict_with_method_multilabel_ovr()
sklearn.model_selection.tests.test_validation.test_cross_val_predict_with_method_multilabel_ovr ()
Definition at line 1900 of file test_validation.py.
test_cross_val_predict_with_method_multilabel_rf()
sklearn.model_selection.tests.test_validation.test_cross_val_predict_with_method_multilabel_rf ()
Definition at line 1926 of file test_validation.py.
test_cross_val_predict_with_method_multilabel_rf_rare_class()
sklearn.model_selection.tests.test_validation.test_cross_val_predict_with_method_multilabel_rf_rare_class ()
Definition at line 1957 of file test_validation.py.
test_cross_val_predict_with_method_rare_class()
sklearn.model_selection.tests.test_validation.test_cross_val_predict_with_method_rare_class ()
Definition at line 1943 of file test_validation.py.
test_cross_val_predict_y_none()
sklearn.model_selection.tests.test_validation.test_cross_val_predict_y_none ()
Definition at line 1148 of file test_validation.py.
test_cross_val_score()
sklearn.model_selection.tests.test_validation.test_cross_val_score (coo_container)
Definition at line 286 of file test_validation.py.
test_cross_val_score_allow_nans()
sklearn.model_selection.tests.test_validation.test_cross_val_score_allow_nans ()
Definition at line 881 of file test_validation.py.
test_cross_val_score_failing_scorer()
sklearn.model_selection.tests.test_validation.test_cross_val_score_failing_scorer (error_score)
Definition at line 2202 of file test_validation.py.
test_cross_val_score_fit_params()
sklearn.model_selection.tests.test_validation.test_cross_val_score_fit_params (coo_container)
Definition at line 691 of file test_validation.py.
test_cross_val_score_mask()
sklearn.model_selection.tests.test_validation.test_cross_val_score_mask ()
Definition at line 644 of file test_validation.py.
test_cross_val_score_multilabel()
sklearn.model_selection.tests.test_validation.test_cross_val_score_multilabel ()
Definition at line 895 of file test_validation.py.
test_cross_val_score_pandas()
sklearn.model_selection.tests.test_validation.test_cross_val_score_pandas ()
Definition at line 625 of file test_validation.py.
test_cross_val_score_precomputed()
sklearn.model_selection.tests.test_validation.test_cross_val_score_precomputed ()
Definition at line 663 of file test_validation.py.
test_cross_val_score_predict_groups()
sklearn.model_selection.tests.test_validation.test_cross_val_score_predict_groups ()
Definition at line 603 of file test_validation.py.
test_cross_val_score_score_func()
sklearn.model_selection.tests.test_validation.test_cross_val_score_score_func ()
Definition at line 726 of file test_validation.py.
test_cross_val_score_sparse_fit_params()
sklearn.model_selection.tests.test_validation.test_cross_val_score_sparse_fit_params (coo_container)
Definition at line 1162 of file test_validation.py.
test_cross_val_score_with_score_func_classification()
sklearn.model_selection.tests.test_validation.test_cross_val_score_with_score_func_classification ()
Definition at line 742 of file test_validation.py.
test_cross_val_score_with_score_func_regression()
sklearn.model_selection.tests.test_validation.test_cross_val_score_with_score_func_regression ()
Definition at line 761 of file test_validation.py.
test_cross_validate()
sklearn.model_selection.tests.test_validation.test_cross_validate (bool use_sparse, csr_container)
Definition at line 409 of file test_validation.py.
test_cross_validate_all_failing_fits_error()
sklearn.model_selection.tests.test_validation.test_cross_validate_all_failing_fits_error (error_score)
Definition at line 2173 of file test_validation.py.
test_cross_validate_failing_scorer()
sklearn.model_selection.tests.test_validation.test_cross_validate_failing_scorer (error_score, return_train_score, with_multimetric)
Definition at line 2232 of file test_validation.py.
test_cross_validate_invalid_scoring_param()
sklearn.model_selection.tests.test_validation.test_cross_validate_invalid_scoring_param ()
Definition at line 336 of file test_validation.py.
test_cross_validate_many_jobs()
sklearn.model_selection.tests.test_validation.test_cross_validate_many_jobs ()
Definition at line 326 of file test_validation.py.
test_cross_validate_nested_estimator()
sklearn.model_selection.tests.test_validation.test_cross_validate_nested_estimator ()
Definition at line 388 of file test_validation.py.
test_cross_validate_params_none()
sklearn.model_selection.tests.test_validation.test_cross_validate_params_none (func, extra_args)
Test that no errors are raised when passing `params=None`, which is the
default value.
Non-regression test for: https://github.com/scikit-learn/scikit-learn/issues/30447
Definition at line 2538 of file test_validation.py.
test_cross_validate_return_indices()
sklearn.model_selection.tests.test_validation.test_cross_validate_return_indices (global_random_seed)
Check the behaviour of `return_indices` in `cross_validate`.
Definition at line 2442 of file test_validation.py.
test_cross_validate_some_failing_fits_warning()
sklearn.model_selection.tests.test_validation.test_cross_validate_some_failing_fits_warning (error_score)
Definition at line 2145 of file test_validation.py.
test_fit_and_score_failing()
sklearn.model_selection.tests.test_validation.test_fit_and_score_failing ()
Definition at line 2080 of file test_validation.py.
test_fit_and_score_verbosity()
sklearn.model_selection.tests.test_validation.test_fit_and_score_verbosity (capsys, train_score, scorer, verbose, split_prg, cdt_prg, expected)
Definition at line 2333 of file test_validation.py.
test_fit_and_score_working()
sklearn.model_selection.tests.test_validation.test_fit_and_score_working ()
Definition at line 2107 of file test_validation.py.
test_fit_param_deprecation()
sklearn.model_selection.tests.test_validation.test_fit_param_deprecation (func, extra_args)
Check that we warn about deprecating `fit_params`.
Definition at line 2480 of file test_validation.py.
test_gridsearchcv_cross_val_predict_with_method()
sklearn.model_selection.tests.test_validation.test_gridsearchcv_cross_val_predict_with_method ()
Definition at line 1891 of file test_validation.py.
test_groups_with_routing_validation()
sklearn.model_selection.tests.test_validation.test_groups_with_routing_validation (func, extra_args)
Check that we raise an error if `groups` are passed to the cv method instead
of `params` when metadata routing is enabled.
Definition at line 2512 of file test_validation.py.
test_learning_curve()
sklearn.model_selection.tests.test_validation.test_learning_curve ()
Definition at line 1171 of file test_validation.py.
test_learning_curve_batch_and_incremental_learning_are_equal()
sklearn.model_selection.tests.test_validation.test_learning_curve_batch_and_incremental_learning_are_equal ()
Definition at line 1343 of file test_validation.py.
test_learning_curve_exploit_incremental_learning_routing()
sklearn.model_selection.tests.test_validation.test_learning_curve_exploit_incremental_learning_routing ()
Test that learning_curve routes metadata to the estimator correctly while
partial_fitting it with `exploit_incremental_learning=True`.
Definition at line 2701 of file test_validation.py.
test_learning_curve_incremental_learning()
sklearn.model_selection.tests.test_validation.test_learning_curve_incremental_learning ()
Definition at line 1293 of file test_validation.py.
test_learning_curve_incremental_learning_not_possible()
sklearn.model_selection.tests.test_validation.test_learning_curve_incremental_learning_not_possible ()
Definition at line 1277 of file test_validation.py.
test_learning_curve_incremental_learning_params()
sklearn.model_selection.tests.test_validation.test_learning_curve_incremental_learning_params ()
Definition at line 1544 of file test_validation.py.
test_learning_curve_incremental_learning_unsupervised()
sklearn.model_selection.tests.test_validation.test_learning_curve_incremental_learning_unsupervised ()
Definition at line 1319 of file test_validation.py.
test_learning_curve_n_sample_range_out_of_bounds()
sklearn.model_selection.tests.test_validation.test_learning_curve_n_sample_range_out_of_bounds ()
Definition at line 1382 of file test_validation.py.
test_learning_curve_params()
sklearn.model_selection.tests.test_validation.test_learning_curve_params ()
Definition at line 1525 of file test_validation.py.
test_learning_curve_partial_fit_regressors()
sklearn.model_selection.tests.test_validation.test_learning_curve_partial_fit_regressors ()
Check that regressors with partial_fit is supported.
Non-regression test for #22981.
Definition at line 2398 of file test_validation.py.
test_learning_curve_remove_duplicate_sample_sizes()
sklearn.model_selection.tests.test_validation.test_learning_curve_remove_duplicate_sample_sizes ()
Definition at line 1405 of file test_validation.py.
test_learning_curve_some_failing_fits_warning()
sklearn.model_selection.tests.test_validation.test_learning_curve_some_failing_fits_warning (global_random_seed)
Checks for fit failures in `learning_curve` and raises the required warning
Definition at line 2409 of file test_validation.py.
test_learning_curve_unsupervised()
sklearn.model_selection.tests.test_validation.test_learning_curve_unsupervised ()
Definition at line 1232 of file test_validation.py.
test_learning_curve_verbose()
sklearn.model_selection.tests.test_validation.test_learning_curve_verbose ()
Definition at line 1251 of file test_validation.py.
test_learning_curve_with_boolean_indices()
sklearn.model_selection.tests.test_validation.test_learning_curve_with_boolean_indices ()
Definition at line 1427 of file test_validation.py.
test_learning_curve_with_shuffle()
sklearn.model_selection.tests.test_validation.test_learning_curve_with_shuffle ()
Definition at line 1447 of file test_validation.py.
test_passed_unrequested_metadata()
sklearn.model_selection.tests.test_validation.test_passed_unrequested_metadata (func, extra_args)
Check that we raise an error when passing metadata that is not
requested.
Definition at line 2559 of file test_validation.py.
test_permutation_score()
sklearn.model_selection.tests.test_validation.test_permutation_score (coo_container)
Definition at line 786 of file test_validation.py.
test_permutation_test_score_allow_nans()
sklearn.model_selection.tests.test_validation.test_permutation_test_score_allow_nans ()
Definition at line 852 of file test_validation.py.
test_permutation_test_score_pandas()
sklearn.model_selection.tests.test_validation.test_permutation_test_score_pandas ()
Definition at line 2060 of file test_validation.py.
test_permutation_test_score_params()
sklearn.model_selection.tests.test_validation.test_permutation_test_score_params ()
Definition at line 866 of file test_validation.py.
test_score()
sklearn.model_selection.tests.test_validation.test_score ()
Definition at line 2365 of file test_validation.py.
test_score_memmap()
sklearn.model_selection.tests.test_validation.test_score_memmap ()
Definition at line 2034 of file test_validation.py.
test_validation_curve()
sklearn.model_selection.tests.test_validation.test_validation_curve ()
Definition at line 1592 of file test_validation.py.
test_validation_curve_clone_estimator()
sklearn.model_selection.tests.test_validation.test_validation_curve_clone_estimator ()
Definition at line 1619 of file test_validation.py.
test_validation_curve_cv_splits_consistency()
sklearn.model_selection.tests.test_validation.test_validation_curve_cv_splits_consistency ()
Definition at line 1641 of file test_validation.py.
test_validation_curve_params()
sklearn.model_selection.tests.test_validation.test_validation_curve_params ()
Definition at line 1687 of file test_validation.py.
test_validation_functions_routing()
sklearn.model_selection.tests.test_validation.test_validation_functions_routing (func, extra_args)
Check that the respective cv method is properly dispatching the metadata
to the consumer.
Definition at line 2608 of file test_validation.py.
three_params_scorer()
sklearn.model_selection.tests.test_validation.three_params_scorer (i, j, k)
Definition at line 2293 of file test_validation.py.
Variable Documentation
P
sklearn.model_selection.tests.test_validation.P = np.eye(5)
Definition at line 282 of file test_validation.py.
X
sklearn.model_selection.tests.test_validation.X = np.ones((15, 2))
Definition at line 277 of file test_validation.py.
y
sklearn.model_selection.tests.test_validation.y = np.array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 6])
Definition at line 278 of file test_validation.py.
y2
sklearn.model_selection.tests.test_validation.y2 = np.array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3])
Definition at line 281 of file test_validation.py.