Code Cloning Analysis: fontTools.ttLib.tables.otTables.ClipList Class Reference
fontTools.ttLib.tables.otTables.ClipList Class Reference
Public Member Functions
populateDefaults (self, propagator=None)
postRead (self, rawTable, font)
groups (self)
preWrite (self, font)
toXML (self, xmlWriter, font, attrs=None, name=None)
fromXML (self, name, attrs, content, font)
Public Attributes
dict clips = {}
Format
Detailed Description
Definition at line 1770 of file otTables.py.
Member Function Documentation
fromXML()
fontTools.ttLib.tables.otTables.ClipList.fromXML (self, name, attrs, content, font)
Definition at line 1893 of file otTables.py.
groups()
fontTools.ttLib.tables.otTables.ClipList.groups (self)
Definition at line 1818 of file otTables.py.
Referenced by pandas.io.pytables.HDFStore.__contains__(), pandas.io.pytables.HDFStore.items(), and pandas.io.pytables.HDFStore.keys().
populateDefaults()
fontTools.ttLib.tables.otTables.ClipList.populateDefaults (self, propagator = None)
Definition at line 1771 of file otTables.py.
postRead()
fontTools.ttLib.tables.otTables.ClipList.postRead (self, rawTable, font)
Definition at line 1775 of file otTables.py.
preWrite()
fontTools.ttLib.tables.otTables.ClipList.preWrite (self, font)
Definition at line 1830 of file otTables.py.
toXML()
fontTools.ttLib.tables.otTables.ClipList.toXML (self, xmlWriter, font, attrs = None, name = None)
Definition at line 1866 of file otTables.py.
Member Data Documentation
clips
dict fontTools.ttLib.tables.otTables.ClipList.clips = {}
Definition at line 1773 of file otTables.py.
Format
fontTools.ttLib.tables.otTables.ClipList.Format
Definition at line 1871 of file otTables.py.
Referenced by fontTools.varLib.merger.COLRVariationMerger.expandPaintColrLayers(), and fontTools.ttLib.tables.otTables.Paint.traverse().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ttLib/tables/otTables.py