Code Cloning Analysis: fontTools.feaLib.lexer.Lexer Class Reference
fontTools.feaLib.lexer.Lexer Class Reference
Public Member Functions
__init__ (self, text, filename)
__iter__ (self)
next (self)
__next__ (self)
location_ (self)
next_ (self)
scan_over_ (self, valid)
scan_until_ (self, stop_at)
scan_anonymous_block (self, tag)
Public Attributes
filename_ = filename
int line_ = 1
int pos_ = 0
int line_start_ = 0
text_ = text
text_length_ = len(text)
str mode_ = Lexer.MODE_NORMAL_
Static Public Attributes
str NUMBER = "NUMBER"
str HEXADECIMAL = "HEXADECIMAL"
str OCTAL = "OCTAL"
tuple NUMBERS = (NUMBER, HEXADECIMAL, OCTAL)
str FLOAT = "FLOAT"
str STRING = "STRING"
str NAME = "NAME"
str FILENAME = "FILENAME"
str GLYPHCLASS = "GLYPHCLASS"
str CID = "CID"
str SYMBOL = "SYMBOL"
str COMMENT = "COMMENT"
str NEWLINE = "NEWLINE"
str ANONYMOUS_BLOCK = "ANONYMOUS_BLOCK"
str CHAR_WHITESPACE_ = " \t"
str CHAR_NEWLINE_ = "\r\n"
str CHAR_SYMBOL_ = ",;:-+'{}[]<>()="
str CHAR_DIGIT_ = "0123456789"
str CHAR_HEXDIGIT_ = "0123456789ABCDEFabcdef"
str CHAR_LETTER_ = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
str CHAR_NAME_START_ = CHAR_LETTER_ + "_+*:.^~!\\"
str CHAR_NAME_CONTINUATION_ = CHAR_LETTER_ + CHAR_DIGIT_ + "_.+*:^~!/-"
RE_GLYPHCLASS = re.compile(r"^[A-Za-z_0-9.\-]+$")
str MODE_NORMAL_ = "NORMAL"
str MODE_FILENAME_ = "FILENAME"
Detailed Description
Definition at line 13 of file lexer.py.
Constructor & Destructor Documentation
__init__()
fontTools.feaLib.lexer.Lexer.__init__ (self, text, filename)
Definition at line 43 of file lexer.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__iter__()
fontTools.feaLib.lexer.Lexer.__iter__ (self)
Definition at line 52 of file lexer.py.
__next__()
fontTools.feaLib.lexer.Lexer.__next__ (self)
Definition at line 58 of file lexer.py.
Referenced by fontTools.feaLib.lexer.IncludingLexer.__init__().
location_()
fontTools.feaLib.lexer.Lexer.location_ (self)
Definition at line 64 of file lexer.py.
next()
fontTools.feaLib.lexer.Lexer.next (self)
Definition at line 55 of file lexer.py.
next_()
fontTools.feaLib.lexer.Lexer.next_ (self)
Definition at line 68 of file lexer.py.
scan_anonymous_block()
fontTools.feaLib.lexer.Lexer.scan_anonymous_block (self, tag)
Definition at line 177 of file lexer.py.
scan_over_()
fontTools.feaLib.lexer.Lexer.scan_over_ (self, valid)
Definition at line 165 of file lexer.py.
scan_until_()
fontTools.feaLib.lexer.Lexer.scan_until_ (self, stop_at)
Definition at line 171 of file lexer.py.
Member Data Documentation
ANONYMOUS_BLOCK
str fontTools.feaLib.lexer.Lexer.ANONYMOUS_BLOCK = "ANONYMOUS_BLOCK" static
Definition at line 27 of file lexer.py.
CHAR_DIGIT_
str fontTools.feaLib.lexer.Lexer.CHAR_DIGIT_ = "0123456789" static
Definition at line 32 of file lexer.py.
CHAR_HEXDIGIT_
str fontTools.feaLib.lexer.Lexer.CHAR_HEXDIGIT_ = "0123456789ABCDEFabcdef" static
Definition at line 33 of file lexer.py.
CHAR_LETTER_
str fontTools.feaLib.lexer.Lexer.CHAR_LETTER_ = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz" static
Definition at line 34 of file lexer.py.
CHAR_NAME_CONTINUATION_
str fontTools.feaLib.lexer.Lexer.CHAR_NAME_CONTINUATION_ = CHAR_LETTER_ + CHAR_DIGIT_ + "_.+*:^~!/-" static
Definition at line 36 of file lexer.py.
CHAR_NAME_START_
str fontTools.feaLib.lexer.Lexer.CHAR_NAME_START_ = CHAR_LETTER_ + "_+*:.^~!\\" static
Definition at line 35 of file lexer.py.
CHAR_NEWLINE_
str fontTools.feaLib.lexer.Lexer.CHAR_NEWLINE_ = "\r\n" static
Definition at line 30 of file lexer.py.
CHAR_SYMBOL_
str fontTools.feaLib.lexer.Lexer.CHAR_SYMBOL_ = ",;:-+'{}[]<>()=" static
Definition at line 31 of file lexer.py.
CHAR_WHITESPACE_
str fontTools.feaLib.lexer.Lexer.CHAR_WHITESPACE_ = " \t" static
Definition at line 29 of file lexer.py.
CID
str fontTools.feaLib.lexer.Lexer.CID = "CID" static
Definition at line 23 of file lexer.py.
COMMENT
str fontTools.feaLib.lexer.Lexer.COMMENT = "COMMENT" static
Definition at line 25 of file lexer.py.
FILENAME
str fontTools.feaLib.lexer.Lexer.FILENAME = "FILENAME" static
Definition at line 21 of file lexer.py.
filename_
fontTools.feaLib.lexer.Lexer.filename_ = filename
Definition at line 44 of file lexer.py.
FLOAT
str fontTools.feaLib.lexer.Lexer.FLOAT = "FLOAT" static
Definition at line 18 of file lexer.py.
GLYPHCLASS
str fontTools.feaLib.lexer.Lexer.GLYPHCLASS = "GLYPHCLASS" static
Definition at line 22 of file lexer.py.
HEXADECIMAL
str fontTools.feaLib.lexer.Lexer.HEXADECIMAL = "HEXADECIMAL" static
Definition at line 15 of file lexer.py.
line_
fontTools.feaLib.lexer.Lexer.line_ = 1
Definition at line 45 of file lexer.py.
Referenced by sklearn.calibration.CalibrationDisplay.plot(), sklearn.metrics._plot.det_curve.DetCurveDisplay.plot(), sklearn.metrics._plot.precision_recall_curve.PrecisionRecallDisplay.plot(), sklearn.metrics._plot.regression.PredictionErrorDisplay.plot(), and sklearn.metrics._plot.roc_curve.RocCurveDisplay.plot().
line_start_
int fontTools.feaLib.lexer.Lexer.line_start_ = 0
Definition at line 47 of file lexer.py.
mode_
str fontTools.feaLib.lexer.Lexer.mode_ = Lexer.MODE_NORMAL_
Definition at line 50 of file lexer.py.
MODE_FILENAME_
str fontTools.feaLib.lexer.Lexer.MODE_FILENAME_ = "FILENAME" static
Definition at line 41 of file lexer.py.
MODE_NORMAL_
str fontTools.feaLib.lexer.Lexer.MODE_NORMAL_ = "NORMAL" static
Definition at line 40 of file lexer.py.
NAME
str fontTools.feaLib.lexer.Lexer.NAME = "NAME" static
Definition at line 20 of file lexer.py.
NEWLINE
str fontTools.feaLib.lexer.Lexer.NEWLINE = "NEWLINE" static
Definition at line 26 of file lexer.py.
NUMBER
str fontTools.feaLib.lexer.Lexer.NUMBER = "NUMBER" static
Definition at line 14 of file lexer.py.
NUMBERS
tuple fontTools.feaLib.lexer.Lexer.NUMBERS = (NUMBER, HEXADECIMAL, OCTAL) static
Definition at line 17 of file lexer.py.
OCTAL
str fontTools.feaLib.lexer.Lexer.OCTAL = "OCTAL" static
Definition at line 16 of file lexer.py.
pos_
int fontTools.feaLib.lexer.Lexer.pos_ = 0
Definition at line 46 of file lexer.py.
RE_GLYPHCLASS
fontTools.feaLib.lexer.Lexer.RE_GLYPHCLASS = re.compile(r"^[A-Za-z_0-9.\-]+$") static
Definition at line 38 of file lexer.py.
STRING
str fontTools.feaLib.lexer.Lexer.STRING = "STRING" static
Definition at line 19 of file lexer.py.
SYMBOL
str fontTools.feaLib.lexer.Lexer.SYMBOL = "SYMBOL" static
Definition at line 24 of file lexer.py.
text_
fontTools.feaLib.lexer.Lexer.text_ = text
Definition at line 48 of file lexer.py.
Referenced by sklearn.metrics._plot.confusion_matrix.ConfusionMatrixDisplay.plot().
text_length_
fontTools.feaLib.lexer.Lexer.text_length_ = len(text)
Definition at line 49 of file lexer.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/feaLib/lexer.py