Code Cloning Analysis: pandas.core.arrays.sparse.accessor.SparseFrameAccessor Class Reference
pandas.core.arrays.sparse.accessor.SparseFrameAccessor Class Reference
Public Member Functions
DataFrame from_spmatrix (cls, data, index=None, columns=None)
DataFrame to_dense (self)
to_coo (self)
float density (self)
Public Member Functions inherited from pandas.core.arrays.sparse.accessor.BaseAccessor
None __init__ (self, data=None)
Protected Member Functions
_validate (self, data)
Protected Member Functions inherited from pandas.core.accessor.PandasDelegate
_delegate_property_get (self, str name, *args, **kwargs)
_delegate_property_set (self, str name, value, *args, **kwargs)
_delegate_method (self, str name, *args, **kwargs)
None _add_delegate_accessors (cls, delegate, list[str] accessors, str typ, bool overwrite=False, Callable[[str], str] accessor_mapping=lambda x:x, bool raise_on_missing=True)
Static Protected Member Functions
_prep_index (data, index, columns)
Additional Inherited Members
Static Public Attributes inherited from pandas.core.arrays.sparse.accessor.BaseAccessor
typ
Protected Attributes inherited from pandas.core.arrays.sparse.accessor.BaseAccessor
_parent = data
Static Protected Attributes inherited from pandas.core.arrays.sparse.accessor.BaseAccessor
str _validation_msg = "Can only use the '.sparse' accessor with Sparse data."
Detailed Description
DataFrame accessor for sparse data.
Examples
--------
>>> df = pd.DataFrame({"a": [1, 2, 0, 0],
...                   "b": [3, 0, 0, 4]}, dtype="Sparse[int]")
>>> df.sparse.density
0.5
Definition at line 234 of file accessor.py.
Member Function Documentation
_prep_index()
pandas.core.arrays.sparse.accessor.SparseFrameAccessor._prep_index (data, index, columns) static protected
Definition at line 394 of file accessor.py.
_validate()
pandas.core.arrays.sparse.accessor.SparseFrameAccessor._validate (self, data) protected
Reimplemented from pandas.core.arrays.sparse.accessor.BaseAccessor.
Definition at line 246 of file accessor.py.
density()
float pandas.core.arrays.sparse.accessor.SparseFrameAccessor.density (self)
Ratio of non-sparse points to total (dense) data points.
Examples
--------
>>> df = pd.DataFrame({"A": pd.arrays.SparseArray([0, 1, 0, 1])})
>>> df.sparse.density
0.5
Definition at line 380 of file accessor.py.
from_spmatrix()
DataFrame pandas.core.arrays.sparse.accessor.SparseFrameAccessor.from_spmatrix (cls, data, index = None, columns = None)
Create a new DataFrame from a scipy sparse matrix.
Parameters
----------
data : scipy.sparse.spmatrix
    Must be convertible to csc format.
index, columns : Index, optional
    Row and column labels to use for the resulting DataFrame.
    Defaults to a RangeIndex.
Returns
-------
DataFrame
    Each column of the DataFrame is stored as a
    :class:`arrays.SparseArray`.
Examples
--------
>>> import scipy.sparse
>>> mat = scipy.sparse.eye(3, dtype=float)
>>> pd.DataFrame.sparse.from_spmatrix(mat)
     0    1    2
0  1.0    0    0
1    0  1.0    0
2    0    0  1.0
Definition at line 252 of file accessor.py.
to_coo()
pandas.core.arrays.sparse.accessor.SparseFrameAccessor.to_coo (self)
Return the contents of the frame as a sparse SciPy COO matrix.
Returns
-------
scipy.sparse.spmatrix
    If the caller is heterogeneous and contains booleans or objects,
    the result will be of dtype=object. See Notes.
Notes
-----
The dtype will be the lowest-common-denominator type (implicit
upcasting); that is to say if the dtypes (even of numeric types)
are mixed, the one that accommodates all will be chosen.
e.g. If the dtypes are float16 and float32, dtype will be upcast to
float32. By numpy.find_common_type convention, mixing int64 and
and uint64 will result in a float64 dtype.
Examples
--------
>>> df = pd.DataFrame({"A": pd.arrays.SparseArray([0, 1, 0, 1])})
>>> df.sparse.to_coo()
<COOrdinate sparse matrix of dtype 'int64'
    with 2 stored elements and shape (4, 1)>
Definition at line 329 of file accessor.py.
to_dense()
DataFrame pandas.core.arrays.sparse.accessor.SparseFrameAccessor.to_dense (self)
Convert a DataFrame with sparse values to dense.
Returns
-------
DataFrame
    A DataFrame with the same values stored as dense arrays.
Examples
--------
>>> df = pd.DataFrame({"A": pd.arrays.SparseArray([0, 1, 0])})
>>> df.sparse.to_dense()
   A
0  0
1  1
2  0
Definition at line 306 of file accessor.py.
Referenced by pandas.core.arrays.sparse.array.SparseArray.argmin(), pandas.core.arrays.sparse.array.SparseArray.cumsum(), and pandas.core.arrays.sparse.array.SparseArray.value_counts().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/core/arrays/sparse/accessor.py