Code Cloning Analysis: scipy.sparse._spfuncs Namespace Reference
scipy.sparse._spfuncs Namespace Reference
Functions
estimate_blocksize (A, efficiency=0.7)
count_blocks (A, blocksize)
Variables
list __all__ = ['count_blocks','estimate_blocksize']
Detailed Description
 Functions that operate on sparse matrices
Function Documentation
count_blocks()
scipy.sparse._spfuncs.count_blocks (A, blocksize)
For a given blocksize=(r,c) count the number of occupied
blocks in a sparse matrix A
Definition at line 62 of file _spfuncs.py.
References count_blocks(), and scipy.sparse._base.issparse().
Referenced by count_blocks(), and estimate_blocksize().
estimate_blocksize()
scipy.sparse._spfuncs.estimate_blocksize (A, efficiency = 0.7)
Attempt to determine the blocksize of a sparse matrix
Returns a blocksize=(r,c) such that
    - A.nnz / A.tobsr( (r,c) ).nnz > efficiency
Definition at line 11 of file _spfuncs.py.
References count_blocks(), and scipy.sparse._base.issparse().
Variable Documentation
__all__
list scipy.sparse._spfuncs.__all__ = ['count_blocks','estimate_blocksize'] private
Definition at line 4 of file _spfuncs.py.