Code Cloning Analysis: scipy.signal.tests.test_cont2discrete.TestC2D Class Reference
scipy.signal.tests.test_cont2discrete.TestC2D Class Reference
Public Member Functions
test_zoh (self)
test_foh (self)
test_impulse (self)
test_gbt (self)
test_euler (self)
test_backward_diff (self)
test_bilinear (self)
test_transferfunction (self)
test_zerospolesgain (self)
test_gbt_with_sio_tf_and_zpk (self)
test_discrete_approx (self)
test_simo_tf (self)
test_multioutput (self)
Detailed Description
Definition at line 15 of file test_cont2discrete.py.
Member Function Documentation
test_backward_diff()
scipy.signal.tests.test_cont2discrete.TestC2D.test_backward_diff (self)
Definition at line 130 of file test_cont2discrete.py.
test_bilinear()
scipy.signal.tests.test_cont2discrete.TestC2D.test_bilinear (self)
Definition at line 155 of file test_cont2discrete.py.
test_discrete_approx()
scipy.signal.tests.test_cont2discrete.TestC2D.test_discrete_approx (self)
Test that the solution to the discrete approximation of a continuous
system actually approximates the solution to the continuous system.
This is an indirect test of the correctness of the implementation
of cont2discrete.
Definition at line 276 of file test_cont2discrete.py.
References scipy.signal._ltisys.dlsim(), and scipy.signal._ltisys.lsim().
test_euler()
scipy.signal.tests.test_cont2discrete.TestC2D.test_euler (self)
Definition at line 106 of file test_cont2discrete.py.
test_foh()
scipy.signal.tests.test_cont2discrete.TestC2D.test_foh (self)
Definition at line 35 of file test_cont2discrete.py.
test_gbt()
scipy.signal.tests.test_cont2discrete.TestC2D.test_gbt (self)
Definition at line 80 of file test_cont2discrete.py.
test_gbt_with_sio_tf_and_zpk()
scipy.signal.tests.test_cont2discrete.TestC2D.test_gbt_with_sio_tf_and_zpk (self)
Test method='gbt' with alpha=0.25 for tf and zpk cases.
Definition at line 234 of file test_cont2discrete.py.
References scipy.signal._lti_conversion.ss2tf(), and scipy.signal._lti_conversion.ss2zpk().
test_impulse()
scipy.signal.tests.test_cont2discrete.TestC2D.test_impulse (self)
Definition at line 58 of file test_cont2discrete.py.
test_multioutput()
scipy.signal.tests.test_cont2discrete.TestC2D.test_multioutput (self)
Definition at line 325 of file test_cont2discrete.py.
test_simo_tf()
scipy.signal.tests.test_cont2discrete.TestC2D.test_simo_tf (self)
Definition at line 316 of file test_cont2discrete.py.
test_transferfunction()
scipy.signal.tests.test_cont2discrete.TestC2D.test_transferfunction (self)
Definition at line 199 of file test_cont2discrete.py.
test_zerospolesgain()
scipy.signal.tests.test_cont2discrete.TestC2D.test_zerospolesgain (self)
Definition at line 214 of file test_cont2discrete.py.
test_zoh()
scipy.signal.tests.test_cont2discrete.TestC2D.test_zoh (self)
Definition at line 16 of file test_cont2discrete.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/signal/tests/test_cont2discrete.py