Code Cloning Analysis: matplotlib._afm.AFM Class Reference
matplotlib._afm.AFM Class Reference
Public Member Functions
__init__ (self, fh)
get_bbox_char (self, c, isord=False)
string_width_height (self, s)
get_str_bbox_and_descent (self, s)
get_str_bbox (self, s)
get_name_char (self, c, isord=False)
get_width_char (self, c, isord=False)
get_width_from_char_name (self, name)
get_height_char (self, c, isord=False)
get_kern_dist (self, c1, c2)
get_kern_dist_from_name (self, name1, name2)
get_fontname (self)
postscript_name (self)
get_fullname (self)
get_familyname (self)
family_name (self)
get_weight (self)
get_angle (self)
get_capheight (self)
get_xheight (self)
get_underline_thickness (self)
get_horizontal_stem_width (self)
get_vertical_stem_width (self)
Protected Attributes
_header = _parse_header(fh)
_metrics
_metrics_by_name = _parse_char_metrics(fh)
_kern
_composite = _parse_optional(fh)
Detailed Description
Definition at line 358 of file _afm.py.
Constructor & Destructor Documentation
__init__()
matplotlib._afm.AFM.__init__ (self, fh)
Parse the AFM file in file object *fh*.
Definition at line 360 of file _afm.py.
References _composite, _header, _kern, _metrics, _metrics_by_name, matplotlib._afm._parse_char_metrics(), matplotlib._afm._parse_header(), and matplotlib._afm._parse_optional().
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
family_name()
matplotlib._afm.AFM.family_name (self)
The font family name, e.g., 'Times'.
Definition at line 496 of file _afm.py.
References get_familyname().
get_angle()
matplotlib._afm.AFM.get_angle (self)
Return the fontangle as float.
Definition at line 504 of file _afm.py.
References _header.
get_bbox_char()
matplotlib._afm.AFM.get_bbox_char (self, c, isord = False)
Definition at line 366 of file _afm.py.
get_capheight()
matplotlib._afm.AFM.get_capheight (self)
Return the cap height as float.
Definition at line 508 of file _afm.py.
References _header.
get_familyname()
matplotlib._afm.AFM.get_familyname (self)
Return the font family name, e.g., 'Times'.
Definition at line 483 of file _afm.py.
References _header, and get_fullname().
Referenced by family_name().
get_fontname()
matplotlib._afm.AFM.get_fontname (self)
Return the font name, e.g., 'Times-Roman'.
Definition at line 468 of file _afm.py.
References _header, and get_fontname().
Referenced by get_fontname().
get_fullname()
matplotlib._afm.AFM.get_fullname (self)
Return the font full name, e.g., 'Times-Roman'.
Definition at line 476 of file _afm.py.
References _header.
Referenced by get_familyname().
get_height_char()
matplotlib._afm.AFM.get_height_char (self, c, isord = False)
Get the bounding box (ink) height of character *c* (space is 0).
Definition at line 448 of file _afm.py.
References _metrics.
get_horizontal_stem_width()
matplotlib._afm.AFM.get_horizontal_stem_width (self)
Return the standard horizontal stem width as float, or *None* if
not specified in AFM file.
Definition at line 520 of file _afm.py.
References _header.
get_kern_dist()
matplotlib._afm.AFM.get_kern_dist (self, c1, c2)
Return the kerning pair distance (possibly 0) for chars *c1* and *c2*.
Definition at line 454 of file _afm.py.
References get_kern_dist_from_name(), and get_name_char().
get_kern_dist_from_name()
matplotlib._afm.AFM.get_kern_dist_from_name (self, name1, name2)
Return the kerning pair distance (possibly 0) for chars
*name1* and *name2*.
Definition at line 461 of file _afm.py.
References _kern.
Referenced by get_kern_dist().
get_name_char()
matplotlib._afm.AFM.get_name_char (self, c, isord = False)
Get the name of the character, i.e., ';' is 'semicolon'.
Definition at line 430 of file _afm.py.
References _metrics.
Referenced by get_kern_dist().
get_str_bbox()
matplotlib._afm.AFM.get_str_bbox (self, s)
Return the string bounding box.
Definition at line 426 of file _afm.py.
References get_str_bbox_and_descent().
get_str_bbox_and_descent()
matplotlib._afm.AFM.get_str_bbox_and_descent (self, s)
Return the string bounding box and the maximal descent.
Definition at line 396 of file _afm.py.
References _kern, and _metrics_by_name.
Referenced by get_str_bbox().
get_underline_thickness()
matplotlib._afm.AFM.get_underline_thickness (self)
Return the underline thickness as float.
Definition at line 516 of file _afm.py.
References _header.
get_vertical_stem_width()
matplotlib._afm.AFM.get_vertical_stem_width (self)
Return the standard vertical stem width as float, or *None* if
not specified in AFM file.
Definition at line 527 of file _afm.py.
References _header.
get_weight()
matplotlib._afm.AFM.get_weight (self)
Return the font weight, e.g., 'Bold' or 'Roman'.
Definition at line 500 of file _afm.py.
References _header.
get_width_char()
matplotlib._afm.AFM.get_width_char (self, c, isord = False)
Get the width of the character from the character metric WX field.
Definition at line 436 of file _afm.py.
References _metrics.
get_width_from_char_name()
matplotlib._afm.AFM.get_width_from_char_name (self, name)
Get the width of the character from a type1 character name.
Definition at line 444 of file _afm.py.
References _metrics_by_name.
get_xheight()
matplotlib._afm.AFM.get_xheight (self)
Return the xheight as float.
Definition at line 512 of file _afm.py.
References _header.
postscript_name()
matplotlib._afm.AFM.postscript_name (self)
Definition at line 473 of file _afm.py.
string_width_height()
matplotlib._afm.AFM.string_width_height (self, s)
Return the string width (including kerning) and string height
as a (*w*, *h*) tuple.
Definition at line 371 of file _afm.py.
References _kern, and _metrics.
Member Data Documentation
_composite
matplotlib._afm.AFM._composite = _parse_optional(fh) protected
Definition at line 364 of file _afm.py.
Referenced by __init__().
_header
matplotlib._afm.AFM._header = _parse_header(fh) protected
Definition at line 362 of file _afm.py.
Referenced by __init__(), get_angle(), get_capheight(), get_familyname(), get_fontname(), get_fullname(), get_horizontal_stem_width(), get_underline_thickness(), get_vertical_stem_width(), get_weight(), and get_xheight().
_kern
matplotlib._afm.AFM._kern protected
Definition at line 364 of file _afm.py.
Referenced by __init__(), get_kern_dist_from_name(), get_str_bbox_and_descent(), and string_width_height().
_metrics
matplotlib._afm.AFM._metrics protected
Definition at line 363 of file _afm.py.
Referenced by __init__(), get_height_char(), matplotlib._mathtext.Char.get_kerning(), get_name_char(), get_width_char(), matplotlib._mathtext.Accent.render(), and string_width_height().
_metrics_by_name
matplotlib._afm.AFM._metrics_by_name = _parse_char_metrics(fh) protected
Definition at line 363 of file _afm.py.
Referenced by __init__(), get_str_bbox_and_descent(), and get_width_from_char_name().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/_afm.py