Code Cloning Analysis: fontTools.feaLib.ast.ValueRecord Class Reference
fontTools.feaLib.ast.ValueRecord Class Reference
Public Member Functions
__init__ (self, xPlacement=None, yPlacement=None, xAdvance=None, yAdvance=None, xPlaDevice=None, yPlaDevice=None, xAdvDevice=None, yAdvDevice=None, vertical=False, location=None)
__eq__ (self, other)
__ne__ (self, other)
__hash__ (self)
asFea (self, indent="")
__bool__ (self)
Public Member Functions inherited from fontTools.feaLib.ast.Element
__init__ (self, location=None)
build (self, builder)
__str__ (self)
Public Attributes
xPlacement
tuple yPlacement = (xPlacement, yPlacement)
xAdvance
tuple yAdvance = (xAdvance, yAdvance)
xPlaDevice
tuple yPlaDevice = (xPlaDevice, yPlaDevice)
xAdvDevice
tuple yAdvDevice = (xAdvDevice, yAdvDevice)
vertical = vertical
Public Attributes inherited from fontTools.feaLib.ast.Element
location = location
Static Private Attributes
__nonzero__ = __bool__
Detailed Description
Represents a value record.
Definition at line 1547 of file ast.py.
Constructor & Destructor Documentation
__init__()
fontTools.feaLib.ast.ValueRecord.__init__ (self, xPlacement = None, yPlacement = None, xAdvance = None, yAdvance = None, xPlaDevice = None, yPlaDevice = None, xAdvDevice = None, yAdvDevice = None, vertical = False, location = None)
Definition at line 1550 of file ast.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__bool__()
fontTools.feaLib.ast.ValueRecord.__bool__ (self)
Definition at line 1639 of file ast.py.
__eq__()
fontTools.feaLib.ast.ValueRecord.__eq__ (self, other)
Definition at line 1570 of file ast.py.
Referenced by fontTools.ttLib.tables.ttProgram.Program.__bool__(), pandas.core.dtypes.base.ExtensionDtype.__eq__(), pandas.io.pytables.IndexCol.__eq__(), fontTools.ttLib.tables._g_l_y_f.GlyphCoordinates.__ne__(), pip._vendor.msgpack.ext.Timestamp.__ne__(), numpy.polynomial._polybase.ABCPolyBase._str_term_ascii(), fontTools.ttLib.tables._g_l_y_f.Glyph.drawPoints(), fontTools.ttLib.tables.otBase.OTTableWriter.getDataForHarfbuzz(), pip._vendor.distlib.version.Matcher.match(), pandas.core.dtypes.dtypes.PeriodDtype.na_value(), and numpy.lib.polynomial.poly1d.roots().
__hash__()
fontTools.feaLib.ast.ValueRecord.__hash__ (self)
Definition at line 1583 of file ast.py.
Referenced by pip._vendor.rich.style.Style.pick_first().
__ne__()
fontTools.feaLib.ast.ValueRecord.__ne__ (self, other)
Definition at line 1580 of file ast.py.
asFea()
fontTools.feaLib.ast.ValueRecord.asFea (self, indent = "")
Returns this element as a string of feature code. For block-type
elements (such as :class:`FeatureBlock`), the `indent` string is
added to the start of each line in the output.
Reimplemented from fontTools.feaLib.ast.Element.
Definition at line 1595 of file ast.py.
References vertical, xAdvance, xAdvDevice, xPlacement, xPlaDevice, yAdvance, yAdvDevice, yPlacement, and yPlaDevice.
Member Data Documentation
__nonzero__
fontTools.feaLib.ast.ValueRecord.__nonzero__ = __bool__ static private
Definition at line 1654 of file ast.py.
Referenced by pandas.core.generic.NDFrame.bool().
vertical
fontTools.feaLib.ast.ValueRecord.vertical = vertical
Definition at line 1568 of file ast.py.
Referenced by fontTools.feaLib.ast.BaseAxis.asFea(), asFea(), fontTools.feaLib.ast.BaseAxis.build(), and pip._vendor.rich.align.Align.right().
xAdvance
fontTools.feaLib.ast.ValueRecord.xAdvance
Definition at line 1565 of file ast.py.
Referenced by asFea().
xAdvDevice
fontTools.feaLib.ast.ValueRecord.xAdvDevice
Definition at line 1567 of file ast.py.
Referenced by asFea().
xPlacement
fontTools.feaLib.ast.ValueRecord.xPlacement
Definition at line 1564 of file ast.py.
Referenced by asFea().
xPlaDevice
fontTools.feaLib.ast.ValueRecord.xPlaDevice
Definition at line 1566 of file ast.py.
Referenced by asFea().
yAdvance
fontTools.feaLib.ast.ValueRecord.yAdvance = (xAdvance, yAdvance)
Definition at line 1565 of file ast.py.
Referenced by asFea().
yAdvDevice
fontTools.feaLib.ast.ValueRecord.yAdvDevice = (xAdvDevice, yAdvDevice)
Definition at line 1567 of file ast.py.
Referenced by asFea().
yPlacement
fontTools.feaLib.ast.ValueRecord.yPlacement = (xPlacement, yPlacement)
Definition at line 1564 of file ast.py.
Referenced by asFea().
yPlaDevice
fontTools.feaLib.ast.ValueRecord.yPlaDevice = (xPlaDevice, yPlaDevice)
Definition at line 1566 of file ast.py.
Referenced by asFea().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/feaLib/ast.py