Code Cloning Analysis: numpy.core.arrayprint.ComplexFloatingFormat Class Reference
numpy.core.arrayprint.ComplexFloatingFormat Class Reference
Public Member Functions
__init__ (self, x, precision, floatmode, suppress_small, sign=False, *, legacy=None)
__call__ (self, x)
Public Attributes
real_format
imag_format
Detailed Description
 Formatter for subtypes of np.complexfloating
Definition at line 1245 of file arrayprint.py.
Constructor & Destructor Documentation
__init__()
numpy.core.arrayprint.ComplexFloatingFormat.__init__ (self, x, precision, floatmode, suppress_small, sign = False, * , legacy = None)
Definition at line 1247 of file arrayprint.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__call__()
numpy.core.arrayprint.ComplexFloatingFormat.__call__ (self, x)
Definition at line 1267 of file arrayprint.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), and scipy.interpolate._fitpack2.SphereBivariateSpline.ev().
Member Data Documentation
imag_format
numpy.core.arrayprint.ComplexFloatingFormat.imag_format
Initial value:
=  FloatingFormat(
            x.imag, precision, floatmode_imag, suppress_small,
            sign='+', legacy=legacy
        )
Definition at line 1262 of file arrayprint.py.
real_format
numpy.core.arrayprint.ComplexFloatingFormat.real_format
Initial value:
=  FloatingFormat(
            x.real, precision, floatmode_real, suppress_small,
            sign=sign, legacy=legacy
        )
Definition at line 1258 of file arrayprint.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/core/arrayprint.py