Code Cloning Analysis: scipy.linalg.tests.test_decomp.TestEigTridiagonal Class Reference
scipy.linalg.tests.test_decomp.TestEigTridiagonal Class Reference
Public Member Functions
setup_method (self)
create_trimat (self)
test_degenerate (self)
test_eigvalsh_tridiagonal (self)
test_eigh_tridiagonal (self)
Public Attributes
d = full(N, 1.0)
e = full(N-1, -1.0)
tuple full_mat = (diag(self.d) + diag(self.e, -1) + diag(self.e, 1))
w = ew[args]
evec = ev[:, args]
Detailed Description
Definition at line 637 of file test_decomp.py.
Member Function Documentation
create_trimat()
scipy.linalg.tests.test_decomp.TestEigTridiagonal.create_trimat (self)
Create the full matrix `self.fullmat`, `self.d`, and `self.e`.
Definition at line 641 of file test_decomp.py.
setup_method()
scipy.linalg.tests.test_decomp.TestEigTridiagonal.setup_method (self)
Definition at line 638 of file test_decomp.py.
test_degenerate()
scipy.linalg.tests.test_decomp.TestEigTridiagonal.test_degenerate (self)
Test error conditions.
Definition at line 656 of file test_decomp.py.
test_eigh_tridiagonal()
scipy.linalg.tests.test_decomp.TestEigTridiagonal.test_eigh_tridiagonal (self)
Compare eigenvalues and eigenvectors of eigh_tridiagonal
   with those of eig.
Definition at line 705 of file test_decomp.py.
test_eigvalsh_tridiagonal()
scipy.linalg.tests.test_decomp.TestEigTridiagonal.test_eigvalsh_tridiagonal (self)
Compare eigenvalues of eigvalsh_tridiagonal with those of eig.
Definition at line 671 of file test_decomp.py.
Member Data Documentation
d
scipy.linalg.tests.test_decomp.TestEigTridiagonal.d = full(N, 1.0)
Definition at line 646 of file test_decomp.py.
Referenced by scipy.stats._qmc.PoissonDisk._hypersphere_surface_sample(), scipy.stats._qmc.PoissonDisk._hypersphere_volume_sample(), scipy.stats._qmc.PoissonDisk._initialize_grid_pool(), scipy.stats._qmc.Halton._random(), scipy.stats._qmc.PoissonDisk._random(), scipy.stats._qmc.Sobol._random(), scipy.stats._qmc.LatinHypercube._random_lhs(), scipy.stats._qmc.LatinHypercube._random_oa_lhs(), scipy.stats._qmc.Sobol._scramble(), scipy.sparse.linalg._expm_multiply.LazyOperatorNormInfo.alpha(), scipy.stats._kde.gaussian_kde.evaluate(), scipy.stats._qmc.Sobol.fast_forward(), scipy.stats._kde.gaussian_kde.integrate_box(), scipy.stats._kde.gaussian_kde.integrate_box_1d(), scipy.stats._kde.gaussian_kde.integrate_gaussian(), scipy.stats._kde.gaussian_kde.integrate_kde(), scipy.optimize._zeros_py.TOMS748Solver.iterate(), scipy.stats._kde.gaussian_kde.logpdf(), scipy.stats._kde.gaussian_kde.resample(), scipy.stats._kde.gaussian_kde.scotts_factor(), scipy.stats._kde.gaussian_kde.silverman_factor(), and scipy.optimize._zeros_py.TOMS748Solver.solve().
e
scipy.linalg.tests.test_decomp.TestEigTridiagonal.e = full(N-1, -1.0)
Definition at line 647 of file test_decomp.py.
Referenced by scipy.optimize._zeros_py.TOMS748Solver.iterate(), and scipy.optimize._zeros_py.TOMS748Solver.solve().
evec
scipy.linalg.tests.test_decomp.TestEigTridiagonal.evec = ev[:, args]
Definition at line 654 of file test_decomp.py.
full_mat
tuple scipy.linalg.tests.test_decomp.TestEigTridiagonal.full_mat = (diag(self.d) + diag(self.e, -1) + diag(self.e, 1))
Definition at line 648 of file test_decomp.py.
w
scipy.linalg.tests.test_decomp.TestEigTridiagonal.w = ew[args]
Definition at line 653 of file test_decomp.py.
Referenced by scipy.signal._czt.CZT.points().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/linalg/tests/test_decomp.py