Code Cloning Analysis: numpy.f2py.cfuncs Namespace Reference
numpy.f2py.cfuncs Namespace Reference
Functions
buildcfuncs ()
append_needs (need, flag=1)
Auxiliary functions for sorting needs ###################.
get_needs ()
Variables
f2py_version = __version__.version
errmess = sys.stderr.write
dict outneeds
Definitions ##################.
dict needs = {}
dict includes0 = {'includes0': '/*need_includes0*/'}
dict includes = {'includes': '/*need_includes*/'}
dict userincludes = {'userincludes': '/*need_userincludes*/'}
dict typedefs = {'typedefs': '/*need_typedefs*/'}
dict typedefs_generated = {'typedefs_generated': '/*need_typedefs_generated*/'}
dict cppmacros = {'cppmacros': '/*need_cppmacros*/'}
dict cfuncs = {'cfuncs': '/*need_cfuncs*/'}
dict callbacks = {'callbacks': '/*need_callbacks*/'}
dict f90modhooks
dict commonhooks
Detailed Description
C declarations, CPP macros, and C functions for f2py2e.
Only required declarations/macros/functions will be used.
Copyright 1999 -- 2011 Pearu Peterson all rights reserved.
Copyright 2011 -- present NumPy Developers.
Permission to use, modify, and distribute this software is given under the
terms of the NumPy License.
NO WARRANTY IS EXPRESSED OR IMPLIED.  USE AT YOUR OWN RISK.
Function Documentation
append_needs()
numpy.f2py.cfuncs.append_needs (need, flag = 1)
Auxiliary functions for sorting needs ###################.
Definition at line 1437 of file cfuncs.py.
References numpy.lib.function_base.append(), and append_needs().
Referenced by append_needs().
buildcfuncs()
numpy.f2py.cfuncs.buildcfuncs ()
Definition at line 1422 of file cfuncs.py.
get_needs()
numpy.f2py.cfuncs.get_needs ()
Definition at line 1504 of file cfuncs.py.
Variable Documentation
callbacks
dict numpy.f2py.cfuncs.callbacks = {'callbacks': '/*need_callbacks*/'}
Definition at line 35 of file cfuncs.py.
cfuncs
dict numpy.f2py.cfuncs.cfuncs = {'cfuncs': '/*need_cfuncs*/'}
Definition at line 34 of file cfuncs.py.
commonhooks
dict numpy.f2py.cfuncs.commonhooks
Initial value:
=  {'commonhooks': '/*need_commonhooks*/',
               'initcommonhooks': '/*need_initcommonhooks*/',
               }
Definition at line 40 of file cfuncs.py.
cppmacros
dict numpy.f2py.cfuncs.cppmacros = {'cppmacros': '/*need_cppmacros*/'}
Definition at line 33 of file cfuncs.py.
errmess
numpy.f2py.cfuncs.errmess = sys.stderr.write
Definition at line 19 of file cfuncs.py.
f2py_version
numpy.f2py.cfuncs.f2py_version = __version__.version
Definition at line 18 of file cfuncs.py.
f90modhooks
dict numpy.f2py.cfuncs.f90modhooks
Initial value:
=  {'f90modhooks': '/*need_f90modhooks*/',
               'initf90modhooksstatic': '/*initf90modhooksstatic*/',
               'initf90modhooksdynamic': '/*initf90modhooksdynamic*/',
               }
Definition at line 36 of file cfuncs.py.
includes
dict numpy.f2py.cfuncs.includes = {'includes': '/*need_includes*/'}
Definition at line 29 of file cfuncs.py.
includes0
dict numpy.f2py.cfuncs.includes0 = {'includes0': '/*need_includes0*/'}
Definition at line 28 of file cfuncs.py.
needs
dict numpy.f2py.cfuncs.needs = {}
Definition at line 27 of file cfuncs.py.
outneeds
dict numpy.f2py.cfuncs.outneeds
Initial value:
=  {'includes0': [], 'includes': [], 'typedefs': [], 'typedefs_generated': [],
            'userincludes': [],
            'cppmacros': [], 'cfuncs': [], 'callbacks': [], 'f90modhooks': [],
            'commonhooks': []}
Definitions ##################.
Definition at line 23 of file cfuncs.py.
typedefs
dict numpy.f2py.cfuncs.typedefs = {'typedefs': '/*need_typedefs*/'}
Definition at line 31 of file cfuncs.py.
typedefs_generated
dict numpy.f2py.cfuncs.typedefs_generated = {'typedefs_generated': '/*need_typedefs_generated*/'}
Definition at line 32 of file cfuncs.py.
userincludes
dict numpy.f2py.cfuncs.userincludes = {'userincludes': '/*need_userincludes*/'}
Definition at line 30 of file cfuncs.py.