Code Cloning Analysis: sklearn.tests.test_random_projection Namespace Reference
sklearn.tests.test_random_projection Namespace Reference
Functions
make_sparse_random_data (coo_container, n_samples, n_features, n_nonzeros, random_state=None, sparse_format="csr")
densify (matrix)
test_invalid_jl_domain (n_samples, eps)
test on JL lemma
test_input_size_jl_min_dim ()
check_input_size_random_matrix (random_matrix)
tests random matrix generation
check_size_generated (random_matrix)
check_zero_mean_and_unit_norm (random_matrix)
check_input_with_sparse_random_matrix (random_matrix)
test_basic_property_of_random_matrix (random_matrix)
test_basic_property_of_sparse_random_matrix (random_matrix)
test_gaussian_random_matrix ()
test_sparse_random_matrix ()
test_random_projection_transformer_invalid_input ()
tests on random projection transformer
test_try_to_transform_before_fit (coo_container, global_random_seed)
test_too_many_samples_to_find_a_safe_embedding (coo_container, global_random_seed)
test_random_projection_embedding_quality (coo_container)
test_SparseRandomProj_output_representation (coo_container)
test_correct_RandomProjection_dimensions_embedding (coo_container, global_random_seed)
test_warning_n_components_greater_than_n_features (coo_container, global_random_seed)
test_works_with_sparse_data (coo_container, global_random_seed)
test_johnson_lindenstrauss_min_dim ()
test_random_projection_feature_names_out (coo_container, random_projection_cls, global_random_seed)
test_inverse_transform (coo_container, n_samples, n_features, random_projection_cls, compute_inverse_components, global_random_seed)
test_random_projection_dtype_match (random_projection_cls, input_dtype, expected_dtype)
test_random_projection_numerical_consistency (random_projection_cls)
Variables
list all_sparse_random_matrix = [_sparse_random_matrix]
list all_dense_random_matrix = [_gaussian_random_matrix]
list all_random_matrix = all_sparse_random_matrix + all_dense_random_matrix
list all_SparseRandomProjection = [SparseRandomProjection]
list all_DenseRandomProjection = [GaussianRandomProjection]
list all_RandomProjection = all_SparseRandomProjection + all_DenseRandomProjection
n_samples
n_features
n_nonzeros = int(n_samples * n_features / 100.0)
Function Documentation
check_input_size_random_matrix()
sklearn.tests.test_random_projection.check_input_size_random_matrix (random_matrix)
tests random matrix generation
Definition at line 106 of file test_random_projection.py.
References check_input_size_random_matrix().
Referenced by check_input_size_random_matrix().
check_input_with_sparse_random_matrix()
sklearn.tests.test_random_projection.check_input_with_sparse_random_matrix (random_matrix)
Definition at line 132 of file test_random_projection.py.
check_size_generated()
sklearn.tests.test_random_projection.check_size_generated (random_matrix)
Definition at line 113 of file test_random_projection.py.
check_zero_mean_and_unit_norm()
sklearn.tests.test_random_projection.check_zero_mean_and_unit_norm (random_matrix)
Definition at line 122 of file test_random_projection.py.
densify()
sklearn.tests.test_random_projection.densify (matrix)
Definition at line 65 of file test_random_projection.py.
make_sparse_random_data()
sklearn.tests.test_random_projection.make_sparse_random_data (coo_container, n_samples, n_features, n_nonzeros, random_state = None, sparse_format = "csr")
Make some random data with uniformly located non zero entries with
Gaussian distributed values; `sparse_format` can be `"csr"` (default) or
`None` (in which case a dense array is returned).
Definition at line 36 of file test_random_projection.py.
Referenced by test_johnson_lindenstrauss_min_dim(), and test_random_projection_transformer_invalid_input().
test_basic_property_of_random_matrix()
sklearn.tests.test_random_projection.test_basic_property_of_random_matrix (random_matrix)
Definition at line 141 of file test_random_projection.py.
test_basic_property_of_sparse_random_matrix()
sklearn.tests.test_random_projection.test_basic_property_of_sparse_random_matrix (random_matrix)
Definition at line 149 of file test_random_projection.py.
test_correct_RandomProjection_dimensions_embedding()
sklearn.tests.test_random_projection.test_correct_RandomProjection_dimensions_embedding (coo_container, global_random_seed)
Definition at line 348 of file test_random_projection.py.
test_gaussian_random_matrix()
sklearn.tests.test_random_projection.test_gaussian_random_matrix ()
Definition at line 157 of file test_random_projection.py.
test_input_size_jl_min_dim()
sklearn.tests.test_random_projection.test_input_size_jl_min_dim ()
Definition at line 94 of file test_random_projection.py.
test_invalid_jl_domain()
sklearn.tests.test_random_projection.test_invalid_jl_domain (n_samples, eps)
test on JL lemma
Definition at line 89 of file test_random_projection.py.
test_inverse_transform()
sklearn.tests.test_random_projection.test_inverse_transform (coo_container, n_samples, n_features, random_projection_cls, compute_inverse_components, global_random_seed)
Definition at line 489 of file test_random_projection.py.
test_johnson_lindenstrauss_min_dim()
sklearn.tests.test_random_projection.test_johnson_lindenstrauss_min_dim ()
Test Johnson-Lindenstrauss for small eps.
Regression test for #17111: before #19374, 32-bit systems would fail.
Definition at line 451 of file test_random_projection.py.
References make_sparse_random_data().
test_random_projection_dtype_match()
sklearn.tests.test_random_projection.test_random_projection_dtype_match (random_projection_cls, input_dtype, expected_dtype)
Definition at line 557 of file test_random_projection.py.
test_random_projection_embedding_quality()
sklearn.tests.test_random_projection.test_random_projection_embedding_quality (coo_container)
Definition at line 274 of file test_random_projection.py.
test_random_projection_feature_names_out()
sklearn.tests.test_random_projection.test_random_projection_feature_names_out (coo_container, random_projection_cls, global_random_seed)
Definition at line 461 of file test_random_projection.py.
test_random_projection_numerical_consistency()
sklearn.tests.test_random_projection.test_random_projection_numerical_consistency (random_projection_cls)
Definition at line 571 of file test_random_projection.py.
test_random_projection_transformer_invalid_input()
sklearn.tests.test_random_projection.test_random_projection_transformer_invalid_input ()
tests on random projection transformer
Definition at line 228 of file test_random_projection.py.
References make_sparse_random_data().
test_sparse_random_matrix()
sklearn.tests.test_random_projection.test_sparse_random_matrix ()
Definition at line 171 of file test_random_projection.py.
test_SparseRandomProj_output_representation()
sklearn.tests.test_random_projection.test_SparseRandomProj_output_representation (coo_container)
Definition at line 312 of file test_random_projection.py.
test_too_many_samples_to_find_a_safe_embedding()
sklearn.tests.test_random_projection.test_too_many_samples_to_find_a_safe_embedding (coo_container, global_random_seed)
Definition at line 252 of file test_random_projection.py.
test_try_to_transform_before_fit()
sklearn.tests.test_random_projection.test_try_to_transform_before_fit (coo_container, global_random_seed)
Definition at line 237 of file test_random_projection.py.
test_warning_n_components_greater_than_n_features()
sklearn.tests.test_random_projection.test_warning_n_components_greater_than_n_features (coo_container, global_random_seed)
Definition at line 401 of file test_random_projection.py.
test_works_with_sparse_data()
sklearn.tests.test_random_projection.test_works_with_sparse_data (coo_container, global_random_seed)
Definition at line 422 of file test_random_projection.py.
Variable Documentation
all_dense_random_matrix
list sklearn.tests.test_random_projection.all_dense_random_matrix = [_gaussian_random_matrix]
Definition at line 28 of file test_random_projection.py.
all_DenseRandomProjection
list sklearn.tests.test_random_projection.all_DenseRandomProjection = [GaussianRandomProjection]
Definition at line 32 of file test_random_projection.py.
all_random_matrix
list sklearn.tests.test_random_projection.all_random_matrix = all_sparse_random_matrix + all_dense_random_matrix
Definition at line 29 of file test_random_projection.py.
all_RandomProjection
list sklearn.tests.test_random_projection.all_RandomProjection = all_SparseRandomProjection + all_DenseRandomProjection
Definition at line 33 of file test_random_projection.py.
all_sparse_random_matrix
list sklearn.tests.test_random_projection.all_sparse_random_matrix = [_sparse_random_matrix]
Definition at line 27 of file test_random_projection.py.
all_SparseRandomProjection
list sklearn.tests.test_random_projection.all_SparseRandomProjection = [SparseRandomProjection]
Definition at line 31 of file test_random_projection.py.
n_features
sklearn.tests.test_random_projection.n_features
Definition at line 72 of file test_random_projection.py.
n_nonzeros
sklearn.tests.test_random_projection.n_nonzeros = int(n_samples * n_features / 100.0)
Definition at line 73 of file test_random_projection.py.
n_samples
sklearn.tests.test_random_projection.n_samples
Definition at line 72 of file test_random_projection.py.