Code Cloning Analysis: pandas.util.version.NegativeInfinityType Class Reference
pandas.util.version.NegativeInfinityType Class Reference
Public Member Functions
str __repr__ (self)
int __hash__ (self)
bool __lt__ (self, object other)
bool __le__ (self, object other)
bool __eq__ (self, object other)
bool __ne__ (self, object other)
bool __gt__ (self, object other)
bool __ge__ (self, object other)
InfinityType __neg__ (object self)
Detailed Description
Definition at line 57 of file __init__.py.
Member Function Documentation
__eq__()
bool pandas.util.version.NegativeInfinityType.__eq__ (self, object other)
Definition at line 70 of file __init__.py.
Referenced by pip._vendor.msgpack.ext.Timestamp.__ne__(), and pip._vendor.distlib.version.Matcher.match().
__ge__()
bool pandas.util.version.NegativeInfinityType.__ge__ (self, object other)
Definition at line 79 of file __init__.py.
__gt__()
bool pandas.util.version.NegativeInfinityType.__gt__ (self, object other)
Definition at line 76 of file __init__.py.
__hash__()
int pandas.util.version.NegativeInfinityType.__hash__ (self)
Definition at line 61 of file __init__.py.
Referenced by pip._vendor.rich.style.Style.pick_first().
__le__()
bool pandas.util.version.NegativeInfinityType.__le__ (self, object other)
Definition at line 67 of file __init__.py.
__lt__()
bool pandas.util.version.NegativeInfinityType.__lt__ (self, object other)
Definition at line 64 of file __init__.py.
__ne__()
bool pandas.util.version.NegativeInfinityType.__ne__ (self, object other)
Definition at line 73 of file __init__.py.
__neg__()
InfinityType pandas.util.version.NegativeInfinityType.__neg__ (object self)
Definition at line 82 of file __init__.py.
__repr__()
str pandas.util.version.NegativeInfinityType.__repr__ (self)
Definition at line 58 of file __init__.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/util/version/__init__.py