Code Cloning Analysis: pandas.core.dtypes.astype Namespace Reference
pandas.core.dtypes.astype Namespace Reference
Functions
np.ndarray _astype_nansafe (np.ndarray arr, np.dtype dtype, bool copy=..., bool skipna=...)
ExtensionArray _astype_nansafe (np.ndarray arr, ExtensionDtype dtype, bool copy=..., bool skipna=...)
ArrayLike _astype_nansafe (np.ndarray arr, DtypeObj dtype, bool copy=True, bool skipna=False)
np.ndarray _astype_float_to_int_nansafe (np.ndarray values, np.dtype dtype, bool copy)
ArrayLike astype_array (ArrayLike values, DtypeObj dtype, bool copy=False)
ArrayLike astype_array_safe (ArrayLike values, dtype, bool copy=False, IgnoreRaise errors="raise")
bool astype_is_view (DtypeObj dtype, DtypeObj new_dtype)
Variables
_dtype_obj = np.dtype(object)
Detailed Description
Functions for implementing 'astype' methods according to pandas conventions,
particularly ones that differ from numpy.
Function Documentation
_astype_float_to_int_nansafe()
np.ndarray pandas.core.dtypes.astype._astype_float_to_int_nansafe (np.ndarray values, np.dtype dtype, bool copy) protected
astype with a check preventing converting NaN to an meaningless integer value.
Definition at line 138 of file astype.py.
Referenced by _astype_nansafe().
_astype_nansafe() [1/3]
ArrayLike pandas.core.dtypes.astype._astype_nansafe (np.ndarray arr, DtypeObj dtype, bool copy = True, bool skipna = False) protected
Cast the elements of an array to a given dtype a nan-safe manner.
Parameters
----------
arr : ndarray
dtype : np.dtype or ExtensionDtype
copy : bool, default True
    If False, a view will be attempted but may fail, if
    e.g. the item sizes don't align.
skipna: bool, default False
    Whether or not we should skip NaN when casting as a string-type.
Raises
------
ValueError
    The dtype was a datetime64/timedelta64 dtype, but it had no unit.
Definition at line 56 of file astype.py.
References _astype_float_to_int_nansafe().
_astype_nansafe() [2/3]
ExtensionArray pandas.core.dtypes.astype._astype_nansafe (np.ndarray arr, ExtensionDtype dtype, bool copy = ..., bool skipna = ...) protected
Definition at line 50 of file astype.py.
_astype_nansafe() [3/3]
np.ndarray pandas.core.dtypes.astype._astype_nansafe (np.ndarray arr, np.dtype dtype, bool copy = ..., bool skipna = ...) protected
Definition at line 43 of file astype.py.
astype_array()
ArrayLike pandas.core.dtypes.astype.astype_array (ArrayLike values, DtypeObj dtype, bool copy = False)
Cast array (ndarray or ExtensionArray) to the new dtype.
Parameters
----------
values : ndarray or ExtensionArray
dtype : dtype object
copy : bool, default False
    copy if indicated
Returns
-------
ndarray or ExtensionArray
Definition at line 157 of file astype.py.
Referenced by astype_array_safe().
astype_array_safe()
ArrayLike pandas.core.dtypes.astype.astype_array_safe (ArrayLike values, dtype, bool copy = False, IgnoreRaise errors = "raise")
Cast array (ndarray or ExtensionArray) to the new dtype.
This basically is the implementation for DataFrame/Series.astype and
includes all custom logic for pandas (NaN-safety, converting str to object,
not allowing)
Parameters
----------
values : ndarray or ExtensionArray
dtype : str, dtype convertible
copy : bool, default False
    copy if indicated
errors : str, {'raise', 'ignore'}, default 'raise'
    - ``raise`` : allow exceptions to be raised
    - ``ignore`` : suppress exceptions. On error return original object
Returns
-------
ndarray or ExtensionArray
Definition at line 191 of file astype.py.
References astype_array().
astype_is_view()
bool pandas.core.dtypes.astype.astype_is_view (DtypeObj dtype, DtypeObj new_dtype)
Checks if astype avoided copying the data.
Parameters
----------
dtype : Original dtype
new_dtype : target dtype
Returns
-------
True if new data is a view or not guaranteed to be a copy, False otherwise
Definition at line 249 of file astype.py.
Variable Documentation
_dtype_obj
pandas.core.dtypes.astype._dtype_obj = np.dtype(object) protected
Definition at line 39 of file astype.py.