Code Cloning Analysis: fontTools.misc.loggingTools.CapturingLogHandler Class Reference
fontTools.misc.loggingTools.CapturingLogHandler Class Reference
Public Member Functions
__init__ (self, logger, level)
__enter__ (self)
__exit__ (self, type, value, traceback)
emit (self, record)
assertRegex (self, regexp, msg=None)
Public Attributes
list records = []
logger = logging.getLogger(logger)
original_disabled = self.logger.disabled
original_level = self.logger.level
original_propagate = self.logger.propagate
level
Detailed Description
Definition at line 437 of file loggingTools.py.
Constructor & Destructor Documentation
__init__()
fontTools.misc.loggingTools.CapturingLogHandler.__init__ (self, logger, level)
Definition at line 438 of file loggingTools.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__enter__()
fontTools.misc.loggingTools.CapturingLogHandler.__enter__ (self)
Definition at line 446 of file loggingTools.py.
__exit__()
fontTools.misc.loggingTools.CapturingLogHandler.__exit__ (self, type, value, traceback)
Definition at line 458 of file loggingTools.py.
assertRegex()
fontTools.misc.loggingTools.CapturingLogHandler.assertRegex (self, regexp, msg = None)
Definition at line 469 of file loggingTools.py.
emit()
fontTools.misc.loggingTools.CapturingLogHandler.emit (self, record)
Definition at line 466 of file loggingTools.py.
Member Data Documentation
level
fontTools.misc.loggingTools.CapturingLogHandler.level
Definition at line 452 of file loggingTools.py.
Referenced by pandas.core.groupby.groupby.BaseGroupBy.__iter__(), pandas.core.groupby.grouper.Grouper._get_grouper(), pandas.core.groupby.generic.DataFrameGroupBy._gotitem(), pandas.core.groupby.grouper.Grouping._ilevel(), pandas.core.groupby.grouper.Grouper._set_grouper(), and pandas.core.groupby.groupby.BaseGroupBy.get_group().
logger
fontTools.misc.loggingTools.CapturingLogHandler.logger = logging.getLogger(logger)
Definition at line 442 of file loggingTools.py.
Referenced by pip._vendor.chardet.universaldetector.UniversalDetector.close().
original_disabled
fontTools.misc.loggingTools.CapturingLogHandler.original_disabled = self.logger.disabled
Definition at line 447 of file loggingTools.py.
original_level
fontTools.misc.loggingTools.CapturingLogHandler.original_level = self.logger.level
Definition at line 448 of file loggingTools.py.
original_propagate
fontTools.misc.loggingTools.CapturingLogHandler.original_propagate = self.logger.propagate
Definition at line 449 of file loggingTools.py.
records
list fontTools.misc.loggingTools.CapturingLogHandler.records = []
Definition at line 440 of file loggingTools.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/misc/loggingTools.py