Code Cloning Analysis: joblib._dask.DaskDistributedBackend Class Reference
joblib._dask.DaskDistributedBackend Class Reference
Public Member Functions
__init__ (self, scheduler_host=None, scatter=None, client=None, loop=None, wait_for_workers_timeout=10, **submit_kwargs)
__reduce__ (self)
get_nested_backend (self)
configure (self, n_jobs=1, parallel=None, **backend_args)
start_call (self)
stop_call (self)
effective_n_jobs (self, n_jobs)
apply_async (self, func, callback=None)
retrieve_result_callback (self, out)
abort_everything (self, ensure_ready=True)
retrieval_context (self)
Public Member Functions inherited from joblib._parallel_backends.ParallelBackendBase
supports_return_generator (self)
supports_timeout (self)
__init__ (self, nesting_level=None, inner_max_num_threads=None, **backend_kwargs)
submit (self, func, callback=None)
retrieve_result (self, out, timeout=None)
terminate (self)
compute_batch_size (self)
batch_completed (self, batch_size, duration)
Public Attributes
client = client
dict data_futures = {id(x): f for x, f in zip(scatter, scattered)}
wait_for_workers_timeout = wait_for_workers_timeout
submit_kwargs = submit_kwargs
waiting_futures
call_data_futures = _WeakKeyDictionary()
Public Attributes inherited from joblib._parallel_backends.ParallelBackendBase
inner_max_num_threads = inner_max_num_threads
backend_kwargs = backend_kwargs
supports_timeout
parallel = parallel
Static Public Attributes
float MIN_IDEAL_BATCH_DURATION = 0.2
float MAX_IDEAL_BATCH_DURATION = 1.0
Static Public Attributes inherited from joblib._parallel_backends.ParallelBackendBase
int default_n_jobs = 1
bool supports_inner_max_num_threads = False
bool supports_retrieve_callback = False
nesting_level = None
list MAX_NUM_THREADS_VARS
str TBB_ENABLE_IPC_VAR = "ENABLE_IPC"
Protected Member Functions
_collect (self)
_to_func_args (self, func)
Protected Member Functions inherited from joblib._parallel_backends.ParallelBackendBase
_prepare_worker_env (self, n_jobs)
Protected Attributes
list _scatter = list(scatter)
dict _results = {}
dict _callbacks = {}
bool _continue
_collect = True
Additional Inherited Members
Static Public Member Functions inherited from joblib._parallel_backends.ParallelBackendBase
in_main_thread ()
Detailed Description
Definition at line 143 of file _dask.py.
Constructor & Destructor Documentation
__init__()
joblib._dask.DaskDistributedBackend.__init__ (self, scheduler_host = None, scatter = None, client = None, loop = None, wait_for_workers_timeout = 10, ** submit_kwargs)
Definition at line 149 of file _dask.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__reduce__()
joblib._dask.DaskDistributedBackend.__reduce__ (self)
Definition at line 221 of file _dask.py.
_collect()
joblib._dask.DaskDistributedBackend._collect (self) protected
Definition at line 208 of file _dask.py.
_to_func_args()
joblib._dask.DaskDistributedBackend._to_func_args (self, func) protected
Definition at line 272 of file _dask.py.
Referenced by apply_async().
abort_everything()
joblib._dask.DaskDistributedBackend.abort_everything (self, ensure_ready = True)
Tell the client to cancel any task submitted via this instance
joblib.Parallel will never access those results
Reimplemented from joblib._parallel_backends.ParallelBackendBase.
Definition at line 355 of file _dask.py.
References waiting_futures.
apply_async()
joblib._dask.DaskDistributedBackend.apply_async (self, func, callback = None)
Deprecated: implement `submit` instead.
Reimplemented from joblib._parallel_backends.ParallelBackendBase.
Definition at line 330 of file _dask.py.
References _callbacks, _results, _to_func_args(), client, joblib._parallel_backends.ParallelBackendBase.submit(), submit_kwargs, and waiting_futures.
Referenced by joblib._parallel_backends.ParallelBackendBase.submit().
configure()
joblib._dask.DaskDistributedBackend.configure (self, n_jobs = 1, parallel = None, ** prefer)
Reconfigure the backend and return the number of workers.
This makes it possible to reuse an existing backend instance for
successive independent calls to Parallel with different parameters.
Reimplemented from joblib._parallel_backends.ParallelBackendBase.
Definition at line 227 of file _dask.py.
References effective_n_jobs(), and parallel.
Referenced by joblib._parallel_backends.LokyBackend.abort_everything(), joblib._parallel_backends.PoolManagerMixin.abort_everything(), and scipy.optimize._zeros_py.TOMS748Solver.solve().
effective_n_jobs()
joblib._dask.DaskDistributedBackend.effective_n_jobs (self, n_jobs)
Determine the number of jobs that can actually run in parallel
n_jobs is the number of workers requested by the callers. Passing
n_jobs=-1 means requesting all available workers for instance matching
the number of CPU cores on the worker host(s).
This method should return a guesstimate of the number of workers that
can actually perform work concurrently. The primary use case is to make
it possible for the caller to know in how many chunks to slice the
work.
In general working on larger data chunks is more efficient (less
scheduling overhead and better use of CPU cache prefetching heuristics)
as long as all the workers have enough work to do.
Reimplemented from joblib._parallel_backends.ParallelBackendBase.
Definition at line 246 of file _dask.py.
References client, data_futures, joblib._parallel_backends.ParallelBackendBase.submit(), and wait_for_workers_timeout.
Referenced by configure(), joblib._parallel_backends.LokyBackend.configure(), joblib._parallel_backends.MultiprocessingBackend.configure(), joblib._parallel_backends.ParallelBackendBase.configure(), joblib._parallel_backends.ThreadingBackend.configure(), and joblib.test.test_parallel.FakeParallelBackend.configure().
get_nested_backend()
joblib._dask.DaskDistributedBackend.get_nested_backend (self)
Backend instance to be used by nested Parallel calls.
By default a thread-based backend is used for the first level of
nesting. Beyond, switch to sequential backend to avoid spawning too
many threads on the host.
Reimplemented from joblib._parallel_backends.ParallelBackendBase.
Definition at line 224 of file _dask.py.
References client.
retrieval_context()
joblib._dask.DaskDistributedBackend.retrieval_context (self)
Override ParallelBackendBase.retrieval_context to avoid deadlocks.
This removes thread from the worker's thread pool (using 'secede').
Seceding avoids deadlock in nested parallelism settings.
Reimplemented from joblib._parallel_backends.ParallelBackendBase.
Definition at line 366 of file _dask.py.
retrieve_result_callback()
joblib._dask.DaskDistributedBackend.retrieve_result_callback (self, out)
Called within the callback function passed to `submit`.
This method can customise how the result of the function is retrieved
from the future-like object.
Parameters
----------
future: future-like
    The future-like object returned by the `submit` method.
Returns
-------
result: object
    The result of the function executed in parallel.
Reimplemented from joblib._parallel_backends.ParallelBackendBase.
Definition at line 352 of file _dask.py.
start_call()
joblib._dask.DaskDistributedBackend.start_call (self)
Call-back method called at the beginning of a Parallel call
Reimplemented from joblib._parallel_backends.ParallelBackendBase.
Definition at line 231 of file _dask.py.
References _collect, _continue, call_data_futures, and client.
stop_call()
joblib._dask.DaskDistributedBackend.stop_call (self)
Call-back method called at the end of a Parallel call
Reimplemented from joblib._parallel_backends.ParallelBackendBase.
Definition at line 236 of file _dask.py.
References _continue, and call_data_futures.
Member Data Documentation
_callbacks
dict joblib._dask.DaskDistributedBackend._callbacks = {} protected
Definition at line 206 of file _dask.py.
Referenced by matplotlib.backend_managers.ToolManager.add_tool(), apply_async(), matplotlib.backend_managers.ToolManager.message_event(), matplotlib.backend_managers.ToolManager.remove_tool(), matplotlib.backend_managers.ToolManager.toolmanager_connect(), matplotlib.backend_managers.ToolManager.toolmanager_disconnect(), and matplotlib.backend_managers.ToolManager.trigger_tool().
_collect
joblib._dask.DaskDistributedBackend._collect = True protected
Definition at line 233 of file _dask.py.
Referenced by start_call().
_continue
bool joblib._dask.DaskDistributedBackend._continue protected
Definition at line 209 of file _dask.py.
Referenced by start_call(), and stop_call().
_results
dict joblib._dask.DaskDistributedBackend._results = {} protected
Definition at line 205 of file _dask.py.
Referenced by apply_async().
_scatter
list joblib._dask.DaskDistributedBackend._scatter = list(scatter) protected
Definition at line 194 of file _dask.py.
call_data_futures
joblib._dask.DaskDistributedBackend.call_data_futures = _WeakKeyDictionary()
Definition at line 234 of file _dask.py.
Referenced by start_call(), and stop_call().
client
joblib._dask.DaskDistributedBackend.client = client
Definition at line 185 of file _dask.py.
Referenced by pip._vendor.distlib.locators.PyPIRPCLocator.__init__(), pip._vendor.distlib.locators.PyPIRPCLocator._get_project(), apply_async(), effective_n_jobs(), pip._vendor.distlib.locators.PyPIRPCLocator.get_distribution_names(), get_nested_backend(), and start_call().
data_futures
dict joblib._dask.DaskDistributedBackend.data_futures = {id(x): f for x, f in zip(scatter, scattered)}
Definition at line 196 of file _dask.py.
Referenced by effective_n_jobs().
MAX_IDEAL_BATCH_DURATION
float joblib._dask.DaskDistributedBackend.MAX_IDEAL_BATCH_DURATION = 1.0 static
Definition at line 145 of file _dask.py.
Referenced by joblib._parallel_backends.AutoBatchingMixin.compute_batch_size().
MIN_IDEAL_BATCH_DURATION
float joblib._dask.DaskDistributedBackend.MIN_IDEAL_BATCH_DURATION = 0.2 static
Definition at line 144 of file _dask.py.
Referenced by joblib._parallel_backends.AutoBatchingMixin.compute_batch_size().
submit_kwargs
joblib._dask.DaskDistributedBackend.submit_kwargs = submit_kwargs
Definition at line 201 of file _dask.py.
Referenced by apply_async().
wait_for_workers_timeout
joblib._dask.DaskDistributedBackend.wait_for_workers_timeout = wait_for_workers_timeout
Definition at line 200 of file _dask.py.
Referenced by effective_n_jobs().
waiting_futures
joblib._dask.DaskDistributedBackend.waiting_futures
Initial value:
=  as_completed(
            [], loop=client.loop, with_results=True, raise_errors=False
        )
Definition at line 202 of file _dask.py.
Referenced by abort_everything(), and apply_async().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/joblib/_dask.py