Code Cloning Analysis: scipy._lib.tests.test_public_api Namespace Reference
scipy._lib.tests.test_public_api Namespace Reference
Functions
test_dir_testing ()
is_unexpected (name)
test_all_modules_are_expected ()
test_all_modules_are_expected_2 ()
test_api_importable ()
Variables
list PUBLIC_MODULES
list PRIVATE_BUT_PRESENT_MODULES
list SKIP_LIST
list SKIP_LIST_2
Detailed Description
This test script is adopted from:
    https://github.com/numpy/numpy/blob/main/numpy/tests/test_public_api.py
Function Documentation
is_unexpected()
scipy._lib.tests.test_public_api.is_unexpected (name)
Check if this needs to be considered.
Definition at line 194 of file test_public_api.py.
Referenced by test_all_modules_are_expected(), and test_all_modules_are_expected_2().
test_all_modules_are_expected()
scipy._lib.tests.test_public_api.test_all_modules_are_expected ()
Test that we don't add anything that looks like a new public module by
accident.  Check is based on filenames.
Definition at line 214 of file test_public_api.py.
References is_unexpected().
test_all_modules_are_expected_2()
scipy._lib.tests.test_public_api.test_all_modules_are_expected_2 ()
Method checking all objects. The pkgutil-based method in
`test_all_modules_are_expected` does not catch imports into a namespace,
only filenames.
Definition at line 247 of file test_public_api.py.
References is_unexpected().
test_api_importable()
scipy._lib.tests.test_public_api.test_api_importable ()
Check that all submodules listed higher up in this file can be imported
Note that if a PRIVATE_BUT_PRESENT_MODULES entry goes missing, it may
simply need to be removed from the list (deprecation may or may not be
needed - apply common sense).
Definition at line 280 of file test_public_api.py.
test_dir_testing()
scipy._lib.tests.test_public_api.test_dir_testing ()
Assert that output of dir has only one "testing/tester"
attribute without duplicate
Definition at line 14 of file test_public_api.py.
Variable Documentation
PRIVATE_BUT_PRESENT_MODULES
list scipy._lib.tests.test_public_api.PRIVATE_BUT_PRESENT_MODULES
Definition at line 74 of file test_public_api.py.
PUBLIC_MODULES
list scipy._lib.tests.test_public_api.PUBLIC_MODULES
Definition at line 27 of file test_public_api.py.
SKIP_LIST
list scipy._lib.tests.test_public_api.SKIP_LIST
Initial value:
=  [
    'scipy.conftest',
    'scipy.version',
]
Definition at line 208 of file test_public_api.py.
SKIP_LIST_2
list scipy._lib.tests.test_public_api.SKIP_LIST_2
Initial value:
=  [
    'scipy.char',
    'scipy.rec',
    'scipy.emath',
    'scipy.math',
    'scipy.random',
    'scipy.ctypeslib',
    'scipy.ma'
]
Definition at line 236 of file test_public_api.py.