Code Cloning Analysis: sklearn.tests.test_metaestimators_metadata_routing Namespace Reference
sklearn.tests.test_metaestimators_metadata_routing Namespace Reference
Functions
get_init_args (metaestimator_info, sub_estimator_consumes)
set_requests (obj, *, method_mapping, methods, metadata_name, value=True)
test_unsupported_estimators_get_metadata_routing (estimator)
test_unsupported_estimators_fit_with_metadata (estimator)
test_registry_copy ()
test_default_request (metaestimator)
test_error_on_missing_requests_for_sub_estimator (metaestimator)
test_setting_request_on_sub_estimator_removes_error (metaestimator)
test_non_consuming_estimator_works (metaestimator)
test_metadata_is_routed_correctly_to_scorer (metaestimator)
test_metadata_is_routed_correctly_to_splitter (metaestimator)
test_metadata_routed_to_group_splitter (metaestimator)
Variables
rng = np.random.RandomState(42)
N
M
X = rng.rand(N, M)
y = rng.randint(0, 3, size=N)
tuple y_binary = (y >= 1).astype(int)
classes = np.unique(y)
y_multi = rng.randint(0, 3, size=(N, 3))
list classes_multi = [np.unique(y_multi[:, i]) for i in range(y_multi.shape[1])]
metadata = rng.randint(0, 10, size=N)
sample_weight = rng.rand(N)
groups = rng.randint(0, 10, size=len(y))
list METAESTIMATORS
list METAESTIMATOR_IDS = [str(row["metaestimator"].__name__) for row in METAESTIMATORS]
list UNSUPPORTED_ESTIMATORS
Function Documentation
get_init_args()
sklearn.tests.test_metaestimators_metadata_routing.get_init_args (metaestimator_info, sub_estimator_consumes)
Get the init args for a metaestimator
This is a helper function to get the init args for a metaestimator from
the METAESTIMATORS list. It returns an empty dict if no init args are
required.
Parameters
----------
metaestimator_info : dict
    The metaestimator info from METAESTIMATORS
sub_estimator_consumes : bool
    Whether the sub-estimator consumes metadata or not.
Returns
-------
kwargs : dict
    The init args for the metaestimator.
(estimator, estimator_registry) : (estimator, registry)
    The sub-estimator and the corresponding registry.
(scorer, scorer_registry) : (scorer, registry)
    The scorer and the corresponding registry.
(cv, cv_registry) : (CV splitter, registry)
    The CV splitter and the corresponding registry.
Definition at line 494 of file test_metaestimators_metadata_routing.py.
Referenced by test_metadata_is_routed_correctly_to_scorer(), test_metadata_is_routed_correctly_to_splitter(), test_metadata_routed_to_group_splitter(), and test_unsupported_estimators_fit_with_metadata().
set_requests()
sklearn.tests.test_metaestimators_metadata_routing.set_requests (obj, * , method_mapping, methods, metadata_name, value = True)
Call `set_{method}_request` on a list of methods from the sub-estimator.
Parameters
----------
obj : BaseEstimator
    The object for which `set_{method}_request` methods are called.
method_mapping : dict
    The method mapping in the form of `{caller: [callee, ...]}`.
    If a "caller" is not present in the method mapping, a one-to-one mapping is
    assumed.
methods : list of str
    The list of methods as "caller"s for which the request for the child should
    be set.
metadata_name : str
    The name of the metadata to be routed, usually either `"metadata"` or
    `"sample_weight"` in our tests.
value : None, bool, or str
    The request value to be set, by default it's `True`
Definition at line 565 of file test_metaestimators_metadata_routing.py.
Referenced by test_metadata_is_routed_correctly_to_scorer(), and test_unsupported_estimators_fit_with_metadata().
test_default_request()
sklearn.tests.test_metaestimators_metadata_routing.test_default_request (metaestimator)
Definition at line 637 of file test_metaestimators_metadata_routing.py.
test_error_on_missing_requests_for_sub_estimator()
sklearn.tests.test_metaestimators_metadata_routing.test_error_on_missing_requests_for_sub_estimator (metaestimator)
Definition at line 654 of file test_metaestimators_metadata_routing.py.
test_metadata_is_routed_correctly_to_scorer()
sklearn.tests.test_metaestimators_metadata_routing.test_metadata_is_routed_correctly_to_scorer (metaestimator)
Test that any requested metadata is correctly routed to the underlying
scorers in CV estimators.
Definition at line 822 of file test_metaestimators_metadata_routing.py.
References get_init_args(), and set_requests().
test_metadata_is_routed_correctly_to_splitter()
sklearn.tests.test_metaestimators_metadata_routing.test_metadata_is_routed_correctly_to_splitter (metaestimator)
Test that any requested metadata is correctly routed to the underlying
splitters in CV estimators.
Definition at line 868 of file test_metaestimators_metadata_routing.py.
References get_init_args().
test_metadata_routed_to_group_splitter()
sklearn.tests.test_metaestimators_metadata_routing.test_metadata_routed_to_group_splitter (metaestimator)
Test that groups are routed correctly if group splitter of CV estimator is used
within cross_validate. Regression test for issue described in PR #29634 to test that
`ValueError: The 'groups' parameter should not be None.` is not raised.
Definition at line 903 of file test_metaestimators_metadata_routing.py.
References get_init_args().
test_non_consuming_estimator_works()
sklearn.tests.test_metaestimators_metadata_routing.test_non_consuming_estimator_works (metaestimator)
Definition at line 783 of file test_metaestimators_metadata_routing.py.
test_registry_copy()
sklearn.tests.test_metaestimators_metadata_routing.test_registry_copy ()
Definition at line 626 of file test_metaestimators_metadata_routing.py.
test_setting_request_on_sub_estimator_removes_error()
sklearn.tests.test_metaestimators_metadata_routing.test_setting_request_on_sub_estimator_removes_error (metaestimator)
Definition at line 713 of file test_metaestimators_metadata_routing.py.
test_unsupported_estimators_fit_with_metadata()
sklearn.tests.test_metaestimators_metadata_routing.test_unsupported_estimators_fit_with_metadata (estimator)
Test that fit raises NotImplementedError when metadata routing is
enabled and a metadata is passed on meta-estimators for which we haven't
implemented routing yet.
Definition at line 612 of file test_metaestimators_metadata_routing.py.
References get_init_args(), and set_requests().
test_unsupported_estimators_get_metadata_routing()
sklearn.tests.test_metaestimators_metadata_routing.test_unsupported_estimators_get_metadata_routing (estimator)
Test that get_metadata_routing is not implemented on meta-estimators for
which we haven't implemented routing yet.
Definition at line 603 of file test_metaestimators_metadata_routing.py.
Variable Documentation
classes
sklearn.tests.test_metaestimators_metadata_routing.classes = np.unique(y)
Definition at line 85 of file test_metaestimators_metadata_routing.py.
classes_multi
list sklearn.tests.test_metaestimators_metadata_routing.classes_multi = [np.unique(y_multi[:, i]) for i in range(y_multi.shape[1])]
Definition at line 87 of file test_metaestimators_metadata_routing.py.
groups
sklearn.tests.test_metaestimators_metadata_routing.groups = rng.randint(0, 10, size=len(y))
Definition at line 90 of file test_metaestimators_metadata_routing.py.
M
sklearn.tests.test_metaestimators_metadata_routing.M
Definition at line 81 of file test_metaestimators_metadata_routing.py.
metadata
sklearn.tests.test_metaestimators_metadata_routing.metadata = rng.randint(0, 10, size=N)
Definition at line 88 of file test_metaestimators_metadata_routing.py.
METAESTIMATOR_IDS
list sklearn.tests.test_metaestimators_metadata_routing.METAESTIMATOR_IDS = [str(row["metaestimator"].__name__) for row in METAESTIMATORS]
Definition at line 486 of file test_metaestimators_metadata_routing.py.
METAESTIMATORS
list sklearn.tests.test_metaestimators_metadata_routing.METAESTIMATORS
Definition at line 93 of file test_metaestimators_metadata_routing.py.
N
sklearn.tests.test_metaestimators_metadata_routing.N
Definition at line 81 of file test_metaestimators_metadata_routing.py.
rng
sklearn.tests.test_metaestimators_metadata_routing.rng = np.random.RandomState(42)
Definition at line 80 of file test_metaestimators_metadata_routing.py.
sample_weight
sklearn.tests.test_metaestimators_metadata_routing.sample_weight = rng.rand(N)
Definition at line 89 of file test_metaestimators_metadata_routing.py.
UNSUPPORTED_ESTIMATORS
list sklearn.tests.test_metaestimators_metadata_routing.UNSUPPORTED_ESTIMATORS
Initial value:
=  [
    AdaBoostClassifier(),
    AdaBoostRegressor(),
]
Definition at line 488 of file test_metaestimators_metadata_routing.py.
X
sklearn.tests.test_metaestimators_metadata_routing.X = rng.rand(N, M)
Definition at line 82 of file test_metaestimators_metadata_routing.py.
y
sklearn.tests.test_metaestimators_metadata_routing.y = rng.randint(0, 3, size=N)
Definition at line 83 of file test_metaestimators_metadata_routing.py.
y_binary
tuple sklearn.tests.test_metaestimators_metadata_routing.y_binary = (y >= 1).astype(int)
Definition at line 84 of file test_metaestimators_metadata_routing.py.
y_multi
sklearn.tests.test_metaestimators_metadata_routing.y_multi = rng.randint(0, 3, size=(N, 3))
Definition at line 86 of file test_metaestimators_metadata_routing.py.