Code Cloning Analysis: scipy.integrate.tests.test_integrate.CoupledDecay Class Reference
scipy.integrate.tests.test_integrate.CoupledDecay Class Reference
Public Member Functions
f (self, z, t)
jac (self, z, t)
verify (self, zs, t)
Static Public Attributes
list lmbd = [0.17, 0.23, 0.29]
Static Public Attributes inherited from scipy.integrate.tests.test_integrate.ODE
bool stiff = False
bool cmplx = False
int stop_t = 1
list z0 = []
lband = None
uband = None
int atol = 1e-6
int rtol = 1e-5
Detailed Description
3 coupled decays suited for banded treatment
(banded mode makes it necessary when N>>3)
Definition at line 465 of file test_integrate.py.
Member Function Documentation
f()
scipy.integrate.tests.test_integrate.CoupledDecay.f (self, z, t)
Definition at line 479 of file test_integrate.py.
Referenced by scipy.optimize._shgo_lib._vertex.VertexScalarField.maximiser(), and scipy.optimize._shgo_lib._vertex.VertexScalarField.minimiser().
jac()
scipy.integrate.tests.test_integrate.CoupledDecay.jac (self, z, t)
Definition at line 485 of file test_integrate.py.
Referenced by scipy.optimize.tests.test_slsqp.TestSLSQP.fprime_ieqcon2(), and scipy.optimize.tests.test_slsqp.TestSLSQP.jac().
verify()
scipy.integrate.tests.test_integrate.CoupledDecay.verify (self, zs, t)
Definition at line 510 of file test_integrate.py.
Member Data Documentation
lmbd
list scipy.integrate.tests.test_integrate.CoupledDecay.lmbd = [0.17, 0.23, 0.29] static
Definition at line 477 of file test_integrate.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/integrate/tests/test_integrate.py