Code Cloning Analysis: pandas.tseries.holiday Namespace Reference
pandas.tseries.holiday Namespace Reference
Classes
class AbstractHolidayCalendar
class Holiday
class HolidayCalendarMetaClass
class USFederalHolidayCalendar
Functions
datetime next_monday (datetime dt)
datetime next_monday_or_tuesday (datetime dt)
datetime previous_friday (datetime dt)
datetime sunday_to_monday (datetime dt)
datetime weekend_to_monday (datetime dt)
datetime nearest_workday (datetime dt)
datetime next_workday (datetime dt)
datetime previous_workday (datetime dt)
datetime before_nearest_workday (datetime dt)
datetime after_nearest_workday (datetime dt)
None register (cls)
get_calendar (str name)
HolidayCalendarFactory (str name, base, other, base_class=AbstractHolidayCalendar)
Variables
dict holiday_calendars = {}
USMemorialDay
USLaborDay = Holiday("Labor Day", month=9, day=1, offset=DateOffset(weekday=MO(1)))
USColumbusDay
USThanksgivingDay
USMartinLutherKingJr
USPresidentsDay
GoodFriday = Holiday("Good Friday", month=1, day=1, offset=[Easter(), Day(-2)])
EasterMonday = Holiday("Easter Monday", month=1, day=1, offset=[Easter(), Day(1)])
list __all__
Function Documentation
after_nearest_workday()
datetime pandas.tseries.holiday.after_nearest_workday (datetime dt)
returns next workday after nearest workday
needed for Boxing day or multiple holidays in a series
Definition at line 138 of file holiday.py.
References nearest_workday(), and next_workday().
before_nearest_workday()
datetime pandas.tseries.holiday.before_nearest_workday (datetime dt)
returns previous workday after nearest workday
Definition at line 131 of file holiday.py.
References nearest_workday(), and previous_workday().
get_calendar()
pandas.tseries.holiday.get_calendar (str name)
Return an instance of a calendar based on its name.
Parameters
----------
name : str
    Calendar name to return an instance of
Definition at line 387 of file holiday.py.
HolidayCalendarFactory()
pandas.tseries.holiday.HolidayCalendarFactory (str name, base, other, base_class = AbstractHolidayCalendar)
Definition at line 607 of file holiday.py.
nearest_workday()
datetime pandas.tseries.holiday.nearest_workday (datetime dt)
If holiday falls on Saturday, use day before (Friday) instead;
if holiday falls on Sunday, use day thereafter (Monday) instead.
Definition at line 97 of file holiday.py.
Referenced by after_nearest_workday(), and before_nearest_workday().
next_monday()
datetime pandas.tseries.holiday.next_monday (datetime dt)
If holiday falls on Saturday, use following Monday instead;
if holiday falls on Sunday, use Monday instead
Definition at line 37 of file holiday.py.
next_monday_or_tuesday()
datetime pandas.tseries.holiday.next_monday_or_tuesday (datetime dt)
For second holiday of two adjacent ones!
If holiday falls on Saturday, use following Monday instead;
if holiday falls on Sunday or Monday, use following Tuesday instead
(because Monday is already taken by adjacent holiday on the day before)
Definition at line 49 of file holiday.py.
next_workday()
datetime pandas.tseries.holiday.next_workday (datetime dt)
returns next weekday used for observances
Definition at line 109 of file holiday.py.
Referenced by after_nearest_workday().
previous_friday()
datetime pandas.tseries.holiday.previous_friday (datetime dt)
If holiday falls on Saturday or Sunday, use previous Friday instead.
Definition at line 64 of file holiday.py.
previous_workday()
datetime pandas.tseries.holiday.previous_workday (datetime dt)
returns previous weekday used for observances
Definition at line 120 of file holiday.py.
Referenced by before_nearest_workday().
register()
None pandas.tseries.holiday.register (cls)
Definition at line 379 of file holiday.py.
sunday_to_monday()
datetime pandas.tseries.holiday.sunday_to_monday (datetime dt)
If holiday falls on Sunday, use day thereafter (Monday) instead.
Definition at line 75 of file holiday.py.
weekend_to_monday()
datetime pandas.tseries.holiday.weekend_to_monday (datetime dt)
If holiday falls on Sunday or Saturday,
use day thereafter (Monday) instead.
Needed for holidays such as Christmas observation in Europe
Definition at line 84 of file holiday.py.
Variable Documentation
__all__
list pandas.tseries.holiday.__all__ private
Initial value:
=  [
    "after_nearest_workday",
    "before_nearest_workday",
    "FR",
    "get_calendar",
    "HolidayCalendarFactory",
    "MO",
    "nearest_workday",
    "next_monday",
    "next_monday_or_tuesday",
    "next_workday",
    "previous_friday",
    "previous_workday",
    "register",
    "SA",
    "SU",
    "sunday_to_monday",
    "TH",
    "TU",
    "WE",
    "weekend_to_monday",
]
Definition at line 613 of file holiday.py.
EasterMonday
pandas.tseries.holiday.EasterMonday = Holiday("Easter Monday", month=1, day=1, offset=[Easter(), Day(1)])
Definition at line 577 of file holiday.py.
GoodFriday
pandas.tseries.holiday.GoodFriday = Holiday("Good Friday", month=1, day=1, offset=[Easter(), Day(-2)])
Definition at line 575 of file holiday.py.
holiday_calendars
dict pandas.tseries.holiday.holiday_calendars = {}
Definition at line 376 of file holiday.py.
USColumbusDay
pandas.tseries.holiday.USColumbusDay
Initial value:
=  Holiday(
    "Columbus Day", month=10, day=1, offset=DateOffset(weekday=MO(2))
)
Definition at line 559 of file holiday.py.
USLaborDay
pandas.tseries.holiday.USLaborDay = Holiday("Labor Day", month=9, day=1, offset=DateOffset(weekday=MO(1)))
Definition at line 558 of file holiday.py.
USMartinLutherKingJr
pandas.tseries.holiday.USMartinLutherKingJr
Initial value:
=  Holiday(
    "Birthday of Martin Luther King, Jr.",
    start_date=datetime(1986, 1, 1),
    month=1,
    day=1,
    offset=DateOffset(weekday=MO(3)),
)
Definition at line 565 of file holiday.py.
USMemorialDay
pandas.tseries.holiday.USMemorialDay
Initial value:
=  Holiday(
    "Memorial Day", month=5, day=31, offset=DateOffset(weekday=MO(-1))
)
Definition at line 555 of file holiday.py.
USPresidentsDay
pandas.tseries.holiday.USPresidentsDay
Initial value:
=  Holiday(
    "Washington's Birthday", month=2, day=1, offset=DateOffset(weekday=MO(3))
)
Definition at line 572 of file holiday.py.
USThanksgivingDay
pandas.tseries.holiday.USThanksgivingDay
Initial value:
=  Holiday(
    "Thanksgiving Day", month=11, day=1, offset=DateOffset(weekday=TH(4))
)
Definition at line 562 of file holiday.py.