Code Cloning Analysis: sklearn.metrics.cluster._bicluster Namespace Reference
sklearn.metrics.cluster._bicluster Namespace Reference
Functions
_check_rows_and_columns (a, b)
_jaccard (a_rows, a_cols, b_rows, b_cols)
_pairwise_similarity (a, b, similarity)
consensus_score (a, b, *, similarity="jaccard")
Variables
list __all__ = ["consensus_score"]
Function Documentation
_check_rows_and_columns()
sklearn.metrics.cluster._bicluster._check_rows_and_columns (a, b) protected
Unpacks the row and column arrays and checks their shape.
Definition at line 13 of file _bicluster.py.
Referenced by _pairwise_similarity().
_jaccard()
sklearn.metrics.cluster._bicluster._jaccard (a_rows, a_cols, b_rows, b_cols) protected
Jaccard coefficient on the elements of the two biclusters.
Definition at line 23 of file _bicluster.py.
_pairwise_similarity()
sklearn.metrics.cluster._bicluster._pairwise_similarity (a, b, similarity) protected
Computes pairwise similarity matrix.
result[i, j] is the Jaccard coefficient of a's bicluster i and b's
bicluster j.
Definition at line 33 of file _bicluster.py.
References _check_rows_and_columns().
Referenced by consensus_score().
consensus_score()
sklearn.metrics.cluster._bicluster.consensus_score (a, b, * , similarity = "jaccard")
The similarity of two sets of biclusters.
Similarity between individual biclusters is computed. Then the best
matching between sets is found by solving a linear sum assignment problem,
using a modified Jonker-Volgenant algorithm.
The final score is the sum of similarities divided by the size of
the larger set.
Read more in the :ref:`User Guide <biclustering>`.
Parameters
----------
a : tuple (rows, columns)
    Tuple of row and column indicators for a set of biclusters.
b : tuple (rows, columns)
    Another set of biclusters like ``a``.
similarity : 'jaccard' or callable, default='jaccard'
    May be the string "jaccard" to use the Jaccard coefficient, or
    any function that takes four arguments, each of which is a 1d
    indicator vector: (a_rows, a_columns, b_rows, b_columns).
Returns
-------
consensus_score : float
   Consensus score, a non-negative value, sum of similarities
   divided by size of larger set.
See Also
--------
scipy.optimize.linear_sum_assignment : Solve the linear sum assignment problem.
References
----------
* Hochreiter, Bodenhofer, et. al., 2010. `FABIA: factor analysis
  for bicluster acquisition
  <https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2881408/>`__.
Examples
--------
>>> from sklearn.metrics import consensus_score
>>> a = ([[True, False], [False, True]], [[False, True], [True, False]])
>>> b = ([[False, True], [True, False]], [[True, False], [False, True]])
>>> consensus_score(a, b, similarity='jaccard')
1.0
Definition at line 60 of file _bicluster.py.
References _pairwise_similarity().
Variable Documentation
__all__
list sklearn.metrics.cluster._bicluster.__all__ = ["consensus_score"] private
Definition at line 10 of file _bicluster.py.