Code Cloning Analysis: matplotlib.backends.backend_pdf.FigureCanvasPdf Class Reference
matplotlib.backends.backend_pdf.FigureCanvasPdf Class Reference
Public Member Functions
get_default_filetype (self)
print_pdf (self, filename, *, bbox_inches_restore=None, metadata=None)
draw (self)
Public Member Functions inherited from matplotlib.backend_bases.FigureCanvasBase
supports_blit (cls)
__init__ (self, figure=None)
new_manager (cls, figure, num)
is_saving (self)
blit (self, bbox=None)
inaxes (self, xy)
grab_mouse (self, ax)
release_mouse (self, ax)
set_cursor (self, cursor)
draw_idle (self, *args, **kwargs)
device_pixel_ratio (self)
get_width_height (self, *, physical=False)
get_supported_filetypes (cls)
get_supported_filetypes_grouped (cls)
print_figure (self, filename, dpi=None, facecolor=None, edgecolor=None, orientation='portrait', format=None, *, bbox_inches=None, pad_inches=None, bbox_extra_artists=None, backend=None, **kwargs)
get_default_filename (self)
mpl_connect (self, s, func)
mpl_disconnect (self, cid)
new_timer (self, interval=None, callbacks=None)
flush_events (self)
start_event_loop (self, timeout=0)
stop_event_loop (self)
Additional Inherited Members
Public Attributes inherited from matplotlib.backend_bases.FigureCanvasBase
figure = figure
manager = None
widgetlock = widgets.LockDraw()
mouse_grabber = None
toolbar = None
device_pixel_ratio
Static Public Attributes inherited from matplotlib.backend_bases.FigureCanvasBase
required_interactive_framework = None
manager_class = _api.classproperty(lambda cls: FigureManagerBase)
list events
fixed_dpi = None
filetypes = _default_filetypes
Protected Member Functions inherited from matplotlib.backend_bases.FigureCanvasBase
_fix_ipython_backend2gui (cls)
_idle_draw_cntx (self)
_set_device_pixel_ratio (self, ratio)
_switch_canvas_and_return_print_method (self, fmt, backend=None)
Protected Attributes inherited from matplotlib.backend_bases.FigureCanvasBase
bool _is_idle_drawing = True
bool _is_saving = False
_button = None
_key = None
int _device_pixel_ratio = 1
bool _looping = True
Static Protected Attributes inherited from matplotlib.backend_bases.FigureCanvasBase
_timer_cls = TimerBase
Properties inherited from matplotlib.backend_bases.FigureCanvasBase
callbacks = property(lambda self: self.figure._canvas_callbacks)
button_pick_id = property(lambda self: self.figure._button_pick_id)
scroll_pick_id = property(lambda self: self.figure._scroll_pick_id)
Detailed Description
Definition at line 2761 of file backend_pdf.py.
Member Function Documentation
draw()
matplotlib.backends.backend_pdf.FigureCanvasPdf.draw (self)
Render the `.Figure`.
This method must walk the artist tree, even if no output is produced,
because it triggers deferred work that users may want to access
before saving output to disk. For example computing limits,
auto-limits, and tick values.
Reimplemented from matplotlib.backend_bases.FigureCanvasBase.
Definition at line 2796 of file backend_pdf.py.
References draw(), and matplotlib.backend_bases.FigureCanvasBase.figure.
Referenced by draw(), and get_default_filetype().
get_default_filetype()
matplotlib.backends.backend_pdf.FigureCanvasPdf.get_default_filetype (cls)
Return the default savefig file format as specified in
:rc:`savefig.format`.
The returned string does not include a period. This method is
overridden in backends that only support a single file type.
Reimplemented from matplotlib.backend_bases.FigureCanvasBase.
Definition at line 2767 of file backend_pdf.py.
References draw(), and matplotlib.backend_bases.FigureCanvasBase.figure.
print_pdf()
matplotlib.backends.backend_pdf.FigureCanvasPdf.print_pdf (self, filename, * , bbox_inches_restore = None, metadata = None)
Definition at line 2770 of file backend_pdf.py.
Referenced by matplotlib.backends.backend_pgf.FigureCanvasPgf.print_png().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/backends/backend_pdf.py