Code Cloning Analysis: joblib.numpy_pickle_compat Namespace Reference
joblib.numpy_pickle_compat Namespace Reference
Classes
class NDArrayWrapper
Utility objects for persistence.
class ZipNumpyUnpickler
class ZNDArrayWrapper
Functions
hex_str (an_int)
asbytes (s)
read_zfile (file_handle)
write_zfile (file_handle, data, compress=1)
load_compatibility (filename)
Variables
_MAX_LEN = len(hex_str(2**64))
int _CHUNK_SIZE = 64 * 1024
Detailed Description
Numpy pickle compatibility functions.
Function Documentation
asbytes()
joblib.numpy_pickle_compat.asbytes (s)
Definition at line 22 of file numpy_pickle_compat.py.
hex_str()
joblib.numpy_pickle_compat.hex_str (an_int)
Convert an int to an hexadecimal string.
Definition at line 17 of file numpy_pickle_compat.py.
References hex_str().
Referenced by hex_str(), and write_zfile().
load_compatibility()
joblib.numpy_pickle_compat.load_compatibility (filename)
Reconstruct a Python object from a file persisted with joblib.dump.
This function ensures the compatibility with joblib old persistence format
(<= 0.9.3).
Parameters
----------
filename: string
    The name of the file from which to load the object
Returns
-------
result: any Python object
    The object stored in the file.
See Also
--------
joblib.dump : function to save an object
Notes
-----
This function can load numpy array files saved separately during the
dump.
Definition at line 204 of file numpy_pickle_compat.py.
read_zfile()
joblib.numpy_pickle_compat.read_zfile (file_handle)
Read the z-file and return the content as a string.
Z-files are raw data compressed with zlib used internally by joblib
for persistence. Backward compatibility is not guaranteed. Do not
use for external purposes.
Definition at line 32 of file numpy_pickle_compat.py.
Referenced by joblib.numpy_pickle_compat.ZipNumpyUnpickler.__init__(), and joblib.numpy_pickle_compat.ZNDArrayWrapper.read().
write_zfile()
joblib.numpy_pickle_compat.write_zfile (file_handle, data, compress = 1)
Write the data in the given file as a Z-file.
Z-files are raw data compressed with zlib used internally by joblib
for persistence. Backward compatibility is not guaranteed. Do not
use for external purposes.
Definition at line 66 of file numpy_pickle_compat.py.
References hex_str().
Variable Documentation
_CHUNK_SIZE
int joblib.numpy_pickle_compat._CHUNK_SIZE = 64 * 1024 protected
Definition at line 29 of file numpy_pickle_compat.py.
_MAX_LEN
joblib.numpy_pickle_compat._MAX_LEN = len(hex_str(2**64)) protected
Definition at line 28 of file numpy_pickle_compat.py.