Code Cloning Analysis: fontTools.cu2qu.ufo.GetSegmentsPen Class Reference
fontTools.cu2qu.ufo.GetSegmentsPen Class Reference
Public Member Functions
__init__ (self)
moveTo (self, pt)
lineTo (self, pt)
qCurveTo (self, *points)
curveTo (self, *points)
closePath (self)
endPath (self)
addComponent (self, glyphName, transformation)
Public Member Functions inherited from fontTools.pens.basePen.AbstractPen
None addVarComponent (self, str glyphName, DecomposedTransform transformation, Dict[str, float] location)
Public Attributes
list segments = []
Protected Member Functions
_add_segment (self, tag, *args)
Protected Attributes
_last_pt = None
Detailed Description
Pen to collect segments into lists of points for conversion.
Curves always include their initial on-curve point, so some points are
duplicated between segments.
Definition at line 65 of file ufo.py.
Constructor & Destructor Documentation
__init__()
fontTools.cu2qu.ufo.GetSegmentsPen.__init__ (self)
Definition at line 72 of file ufo.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_add_segment()
fontTools.cu2qu.ufo.GetSegmentsPen._add_segment (self, tag, * args) protected
Definition at line 76 of file ufo.py.
Referenced by closePath(), curveTo(), endPath(), lineTo(), moveTo(), and qCurveTo().
addComponent()
fontTools.cu2qu.ufo.GetSegmentsPen.addComponent (self, glyphName, transformation)
Add a sub glyph. The 'transformation' argument must be a 6-tuple
containing an affine transformation, or a Transform object from the
fontTools.misc.transform module. More precisely: it should be a
sequence containing 6 numbers.
Reimplemented from fontTools.pens.basePen.AbstractPen.
Definition at line 99 of file ufo.py.
closePath()
fontTools.cu2qu.ufo.GetSegmentsPen.closePath (self)
Close the current sub path. You must call either pen.closePath()
or pen.endPath() after each sub path.
Reimplemented from fontTools.pens.basePen.AbstractPen.
Definition at line 93 of file ufo.py.
References _add_segment().
Referenced by fontTools.pens.ttGlyphPen.TTGlyphPen.endPath(), fontTools.pens.pointInsidePen.PointInsidePen.getResult(), and fontTools.pens.pointInsidePen.PointInsidePen.setTestPoint().
curveTo()
fontTools.cu2qu.ufo.GetSegmentsPen.curveTo (self, * points)
Draw a cubic bezier with an arbitrary number of control points.
The last point specified is on-curve, all others are off-curve
(control) points. If the number of control points is > 2, the
segment is split into multiple bezier segments. This works
like this:
Let n be the number of control points (which is the number of
arguments to this call minus 1). If n==2, a plain vanilla cubic
bezier is drawn. If n==1, we fall back to a quadratic segment and
if n==0 we draw a straight line. It gets interesting when n>2:
n-1 PostScript-style cubic segments will be drawn as if it were
one curve. See decomposeSuperBezierSegment().
The conversion algorithm used for n>2 is inspired by NURB
splines, and is conceptually equivalent to the TrueType "implied
points" principle. See also decomposeQuadraticSegment().
Reimplemented from fontTools.pens.basePen.AbstractPen.
Definition at line 90 of file ufo.py.
References _add_segment(), and _last_pt.
endPath()
fontTools.cu2qu.ufo.GetSegmentsPen.endPath (self)
End the current sub path, but don't close it. You must call
either pen.closePath() or pen.endPath() after each sub path.
Reimplemented from fontTools.pens.basePen.AbstractPen.
Definition at line 96 of file ufo.py.
References _add_segment().
lineTo()
fontTools.cu2qu.ufo.GetSegmentsPen.lineTo (self, pt)
Draw a straight line from the current point to 'pt'.
Reimplemented from fontTools.pens.basePen.AbstractPen.
Definition at line 84 of file ufo.py.
References _add_segment().
Referenced by fontTools.pens.basePen.BasePen.curveTo(), fontTools.pens.pointInsidePen.PointInsidePen.getResult(), and fontTools.pens.basePen.BasePen.qCurveTo().
moveTo()
fontTools.cu2qu.ufo.GetSegmentsPen.moveTo (self, pt)
Begin a new sub path, set the current point to 'pt'. You must
end each sub path with a call to pen.closePath() or pen.endPath().
Reimplemented from fontTools.pens.basePen.AbstractPen.
Definition at line 81 of file ufo.py.
References _add_segment().
qCurveTo()
fontTools.cu2qu.ufo.GetSegmentsPen.qCurveTo (self, * points)
Draw a whole string of quadratic curve segments.
The last point specified is on-curve, all others are off-curve
points.
This method implements TrueType-style curves, breaking up curves
using 'implied points': between each two consequtive off-curve points,
there is one implied point exactly in the middle between them. See
also decomposeQuadraticSegment().
The last argument (normally the on-curve point) may be None.
This is to support contours that have NO on-curve points (a rarely
seen feature of TrueType outlines).
Reimplemented from fontTools.pens.basePen.AbstractPen.
Definition at line 87 of file ufo.py.
References _add_segment(), and _last_pt.
Referenced by fontTools.pens.basePen.BasePen.curveTo(), and fontTools.pens.cu2quPen.Cu2QuPen.curveTo().
Member Data Documentation
_last_pt
fontTools.cu2qu.ufo.GetSegmentsPen._last_pt = None protected
Definition at line 73 of file ufo.py.
Referenced by curveTo(), and qCurveTo().
segments
list fontTools.cu2qu.ufo.GetSegmentsPen.segments = []
Definition at line 74 of file ufo.py.
Referenced by fontTools.ttLib.tables._a_v_a_r.table__a_v_a_r.compile(), and fontTools.ttLib.tables._a_v_a_r.table__a_v_a_r.decompile().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/cu2qu/ufo.py