Code Cloning Analysis: numpy._typing._add_docstring Namespace Reference
numpy._typing._add_docstring Namespace Reference
Functions
None add_newdoc (str name, str value, str doc)
str _parse_docstrings ()
Variables
list _docstrings_list = []
str _docstrings = _parse_docstrings()
Detailed Description
A module for creating docstrings for sphinx ``data`` domains.
Function Documentation
_parse_docstrings()
str numpy._typing._add_docstring._parse_docstrings () protected
Convert all docstrings in ``_docstrings_list`` into a single
sphinx-legible text block.
Definition at line 27 of file _add_docstring.py.
References _parse_docstrings(), and add_newdoc().
Referenced by _parse_docstrings().
add_newdoc()
None numpy._typing._add_docstring.add_newdoc (str name, str value, str doc)
Append ``_docstrings_list`` with a docstring for `name`.
Parameters
----------
name : str
    The name of the object.
value : str
    A string-representation of the object.
doc : str
    The docstring of the object.
Definition at line 11 of file _add_docstring.py.
Referenced by _parse_docstrings().
Variable Documentation
_docstrings
str numpy._typing._add_docstring._docstrings = _parse_docstrings() protected
Definition at line 152 of file _add_docstring.py.
_docstrings_list
list numpy._typing._add_docstring._docstrings_list = [] protected
Definition at line 8 of file _add_docstring.py.