Code Cloning Analysis: scipy.integrate._ode.complex_ode Class Reference
scipy.integrate._ode.complex_ode Class Reference
Public Member Functions
__init__ (self, f, jac=None)
y (self)
set_integrator (self, name, **integrator_params)
set_initial_value (self, y, t=0.0)
integrate (self, t, step=False, relax=False)
set_solout (self, solout)
Public Member Functions inherited from scipy.integrate._ode.ode
__init__ (self, f, jac=None)
successful (self)
get_return_code (self)
set_f_params (self, *args)
set_jac_params (self, *args)
Public Attributes
cf = f
cjac = jac
tmp = zeros(y.size * 2, 'float')
Public Attributes inherited from scipy.integrate._ode.ode
int stiff = 0
f = f
jac = jac
tuple f_params = ()
tuple jac_params = ()
float t = t
Protected Member Functions
_wrap (self, t, y, *f_args)
_wrap_jac (self, t, y, *jac_args)
Protected Attributes
_wrap
_wrap_jac
Protected Attributes inherited from scipy.integrate._ode.ode
list _y = []
_integrator = integrator(**integrator_params)
Detailed Description
A wrapper of ode for complex systems.
This functions similarly as `ode`, but re-maps a complex-valued
equation system to a real-valued one before using the integrators.
Parameters
----------
f : callable ``f(t, y, *f_args)``
    Rhs of the equation. t is a scalar, ``y.shape == (n,)``.
    ``f_args`` is set by calling ``set_f_params(*args)``.
jac : callable ``jac(t, y, *jac_args)``
    Jacobian of the rhs, ``jac[i,j] = d f[i] / d y[j]``.
    ``jac_args`` is set by calling ``set_f_params(*args)``.
Attributes
----------
t : float
    Current time.
y : ndarray
    Current variable values.
Examples
--------
For usage examples, see `ode`.
Definition at line 593 of file _ode.py.
Constructor & Destructor Documentation
__init__()
scipy.integrate._ode.complex_ode.__init__ (self, f, jac = None)
Definition at line 622 of file _ode.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
_wrap()
scipy.integrate._ode.complex_ode._wrap (self, t, y, * f_args) protected
Definition at line 630 of file _ode.py.
_wrap_jac()
scipy.integrate._ode.complex_ode._wrap_jac (self, t, y, * jac_args) protected
Definition at line 638 of file _ode.py.
integrate()
scipy.integrate._ode.complex_ode.integrate (self, t, step = False, relax = False)
Find y=y(t), set y as an initial condition, and return y.
Parameters
----------
t : float
    The endpoint of the integration step.
step : bool
    If True, and if the integrator supports the step method,
    then perform a single integration step and return.
    This parameter is provided in order to expose internals of
    the implementation, and should not be changed from its default
    value in most cases.
relax : bool
    If True and if the integrator supports the run_relax method,
    then integrate until t_1 >= t and return. ``relax`` is not
    referenced if ``step=True``.
    This parameter is provided in order to expose internals of
    the implementation, and should not be changed from its default
    value in most cases.
Returns
-------
y : float
    The integrated value at t
Reimplemented from scipy.integrate._ode.ode.
Definition at line 699 of file _ode.py.
set_initial_value()
scipy.integrate._ode.complex_ode.set_initial_value (self, y, t = 0.0)
Set initial conditions y(t) = y.
Reimplemented from scipy.integrate._ode.ode.
Definition at line 691 of file _ode.py.
References tmp.
set_integrator()
scipy.integrate._ode.complex_ode.set_integrator (self, name, ** integrator_params)
Set integrator by name.
Parameters
----------
name : str
    Name of the integrator
**integrator_params
    Additional parameters for the integrator.
Reimplemented from scipy.integrate._ode.ode.
Definition at line 665 of file _ode.py.
set_solout()
scipy.integrate._ode.complex_ode.set_solout (self, solout)
Set callable to be called at every successful integration step.
Parameters
----------
solout : callable
    ``solout(t, y)`` is called at each internal integrator step,
    t is a scalar providing the current independent position
    y is the current soloution ``y.shape == (n,)``
    solout should return -1 to stop integration
    otherwise it should return None or 0
Reimplemented from scipy.integrate._ode.ode.
Definition at line 728 of file _ode.py.
References scipy.integrate._ode.ode._integrator, and set_solout().
Referenced by set_solout().
y()
scipy.integrate._ode.complex_ode.y (self)
Reimplemented from scipy.integrate._ode.ode.
Definition at line 662 of file _ode.py.
Member Data Documentation
_wrap
scipy.integrate._ode.complex_ode._wrap protected
Definition at line 626 of file _ode.py.
_wrap_jac
scipy.integrate._ode.complex_ode._wrap_jac protected
Definition at line 628 of file _ode.py.
cf
scipy.integrate._ode.complex_ode.cf = f
Definition at line 623 of file _ode.py.
cjac
scipy.integrate._ode.complex_ode.cjac = jac
Definition at line 624 of file _ode.py.
tmp
scipy.integrate._ode.complex_ode.tmp = zeros(y.size * 2, 'float')
Definition at line 694 of file _ode.py.
Referenced by set_initial_value().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/integrate/_ode.py