Code Cloning Analysis: fontTools.varLib.stat Namespace Reference
fontTools.varLib.stat Namespace Reference
Functions
None buildVFStatTable (TTFont ttFont, DesignSpaceDocument doc, str vfName)
List[Dict] getStatAxes (DesignSpaceDocument doc, Region userRegion)
List[Dict] getStatLocations (DesignSpaceDocument doc, Region userRegion)
int _labelToFlags (Union[AxisLabelDescriptor, LocationLabelDescriptor] label)
Dict _axisLabelToStatLocation (AxisLabelDescriptor label)
Detailed Description
Extra methods for DesignSpaceDocument to generate its STAT table data.
Function Documentation
_axisLabelToStatLocation()
Dict fontTools.varLib.stat._axisLabelToStatLocation (AxisLabelDescriptor label) protected
Definition at line 123 of file stat.py.
_labelToFlags()
int fontTools.varLib.stat._labelToFlags (Union[AxisLabelDescriptor, LocationLabelDescriptor] label) protected
Definition at line 114 of file stat.py.
buildVFStatTable()
None fontTools.varLib.stat.buildVFStatTable (TTFont ttFont, DesignSpaceDocument doc, str vfName)
Build the STAT table for the variable font identified by its name in
the given document.
Knowing which variable we're building STAT data for is needed to subset
the STAT locations to only include what the variable font actually ships.
.. versionadded:: 5.0
.. seealso::
    - :func:`getStatAxes()`
    - :func:`getStatLocations()`
    - :func:`fontTools.otlLib.builder.buildStatTable()`
Definition at line 18 of file stat.py.
References fontTools.otlLib.builder.buildStatTable(), getStatAxes(), and getStatLocations().
getStatAxes()
List[Dict] fontTools.varLib.stat.getStatAxes (DesignSpaceDocument doc, Region userRegion)
Return a list of axis dicts suitable for use as the ``axes``
argument to :func:`fontTools.otlLib.builder.buildStatTable()`.
.. versionadded:: 5.0
Definition at line 57 of file stat.py.
Referenced by buildVFStatTable().
getStatLocations()
List[Dict] fontTools.varLib.stat.getStatLocations (DesignSpaceDocument doc, Region userRegion)
Return a list of location dicts suitable for use as the ``locations``
argument to :func:`fontTools.otlLib.builder.buildStatTable()`.
.. versionadded:: 5.0
Definition at line 91 of file stat.py.
Referenced by buildVFStatTable().