Code Cloning Analysis: scipy.stats._covariance.CovViaPSD Class Reference
scipy.stats._covariance.CovViaPSD Class Reference
Public Member Functions
__init__ (self, psd)
Public Member Functions inherited from scipy.stats._covariance.Covariance
__init__ (self)
whiten (self, x)
colorize (self, x)
log_pdet (self)
rank (self)
covariance (self)
shape (self)
Protected Member Functions
_whiten (self, x)
_support_mask (self, x)
Protected Member Functions inherited from scipy.stats._covariance.Covariance
_validate_matrix (self, A, name)
_validate_vector (self, A, name)
Protected Attributes
_LP = psd.U
_covariance = psd._M
_shape = psd._M.shape
_psd = psd
bool _allow_singular = False
Protected Attributes inherited from scipy.stats._covariance.Covariance
_log_pdet
_rank
Additional Inherited Members
Static Public Member Functions inherited from scipy.stats._covariance.Covariance
from_diagonal (diagonal)
from_precision (precision, covariance=None)
from_cholesky (cholesky)
from_eigendecomposition (eigendecomposition)
Detailed Description
Representation of a covariance provided via an instance of _PSD
Definition at line 612 of file _covariance.py.
Constructor & Destructor Documentation
__init__()
scipy.stats._covariance.CovViaPSD.__init__ (self, psd)
Definition at line 617 of file _covariance.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
_support_mask()
scipy.stats._covariance.CovViaPSD._support_mask (self, x) protected
Definition at line 629 of file _covariance.py.
Referenced by scipy.stats._distn_infrastructure.rv_continuous._nnlf_and_penalty(), scipy.stats._distn_infrastructure.rv_continuous.logpdf(), scipy.stats._distn_infrastructure.rv_generic.nnlf(), and scipy.stats._distn_infrastructure.rv_continuous.pdf().
_whiten()
scipy.stats._covariance.CovViaPSD._whiten (self, x) protected
Definition at line 626 of file _covariance.py.
Referenced by scipy.stats._covariance.Covariance.whiten().
Member Data Documentation
_allow_singular
bool scipy.stats._covariance.CovViaPSD._allow_singular = False protected
Definition at line 624 of file _covariance.py.
_covariance
scipy.stats._covariance.CovViaPSD._covariance = psd._M protected
Definition at line 621 of file _covariance.py.
Referenced by scipy.stats._covariance.Covariance.covariance().
_LP
scipy.stats._covariance.CovViaPSD._LP = psd.U protected
Definition at line 618 of file _covariance.py.
_psd
scipy.stats._covariance.CovViaPSD._psd = psd protected
Definition at line 623 of file _covariance.py.
_shape
scipy.stats._covariance.CovViaPSD._shape = psd._M.shape protected
Definition at line 622 of file _covariance.py.
Referenced by pandas.util._doctools.TablePlotter._get_cells(), scipy.sparse._matrix.spmatrix.get_shape(), pandas.util._doctools.TablePlotter.plot(), and scipy.stats._covariance.Covariance.shape().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/stats/_covariance.py