Code Cloning Analysis: matplotlib.lines Namespace Reference
matplotlib.lines Namespace Reference
Classes
class AxLine
class Line2D
class VertexSelector
Functions
_get_dash_pattern (style)
_get_dash_patterns (styles)
_get_inverse_dash_pattern (offset, dashes)
_scale_dashes (offset, dashes, lw)
segment_hits (cx, cy, x, y, radius)
_mark_every_path (markevery, tpath, affine, ax)
Variables
_log = logging.getLogger(__name__)
lineStyles = Line2D._lineStyles
lineMarkers = MarkerStyle.markers
drawStyles = Line2D.drawStyles
fillStyles = MarkerStyle.fillstyles
Detailed Description
2D lines with support for a variety of line styles, markers, colors, etc.
Function Documentation
_get_dash_pattern()
matplotlib.lines._get_dash_pattern (style) protected
Convert linestyle to dash pattern.
Definition at line 33 of file lines.py.
Referenced by _get_dash_patterns(), and matplotlib.lines.Line2D.set_linestyle().
_get_dash_patterns()
matplotlib.lines._get_dash_patterns (styles) protected
Convert linestyle or sequence of linestyles to list of dash patterns.
Definition at line 63 of file lines.py.
References _get_dash_pattern().
_get_inverse_dash_pattern()
matplotlib.lines._get_inverse_dash_pattern (offset, dashes) protected
Return the inverse of the given dash pattern, for filling the gaps.
Definition at line 77 of file lines.py.
Referenced by matplotlib.lines.Line2D._get_transformed_path().
_mark_every_path()
matplotlib.lines._mark_every_path (markevery, tpath, affine, ax) protected
Helper function that sorts out how to deal the input
`markevery` and returns the points where markers should be drawn.
Takes in the `markevery` value and the line path and returns the
sub-sampled path.
Definition at line 135 of file lines.py.
Referenced by matplotlib.lines.Line2D._get_transformed_path().
_scale_dashes()
matplotlib.lines._scale_dashes (offset, dashes, lw) protected
Definition at line 89 of file lines.py.
segment_hits()
matplotlib.lines.segment_hits (cx, cy, x, y, radius)
Return the indices of the segments in the polyline with coordinates (*cx*,
*cy*) that are within a distance *radius* of the point (*x*, *y*).
Definition at line 98 of file lines.py.
Referenced by matplotlib.lines.Line2D.contains().
Variable Documentation
_log
matplotlib.lines._log = logging.getLogger(__name__) protected
Definition at line 30 of file lines.py.
drawStyles
matplotlib.lines.drawStyles = Line2D.drawStyles
Definition at line 1719 of file lines.py.
fillStyles
matplotlib.lines.fillStyles = MarkerStyle.fillstyles
Definition at line 1720 of file lines.py.
lineMarkers
matplotlib.lines.lineMarkers = MarkerStyle.markers
Definition at line 1718 of file lines.py.
lineStyles
matplotlib.lines.lineStyles = Line2D._lineStyles
Definition at line 1717 of file lines.py.