Code Cloning Analysis: pip._vendor.chardet.charsetprober.CharSetProber Class Reference
pip._vendor.chardet.charsetprober.CharSetProber Class Reference
Public Member Functions
None __init__ (self, LanguageFilter lang_filter=LanguageFilter.NONE)
None reset (self)
Optional[str] charset_name (self)
Optional[str] language (self)
ProbingState feed (self, Union[bytes, bytearray] byte_str)
ProbingState state (self)
float get_confidence (self)
Static Public Member Functions
bytes filter_high_byte_only (Union[bytes, bytearray] buf)
bytearray filter_international_words (Union[bytes, bytearray] buf)
bytes remove_xml_tags (Union[bytes, bytearray] buf)
Public Attributes
bool active = True
lang_filter = lang_filter
logger = logging.getLogger(__name__)
Static Public Attributes
float SHORTCUT_THRESHOLD = 0.95
Protected Attributes
_state = ProbingState.DETECTING
Detailed Description
Definition at line 40 of file charsetprober.py.
Constructor & Destructor Documentation
__init__()
None pip._vendor.chardet.charsetprober.CharSetProber.__init__ (self, LanguageFilter lang_filter = LanguageFilter.NONE)
Definition at line 44 of file charsetprober.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
charset_name()
Optional[str] pip._vendor.chardet.charsetprober.CharSetProber.charset_name (self)
Definition at line 54 of file charsetprober.py.
feed()
ProbingState pip._vendor.chardet.charsetprober.CharSetProber.feed (self, Union[bytes, bytearray] byte_str)
Definition at line 61 of file charsetprober.py.
filter_high_byte_only()
bytes pip._vendor.chardet.charsetprober.CharSetProber.filter_high_byte_only (Union[bytes, bytearray] buf) static
Definition at line 72 of file charsetprober.py.
filter_international_words()
bytearray pip._vendor.chardet.charsetprober.CharSetProber.filter_international_words (Union[bytes, bytearray] buf) static
We define three types of bytes:
alphabet: english alphabets [a-zA-Z]
international: international characters [\x80-\xFF]
marker: everything else [^a-zA-Z\x80-\xFF]
The input buffer can be thought to contain a series of words delimited
by markers. This function works to filter all words that contain at
least one international character. All contiguous sequences of markers
are replaced by a single space ascii character.
This filter applies to all scripts which do not use English characters.
Definition at line 77 of file charsetprober.py.
get_confidence()
float pip._vendor.chardet.charsetprober.CharSetProber.get_confidence (self)
Definition at line 68 of file charsetprober.py.
Referenced by pip._vendor.chardet.utf1632prober.UTF1632Prober.validate_utf16_characters().
language()
Optional[str] pip._vendor.chardet.charsetprober.CharSetProber.language (self)
Definition at line 58 of file charsetprober.py.
remove_xml_tags()
bytes pip._vendor.chardet.charsetprober.CharSetProber.remove_xml_tags (Union[bytes, bytearray] buf) static
Returns a copy of ``buf`` that retains only the sequences of English
alphabet and high byte characters that are not between <> characters.
This filter can be applied to all scripts which contain both English
characters and extended ASCII characters, but is currently only used by
``Latin1Prober``.
Definition at line 111 of file charsetprober.py.
reset()
None pip._vendor.chardet.charsetprober.CharSetProber.reset (self)
Definition at line 50 of file charsetprober.py.
Referenced by scipy._lib._docscrape.Reader.__init__().
state()
ProbingState pip._vendor.chardet.charsetprober.CharSetProber.state (self)
Definition at line 65 of file charsetprober.py.
Referenced by pip._vendor.resolvelib.resolvers.Resolution._backjump(), pip._vendor.resolvelib.resolvers.Resolution._remove_information_from_criteria(), and pip._vendor.chardet.utf1632prober.UTF1632Prober.validate_utf16_characters().
Member Data Documentation
_state
pip._vendor.chardet.charsetprober.CharSetProber._state = ProbingState.DETECTING protected
Definition at line 45 of file charsetprober.py.
Referenced by pip._vendor.chardet.utf1632prober.UTF1632Prober.validate_utf16_characters().
active
bool pip._vendor.chardet.charsetprober.CharSetProber.active = True
Definition at line 46 of file charsetprober.py.
lang_filter
pip._vendor.chardet.charsetprober.CharSetProber.lang_filter = lang_filter
Definition at line 47 of file charsetprober.py.
Referenced by pip._vendor.chardet.universaldetector.UniversalDetector.feed().
logger
pip._vendor.chardet.charsetprober.CharSetProber.logger = logging.getLogger(__name__)
Definition at line 48 of file charsetprober.py.
Referenced by pip._vendor.chardet.universaldetector.UniversalDetector.close().
SHORTCUT_THRESHOLD
float pip._vendor.chardet.charsetprober.CharSetProber.SHORTCUT_THRESHOLD = 0.95 static
Definition at line 42 of file charsetprober.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pip/_vendor/chardet/charsetprober.py