Code Cloning Analysis: numpy.f2py._backends._meson.MesonTemplate Class Reference
numpy.f2py._backends._meson.MesonTemplate Class Reference
Public Member Functions
__init__ (self, str modulename, list[Path] sources, list[str] deps, list[str] libraries, list[Path] library_dirs, list[Path] include_dirs, list[Path] object_files, list[str] linker_args, list[str] c_args, str build_type, str python_exe)
str meson_build_template (self)
None initialize_template (self)
None sources_substitution (self)
None deps_substitution (self)
None libraries_substitution (self)
None include_substitution (self)
generate_meson_build (self)
Public Attributes
modulename = modulename
tuple build_template_path
sources = sources
deps = deps
libraries = libraries
library_dirs = library_dirs
list include_dirs = include_dirs
dict substitutions = {}
objects = object_files
list pipeline
build_type = build_type
python_exe = python_exe
Detailed Description
Template meson build file generation class.
Definition at line 17 of file _meson.py.
Constructor & Destructor Documentation
__init__()
numpy.f2py._backends._meson.MesonTemplate.__init__ (self, str modulename, list[Path] sources, list[str] deps, list[str] libraries, list[Path] library_dirs, list[Path] include_dirs, list[Path] object_files, list[str] linker_args, list[str] c_args, str build_type, str python_exe)
Definition at line 20 of file _meson.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
deps_substitution()
None numpy.f2py._backends._meson.MesonTemplate.deps_substitution (self)
Definition at line 79 of file _meson.py.
generate_meson_build()
numpy.f2py._backends._meson.MesonTemplate.generate_meson_build (self)
Definition at line 114 of file _meson.py.
include_substitution()
None numpy.f2py._backends._meson.MesonTemplate.include_substitution (self)
Definition at line 108 of file _meson.py.
initialize_template()
None numpy.f2py._backends._meson.MesonTemplate.initialize_template (self)
Definition at line 68 of file _meson.py.
libraries_substitution()
None numpy.f2py._backends._meson.MesonTemplate.libraries_substitution (self)
Definition at line 85 of file _meson.py.
meson_build_template()
str numpy.f2py._backends._meson.MesonTemplate.meson_build_template (self)
Definition at line 58 of file _meson.py.
sources_substitution()
None numpy.f2py._backends._meson.MesonTemplate.sources_substitution (self)
Definition at line 73 of file _meson.py.
Member Data Documentation
build_template_path
tuple numpy.f2py._backends._meson.MesonTemplate.build_template_path
Initial value:
=  (
            Path(__file__).parent.absolute() / "meson.build.template"
        )
Definition at line 35 of file _meson.py.
build_type
numpy.f2py._backends._meson.MesonTemplate.build_type = build_type
Definition at line 55 of file _meson.py.
Referenced by numpy.f2py._backends._meson.MesonBackend.write_meson_build().
deps
numpy.f2py._backends._meson.MesonTemplate.deps = deps
Definition at line 39 of file _meson.py.
include_dirs
list numpy.f2py._backends._meson.MesonTemplate.include_dirs = include_dirs
Definition at line 43 of file _meson.py.
libraries
numpy.f2py._backends._meson.MesonTemplate.libraries = libraries
Definition at line 40 of file _meson.py.
library_dirs
numpy.f2py._backends._meson.MesonTemplate.library_dirs = library_dirs
Definition at line 41 of file _meson.py.
modulename
numpy.f2py._backends._meson.MesonTemplate.modulename = modulename
Definition at line 34 of file _meson.py.
objects
numpy.f2py._backends._meson.MesonTemplate.objects = object_files
Definition at line 47 of file _meson.py.
pipeline
list numpy.f2py._backends._meson.MesonTemplate.pipeline
Initial value:
=  [
            self.initialize_template,
            self.sources_substitution,
            self.deps_substitution,
            self.include_substitution,
            self.libraries_substitution,
        ]
Definition at line 48 of file _meson.py.
python_exe
numpy.f2py._backends._meson.MesonTemplate.python_exe = python_exe
Definition at line 56 of file _meson.py.
sources
numpy.f2py._backends._meson.MesonTemplate.sources = sources
Definition at line 38 of file _meson.py.
substitutions
numpy.f2py._backends._meson.MesonTemplate.substitutions = {}
Definition at line 46 of file _meson.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/f2py/_backends/_meson.py