Code Cloning Analysis: pandas.io.formats.style Namespace Reference
pandas.io.formats.style Namespace Reference
Classes
class Styler
Functions
Generator[tuple[Any, Any], None, None] _mpl (Callable func)
np.ndarray _validate_apply_axis_arg (NDFrame|Sequence|np.ndarray arg, str arg_name, Any|None dtype, NDFrame data)
_background_gradient (data, str|Colormap cmap="PuBu", float low=0, float high=0, float text_color_threshold=0.408, float|None vmin=None, float|None vmax=None, Sequence|np.ndarray|DataFrame|Series|None gmap=None, bool text_only=False)
np.ndarray _highlight_between (NDFrame data, str props, Scalar|Sequence|np.ndarray|NDFrame|None left=None, Scalar|Sequence|np.ndarray|NDFrame|None right=None, bool|str inclusive=True)
np.ndarray _highlight_value (DataFrame|Series data, str op, str props)
_bar (NDFrame data, str|float|Callable align, str|list|tuple colors, Any cmap, float width, float height, float|None vmin, float|None vmax, str base_css)
Variables
jinja2 = import_optional_dependency("jinja2", extra="DataFrame.style requires jinja2.")
bool has_mpl = True
str subset_args
Shared Doc Strings.
str properties_args
str coloring_args
str buffering_args
str encoding_args
Detailed Description
Module for applying conditional formatting to DataFrames and Series.
Function Documentation
_background_gradient()
pandas.io.formats.style._background_gradient (data, str | Colormap cmap = "PuBu", float low = 0, float high = 0, float text_color_threshold = 0.408, float | None vmin = None, float | None vmax = None, Sequence | np.ndarray | DataFrame | Series | None gmap = None, bool text_only = False) protected
Color background in a range according to the data or a gradient map
Definition at line 3787 of file style.py.
References _validate_apply_axis_arg().
_bar()
pandas.io.formats.style._bar (NDFrame data, str | float | Callable align, str | list | tuple colors, Any cmap, float width, float height, float | None vmin, float | None vmax, str base_css) protected
Draw bar chart in data cells using HTML CSS linear gradient.
Parameters
----------
data : Series or DataFrame
    Underling subset of Styler data on which operations are performed.
align : str in {"left", "right", "mid", "zero", "mean"}, int, float, callable
    Method for how bars are structured or scalar value of centre point.
colors : list-like of str
    Two listed colors as string in valid CSS.
width : float in [0,1]
    The percentage of the cell, measured from left, where drawn bars will reside.
height : float in [0,1]
    The percentage of the cell's height where drawn bars will reside, centrally
    aligned.
vmin : float, optional
    Overwrite the minimum value of the window.
vmax : float, optional
    Overwrite the maximum value of the window.
base_css : str
    Additional CSS that is included in the cell before bars are drawn.
Definition at line 3931 of file style.py.
_highlight_between()
np.ndarray pandas.io.formats.style._highlight_between (NDFrame data, str props, Scalar | Sequence | np.ndarray | NDFrame | None left = None, Scalar | Sequence | np.ndarray | NDFrame | None right = None, bool | str inclusive = True) protected
Return an array of css props based on condition of data values within given range.
Definition at line 3863 of file style.py.
References _validate_apply_axis_arg().
_highlight_value()
np.ndarray pandas.io.formats.style._highlight_value (DataFrame | Series data, str op, str props) protected
Return an array of css strings based on the condition of values matching an op.
Definition at line 3919 of file style.py.
_mpl()
Generator[tuple[Any, Any], None, None] pandas.io.formats.style._mpl (Callable func) protected
Definition at line 94 of file style.py.
_validate_apply_axis_arg()
np.ndarray pandas.io.formats.style._validate_apply_axis_arg (NDFrame | Sequence | np.ndarray arg, str arg_name, Any | None dtype, NDFrame data) protected
For the apply-type methods, ``axis=None`` creates ``data`` as DataFrame, and for
``axis=[1,0]`` it creates a Series. Where ``arg`` is expected as an element
of some operator with ``data`` we must make sure that the two are compatible shapes,
or raise.
Parameters
----------
arg : sequence, Series or DataFrame
    the user input arg
arg_name : string
    name of the arg for use in error messages
dtype : numpy dtype, optional
    forced numpy dtype if given
data : Series or DataFrame
    underling subset of Styler data on which operations are performed
Returns
-------
ndarray
Definition at line 3734 of file style.py.
Referenced by _background_gradient(), and _highlight_between().
Variable Documentation
buffering_args
str pandas.io.formats.style.buffering_args
Initial value:
=  """buf : str, path object, file-like object, optional
         String, path object (implementing ``os.PathLike[str]``), or file-like
         object implementing a string ``write()`` function. If ``None``, the result is
         returned as a string."""
Definition at line 116 of file style.py.
coloring_args
str pandas.io.formats.style.coloring_args
Initial value:
=  """color : str, default '{default}'
           Background color to use for highlighting."""
Definition at line 113 of file style.py.
encoding_args
str pandas.io.formats.style.encoding_args
Initial value:
=  """encoding : str, optional
              Character encoding setting for file output (and meta tags if available).
              Defaults to ``pandas.options.styler.render.encoding`` value of "utf-8"."""
Definition at line 121 of file style.py.
has_mpl
bool pandas.io.formats.style.has_mpl = True
Definition at line 88 of file style.py.
jinja2
pandas.io.formats.style.jinja2 = import_optional_dependency("jinja2", extra="DataFrame.style requires jinja2.")
Definition at line 44 of file style.py.
properties_args
str pandas.io.formats.style.properties_args
Initial value:
=  """props : str, default None
           CSS properties to use for highlighting. If ``props`` is given, ``color``
           is not used."""
Definition at line 109 of file style.py.
subset_args
str pandas.io.formats.style.subset_args
Initial value:
=  """subset : label, array-like, IndexSlice, optional
            A valid 2d input to `DataFrame.loc[<subset>]`, or, in the case of a 1d input
            or single key, to `DataFrame.loc[:, <subset>]` where the columns are
            prioritised, to limit ``data`` to *before* applying the function."""
Shared Doc Strings.
Definition at line 104 of file style.py.