Code Cloning Analysis: fontTools.designspaceLib.statNames Namespace Reference
fontTools.designspaceLib.statNames Namespace Reference
Classes
class StatNames
Functions
StatNames getStatNames (DesignSpaceDocument doc, SimpleLocationDict userLocation)
Dict[str, list[AxisLabelDescriptor]] _getSortedAxisLabels (list[Union[AxisDescriptor, DiscreteAxisDescriptor]] axes)
list[AxisLabelDescriptor] _getAxisLabelsForUserLocation (list[Union[AxisDescriptor, DiscreteAxisDescriptor]] axes, SimpleLocationDict userLocation)
Tuple[RibbiStyleName, SimpleLocationDict] _getRibbiStyle (DesignSpaceDocument self, SimpleLocationDict userLocation)
Variables
LOGGER = logging.getLogger(__name__)
RibbiStyleName
dict BOLD_ITALIC_TO_RIBBI_STYLE
Detailed Description
Compute name information for a given location in user-space coordinates
using STAT data. This can be used to fill-in automatically the names of an
instance:
.. code:: python
    instance = doc.instances[0]
    names = getStatNames(doc, instance.getFullUserLocation(doc))
    print(names.styleNames)
Function Documentation
_getAxisLabelsForUserLocation()
list[AxisLabelDescriptor] fontTools.designspaceLib.statNames._getAxisLabelsForUserLocation (list[Union[AxisDescriptor, DiscreteAxisDescriptor]] axes, SimpleLocationDict userLocation) protected
Definition at line 171 of file statNames.py.
_getRibbiStyle()
Tuple[RibbiStyleName, SimpleLocationDict] fontTools.designspaceLib.statNames._getRibbiStyle (DesignSpaceDocument self, SimpleLocationDict userLocation) protected
Compute the RIBBI style name of the given user location,
return the location of the matching Regular in the RIBBI group.
.. versionadded:: 5.0
Definition at line 209 of file statNames.py.
Referenced by getStatNames().
_getSortedAxisLabels()
Dict[str, list[AxisLabelDescriptor]] fontTools.designspaceLib.statNames._getSortedAxisLabels (list[Union[AxisDescriptor, DiscreteAxisDescriptor]] axes) protected
Returns axis labels sorted by their ordering, with unordered ones appended as
they are listed.
Definition at line 147 of file statNames.py.
References _getSortedAxisLabels().
Referenced by _getSortedAxisLabels().
getStatNames()
StatNames fontTools.designspaceLib.statNames.getStatNames (DesignSpaceDocument doc, SimpleLocationDict userLocation)
Compute the family, style, PostScript names of the given ``userLocation``
using the document's STAT information.
Also computes localizations.
If not enough STAT data is available for a given name, either its dict of
localized names will be empty (family and style names), or the name will be
None (PostScript name).
Note: this method does not consider info attached to the instance, like
family name. The user needs to override all names on an instance that STAT
information would compute differently than desired.
.. versionadded:: 5.0
Definition at line 55 of file statNames.py.
References _getRibbiStyle(), and getStatNames().
Referenced by getStatNames().
Variable Documentation
BOLD_ITALIC_TO_RIBBI_STYLE
dict fontTools.designspaceLib.statNames.BOLD_ITALIC_TO_RIBBI_STYLE
Initial value:
=  {
    (False, False): "regular",
    (False, True): "italic",
    (True, False): "bold",
    (True, True): "bold italic",
}
Definition at line 36 of file statNames.py.
LOGGER
fontTools.designspaceLib.statNames.LOGGER = logging.getLogger(__name__)
Definition at line 27 of file statNames.py.
RibbiStyleName
fontTools.designspaceLib.statNames.RibbiStyleName
Initial value:
=  Union[
    Literal["regular"],
    Literal["bold"],
    Literal["italic"],
    Literal["bold italic"],
]
Definition at line 29 of file statNames.py.