Code Cloning Analysis: fontTools.ttLib.tables.D_S_I_G_.table_D_S_I_G_ Class Reference
fontTools.ttLib.tables.D_S_I_G_.table_D_S_I_G_ Class Reference
Public Member Functions
decompile (self, data, ttFont)
compile (self, ttFont)
toXML (self, xmlWriter, ttFont)
fromXML (self, name, attrs, content, ttFont)
Public Member Functions inherited from fontTools.ttLib.tables.DefaultTable.DefaultTable
__init__ (self, tag=None)
__repr__ (self)
__eq__ (self, other)
__ne__ (self, other)
Public Attributes
int ulVersion = 1, "DSIG ulVersion must be 1"
list signatureRecords = []
usNumSigs
usFlag = safeEval(attrs["flag"])
Public Attributes inherited from fontTools.ttLib.tables.DefaultTable.DefaultTable
tableTag = Tag(tag)
data = data
ERROR
Additional Inherited Members
Static Public Attributes inherited from fontTools.ttLib.tables.DefaultTable.DefaultTable
list dependencies = []
Detailed Description
Digital Signature table
The ``DSIG`` table contains cryptographic signatures for the font.
See also https://learn.microsoft.com/en-us/typography/opentype/spec/dsig
Definition at line 41 of file D_S_I_G_.py.
Member Function Documentation
compile()
fontTools.ttLib.tables.D_S_I_G_.table_D_S_I_G_.compile (self, ttFont)
Reimplemented from fontTools.ttLib.tables.DefaultTable.DefaultTable.
Definition at line 74 of file D_S_I_G_.py.
Referenced by fontTools.ttLib.tables.TupleVariation.TupleVariation.getCoordWidth(), and PIL.FontFile.FontFile.save().
decompile()
fontTools.ttLib.tables.D_S_I_G_.table_D_S_I_G_.decompile (self, data, ttFont)
Reimplemented from fontTools.ttLib.tables.DefaultTable.DefaultTable.
Definition at line 49 of file D_S_I_G_.py.
Referenced by fontTools.ttLib.tables._c_m_a_p.CmapSubtable.newSubtable().
fromXML()
fontTools.ttLib.tables.D_S_I_G_.table_D_S_I_G_.fromXML (self, name, attrs, content, ttFont)
Reimplemented from fontTools.ttLib.tables.DefaultTable.DefaultTable.
Definition at line 111 of file D_S_I_G_.py.
toXML()
fontTools.ttLib.tables.D_S_I_G_.table_D_S_I_G_.toXML (self, xmlWriter, ttFont)
Reimplemented from fontTools.ttLib.tables.DefaultTable.DefaultTable.
Definition at line 95 of file D_S_I_G_.py.
Member Data Documentation
signatureRecords
list fontTools.ttLib.tables.D_S_I_G_.table_D_S_I_G_.signatureRecords = []
Definition at line 53 of file D_S_I_G_.py.
ulVersion
int fontTools.ttLib.tables.D_S_I_G_.table_D_S_I_G_.ulVersion = 1, "DSIG ulVersion must be 1"
Definition at line 51 of file D_S_I_G_.py.
usFlag
fontTools.ttLib.tables.D_S_I_G_.table_D_S_I_G_.usFlag = safeEval(attrs["flag"])
Definition at line 116 of file D_S_I_G_.py.
usNumSigs
fontTools.ttLib.tables.D_S_I_G_.table_D_S_I_G_.usNumSigs
Definition at line 54 of file D_S_I_G_.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ttLib/tables/D_S_I_G_.py