Code Cloning Analysis: pip._internal.commands.wheel.WheelCommand Class Reference
pip._internal.commands.wheel.WheelCommand Class Reference
Public Member Functions
None add_options (self)
int run (self, Values options, List[str] args)
Public Member Functions inherited from pip._internal.cli.req_command.RequirementCommand
None __init__ (self, *Any args, **Any kw)
RequirementPreparer make_requirement_preparer (cls, TempDirectory temp_build_dir, Values options, BuildTracker build_tracker, PipSession session, PackageFinder finder, bool use_user_site, Optional[str] download_dir=None, int verbosity=0)
BaseResolver make_resolver (cls, RequirementPreparer preparer, PackageFinder finder, Values options, Optional[WheelCache] wheel_cache=None, bool use_user_site=False, bool ignore_installed=True, bool ignore_requires_python=False, bool force_reinstall=False, str upgrade_strategy="to-satisfy-only", Optional[bool] use_pep517=None, Optional[Tuple[int,...]] py_version_info=None)
List[InstallRequirement] get_requirements (self, List[str] args, Values options, PackageFinder finder, PipSession session)
Public Member Functions inherited from pip._internal.cli.req_command.IndexGroupCommand
None handle_pip_version_check (self, Values options)
Public Member Functions inherited from pip._internal.cli.base_command.Command
None __init__ (self, str name, str summary, bool isolated=False)
Tuple[Values, List[str]] parse_args (self, List[str] args)
int main (self, List[str] args)
Public Member Functions inherited from pip._internal.cli.command_context.CommandContextMixIn
None __init__ (self)
Generator[None, None, None] main_context (self)
_T enter_context (self, ContextManager[_T] context_provider)
Public Member Functions inherited from pip._internal.cli.req_command.SessionCommandMixin
None __init__ (self)
PipSession get_default_session (self, Values options)
Additional Inherited Members
Static Public Member Functions inherited from pip._internal.cli.req_command.RequirementCommand
str determine_resolver_variant (Values options)
None trace_basic_info (PackageFinder finder)
Public Attributes inherited from pip._internal.cli.base_command.Command
name = name
summary = summary
parser
Optional[TempDirRegistry] tempdir_registry = None
cmd_opts = optparse.OptionGroup(self.parser, optgroup_name)
verbosity = options.verbose - options.quiet
Static Public Attributes inherited from pip._internal.cli.base_command.Command
str usage = ""
bool ignore_require_venv = False
Protected Member Functions inherited from pip._internal.cli.req_command.RequirementCommand
PackageFinder _build_package_finder (self, Values options, PipSession session, Optional[TargetPython] target_python=None, Optional[bool] ignore_requires_python=None)
Protected Member Functions inherited from pip._internal.cli.base_command.Command
int _main (self, List[str] args)
Protected Member Functions inherited from pip._internal.cli.req_command.SessionCommandMixin
Optional[List[str]] _get_index_urls (cls, Values options)
PipSession _build_session (self, Values options, Optional[int] retries=None, Optional[int] timeout=None, bool fallback_to_certifi=False)
Protected Attributes inherited from pip._internal.cli.command_context.CommandContextMixIn
bool _in_main_context = False
_main_context = ExitStack()
Protected Attributes inherited from pip._internal.cli.req_command.SessionCommandMixin
Optional[PipSession] _session = None
Detailed Description
Build Wheel archives for your requirements and dependencies.
Wheel is a built-package format, and offers the advantage of not
recompiling your software during every install. For more details, see the
wheel docs: https://wheel.readthedocs.io/en/latest/
'pip wheel' uses the build system interface as described here:
https://pip.pypa.io/en/stable/reference/build-system/
Definition at line 24 of file wheel.py.
Member Function Documentation
add_options()
None pip._internal.commands.wheel.WheelCommand.add_options (self)
Reimplemented from pip._internal.cli.base_command.Command.
Definition at line 44 of file wheel.py.
run()
int pip._internal.commands.wheel.WheelCommand.run (self, Values options, List[str] args)
Reimplemented from pip._internal.cli.base_command.Command.
Definition at line 104 of file wheel.py.
Referenced by scipy.odr._odrpack.ODR.restart(), scipy.integrate._ode.lsoda.run_relax(), scipy.integrate._ode.vode.run_relax(), scipy.integrate._ode.lsoda.step(), and scipy.integrate._ode.vode.step().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pip/_internal/commands/wheel.py