Code Cloning Analysis: pandas.tests.frame.test_subclass.MySubclassWithMetadata Class Reference
pandas.tests.frame.test_subclass.MySubclassWithMetadata Class Reference
Public Member Functions
None __init__ (self, *args, **kwargs)
Public Attributes
my_metadata = my_metadata
Protected Member Functions
_constructor (self)
Static Protected Attributes
list _metadata = ["my_metadata"]
Detailed Description
Definition at line 761 of file test_subclass.py.
Constructor & Destructor Documentation
__init__()
None pandas.tests.frame.test_subclass.MySubclassWithMetadata.__init__ (self, * args, ** kwargs)
Definition at line 764 of file test_subclass.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
_constructor()
pandas.tests.frame.test_subclass.MySubclassWithMetadata._constructor (self) protected
Definition at line 773 of file test_subclass.py.
Referenced by pandas.core.base.IndexOpsMixin._memory_usage().
Member Data Documentation
_metadata
list pandas.tests.frame.test_subclass.MySubclassWithMetadata._metadata = ["my_metadata"] static protected
Definition at line 762 of file test_subclass.py.
Referenced by pip._internal.req.req_install.InstallRequirement.prepare_metadata().
my_metadata
pandas.tests.frame.test_subclass.MySubclassWithMetadata.my_metadata = my_metadata
Definition at line 770 of file test_subclass.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/tests/frame/test_subclass.py