Code Cloning Analysis: scipy.optimize.tests.test_minpack Namespace Reference
scipy.optimize.tests.test_minpack Namespace Reference
Classes
class ReturnShape
class TestCurveFit
class TestFixedPoint
class TestFSolve
class TestLeastSq
class TestRootHybr
class TestRootLM
Functions
dummy_func (x, shape)
sequence_parallel (fs)
pressure_network (flow_rates, Qtot, k)
pressure_network_jacobian (flow_rates, Qtot, k)
pressure_network_fun_and_grad (flow_rates, Qtot, k)
Detailed Description
Unit tests for optimization routines from minpack.py.
Function Documentation
dummy_func()
scipy.optimize.tests.test_minpack.dummy_func (x, shape)
A function that returns an array of ones of the given shape.
`x` is ignored.
Definition at line 36 of file test_minpack.py.
pressure_network()
scipy.optimize.tests.test_minpack.pressure_network (flow_rates, Qtot, k)
Evaluate non-linear equation system representing
the pressures and flows in a system of n parallel pipes::
    f_i = P_i - P_0, for i = 1..n
    f_0 = sum(Q_i) - Qtot
where Q_i is the flow rate in pipe i and P_i the pressure in that pipe.
Pressure is modeled as a P=kQ**2 where k is a valve coefficient and
Q is the flow rate.
Parameters
----------
flow_rates : float
    A 1-D array of n flow rates [kg/s].
k : float
    A 1-D array of n valve coefficients [1/kg m].
Qtot : float
    A scalar, the total input flow rate [kg/s].
Returns
-------
F : float
    A 1-D array, F[i] == f_i.
Definition at line 52 of file test_minpack.py.
Referenced by pressure_network_jacobian().
pressure_network_fun_and_grad()
scipy.optimize.tests.test_minpack.pressure_network_fun_and_grad (flow_rates, Qtot, k)
Definition at line 106 of file test_minpack.py.
pressure_network_jacobian()
scipy.optimize.tests.test_minpack.pressure_network_jacobian (flow_rates, Qtot, k)
Return the jacobian of the equation system F(flow_rates)
computed by `pressure_network` with respect to
*flow_rates*. See `pressure_network` for the detailed
description of parrameters.
Returns
-------
jac : float
    *n* by *n* matrix ``df_i/dQ_i`` where ``n = len(flow_rates)``
    and *f_i* and *Q_i* are described in the doc for `pressure_network`
Definition at line 83 of file test_minpack.py.
References pressure_network(), and pressure_network_jacobian().
Referenced by pressure_network_jacobian().
sequence_parallel()
scipy.optimize.tests.test_minpack.sequence_parallel (fs)
Definition at line 43 of file test_minpack.py.