Code Cloning Analysis: sklearn.preprocessing._data Namespace Reference
sklearn.preprocessing._data Namespace Reference
Classes
class Binarizer
class KernelCenterer
class MaxAbsScaler
class MinMaxScaler
class Normalizer
class PowerTransformer
class QuantileTransformer
class RobustScaler
class StandardScaler
Functions
_is_constant_feature (var, mean, n_samples)
_handle_zeros_in_scale (scale, copy=True, constant_mask=None)
scale (X, *, axis=0, with_mean=True, with_std=True, copy=True)
minmax_scale (X, feature_range=(0, 1), *, axis=0, copy=True)
maxabs_scale (X, *, axis=0, copy=True)
robust_scale (X, *, axis=0, with_centering=True, with_scaling=True, quantile_range=(25.0, 75.0), copy=True, unit_variance=False)
normalize (X, norm="l2", *, axis=1, copy=True, return_norm=False)
binarize (X, *, threshold=0.0, copy=True)
add_dummy_feature (X, value=1.0)
quantile_transform (X, *, axis=0, n_quantiles=1000, output_distribution="uniform", ignore_implicit_zeros=False, subsample=int(1e5), random_state=None, copy=True)
power_transform (X, method="yeo-johnson", *, standardize=True, copy=True)
Variables
int BOUNDS_THRESHOLD = 1e-7
list __all__
Function Documentation
_handle_zeros_in_scale()
sklearn.preprocessing._data._handle_zeros_in_scale (scale, copy = True, constant_mask = None) protected
Set scales of near constant features to 1.
The goal is to avoid division by very small or zero values.
Near constant features are detected automatically by identifying
scales close to machine precision unless they are precomputed by
the caller and passed with the `constant_mask` kwarg.
Typically for standard scaling, the scales are the standard
deviation while near constant features are better detected on the
computed variances which are closer to machine precision by
construction.
Definition at line 92 of file _data.py.
Referenced by sklearn.preprocessing._data.RobustScaler.fit(), normalize(), sklearn.preprocessing._data.MaxAbsScaler.partial_fit(), sklearn.preprocessing._data.MinMaxScaler.partial_fit(), sklearn.preprocessing._data.StandardScaler.partial_fit(), and scale().
_is_constant_feature()
sklearn.preprocessing._data._is_constant_feature (var, mean, n_samples) protected
Detect if a feature is indistinguishable from a constant feature.
The detection is based on its computed variance and on the theoretical
error bounds of the '2 pass algorithm' for variance computation.
See "Algorithms for computing the sample variance: analysis and
recommendations", by Chan, Golub, and LeVeque.
Definition at line 76 of file _data.py.
Referenced by sklearn.preprocessing._data.PowerTransformer.fit_transform(), and sklearn.preprocessing._data.StandardScaler.partial_fit().
add_dummy_feature()
sklearn.preprocessing._data.add_dummy_feature (X, value = 1.0)
Augment dataset with an additional dummy feature.
This is useful for fitting an intercept term with implementations which
cannot otherwise fit it directly.
Parameters
----------
X : {array-like, sparse matrix} of shape (n_samples, n_features)
    Data.
value : float
    Value to use for the dummy feature.
Returns
-------
X : {ndarray, sparse matrix} of shape (n_samples, n_features + 1)
    Same data with dummy feature added as first column.
Examples
--------
>>> from sklearn.preprocessing import add_dummy_feature
>>> add_dummy_feature([[0, 1], [1, 0]])
array([[1., 0., 1.],
       [1., 1., 0.]])
Definition at line 2544 of file _data.py.
References add_dummy_feature().
Referenced by add_dummy_feature().
binarize()
sklearn.preprocessing._data.binarize (X, * , threshold = 0.0, copy = True)
Boolean thresholding of array-like or scipy.sparse matrix.
Read more in the :ref:`User Guide <preprocessing_binarization>`.
Parameters
----------
X : {array-like, sparse matrix} of shape (n_samples, n_features)
    The data to binarize, element by element.
    scipy.sparse matrices should be in CSR or CSC format to avoid an
    un-necessary copy.
threshold : float, default=0.0
    Feature values below or equal to this are replaced by 0, above it by 1.
    Threshold may not be less than 0 for operations on sparse matrices.
copy : bool, default=True
    If False, try to avoid a copy and binarize in place.
    This is not guaranteed to always work in place; e.g. if the data is
    a numpy array with an object dtype, a copy will be returned even with
    copy=False.
Returns
-------
X_tr : {ndarray, sparse matrix} of shape (n_samples, n_features)
    The transformed data.
See Also
--------
Binarizer : Performs binarization using the Transformer API
    (e.g. as part of a preprocessing :class:`~sklearn.pipeline.Pipeline`).
Examples
--------
>>> from sklearn.preprocessing import binarize
>>> X = [[0.4, 0.6, 0.5], [0.6, 0.1, 0.2]]
>>> binarize(X, threshold=0.5)
array([[0., 1., 0.],
       [1., 0., 0.]])
Definition at line 2170 of file _data.py.
Referenced by sklearn.preprocessing._data.Binarizer.transform().
maxabs_scale()
sklearn.preprocessing._data.maxabs_scale (X, * , axis = 0, copy = True)
Scale each feature to the [-1, 1] range without breaking the sparsity.
This estimator scales each feature individually such
that the maximal absolute value of each feature in the
training set will be 1.0.
This scaler can also be applied to sparse CSR or CSC matrices.
Parameters
----------
X : {array-like, sparse matrix} of shape (n_samples, n_features)
    The data.
axis : {0, 1}, default=0
    Axis used to scale along. If 0, independently scale each feature,
    otherwise (if 1) scale each sample.
copy : bool, default=True
    If False, try to avoid a copy and scale in place.
    This is not guaranteed to always work in place; e.g. if the data is
    a numpy array with an int dtype, a copy will be returned even with
    copy=False.
Returns
-------
X_tr : {ndarray, sparse matrix} of shape (n_samples, n_features)
    The transformed data.
.. warning:: Risk of data leak
    Do not use :func:`~sklearn.preprocessing.maxabs_scale` unless you know
    what you are doing. A common mistake is to apply it to the entire data
    *before* splitting into training and test sets. This will bias the
    model evaluation because information would have leaked from the test
    set to the training set.
    In general, we recommend using
    :class:`~sklearn.preprocessing.MaxAbsScaler` within a
    :ref:`Pipeline <pipeline>` in order to prevent most risks of data
    leaking: `pipe = make_pipeline(MaxAbsScaler(), LogisticRegression())`.
See Also
--------
MaxAbsScaler : Performs scaling to the [-1, 1] range using
    the Transformer API (e.g. as part of a preprocessing
    :class:`~sklearn.pipeline.Pipeline`).
Notes
-----
NaNs are treated as missing values: disregarded to compute the statistics,
and maintained during the data transformation.
For a comparison of the different scalers, transformers, and normalizers,
see: :ref:`sphx_glr_auto_examples_preprocessing_plot_all_scaling.py`.
Examples
--------
>>> from sklearn.preprocessing import maxabs_scale
>>> X = [[-2, 1, 2], [-1, 0, 1]]
>>> maxabs_scale(X, axis=0)  # scale each column independently
array([[-1. ,  1. ,  1. ],
       [-0.5,  0. ,  0.5]])
>>> maxabs_scale(X, axis=1)  # scale each row independently
array([[-1. ,  0.5,  1. ],
       [-1. ,  0. ,  1. ]])
Definition at line 1392 of file _data.py.
minmax_scale()
sklearn.preprocessing._data.minmax_scale (X, feature_range = (0, 1), * , axis = 0, copy = True)
Transform features by scaling each feature to a given range.
This estimator scales and translates each feature individually such
that it is in the given range on the training set, i.e. between
zero and one.
The transformation is given by (when ``axis=0``)::
    X_std = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
    X_scaled = X_std * (max - min) + min
where min, max = feature_range.
The transformation is calculated as (when ``axis=0``)::
   X_scaled = scale * X + min - X.min(axis=0) * scale
   where scale = (max - min) / (X.max(axis=0) - X.min(axis=0))
This transformation is often used as an alternative to zero mean,
unit variance scaling.
Read more in the :ref:`User Guide <preprocessing_scaler>`.
.. versionadded:: 0.17
   *minmax_scale* function interface
   to :class:`~sklearn.preprocessing.MinMaxScaler`.
Parameters
----------
X : array-like of shape (n_samples, n_features)
    The data.
feature_range : tuple (min, max), default=(0, 1)
    Desired range of transformed data.
axis : {0, 1}, default=0
    Axis used to scale along. If 0, independently scale each feature,
    otherwise (if 1) scale each sample.
copy : bool, default=True
    If False, try to avoid a copy and scale in place.
    This is not guaranteed to always work in place; e.g. if the data is
    a numpy array with an int dtype, a copy will be returned even with
    copy=False.
Returns
-------
X_tr : ndarray of shape (n_samples, n_features)
    The transformed data.
.. warning:: Risk of data leak
    Do not use :func:`~sklearn.preprocessing.minmax_scale` unless you know
    what you are doing. A common mistake is to apply it to the entire data
    *before* splitting into training and test sets. This will bias the
    model evaluation because information would have leaked from the test
    set to the training set.
    In general, we recommend using
    :class:`~sklearn.preprocessing.MinMaxScaler` within a
    :ref:`Pipeline <pipeline>` in order to prevent most risks of data
    leaking: `pipe = make_pipeline(MinMaxScaler(), LogisticRegression())`.
See Also
--------
MinMaxScaler : Performs scaling to a given range using the Transformer
    API (e.g. as part of a preprocessing
    :class:`~sklearn.pipeline.Pipeline`).
Notes
-----
For a comparison of the different scalers, transformers, and normalizers,
see: :ref:`sphx_glr_auto_examples_preprocessing_plot_all_scaling.py`.
Examples
--------
>>> from sklearn.preprocessing import minmax_scale
>>> X = [[-2, 1, 2], [-1, 0, 1]]
>>> minmax_scale(X, axis=0)  # scale each column independently
array([[0., 1., 1.],
       [1., 0., 0.]])
>>> minmax_scale(X, axis=1)  # scale each row independently
array([[0.  , 0.75, 1.  ],
       [0.  , 0.5 , 1.  ]])
Definition at line 612 of file _data.py.
normalize()
sklearn.preprocessing._data.normalize (X, norm = "l2", * , axis = 1, copy = True, return_norm = False)
Scale input vectors individually to unit norm (vector length).
Read more in the :ref:`User Guide <preprocessing_normalization>`.
Parameters
----------
X : {array-like, sparse matrix} of shape (n_samples, n_features)
    The data to normalize, element by element.
    scipy.sparse matrices should be in CSR format to avoid an
    un-necessary copy.
norm : {'l1', 'l2', 'max'}, default='l2'
    The norm to use to normalize each non zero sample (or each non-zero
    feature if axis is 0).
axis : {0, 1}, default=1
    Define axis used to normalize the data along. If 1, independently
    normalize each sample, otherwise (if 0) normalize each feature.
copy : bool, default=True
    If False, try to avoid a copy and normalize in place.
    This is not guaranteed to always work in place; e.g. if the data is
    a numpy array with an int dtype, a copy will be returned even with
    copy=False.
return_norm : bool, default=False
    Whether to return the computed norms.
Returns
-------
X : {ndarray, sparse matrix} of shape (n_samples, n_features)
    Normalized input X.
norms : ndarray of shape (n_samples,) if axis=1 else (n_features,)
    An array of norms along given axis for X.
    When X is sparse, a NotImplementedError will be raised
    for norm 'l1' or 'l2'.
See Also
--------
Normalizer : Performs normalization using the Transformer API
    (e.g. as part of a preprocessing :class:`~sklearn.pipeline.Pipeline`).
Notes
-----
For a comparison of the different scalers, transformers, and normalizers,
see: :ref:`sphx_glr_auto_examples_preprocessing_plot_all_scaling.py`.
Examples
--------
>>> from sklearn.preprocessing import normalize
>>> X = [[-2, 1, 2], [-1, 0, 1]]
>>> normalize(X, norm="l1")  # L1 normalization each row independently
array([[-0.4,  0.2,  0.4],
       [-0.5,  0. ,  0.5]])
>>> normalize(X, norm="l2")  # L2 normalization each row independently
array([[-0.67, 0.33, 0.67],
       [-0.71, 0.  , 0.71]])
Definition at line 1912 of file _data.py.
References _handle_zeros_in_scale().
Referenced by sklearn.preprocessing._data.Normalizer.transform().
power_transform()
sklearn.preprocessing._data.power_transform (X, method = "yeo-johnson", * , standardize = True, copy = True)
Parametric, monotonic transformation to make data more Gaussian-like.
Power transforms are a family of parametric, monotonic transformations
that are applied to make data more Gaussian-like. This is useful for
modeling issues related to heteroscedasticity (non-constant variance),
or other situations where normality is desired.
Currently, power_transform supports the Box-Cox transform and the
Yeo-Johnson transform. The optimal parameter for stabilizing variance and
minimizing skewness is estimated through maximum likelihood.
Box-Cox requires input data to be strictly positive, while Yeo-Johnson
supports both positive or negative data.
By default, zero-mean, unit-variance normalization is applied to the
transformed data.
Read more in the :ref:`User Guide <preprocessing_transformer>`.
Parameters
----------
X : array-like of shape (n_samples, n_features)
    The data to be transformed using a power transformation.
method : {'yeo-johnson', 'box-cox'}, default='yeo-johnson'
    The power transform method. Available methods are:
    - 'yeo-johnson' [1]_, works with positive and negative values
    - 'box-cox' [2]_, only works with strictly positive values
    .. versionchanged:: 0.23
        The default value of the `method` parameter changed from
        'box-cox' to 'yeo-johnson' in 0.23.
standardize : bool, default=True
    Set to True to apply zero-mean, unit-variance normalization to the
    transformed output.
copy : bool, default=True
    If False, try to avoid a copy and transform in place.
    This is not guaranteed to always work in place; e.g. if the data is
    a numpy array with an int dtype, a copy will be returned even with
    copy=False.
Returns
-------
X_trans : ndarray of shape (n_samples, n_features)
    The transformed data.
See Also
--------
PowerTransformer : Equivalent transformation with the
    Transformer API (e.g. as part of a preprocessing
    :class:`~sklearn.pipeline.Pipeline`).
quantile_transform : Maps data to a standard normal distribution with
    the parameter `output_distribution='normal'`.
Notes
-----
NaNs are treated as missing values: disregarded in ``fit``, and maintained
in ``transform``.
For a comparison of the different scalers, transformers, and normalizers,
see: :ref:`sphx_glr_auto_examples_preprocessing_plot_all_scaling.py`.
References
----------
.. [1] I.K. Yeo and R.A. Johnson, "A new family of power transformations to
       improve normality or symmetry." Biometrika, 87(4), pp.954-959,
       (2000).
.. [2] G.E.P. Box and D.R. Cox, "An Analysis of Transformations", Journal
       of the Royal Statistical Society B, 26, 211-252 (1964).
Examples
--------
>>> import numpy as np
>>> from sklearn.preprocessing import power_transform
>>> data = [[1, 2], [3, 2], [4, 5]]
>>> print(power_transform(data, method='box-cox'))
[[-1.332 -0.707]
 [ 0.256 -0.707]
 [ 1.076  1.414]]
.. warning:: Risk of data leak.
    Do not use :func:`~sklearn.preprocessing.power_transform` unless you
    know what you are doing. A common mistake is to apply it to the entire
    data *before* splitting into training and test sets. This will bias the
    model evaluation because information would have leaked from the test
    set to the training set.
    In general, we recommend using
    :class:`~sklearn.preprocessing.PowerTransformer` within a
    :ref:`Pipeline <pipeline>` in order to prevent most risks of data
    leaking, e.g.: `pipe = make_pipeline(PowerTransformer(),
    LogisticRegression())`.
Definition at line 3606 of file _data.py.
quantile_transform()
sklearn.preprocessing._data.quantile_transform (X, * , axis = 0, n_quantiles = 1000, output_distribution = "uniform", ignore_implicit_zeros = False, subsample = int(1e5), random_state = None, copy = True)
Transform features using quantiles information.
This method transforms the features to follow a uniform or a normal
distribution. Therefore, for a given feature, this transformation tends
to spread out the most frequent values. It also reduces the impact of
(marginal) outliers: this is therefore a robust preprocessing scheme.
The transformation is applied on each feature independently. First an
estimate of the cumulative distribution function of a feature is
used to map the original values to a uniform distribution. The obtained
values are then mapped to the desired output distribution using the
associated quantile function. Features values of new/unseen data that fall
below or above the fitted range will be mapped to the bounds of the output
distribution. Note that this transform is non-linear. It may distort linear
correlations between variables measured at the same scale but renders
variables measured at different scales more directly comparable.
Read more in the :ref:`User Guide <preprocessing_transformer>`.
Parameters
----------
X : {array-like, sparse matrix} of shape (n_samples, n_features)
    The data to transform.
axis : int, default=0
    Axis used to compute the means and standard deviations along. If 0,
    transform each feature, otherwise (if 1) transform each sample.
n_quantiles : int, default=1000 or n_samples
    Number of quantiles to be computed. It corresponds to the number
    of landmarks used to discretize the cumulative distribution function.
    If n_quantiles is larger than the number of samples, n_quantiles is set
    to the number of samples as a larger number of quantiles does not give
    a better approximation of the cumulative distribution function
    estimator.
output_distribution : {'uniform', 'normal'}, default='uniform'
    Marginal distribution for the transformed data. The choices are
    'uniform' (default) or 'normal'.
ignore_implicit_zeros : bool, default=False
    Only applies to sparse matrices. If True, the sparse entries of the
    matrix are discarded to compute the quantile statistics. If False,
    these entries are treated as zeros.
subsample : int or None, default=1e5
    Maximum number of samples used to estimate the quantiles for
    computational efficiency. Note that the subsampling procedure may
    differ for value-identical sparse and dense matrices.
    Disable subsampling by setting `subsample=None`.
    .. versionadded:: 1.5
       The option `None` to disable subsampling was added.
random_state : int, RandomState instance or None, default=None
    Determines random number generation for subsampling and smoothing
    noise.
    Please see ``subsample`` for more details.
    Pass an int for reproducible results across multiple function calls.
    See :term:`Glossary <random_state>`.
copy : bool, default=True
    If False, try to avoid a copy and transform in place.
    This is not guaranteed to always work in place; e.g. if the data is
    a numpy array with an int dtype, a copy will be returned even with
    copy=False.
    .. versionchanged:: 0.23
        The default value of `copy` changed from False to True in 0.23.
Returns
-------
Xt : {ndarray, sparse matrix} of shape (n_samples, n_features)
    The transformed data.
See Also
--------
QuantileTransformer : Performs quantile-based scaling using the
    Transformer API (e.g. as part of a preprocessing
    :class:`~sklearn.pipeline.Pipeline`).
power_transform : Maps data to a normal distribution using a
    power transformation.
scale : Performs standardization that is faster, but less robust
    to outliers.
robust_scale : Performs robust standardization that removes the influence
    of outliers but does not put outliers and inliers on the same scale.
Notes
-----
NaNs are treated as missing values: disregarded in fit, and maintained in
transform.
.. warning:: Risk of data leak
    Do not use :func:`~sklearn.preprocessing.quantile_transform` unless
    you know what you are doing. A common mistake is to apply it
    to the entire data *before* splitting into training and
    test sets. This will bias the model evaluation because
    information would have leaked from the test set to the
    training set.
    In general, we recommend using
    :class:`~sklearn.preprocessing.QuantileTransformer` within a
    :ref:`Pipeline <pipeline>` in order to prevent most risks of data
    leaking:`pipe = make_pipeline(QuantileTransformer(),
    LogisticRegression())`.
For a comparison of the different scalers, transformers, and normalizers,
see: :ref:`sphx_glr_auto_examples_preprocessing_plot_all_scaling.py`.
Examples
--------
>>> import numpy as np
>>> from sklearn.preprocessing import quantile_transform
>>> rng = np.random.RandomState(0)
>>> X = np.sort(rng.normal(loc=0.5, scale=0.25, size=(25, 1)), axis=0)
>>> quantile_transform(X, n_quantiles=10, random_state=0, copy=True)
array([...])
Definition at line 3043 of file _data.py.
robust_scale()
sklearn.preprocessing._data.robust_scale (X, * , axis = 0, with_centering = True, with_scaling = True, quantile_range = (25.0, 75.0), copy = True, unit_variance = False)
Standardize a dataset along any axis.
Center to the median and component wise scale
according to the interquartile range.
Read more in the :ref:`User Guide <preprocessing_scaler>`.
Parameters
----------
X : {array-like, sparse matrix} of shape (n_sample, n_features)
    The data to center and scale.
axis : int, default=0
    Axis used to compute the medians and IQR along. If 0,
    independently scale each feature, otherwise (if 1) scale
    each sample.
with_centering : bool, default=True
    If `True`, center the data before scaling.
with_scaling : bool, default=True
    If `True`, scale the data to unit variance (or equivalently,
    unit standard deviation).
quantile_range : tuple (q_min, q_max), 0.0 < q_min < q_max < 100.0,\
    default=(25.0, 75.0)
    Quantile range used to calculate `scale_`. By default this is equal to
    the IQR, i.e., `q_min` is the first quantile and `q_max` is the third
    quantile.
    .. versionadded:: 0.18
copy : bool, default=True
    If False, try to avoid a copy and scale in place.
    This is not guaranteed to always work in place; e.g. if the data is
    a numpy array with an int dtype, a copy will be returned even with
    copy=False.
unit_variance : bool, default=False
    If `True`, scale data so that normally distributed features have a
    variance of 1. In general, if the difference between the x-values of
    `q_max` and `q_min` for a standard normal distribution is greater
    than 1, the dataset will be scaled down. If less than 1, the dataset
    will be scaled up.
    .. versionadded:: 0.24
Returns
-------
X_tr : {ndarray, sparse matrix} of shape (n_samples, n_features)
    The transformed data.
See Also
--------
RobustScaler : Performs centering and scaling using the Transformer API
    (e.g. as part of a preprocessing :class:`~sklearn.pipeline.Pipeline`).
Notes
-----
This implementation will refuse to center scipy.sparse matrices
since it would make them non-sparse and would potentially crash the
program with memory exhaustion problems.
Instead the caller is expected to either set explicitly
`with_centering=False` (in that case, only variance scaling will be
performed on the features of the CSR matrix) or to call `X.toarray()`
if he/she expects the materialized dense array to fit in memory.
To avoid memory copy the caller should pass a CSR matrix.
For a comparison of the different scalers, transformers, and normalizers,
see: :ref:`sphx_glr_auto_examples_preprocessing_plot_all_scaling.py`.
.. warning:: Risk of data leak
    Do not use :func:`~sklearn.preprocessing.robust_scale` unless you know
    what you are doing. A common mistake is to apply it to the entire data
    *before* splitting into training and test sets. This will bias the
    model evaluation because information would have leaked from the test
    set to the training set.
    In general, we recommend using
    :class:`~sklearn.preprocessing.RobustScaler` within a
    :ref:`Pipeline <pipeline>` in order to prevent most risks of data
    leaking: `pipe = make_pipeline(RobustScaler(), LogisticRegression())`.
Examples
--------
>>> from sklearn.preprocessing import robust_scale
>>> X = [[-2, 1, 2], [-1, 0, 1]]
>>> robust_scale(X, axis=0)  # scale each column independently
array([[-1.,  1.,  1.],
       [ 1., -1., -1.]])
>>> robust_scale(X, axis=1)  # scale each row independently
array([[-1.5,  0. ,  0.5],
       [-1. ,  0. ,  1. ]])
Definition at line 1765 of file _data.py.
scale()
sklearn.preprocessing._data.scale (X, * , axis = 0, with_mean = True, with_std = True, copy = True)
Standardize a dataset along any axis.
Center to the mean and component wise scale to unit variance.
Read more in the :ref:`User Guide <preprocessing_scaler>`.
Parameters
----------
X : {array-like, sparse matrix} of shape (n_samples, n_features)
    The data to center and scale.
axis : {0, 1}, default=0
    Axis used to compute the means and standard deviations along. If 0,
    independently standardize each feature, otherwise (if 1) standardize
    each sample.
with_mean : bool, default=True
    If True, center the data before scaling.
with_std : bool, default=True
    If True, scale the data to unit variance (or equivalently,
    unit standard deviation).
copy : bool, default=True
    If False, try to avoid a copy and scale in place.
    This is not guaranteed to always work in place; e.g. if the data is
    a numpy array with an int dtype, a copy will be returned even with
    copy=False.
Returns
-------
X_tr : {ndarray, sparse matrix} of shape (n_samples, n_features)
    The transformed data.
See Also
--------
StandardScaler : Performs scaling to unit variance using the Transformer
    API (e.g. as part of a preprocessing
    :class:`~sklearn.pipeline.Pipeline`).
Notes
-----
This implementation will refuse to center scipy.sparse matrices
since it would make them non-sparse and would potentially crash the
program with memory exhaustion problems.
Instead the caller is expected to either set explicitly
`with_mean=False` (in that case, only variance scaling will be
performed on the features of the CSC matrix) or to call `X.toarray()`
if he/she expects the materialized dense array to fit in memory.
To avoid memory copy the caller should pass a CSC matrix.
NaNs are treated as missing values: disregarded to compute the statistics,
and maintained during the data transformation.
We use a biased estimator for the standard deviation, equivalent to
`numpy.std(x, ddof=0)`. Note that the choice of `ddof` is unlikely to
affect model performance.
For a comparison of the different scalers, transformers, and normalizers,
see: :ref:`sphx_glr_auto_examples_preprocessing_plot_all_scaling.py`.
.. warning:: Risk of data leak
    Do not use :func:`~sklearn.preprocessing.scale` unless you know
    what you are doing. A common mistake is to apply it to the entire data
    *before* splitting into training and test sets. This will bias the
    model evaluation because information would have leaked from the test
    set to the training set.
    In general, we recommend using
    :class:`~sklearn.preprocessing.StandardScaler` within a
    :ref:`Pipeline <pipeline>` in order to prevent most risks of data
    leaking: `pipe = make_pipeline(StandardScaler(), LogisticRegression())`.
Examples
--------
>>> from sklearn.preprocessing import scale
>>> X = [[-2, 1, 2], [-1, 0, 1]]
>>> scale(X, axis=0)  # scaling each column independently
array([[-1.,  1.,  1.],
       [ 1., -1., -1.]])
>>> scale(X, axis=1)  # scaling each row independently
array([[-1.37,  0.39,  0.98],
       [-1.22,  0.     ,  1.22]])
Definition at line 137 of file _data.py.
References _handle_zeros_in_scale().
Variable Documentation
__all__
list sklearn.preprocessing._data.__all__ private
Initial value:
=  [
    "Binarizer",
    "KernelCenterer",
    "MaxAbsScaler",
    "MinMaxScaler",
    "Normalizer",
    "OneHotEncoder",
    "PowerTransformer",
    "QuantileTransformer",
    "RobustScaler",
    "StandardScaler",
    "add_dummy_feature",
    "binarize",
    "maxabs_scale",
    "minmax_scale",
    "normalize",
    "power_transform",
    "quantile_transform",
    "robust_scale",
    "scale",
]
Definition at line 53 of file _data.py.
BOUNDS_THRESHOLD
int sklearn.preprocessing._data.BOUNDS_THRESHOLD = 1e-7
Definition at line 51 of file _data.py.