Code Cloning Analysis: fontTools.designspaceLib.types.Range Class Reference
fontTools.designspaceLib.types.Range Class Reference
Public Member Functions
__post_init__ (self)
bool __contains__ (self, Union[float, Range] value)
Optional[Range] intersection (self, Range other)
Public Attributes
minimum
maximum = sorted((self.minimum, self.maximum))
Static Public Attributes
float default = 0
Detailed Description
Definition at line 22 of file types.py.
Member Function Documentation
__contains__()
bool fontTools.designspaceLib.types.Range.__contains__ (self, Union[float, Range] value)
Definition at line 34 of file types.py.
__post_init__()
fontTools.designspaceLib.types.Range.__post_init__ (self)
Definition at line 30 of file types.py.
intersection()
Optional[Range] fontTools.designspaceLib.types.Range.intersection (self, Range other)
Definition at line 39 of file types.py.
Referenced by pandas.core.indexes.range.RangeIndex._union(), and pandas.core.indexes.base.Index.join().
Member Data Documentation
default
fontTools.designspaceLib.types.Range.default = 0 static
Definition at line 27 of file types.py.
Referenced by fontTools.varLib.instancer.AxisTriple.limitRangeAndPopulateDefaults(), numpy.lib._iotools.StringConverter.update(), and numpy.lib._iotools.StringConverter.upgrade_mapper().
maximum
fontTools.designspaceLib.types.Range.maximum = sorted((self.minimum, self.maximum))
Definition at line 31 of file types.py.
Referenced by fontTools.varLib.instancer.AxisTriple.limitRangeAndPopulateDefaults(), and pip._vendor.rich.measure.Measurement.span().
minimum
fontTools.designspaceLib.types.Range.minimum
Definition at line 31 of file types.py.
Referenced by fontTools.varLib.instancer.AxisTriple.limitRangeAndPopulateDefaults(), and pip._vendor.rich.measure.Measurement.span().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/designspaceLib/types.py