Code Cloning Analysis: sklearn.tests.test_metaestimators Namespace Reference
sklearn.tests.test_metaestimators Namespace Reference
Classes
class DelegatorData
Functions
test_metaestimator_delegation ()
_get_instance_with_pipeline (meta_estimator, init_params)
_generate_meta_estimator_instances_with_pipeline ()
Variables
list DELEGATING_METAESTIMATORS
param = param
hidden_method = hidden_method
coef_ = np.arange(X.shape[1])
list classes_ = []
Detailed Description
Common tests for metaestimators
Function Documentation
_generate_meta_estimator_instances_with_pipeline()
sklearn.tests.test_metaestimators._generate_meta_estimator_instances_with_pipeline () protected
Generate instances of meta-estimators fed with a pipeline
Are considered meta-estimators all estimators accepting one of "estimator",
"base_estimator" or "estimators".
Definition at line 251 of file test_metaestimators.py.
References _generate_meta_estimator_instances_with_pipeline(), and _get_instance_with_pipeline().
Referenced by _generate_meta_estimator_instances_with_pipeline().
_get_instance_with_pipeline()
sklearn.tests.test_metaestimators._get_instance_with_pipeline (meta_estimator, init_params) protected
Given a single meta-estimator instance, generate an instance with a pipeline
Definition at line 204 of file test_metaestimators.py.
Referenced by _generate_meta_estimator_instances_with_pipeline().
test_metaestimator_delegation()
sklearn.tests.test_metaestimators.test_metaestimator_delegation ()
Definition at line 87 of file test_metaestimators.py.
Variable Documentation
classes_
list sklearn.tests.test_metaestimators.classes_ = []
Definition at line 105 of file test_metaestimators.py.
coef_
sklearn.tests.test_metaestimators.coef_ = np.arange(X.shape[1])
Definition at line 104 of file test_metaestimators.py.
DELEGATING_METAESTIMATORS
list sklearn.tests.test_metaestimators.DELEGATING_METAESTIMATORS
Definition at line 49 of file test_metaestimators.py.
hidden_method
sklearn.tests.test_metaestimators.hidden_method = hidden_method
Definition at line 101 of file test_metaestimators.py.
param
sklearn.tests.test_metaestimators.param = param
Definition at line 100 of file test_metaestimators.py.