Code Cloning Analysis: matplotlib.ticker.Locator Class Reference
matplotlib.ticker.Locator Class Reference
Public Member Functions
tick_values (self, vmin, vmax)
set_params (self, **kwargs)
__call__ (self)
raise_if_exceeds (self, locs)
nonsingular (self, v0, v1)
view_limits (self, vmin, vmax)
Public Member Functions inherited from matplotlib.ticker.TickHelper
set_axis (self, axis)
create_dummy_axis (self, **kwargs)
Static Public Attributes
int MAXTICKS = 1000
Static Public Attributes inherited from matplotlib.ticker.TickHelper
axis = None
Detailed Description
Determine tick locations.
Note that the same locator should not be used across multiple
`~matplotlib.axis.Axis` because the locator stores references to the Axis
data and view limits.
Definition at line 1649 of file ticker.py.
Member Function Documentation
__call__()
matplotlib.ticker.Locator.__call__ (self)
Return the locations of the ticks.
Definition at line 1690 of file ticker.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), and scipy.interpolate._fitpack2.SphereBivariateSpline.ev().
nonsingular()
matplotlib.ticker.Locator.nonsingular (self, v0, v1)
Adjust a range as needed to avoid singularities.
This method gets called during autoscaling, with ``(v0, v1)`` set to
the data limits on the Axes if the Axes contains any data, or
``(-inf, +inf)`` if not.
- If ``v0 == v1`` (possibly up to some floating point slop), this
  method returns an expanded interval around this value.
- If ``(v0, v1) == (-inf, +inf)``, this method returns appropriate
  default view limits.
- Otherwise, ``(v0, v1)`` is returned without modification.
Reimplemented in matplotlib.dates.AutoDateLocator, matplotlib.dates.DateLocator, matplotlib.ticker.LogitLocator, and matplotlib.ticker.LogLocator.
Definition at line 1714 of file ticker.py.
Referenced by pandas.plotting._matplotlib.converter.MilliSecondLocator.autoscale(), and pandas.plotting._matplotlib.converter.TimeSeries_DateLocator.autoscale().
raise_if_exceeds()
matplotlib.ticker.Locator.raise_if_exceeds (self, locs)
Log at WARNING level if *locs* is longer than `Locator.MAXTICKS`.
This is intended to be called immediately before returning *locs* from
``__call__`` to inform users in case their Locator returns a huge
number of ticks, causing Matplotlib to run out of memory.
The "strange" name of this method dates back to when it would raise an
exception instead of emitting a log.
Definition at line 1696 of file ticker.py.
References MAXTICKS.
Referenced by matplotlib.dates.RRuleLocator.tick_values().
set_params()
matplotlib.ticker.Locator.set_params (self, ** kwargs)
Do nothing, and raise a warning. Any locator class not supporting the
set_params() function will call this.
Reimplemented in matplotlib.ticker.AsinhLocator, matplotlib.ticker.FixedLocator, matplotlib.ticker.IndexLocator, matplotlib.ticker.LinearLocator, matplotlib.ticker.LogitLocator, matplotlib.ticker.LogLocator, matplotlib.ticker.MaxNLocator, matplotlib.ticker.MultipleLocator, and matplotlib.ticker.SymmetricalLogLocator.
Definition at line 1681 of file ticker.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.theta().
tick_values()
matplotlib.ticker.Locator.tick_values (self, vmin, vmax)
Return the values of the located ticks given **vmin** and **vmax**.
.. note::
    To get tick locations with the vmin and vmax values defined
    automatically for the associated ``axis`` simply call
    the Locator instance::
        >>> print(type(loc))
        <type 'Locator'>
        >>> print(loc())
        [1, 2, 3, 4]
Reimplemented in matplotlib.category.StrCategoryLocator, matplotlib.dates.AutoDateLocator, matplotlib.dates.MicrosecondLocator, matplotlib.dates.RRuleLocator, matplotlib.ticker.AsinhLocator, matplotlib.ticker.AutoMinorLocator, matplotlib.ticker.FixedLocator, matplotlib.ticker.IndexLocator, matplotlib.ticker.LinearLocator, matplotlib.ticker.LogitLocator, matplotlib.ticker.LogLocator, matplotlib.ticker.MaxNLocator, matplotlib.ticker.MultipleLocator, matplotlib.ticker.NullLocator, and matplotlib.ticker.SymmetricalLogLocator.
Definition at line 1664 of file ticker.py.
view_limits()
matplotlib.ticker.Locator.view_limits (self, vmin, vmax)
Select a scale for the range from vmin to vmax.
Subclasses should override this method to change locator behaviour.
Reimplemented in matplotlib.ticker.LinearLocator, matplotlib.ticker.LogLocator, matplotlib.ticker.MaxNLocator, matplotlib.ticker.MultipleLocator, and matplotlib.ticker.SymmetricalLogLocator.
Definition at line 1730 of file ticker.py.
Member Data Documentation
MAXTICKS
matplotlib.ticker.Locator.MAXTICKS = 1000 static
Definition at line 1662 of file ticker.py.
Referenced by raise_if_exceeds().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/ticker.py