Code Cloning Analysis: scipy.fftpack._pseudo_diffs Namespace Reference
scipy.fftpack._pseudo_diffs Namespace Reference
Functions
diff (x, order=1, period=None, _cache=_cache)
tilbert (x, h, period=None, _cache=_cache)
itilbert (x, h, period=None, _cache=_cache)
hilbert (x, _cache=_cache)
ihilbert (x)
cs_diff (x, a, b, period=None, _cache=_cache)
sc_diff (x, a, b, period=None, _cache=_cache)
ss_diff (x, a, b, period=None, _cache=_cache)
cc_diff (x, a, b, period=None, _cache=_cache)
shift (x, a, period=None, _cache=_cache)
Variables
list __all__
dict _cache = {}
Detailed Description
Differential and pseudo-differential operators.
Function Documentation
cc_diff()
scipy.fftpack._pseudo_diffs.cc_diff (x, a, b, period = None, _cache = _cache)
Return (a,b)-cosh/cosh pseudo-derivative of a periodic sequence.
If x_j and y_j are Fourier coefficients of periodic functions x
and y, respectively, then::
  y_j = cosh(j*a*2*pi/period)/cosh(j*b*2*pi/period) * x_j
Parameters
----------
x : array_like
    The array to take the pseudo-derivative from.
a,b : float
    Defines the parameters of the sinh/sinh pseudo-differential
    operator.
period : float, optional
    The period of the sequence x. Default is ``2*pi``.
Returns
-------
cc_diff : ndarray
    Pseudo-derivative of periodic sequence `x`.
Notes
-----
``cc_diff(cc_diff(x,a,b),b,a) == x``
Definition at line 447 of file _pseudo_diffs.py.
References cc_diff().
Referenced by cc_diff().
cs_diff()
scipy.fftpack._pseudo_diffs.cs_diff (x, a, b, period = None, _cache = _cache)
Return (a,b)-cosh/sinh pseudo-derivative of a periodic sequence.
If ``x_j`` and ``y_j`` are Fourier coefficients of periodic functions x
and y, respectively, then::
  y_j = -sqrt(-1)*cosh(j*a*2*pi/period)/sinh(j*b*2*pi/period) * x_j
  y_0 = 0
Parameters
----------
x : array_like
    The array to take the pseudo-derivative from.
a, b : float
    Defines the parameters of the cosh/sinh pseudo-differential
    operator.
period : float, optional
    The period of the sequence. Default period is ``2*pi``.
Returns
-------
cs_diff : ndarray
    Pseudo-derivative of periodic sequence `x`.
Notes
-----
For even len(`x`), the Nyquist mode of `x` is taken as zero.
Definition at line 276 of file _pseudo_diffs.py.
References cs_diff().
Referenced by cs_diff().
diff()
scipy.fftpack._pseudo_diffs.diff (x, order = 1, period = None, _cache = _cache)
Return kth derivative (or integral) of a periodic sequence x.
If x_j and y_j are Fourier coefficients of periodic functions x
and y, respectively, then::
  y_j = pow(sqrt(-1)*j*2*pi/period, order) * x_j
  y_0 = 0 if order is not 0.
Parameters
----------
x : array_like
    Input array.
order : int, optional
    The order of differentiation. Default order is 1. If order is
    negative, then integration is carried out under the assumption
    that ``x_0 == 0``.
period : float, optional
    The assumed period of the sequence. Default is ``2*pi``.
Notes
-----
If ``sum(x, axis=0) = 0`` then ``diff(diff(x, k), -k) == x`` (within
numerical accuracy).
For odd order and even ``len(x)``, the Nyquist mode is taken zero.
Definition at line 20 of file _pseudo_diffs.py.
References diff().
Referenced by diff().
hilbert()
scipy.fftpack._pseudo_diffs.hilbert (x, _cache = _cache)
Return Hilbert transform of a periodic sequence x.
If x_j and y_j are Fourier coefficients of periodic functions x
and y, respectively, then::
  y_j = sqrt(-1)*sign(j) * x_j
  y_0 = 0
Parameters
----------
x : array_like
    The input array, should be periodic.
_cache : dict, optional
    Dictionary that contains the kernel used to do a convolution with.
Returns
-------
y : ndarray
    The transformed input.
See Also
--------
scipy.signal.hilbert : Compute the analytic signal, using the Hilbert
                       transform.
Notes
-----
If ``sum(x, axis=0) == 0`` then ``hilbert(ihilbert(x)) == x``.
For even len(x), the Nyquist mode of x is taken zero.
The sign of the returned transform does not have a factor -1 that is more
often than not found in the definition of the Hilbert transform. Note also
that `scipy.signal.hilbert` does have an extra -1 factor compared to this
function.
Definition at line 195 of file _pseudo_diffs.py.
References hilbert().
Referenced by hilbert(), and ihilbert().
ihilbert()
scipy.fftpack._pseudo_diffs.ihilbert (x)
Return inverse Hilbert transform of a periodic sequence x.
If ``x_j`` and ``y_j`` are Fourier coefficients of periodic functions x
and y, respectively, then::
  y_j = -sqrt(-1)*sign(j) * x_j
  y_0 = 0
Definition at line 259 of file _pseudo_diffs.py.
References hilbert().
itilbert()
scipy.fftpack._pseudo_diffs.itilbert (x, h, period = None, _cache = _cache)
Return inverse h-Tilbert transform of a periodic sequence x.
If ``x_j`` and ``y_j`` are Fourier coefficients of periodic functions x
and y, respectively, then::
  y_j = -sqrt(-1)*tanh(j*h*2*pi/period) * x_j
  y_0 = 0
For more details, see `tilbert`.
Definition at line 153 of file _pseudo_diffs.py.
References itilbert().
Referenced by itilbert().
sc_diff()
scipy.fftpack._pseudo_diffs.sc_diff (x, a, b, period = None, _cache = _cache)
Return (a,b)-sinh/cosh pseudo-derivative of a periodic sequence x.
If x_j and y_j are Fourier coefficients of periodic functions x
and y, respectively, then::
  y_j = sqrt(-1)*sinh(j*a*2*pi/period)/cosh(j*b*2*pi/period) * x_j
  y_0 = 0
Parameters
----------
x : array_like
    Input array.
a,b : float
    Defines the parameters of the sinh/cosh pseudo-differential
    operator.
period : float, optional
    The period of the sequence x. Default is 2*pi.
Notes
-----
``sc_diff(cs_diff(x,a,b),b,a) == x``
For even ``len(x)``, the Nyquist mode of x is taken as zero.
Definition at line 336 of file _pseudo_diffs.py.
References sc_diff().
Referenced by sc_diff().
shift()
scipy.fftpack._pseudo_diffs.shift (x, a, period = None, _cache = _cache)
Shift periodic sequence x by a: y(u) = x(u+a).
If x_j and y_j are Fourier coefficients of periodic functions x
and y, respectively, then::
      y_j = exp(j*a*2*pi/period*sqrt(-1)) * x_f
Parameters
----------
x : array_like
    The array to take the pseudo-derivative from.
a : float
    Defines the parameters of the sinh/sinh pseudo-differential
period : float, optional
    The period of the sequences x and y. Default period is ``2*pi``.
Definition at line 504 of file _pseudo_diffs.py.
References shift().
Referenced by shift().
ss_diff()
scipy.fftpack._pseudo_diffs.ss_diff (x, a, b, period = None, _cache = _cache)
Return (a,b)-sinh/sinh pseudo-derivative of a periodic sequence x.
If x_j and y_j are Fourier coefficients of periodic functions x
and y, respectively, then::
  y_j = sinh(j*a*2*pi/period)/sinh(j*b*2*pi/period) * x_j
  y_0 = a/b * x_0
Parameters
----------
x : array_like
    The array to take the pseudo-derivative from.
a,b
    Defines the parameters of the sinh/sinh pseudo-differential
    operator.
period : float, optional
    The period of the sequence x. Default is ``2*pi``.
Notes
-----
``ss_diff(ss_diff(x,a,b),b,a) == x``
Definition at line 392 of file _pseudo_diffs.py.
References ss_diff().
Referenced by ss_diff().
tilbert()
scipy.fftpack._pseudo_diffs.tilbert (x, h, period = None, _cache = _cache)
Return h-Tilbert transform of a periodic sequence x.
If x_j and y_j are Fourier coefficients of periodic functions x
and y, respectively, then::
    y_j = sqrt(-1)*coth(j*h*2*pi/period) * x_j
    y_0 = 0
Parameters
----------
x : array_like
    The input array to transform.
h : float
    Defines the parameter of the Tilbert transform.
period : float, optional
    The assumed period of the sequence. Default period is ``2*pi``.
Returns
-------
tilbert : ndarray
    The result of the transform.
Notes
-----
If ``sum(x, axis=0) == 0`` and ``n = len(x)`` is odd, then
``tilbert(itilbert(x)) == x``.
If ``2 * pi * h / period`` is approximately 10 or larger, then
numerically ``tilbert == hilbert``
(theoretically oo-Tilbert == Hilbert).
For even ``len(x)``, the Nyquist mode of ``x`` is taken zero.
Definition at line 83 of file _pseudo_diffs.py.
References tilbert().
Referenced by tilbert().
Variable Documentation
__all__
list scipy.fftpack._pseudo_diffs.__all__ private
Initial value:
=  ['diff',
           'tilbert','itilbert','hilbert','ihilbert',
           'cs_diff','cc_diff','sc_diff','ss_diff',
           'shift']
Definition at line 6 of file _pseudo_diffs.py.
_cache
dict scipy.fftpack._pseudo_diffs._cache = {} protected
Definition at line 17 of file _pseudo_diffs.py.