Code Cloning Analysis: sklearn.externals.array_api_compat.common._helpers Namespace Reference
sklearn.externals.array_api_compat.common._helpers Namespace Reference
Classes
class _dask_device
Functions
bool _issubclass_fast (type cls, str modname, str clsname)
TypeGuard[_ZeroGradientArray] _is_jax_zero_gradient_array (object x)
TypeGuard[npt.NDArray[Any]] is_numpy_array (object x)
bool is_cupy_array (object x)
TypeIs[torch.Tensor] is_torch_array (object x)
TypeIs[ndx.Array] is_ndonnx_array (object x)
TypeIs[da.Array] is_dask_array (object x)
TypeIs[jax.Array] is_jax_array (object x)
TypeIs[sparse.SparseArray] is_pydata_sparse_array (object x)
TypeIs[_ArrayApiObj] is_array_api_obj (object x)
bool _is_array_api_cls (type cls)
str _compat_module_name ()
bool is_numpy_namespace (Namespace xp)
bool is_cupy_namespace (Namespace xp)
bool is_torch_namespace (Namespace xp)
bool is_ndonnx_namespace (Namespace xp)
bool is_dask_namespace (Namespace xp)
bool is_jax_namespace (Namespace xp)
bool is_pydata_sparse_namespace (Namespace xp)
bool is_array_api_strict_namespace (Namespace xp)
None _check_api_version (str|None api_version)
Namespace array_namespace (*Array|complex|None xs, str|None api_version=None, bool|None use_compat=None)
None _check_device (Namespace bare_xp, Device device)
Device device (_ArrayApiObj x)
_CupyArray _cupy_to_device (_CupyArray x, Device device, int|Any|None stream=None)
torch.Tensor _torch_to_device (torch.Tensor x, torch.device|str|int device, None stream=None)
Array to_device (Array x, Device device, *, int|Any|None stream=None)
int size (HasShape[Collection[SupportsIndex]] x)
None size (HasShape[Collection[None]] x)
int|None size (HasShape[Collection[SupportsIndex|None]] x)
bool|None _is_writeable_cls (type cls)
bool is_writeable_array (object x)
bool|None _is_lazy_cls (type cls)
bool is_lazy_array (object x)
list[str] __dir__ ()
Variables
_SizeT = TypeVar("_SizeT", bound = int | None)
TypeAlias _ZeroGradientArray = npt.NDArray[np.void]
TypeAlias _CupyArray = Any
tuple _ArrayApiObj
Final _API_VERSIONS_OLD = frozenset({"2021.12", "2022.12", "2023.12"})
Final _API_VERSIONS = _API_VERSIONS_OLD | frozenset({"2024.12"})
Namespace get_namespace = array_namespace
_DASK_DEVICE = _dask_device()
Device _device = device
list __all__
list _all_ignore = ['lru_cache', 'sys', 'math', 'inspect', 'warnings']
Detailed Description
Various helper functions which are not part of the spec.
Functions which start with an underscore are for internal use only but helpers
that are in __all__ are intended as additional helper functions for use by end
users of the compat library.
Function Documentation
__dir__()
list[str] sklearn.externals.array_api_compat.common._helpers.__dir__ ()
Definition at line 1057 of file _helpers.py.
_check_api_version()
None sklearn.externals.array_api_compat.common._helpers._check_api_version (str | None api_version) protected
Definition at line 477 of file _helpers.py.
_check_device()
None sklearn.externals.array_api_compat.common._helpers._check_device (Namespace bare_xp, Device device) protected
Validate dummy device on device-less array backends.
Notes
-----
This function is also invoked by CuPy, which does have multiple devices
if there are multiple GPUs available.
However, CuPy multi-device support is currently impossible
without using the global device or a context manager:
https://github.com/data-apis/array-api-compat/pull/293
Definition at line 660 of file _helpers.py.
_compat_module_name()
str sklearn.externals.array_api_compat.common._helpers._compat_module_name () protected
Definition at line 305 of file _helpers.py.
_cupy_to_device()
_CupyArray sklearn.externals.array_api_compat.common._helpers._cupy_to_device (_CupyArray x, Device device, int | Any | None stream = None) protected
Definition at line 772 of file _helpers.py.
_is_array_api_cls()
bool sklearn.externals.array_api_compat.common._helpers._is_array_api_cls (type cls) protected
Definition at line 291 of file _helpers.py.
_is_jax_zero_gradient_array()
TypeGuard[_ZeroGradientArray] sklearn.externals.array_api_compat.common._helpers._is_jax_zero_gradient_array (object x) protected
Return True if `x` is a zero-gradient array.
These arrays are a design quirk of Jax that may one day be removed.
See https://github.com/google/jax/issues/20620.
Definition at line 75 of file _helpers.py.
Referenced by is_jax_array(), and is_numpy_array().
_is_lazy_cls()
bool | None sklearn.externals.array_api_compat.common._helpers._is_lazy_cls (type cls) protected
Definition at line 955 of file _helpers.py.
_is_writeable_cls()
bool | None sklearn.externals.array_api_compat.common._helpers._is_writeable_cls (type cls) protected
Definition at line 923 of file _helpers.py.
_issubclass_fast()
bool sklearn.externals.array_api_compat.common._helpers._issubclass_fast (type cls, str modname, str clsname) protected
Definition at line 66 of file _helpers.py.
_torch_to_device()
torch.Tensor sklearn.externals.array_api_compat.common._helpers._torch_to_device (torch.Tensor x, torch.device | str | int device, None stream = None) protected
Definition at line 802 of file _helpers.py.
array_namespace()
Namespace sklearn.externals.array_api_compat.common._helpers.array_namespace (*Array | complex | None xs, str | None api_version = None, bool | None use_compat = None)
Get the array API compatible namespace for the arrays `xs`.
Parameters
----------
xs: arrays
    one or more arrays. xs can also be Python scalars (bool, int, float,
    complex, or None), which are ignored.
api_version: str
    The newest version of the spec that you need support for (currently
    the compat library wrapped APIs support v2024.12).
use_compat: bool or None
    If None (the default), the native namespace will be returned if it is
    already array API compatible, otherwise a compat wrapper is used. If
    True, the compat library wrapped library will be returned. If False,
    the native library namespace is returned.
Returns
-------
out: namespace
    The array API compatible namespace corresponding to the arrays in `xs`.
Raises
------
TypeError
    If `xs` contains arrays from different array libraries or contains a
    non-array.
Typical usage is to pass the arguments of a function to
`array_namespace()` at the top of a function to get the corresponding
array API namespace:
.. code:: python
   def your_function(x, y):
       xp = array_api_compat.array_namespace(x, y)
       # Now use xp as the array library namespace
       return xp.mean(x, axis=0) + 2*xp.std(y, axis=0)
Wrapped array namespaces can also be imported directly. For example,
`array_namespace(np.array(...))` will return `array_api_compat.numpy`.
This function will also work for any array library not wrapped by
array-api-compat if it explicitly defines `__array_namespace__
<https://data-apis.org/array-api/latest/API_specification/generated/array_api.array.__array_namespace__.html>`__
(the wrapped namespace is always preferred if it exists).
See Also
--------
is_array_api_obj
is_numpy_array
is_cupy_array
is_torch_array
is_dask_array
is_jax_array
is_pydata_sparse_array
Definition at line 488 of file _helpers.py.
References is_cupy_array(), is_dask_array(), is_jax_array(), is_numpy_array(), is_pydata_sparse_array(), and is_torch_array().
Referenced by sklearn.externals.array_api_compat.dask.array._aliases.argsort(), is_lazy_array(), and sklearn.externals.array_api_compat.dask.array._aliases.sort().
device()
Device sklearn.externals.array_api_compat.common._helpers.device (_ArrayApiObj x)
Hardware device the array data resides on.
This is equivalent to `x.device` according to the `standard
<https://data-apis.org/array-api/latest/API_specification/generated/array_api.array.device.html>`__.
This helper is included because some array libraries either do not have
the `device` attribute or include it with an incompatible API.
Parameters
----------
x: array
    array instance from an array API compatible library.
Returns
-------
out: device
    a ``device`` object (see the `Device Support <https://data-apis.org/array-api/latest/design_topics/device_support.html>`__
    section of the array API specification).
Notes
-----
For NumPy the device is always `"cpu"`. For Dask, the device is always a
special `DASK_DEVICE` object.
See Also
--------
to_device : Move array data to a different device.
Definition at line 699 of file _helpers.py.
References device(), is_dask_array(), is_jax_array(), is_numpy_array(), and is_pydata_sparse_array().
Referenced by device().
is_array_api_obj()
TypeIs[_ArrayApiObj] sklearn.externals.array_api_compat.common._helpers.is_array_api_obj (object x)
Return True if `x` is an array API compatible array object.
See Also
--------
array_namespace
is_numpy_array
is_cupy_array
is_torch_array
is_ndonnx_array
is_dask_array
is_jax_array
Definition at line 269 of file _helpers.py.
is_array_api_strict_namespace()
bool sklearn.externals.array_api_compat.common._helpers.is_array_api_strict_namespace (Namespace xp)
Returns True if `xp` is an array-api-strict namespace.
See Also
--------
array_namespace
is_numpy_namespace
is_cupy_namespace
is_torch_namespace
is_ndonnx_namespace
is_dask_namespace
is_jax_namespace
is_pydata_sparse_namespace
Definition at line 458 of file _helpers.py.
is_cupy_array()
bool sklearn.externals.array_api_compat.common._helpers.is_cupy_array (object x)
Return True if `x` is a CuPy array.
This function does not import CuPy if it has not already been imported
and is therefore cheap to use.
This also returns True for `cupy.ndarray` subclasses and CuPy scalar objects.
See Also
--------
array_namespace
is_array_api_obj
is_numpy_array
is_torch_array
is_ndonnx_array
is_dask_array
is_jax_array
is_pydata_sparse_array
Definition at line 127 of file _helpers.py.
Referenced by array_namespace(), and to_device().
is_cupy_namespace()
bool sklearn.externals.array_api_compat.common._helpers.is_cupy_namespace (Namespace xp)
Returns True if `xp` is a CuPy namespace.
This includes both CuPy itself and the version wrapped by array-api-compat.
See Also
--------
array_namespace
is_numpy_namespace
is_torch_namespace
is_ndonnx_namespace
is_dask_namespace
is_jax_namespace
is_pydata_sparse_namespace
is_array_api_strict_namespace
Definition at line 333 of file _helpers.py.
is_dask_array()
TypeIs[da.Array] sklearn.externals.array_api_compat.common._helpers.is_dask_array (object x)
Return True if `x` is a dask.array Array.
This function does not import dask if it has not already been imported
and is therefore cheap to use.
See Also
--------
array_namespace
is_array_api_obj
is_numpy_array
is_cupy_array
is_torch_array
is_ndonnx_array
is_jax_array
is_pydata_sparse_array
Definition at line 197 of file _helpers.py.
Referenced by array_namespace(), device(), and to_device().
is_dask_namespace()
bool sklearn.externals.array_api_compat.common._helpers.is_dask_namespace (Namespace xp)
Returns True if `xp` is a Dask namespace.
This includes both ``dask.array`` itself and the version wrapped by array-api-compat.
See Also
--------
array_namespace
is_numpy_namespace
is_cupy_namespace
is_torch_namespace
is_ndonnx_namespace
is_jax_namespace
is_pydata_sparse_namespace
is_array_api_strict_namespace
Definition at line 396 of file _helpers.py.
is_jax_array()
TypeIs[jax.Array] sklearn.externals.array_api_compat.common._helpers.is_jax_array (object x)
Return True if `x` is a JAX array.
This function does not import JAX if it has not already been imported
and is therefore cheap to use.
See Also
--------
array_namespace
is_array_api_obj
is_numpy_array
is_cupy_array
is_torch_array
is_ndonnx_array
is_dask_array
is_pydata_sparse_array
Definition at line 220 of file _helpers.py.
References _is_jax_zero_gradient_array().
Referenced by array_namespace(), device(), and to_device().
is_jax_namespace()
bool sklearn.externals.array_api_compat.common._helpers.is_jax_namespace (Namespace xp)
Returns True if `xp` is a JAX namespace.
This includes ``jax.numpy`` and ``jax.experimental.array_api`` which existed in
older versions of JAX.
See Also
--------
array_namespace
is_numpy_namespace
is_cupy_namespace
is_torch_namespace
is_ndonnx_namespace
is_dask_namespace
is_pydata_sparse_namespace
is_array_api_strict_namespace
Definition at line 417 of file _helpers.py.
is_lazy_array()
bool sklearn.externals.array_api_compat.common._helpers.is_lazy_array (object x)
Return True if x is potentially a future or it may be otherwise impossible or
expensive to eagerly read its contents, regardless of their size, e.g. by
calling ``bool(x)`` or ``float(x)``.
Return False otherwise; e.g. ``bool(x)`` etc. is guaranteed to succeed and to be
cheap as long as the array has the right dtype and size.
Note
----
This function errs on the side of caution for array types that may or may not be
lazy, e.g. JAX arrays, by always returning True for them.
Definition at line 973 of file _helpers.py.
References array_namespace().
is_ndonnx_array()
TypeIs[ndx.Array] sklearn.externals.array_api_compat.common._helpers.is_ndonnx_array (object x)
Return True if `x` is a ndonnx Array.
This function does not import ndonnx if it has not already been imported
and is therefore cheap to use.
See Also
--------
array_namespace
is_array_api_obj
is_numpy_array
is_cupy_array
is_ndonnx_array
is_dask_array
is_jax_array
is_pydata_sparse_array
Definition at line 174 of file _helpers.py.
is_ndonnx_namespace()
bool sklearn.externals.array_api_compat.common._helpers.is_ndonnx_namespace (Namespace xp)
Returns True if `xp` is an NDONNX namespace.
See Also
--------
array_namespace
is_numpy_namespace
is_cupy_namespace
is_torch_namespace
is_dask_namespace
is_jax_namespace
is_pydata_sparse_namespace
is_array_api_strict_namespace
Definition at line 376 of file _helpers.py.
is_numpy_array()
TypeGuard[npt.NDArray[Any]] sklearn.externals.array_api_compat.common._helpers.is_numpy_array (object x)
Return True if `x` is a NumPy array.
This function does not import NumPy if it has not already been imported
and is therefore cheap to use.
This also returns True for `ndarray` subclasses and NumPy scalar objects.
See Also
--------
array_namespace
is_array_api_obj
is_cupy_array
is_torch_array
is_ndonnx_array
is_dask_array
is_jax_array
is_pydata_sparse_array
Definition at line 98 of file _helpers.py.
References _is_jax_zero_gradient_array().
Referenced by array_namespace(), device(), and to_device().
is_numpy_namespace()
bool sklearn.externals.array_api_compat.common._helpers.is_numpy_namespace (Namespace xp)
Returns True if `xp` is a NumPy namespace.
This includes both NumPy itself and the version wrapped by array-api-compat.
See Also
--------
array_namespace
is_cupy_namespace
is_torch_namespace
is_ndonnx_namespace
is_dask_namespace
is_jax_namespace
is_pydata_sparse_namespace
is_array_api_strict_namespace
Definition at line 311 of file _helpers.py.
is_pydata_sparse_array()
TypeIs[sparse.SparseArray] sklearn.externals.array_api_compat.common._helpers.is_pydata_sparse_array (object x)
Return True if `x` is an array from the `sparse` package.
This function does not import `sparse` if it has not already been imported
and is therefore cheap to use.
See Also
--------
array_namespace
is_array_api_obj
is_numpy_array
is_cupy_array
is_torch_array
is_ndonnx_array
is_dask_array
is_jax_array
Definition at line 244 of file _helpers.py.
Referenced by array_namespace(), device(), and to_device().
is_pydata_sparse_namespace()
bool sklearn.externals.array_api_compat.common._helpers.is_pydata_sparse_namespace (Namespace xp)
Returns True if `xp` is a pydata/sparse namespace.
See Also
--------
array_namespace
is_numpy_namespace
is_cupy_namespace
is_torch_namespace
is_ndonnx_namespace
is_dask_namespace
is_jax_namespace
is_array_api_strict_namespace
Definition at line 439 of file _helpers.py.
is_torch_array()
TypeIs[torch.Tensor] sklearn.externals.array_api_compat.common._helpers.is_torch_array (object x)
Return True if `x` is a PyTorch tensor.
This function does not import PyTorch if it has not already been imported
and is therefore cheap to use.
See Also
--------
array_namespace
is_array_api_obj
is_numpy_array
is_cupy_array
is_dask_array
is_jax_array
is_pydata_sparse_array
Definition at line 152 of file _helpers.py.
Referenced by array_namespace(), and to_device().
is_torch_namespace()
bool sklearn.externals.array_api_compat.common._helpers.is_torch_namespace (Namespace xp)
Returns True if `xp` is a PyTorch namespace.
This includes both PyTorch itself and the version wrapped by array-api-compat.
See Also
--------
array_namespace
is_numpy_namespace
is_cupy_namespace
is_ndonnx_namespace
is_dask_namespace
is_jax_namespace
is_pydata_sparse_namespace
is_array_api_strict_namespace
Definition at line 355 of file _helpers.py.
is_writeable_array()
bool sklearn.externals.array_api_compat.common._helpers.is_writeable_array (object x)
Return False if ``x.__setitem__`` is expected to raise; True otherwise.
Return False if `x` is not an array API compatible object.
Warning
-------
As there is no standard way to check if an array is writeable without actually
writing to it, this function blindly returns True for all unknown array types.
Definition at line 935 of file _helpers.py.
size() [1/3]
None sklearn.externals.array_api_compat.common._helpers.size (HasShape[Collection[None]] x)
Definition at line 899 of file _helpers.py.
size() [2/3]
int sklearn.externals.array_api_compat.common._helpers.size (HasShape[Collection[SupportsIndex]] x)
Definition at line 897 of file _helpers.py.
size() [3/3]
int | None sklearn.externals.array_api_compat.common._helpers.size (HasShape] x[Collection[SupportsIndex|None])
Return the total number of elements of x.
This is equivalent to `x.size` according to the `standard
<https://data-apis.org/array-api/latest/API_specification/generated/array_api.array.size.html>`__.
This helper is included because PyTorch defines `size` in an
:external+torch:meth:`incompatible way <torch.Tensor.size>`.
It also fixes dask.array's behaviour which returns nan for unknown sizes, whereas
the standard requires None.
Definition at line 901 of file _helpers.py.
to_device()
Array sklearn.externals.array_api_compat.common._helpers.to_device (Array x, Device device, * , int | Any | None stream = None)
Copy the array from the device on which it currently resides to the specified ``device``.
This is equivalent to `x.to_device(device, stream=stream)` according to
the `standard
<https://data-apis.org/array-api/latest/API_specification/generated/array_api.array.to_device.html>`__.
This helper is included because some array libraries do not have the
`to_device` method.
Parameters
----------
x: array
    array instance from an array API compatible library.
device: device
    a ``device`` object (see the `Device Support <https://data-apis.org/array-api/latest/design_topics/device_support.html>`__
    section of the array API specification).
stream: int | Any | None
    stream object to use during copy. In addition to the types supported
    in ``array.__dlpack__``, implementations may choose to support any
    library-specific stream object with the caveat that any code using
    such an object would not be portable.
Returns
-------
out: array
    an array with the same data and data type as ``x`` and located on the
    specified ``device``.
Notes
-----
For NumPy, this function effectively does nothing since the only supported
device is the CPU. For CuPy, this method supports CuPy CUDA
:external+cupy:class:`Device <cupy.cuda.Device>` and
:external+cupy:class:`Stream <cupy.cuda.Stream>` objects. For PyTorch,
this is the same as :external+torch:meth:`x.to(device) <torch.Tensor.to>`
(the ``stream`` argument is not supported in PyTorch).
See Also
--------
device : Hardware device the array data resides on.
Definition at line 813 of file _helpers.py.
References is_cupy_array(), is_dask_array(), is_jax_array(), is_numpy_array(), is_pydata_sparse_array(), and is_torch_array().
Variable Documentation
__all__
list sklearn.externals.array_api_compat.common._helpers.__all__ private
Initial value:
=  [
    "array_namespace",
    "device",
    "get_namespace",
    "is_array_api_obj",
    "is_array_api_strict_namespace",
    "is_cupy_array",
    "is_cupy_namespace",
    "is_dask_array",
    "is_dask_namespace",
    "is_jax_array",
    "is_jax_namespace",
    "is_numpy_array",
    "is_numpy_namespace",
    "is_torch_array",
    "is_torch_namespace",
    "is_ndonnx_array",
    "is_ndonnx_namespace",
    "is_pydata_sparse_array",
    "is_pydata_sparse_namespace",
    "is_writeable_array",
    "is_lazy_array",
    "size",
    "to_device",
]
Definition at line 1029 of file _helpers.py.
_all_ignore
list sklearn.externals.array_api_compat.common._helpers._all_ignore = ['lru_cache', 'sys', 'math', 'inspect', 'warnings'] protected
Definition at line 1055 of file _helpers.py.
_API_VERSIONS
Final sklearn.externals.array_api_compat.common._helpers._API_VERSIONS = _API_VERSIONS_OLD | frozenset({"2024.12"}) protected
Definition at line 62 of file _helpers.py.
_API_VERSIONS_OLD
Final sklearn.externals.array_api_compat.common._helpers._API_VERSIONS_OLD = frozenset({"2021.12", "2022.12", "2023.12"}) protected
Definition at line 61 of file _helpers.py.
_ArrayApiObj
tuple sklearn.externals.array_api_compat.common._helpers._ArrayApiObj protected
Initial value:
=  (
        npt.NDArray[Any]
        | da.Array
        | jax.Array
        | ndx.Array
        | sparse.SparseArray
        | torch.Tensor
        | SupportsArrayNamespace[Any]
        | _CupyArray
    )
Definition at line 50 of file _helpers.py.
_CupyArray
TypeAlias sklearn.externals.array_api_compat.common._helpers._CupyArray = Any protected
Definition at line 48 of file _helpers.py.
_DASK_DEVICE
sklearn.externals.array_api_compat.common._helpers._DASK_DEVICE = _dask_device() protected
Definition at line 690 of file _helpers.py.
_device
Device sklearn.externals.array_api_compat.common._helpers._device = device protected
Definition at line 768 of file _helpers.py.
_SizeT
sklearn.externals.array_api_compat.common._helpers._SizeT = TypeVar("_SizeT", bound = int | None) protected
Definition at line 45 of file _helpers.py.
_ZeroGradientArray
TypeAlias sklearn.externals.array_api_compat.common._helpers._ZeroGradientArray = npt.NDArray[np.void] protected
Definition at line 47 of file _helpers.py.
get_namespace
Namespace sklearn.externals.array_api_compat.common._helpers.get_namespace = array_namespace
Definition at line 657 of file _helpers.py.