Code Cloning Analysis: axisartist.floating_axes.FloatingAxesBase Class Reference
axisartist.floating_axes.FloatingAxesBase Class Reference
Public Member Functions
__init__ (self, *args, grid_helper, **kwargs)
clear (self)
adjust_axes_lim (self)
Public Attributes
transData
transAxes = False))
Protected Member Functions
_gen_axes_patch (self)
Detailed Description
Definition at line 236 of file floating_axes.py.
Constructor & Destructor Documentation
__init__()
axisartist.floating_axes.FloatingAxesBase.__init__ (self, * args, grid_helper, ** kwargs)
Definition at line 238 of file floating_axes.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_gen_axes_patch()
axisartist.floating_axes.FloatingAxesBase._gen_axes_patch (self) protected
Definition at line 243 of file floating_axes.py.
adjust_axes_lim()
axisartist.floating_axes.FloatingAxesBase.adjust_axes_lim (self)
Definition at line 264 of file floating_axes.py.
clear()
axisartist.floating_axes.FloatingAxesBase.clear (self)
Definition at line 250 of file floating_axes.py.
Referenced by matplotlib.projections.geo.AitoffAxes.InvertedAitoffTransform.inverted(), matplotlib.projections.geo.HammerAxes.InvertedHammerTransform.inverted(), matplotlib.projections.geo.LambertAxes.InvertedLambertTransform.inverted(), and matplotlib.projections.geo.MollweideAxes.InvertedMollweideTransform.inverted().
Member Data Documentation
transAxes
axisartist.floating_axes.FloatingAxesBase.transAxes = False))
Definition at line 259 of file floating_axes.py.
transData
axisartist.floating_axes.FloatingAxesBase.transData
Definition at line 254 of file floating_axes.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/mpl_toolkits/axisartist/floating_axes.py