Code Cloning Analysis: pandas.tests.dtypes.test_dtypes.TestIntervalDtype Class Reference
pandas.tests.dtypes.test_dtypes.TestIntervalDtype Class Reference
Public Member Functions
dtype (self)
test_hash_vs_equality (self, dtype)
test_construction (self, subtype)
test_construction_allows_closed_none (self, subtype)
test_closed_mismatch (self)
test_construction_generic (self, subtype)
test_construction_not_supported (self, subtype)
test_construction_errors (self, subtype)
test_closed_must_match (self)
test_closed_invalid (self)
test_construction_from_string (self, dtype)
test_construction_from_string_errors (self, string)
test_construction_from_string_error_subtype (self, string)
test_subclass (self)
test_is_dtype (self, dtype)
test_equality (self, dtype)
test_equality_generic (self, subtype)
test_name_repr (self, subtype)
test_name_repr_generic (self, subtype)
test_basic (self, dtype)
test_basic_dtype (self)
test_caching (self)
test_not_string (self)
test_unpickling_without_closed (self)
test_dont_keep_ref_after_del (self)
Public Member Functions inherited from pandas.tests.dtypes.test_dtypes.Base
test_hash (self, dtype)
test_equality_invalid (self, dtype)
test_numpy_informed (self, dtype)
test_pickle (self, dtype)
Detailed Description
Definition at line 581 of file test_dtypes.py.
Member Function Documentation
dtype()
pandas.tests.dtypes.test_dtypes.TestIntervalDtype.dtype (self)
Class level fixture of dtype for TestIntervalDtype
Definition at line 583 of file test_dtypes.py.
Referenced by pandas.core.arrays.base.ExtensionScalarOpsMixin._create_method(), scipy.sparse._index.IndexMixin._getcol(), pandas.core.generic.NDFrame._inplace_method(), scipy.sparse._index.IndexMixin._raise_on_1d_array_slice(), pandas.core.strings.object_array.ObjectStringArrayMixin._str_map(), numpy.matrixlib.defmatrix.matrix.H(), numpy.core.records.record.pprint(), pandas.core.frame.DataFrame.quantile(), and pandas.core.generic.NDFrame.rank().
test_basic()
pandas.tests.dtypes.test_dtypes.TestIntervalDtype.test_basic (self, dtype)
Definition at line 816 of file test_dtypes.py.
test_basic_dtype()
pandas.tests.dtypes.test_dtypes.TestIntervalDtype.test_basic_dtype (self)
Definition at line 831 of file test_dtypes.py.
test_caching()
pandas.tests.dtypes.test_dtypes.TestIntervalDtype.test_caching (self)
Definition at line 847 of file test_dtypes.py.
test_closed_invalid()
pandas.tests.dtypes.test_dtypes.TestIntervalDtype.test_closed_invalid (self)
Definition at line 683 of file test_dtypes.py.
test_closed_mismatch()
pandas.tests.dtypes.test_dtypes.TestIntervalDtype.test_closed_mismatch (self)
Definition at line 634 of file test_dtypes.py.
test_closed_must_match()
pandas.tests.dtypes.test_dtypes.TestIntervalDtype.test_closed_must_match (self)
Definition at line 675 of file test_dtypes.py.
test_construction()
pandas.tests.dtypes.test_dtypes.TestIntervalDtype.test_construction (self, subtype)
Definition at line 618 of file test_dtypes.py.
test_construction_allows_closed_none()
pandas.tests.dtypes.test_dtypes.TestIntervalDtype.test_construction_allows_closed_none (self, subtype)
Definition at line 628 of file test_dtypes.py.
test_construction_errors()
pandas.tests.dtypes.test_dtypes.TestIntervalDtype.test_construction_errors (self, subtype)
Definition at line 670 of file test_dtypes.py.
test_construction_from_string()
pandas.tests.dtypes.test_dtypes.TestIntervalDtype.test_construction_from_string (self, dtype)
Definition at line 687 of file test_dtypes.py.
test_construction_from_string_error_subtype()
pandas.tests.dtypes.test_dtypes.TestIntervalDtype.test_construction_from_string_error_subtype (self, string)
Definition at line 702 of file test_dtypes.py.
test_construction_from_string_errors()
pandas.tests.dtypes.test_dtypes.TestIntervalDtype.test_construction_from_string_errors (self, string)
Definition at line 694 of file test_dtypes.py.
test_construction_generic()
pandas.tests.dtypes.test_dtypes.TestIntervalDtype.test_construction_generic (self, subtype)
Definition at line 640 of file test_dtypes.py.
test_construction_not_supported()
pandas.tests.dtypes.test_dtypes.TestIntervalDtype.test_construction_not_supported (self, subtype)
Definition at line 660 of file test_dtypes.py.
test_dont_keep_ref_after_del()
pandas.tests.dtypes.test_dtypes.TestIntervalDtype.test_dont_keep_ref_after_del (self)
Definition at line 872 of file test_dtypes.py.
test_equality()
pandas.tests.dtypes.test_dtypes.TestIntervalDtype.test_equality (self, dtype)
Definition at line 740 of file test_dtypes.py.
test_equality_generic()
pandas.tests.dtypes.test_dtypes.TestIntervalDtype.test_equality_generic (self, subtype)
Definition at line 782 of file test_dtypes.py.
test_hash_vs_equality()
pandas.tests.dtypes.test_dtypes.TestIntervalDtype.test_hash_vs_equality (self, dtype)
Definition at line 589 of file test_dtypes.py.
test_is_dtype()
pandas.tests.dtypes.test_dtypes.TestIntervalDtype.test_is_dtype (self, dtype)
Definition at line 720 of file test_dtypes.py.
test_name_repr()
pandas.tests.dtypes.test_dtypes.TestIntervalDtype.test_name_repr (self, subtype)
Definition at line 801 of file test_dtypes.py.
test_name_repr_generic()
pandas.tests.dtypes.test_dtypes.TestIntervalDtype.test_name_repr_generic (self, subtype)
Definition at line 810 of file test_dtypes.py.
test_not_string()
pandas.tests.dtypes.test_dtypes.TestIntervalDtype.test_not_string (self)
Definition at line 860 of file test_dtypes.py.
test_subclass()
pandas.tests.dtypes.test_dtypes.TestIntervalDtype.test_subclass (self)
Definition at line 713 of file test_dtypes.py.
test_unpickling_without_closed()
pandas.tests.dtypes.test_dtypes.TestIntervalDtype.test_unpickling_without_closed (self)
Definition at line 864 of file test_dtypes.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/tests/dtypes/test_dtypes.py