Code Cloning Analysis: pandas.io.common._IOWrapper Class Reference
pandas.io.common._IOWrapper Class Reference
Public Member Functions
None __init__ (self, BaseBuffer buffer)
__getattr__ (self, str name)
bool readable (self)
bool seekable (self)
bool writable (self)
Public Attributes
buffer = buffer
Detailed Description
Definition at line 1059 of file common.py.
Constructor & Destructor Documentation
__init__()
None pandas.io.common._IOWrapper.__init__ (self, BaseBuffer buffer)
Definition at line 1066 of file common.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__getattr__()
pandas.io.common._IOWrapper.__getattr__ (self, str name)
Definition at line 1069 of file common.py.
readable()
bool pandas.io.common._IOWrapper.readable (self)
Definition at line 1072 of file common.py.
seekable()
bool pandas.io.common._IOWrapper.seekable (self)
Definition at line 1077 of file common.py.
writable()
bool pandas.io.common._IOWrapper.writable (self)
Definition at line 1082 of file common.py.
Member Data Documentation
buffer
pandas.io.common._IOWrapper.buffer = buffer
Definition at line 1067 of file common.py.
Referenced by fontTools.pens.freetypePen.FreeTypePen.array(), pandas.io.parsers.python_parser.FixedWidthReader.get_rows(), and fontTools.pens.freetypePen.FreeTypePen.image().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/io/common.py