Code Cloning Analysis: second_prompt Namespace Reference
second_prompt Namespace Reference
Classes
class Confidence
Defines the Confidence class, which is used to determine the structured ouput.
Functions
safe_parse_response (response)
Translates the given response from the model into the proper dictionary format.
ensemble_assessment (code1, code2, model_name, prompt, n=3)
Performs multiple assessments and aggregates predictions using voting.
determine_similarity (results)
rag_similarity_assessment (code1, code2, model_name, prompt)
Sends a prompt to the LLM to classify clone type and score similarities.
Variables
str DATA_DIR = "./data/data"
Path to the directory containing code files for similarity comparison.
str PAIRS_CSV = "./pairs.csv"
CSV file containing file pairs to compare.
str GROUND_TRUTH_CSV = "./ground_truth.csv"
CSV file containing ground truth similarity labels for file pairs.
list LLMS
List of model names to use for clone detection.
list PROMPTS
The first prompt we tested on.
pairs_df = pd.read_csv(PAIRS_CSV)
DataFrame of file pairs to compare.
ground_truth_df = pd.read_csv(GROUND_TRUTH_CSV)
DataFrame containing ground truth similarity labels.
ground_truth_map = dict(zip(ground_truth_df['pair-id'], ground_truth_df['similar']))
Dictionary mapping pair IDs to binary similarity values.
dict results_by_prompt = {i: {'truth': [], 'preds': []} for i in range(len(PROMPTS))}
Executes evaluation over prompts and saves results and metrics.
str output = f"./results/prompt_second_results_{LLMS[0]}_iteration_{iteration}.csv"
newline
writer = csv.writer(outfile)
file1_path = os.path.join(DATA_DIR, row['file1'])
file2_path = os.path.join(DATA_DIR, row['file2'])
pair_id = row['pair-id']
encoding
errors
code1 = f1.read()
code2 = f2.read()
ground_truth_sim = ground_truth_map.get(pair_id, "Unknown")
results
predicted_type
predicted_sim
model_name
prompt
n
str metrics_output = f'./results/prompt_second_{LLMS[0]}_iteration_{iteration}.txt'
Calculate and write evaluation metrics for the threshold.
dict truth = results_by_prompt[prompt_id]['truth']
dict preds = results_by_prompt[prompt_id]['preds']
acc = accuracy_score(truth, preds)
prec = precision_score(truth, preds, zero_division=0)
rec = recall_score(truth, preds, zero_division=0)
f1s = f1_score(truth, preds, zero_division=0)
mse = mean_squared_error(truth, preds, zero_division=0)
file
Function Documentation
determine_similarity()
second_prompt.determine_similarity (results)
Definition at line 160 of file second_prompt.py.
ensemble_assessment()
second_prompt.ensemble_assessment (code1, code2, model_name, thr, n = 3)
Performs multiple assessments and aggregates predictions using voting.
Parameters
code1 First code string.
code2 Second code string.
model_name The name of the LLM model to use.
thr Threshold for similarity.
n Number of repeated assessments for ensemble.
Returns
Tuple of (average type scores, majority predicted type, majority binary similarity).
Definition at line 115 of file second_prompt.py.
References rag_similarity_assessment().
rag_similarity_assessment()
second_prompt.rag_similarity_assessment (code1, code2, model_name, thr)
Sends a prompt to the LLM to classify clone type and score similarities.
Parameters
code1 First code snippet to evaluate.
code2 Second code snippet to evaluate.
model_name Name of the language model to query.
thr Threshold for determining clone similarity.
Returns
Tuple of (type score dictionary, predicted type, binary similarity).
Definition at line 177 of file second_prompt.py.
References safe_parse_response().
Referenced by ensemble_assessment().
safe_parse_response()
second_prompt.safe_parse_response (response)
Translates the given response from the model into the proper dictionary format.
Parameters
response The RAG output.
Definition at line 86 of file second_prompt.py.
Referenced by rag_similarity_assessment().
Variable Documentation
acc
second_prompt.acc = accuracy_score(truth, preds)
Definition at line 243 of file second_prompt.py.
code1
second_prompt.code1 = f1.read()
Definition at line 216 of file second_prompt.py.
code2
second_prompt.code2 = f2.read()
Definition at line 217 of file second_prompt.py.
DATA_DIR
str second_prompt.DATA_DIR = "./data/data"
Path to the directory containing code files for similarity comparison.
Definition at line 25 of file second_prompt.py.
encoding
second_prompt.encoding
Definition at line 214 of file second_prompt.py.
errors
second_prompt.errors
Definition at line 214 of file second_prompt.py.
f1s
second_prompt.f1s = f1_score(truth, preds, zero_division=0)
Definition at line 246 of file second_prompt.py.
file
second_prompt.file
Definition at line 248 of file second_prompt.py.
file1_path
second_prompt.file1_path = os.path.join(DATA_DIR, row['file1'])
Definition at line 210 of file second_prompt.py.
file2_path
second_prompt.file2_path = os.path.join(DATA_DIR, row['file2'])
Definition at line 211 of file second_prompt.py.
GROUND_TRUTH_CSV
str second_prompt.GROUND_TRUTH_CSV = "./ground_truth.csv"
CSV file containing ground truth similarity labels for file pairs.
Definition at line 33 of file second_prompt.py.
ground_truth_df
second_prompt.ground_truth_df = pd.read_csv(GROUND_TRUTH_CSV)
DataFrame containing ground truth similarity labels.
Definition at line 76 of file second_prompt.py.
ground_truth_map
second_prompt.ground_truth_map = dict(zip(ground_truth_df['pair-id'], ground_truth_df['similar']))
Dictionary mapping pair IDs to binary similarity values.
Definition at line 80 of file second_prompt.py.
ground_truth_sim
second_prompt.ground_truth_sim = ground_truth_map.get(pair_id, "Unknown")
Definition at line 221 of file second_prompt.py.
LLMS
list second_prompt.LLMS
Initial value:
=  [
    "llama3.1:latest"
]
List of model names to use for clone detection.
Definition at line 37 of file second_prompt.py.
metrics_output
str second_prompt.metrics_output = f'./results/prompt_second_{LLMS[0]}_iteration_{iteration}.txt'
Calculate and write evaluation metrics for the threshold.
Definition at line 237 of file second_prompt.py.
model_name
second_prompt.model_name
Definition at line 226 of file second_prompt.py.
mse
second_prompt.mse = mean_squared_error(truth, preds, zero_division=0)
Definition at line 247 of file second_prompt.py.
n
second_prompt.n
Definition at line 226 of file second_prompt.py.
newline
second_prompt.newline
Definition at line 201 of file second_prompt.py.
output
str second_prompt.output = f"./results/prompt_second_results_{LLMS[0]}_iteration_{iteration}.csv"
Definition at line 200 of file second_prompt.py.
pair_id
second_prompt.pair_id = row['pair-id']
Definition at line 212 of file second_prompt.py.
PAIRS_CSV
str second_prompt.PAIRS_CSV = "./pairs.csv"
CSV file containing file pairs to compare.
Definition at line 29 of file second_prompt.py.
pairs_df
second_prompt.pairs_df = pd.read_csv(PAIRS_CSV)
DataFrame of file pairs to compare.
Definition at line 72 of file second_prompt.py.
prec
second_prompt.prec = precision_score(truth, preds, zero_division=0)
Definition at line 244 of file second_prompt.py.
predicted_sim
second_prompt.predicted_sim
Definition at line 226 of file second_prompt.py.
predicted_type
second_prompt.predicted_type
Definition at line 226 of file second_prompt.py.
preds
dict second_prompt.preds = results_by_prompt[prompt_id]['preds']
Definition at line 241 of file second_prompt.py.
prompt
second_prompt.prompt
Definition at line 226 of file second_prompt.py.
PROMPTS
list second_prompt.PROMPTS
Initial value:
=  [
    # Prompt 2
]
The first prompt we tested on.
Definition at line 50 of file second_prompt.py.
rec
second_prompt.rec = recall_score(truth, preds, zero_division=0)
Definition at line 245 of file second_prompt.py.
results
second_prompt.results
Definition at line 226 of file second_prompt.py.
results_by_prompt
dict second_prompt.results_by_prompt = {i: {'truth': [], 'preds': []} for i in range(len(PROMPTS))}
Executes evaluation over prompts and saves results and metrics.
Definition at line 195 of file second_prompt.py.
truth
dict second_prompt.truth = results_by_prompt[prompt_id]['truth']
Definition at line 240 of file second_prompt.py.
writer
second_prompt.writer = csv.writer(outfile)
Definition at line 202 of file second_prompt.py.