Code Cloning Analysis: numpy.f2py.capi_maps Namespace Reference
numpy.f2py.capi_maps Namespace Reference
Functions
load_f2cmap_file (f2cmap_file)
getctype (var)
f2cexpr (expr)
getstrlength (var)
getarrdims (a, var, verbose=0)
getpydocsign (a, var)
getarrdocsign (a, var)
getinit (a, var)
get_elsize (var)
sign2map (a, var)
routsign2map (rout)
modsign2map (m)
cb_sign2map (a, var, index=None)
cb_routsign2map (rout, um)
common_sign2map (a, var)
Variables
f2py_version = __version__.version
list __all__
list depargs = []
dict lcb_map = {}
dict lcb2_map = {}
dict c2py_map
dict c2capi_map
dict c2pycode_map
dict c2buildvalue_map
dict f2cmap_all
_
f2cmap_default = copy.deepcopy(f2cmap_all)
list f2cmap_mapped = []
dict cformat_map
Detailed Description
Copyright 1999 -- 2011 Pearu Peterson all rights reserved.
Copyright 2011 -- present NumPy Developers.
Permission to use, modify, and distribute this software is given under the
terms of the NumPy License.
NO WARRANTY IS EXPRESSED OR IMPLIED.  USE AT YOUR OWN RISK.
Function Documentation
cb_routsign2map()
numpy.f2py.capi_maps.cb_routsign2map (rout, um)
name,begintitle,endtitle,argname
ctype,rctype,maxnofargs,nofoptargs,returncptr
Definition at line 717 of file capi_maps.py.
References getctype().
cb_sign2map()
numpy.f2py.capi_maps.cb_sign2map (a, var, index = None)
Definition at line 699 of file capi_maps.py.
common_sign2map()
numpy.f2py.capi_maps.common_sign2map (a, var)
Definition at line 799 of file capi_maps.py.
f2cexpr()
numpy.f2py.capi_maps.f2cexpr (expr)
Rewrite Fortran expression as f2py supported C expression.
Due to the lack of a proper expression parser in f2py, this
function uses a heuristic approach that assumes that Fortran
arithmetic expressions are valid C arithmetic expressions when
mapping Fortran function calls to the corresponding C function/CPP
macros calls.
Definition at line 238 of file capi_maps.py.
References f2cexpr(), getctype(), and numpy.lib.shape_base.split().
Referenced by f2cexpr().
get_elsize()
numpy.f2py.capi_maps.get_elsize (var)
Definition at line 469 of file capi_maps.py.
getarrdims()
numpy.f2py.capi_maps.getarrdims (a, var, verbose = 0)
Definition at line 281 of file capi_maps.py.
getarrdocsign()
numpy.f2py.capi_maps.getarrdocsign (a, var)
Definition at line 416 of file capi_maps.py.
getctype()
numpy.f2py.capi_maps.getctype (var)
Determines C type
Definition at line 187 of file capi_maps.py.
References getctype().
Referenced by cb_routsign2map(), f2cexpr(), getctype(), modsign2map(), routsign2map(), and sign2map().
getinit()
numpy.f2py.capi_maps.getinit (a, var)
Definition at line 434 of file capi_maps.py.
getpydocsign()
numpy.f2py.capi_maps.getpydocsign (a, var)
Definition at line 342 of file capi_maps.py.
getstrlength()
numpy.f2py.capi_maps.getstrlength (var)
Definition at line 253 of file capi_maps.py.
load_f2cmap_file()
numpy.f2py.capi_maps.load_f2cmap_file (f2cmap_file)
Definition at line 138 of file capi_maps.py.
modsign2map()
numpy.f2py.capi_maps.modsign2map (m)
modulename
Definition at line 670 of file capi_maps.py.
References getctype().
routsign2map()
numpy.f2py.capi_maps.routsign2map (rout)
name,NAME,begintitle,endtitle
rname,ctype,rformat
routdebugshowvalue
Definition at line 589 of file capi_maps.py.
References getctype().
sign2map()
numpy.f2py.capi_maps.sign2map (a, var)
varname,ctype,atype
init,init.r,init.i,pytype
vardebuginfo,vardebugshowvalue,varshowvalue
varrformat
intent
Definition at line 483 of file capi_maps.py.
References getctype(), and numpy.lib.shape_base.split().
Variable Documentation
_
numpy.f2py.capi_maps._ protected
Definition at line 132 of file capi_maps.py.
__all__
list numpy.f2py.capi_maps.__all__ private
Initial value:
=  [
    'getctype', 'getstrlength', 'getarrdims', 'getpydocsign',
    'getarrdocsign', 'getinit', 'sign2map', 'routsign2map', 'modsign2map',
    'cb_sign2map', 'cb_routsign2map', 'common_sign2map', 'process_f2cmap_dict'
]
Definition at line 24 of file capi_maps.py.
c2buildvalue_map
dict numpy.f2py.capi_maps.c2buildvalue_map
Initial value:
=  {'double': 'd',
                    'float': 'f',
                    'char': 'b',
                    'signed_char': 'b',
                    'short': 'h',
                    'int': 'i',
                    'long': 'l',
                    'long_long': 'L',
                    'complex_float': 'N',
                    'complex_double': 'N',
                    'complex_long_double': 'N',
                    'string': 'y',
                    'character': 'c'}
Definition at line 96 of file capi_maps.py.
c2capi_map
dict numpy.f2py.capi_maps.c2capi_map
Initial value:
=  {'double': 'NPY_DOUBLE',
                'float': 'NPY_FLOAT',
                'long_double': 'NPY_LONGDOUBLE',
                'char': 'NPY_BYTE',
                'unsigned_char': 'NPY_UBYTE',
                'signed_char': 'NPY_BYTE',
                'short': 'NPY_SHORT',
                'unsigned_short': 'NPY_USHORT',
                'int': 'NPY_INT',
                'unsigned': 'NPY_UINT',
                'long': 'NPY_LONG',
                'unsigned_long': 'NPY_ULONG',
                'long_long': 'NPY_LONGLONG',
                'unsigned_long_long': 'NPY_ULONGLONG',
                'complex_float': 'NPY_CFLOAT',
                'complex_double': 'NPY_CDOUBLE',
                'complex_long_double': 'NPY_CDOUBLE',
                'string': 'NPY_STRING',
                'character': 'NPY_STRING'}
Definition at line 55 of file capi_maps.py.
c2py_map
dict numpy.f2py.capi_maps.c2py_map
Initial value:
=  {'double': 'float',
            'float': 'float',                          # forced casting
            'long_double': 'float',                    # forced casting
            'char': 'int',                             # forced casting
            'signed_char': 'int',                      # forced casting
            'unsigned_char': 'int',                    # forced casting
            'short': 'int',                            # forced casting
            'unsigned_short': 'int',                   # forced casting
            'int': 'int',                              # forced casting
            'long': 'int',
            'long_long': 'long',
            'unsigned': 'int',                         # forced casting
            'complex_float': 'complex',                # forced casting
            'complex_double': 'complex',
            'complex_long_double': 'complex',          # forced casting
            'string': 'string',
            'character': 'bytes',
            }
Definition at line 36 of file capi_maps.py.
c2pycode_map
dict numpy.f2py.capi_maps.c2pycode_map
Initial value:
=  {'double': 'd',
                'float': 'f',
                'long_double': 'g',
                'char': 'b',
                'unsigned_char': 'B',
                'signed_char': 'b',
                'short': 'h',
                'unsigned_short': 'H',
                'int': 'i',
                'unsigned': 'I',
                'long': 'l',
                'unsigned_long': 'L',
                'long_long': 'q',
                'unsigned_long_long': 'Q',
                'complex_float': 'F',
                'complex_double': 'D',
                'complex_long_double': 'G',
                'string': 'S',
                'character': 'c'}
Definition at line 75 of file capi_maps.py.
cformat_map
dict numpy.f2py.capi_maps.cformat_map
Initial value:
=  {'double': '%g',
               'float': '%g',
               'long_double': '%Lg',
               'char': '%d',
               'signed_char': '%d',
               'unsigned_char': '%hhu',
               'short': '%hd',
               'unsigned_short': '%hu',
               'int': '%d',
               'unsigned': '%u',
               'long': '%ld',
               'unsigned_long': '%lu',
               'long_long': '%ld',
               'complex_float': '(%g,%g)',
               'complex_double': '(%g,%g)',
               'complex_long_double': '(%Lg,%Lg)',
               'string': '\\"%s\\"',
               'character': "'%c'",
               }
Definition at line 164 of file capi_maps.py.
depargs
list numpy.f2py.capi_maps.depargs = []
Definition at line 31 of file capi_maps.py.
f2cmap_all
numpy.f2py.capi_maps.f2cmap_all
Initial value:
=  {'real': {'': 'float', '4': 'float', '8': 'double',
                       '12': 'long_double', '16': 'long_double'},
              'integer': {'': 'int', '1': 'signed_char', '2': 'short',
                          '4': 'int', '8': 'long_long',
                          '-1': 'unsigned_char', '-2': 'unsigned_short',
                          '-4': 'unsigned', '-8': 'unsigned_long_long'},
              'complex': {'': 'complex_float', '8': 'complex_float',
                          '16': 'complex_double', '24': 'complex_long_double',
                          '32': 'complex_long_double'},
              'complexkind': {'': 'complex_float', '4': 'complex_float',
                              '8': 'complex_double', '12': 'complex_long_double',
                              '16': 'complex_long_double'},
              'logical': {'': 'int', '1': 'char', '2': 'short', '4': 'int',
                          '8': 'long_long'},
              'double complex': {'': 'complex_double'},
              'double precision': {'': 'double'},
              'byte': {'': 'char'},
              }
Definition at line 110 of file capi_maps.py.
f2cmap_default
numpy.f2py.capi_maps.f2cmap_default = copy.deepcopy(f2cmap_all)
Definition at line 134 of file capi_maps.py.
f2cmap_mapped
list numpy.f2py.capi_maps.f2cmap_mapped = []
Definition at line 136 of file capi_maps.py.
f2py_version
numpy.f2py.capi_maps.f2py_version = __version__.version
Definition at line 10 of file capi_maps.py.
lcb2_map
dict numpy.f2py.capi_maps.lcb2_map = {}
Definition at line 33 of file capi_maps.py.
lcb_map
dict numpy.f2py.capi_maps.lcb_map = {}
Definition at line 32 of file capi_maps.py.