Code Cloning Analysis: fontTools.otlLib.builder.ChainContextPosBuilder Class Reference
fontTools.otlLib.builder.ChainContextPosBuilder Class Reference
Public Member Functions
__init__ (self, font, location)
find_chainable_single_pos (self, lookups, glyphs, value)
Public Member Functions inherited from fontTools.otlLib.builder.ChainContextualBuilder
equals (self, other)
rulesets (self)
getCompiledSize_ (self, subtables)
build (self)
buildFormat1Subtable (self, ruleset, chaining=True)
buildFormat2Subtable (self, ruleset, classdefs, chaining=True)
buildFormat3Subtable (self, rule, chaining=True)
buildLookupList (self, rule, st)
add_subtable_break (self, location)
newSubtable_ (self, chaining=True)
ruleSetAttr_ (self, format=1, chaining=True)
ruleAttr_ (self, format=1, chaining=True)
newRuleSet_ (self, format=1, chaining=True)
newRule_ (self, format=1, chaining=True)
attachSubtableWithCount_ (self, st, subtable_name, count_name, existing=None, index=None, chaining=False)
newLookupRecord_ (self, st)
Public Member Functions inherited from fontTools.otlLib.builder.LookupBuilder
__init__ (self, font, location, table, lookup_type, extension=False)
promote_lookup_type (self, is_named_lookup)
inferGlyphClasses (self)
getAlternateGlyphs (self)
buildLookup_ (self, subtables)
buildMarkClasses_ (self, marks)
setBacktrackCoverage_ (self, prefix, subtable)
setLookAheadCoverage_ (self, suffix, subtable)
setInputCoverage_ (self, glyphs, subtable)
setCoverage_ (self, glyphs, subtable)
build_subst_subtables (self, mapping, klass)
bool can_add_mapping (self, _mapping)
Additional Inherited Members
Public Attributes inherited from fontTools.otlLib.builder.ChainContextualBuilder
rules = other.rules
str subtable_type = "Pos":
Public Attributes inherited from fontTools.otlLib.builder.LookupBuilder
font = font
glyphMap = font.getReverseGlyphMap()
location = location
table
lookup_type = table, lookup_type
int lookupflag = 0
markFilterSet = None
lookup_index = None
extension = extension
Static Public Attributes inherited from fontTools.otlLib.builder.LookupBuilder
str SUBTABLE_BREAK_ = "SUBTABLE_BREAK"
Detailed Description
Builds a Chained Contextual Positioning (GPOS8) lookup.
Users are expected to manually add rules to the ``rules`` attribute after
the object has been initialized, e.g.::
    # pos [A B] [C D] x' lookup lu1 y' z' lookup lu2 E;
    prefix  = [ ["A", "B"], ["C", "D"] ]
    suffix  = [ ["E"] ]
    glyphs  = [ ["x"], ["y"], ["z"] ]
    lookups = [ [lu1], None,  [lu2] ]
    builder.rules.append( (prefix, glyphs, suffix, lookups) )
Attributes:
    font (``fontTools.TTLib.TTFont``): A font object.
    location: A string or tuple representing the location in the original
        source which produced this lookup.
    rules: A list of tuples representing the rules in this lookup.
    lookupflag (int): The lookup's flag
    markFilterSet: Either ``None`` if no mark filtering set is used, or
        an integer representing the filtering set to be used for this
        lookup. If a mark filtering set is provided,
        `LOOKUP_FLAG_USE_MARK_FILTERING_SET` will be set on the lookup's
        flags.
Definition at line 726 of file builder.py.
Constructor & Destructor Documentation
__init__()
fontTools.otlLib.builder.ChainContextPosBuilder.__init__ (self, font, location)
Definition at line 753 of file builder.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
find_chainable_single_pos()
fontTools.otlLib.builder.ChainContextPosBuilder.find_chainable_single_pos (self, lookups, glyphs, value)
Helper for add_single_pos_chained_()
Definition at line 758 of file builder.py.
References fontTools.otlLib.builder.LookupBuilder.SUBTABLE_BREAK_.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/otlLib/builder.py