Code Cloning Analysis: sklearn.metrics._scorer Namespace Reference
sklearn.metrics._scorer Namespace Reference
Classes
class _BaseScorer
class _CurveScorer
class _MultimetricScorer
class _PassthroughScorer
class _Scorer
Functions
_cached_call (cache, estimator, response_method, *args, **kwargs)
get_scorer (scoring)
_check_multimetric_scoring (estimator, scoring)
_get_response_method_name (response_method)
make_scorer (score_func, *, response_method="default", greater_is_better=True, **kwargs)
positive_likelihood_ratio (y_true, y_pred)
negative_likelihood_ratio (y_true, y_pred)
get_scorer_names ()
check_scoring (estimator=None, scoring=None, *, allow_none=False, raise_exc=True)
_threshold_scores_to_class_labels (y_score, threshold, classes, pos_label)
Variables
explained_variance_scorer = make_scorer(explained_variance_score)
r2_scorer = make_scorer(r2_score)
neg_max_error_scorer = make_scorer(max_error, greater_is_better=False)
max_error_scorer = make_scorer(max_error, greater_is_better=False)
tuple deprecation_msg
_deprecation_msg
neg_mean_squared_error_scorer = make_scorer(mean_squared_error, greater_is_better=False)
neg_mean_squared_log_error_scorer
neg_mean_absolute_error_scorer
neg_mean_absolute_percentage_error_scorer
neg_median_absolute_error_scorer
neg_root_mean_squared_error_scorer
neg_root_mean_squared_log_error_scorer
neg_mean_poisson_deviance_scorer
neg_mean_gamma_deviance_scorer
d2_absolute_error_scorer = make_scorer(d2_absolute_error_score)
accuracy_scorer = make_scorer(accuracy_score)
balanced_accuracy_scorer = make_scorer(balanced_accuracy_score)
matthews_corrcoef_scorer = make_scorer(matthews_corrcoef)
positive_likelihood_ratio_scorer = make_scorer(positive_likelihood_ratio)
neg_negative_likelihood_ratio_scorer
top_k_accuracy_scorer
roc_auc_scorer
average_precision_scorer
roc_auc_ovo_scorer
roc_auc_ovo_weighted_scorer
roc_auc_ovr_scorer
roc_auc_ovr_weighted_scorer
neg_log_loss_scorer
neg_brier_score_scorer
brier_score_loss_scorer
adjusted_rand_scorer = make_scorer(adjusted_rand_score)
rand_scorer = make_scorer(rand_score)
homogeneity_scorer = make_scorer(homogeneity_score)
completeness_scorer = make_scorer(completeness_score)
v_measure_scorer = make_scorer(v_measure_score)
mutual_info_scorer = make_scorer(mutual_info_score)
adjusted_mutual_info_scorer = make_scorer(adjusted_mutual_info_score)
normalized_mutual_info_scorer = make_scorer(normalized_mutual_info_score)
fowlkes_mallows_scorer = make_scorer(fowlkes_mallows_score)
_SCORERS
metric
average
str qualified_name = "{0}_{1}".format(name, average)
pos_label
None
Detailed Description
The :mod:`sklearn.metrics.scorer` submodule implements a flexible
interface for model selection and evaluation using
arbitrary score functions.
A scorer object is a callable that can be passed to
:class:`~sklearn.model_selection.GridSearchCV` or
:func:`sklearn.model_selection.cross_val_score` as the ``scoring``
parameter, to specify how a model should be evaluated.
The signature of the call is ``(estimator, X, y)`` where ``estimator``
is the model to be evaluated, ``X`` is the test data and ``y`` is the
ground truth labeling (or ``None`` in the case of unsupervised models).
Function Documentation
_cached_call()
sklearn.metrics._scorer._cached_call (cache, estimator, response_method, * args, ** kwargs) protected
Call estimator with method and args and kwargs.
Definition at line 85 of file _scorer.py.
_check_multimetric_scoring()
sklearn.metrics._scorer._check_multimetric_scoring (estimator, scoring) protected
Check the scoring parameter in cases when multiple metrics are allowed.
In addition, multimetric scoring leverages a caching mechanism to not call the same
estimator response method multiple times. Hence, the scorer is modified to only use
a single response method given a list of response methods and the estimator.
Parameters
----------
estimator : sklearn estimator instance
    The estimator for which the scoring will be applied.
scoring : list, tuple or dict
    Strategy to evaluate the performance of the cross-validated model on
    the test set.
    The possibilities are:
    - a list or tuple of unique strings;
    - a callable returning a dictionary where they keys are the metric
      names and the values are the metric scores;
    - a dictionary with metric names as keys and callables a values.
    See :ref:`multimetric_grid_search` for an example.
Returns
-------
scorers_dict : dict
    A dict mapping each scorer name to its validated scorer.
Definition at line 543 of file _scorer.py.
References check_scoring().
Referenced by check_scoring().
_get_response_method_name()
sklearn.metrics._scorer._get_response_method_name (response_method) protected
Definition at line 632 of file _scorer.py.
_threshold_scores_to_class_labels()
sklearn.metrics._scorer._threshold_scores_to_class_labels (y_score, threshold, classes, pos_label) protected
Threshold `y_score` and return the associated class labels.
Definition at line 1052 of file _scorer.py.
Referenced by sklearn.metrics._scorer._CurveScorer._score().
check_scoring()
sklearn.metrics._scorer.check_scoring (estimator = None, scoring = None, * , allow_none = False, raise_exc = True)
Determine scorer from user options.
A TypeError will be thrown if the estimator cannot be scored.
Parameters
----------
estimator : estimator object implementing 'fit' or None, default=None
    The object to use to fit the data. If `None`, then this function may error
    depending on `allow_none`.
scoring : str, callable, list, tuple, set, or dict, default=None
    Scorer to use. If `scoring` represents a single score, one can use:
    - a single string (see :ref:`scoring_string_names`);
    - a callable (see :ref:`scoring_callable`) that returns a single value;
    - `None`, the `estimator`'s
      :ref:`default evaluation criterion <scoring_api_overview>` is used.
    If `scoring` represents multiple scores, one can use:
    - a list, tuple or set of unique strings;
    - a callable returning a dictionary where the keys are the metric names and the
      values are the metric scorers;
    - a dictionary with metric names as keys and callables a values. The callables
      need to have the signature `callable(estimator, X, y)`.
allow_none : bool, default=False
    Whether to return None or raise an error if no `scoring` is specified and the
    estimator has no `score` method.
raise_exc : bool, default=True
    Whether to raise an exception (if a subset of the scorers in multimetric scoring
    fails) or to return an error code.
    - If set to `True`, raises the failing scorer's exception.
    - If set to `False`, a formatted string of the exception details is passed as
      result of the failing scorer(s).
    This applies if `scoring` is list, tuple, set, or dict. Ignored if `scoring` is
    a str or a callable.
    .. versionadded:: 1.6
Returns
-------
scoring : callable
    A scorer callable object / function with signature ``scorer(estimator, X, y)``.
Examples
--------
>>> from sklearn.datasets import load_iris
>>> from sklearn.metrics import check_scoring
>>> from sklearn.tree import DecisionTreeClassifier
>>> X, y = load_iris(return_X_y=True)
>>> classifier = DecisionTreeClassifier(max_depth=2).fit(X, y)
>>> scorer = check_scoring(classifier, scoring='accuracy')
>>> scorer(classifier, X, y)
0.96...
>>> from sklearn.metrics import make_scorer, accuracy_score, mean_squared_log_error
>>> X, y = load_iris(return_X_y=True)
>>> y *= -1
>>> clf = DecisionTreeClassifier().fit(X, y)
>>> scoring = {
...     "accuracy": make_scorer(accuracy_score),
...     "mean_squared_log_error": make_scorer(mean_squared_log_error),
... }
>>> scoring_call = check_scoring(estimator=clf, scoring=scoring, raise_exc=False)
>>> scores = scoring_call(clf, X, y)
>>> scores
{'accuracy': 1.0, 'mean_squared_log_error': 'Traceback ...'}
Definition at line 945 of file _scorer.py.
References _check_multimetric_scoring(), and get_scorer().
Referenced by _check_multimetric_scoring().
get_scorer()
sklearn.metrics._scorer.get_scorer (scoring)
Get a scorer from string.
Read more in the :ref:`User Guide <scoring_parameter>`.
:func:`~sklearn.metrics.get_scorer_names` can be used to retrieve the names
of all available scorers.
Parameters
----------
scoring : str, callable or None
    Scoring method as string. If callable it is returned as is.
    If None, returns None.
Returns
-------
scorer : callable
    The scorer.
Notes
-----
When passed a string, this function always returns a copy of the scorer
object. Calling `get_scorer` twice for the same scorer results in two
separate scorer objects.
Examples
--------
>>> import numpy as np
>>> from sklearn.dummy import DummyClassifier
>>> from sklearn.metrics import get_scorer
>>> X = np.reshape([0, 1, -1, -0.5, 2], (-1, 1))
>>> y = np.array([0, 1, 1, 0, 1])
>>> classifier = DummyClassifier(strategy="constant", constant=0).fit(X, y)
>>> accuracy = get_scorer("accuracy")
>>> accuracy(classifier, X, y)
0.4
Definition at line 417 of file _scorer.py.
Referenced by check_scoring().
get_scorer_names()
sklearn.metrics._scorer.get_scorer_names ()
Get the names of all available scorers.
These names can be passed to :func:`~sklearn.metrics.get_scorer` to
retrieve the scorer object.
Returns
-------
list of str
    Names of all available scorers.
Examples
--------
>>> from sklearn.metrics import get_scorer_names
>>> all_scorers = get_scorer_names()
>>> type(all_scorers)
<class 'list'>
>>> all_scorers[:3]
['accuracy', 'adjusted_mutual_info_score', 'adjusted_rand_score']
>>> "roc_auc" in all_scorers
True
Definition at line 891 of file _scorer.py.
References get_scorer_names(), and make_scorer().
Referenced by get_scorer_names().
make_scorer()
sklearn.metrics._scorer.make_scorer (score_func, * , response_method = "default", greater_is_better = True, ** kwargs)
Make a scorer from a performance metric or loss function.
A scorer is a wrapper around an arbitrary metric or loss function that is called
with the signature `scorer(estimator, X, y_true, **kwargs)`.
It is accepted in all scikit-learn estimators or functions allowing a `scoring`
parameter.
The parameter `response_method` allows to specify which method of the estimator
should be used to feed the scoring/loss function.
Read more in the :ref:`User Guide <scoring_callable>`.
Parameters
----------
score_func : callable
    Score function (or loss function) with signature
    ``score_func(y, y_pred, **kwargs)``.
response_method : {"predict_proba", "decision_function", "predict"} or \
        list/tuple of such str, default=None
    Specifies the response method to use get prediction from an estimator
    (i.e. :term:`predict_proba`, :term:`decision_function` or
    :term:`predict`). Possible choices are:
    - if `str`, it corresponds to the name to the method to return;
    - if a list or tuple of `str`, it provides the method names in order of
      preference. The method returned corresponds to the first method in
      the list and which is implemented by `estimator`.
    - if `None`, it is equivalent to `"predict"`.
    .. versionadded:: 1.4
    .. deprecated:: 1.6
        None is equivalent to 'predict' and is deprecated. It will be removed in
        version 1.8.
greater_is_better : bool, default=True
    Whether `score_func` is a score function (default), meaning high is
    good, or a loss function, meaning low is good. In the latter case, the
    scorer object will sign-flip the outcome of the `score_func`.
**kwargs : additional arguments
    Additional parameters to be passed to `score_func`.
Returns
-------
scorer : callable
    Callable object that returns a scalar score; greater is better.
Examples
--------
>>> from sklearn.metrics import fbeta_score, make_scorer
>>> ftwo_scorer = make_scorer(fbeta_score, beta=2)
>>> ftwo_scorer
make_scorer(fbeta_score, response_method='predict', beta=2)
>>> from sklearn.model_selection import GridSearchCV
>>> from sklearn.svm import LinearSVC
>>> grid = GridSearchCV(LinearSVC(), param_grid={'C': [1, 10]},
...                     scoring=ftwo_scorer)
Definition at line 653 of file _scorer.py.
References make_scorer().
Referenced by get_scorer_names(), and make_scorer().
negative_likelihood_ratio()
sklearn.metrics._scorer.negative_likelihood_ratio (y_true, y_pred)
Definition at line 783 of file _scorer.py.
positive_likelihood_ratio()
sklearn.metrics._scorer.positive_likelihood_ratio (y_true, y_pred)
Definition at line 779 of file _scorer.py.
Variable Documentation
_deprecation_msg
sklearn.metrics._scorer._deprecation_msg protected
Definition at line 744 of file _scorer.py.
_SCORERS
sklearn.metrics._scorer._SCORERS protected
Definition at line 850 of file _scorer.py.
accuracy_scorer
sklearn.metrics._scorer.accuracy_scorer = make_scorer(accuracy_score)
Definition at line 774 of file _scorer.py.
adjusted_mutual_info_scorer
sklearn.metrics._scorer.adjusted_mutual_info_scorer = make_scorer(adjusted_mutual_info_score)
Definition at line 845 of file _scorer.py.
adjusted_rand_scorer
sklearn.metrics._scorer.adjusted_rand_scorer = make_scorer(adjusted_rand_score)
Definition at line 839 of file _scorer.py.
average
sklearn.metrics._scorer.average
Definition at line 922 of file _scorer.py.
average_precision_scorer
sklearn.metrics._scorer.average_precision_scorer
Initial value:
=  make_scorer(
    average_precision_score,
    response_method=("decision_function", "predict_proba"),
)
Definition at line 803 of file _scorer.py.
balanced_accuracy_scorer
sklearn.metrics._scorer.balanced_accuracy_scorer = make_scorer(balanced_accuracy_score)
Definition at line 775 of file _scorer.py.
brier_score_loss_scorer
sklearn.metrics._scorer.brier_score_loss_scorer
Initial value:
=  make_scorer(
    brier_score_loss, greater_is_better=False, response_method="predict_proba"
)
Definition at line 833 of file _scorer.py.
completeness_scorer
sklearn.metrics._scorer.completeness_scorer = make_scorer(completeness_score)
Definition at line 842 of file _scorer.py.
d2_absolute_error_scorer
sklearn.metrics._scorer.d2_absolute_error_scorer = make_scorer(d2_absolute_error_score)
Definition at line 771 of file _scorer.py.
deprecation_msg
tuple sklearn.metrics._scorer.deprecation_msg
Initial value:
=  (
    "Scoring method max_error was renamed to "
    "neg_max_error in version 1.6 and will "
    "be removed in 1.8."
)
Definition at line 739 of file _scorer.py.
explained_variance_scorer
sklearn.metrics._scorer.explained_variance_scorer = make_scorer(explained_variance_score)
Definition at line 734 of file _scorer.py.
fowlkes_mallows_scorer
sklearn.metrics._scorer.fowlkes_mallows_scorer = make_scorer(fowlkes_mallows_score)
Definition at line 847 of file _scorer.py.
homogeneity_scorer
sklearn.metrics._scorer.homogeneity_scorer = make_scorer(homogeneity_score)
Definition at line 841 of file _scorer.py.
matthews_corrcoef_scorer
sklearn.metrics._scorer.matthews_corrcoef_scorer = make_scorer(matthews_corrcoef)
Definition at line 776 of file _scorer.py.
max_error_scorer
sklearn.metrics._scorer.max_error_scorer = make_scorer(max_error, greater_is_better=False)
Definition at line 737 of file _scorer.py.
metric
sklearn.metrics._scorer.metric
Definition at line 922 of file _scorer.py.
mutual_info_scorer
sklearn.metrics._scorer.mutual_info_scorer = make_scorer(mutual_info_score)
Definition at line 844 of file _scorer.py.
neg_brier_score_scorer
sklearn.metrics._scorer.neg_brier_score_scorer
Initial value:
=  make_scorer(
    brier_score_loss, greater_is_better=False, response_method="predict_proba"
)
Definition at line 830 of file _scorer.py.
neg_log_loss_scorer
sklearn.metrics._scorer.neg_log_loss_scorer
Initial value:
=  make_scorer(
    log_loss, greater_is_better=False, response_method="predict_proba"
)
Definition at line 827 of file _scorer.py.
neg_max_error_scorer
sklearn.metrics._scorer.neg_max_error_scorer = make_scorer(max_error, greater_is_better=False)
Definition at line 736 of file _scorer.py.
neg_mean_absolute_error_scorer
sklearn.metrics._scorer.neg_mean_absolute_error_scorer
Initial value:
=  make_scorer(
    mean_absolute_error, greater_is_better=False
)
Definition at line 749 of file _scorer.py.
neg_mean_absolute_percentage_error_scorer
sklearn.metrics._scorer.neg_mean_absolute_percentage_error_scorer
Initial value:
=  make_scorer(
    mean_absolute_percentage_error, greater_is_better=False
)
Definition at line 752 of file _scorer.py.
neg_mean_gamma_deviance_scorer
sklearn.metrics._scorer.neg_mean_gamma_deviance_scorer
Initial value:
=  make_scorer(
    mean_gamma_deviance, greater_is_better=False
)
Definition at line 768 of file _scorer.py.
neg_mean_poisson_deviance_scorer
sklearn.metrics._scorer.neg_mean_poisson_deviance_scorer
Initial value:
=  make_scorer(
    mean_poisson_deviance, greater_is_better=False
)
Definition at line 764 of file _scorer.py.
neg_mean_squared_error_scorer
sklearn.metrics._scorer.neg_mean_squared_error_scorer = make_scorer(mean_squared_error, greater_is_better=False)
Definition at line 745 of file _scorer.py.
neg_mean_squared_log_error_scorer
sklearn.metrics._scorer.neg_mean_squared_log_error_scorer
Initial value:
=  make_scorer(
    mean_squared_log_error, greater_is_better=False
)
Definition at line 746 of file _scorer.py.
neg_median_absolute_error_scorer
sklearn.metrics._scorer.neg_median_absolute_error_scorer
Initial value:
=  make_scorer(
    median_absolute_error, greater_is_better=False
)
Definition at line 755 of file _scorer.py.
neg_negative_likelihood_ratio_scorer
sklearn.metrics._scorer.neg_negative_likelihood_ratio_scorer
Initial value:
=  make_scorer(
    negative_likelihood_ratio, greater_is_better=False
)
Definition at line 788 of file _scorer.py.
neg_root_mean_squared_error_scorer
sklearn.metrics._scorer.neg_root_mean_squared_error_scorer
Initial value:
=  make_scorer(
    root_mean_squared_error, greater_is_better=False
)
Definition at line 758 of file _scorer.py.
neg_root_mean_squared_log_error_scorer
sklearn.metrics._scorer.neg_root_mean_squared_log_error_scorer
Initial value:
=  make_scorer(
    root_mean_squared_log_error, greater_is_better=False
)
Definition at line 761 of file _scorer.py.
None
sklearn.metrics._scorer.None
Definition at line 925 of file _scorer.py.
normalized_mutual_info_scorer
sklearn.metrics._scorer.normalized_mutual_info_scorer = make_scorer(normalized_mutual_info_score)
Definition at line 846 of file _scorer.py.
pos_label
sklearn.metrics._scorer.pos_label
Definition at line 925 of file _scorer.py.
positive_likelihood_ratio_scorer
sklearn.metrics._scorer.positive_likelihood_ratio_scorer = make_scorer(positive_likelihood_ratio)
Definition at line 787 of file _scorer.py.
qualified_name
str sklearn.metrics._scorer.qualified_name = "{0}_{1}".format(name, average)
Definition at line 924 of file _scorer.py.
r2_scorer
sklearn.metrics._scorer.r2_scorer = make_scorer(r2_score)
Definition at line 735 of file _scorer.py.
rand_scorer
sklearn.metrics._scorer.rand_scorer = make_scorer(rand_score)
Definition at line 840 of file _scorer.py.
roc_auc_ovo_scorer
sklearn.metrics._scorer.roc_auc_ovo_scorer
Initial value:
=  make_scorer(
    roc_auc_score, response_method="predict_proba", multi_class="ovo"
)
Definition at line 807 of file _scorer.py.
roc_auc_ovo_weighted_scorer
sklearn.metrics._scorer.roc_auc_ovo_weighted_scorer
Initial value:
=  make_scorer(
    roc_auc_score,
    response_method="predict_proba",
    multi_class="ovo",
    average="weighted",
)
Definition at line 810 of file _scorer.py.
roc_auc_ovr_scorer
sklearn.metrics._scorer.roc_auc_ovr_scorer
Initial value:
=  make_scorer(
    roc_auc_score, response_method="predict_proba", multi_class="ovr"
)
Definition at line 816 of file _scorer.py.
roc_auc_ovr_weighted_scorer
sklearn.metrics._scorer.roc_auc_ovr_weighted_scorer
Initial value:
=  make_scorer(
    roc_auc_score,
    response_method="predict_proba",
    multi_class="ovr",
    average="weighted",
)
Definition at line 819 of file _scorer.py.
roc_auc_scorer
sklearn.metrics._scorer.roc_auc_scorer
Initial value:
=  make_scorer(
    roc_auc_score,
    greater_is_better=True,
    response_method=("decision_function", "predict_proba"),
)
Definition at line 798 of file _scorer.py.
top_k_accuracy_scorer
sklearn.metrics._scorer.top_k_accuracy_scorer
Initial value:
=  make_scorer(
    top_k_accuracy_score,
    greater_is_better=True,
    response_method=("decision_function", "predict_proba"),
)
Definition at line 793 of file _scorer.py.
v_measure_scorer
sklearn.metrics._scorer.v_measure_scorer = make_scorer(v_measure_score)
Definition at line 843 of file _scorer.py.