Code Cloning Analysis: scipy.stats._continuous_distns Namespace Reference
scipy.stats._continuous_distns Namespace Reference
Classes
class alpha_gen
class anglit_gen
class arcsine_gen
class argus_gen
class beta_gen
class betaprime_gen
class bradford_gen
class burr12_gen
class burr_gen
class cauchy_gen
class chi2_gen
class chi_gen
class cosine_gen
class crystalball_gen
class dgamma_gen
class dweibull_gen
class erlang_gen
class expon_gen
class exponnorm_gen
class exponpow_gen
class exponweib_gen
class f_gen
class fatiguelife_gen
class fisk_gen
class FitDataError
class FitSolverError
class FitUniformFixedScaleDataError
class foldcauchy_gen
class foldnorm_gen
Folded Normal abs(Z) where (Z is normal with mu=L and std=S so that c=abs(L)/S)
class gamma_gen
Gamma (Use MATLAB and MATHEMATICA (b=theta=scale, a=alpha=shape) definition)
class gausshyper_gen
class genexpon_gen
class genextreme_gen
class gengamma_gen
class genhalflogistic_gen
class genhyperbolic_gen
class geninvgauss_gen
class genlogistic_gen
class gennorm_gen
class genpareto_gen
class gibrat_gen
class gompertz_gen
class gumbel_l_gen
class gumbel_r_gen
class halfcauchy_gen
class halfgennorm_gen
class halflogistic_gen
class halfnorm_gen
class hypsecant_gen
class invgamma_gen
class invgauss_gen
class invweibull_gen
class johnsonsb_gen
class johnsonsu_gen
class kappa3_gen
class kappa4_gen
class ksone_gen
class kstwo_gen
class kstwobign_gen
class laplace_asymmetric_gen
class laplace_gen
class levy_gen
class levy_l_gen
class loggamma_gen
class logistic_gen
class loglaplace_gen
class lognorm_gen
class lomax_gen
class maxwell_gen
class mielke_gen
class moyal_gen
class nakagami_gen
class ncf_gen
class nct_gen
class ncx2_gen
class norm_gen
class norminvgauss_gen
class pareto_gen
class pearson3_gen
class powerlaw_gen
class powerlognorm_gen
class powernorm_gen
class rayleigh_gen
class rdist_gen
class recipinvgauss_gen
class reciprocal_gen
class rel_breitwigner_gen
class rice_gen
class rv_histogram
class semicircular_gen
class skewcauchy_gen
class skewnorm_gen
class studentized_range_gen
class t_gen
class trapezoid_gen
class triang_gen
class truncexpon_gen
class truncnorm_gen
class truncpareto_gen
class truncweibull_min_gen
class tukeylambda_gen
class uniform_gen
class vonmises_gen
class wald_gen
class weibull_max_gen
class weibull_min_gen
class wrapcauchy_gen
Functions
_remove_optimizer_parameters (kwds)
_call_super_mom (fun)
_get_left_bracket (fun, rbrack, lbrack=None)
_norm_pdf (x)
_norm_logpdf (x)
_norm_cdf (x)
_norm_logcdf (x)
_norm_ppf (q)
_norm_sf (x)
_norm_logsf (x)
_norm_isf (q)
_beta_mle_a (a, b, n, s1)
_beta_mle_ab (theta, n, s1, s2)
_pow1pm1 (x, y)
_digammainv (y)
_average_with_log_weights (x, logweights)
_check_fit_input_parameters (dist, data, args, kwds)
_lognorm_logpdf (x, s)
_ncx2_log_pdf (x, df, nc)
_log_sum (log_p, log_q)
_log_diff (log_p, log_q)
_log_gauss_mass (a, b)
_argus_phi (chi)
Variables
ksone = ksone_gen(a=0.0, b=1.0, name='ksone')
kstwo = kstwo_gen(momtype=0, a=0.0, b=1.0, name='kstwo')
kstwobign = kstwobign_gen(a=0.0, name='kstwobign')
_norm_pdf_C = np.sqrt(2*np.pi)
Normal distribution.
_norm_pdf_logC = np.log(_norm_pdf_C)
norm = norm_gen(name='norm')
alpha = alpha_gen(a=0.0, name='alpha')
anglit = anglit_gen(a=-np.pi/4, b=np.pi/4, name='anglit')
arcsine = arcsine_gen(a=0.0, b=1.0, name='arcsine')
beta = beta_gen(a=0.0, b=1.0, name='beta')
betaprime = betaprime_gen(a=0.0, name='betaprime')
bradford = bradford_gen(a=0.0, b=1.0, name='bradford')
burr = burr_gen(a=0.0, name='burr')
burr12 = burr12_gen(a=0.0, name='burr12')
fisk = fisk_gen(a=0.0, name='fisk')
cauchy = cauchy_gen(name='cauchy')
chi = chi_gen(a=0.0, name='chi')
chi2 = chi2_gen(a=0.0, name='chi2')
cosine = cosine_gen(a=-np.pi, b=np.pi, name='cosine')
dgamma = dgamma_gen(name='dgamma')
dweibull = dweibull_gen(name='dweibull')
expon = expon_gen(a=0.0, name='expon')
exponnorm = exponnorm_gen(name='exponnorm')
exponweib = exponweib_gen(a=0.0, name='exponweib')
exponpow = exponpow_gen(a=0.0, name='exponpow')
fatiguelife = fatiguelife_gen(a=0.0, name='fatiguelife')
foldcauchy = foldcauchy_gen(a=0.0, name='foldcauchy')
f = f_gen(a=0.0, name='f')
foldnorm = foldnorm_gen(a=0.0, name='foldnorm')
weibull_min = weibull_min_gen(a=0.0, name='weibull_min')
truncweibull_min = truncweibull_min_gen(name='truncweibull_min')
weibull_max = weibull_max_gen(b=0.0, name='weibull_max')
genlogistic = genlogistic_gen(name='genlogistic')
genpareto = genpareto_gen(a=0.0, name='genpareto')
genexpon = genexpon_gen(a=0.0, name='genexpon')
genextreme = genextreme_gen(name='genextreme')
gamma = gamma_gen(a=0.0, name='gamma')
erlang = erlang_gen(a=0.0, name='erlang')
gengamma = gengamma_gen(a=0.0, name='gengamma')
genhalflogistic = genhalflogistic_gen(a=0.0, name='genhalflogistic')
genhyperbolic = genhyperbolic_gen(name='genhyperbolic')
gompertz = gompertz_gen(a=0.0, name='gompertz')
gumbel_r = gumbel_r_gen(name='gumbel_r')
gumbel_l = gumbel_l_gen(name='gumbel_l')
halfcauchy = halfcauchy_gen(a=0.0, name='halfcauchy')
halflogistic = halflogistic_gen(a=0.0, name='halflogistic')
halfnorm = halfnorm_gen(a=0.0, name='halfnorm')
hypsecant = hypsecant_gen(name='hypsecant')
gausshyper = gausshyper_gen(a=0.0, b=1.0, name='gausshyper')
invgamma = invgamma_gen(a=0.0, name='invgamma')
invgauss = invgauss_gen(a=0.0, name='invgauss')
geninvgauss = geninvgauss_gen(a=0.0, name="geninvgauss")
norminvgauss = norminvgauss_gen(name="norminvgauss")
invweibull = invweibull_gen(a=0, name='invweibull')
johnsonsb = johnsonsb_gen(a=0.0, b=1.0, name='johnsonsb')
johnsonsu = johnsonsu_gen(name='johnsonsu')
laplace = laplace_gen(name='laplace')
laplace_asymmetric = laplace_asymmetric_gen(name='laplace_asymmetric')
levy = levy_gen(a=0.0, name="levy")
levy_l = levy_l_gen(b=0.0, name="levy_l")
logistic = logistic_gen(name='logistic')
loggamma = loggamma_gen(name='loggamma')
loglaplace = loglaplace_gen(a=0.0, name='loglaplace')
lognorm = lognorm_gen(a=0.0, name='lognorm')
gibrat = gibrat_gen(a=0.0, name='gibrat')
maxwell = maxwell_gen(a=0.0, name='maxwell')
mielke = mielke_gen(a=0.0, name='mielke')
kappa4 = kappa4_gen(name='kappa4')
kappa3 = kappa3_gen(a=0.0, name='kappa3')
moyal = moyal_gen(name="moyal")
nakagami = nakagami_gen(a=0.0, name="nakagami")
ncx2 = ncx2_gen(a=0.0, name='ncx2')
ncf = ncf_gen(a=0.0, name='ncf')
t = t_gen(name='t')
nct = nct_gen(name="nct")
pareto = pareto_gen(a=1.0, name="pareto")
lomax = lomax_gen(a=0.0, name="lomax")
pearson3 = pearson3_gen(name="pearson3")
powerlaw = powerlaw_gen(a=0.0, b=1.0, name="powerlaw")
powerlognorm = powerlognorm_gen(a=0.0, name="powerlognorm")
powernorm = powernorm_gen(name='powernorm')
rdist = rdist_gen(a=-1.0, b=1.0, name="rdist")
rayleigh = rayleigh_gen(a=0.0, name="rayleigh")
loguniform = reciprocal_gen(name="loguniform")
reciprocal = reciprocal_gen(name="reciprocal")
rice = rice_gen(a=0.0, name="rice")
recipinvgauss = recipinvgauss_gen(a=0.0, name='recipinvgauss')
semicircular = semicircular_gen(a=-1.0, b=1.0, name="semicircular")
skewcauchy = skewcauchy_gen(name='skewcauchy')
skewnorm = skewnorm_gen(name='skewnorm')
trapezoid = trapezoid_gen(a=0.0, b=1.0, name="trapezoid")
trapz = trapezoid_gen(a=0.0, b=1.0, name="trapz")
__doc__
triang = triang_gen(a=0.0, b=1.0, name="triang")
truncexpon = truncexpon_gen(a=0.0, name='truncexpon')
truncnorm = truncnorm_gen(name='truncnorm', momtype=1)
truncpareto = truncpareto_gen(a=1.0, name='truncpareto')
tukeylambda = tukeylambda_gen(name='tukeylambda')
uniform = uniform_gen(a=0.0, b=1.0, name='uniform')
vonmises = vonmises_gen(name='vonmises')
vonmises_line = vonmises_gen(a=-np.pi, b=np.pi, name='vonmises_line')
wald = wald_gen(a=0.0, name="wald")
wrapcauchy = wrapcauchy_gen(a=0.0, b=2*np.pi, name='wrapcauchy')
gennorm = gennorm_gen(name='gennorm')
halfgennorm = halfgennorm_gen(a=0, name='halfgennorm')
crystalball = crystalball_gen(name='crystalball', longname="A Crystalball Function")
argus = argus_gen(name='argus', longname="An Argus Function", a=0.0, b=1.0)
studentized_range
rel_breitwigner = rel_breitwigner_gen(a=0.0, name="rel_breitwigner")
pairs = list(globals().copy().items())
_distn_names
_distn_gen_names
__all__ = _distn_names + _distn_gen_names + ['rv_histogram']
Function Documentation
_argus_phi()
scipy.stats._continuous_distns._argus_phi (chi) protected
Utility function for the argus distribution used in the pdf, sf and
moment calculation.
Note that for all x > 0:
gammainc(1.5, x**2/2) = 2 * (_norm_cdf(x) - x * _norm_pdf(x) - 0.5).
This can be verified directly by noting that the cdf of Gamma(1.5) can
be written as erf(sqrt(x)) - 2*sqrt(x)*exp(-x)/sqrt(Pi).
We use gammainc instead of the usual definition because it is more precise
for small chi.
Definition at line 10610 of file _continuous_distns.py.
_average_with_log_weights()
scipy.stats._continuous_distns._average_with_log_weights (x, logweights) protected
Definition at line 3890 of file _continuous_distns.py.
_beta_mle_a()
scipy.stats._continuous_distns._beta_mle_a (a, b, n, s1) protected
Definition at line 622 of file _continuous_distns.py.
_beta_mle_ab()
scipy.stats._continuous_distns._beta_mle_ab (theta, n, s1, s2) protected
Definition at line 631 of file _continuous_distns.py.
_call_super_mom()
scipy.stats._continuous_distns._call_super_mom (fun) protected
Definition at line 58 of file _continuous_distns.py.
_check_fit_input_parameters()
scipy.stats._continuous_distns._check_fit_input_parameters (dist, data, args, kwds) protected
Definition at line 5474 of file _continuous_distns.py.
_digammainv()
scipy.stats._continuous_distns._digammainv (y) protected
Inverse of the digamma function (real positive arguments only).
This function is used in the `fit` method of `gamma_gen`.
The function uses either optimize.fsolve or optimize.newton
to solve `sc.digamma(x) - y = 0`.  There is probably room for
improvement, but currently it works over a wide range of y:
>>> import numpy as np
>>> rng = np.random.default_rng()
>>> y = 64*rng.standard_normal(1000000)
>>> y.min(), y.max()
(-311.43592651416662, 351.77388222276869)
>>> x = [_digammainv(t) for t in y]
>>> np.abs(sc.digamma(x) - y).max()
1.1368683772161603e-13
Definition at line 3158 of file _continuous_distns.py.
Referenced by scipy.stats._continuous_distns.gamma_gen.fit().
_get_left_bracket()
scipy.stats._continuous_distns._get_left_bracket (fun, rbrack, lbrack = None) protected
Definition at line 79 of file _continuous_distns.py.
_log_diff()
scipy.stats._continuous_distns._log_diff (log_p, log_q) protected
Definition at line 9146 of file _continuous_distns.py.
_log_gauss_mass()
scipy.stats._continuous_distns._log_gauss_mass (a, b) protected
Log of Gaussian probability mass within an interval
Definition at line 9150 of file _continuous_distns.py.
Referenced by scipy.stats._continuous_distns.truncnorm_gen._get_support().
_log_sum()
scipy.stats._continuous_distns._log_sum (log_p, log_q) protected
Definition at line 9141 of file _continuous_distns.py.
_lognorm_logpdf()
scipy.stats._continuous_distns._lognorm_logpdf (x, s) protected
Definition at line 6008 of file _continuous_distns.py.
_ncx2_log_pdf()
scipy.stats._continuous_distns._ncx2_log_pdf (x, df, nc) protected
Definition at line 6922 of file _continuous_distns.py.
_norm_cdf()
scipy.stats._continuous_distns._norm_cdf (x) protected
Definition at line 308 of file _continuous_distns.py.
_norm_isf()
scipy.stats._continuous_distns._norm_isf (q) protected
Definition at line 328 of file _continuous_distns.py.
_norm_logcdf()
scipy.stats._continuous_distns._norm_logcdf (x) protected
Definition at line 312 of file _continuous_distns.py.
_norm_logpdf()
scipy.stats._continuous_distns._norm_logpdf (x) protected
Definition at line 304 of file _continuous_distns.py.
_norm_logsf()
scipy.stats._continuous_distns._norm_logsf (x) protected
Definition at line 324 of file _continuous_distns.py.
_norm_pdf()
scipy.stats._continuous_distns._norm_pdf (x) protected
Definition at line 300 of file _continuous_distns.py.
_norm_ppf()
scipy.stats._continuous_distns._norm_ppf (q) protected
Definition at line 316 of file _continuous_distns.py.
_norm_sf()
scipy.stats._continuous_distns._norm_sf (x) protected
Definition at line 320 of file _continuous_distns.py.
_pow1pm1()
scipy.stats._continuous_distns._pow1pm1 (x, y) protected
Compute (1 + x)**y - 1.
Uses expm1 and xlog1py to avoid loss of precision when
(1 + x)**y is close to 1.
Note that the inverse of this function with respect to x is
``_pow1pm1(x, 1/y)``.  That is, if
    t = _pow1pm1(x, y)
then
    x = _pow1pm1(t, 1/y)
Definition at line 1935 of file _continuous_distns.py.
_remove_optimizer_parameters()
scipy.stats._continuous_distns._remove_optimizer_parameters (kwds) protected
Remove the optimizer-related keyword arguments 'loc', 'scale' and
'optimizer' from `kwds`.  Then check that `kwds` is empty, and
raise `TypeError("Unknown arguments: %s." % kwds)` if it is not.
This function is used in the fit method of distributions that override
the default method and do not use the default optimization code.
`kwds` is modified in-place.
Definition at line 39 of file _continuous_distns.py.
Referenced by scipy.stats._continuous_distns.beta_gen.fit(), scipy.stats._continuous_distns.expon_gen.fit(), scipy.stats._continuous_distns.gamma_gen.fit(), scipy.stats._continuous_distns.norm_gen.fit(), and scipy.stats._continuous_distns.uniform_gen.fit().
Variable Documentation
__all__
scipy.stats._continuous_distns.__all__ = _distn_names + _distn_gen_names + ['rv_histogram'] private
Definition at line 11364 of file _continuous_distns.py.
__doc__
scipy.stats._continuous_distns.__doc__ private
Definition at line 8995 of file _continuous_distns.py.
_distn_gen_names
scipy.stats._continuous_distns._distn_gen_names protected
Definition at line 11362 of file _continuous_distns.py.
_distn_names
scipy.stats._continuous_distns._distn_names protected
Definition at line 11362 of file _continuous_distns.py.
_norm_pdf_C
scipy.stats._continuous_distns._norm_pdf_C = np.sqrt(2*np.pi) protected
Normal distribution.
Definition at line 296 of file _continuous_distns.py.
_norm_pdf_logC
scipy.stats._continuous_distns._norm_pdf_logC = np.log(_norm_pdf_C) protected
Definition at line 297 of file _continuous_distns.py.
alpha
scipy.stats._continuous_distns.alpha = alpha_gen(a=0.0, name='alpha')
Definition at line 499 of file _continuous_distns.py.
anglit
scipy.stats._continuous_distns.anglit = anglit_gen(a=-np.pi/4, b=np.pi/4, name='anglit')
Definition at line 545 of file _continuous_distns.py.
arcsine
scipy.stats._continuous_distns.arcsine = arcsine_gen(a=0.0, b=1.0, name='arcsine')
Definition at line 593 of file _continuous_distns.py.
argus
scipy.stats._continuous_distns.argus = argus_gen(name='argus', longname="An Argus Function", a=0.0, b=1.0)
Definition at line 10822 of file _continuous_distns.py.
beta
scipy.stats._continuous_distns.beta = beta_gen(a=0.0, b=1.0, name='beta')
Definition at line 839 of file _continuous_distns.py.
betaprime
scipy.stats._continuous_distns.betaprime = betaprime_gen(a=0.0, name='betaprime')
Definition at line 950 of file _continuous_distns.py.
bradford
scipy.stats._continuous_distns.bradford = bradford_gen(a=0.0, b=1.0, name='bradford')
Definition at line 1008 of file _continuous_distns.py.
burr
scipy.stats._continuous_distns.burr = burr_gen(a=0.0, name='burr')
Definition at line 1135 of file _continuous_distns.py.
burr12
scipy.stats._continuous_distns.burr12 = burr12_gen(a=0.0, name='burr12')
Definition at line 1218 of file _continuous_distns.py.
cauchy
scipy.stats._continuous_distns.cauchy = cauchy_gen(name='cauchy')
Definition at line 1352 of file _continuous_distns.py.
chi
scipy.stats._continuous_distns.chi = chi_gen(a=0.0, name='chi')
Definition at line 1436 of file _continuous_distns.py.
chi2
scipy.stats._continuous_distns.chi2 = chi2_gen(a=0.0, name='chi2')
Definition at line 1528 of file _continuous_distns.py.
cosine
scipy.stats._continuous_distns.cosine = cosine_gen(a=-np.pi, b=np.pi, name='cosine')
Definition at line 1584 of file _continuous_distns.py.
crystalball
scipy.stats._continuous_distns.crystalball = crystalball_gen(name='crystalball', longname="A Crystalball Function")
Definition at line 10607 of file _continuous_distns.py.
dgamma
scipy.stats._continuous_distns.dgamma = dgamma_gen(name='dgamma')
Definition at line 1664 of file _continuous_distns.py.
dweibull
scipy.stats._continuous_distns.dweibull = dweibull_gen(name='dweibull')
Definition at line 1739 of file _continuous_distns.py.
erlang
scipy.stats._continuous_distns.erlang = erlang_gen(a=0.0, name='erlang')
Definition at line 3448 of file _continuous_distns.py.
expon
scipy.stats._continuous_distns.expon = expon_gen(a=0.0, name='expon')
Definition at line 1851 of file _continuous_distns.py.
exponnorm
scipy.stats._continuous_distns.exponnorm = exponnorm_gen(name='exponnorm')
Definition at line 1932 of file _continuous_distns.py.
exponpow
scipy.stats._continuous_distns.exponpow = exponpow_gen(a=0.0, name='exponpow')
Definition at line 2082 of file _continuous_distns.py.
exponweib
scipy.stats._continuous_distns.exponweib = exponweib_gen(a=0.0, name='exponweib')
Definition at line 2026 of file _continuous_distns.py.
f
scipy.stats._continuous_distns.f = f_gen(a=0.0, name='f')
Definition at line 2319 of file _continuous_distns.py.
fatiguelife
scipy.stats._continuous_distns.fatiguelife = fatiguelife_gen(a=0.0, name='fatiguelife')
Definition at line 2162 of file _continuous_distns.py.
fisk
scipy.stats._continuous_distns.fisk = fisk_gen(a=0.0, name='fisk')
Definition at line 1296 of file _continuous_distns.py.
foldcauchy
scipy.stats._continuous_distns.foldcauchy = foldcauchy_gen(a=0.0, name='foldcauchy')
Definition at line 2213 of file _continuous_distns.py.
foldnorm
scipy.stats._continuous_distns.foldnorm = foldnorm_gen(a=0.0, name='foldnorm')
Definition at line 2392 of file _continuous_distns.py.
gamma
scipy.stats._continuous_distns.gamma = gamma_gen(a=0.0, name='gamma')
Definition at line 3389 of file _continuous_distns.py.
gausshyper
scipy.stats._continuous_distns.gausshyper = gausshyper_gen(a=0.0, b=1.0, name='gausshyper')
Definition at line 4383 of file _continuous_distns.py.
genexpon
scipy.stats._continuous_distns.genexpon = genexpon_gen(a=0.0, name='genexpon')
Definition at line 3003 of file _continuous_distns.py.
genextreme
scipy.stats._continuous_distns.genextreme = genextreme_gen(name='genextreme')
Definition at line 3155 of file _continuous_distns.py.
gengamma
scipy.stats._continuous_distns.gengamma = gengamma_gen(a=0.0, name='gengamma')
Definition at line 3548 of file _continuous_distns.py.
genhalflogistic
scipy.stats._continuous_distns.genhalflogistic = genhalflogistic_gen(a=0.0, name='genhalflogistic')
Definition at line 3601 of file _continuous_distns.py.
genhyperbolic
scipy.stats._continuous_distns.genhyperbolic = genhyperbolic_gen(name='genhyperbolic')
Definition at line 3836 of file _continuous_distns.py.
geninvgauss
scipy.stats._continuous_distns.geninvgauss = geninvgauss_gen(a=0.0, name="geninvgauss")
Definition at line 4927 of file _continuous_distns.py.
genlogistic
scipy.stats._continuous_distns.genlogistic = genlogistic_gen(name='genlogistic')
Definition at line 2813 of file _continuous_distns.py.
gennorm
scipy.stats._continuous_distns.gennorm = gennorm_gen(name='gennorm')
Definition at line 10385 of file _continuous_distns.py.
genpareto
scipy.stats._continuous_distns.genpareto = genpareto_gen(a=0.0, name='genpareto')
Definition at line 2936 of file _continuous_distns.py.
gibrat
scipy.stats._continuous_distns.gibrat = gibrat_gen(a=0.0, name='gibrat')
Definition at line 6254 of file _continuous_distns.py.
gompertz
scipy.stats._continuous_distns.gompertz = gompertz_gen(a=0.0, name='gompertz')
Definition at line 3887 of file _continuous_distns.py.
gumbel_l
scipy.stats._continuous_distns.gumbel_l = gumbel_l_gen(name='gumbel_l')
Definition at line 4104 of file _continuous_distns.py.
gumbel_r
scipy.stats._continuous_distns.gumbel_r = gumbel_r_gen(name='gumbel_r')
Definition at line 4025 of file _continuous_distns.py.
halfcauchy
scipy.stats._continuous_distns.halfcauchy = halfcauchy_gen(a=0.0, name='halfcauchy')
Definition at line 4156 of file _continuous_distns.py.
halfgennorm
scipy.stats._continuous_distns.halfgennorm = halfgennorm_gen(a=0, name='halfgennorm')
Definition at line 10452 of file _continuous_distns.py.
halflogistic
scipy.stats._continuous_distns.halflogistic = halflogistic_gen(a=0.0, name='halflogistic')
Definition at line 4220 of file _continuous_distns.py.
halfnorm
scipy.stats._continuous_distns.halfnorm = halfnorm_gen(a=0.0, name='halfnorm')
Definition at line 4280 of file _continuous_distns.py.
hypsecant
scipy.stats._continuous_distns.hypsecant = hypsecant_gen(name='hypsecant')
Definition at line 4323 of file _continuous_distns.py.
invgamma
scipy.stats._continuous_distns.invgamma = invgamma_gen(a=0.0, name='invgamma')
Definition at line 4472 of file _continuous_distns.py.
invgauss
scipy.stats._continuous_distns.invgauss = invgauss_gen(a=0.0, name='invgauss')
Definition at line 4607 of file _continuous_distns.py.
invweibull
scipy.stats._continuous_distns.invweibull = invweibull_gen(a=0, name='invweibull')
Definition at line 5147 of file _continuous_distns.py.
johnsonsb
scipy.stats._continuous_distns.johnsonsb = johnsonsb_gen(a=0.0, b=1.0, name='johnsonsb')
Definition at line 5206 of file _continuous_distns.py.
johnsonsu
scipy.stats._continuous_distns.johnsonsu = johnsonsu_gen(name='johnsonsu')
Definition at line 5302 of file _continuous_distns.py.
kappa3
scipy.stats._continuous_distns.kappa3 = kappa3_gen(a=0.0, name='kappa3')
Definition at line 6720 of file _continuous_distns.py.
kappa4
scipy.stats._continuous_distns.kappa4 = kappa4_gen(name='kappa4')
Definition at line 6661 of file _continuous_distns.py.
ksone
scipy.stats._continuous_distns.ksone = ksone_gen(a=0.0, b=1.0, name='ksone')
Definition at line 162 of file _continuous_distns.py.
kstwo
scipy.stats._continuous_distns.kstwo = kstwo_gen(momtype=0, a=0.0, b=1.0, name='kstwo')
Definition at line 229 of file _continuous_distns.py.
kstwobign
scipy.stats._continuous_distns.kstwobign = kstwobign_gen(a=0.0, name='kstwobign')
Definition at line 288 of file _continuous_distns.py.
laplace
scipy.stats._continuous_distns.laplace = laplace_gen(name='laplace')
Definition at line 5377 of file _continuous_distns.py.
laplace_asymmetric
scipy.stats._continuous_distns.laplace_asymmetric = laplace_asymmetric_gen(name='laplace_asymmetric')
Definition at line 5471 of file _continuous_distns.py.
levy
scipy.stats._continuous_distns.levy = levy_gen(a=0.0, name="levy")
Definition at line 5624 of file _continuous_distns.py.
levy_l
scipy.stats._continuous_distns.levy_l = levy_l_gen(b=0.0, name="levy_l")
Definition at line 5728 of file _continuous_distns.py.
loggamma
scipy.stats._continuous_distns.loggamma = loggamma_gen(name='loggamma')
Definition at line 5950 of file _continuous_distns.py.
logistic
scipy.stats._continuous_distns.logistic = logistic_gen(name='logistic')
Definition at line 5847 of file _continuous_distns.py.
loglaplace
scipy.stats._continuous_distns.loglaplace = loglaplace_gen(a=0.0, name='loglaplace')
Definition at line 6005 of file _continuous_distns.py.
lognorm
scipy.stats._continuous_distns.lognorm = lognorm_gen(a=0.0, name='lognorm')
Definition at line 6192 of file _continuous_distns.py.
loguniform
scipy.stats._continuous_distns.loguniform = reciprocal_gen(name="loguniform")
Definition at line 8415 of file _continuous_distns.py.
lomax
scipy.stats._continuous_distns.lomax = lomax_gen(a=0.0, name="lomax")
Definition at line 7550 of file _continuous_distns.py.
maxwell
scipy.stats._continuous_distns.maxwell = maxwell_gen(a=0.0, name='maxwell')
Definition at line 6322 of file _continuous_distns.py.
mielke
scipy.stats._continuous_distns.mielke = mielke_gen(a=0.0, name='mielke')
Definition at line 6387 of file _continuous_distns.py.
moyal
scipy.stats._continuous_distns.moyal = moyal_gen(name="moyal")
Definition at line 6815 of file _continuous_distns.py.
nakagami
scipy.stats._continuous_distns.nakagami = nakagami_gen(a=0.0, name="nakagami")
Definition at line 6918 of file _continuous_distns.py.
ncf
scipy.stats._continuous_distns.ncf = ncf_gen(a=0.0, name='ncf')
Definition at line 7116 of file _continuous_distns.py.
nct
scipy.stats._continuous_distns.nct = nct_gen(name="nct")
Definition at line 7335 of file _continuous_distns.py.
ncx2
scipy.stats._continuous_distns.ncx2 = ncx2_gen(a=0.0, name='ncx2')
Definition at line 7021 of file _continuous_distns.py.
norm
scipy.stats._continuous_distns.norm = norm_gen(name='norm')
Definition at line 442 of file _continuous_distns.py.
norminvgauss
scipy.stats._continuous_distns.norminvgauss = norminvgauss_gen(name="norminvgauss")
Definition at line 5077 of file _continuous_distns.py.
pairs
scipy.stats._continuous_distns.pairs = list(globals().copy().items())
Definition at line 11361 of file _continuous_distns.py.
pareto
scipy.stats._continuous_distns.pareto = pareto_gen(a=1.0, name="pareto")
Definition at line 7493 of file _continuous_distns.py.
pearson3
scipy.stats._continuous_distns.pearson3 = pearson3_gen(name="pearson3")
Definition at line 7732 of file _continuous_distns.py.
powerlaw
scipy.stats._continuous_distns.powerlaw = powerlaw_gen(a=0.0, b=1.0, name="powerlaw")
Definition at line 8013 of file _continuous_distns.py.
powerlognorm
scipy.stats._continuous_distns.powerlognorm = powerlognorm_gen(a=0.0, name="powerlognorm")
Definition at line 8071 of file _continuous_distns.py.
powernorm
scipy.stats._continuous_distns.powernorm = powernorm_gen(name='powernorm')
Definition at line 8128 of file _continuous_distns.py.
rayleigh
scipy.stats._continuous_distns.rayleigh = rayleigh_gen(a=0.0, name="rayleigh")
Definition at line 8313 of file _continuous_distns.py.
rdist
scipy.stats._continuous_distns.rdist = rdist_gen(a=-1.0, b=1.0, name="rdist")
Definition at line 8189 of file _continuous_distns.py.
recipinvgauss
scipy.stats._continuous_distns.recipinvgauss = recipinvgauss_gen(a=0.0, name='recipinvgauss')
Definition at line 8538 of file _continuous_distns.py.
reciprocal
scipy.stats._continuous_distns.reciprocal = reciprocal_gen(name="reciprocal")
Definition at line 8416 of file _continuous_distns.py.
rel_breitwigner
scipy.stats._continuous_distns.rel_breitwigner = rel_breitwigner_gen(a=0.0, name="rel_breitwigner")
Definition at line 11357 of file _continuous_distns.py.
rice
scipy.stats._continuous_distns.rice = rice_gen(a=0.0, name="rice")
Definition at line 8482 of file _continuous_distns.py.
semicircular
scipy.stats._continuous_distns.semicircular = semicircular_gen(a=-1.0, b=1.0, name="semicircular")
Definition at line 8601 of file _continuous_distns.py.
skewcauchy
scipy.stats._continuous_distns.skewcauchy = skewcauchy_gen(name='skewcauchy')
Definition at line 8671 of file _continuous_distns.py.
skewnorm
scipy.stats._continuous_distns.skewnorm = skewnorm_gen(name='skewnorm')
Definition at line 8881 of file _continuous_distns.py.
studentized_range
scipy.stats._continuous_distns.studentized_range
Initial value:
=  studentized_range_gen(name='studentized_range', a=0,
                                          b=np.inf)
Definition at line 11207 of file _continuous_distns.py.
t
scipy.stats._continuous_distns.t = t_gen(name='t')
Definition at line 7251 of file _continuous_distns.py.
trapezoid
scipy.stats._continuous_distns.trapezoid = trapezoid_gen(a=0.0, b=1.0, name="trapezoid")
Definition at line 8990 of file _continuous_distns.py.
trapz
scipy.stats._continuous_distns.trapz = trapezoid_gen(a=0.0, b=1.0, name="trapz")
Definition at line 8993 of file _continuous_distns.py.
triang
scipy.stats._continuous_distns.triang = triang_gen(a=0.0, b=1.0, name="triang")
Definition at line 9071 of file _continuous_distns.py.
truncexpon
scipy.stats._continuous_distns.truncexpon = truncexpon_gen(a=0.0, name='truncexpon')
Definition at line 9137 of file _continuous_distns.py.
truncnorm
scipy.stats._continuous_distns.truncnorm = truncnorm_gen(name='truncnorm', momtype=1)
Definition at line 9379 of file _continuous_distns.py.
truncpareto
scipy.stats._continuous_distns.truncpareto = truncpareto_gen(a=1.0, name='truncpareto')
Definition at line 9700 of file _continuous_distns.py.
truncweibull_min
scipy.stats._continuous_distns.truncweibull_min = truncweibull_min_gen(name='truncweibull_min')
Definition at line 2662 of file _continuous_distns.py.
tukeylambda
scipy.stats._continuous_distns.tukeylambda = tukeylambda_gen(name='tukeylambda')
Definition at line 9753 of file _continuous_distns.py.
uniform
scipy.stats._continuous_distns.uniform = uniform_gen(a=0.0, b=1.0, name='uniform')
Definition at line 9949 of file _continuous_distns.py.
vonmises
scipy.stats._continuous_distns.vonmises = vonmises_gen(name='vonmises')
Definition at line 10164 of file _continuous_distns.py.
vonmises_line
scipy.stats._continuous_distns.vonmises_line = vonmises_gen(a=-np.pi, b=np.pi, name='vonmises_line')
Definition at line 10165 of file _continuous_distns.py.
wald
scipy.stats._continuous_distns.wald = wald_gen(a=0.0, name="wald")
Definition at line 10229 of file _continuous_distns.py.
weibull_max
scipy.stats._continuous_distns.weibull_max = weibull_max_gen(b=0.0, name='weibull_max')
Definition at line 2736 of file _continuous_distns.py.
weibull_min
scipy.stats._continuous_distns.weibull_min = weibull_min_gen(a=0.0, name='weibull_min')
Definition at line 2552 of file _continuous_distns.py.
wrapcauchy
scipy.stats._continuous_distns.wrapcauchy = wrapcauchy_gen(a=0.0, b=2*np.pi, name='wrapcauchy')
Definition at line 10295 of file _continuous_distns.py.