Code Cloning Analysis: scipy.io.matlab._mio5 Namespace Reference
scipy.io.matlab._mio5 Namespace Reference
Classes
class EmptyStructMarker
class MatFile5Reader
class MatFile5Writer
class VarWriter5
Functions
_has_struct (elem)
_inspect_cell_array (ndarray)
_matstruct_to_dict (matobj)
_simplify_cells (d)
varmats_from_mat (file_obj)
to_writeable (source)
Variables
NDT_FILE_HDR = MDTYPES[native_code]['dtypes']['file_header']
NDT_TAG_FULL = MDTYPES[native_code]['dtypes']['tag_full']
NDT_TAG_SMALL = MDTYPES[native_code]['dtypes']['tag_smalldata']
NDT_ARRAY_FLAGS = MDTYPES[native_code]['dtypes']['array_flags']
Detailed Description
 Classes for read / write of matlab (TM) 5 files
The matfile specification last found here:
https://www.mathworks.com/access/helpdesk/help/pdf_doc/matlab/matfile_format.pdf
(as of December 5 2008)
=================================
 Note on functions and mat files
=================================
The document above does not give any hints as to the storage of matlab
function handles, or anonymous function handles. I had, therefore, to
guess the format of matlab arrays of ``mxFUNCTION_CLASS`` and
``mxOPAQUE_CLASS`` by looking at example mat files.
``mxFUNCTION_CLASS`` stores all types of matlab functions. It seems to
contain a struct matrix with a set pattern of fields. For anonymous
functions, a sub-fields of one of these fields seems to contain the
well-named ``mxOPAQUE_CLASS``. This seems to contain:
* array flags as for any matlab matrix
* 3 int8 strings
* a matrix
It seems that whenever the mat file contains a ``mxOPAQUE_CLASS``
instance, there is also an un-named matrix (name == '') at the end of
the mat file. I'll call this the ``__function_workspace__`` matrix.
When I saved two anonymous functions in a mat file, or appended another
anonymous function to the mat file, there was still only one
``__function_workspace__`` un-named matrix at the end, but larger than
that for a mat file with a single anonymous function, suggesting that
the workspaces for the two functions had been merged.
The ``__function_workspace__`` matrix appears to be of double class
(``mxCLASS_DOUBLE``), but stored as uint8, the memory for which is in
the format of a mini .mat file, without the first 124 bytes of the file
header (the description and the subsystem_offset), but with the version
U2 bytes, and the S2 endian test bytes. There follow 4 zero bytes,
presumably for 8 byte padding, and then a series of ``miMATRIX``
entries, as in a standard mat file. The ``miMATRIX`` entries appear to
be series of un-named (name == '') matrices, and may also contain arrays
of this same mini-mat format.
I guess that:
* saving an anonymous function back to a mat file will need the
  associated ``__function_workspace__`` matrix saved as well for the
  anonymous function to work correctly.
* appending to a mat file that has a ``__function_workspace__`` would
  involve first pulling off this workspace, appending, checking whether
  there were any more anonymous functions appended, and then somehow
  merging the relevant workspaces, and saving at the end of the mat
  file.
The mat files I was playing with are in ``tests/data``:
* sqr.mat
* parabola.mat
* some_functions.mat
See ``tests/test_mio.py:test_mio_funcs.py`` for the debugging
script I was working with.
Small fragments of current code adapted from matfile.py by Heiko
Henkelmann; parts of the code for simplify_cells=True adapted from
http://blog.nephics.com/2019/08/28/better-loadmat-for-scipy/.
Function Documentation
_has_struct()
scipy.io.matlab._mio5._has_struct (elem) protected
Determine if elem is an array and if first array item is a struct.
Definition at line 104 of file _mio5.py.
Referenced by _inspect_cell_array(), _matstruct_to_dict(), and _simplify_cells().
_inspect_cell_array()
scipy.io.matlab._mio5._inspect_cell_array (ndarray) protected
Construct lists from cell arrays (loaded as numpy ndarrays), recursing
into items if they contain mat_struct objects.
Definition at line 110 of file _mio5.py.
References _has_struct(), _inspect_cell_array(), and _matstruct_to_dict().
Referenced by _inspect_cell_array(), _matstruct_to_dict(), and _simplify_cells().
_matstruct_to_dict()
scipy.io.matlab._mio5._matstruct_to_dict (matobj) protected
Construct nested dicts from mat_struct objects.
Definition at line 124 of file _mio5.py.
References _has_struct(), _inspect_cell_array(), and _matstruct_to_dict().
Referenced by _inspect_cell_array(), _matstruct_to_dict(), and _simplify_cells().
_simplify_cells()
scipy.io.matlab._mio5._simplify_cells (d) protected
Convert mat objects in dict to nested dicts.
Definition at line 138 of file _mio5.py.
References _has_struct(), _inspect_cell_array(), and _matstruct_to_dict().
Referenced by scipy.io.matlab._mio5.MatFile5Reader.get_variables().
to_writeable()
scipy.io.matlab._mio5.to_writeable (source)
 Convert input object ``source`` to something we can write
Parameters
----------
source : object
Returns
-------
arr : None or ndarray or EmptyStructMarker
    If `source` cannot be converted to something we can write to a matfile,
    return None.  If `source` is equivalent to an empty dictionary, return
    ``EmptyStructMarker``.  Otherwise return `source` converted to an
    ndarray with contents for writing to matfile.
Definition at line 448 of file _mio5.py.
Referenced by scipy.io.matlab._mio5.VarWriter5.write().
varmats_from_mat()
scipy.io.matlab._mio5.varmats_from_mat (file_obj)
 Pull variables out of mat 5 file as a sequence of mat file objects
This can be useful with a difficult mat file, containing unreadable
variables. This routine pulls the variables out in raw form and puts them,
unread, back into a file stream for saving or reading. Another use is the
pathological case where there is more than one variable of the same name in
the file; this routine returns the duplicates, whereas the standard reader
will overwrite duplicates in the returned dictionary.
The file pointer in `file_obj` will be undefined. File pointers for the
returned file-like objects are set at 0.
Parameters
----------
file_obj : file-like
    file object containing mat file
Returns
-------
named_mats : list
    list contains tuples of (name, BytesIO) where BytesIO is a file-like
    object containing mat file contents as for a single variable. The
    BytesIO contains a string with the original header and a single var. If
    ``var_file_obj`` is an individual BytesIO instance, then save as a mat
    file with something like ``open('test.mat',
    'wb').write(var_file_obj.read())``
Examples
--------
>>> import scipy.io
BytesIO is from the ``io`` module in Python 3, and is ``cStringIO`` for
Python < 3.
>>> mat_fileobj = BytesIO()
>>> scipy.io.savemat(mat_fileobj, {'b': np.arange(10), 'a': 'a string'})
>>> varmats = varmats_from_mat(mat_fileobj)
>>> sorted([name for name, str_obj in varmats])
['a', 'b']
Definition at line 375 of file _mio5.py.
Variable Documentation
NDT_ARRAY_FLAGS
scipy.io.matlab._mio5.NDT_ARRAY_FLAGS = MDTYPES[native_code]['dtypes']['array_flags']
Definition at line 508 of file _mio5.py.
NDT_FILE_HDR
scipy.io.matlab._mio5.NDT_FILE_HDR = MDTYPES[native_code]['dtypes']['file_header']
Definition at line 505 of file _mio5.py.
NDT_TAG_FULL
scipy.io.matlab._mio5.NDT_TAG_FULL = MDTYPES[native_code]['dtypes']['tag_full']
Definition at line 506 of file _mio5.py.
NDT_TAG_SMALL
scipy.io.matlab._mio5.NDT_TAG_SMALL = MDTYPES[native_code]['dtypes']['tag_smalldata']
Definition at line 507 of file _mio5.py.