Code Cloning Analysis: pandas.io.pytables.BlockManagerFixed Class Reference
pandas.io.pytables.BlockManagerFixed Class Reference
Public Member Functions
Shape|None shape (self)
DataFrame read (self, where=None, columns=None, int|None start=None, int|None stop=None)
None write (self, obj, **kwargs)
Public Member Functions inherited from pandas.io.pytables.GenericFixed
None validate_read (self, columns, where)
bool is_exists (self)
None set_attrs (self)
None get_attrs (self)
read_array (self, str key, int|None start=None, int|None stop=None)
Index read_index (self, str key, int|None start=None, int|None stop=None)
None write_index (self, str key, Index index)
None write_multi_index (self, str key, MultiIndex index)
MultiIndex read_multi_index (self, str key, int|None start=None, int|None stop=None)
Index read_index_node (self, Node node, int|None start=None, int|None stop=None)
None write_array_empty (self, str key, ArrayLike value)
None write_array (self, str key, AnyArrayLike obj, Index|None items=None)
Public Member Functions inherited from pandas.io.pytables.Fixed
None __init__ (self, HDFStore parent, Node group, str|None encoding="UTF-8", str errors="strict")
bool is_old_version (self)
tuple[int, int, int] version (self)
pandas_type (self)
str __repr__ (self)
None set_object_info (self)
Fixed copy (self)
pathname (self)
attrs (self)
storable (self)
nrows (self)
Literal[True]|None validate (self, other)
None validate_version (self, where=None)
bool infer_axes (self)
None delete (self, where=None, int|None start=None, int|None stop=None)
Public Attributes
nblocks = []
ndim
Public Attributes inherited from pandas.io.pytables.Fixed
parent = parent
group = group
encoding = _ensure_encoding(encoding)
errors = errors
storable
Additional Inherited Members
Static Public Attributes inherited from pandas.io.pytables.GenericFixed
list attributes = []
Static Public Attributes inherited from pandas.io.pytables.Fixed
str format_type = "fixed"
type obj_type [DataFrame | Series]
bool is_table = False
Protected Member Functions inherited from pandas.io.pytables.GenericFixed
str _class_to_alias (self, cls)
_alias_to_class (self, alias)
_get_index_factory (self, attrs)
Protected Member Functions inherited from pandas.io.pytables.Fixed
_handle (self)
_filters (self)
int _complevel (self)
bool _fletcher32 (self)
Static Protected Attributes inherited from pandas.io.pytables.GenericFixed
dict _index_type_map = {DatetimeIndex: "datetime", PeriodIndex: "period"}
dict _reverse_index_map = {v: k for k, v in _index_type_map.items()}
Detailed Description
Definition at line 3305 of file pytables.py.
Member Function Documentation
read()
DataFrame pandas.io.pytables.BlockManagerFixed.read (self, where = None, columns = None, int | None start = None, int | None stop = None)
Reimplemented from pandas.io.pytables.Fixed.
Definition at line 3337 of file pytables.py.
Referenced by pip._vendor.urllib3.util.ssltransport.SSLTransport.__init__(), pandas.io.sas.sas7bdat.SAS7BDATReader.column_types(), pip._vendor.urllib3.response.HTTPResponse.drain_conn(), pip._vendor.urllib3.response.HTTPResponse.from_httplib(), pandas.io.sas.sas_xport.XportReader.get_chunk(), PIL.ContainerIO.ContainerIO.readline(), and pip._vendor.urllib3.response.HTTPResponse.stream().
shape()
Shape | None pandas.io.pytables.BlockManagerFixed.shape (self)
Reimplemented from pandas.io.pytables.Fixed.
Definition at line 3311 of file pytables.py.
Referenced by scipy.sparse._index.IndexMixin._getcol(), scipy.sparse._index.IndexMixin._getrow(), scipy.sparse._index.IndexMixin._raise_on_1d_array_slice(), and pandas.core.arrays.timedeltas.TimedeltaArray._scalar_divlike_op().
write()
None pandas.io.pytables.BlockManagerFixed.write (self, obj, ** kwargs)
Reimplemented from pandas.io.pytables.GenericFixed.
Definition at line 3382 of file pytables.py.
Referenced by joblib.externals.cloudpickle.cloudpickle.Pickler.reducer_override(), scipy.io.matlab._mio5.VarWriter5.write_sparse(), and scipy.io.matlab._mio5.VarWriter5.write_top().
Member Data Documentation
nblocks
pandas.io.pytables.BlockManagerFixed.nblocks = []
Definition at line 3317 of file pytables.py.
Referenced by pandas.core.internals.managers.BlockManager.iset().
ndim
pandas.io.pytables.BlockManagerFixed.ndim
Definition at line 3349 of file pytables.py.
Referenced by numpy.lib.arrayterator.Arrayterator.__getitem__(), pandas.core.arrays.datetimes.DatetimeArray.__iter__(), pandas.io.pytables.Table._create_axes(), pandas.core.arrays.datetimelike.TimelikeOps.freq(), pandas.core.arrays.base.ExtensionArray.tolist(), pandas.core.arrays.string_.BaseStringArray.tolist(), and pandas.core.arrays.base.ExtensionArray.view().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/io/pytables.py