Code Cloning Analysis: fontTools.cffLib.IndexedStrings Class Reference
fontTools.cffLib.IndexedStrings Class Reference
Public Member Functions
__init__ (self, file=None)
getCompiler (self)
__len__ (self)
__getitem__ (self, SID)
getSID (self, s)
getStrings (self)
buildStringMapping (self)
Public Attributes
strings = strings
dict stringMapping
Detailed Description
SID -> string mapping.
Definition at line 2747 of file __init__.py.
Constructor & Destructor Documentation
__init__()
fontTools.cffLib.IndexedStrings.__init__ (self, file = None)
Definition at line 2750 of file __init__.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__getitem__()
fontTools.cffLib.IndexedStrings.__getitem__ (self, SID)
Definition at line 2763 of file __init__.py.
__len__()
fontTools.cffLib.IndexedStrings.__len__ (self)
Definition at line 2760 of file __init__.py.
buildStringMapping()
fontTools.cffLib.IndexedStrings.buildStringMapping (self)
Definition at line 2786 of file __init__.py.
getCompiler()
fontTools.cffLib.IndexedStrings.getCompiler (self)
Definition at line 2757 of file __init__.py.
getSID()
fontTools.cffLib.IndexedStrings.getSID (self, s)
Definition at line 2769 of file __init__.py.
getStrings()
fontTools.cffLib.IndexedStrings.getStrings (self)
Definition at line 2783 of file __init__.py.
Member Data Documentation
stringMapping
dict fontTools.cffLib.IndexedStrings.stringMapping
Definition at line 2775 of file __init__.py.
strings
fontTools.cffLib.IndexedStrings.strings = strings
Definition at line 2755 of file __init__.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/cffLib/__init__.py