Code Cloning Analysis: fontTools.varLib.mutator Namespace Reference
fontTools.varLib.mutator Namespace Reference
Functions
interpolate_cff2_PrivateDict (topDict, interpolateFromDeltas)
interpolate_cff2_charstrings (topDict, interpolateFromDeltas, glyphOrder)
interpolate_cff2_metrics (varfont, topDict, glyphOrder, loc)
instantiateVariableFont (varfont, location, inplace=False, overlap=True)
main (args=None)
Variables
log = logging.getLogger("fontTools.varlib.mutator")
dict OS2_WIDTH_CLASS_VALUES = {}
list percents = [50.0, 62.5, 75.0, 87.5, 100.0, 112.5, 125.0, 150.0, 200.0]
start
tuple half = (prev + curr) / 2
Detailed Description
Instantiate a variation font.  Run, eg:
.. code-block:: sh
    $ fonttools varLib.mutator ./NotoSansArabic-VF.ttf wght=140 wdth=85
Function Documentation
instantiateVariableFont()
fontTools.varLib.mutator.instantiateVariableFont (varfont, location, inplace = False, overlap = True)
Generate a static instance from a variable TTFont and a dictionary
defining the desired location along the variable font's axes.
The location values must be specified as user-space coordinates, e.g.:
.. code-block::
    {'wght': 400, 'wdth': 100}
By default, a new TTFont object is returned. If ``inplace`` is True, the
input varfont is modified and reduced to a static font.
When the overlap parameter is defined as True,
OVERLAP_SIMPLE and OVERLAP_COMPOUND bits are set to 1.  See
https://docs.microsoft.com/en-us/typography/opentype/spec/glyf
Definition at line 162 of file mutator.py.
References interpolate_cff2_metrics().
Referenced by main().
interpolate_cff2_charstrings()
fontTools.varLib.mutator.interpolate_cff2_charstrings (topDict, interpolateFromDeltas, glyphOrder)
Definition at line 73 of file mutator.py.
interpolate_cff2_metrics()
fontTools.varLib.mutator.interpolate_cff2_metrics (varfont, topDict, glyphOrder, loc)
Unlike TrueType glyphs, neither advance width nor bounding box
info is stored in a CFF2 charstring. The width data exists only in
the hmtx and HVAR tables. Since LSB data cannot be interpolated
reliably from the master LSB values in the hmtx table, we traverse
the charstring to determine the actual bound box.
Definition at line 115 of file mutator.py.
Referenced by instantiateVariableFont().
interpolate_cff2_PrivateDict()
fontTools.varLib.mutator.interpolate_cff2_PrivateDict (topDict, interpolateFromDeltas)
Definition at line 44 of file mutator.py.
main()
fontTools.varLib.mutator.main (args = None)
Instantiate a variation font
Definition at line 437 of file mutator.py.
References instantiateVariableFont().
Variable Documentation
half
tuple fontTools.varLib.mutator.half = (prev + curr) / 2
Definition at line 40 of file mutator.py.
log
fontTools.varLib.mutator.log = logging.getLogger("fontTools.varlib.mutator")
Definition at line 34 of file mutator.py.
OS2_WIDTH_CLASS_VALUES
dict fontTools.varLib.mutator.OS2_WIDTH_CLASS_VALUES = {}
Definition at line 37 of file mutator.py.
percents
list fontTools.varLib.mutator.percents = [50.0, 62.5, 75.0, 87.5, 100.0, 112.5, 125.0, 150.0, 200.0]
Definition at line 38 of file mutator.py.
start
fontTools.varLib.mutator.start
Definition at line 39 of file mutator.py.