Code Cloning Analysis: numpy.polynomial.tests.test_symbol.TestBinaryOperatorsSameSymbol Class Reference
numpy.polynomial.tests.test_symbol.TestBinaryOperatorsSameSymbol Class Reference
Public Member Functions
test_add (self, rhs)
test_sub (self, rhs)
test_polymul (self, rhs)
test_divmod (self, rhs)
test_radd (self, rhs)
test_rsub (self, rhs)
test_rmul (self, rhs)
test_rdivmod (self, rhs)
Static Public Attributes
p = poly.Polynomial([1, 2, 3], symbol='z')
Detailed Description
Ensure symbol is preserved for numeric operations on polynomials with
the same symbol
Definition at line 87 of file test_symbol.py.
Member Function Documentation
test_add()
numpy.polynomial.tests.test_symbol.TestBinaryOperatorsSameSymbol.test_add (self, rhs)
Definition at line 94 of file test_symbol.py.
test_divmod()
numpy.polynomial.tests.test_symbol.TestBinaryOperatorsSameSymbol.test_divmod (self, rhs)
Definition at line 106 of file test_symbol.py.
test_polymul()
numpy.polynomial.tests.test_symbol.TestBinaryOperatorsSameSymbol.test_polymul (self, rhs)
Definition at line 102 of file test_symbol.py.
test_radd()
numpy.polynomial.tests.test_symbol.TestBinaryOperatorsSameSymbol.test_radd (self, rhs)
Definition at line 110 of file test_symbol.py.
test_rdivmod()
numpy.polynomial.tests.test_symbol.TestBinaryOperatorsSameSymbol.test_rdivmod (self, rhs)
Definition at line 122 of file test_symbol.py.
test_rmul()
numpy.polynomial.tests.test_symbol.TestBinaryOperatorsSameSymbol.test_rmul (self, rhs)
Definition at line 118 of file test_symbol.py.
test_rsub()
numpy.polynomial.tests.test_symbol.TestBinaryOperatorsSameSymbol.test_rsub (self, rhs)
Definition at line 114 of file test_symbol.py.
test_sub()
numpy.polynomial.tests.test_symbol.TestBinaryOperatorsSameSymbol.test_sub (self, rhs)
Definition at line 98 of file test_symbol.py.
Member Data Documentation
p
numpy.polynomial.tests.test_symbol.TestBinaryOperatorsSameSymbol.p = poly.Polynomial([1, 2, 3], symbol='z') static
Definition at line 92 of file test_symbol.py.
Referenced by sklearn.model_selection._split.LeavePOut._iter_test_indices(), sklearn.cluster._dbscan.DBSCAN.fit(), sklearn.cluster._optics.OPTICS.fit(), sklearn.model_selection._split.LeavePOut.get_n_splits(), sklearn.neighbors._classification.KNeighborsClassifier.predict_proba(), sklearn.neighbors._classification.RadiusNeighborsClassifier.predict_proba(), sklearn.utils.tests.test_estimator_checks.ModifiesValueInsteadOfRaisingError.set_params(), and sklearn.utils.tests.test_estimator_checks.RaisesErrorInSetParams.set_params().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/polynomial/tests/test_symbol.py