Code Cloning Analysis: matplotlib.testing.jpl_units.StrConverter.StrConverter Class Reference
matplotlib.testing.jpl_units.StrConverter.StrConverter Class Reference
Static Public Member Functions
axisinfo (unit, axis)
convert (value, unit, axis)
default_units (value, axis)
Detailed Description
A Matplotlib converter class for string data values.
Valid units for string are:
- 'indexed' : Values are indexed as they are specified for plotting.
- 'sorted'  : Values are sorted alphanumerically.
- 'inverted' : Values are inverted so that the first value is on top.
- 'sorted-inverted' :  A combination of 'sorted' and 'inverted'
Definition at line 10 of file StrConverter.py.
Member Function Documentation
axisinfo()
matplotlib.testing.jpl_units.StrConverter.StrConverter.axisinfo (unit, axis) static
Return an `.AxisInfo` for the axis with the specified units.
Reimplemented from matplotlib.units.ConversionInterface.
Definition at line 22 of file StrConverter.py.
convert()
matplotlib.testing.jpl_units.StrConverter.StrConverter.convert (obj, unit, axis) static
Convert *obj* using *unit* for the specified *axis*.
If *obj* is a sequence, return the converted sequence.  The output must
be a sequence of scalars that can be used by the numpy array layer.
Reimplemented from matplotlib.units.ConversionInterface.
Definition at line 27 of file StrConverter.py.
Referenced by pandas.core.computation.engines.NumExprEngine._evaluate(), pandas.core.internals.blocks.Block.convert(), PIL.Image.Image.reduce(), PIL.Image.Image.resize(), and PIL.Image.Image.transform().
default_units()
matplotlib.testing.jpl_units.StrConverter.StrConverter.default_units (x, axis) static
Return the default unit for *x* or ``None`` for the given axis.
Reimplemented from matplotlib.units.ConversionInterface.
Definition at line 94 of file StrConverter.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/testing/jpl_units/StrConverter.py