Code Cloning Analysis: scipy.integrate._ivp.lsoda.LsodaDenseOutput Class Reference
scipy.integrate._ivp.lsoda.LsodaDenseOutput Class Reference
Public Member Functions
__init__ (self, t_old, t, h, order, yh)
Public Member Functions inherited from scipy.integrate._ivp.base.DenseOutput
__init__ (self, t_old, t)
__call__ (self, t)
Public Attributes
h = h
yh = yh
p = np.arange(order + 1)
Public Attributes inherited from scipy.integrate._ivp.base.DenseOutput
t_old = t_old
t = t
t_min = min(t, t_old)
t_max = max(t, t_old)
Protected Member Functions
_call_impl (self, t)
Detailed Description
Definition at line 188 of file lsoda.py.
Constructor & Destructor Documentation
__init__()
scipy.integrate._ivp.lsoda.LsodaDenseOutput.__init__ (self, t_old, t, h, order, yh)
Definition at line 189 of file lsoda.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
_call_impl()
scipy.integrate._ivp.lsoda.LsodaDenseOutput._call_impl (self, t) protected
Reimplemented from scipy.integrate._ivp.base.DenseOutput.
Definition at line 195 of file lsoda.py.
Member Data Documentation
h
scipy.integrate._ivp.lsoda.LsodaDenseOutput.h = h
Definition at line 191 of file lsoda.py.
p
scipy.integrate._ivp.lsoda.LsodaDenseOutput.p = np.arange(order + 1)
Definition at line 193 of file lsoda.py.
Referenced by sklearn.model_selection._split.LeavePOut._iter_test_indices(), sklearn.cluster._dbscan.DBSCAN.fit(), sklearn.cluster._optics.OPTICS.fit(), sklearn.model_selection._split.LeavePOut.get_n_splits(), sklearn.neighbors._classification.KNeighborsClassifier.predict_proba(), sklearn.neighbors._classification.RadiusNeighborsClassifier.predict_proba(), sklearn.utils.tests.test_estimator_checks.ModifiesValueInsteadOfRaisingError.set_params(), and sklearn.utils.tests.test_estimator_checks.RaisesErrorInSetParams.set_params().
yh
scipy.integrate._ivp.lsoda.LsodaDenseOutput.yh = yh
Definition at line 192 of file lsoda.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/integrate/_ivp/lsoda.py