Code Cloning Analysis: fontTools.ttLib.tables.S__i_l_f.Classes Class Reference
fontTools.ttLib.tables.S__i_l_f.Classes Class Reference
Public Member Functions
__init__ (self)
decompile (self, data, ttFont, version=2.0)
compile (self, ttFont, version=2.0)
toXML (self, writer, ttFont, version=2.0)
fromXML (self, name, attrs, content, ttFont, version=2.0)
Public Attributes
list linear = []
list nonLinear = []
self.numClass], numLinear
int numClass = len(oClasses) - 1
Detailed Description
Definition at line 666 of file S__i_l_f.py.
Constructor & Destructor Documentation
__init__()
fontTools.ttLib.tables.S__i_l_f.Classes.__init__ (self)
Definition at line 667 of file S__i_l_f.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
compile()
fontTools.ttLib.tables.S__i_l_f.Classes.compile (self, ttFont, version = 2.0)
Definition at line 696 of file S__i_l_f.py.
Referenced by fontTools.ttLib.tables.TupleVariation.TupleVariation.getCoordWidth(), and PIL.FontFile.FontFile.save().
decompile()
fontTools.ttLib.tables.S__i_l_f.Classes.decompile (self, data, ttFont, version = 2.0)
Definition at line 671 of file S__i_l_f.py.
Referenced by fontTools.ttLib.tables._c_m_a_p.CmapSubtable.newSubtable().
fromXML()
fontTools.ttLib.tables.S__i_l_f.Classes.fromXML (self, name, attrs, content, ttFont, version = 2.0)
Definition at line 751 of file S__i_l_f.py.
toXML()
fontTools.ttLib.tables.S__i_l_f.Classes.toXML (self, writer, ttFont, version = 2.0)
Definition at line 723 of file S__i_l_f.py.
Member Data Documentation
linear
fontTools.ttLib.tables.S__i_l_f.Classes.linear = []
Definition at line 668 of file S__i_l_f.py.
nonLinear
fontTools.ttLib.tables.S__i_l_f.Classes.nonLinear = []
Definition at line 669 of file S__i_l_f.py.
numClass
int fontTools.ttLib.tables.S__i_l_f.Classes.numClass = len(oClasses) - 1
Definition at line 713 of file S__i_l_f.py.
numLinear
self.numClass], fontTools.ttLib.tables.S__i_l_f.Classes.numLinear
Definition at line 687 of file S__i_l_f.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ttLib/tables/S__i_l_f.py