Code Cloning Analysis: numpy.testing._private.extbuild Namespace Reference
numpy.testing._private.extbuild Namespace Reference
Functions
build_and_import_extension (modname, functions, *, prologue="", build_dir=None, include_dirs=[], more_init="")
compile_extension_module (name, builddir, include_dirs, source_string, libraries=[], library_dirs=[])
_convert_str_to_file (source, dirname)
_make_methods (functions, modname)
_make_source (name, init, body)
_c_compile (cfile, outputfilename, include_dirs=[], libraries=[], library_dirs=[])
build (cfile, outputfilename, compile_extra, link_extra, include_dirs, libraries, library_dirs)
get_so_suffix ()
Variables
list __all__ = ['build_and_import_extension', 'compile_extension_module']
Detailed Description
Build a c-extension module on-the-fly in tests.
See build_and_import_extensions for usage hints
Function Documentation
_c_compile()
numpy.testing._private.extbuild._c_compile (cfile, outputfilename, include_dirs = [], libraries = [], library_dirs = []) protected
Definition at line 181 of file extbuild.py.
_convert_str_to_file()
numpy.testing._private.extbuild._convert_str_to_file (source, dirname) protected
Helper function to create a file ``source.c`` in `dirname` that contains
the string in `source`. Returns the file name
Definition at line 113 of file extbuild.py.
Referenced by compile_extension_module().
_make_methods()
numpy.testing._private.extbuild._make_methods (functions, modname) protected
 Turns the name, signature, code in functions into complete functions
and lists them in a methods_table. Then turns the methods_table into a
``PyMethodDef`` structure and returns the resulting code fragment ready
for compilation
Definition at line 123 of file extbuild.py.
Referenced by build_and_import_extension().
_make_source()
numpy.testing._private.extbuild._make_source (name, init, body) protected
 Combines the code fragments into source code ready to be compiled
Definition at line 163 of file extbuild.py.
Referenced by build_and_import_extension().
build()
numpy.testing._private.extbuild.build (cfile, outputfilename, compile_extra, link_extra, include_dirs, libraries, library_dirs)
Definition at line 212 of file extbuild.py.
build_and_import_extension()
numpy.testing._private.extbuild.build_and_import_extension (modname, functions, * , prologue = "", build_dir = None, include_dirs = [], more_init = "")
Build and imports a c-extension module `modname` from a list of function
fragments `functions`.
Parameters
----------
functions : list of fragments
    Each fragment is a sequence of func_name, calling convention, snippet.
prologue : string
    Code to precede the rest, usually extra ``#include`` or ``#define``
    macros.
build_dir : pathlib.Path
    Where to build the module, usually a temporary directory
include_dirs : list
    Extra directories to find include files when compiling
more_init : string
    Code to appear in the module PyMODINIT_FUNC
Returns
-------
out: module
    The module will have been loaded and is ready for use
Examples
--------
>>> functions = [("test_bytes", "METH_O", \"\"\"
    if ( !PyBytesCheck(args)) {
        Py_RETURN_FALSE;
    }
    Py_RETURN_TRUE;
\"\"\")]
>>> mod = build_and_import_extension("testme", functions)
>>> assert not mod.test_bytes(u'abc')
>>> assert mod.test_bytes(b'abc')
Definition at line 17 of file extbuild.py.
References _make_methods(), _make_source(), and compile_extension_module().
compile_extension_module()
numpy.testing._private.extbuild.compile_extension_module (name, builddir, include_dirs, source_string, libraries = [], library_dirs = [])
Build an extension module and return the filename of the resulting
native code file.
Parameters
----------
name : string
    name of the module, possibly including dots if it is a module inside a
    package.
builddir : pathlib.Path
    Where to build the module, usually a temporary directory
include_dirs : list
    Extra directories to find include files when compiling
libraries : list
    Libraries to link into the extension module
library_dirs: list
    Where to find the libraries, ``-L`` passed to the linker
Definition at line 80 of file extbuild.py.
References _convert_str_to_file().
Referenced by build_and_import_extension().
get_so_suffix()
numpy.testing._private.extbuild.get_so_suffix ()
Definition at line 245 of file extbuild.py.
Variable Documentation
__all__
list numpy.testing._private.extbuild.__all__ = ['build_and_import_extension', 'compile_extension_module'] private
Definition at line 14 of file extbuild.py.