Code Cloning Analysis: fontTools.ttLib.tables._n_a_m_e.NameRecordVisitor Class Reference
fontTools.ttLib.tables._n_a_m_e.NameRecordVisitor Class Reference
Public Member Functions
__init__ (self)
Public Member Functions inherited from fontTools.ttLib.ttVisitor.TTVisitor
visitAttr (self, obj, attr, value, *args, **kwargs)
visit (self, obj, *args, **kwargs)
Public Member Functions inherited from fontTools.misc.visitor.Visitor
register (celf, clazzes)
register_attr (celf, clazzes, attrs)
register_attrs (celf, clazzes_attrs)
visitObject (self, obj, *args, **kwargs)
visitList (self, obj, *args, **kwargs)
visitDict (self, obj, *args, **kwargs)
visitLeaf (self, obj, *args, **kwargs)
Public Attributes
seen = set()
Static Public Attributes
tuple TABLES = ("GSUB", "GPOS", "fvar", "CPAL", "STAT")
Static Public Attributes inherited from fontTools.misc.visitor.Visitor
bool defaultStop = False
Additional Inherited Members
Protected Member Functions inherited from fontTools.misc.visitor.Visitor
_register (celf, clazzes_attrs)
_visitorsFor (celf, thing, _default={})
Static Protected Attributes inherited from fontTools.misc.visitor.Visitor
dict _visitors
Detailed Description
Definition at line 1170 of file _n_a_m_e.py.
Constructor & Destructor Documentation
__init__()
fontTools.ttLib.tables._n_a_m_e.NameRecordVisitor.__init__ (self)
Definition at line 1174 of file _n_a_m_e.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Data Documentation
seen
fontTools.ttLib.tables._n_a_m_e.NameRecordVisitor.seen = set()
Definition at line 1175 of file _n_a_m_e.py.
TABLES
tuple fontTools.ttLib.tables._n_a_m_e.NameRecordVisitor.TABLES = ("GSUB", "GPOS", "fvar", "CPAL", "STAT") static
Definition at line 1172 of file _n_a_m_e.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ttLib/tables/_n_a_m_e.py