Code Cloning Analysis: scipy.stats._survival.ECDFResult Class Reference
scipy.stats._survival.ECDFResult Class Reference
Public Member Functions
__init__ (self, q, cdf, sf, n, d)
Public Attributes
cdf = EmpiricalDistributionFunction(q, cdf, n, d, "cdf")
sf = EmpiricalDistributionFunction(q, sf, n, d, "sf")
Detailed Description
 Result object returned by `scipy.stats.ecdf`
Attributes
----------
cdf : `~scipy.stats._result_classes.EmpiricalDistributionFunction`
    An object representing the empirical cumulative distribution function.
sf : `~scipy.stats._result_classes.EmpiricalDistributionFunction`
    An object representing the complement of the empirical cumulative
    distribution function.
Definition at line 223 of file _survival.py.
Constructor & Destructor Documentation
__init__()
scipy.stats._survival.ECDFResult.__init__ (self, q, cdf, sf, n, d)
Definition at line 237 of file _survival.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params().
Member Data Documentation
cdf
scipy.stats._survival.ECDFResult.cdf = EmpiricalDistributionFunction(q, cdf, n, d, "cdf")
Definition at line 238 of file _survival.py.
Referenced by scipy.stats._multivariate.multivariate_normal_frozen.__init__(), scipy.stats._discrete_distns.nhypergeom_gen._argcheck(), scipy.stats._distn_infrastructure.rv_continuous._delta_cdf(), scipy.stats._distn_infrastructure.rv_continuous._updated_ctor_param(), and scipy.stats._distn_infrastructure.rv_continuous.expect().
sf
scipy.stats._survival.ECDFResult.sf = EmpiricalDistributionFunction(q, sf, n, d, "sf")
Definition at line 239 of file _survival.py.
Referenced by scipy.stats._distn_infrastructure.rv_continuous._delta_cdf(), and scipy.stats._distn_infrastructure.rv_discrete.expect().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/stats/_survival.py