Code Cloning Analysis: sklearn.linear_model.tests.test_coordinate_descent Namespace Reference
sklearn.linear_model.tests.test_coordinate_descent Namespace Reference
Functions
test_set_order_dense (order, input_order)
test_set_order_sparse (order, input_order, coo_container)
test_lasso_zero ()
test_enet_nonfinite_params ()
test_lasso_toy ()
test_enet_toy ()
test_lasso_dual_gap ()
build_dataset (n_samples=50, n_features=200, n_informative_features=10, n_targets=1)
test_lasso_cv ()
test_lasso_cv_with_some_model_selection ()
test_lasso_cv_positive_constraint ()
test_lassocv_alphas_validation (alphas, err_type, err_msg)
_scale_alpha_inplace (estimator, n_samples)
test_model_pipeline_same_dense_and_sparse (LinearModel, params, csr_container)
test_lasso_path_return_models_vs_new_return_gives_same_coefficients ()
test_enet_path ()
test_path_parameters ()
test_warm_start ()
test_lasso_alpha_warning ()
test_lasso_positive_constraint ()
test_enet_positive_constraint ()
test_enet_cv_positive_constraint ()
test_uniform_targets ()
test_multi_task_lasso_and_enet ()
test_lasso_readonly_data ()
test_multi_task_lasso_readonly_data ()
test_enet_multitarget ()
test_multioutput_enetcv_error ()
test_multitask_enet_and_lasso_cv ()
test_1d_multioutput_enet_and_multitask_enet_cv ()
test_1d_multioutput_lasso_and_multitask_lasso_cv ()
test_sparse_input_dtype_enet_and_lassocv (csr_container)
test_elasticnet_precompute_incorrect_gram ()
test_elasticnet_precompute_gram_weighted_samples ()
test_elasticnet_precompute_gram ()
test_warm_start_convergence ()
test_warm_start_convergence_with_regularizer_decrement ()
test_random_descent (csr_container)
test_enet_path_positive ()
test_sparse_dense_descent_paths (csr_container)
test_path_unknown_parameter (path_func)
test_check_input_false ()
test_enet_copy_X_True (check_input)
test_enet_copy_X_False_check_input_False ()
test_overrided_gram_matrix ()
test_lasso_non_float_y (model)
test_enet_float_precision ()
test_enet_l1_ratio ()
test_coef_shape_not_zero ()
test_warm_start_multitask_lasso ()
test_enet_coordinate_descent (klass, n_classes, kwargs)
test_convergence_warnings ()
test_sparse_input_convergence_warning (csr_container)
test_lassoCV_does_not_set_precompute (monkeypatch, precompute, inner_precompute)
test_multi_task_lasso_cv_dtype ()
test_enet_sample_weight_consistency (fit_intercept, alpha, precompute, sparse_container, global_random_seed)
test_enet_cv_sample_weight_correctness (fit_intercept, sparse_container, global_random_seed)
test_enet_cv_grid_search (sample_weight)
test_enet_cv_sample_weight_consistency (fit_intercept, l1_ratio, precompute, sparse_container)
test_enet_alpha_max_sample_weight (X_is_sparse, fit_intercept, sample_weight)
test_linear_models_cv_fit_with_loky (estimator)
test_enet_sample_weight_does_not_overwrite_sample_weight (check_input)
test_enet_ridge_consistency (ridge_alpha)
test_sample_weight_invariance (estimator)
test_read_only_buffer ()
test_cv_estimators_reject_params_with_no_routing_enabled (EstimatorCV)
test_multitask_cv_estimators_with_sample_weight (MultiTaskEstimatorCV)
test_linear_model_cv_deprecated_n_alphas (Estimator)
test_linear_model_cv_deprecated_alphas_none (Estimator)
test_linear_model_cv_alphas_n_alphas_unset (Estimator)
test_linear_model_cv_alphas (Estimator)
Variables
precompute = inner_precompute
Function Documentation
_scale_alpha_inplace()
sklearn.linear_model.tests.test_coordinate_descent._scale_alpha_inplace (estimator, n_samples) protected
Rescale the parameter alpha from when the estimator is evoked with
normalize set to True as if it were evoked in a Pipeline with normalize set
to False and with a StandardScaler.
Definition at line 331 of file test_coordinate_descent.py.
References build_dataset().
build_dataset()
sklearn.linear_model.tests.test_coordinate_descent.build_dataset (n_samples = 50, n_features = 200, n_informative_features = 10, n_targets = 1)
build an ill-posed linear regression problem with many noisy features and
comparatively few samples
Definition at line 226 of file test_coordinate_descent.py.
References build_dataset().
Referenced by _scale_alpha_inplace(), build_dataset(), test_enet_coordinate_descent(), test_lasso_dual_gap(), and test_path_unknown_parameter().
test_1d_multioutput_enet_and_multitask_enet_cv()
sklearn.linear_model.tests.test_coordinate_descent.test_1d_multioutput_enet_and_multitask_enet_cv ()
Definition at line 712 of file test_coordinate_descent.py.
test_1d_multioutput_lasso_and_multitask_lasso_cv()
sklearn.linear_model.tests.test_coordinate_descent.test_1d_multioutput_lasso_and_multitask_lasso_cv ()
Definition at line 725 of file test_coordinate_descent.py.
test_check_input_false()
sklearn.linear_model.tests.test_coordinate_descent.test_check_input_false ()
Definition at line 942 of file test_coordinate_descent.py.
test_coef_shape_not_zero()
sklearn.linear_model.tests.test_coordinate_descent.test_coef_shape_not_zero ()
Definition at line 1116 of file test_coordinate_descent.py.
test_convergence_warnings()
sklearn.linear_model.tests.test_coordinate_descent.test_convergence_warnings ()
Definition at line 1158 of file test_coordinate_descent.py.
test_cv_estimators_reject_params_with_no_routing_enabled()
sklearn.linear_model.tests.test_coordinate_descent.test_cv_estimators_reject_params_with_no_routing_enabled (EstimatorCV)
Check that the models inheriting from class:`LinearModelCV` raise an
error when any `params` are passed when routing is not enabled.
Definition at line 1629 of file test_coordinate_descent.py.
test_elasticnet_precompute_gram()
sklearn.linear_model.tests.test_coordinate_descent.test_elasticnet_precompute_gram ()
Definition at line 794 of file test_coordinate_descent.py.
test_elasticnet_precompute_gram_weighted_samples()
sklearn.linear_model.tests.test_coordinate_descent.test_elasticnet_precompute_gram_weighted_samples ()
Definition at line 772 of file test_coordinate_descent.py.
test_elasticnet_precompute_incorrect_gram()
sklearn.linear_model.tests.test_coordinate_descent.test_elasticnet_precompute_incorrect_gram ()
Definition at line 755 of file test_coordinate_descent.py.
test_enet_alpha_max_sample_weight()
sklearn.linear_model.tests.test_coordinate_descent.test_enet_alpha_max_sample_weight (X_is_sparse, fit_intercept, sample_weight)
Definition at line 1474 of file test_coordinate_descent.py.
test_enet_coordinate_descent()
sklearn.linear_model.tests.test_coordinate_descent.test_enet_coordinate_descent (klass, n_classes, kwargs)
Test that a warning is issued if model does not converge
Definition at line 1141 of file test_coordinate_descent.py.
References build_dataset().
test_enet_copy_X_False_check_input_False()
sklearn.linear_model.tests.test_coordinate_descent.test_enet_copy_X_False_check_input_False ()
Definition at line 974 of file test_coordinate_descent.py.
test_enet_copy_X_True()
sklearn.linear_model.tests.test_coordinate_descent.test_enet_copy_X_True (check_input)
Definition at line 963 of file test_coordinate_descent.py.
test_enet_cv_grid_search()
sklearn.linear_model.tests.test_coordinate_descent.test_enet_cv_grid_search (sample_weight)
Test that ElasticNetCV gives same result as GridSearchCV.
Definition at line 1383 of file test_coordinate_descent.py.
test_enet_cv_positive_constraint()
sklearn.linear_model.tests.test_coordinate_descent.test_enet_cv_positive_constraint ()
Definition at line 560 of file test_coordinate_descent.py.
test_enet_cv_sample_weight_consistency()
sklearn.linear_model.tests.test_coordinate_descent.test_enet_cv_sample_weight_consistency (fit_intercept, l1_ratio, precompute, sparse_container)
Test that the impact of sample_weight is consistent.
Definition at line 1421 of file test_coordinate_descent.py.
test_enet_cv_sample_weight_correctness()
sklearn.linear_model.tests.test_coordinate_descent.test_enet_cv_sample_weight_correctness (fit_intercept, sparse_container, global_random_seed)
Test that ElasticNetCV with sample weights gives correct results.
We fit the same model twice, once with weighted training data, once with repeated
data points in the training data and check that both models converge to the
same solution.
Since this model uses an internal cross-validation scheme to tune the alpha
regularization parameter, we make sure that the repetitions only occur within
a specific CV group. Data points belonging to other CV groups stay
unit-weighted / "unrepeated".
Definition at line 1308 of file test_coordinate_descent.py.
test_enet_float_precision()
sklearn.linear_model.tests.test_coordinate_descent.test_enet_float_precision ()
Definition at line 1011 of file test_coordinate_descent.py.
test_enet_l1_ratio()
sklearn.linear_model.tests.test_coordinate_descent.test_enet_l1_ratio ()
Definition at line 1071 of file test_coordinate_descent.py.
test_enet_multitarget()
sklearn.linear_model.tests.test_coordinate_descent.test_enet_multitarget ()
Definition at line 656 of file test_coordinate_descent.py.
test_enet_nonfinite_params()
sklearn.linear_model.tests.test_coordinate_descent.test_enet_nonfinite_params ()
Definition at line 108 of file test_coordinate_descent.py.
test_enet_path()
sklearn.linear_model.tests.test_coordinate_descent.test_enet_path ()
Definition at line 438 of file test_coordinate_descent.py.
test_enet_path_positive()
sklearn.linear_model.tests.test_coordinate_descent.test_enet_path_positive ()
Definition at line 903 of file test_coordinate_descent.py.
test_enet_positive_constraint()
sklearn.linear_model.tests.test_coordinate_descent.test_enet_positive_constraint ()
Definition at line 551 of file test_coordinate_descent.py.
test_enet_ridge_consistency()
sklearn.linear_model.tests.test_coordinate_descent.test_enet_ridge_consistency (ridge_alpha)
Definition at line 1527 of file test_coordinate_descent.py.
test_enet_sample_weight_consistency()
sklearn.linear_model.tests.test_coordinate_descent.test_enet_sample_weight_consistency (fit_intercept, alpha, precompute, sparse_container, global_random_seed)
Test that the impact of sample_weight is consistent.
Note that this test is stricter than the common test
check_sample_weight_equivalence alone and also tests sparse X.
Definition at line 1221 of file test_coordinate_descent.py.
test_enet_sample_weight_does_not_overwrite_sample_weight()
sklearn.linear_model.tests.test_coordinate_descent.test_enet_sample_weight_does_not_overwrite_sample_weight (check_input)
Check that ElasticNet does not overwrite sample_weights.
Definition at line 1507 of file test_coordinate_descent.py.
test_enet_toy()
sklearn.linear_model.tests.test_coordinate_descent.test_enet_toy ()
Definition at line 161 of file test_coordinate_descent.py.
test_lasso_alpha_warning()
sklearn.linear_model.tests.test_coordinate_descent.test_lasso_alpha_warning ()
Definition at line 524 of file test_coordinate_descent.py.
test_lasso_cv()
sklearn.linear_model.tests.test_coordinate_descent.test_lasso_cv ()
Definition at line 244 of file test_coordinate_descent.py.
test_lasso_cv_positive_constraint()
sklearn.linear_model.tests.test_coordinate_descent.test_lasso_cv_positive_constraint ()
Definition at line 286 of file test_coordinate_descent.py.
test_lasso_cv_with_some_model_selection()
sklearn.linear_model.tests.test_coordinate_descent.test_lasso_cv_with_some_model_selection ()
Definition at line 274 of file test_coordinate_descent.py.
test_lasso_dual_gap()
sklearn.linear_model.tests.test_coordinate_descent.test_lasso_dual_gap ()
Check that Lasso.dual_gap_ matches its objective formulation, with the
datafit normalized by n_samples
Definition at line 208 of file test_coordinate_descent.py.
References build_dataset().
test_lasso_non_float_y()
sklearn.linear_model.tests.test_coordinate_descent.test_lasso_non_float_y (model)
Definition at line 999 of file test_coordinate_descent.py.
test_lasso_path_return_models_vs_new_return_gives_same_coefficients()
sklearn.linear_model.tests.test_coordinate_descent.test_lasso_path_return_models_vs_new_return_gives_same_coefficients ()
Definition at line 413 of file test_coordinate_descent.py.
test_lasso_positive_constraint()
sklearn.linear_model.tests.test_coordinate_descent.test_lasso_positive_constraint ()
Definition at line 538 of file test_coordinate_descent.py.
test_lasso_readonly_data()
sklearn.linear_model.tests.test_coordinate_descent.test_lasso_readonly_data ()
Definition at line 633 of file test_coordinate_descent.py.
test_lasso_toy()
sklearn.linear_model.tests.test_coordinate_descent.test_lasso_toy ()
Definition at line 123 of file test_coordinate_descent.py.
test_lasso_zero()
sklearn.linear_model.tests.test_coordinate_descent.test_lasso_zero ()
Definition at line 93 of file test_coordinate_descent.py.
test_lassocv_alphas_validation()
sklearn.linear_model.tests.test_coordinate_descent.test_lassocv_alphas_validation (alphas, err_type, err_msg)
Check the `alphas` validation in LassoCV.
Definition at line 319 of file test_coordinate_descent.py.
test_lassoCV_does_not_set_precompute()
sklearn.linear_model.tests.test_coordinate_descent.test_lassoCV_does_not_set_precompute (monkeypatch, precompute, inner_precompute)
Definition at line 1190 of file test_coordinate_descent.py.
test_linear_model_cv_alphas()
sklearn.linear_model.tests.test_coordinate_descent.test_linear_model_cv_alphas (Estimator)
Check that the behavior of alphas is consistent with n_alphas.
Definition at line 1755 of file test_coordinate_descent.py.
test_linear_model_cv_alphas_n_alphas_unset()
sklearn.linear_model.tests.test_coordinate_descent.test_linear_model_cv_alphas_n_alphas_unset (Estimator)
Check that no warning is raised when both n_alphas and alphas are unset.
Definition at line 1736 of file test_coordinate_descent.py.
test_linear_model_cv_deprecated_alphas_none()
sklearn.linear_model.tests.test_coordinate_descent.test_linear_model_cv_deprecated_alphas_none (Estimator)
Check the deprecation of alphas=None.
Definition at line 1718 of file test_coordinate_descent.py.
test_linear_model_cv_deprecated_n_alphas()
sklearn.linear_model.tests.test_coordinate_descent.test_linear_model_cv_deprecated_n_alphas (Estimator)
Check the deprecation of n_alphas in favor of alphas.
Definition at line 1689 of file test_coordinate_descent.py.
test_linear_models_cv_fit_with_loky()
sklearn.linear_model.tests.test_coordinate_descent.test_linear_models_cv_fit_with_loky (estimator)
Definition at line 1492 of file test_coordinate_descent.py.
test_model_pipeline_same_dense_and_sparse()
sklearn.linear_model.tests.test_coordinate_descent.test_model_pipeline_same_dense_and_sparse (LinearModel, params, csr_container)
Definition at line 380 of file test_coordinate_descent.py.
test_multi_task_lasso_and_enet()
sklearn.linear_model.tests.test_coordinate_descent.test_multi_task_lasso_and_enet ()
Definition at line 612 of file test_coordinate_descent.py.
test_multi_task_lasso_cv_dtype()
sklearn.linear_model.tests.test_coordinate_descent.test_multi_task_lasso_cv_dtype ()
Definition at line 1207 of file test_coordinate_descent.py.
test_multi_task_lasso_readonly_data()
sklearn.linear_model.tests.test_coordinate_descent.test_multi_task_lasso_readonly_data ()
Definition at line 646 of file test_coordinate_descent.py.
test_multioutput_enetcv_error()
sklearn.linear_model.tests.test_coordinate_descent.test_multioutput_enetcv_error ()
Definition at line 676 of file test_coordinate_descent.py.
test_multitask_cv_estimators_with_sample_weight()
sklearn.linear_model.tests.test_coordinate_descent.test_multitask_cv_estimators_with_sample_weight (MultiTaskEstimatorCV)
Check that for :class:`MultiTaskElasticNetCV` and
class:`MultiTaskLassoCV` if `sample_weight` is passed and the
CV splitter does not support `sample_weight` an error is raised.
On the other hand if the splitter does support `sample_weight`
while `sample_weight` is passed there is no error and process
completes smoothly as before.
Definition at line 1646 of file test_coordinate_descent.py.
test_multitask_enet_and_lasso_cv()
sklearn.linear_model.tests.test_coordinate_descent.test_multitask_enet_and_lasso_cv ()
Definition at line 685 of file test_coordinate_descent.py.
test_overrided_gram_matrix()
sklearn.linear_model.tests.test_coordinate_descent.test_overrided_gram_matrix ()
Definition at line 986 of file test_coordinate_descent.py.
test_path_parameters()
sklearn.linear_model.tests.test_coordinate_descent.test_path_parameters ()
Definition at line 502 of file test_coordinate_descent.py.
test_path_unknown_parameter()
sklearn.linear_model.tests.test_coordinate_descent.test_path_unknown_parameter (path_func)
Check that passing parameter not used by the coordinate descent solver
will raise an error.
Definition at line 933 of file test_coordinate_descent.py.
References build_dataset().
test_random_descent()
sklearn.linear_model.tests.test_coordinate_descent.test_random_descent (csr_container)
Definition at line 863 of file test_coordinate_descent.py.
test_read_only_buffer()
sklearn.linear_model.tests.test_coordinate_descent.test_read_only_buffer ()
Test that sparse coordinate descent works for read-only buffers
Definition at line 1613 of file test_coordinate_descent.py.
test_sample_weight_invariance()
sklearn.linear_model.tests.test_coordinate_descent.test_sample_weight_invariance (estimator)
Definition at line 1567 of file test_coordinate_descent.py.
test_set_order_dense()
sklearn.linear_model.tests.test_coordinate_descent.test_set_order_dense (order, input_order)
Check that _set_order returns arrays with promised order.
Definition at line 59 of file test_coordinate_descent.py.
test_set_order_sparse()
sklearn.linear_model.tests.test_coordinate_descent.test_set_order_sparse (order, input_order, coo_container)
Check that _set_order returns sparse matrices in promised format.
Definition at line 79 of file test_coordinate_descent.py.
test_sparse_dense_descent_paths()
sklearn.linear_model.tests.test_coordinate_descent.test_sparse_dense_descent_paths (csr_container)
Definition at line 922 of file test_coordinate_descent.py.
test_sparse_input_convergence_warning()
sklearn.linear_model.tests.test_coordinate_descent.test_sparse_input_convergence_warning (csr_container)
Definition at line 1170 of file test_coordinate_descent.py.
test_sparse_input_dtype_enet_and_lassocv()
sklearn.linear_model.tests.test_coordinate_descent.test_sparse_input_dtype_enet_and_lassocv (csr_container)
Definition at line 738 of file test_coordinate_descent.py.
test_uniform_targets()
sklearn.linear_model.tests.test_coordinate_descent.test_uniform_targets ()
Definition at line 579 of file test_coordinate_descent.py.
test_warm_start()
sklearn.linear_model.tests.test_coordinate_descent.test_warm_start ()
Definition at line 513 of file test_coordinate_descent.py.
test_warm_start_convergence()
sklearn.linear_model.tests.test_coordinate_descent.test_warm_start_convergence ()
Definition at line 817 of file test_coordinate_descent.py.
test_warm_start_convergence_with_regularizer_decrement()
sklearn.linear_model.tests.test_coordinate_descent.test_warm_start_convergence_with_regularizer_decrement ()
Definition at line 839 of file test_coordinate_descent.py.
test_warm_start_multitask_lasso()
sklearn.linear_model.tests.test_coordinate_descent.test_warm_start_multitask_lasso ()
Definition at line 1122 of file test_coordinate_descent.py.
Variable Documentation
precompute
sklearn.linear_model.tests.test_coordinate_descent.precompute = inner_precompute
Definition at line 1199 of file test_coordinate_descent.py.