Code Cloning Analysis: scipy.stats.tests.test_mstats_basic.TestCompareWithStats Class Reference
scipy.stats.tests.test_mstats_basic.TestCompareWithStats Class Reference
Public Member Functions
get_n (self)
generate_xy_sample (self, n)
generate_xy_sample2D (self, n, nx)
test_linregress (self)
test_pearsonr (self)
test_spearmanr (self)
test_spearmanr_backcompat_useties (self)
test_gmean (self)
test_hmean (self)
test_skew (self)
test_moment (self)
test_zscore (self)
test_kurtosis (self)
test_sem (self)
test_describe (self)
test_describe_result_attributes (self)
test_rankdata (self)
test_tmean (self)
test_tmax (self)
test_tmin (self)
test_zmap (self)
test_variation (self)
test_tvar (self)
test_trimboth (self)
test_tsem (self)
test_skewtest (self)
test_skewtest_result_attributes (self)
test_skewtest_2D_notmasked (self)
test_skewtest_2D_WithMask (self)
test_normaltest (self)
test_find_repeats (self)
test_kendalltau (self)
test_obrientransform (self)
test_ks_1samp (self)
test_kstest_1samp (self)
test_ks_2samp (self)
test_kstest_2samp (self)
Detailed Description
Class to compare mstats results with stats results.
It is in general assumed that scipy.stats is at a more mature stage than
stats.mstats.  If a routine in mstats results in similar results like in
scipy.stats, this is considered also as a proper validation of scipy.mstats
routine.
Different sample sizes are used for testing, as some problems between stats
and mstats are dependent on sample size.
Author: Alexander Loew
NOTE that some tests fail. This might be caused by
a) actual differences or bugs between stats and mstats
b) numerical inaccuracies
c) different definitions of routine interfaces
These failures need to be checked. Current workaround is to have disabled these tests,
but issuing reports on scipy-dev
Definition at line 1509 of file test_mstats_basic.py.
Member Function Documentation
generate_xy_sample()
scipy.stats.tests.test_mstats_basic.TestCompareWithStats.generate_xy_sample (self, n)
Definition at line 1536 of file test_mstats_basic.py.
Referenced by get_n(), test_ks_1samp(), test_ks_2samp(), test_kstest_1samp(), and test_kstest_2samp().
generate_xy_sample2D()
scipy.stats.tests.test_mstats_basic.TestCompareWithStats.generate_xy_sample2D (self, n, nx)
Definition at line 1551 of file test_mstats_basic.py.
Referenced by get_n().
get_n()
scipy.stats.tests.test_mstats_basic.TestCompareWithStats.get_n (self)
 Returns list of sample sizes to be used for comparison.
Definition at line 1532 of file test_mstats_basic.py.
References generate_xy_sample(), generate_xy_sample2D(), and get_n().
Referenced by get_n(), test_ks_1samp(), test_ks_2samp(), test_kstest_1samp(), and test_kstest_2samp().
test_describe()
scipy.stats.tests.test_mstats_basic.TestCompareWithStats.test_describe (self)
Definition at line 1693 of file test_mstats_basic.py.
test_describe_result_attributes()
scipy.stats.tests.test_mstats_basic.TestCompareWithStats.test_describe_result_attributes (self)
Definition at line 1703 of file test_mstats_basic.py.
test_find_repeats()
scipy.stats.tests.test_mstats_basic.TestCompareWithStats.test_find_repeats (self)
Definition at line 1829 of file test_mstats_basic.py.
test_gmean()
scipy.stats.tests.test_mstats_basic.TestCompareWithStats.test_gmean (self)
Definition at line 1596 of file test_mstats_basic.py.
test_hmean()
scipy.stats.tests.test_mstats_basic.TestCompareWithStats.test_hmean (self)
Definition at line 1607 of file test_mstats_basic.py.
test_kendalltau()
scipy.stats.tests.test_mstats_basic.TestCompareWithStats.test_kendalltau (self)
Definition at line 1848 of file test_mstats_basic.py.
test_ks_1samp()
scipy.stats.tests.test_mstats_basic.TestCompareWithStats.test_ks_1samp (self)
Checks that mstats.ks_1samp and stats.ks_1samp agree on masked arrays.
Definition at line 1863 of file test_mstats_basic.py.
References generate_xy_sample(), and get_n().
test_ks_2samp()
scipy.stats.tests.test_mstats_basic.TestCompareWithStats.test_ks_2samp (self)
Checks that mstats.ks_2samp and stats.ks_2samp agree on masked arrays.
gh-8431
Definition at line 1889 of file test_mstats_basic.py.
References generate_xy_sample(), and get_n().
test_kstest_1samp()
scipy.stats.tests.test_mstats_basic.TestCompareWithStats.test_kstest_1samp (self)
Checks that 1-sample mstats.kstest and stats.kstest agree on masked arrays.
Definition at line 1876 of file test_mstats_basic.py.
References generate_xy_sample(), and get_n().
test_kstest_2samp()
scipy.stats.tests.test_mstats_basic.TestCompareWithStats.test_kstest_2samp (self)
Checks that 2-sample mstats.kstest and stats.kstest agree on masked arrays.
Definition at line 1906 of file test_mstats_basic.py.
References generate_xy_sample(), and get_n().
test_kurtosis()
scipy.stats.tests.test_mstats_basic.TestCompareWithStats.test_kurtosis (self)
Definition at line 1661 of file test_mstats_basic.py.
test_linregress()
scipy.stats.tests.test_mstats_basic.TestCompareWithStats.test_linregress (self)
Definition at line 1566 of file test_mstats_basic.py.
test_moment()
scipy.stats.tests.test_mstats_basic.TestCompareWithStats.test_moment (self)
Definition at line 1631 of file test_mstats_basic.py.
test_normaltest()
scipy.stats.tests.test_mstats_basic.TestCompareWithStats.test_normaltest (self)
Definition at line 1819 of file test_mstats_basic.py.
test_obrientransform()
scipy.stats.tests.test_mstats_basic.TestCompareWithStats.test_obrientransform (self)
Definition at line 1856 of file test_mstats_basic.py.
test_pearsonr()
scipy.stats.tests.test_mstats_basic.TestCompareWithStats.test_pearsonr (self)
Definition at line 1573 of file test_mstats_basic.py.
test_rankdata()
scipy.stats.tests.test_mstats_basic.TestCompareWithStats.test_rankdata (self)
Definition at line 1709 of file test_mstats_basic.py.
test_sem()
scipy.stats.tests.test_mstats_basic.TestCompareWithStats.test_sem (self)
Definition at line 1672 of file test_mstats_basic.py.
test_skew()
scipy.stats.tests.test_mstats_basic.TestCompareWithStats.test_skew (self)
Definition at line 1619 of file test_mstats_basic.py.
test_skewtest()
scipy.stats.tests.test_mstats_basic.TestCompareWithStats.test_skewtest (self)
Definition at line 1786 of file test_mstats_basic.py.
test_skewtest_2D_notmasked()
scipy.stats.tests.test_mstats_basic.TestCompareWithStats.test_skewtest_2D_notmasked (self)
Definition at line 1801 of file test_mstats_basic.py.
test_skewtest_2D_WithMask()
scipy.stats.tests.test_mstats_basic.TestCompareWithStats.test_skewtest_2D_WithMask (self)
Definition at line 1808 of file test_mstats_basic.py.
test_skewtest_result_attributes()
scipy.stats.tests.test_mstats_basic.TestCompareWithStats.test_skewtest_result_attributes (self)
Definition at line 1795 of file test_mstats_basic.py.
test_spearmanr()
scipy.stats.tests.test_mstats_basic.TestCompareWithStats.test_spearmanr (self)
Definition at line 1582 of file test_mstats_basic.py.
test_spearmanr_backcompat_useties()
scipy.stats.tests.test_mstats_basic.TestCompareWithStats.test_spearmanr_backcompat_useties (self)
Definition at line 1590 of file test_mstats_basic.py.
test_tmax()
scipy.stats.tests.test_mstats_basic.TestCompareWithStats.test_tmax (self)
Definition at line 1722 of file test_mstats_basic.py.
test_tmean()
scipy.stats.tests.test_mstats_basic.TestCompareWithStats.test_tmean (self)
Definition at line 1716 of file test_mstats_basic.py.
test_tmin()
scipy.stats.tests.test_mstats_basic.TestCompareWithStats.test_tmin (self)
Definition at line 1735 of file test_mstats_basic.py.
test_trimboth()
scipy.stats.tests.test_mstats_basic.TestCompareWithStats.test_trimboth (self)
Definition at line 1769 of file test_mstats_basic.py.
test_tsem()
scipy.stats.tests.test_mstats_basic.TestCompareWithStats.test_tsem (self)
Definition at line 1775 of file test_mstats_basic.py.
test_tvar()
scipy.stats.tests.test_mstats_basic.TestCompareWithStats.test_tvar (self)
Definition at line 1761 of file test_mstats_basic.py.
test_variation()
scipy.stats.tests.test_mstats_basic.TestCompareWithStats.test_variation (self)
Definition at line 1753 of file test_mstats_basic.py.
test_zmap()
scipy.stats.tests.test_mstats_basic.TestCompareWithStats.test_zmap (self)
Definition at line 1746 of file test_mstats_basic.py.
test_zscore()
scipy.stats.tests.test_mstats_basic.TestCompareWithStats.test_zscore (self)
Definition at line 1643 of file test_mstats_basic.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/stats/tests/test_mstats_basic.py