Code Cloning Analysis: numpy.polynomial.tests.test_symbol.TestUnaryOperators Class Reference
numpy.polynomial.tests.test_symbol.TestUnaryOperators Class Reference
Public Member Functions
test_neg (self)
test_scalarmul (self)
test_rscalarmul (self)
test_pow (self)
Static Public Attributes
p = poly.Polynomial([1, 2, 3], symbol='z')
Detailed Description
Definition at line 60 of file test_symbol.py.
Member Function Documentation
test_neg()
numpy.polynomial.tests.test_symbol.TestUnaryOperators.test_neg (self)
Definition at line 63 of file test_symbol.py.
test_pow()
numpy.polynomial.tests.test_symbol.TestUnaryOperators.test_pow (self)
Definition at line 75 of file test_symbol.py.
test_rscalarmul()
numpy.polynomial.tests.test_symbol.TestUnaryOperators.test_rscalarmul (self)
Definition at line 71 of file test_symbol.py.
test_scalarmul()
numpy.polynomial.tests.test_symbol.TestUnaryOperators.test_scalarmul (self)
Definition at line 67 of file test_symbol.py.
Member Data Documentation
p
numpy.polynomial.tests.test_symbol.TestUnaryOperators.p = poly.Polynomial([1, 2, 3], symbol='z') static
Definition at line 61 of file test_symbol.py.
Referenced by sklearn.model_selection._split.LeavePOut._iter_test_indices(), sklearn.cluster._dbscan.DBSCAN.fit(), sklearn.cluster._optics.OPTICS.fit(), sklearn.model_selection._split.LeavePOut.get_n_splits(), sklearn.neighbors._classification.KNeighborsClassifier.predict_proba(), sklearn.neighbors._classification.RadiusNeighborsClassifier.predict_proba(), sklearn.utils.tests.test_estimator_checks.ModifiesValueInsteadOfRaisingError.set_params(), and sklearn.utils.tests.test_estimator_checks.RaisesErrorInSetParams.set_params().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/polynomial/tests/test_symbol.py