Code Cloning Analysis: pandas._config.config.option_context Class Reference
pandas._config.config.option_context Class Reference
Public Member Functions
None __init__ (self, *args)
None __enter__ (self)
None __exit__ (self, *args)
Public Attributes
ops = list(zip(args[::2], args[1::2]))
list undo = [(pat, _get_option(pat)) for pat, val in self.ops]
Detailed Description
Context manager to temporarily set options in the `with` statement context.
You need to invoke as ``option_context(pat, val, [(pat, val), ...])``.
Examples
--------
>>> from pandas import option_context
>>> with option_context('display.max_rows', 10, 'display.max_columns', 5):
...     pass
Definition at line 458 of file config.py.
Constructor & Destructor Documentation
__init__()
None pandas._config.config.option_context.__init__ (self, * args)
Definition at line 471 of file config.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__enter__()
None pandas._config.config.option_context.__enter__ (self)
Definition at line 479 of file config.py.
__exit__()
None pandas._config.config.option_context.__exit__ (self, * args)
Definition at line 485 of file config.py.
Member Data Documentation
ops
pandas._config.config.option_context.ops = list(zip(args[::2], args[1::2]))
Definition at line 477 of file config.py.
undo
list pandas._config.config.option_context.undo = [(pat, _get_option(pat)) for pat, val in self.ops]
Definition at line 480 of file config.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/_config/config.py