Code Cloning Analysis: pandas.core.methods.describe Namespace Reference
pandas.core.methods.describe Namespace Reference
Classes
class DataFrameDescriber
class NDFrameDescriberAbstract
class SeriesDescriber
Functions
NDFrameT describe_ndframe (*, NDFrameT obj, str|Sequence[str]|None include, str|Sequence[str]|None exclude, Sequence[float]|np.ndarray|None percentiles)
list[Hashable] reorder_columns (Sequence[Series] ldesc)
Series describe_numeric_1d (Series series, Sequence[float] percentiles)
Series describe_categorical_1d (Series data, Sequence[float] percentiles_ignored)
Series describe_timestamp_as_categorical_1d (Series data, Sequence[float] percentiles_ignored)
Series describe_timestamp_1d (Series data, Sequence[float] percentiles)
Callable select_describe_func (Series data)
npt.NDArray[np.float64] _refine_percentiles (Sequence[float]|np.ndarray|None percentiles)
Detailed Description
Module responsible for execution of NDFrame.describe() method.
Method NDFrame.describe() delegates actual execution to function describe_ndframe().
Function Documentation
_refine_percentiles()
npt.NDArray[np.float64] pandas.core.methods.describe._refine_percentiles (Sequence[float] | np.ndarray | None percentiles) protected
Ensure that percentiles are unique and sorted.
Parameters
----------
percentiles : list-like of numbers, optional
    The percentiles to include in the output.
Definition at line 384 of file describe.py.
Referenced by describe_ndframe().
describe_categorical_1d()
Series pandas.core.methods.describe.describe_categorical_1d (Series data, Sequence[float] percentiles_ignored)
Describe series containing categorical data.
Parameters
----------
data : Series
    Series to be described.
percentiles_ignored : list-like of numbers
    Ignored, but in place to unify interface.
Definition at line 258 of file describe.py.
describe_ndframe()
NDFrameT pandas.core.methods.describe.describe_ndframe (* , NDFrameT obj, str | Sequence[str] | None include, str | Sequence[str] | None exclude, Sequence[float] | np.ndarray | None percentiles)
Describe series or dataframe.
Called from pandas.core.generic.NDFrame.describe()
Parameters
----------
obj: DataFrame or Series
    Either dataframe or series to be described.
include : 'all', list-like of dtypes or None (default), optional
    A white list of data types to include in the result. Ignored for ``Series``.
exclude : list-like of dtypes or None (default), optional,
    A black list of data types to omit from the result. Ignored for ``Series``.
percentiles : list-like of numbers, optional
    The percentiles to include in the output. All should fall between 0 and 1.
    The default is ``[.25, .5, .75]``, which returns the 25th, 50th, and
    75th percentiles.
Returns
-------
Dataframe or series description.
Definition at line 55 of file describe.py.
References _refine_percentiles().
describe_numeric_1d()
Series pandas.core.methods.describe.describe_numeric_1d (Series series, Sequence[float] percentiles)
Describe series containing numerical data.
Parameters
----------
series : Series
    Series to be described.
percentiles : list-like of numbers
    The percentiles to include in the output.
Definition at line 217 of file describe.py.
describe_timestamp_1d()
Series pandas.core.methods.describe.describe_timestamp_1d (Series data, Sequence[float] percentiles)
Describe series containing datetime64 dtype.
Parameters
----------
data : Series
    Series to be described.
percentiles : list-like of numbers
    The percentiles to include in the output.
Definition at line 338 of file describe.py.
describe_timestamp_as_categorical_1d()
Series pandas.core.methods.describe.describe_timestamp_as_categorical_1d (Series data, Sequence[float] percentiles_ignored)
Describe series containing timestamp data treated as categorical.
Parameters
----------
data : Series
    Series to be described.
percentiles_ignored : list-like of numbers
    Ignored, but in place to unify interface.
Definition at line 290 of file describe.py.
reorder_columns()
list[Hashable] pandas.core.methods.describe.reorder_columns (Sequence[Series] ldesc)
Set a convenient order for rows for display.
Definition at line 204 of file describe.py.
Referenced by pandas.core.methods.describe.DataFrameDescriber.describe().
select_describe_func()
Callable pandas.core.methods.describe.select_describe_func (Series data)
Select proper function for describing series based on data type.
Parameters
----------
data : Series
    Series to be described.
Definition at line 362 of file describe.py.
Referenced by pandas.core.methods.describe.DataFrameDescriber.describe(), and pandas.core.methods.describe.SeriesDescriber.describe().