Code Cloning Analysis: sklearn.multiclass Namespace Reference
sklearn.multiclass Namespace Reference
Classes
class _ConstantPredictor
class OneVsOneClassifier
class OneVsRestClassifier
class OutputCodeClassifier
Functions
_fit_binary (estimator, X, y, fit_params, classes=None)
_partial_fit_binary (estimator, X, y, partial_fit_params)
_predict_binary (estimator, X)
_threshold_for_binary_predict (estimator)
_estimators_has (attr)
_fit_ovo_binary (estimator, X, y, i, j, fit_params)
_partial_fit_ovo_binary (estimator, X, y, i, j, partial_fit_params)
Variables
list __all__
estimator
Detailed Description
Multiclass learning algorithms.
- one-vs-the-rest / one-vs-all
- one-vs-one
- error correcting output codes
The estimators provided in this module are meta-estimators: they require a base
estimator to be provided in their constructor. For example, it is possible to
use these estimators to turn a binary classifier or a regressor into a
multiclass classifier. It is also possible to use these estimators with
multiclass estimators in the hope that their accuracy or runtime performance
improves.
All classifiers in scikit-learn implement multiclass classification; you
only need to use this module if you want to experiment with custom multiclass
strategies.
The one-vs-the-rest meta-classifier also implements a `predict_proba` method,
so long as such a method is implemented by the base classifier. This method
returns probabilities of class membership in both the single label and
multilabel case.  Note that in the multilabel case, probabilities are the
marginal probability that a given sample falls in the given class. As such, in
the multilabel case the sum of these probabilities over all possible labels
for a given sample *will not* sum to unity, as they do in the single label
case.
Function Documentation
_estimators_has()
sklearn.multiclass._estimators_has (attr) protected
Check if self.estimator or self.estimators_[0] has attr.
If `self.estimators_[0]` has the attr, then its safe to assume that other
estimators have it too. We raise the original `AttributeError` if `attr`
does not exist. This function is used together with `available_if`.
Definition at line 183 of file multiclass.py.
_fit_binary()
sklearn.multiclass._fit_binary (estimator, X, y, fit_params, classes = None) protected
Fit a single binary estimator.
Definition at line 81 of file multiclass.py.
Referenced by _fit_ovo_binary().
_fit_ovo_binary()
sklearn.multiclass._fit_ovo_binary (estimator, X, y, i, j, fit_params) protected
Fit a single binary estimator (one-vs-one).
Definition at line 637 of file multiclass.py.
References _fit_binary().
_partial_fit_binary()
sklearn.multiclass._partial_fit_binary (estimator, X, y, partial_fit_params) protected
Partially fit a single binary estimator.
Definition at line 100 of file multiclass.py.
Referenced by _partial_fit_ovo_binary().
_partial_fit_ovo_binary()
sklearn.multiclass._partial_fit_ovo_binary (estimator, X, y, i, j, partial_fit_params) protected
Partially fit a single binary estimator(one-vs-one).
Definition at line 659 of file multiclass.py.
References _partial_fit_binary().
_predict_binary()
sklearn.multiclass._predict_binary (estimator, X) protected
Make predictions using a single binary estimator.
Definition at line 106 of file multiclass.py.
Referenced by sklearn.multiclass.OneVsOneClassifier.decision_function(), sklearn.multiclass.OneVsRestClassifier.predict(), and sklearn.multiclass.OutputCodeClassifier.predict().
_threshold_for_binary_predict()
sklearn.multiclass._threshold_for_binary_predict (estimator) protected
Threshold for predictions from binary estimator.
Definition at line 118 of file multiclass.py.
Referenced by sklearn.multiclass.OneVsOneClassifier.predict(), and sklearn.multiclass.OneVsRestClassifier.predict().
Variable Documentation
__all__
list sklearn.multiclass.__all__ private
Initial value:
=  [
    "OneVsOneClassifier",
    "OneVsRestClassifier",
    "OutputCodeClassifier",
]
Definition at line 74 of file multiclass.py.
estimator
sklearn.multiclass.estimator
Definition at line 195 of file multiclass.py.