Code Cloning Analysis: matplotlib.patches.BoxStyle.Roundtooth Class Reference
matplotlib.patches.BoxStyle.Roundtooth Class Reference
Public Member Functions
__call__ (self, x0, y0, width, height, mutation_size)
Public Member Functions inherited from matplotlib.patches.BoxStyle.Sawtooth
__init__ (self, pad=0.3, tooth_size=None)
__call__ (self, x0, y0, width, height, mutation_size)
Additional Inherited Members
Public Attributes inherited from matplotlib.patches.BoxStyle.Sawtooth
pad = pad
tooth_size = tooth_size
Protected Member Functions inherited from matplotlib.patches.BoxStyle.Sawtooth
_get_sawtooth_vertices (self, x0, y0, width, height, mutation_size)
Detailed Description
A box with a rounded sawtooth outline.
Definition at line 2730 of file patches.py.
Member Function Documentation
__call__()
matplotlib.patches.BoxStyle.Roundtooth.__call__ (self, x0, y0, width, height, mutation_size)
Definition at line 2733 of file patches.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), scipy.interpolate._fitpack2.SphereBivariateSpline.ev(), matplotlib.ticker.Formatter.format_data(), and matplotlib.ticker.LogFormatter.format_data().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/patches.py