Code Cloning Analysis: pandas.plotting._matplotlib.tools Namespace Reference
pandas.plotting._matplotlib.tools Namespace Reference
Functions
bool do_adjust_figure (Figure fig)
None maybe_adjust_figure (Figure fig, *args, **kwargs)
None format_date_labels (Axes ax, rot)
Table table (ax, DataFrame|Series data, rowLabels=None, colLabels=None, **kwargs)
tuple[int, int] _get_layout (int nplots, tuple[int, int]|None layout=None, str layout_type="box")
create_subplots (int naxes, bool sharex=False, bool sharey=False, bool squeeze=True, subplot_kw=None, ax=None, layout=None, str layout_type="box", **fig_kw)
None _remove_labels_from_axis (Axis axis)
bool _has_externally_shared_axis (Axes ax1, str compare_axis)
None handle_shared_axes (Iterable[Axes] axarr, int nplots, int naxes, int nrows, int ncols, bool sharex, bool sharey)
np.ndarray flatten_axes (Axes|Sequence[Axes] axes)
set_ticks_props (Axes|Sequence[Axes] axes, int|None xlabelsize=None, xrot=None, int|None ylabelsize=None, yrot=None)
list[Line2D] get_all_lines (Axes ax)
tuple[float, float] get_xlim (Iterable[Line2D] lines)
Function Documentation
_get_layout()
tuple[int, int] pandas.plotting._matplotlib.tools._get_layout (int nplots, tuple[int, int] | None layout = None, str layout_type = "box") protected
Definition at line 92 of file tools.py.
_has_externally_shared_axis()
bool pandas.plotting._matplotlib.tools._has_externally_shared_axis (Axes ax1, str compare_axis) protected
Return whether an axis is externally shared.
Parameters
----------
ax1 : matplotlib.axes.Axes
    Axis to query.
compare_axis : str
    `"x"` or `"y"` according to whether the X-axis or Y-axis is being
    compared.
Returns
-------
bool
    `True` if the axis is externally shared. Otherwise `False`.
Notes
-----
If two axes with different positions are sharing an axis, they can be
referred to as *externally* sharing the common axis.
If two axes sharing an axis also have the same position, they can be
referred to as *internally* sharing the common axis (a.k.a twinning).
_handle_shared_axes() is only interested in axes externally sharing an
axis, regardless of whether either of the axes is also internally sharing
with a third axis.
Definition at line 342 of file tools.py.
References _has_externally_shared_axis().
Referenced by _has_externally_shared_axis().
_remove_labels_from_axis()
None pandas.plotting._matplotlib.tools._remove_labels_from_axis (Axis axis) protected
Definition at line 326 of file tools.py.
create_subplots()
pandas.plotting._matplotlib.tools.create_subplots (int naxes, bool sharex = False, bool sharey = False, bool squeeze = True, subplot_kw = None, ax = None, layout = None, str layout_type = "box", ** fig_kw)
Create a figure with a set of subplots already made.
This utility wrapper makes it convenient to create common layouts of
subplots, including the enclosing figure object, in a single call.
Parameters
----------
naxes : int
  Number of required axes. Exceeded axes are set invisible. Default is
  nrows * ncols.
sharex : bool
  If True, the X axis will be shared amongst all subplots.
sharey : bool
  If True, the Y axis will be shared amongst all subplots.
squeeze : bool
  If True, extra dimensions are squeezed out from the returned axis object:
    - if only one subplot is constructed (nrows=ncols=1), the resulting
    single Axis object is returned as a scalar.
    - for Nx1 or 1xN subplots, the returned object is a 1-d numpy object
    array of Axis objects are returned as numpy 1-d arrays.
    - for NxM subplots with N>1 and M>1 are returned as a 2d array.
  If False, no squeezing is done: the returned axis object is always
  a 2-d array containing Axis instances, even if it ends up being 1x1.
subplot_kw : dict
  Dict with keywords passed to the add_subplot() call used to create each
  subplots.
ax : Matplotlib axis object, optional
layout : tuple
  Number of rows and columns of the subplot grid.
  If not specified, calculated from naxes and layout_type
layout_type : {'box', 'horizontal', 'vertical'}, default 'box'
  Specify how to layout the subplot grid.
fig_kw : Other keyword arguments to be passed to the figure() call.
    Note that all keywords not recognized above will be
    automatically included here.
Returns
-------
fig, ax : tuple
  - fig is the Matplotlib Figure object
  - ax can be either a single axis object or an array of axis objects if
  more than one subplot was created.  The dimensions of the resulting array
  can be controlled with the squeeze keyword, see above.
Examples
--------
x = np.linspace(0, 2*np.pi, 400)
y = np.sin(x**2)
# Just a figure and one subplot
f, ax = plt.subplots()
ax.plot(x, y)
ax.set_title('Simple plot')
# Two subplots, unpack the output array immediately
f, (ax1, ax2) = plt.subplots(1, 2, sharey=True)
ax1.plot(x, y)
ax1.set_title('Sharing Y axis')
ax2.scatter(x, y)
# Four polar axes
plt.subplots(2, 2, subplot_kw=dict(polar=True))
Definition at line 142 of file tools.py.
do_adjust_figure()
bool pandas.plotting._matplotlib.tools.do_adjust_figure (Figure fig)
Whether fig has constrained_layout enabled.
Definition at line 39 of file tools.py.
Referenced by maybe_adjust_figure().
flatten_axes()
np.ndarray pandas.plotting._matplotlib.tools.flatten_axes (Axes | Sequence[Axes] axes)
Definition at line 445 of file tools.py.
format_date_labels()
None pandas.plotting._matplotlib.tools.format_date_labels (Axes ax, rot)
Definition at line 52 of file tools.py.
get_all_lines()
list[Line2D] pandas.plotting._matplotlib.tools.get_all_lines (Axes ax)
Definition at line 474 of file tools.py.
get_xlim()
tuple[float, float] pandas.plotting._matplotlib.tools.get_xlim (Iterable[Line2D] lines)
Definition at line 486 of file tools.py.
handle_shared_axes()
None pandas.plotting._matplotlib.tools.handle_shared_axes (Iterable[Axes] axarr, int nplots, int naxes, int nrows, int ncols, bool sharex, bool sharey)
Definition at line 392 of file tools.py.
maybe_adjust_figure()
None pandas.plotting._matplotlib.tools.maybe_adjust_figure (Figure fig, * args, ** kwargs)
Call fig.subplots_adjust unless fig has constrained_layout enabled.
Definition at line 46 of file tools.py.
References do_adjust_figure(), maybe_adjust_figure(), and matplotlib.table.table().
Referenced by maybe_adjust_figure().
set_ticks_props()
pandas.plotting._matplotlib.tools.set_ticks_props (Axes | Sequence[Axes] axes, int | None xlabelsize = None, xrot = None, int | None ylabelsize = None, yrot = None)
Definition at line 453 of file tools.py.
table()
Table pandas.plotting._matplotlib.tools.table (ax, DataFrame | Series data, rowLabels = None, colLabels = None, ** kwargs)
Definition at line 63 of file tools.py.