Code Cloning Analysis: fontTools.cu2qu.ufo Namespace Reference
fontTools.cu2qu.ufo Namespace Reference
Classes
class GetSegmentsPen
Functions
zip (*args)
_get_segments (glyph)
_set_segments (glyph, segments, reverse_direction)
_segments_to_quadratic (segments, max_err, stats, all_quadratic=True)
_glyphs_to_quadratic (glyphs, max_err, reverse_direction, stats, all_quadratic=True)
glyphs_to_quadratic (glyphs, max_err=None, reverse_direction=False, stats=None, all_quadratic=True)
fonts_to_quadratic (fonts, max_err_em=None, max_err=None, reverse_direction=False, stats=None, dump_stats=False, remember_curve_type=True, all_quadratic=True)
glyph_to_quadratic (glyph, **kwargs)
font_to_quadratic (font, **kwargs)
Variables
list __all__ = ["fonts_to_quadratic", "font_to_quadratic"]
float DEFAULT_MAX_ERR = 0.001
str CURVE_TYPE_LIB_KEY = "com.github.googlei18n.cu2qu.curve_type"
logger = logging.getLogger(__name__)
_zip = zip
Detailed Description
Converts cubic bezier curves to quadratic splines.
Conversion is performed such that the quadratic splines keep the same end-curve
tangents as the original cubics. The approach is iterative, increasing the
number of segments for a spline until the error gets below a bound.
Respective curves from multiple fonts will be converted at once to ensure that
the resulting splines are interpolation-compatible.
Function Documentation
_get_segments()
fontTools.cu2qu.ufo._get_segments (glyph) protected
Get a glyph's segments as extracted by GetSegmentsPen.
Definition at line 103 of file ufo.py.
Referenced by _glyphs_to_quadratic().
_glyphs_to_quadratic()
fontTools.cu2qu.ufo._glyphs_to_quadratic (glyphs, max_err, reverse_direction, stats, all_quadratic = True) protected
Do the actual conversion of a set of compatible glyphs, after arguments
have been set up.
Return True if the glyphs were modified, else return False.
Definition at line 164 of file ufo.py.
References _get_segments(), _segments_to_quadratic(), _set_segments(), and zip().
Referenced by fonts_to_quadratic(), and glyphs_to_quadratic().
_segments_to_quadratic()
fontTools.cu2qu.ufo._segments_to_quadratic (segments, max_err, stats, all_quadratic = True) protected
Return quadratic approximations of cubic segments.
Definition at line 146 of file ufo.py.
References fontTools.cu2qu.cu2qu.curves_to_quadratic().
Referenced by _glyphs_to_quadratic().
_set_segments()
fontTools.cu2qu.ufo._set_segments (glyph, segments, reverse_direction) protected
Draw segments as extracted by GetSegmentsPen back to a glyph.
Definition at line 122 of file ufo.py.
Referenced by _glyphs_to_quadratic().
font_to_quadratic()
fontTools.cu2qu.ufo.font_to_quadratic (font, ** kwargs)
Convenience wrapper around fonts_to_quadratic, for just one font.
Return the set of modified glyph names if any, else return empty set.
Definition at line 344 of file ufo.py.
References fonts_to_quadratic().
fonts_to_quadratic()
fontTools.cu2qu.ufo.fonts_to_quadratic (fonts, max_err_em = None, max_err = None, reverse_direction = False, stats = None, dump_stats = False, remember_curve_type = True, all_quadratic = True)
Convert the curves of a collection of fonts to quadratic.
All curves will be converted to quadratic at once, ensuring interpolation
compatibility. If this is not required, calling fonts_to_quadratic with one
font at a time may yield slightly more optimized results.
Return the set of modified glyph names if any, else return an empty set.
By default, cu2qu stores the curve type in the fonts' lib, under a private
key "com.github.googlei18n.cu2qu.curve_type", and will not try to convert
them again if the curve type is already set to "quadratic".
Setting 'remember_curve_type' to False disables this optimization.
Raises IncompatibleFontsError if same-named glyphs from different fonts
have non-interpolatable outlines.
Definition at line 237 of file ufo.py.
References _glyphs_to_quadratic(), and zip().
Referenced by font_to_quadratic().
glyph_to_quadratic()
fontTools.cu2qu.ufo.glyph_to_quadratic (glyph, ** kwargs)
Convenience wrapper around glyphs_to_quadratic, for just one glyph.
Return True if the glyph was modified, else return False.
Definition at line 336 of file ufo.py.
References glyphs_to_quadratic().
glyphs_to_quadratic()
fontTools.cu2qu.ufo.glyphs_to_quadratic (glyphs, max_err = None, reverse_direction = False, stats = None, all_quadratic = True)
Convert the curves of a set of compatible of glyphs to quadratic.
All curves will be converted to quadratic at once, ensuring interpolation
compatibility. If this is not required, calling glyphs_to_quadratic with one
glyph at a time may yield slightly more optimized results.
Return True if glyphs were modified, else return False.
Raises IncompatibleGlyphsError if glyphs have non-interpolatable outlines.
Definition at line 206 of file ufo.py.
References _glyphs_to_quadratic().
Referenced by glyph_to_quadratic().
zip()
fontTools.cu2qu.ufo.zip (* args)
Ensure each argument to zip has the same length. Also make sure a list is
returned for python 2/3 compatibility.
Definition at line 55 of file ufo.py.
Referenced by _glyphs_to_quadratic(), and fonts_to_quadratic().
Variable Documentation
__all__
list fontTools.cu2qu.ufo.__all__ = ["fonts_to_quadratic", "font_to_quadratic"] private
Definition at line 41 of file ufo.py.
_zip
fontTools.cu2qu.ufo._zip = zip protected
Definition at line 52 of file ufo.py.
CURVE_TYPE_LIB_KEY
str fontTools.cu2qu.ufo.CURVE_TYPE_LIB_KEY = "com.github.googlei18n.cu2qu.curve_type"
Definition at line 47 of file ufo.py.
DEFAULT_MAX_ERR
float fontTools.cu2qu.ufo.DEFAULT_MAX_ERR = 0.001
Definition at line 46 of file ufo.py.
logger
fontTools.cu2qu.ufo.logger = logging.getLogger(__name__)
Definition at line 49 of file ufo.py.