Code Cloning Analysis: matplotlib.dates.RRuleLocator Class Reference
matplotlib.dates.RRuleLocator Class Reference
Public Member Functions
__init__ (self, o, tz=None)
__call__ (self)
tick_values (self, vmin, vmax)
Public Member Functions inherited from matplotlib.dates.DateLocator
__init__ (self, tz=None)
set_tzinfo (self, tz)
datalim_to_dt (self)
viewlim_to_dt (self)
nonsingular (self, vmin, vmax)
Public Member Functions inherited from matplotlib.ticker.Locator
set_params (self, **kwargs)
__call__ (self)
raise_if_exceeds (self, locs)
view_limits (self, vmin, vmax)
Public Member Functions inherited from matplotlib.ticker.TickHelper
set_axis (self, axis)
create_dummy_axis (self, **kwargs)
Static Public Member Functions
get_unit_generic (freq)
Public Attributes
rule = o
Public Attributes inherited from matplotlib.dates.DateLocator
tz = _get_tzinfo(tz)
Protected Member Functions
_create_rrule (self, vmin, vmax)
_get_unit (self)
_get_interval (self)
Additional Inherited Members
Static Public Attributes inherited from matplotlib.dates.DateLocator
dict hms0d = {'byhour': 0, 'byminute': 0, 'bysecond': 0}
Static Public Attributes inherited from matplotlib.ticker.Locator
int MAXTICKS = 1000
Static Public Attributes inherited from matplotlib.ticker.TickHelper
axis = None
Detailed Description
Definition at line 1138 of file dates.py.
Constructor & Destructor Documentation
__init__()
matplotlib.dates.RRuleLocator.__init__ (self, o, tz = None)
Definition at line 1141 of file dates.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__call__()
matplotlib.dates.RRuleLocator.__call__ (self)
Definition at line 1145 of file dates.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), scipy.interpolate._fitpack2.SphereBivariateSpline.ev(), matplotlib.ticker.Formatter.format_data(), and matplotlib.ticker.LogFormatter.format_data().
_create_rrule()
matplotlib.dates.RRuleLocator._create_rrule (self, vmin, vmax) protected
Definition at line 1161 of file dates.py.
Referenced by tick_values().
_get_interval()
matplotlib.dates.RRuleLocator._get_interval (self) protected
Return the number of units for each tick.
Reimplemented from matplotlib.dates.DateLocator.
Definition at line 1210 of file dates.py.
References rule.
_get_unit()
matplotlib.dates.RRuleLocator._get_unit (self) protected
Return how many days a unit of the locator is; used for
intelligent autoscaling.
Reimplemented from matplotlib.dates.DateLocator.
Definition at line 1185 of file dates.py.
References get_unit_generic(), and rule.
get_unit_generic()
matplotlib.dates.RRuleLocator.get_unit_generic (freq) static
Definition at line 1191 of file dates.py.
Referenced by _get_unit().
tick_values()
matplotlib.dates.RRuleLocator.tick_values (self, vmin, vmax)
Return the values of the located ticks given **vmin** and **vmax**.
.. note::
    To get tick locations with the vmin and vmax values defined
    automatically for the associated ``axis`` simply call
    the Locator instance::
        >>> print(type(loc))
        <type 'Locator'>
        >>> print(loc())
        [1, 2, 3, 4]
Reimplemented from matplotlib.ticker.Locator.
Definition at line 1154 of file dates.py.
References _create_rrule(), matplotlib.dates.date2num(), matplotlib.ticker.Locator.raise_if_exceeds(), and rule.
Referenced by matplotlib.dates.MicrosecondLocator.__init__().
Member Data Documentation
rule
matplotlib.dates.RRuleLocator.rule = o
Definition at line 1143 of file dates.py.
Referenced by matplotlib.dates.YearLocator.__init__(), _get_interval(), _get_unit(), and tick_values().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/dates.py