Code Cloning Analysis: numpy.core.numerictypes Namespace Reference
numpy.core.numerictypes Namespace Reference
Classes
class _typedict
Functions
maximum_sctype (t)
issctype (rep)
obj2sctype (rep, default=None)
issubclass_ (arg1, arg2)
issubsctype (arg1, arg2)
issubdtype (arg1, arg2)
_construct_lookups ()
sctype2char (sctype)
_scalar_type_key (typ)
_find_common_coerce (a, b)
_can_coerce_all (dtypelist, start=0)
_register_types ()
find_common_type (array_types, scalar_types)
Variables
list __all__
generic = allTypes['generic']
list genericTypeRank
nbytes = _typedict()
_alignment = _typedict()
_maxvals = _typedict()
_minvals = _typedict()
cast = _typedict()
x
k
copy
list ScalarType = [int, float, complex, bool, bytes, str, memoryview]
_concrete_types
key
dict typecodes
typeDict = sctypeDict
list _kind_list = ['b', 'u', 'i', 'f', 'c', 'S', 'U', 'V', 'O', 'M', 'm']
str __test_types = '?'+typecodes['AllInteger'][:-2]+typecodes['AllFloat']+'O'
__len_test_types = len(__test_types)
Detailed Description
numerictypes: Define the numeric type objects
This module is designed so "from numerictypes import \\*" is safe.
Exported symbols include:
  Dictionary with all registered number types (including aliases):
    sctypeDict
  Type objects (not all will be available, depends on platform):
      see variable sctypes for which ones you have
    Bit-width names
    int8 int16 int32 int64 int128
    uint8 uint16 uint32 uint64 uint128
    float16 float32 float64 float96 float128 float256
    complex32 complex64 complex128 complex192 complex256 complex512
    datetime64 timedelta64
    c-based names
    bool_
    object_
    void, str_, unicode_
    byte, ubyte,
    short, ushort
    intc, uintc,
    intp, uintp,
    int_, uint,
    longlong, ulonglong,
    single, csingle,
    float_, complex_,
    longfloat, clongfloat,
   As part of the type-hierarchy:    xx -- is bit-width
   generic
     +-> bool_                                  (kind=b)
     +-> number
     |   +-> integer
     |   |   +-> signedinteger     (intxx)      (kind=i)
     |   |   |     byte
     |   |   |     short
     |   |   |     intc
     |   |   |     intp
     |   |   |     int_
     |   |   |     longlong
     |   |   \\-> unsignedinteger  (uintxx)     (kind=u)
     |   |         ubyte
     |   |         ushort
     |   |         uintc
     |   |         uintp
     |   |         uint_
     |   |         ulonglong
     |   +-> inexact
     |       +-> floating          (floatxx)    (kind=f)
     |       |     half
     |       |     single
     |       |     float_          (double)
     |       |     longfloat
     |       \\-> complexfloating  (complexxx)  (kind=c)
     |             csingle         (singlecomplex)
     |             complex_        (cfloat, cdouble)
     |             clongfloat      (longcomplex)
     +-> flexible
     |   +-> character
     |   |     str_     (string_, bytes_)       (kind=S)    [Python 2]
     |   |     unicode_                         (kind=U)    [Python 2]
     |   |
     |   |     bytes_   (string_)               (kind=S)    [Python 3]
     |   |     str_     (unicode_)              (kind=U)    [Python 3]
     |   |
     |   \\-> void                              (kind=V)
     \\-> object_ (not used much)               (kind=O)
Function Documentation
_can_coerce_all()
numpy.core.numerictypes._can_coerce_all (dtypelist, start = 0) protected
Definition at line 574 of file numerictypes.py.
_construct_lookups()
numpy.core.numerictypes._construct_lookups () protected
Definition at line 441 of file numerictypes.py.
_find_common_coerce()
numpy.core.numerictypes._find_common_coerce (a, b) protected
Definition at line 564 of file numerictypes.py.
_register_types()
numpy.core.numerictypes._register_types () protected
Definition at line 589 of file numerictypes.py.
_scalar_type_key()
numpy.core.numerictypes._scalar_type_key (typ) protected
A ``key`` function for `sorted`.
Definition at line 514 of file numerictypes.py.
find_common_type()
numpy.core.numerictypes.find_common_type (array_types, scalar_types)
Determine common type following standard coercion rules.
.. deprecated:: NumPy 1.25
    This function is deprecated, use `numpy.promote_types` or
    `numpy.result_type` instead.  To achieve semantics for the
    `scalar_types` argument, use `numpy.result_type` and pass the Python
    values `0`, `0.0`, or `0j`.
    This will give the same results in almost all cases.
    More information and rare exception can be found in the
    `NumPy 1.25 release notes <https://numpy.org/devdocs/release/1.25.0-notes.html>`_.
Parameters
----------
array_types : sequence
    A list of dtypes or dtype convertible objects representing arrays.
scalar_types : sequence
    A list of dtypes or dtype convertible objects representing scalars.
Returns
-------
datatype : dtype
    The common data type, which is the maximum of `array_types` ignoring
    `scalar_types`, unless the maximum of `scalar_types` is of a
    different kind (`dtype.kind`). If the kind is not understood, then
    None is returned.
See Also
--------
dtype, common_type, can_cast, mintypecode
Examples
--------
>>> np.find_common_type([], [np.int64, np.float32, complex])
dtype('complex128')
>>> np.find_common_type([np.int64, np.float32], [])
dtype('float64')
The standard casting rules ensure that a scalar cannot up-cast an
array unless the scalar is of a fundamentally different kind of data
(i.e. under a different hierarchy in the data type hierarchy) then
the array:
>>> np.find_common_type([np.float32], [np.int64, np.float64])
dtype('float32')
Complex is of a different type, so it up-casts the float in the
`array_types` argument:
>>> np.find_common_type([np.float32], [complex])
dtype('complex128')
Type specifier strings are convertible to dtypes and can therefore
be used instead of dtypes:
>>> np.find_common_type(['f4', 'f4', 'i4'], ['c8'])
dtype('complex128')
Definition at line 599 of file numerictypes.py.
issctype()
numpy.core.numerictypes.issctype (rep)
Determines whether the given object represents a scalar data-type.
Parameters
----------
rep : any
    If `rep` is an instance of a scalar dtype, True is returned. If not,
    False is returned.
Returns
-------
out : bool
    Boolean result of check whether `rep` is a scalar dtype.
See Also
--------
issubsctype, issubdtype, obj2sctype, sctype2char
Examples
--------
>>> np.issctype(np.int32)
True
>>> np.issctype(list)
False
>>> np.issctype(1.1)
False
Strings are also a scalar type:
>>> np.issctype(np.dtype('str'))
True
Definition at line 184 of file numerictypes.py.
References obj2sctype().
issubclass_()
numpy.core.numerictypes.issubclass_ (arg1, arg2)
Determine if a class is a subclass of a second class.
`issubclass_` is equivalent to the Python built-in ``issubclass``,
except that it returns False instead of raising a TypeError if one
of the arguments is not a class.
Parameters
----------
arg1 : class
    Input class. True is returned if `arg1` is a subclass of `arg2`.
arg2 : class or tuple of classes.
    Input class. If a tuple of classes, True is returned if `arg1` is a
    subclass of any of the tuple elements.
Returns
-------
out : bool
    Whether `arg1` is a subclass of `arg2` or not.
See Also
--------
issubsctype, issubdtype, issctype
Examples
--------
>>> np.issubclass_(np.int32, int)
False
>>> np.issubclass_(np.int32, float)
False
>>> np.issubclass_(np.float64, float)
True
Definition at line 284 of file numerictypes.py.
Referenced by issubdtype().
issubdtype()
numpy.core.numerictypes.issubdtype (arg1, arg2)
Returns True if first argument is a typecode lower/equal in type hierarchy.
This is like the builtin :func:`issubclass`, but for `dtype`\ s.
Parameters
----------
arg1, arg2 : dtype_like
    `dtype` or object coercible to one
Returns
-------
out : bool
See Also
--------
:ref:`arrays.scalars` : Overview of the numpy type hierarchy.
issubsctype, issubclass_
Examples
--------
`issubdtype` can be used to check the type of arrays:
>>> ints = np.array([1, 2, 3], dtype=np.int32)
>>> np.issubdtype(ints.dtype, np.integer)
True
>>> np.issubdtype(ints.dtype, np.floating)
False
>>> floats = np.array([1, 2, 3], dtype=np.float32)
>>> np.issubdtype(floats.dtype, np.integer)
False
>>> np.issubdtype(floats.dtype, np.floating)
True
Similar types of different sizes are not subdtypes of each other:
>>> np.issubdtype(np.float64, np.float32)
False
>>> np.issubdtype(np.float32, np.float64)
False
but both are subtypes of `floating`:
>>> np.issubdtype(np.float64, np.floating)
True
>>> np.issubdtype(np.float32, np.floating)
True
For convenience, dtype-like objects are allowed too:
>>> np.issubdtype('S1', np.string_)
True
>>> np.issubdtype('i4', np.signedinteger)
True
Definition at line 358 of file numerictypes.py.
References issubclass_().
Referenced by numpy.testing._private.utils.assert_array_almost_equal(), and numpy.lib.index_tricks.ix_().
issubsctype()
numpy.core.numerictypes.issubsctype (arg1, arg2)
Determine if the first argument is a subclass of the second argument.
Parameters
----------
arg1, arg2 : dtype or dtype specifier
    Data-types.
Returns
-------
out : bool
    The result.
See Also
--------
issctype, issubdtype, obj2sctype
Examples
--------
>>> np.issubsctype('S8', str)
False
>>> np.issubsctype(np.array([1]), int)
True
>>> np.issubsctype(np.array([1]), float)
False
Definition at line 326 of file numerictypes.py.
References obj2sctype().
maximum_sctype()
numpy.core.numerictypes.maximum_sctype (t)
Return the scalar type of highest precision of the same kind as the input.
Parameters
----------
t : dtype or dtype specifier
    The input data type. This can be a `dtype` object or an object that
    is convertible to a `dtype`.
Returns
-------
out : dtype
    The highest precision data type of the same kind (`dtype.kind`) as `t`.
See Also
--------
obj2sctype, mintypecode, sctype2char
dtype
Examples
--------
>>> np.maximum_sctype(int)
<class 'numpy.int64'>
>>> np.maximum_sctype(np.uint8)
<class 'numpy.uint64'>
>>> np.maximum_sctype(complex)
<class 'numpy.complex256'> # may vary
>>> np.maximum_sctype(str)
<class 'numpy.str_'>
>>> np.maximum_sctype('i2')
<class 'numpy.int64'>
>>> np.maximum_sctype('f4')
<class 'numpy.float128'> # may vary
Definition at line 134 of file numerictypes.py.
References obj2sctype().
obj2sctype()
numpy.core.numerictypes.obj2sctype (rep, default = None)
Return the scalar dtype or NumPy equivalent of Python type of an object.
Parameters
----------
rep : any
    The object of which the type is returned.
default : any, optional
    If given, this is returned for objects whose types can not be
    determined. If not given, None is returned for those objects.
Returns
-------
dtype : dtype or Python type
    The data type of `rep`.
See Also
--------
sctype2char, issctype, issubsctype, issubdtype, maximum_sctype
Examples
--------
>>> np.obj2sctype(np.int32)
<class 'numpy.int32'>
>>> np.obj2sctype(np.array([1., 2.]))
<class 'numpy.float64'>
>>> np.obj2sctype(np.array([1.j]))
<class 'numpy.complex128'>
>>> np.obj2sctype(dict)
<class 'numpy.object_'>
>>> np.obj2sctype('string')
>>> np.obj2sctype(1, default=list)
<class 'list'>
Definition at line 230 of file numerictypes.py.
Referenced by issctype(), issubsctype(), maximum_sctype(), and sctype2char().
sctype2char()
numpy.core.numerictypes.sctype2char (sctype)
Return the string representation of a scalar dtype.
Parameters
----------
sctype : scalar dtype or object
    If a scalar dtype, the corresponding string character is
    returned. If an object, `sctype2char` tries to infer its scalar type
    and then return the corresponding string character.
Returns
-------
typechar : str
    The string character corresponding to the scalar type.
Raises
------
ValueError
    If `sctype` is an object for which the type can not be inferred.
See Also
--------
obj2sctype, issctype, issubsctype, mintypecode
Examples
--------
>>> for sctype in [np.int32, np.double, np.complex_, np.string_, np.ndarray]:
...     print(np.sctype2char(sctype))
l # may vary
d
D
S
O
>>> x = np.array([1., 2-1.j])
>>> np.sctype2char(x)
'D'
>>> np.sctype2char(list)
'O'
Definition at line 457 of file numerictypes.py.
References obj2sctype().
Variable Documentation
__all__
list numpy.core.numerictypes.__all__ private
Initial value:
=  ['sctypeDict', 'sctypes',
           'ScalarType', 'obj2sctype', 'cast', 'nbytes', 'sctype2char',
           'maximum_sctype', 'issctype', 'typecodes', 'find_common_type',
           'issubdtype', 'datetime_data', 'datetime_as_string',
           'busday_offset', 'busday_count', 'is_busday', 'busdaycalendar',
           ]
Definition at line 92 of file numerictypes.py.
__len_test_types
numpy.core.numerictypes.__len_test_types = len(__test_types) private
Definition at line 560 of file numerictypes.py.
__test_types
str numpy.core.numerictypes.__test_types = '?'+typecodes['AllInteger'][:-2]+typecodes['AllFloat']+'O' private
Definition at line 559 of file numerictypes.py.
_alignment
numpy.core.numerictypes._alignment = _typedict() protected
Definition at line 438 of file numerictypes.py.
_concrete_types
numpy.core.numerictypes._concrete_types protected
Definition at line 521 of file numerictypes.py.
_kind_list
list numpy.core.numerictypes._kind_list = ['b', 'u', 'i', 'f', 'c', 'S', 'U', 'V', 'O', 'M', 'm'] protected
Definition at line 557 of file numerictypes.py.
_maxvals
numpy.core.numerictypes._maxvals = _typedict() protected
Definition at line 439 of file numerictypes.py.
_minvals
numpy.core.numerictypes._minvals = _typedict() protected
Definition at line 440 of file numerictypes.py.
cast
numpy.core.numerictypes.cast = _typedict()
Definition at line 509 of file numerictypes.py.
copy
numpy.core.numerictypes.copy
Definition at line 511 of file numerictypes.py.
generic
numpy.core.numerictypes.generic = allTypes['generic']
Definition at line 123 of file numerictypes.py.
genericTypeRank
list numpy.core.numerictypes.genericTypeRank
Initial value:
=  ['bool', 'int8', 'uint8', 'int16', 'uint16',
                   'int32', 'uint32', 'int64', 'uint64', 'int128',
                   'uint128', 'float16',
                   'float32', 'float64', 'float80', 'float96', 'float128',
                   'float256',
                   'complex32', 'complex64', 'complex128', 'complex160',
                   'complex192', 'complex256', 'complex512', 'object']
Definition at line 125 of file numerictypes.py.
k
numpy.core.numerictypes.k
Definition at line 511 of file numerictypes.py.
key
numpy.core.numerictypes.key
Definition at line 521 of file numerictypes.py.
nbytes
numpy.core.numerictypes.nbytes = _typedict()
Definition at line 437 of file numerictypes.py.
ScalarType
numpy.core.numerictypes.ScalarType = [int, float, complex, bool, bytes, str, memoryview]
Definition at line 520 of file numerictypes.py.
typecodes
dict numpy.core.numerictypes.typecodes
Initial value:
=  {'Character':'c',
             'Integer':'bhilqp',
             'UnsignedInteger':'BHILQP',
             'Float':'efdg',
             'Complex':'FDG',
             'AllInteger':'bBhHiIlLqQpP',
             'AllFloat':'efdgFDG',
             'Datetime': 'Mm',
             'All':'?bhilqpBHILQPefdgFDGSUVOMm'}
Definition at line 532 of file numerictypes.py.
typeDict
numpy.core.numerictypes.typeDict = sctypeDict
Definition at line 544 of file numerictypes.py.
x
numpy.core.numerictypes.x
Definition at line 511 of file numerictypes.py.