Code Cloning Analysis: numpy.ma.tests.test_subclassing.CSAIterator Class Reference
numpy.ma.tests.test_subclassing.CSAIterator Class Reference
Public Member Functions
__init__ (self, a)
__iter__ (self)
__getitem__ (self, indx)
__setitem__ (self, index, value)
__next__ (self)
Protected Attributes
_original = a
_dataiter = a.view(np.ndarray).flat
Detailed Description
Flat iterator object that uses its own setter/getter
(works around ndarray.flat not propagating subclass setters/getters
see https://github.com/numpy/numpy/issues/4564)
roughly following MaskedIterator
Definition at line 80 of file test_subclassing.py.
Constructor & Destructor Documentation
__init__()
numpy.ma.tests.test_subclassing.CSAIterator.__init__ (self, a)
Definition at line 87 of file test_subclassing.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__getitem__()
numpy.ma.tests.test_subclassing.CSAIterator.__getitem__ (self, indx)
Definition at line 94 of file test_subclassing.py.
__iter__()
numpy.ma.tests.test_subclassing.CSAIterator.__iter__ (self)
Definition at line 91 of file test_subclassing.py.
__next__()
numpy.ma.tests.test_subclassing.CSAIterator.__next__ (self)
Definition at line 104 of file test_subclassing.py.
__setitem__()
numpy.ma.tests.test_subclassing.CSAIterator.__setitem__ (self, index, value)
Definition at line 101 of file test_subclassing.py.
Member Data Documentation
_dataiter
numpy.ma.tests.test_subclassing.CSAIterator._dataiter = a.view(np.ndarray).flat protected
Definition at line 89 of file test_subclassing.py.
_original
numpy.ma.tests.test_subclassing.CSAIterator._original = a protected
Definition at line 88 of file test_subclassing.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/ma/tests/test_subclassing.py