Code Cloning Analysis: matplotlib.sphinxext.figmpl_directive.FigureMpl Class Reference
matplotlib.sphinxext.figmpl_directive.FigureMpl Class Reference
Public Member Functions
run (self)
Static Public Attributes
bool has_content = False
int required_arguments = 1
int optional_arguments = 2
bool final_argument_whitespace = False
dict option_spec
Detailed Description
Implements a directive to allow an optional hidpi image.
Meant to be used with the *plot_srcset* configuration option in conf.py,
and gets set in the TEMPLATE of plot_directive.py
e.g.::
    .. figure-mpl:: plot_directive/some_plots-1.png
        :alt: bar
        :srcset: plot_directive/some_plots-1.png,
                 plot_directive/some_plots-1.2x.png 2.00x
        :class: plot-directive
The resulting html (at ``some_plots.html``) is::
    <img src="sphx_glr_bar_001_hidpi.png"
        srcset="_images/some_plot-1.png,
                _images/some_plots-1.2x.png 2.00x",
        alt="bar"
        class="plot_directive" />
Note that the handling of subdirectories is different than that used by the sphinx
figure directive::
    .. figure-mpl:: plot_directive/nestedpage/index-1.png
        :alt: bar
        :srcset: plot_directive/nestedpage/index-1.png
                 plot_directive/nestedpage/index-1.2x.png 2.00x
        :class: plot_directive
The resulting html (at ``nestedpage/index.html``)::
    <img src="../_images/nestedpage-index-1.png"
        srcset="../_images/nestedpage-index-1.png,
                ../_images/_images/nestedpage-index-1.2x.png 2.00x",
        alt="bar"
        class="sphx-glr-single-img" />
where the subdirectory is included in the image name for uniqueness.
Definition at line 32 of file figmpl_directive.py.
Member Function Documentation
run()
matplotlib.sphinxext.figmpl_directive.FigureMpl.run (self)
Definition at line 90 of file figmpl_directive.py.
Referenced by scipy.odr._odrpack.ODR.restart(), scipy.integrate._ode.lsoda.run_relax(), scipy.integrate._ode.vode.run_relax(), scipy.integrate._ode.lsoda.step(), and scipy.integrate._ode.vode.step().
Member Data Documentation
final_argument_whitespace
bool matplotlib.sphinxext.figmpl_directive.FigureMpl.final_argument_whitespace = False static
Definition at line 78 of file figmpl_directive.py.
has_content
bool matplotlib.sphinxext.figmpl_directive.FigureMpl.has_content = False static
Definition at line 75 of file figmpl_directive.py.
option_spec
dict matplotlib.sphinxext.figmpl_directive.FigureMpl.option_spec static
Initial value:
=  {
        'alt': directives.unchanged,
        'height': directives.length_or_unitless,
        'width': directives.length_or_percentage_or_unitless,
        'scale': directives.nonnegative_int,
        'align': Image.align,
        'class': directives.class_option,
        'caption': directives.unchanged,
        'srcset': directives.unchanged,
    }
Definition at line 79 of file figmpl_directive.py.
optional_arguments
int matplotlib.sphinxext.figmpl_directive.FigureMpl.optional_arguments = 2 static
Definition at line 77 of file figmpl_directive.py.
required_arguments
int matplotlib.sphinxext.figmpl_directive.FigureMpl.required_arguments = 1 static
Definition at line 76 of file figmpl_directive.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/sphinxext/figmpl_directive.py