Code Cloning Analysis: axes_grid1.inset_locator._TransformedBboxWithCallback Class Reference
axes_grid1.inset_locator._TransformedBboxWithCallback Class Reference
Public Member Functions
__init__ (self, *args, callback, **kwargs)
get_points (self)
Public Member Functions inherited from matplotlib.transforms.TransformedBbox
__init__ (self, bbox, transform, **kwargs)
contains (self, x, y)
fully_contains (self, x, y)
Public Member Functions inherited from matplotlib.transforms.BboxBase
frozen (self)
__array__ (self, *args, **kwargs)
x0 (self)
y0 (self)
x1 (self)
y1 (self)
p0 (self)
p1 (self)
xmin (self)
ymin (self)
xmax (self)
ymax (self)
min (self)
max (self)
intervalx (self)
intervaly (self)
width (self)
height (self)
size (self)
bounds (self)
extents (self)
containsx (self, x)
containsy (self, y)
overlaps (self, other)
fully_containsx (self, x)
fully_containsy (self, y)
fully_overlaps (self, other)
transformed (self, transform)
anchored (self, c, container)
shrunk (self, mx, my)
shrunk_to_aspect (self, box_aspect, container=None, fig_aspect=1.0)
splitx (self, *args)
splity (self, *args)
count_contains (self, vertices)
count_overlaps (self, bboxes)
expanded (self, sw, sh)
padded (self, w_pad, h_pad=None)
translated (self, tx, ty)
corners (self)
rotated (self, radians)
Public Member Functions inherited from matplotlib.transforms.TransformNode
__init__ (self, shorthand_name=None)
__str__ (self)
__getstate__ (self)
__setstate__ (self, data_dict)
__copy__ (self)
invalidate (self)
set_children (self, *children)
Protected Attributes
_callback = callback
Protected Attributes inherited from matplotlib.transforms.TransformedBbox
_bbox = bbox
_transform = transform
_points = None
Protected Attributes inherited from matplotlib.transforms.TransformNode
dict _parents = {}
_invalid = self._INVALID_FULL
str _shorthand_name = shorthand_name or ''
Additional Inherited Members
Static Public Member Functions inherited from matplotlib.transforms.BboxBase
union (bboxes)
intersection (bbox1, bbox2)
Public Attributes inherited from matplotlib.transforms.BboxBase
max
Static Public Attributes inherited from matplotlib.transforms.BboxBase
dict coefs
Static Public Attributes inherited from matplotlib.transforms.TransformNode
bool is_affine = False
is_bbox = _api.deprecated("3.9")(_api.classproperty(lambda cls: False))
bool pass_through = False
Protected Member Functions inherited from matplotlib.transforms.TransformNode
_invalidate_internal (self, level, invalidating_node)
Static Protected Member Functions inherited from matplotlib.transforms.BboxBase
_check (points)
Static Protected Attributes inherited from matplotlib.transforms.TransformedBbox
_get_points = get_points
Static Protected Attributes inherited from matplotlib.transforms.TransformNode
_VALID
_INVALID_AFFINE_ONLY
_INVALID_FULL
Detailed Description
Variant of `.TransformBbox` which calls *callback* before returning points.
Used by `.mark_inset` to unstale the parent axes' viewlim as needed.
Definition at line 454 of file inset_locator.py.
Constructor & Destructor Documentation
__init__()
axes_grid1.inset_locator._TransformedBboxWithCallback.__init__ (self, * args, callback, ** kwargs)
Definition at line 461 of file inset_locator.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
get_points()
axes_grid1.inset_locator._TransformedBboxWithCallback.get_points (self)
Reimplemented from matplotlib.transforms.TransformedBbox.
Definition at line 465 of file inset_locator.py.
Member Data Documentation
_callback
axes_grid1.inset_locator._TransformedBboxWithCallback._callback = callback protected
Definition at line 463 of file inset_locator.py.
Referenced by sklearn.neighbors._nca.NeighborhoodComponentsAnalysis.fit().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/mpl_toolkits/axes_grid1/inset_locator.py