Code Cloning Analysis: fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf Class Reference
fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf Class Reference
Public Member Functions
__init__ (self, font, location, recalcBounds=True)
__getitem__ (self, glyphName)
Public Member Functions inherited from fontTools.ttLib.ttGlyphSet._TTGlyphSet
__init__ (self, font, location, glyphsMapping, *, recalcBounds=True)
pushLocation (self, location, bool reset)
pushDepth (self)
__contains__ (self, glyphName)
__iter__ (self)
__len__ (self)
has_key (self, glyphName)
Public Attributes
glyfTable = font["glyf"]
gvarTable = font.get("gvar")
Public Attributes inherited from fontTools.ttLib.ttGlyphSet._TTGlyphSet
recalcBounds = recalcBounds
font = font
tuple defaultLocationNormalized
list location = location if location is not None else {}
dict rawLocation = {}
originalLocation = location if location is not None else {}
int depth = 0
list locationStack = []
list rawLocationStack = []
glyphsMapping = glyphsMapping
hMetrics = font["hmtx"].metrics
vMetrics = getattr(font.get("vmtx"), "metrics", None)
hvarTable = None
hvarInstancer
Detailed Description
Definition at line 97 of file ttGlyphSet.py.
Constructor & Destructor Documentation
__init__()
fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf.__init__ (self, font, location, recalcBounds = True)
Definition at line 98 of file ttGlyphSet.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__getitem__()
fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf.__getitem__ (self, glyphName)
Definition at line 103 of file ttGlyphSet.py.
Member Data Documentation
glyfTable
fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf.glyfTable = font["glyf"]
Definition at line 99 of file ttGlyphSet.py.
gvarTable
fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf.gvarTable = font.get("gvar")
Definition at line 101 of file ttGlyphSet.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ttLib/ttGlyphSet.py