Code Cloning Analysis: fontTools.varLib Namespace Reference
fontTools.varLib Namespace Reference
Namespaces
namespace featureVars
namespace instancer
namespace interpolatable
namespace interpolate_layout
namespace merger
namespace models
namespace mutator
namespace plot
namespace stat
Classes
class MasterFinder
Functions
_add_fvar (font, axes, List[InstanceDescriptor] instances)
_add_avar (font, axes, mappings, axisTags)
_add_stat (font)
_add_gvar (font, masterModel, master_ttfs, tolerance=0.5, optimize=True)
_remove_TTHinting (font)
_merge_TTHinting (font, masterModel, master_ttfs)
_add_HVAR (font, masterModel, master_ttfs, axisTags)
_add_VVAR (font, masterModel, master_ttfs, axisTags)
_add_VHVAR (font, axisTags, tableFields, getAdvanceMetrics)
_get_advance_metrics (font, masterModel, master_ttfs, axisTags, tableFields)
_add_MVAR (font, masterModel, master_ttfs, axisTags)
_add_BASE (font, masterModel, master_ttfs, axisTags)
_merge_OTL (font, model, master_fonts, axisTags)
_add_GSUB_feature_variations (font, axes, internal_axis_supports, rules, featureTags)
_add_CFF2 (varFont, model, master_fonts)
_add_COLR (font, model, master_fonts, axisTags, colr_layer_reuse=True)
load_designspace (designspace, log_enabled=True, *, require_sources=True)
set_default_weight_width_slant (font, location)
int drop_implied_oncurve_points (*TTFont masters)
build_many (DesignSpaceDocument designspace, master_finder=lambda s:s, exclude=[], optimize=True, skip_vf=lambda vf_name:False, colr_layer_reuse=True, drop_implied_oncurves=False)
build (designspace, master_finder=lambda s:s, exclude=[], optimize=True, colr_layer_reuse=True, drop_implied_oncurves=False)
_open_font (path, master_finder=lambda s:s)
load_masters (designspace, master_finder=lambda s:s)
_feature_variations_tags (ds)
addGSUBFeatureVariations (vf, designspace, featureTags=(), *, log_enabled=False)
main (args=None)
Variables
log = logging.getLogger("fontTools.varLib")
str FEAVAR_FEATURETAG_LIB_KEY = "com.github.fonttools.varLib.featureVarsFeatureTag"
_MasterData = namedtuple("_MasterData", ["glyf", "hMetrics", "vMetrics"])
_MetricsFields
HVAR_FIELDS
VVAR_FIELDS
_DesignSpaceData
dict WDTH_VALUE_TO_OS2_WIDTH_CLASS
Detailed Description
Module for dealing with 'gvar'-style font variations, also known as run-time
interpolation.
The ideas here are very similar to MutatorMath.  There is even code to read
MutatorMath .designspace files in the varLib.designspace module.
For now, if you run this file on a designspace file, it tries to find
ttf-interpolatable files for the masters and build a variable-font from
them.  Such ttf-interpolatable and designspace files can be generated from
a Glyphs source, eg., using noto-source as an example:
    .. code-block:: sh
        $ fontmake -o ttf-interpolatable -g NotoSansArabic-MM.glyphs
Then you can make a variable-font this way:
    .. code-block:: sh
        $ fonttools varLib master_ufo/NotoSansArabic.designspace
API *will* change in near future.
Function Documentation
_add_avar()
fontTools.varLib._add_avar (font, axes, mappings, axisTags) protected
Add 'avar' table to font.
axes is an ordered dictionary of AxisDescriptor objects.
Definition at line 163 of file __init__.py.
Referenced by build(), and fontTools.varLib.avar.main().
_add_BASE()
fontTools.varLib._add_BASE (font, masterModel, master_ttfs, axisTags) protected
Definition at line 761 of file __init__.py.
_add_CFF2()
fontTools.varLib._add_CFF2 (varFont, model, master_fonts) protected
Definition at line 864 of file __init__.py.
_add_COLR()
fontTools.varLib._add_COLR (font, model, master_fonts, axisTags, colr_layer_reuse = True) protected
Definition at line 878 of file __init__.py.
_add_fvar()
fontTools.varLib._add_fvar (font, axes, List[InstanceDescriptor] instances) protected
Add 'fvar' table to font.
axes is an ordered dictionary of DesignspaceAxis objects.
instances is list of dictionary objects with 'location', 'stylename',
and possibly 'postscriptfontname' entries.
Definition at line 70 of file __init__.py.
Referenced by build().
_add_GSUB_feature_variations()
fontTools.varLib._add_GSUB_feature_variations (font, axes, internal_axis_supports, rules, featureTags) protected
Definition at line 811 of file __init__.py.
_add_gvar()
fontTools.varLib._add_gvar (font, masterModel, master_ttfs, tolerance = 0.5, optimize = True) protected
Definition at line 321 of file __init__.py.
_add_HVAR()
fontTools.varLib._add_HVAR (font, masterModel, master_ttfs, axisTags) protected
Definition at line 526 of file __init__.py.
_add_MVAR()
fontTools.varLib._add_MVAR (font, masterModel, master_ttfs, axisTags) protected
Definition at line 683 of file __init__.py.
_add_stat()
fontTools.varLib._add_stat (font) protected
Definition at line 303 of file __init__.py.
_add_VHVAR()
fontTools.varLib._add_VHVAR (font, axisTags, tableFields, getAdvanceMetrics) protected
Definition at line 540 of file __init__.py.
_add_VVAR()
fontTools.varLib._add_VVAR (font, masterModel, master_ttfs, axisTags) protected
Definition at line 533 of file __init__.py.
_feature_variations_tags()
fontTools.varLib._feature_variations_tags (ds) protected
Definition at line 1335 of file __init__.py.
_get_advance_metrics()
fontTools.varLib._get_advance_metrics (font, masterModel, master_ttfs, axisTags, tableFields) protected
Definition at line 631 of file __init__.py.
_merge_OTL()
fontTools.varLib._merge_OTL (font, model, master_fonts, axisTags) protected
Definition at line 776 of file __init__.py.
_merge_TTHinting()
fontTools.varLib._merge_TTHinting (font, masterModel, master_ttfs) protected
Definition at line 422 of file __init__.py.
_open_font()
fontTools.varLib._open_font (path, master_finder = lambda s: s) protected
Definition at line 1270 of file __init__.py.
_remove_TTHinting()
fontTools.varLib._remove_TTHinting (font) protected
Definition at line 403 of file __init__.py.
addGSUBFeatureVariations()
fontTools.varLib.addGSUBFeatureVariations (vf, designspace, featureTags = (), * , log_enabled = False)
Add GSUB FeatureVariations table to variable font, based on DesignSpace rules.
Args:
    vf: A TTFont object representing the variable font.
    designspace: A DesignSpaceDocument object.
    featureTags: Optional feature tag(s) to use for the FeatureVariations records.
        If unset, the key 'com.github.fonttools.varLib.featureVarsFeatureTag' is
        looked up in the DS <lib> and used; otherwise the default is 'rclt' if
        the <rules processing="last"> attribute is set, else 'rvrn'.
        See <https://fonttools.readthedocs.io/en/latest/designspaceLib/xml.html#rules-element>
    log_enabled: If True, log info about DS axes and sources. Default is False, as
        the same info may have already been logged as part of varLib.build.
Definition at line 1343 of file __init__.py.
build()
fontTools.varLib.build (designspace, master_finder = lambda s: s, exclude = [], optimize = True, colr_layer_reuse = True, drop_implied_oncurves = False)
Build variation font from a designspace file.
If master_finder is set, it should be a callable that takes master
filename as found in designspace file and map it to master font
binary as to be opened (eg. .ttf or .otf).
Definition at line 1161 of file __init__.py.
References _add_avar(), _add_fvar(), drop_implied_oncurve_points(), and load_masters().
Referenced by build_many().
build_many()
fontTools.varLib.build_many (DesignSpaceDocument designspace, master_finder = lambda s: s, exclude = [], optimize = True, skip_vf = lambda vf_name: False, colr_layer_reuse = True, drop_implied_oncurves = False)
Build variable fonts from a designspace file, version 5 which can define
several VFs, or version 4 which has implicitly one VF covering the whole doc.
If master_finder is set, it should be a callable that takes master
filename as found in designspace file and map it to master font
binary as to be opened (eg. .ttf or .otf).
skip_vf can be used to skip building some of the variable fonts defined in
the input designspace. It's a predicate that takes as argument the name
of the variable font and returns `bool`.
Always returns a Dict[str, TTFont] keyed by VariableFontDescriptor.name
Definition at line 1102 of file __init__.py.
References build().
Referenced by main().
drop_implied_oncurve_points()
int fontTools.varLib.drop_implied_oncurve_points (*TTFont masters)
Drop impliable on-curve points from all the simple glyphs in masters.
In TrueType glyf outlines, on-curve points can be implied when they are located
exactly at the midpoint of the line connecting two consecutive off-curve points.
The input masters' glyf tables are assumed to contain same-named glyphs that are
interpolatable. Oncurve points are only dropped if they can be implied for all
the masters. The fonts are modified in-place.
Args:
    masters: The TTFont(s) to modify
Returns:
    The total number of points that were dropped if any.
Reference:
https://developer.apple.com/fonts/TrueType-Reference-Manual/RM01/Chap1.html
Definition at line 1062 of file __init__.py.
Referenced by build().
load_designspace()
fontTools.varLib.load_designspace (designspace, log_enabled = True, * , require_sources = True)
Definition at line 893 of file __init__.py.
load_masters()
fontTools.varLib.load_masters (designspace, master_finder = lambda s: s)
Ensure that all SourceDescriptor.font attributes have an appropriate TTFont
object loaded, or else open TTFont objects from the SourceDescriptor.path
attributes.
The paths can point to either an OpenType font, a TTX file, or a UFO. In the
latter case, use the provided master_finder callable to map from UFO paths to
the respective master font binaries (e.g. .ttf, .otf or .ttx).
Return list of master TTFont objects in the same order they are listed in the
DesignSpaceDocument.
Definition at line 1292 of file __init__.py.
Referenced by build(), and fontTools.varLib.interpolate_layout.interpolate_layout().
main()
fontTools.varLib.main (args = None)
Build variable fonts from a designspace file and masters
Definition at line 1367 of file __init__.py.
References build_many().
set_default_weight_width_slant()
fontTools.varLib.set_default_weight_width_slant (font, location)
Definition at line 1037 of file __init__.py.
Variable Documentation
_DesignSpaceData
fontTools.varLib._DesignSpaceData protected
Initial value:
=  namedtuple(
    "_DesignSpaceData",
    [
        "axes",
        "axisMappings",
        "internal_axis_supports",
        "base_idx",
        "normalized_master_locs",
        "masters",
        "instances",
        "rules",
        "rulesProcessingLast",
        "lib",
    ],
)
Definition at line 847 of file __init__.py.
_MasterData
fontTools.varLib._MasterData = namedtuple("_MasterData", ["glyf", "hMetrics", "vMetrics"]) protected
Definition at line 318 of file __init__.py.
_MetricsFields
fontTools.varLib._MetricsFields protected
Initial value:
=  namedtuple(
    "_MetricsFields",
    [
        "tableTag",
        "metricsTag",
        "sb1",
        "sb2",
        "advMapping",
        "vOrigMapping",
        "phantomIndex",
    ],
)
Definition at line 492 of file __init__.py.
FEAVAR_FEATURETAG_LIB_KEY
str fontTools.varLib.FEAVAR_FEATURETAG_LIB_KEY = "com.github.fonttools.varLib.featureVarsFeatureTag"
Definition at line 63 of file __init__.py.
HVAR_FIELDS
fontTools.varLib.HVAR_FIELDS
Initial value:
=  _MetricsFields(
    tableTag="HVAR",
    metricsTag="hmtx",
    sb1="LsbMap",
    sb2="RsbMap",
    advMapping="AdvWidthMap",
    vOrigMapping=None,
    phantomIndex=0,
)
Definition at line 505 of file __init__.py.
log
fontTools.varLib.log = logging.getLogger("fontTools.varLib")
Definition at line 57 of file __init__.py.
VVAR_FIELDS
fontTools.varLib.VVAR_FIELDS
Initial value:
=  _MetricsFields(
    tableTag="VVAR",
    metricsTag="vmtx",
    sb1="TsbMap",
    sb2="BsbMap",
    advMapping="AdvHeightMap",
    vOrigMapping="VOrgMap",
    phantomIndex=1,
)
Definition at line 515 of file __init__.py.
WDTH_VALUE_TO_OS2_WIDTH_CLASS
dict fontTools.varLib.WDTH_VALUE_TO_OS2_WIDTH_CLASS
Initial value:
=  {
    50: 1,
    62.5: 2,
    75: 3,
    87.5: 4,
    100: 5,
    112.5: 6,
    125: 7,
    150: 8,
    200: 9,
}
Definition at line 1024 of file __init__.py.