Code Cloning Analysis: pandas.errors.AbstractMethodError Class Reference
pandas.errors.AbstractMethodError Class Reference
Public Member Functions
None __init__ (self, class_instance, str methodtype="method")
str __str__ (self)
Public Attributes
str methodtype = methodtype
class_instance = class_instance
Detailed Description
Raise this error instead of NotImplementedError for abstract methods.
Examples
--------
>>> class Foo:
...     @classmethod
...     def classmethod(cls):
...         raise pd.errors.AbstractMethodError(cls, methodtype="classmethod")
...     def method(self):
...         raise pd.errors.AbstractMethodError(self)
>>> test = Foo.classmethod()
Traceback (most recent call last):
AbstractMethodError: This classmethod must be defined in the concrete class Foo
>>> test2 = Foo().method()
Traceback (most recent call last):
AbstractMethodError: This classmethod must be defined in the concrete class Foo
Definition at line 273 of file __init__.py.
Constructor & Destructor Documentation
__init__()
None pandas.errors.AbstractMethodError.__init__ (self, class_instance, str methodtype = "method")
Definition at line 294 of file __init__.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__str__()
str pandas.errors.AbstractMethodError.__str__ (self)
Definition at line 303 of file __init__.py.
Member Data Documentation
class_instance
pandas.errors.AbstractMethodError.class_instance = class_instance
Definition at line 301 of file __init__.py.
methodtype
str pandas.errors.AbstractMethodError.methodtype = methodtype
Definition at line 300 of file __init__.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/errors/__init__.py