Code Cloning Analysis: pandas.core.arrays.sparse.array Namespace Reference
pandas.core.arrays.sparse.array Namespace Reference
Classes
class ellipsis
class SparseArray
Functions
np.ndarray _get_fill (SparseArray arr)
SparseArray _sparse_array_op (SparseArray left, SparseArray right, Callable op, str name)
SparseArray _wrap_result (str name, data, sparse_index, fill_value, Dtype|None dtype=None)
_make_sparse (np.ndarray arr, SparseIndexKind kind="block", fill_value=None, np.dtype|None dtype=None)
BlockIndex make_sparse_index (int length, indices, Literal["block"] kind)
IntIndex make_sparse_index (int length, indices, Literal["integer"] kind)
SparseIndex make_sparse_index (int length, indices, SparseIndexKind kind)
Variables
Ellipsis
SparseIndexKind = Literal["integer", "block"]
ellipsis = type(Ellipsis)
dict _sparray_doc_kwargs = {"klass": "SparseArray"}
Detailed Description
SparseArray data structure
Function Documentation
_get_fill()
np.ndarray pandas.core.arrays.sparse.array._get_fill (SparseArray arr) protected
Create a 0-dim ndarray containing the fill value
Parameters
----------
arr : SparseArray
Returns
-------
fill_value : ndarray
    0-dim ndarray with just the fill value.
Notes
-----
coerce fill_value to arr dtype if possible
int64 SparseArray can have NaN as fill_value if there is no missing
Definition at line 132 of file array.py.
Referenced by _sparse_array_op(), and pandas.core.arrays.sparse.array.SparseArray.argmin().
_make_sparse()
pandas.core.arrays.sparse.array._make_sparse (np.ndarray arr, SparseIndexKind kind = "block", fill_value = None, np.dtype | None dtype = None) protected
Convert ndarray to sparse format
Parameters
----------
arr : ndarray
kind : {'block', 'integer'}
fill_value : NaN or another value
dtype : np.dtype, optional
copy : bool, default False
Returns
-------
(sparse_values, index, fill_value) : (ndarray, SparseIndex, Scalar)
Definition at line 1864 of file array.py.
_sparse_array_op()
SparseArray pandas.core.arrays.sparse.array._sparse_array_op (SparseArray left, SparseArray right, Callable op, str name) protected
Perform a binary operation between two arrays.
Parameters
----------
left : Union[SparseArray, ndarray]
right : Union[SparseArray, ndarray]
op : Callable
    The binary operation to perform
name str
    Name of the callable.
Returns
-------
SparseArray
Definition at line 156 of file array.py.
References _get_fill(), and _wrap_result().
Referenced by pandas.core.arrays.sparse.array.SparseArray.argmin().
_wrap_result()
SparseArray pandas.core.arrays.sparse.array._wrap_result (str name, data, sparse_index, fill_value, Dtype | None dtype = None) protected
wrap op result to have correct dtype
Definition at line 264 of file array.py.
Referenced by _sparse_array_op(), and pandas.core.arrays.sparse.array.SparseArray.argmin().
make_sparse_index() [1/3]
BlockIndex pandas.core.arrays.sparse.array.make_sparse_index (int length, indices, Literal["block"] kind)
Definition at line 1927 of file array.py.
make_sparse_index() [2/3]
IntIndex pandas.core.arrays.sparse.array.make_sparse_index (int length, indices, Literal["integer"] kind)
Definition at line 1932 of file array.py.
make_sparse_index() [3/3]
SparseIndex pandas.core.arrays.sparse.array.make_sparse_index (int length, indices, SparseIndexKind kind)
Definition at line 1936 of file array.py.
Variable Documentation
_sparray_doc_kwargs
dict pandas.core.arrays.sparse.array._sparray_doc_kwargs = {"klass": "SparseArray"} protected
Definition at line 129 of file array.py.
Ellipsis
pandas.core.arrays.sparse.array.Ellipsis
Definition at line 94 of file array.py.
ellipsis
pandas.core.arrays.sparse.array.ellipsis = type(Ellipsis)
Definition at line 123 of file array.py.
SparseIndexKind
pandas.core.arrays.sparse.array.SparseIndexKind = Literal["integer", "block"]
Definition at line 103 of file array.py.