Code Cloning Analysis: scipy.special._precompute.gammainc_asy Namespace Reference
scipy.special._precompute.gammainc_asy Namespace Reference
Functions
compute_a (n)
compute_g (n)
eta (lam)
compute_alpha (n)
compute_d (K, N)
main ()
Variables
str header
str footer
Detailed Description
Precompute coefficients of Temme's asymptotic expansion for gammainc.
This takes about 8 hours to run on a 2.3 GHz Macbook Pro with 4GB ram.
Sources:
[1] NIST, "Digital Library of Mathematical Functions",
    https://dlmf.nist.gov/
Function Documentation
compute_a()
scipy.special._precompute.gammainc_asy.compute_a (n)
a_k from DLMF 5.11.6
Definition at line 20 of file gammainc_asy.py.
Referenced by compute_g().
compute_alpha()
scipy.special._precompute.gammainc_asy.compute_alpha (n)
alpha_n from DLMF 8.12.13
Definition at line 49 of file gammainc_asy.py.
Referenced by compute_d().
compute_d()
scipy.special._precompute.gammainc_asy.compute_d (K, N)
d_{k, n} from DLMF 8.12.12
Definition at line 55 of file gammainc_asy.py.
References compute_alpha(), compute_d(), and compute_g().
Referenced by compute_d().
compute_g()
scipy.special._precompute.gammainc_asy.compute_g (n)
g_k from DLMF 5.11.3/5.11.5
Definition at line 32 of file gammainc_asy.py.
References compute_a().
Referenced by compute_d().
eta()
scipy.special._precompute.gammainc_asy.eta (lam)
Function from DLMF 8.12.1 shifted to be centered at 0.
Definition at line 39 of file gammainc_asy.py.
main()
scipy.special._precompute.gammainc_asy.main ()
Definition at line 94 of file gammainc_asy.py.
Variable Documentation
footer
str scipy.special._precompute.gammainc_asy.footer
Initial value:
=  \
r"""
#endif
"""
Definition at line 88 of file gammainc_asy.py.
header
str scipy.special._precompute.gammainc_asy.header
Initial value:
=  \
r"""/* This file was automatically generated by _precomp/gammainc.py.
 * Do not edit it manually!
 */
#ifndef IGAM_H
#define IGAM_H
#define K {}
#define N {}
static const double d[K][N] =
{{"""
Definition at line 74 of file gammainc_asy.py.