Code Cloning Analysis: sklearn.neighbors.tests.test_neighbors Namespace Reference
sklearn.neighbors.tests.test_neighbors Namespace Reference
Functions
_parse_metric (str metric, dtype=None)
_generate_test_params_for (str metric, int n_features)
_weight_func (dist)
test_unsupervised_kneighbors (global_dtype, n_samples, n_features, n_query_pts, n_neighbors, query_is_train, metric)
test_neigh_predictions_algorithm_agnosticity (global_dtype, n_samples, n_features, n_query_pts, metric, n_neighbors, radius, NeighborsMixinSubclass)
test_unsupervised_inputs (global_dtype, KNeighborsMixinSubclass)
test_not_fitted_error_gets_raised ()
check_precomputed (make_train_test, estimators)
test_precomputed_dense ()
test_precomputed_sparse_knn (fmt)
test_precomputed_sparse_radius (fmt)
test_is_sorted_by_data (csr_container)
test_sort_graph_by_row_values (function, csr_container)
test_sort_graph_by_row_values_copy (csr_container)
test_sort_graph_by_row_values_warning (csr_container)
test_sort_graph_by_row_values_bad_sparse_format (sparse_container)
test_precomputed_sparse_invalid (csr_container)
test_precomputed_cross_validation ()
test_unsupervised_radius_neighbors (global_dtype, n_samples=20, n_features=5, n_query_pts=2, radius=0.5, random_state=0)
test_kneighbors_classifier (global_dtype, algorithm, weights, n_samples=40, n_features=5, n_test_pts=10, n_neighbors=5, random_state=0)
test_kneighbors_classifier_float_labels (global_dtype, n_samples=40, n_features=5, n_test_pts=10, n_neighbors=5, random_state=0)
test_kneighbors_classifier_predict_proba (global_dtype)
test_radius_neighbors_classifier (global_dtype, algorithm, weights, n_samples=40, n_features=5, n_test_pts=10, radius=0.5, random_state=0)
test_radius_neighbors_classifier_when_no_neighbors (global_dtype, algorithm, weights, outlier_label)
test_radius_neighbors_classifier_outlier_labeling (global_dtype, algorithm, weights)
test_radius_neighbors_classifier_zero_distance ()
test_neighbors_regressors_zero_distance ()
test_radius_neighbors_boundary_handling ()
test_radius_neighbors_returns_array_of_objects (csr_container)
test_query_equidistant_kth_nn (algorithm)
test_radius_neighbors_sort_results (algorithm, metric)
test_RadiusNeighborsClassifier_multioutput ()
test_kneighbors_classifier_sparse (n_samples=40, n_features=5, n_test_pts=10, n_neighbors=5, random_state=0)
test_KNeighborsClassifier_multioutput ()
test_kneighbors_regressor (n_samples=40, n_features=5, n_test_pts=10, n_neighbors=3, random_state=0)
test_KNeighborsRegressor_multioutput_uniform_weight ()
test_kneighbors_regressor_multioutput (n_samples=40, n_features=5, n_test_pts=10, n_neighbors=3, random_state=0)
test_radius_neighbors_regressor (n_samples=40, n_features=3, n_test_pts=10, radius=0.5, random_state=0)
test_RadiusNeighborsRegressor_multioutput_with_uniform_weight ()
test_RadiusNeighborsRegressor_multioutput (n_samples=40, n_features=5, n_test_pts=10, random_state=0)
test_kneighbors_regressor_sparse (n_samples=40, n_features=5, n_test_pts=10, n_neighbors=5, random_state=0)
test_neighbors_iris ()
test_neighbors_digits ()
test_kneighbors_graph ()
test_kneighbors_graph_sparse (n_neighbors, mode, csr_container, seed=36)
test_radius_neighbors_graph ()
test_radius_neighbors_graph_sparse (n_neighbors, mode, csr_container, seed=36)
test_neighbors_validate_parameters (Estimator, csr_container)
test_neighbors_minkowski_semimetric_algo_warn (Estimator, n_features, algorithm)
test_neighbors_minkowski_semimetric_algo_error (Estimator, n_features, algorithm)
test_nearest_neighbors_validate_params ()
test_neighbors_metrics (global_dtype, global_random_seed, metric, n_samples=20, n_features=3, n_query_pts=2, n_neighbors=5)
test_kneighbors_brute_backend (metric, global_dtype, global_random_seed, n_samples=2000, n_features=30, n_query_pts=5, n_neighbors=5)
test_callable_metric ()
test_valid_brute_metric_for_auto_algorithm (global_dtype, metric, csr_container, n_samples=20, n_features=12)
test_metric_params_interface ()
test_predict_sparse_ball_kd_tree (csr_container)
test_non_euclidean_kneighbors ()
check_object_arrays (nparray, list_check)
test_k_and_radius_neighbors_train_is_not_query ()
test_k_and_radius_neighbors_X_None (algorithm)
test_k_and_radius_neighbors_duplicates (algorithm)
test_include_self_neighbors_graph ()
test_same_knn_parallel (algorithm)
test_same_radius_neighbors_parallel (algorithm)
test_knn_forcing_backend (backend, algorithm)
test_dtype_convert ()
test_sparse_metric_callable (csr_container)
test_pairwise_boolean_distance ()
test_radius_neighbors_predict_proba ()
test_pipeline_with_nearest_neighbors_transformer ()
test_auto_algorithm (X, metric, metric_params, expected_algo)
test_radius_neighbors_brute_backend (metric, global_random_seed, global_dtype, n_samples=2000, n_features=30, n_query_pts=5, radius=1.0)
test_valid_metrics_has_no_duplicate ()
test_regressor_predict_on_arraylikes ()
test_nan_euclidean_support (Estimator, params)
test_predict_dataframe ()
test_nearest_neighbours_works_with_p_less_than_1 ()
test_KNeighborsClassifier_raise_on_all_zero_weights ()
test_neighbor_classifiers_loocv (nn_model, algorithm)
test_neighbor_regressors_loocv (nn_model, algorithm)
Variables
rng = np.random.RandomState(0)
iris = datasets.load_iris()
perm = rng.permutation(iris.target.size)
data
target
digits = datasets.load_digits()
SPARSE_TYPES
SPARSE_OR_DENSE = SPARSE_TYPES + (np.asarray,)
tuple ALGORITHMS = ("ball_tree", "brute", "kd_tree", "auto")
COMMON_VALID_METRICS
tuple P = (1, 2, 3, 4, np.inf)
kneighbors_graph
radius_neighbors_graph
list DISTANCE_METRIC_OBJS = ["DM_euclidean"]
list WEIGHTS = ["uniform", "distance", _weight_func]
Function Documentation
_generate_test_params_for()
sklearn.neighbors.tests.test_neighbors._generate_test_params_for (str metric, int n_features) protected
Return list of DistanceMetric kwargs for tests.
Definition at line 114 of file test_neighbors.py.
Referenced by test_nearest_neighbors_validate_params().
_parse_metric()
sklearn.neighbors.tests.test_neighbors._parse_metric (str metric, dtype = None) protected
Helper function for properly building a type-specialized DistanceMetric instances.
Constructs a type-specialized DistanceMetric instance from a string
beginning with "DM_" while allowing a pass-through for other metric-specifying
strings. This is necessary since we wish to parameterize dtype independent of
metric, yet DistanceMetric requires it for construction.
Definition at line 99 of file test_neighbors.py.
Referenced by _weight_func(), test_nearest_neighbors_validate_params(), and test_radius_neighbors_boundary_handling().
_weight_func()
sklearn.neighbors.tests.test_neighbors._weight_func (dist) protected
Weight function to replace lambda d: d ** -2.
The lambda function is not valid because:
if d==0 then 0^-2 is not valid.
Definition at line 143 of file test_neighbors.py.
References _parse_metric().
check_object_arrays()
sklearn.neighbors.tests.test_neighbors.check_object_arrays (nparray, list_check)
Definition at line 1915 of file test_neighbors.py.
check_precomputed()
sklearn.neighbors.tests.test_neighbors.check_precomputed (make_train_test, estimators)
Tests unsupervised NearestNeighbors with a distance matrix.
Definition at line 368 of file test_neighbors.py.
References check_precomputed().
Referenced by check_precomputed().
test_auto_algorithm()
sklearn.neighbors.tests.test_neighbors.test_auto_algorithm (X, metric, metric_params, expected_algo)
Definition at line 2245 of file test_neighbors.py.
test_callable_metric()
sklearn.neighbors.tests.test_neighbors.test_callable_metric ()
Definition at line 1789 of file test_neighbors.py.
test_dtype_convert()
sklearn.neighbors.tests.test_neighbors.test_dtype_convert ()
Definition at line 2119 of file test_neighbors.py.
test_include_self_neighbors_graph()
sklearn.neighbors.tests.test_neighbors.test_include_self_neighbors_graph ()
Definition at line 2032 of file test_neighbors.py.
test_is_sorted_by_data()
sklearn.neighbors.tests.test_neighbors.test_is_sorted_by_data (csr_container)
Definition at line 476 of file test_neighbors.py.
test_k_and_radius_neighbors_duplicates()
sklearn.neighbors.tests.test_neighbors.test_k_and_radius_neighbors_duplicates (algorithm)
Definition at line 1983 of file test_neighbors.py.
test_k_and_radius_neighbors_train_is_not_query()
sklearn.neighbors.tests.test_neighbors.test_k_and_radius_neighbors_train_is_not_query ()
Definition at line 1920 of file test_neighbors.py.
test_k_and_radius_neighbors_X_None()
sklearn.neighbors.tests.test_neighbors.test_k_and_radius_neighbors_X_None (algorithm)
Definition at line 1951 of file test_neighbors.py.
test_kneighbors_brute_backend()
sklearn.neighbors.tests.test_neighbors.test_kneighbors_brute_backend (metric, global_dtype, global_random_seed, n_samples = 2000, n_features = 30, n_query_pts = 5, n_neighbors = 5)
Definition at line 1734 of file test_neighbors.py.
test_kneighbors_classifier()
sklearn.neighbors.tests.test_neighbors.test_kneighbors_classifier (global_dtype, algorithm, weights, n_samples = 40, n_features = 5, n_test_pts = 10, n_neighbors = 5, random_state = 0)
Definition at line 668 of file test_neighbors.py.
test_kneighbors_classifier_float_labels()
sklearn.neighbors.tests.test_neighbors.test_kneighbors_classifier_float_labels (global_dtype, n_samples = 40, n_features = 5, n_test_pts = 10, n_neighbors = 5, random_state = 0)
Definition at line 697 of file test_neighbors.py.
test_kneighbors_classifier_predict_proba()
sklearn.neighbors.tests.test_neighbors.test_kneighbors_classifier_predict_proba (global_dtype)
Definition at line 717 of file test_neighbors.py.
test_kneighbors_classifier_sparse()
sklearn.neighbors.tests.test_neighbors.test_kneighbors_classifier_sparse (n_samples = 40, n_features = 5, n_test_pts = 10, n_neighbors = 5, random_state = 0)
Definition at line 1143 of file test_neighbors.py.
test_kneighbors_graph()
sklearn.neighbors.tests.test_neighbors.test_kneighbors_graph ()
Definition at line 1442 of file test_neighbors.py.
test_kneighbors_graph_sparse()
sklearn.neighbors.tests.test_neighbors.test_kneighbors_graph_sparse (n_neighbors, mode, csr_container, seed = 36)
Definition at line 1477 of file test_neighbors.py.
test_kneighbors_regressor()
sklearn.neighbors.tests.test_neighbors.test_kneighbors_regressor (n_samples = 40, n_features = 5, n_test_pts = 10, n_neighbors = 3, random_state = 0)
Definition at line 1207 of file test_neighbors.py.
test_kneighbors_regressor_multioutput()
sklearn.neighbors.tests.test_neighbors.test_kneighbors_regressor_multioutput (n_samples = 40, n_features = 5, n_test_pts = 10, n_neighbors = 3, random_state = 0)
Definition at line 1256 of file test_neighbors.py.
test_kneighbors_regressor_sparse()
sklearn.neighbors.tests.test_neighbors.test_kneighbors_regressor_sparse (n_samples = 40, n_features = 5, n_test_pts = 10, n_neighbors = 5, random_state = 0)
Definition at line 1371 of file test_neighbors.py.
test_KNeighborsClassifier_multioutput()
sklearn.neighbors.tests.test_neighbors.test_KNeighborsClassifier_multioutput ()
Definition at line 1163 of file test_neighbors.py.
test_KNeighborsClassifier_raise_on_all_zero_weights()
sklearn.neighbors.tests.test_neighbors.test_KNeighborsClassifier_raise_on_all_zero_weights ()
Check that `predict` and `predict_proba` raises on sample of all zeros weights.
Related to Issue #25854.
Definition at line 2403 of file test_neighbors.py.
test_KNeighborsRegressor_multioutput_uniform_weight()
sklearn.neighbors.tests.test_neighbors.test_KNeighborsRegressor_multioutput_uniform_weight ()
Definition at line 1231 of file test_neighbors.py.
test_knn_forcing_backend()
sklearn.neighbors.tests.test_neighbors.test_knn_forcing_backend (backend, algorithm)
Definition at line 2101 of file test_neighbors.py.
test_metric_params_interface()
sklearn.neighbors.tests.test_neighbors.test_metric_params_interface ()
Definition at line 1858 of file test_neighbors.py.
test_nan_euclidean_support()
sklearn.neighbors.tests.test_neighbors.test_nan_euclidean_support (Estimator, params)
Check that the different neighbor estimators are lenient towards `nan`
values if using `metric="nan_euclidean"`.
Definition at line 2350 of file test_neighbors.py.
test_nearest_neighbors_validate_params()
sklearn.neighbors.tests.test_neighbors.test_nearest_neighbors_validate_params ()
Validate parameter of NearestNeighbors.
Definition at line 1624 of file test_neighbors.py.
References _generate_test_params_for(), and _parse_metric().
test_nearest_neighbours_works_with_p_less_than_1()
sklearn.neighbors.tests.test_neighbors.test_nearest_neighbours_works_with_p_less_than_1 ()
Check that NearestNeighbors works with :math:`p \\in (0,1)` when `algorithm`
is `"auto"` or `"brute"` regardless of the dtype of X.
Non-regression test for issue #26548
Definition at line 2384 of file test_neighbors.py.
test_neigh_predictions_algorithm_agnosticity()
sklearn.neighbors.tests.test_neighbors.test_neigh_predictions_algorithm_agnosticity (global_dtype, n_samples, n_features, n_query_pts, metric, n_neighbors, radius, NeighborsMixinSubclass)
Definition at line 262 of file test_neighbors.py.
test_neighbor_classifiers_loocv()
sklearn.neighbors.tests.test_neighbors.test_neighbor_classifiers_loocv (nn_model, algorithm)
Check that `predict` and related functions work fine with X=None
Calling predict with X=None computes a prediction for each training point
from the labels of its neighbors (without the label of the data point being
predicted upon). This is therefore mathematically equivalent to
leave-one-out cross-validation without having do any retraining (rebuilding
a KD-tree or Ball-tree index) or any data reshuffling.
Definition at line 2438 of file test_neighbors.py.
test_neighbor_regressors_loocv()
sklearn.neighbors.tests.test_neighbors.test_neighbor_regressors_loocv (nn_model, algorithm)
Check that `predict` and related functions work fine with X=None
Definition at line 2479 of file test_neighbors.py.
test_neighbors_digits()
sklearn.neighbors.tests.test_neighbors.test_neighbors_digits ()
Definition at line 1421 of file test_neighbors.py.
test_neighbors_iris()
sklearn.neighbors.tests.test_neighbors.test_neighbors_iris ()
Definition at line 1402 of file test_neighbors.py.
test_neighbors_metrics()
sklearn.neighbors.tests.test_neighbors.test_neighbors_metrics (global_dtype, global_random_seed, metric, n_samples = 20, n_features = 3, n_query_pts = 2, n_neighbors = 5)
Definition at line 1649 of file test_neighbors.py.
test_neighbors_minkowski_semimetric_algo_error()
sklearn.neighbors.tests.test_neighbors.test_neighbors_minkowski_semimetric_algo_error (Estimator, n_features, algorithm)
Check that we raise a proper error if `algorithm!='brute'` and `p<1`.
Definition at line 1608 of file test_neighbors.py.
test_neighbors_minkowski_semimetric_algo_warn()
sklearn.neighbors.tests.test_neighbors.test_neighbors_minkowski_semimetric_algo_warn (Estimator, n_features, algorithm)
Validation of all classes extending NeighborsBase with
Minkowski semi-metrics (i.e. when 0 < p < 1). That proper
Warning is raised for `algorithm="auto"` and "brute".
Definition at line 1577 of file test_neighbors.py.
test_neighbors_regressors_zero_distance()
sklearn.neighbors.tests.test_neighbors.test_neighbors_regressors_zero_distance ()
Definition at line 966 of file test_neighbors.py.
test_neighbors_validate_parameters()
sklearn.neighbors.tests.test_neighbors.test_neighbors_validate_parameters (Estimator, csr_container)
Additional parameter validation for *Neighbors* estimators not covered by common
validation.
Definition at line 1529 of file test_neighbors.py.
test_non_euclidean_kneighbors()
sklearn.neighbors.tests.test_neighbors.test_non_euclidean_kneighbors ()
Definition at line 1879 of file test_neighbors.py.
test_not_fitted_error_gets_raised()
sklearn.neighbors.tests.test_neighbors.test_not_fitted_error_gets_raised ()
Definition at line 358 of file test_neighbors.py.
test_pairwise_boolean_distance()
sklearn.neighbors.tests.test_neighbors.test_pairwise_boolean_distance ()
Definition at line 2154 of file test_neighbors.py.
test_pipeline_with_nearest_neighbors_transformer()
sklearn.neighbors.tests.test_neighbors.test_pipeline_with_nearest_neighbors_transformer ()
Definition at line 2188 of file test_neighbors.py.
test_precomputed_cross_validation()
sklearn.neighbors.tests.test_neighbors.test_precomputed_cross_validation ()
Definition at line 607 of file test_neighbors.py.
test_precomputed_dense()
sklearn.neighbors.tests.test_neighbors.test_precomputed_dense ()
Definition at line 423 of file test_neighbors.py.
test_precomputed_sparse_invalid()
sklearn.neighbors.tests.test_neighbors.test_precomputed_sparse_invalid (csr_container)
Definition at line 583 of file test_neighbors.py.
test_precomputed_sparse_knn()
sklearn.neighbors.tests.test_neighbors.test_precomputed_sparse_knn (fmt)
Definition at line 440 of file test_neighbors.py.
test_precomputed_sparse_radius()
sklearn.neighbors.tests.test_neighbors.test_precomputed_sparse_radius (fmt)
Definition at line 458 of file test_neighbors.py.
test_predict_dataframe()
sklearn.neighbors.tests.test_neighbors.test_predict_dataframe ()
Check that KNN predict works with dataframes
non-regression test for issue #26768
Definition at line 2370 of file test_neighbors.py.
test_predict_sparse_ball_kd_tree()
sklearn.neighbors.tests.test_neighbors.test_predict_sparse_ball_kd_tree (csr_container)
Definition at line 1867 of file test_neighbors.py.
test_query_equidistant_kth_nn()
sklearn.neighbors.tests.test_neighbors.test_query_equidistant_kth_nn (algorithm)
Definition at line 1041 of file test_neighbors.py.
test_radius_neighbors_boundary_handling()
sklearn.neighbors.tests.test_neighbors.test_radius_neighbors_boundary_handling ()
Test whether points lying on boundary are handled consistently
Also ensures that even with only one query point, an object array
is returned rather than a 2d array.
Definition at line 999 of file test_neighbors.py.
References _parse_metric().
test_radius_neighbors_brute_backend()
sklearn.neighbors.tests.test_neighbors.test_radius_neighbors_brute_backend (metric, global_random_seed, global_dtype, n_samples = 2000, n_features = 30, n_query_pts = 5, radius = 1.0)
Definition at line 2260 of file test_neighbors.py.
test_radius_neighbors_classifier()
sklearn.neighbors.tests.test_neighbors.test_radius_neighbors_classifier (global_dtype, algorithm, weights, n_samples = 40, n_features = 5, n_test_pts = 10, radius = 0.5, random_state = 0)
Definition at line 754 of file test_neighbors.py.
test_radius_neighbors_classifier_outlier_labeling()
sklearn.neighbors.tests.test_neighbors.test_radius_neighbors_classifier_outlier_labeling (global_dtype, algorithm, weights)
Definition at line 817 of file test_neighbors.py.
test_radius_neighbors_classifier_when_no_neighbors()
sklearn.neighbors.tests.test_neighbors.test_radius_neighbors_classifier_when_no_neighbors (global_dtype, algorithm, weights, outlier_label)
Definition at line 785 of file test_neighbors.py.
test_radius_neighbors_classifier_zero_distance()
sklearn.neighbors.tests.test_neighbors.test_radius_neighbors_classifier_zero_distance ()
Definition at line 942 of file test_neighbors.py.
test_radius_neighbors_graph()
sklearn.neighbors.tests.test_neighbors.test_radius_neighbors_graph ()
Definition at line 1490 of file test_neighbors.py.
test_radius_neighbors_graph_sparse()
sklearn.neighbors.tests.test_neighbors.test_radius_neighbors_graph_sparse (n_neighbors, mode, csr_container, seed = 36)
Definition at line 1506 of file test_neighbors.py.
test_radius_neighbors_predict_proba()
sklearn.neighbors.tests.test_neighbors.test_radius_neighbors_predict_proba ()
Definition at line 2167 of file test_neighbors.py.
test_radius_neighbors_regressor()
sklearn.neighbors.tests.test_neighbors.test_radius_neighbors_regressor (n_samples = 40, n_features = 3, n_test_pts = 10, radius = 0.5, random_state = 0)
Definition at line 1281 of file test_neighbors.py.
test_radius_neighbors_returns_array_of_objects()
sklearn.neighbors.tests.test_neighbors.test_radius_neighbors_returns_array_of_objects (csr_container)
Definition at line 1018 of file test_neighbors.py.
test_radius_neighbors_sort_results()
sklearn.neighbors.tests.test_neighbors.test_radius_neighbors_sort_results (algorithm, metric)
Definition at line 1068 of file test_neighbors.py.
test_RadiusNeighborsClassifier_multioutput()
sklearn.neighbors.tests.test_neighbors.test_RadiusNeighborsClassifier_multioutput ()
Definition at line 1105 of file test_neighbors.py.
test_RadiusNeighborsRegressor_multioutput()
sklearn.neighbors.tests.test_neighbors.test_RadiusNeighborsRegressor_multioutput (n_samples = 40, n_features = 5, n_test_pts = 10, random_state = 0)
Definition at line 1347 of file test_neighbors.py.
test_RadiusNeighborsRegressor_multioutput_with_uniform_weight()
sklearn.neighbors.tests.test_neighbors.test_RadiusNeighborsRegressor_multioutput_with_uniform_weight ()
Definition at line 1320 of file test_neighbors.py.
test_regressor_predict_on_arraylikes()
sklearn.neighbors.tests.test_neighbors.test_regressor_predict_on_arraylikes ()
Ensures that `predict` works for array-likes when `weights` is a callable.
Non-regression test for #22687.
Definition at line 2322 of file test_neighbors.py.
test_same_knn_parallel()
sklearn.neighbors.tests.test_neighbors.test_same_knn_parallel (algorithm)
Definition at line 2049 of file test_neighbors.py.
test_same_radius_neighbors_parallel()
sklearn.neighbors.tests.test_neighbors.test_same_radius_neighbors_parallel (algorithm)
Definition at line 2074 of file test_neighbors.py.
test_sort_graph_by_row_values()
sklearn.neighbors.tests.test_neighbors.test_sort_graph_by_row_values (function, csr_container)
Definition at line 503 of file test_neighbors.py.
test_sort_graph_by_row_values_bad_sparse_format()
sklearn.neighbors.tests.test_neighbors.test_sort_graph_by_row_values_bad_sparse_format (sparse_container)
Definition at line 572 of file test_neighbors.py.
test_sort_graph_by_row_values_copy()
sklearn.neighbors.tests.test_neighbors.test_sort_graph_by_row_values_copy (csr_container)
Definition at line 522 of file test_neighbors.py.
test_sort_graph_by_row_values_warning()
sklearn.neighbors.tests.test_neighbors.test_sort_graph_by_row_values_warning (csr_container)
Definition at line 550 of file test_neighbors.py.
test_sparse_metric_callable()
sklearn.neighbors.tests.test_neighbors.test_sparse_metric_callable (csr_container)
Definition at line 2130 of file test_neighbors.py.
test_unsupervised_inputs()
sklearn.neighbors.tests.test_neighbors.test_unsupervised_inputs (global_dtype, KNeighborsMixinSubclass)
Definition at line 337 of file test_neighbors.py.
test_unsupervised_kneighbors()
sklearn.neighbors.tests.test_neighbors.test_unsupervised_kneighbors (global_dtype, n_samples, n_features, n_query_pts, n_neighbors, query_is_train, metric)
Definition at line 167 of file test_neighbors.py.
test_unsupervised_radius_neighbors()
sklearn.neighbors.tests.test_neighbors.test_unsupervised_radius_neighbors (global_dtype, n_samples = 20, n_features = 5, n_query_pts = 2, radius = 0.5, random_state = 0)
Definition at line 624 of file test_neighbors.py.
test_valid_brute_metric_for_auto_algorithm()
sklearn.neighbors.tests.test_neighbors.test_valid_brute_metric_for_auto_algorithm (global_dtype, metric, csr_container, n_samples = 20, n_features = 12)
Definition at line 1814 of file test_neighbors.py.
test_valid_metrics_has_no_duplicate()
sklearn.neighbors.tests.test_neighbors.test_valid_metrics_has_no_duplicate ()
Definition at line 2317 of file test_neighbors.py.
Variable Documentation
ALGORITHMS
tuple sklearn.neighbors.tests.test_neighbors.ALGORITHMS = ("ball_tree", "brute", "kd_tree", "auto")
Definition at line 83 of file test_neighbors.py.
COMMON_VALID_METRICS
sklearn.neighbors.tests.test_neighbors.COMMON_VALID_METRICS
Initial value:
=  sorted(
    set.intersection(*map(set, neighbors.VALID_METRICS.values()))
)
Definition at line 84 of file test_neighbors.py.
data
sklearn.neighbors.tests.test_neighbors.data
Definition at line 64 of file test_neighbors.py.
digits
sklearn.neighbors.tests.test_neighbors.digits = datasets.load_digits()
Definition at line 68 of file test_neighbors.py.
DISTANCE_METRIC_OBJS
list sklearn.neighbors.tests.test_neighbors.DISTANCE_METRIC_OBJS = ["DM_euclidean"]
Definition at line 96 of file test_neighbors.py.
iris
sklearn.neighbors.tests.test_neighbors.iris = datasets.load_iris()
Definition at line 62 of file test_neighbors.py.
kneighbors_graph
sklearn.neighbors.tests.test_neighbors.kneighbors_graph
Definition at line 91 of file test_neighbors.py.
P
tuple sklearn.neighbors.tests.test_neighbors.P = (1, 2, 3, 4, np.inf)
Definition at line 88 of file test_neighbors.py.
perm
sklearn.neighbors.tests.test_neighbors.perm = rng.permutation(iris.target.size)
Definition at line 63 of file test_neighbors.py.
radius_neighbors_graph
sklearn.neighbors.tests.test_neighbors.radius_neighbors_graph
Definition at line 92 of file test_neighbors.py.
rng
sklearn.neighbors.tests.test_neighbors.rng = np.random.RandomState(0)
Definition at line 60 of file test_neighbors.py.
SPARSE_OR_DENSE
sklearn.neighbors.tests.test_neighbors.SPARSE_OR_DENSE = SPARSE_TYPES + (np.asarray,)
Definition at line 81 of file test_neighbors.py.
SPARSE_TYPES
sklearn.neighbors.tests.test_neighbors.SPARSE_TYPES
Initial value:
=  tuple(
    BSR_CONTAINERS
    + COO_CONTAINERS
    + CSC_CONTAINERS
    + CSR_CONTAINERS
    + DOK_CONTAINERS
    + LIL_CONTAINERS
)
Definition at line 73 of file test_neighbors.py.
target
sklearn.neighbors.tests.test_neighbors.target
Definition at line 65 of file test_neighbors.py.
WEIGHTS
list sklearn.neighbors.tests.test_neighbors.WEIGHTS = ["uniform", "distance", _weight_func]
Definition at line 155 of file test_neighbors.py.