Code Cloning Analysis: numpy.lib.mixins Namespace Reference
numpy.lib.mixins Namespace Reference
Classes
class NDArrayOperatorsMixin
Functions
_disables_array_ufunc (obj)
_binary_method (ufunc, name)
_reflected_binary_method (ufunc, name)
_inplace_binary_method (ufunc, name)
_numeric_methods (ufunc, name)
_unary_method (ufunc, name)
Variables
list __all__ = ['NDArrayOperatorsMixin']
Detailed Description
Mixin classes for custom array types that don't inherit from ndarray.
Function Documentation
_binary_method()
numpy.lib.mixins._binary_method (ufunc, name) protected
Implement a forward binary method with a ufunc, e.g., __add__.
Definition at line 16 of file mixins.py.
References _disables_array_ufunc().
Referenced by _numeric_methods().
_disables_array_ufunc()
numpy.lib.mixins._disables_array_ufunc (obj) protected
True when __array_ufunc__ is set to None.
Definition at line 8 of file mixins.py.
Referenced by _binary_method(), and _reflected_binary_method().
_inplace_binary_method()
numpy.lib.mixins._inplace_binary_method (ufunc, name) protected
Implement an in-place binary method with a ufunc, e.g., __iadd__.
Definition at line 36 of file mixins.py.
Referenced by _numeric_methods().
_numeric_methods()
numpy.lib.mixins._numeric_methods (ufunc, name) protected
Implement forward, reflected and inplace binary methods with a ufunc.
Definition at line 44 of file mixins.py.
References _binary_method(), _inplace_binary_method(), and _reflected_binary_method().
_reflected_binary_method()
numpy.lib.mixins._reflected_binary_method (ufunc, name) protected
Implement a reflected binary method with a ufunc, e.g., __radd__.
Definition at line 26 of file mixins.py.
References _disables_array_ufunc().
Referenced by _numeric_methods().
_unary_method()
numpy.lib.mixins._unary_method (ufunc, name) protected
Implement a unary special method with a ufunc.
Definition at line 51 of file mixins.py.
Variable Documentation
__all__
list numpy.lib.mixins.__all__ = ['NDArrayOperatorsMixin'] private
Definition at line 5 of file mixins.py.