Code Cloning Analysis: scipy.optimize._nonlin Namespace Reference
scipy.optimize._nonlin Namespace Reference
Classes
class Anderson
class BroydenFirst
class BroydenSecond
class DiagBroyden
class ExcitingMixing
class GenericBroyden
class InverseJacobian
class Jacobian
class KrylovJacobian
class LinearMixing
class LowRankMatrix
class NoConvergence
class TerminationCondition
Functions
maxnorm (x)
_as_inexact (x)
_array_like (x, x0)
_safe_norm (v)
_set_doc (obj)
nonlin_solve (F, x0, jacobian='krylov', iter=None, verbose=False, maxiter=None, f_tol=None, f_rtol=None, x_tol=None, x_rtol=None, tol_norm=None, line_search='armijo', callback=None, full_output=False, raise_exception=True)
_nonlin_line_search (func, x, Fx, dx, search_type='armijo', rdiff=1e-8, smin=1e-2)
asjacobian (J)
_nonlin_wrapper (name, jac)
Variables
list __all__
_doc_parts
broyden1 = _nonlin_wrapper('broyden1', BroydenFirst)
broyden2 = _nonlin_wrapper('broyden2', BroydenSecond)
anderson = _nonlin_wrapper('anderson', Anderson)
linearmixing = _nonlin_wrapper('linearmixing', LinearMixing)
diagbroyden = _nonlin_wrapper('diagbroyden', DiagBroyden)
excitingmixing = _nonlin_wrapper('excitingmixing', ExcitingMixing)
newton_krylov = _nonlin_wrapper('newton_krylov', KrylovJacobian)
x = x
Function Documentation
_array_like()
scipy.optimize._nonlin._array_like (x, x0) protected
Return ndarray `x` as same array subclass and shape as `x0`
Definition at line 42 of file _nonlin.py.
Referenced by nonlin_solve().
_as_inexact()
scipy.optimize._nonlin._as_inexact (x) protected
Return `x` as an array, of either floats or complex floats
Definition at line 34 of file _nonlin.py.
Referenced by nonlin_solve().
_nonlin_line_search()
scipy.optimize._nonlin._nonlin_line_search (func, x, Fx, dx, search_type = 'armijo', rdiff = 1e-8, smin = 1e-2) protected
Definition at line 266 of file _nonlin.py.
_nonlin_wrapper()
scipy.optimize._nonlin._nonlin_wrapper (name, jac) protected
Construct a solver wrapper with given name and Jacobian approx.
It inspects the keyword arguments of ``jac.__init__``, and allows to
use the same arguments in the wrapper function, in addition to the
keyword arguments of `nonlin_solve`
Definition at line 1517 of file _nonlin.py.
References _nonlin_wrapper().
Referenced by _nonlin_wrapper().
_safe_norm()
scipy.optimize._nonlin._safe_norm (v) protected
Definition at line 49 of file _nonlin.py.
_set_doc()
scipy.optimize._nonlin._set_doc (obj) protected
Definition at line 111 of file _nonlin.py.
asjacobian()
scipy.optimize._nonlin.asjacobian (J)
Convert given object to one suitable for use as a Jacobian.
Definition at line 462 of file _nonlin.py.
Referenced by nonlin_solve().
maxnorm()
scipy.optimize._nonlin.maxnorm (x)
Definition at line 30 of file _nonlin.py.
nonlin_solve()
scipy.optimize._nonlin.nonlin_solve (F, x0, jacobian = 'krylov', iter = None, verbose = False, maxiter = None, f_tol = None, f_rtol = None, x_tol = None, x_rtol = None, tol_norm = None, line_search = 'armijo', callback = None, full_output = False, raise_exception = True)
Find a root of a function, in a way suitable for large-scale problems.
Parameters
----------
%(params_basic)s
jacobian : Jacobian
    A Jacobian approximation: `Jacobian` object or something that
    `asjacobian` can transform to one. Alternatively, a string specifying
    which of the builtin Jacobian approximations to use:
        krylov, broyden1, broyden2, anderson
        diagbroyden, linearmixing, excitingmixing
%(params_extra)s
full_output : bool
    If true, returns a dictionary `info` containing convergence
    information.
raise_exception : bool
    If True, a `NoConvergence` exception is raise if no solution is found.
See Also
--------
asjacobian, Jacobian
Notes
-----
This algorithm implements the inexact Newton method, with
backtracking or full line searches. Several Jacobian
approximations are available, including Krylov and Quasi-Newton
methods.
References
----------
.. [KIM] C. T. Kelley, \"Iterative Methods for Linear and Nonlinear
   Equations\". Society for Industrial and Applied Mathematics. (1995)
   https://archive.siam.org/books/kelley/fr16/
Definition at line 116 of file _nonlin.py.
References _array_like(), _as_inexact(), and asjacobian().
Variable Documentation
__all__
list scipy.optimize._nonlin.__all__ private
Initial value:
=  [
    'broyden1', 'broyden2', 'anderson', 'linearmixing',
    'diagbroyden', 'excitingmixing', 'newton_krylov',
    'BroydenFirst', 'KrylovJacobian', 'InverseJacobian']
Definition at line 16 of file _nonlin.py.
_doc_parts
scipy.optimize._nonlin._doc_parts protected
Initial value:
=  dict(
    params_basic=.strip(),
    params_extra=.strip()
)
Definition at line 59 of file _nonlin.py.
anderson
scipy.optimize._nonlin.anderson = _nonlin_wrapper('anderson', Anderson)
Definition at line 1563 of file _nonlin.py.
broyden1
scipy.optimize._nonlin.broyden1 = _nonlin_wrapper('broyden1', BroydenFirst)
Definition at line 1561 of file _nonlin.py.
broyden2
scipy.optimize._nonlin.broyden2 = _nonlin_wrapper('broyden2', BroydenSecond)
Definition at line 1562 of file _nonlin.py.
diagbroyden
scipy.optimize._nonlin.diagbroyden = _nonlin_wrapper('diagbroyden', DiagBroyden)
Definition at line 1565 of file _nonlin.py.
excitingmixing
scipy.optimize._nonlin.excitingmixing = _nonlin_wrapper('excitingmixing', ExcitingMixing)
Definition at line 1566 of file _nonlin.py.
linearmixing
scipy.optimize._nonlin.linearmixing = _nonlin_wrapper('linearmixing', LinearMixing)
Definition at line 1564 of file _nonlin.py.
newton_krylov
scipy.optimize._nonlin.newton_krylov = _nonlin_wrapper('newton_krylov', KrylovJacobian)
Definition at line 1567 of file _nonlin.py.
x
scipy.optimize._nonlin.x = x
Definition at line 504 of file _nonlin.py.