Code Cloning Analysis: pandas.core.groupby.indexing.GroupByIndexingMixin Class Reference
pandas.core.groupby.indexing.GroupByIndexingMixin Class Reference
Protected Member Functions
GroupByPositionalSelector _positional_selector (self)
np.ndarray _make_mask_from_positional_indexer (self, PositionalIndexer|tuple arg)
np.ndarray _make_mask_from_int (self, int arg)
bool|np.ndarray _make_mask_from_list (self, Iterable[int] args)
bool|np.ndarray _make_mask_from_tuple (self, tuple args)
bool|np.ndarray _make_mask_from_slice (self, slice arg)
np.ndarray _ascending_count (self)
np.ndarray _descending_count (self)
Protected Attributes
_ascending_count = arg
tuple _descending_count = (-arg - 1)
Detailed Description
Mixin for adding ._positional_selector to GroupBy.
Definition at line 32 of file indexing.py.
Member Function Documentation
_ascending_count()
np.ndarray pandas.core.groupby.indexing.GroupByIndexingMixin._ascending_count (self) protected
Definition at line 230 of file indexing.py.
_descending_count()
np.ndarray pandas.core.groupby.indexing.GroupByIndexingMixin._descending_count (self) protected
Definition at line 239 of file indexing.py.
_make_mask_from_int()
np.ndarray pandas.core.groupby.indexing.GroupByIndexingMixin._make_mask_from_int (self, int arg) protected
Definition at line 152 of file indexing.py.
Referenced by _positional_selector().
_make_mask_from_list()
bool | np.ndarray pandas.core.groupby.indexing.GroupByIndexingMixin._make_mask_from_list (self, Iterable[int] args) protected
Definition at line 158 of file indexing.py.
Referenced by _positional_selector().
_make_mask_from_positional_indexer()
np.ndarray pandas.core.groupby.indexing.GroupByIndexingMixin._make_mask_from_positional_indexer (self, PositionalIndexer | tuple arg) protected
Definition at line 123 of file indexing.py.
Referenced by pandas.core.groupby.groupby.GroupBy.head(), pandas.core.groupby.groupby.GroupBy.nth(), and pandas.core.groupby.groupby.GroupBy.tail().
_make_mask_from_slice()
bool | np.ndarray pandas.core.groupby.indexing.GroupByIndexingMixin._make_mask_from_slice (self, slice arg) protected
Definition at line 187 of file indexing.py.
Referenced by _positional_selector().
_make_mask_from_tuple()
bool | np.ndarray pandas.core.groupby.indexing.GroupByIndexingMixin._make_mask_from_tuple (self, tuple args) protected
Definition at line 172 of file indexing.py.
Referenced by _positional_selector().
_positional_selector()
GroupByPositionalSelector pandas.core.groupby.indexing.GroupByIndexingMixin._positional_selector (self) protected
Return positional selection for each group.
``groupby._positional_selector[i:j]`` is similar to
``groupby.apply(lambda x: x.iloc[i:j])``
but much faster and preserves the original index and order.
``_positional_selector[]`` is compatible with and extends :meth:`~GroupBy.head`
and :meth:`~GroupBy.tail`. For example:
- ``head(5)``
- ``_positional_selector[5:-5]``
- ``tail(5)``
together return all the rows.
Allowed inputs for the index are:
- An integer valued iterable, e.g. ``range(2, 4)``.
- A comma separated list of integers and slices, e.g. ``5``, ``2, 4``, ``2:4``.
The output format is the same as :meth:`~GroupBy.head` and
:meth:`~GroupBy.tail`, namely
a subset of the ``DataFrame`` or ``Series`` with the index and order preserved.
Returns
-------
Series
    The filtered subset of the original Series.
DataFrame
    The filtered subset of the original DataFrame.
See Also
--------
DataFrame.iloc : Purely integer-location based indexing for selection by
    position.
GroupBy.head : Return first n rows of each group.
GroupBy.tail : Return last n rows of each group.
GroupBy.nth : Take the nth row from each group if n is an int, or a
    subset of rows, if n is a list of ints.
Notes
-----
- The slice step cannot be negative.
- If the index specification results in overlaps, the item is not duplicated.
- If the index specification changes the order of items, then
  they are returned in their original order.
  By contrast, ``DataFrame.iloc`` can change the row order.
- ``groupby()`` parameters such as as_index and dropna are ignored.
The differences between ``_positional_selector[]`` and :meth:`~GroupBy.nth`
with ``as_index=False`` are:
- Input to ``_positional_selector`` can include
  one or more slices whereas ``nth``
  just handles an integer or a list of integers.
- ``_positional_selector`` can  accept a slice relative to the
  last row of each group.
- ``_positional_selector`` does not have an equivalent to the
  ``nth()`` ``dropna`` parameter.
Examples
--------
>>> df = pd.DataFrame([["a", 1], ["a", 2], ["a", 3], ["b", 4], ["b", 5]],
...                   columns=["A", "B"])
>>> df.groupby("A")._positional_selector[1:2]
   A  B
1  a  2
4  b  5
>>> df.groupby("A")._positional_selector[1, -1]
   A  B
1  a  2
2  a  3
4  b  5
Definition at line 38 of file indexing.py.
References _ascending_count, _descending_count, _make_mask_from_int(), _make_mask_from_list(), _make_mask_from_slice(), and _make_mask_from_tuple().
Member Data Documentation
_ascending_count
pandas.core.groupby.indexing.GroupByIndexingMixin._ascending_count = arg protected
Definition at line 154 of file indexing.py.
Referenced by _positional_selector().
_descending_count
tuple pandas.core.groupby.indexing.GroupByIndexingMixin._descending_count = (-arg - 1) protected
Definition at line 156 of file indexing.py.
Referenced by _positional_selector().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/core/groupby/indexing.py