Code Cloning Analysis: pandas.core._numba.extensions.IlocType Class Reference
pandas.core._numba.extensions.IlocType Class Reference
Public Member Functions
None __init__ (self, obj_type)
key (self)
Public Attributes
obj_type = obj_type
Detailed Description
Definition at line 524 of file extensions.py.
Constructor & Destructor Documentation
__init__()
None pandas.core._numba.extensions.IlocType.__init__ (self, obj_type)
Definition at line 525 of file extensions.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
key()
pandas.core._numba.extensions.IlocType.key (self)
Definition at line 531 of file extensions.py.
Referenced by pip._internal.self_outdated_check.SelfCheckState.get().
Member Data Documentation
obj_type
pandas.core._numba.extensions.IlocType.obj_type = obj_type
Definition at line 526 of file extensions.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/core/_numba/extensions.py