Code Cloning Analysis: matplotlib.backends.backend_ps Namespace Reference
matplotlib.backends.backend_ps Namespace Reference
Classes
class _BackendPS
class _Orientation
class FigureCanvasPS
class RendererPS
Functions
_nums_to_str (*args, sep=" ")
_move_path_to_path_or_stream (src, dst)
_font_to_ps_type3 (font_path, chars)
_font_to_ps_type42 (font_path, chars, fh)
_serialize_type42 (font, subset, fontdata)
_version_and_breakpoints (loca, fontdata)
_bounds (font)
_generate_charstrings (font)
_generate_sfnts (fontdata, font, breakpoints)
_log_if_debug_on (meth)
_convert_psfrags (tmppath, psfrags, paper_width, paper_height, orientation)
_try_distill (func, tmppath, *args, **kwargs)
gs_distill (tmpfile, eps=False, ptype='letter', bbox=None, rotated=False)
xpdf_distill (tmpfile, eps=False, ptype='letter', bbox=None, rotated=False)
get_bbox_header (lbrt, rotated=False)
_get_bbox_header (lbrt)
_get_rotate_command (lbrt)
pstoeps (tmpfile, bbox=None, rotated=False)
Variables
_log = logging.getLogger(__name__)
bool debugPS = False
dict papersize
FigureManagerPS = FigureManagerBase
list _psDefs
Detailed Description
A PostScript backend, which can produce both PostScript .ps and .eps.
Function Documentation
_bounds()
matplotlib.backends.backend_ps._bounds (font) protected
Compute the font bounding box, as if all glyphs were written
at the same start position.
Helper function for _font_to_ps_type42.
Parameters
----------
font : fontTools.ttLib.ttFont.TTFont
    The font
Returns
-------
tuple
    (xMin, yMin, xMax, yMax) of the combined bounding box
    of all the glyphs in the font
Definition at line 300 of file backend_ps.py.
_convert_psfrags()
matplotlib.backends.backend_ps._convert_psfrags (tmppath, psfrags, paper_width, paper_height, orientation) protected
When we want to use the LaTeX backend with postscript, we write PSFrag tags
to a temporary postscript file, each one marking a position for LaTeX to
render some text. convert_psfrags generates a LaTeX document containing the
commands to convert those tags to text. LaTeX/dvips produces the postscript
file that includes the actual text.
Definition at line 1227 of file backend_ps.py.
Referenced by matplotlib.backends.backend_ps.FigureCanvasPS._print_figure_tex().
_font_to_ps_type3()
matplotlib.backends.backend_ps._font_to_ps_type3 (font_path, chars) protected
Subset *chars* from the font at *font_path* into a Type 3 font.
Parameters
----------
font_path : path-like
    Path to the font to be subsetted.
chars : str
    The characters to include in the subsetted font.
Returns
-------
str
    The string representation of a Type 3 font, which can be included
    verbatim into a PostScript file.
Definition at line 92 of file backend_ps.py.
Referenced by matplotlib.backends.backend_ps.FigureCanvasPS._print_figure().
_font_to_ps_type42()
matplotlib.backends.backend_ps._font_to_ps_type42 (font_path, chars, fh) protected
Subset *chars* from the font at *font_path* into a Type 42 font at *fh*.
Parameters
----------
font_path : path-like
    Path to the font to be subsetted.
chars : str
    The characters to include in the subsetted font.
fh : file-like
    Where to write the font.
Definition at line 173 of file backend_ps.py.
References _serialize_type42().
Referenced by matplotlib.backends.backend_ps.FigureCanvasPS._print_figure().
_generate_charstrings()
matplotlib.backends.backend_ps._generate_charstrings (font) protected
Transform font glyphs into CharStrings
Helper function for _font_to_ps_type42.
Parameters
----------
font : fontTools.ttLib.ttFont.TTFont
    The font
Returns
-------
str
    A definition of the CharStrings dictionary in PostScript
Definition at line 325 of file backend_ps.py.
Referenced by _serialize_type42().
_generate_sfnts()
matplotlib.backends.backend_ps._generate_sfnts (fontdata, font, breakpoints) protected
Transform font data into PostScript sfnts format.
Helper function for _font_to_ps_type42.
Parameters
----------
fontdata : bytes
    The raw data of the font
font : fontTools.ttLib.ttFont.TTFont
    The fontTools font object
breakpoints : list
    Sorted offsets of possible breakpoints
Returns
-------
str
    The sfnts array for the font definition, consisting
    of hex-encoded strings in PostScript format
Definition at line 349 of file backend_ps.py.
Referenced by _serialize_type42().
_get_bbox_header()
matplotlib.backends.backend_ps._get_bbox_header (lbrt) protected
Return a PostScript header string for bounding box *lbrt*=(l, b, r, t).
Definition at line 1372 of file backend_ps.py.
Referenced by get_bbox_header(), and pstoeps().
_get_rotate_command()
matplotlib.backends.backend_ps._get_rotate_command (lbrt) protected
Return a PostScript 90° rotation command for bounding box *lbrt*=(l, b, r, t).
Definition at line 1379 of file backend_ps.py.
Referenced by get_bbox_header(), and pstoeps().
_log_if_debug_on()
matplotlib.backends.backend_ps._log_if_debug_on (meth) protected
Wrap `RendererPS` method *meth* to emit a PS comment with the method name,
if the global flag `debugPS` is set.
Definition at line 384 of file backend_ps.py.
_move_path_to_path_or_stream()
matplotlib.backends.backend_ps._move_path_to_path_or_stream (src, dst) protected
Move the contents of file at *src* to path-or-filelike *dst*.
If *dst* is a path, the metadata of *src* are *not* copied.
Definition at line 76 of file backend_ps.py.
Referenced by matplotlib.backends.backend_ps.FigureCanvasPS._print_figure(), and matplotlib.backends.backend_ps.FigureCanvasPS._print_figure_tex().
_nums_to_str()
matplotlib.backends.backend_ps._nums_to_str (* args, sep = " ") protected
Definition at line 72 of file backend_ps.py.
_serialize_type42()
matplotlib.backends.backend_ps._serialize_type42 (font, subset, fontdata) protected
Output a PostScript Type-42 format representation of font
Parameters
----------
font : fontTools.ttLib.ttFont.TTFont
    The original font object
subset : fontTools.ttLib.ttFont.TTFont
    The subset font object
fontdata : bytes
    The raw font data in TTF format
Returns
-------
str
    The Type-42 formatted font
Definition at line 209 of file backend_ps.py.
References _generate_charstrings(), _generate_sfnts(), and _version_and_breakpoints().
Referenced by _font_to_ps_type42().
_try_distill()
matplotlib.backends.backend_ps._try_distill (func, tmppath, * args, ** kwargs) protected
Definition at line 1276 of file backend_ps.py.
_version_and_breakpoints()
matplotlib.backends.backend_ps._version_and_breakpoints (loca, fontdata) protected
Read the version number of the font and determine sfnts breakpoints.
When a TrueType font file is written as a Type 42 font, it has to be
broken into substrings of at most 65535 bytes. These substrings must
begin at font table boundaries or glyph boundaries in the glyf table.
This function determines all possible breakpoints and it is the caller's
responsibility to do the splitting.
Helper function for _font_to_ps_type42.
Parameters
----------
loca : fontTools.ttLib._l_o_c_a.table__l_o_c_a or None
    The loca table of the font if available
fontdata : bytes
    The raw data of the font
Returns
-------
version : tuple[int, int]
    A 2-tuple of the major version number and minor version number.
breakpoints : list[int]
    The breakpoints is a sorted list of offsets into fontdata; if loca is not
    available, just the table boundaries.
Definition at line 257 of file backend_ps.py.
Referenced by _serialize_type42().
get_bbox_header()
matplotlib.backends.backend_ps.get_bbox_header (lbrt, rotated = False)
Return a postscript header string for the given bbox lbrt=(l, b, r, t).
Optionally, return rotate command.
Definition at line 1364 of file backend_ps.py.
References _get_bbox_header(), and _get_rotate_command().
gs_distill()
matplotlib.backends.backend_ps.gs_distill (tmpfile, eps = False, ptype = 'letter', bbox = None, rotated = False)
Use ghostscript's pswrite or epswrite device to distill a file.
This yields smaller files without illegal encapsulated postscript
operators. The output is low-level, converting text to outlines.
Definition at line 1283 of file backend_ps.py.
References pstoeps().
pstoeps()
matplotlib.backends.backend_ps.pstoeps (tmpfile, bbox = None, rotated = False)
Convert the postscript to encapsulated postscript.  The bbox of
the eps file will be replaced with the given *bbox* argument. If
None, original bbox will be used.
Definition at line 1385 of file backend_ps.py.
References _get_bbox_header(), and _get_rotate_command().
Referenced by gs_distill(), and xpdf_distill().
xpdf_distill()
matplotlib.backends.backend_ps.xpdf_distill (tmpfile, eps = False, ptype = 'letter', bbox = None, rotated = False)
Use ghostscript's ps2pdf and xpdf's/poppler's pdftops to distill a file.
This yields smaller files without illegal encapsulated postscript
operators. This distiller is preferred, generating high-level postscript
output that treats text as text.
Definition at line 1322 of file backend_ps.py.
References pstoeps().
Variable Documentation
_log
matplotlib.backends.backend_ps._log = logging.getLogger(__name__) protected
Definition at line 41 of file backend_ps.py.
_psDefs
list matplotlib.backends.backend_ps._psDefs protected
Initial value:
=  [
    # name proc  *_d*  -
    # Note that this cannot be bound to /d, because when embedding a Type3 font
    # we may want to define a "d" glyph using "/d{...} d" which would locally
    # overwrite the definition.
    "/_d { bind def } bind def",
    # x y  *m*  -
    "/m { moveto } _d",
    # x y  *l*  -
    "/l { lineto } _d",
    # x y  *r*  -
    "/r { rlineto } _d",
    # x1 y1 x2 y2 x y *c*  -
    "/c { curveto } _d",
    # *cl*  -
    "/cl { closepath } _d",
    # *ce*  -
    "/ce { closepath eofill } _d",
    # wx wy llx lly urx ury  *setcachedevice*  -
    "/sc { setcachedevice } _d",
]
Definition at line 1455 of file backend_ps.py.
debugPS
bool matplotlib.backends.backend_ps.debugPS = False
Definition at line 42 of file backend_ps.py.
FigureManagerPS
matplotlib.backends.backend_ps.FigureManagerPS = FigureManagerBase
Definition at line 1440 of file backend_ps.py.
papersize
dict matplotlib.backends.backend_ps.papersize
Initial value:
=  {'letter': (8.5, 11),
             'legal': (8.5, 14),
             'ledger': (11, 17),
             'a0': (33.11, 46.81),
             'a1': (23.39, 33.11),
             'a2': (16.54, 23.39),
             'a3': (11.69, 16.54),
             'a4': (8.27, 11.69),
             'a5': (5.83, 8.27),
             'a6': (4.13, 5.83),
             'a7': (2.91, 4.13),
             'a8': (2.05, 2.91),
             'a9': (1.46, 2.05),
             'a10': (1.02, 1.46),
             'b0': (40.55, 57.32),
             'b1': (28.66, 40.55),
             'b2': (20.27, 28.66),
             'b3': (14.33, 20.27),
             'b4': (10.11, 14.33),
             'b5': (7.16, 10.11),
             'b6': (5.04, 7.16),
             'b7': (3.58, 5.04),
             'b8': (2.51, 3.58),
             'b9': (1.76, 2.51),
             'b10': (1.26, 1.76)}
Definition at line 45 of file backend_ps.py.