Code Cloning Analysis: scipy.sparse.linalg.tests.test_propack Namespace Reference
scipy.sparse.linalg.tests.test_propack Namespace Reference
Functions
is_complex_type (dtype)
is_32bit ()
is_windows ()
generate_matrix (constructor, n, m, f, dtype=float, rseed=0, **kwargs)
assert_orthogonal (u1, u2, rtol, atol)
check_svdp (n, m, constructor, dtype, k, irl_mode, which, f=0.8)
test_svdp (ctor, dtype, irl, which)
test_examples (dtype, irl)
test_shifts (shifts, dtype)
test_shifts_accuracy ()
Variables
dict TOLS
list _dtypes = []
list marks = []
Function Documentation
assert_orthogonal()
scipy.sparse.linalg.tests.test_propack.assert_orthogonal (u1, u2, rtol, atol)
Check that the first k rows of u1 and u2 are orthogonal
Definition at line 63 of file test_propack.py.
References assert_orthogonal(), and generate_matrix().
Referenced by assert_orthogonal().
check_svdp()
scipy.sparse.linalg.tests.test_propack.check_svdp (n, m, constructor, dtype, k, irl_mode, which, f = 0.8)
Definition at line 69 of file test_propack.py.
generate_matrix()
scipy.sparse.linalg.tests.test_propack.generate_matrix (constructor, n, m, f, dtype = float, rseed = 0, ** kwargs)
Generate a random sparse matrix
Definition at line 50 of file test_propack.py.
Referenced by assert_orthogonal().
is_32bit()
scipy.sparse.linalg.tests.test_propack.is_32bit ()
Definition at line 25 of file test_propack.py.
is_complex_type()
scipy.sparse.linalg.tests.test_propack.is_complex_type (dtype)
Definition at line 21 of file test_propack.py.
is_windows()
scipy.sparse.linalg.tests.test_propack.is_windows ()
Definition at line 29 of file test_propack.py.
test_examples()
scipy.sparse.linalg.tests.test_propack.test_examples (dtype, irl)
Definition at line 116 of file test_propack.py.
test_shifts()
scipy.sparse.linalg.tests.test_propack.test_shifts (shifts, dtype)
Definition at line 166 of file test_propack.py.
test_shifts_accuracy()
scipy.sparse.linalg.tests.test_propack.test_shifts_accuracy ()
Definition at line 179 of file test_propack.py.
test_svdp()
scipy.sparse.linalg.tests.test_propack.test_svdp (ctor, dtype, irl, which)
Definition at line 97 of file test_propack.py.
Variable Documentation
_dtypes
scipy.sparse.linalg.tests.test_propack._dtypes = [] protected
Definition at line 33 of file test_propack.py.
marks
list scipy.sparse.linalg.tests.test_propack.marks = []
Definition at line 35 of file test_propack.py.
TOLS
dict scipy.sparse.linalg.tests.test_propack.TOLS
Initial value:
=  {
    np.float32: 1e-4,
    np.float64: 1e-8,
    np.complex64: 1e-4,
    np.complex128: 1e-8,
}
Definition at line 13 of file test_propack.py.