Code Cloning Analysis: numpy.lib.format Namespace Reference
numpy.lib.format Namespace Reference
Functions
_check_version (version)
magic (major, minor)
read_magic (fp)
dtype_to_descr (dtype)
descr_to_dtype (descr)
header_data_from_array_1_0 (array)
_wrap_header (header, version)
_wrap_header_guess_version (header)
_write_array_header (fp, d, version=None)
write_array_header_1_0 (fp, d)
write_array_header_2_0 (fp, d)
read_array_header_1_0 (fp, max_header_size=_MAX_HEADER_SIZE)
read_array_header_2_0 (fp, max_header_size=_MAX_HEADER_SIZE)
_filter_header (s)
_read_array_header (fp, version, max_header_size=_MAX_HEADER_SIZE)
write_array (fp, array, version=None, allow_pickle=True, pickle_kwargs=None)
read_array (fp, allow_pickle=False, pickle_kwargs=None, *, max_header_size=_MAX_HEADER_SIZE)
open_memmap (filename, mode='r+', dtype=None, shape=None, fortran_order=False, version=None, *, max_header_size=_MAX_HEADER_SIZE)
_read_bytes (fp, size, error_template="ran out of data")
Variables
list __all__ = []
dict EXPECTED_KEYS = {'descr', 'fortran_order', 'shape'}
str MAGIC_PREFIX = b'\x93NUMPY'
int MAGIC_LEN = len(MAGIC_PREFIX) + 2
int ARRAY_ALIGN = 64
int BUFFER_SIZE = 2**18
int GROWTH_AXIS_MAX_DIGITS = 21
dict _header_size_info
int _MAX_HEADER_SIZE = 10000
Detailed Description
Binary serialization
NPY format
==========
A simple format for saving numpy arrays to disk with the full
information about them.
The ``.npy`` format is the standard binary file format in NumPy for
persisting a *single* arbitrary NumPy array on disk. The format stores all
of the shape and dtype information necessary to reconstruct the array
correctly even on another machine with a different architecture.
The format is designed to be as simple as possible while achieving
its limited goals.
The ``.npz`` format is the standard format for persisting *multiple* NumPy
arrays on disk. A ``.npz`` file is a zip file containing multiple ``.npy``
files, one for each array.
Capabilities
------------
- Can represent all NumPy arrays including nested record arrays and
  object arrays.
- Represents the data in its native binary form.
- Supports Fortran-contiguous arrays directly.
- Stores all of the necessary information to reconstruct the array
  including shape and dtype on a machine of a different
  architecture.  Both little-endian and big-endian arrays are
  supported, and a file with little-endian numbers will yield
  a little-endian array on any machine reading the file. The
  types are described in terms of their actual sizes. For example,
  if a machine with a 64-bit C "long int" writes out an array with
  "long ints", a reading machine with 32-bit C "long ints" will yield
  an array with 64-bit integers.
- Is straightforward to reverse engineer. Datasets often live longer than
  the programs that created them. A competent developer should be
  able to create a solution in their preferred programming language to
  read most ``.npy`` files that they have been given without much
  documentation.
- Allows memory-mapping of the data. See `open_memmap`.
- Can be read from a filelike stream object instead of an actual file.
- Stores object arrays, i.e. arrays containing elements that are arbitrary
  Python objects. Files with object arrays are not to be mmapable, but
  can be read and written to disk.
Limitations
-----------
- Arbitrary subclasses of numpy.ndarray are not completely preserved.
  Subclasses will be accepted for writing, but only the array data will
  be written out. A regular numpy.ndarray object will be created
  upon reading the file.
.. warning::
  Due to limitations in the interpretation of structured dtypes, dtypes
  with fields with empty names will have the names replaced by 'f0', 'f1',
  etc. Such arrays will not round-trip through the format entirely
  accurately. The data is intact; only the field names will differ. We are
  working on a fix for this. This fix will not require a change in the
  file format. The arrays with such structures can still be saved and
  restored, and the correct dtype may be restored by using the
  ``loadedarray.view(correct_dtype)`` method.
File extensions
---------------
We recommend using the ``.npy`` and ``.npz`` extensions for files saved
in this format. This is by no means a requirement; applications may wish
to use these file formats but use an extension specific to the
application. In the absence of an obvious alternative, however,
we suggest using ``.npy`` and ``.npz``.
Version numbering
-----------------
The version numbering of these formats is independent of NumPy version
numbering. If the format is upgraded, the code in `numpy.io` will still
be able to read and write Version 1.0 files.
Format Version 1.0
------------------
The first 6 bytes are a magic string: exactly ``\\x93NUMPY``.
The next 1 byte is an unsigned byte: the major version number of the file
format, e.g. ``\\x01``.
The next 1 byte is an unsigned byte: the minor version number of the file
format, e.g. ``\\x00``. Note: the version of the file format is not tied
to the version of the numpy package.
The next 2 bytes form a little-endian unsigned short int: the length of
the header data HEADER_LEN.
The next HEADER_LEN bytes form the header data describing the array's
format. It is an ASCII string which contains a Python literal expression
of a dictionary. It is terminated by a newline (``\\n``) and padded with
spaces (``\\x20``) to make the total of
``len(magic string) + 2 + len(length) + HEADER_LEN`` be evenly divisible
by 64 for alignment purposes.
The dictionary contains three keys:
    "descr" : dtype.descr
      An object that can be passed as an argument to the `numpy.dtype`
      constructor to create the array's dtype.
    "fortran_order" : bool
      Whether the array data is Fortran-contiguous or not. Since
      Fortran-contiguous arrays are a common form of non-C-contiguity,
      we allow them to be written directly to disk for efficiency.
    "shape" : tuple of int
      The shape of the array.
For repeatability and readability, the dictionary keys are sorted in
alphabetic order. This is for convenience only. A writer SHOULD implement
this if possible. A reader MUST NOT depend on this.
Following the header comes the array data. If the dtype contains Python
objects (i.e. ``dtype.hasobject is True``), then the data is a Python
pickle of the array. Otherwise the data is the contiguous (either C-
or Fortran-, depending on ``fortran_order``) bytes of the array.
Consumers can figure out the number of bytes by multiplying the number
of elements given by the shape (noting that ``shape=()`` means there is
1 element) by ``dtype.itemsize``.
Format Version 2.0
------------------
The version 1.0 format only allowed the array header to have a total size of
65535 bytes.  This can be exceeded by structured arrays with a large number of
columns.  The version 2.0 format extends the header size to 4 GiB.
`numpy.save` will automatically save in 2.0 format if the data requires it,
else it will always use the more compatible 1.0 format.
The description of the fourth element of the header therefore has become:
"The next 4 bytes form a little-endian unsigned int: the length of the header
data HEADER_LEN."
Format Version 3.0
------------------
This version replaces the ASCII string (which in practice was latin1) with
a utf8-encoded string, so supports structured types with any unicode field
names.
Notes
-----
The ``.npy`` format, including motivation for creating it and a comparison of
alternatives, is described in the
:doc:`"npy-format" NEP <neps:nep-0001-npy-format>`, however details have
evolved with time and this document is more current.
Function Documentation
_check_version()
numpy.lib.format._check_version (version) protected
Definition at line 196 of file format.py.
_filter_header()
numpy.lib.format._filter_header (s) protected
Clean up 'L' in npz header ints.
Cleans up the 'L' in strings representing integers. Needed to allow npz
headers produced in Python2 to be read in Python3.
Parameters
----------
s : string
    Npy file header.
Returns
-------
header : str
    Cleaned up header.
Definition at line 552 of file format.py.
Referenced by _read_array_header().
_read_array_header()
numpy.lib.format._read_array_header (fp, version, max_header_size = _MAX_HEADER_SIZE) protected
see read_array_header_1_0
Definition at line 587 of file format.py.
References _filter_header(), _read_bytes(), numpy.core.fromnumeric.all(), descr_to_dtype(), and numpy.lib.utils.safe_eval().
Referenced by open_memmap(), read_array(), read_array_header_1_0(), and read_array_header_2_0().
_read_bytes()
numpy.lib.format._read_bytes (fp, size, error_template = "ran out of data") protected
Read from file-like object until size bytes are read.
Raises ValueError if not EOF is encountered before size bytes are read.
Non-blocking objects only supported if they derive from io objects.
Required as e.g. ZipExtFile in python 2.6 can return less data than
requested.
Definition at line 951 of file format.py.
Referenced by _read_array_header(), read_array(), and read_magic().
_wrap_header()
numpy.lib.format._wrap_header (header, version) protected
Takes a stringified header, and attaches the prefix and padding to it
Definition at line 366 of file format.py.
References magic().
Referenced by _wrap_header_guess_version(), and _write_array_header().
_wrap_header_guess_version()
numpy.lib.format._wrap_header_guess_version (header) protected
Like `_wrap_header`, but chooses an appropriate version given the contents
Definition at line 390 of file format.py.
References _wrap_header().
Referenced by _write_array_header().
_write_array_header()
numpy.lib.format._write_array_header (fp, d, version = None) protected
 Write the header for an array and returns the version used
Parameters
----------
fp : filelike object
d : dict
    This has the appropriate entries for writing its string representation
    to the header of the file.
version : tuple or None
    None means use oldest that works. Providing an explicit version will
    raise a ValueError if the format does not allow saving this data.
    Default: None
Definition at line 414 of file format.py.
References _wrap_header(), and _wrap_header_guess_version().
Referenced by open_memmap(), write_array(), write_array_header_1_0(), and write_array_header_2_0().
descr_to_dtype()
numpy.lib.format.descr_to_dtype (descr)
Returns a dtype based off the given description.
This is essentially the reverse of `dtype_to_descr()`. It will remove
the valueless padding fields created by, i.e. simple fields like
dtype('float32'), and then convert the description to its corresponding
dtype.
Parameters
----------
descr : object
    The object retrieved by dtype.descr. Can be passed to
    `numpy.dtype()` in order to replicate the input dtype.
Returns
-------
dtype : dtype
    The dtype constructed by the description.
Definition at line 282 of file format.py.
References descr_to_dtype().
Referenced by _read_array_header(), and descr_to_dtype().
dtype_to_descr()
numpy.lib.format.dtype_to_descr (dtype)
Get a serializable descriptor from the dtype.
The .descr attribute of a dtype object cannot be round-tripped through
the dtype() constructor. Simple types, like dtype('float32'), have
a descr which looks like a record array with one field with '' as
a name. The dtype() constructor interprets this as a request to give
a default name.  Instead, we construct descriptor that can be passed to
dtype().
Parameters
----------
dtype : dtype
    The dtype of the array that will be written to disk.
Returns
-------
descr : object
    An object that can be passed to `numpy.dtype()` in order to
    replicate the input dtype.
Definition at line 243 of file format.py.
References numpy.lib.utils.drop_metadata().
Referenced by header_data_from_array_1_0(), and open_memmap().
header_data_from_array_1_0()
numpy.lib.format.header_data_from_array_1_0 (array)
 Get the dictionary of header metadata from a numpy.ndarray.
Parameters
----------
array : numpy.ndarray
Returns
-------
d : dict
    This has the appropriate entries for writing its string representation
    to the header of the file.
Definition at line 338 of file format.py.
References dtype_to_descr().
Referenced by write_array().
magic()
numpy.lib.format.magic (major, minor)
 Return the magic string for the given file format version.
Parameters
----------
major : int in [0, 255]
minor : int in [0, 255]
Returns
-------
magic : str
Raises
------
ValueError if the version cannot be formatted.
Definition at line 201 of file format.py.
Referenced by _wrap_header().
open_memmap()
numpy.lib.format.open_memmap (filename, mode = 'r+', dtype = None, shape = None, fortran_order = False, version = None, * , max_header_size = _MAX_HEADER_SIZE)
Open a .npy file as a memory-mapped array.
This may be used to read an existing file or create a new one.
Parameters
----------
filename : str or path-like
    The name of the file on disk.  This may *not* be a file-like
    object.
mode : str, optional
    The mode in which to open the file; the default is 'r+'.  In
    addition to the standard file modes, 'c' is also accepted to mean
    "copy on write."  See `memmap` for the available mode strings.
dtype : data-type, optional
    The data type of the array if we are creating a new file in "write"
    mode, if not, `dtype` is ignored.  The default value is None, which
    results in a data-type of `float64`.
shape : tuple of int
    The shape of the array if we are creating a new file in "write"
    mode, in which case this parameter is required.  Otherwise, this
    parameter is ignored and is thus optional.
fortran_order : bool, optional
    Whether the array should be Fortran-contiguous (True) or
    C-contiguous (False, the default) if we are creating a new file in
    "write" mode.
version : tuple of int (major, minor) or None
    If the mode is a "write" mode, then this is the version of the file
    format used to create the file.  None means use the oldest
    supported version that is able to store the data.  Default: None
max_header_size : int, optional
    Maximum allowed size of the header.  Large headers may not be safe
    to load securely and thus require explicitly passing a larger value.
    See :py:func:`ast.literal_eval()` for details.
Returns
-------
marray : memmap
    The memory-mapped array.
Raises
------
ValueError
    If the data or the mode is invalid.
OSError
    If the file is not found or cannot be opened correctly.
See Also
--------
numpy.memmap
Definition at line 844 of file format.py.
References _read_array_header(), _write_array_header(), dtype_to_descr(), and read_magic().
read_array()
numpy.lib.format.read_array (fp, allow_pickle = False, pickle_kwargs = None, * , max_header_size = _MAX_HEADER_SIZE)
Read an array from an NPY file.
Parameters
----------
fp : file_like object
    If this is not a real file object, then this may take extra memory
    and time.
allow_pickle : bool, optional
    Whether to allow writing pickled data. Default: False
    .. versionchanged:: 1.16.3
        Made default False in response to CVE-2019-6446.
pickle_kwargs : dict
    Additional keyword arguments to pass to pickle.load. These are only
    useful when loading object arrays saved on Python 2 when using
    Python 3.
max_header_size : int, optional
    Maximum allowed size of the header.  Large headers may not be safe
    to load securely and thus require explicitly passing a larger value.
    See :py:func:`ast.literal_eval()` for details.
    This option is ignored when `allow_pickle` is passed.  In that case
    the file is by definition trusted and the limit is unnecessary.
Returns
-------
array : ndarray
    The array from the data on disk.
Raises
------
ValueError
    If the data is invalid, or allow_pickle=False and the file contains
    an object array.
Definition at line 738 of file format.py.
References _read_array_header(), _read_bytes(), numpy.core.fromnumeric.min(), and read_magic().
read_array_header_1_0()
numpy.lib.format.read_array_header_1_0 (fp, max_header_size = _MAX_HEADER_SIZE)
Read an array header from a filelike object using the 1.0 file format
version.
This will leave the file object located just after the header.
Parameters
----------
fp : filelike object
    A file object or something with a `.read()` method like a file.
Returns
-------
shape : tuple of int
    The shape of the array.
fortran_order : bool
    The array data will be written out directly if it is either
    C-contiguous or Fortran-contiguous. Otherwise, it will be made
    contiguous before writing it out.
dtype : dtype
    The dtype of the file's data.
max_header_size : int, optional
    Maximum allowed size of the header.  Large headers may not be safe
    to load securely and thus require explicitly passing a larger value.
    See :py:func:`ast.literal_eval()` for details.
Raises
------
ValueError
    If the data is invalid.
Definition at line 477 of file format.py.
References _read_array_header().
read_array_header_2_0()
numpy.lib.format.read_array_header_2_0 (fp, max_header_size = _MAX_HEADER_SIZE)
Read an array header from a filelike object using the 2.0 file format
version.
This will leave the file object located just after the header.
.. versionadded:: 1.9.0
Parameters
----------
fp : filelike object
    A file object or something with a `.read()` method like a file.
max_header_size : int, optional
    Maximum allowed size of the header.  Large headers may not be safe
    to load securely and thus require explicitly passing a larger value.
    See :py:func:`ast.literal_eval()` for details.
Returns
-------
shape : tuple of int
    The shape of the array.
fortran_order : bool
    The array data will be written out directly if it is either
    C-contiguous or Fortran-contiguous. Otherwise, it will be made
    contiguous before writing it out.
dtype : dtype
    The dtype of the file's data.
Raises
------
ValueError
    If the data is invalid.
Definition at line 513 of file format.py.
References _read_array_header().
read_magic()
numpy.lib.format.read_magic (fp)
 Read the magic string to get the version of the file format.
Parameters
----------
fp : filelike object
Returns
-------
major : int
minor : int
Definition at line 223 of file format.py.
References _read_bytes().
Referenced by open_memmap(), and read_array().
write_array()
numpy.lib.format.write_array (fp, array, version = None, allow_pickle = True, pickle_kwargs = None)
Write an array to an NPY file, including a header.
If the array is neither C-contiguous nor Fortran-contiguous AND the
file_like object is not a real file object, this function will have to
copy data in memory.
Parameters
----------
fp : file_like object
    An open, writable file object, or similar object with a
    ``.write()`` method.
array : ndarray
    The array to write to disk.
version : (int, int) or None, optional
    The version number of the format. None means use the oldest
    supported version that is able to store the data.  Default: None
allow_pickle : bool, optional
    Whether to allow writing pickled data. Default: True
pickle_kwargs : dict, optional
    Additional keyword arguments to pass to pickle.dump, excluding
    'protocol'. These are only useful when pickling objects in object
    arrays on Python 3 to Python 2 compatible format.
Raises
------
ValueError
    If the array cannot be persisted. This includes the case of
    allow_pickle=False and array being an object array.
Various other errors
    If the array contains Python objects as part of its dtype, the
    process of pickling them may raise various errors if the objects
    are not picklable.
Definition at line 666 of file format.py.
References _write_array_header(), header_data_from_array_1_0(), and numpy.core.fromnumeric.max().
write_array_header_1_0()
numpy.lib.format.write_array_header_1_0 (fp, d)
 Write the header for an array using the 1.0 format.
Parameters
----------
fp : filelike object
d : dict
    This has the appropriate entries for writing its string
    representation to the header of the file.
Definition at line 449 of file format.py.
References _write_array_header().
write_array_header_2_0()
numpy.lib.format.write_array_header_2_0 (fp, d)
 Write the header for an array using the 2.0 format.
    The 2.0 format allows storing very large structured arrays.
.. versionadded:: 1.9.0
Parameters
----------
fp : filelike object
d : dict
    This has the appropriate entries for writing its string
    representation to the header of the file.
Definition at line 462 of file format.py.
References _write_array_header().
Variable Documentation
__all__
list numpy.lib.format.__all__ = [] private
Definition at line 172 of file format.py.
_header_size_info
dict numpy.lib.format._header_size_info protected
Initial value:
=  {
    (1, 0): ('<H', 'latin1'),
    (2, 0): ('<I', 'latin1'),
    (3, 0): ('<I', 'utf8'),
}
Definition at line 185 of file format.py.
_MAX_HEADER_SIZE
int numpy.lib.format._MAX_HEADER_SIZE = 10000 protected
Definition at line 194 of file format.py.
ARRAY_ALIGN
int numpy.lib.format.ARRAY_ALIGN = 64
Definition at line 178 of file format.py.
BUFFER_SIZE
int numpy.lib.format.BUFFER_SIZE = 2**18
Definition at line 179 of file format.py.
EXPECTED_KEYS
dict numpy.lib.format.EXPECTED_KEYS = {'descr', 'fortran_order', 'shape'}
Definition at line 175 of file format.py.
GROWTH_AXIS_MAX_DIGITS
int numpy.lib.format.GROWTH_AXIS_MAX_DIGITS = 21
Definition at line 181 of file format.py.
MAGIC_LEN
int numpy.lib.format.MAGIC_LEN = len(MAGIC_PREFIX) + 2
Definition at line 177 of file format.py.
MAGIC_PREFIX
str numpy.lib.format.MAGIC_PREFIX = b'\x93NUMPY'
Definition at line 176 of file format.py.