Code Cloning Analysis: kiwisolver.exceptions.DuplicateConstraint Class Reference
kiwisolver.exceptions.DuplicateConstraint Class Reference
Public Member Functions
__init__ (self, constraint)
Public Attributes
constraint = constraint
Static Private Attributes
tuple __slots__ = ("constraint",)
Detailed Description
Definition at line 19 of file exceptions.py.
Constructor & Destructor Documentation
__init__()
kiwisolver.exceptions.DuplicateConstraint.__init__ (self, constraint)
Definition at line 22 of file exceptions.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Data Documentation
__slots__
tuple kiwisolver.exceptions.DuplicateConstraint.__slots__ = ("constraint",) static private
Definition at line 20 of file exceptions.py.
constraint
kiwisolver.exceptions.DuplicateConstraint.constraint = constraint
Definition at line 23 of file exceptions.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/kiwisolver/exceptions.py