Code Cloning Analysis: fontTools.ttLib.tables.otTables.AATStateTable Class Reference
fontTools.ttLib.tables.otTables.AATStateTable Class Reference
Public Member Functions
__init__ (self)
Public Attributes
dict GlyphClasses = {}
list States = []
list PerGlyphLookups = []
Detailed Description
Definition at line 438 of file otTables.py.
Constructor & Destructor Documentation
__init__()
fontTools.ttLib.tables.otTables.AATStateTable.__init__ (self)
Definition at line 439 of file otTables.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Data Documentation
GlyphClasses
dict fontTools.ttLib.tables.otTables.AATStateTable.GlyphClasses = {}
Definition at line 440 of file otTables.py.
PerGlyphLookups
list fontTools.ttLib.tables.otTables.AATStateTable.PerGlyphLookups = []
Definition at line 442 of file otTables.py.
States
list fontTools.ttLib.tables.otTables.AATStateTable.States = []
Definition at line 441 of file otTables.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ttLib/tables/otTables.py