Code Cloning Analysis: dateutil.tz._common Namespace Reference
dateutil.tz._common Namespace Reference
Classes
class _DatetimeWithFold
class _tzinfo
class tzrangebase
Functions
tzname_in_python2 (namefunc)
enfold (dt, fold=1)
_validate_fromutc_inputs (f)
Variables
ZERO = timedelta(0)
list __all__ = ['tzname_in_python2', 'enfold']
Function Documentation
_validate_fromutc_inputs()
dateutil.tz._common._validate_fromutc_inputs (f) protected
The CPython version of ``fromutc`` checks that the input is a ``datetime``
object and that ``self`` is attached as its ``tzinfo``.
Definition at line 132 of file _common.py.
enfold()
dateutil.tz._common.enfold (dt, fold = 1)
Provides a unified interface for assigning the ``fold`` attribute to
datetimes both before and after the implementation of PEP-495.
:param fold:
    The value for the ``fold`` attribute in the returned datetime. This
    should be either 0 or 1.
:return:
    Returns an object for which ``getattr(dt, 'fold', 0)`` returns
    ``fold`` for all versions of Python. In versions prior to
    Python 3.6, this is a ``_DatetimeWithFold`` object, which is a
    subclass of :py:class:`datetime.datetime` with the ``fold``
    attribute added, if ``fold`` is 1.
.. versionadded:: 2.6.0
Definition at line 37 of file _common.py.
Referenced by dateutil.tz._common._tzinfo._fromutc(), dateutil.tz._common._tzinfo.fromutc(), dateutil.tz._common.tzrangebase.fromutc(), and dateutil.tz._common._tzinfo.is_ambiguous().
tzname_in_python2()
dateutil.tz._common.tzname_in_python2 (namefunc)
Change unicode output into bytestrings in Python 2
tzname() API changed in Python 3. It used to return bytes, but was changed
to unicode strings
Definition at line 13 of file _common.py.
Variable Documentation
__all__
list dateutil.tz._common.__all__ = ['tzname_in_python2', 'enfold'] private
Definition at line 10 of file _common.py.
ZERO
dateutil.tz._common.ZERO = timedelta(0)
Definition at line 8 of file _common.py.