Code Cloning Analysis: fontTools.ttLib.tables._c_m_a_p.SubHeader Class Reference
fontTools.ttLib.tables._c_m_a_p.SubHeader Class Reference
Public Member Functions
__init__ (self)
Public Attributes
firstCode = None
entryCount = None
idDelta = None
idRangeOffset = None
list glyphIndexArray = []
Detailed Description
Definition at line 435 of file _c_m_a_p.py.
Constructor & Destructor Documentation
__init__()
fontTools.ttLib.tables._c_m_a_p.SubHeader.__init__ (self)
Definition at line 436 of file _c_m_a_p.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Data Documentation
entryCount
fontTools.ttLib.tables._c_m_a_p.SubHeader.entryCount = None
Definition at line 438 of file _c_m_a_p.py.
firstCode
fontTools.ttLib.tables._c_m_a_p.SubHeader.firstCode = None
Definition at line 437 of file _c_m_a_p.py.
glyphIndexArray
list fontTools.ttLib.tables._c_m_a_p.SubHeader.glyphIndexArray = []
Definition at line 441 of file _c_m_a_p.py.
idDelta
fontTools.ttLib.tables._c_m_a_p.SubHeader.idDelta = None
Definition at line 439 of file _c_m_a_p.py.
idRangeOffset
fontTools.ttLib.tables._c_m_a_p.SubHeader.idRangeOffset = None
Definition at line 440 of file _c_m_a_p.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ttLib/tables/_c_m_a_p.py