Code Cloning Analysis: scipy.stats._covariance.CovViaDiagonal Class Reference
scipy.stats._covariance.CovViaDiagonal Class Reference
Public Member Functions
__init__ (self, diagonal)
Public Member Functions inherited from scipy.stats._covariance.Covariance
__init__ (self)
whiten (self, x)
colorize (self, x)
log_pdet (self)
rank (self)
covariance (self)
shape (self)
Protected Member Functions
_whiten (self, x)
_colorize (self, x)
_support_mask (self, x)
Protected Member Functions inherited from scipy.stats._covariance.Covariance
_validate_matrix (self, A, name)
_validate_vector (self, A, name)
Protected Attributes
_sqrt_diagonal = np.sqrt(diagonal)
_LP = psuedo_reciprocals
_covariance = np.apply_along_axis(np.diag, -1, diagonal)
_i_zero = i_zero
_shape = self._covariance.shape
bool _allow_singular = True
Protected Attributes inherited from scipy.stats._covariance.Covariance
_log_pdet
_rank
Additional Inherited Members
Static Public Member Functions inherited from scipy.stats._covariance.Covariance
from_diagonal (diagonal)
from_precision (precision, covariance=None)
from_cholesky (cholesky)
from_eigendecomposition (eigendecomposition)
Detailed Description
Definition at line 501 of file _covariance.py.
Constructor & Destructor Documentation
__init__()
scipy.stats._covariance.CovViaDiagonal.__init__ (self, diagonal)
Definition at line 503 of file _covariance.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
_colorize()
scipy.stats._covariance.CovViaDiagonal._colorize (self, x) protected
Definition at line 526 of file _covariance.py.
Referenced by scipy.stats._covariance.Covariance.colorize().
_support_mask()
scipy.stats._covariance.CovViaDiagonal._support_mask (self, x) protected
Check whether x lies in the support of the distribution.
Definition at line 529 of file _covariance.py.
References _i_zero.
Referenced by scipy.stats._distn_infrastructure.rv_continuous._nnlf_and_penalty(), scipy.stats._distn_infrastructure.rv_continuous.logpdf(), scipy.stats._distn_infrastructure.rv_generic.nnlf(), and scipy.stats._distn_infrastructure.rv_continuous.pdf().
_whiten()
scipy.stats._covariance.CovViaDiagonal._whiten (self, x) protected
Definition at line 523 of file _covariance.py.
Referenced by scipy.stats._covariance.Covariance.whiten().
Member Data Documentation
_allow_singular
bool scipy.stats._covariance.CovViaDiagonal._allow_singular = True protected
Definition at line 521 of file _covariance.py.
_covariance
scipy.stats._covariance.CovViaDiagonal._covariance = np.apply_along_axis(np.diag, -1, diagonal) protected
Definition at line 518 of file _covariance.py.
Referenced by scipy.stats._covariance.Covariance.covariance().
_i_zero
scipy.stats._covariance.CovViaDiagonal._i_zero = i_zero protected
Definition at line 519 of file _covariance.py.
Referenced by _support_mask().
_LP
scipy.stats._covariance.CovViaDiagonal._LP = psuedo_reciprocals protected
Definition at line 516 of file _covariance.py.
_shape
scipy.stats._covariance.CovViaDiagonal._shape = self._covariance.shape protected
Definition at line 520 of file _covariance.py.
Referenced by pandas.util._doctools.TablePlotter._get_cells(), scipy.sparse._matrix.spmatrix.get_shape(), pandas.util._doctools.TablePlotter.plot(), and scipy.stats._covariance.Covariance.shape().
_sqrt_diagonal
scipy.stats._covariance.CovViaDiagonal._sqrt_diagonal = np.sqrt(diagonal) protected
Definition at line 515 of file _covariance.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/stats/_covariance.py