Code Cloning Analysis: PIL.ImageMorph.MorphOp Class Reference
PIL.ImageMorph.MorphOp Class Reference
Public Member Functions
None __init__ (self, bytearray|None lut=None, str|None op_name=None, list[str]|None patterns=None)
tuple[int, Image.Image] apply (self, Image.Image image)
list[tuple[int, int]] match (self, Image.Image image)
list[tuple[int, int]] get_on_pixels (self, Image.Image image)
None load_lut (self, str filename)
None save_lut (self, str filename)
None set_lut (self, bytearray|None lut)
Public Attributes
lut = lut
Detailed Description
A class for binary morphological operators
Definition at line 187 of file ImageMorph.py.
Constructor & Destructor Documentation
__init__()
None PIL.ImageMorph.MorphOp.__init__ (self, bytearray | None lut = None, str | None op_name = None, list[str] | None patterns = None)
Create a binary morphological operator
Definition at line 190 of file ImageMorph.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
apply()
tuple[int, Image.Image] PIL.ImageMorph.MorphOp.apply (self, Image.Image image)
Run a single morphological operation on an image
Returns a tuple of the number of changed pixels and the
morphed image
Definition at line 203 of file ImageMorph.py.
Referenced by pandas.core.window.rolling.BaseWindow._apply(), pandas.core.generic.NDFrame.backfill(), sklearn.ensemble._forest.RandomTreesEmbedding.fit_transform(), PIL.ImageCms.Flags.GRIDPOINTS(), and sklearn.ensemble._forest.RandomTreesEmbedding.transform().
get_on_pixels()
list[tuple[int, int]] PIL.ImageMorph.MorphOp.get_on_pixels (self, Image.Image image)
Get a list of all turned on pixels in a binary image
Returns a list of tuples of (x,y) coordinates
of all matching pixels. See :ref:`coordinate-system`.
Definition at line 234 of file ImageMorph.py.
load_lut()
None PIL.ImageMorph.MorphOp.load_lut (self, str filename)
Load an operator from an mrl file
Definition at line 245 of file ImageMorph.py.
match()
list[tuple[int, int]] PIL.ImageMorph.MorphOp.match (self, Image.Image image)
Get a list of coordinates matching the morphological operation on
an image.
Returns a list of tuples of (x,y) coordinates
of all matching pixels. See :ref:`coordinate-system`.
Definition at line 219 of file ImageMorph.py.
save_lut()
None PIL.ImageMorph.MorphOp.save_lut (self, str filename)
Save an operator to an mrl file
Definition at line 255 of file ImageMorph.py.
set_lut()
None PIL.ImageMorph.MorphOp.set_lut (self, bytearray | None lut)
Set the lut from an external source
Definition at line 263 of file ImageMorph.py.
Member Data Documentation
lut
PIL.ImageMorph.MorphOp.lut = lut
Definition at line 197 of file ImageMorph.py.
Referenced by matplotlib.colors.BivarColormap._repr_png_().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/PIL/ImageMorph.py