Code Cloning Analysis: fontTools.misc.psCharStrings.SimpleT2Decompiler Class Reference
fontTools.misc.psCharStrings.SimpleT2Decompiler Class Reference
Public Member Functions
__init__ (self, localSubrs, globalSubrs, private=None, blender=None)
reset (self)
execute (self, charString)
pop (self)
popall (self)
push (self, value)
op_return (self, index)
op_endchar (self, index)
op_ignore (self, index)
op_callsubr (self, index)
op_callgsubr (self, index)
op_hstem (self, index)
op_vstem (self, index)
op_hstemhm (self, index)
op_vstemhm (self, index)
op_hintmask (self, index)
countHints (self)
op_and (self, index)
op_or (self, index)
op_not (self, index)
op_store (self, index)
op_abs (self, index)
op_add (self, index)
op_sub (self, index)
op_div (self, index)
op_load (self, index)
op_neg (self, index)
op_eq (self, index)
op_drop (self, index)
op_put (self, index)
op_get (self, index)
op_ifelse (self, index)
op_random (self, index)
op_mul (self, index)
op_sqrt (self, index)
op_dup (self, index)
op_exch (self, index)
op_index (self, index)
op_roll (self, index)
op_blend (self, index)
op_vsindex (self, index)
Public Attributes
localSubrs = localSubrs
localBias = calcSubrBias(localSubrs)
globalSubrs = globalSubrs
globalBias = calcSubrBias(globalSubrs)
private = private
blender = blender
list callingStack = []
list operandStack = []
int hintCount = 0
int hintMaskBytes = 0
int numRegions = 0
int vsIndex = 0
Static Public Attributes
op_cntrmask = op_hintmask
Detailed Description
Definition at line 323 of file psCharStrings.py.
Constructor & Destructor Documentation
__init__()
fontTools.misc.psCharStrings.SimpleT2Decompiler.__init__ (self, localSubrs, globalSubrs, private = None, blender = None)
Definition at line 324 of file psCharStrings.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
countHints()
fontTools.misc.psCharStrings.SimpleT2Decompiler.countHints (self)
Definition at line 426 of file psCharStrings.py.
execute()
fontTools.misc.psCharStrings.SimpleT2Decompiler.execute (self, charString)
Definition at line 341 of file psCharStrings.py.
Referenced by pandas.io.sql.SQLiteDatabase._query_iterator(), pandas.io.sql.SQLDatabase.read_query(), and pandas.io.sql.SQLiteDatabase.to_sql().
op_abs()
fontTools.misc.psCharStrings.SimpleT2Decompiler.op_abs (self, index)
Definition at line 443 of file psCharStrings.py.
op_add()
fontTools.misc.psCharStrings.SimpleT2Decompiler.op_add (self, index)
Definition at line 446 of file psCharStrings.py.
op_and()
fontTools.misc.psCharStrings.SimpleT2Decompiler.op_and (self, index)
Definition at line 431 of file psCharStrings.py.
op_blend()
fontTools.misc.psCharStrings.SimpleT2Decompiler.op_blend (self, index)
Definition at line 497 of file psCharStrings.py.
op_callgsubr()
fontTools.misc.psCharStrings.SimpleT2Decompiler.op_callgsubr (self, index)
Definition at line 400 of file psCharStrings.py.
op_callsubr()
fontTools.misc.psCharStrings.SimpleT2Decompiler.op_callsubr (self, index)
Definition at line 395 of file psCharStrings.py.
op_div()
fontTools.misc.psCharStrings.SimpleT2Decompiler.op_div (self, index)
Definition at line 452 of file psCharStrings.py.
op_drop()
fontTools.misc.psCharStrings.SimpleT2Decompiler.op_drop (self, index)
Definition at line 464 of file psCharStrings.py.
op_dup()
fontTools.misc.psCharStrings.SimpleT2Decompiler.op_dup (self, index)
Definition at line 485 of file psCharStrings.py.
op_endchar()
fontTools.misc.psCharStrings.SimpleT2Decompiler.op_endchar (self, index)
Definition at line 389 of file psCharStrings.py.
op_eq()
fontTools.misc.psCharStrings.SimpleT2Decompiler.op_eq (self, index)
Definition at line 461 of file psCharStrings.py.
op_exch()
fontTools.misc.psCharStrings.SimpleT2Decompiler.op_exch (self, index)
Definition at line 488 of file psCharStrings.py.
op_get()
fontTools.misc.psCharStrings.SimpleT2Decompiler.op_get (self, index)
Definition at line 470 of file psCharStrings.py.
op_hintmask()
fontTools.misc.psCharStrings.SimpleT2Decompiler.op_hintmask (self, index)
Definition at line 417 of file psCharStrings.py.
op_hstem()
fontTools.misc.psCharStrings.SimpleT2Decompiler.op_hstem (self, index)
Definition at line 405 of file psCharStrings.py.
op_hstemhm()
fontTools.misc.psCharStrings.SimpleT2Decompiler.op_hstemhm (self, index)
Definition at line 411 of file psCharStrings.py.
op_ifelse()
fontTools.misc.psCharStrings.SimpleT2Decompiler.op_ifelse (self, index)
Definition at line 473 of file psCharStrings.py.
op_ignore()
fontTools.misc.psCharStrings.SimpleT2Decompiler.op_ignore (self, index)
Definition at line 392 of file psCharStrings.py.
op_index()
fontTools.misc.psCharStrings.SimpleT2Decompiler.op_index (self, index)
Definition at line 491 of file psCharStrings.py.
op_load()
fontTools.misc.psCharStrings.SimpleT2Decompiler.op_load (self, index)
Definition at line 455 of file psCharStrings.py.
op_mul()
fontTools.misc.psCharStrings.SimpleT2Decompiler.op_mul (self, index)
Definition at line 479 of file psCharStrings.py.
op_neg()
fontTools.misc.psCharStrings.SimpleT2Decompiler.op_neg (self, index)
Definition at line 458 of file psCharStrings.py.
op_not()
fontTools.misc.psCharStrings.SimpleT2Decompiler.op_not (self, index)
Definition at line 437 of file psCharStrings.py.
op_or()
fontTools.misc.psCharStrings.SimpleT2Decompiler.op_or (self, index)
Definition at line 434 of file psCharStrings.py.
op_put()
fontTools.misc.psCharStrings.SimpleT2Decompiler.op_put (self, index)
Definition at line 467 of file psCharStrings.py.
op_random()
fontTools.misc.psCharStrings.SimpleT2Decompiler.op_random (self, index)
Definition at line 476 of file psCharStrings.py.
op_return()
fontTools.misc.psCharStrings.SimpleT2Decompiler.op_return (self, index)
Definition at line 385 of file psCharStrings.py.
op_roll()
fontTools.misc.psCharStrings.SimpleT2Decompiler.op_roll (self, index)
Definition at line 494 of file psCharStrings.py.
op_sqrt()
fontTools.misc.psCharStrings.SimpleT2Decompiler.op_sqrt (self, index)
Definition at line 482 of file psCharStrings.py.
op_store()
fontTools.misc.psCharStrings.SimpleT2Decompiler.op_store (self, index)
Definition at line 440 of file psCharStrings.py.
op_sub()
fontTools.misc.psCharStrings.SimpleT2Decompiler.op_sub (self, index)
Definition at line 449 of file psCharStrings.py.
op_vsindex()
fontTools.misc.psCharStrings.SimpleT2Decompiler.op_vsindex (self, index)
Definition at line 518 of file psCharStrings.py.
op_vstem()
fontTools.misc.psCharStrings.SimpleT2Decompiler.op_vstem (self, index)
Definition at line 408 of file psCharStrings.py.
op_vstemhm()
fontTools.misc.psCharStrings.SimpleT2Decompiler.op_vstemhm (self, index)
Definition at line 414 of file psCharStrings.py.
pop()
fontTools.misc.psCharStrings.SimpleT2Decompiler.pop (self)
Definition at line 372 of file psCharStrings.py.
Referenced by fontTools.misc.psCharStrings.DictDecompiler.arg_blendList(), matplotlib.backends.backend_pdf.GraphicsContextPdf.clip_cmd(), matplotlib.backends.backend_pdf.GraphicsContextPdf.finalize(), and fontTools.misc.psCharStrings.T2OutlineExtractor.op_hvcurveto().
popall()
fontTools.misc.psCharStrings.SimpleT2Decompiler.popall (self)
Definition at line 377 of file psCharStrings.py.
Referenced by fontTools.misc.psCharStrings.DictDecompiler.arg_blendList(), fontTools.misc.psCharStrings.T2OutlineExtractor.op_hhcurveto(), fontTools.misc.psCharStrings.T2OutlineExtractor.op_hvcurveto(), fontTools.misc.psCharStrings.T2OutlineExtractor.op_rcurveline(), fontTools.misc.psCharStrings.T2OutlineExtractor.op_rlinecurve(), fontTools.misc.psCharStrings.T2OutlineExtractor.op_rrcurveto(), and fontTools.misc.psCharStrings.T2OutlineExtractor.op_vhcurveto().
push()
fontTools.misc.psCharStrings.SimpleT2Decompiler.push (self, value)
Definition at line 382 of file psCharStrings.py.
Referenced by matplotlib.backends.backend_pdf.GraphicsContextPdf.clip_cmd(), matplotlib.cbook._Stack.home(), and fontTools.misc.psCharStrings.T2OutlineExtractor.op_hvcurveto().
reset()
fontTools.misc.psCharStrings.SimpleT2Decompiler.reset (self)
Definition at line 333 of file psCharStrings.py.
Referenced by PIL.TiffImagePlugin.ImageFileDirectory_v2.__init__(), scipy._lib._docscrape.Reader.__init__(), and PIL.TiffImagePlugin.ImageFileDirectory_v2.named().
Member Data Documentation
blender
fontTools.misc.psCharStrings.SimpleT2Decompiler.blender = blender
Definition at line 330 of file psCharStrings.py.
callingStack
list fontTools.misc.psCharStrings.SimpleT2Decompiler.callingStack = []
Definition at line 334 of file psCharStrings.py.
globalBias
fontTools.misc.psCharStrings.SimpleT2Decompiler.globalBias = calcSubrBias(globalSubrs)
Definition at line 328 of file psCharStrings.py.
globalSubrs
fontTools.misc.psCharStrings.SimpleT2Decompiler.globalSubrs = globalSubrs
Definition at line 327 of file psCharStrings.py.
hintCount
int fontTools.misc.psCharStrings.SimpleT2Decompiler.hintCount = 0
Definition at line 336 of file psCharStrings.py.
hintMaskBytes
int fontTools.misc.psCharStrings.SimpleT2Decompiler.hintMaskBytes = 0
Definition at line 337 of file psCharStrings.py.
localBias
fontTools.misc.psCharStrings.SimpleT2Decompiler.localBias = calcSubrBias(localSubrs)
Definition at line 326 of file psCharStrings.py.
localSubrs
fontTools.misc.psCharStrings.SimpleT2Decompiler.localSubrs = localSubrs
Definition at line 325 of file psCharStrings.py.
numRegions
int fontTools.misc.psCharStrings.SimpleT2Decompiler.numRegions = 0
Definition at line 338 of file psCharStrings.py.
op_cntrmask
fontTools.misc.psCharStrings.SimpleT2Decompiler.op_cntrmask = op_hintmask static
Definition at line 424 of file psCharStrings.py.
operandStack
list fontTools.misc.psCharStrings.SimpleT2Decompiler.operandStack = []
Definition at line 335 of file psCharStrings.py.
private
fontTools.misc.psCharStrings.SimpleT2Decompiler.private = private
Definition at line 329 of file psCharStrings.py.
Referenced by pip._vendor.rich._inspect.Inspect._render().
vsIndex
int fontTools.misc.psCharStrings.SimpleT2Decompiler.vsIndex = 0
Definition at line 339 of file psCharStrings.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/misc/psCharStrings.py