Code Cloning Analysis: fontTools.otlLib.builder Namespace Reference
fontTools.otlLib.builder Namespace Reference
Classes
class AlternateSubstBuilder
class AnySubstBuilder
class ChainContextPosBuilder
class ChainContextSubstBuilder
class ChainContextualBuilder
class ChainContextualRule
class ChainContextualRuleset
class ClassDefBuilder
class ClassPairPosSubtableBuilder
class CursivePosBuilder
class LigatureSubstBuilder
class LookupBuilder
class MarkBasePosBuilder
class MarkLigPosBuilder
class MarkMarkPosBuilder
class MultipleSubstBuilder
class PairPosBuilder
class ReverseChainSingleSubstBuilder
class SinglePosBuilder
class SingleSubstBuilder
Functions
buildCoverage (glyphs, glyphMap)
buildLookup (subtables, flags=0, markFilterSet=None, table=None, extension=False)
buildSingleSubstSubtable (mapping)
buildMultipleSubstSubtable (mapping)
buildAlternateSubstSubtable (mapping)
buildLigatureSubstSubtable (mapping)
buildAnchor (x, y, point=None, deviceX=None, deviceY=None)
buildBaseArray (bases, numMarkClasses, glyphMap)
buildBaseRecord (anchors)
buildComponentRecord (anchors)
buildCursivePosSubtable (attach, glyphMap)
buildDevice (deltas)
buildLigatureArray (ligs, numMarkClasses, glyphMap)
buildLigatureAttach (components)
buildMarkArray (marks, glyphMap)
buildMarkBasePos (marks, bases, glyphMap)
buildMarkBasePosSubtable (marks, bases, glyphMap)
buildMarkLigPos (marks, ligs, glyphMap)
buildMarkLigPosSubtable (marks, ligs, glyphMap)
buildMarkRecord (classID, anchor)
buildMark2Record (anchors)
_getValueFormat (f, values, i)
buildPairPosClassesSubtable (pairs, glyphMap, valueFormat1=None, valueFormat2=None)
buildPairPosGlyphs (pairs, glyphMap)
buildPairPosGlyphsSubtable (pairs, glyphMap, valueFormat1=None, valueFormat2=None)
buildSinglePos (mapping, glyphMap)
buildSinglePosSubtable (values, glyphMap)
_getSinglePosTableKey (subtable, glyphMap)
_getSinglePosValueKey (valueRecord)
_makeDeviceTuple (device)
_getSinglePosValueSize (valueKey)
buildValue (value)
buildAttachList (attachPoints, glyphMap)
buildAttachPoint (points)
buildCaretValueForCoord (coord)
buildCaretValueForPoint (point)
buildLigCaretList (coords, points, glyphMap)
buildLigGlyph (coords, points)
buildMarkGlyphSetsDef (markSets, glyphMap)
None buildStatTable (TTFont ttFont, axes, locations=None, Union[STATName, STATNameStatement] elidedFallbackName=2, bool windowsNames=True, bool macNames=True)
_buildAxisRecords (axes, ttFont, windowsNames=True, macNames=True)
_buildAxisValuesFormat4 (locations, axes, ttFont, windowsNames=True, macNames=True)
int _addName (TTFont ttFont, Union[STATName, STATNameStatement] value, int minNameID=0, bool windows=True, bool mac=True)
buildMathTable (ttFont, constants=None, italicsCorrections=None, topAccentAttachments=None, extendedShapes=None, mathKerns=None, minConnectorOverlap=0, vertGlyphVariants=None, horizGlyphVariants=None, vertGlyphAssembly=None, horizGlyphAssembly=None)
_buildMathConstants (constants)
_buildMathGlyphInfo (glyphMap, italicsCorrections, topAccentAttachments, extendedShapes, mathKerns)
_buildMathVariants (glyphMap, minConnectorOverlap, vertGlyphVariants, horizGlyphVariants, vertGlyphAssembly, horizGlyphAssembly)
_buildMathGlyphConstruction (glyphMap, variants, assemblies)
_mathValueRecord (value)
Variables
log = logging.getLogger(__name__)
int LOOKUP_FLAG_RIGHT_TO_LEFT = 0x0001
int LOOKUP_FLAG_IGNORE_BASE_GLYPHS = 0x0002
int LOOKUP_FLAG_IGNORE_LIGATURES = 0x0004
int LOOKUP_FLAG_IGNORE_MARKS = 0x0008
int LOOKUP_FLAG_USE_MARK_FILTERING_SET = 0x0010
_DeviceTuple = namedtuple("_DeviceTuple", "DeltaFormat StartSize EndSize DeltaValue")
AXIS_VALUE_NEGATIVE_INFINITY = fixedToFloat(-0x80000000, 16)
AXIS_VALUE_POSITIVE_INFINITY = fixedToFloat(0x7FFFFFFF, 16)
STATName = Union[int, str, Dict[str, str]]
glyphs = sorted(set(glyphs), key=glyphMap.__getitem__)
LookupType = lookupType
LookupFlag = flags
SubTable = subtables
SubTableCount = len(self.SubTable)
MarkFilteringSet = markFilterSet
mapping = dict(mapping)
alternates = dict(mapping)
dict ligatures = {}
XCoordinate
YCoordinate = x, y
int Format = 1
AnchorPoint = point
XDeviceTable = deviceX
YDeviceTable = deviceY
list BaseRecord = []
BaseCount = len(self.BaseRecord)
BaseAnchor = anchors
LigatureAnchor = anchors
list Coverage = buildCoverage(attach.keys(), glyphMap)
list EntryExitRecord = []
EntryExitCount = len(self.EntryExitRecord)
StartSize = min(keys)
EndSize = max(keys)
list DeltaValue
int DeltaFormat = 1
list LigatureAttach = []
LigatureCount = len(self.LigatureAttach)
list ComponentRecord = [buildComponentRecord(c) for c in components]
ComponentCount = len(self.ComponentRecord)
list MarkRecord = []
MarkCount = len(self.MarkRecord)
MarkCoverage = buildCoverage(marks, glyphMap)
MarkArray = buildMarkArray(marks, glyphMap)
int ClassCount = max([mc for mc, _ in marks.values()]) + 1
BaseCoverage = buildCoverage(bases, glyphMap)
BaseArray = buildBaseArray(bases, self.ClassCount, glyphMap)
LigatureCoverage = buildCoverage(ligs, glyphMap)
LigatureArray = buildLigatureArray(ligs, self.ClassCount, glyphMap)
Class = classID
MarkAnchor = anchor
Mark2Anchor = anchors
ClassDef1 = classDef1.build()
ClassDef2 = classDef2.build()
list Class1Record = []
Class1Count = len(self.Class1Record)
Class2Count = len(classes2)
list PairSet = []
PairSetCount = len(self.PairSet)
Value = valueRecords[0]
ValueCount = len(self.Value)
list AttachPoint = [buildAttachPoint(attachPoints[g]) for g in self.Coverage.glyphs]
GlyphCount = len(self.AttachPoint)
PointIndex = sorted(set(points))
PointCount = len(self.PointIndex)
Coordinate = 3
DeviceTable = coord
CaretValuePoint = point
list LigGlyph = [carets[g] for g in self.Coverage.glyphs]
LigGlyphCount = len(self.LigGlyph)
CaretValue = carets
CaretCount = len(self.CaretValue)
int MarkSetTableFormat = 1
MarkSetCount = len(self.Coverage)
Function Documentation
_addName()
int fontTools.otlLib.builder._addName (TTFont ttFont, Union[STATName, STATNameStatement] value, int minNameID = 0, bool windows = True, bool mac = True) protected
Definition at line 3141 of file builder.py.
_buildAxisRecords()
fontTools.otlLib.builder._buildAxisRecords (axes, ttFont, windowsNames = True, macNames = True) protected
Definition at line 3072 of file builder.py.
_buildAxisValuesFormat4()
fontTools.otlLib.builder._buildAxisValuesFormat4 (locations, axes, ttFont, windowsNames = True, macNames = True) protected
Definition at line 3115 of file builder.py.
_buildMathConstants()
fontTools.otlLib.builder._buildMathConstants (constants) protected
Definition at line 3308 of file builder.py.
_buildMathGlyphConstruction()
fontTools.otlLib.builder._buildMathGlyphConstruction (glyphMap, variants, assemblies) protected
Definition at line 3419 of file builder.py.
_buildMathGlyphInfo()
fontTools.otlLib.builder._buildMathGlyphInfo (glyphMap, italicsCorrections, topAccentAttachments, extendedShapes, mathKerns) protected
Definition at line 3322 of file builder.py.
_buildMathVariants()
fontTools.otlLib.builder._buildMathVariants (glyphMap, minConnectorOverlap, vertGlyphVariants, horizGlyphVariants, vertGlyphAssembly, horizGlyphAssembly) protected
Definition at line 3380 of file builder.py.
_getSinglePosTableKey()
fontTools.otlLib.builder._getSinglePosTableKey (subtable, glyphMap) protected
Definition at line 2645 of file builder.py.
_getSinglePosValueKey()
fontTools.otlLib.builder._getSinglePosValueKey (valueRecord) protected
Definition at line 2651 of file builder.py.
_getSinglePosValueSize()
fontTools.otlLib.builder._getSinglePosValueSize (valueKey) protected
Definition at line 2679 of file builder.py.
_getValueFormat()
fontTools.otlLib.builder._getValueFormat (f, values, i) protected
Definition at line 2313 of file builder.py.
_makeDeviceTuple()
fontTools.otlLib.builder._makeDeviceTuple (device) protected
Definition at line 2669 of file builder.py.
_mathValueRecord()
fontTools.otlLib.builder._mathValueRecord (value) protected
Definition at line 3462 of file builder.py.
buildAlternateSubstSubtable()
fontTools.otlLib.builder.buildAlternateSubstSubtable (mapping)
Builds an alternate substitution (GSUB3) subtable.
Note that if you are implementing a layout compiler, you may find it more
flexible to use
:py:class:`fontTools.otlLib.lookupBuilders.AlternateSubstBuilder` instead.
Args:
    mapping: A dictionary mapping input glyph names to a list of output
        glyph names.
Returns:
    An ``otTables.AlternateSubst`` object or ``None`` if the mapping dictionary
    is empty.
Definition at line 1854 of file builder.py.
buildAnchor()
fontTools.otlLib.builder.buildAnchor (x, y, point = None, deviceX = None, deviceY = None)
Builds an Anchor table.
This determines the appropriate anchor format based on the passed parameters.
Args:
    x (int): X coordinate.
    y (int): Y coordinate.
    point (int): Index of glyph contour point, if provided.
    deviceX (``otTables.Device``): X coordinate device table, if provided.
    deviceY (``otTables.Device``): Y coordinate device table, if provided.
Returns:
    An ``otTables.Anchor`` object.
Definition at line 1922 of file builder.py.
buildAttachList()
fontTools.otlLib.builder.buildAttachList (attachPoints, glyphMap)
Builds an AttachList subtable.
A GDEF table may contain an Attachment Point List table (AttachList)
which stores the contour indices of attachment points for glyphs with
attachment points. This routine builds AttachList subtables.
Args:
    attachPoints (dict): A mapping between glyph names and a list of
        contour indices.
Returns:
    An ``otTables.AttachList`` object if attachment points are supplied,
        or ``None`` otherwise.
Definition at line 2721 of file builder.py.
References buildCoverage().
buildAttachPoint()
fontTools.otlLib.builder.buildAttachPoint (points)
Definition at line 2745 of file builder.py.
buildBaseArray()
fontTools.otlLib.builder.buildBaseArray (bases, numMarkClasses, glyphMap)
Builds a base array record.
As part of building mark-to-base positioning rules, you will need to define
a ``BaseArray`` record, which "defines for each base glyph an array of
anchors, one for each mark class." This function builds the base array
subtable.
Example::
    bases = {"a": {0: a3, 1: a5}, "b": {0: a4, 1: a5}}
    basearray = buildBaseArray(bases, 2, font.getReverseGlyphMap())
Args:
    bases (dict): A dictionary mapping anchors to glyphs; the keys being
        glyph names, and the values being dictionaries mapping mark class ID
        to the appropriate ``otTables.Anchor`` object used for attaching marks
        of that class.
    numMarkClasses (int): The total number of mark classes for which anchors
        are defined.
    glyphMap: a glyph name to ID map, typically returned from
        ``font.getReverseGlyphMap()``.
Returns:
    An ``otTables.BaseArray`` object.
Definition at line 1953 of file builder.py.
Referenced by buildMarkBasePosSubtable().
buildBaseRecord()
fontTools.otlLib.builder.buildBaseRecord (anchors)
Definition at line 1989 of file builder.py.
buildCaretValueForCoord()
fontTools.otlLib.builder.buildCaretValueForCoord (coord)
Definition at line 2756 of file builder.py.
buildCaretValueForPoint()
fontTools.otlLib.builder.buildCaretValueForPoint (point)
Definition at line 2769 of file builder.py.
buildComponentRecord()
fontTools.otlLib.builder.buildComponentRecord (anchors)
Builds a component record.
As part of building mark-to-ligature positioning rules, you will need to
define ``ComponentRecord`` objects, which contain "an array of offsets...
to the Anchor tables that define all the attachment points used to attach
marks to the component." This function builds the component record.
Args:
    anchors: A list of ``otTables.Anchor`` objects or ``None``.
Returns:
    A ``otTables.ComponentRecord`` object or ``None`` if no anchors are
    supplied.
Definition at line 1996 of file builder.py.
Referenced by buildLigatureArray().
buildCoverage()
fontTools.otlLib.builder.buildCoverage (glyphs, glyphMap)
Builds a coverage table.
Coverage tables (as defined in the `OpenType spec <https://docs.microsoft.com/en-gb/typography/opentype/spec/chapter2#coverage-table>`__)
are used in all OpenType Layout lookups apart from the Extension type, and
define the glyphs involved in a layout subtable. This allows shaping engines
to compare the glyph stream with the coverage table and quickly determine
whether a subtable should be involved in a shaping operation.
This function takes a list of glyphs and a glyphname-to-ID map, and
returns a ``Coverage`` object representing the coverage table.
Example::
    glyphMap = font.getReverseGlyphMap()
    glyphs = [ "A", "B", "C" ]
    coverage = buildCoverage(glyphs, glyphMap)
Args:
    glyphs: a sequence of glyph names.
    glyphMap: a glyph name to ID map, typically returned from
        ``font.getReverseGlyphMap()``.
Returns:
    An ``otTables.Coverage`` object or ``None`` if there are no glyphs
    supplied.
Definition at line 32 of file builder.py.
Referenced by fontTools.otlLib.builder.ChainContextualBuilder.build(), fontTools.otlLib.builder.MarkMarkPosBuilder.build(), fontTools.otlLib.builder.ReverseChainSingleSubstBuilder.build(), buildAttachList(), buildCursivePosSubtable(), buildLigCaretList(), buildMarkBasePosSubtable(), fontTools.otlLib.builder.LookupBuilder.buildMarkClasses_(), buildMarkGlyphSetsDef(), buildMarkLigPosSubtable(), buildMathTable(), buildPairPosClassesSubtable(), buildPairPosGlyphsSubtable(), and buildSinglePosSubtable().
buildCursivePosSubtable()
fontTools.otlLib.builder.buildCursivePosSubtable (attach, glyphMap)
Builds a cursive positioning (GPOS3) subtable.
Cursive positioning lookups are made up of a coverage table of glyphs,
and a set of ``EntryExitRecord`` records containing the anchors for
each glyph. This function builds the cursive positioning subtable.
Example::
    subtable = buildCursivePosSubtable({
        "AlifIni": (None, buildAnchor(0, 50)),
        "BehMed": (buildAnchor(500,250), buildAnchor(0,50)),
        # ...
    }, font.getReverseGlyphMap())
Args:
    attach (dict): A mapping between glyph names and a tuple of two
        ``otTables.Anchor`` objects representing entry and exit anchors.
    glyphMap: a glyph name to ID map, typically returned from
        ``font.getReverseGlyphMap()``.
Returns:
    An ``otTables.CursivePos`` object, or ``None`` if the attachment
    dictionary was empty.
Definition at line 2018 of file builder.py.
References buildCoverage().
Referenced by fontTools.otlLib.builder.CursivePosBuilder.build().
buildDevice()
fontTools.otlLib.builder.buildDevice (deltas)
Builds a Device record as part of a ValueRecord or Anchor.
Device tables specify size-specific adjustments to value records
and anchors to reflect changes based on the resolution of the output.
For example, one could specify that an anchor's Y position should be
increased by 1 pixel when displayed at 8 pixels per em. This routine
builds device records.
Args:
    deltas: A dictionary mapping pixels-per-em sizes to the delta
        adjustment in pixels when the font is displayed at that size.
Returns:
    An ``otTables.Device`` object if any deltas were supplied, or
    ``None`` otherwise.
Definition at line 2059 of file builder.py.
buildLigatureArray()
fontTools.otlLib.builder.buildLigatureArray (ligs, numMarkClasses, glyphMap)
Builds a LigatureArray subtable.
As part of building a mark-to-ligature lookup, you will need to define
the set of anchors (for each mark class) on each component of the ligature
where marks can be attached. For example, for an Arabic divine name ligature
(lam lam heh), you may want to specify mark attachment positioning for
superior marks (fatha, etc.) and inferior marks (kasra, etc.) on each glyph
of the ligature. This routine builds the ligature array record.
Example::
    buildLigatureArray({
        "lam-lam-heh": [
            { 0: superiorAnchor1, 1: inferiorAnchor1 }, # attach points for lam1
            { 0: superiorAnchor2, 1: inferiorAnchor2 }, # attach points for lam2
            { 0: superiorAnchor3, 1: inferiorAnchor3 }, # attach points for heh
        ]
    }, 2, font.getReverseGlyphMap())
Args:
    ligs (dict): A mapping of ligature names to an array of dictionaries:
        for each component glyph in the ligature, an dictionary mapping
        mark class IDs to anchors.
    numMarkClasses (int): The number of mark classes.
    glyphMap: a glyph name to ID map, typically returned from
        ``font.getReverseGlyphMap()``.
Returns:
    An ``otTables.LigatureArray`` object if deltas were supplied.
Definition at line 2098 of file builder.py.
References buildComponentRecord().
Referenced by buildMarkLigPosSubtable().
buildLigatureAttach()
fontTools.otlLib.builder.buildLigatureAttach (components)
Definition at line 2140 of file builder.py.
buildLigatureSubstSubtable()
fontTools.otlLib.builder.buildLigatureSubstSubtable (mapping)
Builds a ligature substitution (GSUB4) subtable.
Note that if you are implementing a layout compiler, you may find it more
flexible to use
:py:class:`fontTools.otlLib.lookupBuilders.LigatureSubstBuilder` instead.
Example::
    # sub f f i by f_f_i;
    # sub f i by f_i;
    subtable = buildLigatureSubstSubtable({
        ("f", "f", "i"): "f_f_i",
        ("f", "i"): "f_i",
    })
Args:
    mapping: A dictionary mapping tuples of glyph names to output
        glyph names.
Returns:
    An ``otTables.LigatureSubst`` object or ``None`` if the mapping dictionary
    is empty.
Definition at line 1876 of file builder.py.
buildLigCaretList()
fontTools.otlLib.builder.buildLigCaretList (coords, points, glyphMap)
Builds a ligature caret list table.
Ligatures appear as a single glyph representing multiple characters; however
when, for example, editing text containing a ``f_i`` ligature, the user may
want to place the cursor between the ``f`` and the ``i``. The ligature caret
list in the GDEF table specifies the position to display the "caret" (the
character insertion indicator, typically a flashing vertical bar) "inside"
the ligature to represent an insertion point. The insertion positions may
be specified either by coordinate or by contour point.
Example::
    coords = {
        "f_f_i": [300, 600] # f|fi cursor at 300 units, ff|i cursor at 600.
    }
    points = {
        "c_t": [28] # c|t cursor appears at coordinate of contour point 28.
    }
    ligcaretlist = buildLigCaretList(coords, points, font.getReverseGlyphMap())
Args:
    coords: A mapping between glyph names and a list of coordinates for
        the insertion point of each ligature component after the first one.
    points: A mapping between glyph names and a list of contour points for
        the insertion point of each ligature component after the first one.
    glyphMap: a glyph name to ID map, typically returned from
        ``font.getReverseGlyphMap()``.
Returns:
    A ``otTables.LigCaretList`` object if any carets are present, or
        ``None`` otherwise.
Definition at line 2777 of file builder.py.
References buildCoverage().
buildLigGlyph()
fontTools.otlLib.builder.buildLigGlyph (coords, points)
Definition at line 2823 of file builder.py.
buildLookup()
fontTools.otlLib.builder.buildLookup (subtables, flags = 0, markFilterSet = None, table = None, extension = False)
Turns a collection of rules into a lookup.
A Lookup (as defined in the `OpenType Spec <https://docs.microsoft.com/en-gb/typography/opentype/spec/chapter2#lookupTbl>`__)
wraps the individual rules in a layout operation (substitution or
positioning) in a data structure expressing their overall lookup type -
for example, single substitution, mark-to-base attachment, and so on -
as well as the lookup flags and any mark filtering sets. You may import
the following constants to express lookup flags:
- ``LOOKUP_FLAG_RIGHT_TO_LEFT``
- ``LOOKUP_FLAG_IGNORE_BASE_GLYPHS``
- ``LOOKUP_FLAG_IGNORE_LIGATURES``
- ``LOOKUP_FLAG_IGNORE_MARKS``
- ``LOOKUP_FLAG_USE_MARK_FILTERING_SET``
Args:
    subtables: A list of layout subtable objects (e.g.
        ``MultipleSubst``, ``PairPos``, etc.) or ``None``.
    flags (int): This lookup's flags.
    markFilterSet: Either ``None`` if no mark filtering set is used, or
        an integer representing the filtering set to be used for this
        lookup. If a mark filtering set is provided,
        `LOOKUP_FLAG_USE_MARK_FILTERING_SET` will be set on the lookup's
        flags.
    table (str): The name of the table this lookup belongs to, e.g. "GPOS" or "GSUB".
    extension (bool): ``True`` if this is an extension lookup, ``False`` otherwise.
Returns:
    An ``otTables.Lookup`` object or ``None`` if there are no subtables
    supplied.
Definition at line 78 of file builder.py.
Referenced by fontTools.otlLib.builder.LookupBuilder.getAlternateGlyphs().
buildMark2Record()
fontTools.otlLib.builder.buildMark2Record (anchors)
Definition at line 2306 of file builder.py.
buildMarkArray()
fontTools.otlLib.builder.buildMarkArray (marks, glyphMap)
Builds a mark array subtable.
As part of building mark-to-* positioning rules, you will need to define
a MarkArray subtable, which "defines the class and the anchor point
for a mark glyph." This function builds the mark array subtable.
Example::
    mark = {
        "acute": (0, buildAnchor(300,712)),
        # ...
    }
    markarray = buildMarkArray(marks, font.getReverseGlyphMap())
Args:
    marks (dict): A dictionary mapping anchors to glyphs; the keys being
        glyph names, and the values being a tuple of mark class number and
        an ``otTables.Anchor`` object representing the mark's attachment
        point.
    glyphMap: a glyph name to ID map, typically returned from
        ``font.getReverseGlyphMap()``.
Returns:
    An ``otTables.MarkArray`` object.
Definition at line 2148 of file builder.py.
Referenced by fontTools.otlLib.builder.MarkMarkPosBuilder.build(), buildMarkBasePosSubtable(), and buildMarkLigPosSubtable().
buildMarkBasePos()
fontTools.otlLib.builder.buildMarkBasePos (marks, bases, glyphMap)
Build a list of MarkBasePos (GPOS4) subtables.
.. deprecated:: 4.58.0
       Use :func:`buildMarkBasePosSubtable` instead.
Definition at line 2187 of file builder.py.
References buildMarkBasePosSubtable().
buildMarkBasePosSubtable()
fontTools.otlLib.builder.buildMarkBasePosSubtable (marks, bases, glyphMap)
Build a single MarkBasePos (GPOS4) subtable.
This builds a mark-to-base lookup subtable containing all of the referenced
marks and bases.
Example::
    # a1, a2, a3, a4, a5 = buildAnchor(500, 100), ...
    marks = {"acute": (0, a1), "grave": (0, a1), "cedilla": (1, a2)}
    bases = {"a": {0: a3, 1: a5}, "b": {0: a4, 1: a5}}
    markbaseposes = [buildMarkBasePosSubtable(marks, bases, font.getReverseGlyphMap())]
Args:
    marks (dict): A dictionary mapping anchors to glyphs; the keys being
        glyph names, and the values being a tuple of mark class number and
        an ``otTables.Anchor`` object representing the mark's attachment
        point. (See :func:`buildMarkArray`.)
    bases (dict): A dictionary mapping anchors to glyphs; the keys being
        glyph names, and the values being dictionaries mapping mark class ID
        to the appropriate ``otTables.Anchor`` object used for attaching marks
        of that class. (See :func:`buildBaseArray`.)
    glyphMap: a glyph name to ID map, typically returned from
        ``font.getReverseGlyphMap()``.
Returns:
    A ``otTables.MarkBasePos`` object.
Definition at line 2196 of file builder.py.
References buildBaseArray(), buildCoverage(), and buildMarkArray().
Referenced by fontTools.otlLib.builder.MarkBasePosBuilder.build(), and buildMarkBasePos().
buildMarkGlyphSetsDef()
fontTools.otlLib.builder.buildMarkGlyphSetsDef (markSets, glyphMap)
Builds a mark glyph sets definition table.
OpenType Layout lookups may choose to use mark filtering sets to consider
or ignore particular combinations of marks. These sets are specified by
setting a flag on the lookup, but the mark filtering sets are defined in
the ``GDEF`` table. This routine builds the subtable containing the mark
glyph set definitions.
Example::
    set0 = set("acute", "grave")
    set1 = set("caron", "grave")
    markglyphsets = buildMarkGlyphSetsDef([set0, set1], font.getReverseGlyphMap())
Args:
    markSets: A list of sets of glyphnames.
    glyphMap: a glyph name to ID map, typically returned from
        ``font.getReverseGlyphMap()``.
Returns
    An ``otTables.MarkGlyphSetsDef`` object.
Definition at line 2839 of file builder.py.
References buildCoverage().
buildMarkLigPos()
fontTools.otlLib.builder.buildMarkLigPos (marks, ligs, glyphMap)
Build a list of MarkLigPos (GPOS5) subtables.
.. deprecated:: 4.58.0
   Use :func:`buildMarkLigPosSubtable` instead.
Definition at line 2236 of file builder.py.
References buildMarkLigPosSubtable().
buildMarkLigPosSubtable()
fontTools.otlLib.builder.buildMarkLigPosSubtable (marks, ligs, glyphMap)
Build a single MarkLigPos (GPOS5) subtable.
This builds a mark-to-base lookup subtable containing all of the referenced
marks and bases.
Note that if you are implementing a layout compiler, you may find it more
flexible to use
:py:class:`fontTools.otlLib.lookupBuilders.MarkLigPosBuilder` instead.
Example::
    # a1, a2, a3, a4, a5 = buildAnchor(500, 100), ...
    marks = {
        "acute": (0, a1),
        "grave": (0, a1),
        "cedilla": (1, a2)
    }
    ligs = {
        "f_i": [
            { 0: a3, 1: a5 }, # f
            { 0: a4, 1: a5 }  # i
            ],
    #   "c_t": [{...}, {...}]
    }
    markligpose = buildMarkLigPosSubtable(marks, ligs,
        font.getReverseGlyphMap())
Args:
    marks (dict): A dictionary mapping anchors to glyphs; the keys being
        glyph names, and the values being a tuple of mark class number and
        an ``otTables.Anchor`` object representing the mark's attachment
        point. (See :func:`buildMarkArray`.)
    ligs (dict): A mapping of ligature names to an array of dictionaries:
        for each component glyph in the ligature, an dictionary mapping
        mark class IDs to anchors. (See :func:`buildLigatureArray`.)
    glyphMap: a glyph name to ID map, typically returned from
        ``font.getReverseGlyphMap()``.
Returns:
    A ``otTables.MarkLigPos`` object.
Definition at line 2245 of file builder.py.
References buildCoverage(), buildLigatureArray(), and buildMarkArray().
Referenced by fontTools.otlLib.builder.MarkLigPosBuilder.build(), and buildMarkLigPos().
buildMarkRecord()
fontTools.otlLib.builder.buildMarkRecord (classID, anchor)
Definition at line 2297 of file builder.py.
buildMathTable()
fontTools.otlLib.builder.buildMathTable (ttFont, constants = None, italicsCorrections = None, topAccentAttachments = None, extendedShapes = None, mathKerns = None, minConnectorOverlap = 0, vertGlyphVariants = None, horizGlyphVariants = None, vertGlyphAssembly = None, horizGlyphAssembly = None)
Add a 'MATH' table to 'ttFont'.
'constants' is a dictionary of math constants. The keys are the constant
names from the MATH table specification (with capital first letter), and the
values are the constant values as numbers.
'italicsCorrections' is a dictionary of italic corrections. The keys are the
glyph names, and the values are the italic corrections as numbers.
'topAccentAttachments' is a dictionary of top accent attachments. The keys
are the glyph names, and the values are the top accent horizontal positions
as numbers.
'extendedShapes' is a set of extended shape glyphs.
'mathKerns' is a dictionary of math kerns. The keys are the glyph names, and
the values are dictionaries. The keys of these dictionaries are the side
names ('TopRight', 'TopLeft', 'BottomRight', 'BottomLeft'), and the values
are tuples of two lists. The first list contains the correction heights as
numbers, and the second list contains the kern values as numbers.
'minConnectorOverlap' is the minimum connector overlap as a number.
'vertGlyphVariants' is a dictionary of vertical glyph variants. The keys are
the glyph names, and the values are tuples of glyph name and full advance height.
'horizGlyphVariants' is a dictionary of horizontal glyph variants. The keys
are the glyph names, and the values are tuples of glyph name and full
advance width.
'vertGlyphAssembly' is a dictionary of vertical glyph assemblies. The keys
are the glyph names, and the values are tuples of assembly parts and italics
correction. The assembly parts are tuples of glyph name, flags, start
connector length, end connector length, and full advance height.
'horizGlyphAssembly' is a dictionary of horizontal glyph assemblies. The
keys are the glyph names, and the values are tuples of assembly parts
and italics correction. The assembly parts are tuples of glyph name, flags,
start connector length, end connector length, and full advance width.
Where a number is expected, an integer or a float can be used. The floats
will be rounded.
Example::
    constants = {
        "ScriptPercentScaleDown": 70,
        "ScriptScriptPercentScaleDown": 50,
        "DelimitedSubFormulaMinHeight": 24,
        "DisplayOperatorMinHeight": 60,
        ...
    }
    italicsCorrections = {
        "fitalic-math": 100,
        "fbolditalic-math": 120,
        ...
    }
    topAccentAttachments = {
        "circumflexcomb": 500,
        "acutecomb": 400,
        "A": 300,
        "B": 340,
        ...
    }
    extendedShapes = {"parenleft", "parenright", ...}
    mathKerns = {
        "A": {
            "TopRight": ([-50, -100], [10, 20, 30]),
            "TopLeft": ([50, 100], [10, 20, 30]),
            ...
        },
        ...
    }
    vertGlyphVariants = {
        "parenleft": [("parenleft", 700), ("parenleft.size1", 1000), ...],
        "parenright": [("parenright", 700), ("parenright.size1", 1000), ...],
        ...
    }
    vertGlyphAssembly = {
        "braceleft": [
            (
                ("braceleft.bottom", 0, 0, 200, 500),
                ("braceleft.extender", 1, 200, 200, 200)),
                ("braceleft.middle", 0, 100, 100, 700),
                ("braceleft.extender", 1, 200, 200, 200),
                ("braceleft.top", 0, 200, 0, 500),
            ),
            100,
        ],
        ...
    }
Definition at line 3177 of file builder.py.
References buildCoverage().
buildMultipleSubstSubtable()
fontTools.otlLib.builder.buildMultipleSubstSubtable (mapping)
Builds a multiple substitution (GSUB2) subtable.
Note that if you are implementing a layout compiler, you may find it more
flexible to use
:py:class:`fontTools.otlLib.lookupBuilders.MultipleSubstBuilder` instead.
Example::
    # sub uni06C0 by uni06D5.fina hamza.above
    # sub uni06C2 by uni06C1.fina hamza.above;
    subtable = buildMultipleSubstSubtable({
        "uni06C0": [ "uni06D5.fina", "hamza.above"],
        "uni06C2": [ "uni06D1.fina", "hamza.above"]
    })
Args:
    mapping: A dictionary mapping input glyph names to a list of output
        glyph names.
Returns:
    An ``otTables.MultipleSubst`` object or ``None`` if the mapping dictionary
    is empty.
Definition at line 1822 of file builder.py.
buildPairPosClassesSubtable()
fontTools.otlLib.builder.buildPairPosClassesSubtable (pairs, glyphMap, valueFormat1 = None, valueFormat2 = None)
Builds a class pair adjustment (GPOS2 format 2) subtable.
Kerning tables are generally expressed as pair positioning tables using
class-based pair adjustments. This routine builds format 2 PairPos
subtables.
Note that if you are implementing a layout compiler, you may find it more
flexible to use
:py:class:`fontTools.otlLib.lookupBuilders.ClassPairPosSubtableBuilder`
instead, as this takes care of ensuring that the supplied pairs can be
formed into non-overlapping classes and emitting individual subtables
whenever the non-overlapping requirement means that a new subtable is
required.
Example::
    pairs = {}
    pairs[(
        [ "K", "X" ],
        [ "W", "V" ]
    )] = ( buildValue(xAdvance=+5), buildValue() )
    # pairs[(... , ...)] = (..., ...)
    pairpos = buildPairPosClassesSubtable(pairs, font.getReverseGlyphMap())
Args:
    pairs (dict): Pair positioning data; the keys being a two-element
        tuple of lists of glyphnames, and the values being a two-element
        tuple of ``otTables.ValueRecord`` objects.
    glyphMap: a glyph name to ID map, typically returned from
        ``font.getReverseGlyphMap()``.
    valueFormat1: Force the "left" value records to the given format.
    valueFormat2: Force the "right" value records to the given format.
Returns:
    A ``otTables.PairPos`` object.
Definition at line 2324 of file builder.py.
References buildCoverage().
Referenced by fontTools.otlLib.builder.ClassPairPosSubtableBuilder.subtables().
buildPairPosGlyphs()
fontTools.otlLib.builder.buildPairPosGlyphs (pairs, glyphMap)
Builds a list of glyph-based pair adjustment (GPOS2 format 1) subtables.
This organises a list of pair positioning adjustments into subtables based
on common value record formats.
Note that if you are implementing a layout compiler, you may find it more
flexible to use
:py:class:`fontTools.otlLib.lookupBuilders.PairPosBuilder`
instead.
Example::
    pairs = {
        ("K", "W"): ( buildValue(xAdvance=+5), buildValue() ),
        ("K", "V"): ( buildValue(xAdvance=+5), buildValue() ),
        # ...
    }
    subtables = buildPairPosGlyphs(pairs, font.getReverseGlyphMap())
Args:
    pairs (dict): Pair positioning data; the keys being a two-element
        tuple of glyphnames, and the values being a two-element
        tuple of ``otTables.ValueRecord`` objects.
    glyphMap: a glyph name to ID map, typically returned from
        ``font.getReverseGlyphMap()``.
Returns:
    A list of ``otTables.PairPos`` objects.
Definition at line 2403 of file builder.py.
References buildPairPosGlyphsSubtable().
Referenced by fontTools.otlLib.builder.PairPosBuilder.build().
buildPairPosGlyphsSubtable()
fontTools.otlLib.builder.buildPairPosGlyphsSubtable (pairs, glyphMap, valueFormat1 = None, valueFormat2 = None)
Builds a single glyph-based pair adjustment (GPOS2 format 1) subtable.
This builds a PairPos subtable from a dictionary of glyph pairs and
their positioning adjustments. See also :func:`buildPairPosGlyphs`.
Note that if you are implementing a layout compiler, you may find it more
flexible to use
:py:class:`fontTools.otlLib.lookupBuilders.PairPosBuilder` instead.
Example::
    pairs = {
        ("K", "W"): ( buildValue(xAdvance=+5), buildValue() ),
        ("K", "V"): ( buildValue(xAdvance=+5), buildValue() ),
        # ...
    }
    pairpos = buildPairPosGlyphsSubtable(pairs, font.getReverseGlyphMap())
Args:
    pairs (dict): Pair positioning data; the keys being a two-element
        tuple of glyphnames, and the values being a two-element
        tuple of ``otTables.ValueRecord`` objects.
    glyphMap: a glyph name to ID map, typically returned from
        ``font.getReverseGlyphMap()``.
    valueFormat1: Force the "left" value records to the given format.
    valueFormat2: Force the "right" value records to the given format.
Returns:
    A ``otTables.PairPos`` object.
Definition at line 2447 of file builder.py.
References buildCoverage().
Referenced by buildPairPosGlyphs().
buildSinglePos()
fontTools.otlLib.builder.buildSinglePos (mapping, glyphMap)
Builds a list of single adjustment (GPOS1) subtables.
This builds a list of SinglePos subtables from a dictionary of glyph
names and their positioning adjustments. The format of the subtables are
determined to optimize the size of the resulting subtables.
See also :func:`buildSinglePosSubtable`.
Note that if you are implementing a layout compiler, you may find it more
flexible to use
:py:class:`fontTools.otlLib.lookupBuilders.SinglePosBuilder` instead.
Example::
    mapping = {
        "V": buildValue({ "xAdvance" : +5 }),
        # ...
    }
    subtables = buildSinglePos(pairs, font.getReverseGlyphMap())
Args:
    mapping (dict): A mapping between glyphnames and
        ``otTables.ValueRecord`` objects.
    glyphMap: a glyph name to ID map, typically returned from
        ``font.getReverseGlyphMap()``.
Returns:
    A list of ``otTables.SinglePos`` objects.
Definition at line 2511 of file builder.py.
References buildSinglePosSubtable().
Referenced by fontTools.otlLib.builder.SinglePosBuilder.build().
buildSinglePosSubtable()
fontTools.otlLib.builder.buildSinglePosSubtable (values, glyphMap)
Builds a single adjustment (GPOS1) subtable.
This builds a list of SinglePos subtables from a dictionary of glyph
names and their positioning adjustments. The format of the subtable is
determined to optimize the size of the output.
See also :func:`buildSinglePos`.
Note that if you are implementing a layout compiler, you may find it more
flexible to use
:py:class:`fontTools.otlLib.lookupBuilders.SinglePosBuilder` instead.
Example::
    mapping = {
        "V": buildValue({ "xAdvance" : +5 }),
        # ...
    }
    subtable = buildSinglePos(pairs, font.getReverseGlyphMap())
Args:
    mapping (dict): A mapping between glyphnames and
        ``otTables.ValueRecord`` objects.
    glyphMap: a glyph name to ID map, typically returned from
        ``font.getReverseGlyphMap()``.
Returns:
    A ``otTables.SinglePos`` object.
Definition at line 2593 of file builder.py.
References buildCoverage().
Referenced by buildSinglePos().
buildSingleSubstSubtable()
fontTools.otlLib.builder.buildSingleSubstSubtable (mapping)
Builds a single substitution (GSUB1) subtable.
Note that if you are implementing a layout compiler, you may find it more
flexible to use
:py:class:`fontTools.otlLib.lookupBuilders.SingleSubstBuilder` instead.
Args:
    mapping: A dictionary mapping input glyph names to output glyph names.
Returns:
    An ``otTables.SingleSubst`` object, or ``None`` if the mapping dictionary
    is empty.
Definition at line 1801 of file builder.py.
buildStatTable()
None fontTools.otlLib.builder.buildStatTable (TTFont ttFont, axes, locations = None, Union[STATName, STATNameStatement] elidedFallbackName = 2, bool windowsNames = True, bool macNames = True)
Add a 'STAT' table to 'ttFont'.
'axes' is a list of dictionaries describing axes and their
values.
Example::
    axes = [
        dict(
            tag="wght",
            name="Weight",
            ordering=0,  # optional
            values=[
                dict(value=100, name='Thin'),
                dict(value=300, name='Light'),
                dict(value=400, name='Regular', flags=0x2),
                dict(value=900, name='Black'),
            ],
        )
    ]
Each axis dict must have 'tag' and 'name' items. 'tag' maps
to the 'AxisTag' field. 'name' can be a name ID (int), a string,
or a dictionary containing multilingual names (see the
addMultilingualName() name table method), and will translate to
the AxisNameID field.
An axis dict may contain an 'ordering' item that maps to the
AxisOrdering field. If omitted, the order of the axes list is
used to calculate AxisOrdering fields.
The axis dict may contain a 'values' item, which is a list of
dictionaries describing AxisValue records belonging to this axis.
Each value dict must have a 'name' item, which can be a name ID
(int), a string, or a dictionary containing multilingual names,
like the axis name. It translates to the ValueNameID field.
Optionally the value dict can contain a 'flags' item. It maps to
the AxisValue Flags field, and will be 0 when omitted.
The format of the AxisValue is determined by the remaining contents
of the value dictionary:
If the value dict contains a 'value' item, an AxisValue record
Format 1 is created. If in addition to the 'value' item it contains
a 'linkedValue' item, an AxisValue record Format 3 is built.
If the value dict contains a 'nominalValue' item, an AxisValue
record Format 2 is built. Optionally it may contain 'rangeMinValue'
and 'rangeMaxValue' items. These map to -Infinity and +Infinity
respectively if omitted.
You cannot specify Format 4 AxisValue tables this way, as they are
not tied to a single axis, and specify a name for a location that
is defined by multiple axes values. Instead, you need to supply the
'locations' argument.
The optional 'locations' argument specifies AxisValue Format 4
tables. It should be a list of dicts, where each dict has a 'name'
item, which works just like the value dicts above, an optional
'flags' item (defaulting to 0x0), and a 'location' dict. A
location dict key is an axis tag, and the associated value is the
location on the specified axis. They map to the AxisIndex and Value
fields of the AxisValueRecord.
Example::
    locations = [
        dict(name='Regular ABCD', location=dict(wght=300, ABCD=100)),
        dict(name='Bold ABCD XYZ', location=dict(wght=600, ABCD=200)),
    ]
The optional 'elidedFallbackName' argument can be a name ID (int),
a string, a dictionary containing multilingual names, or a list of
STATNameStatements. It translates to the ElidedFallbackNameID field.
The 'ttFont' argument must be a TTFont instance that already has a
'name' table. If a 'STAT' table already exists, it will be
overwritten by the newly created one.
Definition at line 2943 of file builder.py.
Referenced by fontTools.varLib.stat.buildVFStatTable().
buildValue()
fontTools.otlLib.builder.buildValue (value)
Builds a positioning value record.
Value records are used to specify coordinates and adjustments for
positioning and attaching glyphs. Many of the positioning functions
in this library take ``otTables.ValueRecord`` objects as arguments.
This function builds value records from dictionaries.
Args:
    value (dict): A dictionary with zero or more of the following keys:
        - ``xPlacement``
        - ``yPlacement``
        - ``xAdvance``
        - ``yAdvance``
        - ``xPlaDevice``
        - ``yPlaDevice``
        - ``xAdvDevice``
        - ``yAdvDevice``
Returns:
    An ``otTables.ValueRecord`` object.
Definition at line 2690 of file builder.py.
Variable Documentation
_DeviceTuple
fontTools.otlLib.builder._DeviceTuple = namedtuple("_DeviceTuple", "DeltaFormat StartSize EndSize DeltaValue") protected
Definition at line 2666 of file builder.py.
alternates
fontTools.otlLib.builder.alternates = dict(mapping)
Definition at line 1872 of file builder.py.
AnchorPoint
fontTools.otlLib.builder.AnchorPoint = point
Definition at line 1941 of file builder.py.
AttachPoint
list fontTools.otlLib.builder.AttachPoint = [buildAttachPoint(attachPoints[g]) for g in self.Coverage.glyphs]
Definition at line 2740 of file builder.py.
AXIS_VALUE_NEGATIVE_INFINITY
fontTools.otlLib.builder.AXIS_VALUE_NEGATIVE_INFINITY = fixedToFloat(-0x80000000, 16)
Definition at line 2936 of file builder.py.
AXIS_VALUE_POSITIVE_INFINITY
fontTools.otlLib.builder.AXIS_VALUE_POSITIVE_INFINITY = fixedToFloat(0x7FFFFFFF, 16)
Definition at line 2937 of file builder.py.
BaseAnchor
fontTools.otlLib.builder.BaseAnchor = anchors
Definition at line 1992 of file builder.py.
BaseArray
fontTools.otlLib.builder.BaseArray = buildBaseArray(bases, self.ClassCount, glyphMap)
Definition at line 2231 of file builder.py.
BaseCount
fontTools.otlLib.builder.BaseCount = len(self.BaseRecord)
Definition at line 1985 of file builder.py.
BaseCoverage
fontTools.otlLib.builder.BaseCoverage = buildCoverage(bases, glyphMap)
Definition at line 2230 of file builder.py.
BaseRecord
list fontTools.otlLib.builder.BaseRecord = []
Definition at line 1980 of file builder.py.
CaretCount
fontTools.otlLib.builder.CaretCount = len(self.CaretValue)
Definition at line 2835 of file builder.py.
CaretValue
fontTools.otlLib.builder.CaretValue = carets
Definition at line 2834 of file builder.py.
CaretValuePoint
fontTools.otlLib.builder.CaretValuePoint = point
Definition at line 2773 of file builder.py.
Class
fontTools.otlLib.builder.Class = classID
Definition at line 2301 of file builder.py.
Class1Count
fontTools.otlLib.builder.Class1Count = len(self.Class1Record)
Definition at line 2398 of file builder.py.
Class1Record
list fontTools.otlLib.builder.Class1Record = []
Definition at line 2379 of file builder.py.
Class2Count
fontTools.otlLib.builder.Class2Count = len(classes2)
Definition at line 2399 of file builder.py.
ClassCount
int fontTools.otlLib.builder.ClassCount = max([mc for mc, _ in marks.values()]) + 1
Definition at line 2229 of file builder.py.
ClassDef1
fontTools.otlLib.builder.ClassDef1 = classDef1.build()
Definition at line 2375 of file builder.py.
ClassDef2
fontTools.otlLib.builder.ClassDef2 = classDef2.build()
Definition at line 2376 of file builder.py.
ComponentCount
fontTools.otlLib.builder.ComponentCount = len(self.ComponentRecord)
Definition at line 2144 of file builder.py.
ComponentRecord
list fontTools.otlLib.builder.ComponentRecord = [buildComponentRecord(c) for c in components]
Definition at line 2143 of file builder.py.
Coordinate
fontTools.otlLib.builder.Coordinate = 3
Definition at line 2762 of file builder.py.
Coverage
list fontTools.otlLib.builder.Coverage = buildCoverage(attach.keys(), glyphMap)
Definition at line 2047 of file builder.py.
DeltaFormat
int fontTools.otlLib.builder.DeltaFormat = 1
Definition at line 2090 of file builder.py.
DeltaValue
list fontTools.otlLib.builder.DeltaValue
Initial value:
=  [
        deltas.get(size, 0) for size in range(startSize, endSize + 1)
    ]
Definition at line 2083 of file builder.py.
DeviceTable
fontTools.otlLib.builder.DeviceTable = coord
Definition at line 2762 of file builder.py.
EndSize
fontTools.otlLib.builder.EndSize = max(keys)
Definition at line 2081 of file builder.py.
EntryExitCount
fontTools.otlLib.builder.EntryExitCount = len(self.EntryExitRecord)
Definition at line 2055 of file builder.py.
EntryExitRecord
list fontTools.otlLib.builder.EntryExitRecord = []
Definition at line 2048 of file builder.py.
Format
int fontTools.otlLib.builder.Format = 1
Definition at line 1939 of file builder.py.
GlyphCount
fontTools.otlLib.builder.GlyphCount = len(self.AttachPoint)
Definition at line 2741 of file builder.py.
glyphs
fontTools.otlLib.builder.glyphs = sorted(set(glyphs), key=glyphMap.__getitem__)
Definition at line 64 of file builder.py.
LigatureAnchor
fontTools.otlLib.builder.LigatureAnchor = anchors
Definition at line 2014 of file builder.py.
LigatureArray
fontTools.otlLib.builder.LigatureArray = buildLigatureArray(ligs, self.ClassCount, glyphMap)
Definition at line 2293 of file builder.py.
LigatureAttach
list fontTools.otlLib.builder.LigatureAttach = []
Definition at line 2130 of file builder.py.
LigatureCount
fontTools.otlLib.builder.LigatureCount = len(self.LigatureAttach)
Definition at line 2136 of file builder.py.
LigatureCoverage
fontTools.otlLib.builder.LigatureCoverage = buildCoverage(ligs, glyphMap)
Definition at line 2292 of file builder.py.
ligatures
dict fontTools.otlLib.builder.ligatures = {}
Definition at line 1908 of file builder.py.
LigGlyph
list fontTools.otlLib.builder.LigGlyph = [carets[g] for g in self.Coverage.glyphs]
Definition at line 2818 of file builder.py.
LigGlyphCount
fontTools.otlLib.builder.LigGlyphCount = len(self.LigGlyph)
Definition at line 2819 of file builder.py.
log
fontTools.otlLib.builder.log = logging.getLogger(__name__)
Definition at line 29 of file builder.py.
LOOKUP_FLAG_IGNORE_BASE_GLYPHS
int fontTools.otlLib.builder.LOOKUP_FLAG_IGNORE_BASE_GLYPHS = 0x0002
Definition at line 72 of file builder.py.
LOOKUP_FLAG_IGNORE_LIGATURES
int fontTools.otlLib.builder.LOOKUP_FLAG_IGNORE_LIGATURES = 0x0004
Definition at line 73 of file builder.py.
LOOKUP_FLAG_IGNORE_MARKS
int fontTools.otlLib.builder.LOOKUP_FLAG_IGNORE_MARKS = 0x0008
Definition at line 74 of file builder.py.
LOOKUP_FLAG_RIGHT_TO_LEFT
int fontTools.otlLib.builder.LOOKUP_FLAG_RIGHT_TO_LEFT = 0x0001
Definition at line 71 of file builder.py.
LOOKUP_FLAG_USE_MARK_FILTERING_SET
int fontTools.otlLib.builder.LOOKUP_FLAG_USE_MARK_FILTERING_SET = 0x0010
Definition at line 75 of file builder.py.
LookupFlag
fontTools.otlLib.builder.LookupFlag = flags
Definition at line 135 of file builder.py.
LookupType
fontTools.otlLib.builder.LookupType = lookupType
Definition at line 134 of file builder.py.
mapping
fontTools.otlLib.builder.mapping = dict(mapping)
Definition at line 1818 of file builder.py.
Mark2Anchor
fontTools.otlLib.builder.Mark2Anchor = anchors
Definition at line 2309 of file builder.py.
MarkAnchor
fontTools.otlLib.builder.MarkAnchor = anchor
Definition at line 2302 of file builder.py.
MarkArray
fontTools.otlLib.builder.MarkArray = buildMarkArray(marks, glyphMap)
Definition at line 2228 of file builder.py.
MarkCount
fontTools.otlLib.builder.MarkCount = len(self.MarkRecord)
Definition at line 2180 of file builder.py.
MarkCoverage
fontTools.otlLib.builder.MarkCoverage = buildCoverage(marks, glyphMap)
Definition at line 2227 of file builder.py.
MarkFilteringSet
fontTools.otlLib.builder.MarkFilteringSet = markFilterSet
Definition at line 141 of file builder.py.
MarkRecord
list fontTools.otlLib.builder.MarkRecord = []
Definition at line 2175 of file builder.py.
MarkSetCount
fontTools.otlLib.builder.MarkSetCount = len(self.Coverage)
Definition at line 2869 of file builder.py.
MarkSetTableFormat
int fontTools.otlLib.builder.MarkSetTableFormat = 1
Definition at line 2867 of file builder.py.
PairSet
list fontTools.otlLib.builder.PairSet = []
Definition at line 2487 of file builder.py.
PairSetCount
fontTools.otlLib.builder.PairSetCount = len(self.PairSet)
Definition at line 2507 of file builder.py.
PointCount
fontTools.otlLib.builder.PointCount = len(self.PointIndex)
Definition at line 2752 of file builder.py.
PointIndex
fontTools.otlLib.builder.PointIndex = sorted(set(points))
Definition at line 2751 of file builder.py.
StartSize
fontTools.otlLib.builder.StartSize = min(keys)
Definition at line 2080 of file builder.py.
STATName
fontTools.otlLib.builder.STATName = Union[int, str, Dict[str, str]]
Definition at line 2939 of file builder.py.
SubTable
fontTools.otlLib.builder.SubTable = subtables
Definition at line 136 of file builder.py.
SubTableCount
fontTools.otlLib.builder.SubTableCount = len(self.SubTable)
Definition at line 137 of file builder.py.
Value
fontTools.otlLib.builder.Value = valueRecords[0]
Definition at line 2635 of file builder.py.
ValueCount
fontTools.otlLib.builder.ValueCount = len(self.Value)
Definition at line 2641 of file builder.py.
XCoordinate
fontTools.otlLib.builder.XCoordinate
Definition at line 1938 of file builder.py.
XDeviceTable
fontTools.otlLib.builder.XDeviceTable = deviceX
Definition at line 1947 of file builder.py.
YCoordinate
fontTools.otlLib.builder.YCoordinate = x, y
Definition at line 1938 of file builder.py.
YDeviceTable
fontTools.otlLib.builder.YDeviceTable = deviceY
Definition at line 1948 of file builder.py.