Code Cloning Analysis: sklearn.utils._set_output Namespace Reference
sklearn.utils._set_output Namespace Reference
Classes
class _SetOutputMixin
class ContainerAdapterProtocol
class ContainerAdaptersManager
class PandasAdapter
class PolarsAdapter
Functions
check_library_installed (library)
get_columns (columns)
_get_adapter_from_container (container)
_get_container_adapter (method, estimator=None)
_get_output_config (method, estimator=None)
_wrap_data_with_container (method, data_to_wrap, original_input, estimator)
_wrap_method_output (f, method)
_auto_wrap_is_configured (estimator)
_safe_set_output (estimator, *, transform=None)
Variables
ADAPTERS_MANAGER = ContainerAdaptersManager()
Function Documentation
_auto_wrap_is_configured()
sklearn.utils._set_output._auto_wrap_is_configured (estimator) protected
Return True if estimator is configured for auto-wrapping the transform method.
`_SetOutputMixin` sets `_sklearn_auto_wrap_output_keys` to `set()` if auto wrapping
is manually disabled.
Definition at line 334 of file _set_output.py.
Referenced by _wrap_data_with_container().
_get_adapter_from_container()
sklearn.utils._set_output._get_adapter_from_container (container) protected
Get the adapter that knows how to handle such container.
See :class:`sklearn.utils._set_output.ContainerAdapterProtocol` for more
details.
Definition at line 203 of file _set_output.py.
_get_container_adapter()
sklearn.utils._set_output._get_container_adapter (method, estimator = None) protected
Get container adapter.
Definition at line 221 of file _set_output.py.
References _get_output_config().
_get_output_config()
sklearn.utils._set_output._get_output_config (method, estimator = None) protected
Get output config based on estimator and global configuration.
Parameters
----------
method : {"transform"}
    Estimator's method for which the output container is looked up.
estimator : estimator instance or None
    Estimator to get the output configuration from. If `None`, check global
    configuration is used.
Returns
-------
config : dict
    Dictionary with keys:
    - "dense": specifies the dense container for `method`. This can be
      `"default"` or `"pandas"`.
Definition at line 230 of file _set_output.py.
Referenced by _get_container_adapter(), and _wrap_data_with_container().
_safe_set_output()
sklearn.utils._set_output._safe_set_output (estimator, * , transform = None) protected
Safely call estimator.set_output and error if it not available.
This is used by meta-estimators to set the output for child estimators.
Parameters
----------
estimator : estimator instance
    Estimator instance.
transform : {"default", "pandas", "polars"}, default=None
    Configure output of the following estimator's methods:
    - `"transform"`
    - `"fit_transform"`
    If `None`, this operation is a no-op.
Returns
-------
estimator : estimator instance
    Estimator instance.
Definition at line 424 of file _set_output.py.
_wrap_data_with_container()
sklearn.utils._set_output._wrap_data_with_container (method, data_to_wrap, original_input, estimator) protected
Wrap output with container based on an estimator's or global config.
Parameters
----------
method : {"transform"}
    Estimator's method to get container output for.
data_to_wrap : {ndarray, dataframe}
    Data to wrap with container.
original_input : {ndarray, dataframe}
    Original input of function.
estimator : estimator instance
    Estimator with to get the output configuration from.
Returns
-------
output : {ndarray, dataframe}
    If the output config is "default" or the estimator is not configured
    for wrapping return `data_to_wrap` unchanged.
    If the output config is "pandas", return `data_to_wrap` as a pandas
    DataFrame.
Definition at line 265 of file _set_output.py.
References _auto_wrap_is_configured(), and _get_output_config().
Referenced by _wrap_method_output().
_wrap_method_output()
sklearn.utils._set_output._wrap_method_output (f, method) protected
Wrapper used by `_SetOutputMixin` to automatically wrap methods.
Definition at line 311 of file _set_output.py.
References _wrap_data_with_container().
check_library_installed()
sklearn.utils._set_output.check_library_installed (library)
Check library is installed.
Definition at line 15 of file _set_output.py.
get_columns()
sklearn.utils._set_output.get_columns (columns)
Definition at line 26 of file _set_output.py.
Variable Documentation
ADAPTERS_MANAGER
sklearn.utils._set_output.ADAPTERS_MANAGER = ContainerAdaptersManager()
Definition at line 198 of file _set_output.py.