Code Cloning Analysis: pandas._config.localization Namespace Reference
pandas._config.localization Namespace Reference
Functions
Generator[str|tuple[str, str], None, None] set_locale (str|tuple[str, str] new_locale, int lc_var=locale.LC_ALL)
bool can_set_locale (str lc, int lc_var=locale.LC_ALL)
list[str] _valid_locales (list[str]|str locales, bool normalize)
list[str] get_locales (str|None prefix=None, bool normalize=True)
Detailed Description
Helpers for configuring locale settings.
Name `localization` is chosen to avoid overlap with builtin `locale` module.
Function Documentation
_valid_locales()
list[str] pandas._config.localization._valid_locales (list[str] | str locales, bool normalize) protected
Return a list of normalized locales that do not throw an ``Exception``
when set.
Parameters
----------
locales : str
    A string where each locale is separated by a newline.
normalize : bool
    Whether to call ``locale.normalize`` on each locale.
Returns
-------
valid_locales : list
    A list of valid locales.
Definition at line 84 of file localization.py.
References can_set_locale().
Referenced by get_locales().
can_set_locale()
bool pandas._config.localization.can_set_locale (str lc, int lc_var = locale.LC_ALL)
Check to see if we can set a locale, and subsequently get the locale,
without raising an Exception.
Parameters
----------
lc : str
    The locale to attempt to set.
lc_var : int, default `locale.LC_ALL`
    The category of the locale being set.
Returns
-------
bool
    Whether the passed locale can be set
Definition at line 57 of file localization.py.
References set_locale().
Referenced by _valid_locales().
get_locales()
list[str] pandas._config.localization.get_locales (str | None prefix = None, bool normalize = True)
Get all the locales that are available on the system.
Parameters
----------
prefix : str
    If not ``None`` then return only those locales with the prefix
    provided. For example to get all English language locales (those that
    start with ``"en"``), pass ``prefix="en"``.
normalize : bool
    Call ``locale.normalize`` on the resulting list of available locales.
    If ``True``, only locales that can be set without throwing an
    ``Exception`` are returned.
Returns
-------
locales : list of strings
    A list of locale strings that can be set with ``locale.setlocale()``.
    For example::
        locale.setlocale(locale.LC_ALL, locale_string)
On error will return an empty list (no locale available, e.g. Windows)
Definition at line 111 of file localization.py.
References _valid_locales().
set_locale()
Generator[str | tuple[str, str], None, None] pandas._config.localization.set_locale (str | tuple[str, str] new_locale, int lc_var = locale.LC_ALL)
Context manager for temporarily setting a locale.
Parameters
----------
new_locale : str or tuple
    A string of the form <language_country>.<encoding>. For example to set
    the current locale to US English with a UTF8 encoding, you would pass
    "en_US.UTF-8".
lc_var : int, default `locale.LC_ALL`
    The category of the locale being set.
Notes
-----
This is useful when you want to run a particular block of code under a
particular locale, without globally setting the locale. This probably isn't
thread-safe.
Definition at line 22 of file localization.py.
Referenced by can_set_locale().