Code Cloning Analysis: sklearn.cluster.tests.test_bicluster Namespace Reference
sklearn.cluster.tests.test_bicluster Namespace Reference
Classes
class MockBiclustering
Functions
test_get_submatrix (csr_container)
_test_shape_indices (model)
test_spectral_coclustering (global_random_seed, csr_container)
test_spectral_biclustering (global_random_seed, csr_container)
_do_scale_test (scaled)
_do_bistochastic_test (scaled)
test_scale_normalize (global_random_seed, csr_container)
test_bistochastic_normalize (global_random_seed, csr_container)
test_log_normalize (global_random_seed)
test_fit_best_piecewise (global_random_seed)
test_project_and_cluster (global_random_seed, csr_container)
test_perfect_checkerboard (global_random_seed)
test_spectralbiclustering_parameter_validation (params, type_err, err_msg)
test_n_features_in_ (est)
Detailed Description
Testing for Spectral Biclustering methods
Function Documentation
_do_bistochastic_test()
sklearn.cluster.tests.test_bicluster._do_bistochastic_test (scaled) protected
Check that rows and columns sum to the same constant.
Definition at line 146 of file test_bicluster.py.
References _do_bistochastic_test(), and _do_scale_test().
Referenced by _do_bistochastic_test().
_do_scale_test()
sklearn.cluster.tests.test_bicluster._do_scale_test (scaled) protected
Check that rows sum to one constant, and columns to another.
Definition at line 135 of file test_bicluster.py.
Referenced by _do_bistochastic_test().
_test_shape_indices()
sklearn.cluster.tests.test_bicluster._test_shape_indices (model) protected
Definition at line 54 of file test_bicluster.py.
test_bistochastic_normalize()
sklearn.cluster.tests.test_bicluster.test_bistochastic_normalize (global_random_seed, csr_container)
Definition at line 164 of file test_bicluster.py.
test_fit_best_piecewise()
sklearn.cluster.tests.test_bicluster.test_fit_best_piecewise (global_random_seed)
Definition at line 183 of file test_bicluster.py.
test_get_submatrix()
sklearn.cluster.tests.test_bicluster.test_get_submatrix (csr_container)
Definition at line 39 of file test_bicluster.py.
test_log_normalize()
sklearn.cluster.tests.test_bicluster.test_log_normalize (global_random_seed)
Definition at line 174 of file test_bicluster.py.
test_n_features_in_()
sklearn.cluster.tests.test_bicluster.test_n_features_in_ (est)
Definition at line 259 of file test_bicluster.py.
test_perfect_checkerboard()
sklearn.cluster.tests.test_bicluster.test_perfect_checkerboard (global_random_seed)
Definition at line 200 of file test_bicluster.py.
test_project_and_cluster()
sklearn.cluster.tests.test_bicluster.test_project_and_cluster (global_random_seed, csr_container)
Definition at line 191 of file test_bicluster.py.
test_scale_normalize()
sklearn.cluster.tests.test_bicluster.test_scale_normalize (global_random_seed, csr_container)
Definition at line 153 of file test_bicluster.py.
test_spectral_biclustering()
sklearn.cluster.tests.test_bicluster.test_spectral_biclustering (global_random_seed, csr_container)
Definition at line 94 of file test_bicluster.py.
test_spectral_coclustering()
sklearn.cluster.tests.test_bicluster.test_spectral_coclustering (global_random_seed, csr_container)
Definition at line 64 of file test_bicluster.py.
test_spectralbiclustering_parameter_validation()
sklearn.cluster.tests.test_bicluster.test_spectralbiclustering_parameter_validation (params, type_err, err_msg)
Check parameters validation in `SpectralBiClustering`
Definition at line 250 of file test_bicluster.py.