Code Cloning Analysis: fontTools.cffLib.TopDictIndex Class Reference
fontTools.cffLib.TopDictIndex Class Reference
Public Member Functions
__init__ (self, file=None, cff2GetGlyphOrder=None, topSize=0, isCFF2=None)
produceItem (self, index, data, file, offset)
toXML (self, xmlWriter)
Public Member Functions inherited from fontTools.cffLib.Index
__init__ (self, file=None, isCFF2=None)
__len__ (self)
__getitem__ (self, index)
__setitem__ (self, index, item)
append (self, item)
getCompiler (self, strings, parent, isCFF2=None)
clear (self)
Public Attributes
cff2GetGlyphOrder = cff2GetGlyphOrder
Public Attributes inherited from fontTools.cffLib.Index
list items = []
list offsets = []
file = file
int offsetBase = file.tell() - 1
Additional Inherited Members
Static Public Attributes inherited from fontTools.cffLib.Index
compilerClass = IndexCompiler
Protected Attributes inherited from fontTools.cffLib.Index
_isCFF2 = isCFF2
Detailed Description
This index represents the array of ``TopDict`` structures in the font
(again, usually only one entry is present). Hence the following calls are
equivalent:
.. code:: python
        tt["CFF "].cff[0]
        # <fontTools.cffLib.TopDict object at 0x102ed6e50>
        tt["CFF "].cff.topDictIndex[0]
        # <fontTools.cffLib.TopDict object at 0x102ed6e50>
Definition at line 769 of file __init__.py.
Constructor & Destructor Documentation
__init__()
fontTools.cffLib.TopDictIndex.__init__ (self, file = None, cff2GetGlyphOrder = None, topSize = 0, isCFF2 = None)
Definition at line 785 of file __init__.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
produceItem()
fontTools.cffLib.TopDictIndex.produceItem (self, index, data, file, offset)
Reimplemented from fontTools.cffLib.Index.
Definition at line 803 of file __init__.py.
toXML()
fontTools.cffLib.TopDictIndex.toXML (self, xmlWriter)
Definition at line 815 of file __init__.py.
Member Data Documentation
cff2GetGlyphOrder
fontTools.cffLib.TopDictIndex.cff2GetGlyphOrder = cff2GetGlyphOrder
Definition at line 786 of file __init__.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/cffLib/__init__.py