Code Cloning Analysis: pytz Namespace Reference
pytz Namespace Reference
Namespaces
namespace exceptions
namespace reference
namespace tzfile
namespace tzinfo
Classes
class _CountryNameDict
class _CountryTimezoneDict
class _FixedOffset
class UTC
Functions
ascii (s)
open_resource (name)
resource_exists (name)
timezone (zone)
_unmunge_zone (zone)
_case_insensitive_zone_lookup (zone)
_UTC ()
_p (*args)
FixedOffset (offset, _tzinfos={})
_test ()
Variables
str OLSON_VERSION = '2025b'
str VERSION = '2025.2'
str __version__ = VERSION
str OLSEN_VERSION = OLSON_VERSION
list __all__
unicode = str
dict _tzinfo_cache = {}
_all_timezones_lower_to_standard = None
ZERO = datetime.timedelta(0)
HOUR = datetime.timedelta(hours=1)
UTC = UTC()
__safe_for_unpickling__
country_timezones = _CountryTimezoneDict()
country_names = _CountryNameDict()
list _all_timezones_unchecked
all_timezones
all_timezones_set = LazySet(all_timezones)
list common_timezones
common_timezones_set = LazySet(common_timezones)
Detailed Description
datetime.tzinfo timezone definitions generated from the
Olson timezone database:
    ftp://elsie.nci.nih.gov/pub/tz*.tar.gz
See the datetime section of the Python Library Reference for information
on how to use these modules.
Function Documentation
_case_insensitive_zone_lookup()
pytz._case_insensitive_zone_lookup (zone) protected
case-insensitively matching timezone, else return zone unchanged
Definition at line 201 of file __init__.py.
Referenced by timezone().
_p()
pytz._p (* args) protected
Factory function for unpickling pytz tzinfo instances.
Just a wrapper around tzinfo.unpickler to save a few bytes in each pickle
by shortening the path.
Definition at line 301 of file __init__.py.
_test()
pytz._test () protected
Definition at line 508 of file __init__.py.
_unmunge_zone()
pytz._unmunge_zone (zone) protected
Undo the time zone name munging done by older versions of pytz.
Definition at line 193 of file __init__.py.
Referenced by timezone().
_UTC()
pytz._UTC () protected
Factory function for utc unpickling.
Makes sure that unpickling a utc instance always returns the same
module global.
These examples belong in the UTC class above, but it is obscured; or in
the README.rst, but we are not depending on Python 2.4 so integrating
the README.rst examples with the unit tests is not trivial.
>>> import datetime, pickle
>>> dt = datetime.datetime(2005, 3, 1, 14, 13, 21, tzinfo=utc)
>>> naive = dt.replace(tzinfo=None)
>>> p = pickle.dumps(dt, 1)
>>> naive_p = pickle.dumps(naive, 1)
>>> len(p) - len(naive_p)
17
>>> new = pickle.loads(p)
>>> new == dt
True
>>> new is dt
False
>>> new.tzinfo is dt.tzinfo
True
>>> utc is UTC is timezone('UTC')
True
>>> utc is timezone('GMT')
False
Definition at line 266 of file __init__.py.
ascii()
pytz.ascii (s)
    >>> ascii('Hello')
    'Hello'
    >>> ascii('\N{TRADE MARK SIGN}') #doctest: +IGNORE_EXCEPTION_DETAIL
    Traceback (most recent call last):
        ...
    UnicodeEncodeError: ...
    >>> ascii('Hello')
    'Hello'
    >>> ascii(u'Hello')
    'Hello'
    >>> ascii(u'\N{TRADE MARK SIGN}') #doctest: +IGNORE_EXCEPTION_DETAIL
    Traceback (most recent call last):
        ...
    UnicodeEncodeError: ...
Definition at line 47 of file __init__.py.
Referenced by timezone().
FixedOffset()
pytz.FixedOffset (offset, _tzinfos = {})
return a fixed-offset timezone based off a number of minutes.
    >>> one = FixedOffset(-330)
    >>> one
    pytz.FixedOffset(-330)
    >>> str(one.utcoffset(datetime.datetime.now()))
    '-1 day, 18:30:00'
    >>> str(one.dst(datetime.datetime.now()))
    '0:00:00'
    >>> two = FixedOffset(1380)
    >>> two
    pytz.FixedOffset(1380)
    >>> str(two.utcoffset(datetime.datetime.now()))
    '23:00:00'
    >>> str(two.dst(datetime.datetime.now()))
    '0:00:00'
The datetime.timedelta must be between the range of -1 and 1 day,
non-inclusive.
    >>> FixedOffset(1440)
    Traceback (most recent call last):
    ...
    ValueError: ('absolute offset is too large', 1440)
    >>> FixedOffset(-1440)
    Traceback (most recent call last):
    ...
    ValueError: ('absolute offset is too large', -1440)
An offset of 0 is special-cased to return UTC.
    >>> FixedOffset(0) is UTC
    True
There should always be only one instance of a FixedOffset per timedelta.
This should be true for multiple creation calls.
    >>> FixedOffset(-330) is one
    True
    >>> FixedOffset(1380) is two
    True
It should also be true for pickling.
    >>> import pickle
    >>> pickle.loads(pickle.dumps(one)) is one
    True
    >>> pickle.loads(pickle.dumps(two)) is two
    True
Definition at line 438 of file __init__.py.
References resource_exists().
open_resource()
pytz.open_resource (name)
Open a resource from the zoneinfo subdir for reading.
Uses the pkg_resources module if available and no standard file
found at the calculated location.
It is possible to specify different location for zoneinfo
subdir by using the PYTZ_TZDATADIR environment variable.
Definition at line 78 of file __init__.py.
Referenced by pytz._CountryTimezoneDict.__call__(), resource_exists(), and timezone().
resource_exists()
pytz.resource_exists (name)
Return true if the given resource exists
Definition at line 111 of file __init__.py.
References open_resource().
Referenced by FixedOffset().
timezone()
pytz.timezone (zone)
 Return a datetime.tzinfo implementation for the given timezone
>>> from datetime import datetime, timedelta
>>> utc = timezone('UTC')
>>> eastern = timezone('US/Eastern')
>>> eastern.zone
'US/Eastern'
>>> timezone(unicode('US/Eastern')) is eastern
True
>>> utc_dt = datetime(2002, 10, 27, 6, 0, 0, tzinfo=utc)
>>> loc_dt = utc_dt.astimezone(eastern)
>>> fmt = '%Y-%m-%d %H:%M:%S %Z (%z)'
>>> loc_dt.strftime(fmt)
'2002-10-27 01:00:00 EST (-0500)'
>>> (loc_dt - timedelta(minutes=10)).strftime(fmt)
'2002-10-27 00:50:00 EST (-0500)'
>>> eastern.normalize(loc_dt - timedelta(minutes=10)).strftime(fmt)
'2002-10-27 01:50:00 EDT (-0400)'
>>> (loc_dt + timedelta(minutes=10)).strftime(fmt)
'2002-10-27 01:10:00 EST (-0500)'
Raises UnknownTimeZoneError if passed an unknown zone.
>>> try:
...     timezone('Asia/Shangri-La')
... except UnknownTimeZoneError:
...     print('Unknown')
Unknown
>>> try:
...     timezone(unicode('\N{TRADE MARK SIGN}'))
... except UnknownTimeZoneError:
...     print('Unknown')
Unknown
Definition at line 130 of file __init__.py.
References _case_insensitive_zone_lookup(), _unmunge_zone(), ascii(), and open_resource().
Referenced by pandas.tests.scalar.test_nat._get_overlap_public_nat_methods(), pandas.tests.dtypes.test_dtypes.TestDatetimeTZDtype.dtype(), pandas.tests.resample.test_datetime_index.simple_date_range_series(), matplotlib.tests.test_dates.test_drange(), pandas.tests.indexes.datetimes.test_constructors.TestDatetimeIndex.test_dti_tz_constructors(), pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_examples4(), and pytz.tzinfo.unpickler().
Variable Documentation
__all__
list pytz.__all__ private
Initial value:
=  [
    'timezone', 'utc', 'country_timezones', 'country_names',
    'AmbiguousTimeError', 'InvalidTimeError',
    'NonExistentTimeError', 'UnknownTimeZoneError',
    'all_timezones', 'all_timezones_set',
    'common_timezones', 'common_timezones_set',
    'BaseTzInfo', 'FixedOffset',
]
Definition at line 31 of file __init__.py.
__safe_for_unpickling__
pytz.__safe_for_unpickling__ private
Definition at line 298 of file __init__.py.
__version__
str pytz.__version__ = VERSION private
Definition at line 27 of file __init__.py.
_all_timezones_lower_to_standard
pytz._all_timezones_lower_to_standard = None protected
Definition at line 198 of file __init__.py.
_all_timezones_unchecked
list pytz._all_timezones_unchecked protected
Definition at line 517 of file __init__.py.
_tzinfo_cache
dict pytz._tzinfo_cache = {} protected
Definition at line 127 of file __init__.py.
all_timezones
pytz.all_timezones
Initial value:
=  LazyList(
        tz for tz in _all_timezones_unchecked if resource_exists(tz))
Definition at line 1115 of file __init__.py.
all_timezones_set
pytz.all_timezones_set = LazySet(all_timezones)
Definition at line 1118 of file __init__.py.
common_timezones
pytz.common_timezones
Definition at line 1119 of file __init__.py.
common_timezones_set
pytz.common_timezones_set = LazySet(common_timezones)
Definition at line 1556 of file __init__.py.
country_names
pytz.country_names = _CountryNameDict()
Definition at line 393 of file __init__.py.
country_timezones
pytz.country_timezones = _CountryTimezoneDict()
Definition at line 369 of file __init__.py.
HOUR
pytz.HOUR = datetime.timedelta(hours=1)
Definition at line 210 of file __init__.py.
OLSEN_VERSION
str pytz.OLSEN_VERSION = OLSON_VERSION
Definition at line 29 of file __init__.py.
OLSON_VERSION
str pytz.OLSON_VERSION = '2025b'
Definition at line 25 of file __init__.py.
unicode
pytz.unicode = str
Definition at line 45 of file __init__.py.
UTC
pytz.UTC = UTC()
Definition at line 263 of file __init__.py.
VERSION
str pytz.VERSION = '2025.2'
Definition at line 26 of file __init__.py.
ZERO
pytz.ZERO = datetime.timedelta(0)
Definition at line 209 of file __init__.py.