Code Cloning Analysis: pandas.core.arrays.sparse.accessor.SparseAccessor Class Reference
pandas.core.arrays.sparse.accessor.SparseAccessor Class Reference
Public Member Functions
Series from_coo (cls, A, bool dense_index=False)
to_coo (self, row_levels=(0,), column_levels=(1,), bool sort_labels=False)
Series to_dense (self)
Public Member Functions inherited from pandas.core.arrays.sparse.accessor.BaseAccessor
None __init__ (self, data=None)
Protected Member Functions
_validate (self, data)
_delegate_property_get (self, str name, *args, **kwargs)
_delegate_method (self, str name, *args, **kwargs)
Protected Member Functions inherited from pandas.core.accessor.PandasDelegate
_delegate_property_set (self, str name, value, *args, **kwargs)
None _add_delegate_accessors (cls, delegate, list[str] accessors, str typ, bool overwrite=False, Callable[[str], str] accessor_mapping=lambda x:x, bool raise_on_missing=True)
Additional Inherited Members
Static Public Attributes inherited from pandas.core.arrays.sparse.accessor.BaseAccessor
typ
Protected Attributes inherited from pandas.core.arrays.sparse.accessor.BaseAccessor
_parent = data
Static Protected Attributes inherited from pandas.core.arrays.sparse.accessor.BaseAccessor
str _validation_msg = "Can only use the '.sparse' accessor with Sparse data."
Detailed Description
Accessor for SparseSparse from other sparse matrix data types.
Examples
--------
>>> ser = pd.Series([0, 0, 2, 2, 2], dtype="Sparse[int]")
>>> ser.sparse.density
0.6
>>> ser.sparse.sp_values
array([2, 2, 2])
Definition at line 40 of file accessor.py.
Member Function Documentation
_delegate_method()
pandas.core.arrays.sparse.accessor.SparseAccessor._delegate_method (self, str name, * args, ** kwargs) protected
Reimplemented from pandas.core.accessor.PandasDelegate.
Definition at line 60 of file accessor.py.
_delegate_property_get()
pandas.core.arrays.sparse.accessor.SparseAccessor._delegate_property_get (self, str name, * args, ** kwargs) protected
Reimplemented from pandas.core.accessor.PandasDelegate.
Definition at line 57 of file accessor.py.
_validate()
pandas.core.arrays.sparse.accessor.SparseAccessor._validate (self, data) protected
Reimplemented from pandas.core.arrays.sparse.accessor.BaseAccessor.
Definition at line 53 of file accessor.py.
from_coo()
Series pandas.core.arrays.sparse.accessor.SparseAccessor.from_coo (cls, A, bool dense_index = False)
Create a Series with sparse values from a scipy.sparse.coo_matrix.
Parameters
----------
A : scipy.sparse.coo_matrix
dense_index : bool, default False
    If False (default), the index consists of only the
    coords of the non-null entries of the original coo_matrix.
    If True, the index consists of the full sorted
    (row, col) coordinates of the coo_matrix.
Returns
-------
s : Series
    A Series with sparse values.
Examples
--------
>>> from scipy import sparse
>>> A = sparse.coo_matrix(
...     ([3.0, 1.0, 2.0], ([1, 0, 0], [0, 2, 3])), shape=(3, 4)
...)
>>> A
<COOrdinate sparse matrix of dtype 'float64'
    with 3 stored elements and shape (3, 4)>
>>> A.todense()
matrix([[0., 0., 1., 2.],
[3., 0., 0., 0.],
[0., 0., 0., 0.]])
>>> ss = pd.Series.sparse.from_coo(A)
>>> ss
0  2    1.0
   3    2.0
1  0    3.0
dtype: Sparse[float64, nan]
Definition at line 69 of file accessor.py.
to_coo()
pandas.core.arrays.sparse.accessor.SparseAccessor.to_coo (self, row_levels = (0,), column_levels = (1,), bool sort_labels = False)
Create a scipy.sparse.coo_matrix from a Series with MultiIndex.
Use row_levels and column_levels to determine the row and column
coordinates respectively. row_levels and column_levels are the names
(labels) or numbers of the levels. {row_levels, column_levels} must be
a partition of the MultiIndex level names (or numbers).
Parameters
----------
row_levels : tuple/list
column_levels : tuple/list
sort_labels : bool, default False
    Sort the row and column labels before forming the sparse matrix.
    When `row_levels` and/or `column_levels` refer to a single level,
    set to `True` for a faster execution.
Returns
-------
y : scipy.sparse.coo_matrix
rows : list (row labels)
columns : list (column labels)
Examples
--------
>>> s = pd.Series([3.0, np.nan, 1.0, 3.0, np.nan, np.nan])
>>> s.index = pd.MultiIndex.from_tuples(
...     [
...         (1, 2, "a", 0),
...         (1, 2, "a", 1),
...         (1, 1, "b", 0),
...         (1, 1, "b", 1),
...         (2, 1, "b", 0),
...         (2, 1, "b", 1)
...     ],
...     names=["A", "B", "C", "D"],
...)
>>> s
A  B  C  D
1  2  a  0    3.0
         1    NaN
   1  b  0    1.0
         1    3.0
2  1  b  0    NaN
         1    NaN
dtype: float64
>>> ss = s.astype("Sparse")
>>> ss
A  B  C  D
1  2  a  0    3.0
         1    NaN
   1  b  0    1.0
         1    3.0
2  1  b  0    NaN
         1    NaN
dtype: Sparse[float64, nan]
>>> A, rows, columns = ss.sparse.to_coo(
...     row_levels=["A", "B"], column_levels=["C", "D"], sort_labels=True
...)
>>> A
<COOrdinate sparse matrix of dtype 'float64'
    with 3 stored elements and shape (3, 4)>
>>> A.todense()
matrix([[0., 0., 1., 3.],
[3., 0., 0., 0.],
[0., 0., 0., 0.]])
>>> rows
[(1, 1), (1, 2), (2, 1)]
>>> columns
[('a', 0), ('a', 1), ('b', 0), ('b', 1)]
Definition at line 118 of file accessor.py.
to_dense()
Series pandas.core.arrays.sparse.accessor.SparseAccessor.to_dense (self)
Convert a Series from sparse values to dense.
Returns
-------
Series:
    A Series with the same values, stored as a dense array.
Examples
--------
>>> series = pd.Series(pd.arrays.SparseArray([0, 1, 0]))
>>> series
0    0
1    1
2    0
dtype: Sparse[int64, 0]
>>> series.sparse.to_dense()
0    0
1    1
2    0
dtype: int64
Definition at line 200 of file accessor.py.
Referenced by pandas.core.arrays.sparse.array.SparseArray.argmin(), pandas.core.arrays.sparse.array.SparseArray.cumsum(), and pandas.core.arrays.sparse.array.SparseArray.value_counts().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/core/arrays/sparse/accessor.py