Code Cloning Analysis: numpy.core.arrayprint.DatetimeFormat Class Reference
numpy.core.arrayprint.DatetimeFormat Class Reference
Public Member Functions
__init__ (self, x, unit=None, timezone=None, casting='same_kind', legacy=False)
__call__ (self, x)
Public Member Functions inherited from numpy.core.arrayprint._TimelikeFormat
__init__ (self, data)
__call__ (self, x)
Public Attributes
timezone = timezone
unit = unit
casting = casting
legacy = legacy
Protected Member Functions
_format_non_nat (self, x)
Additional Inherited Members
Protected Attributes inherited from numpy.core.arrayprint._TimelikeFormat
str _format = '%{}s'.format(max_str_len)
str _nat = "'NaT'".rjust(max_str_len)
Detailed Description
Definition at line 1304 of file arrayprint.py.
Constructor & Destructor Documentation
__init__()
numpy.core.arrayprint.DatetimeFormat.__init__ (self, x, unit = None, timezone = None, casting = 'same_kind', legacy = False)
Definition at line 1305 of file arrayprint.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__call__()
numpy.core.arrayprint.DatetimeFormat.__call__ (self, x)
Definition at line 1324 of file arrayprint.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), and scipy.interpolate._fitpack2.SphereBivariateSpline.ev().
_format_non_nat()
numpy.core.arrayprint.DatetimeFormat._format_non_nat (self, x) protected
Reimplemented from numpy.core.arrayprint._TimelikeFormat.
Definition at line 1329 of file arrayprint.py.
Member Data Documentation
casting
numpy.core.arrayprint.DatetimeFormat.casting = casting
Definition at line 1318 of file arrayprint.py.
legacy
numpy.core.arrayprint.DatetimeFormat.legacy = legacy
Definition at line 1319 of file arrayprint.py.
timezone
numpy.core.arrayprint.DatetimeFormat.timezone = timezone
Definition at line 1316 of file arrayprint.py.
unit
numpy.core.arrayprint.DatetimeFormat.unit = unit
Definition at line 1317 of file arrayprint.py.
Referenced by pandas.core.arrays.datetimes.DatetimeArray.__iter__(), pandas.core.dtypes.dtypes.DatetimeTZDtype._creso(), pandas.core.arrays.datetimes.DatetimeArray._from_sequence_not_strict(), pandas.core.arrays.timedeltas.TimedeltaArray._from_sequence_not_strict(), pandas.core.indexes.datetimes.DatetimeIndex._get_time_micros(), pandas.core.arrays.datetimelike.TimelikeOps._validate_frequency(), pandas.core.dtypes.dtypes.DatetimeTZDtype.name(), pandas.core.indexes.datetimelike.DatetimeTimedeltaMixin.shift(), pandas.core.arrays.datetimes.DatetimeArray.tz_convert(), and pandas.core.arrays.datetimes.DatetimeArray.tz_localize().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/core/arrayprint.py