Code Cloning Analysis: fontTools.feaLib.parser.Parser Class Reference
fontTools.feaLib.parser.Parser Class Reference
Public Member Functions
__init__ (self, featurefile, glyphNames=(), followIncludes=True, includeDir=None, **kwargs)
parse (self)
parse_anchor_ (self)
parse_anchor_marks_ (self)
parse_anchordef_ (self)
parse_anonymous_ (self)
parse_attach_ (self)
parse_enumerate_ (self, vertical)
parse_GlyphClassDef_ (self)
parse_glyphclass_definition_ (self)
split_glyph_range_ (self, name, location)
parse_glyphclass_ (self, accept_glyphname, accept_null=False)
parse_glyph_pattern_ (self, vertical)
parse_ignore_glyph_pattern_ (self, sub)
parse_ignore_context_ (self, sub)
parse_ignore_ (self)
parse_include_ (self)
parse_language_ (self)
parse_ligatureCaretByIndex_ (self)
parse_ligatureCaretByPos_ (self)
parse_lookup_ (self, vertical)
parse_lookupflag_ (self)
parse_markClass_ (self)
parse_position_ (self, enumerated, vertical)
parse_position_cursive_ (self, enumerated, vertical)
parse_position_base_ (self, enumerated, vertical)
parse_position_ligature_ (self, enumerated, vertical)
parse_position_mark_ (self, enumerated, vertical)
parse_script_ (self)
parse_substitute_ (self)
parse_subtable_ (self)
parse_size_parameters_ (self)
parse_size_menuname_ (self)
parse_table_ (self)
parse_table_GDEF_ (self, table)
parse_table_head_ (self, table)
parse_table_hhea_ (self, table)
parse_table_vhea_ (self, table)
parse_table_name_ (self, table)
parse_name_ (self)
parse_stat_name_ (self)
parse_nameid_ (self)
unescape_string_ (self, string, encoding)
find_previous (self, statements, class_)
parse_table_BASE_ (self, table)
parse_table_OS_2_ (self, table)
parse_STAT_ElidedFallbackName (self)
parse_STAT_design_axis (self)
parse_STAT_axis_value_ (self)
parse_STAT_location (self)
parse_table_STAT_ (self, table)
parse_base_tag_list_ (self)
parse_base_script_list_ (self, count)
parse_base_script_record_ (self, count)
parse_base_minmax_ (self)
parse_device_ (self)
is_next_value_ (self)
parse_valuerecord_ (self, vertical)
parse_valuerecord_definition_ (self, vertical)
parse_languagesystem_ (self)
parse_feature_block_ (self, variation=False)
parse_feature_reference_ (self)
parse_featureNames_ (self, tag)
parse_cvParameters_ (self, tag)
parse_cvNameIDs_ (self, tag, block_name)
parse_cvCharacter_ (self, tag)
parse_FontRevision_ (self)
parse_conditionset_ (self)
parse_block_ (self, block, vertical, stylisticset=None, size_feature=False, cv_feature=None)
is_cur_keyword_ (self, k)
expect_class_name_ (self)
expect_cid_ (self)
expect_filename_ (self)
expect_glyph_ (self)
check_glyph_name_in_glyph_set (self, *names)
expect_markClass_reference_ (self)
expect_tag_ (self)
expect_script_tag_ (self)
expect_language_tag_ (self)
expect_symbol_ (self, symbol)
expect_keyword_ (self, keyword)
expect_name_ (self)
expect_number_ (self, variable=False)
expect_variable_scalar_ (self)
expect_master_ (self)
expect_any_number_ (self)
expect_float_ (self)
expect_decipoint_ (self)
expect_stat_flags (self)
expect_stat_values_ (self)
expect_string_ (self)
advance_lexer_ (self, comments=False)
make_cid_range_ (self, location, start, limit)
make_glyph_range_ (self, location, start, limit)
Static Public Member Functions
unescape_unichr_ (match)
unescape_byte_ (match, encoding)
reverse_string_ (s)
Public Attributes
glyphNames_ = set(glyphNames)
doc_ = self.ast.FeatureFile()
anchors_ = SymbolTable()
glyphclasses_ = SymbolTable()
lookups_ = SymbolTable()
valuerecords_ = SymbolTable()
dict symbol_tables_ = {self.anchors_, self.valuerecords_}
next_token_type_
tuple next_token_ = (None, None)
list cur_comments_ = []
next_token_location_ = None
lexer_ = lexerClass(featurefile, includeDir=includeDir)
dict missing = {}
str cur_token_ = self.glyphclasses_.resolve(self.cur_token_)
str cur_token_type_ = ";":
list cur_token_location_ = True
Static Public Attributes
dict extensions = {}
ast = ast
dict SS_FEATURE_TAGS = {"ss%02d" % i for i in range(1, 20 + 1)}
dict CV_FEATURE_TAGS = {"cv%02d" % i for i in range(1, 99 + 1)}
Detailed Description
Initializes a Parser object.
Example:
    .. code:: python
        from fontTools.feaLib.parser import Parser
        parser = Parser(file, font.getReverseGlyphMap())
        parsetree = parser.parse()
Note: the ``glyphNames`` iterable serves a double role to help distinguish
glyph names from ranges in the presence of hyphens and to ensure that glyph
names referenced in a feature file are actually part of a font's glyph set.
If the iterable is left empty, no glyph name in glyph set checking takes
place, and all glyph tokens containing hyphens are treated as literal glyph
names, not as ranges. (Adding a space around the hyphen can, in any case,
help to disambiguate ranges from glyph names containing hyphens.)
By default, the parser will follow ``include()`` statements in the feature
file. To turn this off, pass ``followIncludes=False``. Pass a directory string as
``includeDir`` to explicitly declare a directory to search included feature files
in.
Definition at line 15 of file parser.py.
Constructor & Destructor Documentation
__init__()
fontTools.feaLib.parser.Parser.__init__ (self, featurefile, glyphNames = (), followIncludes = True, includeDir = None, ** kwargs)
Definition at line 45 of file parser.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
advance_lexer_()
fontTools.feaLib.parser.Parser.advance_lexer_ (self, comments = False)
Definition at line 2275 of file parser.py.
Referenced by check_glyph_name_in_glyph_set(), parse(), parse_featureNames_(), and parse_name_().
check_glyph_name_in_glyph_set()
fontTools.feaLib.parser.Parser.check_glyph_name_in_glyph_set (self, * names)
Adds a glyph name (just `start`) or glyph names of a
range (`start` and `end`) which are not in the glyph set
to the "missing list" for future error reporting.
If no glyph set is present, does nothing.
Definition at line 2099 of file parser.py.
References advance_lexer_(), ast, cur_comments_, cur_token_, cur_token_location_, cur_token_type_, expect_class_name_(), expect_float_(), expect_master_(), expect_name_(), expect_number_(), expect_tag_(), expect_variable_scalar_(), glyphclasses_, glyphNames_, lexer_, missing, next_token_, next_token_location_, and next_token_type_.
Referenced by parse().
expect_any_number_()
fontTools.feaLib.parser.Parser.expect_any_number_ (self)
Definition at line 2217 of file parser.py.
Referenced by parse_featureNames_(), and parse_name_().
expect_cid_()
fontTools.feaLib.parser.Parser.expect_cid_ (self)
Definition at line 2079 of file parser.py.
Referenced by parse().
expect_class_name_()
fontTools.feaLib.parser.Parser.expect_class_name_ (self)
Definition at line 2073 of file parser.py.
Referenced by check_glyph_name_in_glyph_set(), and parse().
expect_decipoint_()
fontTools.feaLib.parser.Parser.expect_decipoint_ (self)
Definition at line 2233 of file parser.py.
Referenced by parse().
expect_filename_()
fontTools.feaLib.parser.Parser.expect_filename_ (self)
Definition at line 2085 of file parser.py.
Referenced by parse().
expect_float_()
fontTools.feaLib.parser.Parser.expect_float_ (self)
Definition at line 2225 of file parser.py.
Referenced by check_glyph_name_in_glyph_set(), parse_featureNames_(), and parse_name_().
expect_glyph_()
fontTools.feaLib.parser.Parser.expect_glyph_ (self)
Definition at line 2091 of file parser.py.
Referenced by parse().
expect_keyword_()
fontTools.feaLib.parser.Parser.expect_keyword_ (self, keyword)
Definition at line 2160 of file parser.py.
Referenced by parse(), and parse_name_().
expect_language_tag_()
fontTools.feaLib.parser.Parser.expect_language_tag_ (self)
Definition at line 2145 of file parser.py.
Referenced by parse(), and parse_name_().
expect_markClass_reference_()
fontTools.feaLib.parser.Parser.expect_markClass_reference_ (self)
Definition at line 2113 of file parser.py.
Referenced by parse().
expect_master_()
fontTools.feaLib.parser.Parser.expect_master_ (self)
Definition at line 2190 of file parser.py.
Referenced by check_glyph_name_in_glyph_set().
expect_name_()
fontTools.feaLib.parser.Parser.expect_name_ (self)
Definition at line 2166 of file parser.py.
Referenced by check_glyph_name_in_glyph_set(), parse(), parse_featureNames_(), and parse_name_().
expect_number_()
fontTools.feaLib.parser.Parser.expect_number_ (self, variable = False)
Definition at line 2172 of file parser.py.
Referenced by check_glyph_name_in_glyph_set(), parse(), parse_featureNames_(), and parse_name_().
expect_script_tag_()
fontTools.feaLib.parser.Parser.expect_script_tag_ (self)
Definition at line 2136 of file parser.py.
Referenced by parse(), and parse_name_().
expect_stat_flags()
fontTools.feaLib.parser.Parser.expect_stat_flags (self)
Definition at line 2243 of file parser.py.
Referenced by parse_name_().
expect_stat_values_()
fontTools.feaLib.parser.Parser.expect_stat_values_ (self)
Definition at line 2259 of file parser.py.
expect_string_()
fontTools.feaLib.parser.Parser.expect_string_ (self)
Definition at line 2269 of file parser.py.
Referenced by parse_name_().
expect_symbol_()
fontTools.feaLib.parser.Parser.expect_symbol_ (self, symbol)
Definition at line 2154 of file parser.py.
Referenced by parse(), parse_featureNames_(), and parse_name_().
expect_tag_()
fontTools.feaLib.parser.Parser.expect_tag_ (self)
Definition at line 2126 of file parser.py.
Referenced by check_glyph_name_in_glyph_set(), parse(), and parse_name_().
expect_variable_scalar_()
fontTools.feaLib.parser.Parser.expect_variable_scalar_ (self)
Definition at line 2180 of file parser.py.
Referenced by check_glyph_name_in_glyph_set().
find_previous()
fontTools.feaLib.parser.Parser.find_previous (self, statements, class_)
Definition at line 1289 of file parser.py.
Referenced by parse_name_().
is_cur_keyword_()
fontTools.feaLib.parser.Parser.is_cur_keyword_ (self, k)
Definition at line 2065 of file parser.py.
Referenced by parse(), parse_featureNames_(), and parse_name_().
is_next_value_()
fontTools.feaLib.parser.Parser.is_next_value_ (self)
Definition at line 1663 of file parser.py.
Referenced by parse().
make_cid_range_()
fontTools.feaLib.parser.Parser.make_cid_range_ (self, location, start, limit)
(location, 999, 1001) --> ["cid00999", "cid01000", "cid01001"]
Definition at line 2304 of file parser.py.
Referenced by parse().
make_glyph_range_()
fontTools.feaLib.parser.Parser.make_glyph_range_ (self, location, start, limit)
(location, "a.sc", "d.sc") --> ["a.sc", "b.sc", "c.sc", "d.sc"]
Definition at line 2315 of file parser.py.
References reverse_string_().
Referenced by parse().
parse()
fontTools.feaLib.parser.Parser.parse (self)
Parse the file, and return a :class:`fontTools.feaLib.ast.FeatureFile`
object representing the root of the abstract syntax tree containing the
parsed contents of the file.
Definition at line 78 of file parser.py.
References advance_lexer_(), anchors_, ast, check_glyph_name_in_glyph_set(), cur_comments_, cur_token_, cur_token_location_, cur_token_type_, doc_, expect_cid_(), expect_class_name_(), expect_decipoint_(), expect_filename_(), expect_glyph_(), expect_keyword_(), expect_language_tag_(), expect_markClass_reference_(), expect_name_(), expect_number_(), expect_script_tag_(), expect_symbol_(), expect_tag_(), extensions, glyphclasses_, glyphNames_, is_cur_keyword_(), is_next_value_(), lexer_, fontTools.feaLib.builder.Builder.lookups_, lookups_, make_cid_range_(), make_glyph_range_(), missing, next_token_, next_token_location_, next_token_type_, parse_anchor_(), parse_anchor_marks_(), parse_anchordef_(), parse_anonymous_(), parse_attach_(), parse_block_(), parse_conditionset_(), parse_device_(), parse_feature_block_(), parse_FontRevision_(), parse_glyph_pattern_(), parse_glyphclass_(), parse_glyphclass_definition_(), parse_GlyphClassDef_(), parse_ignore_context_(), parse_ignore_glyph_pattern_(), parse_include_(), parse_languagesystem_(), parse_ligatureCaretByIndex_(), parse_ligatureCaretByPos_(), parse_lookup_(), parse_markClass_(), parse_name_(), parse_nameid_(), parse_position_(), parse_position_base_(), parse_position_cursive_(), parse_position_ligature_(), parse_position_mark_(), parse_table_(), parse_table_BASE_(), parse_table_GDEF_(), parse_table_head_(), parse_table_hhea_(), parse_table_name_(), parse_table_OS_2_(), parse_table_STAT_(), parse_table_vhea_(), parse_valuerecord_(), parse_valuerecord_definition_(), and split_glyph_range_().
Referenced by pandas.io.formats.css.CSSResolver.__call__(), fontTools.t1Lib.T1Font.getGlyphSet(), and pip._vendor.rich.style.Style.normalize().
parse_anchor_()
fontTools.feaLib.parser.Parser.parse_anchor_ (self)
Definition at line 141 of file parser.py.
Referenced by parse().
parse_anchor_marks_()
fontTools.feaLib.parser.Parser.parse_anchor_marks_ (self)
Definition at line 195 of file parser.py.
Referenced by parse().
parse_anchordef_()
fontTools.feaLib.parser.Parser.parse_anchordef_ (self)
Definition at line 207 of file parser.py.
Referenced by parse(), and parse_featureNames_().
parse_anonymous_()
fontTools.feaLib.parser.Parser.parse_anonymous_ (self)
Definition at line 224 of file parser.py.
Referenced by parse().
parse_attach_()
fontTools.feaLib.parser.Parser.parse_attach_ (self)
Definition at line 236 of file parser.py.
Referenced by parse().
parse_base_minmax_()
fontTools.feaLib.parser.Parser.parse_base_minmax_ (self)
Definition at line 1629 of file parser.py.
Referenced by parse_name_().
parse_base_script_list_()
fontTools.feaLib.parser.Parser.parse_base_script_list_ (self, count)
Definition at line 1611 of file parser.py.
Referenced by parse_name_().
parse_base_script_record_()
fontTools.feaLib.parser.Parser.parse_base_script_record_ (self, count)
Definition at line 1623 of file parser.py.
Referenced by parse_name_().
parse_base_tag_list_()
fontTools.feaLib.parser.Parser.parse_base_tag_list_ (self)
Definition at line 1599 of file parser.py.
Referenced by parse_name_().
parse_block_()
fontTools.feaLib.parser.Parser.parse_block_ (self, block, vertical, stylisticset = None, size_feature = False, cv_feature = None)
Definition at line 1987 of file parser.py.
Referenced by parse(), and parse_name_().
parse_conditionset_()
fontTools.feaLib.parser.Parser.parse_conditionset_ (self)
Definition at line 1950 of file parser.py.
Referenced by parse().
parse_cvCharacter_()
fontTools.feaLib.parser.Parser.parse_cvCharacter_ (self, tag)
Definition at line 1928 of file parser.py.
Referenced by parse_featureNames_().
parse_cvNameIDs_()
fontTools.feaLib.parser.Parser.parse_cvNameIDs_ (self, tag, block_name)
Definition at line 1892 of file parser.py.
Referenced by parse_featureNames_().
parse_cvParameters_()
fontTools.feaLib.parser.Parser.parse_cvParameters_ (self, tag)
Definition at line 1847 of file parser.py.
Referenced by parse_featureNames_().
parse_device_()
fontTools.feaLib.parser.Parser.parse_device_ (self)
Definition at line 1648 of file parser.py.
Referenced by parse(), and parse_name_().
parse_enumerate_()
fontTools.feaLib.parser.Parser.parse_enumerate_ (self, vertical)
Definition at line 247 of file parser.py.
Referenced by parse_featureNames_().
parse_feature_block_()
fontTools.feaLib.parser.Parser.parse_feature_block_ (self, variation = False)
Definition at line 1767 of file parser.py.
Referenced by parse().
parse_feature_reference_()
fontTools.feaLib.parser.Parser.parse_feature_reference_ (self)
Definition at line 1805 of file parser.py.
Referenced by parse_featureNames_().
parse_featureNames_()
fontTools.feaLib.parser.Parser.parse_featureNames_ (self, tag)
Parses a ``featureNames`` statement found in stylistic set features.
See section `8.c <https://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html#8.c>`_.
Definition at line 1812 of file parser.py.
References advance_lexer_(), ast, cur_comments_, cur_token_, cur_token_location_, cur_token_type_, expect_any_number_(), expect_float_(), expect_name_(), expect_number_(), expect_symbol_(), extensions, is_cur_keyword_(), next_token_, next_token_type_, parse_anchordef_(), parse_cvCharacter_(), parse_cvNameIDs_(), parse_cvParameters_(), parse_enumerate_(), parse_feature_reference_(), parse_featureNames_(), parse_glyphclass_definition_(), parse_ignore_(), parse_language_(), parse_lookup_(), parse_lookupflag_(), parse_markClass_(), parse_name_(), parse_position_(), parse_script_(), parse_size_menuname_(), parse_size_parameters_(), parse_substitute_(), parse_subtable_(), parse_valuerecord_definition_(), and symbol_tables_.
Referenced by parse_featureNames_().
parse_FontRevision_()
fontTools.feaLib.parser.Parser.parse_FontRevision_ (self)
Definition at line 1940 of file parser.py.
Referenced by parse().
parse_glyph_pattern_()
fontTools.feaLib.parser.Parser.parse_glyph_pattern_ (self, vertical)
Definition at line 433 of file parser.py.
Referenced by parse().
parse_glyphclass_()
fontTools.feaLib.parser.Parser.parse_glyphclass_ (self, accept_glyphname, accept_null = False)
Definition at line 333 of file parser.py.
Referenced by parse().
parse_glyphclass_definition_()
fontTools.feaLib.parser.Parser.parse_glyphclass_definition_ (self)
Definition at line 281 of file parser.py.
Referenced by parse(), and parse_featureNames_().
parse_GlyphClassDef_()
fontTools.feaLib.parser.Parser.parse_GlyphClassDef_ (self)
Definition at line 253 of file parser.py.
Referenced by parse().
parse_ignore_()
fontTools.feaLib.parser.Parser.parse_ignore_ (self)
Definition at line 554 of file parser.py.
Referenced by parse_featureNames_().
parse_ignore_context_()
fontTools.feaLib.parser.Parser.parse_ignore_context_ (self, sub)
Definition at line 545 of file parser.py.
Referenced by parse().
parse_ignore_glyph_pattern_()
fontTools.feaLib.parser.Parser.parse_ignore_glyph_pattern_ (self, sub)
Definition at line 526 of file parser.py.
Referenced by parse().
parse_include_()
fontTools.feaLib.parser.Parser.parse_include_ (self)
Definition at line 569 of file parser.py.
Referenced by parse().
parse_language_()
fontTools.feaLib.parser.Parser.parse_language_ (self)
Definition at line 576 of file parser.py.
Referenced by parse_featureNames_().
parse_languagesystem_()
fontTools.feaLib.parser.Parser.parse_languagesystem_ (self)
Definition at line 1759 of file parser.py.
Referenced by parse().
parse_ligatureCaretByIndex_()
fontTools.feaLib.parser.Parser.parse_ligatureCaretByIndex_ (self)
Definition at line 591 of file parser.py.
Referenced by parse().
parse_ligatureCaretByPos_()
fontTools.feaLib.parser.Parser.parse_ligatureCaretByPos_ (self)
Definition at line 601 of file parser.py.
Referenced by parse().
parse_lookup_()
fontTools.feaLib.parser.Parser.parse_lookup_ (self, vertical)
Definition at line 611 of file parser.py.
Referenced by parse(), and parse_featureNames_().
parse_lookupflag_()
fontTools.feaLib.parser.Parser.parse_lookupflag_ (self)
Definition at line 636 of file parser.py.
Referenced by parse_featureNames_().
parse_markClass_()
fontTools.feaLib.parser.Parser.parse_markClass_ (self)
Definition at line 693 of file parser.py.
Referenced by parse(), and parse_featureNames_().
parse_name_()
fontTools.feaLib.parser.Parser.parse_name_ (self)
Parses a name record. See `section 9.e <https://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html#9.e>`_.
Definition at line 1194 of file parser.py.
References advance_lexer_(), ast, cur_comments_, cur_token_, cur_token_location_, cur_token_type_, CV_FEATURE_TAGS, expect_any_number_(), expect_float_(), expect_keyword_(), expect_language_tag_(), expect_name_(), expect_number_(), expect_script_tag_(), expect_stat_flags(), expect_string_(), expect_symbol_(), expect_tag_(), find_previous(), is_cur_keyword_(), next_token_, next_token_location_, next_token_type_, parse_base_minmax_(), parse_base_script_list_(), parse_base_script_record_(), parse_base_tag_list_(), parse_block_(), parse_device_(), parse_name_(), parse_STAT_axis_value_(), parse_STAT_design_axis(), parse_STAT_ElidedFallbackName(), parse_STAT_location(), parse_stat_name_(), parse_valuerecord_(), SS_FEATURE_TAGS, unescape_byte_(), unescape_string_(), unescape_unichr_(), and valuerecords_.
Referenced by parse(), parse_featureNames_(), and parse_name_().
parse_nameid_()
fontTools.feaLib.parser.Parser.parse_nameid_ (self)
Definition at line 1255 of file parser.py.
Referenced by parse().
parse_position_()
fontTools.feaLib.parser.Parser.parse_position_ (self, enumerated, vertical)
Definition at line 715 of file parser.py.
Referenced by parse(), and parse_featureNames_().
parse_position_base_()
fontTools.feaLib.parser.Parser.parse_position_base_ (self, enumerated, vertical)
Definition at line 784 of file parser.py.
Referenced by parse().
parse_position_cursive_()
fontTools.feaLib.parser.Parser.parse_position_cursive_ (self, enumerated, vertical)
Definition at line 768 of file parser.py.
Referenced by parse().
parse_position_ligature_()
fontTools.feaLib.parser.Parser.parse_position_ligature_ (self, enumerated, vertical)
Definition at line 798 of file parser.py.
Referenced by parse().
parse_position_mark_()
fontTools.feaLib.parser.Parser.parse_position_mark_ (self, enumerated, vertical)
Definition at line 815 of file parser.py.
Referenced by parse().
parse_script_()
fontTools.feaLib.parser.Parser.parse_script_ (self)
Definition at line 829 of file parser.py.
Referenced by parse_featureNames_().
parse_size_menuname_()
fontTools.feaLib.parser.Parser.parse_size_menuname_ (self)
Definition at line 1045 of file parser.py.
Referenced by parse_featureNames_().
parse_size_parameters_()
fontTools.feaLib.parser.Parser.parse_size_parameters_ (self)
Definition at line 1027 of file parser.py.
Referenced by parse_featureNames_().
parse_STAT_axis_value_()
fontTools.feaLib.parser.Parser.parse_STAT_axis_value_ (self)
Definition at line 1469 of file parser.py.
Referenced by parse_name_().
parse_STAT_design_axis()
fontTools.feaLib.parser.Parser.parse_STAT_design_axis (self)
Definition at line 1435 of file parser.py.
Referenced by parse_name_().
parse_STAT_ElidedFallbackName()
fontTools.feaLib.parser.Parser.parse_STAT_ElidedFallbackName (self)
Definition at line 1407 of file parser.py.
Referenced by parse_name_().
parse_STAT_location()
fontTools.feaLib.parser.Parser.parse_STAT_location (self)
Definition at line 1525 of file parser.py.
Referenced by parse_name_().
parse_stat_name_()
fontTools.feaLib.parser.Parser.parse_stat_name_ (self)
Definition at line 1226 of file parser.py.
Referenced by parse_name_().
parse_substitute_()
fontTools.feaLib.parser.Parser.parse_substitute_ (self)
Definition at line 835 of file parser.py.
Referenced by parse_featureNames_().
parse_subtable_()
fontTools.feaLib.parser.Parser.parse_subtable_ (self)
Definition at line 1021 of file parser.py.
Referenced by parse_featureNames_().
parse_table_()
fontTools.feaLib.parser.Parser.parse_table_ (self)
Definition at line 1053 of file parser.py.
Referenced by parse().
parse_table_BASE_()
fontTools.feaLib.parser.Parser.parse_table_BASE_ (self, table)
Definition at line 1302 of file parser.py.
Referenced by parse().
parse_table_GDEF_()
fontTools.feaLib.parser.Parser.parse_table_GDEF_ (self, table)
Definition at line 1083 of file parser.py.
Referenced by parse().
parse_table_head_()
fontTools.feaLib.parser.Parser.parse_table_head_ (self, table)
Definition at line 1107 of file parser.py.
Referenced by parse().
parse_table_hhea_()
fontTools.feaLib.parser.Parser.parse_table_hhea_ (self, table)
Definition at line 1122 of file parser.py.
Referenced by parse().
parse_table_name_()
fontTools.feaLib.parser.Parser.parse_table_name_ (self, table)
Definition at line 1177 of file parser.py.
Referenced by parse().
parse_table_OS_2_()
fontTools.feaLib.parser.Parser.parse_table_OS_2_ (self, table)
Definition at line 1363 of file parser.py.
Referenced by parse().
parse_table_STAT_()
fontTools.feaLib.parser.Parser.parse_table_STAT_ (self, table)
Definition at line 1558 of file parser.py.
Referenced by parse().
parse_table_vhea_()
fontTools.feaLib.parser.Parser.parse_table_vhea_ (self, table)
Definition at line 1149 of file parser.py.
Referenced by parse().
parse_valuerecord_()
fontTools.feaLib.parser.Parser.parse_valuerecord_ (self, vertical)
Definition at line 1670 of file parser.py.
Referenced by parse(), and parse_name_().
parse_valuerecord_definition_()
fontTools.feaLib.parser.Parser.parse_valuerecord_definition_ (self, vertical)
Definition at line 1748 of file parser.py.
Referenced by parse(), and parse_featureNames_().
reverse_string_()
fontTools.feaLib.parser.Parser.reverse_string_ (s) static
'abc' --> 'cba'
Definition at line 2300 of file parser.py.
Referenced by make_glyph_range_().
split_glyph_range_()
fontTools.feaLib.parser.Parser.split_glyph_range_ (self, name, location)
Definition at line 291 of file parser.py.
Referenced by parse().
unescape_byte_()
fontTools.feaLib.parser.Parser.unescape_byte_ (match, encoding) static
Definition at line 1285 of file parser.py.
Referenced by parse_name_().
unescape_string_()
fontTools.feaLib.parser.Parser.unescape_string_ (self, string, encoding)
Definition at line 1267 of file parser.py.
Referenced by parse_name_().
unescape_unichr_()
fontTools.feaLib.parser.Parser.unescape_unichr_ (match) static
Definition at line 1280 of file parser.py.
Referenced by parse_name_().
Member Data Documentation
anchors_
fontTools.feaLib.parser.Parser.anchors_ = SymbolTable()
Definition at line 65 of file parser.py.
Referenced by parse().
ast
fontTools.feaLib.parser.Parser.ast = ast static
Definition at line 41 of file parser.py.
Referenced by check_glyph_name_in_glyph_set(), parse(), parse_featureNames_(), and parse_name_().
cur_comments_
list fontTools.feaLib.parser.Parser.cur_comments_ = []
Definition at line 71 of file parser.py.
Referenced by check_glyph_name_in_glyph_set(), parse(), parse_featureNames_(), and parse_name_().
cur_token_
fontTools.feaLib.parser.Parser.cur_token_ = self.glyphclasses_.resolve(self.cur_token_)
Definition at line 87 of file parser.py.
Referenced by check_glyph_name_in_glyph_set(), parse(), parse_featureNames_(), and parse_name_().
cur_token_location_
fontTools.feaLib.parser.Parser.cur_token_location_ = True
Definition at line 126 of file parser.py.
Referenced by check_glyph_name_in_glyph_set(), parse(), parse_featureNames_(), and parse_name_().
cur_token_type_
fontTools.feaLib.parser.Parser.cur_token_type_ = ";":
Definition at line 124 of file parser.py.
Referenced by check_glyph_name_in_glyph_set(), parse(), parse_featureNames_(), and parse_name_().
CV_FEATURE_TAGS
dict fontTools.feaLib.parser.Parser.CV_FEATURE_TAGS = {"cv%02d" % i for i in range(1, 99 + 1)} static
Definition at line 43 of file parser.py.
Referenced by parse_name_().
doc_
fontTools.feaLib.parser.Parser.doc_ = self.ast.FeatureFile()
Definition at line 64 of file parser.py.
Referenced by parse().
extensions
dict fontTools.feaLib.parser.Parser.extensions = {} static
Definition at line 40 of file parser.py.
Referenced by parse(), and parse_featureNames_().
glyphclasses_
fontTools.feaLib.parser.Parser.glyphclasses_ = SymbolTable()
Definition at line 66 of file parser.py.
Referenced by check_glyph_name_in_glyph_set(), and parse().
glyphNames_
fontTools.feaLib.parser.Parser.glyphNames_ = set(glyphNames)
Definition at line 63 of file parser.py.
Referenced by check_glyph_name_in_glyph_set(), and parse().
lexer_
fontTools.feaLib.parser.Parser.lexer_ = lexerClass(featurefile, includeDir=includeDir)
Definition at line 74 of file parser.py.
Referenced by check_glyph_name_in_glyph_set(), and parse().
lookups_
fontTools.feaLib.parser.Parser.lookups_ = SymbolTable()
Definition at line 67 of file parser.py.
Referenced by parse().
missing
dict fontTools.feaLib.parser.Parser.missing = {}
Definition at line 75 of file parser.py.
Referenced by pip._vendor.distlib.database.DependencyGraph.add_missing(), check_glyph_name_in_glyph_set(), and parse().
next_token_
fontTools.feaLib.parser.Parser.next_token_ = (None, None)
Definition at line 70 of file parser.py.
Referenced by check_glyph_name_in_glyph_set(), parse(), parse_featureNames_(), and parse_name_().
next_token_location_
fontTools.feaLib.parser.Parser.next_token_location_ = None
Definition at line 72 of file parser.py.
Referenced by check_glyph_name_in_glyph_set(), parse(), and parse_name_().
next_token_type_
fontTools.feaLib.parser.Parser.next_token_type_
Initial value:
=  (
                self.next_token_type_,
                self.next_token_,
                self.next_token_location_,
            )
Definition at line 70 of file parser.py.
Referenced by check_glyph_name_in_glyph_set(), parse(), parse_featureNames_(), and parse_name_().
SS_FEATURE_TAGS
dict fontTools.feaLib.parser.Parser.SS_FEATURE_TAGS = {"ss%02d" % i for i in range(1, 20 + 1)} static
Definition at line 42 of file parser.py.
Referenced by parse_name_().
symbol_tables_
dict fontTools.feaLib.parser.Parser.symbol_tables_ = {self.anchors_, self.valuerecords_}
Definition at line 69 of file parser.py.
Referenced by parse_featureNames_().
valuerecords_
fontTools.feaLib.parser.Parser.valuerecords_ = SymbolTable()
Definition at line 68 of file parser.py.
Referenced by parse_name_().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/feaLib/parser.py