Code Cloning Analysis: fontTools.ttLib.tables._c_m_a_p.cmap_format_12 Class Reference
fontTools.ttLib.tables._c_m_a_p.cmap_format_12 Class Reference
Public Member Functions
__init__ (self, format=12)
Public Member Functions inherited from fontTools.ttLib.tables._c_m_a_p.cmap_format_12_or_13
__init__ (self, format)
decompileHeader (self, data, ttFont)
decompile (self, data, ttFont)
compile (self, ttFont)
toXML (self, writer, ttFont)
fromXML (self, name, attrs, content, ttFont)
Public Member Functions inherited from fontTools.ttLib.tables._c_m_a_p.CmapSubtable
__init__ (self, format)
ensureDecompiled (self, recurse=False)
__getattr__ (self, attr)
getEncoding (self, default=None)
isUnicode (self)
isSymbol (self)
__lt__ (self, other)
Protected Member Functions
_computeGIDs (self, startingGlyph, numberOfGlyphs)
_IsInSameRun (self, glyphID, lastGlyphID, charCode, lastCharCode)
Protected Member Functions inherited from fontTools.ttLib.tables._c_m_a_p.CmapSubtable
_writeCodes (self, codes, writer)
Static Protected Attributes
int _format_step = 1
Additional Inherited Members
Static Public Member Functions inherited from fontTools.ttLib.tables._c_m_a_p.CmapSubtable
getSubtableClass (format)
newSubtable (format)
Public Attributes inherited from fontTools.ttLib.tables._c_m_a_p.cmap_format_12_or_13
int reserved = 0
nGroups = nGroups
dict cmap = _make_map(self.ttFont, charCodes, gids)
Public Attributes inherited from fontTools.ttLib.tables._c_m_a_p.CmapSubtable
format = format
data = None
ttFont = None
int platformID = None
platEncID = None
tuple language
length = int(length)
Detailed Description
Definition at line 1308 of file _c_m_a_p.py.
Constructor & Destructor Documentation
__init__()
fontTools.ttLib.tables._c_m_a_p.cmap_format_12.__init__ (self, format = 12)
Definition at line 1311 of file _c_m_a_p.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_computeGIDs()
fontTools.ttLib.tables._c_m_a_p.cmap_format_12._computeGIDs (self, startingGlyph, numberOfGlyphs) protected
Definition at line 1314 of file _c_m_a_p.py.
_IsInSameRun()
fontTools.ttLib.tables._c_m_a_p.cmap_format_12._IsInSameRun (self, glyphID, lastGlyphID, charCode, lastCharCode) protected
Definition at line 1317 of file _c_m_a_p.py.
Member Data Documentation
_format_step
int fontTools.ttLib.tables._c_m_a_p.cmap_format_12._format_step = 1 static protected
Definition at line 1309 of file _c_m_a_p.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ttLib/tables/_c_m_a_p.py