Code Cloning Analysis: matplotlib.animation.ArtistAnimation Class Reference
matplotlib.animation.ArtistAnimation Class Reference
Public Member Functions
__init__ (self, fig, artists, *args, **kwargs)
Public Member Functions inherited from matplotlib.animation.TimedAnimation
__init__ (self, fig, interval=200, repeat_delay=0, repeat=True, event_source=None, *args, **kwargs)
Public Member Functions inherited from matplotlib.animation.Animation
__init__ (self, fig, event_source=None, blit=False)
__del__ (self)
save (self, filename, writer=None, fps=None, dpi=None, codec=None, bitrate=None, extra_args=None, metadata=None, extra_anim=None, savefig_kwargs=None, *, progress_callback=None)
new_frame_seq (self)
new_saved_frame_seq (self)
to_html5_video (self, embed_limit=None)
to_jshtml (self, fps=None, embed_frames=True, default_mode=None)
pause (self)
resume (self)
Protected Member Functions
_init_draw (self)
_pre_draw (self, framedata, blit)
_draw_frame (self, artists)
Protected Member Functions inherited from matplotlib.animation.TimedAnimation
_step (self, *args)
Protected Member Functions inherited from matplotlib.animation.Animation
_start (self, *args)
_stop (self, *args)
_draw_next_frame (self, framedata, blit)
_post_draw (self, framedata, blit)
_blit_draw (self, artists)
_blit_clear (self, artists)
_setup_blit (self)
_on_resize (self, event)
_end_redraw (self, event)
_repr_html_ (self)
Additional Inherited Members
Public Attributes inherited from matplotlib.animation.Animation
frame_seq = self.new_frame_seq()
event_source = event_source
Protected Attributes inherited from matplotlib.animation.TimedAnimation
_interval = interval
int _repeat_delay = repeat_delay if repeat_delay is not None else 0
_repeat = repeat
Protected Attributes inherited from matplotlib.animation.Animation
bool _draw_was_started = False
_fig = fig
_blit = blit and fig.canvas.supports_blit
_first_draw_id = fig.canvas.mpl_connect('draw_event', self._start)
_close_id
_resize_id
_framedata
list _drawn_artists
_blit_cache = dict()
_base64_video = vid64.decode('ascii')
str _video_size
_html_representation = path.read_text()
Detailed Description
`TimedAnimation` subclass that creates an animation by using a fixed
set of `.Artist` objects.
Before creating an instance, all plotting should have taken place
and the relevant artists saved.
.. note::
    You must store the created Animation in a variable that lives as long
    as the animation should run. Otherwise, the Animation object will be
    garbage-collected and the animation stops.
Parameters
----------
fig : `~matplotlib.figure.Figure`
    The figure object used to get needed events, such as draw or resize.
artists : list
    Each list entry is a collection of `.Artist` objects that are made
    visible on the corresponding frame.  Other artists are made invisible.
interval : int, default: 200
    Delay between frames in milliseconds.
repeat_delay : int, default: 0
    The delay in milliseconds between consecutive animation runs, if
    *repeat* is True.
repeat : bool, default: True
    Whether the animation repeats when the sequence of frames is completed.
blit : bool, default: False
    Whether blitting is used to optimize drawing.
Definition at line 1473 of file animation.py.
Constructor & Destructor Documentation
__init__()
matplotlib.animation.ArtistAnimation.__init__ (self, fig, artists, * args, ** kwargs)
Definition at line 1505 of file animation.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_draw_frame()
matplotlib.animation.ArtistAnimation._draw_frame (self, artists) protected
Reimplemented from matplotlib.animation.Animation.
Definition at line 1540 of file animation.py.
_init_draw()
matplotlib.animation.ArtistAnimation._init_draw (self) protected
Reimplemented from matplotlib.animation.Animation.
Definition at line 1514 of file animation.py.
_pre_draw()
matplotlib.animation.ArtistAnimation._pre_draw (self, framedata, blit) protected
Clears artists from the last frame.
Reimplemented from matplotlib.animation.Animation.
Definition at line 1530 of file animation.py.
References matplotlib.animation.Animation._blit_clear(), and matplotlib.animation.Animation._drawn_artists.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/animation.py