Code Cloning Analysis: numpy.ma.testutils Namespace Reference
numpy.ma.testutils Namespace Reference
Functions
approx (a, b, fill_value=True, rtol=1e-5, atol=1e-8)
almost (a, b, decimal=6, fill_value=True)
_assert_equal_on_sequences (actual, desired, err_msg='')
assert_equal_records (a, b)
assert_equal (actual, desired, err_msg='')
fail_if_equal (actual, desired, err_msg='')
assert_almost_equal (actual, desired, decimal=7, err_msg='', verbose=True)
assert_array_compare (comparison, x, y, err_msg='', verbose=True, header='', fill_value=True)
assert_array_equal (x, y, err_msg='', verbose=True)
fail_if_array_equal (x, y, err_msg='', verbose=True)
assert_array_approx_equal (x, y, decimal=6, err_msg='', verbose=True)
assert_array_almost_equal (x, y, decimal=6, err_msg='', verbose=True)
assert_array_less (x, y, err_msg='', verbose=True)
assert_mask_equal (m1, m2, err_msg='')
Variables
list __all__masked
list __some__from_testing
list __all__ = __all__masked + __some__from_testing
assert_not_equal = fail_if_equal
assert_close = assert_almost_equal
Detailed Description
Miscellaneous functions for testing masked arrays and subclasses
:author: Pierre Gerard-Marchant
:contact: pierregm_at_uga_dot_edu
:version: $Id: testutils.py 3529 2007-11-13 08:01:14Z jarrod.millman $
Function Documentation
_assert_equal_on_sequences()
numpy.ma.testutils._assert_equal_on_sequences (actual, desired, err_msg = '') protected
Asserts the equality of two non-array sequences.
Definition at line 82 of file testutils.py.
References assert_equal().
Referenced by assert_equal().
almost()
numpy.ma.testutils.almost (a, b, decimal = 6, fill_value = True)
Returns True if a and b are equal up to decimal places.
If fill_value is True, masked values considered equal. Otherwise,
masked values are considered unequal.
Definition at line 63 of file testutils.py.
References numpy.ma.core.filled(), numpy.ma.core.getmask(), and numpy.ma.core.mask_or().
Referenced by assert_array_almost_equal().
approx()
numpy.ma.testutils.approx (a, b, fill_value = True, rtol = 1e-5, atol = 1e-8)
Returns true if all components of a and b are equal to given tolerances.
If fill_value is True, masked values considered equal. Otherwise,
masked values are considered unequal.  The relative error rtol should
be positive and << 1.0 The absolute error atol comes into play for
those elements of b that are very small or zero; it says how small a
must be also.
Definition at line 41 of file testutils.py.
References numpy.ma.core.filled(), numpy.ma.core.getmask(), and numpy.ma.core.mask_or().
Referenced by assert_array_approx_equal(), and fail_if_array_equal().
assert_almost_equal()
numpy.ma.testutils.assert_almost_equal (actual, desired, decimal = 7, err_msg = '', verbose = True)
Asserts that two items are almost equal.
The test is equivalent to abs(desired-actual) < 0.5 * 10**(-decimal).
Definition at line 176 of file testutils.py.
References assert_array_almost_equal().
assert_array_almost_equal()
numpy.ma.testutils.assert_array_almost_equal (x, y, decimal = 6, err_msg = '', verbose = True)
Checks the equality of two masked arrays, up to given number odecimals.
The equality is checked elementwise.
Definition at line 255 of file testutils.py.
References almost(), and assert_array_compare().
Referenced by assert_almost_equal().
assert_array_approx_equal()
numpy.ma.testutils.assert_array_approx_equal (x, y, decimal = 6, err_msg = '', verbose = True)
Checks the equality of two masked arrays, up to given number odecimals.
The equality is checked elementwise.
Definition at line 241 of file testutils.py.
References approx(), and assert_array_compare().
assert_array_compare()
numpy.ma.testutils.assert_array_compare (comparison, x, y, err_msg = '', verbose = True, header = '', fill_value = True)
Asserts that comparison between two masked arrays is satisfied.
The comparison is elementwise.
Definition at line 195 of file testutils.py.
References numpy.ma.core.getmask(), and numpy.ma.core.mask_or().
Referenced by assert_array_almost_equal(), assert_array_approx_equal(), assert_array_equal(), assert_array_less(), and fail_if_array_equal().
assert_array_equal()
numpy.ma.testutils.assert_array_equal (x, y, err_msg = '', verbose = True)
Checks the elementwise equality of two masked arrays.
Definition at line 220 of file testutils.py.
References assert_array_compare().
Referenced by assert_equal(), and assert_mask_equal().
assert_array_less()
numpy.ma.testutils.assert_array_less (x, y, err_msg = '', verbose = True)
Checks that x is smaller than y elementwise.
Definition at line 269 of file testutils.py.
References assert_array_compare().
assert_equal()
numpy.ma.testutils.assert_equal (actual, desired, err_msg = '')
Asserts that two items are equal.
Definition at line 108 of file testutils.py.
References _assert_equal_on_sequences(), assert_array_equal(), and assert_equal().
Referenced by _assert_equal_on_sequences(), assert_equal(), and assert_equal_records().
assert_equal_records()
numpy.ma.testutils.assert_equal_records (a, b)
Asserts that two records are equal.
Pretty crude for now.
Definition at line 93 of file testutils.py.
References assert_equal().
assert_mask_equal()
numpy.ma.testutils.assert_mask_equal (m1, m2, err_msg = '')
Asserts the equality of two masks.
Definition at line 279 of file testutils.py.
References assert_array_equal().
fail_if_array_equal()
numpy.ma.testutils.fail_if_array_equal (x, y, err_msg = '', verbose = True)
Raises an assertion error if two masked arrays are not equal elementwise.
Definition at line 230 of file testutils.py.
References approx(), and assert_array_compare().
Referenced by fail_if_equal().
fail_if_equal()
numpy.ma.testutils.fail_if_equal (actual, desired, err_msg = '')
Raises an assertion error if two items are equal.
Definition at line 147 of file testutils.py.
References fail_if_array_equal(), and fail_if_equal().
Referenced by fail_if_equal().
Variable Documentation
__all__
list numpy.ma.testutils.__all__ = __all__masked + __some__from_testing private
Definition at line 38 of file testutils.py.
__all__masked
list numpy.ma.testutils.__all__masked private
Initial value:
=  [
    'almost', 'approx', 'assert_almost_equal', 'assert_array_almost_equal',
    'assert_array_approx_equal', 'assert_array_compare',
    'assert_array_equal', 'assert_array_less', 'assert_close',
    'assert_equal', 'assert_equal_records', 'assert_mask_equal',
    'assert_not_equal', 'fail_if_array_equal',
    ]
Definition at line 20 of file testutils.py.
__some__from_testing
list numpy.ma.testutils.__some__from_testing private
Initial value:
=  [
    'TestCase', 'assert_', 'assert_allclose', 'assert_array_almost_equal_nulp',
    'assert_raises'
    ]
Definition at line 33 of file testutils.py.
assert_close
numpy.ma.testutils.assert_close = assert_almost_equal
Definition at line 192 of file testutils.py.
assert_not_equal
numpy.ma.testutils.assert_not_equal = fail_if_equal
Definition at line 173 of file testutils.py.