Code Cloning Analysis: numpy.random.tests.test_random.TestSetState Class Reference
numpy.random.tests.test_random.TestSetState Class Reference
Public Member Functions
setup_method (self)
test_basic (self)
test_gaussian_reset (self)
test_gaussian_reset_in_media_res (self)
test_backwards_compatibility (self)
test_negative_binomial (self)
test_set_invalid_state (self)
Public Attributes
int seed = 1234567890
prng = random.RandomState(self.seed)
state = self.prng.get_state()
Detailed Description
Definition at line 103 of file test_random.py.
Member Function Documentation
setup_method()
numpy.random.tests.test_random.TestSetState.setup_method (self)
Definition at line 104 of file test_random.py.
test_backwards_compatibility()
numpy.random.tests.test_random.TestSetState.test_backwards_compatibility (self)
Definition at line 133 of file test_random.py.
test_basic()
numpy.random.tests.test_random.TestSetState.test_basic (self)
Definition at line 109 of file test_random.py.
test_gaussian_reset()
numpy.random.tests.test_random.TestSetState.test_gaussian_reset (self)
Definition at line 115 of file test_random.py.
test_gaussian_reset_in_media_res()
numpy.random.tests.test_random.TestSetState.test_gaussian_reset_in_media_res (self)
Definition at line 122 of file test_random.py.
test_negative_binomial()
numpy.random.tests.test_random.TestSetState.test_negative_binomial (self)
Definition at line 145 of file test_random.py.
test_set_invalid_state()
numpy.random.tests.test_random.TestSetState.test_set_invalid_state (self)
Definition at line 150 of file test_random.py.
Member Data Documentation
prng
numpy.random.tests.test_random.TestSetState.prng = random.RandomState(self.seed)
Definition at line 106 of file test_random.py.
seed
int numpy.random.tests.test_random.TestSetState.seed = 1234567890
Definition at line 105 of file test_random.py.
state
numpy.random.tests.test_random.TestSetState.state = self.prng.get_state()
Definition at line 107 of file test_random.py.
Referenced by pip._vendor.resolvelib.resolvers.Resolution._backjump(), PIL.PpmImagePlugin.PpmPlainDecoder._decode_bitonal(), pip._vendor.resolvelib.resolvers.Resolution._remove_information_from_criteria(), PIL.DdsImagePlugin.DdsRgbDecoder.decode(), PIL.FitsImagePlugin.FitsGzipDecoder.decode(), PIL.MspImagePlugin.MspDecoder.decode(), PIL.PpmImagePlugin.PpmDecoder.decode(), PIL.QoiImagePlugin.QoiDecoder.decode(), PIL.SgiImagePlugin.SGI16Decoder.decode(), PIL.XpmImagePlugin.XpmDecoder.decode(), PIL.ImageFile.PyDecoder.set_as_raw(), PIL.ImageFile.PyCodec.setimage(), and pip._vendor.chardet.utf1632prober.UTF1632Prober.validate_utf16_characters().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/random/tests/test_random.py