Code Cloning Analysis: matplotlib.tests.test_ticker.TestLogFormatterMathtext Class Reference
matplotlib.tests.test_ticker.TestLogFormatterMathtext Class Reference
Public Member Functions
test_min_exponent (self, min_exponent, value, expected)
Static Public Attributes
fmt = mticker.LogFormatterMathtext()
list test_data
Detailed Description
Definition at line 995 of file test_ticker.py.
Member Function Documentation
test_min_exponent()
matplotlib.tests.test_ticker.TestLogFormatterMathtext.test_min_exponent (self, min_exponent, value, expected)
Definition at line 1009 of file test_ticker.py.
Member Data Documentation
fmt
matplotlib.tests.test_ticker.TestLogFormatterMathtext.fmt = mticker.LogFormatterMathtext() static
Definition at line 996 of file test_ticker.py.
Referenced by matplotlib.ticker.FormatStrFormatter.__call__(), matplotlib.ticker.StrMethodFormatter.__call__(), pandas.io.formats.format.DataFrameRenderer.to_csv(), pandas.io.formats.format.DataFrameRenderer.to_html(), pandas.io.formats.format.DataFrameRenderer.to_string(), and pandas.io.formats.html.HTMLFormatter.write_th().
test_data
list matplotlib.tests.test_ticker.TestLogFormatterMathtext.test_data static
Initial value:
=  [
        (0, 1, '$\\mathdefault{10^{0}}$'),
        (0, 1e-2, '$\\mathdefault{10^{-2}}$'),
        (0, 1e2, '$\\mathdefault{10^{2}}$'),
        (3, 1, '$\\mathdefault{1}$'),
        (3, 1e-2, '$\\mathdefault{0.01}$'),
        (3, 1e2, '$\\mathdefault{100}$'),
        (3, 1e-3, '$\\mathdefault{10^{-3}}$'),
        (3, 1e3, '$\\mathdefault{10^{3}}$'),
    ]
Definition at line 997 of file test_ticker.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/tests/test_ticker.py