Code Cloning Analysis: pandas.io.parsers.python_parser.FixedWidthFieldParser Class Reference
pandas.io.parsers.python_parser.FixedWidthFieldParser Class Reference
Public Member Functions
None __init__ (self, ReadCsvBuffer[str] f, **kwds)
Public Member Functions inherited from pandas.io.parsers.python_parser.PythonParser
None __init__ (self, ReadCsvBuffer[str]|list f, **kwds)
re.Pattern num (self)
tuple[ Index|None, Sequence[Hashable]|MultiIndex, Mapping[Hashable, ArrayLike]] read (self, int|None rows=None)
tuple[ Index|None, Sequence[Hashable]|MultiIndex, Mapping[Hashable, ArrayLike]] get_chunk (self, int|None size=None)
Public Member Functions inherited from pandas.io.parsers.base_parser.ParserBase
None __init__ (self, kwds)
None close (self)
Public Attributes
colspecs = kwds.pop("colspecs")
infer_nrows = kwds.pop("infer_nrows")
Public Attributes inherited from pandas.io.parsers.python_parser.PythonParser
Iterator[str]|None data = None
list buf = []
int pos = 0
int line_pos = 0
skiprows = kwds["skiprows"]
skipfunc = self.skiprows
skipfooter = _validate_skipfooter_arg(kwds["skipfooter"])
delimiter = kwds["delimiter"]
quotechar = kwds["quotechar"]
escapechar = kwds["escapechar"]
doublequote = kwds["doublequote"]
skipinitialspace = kwds["skipinitialspace"]
lineterminator = kwds["lineterminator"]
quoting = kwds["quoting"]
skip_blank_lines = kwds["skip_blank_lines"]
bool has_index_names = False
verbose = kwds["verbose"]
thousands = kwds["thousands"]
decimal = kwds["decimal"]
comment = kwds["comment"]
num_original_columns
columns
Public Attributes inherited from pandas.io.parsers.base_parser.ParserBase
names = kwds.get("names")
Sequence[Hashable]|None orig_names = None
list index_col = kwds.get("index_col", None)
set unnamed_cols = set()
Sequence[Hashable]|None index_names = None
Sequence[Hashable]|None col_names = None
parse_dates = _validate_parse_dates_arg(kwds.pop("parse_dates", False))
date_parser = kwds.pop("date_parser", lib.no_default)
date_format = kwds.pop("date_format", None)
dayfirst = kwds.pop("dayfirst", False)
keep_date_col = kwds.pop("keep_date_col", False)
na_values = kwds.get("na_values")
na_fvalues = kwds.get("na_fvalues")
na_filter = kwds.get("na_filter", False)
keep_default_na = kwds.get("keep_default_na", True)
dtype = copy(kwds.get("dtype", None))
converters = kwds.get("converters")
dtype_backend = kwds.get("dtype_backend")
true_values = kwds.get("true_values")
false_values = kwds.get("false_values")
cache_dates = kwds.pop("cache_dates", True)
header = kwds.get("header")
usecols = sorted(self.usecols)
on_bad_lines = kwds.get("on_bad_lines", self.BadLineHandleMethod.ERROR)
Protected Member Functions
FixedWidthReader _make_reader (self, IO[str]|ReadCsvBuffer[str] f)
list[list[Scalar]] _remove_empty_lines (self, list[list[Scalar]] lines)
Protected Member Functions inherited from pandas.io.parsers.python_parser.PythonParser
tuple[Mapping[Hashable, np.ndarray], Sequence[Hashable]] _exclude_implicit_index (self, list[np.ndarray] alldata)
Mapping[Hashable, ArrayLike] _convert_data (self, Mapping[Hashable, np.ndarray] data)
bool _have_mi_columns (self)
tuple[list[list[Scalar|None]], int, set[Scalar|None]] _infer_columns (self)
_header_line (self)
list[list[Scalar|None]] _handle_usecols (self, list[list[Scalar|None]] columns, list[Scalar|None] usecols_key, int num_original_columns)
list[Scalar] _buffered_line (self)
list[Scalar] _check_for_bom (self, list[Scalar] first_row)
bool _is_line_empty (self, list[Scalar] line)
list[Scalar] _next_line (self)
None _alert_malformed (self, str msg, int row_num)
list[Scalar]|None _next_iter_line (self, int row_num)
list[list[Scalar]] _check_comments (self, list[list[Scalar]] lines)
list[list[Scalar]] _check_thousands (self, list[list[Scalar]] lines)
list[list[Scalar]] _search_replace_num_columns (self, list[list[Scalar]] lines, str search, str replace)
list[list[Scalar]] _check_decimal (self, list[list[Scalar]] lines)
None _clear_buffer (self)
tuple[Sequence[Hashable]|None, list[Hashable], list[Hashable]] _get_index_name (self)
list[np.ndarray] _rows_to_cols (self, list[list[Scalar]] content)
list[list[Scalar]] _get_lines (self, int|None rows=None)
list[list[Scalar]] _remove_skipped_rows (self, list[list[Scalar]] new_rows)
set[int] _set_no_thousand_columns (self)
Protected Member Functions inherited from pandas.io.parsers.base_parser.ParserBase
Iterable _validate_parse_dates_presence (self, Sequence[Hashable] columns)
bool _has_complex_date_col (self)
bool _should_parse_dates (self, int i)
tuple[ Sequence[Hashable], Sequence[Hashable]|None, Sequence[Hashable]|None, bool] _extract_multi_indexer_columns (self, header, Sequence[Hashable]|None index_names, bool passed_names=False)
Sequence[Hashable]|MultiIndex _maybe_make_multi_index_columns (self, Sequence[Hashable] columns, Sequence[Hashable]|None col_names=None)
tuple[Index|None, Sequence[Hashable]|MultiIndex] _make_index (self, data, alldata, columns, list[Scalar]|None indexnamerow=None)
_get_simple_index (self, data, columns)
_get_complex_date_index (self, data, col_names)
_clean_mapping (self, mapping)
Index _agg_index (self, index, bool try_parse_dates=True)
_convert_to_ndarrays (self, Mapping dct, na_values, na_fvalues, bool verbose=False, converters=None, dtypes=None)
set[int] _set_noconvert_dtype_columns (self, list[int] col_indices, Sequence[Hashable] names)
tuple[ArrayLike, int] _infer_types (self, values, na_values, no_dtype_specified, bool try_num_bool=True)
ArrayLike _cast_types (self, ArrayLike values, DtypeObj cast_type, column)
tuple[Sequence[Hashable]|Index, DataFrame] _do_date_conversions (self, Index names, DataFrame data)
tuple[Sequence[Hashable], Mapping[Hashable, ArrayLike]] _do_date_conversions (self, Sequence[Hashable] names, Mapping[Hashable, ArrayLike] data)
tuple[Sequence[Hashable]|Index, Mapping[Hashable, ArrayLike]|DataFrame] _do_date_conversions (self, Sequence[Hashable]|Index names, Mapping[Hashable, ArrayLike]|DataFrame data)
None _check_data_length (self, Sequence[Hashable] columns, Sequence[ArrayLike] data)
set[int] _evaluate_usecols (self, set[int]|Callable[[Hashable], object] usecols, Sequence[Hashable] names)
set[str] _evaluate_usecols (self, set[str] usecols, Sequence[Hashable] names)
set[str]|set[int] _evaluate_usecols (self, Callable[[Hashable], object]|set[str]|set[int] usecols, Sequence[Hashable] names)
_validate_usecols_names (self, usecols, Sequence names)
_validate_usecols_arg (self, usecols)
tuple[list|None, list, list] _clean_index_names (self, columns, index_col)
_get_empty_meta (self, columns, DtypeArg|None dtype=None)
Additional Inherited Members
Static Public Attributes inherited from pandas.io.parsers.base_parser.ParserBase
str usecols_dtype | None
Protected Attributes inherited from pandas.io.parsers.python_parser.PythonParser
list[int]|None _col_indices = None
Protected Attributes inherited from pandas.io.parsers.base_parser.ParserBase
bool _implicit_index = False
list _parse_date_cols = []
_date_conv
bool _name_processed = False
bool _first_chunk = True
_has_complex_date_col
Static Protected Attributes inherited from pandas.io.parsers.python_parser.PythonParser
set _no_thousands_columns [int]
Detailed Description
Specialization that Converts fixed-width fields into DataFrames.
See PythonParser for details.
Definition at line 1319 of file python_parser.py.
Constructor & Destructor Documentation
__init__()
None pandas.io.parsers.python_parser.FixedWidthFieldParser.__init__ (self, ReadCsvBuffer[str] f, ** kwds)
Definition at line 1325 of file python_parser.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_make_reader()
FixedWidthReader pandas.io.parsers.python_parser.FixedWidthFieldParser._make_reader (self, IO[str] | ReadCsvBuffer[str] f) protected
Reimplemented from pandas.io.parsers.python_parser.PythonParser.
Definition at line 1331 of file python_parser.py.
_remove_empty_lines()
list[list[Scalar]] pandas.io.parsers.python_parser.FixedWidthFieldParser._remove_empty_lines (self, list[list[Scalar]] lines) protected
Returns the list of lines without the empty ones. With fixed-width
fields, empty lines become arrays of empty strings.
See PythonParser._remove_empty_lines.
Reimplemented from pandas.io.parsers.python_parser.PythonParser.
Definition at line 1341 of file python_parser.py.
Member Data Documentation
colspecs
pandas.io.parsers.python_parser.FixedWidthFieldParser.colspecs = kwds.pop("colspecs")
Definition at line 1327 of file python_parser.py.
infer_nrows
pandas.io.parsers.python_parser.FixedWidthFieldParser.infer_nrows = kwds.pop("infer_nrows")
Definition at line 1328 of file python_parser.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/io/parsers/python_parser.py