Code Cloning Analysis: pandas.io.stata.StataWriter117 Class Reference
pandas.io.stata.StataWriter117 Class Reference
Public Member Functions
None __init__ (self, FilePath|WriteBuffer[bytes] fname, DataFrame data, dict[Hashable, str]|None convert_dates=None, bool write_index=True, str|None byteorder=None, datetime|None time_stamp=None, str|None data_label=None, dict[Hashable, str]|None variable_labels=None, Sequence[Hashable]|None convert_strl=None, CompressionOptions compression="infer", StorageOptions|None storage_options=None, *, dict[Hashable, dict[float, str]]|None value_labels=None)
Public Member Functions inherited from pandas.io.stata.StataWriter
None __init__ (self, FilePath|WriteBuffer[bytes] fname, DataFrame data, dict[Hashable, str]|None convert_dates=None, bool write_index=True, str|None byteorder=None, datetime|None time_stamp=None, str|None data_label=None, dict[Hashable, str]|None variable_labels=None, CompressionOptions compression="infer", StorageOptions|None storage_options=None, *, dict[Hashable, dict[float, str]]|None value_labels=None)
None write_file (self)
Public Member Functions inherited from pandas.io.stata.StataParser
None __init__ (self)
Protected Member Functions
None _update_map (self, str tag)
None _write_header (self, str|None data_label=None, datetime|None time_stamp=None)
None _write_map (self)
None _write_variable_types (self)
None _write_varnames (self)
None _write_sortlist (self)
None _write_formats (self)
None _write_value_label_names (self)
None _write_variable_labels (self)
None _write_characteristics (self)
None _write_data (self, records)
None _write_strls (self)
None _write_expansion_fields (self)
None _write_value_labels (self)
None _write_file_close_tag (self)
None _update_strl_names (self)
DataFrame _convert_strls (self, DataFrame data)
None _set_formats_and_types (self, Series dtypes)
Protected Member Functions inherited from pandas.io.stata.StataWriter
None _write (self, str to_write)
None _write_bytes (self, bytes value)
list[StataNonCatValueLabel] _prepare_non_cat_value_labels (self, DataFrame data)
DataFrame _prepare_categoricals (self, DataFrame data)
DataFrame _replace_nans (self, DataFrame data)
str _validate_variable_name (self, str name)
DataFrame _check_column_names (self, DataFrame data)
None _prepare_pandas (self, DataFrame data)
None _encode_strings (self)
None _close (self)
np.rec.recarray _prepare_data (self)
bytes _null_terminate_bytes (self, str s)
Static Protected Member Functions
bytes _tag (str|bytes val, str tag)
Static Protected Member Functions inherited from pandas.io.stata.StataWriter
str _null_terminate_str (str s)
Protected Attributes
list _convert_strl = []
dict _map = {}
str _strl_blob = b""
Protected Attributes inherited from pandas.io.stata.StataWriter
dict _convert_dates = {} if convert_dates is None else convert_dates
_write_index = write_index
_time_stamp = time_stamp
_data_label = data_label
_variable_labels = variable_labels
_non_cat_value_labels = value_labels
list _value_labels = []
_has_value_labels = np.array([], dtype=bool)
_compression = compression
IO[bytes]|None _output_file = None
dict _converted_names = {}
_byteorder = _set_endianness(byteorder)
_fname = fname
Static Protected Attributes
int _dta_version = 117
Static Protected Attributes inherited from pandas.io.stata.StataWriter
int _max_string_length = 244
Literal _encoding = "latin-1"
Additional Inherited Members
Public Attributes inherited from pandas.io.stata.StataWriter
data = data
storage_options = storage_options
dict type_converters = {253: np.int32, 252: np.int16, 251: np.int8}
list fmtlist = []
list typlist = []
nobs = self._prepare_categoricals(data)
nvar = data.shape
varlist = data.columns.tolist()
handles = self.storage_options,
Public Attributes inherited from pandas.io.stata.StataParser
DTYPE_MAP
dict DTYPE_MAP_XML
TYPE_MAP = list(tuple(range(251)) + tuple("bhlfd"))
dict TYPE_MAP_XML
dict VALID_RANGE
dict OLD_TYPE_MAPPING
dict MISSING_VALUES
dict NUMPY_TYPE_MAP
dict RESERVED_WORDS
Detailed Description
A class for writing Stata binary dta files in Stata 13 format (117)
Parameters
----------
fname : path (string), buffer or path object
    string, path object (pathlib.Path or py._path.local.LocalPath) or
    object implementing a binary write() functions. If using a buffer
    then the buffer will not be automatically closed after the file
    is written.
data : DataFrame
    Input to save
convert_dates : dict
    Dictionary mapping columns containing datetime types to stata internal
    format to use when writing the dates. Options are 'tc', 'td', 'tm',
    'tw', 'th', 'tq', 'ty'. Column can be either an integer or a name.
    Datetime columns that do not have a conversion type specified will be
    converted to 'tc'. Raises NotImplementedError if a datetime column has
    timezone information
write_index : bool
    Write the index to Stata dataset.
byteorder : str
    Can be ">", "<", "little", or "big". default is `sys.byteorder`
time_stamp : datetime
    A datetime to use as file creation date.  Default is the current time
data_label : str
    A label for the data set.  Must be 80 characters or smaller.
variable_labels : dict
    Dictionary containing columns as keys and variable labels as values.
    Each label must be 80 characters or smaller.
convert_strl : list
    List of columns names to convert to Stata StrL format.  Columns with
    more than 2045 characters are automatically written as StrL.
    Smaller columns can be converted by including the column name.  Using
    StrLs can reduce output file size when strings are longer than 8
    characters, and either frequently repeated or sparse.
{compression_options}
    .. versionchanged:: 1.4.0 Zstandard support.
value_labels : dict of dicts
    Dictionary containing columns as keys and dictionaries of column value
    to labels as values. The combined length of all labels for a single
    variable must be 32,000 characters or smaller.
    .. versionadded:: 1.4.0
Returns
-------
writer : StataWriter117 instance
    The StataWriter117 instance has a write_file method, which will
    write the file to the given `fname`.
Raises
------
NotImplementedError
    * If datetimes contain timezone information
ValueError
    * Columns listed in convert_dates are neither datetime64[ns]
      or datetime
    * Column dtype is not representable in Stata
    * Column listed in convert_dates is not in DataFrame
    * Categorical label contains more than 32,000 characters
Examples
--------
>>> data = pd.DataFrame([[1.0, 1, 'a']], columns=['a', 'b', 'c'])
>>> writer = pd.io.stata.StataWriter117('./data_file.dta', data)
>>> writer.write_file()
Directly write a zip file
>>> compression = {"method": "zip", "archive_name": "data_file.dta"}
>>> writer = pd.io.stata.StataWriter117(
...     './data_file.zip', data, compression=compression
...)
>>> writer.write_file()
Or with long strings stored in strl format
>>> data = pd.DataFrame([['A relatively long string'], [''], ['']],
...                     columns=['strls'])
>>> writer = pd.io.stata.StataWriter117(
...     './data_file_with_long_strings.dta', data, convert_strl=['strls'])
>>> writer.write_file()
Definition at line 3209 of file stata.py.
Constructor & Destructor Documentation
__init__()
None pandas.io.stata.StataWriter117.__init__ (self, FilePath | WriteBuffer[bytes] fname, DataFrame data, dict[Hashable, str] | None convert_dates = None, bool write_index = True, str | None byteorder = None, datetime | None time_stamp = None, str | None data_label = None, dict[Hashable, str] | None variable_labels = None, Sequence[Hashable] | None convert_strl = None, CompressionOptions compression = "infer", StorageOptions | None storage_options = None, * , dict[Hashable, dict[float, str]] | None value_labels = None)
Definition at line 3298 of file stata.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_convert_strls()
DataFrame pandas.io.stata.StataWriter117._convert_strls (self, DataFrame data) protected
Convert columns to StrLs if either very large or in the
convert_strl variable
Reimplemented from pandas.io.stata.StataWriter.
Definition at line 3555 of file stata.py.
_set_formats_and_types()
None pandas.io.stata.StataWriter117._set_formats_and_types (self, Series dtypes) protected
Reimplemented from pandas.io.stata.StataWriter.
Definition at line 3573 of file stata.py.
_tag()
bytes pandas.io.stata.StataWriter117._tag (str | bytes val, str tag) static protected
Surround val with <tag></tag>
Definition at line 3336 of file stata.py.
_update_map()
None pandas.io.stata.StataWriter117._update_map (self, str tag) protected
Update map location for tag with file position
Definition at line 3342 of file stata.py.
_update_strl_names()
None pandas.io.stata.StataWriter117._update_strl_names (self) protected
Update column names for conversion to strl if they might have been
changed to comply with Stata naming rules
Reimplemented from pandas.io.stata.StataWriter.
Definition at line 3544 of file stata.py.
_write_characteristics()
None pandas.io.stata.StataWriter117._write_characteristics (self) protected
No-op, future compatibility
Reimplemented from pandas.io.stata.StataWriter.
Definition at line 3513 of file stata.py.
_write_data()
None pandas.io.stata.StataWriter117._write_data (self, records) protected
Reimplemented from pandas.io.stata.StataWriter.
Definition at line 3517 of file stata.py.
_write_expansion_fields()
None pandas.io.stata.StataWriter117._write_expansion_fields (self) protected
No-op in dta 117+
Reimplemented from pandas.io.stata.StataWriter.
Definition at line 3527 of file stata.py.
_write_file_close_tag()
None pandas.io.stata.StataWriter117._write_file_close_tag (self) protected
No-op, future compatibility
Reimplemented from pandas.io.stata.StataWriter.
Definition at line 3539 of file stata.py.
_write_formats()
None pandas.io.stata.StataWriter117._write_formats (self) protected
Reimplemented from pandas.io.stata.StataWriter.
Definition at line 3458 of file stata.py.
_write_header()
None pandas.io.stata.StataWriter117._write_header (self, str | None data_label = None, datetime | None time_stamp = None) protected
Write the file header
Reimplemented from pandas.io.stata.StataWriter.
Definition at line 3347 of file stata.py.
_write_map()
None pandas.io.stata.StataWriter117._write_map (self) protected
Called twice during file write. The first populates the values in
the map with 0s.  The second call writes the final map locations when
all blocks have been written.
Reimplemented from pandas.io.stata.StataWriter.
Definition at line 3405 of file stata.py.
_write_sortlist()
None pandas.io.stata.StataWriter117._write_sortlist (self) protected
Reimplemented from pandas.io.stata.StataWriter.
Definition at line 3453 of file stata.py.
_write_strls()
None pandas.io.stata.StataWriter117._write_strls (self) protected
No-op, future compatibility
Reimplemented from pandas.io.stata.StataWriter.
Definition at line 3523 of file stata.py.
_write_value_label_names()
None pandas.io.stata.StataWriter117._write_value_label_names (self) protected
Reimplemented from pandas.io.stata.StataWriter.
Definition at line 3466 of file stata.py.
_write_value_labels()
None pandas.io.stata.StataWriter117._write_value_labels (self) protected
Reimplemented from pandas.io.stata.StataWriter.
Definition at line 3530 of file stata.py.
_write_variable_labels()
None pandas.io.stata.StataWriter117._write_variable_labels (self) protected
Reimplemented from pandas.io.stata.StataWriter.
Definition at line 3481 of file stata.py.
_write_variable_types()
None pandas.io.stata.StataWriter117._write_variable_types (self) protected
Reimplemented from pandas.io.stata.StataWriter.
Definition at line 3435 of file stata.py.
_write_varnames()
None pandas.io.stata.StataWriter117._write_varnames (self) protected
Reimplemented from pandas.io.stata.StataWriter.
Definition at line 3442 of file stata.py.
Member Data Documentation
_convert_strl
list pandas.io.stata.StataWriter117._convert_strl = [] protected
Definition at line 3315 of file stata.py.
_dta_version
pandas.io.stata.StataWriter117._dta_version = 117 static protected
Definition at line 3296 of file stata.py.
_map
dict pandas.io.stata.StataWriter117._map = {} protected
Definition at line 3332 of file stata.py.
_strl_blob
pandas.io.stata.StataWriter117._strl_blob = b"" protected
Definition at line 3333 of file stata.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/io/stata.py