Code Cloning Analysis: matplotlib.backends.backend_webagg.WebAggApplication Class Reference
matplotlib.backends.backend_webagg.WebAggApplication Class Reference
Classes
class AllFiguresPage
class Download
class FavIcon
class MplJs
class SingleFigurePage
class WebSocket
Public Member Functions
__init__ (self, url_prefix='')
initialize (cls, url_prefix='', port=None, address=None)
start (cls)
Public Attributes
FavIcon
SingleFigurePage
AllFiguresPage
MplJs
WebSocket
Download
url_prefix = url_prefix
address = mpl.rcParams['webagg.address']
port = mpl.rcParams['webagg.port']
Static Public Attributes
bool initialized = False
bool started = False
Detailed Description
Definition at line 70 of file backend_webagg.py.
Constructor & Destructor Documentation
__init__()
matplotlib.backends.backend_webagg.WebAggApplication.__init__ (self, url_prefix = '')
Definition at line 169 of file backend_webagg.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
initialize()
matplotlib.backends.backend_webagg.WebAggApplication.initialize (cls, url_prefix = '', port = None, address = None)
Definition at line 210 of file backend_webagg.py.
start()
matplotlib.backends.backend_webagg.WebAggApplication.start (cls)
Definition at line 256 of file backend_webagg.py.
Referenced by scipy.optimize._zeros_py.TOMS748Solver.solve(), pip._vendor.rich.live.Live.stop(), pip._vendor.rich.progress.Progress.stop(), and pip._vendor.rich.status.Status.stop().
Member Data Documentation
address
matplotlib.backends.backend_webagg.WebAggApplication.address = mpl.rcParams['webagg.address']
Definition at line 234 of file backend_webagg.py.
AllFiguresPage
matplotlib.backends.backend_webagg.WebAggApplication.AllFiguresPage
Definition at line 194 of file backend_webagg.py.
Download
matplotlib.backends.backend_webagg.WebAggApplication.Download
Definition at line 205 of file backend_webagg.py.
FavIcon
matplotlib.backends.backend_webagg.WebAggApplication.FavIcon
Definition at line 187 of file backend_webagg.py.
initialized
bool matplotlib.backends.backend_webagg.WebAggApplication.initialized = False static
Definition at line 71 of file backend_webagg.py.
Referenced by scipy.integrate._ode.lsoda.reset(), scipy.integrate._ode.vode.reset(), scipy.integrate._ode.zvode.reset(), scipy.integrate._ode.lsoda.run(), and scipy.integrate._ode.vode.run().
MplJs
matplotlib.backends.backend_webagg.WebAggApplication.MplJs
Definition at line 197 of file backend_webagg.py.
port
matplotlib.backends.backend_webagg.WebAggApplication.port = mpl.rcParams['webagg.port']
Definition at line 237 of file backend_webagg.py.
Referenced by pip._vendor.urllib3.connectionpool.HTTPConnectionPool._make_request(), pip._vendor.urllib3.connection.HTTPConnection._new_conn(), pip._vendor.urllib3.connectionpool.HTTPConnectionPool._new_conn(), pip._vendor.urllib3.connectionpool.HTTPSConnectionPool._new_conn(), pip._vendor.urllib3.contrib.ntlmpool.NTLMConnectionPool._new_conn(), pip._vendor.urllib3.contrib.socks.SOCKSConnection._new_conn(), pip._vendor.urllib3.connectionpool.HTTPSConnectionPool._prepare_proxy(), pip._vendor.urllib3.connectionpool.HTTPConnectionPool.is_same_host(), and pip._vendor.urllib3.util.url.Url.netloc().
SingleFigurePage
matplotlib.backends.backend_webagg.WebAggApplication.SingleFigurePage
Definition at line 190 of file backend_webagg.py.
started
bool matplotlib.backends.backend_webagg.WebAggApplication.started = False static
Definition at line 72 of file backend_webagg.py.
url_prefix
matplotlib.backends.backend_webagg.WebAggApplication.url_prefix = url_prefix
Definition at line 217 of file backend_webagg.py.
WebSocket
matplotlib.backends.backend_webagg.WebAggApplication.WebSocket
Definition at line 201 of file backend_webagg.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/backends/backend_webagg.py