Code Cloning Analysis: numpy.typing.mypy_plugin Namespace Reference
numpy.typing.mypy_plugin Namespace Reference
Classes
class _NumpyPlugin
Functions
dict[str, str] _get_precision_dict ()
list[str] _get_extended_precision_list ()
str _get_c_intp_name ()
Type _hook (AnalyzeTypeContext ctx)
int _index (Iterable[Statement] iterable, str id)
None _override_imports (MypyFile file, str module, list[tuple[str, None|str]] imports)
type[_NumpyPlugin] plugin (str version)
Variables
_HookFunc = Callable[[AnalyzeTypeContext], Type]
None MYPY_EX = None
list __all__ = []
Final _PRECISION_DICT = _get_precision_dict()
Final _EXTENDED_PRECISION_LIST = _get_extended_precision_list()
Final _C_INTP = _get_c_intp_name()
Detailed Description
A mypy_ plugin for managing a number of platform-specific annotations.
Its functionality can be split into three distinct parts:
* Assigning the (platform-dependent) precisions of certain `~numpy.number`
  subclasses, including the likes of `~numpy.int_`, `~numpy.intp` and
  `~numpy.longlong`. See the documentation on
  :ref:`scalar types <arrays.scalars.built-in>` for a comprehensive overview
  of the affected classes. Without the plugin the precision of all relevant
  classes will be inferred as `~typing.Any`.
* Removing all extended-precision `~numpy.number` subclasses that are
  unavailable for the platform in question. Most notably this includes the
  likes of `~numpy.float128` and `~numpy.complex256`. Without the plugin *all*
  extended-precision types will, as far as mypy is concerned, be available
  to all platforms.
* Assigning the (platform-dependent) precision of `~numpy.ctypeslib.c_intp`.
  Without the plugin the type will default to `ctypes.c_int64`.
  .. versionadded:: 1.22
Examples
--------
To enable the plugin, one must add it to their mypy `configuration file`_:
.. code-block:: ini
    [mypy]
    plugins = numpy.typing.mypy_plugin
.. _mypy: http://mypy-lang.org/
.. _configuration file: https://mypy.readthedocs.io/en/stable/config_file.html
Function Documentation
_get_c_intp_name()
str numpy.typing.mypy_plugin._get_c_intp_name () protected
Definition at line 95 of file mypy_plugin.py.
_get_extended_precision_list()
list[str] numpy.typing.mypy_plugin._get_extended_precision_list () protected
Definition at line 77 of file mypy_plugin.py.
_get_precision_dict()
dict[str, str] numpy.typing.mypy_plugin._get_precision_dict () protected
Definition at line 56 of file mypy_plugin.py.
_hook()
Type numpy.typing.mypy_plugin._hook (AnalyzeTypeContext ctx) protected
Replace a type-alias with a concrete ``NBitBase`` subclass.
Definition at line 119 of file mypy_plugin.py.
_index()
int numpy.typing.mypy_plugin._index (Iterable[Statement] iterable, str id) protected
Identify the first ``ImportFrom`` instance the specified `id`.
Definition at line 128 of file mypy_plugin.py.
Referenced by _override_imports().
_override_imports()
None numpy.typing.mypy_plugin._override_imports (MypyFile file, str module, list[tuple[str, None | str]] imports) protected
Override the first `module`-based import with new `imports`.
Definition at line 136 of file mypy_plugin.py.
References _index().
Referenced by numpy.typing.mypy_plugin._NumpyPlugin.get_additional_deps().
plugin()
type[_NumpyPlugin] numpy.typing.mypy_plugin.plugin (str version)
An entry-point for mypy.
Definition at line 189 of file mypy_plugin.py.
Variable Documentation
__all__
list numpy.typing.mypy_plugin.__all__ = [] private
Definition at line 53 of file mypy_plugin.py.
_C_INTP
Final numpy.typing.mypy_plugin._C_INTP = _get_c_intp_name() protected
Definition at line 116 of file mypy_plugin.py.
_EXTENDED_PRECISION_LIST
Final numpy.typing.mypy_plugin._EXTENDED_PRECISION_LIST = _get_extended_precision_list() protected
Definition at line 113 of file mypy_plugin.py.
_HookFunc
numpy.typing.mypy_plugin._HookFunc = Callable[[AnalyzeTypeContext], Type] protected
Definition at line 48 of file mypy_plugin.py.
_PRECISION_DICT
Final numpy.typing.mypy_plugin._PRECISION_DICT = _get_precision_dict() protected
Definition at line 110 of file mypy_plugin.py.
MYPY_EX
numpy.typing.mypy_plugin.MYPY_EX = None
Definition at line 49 of file mypy_plugin.py.