Code Cloning Analysis: numpy.ma.tests.test_subclassing.ArrayNoInheritance Class Reference
numpy.ma.tests.test_subclassing.ArrayNoInheritance Class Reference
Public Member Functions
__init__ (self, data, units)
__getattr__ (self, attr)
Public Attributes
magnitude = data
units = units
Detailed Description
Quantity-like class that does not inherit from ndarray
Definition at line 376 of file test_subclassing.py.
Constructor & Destructor Documentation
__init__()
numpy.ma.tests.test_subclassing.ArrayNoInheritance.__init__ (self, data, units)
Definition at line 378 of file test_subclassing.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__getattr__()
numpy.ma.tests.test_subclassing.ArrayNoInheritance.__getattr__ (self, attr)
Definition at line 382 of file test_subclassing.py.
Member Data Documentation
magnitude
numpy.ma.tests.test_subclassing.ArrayNoInheritance.magnitude = data
Definition at line 379 of file test_subclassing.py.
units
numpy.ma.tests.test_subclassing.ArrayNoInheritance.units = units
Definition at line 380 of file test_subclassing.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/ma/tests/test_subclassing.py