Code Cloning Analysis: matplotlib._type1font._StringToken Class Reference
matplotlib._type1font._StringToken Class Reference
Public Member Functions
value (self)
Public Member Functions inherited from matplotlib._type1font._Token
__init__ (self, pos, raw)
__str__ (self)
endpos (self)
is_keyword (self, *names)
is_slash_name (self)
is_delim (self)
is_number (self)
Protected Member Functions
_escape (cls, match)
Protected Attributes
_escape
Static Protected Attributes
_escapes_re = re.compile(r'\\‍([\\‍()nrtbf]|[0-7]{1,3})')
dict _replacements
_ws_re = re.compile('[\0\t\r\f\n ]')
Additional Inherited Members
Public Attributes inherited from matplotlib._type1font._Token
pos = pos
raw = raw
Static Public Attributes inherited from matplotlib._type1font._Token
str kind = '?'
Detailed Description
Definition at line 131 of file _type1font.py.
Member Function Documentation
_escape()
matplotlib._type1font._StringToken._escape (cls, match) protected
Definition at line 139 of file _type1font.py.
Referenced by pip._vendor.pygments.formatters.rtf.RtfFormatter.__init__().
value()
matplotlib._type1font._StringToken.value (self)
Reimplemented from matplotlib._type1font._Token.
Definition at line 147 of file _type1font.py.
Referenced by sklearn.externals.array_api_extra._lib._at._AtOp.__str__(), pip._internal.models.link.LinkHash.as_hashes(), pip._internal.models.link.LinkHash.find_hash_url_fragment(), and pip._internal.models.link.LinkHash.is_hash_allowed().
Member Data Documentation
_escape
matplotlib._type1font._StringToken._escape protected
Definition at line 149 of file _type1font.py.
Referenced by pip._vendor.pygments.formatters.rtf.RtfFormatter.__init__().
_escapes_re
matplotlib._type1font._StringToken._escapes_re = re.compile(r'\\‍([\\‍()nrtbf]|[0-7]{1,3})') static protected
Definition at line 133 of file _type1font.py.
_replacements
dict matplotlib._type1font._StringToken._replacements static protected
Initial value:
=  {'\\': '\\', '(': '(', ')': ')', 'n': '\n',
                     'r': '\r', 't': '\t', 'b': '\b', 'f': '\f'}
Definition at line 134 of file _type1font.py.
_ws_re
matplotlib._type1font._StringToken._ws_re = re.compile('[\0\t\r\f\n ]') static protected
Definition at line 136 of file _type1font.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/_type1font.py