Code Cloning Analysis: scipy.sparse.tests.test_base Namespace Reference
scipy.sparse.tests.test_base Namespace Reference
Classes
class _NonCanonicalCompressedMixin
class _NonCanonicalCSMixin
class _NonCanonicalMixin
class _TestArithmetic
class _TestCommon
class _TestFancyIndexing
class _TestFancyIndexingAssign
class _TestFancyMultidim
class _TestFancyMultidimAssign
class _TestGetNnzAxis
class _TestGetSet
class _TestInplaceArithmetic
class _TestMinMax
class _TestSlicing
class _TestSlicingAssign
class _TestSolve
class BinopTester
class BinopTester_with_shape
class Test64Bit
class TestBSR
class TestBSRNonCanonical
class TestCOO
class TestCOONonCanonical
class TestCSC
class TestCSCNonCanonical
class TestCSR
class TestCSRNonCanonical
class TestDIA
class TestDOK
class TestLIL
Functions
assert_in (member, collection, msg=None)
assert_array_equal_dtype (x, y, **kwargs)
sparse_may_share_memory (A, B)
with_64bit_maxval_limit (maxval_limit=None, random=False, fixed_dtype=None, downcast_maxval=None, assert_32bit=False)
toarray (a)
check_remains_sorted (X)
_possibly_unimplemented (cls, require=True)
sparse_test_class (getset=True, slicing=True, slicing_assign=True, fancy_indexing=True, fancy_assign=True, fancy_multidim_indexing=True, fancy_multidim_assign=True, minmax=True, nnz_axis=True)
_same_sum_duplicate (data, *inds, **kwargs)
cases_64bit ()
Variables
tuple IS_COLAB = ('google.colab' in sys.modules)
NON_ARRAY_BACKED_FORMATS = frozenset(['dok'])
sup_complex = suppress_warnings()
__bases__
__dict__
__name__ = names.get(name)
Detailed Description
 Test functions for sparse matrices. Each class in the "Matrix class
based tests" section become subclasses of the classes in the "Generic
tests" section. This is done by the functions in the "Tailored base
class for generic tests" section.
Function Documentation
_possibly_unimplemented()
scipy.sparse.tests.test_base._possibly_unimplemented (cls, require = True) protected
Construct a class that either runs tests as usual (require=True),
or each method skips if it encounters a common error.
Definition at line 3605 of file test_base.py.
Referenced by sparse_test_class().
_same_sum_duplicate()
scipy.sparse.tests.test_base._same_sum_duplicate (data, * inds, ** kwargs) protected
Duplicates entries to produce the same matrix
Definition at line 4733 of file test_base.py.
Referenced by scipy.sparse.tests.test_base._NonCanonicalCompressedMixin._arg1_for_noncanonical(), and scipy.sparse.tests.test_base.TestCOONonCanonical._arg1_for_noncanonical().
assert_array_equal_dtype()
scipy.sparse.tests.test_base.assert_array_equal_dtype (x, y, ** kwargs)
Definition at line 53 of file test_base.py.
assert_in()
scipy.sparse.tests.test_base.assert_in (member, collection, msg = None)
Definition at line 49 of file test_base.py.
cases_64bit()
scipy.sparse.tests.test_base.cases_64bit ()
Definition at line 4927 of file test_base.py.
check_remains_sorted()
scipy.sparse.tests.test_base.check_remains_sorted (X)
Checks that sorted indices property is retained through an operation
Definition at line 2998 of file test_base.py.
sparse_may_share_memory()
scipy.sparse.tests.test_base.sparse_may_share_memory (A, B)
Definition at line 60 of file test_base.py.
sparse_test_class()
scipy.sparse.tests.test_base.sparse_test_class (getset = True, slicing = True, slicing_assign = True, fancy_indexing = True, fancy_assign = True, fancy_multidim_indexing = True, fancy_multidim_assign = True, minmax = True, nnz_axis = True)
Construct a base class, optionally converting some of the tests in
the suite to check that the feature is not implemented.
Definition at line 3633 of file test_base.py.
References _possibly_unimplemented().
toarray()
scipy.sparse.tests.test_base.toarray (a)
Definition at line 165 of file test_base.py.
with_64bit_maxval_limit()
scipy.sparse.tests.test_base.with_64bit_maxval_limit (maxval_limit = None, random = False, fixed_dtype = None, downcast_maxval = None, assert_32bit = False)
Monkeypatch the maxval threshold at which scipy.sparse switches to
64-bit index arrays, or make it (pseudo-)random.
Definition at line 84 of file test_base.py.
Variable Documentation
__bases__
scipy.sparse.tests.test_base.__bases__ private
Definition at line 3629 of file test_base.py.
__dict__
scipy.sparse.tests.test_base.__dict__ private
Definition at line 3661 of file test_base.py.
__name__
scipy.sparse.tests.test_base.__name__ = names.get(name) private
Definition at line 3667 of file test_base.py.
IS_COLAB
tuple scipy.sparse.tests.test_base.IS_COLAB = ('google.colab' in sys.modules)
Definition at line 46 of file test_base.py.
NON_ARRAY_BACKED_FORMATS
scipy.sparse.tests.test_base.NON_ARRAY_BACKED_FORMATS = frozenset(['dok'])
Definition at line 58 of file test_base.py.
sup_complex
scipy.sparse.tests.test_base.sup_complex = suppress_warnings()
Definition at line 80 of file test_base.py.