Code Cloning Analysis: pip._vendor.typing_extensions._ProtocolMeta Class Reference
pip._vendor.typing_extensions._ProtocolMeta Class Reference
Public Member Functions
__new__ (mcls, name, bases, namespace, **kwargs)
__init__ (cls, *args, **kwargs)
__subclasscheck__ (cls, other)
__instancecheck__ (cls, instance)
__eq__ (cls, other)
int __hash__ (cls)
Private Attributes
__protocol_attrs__ = _get_protocol_attrs(cls)
__callable_proto_members_only__
Detailed Description
Definition at line 611 of file typing_extensions.py.
Constructor & Destructor Documentation
__init__()
pip._vendor.typing_extensions._ProtocolMeta.__init__ (cls, * args, ** kwargs)
Definition at line 634 of file typing_extensions.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
__eq__()
pip._vendor.typing_extensions._ProtocolMeta.__eq__ (cls, other)
Definition at line 699 of file typing_extensions.py.
__hash__()
int pip._vendor.typing_extensions._ProtocolMeta.__hash__ (cls)
Definition at line 712 of file typing_extensions.py.
__instancecheck__()
pip._vendor.typing_extensions._ProtocolMeta.__instancecheck__ (cls, instance)
Definition at line 668 of file typing_extensions.py.
__new__()
pip._vendor.typing_extensions._ProtocolMeta.__new__ (mcls, name, bases, namespace, ** kwargs)
Definition at line 618 of file typing_extensions.py.
Referenced by matplotlib.path.Path._fast_from_codes_and_verts(), pandas.core.generic.NDFrame._from_mgr(), pandas.core.arrays.string_.StringArray._from_sequence(), scipy.interpolate._fitpack2._BivariateSplineBase._from_tck(), scipy.interpolate._fitpack2.UnivariateSpline._from_tck(), matplotlib.colors.Colormap._get_rgba_and_mask(), pip._vendor.rich.style.Style.clear_meta_and_links(), matplotlib.colors.MultivarColormap.copy(), pip._vendor.rich.style.Style.copy(), pip._vendor.rich.style.Style.from_color(), pip._vendor.rich.json.JSON.from_data(), pip._vendor.rich.style.Style.from_meta(), matplotlib.colors.BivarColormap.lut(), pip._vendor.rich.style.Style.test(), pip._vendor.rich.style.Style.update_link(), and pip._vendor.rich.style.Style.without_color().
__subclasscheck__()
pip._vendor.typing_extensions._ProtocolMeta.__subclasscheck__ (cls, other)
Definition at line 644 of file typing_extensions.py.
Member Data Documentation
__callable_proto_members_only__
pip._vendor.typing_extensions._ProtocolMeta.__callable_proto_members_only__ private
Initial value:
=  all(
                    callable(getattr(cls, attr, None)) for attr in cls.__protocol_attrs__
                )
Definition at line 640 of file typing_extensions.py.
__protocol_attrs__
pip._vendor.typing_extensions._ProtocolMeta.__protocol_attrs__ = _get_protocol_attrs(cls) private
Definition at line 637 of file typing_extensions.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pip/_vendor/typing_extensions.py