Code Cloning Analysis: sklearn.feature_extraction.text.CountVectorizer Class Reference
sklearn.feature_extraction.text.CountVectorizer Class Reference
Public Member Functions
__init__ (self, *, input="content", encoding="utf-8", decode_error="strict", strip_accents=None, lowercase=True, preprocessor=None, tokenizer=None, stop_words=None, token_pattern=r"(?u)\b\w\w+\b", ngram_range=(1, 1), analyzer="word", max_df=1.0, min_df=1, max_features=None, vocabulary=None, binary=False, dtype=np.int64)
fit (self, raw_documents, y=None)
fit_transform (self, raw_documents, y=None)
transform (self, raw_documents)
inverse_transform (self, X)
get_feature_names_out (self, input_features=None)
__sklearn_tags__ (self)
Public Member Functions inherited from sklearn.feature_extraction.text._VectorizerMixin
decode (self, doc)
build_preprocessor (self)
build_tokenizer (self)
get_stop_words (self)
build_analyzer (self)
Public Member Functions inherited from sklearn.base.BaseEstimator
get_params (self, deep=True)
set_params (self, **params)
__sklearn_clone__ (self)
__repr__ (self, N_CHAR_MAX=700)
__getstate__ (self)
__setstate__ (self, state)
__sklearn_tags__ (self)
Public Member Functions inherited from sklearn.utils._metadata_requests._MetadataRequester
set_fit_request (self, **kwargs)
set_partial_fit_request (self, **kwargs)
set_predict_request (self, **kwargs)
set_predict_proba_request (self, **kwargs)
set_predict_log_proba_request (self, **kwargs)
set_decision_function_request (self, **kwargs)
set_score_request (self, **kwargs)
set_split_request (self, **kwargs)
set_transform_request (self, **kwargs)
set_inverse_transform_request (self, **kwargs)
__init_subclass__ (cls, **kwargs)
get_metadata_routing (self)
Public Attributes
encoding = encoding
decode_error = decode_error
preprocessor = preprocessor
tokenizer = tokenizer
lowercase = lowercase
token_pattern = token_pattern
max_df = max_df
min_df = min_df
max_features = max_features
vocabulary = vocabulary
binary = binary
dtype = dtype
Public Attributes inherited from sklearn.feature_extraction.text._VectorizerMixin
str input = "filename":
str strip_accents = None
stop_words
str analyzer = (1, 1)
bool fixed_vocabulary_ = True
vocabulary_ = dict(vocabulary)
ngram_range
Protected Member Functions
_sort_features (self, X, vocabulary)
_limit_features (self, X, vocabulary, high=None, low=None, limit=None)
_count_vocab (self, raw_documents, fixed_vocab)
Protected Member Functions inherited from sklearn.feature_extraction.text._VectorizerMixin
_word_ngrams (self, tokens, stop_words=None)
_char_ngrams (self, text_document)
_char_wb_ngrams (self, text_document)
_check_stop_words_consistency (self, stop_words, preprocess, tokenize)
_validate_vocabulary (self)
_check_vocabulary (self)
_validate_ngram_range (self)
_warn_for_unused_params (self)
Protected Member Functions inherited from sklearn.base.BaseEstimator
_get_param_names (cls)
_get_params_html (self, deep=True)
_validate_params (self)
Protected Member Functions inherited from sklearn.utils._repr_html.base.ReprHTMLMixin
_repr_html_ (self)
_repr_html_inner (self)
_repr_mimebundle_ (self, **kwargs)
Protected Member Functions inherited from sklearn.utils._repr_html.base._HTMLDocumentationLinkMixin
_doc_link_template (self)
_doc_link_template (self, value)
_get_doc_link (self)
Protected Member Functions inherited from sklearn.utils._metadata_requests._MetadataRequester
_build_request_for_signature (cls, router, method)
_get_default_requests (cls)
_get_metadata_request (self)
Static Private Attributes
dict __metadata_request__fit = {"raw_documents": metadata_routing.UNUSED}
dict __metadata_request__transform = {"raw_documents": metadata_routing.UNUSED}
Additional Inherited Members
Protected Attributes inherited from sklearn.feature_extraction.text._VectorizerMixin
_stop_words_id = id(self.stop_words)
Protected Attributes inherited from sklearn.base.BaseEstimator
_parameter_constraints
Static Protected Attributes inherited from sklearn.feature_extraction.text._VectorizerMixin
_white_spaces = re.compile(r"\s\s+")
Static Protected Attributes inherited from sklearn.base.BaseEstimator
_html_repr = estimator_html_repr
Static Protected Attributes inherited from sklearn.utils._repr_html.base._HTMLDocumentationLinkMixin
str _doc_link_module = "sklearn"
_doc_link_url_param_generator = None
Detailed Description
Convert a collection of text documents to a matrix of token counts.
This implementation produces a sparse representation of the counts using
scipy.sparse.csr_matrix.
If you do not provide an a-priori dictionary and you do not use an analyzer
that does some kind of feature selection then the number of features will
be equal to the vocabulary size found by analyzing the data.
For an efficiency comparison of the different feature extractors, see
:ref:`sphx_glr_auto_examples_text_plot_hashing_vs_dict_vectorizer.py`.
Read more in the :ref:`User Guide <text_feature_extraction>`.
Parameters
----------
input : {'filename', 'file', 'content'}, default='content'
    - If `'filename'`, the sequence passed as an argument to fit is
      expected to be a list of filenames that need reading to fetch
      the raw content to analyze.
    - If `'file'`, the sequence items must have a 'read' method (file-like
      object) that is called to fetch the bytes in memory.
    - If `'content'`, the input is expected to be a sequence of items that
      can be of type string or byte.
encoding : str, default='utf-8'
    If bytes or files are given to analyze, this encoding is used to
    decode.
decode_error : {'strict', 'ignore', 'replace'}, default='strict'
    Instruction on what to do if a byte sequence is given to analyze that
    contains characters not of the given `encoding`. By default, it is
    'strict', meaning that a UnicodeDecodeError will be raised. Other
    values are 'ignore' and 'replace'.
strip_accents : {'ascii', 'unicode'} or callable, default=None
    Remove accents and perform other character normalization
    during the preprocessing step.
    'ascii' is a fast method that only works on characters that have
    a direct ASCII mapping.
    'unicode' is a slightly slower method that works on any characters.
    None (default) means no character normalization is performed.
    Both 'ascii' and 'unicode' use NFKD normalization from
    :func:`unicodedata.normalize`.
lowercase : bool, default=True
    Convert all characters to lowercase before tokenizing.
preprocessor : callable, default=None
    Override the preprocessing (strip_accents and lowercase) stage while
    preserving the tokenizing and n-grams generation steps.
    Only applies if ``analyzer`` is not callable.
tokenizer : callable, default=None
    Override the string tokenization step while preserving the
    preprocessing and n-grams generation steps.
    Only applies if ``analyzer == 'word'``.
stop_words : {'english'}, list, default=None
    If 'english', a built-in stop word list for English is used.
    There are several known issues with 'english' and you should
    consider an alternative (see :ref:`stop_words`).
    If a list, that list is assumed to contain stop words, all of which
    will be removed from the resulting tokens.
    Only applies if ``analyzer == 'word'``.
    If None, no stop words will be used. In this case, setting `max_df`
    to a higher value, such as in the range (0.7, 1.0), can automatically detect
    and filter stop words based on intra corpus document frequency of terms.
token_pattern : str or None, default=r"(?u)\\b\\w\\w+\\b"
    Regular expression denoting what constitutes a "token", only used
    if ``analyzer == 'word'``. The default regexp select tokens of 2
    or more alphanumeric characters (punctuation is completely ignored
    and always treated as a token separator).
    If there is a capturing group in token_pattern then the
    captured group content, not the entire match, becomes the token.
    At most one capturing group is permitted.
ngram_range : tuple (min_n, max_n), default=(1, 1)
    The lower and upper boundary of the range of n-values for different
    word n-grams or char n-grams to be extracted. All values of n such
    such that min_n <= n <= max_n will be used. For example an
    ``ngram_range`` of ``(1, 1)`` means only unigrams, ``(1, 2)`` means
    unigrams and bigrams, and ``(2, 2)`` means only bigrams.
    Only applies if ``analyzer`` is not callable.
analyzer : {'word', 'char', 'char_wb'} or callable, default='word'
    Whether the feature should be made of word n-gram or character
    n-grams.
    Option 'char_wb' creates character n-grams only from text inside
    word boundaries; n-grams at the edges of words are padded with space.
    If a callable is passed it is used to extract the sequence of features
    out of the raw, unprocessed input.
    .. versionchanged:: 0.21
    Since v0.21, if ``input`` is ``filename`` or ``file``, the data is
    first read from the file and then passed to the given callable
    analyzer.
max_df : float in range [0.0, 1.0] or int, default=1.0
    When building the vocabulary ignore terms that have a document
    frequency strictly higher than the given threshold (corpus-specific
    stop words).
    If float, the parameter represents a proportion of documents, integer
    absolute counts.
    This parameter is ignored if vocabulary is not None.
min_df : float in range [0.0, 1.0] or int, default=1
    When building the vocabulary ignore terms that have a document
    frequency strictly lower than the given threshold. This value is also
    called cut-off in the literature.
    If float, the parameter represents a proportion of documents, integer
    absolute counts.
    This parameter is ignored if vocabulary is not None.
max_features : int, default=None
    If not None, build a vocabulary that only consider the top
    `max_features` ordered by term frequency across the corpus.
    Otherwise, all features are used.
    This parameter is ignored if vocabulary is not None.
vocabulary : Mapping or iterable, default=None
    Either a Mapping (e.g., a dict) where keys are terms and values are
    indices in the feature matrix, or an iterable over terms. If not
    given, a vocabulary is determined from the input documents. Indices
    in the mapping should not be repeated and should not have any gap
    between 0 and the largest index.
binary : bool, default=False
    If True, all non zero counts are set to 1. This is useful for discrete
    probabilistic models that model binary events rather than integer
    counts.
dtype : dtype, default=np.int64
    Type of the matrix returned by fit_transform() or transform().
Attributes
----------
vocabulary_ : dict
    A mapping of terms to feature indices.
fixed_vocabulary_ : bool
    True if a fixed vocabulary of term to indices mapping
    is provided by the user.
See Also
--------
HashingVectorizer : Convert a collection of text documents to a
    matrix of token counts.
TfidfVectorizer : Convert a collection of raw documents to a matrix
    of TF-IDF features.
Examples
--------
>>> from sklearn.feature_extraction.text import CountVectorizer
>>> corpus = [
...     'This is the first document.',
...     'This document is the second document.',
...     'And this is the third one.',
...     'Is this the first document?',
... ]
>>> vectorizer = CountVectorizer()
>>> X = vectorizer.fit_transform(corpus)
>>> vectorizer.get_feature_names_out()
array(['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third',
       'this'], ...)
>>> print(X.toarray())
[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]
>>> vectorizer2 = CountVectorizer(analyzer='word', ngram_range=(2, 2))
>>> X2 = vectorizer2.fit_transform(corpus)
>>> vectorizer2.get_feature_names_out()
array(['and this', 'document is', 'first document', 'is the', 'is this',
       'second document', 'the first', 'the second', 'the third', 'third one',
       'this document', 'this is', 'this the'], ...)
 >>> print(X2.toarray())
 [[0 0 1 1 0 0 1 0 0 0 0 1 0]
 [0 1 0 1 0 1 0 1 0 0 1 0 0]
 [1 0 0 1 0 0 0 0 1 1 0 1 0]
 [0 0 1 0 1 0 1 0 0 0 0 0 1]]
Definition at line 928 of file text.py.
Constructor & Destructor Documentation
__init__()
sklearn.feature_extraction.text.CountVectorizer.__init__ (self, * , input = "content", encoding = "utf-8", decode_error = "strict", strip_accents = None, lowercase = True, preprocessor = None, tokenizer = None, stop_words = None, token_pattern = r"(?u)\b\w\w+\b", ngram_range = (1, 1), analyzer = "word", max_df = 1.0, min_df = 1, max_features = None, vocabulary = None, binary = False, dtype = np.int64)
Definition at line 1154 of file text.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params().
Member Function Documentation
__sklearn_tags__()
sklearn.feature_extraction.text.CountVectorizer.__sklearn_tags__ (self)
Definition at line 1478 of file text.py.
_count_vocab()
sklearn.feature_extraction.text.CountVectorizer._count_vocab (self, raw_documents, fixed_vocab) protected
Create sparse feature matrix, and vocabulary where fixed_vocab=False
Definition at line 1246 of file text.py.
_limit_features()
sklearn.feature_extraction.text.CountVectorizer._limit_features (self, X, vocabulary, high = None, low = None, limit = None) protected
Remove too rare or too common features.
Prune features that are non zero in more samples than high or less
documents than low, modifying the vocabulary, and restricting it to
at most the limit most frequent.
This does not prune samples with zero features.
Definition at line 1207 of file text.py.
_sort_features()
sklearn.feature_extraction.text.CountVectorizer._sort_features (self, X, vocabulary) protected
Sort features by name
Returns a reordered matrix and modifies the vocabulary in place
Definition at line 1193 of file text.py.
fit()
sklearn.feature_extraction.text.CountVectorizer.fit (self, raw_documents, y = None)
Learn a vocabulary dictionary of all tokens in the raw documents.
Parameters
----------
raw_documents : iterable
    An iterable which generates either str, unicode or file objects.
y : None
    This parameter is ignored.
Returns
-------
self : object
    Fitted vectorizer.
Reimplemented in sklearn.feature_extraction.text.TfidfVectorizer.
Definition at line 1311 of file text.py.
Referenced by sklearn.cluster._kmeans._BaseKMeans.fit_predict(), sklearn.neighbors._lof.LocalOutlierFactor.fit_predict(), sklearn.cluster._kmeans._BaseKMeans.fit_transform(), sklearn.manifold._spectral_embedding.SpectralEmbedding.fit_transform(), sklearn.neighbors._graph.KNeighborsTransformer.fit_transform(), sklearn.neighbors._graph.RadiusNeighborsTransformer.fit_transform(), sklearn.preprocessing._label.LabelBinarizer.fit_transform(), sklearn.preprocessing._label.MultiLabelBinarizer.fit_transform(), sklearn.tests.metadata_routing_common.ConsumingTransformer.fit_transform(), and sklearn.utils.tests.test_estimator_checks.SparseTransformer.fit_transform().
fit_transform()
sklearn.feature_extraction.text.CountVectorizer.fit_transform (self, raw_documents, y = None)
Learn the vocabulary dictionary and return document-term matrix.
This is equivalent to fit followed by transform, but more efficiently
implemented.
Parameters
----------
raw_documents : iterable
    An iterable which generates either str, unicode or file objects.
y : None
    This parameter is ignored.
Returns
-------
X : array of shape (n_samples, n_features)
    Document-term matrix.
Reimplemented in sklearn.feature_extraction.text.TfidfVectorizer.
Definition at line 1331 of file text.py.
Referenced by sklearn.manifold._mds.MDS.fit().
get_feature_names_out()
sklearn.feature_extraction.text.CountVectorizer.get_feature_names_out (self, input_features = None)
Get output feature names for transformation.
Parameters
----------
input_features : array-like of str or None, default=None
    Not used, present here for API consistency by convention.
Returns
-------
feature_names_out : ndarray of str objects
    Transformed feature names.
Definition at line 1459 of file text.py.
Referenced by sklearn.preprocessing._function_transformer.FunctionTransformer.transform().
inverse_transform()
sklearn.feature_extraction.text.CountVectorizer.inverse_transform (self, X)
Return terms per document with nonzero entries in X.
Parameters
----------
X : {array-like, sparse matrix} of shape (n_samples, n_features)
    Document-term matrix.
Returns
-------
X_original : list of arrays of shape (n_samples,)
    List of arrays of terms.
Definition at line 1426 of file text.py.
Referenced by sklearn.preprocessing._function_transformer.FunctionTransformer._check_inverse_transform(), and sklearn.feature_selection._base.SelectorMixin.inverse_transform().
transform()
sklearn.feature_extraction.text.CountVectorizer.transform (self, raw_documents)
Transform documents to document-term matrix.
Extract token counts out of raw text documents using the vocabulary
fitted with fit or the one provided to the constructor.
Parameters
----------
raw_documents : iterable
    An iterable which generates either str, unicode or file objects.
Returns
-------
X : sparse matrix of shape (n_samples, n_features)
    Document-term matrix.
Reimplemented in sklearn.feature_extraction.text.TfidfVectorizer.
Definition at line 1398 of file text.py.
Referenced by sklearn.preprocessing._function_transformer.FunctionTransformer._check_inverse_transform(), sklearn.feature_selection._rfe.RFE.decision_function(), PIL.ImageCms.Flags.GRIDPOINTS(), sklearn.ensemble._stacking._BaseStacking.predict(), sklearn.feature_selection._rfe.RFE.predict(), sklearn.feature_selection._rfe.RFE.predict_log_proba(), sklearn.feature_selection._rfe.RFE.predict_proba(), sklearn.feature_selection._rfe.RFE.score(), and sklearn.preprocessing._polynomial.PolynomialFeatures.transform().
Member Data Documentation
__metadata_request__fit
dict sklearn.feature_extraction.text.CountVectorizer.__metadata_request__fit = {"raw_documents": metadata_routing.UNUSED} static private
Definition at line 1125 of file text.py.
__metadata_request__transform
dict sklearn.feature_extraction.text.CountVectorizer.__metadata_request__transform = {"raw_documents": metadata_routing.UNUSED} static private
Definition at line 1126 of file text.py.
binary
sklearn.feature_extraction.text.CountVectorizer.binary = binary
Definition at line 1190 of file text.py.
decode_error
sklearn.feature_extraction.text.CountVectorizer.decode_error = decode_error
Definition at line 1177 of file text.py.
Referenced by sklearn.feature_extraction.text._VectorizerMixin.decode().
dtype
sklearn.feature_extraction.text.CountVectorizer.dtype = dtype
Definition at line 1191 of file text.py.
Referenced by pandas.core.arrays.base.ExtensionScalarOpsMixin._create_method(), pandas.core.interchange.column.PandasColumn._get_data_buffer(), pandas.core.interchange.column.PandasColumn._get_offsets_buffer(), pandas.core.interchange.column.PandasColumn._get_validity_buffer(), scipy.sparse._index.IndexMixin._getcol(), pandas.core.generic.NDFrame._inplace_method(), scipy.sparse._index.IndexMixin._raise_on_1d_array_slice(), pandas.core.strings.object_array.ObjectStringArrayMixin._str_map(), pandas.core.arrays.timedeltas.TimedeltaArray._vector_divlike_op(), pandas.core.interchange.column.PandasColumn.describe_categorical(), pandas.core.interchange.column.PandasColumn.describe_null(), sklearn.preprocessing._discretization.KBinsDiscretizer.fit(), sklearn.preprocessing._encoders.OrdinalEncoder.fit(), numpy.matrixlib.defmatrix.matrix.H(), pandas.core.internals.array_manager.SingleArrayManager.make_empty(), numpy.core.records.record.pprint(), pandas.core.frame.DataFrame.quantile(), pandas.core.generic.NDFrame.rank(), sklearn.preprocessing._discretization.KBinsDiscretizer.transform(), sklearn.preprocessing._encoders.OneHotEncoder.transform(), sklearn.preprocessing._encoders.OrdinalEncoder.transform(), pandas.io.pytables.AppendableTable.write_data(), and pandas.io.pytables.AppendableTable.write_data_chunk().
encoding
sklearn.feature_extraction.text.CountVectorizer.encoding = encoding
Definition at line 1176 of file text.py.
Referenced by pip._vendor.rich.console.ConsoleOptions.ascii_only(), sklearn.feature_extraction.text._VectorizerMixin.decode(), and pip._vendor.rich.console.Console.options().
lowercase
sklearn.feature_extraction.text.CountVectorizer.lowercase = lowercase
Definition at line 1182 of file text.py.
Referenced by sklearn.feature_extraction.text._VectorizerMixin.build_preprocessor().
max_df
sklearn.feature_extraction.text.CountVectorizer.max_df = max_df
Definition at line 1185 of file text.py.
max_features
sklearn.feature_extraction.text.CountVectorizer.max_features = max_features
Definition at line 1187 of file text.py.
Referenced by sklearn.tree._classes.BaseDecisionTree._compute_missing_values_in_feature_mask(), and sklearn.feature_selection._from_model.SelectFromModel._get_support_mask().
min_df
sklearn.feature_extraction.text.CountVectorizer.min_df = min_df
Definition at line 1186 of file text.py.
preprocessor
sklearn.feature_extraction.text.CountVectorizer.preprocessor = preprocessor
Definition at line 1179 of file text.py.
Referenced by sklearn.feature_extraction.text._VectorizerMixin.build_preprocessor().
token_pattern
sklearn.feature_extraction.text.CountVectorizer.token_pattern = token_pattern
Definition at line 1183 of file text.py.
Referenced by sklearn.feature_extraction.text._VectorizerMixin.build_tokenizer().
tokenizer
sklearn.feature_extraction.text.CountVectorizer.tokenizer = tokenizer
Definition at line 1180 of file text.py.
Referenced by sklearn.feature_extraction.text._VectorizerMixin.build_tokenizer().
vocabulary
sklearn.feature_extraction.text.CountVectorizer.vocabulary = vocabulary
Definition at line 1189 of file text.py.
Referenced by sklearn.feature_extraction.text._VectorizerMixin.build_analyzer().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/sklearn/feature_extraction/text.py