Code Cloning Analysis: sklearn.datasets.tests.test_svmlight_format Namespace Reference
sklearn.datasets.tests.test_svmlight_format Namespace Reference
Functions
_svmlight_local_test_file_path (filename)
_load_svmlight_local_test_file (filename, **kwargs)
test_load_svmlight_file ()
test_load_svmlight_file_fd ()
test_load_svmlight_pathlib ()
test_load_svmlight_file_multilabel ()
test_load_svmlight_files ()
test_load_svmlight_file_n_features ()
test_load_compressed ()
test_load_invalid_file ()
test_load_invalid_order_file ()
test_load_zero_based ()
test_load_zero_based_auto ()
test_load_with_qid ()
test_load_large_qid ()
test_load_invalid_file2 ()
test_not_a_filename ()
test_invalid_filename ()
test_dump (csr_container)
test_dump_multilabel (csr_container)
test_dump_concise ()
test_dump_comment ()
test_dump_invalid ()
test_dump_query_id ()
test_load_with_long_qid ()
test_load_zeros (csr_container)
test_load_with_offsets (sparsity, n_samples, n_features, csr_container)
test_load_offset_exhaustive_splits (csr_container)
test_load_with_offsets_error ()
test_multilabel_y_explicit_zeros (tmp_path, csr_container)
test_dump_read_only (tmp_path)
Variables
str TEST_DATA_MODULE = "sklearn.datasets.tests.data"
str datafile = "svmlight_classification.txt"
str multifile = "svmlight_multilabel.txt"
str invalidfile = "svmlight_invalid.txt"
str invalidfile2 = "svmlight_invalid_order.txt"
Function Documentation
_load_svmlight_local_test_file()
sklearn.datasets.tests.test_svmlight_format._load_svmlight_local_test_file (filename, ** kwargs) protected
Helper to load resource `filename` with `importlib.resources`
Definition at line 34 of file test_svmlight_format.py.
References _load_svmlight_local_test_file().
Referenced by _load_svmlight_local_test_file(), and test_load_large_qid().
_svmlight_local_test_file_path()
sklearn.datasets.tests.test_svmlight_format._svmlight_local_test_file_path (filename) protected
Definition at line 30 of file test_svmlight_format.py.
test_dump()
sklearn.datasets.tests.test_svmlight_format.test_dump (csr_container)
Definition at line 259 of file test_svmlight_format.py.
test_dump_comment()
sklearn.datasets.tests.test_svmlight_format.test_dump_comment ()
Definition at line 374 of file test_svmlight_format.py.
test_dump_concise()
sklearn.datasets.tests.test_svmlight_format.test_dump_concise ()
Definition at line 343 of file test_svmlight_format.py.
test_dump_invalid()
sklearn.datasets.tests.test_svmlight_format.test_dump_invalid ()
Definition at line 407 of file test_svmlight_format.py.
test_dump_multilabel()
sklearn.datasets.tests.test_svmlight_format.test_dump_multilabel (csr_container)
Definition at line 329 of file test_svmlight_format.py.
test_dump_query_id()
sklearn.datasets.tests.test_svmlight_format.test_dump_query_id ()
Definition at line 420 of file test_svmlight_format.py.
test_dump_read_only()
sklearn.datasets.tests.test_svmlight_format.test_dump_read_only (tmp_path)
Ensure that there is no ValueError when dumping a read-only `X`.
Non-regression test for:
https://github.com/scikit-learn/scikit-learn/issues/28026
Definition at line 599 of file test_svmlight_format.py.
test_invalid_filename()
sklearn.datasets.tests.test_svmlight_format.test_invalid_filename ()
Definition at line 253 of file test_svmlight_format.py.
test_load_compressed()
sklearn.datasets.tests.test_svmlight_format.test_load_compressed ()
Definition at line 145 of file test_svmlight_format.py.
test_load_invalid_file()
sklearn.datasets.tests.test_svmlight_format.test_load_invalid_file ()
Definition at line 173 of file test_svmlight_format.py.
test_load_invalid_file2()
sklearn.datasets.tests.test_svmlight_format.test_load_invalid_file2 ()
Definition at line 239 of file test_svmlight_format.py.
test_load_invalid_order_file()
sklearn.datasets.tests.test_svmlight_format.test_load_invalid_order_file ()
Definition at line 178 of file test_svmlight_format.py.
test_load_large_qid()
sklearn.datasets.tests.test_svmlight_format.test_load_large_qid ()
load large libsvm / svmlight file with qid attribute. Tests 64-bit query ID
Definition at line 224 of file test_svmlight_format.py.
References _load_svmlight_local_test_file().
test_load_offset_exhaustive_splits()
sklearn.datasets.tests.test_svmlight_format.test_load_offset_exhaustive_splits (csr_container)
Definition at line 526 of file test_svmlight_format.py.
test_load_svmlight_file()
sklearn.datasets.tests.test_svmlight_format.test_load_svmlight_file ()
Definition at line 43 of file test_svmlight_format.py.
test_load_svmlight_file_fd()
sklearn.datasets.tests.test_svmlight_format.test_load_svmlight_file_fd ()
Definition at line 78 of file test_svmlight_format.py.
test_load_svmlight_file_multilabel()
sklearn.datasets.tests.test_svmlight_format.test_load_svmlight_file_multilabel ()
Definition at line 107 of file test_svmlight_format.py.
test_load_svmlight_file_n_features()
sklearn.datasets.tests.test_svmlight_format.test_load_svmlight_file_n_features ()
Definition at line 128 of file test_svmlight_format.py.
test_load_svmlight_files()
sklearn.datasets.tests.test_svmlight_format.test_load_svmlight_files ()
Definition at line 112 of file test_svmlight_format.py.
test_load_svmlight_pathlib()
sklearn.datasets.tests.test_svmlight_format.test_load_svmlight_pathlib ()
Definition at line 97 of file test_svmlight_format.py.
test_load_with_long_qid()
sklearn.datasets.tests.test_svmlight_format.test_load_with_long_qid ()
Definition at line 435 of file test_svmlight_format.py.
test_load_with_offsets()
sklearn.datasets.tests.test_svmlight_format.test_load_with_offsets (sparsity, n_samples, n_features, csr_container)
Definition at line 489 of file test_svmlight_format.py.
test_load_with_offsets_error()
sklearn.datasets.tests.test_svmlight_format.test_load_with_offsets_error ()
Definition at line 568 of file test_svmlight_format.py.
test_load_with_qid()
sklearn.datasets.tests.test_svmlight_format.test_load_with_qid ()
Definition at line 204 of file test_svmlight_format.py.
test_load_zero_based()
sklearn.datasets.tests.test_svmlight_format.test_load_zero_based ()
Definition at line 183 of file test_svmlight_format.py.
test_load_zero_based_auto()
sklearn.datasets.tests.test_svmlight_format.test_load_zero_based_auto ()
Definition at line 189 of file test_svmlight_format.py.
test_load_zeros()
sklearn.datasets.tests.test_svmlight_format.test_load_zeros (csr_container)
Definition at line 472 of file test_svmlight_format.py.
test_multilabel_y_explicit_zeros()
sklearn.datasets.tests.test_svmlight_format.test_multilabel_y_explicit_zeros (tmp_path, csr_container)
Ensure that if y contains explicit zeros (i.e. elements of y.data equal to
0) then those explicit zeros are not encoded.
Definition at line 574 of file test_svmlight_format.py.
test_not_a_filename()
sklearn.datasets.tests.test_svmlight_format.test_not_a_filename ()
Definition at line 246 of file test_svmlight_format.py.
Variable Documentation
datafile
str sklearn.datasets.tests.test_svmlight_format.datafile = "svmlight_classification.txt"
Definition at line 24 of file test_svmlight_format.py.
invalidfile
str sklearn.datasets.tests.test_svmlight_format.invalidfile = "svmlight_invalid.txt"
Definition at line 26 of file test_svmlight_format.py.
invalidfile2
str sklearn.datasets.tests.test_svmlight_format.invalidfile2 = "svmlight_invalid_order.txt"
Definition at line 27 of file test_svmlight_format.py.
multifile
str sklearn.datasets.tests.test_svmlight_format.multifile = "svmlight_multilabel.txt"
Definition at line 25 of file test_svmlight_format.py.
TEST_DATA_MODULE
str sklearn.datasets.tests.test_svmlight_format.TEST_DATA_MODULE = "sklearn.datasets.tests.data"
Definition at line 23 of file test_svmlight_format.py.