Code Cloning Analysis: matplotlib.colors.NoNorm Class Reference
matplotlib.colors.NoNorm Class Reference
Public Member Functions
__call__ (self, value, clip=None)
inverse (self, value)
Public Member Functions inherited from matplotlib.colors.Normalize
__init__ (self, vmin=None, vmax=None, clip=False)
vmin (self)
vmin (self, value)
vmax (self)
vmax (self, value)
clip (self)
clip (self, value)
__call__ (self, value, clip=None)
autoscale (self, A)
autoscale_None (self, A)
scaled (self)
Additional Inherited Members
Static Public Member Functions inherited from matplotlib.colors.Normalize
process_value (value)
Public Attributes inherited from matplotlib.colors.Normalize
callbacks = cbook.CallbackRegistry(signals=["changed"])
vmin = None
vmax = A.max()
Protected Member Functions inherited from matplotlib.colors.Normalize
_changed (self)
Protected Attributes inherited from matplotlib.colors.Normalize
_vmin = _sanitize_extrema(vmin)
_vmax = _sanitize_extrema(vmax)
_clip = clip
_scale = None
Detailed Description
Dummy replacement for `Normalize`, for the case where we want to use
indices directly in a `~matplotlib.cm.ScalarMappable`.
Definition at line 3058 of file colors.py.
Member Function Documentation
__call__()
matplotlib.colors.NoNorm.__call__ (self, value, clip = None)
Definition at line 3063 of file colors.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), scipy.interpolate._fitpack2.SphereBivariateSpline.ev(), matplotlib.ticker.Formatter.format_data(), and matplotlib.ticker.LogFormatter.format_data().
inverse()
matplotlib.colors.NoNorm.inverse (self, value)
Maps the normalized value (i.e., index in the colormap) back to image
data value.
Parameters
----------
value
    Normalized value.
Reimplemented from matplotlib.colors.Normalize.
Definition at line 3068 of file colors.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/colors.py