Code Cloning Analysis: joblib._parallel_backends.FallbackToBackend Class Reference
joblib._parallel_backends.FallbackToBackend Class Reference
Public Member Functions
__init__ (self, backend)
Public Attributes
backend = backend
Detailed Description
Raised when configuration should fallback to another backend
Definition at line 732 of file _parallel_backends.py.
Constructor & Destructor Documentation
__init__()
joblib._parallel_backends.FallbackToBackend.__init__ (self, backend)
Definition at line 735 of file _parallel_backends.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Data Documentation
backend
joblib._parallel_backends.FallbackToBackend.backend = backend
Definition at line 736 of file _parallel_backends.py.
Referenced by joblib.memory.Memory.cache().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/joblib/_parallel_backends.py