Code Cloning Analysis: fontTools.ufoLib.glifLib._FetchImageFileNameParser Class Reference
fontTools.ufoLib.glifLib._FetchImageFileNameParser Class Reference
Public Member Functions
__init__ (self)
startElementHandler (self, name, attrs)
Public Member Functions inherited from fontTools.ufoLib.glifLib._BaseParser
__init__ (self)
parse (self, text)
endElementHandler (self, name)
Public Attributes
fileName = None
Additional Inherited Members
Protected Attributes inherited from fontTools.ufoLib.glifLib._BaseParser
list _elementStack = []
Detailed Description
Definition at line 1829 of file glifLib.py.
Constructor & Destructor Documentation
__init__()
fontTools.ufoLib.glifLib._FetchImageFileNameParser.__init__ (self)
Definition at line 1830 of file glifLib.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
startElementHandler()
fontTools.ufoLib.glifLib._FetchImageFileNameParser.startElementHandler (self, name, attrs)
Reimplemented from fontTools.ufoLib.glifLib._BaseParser.
Definition at line 1834 of file glifLib.py.
Member Data Documentation
fileName
fontTools.ufoLib.glifLib._FetchImageFileNameParser.fileName = None
Definition at line 1831 of file glifLib.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ufoLib/glifLib.py