Code Cloning Analysis: fontTools.ufoLib.glifLib._BaseParser Class Reference
fontTools.ufoLib.glifLib._BaseParser Class Reference
Public Member Functions
__init__ (self)
parse (self, text)
startElementHandler (self, name, attrs)
endElementHandler (self, name)
Protected Attributes
list _elementStack = []
Detailed Description
Definition at line 1760 of file glifLib.py.
Constructor & Destructor Documentation
__init__()
fontTools.ufoLib.glifLib._BaseParser.__init__ (self)
Definition at line 1761 of file glifLib.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
endElementHandler()
fontTools.ufoLib.glifLib._BaseParser.endElementHandler (self, name)
Definition at line 1775 of file glifLib.py.
parse()
fontTools.ufoLib.glifLib._BaseParser.parse (self, text)
Definition at line 1764 of file glifLib.py.
Referenced by pandas.io.formats.css.CSSResolver.__call__(), and pip._vendor.rich.style.Style.normalize().
startElementHandler()
fontTools.ufoLib.glifLib._BaseParser.startElementHandler (self, name, attrs)
Definition at line 1772 of file glifLib.py.
Member Data Documentation
_elementStack
list fontTools.ufoLib.glifLib._BaseParser._elementStack = [] protected
Definition at line 1762 of file glifLib.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ufoLib/glifLib.py