Code Cloning Analysis: fontTools.ttLib.tables._h_h_e_a.table__h_h_e_a Class Reference
fontTools.ttLib.tables._h_h_e_a.table__h_h_e_a Class Reference
Public Member Functions
ascender (self)
ascender (self, value)
descender (self)
descender (self, value)
decompile (self, data, ttFont)
compile (self, ttFont)
recalc (self, ttFont)
toXML (self, writer, ttFont)
fromXML (self, name, attrs, content, ttFont)
Public Member Functions inherited from fontTools.ttLib.tables.DefaultTable.DefaultTable
__init__ (self, tag=None)
__repr__ (self)
__eq__ (self, other)
__ne__ (self, other)
Public Attributes
ascent = value
descent = value
tableVersion = fi2ve(self.tableVersion)
advanceWidthMax = max(adv for adv, _ in hmtxTable.metrics.values())
int minLeftSideBearing = minLeftSideBearing
int minRightSideBearing = minRightSideBearing
int xMaxExtent = xMaxExtent
Public Attributes inherited from fontTools.ttLib.tables.DefaultTable.DefaultTable
tableTag = Tag(tag)
data = data
ERROR
Additional Inherited Members
Static Public Attributes inherited from fontTools.ttLib.tables.DefaultTable.DefaultTable
list dependencies = []
Detailed Description
Horizontal Header table
The ``hhea`` table contains information needed during horizontal
text layout.
.. note::
   This converter class is kept in sync with the :class:`._v_h_e_a.table__v_h_e_a`
   table constructor.
See also https://learn.microsoft.com/en-us/typography/opentype/spec/hhea
Definition at line 33 of file _h_h_e_a.py.
Member Function Documentation
ascender() [1/2]
fontTools.ttLib.tables._h_h_e_a.table__h_h_e_a.ascender (self)
Definition at line 52 of file _h_h_e_a.py.
ascender() [2/2]
fontTools.ttLib.tables._h_h_e_a.table__h_h_e_a.ascender (self, value)
Definition at line 56 of file _h_h_e_a.py.
compile()
fontTools.ttLib.tables._h_h_e_a.table__h_h_e_a.compile (self, ttFont)
Reimplemented from fontTools.ttLib.tables.DefaultTable.DefaultTable.
Definition at line 70 of file _h_h_e_a.py.
Referenced by fontTools.ttLib.tables.TupleVariation.TupleVariation.getCoordWidth(), and PIL.FontFile.FontFile.save().
decompile()
fontTools.ttLib.tables._h_h_e_a.table__h_h_e_a.decompile (self, data, ttFont)
Reimplemented from fontTools.ttLib.tables.DefaultTable.DefaultTable.
Definition at line 67 of file _h_h_e_a.py.
Referenced by fontTools.ttLib.tables._c_m_a_p.CmapSubtable.newSubtable().
descender() [1/2]
fontTools.ttLib.tables._h_h_e_a.table__h_h_e_a.descender (self)
Definition at line 60 of file _h_h_e_a.py.
descender() [2/2]
fontTools.ttLib.tables._h_h_e_a.table__h_h_e_a.descender (self, value)
Definition at line 64 of file _h_h_e_a.py.
fromXML()
fontTools.ttLib.tables._h_h_e_a.table__h_h_e_a.fromXML (self, name, attrs, content, ttFont)
Reimplemented from fontTools.ttLib.tables.DefaultTable.DefaultTable.
Definition at line 143 of file _h_h_e_a.py.
recalc()
fontTools.ttLib.tables._h_h_e_a.table__h_h_e_a.recalc (self, ttFont)
Definition at line 80 of file _h_h_e_a.py.
toXML()
fontTools.ttLib.tables._h_h_e_a.table__h_h_e_a.toXML (self, writer, ttFont)
Reimplemented from fontTools.ttLib.tables.DefaultTable.DefaultTable.
Definition at line 133 of file _h_h_e_a.py.
Member Data Documentation
advanceWidthMax
fontTools.ttLib.tables._h_h_e_a.table__h_h_e_a.advanceWidthMax = max(adv for adv, _ in hmtxTable.metrics.values())
Definition at line 85 of file _h_h_e_a.py.
ascent
fontTools.ttLib.tables._h_h_e_a.table__h_h_e_a.ascent = value
Definition at line 57 of file _h_h_e_a.py.
descent
fontTools.ttLib.tables._h_h_e_a.table__h_h_e_a.descent = value
Definition at line 65 of file _h_h_e_a.py.
minLeftSideBearing
int fontTools.ttLib.tables._h_h_e_a.table__h_h_e_a.minLeftSideBearing = minLeftSideBearing
Definition at line 124 of file _h_h_e_a.py.
minRightSideBearing
int fontTools.ttLib.tables._h_h_e_a.table__h_h_e_a.minRightSideBearing = minRightSideBearing
Definition at line 125 of file _h_h_e_a.py.
tableVersion
fontTools.ttLib.tables._h_h_e_a.table__h_h_e_a.tableVersion = fi2ve(self.tableVersion)
Definition at line 77 of file _h_h_e_a.py.
Referenced by fontTools.ttLib.tables._m_a_x_p.table__m_a_x_p.recalc().
xMaxExtent
int fontTools.ttLib.tables._h_h_e_a.table__h_h_e_a.xMaxExtent = xMaxExtent
Definition at line 126 of file _h_h_e_a.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ttLib/tables/_h_h_e_a.py