Code Cloning Analysis: pandas.tests.io.excel.test_readers Namespace Reference
pandas.tests.io.excel.test_readers Namespace Reference
Classes
class TestExcelFileRead
class TestReaders
Functions
bool _is_valid_engine_ext_pair (engine, str read_ext)
_transfer_marks (engine, read_ext)
engine_and_read_ext (request)
engine (engine_and_read_ext)
read_ext (engine_and_read_ext)
df_ref (datapath)
str get_exp_unit (str read_ext, str|None engine)
None adjust_expected (DataFrame expected, str read_ext, str engine)
xfail_datetimes_with_pyxlsb (engine, request)
Variables
pytestmark = pytest.mark.single_cpu
list read_ext_params = [".xls", ".xlsx", ".xlsm", ".xlsb", ".ods"]
list engine_params
Function Documentation
_is_valid_engine_ext_pair()
bool pandas.tests.io.excel.test_readers._is_valid_engine_ext_pair (engine, str read_ext) protected
Filter out invalid (engine, ext) pairs instead of skipping, as that
produces 500+ pytest.skips.
Definition at line 64 of file test_readers.py.
Referenced by _transfer_marks().
_transfer_marks()
pandas.tests.io.excel.test_readers._transfer_marks (engine, read_ext) protected
engine gives us a pytest.param object with some marks, read_ext is just
a string.  We need to generate a new pytest.param inheriting the marks.
Definition at line 85 of file test_readers.py.
References _is_valid_engine_ext_pair(), and _transfer_marks().
Referenced by _transfer_marks().
adjust_expected()
None pandas.tests.io.excel.test_readers.adjust_expected (DataFrame expected, str read_ext, str engine)
Definition at line 137 of file test_readers.py.
df_ref()
pandas.tests.io.excel.test_readers.df_ref (datapath)
Obtain the reference data from read_csv with the Python engine.
Definition at line 124 of file test_readers.py.
engine()
pandas.tests.io.excel.test_readers.engine (engine_and_read_ext)
Definition at line 112 of file test_readers.py.
engine_and_read_ext()
pandas.tests.io.excel.test_readers.engine_and_read_ext (request)
Fixture for Excel reader engine and read_ext, only including valid pairs.
Definition at line 104 of file test_readers.py.
get_exp_unit()
str pandas.tests.io.excel.test_readers.get_exp_unit (str read_ext, str | None engine)
Definition at line 133 of file test_readers.py.
read_ext()
pandas.tests.io.excel.test_readers.read_ext (engine_and_read_ext)
Definition at line 118 of file test_readers.py.
xfail_datetimes_with_pyxlsb()
pandas.tests.io.excel.test_readers.xfail_datetimes_with_pyxlsb (engine, request)
Definition at line 144 of file test_readers.py.
Variable Documentation
engine_params
list pandas.tests.io.excel.test_readers.engine_params
Initial value:
=  [
    # Add any engines to test here
    # When defusedxml is installed it triggers deprecation warnings for
    # xlrd and openpyxl, so catch those here
    pytest.param(
        "xlrd",
        marks=[
            td.skip_if_no("xlrd"),
        ],
    ),
    pytest.param(
        "openpyxl",
        marks=[
            td.skip_if_no("openpyxl"),
        ],
    ),
    pytest.param(
        None,
        marks=[
            td.skip_if_no("xlrd"),
        ],
    ),
    pytest.param("pyxlsb", marks=td.skip_if_no("pyxlsb")),
    pytest.param("odf", marks=td.skip_if_no("odf")),
    pytest.param("calamine", marks=td.skip_if_no("python_calamine")),
]
Definition at line 36 of file test_readers.py.
pytestmark
pandas.tests.io.excel.test_readers.pytestmark = pytest.mark.single_cpu
Definition at line 33 of file test_readers.py.
read_ext_params
list pandas.tests.io.excel.test_readers.read_ext_params = [".xls", ".xlsx", ".xlsm", ".xlsb", ".ods"]
Definition at line 35 of file test_readers.py.