Code Cloning Analysis: pip._vendor.chardet.jpcntx.JapaneseContextAnalysis Class Reference
pip._vendor.chardet.jpcntx.JapaneseContextAnalysis Class Reference
Public Member Functions
None __init__ (self)
None reset (self)
None feed (self, Union[bytes, bytearray] byte_str, int num_bytes)
bool got_enough_data (self)
float get_confidence (self)
Tuple[int, int] get_order (self, Union[bytes, bytearray] _)
Static Public Attributes
int NUM_OF_CATEGORY = 6
int DONT_KNOW = -1
int ENOUGH_REL_THRESHOLD = 100
int MAX_REL_THRESHOLD = 1000
int MINIMUM_DATA_THRESHOLD = 4
Protected Attributes
int _total_rel = 0
list _rel_sample = []
int _need_to_skip_char_num = 0
int _last_char_order = -1
bool _done = False
Detailed Description
Definition at line 120 of file jpcntx.py.
Constructor & Destructor Documentation
__init__()
None pip._vendor.chardet.jpcntx.JapaneseContextAnalysis.__init__ (self)
Definition at line 127 of file jpcntx.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
feed()
None pip._vendor.chardet.jpcntx.JapaneseContextAnalysis.feed (self, Union[bytes, bytearray] byte_str, int num_bytes)
Definition at line 147 of file jpcntx.py.
get_confidence()
float pip._vendor.chardet.jpcntx.JapaneseContextAnalysis.get_confidence (self)
Definition at line 179 of file jpcntx.py.
get_order()
Tuple[int, int] pip._vendor.chardet.jpcntx.JapaneseContextAnalysis.get_order (self, Union[bytes, bytearray] _)
Definition at line 185 of file jpcntx.py.
got_enough_data()
bool pip._vendor.chardet.jpcntx.JapaneseContextAnalysis.got_enough_data (self)
Definition at line 176 of file jpcntx.py.
reset()
None pip._vendor.chardet.jpcntx.JapaneseContextAnalysis.reset (self)
Definition at line 135 of file jpcntx.py.
Referenced by scipy._lib._docscrape.Reader.__init__().
Member Data Documentation
_done
bool pip._vendor.chardet.jpcntx.JapaneseContextAnalysis._done = False protected
Definition at line 132 of file jpcntx.py.
_last_char_order
int pip._vendor.chardet.jpcntx.JapaneseContextAnalysis._last_char_order = -1 protected
Definition at line 131 of file jpcntx.py.
_need_to_skip_char_num
int pip._vendor.chardet.jpcntx.JapaneseContextAnalysis._need_to_skip_char_num = 0 protected
Definition at line 130 of file jpcntx.py.
_rel_sample
list pip._vendor.chardet.jpcntx.JapaneseContextAnalysis._rel_sample = [] protected
Definition at line 129 of file jpcntx.py.
_total_rel
int pip._vendor.chardet.jpcntx.JapaneseContextAnalysis._total_rel = 0 protected
Definition at line 128 of file jpcntx.py.
DONT_KNOW
int pip._vendor.chardet.jpcntx.JapaneseContextAnalysis.DONT_KNOW = -1 static
Definition at line 122 of file jpcntx.py.
ENOUGH_REL_THRESHOLD
int pip._vendor.chardet.jpcntx.JapaneseContextAnalysis.ENOUGH_REL_THRESHOLD = 100 static
Definition at line 123 of file jpcntx.py.
MAX_REL_THRESHOLD
int pip._vendor.chardet.jpcntx.JapaneseContextAnalysis.MAX_REL_THRESHOLD = 1000 static
Definition at line 124 of file jpcntx.py.
MINIMUM_DATA_THRESHOLD
int pip._vendor.chardet.jpcntx.JapaneseContextAnalysis.MINIMUM_DATA_THRESHOLD = 4 static
Definition at line 125 of file jpcntx.py.
NUM_OF_CATEGORY
int pip._vendor.chardet.jpcntx.JapaneseContextAnalysis.NUM_OF_CATEGORY = 6 static
Definition at line 121 of file jpcntx.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pip/_vendor/chardet/jpcntx.py