Code Cloning Analysis: joblib.numpy_pickle_utils Namespace Reference
joblib.numpy_pickle_utils Namespace Reference
Functions
_is_raw_file (fileobj)
_get_prefixes_max_len ()
_is_numpy_array_byte_order_mismatch (array)
_ensure_native_byte_order (array)
_detect_compressor (fileobj)
Cache file utilities.
_buffered_read_file (fobj)
_buffered_write_file (fobj)
_validate_fileobject_and_memmap (fileobj, filename, mmap_mode=None)
_write_fileobject (filename, compress=("zlib", 3))
_read_bytes (fp, size, error_template="ran out of data")
_reconstruct (*args, **kwargs)
Variables
np = None
Unpickler = pickle._Unpickler
Pickler = pickle._Pickler
xrange = range
bz2 = None
int _IO_BUFFER_SIZE = 1024**2
int BUFFER_SIZE = 2**18
Detailed Description
Utilities for fast persistence of big data, with optional compression.
Function Documentation
_buffered_read_file()
joblib.numpy_pickle_utils._buffered_read_file (fobj) protected
Return a buffered version of a read file object.
Definition at line 120 of file numpy_pickle_utils.py.
Referenced by _validate_fileobject_and_memmap().
_buffered_write_file()
joblib.numpy_pickle_utils._buffered_write_file (fobj) protected
Return a buffered version of a write file object.
Definition at line 125 of file numpy_pickle_utils.py.
Referenced by _write_fileobject().
_detect_compressor()
joblib.numpy_pickle_utils._detect_compressor (fileobj) protected
Cache file utilities.
Return the compressor matching fileobj.
Parameters
----------
fileobj: file object
Returns
-------
str in {'zlib', 'gzip', 'bz2', 'lzma', 'xz', 'compat', 'not-compressed'}
Definition at line 88 of file numpy_pickle_utils.py.
Referenced by _validate_fileobject_and_memmap().
_ensure_native_byte_order()
joblib.numpy_pickle_utils._ensure_native_byte_order (array) protected
Use the byte order of the host while preserving values
Does nothing if array already uses the system byte order.
Definition at line 76 of file numpy_pickle_utils.py.
References _is_numpy_array_byte_order_mismatch().
_get_prefixes_max_len()
joblib.numpy_pickle_utils._get_prefixes_max_len () protected
Definition at line 44 of file numpy_pickle_utils.py.
_is_numpy_array_byte_order_mismatch()
joblib.numpy_pickle_utils._is_numpy_array_byte_order_mismatch (array) protected
Check if numpy array is having byte order mismatch
Definition at line 51 of file numpy_pickle_utils.py.
Referenced by _ensure_native_byte_order().
_is_raw_file()
joblib.numpy_pickle_utils._is_raw_file (fileobj) protected
Check if fileobj is a raw file object, e.g created with open.
Definition at line 38 of file numpy_pickle_utils.py.
Referenced by _validate_fileobject_and_memmap().
_read_bytes()
joblib.numpy_pickle_utils._read_bytes (fp, size, error_template = "ran out of data") protected
Read from file-like object until size bytes are read.
TODO python2_drop: is it still needed? The docstring mentions python 2.6
and it looks like this can be at least simplified ...
Raises ValueError if not EOF is encountered before size bytes are read.
Non-blocking objects only supported if they derive from io objects.
Required as e.g. ZipExtFile in python 2.6 can return less data than
requested.
This function was taken from numpy/lib/format.py in version 1.10.2.
Parameters
----------
fp: file-like object
size: int
error_template: str
Returns
-------
a bytes object
    The data read in bytes.
Definition at line 234 of file numpy_pickle_utils.py.
_reconstruct()
joblib.numpy_pickle_utils._reconstruct (* args, ** kwargs) protected
Definition at line 279 of file numpy_pickle_utils.py.
_validate_fileobject_and_memmap()
joblib.numpy_pickle_utils._validate_fileobject_and_memmap (fileobj, filename, mmap_mode = None) protected
Utility function opening the right fileobject from a filename.
The magic number is used to choose between the type of file object to open:
* regular file object (default)
* zlib file object
* gzip file object
* bz2 file object
* lzma file object (for xz and lzma compressor)
Parameters
----------
fileobj: file object
filename: str
    filename path corresponding to the fileobj parameter.
mmap_mode: str
    memory map mode that should be used to open the pickle file. This
    parameter is useful to verify that the user is not trying to one with
    compression. Default: None.
Returns
-------
    a tuple with a file like object, and the validated mmap_mode.
Definition at line 131 of file numpy_pickle_utils.py.
References _buffered_read_file(), _detect_compressor(), and _is_raw_file().
_write_fileobject()
joblib.numpy_pickle_utils._write_fileobject (filename, compress = ("zlib", 3)) protected
Return the right compressor file object in write mode.
Definition at line 211 of file numpy_pickle_utils.py.
References _buffered_write_file().
Variable Documentation
_IO_BUFFER_SIZE
int joblib.numpy_pickle_utils._IO_BUFFER_SIZE = 1024**2 protected
Definition at line 35 of file numpy_pickle_utils.py.
BUFFER_SIZE
int joblib.numpy_pickle_utils.BUFFER_SIZE = 2**18
Definition at line 231 of file numpy_pickle_utils.py.
bz2
joblib.numpy_pickle_utils.bz2 = None
Definition at line 32 of file numpy_pickle_utils.py.
np
joblib.numpy_pickle_utils.np = None
Definition at line 18 of file numpy_pickle_utils.py.
Pickler
joblib.numpy_pickle_utils.Pickler = pickle._Pickler
Definition at line 21 of file numpy_pickle_utils.py.
Unpickler
joblib.numpy_pickle_utils.Unpickler = pickle._Unpickler
Definition at line 20 of file numpy_pickle_utils.py.
xrange
joblib.numpy_pickle_utils.xrange = range
Definition at line 22 of file numpy_pickle_utils.py.