Code Cloning Analysis: matplotlib.cbook._ExceptionInfo Class Reference
matplotlib.cbook._ExceptionInfo Class Reference
Public Member Functions
__init__ (self, cls, *args)
from_exception (cls, exc)
to_exception (self)
Protected Attributes
_cls = cls
_args = args
Detailed Description
A class to carry exception information around.
This is used to store and later raise exceptions. It's an alternative to
directly storing Exception instances that circumvents traceback-related
issues: caching tracebacks can keep user's objects in local namespaces
alive indefinitely, which can lead to very surprising memory issues for
users and result in incorrect tracebacks.
Definition at line 35 of file cbook.py.
Constructor & Destructor Documentation
__init__()
matplotlib.cbook._ExceptionInfo.__init__ (self, cls, * args)
Definition at line 46 of file cbook.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
from_exception()
matplotlib.cbook._ExceptionInfo.from_exception (cls, exc)
Definition at line 51 of file cbook.py.
to_exception()
matplotlib.cbook._ExceptionInfo.to_exception (self)
Definition at line 54 of file cbook.py.
Member Data Documentation
_args
matplotlib.cbook._ExceptionInfo._args = args protected
Definition at line 48 of file cbook.py.
Referenced by matplotlib.animation.MovieWriter.setup().
_cls
matplotlib.cbook._ExceptionInfo._cls = cls protected
Definition at line 47 of file cbook.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/cbook.py