Code Cloning Analysis: scipy.stats._distn_infrastructure.rv_discrete_frozen Class Reference
scipy.stats._distn_infrastructure.rv_discrete_frozen Class Reference
Public Member Functions
pmf (self, k)
logpmf (self, k)
Public Member Functions inherited from scipy.stats._distn_infrastructure.rv_frozen
__init__ (self, dist, *args, **kwds)
random_state (self)
random_state (self, seed)
cdf (self, x)
logcdf (self, x)
ppf (self, q)
isf (self, q)
rvs (self, size=None, random_state=None)
sf (self, x)
logsf (self, x)
stats (self, moments='mv')
median (self)
mean (self)
var (self)
std (self)
moment (self, order=None)
entropy (self)
interval (self, confidence=None)
expect (self, func=None, lb=None, ub=None, conditional=False, **kwds)
support (self)
Additional Inherited Members
Public Attributes inherited from scipy.stats._distn_infrastructure.rv_frozen
args = args
kwds = kwds
dist = dist.__class__(**dist._updated_ctor_param())
a
b = self.dist._get_support(*shapes)
Detailed Description
Definition at line 541 of file _distn_infrastructure.py.
Member Function Documentation
logpmf()
scipy.stats._distn_infrastructure.rv_discrete_frozen.logpmf (self, k)
Definition at line 546 of file _distn_infrastructure.py.
Referenced by scipy.stats._multivariate.dirichlet_multinomial_gen.pmf(), scipy.stats._multivariate.multinomial_gen.pmf(), scipy.stats._multivariate.multivariate_hypergeom_gen.pmf(), and scipy.stats._multivariate.random_table_gen.pmf().
pmf()
scipy.stats._distn_infrastructure.rv_discrete_frozen.pmf (self, k)
Definition at line 543 of file _distn_infrastructure.py.
Referenced by scipy.stats._discrete_distns.hypergeom_gen._argcheck(), scipy.stats._distn_infrastructure.rv_discrete.isf(), scipy.stats._page_trend_test._PageL.pmf(), and scipy.stats._page_trend_test._PageL.sf().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/stats/_distn_infrastructure.py