Code Cloning Analysis: pandas.core.internals.concat Namespace Reference
pandas.core.internals.concat Namespace Reference
Classes
class JoinUnit
Functions
Manager2D _concatenate_array_managers (list[ArrayManager] mgrs, list[Index] axes, AxisInt concat_axis)
Manager2D concatenate_managers (mgrs_indexers, list[Index] axes, AxisInt concat_axis, bool copy)
list[BlockManager] _maybe_reindex_columns_na_proxy (list[Index] axes, list[tuple[BlockManager, dict[int, np.ndarray]]] mgrs_indexers, bool needs_copy)
bool _is_homogeneous_mgr (BlockManager mgr, DtypeObj first_dtype)
Block _concat_homogeneous_fastpath (mgrs_indexers, Shape shape, np.dtype first_dtype)
list[tuple[BlockPlacement, list[JoinUnit]]] _get_combined_plan (list[BlockManager] mgrs)
Block _get_block_for_concat_plan (BlockManager mgr, BlockPlacement bp, int blkno, *, int max_len)
ArrayLike _concatenate_join_units (list[JoinUnit] join_units, bool copy)
_dtype_to_na_value (DtypeObj dtype, bool has_none_blocks)
tuple[DtypeObj, DtypeObj] _get_empty_dtype (Sequence[JoinUnit] join_units)
bool _is_uniform_join_units (list[JoinUnit] join_units)
Function Documentation
_concat_homogeneous_fastpath()
Block pandas.core.internals.concat._concat_homogeneous_fastpath (mgrs_indexers, Shape shape, np.dtype first_dtype) protected
With single-Block managers with homogeneous dtypes (that can already hold nan),
we avoid [...]
Definition at line 249 of file concat.py.
Referenced by concatenate_managers().
_concatenate_array_managers()
Manager2D pandas.core.internals.concat._concatenate_array_managers (list[ArrayManager] mgrs, list[Index] axes, AxisInt concat_axis) protected
Concatenate array managers into one.
Parameters
----------
mgrs_indexers : list of (ArrayManager, {axis: indexer,...}) tuples
axes : list of Index
concat_axis : int
Returns
-------
ArrayManager
Definition at line 70 of file concat.py.
Referenced by concatenate_managers().
_concatenate_join_units()
ArrayLike pandas.core.internals.concat._concatenate_join_units (list[JoinUnit] join_units, bool copy) protected
Concatenate values from several join units along axis=1.
Definition at line 457 of file concat.py.
References _dtype_to_na_value(), and _get_empty_dtype().
Referenced by concatenate_managers().
_dtype_to_na_value()
pandas.core.internals.concat._dtype_to_na_value (DtypeObj dtype, bool has_none_blocks) protected
Find the NA value to go with this dtype.
Definition at line 503 of file concat.py.
Referenced by _concatenate_join_units().
_get_block_for_concat_plan()
Block pandas.core.internals.concat._get_block_for_concat_plan (BlockManager mgr, BlockPlacement bp, int blkno, * , int max_len) protected
Definition at line 322 of file concat.py.
_get_combined_plan()
list[tuple[BlockPlacement, list[JoinUnit]]] pandas.core.internals.concat._get_combined_plan (list[BlockManager] mgrs) protected
Definition at line 296 of file concat.py.
_get_empty_dtype()
tuple[DtypeObj, DtypeObj] pandas.core.internals.concat._get_empty_dtype (Sequence[JoinUnit] join_units) protected
Return dtype and N/A values to use when concatenating specified units.
Returned N/A value may be None which means there was no casting involved.
Returns
-------
dtype
Definition at line 526 of file concat.py.
Referenced by _concatenate_join_units().
_is_homogeneous_mgr()
bool pandas.core.internals.concat._is_homogeneous_mgr (BlockManager mgr, DtypeObj first_dtype) protected
Check if this Manager can be treated as a single ndarray.
Definition at line 236 of file concat.py.
Referenced by concatenate_managers().
_is_uniform_join_units()
bool pandas.core.internals.concat._is_uniform_join_units (list[JoinUnit] join_units) protected
Check if the join units consist of blocks of uniform type that can
be concatenated using Block.concat_same_type instead of the generic
_concatenate_join_units (which uses `concat_compat`).
Definition at line 572 of file concat.py.
Referenced by concatenate_managers().
_maybe_reindex_columns_na_proxy()
list[BlockManager] pandas.core.internals.concat._maybe_reindex_columns_na_proxy (list[Index] axes, list[tuple[BlockManager, dict[int, np.ndarray]]] mgrs_indexers, bool needs_copy) protected
Reindex along columns so that all of the BlockManagers being concatenated
have matching columns.
Columns added in this reindexing have dtype=np.void, indicating they
should be ignored when choosing a column's final dtype.
Definition at line 202 of file concat.py.
Referenced by concatenate_managers().
concatenate_managers()
Manager2D pandas.core.internals.concat.concatenate_managers (mgrs_indexers, list[Index] axes, AxisInt concat_axis, bool copy)
Concatenate block managers into one.
Parameters
----------
mgrs_indexers : list of (BlockManager, {axis: indexer,...}) tuples
axes : list of Index
concat_axis : int
copy : bool
Returns
-------
BlockManager
Definition at line 94 of file concat.py.
References _concat_homogeneous_fastpath(), _concatenate_array_managers(), _concatenate_join_units(), _is_homogeneous_mgr(), _is_uniform_join_units(), and _maybe_reindex_columns_na_proxy().