Code Cloning Analysis: fontTools.ttLib.tables.otTables.VarCompositeGlyph Class Reference
fontTools.ttLib.tables.otTables.VarCompositeGlyph Class Reference
Public Member Functions
__init__ (self, components=None)
decompile (self, data, font, localState)
compile (self, font)
toXML (self, xmlWriter, font, attrs, name)
fromXML (self, name, attrs, content, font)
Public Attributes
list components = components if components is not None else []
Detailed Description
Definition at line 404 of file otTables.py.
Constructor & Destructor Documentation
__init__()
fontTools.ttLib.tables.otTables.VarCompositeGlyph.__init__ (self, components = None)
Definition at line 405 of file otTables.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
compile()
fontTools.ttLib.tables.otTables.VarCompositeGlyph.compile (self, font)
Definition at line 415 of file otTables.py.
Referenced by fontTools.ttLib.tables.TupleVariation.TupleVariation.getCoordWidth(), and PIL.FontFile.FontFile.save().
decompile()
fontTools.ttLib.tables.otTables.VarCompositeGlyph.decompile (self, data, font, localState)
Definition at line 408 of file otTables.py.
Referenced by fontTools.ttLib.tables._c_m_a_p.CmapSubtable.newSubtable().
fromXML()
fontTools.ttLib.tables.otTables.VarCompositeGlyph.fromXML (self, name, attrs, content, font)
Definition at line 429 of file otTables.py.
toXML()
fontTools.ttLib.tables.otTables.VarCompositeGlyph.toXML (self, xmlWriter, font, attrs, name)
Definition at line 421 of file otTables.py.
Member Data Documentation
components
fontTools.ttLib.tables.otTables.VarCompositeGlyph.components = components if components is not None else []
Definition at line 406 of file otTables.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ttLib/tables/otTables.py