Code Cloning Analysis: fontTools.ttLib.tables.otTables.InsertionMorphAction Class Reference
fontTools.ttLib.tables.otTables.InsertionMorphAction Class Reference
Public Member Functions
__init__ (self)
compile (self, writer, font, actionIndex)
decompile (self, reader, font, actionReader)
toXML (self, xmlWriter, font, attrs, name)
fromXML (self, name, attrs, content, font)
Static Public Member Functions
compileActions (font, states)
Public Attributes
int NewState = 0
int ReservedFlags = 0
CurrentInsertionAction = len(self.MarkedInsertionAction)
list MarkedInsertionAction = [], []
SetMark
DontAdvance = 0x8000
CurrentIsKashidaLike = 0x4000
MarkedIsKashidaLike = 0x2000
CurrentInsertBefore = 0x1000
MarkedInsertBefore = 0x0800
Static Public Attributes
int staticSize = 8
int actionHeaderSize = 4
Protected Member Functions
_decompileInsertionAction (self, actionReader, font, index, count)
Protected Member Functions inherited from fontTools.ttLib.tables.otTables.AATAction
_writeFlagsToXML (self, xmlWriter)
_setFlag (self, flag)
Additional Inherited Members
Static Protected Attributes inherited from fontTools.ttLib.tables.otTables.AATAction
_FLAGS = None
Detailed Description
Definition at line 777 of file otTables.py.
Constructor & Destructor Documentation
__init__()
fontTools.ttLib.tables.otTables.InsertionMorphAction.__init__ (self)
Definition at line 789 of file otTables.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_decompileInsertionAction()
fontTools.ttLib.tables.otTables.InsertionMorphAction._decompileInsertionAction (self, actionReader, font, index, count) protected
Definition at line 843 of file otTables.py.
compile()
fontTools.ttLib.tables.otTables.InsertionMorphAction.compile (self, writer, font, actionIndex)
Definition at line 796 of file otTables.py.
Referenced by fontTools.ttLib.tables.TupleVariation.TupleVariation.getCoordWidth(), and PIL.FontFile.FontFile.save().
compileActions()
fontTools.ttLib.tables.otTables.InsertionMorphAction.compileActions (font, states) static
Reimplemented from fontTools.ttLib.tables.otTables.AATAction.
Definition at line 881 of file otTables.py.
decompile()
fontTools.ttLib.tables.otTables.InsertionMorphAction.decompile (self, reader, font, actionReader)
Definition at line 826 of file otTables.py.
Referenced by fontTools.ttLib.tables._c_m_a_p.CmapSubtable.newSubtable().
fromXML()
fontTools.ttLib.tables.otTables.InsertionMorphAction.fromXML (self, name, attrs, content, font)
Definition at line 864 of file otTables.py.
toXML()
fontTools.ttLib.tables.otTables.InsertionMorphAction.toXML (self, xmlWriter, font, attrs, name)
Definition at line 849 of file otTables.py.
Member Data Documentation
actionHeaderSize
int fontTools.ttLib.tables.otTables.InsertionMorphAction.actionHeaderSize = 4 static
Definition at line 779 of file otTables.py.
CurrentInsertBefore
fontTools.ttLib.tables.otTables.InsertionMorphAction.CurrentInsertBefore = 0x1000
Definition at line 808 of file otTables.py.
CurrentInsertionAction
fontTools.ttLib.tables.otTables.InsertionMorphAction.CurrentInsertionAction = len(self.MarkedInsertionAction)
Definition at line 794 of file otTables.py.
CurrentIsKashidaLike
fontTools.ttLib.tables.otTables.InsertionMorphAction.CurrentIsKashidaLike = 0x4000
Definition at line 804 of file otTables.py.
DontAdvance
fontTools.ttLib.tables.otTables.InsertionMorphAction.DontAdvance = 0x8000
Definition at line 802 of file otTables.py.
MarkedInsertBefore
fontTools.ttLib.tables.otTables.InsertionMorphAction.MarkedInsertBefore = 0x0800
Definition at line 810 of file otTables.py.
MarkedInsertionAction
fontTools.ttLib.tables.otTables.InsertionMorphAction.MarkedInsertionAction = [], []
Definition at line 794 of file otTables.py.
MarkedIsKashidaLike
fontTools.ttLib.tables.otTables.InsertionMorphAction.MarkedIsKashidaLike = 0x2000
Definition at line 806 of file otTables.py.
NewState
fontTools.ttLib.tables.otTables.InsertionMorphAction.NewState = 0
Definition at line 790 of file otTables.py.
ReservedFlags
int fontTools.ttLib.tables.otTables.InsertionMorphAction.ReservedFlags = 0
Definition at line 793 of file otTables.py.
SetMark
fontTools.ttLib.tables.otTables.InsertionMorphAction.SetMark
Definition at line 800 of file otTables.py.
staticSize
int fontTools.ttLib.tables.otTables.InsertionMorphAction.staticSize = 8 static
Definition at line 778 of file otTables.py.
Referenced by fontTools.ttLib.tables.otConverters.BaseConverter.readArray().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ttLib/tables/otTables.py