Code Cloning Analysis: sklearn.metrics.tests.test_common Namespace Reference
sklearn.metrics.tests.test_common Namespace Reference
Functions
precision_recall_curve_padded_thresholds (*args, **kwargs)
_require_positive_targets (y1, y2)
_require_log1p_targets (y1, y2)
test_symmetry_consistency ()
test_symmetric_metric (name)
test_not_symmetric_metric (name)
test_symmetry_tests ()
test_sample_order_invariance (name)
test_sample_order_invariance_multilabel_and_multioutput ()
test_format_invariance_with_1d_vectors (name)
test_classification_invariance_string_vs_numbers_labels (name)
test_thresholded_invariance_string_vs_numbers_labels (name)
test_regression_thresholded_inf_nan_input (metric, y_true, y_score)
test_classification_inf_nan_input (metric, y_true, y_score)
test_classification_binary_continuous_input (metric)
check_single_sample (name)
check_single_sample_multioutput (name)
test_single_sample (name)
test_single_sample_multioutput (name)
test_multioutput_number_of_output_differ (name)
test_multioutput_regression_invariance_to_dimension_shuffling (name)
test_multilabel_representation_invariance (coo_container)
test_raise_value_error_multilabel_sequences (name)
test_normalize_option_binary_classification (name)
test_normalize_option_multiclass_classification (name)
test_normalize_option_multilabel_classification (name)
_check_averaging (metric, y_true, y_pred, y_true_binarize, y_pred_binarize, is_multilabel)
check_averaging (name, y_true, y_true_binarize, y_pred, y_pred_binarize, y_score)
test_averaging_multiclass (name)
test_averaging_multilabel (name)
test_averaging_multilabel_all_zeroes (name)
test_averaging_binary_multilabel_all_zeroes ()
test_averaging_multilabel_all_ones (name)
check_sample_weight_invariance (name, metric, y1, y2)
test_regression_sample_weight_invariance (name)
test_regression_with_invalid_sample_weight (name)
test_binary_sample_weight_invariance (name)
test_multiclass_sample_weight_invariance (name)
test_multilabel_sample_weight_invariance (name)
test_multioutput_sample_weight_invariance (name)
test_no_averaging_labels ()
test_multilabel_label_permutations_invariance (name)
test_thresholded_multilabel_multioutput_permutations_invariance (name)
test_thresholded_metric_permutation_invariance (name)
test_metrics_consistent_type_error (metric_name)
test_metrics_pos_label_error_str (metric, y_pred_threshold, dtype_y_str)
check_array_api_metric (metric, array_namespace, device, dtype_name, a_np, b_np, **metric_kwargs)
check_array_api_binary_classification_metric (metric, array_namespace, device, dtype_name)
check_array_api_multiclass_classification_metric (metric, array_namespace, device, dtype_name)
check_array_api_multilabel_classification_metric (metric, array_namespace, device, dtype_name)
check_array_api_regression_metric (metric, array_namespace, device, dtype_name)
check_array_api_regression_metric_multioutput (metric, array_namespace, device, dtype_name)
check_array_api_metric_pairwise (metric, array_namespace, device, dtype_name)
yield_metric_checker_combinations (metric_checkers=array_api_metric_checkers)
test_array_api_compliance (metric, array_namespace, device, dtype_name, check_func)
test_metrics_dataframe_series (metric_name, df_lib_name)
_get_metric_kwargs_for_array_api_testing (metric, params)
test_returned_value_consistency (name)
Variables
dict REGRESSION_METRICS
dict CLASSIFICATION_METRICS
dict CURVE_METRICS
dict THRESHOLDED_METRICS
ALL_METRICS = dict()
dict METRIC_UNDEFINED_BINARY
dict METRIC_UNDEFINED_MULTICLASS
dict METRIC_UNDEFINED_BINARY_MULTICLASS
dict METRICS_WITH_AVERAGING
dict THRESHOLDED_METRICS_WITH_AVERAGING
dict METRICS_WITH_POS_LABEL
dict METRICS_WITH_LABELS
dict METRICS_WITH_NORMALIZE_OPTION
dict THRESHOLDED_MULTILABEL_METRICS
dict MULTILABELS_METRICS
dict MULTIOUTPUT_METRICS
dict SYMMETRIC_METRICS
dict NOT_SYMMETRIC_METRICS
dict METRICS_WITHOUT_SAMPLE_WEIGHT
dict METRICS_REQUIRE_POSITIVE_Y
dict METRICS_WITH_LOG1P_Y
list invalids_nan_inf
dict array_api_metric_checkers
Function Documentation
_check_averaging()
sklearn.metrics.tests.test_common._check_averaging (metric, y_true, y_pred, y_true_binarize, y_pred_binarize, is_multilabel) protected
Definition at line 1329 of file test_common.py.
_get_metric_kwargs_for_array_api_testing()
sklearn.metrics.tests.test_common._get_metric_kwargs_for_array_api_testing (metric, params) protected
Helper function to enable specifying a variety of additional params and
their corresponding values, so that they can be passed to a metric function
when testing for array api compliance.
Definition at line 2299 of file test_common.py.
Referenced by test_classification_binary_continuous_input().
_require_log1p_targets()
sklearn.metrics.tests.test_common._require_log1p_targets (y1, y2) protected
Make targets strictly larger than -1
Definition at line 586 of file test_common.py.
References _require_log1p_targets(), and _require_positive_targets().
Referenced by _require_log1p_targets().
_require_positive_targets()
sklearn.metrics.tests.test_common._require_positive_targets (y1, y2) protected
Make targets strictly positive
Definition at line 578 of file test_common.py.
Referenced by _require_log1p_targets(), and test_returned_value_consistency().
check_array_api_binary_classification_metric()
sklearn.metrics.tests.test_common.check_array_api_binary_classification_metric (metric, array_namespace, device, dtype_name)
Definition at line 1933 of file test_common.py.
check_array_api_metric()
sklearn.metrics.tests.test_common.check_array_api_metric (metric, array_namespace, device, dtype_name, a_np, b_np, ** metric_kwargs)
Definition at line 1869 of file test_common.py.
check_array_api_metric_pairwise()
sklearn.metrics.tests.test_common.check_array_api_metric_pairwise (metric, array_namespace, device, dtype_name)
Definition at line 2133 of file test_common.py.
check_array_api_multiclass_classification_metric()
sklearn.metrics.tests.test_common.check_array_api_multiclass_classification_metric (metric, array_namespace, device, dtype_name)
Definition at line 1962 of file test_common.py.
check_array_api_multilabel_classification_metric()
sklearn.metrics.tests.test_common.check_array_api_multilabel_classification_metric (metric, array_namespace, device, dtype_name)
Definition at line 2002 of file test_common.py.
check_array_api_regression_metric()
sklearn.metrics.tests.test_common.check_array_api_regression_metric (metric, array_namespace, device, dtype_name)
Definition at line 2042 of file test_common.py.
check_array_api_regression_metric_multioutput()
sklearn.metrics.tests.test_common.check_array_api_regression_metric_multioutput (metric, array_namespace, device, dtype_name)
Definition at line 2084 of file test_common.py.
check_averaging()
sklearn.metrics.tests.test_common.check_averaging (name, y_true, y_true_binarize, y_pred, y_pred_binarize, y_score)
Definition at line 1383 of file test_common.py.
check_sample_weight_invariance()
sklearn.metrics.tests.test_common.check_sample_weight_invariance (name, metric, y1, y2)
Definition at line 1477 of file test_common.py.
check_single_sample()
sklearn.metrics.tests.test_common.check_single_sample (name)
Definition at line 1051 of file test_common.py.
check_single_sample_multioutput()
sklearn.metrics.tests.test_common.check_single_sample_multioutput (name)
Definition at line 1069 of file test_common.py.
precision_recall_curve_padded_thresholds()
sklearn.metrics.tests.test_common.precision_recall_curve_padded_thresholds (* args, ** kwargs)
The dimensions of precision-recall pairs and the threshold array as
returned by the precision_recall_curve do not match. See
func:`sklearn.metrics.precision_recall_curve`
This prevents implicit conversion of return value triple to an higher
dimensional np.array of dtype('float64') (it will be of dtype('object)
instead). This again is needed for assert_array_equal to work correctly.
As a workaround we pad the threshold array with NaN values to match
the dimension of precision and recall arrays respectively.
Definition at line 203 of file test_common.py.
test_array_api_compliance()
sklearn.metrics.tests.test_common.test_array_api_compliance (metric, array_namespace, device, dtype_name, check_func)
Definition at line 2278 of file test_common.py.
test_averaging_binary_multilabel_all_zeroes()
sklearn.metrics.tests.test_common.test_averaging_binary_multilabel_all_zeroes ()
Definition at line 1447 of file test_common.py.
test_averaging_multiclass()
sklearn.metrics.tests.test_common.test_averaging_multiclass (name)
Definition at line 1401 of file test_common.py.
test_averaging_multilabel()
sklearn.metrics.tests.test_common.test_averaging_multilabel (name)
Definition at line 1418 of file test_common.py.
test_averaging_multilabel_all_ones()
sklearn.metrics.tests.test_common.test_averaging_multilabel_all_ones (name)
Definition at line 1467 of file test_common.py.
test_averaging_multilabel_all_zeroes()
sklearn.metrics.tests.test_common.test_averaging_multilabel_all_zeroes (name)
Definition at line 1437 of file test_common.py.
test_binary_sample_weight_invariance()
sklearn.metrics.tests.test_common.test_binary_sample_weight_invariance (name)
Definition at line 1626 of file test_common.py.
test_classification_binary_continuous_input()
sklearn.metrics.tests.test_common.test_classification_binary_continuous_input (metric)
check that classification metrics raise a message of mixed type data
with continuous/binary target vectors.
Definition at line 1040 of file test_common.py.
References _get_metric_kwargs_for_array_api_testing().
test_classification_inf_nan_input()
sklearn.metrics.tests.test_common.test_classification_inf_nan_input (metric, y_true, y_score)
check that classification metrics raise a message mentioning the
occurrence of non-finite values in the target vectors.
Definition at line 1017 of file test_common.py.
test_classification_invariance_string_vs_numbers_labels()
sklearn.metrics.tests.test_common.test_classification_invariance_string_vs_numbers_labels (name)
Definition at line 886 of file test_common.py.
test_format_invariance_with_1d_vectors()
sklearn.metrics.tests.test_common.test_format_invariance_with_1d_vectors (name)
Definition at line 757 of file test_common.py.
test_metrics_consistent_type_error()
sklearn.metrics.tests.test_common.test_metrics_consistent_type_error (metric_name)
Definition at line 1816 of file test_common.py.
test_metrics_dataframe_series()
sklearn.metrics.tests.test_common.test_metrics_dataframe_series (metric_name, df_lib_name)
Definition at line 2284 of file test_common.py.
test_metrics_pos_label_error_str()
sklearn.metrics.tests.test_common.test_metrics_pos_label_error_str (metric, y_pred_threshold, dtype_y_str)
Definition at line 1843 of file test_common.py.
test_multiclass_sample_weight_invariance()
sklearn.metrics.tests.test_common.test_multiclass_sample_weight_invariance (name)
Definition at line 1649 of file test_common.py.
test_multilabel_label_permutations_invariance()
sklearn.metrics.tests.test_common.test_multilabel_label_permutations_invariance (name)
Definition at line 1737 of file test_common.py.
test_multilabel_representation_invariance()
sklearn.metrics.tests.test_common.test_multilabel_representation_invariance (coo_container)
Definition at line 1129 of file test_common.py.
test_multilabel_sample_weight_invariance()
sklearn.metrics.tests.test_common.test_multilabel_sample_weight_invariance (name)
Definition at line 1673 of file test_common.py.
test_multioutput_number_of_output_differ()
sklearn.metrics.tests.test_common.test_multioutput_number_of_output_differ (name)
Definition at line 1099 of file test_common.py.
test_multioutput_regression_invariance_to_dimension_shuffling()
sklearn.metrics.tests.test_common.test_multioutput_regression_invariance_to_dimension_shuffling (name)
Definition at line 1109 of file test_common.py.
test_multioutput_sample_weight_invariance()
sklearn.metrics.tests.test_common.test_multioutput_sample_weight_invariance (name)
Definition at line 1700 of file test_common.py.
test_no_averaging_labels()
sklearn.metrics.tests.test_common.test_no_averaging_labels ()
Definition at line 1709 of file test_common.py.
test_normalize_option_binary_classification()
sklearn.metrics.tests.test_common.test_normalize_option_binary_classification (name)
Definition at line 1222 of file test_common.py.
test_normalize_option_multiclass_classification()
sklearn.metrics.tests.test_common.test_normalize_option_multiclass_classification (name)
Definition at line 1251 of file test_common.py.
test_normalize_option_multilabel_classification()
sklearn.metrics.tests.test_common.test_normalize_option_multilabel_classification (name)
Definition at line 1282 of file test_common.py.
test_not_symmetric_metric()
sklearn.metrics.tests.test_common.test_not_symmetric_metric (name)
Definition at line 643 of file test_common.py.
test_raise_value_error_multilabel_sequences()
sklearn.metrics.tests.test_common.test_raise_value_error_multilabel_sequences (name)
Definition at line 1205 of file test_common.py.
test_regression_sample_weight_invariance()
sklearn.metrics.tests.test_common.test_regression_sample_weight_invariance (name)
Definition at line 1581 of file test_common.py.
test_regression_thresholded_inf_nan_input()
sklearn.metrics.tests.test_common.test_regression_thresholded_inf_nan_input (metric, y_true, y_score)
Definition at line 995 of file test_common.py.
test_regression_with_invalid_sample_weight()
sklearn.metrics.tests.test_common.test_regression_with_invalid_sample_weight (name)
Definition at line 1598 of file test_common.py.
test_returned_value_consistency()
sklearn.metrics.tests.test_common.test_returned_value_consistency (name)
Ensure that the returned values of all metrics are consistent.
It can either be a float, a numpy array, or a tuple of floats or numpy arrays.
It should not be a numpy float64 or float32.
Definition at line 2321 of file test_common.py.
References _require_positive_targets().
test_sample_order_invariance()
sklearn.metrics.tests.test_common.test_sample_order_invariance (name)
Definition at line 688 of file test_common.py.
test_sample_order_invariance_multilabel_and_multioutput()
sklearn.metrics.tests.test_common.test_sample_order_invariance_multilabel_and_multioutput ()
Definition at line 709 of file test_common.py.
test_single_sample()
sklearn.metrics.tests.test_common.test_single_sample (name)
Definition at line 1087 of file test_common.py.
test_single_sample_multioutput()
sklearn.metrics.tests.test_common.test_single_sample_multioutput (name)
Definition at line 1094 of file test_common.py.
test_symmetric_metric()
sklearn.metrics.tests.test_common.test_symmetric_metric (name)
Definition at line 609 of file test_common.py.
test_symmetry_consistency()
sklearn.metrics.tests.test_common.test_symmetry_consistency ()
Definition at line 596 of file test_common.py.
test_symmetry_tests()
sklearn.metrics.tests.test_common.test_symmetry_tests ()
Definition at line 669 of file test_common.py.
test_thresholded_invariance_string_vs_numbers_labels()
sklearn.metrics.tests.test_common.test_thresholded_invariance_string_vs_numbers_labels (name)
Definition at line 940 of file test_common.py.
test_thresholded_metric_permutation_invariance()
sklearn.metrics.tests.test_common.test_thresholded_metric_permutation_invariance (name)
Definition at line 1794 of file test_common.py.
test_thresholded_multilabel_multioutput_permutations_invariance()
sklearn.metrics.tests.test_common.test_thresholded_multilabel_multioutput_permutations_invariance (name)
Definition at line 1758 of file test_common.py.
yield_metric_checker_combinations()
sklearn.metrics.tests.test_common.yield_metric_checker_combinations (metric_checkers = array_api_metric_checkers)
Definition at line 2266 of file test_common.py.
Variable Documentation
ALL_METRICS
sklearn.metrics.tests.test_common.ALL_METRICS = dict()
Definition at line 274 of file test_common.py.
array_api_metric_checkers
dict sklearn.metrics.tests.test_common.array_api_metric_checkers
Definition at line 2162 of file test_common.py.
CLASSIFICATION_METRICS
dict sklearn.metrics.tests.test_common.CLASSIFICATION_METRICS
Definition at line 146 of file test_common.py.
CURVE_METRICS
dict sklearn.metrics.tests.test_common.CURVE_METRICS
Initial value:
=  {
    "roc_curve": roc_curve,
    "precision_recall_curve": precision_recall_curve_padded_thresholds,
    "det_curve": det_curve,
}
Definition at line 234 of file test_common.py.
invalids_nan_inf
list sklearn.metrics.tests.test_common.invalids_nan_inf
Initial value:
=  [
    ([0, 1], [np.inf, np.inf]),
    ([0, 1], [np.nan, np.nan]),
    ([0, 1], [np.nan, np.inf]),
    ([0, 1], [np.inf, 1]),
    ([0, 1], [np.nan, 1]),
]
Definition at line 982 of file test_common.py.
METRIC_UNDEFINED_BINARY
dict sklearn.metrics.tests.test_common.METRIC_UNDEFINED_BINARY
Initial value:
=  {
    "samples_f0.5_score",
    "samples_f1_score",
    "samples_f2_score",
    "samples_precision_score",
    "samples_recall_score",
    "samples_jaccard_score",
    "coverage_error",
    "unnormalized_multilabel_confusion_matrix_sample",
    "label_ranking_loss",
    "label_ranking_average_precision_score",
    "dcg_score",
    "ndcg_score",
}
Definition at line 290 of file test_common.py.
METRIC_UNDEFINED_BINARY_MULTICLASS
dict sklearn.metrics.tests.test_common.METRIC_UNDEFINED_BINARY_MULTICLASS
Initial value:
=  METRIC_UNDEFINED_BINARY.union(
    METRIC_UNDEFINED_MULTICLASS
)
Definition at line 326 of file test_common.py.
METRIC_UNDEFINED_MULTICLASS
dict sklearn.metrics.tests.test_common.METRIC_UNDEFINED_MULTICLASS
Initial value:
=  {
    "micro_roc_auc",
    "samples_roc_auc",
    "partial_roc_auc",
    "roc_auc_score",
    "weighted_roc_auc",
    "jaccard_score",
    # with default average='binary', multiclass is prohibited
    "precision_score",
    "recall_score",
    "f1_score",
    "f2_score",
    "f0.5_score",
    # curves
    "roc_curve",
    "precision_recall_curve",
    "det_curve",
}
Definition at line 306 of file test_common.py.
METRICS_REQUIRE_POSITIVE_Y
dict sklearn.metrics.tests.test_common.METRICS_REQUIRE_POSITIVE_Y
Initial value:
=  {
    "mean_poisson_deviance",
    "mean_gamma_deviance",
    "mean_compound_poisson_deviance",
    "d2_tweedie_score",
}
Definition at line 564 of file test_common.py.
METRICS_WITH_AVERAGING
dict sklearn.metrics.tests.test_common.METRICS_WITH_AVERAGING
Initial value:
=  {
    "precision_score",
    "recall_score",
    "f1_score",
    "f2_score",
    "f0.5_score",
    "jaccard_score",
}
Definition at line 331 of file test_common.py.
METRICS_WITH_LABELS
dict sklearn.metrics.tests.test_common.METRICS_WITH_LABELS
Definition at line 368 of file test_common.py.
METRICS_WITH_LOG1P_Y
dict sklearn.metrics.tests.test_common.METRICS_WITH_LOG1P_Y
Initial value:
=  {
    "mean_squared_log_error",
    "root_mean_squared_log_error",
}
Definition at line 572 of file test_common.py.
METRICS_WITH_NORMALIZE_OPTION
dict sklearn.metrics.tests.test_common.METRICS_WITH_NORMALIZE_OPTION
Initial value:
=  {
    "accuracy_score",
    "top_k_accuracy_score",
    "zero_one_loss",
}
Definition at line 406 of file test_common.py.
METRICS_WITH_POS_LABEL
dict sklearn.metrics.tests.test_common.METRICS_WITH_POS_LABEL
Initial value:
=  {
    "roc_curve",
    "precision_recall_curve",
    "det_curve",
    "brier_score_loss",
    "precision_score",
    "recall_score",
    "f1_score",
    "f2_score",
    "f0.5_score",
    "jaccard_score",
    "average_precision_score",
    "weighted_average_precision_score",
    "micro_average_precision_score",
    "samples_average_precision_score",
}
Definition at line 348 of file test_common.py.
METRICS_WITHOUT_SAMPLE_WEIGHT
dict sklearn.metrics.tests.test_common.METRICS_WITHOUT_SAMPLE_WEIGHT
Initial value:
=  {
    "median_absolute_error",
    "max_error",
    "ovo_roc_auc",
    "weighted_ovo_roc_auc",
}
Definition at line 557 of file test_common.py.
MULTILABELS_METRICS
dict sklearn.metrics.tests.test_common.MULTILABELS_METRICS
Definition at line 434 of file test_common.py.
MULTIOUTPUT_METRICS
dict sklearn.metrics.tests.test_common.MULTIOUTPUT_METRICS
Initial value:
=  {
    "mean_absolute_error",
    "median_absolute_error",
    "mean_squared_error",
    "mean_squared_log_error",
    "r2_score",
    "root_mean_squared_error",
    "root_mean_squared_log_error",
    "explained_variance_score",
    "mean_absolute_percentage_error",
    "mean_pinball_loss",
    "d2_pinball_score",
    "d2_absolute_error_score",
}
Definition at line 468 of file test_common.py.
NOT_SYMMETRIC_METRICS
dict sklearn.metrics.tests.test_common.NOT_SYMMETRIC_METRICS
Definition at line 521 of file test_common.py.
REGRESSION_METRICS
dict sklearn.metrics.tests.test_common.REGRESSION_METRICS
Initial value:
=  {
    "max_error": max_error,
    "mean_absolute_error": mean_absolute_error,
    "mean_squared_error": mean_squared_error,
    "mean_squared_log_error": mean_squared_log_error,
    "mean_pinball_loss": mean_pinball_loss,
    "median_absolute_error": median_absolute_error,
    "mean_absolute_percentage_error": mean_absolute_percentage_error,
    "explained_variance_score": explained_variance_score,
    "r2_score": partial(r2_score, multioutput="variance_weighted"),
    "root_mean_squared_error": root_mean_squared_error,
    "root_mean_squared_log_error": root_mean_squared_log_error,
    "mean_normal_deviance": partial(mean_tweedie_deviance, power=0),
    "mean_poisson_deviance": mean_poisson_deviance,
    "mean_gamma_deviance": mean_gamma_deviance,
    "mean_compound_poisson_deviance": partial(mean_tweedie_deviance, power=1.4),
    "d2_tweedie_score": partial(d2_tweedie_score, power=1.4),
    "d2_pinball_score": d2_pinball_score,
    "d2_absolute_error_score": d2_absolute_error_score,
}
Definition at line 125 of file test_common.py.
SYMMETRIC_METRICS
dict sklearn.metrics.tests.test_common.SYMMETRIC_METRICS
Definition at line 485 of file test_common.py.
THRESHOLDED_METRICS
dict sklearn.metrics.tests.test_common.THRESHOLDED_METRICS
Definition at line 240 of file test_common.py.
THRESHOLDED_METRICS_WITH_AVERAGING
dict sklearn.metrics.tests.test_common.THRESHOLDED_METRICS_WITH_AVERAGING
Initial value:
=  {
    "roc_auc_score",
    "average_precision_score",
    "partial_roc_auc",
}
Definition at line 341 of file test_common.py.
THRESHOLDED_MULTILABEL_METRICS
dict sklearn.metrics.tests.test_common.THRESHOLDED_MULTILABEL_METRICS
Initial value:
=  {
    "log_loss",
    "unnormalized_log_loss",
    "brier_score_loss",
    "roc_auc_score",
    "weighted_roc_auc",
    "samples_roc_auc",
    "micro_roc_auc",
    "partial_roc_auc",
    "average_precision_score",
    "weighted_average_precision_score",
    "samples_average_precision_score",
    "micro_average_precision_score",
    "coverage_error",
    "label_ranking_loss",
    "ndcg_score",
    "dcg_score",
    "label_ranking_average_precision_score",
}
Definition at line 413 of file test_common.py.