Code Cloning Analysis: scipy.fftpack.tests.test_real_transforms Namespace Reference
scipy.fftpack.tests.test_real_transforms Namespace Reference
Classes
class _TestDCTBase
class _TestDCTIBase
class _TestDCTIIBase
class _TestDCTIIIBase
class _TestDCTIVBase
class _TestDSTBase
class _TestDSTIBase
class _TestDSTIVBase
class _TestIDCTBase
class _TestIDSTBase
class Test_DCTN_IDCTN
class TestComplex
class TestDCTIDouble
class TestDCTIFloat
class TestDCTIIDouble
class TestDCTIIFloat
class TestDCTIIIDouble
class TestDCTIIIFloat
class TestDCTIIIInt
class TestDCTIIInt
class TestDCTIInt
class TestDCTIVDouble
class TestDCTIVFloat
class TestDCTIVInt
class TestDSTIDouble
class TestDSTIFloat
class TestDSTIIDouble
class TestDSTIIFloat
class TestDSTIIIDouble
class TestDSTIIIFloat
class TestDSTIIIInt
class TestDSTIIInt
class TestDSTIInt
class TestDSTIVDouble
class TestDSTIVFloat
class TestDSTIVInt
class TestIDCTIDouble
class TestIDCTIFloat
class TestIDCTIIDouble
class TestIDCTIIFloat
class TestIDCTIIIDouble
class TestIDCTIIIFloat
class TestIDCTIIIInt
class TestIDCTIIInt
class TestIDCTIInt
class TestIDCTIVDouble
class TestIDCTIVFloat
class TestIDCTIVInt
class TestIDSTIDouble
class TestIDSTIFloat
class TestIDSTIIDouble
class TestIDSTIIFloat
class TestIDSTIIIDouble
class TestIDSTIIIFloat
class TestIDSTIIIInt
class TestIDSTIIInt
class TestIDSTIInt
class TestIDSTIVDouble
class TestIDSTIVFloat
class TestIDSTIVnt
class TestOverwrite
Functions
fftw_dct_ref (type, size, dt)
fftw_dst_ref (type, size, dt)
dct_2d_ref (x, **kwargs)
idct_2d_ref (x, **kwargs)
dst_2d_ref (x, **kwargs)
idst_2d_ref (x, **kwargs)
naive_dct1 (x, norm=None)
naive_dst1 (x, norm=None)
naive_dct4 (x, norm=None)
naive_dst4 (x, norm=None)
Variables
MDATA = np.load(join(dirname(__file__), 'test.npz'))
list X = [MDATA['x%d' % i] for i in range(8)]
list Y = [MDATA['y%d' % i] for i in range(8)]
FFTWDATA_DOUBLE = np.load(join(dirname(__file__), 'fftw_double_ref.npz'))
FFTWDATA_SINGLE = np.load(join(dirname(__file__), 'fftw_single_ref.npz'))
FFTWDATA_SIZES = FFTWDATA_DOUBLE['sizes']
Function Documentation
dct_2d_ref()
scipy.fftpack.tests.test_real_transforms.dct_2d_ref (x, ** kwargs)
Calculate reference values for testing dct2.
Definition at line 52 of file test_real_transforms.py.
References scipy.fftpack._realtransforms.dct().
dst_2d_ref()
scipy.fftpack.tests.test_real_transforms.dst_2d_ref (x, ** kwargs)
Calculate reference values for testing dst2.
Definition at line 72 of file test_real_transforms.py.
References scipy.fftpack._realtransforms.dst().
fftw_dct_ref()
scipy.fftpack.tests.test_real_transforms.fftw_dct_ref (type, size, dt)
Definition at line 26 of file test_real_transforms.py.
fftw_dst_ref()
scipy.fftpack.tests.test_real_transforms.fftw_dst_ref (type, size, dt)
Definition at line 39 of file test_real_transforms.py.
idct_2d_ref()
scipy.fftpack.tests.test_real_transforms.idct_2d_ref (x, ** kwargs)
Calculate reference values for testing idct2.
Definition at line 62 of file test_real_transforms.py.
References scipy.fftpack._realtransforms.idct().
idst_2d_ref()
scipy.fftpack.tests.test_real_transforms.idst_2d_ref (x, ** kwargs)
Calculate reference values for testing idst2.
Definition at line 82 of file test_real_transforms.py.
References scipy.fftpack._realtransforms.idst().
naive_dct1()
scipy.fftpack.tests.test_real_transforms.naive_dct1 (x, norm = None)
Calculate textbook definition version of DCT-I.
Definition at line 92 of file test_real_transforms.py.
naive_dct4()
scipy.fftpack.tests.test_real_transforms.naive_dct4 (x, norm = None)
Calculate textbook definition version of DCT-IV.
Definition at line 127 of file test_real_transforms.py.
naive_dst1()
scipy.fftpack.tests.test_real_transforms.naive_dst1 (x, norm = None)
Calculate textbook definition version  of DST-I.
Definition at line 113 of file test_real_transforms.py.
naive_dst4()
scipy.fftpack.tests.test_real_transforms.naive_dst4 (x, norm = None)
Calculate textbook definition version of DST-IV.
Definition at line 142 of file test_real_transforms.py.
Variable Documentation
FFTWDATA_DOUBLE
scipy.fftpack.tests.test_real_transforms.FFTWDATA_DOUBLE = np.load(join(dirname(__file__), 'fftw_double_ref.npz'))
Definition at line 21 of file test_real_transforms.py.
FFTWDATA_SINGLE
scipy.fftpack.tests.test_real_transforms.FFTWDATA_SINGLE = np.load(join(dirname(__file__), 'fftw_single_ref.npz'))
Definition at line 22 of file test_real_transforms.py.
FFTWDATA_SIZES
scipy.fftpack.tests.test_real_transforms.FFTWDATA_SIZES = FFTWDATA_DOUBLE['sizes']
Definition at line 23 of file test_real_transforms.py.
MDATA
scipy.fftpack.tests.test_real_transforms.MDATA = np.load(join(dirname(__file__), 'test.npz'))
Definition at line 12 of file test_real_transforms.py.
X
list scipy.fftpack.tests.test_real_transforms.X = [MDATA['x%d' % i] for i in range(8)]
Definition at line 13 of file test_real_transforms.py.
Y
list scipy.fftpack.tests.test_real_transforms.Y = [MDATA['y%d' % i] for i in range(8)]
Definition at line 14 of file test_real_transforms.py.