Code Cloning Analysis: matplotlib.transforms Namespace Reference
matplotlib.transforms Namespace Reference
Classes
class _BlendedMixin
class _ScaledRotation
class Affine2D
class Affine2DBase
class AffineBase
class AffineDeltaTransform
class Bbox
class BboxBase
class BboxTransform
class BboxTransformFrom
class BboxTransformTo
class BboxTransformToMaxOnly
class BlendedAffine2D
class BlendedGenericTransform
class CompositeAffine2D
class CompositeGenericTransform
class IdentityTransform
class LockableBbox
class ScaledTranslation
class Transform
class TransformedBbox
class TransformedPatchPath
class TransformedPath
class TransformNode
class TransformWrapper
Functions
_make_str_method (*args, **kwargs)
blended_transform_factory (x_transform, y_transform)
composite_transform_factory (a, b)
nonsingular (vmin, vmax, expander=0.001, tiny=1e-15, increasing=True)
interval_contains (interval, val)
_interval_contains_close (interval, val, rtol=1e-10)
interval_contains_open (interval, val)
offset_copy (trans, fig=None, x=0.0, y=0.0, units='inches')
Variables
bool DEBUG = False
_default_minpos = np.array([np.inf, np.inf])
Detailed Description
Matplotlib includes a framework for arbitrary geometric transformations that is used to
determine the final position of all elements drawn on the canvas.
Transforms are composed into trees of `TransformNode` objects
whose actual value depends on their children.  When the contents of
children change, their parents are automatically invalidated.  The
next time an invalidated transform is accessed, it is recomputed to
reflect those changes.  This invalidation/caching approach prevents
unnecessary recomputations of transforms, and contributes to better
interactive performance.
For example, here is a graph of the transform tree used to plot data to the figure:
.. graphviz:: /api/transforms.dot
    :alt: Diagram of transform tree from data to figure coordinates.
The framework can be used for both affine and non-affine
transformations.  However, for speed, we want to use the backend
renderers to perform affine transformations whenever possible.
Therefore, it is possible to perform just the affine or non-affine
part of a transformation on a set of data.  The affine is always
assumed to occur after the non-affine.  For any transform::
  full transform == non-affine part + affine part
The backends are not expected to handle non-affine transformations
themselves.
See the tutorial :ref:`transforms_tutorial` for examples
of how to use transforms.
Function Documentation
_interval_contains_close()
matplotlib.transforms._interval_contains_close (interval, val, rtol = 1e-10) protected
Check, inclusively, whether an interval includes a given value, with the
interval expanded by a small tolerance to admit floating point errors.
Parameters
----------
interval : (float, float)
    The endpoints of the interval.
val : float
    Value to check is within interval.
rtol : float, default: 1e-10
    Relative tolerance slippage allowed outside of the interval.
    For an interval ``[a, b]``, values
    ``a - rtol * (b - a) <= val <= b + rtol * (b - a)`` are considered
    inside the interval.
Returns
-------
bool
    Whether *val* is within the *interval* (with tolerance).
Definition at line 2917 of file transforms.py.
_make_str_method()
matplotlib.transforms._make_str_method (* args, ** kwargs) protected
Generate a ``__str__`` method for a `.Transform` subclass.
After ::
    class T:
        __str__ = _make_str_method("attr", key="other")
``str(T(...))`` will be
.. code-block:: text
    {type(T).__name__}(
        {self.attr},
        key={self.other})
Definition at line 56 of file transforms.py.
Referenced by matplotlib.transforms.Affine2D.__init__(), matplotlib.transforms.BboxTransform.__init__(), matplotlib.transforms.BboxTransformTo.__init__(), matplotlib.transforms.LockableBbox.__init__(), matplotlib.transforms.TransformedBbox.__init__(), matplotlib.transforms.TransformWrapper.__init__(), matplotlib.transforms.CompositeAffine2D._iter_break_from_left_to_right(), matplotlib.transforms.CompositeGenericTransform.contains_branch_seperately(), and matplotlib.transforms.IdentityTransform.frozen().
blended_transform_factory()
matplotlib.transforms.blended_transform_factory (x_transform, y_transform)
Create a new "blended" transform using *x_transform* to transform
the *x*-axis and *y_transform* to transform the *y*-axis.
A faster version of the blended transform is returned for the case
where both child transforms are affine.
Definition at line 2317 of file transforms.py.
Referenced by matplotlib.transforms.BlendedGenericTransform.frozen().
composite_transform_factory()
matplotlib.transforms.composite_transform_factory (a, b)
Create a new composite transform that is the result of applying
transform a then transform b.
Shortcut versions of the blended transform are provided for the
case where both child transforms are affine, or one or the other
is the identity transform.
Composite transforms may also be created using the '+' operator,
e.g.::
  c = a + b
Definition at line 2498 of file transforms.py.
Referenced by matplotlib.transforms.Transform.__add__(), and matplotlib.transforms.CompositeGenericTransform.frozen().
interval_contains()
matplotlib.transforms.interval_contains (interval, val)
Check, inclusively, whether an interval includes a given value.
Parameters
----------
interval : (float, float)
    The endpoints of the interval.
val : float
    Value to check is within interval.
Returns
-------
bool
    Whether *val* is within the *interval*.
Definition at line 2895 of file transforms.py.
interval_contains_open()
matplotlib.transforms.interval_contains_open (interval, val)
Check, excluding endpoints, whether an interval includes a given value.
Parameters
----------
interval : (float, float)
    The endpoints of the interval.
val : float
    Value to check is within interval.
Returns
-------
bool
    Whether *val* is within the *interval*.
Definition at line 2946 of file transforms.py.
nonsingular()
matplotlib.transforms.nonsingular (vmin, vmax, expander = 0.001, tiny = 1e-15, increasing = True)
Modify the endpoints of a range as needed to avoid singularities.
Parameters
----------
vmin, vmax : float
    The initial endpoints.
expander : float, default: 0.001
    Fractional amount by which *vmin* and *vmax* are expanded if
    the original interval is too small, based on *tiny*.
tiny : float, default: 1e-15
    Threshold for the ratio of the interval to the maximum absolute
    value of its endpoints.  If the interval is smaller than
    this, it will be expanded.  This value should be around
    1e-15 or larger; otherwise the interval will be approaching
    the double precision resolution limit.
increasing : bool, default: True
    If True, swap *vmin*, *vmax* if *vmin* > *vmax*.
Returns
-------
vmin, vmax : float
    Endpoints, expanded and/or swapped if necessary.
    If either input is inf or NaN, or if both inputs are 0 or very
    close to zero, it returns -*expander*, *expander*.
Definition at line 2837 of file transforms.py.
offset_copy()
matplotlib.transforms.offset_copy (trans, fig = None, x = 0.0, y = 0.0, units = 'inches')
Return a new transform with an added offset.
Parameters
----------
trans : `Transform` subclass
    Any transform, to which offset will be applied.
fig : `~matplotlib.figure.Figure`, default: None
    Current figure. It can be None if *units* are 'dots'.
x, y : float, default: 0.0
    The offset to apply.
units : {'inches', 'points', 'dots'}, default: 'inches'
    Units of the offset.
Returns
-------
`Transform` subclass
    Transform with applied offset.
Definition at line 2966 of file transforms.py.
Variable Documentation
_default_minpos
matplotlib.transforms._default_minpos = np.array([np.inf, np.inf]) protected
Definition at line 665 of file transforms.py.
DEBUG
bool matplotlib.transforms.DEBUG = False
Definition at line 53 of file transforms.py.