Code Cloning Analysis: sklearn.manifold._spectral_embedding Namespace Reference
sklearn.manifold._spectral_embedding Namespace Reference
Classes
class SpectralEmbedding
Functions
_graph_connected_component (graph, node_id)
_graph_is_connected (graph)
_set_diag (laplacian, value, norm_laplacian)
spectral_embedding (adjacency, *, n_components=8, eigen_solver=None, random_state=None, eigen_tol="auto", norm_laplacian=True, drop_first=True)
_spectral_embedding (adjacency, *, n_components=8, eigen_solver=None, random_state=None, eigen_tol="auto", norm_laplacian=True, drop_first=True)
Detailed Description
Spectral Embedding.
Function Documentation
_graph_connected_component()
sklearn.manifold._spectral_embedding._graph_connected_component (graph, node_id) protected
Find the largest graph connected components that contains one
given node.
Parameters
----------
graph : array-like of shape (n_samples, n_samples)
    Adjacency matrix of the graph, non-zero weight means an edge
    between the nodes.
node_id : int
    The index of the query node of the graph.
Returns
-------
connected_components_matrix : array-like of shape (n_samples,)
    An array of bool value indicating the indexes of the nodes
    belonging to the largest connected components of the given query
    node.
Definition at line 31 of file _spectral_embedding.py.
Referenced by _graph_is_connected().
_graph_is_connected()
sklearn.manifold._spectral_embedding._graph_is_connected (graph) protected
Return whether the graph is connected (True) or Not (False).
Parameters
----------
graph : {array-like, sparse matrix} of shape (n_samples, n_samples)
    Adjacency matrix of the graph, non-zero weight means an edge
    between the nodes.
Returns
-------
is_connected : bool
    True means the graph is fully connected and False means not.
Definition at line 76 of file _spectral_embedding.py.
References _graph_connected_component().
Referenced by spectral_embedding().
_set_diag()
sklearn.manifold._spectral_embedding._set_diag (laplacian, value, norm_laplacian) protected
Set the diagonal of the laplacian matrix and convert it to a
sparse format well suited for eigenvalue decomposition.
Parameters
----------
laplacian : {ndarray, sparse matrix}
    The graph laplacian.
value : float
    The value of the diagonal.
norm_laplacian : bool
    Whether the value of the diagonal should be changed or not.
Returns
-------
laplacian : {array, sparse matrix}
    An array of matrix in a form that is well suited to fast
    eigenvalue decomposition, depending on the band width of the
    matrix.
Definition at line 108 of file _spectral_embedding.py.
Referenced by spectral_embedding().
_spectral_embedding()
sklearn.manifold._spectral_embedding._spectral_embedding (adjacency, * , n_components = 8, eigen_solver = None, random_state = None, eigen_tol = "auto", norm_laplacian = True, drop_first = True) protected
Definition at line 299 of file _spectral_embedding.py.
spectral_embedding()
sklearn.manifold._spectral_embedding.spectral_embedding (adjacency, * , n_components = 8, eigen_solver = None, random_state = None, eigen_tol = "auto", norm_laplacian = True, drop_first = True)
Project the sample on the first eigenvectors of the graph Laplacian.
The adjacency matrix is used to compute a normalized graph Laplacian
whose spectrum (especially the eigenvectors associated to the
smallest eigenvalues) has an interpretation in terms of minimal
number of cuts necessary to split the graph into comparably sized
components.
This embedding can also 'work' even if the ``adjacency`` variable is
not strictly the adjacency matrix of a graph but more generally
an affinity or similarity matrix between samples (for instance the
heat kernel of a euclidean distance matrix or a k-NN matrix).
However care must taken to always make the affinity matrix symmetric
so that the eigenvector decomposition works as expected.
Note : Laplacian Eigenmaps is the actual algorithm implemented here.
Read more in the :ref:`User Guide <spectral_embedding>`.
Parameters
----------
adjacency : {array-like, sparse graph} of shape (n_samples, n_samples)
    The adjacency matrix of the graph to embed.
n_components : int, default=8
    The dimension of the projection subspace.
eigen_solver : {'arpack', 'lobpcg', 'amg'}, default=None
    The eigenvalue decomposition strategy to use. AMG requires pyamg
    to be installed. It can be faster on very large, sparse problems,
    but may also lead to instabilities. If None, then ``'arpack'`` is
    used.
random_state : int, RandomState instance or None, default=None
    A pseudo random number generator used for the initialization
    of the lobpcg eigen vectors decomposition when `eigen_solver ==
    'amg'`, and for the K-Means initialization. Use an int to make
    the results deterministic across calls (See
    :term:`Glossary <random_state>`).
    .. note::
        When using `eigen_solver == 'amg'`,
        it is necessary to also fix the global numpy seed with
        `np.random.seed(int)` to get deterministic results. See
        https://github.com/pyamg/pyamg/issues/139 for further
        information.
eigen_tol : float, default="auto"
    Stopping criterion for eigendecomposition of the Laplacian matrix.
    If `eigen_tol="auto"` then the passed tolerance will depend on the
    `eigen_solver`:
    - If `eigen_solver="arpack"`, then `eigen_tol=0.0`;
    - If `eigen_solver="lobpcg"` or `eigen_solver="amg"`, then
      `eigen_tol=None` which configures the underlying `lobpcg` solver to
      automatically resolve the value according to their heuristics. See,
      :func:`scipy.sparse.linalg.lobpcg` for details.
    Note that when using `eigen_solver="amg"` values of `tol<1e-5` may lead
    to convergence issues and should be avoided.
    .. versionadded:: 1.2
       Added 'auto' option.
norm_laplacian : bool, default=True
    If True, then compute symmetric normalized Laplacian.
drop_first : bool, default=True
    Whether to drop the first eigenvector. For spectral embedding, this
    should be True as the first eigenvector should be constant vector for
    connected graph, but for spectral clustering, this should be kept as
    False to retain the first eigenvector.
Returns
-------
embedding : ndarray of shape (n_samples, n_components)
    The reduced samples.
Notes
-----
Spectral Embedding (Laplacian Eigenmaps) is most useful when the graph
has one connected component. If there graph has many components, the first
few eigenvectors will simply uncover the connected components of the graph.
References
----------
* https://en.wikipedia.org/wiki/LOBPCG
* :doi:`"Toward the Optimal Preconditioned Eigensolver: Locally Optimal
  Block Preconditioned Conjugate Gradient Method",
  Andrew V. Knyazev
  <10.1137/S1064827500366124>`
Examples
--------
>>> from sklearn.datasets import load_digits
>>> from sklearn.neighbors import kneighbors_graph
>>> from sklearn.manifold import spectral_embedding
>>> X, _ = load_digits(return_X_y=True)
>>> X = X[:100]
>>> affinity_matrix = kneighbors_graph(
...     X, n_neighbors=int(X.shape[0] / 10), include_self=True
...)
>>> # make the matrix symmetric
>>> affinity_matrix = 0.5 * (affinity_matrix + affinity_matrix.T)
>>> embedding = spectral_embedding(affinity_matrix, n_components=2, random_state=42)
>>> embedding.shape
(100, 2)
Definition at line 166 of file _spectral_embedding.py.
References _graph_is_connected(), and _set_diag().