Code Cloning Analysis: scipy._lib._uarray._backend Namespace Reference
scipy._lib._uarray._backend Namespace Reference
Classes
class Dispatchable
Functions
unpickle_function (mod_name, qname, self_)
pickle_function (func)
pickle_state (state)
pickle_set_backend_context (ctx)
pickle_skip_backend_context (ctx)
get_state ()
reset_state ()
set_state (state)
create_multimethod (*args, **kwargs)
generate_multimethod (ArgumentExtractorType argument_extractor, ArgumentReplacerType argument_replacer, str domain, typing.Optional[typing.Callable] default=None)
set_backend (backend, coerce=False, only=False)
skip_backend (backend)
get_defaults (f)
set_global_backend (backend, coerce=False, only=False, *, try_last=False)
register_backend (backend)
clear_backends (domain, registered=True, globals=False)
mark_as (dispatch_type)
all_of_type (arg_type)
wrap_single_convertor (convert_single)
wrap_single_convertor_instance (convert_single)
determine_backend (value, dispatch_type, *, domain, only=True, coerce=False)
determine_backend_multi (dispatchables, *, domain, only=True, coerce=False, **kwargs)
Variables
list __all__
ArgumentExtractorType = typing.Callable[..., typing.Tuple["Dispatchable", ...]]
ArgumentReplacerType
Function Documentation
all_of_type()
scipy._lib._uarray._backend.all_of_type (arg_type)
Marks all unmarked arguments as a given type.
Examples
--------
>>> @all_of_type(str)
... def f(a, b):
...     return a, Dispatchable(b, int)
>>> f('a', 1)
(<Dispatchable: type=<class 'str'>, value='a'>, <Dispatchable: type=<class 'int'>, value=1>)
Definition at line 463 of file _backend.py.
clear_backends()
scipy._lib._uarray._backend.clear_backends (domain, registered = True, globals = False)
This utility method clears registered backends.
.. warning::
    We caution library authors against using this function in
    their code. We do *not* support this use-case. This function
    is meant to be used only by users themselves.
.. warning::
    Do NOT use this method inside a multimethod call, or the
    program is likely to crash.
Parameters
----------
domain : Optional[str]
    The domain for which to de-register backends. ``None`` means
    de-register for all domains.
registered : bool
    Whether or not to clear registered backends. See :obj:`register_backend`.
globals : bool
    Whether or not to clear global backends. See :obj:`set_global_backend`.
See Also
--------
register_backend : Register a backend globally.
set_global_backend : Set a global backend.
Definition at line 375 of file _backend.py.
create_multimethod()
scipy._lib._uarray._backend.create_multimethod (* args, ** kwargs)
Creates a decorator for generating multimethods.
This function creates a decorator that can be used with an argument
extractor in order to generate a multimethod. Other than for the
argument extractor, all arguments are passed on to
:obj:`generate_multimethod`.
See Also
--------
generate_multimethod
    Generates a multimethod.
Definition at line 152 of file _backend.py.
References generate_multimethod().
determine_backend()
scipy._lib._uarray._backend.determine_backend (value, dispatch_type, * , domain, only = True, coerce = False)
Set the backend to the first active backend that supports ``value``
This is useful for functions that call multimethods without any dispatchable
arguments. You can use :func:`determine_backend` to ensure the same backend
is used everywhere in a block of multimethod calls.
Parameters
----------
value
    The value being tested
dispatch_type
    The dispatch type associated with ``value``, aka
    ":ref:`marking <MarkingGlossary>`".
domain: string
    The domain to query for backends and set.
coerce: bool
    Whether or not to allow coercion to the backend's types. Implies ``only``.
only: bool
    Whether or not this should be the last backend to try.
See Also
--------
set_backend: For when you know which backend to set
Notes
-----
Support is determined by the ``__ua_convert__`` protocol. Backends not
supporting the type must return ``NotImplemented`` from their
``__ua_convert__`` if they don't support input of that type.
Examples
--------
Suppose we have two backends ``BackendA`` and ``BackendB`` each supporting
different types, ``TypeA`` and ``TypeB``. Neither supporting the other type:
>>> with ua.set_backend(ex.BackendA):
...     ex.call_multimethod(ex.TypeB(), ex.TypeB())
Traceback (most recent call last):
    ...
uarray.BackendNotImplementedError: ...
Now consider a multimethod that creates a new object of ``TypeA``, or
``TypeB`` depending on the active backend.
>>> with ua.set_backend(ex.BackendA), ua.set_backend(ex.BackendB):
...         res = ex.creation_multimethod()
...         ex.call_multimethod(res, ex.TypeA())
Traceback (most recent call last):
    ...
uarray.BackendNotImplementedError: ...
``res`` is an object of ``TypeB`` because ``BackendB`` is set in the
innermost with statement. So, ``call_multimethod`` fails since the types
don't match.
Instead, we need to first find a backend suitable for all of our objects.
>>> with ua.set_backend(ex.BackendA), ua.set_backend(ex.BackendB):
...     x = ex.TypeA()
...     with ua.determine_backend(x, "mark", domain="ua_examples"):
...         res = ex.creation_multimethod()
...         ex.call_multimethod(res, x)
TypeA
Definition at line 542 of file _backend.py.
References set_backend().
determine_backend_multi()
scipy._lib._uarray._backend.determine_backend_multi (dispatchables, * , domain, only = True, coerce = False, ** kwargs)
Set a backend supporting all ``dispatchables``
This is useful for functions that call multimethods without any dispatchable
arguments. You can use :func:`determine_backend_multi` to ensure the same
backend is used everywhere in a block of multimethod calls involving
multiple arrays.
Parameters
----------
dispatchables: Sequence[Union[uarray.Dispatchable, Any]]
    The dispatchables that must be supported
domain: string
    The domain to query for backends and set.
coerce: bool
    Whether or not to allow coercion to the backend's types. Implies ``only``.
only: bool
    Whether or not this should be the last backend to try.
dispatch_type: Optional[Any]
    The default dispatch type associated with ``dispatchables``, aka
    ":ref:`marking <MarkingGlossary>`".
See Also
--------
determine_backend: For a single dispatch value
set_backend: For when you know which backend to set
Notes
-----
Support is determined by the ``__ua_convert__`` protocol. Backends not
supporting the type must return ``NotImplemented`` from their
``__ua_convert__`` if they don't support input of that type.
Examples
--------
:func:`determine_backend` allows the backend to be set from a single
object. :func:`determine_backend_multi` allows multiple objects to be
checked simultaneously for support in the backend. Suppose we have a
``BackendAB`` which supports ``TypeA`` and ``TypeB`` in the same call,
and a ``BackendBC`` that doesn't support ``TypeA``.
>>> with ua.set_backend(ex.BackendAB), ua.set_backend(ex.BackendBC):
...     a, b = ex.TypeA(), ex.TypeB()
...     with ua.determine_backend_multi(
...         [ua.Dispatchable(a, "mark"), ua.Dispatchable(b, "mark")],
...         domain="ua_examples"
...):
...         res = ex.creation_multimethod()
...         ex.call_multimethod(res, a, b)
TypeA
This won't call ``BackendBC`` because it doesn't support ``TypeA``.
We can also use leave out the ``ua.Dispatchable`` if we specify the
default ``dispatch_type`` for the ``dispatchables`` argument.
>>> with ua.set_backend(ex.BackendAB), ua.set_backend(ex.BackendBC):
...     a, b = ex.TypeA(), ex.TypeB()
...     with ua.determine_backend_multi(
...         [a, b], dispatch_type="mark", domain="ua_examples"
...):
...         res = ex.creation_multimethod()
...         ex.call_multimethod(res, a, b)
TypeA
Definition at line 616 of file _backend.py.
References set_backend().
generate_multimethod()
scipy._lib._uarray._backend.generate_multimethod (ArgumentExtractorType argument_extractor, ArgumentReplacerType argument_replacer, str domain, typing.Optional[typing.Callable] default = None)
Generates a multimethod.
Parameters
----------
argument_extractor : ArgumentExtractorType
    A callable which extracts the dispatchable arguments. Extracted arguments
    should be marked by the :obj:`Dispatchable` class. It has the same signature
    as the desired multimethod.
argument_replacer : ArgumentReplacerType
    A callable with the signature (args, kwargs, dispatchables), which should also
    return an (args, kwargs) pair with the dispatchables replaced inside the args/kwargs.
domain : str
    A string value indicating the domain of this multimethod.
default: Optional[Callable], optional
    The default implementation of this multimethod, where ``None`` (the default) specifies
    there is no default implementation.
Examples
--------
In this example, ``a`` is to be dispatched over, so we return it, while marking it as an ``int``.
The trailing comma is needed because the args have to be returned as an iterable.
>>> def override_me(a, b):
...   return Dispatchable(a, int),
Next, we define the argument replacer that replaces the dispatchables inside args/kwargs with the
supplied ones.
>>> def override_replacer(args, kwargs, dispatchables):
...     return (dispatchables[0], args[1]), {}
Next, we define the multimethod.
>>> overridden_me = generate_multimethod(
...     override_me, override_replacer, "ua_examples"
...)
Notice that there's no default implementation, unless you supply one.
>>> overridden_me(1, "a")
Traceback (most recent call last):
    ...
uarray.BackendNotImplementedError: ...
>>> overridden_me2 = generate_multimethod(
...     override_me, override_replacer, "ua_examples", default=lambda x, y: (x, y)
...)
>>> overridden_me2(1, "a")
(1, 'a')
See Also
--------
uarray
    See the module documentation for how to override the method by creating backends.
Definition at line 173 of file _backend.py.
Referenced by create_multimethod().
get_defaults()
scipy._lib._uarray._backend.get_defaults (f)
Definition at line 306 of file _backend.py.
get_state()
scipy._lib._uarray._backend.get_state ()
Returns an opaque object containing the current state of all the backends.
Can be used for synchronization between threads/processes.
See Also
--------
set_state
    Sets the state returned by this function.
Definition at line 104 of file _backend.py.
Referenced by reset_state(), and set_state().
mark_as()
scipy._lib._uarray._backend.mark_as (dispatch_type)
Creates a utility function to mark something as a specific type.
Examples
--------
>>> mark_int = mark_as(int)
>>> mark_int(1)
<Dispatchable: type=<class 'int'>, value=1>
Definition at line 450 of file _backend.py.
pickle_function()
scipy._lib._uarray._backend.pickle_function (func)
Definition at line 68 of file _backend.py.
pickle_set_backend_context()
scipy._lib._uarray._backend.pickle_set_backend_context (ctx)
Definition at line 90 of file _backend.py.
pickle_skip_backend_context()
scipy._lib._uarray._backend.pickle_skip_backend_context (ctx)
Definition at line 94 of file _backend.py.
pickle_state()
scipy._lib._uarray._backend.pickle_state (state)
Definition at line 86 of file _backend.py.
register_backend()
scipy._lib._uarray._backend.register_backend (backend)
This utility method sets registers backend for permanent use. It
will be tried in the list of backends automatically, unless the
``only`` flag is set on a backend.
Note that this method is not thread-safe.
Parameters
----------
backend
    The backend to register.
Definition at line 359 of file _backend.py.
reset_state()
scipy._lib._uarray._backend.reset_state ()
Returns a context manager that resets all state once exited.
See Also
--------
set_state
    Context manager that sets the backend state.
get_state
    Gets a state to be set by this context manager.
Definition at line 119 of file _backend.py.
References get_state(), and set_state().
set_backend()
scipy._lib._uarray._backend.set_backend (backend, coerce = False, only = False)
A context manager that sets the preferred backend.
Parameters
----------
backend
    The backend to set.
coerce
    Whether or not to coerce to a specific backend's types. Implies ``only``.
only
    Whether or not this should be the last backend to try.
See Also
--------
skip_backend: A context manager that allows skipping of backends.
set_global_backend: Set a single, global backend for a domain.
Definition at line 248 of file _backend.py.
Referenced by determine_backend(), and determine_backend_multi().
set_global_backend()
scipy._lib._uarray._backend.set_global_backend (backend, coerce = False, only = False, * , try_last = False)
This utility method replaces the default backend for permanent use. It
will be tried in the list of backends automatically, unless the
``only`` flag is set on a backend. This will be the first tried
backend outside the :obj:`set_backend` context manager.
Note that this method is not thread-safe.
.. warning::
    We caution library authors against using this function in
    their code. We do *not* support this use-case. This function
    is meant to be used only by users themselves, or by a reference
    implementation, if one exists.
Parameters
----------
backend
    The backend to register.
coerce : bool
    Whether to coerce input types when trying this backend.
only : bool
    If ``True``, no more backends will be tried if this fails.
    Implied by ``coerce=True``.
try_last : bool
    If ``True``, the global backend is tried after registered backends.
See Also
--------
set_backend: A context manager that allows setting of backends.
skip_backend: A context manager that allows skipping of backends.
Definition at line 324 of file _backend.py.
set_state()
scipy._lib._uarray._backend.set_state (state)
A context manager that sets the state of the backends to one returned by :obj:`get_state`.
See Also
--------
get_state
    Gets a state to be set by this context manager.
Definition at line 135 of file _backend.py.
References get_state().
Referenced by reset_state().
skip_backend()
scipy._lib._uarray._backend.skip_backend (backend)
A context manager that allows one to skip a given backend from processing
entirely. This allows one to use another backend's code in a library that
is also a consumer of the same backend.
Parameters
----------
backend
    The backend to skip.
See Also
--------
set_backend: A context manager that allows setting of backends.
set_global_backend: Set a single, global backend for a domain.
Definition at line 278 of file _backend.py.
unpickle_function()
scipy._lib._uarray._backend.unpickle_function (mod_name, qname, self_)
Definition at line 48 of file _backend.py.
wrap_single_convertor()
scipy._lib._uarray._backend.wrap_single_convertor (convert_single)
Wraps a ``__ua_convert__`` defined for a single element to all elements.
If any of them return ``NotImplemented``, the operation is assumed to be
undefined.
Accepts a signature of (value, type, coerce).
Definition at line 492 of file _backend.py.
wrap_single_convertor_instance()
scipy._lib._uarray._backend.wrap_single_convertor_instance (convert_single)
Wraps a ``__ua_convert__`` defined for a single element to all elements.
If any of them return ``NotImplemented``, the operation is assumed to be
undefined.
Accepts a signature of (value, type, coerce).
Definition at line 517 of file _backend.py.
Variable Documentation
__all__
list scipy._lib._uarray._backend.__all__ private
Initial value:
=  [
    "set_backend",
    "set_global_backend",
    "skip_backend",
    "register_backend",
    "determine_backend",
    "determine_backend_multi",
    "clear_backends",
    "create_multimethod",
    "generate_multimethod",
    "_Function",
    "BackendNotImplementedError",
    "Dispatchable",
    "wrap_single_convertor",
    "wrap_single_convertor_instance",
    "all_of_type",
    "mark_as",
    "set_state",
    "get_state",
    "reset_state",
    "_BackendState",
    "_SkipBackendContext",
    "_SetBackendContext",
]
Definition at line 18 of file _backend.py.
ArgumentExtractorType
scipy._lib._uarray._backend.ArgumentExtractorType = typing.Callable[..., typing.Tuple["Dispatchable", ...]]
Definition at line 43 of file _backend.py.
ArgumentReplacerType
scipy._lib._uarray._backend.ArgumentReplacerType
Initial value:
=  typing.Callable[
    [typing.Tuple, typing.Dict, typing.Tuple], typing.Tuple[typing.Tuple, typing.Dict]
]
Definition at line 44 of file _backend.py.