Code Cloning Analysis: pandas.tests.arithmetic.test_interval.TestComparison Class Reference
pandas.tests.arithmetic.test_interval.TestComparison Class Reference
Public Member Functions
op (self, request)
interval_constructor (self, request)
elementwise_comparison (self, op, interval_array, other)
test_compare_scalar_interval (self, op, interval_array)
test_compare_scalar_interval_mixed_closed (self, op, closed, other_closed)
test_compare_scalar_na (self, op, interval_array, nulls_fixture, box_with_array)
test_compare_scalar_other (self, op, interval_array, other)
test_compare_list_like_interval (self, op, interval_array, interval_constructor)
test_compare_list_like_interval_mixed_closed (self, op, interval_constructor, closed, other_closed)
test_compare_list_like_object (self, op, interval_array, other)
test_compare_list_like_nan (self, op, interval_array, nulls_fixture)
test_compare_list_like_other (self, op, interval_array, other)
test_compare_length_mismatch_errors (self, op, other_constructor, length)
test_index_series_compat (self, op, constructor, expected_type, assert_func)
test_comparison_operations (self, scalars)
Detailed Description
Definition at line 77 of file test_interval.py.
Member Function Documentation
elementwise_comparison()
pandas.tests.arithmetic.test_interval.TestComparison.elementwise_comparison (self, op, interval_array, other)
Helper that performs elementwise comparisons between `array` and `other`
Definition at line 105 of file test_interval.py.
References elementwise_comparison(), and interval_constructor().
Referenced by elementwise_comparison().
interval_constructor()
pandas.tests.arithmetic.test_interval.TestComparison.interval_constructor (self, request)
Fixture for all pandas native interval constructors.
To be used as the LHS of IntervalArray comparisons.
Definition at line 98 of file test_interval.py.
Referenced by elementwise_comparison().
op()
pandas.tests.arithmetic.test_interval.TestComparison.op (self, request)
Definition at line 79 of file test_interval.py.
test_compare_length_mismatch_errors()
pandas.tests.arithmetic.test_interval.TestComparison.test_compare_length_mismatch_errors (self, op, other_constructor, length)
Definition at line 260 of file test_interval.py.
test_compare_list_like_interval()
pandas.tests.arithmetic.test_interval.TestComparison.test_compare_list_like_interval (self, op, interval_array, interval_constructor)
Definition at line 176 of file test_interval.py.
test_compare_list_like_interval_mixed_closed()
pandas.tests.arithmetic.test_interval.TestComparison.test_compare_list_like_interval_mixed_closed (self, op, interval_constructor, closed, other_closed)
Definition at line 197 of file test_interval.py.
test_compare_list_like_nan()
pandas.tests.arithmetic.test_interval.TestComparison.test_compare_list_like_nan (self, op, interval_array, nulls_fixture)
Definition at line 230 of file test_interval.py.
test_compare_list_like_object()
pandas.tests.arithmetic.test_interval.TestComparison.test_compare_list_like_object (self, op, interval_array, other)
Definition at line 225 of file test_interval.py.
test_compare_list_like_other()
pandas.tests.arithmetic.test_interval.TestComparison.test_compare_list_like_other (self, op, interval_array, other)
Definition at line 253 of file test_interval.py.
test_compare_scalar_interval()
pandas.tests.arithmetic.test_interval.TestComparison.test_compare_scalar_interval (self, op, interval_array)
Definition at line 115 of file test_interval.py.
test_compare_scalar_interval_mixed_closed()
pandas.tests.arithmetic.test_interval.TestComparison.test_compare_scalar_interval_mixed_closed (self, op, closed, other_closed)
Definition at line 128 of file test_interval.py.
test_compare_scalar_na()
pandas.tests.arithmetic.test_interval.TestComparison.test_compare_scalar_na (self, op, interval_array, nulls_fixture, box_with_array)
Definition at line 136 of file test_interval.py.
test_compare_scalar_other()
pandas.tests.arithmetic.test_interval.TestComparison.test_compare_scalar_other (self, op, interval_array, other)
Definition at line 171 of file test_interval.py.
test_comparison_operations()
pandas.tests.arithmetic.test_interval.TestComparison.test_comparison_operations (self, scalars)
Definition at line 301 of file test_interval.py.
test_index_series_compat()
pandas.tests.arithmetic.test_interval.TestComparison.test_index_series_compat (self, op, constructor, expected_type, assert_func)
Definition at line 273 of file test_interval.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/tests/arithmetic/test_interval.py