Code Cloning Analysis: sklearn.externals.array_api_extra._delegation Namespace Reference
sklearn.externals.array_api_extra._delegation Namespace Reference
Functions
bool _delegate (ModuleType xp, *Backend backends)
Array isclose (Array|complex a, Array|complex b, *, float rtol=1e-05, float atol=1e-08, bool equal_nan=False, ModuleType|None xp=None)
Array pad (Array x, int|tuple[int, int]|Sequence[tuple[int, int]] pad_width, Literal["constant"] mode="constant", *, complex constant_values=0, ModuleType|None xp=None)
Variables
list __all__ = ["isclose", "pad"]
Detailed Description
Delegation to existing implementations for Public API Functions.
Function Documentation
_delegate()
bool sklearn.externals.array_api_extra._delegation._delegate (ModuleType xp, *Backend backends) protected
Check whether `xp` is one of the `backends` to delegate to.
Parameters
----------
xp : array_namespace
    Array namespace to check.
*backends : IsNamespace
    Arbitrarily many backends (from the ``IsNamespace`` enum) to check.
Returns
-------
bool
    ``True`` if `xp` matches one of the `backends`, ``False`` otherwise.
Definition at line 15 of file _delegation.py.
Referenced by isclose(), and pad().
isclose()
Array sklearn.externals.array_api_extra._delegation.isclose (Array | complex a, Array | complex b, * , float rtol = 1e-05, float atol = 1e-08, bool equal_nan = False, ModuleType | None xp = None)
Return a boolean array where two arrays are element-wise equal within a tolerance.
The tolerance values are positive, typically very small numbers. The relative
difference ``(rtol * abs(b))`` and the absolute difference `atol` are added together
to compare against the absolute difference between `a` and `b`.
NaNs are treated as equal if they are in the same place and if ``equal_nan=True``.
Infs are treated as equal if they are in the same place and of the same sign in both
arrays.
Parameters
----------
a, b : Array | int | float | complex | bool
    Input objects to compare. At least one must be an array.
rtol : array_like, optional
    The relative tolerance parameter (see Notes).
atol : array_like, optional
    The absolute tolerance parameter (see Notes).
equal_nan : bool, optional
    Whether to compare NaN's as equal. If True, NaN's in `a` will be considered
    equal to NaN's in `b` in the output array.
xp : array_namespace, optional
    The standard-compatible namespace for `a` and `b`. Default: infer.
Returns
-------
Array
    A boolean array of shape broadcasted from `a` and `b`, containing ``True`` where
    `a` is close to `b`, and ``False`` otherwise.
Warnings
--------
The default `atol` is not appropriate for comparing numbers with magnitudes much
smaller than one (see notes).
See Also
--------
math.isclose : Similar function in stdlib for Python scalars.
Notes
-----
For finite values, `isclose` uses the following equation to test whether two
floating point values are equivalent::
    absolute(a - b) <= (atol + rtol * absolute(b))
Unlike the built-in `math.isclose`,
the above equation is not symmetric in `a` and `b`,
so that ``isclose(a, b)`` might be different from ``isclose(b, a)`` in some rare
cases.
The default value of `atol` is not appropriate when the reference value `b` has
magnitude smaller than one. For example, it is unlikely that ``a = 1e-9`` and
``b = 2e-9`` should be considered "close", yet ``isclose(1e-9, 2e-9)`` is ``True``
with default settings. Be sure to select `atol` for the use case at hand, especially
for defining the threshold below which a non-zero value in `a` will be considered
"close" to a very small or zero value in `b`.
The comparison of `a` and `b` uses standard broadcasting, which means that `a` and
`b` need not have the same shape in order for ``isclose(a, b)`` to evaluate to
``True``.
`isclose` is not defined for non-numeric data types.
``bool`` is considered a numeric data-type for this purpose.
Definition at line 34 of file _delegation.py.
References _delegate().
pad()
Array sklearn.externals.array_api_extra._delegation.pad (Array x, int | tuple[int, int] | Sequence[tuple[int, int]] pad_width, Literal["constant"] mode = "constant", * , complex constant_values = 0, ModuleType | None xp = None)
Pad the input array.
Parameters
----------
x : array
    Input array.
pad_width : int or tuple of ints or sequence of pairs of ints
    Pad the input array with this many elements from each side.
    If a sequence of tuples, ``[(before_0, after_0), ... (before_N, after_N)]``,
    each pair applies to the corresponding axis of ``x``.
    A single tuple, ``(before, after)``, is equivalent to a list of ``x.ndim``
    copies of this tuple.
mode : str, optional
    Only "constant" mode is currently supported, which pads with
    the value passed to `constant_values`.
constant_values : python scalar, optional
    Use this value to pad the input. Default is zero.
xp : array_namespace, optional
    The standard-compatible namespace for `x`. Default: infer.
Returns
-------
array
    The input array,
    padded with ``pad_width`` elements equal to ``constant_values``.
Definition at line 121 of file _delegation.py.
References _delegate().
Variable Documentation
__all__
list sklearn.externals.array_api_extra._delegation.__all__ = ["isclose", "pad"] private
Definition at line 12 of file _delegation.py.