Code Cloning Analysis: fontTools.ttLib.ttFont Namespace Reference
fontTools.ttLib.ttFont Namespace Reference
Classes
class GlyphOrder
class TTFont
Functions
getTableModule (tag)
registerCustomTableClass (tag, moduleName, className=None)
unregisterCustomTableClass (tag)
getCustomTableClass (tag)
getTableClass (tag)
getClassTag (klass)
newTable (tag)
_escapechar (c)
tagToIdentifier (tag)
identifierToTag (ident)
tagToXML (tag)
xmlToTag (tag)
sortedTagList (tagList, tableOrder=None)
reorderFontTables (inFile, outFile, tableOrder=None, checkChecksums=False)
maxPowerOfTwo (x)
getSearchRange (n, itemSize=16)
Variables
log = logging.getLogger(__name__)
dict _customTableRegistry = {}
list TTFTableOrder
list OTFTableOrder = ["head", "hhea", "maxp", "OS/2", "name", "cmap", "post", "CFF "]
Function Documentation
_escapechar()
fontTools.ttLib.ttFont._escapechar (c) protected
Helper function for tagToIdentifier()
Definition at line 963 of file ttFont.py.
Referenced by tagToIdentifier().
getClassTag()
fontTools.ttLib.ttFont.getClassTag (klass)
Fetch the table tag for a class object.
Definition at line 949 of file ttFont.py.
References identifierToTag().
getCustomTableClass()
fontTools.ttLib.ttFont.getCustomTableClass (tag)
Return the custom table class for tag, if one has been registered
with 'registerCustomTableClass()'. Else return None.
Definition at line 921 of file ttFont.py.
Referenced by getTableClass().
getSearchRange()
fontTools.ttLib.ttFont.getSearchRange (n, itemSize = 16)
Calculate searchRange, entrySelector, rangeShift.
Definition at line 1140 of file ttFont.py.
References maxPowerOfTwo().
Referenced by fontTools.ttLib.sfnt.SFNTReader.__getitem__(), fontTools.ttLib.woff2.WOFF2Writer._calcMasterChecksum(), and fontTools.ttLib.tables.otConverters.AATLookup.write().
getTableClass()
fontTools.ttLib.ttFont.getTableClass (tag)
Fetch the packer/unpacker class for a table.
Definition at line 934 of file ttFont.py.
References getCustomTableClass(), getTableModule(), and tagToIdentifier().
getTableModule()
fontTools.ttLib.ttFont.getTableModule (tag)
Fetch the packer/unpacker module for a table.
Return None when no module is found.
Definition at line 873 of file ttFont.py.
References tagToIdentifier().
Referenced by getTableClass(), and fontTools.ttLib.woff2.WOFF2GlyfTable.transform().
identifierToTag()
fontTools.ttLib.ttFont.identifierToTag (ident)
the opposite of tagToIdentifier()
Definition at line 1010 of file ttFont.py.
Referenced by getClassTag(), and xmlToTag().
maxPowerOfTwo()
fontTools.ttLib.ttFont.maxPowerOfTwo (x)
Return the highest exponent of two, so that
(2 ** exponent) <= x.  Return 0 if x is 0.
Definition at line 1129 of file ttFont.py.
Referenced by getSearchRange().
newTable()
fontTools.ttLib.ttFont.newTable (tag)
Return a new instance of a table.
Definition at line 957 of file ttFont.py.
Referenced by fontTools.ttLib.tables._n_a_m_e._makeMacName().
registerCustomTableClass()
fontTools.ttLib.ttFont.registerCustomTableClass (tag, moduleName, className = None)
Register a custom packer/unpacker class for a table.
The 'moduleName' must be an importable module. If no 'className'
is given, it is derived from the tag, for example it will be
``table_C_U_S_T_`` for a 'CUST' tag.
The registered table class should be a subclass of
:py:class:`fontTools.ttLib.tables.DefaultTable.DefaultTable`
Definition at line 901 of file ttFont.py.
References tagToIdentifier().
reorderFontTables()
fontTools.ttLib.ttFont.reorderFontTables (inFile, outFile, tableOrder = None, checkChecksums = False)
Rewrite a font file, ordering the tables as recommended by the
OpenType specification 1.4.
Definition at line 1109 of file ttFont.py.
References sortedTagList().
Referenced by fontTools.ttLib.ttFont.TTFont.save().
sortedTagList()
fontTools.ttLib.ttFont.sortedTagList (tagList, tableOrder = None)
Return a sorted copy of tagList, sorted according to the OpenType
specification, or according to a custom tableOrder. If given and not
None, tableOrder needs to be a list of tag names.
Definition at line 1085 of file ttFont.py.
Referenced by fontTools.ttLib.ttFont.TTFont.keys(), and reorderFontTables().
tagToIdentifier()
fontTools.ttLib.ttFont.tagToIdentifier (tag)
Convert a table tag to a valid (but UGLY) python identifier,
as well as a filename that's guaranteed to be unique even on a
caseless file system. Each character is mapped to two characters.
Lowercase letters get an underscore before the letter, uppercase
letters get an underscore after the letter. Trailing spaces are
trimmed. Illegal characters are escaped as two hex bytes. If the
result starts with a number (as the result of a hex escape), an
extra underscore is prepended. Examples:
.. code-block:: pycon
    >>>
    >> tagToIdentifier('glyf')
    '_g_l_y_f'
    >> tagToIdentifier('cvt ')
    '_c_v_t'
    >> tagToIdentifier('OS/2')
    'O_S_2f_2'
Definition at line 975 of file ttFont.py.
References _escapechar().
Referenced by getTableClass(), getTableModule(), registerCustomTableClass(), fontTools.ttLib.ttFont.TTFont.saveXML(), and tagToXML().
tagToXML()
fontTools.ttLib.ttFont.tagToXML (tag)
Similarly to tagToIdentifier(), this converts a TT tag
to a valid XML element name. Since XML element names are
case sensitive, this is a fairly simple/readable translation.
Definition at line 1031 of file ttFont.py.
References tagToIdentifier().
Referenced by fontTools.ttLib.ttFont.TTFont.saveXML().
unregisterCustomTableClass()
fontTools.ttLib.ttFont.unregisterCustomTableClass (tag)
Unregister the custom packer/unpacker class for a table.
Definition at line 916 of file ttFont.py.
xmlToTag()
fontTools.ttLib.ttFont.xmlToTag (tag)
The opposite of tagToXML()
Definition at line 1049 of file ttFont.py.
References identifierToTag().
Variable Documentation
_customTableRegistry
dict fontTools.ttLib.ttFont._customTableRegistry = {} protected
Definition at line 898 of file ttFont.py.
log
fontTools.ttLib.ttFont.log = logging.getLogger(__name__)
Definition at line 19 of file ttFont.py.
OTFTableOrder
list fontTools.ttLib.ttFont.OTFTableOrder = ["head", "hhea", "maxp", "OS/2", "name", "cmap", "post", "CFF "]
Definition at line 1082 of file ttFont.py.
TTFTableOrder
list fontTools.ttLib.ttFont.TTFTableOrder
Initial value:
=  [
    "head",
    "hhea",
    "maxp",
    "OS/2",
    "hmtx",
    "LTSH",
    "VDMX",
    "hdmx",
    "cmap",
    "fpgm",
    "prep",
    "cvt ",
    "loca",
    "glyf",
    "kern",
    "name",
    "post",
    "gasp",
    "PCLT",
]
Definition at line 1060 of file ttFont.py.