Code Cloning Analysis: scipy.optimize._tstutils Namespace Reference
scipy.optimize._tstutils Namespace Reference
Functions
f1 (x)
f1_fp (x)
f1_fpp (x)
f2 (x)
f2_fp (x)
f2_fpp (x)
f3 (x)
f3_fp (x)
f3_fpp (x)
f4 (x)
f5 (x)
f6 (x)
aps01_f (x)
aps01_fp (x)
aps01_fpp (x)
aps02_f (x)
aps02_fp (x)
aps02_fpp (x)
aps03_f (x, a, b)
aps03_fp (x, a, b)
aps03_fpp (x, a, b)
aps04_f (x, n, a)
aps04_fp (x, n, a)
aps04_fpp (x, n, a)
aps05_f (x)
aps05_fp (x)
aps05_fpp (x)
aps06_f (x, n)
aps06_fp (x, n)
aps06_fpp (x, n)
aps07_f (x, n)
aps07_fp (x, n)
aps07_fpp (x, n)
aps08_f (x, n)
aps08_fp (x, n)
aps08_fpp (x, n)
aps09_f (x, n)
aps09_fp (x, n)
aps09_fpp (x, n)
aps10_f (x, n)
aps10_fp (x, n)
aps10_fpp (x, n)
aps11_f (x, n)
aps11_fp (x, n)
aps11_fpp (x, n)
aps12_f (x, n)
aps12_fp (x, n)
aps12_fpp (x, n)
aps13_f (x)
aps13_fp (x)
aps13_fpp (x)
aps14_f (x, n)
aps14_fp (x, n)
aps14_fpp (x, n)
aps15_f (x, n)
aps15_fp (x, n)
aps15_fpp (x, n)
cplx01_f (z, n, a)
cplx01_fp (z, n, a)
cplx01_fpp (z, n, a)
cplx02_f (z, a)
cplx02_fp (z, a)
cplx02_fpp (z, a)
_add_a_b (tests)
get_tests (collection='original', smoothness=None)
fun1 (x)
fun2 (x)
fun3 (x)
fun4 (x)
fun5 (x)
fun6 (x)
fun7 (x)
fun8 (x)
fun9 (x)
Variables
str description
dict _f6_cache = {}
list _ORIGINAL_TESTS_KEYS = ["f", "fprime", "fprime2", "args", "bracket", "smoothness", "x0", "root", "ID"]
list _ORIGINAL_TESTS
list _ORIGINAL_TESTS_DICTS = [dict(zip(_ORIGINAL_TESTS_KEYS, testcase)) for testcase in _ORIGINAL_TESTS]
_MAX_EXPABLE = np.log(np.finfo(float).max)
list _APS_TESTS_KEYS = ["f", "fprime", "fprime2", "args", "bracket", "smoothness", "x0", "root", "ID"]
list _APS_TESTS
list _APS_TESTS_DICTS = [dict(zip(_APS_TESTS_KEYS, testcase)) for testcase in _APS_TESTS]
list _COMPLEX_TESTS_KEYS = ["f", "fprime", "fprime2", "args", "smoothness", "x0", "x1", "root", "ID"]
list _COMPLEX_TESTS
list _COMPLEX_TESTS_DICTS = [dict(zip(_COMPLEX_TESTS_KEYS, testcase)) for testcase in _COMPLEX_TESTS]
list methods = [cc.bisect, cc.ridder, cc.brenth, cc.brentq]
list mstrings = ['cc.bisect', 'cc.ridder', 'cc.brenth', 'cc.brentq']
list functions = [f2, f3, f4, f5, f6]
list fstrings = ['f2', 'f3', 'f4', 'f5', 'f6']
root
list _CHANDRUPATLA_TESTS_KEYS = ["f", "bracket", "root", "nfeval", "ID"]
list _CHANDRUPATLA_TESTS
list _CHANDRUPATLA_TESTS_DICTS
Detailed Description
Parameters used in test and benchmark methods.
Collections of test cases suitable for testing 1-D root-finders
  'original': The original benchmarking functions.
     Real-valued functions of real-valued inputs on an interval
     with a zero.
     f1, .., f3 are continuous and infinitely differentiable
     f4 has a left- and right- discontinuity at the root
     f5 has a root at 1 replacing a 1st order pole
     f6 is randomly positive on one side of the root,
     randomly negative on the other.
     f4 - f6 are not continuous at the root.
  'aps': The test problems in the 1995 paper
     TOMS "Algorithm 748: Enclosing Zeros of Continuous Functions"
     by Alefeld, Potra and Shi. Real-valued functions of
     real-valued inputs on an interval with a zero.
     Suitable for methods which start with an enclosing interval, and
     derivatives up to 2nd order.
  'complex': Some complex-valued functions of complex-valued inputs.
     No enclosing bracket is provided.
     Suitable for methods which use one or more starting values, and
     derivatives up to 2nd order.
  The test cases are provided as a list of dictionaries. The dictionary
  keys will be a subset of:
  ["f", "fprime", "fprime2", "args", "bracket", "smoothness",
  "a", "b", "x0", "x1", "root", "ID"]
Function Documentation
_add_a_b()
scipy.optimize._tstutils._add_a_b (tests) protected
Add "a" and "b" keys to each test from the "bracket" value
Definition at line 630 of file _tstutils.py.
References _add_a_b().
Referenced by _add_a_b(), and get_tests().
aps01_f()
scipy.optimize._tstutils.aps01_f (x)
Straightforward sum of trigonometric function and polynomial
Definition at line 162 of file _tstutils.py.
aps01_fp()
scipy.optimize._tstutils.aps01_fp (x)
Definition at line 167 of file _tstutils.py.
aps01_fpp()
scipy.optimize._tstutils.aps01_fpp (x)
Definition at line 171 of file _tstutils.py.
aps02_f()
scipy.optimize._tstutils.aps02_f (x)
poles at x=n**2, 1st and 2nd derivatives at root are also close to 0
Definition at line 175 of file _tstutils.py.
aps02_fp()
scipy.optimize._tstutils.aps02_fp (x)
Definition at line 181 of file _tstutils.py.
aps02_fpp()
scipy.optimize._tstutils.aps02_fpp (x)
Definition at line 186 of file _tstutils.py.
aps03_f()
scipy.optimize._tstutils.aps03_f (x, a, b)
Rapidly changing at the root
Definition at line 191 of file _tstutils.py.
aps03_fp()
scipy.optimize._tstutils.aps03_fp (x, a, b)
Definition at line 196 of file _tstutils.py.
aps03_fpp()
scipy.optimize._tstutils.aps03_fpp (x, a, b)
Definition at line 200 of file _tstutils.py.
aps04_f()
scipy.optimize._tstutils.aps04_f (x, n, a)
Medium-degree polynomial
Definition at line 204 of file _tstutils.py.
aps04_fp()
scipy.optimize._tstutils.aps04_fp (x, n, a)
Definition at line 209 of file _tstutils.py.
aps04_fpp()
scipy.optimize._tstutils.aps04_fpp (x, n, a)
Definition at line 213 of file _tstutils.py.
aps05_f()
scipy.optimize._tstutils.aps05_f (x)
Simple Trigonometric function
Definition at line 217 of file _tstutils.py.
aps05_fp()
scipy.optimize._tstutils.aps05_fp (x)
Definition at line 222 of file _tstutils.py.
aps05_fpp()
scipy.optimize._tstutils.aps05_fpp (x)
Definition at line 226 of file _tstutils.py.
aps06_f()
scipy.optimize._tstutils.aps06_f (x, n)
Exponential rapidly changing from -1 to 1 at x=0
Definition at line 230 of file _tstutils.py.
aps06_fp()
scipy.optimize._tstutils.aps06_fp (x, n)
Definition at line 235 of file _tstutils.py.
aps06_fpp()
scipy.optimize._tstutils.aps06_fpp (x, n)
Definition at line 239 of file _tstutils.py.
aps07_f()
scipy.optimize._tstutils.aps07_f (x, n)
Upside down parabola with parametrizable height
Definition at line 243 of file _tstutils.py.
aps07_fp()
scipy.optimize._tstutils.aps07_fp (x, n)
Definition at line 248 of file _tstutils.py.
aps07_fpp()
scipy.optimize._tstutils.aps07_fpp (x, n)
Definition at line 252 of file _tstutils.py.
aps08_f()
scipy.optimize._tstutils.aps08_f (x, n)
Degree n polynomial
Definition at line 256 of file _tstutils.py.
aps08_fp()
scipy.optimize._tstutils.aps08_fp (x, n)
Definition at line 261 of file _tstutils.py.
aps08_fpp()
scipy.optimize._tstutils.aps08_fpp (x, n)
Definition at line 265 of file _tstutils.py.
aps09_f()
scipy.optimize._tstutils.aps09_f (x, n)
Upside down quartic with parametrizable height
Definition at line 269 of file _tstutils.py.
aps09_fp()
scipy.optimize._tstutils.aps09_fp (x, n)
Definition at line 274 of file _tstutils.py.
aps09_fpp()
scipy.optimize._tstutils.aps09_fpp (x, n)
Definition at line 278 of file _tstutils.py.
aps10_f()
scipy.optimize._tstutils.aps10_f (x, n)
Exponential plus a polynomial
Definition at line 282 of file _tstutils.py.
aps10_fp()
scipy.optimize._tstutils.aps10_fp (x, n)
Definition at line 287 of file _tstutils.py.
aps10_fpp()
scipy.optimize._tstutils.aps10_fpp (x, n)
Definition at line 291 of file _tstutils.py.
aps11_f()
scipy.optimize._tstutils.aps11_f (x, n)
Rational function with a zero at x=1/n and a pole at x=0
Definition at line 295 of file _tstutils.py.
aps11_fp()
scipy.optimize._tstutils.aps11_fp (x, n)
Definition at line 300 of file _tstutils.py.
aps11_fpp()
scipy.optimize._tstutils.aps11_fpp (x, n)
Definition at line 304 of file _tstutils.py.
aps12_f()
scipy.optimize._tstutils.aps12_f (x, n)
nth root of x, with a zero at x=n
Definition at line 308 of file _tstutils.py.
aps12_fp()
scipy.optimize._tstutils.aps12_fp (x, n)
Definition at line 313 of file _tstutils.py.
aps12_fpp()
scipy.optimize._tstutils.aps12_fpp (x, n)
Definition at line 317 of file _tstutils.py.
aps13_f()
scipy.optimize._tstutils.aps13_f (x)
Function with *all* derivatives 0 at the root
Definition at line 324 of file _tstutils.py.
aps13_fp()
scipy.optimize._tstutils.aps13_fp (x)
Definition at line 337 of file _tstutils.py.
aps13_fpp()
scipy.optimize._tstutils.aps13_fpp (x)
Definition at line 346 of file _tstutils.py.
aps14_f()
scipy.optimize._tstutils.aps14_f (x, n)
0 for negative x-values, trigonometric+linear for x positive
Definition at line 355 of file _tstutils.py.
aps14_fp()
scipy.optimize._tstutils.aps14_fp (x, n)
Definition at line 362 of file _tstutils.py.
aps14_fpp()
scipy.optimize._tstutils.aps14_fpp (x, n)
Definition at line 368 of file _tstutils.py.
aps15_f()
scipy.optimize._tstutils.aps15_f (x, n)
piecewise linear, constant outside of [0, 0.002/(1+n)]
Definition at line 374 of file _tstutils.py.
aps15_fp()
scipy.optimize._tstutils.aps15_fp (x, n)
Definition at line 383 of file _tstutils.py.
aps15_fpp()
scipy.optimize._tstutils.aps15_fpp (x, n)
Definition at line 389 of file _tstutils.py.
cplx01_f()
scipy.optimize._tstutils.cplx01_f (z, n, a)
z**n-a:  Use to find the nth root of a
Definition at line 575 of file _tstutils.py.
cplx01_fp()
scipy.optimize._tstutils.cplx01_fp (z, n, a)
Definition at line 580 of file _tstutils.py.
cplx01_fpp()
scipy.optimize._tstutils.cplx01_fpp (z, n, a)
Definition at line 584 of file _tstutils.py.
cplx02_f()
scipy.optimize._tstutils.cplx02_f (z, a)
e**z - a: Use to find the log of a
Definition at line 588 of file _tstutils.py.
cplx02_fp()
scipy.optimize._tstutils.cplx02_fp (z, a)
Definition at line 593 of file _tstutils.py.
cplx02_fpp()
scipy.optimize._tstutils.cplx02_fpp (z, a)
Definition at line 597 of file _tstutils.py.
f1()
scipy.optimize._tstutils.f1 (x)
f1 is a quadratic with roots at 0 and 1
Definition at line 64 of file _tstutils.py.
f1_fp()
scipy.optimize._tstutils.f1_fp (x)
Definition at line 69 of file _tstutils.py.
f1_fpp()
scipy.optimize._tstutils.f1_fpp (x)
Definition at line 73 of file _tstutils.py.
f2()
scipy.optimize._tstutils.f2 (x)
f2 is a symmetric parabola, x**2 - 1
Definition at line 77 of file _tstutils.py.
f2_fp()
scipy.optimize._tstutils.f2_fp (x)
Definition at line 82 of file _tstutils.py.
f2_fpp()
scipy.optimize._tstutils.f2_fpp (x)
Definition at line 86 of file _tstutils.py.
f3()
scipy.optimize._tstutils.f3 (x)
A quartic with roots at 0, 1, 2 and 3
Definition at line 90 of file _tstutils.py.
f3_fp()
scipy.optimize._tstutils.f3_fp (x)
Definition at line 95 of file _tstutils.py.
f3_fpp()
scipy.optimize._tstutils.f3_fpp (x)
Definition at line 99 of file _tstutils.py.
f4()
scipy.optimize._tstutils.f4 (x)
Piecewise linear, left- and right- discontinuous at x=1, the root.
Definition at line 103 of file _tstutils.py.
f5()
scipy.optimize._tstutils.f5 (x)
Hyperbola with a pole at x=1, but pole replaced with 0. Not continuous at root.
Definition at line 112 of file _tstutils.py.
f6()
scipy.optimize._tstutils.f6 (x)
Definition at line 123 of file _tstutils.py.
fun1()
scipy.optimize._tstutils.fun1 (x)
Definition at line 686 of file _tstutils.py.
fun2()
scipy.optimize._tstutils.fun2 (x)
Definition at line 691 of file _tstutils.py.
fun3()
scipy.optimize._tstutils.fun3 (x)
Definition at line 696 of file _tstutils.py.
fun4()
scipy.optimize._tstutils.fun4 (x)
Definition at line 701 of file _tstutils.py.
fun5()
scipy.optimize._tstutils.fun5 (x)
Definition at line 706 of file _tstutils.py.
fun6()
scipy.optimize._tstutils.fun6 (x)
Definition at line 711 of file _tstutils.py.
fun7()
scipy.optimize._tstutils.fun7 (x)
Definition at line 716 of file _tstutils.py.
fun8()
scipy.optimize._tstutils.fun8 (x)
Definition at line 721 of file _tstutils.py.
fun9()
scipy.optimize._tstutils.fun9 (x)
Definition at line 727 of file _tstutils.py.
get_tests()
scipy.optimize._tstutils.get_tests (collection = 'original', smoothness = None)
Return the requested collection of test cases, as an array of dicts with subset-specific keys
Allowed values of collection:
'original': The original benchmarking functions.
     Real-valued functions of real-valued inputs on an interval with a zero.
     f1, .., f3 are continuous and infinitely differentiable
     f4 has a single discontinuity at the root
     f5 has a root at 1 replacing a 1st order pole
     f6 is randomly positive on one side of the root, randomly negative on the other
'aps': The test problems in the TOMS "Algorithm 748: Enclosing Zeros of Continuous Functions"
     paper by Alefeld, Potra and Shi. Real-valued functions of
     real-valued inputs on an interval with a zero.
     Suitable for methods which start with an enclosing interval, and
     derivatives up to 2nd order.
'complex': Some complex-valued functions of complex-valued inputs.
     No enclosing bracket is provided.
     Suitable for methods which use one or more starting values, and
     derivatives up to 2nd order.
The dictionary keys will be a subset of
["f", "fprime", "fprime2", "args", "bracket", "a", b", "smoothness", "x0", "x1", "root", "ID"]
Definition at line 642 of file _tstutils.py.
References _add_a_b().
Variable Documentation
_APS_TESTS
list scipy.optimize._tstutils._APS_TESTS protected
Definition at line 410 of file _tstutils.py.
_APS_TESTS_DICTS
list scipy.optimize._tstutils._APS_TESTS_DICTS = [dict(zip(_APS_TESTS_KEYS, testcase)) for testcase in _APS_TESTS] protected
Definition at line 567 of file _tstutils.py.
_APS_TESTS_KEYS
list scipy.optimize._tstutils._APS_TESTS_KEYS = ["f", "fprime", "fprime2", "args", "bracket", "smoothness", "x0", "root", "ID"] protected
Definition at line 409 of file _tstutils.py.
_CHANDRUPATLA_TESTS
list scipy.optimize._tstutils._CHANDRUPATLA_TESTS protected
Definition at line 743 of file _tstutils.py.
_CHANDRUPATLA_TESTS_DICTS
list scipy.optimize._tstutils._CHANDRUPATLA_TESTS_DICTS protected
Initial value:
=  [dict(zip(_CHANDRUPATLA_TESTS_KEYS, testcase))
                             for testcase in _CHANDRUPATLA_TESTS]
Definition at line 793 of file _tstutils.py.
_CHANDRUPATLA_TESTS_KEYS
list scipy.optimize._tstutils._CHANDRUPATLA_TESTS_KEYS = ["f", "bracket", "root", "nfeval", "ID"] protected
Definition at line 742 of file _tstutils.py.
_COMPLEX_TESTS
list scipy.optimize._tstutils._COMPLEX_TESTS protected
Initial value:
=  [
    [cplx01_f, cplx01_fp, cplx01_fpp, (2, -1), np.inf, (1 + 1j), (0.5 + 0.5j), 1j, "complex.01.00"],
    [cplx01_f, cplx01_fp, cplx01_fpp, (3, 1), np.inf, (-1 + 1j), (-0.5 + 2.0j), (-0.5 + np.sqrt(3) / 2 * 1.0j),
     "complex.01.01"],
    [cplx01_f, cplx01_fp, cplx01_fpp, (3, -1), np.inf, 1j, (0.5 + 0.5j), (0.5 + np.sqrt(3) / 2 * 1.0j),
     "complex.01.02"],
    [cplx01_f, cplx01_fp, cplx01_fpp, (3, 8), np.inf, 5, 4, 2, "complex.01.03"],
    [cplx02_f, cplx02_fp, cplx02_fpp, (-1,), np.inf, (1 + 2j), (0.5 + 0.5j), np.pi * 1.0j, "complex.02.00"],
    [cplx02_f, cplx02_fp, cplx02_fpp, (1j,), np.inf, (1 + 2j), (0.5 + 0.5j), np.pi * 0.5j, "complex.02.01"],
]
Definition at line 616 of file _tstutils.py.
_COMPLEX_TESTS_DICTS
list scipy.optimize._tstutils._COMPLEX_TESTS_DICTS = [dict(zip(_COMPLEX_TESTS_KEYS, testcase)) for testcase in _COMPLEX_TESTS] protected
Definition at line 627 of file _tstutils.py.
_COMPLEX_TESTS_KEYS
list scipy.optimize._tstutils._COMPLEX_TESTS_KEYS = ["f", "fprime", "fprime2", "args", "smoothness", "x0", "x1", "root", "ID"] protected
Definition at line 615 of file _tstutils.py.
_f6_cache
dict scipy.optimize._tstutils._f6_cache = {} protected
Definition at line 122 of file _tstutils.py.
_MAX_EXPABLE
scipy.optimize._tstutils._MAX_EXPABLE = np.log(np.finfo(float).max) protected
Definition at line 321 of file _tstutils.py.
_ORIGINAL_TESTS
list scipy.optimize._tstutils._ORIGINAL_TESTS protected
Initial value:
=  [
    [f1, f1_fp, f1_fpp, (), [0.5, np.sqrt(3)], np.inf, 0.6, 1.0, "original.01.00"],
    [f2, f2_fp, f2_fpp, (), [0.5, np.sqrt(3)], np.inf, 0.6, 1.0, "original.02.00"],
    [f3, f3_fp, f3_fpp, (), [0.5, np.sqrt(3)], np.inf, 0.6, 1.0, "original.03.00"],
    [f4, None, None, (), [0.5, np.sqrt(3)], -1, 0.6, 1.0, "original.04.00"],
    [f5, None, None, (), [0.5, np.sqrt(3)], -1, 0.6, 1.0, "original.05.00"],
    [f6, None, None, (), [0.5, np.sqrt(3)], -np.inf, 0.6, 1.0, "original.05.00"]
]
Definition at line 146 of file _tstutils.py.
_ORIGINAL_TESTS_DICTS
list scipy.optimize._tstutils._ORIGINAL_TESTS_DICTS = [dict(zip(_ORIGINAL_TESTS_KEYS, testcase)) for testcase in _ORIGINAL_TESTS] protected
Definition at line 155 of file _tstutils.py.
_ORIGINAL_TESTS_KEYS
list scipy.optimize._tstutils._ORIGINAL_TESTS_KEYS = ["f", "fprime", "fprime2", "args", "bracket", "smoothness", "x0", "root", "ID"] protected
Definition at line 145 of file _tstutils.py.
description
str scipy.optimize._tstutils.description
Initial value:
=  """
f2 is a symmetric parabola, x**2 - 1
f3 is a quartic polynomial with large hump in interval
f4 is step function with a discontinuity at 1
f5 is a hyperbola with vertical asymptote at 1
f6 has random values positive to left of 1, negative to right
Of course, these are not real problems. They just test how the
'good' solvers behave in bad circumstances where bisection is
really the best. A good solver should not be much worse than
bisection in such circumstance, while being faster for smooth
monotone sorts of functions.
"""
Definition at line 49 of file _tstutils.py.
fstrings
list scipy.optimize._tstutils.fstrings = ['f2', 'f3', 'f4', 'f5', 'f6']
Definition at line 680 of file _tstutils.py.
functions
list scipy.optimize._tstutils.functions = [f2, f3, f4, f5, f6]
Definition at line 679 of file _tstutils.py.
methods
list scipy.optimize._tstutils.methods = [cc.bisect, cc.ridder, cc.brenth, cc.brentq]
Definition at line 677 of file _tstutils.py.
mstrings
list scipy.optimize._tstutils.mstrings = ['cc.bisect', 'cc.ridder', 'cc.brenth', 'cc.brentq']
Definition at line 678 of file _tstutils.py.
root
scipy.optimize._tstutils.root
Definition at line 688 of file _tstutils.py.