Code Cloning Analysis: pip._internal.distributions.sdist.SourceDistribution Class Reference
pip._internal.distributions.sdist.SourceDistribution Class Reference
Public Member Functions
Optional[str] build_tracker_id (self)
BaseDistribution get_metadata_distribution (self)
None prepare_distribution_metadata (self, PackageFinder finder, bool build_isolation, bool check_build_deps)
Public Member Functions inherited from pip._internal.distributions.base.AbstractDistribution
None __init__ (self, InstallRequirement req)
Protected Member Functions
None _prepare_build_backend (self, PackageFinder finder)
Iterable[str] _get_build_requires_wheel (self)
Iterable[str] _get_build_requires_editable (self)
None _install_build_reqs (self, PackageFinder finder)
None _raise_conflicts (self, str conflicting_with, Set[Tuple[str, str]] conflicting_reqs)
None _raise_missing_reqs (self, Set[str] missing)
Additional Inherited Members
Public Attributes inherited from pip._internal.distributions.base.AbstractDistribution
req = req
Detailed Description
Represents a source distribution.
The preparation step for these needs metadata for the packages to be
generated, either using PEP 517 or using the legacy `setup.py egg_info`.
Definition at line 14 of file sdist.py.
Member Function Documentation
_get_build_requires_editable()
Iterable[str] pip._internal.distributions.sdist.SourceDistribution._get_build_requires_editable (self) protected
Definition at line 103 of file sdist.py.
Referenced by build_tracker_id().
_get_build_requires_wheel()
Iterable[str] pip._internal.distributions.sdist.SourceDistribution._get_build_requires_wheel (self) protected
Definition at line 95 of file sdist.py.
Referenced by build_tracker_id().
_install_build_reqs()
None pip._internal.distributions.sdist.SourceDistribution._install_build_reqs (self, PackageFinder finder) protected
Definition at line 113 of file sdist.py.
Referenced by build_tracker_id().
_prepare_build_backend()
None pip._internal.distributions.sdist.SourceDistribution._prepare_build_backend (self, PackageFinder finder) protected
Definition at line 69 of file sdist.py.
Referenced by build_tracker_id().
_raise_conflicts()
None pip._internal.distributions.sdist.SourceDistribution._raise_conflicts (self, str conflicting_with, Set[Tuple[str, str]] conflicting_reqs) protected
Definition at line 132 of file sdist.py.
Referenced by build_tracker_id().
_raise_missing_reqs()
None pip._internal.distributions.sdist.SourceDistribution._raise_missing_reqs (self, Set[str] missing) protected
Definition at line 149 of file sdist.py.
Referenced by build_tracker_id().
build_tracker_id()
Optional[str] pip._internal.distributions.sdist.SourceDistribution.build_tracker_id (self)
Identify this requirement uniquely by its link.
Reimplemented from pip._internal.distributions.base.AbstractDistribution.
Definition at line 22 of file sdist.py.
References _get_build_requires_editable(), _get_build_requires_wheel(), _install_build_reqs(), _prepare_build_backend(), _raise_conflicts(), _raise_missing_reqs(), and pip._internal.distributions.base.AbstractDistribution.req.
get_metadata_distribution()
BaseDistribution pip._internal.distributions.sdist.SourceDistribution.get_metadata_distribution (self)
Reimplemented from pip._internal.distributions.base.AbstractDistribution.
Definition at line 27 of file sdist.py.
prepare_distribution_metadata()
None pip._internal.distributions.sdist.SourceDistribution.prepare_distribution_metadata (self, PackageFinder finder, bool build_isolation, bool check_build_deps)
Reimplemented from pip._internal.distributions.base.AbstractDistribution.
Definition at line 30 of file sdist.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py