Code Cloning Analysis: fontTools.cu2qu.cu2qu Namespace Reference
fontTools.cu2qu.cu2qu Namespace Reference
Functions
dot (v1, v2)
calc_cubic_points (a, b, c, d)
calc_cubic_parameters (p0, p1, p2, p3)
split_cubic_into_n_iter (p0, p1, p2, p3, n)
_split_cubic_into_n_gen (p0, p1, p2, p3, n)
split_cubic_into_two (p0, p1, p2, p3)
split_cubic_into_three (p0, p1, p2, p3)
cubic_approx_control (t, p0, p1, p2, p3)
calc_intersect (a, b, c, d)
cubic_farthest_fit_inside (p0, p1, p2, p3, tolerance)
cubic_approx_quadratic (cubic, tolerance)
cubic_approx_spline (cubic, n, tolerance, all_quadratic)
curve_to_quadratic (curve, max_err, all_quadratic=True)
curves_to_quadratic (curves, max_errors, all_quadratic=True)
Variables
COMPILED = cython.compiled
list __all__ = ["curve_to_quadratic", "curves_to_quadratic"]
int MAX_N = 100
NAN = float("NaN")
Function Documentation
_split_cubic_into_n_gen()
fontTools.cu2qu.cu2qu._split_cubic_into_n_gen (p0, p1, p2, p3, n) protected
Definition at line 138 of file cu2qu.py.
calc_cubic_parameters()
fontTools.cu2qu.cu2qu.calc_cubic_parameters (p0, p1, p2, p3)
Definition at line 74 of file cu2qu.py.
calc_cubic_points()
fontTools.cu2qu.cu2qu.calc_cubic_points (a, b, c, d)
Definition at line 60 of file cu2qu.py.
calc_intersect()
fontTools.cu2qu.cu2qu.calc_intersect (a, b, c, d)
Calculate the intersection of two lines.
Args:
    a (complex): Start point of first line.
    b (complex): End point of first line.
    c (complex): Start point of second line.
    d (complex): End point of second line.
Returns:
    complex: Location of intersection if one present, ``complex(NaN,NaN)``
    if no intersection was found.
Definition at line 257 of file cu2qu.py.
References dot().
Referenced by cubic_approx_quadratic().
cubic_approx_control()
fontTools.cu2qu.cu2qu.cubic_approx_control (t, p0, p1, p2, p3)
Approximate a cubic Bezier using a quadratic one.
Args:
    t (double): Position of control point.
    p0 (complex): Start point of curve.
    p1 (complex): First handle of curve.
    p2 (complex): Second handle of curve.
    p3 (complex): End point of curve.
Returns:
    complex: Location of candidate control point on quadratic curve.
Definition at line 234 of file cu2qu.py.
Referenced by cubic_approx_spline().
cubic_approx_quadratic()
fontTools.cu2qu.cu2qu.cubic_approx_quadratic (cubic, tolerance)
Approximate a cubic Bezier with a single quadratic within a given tolerance.
Args:
    cubic (sequence): Four complex numbers representing control points of
        the cubic Bezier curve.
    tolerance (double): Permitted deviation from the original curve.
Returns:
    Three complex numbers representing control points of the quadratic
    curve if it fits within the given tolerance, or ``None`` if no suitable
    curve could be calculated.
Definition at line 332 of file cu2qu.py.
References calc_intersect(), and cubic_farthest_fit_inside().
Referenced by cubic_approx_spline().
cubic_approx_spline()
fontTools.cu2qu.cu2qu.cubic_approx_spline (cubic, n, tolerance, all_quadratic)
Approximate a cubic Bezier curve with a spline of n quadratics.
Args:
    cubic (sequence): Four complex numbers representing control points of
        the cubic Bezier curve.
    n (int): Number of quadratic Bezier curves in the spline.
    tolerance (double): Permitted deviation from the original curve.
Returns:
    A list of ``n+2`` complex numbers, representing control points of the
    quadratic spline if it fits within the given tolerance, or ``None`` if
    no suitable spline could be calculated.
Definition at line 372 of file cu2qu.py.
References cubic_approx_control(), cubic_approx_quadratic(), cubic_farthest_fit_inside(), and split_cubic_into_n_iter().
Referenced by curve_to_quadratic(), and curves_to_quadratic().
cubic_farthest_fit_inside()
fontTools.cu2qu.cu2qu.cubic_farthest_fit_inside (p0, p1, p2, p3, tolerance)
Check if a cubic Bezier lies within a given distance of the origin.
"Origin" means *the* origin (0,0), not the start of the curve. Note that no
checks are made on the start and end positions of the curve; this function
only checks the inside of the curve.
Args:
    p0 (complex): Start point of curve.
    p1 (complex): First handle of curve.
    p2 (complex): Second handle of curve.
    p3 (complex): End point of curve.
    tolerance (double): Distance from origin.
Returns:
    bool: True if the cubic Bezier ``p`` entirely lies within a distance
    ``tolerance`` of the origin, False otherwise.
Definition at line 290 of file cu2qu.py.
References cubic_farthest_fit_inside().
Referenced by cubic_approx_quadratic(), cubic_approx_spline(), and cubic_farthest_fit_inside().
curve_to_quadratic()
fontTools.cu2qu.cu2qu.curve_to_quadratic (curve, max_err, all_quadratic = True)
Approximate a cubic Bezier curve with a spline of n quadratics.
Args:
    cubic (sequence): Four 2D tuples representing control points of
        the cubic Bezier curve.
    max_err (double): Permitted deviation from the original curve.
    all_quadratic (bool): If True (default) returned value is a
        quadratic spline. If False, it's either a single quadratic
        curve or a single cubic curve.
Returns:
    If all_quadratic is True: A list of 2D tuples, representing
    control points of the quadratic spline if it fits within the
    given tolerance, or ``None`` if no suitable spline could be
    calculated.
    If all_quadratic is False: Either a quadratic curve (if length
    of output is 3), or a cubic curve (if length of output is 4).
Definition at line 439 of file cu2qu.py.
References cubic_approx_spline().
curves_to_quadratic()
fontTools.cu2qu.cu2qu.curves_to_quadratic (curves, max_errors, all_quadratic = True)
Return quadratic Bezier splines approximating the input cubic Beziers.
Args:
    curves: A sequence of *n* curves, each curve being a sequence of four
        2D tuples.
    max_errors: A sequence of *n* floats representing the maximum permissible
        deviation from each of the cubic Bezier curves.
    all_quadratic (bool): If True (default) returned values are a
        quadratic spline. If False, they are either a single quadratic
        curve or a single cubic curve.
Example::
    >>> curves_to_quadratic( [
    ...   [ (50,50), (100,100), (150,100), (200,50) ],
    ...   [ (75,50), (120,100), (150,75),  (200,60) ]
    ... ], [1,1] )
    [[(50.0, 50.0), (75.0, 75.0), (125.0, 91.66666666666666), (175.0, 75.0), (200.0, 50.0)], [(75.0, 50.0), (97.5, 75.0), (135.41666666666666, 82.08333333333333), (175.0, 67.5), (200.0, 60.0)]]
The returned splines have "implied oncurve points" suitable for use in
TrueType ``glif`` outlines - i.e. in the first spline returned above,
the first quadratic segment runs from (50,50) to
((75 + 125)/2 , (120 + 91.666..)/2) = (100, 83.333...).
Returns:
    If all_quadratic is True, a list of splines, each spline being a list
    of 2D tuples.
    If all_quadratic is False, a list of curves, each curve being a quadratic
    (length 3), or cubic (length 4).
Raises:
    fontTools.cu2qu.Errors.ApproxNotFoundError: if no suitable approximation
    can be found for all curves with the given parameters.
Definition at line 473 of file cu2qu.py.
References cubic_approx_spline().
Referenced by fontTools.cu2qu.ufo._segments_to_quadratic().
dot()
fontTools.cu2qu.cu2qu.dot (v1, v2)
Return the dot product of two vectors.
Args:
    v1 (complex): First vector.
    v2 (complex): Second vector.
Returns:
    double: Dot product.
Definition at line 41 of file cu2qu.py.
Referenced by calc_intersect().
split_cubic_into_n_iter()
fontTools.cu2qu.cu2qu.split_cubic_into_n_iter (p0, p1, p2, p3, n)
Split a cubic Bezier into n equal parts.
Splits the curve into `n` equal parts by curve time.
(t=0..1/n, t=1/n..2/n, ...)
Args:
    p0 (complex): Start point of curve.
    p1 (complex): First handle of curve.
    p2 (complex): Second handle of curve.
    p3 (complex): End point of curve.
Returns:
    An iterator yielding the control points (four complex values) of the
    subcurves.
Definition at line 87 of file cu2qu.py.
References split_cubic_into_three(), and split_cubic_into_two().
Referenced by cubic_approx_spline().
split_cubic_into_three()
fontTools.cu2qu.cu2qu.split_cubic_into_three (p0, p1, p2, p3)
Split a cubic Bezier into three equal parts.
Splits the curve into three equal parts at t = 1/3 and t = 2/3
Args:
    p0 (complex): Start point of curve.
    p1 (complex): First handle of curve.
    p2 (complex): Second handle of curve.
    p3 (complex): End point of curve.
Returns:
    tuple: Three cubic Beziers (each expressed as a tuple of four complex
    values).
Definition at line 197 of file cu2qu.py.
Referenced by split_cubic_into_n_iter().
split_cubic_into_two()
fontTools.cu2qu.cu2qu.split_cubic_into_two (p0, p1, p2, p3)
Split a cubic Bezier into two equal parts.
Splits the curve into two equal parts at t = 0.5
Args:
    p0 (complex): Start point of curve.
    p1 (complex): First handle of curve.
    p2 (complex): Second handle of curve.
    p3 (complex): End point of curve.
Returns:
    tuple: Two cubic Beziers (each expressed as a tuple of four complex
    values).
Definition at line 160 of file cu2qu.py.
Referenced by split_cubic_into_n_iter().
Variable Documentation
__all__
list fontTools.cu2qu.cu2qu.__all__ = ["curve_to_quadratic", "curves_to_quadratic"] private
Definition at line 30 of file cu2qu.py.
COMPILED
fontTools.cu2qu.cu2qu.COMPILED = cython.compiled
Definition at line 23 of file cu2qu.py.
MAX_N
int fontTools.cu2qu.cu2qu.MAX_N = 100
Definition at line 32 of file cu2qu.py.
NAN
fontTools.cu2qu.cu2qu.NAN = float("NaN")
Definition at line 34 of file cu2qu.py.