Code Cloning Analysis: pandas._typing.WriteBuffer Class Reference
pandas._typing.WriteBuffer Class Reference
Public Member Functions
Any write (self, AnyStr_contra __b)
Any flush (self)
Public Member Functions inherited from pandas._typing.BaseBuffer
str mode (self)
int seek (self, int __offset, int __whence=...)
bool seekable (self)
int tell (self)
Detailed Description
Definition at line 288 of file _typing.py.
Member Function Documentation
flush()
Any pandas._typing.WriteBuffer.flush (self)
Definition at line 293 of file _typing.py.
Referenced by scipy.io._netcdf.netcdf_file.close().
write()
Any pandas._typing.WriteBuffer.write (self, AnyStr_contra __b)
Definition at line 289 of file _typing.py.
Referenced by joblib.externals.cloudpickle.cloudpickle.Pickler.reducer_override(), scipy.io.matlab._mio5.VarWriter5.write_sparse(), pandas.io.formats.html.HTMLFormatter.write_th(), and scipy.io.matlab._mio5.VarWriter5.write_top().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/_typing.py