Code Cloning Analysis: pandas.util.version.LegacyVersion Class Reference
pandas.util.version.LegacyVersion Class Reference
Public Member Functions
None __init__ (self, str version)
str __str__ (self)
str __repr__ (self)
str public (self)
str base_version (self)
int epoch (self)
None release (self)
None pre (self)
None post (self)
None dev (self)
None local (self)
bool is_prerelease (self)
bool is_postrelease (self)
bool is_devrelease (self)
Public Member Functions inherited from pandas.util.version._BaseVersion
int __hash__ (self)
bool __lt__ (self, _BaseVersion other)
bool __le__ (self, _BaseVersion other)
bool __eq__ (self, object other)
bool __ge__ (self, _BaseVersion other)
bool __gt__ (self, _BaseVersion other)
bool __ne__ (self, object other)
Protected Attributes
_version = str(version)
Additional Inherited Members
Static Protected Attributes inherited from pandas.util.version._BaseVersion
CmpKey _key | LegacyCmpKey
Detailed Description
Definition at line 186 of file __init__.py.
Constructor & Destructor Documentation
__init__()
None pandas.util.version.LegacyVersion.__init__ (self, str version)
Definition at line 187 of file __init__.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
__repr__()
str pandas.util.version.LegacyVersion.__repr__ (self)
Definition at line 200 of file __init__.py.
__str__()
str pandas.util.version.LegacyVersion.__str__ (self)
Definition at line 197 of file __init__.py.
base_version()
str pandas.util.version.LegacyVersion.base_version (self)
Definition at line 208 of file __init__.py.
dev()
None pandas.util.version.LegacyVersion.dev (self)
Definition at line 228 of file __init__.py.
epoch()
int pandas.util.version.LegacyVersion.epoch (self)
Definition at line 212 of file __init__.py.
is_devrelease()
bool pandas.util.version.LegacyVersion.is_devrelease (self)
Definition at line 244 of file __init__.py.
is_postrelease()
bool pandas.util.version.LegacyVersion.is_postrelease (self)
Definition at line 240 of file __init__.py.
is_prerelease()
bool pandas.util.version.LegacyVersion.is_prerelease (self)
Definition at line 236 of file __init__.py.
local()
None pandas.util.version.LegacyVersion.local (self)
Definition at line 232 of file __init__.py.
post()
None pandas.util.version.LegacyVersion.post (self)
Definition at line 224 of file __init__.py.
pre()
None pandas.util.version.LegacyVersion.pre (self)
Definition at line 220 of file __init__.py.
public()
str pandas.util.version.LegacyVersion.public (self)
Definition at line 204 of file __init__.py.
release()
None pandas.util.version.LegacyVersion.release (self)
Definition at line 216 of file __init__.py.
Member Data Documentation
_version
pandas.util.version.LegacyVersion._version = str(version) protected
Definition at line 188 of file __init__.py.
Referenced by pip._internal.resolution.resolvelib.candidates._InstallRequirementBackedCandidate._check_metadata_consistency(), pip._internal.resolution.resolvelib.candidates._InstallRequirementBackedCandidate.name(), pip._internal.resolution.resolvelib.candidates.AlreadyInstalledCandidate.name(), and pip._internal.resolution.resolvelib.candidates.RequiresPythonCandidate.name().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/util/version/__init__.py