Code Cloning Analysis: dateutil.tz.win.tzres Class Reference
dateutil.tz.win.tzres Class Reference
Public Member Functions
__init__ (self, tzres_loc='tzres.dll')
load_name (self, offset)
name_from_string (self, tzname_str)
Public Attributes
LoadStringW = user32.LoadStringW
tzres_loc = tzres_loc
Static Public Attributes
p_wchar = ctypes.POINTER(wintypes.WCHAR)
Protected Attributes
_tzres = ctypes.WinDLL(tzres_loc)
Detailed Description
Class for accessing ``tzres.dll``, which contains timezone name related
resources.
.. versionadded:: 2.5.0
Definition at line 48 of file win.py.
Constructor & Destructor Documentation
__init__()
dateutil.tz.win.tzres.__init__ (self, tzres_loc = 'tzres.dll')
Definition at line 57 of file win.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
load_name()
dateutil.tz.win.tzres.load_name (self, offset)
Load a timezone name from a DLL offset (integer).
>>> from dateutil.tzwin import tzres
>>> tzr = tzres()
>>> print(tzr.load_name(112))
'Eastern Standard Time'
:param offset:
    A positive integer value referring to a string from the tzres dll.
.. note::
    Offsets found in the registry are generally of the form
    ``@tzres.dll,-114``. The offset in this case is 114, not -114.
Definition at line 71 of file win.py.
References _tzres, LoadStringW, and p_wchar.
Referenced by name_from_string().
name_from_string()
dateutil.tz.win.tzres.name_from_string (self, tzname_str)
Parse strings as returned from the Windows registry into the time zone
name as defined in the registry.
>>> from dateutil.tzwin import tzres
>>> tzr = tzres()
>>> print(tzr.name_from_string('@tzres.dll,-251'))
'Dateline Daylight Time'
>>> print(tzr.name_from_string('Eastern Standard Time'))
'Eastern Standard Time'
:param tzname_str:
    A timezone name string as returned from a Windows registry key.
:return:
    Returns the localized timezone string from tzres.dll if the string
    is of the form `@tzres.dll,-offset`, else returns the input string.
Definition at line 94 of file win.py.
References load_name().
Member Data Documentation
_tzres
dateutil.tz.win.tzres._tzres = ctypes.WinDLL(tzres_loc) protected
Definition at line 68 of file win.py.
Referenced by load_name().
LoadStringW
dateutil.tz.win.tzres.LoadStringW = user32.LoadStringW
Definition at line 67 of file win.py.
Referenced by load_name().
p_wchar
dateutil.tz.win.tzres.p_wchar = ctypes.POINTER(wintypes.WCHAR) static
Definition at line 55 of file win.py.
Referenced by load_name().
tzres_loc
dateutil.tz.win.tzres.tzres_loc = tzres_loc
Definition at line 69 of file win.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/dateutil/tz/win.py