Code Cloning Analysis: fontTools.cffLib.transforms._DehintingT2Decompiler Class Reference
fontTools.cffLib.transforms._DehintingT2Decompiler Class Reference
Classes
class Hints
Public Member Functions
__init__ (self, css, localSubrs, globalSubrs, nominalWidthX, defaultWidthX, private=None)
execute (self, charString)
op_callsubr (self, index)
op_callgsubr (self, index)
op_hstem (self, index)
op_vstem (self, index)
op_hstemhm (self, index)
op_vstemhm (self, index)
op_hintmask (self, index)
op_cntrmask (self, index)
processHintmask (self, index)
processHint (self, index)
processSubr (self, index, subr)
Public Member Functions inherited from fontTools.misc.psCharStrings.T2WidthExtractor
__init__ (self, localSubrs, globalSubrs, nominalWidthX, defaultWidthX, private=None, blender=None)
reset (self)
popallWidth (self, evenOdd=0)
countHints (self)
op_rmoveto (self, index)
op_hmoveto (self, index)
op_vmoveto (self, index)
op_endchar (self, index)
Public Member Functions inherited from fontTools.misc.psCharStrings.SimpleT2Decompiler
__init__ (self, localSubrs, globalSubrs, private=None, blender=None)
pop (self)
popall (self)
push (self, value)
op_return (self, index)
op_ignore (self, index)
op_and (self, index)
op_or (self, index)
op_not (self, index)
op_store (self, index)
op_abs (self, index)
op_add (self, index)
op_sub (self, index)
op_div (self, index)
op_load (self, index)
op_neg (self, index)
op_eq (self, index)
op_drop (self, index)
op_put (self, index)
op_get (self, index)
op_ifelse (self, index)
op_random (self, index)
op_mul (self, index)
op_sqrt (self, index)
op_dup (self, index)
op_exch (self, index)
op_index (self, index)
op_roll (self, index)
op_blend (self, index)
op_vsindex (self, index)
Protected Attributes
_css = css
Additional Inherited Members
Public Attributes inherited from fontTools.misc.psCharStrings.T2WidthExtractor
nominalWidthX = nominalWidthX
defaultWidthX = defaultWidthX
int gotWidth = 0
int width = 0
Public Attributes inherited from fontTools.misc.psCharStrings.SimpleT2Decompiler
localSubrs = localSubrs
localBias = calcSubrBias(localSubrs)
globalSubrs = globalSubrs
globalBias = calcSubrBias(globalSubrs)
private = private
blender = blender
list callingStack = []
list operandStack = []
int hintCount = 0
int hintMaskBytes = 0
int numRegions = 0
int vsIndex = 0
Detailed Description
Definition at line 142 of file transforms.py.
Constructor & Destructor Documentation
__init__()
fontTools.cffLib.transforms._DehintingT2Decompiler.__init__ (self, css, localSubrs, globalSubrs, nominalWidthX, defaultWidthX, private = None)
Definition at line 169 of file transforms.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
execute()
fontTools.cffLib.transforms._DehintingT2Decompiler.execute (self, charString)
Reimplemented from fontTools.misc.psCharStrings.SimpleT2Decompiler.
Definition at line 178 of file transforms.py.
Referenced by pandas.io.sql.SQLiteDatabase._query_iterator(), pandas.io.sql.SQLDatabase.read_query(), and pandas.io.sql.SQLiteDatabase.to_sql().
op_callgsubr()
fontTools.cffLib.transforms._DehintingT2Decompiler.op_callgsubr (self, index)
Reimplemented from fontTools.misc.psCharStrings.SimpleT2Decompiler.
Definition at line 207 of file transforms.py.
op_callsubr()
fontTools.cffLib.transforms._DehintingT2Decompiler.op_callsubr (self, index)
Reimplemented from fontTools.misc.psCharStrings.SimpleT2Decompiler.
Definition at line 202 of file transforms.py.
op_cntrmask()
fontTools.cffLib.transforms._DehintingT2Decompiler.op_cntrmask (self, index)
Reimplemented from fontTools.misc.psCharStrings.SimpleT2Decompiler.
Definition at line 233 of file transforms.py.
op_hintmask()
fontTools.cffLib.transforms._DehintingT2Decompiler.op_hintmask (self, index)
Reimplemented from fontTools.misc.psCharStrings.SimpleT2Decompiler.
Definition at line 228 of file transforms.py.
op_hstem()
fontTools.cffLib.transforms._DehintingT2Decompiler.op_hstem (self, index)
Reimplemented from fontTools.misc.psCharStrings.SimpleT2Decompiler.
Definition at line 212 of file transforms.py.
op_hstemhm()
fontTools.cffLib.transforms._DehintingT2Decompiler.op_hstemhm (self, index)
Reimplemented from fontTools.misc.psCharStrings.SimpleT2Decompiler.
Definition at line 220 of file transforms.py.
op_vstem()
fontTools.cffLib.transforms._DehintingT2Decompiler.op_vstem (self, index)
Reimplemented from fontTools.misc.psCharStrings.SimpleT2Decompiler.
Definition at line 216 of file transforms.py.
op_vstemhm()
fontTools.cffLib.transforms._DehintingT2Decompiler.op_vstemhm (self, index)
Reimplemented from fontTools.misc.psCharStrings.SimpleT2Decompiler.
Definition at line 224 of file transforms.py.
processHint()
fontTools.cffLib.transforms._DehintingT2Decompiler.processHint (self, index)
Definition at line 255 of file transforms.py.
processHintmask()
fontTools.cffLib.transforms._DehintingT2Decompiler.processHintmask (self, index)
Definition at line 238 of file transforms.py.
processSubr()
fontTools.cffLib.transforms._DehintingT2Decompiler.processSubr (self, index, subr)
Definition at line 262 of file transforms.py.
Member Data Documentation
_css
fontTools.cffLib.transforms._DehintingT2Decompiler._css = css protected
Definition at line 172 of file transforms.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/cffLib/transforms.py