Code Cloning Analysis: matplotlib.dates._SwitchableDateConverter Class Reference
matplotlib.dates._SwitchableDateConverter Class Reference
Public Member Functions
axisinfo (self, *args, **kwargs)
default_units (self, *args, **kwargs)
convert (self, *args, **kwargs)
Static Protected Member Functions
_get_converter ()
Detailed Description
Helper converter-like object that generates and dispatches to
temporary ConciseDateConverter or DateConverter instances based on
:rc:`date.converter` and :rc:`date.interval_multiples`.
Definition at line 1812 of file dates.py.
Member Function Documentation
_get_converter()
matplotlib.dates._SwitchableDateConverter._get_converter () static protected
Definition at line 1820 of file dates.py.
axisinfo()
matplotlib.dates._SwitchableDateConverter.axisinfo (self, * args, ** kwargs)
Definition at line 1827 of file dates.py.
convert()
matplotlib.dates._SwitchableDateConverter.convert (self, * args, ** kwargs)
Definition at line 1833 of file dates.py.
Referenced by matplotlib.testing.jpl_units.Epoch.Epoch.__add__(), matplotlib.testing.jpl_units.Epoch.Epoch.__init__(), matplotlib.testing.jpl_units.Epoch.Epoch.__sub__(), matplotlib.testing.jpl_units.Epoch.Epoch._cmp(), pandas.core.computation.engines.NumExprEngine._evaluate(), pandas.core.internals.blocks.Block.convert(), PIL.Image.Image.reduce(), PIL.Image.Image.resize(), and PIL.Image.Image.transform().
default_units()
matplotlib.dates._SwitchableDateConverter.default_units (self, * args, ** kwargs)
Definition at line 1830 of file dates.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/dates.py