Code Cloning Analysis: matplotlib.animation.FuncAnimation Class Reference
matplotlib.animation.FuncAnimation Class Reference
Public Member Functions
__init__ (self, fig, func, frames=None, init_func=None, fargs=None, save_count=None, *, cache_frame_data=True, **kwargs)
new_frame_seq (self)
new_saved_frame_seq (self)
Public Member Functions inherited from matplotlib.animation.TimedAnimation
__init__ (self, fig, interval=200, repeat_delay=0, repeat=True, event_source=None, *args, **kwargs)
Public Member Functions inherited from matplotlib.animation.Animation
__init__ (self, fig, event_source=None, blit=False)
__del__ (self)
save (self, filename, writer=None, fps=None, dpi=None, codec=None, bitrate=None, extra_args=None, metadata=None, extra_anim=None, savefig_kwargs=None, *, progress_callback=None)
to_html5_video (self, embed_limit=None)
to_jshtml (self, fps=None, embed_frames=True, default_mode=None)
pause (self)
resume (self)
Protected Member Functions
_init_draw (self)
_draw_frame (self, framedata)
Protected Member Functions inherited from matplotlib.animation.TimedAnimation
_step (self, *args)
Protected Member Functions inherited from matplotlib.animation.Animation
_start (self, *args)
_stop (self, *args)
_draw_next_frame (self, framedata, blit)
_pre_draw (self, framedata, blit)
_post_draw (self, framedata, blit)
_blit_draw (self, artists)
_blit_clear (self, artists)
_setup_blit (self)
_on_resize (self, event)
_end_redraw (self, event)
_repr_html_ (self)
Protected Attributes
tuple _args = fargs
_func = func
_init_func = init_func
_save_count = save_count
_iter_gen = itertools.count
_tee_from = frames
_cache_frame_data = cache_frame_data
list _save_seq = []
_old_saved_seq = list(self._save_seq)
Protected Attributes inherited from matplotlib.animation.TimedAnimation
_interval = interval
int _repeat_delay = repeat_delay if repeat_delay is not None else 0
_repeat = repeat
Protected Attributes inherited from matplotlib.animation.Animation
bool _draw_was_started = False
_fig = fig
_blit = blit and fig.canvas.supports_blit
_first_draw_id = fig.canvas.mpl_connect('draw_event', self._start)
_close_id
_resize_id
_framedata
list _drawn_artists
_blit_cache = dict()
_base64_video = vid64.decode('ascii')
str _video_size
_html_representation = path.read_text()
Additional Inherited Members
Public Attributes inherited from matplotlib.animation.Animation
frame_seq = self.new_frame_seq()
event_source = event_source
Detailed Description
`TimedAnimation` subclass that makes an animation by repeatedly calling
a function *func*.
.. note::
    You must store the created Animation in a variable that lives as long
    as the animation should run. Otherwise, the Animation object will be
    garbage-collected and the animation stops.
Parameters
----------
fig : `~matplotlib.figure.Figure`
    The figure object used to get needed events, such as draw or resize.
func : callable
    The function to call at each frame.  The first argument will
    be the next value in *frames*.   Any additional positional
    arguments can be supplied using `functools.partial` or via the *fargs*
    parameter.
    The required signature is::
        def func(frame, *fargs) -> iterable_of_artists
    It is often more convenient to provide the arguments using
    `functools.partial`. In this way it is also possible to pass keyword
    arguments. To pass a function with both positional and keyword
    arguments, set all arguments as keyword arguments, just leaving the
    *frame* argument unset::
        def func(frame, art, *, y=None):
            ...
        ani = FuncAnimation(fig, partial(func, art=ln, y='foo'))
    If ``blit == True``, *func* must return an iterable of all artists
    that were modified or created. This information is used by the blitting
    algorithm to determine which parts of the figure have to be updated.
    The return value is unused if ``blit == False`` and may be omitted in
    that case.
frames : iterable, int, generator function, or None, optional
    Source of data to pass *func* and each frame of the animation
    - If an iterable, then simply use the values provided.  If the
      iterable has a length, it will override the *save_count* kwarg.
    - If an integer, then equivalent to passing ``range(frames)``
    - If a generator function, then must have the signature::
         def gen_function() -> obj
    - If *None*, then equivalent to passing ``itertools.count``.
    In all of these cases, the values in *frames* is simply passed through
    to the user-supplied *func* and thus can be of any type.
init_func : callable, optional
    A function used to draw a clear frame. If not given, the results of
    drawing from the first item in the frames sequence will be used. This
    function will be called once before the first frame.
    The required signature is::
        def init_func() -> iterable_of_artists
    If ``blit == True``, *init_func* must return an iterable of artists
    to be re-drawn. This information is used by the blitting algorithm to
    determine which parts of the figure have to be updated.  The return
    value is unused if ``blit == False`` and may be omitted in that case.
fargs : tuple or None, optional
    Additional arguments to pass to each call to *func*. Note: the use of
    `functools.partial` is preferred over *fargs*. See *func* for details.
save_count : int, optional
    Fallback for the number of values from *frames* to cache. This is
    only used if the number of frames cannot be inferred from *frames*,
    i.e. when it's an iterator without length or a generator.
interval : int, default: 200
    Delay between frames in milliseconds.
repeat_delay : int, default: 0
    The delay in milliseconds between consecutive animation runs, if
    *repeat* is True.
repeat : bool, default: True
    Whether the animation repeats when the sequence of frames is completed.
blit : bool, default: False
    Whether blitting is used to optimize drawing.  Note: when using
    blitting, any animated artists will be drawn according to their zorder;
    however, they will be drawn on top of any previous artists, regardless
    of their zorder.
cache_frame_data : bool, default: True
    Whether frame data is cached.  Disabling cache might be helpful when
    frames contain large objects.
Definition at line 1550 of file animation.py.
Constructor & Destructor Documentation
__init__()
matplotlib.animation.FuncAnimation.__init__ (self, fig, func, frames = None, init_func = None, fargs = None, save_count = None, * , cache_frame_data = True, ** kwargs)
Definition at line 1653 of file animation.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_draw_frame()
matplotlib.animation.FuncAnimation._draw_frame (self, framedata) protected
Reimplemented from matplotlib.animation.Animation.
Definition at line 1781 of file animation.py.
_init_draw()
matplotlib.animation.FuncAnimation._init_draw (self) protected
Reimplemented from matplotlib.animation.Animation.
Definition at line 1749 of file animation.py.
new_frame_seq()
matplotlib.animation.FuncAnimation.new_frame_seq (self)
Return a new sequence of frame information.
Reimplemented from matplotlib.animation.Animation.
Definition at line 1722 of file animation.py.
References _iter_gen.
new_saved_frame_seq()
matplotlib.animation.FuncAnimation.new_saved_frame_seq (self)
Return a new sequence of saved/cached frame information.
Reimplemented from matplotlib.animation.Animation.
Definition at line 1726 of file animation.py.
References _args, matplotlib.animation.Animation._blit, _cache_frame_data, matplotlib.animation.Animation._draw_frame(), matplotlib.animation.Animation._drawn_artists, _func, _init_func, _old_saved_seq, _save_count, _save_seq, and matplotlib.animation.Animation.new_frame_seq().
Member Data Documentation
_args
tuple matplotlib.animation.FuncAnimation._args = fargs protected
Definition at line 1656 of file animation.py.
Referenced by new_saved_frame_seq(), and matplotlib.animation.MovieWriter.setup().
_cache_frame_data
matplotlib.animation.FuncAnimation._cache_frame_data = cache_frame_data protected
Definition at line 1711 of file animation.py.
Referenced by new_saved_frame_seq().
_func
matplotlib.animation.FuncAnimation._func = func protected
Definition at line 1659 of file animation.py.
Referenced by numpy.ma.core._convert2ma._replace_return_type(), and new_saved_frame_seq().
_init_func
matplotlib.animation.FuncAnimation._init_func = init_func protected
Definition at line 1660 of file animation.py.
Referenced by new_saved_frame_seq().
_iter_gen
matplotlib.animation.FuncAnimation._iter_gen = itertools.count protected
Definition at line 1672 of file animation.py.
Referenced by new_frame_seq().
_old_saved_seq
matplotlib.animation.FuncAnimation._old_saved_seq = list(self._save_seq) protected
Definition at line 1733 of file animation.py.
Referenced by new_saved_frame_seq().
_save_count
matplotlib.animation.FuncAnimation._save_count = save_count protected
Definition at line 1665 of file animation.py.
Referenced by new_saved_frame_seq().
_save_seq
list matplotlib.animation.FuncAnimation._save_seq = [] protected
Definition at line 1714 of file animation.py.
Referenced by new_saved_frame_seq().
_tee_from
matplotlib.animation.FuncAnimation._tee_from = frames protected
Definition at line 1677 of file animation.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/animation.py