Code Cloning Analysis: scipy.stats._qmvnt Namespace Reference
scipy.stats._qmvnt Namespace Reference
Functions
_factorize_int (n)
_primitive_root (p)
_cbc_lattice (n_dim, n_qmc_samples)
_qauto (func, covar, low, high, rng, error=1e-3, limit=10_000, **kwds)
_qmvn (m, covar, low, high, rng, lattice='cbc', n_batches=10)
_mvn_qmc_integrand (covar, low, high, use_tent=False)
_qmvt (m, nu, covar, low, high, rng, lattice='cbc', n_batches=10)
_permuted_cholesky (covar, low, high, tol=1e-10)
_swap_slices (x, slc1, slc2)
Variables
phi = ndtr
phinv = ndtri
Function Documentation
_cbc_lattice()
scipy.stats._qmvnt._cbc_lattice (n_dim, n_qmc_samples) protected
Compute a QMC lattice generator using a Fast CBC construction.
Parameters
----------
n_dim : int > 0
    The number of dimensions for the lattice.
n_qmc_samples : int > 0
    The desired number of QMC samples. This will be rounded down to the
    nearest prime to enable the CBC construction.
Returns
-------
q : float array : shape=(n_dim,)
    The lattice generator vector. All values are in the open interval
    `(0, 1)`.
actual_n_qmc_samples : int
    The prime number of QMC samples that must be used with this lattice,
    no more, no less.
References
----------
.. [1] Nuyens, D. and Cools, R. "Fast Component-by-Component Construction,
       a Reprise for Different Kernels", In H. Niederreiter and D. Talay,
       editors, Monte-Carlo and Quasi-Monte Carlo Methods 2004,
       Springer-Verlag, 2006, 371-385.
Definition at line 89 of file _qmvnt.py.
References _primitive_root().
Referenced by _qmvn(), and _qmvt().
_factorize_int()
scipy.stats._qmvnt._factorize_int (n) protected
Return a sorted list of the unique prime factors of a positive integer.
Definition at line 46 of file _qmvnt.py.
Referenced by _primitive_root().
_mvn_qmc_integrand()
scipy.stats._qmvnt._mvn_qmc_integrand (covar, low, high, use_tent = False) protected
Transform the multivariate normal integration into a QMC integrand over
a unit hypercube.
The dimensionality of the resulting hypercube integration domain is one
less than the dimensionality of the original integrand. Note that this
transformation subsumes the integration bounds in order to account for
infinite bounds. The QMC integration one does with the returned integrand
should be on the unit hypercube.
Parameters
----------
covar : (n, n) float array
    Possibly singular, positive semidefinite symmetric covariance matrix.
low, high : (n,) float array
    The low and high integration bounds.
use_tent : bool, optional
    If True, then use tent periodization. Only helpful for lattice rules.
Returns
-------
integrand : Callable[[NDArray], NDArray]
    The QMC-integrable integrand. It takes an
    ``(n_qmc_samples, ndim_integrand)`` array of QMC samples in the unit
    hypercube and returns the ``(n_qmc_samples,)`` evaluations of at these
    QMC points.
ndim_integrand : int
    The dimensionality of the integrand. Equal to ``n-1``.
Definition at line 274 of file _qmvnt.py.
References _permuted_cholesky().
_permuted_cholesky()
scipy.stats._qmvnt._permuted_cholesky (covar, low, high, tol = 1e-10) protected
Compute a scaled, permuted Cholesky factor, with integration bounds.
The scaling and permuting of the dimensions accomplishes part of the
transformation of the original integration problem into a more numerically
tractable form. The lower-triangular Cholesky factor will then be used in
the subsequent integration. The integration bounds will be scaled and
permuted as well.
Parameters
----------
covar : (n, n) float array
    Possibly singular, positive semidefinite symmetric covariance matrix.
low, high : (n,) float array
    The low and high integration bounds.
tol : float, optional
    The singularity tolerance.
Returns
-------
cho : (n, n) float array
    Lower Cholesky factor, scaled and permuted.
new_low, new_high : (n,) float array
    The scaled and permuted low and high integration bounds.
Definition at line 428 of file _qmvnt.py.
Referenced by _mvn_qmc_integrand(), _qmvn(), and _qmvt().
_primitive_root()
scipy.stats._qmvnt._primitive_root (p) protected
Compute a primitive root of the prime number `p`.
Used in the CBC lattice construction.
References
----------
.. [1] https://en.wikipedia.org/wiki/Primitive_root_modulo_n
Definition at line 62 of file _qmvnt.py.
References _factorize_int().
Referenced by _cbc_lattice().
_qauto()
scipy.stats._qmvnt._qauto (func, covar, low, high, rng, error = 1e-3, limit = 10_000, ** kwds) protected
Automatically rerun the integration to get the required error bound.
Parameters
----------
func : callable
    Either :func:`_qmvn` or :func:`_qmvt`.
covar, low, high : array
    As specified in :func:`_qmvn` and :func:`_qmvt`.
rng : Generator, optional
    default_rng(), yada, yada
error : float > 0
    The desired error bound.
limit : int > 0:
    The rough limit of the number of integration points to consider. The
    integration will stop looping once this limit has been *exceeded*.
**kwds :
    Other keyword arguments to pass to `func`. When using :func:`_qmvt`, be
    sure to include ``nu=`` as one of these.
Returns
-------
prob : float
    The estimated probability mass within the bounds.
est_error : float
    3 times the standard error of the batch estimates.
n_samples : int
    The number of integration points actually used.
Definition at line 151 of file _qmvnt.py.
_qmvn()
scipy.stats._qmvnt._qmvn (m, covar, low, high, rng, lattice = 'cbc', n_batches = 10) protected
Multivariate normal integration over box bounds.
Parameters
----------
m : int > n_batches
    The number of points to sample. This number will be divided into
    `n_batches` batches that apply random offsets of the sampling lattice
    for each batch in order to estimate the error.
covar : (n, n) float array
    Possibly singular, positive semidefinite symmetric covariance matrix.
low, high : (n,) float array
    The low and high integration bounds.
rng : Generator, optional
    default_rng(), yada, yada
lattice : 'cbc' or callable
    The type of lattice rule to use to construct the integration points.
n_batches : int > 0, optional
    The number of QMC batches to apply.
Returns
-------
prob : float
    The estimated probability mass within the bounds.
est_error : float
    3 times the standard error of the batch estimates.
Definition at line 204 of file _qmvnt.py.
References _cbc_lattice(), and _permuted_cholesky().
_qmvt()
scipy.stats._qmvnt._qmvt (m, nu, covar, low, high, rng, lattice = 'cbc', n_batches = 10) protected
Multivariate t integration over box bounds.
Parameters
----------
m : int > n_batches
    The number of points to sample. This number will be divided into
    `n_batches` batches that apply random offsets of the sampling lattice
    for each batch in order to estimate the error.
nu : float >= 0
    The shape parameter of the multivariate t distribution.
covar : (n, n) float array
    Possibly singular, positive semidefinite symmetric covariance matrix.
low, high : (n,) float array
    The low and high integration bounds.
rng : Generator, optional
    default_rng(), yada, yada
lattice : 'cbc' or callable
    The type of lattice rule to use to construct the integration points.
n_batches : int > 0, optional
    The number of QMC batches to apply.
Returns
-------
prob : float
    The estimated probability mass within the bounds.
est_error : float
    3 times the standard error of the batch estimates.
n_samples : int
    The number of samples actually used.
Definition at line 338 of file _qmvnt.py.
References _cbc_lattice(), and _permuted_cholesky().
_swap_slices()
scipy.stats._qmvnt._swap_slices (x, slc1, slc2) protected
Definition at line 530 of file _qmvnt.py.
Variable Documentation
phi
scipy.stats._qmvnt.phi = ndtr
Definition at line 42 of file _qmvnt.py.
phinv
scipy.stats._qmvnt.phinv = ndtri
Definition at line 43 of file _qmvnt.py.