Code Cloning Analysis: pandas.core.internals.concat.JoinUnit Class Reference
pandas.core.internals.concat.JoinUnit Class Reference
Public Member Functions
None __init__ (self, Block block)
str __repr__ (self)
bool is_na (self)
bool is_na_after_size_and_isna_all_deprecation (self)
ArrayLike get_reindexed_values (self, DtypeObj empty_dtype, upcasted_na)
Public Attributes
block = block
is_na
Protected Member Functions
bool _is_valid_na_for (self, DtypeObj dtype)
Detailed Description
Definition at line 350 of file concat.py.
Constructor & Destructor Documentation
__init__()
None pandas.core.internals.concat.JoinUnit.__init__ (self, Block block)
Definition at line 351 of file concat.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__repr__()
str pandas.core.internals.concat.JoinUnit.__repr__ (self)
Definition at line 354 of file concat.py.
_is_valid_na_for()
bool pandas.core.internals.concat.JoinUnit._is_valid_na_for (self, DtypeObj dtype) protected
Check that we are all-NA of a type/dtype that is compatible with this dtype.
Augments `self.is_na` with an additional check of the type of NA values.
Definition at line 357 of file concat.py.
References block, and is_na.
Referenced by is_na_after_size_and_isna_all_deprecation().
get_reindexed_values()
ArrayLike pandas.core.internals.concat.JoinUnit.get_reindexed_values (self, DtypeObj empty_dtype, upcasted_na)
Definition at line 431 of file concat.py.
is_na()
bool pandas.core.internals.concat.JoinUnit.is_na (self)
Definition at line 390 of file concat.py.
is_na_after_size_and_isna_all_deprecation()
bool pandas.core.internals.concat.JoinUnit.is_na_after_size_and_isna_all_deprecation (self)
Will self.is_na be True after values.size == 0 deprecation and isna_all
deprecation are enforced?
Definition at line 421 of file concat.py.
References _is_valid_na_for(), and block.
Member Data Documentation
block
pandas.core.internals.concat.JoinUnit.block = block
Definition at line 352 of file concat.py.
Referenced by pip._vendor.urllib3.connectionpool.HTTPConnectionPool._get_conn(), _is_valid_na_for(), and is_na_after_size_and_isna_all_deprecation().
is_na
pandas.core.internals.concat.JoinUnit.is_na
Definition at line 362 of file concat.py.
Referenced by _is_valid_na_for().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/core/internals/concat.py