Code Cloning Analysis: matplotlib.testing Namespace Reference
matplotlib.testing Namespace Reference
Namespaces
namespace _markers
namespace compare
namespace jpl_units
namespace widgets
Functions
set_font_settings_for_testing ()
set_reproducibility_for_testing ()
setup ()
subprocess_run_for_testing (command, env=None, timeout=60, stdout=None, stderr=None, check=False, text=True, capture_output=False)
subprocess_run_helper (func, *args, timeout, extra_env=None)
_check_for_pgf (texsystem)
_has_tex_package (package)
ipython_in_subprocess (requested_backend_or_gui_framework, all_expected_backends)
is_ci_environment ()
Variables
_log = logging.getLogger(__name__)
Detailed Description
Helper functions for testing.
Function Documentation
_check_for_pgf()
matplotlib.testing._check_for_pgf (texsystem) protected
Check if a given TeX system + pgf is available
Parameters
----------
texsystem : str
    The executable name to check
Definition at line 146 of file __init__.py.
References subprocess_run_for_testing().
_has_tex_package()
matplotlib.testing._has_tex_package (package) protected
Definition at line 174 of file __init__.py.
ipython_in_subprocess()
matplotlib.testing.ipython_in_subprocess (requested_backend_or_gui_framework, all_expected_backends)
Definition at line 182 of file __init__.py.
is_ci_environment()
matplotlib.testing.is_ci_environment ()
Definition at line 216 of file __init__.py.
set_font_settings_for_testing()
matplotlib.testing.set_font_settings_for_testing ()
Definition at line 18 of file __init__.py.
set_reproducibility_for_testing()
matplotlib.testing.set_reproducibility_for_testing ()
Definition at line 24 of file __init__.py.
setup()
matplotlib.testing.setup ()
Definition at line 28 of file __init__.py.
subprocess_run_for_testing()
matplotlib.testing.subprocess_run_for_testing (command, env = None, timeout = 60, stdout = None, stderr = None, check = False, text = True, capture_output = False)
Create and run a subprocess.
Thin wrapper around `subprocess.run`, intended for testing.  Will
mark fork() failures on Cygwin as expected failures: not a
success, but not indicating a problem with the code either.
Parameters
----------
args : list of str
env : dict[str, str]
timeout : float
stdout, stderr
check : bool
text : bool
    Also called ``universal_newlines`` in subprocess.  I chose this
    name since the main effect is returning bytes (`False`) vs. str
    (`True`), though it also tries to normalize newlines across
    platforms.
capture_output : bool
    Set stdout and stderr to subprocess.PIPE
Returns
-------
proc : subprocess.Popen
See Also
--------
subprocess.run
Raises
------
pytest.xfail
    If platform is Cygwin and subprocess reports a fork() failure.
Definition at line 53 of file __init__.py.
Referenced by _check_for_pgf(), and subprocess_run_helper().
subprocess_run_helper()
matplotlib.testing.subprocess_run_helper (func, * args, timeout, extra_env = None)
Run a function in a sub-process.
Parameters
----------
func : function
    The function to be run.  It must be in a module that is importable.
*args : str
    Any additional command line arguments to be passed in
    the first argument to ``subprocess.run``.
extra_env : dict[str, str]
    Any additional environment variables to be set for the subprocess.
Definition at line 109 of file __init__.py.
References subprocess_run_for_testing().
Variable Documentation
_log
matplotlib.testing._log = logging.getLogger(__name__) protected
Definition at line 15 of file __init__.py.