Code Cloning Analysis: matplotlib.backends.backend_pgf.LatexError Class Reference
matplotlib.backends.backend_pgf.LatexError Class Reference
Public Member Functions
__init__ (self, message, latex_output="")
__str__ (self)
Public Attributes
latex_output = latex_output
Detailed Description
Definition at line 186 of file backend_pgf.py.
Constructor & Destructor Documentation
__init__()
matplotlib.backends.backend_pgf.LatexError.__init__ (self, message, latex_output = "")
Definition at line 187 of file backend_pgf.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__str__()
matplotlib.backends.backend_pgf.LatexError.__str__ (self)
Definition at line 191 of file backend_pgf.py.
Referenced by numpy.polynomial._polybase.ABCPolyBase._get_coefficients().
Member Data Documentation
latex_output
matplotlib.backends.backend_pgf.LatexError.latex_output = latex_output
Definition at line 189 of file backend_pgf.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/backends/backend_pgf.py