Code Cloning Analysis: matplotlib.projections.geo.GeoAxes.ThetaFormatter Class Reference
matplotlib.projections.geo.GeoAxes.ThetaFormatter Class Reference
Public Member Functions
__init__ (self, round_to=1.0)
__call__ (self, x, pos=None)
Public Member Functions inherited from matplotlib.ticker.Formatter
__call__ (self, x, pos=None)
format_ticks (self, values)
format_data (self, value)
format_data_short (self, value)
get_offset (self)
set_locs (self, locs)
Public Member Functions inherited from matplotlib.ticker.TickHelper
set_axis (self, axis)
create_dummy_axis (self, **kwargs)
Protected Attributes
_round_to = round_to
Additional Inherited Members
Static Public Member Functions inherited from matplotlib.ticker.Formatter
fix_minus (s)
Static Public Attributes inherited from matplotlib.ticker.Formatter
list locs = []
Static Public Attributes inherited from matplotlib.ticker.TickHelper
axis = None
Protected Member Functions inherited from matplotlib.ticker.Formatter
_set_locator (self, locator)
Detailed Description
Used to format the theta tick labels.  Converts the native
unit of radians into degrees and adds a degree symbol.
Definition at line 18 of file geo.py.
Constructor & Destructor Documentation
__init__()
matplotlib.projections.geo.GeoAxes.ThetaFormatter.__init__ (self, round_to = 1.0)
Definition at line 23 of file geo.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__call__()
matplotlib.projections.geo.GeoAxes.ThetaFormatter.__call__ (self, x, pos = None)
Definition at line 26 of file geo.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), scipy.interpolate._fitpack2.SphereBivariateSpline.ev(), matplotlib.ticker.Formatter.format_data(), and matplotlib.ticker.LogFormatter.format_data().
Member Data Documentation
_round_to
matplotlib.projections.geo.GeoAxes.ThetaFormatter._round_to = round_to protected
Definition at line 24 of file geo.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/projections/geo.py