Code Cloning Analysis: sklearn.base.TransformerMixin Class Reference
sklearn.base.TransformerMixin Class Reference
Inherits sklearn.utils._set_output._SetOutputMixin.
Inherited by sklearn.cluster._birch.Birch, sklearn.cluster._feature_agglomeration.AgglomerationTransform, sklearn.cluster._kmeans._BaseKMeans, sklearn.compose._column_transformer.ColumnTransformer, sklearn.compose.tests.test_column_transformer.Trans, sklearn.compose.tests.test_target.DummyCheckerArrayTransformer, sklearn.compose.tests.test_target.DummyTransformer, sklearn.cross_decomposition._pls.PLSSVD, sklearn.cross_decomposition._pls._PLS, sklearn.decomposition._base._BasePCA, sklearn.decomposition._dict_learning._BaseSparseCoding, sklearn.decomposition._factor_analysis.FactorAnalysis, sklearn.decomposition._fastica.FastICA, sklearn.decomposition._kernel_pca.KernelPCA, sklearn.decomposition._lda.LatentDirichletAllocation, sklearn.decomposition._nmf._BaseNMF, sklearn.decomposition._sparse_pca._BaseSparsePCA, sklearn.decomposition._truncated_svd.TruncatedSVD, sklearn.discriminant_analysis.LinearDiscriminantAnalysis, sklearn.ensemble._forest.RandomTreesEmbedding, sklearn.ensemble._hist_gradient_boosting.binning._BinMapper, sklearn.ensemble._stacking._BaseStacking, sklearn.ensemble._voting._BaseVoting, sklearn.feature_extraction._dict_vectorizer.DictVectorizer, sklearn.feature_extraction._hash.FeatureHasher, sklearn.feature_extraction.image.PatchExtractor, sklearn.feature_extraction.text.HashingVectorizer, sklearn.feature_extraction.text.TfidfTransformer, sklearn.feature_selection._base.SelectorMixin, sklearn.impute._base.MissingIndicator, sklearn.impute._base._BaseImputer, sklearn.isotonic.IsotonicRegression, sklearn.kernel_approximation.AdditiveChi2Sampler, sklearn.kernel_approximation.Nystroem, sklearn.kernel_approximation.PolynomialCountSketch, sklearn.kernel_approximation.RBFSampler, sklearn.kernel_approximation.SkewedChi2Sampler, sklearn.manifold._isomap.Isomap, sklearn.manifold._locally_linear.LocallyLinearEmbedding, sklearn.manifold._t_sne.TSNE, sklearn.neighbors._graph.KNeighborsTransformer, sklearn.neighbors._graph.RadiusNeighborsTransformer, sklearn.neighbors._nca.NeighborhoodComponentsAnalysis, sklearn.neural_network._rbm.BernoulliRBM, sklearn.pipeline.FeatureUnion, sklearn.preprocessing._data.Binarizer, sklearn.preprocessing._data.KernelCenterer, sklearn.preprocessing._data.MaxAbsScaler, sklearn.preprocessing._data.MinMaxScaler, sklearn.preprocessing._data.Normalizer, sklearn.preprocessing._data.PowerTransformer, sklearn.preprocessing._data.QuantileTransformer, sklearn.preprocessing._data.RobustScaler, sklearn.preprocessing._data.StandardScaler, sklearn.preprocessing._discretization.KBinsDiscretizer, sklearn.preprocessing._encoders._BaseEncoder, sklearn.preprocessing._function_transformer.FunctionTransformer, sklearn.preprocessing._label.LabelBinarizer, sklearn.preprocessing._label.LabelEncoder, sklearn.preprocessing._label.MultiLabelBinarizer, sklearn.preprocessing._polynomial.PolynomialFeatures, sklearn.preprocessing._polynomial.SplineTransformer, sklearn.random_projection.BaseRandomProjection, sklearn.tests.metadata_routing_common.ConsumingTransformer, sklearn.tests.metadata_routing_common.MetaTransformer, sklearn.tests.test_pipeline.Mult, sklearn.tests.test_pipeline.NoInvTransf, sklearn.utils.tests.test_estimator_checks.SparseTransformer, sklearn.utils.tests.test_pprint.StandardScaler, and sklearn.utils.tests.test_tags.EmptyTransformer.
Public Member Functions
__sklearn_tags__ (self)
fit_transform (self, X, y=None, **fit_params)
Public Member Functions inherited from sklearn.utils._set_output._SetOutputMixin
__init_subclass__ (cls, auto_wrap_output_keys=("transform",), **kwargs)
set_output (self, *, transform=None)
Additional Inherited Members
Protected Attributes inherited from sklearn.utils._set_output._SetOutputMixin
_sklearn_auto_wrap_output_keys = set()
dict _sklearn_output_config = {}
Detailed Description
Mixin class for all transformers in scikit-learn.
This mixin defines the following functionality:
- a `fit_transform` method that delegates to `fit` and `transform`;
- a `set_output` method to output `X` as a specific container type.
If :term:`get_feature_names_out` is defined, then :class:`BaseEstimator` will
automatically wrap `transform` and `fit_transform` to follow the `set_output`
API. See the :ref:`developer_api_set_output` for details.
:class:`OneToOneFeatureMixin` and
:class:`ClassNamePrefixFeaturesOutMixin` are helpful mixins for
defining :term:`get_feature_names_out`.
Examples
--------
>>> import numpy as np
>>> from sklearn.base import BaseEstimator, TransformerMixin
>>> class MyTransformer(TransformerMixin, BaseEstimator):
...     def __init__(self, *, param=1):
...         self.param = param
...     def fit(self, X, y=None):
...         return self
...     def transform(self, X):
...         return np.full(shape=len(X), fill_value=self.param)
>>> transformer = MyTransformer()
>>> X = [[1, 2], [2, 3], [3, 4]]
>>> transformer.fit_transform(X)
array([1, 1, 1])
Definition at line 801 of file base.py.
Member Function Documentation
__sklearn_tags__()
sklearn.base.TransformerMixin.__sklearn_tags__ (self)
Definition at line 834 of file base.py.
fit_transform()
sklearn.base.TransformerMixin.fit_transform (self, X, y = None, ** fit_params)
Fit to data, then transform it.
Fits transformer to `X` and `y` with optional parameters `fit_params`
and returns a transformed version of `X`.
Parameters
----------
X : array-like of shape (n_samples, n_features)
    Input samples.
y :  array-like of shape (n_samples,) or (n_samples, n_outputs), \
        default=None
    Target values (None for unsupervised transformations).
**fit_params : dict
    Additional fit parameters.
Returns
-------
X_new : ndarray array of shape (n_samples, n_features_new)
    Transformed array.
Reimplemented in sklearn.cluster._kmeans._BaseKMeans, sklearn.compose._column_transformer.ColumnTransformer, sklearn.cross_decomposition._pls._PLS, sklearn.cross_decomposition._pls.PLSSVD, sklearn.decomposition._dict_learning.DictionaryLearning, sklearn.decomposition._fastica.FastICA, sklearn.decomposition._kernel_pca.KernelPCA, sklearn.decomposition._lda.LatentDirichletAllocation, sklearn.decomposition._nmf.MiniBatchNMF, sklearn.decomposition._nmf.NMF, sklearn.decomposition._pca.PCA, sklearn.decomposition._truncated_svd.TruncatedSVD, sklearn.ensemble._forest.RandomTreesEmbedding, sklearn.ensemble._stacking.StackingRegressor, sklearn.ensemble._voting._BaseVoting, sklearn.feature_extraction._dict_vectorizer.DictVectorizer, sklearn.feature_extraction.text.HashingVectorizer, sklearn.impute._base.MissingIndicator, sklearn.impute._iterative.IterativeImputer, sklearn.manifold._isomap.Isomap, sklearn.manifold._locally_linear.LocallyLinearEmbedding, sklearn.manifold._t_sne.TSNE, sklearn.neighbors._graph.KNeighborsTransformer, sklearn.neighbors._graph.RadiusNeighborsTransformer, sklearn.pipeline.FeatureUnion, sklearn.preprocessing._data.PowerTransformer, sklearn.preprocessing._label.LabelBinarizer, sklearn.preprocessing._label.LabelEncoder, sklearn.preprocessing._label.MultiLabelBinarizer, sklearn.preprocessing._target_encoder.TargetEncoder, sklearn.tests.metadata_routing_common.ConsumingTransformer, and sklearn.utils.tests.test_estimator_checks.SparseTransformer.
Definition at line 839 of file base.py.
Referenced by sklearn.feature_selection.tests.test_base.StepSelector._get_support_mask(), sklearn.compose._column_transformer.ColumnTransformer.fit(), sklearn.decomposition._dict_learning.DictionaryLearning.fit(), sklearn.decomposition._nmf._BaseNMF.fit(), sklearn.decomposition._truncated_svd.TruncatedSVD.fit(), sklearn.ensemble._forest.RandomTreesEmbedding.fit(), sklearn.impute._iterative.IterativeImputer.fit(), sklearn.manifold._mds.MDS.fit(), sklearn.manifold._t_sne.TSNE.fit(), and sklearn.neighbors._nca.NeighborhoodComponentsAnalysis.fit().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/sklearn/base.py