Code Cloning Analysis: matplotlib._pylab_helpers.Gcf Class Reference
matplotlib._pylab_helpers.Gcf Class Reference
Public Member Functions
get_fig_manager (cls, num)
destroy (cls, num)
destroy_fig (cls, fig)
destroy_all (cls)
has_fignum (cls, num)
get_all_fig_managers (cls)
get_num_fig_managers (cls)
get_active (cls)
set_active (cls, manager)
draw_all (cls, force=False)
Static Public Attributes
figs = OrderedDict()
Protected Member Functions
_set_new_active_manager (cls, manager)
Detailed Description
Singleton to maintain the relation between figures and their managers, and
keep track of and "active" figure and manager.
The canvas of a figure created through pyplot is associated with a figure
manager, which handles the interaction between the figure and the backend.
pyplot keeps track of figure managers using an identifier, the "figure
number" or "manager number" (which can actually be any hashable value);
this number is available as the :attr:`number` attribute of the manager.
This class is never instantiated; it consists of an `OrderedDict` mapping
figure/manager numbers to managers, and a set of class methods that
manipulate this `OrderedDict`.
Attributes
----------
figs : OrderedDict
    `OrderedDict` mapping numbers to managers; the active manager is at the
    end.
Definition at line 9 of file _pylab_helpers.py.
Member Function Documentation
_set_new_active_manager()
matplotlib._pylab_helpers.Gcf._set_new_active_manager (cls, manager) protected
Adopt *manager* into pyplot and make it the active manager.
Definition at line 105 of file _pylab_helpers.py.
References set_active().
destroy()
matplotlib._pylab_helpers.Gcf.destroy (cls, num)
Destroy manager *num* -- either a manager instance or a manager number.
In the interactive backends, this is bound to the window "destroy" and
"delete" events.
It is recommended to pass a manager instance, to avoid confusion when
two managers share the same number.
Definition at line 45 of file _pylab_helpers.py.
References figs.
Referenced by destroy_fig().
destroy_all()
matplotlib._pylab_helpers.Gcf.destroy_all (cls)
Destroy all figures.
Definition at line 77 of file _pylab_helpers.py.
References figs.
destroy_fig()
matplotlib._pylab_helpers.Gcf.destroy_fig (cls, fig)
Destroy figure *fig*.
Definition at line 69 of file _pylab_helpers.py.
References destroy(), and figs.
draw_all()
matplotlib._pylab_helpers.Gcf.draw_all (cls, force = False)
Redraw all stale managed figures, or, if *force* is True, all managed
figures.
Definition at line 124 of file _pylab_helpers.py.
References get_all_fig_managers().
get_active()
matplotlib._pylab_helpers.Gcf.get_active (cls)
Return the active manager, or *None* if there is no manager.
Definition at line 100 of file _pylab_helpers.py.
References figs.
get_all_fig_managers()
matplotlib._pylab_helpers.Gcf.get_all_fig_managers (cls)
Return a list of figure managers.
Definition at line 90 of file _pylab_helpers.py.
References figs.
Referenced by draw_all().
get_fig_manager()
matplotlib._pylab_helpers.Gcf.get_fig_manager (cls, num)
If manager number *num* exists, make it the active one and return it;
otherwise return *None*.
Definition at line 34 of file _pylab_helpers.py.
References figs, and set_active().
get_num_fig_managers()
matplotlib._pylab_helpers.Gcf.get_num_fig_managers (cls)
Return the number of figures being managed.
Definition at line 95 of file _pylab_helpers.py.
References figs.
has_fignum()
matplotlib._pylab_helpers.Gcf.has_fignum (cls, num)
Return whether figure number *num* exists.
Definition at line 85 of file _pylab_helpers.py.
References figs.
set_active()
matplotlib._pylab_helpers.Gcf.set_active (cls, manager)
Make *manager* the active manager.
Definition at line 118 of file _pylab_helpers.py.
References figs.
Referenced by matplotlib.widgets.CheckButtons._clear(), matplotlib.widgets.RadioButtons._clear(), _set_new_active_manager(), matplotlib.widgets.RadioButtons.clear(), and get_fig_manager().
Member Data Documentation
figs
matplotlib._pylab_helpers.Gcf.figs = OrderedDict() static
Definition at line 31 of file _pylab_helpers.py.
Referenced by destroy(), destroy_all(), destroy_fig(), get_active(), get_all_fig_managers(), get_fig_manager(), get_num_fig_managers(), has_fignum(), and set_active().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/_pylab_helpers.py