Code Cloning Analysis: pandas.core.accessor.DirNamesMixin Class Reference
pandas.core.accessor.DirNamesMixin Class Reference
Public Member Functions
list[str] __dir__ (self)
Protected Member Functions
set[str] _dir_deletions (self)
set[str] _dir_additions (self)
Static Protected Attributes
set _accessors = set()
frozenset _hidden_attrs = frozenset()
Detailed Description
Definition at line 19 of file accessor.py.
Member Function Documentation
__dir__()
list[str] pandas.core.accessor.DirNamesMixin.__dir__ (self)
Provide method name lookup and completion.
Notes
-----
Only provide 'public' methods.
Definition at line 36 of file accessor.py.
References __dir__(), _dir_additions(), and _dir_deletions().
Referenced by __dir__().
_dir_additions()
set[str] pandas.core.accessor.DirNamesMixin._dir_additions (self) protected
Add additional __dir__ for this object.
Reimplemented in pandas.core.generic.NDFrame, and pandas.core.groupby.groupby.BaseGroupBy.
Definition at line 30 of file accessor.py.
References _accessors.
Referenced by __dir__().
_dir_deletions()
set[str] pandas.core.accessor.DirNamesMixin._dir_deletions (self) protected
Delete unwanted __dir__ for this object.
Definition at line 24 of file accessor.py.
References _accessors, and _hidden_attrs.
Referenced by __dir__().
Member Data Documentation
_accessors
set pandas.core.accessor.DirNamesMixin._accessors = set() static protected
Definition at line 20 of file accessor.py.
Referenced by pandas.core.generic.NDFrame.__getattr__(), _dir_additions(), and _dir_deletions().
_hidden_attrs
frozenset pandas.core.accessor.DirNamesMixin._hidden_attrs = frozenset() static protected
Definition at line 21 of file accessor.py.
Referenced by _dir_deletions().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/core/accessor.py