Code Cloning Analysis: matplotlib.tests.test_colors Namespace Reference
matplotlib.tests.test_colors Namespace Reference
Classes
class TestAsinhNorm
Functions
test_create_lookup_table (N, result)
test_index_dtype (dtype)
test_resampled ()
test_colormaps_get_cmap ()
test_double_register_builtin_cmap ()
test_colormap_copy ()
test_colormap_equals ()
test_colormap_endian ()
test_colormap_invalid ()
test_colormap_return_types ()
test_BoundaryNorm ()
test_CenteredNorm ()
test_lognorm_invalid (vmin, vmax)
test_LogNorm ()
test_LogNorm_inverse ()
test_PowerNorm ()
test_PowerNorm_translation_invariance ()
test_powernorm_cbar_limits ()
test_Normalize ()
test_FuncNorm ()
test_TwoSlopeNorm_autoscale ()
test_TwoSlopeNorm_autoscale_None_vmin ()
test_TwoSlopeNorm_autoscale_None_vmax ()
test_TwoSlopeNorm_scale ()
test_TwoSlopeNorm_scaleout_center ()
test_TwoSlopeNorm_scaleout_center_max ()
test_TwoSlopeNorm_Even ()
test_TwoSlopeNorm_Odd ()
test_TwoSlopeNorm_VminEqualsVcenter ()
test_TwoSlopeNorm_VmaxEqualsVcenter ()
test_TwoSlopeNorm_VminGTVcenter ()
test_TwoSlopeNorm_TwoSlopeNorm_VminGTVmax ()
test_TwoSlopeNorm_VcenterGTVmax ()
test_TwoSlopeNorm_premature_scaling ()
test_SymLogNorm ()
test_SymLogNorm_colorbar ()
test_SymLogNorm_single_zero ()
_inverse_tester (norm_instance, vals)
_scalar_tester (norm_instance, vals)
_mask_tester (norm_instance, vals)
test_cmap_and_norm_from_levels_and_colors ()
test_boundarynorm_and_colorbarbase ()
test_cmap_and_norm_from_levels_and_colors2 ()
test_rgb_hsv_round_trip ()
test_autoscale_masked ()
test_light_source_topo_surface ()
test_light_source_shading_default ()
test_light_source_shading_empty_mask ()
test_light_source_masked_shading ()
test_light_source_hillshading ()
test_light_source_planar_hillshading ()
test_color_names ()
_sph2cart (theta, phi)
_azimuth2math (azimuth, elevation)
test_pandas_iterable (pd)
test_colormap_reversing (name)
test_has_alpha_channel ()
test_cn ()
test_conversions ()
test_conversions_masked ()
test_to_rgba_array_single_str ()
test_to_rgba_array_2tuple_str ()
test_to_rgba_array_alpha_array ()
test_to_rgba_array_accepts_color_alpha_tuple ()
test_to_rgba_array_explicit_alpha_overrides_tuple_alpha ()
test_to_rgba_array_accepts_color_alpha_tuple_with_multiple_colors ()
test_to_rgba_array_error_with_color_invalid_alpha_tuple ()
test_to_rgba_accepts_color_alpha_tuple (rgba_alpha)
test_to_rgba_explicit_alpha_overrides_tuple_alpha ()
test_to_rgba_error_with_color_invalid_alpha_tuple ()
test_scalarmappable_to_rgba (bytes)
test_scalarmappable_nan_to_rgba (bytes)
test_failed_conversions ()
test_grey_gray ()
test_tableau_order ()
test_ndarray_subclass_norm ()
test_same_color ()
test_hex_shorthand_notation ()
test_repr_png ()
test_repr_html ()
test_get_under_over_bad ()
test_non_mutable_get_values (kind)
test_colormap_alpha_array ()
test_colormap_bad_data_with_alpha ()
test_2d_to_rgba ()
test_set_dict_to_rgba ()
test_norm_deepcopy ()
test_set_clim_emits_single_callback ()
test_norm_callback ()
test_scalarmappable_norm_update ()
test_norm_update_figs (fig_test, fig_ref)
test_make_norm_from_scale_name ()
test_color_sequences ()
test_cm_set_cmap_error ()
test_set_cmap_mismatched_name ()
test_cmap_alias_names ()
test_to_rgba_array_none_color_with_alpha_param ()
test_is_color_like (input, expected)
test_colorizer_vmin_vmax ()
Function Documentation
_azimuth2math()
matplotlib.tests.test_colors._azimuth2math (azimuth, elevation) protected
Convert from clockwise-from-north and up-from-horizontal to mathematical
conventions.
Definition at line 1146 of file test_colors.py.
Referenced by test_light_source_hillshading(), and test_light_source_planar_hillshading().
_inverse_tester()
matplotlib.tests.test_colors._inverse_tester (norm_instance, vals) protected
Checks if the inverse of the given normalization is working.
Definition at line 764 of file test_colors.py.
Referenced by test_LogNorm_inverse(), and test_SymLogNorm().
_mask_tester()
matplotlib.tests.test_colors._mask_tester (norm_instance, vals) protected
Checks mask handling
Definition at line 780 of file test_colors.py.
Referenced by test_LogNorm_inverse(), and test_SymLogNorm().
_scalar_tester()
matplotlib.tests.test_colors._scalar_tester (norm_instance, vals) protected
Checks if scalars and arrays are handled the same way.
Tests only for float.
Definition at line 771 of file test_colors.py.
Referenced by test_LogNorm_inverse(), and test_SymLogNorm().
_sph2cart()
matplotlib.tests.test_colors._sph2cart (theta, phi) protected
Definition at line 1139 of file test_colors.py.
test_2d_to_rgba()
matplotlib.tests.test_colors.test_2d_to_rgba ()
Definition at line 1524 of file test_colors.py.
test_autoscale_masked()
matplotlib.tests.test_colors.test_autoscale_masked ()
Definition at line 909 of file test_colors.py.
test_BoundaryNorm()
matplotlib.tests.test_colors.test_BoundaryNorm ()
GitHub issue #1258: interpolation was failing with numpy
1.7 pre-release.
Definition at line 218 of file test_colors.py.
test_boundarynorm_and_colorbarbase()
matplotlib.tests.test_colors.test_boundarynorm_and_colorbarbase ()
Definition at line 810 of file test_colors.py.
test_CenteredNorm()
matplotlib.tests.test_colors.test_CenteredNorm ()
Definition at line 388 of file test_colors.py.
test_cm_set_cmap_error()
matplotlib.tests.test_colors.test_cm_set_cmap_error ()
Definition at line 1690 of file test_colors.py.
test_cmap_alias_names()
matplotlib.tests.test_colors.test_cmap_alias_names ()
Definition at line 1710 of file test_colors.py.
test_cmap_and_norm_from_levels_and_colors()
matplotlib.tests.test_colors.test_cmap_and_norm_from_levels_and_colors ()
Definition at line 790 of file test_colors.py.
test_cmap_and_norm_from_levels_and_colors2()
matplotlib.tests.test_colors.test_cmap_and_norm_from_levels_and_colors2 ()
Definition at line 839 of file test_colors.py.
test_cn()
matplotlib.tests.test_colors.test_cn ()
Definition at line 1194 of file test_colors.py.
test_color_names()
matplotlib.tests.test_colors.test_color_names ()
Definition at line 1133 of file test_colors.py.
test_color_sequences()
matplotlib.tests.test_colors.test_color_sequences ()
Definition at line 1650 of file test_colors.py.
test_colorizer_vmin_vmax()
matplotlib.tests.test_colors.test_colorizer_vmin_vmax ()
Definition at line 1738 of file test_colors.py.
test_colormap_alpha_array()
matplotlib.tests.test_colors.test_colormap_alpha_array ()
Definition at line 1498 of file test_colors.py.
test_colormap_bad_data_with_alpha()
matplotlib.tests.test_colors.test_colormap_bad_data_with_alpha ()
Definition at line 1510 of file test_colors.py.
test_colormap_copy()
matplotlib.tests.test_colors.test_colormap_copy ()
Definition at line 104 of file test_colors.py.
test_colormap_endian()
matplotlib.tests.test_colors.test_colormap_endian ()
GitHub issue #1005: a bug in putmask caused erroneous
mapping of 1.0 when input from a non-native-byteorder
array.
Definition at line 149 of file test_colors.py.
test_colormap_equals()
matplotlib.tests.test_colors.test_colormap_equals ()
Definition at line 126 of file test_colors.py.
test_colormap_invalid()
matplotlib.tests.test_colors.test_colormap_invalid ()
GitHub issue #9892: Handling of nan's were getting mapped to under
rather than bad. This tests to make sure all invalid values
(-inf, nan, inf) are mapped respectively to (under, bad, over).
Definition at line 164 of file test_colors.py.
test_colormap_return_types()
matplotlib.tests.test_colors.test_colormap_return_types ()
Make sure that tuples are returned for scalar input and
that the proper shapes are returned for ndarrays.
Definition at line 198 of file test_colors.py.
test_colormap_reversing()
matplotlib.tests.test_colors.test_colormap_reversing (name)
Check the generated _lut data of a colormap and corresponding reversed
colormap if they are almost the same.
Definition at line 1168 of file test_colors.py.
test_colormaps_get_cmap()
matplotlib.tests.test_colors.test_colormaps_get_cmap ()
Definition at line 77 of file test_colors.py.
test_conversions()
matplotlib.tests.test_colors.test_conversions ()
Definition at line 1216 of file test_colors.py.
test_conversions_masked()
matplotlib.tests.test_colors.test_conversions_masked ()
Definition at line 1235 of file test_colors.py.
test_create_lookup_table()
matplotlib.tests.test_colors.test_create_lookup_table (N, result)
Definition at line 31 of file test_colors.py.
test_double_register_builtin_cmap()
matplotlib.tests.test_colors.test_double_register_builtin_cmap ()
Definition at line 97 of file test_colors.py.
test_failed_conversions()
matplotlib.tests.test_colors.test_failed_conversions ()
Definition at line 1383 of file test_colors.py.
test_FuncNorm()
matplotlib.tests.test_colors.test_FuncNorm ()
Definition at line 575 of file test_colors.py.
test_get_under_over_bad()
matplotlib.tests.test_colors.test_get_under_over_bad ()
Definition at line 1481 of file test_colors.py.
test_grey_gray()
matplotlib.tests.test_colors.test_grey_gray ()
Definition at line 1397 of file test_colors.py.
test_has_alpha_channel()
matplotlib.tests.test_colors.test_has_alpha_channel ()
Definition at line 1185 of file test_colors.py.
test_hex_shorthand_notation()
matplotlib.tests.test_colors.test_hex_shorthand_notation ()
Definition at line 1452 of file test_colors.py.
test_index_dtype()
matplotlib.tests.test_colors.test_index_dtype (dtype)
Definition at line 37 of file test_colors.py.
test_is_color_like()
matplotlib.tests.test_colors.test_is_color_like (input, expected)
Definition at line 1734 of file test_colors.py.
test_light_source_hillshading()
matplotlib.tests.test_colors.test_light_source_hillshading ()
Compare the current hillshading method against one that should be
mathematically equivalent. Illuminates a cone from a range of angles.
Definition at line 1065 of file test_colors.py.
References _azimuth2math().
test_light_source_masked_shading()
matplotlib.tests.test_colors.test_light_source_masked_shading ()
Array comparison test for a surface with a masked portion. Ensures that
we don't wind up with "fringes" of odd colors around masked regions.
Definition at line 1009 of file test_colors.py.
test_light_source_planar_hillshading()
matplotlib.tests.test_colors.test_light_source_planar_hillshading ()
Ensure that the illumination intensity is correct for planar surfaces.
Definition at line 1096 of file test_colors.py.
References _azimuth2math().
test_light_source_shading_default()
matplotlib.tests.test_colors.test_light_source_shading_default ()
Array comparison test for the default "hsv" blend mode. Ensure the
default result doesn't change without warning.
Definition at line 939 of file test_colors.py.
test_light_source_shading_empty_mask()
matplotlib.tests.test_colors.test_light_source_shading_empty_mask ()
Definition at line 993 of file test_colors.py.
test_light_source_topo_surface()
matplotlib.tests.test_colors.test_light_source_topo_surface ()
Shades a DEM using different v.e.'s and blend modes.
Definition at line 917 of file test_colors.py.
test_LogNorm()
matplotlib.tests.test_colors.test_LogNorm ()
LogNorm ignored clip, now it has the same
behavior as Normalize, e.g., values > vmax are bigger than 1
without clip, with clip they are 1.
Definition at line 468 of file test_colors.py.
test_lognorm_invalid()
matplotlib.tests.test_colors.test_lognorm_invalid (vmin, vmax)
Definition at line 459 of file test_colors.py.
test_LogNorm_inverse()
matplotlib.tests.test_colors.test_LogNorm_inverse ()
Test that lists work, and that the inverse works
Definition at line 478 of file test_colors.py.
References _inverse_tester(), _mask_tester(), and _scalar_tester().
test_make_norm_from_scale_name()
matplotlib.tests.test_colors.test_make_norm_from_scale_name ()
Definition at line 1644 of file test_colors.py.
test_ndarray_subclass_norm()
matplotlib.tests.test_colors.test_ndarray_subclass_norm ()
Definition at line 1414 of file test_colors.py.
test_non_mutable_get_values()
matplotlib.tests.test_colors.test_non_mutable_get_values (kind)
Definition at line 1489 of file test_colors.py.
test_norm_callback()
matplotlib.tests.test_colors.test_norm_callback ()
Definition at line 1573 of file test_colors.py.
test_norm_deepcopy()
matplotlib.tests.test_colors.test_norm_deepcopy ()
Definition at line 1543 of file test_colors.py.
test_norm_update_figs()
matplotlib.tests.test_colors.test_norm_update_figs (fig_test, fig_ref)
Definition at line 1628 of file test_colors.py.
test_Normalize()
matplotlib.tests.test_colors.test_Normalize ()
Definition at line 548 of file test_colors.py.
test_pandas_iterable()
matplotlib.tests.test_colors.test_pandas_iterable (pd)
Definition at line 1156 of file test_colors.py.
test_PowerNorm()
matplotlib.tests.test_colors.test_PowerNorm ()
Definition at line 489 of file test_colors.py.
test_powernorm_cbar_limits()
matplotlib.tests.test_colors.test_powernorm_cbar_limits ()
Definition at line 539 of file test_colors.py.
test_PowerNorm_translation_invariance()
matplotlib.tests.test_colors.test_PowerNorm_translation_invariance ()
Definition at line 530 of file test_colors.py.
test_repr_html()
matplotlib.tests.test_colors.test_repr_html ()
Definition at line 1470 of file test_colors.py.
test_repr_png()
matplotlib.tests.test_colors.test_repr_png ()
Definition at line 1457 of file test_colors.py.
test_resampled()
matplotlib.tests.test_colors.test_resampled ()
GitHub issue #6025 pointed to incorrect ListedColormap.resampled;
here we test the method for LinearSegmentedColormap as well.
Definition at line 43 of file test_colors.py.
test_rgb_hsv_round_trip()
matplotlib.tests.test_colors.test_rgb_hsv_round_trip ()
Definition at line 899 of file test_colors.py.
test_same_color()
matplotlib.tests.test_colors.test_same_color ()
Definition at line 1440 of file test_colors.py.
test_scalarmappable_nan_to_rgba()
matplotlib.tests.test_colors.test_scalarmappable_nan_to_rgba (bytes)
Definition at line 1358 of file test_colors.py.
test_scalarmappable_norm_update()
matplotlib.tests.test_colors.test_scalarmappable_norm_update ()
Definition at line 1598 of file test_colors.py.
test_scalarmappable_to_rgba()
matplotlib.tests.test_colors.test_scalarmappable_to_rgba (bytes)
Definition at line 1316 of file test_colors.py.
test_set_clim_emits_single_callback()
matplotlib.tests.test_colors.test_set_clim_emits_single_callback ()
Definition at line 1556 of file test_colors.py.
test_set_cmap_mismatched_name()
matplotlib.tests.test_colors.test_set_cmap_mismatched_name ()
Definition at line 1698 of file test_colors.py.
test_set_dict_to_rgba()
matplotlib.tests.test_colors.test_set_dict_to_rgba ()
Definition at line 1531 of file test_colors.py.
test_SymLogNorm()
matplotlib.tests.test_colors.test_SymLogNorm ()
Test SymLogNorm behavior
Definition at line 687 of file test_colors.py.
References _inverse_tester(), _mask_tester(), and _scalar_tester().
test_SymLogNorm_colorbar()
matplotlib.tests.test_colors.test_SymLogNorm_colorbar ()
Test un-called SymLogNorm in a colorbar.
Definition at line 720 of file test_colors.py.
test_SymLogNorm_single_zero()
matplotlib.tests.test_colors.test_SymLogNorm_single_zero ()
Test SymLogNorm to ensure it is not adding sub-ticks to zero label
Definition at line 730 of file test_colors.py.
test_tableau_order()
matplotlib.tests.test_colors.test_tableau_order ()
Definition at line 1406 of file test_colors.py.
test_to_rgba_accepts_color_alpha_tuple()
matplotlib.tests.test_colors.test_to_rgba_accepts_color_alpha_tuple (rgba_alpha)
Definition at line 1302 of file test_colors.py.
test_to_rgba_array_2tuple_str()
matplotlib.tests.test_colors.test_to_rgba_array_2tuple_str ()
Definition at line 1255 of file test_colors.py.
test_to_rgba_array_accepts_color_alpha_tuple()
matplotlib.tests.test_colors.test_to_rgba_array_accepts_color_alpha_tuple ()
Definition at line 1270 of file test_colors.py.
test_to_rgba_array_accepts_color_alpha_tuple_with_multiple_colors()
matplotlib.tests.test_colors.test_to_rgba_array_accepts_color_alpha_tuple_with_multiple_colors ()
Definition at line 1282 of file test_colors.py.
test_to_rgba_array_alpha_array()
matplotlib.tests.test_colors.test_to_rgba_array_alpha_array ()
Definition at line 1260 of file test_colors.py.
test_to_rgba_array_error_with_color_invalid_alpha_tuple()
matplotlib.tests.test_colors.test_to_rgba_array_error_with_color_invalid_alpha_tuple ()
Definition at line 1294 of file test_colors.py.
test_to_rgba_array_explicit_alpha_overrides_tuple_alpha()
matplotlib.tests.test_colors.test_to_rgba_array_explicit_alpha_overrides_tuple_alpha ()
Definition at line 1276 of file test_colors.py.
test_to_rgba_array_none_color_with_alpha_param()
matplotlib.tests.test_colors.test_to_rgba_array_none_color_with_alpha_param ()
Definition at line 1715 of file test_colors.py.
test_to_rgba_array_single_str()
matplotlib.tests.test_colors.test_to_rgba_array_single_str ()
Definition at line 1245 of file test_colors.py.
test_to_rgba_error_with_color_invalid_alpha_tuple()
matplotlib.tests.test_colors.test_to_rgba_error_with_color_invalid_alpha_tuple ()
Definition at line 1310 of file test_colors.py.
test_to_rgba_explicit_alpha_overrides_tuple_alpha()
matplotlib.tests.test_colors.test_to_rgba_explicit_alpha_overrides_tuple_alpha ()
Definition at line 1306 of file test_colors.py.
test_TwoSlopeNorm_autoscale()
matplotlib.tests.test_colors.test_TwoSlopeNorm_autoscale ()
Definition at line 598 of file test_colors.py.
test_TwoSlopeNorm_autoscale_None_vmax()
matplotlib.tests.test_colors.test_TwoSlopeNorm_autoscale_None_vmax ()
Definition at line 612 of file test_colors.py.
test_TwoSlopeNorm_autoscale_None_vmin()
matplotlib.tests.test_colors.test_TwoSlopeNorm_autoscale_None_vmin ()
Definition at line 605 of file test_colors.py.
test_TwoSlopeNorm_Even()
matplotlib.tests.test_colors.test_TwoSlopeNorm_Even ()
Definition at line 642 of file test_colors.py.
test_TwoSlopeNorm_Odd()
matplotlib.tests.test_colors.test_TwoSlopeNorm_Odd ()
Definition at line 649 of file test_colors.py.
test_TwoSlopeNorm_premature_scaling()
matplotlib.tests.test_colors.test_TwoSlopeNorm_premature_scaling ()
Definition at line 681 of file test_colors.py.
test_TwoSlopeNorm_scale()
matplotlib.tests.test_colors.test_TwoSlopeNorm_scale ()
Definition at line 619 of file test_colors.py.
test_TwoSlopeNorm_scaleout_center()
matplotlib.tests.test_colors.test_TwoSlopeNorm_scaleout_center ()
Definition at line 626 of file test_colors.py.
test_TwoSlopeNorm_scaleout_center_max()
matplotlib.tests.test_colors.test_TwoSlopeNorm_scaleout_center_max ()
Definition at line 634 of file test_colors.py.
test_TwoSlopeNorm_TwoSlopeNorm_VminGTVmax()
matplotlib.tests.test_colors.test_TwoSlopeNorm_TwoSlopeNorm_VminGTVmax ()
Definition at line 671 of file test_colors.py.
test_TwoSlopeNorm_VcenterGTVmax()
matplotlib.tests.test_colors.test_TwoSlopeNorm_VcenterGTVmax ()
Definition at line 676 of file test_colors.py.
test_TwoSlopeNorm_VmaxEqualsVcenter()
matplotlib.tests.test_colors.test_TwoSlopeNorm_VmaxEqualsVcenter ()
Definition at line 661 of file test_colors.py.
test_TwoSlopeNorm_VminEqualsVcenter()
matplotlib.tests.test_colors.test_TwoSlopeNorm_VminEqualsVcenter ()
Definition at line 656 of file test_colors.py.
test_TwoSlopeNorm_VminGTVcenter()
matplotlib.tests.test_colors.test_TwoSlopeNorm_VminGTVcenter ()
Definition at line 666 of file test_colors.py.