Code Cloning Analysis: joblib.externals.loky.process_executor._ExceptionWithTraceback Class Reference
joblib.externals.loky.process_executor._ExceptionWithTraceback Class Reference
Public Member Functions
__init__ (self, exc)
__reduce__ (self)
Public Attributes
exc = exc
tb = tb
Detailed Description
Definition at line 242 of file process_executor.py.
Constructor & Destructor Documentation
__init__()
joblib.externals.loky.process_executor._ExceptionWithTraceback.__init__ (self, exc)
Definition at line 243 of file process_executor.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__reduce__()
joblib.externals.loky.process_executor._ExceptionWithTraceback.__reduce__ (self)
Definition at line 252 of file process_executor.py.
Member Data Documentation
exc
joblib.externals.loky.process_executor._ExceptionWithTraceback.exc = exc
Definition at line 249 of file process_executor.py.
tb
joblib.externals.loky.process_executor._ExceptionWithTraceback.tb = tb
Definition at line 250 of file process_executor.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py