Code Cloning Analysis: sklearn.linear_model._stochastic_gradient Namespace Reference
sklearn.linear_model._stochastic_gradient Namespace Reference
Classes
class _ValidationScoreCallback
class BaseSGD
class BaseSGDClassifier
class BaseSGDRegressor
class SGDClassifier
class SGDOneClassSVM
class SGDRegressor
Functions
_prepare_fit_binary (est, y, i, input_dtype, label_encode=True)
fit_binary (est, i, X, y, alpha, C, learning_rate, max_iter, pos_weight, neg_weight, sample_weight, validation_mask=None, random_state=None)
_get_plain_sgd_function (input_dtype)
Variables
dict LEARNING_RATE_TYPES
dict PENALTY_TYPES = {"none": 0, "l2": 2, "l1": 1, "elasticnet": 3}
float DEFAULT_EPSILON = 0.1
MAX_INT = np.iinfo(np.int32).max
Detailed Description
Classification, regression and One-Class SVM using Stochastic Gradient
Descent (SGD).
Function Documentation
_get_plain_sgd_function()
sklearn.linear_model._stochastic_gradient._get_plain_sgd_function (input_dtype) protected
Definition at line 506 of file _stochastic_gradient.py.
_prepare_fit_binary()
sklearn.linear_model._stochastic_gradient._prepare_fit_binary (est, y, i, input_dtype, label_encode = True) protected
Initialization for fit_binary.
Returns y, coef, intercept, average_coef, average_intercept.
Definition at line 333 of file _stochastic_gradient.py.
Referenced by fit_binary().
fit_binary()
sklearn.linear_model._stochastic_gradient.fit_binary (est, i, X, y, alpha, C, learning_rate, max_iter, pos_weight, neg_weight, sample_weight, validation_mask = None, random_state = None)
Fit a single binary classifier.
The i'th class is considered the "positive" class.
Parameters
----------
est : Estimator object
    The estimator to fit
i : int
    Index of the positive class
X : numpy array or sparse matrix of shape [n_samples,n_features]
    Training data
y : numpy array of shape [n_samples, ]
    Target values
alpha : float
    The regularization parameter
C : float
    Maximum step size for passive aggressive
learning_rate : str
    The learning rate. Accepted values are 'constant', 'optimal',
    'invscaling', 'pa1' and 'pa2'.
max_iter : int
    The maximum number of iterations (epochs)
pos_weight : float
    The weight of the positive class
neg_weight : float
    The weight of the negative class
sample_weight : numpy array of shape [n_samples, ]
    The weight of each sample
validation_mask : numpy array of shape [n_samples, ], default=None
    Precomputed validation mask in case _fit_binary is called in the
    context of a one-vs-rest reduction.
random_state : int, RandomState instance, default=None
    If int, random_state is the seed used by the random number generator;
    If RandomState instance, random_state is the random number generator;
    If None, the random number generator is the RandomState instance used
    by `np.random`.
Definition at line 370 of file _stochastic_gradient.py.
References _prepare_fit_binary().
Referenced by sklearn.linear_model._stochastic_gradient.BaseSGDClassifier._fit_binary().
Variable Documentation
DEFAULT_EPSILON
float sklearn.linear_model._stochastic_gradient.DEFAULT_EPSILON = 0.1
Definition at line 54 of file _stochastic_gradient.py.
LEARNING_RATE_TYPES
dict sklearn.linear_model._stochastic_gradient.LEARNING_RATE_TYPES
Initial value:
=  {
    "constant": 1,
    "optimal": 2,
    "invscaling": 3,
    "adaptive": 4,
    "pa1": 5,
    "pa2": 6,
}
Definition at line 43 of file _stochastic_gradient.py.
MAX_INT
sklearn.linear_model._stochastic_gradient.MAX_INT = np.iinfo(np.int32).max
Definition at line 57 of file _stochastic_gradient.py.
PENALTY_TYPES
dict sklearn.linear_model._stochastic_gradient.PENALTY_TYPES = {"none": 0, "l2": 2, "l1": 1, "elasticnet": 3}
Definition at line 52 of file _stochastic_gradient.py.