Code Cloning Analysis: numpy.tests.test_public_api Namespace Reference
numpy.tests.test_public_api Namespace Reference
Functions
check_dir (module, module_name=None)
test_numpy_namespace ()
test_import_lazy_import (name)
test_dir_testing ()
test_numpy_linalg ()
test_numpy_fft ()
test_NPY_NO_EXPORT ()
is_unexpected (name)
test_all_modules_are_expected ()
test_all_modules_are_expected_2 ()
test_api_importable ()
test_array_api_entry_point ()
test_moved_exceptions (name)
Variables
ctypes = None
list PUBLIC_MODULES
list PUBLIC_ALIASED_MODULES
list PRIVATE_BUT_PRESENT_MODULES
list SKIP_LIST
list SKIP_LIST_2
Function Documentation
check_dir()
numpy.tests.test_public_api.check_dir (module, module_name = None)
Returns a mapping of all objects with the wrong __module__ attribute.
Definition at line 20 of file test_public_api.py.
References check_dir().
Referenced by check_dir(), and test_dir_testing().
is_unexpected()
numpy.tests.test_public_api.is_unexpected (name)
Check if this needs to be considered.
Definition at line 305 of file test_public_api.py.
Referenced by test_all_modules_are_expected(), and test_all_modules_are_expected_2().
test_all_modules_are_expected()
numpy.tests.test_public_api.test_all_modules_are_expected ()
Test that we don't add anything that looks like a new public module by
accident.  Check is based on filenames.
Definition at line 344 of file test_public_api.py.
References is_unexpected().
test_all_modules_are_expected_2()
numpy.tests.test_public_api.test_all_modules_are_expected_2 ()
Method checking all objects. The pkgutil-based method in
`test_all_modules_are_expected` does not catch imports into a namespace,
only filenames.  So this test is more thorough, and checks this like:
    import .lib.scimath as emath
To check if something in a module is (effectively) public, one can check if
there's anything in that namespace that's a public function/object but is
not exposed in a higher-level namespace.  For example for a `numpy.lib`
submodule::
    mod = np.lib.mixins
    for obj in mod.__all__:
        if obj in np.__all__:
            continue
        elif obj in np.lib.__all__:
            continue
        else:
            print(obj)
Definition at line 391 of file test_public_api.py.
References is_unexpected().
test_api_importable()
numpy.tests.test_public_api.test_api_importable ()
Check that all submodules listed higher up in this file can be imported
Note that if a PRIVATE_BUT_PRESENT_MODULES entry goes missing, it may
simply need to be removed from the list (deprecation may or may not be
needed - apply common sense).
Definition at line 443 of file test_public_api.py.
test_array_api_entry_point()
numpy.tests.test_public_api.test_array_api_entry_point ()
Entry point for Array API implementation can be found with importlib and
returns the numpy.array_api namespace.
Definition at line 499 of file test_public_api.py.
test_dir_testing()
numpy.tests.test_public_api.test_dir_testing ()
Assert that output of dir has only one "testing/tester"
attribute without duplicate
Definition at line 88 of file test_public_api.py.
References check_dir().
test_import_lazy_import()
numpy.tests.test_public_api.test_import_lazy_import (name)
Make sure we can actually use the modules we lazy load.
While not exported as part of the public API, it was accessible.  With the
use of __getattr__ and __dir__, this isn't always true It can happen that
an infinite recursion may happen.
This is the only way I found that would force the failure to appear on the
badly implemented code.
We also test for the presence of the lazily imported modules in dir
Definition at line 67 of file test_public_api.py.
test_moved_exceptions()
numpy.tests.test_public_api.test_moved_exceptions (name)
Definition at line 543 of file test_public_api.py.
test_NPY_NO_EXPORT()
numpy.tests.test_public_api.test_NPY_NO_EXPORT ()
Definition at line 106 of file test_public_api.py.
test_numpy_fft()
numpy.tests.test_public_api.test_numpy_fft ()
Definition at line 99 of file test_public_api.py.
test_numpy_linalg()
numpy.tests.test_public_api.test_numpy_linalg ()
Definition at line 94 of file test_public_api.py.
test_numpy_namespace()
numpy.tests.test_public_api.test_numpy_namespace ()
Definition at line 33 of file test_public_api.py.
Variable Documentation
ctypes
numpy.tests.test_public_api.ctypes = None
Definition at line 17 of file test_public_api.py.
PRIVATE_BUT_PRESENT_MODULES
list numpy.tests.test_public_api.PRIVATE_BUT_PRESENT_MODULES
Definition at line 183 of file test_public_api.py.
PUBLIC_ALIASED_MODULES
list numpy.tests.test_public_api.PUBLIC_ALIASED_MODULES
Initial value:
=  [
    "numpy.char",
    "numpy.emath",
    "numpy.rec",
]
Definition at line 176 of file test_public_api.py.
PUBLIC_MODULES
list numpy.tests.test_public_api.PUBLIC_MODULES
Definition at line 126 of file test_public_api.py.
SKIP_LIST
list numpy.tests.test_public_api.SKIP_LIST
Initial value:
=  [
    "numpy.core.code_generators",
    "numpy.core.code_generators.genapi",
    "numpy.core.code_generators.generate_umath",
    "numpy.core.code_generators.ufunc_docstrings",
    "numpy.core.code_generators.generate_numpy_api",
    "numpy.core.code_generators.generate_ufunc_api",
    "numpy.core.code_generators.numpy_api",
    "numpy.core.code_generators.generate_umath_doc",
    "numpy.core.code_generators.verify_c_api_version",
    "numpy.core.cversions",
    "numpy.core.generate_numpy_api",
    "numpy.core.umath_tests",
]
Definition at line 324 of file test_public_api.py.
SKIP_LIST_2
list numpy.tests.test_public_api.SKIP_LIST_2
Initial value:
=  [
    'numpy.math',
    'numpy.doc.constants.re',
    'numpy.doc.constants.textwrap',
    'numpy.lib.emath',
    'numpy.lib.math',
    'numpy.matlib.char',
    'numpy.matlib.rec',
    'numpy.matlib.emath',
    'numpy.matlib.exceptions',
    'numpy.matlib.math',
    'numpy.matlib.linalg',
    'numpy.matlib.fft',
    'numpy.matlib.random',
    'numpy.matlib.ctypeslib',
    'numpy.matlib.ma',
]
Definition at line 366 of file test_public_api.py.