Code Cloning Analysis: pandas.plotting._matplotlib.converter Namespace Reference
pandas.plotting._matplotlib.converter Namespace Reference
Classes
class DatetimeConverter
class MilliSecondLocator
class PandasAutoDateFormatter
class PandasAutoDateLocator
class PeriodConverter
class TimeConverter
class TimeFormatter
class TimeSeries_DateFormatter
class TimeSeries_DateLocator
class TimeSeries_TimedeltaFormatter
Functions
get_pairs ()
F register_pandas_matplotlib_converters (F func)
Generator[None, None, None] pandas_converters ()
None register ()
None deregister ()
float _to_ordinalf (pydt.time tm)
time2num (d)
get_datevalue (date, freq)
datetime _from_ordinal (x, tzinfo|None tz=None)
tuple[int, int] _get_default_annual_spacing (nyears)
npt.NDArray[np.intp] _period_break (PeriodIndex dates, str period)
npt.NDArray[np.bool_] _period_break_mask (PeriodIndex dates, str period)
bool has_level_label (npt.NDArray[np.intp] label_flags, float vmin)
tuple[int, int, int] _get_periods_per_ymd (BaseOffset freq)
np.ndarray _daily_finder (float vmin, float vmax, BaseOffset freq)
np.ndarray _monthly_finder (float vmin, float vmax, BaseOffset freq)
np.ndarray _quarterly_finder (float vmin, float vmax, BaseOffset freq)
np.ndarray _annual_finder (float vmin, float vmax, BaseOffset freq)
get_finder (BaseOffset freq)
Variables
dict _mpl_units = {}
Function Documentation
_annual_finder()
np.ndarray pandas.plotting._matplotlib.converter._annual_finder (float vmin, float vmax, BaseOffset freq) protected
Definition at line 908 of file converter.py.
_daily_finder()
np.ndarray pandas.plotting._matplotlib.converter._daily_finder (float vmin, float vmax, BaseOffset freq) protected
Definition at line 588 of file converter.py.
_from_ordinal()
datetime pandas.plotting._matplotlib.converter._from_ordinal (x, tzinfo | None tz = None) protected
Definition at line 463 of file converter.py.
_get_default_annual_spacing()
tuple[int, int] pandas.plotting._matplotlib.converter._get_default_annual_spacing (nyears) protected
Returns a default spacing between consecutive ticks for annual data.
Definition at line 492 of file converter.py.
Referenced by has_level_label().
_get_periods_per_ymd()
tuple[int, int, int] pandas.plotting._matplotlib.converter._get_periods_per_ymd (BaseOffset freq) protected
Definition at line 551 of file converter.py.
_monthly_finder()
np.ndarray pandas.plotting._matplotlib.converter._monthly_finder (float vmin, float vmax, BaseOffset freq) protected
Definition at line 788 of file converter.py.
_period_break()
npt.NDArray[np.intp] pandas.plotting._matplotlib.converter._period_break (PeriodIndex dates, str period) protected
Returns the indices where the given period changes.
Parameters
----------
dates : PeriodIndex
    Array of intervals to monitor.
period : str
    Name of the period to monitor.
Definition at line 514 of file converter.py.
Referenced by has_level_label().
_period_break_mask()
npt.NDArray[np.bool_] pandas.plotting._matplotlib.converter._period_break_mask (PeriodIndex dates, str period) protected
Definition at line 529 of file converter.py.
_quarterly_finder()
np.ndarray pandas.plotting._matplotlib.converter._quarterly_finder (float vmin, float vmax, BaseOffset freq) protected
Definition at line 860 of file converter.py.
_to_ordinalf()
float pandas.plotting._matplotlib.converter._to_ordinalf (pydt.time tm) protected
Definition at line 147 of file converter.py.
deregister()
None pandas.plotting._matplotlib.converter.deregister ()
Definition at line 133 of file converter.py.
get_datevalue()
pandas.plotting._matplotlib.converter.get_datevalue (date, freq)
Definition at line 271 of file converter.py.
get_finder()
pandas.plotting._matplotlib.converter.get_finder (BaseOffset freq)
Definition at line 930 of file converter.py.
get_pairs()
pandas.plotting._matplotlib.converter.get_pairs ()
Definition at line 75 of file converter.py.
has_level_label()
bool pandas.plotting._matplotlib.converter.has_level_label (npt.NDArray[np.intp] label_flags, float vmin)
Returns true if the ``label_flags`` indicate there is at least one label
for this level.
if the minimum view limit is not an exact integer, then the first tick
label won't be shown, so we must adjust for that.
Definition at line 535 of file converter.py.
References _get_default_annual_spacing(), _period_break(), and has_level_label().
Referenced by has_level_label().
pandas_converters()
Generator[None, None, None] pandas.plotting._matplotlib.converter.pandas_converters ()
Context manager registering pandas' converters for a plot.
See Also
--------
register_pandas_matplotlib_converters : Decorator that applies this.
Definition at line 101 of file converter.py.
Referenced by register_pandas_matplotlib_converters().
register()
None pandas.plotting._matplotlib.converter.register ()
Definition at line 122 of file converter.py.
register_pandas_matplotlib_converters()
F pandas.plotting._matplotlib.converter.register_pandas_matplotlib_converters (F func)
Decorator applying pandas_converters.
Definition at line 87 of file converter.py.
References pandas_converters().
time2num()
pandas.plotting._matplotlib.converter.time2num (d)
Definition at line 152 of file converter.py.
Variable Documentation
_mpl_units
dict pandas.plotting._matplotlib.converter._mpl_units = {} protected
Definition at line 72 of file converter.py.