Code Cloning Analysis: numpy.f2py._src_pyf Namespace Reference
numpy.f2py._src_pyf Namespace Reference
Functions
parse_structure (astr)
find_repl_patterns (astr)
find_and_remove_repl_patterns (astr)
conv (astr)
unique_key (adict)
expand_sub (substr, names)
process_str (allstr)
resolve_includes (source)
process_file (source)
Variables
routine_start_re = re.compile(r'(\n|\A)(((\$|\*))|)\s*(subroutine|function)\b', re.I)
routine_end_re = re.compile(r'\n\s*end\s*(subroutine|function)\b.*(\n|\Z)', re.I)
function_start_re = re.compile(r'\n (\$|\*)\s*function\b', re.I)
template_re = re.compile(r"<\s*(\w[\w\d]*)\s*>")
named_re = re.compile(r"<\s*(\w[\w\d]*)\s*=\s*(.*?)\s*>")
list_re = re.compile(r"<\s*((.*?))\s*>")
item_re = re.compile(r"\A\\(?P<index>\d+)\Z")
template_name_re = re.compile(r'\A\s*(\w[\w\d]*)\s*\Z')
include_src_re = re.compile(r"(\n|\A)\s*include\s*['\"](?P<name>[\w\d./\\]+\.src)['\"]", re.I)
_special_names = find_repl_patterns()
Function Documentation
conv()
numpy.f2py._src_pyf.conv (astr)
Definition at line 101 of file _src_pyf.py.
expand_sub()
numpy.f2py._src_pyf.expand_sub (substr, names)
Definition at line 126 of file _src_pyf.py.
find_and_remove_repl_patterns()
numpy.f2py._src_pyf.find_and_remove_repl_patterns (astr)
Definition at line 95 of file _src_pyf.py.
find_repl_patterns()
numpy.f2py._src_pyf.find_repl_patterns (astr)
Definition at line 85 of file _src_pyf.py.
parse_structure()
numpy.f2py._src_pyf.parse_structure (astr)
 Return a list of tuples for each function or subroutine each
tuple is the start and end of a subroutine or function to be
expanded.
Definition at line 54 of file _src_pyf.py.
References unique_key().
Referenced by unique_key().
process_file()
numpy.f2py._src_pyf.process_file (source)
Definition at line 224 of file _src_pyf.py.
process_str()
numpy.f2py._src_pyf.process_str (allstr)
Definition at line 185 of file _src_pyf.py.
resolve_includes()
numpy.f2py._src_pyf.resolve_includes (source)
Definition at line 206 of file _src_pyf.py.
unique_key()
numpy.f2py._src_pyf.unique_key (adict)
 Obtain a unique key given a dictionary.
Definition at line 111 of file _src_pyf.py.
References parse_structure(), and unique_key().
Referenced by parse_structure(), and unique_key().
Variable Documentation
_special_names
numpy.f2py._src_pyf._special_names = find_repl_patterns() protected
Definition at line 228 of file _src_pyf.py.
function_start_re
numpy.f2py._src_pyf.function_start_re = re.compile(r'\n (\$|\*)\s*function\b', re.I)
Definition at line 52 of file _src_pyf.py.
include_src_re
numpy.f2py._src_pyf.include_src_re = re.compile(r"(\n|\A)\s*include\s*['\"](?P<name>[\w\d./\\]+\.src)['\"]", re.I)
Definition at line 204 of file _src_pyf.py.
item_re
numpy.f2py._src_pyf.item_re = re.compile(r"\A\\(?P<index>\d+)\Z")
Definition at line 100 of file _src_pyf.py.
list_re
numpy.f2py._src_pyf.list_re = re.compile(r"<\s*((.*?))\s*>")
Definition at line 83 of file _src_pyf.py.
named_re
numpy.f2py._src_pyf.named_re = re.compile(r"<\s*(\w[\w\d]*)\s*=\s*(.*?)\s*>")
Definition at line 82 of file _src_pyf.py.
routine_end_re
numpy.f2py._src_pyf.routine_end_re = re.compile(r'\n\s*end\s*(subroutine|function)\b.*(\n|\Z)', re.I)
Definition at line 51 of file _src_pyf.py.
routine_start_re
numpy.f2py._src_pyf.routine_start_re = re.compile(r'(\n|\A)(((\$|\*))|)\s*(subroutine|function)\b', re.I)
Definition at line 50 of file _src_pyf.py.
template_name_re
numpy.f2py._src_pyf.template_name_re = re.compile(r'\A\s*(\w[\w\d]*)\s*\Z')
Definition at line 125 of file _src_pyf.py.
template_re
numpy.f2py._src_pyf.template_re = re.compile(r"<\s*(\w[\w\d]*)\s*>")
Definition at line 81 of file _src_pyf.py.