Code Cloning Analysis: numpy.core._dtype Namespace Reference
numpy.core._dtype Namespace Reference
Functions
_kind_name (dtype)
__str__ (dtype)
__repr__ (dtype)
_unpack_field (dtype, offset, title=None)
_isunsized (dtype)
_construction_repr (dtype, include_align=False, short=False)
_scalar_str (dtype, short)
_byte_order_str (dtype)
_datetime_metadata_str (dtype)
_struct_dict_str (dtype, includealignedflag)
_aligned_offset (offset, alignment)
_is_packed (dtype)
_struct_list_str (dtype)
_struct_str (dtype, include_align)
_subarray_str (dtype)
_name_includes_bit_suffix (dtype)
_name_get (dtype)
Variables
dict _kind_to_stem
Detailed Description
A place for code to be called from the implementation of np.dtype
String handling is much easier to do correctly in python.
Function Documentation
__repr__()
numpy.core._dtype.__repr__ (dtype)
Definition at line 45 of file _dtype.py.
__str__()
numpy.core._dtype.__str__ (dtype)
Definition at line 34 of file _dtype.py.
_aligned_offset()
numpy.core._dtype._aligned_offset (offset, alignment) protected
Definition at line 240 of file _dtype.py.
_byte_order_str()
numpy.core._dtype._byte_order_str (dtype) protected
 Normalize byteorder to '<' or '>'
Definition at line 160 of file _dtype.py.
References _construction_repr(), _unpack_field(), and numpy.core.fromnumeric.any().
Referenced by _construction_repr().
_construction_repr()
numpy.core._dtype._construction_repr (dtype, include_align = False, short = False) protected
Creates a string repr of the dtype, excluding the 'dtype()' part
surrounding the object. This object may be a string, a list, or
a dict depending on the nature of the dtype. This
is the object passed as the first parameter to the dtype
constructor, and if no additional constructor parameters are
given, will reproduce the exact memory layout.
Parameters
----------
short : bool
    If true, this creates a shorter repr using 'kind' and 'itemsize', instead
    of the longer type name.
include_align : bool
    If true, this includes the 'align=True' parameter
    inside the struct dtype construction dict when needed. Use this flag
    if you want a proper repr string without the 'dtype()' part around it.
    If false, this does not preserve the
    'align=True' parameter or sticky NPY_ALIGNED_STRUCT flag for
    struct arrays like the regular repr does, because the 'align'
    flag is not part of first dtype constructor parameter. This
    mode is intended for a full 'repr', where the 'align=True' is
    provided as the second parameter.
Definition at line 68 of file _dtype.py.
References _byte_order_str().
Referenced by _byte_order_str(), and _is_packed().
_datetime_metadata_str()
numpy.core._dtype._datetime_metadata_str (dtype) protected
Definition at line 178 of file _dtype.py.
_is_packed()
numpy.core._dtype._is_packed (dtype) protected
Checks whether the structured data type in 'dtype'
has a simple layout, where all the fields are in order,
and follow each other with no alignment padding.
When this returns true, the dtype can be reconstructed
from a list of the field names and dtypes with no additional
dtype parameters.
Duplicates the C `is_dtype_struct_simple_unaligned_layout` function.
Definition at line 245 of file _dtype.py.
References _construction_repr(), _is_packed(), _unpack_field(), and numpy.core.fromnumeric.max().
Referenced by _is_packed().
_isunsized()
numpy.core._dtype._isunsized (dtype) protected
Definition at line 63 of file _dtype.py.
_kind_name()
numpy.core._dtype._kind_name (dtype) protected
Definition at line 24 of file _dtype.py.
_name_get()
numpy.core._dtype._name_get (dtype) protected
Definition at line 346 of file _dtype.py.
_name_includes_bit_suffix()
numpy.core._dtype._name_includes_bit_suffix (dtype) protected
Definition at line 330 of file _dtype.py.
_scalar_str()
numpy.core._dtype._scalar_str (dtype, short) protected
Definition at line 103 of file _dtype.py.
_struct_dict_str()
numpy.core._dtype._struct_dict_str (dtype, includealignedflag) protected
Definition at line 189 of file _dtype.py.
_struct_list_str()
numpy.core._dtype._struct_list_str (dtype) protected
Definition at line 279 of file _dtype.py.
_struct_str()
numpy.core._dtype._struct_str (dtype, include_align) protected
Definition at line 305 of file _dtype.py.
_subarray_str()
numpy.core._dtype._subarray_str (dtype) protected
Definition at line 322 of file _dtype.py.
_unpack_field()
numpy.core._dtype._unpack_field (dtype, offset, title = None) protected
Helper function to normalize the items in dtype.fields.
Call as:
dtype, offset, title = _unpack_field(*dtype.fields[name])
Definition at line 52 of file _dtype.py.
Referenced by _byte_order_str(), and _is_packed().
Variable Documentation
_kind_to_stem
dict numpy.core._dtype._kind_to_stem protected
Initial value:
=  {
    'u': 'uint',
    'i': 'int',
    'c': 'complex',
    'f': 'float',
    'b': 'bool',
    'V': 'void',
    'O': 'object',
    'M': 'datetime',
    'm': 'timedelta',
    'S': 'bytes',
    'U': 'str',
}
Definition at line 9 of file _dtype.py.