Code Cloning Analysis: scipy.io.matlab.tests.test_mio Namespace Reference
scipy.io.matlab.tests.test_mio Namespace Reference
Functions
mlarr (*args, **kwargs)
types_compatible (var1, var2)
_check_level (label, expected, actual)
_load_check_case (name, files, case)
_whos_check_case (name, files, case, classes)
_rt_check_case (name, expected, format)
_cases (version, filt='test%(name) s_ *.mat')
test_load (version)
test_whos (version)
test_round_trip (version, fmts)
test_gzip_simple ()
test_multiple_open ()
test_mat73 ()
test_warnings ()
test_regression_653 ()
test_structname_len ()
test_4_and_long_field_names_incompatible ()
test_long_field_names ()
test_long_field_names_in_struct ()
test_cell_with_one_thing_in_it ()
test_writer_properties ()
test_use_small_element ()
test_save_dict ()
test_1d_shape ()
test_compression ()
test_single_object ()
test_skip_variable ()
test_empty_struct ()
test_save_empty_dict ()
assert_any_equal (output, alternatives)
test_to_writeable ()
test_recarray ()
test_save_object ()
test_read_opts ()
test_empty_string ()
test_corrupted_data ()
test_corrupted_data_check_can_be_disabled ()
test_read_both_endian ()
test_write_opposite_endian ()
test_logical_array ()
test_logical_out_type ()
test_roundtrip_zero_dimensions ()
test_mat4_3d ()
test_func_read ()
test_mat_dtype ()
test_sparse_in_struct ()
test_mat_struct_squeeze ()
test_scalar_squeeze ()
test_str_round ()
test_fieldnames ()
test_loadmat_varnames ()
test_round_types ()
test_varmats_from_mat ()
test_one_by_zero ()
test_load_mat4_le ()
test_unicode_mat4 ()
test_logical_sparse ()
test_empty_sparse ()
test_empty_mat_error ()
test_miuint32_compromise ()
test_miutf8_for_miint8_compromise ()
test_bad_utf8 ()
test_save_unicode_field (tmpdir)
test_save_custom_array_type (tmpdir)
test_filenotfound ()
test_simplify_cells ()
test_matfile_version (version, filt, regex)
test_opaque ()
test_opaque_simplify ()
test_deprecation ()
test_gh_17992 (tmp_path)
Variables
test_data_path = pjoin(dirname(__file__), 'data')
int theta = np.pi/4*np.arange(9,dtype=float).reshape(1,9)
list case_table4
A = np.zeros((3,5))
B = A.astype(complex)
CA
list case_table5
CAE
objarr = np.empty((1,1),dtype=object)
st_sub_arr = array([np.sqrt(2),np.exp(1),np.pi]).reshape(1,3)
list dtype = [(n, object) for n in ['stringfield', 'doublefield', 'complexfield']]
st1 = np.zeros((1,1), dtype)
CN = np.zeros((1,2), dtype=object)
st2 = np.empty((1,1), dtype=[(n, object) for n in ['one', 'two']])
a = np.empty((1,2), dtype=[(n, object) for n in ['one', 'two']])
list ODT
MO = MatlabObject(np.zeros((1,1), dtype=ODT), 'inline')
m0 = MO[0,0]
fp_u_str = open(pjoin(test_data_path, 'japanese_utf8.txt'), 'rb')
u_str = fp_u_str.read().decode('utf-8')
list case_table5_rt = case_table5[:]
Detailed Description
 Nose test generators
Need function load / save / roundtrip tests
Function Documentation
_cases()
scipy.io.matlab.tests.test_mio._cases (version, filt = 'test%(name)s_*.mat') protected
Definition at line 332 of file test_mio.py.
_check_level()
scipy.io.matlab.tests.test_mio._check_level (label, expected, actual) protected
 Check one level of a potentially nested array
Definition at line 250 of file test_mio.py.
References _check_level(), and types_compatible().
Referenced by _check_level().
_load_check_case()
scipy.io.matlab.tests.test_mio._load_check_case (name, files, case) protected
Definition at line 297 of file test_mio.py.
_rt_check_case()
scipy.io.matlab.tests.test_mio._rt_check_case (name, expected, format) protected
Definition at line 324 of file test_mio.py.
_whos_check_case()
scipy.io.matlab.tests.test_mio._whos_check_case (name, files, case, classes) protected
Definition at line 307 of file test_mio.py.
assert_any_equal()
scipy.io.matlab.tests.test_mio.assert_any_equal (output, alternatives)
 Assert `output` is equal to at least one element in `alternatives`
Definition at line 701 of file test_mio.py.
References assert_any_equal().
Referenced by assert_any_equal().
mlarr()
scipy.io.matlab.tests.test_mio.mlarr (* args, ** kwargs)
Convenience function to return matlab-compatible 2-D array.
Definition at line 41 of file test_mio.py.
References mlarr().
Referenced by mlarr().
test_1d_shape()
scipy.io.matlab.tests.test_mio.test_1d_shape ()
Definition at line 584 of file test_mio.py.
test_4_and_long_field_names_incompatible()
scipy.io.matlab.tests.test_mio.test_4_and_long_field_names_incompatible ()
Definition at line 485 of file test_mio.py.
test_bad_utf8()
scipy.io.matlab.tests.test_mio.test_bad_utf8 ()
Definition at line 1225 of file test_mio.py.
test_cell_with_one_thing_in_it()
scipy.io.matlab.tests.test_mio.test_cell_with_one_thing_in_it ()
Definition at line 521 of file test_mio.py.
test_compression()
scipy.io.matlab.tests.test_mio.test_compression ()
Definition at line 609 of file test_mio.py.
test_corrupted_data()
scipy.io.matlab.tests.test_mio.test_corrupted_data ()
Definition at line 882 of file test_mio.py.
test_corrupted_data_check_can_be_disabled()
scipy.io.matlab.tests.test_mio.test_corrupted_data_check_can_be_disabled ()
Definition at line 891 of file test_mio.py.
test_deprecation()
scipy.io.matlab.tests.test_mio.test_deprecation ()
Test that access to previous attributes still works.
Definition at line 1299 of file test_mio.py.
test_empty_mat_error()
scipy.io.matlab.tests.test_mio.test_empty_mat_error ()
Definition at line 1196 of file test_mio.py.
test_empty_sparse()
scipy.io.matlab.tests.test_mio.test_empty_sparse ()
Definition at line 1176 of file test_mio.py.
test_empty_string()
scipy.io.matlab.tests.test_mio.test_empty_string ()
Definition at line 855 of file test_mio.py.
test_empty_struct()
scipy.io.matlab.tests.test_mio.test_empty_struct ()
Definition at line 671 of file test_mio.py.
test_fieldnames()
scipy.io.matlab.tests.test_mio.test_fieldnames ()
Definition at line 1059 of file test_mio.py.
test_filenotfound()
scipy.io.matlab.tests.test_mio.test_filenotfound ()
Definition at line 1250 of file test_mio.py.
test_func_read()
scipy.io.matlab.tests.test_mio.test_func_read ()
Definition at line 973 of file test_mio.py.
test_gh_17992()
scipy.io.matlab.tests.test_mio.test_gh_17992 (tmp_path)
Definition at line 1310 of file test_mio.py.
test_gzip_simple()
scipy.io.matlab.tests.test_mio.test_gzip_simple ()
Definition at line 377 of file test_mio.py.
test_load()
scipy.io.matlab.tests.test_mio.test_load (version)
Definition at line 355 of file test_mio.py.
test_load_mat4_le()
scipy.io.matlab.tests.test_mio.test_load_mat4_le ()
Definition at line 1138 of file test_mio.py.
test_loadmat_varnames()
scipy.io.matlab.tests.test_mio.test_loadmat_varnames ()
Definition at line 1068 of file test_mio.py.
test_logical_array()
scipy.io.matlab.tests.test_mio.test_logical_array ()
Definition at line 931 of file test_mio.py.
test_logical_out_type()
scipy.io.matlab.tests.test_mio.test_logical_out_type ()
Definition at line 942 of file test_mio.py.
test_logical_sparse()
scipy.io.matlab.tests.test_mio.test_logical_sparse ()
Definition at line 1155 of file test_mio.py.
test_long_field_names()
scipy.io.matlab.tests.test_mio.test_long_field_names ()
Definition at line 492 of file test_mio.py.
test_long_field_names_in_struct()
scipy.io.matlab.tests.test_mio.test_long_field_names_in_struct ()
Definition at line 504 of file test_mio.py.
test_mat4_3d()
scipy.io.matlab.tests.test_mio.test_mat4_3d ()
Definition at line 966 of file test_mio.py.
test_mat73()
scipy.io.matlab.tests.test_mio.test_mat73 ()
Definition at line 434 of file test_mio.py.
test_mat_dtype()
scipy.io.matlab.tests.test_mio.test_mat_dtype ()
Definition at line 985 of file test_mio.py.
test_mat_struct_squeeze()
scipy.io.matlab.tests.test_mio.test_mat_struct_squeeze ()
Definition at line 1010 of file test_mio.py.
test_matfile_version()
scipy.io.matlab.tests.test_mio.test_matfile_version (version, filt, regex)
Definition at line 1274 of file test_mio.py.
test_miuint32_compromise()
scipy.io.matlab.tests.test_mio.test_miuint32_compromise ()
Definition at line 1202 of file test_mio.py.
test_miutf8_for_miint8_compromise()
scipy.io.matlab.tests.test_mio.test_miutf8_for_miint8_compromise ()
Definition at line 1214 of file test_mio.py.
test_multiple_open()
scipy.io.matlab.tests.test_mio.test_multiple_open ()
Definition at line 405 of file test_mio.py.
test_one_by_zero()
scipy.io.matlab.tests.test_mio.test_one_by_zero ()
Definition at line 1128 of file test_mio.py.
test_opaque()
scipy.io.matlab.tests.test_mio.test_opaque ()
Test that we can read a MatlabOpaque object.
Definition at line 1286 of file test_mio.py.
test_opaque_simplify()
scipy.io.matlab.tests.test_mio.test_opaque_simplify ()
Test that we can read a MatlabOpaque object when simplify_cells=True.
Definition at line 1293 of file test_mio.py.
test_read_both_endian()
scipy.io.matlab.tests.test_mio.test_read_both_endian ()
Definition at line 897 of file test_mio.py.
test_read_opts()
scipy.io.matlab.tests.test_mio.test_read_opts ()
Definition at line 820 of file test_mio.py.
test_recarray()
scipy.io.matlab.tests.test_mio.test_recarray ()
Definition at line 775 of file test_mio.py.
test_regression_653()
scipy.io.matlab.tests.test_mio.test_regression_653 ()
Definition at line 461 of file test_mio.py.
test_round_trip()
scipy.io.matlab.tests.test_mio.test_round_trip (version, fmts)
Definition at line 371 of file test_mio.py.
test_round_types()
scipy.io.matlab.tests.test_mio.test_round_types ()
Definition at line 1093 of file test_mio.py.
test_roundtrip_zero_dimensions()
scipy.io.matlab.tests.test_mio.test_roundtrip_zero_dimensions ()
Definition at line 959 of file test_mio.py.
test_save_custom_array_type()
scipy.io.matlab.tests.test_mio.test_save_custom_array_type (tmpdir)
Definition at line 1239 of file test_mio.py.
test_save_dict()
scipy.io.matlab.tests.test_mio.test_save_dict ()
Definition at line 569 of file test_mio.py.
test_save_empty_dict()
scipy.io.matlab.tests.test_mio.test_save_empty_dict ()
Definition at line 690 of file test_mio.py.
test_save_object()
scipy.io.matlab.tests.test_mio.test_save_object ()
Definition at line 802 of file test_mio.py.
test_save_unicode_field()
scipy.io.matlab.tests.test_mio.test_save_unicode_field (tmpdir)
Definition at line 1233 of file test_mio.py.
test_scalar_squeeze()
scipy.io.matlab.tests.test_mio.test_scalar_squeeze ()
Definition at line 1020 of file test_mio.py.
test_simplify_cells()
scipy.io.matlab.tests.test_mio.test_simplify_cells ()
Definition at line 1256 of file test_mio.py.
test_single_object()
scipy.io.matlab.tests.test_mio.test_single_object ()
Definition at line 636 of file test_mio.py.
test_skip_variable()
scipy.io.matlab.tests.test_mio.test_skip_variable ()
Definition at line 641 of file test_mio.py.
test_sparse_in_struct()
scipy.io.matlab.tests.test_mio.test_sparse_in_struct ()
Definition at line 1000 of file test_mio.py.
test_str_round()
scipy.io.matlab.tests.test_mio.test_str_round ()
Definition at line 1030 of file test_mio.py.
test_structname_len()
scipy.io.matlab.tests.test_mio.test_structname_len ()
Definition at line 473 of file test_mio.py.
test_to_writeable()
scipy.io.matlab.tests.test_mio.test_to_writeable ()
Definition at line 712 of file test_mio.py.
test_unicode_mat4()
scipy.io.matlab.tests.test_mio.test_unicode_mat4 ()
Definition at line 1146 of file test_mio.py.
test_use_small_element()
scipy.io.matlab.tests.test_mio.test_use_small_element ()
Definition at line 549 of file test_mio.py.
test_varmats_from_mat()
scipy.io.matlab.tests.test_mio.test_varmats_from_mat ()
Definition at line 1106 of file test_mio.py.
test_warnings()
scipy.io.matlab.tests.test_mio.test_warnings ()
Definition at line 448 of file test_mio.py.
test_whos()
scipy.io.matlab.tests.test_mio.test_whos (version)
Definition at line 361 of file test_mio.py.
test_write_opposite_endian()
scipy.io.matlab.tests.test_mio.test_write_opposite_endian ()
Definition at line 912 of file test_mio.py.
test_writer_properties()
scipy.io.matlab.tests.test_mio.test_writer_properties ()
Definition at line 535 of file test_mio.py.
types_compatible()
scipy.io.matlab.tests.test_mio.types_compatible (var1, var2)
Check if types are same or compatible.
0-D numpy scalars are compatible with bare python scalars.
Definition at line 234 of file test_mio.py.
Referenced by _check_level().
Variable Documentation
A
scipy.io.matlab.tests.test_mio.A = np.zeros((3,5))
Definition at line 66 of file test_mio.py.
a
scipy.io.matlab.tests.test_mio.a = np.empty((1,2), dtype=[(n, object) for n in ['one', 'two']])
Definition at line 175 of file test_mio.py.
B
scipy.io.matlab.tests.test_mio.B = A.astype(complex)
Definition at line 79 of file test_mio.py.
CA
scipy.io.matlab.tests.test_mio.CA
Initial value:
=  mlarr((# tuple for object array creation
        [],
        mlarr([1]),
        mlarr([[1,2]]),
        mlarr([[1,2,3]])), dtype=object).reshape(1,-1)
Definition at line 102 of file test_mio.py.
CAE
scipy.io.matlab.tests.test_mio.CAE
Initial value:
=  mlarr((# tuple for object array creation
    mlarr(1),
    mlarr(2),
    mlarr([]),
    mlarr([]),
    mlarr(3)), dtype=object).reshape(1,-1)
Definition at line 113 of file test_mio.py.
case_table4
list scipy.io.matlab.tests.test_mio.case_table4
Initial value:
=  [
    {'name': 'double',
     'classes': {'testdouble': 'double'},
     'expected': {'testdouble': theta}
     }]
Definition at line 50 of file test_mio.py.
case_table5
list scipy.io.matlab.tests.test_mio.case_table5
Initial value:
=  [
    {'name': 'cell',
     'classes': {'testcell': 'cell'},
     'expected': {'testcell': CA}}]
Definition at line 109 of file test_mio.py.
case_table5_rt
list scipy.io.matlab.tests.test_mio.case_table5_rt = case_table5[:]
Definition at line 226 of file test_mio.py.
CN
scipy.io.matlab.tests.test_mio.CN = np.zeros((1,2), dtype=object)
Definition at line 153 of file test_mio.py.
dtype
scipy.io.matlab.tests.test_mio.dtype = [(n, object) for n in ['stringfield', 'doublefield', 'complexfield']]
Definition at line 143 of file test_mio.py.
fp_u_str
scipy.io.matlab.tests.test_mio.fp_u_str = open(pjoin(test_data_path, 'japanese_utf8.txt'), 'rb')
Definition at line 201 of file test_mio.py.
m0
scipy.io.matlab.tests.test_mio.m0 = MO[0,0]
Definition at line 189 of file test_mio.py.
MO
scipy.io.matlab.tests.test_mio.MO = MatlabObject(np.zeros((1,1), dtype=ODT), 'inline')
Definition at line 188 of file test_mio.py.
objarr
scipy.io.matlab.tests.test_mio.objarr = np.empty((1,1),dtype=object)
Definition at line 119 of file test_mio.py.
ODT
list scipy.io.matlab.tests.test_mio.ODT
Initial value:
=  np.dtype([(n, object) for n in
                 ['expr', 'inputExpr', 'args',
                  'isEmpty', 'numArgs', 'version']])
Definition at line 185 of file test_mio.py.
st1
scipy.io.matlab.tests.test_mio.st1 = np.zeros((1,1), dtype)
Definition at line 144 of file test_mio.py.
st2
scipy.io.matlab.tests.test_mio.st2 = np.empty((1,1), dtype=[(n, object) for n in ['one', 'two']])
Definition at line 166 of file test_mio.py.
st_sub_arr
scipy.io.matlab.tests.test_mio.st_sub_arr = array([np.sqrt(2),np.exp(1),np.pi]).reshape(1,3)
Definition at line 142 of file test_mio.py.
test_data_path
scipy.io.matlab.tests.test_mio.test_data_path = pjoin(dirname(__file__), 'data')
Definition at line 38 of file test_mio.py.
theta
int scipy.io.matlab.tests.test_mio.theta = np.pi/4*np.arange(9,dtype=float).reshape(1,9)
Definition at line 49 of file test_mio.py.
u_str
scipy.io.matlab.tests.test_mio.u_str = fp_u_str.read().decode('utf-8')
Definition at line 202 of file test_mio.py.