Code Cloning Analysis: sklearn.cluster._agglomerative.FeatureAgglomeration Class Reference
sklearn.cluster._agglomerative.FeatureAgglomeration Class Reference
Public Member Functions
__init__ (self, n_clusters=2, *, metric="euclidean", memory=None, connectivity=None, compute_full_tree="auto", linkage="ward", pooling_func=np.mean, distance_threshold=None, compute_distances=False)
fit (self, X, y=None)
fit_predict (self)
Public Member Functions inherited from sklearn.base.ClassNamePrefixFeaturesOutMixin
get_feature_names_out (self, input_features=None)
Public Member Functions inherited from sklearn.cluster._feature_agglomeration.AgglomerationTransform
transform (self, X)
inverse_transform (self, X)
Public Member Functions inherited from sklearn.base.TransformerMixin
__sklearn_tags__ (self)
fit_transform (self, X, y=None, **fit_params)
Public Member Functions inherited from sklearn.utils._set_output._SetOutputMixin
__init_subclass__ (cls, auto_wrap_output_keys=("transform",), **kwargs)
set_output (self, *, transform=None)
Public Member Functions inherited from sklearn.cluster._agglomerative.AgglomerativeClustering
__init__ (self, n_clusters=2, *, metric="euclidean", memory=None, connectivity=None, compute_full_tree="auto", linkage="ward", distance_threshold=None, compute_distances=False)
Public Member Functions inherited from sklearn.base.ClusterMixin
__sklearn_tags__ (self)
Public Member Functions inherited from sklearn.base.BaseEstimator
get_params (self, deep=True)
set_params (self, **params)
__sklearn_clone__ (self)
__repr__ (self, N_CHAR_MAX=700)
__getstate__ (self)
__setstate__ (self, state)
__sklearn_tags__ (self)
Public Member Functions inherited from sklearn.utils._metadata_requests._MetadataRequester
set_fit_request (self, **kwargs)
set_partial_fit_request (self, **kwargs)
set_predict_request (self, **kwargs)
set_predict_proba_request (self, **kwargs)
set_predict_log_proba_request (self, **kwargs)
set_decision_function_request (self, **kwargs)
set_score_request (self, **kwargs)
set_split_request (self, **kwargs)
set_transform_request (self, **kwargs)
set_inverse_transform_request (self, **kwargs)
__init_subclass__ (cls, **kwargs)
get_metadata_routing (self)
Additional Inherited Members
Public Attributes inherited from sklearn.cluster._feature_agglomeration.AgglomerationTransform
pooling_func = np.mean and not issparse(X):
Public Attributes inherited from sklearn.cluster._agglomerative.AgglomerativeClustering
n_clusters = n_clusters
distance_threshold = distance_threshold
memory = memory
connectivity = connectivity
compute_full_tree = compute_full_tree
str linkage = linkage
metric = metric
compute_distances = compute_distances
children_
n_connected_components_
n_leaves_
distances_ = out[-1]
tuple n_clusters_
labels_ = _hc_cut(self.n_clusters_, self.children_, self.n_leaves_)
Protected Member Functions inherited from sklearn.cluster._agglomerative.AgglomerativeClustering
_fit (self, X)
Protected Member Functions inherited from sklearn.base.BaseEstimator
_get_param_names (cls)
_get_params_html (self, deep=True)
_validate_params (self)
Protected Member Functions inherited from sklearn.utils._repr_html.base.ReprHTMLMixin
_repr_html_ (self)
_repr_html_inner (self)
_repr_mimebundle_ (self, **kwargs)
Protected Member Functions inherited from sklearn.utils._repr_html.base._HTMLDocumentationLinkMixin
_doc_link_template (self)
_doc_link_template (self, value)
_get_doc_link (self)
Protected Member Functions inherited from sklearn.utils._metadata_requests._MetadataRequester
_build_request_for_signature (cls, router, method)
_get_default_requests (cls)
_get_metadata_request (self)
Protected Attributes inherited from sklearn.base.ClassNamePrefixFeaturesOutMixin
_n_features_out
Protected Attributes inherited from sklearn.utils._set_output._SetOutputMixin
_sklearn_auto_wrap_output_keys = set()
dict _sklearn_output_config = {}
Protected Attributes inherited from sklearn.base.BaseEstimator
_parameter_constraints
Static Protected Attributes inherited from sklearn.base.ClusterMixin
str _estimator_type = "clusterer"
Static Protected Attributes inherited from sklearn.base.BaseEstimator
_html_repr = estimator_html_repr
Static Protected Attributes inherited from sklearn.utils._repr_html.base._HTMLDocumentationLinkMixin
str _doc_link_module = "sklearn"
_doc_link_url_param_generator = None
Detailed Description
Agglomerate features.
Recursively merges pair of clusters of features.
Refer to
:ref:`sphx_glr_auto_examples_cluster_plot_feature_agglomeration_vs_univariate_selection.py`
for an example comparison of :class:`FeatureAgglomeration` strategy with a
univariate feature selection strategy (based on ANOVA).
Read more in the :ref:`User Guide <hierarchical_clustering>`.
Parameters
----------
n_clusters : int or None, default=2
    The number of clusters to find. It must be ``None`` if
    ``distance_threshold`` is not ``None``.
metric : str or callable, default="euclidean"
    Metric used to compute the linkage. Can be "euclidean", "l1", "l2",
    "manhattan", "cosine", or "precomputed". If linkage is "ward", only
    "euclidean" is accepted. If "precomputed", a distance matrix is needed
    as input for the fit method.
    .. versionadded:: 1.2
memory : str or object with the joblib.Memory interface, default=None
    Used to cache the output of the computation of the tree.
    By default, no caching is done. If a string is given, it is the
    path to the caching directory.
connectivity : array-like, sparse matrix, or callable, default=None
    Connectivity matrix. Defines for each feature the neighboring
    features following a given structure of the data.
    This can be a connectivity matrix itself or a callable that transforms
    the data into a connectivity matrix, such as derived from
    `kneighbors_graph`. Default is `None`, i.e, the
    hierarchical clustering algorithm is unstructured.
compute_full_tree : 'auto' or bool, default='auto'
    Stop early the construction of the tree at `n_clusters`. This is useful
    to decrease computation time if the number of clusters is not small
    compared to the number of features. This option is useful only when
    specifying a connectivity matrix. Note also that when varying the
    number of clusters and using caching, it may be advantageous to compute
    the full tree. It must be ``True`` if ``distance_threshold`` is not
    ``None``. By default `compute_full_tree` is "auto", which is equivalent
    to `True` when `distance_threshold` is not `None` or that `n_clusters`
    is inferior to the maximum between 100 or `0.02 * n_samples`.
    Otherwise, "auto" is equivalent to `False`.
linkage : {"ward", "complete", "average", "single"}, default="ward"
    Which linkage criterion to use. The linkage criterion determines which
    distance to use between sets of features. The algorithm will merge
    the pairs of cluster that minimize this criterion.
    - "ward" minimizes the variance of the clusters being merged.
    - "complete" or maximum linkage uses the maximum distances between
      all features of the two sets.
    - "average" uses the average of the distances of each feature of
      the two sets.
    - "single" uses the minimum of the distances between all features
      of the two sets.
pooling_func : callable, default=np.mean
    This combines the values of agglomerated features into a single
    value, and should accept an array of shape [M, N] and the keyword
    argument `axis=1`, and reduce it to an array of size [M].
distance_threshold : float, default=None
    The linkage distance threshold at or above which clusters will not be
    merged. If not ``None``, ``n_clusters`` must be ``None`` and
    ``compute_full_tree`` must be ``True``.
    .. versionadded:: 0.21
compute_distances : bool, default=False
    Computes distances between clusters even if `distance_threshold` is not
    used. This can be used to make dendrogram visualization, but introduces
    a computational and memory overhead.
    .. versionadded:: 0.24
Attributes
----------
n_clusters_ : int
    The number of clusters found by the algorithm. If
    ``distance_threshold=None``, it will be equal to the given
    ``n_clusters``.
labels_ : array-like of (n_features,)
    Cluster labels for each feature.
n_leaves_ : int
    Number of leaves in the hierarchical tree.
n_connected_components_ : int
    The estimated number of connected components in the graph.
    .. versionadded:: 0.21
        ``n_connected_components_`` was added to replace ``n_components_``.
n_features_in_ : int
    Number of features seen during :term:`fit`.
    .. versionadded:: 0.24
feature_names_in_ : ndarray of shape (`n_features_in_`,)
    Names of features seen during :term:`fit`. Defined only when `X`
    has feature names that are all strings.
    .. versionadded:: 1.0
children_ : array-like of shape (n_nodes-1, 2)
    The children of each non-leaf node. Values less than `n_features`
    correspond to leaves of the tree which are the original samples.
    A node `i` greater than or equal to `n_features` is a non-leaf
    node and has children `children_[i - n_features]`. Alternatively
    at the i-th iteration, children[i][0] and children[i][1]
    are merged to form node `n_features + i`.
distances_ : array-like of shape (n_nodes-1,)
    Distances between nodes in the corresponding place in `children_`.
    Only computed if `distance_threshold` is used or `compute_distances`
    is set to `True`.
See Also
--------
AgglomerativeClustering : Agglomerative clustering samples instead of
    features.
ward_tree : Hierarchical clustering with ward linkage.
Examples
--------
>>> import numpy as np
>>> from sklearn import datasets, cluster
>>> digits = datasets.load_digits()
>>> images = digits.images
>>> X = np.reshape(images, (len(images), -1))
>>> agglo = cluster.FeatureAgglomeration(n_clusters=32)
>>> agglo.fit(X)
FeatureAgglomeration(n_clusters=32)
>>> X_reduced = agglo.transform(X)
>>> X_reduced.shape
(1797, 32)
Definition at line 1119 of file _agglomerative.py.
Constructor & Destructor Documentation
__init__()
sklearn.cluster._agglomerative.FeatureAgglomeration.__init__ (self, n_clusters = 2, * , metric = "euclidean", memory = None, connectivity = None, compute_full_tree = "auto", linkage = "ward", pooling_func = np.mean, distance_threshold = None, compute_distances = False)
Definition at line 1283 of file _agglomerative.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params().
Member Function Documentation
fit()
sklearn.cluster._agglomerative.FeatureAgglomeration.fit (self, X, y = None)
Fit the hierarchical clustering on the data.
Parameters
----------
X : array-like of shape (n_samples, n_features)
    The data.
y : Ignored
    Not used, present here for API consistency by convention.
Returns
-------
self : object
    Returns the transformer.
Reimplemented from sklearn.cluster._agglomerative.AgglomerativeClustering.
Definition at line 1309 of file _agglomerative.py.
References sklearn.cluster._agglomerative.AgglomerativeClustering._fit(), sklearn.base.ClassNamePrefixFeaturesOutMixin._n_features_out, and sklearn.cluster._agglomerative.AgglomerativeClustering.n_clusters_.
Referenced by sklearn.cluster._dbscan.DBSCAN.fit_predict(), sklearn.cluster._hdbscan.hdbscan.HDBSCAN.fit_predict(), sklearn.cluster._kmeans._BaseKMeans.fit_predict(), sklearn.neighbors._lof.LocalOutlierFactor.fit_predict(), sklearn.cluster._kmeans._BaseKMeans.fit_transform(), sklearn.cross_decomposition._pls._PLS.fit_transform(), sklearn.cross_decomposition._pls.PLSSVD.fit_transform(), sklearn.decomposition._kernel_pca.KernelPCA.fit_transform(), sklearn.decomposition._lda.LatentDirichletAllocation.fit_transform(), sklearn.manifold._spectral_embedding.SpectralEmbedding.fit_transform(), sklearn.neighbors._graph.KNeighborsTransformer.fit_transform(), sklearn.neighbors._graph.RadiusNeighborsTransformer.fit_transform(), sklearn.preprocessing._label.LabelBinarizer.fit_transform(), sklearn.preprocessing._label.MultiLabelBinarizer.fit_transform(), sklearn.tests.metadata_routing_common.ConsumingTransformer.fit_transform(), and sklearn.utils.tests.test_estimator_checks.SparseTransformer.fit_transform().
fit_predict()
sklearn.cluster._agglomerative.FeatureAgglomeration.fit_predict (self)
Fit and return the result of each sample's clustering assignment.
Reimplemented from sklearn.cluster._agglomerative.AgglomerativeClustering.
Definition at line 1331 of file _agglomerative.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/sklearn/cluster/_agglomerative.py