Code Cloning Analysis: scipy.optimize.tests.test_linprog Namespace Reference
scipy.optimize.tests.test_linprog Namespace Reference
Classes
class AutoscaleTests
class LinprogCommonTests
Common Tests #.
class LinprogHiGHSTests
class LinprogIPTests
class LinprogRSTests
class LinprogSimplexTests
class RRTests
class TestAutoscaleIP
class TestAutoscaleRS
class TestAutoscaleSimplex
class TestLinprogHiGHSIPM
class TestLinprogHiGHSMIP
class TestLinprogHiGHSSimplexDual
class TestLinprogIPDense
class TestLinprogIPSparse
class TestLinprogIPSparseCholmod
class TestLinprogIPSparsePresolve
class TestLinprogIPSparseUmfpack
class TestLinprogIPSpecific
class TestLinprogRSBland
class TestLinprogRSCommon
class TestLinprogSimplexBland
class TestLinprogSimplexDefault
class TestLinprogSimplexNoPresolve
class TestRRID
class TestRRPivot
class TestRRSVD
Functions
_assert_iteration_limit_reached (res, maxiter)
_assert_infeasible (res)
_assert_unbounded (res)
_assert_unable_to_find_basic_feasible_sol (res)
_assert_success (res, desired_fun=None, desired_x=None, rtol=1e-8, atol=1e-8)
magic_square (n)
lpgen_2d (m, n)
very_random_gen (seed=0)
nontrivial_problem ()
l1_regression_prob (seed=0, m=8, d=9, n=100)
generic_callback_test (self)
test_unknown_solvers_and_options ()
test_choose_solver ()
test_deprecation ()
test_highs_status_message ()
test_bug_17380 ()
Variables
bool has_umfpack = True
bool has_cholmod = True
A_ub = None
b_ub = None
A_eq = None
b_eq = None
bounds = None
Detailed Description
Unit test for Linear Programming
Function Documentation
_assert_infeasible()
scipy.optimize.tests.test_linprog._assert_infeasible (res) protected
Definition at line 38 of file test_linprog.py.
_assert_iteration_limit_reached()
scipy.optimize.tests.test_linprog._assert_iteration_limit_reached (res, maxiter) protected
Definition at line 32 of file test_linprog.py.
_assert_success()
scipy.optimize.tests.test_linprog._assert_success (res, desired_fun = None, desired_x = None, rtol = 1e-8, atol = 1e-8) protected
Definition at line 60 of file test_linprog.py.
_assert_unable_to_find_basic_feasible_sol()
scipy.optimize.tests.test_linprog._assert_unable_to_find_basic_feasible_sol (res) protected
Definition at line 50 of file test_linprog.py.
_assert_unbounded()
scipy.optimize.tests.test_linprog._assert_unbounded (res) protected
Definition at line 44 of file test_linprog.py.
generic_callback_test()
scipy.optimize.tests.test_linprog.generic_callback_test (self)
Definition at line 239 of file test_linprog.py.
l1_regression_prob()
scipy.optimize.tests.test_linprog.l1_regression_prob (seed = 0, m = 8, d = 9, n = 100)
Training data is {(x0, y0), (x1, y2), ..., (xn-1, yn-1)}
    x in R^d
    y in R
n: number of training samples
d: dimension of x, i.e. x in R^d
phi: feature map R^d -> R^m
m: dimension of feature space
Definition at line 204 of file test_linprog.py.
References magic_square().
Referenced by scipy.optimize.tests.test_linprog.TestLinprogHiGHSSimplexDual.test_lad_regression().
lpgen_2d()
scipy.optimize.tests.test_linprog.lpgen_2d (m, n)
 -> A b c LP test: m*n vars, m+n constraints
    row sums == n/m, col sums == 1
    https://gist.github.com/denis-bz/8647461
Definition at line 147 of file test_linprog.py.
Referenced by scipy.optimize.tests.test_linprog.LinprogCommonTests.test_callback(), and scipy.optimize.tests.test_linprog.LinprogCommonTests.test_nontrivial_problem().
magic_square()
scipy.optimize.tests.test_linprog.magic_square (n)
Generates a linear program for which integer solutions represent an
n x n magic square; binary decision variables represent the presence
(or absence) of an integer 1 to n^2 in each position of the square.
Definition at line 81 of file test_linprog.py.
Referenced by l1_regression_prob(), scipy.optimize.tests.test_linprog.LinprogCommonTests.test_bug_5400(), and scipy.optimize.tests.test_linprog.LinprogHiGHSTests.test_callback().
nontrivial_problem()
scipy.optimize.tests.test_linprog.nontrivial_problem ()
Definition at line 190 of file test_linprog.py.
test_bug_17380()
scipy.optimize.tests.test_linprog.test_bug_17380 ()
Definition at line 349 of file test_linprog.py.
test_choose_solver()
scipy.optimize.tests.test_linprog.test_choose_solver ()
Definition at line 285 of file test_linprog.py.
test_deprecation()
scipy.optimize.tests.test_linprog.test_deprecation ()
Definition at line 295 of file test_linprog.py.
test_highs_status_message()
scipy.optimize.tests.test_linprog.test_highs_status_message ()
Definition at line 304 of file test_linprog.py.
test_unknown_solvers_and_options()
scipy.optimize.tests.test_linprog.test_unknown_solvers_and_options ()
Definition at line 270 of file test_linprog.py.
very_random_gen()
scipy.optimize.tests.test_linprog.very_random_gen (seed = 0)
Definition at line 174 of file test_linprog.py.
Variable Documentation
A_eq
scipy.optimize.tests.test_linprog.A_eq = None
Definition at line 355 of file test_linprog.py.
A_ub
scipy.optimize.tests.test_linprog.A_ub = None
Definition at line 353 of file test_linprog.py.
b_eq
scipy.optimize.tests.test_linprog.b_eq = None
Definition at line 356 of file test_linprog.py.
b_ub
scipy.optimize.tests.test_linprog.b_ub = None
Definition at line 354 of file test_linprog.py.
bounds
scipy.optimize.tests.test_linprog.bounds = None
Definition at line 357 of file test_linprog.py.
has_cholmod
bool scipy.optimize.tests.test_linprog.has_cholmod = True
Definition at line 24 of file test_linprog.py.
has_umfpack
bool scipy.optimize.tests.test_linprog.has_umfpack = True
Definition at line 18 of file test_linprog.py.