Code Cloning Analysis: matplotlib.style.core Namespace Reference
matplotlib.style.core Namespace Reference
Functions
use (style)
context (style, after_reset=False)
update_user_library (library)
read_style_directory (style_dir)
update_nested_dict (main_dict, new_dict)
reload_library ()
Variables
_log = logging.getLogger(__name__)
list __all__ = ['use', 'context', 'available', 'library', 'reload_library']
BASE_LIBRARY_PATH = os.path.join(mpl.get_data_path(), 'stylelib')
list USER_LIBRARY_PATHS = [os.path.join(mpl.get_configdir(), 'stylelib')]
str STYLE_EXTENSION = 'mplstyle'
dict STYLE_BLACKLIST
_base_library = read_style_directory(BASE_LIBRARY_PATH)
dict library = {}
list available = []
Detailed Description
Core functions and attributes for the matplotlib style library:
``use``
    Select style sheet to override the current matplotlib settings.
``context``
    Context manager to use a style sheet temporarily.
``available``
    List available style sheets.
``library``
    A dictionary of style names and matplotlib settings.
Function Documentation
context()
matplotlib.style.core.context (style, after_reset = False)
Context manager for using style settings temporarily.
Parameters
----------
style : str, dict, Path or list
    A style specification. Valid options are:
    str
        - One of the style names in `.style.available` (a builtin style or
          a style installed in the user library path).
        - A dotted name of the form "package.style_name"; in that case,
          "package" should be an importable Python package name, e.g. at
          ``/path/to/package/__init__.py``; the loaded style file is
          ``/path/to/package/style_name.mplstyle``.  (Style files in
          subpackages are likewise supported.)
        - The path or URL to a style file, which gets loaded by
          `.rc_params_from_file`.
    dict
        A mapping of key/value pairs for `matplotlib.rcParams`.
    Path
        The path to a style file, which gets loaded by
        `.rc_params_from_file`.
    list
        A list of style specifiers (str, Path or dict), which are applied
        from first to last in the list.
after_reset : bool
    If True, apply style after resetting settings to their defaults;
    otherwise, apply style on top of the current settings.
Definition at line 147 of file core.py.
References use().
read_style_directory()
matplotlib.style.core.read_style_directory (style_dir)
Return dictionary of styles defined in *style_dir*.
Definition at line 198 of file core.py.
References matplotlib._rc_params_in_file().
Referenced by update_nested_dict(), and update_user_library().
reload_library()
matplotlib.style.core.reload_library ()
Reload the style library.
Definition at line 230 of file core.py.
References reload_library(), and update_user_library().
Referenced by reload_library().
update_nested_dict()
matplotlib.style.core.update_nested_dict (main_dict, new_dict)
Update nested dict (only level of nesting) with new values.
Unlike `dict.update`, this assumes that the values of the parent dict are
dicts (or dict-like), so you shouldn't replace the nested dict if it
already exists. Instead you should update the sub-dict.
Definition at line 209 of file core.py.
References read_style_directory().
Referenced by update_user_library().
update_user_library()
matplotlib.style.core.update_user_library (library)
Update style library with user-defined rc files.
Definition at line 190 of file core.py.
References read_style_directory(), and update_nested_dict().
Referenced by reload_library().
use()
matplotlib.style.core.use (style)
Use Matplotlib style settings from a style specification.
The style name of 'default' is reserved for reverting back to
the default style settings.
.. note::
   This updates the `.rcParams` with the settings from the style.
   `.rcParams` not defined in the style are kept.
Parameters
----------
style : str, dict, Path or list
    A style specification. Valid options are:
    str
        - One of the style names in `.style.available` (a builtin style or
          a style installed in the user library path).
        - A dotted name of the form "package.style_name"; in that case,
          "package" should be an importable Python package name, e.g. at
          ``/path/to/package/__init__.py``; the loaded style file is
          ``/path/to/package/style_name.mplstyle``.  (Style files in
          subpackages are likewise supported.)
        - The path or URL to a style file, which gets loaded by
          `.rc_params_from_file`.
    dict
        A mapping of key/value pairs for `matplotlib.rcParams`.
    Path
        The path to a style file, which gets loaded by
        `.rc_params_from_file`.
    list
        A list of style specifiers (str, Path or dict), which are applied
        from first to last in the list.
Notes
-----
The following `.rcParams` are not related to style and will be ignored if
found in a style specification:
%s
Definition at line 45 of file core.py.
References matplotlib._rc_params_in_file().
Referenced by context().
Variable Documentation
__all__
list matplotlib.style.core.__all__ = ['use', 'context', 'available', 'library', 'reload_library'] private
Definition at line 26 of file core.py.
_base_library
matplotlib.style.core._base_library = read_style_directory(BASE_LIBRARY_PATH) protected
Definition at line 225 of file core.py.
_log
matplotlib.style.core._log = logging.getLogger(__name__) protected
Definition at line 24 of file core.py.
available
list matplotlib.style.core.available = []
Definition at line 227 of file core.py.
BASE_LIBRARY_PATH
matplotlib.style.core.BASE_LIBRARY_PATH = os.path.join(mpl.get_data_path(), 'stylelib')
Definition at line 29 of file core.py.
library
dict matplotlib.style.core.library = {}
Definition at line 226 of file core.py.
STYLE_BLACKLIST
dict matplotlib.style.core.STYLE_BLACKLIST
Initial value:
=  {
    'interactive', 'backend', 'webagg.port', 'webagg.address',
    'webagg.port_retries', 'webagg.open_in_browser', 'backend_fallback',
    'toolbar', 'timezone', 'figure.max_open_warning',
    'figure.raise_window', 'savefig.directory', 'tk.window_focus',
    'docstring.hardcopy', 'date.epoch'}
Definition at line 34 of file core.py.
STYLE_EXTENSION
str matplotlib.style.core.STYLE_EXTENSION = 'mplstyle'
Definition at line 32 of file core.py.
USER_LIBRARY_PATHS
list matplotlib.style.core.USER_LIBRARY_PATHS = [os.path.join(mpl.get_configdir(), 'stylelib')]
Definition at line 31 of file core.py.