Code Cloning Analysis: matplotlib.dates.WeekdayLocator Class Reference
matplotlib.dates.WeekdayLocator Class Reference
Public Member Functions
__init__ (self, byweekday=1, interval=1, tz=None)
Public Member Functions inherited from matplotlib.dates.RRuleLocator
__init__ (self, o, tz=None)
__call__ (self)
tick_values (self, vmin, vmax)
Public Member Functions inherited from matplotlib.dates.DateLocator
__init__ (self, tz=None)
set_tzinfo (self, tz)
datalim_to_dt (self)
viewlim_to_dt (self)
nonsingular (self, vmin, vmax)
Public Member Functions inherited from matplotlib.ticker.Locator
set_params (self, **kwargs)
__call__ (self)
raise_if_exceeds (self, locs)
view_limits (self, vmin, vmax)
Public Member Functions inherited from matplotlib.ticker.TickHelper
set_axis (self, axis)
create_dummy_axis (self, **kwargs)
Additional Inherited Members
Static Public Member Functions inherited from matplotlib.dates.RRuleLocator
get_unit_generic (freq)
Public Attributes inherited from matplotlib.dates.RRuleLocator
rule = o
Public Attributes inherited from matplotlib.dates.DateLocator
tz = _get_tzinfo(tz)
Static Public Attributes inherited from matplotlib.dates.DateLocator
dict hms0d = {'byhour': 0, 'byminute': 0, 'bysecond': 0}
Static Public Attributes inherited from matplotlib.ticker.Locator
int MAXTICKS = 1000
Static Public Attributes inherited from matplotlib.ticker.TickHelper
axis = None
Protected Member Functions inherited from matplotlib.dates.RRuleLocator
_create_rrule (self, vmin, vmax)
_get_unit (self)
_get_interval (self)
Detailed Description
Make ticks on occurrences of each weekday.
Definition at line 1524 of file dates.py.
Constructor & Destructor Documentation
__init__()
matplotlib.dates.WeekdayLocator.__init__ (self, byweekday = 1, interval = 1, tz = None)
Parameters
----------
byweekday : int or list of int, default: all days
    Ticks will be placed on every weekday in *byweekday*. Default is
    every day.
    Elements of *byweekday* must be one of MO, TU, WE, TH, FR, SA,
    SU, the constants from :mod:`dateutil.rrule`, which have been
    imported into the :mod:`matplotlib.dates` namespace.
interval : int, default: 1
    The interval between each iteration. For example, if
    ``interval=2``, mark every second occurrence.
tz : str or `~datetime.tzinfo`, default: :rc:`timezone`
    Ticks timezone. If a string, *tz* is passed to `dateutil.tz`.
Definition at line 1529 of file dates.py.
References __init__(), and matplotlib.dates.DateLocator.hms0d.
Referenced by __init__(), sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/dates.py