Code Cloning Analysis: pandas.core.array_algos.take Namespace Reference
pandas.core.array_algos.take Namespace Reference
Functions
np.ndarray take_nd (np.ndarray arr, indexer, AxisInt axis=..., fill_value=..., bool allow_fill=...)
ArrayLike take_nd (ExtensionArray arr, indexer, AxisInt axis=..., fill_value=..., bool allow_fill=...)
ArrayLike take_nd (ArrayLike arr, indexer, AxisInt axis=0, fill_value=lib.no_default, bool allow_fill=True)
np.ndarray _take_nd_ndarray (np.ndarray arr, npt.NDArray[np.intp]|None indexer, AxisInt axis, fill_value, bool allow_fill)
ArrayLike take_1d (ArrayLike arr, npt.NDArray[np.intp] indexer, fill_value=None, bool allow_fill=True, npt.NDArray[np.bool_]|None mask=None)
np.ndarray take_2d_multi (np.ndarray arr, tuple[npt.NDArray[np.intp], npt.NDArray[np.intp]] indexer, fill_value=np.nan)
_get_take_nd_function_cached (int ndim, np.dtype arr_dtype, np.dtype out_dtype, AxisInt axis)
_get_take_nd_function (int ndim, np.dtype arr_dtype, np.dtype out_dtype, AxisInt axis=0, mask_info=None)
_view_wrapper (f, arr_dtype=None, out_dtype=None, fill_wrap=None)
_convert_wrapper (f, conv_dtype)
None _take_nd_object (np.ndarray arr, npt.NDArray[np.intp] indexer, np.ndarray out, AxisInt axis, fill_value, mask_info)
None _take_2d_multi_object (np.ndarray arr, tuple[npt.NDArray[np.intp], npt.NDArray[np.intp]] indexer, np.ndarray out, fill_value, mask_info)
_take_preprocess_indexer_and_fill_value (np.ndarray arr, npt.NDArray[np.intp] indexer, fill_value, bool allow_fill, npt.NDArray[np.bool_]|None mask=None)
Variables
dict _take_1d_dict
dict _take_2d_axis0_dict
dict _take_2d_axis1_dict
dict _take_2d_multi_dict
Function Documentation
_convert_wrapper()
pandas.core.array_algos.take._convert_wrapper (f, conv_dtype) protected
Definition at line 374 of file take.py.
_get_take_nd_function()
pandas.core.array_algos.take._get_take_nd_function (int ndim, np.dtype arr_dtype, np.dtype out_dtype, AxisInt axis = 0, mask_info = None) protected
Get the appropriate "take" implementation for the given dimension, axis
and dtypes.
Definition at line 325 of file take.py.
References _get_take_nd_function_cached().
Referenced by take_1d(), and take_nd().
_get_take_nd_function_cached()
pandas.core.array_algos.take._get_take_nd_function_cached (int ndim, np.dtype arr_dtype, np.dtype out_dtype, AxisInt axis) protected
Part of _get_take_nd_function below that doesn't need `mask_info` and thus
can be cached (mask_info potentially contains a numpy ndarray which is not
hashable and thus cannot be used as argument for cached function).
Definition at line 288 of file take.py.
Referenced by _get_take_nd_function().
_take_2d_multi_object()
None pandas.core.array_algos.take._take_2d_multi_object (np.ndarray arr, tuple[npt.NDArray[np.intp], npt.NDArray[np.intp]] indexer, np.ndarray out, fill_value, mask_info) protected
Definition at line 535 of file take.py.
_take_nd_ndarray()
np.ndarray pandas.core.array_algos.take._take_nd_ndarray (np.ndarray arr, npt.NDArray[np.intp] | None indexer, AxisInt axis, fill_value, bool allow_fill) protected
Definition at line 120 of file take.py.
_take_nd_object()
None pandas.core.array_algos.take._take_nd_object (np.ndarray arr, npt.NDArray[np.intp] indexer, np.ndarray out, AxisInt axis, fill_value, mask_info) protected
Definition at line 512 of file take.py.
_take_preprocess_indexer_and_fill_value()
pandas.core.array_algos.take._take_preprocess_indexer_and_fill_value (np.ndarray arr, npt.NDArray[np.intp] indexer, fill_value, bool allow_fill, npt.NDArray[np.bool_] | None mask = None) protected
Definition at line 564 of file take.py.
_view_wrapper()
pandas.core.array_algos.take._view_wrapper (f, arr_dtype = None, out_dtype = None, fill_wrap = None) protected
Definition at line 352 of file take.py.
take_1d()
ArrayLike pandas.core.array_algos.take.take_1d (ArrayLike arr, npt.NDArray[np.intp] indexer, fill_value = None, bool allow_fill = True, npt.NDArray[np.bool_] | None mask = None)
Specialized version for 1D arrays. Differences compared to `take_nd`:
- Assumes input array has already been converted to numpy array / EA
- Assumes indexer is already guaranteed to be intp dtype ndarray
- Only works for 1D arrays
To ensure the lowest possible overhead.
Note: similarly to `take_nd`, this function assumes that the indexer is
a valid(ated) indexer with no out of bound indices.
Parameters
----------
arr : np.ndarray or ExtensionArray
    Input array.
indexer : ndarray
    1-D array of indices to take (validated indices, intp dtype).
fill_value : any, default np.nan
    Fill value to replace -1 values with
allow_fill : bool, default True
    If False, indexer is assumed to contain no -1 values so no filling
    will be done.  This short-circuits computation of a mask. Result is
    undefined if allow_fill == False and -1 is present in indexer.
mask : np.ndarray, optional, default None
    If `allow_fill` is True, and the mask (where indexer == -1) is already
    known, it can be passed to avoid recomputation.
Definition at line 169 of file take.py.
References _get_take_nd_function().
take_2d_multi()
np.ndarray pandas.core.array_algos.take.take_2d_multi (np.ndarray arr, tuple[npt.NDArray[np.intp], npt.NDArray[np.intp]] indexer, fill_value = np.nan)
Specialized Cython take which sets NaN values in one pass.
Definition at line 227 of file take.py.
take_nd() [1/3]
ArrayLike pandas.core.array_algos.take.take_nd (ArrayLike arr, indexer, AxisInt axis = 0, fill_value = lib.no_default, bool allow_fill = True)
Specialized Cython take which sets NaN values in one pass
This dispatches to ``take`` defined on ExtensionArrays.
Note: this function assumes that the indexer is a valid(ated) indexer with
no out of bound indices.
Parameters
----------
arr : np.ndarray or ExtensionArray
    Input array.
indexer : ndarray
    1-D array of indices to take, subarrays corresponding to -1 value
    indices are filed with fill_value
axis : int, default 0
    Axis to take from
fill_value : any, default np.nan
    Fill value to replace -1 values with
allow_fill : bool, default True
    If False, indexer is assumed to contain no -1 values so no filling
    will be done.  This short-circuits computation of a mask.  Result is
    undefined if allow_fill == False and -1 is present in indexer.
Returns
-------
subarray : np.ndarray or ExtensionArray
    May be the same type as the input, or cast to an ndarray.
Definition at line 59 of file take.py.
References _get_take_nd_function().
take_nd() [2/3]
ArrayLike pandas.core.array_algos.take.take_nd (ExtensionArray arr, indexer, AxisInt axis = ..., fill_value = ..., bool allow_fill = ...)
Definition at line 49 of file take.py.
take_nd() [3/3]
np.ndarray pandas.core.array_algos.take.take_nd (np.ndarray arr, indexer, AxisInt axis = ..., fill_value = ..., bool allow_fill = ...)
Definition at line 38 of file take.py.
Variable Documentation
_take_1d_dict
dict pandas.core.array_algos.take._take_1d_dict protected
Initial value:
=  {
    ("int8", "int8"): libalgos.take_1d_int8_int8,
    ("int8", "int32"): libalgos.take_1d_int8_int32,
    ("int8", "int64"): libalgos.take_1d_int8_int64,
    ("int8", "float64"): libalgos.take_1d_int8_float64,
    ("int16", "int16"): libalgos.take_1d_int16_int16,
    ("int16", "int32"): libalgos.take_1d_int16_int32,
    ("int16", "int64"): libalgos.take_1d_int16_int64,
    ("int16", "float64"): libalgos.take_1d_int16_float64,
    ("int32", "int32"): libalgos.take_1d_int32_int32,
    ("int32", "int64"): libalgos.take_1d_int32_int64,
    ("int32", "float64"): libalgos.take_1d_int32_float64,
    ("int64", "int64"): libalgos.take_1d_int64_int64,
    ("int64", "float64"): libalgos.take_1d_int64_float64,
    ("float32", "float32"): libalgos.take_1d_float32_float32,
    ("float32", "float64"): libalgos.take_1d_float32_float64,
    ("float64", "float64"): libalgos.take_1d_float64_float64,
    ("object", "object"): libalgos.take_1d_object_object,
    ("bool", "bool"): _view_wrapper(libalgos.take_1d_bool_bool, np.uint8, np.uint8),
    ("bool", "object"): _view_wrapper(libalgos.take_1d_bool_object, np.uint8, None),
    ("datetime64[ns]", "datetime64[ns]"): _view_wrapper(
        libalgos.take_1d_int64_int64, np.int64, np.int64, np.int64
    ),
    ("timedelta64[ns]", "timedelta64[ns]"): _view_wrapper(
        libalgos.take_1d_int64_int64, np.int64, np.int64, np.int64
    ),
}
Definition at line 387 of file take.py.
_take_2d_axis0_dict
dict pandas.core.array_algos.take._take_2d_axis0_dict protected
Definition at line 415 of file take.py.
_take_2d_axis1_dict
dict pandas.core.array_algos.take._take_2d_axis1_dict protected
Definition at line 447 of file take.py.
_take_2d_multi_dict
dict pandas.core.array_algos.take._take_2d_multi_dict protected
Definition at line 479 of file take.py.