Code Cloning Analysis: numpy.lib._iotools Namespace Reference
numpy.lib._iotools Namespace Reference
Classes
class ConversionWarning
class ConverterError
class ConverterLockError
class LineSplitter
class NameValidator
class StringConverter
Functions
_decode_line (line, encoding=None)
_is_string_like (obj)
_is_bytes_like (obj)
has_nested_fields (ndtype)
flatten_dtype (ndtype, flatten_base=False)
str2bool (value)
easy_dtype (ndtype, names=None, defaultfmt="f%i", **validationargs)
Variables
str __docformat__ = "restructuredtext en"
Detailed Description
A collection of functions designed to help I/O with ascii files.
Function Documentation
_decode_line()
numpy.lib._iotools._decode_line (line, encoding = None) protected
Decode bytes from binary input streams.
Defaults to decoding from 'latin1'. That differs from the behavior of
np.compat.asunicode that decodes from 'ascii'.
Parameters
----------
line : str or bytes
     Line to be decoded.
encoding : str
     Encoding used to decode `line`.
Returns
-------
decoded_line : str
Definition at line 11 of file _iotools.py.
Referenced by numpy.lib._iotools.LineSplitter._delimited_splitter(), and numpy.lib._iotools.LineSplitter.autostrip().
_is_bytes_like()
numpy.lib._iotools._is_bytes_like (obj) protected
Check whether obj behaves like a bytes object.
Definition at line 48 of file _iotools.py.
_is_string_like()
numpy.lib._iotools._is_string_like (obj) protected
Check whether obj behaves like a string.
Definition at line 37 of file _iotools.py.
easy_dtype()
numpy.lib._iotools.easy_dtype (ndtype, names = None, defaultfmt = "f%i", ** validationargs)
Convenience function to create a `np.dtype` object.
The function processes the input `dtype` and matches it with the given
names.
Parameters
----------
ndtype : var
    Definition of the dtype. Can be any string or dictionary recognized
    by the `np.dtype` function, or a sequence of types.
names : str or sequence, optional
    Sequence of strings to use as field names for a structured dtype.
    For convenience, `names` can be a string of a comma-separated list
    of names.
defaultfmt : str, optional
    Format string used to define missing names, such as ``"f%i"``
    (default) or ``"fields_%02i"``.
validationargs : optional
    A series of optional arguments used to initialize a
    `NameValidator`.
Examples
--------
>>> np.lib._iotools.easy_dtype(float)
dtype('float64')
>>> np.lib._iotools.easy_dtype("i4, f8")
dtype([('f0', '<i4'), ('f1', '<f8')])
>>> np.lib._iotools.easy_dtype("i4, f8", defaultfmt="field_%03i")
dtype([('field_000', '<i4'), ('field_001', '<f8')])
>>> np.lib._iotools.easy_dtype((int, float, float), names="a,b,c")
dtype([('a', '<i8'), ('b', '<f8'), ('c', '<f8')])
>>> np.lib._iotools.easy_dtype(float, names="a,b,c")
dtype([('a', '<f8'), ('b', '<f8'), ('c', '<f8')])
Definition at line 822 of file _iotools.py.
flatten_dtype()
numpy.lib._iotools.flatten_dtype (ndtype, flatten_base = False)
Unpack a structured data-type by collapsing nested fields and/or fields
with a shape.
Note that the field names are lost.
Parameters
----------
ndtype : dtype
    The datatype to collapse
flatten_base : bool, optional
   If True, transform a field with a shape into several fields. Default is
   False.
Examples
--------
>>> dt = np.dtype([('name', 'S4'), ('x', float), ('y', float),
...                ('block', int, (2, 3))])
>>> np.lib._iotools.flatten_dtype(dt)
[dtype('S4'), dtype('float64'), dtype('float64'), dtype('int64')]
>>> np.lib._iotools.flatten_dtype(dt, flatten_base=True)
[dtype('S4'),
 dtype('float64'),
 dtype('float64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64'),
 dtype('int64')]
Definition at line 86 of file _iotools.py.
References flatten_dtype().
Referenced by flatten_dtype().
has_nested_fields()
numpy.lib._iotools.has_nested_fields (ndtype)
Returns whether one or several fields of a dtype are nested.
Parameters
----------
ndtype : dtype
    Data-type of a structured array.
Raises
------
AttributeError
    If `ndtype` does not have a `names` attribute.
Examples
--------
>>> dt = np.dtype([('name', 'S4'), ('x', float), ('y', float)])
>>> np.lib._iotools.has_nested_fields(dt)
False
Definition at line 59 of file _iotools.py.
str2bool()
numpy.lib._iotools.str2bool (value)
Tries to transform a string supposed to represent a boolean to a boolean.
Parameters
----------
value : str
    The string that is transformed to a boolean.
Returns
-------
boolval : bool
    The boolean representation of `value`.
Raises
------
ValueError
    If the string is not 'True' or 'False' (case independent)
Examples
--------
>>> np.lib._iotools.str2bool('TRUE')
True
>>> np.lib._iotools.str2bool('false')
False
Definition at line 385 of file _iotools.py.
Variable Documentation
__docformat__
str numpy.lib._iotools.__docformat__ = "restructuredtext en" private
Definition at line 4 of file _iotools.py.