Code Cloning Analysis: fontTools.unicodedata Namespace Reference
fontTools.unicodedata Namespace Reference
Functions
mirrored (code)
script (char)
script_extension (char)
script_name (code, default=KeyError)
_normalize_property_name (string)
script_code (script_name, default=KeyError)
HorizDirection|T script_horizontal_direction (str script_code, T default)
HorizDirection script_horizontal_direction (str script_code, type[KeyError] default=KeyError)
HorizDirection|T script_horizontal_direction (str script_code, T|type[KeyError] default=KeyError)
block (char)
ot_tags_from_script (script_code)
ot_tag_to_script (tag)
Variables
list __all__
_normalize_re = re.compile(r"[-_ ]+")
dict _SCRIPT_CODES = {_normalize_property_name(v): k for k, v in Scripts.NAMES.items()}
dict RTL_SCRIPTS
HorizDirection = Literal["RTL", "LTR"]
T = TypeVar("T")
Function Documentation
_normalize_property_name()
fontTools.unicodedata._normalize_property_name (string) protected
Remove case, strip space, '-' and '_' for loose matching.
Definition at line 119 of file __init__.py.
References _normalize_property_name().
Referenced by _normalize_property_name(), and script_code().
block()
fontTools.unicodedata.block (char)
Return the block property assigned to the Unicode character 'char'
as a string.
>>> block("a")
'Basic Latin'
>>> block(chr(0x060C))
'Arabic'
>>> block(chr(0xEFFFF))
'No_Block'
Definition at line 232 of file __init__.py.
mirrored()
fontTools.unicodedata.mirrored (code)
If code (unicode codepoint) has a mirrored version returns it, otherwise None.
Definition at line 48 of file __init__.py.
ot_tag_to_script()
fontTools.unicodedata.ot_tag_to_script (tag)
Return the Unicode script code for the given OpenType script tag, or
None for "DFLT" tag or if there is no Unicode script associated with it.
Raises ValueError if the tag is invalid.
Definition at line 267 of file __init__.py.
ot_tags_from_script()
fontTools.unicodedata.ot_tags_from_script (script_code)
Return a list of OpenType script tags associated with a given
Unicode script code.
Return ['DFLT'] script tag for invalid/unknown script codes.
Definition at line 248 of file __init__.py.
script()
fontTools.unicodedata.script (char)
Return the four-letter script code assigned to the Unicode character
'char' as string.
>>> script("a")
'Latn'
>>> script(",")
'Zyyy'
>>> script(chr(0x10FFFF))
'Zzzz'
Definition at line 53 of file __init__.py.
Referenced by script_extension().
script_code()
fontTools.unicodedata.script_code (script_name, default = KeyError)
Returns the four-letter Unicode script code from its long name
If no matching script code is found, a KeyError is raised by default.
You can use the 'default' argument to return a fallback string (e.g.
'Zzzz' or None) instead of throwing an error.
Definition at line 127 of file __init__.py.
References _normalize_property_name().
script_extension()
fontTools.unicodedata.script_extension (char)
Return the script extension property assigned to the Unicode character
'char' as a set of string.
>>> script_extension("a") == {'Latn'}
True
>>> script_extension(chr(0x060C)) == {'Nkoo', 'Arab', 'Rohg', 'Thaa', 'Syrc', 'Gara', 'Yezi'}
True
>>> script_extension(chr(0x10FFFF)) == {'Zzzz'}
True
Definition at line 78 of file __init__.py.
References script().
script_horizontal_direction() [1/3]
HorizDirection | T fontTools.unicodedata.script_horizontal_direction (str script_code, T default)
Definition at line 210 of file __init__.py.
script_horizontal_direction() [2/3]
HorizDirection fontTools.unicodedata.script_horizontal_direction (str script_code, type[KeyError] default = KeyError)
Definition at line 214 of file __init__.py.
script_horizontal_direction() [3/3]
HorizDirection | T fontTools.unicodedata.script_horizontal_direction (str script_code, T | type[KeyError] default = KeyError)
Return "RTL" for scripts that contain right-to-left characters
according to the Bidi_Class property. Otherwise return "LTR".
Definition at line 219 of file __init__.py.
script_name()
fontTools.unicodedata.script_name (code, default = KeyError)
Return the long, human-readable script name given a four-letter
Unicode script code.
If no matching name is found, a KeyError is raised by default.
You can use the 'default' argument to return a fallback value (e.g.
'Unknown' or None) instead of throwing an error.
Definition at line 99 of file __init__.py.
Variable Documentation
__all__
list fontTools.unicodedata.__all__ private
Initial value:
=  [
    # names from built-in unicodedata module
    "lookup",
    "name",
    "decimal",
    "digit",
    "numeric",
    "category",
    "bidirectional",
    "combining",
    "east_asian_width",
    "mirrored",
    "decomposition",
    "normalize",
    "unidata_version",
    "ucd_3_2_0",
    # additonal functions
    "block",
    "script",
    "script_extension",
    "script_name",
    "script_code",
    "script_horizontal_direction",
    "ot_tags_from_script",
    "ot_tag_to_script",
]
Definition at line 20 of file __init__.py.
_normalize_re
fontTools.unicodedata._normalize_re = re.compile(r"[-_ ]+") protected
Definition at line 116 of file __init__.py.
_SCRIPT_CODES
dict fontTools.unicodedata._SCRIPT_CODES = {_normalize_property_name(v): k for k, v in Scripts.NAMES.items()} protected
Definition at line 124 of file __init__.py.
HorizDirection
fontTools.unicodedata.HorizDirection = Literal["RTL", "LTR"]
Definition at line 205 of file __init__.py.
RTL_SCRIPTS
dict fontTools.unicodedata.RTL_SCRIPTS
Definition at line 148 of file __init__.py.
T
fontTools.unicodedata.T = TypeVar("T")
Definition at line 206 of file __init__.py.