Code Cloning Analysis: fontTools.designspaceLib.BaseDocWriter Class Reference
fontTools.designspaceLib.BaseDocWriter Class Reference
Public Member Functions
getAxisDecriptor (cls)
getAxisMappingDescriptor (cls)
getSourceDescriptor (cls)
getInstanceDescriptor (cls)
getRuleDescriptor (cls)
__init__ (self, documentPath, DesignSpaceDocument documentObject)
write (self, pretty=True, encoding="UTF-8", xml_declaration=True)
intOrFloat (self, num)
Public Attributes
path = documentPath
documentObject = documentObject
effectiveFormatTuple = self._getEffectiveFormatTuple()
root = ET.Element("designspace")
Static Public Attributes
axisDescriptorClass = AxisDescriptor
discreteAxisDescriptorClass = DiscreteAxisDescriptor
axisLabelDescriptorClass = AxisLabelDescriptor
axisMappingDescriptorClass = AxisMappingDescriptor
locationLabelDescriptorClass = LocationLabelDescriptor
ruleDescriptorClass = RuleDescriptor
sourceDescriptorClass = SourceDescriptor
variableFontDescriptorClass = VariableFontDescriptor
valueAxisSubsetDescriptorClass = ValueAxisSubsetDescriptor
rangeAxisSubsetDescriptorClass = RangeAxisSubsetDescriptor
instanceDescriptorClass = InstanceDescriptor
Protected Member Functions
_getEffectiveFormatTuple (self)
_makeLocationElement (self, locationObject, name=None)
_addRule (self, ruleObject)
_addAxis (self, axisObject)
_addAxisMapping (self, mappingsElement, mappingObject)
None _addAxisLabel (self, ET.Element axisElement, AxisLabelDescriptor label)
_addLabelNames (self, parentElement, labelNames)
None _addLocationLabel (self, ET.Element parentElement, LocationLabelDescriptor label)
_addLocationElement (self, parentElement, *, AnisotropicLocationDict designLocation=None, SimpleLocationDict userLocation=None)
_addInstance (self, instanceObject)
_addSource (self, sourceObject)
None _addVariableFont (self, ET.Element parentElement, VariableFontDescriptor vf)
None _addLib (self, ET.Element parentElement, Any data, int indent_level)
_writeGlyphElement (self, instanceElement, instanceObject, glyphName, data)
Static Protected Attributes
str _whiteSpace = " "
Detailed Description
Definition at line 1388 of file __init__.py.
Constructor & Destructor Documentation
__init__()
fontTools.designspaceLib.BaseDocWriter.__init__ (self, documentPath, DesignSpaceDocument documentObject)
Definition at line 1422 of file __init__.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_addAxis()
fontTools.designspaceLib.BaseDocWriter._addAxis (self, axisObject) protected
Definition at line 1588 of file __init__.py.
_addAxisLabel()
None fontTools.designspaceLib.BaseDocWriter._addAxisLabel (self, ET.Element axisElement, AxisLabelDescriptor label) protected
Definition at line 1637 of file __init__.py.
Referenced by _makeLocationElement().
_addAxisMapping()
fontTools.designspaceLib.BaseDocWriter._addAxisMapping (self, mappingsElement, mappingObject) protected
Definition at line 1618 of file __init__.py.
_addInstance()
fontTools.designspaceLib.BaseDocWriter._addInstance (self, instanceObject) protected
Definition at line 1706 of file __init__.py.
_addLabelNames()
fontTools.designspaceLib.BaseDocWriter._addLabelNames (self, parentElement, labelNames) protected
Definition at line 1658 of file __init__.py.
Referenced by _makeLocationElement().
_addLib()
None fontTools.designspaceLib.BaseDocWriter._addLib (self, ET.Element parentElement, Any data, int indent_level) protected
Definition at line 1917 of file __init__.py.
Referenced by _makeLocationElement().
_addLocationElement()
fontTools.designspaceLib.BaseDocWriter._addLocationElement (self, parentElement, * , AnisotropicLocationDict designLocation = None, SimpleLocationDict userLocation = None) protected
Definition at line 1678 of file __init__.py.
Referenced by _makeLocationElement().
_addLocationLabel()
None fontTools.designspaceLib.BaseDocWriter._addLocationLabel (self, ET.Element parentElement, LocationLabelDescriptor label) protected
Definition at line 1665 of file __init__.py.
_addRule()
fontTools.designspaceLib.BaseDocWriter._addRule (self, ruleObject) protected
Definition at line 1556 of file __init__.py.
_addSource()
fontTools.designspaceLib.BaseDocWriter._addSource (self, sourceObject) protected
Definition at line 1812 of file __init__.py.
_addVariableFont()
None fontTools.designspaceLib.BaseDocWriter._addVariableFont (self, ET.Element parentElement, VariableFontDescriptor vf) protected
Definition at line 1878 of file __init__.py.
_getEffectiveFormatTuple()
fontTools.designspaceLib.BaseDocWriter._getEffectiveFormatTuple (self) protected
Try to use the version specified in the document, or a sufficiently
recent version to be able to encode what the document contains.
Definition at line 1503 of file __init__.py.
References documentObject.
_makeLocationElement()
fontTools.designspaceLib.BaseDocWriter._makeLocationElement (self, locationObject, name = None) protected
Convert Location dict to a locationElement.
Definition at line 1530 of file __init__.py.
References _addAxisLabel(), _addLabelNames(), _addLib(), _addLocationElement(), _makeLocationElement(), _writeGlyphElement(), documentObject, effectiveFormatTuple, intOrFloat(), and root.
Referenced by _makeLocationElement().
_writeGlyphElement()
fontTools.designspaceLib.BaseDocWriter._writeGlyphElement (self, instanceElement, instanceObject, glyphName, data) protected
Definition at line 1924 of file __init__.py.
Referenced by _makeLocationElement().
getAxisDecriptor()
fontTools.designspaceLib.BaseDocWriter.getAxisDecriptor (cls)
Definition at line 1403 of file __init__.py.
getAxisMappingDescriptor()
fontTools.designspaceLib.BaseDocWriter.getAxisMappingDescriptor (cls)
Definition at line 1407 of file __init__.py.
getInstanceDescriptor()
fontTools.designspaceLib.BaseDocWriter.getInstanceDescriptor (cls)
Definition at line 1415 of file __init__.py.
getRuleDescriptor()
fontTools.designspaceLib.BaseDocWriter.getRuleDescriptor (cls)
Definition at line 1419 of file __init__.py.
getSourceDescriptor()
fontTools.designspaceLib.BaseDocWriter.getSourceDescriptor (cls)
Definition at line 1411 of file __init__.py.
intOrFloat()
fontTools.designspaceLib.BaseDocWriter.intOrFloat (self, num)
Definition at line 1551 of file __init__.py.
Referenced by _makeLocationElement().
write()
fontTools.designspaceLib.BaseDocWriter.write (self, pretty = True, encoding = "UTF-8", xml_declaration = True)
Definition at line 1428 of file __init__.py.
Referenced by matplotlib.backends.backend_pdf.PdfFile.addGouraudTriangles(), matplotlib.backends.backend_pdf.PdfFile.close(), fontTools.ttLib.tables.otConverters.BaseConverter.read(), joblib.externals.cloudpickle.cloudpickle.Pickler.reducer_override(), scipy.io.matlab._mio5.VarWriter5.write_sparse(), pandas.io.formats.html.HTMLFormatter.write_th(), scipy.io.matlab._mio5.VarWriter5.write_top(), matplotlib.backends.backend_pdf.PdfFile.writeTrailer(), and matplotlib.backends.backend_pdf.PdfFile.writeXref().
Member Data Documentation
_whiteSpace
str fontTools.designspaceLib.BaseDocWriter._whiteSpace = " " static protected
Definition at line 1389 of file __init__.py.
axisDescriptorClass
fontTools.designspaceLib.BaseDocWriter.axisDescriptorClass = AxisDescriptor static
Definition at line 1390 of file __init__.py.
axisLabelDescriptorClass
fontTools.designspaceLib.BaseDocWriter.axisLabelDescriptorClass = AxisLabelDescriptor static
Definition at line 1392 of file __init__.py.
axisMappingDescriptorClass
fontTools.designspaceLib.BaseDocWriter.axisMappingDescriptorClass = AxisMappingDescriptor static
Definition at line 1393 of file __init__.py.
discreteAxisDescriptorClass
fontTools.designspaceLib.BaseDocWriter.discreteAxisDescriptorClass = DiscreteAxisDescriptor static
Definition at line 1391 of file __init__.py.
documentObject
fontTools.designspaceLib.BaseDocWriter.documentObject = documentObject
Definition at line 1424 of file __init__.py.
Referenced by _getEffectiveFormatTuple(), _makeLocationElement(), fontTools.designspaceLib.BaseDocReader.readLib(), and fontTools.designspaceLib.BaseDocReader.readLocationElement().
effectiveFormatTuple
fontTools.designspaceLib.BaseDocWriter.effectiveFormatTuple = self._getEffectiveFormatTuple()
Definition at line 1425 of file __init__.py.
Referenced by _makeLocationElement().
instanceDescriptorClass
fontTools.designspaceLib.BaseDocWriter.instanceDescriptorClass = InstanceDescriptor static
Definition at line 1400 of file __init__.py.
Referenced by fontTools.designspaceLib.BaseDocReader.readLocationElement().
locationLabelDescriptorClass
fontTools.designspaceLib.BaseDocWriter.locationLabelDescriptorClass = LocationLabelDescriptor static
Definition at line 1394 of file __init__.py.
path
fontTools.designspaceLib.BaseDocWriter.path = documentPath
Definition at line 1423 of file __init__.py.
Referenced by pip._vendor.distlib.database._Cache.__init__(), pip._vendor.distlib.database.BaseInstalledDistribution.__init__(), pip._vendor.distlib.database.DistributionPath.__init__(), fontTools.pens.qtPen.QtPen._qCurveToOne(), fontTools.pens.quartzPen.QuartzPen._qCurveToOne(), fontTools.pens.wxPen.WxPen._qCurveToOne(), pip._vendor.distlib.database.DistributionPath._yield_distributions(), pip._vendor.distlib.database._Cache.add(), pip._vendor.distlib.database.EggInfoDistribution.check_installed_files(), pip._vendor.distlib.database.InstalledDistribution.check_installed_files(), pip._vendor.distlib.database._Cache.clear(), sklearn.linear_model._coordinate_descent.ElasticNet.fit(), sklearn.linear_model._coordinate_descent.LinearModelCV.fit(), pip._internal.models.link.Link.from_element(), pip._vendor.distlib.database.InstalledDistribution.get_distinfo_file(), fontTools.designspaceLib.DesignSpaceDocument.getVariableFonts(), pip._vendor.distlib.database.EggInfoDistribution.list_distinfo_files(), pip._vendor.distlib.database.InstalledDistribution.list_distinfo_files(), pip._vendor.distlib.database.EggInfoDistribution.list_installed_files(), pip._internal.models.link.Link.netloc(), fontTools.designspaceLib.DesignSpaceDocument.read(), pip._vendor.urllib3.util.url.Url.request_uri(), pip._vendor.distlib.database.InstalledDistribution.shared_locations(), fontTools.designspaceLib.DesignSpaceDocument.updateFilenameFromPath(), fontTools.designspaceLib.DesignSpaceDocument.updatePaths(), fontTools.designspaceLib.DesignSpaceDocument.write(), pip._vendor.distlib.database.InstalledDistribution.write_installed_files(), and pip._vendor.distlib.database.InstalledDistribution.write_shared_locations().
rangeAxisSubsetDescriptorClass
fontTools.designspaceLib.BaseDocWriter.rangeAxisSubsetDescriptorClass = RangeAxisSubsetDescriptor static
Definition at line 1399 of file __init__.py.
root
fontTools.designspaceLib.BaseDocWriter.root = ET.Element("designspace")
Definition at line 1426 of file __init__.py.
Referenced by pandas.io.formats.xml.EtreeXMLFormatter._build_tree(), pandas.io.formats.xml.LxmlXMLFormatter._build_tree(), sklearn.ensemble._hist_gradient_boosting.grower.TreeGrower._initialize_root(), _makeLocationElement(), pandas.io.formats.xml.LxmlXMLFormatter._transform_doc(), pandas.io.pytables.HDFStore.get_node(), sklearn.ensemble._hist_gradient_boosting.grower.TreeGrower.make_predictor(), fontTools.designspaceLib.BaseDocReader.readLib(), and fontTools.designspaceLib.BaseDocReader.readLocationElement().
ruleDescriptorClass
fontTools.designspaceLib.BaseDocWriter.ruleDescriptorClass = RuleDescriptor static
Definition at line 1395 of file __init__.py.
sourceDescriptorClass
fontTools.designspaceLib.BaseDocWriter.sourceDescriptorClass = SourceDescriptor static
Definition at line 1396 of file __init__.py.
valueAxisSubsetDescriptorClass
fontTools.designspaceLib.BaseDocWriter.valueAxisSubsetDescriptorClass = ValueAxisSubsetDescriptor static
Definition at line 1398 of file __init__.py.
variableFontDescriptorClass
fontTools.designspaceLib.BaseDocWriter.variableFontDescriptorClass = VariableFontDescriptor static
Definition at line 1397 of file __init__.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/designspaceLib/__init__.py