Code Cloning Analysis: sklearn.utils._repr_html.estimator Namespace Reference
sklearn.utils._repr_html.estimator Namespace Reference
Classes
class _IDCounter
class _VisualBlock
Functions
_get_css_style ()
_write_label_html (out, params, name, name_details, name_caption=None, doc_link_label=None, outer_class="sk-label-container", inner_class="sk-label", checked=False, doc_link="", is_fitted_css_class="", is_fitted_icon="", param_prefix="")
_get_visual_block (estimator)
_write_estimator_html (out, estimator, estimator_label, estimator_label_details, is_fitted_css_class, is_fitted_icon="", first_call=False, param_prefix="")
estimator_html_repr (estimator)
Variables
_CONTAINER_ID_COUNTER = _IDCounter("sk-container-id")
_ESTIMATOR_ID_COUNTER = _IDCounter("sk-estimator-id")
_CSS_STYLE = _get_css_style()
Function Documentation
_get_css_style()
sklearn.utils._repr_html.estimator._get_css_style () protected
Definition at line 26 of file estimator.py.
_get_visual_block()
sklearn.utils._repr_html.estimator._get_visual_block (estimator) protected
Generate information about how to display an estimator.
Definition at line 223 of file estimator.py.
Referenced by _write_estimator_html().
_write_estimator_html()
sklearn.utils._repr_html.estimator._write_estimator_html (out, estimator, estimator_label, estimator_label_details, is_fitted_css_class, is_fitted_icon = "", first_call = False, param_prefix = "") protected
Write estimator to html in serial, parallel, or by itself (single).
For multiple estimators, this function is called recursively.
Parameters
----------
out : file-like object
    The file to write the HTML representation to.
estimator : estimator object
    The estimator to visualize.
estimator_label : str
    The label for the estimator. It corresponds either to the estimator class name
    for simple estimator or in the case of `Pipeline` and `ColumnTransformer`, it
    corresponds to the name of the step.
estimator_label_details : str
    The details to show as content in the dropdown part of the toggleable label.
    It can contain information as non-default parameters or column information for
    `ColumnTransformer`.
is_fitted_css_class : {"", "fitted"}
    The CSS class to indicate whether or not the estimator is fitted or not. The
    empty string means that the estimator is not fitted and "fitted" means that the
    estimator is fitted.
is_fitted_icon : str, default=""
    The HTML representation to show the fitted information in the diagram. An empty
    string means that no information is shown. If the estimator to be shown is not
    the first estimator (i.e. `first_call=False`), `is_fitted_icon` is always an
    empty string.
first_call : bool, default=False
    Whether this is the first time this function is called.
param_prefix : str, default=""
    The prefix to prepend to parameter names for nested estimators.
    For example, in a pipeline this might be "pipeline__stepname__".
Definition at line 266 of file estimator.py.
References _get_visual_block(), _write_estimator_html(), and _write_label_html().
Referenced by _write_estimator_html(), and estimator_html_repr().
_write_label_html()
sklearn.utils._repr_html.estimator._write_label_html (out, params, name, name_details, name_caption = None, doc_link_label = None, outer_class = "sk-label-container", inner_class = "sk-label", checked = False, doc_link = "", is_fitted_css_class = "", is_fitted_icon = "", param_prefix = "") protected
Write labeled html with or without a dropdown with named details.
Parameters
----------
out : file-like object
    The file to write the HTML representation to.
params: str
    If estimator has `get_params` method, this is the HTML representation
    of the estimator's parameters and their values. When the estimator
    does not have `get_params`, it is an empty string.
name : str
    The label for the estimator. It corresponds either to the estimator class name
    for a simple estimator or in the case of a `Pipeline` and `ColumnTransformer`,
    it corresponds to the name of the step.
name_details : str
    The details to show as content in the dropdown part of the toggleable label. It
    can contain information such as non-default parameters or column information for
    `ColumnTransformer`.
name_caption : str, default=None
    The caption below the name. If `None`, no caption will be created.
doc_link_label : str, default=None
    The label for the documentation link. If provided, the label would be
    "Documentation for {doc_link_label}". Otherwise it will look for `name`.
outer_class : {"sk-label-container", "sk-item"}, default="sk-label-container"
    The CSS class for the outer container.
inner_class : {"sk-label", "sk-estimator"}, default="sk-label"
    The CSS class for the inner container.
checked : bool, default=False
    Whether the dropdown is folded or not. With a single estimator, we intend to
    unfold the content.
doc_link : str, default=""
    The link to the documentation for the estimator. If an empty string, no link is
    added to the diagram. This can be generated for an estimator if it uses the
    `_HTMLDocumentationLinkMixin`.
is_fitted_css_class : {"", "fitted"}
    The CSS class to indicate whether or not the estimator is fitted. The
    empty string means that the estimator is not fitted and "fitted" means that the
    estimator is fitted.
is_fitted_icon : str, default=""
    The HTML representation to show the fitted information in the diagram. An empty
    string means that no information is shown.
param_prefix : str, default=""
    The prefix to prepend to parameter names for nested estimators.
Definition at line 108 of file estimator.py.
Referenced by _write_estimator_html().
estimator_html_repr()
sklearn.utils._repr_html.estimator.estimator_html_repr (estimator)
Build a HTML representation of an estimator.
Read more in the :ref:`User Guide <visualizing_composite_estimators>`.
Parameters
----------
estimator : estimator object
    The estimator to visualize.
Returns
-------
html: str
    HTML representation of estimator.
Examples
--------
>>> from sklearn.utils._repr_html.estimator import estimator_html_repr
>>> from sklearn.linear_model import LogisticRegression
>>> estimator_html_repr(LogisticRegression())
'<style>#sk-container-id...'
Definition at line 407 of file estimator.py.
References _write_estimator_html().
Variable Documentation
_CONTAINER_ID_COUNTER
sklearn.utils._repr_html.estimator._CONTAINER_ID_COUNTER = _IDCounter("sk-container-id") protected
Definition at line 36 of file estimator.py.
_CSS_STYLE
sklearn.utils._repr_html.estimator._CSS_STYLE = _get_css_style() protected
Definition at line 38 of file estimator.py.
_ESTIMATOR_ID_COUNTER
sklearn.utils._repr_html.estimator._ESTIMATOR_ID_COUNTER = _IDCounter("sk-estimator-id") protected
Definition at line 37 of file estimator.py.