Code Cloning Analysis: PIL.PdfParser.PdfStream Class Reference
PIL.PdfParser.PdfStream Class Reference
Public Member Functions
None __init__ (self, PdfDict dictionary, bytes buf)
bytes decode (self)
Public Attributes
dictionary = dictionary
buf = buf
Detailed Description
Definition at line 317 of file PdfParser.py.
Constructor & Destructor Documentation
__init__()
None PIL.PdfParser.PdfStream.__init__ (self, PdfDict dictionary, bytes buf)
Definition at line 318 of file PdfParser.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
decode()
bytes PIL.PdfParser.PdfStream.decode (self)
Definition at line 322 of file PdfParser.py.
Referenced by sklearn.feature_extraction.text._VectorizerMixin.build_analyzer().
Member Data Documentation
buf
PIL.PdfParser.PdfStream.buf = buf
Definition at line 320 of file PdfParser.py.
dictionary
PIL.PdfParser.PdfStream.dictionary = dictionary
Definition at line 319 of file PdfParser.py.
Referenced by sklearn.decomposition._dict_learning.SparseCoder.inverse_transform(), sklearn.decomposition._dict_learning.SparseCoder.n_components_(), sklearn.decomposition._dict_learning.SparseCoder.n_features_in_(), and sklearn.decomposition._dict_learning.SparseCoder.transform().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/PIL/PdfParser.py