Code Cloning Analysis: pandas.plotting._matplotlib.core.PiePlot Class Reference
pandas.plotting._matplotlib.core.PiePlot Class Reference
Public Member Functions
None __init__ (self, data, kind=None, **kwargs)
Public Member Functions inherited from pandas.plotting._matplotlib.core.MPLPlot
str|None orientation (self)
None __init__ (self, data, kind=None, IndexLabel|None by=None, bool|Sequence[Sequence[str]] subplots=False, bool|None sharex=None, bool sharey=False, bool use_index=True, tuple[float, float]|None figsize=None, grid=None, bool|str legend=True, rot=None, ax=None, fig=None, title=None, xlim=None, ylim=None, xticks=None, yticks=None, Hashable|None xlabel=None, Hashable|None ylabel=None, int|None fontsize=None, bool|tuple|list|np.ndarray secondary_y=False, colormap=None, bool table=False, layout=None, bool include_bool=False, IndexLabel|None column=None, *, bool|None|Literal["sym"] logx=False, bool|None|Literal["sym"] logy=False, bool|None|Literal["sym"] loglog=False, bool mark_right=True, bool stacked=False, Hashable|None label=None, style=None, **kwds)
int nseries (self)
None draw (self)
None generate (self)
Figure fig (self)
Sequence[Axes] axes (self)
result (self)
str|None legend_title (self)
plt (self)
on_right (self, int i)
Protected Member Functions
Literal["pie"] _kind (self)
bool|None|Literal["sym"] _validate_log_kwd (cls, str kwd, bool|None|Literal["sym"] value)
None _validate_color_args (self, color, colormap)
None _make_plot (self, Figure fig)
None _post_plot_logic (self, Axes ax, data)
Protected Member Functions inherited from pandas.plotting._matplotlib.core.MPLPlot
int _get_nseries (self, Series|DataFrame data)
Axes _maybe_right_yaxis (self, Axes ax, int axes_num)
tuple[Sequence[Axes], Figure] _axes_and_fig (self)
DataFrame _ensure_frame (self, data)
None _compute_plot_data (self)
None _add_table (self)
None _post_plot_logic_common (self, Axes ax)
None _adorn_subplots (self, Figure fig)
str _mark_right_label (self, str label, int index)
None _append_legend_handles_labels (self, Artist handle, str label)
None _make_legend (self)
_get_xticks (self)
_plot (cls, Axes ax, x, np.ndarray y, style=None, bool is_errorbar=False, **kwds)
_get_custom_index_name (self)
str|None _get_index_name (self)
_get_ax_layer (cls, ax, bool primary=True)
int _col_idx_to_axis_idx (self, int col_idx)
_get_ax (self, int i)
_apply_style_colors (self, colors, dict[str, Any] kwds, int col_num, str label)
_get_colors (self, int|None num_colors=None, str color_kwds="color")
dict[str, Any] _get_errorbars (self, label=None, index=None, bool xerr=True, bool yerr=True)
_get_subplots (self, Figure fig)
tuple[int, int] _get_axes_layout (self, Figure fig)
Additional Inherited Members
Public Attributes inherited from pandas.plotting._matplotlib.core.MPLPlot
by = com.maybe_make_list(by)
list columns = com.maybe_make_list(column)
kind = kind
bool|list[tuple[int,...]] subplots
bool sharex = type(self)._validate_sharex(sharex, ax, by)
sharey = sharey
figsize = figsize
layout = layout
xticks = xticks
yticks = yticks
xlim = xlim
ylim = ylim
title = title
use_index = use_index
xlabel = xlabel
ylabel = ylabel
fontsize = fontsize
int rot = rot
grid = grid
str legend = legend
list legend_handles = []
list legend_labels = []
bool|None|Literal["sym"] logx = type(self)._validate_log_kwd("logx", logx)
bool|None|Literal["sym"] logy = type(self)._validate_log_kwd("logy", logy)
bool|None|Literal["sym"] loglog = type(self)._validate_log_kwd("loglog", loglog)
label = label
style = style
mark_right = mark_right
stacked = stacked
ax = ax
dict errors = {"xerr": xerr, "yerr": yerr}
DataFrame data = data
secondary_y = secondary_y
colormap = kwds.pop("cmap")
table = table
include_bool = include_bool
kwds = kwds
color = self._validate_color_args(color, self.colormap)
int nseries = 1 and color is not None and not is_list_like(color):
axes = self.nseries:
str orientation = "vertical" or self.orientation is None:
Static Protected Member Functions inherited from pandas.plotting._matplotlib.core.MPLPlot
bool _validate_sharex (bool|None sharex, ax, by)
bool|list[tuple[int,...]] _validate_subplots_kwarg (bool|Sequence[Sequence[str]] subplots, Series|DataFrame data, str kind)
Iterator[tuple[Hashable, np.ndarray]] _iter_data (DataFrame|dict[Hashable, Series|DataFrame] data)
bool _has_plotted_object (Axes ax)
_convert_to_ndarray (data)
None _apply_axis_properties (Axis axis, rot=None, int|None fontsize=None)
_get_ax_legend (Axes ax)
tuple[Any, NDFrameT] _parse_errorbars (str label, err, NDFrameT data, int nseries)
Protected Attributes inherited from pandas.plotting._matplotlib.core.MPLPlot
_grouped = data.groupby(unpack_single_str_list(self.by))
bool _rot_set = True
Static Protected Attributes inherited from pandas.plotting._matplotlib.core.MPLPlot
str _layout_type = "vertical"
int _default_rot = 0
bool _need_to_set_index = False
Detailed Description
Definition at line 2048 of file core.py.
Constructor & Destructor Documentation
__init__()
None pandas.plotting._matplotlib.core.PiePlot.__init__ (self, data, kind = None, ** kwargs)
Definition at line 2055 of file core.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_kind()
Literal["pie"] pandas.plotting._matplotlib.core.PiePlot._kind (self) protected
Reimplemented from pandas.plotting._matplotlib.core.MPLPlot.
Definition at line 2050 of file core.py.
_make_plot()
None pandas.plotting._matplotlib.core.PiePlot._make_plot (self, Figure fig) protected
Reimplemented from pandas.plotting._matplotlib.core.MPLPlot.
Definition at line 2080 of file core.py.
_post_plot_logic()
None pandas.plotting._matplotlib.core.PiePlot._post_plot_logic (self, Axes ax, data) protected
Post process for each axes. Overridden in child classes
Reimplemented from pandas.plotting._matplotlib.core.MPLPlot.
Definition at line 2124 of file core.py.
_validate_color_args()
None pandas.plotting._matplotlib.core.PiePlot._validate_color_args (self, color, colormap) protected
Reimplemented from pandas.plotting._matplotlib.core.MPLPlot.
Definition at line 2076 of file core.py.
_validate_log_kwd()
bool | None | Literal["sym"] pandas.plotting._matplotlib.core.PiePlot._validate_log_kwd (cls, str kwd, bool | None | Literal["sym"] value) protected
Reimplemented from pandas.plotting._matplotlib.core.MPLPlot.
Definition at line 2062 of file core.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/plotting/_matplotlib/core.py