Code Cloning Analysis: matplotlib.legend_handler.HandlerBase Class Reference
matplotlib.legend_handler.HandlerBase Class Reference
Public Member Functions
__init__ (self, xpad=0., ypad=0., update_func=None)
update_prop (self, legend_handle, orig_handle, legend)
adjust_drawing_area (self, legend, orig_handle, xdescent, ydescent, width, height, fontsize)
legend_artist (self, legend, orig_handle, fontsize, handlebox)
create_artists (self, legend, orig_handle, xdescent, ydescent, width, height, fontsize, trans)
Protected Member Functions
_update_prop (self, legend_handle, orig_handle)
_default_update_prop (self, legend_handle, orig_handle)
Protected Attributes
_xpad
_ypad = xpad, ypad
_update_prop_func = update_func
Detailed Description
A base class for default legend handlers.
The derived classes are meant to override *create_artists* method, which
has the following signature::
  def create_artists(self, legend, orig_handle,
                     xdescent, ydescent, width, height, fontsize,
                     trans):
The overridden method needs to create artists of the given
transform that fits in the given dimension (xdescent, ydescent,
width, height) that are scaled by fontsize if necessary.
Definition at line 46 of file legend_handler.py.
Constructor & Destructor Documentation
__init__()
matplotlib.legend_handler.HandlerBase.__init__ (self, xpad = 0., ypad = 0., update_func = None)
Parameters
----------
xpad : float, optional
    Padding in x-direction.
ypad : float, optional
    Padding in y-direction.
update_func : callable, optional
    Function for updating the legend handler properties from another
    legend handler, used by `~HandlerBase.update_prop`.
Definition at line 62 of file legend_handler.py.
References _default_update_prop(), _update_prop(), _update_prop_func, _xpad, and _ypad.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_default_update_prop()
matplotlib.legend_handler.HandlerBase._default_update_prop (self, legend_handle, orig_handle) protected
Definition at line 83 of file legend_handler.py.
Referenced by __init__().
_update_prop()
matplotlib.legend_handler.HandlerBase._update_prop (self, legend_handle, orig_handle) protected
Definition at line 77 of file legend_handler.py.
Referenced by __init__().
adjust_drawing_area()
matplotlib.legend_handler.HandlerBase.adjust_drawing_area (self, legend, orig_handle, xdescent, ydescent, width, height, fontsize)
Definition at line 94 of file legend_handler.py.
Referenced by legend_artist().
create_artists()
matplotlib.legend_handler.HandlerBase.create_artists (self, legend, orig_handle, xdescent, ydescent, width, height, fontsize, trans)
Return the legend artists generated.
Parameters
----------
legend : `~matplotlib.legend.Legend`
    The legend for which these legend artists are being created.
orig_handle : `~matplotlib.artist.Artist` or similar
    The object for which these legend artists are being created.
xdescent, ydescent, width, height : int
    The rectangle (*xdescent*, *ydescent*, *width*, *height*) that the
    legend artists being created should fit within.
fontsize : int
    The fontsize in pixels. The legend artists being created should
    be scaled according to the given fontsize.
trans : `~matplotlib.transforms.Transform`
    The transform that is applied to the legend artists being created.
    Typically from unit coordinates in the handler box to screen
    coordinates.
Reimplemented in matplotlib.legend_handler.HandlerErrorbar, matplotlib.legend_handler.HandlerLine2D, matplotlib.legend_handler.HandlerLine2DCompound, matplotlib.legend_handler.HandlerLineCollection, matplotlib.legend_handler.HandlerPatch, matplotlib.legend_handler.HandlerPolyCollection, matplotlib.legend_handler.HandlerRegularPolyCollection, matplotlib.legend_handler.HandlerStem, matplotlib.legend_handler.HandlerStepPatch, and matplotlib.legend_handler.HandlerTuple.
Definition at line 140 of file legend_handler.py.
Referenced by legend_artist().
legend_artist()
matplotlib.legend_handler.HandlerBase.legend_artist (self, legend, orig_handle, fontsize, handlebox)
Return the artist that this HandlerBase generates for the given
original artist/handle.
Parameters
----------
legend : `~matplotlib.legend.Legend`
    The legend for which these legend artists are being created.
orig_handle : :class:`matplotlib.artist.Artist` or similar
    The object for which these legend artists are being created.
fontsize : int
    The fontsize in pixels. The artists being created should
    be scaled according to the given fontsize.
handlebox : `~matplotlib.offsetbox.OffsetBox`
    The box which has been created to hold this legend entry's
    artists. Artists created in the `legend_artist` method must
    be added to this handlebox inside this method.
Definition at line 103 of file legend_handler.py.
References adjust_drawing_area(), and create_artists().
update_prop()
matplotlib.legend_handler.HandlerBase.update_prop (self, legend_handle, orig_handle, legend)
Definition at line 86 of file legend_handler.py.
Referenced by matplotlib.legend_handler.HandlerErrorbar.create_artists(), matplotlib.legend_handler.HandlerLine2D.create_artists(), matplotlib.legend_handler.HandlerLine2DCompound.create_artists(), matplotlib.legend_handler.HandlerLineCollection.create_artists(), matplotlib.legend_handler.HandlerPatch.create_artists(), matplotlib.legend_handler.HandlerPolyCollection.create_artists(), matplotlib.legend_handler.HandlerRegularPolyCollection.create_artists(), matplotlib.legend_handler.HandlerStem.create_artists(), and matplotlib.legend_handler.HandlerStepPatch.create_artists().
Member Data Documentation
_update_prop_func
matplotlib.legend_handler.HandlerBase._update_prop_func = update_func protected
Definition at line 75 of file legend_handler.py.
Referenced by __init__().
_xpad
matplotlib.legend_handler.HandlerBase._xpad protected
Definition at line 74 of file legend_handler.py.
Referenced by __init__().
_ypad
matplotlib.legend_handler.HandlerBase._ypad = xpad, ypad protected
Definition at line 74 of file legend_handler.py.
Referenced by __init__().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/legend_handler.py