Code Cloning Analysis: scipy.fftpack.tests.test_pseudo_diffs.TestOverwrite Class Reference
scipy.fftpack.tests.test_pseudo_diffs.TestOverwrite Class Reference
Public Member Functions
test_diff (self)
test_tilbert (self)
test_itilbert (self)
test_hilbert (self)
test_cs_diff (self)
test_sc_diff (self)
test_ss_diff (self)
test_cc_diff (self)
test_shift (self)
Static Public Attributes
tuple real_dtypes = (np.float32, np.float64)
tuple dtypes = real_dtypes + (np.complex64, np.complex128)
Protected Member Functions
_check (self, x, routine, *args, **kwargs)
_check_1d (self, routine, dtype, shape, *args, **kwargs)
Detailed Description
Check input overwrite behavior
Definition at line 321 of file test_pseudo_diffs.py.
Member Function Documentation
_check()
scipy.fftpack.tests.test_pseudo_diffs.TestOverwrite._check (self, x, routine, * args, ** kwargs) protected
Definition at line 327 of file test_pseudo_diffs.py.
Referenced by scipy.signal.tests.test_ltisys.TestPlacePoles._check().
_check_1d()
scipy.fftpack.tests.test_pseudo_diffs.TestOverwrite._check_1d (self, routine, dtype, shape, * args, ** kwargs) protected
Definition at line 337 of file test_pseudo_diffs.py.
test_cc_diff()
scipy.fftpack.tests.test_pseudo_diffs.TestOverwrite.test_cc_diff (self)
Definition at line 374 of file test_pseudo_diffs.py.
test_cs_diff()
scipy.fftpack.tests.test_pseudo_diffs.TestOverwrite.test_cs_diff (self)
Definition at line 362 of file test_pseudo_diffs.py.
test_diff()
scipy.fftpack.tests.test_pseudo_diffs.TestOverwrite.test_diff (self)
Definition at line 346 of file test_pseudo_diffs.py.
test_hilbert()
scipy.fftpack.tests.test_pseudo_diffs.TestOverwrite.test_hilbert (self)
Definition at line 358 of file test_pseudo_diffs.py.
test_itilbert()
scipy.fftpack.tests.test_pseudo_diffs.TestOverwrite.test_itilbert (self)
Definition at line 354 of file test_pseudo_diffs.py.
test_sc_diff()
scipy.fftpack.tests.test_pseudo_diffs.TestOverwrite.test_sc_diff (self)
Definition at line 366 of file test_pseudo_diffs.py.
test_shift()
scipy.fftpack.tests.test_pseudo_diffs.TestOverwrite.test_shift (self)
Definition at line 378 of file test_pseudo_diffs.py.
test_ss_diff()
scipy.fftpack.tests.test_pseudo_diffs.TestOverwrite.test_ss_diff (self)
Definition at line 370 of file test_pseudo_diffs.py.
test_tilbert()
scipy.fftpack.tests.test_pseudo_diffs.TestOverwrite.test_tilbert (self)
Definition at line 350 of file test_pseudo_diffs.py.
Member Data Documentation
dtypes
tuple scipy.fftpack.tests.test_pseudo_diffs.TestOverwrite.dtypes = real_dtypes + (np.complex64, np.complex128) static
Definition at line 325 of file test_pseudo_diffs.py.
Referenced by scipy.io.matlab._miobase.MatFileReader.__init__(), pandas.core.generic.NDFrame._consolidate(), pandas.core.frame.DataFrame._constructor(), pandas.core.generic.NDFrame._get_cleaned_column_resolvers(), pandas.core.frame.DataFrame.combine_first(), sklearn.externals.array_api_compat.torch._info.__array_namespace_info__.default_dtypes(), pandas.core.frame.DataFrame.dot(), sklearn.externals.array_api_compat.cupy._info.__array_namespace_info__.dtypes(), sklearn.externals.array_api_compat.dask.array._info.__array_namespace_info__.dtypes(), sklearn.externals.array_api_compat.numpy._info.__array_namespace_info__.dtypes(), pandas.core.generic.NDFrame.empty(), scipy.io.matlab._mio4.MatFile4Reader.initialize_read(), pandas.core.frame.DataFrame.quantile(), scipy.io.matlab._mio4.VarReader4.read_header(), and pandas.core.frame.DataFrame.transpose().
real_dtypes
tuple scipy.fftpack.tests.test_pseudo_diffs.TestOverwrite.real_dtypes = (np.float32, np.float64) static
Definition at line 324 of file test_pseudo_diffs.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/fftpack/tests/test_pseudo_diffs.py