Code Cloning Analysis: pandas.tseries.frequencies Namespace Reference
pandas.tseries.frequencies Namespace Reference
Classes
class _FrequencyInferer
class _TimedeltaFrequencyInferer
Functions
str|None get_period_alias (str offset_str)
str|None infer_freq (DatetimeIndex|TimedeltaIndex|Series|DatetimeLikeArrayMixin index)
bool _is_multiple (us, int mult)
str _maybe_add_count (str base, float count)
bool is_subperiod (source, target)
bool is_superperiod (source, target)
str _maybe_coerce_freq (code)
bool _quarter_months_conform (str source, str target)
bool _is_annual (str rule)
bool _is_quarterly (str rule)
bool _is_monthly (str rule)
bool _is_weekly (str rule)
Variables
list _need_suffix = ["QS", "BQE", "BQS", "YS", "BYE", "BYS"]
str key = f"{_prefix}-{_m}"
str _alias = f"{_prefix}-{_m}"
list __all__
Function Documentation
_is_annual()
bool pandas.tseries.frequencies._is_annual (str rule) protected
Definition at line 575 of file frequencies.py.
_is_monthly()
bool pandas.tseries.frequencies._is_monthly (str rule) protected
Definition at line 585 of file frequencies.py.
_is_multiple()
bool pandas.tseries.frequencies._is_multiple (us, int mult) protected
Definition at line 417 of file frequencies.py.
_is_quarterly()
bool pandas.tseries.frequencies._is_quarterly (str rule) protected
Definition at line 580 of file frequencies.py.
_is_weekly()
bool pandas.tseries.frequencies._is_weekly (str rule) protected
Definition at line 590 of file frequencies.py.
_maybe_add_count()
str pandas.tseries.frequencies._maybe_add_count (str base, float count) protected
Definition at line 421 of file frequencies.py.
_maybe_coerce_freq()
str pandas.tseries.frequencies._maybe_coerce_freq (code) protected
we might need to coerce a code to a rule_code
and uppercase it
Parameters
----------
source : str or DateOffset
    Frequency converting from
Returns
-------
str
Definition at line 547 of file frequencies.py.
Referenced by is_subperiod(), and is_superperiod().
_quarter_months_conform()
bool pandas.tseries.frequencies._quarter_months_conform (str source, str target) protected
Definition at line 569 of file frequencies.py.
get_period_alias()
str | None pandas.tseries.frequencies.get_period_alias (str offset_str)
Alias to closest period strings BQ->Q etc.
Definition at line 78 of file frequencies.py.
infer_freq()
str | None pandas.tseries.frequencies.infer_freq (DatetimeIndex | TimedeltaIndex | Series | DatetimeLikeArrayMixin index)
Infer the most likely frequency given the input index.
Parameters
----------
index : DatetimeIndex, TimedeltaIndex, Series or array-like
  If passed a Series will use the values of the series (NOT THE INDEX).
Returns
-------
str or None
    None if no discernible frequency.
Raises
------
TypeError
    If the index is not datetime-like.
ValueError
    If there are fewer than three values.
Examples
--------
>>> idx = pd.date_range(start='2020/12/01', end='2020/12/30', periods=30)
>>> pd.infer_freq(idx)
'D'
Definition at line 89 of file frequencies.py.
is_subperiod()
bool pandas.tseries.frequencies.is_subperiod (source, target)
Returns True if downsampling is possible between source and target
frequencies
Parameters
----------
source : str or DateOffset
    Frequency converting from
target : str or DateOffset
    Frequency converting to
Returns
-------
bool
Definition at line 434 of file frequencies.py.
References _maybe_coerce_freq().
is_superperiod()
bool pandas.tseries.frequencies.is_superperiod (source, target)
Returns True if upsampling is possible between source and target
frequencies
Parameters
----------
source : str or DateOffset
    Frequency converting from
target : str or DateOffset
    Frequency converting to
Returns
-------
bool
Definition at line 489 of file frequencies.py.
References _maybe_coerce_freq().
Variable Documentation
__all__
list pandas.tseries.frequencies.__all__ private
Initial value:
=  [
    "Day",
    "get_period_alias",
    "infer_freq",
    "is_subperiod",
    "is_superperiod",
    "to_offset",
]
Definition at line 595 of file frequencies.py.
_alias
str pandas.tseries.frequencies._alias = f"{_prefix}-{_m}" protected
Definition at line 71 of file frequencies.py.
_need_suffix
list pandas.tseries.frequencies._need_suffix = ["QS", "BQE", "BQS", "YS", "BYE", "BYS"] protected
Definition at line 62 of file frequencies.py.
key
str pandas.tseries.frequencies.key = f"{_prefix}-{_m}"
Definition at line 66 of file frequencies.py.