Code Cloning Analysis: sklearn.multiclass._ConstantPredictor Class Reference
sklearn.multiclass._ConstantPredictor Class Reference
Public Member Functions
fit (self, X, y)
predict (self, X)
decision_function (self, X)
predict_proba (self, X)
Public Member Functions inherited from sklearn.base.BaseEstimator
get_params (self, deep=True)
set_params (self, **params)
__sklearn_clone__ (self)
__repr__ (self, N_CHAR_MAX=700)
__getstate__ (self)
__setstate__ (self, state)
__sklearn_tags__ (self)
Public Member Functions inherited from sklearn.utils._metadata_requests._MetadataRequester
set_fit_request (self, **kwargs)
set_partial_fit_request (self, **kwargs)
set_predict_request (self, **kwargs)
set_predict_proba_request (self, **kwargs)
set_predict_log_proba_request (self, **kwargs)
set_decision_function_request (self, **kwargs)
set_score_request (self, **kwargs)
set_split_request (self, **kwargs)
set_transform_request (self, **kwargs)
set_inverse_transform_request (self, **kwargs)
__init_subclass__ (cls, **kwargs)
get_metadata_routing (self)
Public Attributes
y_ = y
Additional Inherited Members
Protected Member Functions inherited from sklearn.base.BaseEstimator
_get_param_names (cls)
_get_params_html (self, deep=True)
_validate_params (self)
Protected Member Functions inherited from sklearn.utils._repr_html.base.ReprHTMLMixin
_repr_html_ (self)
_repr_html_inner (self)
_repr_mimebundle_ (self, **kwargs)
Protected Member Functions inherited from sklearn.utils._repr_html.base._HTMLDocumentationLinkMixin
_doc_link_template (self)
_doc_link_template (self, value)
_get_doc_link (self)
Protected Member Functions inherited from sklearn.utils._metadata_requests._MetadataRequester
_build_request_for_signature (cls, router, method)
_get_default_requests (cls)
_get_metadata_request (self)
Protected Attributes inherited from sklearn.base.BaseEstimator
_parameter_constraints
Static Protected Attributes inherited from sklearn.base.BaseEstimator
_html_repr = estimator_html_repr
Static Protected Attributes inherited from sklearn.utils._repr_html.base._HTMLDocumentationLinkMixin
str _doc_link_module = "sklearn"
_doc_link_url_param_generator = None
Detailed Description
Helper predictor to be used when only one class is present.
Definition at line 127 of file multiclass.py.
Member Function Documentation
decision_function()
sklearn.multiclass._ConstantPredictor.decision_function (self, X)
Definition at line 154 of file multiclass.py.
Referenced by sklearn.neighbors._lof.LocalOutlierFactor._predict(), sklearn.multiclass.OneVsOneClassifier.predict(), sklearn.svm._base.BaseSVC.predict(), and sklearn.svm._classes.OneClassSVM.score_samples().
fit()
sklearn.multiclass._ConstantPredictor.fit (self, X, y)
Definition at line 130 of file multiclass.py.
Referenced by sklearn.cluster._kmeans._BaseKMeans.fit_predict(), sklearn.neighbors._lof.LocalOutlierFactor.fit_predict(), sklearn.cluster._kmeans._BaseKMeans.fit_transform(), sklearn.neighbors._graph.KNeighborsTransformer.fit_transform(), sklearn.neighbors._graph.RadiusNeighborsTransformer.fit_transform(), sklearn.preprocessing._label.LabelBinarizer.fit_transform(), sklearn.preprocessing._label.MultiLabelBinarizer.fit_transform(), sklearn.tests.metadata_routing_common.ConsumingTransformer.fit_transform(), and sklearn.utils.tests.test_estimator_checks.SparseTransformer.fit_transform().
predict()
sklearn.multiclass._ConstantPredictor.predict (self, X)
Definition at line 140 of file multiclass.py.
Referenced by sklearn.multioutput.MultiOutputClassifier.score().
predict_proba()
sklearn.multiclass._ConstantPredictor.predict_proba (self, X)
Definition at line 168 of file multiclass.py.
Referenced by sklearn.neighbors._classification.KNeighborsClassifier.predict(), sklearn.neighbors._classification.RadiusNeighborsClassifier.predict(), sklearn.semi_supervised._label_propagation.BaseLabelPropagation.predict(), sklearn.multioutput.ClassifierChain.predict_log_proba(), sklearn.neural_network._multilayer_perceptron.MLPClassifier.predict_log_proba(), sklearn.svm._base.BaseSVC.predict_log_proba(), and sklearn.tree._classes.DecisionTreeClassifier.predict_log_proba().
Member Data Documentation
y_
sklearn.multiclass._ConstantPredictor.y_ = y
Definition at line 137 of file multiclass.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/sklearn/multiclass.py