Code Cloning Analysis: fontTools.ttLib.tables.otBase.OverflowErrorRecord Class Reference
fontTools.ttLib.tables.otBase.OverflowErrorRecord Class Reference
Public Member Functions
__init__ (self, overflowTuple)
__repr__ (self)
Public Attributes
tableType = overflowTuple[0]
LookupListIndex = overflowTuple[1]
SubTableIndex = overflowTuple[2]
itemName = overflowTuple[3]
itemIndex = overflowTuple[4]
Detailed Description
Definition at line 28 of file otBase.py.
Constructor & Destructor Documentation
__init__()
fontTools.ttLib.tables.otBase.OverflowErrorRecord.__init__ (self, overflowTuple)
Definition at line 29 of file otBase.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__repr__()
fontTools.ttLib.tables.otBase.OverflowErrorRecord.__repr__ (self)
Definition at line 36 of file otBase.py.
Member Data Documentation
itemIndex
fontTools.ttLib.tables.otBase.OverflowErrorRecord.itemIndex = overflowTuple[4]
Definition at line 34 of file otBase.py.
itemName
fontTools.ttLib.tables.otBase.OverflowErrorRecord.itemName = overflowTuple[3]
Definition at line 33 of file otBase.py.
LookupListIndex
fontTools.ttLib.tables.otBase.OverflowErrorRecord.LookupListIndex = overflowTuple[1]
Definition at line 31 of file otBase.py.
SubTableIndex
fontTools.ttLib.tables.otBase.OverflowErrorRecord.SubTableIndex = overflowTuple[2]
Definition at line 32 of file otBase.py.
tableType
fontTools.ttLib.tables.otBase.OverflowErrorRecord.tableType = overflowTuple[0]
Definition at line 30 of file otBase.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ttLib/tables/otBase.py