Code Cloning Analysis: sklearn.cluster._kmeans Namespace Reference
sklearn.cluster._kmeans Namespace Reference
Classes
class _BaseKMeans
class KMeans
class MiniBatchKMeans
Functions
kmeans_plusplus (X, n_clusters, *, sample_weight=None, x_squared_norms=None, random_state=None, n_local_trials=None)
Initialization heuristic.
_kmeans_plusplus (X, n_clusters, x_squared_norms, sample_weight, random_state, n_local_trials=None)
_tolerance (X, tol)
K-means batch estimation by EM (expectation maximization)
k_means (X, n_clusters, *, sample_weight=None, init="k-means++", n_init="auto", max_iter=300, verbose=False, tol=1e-4, random_state=None, copy_x=True, algorithm="lloyd", return_n_iter=False)
_kmeans_single_elkan (X, sample_weight, centers_init, max_iter=300, verbose=False, tol=1e-4, n_threads=1)
_kmeans_single_lloyd (X, sample_weight, centers_init, max_iter=300, verbose=False, tol=1e-4, n_threads=1)
_labels_inertia (X, sample_weight, centers, n_threads=1, return_inertia=True)
_mini_batch_step (X, sample_weight, centers, centers_new, weight_sums, random_state, random_reassign=False, reassignment_ratio=0.01, verbose=False, n_threads=1)
Variables
_labels_inertia_threadpool_limit
Detailed Description
K-means clustering.
Function Documentation
_kmeans_plusplus()
sklearn.cluster._kmeans._kmeans_plusplus (X, n_clusters, x_squared_norms, sample_weight, random_state, n_local_trials = None) protected
Computational component for initialization of n_clusters by
k-means++. Prior validation of data is assumed.
Parameters
----------
X : {ndarray, sparse matrix} of shape (n_samples, n_features)
    The data to pick seeds for.
n_clusters : int
    The number of seeds to choose.
sample_weight : ndarray of shape (n_samples,)
    The weights for each observation in `X`.
x_squared_norms : ndarray of shape (n_samples,)
    Squared Euclidean norm of each data point.
random_state : RandomState instance
    The generator used to initialize the centers.
    See :term:`Glossary <random_state>`.
n_local_trials : int, default=None
    The number of seeding trials for each center (except the first),
    of which the one reducing inertia the most is greedily chosen.
    Set to None to make the number of trials depend logarithmically
    on the number of seeds (2+log(k)); this is the default.
Returns
-------
centers : ndarray of shape (n_clusters, n_features)
    The initial centers for k-means.
indices : ndarray of shape (n_clusters,)
    The index location of the chosen centers in the data array X. For a
    given index and center, X[index] = center.
Definition at line 174 of file _kmeans.py.
Referenced by sklearn.cluster._kmeans._BaseKMeans._init_centroids(), and kmeans_plusplus().
_kmeans_single_elkan()
sklearn.cluster._kmeans._kmeans_single_elkan (X, sample_weight, centers_init, max_iter = 300, verbose = False, tol = 1e-4, n_threads = 1) protected
A single run of k-means elkan, assumes preparation completed prior.
Parameters
----------
X : {ndarray, sparse matrix} of shape (n_samples, n_features)
    The observations to cluster. If sparse matrix, must be in CSR format.
sample_weight : array-like of shape (n_samples,)
    The weights for each observation in X.
centers_init : ndarray of shape (n_clusters, n_features)
    The initial centers.
max_iter : int, default=300
    Maximum number of iterations of the k-means algorithm to run.
verbose : bool, default=False
    Verbosity mode.
tol : float, default=1e-4
    Relative tolerance with regards to Frobenius norm of the difference
    in the cluster centers of two consecutive iterations to declare
    convergence.
    It's not advised to set `tol=0` since convergence might never be
    declared due to rounding errors. Use a very small number instead.
n_threads : int, default=1
    The number of OpenMP threads to use for the computation. Parallelism is
    sample-wise on the main cython loop which assigns each sample to its
    closest center.
Returns
-------
centroid : ndarray of shape (n_clusters, n_features)
    Centroids found at the last iteration of k-means.
label : ndarray of shape (n_samples,)
    label[i] is the code or index of the centroid the
    i'th observation is closest to.
inertia : float
    The final value of the inertia criterion (sum of squared distances to
    the closest centroid for all observations in the training set).
n_iter : int
    Number of iterations run.
Definition at line 456 of file _kmeans.py.
_kmeans_single_lloyd()
sklearn.cluster._kmeans._kmeans_single_lloyd (X, sample_weight, centers_init, max_iter = 300, verbose = False, tol = 1e-4, n_threads = 1) protected
A single run of k-means lloyd, assumes preparation completed prior.
Parameters
----------
X : {ndarray, sparse matrix} of shape (n_samples, n_features)
    The observations to cluster. If sparse matrix, must be in CSR format.
sample_weight : ndarray of shape (n_samples,)
    The weights for each observation in X.
centers_init : ndarray of shape (n_clusters, n_features)
    The initial centers.
max_iter : int, default=300
    Maximum number of iterations of the k-means algorithm to run.
verbose : bool, default=False
    Verbosity mode
tol : float, default=1e-4
    Relative tolerance with regards to Frobenius norm of the difference
    in the cluster centers of two consecutive iterations to declare
    convergence.
    It's not advised to set `tol=0` since convergence might never be
    declared due to rounding errors. Use a very small number instead.
n_threads : int, default=1
    The number of OpenMP threads to use for the computation. Parallelism is
    sample-wise on the main cython loop which assigns each sample to its
    closest center.
Returns
-------
centroid : ndarray of shape (n_clusters, n_features)
    Centroids found at the last iteration of k-means.
label : ndarray of shape (n_samples,)
    label[i] is the code or index of the centroid the
    i'th observation is closest to.
inertia : float
    The final value of the inertia criterion (sum of squared distances to
    the closest centroid for all observations in the training set).
n_iter : int
    Number of iterations run.
Definition at line 624 of file _kmeans.py.
_labels_inertia()
sklearn.cluster._kmeans._labels_inertia (X, sample_weight, centers, n_threads = 1, return_inertia = True) protected
E step of the K-means EM algorithm.
Compute the labels and the inertia of the given samples and centers.
Parameters
----------
X : {ndarray, sparse matrix} of shape (n_samples, n_features)
    The input samples to assign to the labels. If sparse matrix, must
    be in CSR format.
sample_weight : ndarray of shape (n_samples,)
    The weights for each observation in X.
x_squared_norms : ndarray of shape (n_samples,)
    Precomputed squared euclidean norm of each data point, to speed up
    computations.
centers : ndarray of shape (n_clusters, n_features)
    The cluster centers.
n_threads : int, default=1
    The number of OpenMP threads to use for the computation. Parallelism is
    sample-wise on the main cython loop which assigns each sample to its
    closest center.
return_inertia : bool, default=True
    Whether to compute and return the inertia.
Returns
-------
labels : ndarray of shape (n_samples,)
    The resulting assignment.
inertia : float
    Sum of squared distances of samples to their closest cluster center.
    Inertia is only returned if return_inertia is True.
Definition at line 755 of file _kmeans.py.
Referenced by _mini_batch_step().
_mini_batch_step()
sklearn.cluster._kmeans._mini_batch_step (X, sample_weight, centers, centers_new, weight_sums, random_state, random_reassign = False, reassignment_ratio = 0.01, verbose = False, n_threads = 1) protected
Incremental update of the centers for the Minibatch K-Means algorithm.
Parameters
----------
X : {ndarray, sparse matrix} of shape (n_samples, n_features)
    The original data array. If sparse, must be in CSR format.
x_squared_norms : ndarray of shape (n_samples,)
    Squared euclidean norm of each data point.
sample_weight : ndarray of shape (n_samples,)
    The weights for each observation in `X`.
centers : ndarray of shape (n_clusters, n_features)
    The cluster centers before the current iteration
centers_new : ndarray of shape (n_clusters, n_features)
    The cluster centers after the current iteration. Modified in-place.
weight_sums : ndarray of shape (n_clusters,)
    The vector in which we keep track of the numbers of points in a
    cluster. This array is modified in place.
random_state : RandomState instance
    Determines random number generation for low count centers reassignment.
    See :term:`Glossary <random_state>`.
random_reassign : boolean, default=False
    If True, centers with very low counts are randomly reassigned
    to observations.
reassignment_ratio : float, default=0.01
    Control the fraction of the maximum number of counts for a
    center to be reassigned. A higher value means that low count
    centers are more likely to be reassigned, which means that the
    model will take longer to converge, but should converge in a
    better clustering.
verbose : bool, default=False
    Controls the verbosity.
n_threads : int, default=1
    The number of OpenMP threads to use for the computation.
Returns
-------
inertia : float
    Sum of squared distances of samples to their closest cluster center.
    The inertia is computed after finding the labels and before updating
    the centers.
Definition at line 1557 of file _kmeans.py.
References _labels_inertia().
Referenced by sklearn.cluster._kmeans.MiniBatchKMeans.fit(), and sklearn.cluster._kmeans.MiniBatchKMeans.partial_fit().
_tolerance()
sklearn.cluster._kmeans._tolerance (X, tol) protected
K-means batch estimation by EM (expectation maximization)
Return a tolerance which is dependent on the dataset.
Definition at line 279 of file _kmeans.py.
k_means()
sklearn.cluster._kmeans.k_means (X, n_clusters, * , sample_weight = None, init = "k-means++", n_init = "auto", max_iter = 300, verbose = False, tol = 1e-4, random_state = None, copy_x = True, algorithm = "lloyd", return_n_iter = False)
Perform K-means clustering algorithm.
Read more in the :ref:`User Guide <k_means>`.
Parameters
----------
X : {array-like, sparse matrix} of shape (n_samples, n_features)
    The observations to cluster. It must be noted that the data
    will be converted to C ordering, which will cause a memory copy
    if the given data is not C-contiguous.
n_clusters : int
    The number of clusters to form as well as the number of
    centroids to generate.
sample_weight : array-like of shape (n_samples,), default=None
    The weights for each observation in `X`. If `None`, all observations
    are assigned equal weight. `sample_weight` is not used during
    initialization if `init` is a callable or a user provided array.
init : {'k-means++', 'random'}, callable or array-like of shape \
        (n_clusters, n_features), default='k-means++'
    Method for initialization:
    - `'k-means++'` : selects initial cluster centers for k-mean
      clustering in a smart way to speed up convergence. See section
      Notes in k_init for more details.
    - `'random'`: choose `n_clusters` observations (rows) at random from data
      for the initial centroids.
    - If an array is passed, it should be of shape `(n_clusters, n_features)`
      and gives the initial centers.
    - If a callable is passed, it should take arguments `X`, `n_clusters` and a
      random state and return an initialization.
n_init : 'auto' or int, default="auto"
    Number of time the k-means algorithm will be run with different
    centroid seeds. The final results will be the best output of
    n_init consecutive runs in terms of inertia.
    When `n_init='auto'`, the number of runs depends on the value of init:
    10 if using `init='random'` or `init` is a callable;
    1 if using `init='k-means++'` or `init` is an array-like.
    .. versionadded:: 1.2
       Added 'auto' option for `n_init`.
    .. versionchanged:: 1.4
       Default value for `n_init` changed to `'auto'`.
max_iter : int, default=300
    Maximum number of iterations of the k-means algorithm to run.
verbose : bool, default=False
    Verbosity mode.
tol : float, default=1e-4
    Relative tolerance with regards to Frobenius norm of the difference
    in the cluster centers of two consecutive iterations to declare
    convergence.
random_state : int, RandomState instance or None, default=None
    Determines random number generation for centroid initialization. Use
    an int to make the randomness deterministic.
    See :term:`Glossary <random_state>`.
copy_x : bool, default=True
    When pre-computing distances it is more numerically accurate to center
    the data first. If `copy_x` is True (default), then the original data is
    not modified. If False, the original data is modified, and put back
    before the function returns, but small numerical differences may be
    introduced by subtracting and then adding the data mean. Note that if
    the original data is not C-contiguous, a copy will be made even if
    `copy_x` is False. If the original data is sparse, but not in CSR format,
    a copy will be made even if `copy_x` is False.
algorithm : {"lloyd", "elkan"}, default="lloyd"
    K-means algorithm to use. The classical EM-style algorithm is `"lloyd"`.
    The `"elkan"` variation can be more efficient on some datasets with
    well-defined clusters, by using the triangle inequality. However it's
    more memory intensive due to the allocation of an extra array of shape
    `(n_samples, n_clusters)`.
    .. versionchanged:: 0.18
        Added Elkan algorithm
    .. versionchanged:: 1.1
        Renamed "full" to "lloyd", and deprecated "auto" and "full".
        Changed "auto" to use "lloyd" instead of "elkan".
return_n_iter : bool, default=False
    Whether or not to return the number of iterations.
Returns
-------
centroid : ndarray of shape (n_clusters, n_features)
    Centroids found at the last iteration of k-means.
label : ndarray of shape (n_samples,)
    The `label[i]` is the code or index of the centroid the
    i'th observation is closest to.
inertia : float
    The final value of the inertia criterion (sum of squared distances to
    the closest centroid for all observations in the training set).
best_n_iter : int
    Number of iterations corresponding to the best results.
    Returned only if `return_n_iter` is set to True.
Examples
--------
>>> import numpy as np
>>> from sklearn.cluster import k_means
>>> X = np.array([[1, 2], [1, 4], [1, 0],
...               [10, 2], [10, 4], [10, 0]])
>>> centroid, label, inertia = k_means(
...     X, n_clusters=2, n_init="auto", random_state=0
...)
>>> centroid
array([[10.,  2.],
       [ 1.,  2.]])
>>> label
array([1, 1, 1, 0, 0, 0], dtype=int32)
>>> inertia
16.0
Definition at line 298 of file _kmeans.py.
kmeans_plusplus()
sklearn.cluster._kmeans.kmeans_plusplus (X, n_clusters, * , sample_weight = None, x_squared_norms = None, random_state = None, n_local_trials = None)
Initialization heuristic.
Init n_clusters seeds according to k-means++.
.. versionadded:: 0.24
Parameters
----------
X : {array-like, sparse matrix} of shape (n_samples, n_features)
    The data to pick seeds from.
n_clusters : int
    The number of centroids to initialize.
sample_weight : array-like of shape (n_samples,), default=None
    The weights for each observation in `X`. If `None`, all observations
    are assigned equal weight. `sample_weight` is ignored if `init`
    is a callable or a user provided array.
    .. versionadded:: 1.3
x_squared_norms : array-like of shape (n_samples,), default=None
    Squared Euclidean norm of each data point.
random_state : int or RandomState instance, default=None
    Determines random number generation for centroid initialization. Pass
    an int for reproducible output across multiple function calls.
    See :term:`Glossary <random_state>`.
n_local_trials : int, default=None
    The number of seeding trials for each center (except the first),
    of which the one reducing inertia the most is greedily chosen.
    Set to None to make the number of trials depend logarithmically
    on the number of seeds (2+log(k)) which is the recommended setting.
    Setting to 1 disables the greedy cluster selection and recovers the
    vanilla k-means++ algorithm which was empirically shown to work less
    well than its greedy variant.
Returns
-------
centers : ndarray of shape (n_clusters, n_features)
    The initial centers for k-means.
indices : ndarray of shape (n_clusters,)
    The index location of the chosen centers in the data array X. For a
    given index and center, X[index] = center.
Notes
-----
Selects initial cluster centers for k-mean clustering in a smart way
to speed up convergence. see: Arthur, D. and Vassilvitskii, S.
"k-means++: the advantages of careful seeding". ACM-SIAM symposium
on Discrete algorithms. 2007
Examples
--------
>>> from sklearn.cluster import kmeans_plusplus
>>> import numpy as np
>>> X = np.array([[1, 2], [1, 4], [1, 0],
...               [10, 2], [10, 4], [10, 0]])
>>> centers, indices = kmeans_plusplus(X, n_clusters=2, random_state=0)
>>> centers
array([[10,  2],
       [ 1,  0]])
>>> indices
array([3, 2])
Definition at line 68 of file _kmeans.py.
References _kmeans_plusplus().
Variable Documentation
_labels_inertia_threadpool_limit
sklearn.cluster._kmeans._labels_inertia_threadpool_limit protected
Initial value:
=  _threadpool_controller_decorator(
    limits=1, user_api="blas"
)(_labels_inertia)
Definition at line 826 of file _kmeans.py.