Code Cloning Analysis: sklearn.datasets.tests.test_openml._MockHTTPResponse Class Reference
sklearn.datasets.tests.test_openml._MockHTTPResponse Class Reference
Public Member Functions
__init__ (self, data, is_gzip)
read (self, amt=-1)
close (self)
info (self)
__iter__ (self)
__enter__ (self)
__exit__ (self, exc_type, exc_val, exc_tb)
Public Attributes
data = data
is_gzip = is_gzip
Detailed Description
Definition at line 38 of file test_openml.py.
Constructor & Destructor Documentation
__init__()
sklearn.datasets.tests.test_openml._MockHTTPResponse.__init__ (self, data, is_gzip)
Definition at line 39 of file test_openml.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params().
Member Function Documentation
__enter__()
sklearn.datasets.tests.test_openml._MockHTTPResponse.__enter__ (self)
Definition at line 57 of file test_openml.py.
__exit__()
sklearn.datasets.tests.test_openml._MockHTTPResponse.__exit__ (self, exc_type, exc_val, exc_tb)
Definition at line 60 of file test_openml.py.
__iter__()
sklearn.datasets.tests.test_openml._MockHTTPResponse.__iter__ (self)
Definition at line 54 of file test_openml.py.
close()
sklearn.datasets.tests.test_openml._MockHTTPResponse.close (self)
Definition at line 46 of file test_openml.py.
info()
sklearn.datasets.tests.test_openml._MockHTTPResponse.info (self)
Definition at line 49 of file test_openml.py.
Referenced by pandas.io.formats.info._TableBuilderAbstract.display_memory_usage(), pandas.io.formats.info._TableBuilderAbstract.dtype_counts(), pandas.io.formats.info._TableBuilderAbstract.dtypes(), pandas.io.formats.info._TableBuilderAbstract.get_lines(), and pandas.io.formats.info._TableBuilderAbstract.memory_usage_string().
read()
sklearn.datasets.tests.test_openml._MockHTTPResponse.read (self, amt = -1)
Definition at line 43 of file test_openml.py.
Member Data Documentation
data
sklearn.datasets.tests.test_openml._MockHTTPResponse.data = data
Definition at line 40 of file test_openml.py.
Referenced by pandas.tests.extension.decimal.array.DecimalArray._reduce(), matplotlib.backends.backend_svg.XMLWriter.element(), numpy.core._internal._ctypes.get_data(), and PIL.GifImagePlugin.GifImageFile.seek().
is_gzip
sklearn.datasets.tests.test_openml._MockHTTPResponse.is_gzip = is_gzip
Definition at line 41 of file test_openml.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/sklearn/datasets/tests/test_openml.py