Code Cloning Analysis: matplotlib.backends.backend_pgf Namespace Reference
matplotlib.backends.backend_pgf Namespace Reference
Classes
class _BackendPgf
class FigureCanvasPgf
class LatexError
class LatexManager
class PdfPages
class RendererPgf
Functions
_get_preamble ()
_tex_escape (text)
_writeln (fh, line)
_escape_and_apply_props (s, prop)
_metadata_to_str (key, value)
make_pdf_to_png_converter ()
_get_image_inclusion_command ()
Variables
_log = logging.getLogger(__name__)
str _DOCUMENTCLASS = r"\documentclass{article}"
int latex_pt_to_in = 1. / 72.27
int latex_in_to_pt = 1. / latex_pt_to_in
int mpl_pt_to_in = 1. / 72.
int mpl_in_to_pt = 1. / mpl_pt_to_in
FigureManagerPgf = FigureManagerBase
Function Documentation
_escape_and_apply_props()
matplotlib.backends.backend_pgf._escape_and_apply_props (s, prop) protected
Generate a TeX string that renders string *s* with font properties *prop*,
also applying any required escapes to *s*.
Definition at line 103 of file backend_pgf.py.
References _tex_escape().
Referenced by matplotlib.backends.backend_pgf.RendererPgf.draw_text(), and matplotlib.backends.backend_pgf.LatexManager.get_width_height_descent().
_get_image_inclusion_command()
matplotlib.backends.backend_pgf._get_image_inclusion_command () protected
Definition at line 351 of file backend_pgf.py.
_get_preamble()
matplotlib.backends.backend_pgf._get_preamble () protected
Prepare a LaTeX preamble based on the rcParams configuration.
Definition at line 39 of file backend_pgf.py.
Referenced by matplotlib.backends.backend_pgf.PdfPages.__init__(), matplotlib.backends.backend_pgf.FigureCanvasPgf.get_default_filetype(), and matplotlib.backends.backend_pgf.FigureCanvasPgf.print_pdf().
_metadata_to_str()
matplotlib.backends.backend_pgf._metadata_to_str (key, value) protected
Convert metadata key/value to a form that hyperref accepts.
Definition at line 148 of file backend_pgf.py.
Referenced by matplotlib.backends.backend_pgf.PdfPages.__init__(), and matplotlib.backends.backend_pgf.FigureCanvasPgf.print_pdf().
_tex_escape()
matplotlib.backends.backend_pgf._tex_escape (text) protected
Do some necessary and/or useful substitutions for texts to be included in
LaTeX documents.
Definition at line 88 of file backend_pgf.py.
Referenced by _escape_and_apply_props().
_writeln()
matplotlib.backends.backend_pgf._writeln (fh, line) protected
Definition at line 96 of file backend_pgf.py.
make_pdf_to_png_converter()
matplotlib.backends.backend_pgf.make_pdf_to_png_converter ()
Return a function that converts a pdf file to a png file.
Definition at line 159 of file backend_pgf.py.
Referenced by matplotlib.backends.backend_pgf.FigureCanvasPgf.print_png().
Variable Documentation
_DOCUMENTCLASS
str matplotlib.backends.backend_pgf._DOCUMENTCLASS = r"\documentclass{article}" protected
Definition at line 32 of file backend_pgf.py.
_log
matplotlib.backends.backend_pgf._log = logging.getLogger(__name__) protected
Definition at line 29 of file backend_pgf.py.
FigureManagerPgf
matplotlib.backends.backend_pgf.FigureManagerPgf = FigureManagerBase
Definition at line 877 of file backend_pgf.py.
latex_in_to_pt
int matplotlib.backends.backend_pgf.latex_in_to_pt = 1. / latex_pt_to_in
Definition at line 83 of file backend_pgf.py.
latex_pt_to_in
int matplotlib.backends.backend_pgf.latex_pt_to_in = 1. / 72.27
Definition at line 82 of file backend_pgf.py.
mpl_in_to_pt
int matplotlib.backends.backend_pgf.mpl_in_to_pt = 1. / mpl_pt_to_in
Definition at line 85 of file backend_pgf.py.
mpl_pt_to_in
int matplotlib.backends.backend_pgf.mpl_pt_to_in = 1. / 72.
Definition at line 84 of file backend_pgf.py.