Code Cloning Analysis: pip._internal.metadata.importlib._compat.BasePath Class Reference
pip._internal.metadata.importlib._compat.BasePath Class Reference
Public Member Functions
str name (self)
"BasePath" parent (self)
Detailed Description
A protocol that various path objects conform.
This exists because importlib.metadata uses both ``pathlib.Path`` and
``zipfile.Path``, and we need a common base for type hints (Union does not
work well since ``zipfile.Path`` is too new for our linter setup).
This does not mean to be exhaustive, but only contains things that present
in both classes *that we need*.
Definition at line 14 of file _compat.py.
Member Function Documentation
name()
str pip._internal.metadata.importlib._compat.BasePath.name (self)
Definition at line 26 of file _compat.py.
Referenced by pip._vendor.pyparsing.core.Regex.__init__(), pip._vendor.distro.distro.LinuxDistribution.linux_distribution(), and pip._internal.resolution.resolvelib.requirements.SpecifierRequirement.name().
parent()
"BasePath" pip._internal.metadata.importlib._compat.BasePath.parent (self)
Definition at line 30 of file _compat.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_compat.py