Code Cloning Analysis: pip._vendor.cachecontrol.caches.file_cache._FileCacheMixin Class Reference
pip._vendor.cachecontrol.caches.file_cache._FileCacheMixin Class Reference
Public Member Functions
None __init__ (self, str directory, bool forever=False, int filemode=0o0600, int dirmode=0o0700, type[BaseFileLock]|None lock_class=None)
bytes|None get (self, str key)
None set (self, str key, bytes value, int|datetime|None expires=None)
Static Public Member Functions
str encode (str x)
Public Attributes
directory = directory
forever = forever
filemode = filemode
dirmode = dirmode
lock_class = lock_class
Protected Member Functions
str _fn (self, str name)
None _write (self, str path, bytes data)
None _delete (self, str key, str suffix)
Detailed Description
Shared implementation for both FileCache variants.
Definition at line 61 of file file_cache.py.
Constructor & Destructor Documentation
__init__()
None pip._vendor.cachecontrol.caches.file_cache._FileCacheMixin.__init__ (self, str directory, bool forever = False, int filemode = 0o0600, int dirmode = 0o0700, type[BaseFileLock] | None lock_class = None)
Definition at line 64 of file file_cache.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
_delete()
None pip._vendor.cachecontrol.caches.file_cache._FileCacheMixin._delete (self, str key, str suffix) protected
Definition at line 134 of file file_cache.py.
Referenced by pip._vendor.cachecontrol.caches.file_cache.SeparateBodyFileCache.get_body().
_fn()
str pip._vendor.cachecontrol.caches.file_cache._FileCacheMixin._fn (self, str name) protected
Definition at line 97 of file file_cache.py.
Referenced by _write(), and pip._vendor.cachecontrol.caches.file_cache.SeparateBodyFileCache.get_body().
_write()
None pip._vendor.cachecontrol.caches.file_cache._FileCacheMixin._write (self, str path, bytes data) protected
Safely write the data to the given path.
Definition at line 119 of file file_cache.py.
References _fn(), dirmode, filemode, forever, and lock_class.
Referenced by scipy.io._netcdf.netcdf_file.flush(), pip._vendor.cachecontrol.caches.file_cache.SeparateBodyFileCache.get_body(), and scipy.io._mmio.MMFile.write().
encode()
str pip._vendor.cachecontrol.caches.file_cache._FileCacheMixin.encode (str x) static
Definition at line 94 of file file_cache.py.
get()
bytes | None pip._vendor.cachecontrol.caches.file_cache._FileCacheMixin.get (self, str key)
Definition at line 104 of file file_cache.py.
Referenced by scipy._lib._docscrape.NumpyDocString._parse_summary(), pip._vendor.distlib.metadata.LegacyMetadata.check(), pip._vendor.rich.layout.Layout.get(), fontTools.misc.macRes.ResourceReader.getNamedResource(), fontTools.misc.macRes.ResourceReader.getNames(), and pip._vendor.distlib.metadata.LegacyMetadata.write_file().
set()
None pip._vendor.cachecontrol.caches.file_cache._FileCacheMixin.set (self, str key, bytes value, int | datetime | None expires = None)
Definition at line 113 of file file_cache.py.
Referenced by matplotlib.contour.ContourSet.__init__(), pip._vendor.requests.cookies.RequestsCookieJar.__setitem__(), matplotlib.axes._base._AxesBase._set_view(), mplot3d.axes3d.Axes3D._set_view(), matplotlib.axes._axes.Axes.pie(), pip._vendor.distlib.metadata.LegacyMetadata.read_file(), numpy.core.tests.test_simd._SIMD_ALL.test_lut(), and pip._vendor.distlib.metadata.LegacyMetadata.update().
Member Data Documentation
directory
pip._vendor.cachecontrol.caches.file_cache._FileCacheMixin.directory = directory
Definition at line 87 of file file_cache.py.
dirmode
pip._vendor.cachecontrol.caches.file_cache._FileCacheMixin.dirmode = dirmode
Definition at line 90 of file file_cache.py.
Referenced by _write().
filemode
pip._vendor.cachecontrol.caches.file_cache._FileCacheMixin.filemode = filemode
Definition at line 89 of file file_cache.py.
Referenced by _write().
forever
pip._vendor.cachecontrol.caches.file_cache._FileCacheMixin.forever = forever
Definition at line 88 of file file_cache.py.
Referenced by _write().
lock_class
pip._vendor.cachecontrol.caches.file_cache._FileCacheMixin.lock_class = lock_class
Definition at line 91 of file file_cache.py.
Referenced by _write().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pip/_vendor/cachecontrol/caches/file_cache.py