Code Cloning Analysis: pip._vendor.chardet.mbcharsetprober.MultiByteCharSetProber Class Reference
pip._vendor.chardet.mbcharsetprober.MultiByteCharSetProber Class Reference
Public Member Functions
None __init__ (self, LanguageFilter lang_filter=LanguageFilter.NONE)
None reset (self)
ProbingState feed (self, Union[bytes, bytearray] byte_str)
float get_confidence (self)
Public Member Functions inherited from pip._vendor.chardet.charsetprober.CharSetProber
None __init__ (self, LanguageFilter lang_filter=LanguageFilter.NONE)
Optional[str] charset_name (self)
Optional[str] language (self)
ProbingState state (self)
Public Attributes
Optional[CharDistributionAnalysis] distribution_analyzer = None
Optional[CodingStateMachine] coding_sm = None
Public Attributes inherited from pip._vendor.chardet.charsetprober.CharSetProber
bool active = True
lang_filter = lang_filter
logger = logging.getLogger(__name__)
Protected Attributes
_last_char = bytearray(b"\0\0")
Protected Attributes inherited from pip._vendor.chardet.charsetprober.CharSetProber
_state = ProbingState.DETECTING
Additional Inherited Members
Static Public Member Functions inherited from pip._vendor.chardet.charsetprober.CharSetProber
bytes filter_high_byte_only (Union[bytes, bytearray] buf)
bytearray filter_international_words (Union[bytes, bytearray] buf)
bytes remove_xml_tags (Union[bytes, bytearray] buf)
Static Public Attributes inherited from pip._vendor.chardet.charsetprober.CharSetProber
float SHORTCUT_THRESHOLD = 0.95
Detailed Description
MultiByteCharSetProber
Definition at line 38 of file mbcharsetprober.py.
Constructor & Destructor Documentation
__init__()
None pip._vendor.chardet.mbcharsetprober.MultiByteCharSetProber.__init__ (self, LanguageFilter lang_filter = LanguageFilter.NONE)
Definition at line 43 of file mbcharsetprober.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
feed()
ProbingState pip._vendor.chardet.mbcharsetprober.MultiByteCharSetProber.feed (self, Union[bytes, bytearray] byte_str)
Reimplemented from pip._vendor.chardet.charsetprober.CharSetProber.
Definition at line 57 of file mbcharsetprober.py.
get_confidence()
float pip._vendor.chardet.mbcharsetprober.MultiByteCharSetProber.get_confidence (self)
Reimplemented from pip._vendor.chardet.charsetprober.CharSetProber.
Definition at line 93 of file mbcharsetprober.py.
reset()
None pip._vendor.chardet.mbcharsetprober.MultiByteCharSetProber.reset (self)
Reimplemented from pip._vendor.chardet.charsetprober.CharSetProber.
Definition at line 49 of file mbcharsetprober.py.
Referenced by scipy._lib._docscrape.Reader.__init__().
Member Data Documentation
_last_char
pip._vendor.chardet.mbcharsetprober.MultiByteCharSetProber._last_char = bytearray(b"\0\0") protected
Definition at line 47 of file mbcharsetprober.py.
Referenced by pip._vendor.chardet.universaldetector.UniversalDetector.feed(), and pip._vendor.chardet.universaldetector.UniversalDetector.reset().
coding_sm
Optional[CodingStateMachine] pip._vendor.chardet.mbcharsetprober.MultiByteCharSetProber.coding_sm = None
Definition at line 46 of file mbcharsetprober.py.
distribution_analyzer
Optional[CharDistributionAnalysis] pip._vendor.chardet.mbcharsetprober.MultiByteCharSetProber.distribution_analyzer = None
Definition at line 45 of file mbcharsetprober.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pip/_vendor/chardet/mbcharsetprober.py