Code Cloning Analysis: joblib.func_inspect Namespace Reference
joblib.func_inspect Namespace Reference
Functions
get_func_code (func)
_clean_win_chars (string)
get_func_name (func, resolv_alias=True, win_characters=True)
_signature_str (function_name, arg_sig)
_function_called_str (function_name, args, kwargs)
filter_args (func, ignore_lst, args=(), kwargs=dict())
_format_arg (arg)
format_signature (func, *args, **kwargs)
format_call (func, args, kwargs, object_name="Memory")
Variables
tuple full_argspec_fields
full_argspec_type = collections.namedtuple("FullArgSpec", full_argspec_fields)
Detailed Description
My own variation on function-specific inspect-like features.
Function Documentation
_clean_win_chars()
joblib.func_inspect._clean_win_chars (string) protected
Windows cannot encode some characters in filename.
Definition at line 82 of file func_inspect.py.
Referenced by get_func_name().
_format_arg()
joblib.func_inspect._format_arg (arg) protected
Definition at line 340 of file func_inspect.py.
_function_called_str()
joblib.func_inspect._function_called_str (function_name, args, kwargs) protected
Helper function to output a function call
Definition at line 193 of file func_inspect.py.
Referenced by filter_args().
_signature_str()
joblib.func_inspect._signature_str (function_name, arg_sig) protected
Helper function to output a function signature
Definition at line 188 of file func_inspect.py.
Referenced by filter_args().
filter_args()
joblib.func_inspect.filter_args (func, ignore_lst, args = (), kwargs = dict())
Filters the given args and kwargs using a list of arguments to
ignore, and a function specification.
Parameters
----------
func: callable
    Function giving the argument specification
ignore_lst: list of strings
    List of arguments to ignore (either a name of an argument
    in the function spec, or '*', or '**')
*args: list
    Positional arguments passed to the function.
**kwargs: dict
    Keyword arguments passed to the function
Returns
-------
filtered_args: list
    List of filtered positional and keyword arguments.
Definition at line 202 of file func_inspect.py.
References _function_called_str(), _signature_str(), and get_func_name().
format_call()
joblib.func_inspect.format_call (func, args, kwargs, object_name = "Memory")
Returns a nicely formatted statement displaying the function
call with the given arguments.
Definition at line 371 of file func_inspect.py.
format_signature()
joblib.func_inspect.format_signature (func, * args, ** kwargs)
Definition at line 347 of file func_inspect.py.
get_func_code()
joblib.func_inspect.get_func_code (func)
Attempts to retrieve a reliable function code hash.
The reason we don't use inspect.getsource is that it caches the
source, whereas we want this to be modified on the fly when the
function is modified.
Returns
-------
func_code: string
    The function code
source_file: string
    The path to the file in which the function is defined.
first_line: int
    The first line of the code in the source file.
Notes
------
This function does a bit more magic than inspect, and is thus
more robust.
Definition at line 25 of file func_inspect.py.
get_func_name()
joblib.func_inspect.get_func_name (func, resolv_alias = True, win_characters = True)
Return the function import path (as a list of module names), and
a name for the function.
Parameters
----------
func: callable
    The func to inspect
resolv_alias: boolean, optional
    If true, possible local aliases are indicated.
win_characters: boolean, optional
    If true, substitute special characters using urllib.quote
    This is useful in Windows, as it cannot encode some filenames
Definition at line 98 of file func_inspect.py.
References _clean_win_chars().
Referenced by filter_args().
Variable Documentation
full_argspec_fields
tuple joblib.func_inspect.full_argspec_fields
Initial value:
=  (
    "args varargs varkw defaults kwonlyargs kwonlydefaults annotations"
)
Definition at line 19 of file func_inspect.py.
full_argspec_type
joblib.func_inspect.full_argspec_type = collections.namedtuple("FullArgSpec", full_argspec_fields)
Definition at line 22 of file func_inspect.py.