Code Cloning Analysis: PIL.ImageMorph.LutBuilder Class Reference
PIL.ImageMorph.LutBuilder Class Reference
Public Member Functions
None __init__ (self, list[str]|None patterns=None, str|None op_name=None)
None add_patterns (self, list[str] patterns)
None build_default_lut (self)
bytearray|None get_lut (self)
bytearray build_lut (self)
Public Attributes
list patterns = patterns
bytearray|None lut = None
Protected Member Functions
str _string_permute (self, str pattern, list[int] permutation)
list[tuple[str, int]] _pattern_permute (self, str basic_pattern, str options, int basic_result)
Detailed Description
A class for building a MorphLut from a descriptive language
The input patterns is a list of a strings sequences like these::
    4:(...
       .1.
       111)->1
(whitespaces including linebreaks are ignored). The option 4
describes a series of symmetry operations (in this case a
4-rotation), the pattern is described by:
- . or X - Ignore
- 1 - Pixel is on
- 0 - Pixel is off
The result of the operation is described after "->" string.
The default is to return the current pixel value, which is
returned if no other match is found.
Operations:
- 4 - 4 way rotation
- N - Negate
- 1 - Dummy op for no other operation (an op must always be given)
- M - Mirroring
Example::
    lb = LutBuilder(patterns = ["4:(... .1. 111)->1"])
    lut = lb.build_lut()
Definition at line 29 of file ImageMorph.py.
Constructor & Destructor Documentation
__init__()
None PIL.ImageMorph.LutBuilder.__init__ (self, list[str] | None patterns = None, str | None op_name = None)
Definition at line 65 of file ImageMorph.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
_pattern_permute()
list[tuple[str, int]] PIL.ImageMorph.LutBuilder._pattern_permute (self, str basic_pattern, str options, int basic_result) protected
pattern_permute takes a basic pattern and its result and clones
the pattern according to the modifications described in the $options
parameter. It returns a list of all cloned patterns.
Definition at line 110 of file ImageMorph.py.
References _string_permute().
Referenced by build_lut().
_string_permute()
str PIL.ImageMorph.LutBuilder._string_permute (self, str pattern, list[int] permutation) protected
string_permute takes a pattern and a permutation and returns the
string permuted according to the permutation list.
Definition at line 103 of file ImageMorph.py.
Referenced by _pattern_permute().
add_patterns()
None PIL.ImageMorph.LutBuilder.add_patterns (self, list[str] patterns)
Definition at line 92 of file ImageMorph.py.
build_default_lut()
None PIL.ImageMorph.LutBuilder.build_default_lut (self)
Definition at line 95 of file ImageMorph.py.
Referenced by build_lut().
build_lut()
bytearray PIL.ImageMorph.LutBuilder.build_lut (self)
Compile all patterns into a morphology lut.
TBD :Build based on (file) morphlut:modify_lut
Definition at line 142 of file ImageMorph.py.
References _pattern_permute(), build_default_lut(), lut, and patterns.
get_lut()
bytearray | None PIL.ImageMorph.LutBuilder.get_lut (self)
Definition at line 100 of file ImageMorph.py.
Member Data Documentation
lut
bytearray | None PIL.ImageMorph.LutBuilder.lut = None
Definition at line 72 of file ImageMorph.py.
Referenced by matplotlib.colors.BivarColormap._repr_png_(), and build_lut().
patterns
list PIL.ImageMorph.LutBuilder.patterns = patterns
Definition at line 69 of file ImageMorph.py.
Referenced by build_lut().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/PIL/ImageMorph.py