Code Cloning Analysis: fontTools.ttLib.tables._h_m_t_x.table__h_m_t_x Class Reference
fontTools.ttLib.tables._h_m_t_x.table__h_m_t_x Class Reference
Public Member Functions
decompile (self, data, ttFont)
compile (self, ttFont)
toXML (self, writer, ttFont)
fromXML (self, name, attrs, content, ttFont)
__delitem__ (self, glyphName)
__getitem__ (self, glyphName)
__setitem__ (self, glyphName, advance_sb_pair)
Public Member Functions inherited from fontTools.ttLib.tables.DefaultTable.DefaultTable
__init__ (self, tag=None)
__repr__ (self)
__eq__ (self, other)
__ne__ (self, other)
Public Attributes
dict metrics = {}
Public Attributes inherited from fontTools.ttLib.tables.DefaultTable.DefaultTable
tableTag = Tag(tag)
data = data
ERROR
Static Public Attributes
str headerTag = "hhea"
str advanceName = "width"
str sideBearingName = "lsb"
str numberOfMetricsName = "numberOfHMetrics"
str longMetricFormat = "Hh"
Static Public Attributes inherited from fontTools.ttLib.tables.DefaultTable.DefaultTable
list dependencies = []
Detailed Description
Horizontal Metrics table
The ``hmtx`` table contains per-glyph metrics for the glyphs in a
``glyf``, ``CFF ``, or ``CFF2`` table, as needed for horizontal text
layout.
See also https://learn.microsoft.com/en-us/typography/opentype/spec/hmtx
Definition at line 14 of file _h_m_t_x.py.
Member Function Documentation
__delitem__()
fontTools.ttLib.tables._h_m_t_x.table__h_m_t_x.__delitem__ (self, glyphName)
Definition at line 153 of file _h_m_t_x.py.
__getitem__()
fontTools.ttLib.tables._h_m_t_x.table__h_m_t_x.__getitem__ (self, glyphName)
Definition at line 156 of file _h_m_t_x.py.
__setitem__()
fontTools.ttLib.tables._h_m_t_x.table__h_m_t_x.__setitem__ (self, glyphName, advance_sb_pair)
Definition at line 159 of file _h_m_t_x.py.
compile()
fontTools.ttLib.tables._h_m_t_x.table__h_m_t_x.compile (self, ttFont)
Reimplemented from fontTools.ttLib.tables.DefaultTable.DefaultTable.
Definition at line 78 of file _h_m_t_x.py.
Referenced by fontTools.ttLib.tables.TupleVariation.TupleVariation.getCoordWidth(), and PIL.FontFile.FontFile.save().
decompile()
fontTools.ttLib.tables._h_m_t_x.table__h_m_t_x.decompile (self, data, ttFont)
Reimplemented from fontTools.ttLib.tables.DefaultTable.DefaultTable.
Definition at line 30 of file _h_m_t_x.py.
Referenced by fontTools.ttLib.tables._c_m_a_p.CmapSubtable.newSubtable().
fromXML()
fontTools.ttLib.tables._h_m_t_x.table__h_m_t_x.fromXML (self, name, attrs, content, ttFont)
Reimplemented from fontTools.ttLib.tables.DefaultTable.DefaultTable.
Definition at line 144 of file _h_m_t_x.py.
toXML()
fontTools.ttLib.tables._h_m_t_x.table__h_m_t_x.toXML (self, writer, ttFont)
Reimplemented from fontTools.ttLib.tables.DefaultTable.DefaultTable.
Definition at line 130 of file _h_m_t_x.py.
Member Data Documentation
advanceName
fontTools.ttLib.tables._h_m_t_x.table__h_m_t_x.advanceName = "width" static
Definition at line 25 of file _h_m_t_x.py.
headerTag
fontTools.ttLib.tables._h_m_t_x.table__h_m_t_x.headerTag = "hhea" static
Definition at line 24 of file _h_m_t_x.py.
longMetricFormat
str fontTools.ttLib.tables._h_m_t_x.table__h_m_t_x.longMetricFormat = "Hh" static
Definition at line 28 of file _h_m_t_x.py.
metrics
dict fontTools.ttLib.tables._h_m_t_x.table__h_m_t_x.metrics = {}
Definition at line 59 of file _h_m_t_x.py.
Referenced by PIL.FontFile.FontFile.compile(), and PIL.FontFile.FontFile.save().
numberOfMetricsName
fontTools.ttLib.tables._h_m_t_x.table__h_m_t_x.numberOfMetricsName = "numberOfHMetrics" static
Definition at line 27 of file _h_m_t_x.py.
sideBearingName
fontTools.ttLib.tables._h_m_t_x.table__h_m_t_x.sideBearingName = "lsb" static
Definition at line 26 of file _h_m_t_x.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ttLib/tables/_h_m_t_x.py