Code Cloning Analysis: fontTools.feaLib.ast.GlyphClassDefStatement Class Reference
fontTools.feaLib.ast.GlyphClassDefStatement Class Reference
Public Member Functions
__init__ (self, baseGlyphs, markGlyphs, ligatureGlyphs, componentGlyphs, location=None)
build (self, builder)
asFea (self, indent="")
Public Member Functions inherited from fontTools.feaLib.ast.Element
__init__ (self, location=None)
__str__ (self)
Public Attributes
baseGlyphs
tuple markGlyphs = (baseGlyphs, markGlyphs)
ligatureGlyphs = ligatureGlyphs
componentGlyphs = componentGlyphs
Public Attributes inherited from fontTools.feaLib.ast.Element
location = location
Detailed Description
Example: ``GlyphClassDef @UPPERCASE, [B], [C], [D];``. The parameters
must be either :class:`GlyphClass` or :class:`GlyphClassName` objects, or
``None``.
Definition at line 480 of file ast.py.
Constructor & Destructor Documentation
__init__()
fontTools.feaLib.ast.GlyphClassDefStatement.__init__ (self, baseGlyphs, markGlyphs, ligatureGlyphs, componentGlyphs, location = None)
Definition at line 485 of file ast.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
asFea()
fontTools.feaLib.ast.GlyphClassDefStatement.asFea (self, indent = "")
Returns this element as a string of feature code. For block-type
elements (such as :class:`FeatureBlock`), the `indent` string is
added to the start of each line in the output.
Reimplemented from fontTools.feaLib.ast.Element.
Definition at line 501 of file ast.py.
References asFea(), baseGlyphs, componentGlyphs, ligatureGlyphs, and markGlyphs.
Referenced by asFea().
build()
fontTools.feaLib.ast.GlyphClassDefStatement.build (self, builder)
Calls the builder's ``add_glyphClassDef`` callback.
Reimplemented from fontTools.feaLib.ast.Element.
Definition at line 493 of file ast.py.
References baseGlyphs, componentGlyphs, ligatureGlyphs, fontTools.feaLib.ast.Element.location, and markGlyphs.
Member Data Documentation
baseGlyphs
fontTools.feaLib.ast.GlyphClassDefStatement.baseGlyphs
Definition at line 489 of file ast.py.
Referenced by asFea(), and build().
componentGlyphs
fontTools.feaLib.ast.GlyphClassDefStatement.componentGlyphs = componentGlyphs
Definition at line 491 of file ast.py.
Referenced by asFea(), and build().
ligatureGlyphs
fontTools.feaLib.ast.GlyphClassDefStatement.ligatureGlyphs = ligatureGlyphs
Definition at line 490 of file ast.py.
Referenced by asFea(), and build().
markGlyphs
tuple fontTools.feaLib.ast.GlyphClassDefStatement.markGlyphs = (baseGlyphs, markGlyphs)
Definition at line 489 of file ast.py.
Referenced by asFea(), and build().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/feaLib/ast.py