Code Cloning Analysis: pytz.UTC Class Reference
pytz.UTC Class Reference
Public Member Functions
fromutc (self, dt)
utcoffset (self, dt)
tzname (self, dt)
dst (self, dt)
__reduce__ (self)
localize (self, dt, is_dst=False)
normalize (self, dt, is_dst=False)
__repr__ (self)
__str__ (self)
Public Member Functions inherited from pytz.tzinfo.BaseTzInfo
__str__ (self)
Static Protected Attributes
_dst = ZERO
Static Protected Attributes inherited from pytz.tzinfo.BaseTzInfo
_utcoffset = None
_tzname = None
Additional Inherited Members
Static Public Attributes inherited from pytz.tzinfo.BaseTzInfo
zone = None
Detailed Description
UTC
Optimized UTC implementation. It unpickles using the single module global
instance defined beneath this class declaration.
Definition at line 213 of file __init__.py.
Member Function Documentation
__reduce__()
pytz.UTC.__reduce__ (self)
Definition at line 239 of file __init__.py.
__repr__()
pytz.UTC.__repr__ (self)
Definition at line 256 of file __init__.py.
__str__()
pytz.UTC.__str__ (self)
Definition at line 259 of file __init__.py.
dst()
pytz.UTC.dst (self, dt)
Definition at line 236 of file __init__.py.
fromutc()
pytz.UTC.fromutc (self, dt)
Definition at line 225 of file __init__.py.
Referenced by pytz.tzinfo.DstTzInfo.normalize().
localize()
pytz.UTC.localize (self, dt, is_dst = False)
Convert naive time to local time
Definition at line 242 of file __init__.py.
Referenced by pytz.tzinfo.DstTzInfo.dst(), pytz.tzinfo.DstTzInfo.localize(), pytz.tzinfo.DstTzInfo.tzname(), and pytz.tzinfo.DstTzInfo.utcoffset().
normalize()
pytz.UTC.normalize (self, dt, is_dst = False)
Correct the timezone information on the given datetime
Definition at line 248 of file __init__.py.
tzname()
pytz.UTC.tzname (self, dt)
Definition at line 233 of file __init__.py.
utcoffset()
pytz.UTC.utcoffset (self, dt)
Definition at line 230 of file __init__.py.
Member Data Documentation
_dst
pytz.UTC._dst = ZERO static protected
Definition at line 222 of file __init__.py.
Referenced by pytz.tzinfo.DstTzInfo.dst(), and pytz.tzinfo.DstTzInfo.tzname().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pytz/__init__.py