Code Cloning Analysis: matplotlib._mathtext.Hrule Class Reference
matplotlib._mathtext.Hrule Class Reference
Public Member Functions
__init__ (self, ParserState state, float|None thickness=None)
Public Member Functions inherited from matplotlib._mathtext.Rule
__init__ (self, float width, float height, float depth, ParserState state)
None render (self, Output output, float x, float y, float w, float h)
Public Member Functions inherited from matplotlib._mathtext.Box
None __init__ (self, float width, float height, float depth)
None shrink (self)
Public Member Functions inherited from matplotlib._mathtext.Node
None __init__ (self)
str __repr__ (self)
float get_kerning (self, Node|None next)
Additional Inherited Members
Public Attributes inherited from matplotlib._mathtext.Rule
fontset = state.fontset
Public Attributes inherited from matplotlib._mathtext.Box
width = width
height = height
depth = depth
Public Attributes inherited from matplotlib._mathtext.Node
int size = 0
Detailed Description
Convenience class to create a horizontal rule.
Definition at line 1410 of file _mathtext.py.
Constructor & Destructor Documentation
__init__()
matplotlib._mathtext.Hrule.__init__ (self, ParserState state, float | None thickness = None)
Definition at line 1413 of file _mathtext.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/_mathtext.py