Code Cloning Analysis: matplotlib.offsetbox.DraggableOffsetBox Class Reference
matplotlib.offsetbox.DraggableOffsetBox Class Reference
Public Member Functions
__init__ (self, ref_artist, offsetbox, use_blit=False)
save_offset (self)
update_offset (self, dx, dy)
get_loc_in_canvas (self)
Public Member Functions inherited from matplotlib.offsetbox.DraggableBase
__init__ (self, ref_artist, use_blit=False)
on_motion (self, evt)
on_pick (self, evt)
on_release (self, event)
disconnect (self)
finalize_offset (self)
Public Attributes
offsetbox = offsetbox
offsetbox_x
offsetbox_y = offset
Public Attributes inherited from matplotlib.offsetbox.DraggableBase
ref_artist = ref_artist
bool got_artist = False
background = evt.y - self.mouse_y
mouse_x = evt.mouseevent.x
mouse_y = evt.mouseevent.y
Additional Inherited Members
Protected Member Functions inherited from matplotlib.offsetbox.DraggableBase
_check_still_parented (self)
Static Protected Member Functions inherited from matplotlib.offsetbox.DraggableBase
_picker (artist, mouseevent)
Protected Attributes inherited from matplotlib.offsetbox.DraggableBase
_picker
_use_blit = use_blit and self.canvas.supports_blit
list _disconnectors
Properties inherited from matplotlib.offsetbox.DraggableBase
canvas = property(lambda self: self.ref_artist.get_figure(root=True).canvas)
cids
Detailed Description
Definition at line 1576 of file offsetbox.py.
Constructor & Destructor Documentation
__init__()
matplotlib.offsetbox.DraggableOffsetBox.__init__ (self, ref_artist, offsetbox, use_blit = False)
Definition at line 1577 of file offsetbox.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
get_loc_in_canvas()
matplotlib.offsetbox.DraggableOffsetBox.get_loc_in_canvas (self)
Definition at line 1592 of file offsetbox.py.
Referenced by matplotlib.legend.DraggableLegend.__init__().
save_offset()
matplotlib.offsetbox.DraggableOffsetBox.save_offset (self)
Reimplemented from matplotlib.offsetbox.DraggableBase.
Definition at line 1581 of file offsetbox.py.
update_offset()
matplotlib.offsetbox.DraggableOffsetBox.update_offset (self, dx, dy)
Reimplemented from matplotlib.offsetbox.DraggableBase.
Definition at line 1588 of file offsetbox.py.
Member Data Documentation
offsetbox
matplotlib.offsetbox.DraggableOffsetBox.offsetbox = offsetbox
Definition at line 1579 of file offsetbox.py.
offsetbox_x
matplotlib.offsetbox.DraggableOffsetBox.offsetbox_x
Definition at line 1585 of file offsetbox.py.
offsetbox_y
matplotlib.offsetbox.DraggableOffsetBox.offsetbox_y = offset
Definition at line 1585 of file offsetbox.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/offsetbox.py