Code Cloning Analysis: matplotlib.ticker._DummyAxis Class Reference
matplotlib.ticker._DummyAxis Class Reference
Public Member Functions
__init__ (self, minpos=0)
get_view_interval (self)
set_view_interval (self, vmin, vmax)
get_minpos (self)
get_data_interval (self)
set_data_interval (self, vmin, vmax)
get_tick_space (self)
Protected Attributes
tuple _data_interval = (0, 1)
tuple _view_interval = (0, 1)
_minpos = minpos
Static Private Attributes
str __name__ = "dummy"
Detailed Description
Definition at line 160 of file ticker.py.
Constructor & Destructor Documentation
__init__()
matplotlib.ticker._DummyAxis.__init__ (self, minpos = 0)
Definition at line 163 of file ticker.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
get_data_interval()
matplotlib.ticker._DummyAxis.get_data_interval (self)
Definition at line 177 of file ticker.py.
Referenced by mplot3d.axis3d.Axis.draw_pane().
get_minpos()
matplotlib.ticker._DummyAxis.get_minpos (self)
Definition at line 174 of file ticker.py.
get_tick_space()
matplotlib.ticker._DummyAxis.get_tick_space (self)
Definition at line 183 of file ticker.py.
get_view_interval()
matplotlib.ticker._DummyAxis.get_view_interval (self)
Definition at line 168 of file ticker.py.
Referenced by mplot3d.axis3d.Axis.draw_pane().
set_data_interval()
matplotlib.ticker._DummyAxis.set_data_interval (self, vmin, vmax)
Definition at line 180 of file ticker.py.
Referenced by mplot3d.axis3d.Axis.draw_pane().
set_view_interval()
matplotlib.ticker._DummyAxis.set_view_interval (self, vmin, vmax)
Definition at line 171 of file ticker.py.
Referenced by mplot3d.axis3d.Axis.draw_pane().
Member Data Documentation
__name__
str matplotlib.ticker._DummyAxis.__name__ = "dummy" static private
Definition at line 161 of file ticker.py.
Referenced by sklearn.utils.deprecation.deprecated.__call__(), pandas.tseries.holiday.Holiday._apply_rule(), sklearn.utils._metadata_requests._MetadataRequester._build_request_for_signature(), pandas.core.arrays.interval.IntervalArray._from_factorized(), sklearn.utils._metadata_requests._MetadataRequester._get_default_requests(), pandas.tests.extension.date.array.DateDtype.construct_from_string(), pip._vendor.pygments.sphinxext.PygmentsDoc.document_lexers_overview(), numpy.ma.extras._fromnxfunction.getdoc(), and matplotlib.patches._Style.pprint_styles().
_data_interval
tuple matplotlib.ticker._DummyAxis._data_interval = (0, 1) protected
Definition at line 164 of file ticker.py.
_minpos
matplotlib.ticker._DummyAxis._minpos = minpos protected
Definition at line 166 of file ticker.py.
Referenced by matplotlib.transforms.Bbox.__init__(), matplotlib.transforms.Bbox.minpos(), matplotlib.transforms.Bbox.minposx(), matplotlib.transforms.Bbox.minposy(), and matplotlib.transforms.Bbox.update_from_path().
_view_interval
tuple matplotlib.ticker._DummyAxis._view_interval = (0, 1) protected
Definition at line 165 of file ticker.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/ticker.py