Code Cloning Analysis: fontTools.misc.etree.Element Class Reference
fontTools.misc.etree.Element Class Reference
Public Member Functions
__init__ (self, tag, attrib=_Attrib(), **extra)
Public Attributes
attrib = _Attrib()
Detailed Description
Element subclass that keeps the order of attributes.
Definition at line 68 of file etree.py.
Constructor & Destructor Documentation
__init__()
fontTools.misc.etree.Element.__init__ (self, tag, attrib = _Attrib(), ** extra)
Definition at line 71 of file etree.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Data Documentation
attrib
fontTools.misc.etree.Element.attrib = _Attrib()
Definition at line 73 of file etree.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/misc/etree.py