Code Cloning Analysis: scipy.optimize._dual_annealing.LocalSearchWrapper Class Reference
scipy.optimize._dual_annealing.LocalSearchWrapper Class Reference
Public Member Functions
__init__ (self, search_bounds, func_wrapper, *args, **kwargs)
local_search (self, x, e)
Public Attributes
func_wrapper = func_wrapper
kwargs = kwargs
jac = self.kwargs.get('jac', None)
minimizer = minimize
lower = np.array(bounds_list[0])
upper = np.array(bounds_list[1])
Static Public Attributes
int LS_MAXITER_RATIO = 6
int LS_MAXITER_MIN = 100
int LS_MAXITER_MAX = 1000
Detailed Description
Class used to wrap around the minimizer used for local search
Default local minimizer is SciPy minimizer L-BFGS-B
Definition at line 384 of file _dual_annealing.py.
Constructor & Destructor Documentation
__init__()
scipy.optimize._dual_annealing.LocalSearchWrapper.__init__ (self, search_bounds, func_wrapper, * args, ** kwargs)
Definition at line 394 of file _dual_annealing.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
local_search()
scipy.optimize._dual_annealing.LocalSearchWrapper.local_search (self, x, e)
Definition at line 419 of file _dual_annealing.py.
Member Data Documentation
func_wrapper
scipy.optimize._dual_annealing.LocalSearchWrapper.func_wrapper = func_wrapper
Definition at line 395 of file _dual_annealing.py.
jac
scipy.optimize._dual_annealing.LocalSearchWrapper.jac = self.kwargs.get('jac', None)
Definition at line 397 of file _dual_annealing.py.
Referenced by scipy.optimize._optimize.MemoizeJac.__call__(), scipy.optimize._trustregion_dogleg.DoglegSubproblem.cauchy_point(), scipy.optimize.tests.test_slsqp.TestSLSQP.fprime_ieqcon2(), scipy.optimize._trustregion_constr.tr_interior_point.BarrierSubproblem.gradient_and_jacobian(), scipy.optimize.tests.test_slsqp.TestSLSQP.jac(), scipy.optimize._trustregion.BaseQuadraticSubproblem.jac_mag(), scipy.optimize._trustregion_dogleg.DoglegSubproblem.newton_point(), scipy.optimize._trustregion_exact.IterativeSubproblem.solve(), and scipy.optimize._trustregion_ncg.CGSteihaugSubproblem.solve().
kwargs
scipy.optimize._dual_annealing.LocalSearchWrapper.kwargs = kwargs
Definition at line 396 of file _dual_annealing.py.
Referenced by scipy.optimize.tests.test__basinhopping.TestBasinHopping.setup_method().
lower
scipy.optimize._dual_annealing.LocalSearchWrapper.lower = np.array(bounds_list[0])
Definition at line 400 of file _dual_annealing.py.
LS_MAXITER_MAX
int scipy.optimize._dual_annealing.LocalSearchWrapper.LS_MAXITER_MAX = 1000 static
Definition at line 392 of file _dual_annealing.py.
LS_MAXITER_MIN
int scipy.optimize._dual_annealing.LocalSearchWrapper.LS_MAXITER_MIN = 100 static
Definition at line 391 of file _dual_annealing.py.
LS_MAXITER_RATIO
int scipy.optimize._dual_annealing.LocalSearchWrapper.LS_MAXITER_RATIO = 6 static
Definition at line 390 of file _dual_annealing.py.
minimizer
scipy.optimize._dual_annealing.LocalSearchWrapper.minimizer = minimize
Definition at line 398 of file _dual_annealing.py.
upper
scipy.optimize._dual_annealing.LocalSearchWrapper.upper = np.array(bounds_list[1])
Definition at line 401 of file _dual_annealing.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/optimize/_dual_annealing.py