Code Cloning Analysis: pandas.io.stata.StataParser Class Reference
pandas.io.stata.StataParser Class Reference
Public Member Functions
None __init__ (self)
Public Attributes
DTYPE_MAP
dict DTYPE_MAP_XML
TYPE_MAP = list(tuple(range(251)) + tuple("bhlfd"))
dict TYPE_MAP_XML
dict VALID_RANGE
dict OLD_TYPE_MAPPING
dict MISSING_VALUES
dict NUMPY_TYPE_MAP
dict RESERVED_WORDS
Detailed Description
Definition at line 961 of file stata.py.
Constructor & Destructor Documentation
__init__()
None pandas.io.stata.StataParser.__init__ (self)
Definition at line 962 of file stata.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Data Documentation
DTYPE_MAP
pandas.io.stata.StataParser.DTYPE_MAP
Initial value:
=  dict(
            [(i, np.dtype(f"S{i}")) for i in range(1, 245)]
            + [
                (251, np.dtype(np.int8)),
                (252, np.dtype(np.int16)),
                (253, np.dtype(np.int32)),
                (254, np.dtype(np.float32)),
                (255, np.dtype(np.float64)),
            ]
        )
Definition at line 978 of file stata.py.
DTYPE_MAP_XML
dict pandas.io.stata.StataParser.DTYPE_MAP_XML
Initial value:
=  {
            32768: np.dtype(np.uint8),  # Keys to GSO
            65526: np.dtype(np.float64),
            65527: np.dtype(np.float32),
            65528: np.dtype(np.int32),
            65529: np.dtype(np.int16),
            65530: np.dtype(np.int8),
        }
Definition at line 988 of file stata.py.
MISSING_VALUES
dict pandas.io.stata.StataParser.MISSING_VALUES
Initial value:
=  {
            "b": 101,
            "h": 32741,
            "l": 2147483621,
            "f": np.float32(struct.unpack("<f", b"\x00\x00\x00\x7f")[0]),
            "d": np.float64(
                struct.unpack("<d", b"\x00\x00\x00\x00\x00\x00\xe0\x7f")[0]
            ),
        }
Definition at line 1037 of file stata.py.
NUMPY_TYPE_MAP
dict pandas.io.stata.StataParser.NUMPY_TYPE_MAP
Initial value:
=  {
            "b": "i1",
            "h": "i2",
            "l": "i4",
            "f": "f4",
            "d": "f8",
            "Q": "u8",
        }
Definition at line 1046 of file stata.py.
OLD_TYPE_MAPPING
dict pandas.io.stata.StataParser.OLD_TYPE_MAPPING
Initial value:
=  {
            98: 251,  # byte
            105: 252,  # int
            108: 253,  # long
            102: 254,  # float
            100: 255,  # double
        }
Definition at line 1027 of file stata.py.
RESERVED_WORDS
dict pandas.io.stata.StataParser.RESERVED_WORDS
Definition at line 1056 of file stata.py.
TYPE_MAP
pandas.io.stata.StataParser.TYPE_MAP = list(tuple(range(251)) + tuple("bhlfd"))
Definition at line 996 of file stata.py.
TYPE_MAP_XML
dict pandas.io.stata.StataParser.TYPE_MAP_XML
Initial value:
=  {
            # Not really a Q, unclear how to handle byteswap
            32768: "Q",
            65526: "d",
            65527: "f",
            65528: "l",
            65529: "h",
            65530: "b",
        }
Definition at line 997 of file stata.py.
VALID_RANGE
dict pandas.io.stata.StataParser.VALID_RANGE
Initial value:
=  {
            "b": (-127, 100),
            "h": (-32767, 32740),
            "l": (-2147483647, 2147483620),
            "f": (
                np.float32(struct.unpack("<f", float32_min)[0]),
                np.float32(struct.unpack("<f", float32_max)[0]),
            ),
            "d": (
                np.float64(struct.unpack("<d", float64_min)[0]),
                np.float64(struct.unpack("<d", float64_max)[0]),
            ),
        }
Definition at line 1013 of file stata.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/io/stata.py