Code Cloning Analysis: dateutil.parser._parser._resultbase Class Reference
dateutil.parser._parser._resultbase Class Reference
Public Member Functions
__init__ (self)
__len__ (self)
__repr__ (self)
Protected Member Functions
_repr (self, classname)
Private Attributes
__slots__
Detailed Description
Definition at line 219 of file _parser.py.
Constructor & Destructor Documentation
__init__()
dateutil.parser._parser._resultbase.__init__ (self)
Definition at line 221 of file _parser.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__len__()
dateutil.parser._parser._resultbase.__len__ (self)
Definition at line 233 of file _parser.py.
__repr__()
dateutil.parser._parser._resultbase.__repr__ (self)
Definition at line 237 of file _parser.py.
_repr()
dateutil.parser._parser._resultbase._repr (self, classname) protected
Definition at line 225 of file _parser.py.
Referenced by sklearn.utils._pprint._EstimatorPrettyPrinter._format_items(), sklearn.utils._pprint._EstimatorPrettyPrinter._format_params_or_dict_items(), and sklearn.utils._pprint._EstimatorPrettyPrinter._pprint_key_val_tuple().
Member Data Documentation
__slots__
dateutil.parser._parser._resultbase.__slots__ private
Definition at line 222 of file _parser.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/dateutil/parser/_parser.py