Code Cloning Analysis: dateutil.tz._common._tzinfo Class Reference
dateutil.tz._common._tzinfo Class Reference
Public Member Functions
is_ambiguous (self, dt)
fromutc (self, dt)
Protected Member Functions
_fold_status (self, dt_utc, dt_wall)
_fold (self, dt)
_fromutc (self, dt)
Detailed Description
Base class for all ``dateutil`` ``tzinfo`` objects.
Definition at line 149 of file _common.py.
Member Function Documentation
_fold()
dateutil.tz._common._tzinfo._fold (self, dt) protected
Definition at line 204 of file _common.py.
Referenced by dateutil.tz._common.tzrangebase.is_ambiguous(), dateutil.tz.tz.tzfile.is_ambiguous(), and dateutil.tz.tz.tzlocal.is_ambiguous().
_fold_status()
dateutil.tz._common._tzinfo._fold_status (self, dt_utc, dt_wall) protected
Determine the fold status of a "wall" datetime, given a representation
of the same datetime as a (naive) UTC datetime. This is calculated based
on the assumption that ``dt.utcoffset() - dt.dst()`` is constant for all
datetimes, and that this offset is the actual number of hours separating
``dt_utc`` and ``dt_wall``.
:param dt_utc:
    Representation of the datetime as UTC
:param dt_wall:
    Representation of the datetime as "wall time". This parameter must
    either have a `fold` attribute or have a fold-naive
    :class:`datetime.tzinfo` attached, otherwise the calculation may
    fail.
Definition at line 179 of file _common.py.
References is_ambiguous().
Referenced by fromutc().
_fromutc()
dateutil.tz._common._tzinfo._fromutc (self, dt) protected
Given a timezone-aware datetime in a given timezone, calculates a
timezone-aware datetime in a new timezone.
Since this is the one time that we *know* we have an unambiguous
datetime object, we take this opportunity to determine whether the
datetime is ambiguous and in a "fold" state (e.g. if it's the first
occurrence, chronologically, of the ambiguous datetime).
:param dt:
    A timezone-aware :class:`datetime.datetime` object.
Definition at line 207 of file _common.py.
References dateutil.tz._common.enfold().
Referenced by fromutc().
fromutc()
dateutil.tz._common._tzinfo.fromutc (self, dt)
Given a timezone-aware datetime in a given timezone, calculates a
timezone-aware datetime in a new timezone.
Since this is the one time that we *know* we have an unambiguous
datetime object, we take this opportunity to determine whether the
datetime is ambiguous and in a "fold" state (e.g. if it's the first
occurrence, chronologically, of the ambiguous datetime).
:param dt:
    A timezone-aware :class:`datetime.datetime` object.
Reimplemented in dateutil.tz._common.tzrangebase, and dateutil.tz.tz.tzfile.
Definition at line 245 of file _common.py.
References _fold_status(), _fromutc(), and dateutil.tz._common.enfold().
Referenced by pytz.tzinfo.DstTzInfo.normalize().
is_ambiguous()
dateutil.tz._common._tzinfo.is_ambiguous (self, dt)
Whether or not the "wall time" of a given datetime is ambiguous in this
zone.
:param dt:
    A :py:class:`datetime.datetime`, naive or time zone aware.
:return:
    Returns ``True`` if ambiguous, ``False`` otherwise.
.. versionadded:: 2.6.0
Reimplemented in dateutil.tz._common.tzrangebase, dateutil.tz.tz.tzfile, and dateutil.tz.tz.tzlocal.
Definition at line 154 of file _common.py.
References dateutil.tz._common.enfold().
Referenced by _fold_status(), dateutil.tz._common.tzrangebase.fromutc(), dateutil.tz.tz.tzfile.fromutc(), dateutil.tz._common.tzrangebase.is_ambiguous(), dateutil.tz.tz.tzfile.is_ambiguous(), and dateutil.tz.tz.tzlocal.is_ambiguous().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/dateutil/tz/_common.py