Code Cloning Analysis: pandas.core.computation.expr.PythonExprVisitor Class Reference
pandas.core.computation.expr.PythonExprVisitor Class Reference
Public Member Functions
None __init__ (self, env, engine, parser, preparser=lambda source, f=None:source)
Public Member Functions inherited from pandas.core.computation.expr.BaseExprVisitor
None __init__ (self, env, engine, parser, preparser=_preparse)
visit (self, node, **kwargs)
visit_Module (self, node, **kwargs)
visit_Expr (self, node, **kwargs)
visit_BinOp (self, node, **kwargs)
visit_UnaryOp (self, node, **kwargs)
Term visit_Name (self, node, **kwargs)
Term visit_NameConstant (self, node, **kwargs)
Term visit_Num (self, node, **kwargs)
Term visit_Constant (self, node, **kwargs)
Term visit_Str (self, node, **kwargs)
Term visit_List (self, node, **kwargs)
visit_Index (self, node, **kwargs)
Term visit_Subscript (self, node, **kwargs)
slice visit_Slice (self, node, **kwargs)
visit_Assign (self, node, **kwargs)
visit_Attribute (self, node, **kwargs)
visit_Call (self, node, side=None, **kwargs)
translate_In (self, op)
visit_Compare (self, node, **kwargs)
visit_BoolOp (self, node, **kwargs)
Additional Inherited Members
Public Attributes inherited from pandas.core.computation.expr.BaseExprVisitor
env = env
engine = engine
parser = parser
preparser = preparser
assigner = None
Static Public Attributes inherited from pandas.core.computation.expr.BaseExprVisitor
ClassVar const_type = Constant
ClassVar term_type = Term
binary_ops = CMP_OPS_SYMS + BOOL_OPS_SYMS + ARITH_OPS_SYMS
tuple binary_op_nodes
binary_op_nodes_map = dict(zip(binary_ops, binary_op_nodes))
unary_ops = UNARY_OPS_SYMS
str unary_op_nodes = "UAdd", "USub", "Invert", "Not"
unary_op_nodes_map = dict(zip(unary_ops, unary_op_nodes))
dict rewrite_map
tuple unsupported_nodes [str, ...]
Term visit_Tuple = visit_List
Protected Member Functions inherited from pandas.core.computation.expr.BaseExprVisitor
_rewrite_membership_op (self, node, left, right)
_maybe_transform_eq_ne (self, node, left=None, right=None)
_maybe_downcast_constants (self, left, right)
_maybe_eval (self, binop, eval_in_python)
_maybe_evaluate_binop (self, op, op_class, lhs, rhs, eval_in_python=("in", "not in"), maybe_eval_in_python=("==", "!=", "<", ">", "<=", ">="))
_try_visit_binop (self, bop)
Detailed Description
Definition at line 772 of file expr.py.
Constructor & Destructor Documentation
__init__()
None pandas.core.computation.expr.PythonExprVisitor.__init__ (self, env, engine, parser, preparser = lambda source, f = None: source)
Definition at line 773 of file expr.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/core/computation/expr.py