Code Cloning Analysis: matplotlib.testing.compare._GSConverter Class Reference
matplotlib.testing.compare._GSConverter Class Reference
Public Member Functions
__call__ (self, orig, dest)
Public Member Functions inherited from matplotlib.testing.compare._Converter
__init__ (self)
__del__ (self)
Additional Inherited Members
Protected Member Functions inherited from matplotlib.testing.compare._Converter
_read_until (self, terminator)
Protected Attributes inherited from matplotlib.testing.compare._Converter
_proc = None
Detailed Description
Definition at line 100 of file compare.py.
Member Function Documentation
__call__()
matplotlib.testing.compare._GSConverter.__call__ (self, orig, dest)
Definition at line 101 of file compare.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), scipy.interpolate._fitpack2.SphereBivariateSpline.ev(), matplotlib.ticker.Formatter.format_data(), and matplotlib.ticker.LogFormatter.format_data().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/testing/compare.py