Code Cloning Analysis: axisartist.grid_finder.MaxNLocator Class Reference
axisartist.grid_finder.MaxNLocator Class Reference
Public Member Functions
__init__ (self, nbins=10, steps=None, trim=True, integer=False, symmetric=False, prune=None)
__call__ (self, v1, v2)
Detailed Description
Definition at line 268 of file grid_finder.py.
Constructor & Destructor Documentation
__init__()
axisartist.grid_finder.MaxNLocator.__init__ (self, nbins = 10, steps = None, trim = True, integer = False, symmetric = False, prune = None)
Definition at line 269 of file grid_finder.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__call__()
axisartist.grid_finder.MaxNLocator.__call__ (self, v1, v2)
Definition at line 279 of file grid_finder.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), and scipy.interpolate._fitpack2.SphereBivariateSpline.ev().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/mpl_toolkits/axisartist/grid_finder.py