Code Cloning Analysis: sklearn.manifold._locally_linear Namespace Reference
sklearn.manifold._locally_linear Namespace Reference
Classes
class LocallyLinearEmbedding
Functions
barycenter_weights (X, Y, indices, reg=1e-3)
barycenter_kneighbors_graph (X, n_neighbors, reg=1e-3, n_jobs=None)
null_space (M, k, k_skip=1, eigen_solver="arpack", tol=1e-6, max_iter=100, random_state=None)
_locally_linear_embedding (X, *, n_neighbors, n_components, reg=1e-3, eigen_solver="auto", tol=1e-6, max_iter=100, method="standard", hessian_tol=1e-4, modified_tol=1e-12, random_state=None, n_jobs=None)
locally_linear_embedding (X, *, n_neighbors, n_components, reg=1e-3, eigen_solver="auto", tol=1e-6, max_iter=100, method="standard", hessian_tol=1e-4, modified_tol=1e-12, random_state=None, n_jobs=None)
Detailed Description
Locally Linear Embedding
Function Documentation
_locally_linear_embedding()
sklearn.manifold._locally_linear._locally_linear_embedding (X, * , n_neighbors, n_components, reg = 1e-3, eigen_solver = "auto", tol = 1e-6, max_iter = 100, method = "standard", hessian_tol = 1e-4, modified_tol = 1e-12, random_state = None, n_jobs = None) protected
Definition at line 200 of file _locally_linear.py.
barycenter_kneighbors_graph()
sklearn.manifold._locally_linear.barycenter_kneighbors_graph (X, n_neighbors, reg = 1e-3, n_jobs = None)
Computes the barycenter weighted graph of k-Neighbors for points in X
Parameters
----------
X : {array-like, NearestNeighbors}
    Sample data, shape = (n_samples, n_features), in the form of a
    numpy array or a NearestNeighbors object.
n_neighbors : int
    Number of neighbors for each sample.
reg : float, default=1e-3
    Amount of regularization when solving the least-squares
    problem. Only relevant if mode='barycenter'. If None, use the
    default.
n_jobs : int or None, default=None
    The number of parallel jobs to run for neighbors search.
    ``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.
    ``-1`` means using all processors. See :term:`Glossary <n_jobs>`
    for more details.
Returns
-------
A : sparse matrix in CSR format, shape = [n_samples, n_samples]
    A[i, j] is assigned the weight of edge that connects i to j.
See Also
--------
sklearn.neighbors.kneighbors_graph
sklearn.neighbors.radius_neighbors_graph
Definition at line 82 of file _locally_linear.py.
References barycenter_weights().
Referenced by null_space().
barycenter_weights()
sklearn.manifold._locally_linear.barycenter_weights (X, Y, indices, reg = 1e-3)
Compute barycenter weights of X from Y along the first axis
We estimate the weights to assign to each point in Y[indices] to recover
the point X[i]. The barycenter weights sum to 1.
Parameters
----------
X : array-like, shape (n_samples, n_dim)
Y : array-like, shape (n_samples, n_dim)
indices : array-like, shape (n_samples, n_dim)
        Indices of the points in Y used to compute the barycenter
reg : float, default=1e-3
    Amount of regularization to add for the problem to be
    well-posed in the case of n_neighbors > n_dim
Returns
-------
B : array-like, shape (n_samples, n_neighbors)
Notes
-----
See developers note for more information.
Definition at line 28 of file _locally_linear.py.
Referenced by barycenter_kneighbors_graph(), and sklearn.manifold._locally_linear.LocallyLinearEmbedding.transform().
locally_linear_embedding()
sklearn.manifold._locally_linear.locally_linear_embedding (X, * , n_neighbors, n_components, reg = 1e-3, eigen_solver = "auto", tol = 1e-6, max_iter = 100, method = "standard", hessian_tol = 1e-4, modified_tol = 1e-12, random_state = None, n_jobs = None)
Perform a Locally Linear Embedding analysis on the data.
Read more in the :ref:`User Guide <locally_linear_embedding>`.
Parameters
----------
X : {array-like, NearestNeighbors}
    Sample data, shape = (n_samples, n_features), in the form of a
    numpy array or a NearestNeighbors object.
n_neighbors : int
    Number of neighbors to consider for each point.
n_components : int
    Number of coordinates for the manifold.
reg : float, default=1e-3
    Regularization constant, multiplies the trace of the local covariance
    matrix of the distances.
eigen_solver : {'auto', 'arpack', 'dense'}, default='auto'
    auto : algorithm will attempt to choose the best method for input data
    arpack : use arnoldi iteration in shift-invert mode.
                For this method, M may be a dense matrix, sparse matrix,
                or general linear operator.
                Warning: ARPACK can be unstable for some problems.  It is
                best to try several random seeds in order to check results.
    dense  : use standard dense matrix operations for the eigenvalue
                decomposition.  For this method, M must be an array
                or matrix type.  This method should be avoided for
                large problems.
tol : float, default=1e-6
    Tolerance for 'arpack' method
    Not used if eigen_solver=='dense'.
max_iter : int, default=100
    Maximum number of iterations for the arpack solver.
method : {'standard', 'hessian', 'modified', 'ltsa'}, default='standard'
    standard : use the standard locally linear embedding algorithm.
               see reference [1]_
    hessian  : use the Hessian eigenmap method.  This method requires
               n_neighbors > n_components * (1 + (n_components + 1) / 2.
               see reference [2]_
    modified : use the modified locally linear embedding algorithm.
               see reference [3]_
    ltsa     : use local tangent space alignment algorithm
               see reference [4]_
hessian_tol : float, default=1e-4
    Tolerance for Hessian eigenmapping method.
    Only used if method == 'hessian'.
modified_tol : float, default=1e-12
    Tolerance for modified LLE method.
    Only used if method == 'modified'.
random_state : int, RandomState instance, default=None
    Determines the random number generator when ``solver`` == 'arpack'.
    Pass an int for reproducible results across multiple function calls.
    See :term:`Glossary <random_state>`.
n_jobs : int or None, default=None
    The number of parallel jobs to run for neighbors search.
    ``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.
    ``-1`` means using all processors. See :term:`Glossary <n_jobs>`
    for more details.
Returns
-------
Y : ndarray of shape (n_samples, n_components)
    Embedding vectors.
squared_error : float
    Reconstruction error for the embedding vectors. Equivalent to
    ``norm(Y - W Y, 'fro')**2``, where W are the reconstruction weights.
References
----------
.. [1] Roweis, S. & Saul, L. Nonlinear dimensionality reduction
    by locally linear embedding.  Science 290:2323 (2000).
.. [2] Donoho, D. & Grimes, C. Hessian eigenmaps: Locally
    linear embedding techniques for high-dimensional data.
    Proc Natl Acad Sci U S A.  100:5591 (2003).
.. [3] `Zhang, Z. & Wang, J. MLLE: Modified Locally Linear
    Embedding Using Multiple Weights.
    <https://citeseerx.ist.psu.edu/doc_view/pid/0b060fdbd92cbcc66b383bcaa9ba5e5e624d7ee3>`_
.. [4] Zhang, Z. & Zha, H. Principal manifolds and nonlinear
    dimensionality reduction via tangent space alignment.
    Journal of Shanghai Univ.  8:406 (2004)
Examples
--------
>>> from sklearn.datasets import load_digits
>>> from sklearn.manifold import locally_linear_embedding
>>> X, _ = load_digits(return_X_y=True)
>>> X.shape
(1797, 64)
>>> embedding, _ = locally_linear_embedding(X[:100],n_neighbors=5, n_components=2)
>>> embedding.shape
(100, 2)
Definition at line 465 of file _locally_linear.py.
null_space()
sklearn.manifold._locally_linear.null_space (M, k, k_skip = 1, eigen_solver = "arpack", tol = 1e-6, max_iter = 100, random_state = None)
Find the null space of a matrix M.
Parameters
----------
M : {array, matrix, sparse matrix, LinearOperator}
    Input covariance matrix: should be symmetric positive semi-definite
k : int
    Number of eigenvalues/vectors to return
k_skip : int, default=1
    Number of low eigenvalues to skip.
eigen_solver : {'auto', 'arpack', 'dense'}, default='arpack'
    auto : algorithm will attempt to choose the best method for input data
    arpack : use arnoldi iteration in shift-invert mode.
                For this method, M may be a dense matrix, sparse matrix,
                or general linear operator.
                Warning: ARPACK can be unstable for some problems.  It is
                best to try several random seeds in order to check results.
    dense  : use standard dense matrix operations for the eigenvalue
                decomposition.  For this method, M must be an array
                or matrix type.  This method should be avoided for
                large problems.
tol : float, default=1e-6
    Tolerance for 'arpack' method.
    Not used if eigen_solver=='dense'.
max_iter : int, default=100
    Maximum number of iterations for 'arpack' method.
    Not used if eigen_solver=='dense'
random_state : int, RandomState instance, default=None
    Determines the random number generator when ``solver`` == 'arpack'.
    Pass an int for reproducible results across multiple function calls.
    See :term:`Glossary <random_state>`.
Definition at line 124 of file _locally_linear.py.
References barycenter_kneighbors_graph(), and null_space().
Referenced by null_space().