Code Cloning Analysis: fontTools.ttLib.tables.S_V_G_.DocumentIndexEntry Class Reference
fontTools.ttLib.tables.S_V_G_.DocumentIndexEntry Class Reference
Public Member Functions
__init__ (self)
__repr__ (self)
Public Attributes
startGlyphID = None
endGlyphID = None
svgDocOffset = None
svgDocLength = None
Detailed Description
Definition at line 192 of file S_V_G_.py.
Constructor & Destructor Documentation
__init__()
fontTools.ttLib.tables.S_V_G_.DocumentIndexEntry.__init__ (self)
Definition at line 193 of file S_V_G_.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__repr__()
fontTools.ttLib.tables.S_V_G_.DocumentIndexEntry.__repr__ (self)
Definition at line 199 of file S_V_G_.py.
Member Data Documentation
endGlyphID
fontTools.ttLib.tables.S_V_G_.DocumentIndexEntry.endGlyphID = None
Definition at line 195 of file S_V_G_.py.
startGlyphID
fontTools.ttLib.tables.S_V_G_.DocumentIndexEntry.startGlyphID = None
Definition at line 194 of file S_V_G_.py.
svgDocLength
fontTools.ttLib.tables.S_V_G_.DocumentIndexEntry.svgDocLength = None
Definition at line 197 of file S_V_G_.py.
svgDocOffset
fontTools.ttLib.tables.S_V_G_.DocumentIndexEntry.svgDocOffset = None
Definition at line 196 of file S_V_G_.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ttLib/tables/S_V_G_.py