Code Cloning Analysis: fontTools.ttLib.tables._v_h_e_a.table__v_h_e_a Class Reference
fontTools.ttLib.tables._v_h_e_a.table__v_h_e_a Class Reference
Public Member Functions
decompile (self, data, ttFont)
compile (self, ttFont)
recalc (self, ttFont)
toXML (self, writer, ttFont)
fromXML (self, name, attrs, content, ttFont)
reserved0 (self)
reserved0 (self, value)
Public Member Functions inherited from fontTools.ttLib.tables.DefaultTable.DefaultTable
__init__ (self, tag=None)
__repr__ (self)
__eq__ (self, other)
__ne__ (self, other)
Public Attributes
tableVersion = fi2ve(self.tableVersion)
advanceHeightMax = max(adv for adv, _ in vmtxTable.metrics.values())
int minTopSideBearing = minTopSideBearing
int minBottomSideBearing = minBottomSideBearing
int yMaxExtent = yMaxExtent
caretOffset = value
Public Attributes inherited from fontTools.ttLib.tables.DefaultTable.DefaultTable
tableTag = Tag(tag)
data = data
ERROR
Additional Inherited Members
Static Public Attributes inherited from fontTools.ttLib.tables.DefaultTable.DefaultTable
list dependencies = []
Detailed Description
Vertical Header table
The ``vhea`` table contains information needed during vertical
text layout.
.. note::
   This converter class is kept in sync with the :class:`._h_h_e_a.table__h_h_e_a`
   table constructor.
See also https://learn.microsoft.com/en-us/typography/opentype/spec/vhea
Definition at line 33 of file _v_h_e_a.py.
Member Function Documentation
compile()
fontTools.ttLib.tables._v_h_e_a.table__v_h_e_a.compile (self, ttFont)
Reimplemented from fontTools.ttLib.tables.DefaultTable.DefaultTable.
Definition at line 53 of file _v_h_e_a.py.
Referenced by fontTools.ttLib.tables.TupleVariation.TupleVariation.getCoordWidth(), and PIL.FontFile.FontFile.save().
decompile()
fontTools.ttLib.tables._v_h_e_a.table__v_h_e_a.decompile (self, data, ttFont)
Reimplemented from fontTools.ttLib.tables.DefaultTable.DefaultTable.
Definition at line 50 of file _v_h_e_a.py.
Referenced by fontTools.ttLib.tables._c_m_a_p.CmapSubtable.newSubtable().
fromXML()
fontTools.ttLib.tables._v_h_e_a.table__v_h_e_a.fromXML (self, name, attrs, content, ttFont)
Reimplemented from fontTools.ttLib.tables.DefaultTable.DefaultTable.
Definition at line 126 of file _v_h_e_a.py.
recalc()
fontTools.ttLib.tables._v_h_e_a.table__v_h_e_a.recalc (self, ttFont)
Definition at line 63 of file _v_h_e_a.py.
reserved0() [1/2]
fontTools.ttLib.tables._v_h_e_a.table__v_h_e_a.reserved0 (self)
Definition at line 134 of file _v_h_e_a.py.
reserved0() [2/2]
fontTools.ttLib.tables._v_h_e_a.table__v_h_e_a.reserved0 (self, value)
Definition at line 138 of file _v_h_e_a.py.
toXML()
fontTools.ttLib.tables._v_h_e_a.table__v_h_e_a.toXML (self, writer, ttFont)
Reimplemented from fontTools.ttLib.tables.DefaultTable.DefaultTable.
Definition at line 116 of file _v_h_e_a.py.
Member Data Documentation
advanceHeightMax
fontTools.ttLib.tables._v_h_e_a.table__v_h_e_a.advanceHeightMax = max(adv for adv, _ in vmtxTable.metrics.values())
Definition at line 68 of file _v_h_e_a.py.
caretOffset
fontTools.ttLib.tables._v_h_e_a.table__v_h_e_a.caretOffset = value
Definition at line 139 of file _v_h_e_a.py.
minBottomSideBearing
int fontTools.ttLib.tables._v_h_e_a.table__v_h_e_a.minBottomSideBearing = minBottomSideBearing
Definition at line 108 of file _v_h_e_a.py.
minTopSideBearing
int fontTools.ttLib.tables._v_h_e_a.table__v_h_e_a.minTopSideBearing = minTopSideBearing
Definition at line 107 of file _v_h_e_a.py.
tableVersion
fontTools.ttLib.tables._v_h_e_a.table__v_h_e_a.tableVersion = fi2ve(self.tableVersion)
Definition at line 60 of file _v_h_e_a.py.
yMaxExtent
int fontTools.ttLib.tables._v_h_e_a.table__v_h_e_a.yMaxExtent = yMaxExtent
Definition at line 109 of file _v_h_e_a.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ttLib/tables/_v_h_e_a.py