Code Cloning Analysis: scipy.optimize._lsq.trf_linear Namespace Reference
scipy.optimize._lsq.trf_linear Namespace Reference
Functions
regularized_lsq_with_qr (m, n, R, QTb, perm, diag, copy_R=True)
backtracking (A, g, x, p, theta, p_dot_g, lb, ub)
select_step (x, A_h, g_h, c_h, p, p_h, d, lb, ub, theta)
trf_linear (A, b, x_lsq, lb, ub, tol, lsq_solver, lsmr_tol, max_iter, verbose, *, lsmr_maxiter=None)
Detailed Description
The adaptation of Trust Region Reflective algorithm for a linear
least-squares problem.
Function Documentation
backtracking()
scipy.optimize._lsq.trf_linear.backtracking (A, g, x, p, theta, p_dot_g, lb, ub)
Find an appropriate step size using backtracking line search.
Definition at line 69 of file trf_linear.py.
Referenced by select_step().
regularized_lsq_with_qr()
scipy.optimize._lsq.trf_linear.regularized_lsq_with_qr (m, n, R, QTb, perm, diag, copy_R = True)
Solve regularized least squares using information from QR-decomposition.
The initial problem is to solve the following system in a least-squares
sense::
    A x = b
    D x = 0
where D is diagonal matrix. The method is based on QR decomposition
of the form A P = Q R, where P is a column permutation matrix, Q is an
orthogonal matrix and R is an upper triangular matrix.
Parameters
----------
m, n : int
    Initial shape of A.
R : ndarray, shape (n, n)
    Upper triangular matrix from QR decomposition of A.
QTb : ndarray, shape (n,)
    First n components of Q^T b.
perm : ndarray, shape (n,)
    Array defining column permutation of A, such that ith column of
    P is perm[i]-th column of identity matrix.
diag : ndarray, shape (n,)
    Array containing diagonal elements of D.
Returns
-------
x : ndarray, shape (n,)
    Found least-squares solution.
Definition at line 18 of file trf_linear.py.
Referenced by select_step().
select_step()
scipy.optimize._lsq.trf_linear.select_step (x, A_h, g_h, c_h, p, p_h, d, lb, ub, theta)
Select the best step according to Trust Region Reflective algorithm.
Definition at line 90 of file trf_linear.py.
References backtracking(), regularized_lsq_with_qr(), and select_step().
Referenced by select_step().
trf_linear()
scipy.optimize._lsq.trf_linear.trf_linear (A, b, x_lsq, lb, ub, tol, lsq_solver, lsmr_tol, max_iter, verbose, * , lsmr_maxiter = None)
Definition at line 142 of file trf_linear.py.