Code Cloning Analysis: fontTools.ttLib.tables.C_F_F_.table_C_F_F_ Class Reference
fontTools.ttLib.tables.C_F_F_.table_C_F_F_ Class Reference
Public Member Functions
__init__ (self, tag=None)
decompile (self, data, otFont)
compile (self, otFont)
haveGlyphNames (self)
getGlyphOrder (self)
setGlyphOrder (self, glyphOrder)
toXML (self, writer, otFont)
fromXML (self, name, attrs, content, otFont)
Public Member Functions inherited from fontTools.ttLib.tables.DefaultTable.DefaultTable
__init__ (self, tag=None)
__repr__ (self)
__eq__ (self, other)
__ne__ (self, other)
Public Attributes
cff = cffLib.CFFFontSet()
Public Attributes inherited from fontTools.ttLib.tables.DefaultTable.DefaultTable
tableTag = Tag(tag)
data = data
ERROR
Protected Attributes
bool _gaveGlyphOrder = False
Additional Inherited Members
Static Public Attributes inherited from fontTools.ttLib.tables.DefaultTable.DefaultTable
list dependencies = []
Detailed Description
Compact Font Format table (version 1)
The ``CFF`` table embeds a CFF-formatted font. The CFF font format
predates OpenType and could be used as a standalone font file, but the
``CFF`` table is also used to package CFF fonts into an OpenType
container.
.. note::
   ``CFF`` has been succeeded by ``CFF2``, which eliminates much of
   the redundancy incurred by embedding CFF version 1 in an OpenType
   font.
See also https://learn.microsoft.com/en-us/typography/opentype/spec/cff
Definition at line 6 of file C_F_F_.py.
Constructor & Destructor Documentation
__init__()
fontTools.ttLib.tables.C_F_F_.table_C_F_F_.__init__ (self, tag = None)
Definition at line 22 of file C_F_F_.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
compile()
fontTools.ttLib.tables.C_F_F_.table_C_F_F_.compile (self, otFont)
Reimplemented from fontTools.ttLib.tables.DefaultTable.DefaultTable.
Definition at line 31 of file C_F_F_.py.
Referenced by fontTools.ttLib.tables.TupleVariation.TupleVariation.getCoordWidth(), and PIL.FontFile.FontFile.save().
decompile()
fontTools.ttLib.tables.C_F_F_.table_C_F_F_.decompile (self, data, otFont)
Reimplemented from fontTools.ttLib.tables.DefaultTable.DefaultTable.
Definition at line 27 of file C_F_F_.py.
Referenced by fontTools.ttLib.tables._c_m_a_p.CmapSubtable.newSubtable().
fromXML()
fontTools.ttLib.tables.C_F_F_.table_C_F_F_.fromXML (self, name, attrs, content, otFont)
Reimplemented from fontTools.ttLib.tables.DefaultTable.DefaultTable.
Definition at line 58 of file C_F_F_.py.
getGlyphOrder()
fontTools.ttLib.tables.C_F_F_.table_C_F_F_.getGlyphOrder (self)
Definition at line 42 of file C_F_F_.py.
Referenced by fontTools.ttLib.ttFont.TTFont.getGlyphName(), fontTools.ttLib.ttFont.TTFont.getGlyphNameMany(), fontTools.ttLib.ttFont.TTFont.getGlyphNames(), fontTools.ttLib.ttFont.TTFont.getGlyphNames2(), fontTools.ttLib.ttFont.TTFont.getReverseGlyphMap(), and fontTools.ttLib.ttFont.TTFont.importXML().
haveGlyphNames()
fontTools.ttLib.tables.C_F_F_.table_C_F_F_.haveGlyphNames (self)
Definition at line 36 of file C_F_F_.py.
setGlyphOrder()
fontTools.ttLib.tables.C_F_F_.table_C_F_F_.setGlyphOrder (self, glyphOrder)
Definition at line 50 of file C_F_F_.py.
toXML()
fontTools.ttLib.tables.C_F_F_.table_C_F_F_.toXML (self, writer, otFont)
Reimplemented from fontTools.ttLib.tables.DefaultTable.DefaultTable.
Definition at line 55 of file C_F_F_.py.
Member Data Documentation
_gaveGlyphOrder
bool fontTools.ttLib.tables.C_F_F_.table_C_F_F_._gaveGlyphOrder = False protected
Definition at line 25 of file C_F_F_.py.
cff
fontTools.ttLib.tables.C_F_F_.table_C_F_F_.cff = cffLib.CFFFontSet()
Definition at line 24 of file C_F_F_.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ttLib/tables/C_F_F_.py