Code Cloning Analysis: pandas.io.formats.format Namespace Reference
pandas.io.formats.format Namespace Reference
Classes
class _Datetime64Formatter
class _Datetime64TZFormatter
class _ExtensionArrayFormatter
class _GenericArrayFormatter
class _IntArrayFormatter
class _Timedelta64Formatter
class DataFrameFormatter
class DataFrameRenderer
class EngFormatter
class FloatArrayFormatter
class SeriesFormatter
Functions
dict[str, Any] get_dataframe_repr_params ()
dict[str, Any] get_series_repr_params ()
str|None save_to_buffer (str string, FilePath|WriteBuffer[str]|None buf=None, str|None encoding=None)
Generator[WriteBuffer[str], None, None]|Generator[StringIO, None, None] _get_buffer (FilePath|WriteBuffer[str]|None buf, str|None encoding=None)
list[str] format_array (ArrayLike values, Callable|None formatter, FloatFormatType|None float_format=None, str na_rep="NaN", int|None digits=None, str|int|None space=None, str justify="right", str decimal=".", bool|None leading_space=True, int|None quoting=None, Callable|None fallback_formatter=None)
list[str] format_percentiles ((np.ndarray|Sequence[float]) percentiles)
int get_precision (np.ndarray|Sequence[float] array)
str _format_datetime64 (NaTType|Timestamp x, str nat_rep="NaT")
str _format_datetime64_dateonly (NaTType|Timestamp x, str nat_rep="NaT", str|None date_format=None)
Callable get_format_datetime64 (bool is_dates_only, str nat_rep="NaT", str|None date_format=None)
Callable get_format_timedelta64 (TimedeltaArray values, str|float nat_rep="NaT", bool box=False)
list[str] _make_fixed_width (list[str] strings, str justify="right", int|None minimum=None, printing._TextAdjustment|None adj=None)
list[str] _trim_zeros_complex (ArrayLike str_complexes, str decimal=".")
str _trim_zeros_single_float (str str_float)
list[str] _trim_zeros_float (ArrayLike|list[str] str_floats, str decimal=".")
bool _has_names (Index index)
None set_eng_float_format (int accuracy=3, bool use_eng_prefix=False)
list[dict[int, int]] get_level_lengths (Any levels, bool|object|str sentinel="")
None buffer_put_lines (WriteBuffer[str] buf, list[str] lines)
Variables
Final common_docstring
tuple VALID_JUSTIFY_PARAMETERS
Final return_docstring
Detailed Description
Internal module for formatting output data in csv, html, xml,
and latex files. This module also applies to display formatting.
Function Documentation
_format_datetime64()
str pandas.io.formats.format._format_datetime64 (NaTType | Timestamp x, str nat_rep = "NaT") protected
Definition at line 1619 of file format.py.
_format_datetime64_dateonly()
str pandas.io.formats.format._format_datetime64_dateonly (NaTType | Timestamp x, str nat_rep = "NaT", str | None date_format = None) protected
Definition at line 1628 of file format.py.
_get_buffer()
Generator[WriteBuffer[str], None, None] | Generator[StringIO, None, None] pandas.io.formats.format._get_buffer (FilePath | WriteBuffer[str] | None buf, str | None encoding = None) protected
Context manager to open, yield and close buffer for filenames or Path-like
objects, otherwise yield buf unchanged.
Definition at line 1042 of file format.py.
Referenced by save_to_buffer().
_has_names()
bool pandas.io.formats.format._has_names (Index index) protected
Definition at line 1841 of file format.py.
_make_fixed_width()
list[str] pandas.io.formats.format._make_fixed_width (list[str] strings, str justify = "right", int | None minimum = None, printing._TextAdjustment | None adj = None) protected
Definition at line 1726 of file format.py.
_trim_zeros_complex()
list[str] pandas.io.formats.format._trim_zeros_complex (ArrayLike str_complexes, str decimal = ".") protected
Separates the real and imaginary parts from the complex number, and
executes the _trim_zeros_float method on each of those.
Definition at line 1760 of file format.py.
References _trim_zeros_float().
Referenced by pandas.io.formats.format.FloatArrayFormatter.get_result_as_array().
_trim_zeros_float()
list[str] pandas.io.formats.format._trim_zeros_float (ArrayLike | list[str] str_floats, str decimal = ".") protected
Trims the maximum number of trailing zeros equally from
all numbers containing decimals, leaving just one if
necessary.
Definition at line 1805 of file format.py.
Referenced by _trim_zeros_complex(), and pandas.io.formats.format.FloatArrayFormatter.get_result_as_array().
_trim_zeros_single_float()
str pandas.io.formats.format._trim_zeros_single_float (str str_float) protected
Trims trailing zeros after a decimal point,
leaving just one if necessary.
Definition at line 1793 of file format.py.
buffer_put_lines()
None pandas.io.formats.format.buffer_put_lines (WriteBuffer[str] buf, list[str] lines)
Appends lines to a buffer.
Parameters
----------
buf
    The buffer to write to
lines
    The lines to append.
Definition at line 2045 of file format.py.
format_array()
list[str] pandas.io.formats.format.format_array (ArrayLike values, Callable | None formatter, FloatFormatType | None float_format = None, str na_rep = "NaN", int | None digits = None, str | int | None space = None, str justify = "right", str decimal = ".", bool | None leading_space = True, int | None quoting = None, Callable | None fallback_formatter = None)
Format an array for printing.
Parameters
----------
values : np.ndarray or ExtensionArray
formatter
float_format
na_rep
digits
space
justify
decimal
leading_space : bool, optional, default True
    Whether the array should be formatted with a leading space.
    When an array as a column of a Series or DataFrame, we do want
    the leading space to pad between columns.
    When formatting an Index subclass
    (e.g. IntervalIndex._get_values_for_csv), we don't want the
    leading space since it should be left-aligned.
fallback_formatter
Returns
-------
List[str]
Definition at line 1079 of file format.py.
Referenced by pandas.io.formats.format.DataFrameFormatter._truncate_vertically().
format_percentiles()
list[str] pandas.io.formats.format.format_percentiles ((np.ndarray | Sequence[float]) percentiles)
Outputs rounded and formatted percentiles.
Parameters
----------
percentiles : list-like, containing floats from interval [0,1]
Returns
-------
formatted : list of strings
Notes
-----
Rounding precision is chosen so that: (1) if any two elements of
``percentiles`` differ, they remain different after rounding
(2) no entry is *rounded* to 0% or 100%.
Any non-integer is always rounded to at least 1 decimal place.
Examples
--------
Keeps all entries different after rounding:
>>> format_percentiles([0.01999, 0.02001, 0.5, 0.666666, 0.9999])
['1.999%', '2.001%', '50%', '66.667%', '99.99%']
No element is rounded to 0% or 100% (unless already equal to it).
Duplicates are allowed:
>>> format_percentiles([0, 0.5, 0.02001, 0.5, 0.666666, 0.9999])
['0%', '50%', '2.0%', '50%', '66.67%', '99.99%']
Definition at line 1546 of file format.py.
get_dataframe_repr_params()
dict[str, Any] pandas.io.formats.format.get_dataframe_repr_params ()
Get the parameters used to repr(dataFrame) calls using DataFrame.to_string.
Supplying these parameters to DataFrame.to_string is equivalent to calling
``repr(DataFrame)``. This is useful if you want to adjust the repr output.
.. versionadded:: 1.4.0
Example
-------
>>> import pandas as pd
>>>
>>> df = pd.DataFrame([[1, 2], [3, 4]])
>>> repr_params = pd.io.formats.format.get_dataframe_repr_params()
>>> repr(df) == df.to_string(**repr_params)
True
Definition at line 351 of file format.py.
get_format_datetime64()
Callable pandas.io.formats.format.get_format_datetime64 (bool is_dates_only, str nat_rep = "NaT", str | None date_format = None)
Return a formatter callable taking a datetime64 as input and providing
a string as output
Definition at line 1643 of file format.py.
Referenced by pandas.io.formats.format._Datetime64TZFormatter._format_strings().
get_format_timedelta64()
Callable pandas.io.formats.format.get_format_timedelta64 (TimedeltaArray values, str | float nat_rep = "NaT", bool box = False)
Return a formatter function for a range of timedeltas.
These will all have the same format argument
If box, then show the return in quotes
Definition at line 1692 of file format.py.
get_level_lengths()
list[dict[int, int]] pandas.io.formats.format.get_level_lengths (Any levels, bool | object | str sentinel = "")
For each index in each level the function returns lengths of indexes.
Parameters
----------
levels : list of lists
    List of values on for level.
sentinel : string, optional
    Value which states that no new index starts on there.
Returns
-------
Returns list of maps. For each level returns map of indexes (key is index
in row and value is length of index).
Definition at line 2002 of file format.py.
get_precision()
int pandas.io.formats.format.get_precision (np.ndarray | Sequence[float] array)
Definition at line 1609 of file format.py.
get_series_repr_params()
dict[str, Any] pandas.io.formats.format.get_series_repr_params ()
Get the parameters used to repr(Series) calls using Series.to_string.
Supplying these parameters to Series.to_string is equivalent to calling
``repr(series)``. This is useful if you want to adjust the series repr output.
.. versionadded:: 1.4.0
Example
-------
>>> import pandas as pd
>>>
>>> ser = pd.Series([1, 2, 3, 4])
>>> repr_params = pd.io.formats.format.get_series_repr_params()
>>> repr(ser) == ser.to_string(**repr_params)
True
Definition at line 384 of file format.py.
save_to_buffer()
str | None pandas.io.formats.format.save_to_buffer (str string, FilePath | WriteBuffer[str] | None buf = None, str | None encoding = None)
Perform serialization. Write to buf or return as string if buf is None.
Definition at line 1025 of file format.py.
References _get_buffer().
Referenced by pandas.io.formats.format.DataFrameRenderer.to_html(), and pandas.io.formats.format.DataFrameRenderer.to_string().
set_eng_float_format()
None pandas.io.formats.format.set_eng_float_format (int accuracy = 3, bool use_eng_prefix = False)
Format float representation in DataFrame with SI notation.
Parameters
----------
accuracy : int, default 3
    Number of decimal digits after the floating point.
use_eng_prefix : bool, default False
    Whether to represent a value with SI prefixes.
Returns
-------
None
Examples
--------
>>> df = pd.DataFrame([1e-9, 1e-3, 1, 1e3, 1e6])
>>> df
              0
0  1.000000e-09
1  1.000000e-03
2  1.000000e+00
3  1.000000e+03
4  1.000000e+06
>>> pd.set_eng_float_format(accuracy=1)
>>> df
         0
0  1.0E-09
1  1.0E-03
2  1.0E+00
3  1.0E+03
4  1.0E+06
>>> pd.set_eng_float_format(use_eng_prefix=True)
>>> df
        0
0  1.000n
1  1.000m
2   1.000
3  1.000k
4  1.000M
>>> pd.set_eng_float_format(accuracy=1, use_eng_prefix=True)
>>> df
      0
0  1.0n
1  1.0m
2   1.0
3  1.0k
4  1.0M
>>> pd.set_option("display.float_format", None)  # unset option
Definition at line 1944 of file format.py.
Variable Documentation
common_docstring
Final pandas.io.formats.format.common_docstring
Definition at line 110 of file format.py.
return_docstring
Final pandas.io.formats.format.return_docstring
Initial value:
=  """
        Returns
        -------
        str or None
            If buf is None, returns the result as a string. Otherwise returns
            None.
    """
Definition at line 180 of file format.py.
VALID_JUSTIFY_PARAMETERS
tuple pandas.io.formats.format.VALID_JUSTIFY_PARAMETERS
Initial value:
=  (
    "left",
    "right",
    "center",
    "justify",
    "justify-all",
    "start",
    "end",
    "inherit",
    "match-parent",
    "initial",
    "unset",
)
Definition at line 166 of file format.py.