Code Cloning Analysis: pandas.core.window.rolling.RollingAndExpandingMixin Class Reference
pandas.core.window.rolling.RollingAndExpandingMixin Class Reference
Public Member Functions
count (self, bool numeric_only=False)
apply (self, Callable[..., Any] func, bool raw=False, Literal["cython", "numba"]|None engine=None, dict[str, bool]|None engine_kwargs=None, tuple[Any,...]|None args=None, dict[str, Any]|None kwargs=None)
sum (self, bool numeric_only=False, Literal["cython", "numba"]|None engine=None, dict[str, bool]|None engine_kwargs=None)
max (self, bool numeric_only=False, Literal["cython", "numba"]|None engine=None, dict[str, bool]|None engine_kwargs=None)
min (self, bool numeric_only=False, Literal["cython", "numba"]|None engine=None, dict[str, bool]|None engine_kwargs=None)
mean (self, bool numeric_only=False, Literal["cython", "numba"]|None engine=None, dict[str, bool]|None engine_kwargs=None)
median (self, bool numeric_only=False, Literal["cython", "numba"]|None engine=None, dict[str, bool]|None engine_kwargs=None)
std (self, int ddof=1, bool numeric_only=False, Literal["cython", "numba"]|None engine=None, dict[str, bool]|None engine_kwargs=None)
var (self, int ddof=1, bool numeric_only=False, Literal["cython", "numba"]|None engine=None, dict[str, bool]|None engine_kwargs=None)
skew (self, bool numeric_only=False)
sem (self, int ddof=1, bool numeric_only=False)
kurt (self, bool numeric_only=False)
quantile (self, float q, QuantileInterpolation interpolation="linear", bool numeric_only=False)
rank (self, WindowingRankType method="average", bool ascending=True, bool pct=False, bool numeric_only=False)
cov (self, DataFrame|Series|None other=None, bool|None pairwise=None, int ddof=1, bool numeric_only=False)
corr (self, DataFrame|Series|None other=None, bool|None pairwise=None, int ddof=1, bool numeric_only=False)
Public Member Functions inherited from pandas.core.window.rolling.BaseWindow
None __init__ (self, NDFrame obj, window=None, int|None min_periods=None, bool|None center=False, str|None win_type=None, Axis axis=0, str|Index|None on=None, str|None closed=None, int|None step=None, str method="single", *, selection=None)
__getattr__ (self, str attr)
str __repr__ (self)
Iterator __iter__ (self)
aggregate (self, func, *args, **kwargs)
Public Member Functions inherited from pandas.core.base.SelectionMixin
int ndim (self)
__getitem__ (self, key)
Protected Member Functions
Callable[[np.ndarray, np.ndarray, np.ndarray, int], np.ndarray] _generate_cython_apply_func (self, tuple[Any,...] args, dict[str, Any] kwargs, bool|np.bool_ raw, Callable[..., Any] function)
Protected Member Functions inherited from pandas.core.window.rolling.BaseWindow
None _validate (self)
None _check_window_bounds (self, np.ndarray start, np.ndarray end, int num_vals)
Index _slice_axis_for_step (self, Index index, Sized|None result=None)
None _validate_numeric_only (self, str name, bool numeric_only)
NDFrameT _make_numeric_only (self, NDFrameT obj)
NDFrameT _create_data (self, NDFrameT obj, bool numeric_only=False)
_gotitem (self, key, ndim, subset=None)
_dir_additions (self)
np.ndarray _prep_values (self, ArrayLike values)
None _insert_on_column (self, DataFrame result, DataFrame obj)
npt.NDArray[np.int64]|None _index_array (self)
DataFrame _resolve_output (self, DataFrame out, DataFrame obj)
BaseIndexer _get_window_indexer (self)
Series _apply_series (self, Callable[..., ArrayLike] homogeneous_func, str|None name=None)
DataFrame|Series _apply_columnwise (self, Callable[..., ArrayLike] homogeneous_func, str name, bool numeric_only=False)
DataFrame|Series _apply_tablewise (self, Callable[..., ArrayLike] homogeneous_func, str|None name=None, bool numeric_only=False)
DataFrame|Series _apply_pairwise (self, DataFrame|Series target, DataFrame|Series|None other, bool|None pairwise, Callable[[DataFrame|Series, DataFrame|Series], DataFrame|Series] func, bool numeric_only)
_apply (self, Callable[..., Any] func, str name, bool numeric_only=False, tuple[Any,...] numba_args=(), **kwargs)
_numba_apply (self, Callable[..., Any] func, dict[str, bool]|None engine_kwargs=None, **func_kwargs)
Protected Member Functions inherited from pandas.core.base.SelectionMixin
_selection_list (self)
_selected_obj (self)
_obj_with_exclusions (self)
_infer_selection (self, key, Series|DataFrame subset)
Additional Inherited Members
Public Attributes inherited from pandas.core.window.rolling.BaseWindow
on = on
closed = closed
step = step
window = window
min_periods = min_periods
center = center
win_type = win_type
int axis = obj._get_axis_number(axis) if axis is not None else None
str method = method
Public Attributes inherited from pandas.core.base.SelectionMixin
obj
Static Public Attributes inherited from pandas.core.base.SelectionMixin
frozenset exclusions [Hashable]
agg = aggregate
Protected Attributes inherited from pandas.core.window.rolling.BaseWindow
int|None _win_freq_i8 = None
_on = self.obj.index
Protected Attributes inherited from pandas.core.base.SelectionMixin
_selection_list
Static Protected Attributes inherited from pandas.core.window.rolling.BaseWindow
list _attributes = []
Static Protected Attributes inherited from pandas.core.base.SelectionMixin
IndexLabel _selection = None
list _internal_names = ["_cache", "__setstate__"]
_internal_names_set = set(_internal_names)
Detailed Description
Definition at line 1466 of file rolling.py.
Member Function Documentation
_generate_cython_apply_func()
Callable[[np.ndarray, np.ndarray, np.ndarray, int], np.ndarray] pandas.core.window.rolling.RollingAndExpandingMixin._generate_cython_apply_func (self, tuple[Any, ...] args, dict[str, Any] kwargs, bool | np.bool_ raw, Callable[..., Any] function) protected
Definition at line 1514 of file rolling.py.
apply()
pandas.core.window.rolling.RollingAndExpandingMixin.apply (self, Callable[..., Any] func, bool raw = False, Literal["cython", "numba"] | None engine = None, dict[str, bool] | None engine_kwargs = None, tuple[Any, ...] | None args = None, dict[str, Any] | None kwargs = None)
Definition at line 1471 of file rolling.py.
Referenced by pandas.core.window.rolling.BaseWindow._apply(), pandas.core.generic.NDFrame.backfill(), pandas.io.formats.style.Styler.background_gradient(), pandas.io.formats.style.Styler.bar(), sklearn.ensemble._forest.RandomTreesEmbedding.fit_transform(), PIL.ImageCms.Flags.GRIDPOINTS(), pandas.io.formats.style.Styler.highlight_between(), pandas.io.formats.style.Styler.highlight_max(), pandas.io.formats.style.Styler.highlight_min(), pandas.io.formats.style.Styler.highlight_null(), pandas.io.formats.style.Styler.highlight_quantile(), and sklearn.ensemble._forest.RandomTreesEmbedding.transform().
corr()
pandas.core.window.rolling.RollingAndExpandingMixin.corr (self, DataFrame | Series | None other = None, bool | None pairwise = None, int ddof = 1, bool numeric_only = False)
Definition at line 1797 of file rolling.py.
count()
pandas.core.window.rolling.RollingAndExpandingMixin.count (self, bool numeric_only = False)
Definition at line 1467 of file rolling.py.
Referenced by pandas.core.window.rolling.Rolling._validate_datetimelike_monotonic(), PIL.ImageStat.Stat.mean(), PIL.ImageStat.Stat.median(), PIL.ImageStat.Stat.rms(), and PIL.ImageStat.Stat.var().
cov()
pandas.core.window.rolling.RollingAndExpandingMixin.cov (self, DataFrame | Series | None other = None, bool | None pairwise = None, int ddof = 1, bool numeric_only = False)
Definition at line 1750 of file rolling.py.
kurt()
pandas.core.window.rolling.RollingAndExpandingMixin.kurt (self, bool numeric_only = False)
Definition at line 1707 of file rolling.py.
max()
pandas.core.window.rolling.RollingAndExpandingMixin.max (self, bool numeric_only = False, Literal["cython", "numba"] | None engine = None, dict[str, bool] | None engine_kwargs = None)
Definition at line 1561 of file rolling.py.
mean()
pandas.core.window.rolling.RollingAndExpandingMixin.mean (self, bool numeric_only = False, Literal["cython", "numba"] | None engine = None, dict[str, bool] | None engine_kwargs = None)
Definition at line 1605 of file rolling.py.
Referenced by scipy.stats._continuous_distns.norminvgauss_gen._fitstart().
median()
pandas.core.window.rolling.RollingAndExpandingMixin.median (self, bool numeric_only = False, Literal["cython", "numba"] | None engine = None, dict[str, bool] | None engine_kwargs = None)
Definition at line 1627 of file rolling.py.
min()
pandas.core.window.rolling.RollingAndExpandingMixin.min (self, bool numeric_only = False, Literal["cython", "numba"] | None engine = None, dict[str, bool] | None engine_kwargs = None)
Definition at line 1583 of file rolling.py.
quantile()
pandas.core.window.rolling.RollingAndExpandingMixin.quantile (self, float q, QuantileInterpolation interpolation = "linear", bool numeric_only = False)
Definition at line 1715 of file rolling.py.
rank()
pandas.core.window.rolling.RollingAndExpandingMixin.rank (self, WindowingRankType method = "average", bool ascending = True, bool pct = False, bool numeric_only = False)
Definition at line 1734 of file rolling.py.
sem()
pandas.core.window.rolling.RollingAndExpandingMixin.sem (self, int ddof = 1, bool numeric_only = False)
Definition at line 1700 of file rolling.py.
skew()
pandas.core.window.rolling.RollingAndExpandingMixin.skew (self, bool numeric_only = False)
Definition at line 1692 of file rolling.py.
std()
pandas.core.window.rolling.RollingAndExpandingMixin.std (self, int ddof = 1, bool numeric_only = False, Literal["cython", "numba"] | None engine = None, dict[str, bool] | None engine_kwargs = None)
Definition at line 1648 of file rolling.py.
Referenced by pandas.core.window.rolling.Rolling._validate_datetimelike_monotonic().
sum()
pandas.core.window.rolling.RollingAndExpandingMixin.sum (self, bool numeric_only = False, Literal["cython", "numba"] | None engine = None, dict[str, bool] | None engine_kwargs = None)
Definition at line 1539 of file rolling.py.
Referenced by PIL.ImageStat.Stat.mean(), numpy.core.tests.test_simd._SIMD_ALL.test_arithmetic_reduce_sum(), and PIL.ImageStat.Stat.var().
var()
pandas.core.window.rolling.RollingAndExpandingMixin.var (self, int ddof = 1, bool numeric_only = False, Literal["cython", "numba"] | None engine = None, dict[str, bool] | None engine_kwargs = None)
Definition at line 1672 of file rolling.py.
Referenced by PIL.ImageStat.Stat.stddev().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/core/window/rolling.py