Code Cloning Analysis: joblib.test.test_memory Namespace Reference
joblib.test.test_memory Namespace Reference
Classes
class DummyStoreBackend
class IncompleteStoreBackend
class TestCacheValidationCallback
class TestMemorizedFunc
Functions
f (x, y=1)
Module-level variables for the tests.
check_identity_lazy (func, accumulator, location)
Helper function for the tests.
corrupt_single_cache_item (memory)
monkeypatch_cached_func_warn (func, monkeypatch_fixture)
test_memory_integration (tmpdir)
Tests.
test_parallel_call_cached_function_defined_in_jupyter (tmpdir, call_before_reducing)
test_no_memory ()
test_memory_kwarg (tmpdir)
test_memory_lambda (tmpdir)
test_memory_name_collision (tmpdir)
test_memory_warning_lambda_collisions (tmpdir)
test_memory_warning_collision_detection (tmpdir)
test_memory_partial (tmpdir)
test_memory_eval (tmpdir)
count_and_append (x=[])
test_argument_change (tmpdir)
test_memory_numpy (tmpdir, mmap_mode)
test_memory_numpy_check_mmap_mode (tmpdir, monkeypatch)
test_memory_exception (tmpdir)
test_memory_ignore (tmpdir)
test_memory_ignore_decorated (tmpdir)
test_memory_args_as_kwargs (tmpdir)
test_partial_decoration (tmpdir, ignore, verbose, mmap_mode)
test_func_dir (tmpdir)
test_persistence (tmpdir)
test_check_call_in_cache (tmpdir, consider_cache_valid)
test_call_and_shelve (tmpdir)
test_call_and_shelve_lazily_load_stored_result (tmpdir)
test_memorized_pickling (tmpdir)
test_memorized_repr (tmpdir)
test_memory_file_modification (capsys, tmpdir, monkeypatch)
_function_to_cache (a, b)
_sum (a, b)
_product (a, b)
test_memory_in_memory_function_code_change (tmpdir)
test_clear_memory_with_none_location ()
func_with_kwonly_args (a, b, *, kw1="kw1", kw2="kw2")
float func_with_signature (int a, float b)
test_memory_func_with_kwonly_args (tmpdir)
test_memory_func_with_signature (tmpdir)
_setup_toy_cache (tmpdir, num_inputs=10)
test__get_items (tmpdir)
test__get_items_to_delete (tmpdir)
test_memory_reduce_size_bytes_limit (tmpdir)
test_memory_reduce_size_items_limit (tmpdir)
test_memory_reduce_size_age_limit (tmpdir)
test_memory_clear (tmpdir)
fast_func_with_complex_output ()
fast_func_with_conditional_complex_output (complex_output=True)
test_cached_function_race_condition_when_persisting_output (tmpdir, capfd)
test_cached_function_race_condition_when_persisting_output_2 (tmpdir, capfd)
test_memory_recomputes_after_an_error_while_loading_results (tmpdir, monkeypatch)
test_register_invalid_store_backends_key (invalid_prefix)
test_register_invalid_store_backends_object ()
test_memory_default_store_backend ()
test_warning_on_unknown_location_type ()
test_instanciate_incomplete_store_backend ()
test_dummy_store_backend ()
test_instanciate_store_backend_with_pathlib_path ()
test_filesystem_store_backend_repr (tmpdir)
test_memory_objects_repr (tmpdir)
test_memorized_result_pickle (tmpdir)
compare (left, right, ignored_attrs=None)
test_memory_pickle_dump_load (tmpdir, memory_kwargs)
test_info_log (tmpdir, caplog)
test_memory_creates_gitignore (location)
Detailed Description
Test the memory module.
Function Documentation
_function_to_cache()
joblib.test.test_memory._function_to_cache (a, b) protected
Definition at line 798 of file test_memory.py.
_product()
joblib.test.test_memory._product (a, b) protected
Definition at line 807 of file test_memory.py.
_setup_toy_cache()
joblib.test.test_memory._setup_toy_cache (tmpdir, num_inputs = 10) protected
Definition at line 873 of file test_memory.py.
_sum()
joblib.test.test_memory._sum (a, b) protected
Definition at line 803 of file test_memory.py.
check_identity_lazy()
joblib.test.test_memory.check_identity_lazy (func, accumulator, location)
Helper function for the tests.
Given a function and an accumulator (a list that grows every
time the function is called), check that the function can be
decorated by memory to be a lazy identity.
Definition at line 54 of file test_memory.py.
Referenced by test_memory_integration(), and test_no_memory().
compare()
joblib.test.test_memory.compare (left, right, ignored_attrs = None)
Definition at line 1351 of file test_memory.py.
corrupt_single_cache_item()
joblib.test.test_memory.corrupt_single_cache_item (memory)
Definition at line 69 of file test_memory.py.
count_and_append()
joblib.test.test_memory.count_and_append (x = [])
A function with a side effect in its arguments.
Return the length of its argument and append one element.
Definition at line 374 of file test_memory.py.
f()
joblib.test.test_memory.f (x, y = 1)
Module-level variables for the tests.
A module-level function for testing purposes.
Definition at line 47 of file test_memory.py.
fast_func_with_complex_output()
joblib.test.test_memory.fast_func_with_complex_output ()
Definition at line 1059 of file test_memory.py.
fast_func_with_conditional_complex_output()
joblib.test.test_memory.fast_func_with_conditional_complex_output (complex_output = True)
Definition at line 1064 of file test_memory.py.
func_with_kwonly_args()
joblib.test.test_memory.func_with_kwonly_args (a, b, * , kw1 = "kw1", kw2 = "kw2")
Definition at line 832 of file test_memory.py.
func_with_signature()
float joblib.test.test_memory.func_with_signature (int a, float b)
Definition at line 836 of file test_memory.py.
monkeypatch_cached_func_warn()
joblib.test.test_memory.monkeypatch_cached_func_warn (func, monkeypatch_fixture)
Definition at line 76 of file test_memory.py.
test__get_items()
joblib.test.test_memory.test__get_items (tmpdir)
Definition at line 894 of file test_memory.py.
test__get_items_to_delete()
joblib.test.test_memory.test__get_items_to_delete (tmpdir)
Definition at line 917 of file test_memory.py.
test_argument_change()
joblib.test.test_memory.test_argument_change (tmpdir)
Check that if a function has a side effect in its arguments, it
should use the hash of changing arguments.
Definition at line 384 of file test_memory.py.
test_cached_function_race_condition_when_persisting_output()
joblib.test.test_memory.test_cached_function_race_condition_when_persisting_output (tmpdir, capfd)
Definition at line 1070 of file test_memory.py.
test_cached_function_race_condition_when_persisting_output_2()
joblib.test.test_memory.test_cached_function_race_condition_when_persisting_output_2 (tmpdir, capfd)
Definition at line 1090 of file test_memory.py.
test_call_and_shelve()
joblib.test.test_memory.test_call_and_shelve (tmpdir)
Definition at line 638 of file test_memory.py.
test_call_and_shelve_lazily_load_stored_result()
joblib.test.test_memory.test_call_and_shelve_lazily_load_stored_result (tmpdir)
Check call_and_shelve only load stored data if needed.
Definition at line 661 of file test_memory.py.
test_check_call_in_cache()
joblib.test.test_memory.test_check_call_in_cache (tmpdir, consider_cache_valid)
Definition at line 616 of file test_memory.py.
test_clear_memory_with_none_location()
joblib.test.test_memory.test_clear_memory_with_none_location ()
Definition at line 827 of file test_memory.py.
test_dummy_store_backend()
joblib.test.test_memory.test_dummy_store_backend ()
Definition at line 1254 of file test_memory.py.
test_filesystem_store_backend_repr()
joblib.test.test_memory.test_filesystem_store_backend_repr (tmpdir)
Definition at line 1275 of file test_memory.py.
test_func_dir()
joblib.test.test_memory.test_func_dir (tmpdir)
Definition at line 560 of file test_memory.py.
test_info_log()
joblib.test.test_memory.test_info_log (tmpdir, caplog)
Definition at line 1411 of file test_memory.py.
test_instanciate_incomplete_store_backend()
joblib.test.test_memory.test_instanciate_incomplete_store_backend ()
Definition at line 1240 of file test_memory.py.
test_instanciate_store_backend_with_pathlib_path()
joblib.test.test_memory.test_instanciate_store_backend_with_pathlib_path ()
Definition at line 1265 of file test_memory.py.
test_memorized_pickling()
joblib.test.test_memory.test_memorized_pickling (tmpdir)
Definition at line 697 of file test_memory.py.
test_memorized_repr()
joblib.test.test_memory.test_memorized_repr (tmpdir)
Definition at line 709 of file test_memory.py.
test_memorized_result_pickle()
joblib.test.test_memory.test_memorized_result_pickle (tmpdir)
Definition at line 1327 of file test_memory.py.
test_memory_args_as_kwargs()
joblib.test.test_memory.test_memory_args_as_kwargs (tmpdir)
Non-regression test against 0.12.0 changes.
https://github.com/joblib/joblib/pull/751
Definition at line 526 of file test_memory.py.
test_memory_clear()
joblib.test.test_memory.test_memory_clear (tmpdir)
Definition at line 1049 of file test_memory.py.
test_memory_creates_gitignore()
joblib.test.test_memory.test_memory_creates_gitignore (location)
Test that using the memory object automatically creates a `.gitignore` file
within the new cache directory.
Definition at line 1559 of file test_memory.py.
test_memory_default_store_backend()
joblib.test.test_memory.test_memory_default_store_backend ()
Definition at line 1216 of file test_memory.py.
test_memory_eval()
joblib.test.test_memory.test_memory_eval (tmpdir)
Definition at line 364 of file test_memory.py.
test_memory_exception()
joblib.test.test_memory.test_memory_exception (tmpdir)
Smoketest the exception handling of Memory.
Definition at line 459 of file test_memory.py.
test_memory_file_modification()
joblib.test.test_memory.test_memory_file_modification (capsys, tmpdir, monkeypatch)
Definition at line 741 of file test_memory.py.
test_memory_func_with_kwonly_args()
joblib.test.test_memory.test_memory_func_with_kwonly_args (tmpdir)
Definition at line 840 of file test_memory.py.
test_memory_func_with_signature()
joblib.test.test_memory.test_memory_func_with_signature (tmpdir)
Definition at line 866 of file test_memory.py.
test_memory_ignore()
joblib.test.test_memory.test_memory_ignore (tmpdir)
Definition at line 480 of file test_memory.py.
test_memory_ignore_decorated()
joblib.test.test_memory.test_memory_ignore_decorated (tmpdir)
Definition at line 499 of file test_memory.py.
test_memory_in_memory_function_code_change()
joblib.test.test_memory.test_memory_in_memory_function_code_change (tmpdir)
Definition at line 811 of file test_memory.py.
test_memory_integration()
joblib.test.test_memory.test_memory_integration (tmpdir)
Tests.
Simple test of memory lazy evaluation.
Definition at line 92 of file test_memory.py.
References check_identity_lazy().
test_memory_kwarg()
joblib.test.test_memory.test_memory_kwarg (tmpdir)
Definition at line 260 of file test_memory.py.
test_memory_lambda()
joblib.test.test_memory.test_memory_lambda (tmpdir)
Definition at line 276 of file test_memory.py.
test_memory_name_collision()
joblib.test.test_memory.test_memory_name_collision (tmpdir)
Definition at line 288 of file test_memory.py.
test_memory_numpy()
joblib.test.test_memory.test_memory_numpy (tmpdir, mmap_mode)
Definition at line 400 of file test_memory.py.
test_memory_numpy_check_mmap_mode()
joblib.test.test_memory.test_memory_numpy_check_mmap_mode (tmpdir, monkeypatch)
Check that mmap_mode is respected even at the first call
Definition at line 420 of file test_memory.py.
test_memory_objects_repr()
joblib.test.test_memory.test_memory_objects_repr (tmpdir)
Definition at line 1295 of file test_memory.py.
test_memory_partial()
joblib.test.test_memory.test_memory_partial (tmpdir)
Definition at line 348 of file test_memory.py.
test_memory_pickle_dump_load()
joblib.test.test_memory.test_memory_pickle_dump_load (tmpdir, memory_kwargs)
Definition at line 1371 of file test_memory.py.
test_memory_recomputes_after_an_error_while_loading_results()
joblib.test.test_memory.test_memory_recomputes_after_an_error_while_loading_results (tmpdir, monkeypatch)
Definition at line 1113 of file test_memory.py.
test_memory_reduce_size_age_limit()
joblib.test.test_memory.test_memory_reduce_size_age_limit (tmpdir)
Definition at line 1012 of file test_memory.py.
test_memory_reduce_size_bytes_limit()
joblib.test.test_memory.test_memory_reduce_size_bytes_limit (tmpdir)
Definition at line 957 of file test_memory.py.
test_memory_reduce_size_items_limit()
joblib.test.test_memory.test_memory_reduce_size_items_limit (tmpdir)
Definition at line 985 of file test_memory.py.
test_memory_warning_collision_detection()
joblib.test.test_memory.test_memory_warning_collision_detection (tmpdir)
Definition at line 330 of file test_memory.py.
test_memory_warning_lambda_collisions()
joblib.test.test_memory.test_memory_warning_lambda_collisions (tmpdir)
Definition at line 314 of file test_memory.py.
test_no_memory()
joblib.test.test_memory.test_no_memory ()
Test memory with location=None: no memoize
Definition at line 244 of file test_memory.py.
References check_identity_lazy().
test_parallel_call_cached_function_defined_in_jupyter()
joblib.test.test_memory.test_parallel_call_cached_function_defined_in_jupyter (tmpdir, call_before_reducing)
Definition at line 139 of file test_memory.py.
test_partial_decoration()
joblib.test.test_memory.test_partial_decoration (tmpdir, ignore, verbose, mmap_mode)
Definition at line 547 of file test_memory.py.
test_persistence()
joblib.test.test_memory.test_persistence (tmpdir)
Definition at line 592 of file test_memory.py.
test_register_invalid_store_backends_key()
joblib.test.test_memory.test_register_invalid_store_backends_key (invalid_prefix)
Definition at line 1201 of file test_memory.py.
test_register_invalid_store_backends_object()
joblib.test.test_memory.test_register_invalid_store_backends_object ()
Definition at line 1208 of file test_memory.py.
test_warning_on_unknown_location_type()
joblib.test.test_memory.test_warning_on_unknown_location_type ()
Definition at line 1223 of file test_memory.py.