Code Cloning Analysis: scipy.stats._ksstats Namespace Reference
scipy.stats._ksstats Namespace Reference
Functions
_log_nfactorial_div_n_pow_n (n)
_clip_prob (p)
_select_and_clip_prob (cdfprob, sfprob, cdf=True)
_kolmogn_DMTW (n, d, cdf=True)
_pomeranz_compute_j1j2 (i, n, ll, ceilf, roundf)
_kolmogn_Pomeranz (n, x, cdf=True)
_kolmogn_PelzGood (n, x, cdf=True)
_kolmogn (n, x, cdf=True)
_kolmogn_p (n, x)
_kolmogni (n, p, q)
kolmogn (n, x, cdf=True)
kolmognp (n, x)
kolmogni (n, q, cdf=True)
Variables
int _E128 = 128
_EP128 = np.ldexp(np.longdouble(1), _E128)
_EM128 = np.ldexp(np.longdouble(1), -_E128)
_SQRT2PI = np.sqrt(2 * np.pi)
_LOG_2PI = np.log(2 * np.pi)
int _MIN_LOG = -708
_SQRT3 = np.sqrt(3)
int _PI_SQUARED = np.pi ** 2
int _PI_FOUR = np.pi ** 4
int _PI_SIX = np.pi ** 6
list _STIRLING_COEFFS
Function Documentation
_clip_prob()
scipy.stats._ksstats._clip_prob (p) protected
clips a probability to range 0<=p<=1.
Definition at line 103 of file _ksstats.py.
Referenced by _kolmogn(), and _select_and_clip_prob().
_kolmogn()
scipy.stats._ksstats._kolmogn (n, x, cdf = True) protected
Computes the CDF(or SF) for the two-sided Kolmogorov-Smirnov statistic.
x must be of type float, n of type integer.
Simard & L'Ecuyer (2011) [7].
Definition at line 374 of file _ksstats.py.
References _clip_prob(), _kolmogn_DMTW(), _kolmogn_PelzGood(), _kolmogn_Pomeranz(), and _select_and_clip_prob().
Referenced by _kolmogni(), and kolmogn().
_kolmogn_DMTW()
scipy.stats._ksstats._kolmogn_DMTW (n, d, cdf = True) protected
Computes the Kolmogorov CDF:  Pr(D_n <= d) using the MTW approach to
the Durbin matrix algorithm.
Durbin (1968); Marsaglia, Tsang, Wang (2003). [1], [3].
Definition at line 114 of file _ksstats.py.
References _select_and_clip_prob().
Referenced by _kolmogn().
_kolmogn_p()
scipy.stats._ksstats._kolmogn_p (n, x) protected
Computes the PDF for the two-sided Kolmogorov-Smirnov statistic.
x must be of type float, n of type integer.
Definition at line 434 of file _ksstats.py.
References kolmogn().
Referenced by kolmognp().
_kolmogn_PelzGood()
scipy.stats._ksstats._kolmogn_PelzGood (n, x, cdf = True) protected
Computes the Pelz-Good approximation to Prob(Dn <= x) with 0<=x<=1.
Start with Li-Chien, Korolyuk approximation:
    Prob(Dn <= x) ~ K0(z) + K1(z)/sqrt(n) + K2(z)/n + K3(z)/n**1.5
where z = x*sqrt(n).
Transform each K_(z) using Jacobi theta functions into a form suitable
for small z.
Pelz-Good (1976). [6]
Definition at line 291 of file _ksstats.py.
References _select_and_clip_prob().
Referenced by _kolmogn().
_kolmogn_Pomeranz()
scipy.stats._ksstats._kolmogn_Pomeranz (n, x, cdf = True) protected
Computes Pr(D_n <= d) using the Pomeranz recursion algorithm.
Pomeranz (1974) [2]
Definition at line 207 of file _ksstats.py.
References _pomeranz_compute_j1j2(), and _select_and_clip_prob().
Referenced by _kolmogn().
_kolmogni()
scipy.stats._ksstats._kolmogni (n, p, q) protected
Computes the PPF/ISF of kolmogn.
n of type integer, n>= 1
p is the CDF, q the SF, p+q=1
Definition at line 476 of file _ksstats.py.
References _kolmogn().
Referenced by kolmogni().
_log_nfactorial_div_n_pow_n()
scipy.stats._ksstats._log_nfactorial_div_n_pow_n (n) protected
Definition at line 93 of file _ksstats.py.
_pomeranz_compute_j1j2()
scipy.stats._ksstats._pomeranz_compute_j1j2 (i, n, ll, ceilf, roundf) protected
Compute the endpoints of the interval for row i.
Definition at line 189 of file _ksstats.py.
Referenced by _kolmogn_Pomeranz().
_select_and_clip_prob()
scipy.stats._ksstats._select_and_clip_prob (cdfprob, sfprob, cdf = True) protected
Selects either the CDF or SF, and then clips to range 0<=p<=1.
Definition at line 108 of file _ksstats.py.
References _clip_prob().
Referenced by _kolmogn(), _kolmogn_DMTW(), _kolmogn_PelzGood(), and _kolmogn_Pomeranz().
kolmogn()
scipy.stats._ksstats.kolmogn (n, x, cdf = True)
Computes the CDF for the two-sided Kolmogorov-Smirnov distribution.
The two-sided Kolmogorov-Smirnov distribution has as its CDF Pr(D_n <= x),
for a sample of size n drawn from a distribution with CDF F(t), where
D_n &= sup_t |F_n(t) - F(t)|, and
F_n(t) is the Empirical Cumulative Distribution Function of the sample.
Parameters
----------
n : integer, array_like
    the number of samples
x : float, array_like
    The K-S statistic, float between 0 and 1
cdf : bool, optional
    whether to compute the CDF(default=true) or the SF.
Returns
-------
cdf : ndarray
    CDF (or SF it cdf is False) at the specified locations.
The return value has shape the result of numpy broadcasting n and x.
Definition at line 505 of file _ksstats.py.
References _kolmogn().
Referenced by _kolmogn_p().
kolmogni()
scipy.stats._ksstats.kolmogni (n, q, cdf = True)
Computes the PPF(or ISF) for the two-sided Kolmogorov-Smirnov distribution.
Parameters
----------
n : integer, array_like
    the number of samples
q : float, array_like
    Probabilities, float between 0 and 1
cdf : bool, optional
    whether to compute the PPF(default=true) or the ISF.
Returns
-------
ppf : ndarray
    PPF (or ISF if cdf is False) at the specified locations
The return value has shape the result of numpy broadcasting n and x.
Definition at line 571 of file _ksstats.py.
References _kolmogni().
kolmognp()
scipy.stats._ksstats.kolmognp (n, x)
Computes the PDF for the two-sided Kolmogorov-Smirnov distribution.
Parameters
----------
n : integer, array_like
    the number of samples
x : float, array_like
    The K-S statistic, float between 0 and 1
Returns
-------
pdf : ndarray
    The PDF at the specified locations
The return value has shape the result of numpy broadcasting n and x.
Definition at line 542 of file _ksstats.py.
References _kolmogn_p().
Variable Documentation
_E128
int scipy.stats._ksstats._E128 = 128 protected
Definition at line 73 of file _ksstats.py.
_EM128
scipy.stats._ksstats._EM128 = np.ldexp(np.longdouble(1), -_E128) protected
Definition at line 75 of file _ksstats.py.
_EP128
scipy.stats._ksstats._EP128 = np.ldexp(np.longdouble(1), _E128) protected
Definition at line 74 of file _ksstats.py.
_LOG_2PI
scipy.stats._ksstats._LOG_2PI = np.log(2 * np.pi) protected
Definition at line 78 of file _ksstats.py.
_MIN_LOG
int scipy.stats._ksstats._MIN_LOG = -708 protected
Definition at line 79 of file _ksstats.py.
_PI_FOUR
int scipy.stats._ksstats._PI_FOUR = np.pi ** 4 protected
Definition at line 82 of file _ksstats.py.
_PI_SIX
int scipy.stats._ksstats._PI_SIX = np.pi ** 6 protected
Definition at line 83 of file _ksstats.py.
_PI_SQUARED
int scipy.stats._ksstats._PI_SQUARED = np.pi ** 2 protected
Definition at line 81 of file _ksstats.py.
_SQRT2PI
scipy.stats._ksstats._SQRT2PI = np.sqrt(2 * np.pi) protected
Definition at line 77 of file _ksstats.py.
_SQRT3
scipy.stats._ksstats._SQRT3 = np.sqrt(3) protected
Definition at line 80 of file _ksstats.py.
_STIRLING_COEFFS
list scipy.stats._ksstats._STIRLING_COEFFS protected
Initial value:
=  [-2.955065359477124183e-2, 6.4102564102564102564e-3,
                    -1.9175269175269175269e-3, 8.4175084175084175084e-4,
                    -5.952380952380952381e-4, 7.9365079365079365079e-4,
                    -2.7777777777777777778e-3, 8.3333333333333333333e-2]
Definition at line 87 of file _ksstats.py.