Code Cloning Analysis: pip._vendor.chardet.latin1prober.Latin1Prober Class Reference
pip._vendor.chardet.latin1prober.Latin1Prober Class Reference
Public Member Functions
None __init__ (self)
None reset (self)
str charset_name (self)
str language (self)
ProbingState feed (self, Union[bytes, bytearray] byte_str)
float get_confidence (self)
Public Member Functions inherited from pip._vendor.chardet.charsetprober.CharSetProber
None __init__ (self, LanguageFilter lang_filter=LanguageFilter.NONE)
ProbingState state (self)
Protected Attributes
_last_char_class = OTH
list _freq_counter = []
Protected Attributes inherited from pip._vendor.chardet.charsetprober.CharSetProber
_state = ProbingState.DETECTING
Additional Inherited Members
Static Public Member Functions inherited from pip._vendor.chardet.charsetprober.CharSetProber
bytes filter_high_byte_only (Union[bytes, bytearray] buf)
bytearray filter_international_words (Union[bytes, bytearray] buf)
bytes remove_xml_tags (Union[bytes, bytearray] buf)
Public Attributes inherited from pip._vendor.chardet.charsetprober.CharSetProber
bool active = True
lang_filter = lang_filter
logger = logging.getLogger(__name__)
Static Public Attributes inherited from pip._vendor.chardet.charsetprober.CharSetProber
float SHORTCUT_THRESHOLD = 0.95
Detailed Description
Definition at line 100 of file latin1prober.py.
Constructor & Destructor Documentation
__init__()
None pip._vendor.chardet.latin1prober.Latin1Prober.__init__ (self)
Definition at line 101 of file latin1prober.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
charset_name()
str pip._vendor.chardet.latin1prober.Latin1Prober.charset_name (self)
Reimplemented from pip._vendor.chardet.charsetprober.CharSetProber.
Definition at line 113 of file latin1prober.py.
feed()
ProbingState pip._vendor.chardet.latin1prober.Latin1Prober.feed (self, Union[bytes, bytearray] byte_str)
Reimplemented from pip._vendor.chardet.charsetprober.CharSetProber.
Definition at line 120 of file latin1prober.py.
get_confidence()
float pip._vendor.chardet.latin1prober.Latin1Prober.get_confidence (self)
Reimplemented from pip._vendor.chardet.charsetprober.CharSetProber.
Definition at line 133 of file latin1prober.py.
language()
str pip._vendor.chardet.latin1prober.Latin1Prober.language (self)
Reimplemented from pip._vendor.chardet.charsetprober.CharSetProber.
Definition at line 117 of file latin1prober.py.
reset()
None pip._vendor.chardet.latin1prober.Latin1Prober.reset (self)
Reimplemented from pip._vendor.chardet.charsetprober.CharSetProber.
Definition at line 107 of file latin1prober.py.
Referenced by scipy._lib._docscrape.Reader.__init__().
Member Data Documentation
_freq_counter
list pip._vendor.chardet.latin1prober.Latin1Prober._freq_counter = [] protected
Definition at line 104 of file latin1prober.py.
_last_char_class
pip._vendor.chardet.latin1prober.Latin1Prober._last_char_class = OTH protected
Definition at line 103 of file latin1prober.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pip/_vendor/chardet/latin1prober.py