Code Cloning Analysis: scipy.integrate._quad_vec.SemiInfiniteFunc Class Reference
scipy.integrate._quad_vec.SemiInfiniteFunc Class Reference
Public Member Functions
__init__ (self, func, start, infty)
get_t (self, x)
__call__ (self, t)
Protected Attributes
_func = func
_start = start
int _sgn = -1 if infty < 0 else 1
float _tmin = sys.float_info.min**0.5
Detailed Description
Argument transform from (start, +-oo) to (0, 1)
Definition at line 29 of file _quad_vec.py.
Constructor & Destructor Documentation
__init__()
scipy.integrate._quad_vec.SemiInfiniteFunc.__init__ (self, func, start, infty)
Definition at line 33 of file _quad_vec.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
__call__()
scipy.integrate._quad_vec.SemiInfiniteFunc.__call__ (self, t)
Definition at line 48 of file _quad_vec.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), and scipy.interpolate._fitpack2.SphereBivariateSpline.ev().
get_t()
scipy.integrate._quad_vec.SemiInfiniteFunc.get_t (self, x)
Definition at line 41 of file _quad_vec.py.
Member Data Documentation
_func
scipy.integrate._quad_vec.SemiInfiniteFunc._func = func protected
Definition at line 34 of file _quad_vec.py.
_sgn
int scipy.integrate._quad_vec.SemiInfiniteFunc._sgn = -1 if infty < 0 else 1 protected
Definition at line 36 of file _quad_vec.py.
_start
scipy.integrate._quad_vec.SemiInfiniteFunc._start = start protected
Definition at line 35 of file _quad_vec.py.
Referenced by joblib.parallel.Parallel._get_outputs().
_tmin
float scipy.integrate._quad_vec.SemiInfiniteFunc._tmin = sys.float_info.min**0.5 protected
Definition at line 39 of file _quad_vec.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/integrate/_quad_vec.py