Code Cloning Analysis: scipy.io._harwell_boeing._fortran_format_parser.FortranFormatParser Class Reference
scipy.io._harwell_boeing._fortran_format_parser.FortranFormatParser Class Reference
Public Member Functions
__init__ (self)
parse (self, s)
Public Attributes
tokenizer = Tokenizer()
Protected Member Functions
_get_min (self, tokens)
_expect (self, token, tp)
_parse_format (self, tokens)
_next (self, tokens, tp)
Detailed Description
Parser for Fortran format strings. The parse method returns a *Format
instance.
Notes
-----
Only ExpFormat (exponential format for floating values) and IntFormat
(integer format) for now.
Definition at line 221 of file _fortran_format_parser.py.
Constructor & Destructor Documentation
__init__()
scipy.io._harwell_boeing._fortran_format_parser.FortranFormatParser.__init__ (self)
Definition at line 230 of file _fortran_format_parser.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
_expect()
scipy.io._harwell_boeing._fortran_format_parser.FortranFormatParser._expect (self, token, tp) protected
Definition at line 256 of file _fortran_format_parser.py.
Referenced by scipy.stats._distn_infrastructure.rv_discrete.expect().
_get_min()
scipy.io._harwell_boeing._fortran_format_parser.FortranFormatParser._get_min (self, tokens) protected
Definition at line 249 of file _fortran_format_parser.py.
_next()
scipy.io._harwell_boeing._fortran_format_parser.FortranFormatParser._next (self, tokens, tp) protected
Definition at line 304 of file _fortran_format_parser.py.
_parse_format()
scipy.io._harwell_boeing._fortran_format_parser.FortranFormatParser._parse_format (self, tokens) protected
Definition at line 260 of file _fortran_format_parser.py.
parse()
scipy.io._harwell_boeing._fortran_format_parser.FortranFormatParser.parse (self, s)
Definition at line 233 of file _fortran_format_parser.py.
Member Data Documentation
tokenizer
scipy.io._harwell_boeing._fortran_format_parser.FortranFormatParser.tokenizer = Tokenizer()
Definition at line 231 of file _fortran_format_parser.py.
Referenced by sklearn.feature_extraction.text._VectorizerMixin.build_tokenizer().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/io/_harwell_boeing/_fortran_format_parser.py