Code Cloning Analysis: fontTools.ttLib.tables._l_o_c_a.table__l_o_c_a Class Reference
fontTools.ttLib.tables._l_o_c_a.table__l_o_c_a Class Reference
Public Member Functions
decompile (self, data, ttFont)
compile (self, ttFont)
set (self, locations)
toXML (self, writer, ttFont)
__getitem__ (self, index)
__len__ (self)
Public Member Functions inherited from fontTools.ttLib.tables.DefaultTable.DefaultTable
__init__ (self, tag=None)
fromXML (self, name, attrs, content, ttFont)
__repr__ (self)
__eq__ (self, other)
__ne__ (self, other)
Public Attributes
locations = locations
Public Attributes inherited from fontTools.ttLib.tables.DefaultTable.DefaultTable
tableTag = Tag(tag)
data = data
ERROR
Additional Inherited Members
Static Public Attributes inherited from fontTools.ttLib.tables.DefaultTable.DefaultTable
list dependencies = []
Detailed Description
Index to Location table
The ``loca`` table stores the offsets in the ``glyf`` table that correspond
to the descriptions of each glyph. The glyphs are references by Glyph ID.
See also https://learn.microsoft.com/en-us/typography/opentype/spec/loca
Definition at line 10 of file _l_o_c_a.py.
Member Function Documentation
__getitem__()
fontTools.ttLib.tables._l_o_c_a.table__l_o_c_a.__getitem__ (self, index)
Definition at line 66 of file _l_o_c_a.py.
__len__()
fontTools.ttLib.tables._l_o_c_a.table__l_o_c_a.__len__ (self)
Definition at line 69 of file _l_o_c_a.py.
compile()
fontTools.ttLib.tables._l_o_c_a.table__l_o_c_a.compile (self, ttFont)
Reimplemented from fontTools.ttLib.tables.DefaultTable.DefaultTable.
Definition at line 41 of file _l_o_c_a.py.
Referenced by fontTools.ttLib.tables.TupleVariation.TupleVariation.getCoordWidth(), and PIL.FontFile.FontFile.save().
decompile()
fontTools.ttLib.tables._l_o_c_a.table__l_o_c_a.decompile (self, data, ttFont)
Reimplemented from fontTools.ttLib.tables.DefaultTable.DefaultTable.
Definition at line 21 of file _l_o_c_a.py.
Referenced by fontTools.ttLib.tables._c_m_a_p.CmapSubtable.newSubtable().
set()
fontTools.ttLib.tables._l_o_c_a.table__l_o_c_a.set (self, locations)
Definition at line 59 of file _l_o_c_a.py.
Referenced by matplotlib.contour.ContourSet.__init__(), matplotlib.layout_engine.ConstrainedLayoutEngine.__init__(), matplotlib.layout_engine.TightLayoutEngine.__init__(), matplotlib.transforms.TransformWrapper.__init__(), pip._vendor.requests.cookies.RequestsCookieJar.__setitem__(), matplotlib.axes._base._AxesBase._set_view(), mplot3d.axes3d.Axes3D._set_view(), matplotlib.axes._axes.Axes.pie(), pip._vendor.distlib.metadata.LegacyMetadata.read_file(), matplotlib.layout_engine.ConstrainedLayoutEngine.set(), matplotlib.layout_engine.TightLayoutEngine.set(), numpy.core.tests.test_simd._SIMD_ALL.test_lut(), and pip._vendor.distlib.metadata.LegacyMetadata.update().
toXML()
fontTools.ttLib.tables._l_o_c_a.table__l_o_c_a.toXML (self, writer, ttFont)
Reimplemented from fontTools.ttLib.tables.DefaultTable.DefaultTable.
Definition at line 62 of file _l_o_c_a.py.
Member Data Documentation
locations
fontTools.ttLib.tables._l_o_c_a.table__l_o_c_a.locations = locations
Definition at line 39 of file _l_o_c_a.py.
Referenced by fontTools.varLib.models.VariationModel.getSubModel().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ttLib/tables/_l_o_c_a.py