Code Cloning Analysis: sklearn.utils._testing Namespace Reference
sklearn.utils._testing Namespace Reference
Classes
class _IgnoreWarnings
class _Raises
class MinimalClassifier
class MinimalRegressor
class MinimalTransformer
class TempMemmap
Functions
ignore_warnings (obj=None, category=Warning)
assert_allclose (actual, desired, rtol=None, atol=0.0, equal_nan=True, err_msg="", verbose=True)
assert_allclose_dense_sparse (x, y, rtol=1e-07, atol=1e-9, err_msg="")
set_random_state (estimator, random_state=0)
_is_numpydoc ()
check_skip_network ()
_delete_folder (folder_path, warn=False)
create_memmap_backed_data (data, mmap_mode="r", return_folder=False)
_get_args (function, varargs=False)
_get_func_name (func)
check_docstring_parameters (func, doc=None, ignore=None)
_check_item_included (item_name, args)
_diff_key (line)
_get_diff_msg (docstrings_grouped)
_check_consistency_items (items_docs, type_or_desc, section, n_objects, descr_regex_pattern="", ignore_types=tuple())
assert_docstring_consistency (objects, include_params=False, exclude_params=None, include_attrs=False, exclude_attrs=None, include_returns=False, exclude_returns=None, descr_regex_pattern=None, ignore_types=tuple())
assert_run_python_script_without_output (source_code, pattern=".+", timeout=60)
_convert_container (container, constructor_name, columns_name=None, dtype=None, minversion=None, categorical_feature_names=None)
raises (expected_exc_type, match=None, may_pass=False, err_msg=None)
_array_api_for_tests (array_namespace, device)
_get_warnings_filters_info_list ()
get_pytest_filterwarning_lines ()
turn_warnings_into_errors ()
Variables
list __all__
SkipTest = unittest.case.SkipTest
bool ARRAY_API_COMPAT_FUNCTIONAL = True
skip_if_32bit = pytest.mark.skipif(_IS_32BIT, reason="skipped on 32bit platforms")
fails_if_unstable_openblas
skip_if_no_parallel
skip_if_array_api_compat_not_configured
if_safe_multiprocessing_with_blas
skip_if_no_numpydoc
Detailed Description
Testing utilities.
Function Documentation
_array_api_for_tests()
sklearn.utils._testing._array_api_for_tests (array_namespace, device) protected
Definition at line 1309 of file _testing.py.
_check_consistency_items()
sklearn.utils._testing._check_consistency_items (items_docs, type_or_desc, section, n_objects, descr_regex_pattern = "", ignore_types = tuple()) protected
Helper to check docstring consistency of all `items_docs`.
If item is not present in all objects, checking is skipped and warning raised.
If `regex` provided, match descriptions to all descriptions.
Parameters
----------
items_doc : dict of dict of str
    Dictionary where the key is the string type or description, value is
    a dictionary where the key is "type description" or "description"
    and the value is a list of object names with the same string type or
    description.
type_or_desc : {"type description", "description"}
    Whether to check type description or description between objects.
section : {"Parameters", "Attributes", "Returns"}
    Name of the section type.
n_objects : int
    Total number of objects.
descr_regex_pattern : str, default=""
    Regex pattern to match for description of all objects.
    Ignored when `type_or_desc="type description".
ignore_types : tuple of str, default=()
    Tuple of parameter/attribute/return names for which type description
    matching is ignored. Ignored when `type_or_desc="description".
Definition at line 688 of file _testing.py.
References _get_diff_msg().
Referenced by assert_docstring_consistency().
_check_item_included()
sklearn.utils._testing._check_item_included (item_name, args) protected
Helper to check if item should be included in checking.
Definition at line 630 of file _testing.py.
Referenced by assert_docstring_consistency().
_convert_container()
sklearn.utils._testing._convert_container (container, constructor_name, columns_name = None, dtype = None, minversion = None, categorical_feature_names = None) protected
Convert a given container to a specific array-like with a dtype.
Parameters
----------
container : array-like
    The container to convert.
constructor_name : {"list", "tuple", "array", "sparse", "dataframe", \
        "series", "index", "slice", "sparse_csr", "sparse_csc", \
        "sparse_csr_array", "sparse_csc_array", "pyarrow", "polars", \
        "polars_series"}
    The type of the returned container.
columns_name : index or array-like, default=None
    For pandas container supporting `columns_names`, it will affect
    specific names.
dtype : dtype, default=None
    Force the dtype of the container. Does not apply to `"slice"`
    container.
minversion : str, default=None
    Minimum version for package to install.
categorical_feature_names : list of str, default=None
    List of column names to cast to categorical dtype.
Returns
-------
converted_container
Definition at line 968 of file _testing.py.
_delete_folder()
sklearn.utils._testing._delete_folder (folder_path, warn = False) protected
Utility function to cleanup a temporary folder if still existing.
Copy from joblib.pool (for independence).
Definition at line 372 of file _testing.py.
_diff_key()
sklearn.utils._testing._diff_key (line) protected
Key for grouping output from `context_diff`.
Definition at line 639 of file _testing.py.
_get_args()
sklearn.utils._testing._get_args (function, varargs = False) protected
Helper to get function arguments.
Definition at line 431 of file _testing.py.
Referenced by check_docstring_parameters().
_get_diff_msg()
sklearn.utils._testing._get_diff_msg (docstrings_grouped) protected
Get message showing the difference between type/desc docstrings of all objects.
`docstrings_grouped` keys should be the type/desc docstrings and values are a list
of objects with that docstring. Objects with the same type/desc docstring are
thus grouped together.
Definition at line 652 of file _testing.py.
Referenced by _check_consistency_items().
_get_func_name()
sklearn.utils._testing._get_func_name (func) protected
Get function full name.
Parameters
----------
func : callable
    The function object.
Returns
-------
name : str
    The function name.
Definition at line 457 of file _testing.py.
Referenced by check_docstring_parameters().
_get_warnings_filters_info_list()
sklearn.utils._testing._get_warnings_filters_info_list () protected
Definition at line 1354 of file _testing.py.
_is_numpydoc()
sklearn.utils._testing._is_numpydoc () protected
Definition at line 306 of file _testing.py.
assert_allclose()
sklearn.utils._testing.assert_allclose (actual, desired, rtol = None, atol = 0.0, equal_nan = True, err_msg = "", verbose = True)
dtype-aware variant of numpy.testing.assert_allclose
This variant introspects the least precise floating point dtype
in the input argument and automatically sets the relative tolerance
parameter to 1e-4 float32 and use 1e-7 otherwise (typically float64
in scikit-learn).
`atol` is always left to 0. by default. It should be adjusted manually
to an assertion-specific value in case there are null values expected
in `desired`.
The aggregate tolerance is `atol + rtol * abs(desired)`.
Parameters
----------
actual : array_like
    Array obtained.
desired : array_like
    Array desired.
rtol : float, optional, default=None
    Relative tolerance.
    If None, it is set based on the provided arrays' dtypes.
atol : float, optional, default=0.
    Absolute tolerance.
equal_nan : bool, optional, default=True
    If True, NaNs will compare equal.
err_msg : str, optional, default=''
    The error message to be printed in case of failure.
verbose : bool, optional, default=True
    If True, the conflicting values are appended to the error message.
Raises
------
AssertionError
    If actual and desired are not equal up to specified precision.
See Also
--------
numpy.testing.assert_allclose
Examples
--------
>>> import numpy as np
>>> from sklearn.utils._testing import assert_allclose
>>> x = [1e-5, 1e-3, 1e-1]
>>> y = np.arccos(np.cos(x))
>>> assert_allclose(x, y, rtol=1e-5, atol=0)
>>> a = np.full(shape=10, fill_value=1e-5, dtype=np.float32)
>>> assert_allclose(a, 1e-5)
Definition at line 175 of file _testing.py.
Referenced by assert_allclose_dense_sparse().
assert_allclose_dense_sparse()
sklearn.utils._testing.assert_allclose_dense_sparse (x, y, rtol = 1e-07, atol = 1e-9, err_msg = "")
Assert allclose for sparse and dense data.
Both x and y need to be either sparse or dense, they
can't be mixed.
Parameters
----------
x : {array-like, sparse matrix}
    First array to compare.
y : {array-like, sparse matrix}
    Second array to compare.
rtol : float, default=1e-07
    relative tolerance; see numpy.allclose.
atol : float, default=1e-9
    absolute tolerance; see numpy.allclose. Note that the default here is
    more tolerant than the default for numpy.testing.assert_allclose, where
    atol=0.
err_msg : str, default=''
    Error message to raise.
Definition at line 248 of file _testing.py.
References assert_allclose().
assert_docstring_consistency()
sklearn.utils._testing.assert_docstring_consistency (objects, include_params = False, exclude_params = None, include_attrs = False, exclude_attrs = None, include_returns = False, exclude_returns = None, descr_regex_pattern = None, ignore_types = tuple())
Check consistency between docstring parameters/attributes/returns of objects.
Checks if parameters/attributes/returns have the same type specification and
description (ignoring whitespace) across `objects`. Intended to be used for
related classes/functions/data descriptors.
Entries that do not appear across all `objects` are ignored.
Parameters
----------
objects : list of {classes, functions, data descriptors}
Objects to check.
Objects may be classes, functions or data descriptors with docstrings that
can be parsed by numpydoc.
include_params : list of str or bool, default=False
List of parameters to be included. If True, all parameters are included,
if False, checking is skipped for parameters.
Can only be set if `exclude_params` is None.
exclude_params : list of str or None, default=None
List of parameters to be excluded. If None, no parameters are excluded.
Can only be set if `include_params` is True.
include_attrs : list of str or bool, default=False
List of attributes to be included. If True, all attributes are included,
if False, checking is skipped for attributes.
Can only be set if `exclude_attrs` is None.
exclude_attrs : list of str or None, default=None
List of attributes to be excluded. If None, no attributes are excluded.
Can only be set if `include_attrs` is True.
include_returns : list of str or bool, default=False
List of returns to be included. If True, all returns are included,
if False, checking is skipped for returns.
Can only be set if `exclude_returns` is None.
exclude_returns : list of str or None, default=None
List of returns to be excluded. If None, no returns are excluded.
Can only be set if `include_returns` is True.
descr_regex_pattern : str, default=None
Regular expression to match to all descriptions of included
parameters/attributes/returns. If None, will revert to default behavior
of comparing descriptions between objects.
ignore_types : tuple of str, default=tuple()
Tuple of parameter/attribute/return names to exclude from type description
matching between objects.
Examples
--------
>>> from sklearn.metrics import (accuracy_score, classification_report,
... mean_absolute_error, mean_squared_error, median_absolute_error)
>>> from sklearn.utils._testing import assert_docstring_consistency
... # doctest: +SKIP
>>> assert_docstring_consistency([mean_absolute_error, mean_squared_error],
... include_params=['y_true', 'y_pred', 'sample_weight'])  # doctest: +SKIP
>>> assert_docstring_consistency([median_absolute_error, mean_squared_error],
... include_params=True)  # doctest: +SKIP
>>> assert_docstring_consistency([accuracy_score, classification_report],
... include_params=["y_true"],
... descr_regex_pattern=r"Ground truth \‍(correct\‍) (labels|target values)")
... # doctest: +SKIP
Definition at line 765 of file _testing.py.
References _check_consistency_items(), and _check_item_included().
assert_run_python_script_without_output()
sklearn.utils._testing.assert_run_python_script_without_output (source_code, pattern = ".+", timeout = 60)
Utility to check assertions in an independent Python subprocess.
The script provided in the source code should return 0 and the stdtout +
stderr should not match the pattern `pattern`.
This is a port from cloudpickle https://github.com/cloudpipe/cloudpickle
Parameters
----------
source_code : str
    The Python source code to execute.
pattern : str
    Pattern that the stdout + stderr should not match. By default, unless
    stdout + stderr are both empty, an error will be raised.
timeout : int, default=60
    Time in seconds before timeout.
Definition at line 906 of file _testing.py.
check_docstring_parameters()
sklearn.utils._testing.check_docstring_parameters (func, doc = None, ignore = None)
Helper to check docstring.
Parameters
----------
func : callable
    The function object to test.
doc : str, default=None
    Docstring if it is passed manually to the test.
ignore : list, default=None
    Parameters to ignore.
Returns
-------
incorrect : list
    A list of string describing the incorrect results.
Definition at line 483 of file _testing.py.
References _get_args(), and _get_func_name().
check_skip_network()
sklearn.utils._testing.check_skip_network ()
Definition at line 367 of file _testing.py.
create_memmap_backed_data()
sklearn.utils._testing.create_memmap_backed_data (data, mmap_mode = "r", return_folder = False)
Parameters
----------
data
mmap_mode : str, default='r'
return_folder :  bool, default=False
Definition at line 409 of file _testing.py.
get_pytest_filterwarning_lines()
sklearn.utils._testing.get_pytest_filterwarning_lines ()
Definition at line 1439 of file _testing.py.
ignore_warnings()
sklearn.utils._testing.ignore_warnings (obj = None, category = Warning)
Context manager and decorator to ignore warnings.
Note: Using this (in both variants) will clear all warnings
from all python modules loaded. In case you need to test
cross-module-warning-logging, this is not your tool of choice.
Parameters
----------
obj : callable, default=None
    callable where you want to ignore the warnings.
category : warning class, default=Warning
    The category to filter. If Warning, all categories will be muted.
Examples
--------
>>> import warnings
>>> from sklearn.utils._testing import ignore_warnings
>>> with ignore_warnings():
...     warnings.warn('buhuhuhu')
>>> def nasty_warn():
...     warnings.warn('buhuhuhu')
...     print(42)
>>> ignore_warnings(nasty_warn)()
42
Definition at line 74 of file _testing.py.
raises()
sklearn.utils._testing.raises (expected_exc_type, match = None, may_pass = False, err_msg = None)
Context manager to ensure exceptions are raised within a code block.
This is similar to and inspired from pytest.raises, but supports a few
other cases.
This is only intended to be used in estimator_checks.py where we don't
want to use pytest. In the rest of the code base, just use pytest.raises
instead.
Parameters
----------
excepted_exc_type : Exception or list of Exception
    The exception that should be raised by the block. If a list, the block
    should raise one of the exceptions.
match : str or list of str, default=None
    A regex that the exception message should match. If a list, one of
    the entries must match. If None, match isn't enforced.
may_pass : bool, default=False
    If True, the block is allowed to not raise an exception. Useful in
    cases where some estimators may support a feature but others must
    fail with an appropriate error message. By default, the context
    manager will raise an exception if the block does not raise an
    exception.
err_msg : str, default=None
    If the context manager fails (e.g. the block fails to raise the
    proper exception, or fails to match), then an AssertionError is
    raised with this message. By default, an AssertionError is raised
    with a default error message (depends on the kind of failure). Use
    this to indicate how users should fix their estimators to pass the
    checks.
Attributes
----------
raised_and_matched : bool
    True if an exception was raised and a match was found, False otherwise.
Definition at line 1076 of file _testing.py.
set_random_state()
sklearn.utils._testing.set_random_state (estimator, random_state = 0)
Set random state of an estimator if it has the `random_state` param.
Parameters
----------
estimator : object
    The estimator.
random_state : int, RandomState instance or None, default=0
    Pseudo random number generator state.
    Pass an int for reproducible results across multiple function calls.
    See :term:`Glossary <random_state>`.
Definition at line 290 of file _testing.py.
turn_warnings_into_errors()
sklearn.utils._testing.turn_warnings_into_errors ()
Definition at line 1447 of file _testing.py.
Variable Documentation
__all__
list sklearn.utils._testing.__all__ private
Initial value:
=  [
    "SkipTest",
    "assert_allclose",
    "assert_almost_equal",
    "assert_array_almost_equal",
    "assert_array_equal",
    "assert_array_less",
    "assert_run_python_script_without_output",
]
Definition at line 61 of file _testing.py.
ARRAY_API_COMPAT_FUNCTIONAL
bool sklearn.utils._testing.ARRAY_API_COMPAT_FUNCTIONAL = True
Definition at line 317 of file _testing.py.
fails_if_unstable_openblas
sklearn.utils._testing.fails_if_unstable_openblas
Initial value:
=  pytest.mark.xfail(
        _in_unstable_openblas_configuration(),
        reason="OpenBLAS is unstable for this configuration",
    )
Definition at line 325 of file _testing.py.
if_safe_multiprocessing_with_blas
sklearn.utils._testing.if_safe_multiprocessing_with_blas
Initial value:
=  pytest.mark.skipif(
        sys.platform == "darwin", reason="Possible multi-process bug with some BLAS"
    )
Definition at line 356 of file _testing.py.
skip_if_32bit
sklearn.utils._testing.skip_if_32bit = pytest.mark.skipif(_IS_32BIT, reason="skipped on 32bit platforms")
Definition at line 324 of file _testing.py.
skip_if_array_api_compat_not_configured
sklearn.utils._testing.skip_if_array_api_compat_not_configured
Initial value:
=  pytest.mark.skipif(
        not ARRAY_API_COMPAT_FUNCTIONAL,
        reason="SCIPY_ARRAY_API not set, or versions of NumPy/SciPy too old.",
    )
Definition at line 332 of file _testing.py.
skip_if_no_numpydoc
sklearn.utils._testing.skip_if_no_numpydoc
Initial value:
=  pytest.mark.skipif(
        not _is_numpydoc(),
        reason="numpydoc is required to test the docstrings",
    )
Definition at line 359 of file _testing.py.
skip_if_no_parallel
sklearn.utils._testing.skip_if_no_parallel
Initial value:
=  pytest.mark.skipif(
        not joblib.parallel.mp, reason="joblib is in serial mode"
    )
Definition at line 329 of file _testing.py.
SkipTest
sklearn.utils._testing.SkipTest = unittest.case.SkipTest
Definition at line 71 of file _testing.py.