Code Cloning Analysis: fontTools.voltLib.lexer.Lexer Class Reference
fontTools.voltLib.lexer.Lexer Class Reference
Public Member Functions
__init__ (self, text, filename)
__iter__ (self)
next (self)
__next__ (self)
location_ (self)
next_ (self)
scan_over_ (self, valid)
scan_until_ (self, stop_at)
Public Attributes
filename_ = filename
int line_ = 1
int pos_ = 0
int line_start_ = 0
text_ = text
text_length_ = len(text)
Static Public Attributes
str NUMBER = "NUMBER"
str STRING = "STRING"
str NAME = "NAME"
str NEWLINE = "NEWLINE"
str CHAR_WHITESPACE_ = " \t"
str CHAR_NEWLINE_ = "\r\n"
str CHAR_DIGIT_ = "0123456789"
str CHAR_UC_LETTER_ = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
str CHAR_LC_LETTER_ = "abcdefghijklmnopqrstuvwxyz"
str CHAR_UNDERSCORE_ = "_"
str CHAR_PERIOD_ = "."
tuple CHAR_NAME_START_
tuple CHAR_NAME_CONTINUATION_ = CHAR_NAME_START_ + CHAR_DIGIT_
Detailed Description
Definition at line 4 of file lexer.py.
Constructor & Destructor Documentation
__init__()
fontTools.voltLib.lexer.Lexer.__init__ (self, text, filename)
Definition at line 22 of file lexer.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__iter__()
fontTools.voltLib.lexer.Lexer.__iter__ (self)
Definition at line 30 of file lexer.py.
__next__()
fontTools.voltLib.lexer.Lexer.__next__ (self)
Definition at line 36 of file lexer.py.
location_()
fontTools.voltLib.lexer.Lexer.location_ (self)
Definition at line 42 of file lexer.py.
next()
fontTools.voltLib.lexer.Lexer.next (self)
Definition at line 33 of file lexer.py.
next_()
fontTools.voltLib.lexer.Lexer.next_ (self)
Definition at line 46 of file lexer.py.
scan_over_()
fontTools.voltLib.lexer.Lexer.scan_over_ (self, valid)
Definition at line 89 of file lexer.py.
scan_until_()
fontTools.voltLib.lexer.Lexer.scan_until_ (self, stop_at)
Definition at line 95 of file lexer.py.
Member Data Documentation
CHAR_DIGIT_
str fontTools.voltLib.lexer.Lexer.CHAR_DIGIT_ = "0123456789" static
Definition at line 12 of file lexer.py.
CHAR_LC_LETTER_
str fontTools.voltLib.lexer.Lexer.CHAR_LC_LETTER_ = "abcdefghijklmnopqrstuvwxyz" static
Definition at line 14 of file lexer.py.
CHAR_NAME_CONTINUATION_
tuple fontTools.voltLib.lexer.Lexer.CHAR_NAME_CONTINUATION_ = CHAR_NAME_START_ + CHAR_DIGIT_ static
Definition at line 20 of file lexer.py.
CHAR_NAME_START_
tuple fontTools.voltLib.lexer.Lexer.CHAR_NAME_START_ static
Initial value:
=  (
        CHAR_UC_LETTER_ + CHAR_LC_LETTER_ + CHAR_PERIOD_ + CHAR_UNDERSCORE_
    )
Definition at line 17 of file lexer.py.
CHAR_NEWLINE_
str fontTools.voltLib.lexer.Lexer.CHAR_NEWLINE_ = "\r\n" static
Definition at line 11 of file lexer.py.
CHAR_PERIOD_
str fontTools.voltLib.lexer.Lexer.CHAR_PERIOD_ = "." static
Definition at line 16 of file lexer.py.
CHAR_UC_LETTER_
str fontTools.voltLib.lexer.Lexer.CHAR_UC_LETTER_ = "ABCDEFGHIJKLMNOPQRSTUVWXYZ" static
Definition at line 13 of file lexer.py.
CHAR_UNDERSCORE_
str fontTools.voltLib.lexer.Lexer.CHAR_UNDERSCORE_ = "_" static
Definition at line 15 of file lexer.py.
CHAR_WHITESPACE_
str fontTools.voltLib.lexer.Lexer.CHAR_WHITESPACE_ = " \t" static
Definition at line 10 of file lexer.py.
filename_
fontTools.voltLib.lexer.Lexer.filename_ = filename
Definition at line 23 of file lexer.py.
line_
fontTools.voltLib.lexer.Lexer.line_ = 1
Definition at line 24 of file lexer.py.
Referenced by sklearn.calibration.CalibrationDisplay.plot(), sklearn.metrics._plot.det_curve.DetCurveDisplay.plot(), sklearn.metrics._plot.precision_recall_curve.PrecisionRecallDisplay.plot(), sklearn.metrics._plot.regression.PredictionErrorDisplay.plot(), and sklearn.metrics._plot.roc_curve.RocCurveDisplay.plot().
line_start_
int fontTools.voltLib.lexer.Lexer.line_start_ = 0
Definition at line 26 of file lexer.py.
NAME
str fontTools.voltLib.lexer.Lexer.NAME = "NAME" static
Definition at line 7 of file lexer.py.
NEWLINE
str fontTools.voltLib.lexer.Lexer.NEWLINE = "NEWLINE" static
Definition at line 8 of file lexer.py.
NUMBER
str fontTools.voltLib.lexer.Lexer.NUMBER = "NUMBER" static
Definition at line 5 of file lexer.py.
pos_
int fontTools.voltLib.lexer.Lexer.pos_ = 0
Definition at line 25 of file lexer.py.
STRING
str fontTools.voltLib.lexer.Lexer.STRING = "STRING" static
Definition at line 6 of file lexer.py.
text_
fontTools.voltLib.lexer.Lexer.text_ = text
Definition at line 27 of file lexer.py.
Referenced by sklearn.metrics._plot.confusion_matrix.ConfusionMatrixDisplay.plot().
text_length_
fontTools.voltLib.lexer.Lexer.text_length_ = len(text)
Definition at line 28 of file lexer.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/voltLib/lexer.py