Code Cloning Analysis: pandas.core.arrays._ranges Namespace Reference
pandas.core.arrays._ranges Namespace Reference
Functions
npt.NDArray[np.intp] generate_regular_range (Timestamp|Timedelta|None start, Timestamp|Timedelta|None end, int|None periods, BaseOffset freq, str unit="ns")
int _generate_range_overflow_safe (int endpoint, int periods, int stride, str side="start")
int _generate_range_overflow_safe_signed (int endpoint, int periods, int stride, str side)
Detailed Description
Helper functions to generate range-like data for DatetimeArray
(and possibly TimedeltaArray/PeriodArray)
Function Documentation
_generate_range_overflow_safe()
int pandas.core.arrays._ranges._generate_range_overflow_safe (int endpoint, int periods, int stride, str side = "start") protected
Calculate the second endpoint for passing to np.arange, checking
to avoid an integer overflow.  Catch OverflowError and re-raise
as OutOfBoundsDatetime.
Parameters
----------
endpoint : int
    nanosecond timestamp of the known endpoint of the desired range
periods : int
    number of periods in the desired range
stride : int
    nanoseconds between periods in the desired range
side : {'start', 'end'}
    which end of the range `endpoint` refers to
Returns
-------
other_end : int
Raises
------
OutOfBoundsDatetime
Definition at line 97 of file _ranges.py.
References _generate_range_overflow_safe(), and _generate_range_overflow_safe_signed().
Referenced by _generate_range_overflow_safe(), and generate_regular_range().
_generate_range_overflow_safe_signed()
int pandas.core.arrays._ranges._generate_range_overflow_safe_signed (int endpoint, int periods, int stride, str side) protected
A special case for _generate_range_overflow_safe where `periods * stride`
can be calculated without overflowing int64 bounds.
Definition at line 164 of file _ranges.py.
Referenced by _generate_range_overflow_safe().
generate_regular_range()
npt.NDArray[np.intp] pandas.core.arrays._ranges.generate_regular_range (Timestamp | Timedelta | None start, Timestamp | Timedelta | None end, int | None periods, BaseOffset freq, str unit = "ns")
Generate a range of dates or timestamps with the spans between dates
described by the given `freq` DateOffset.
Parameters
----------
start : Timedelta, Timestamp or None
    First point of produced date range.
end : Timedelta, Timestamp or None
    Last point of produced date range.
periods : int or None
    Number of periods in produced date range.
freq : Tick
    Describes space between dates in produced date range.
unit : str, default "ns"
    The resolution the output is meant to represent.
Returns
-------
ndarray[np.int64]
    Representing the given resolution.
Definition at line 24 of file _ranges.py.
References _generate_range_overflow_safe().