Code Cloning Analysis: matplotlib.patches.CirclePolygon Class Reference
matplotlib.patches.CirclePolygon Class Reference
Public Member Functions
__str__ (self)
__init__ (self, xy, radius=5, *, resolution=20, **kwargs)
Public Member Functions inherited from matplotlib.patches.RegularPolygon
__str__ (self)
__init__ (self, xy, numVertices, *, radius=5, orientation=0, **kwargs)
get_path (self)
get_patch_transform (self)
Public Member Functions inherited from matplotlib.patches.Patch
__init__ (self, *, edgecolor=None, facecolor=None, color=None, linewidth=None, linestyle=None, antialiased=None, hatch=None, fill=True, capstyle=None, joinstyle=None, **kwargs)
get_verts (self)
contains (self, mouseevent, radius=None)
contains_point (self, point, radius=None)
contains_points (self, points, radius=None)
update_from (self, other)
get_extents (self)
get_transform (self)
get_data_transform (self)
get_antialiased (self)
get_edgecolor (self)
get_facecolor (self)
get_linewidth (self)
get_linestyle (self)
set_antialiased (self, aa)
set_edgecolor (self, color)
set_facecolor (self, color)
set_color (self, c)
set_alpha (self, alpha)
set_linewidth (self, w)
set_linestyle (self, ls)
set_fill (self, b)
get_fill (self)
set_capstyle (self, s)
get_capstyle (self)
set_joinstyle (self, s)
get_joinstyle (self)
set_hatch (self, hatch)
get_hatch (self)
set_hatch_linewidth (self, lw)
get_hatch_linewidth (self)
draw (self, renderer)
get_window_extent (self, renderer=None)
Public Member Functions inherited from matplotlib.artist.Artist
__init_subclass__ (cls)
Additional Inherited Members
Public Attributes inherited from matplotlib.patches.RegularPolygon
numvertices
radius
orientation
xy = xy
Public Attributes inherited from matplotlib.patches.Patch
bool stale = True
Public Attributes inherited from matplotlib.artist.Artist
set = _prevent_rasterization(cls.draw)
Static Public Attributes inherited from matplotlib.artist.Artist
int zorder = 0
Protected Member Functions inherited from matplotlib.patches.Patch
_process_radius (self, radius)
_set_edgecolor (self, color)
_set_facecolor (self, color)
_draw_paths_with_artist_properties (self, renderer, draw_path_args_list)
_convert_xy_units (self, xy)
Protected Attributes inherited from matplotlib.patches.RegularPolygon
_path = Path.unit_regular_polygon(numVertices)
_patch_transform = transforms.Affine2D()
Protected Attributes inherited from matplotlib.patches.Patch
_hatch_color = colors.to_rgba(mpl.rcParams['hatch.color'])
_hatch_linewidth = mpl.rcParams['hatch.linewidth']
_fill = bool(fill)
int _linewidth = 0
tuple _unscaled_dash_pattern = (0, None)
tuple _dash_pattern = (0, None)
_picker
_edgecolor = other._edgecolor
_facecolor = other._facecolor
_original_edgecolor = other._original_edgecolor
_original_facecolor = other._original_facecolor
_hatch = other._hatch
_transformSet = other.is_transform_set()
_antialiased = aa
_linestyle = ls
_capstyle = cs
_joinstyle = js
_url
_alpha
Static Protected Attributes inherited from matplotlib.patches.Patch
bool _edge_default = False
Properties inherited from matplotlib.patches.Patch
fill = property(get_fill, set_fill)
Detailed Description
A polygon-approximation of a circle patch.
Definition at line 1570 of file patches.py.
Constructor & Destructor Documentation
__init__()
matplotlib.patches.CirclePolygon.__init__ (self, xy, radius = 5, * , resolution = 20, ** kwargs)
Create a circle at *xy* = (*x*, *y*) with given *radius*.
This circle is approximated by a regular polygon with *resolution*
sides.  For a smoother circle drawn with splines, see `Circle`.
Valid keyword arguments are:
%(Patch:kwdoc)s
Definition at line 1578 of file patches.py.
References __init__().
Referenced by __init__(), sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__str__()
matplotlib.patches.CirclePolygon.__str__ (self)
Definition at line 1573 of file patches.py.
Referenced by numpy.polynomial._polybase.ABCPolyBase._get_coefficients().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/patches.py