Code Cloning Analysis: matplotlib.tests.test_arrow_patches Namespace Reference
matplotlib.tests.test_arrow_patches Namespace Reference
Functions
draw_arrow (ax, t, r)
test_fancyarrow ()
test_boxarrow ()
__prepare_fancyarrow_dpi_cor_test ()
test_fancyarrow_dpi_cor_100dpi ()
test_fancyarrow_dpi_cor_200dpi ()
test_fancyarrow_dash ()
test_arrow_styles ()
test_connection_styles ()
test_invalid_intersection ()
Function Documentation
__prepare_fancyarrow_dpi_cor_test()
matplotlib.tests.test_arrow_patches.__prepare_fancyarrow_dpi_cor_test () private
Convenience function that prepares and returns a FancyArrowPatch. It aims
at being used to test that the size of the arrow head does not depend on
the DPI value of the exported picture.
NB: this function *is not* a test in itself!
Definition at line 52 of file test_arrow_patches.py.
Referenced by test_fancyarrow_dpi_cor_100dpi(), and test_fancyarrow_dpi_cor_200dpi().
draw_arrow()
matplotlib.tests.test_arrow_patches.draw_arrow (ax, t, r)
Definition at line 8 of file test_arrow_patches.py.
test_arrow_styles()
matplotlib.tests.test_arrow_patches.test_arrow_styles ()
Definition at line 120 of file test_arrow_patches.py.
test_boxarrow()
matplotlib.tests.test_arrow_patches.test_boxarrow ()
Definition at line 32 of file test_arrow_patches.py.
test_connection_styles()
matplotlib.tests.test_arrow_patches.test_connection_styles ()
Definition at line 153 of file test_arrow_patches.py.
test_fancyarrow()
matplotlib.tests.test_arrow_patches.test_fancyarrow ()
Definition at line 16 of file test_arrow_patches.py.
test_fancyarrow_dash()
matplotlib.tests.test_arrow_patches.test_fancyarrow_dash ()
Definition at line 98 of file test_arrow_patches.py.
test_fancyarrow_dpi_cor_100dpi()
matplotlib.tests.test_arrow_patches.test_fancyarrow_dpi_cor_100dpi ()
Check the export of a FancyArrowPatch @ 100 DPI. FancyArrowPatch is
instantiated through a dedicated function because another similar test
checks a similar export but with a different DPI value.
Remark: test only a rasterized format.
Definition at line 73 of file test_arrow_patches.py.
References __prepare_fancyarrow_dpi_cor_test().
test_fancyarrow_dpi_cor_200dpi()
matplotlib.tests.test_arrow_patches.test_fancyarrow_dpi_cor_200dpi ()
As test_fancyarrow_dpi_cor_100dpi, but exports @ 200 DPI. The relative size
of the arrow head should be the same.
Definition at line 88 of file test_arrow_patches.py.
References __prepare_fancyarrow_dpi_cor_test().
test_invalid_intersection()
matplotlib.tests.test_arrow_patches.test_invalid_intersection ()
Definition at line 169 of file test_arrow_patches.py.