Code Cloning Analysis: fontTools.varLib.instancer.NormalizedAxisTripleAndDistances Class Reference
fontTools.varLib.instancer.NormalizedAxisTripleAndDistances Class Reference
Public Member Functions
__post_init__ (self)
reverse_negate (self)
renormalizeValue (self, v, extrapolate=True)
Public Member Functions inherited from fontTools.varLib.instancer.AxisTriple
__post_init__ (self)
__getitem__ (self, i)
__len__ (self)
__repr__ (self)
"AxisTriple" expand (cls, Union["AxisTriple", float, # pin axis at single value, same as min==default==max Tuple[float, float], #(min, max), restrict axis and keep default Tuple[float, float, float], #(min, default, max)] v)
"AxisTriple" limitRangeAndPopulateDefaults (self, fvarTriple)
Static Public Attributes
Optional distanceNegative = 1
Optional distancePositive = 1
Static Public Attributes inherited from fontTools.varLib.instancer.AxisTriple
Optional minimum [float]
Optional default [float]
Optional maximum [float]
Additional Inherited Members
Protected Member Functions inherited from fontTools.varLib.instancer.AxisTriple
_replace (self, **kwargs)
Detailed Description
A triple of (min, default, max) normalized axis values,
with distances between min and default, and default and max,
in the *pre-normalized* space.
Definition at line 295 of file __init__.py.
Member Function Documentation
__post_init__()
fontTools.varLib.instancer.NormalizedAxisTripleAndDistances.__post_init__ (self)
Definition at line 306 of file __init__.py.
renormalizeValue()
fontTools.varLib.instancer.NormalizedAxisTripleAndDistances.renormalizeValue (self, v, extrapolate = True)
Renormalizes a normalized value v to the range of this axis,
considering the pre-normalized distances as well as the new
axis limits.
Definition at line 319 of file __init__.py.
References renormalizeValue(), and reverse_negate().
Referenced by renormalizeValue().
reverse_negate()
fontTools.varLib.instancer.NormalizedAxisTripleAndDistances.reverse_negate (self)
Definition at line 315 of file __init__.py.
Referenced by renormalizeValue().
Member Data Documentation
distanceNegative
Optional fontTools.varLib.instancer.NormalizedAxisTripleAndDistances.distanceNegative = 1 static
Definition at line 303 of file __init__.py.
distancePositive
Optional fontTools.varLib.instancer.NormalizedAxisTripleAndDistances.distancePositive = 1 static
Definition at line 304 of file __init__.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/varLib/instancer/__init__.py