Code Cloning Analysis: scipy.optimize._minpack_py Namespace Reference
scipy.optimize._minpack_py Namespace Reference
Functions
_check_func (checker, argname, thefunc, x0, args, numinputs, output_shape=None)
fsolve (func, x0, args=(), fprime=None, full_output=0, col_deriv=0, xtol=1.49012e-8, maxfev=0, band=None, epsfcn=None, factor=100, diag=None)
_root_hybr (func, x0, args=(), jac=None, col_deriv=0, xtol=1.49012e-08, maxfev=0, band=None, eps=None, factor=100, diag=None, **unknown_options)
leastsq (func, x0, args=(), Dfun=None, full_output=False, col_deriv=False, ftol=1.49012e-8, xtol=1.49012e-8, gtol=0.0, maxfev=0, epsfcn=None, factor=100, diag=None)
_lightweight_memoizer (f)
_wrap_func (func, xdata, ydata, transform)
_wrap_jac (jac, xdata, transform)
_initialize_feasible (lb, ub)
curve_fit (f, xdata, ydata, p0=None, sigma=None, absolute_sigma=False, check_finite=None, bounds=(-np.inf, np.inf), method=None, jac=None, *, full_output=False, nan_policy=None, **kwargs)
check_gradient (fcn, Dfcn, x0, args=(), col_deriv=0)
_del2 (p0, p1, d)
_relerr (actual, desired)
_fixed_point_helper (func, x0, args, xtol, maxiter, use_accel)
fixed_point (func, x0, args=(), xtol=1e-8, maxiter=500, method='del2')
Variables
error = _minpack.error
list __all__ = ['fsolve', 'leastsq', 'fixed_point', 'curve_fit']
list LEASTSQ_SUCCESS = [1, 2, 3, 4]
list LEASTSQ_FAILURE = [5, 6, 7, 8]
Function Documentation
_check_func()
scipy.optimize._minpack_py._check_func (checker, argname, thefunc, x0, args, numinputs, output_shape = None) protected
Definition at line 23 of file _minpack_py.py.
_del2()
scipy.optimize._minpack_py._del2 (p0, p1, d) protected
Definition at line 1050 of file _minpack_py.py.
_fixed_point_helper()
scipy.optimize._minpack_py._fixed_point_helper (func, x0, args, xtol, maxiter, use_accel) protected
Definition at line 1058 of file _minpack_py.py.
_initialize_feasible()
scipy.optimize._minpack_py._initialize_feasible (lb, ub) protected
Definition at line 554 of file _minpack_py.py.
_lightweight_memoizer()
scipy.optimize._minpack_py._lightweight_memoizer (f) protected
Definition at line 500 of file _minpack_py.py.
_relerr()
scipy.optimize._minpack_py._relerr (actual, desired) protected
Definition at line 1054 of file _minpack_py.py.
_root_hybr()
scipy.optimize._minpack_py._root_hybr (func, x0, args = (), jac = None, col_deriv = 0, xtol = 1.49012e-08, maxfev = 0, band = None, eps = None, factor = 100, diag = None, ** unknown_options) protected
Find the roots of a multivariate function using MINPACK's hybrd and
hybrj routines (modified Powell method).
Options
-------
col_deriv : bool
    Specify whether the Jacobian function computes derivatives down
    the columns (faster, because there is no transpose operation).
xtol : float
    The calculation will terminate if the relative error between two
    consecutive iterates is at most `xtol`.
maxfev : int
    The maximum number of calls to the function. If zero, then
    ``100*(N+1)`` is the maximum where N is the number of elements
    in `x0`.
band : tuple
    If set to a two-sequence containing the number of sub- and
    super-diagonals within the band of the Jacobi matrix, the
    Jacobi matrix is considered banded (only for ``fprime=None``).
eps : float
    A suitable step length for the forward-difference
    approximation of the Jacobian (for ``fprime=None``). If
    `eps` is less than the machine precision, it is assumed
    that the relative errors in the functions are of the order of
    the machine precision.
factor : float
    A parameter determining the initial step bound
    (``factor * || diag * x||``). Should be in the interval
    ``(0.1, 100)``.
diag : sequence
    N positive entries that serve as a scale factors for the
    variables.
Definition at line 183 of file _minpack_py.py.
Referenced by fsolve(), and scipy.optimize._root.root().
_wrap_func()
scipy.optimize._minpack_py._wrap_func (func, xdata, ydata, transform) protected
Definition at line 520 of file _minpack_py.py.
_wrap_jac()
scipy.optimize._minpack_py._wrap_jac (jac, xdata, transform) protected
Definition at line 541 of file _minpack_py.py.
check_gradient()
scipy.optimize._minpack_py.check_gradient (fcn, Dfcn, x0, args = (), col_deriv = 0)
Perform a simple check on the gradient for correctness.
Definition at line 1019 of file _minpack_py.py.
curve_fit()
scipy.optimize._minpack_py.curve_fit (f, xdata, ydata, p0 = None, sigma = None, absolute_sigma = False, check_finite = None, bounds = (-np.inf, np.inf), method = None, jac = None, * , full_output = False, nan_policy = None, ** kwargs)
Use non-linear least squares to fit a function, f, to data.
Assumes ``ydata = f(xdata, *params) + eps``.
Parameters
----------
f : callable
    The model function, f(x, ...). It must take the independent
    variable as the first argument and the parameters to fit as
    separate remaining arguments.
xdata : array_like
    The independent variable where the data is measured.
    Should usually be an M-length sequence or an (k,M)-shaped array for
    functions with k predictors, and each element should be float
    convertible if it is an array like object.
ydata : array_like
    The dependent data, a length M array - nominally ``f(xdata, ...)``.
p0 : array_like, optional
    Initial guess for the parameters (length N). If None, then the
    initial values will all be 1 (if the number of parameters for the
    function can be determined using introspection, otherwise a
    ValueError is raised).
sigma : None or M-length sequence or MxM array, optional
    Determines the uncertainty in `ydata`. If we define residuals as
    ``r = ydata - f(xdata, *popt)``, then the interpretation of `sigma`
    depends on its number of dimensions:
        - A 1-D `sigma` should contain values of standard deviations of
          errors in `ydata`. In this case, the optimized function is
          ``chisq = sum((r / sigma) ** 2)``.
        - A 2-D `sigma` should contain the covariance matrix of
          errors in `ydata`. In this case, the optimized function is
          ``chisq = r.T @ inv(sigma) @ r``.
          .. versionadded:: 0.19
    None (default) is equivalent of 1-D `sigma` filled with ones.
absolute_sigma : bool, optional
    If True, `sigma` is used in an absolute sense and the estimated parameter
    covariance `pcov` reflects these absolute values.
    If False (default), only the relative magnitudes of the `sigma` values matter.
    The returned parameter covariance matrix `pcov` is based on scaling
    `sigma` by a constant factor. This constant is set by demanding that the
    reduced `chisq` for the optimal parameters `popt` when using the
    *scaled* `sigma` equals unity. In other words, `sigma` is scaled to
    match the sample variance of the residuals after the fit. Default is False.
    Mathematically,
    ``pcov(absolute_sigma=False) = pcov(absolute_sigma=True) * chisq(popt)/(M-N)``
check_finite : bool, optional
    If True, check that the input arrays do not contain nans of infs,
    and raise a ValueError if they do. Setting this parameter to
    False may silently produce nonsensical results if the input arrays
    do contain nans. Default is True if `nan_policy` is not specified
    explicitly and False otherwise.
bounds : 2-tuple of array_like or `Bounds`, optional
    Lower and upper bounds on parameters. Defaults to no bounds.
    There are two ways to specify the bounds:
        - Instance of `Bounds` class.
        - 2-tuple of array_like: Each element of the tuple must be either
          an array with the length equal to the number of parameters, or a
          scalar (in which case the bound is taken to be the same for all
          parameters). Use ``np.inf`` with an appropriate sign to disable
          bounds on all or some parameters.
method : {'lm', 'trf', 'dogbox'}, optional
    Method to use for optimization. See `least_squares` for more details.
    Default is 'lm' for unconstrained problems and 'trf' if `bounds` are
    provided. The method 'lm' won't work when the number of observations
    is less than the number of variables, use 'trf' or 'dogbox' in this
    case.
    .. versionadded:: 0.17
jac : callable, string or None, optional
    Function with signature ``jac(x, ...)`` which computes the Jacobian
    matrix of the model function with respect to parameters as a dense
    array_like structure. It will be scaled according to provided `sigma`.
    If None (default), the Jacobian will be estimated numerically.
    String keywords for 'trf' and 'dogbox' methods can be used to select
    a finite difference scheme, see `least_squares`.
    .. versionadded:: 0.18
full_output : boolean, optional
    If True, this function returns additioal information: `infodict`,
    `mesg`, and `ier`.
    .. versionadded:: 1.9
nan_policy : {'raise', 'omit', None}, optional
    Defines how to handle when input contains nan.
    The following options are available (default is None):
      * 'raise': throws an error
      * 'omit': performs the calculations ignoring nan values
      * None: no special handling of NaNs is performed
        (except what is done by check_finite); the behavior when NaNs
        are present is implementation-dependent and may change.
    Note that if this value is specified explicitly (not None),
    `check_finite` will be set as False.
    .. versionadded:: 1.11
**kwargs
    Keyword arguments passed to `leastsq` for ``method='lm'`` or
    `least_squares` otherwise.
Returns
-------
popt : array
    Optimal values for the parameters so that the sum of the squared
    residuals of ``f(xdata, *popt) - ydata`` is minimized.
pcov : 2-D array
    The estimated approximate covariance of popt. The diagonals provide
    the variance of the parameter estimate. To compute one standard
    deviation errors on the parameters, use
    ``perr = np.sqrt(np.diag(pcov))``. Note that the relationship between
    `cov` and parameter error estimates is derived based on a linear
    approximation to the model function around the optimum [1].
    When this approximation becomes inaccurate, `cov` may not provide an
    accurate measure of uncertainty.
    How the `sigma` parameter affects the estimated covariance
    depends on `absolute_sigma` argument, as described above.
    If the Jacobian matrix at the solution doesn't have a full rank, then
    'lm' method returns a matrix filled with ``np.inf``, on the other hand
    'trf'  and 'dogbox' methods use Moore-Penrose pseudoinverse to compute
    the covariance matrix. Covariance matrices with large condition numbers
    (e.g. computed with `numpy.linalg.cond`) may indicate that results are
    unreliable.
infodict : dict (returned only if `full_output` is True)
    a dictionary of optional outputs with the keys:
    ``nfev``
        The number of function calls. Methods 'trf' and 'dogbox' do not
        count function calls for numerical Jacobian approximation,
        as opposed to 'lm' method.
    ``fvec``
        The residual values evaluated at the solution, for a 1-D `sigma`
        this is ``(f(x, *popt) - ydata)/sigma``.
    ``fjac``
        A permutation of the R matrix of a QR
        factorization of the final approximate
        Jacobian matrix, stored column wise.
        Together with ipvt, the covariance of the
        estimate can be approximated.
        Method 'lm' only provides this information.
    ``ipvt``
        An integer array of length N which defines
        a permutation matrix, p, such that
        fjac*p = q*r, where r is upper triangular
        with diagonal elements of nonincreasing
        magnitude. Column j of p is column ipvt(j)
        of the identity matrix.
        Method 'lm' only provides this information.
    ``qtf``
        The vector (transpose(q) * fvec).
        Method 'lm' only provides this information.
    .. versionadded:: 1.9
mesg : str (returned only if `full_output` is True)
    A string message giving information about the solution.
    .. versionadded:: 1.9
ier : int (returnned only if `full_output` is True)
    An integer flag. If it is equal to 1, 2, 3 or 4, the solution was
    found. Otherwise, the solution was not found. In either case, the
    optional output variable `mesg` gives more information.
    .. versionadded:: 1.9
Raises
------
ValueError
    if either `ydata` or `xdata` contain NaNs, or if incompatible options
    are used.
RuntimeError
    if the least-squares minimization fails.
OptimizeWarning
    if covariance of the parameters can not be estimated.
See Also
--------
least_squares : Minimize the sum of squares of nonlinear functions.
scipy.stats.linregress : Calculate a linear least squares regression for
                         two sets of measurements.
Notes
-----
Users should ensure that inputs `xdata`, `ydata`, and the output of `f`
are ``float64``, or else the optimization may return incorrect results.
With ``method='lm'``, the algorithm uses the Levenberg-Marquardt algorithm
through `leastsq`. Note that this algorithm can only deal with
unconstrained problems.
Box constraints can be handled by methods 'trf' and 'dogbox'. Refer to
the docstring of `least_squares` for more information.
References
----------
[1] K. Vugrin et al. Confidence region estimation techniques for nonlinear
    regression in groundwater flow: Three case studies. Water Resources
    Research, Vol. 43, W03423, :doi:`10.1029/2005WR004804`
Examples
--------
>>> import numpy as np
>>> import matplotlib.pyplot as plt
>>> from scipy.optimize import curve_fit
>>> def func(x, a, b, c):
...     return a * np.exp(-b * x) + c
Define the data to be fit with some noise:
>>> xdata = np.linspace(0, 4, 50)
>>> y = func(xdata, 2.5, 1.3, 0.5)
>>> rng = np.random.default_rng()
>>> y_noise = 0.2 * rng.normal(size=xdata.size)
>>> ydata = y + y_noise
>>> plt.plot(xdata, ydata, 'b-', label='data')
Fit for the parameters a, b, c of the function `func`:
>>> popt, pcov = curve_fit(func, xdata, ydata)
>>> popt
array([2.56274217, 1.37268521, 0.47427475])
>>> plt.plot(xdata, func(xdata, *popt), 'r-',
...          label='fit: a=%5.3f, b=%5.3f, c=%5.3f' % tuple(popt))
Constrain the optimization to the region of ``0 <= a <= 3``,
``0 <= b <= 1`` and ``0 <= c <= 0.5``:
>>> popt, pcov = curve_fit(func, xdata, ydata, bounds=(0, [3., 1., 0.5]))
>>> popt
array([2.43736712, 1.        , 0.34463856])
>>> plt.plot(xdata, func(xdata, *popt), 'g--',
...          label='fit: a=%5.3f, b=%5.3f, c=%5.3f' % tuple(popt))
>>> plt.xlabel('x')
>>> plt.ylabel('y')
>>> plt.legend()
>>> plt.show()
For reliable results, the model `func` should not be overparametrized;
redundant parameters can cause unreliable covariance matrices and, in some
cases, poorer quality fits. As a quick check of whether the model may be
overparameterized, calculate the condition number of the covariance matrix:
>>> np.linalg.cond(pcov)
34.571092161547405  # may vary
The value is small, so it does not raise much concern. If, however, we were
to add a fourth parameter ``d`` to `func` with the same effect as ``a``:
>>> def func(x, a, b, c, d):
...     return a * d * np.exp(-b * x) + c  # a and d are redundant
>>> popt, pcov = curve_fit(func, xdata, ydata)
>>> np.linalg.cond(pcov)
1.13250718925596e+32  # may vary
Such a large value is cause for concern. The diagonal elements of the
covariance matrix, which is related to uncertainty of the fit, gives more
information:
>>> np.diag(pcov)
array([1.48814742e+29, 3.78596560e-02, 5.39253738e-03, 2.76417220e+28])  # may vary
Note that the first and last terms are much larger than the other elements,
suggesting that the optimal values of these parameters are ambiguous and
that only one of these parameters is needed in the model.
Definition at line 571 of file _minpack_py.py.
References leastsq().
fixed_point()
scipy.optimize._minpack_py.fixed_point (func, x0, args = (), xtol = 1e-8, maxiter = 500, method = 'del2')
Find a fixed point of the function.
Given a function of one or more variables and a starting point, find a
fixed point of the function: i.e., where ``func(x0) == x0``.
Parameters
----------
func : function
    Function to evaluate.
x0 : array_like
    Fixed point of function.
args : tuple, optional
    Extra arguments to `func`.
xtol : float, optional
    Convergence tolerance, defaults to 1e-08.
maxiter : int, optional
    Maximum number of iterations, defaults to 500.
method : {"del2", "iteration"}, optional
    Method of finding the fixed-point, defaults to "del2",
    which uses Steffensen's Method with Aitken's ``Del^2``
    convergence acceleration [1]_. The "iteration" method simply iterates
    the function until convergence is detected, without attempting to
    accelerate the convergence.
References
----------
.. [1] Burden, Faires, "Numerical Analysis", 5th edition, pg. 80
Examples
--------
>>> import numpy as np
>>> from scipy import optimize
>>> def func(x, c1, c2):
...    return np.sqrt(c1/(x+c2))
>>> c1 = np.array([10,12.])
>>> c2 = np.array([3, 5.])
>>> optimize.fixed_point(func, [1.2, 1.3], args=(c1,c2))
array([ 1.4920333 ,  1.37228132])
Definition at line 1076 of file _minpack_py.py.
fsolve()
scipy.optimize._minpack_py.fsolve (func, x0, args = (), fprime = None, full_output = 0, col_deriv = 0, xtol = 1.49012e-8, maxfev = 0, band = None, epsfcn = None, factor = 100, diag = None)
Find the roots of a function.
Return the roots of the (non-linear) equations defined by
``func(x) = 0`` given a starting estimate.
Parameters
----------
func : callable ``f(x, *args)``
    A function that takes at least one (possibly vector) argument,
    and returns a value of the same length.
x0 : ndarray
    The starting estimate for the roots of ``func(x) = 0``.
args : tuple, optional
    Any extra arguments to `func`.
fprime : callable ``f(x, *args)``, optional
    A function to compute the Jacobian of `func` with derivatives
    across the rows. By default, the Jacobian will be estimated.
full_output : bool, optional
    If True, return optional outputs.
col_deriv : bool, optional
    Specify whether the Jacobian function computes derivatives down
    the columns (faster, because there is no transpose operation).
xtol : float, optional
    The calculation will terminate if the relative error between two
    consecutive iterates is at most `xtol`.
maxfev : int, optional
    The maximum number of calls to the function. If zero, then
    ``100*(N+1)`` is the maximum where N is the number of elements
    in `x0`.
band : tuple, optional
    If set to a two-sequence containing the number of sub- and
    super-diagonals within the band of the Jacobi matrix, the
    Jacobi matrix is considered banded (only for ``fprime=None``).
epsfcn : float, optional
    A suitable step length for the forward-difference
    approximation of the Jacobian (for ``fprime=None``). If
    `epsfcn` is less than the machine precision, it is assumed
    that the relative errors in the functions are of the order of
    the machine precision.
factor : float, optional
    A parameter determining the initial step bound
    (``factor * || diag * x||``). Should be in the interval
    ``(0.1, 100)``.
diag : sequence, optional
    N positive entries that serve as a scale factors for the
    variables.
Returns
-------
x : ndarray
    The solution (or the result of the last iteration for
    an unsuccessful call).
infodict : dict
    A dictionary of optional outputs with the keys:
    ``nfev``
        number of function calls
    ``njev``
        number of Jacobian calls
    ``fvec``
        function evaluated at the output
    ``fjac``
        the orthogonal matrix, q, produced by the QR
        factorization of the final approximate Jacobian
        matrix, stored column wise
    ``r``
        upper triangular matrix produced by QR factorization
        of the same matrix
    ``qtf``
        the vector ``(transpose(q) * fvec)``
ier : int
    An integer flag.  Set to 1 if a solution was found, otherwise refer
    to `mesg` for more information.
mesg : str
    If no solution is found, `mesg` details the cause of failure.
See Also
--------
root : Interface to root finding algorithms for multivariate
       functions. See the ``method='hybr'`` in particular.
Notes
-----
``fsolve`` is a wrapper around MINPACK's hybrd and hybrj algorithms.
Examples
--------
Find a solution to the system of equations:
``x0*cos(x1) = 4,  x1*x0 - x1 = 5``.
>>> import numpy as np
>>> from scipy.optimize import fsolve
>>> def func(x):
...     return [x[0] * np.cos(x[1]) - 4,
...             x[1] * x[0] - x[1] - 5]
>>> root = fsolve(func, [1, 1])
>>> root
array([6.50409711, 0.90841421])
>>> np.isclose(func(root), [0.0, 0.0])  # func(root) should be almost 0.0.
array([ True,  True])
Definition at line 47 of file _minpack_py.py.
References _root_hybr().
leastsq()
scipy.optimize._minpack_py.leastsq (func, x0, args = (), Dfun = None, full_output = False, col_deriv = False, ftol = 1.49012e-8, xtol = 1.49012e-8, gtol = 0.0, maxfev = 0, epsfcn = None, factor = 100, diag = None)
Minimize the sum of squares of a set of equations.
::
    x = arg min(sum(func(y)**2,axis=0))
             y
Parameters
----------
func : callable
    Should take at least one (possibly length ``N`` vector) argument and
    returns ``M`` floating point numbers. It must not return NaNs or
    fitting might fail. ``M`` must be greater than or equal to ``N``.
x0 : ndarray
    The starting estimate for the minimization.
args : tuple, optional
    Any extra arguments to func are placed in this tuple.
Dfun : callable, optional
    A function or method to compute the Jacobian of func with derivatives
    across the rows. If this is None, the Jacobian will be estimated.
full_output : bool, optional
    If ``True``, return all optional outputs (not just `x` and `ier`).
col_deriv : bool, optional
    If ``True``, specify that the Jacobian function computes derivatives
    down the columns (faster, because there is no transpose operation).
ftol : float, optional
    Relative error desired in the sum of squares.
xtol : float, optional
    Relative error desired in the approximate solution.
gtol : float, optional
    Orthogonality desired between the function vector and the columns of
    the Jacobian.
maxfev : int, optional
    The maximum number of calls to the function. If `Dfun` is provided,
    then the default `maxfev` is 100*(N+1) where N is the number of elements
    in x0, otherwise the default `maxfev` is 200*(N+1).
epsfcn : float, optional
    A variable used in determining a suitable step length for the forward-
    difference approximation of the Jacobian (for Dfun=None).
    Normally the actual step length will be sqrt(epsfcn)*x
    If epsfcn is less than the machine precision, it is assumed that the
    relative errors are of the order of the machine precision.
factor : float, optional
    A parameter determining the initial step bound
    (``factor * || diag * x||``). Should be in interval ``(0.1, 100)``.
diag : sequence, optional
    N positive entries that serve as a scale factors for the variables.
Returns
-------
x : ndarray
    The solution (or the result of the last iteration for an unsuccessful
    call).
cov_x : ndarray
    The inverse of the Hessian. `fjac` and `ipvt` are used to construct an
    estimate of the Hessian. A value of None indicates a singular matrix,
    which means the curvature in parameters `x` is numerically flat. To
    obtain the covariance matrix of the parameters `x`, `cov_x` must be
    multiplied by the variance of the residuals -- see curve_fit. Only
    returned if `full_output` is ``True``.
infodict : dict
    a dictionary of optional outputs with the keys:
    ``nfev``
        The number of function calls
    ``fvec``
        The function evaluated at the output
    ``fjac``
        A permutation of the R matrix of a QR
        factorization of the final approximate
        Jacobian matrix, stored column wise.
        Together with ipvt, the covariance of the
        estimate can be approximated.
    ``ipvt``
        An integer array of length N which defines
        a permutation matrix, p, such that
        fjac*p = q*r, where r is upper triangular
        with diagonal elements of nonincreasing
        magnitude. Column j of p is column ipvt(j)
        of the identity matrix.
    ``qtf``
        The vector (transpose(q) * fvec).
    Only returned if `full_output` is ``True``.
mesg : str
    A string message giving information about the cause of failure.
    Only returned if `full_output` is ``True``.
ier : int
    An integer flag. If it is equal to 1, 2, 3 or 4, the solution was
    found. Otherwise, the solution was not found. In either case, the
    optional output variable 'mesg' gives more information.
See Also
--------
least_squares : Newer interface to solve nonlinear least-squares problems
    with bounds on the variables. See ``method='lm'`` in particular.
Notes
-----
"leastsq" is a wrapper around MINPACK's lmdif and lmder algorithms.
cov_x is a Jacobian approximation to the Hessian of the least squares
objective function.
This approximation assumes that the objective function is based on the
difference between some observed target data (ydata) and a (non-linear)
function of the parameters `f(xdata, params)` ::
       func(params) = ydata - f(xdata, params)
so that the objective function is ::
       min   sum((ydata - f(xdata, params))**2, axis=0)
     params
The solution, `x`, is always a 1-D array, regardless of the shape of `x0`,
or whether `x0` is a scalar.
Examples
--------
>>> from scipy.optimize import leastsq
>>> def func(x):
...     return 2*(x-3)**2+1
>>> leastsq(func, 0)
(array([2.99999999]), 1)
Definition at line 281 of file _minpack_py.py.
Referenced by scipy.optimize._root._root_leastsq(), and curve_fit().
Variable Documentation
__all__
list scipy.optimize._minpack_py.__all__ = ['fsolve', 'leastsq', 'fixed_point', 'curve_fit'] private
Definition at line 20 of file _minpack_py.py.
error
scipy.optimize._minpack_py.error = _minpack.error
Definition at line 18 of file _minpack_py.py.
LEASTSQ_FAILURE
list scipy.optimize._minpack_py.LEASTSQ_FAILURE = [5, 6, 7, 8]
Definition at line 278 of file _minpack_py.py.
LEASTSQ_SUCCESS
list scipy.optimize._minpack_py.LEASTSQ_SUCCESS = [1, 2, 3, 4]
Definition at line 277 of file _minpack_py.py.