Code Cloning Analysis: matplotlib.ticker.LogLocator Class Reference
matplotlib.ticker.LogLocator Class Reference
Public Member Functions
__init__ (self, base=10.0, subs=(1.0,), *, numticks=None)
set_params (self, base=None, subs=None, *, numticks=None)
__call__ (self)
tick_values (self, vmin, vmax)
view_limits (self, vmin, vmax)
nonsingular (self, vmin, vmax)
Public Member Functions inherited from matplotlib.ticker.Locator
__call__ (self)
raise_if_exceeds (self, locs)
Public Member Functions inherited from matplotlib.ticker.TickHelper
set_axis (self, axis)
create_dummy_axis (self, **kwargs)
Public Attributes
str numticks = numticks
Protected Member Functions
_set_subs (self, subs)
Protected Attributes
_base = float(base)
str _subs = 'auto'
Additional Inherited Members
Static Public Attributes inherited from matplotlib.ticker.Locator
int MAXTICKS = 1000
Static Public Attributes inherited from matplotlib.ticker.TickHelper
axis = None
Detailed Description
Place logarithmically spaced ticks.
Places ticks at the values ``subs[j] * base**i``.
Definition at line 2330 of file ticker.py.
Constructor & Destructor Documentation
__init__()
matplotlib.ticker.LogLocator.__init__ (self, base = 10.0, subs = (1.0,), * , numticks = None)
Parameters
----------
base : float, default: 10.0
    The base of the log used, so major ticks are placed at ``base**n``, where
    ``n`` is an integer.
subs : None or {'auto', 'all'} or sequence of float, default: (1.0,)
    Gives the multiples of integer powers of the base at which to place ticks.
    The default of ``(1.0, )`` places ticks only at integer powers of the base.
    Permitted string values are ``'auto'`` and ``'all'``. Both of these use an
    algorithm based on the axis view limits to determine whether and how to put
    ticks between integer powers of the base:
    - ``'auto'``: Ticks are placed only between integer powers.
    - ``'all'``: Ticks are placed between *and* at integer powers.
    - ``None``: Equivalent to ``'auto'``.
numticks : None or int, default: None
    The maximum number of ticks to allow on a given axis. The default of
    ``None`` will try to choose intelligently as long as this Locator has
    already been assigned to an axis using `~.axis.Axis.get_tick_space`, but
    otherwise falls back to 9.
Definition at line 2337 of file ticker.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__call__()
matplotlib.ticker.LogLocator.__call__ (self)
Return the locations of the ticks.
Definition at line 2398 of file ticker.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), and scipy.interpolate._fitpack2.SphereBivariateSpline.ev().
_set_subs()
matplotlib.ticker.LogLocator._set_subs (self, subs) protected
Set the minor ticks for the log scaling every ``base**i*subs[j]``.
Definition at line 2377 of file ticker.py.
nonsingular()
matplotlib.ticker.LogLocator.nonsingular (self, v0, v1)
Adjust a range as needed to avoid singularities.
This method gets called during autoscaling, with ``(v0, v1)`` set to
the data limits on the Axes if the Axes contains any data, or
``(-inf, +inf)`` if not.
- If ``v0 == v1`` (possibly up to some floating point slop), this
  method returns an expanded interval around this value.
- If ``(v0, v1) == (-inf, +inf)``, this method returns appropriate
  default view limits.
- Otherwise, ``(v0, v1)`` is returned without modification.
Reimplemented from matplotlib.ticker.Locator.
Definition at line 2493 of file ticker.py.
Referenced by pandas.plotting._matplotlib.converter.MilliSecondLocator.autoscale().
set_params()
matplotlib.ticker.LogLocator.set_params (self, base = None, subs = None, * , numticks = None)
Set parameters within this locator.
Reimplemented from matplotlib.ticker.Locator.
Definition at line 2368 of file ticker.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.theta().
tick_values()
matplotlib.ticker.LogLocator.tick_values (self, vmin, vmax)
Return the values of the located ticks given **vmin** and **vmax**.
.. note::
    To get tick locations with the vmin and vmax values defined
    automatically for the associated ``axis`` simply call
    the Locator instance::
        >>> print(type(loc))
        <type 'Locator'>
        >>> print(loc())
        [1, 2, 3, 4]
Reimplemented from matplotlib.ticker.Locator.
Definition at line 2403 of file ticker.py.
view_limits()
matplotlib.ticker.LogLocator.view_limits (self, vmin, vmax)
Try to choose the view limits intelligently.
Reimplemented from matplotlib.ticker.Locator.
Definition at line 2481 of file ticker.py.
Member Data Documentation
_base
matplotlib.ticker.LogLocator._base = float(base) protected
Definition at line 2364 of file ticker.py.
Referenced by pip._vendor.distlib.locators.Page.__init__().
_subs
matplotlib.ticker.LogLocator._subs = 'auto' protected
Definition at line 2382 of file ticker.py.
numticks
str matplotlib.ticker.LogLocator.numticks = numticks
Definition at line 2366 of file ticker.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/ticker.py