Code Cloning Analysis: pandas.io.excel._openpyxl.OpenpyxlReader Class Reference
pandas.io.excel._openpyxl.OpenpyxlReader Class Reference
Public Member Functions
None __init__ (self, FilePath|ReadBuffer[bytes] filepath_or_buffer, StorageOptions|None storage_options=None, dict|None engine_kwargs=None)
Workbook load_workbook (self, FilePath|ReadBuffer[bytes] filepath_or_buffer, engine_kwargs)
list[str] sheet_names (self)
get_sheet_by_name (self, str name)
get_sheet_by_index (self, int index)
list[list[Scalar]] get_sheet_data (self, sheet, int|None file_rows_needed=None)
Public Member Functions inherited from pandas.io.excel._base.BaseExcelReader
None __init__ (self, filepath_or_buffer, StorageOptions|None storage_options=None, dict|None engine_kwargs=None)
None close (self)
None raise_if_bad_sheet_by_index (self, int index)
None raise_if_bad_sheet_by_name (self, str name)
parse (self, str|int|list[int]|list[str]|None sheet_name=0, int|Sequence[int]|None header=0, SequenceNotStr[Hashable]|range|None names=None, int|Sequence[int]|None index_col=None, usecols=None, DtypeArg|None dtype=None, Iterable[Hashable]|None true_values=None, Iterable[Hashable]|None false_values=None, Sequence[int]|int|Callable[[int], object]|None skiprows=None, int|None nrows=None, na_values=None, bool verbose=False, list|dict|bool parse_dates=False, Callable|lib.NoDefault date_parser=lib.no_default, dict[Hashable, str]|str|None date_format=None, str|None thousands=None, str decimal=".", str|None comment=None, int skipfooter=0, DtypeBackend|lib.NoDefault dtype_backend=lib.no_default, **kwds)
Protected Member Functions
type[Workbook] _workbook_class (self)
Scalar _convert_cell (self, cell)
Protected Member Functions inherited from pandas.io.excel._base.BaseExcelReader
int _check_skiprows_func (self, Callable skiprows, int rows_to_use)
int|None _calc_rows (self, int|Sequence[int]|None header, int|Sequence[int]|None index_col, Sequence[int]|int|Callable[[int], object]|None skiprows, int|None nrows)
Additional Inherited Members
Public Attributes inherited from pandas.io.excel._base.BaseExcelReader
handles
_WorkbookT book = self.handles.handle
Detailed Description
Definition at line 533 of file _openpyxl.py.
Constructor & Destructor Documentation
__init__()
None pandas.io.excel._openpyxl.OpenpyxlReader.__init__ (self, FilePath | ReadBuffer[bytes] filepath_or_buffer, StorageOptions | None storage_options = None, dict | None engine_kwargs = None)
Reader using openpyxl engine.
Parameters
----------
filepath_or_buffer : str, path object or Workbook
    Object to be parsed.
{storage_options}
engine_kwargs : dict, optional
    Arbitrary keyword arguments passed to excel engine.
Definition at line 535 of file _openpyxl.py.
References __init__(), _convert_cell(), pandas.io.excel._base.BaseExcelReader.book, pandas.io.excel._base.BaseExcelReader.raise_if_bad_sheet_by_index(), and pandas.io.excel._base.BaseExcelReader.raise_if_bad_sheet_by_name().
Referenced by __init__(), sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_convert_cell()
Scalar pandas.io.excel._openpyxl.OpenpyxlReader._convert_cell (self, cell) protected
Definition at line 589 of file _openpyxl.py.
Referenced by __init__(), and pandas.io.excel._pyxlsb.PyxlsbReader.__init__().
_workbook_class()
type[Workbook] pandas.io.excel._openpyxl.OpenpyxlReader._workbook_class (self) protected
Reimplemented from pandas.io.excel._base.BaseExcelReader.
Definition at line 560 of file _openpyxl.py.
get_sheet_by_index()
pandas.io.excel._openpyxl.OpenpyxlReader.get_sheet_by_index (self, int index)
Reimplemented from pandas.io.excel._base.BaseExcelReader.
Definition at line 585 of file _openpyxl.py.
get_sheet_by_name()
pandas.io.excel._openpyxl.OpenpyxlReader.get_sheet_by_name (self, str name)
Reimplemented from pandas.io.excel._base.BaseExcelReader.
Definition at line 581 of file _openpyxl.py.
get_sheet_data()
list[list[Scalar]] pandas.io.excel._openpyxl.OpenpyxlReader.get_sheet_data (self, sheet, int | None file_rows_needed = None)
Reimplemented from pandas.io.excel._base.BaseExcelReader.
Definition at line 607 of file _openpyxl.py.
load_workbook()
Workbook pandas.io.excel._openpyxl.OpenpyxlReader.load_workbook (self, FilePath | ReadBuffer[bytes] filepath_or_buffer, engine_kwargs)
Reimplemented from pandas.io.excel._base.BaseExcelReader.
Definition at line 565 of file _openpyxl.py.
sheet_names()
list[str] pandas.io.excel._openpyxl.OpenpyxlReader.sheet_names (self)
Reimplemented from pandas.io.excel._base.BaseExcelReader.
Definition at line 578 of file _openpyxl.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/io/excel/_openpyxl.py