Code Cloning Analysis: pandas.core.dtypes.cast Namespace Reference
pandas.core.dtypes.cast Namespace Reference
Functions
ArrayLike maybe_convert_platform (list|tuple|range|np.ndarray|ExtensionArray values)
bool is_nested_object (obj)
Scalar maybe_box_datetimelike (Scalar value, Dtype|None dtype=None)
Scalar|None|NAType maybe_box_native (Scalar|None|NAType value)
Scalar _maybe_unbox_datetimelike (Scalar value, DtypeObj dtype)
_disallow_mismatched_datetimelike (value, DtypeObj dtype)
np.ndarray maybe_downcast_to_dtype (np.ndarray result, str|np.dtype dtype)
ArrayLike maybe_downcast_to_dtype (ExtensionArray result, str|np.dtype dtype)
ArrayLike maybe_downcast_to_dtype (ArrayLike result, str|np.dtype dtype)
np.ndarray maybe_downcast_numeric (np.ndarray result, np.dtype dtype, bool do_round=False)
ArrayLike maybe_downcast_numeric (ExtensionArray result, DtypeObj dtype, bool do_round=False)
ArrayLike maybe_downcast_numeric (ArrayLike result, DtypeObj dtype, bool do_round=False)
NumpyIndexT maybe_upcast_numeric_to_64bit (NumpyIndexT arr)
ArrayLike maybe_cast_pointwise_result (ArrayLike result, DtypeObj dtype, bool numeric_only=False, bool same_dtype=True)
ArrayLike _maybe_cast_to_extension_array (type[ExtensionArray] cls, ArrayLike obj, ExtensionDtype|None dtype=None)
np.dtype ensure_dtype_can_hold_na (np.dtype dtype)
ExtensionDtype ensure_dtype_can_hold_na (ExtensionDtype dtype)
DtypeObj ensure_dtype_can_hold_na (DtypeObj dtype)
maybe_promote (np.dtype dtype, fill_value=np.nan)
_maybe_promote_cached (dtype, fill_value, fill_value_type)
_maybe_promote (np.dtype dtype, fill_value=np.nan)
_ensure_dtype_type (value, np.dtype dtype)
tuple[DtypeObj, Any] infer_dtype_from (val)
tuple[DtypeObj, Any] infer_dtype_from_scalar (val)
dict[Scalar, Scalar] dict_compat (dict[Scalar, Scalar] d)
tuple[DtypeObj, ArrayLike] infer_dtype_from_array (arr)
_maybe_infer_dtype_type (element)
None invalidate_string_dtypes (set[DtypeObj] dtype_set)
np.ndarray coerce_indexer_dtype (indexer, categories)
DtypeObj convert_dtypes (ArrayLike input_array, bool convert_string=True, bool convert_integer=True, bool convert_boolean=True, bool convert_floating=True, bool infer_objects=False, Literal["numpy_nullable", "pyarrow"] dtype_backend="numpy_nullable")
np.ndarray|DatetimeArray|TimedeltaArray|PeriodArray|IntervalArray maybe_infer_to_datetimelike (npt.NDArray[np.object_] value, bool convert_to_nullable_dtype=False)
ExtensionArray|np.ndarray maybe_cast_to_datetime (np.ndarray|list value, np.dtype dtype)
None _ensure_nanosecond_dtype (DtypeObj dtype)
DtypeObj find_result_type (DtypeObj left_dtype, Any right)
DtypeObj common_dtype_categorical_compat (Sequence[Index|ArrayLike] objs, DtypeObj dtype)
np.dtype np_find_common_type (*np.dtype dtypes)
np.dtype find_common_type (list[np.dtype] types)
DtypeObj find_common_type (list[ExtensionDtype] types)
DtypeObj find_common_type (list[DtypeObj] types)
find_common_type (types)
np.ndarray construct_2d_arraylike_from_scalar (Scalar value, int length, int width, np.dtype dtype, bool copy)
ArrayLike construct_1d_arraylike_from_scalar (Scalar value, int length, DtypeObj|None dtype)
_maybe_box_and_unbox_datetimelike (Scalar value, DtypeObj dtype)
np.ndarray construct_1d_object_array_from_listlike (Collection values)
np.ndarray maybe_cast_to_integer_array (list|np.ndarray arr, np.dtype dtype)
bool can_hold_element (ArrayLike arr, Any element)
Any np_can_hold_element (np.dtype dtype, Any element)
bool _dtype_can_hold_range (range rng, np.dtype dtype)
bool np_can_cast_scalar (Scalar element, np.dtype dtype)
Variables
_int8_max = np.iinfo(np.int8).max
_int16_max = np.iinfo(np.int16).max
_int32_max = np.iinfo(np.int32).max
_dtype_obj = np.dtype(object)
NumpyArrayT = TypeVar("NumpyArrayT", bound=np.ndarray)
dict _canonical_nans
Detailed Description
Routines for casting.
Function Documentation
_disallow_mismatched_datetimelike()
pandas.core.dtypes.cast._disallow_mismatched_datetimelike (value, DtypeObj dtype) protected
numpy allows np.array(dt64values, dtype="timedelta64[ns]") and
vice-versa, but we do not want to allow this, so we need to
check explicitly
Definition at line 233 of file cast.py.
Referenced by _maybe_unbox_datetimelike().
_dtype_can_hold_range()
bool pandas.core.dtypes.cast._dtype_can_hold_range (range rng, np.dtype dtype) protected
_maybe_infer_dtype_type infers to int64 (and float64 for very large endpoints),
but in many cases a range can be held by a smaller integer dtype.
Check if this is one of those cases.
Definition at line 1959 of file cast.py.
References np_can_cast_scalar().
Referenced by np_can_hold_element().
_ensure_dtype_type()
pandas.core.dtypes.cast._ensure_dtype_type (value, np.dtype dtype) protected
Ensure that the given value is an instance of the given dtype.
e.g. if out dtype is np.complex64_, we should have an instance of that
as opposed to a python complex object.
Parameters
----------
value : object
dtype : np.dtype
Returns
-------
object
Definition at line 736 of file cast.py.
Referenced by maybe_promote().
_ensure_nanosecond_dtype()
None pandas.core.dtypes.cast._ensure_nanosecond_dtype (DtypeObj dtype) protected
Convert dtypes with granularity less than nanosecond to nanosecond
>>> _ensure_nanosecond_dtype(np.dtype("M8[us]"))
>>> _ensure_nanosecond_dtype(np.dtype("M8[D]"))
Traceback (most recent call last):
    ...
TypeError: dtype=datetime64[D] is not supported. Supported resolutions are 's', 'ms', 'us', and 'ns'
>>> _ensure_nanosecond_dtype(np.dtype("m8[ps]"))
Traceback (most recent call last):
    ...
TypeError: dtype=timedelta64[ps] is not supported. Supported resolutions are 's', 'ms', 'us', and 'ns'
Definition at line 1249 of file cast.py.
Referenced by maybe_cast_to_datetime().
_maybe_box_and_unbox_datetimelike()
pandas.core.dtypes.cast._maybe_box_and_unbox_datetimelike (Scalar value, DtypeObj dtype) protected
Definition at line 1579 of file cast.py.
_maybe_cast_to_extension_array()
ArrayLike pandas.core.dtypes.cast._maybe_cast_to_extension_array (type[ExtensionArray] cls, ArrayLike obj, ExtensionDtype | None dtype = None) protected
Call to `_from_sequence` that returns the object unchanged on Exception.
Parameters
----------
cls : class, subclass of ExtensionArray
obj : arraylike
    Values to pass to cls._from_sequence
dtype : ExtensionDtype, optional
Returns
-------
ExtensionArray or obj
Definition at line 480 of file cast.py.
Referenced by maybe_cast_pointwise_result().
_maybe_infer_dtype_type()
pandas.core.dtypes.cast._maybe_infer_dtype_type (element) protected
Try to infer an object's dtype, for use in arithmetic ops.
Uses `element.dtype` if that's available.
Objects implementing the iterator protocol are cast to a NumPy array,
and from there the array's type is used.
Parameters
----------
element : object
    Possibly has a `.dtype` attribute, and possibly the iterator
    protocol.
Returns
-------
tipo : type
Examples
--------
>>> from collections import namedtuple
>>> Foo = namedtuple("Foo", "dtype")
>>> _maybe_infer_dtype_type(Foo(np.dtype("i8")))
dtype('int64')
Definition at line 921 of file cast.py.
Referenced by np_can_hold_element().
_maybe_promote()
pandas.core.dtypes.cast._maybe_promote (np.dtype dtype, fill_value = np.nan) protected
Definition at line 613 of file cast.py.
_maybe_promote_cached()
pandas.core.dtypes.cast._maybe_promote_cached (dtype, fill_value, fill_value_type) protected
Definition at line 606 of file cast.py.
_maybe_unbox_datetimelike()
Scalar pandas.core.dtypes.cast._maybe_unbox_datetimelike (Scalar value, DtypeObj dtype) protected
Convert a Timedelta or Timestamp to timedelta64 or datetime64 for setting
into a numpy array.  Failing to unbox would risk dropping nanoseconds.
Notes
-----
Caller is responsible for checking dtype.kind in "mM"
Definition at line 207 of file cast.py.
References _disallow_mismatched_datetimelike().
Referenced by construct_1d_arraylike_from_scalar().
can_hold_element()
bool pandas.core.dtypes.cast.can_hold_element (ArrayLike arr, Any element)
Can we do an inplace setitem with this element in an array with this dtype?
Parameters
----------
arr : np.ndarray or ExtensionArray
element : Any
Returns
-------
bool
Definition at line 1733 of file cast.py.
References np_can_hold_element().
coerce_indexer_dtype()
np.ndarray pandas.core.dtypes.cast.coerce_indexer_dtype (indexer, categories)
coerce the indexer input array to the smallest dtype possible
Definition at line 972 of file cast.py.
common_dtype_categorical_compat()
DtypeObj pandas.core.dtypes.cast.common_dtype_categorical_compat (Sequence[Index | ArrayLike] objs, DtypeObj dtype)
Update the result of find_common_type to account for NAs in a Categorical.
Parameters
----------
objs : list[np.ndarray | ExtensionArray | Index]
dtype : np.dtype or ExtensionDtype
Returns
-------
np.dtype or ExtensionDtype
Definition at line 1364 of file cast.py.
construct_1d_arraylike_from_scalar()
ArrayLike pandas.core.dtypes.cast.construct_1d_arraylike_from_scalar (Scalar value, int length, DtypeObj | None dtype)
create a np.ndarray / pandas type of specified shape and dtype
filled with values
Parameters
----------
value : scalar value
length : int
dtype : pandas_dtype or np.dtype
Returns
-------
np.ndarray / pandas type of length, filled with value
Definition at line 1528 of file cast.py.
References _maybe_unbox_datetimelike(), infer_dtype_from_scalar(), and maybe_box_datetimelike().
construct_1d_object_array_from_listlike()
np.ndarray pandas.core.dtypes.cast.construct_1d_object_array_from_listlike (Collection values)
Transform any list-like object in a 1-dimensional numpy array of object
dtype.
Parameters
----------
values : any iterable which has a len()
Raises
------
TypeError
    * If `values` does not have a len()
Returns
-------
1-dimensional numpy array of dtype object
Definition at line 1589 of file cast.py.
Referenced by maybe_convert_platform().
construct_2d_arraylike_from_scalar()
np.ndarray pandas.core.dtypes.cast.construct_2d_arraylike_from_scalar (Scalar value, int length, int width, np.dtype dtype, bool copy)
Definition at line 1497 of file cast.py.
convert_dtypes()
DtypeObj pandas.core.dtypes.cast.convert_dtypes (ArrayLike input_array, bool convert_string = True, bool convert_integer = True, bool convert_boolean = True, bool convert_floating = True, bool infer_objects = False, Literal["numpy_nullable", "pyarrow"] dtype_backend = "numpy_nullable")
Convert objects to best possible type, and optionally,
to types supporting ``pd.NA``.
Parameters
----------
input_array : ExtensionArray or np.ndarray
convert_string : bool, default True
    Whether object dtypes should be converted to ``StringDtype()``.
convert_integer : bool, default True
    Whether, if possible, conversion can be done to integer extension types.
convert_boolean : bool, defaults True
    Whether object dtypes should be converted to ``BooleanDtypes()``.
convert_floating : bool, defaults True
    Whether, if possible, conversion can be done to floating extension types.
    If `convert_integer` is also True, preference will be give to integer
    dtypes if the floats can be faithfully casted to integers.
infer_objects : bool, defaults False
    Whether to also infer objects to float/int if possible. Is only hit if the
    object array contains pd.NA.
dtype_backend : {'numpy_nullable', 'pyarrow'}, default 'numpy_nullable'
    Back-end data type applied to the resultant :class:`DataFrame`
    (still experimental). Behaviour is as follows:
    * ``"numpy_nullable"``: returns nullable-dtype-backed :class:`DataFrame`
      (default).
    * ``"pyarrow"``: returns pyarrow-backed nullable :class:`ArrowDtype`
      DataFrame.
    .. versionadded:: 2.0
Returns
-------
np.dtype, or ExtensionDtype
Definition at line 984 of file cast.py.
dict_compat()
dict[Scalar, Scalar] pandas.core.dtypes.cast.dict_compat (dict[Scalar, Scalar] d)
Convert datetimelike-keyed dicts to a Timestamp-keyed dict.
Parameters
----------
d: dict-like object
Returns
-------
dict
Definition at line 863 of file cast.py.
References maybe_box_datetimelike().
ensure_dtype_can_hold_na() [1/3]
DtypeObj pandas.core.dtypes.cast.ensure_dtype_can_hold_na (DtypeObj dtype)
If we have a dtype that cannot hold NA values, find the best match that can.
Definition at line 524 of file cast.py.
ensure_dtype_can_hold_na() [2/3]
ExtensionDtype pandas.core.dtypes.cast.ensure_dtype_can_hold_na (ExtensionDtype dtype)
Definition at line 520 of file cast.py.
ensure_dtype_can_hold_na() [3/3]
np.dtype pandas.core.dtypes.cast.ensure_dtype_can_hold_na (np.dtype dtype)
Definition at line 515 of file cast.py.
find_common_type() [1/4]
DtypeObj pandas.core.dtypes.cast.find_common_type (list[DtypeObj] types)
Definition at line 1438 of file cast.py.
find_common_type() [2/4]
DtypeObj pandas.core.dtypes.cast.find_common_type (list[ExtensionDtype] types)
Definition at line 1433 of file cast.py.
find_common_type() [3/4]
np.dtype pandas.core.dtypes.cast.find_common_type (list[np.dtype] types)
Definition at line 1428 of file cast.py.
find_common_type() [4/4]
pandas.core.dtypes.cast.find_common_type (types)
Find a common data type among the given dtypes.
Parameters
----------
types : list of dtypes
Returns
-------
pandas extension or numpy dtype
See Also
--------
numpy.find_common_type
Definition at line 1442 of file cast.py.
References np_find_common_type().
find_result_type()
DtypeObj pandas.core.dtypes.cast.find_result_type (DtypeObj left_dtype, Any right)
Find the type/dtype for the result of an operation between objects.
This is similar to find_common_type, but looks at the right object instead
of just its dtype. This can be useful in particular when the right
object does not have a `dtype`.
Parameters
----------
left_dtype : np.dtype or ExtensionDtype
right : Any
Returns
-------
np.dtype or ExtensionDtype
See also
--------
find_common_type
numpy.result_type
Definition at line 1293 of file cast.py.
References infer_dtype_from().
infer_dtype_from()
tuple[DtypeObj, Any] pandas.core.dtypes.cast.infer_dtype_from (val)
Interpret the dtype from a scalar or array.
Parameters
----------
val : object
Definition at line 761 of file cast.py.
References infer_dtype_from_array(), and infer_dtype_from_scalar().
Referenced by find_result_type().
infer_dtype_from_array()
tuple[DtypeObj, ArrayLike] pandas.core.dtypes.cast.infer_dtype_from_array (arr)
Infer the dtype from an array.
Parameters
----------
arr : array
Returns
-------
tuple (pandas-compat dtype, array)
Examples
--------
>>> np.asarray([1, '1'])
array(['1', '1'], dtype='<U21')
>>> infer_dtype_from_array([1, '1'])
(dtype('O'), [1, '1'])
Definition at line 878 of file cast.py.
Referenced by infer_dtype_from().
infer_dtype_from_scalar()
tuple[DtypeObj, Any] pandas.core.dtypes.cast.infer_dtype_from_scalar (val)
Interpret the dtype from a scalar.
Parameters
----------
val : object
Definition at line 774 of file cast.py.
References infer_dtype_from_scalar().
Referenced by construct_1d_arraylike_from_scalar(), infer_dtype_from(), infer_dtype_from_scalar(), and maybe_promote().
invalidate_string_dtypes()
None pandas.core.dtypes.cast.invalidate_string_dtypes (set[DtypeObj] dtype_set)
Change string like dtypes to object for
``DataFrame.select_dtypes()``.
Definition at line 955 of file cast.py.
is_nested_object()
bool pandas.core.dtypes.cast.is_nested_object (obj)
return a boolean if we have a nested object, e.g. a Series with 1 or
more Series elements
This may not be necessarily be performant.
Definition at line 143 of file cast.py.
maybe_box_datetimelike()
Scalar pandas.core.dtypes.cast.maybe_box_datetimelike (Scalar value, Dtype | None dtype = None)
Cast scalar to Timestamp or Timedelta if scalar is datetime-like
and dtype is not object.
Parameters
----------
value : scalar
dtype : Dtype, optional
Returns
-------
scalar
Definition at line 158 of file cast.py.
Referenced by construct_1d_arraylike_from_scalar(), dict_compat(), and maybe_box_native().
maybe_box_native()
Scalar | None | NAType pandas.core.dtypes.cast.maybe_box_native (Scalar | None | NAType value)
If passed a scalar cast the scalar to a python native type.
Parameters
----------
value : scalar or Series
Returns
-------
scalar or Series
Definition at line 182 of file cast.py.
References maybe_box_datetimelike().
maybe_cast_pointwise_result()
ArrayLike pandas.core.dtypes.cast.maybe_cast_pointwise_result (ArrayLike result, DtypeObj dtype, bool numeric_only = False, bool same_dtype = True)
Try casting result of a pointwise operation back to the original dtype if
appropriate.
Parameters
----------
result : array-like
    Result to cast.
dtype : np.dtype or ExtensionDtype
    Input Series from which result was calculated.
numeric_only : bool, default False
    Whether to cast only numerics or datetimes as well.
same_dtype : bool, default True
    Specify dtype when calling _from_sequence
Returns
-------
result : array-like
    result maybe casted to the dtype.
Definition at line 440 of file cast.py.
References _maybe_cast_to_extension_array().
maybe_cast_to_datetime()
ExtensionArray | np.ndarray pandas.core.dtypes.cast.maybe_cast_to_datetime (np.ndarray | list value, np.dtype dtype)
try to cast the array/value to a datetimelike dtype, converting float
nan to iNaT
Caller is responsible for handling ExtensionDtype cases and non dt64/td64
cases.
Definition at line 1209 of file cast.py.
References _ensure_nanosecond_dtype().
Referenced by maybe_downcast_to_dtype().
maybe_cast_to_integer_array()
np.ndarray pandas.core.dtypes.cast.maybe_cast_to_integer_array (list | np.ndarray arr, np.dtype dtype)
Takes any dtype and returns the casted version, raising for when data is
incompatible with integer/unsigned integer dtypes.
Parameters
----------
arr : np.ndarray or list
    The array to cast.
dtype : np.dtype
    The integer dtype to cast the array to.
Returns
-------
ndarray
    Array of integer or unsigned integer dtype.
Raises
------
OverflowError : the dtype is incompatible with the data
ValueError : loss of precision has occurred during casting
Examples
--------
If you try to coerce negative values to unsigned integers, it raises:
>>> pd.Series([-1], dtype="uint64")
Traceback (most recent call last):
    ...
OverflowError: Trying to coerce negative values to unsigned integers
Also, if you try to coerce float values to integers, it raises:
>>> maybe_cast_to_integer_array([1, 2, 3.5], dtype=np.dtype("int64"))
Traceback (most recent call last):
    ...
ValueError: Trying to coerce float values to integers
Definition at line 1615 of file cast.py.
maybe_convert_platform()
ArrayLike pandas.core.dtypes.cast.maybe_convert_platform (list | tuple | range | np.ndarray | ExtensionArray values)
try to do platform conversion, allow ndarray or list here
Definition at line 123 of file cast.py.
References construct_1d_object_array_from_listlike().
maybe_downcast_numeric() [1/3]
ArrayLike pandas.core.dtypes.cast.maybe_downcast_numeric (ArrayLike result, DtypeObj dtype, bool do_round = False)
Subset of maybe_downcast_to_dtype restricted to numeric dtypes.
Parameters
----------
result : ndarray or ExtensionArray
dtype : np.dtype or ExtensionDtype
do_round : bool
Returns
-------
ndarray or ExtensionArray
Definition at line 330 of file cast.py.
maybe_downcast_numeric() [2/3]
ArrayLike pandas.core.dtypes.cast.maybe_downcast_numeric (ExtensionArray result, DtypeObj dtype, bool do_round = False)
Definition at line 324 of file cast.py.
maybe_downcast_numeric() [3/3]
np.ndarray pandas.core.dtypes.cast.maybe_downcast_numeric (np.ndarray result, np.dtype dtype, bool do_round = False)
Definition at line 317 of file cast.py.
maybe_downcast_to_dtype() [1/3]
ArrayLike pandas.core.dtypes.cast.maybe_downcast_to_dtype (ArrayLike result, str | np.dtype dtype)
try to cast to the specified dtype (e.g. convert back to bool/int
or could be an astype of float64->float32
Definition at line 258 of file cast.py.
References maybe_cast_to_datetime().
maybe_downcast_to_dtype() [2/3]
ArrayLike pandas.core.dtypes.cast.maybe_downcast_to_dtype (ExtensionArray result, str | np.dtype dtype)
Definition at line 254 of file cast.py.
maybe_downcast_to_dtype() [3/3]
np.ndarray pandas.core.dtypes.cast.maybe_downcast_to_dtype (np.ndarray result, str | np.dtype dtype)
Definition at line 249 of file cast.py.
maybe_infer_to_datetimelike()
np.ndarray | DatetimeArray | TimedeltaArray | PeriodArray | IntervalArray pandas.core.dtypes.cast.maybe_infer_to_datetimelike (npt.NDArray[np.object_] value, bool convert_to_nullable_dtype = False)
we might have a array (or single object) that is datetime like,
and no dtype is passed don't change the value unless we find a
datetime/timedelta set
this is pretty strict in that a datetime/timedelta is REQUIRED
in addition to possible nulls/string likes
Parameters
----------
value : np.ndarray[object]
Returns
-------
np.ndarray, DatetimeArray, TimedeltaArray, PeriodArray, or IntervalArray
Definition at line 1164 of file cast.py.
maybe_promote()
pandas.core.dtypes.cast.maybe_promote (np.dtype dtype, fill_value = np.nan)
Find the minimal dtype that can hold both the given dtype and fill_value.
Parameters
----------
dtype : np.dtype
fill_value : scalar, default np.nan
Returns
-------
dtype
    Upcasted from dtype argument if necessary.
fill_value
    Upcasted from fill_value argument if necessary.
Raises
------
ValueError
    If fill_value is a non-scalar and dtype is not object.
Definition at line 550 of file cast.py.
References _ensure_dtype_type(), infer_dtype_from_scalar(), and np_can_cast_scalar().
maybe_upcast_numeric_to_64bit()
NumpyIndexT pandas.core.dtypes.cast.maybe_upcast_numeric_to_64bit (NumpyIndexT arr)
If array is a int/uint/float bit size lower than 64 bit, upcast it to 64 bit.
Parameters
----------
arr : ndarray or ExtensionArray
Returns
-------
ndarray or ExtensionArray
Definition at line 417 of file cast.py.
np_can_cast_scalar()
bool pandas.core.dtypes.cast.np_can_cast_scalar (Scalar element, np.dtype dtype)
np.can_cast pandas-equivalent for pre 2-0 behavior that allowed scalar
inference
Parameters
----------
element : Scalar
dtype : np.dtype
Returns
-------
bool
Definition at line 1970 of file cast.py.
References np_can_hold_element().
Referenced by _dtype_can_hold_range(), and maybe_promote().
np_can_hold_element()
Any pandas.core.dtypes.cast.np_can_hold_element (np.dtype dtype, Any element)
Raise if we cannot losslessly set this element into an ndarray with this dtype.
Specifically about places where we disagree with numpy.  i.e. there are
cases where numpy will raise in doing the setitem that we do not check
for here, e.g. setting str "X" into a numeric ndarray.
Returns
-------
Any
    The element, potentially cast to the dtype.
Raises
------
ValueError : If we cannot losslessly store this element with this dtype.
Definition at line 1778 of file cast.py.
References _dtype_can_hold_range(), and _maybe_infer_dtype_type().
Referenced by can_hold_element(), and np_can_cast_scalar().
np_find_common_type()
np.dtype pandas.core.dtypes.cast.np_find_common_type (*np.dtype dtypes)
np.find_common_type implementation pre-1.25 deprecation using np.result_type
https://github.com/pandas-dev/pandas/pull/49569#issuecomment-1308300065
Parameters
----------
dtypes : np.dtypes
Returns
-------
np.dtype
Definition at line 1401 of file cast.py.
Referenced by find_common_type().
Variable Documentation
_canonical_nans
dict pandas.core.dtypes.cast._canonical_nans protected
Initial value:
=  {
    np.datetime64: np.datetime64("NaT", "ns"),
    np.timedelta64: np.timedelta64("NaT", "ns"),
    type(np.nan): np.nan,
}
Definition at line 543 of file cast.py.
_dtype_obj
pandas.core.dtypes.cast._dtype_obj = np.dtype(object) protected
Definition at line 118 of file cast.py.
_int16_max
pandas.core.dtypes.cast._int16_max = np.iinfo(np.int16).max protected
Definition at line 115 of file cast.py.
_int32_max
pandas.core.dtypes.cast._int32_max = np.iinfo(np.int32).max protected
Definition at line 116 of file cast.py.
_int8_max
pandas.core.dtypes.cast._int8_max = np.iinfo(np.int8).max protected
Definition at line 114 of file cast.py.
NumpyArrayT
pandas.core.dtypes.cast.NumpyArrayT = TypeVar("NumpyArrayT", bound=np.ndarray)
Definition at line 120 of file cast.py.