Code Cloning Analysis: matplotlib.projections.polar.RadialTick Class Reference
matplotlib.projections.polar.RadialTick Class Reference
Public Member Functions
__init__ (self, *args, **kwargs)
update_position (self, loc)
Protected Member Functions
_determine_anchor (self, mode, angle, start)
Detailed Description
A radial-axis tick.
This subclass of `.YTick` provides radial ticks with some small
modification to their re-positioning such that ticks are rotated based on
axes limits.  This results in ticks that are correctly perpendicular to
the spine. Labels are also rotated to be perpendicular to the spine, when
'auto' rotation is enabled.
Definition at line 556 of file polar.py.
Constructor & Destructor Documentation
__init__()
matplotlib.projections.polar.RadialTick.__init__ (self, * args, ** kwargs)
Definition at line 567 of file polar.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_determine_anchor()
matplotlib.projections.polar.RadialTick._determine_anchor (self, mode, angle, start) protected
Definition at line 572 of file polar.py.
update_position()
matplotlib.projections.polar.RadialTick.update_position (self, loc)
Definition at line 626 of file polar.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/projections/polar.py