Code Cloning Analysis: numpy.core.tests.test_mem_overlap Namespace Reference
numpy.core.tests.test_mem_overlap Namespace Reference
Classes
class TestUFunc
Functions
_indices_for_nelems (nelems)
_indices_for_axis ()
_indices (ndims)
_check_assignment (srcidx, dstidx)
test_overlapping_assignments ()
test_diophantine_fuzz ()
test_diophantine_overflow ()
check_may_share_memory_exact (a, b)
test_may_share_memory_manual ()
iter_random_view_pairs (x, same_steps=True, equal_size=False)
check_may_share_memory_easy_fuzz (get_max_work, same_steps, min_count)
test_may_share_memory_easy_fuzz ()
test_may_share_memory_harder_fuzz ()
test_shares_memory_api ()
test_may_share_memory_bad_max_work ()
test_internal_overlap_diophantine ()
test_internal_overlap_slices ()
check_internal_overlap (a, manual_expected=None)
test_internal_overlap_manual ()
test_internal_overlap_fuzz ()
test_non_ndarray_inputs ()
view_element_first_byte (x)
assert_copy_equivalent (operation, args, out, **kwargs)
Variables
int ndims = 2
int size = 10
shape = tuple([size] * ndims)
int MAY_SHARE_BOUNDS = 0
int MAY_SHARE_EXACT = -1
data = data
Function Documentation
_check_assignment()
numpy.core.tests.test_mem_overlap._check_assignment (srcidx, dstidx) protected
Check assignment arr[dstidx] = arr[srcidx] works.
Definition at line 55 of file test_mem_overlap.py.
References _check_assignment(), _indices(), numpy.core.fromnumeric.all(), numpy.core.fromnumeric.any(), numpy.lib.stride_tricks.as_strided(), numpy.core.fromnumeric.max(), numpy.core.fromnumeric.min(), numpy.core.fromnumeric.reshape(), numpy.core.fromnumeric.sum(), and numpy.core.fromnumeric.transpose().
Referenced by _check_assignment().
_indices()
numpy.core.tests.test_mem_overlap._indices (ndims) protected
Returns ((axis0_src, axis0_dst), (axis1_src, axis1_dst), ...) index pairs.
Definition at line 48 of file test_mem_overlap.py.
References _indices_for_axis().
Referenced by _check_assignment().
_indices_for_axis()
numpy.core.tests.test_mem_overlap._indices_for_axis () protected
Returns (src, dst) pairs of indices.
Definition at line 37 of file test_mem_overlap.py.
References _indices_for_nelems().
Referenced by _indices().
_indices_for_nelems()
numpy.core.tests.test_mem_overlap._indices_for_nelems (nelems) protected
Returns slices of length nelems, from start onwards, in direction sign.
Definition at line 21 of file test_mem_overlap.py.
Referenced by _indices_for_axis().
assert_copy_equivalent()
numpy.core.tests.test_mem_overlap.assert_copy_equivalent (operation, args, out, ** kwargs)
Check that operation(*args, out=out) produces results
equivalent to out[...] = operation(*args, out=out.copy())
Definition at line 576 of file test_mem_overlap.py.
References numpy.core.fromnumeric.any().
check_internal_overlap()
numpy.core.tests.test_mem_overlap.check_internal_overlap (a, manual_expected = None)
Definition at line 450 of file test_mem_overlap.py.
check_may_share_memory_easy_fuzz()
numpy.core.tests.test_mem_overlap.check_may_share_memory_easy_fuzz (get_max_work, same_steps, min_count)
Definition at line 322 of file test_mem_overlap.py.
check_may_share_memory_exact()
numpy.core.tests.test_mem_overlap.check_may_share_memory_exact (a, b)
Definition at line 157 of file test_mem_overlap.py.
iter_random_view_pairs()
numpy.core.tests.test_mem_overlap.iter_random_view_pairs (x, same_steps = True, equal_size = False)
Definition at line 234 of file test_mem_overlap.py.
test_diophantine_fuzz()
numpy.core.tests.test_mem_overlap.test_diophantine_fuzz ()
Definition at line 82 of file test_mem_overlap.py.
test_diophantine_overflow()
numpy.core.tests.test_mem_overlap.test_diophantine_overflow ()
Definition at line 142 of file test_mem_overlap.py.
test_internal_overlap_diophantine()
numpy.core.tests.test_mem_overlap.test_internal_overlap_diophantine ()
Definition at line 397 of file test_mem_overlap.py.
test_internal_overlap_fuzz()
numpy.core.tests.test_mem_overlap.test_internal_overlap_fuzz ()
Definition at line 511 of file test_mem_overlap.py.
test_internal_overlap_manual()
numpy.core.tests.test_mem_overlap.test_internal_overlap_manual ()
Definition at line 474 of file test_mem_overlap.py.
test_internal_overlap_slices()
numpy.core.tests.test_mem_overlap.test_internal_overlap_slices ()
Definition at line 419 of file test_mem_overlap.py.
test_may_share_memory_bad_max_work()
numpy.core.tests.test_mem_overlap.test_may_share_memory_bad_max_work ()
Definition at line 391 of file test_mem_overlap.py.
test_may_share_memory_easy_fuzz()
numpy.core.tests.test_mem_overlap.test_may_share_memory_easy_fuzz ()
Definition at line 355 of file test_mem_overlap.py.
test_may_share_memory_harder_fuzz()
numpy.core.tests.test_mem_overlap.test_may_share_memory_harder_fuzz ()
Definition at line 365 of file test_mem_overlap.py.
test_may_share_memory_manual()
numpy.core.tests.test_mem_overlap.test_may_share_memory_manual ()
Definition at line 183 of file test_mem_overlap.py.
test_non_ndarray_inputs()
numpy.core.tests.test_mem_overlap.test_non_ndarray_inputs ()
Definition at line 539 of file test_mem_overlap.py.
test_overlapping_assignments()
numpy.core.tests.test_mem_overlap.test_overlapping_assignments ()
Definition at line 69 of file test_mem_overlap.py.
test_shares_memory_api()
numpy.core.tests.test_mem_overlap.test_shares_memory_api ()
Definition at line 378 of file test_mem_overlap.py.
view_element_first_byte()
numpy.core.tests.test_mem_overlap.view_element_first_byte (x)
Construct an array viewing the first byte of each element of `x`
Definition at line 567 of file test_mem_overlap.py.
Variable Documentation
data
numpy.core.tests.test_mem_overlap.data = data
Definition at line 544 of file test_mem_overlap.py.
MAY_SHARE_BOUNDS
int numpy.core.tests.test_mem_overlap.MAY_SHARE_BOUNDS = 0
Definition at line 17 of file test_mem_overlap.py.
MAY_SHARE_EXACT
int numpy.core.tests.test_mem_overlap.MAY_SHARE_EXACT = -1
Definition at line 18 of file test_mem_overlap.py.
ndims
int numpy.core.tests.test_mem_overlap.ndims = 2
Definition at line 13 of file test_mem_overlap.py.
shape
numpy.core.tests.test_mem_overlap.shape = tuple([size] * ndims)
Definition at line 15 of file test_mem_overlap.py.
size
int numpy.core.tests.test_mem_overlap.size = 10
Definition at line 14 of file test_mem_overlap.py.