Code Cloning Analysis: matplotlib._mathtext.BakomaFonts Class Reference
matplotlib._mathtext.BakomaFonts Class Reference
Public Member Functions
__init__ (self, FontProperties default_font_prop, LoadFlags load_glyph_flags)
Public Member Functions inherited from matplotlib._mathtext.TruetypeFonts
__init__ (self, FontProperties default_font_prop, LoadFlags load_glyph_flags)
float get_xheight (self, str fontname, float fontsize, float dpi)
float get_underline_thickness (self, str font, float fontsize, float dpi)
float get_kern (self, str font1, str fontclass1, str sym1, float fontsize1, str font2, str fontclass2, str sym2, float fontsize2, float dpi)
Public Member Functions inherited from matplotlib._mathtext.Fonts
__init__ (self, FontProperties default_font_prop, LoadFlags load_glyph_flags)
FontMetrics get_metrics (self, str font, str font_class, str sym, float fontsize, float dpi)
None render_glyph (self, Output output, float ox, float oy, str font, str font_class, str sym, float fontsize, float dpi)
None render_rect_filled (self, Output output, float x1, float y1, float x2, float y2)
list[tuple[str, str]] get_sized_alternatives_for_symbol (self, str fontname, str sym)
Protected Member Functions
tuple[FT2Font, int, bool] _get_glyph (self, str fontname, str font_class, str sym)
Protected Member Functions inherited from matplotlib._mathtext.TruetypeFonts
FT2Font _get_font (self, str|int font)
float _get_offset (self, FT2Font font, Glyph glyph, float fontsize, float dpi)
FontInfo _get_info (self, str fontname, str font_class, str sym, float fontsize, float dpi)
Protected Attributes
_stix_fallback = StixFonts(default_font_prop, load_glyph_flags)
Protected Attributes inherited from matplotlib._mathtext.TruetypeFonts
dict _fonts = {}
Static Protected Attributes
dict _fontmap
_slanted_symbols = set(r"\int \oint".split())
Additional Inherited Members
Public Attributes inherited from matplotlib._mathtext.TruetypeFonts
dict fontmap = {}
Public Attributes inherited from matplotlib._mathtext.Fonts
default_font_prop = default_font_prop
load_glyph_flags = load_glyph_flags
Detailed Description
Use the Bakoma TrueType fonts for rendering.
Symbols are strewn about a number of font files, each of which has
its own proprietary 8-bit encoding.
Definition at line 434 of file _mathtext.py.
Constructor & Destructor Documentation
__init__()
matplotlib._mathtext.BakomaFonts.__init__ (self, FontProperties default_font_prop, LoadFlags load_glyph_flags)
Definition at line 451 of file _mathtext.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_get_glyph()
tuple[FT2Font, int, bool] matplotlib._mathtext.BakomaFonts._get_glyph (self, str fontname, str font_class, str sym) protected
Reimplemented from matplotlib._mathtext.TruetypeFonts.
Definition at line 462 of file _mathtext.py.
Member Data Documentation
_fontmap
dict matplotlib._mathtext.BakomaFonts._fontmap static protected
Initial value:
=  {
        'cal': 'cmsy10',
        'rm':  'cmr10',
        'tt':  'cmtt10',
        'it':  'cmmi10',
        'bf':  'cmb10',
        'sf':  'cmss10',
        'ex':  'cmex10',
    }
Definition at line 441 of file _mathtext.py.
_slanted_symbols
matplotlib._mathtext.BakomaFonts._slanted_symbols = set(r"\int \oint".split()) static protected
Definition at line 460 of file _mathtext.py.
_stix_fallback
matplotlib._mathtext.BakomaFonts._stix_fallback = StixFonts(default_font_prop, load_glyph_flags) protected
Definition at line 452 of file _mathtext.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/_mathtext.py