Code Cloning Analysis: matplotlib.backend_bases Namespace Reference
matplotlib.backend_bases Namespace Reference
Classes
class _Backend
class _Mode
class CloseEvent
class DrawEvent
class Event
class FigureCanvasBase
class FigureManagerBase
class GraphicsContextBase
class KeyEvent
class LocationEvent
class MouseButton
class MouseEvent
class NavigationToolbar2
class NonGuiException
class PickEvent
class RendererBase
class ResizeEvent
class ShowBase
class TimerBase
class ToolContainerBase
Functions
register_backend (format, backend, description=None)
get_registered_canvas_class (format)
_key_handler (event)
_mouse_handler (event)
_get_renderer (figure, print_method=None)
_no_output_draw (figure)
_is_non_interactive_terminal_ipython (ip)
_allow_interrupt (prepare_notifier, handle_sigint)
key_press_handler (event, canvas=None, toolbar=None)
button_press_handler (event, canvas=None, toolbar=None)
Variables
_log = logging.getLogger(__name__)
dict _default_filetypes
dict _default_backends
cursors = tools.cursors
Detailed Description
Abstract base classes define the primitives that renderers and
graphics contexts must implement to serve as a Matplotlib backend.
`RendererBase`
    An abstract base class to handle drawing/rendering operations.
`FigureCanvasBase`
    The abstraction layer that separates the `.Figure` from the backend
    specific details like a user interface drawing area.
`GraphicsContextBase`
    An abstract base class that provides color, line styles, etc.
`Event`
    The base class for all of the Matplotlib event handling.  Derived classes
    such as `KeyEvent` and `MouseEvent` store the meta data like keys and
    buttons pressed, x and y locations in pixel and `~.axes.Axes` coordinates.
`ShowBase`
    The base class for the ``Show`` class of each interactive backend; the
    'show' callable is then set to ``Show.__call__``.
`ToolContainerBase`
    The base class for the Toolbar class of each interactive backend.
Function Documentation
_allow_interrupt()
matplotlib.backend_bases._allow_interrupt (prepare_notifier, handle_sigint) protected
A context manager that allows terminating a plot by sending a SIGINT.  It
is necessary because the running backend prevents the Python interpreter
from running and processing signals (i.e., to raise a KeyboardInterrupt).
To solve this, one needs to somehow wake up the interpreter and make it
close the plot window.  We do this by using the signal.set_wakeup_fd()
function which organizes a write of the signal number into a socketpair.
A backend-specific function, *prepare_notifier*, arranges to listen to
the pair's read socket while the event loop is running.  (If it returns a
notifier object, that object is kept alive while the context manager runs.)
If SIGINT was indeed caught, after exiting the on_signal() function the
interpreter reacts to the signal according to the handler function which
had been set up by a signal.signal() call; here, we arrange to call the
backend-specific *handle_sigint* function.  Finally, we call the old SIGINT
handler with the same arguments that were given to our custom handler.
We do this only if the old handler for SIGINT was not None, which means
that a non-python handler was installed, i.e. in Julia, and not SIG_IGN
which means we should ignore the interrupts.
Parameters
----------
prepare_notifier : Callable[[socket.socket], object]
handle_sigint : Callable[[], object]
Definition at line 1604 of file backend_bases.py.
_get_renderer()
matplotlib.backend_bases._get_renderer (figure, print_method = None) protected
Get the renderer that would be used to save a `.Figure`.
If you need a renderer without any active draw methods use
renderer._draw_disabled to temporary patch them out at your call site.
Definition at line 1551 of file backend_bases.py.
Referenced by matplotlib.backend_bases.FigureCanvasBase.print_figure().
_is_non_interactive_terminal_ipython()
matplotlib.backend_bases._is_non_interactive_terminal_ipython (ip) protected
Return whether we are in a terminal IPython, but non interactive.
When in _terminal_ IPython, ip.parent will have and `interact` attribute,
if this attribute is False we do not setup eventloop integration as the
user will _not_ interact with IPython. In all other case (ZMQKernel, or is
interactive), we do.
Definition at line 1589 of file backend_bases.py.
Referenced by matplotlib.backend_bases.FigureCanvasBase.supports_blit().
_key_handler()
matplotlib.backend_bases._key_handler (event) protected
Definition at line 1505 of file backend_bases.py.
_mouse_handler()
matplotlib.backend_bases._mouse_handler (event) protected
Definition at line 1514 of file backend_bases.py.
_no_output_draw()
matplotlib.backend_bases._no_output_draw (figure) protected
Definition at line 1583 of file backend_bases.py.
button_press_handler()
matplotlib.backend_bases.button_press_handler (event, canvas = None, toolbar = None)
The default Matplotlib button actions for extra mouse buttons.
Parameters are as for `key_press_handler`, except that *event* is a
`MouseEvent`.
Definition at line 2519 of file backend_bases.py.
get_registered_canvas_class()
matplotlib.backend_bases.get_registered_canvas_class (format)
Return the registered default canvas for given file format.
Handles deferred import of required backend.
Definition at line 116 of file backend_bases.py.
Referenced by matplotlib.backend_bases.FigureCanvasBase._switch_canvas_and_return_print_method().
key_press_handler()
matplotlib.backend_bases.key_press_handler (event, canvas = None, toolbar = None)
Implement the default Matplotlib key bindings for the canvas and toolbar
described at :ref:`key-event-handling`.
Parameters
----------
event : `KeyEvent`
    A key press/release event.
canvas : `FigureCanvasBase`, default: ``event.canvas``
    The backend-specific canvas instance.  This parameter is kept for
    back-compatibility, but, if set, should always be equal to
    ``event.canvas``.
toolbar : `NavigationToolbar2`, default: ``event.canvas.toolbar``
    The navigation cursor toolbar.  This parameter is kept for
    back-compatibility, but, if set, should always be equal to
    ``event.canvas.toolbar``.
Definition at line 2378 of file backend_bases.py.
register_backend()
matplotlib.backend_bases.register_backend (format, backend, description = None)
Register a backend for saving to a given file format.
Parameters
----------
format : str
    File extension
backend : module string or canvas class
    Backend for handling file output
description : str, default: ""
    Description of the file type.
Definition at line 97 of file backend_bases.py.
Variable Documentation
_default_backends
dict matplotlib.backend_bases._default_backends protected
Initial value:
=  {
    'eps': 'matplotlib.backends.backend_ps',
    'jpg': 'matplotlib.backends.backend_agg',
    'jpeg': 'matplotlib.backends.backend_agg',
    'pdf': 'matplotlib.backends.backend_pdf',
    'pgf': 'matplotlib.backends.backend_pgf',
    'png': 'matplotlib.backends.backend_agg',
    'ps': 'matplotlib.backends.backend_ps',
    'raw': 'matplotlib.backends.backend_agg',
    'rgba': 'matplotlib.backends.backend_agg',
    'svg': 'matplotlib.backends.backend_svg',
    'svgz': 'matplotlib.backends.backend_svg',
    'tif': 'matplotlib.backends.backend_agg',
    'tiff': 'matplotlib.backends.backend_agg',
    'webp': 'matplotlib.backends.backend_agg',
}
Definition at line 79 of file backend_bases.py.
_default_filetypes
dict matplotlib.backend_bases._default_filetypes protected
Initial value:
=  {
    'eps': 'Encapsulated Postscript',
    'jpg': 'Joint Photographic Experts Group',
    'jpeg': 'Joint Photographic Experts Group',
    'pdf': 'Portable Document Format',
    'pgf': 'PGF code for LaTeX',
    'png': 'Portable Network Graphics',
    'ps': 'Postscript',
    'raw': 'Raw RGBA bitmap',
    'rgba': 'Raw RGBA bitmap',
    'svg': 'Scalable Vector Graphics',
    'svgz': 'Scalable Vector Graphics',
    'tif': 'Tagged Image File Format',
    'tiff': 'Tagged Image File Format',
    'webp': 'WebP Image Format',
}
Definition at line 63 of file backend_bases.py.
_log
matplotlib.backend_bases._log = logging.getLogger(__name__) protected
Definition at line 62 of file backend_bases.py.
cursors
matplotlib.backend_bases.cursors = tools.cursors
Definition at line 2751 of file backend_bases.py.