Code Cloning Analysis: scipy.linalg._decomp_lu Namespace Reference
scipy.linalg._decomp_lu Namespace Reference
Functions
lu_factor (a, overwrite_a=False, check_finite=True)
lu_solve (lu_and_piv, b, trans=0, overwrite_b=False, check_finite=True)
lu (a, permute_l=False, overwrite_a=False, check_finite=True, p_indices=False)
Variables
dict lapack_cast_dict
list __all__ = ['lu', 'lu_solve', 'lu_factor']
Detailed Description
LU decomposition functions.
Function Documentation
lu()
scipy.linalg._decomp_lu.lu (a, permute_l = False, overwrite_a = False, check_finite = True, p_indices = False)
Compute LU decomposition of a matrix with partial pivoting.
The decomposition satisfies::
    A = P @ L @ U
where ``P`` is a permutation matrix, ``L`` lower triangular with unit
diagonal elements, and ``U`` upper triangular. If `permute_l` is set to
``True`` then ``L`` is returned already permuted and hence satisfying
``A = L @ U``.
Parameters
----------
a : (M, N) array_like
    Array to decompose
permute_l : bool, optional
    Perform the multiplication P*L (Default: do not permute)
overwrite_a : bool, optional
    Whether to overwrite data in a (may improve performance)
check_finite : bool, optional
    Whether to check that the input matrix contains only finite numbers.
    Disabling may give a performance gain, but may result in problems
    (crashes, non-termination) if the inputs do contain infinities or NaNs.
p_indices : bool, optional
    If ``True`` the permutation information is returned as row indices.
    The default is ``False`` for backwards-compatibility reasons.
Returns
-------
**(If `permute_l` is ``False``)**
p : (..., M, M) ndarray
    Permutation arrays or vectors depending on `p_indices`
l : (..., M, K) ndarray
    Lower triangular or trapezoidal array with unit diagonal.
    ``K = min(M, N)``
u : (..., K, N) ndarray
    Upper triangular or trapezoidal array
**(If `permute_l` is ``True``)**
pl : (..., M, K) ndarray
    Permuted L matrix.
    ``K = min(M, N)``
u : (..., K, N) ndarray
    Upper triangular or trapezoidal array
Notes
-----
Permutation matrices are costly since they are nothing but row reorder of
``L`` and hence indices are strongly recommended to be used instead if the
permutation is required. The relation in the 2D case then becomes simply
``A = L[P, :] @ U``. In higher dimensions, it is better to use `permute_l`
to avoid complicated indexing tricks.
In 2D case, if one has the indices however, for some reason, the
permutation matrix is still needed then it can be constructed by
``np.eye(M)[P, :]``.
Examples
--------
>>> import numpy as np
>>> from scipy.linalg import lu
>>> A = np.array([[2, 5, 8, 7], [5, 2, 2, 8], [7, 5, 6, 6], [5, 4, 4, 8]])
>>> p, l, u = lu(A)
>>> np.allclose(A, p @ l @ u)
True
>>> p  # Permutation matrix
array([[0., 1., 0., 0.],  # Row index 1
       [0., 0., 0., 1.],  # Row index 3
       [1., 0., 0., 0.],  # Row index 0
       [0., 0., 1., 0.]]) # Row index 2
>>> p, _, _ = lu(A, p_indices=True)
>>> p
array([1, 3, 0, 2])  # as given by row indices above
>>> np.allclose(A, l[p, :] @ u)
True
We can also use nd-arrays, for example, a demonstration with 4D array:
>>> rng = np.random.default_rng()
>>> A = rng.uniform(low=-4, high=4, size=[3, 2, 4, 8])
>>> p, l, u = lu(A)
>>> p.shape, l.shape, u.shape
((3, 2, 4, 4), (3, 2, 4, 4), (3, 2, 4, 8))
>>> np.allclose(A, p @ l @ u)
True
>>> PL, U = lu(A, permute_l=True)
>>> np.allclose(A, PL @ U)
True
Definition at line 159 of file _decomp_lu.py.
References scipy.linalg._misc._datacopied().
Referenced by scipy.linalg._solvers.solve_continuous_are(), scipy.linalg._solvers.solve_discrete_are(), and scipy.linalg.tests.test_decomp_lu.TestLUFactor.test_medium1_complex().
lu_factor()
scipy.linalg._decomp_lu.lu_factor (a, overwrite_a = False, check_finite = True)
Compute pivoted LU decomposition of a matrix.
The decomposition is::
    A = P L U
where P is a permutation matrix, L lower triangular with unit
diagonal elements, and U upper triangular.
Parameters
----------
a : (M, N) array_like
    Matrix to decompose
overwrite_a : bool, optional
    Whether to overwrite data in A (may increase performance)
check_finite : bool, optional
    Whether to check that the input matrix contains only finite numbers.
    Disabling may give a performance gain, but may result in problems
    (crashes, non-termination) if the inputs do contain infinities or NaNs.
Returns
-------
lu : (M, N) ndarray
    Matrix containing U in its upper triangle, and L in its lower triangle.
    The unit diagonal elements of L are not stored.
piv : (N,) ndarray
    Pivot indices representing the permutation matrix P:
    row i of matrix was interchanged with row piv[i].
See Also
--------
lu : gives lu factorization in more user-friendly format
lu_solve : solve an equation system using the LU factorization of a matrix
Notes
-----
This is a wrapper to the ``*GETRF`` routines from LAPACK. Unlike
:func:`lu`, it outputs the L and U factors into a single array
and returns pivot indices instead of a permutation matrix.
Examples
--------
>>> import numpy as np
>>> from scipy.linalg import lu_factor
>>> A = np.array([[2, 5, 8, 7], [5, 2, 2, 8], [7, 5, 6, 6], [5, 4, 4, 8]])
>>> lu, piv = lu_factor(A)
>>> piv
array([2, 2, 3, 3], dtype=int32)
Convert LAPACK's ``piv`` array to NumPy index and test the permutation
>>> piv_py = [2, 0, 3, 1]
>>> L, U = np.tril(lu, k=-1) + np.eye(4), np.triu(lu)
>>> np.allclose(A[piv_py] - L @ U, np.zeros((4, 4)))
True
Definition at line 20 of file _decomp_lu.py.
References scipy.linalg._misc._datacopied(), and scipy.linalg.lapack.get_lapack_funcs().
Referenced by scipy.linalg.tests.test_decomp_lu.TestLUFactor.test_medium1_complex().
lu_solve()
scipy.linalg._decomp_lu.lu_solve (lu_and_piv, b, trans = 0, overwrite_b = False, check_finite = True)
Solve an equation system, a x = b, given the LU factorization of a
Parameters
----------
(lu, piv)
    Factorization of the coefficient matrix a, as given by lu_factor
b : array
    Right-hand side
trans : {0, 1, 2}, optional
    Type of system to solve:
    =====  =========
    trans  system
    =====  =========
    0      a x   = b
    1      a^T x = b
    2      a^H x = b
    =====  =========
overwrite_b : bool, optional
    Whether to overwrite data in b (may increase performance)
check_finite : bool, optional
    Whether to check that the input matrices contain only finite numbers.
    Disabling may give a performance gain, but may result in problems
    (crashes, non-termination) if the inputs do contain infinities or NaNs.
Returns
-------
x : array
    Solution to the system
See Also
--------
lu_factor : LU factorize a matrix
Examples
--------
>>> import numpy as np
>>> from scipy.linalg import lu_factor, lu_solve
>>> A = np.array([[2, 5, 8, 7], [5, 2, 2, 8], [7, 5, 6, 6], [5, 4, 4, 8]])
>>> b = np.array([1, 1, 1, 1])
>>> lu, piv = lu_factor(A)
>>> x = lu_solve((lu, piv), b)
>>> np.allclose(A @ x - b, np.zeros((4,)))
True
Definition at line 94 of file _decomp_lu.py.
References scipy.linalg._misc._datacopied(), and scipy.linalg.lapack.get_lapack_funcs().
Variable Documentation
__all__
list scipy.linalg._decomp_lu.__all__ = ['lu', 'lu_solve', 'lu_factor'] private
Definition at line 17 of file _decomp_lu.py.
lapack_cast_dict
dict scipy.linalg._decomp_lu.lapack_cast_dict
Initial value:
=  {x: ''.join([y for y in 'fdFD' if np.can_cast(x, y)])
                    for x in np.typecodes['All']}
Definition at line 14 of file _decomp_lu.py.