Code Cloning Analysis: pandas.util.version.InfinityType Class Reference
pandas.util.version.InfinityType Class Reference
Public Member Functions
str __repr__ (self)
int __hash__ (self)
bool __lt__ (self, object other)
bool __le__ (self, object other)
bool __eq__ (self, object other)
bool __ne__ (self, object other)
bool __gt__ (self, object other)
bool __ge__ (self, object other)
NegativeInfinityType __neg__ (object self)
Detailed Description
Definition at line 25 of file __init__.py.
Member Function Documentation
__eq__()
bool pandas.util.version.InfinityType.__eq__ (self, object other)
Definition at line 38 of file __init__.py.
Referenced by pip._vendor.msgpack.ext.Timestamp.__ne__(), and pip._vendor.distlib.version.Matcher.match().
__ge__()
bool pandas.util.version.InfinityType.__ge__ (self, object other)
Definition at line 47 of file __init__.py.
__gt__()
bool pandas.util.version.InfinityType.__gt__ (self, object other)
Definition at line 44 of file __init__.py.
__hash__()
int pandas.util.version.InfinityType.__hash__ (self)
Definition at line 29 of file __init__.py.
Referenced by pip._vendor.rich.style.Style.pick_first().
__le__()
bool pandas.util.version.InfinityType.__le__ (self, object other)
Definition at line 35 of file __init__.py.
__lt__()
bool pandas.util.version.InfinityType.__lt__ (self, object other)
Definition at line 32 of file __init__.py.
__ne__()
bool pandas.util.version.InfinityType.__ne__ (self, object other)
Definition at line 41 of file __init__.py.
__neg__()
NegativeInfinityType pandas.util.version.InfinityType.__neg__ (object self)
Definition at line 50 of file __init__.py.
__repr__()
str pandas.util.version.InfinityType.__repr__ (self)
Definition at line 26 of file __init__.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/util/version/__init__.py