Code Cloning Analysis: pip._vendor.chardet.sbcharsetprober.SingleByteCharSetProber Class Reference
pip._vendor.chardet.sbcharsetprober.SingleByteCharSetProber Class Reference
Public Member Functions
None __init__ (self, SingleByteCharSetModel model, bool is_reversed=False, Optional[CharSetProber] name_prober=None)
None reset (self)
Optional[str] charset_name (self)
Optional[str] language (self)
ProbingState feed (self, Union[bytes, bytearray] byte_str)
float get_confidence (self)
Public Member Functions inherited from pip._vendor.chardet.charsetprober.CharSetProber
None __init__ (self, LanguageFilter lang_filter=LanguageFilter.NONE)
ProbingState state (self)
Static Public Attributes
int SAMPLE_SIZE = 64
int SB_ENOUGH_REL_THRESHOLD = 1024
float POSITIVE_SHORTCUT_THRESHOLD = 0.95
float NEGATIVE_SHORTCUT_THRESHOLD = 0.05
Static Public Attributes inherited from pip._vendor.chardet.charsetprober.CharSetProber
float SHORTCUT_THRESHOLD = 0.95
Protected Attributes
_model = model
_reversed = is_reversed
_name_prober = name_prober
int _last_order = 255
list _seq_counters = []
int _total_seqs = 0
int _total_char = 0
int _control_char = 0
int _freq_char = 0
Protected Attributes inherited from pip._vendor.chardet.charsetprober.CharSetProber
_state = ProbingState.DETECTING
Additional Inherited Members
Static Public Member Functions inherited from pip._vendor.chardet.charsetprober.CharSetProber
bytes filter_high_byte_only (Union[bytes, bytearray] buf)
bytearray filter_international_words (Union[bytes, bytearray] buf)
bytes remove_xml_tags (Union[bytes, bytearray] buf)
Public Attributes inherited from pip._vendor.chardet.charsetprober.CharSetProber
bool active = True
lang_filter = lang_filter
logger = logging.getLogger(__name__)
Detailed Description
Definition at line 45 of file sbcharsetprober.py.
Constructor & Destructor Documentation
__init__()
None pip._vendor.chardet.sbcharsetprober.SingleByteCharSetProber.__init__ (self, SingleByteCharSetModel model, bool is_reversed = False, Optional[CharSetProber] name_prober = None)
Definition at line 51 of file sbcharsetprober.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
charset_name()
Optional[str] pip._vendor.chardet.sbcharsetprober.SingleByteCharSetProber.charset_name (self)
Reimplemented from pip._vendor.chardet.charsetprober.CharSetProber.
Definition at line 83 of file sbcharsetprober.py.
feed()
ProbingState pip._vendor.chardet.sbcharsetprober.SingleByteCharSetProber.feed (self, Union[bytes, bytearray] byte_str)
Reimplemented from pip._vendor.chardet.charsetprober.CharSetProber.
Definition at line 94 of file sbcharsetprober.py.
get_confidence()
float pip._vendor.chardet.sbcharsetprober.SingleByteCharSetProber.get_confidence (self)
Reimplemented from pip._vendor.chardet.charsetprober.CharSetProber.
Definition at line 144 of file sbcharsetprober.py.
language()
Optional[str] pip._vendor.chardet.sbcharsetprober.SingleByteCharSetProber.language (self)
Reimplemented from pip._vendor.chardet.charsetprober.CharSetProber.
Definition at line 89 of file sbcharsetprober.py.
reset()
None pip._vendor.chardet.sbcharsetprober.SingleByteCharSetProber.reset (self)
Reimplemented from pip._vendor.chardet.charsetprober.CharSetProber.
Definition at line 71 of file sbcharsetprober.py.
Referenced by scipy._lib._docscrape.Reader.__init__().
Member Data Documentation
_control_char
int pip._vendor.chardet.sbcharsetprober.SingleByteCharSetProber._control_char = 0 protected
Definition at line 67 of file sbcharsetprober.py.
_freq_char
int pip._vendor.chardet.sbcharsetprober.SingleByteCharSetProber._freq_char = 0 protected
Definition at line 68 of file sbcharsetprober.py.
_last_order
int pip._vendor.chardet.sbcharsetprober.SingleByteCharSetProber._last_order = 255 protected
Definition at line 63 of file sbcharsetprober.py.
_model
pip._vendor.chardet.sbcharsetprober.SingleByteCharSetProber._model = model protected
Definition at line 58 of file sbcharsetprober.py.
_name_prober
pip._vendor.chardet.sbcharsetprober.SingleByteCharSetProber._name_prober = name_prober protected
Definition at line 62 of file sbcharsetprober.py.
_reversed
pip._vendor.chardet.sbcharsetprober.SingleByteCharSetProber._reversed = is_reversed protected
Definition at line 60 of file sbcharsetprober.py.
_seq_counters
list pip._vendor.chardet.sbcharsetprober.SingleByteCharSetProber._seq_counters = [] protected
Definition at line 64 of file sbcharsetprober.py.
_total_char
int pip._vendor.chardet.sbcharsetprober.SingleByteCharSetProber._total_char = 0 protected
Definition at line 66 of file sbcharsetprober.py.
_total_seqs
int pip._vendor.chardet.sbcharsetprober.SingleByteCharSetProber._total_seqs = 0 protected
Definition at line 65 of file sbcharsetprober.py.
NEGATIVE_SHORTCUT_THRESHOLD
pip._vendor.chardet.sbcharsetprober.SingleByteCharSetProber.NEGATIVE_SHORTCUT_THRESHOLD = 0.05 static
Definition at line 49 of file sbcharsetprober.py.
POSITIVE_SHORTCUT_THRESHOLD
float pip._vendor.chardet.sbcharsetprober.SingleByteCharSetProber.POSITIVE_SHORTCUT_THRESHOLD = 0.95 static
Definition at line 48 of file sbcharsetprober.py.
SAMPLE_SIZE
int pip._vendor.chardet.sbcharsetprober.SingleByteCharSetProber.SAMPLE_SIZE = 64 static
Definition at line 46 of file sbcharsetprober.py.
SB_ENOUGH_REL_THRESHOLD
int pip._vendor.chardet.sbcharsetprober.SingleByteCharSetProber.SB_ENOUGH_REL_THRESHOLD = 1024 static
Definition at line 47 of file sbcharsetprober.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pip/_vendor/chardet/sbcharsetprober.py