Code Cloning Analysis: sklearn.datasets._samples_generator Namespace Reference
sklearn.datasets._samples_generator Namespace Reference
Functions
_generate_hypercube (samples, dimensions, rng)
make_classification (n_samples=100, n_features=20, *, n_informative=2, n_redundant=2, n_repeated=0, n_classes=2, n_clusters_per_class=2, weights=None, flip_y=0.01, class_sep=1.0, hypercube=True, shift=0.0, scale=1.0, shuffle=True, random_state=None, return_X_y=True)
make_multilabel_classification (n_samples=100, n_features=20, *, n_classes=5, n_labels=2, length=50, allow_unlabeled=True, sparse=False, return_indicator="dense", return_distributions=False, random_state=None)
make_hastie_10_2 (n_samples=12000, *, random_state=None)
make_regression (n_samples=100, n_features=100, *, n_informative=10, n_targets=1, bias=0.0, effective_rank=None, tail_strength=0.5, noise=0.0, shuffle=True, coef=False, random_state=None)
make_circles (n_samples=100, *, shuffle=True, noise=None, random_state=None, factor=0.8)
make_moons (n_samples=100, *, shuffle=True, noise=None, random_state=None)
make_blobs (n_samples=100, n_features=2, *, centers=None, cluster_std=1.0, center_box=(-10.0, 10.0), shuffle=True, random_state=None, return_centers=False)
make_friedman1 (n_samples=100, n_features=10, *, noise=0.0, random_state=None)
make_friedman2 (n_samples=100, *, noise=0.0, random_state=None)
make_friedman3 (n_samples=100, *, noise=0.0, random_state=None)
make_low_rank_matrix (n_samples=100, n_features=100, *, effective_rank=10, tail_strength=0.5, random_state=None)
make_sparse_coded_signal (n_samples, *, n_components, n_features, n_nonzero_coefs, random_state=None)
make_sparse_uncorrelated (n_samples=100, n_features=10, *, random_state=None)
make_spd_matrix (n_dim, *, random_state=None)
make_sparse_spd_matrix (n_dim=1, *, alpha=0.95, norm_diag=False, smallest_coef=0.1, largest_coef=0.9, sparse_format=None, random_state=None)
make_swiss_roll (n_samples=100, *, noise=0.0, random_state=None, hole=False)
make_s_curve (n_samples=100, *, noise=0.0, random_state=None)
make_gaussian_quantiles (*, mean=None, cov=1.0, n_samples=100, n_features=2, n_classes=3, shuffle=True, random_state=None)
_shuffle (data, random_state=None)
make_biclusters (shape, n_clusters, *, noise=0.0, minval=10, maxval=100, shuffle=True, random_state=None)
make_checkerboard (shape, n_clusters, *, noise=0.0, minval=10, maxval=100, shuffle=True, random_state=None)
Detailed Description
Generate samples of synthetic data sets.
Function Documentation
_generate_hypercube()
sklearn.datasets._samples_generator._generate_hypercube (samples, dimensions, rng) protected
Returns distinct binary samples of length dimensions.
Definition at line 26 of file _samples_generator.py.
References _generate_hypercube().
Referenced by _generate_hypercube(), and make_classification().
_shuffle()
sklearn.datasets._samples_generator._shuffle (data, random_state = None) protected
Definition at line 2113 of file _samples_generator.py.
make_biclusters()
sklearn.datasets._samples_generator.make_biclusters (shape, n_clusters, * , noise = 0.0, minval = 10, maxval = 100, shuffle = True, random_state = None)
Generate a constant block diagonal structure array for biclustering.
Read more in the :ref:`User Guide <sample_generators>`.
Parameters
----------
shape : tuple of shape (n_rows, n_cols)
    The shape of the result.
n_clusters : int
    The number of biclusters.
noise : float, default=0.0
    The standard deviation of the gaussian noise.
minval : float, default=10
    Minimum value of a bicluster.
maxval : float, default=100
    Maximum value of a bicluster.
shuffle : bool, default=True
    Shuffle the samples.
random_state : int, RandomState instance or None, default=None
    Determines random number generation for dataset creation. Pass an int
    for reproducible output across multiple function calls.
    See :term:`Glossary <random_state>`.
Returns
-------
X : ndarray of shape `shape`
    The generated array.
rows : ndarray of shape (n_clusters, X.shape[0])
    The indicators for cluster membership of each row.
cols : ndarray of shape (n_clusters, X.shape[1])
    The indicators for cluster membership of each column.
See Also
--------
make_checkerboard: Generate an array with block checkerboard structure for
    biclustering.
References
----------
.. [1] Dhillon, I. S. (2001, August). Co-clustering documents and
    words using bipartite spectral graph partitioning. In Proceedings
    of the seventh ACM SIGKDD international conference on Knowledge
    discovery and data mining (pp. 269-274). ACM.
Examples
--------
>>> from sklearn.datasets import make_biclusters
>>> data, rows, cols = make_biclusters(
...     shape=(10, 20), n_clusters=2, random_state=42
...)
>>> data.shape
(10, 20)
>>> rows.shape
(2, 10)
>>> cols.shape
(2, 20)
Definition at line 2134 of file _samples_generator.py.
make_blobs()
sklearn.datasets._samples_generator.make_blobs (n_samples = 100, n_features = 2, * , centers = None, cluster_std = 1.0, center_box = (-10.0, 10.0), shuffle = True, random_state = None, return_centers = False)
Generate isotropic Gaussian blobs for clustering.
Read more in the :ref:`User Guide <sample_generators>`.
Parameters
----------
n_samples : int or array-like, default=100
    If int, it is the total number of points equally divided among
    clusters.
    If array-like, each element of the sequence indicates
    the number of samples per cluster.
    .. versionchanged:: v0.20
        one can now pass an array-like to the ``n_samples`` parameter
n_features : int, default=2
    The number of features for each sample.
centers : int or array-like of shape (n_centers, n_features), default=None
    The number of centers to generate, or the fixed center locations.
    If n_samples is an int and centers is None, 3 centers are generated.
    If n_samples is array-like, centers must be
    either None or an array of length equal to the length of n_samples.
cluster_std : float or array-like of float, default=1.0
    The standard deviation of the clusters.
center_box : tuple of float (min, max), default=(-10.0, 10.0)
    The bounding box for each cluster center when centers are
    generated at random.
shuffle : bool, default=True
    Shuffle the samples.
random_state : int, RandomState instance or None, default=None
    Determines random number generation for dataset creation. Pass an int
    for reproducible output across multiple function calls.
    See :term:`Glossary <random_state>`.
return_centers : bool, default=False
    If True, then return the centers of each cluster.
    .. versionadded:: 0.23
Returns
-------
X : ndarray of shape (n_samples, n_features)
    The generated samples.
y : ndarray of shape (n_samples,)
    The integer labels for cluster membership of each sample.
centers : ndarray of shape (n_centers, n_features)
    The centers of each cluster. Only returned if
    ``return_centers=True``.
See Also
--------
make_classification : A more intricate variant.
Examples
--------
>>> from sklearn.datasets import make_blobs
>>> X, y = make_blobs(n_samples=10, centers=3, n_features=2,
...                   random_state=0)
>>> print(X.shape)
(10, 2)
>>> y
array([0, 0, 1, 0, 2, 2, 2, 1, 1, 0])
>>> X, y = make_blobs(n_samples=[3, 3, 4], centers=None, n_features=2,
...                   random_state=0)
>>> print(X.shape)
(10, 2)
>>> y
array([0, 1, 2, 0, 2, 2, 2, 1, 1, 0])
Definition at line 996 of file _samples_generator.py.
make_checkerboard()
sklearn.datasets._samples_generator.make_checkerboard (shape, n_clusters, * , noise = 0.0, minval = 10, maxval = 100, shuffle = True, random_state = None)
Generate an array with block checkerboard structure for biclustering.
Read more in the :ref:`User Guide <sample_generators>`.
Parameters
----------
shape : tuple of shape (n_rows, n_cols)
    The shape of the result.
n_clusters : int or array-like or shape (n_row_clusters, n_column_clusters)
    The number of row and column clusters.
noise : float, default=0.0
    The standard deviation of the gaussian noise.
minval : float, default=10
    Minimum value of a bicluster.
maxval : float, default=100
    Maximum value of a bicluster.
shuffle : bool, default=True
    Shuffle the samples.
random_state : int, RandomState instance or None, default=None
    Determines random number generation for dataset creation. Pass an int
    for reproducible output across multiple function calls.
    See :term:`Glossary <random_state>`.
Returns
-------
X : ndarray of shape `shape`
    The generated array.
rows : ndarray of shape (n_clusters, X.shape[0])
    The indicators for cluster membership of each row.
cols : ndarray of shape (n_clusters, X.shape[1])
    The indicators for cluster membership of each column.
See Also
--------
make_biclusters : Generate an array with constant block diagonal structure
    for biclustering.
References
----------
.. [1] Kluger, Y., Basri, R., Chang, J. T., & Gerstein, M. (2003).
    Spectral biclustering of microarray data: coclustering genes
    and conditions. Genome research, 13(4), 703-716.
Examples
--------
>>> from sklearn.datasets import make_checkerboard
>>> data, rows, columns = make_checkerboard(shape=(300, 300), n_clusters=10,
...                                         random_state=42)
>>> data.shape
(300, 300)
>>> rows.shape
(100, 300)
>>> columns.shape
(100, 300)
>>> print(rows[0][:5], columns[0][:5])
[False False False  True False] [False False False False False]
Definition at line 2256 of file _samples_generator.py.
make_circles()
sklearn.datasets._samples_generator.make_circles (n_samples = 100, * , shuffle = True, noise = None, random_state = None, factor = 0.8)
Make a large circle containing a smaller circle in 2d.
A simple toy dataset to visualize clustering and classification
algorithms.
Read more in the :ref:`User Guide <sample_generators>`.
Parameters
----------
n_samples : int or tuple of shape (2,), dtype=int, default=100
    If int, it is the total number of points generated.
    For odd numbers, the inner circle will have one point more than the
    outer circle.
    If two-element tuple, number of points in outer circle and inner
    circle.
    .. versionchanged:: 0.23
       Added two-element tuple.
shuffle : bool, default=True
    Whether to shuffle the samples.
noise : float, default=None
    Standard deviation of Gaussian noise added to the data.
random_state : int, RandomState instance or None, default=None
    Determines random number generation for dataset shuffling and noise.
    Pass an int for reproducible output across multiple function calls.
    See :term:`Glossary <random_state>`.
factor : float, default=.8
    Scale factor between inner and outer circle in the range `[0, 1)`.
Returns
-------
X : ndarray of shape (n_samples, 2)
    The generated samples.
y : ndarray of shape (n_samples,)
    The integer labels (0 or 1) for class membership of each sample.
Examples
--------
>>> from sklearn.datasets import make_circles
>>> X, y = make_circles(random_state=42)
>>> X.shape
(100, 2)
>>> y.shape
(100,)
>>> list(y[:5])
[np.int64(1), np.int64(1), np.int64(1), np.int64(0), np.int64(0)]
Definition at line 809 of file _samples_generator.py.
make_classification()
sklearn.datasets._samples_generator.make_classification (n_samples = 100, n_features = 20, * , n_informative = 2, n_redundant = 2, n_repeated = 0, n_classes = 2, n_clusters_per_class = 2, weights = None, flip_y = 0.01, class_sep = 1.0, hypercube = True, shift = 0.0, scale = 1.0, shuffle = True, random_state = None, return_X_y = True)
Generate a random n-class classification problem.
This initially creates clusters of points normally distributed (std=1)
about vertices of an ``n_informative``-dimensional hypercube with sides of
length ``2*class_sep`` and assigns an equal number of clusters to each
class. It introduces interdependence between these features and adds
various types of further noise to the data.
Without shuffling, ``X`` horizontally stacks features in the following
order: the primary ``n_informative`` features, followed by ``n_redundant``
linear combinations of the informative features, followed by ``n_repeated``
duplicates, drawn randomly with replacement from the informative and
redundant features. The remaining features are filled with random noise.
Thus, without shuffling, all useful features are contained in the columns
``X[:, :n_informative + n_redundant + n_repeated]``.
Read more in the :ref:`User Guide <sample_generators>`.
Parameters
----------
n_samples : int, default=100
    The number of samples.
n_features : int, default=20
    The total number of features. These comprise ``n_informative``
    informative features, ``n_redundant`` redundant features,
    ``n_repeated`` duplicated features and
    ``n_features-n_informative-n_redundant-n_repeated`` useless features
    drawn at random.
n_informative : int, default=2
    The number of informative features. Each class is composed of a number
    of gaussian clusters each located around the vertices of a hypercube
    in a subspace of dimension ``n_informative``. For each cluster,
    informative features are drawn independently from  N(0, 1) and then
    randomly linearly combined within each cluster in order to add
    covariance. The clusters are then placed on the vertices of the
    hypercube.
n_redundant : int, default=2
    The number of redundant features. These features are generated as
    random linear combinations of the informative features.
n_repeated : int, default=0
    The number of duplicated features, drawn randomly from the informative
    and the redundant features.
n_classes : int, default=2
    The number of classes (or labels) of the classification problem.
n_clusters_per_class : int, default=2
    The number of clusters per class.
weights : array-like of shape (n_classes,) or (n_classes - 1,),\
          default=None
    The proportions of samples assigned to each class. If None, then
    classes are balanced. Note that if ``len(weights) == n_classes - 1``,
    then the last class weight is automatically inferred.
    More than ``n_samples`` samples may be returned if the sum of
    ``weights`` exceeds 1. Note that the actual class proportions will
    not exactly match ``weights`` when ``flip_y`` isn't 0.
flip_y : float, default=0.01
    The fraction of samples whose class is assigned randomly. Larger
    values introduce noise in the labels and make the classification
    task harder. Note that the default setting flip_y > 0 might lead
    to less than ``n_classes`` in y in some cases.
class_sep : float, default=1.0
    The factor multiplying the hypercube size.  Larger values spread
    out the clusters/classes and make the classification task easier.
hypercube : bool, default=True
    If True, the clusters are put on the vertices of a hypercube. If
    False, the clusters are put on the vertices of a random polytope.
shift : float, ndarray of shape (n_features,) or None, default=0.0
    Shift features by the specified value. If None, then features
    are shifted by a random value drawn in [-class_sep, class_sep].
scale : float, ndarray of shape (n_features,) or None, default=1.0
    Multiply features by the specified value. If None, then features
    are scaled by a random value drawn in [1, 100]. Note that scaling
    happens after shifting.
shuffle : bool, default=True
    Shuffle the samples and the features.
random_state : int, RandomState instance or None, default=None
    Determines random number generation for dataset creation. Pass an int
    for reproducible output across multiple function calls.
    See :term:`Glossary <random_state>`.
return_X_y : bool, default=True
    If True, a tuple ``(X, y)`` instead of a Bunch object is returned.
    .. versionadded:: 1.7
Returns
-------
data : :class:`~sklearn.utils.Bunch` if `return_X_y` is `False`.
    Dictionary-like object, with the following attributes.
    DESCR : str
        A description of the function that generated the dataset.
    parameter : dict
        A dictionary that stores the values of the arguments passed to the
        generator function.
    feature_info : list of len(n_features)
        A description for each generated feature.
    X : ndarray of shape (n_samples, n_features)
        The generated samples.
    y : ndarray of shape (n_samples,)
        An integer label for class membership of each sample.
    .. versionadded:: 1.7
(X, y) : tuple if ``return_X_y`` is True
    A tuple of generated samples and labels.
See Also
--------
make_blobs : Simplified variant.
make_multilabel_classification : Unrelated generator for multilabel tasks.
Notes
-----
The algorithm is adapted from Guyon [1] and was designed to generate
the "Madelon" dataset.
References
----------
.. [1] I. Guyon, "Design of experiments for the NIPS 2003 variable
       selection benchmark", 2003.
Examples
--------
>>> from sklearn.datasets import make_classification
>>> X, y = make_classification(random_state=42)
>>> X.shape
(100, 20)
>>> y.shape
(100,)
>>> list(y[:5])
[np.int64(0), np.int64(0), np.int64(1), np.int64(1), np.int64(0)]
Definition at line 63 of file _samples_generator.py.
References _generate_hypercube().
make_friedman1()
sklearn.datasets._samples_generator.make_friedman1 (n_samples = 100, n_features = 10, * , noise = 0.0, random_state = None)
Generate the "Friedman #1" regression problem.
This dataset is described in Friedman [1] and Breiman [2].
Inputs `X` are independent features uniformly distributed on the interval
[0, 1]. The output `y` is created according to the formula::
    y(X) = 10 * sin(pi * X[:, 0] * X[:, 1]) + 20 * (X[:, 2] - 0.5) ** 2 \
+ 10 * X[:, 3] + 5 * X[:, 4] + noise * N(0, 1).
Out of the `n_features` features, only 5 are actually used to compute
`y`. The remaining features are independent of `y`.
The number of features has to be >= 5.
Read more in the :ref:`User Guide <sample_generators>`.
Parameters
----------
n_samples : int, default=100
    The number of samples.
n_features : int, default=10
    The number of features. Should be at least 5.
noise : float, default=0.0
    The standard deviation of the gaussian noise applied to the output.
random_state : int, RandomState instance or None, default=None
    Determines random number generation for dataset noise. Pass an int
    for reproducible output across multiple function calls.
    See :term:`Glossary <random_state>`.
Returns
-------
X : ndarray of shape (n_samples, n_features)
    The input samples.
y : ndarray of shape (n_samples,)
    The output values.
References
----------
.. [1] J. Friedman, "Multivariate adaptive regression splines", The Annals
       of Statistics 19 (1), pages 1-67, 1991.
.. [2] L. Breiman, "Bagging predictors", Machine Learning 24,
       pages 123-140, 1996.
Examples
--------
>>> from sklearn.datasets import make_friedman1
>>> X, y = make_friedman1(random_state=42)
>>> X.shape
(100, 10)
>>> y.shape
(100,)
>>> list(y[:3])
[np.float64(16.8), np.float64(5.87), np.float64(9.46)]
Definition at line 1172 of file _samples_generator.py.
make_friedman2()
sklearn.datasets._samples_generator.make_friedman2 (n_samples = 100, * , noise = 0.0, random_state = None)
Generate the "Friedman #2" regression problem.
This dataset is described in Friedman [1] and Breiman [2].
Inputs `X` are 4 independent features uniformly distributed on the
intervals::
    0 <= X[:, 0] <= 100,
    40 * pi <= X[:, 1] <= 560 * pi,
    0 <= X[:, 2] <= 1,
    1 <= X[:, 3] <= 11.
The output `y` is created according to the formula::
    y(X) = (X[:, 0] ** 2 + (X[:, 1] * X[:, 2] \
- 1 / (X[:, 1] * X[:, 3])) ** 2) ** 0.5 + noise * N(0, 1).
Read more in the :ref:`User Guide <sample_generators>`.
Parameters
----------
n_samples : int, default=100
    The number of samples.
noise : float, default=0.0
    The standard deviation of the gaussian noise applied to the output.
random_state : int, RandomState instance or None, default=None
    Determines random number generation for dataset noise. Pass an int
    for reproducible output across multiple function calls.
    See :term:`Glossary <random_state>`.
Returns
-------
X : ndarray of shape (n_samples, 4)
    The input samples.
y : ndarray of shape (n_samples,)
    The output values.
References
----------
.. [1] J. Friedman, "Multivariate adaptive regression splines", The Annals
       of Statistics 19 (1), pages 1-67, 1991.
.. [2] L. Breiman, "Bagging predictors", Machine Learning 24,
       pages 123-140, 1996.
Examples
--------
>>> from sklearn.datasets import make_friedman2
>>> X, y = make_friedman2(random_state=42)
>>> X.shape
(100, 4)
>>> y.shape
(100,)
>>> list(y[:3])
[np.float64(1229.4), np.float64(27.0), np.float64(65.6)]
Definition at line 1255 of file _samples_generator.py.
make_friedman3()
sklearn.datasets._samples_generator.make_friedman3 (n_samples = 100, * , noise = 0.0, random_state = None)
Generate the "Friedman #3" regression problem.
This dataset is described in Friedman [1] and Breiman [2].
Inputs `X` are 4 independent features uniformly distributed on the
intervals::
    0 <= X[:, 0] <= 100,
    40 * pi <= X[:, 1] <= 560 * pi,
    0 <= X[:, 2] <= 1,
    1 <= X[:, 3] <= 11.
The output `y` is created according to the formula::
    y(X) = arctan((X[:, 1] * X[:, 2] - 1 / (X[:, 1] * X[:, 3])) \
/ X[:, 0]) + noise * N(0, 1).
Read more in the :ref:`User Guide <sample_generators>`.
Parameters
----------
n_samples : int, default=100
    The number of samples.
noise : float, default=0.0
    The standard deviation of the gaussian noise applied to the output.
random_state : int, RandomState instance or None, default=None
    Determines random number generation for dataset noise. Pass an int
    for reproducible output across multiple function calls.
    See :term:`Glossary <random_state>`.
Returns
-------
X : ndarray of shape (n_samples, 4)
    The input samples.
y : ndarray of shape (n_samples,)
    The output values.
References
----------
.. [1] J. Friedman, "Multivariate adaptive regression splines", The Annals
       of Statistics 19 (1), pages 1-67, 1991.
.. [2] L. Breiman, "Bagging predictors", Machine Learning 24,
       pages 123-140, 1996.
Examples
--------
>>> from sklearn.datasets import make_friedman3
>>> X, y = make_friedman3(random_state=42)
>>> X.shape
(100, 4)
>>> y.shape
(100,)
>>> list(y[:3])
[np.float64(1.54), np.float64(0.956), np.float64(0.414)]
Definition at line 1339 of file _samples_generator.py.
make_gaussian_quantiles()
sklearn.datasets._samples_generator.make_gaussian_quantiles (* , mean = None, cov = 1.0, n_samples = 100, n_features = 2, n_classes = 3, shuffle = True, random_state = None)
Generate isotropic Gaussian and label samples by quantile.
This classification dataset is constructed by taking a multi-dimensional
standard normal distribution and defining classes separated by nested
concentric multi-dimensional spheres such that roughly equal numbers of
samples are in each class (quantiles of the :math:`\chi^2` distribution).
Read more in the :ref:`User Guide <sample_generators>`.
Parameters
----------
mean : array-like of shape (n_features,), default=None
    The mean of the multi-dimensional normal distribution.
    If None then use the origin (0, 0, ...).
cov : float, default=1.0
    The covariance matrix will be this value times the unit matrix. This
    dataset only produces symmetric normal distributions.
n_samples : int, default=100
    The total number of points equally divided among classes.
n_features : int, default=2
    The number of features for each sample.
n_classes : int, default=3
    The number of classes.
shuffle : bool, default=True
    Shuffle the samples.
random_state : int, RandomState instance or None, default=None
    Determines random number generation for dataset creation. Pass an int
    for reproducible output across multiple function calls.
    See :term:`Glossary <random_state>`.
Returns
-------
X : ndarray of shape (n_samples, n_features)
    The generated samples.
y : ndarray of shape (n_samples,)
    The integer labels for quantile membership of each sample.
Notes
-----
The dataset is from Zhu et al [1].
References
----------
.. [1] J. Zhu, H. Zou, S. Rosset, T. Hastie, "Multi-class AdaBoost", 2009.
Examples
--------
>>> from sklearn.datasets import make_gaussian_quantiles
>>> X, y = make_gaussian_quantiles(random_state=42)
>>> X.shape
(100, 2)
>>> y.shape
(100,)
>>> list(y[:5])
[np.int64(2), np.int64(0), np.int64(1), np.int64(0), np.int64(2)]
Definition at line 2007 of file _samples_generator.py.
make_hastie_10_2()
sklearn.datasets._samples_generator.make_hastie_10_2 (n_samples = 12000, * , random_state = None)
Generate data for binary classification used in Hastie et al. 2009, Example 10.2.
The ten features are standard independent Gaussian and
the target ``y`` is defined by::
  y[i] = 1 if np.sum(X[i] ** 2) > 9.34 else -1
Read more in the :ref:`User Guide <sample_generators>`.
Parameters
----------
n_samples : int, default=12000
    The number of samples.
random_state : int, RandomState instance or None, default=None
    Determines random number generation for dataset creation. Pass an int
    for reproducible output across multiple function calls.
    See :term:`Glossary <random_state>`.
Returns
-------
X : ndarray of shape (n_samples, 10)
    The input samples.
y : ndarray of shape (n_samples,)
    The output values.
See Also
--------
make_gaussian_quantiles : A generalization of this dataset approach.
References
----------
.. [1] T. Hastie, R. Tibshirani and J. Friedman, "Elements of Statistical
       Learning Ed. 2", Springer, 2009.
Examples
--------
>>> from sklearn.datasets import make_hastie_10_2
>>> X, y = make_hastie_10_2(n_samples=24000, random_state=42)
>>> X.shape
(24000, 10)
>>> y.shape
(24000,)
>>> list(y[:5])
[np.float64(-1.0), np.float64(1.0), np.float64(-1.0), np.float64(1.0),
np.float64(-1.0)]
Definition at line 575 of file _samples_generator.py.
make_low_rank_matrix()
sklearn.datasets._samples_generator.make_low_rank_matrix (n_samples = 100, n_features = 100, * , effective_rank = 10, tail_strength = 0.5, random_state = None)
Generate a mostly low rank matrix with bell-shaped singular values.
Most of the variance can be explained by a bell-shaped curve of width
effective_rank: the low rank part of the singular values profile is::
    (1 - tail_strength) * exp(-1.0 * (i / effective_rank) ** 2)
The remaining singular values' tail is fat, decreasing as::
    tail_strength * exp(-0.1 * i / effective_rank).
The low rank part of the profile can be considered the structured
signal part of the data while the tail can be considered the noisy
part of the data that cannot be summarized by a low number of linear
components (singular vectors).
This kind of singular profiles is often seen in practice, for instance:
 - gray level pictures of faces
 - TF-IDF vectors of text documents crawled from the web
Read more in the :ref:`User Guide <sample_generators>`.
Parameters
----------
n_samples : int, default=100
    The number of samples.
n_features : int, default=100
    The number of features.
effective_rank : int, default=10
    The approximate number of singular vectors required to explain most of
    the data by linear combinations.
tail_strength : float, default=0.5
    The relative importance of the fat noisy tail of the singular values
    profile. The value should be between 0 and 1.
random_state : int, RandomState instance or None, default=None
    Determines random number generation for dataset creation. Pass an int
    for reproducible output across multiple function calls.
    See :term:`Glossary <random_state>`.
Returns
-------
X : ndarray of shape (n_samples, n_features)
    The matrix.
Examples
--------
>>> from numpy.linalg import svd
>>> from sklearn.datasets import make_low_rank_matrix
>>> X = make_low_rank_matrix(
...     n_samples=50,
...     n_features=25,
...     effective_rank=5,
...     tail_strength=0.01,
...     random_state=0,
...)
>>> X.shape
(50, 25)
Definition at line 1425 of file _samples_generator.py.
Referenced by make_regression().
make_moons()
sklearn.datasets._samples_generator.make_moons (n_samples = 100, * , shuffle = True, noise = None, random_state = None)
Make two interleaving half circles.
A simple toy dataset to visualize clustering and classification
algorithms. Read more in the :ref:`User Guide <sample_generators>`.
Parameters
----------
n_samples : int or tuple of shape (2,), dtype=int, default=100
    If int, the total number of points generated.
    If two-element tuple, number of points in each of two moons.
    .. versionchanged:: 0.23
       Added two-element tuple.
shuffle : bool, default=True
    Whether to shuffle the samples.
noise : float, default=None
    Standard deviation of Gaussian noise added to the data.
random_state : int, RandomState instance or None, default=None
    Determines random number generation for dataset shuffling and noise.
    Pass an int for reproducible output across multiple function calls.
    See :term:`Glossary <random_state>`.
Returns
-------
X : ndarray of shape (n_samples, 2)
    The generated samples.
y : ndarray of shape (n_samples,)
    The integer labels (0 or 1) for class membership of each sample.
Examples
--------
>>> from sklearn.datasets import make_moons
>>> X, y = make_moons(n_samples=200, noise=0.2, random_state=42)
>>> X.shape
(200, 2)
>>> y.shape
(200,)
Definition at line 905 of file _samples_generator.py.
make_multilabel_classification()
sklearn.datasets._samples_generator.make_multilabel_classification (n_samples = 100, n_features = 20, * , n_classes = 5, n_labels = 2, length = 50, allow_unlabeled = True, sparse = False, return_indicator = "dense", return_distributions = False, random_state = None)
Generate a random multilabel classification problem.
For each sample, the generative process is:
    - pick the number of labels: n ~ Poisson(n_labels)
    - n times, choose a class c: c ~ Multinomial(theta)
    - pick the document length: k ~ Poisson(length)
    - k times, choose a word: w ~ Multinomial(theta_c)
In the above process, rejection sampling is used to make sure that
n is never zero or more than `n_classes`, and that the document length
is never zero. Likewise, we reject classes which have already been chosen.
For an example of usage, see
:ref:`sphx_glr_auto_examples_datasets_plot_random_multilabel_dataset.py`.
Read more in the :ref:`User Guide <sample_generators>`.
Parameters
----------
n_samples : int, default=100
    The number of samples.
n_features : int, default=20
    The total number of features.
n_classes : int, default=5
    The number of classes of the classification problem.
n_labels : int, default=2
    The average number of labels per instance. More precisely, the number
    of labels per sample is drawn from a Poisson distribution with
    ``n_labels`` as its expected value, but samples are bounded (using
    rejection sampling) by ``n_classes``, and must be nonzero if
    ``allow_unlabeled`` is False.
length : int, default=50
    The sum of the features (number of words if documents) is drawn from
    a Poisson distribution with this expected value.
allow_unlabeled : bool, default=True
    If ``True``, some instances might not belong to any class.
sparse : bool, default=False
    If ``True``, return a sparse feature matrix.
    .. versionadded:: 0.17
       parameter to allow *sparse* output.
return_indicator : {'dense', 'sparse'} or False, default='dense'
    If ``'dense'`` return ``Y`` in the dense binary indicator format. If
    ``'sparse'`` return ``Y`` in the sparse binary indicator format.
    ``False`` returns a list of lists of labels.
return_distributions : bool, default=False
    If ``True``, return the prior class probability and conditional
    probabilities of features given classes, from which the data was
    drawn.
random_state : int, RandomState instance or None, default=None
    Determines random number generation for dataset creation. Pass an int
    for reproducible output across multiple function calls.
    See :term:`Glossary <random_state>`.
Returns
-------
X : ndarray of shape (n_samples, n_features)
    The generated samples.
Y : {ndarray, sparse matrix} of shape (n_samples, n_classes)
    The label sets. Sparse matrix should be of CSR format.
p_c : ndarray of shape (n_classes,)
    The probability of each class being drawn. Only returned if
    ``return_distributions=True``.
p_w_c : ndarray of shape (n_features, n_classes)
    The probability of each feature being drawn given each class.
    Only returned if ``return_distributions=True``.
Examples
--------
>>> from sklearn.datasets import make_multilabel_classification
>>> X, y = make_multilabel_classification(n_labels=3, random_state=42)
>>> X.shape
(100, 20)
>>> y.shape
(100, 5)
>>> list(y[:3])
[array([1, 1, 0, 1, 0]), array([0, 1, 1, 1, 0]), array([0, 1, 0, 0, 0])]
Definition at line 401 of file _samples_generator.py.
make_regression()
sklearn.datasets._samples_generator.make_regression (n_samples = 100, n_features = 100, * , n_informative = 10, n_targets = 1, bias = 0.0, effective_rank = None, tail_strength = 0.5, noise = 0.0, shuffle = True, coef = False, random_state = None)
Generate a random regression problem.
The input set can either be well conditioned (by default) or have a low
rank-fat tail singular profile. See :func:`make_low_rank_matrix` for
more details.
The output is generated by applying a (potentially biased) random linear
regression model with `n_informative` nonzero regressors to the previously
generated input and some gaussian centered noise with some adjustable
scale.
Read more in the :ref:`User Guide <sample_generators>`.
Parameters
----------
n_samples : int, default=100
    The number of samples.
n_features : int, default=100
    The number of features.
n_informative : int, default=10
    The number of informative features, i.e., the number of features used
    to build the linear model used to generate the output.
n_targets : int, default=1
    The number of regression targets, i.e., the dimension of the y output
    vector associated with a sample. By default, the output is a scalar.
bias : float, default=0.0
    The bias term in the underlying linear model.
effective_rank : int, default=None
    If not None:
        The approximate number of singular vectors required to explain most
        of the input data by linear combinations. Using this kind of
        singular spectrum in the input allows the generator to reproduce
        the correlations often observed in practice.
    If None:
        The input set is well conditioned, centered and gaussian with
        unit variance.
tail_strength : float, default=0.5
    The relative importance of the fat noisy tail of the singular values
    profile if `effective_rank` is not None. When a float, it should be
    between 0 and 1.
noise : float, default=0.0
    The standard deviation of the gaussian noise applied to the output.
shuffle : bool, default=True
    Shuffle the samples and the features.
coef : bool, default=False
    If True, the coefficients of the underlying linear model are returned.
random_state : int, RandomState instance or None, default=None
    Determines random number generation for dataset creation. Pass an int
    for reproducible output across multiple function calls.
    See :term:`Glossary <random_state>`.
Returns
-------
X : ndarray of shape (n_samples, n_features)
    The input samples.
y : ndarray of shape (n_samples,) or (n_samples, n_targets)
    The output values.
coef : ndarray of shape (n_features,) or (n_features, n_targets)
    The coefficient of the underlying linear model. It is returned only if
    coef is True.
Examples
--------
>>> from sklearn.datasets import make_regression
>>> X, y = make_regression(n_samples=5, n_features=2, noise=1, random_state=42)
>>> X
array([[ 0.4967, -0.1382 ],
    [ 0.6476,  1.523],
    [-0.2341, -0.2341],
    [-0.4694,  0.5425],
    [ 1.579,  0.7674]])
>>> y
array([  6.737,  37.79, -10.27,   0.4017,   42.22])
Definition at line 650 of file _samples_generator.py.
References make_low_rank_matrix().
make_s_curve()
sklearn.datasets._samples_generator.make_s_curve (n_samples = 100, * , noise = 0.0, random_state = None)
Generate an S curve dataset.
Read more in the :ref:`User Guide <sample_generators>`.
Parameters
----------
n_samples : int, default=100
    The number of sample points on the S curve.
noise : float, default=0.0
    The standard deviation of the gaussian noise.
random_state : int, RandomState instance or None, default=None
    Determines random number generation for dataset creation. Pass an int
    for reproducible output across multiple function calls.
    See :term:`Glossary <random_state>`.
Returns
-------
X : ndarray of shape (n_samples, 3)
    The points.
t : ndarray of shape (n_samples,)
    The univariate position of the sample according
    to the main dimension of the points in the manifold.
Examples
--------
>>> from sklearn.datasets import make_s_curve
>>> X, t = make_s_curve(noise=0.05, random_state=0)
>>> X.shape
(100, 3)
>>> t.shape
(100,)
Definition at line 1946 of file _samples_generator.py.
make_sparse_coded_signal()
sklearn.datasets._samples_generator.make_sparse_coded_signal (n_samples, * , n_components, n_features, n_nonzero_coefs, random_state = None)
Generate a signal as a sparse combination of dictionary elements.
Returns matrices `Y`, `D` and `X` such that `Y = XD` where `X` is of shape
`(n_samples, n_components)`, `D` is of shape `(n_components, n_features)`, and
each row of `X` has exactly `n_nonzero_coefs` non-zero elements.
Read more in the :ref:`User Guide <sample_generators>`.
Parameters
----------
n_samples : int
    Number of samples to generate.
n_components : int
    Number of components in the dictionary.
n_features : int
    Number of features of the dataset to generate.
n_nonzero_coefs : int
    Number of active (non-zero) coefficients in each sample.
random_state : int, RandomState instance or None, default=None
    Determines random number generation for dataset creation. Pass an int
    for reproducible output across multiple function calls.
    See :term:`Glossary <random_state>`.
Returns
-------
data : ndarray of shape (n_samples, n_features)
    The encoded signal (Y).
dictionary : ndarray of shape (n_components, n_features)
    The dictionary with normalized components (D).
code : ndarray of shape (n_samples, n_components)
    The sparse code such that each column of this matrix has exactly
    n_nonzero_coefs non-zero items (X).
Examples
--------
>>> from sklearn.datasets import make_sparse_coded_signal
>>> data, dictionary, code = make_sparse_coded_signal(
...     n_samples=50,
...     n_components=100,
...     n_features=10,
...     n_nonzero_coefs=4,
...     random_state=0
...)
>>> data.shape
(50, 10)
>>> dictionary.shape
(100, 10)
>>> code.shape
(50, 100)
Definition at line 1531 of file _samples_generator.py.
make_sparse_spd_matrix()
sklearn.datasets._samples_generator.make_sparse_spd_matrix (n_dim = 1, * , alpha = 0.95, norm_diag = False, smallest_coef = 0.1, largest_coef = 0.9, sparse_format = None, random_state = None)
Generate a sparse symmetric definite positive matrix.
Read more in the :ref:`User Guide <sample_generators>`.
Parameters
----------
n_dim : int, default=1
    The size of the random matrix to generate.
    .. versionchanged:: 1.4
        Renamed from ``dim`` to ``n_dim``.
alpha : float, default=0.95
    The probability that a coefficient is zero (see notes). Larger values
    enforce more sparsity. The value should be in the range 0 and 1.
norm_diag : bool, default=False
    Whether to normalize the output matrix to make the leading diagonal
    elements all 1.
smallest_coef : float, default=0.1
    The value of the smallest coefficient between 0 and 1.
largest_coef : float, default=0.9
    The value of the largest coefficient between 0 and 1.
sparse_format : str, default=None
    String representing the output sparse format, such as 'csc', 'csr', etc.
    If ``None``, return a dense numpy ndarray.
    .. versionadded:: 1.4
random_state : int, RandomState instance or None, default=None
    Determines random number generation for dataset creation. Pass an int
    for reproducible output across multiple function calls.
    See :term:`Glossary <random_state>`.
Returns
-------
prec : ndarray or sparse matrix of shape (dim, dim)
    The generated matrix. If ``sparse_format=None``, this would be an ndarray.
    Otherwise, this will be a sparse matrix of the specified format.
See Also
--------
make_spd_matrix : Generate a random symmetric, positive-definite matrix.
Notes
-----
The sparsity is actually imposed on the cholesky factor of the matrix.
Thus alpha does not translate directly into the filling fraction of
the matrix itself.
Examples
--------
>>> from sklearn.datasets import make_sparse_spd_matrix
>>> make_sparse_spd_matrix(n_dim=4, norm_diag=False, random_state=42)
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])
Definition at line 1748 of file _samples_generator.py.
make_sparse_uncorrelated()
sklearn.datasets._samples_generator.make_sparse_uncorrelated (n_samples = 100, n_features = 10, * , random_state = None)
Generate a random regression problem with sparse uncorrelated design.
This dataset is described in Celeux et al [1]. as::
    X ~ N(0, 1)
    y(X) = X[:, 0] + 2 * X[:, 1] - 2 * X[:, 2] - 1.5 * X[:, 3]
Only the first 4 features are informative. The remaining features are
useless.
Read more in the :ref:`User Guide <sample_generators>`.
Parameters
----------
n_samples : int, default=100
    The number of samples.
n_features : int, default=10
    The number of features.
random_state : int, RandomState instance or None, default=None
    Determines random number generation for dataset creation. Pass an int
    for reproducible output across multiple function calls.
    See :term:`Glossary <random_state>`.
Returns
-------
X : ndarray of shape (n_samples, n_features)
    The input samples.
y : ndarray of shape (n_samples,)
    The output values.
References
----------
.. [1] G. Celeux, M. El Anbari, J.-M. Marin, C. P. Robert,
       "Regularization in regression: comparing Bayesian and frequentist
       methods in a poorly informative situation", 2009.
Examples
--------
>>> from sklearn.datasets import make_sparse_uncorrelated
>>> X, y = make_sparse_uncorrelated(random_state=0)
>>> X.shape
(100, 10)
>>> y.shape
(100,)
Definition at line 1626 of file _samples_generator.py.
make_spd_matrix()
sklearn.datasets._samples_generator.make_spd_matrix (n_dim, * , random_state = None)
Generate a random symmetric, positive-definite matrix.
Read more in the :ref:`User Guide <sample_generators>`.
Parameters
----------
n_dim : int
    The matrix dimension.
random_state : int, RandomState instance or None, default=None
    Determines random number generation for dataset creation. Pass an int
    for reproducible output across multiple function calls.
    See :term:`Glossary <random_state>`.
Returns
-------
X : ndarray of shape (n_dim, n_dim)
    The random symmetric, positive-definite matrix.
See Also
--------
make_sparse_spd_matrix: Generate a sparse symmetric definite positive matrix.
Examples
--------
>>> from sklearn.datasets import make_spd_matrix
>>> make_spd_matrix(n_dim=2, random_state=42)
array([[2.093, 0.346],
       [0.346, 0.218]])
Definition at line 1693 of file _samples_generator.py.
make_swiss_roll()
sklearn.datasets._samples_generator.make_swiss_roll (n_samples = 100, * , noise = 0.0, random_state = None, hole = False)
Generate a swiss roll dataset.
Read more in the :ref:`User Guide <sample_generators>`.
Adapted with permission from Stephen Marsland's code [1].
Parameters
----------
n_samples : int, default=100
    The number of sample points on the Swiss Roll.
noise : float, default=0.0
    The standard deviation of the gaussian noise.
random_state : int, RandomState instance or None, default=None
    Determines random number generation for dataset creation. Pass an int
    for reproducible output across multiple function calls.
    See :term:`Glossary <random_state>`.
hole : bool, default=False
    If True generates the swiss roll with hole dataset.
Returns
-------
X : ndarray of shape (n_samples, 3)
    The points.
t : ndarray of shape (n_samples,)
    The univariate position of the sample according to the main dimension
    of the points in the manifold.
Notes
-----
The algorithm is from Marsland [1].
References
----------
.. [1] S. Marsland, "Machine Learning: An Algorithmic Perspective", 2nd edition,
       Chapter 6, 2014.
       https://homepages.ecs.vuw.ac.nz/~marslast/Code/Ch6/lle.py
Examples
--------
>>> from sklearn.datasets import make_swiss_roll
>>> X, t = make_swiss_roll(noise=0.05, random_state=0)
>>> X.shape
(100, 3)
>>> t.shape
(100,)
Definition at line 1862 of file _samples_generator.py.