Code Cloning Analysis: fontTools.cffLib.transforms._MarkingT2Decompiler Class Reference
fontTools.cffLib.transforms._MarkingT2Decompiler Class Reference
Public Member Functions
__init__ (self, localSubrs, globalSubrs, private)
op_callsubr (self, index)
op_callgsubr (self, index)
Public Member Functions inherited from fontTools.misc.psCharStrings.SimpleT2Decompiler
__init__ (self, localSubrs, globalSubrs, private=None, blender=None)
reset (self)
execute (self, charString)
pop (self)
popall (self)
push (self, value)
op_return (self, index)
op_endchar (self, index)
op_ignore (self, index)
op_hstem (self, index)
op_vstem (self, index)
op_hstemhm (self, index)
op_vstemhm (self, index)
op_hintmask (self, index)
countHints (self)
op_and (self, index)
op_or (self, index)
op_not (self, index)
op_store (self, index)
op_abs (self, index)
op_add (self, index)
op_sub (self, index)
op_div (self, index)
op_load (self, index)
op_neg (self, index)
op_eq (self, index)
op_drop (self, index)
op_put (self, index)
op_get (self, index)
op_ifelse (self, index)
op_random (self, index)
op_mul (self, index)
op_sqrt (self, index)
op_dup (self, index)
op_exch (self, index)
op_index (self, index)
op_roll (self, index)
op_blend (self, index)
op_vsindex (self, index)
Additional Inherited Members
Public Attributes inherited from fontTools.misc.psCharStrings.SimpleT2Decompiler
localSubrs = localSubrs
localBias = calcSubrBias(localSubrs)
globalSubrs = globalSubrs
globalBias = calcSubrBias(globalSubrs)
private = private
blender = blender
list callingStack = []
list operandStack = []
int hintCount = 0
int hintMaskBytes = 0
int numRegions = 0
int vsIndex = 0
Static Public Attributes inherited from fontTools.misc.psCharStrings.SimpleT2Decompiler
op_cntrmask = op_hintmask
Detailed Description
Definition at line 126 of file transforms.py.
Constructor & Destructor Documentation
__init__()
fontTools.cffLib.transforms._MarkingT2Decompiler.__init__ (self, localSubrs, globalSubrs, private)
Definition at line 127 of file transforms.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
op_callgsubr()
fontTools.cffLib.transforms._MarkingT2Decompiler.op_callgsubr (self, index)
Reimplemented from fontTools.misc.psCharStrings.SimpleT2Decompiler.
Definition at line 137 of file transforms.py.
op_callsubr()
fontTools.cffLib.transforms._MarkingT2Decompiler.op_callsubr (self, index)
Reimplemented from fontTools.misc.psCharStrings.SimpleT2Decompiler.
Definition at line 133 of file transforms.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/cffLib/transforms.py