Code Cloning Analysis: threadpoolctl.OpenBLASController Class Reference
threadpoolctl.OpenBLASController Class Reference
Public Member Functions
set_additional_attributes (self)
get_num_threads (self)
set_num_threads (self, num_threads)
get_version (self)
Public Member Functions inherited from threadpoolctl.LibController
__init__ (self, *, filepath=None, prefix=None, parent=None)
info (self)
num_threads (self)
Public Attributes
threading_layer = self._get_threading_layer()
architecture = self._get_architecture()
Public Attributes inherited from threadpoolctl.LibController
parent = parent
prefix = prefix
filepath = filepath
dynlib = ctypes.CDLL(filepath, mode=_RTLD_NOLOAD)
version = self.get_version()
user_api
internal_api
num_threads
Static Public Attributes
tuple filename_prefixes = ("libopenblas", "libblas", "libscipy_openblas")
check_symbols
Protected Member Functions
_find_affixes (self)
_get_threading_layer (self)
_get_architecture (self)
Protected Member Functions inherited from threadpoolctl.LibController
_get_symbol (self, name)
Static Protected Attributes
tuple _symbol_prefixes = ("", "scipy_")
tuple _symbol_suffixes = ("", "64_", "_64")
Additional Inherited Members
Protected Attributes inherited from threadpoolctl.LibController
_symbol_prefix
_symbol_suffix = self._find_affixes()
Detailed Description
Controller class for OpenBLAS
Definition at line 163 of file threadpoolctl.py.
Member Function Documentation
_find_affixes()
threadpoolctl.OpenBLASController._find_affixes (self) protected
Return the affixes for the symbols of the shared library
Reimplemented from threadpoolctl.LibController.
Definition at line 179 of file threadpoolctl.py.
References _symbol_prefixes, _symbol_suffixes, and threadpoolctl.LibController.dynlib.
_get_architecture()
threadpoolctl.OpenBLASController._get_architecture (self) protected
Return the architecture detected by OpenBLAS
Definition at line 226 of file threadpoolctl.py.
References threadpoolctl.LibController._get_symbol().
Referenced by threadpoolctl.BLISController.set_additional_attributes(), and set_additional_attributes().
_get_threading_layer()
threadpoolctl.OpenBLASController._get_threading_layer (self) protected
Return the threading layer of OpenBLAS
Definition at line 214 of file threadpoolctl.py.
References threadpoolctl.LibController._get_symbol().
Referenced by threadpoolctl.BLISController.set_additional_attributes(), threadpoolctl.MKLController.set_additional_attributes(), and set_additional_attributes().
get_num_threads()
threadpoolctl.OpenBLASController.get_num_threads (self)
Return the maximum number of threads available to use
Reimplemented from threadpoolctl.LibController.
Definition at line 190 of file threadpoolctl.py.
References threadpoolctl.LibController._get_symbol().
get_version()
threadpoolctl.OpenBLASController.get_version (self)
Return the version of the shared library
Reimplemented from threadpoolctl.LibController.
Definition at line 202 of file threadpoolctl.py.
References threadpoolctl.LibController._get_symbol().
set_additional_attributes()
threadpoolctl.OpenBLASController.set_additional_attributes (self)
Set additional attributes meant to be exposed in the info dict
Reimplemented from threadpoolctl.LibController.
Definition at line 186 of file threadpoolctl.py.
References _get_architecture(), _get_threading_layer(), architecture, and threading_layer.
set_num_threads()
threadpoolctl.OpenBLASController.set_num_threads (self, num_threads)
Set the maximum number of threads to use
Reimplemented from threadpoolctl.LibController.
Definition at line 196 of file threadpoolctl.py.
References threadpoolctl.LibController._get_symbol().
Member Data Documentation
_symbol_prefixes
threadpoolctl.OpenBLASController._symbol_prefixes = ("", "scipy_") static protected
Definition at line 170 of file threadpoolctl.py.
Referenced by _find_affixes().
_symbol_suffixes
tuple threadpoolctl.OpenBLASController._symbol_suffixes = ("", "64_", "_64") static protected
Definition at line 171 of file threadpoolctl.py.
Referenced by _find_affixes().
architecture
threadpoolctl.OpenBLASController.architecture = self._get_architecture()
Definition at line 188 of file threadpoolctl.py.
Referenced by threadpoolctl.BLISController.set_additional_attributes(), and set_additional_attributes().
check_symbols
threadpoolctl.OpenBLASController.check_symbols static
Initial value:
=  tuple(
        f"{prefix}openblas_get_num_threads{suffix}"
        for prefix, suffix in itertools.product(_symbol_prefixes, _symbol_suffixes)
    )
Definition at line 174 of file threadpoolctl.py.
filename_prefixes
tuple threadpoolctl.OpenBLASController.filename_prefixes = ("libopenblas", "libblas", "libscipy_openblas") static
Definition at line 168 of file threadpoolctl.py.
threading_layer
threadpoolctl.OpenBLASController.threading_layer = self._get_threading_layer()
Definition at line 187 of file threadpoolctl.py.
Referenced by threadpoolctl.BLISController.set_additional_attributes(), threadpoolctl.MKLController.set_additional_attributes(), and set_additional_attributes().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/threadpoolctl.py