Code Cloning Analysis: fontTools.ttLib.ttGlyphSet._TTGlyphSetCFF Class Reference
fontTools.ttLib.ttGlyphSet._TTGlyphSetCFF Class Reference
Public Member Functions
__init__ (self, font, location)
__getitem__ (self, glyphName)
setLocation (self, location)
pushLocation (self, location, bool reset)
Public Member Functions inherited from fontTools.ttLib.ttGlyphSet._TTGlyphSet
__init__ (self, font, location, glyphsMapping, *, recalcBounds=True)
pushDepth (self)
__contains__ (self, glyphName)
__iter__ (self)
__len__ (self)
has_key (self, glyphName)
Public Attributes
charStrings = list(font[tableTag].cff.values())[0].CharStrings
blender = None
Public Attributes inherited from fontTools.ttLib.ttGlyphSet._TTGlyphSet
recalcBounds = recalcBounds
font = font
tuple defaultLocationNormalized
list location = location if location is not None else {}
dict rawLocation = {}
originalLocation = location if location is not None else {}
int depth = 0
list locationStack = []
list rawLocationStack = []
glyphsMapping = glyphsMapping
hMetrics = font["hmtx"].metrics
vMetrics = getattr(font.get("vmtx"), "metrics", None)
hvarTable = None
hvarInstancer
Detailed Description
Definition at line 107 of file ttGlyphSet.py.
Constructor & Destructor Documentation
__init__()
fontTools.ttLib.ttGlyphSet._TTGlyphSetCFF.__init__ (self, font, location)
Definition at line 108 of file ttGlyphSet.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__getitem__()
fontTools.ttLib.ttGlyphSet._TTGlyphSetCFF.__getitem__ (self, glyphName)
Definition at line 114 of file ttGlyphSet.py.
pushLocation()
fontTools.ttLib.ttGlyphSet._TTGlyphSetCFF.pushLocation (self, location, bool reset)
Reimplemented from fontTools.ttLib.ttGlyphSet._TTGlyphSet.
Definition at line 134 of file ttGlyphSet.py.
setLocation()
fontTools.ttLib.ttGlyphSet._TTGlyphSetCFF.setLocation (self, location)
Definition at line 117 of file ttGlyphSet.py.
Member Data Documentation
blender
fontTools.ttLib.ttGlyphSet._TTGlyphSetCFF.blender = None
Definition at line 118 of file ttGlyphSet.py.
charStrings
fontTools.ttLib.ttGlyphSet._TTGlyphSetCFF.charStrings = list(font[tableTag].cff.values())[0].CharStrings
Definition at line 110 of file ttGlyphSet.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ttLib/ttGlyphSet.py