Code Cloning Analysis: pandas.conftest Namespace Reference
pandas.conftest Namespace Reference
Functions
None pytest_addoption (parser)
None ignore_doctest_warning (pytest.Item item, str path, str message)
None pytest_collection_modifyitems (items, config)
None add_doctest_imports (doctest_namespace)
None configure_tests ()
axis (request)
axis_1 (request)
observed (request)
ordered (request)
skipna (request)
keep (request)
inclusive_endpoints_fixture (request)
closed (request)
other_closed (request)
compression (request)
compression_only (request)
writable (request)
join_type (request)
nselect_method (request)
nulls_fixture (request)
unique_nulls_fixture (request)
np_nat_fixture (request)
frame_or_series (request)
index_or_series (request)
index_or_series_or_array (request)
box_with_array (request)
type[dict] dict_subclass ()
type[abc.Mapping] non_dict_mapping_subclass ()
multiindex_year_month_day_dataframe_random_data ()
MultiIndex lexsorted_two_level_string_multiindex ()
DataFrame multiindex_dataframe_random_data (lexsorted_two_level_string_multiindex)
_create_multiindex ()
_create_mi_with_dt64tz_level ()
index (request)
index_flat (request)
index_with_missing (request)
Series string_series ()
Series object_series ()
Series datetime_series ()
_create_series (index)
Series series_with_simple_index (index)
index_or_series_obj (request)
index_or_series_memory_obj (request)
DataFrame int_frame ()
DataFrame float_frame ()
Series rand_series_with_duplicate_datetimeindex ()
ea_scalar_and_dtype (request)
all_arithmetic_operators (request)
all_binary_operators (request)
all_arithmetic_functions (request)
all_numeric_reductions (request)
all_boolean_reductions (request)
all_reductions (request)
comparison_op (request)
compare_operators_no_eq_ne (request)
all_logical_operators (request)
all_numeric_accumulations (request)
strict_data_files (pytestconfig)
Callable[..., str] datapath (str strict_data_files)
tz_naive_fixture (request)
tz_aware_fixture (request)
utc_fixture (request)
unit (request)
string_dtype (request)
string_dtype_no_object (request)
nullable_string_dtype (request)
pyarrow_string_dtype (request)
string_storage (request)
string_dtype_arguments (request)
dtype_backend (request)
bytes_dtype (request)
object_dtype (request)
any_string_dtype (request)
datetime64_dtype (request)
timedelta64_dtype (request)
Timestamp fixed_now_ts ()
float_numpy_dtype (request)
float_ea_dtype (request)
any_float_dtype (request)
complex_dtype (request)
complex_or_float_dtype (request)
any_signed_int_numpy_dtype (request)
any_unsigned_int_numpy_dtype (request)
any_int_numpy_dtype (request)
any_int_ea_dtype (request)
any_int_dtype (request)
any_numeric_ea_dtype (request)
any_numeric_ea_and_arrow_dtype (request)
any_signed_int_ea_dtype (request)
any_real_numpy_dtype (request)
any_real_numeric_dtype (request)
any_numpy_dtype (request)
any_real_nullable_dtype (request)
any_numeric_dtype (request)
any_skipna_inferred_dtype (request)
ip ()
spmatrix (request)
tick_classes (request)
sort_by_key (request)
tuple[Hashable, Hashable, Hashable] names (request)
indexer_sli (request)
indexer_li (request)
indexer_si (request)
indexer_sl (request)
indexer_al (request)
indexer_ial (request)
bool using_array_manager ()
bool using_copy_on_write ()
bool warn_copy_on_write ()
bool using_infer_string ()
str warsaw (request)
arrow_string_storage ()
Variables
bool has_pyarrow = False
zoneinfo = None
list hypothesis_health_checks = [hypothesis.HealthCheck.too_slow]
deadline
suppress_health_check
cls = getattr(pd.tseries.offsets, name)
axis_frame = axis
nulls_fixture2 = nulls_fixture
unique_nulls_fixture2 = unique_nulls_fixture
np_nat_fixture2 = np_nat_fixture
index_or_series2 = index_or_series
box_with_array2 = box_with_array
dict indices_dict
idx = Index(pd.array([f"pandas_{i}" for i in range(100)], dtype="string[pyarrow]"))
index_fixture2 = index
index_flat2 = index_flat
dict _series
dict _narrow_series
dict _index_or_series_objs = {**indices_dict, **_series, **_narrow_series}
dict _typ_objects_series
dict _index_or_series_memory_objs
list _all_numeric_reductions
list _all_boolean_reductions = ["all", "any"]
list _all_reductions = _all_numeric_reductions + _all_boolean_reductions
list _all_numeric_accumulations = ["cumsum", "cumprod", "cummin", "cummax"]
list TIMEZONES
list TIMEZONE_IDS = [repr(i) for i in TIMEZONES]
tz_aware_fixture2 = tz_aware_fixture
list _UTCS = ["utc", "dateutil/UTC", utc, tzutc(), timezone.utc]
utc_fixture2 = utc_fixture
unit2 = unit
string_storage2 = string_storage
string_dtype_arguments2 = string_dtype_arguments
list _any_skipna_inferred_dtype
ids
_
list warsaws = ["Europe/Warsaw", "dateutil/Europe/Warsaw"]
_data = underlying_dict
Detailed Description
This file is very long and growing, but it was decided to not split it yet, as
it's still manageable (2020-03-17, ~1.1k LoC). See gh-31989
Instead of splitting it was decided to define sections here:
- Configuration / Settings
- Autouse fixtures
- Common arguments
- Missing values & co.
- Classes
- Indices
- Series'
- DataFrames
- Operators & Operations
- Data sets/files
- Time zones
- Dtypes
- Misc
Function Documentation
_create_mi_with_dt64tz_level()
pandas.conftest._create_mi_with_dt64tz_level () protected
MultiIndex with a level that is a tzaware DatetimeIndex.
Definition at line 606 of file conftest.py.
References _create_mi_with_dt64tz_level(), and _create_multiindex().
Referenced by _create_mi_with_dt64tz_level().
_create_multiindex()
pandas.conftest._create_multiindex () protected
MultiIndex used to test the general functionality of this object
Definition at line 586 of file conftest.py.
Referenced by _create_mi_with_dt64tz_level().
_create_series()
pandas.conftest._create_series (index) protected
Helper for the _series dict
Definition at line 773 of file conftest.py.
References _create_series().
Referenced by _create_series(), and series_with_simple_index().
add_doctest_imports()
None pandas.conftest.add_doctest_imports (doctest_namespace)
Make `np` and `pd` names available for doctests.
Definition at line 257 of file conftest.py.
all_arithmetic_functions()
pandas.conftest.all_arithmetic_functions (request)
Fixture for operator and roperator arithmetic functions.
Notes
-----
This includes divmod and rdivmod, whereas all_arithmetic_operators
does not.
Definition at line 977 of file conftest.py.
all_arithmetic_operators()
pandas.conftest.all_arithmetic_operators (request)
Fixture for dunder names for common arithmetic operations.
Definition at line 915 of file conftest.py.
all_binary_operators()
pandas.conftest.all_binary_operators (request)
Fixture for operator and roperator arithmetic, comparison, and logical ops.
Definition at line 952 of file conftest.py.
all_boolean_reductions()
pandas.conftest.all_boolean_reductions (request)
Fixture for boolean reduction names.
Definition at line 1017 of file conftest.py.
all_logical_operators()
pandas.conftest.all_logical_operators (request)
Fixture for dunder names for common logical operations
* |
* &
* ^
Definition at line 1068 of file conftest.py.
all_numeric_accumulations()
pandas.conftest.all_numeric_accumulations (request)
Fixture for numeric accumulation names
Definition at line 1083 of file conftest.py.
all_numeric_reductions()
pandas.conftest.all_numeric_reductions (request)
Fixture for numeric reduction names.
Definition at line 1006 of file conftest.py.
all_reductions()
pandas.conftest.all_reductions (request)
Fixture for all (boolean + numeric) reduction names.
Definition at line 1028 of file conftest.py.
any_float_dtype()
pandas.conftest.any_float_dtype (request)
Parameterized fixture for float dtypes.
* float
* 'float32'
* 'float64'
* 'Float32'
* 'Float64'
Definition at line 1466 of file conftest.py.
any_int_dtype()
pandas.conftest.any_int_dtype (request)
Parameterized fixture for any nullable integer dtype.
* int
* 'int8'
* 'uint8'
* 'int16'
* 'uint16'
* 'int32'
* 'uint32'
* 'int64'
* 'uint64'
* 'UInt8'
* 'Int8'
* 'UInt16'
* 'Int16'
* 'UInt32'
* 'Int32'
* 'UInt64'
* 'Int64'
Definition at line 1569 of file conftest.py.
any_int_ea_dtype()
pandas.conftest.any_int_ea_dtype (request)
Parameterized fixture for any nullable integer dtype.
* 'UInt8'
* 'Int8'
* 'UInt16'
* 'Int16'
* 'UInt32'
* 'Int32'
* 'UInt64'
* 'Int64'
Definition at line 1552 of file conftest.py.
any_int_numpy_dtype()
pandas.conftest.any_int_numpy_dtype (request)
Parameterized fixture for any integer dtype.
* int
* 'int8'
* 'uint8'
* 'int16'
* 'uint16'
* 'int32'
* 'uint32'
* 'int64'
* 'uint64'
Definition at line 1534 of file conftest.py.
any_numeric_dtype()
pandas.conftest.any_numeric_dtype (request)
Parameterized fixture for all numeric dtypes.
* int
* 'int8'
* 'uint8'
* 'int16'
* 'uint16'
* 'int32'
* 'uint32'
* 'int64'
* 'uint64'
* float
* 'float32'
* 'float64'
* complex
* 'complex64'
* 'complex128'
* 'UInt8'
* 'Int8'
* 'UInt16'
* 'Int16'
* 'UInt32'
* 'Int32'
* 'UInt64'
* 'Int64'
* 'Float32'
* 'Float64'
Definition at line 1778 of file conftest.py.
any_numeric_ea_and_arrow_dtype()
pandas.conftest.any_numeric_ea_and_arrow_dtype (request)
Parameterized fixture for any nullable integer dtype and
any float ea dtypes.
* 'UInt8'
* 'Int8'
* 'UInt16'
* 'Int16'
* 'UInt32'
* 'Int32'
* 'UInt64'
* 'Int64'
* 'Float32'
* 'Float64'
* 'uint8[pyarrow]'
* 'int8[pyarrow]'
* 'uint16[pyarrow]'
* 'int16[pyarrow]'
* 'uint32[pyarrow]'
* 'int32[pyarrow]'
* 'uint64[pyarrow]'
* 'int64[pyarrow]'
* 'float32[pyarrow]'
* 'float64[pyarrow]'
Definition at line 1622 of file conftest.py.
any_numeric_ea_dtype()
pandas.conftest.any_numeric_ea_dtype (request)
Parameterized fixture for any nullable integer dtype and
any float ea dtypes.
* 'UInt8'
* 'Int8'
* 'UInt16'
* 'Int16'
* 'UInt32'
* 'Int32'
* 'UInt64'
* 'Int64'
* 'Float32'
* 'Float64'
Definition at line 1595 of file conftest.py.
any_numpy_dtype()
pandas.conftest.any_numpy_dtype (request)
Parameterized fixture for all numpy dtypes.
* bool
* 'bool'
* int
* 'int8'
* 'uint8'
* 'int16'
* 'uint16'
* 'int32'
* 'uint32'
* 'int64'
* 'uint64'
* float
* 'float32'
* 'float64'
* complex
* 'complex64'
* 'complex128'
* str
* 'str'
* 'U'
* bytes
* 'bytes'
* 'datetime64[ns]'
* 'M8[ns]'
* 'timedelta64[ns]'
* 'm8[ns]'
* object
* 'object'
Definition at line 1709 of file conftest.py.
any_real_nullable_dtype()
pandas.conftest.any_real_nullable_dtype (request)
Parameterized fixture for all real dtypes that can hold NA.
* float
* 'float32'
* 'float64'
* 'Float32'
* 'Float64'
* 'UInt8'
* 'UInt16'
* 'UInt32'
* 'UInt64'
* 'Int8'
* 'Int16'
* 'Int32'
* 'Int64'
* 'uint8[pyarrow]'
* 'uint16[pyarrow]'
* 'uint32[pyarrow]'
* 'uint64[pyarrow]'
* 'int8[pyarrow]'
* 'int16[pyarrow]'
* 'int32[pyarrow]'
* 'int64[pyarrow]'
* 'float[pyarrow]'
* 'double[pyarrow]'
Definition at line 1746 of file conftest.py.
any_real_numeric_dtype()
pandas.conftest.any_real_numeric_dtype (request)
Parameterized fixture for any (purely) real numeric dtype.
* int
* 'int8'
* 'uint8'
* 'int16'
* 'uint16'
* 'int32'
* 'uint32'
* 'int64'
* 'uint64'
* float
* 'float32'
* 'float64'
and associated ea dtypes.
Definition at line 1686 of file conftest.py.
any_real_numpy_dtype()
pandas.conftest.any_real_numpy_dtype (request)
Parameterized fixture for any (purely) real numeric dtype.
* int
* 'int8'
* 'uint8'
* 'int16'
* 'uint16'
* 'int32'
* 'uint32'
* 'int64'
* 'uint64'
* float
* 'float32'
* 'float64'
Definition at line 1665 of file conftest.py.
any_signed_int_ea_dtype()
pandas.conftest.any_signed_int_ea_dtype (request)
Parameterized fixture for any signed nullable integer dtype.
* 'Int8'
* 'Int16'
* 'Int32'
* 'Int64'
Definition at line 1652 of file conftest.py.
any_signed_int_numpy_dtype()
pandas.conftest.any_signed_int_numpy_dtype (request)
Parameterized fixture for signed integer dtypes.
* int
* 'int8'
* 'int16'
* 'int32'
* 'int64'
Definition at line 1507 of file conftest.py.
any_skipna_inferred_dtype()
pandas.conftest.any_skipna_inferred_dtype (request)
Fixture for all inferred dtypes from _libs.lib.infer_dtype
The covered (inferred) types are:
* 'string'
* 'empty'
* 'bytes'
* 'mixed'
* 'mixed-integer'
* 'mixed-integer-float'
* 'floating'
* 'integer'
* 'decimal'
* 'boolean'
* 'datetime64'
* 'datetime'
* 'date'
* 'timedelta'
* 'time'
* 'period'
* 'interval'
Returns
-------
inferred_dtype : str
    The string for the inferred dtype from _libs.lib.infer_dtype
values : np.ndarray
    An array of object dtype that will be inferred to have
    `inferred_dtype`
Examples
--------
>>> from pandas._libs import lib
>>>
>>> def test_something(any_skipna_inferred_dtype):
...     inferred_dtype, values = any_skipna_inferred_dtype
...     # will pass
...     assert lib.infer_dtype(values, skipna=True) == inferred_dtype
Definition at line 1843 of file conftest.py.
any_string_dtype()
pandas.conftest.any_string_dtype (request)
Parametrized fixture for string dtypes.
* 'object'
* 'string[python]' (NA variant)
* 'string[pyarrow]' (NA variant)
* 'str' (NaN variant, with pyarrow)
* 'str' (NaN variant, without pyarrow)
Definition at line 1392 of file conftest.py.
any_unsigned_int_numpy_dtype()
pandas.conftest.any_unsigned_int_numpy_dtype (request)
Parameterized fixture for unsigned integer dtypes.
* 'uint8'
* 'uint16'
* 'uint32'
* 'uint64'
Definition at line 1521 of file conftest.py.
arrow_string_storage()
pandas.conftest.arrow_string_storage ()
Definition at line 2064 of file conftest.py.
axis()
pandas.conftest.axis (request)
Fixture for returning the axis numbers of a DataFrame.
Definition at line 277 of file conftest.py.
axis_1()
pandas.conftest.axis_1 (request)
Fixture for returning aliases of axis 1 of a DataFrame.
Definition at line 288 of file conftest.py.
box_with_array()
pandas.conftest.box_with_array (request)
Fixture to test behavior for Index, Series, DataFrame, and pandas Array
classes
Definition at line 494 of file conftest.py.
bytes_dtype()
pandas.conftest.bytes_dtype (request)
Parametrized fixture for bytes dtypes.
* bytes
* 'bytes'
Definition at line 1355 of file conftest.py.
closed()
pandas.conftest.closed (request)
Fixture for trying all interval closed parameters.
Definition at line 342 of file conftest.py.
compare_operators_no_eq_ne()
pandas.conftest.compare_operators_no_eq_ne (request)
Fixture for dunder names for compare operations except == and !=
* >=
* >
* <
* <=
Definition at line 1053 of file conftest.py.
comparison_op()
pandas.conftest.comparison_op (request)
Fixture for operator module comparison functions.
Definition at line 1045 of file conftest.py.
complex_dtype()
pandas.conftest.complex_dtype (request)
Parameterized fixture for complex dtypes.
* complex
* 'complex64'
* 'complex128'
Definition at line 1480 of file conftest.py.
complex_or_float_dtype()
pandas.conftest.complex_or_float_dtype (request)
Parameterized fixture for complex and numpy float dtypes.
* complex
* 'complex64'
* 'complex128'
* float
* 'float32'
* 'float64'
Definition at line 1492 of file conftest.py.
compression()
pandas.conftest.compression (request)
Fixture for trying common compression types in compression tests.
Definition at line 368 of file conftest.py.
compression_only()
pandas.conftest.compression_only (request)
Fixture for trying common compression types in compression tests excluding
uncompressed case.
Definition at line 385 of file conftest.py.
configure_tests()
None pandas.conftest.configure_tests ()
Configure settings for all tests and test modules.
Definition at line 266 of file conftest.py.
datapath()
Callable[..., str] pandas.conftest.datapath (str strict_data_files)
Get the path to a data file.
Parameters
----------
path : str
    Path to the file, relative to ``pandas/tests/``
Returns
-------
path including ``pandas/tests``.
Raises
------
ValueError
    If the path doesn't exist and the --no-strict-data-files option is not set.
Definition at line 1102 of file conftest.py.
datetime64_dtype()
pandas.conftest.datetime64_dtype (request)
Parametrized fixture for datetime64 dtypes.
* 'datetime64[ns]'
* 'M8[ns]'
Definition at line 1411 of file conftest.py.
datetime_series()
Series pandas.conftest.datetime_series ()
Fixture for Series of floats with DatetimeIndex
Definition at line 762 of file conftest.py.
dict_subclass()
type[dict] pandas.conftest.dict_subclass ()
Fixture for a dictionary subclass.
Definition at line 506 of file conftest.py.
dtype_backend()
pandas.conftest.dtype_backend (request)
Parametrized fixture for pd.options.mode.string_storage.
* 'python'
* 'pyarrow'
Definition at line 1339 of file conftest.py.
ea_scalar_and_dtype()
pandas.conftest.ea_scalar_and_dtype (request)
Definition at line 905 of file conftest.py.
fixed_now_ts()
Timestamp pandas.conftest.fixed_now_ts ()
Fixture emits fixed Timestamp.now()
Definition at line 1433 of file conftest.py.
float_ea_dtype()
pandas.conftest.float_ea_dtype (request)
Parameterized fixture for float dtypes.
* 'Float32'
* 'Float64'
Definition at line 1455 of file conftest.py.
float_frame()
DataFrame pandas.conftest.float_frame ()
Fixture for DataFrame of floats with index of unique strings
Columns are ['A', 'B', 'C', 'D'].
Definition at line 855 of file conftest.py.
float_numpy_dtype()
pandas.conftest.float_numpy_dtype (request)
Parameterized fixture for float dtypes.
* float
* 'float32'
* 'float64'
Definition at line 1443 of file conftest.py.
frame_or_series()
pandas.conftest.frame_or_series (request)
Fixture to parametrize over DataFrame and Series.
Definition at line 461 of file conftest.py.
ignore_doctest_warning()
None pandas.conftest.ignore_doctest_warning (pytest.Item item, str path, str message)
Ignore doctest warning.
Parameters
----------
item : pytest.Item
    pytest test item.
path : str
    Module path to Python object, e.g. "pandas.core.frame.DataFrame.append". A
    warning will be filtered when item.name ends with in given path. So it is
    sufficient to specify e.g. "DataFrame.append".
message : str
    Message to be filtered.
Definition at line 119 of file conftest.py.
References ignore_doctest_warning().
Referenced by ignore_doctest_warning().
inclusive_endpoints_fixture()
pandas.conftest.inclusive_endpoints_fixture (request)
Fixture for trying all interval 'inclusive' parameters.
Definition at line 334 of file conftest.py.
index()
pandas.conftest.index (request)
Fixture for many "simple" kinds of indices.
These indices are unlikely to cover corner cases, e.g.
    - no names
    - no NaTs/NaNs
    - no values near implementation bounds
    - ...
Definition at line 664 of file conftest.py.
index_flat()
pandas.conftest.index_flat (request)
index fixture, but excluding MultiIndex cases.
Definition at line 687 of file conftest.py.
index_or_series()
pandas.conftest.index_or_series (request)
Fixture to parametrize over Index and Series, made necessary by a mypy
bug, giving an error:
List item 0 has incompatible type "Type[Series]"; expected "Type[PandasObject]"
See GH#29725
Definition at line 469 of file conftest.py.
index_or_series_memory_obj()
pandas.conftest.index_or_series_memory_obj (request)
Fixture for tests on indexes, series, series with a narrow dtype and
series with empty objects type
copy to avoid mutation, e.g. setting .name
Definition at line 828 of file conftest.py.
index_or_series_obj()
pandas.conftest.index_or_series_obj (request)
Fixture for tests on indexes, series and series with a narrow dtype
copy to avoid mutation, e.g. setting .name
Definition at line 806 of file conftest.py.
index_or_series_or_array()
pandas.conftest.index_or_series_or_array (request)
Fixture to parametrize over Index, Series, and ExtensionArray
Definition at line 486 of file conftest.py.
index_with_missing()
pandas.conftest.index_with_missing (request)
Fixture for indices with missing values.
Integer-dtype and empty cases are excluded because they cannot hold missing
values.
MultiIndex is excluded because isna() is not defined for MultiIndex.
Definition at line 710 of file conftest.py.
indexer_al()
pandas.conftest.indexer_al (request)
Parametrize over at.__setitem__, loc.__setitem__
Definition at line 1997 of file conftest.py.
indexer_ial()
pandas.conftest.indexer_ial (request)
Parametrize over iat.__setitem__, iloc.__setitem__
Definition at line 2005 of file conftest.py.
indexer_li()
pandas.conftest.indexer_li (request)
Parametrize over loc.__getitem__, iloc.__getitem__
Definition at line 1973 of file conftest.py.
indexer_si()
pandas.conftest.indexer_si (request)
Parametrize over __setitem__, iloc.__setitem__
Definition at line 1981 of file conftest.py.
indexer_sl()
pandas.conftest.indexer_sl (request)
Parametrize over __setitem__, loc.__setitem__
Definition at line 1989 of file conftest.py.
indexer_sli()
pandas.conftest.indexer_sli (request)
Parametrize over __setitem__, loc.__setitem__, iloc.__setitem__
Definition at line 1965 of file conftest.py.
int_frame()
DataFrame pandas.conftest.int_frame ()
Fixture for DataFrame of ints with index of unique strings
Columns are ['A', 'B', 'C', 'D']
Definition at line 841 of file conftest.py.
ip()
pandas.conftest.ip ()
Get an instance of IPython.InteractiveShell.
Will raise a skip if IPython is not installed.
Definition at line 1894 of file conftest.py.
join_type()
pandas.conftest.join_type (request)
Fixture for trying all types of join operations.
Definition at line 402 of file conftest.py.
keep()
pandas.conftest.keep (request)
Valid values for the 'keep' parameter used in
.duplicated or .drop_duplicates
Definition at line 325 of file conftest.py.
lexsorted_two_level_string_multiindex()
MultiIndex pandas.conftest.lexsorted_two_level_string_multiindex ()
2-level MultiIndex, lexsorted, with string names.
Definition at line 562 of file conftest.py.
multiindex_dataframe_random_data()
DataFrame pandas.conftest.multiindex_dataframe_random_data (lexsorted_two_level_string_multiindex)
DataFrame with 2 level MultiIndex with random data
Definition at line 574 of file conftest.py.
multiindex_year_month_day_dataframe_random_data()
pandas.conftest.multiindex_year_month_day_dataframe_random_data ()
DataFrame with 3 level MultiIndex (year, month, day) covering
first 100 business days from 2000-01-01 with random data
Definition at line 544 of file conftest.py.
names()
tuple[Hashable, Hashable, Hashable] pandas.conftest.names (request)
A 3-tuple of names, the first two for operands, the last for a result.
Definition at line 1957 of file conftest.py.
non_dict_mapping_subclass()
type[abc.Mapping] pandas.conftest.non_dict_mapping_subclass ()
Fixture for a non-mapping dictionary subclass.
Definition at line 519 of file conftest.py.
np_nat_fixture()
pandas.conftest.np_nat_fixture (request)
Fixture for each NaT type in numpy.
Definition at line 444 of file conftest.py.
nselect_method()
pandas.conftest.nselect_method (request)
Fixture for trying all nselect methods.
Definition at line 410 of file conftest.py.
nullable_string_dtype()
pandas.conftest.nullable_string_dtype (request)
Parametrized fixture for string dtypes.
* 'string[python]'
* 'string[pyarrow]'
Definition at line 1266 of file conftest.py.
nulls_fixture()
pandas.conftest.nulls_fixture (request)
Fixture for each null type in pandas.
Definition at line 421 of file conftest.py.
object_dtype()
pandas.conftest.object_dtype (request)
Parametrized fixture for object dtypes.
* object
* 'object'
Definition at line 1366 of file conftest.py.
object_series()
Series pandas.conftest.object_series ()
Fixture for Series of dtype object with Index of unique strings
Definition at line 752 of file conftest.py.
observed()
pandas.conftest.observed (request)
Pass in the observed keyword to groupby for [True, False]
This indicates whether categoricals should return values for
values which are not in the grouper [False / None], or only values which
appear in the grouper [True]. [None] is supported for future compatibility
if we decide to change the default (and would need to warn if this
parameter is not passed).
Definition at line 296 of file conftest.py.
ordered()
pandas.conftest.ordered (request)
Boolean 'ordered' parameter for Categorical.
Definition at line 309 of file conftest.py.
other_closed()
pandas.conftest.other_closed (request)
Secondary closed fixture to allow parametrizing over all pairs of closed.
Definition at line 350 of file conftest.py.
pyarrow_string_dtype()
pandas.conftest.pyarrow_string_dtype (request)
Parametrized fixture for string dtypes backed by Pyarrow.
* 'str[pyarrow]'
* 'string[pyarrow]'
Definition at line 1282 of file conftest.py.
pytest_addoption()
None pandas.conftest.pytest_addoption (parser)
Definition at line 111 of file conftest.py.
pytest_collection_modifyitems()
None pandas.conftest.pytest_collection_modifyitems (items, config)
Definition at line 137 of file conftest.py.
rand_series_with_duplicate_datetimeindex()
Series pandas.conftest.rand_series_with_duplicate_datetimeindex ()
Fixture for Series with a DatetimeIndex that has duplicates.
Definition at line 869 of file conftest.py.
series_with_simple_index()
Series pandas.conftest.series_with_simple_index (index)
Fixture for tests on series with changing types of indices.
Definition at line 787 of file conftest.py.
References _create_series().
skipna()
pandas.conftest.skipna (request)
Boolean 'skipna' parameter.
Definition at line 317 of file conftest.py.
sort_by_key()
pandas.conftest.sort_by_key (request)
Simple fixture for testing keys in sorting methods.
Tests None (no key) and the identity key.
Definition at line 1937 of file conftest.py.
spmatrix()
pandas.conftest.spmatrix (request)
Yields scipy sparse matrix classes.
Definition at line 1913 of file conftest.py.
strict_data_files()
pandas.conftest.strict_data_files (pytestconfig)
Returns the configuration for the test setting `--no-strict-data-files`.
Definition at line 1094 of file conftest.py.
string_dtype()
pandas.conftest.string_dtype (request)
Parametrized fixture for string dtypes.
* str
* 'str'
* 'U'
Definition at line 1221 of file conftest.py.
string_dtype_arguments()
pandas.conftest.string_dtype_arguments (request)
Parametrized fixture for StringDtype storage and na_value.
* 'python' + pd.NA
* 'pyarrow' + pd.NA
* 'pyarrow' + np.nan
Definition at line 1322 of file conftest.py.
string_dtype_no_object()
pandas.conftest.string_dtype_no_object (request)
Parametrized fixture for string dtypes.
* 'string[python]' (NA variant)
* 'string[pyarrow]' (NA variant)
* 'str' (NaN variant, with pyarrow)
* 'str' (NaN variant, without pyarrow)
Definition at line 1246 of file conftest.py.
string_series()
Series pandas.conftest.string_series ()
Fixture for Series of floats with Index of unique strings
Definition at line 740 of file conftest.py.
string_storage()
pandas.conftest.string_storage (request)
Parametrized fixture for pd.options.mode.string_storage.
* 'python'
* 'pyarrow'
Definition at line 1298 of file conftest.py.
tick_classes()
pandas.conftest.tick_classes (request)
Fixture for Tick based datetime offsets available for a time series.
Definition at line 1929 of file conftest.py.
timedelta64_dtype()
pandas.conftest.timedelta64_dtype (request)
Parametrized fixture for timedelta64 dtypes.
* 'timedelta64[ns]'
* 'm8[ns]'
Definition at line 1422 of file conftest.py.
tz_aware_fixture()
pandas.conftest.tz_aware_fixture (request)
Fixture for trying explicit timezones: {0}
Definition at line 1179 of file conftest.py.
tz_naive_fixture()
pandas.conftest.tz_naive_fixture (request)
Fixture for trying timezones including default (None): {0}
Definition at line 1170 of file conftest.py.
unique_nulls_fixture()
pandas.conftest.unique_nulls_fixture (request)
Fixture for each null type in pandas, each null type exactly once.
Definition at line 432 of file conftest.py.
unit()
pandas.conftest.unit (request)
datetime64 units we support.
Definition at line 1207 of file conftest.py.
using_array_manager()
bool pandas.conftest.using_array_manager ()
Fixture to check if the array manager is being used.
Definition at line 2013 of file conftest.py.
using_copy_on_write()
bool pandas.conftest.using_copy_on_write ()
Fixture to check if Copy-on-Write is enabled.
Definition at line 2021 of file conftest.py.
using_infer_string()
bool pandas.conftest.using_infer_string ()
Fixture to check if infer string option is enabled.
Definition at line 2043 of file conftest.py.
utc_fixture()
pandas.conftest.utc_fixture (request)
Fixture to provide variants of UTC timezone strings and tzinfo objects.
Definition at line 1196 of file conftest.py.
warn_copy_on_write()
bool pandas.conftest.warn_copy_on_write ()
Fixture to check if Copy-on-Write is in warning mode.
Definition at line 2032 of file conftest.py.
warsaw()
str pandas.conftest.warsaw (request)
tzinfo for Europe/Warsaw using pytz, dateutil, or zoneinfo.
Definition at line 2056 of file conftest.py.
writable()
pandas.conftest.writable (request)
Fixture that an array is writable.
Definition at line 394 of file conftest.py.
Variable Documentation
_
pandas.conftest._ protected
Definition at line 1839 of file conftest.py.
_all_boolean_reductions
list pandas.conftest._all_boolean_reductions = ["all", "any"] protected
Definition at line 1013 of file conftest.py.
_all_numeric_accumulations
list pandas.conftest._all_numeric_accumulations = ["cumsum", "cumprod", "cummin", "cummax"] protected
Definition at line 1079 of file conftest.py.
_all_numeric_reductions
list pandas.conftest._all_numeric_reductions protected
Initial value:
=  [
    "count",
    "sum",
    "max",
    "min",
    "mean",
    "prod",
    "std",
    "var",
    "median",
    "kurt",
    "skew",
    "sem",
]
Definition at line 989 of file conftest.py.
_all_reductions
list pandas.conftest._all_reductions = _all_numeric_reductions + _all_boolean_reductions protected
Definition at line 1024 of file conftest.py.
_any_skipna_inferred_dtype
list pandas.conftest._any_skipna_inferred_dtype protected
Initial value:
=  [
    ("string", ["a", np.nan, "c"]),
    ("string", ["a", pd.NA, "c"]),
    ("mixed", ["a", pd.NaT, "c"]),  # pd.NaT not considered valid by is_string_array
    ("bytes", [b"a", np.nan, b"c"]),
    ("empty", [np.nan, np.nan, np.nan]),
    ("empty", []),
    ("mixed-integer", ["a", np.nan, 2]),
    ("mixed", ["a", np.nan, 2.0]),
    ("floating", [1.0, np.nan, 2.0]),
    ("integer", [1, np.nan, 2]),
    ("mixed-integer-float", [1, np.nan, 2.0]),
    ("decimal", [Decimal(1), np.nan, Decimal(2)]),
    ("boolean", [True, np.nan, False]),
    ("boolean", [True, pd.NA, False]),
    ("datetime64", [np.datetime64("2013-01-01"), np.nan, np.datetime64("2018-01-01")]),
    ("datetime", [Timestamp("20130101"), np.nan, Timestamp("20180101")]),
    ("date", [date(2013, 1, 1), np.nan, date(2018, 1, 1)]),
    ("complex", [1 + 1j, np.nan, 2 + 2j]),
    # The following dtype is commented out due to GH 23554
    # ('timedelta64', [np.timedelta64(1, 'D'),
    #                  np.nan, np.timedelta64(2, 'D')]),
    ("timedelta", [timedelta(1), np.nan, timedelta(2)]),
    ("time", [time(1), np.nan, time(2)]),
    ("period", [Period(2013), pd.NaT, Period(2018)]),
    ("interval", [Interval(0, 1), np.nan, Interval(0, 2)]),
]
Definition at line 1812 of file conftest.py.
_data
pandas.conftest._data = underlying_dict protected
Definition at line 526 of file conftest.py.
_index_or_series_memory_objs
dict pandas.conftest._index_or_series_memory_objs protected
Initial value:
=  {
    **indices_dict,
    **_series,
    **_narrow_series,
    **_typ_objects_series,
}
Definition at line 819 of file conftest.py.
_index_or_series_objs
dict pandas.conftest._index_or_series_objs = {**indices_dict, **_series, **_narrow_series} protected
Definition at line 802 of file conftest.py.
_narrow_series
dict pandas.conftest._narrow_series protected
Initial value:
=  {
    f"{dtype.__name__}-series": Series(
        range(30), index=[f"i-{i}" for i in range(30)], name="a", dtype=dtype
    )
    for dtype in tm.NARROW_NP_DTYPES
}
Definition at line 794 of file conftest.py.
_series
dict pandas.conftest._series protected
Initial value:
=  {
    f"series-with-{index_id}-index": _create_series(index)
    for index_id, index in indices_dict.items()
}
Definition at line 780 of file conftest.py.
_typ_objects_series
dict pandas.conftest._typ_objects_series protected
Initial value:
=  {
    f"{dtype.__name__}-series": Series(dtype) for dtype in tm.PYTHON_DATA_TYPES
}
Definition at line 814 of file conftest.py.
_UTCS
list pandas.conftest._UTCS = ["utc", "dateutil/UTC", utc, tzutc(), timezone.utc] protected
Definition at line 1190 of file conftest.py.
axis_frame
pandas.conftest.axis_frame = axis
Definition at line 284 of file conftest.py.
box_with_array2
pandas.conftest.box_with_array2 = box_with_array
Definition at line 502 of file conftest.py.
cls
pandas.conftest.cls = getattr(pd.tseries.offsets, name)
Definition at line 219 of file conftest.py.
deadline
pandas.conftest.deadline
Definition at line 211 of file conftest.py.
has_pyarrow
bool pandas.conftest.has_pyarrow = False
Definition at line 92 of file conftest.py.
hypothesis_health_checks
list pandas.conftest.hypothesis_health_checks = [hypothesis.HealthCheck.too_slow]
Definition at line 197 of file conftest.py.
ids
pandas.conftest.ids
Definition at line 1839 of file conftest.py.
idx
pandas.conftest.idx = Index(pd.array([f"pandas_{i}" for i in range(100)], dtype="string[pyarrow]"))
Definition at line 659 of file conftest.py.
index_fixture2
pandas.conftest.index_fixture2 = index
Definition at line 679 of file conftest.py.
index_flat2
pandas.conftest.index_flat2 = index_flat
Definition at line 696 of file conftest.py.
index_or_series2
pandas.conftest.index_or_series2 = index_or_series
Definition at line 482 of file conftest.py.
indices_dict
dict pandas.conftest.indices_dict
Definition at line 617 of file conftest.py.
np_nat_fixture2
pandas.conftest.np_nat_fixture2 = np_nat_fixture
Definition at line 452 of file conftest.py.
nulls_fixture2
pandas.conftest.nulls_fixture2 = nulls_fixture
Definition at line 428 of file conftest.py.
string_dtype_arguments2
pandas.conftest.string_dtype_arguments2 = string_dtype_arguments
Definition at line 1351 of file conftest.py.
string_storage2
pandas.conftest.string_storage2 = string_storage
Definition at line 1350 of file conftest.py.
suppress_health_check
pandas.conftest.suppress_health_check
Definition at line 212 of file conftest.py.
TIMEZONE_IDS
list pandas.conftest.TIMEZONE_IDS = [repr(i) for i in TIMEZONES]
Definition at line 1165 of file conftest.py.
TIMEZONES
list pandas.conftest.TIMEZONES
Initial value:
=  [
    None,
    "UTC",
    "US/Eastern",
    "Asia/Tokyo",
    "dateutil/US/Pacific",
    "dateutil/Asia/Singapore",
    "+01:15",
    "-02:15",
    "UTC+01:15",
    "UTC-02:15",
    tzutc(),
    tzlocal(),
    FixedOffset(300),
    FixedOffset(0),
    FixedOffset(-300),
    timezone.utc,
    timezone(timedelta(hours=1)),
    timezone(timedelta(hours=-1), name="foo"),
]
Definition at line 1138 of file conftest.py.
tz_aware_fixture2
pandas.conftest.tz_aware_fixture2 = tz_aware_fixture
Definition at line 1187 of file conftest.py.
unique_nulls_fixture2
pandas.conftest.unique_nulls_fixture2 = unique_nulls_fixture
Definition at line 440 of file conftest.py.
unit2
pandas.conftest.unit2 = unit
Definition at line 1214 of file conftest.py.
utc_fixture2
pandas.conftest.utc_fixture2 = utc_fixture
Definition at line 1203 of file conftest.py.
warsaws
list pandas.conftest.warsaws = ["Europe/Warsaw", "dateutil/Europe/Warsaw"]
Definition at line 2050 of file conftest.py.
zoneinfo
pandas.conftest.zoneinfo = None
Definition at line 102 of file conftest.py.