Code Cloning Analysis: pip._vendor.typing_extensions.TypeAliasType Class Reference
pip._vendor.typing_extensions.TypeAliasType Class Reference
Public Member Functions
__init__ (self, str name, value, *, type_params=())
None __setattr__ (self, str __name, object __value)
Never __delattr__ (self, str __name)
str __repr__ (self)
__getitem__ (self, parameters)
__reduce__ (self)
__init_subclass__ (cls, *args, **kwargs)
__call__ (self)
__or__ (self, right)
__ror__ (self, left)
Protected Member Functions
Never _raise_attribute_error (self, str name)
Private Attributes
__value__ = value
__type_params__ = type_params
__parameters__ = tuple(parameters)
__module__ = def_mod
__name__ = name
Detailed Description
Create named, parameterized type aliases.
This provides a backport of the new `type` statement in Python 3.12:
    type ListOrSet[T] = list[T] | set[T]
is equivalent to:
    T = TypeVar("T")
    ListOrSet = TypeAliasType("ListOrSet", list[T] | set[T], type_params=(T,))
The name ListOrSet can then be used as an alias for the type it refers to.
The type_params argument should contain all the type parameters used
in the value of the type alias. If the alias is not generic, this
argument is omitted.
Static type checkers should only support type aliases declared using
TypeAliasType that follow these rules:
- The first argument (the name) must be a string literal.
- The TypeAliasType instance must be immediately assigned to a variable
  of the same name. (For example, 'X = TypeAliasType("Y", int)' is invalid,
  as is 'X, Y = TypeAliasType("X", int), TypeAliasType("Y", int)').
Definition at line 2876 of file typing_extensions.py.
Constructor & Destructor Documentation
__init__()
pip._vendor.typing_extensions.TypeAliasType.__init__ (self, str name, value, * , type_params = ())
Definition at line 2904 of file typing_extensions.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
__call__()
pip._vendor.typing_extensions.TypeAliasType.__call__ (self)
Definition at line 2969 of file typing_extensions.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), and scipy.interpolate._fitpack2.SphereBivariateSpline.ev().
__delattr__()
Never pip._vendor.typing_extensions.TypeAliasType.__delattr__ (self, str __name)
Definition at line 2928 of file typing_extensions.py.
__getitem__()
pip._vendor.typing_extensions.TypeAliasType.__getitem__ (self, parameters)
Definition at line 2948 of file typing_extensions.py.
__init_subclass__()
pip._vendor.typing_extensions.TypeAliasType.__init_subclass__ (cls, * args, ** kwargs)
Definition at line 2962 of file typing_extensions.py.
__or__()
pip._vendor.typing_extensions.TypeAliasType.__or__ (self, right)
Definition at line 2973 of file typing_extensions.py.
__reduce__()
pip._vendor.typing_extensions.TypeAliasType.__reduce__ (self)
Definition at line 2959 of file typing_extensions.py.
__repr__()
str pip._vendor.typing_extensions.TypeAliasType.__repr__ (self)
Definition at line 2945 of file typing_extensions.py.
__ror__()
pip._vendor.typing_extensions.TypeAliasType.__ror__ (self, left)
Definition at line 2980 of file typing_extensions.py.
__setattr__()
None pip._vendor.typing_extensions.TypeAliasType.__setattr__ (self, str __name, object __value)
Definition at line 2923 of file typing_extensions.py.
Referenced by scipy.io._netcdf.netcdf_file.flush().
_raise_attribute_error()
Never pip._vendor.typing_extensions.TypeAliasType._raise_attribute_error (self, str name) protected
Definition at line 2931 of file typing_extensions.py.
Member Data Documentation
__module__
pip._vendor.typing_extensions.TypeAliasType.__module__ = def_mod private
Definition at line 2919 of file typing_extensions.py.
Referenced by pip._vendor.pygments.sphinxext.PygmentsDoc.document_lexers_overview(), and matplotlib.backend_bases._Backend.show().
__name__
pip._vendor.typing_extensions.TypeAliasType.__name__ = name private
Definition at line 2921 of file typing_extensions.py.
Referenced by sklearn.utils.deprecation.deprecated.__call__(), pandas.tseries.holiday.Holiday._apply_rule(), sklearn.utils._metadata_requests._MetadataRequester._build_request_for_signature(), pandas.core.arrays.interval.IntervalArray._from_factorized(), sklearn.utils._metadata_requests._MetadataRequester._get_default_requests(), pandas.tests.extension.date.array.DateDtype.construct_from_string(), and matplotlib.patches._Style.pprint_styles().
__parameters__
pip._vendor.typing_extensions.TypeAliasType.__parameters__ = tuple(parameters) private
Definition at line 2916 of file typing_extensions.py.
__type_params__
pip._vendor.typing_extensions.TypeAliasType.__type_params__ = type_params private
Definition at line 2908 of file typing_extensions.py.
__value__
pip._vendor.typing_extensions.TypeAliasType.__value__ = value private
Definition at line 2907 of file typing_extensions.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pip/_vendor/typing_extensions.py