Code Cloning Analysis: joblib.compressor.LZMACompressorWrapper Class Reference
joblib.compressor.LZMACompressorWrapper Class Reference
Public Member Functions
__init__ (self)
compressor_file (self, fileobj, compresslevel=None)
decompressor_file (self, fileobj)
Public Member Functions inherited from joblib.compressor.CompressorWrapper
__init__ (self, obj, prefix=b"", extension="")
Protected Member Functions
_check_versions (self)
Protected Attributes
_lzma_format = getattr(lzma, self._lzma_format_name)
Static Protected Attributes
str _lzma_format_name = "FORMAT_ALONE"
Additional Inherited Members
Public Attributes inherited from joblib.compressor.CompressorWrapper
fileobj_factory = obj
prefix = prefix
extension = extension
Detailed Description
Definition at line 152 of file compressor.py.
Constructor & Destructor Documentation
__init__()
joblib.compressor.LZMACompressorWrapper.__init__ (self)
Definition at line 157 of file compressor.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_check_versions()
joblib.compressor.LZMACompressorWrapper._check_versions (self) protected
Definition at line 164 of file compressor.py.
Referenced by joblib.compressor.LZ4CompressorWrapper.compressor_file(), and joblib.compressor.LZ4CompressorWrapper.decompressor_file().
compressor_file()
joblib.compressor.LZMACompressorWrapper.compressor_file (self, fileobj, compresslevel = None)
Returns an instance of a compressor file object.
Reimplemented from joblib.compressor.CompressorWrapper.
Definition at line 170 of file compressor.py.
References _lzma_format, and joblib.compressor.CompressorWrapper.fileobj_factory.
decompressor_file()
joblib.compressor.LZMACompressorWrapper.decompressor_file (self, fileobj)
Returns an instance of a decompressor file object.
Reimplemented from joblib.compressor.CompressorWrapper.
Definition at line 179 of file compressor.py.
Member Data Documentation
_lzma_format
joblib.compressor.LZMACompressorWrapper._lzma_format = getattr(lzma, self._lzma_format_name) protected
Definition at line 160 of file compressor.py.
Referenced by compressor_file().
_lzma_format_name
str joblib.compressor.LZMACompressorWrapper._lzma_format_name = "FORMAT_ALONE" static protected
Definition at line 155 of file compressor.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/joblib/compressor.py