Code Cloning Analysis: fontTools.misc.bezierTools Namespace Reference
fontTools.misc.bezierTools Namespace Reference
Functions
calcCubicArcLength (pt1, pt2, pt3, pt4, tolerance=0.005)
_split_cubic_into_two (p0, p1, p2, p3)
_calcCubicArcLengthCRecurse (mult, p0, p1, p2, p3)
calcCubicArcLengthC (pt1, pt2, pt3, pt4, tolerance=0.005)
_dot (v1, v2)
_intSecAtan (x)
calcQuadraticArcLength (pt1, pt2, pt3)
calcQuadraticArcLengthC (pt1, pt2, pt3)
approximateQuadraticArcLength (pt1, pt2, pt3)
approximateQuadraticArcLengthC (pt1, pt2, pt3)
calcQuadraticBounds (pt1, pt2, pt3)
approximateCubicArcLength (pt1, pt2, pt3, pt4)
approximateCubicArcLengthC (pt1, pt2, pt3, pt4)
calcCubicBounds (pt1, pt2, pt3, pt4)
splitLine (pt1, pt2, where, isHorizontal)
splitQuadratic (pt1, pt2, pt3, where, isHorizontal)
splitCubic (pt1, pt2, pt3, pt4, where, isHorizontal)
splitQuadraticAtT (pt1, pt2, pt3, *ts)
splitCubicAtT (pt1, pt2, pt3, pt4, *ts)
splitCubicAtTC (pt1, pt2, pt3, pt4, *ts)
splitCubicIntoTwoAtTC (pt1, pt2, pt3, pt4, t)
_splitQuadraticAtT (a, b, c, *ts)
_splitCubicAtT (a, b, c, d, *ts)
_splitCubicAtTC (a, b, c, d, *ts)
solveQuadratic (a, b, c, sqrt=sqrt)
solveCubic (a, b, c, d)
calcQuadraticParameters (pt1, pt2, pt3)
calcCubicParameters (pt1, pt2, pt3, pt4)
calcCubicParametersC (pt1, pt2, pt3, pt4)
calcQuadraticPoints (a, b, c)
calcCubicPoints (a, b, c, d)
calcCubicPointsC (a, b, c, d)
linePointAtT (pt1, pt2, t)
quadraticPointAtT (pt1, pt2, pt3, t)
cubicPointAtT (pt1, pt2, pt3, pt4, t)
cubicPointAtTC (pt1, pt2, pt3, pt4, t)
segmentPointAtT (seg, t)
_line_t_of_pt (s, e, pt)
_both_points_are_on_same_side_of_origin (a, b, origin)
lineLineIntersections (s1, e1, s2, e2)
_alignment_transformation (segment)
_curve_line_intersections_t (curve, line)
curveLineIntersections (curve, line)
_curve_bounds (c)
_split_segment_at_t (c, t)
_curve_curve_intersections_t (curve1, curve2, precision=1e-3, range1=None, range2=None)
_is_linelike (segment)
curveCurveIntersections (curve1, curve2)
segmentSegmentIntersections (seg1, seg2)
_segmentrepr (obj)
printSegments (segments)
Variables
COMPILED = cython.compiled
int EPSILON = 1e-9
Intersection = namedtuple("Intersection", ["pt", "t1", "t2"])
list __all__
int epsilonDigits = 6
int epsilon = 1e-10
Detailed Description
fontTools.misc.bezierTools.py -- tools for working with Bezier path segments.
Function Documentation
_alignment_transformation()
fontTools.misc.bezierTools._alignment_transformation (segment) protected
Definition at line 1232 of file bezierTools.py.
_both_points_are_on_same_side_of_origin()
fontTools.misc.bezierTools._both_points_are_on_same_side_of_origin (a, b, origin) protected
Definition at line 1148 of file bezierTools.py.
_calcCubicArcLengthCRecurse()
fontTools.misc.bezierTools._calcCubicArcLengthCRecurse (mult, p0, p1, p2, p3) protected
Definition at line 92 of file bezierTools.py.
_curve_bounds()
fontTools.misc.bezierTools._curve_bounds (c) protected
Definition at line 1293 of file bezierTools.py.
_curve_curve_intersections_t()
fontTools.misc.bezierTools._curve_curve_intersections_t (curve1, curve2, precision = 1e-3, range1 = None, range2 = None) protected
Definition at line 1313 of file bezierTools.py.
_curve_line_intersections_t()
fontTools.misc.bezierTools._curve_line_intersections_t (curve, line) protected
Definition at line 1242 of file bezierTools.py.
_dot()
fontTools.misc.bezierTools._dot (v1, v2) protected
Definition at line 137 of file bezierTools.py.
_intSecAtan()
fontTools.misc.bezierTools._intSecAtan (x) protected
Definition at line 145 of file bezierTools.py.
_is_linelike()
fontTools.misc.bezierTools._is_linelike (segment) protected
Definition at line 1380 of file bezierTools.py.
_line_t_of_pt()
fontTools.misc.bezierTools._line_t_of_pt (s, e, pt) protected
Definition at line 1134 of file bezierTools.py.
_segmentrepr()
fontTools.misc.bezierTools._segmentrepr (obj) protected
>>> _segmentrepr([1, [2, 3], [], [[2, [3, 4], [0.1, 2.2]]]])
'(1, (2, 3), (), ((2, (3, 4), (0.1, 2.2))))'
Definition at line 1472 of file bezierTools.py.
References _segmentrepr().
Referenced by _segmentrepr(), and printSegments().
_split_cubic_into_two()
fontTools.misc.bezierTools._split_cubic_into_two (p0, p1, p2, p3) protected
Definition at line 75 of file bezierTools.py.
_split_segment_at_t()
fontTools.misc.bezierTools._split_segment_at_t (c, t) protected
Definition at line 1301 of file bezierTools.py.
_splitCubicAtT()
fontTools.misc.bezierTools._splitCubicAtT (a, b, c, d, * ts) protected
Definition at line 735 of file bezierTools.py.
_splitCubicAtTC()
fontTools.misc.bezierTools._splitCubicAtTC (a, b, c, d, * ts) protected
Definition at line 785 of file bezierTools.py.
_splitQuadraticAtT()
fontTools.misc.bezierTools._splitQuadraticAtT (a, b, c, * ts) protected
Definition at line 708 of file bezierTools.py.
approximateCubicArcLength()
fontTools.misc.bezierTools.approximateCubicArcLength (pt1, pt2, pt3, pt4)
Approximates the arc length for a cubic Bezier segment.
Uses Gauss-Lobatto quadrature with n=5 points to approximate arc length.
See :func:`calcCubicArcLength` for a slower but more accurate result.
Args:
    pt1,pt2,pt3,pt4: Control points of the Bezier as 2D tuples.
Returns:
    Arc length value.
Example::
    >>> approximateCubicArcLength((0, 0), (25, 100), (75, 100), (100, 0))
    190.04332968932817
    >>> approximateCubicArcLength((0, 0), (50, 0), (100, 50), (100, 100))
    154.8852074945903
    >>> approximateCubicArcLength((0, 0), (50, 0), (100, 0), (150, 0)) # line; exact result should be 150.
    149.99999999999991
    >>> approximateCubicArcLength((0, 0), (50, 0), (100, 0), (-50, 0)) # cusp; exact result should be 150.
    136.9267662156362
    >>> approximateCubicArcLength((0, 0), (50, 0), (100, -50), (-50, 0)) # cusp
    154.80848416537057
Definition at line 332 of file bezierTools.py.
References approximateCubicArcLengthC().
approximateCubicArcLengthC()
fontTools.misc.bezierTools.approximateCubicArcLengthC (pt1, pt2, pt3, pt4)
Approximates the arc length for a cubic Bezier segment.
Args:
    pt1,pt2,pt3,pt4: Control points of the Bezier as complex numbers.
Returns:
    Arc length value.
Definition at line 376 of file bezierTools.py.
Referenced by approximateCubicArcLength().
approximateQuadraticArcLength()
fontTools.misc.bezierTools.approximateQuadraticArcLength (pt1, pt2, pt3)
Calculates the arc length for a quadratic Bezier segment.
Uses Gauss-Legendre quadrature for a branch-free approximation.
See :func:`calcQuadraticArcLength` for a slower but more accurate result.
Args:
    pt1: Start point of the Bezier as 2D tuple.
    pt2: Handle point of the Bezier as 2D tuple.
    pt3: End point of the Bezier as 2D tuple.
Returns:
    Approximate arc length value.
Definition at line 237 of file bezierTools.py.
References approximateQuadraticArcLengthC().
approximateQuadraticArcLengthC()
fontTools.misc.bezierTools.approximateQuadraticArcLengthC (pt1, pt2, pt3)
Calculates the arc length for a quadratic Bezier segment.
Uses Gauss-Legendre quadrature for a branch-free approximation.
See :func:`calcQuadraticArcLength` for a slower but more accurate result.
Args:
    pt1: Start point of the Bezier as a complex number.
    pt2: Handle point of the Bezier as a complex number.
    pt3: End point of the Bezier as a complex number.
Returns:
    Approximate arc length value.
Definition at line 265 of file bezierTools.py.
Referenced by approximateQuadraticArcLength().
calcCubicArcLength()
fontTools.misc.bezierTools.calcCubicArcLength (pt1, pt2, pt3, pt4, tolerance = 0.005)
Calculates the arc length for a cubic Bezier segment.
Whereas :func:`approximateCubicArcLength` approximates the length, this
function calculates it by "measuring", recursively dividing the curve
until the divided segments are shorter than ``tolerance``.
Args:
    pt1,pt2,pt3,pt4: Control points of the Bezier as 2D tuples.
    tolerance: Controls the precision of the calcuation.
Returns:
    Arc length value.
Definition at line 56 of file bezierTools.py.
References calcCubicArcLengthC().
calcCubicArcLengthC()
fontTools.misc.bezierTools.calcCubicArcLengthC (pt1, pt2, pt3, pt4, tolerance = 0.005)
Calculates the arc length for a cubic Bezier segment.
Args:
    pt1,pt2,pt3,pt4: Control points of the Bezier as complex numbers.
    tolerance: Controls the precision of the calcuation.
Returns:
    Arc length value.
Definition at line 115 of file bezierTools.py.
Referenced by calcCubicArcLength().
calcCubicBounds()
fontTools.misc.bezierTools.calcCubicBounds (pt1, pt2, pt3, pt4)
Calculates the bounding rectangle for a quadratic Bezier segment.
Args:
    pt1,pt2,pt3,pt4: Control points of the Bezier as 2D tuples.
Returns:
    A four-item tuple representing the bounding rectangle ``(xMin, yMin, xMax, yMax)``.
Example::
    >>> calcCubicBounds((0, 0), (25, 100), (75, 100), (100, 0))
    (0, 0, 100, 75.0)
    >>> calcCubicBounds((0, 0), (50, 0), (100, 50), (100, 100))
    (0.0, 0.0, 100, 100)
    >>> print("%f %f %f %f" % calcCubicBounds((50, 0), (0, 100), (100, 100), (50, 0)))
    35.566243 0.000000 64.433757 75.000000
Definition at line 412 of file bezierTools.py.
References solveQuadratic().
Referenced by curveLineIntersections().
calcCubicParameters()
fontTools.misc.bezierTools.calcCubicParameters (pt1, pt2, pt3, pt4)
Definition at line 956 of file bezierTools.py.
calcCubicParametersC()
fontTools.misc.bezierTools.calcCubicParametersC (pt1, pt2, pt3, pt4)
Definition at line 981 of file bezierTools.py.
calcCubicPoints()
fontTools.misc.bezierTools.calcCubicPoints (a, b, c, d)
Definition at line 1001 of file bezierTools.py.
calcCubicPointsC()
fontTools.misc.bezierTools.calcCubicPointsC (a, b, c, d)
Definition at line 1028 of file bezierTools.py.
calcQuadraticArcLength()
fontTools.misc.bezierTools.calcQuadraticArcLength (pt1, pt2, pt3)
Calculates the arc length for a quadratic Bezier segment.
Args:
    pt1: Start point of the Bezier as 2D tuple.
    pt2: Handle point of the Bezier as 2D tuple.
    pt3: End point of the Bezier as 2D tuple.
Returns:
    Arc length value.
Example::
    >>> calcQuadraticArcLength((0, 0), (0, 0), (0, 0)) # empty segment
    0.0
    >>> calcQuadraticArcLength((0, 0), (50, 0), (80, 0)) # collinear points
    80.0
    >>> calcQuadraticArcLength((0, 0), (0, 50), (0, 80)) # collinear points vertical
    80.0
    >>> calcQuadraticArcLength((0, 0), (50, 20), (100, 40)) # collinear points
    107.70329614269008
    >>> calcQuadraticArcLength((0, 0), (0, 100), (100, 0))
    154.02976155645263
    >>> calcQuadraticArcLength((0, 0), (0, 50), (100, 0))
    120.21581243984076
    >>> calcQuadraticArcLength((0, 0), (50, -10), (80, 50))
    102.53273816445825
    >>> calcQuadraticArcLength((0, 0), (40, 0), (-40, 0)) # collinear points, control point outside
    66.66666666666667
    >>> calcQuadraticArcLength((0, 0), (40, 0), (0, 0)) # collinear points, looping back
    40.0
Definition at line 151 of file bezierTools.py.
References calcQuadraticArcLengthC().
calcQuadraticArcLengthC()
fontTools.misc.bezierTools.calcQuadraticArcLengthC (pt1, pt2, pt3)
Calculates the arc length for a quadratic Bezier segment.
Args:
    pt1: Start point of the Bezier as a complex number.
    pt2: Handle point of the Bezier as a complex number.
    pt3: End point of the Bezier as a complex number.
Returns:
    Arc length value.
Definition at line 205 of file bezierTools.py.
Referenced by calcQuadraticArcLength().
calcQuadraticBounds()
fontTools.misc.bezierTools.calcQuadraticBounds (pt1, pt2, pt3)
Calculates the bounding rectangle for a quadratic Bezier segment.
Args:
    pt1: Start point of the Bezier as a 2D tuple.
    pt2: Handle point of the Bezier as a 2D tuple.
    pt3: End point of the Bezier as a 2D tuple.
Returns:
    A four-item tuple representing the bounding rectangle ``(xMin, yMin, xMax, yMax)``.
Example::
    >>> calcQuadraticBounds((0, 0), (50, 100), (100, 0))
    (0, 0, 100, 50.0)
    >>> calcQuadraticBounds((0, 0), (100, 0), (100, 100))
    (0.0, 0.0, 100, 100)
Definition at line 298 of file bezierTools.py.
Referenced by curveLineIntersections().
calcQuadraticParameters()
fontTools.misc.bezierTools.calcQuadraticParameters (pt1, pt2, pt3)
Definition at line 945 of file bezierTools.py.
calcQuadraticPoints()
fontTools.misc.bezierTools.calcQuadraticPoints (a, b, c)
Definition at line 988 of file bezierTools.py.
cubicPointAtT()
fontTools.misc.bezierTools.cubicPointAtT (pt1, pt2, pt3, pt4, t)
Finds the point at time `t` on a cubic curve.
Args:
    pt1, pt2, pt3, pt4: Coordinates of the curve as 2D tuples.
    t: The time along the curve.
Returns:
    A 2D tuple with the coordinates of the point.
Definition at line 1068 of file bezierTools.py.
Referenced by cubicPointAtTC().
cubicPointAtTC()
fontTools.misc.bezierTools.cubicPointAtTC (pt1, pt2, pt3, pt4, t)
Finds the point at time `t` on a cubic curve.
Args:
    pt1, pt2, pt3, pt4: Coordinates of the curve as complex numbers.
    t: The time along the curve.
Returns:
    A complex number with the coordinates of the point.
Definition at line 1103 of file bezierTools.py.
References cubicPointAtT(), linePointAtT(), and quadraticPointAtT().
curveCurveIntersections()
fontTools.misc.bezierTools.curveCurveIntersections (curve1, curve2)
Finds intersections between a curve and a curve.
Args:
    curve1: List of coordinates of the first curve segment as 2D tuples.
    curve2: List of coordinates of the second curve segment as 2D tuples.
Returns:
    A list of ``Intersection`` objects, each object having ``pt``, ``t1``
    and ``t2`` attributes containing the intersection point, time on first
    segment and time on second segment respectively.
Examples::
    >>> curve1 = [ (10,100), (90,30), (40,140), (220,220) ]
    >>> curve2 = [ (5,150), (180,20), (80,250), (210,190) ]
    >>> intersections = curveCurveIntersections(curve1, curve2)
    >>> len(intersections)
    3
    >>> intersections[0].pt
    (81.7831487395506, 109.88904552375288)
Definition at line 1385 of file bezierTools.py.
References curveLineIntersections(), and lineLineIntersections().
Referenced by segmentSegmentIntersections().
curveLineIntersections()
fontTools.misc.bezierTools.curveLineIntersections (curve, line)
Finds intersections between a curve and a line.
Args:
    curve: List of coordinates of the curve segment as 2D tuples.
    line: List of coordinates of the line segment as 2D tuples.
Returns:
    A list of ``Intersection`` objects, each object having ``pt``, ``t1``
    and ``t2`` attributes containing the intersection point, time on first
    segment and time on second segment respectively.
Examples::
    >>> curve = [ (100, 240), (30, 60), (210, 230), (160, 30) ]
    >>> line  = [ (25, 260), (230, 20) ]
    >>> intersections = curveLineIntersections(curve, line)
    >>> len(intersections)
    3
    >>> intersections[0].pt
    (84.9000930760723, 189.87306176459828)
Definition at line 1255 of file bezierTools.py.
References calcCubicBounds(), calcQuadraticBounds(), linePointAtT(), splitCubicAtT(), and splitQuadraticAtT().
Referenced by curveCurveIntersections(), and segmentSegmentIntersections().
lineLineIntersections()
fontTools.misc.bezierTools.lineLineIntersections (s1, e1, s2, e2)
Finds intersections between two line segments.
Args:
    s1, e1: Coordinates of the first line as 2D tuples.
    s2, e2: Coordinates of the second line as 2D tuples.
Returns:
    A list of ``Intersection`` objects, each object having ``pt``, ``t1``
    and ``t2`` attributes containing the intersection point, time on first
    segment and time on second segment respectively.
Examples::
    >>> a = lineLineIntersections( (310,389), (453, 222), (289, 251), (447, 367))
    >>> len(a)
    1
    >>> intersection = a[0]
    >>> intersection.pt
    (374.44882952482897, 313.73458370177315)
    >>> (intersection.t1, intersection.t2)
    (0.45069111555824465, 0.5408153767394238)
Definition at line 1154 of file bezierTools.py.
References solveCubic(), and solveQuadratic().
Referenced by curveCurveIntersections(), and segmentSegmentIntersections().
linePointAtT()
fontTools.misc.bezierTools.linePointAtT (pt1, pt2, t)
Finds the point at time `t` on a line.
Args:
    pt1, pt2: Coordinates of the line as 2D tuples.
    t: The time along the line.
Returns:
    A 2D tuple with the coordinates of the point.
Definition at line 1040 of file bezierTools.py.
Referenced by cubicPointAtTC(), and curveLineIntersections().
printSegments()
fontTools.misc.bezierTools.printSegments (segments)
Helper for the doctests, displaying each segment in a list of
segments on a single line as a tuple.
Definition at line 1485 of file bezierTools.py.
References _segmentrepr().
quadraticPointAtT()
fontTools.misc.bezierTools.quadraticPointAtT (pt1, pt2, pt3, t)
Finds the point at time `t` on a quadratic curve.
Args:
    pt1, pt2, pt3: Coordinates of the curve as 2D tuples.
    t: The time along the curve.
Returns:
    A 2D tuple with the coordinates of the point.
Definition at line 1053 of file bezierTools.py.
Referenced by cubicPointAtTC().
segmentPointAtT()
fontTools.misc.bezierTools.segmentPointAtT (seg, t)
Definition at line 1119 of file bezierTools.py.
segmentSegmentIntersections()
fontTools.misc.bezierTools.segmentSegmentIntersections (seg1, seg2)
Finds intersections between two segments.
Args:
    seg1: List of coordinates of the first segment as 2D tuples.
    seg2: List of coordinates of the second segment as 2D tuples.
Returns:
    A list of ``Intersection`` objects, each object having ``pt``, ``t1``
    and ``t2`` attributes containing the intersection point, time on first
    segment and time on second segment respectively.
Examples::
    >>> curve1 = [ (10,100), (90,30), (40,140), (220,220) ]
    >>> curve2 = [ (5,150), (180,20), (80,250), (210,190) ]
    >>> intersections = segmentSegmentIntersections(curve1, curve2)
    >>> len(intersections)
    3
    >>> intersections[0].pt
    (81.7831487395506, 109.88904552375288)
    >>> curve3 = [ (100, 240), (30, 60), (210, 230), (160, 30) ]
    >>> line  = [ (25, 260), (230, 20) ]
    >>> intersections = segmentSegmentIntersections(curve3, line)
    >>> len(intersections)
    3
    >>> intersections[0].pt
    (84.9000930760723, 189.87306176459828)
Definition at line 1424 of file bezierTools.py.
References curveCurveIntersections(), curveLineIntersections(), and lineLineIntersections().
solveCubic()
fontTools.misc.bezierTools.solveCubic (a, b, c, d)
Solve a cubic equation.
Solves *a*x*x*x + b*x*x + c*x + d = 0* where a, b, c and d are real.
Args:
    a: coefficient of *x*
    b: coefficient of *x*
    c: coefficient of *x*
    d: constant term
Returns:
    A list of roots. Note that the returned list is neither guaranteed to
    be sorted nor to contain unique values!
Examples::
    >>> solveCubic(1, 1, -6, 0)
    [-3.0, -0.0, 2.0]
    >>> solveCubic(-10.0, -9.0, 48.0, -29.0)
    [-2.9, 1.0, 1.0]
    >>> solveCubic(-9.875, -9.0, 47.625, -28.75)
    [-2.911392, 1.0, 1.0]
    >>> solveCubic(1.0, -4.5, 6.75, -3.375)
    [1.5, 1.5, 1.5]
    >>> solveCubic(-12.0, 18.0, -9.0, 1.50023651123)
    [0.5, 0.5, 0.5]
    >>> solveCubic(
    ...     9.0, 0.0, 0.0, -7.62939453125e-05
    ... ) == [-0.0, -0.0, -0.0]
    True
Definition at line 848 of file bezierTools.py.
References solveQuadratic().
Referenced by lineLineIntersections(), and splitCubic().
solveQuadratic()
fontTools.misc.bezierTools.solveQuadratic (a, b, c, sqrt = sqrt)
Solve a quadratic equation.
Solves *a*x*x + b*x + c = 0* where a, b and c are real.
Args:
    a: coefficient of *x*
    b: coefficient of *x*
    c: constant term
Returns:
    A list of roots. Note that the returned list is neither guaranteed to
    be sorted nor to contain unique values!
Definition at line 815 of file bezierTools.py.
Referenced by calcCubicBounds(), lineLineIntersections(), solveCubic(), and splitQuadratic().
splitCubic()
fontTools.misc.bezierTools.splitCubic (pt1, pt2, pt3, pt4, where, isHorizontal)
Split a cubic Bezier curve at a given coordinate.
Args:
    pt1,pt2,pt3,pt4: Control points of the Bezier as 2D tuples.
    where: Position at which to split the curve.
    isHorizontal: Direction of the ray splitting the curve. If true,
        ``where`` is interpreted as a Y coordinate; if false, then
        ``where`` is interpreted as an X coordinate.
Returns:
    A list of two curve segments (each curve segment being four 2D tuples)
    if the curve was successfully split, or a list containing the original
    curve.
Example::
    >>> printSegments(splitCubic((0, 0), (25, 100), (75, 100), (100, 0), 150, False))
    ((0, 0), (25, 100), (75, 100), (100, 0))
    >>> printSegments(splitCubic((0, 0), (25, 100), (75, 100), (100, 0), 50, False))
    ((0, 0), (12.5, 50), (31.25, 75), (50, 75))
    ((50, 75), (68.75, 75), (87.5, 50), (100, 0))
    >>> printSegments(splitCubic((0, 0), (25, 100), (75, 100), (100, 0), 25, True))
    ((0, 0), (2.29379, 9.17517), (4.79804, 17.5085), (7.47414, 25))
    ((7.47414, 25), (31.2886, 91.6667), (68.7114, 91.6667), (92.5259, 25))
    ((92.5259, 25), (95.202, 17.5085), (97.7062, 9.17517), (100, 1.77636e-15))
Definition at line 552 of file bezierTools.py.
References solveCubic().
splitCubicAtT()
fontTools.misc.bezierTools.splitCubicAtT (pt1, pt2, pt3, pt4, * ts)
Split a cubic Bezier curve at one or more values of t.
Args:
    pt1,pt2,pt3,pt4: Control points of the Bezier as 2D tuples.
    *ts: Positions at which to split the curve.
Returns:
    A list of curve segments (each curve segment being four 2D tuples).
Examples::
    >>> printSegments(splitCubicAtT((0, 0), (25, 100), (75, 100), (100, 0), 0.5))
    ((0, 0), (12.5, 50), (31.25, 75), (50, 75))
    ((50, 75), (68.75, 75), (87.5, 50), (100, 0))
    >>> printSegments(splitCubicAtT((0, 0), (25, 100), (75, 100), (100, 0), 0.5, 0.75))
    ((0, 0), (12.5, 50), (31.25, 75), (50, 75))
    ((50, 75), (59.375, 75), (68.75, 68.75), (77.3438, 56.25))
    ((77.3438, 56.25), (85.9375, 43.75), (93.75, 25), (100, 0))
Definition at line 613 of file bezierTools.py.
Referenced by curveLineIntersections().
splitCubicAtTC()
fontTools.misc.bezierTools.splitCubicAtTC (pt1, pt2, pt3, pt4, * ts)
Split a cubic Bezier curve at one or more values of t.
Args:
    pt1,pt2,pt3,pt4: Control points of the Bezier as complex numbers..
    *ts: Positions at which to split the curve.
Yields:
    Curve segments (each curve segment being four complex numbers).
Definition at line 654 of file bezierTools.py.
splitCubicIntoTwoAtTC()
fontTools.misc.bezierTools.splitCubicIntoTwoAtTC (pt1, pt2, pt3, pt4, t)
Split a cubic Bezier curve at t.
Args:
    pt1,pt2,pt3,pt4: Control points of the Bezier as complex numbers.
    t: Position at which to split the curve.
Returns:
    A tuple of two curve segments (each curve segment being four complex numbers).
Definition at line 682 of file bezierTools.py.
splitLine()
fontTools.misc.bezierTools.splitLine (pt1, pt2, where, isHorizontal)
Split a line at a given coordinate.
Args:
    pt1: Start point of line as 2D tuple.
    pt2: End point of line as 2D tuple.
    where: Position at which to split the line.
    isHorizontal: Direction of the ray splitting the line. If true,
        ``where`` is interpreted as a Y coordinate; if false, then
        ``where`` is interpreted as an X coordinate.
Returns:
    A list of two line segments (each line segment being two 2D tuples)
    if the line was successfully split, or a list containing the original
    line.
Example::
    >>> printSegments(splitLine((0, 0), (100, 100), 50, True))
    ((0, 0), (50, 50))
    ((50, 50), (100, 100))
    >>> printSegments(splitLine((0, 0), (100, 100), 100, True))
    ((0, 0), (100, 100))
    >>> printSegments(splitLine((0, 0), (100, 100), 0, True))
    ((0, 0), (0, 0))
    ((0, 0), (100, 100))
    >>> printSegments(splitLine((0, 0), (100, 100), 0, False))
    ((0, 0), (0, 0))
    ((0, 0), (100, 100))
    >>> printSegments(splitLine((100, 0), (0, 0), 50, False))
    ((100, 0), (50, 0))
    ((50, 0), (0, 0))
    >>> printSegments(splitLine((0, 100), (0, 0), 50, True))
    ((0, 100), (0, 50))
    ((0, 50), (0, 0))
Definition at line 450 of file bezierTools.py.
splitQuadratic()
fontTools.misc.bezierTools.splitQuadratic (pt1, pt2, pt3, where, isHorizontal)
Split a quadratic Bezier curve at a given coordinate.
Args:
    pt1,pt2,pt3: Control points of the Bezier as 2D tuples.
    where: Position at which to split the curve.
    isHorizontal: Direction of the ray splitting the curve. If true,
        ``where`` is interpreted as a Y coordinate; if false, then
        ``where`` is interpreted as an X coordinate.
Returns:
    A list of two curve segments (each curve segment being three 2D tuples)
    if the curve was successfully split, or a list containing the original
    curve.
Example::
    >>> printSegments(splitQuadratic((0, 0), (50, 100), (100, 0), 150, False))
    ((0, 0), (50, 100), (100, 0))
    >>> printSegments(splitQuadratic((0, 0), (50, 100), (100, 0), 50, False))
    ((0, 0), (25, 50), (50, 50))
    ((50, 50), (75, 50), (100, 0))
    >>> printSegments(splitQuadratic((0, 0), (50, 100), (100, 0), 25, False))
    ((0, 0), (12.5, 25), (25, 37.5))
    ((25, 37.5), (62.5, 75), (100, 0))
    >>> printSegments(splitQuadratic((0, 0), (50, 100), (100, 0), 25, True))
    ((0, 0), (7.32233, 14.6447), (14.6447, 25))
    ((14.6447, 25), (50, 75), (85.3553, 25))
    ((85.3553, 25), (92.6777, 14.6447), (100, -7.10543e-15))
    >>> # XXX I'm not at all sure if the following behavior is desirable:
    >>> printSegments(splitQuadratic((0, 0), (50, 100), (100, 0), 50, True))
    ((0, 0), (25, 50), (50, 50))
    ((50, 50), (50, 50), (50, 50))
    ((50, 50), (75, 50), (100, 0))
Definition at line 507 of file bezierTools.py.
References solveQuadratic().
splitQuadraticAtT()
fontTools.misc.bezierTools.splitQuadraticAtT (pt1, pt2, pt3, * ts)
Split a quadratic Bezier curve at one or more values of t.
Args:
    pt1,pt2,pt3: Control points of the Bezier as 2D tuples.
    *ts: Positions at which to split the curve.
Returns:
    A list of curve segments (each curve segment being three 2D tuples).
Examples::
    >>> printSegments(splitQuadraticAtT((0, 0), (50, 100), (100, 0), 0.5))
    ((0, 0), (25, 50), (50, 50))
    ((50, 50), (75, 50), (100, 0))
    >>> printSegments(splitQuadraticAtT((0, 0), (50, 100), (100, 0), 0.5, 0.75))
    ((0, 0), (25, 50), (50, 50))
    ((50, 50), (62.5, 50), (75, 37.5))
    ((75, 37.5), (87.5, 25), (100, 0))
Definition at line 589 of file bezierTools.py.
Referenced by curveLineIntersections().
Variable Documentation
__all__
list fontTools.misc.bezierTools.__all__ private
Initial value:
=  [
    "approximateCubicArcLength",
    "approximateCubicArcLengthC",
    "approximateQuadraticArcLength",
    "approximateQuadraticArcLengthC",
    "calcCubicArcLength",
    "calcCubicArcLengthC",
    "calcQuadraticArcLength",
    "calcQuadraticArcLengthC",
    "calcCubicBounds",
    "calcQuadraticBounds",
    "splitLine",
    "splitQuadratic",
    "splitCubic",
    "splitQuadraticAtT",
    "splitCubicAtT",
    "splitCubicAtTC",
    "splitCubicIntoTwoAtTC",
    "solveQuadratic",
    "solveCubic",
    "quadraticPointAtT",
    "cubicPointAtT",
    "cubicPointAtTC",
    "linePointAtT",
    "segmentPointAtT",
    "lineLineIntersections",
    "curveLineIntersections",
    "curveCurveIntersections",
    "segmentSegmentIntersections",
]
Definition at line 24 of file bezierTools.py.
COMPILED
fontTools.misc.bezierTools.COMPILED = cython.compiled
Definition at line 15 of file bezierTools.py.
EPSILON
int fontTools.misc.bezierTools.EPSILON = 1e-9
Definition at line 18 of file bezierTools.py.
epsilon
int fontTools.misc.bezierTools.epsilon = 1e-10
Definition at line 130 of file bezierTools.py.
epsilonDigits
int fontTools.misc.bezierTools.epsilonDigits = 6
Definition at line 129 of file bezierTools.py.
Intersection
fontTools.misc.bezierTools.Intersection = namedtuple("Intersection", ["pt", "t1", "t2"])
Definition at line 21 of file bezierTools.py.