Code Cloning Analysis: matplotlib.hatch.NorthEastHatch Class Reference
matplotlib.hatch.NorthEastHatch Class Reference
Public Member Functions
__init__ (self, hatch, density)
set_vertices_and_codes (self, vertices, codes)
Public Attributes
num_lines
tuple num_vertices = (self.num_lines + 1) * 2
Detailed Description
Definition at line 48 of file hatch.py.
Constructor & Destructor Documentation
__init__()
matplotlib.hatch.NorthEastHatch.__init__ (self, hatch, density)
Definition at line 49 of file hatch.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
set_vertices_and_codes()
matplotlib.hatch.NorthEastHatch.set_vertices_and_codes (self, vertices, codes)
Definition at line 57 of file hatch.py.
Member Data Documentation
num_lines
matplotlib.hatch.NorthEastHatch.num_lines
Initial value:
=  int(
            (hatch.count('/') + hatch.count('x') + hatch.count('X')) * density)
Definition at line 50 of file hatch.py.
num_vertices
tuple matplotlib.hatch.NorthEastHatch.num_vertices = (self.num_lines + 1) * 2
Definition at line 53 of file hatch.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/hatch.py