Code Cloning Analysis: numpy.core.tests.test_numeric.TestKeepdims.sub_array Class Reference
numpy.core.tests.test_numeric.TestKeepdims.sub_array Class Reference
Public Member Functions
sum (self, axis=None, dtype=None, out=None)
Detailed Description
Definition at line 3569 of file test_numeric.py.
Member Function Documentation
sum()
numpy.core.tests.test_numeric.TestKeepdims.sub_array.sum (self, axis = None, dtype = None, out = None)
Definition at line 3570 of file test_numeric.py.
Referenced by numpy.ma.core.MaskedArray.mean(), PIL.ImageStat.Stat.mean(), numpy.core.tests.test_simd._SIMD_ALL.test_arithmetic_reduce_sum(), and PIL.ImageStat.Stat.var().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/core/tests/test_numeric.py