Code Cloning Analysis: scipy.stats.tests.test_distributions.TestStudentizedRange Class Reference
scipy.stats.tests.test_distributions.TestStudentizedRange Class Reference
Public Member Functions
test_cdf_against_tables (self)
test_ppf_against_tables (self)
test_cdf_against_mp (self, case_result)
test_pdf_against_mp (self, case_result)
test_moment_against_mp (self, case_result)
test_pdf_integration (self)
test_pdf_against_cdf (self)
test_cdf_against_r (self, r_case_result)
test_moment_vectorization (self)
test_fitstart_valid (self)
test_infinite_df (self)
test_df_cutoff (self)
test_clipping (self)
Static Public Attributes
list q05
list q01
list q001
qs = np.concatenate((q05, q01, q001))
list ps = [.95, .99, .999]
list vs = [1, 3, 10, 20, 120, np.inf]
list ks = [2, 8, 14, 20]
data = list(zip(product(ps, vs, ks), qs))
list r_data
path_prefix = os.path.dirname(__file__)
str relative_path = "data/studentized_range_mpmath_ref.json"
pregenerated_data = json.load(file)
Detailed Description
Definition at line 6907 of file test_distributions.py.
Member Function Documentation
test_cdf_against_mp()
scipy.stats.tests.test_distributions.TestStudentizedRange.test_cdf_against_mp (self, case_result)
Definition at line 6969 of file test_distributions.py.
test_cdf_against_r()
scipy.stats.tests.test_distributions.TestStudentizedRange.test_cdf_against_r (self, r_case_result)
Definition at line 7030 of file test_distributions.py.
test_cdf_against_tables()
scipy.stats.tests.test_distributions.TestStudentizedRange.test_cdf_against_tables (self)
Definition at line 6950 of file test_distributions.py.
test_clipping()
scipy.stats.tests.test_distributions.TestStudentizedRange.test_clipping (self)
Definition at line 7093 of file test_distributions.py.
test_df_cutoff()
scipy.stats.tests.test_distributions.TestStudentizedRange.test_df_cutoff (self)
Definition at line 7072 of file test_distributions.py.
test_fitstart_valid()
scipy.stats.tests.test_distributions.TestStudentizedRange.test_fitstart_valid (self)
Definition at line 7054 of file test_distributions.py.
test_infinite_df()
scipy.stats.tests.test_distributions.TestStudentizedRange.test_infinite_df (self)
Definition at line 7061 of file test_distributions.py.
test_moment_against_mp()
scipy.stats.tests.test_distributions.TestStudentizedRange.test_moment_against_mp (self, case_result)
Definition at line 6993 of file test_distributions.py.
test_moment_vectorization()
scipy.stats.tests.test_distributions.TestStudentizedRange.test_moment_vectorization (self)
Definition at line 7039 of file test_distributions.py.
test_pdf_against_cdf()
scipy.stats.tests.test_distributions.TestStudentizedRange.test_pdf_against_cdf (self)
Definition at line 7014 of file test_distributions.py.
test_pdf_against_mp()
scipy.stats.tests.test_distributions.TestStudentizedRange.test_pdf_against_mp (self, case_result)
Definition at line 6980 of file test_distributions.py.
test_pdf_integration()
scipy.stats.tests.test_distributions.TestStudentizedRange.test_pdf_integration (self)
Definition at line 7007 of file test_distributions.py.
test_ppf_against_tables()
scipy.stats.tests.test_distributions.TestStudentizedRange.test_ppf_against_tables (self)
Definition at line 6957 of file test_distributions.py.
Member Data Documentation
data
scipy.stats.tests.test_distributions.TestStudentizedRange.data = list(zip(product(ps, vs, ks), qs)) static
Definition at line 6938 of file test_distributions.py.
Referenced by pandas.tests.extension.decimal.array.DecimalArray._reduce(), matplotlib.backends.backend_svg.XMLWriter.element(), numpy.core._internal._ctypes.get_data(), and PIL.GifImagePlugin.GifImageFile.seek().
ks
list scipy.stats.tests.test_distributions.TestStudentizedRange.ks = [2, 8, 14, 20] static
Definition at line 6936 of file test_distributions.py.
path_prefix
scipy.stats.tests.test_distributions.TestStudentizedRange.path_prefix = os.path.dirname(__file__) static
Definition at line 6963 of file test_distributions.py.
pregenerated_data
scipy.stats.tests.test_distributions.TestStudentizedRange.pregenerated_data = json.load(file) static
Definition at line 6966 of file test_distributions.py.
ps
list scipy.stats.tests.test_distributions.TestStudentizedRange.ps = [.95, .99, .999] static
Definition at line 6934 of file test_distributions.py.
q001
list scipy.stats.tests.test_distributions.TestStudentizedRange.q001 static
Initial value:
=  [900.3, 2272, 2718, 2980,
            18.28, 34.12, 39.69, 43.05,
            6.487, 9.352, 10.39, 11.03,
            5.444, 7.313, 7.966, 8.370,
            4.772, 6.039, 6.448, 6.695,
            4.654, 5.823, 6.191, 6.411]
Definition at line 6927 of file test_distributions.py.
q01
list scipy.stats.tests.test_distributions.TestStudentizedRange.q01 static
Initial value:
=  [90.03, 227.2, 271.8, 298.0,
           8.261, 15.64, 18.22, 19.77,
           4.482, 6.875, 7.712, 8.226,
           4.024, 5.839, 6.450, 6.823,
           3.702, 5.118, 5.562, 5.827,
           3.643, 4.987, 5.400, 5.645]
Definition at line 6921 of file test_distributions.py.
q05
list scipy.stats.tests.test_distributions.TestStudentizedRange.q05 static
Initial value:
=  [17.97, 45.40, 54.33, 59.56,
           4.501, 8.853, 10.35, 11.24,
           3.151, 5.305, 6.028, 6.467,
           2.950, 4.768, 5.357, 5.714,
           2.800, 4.363, 4.842, 5.126,
           2.772, 4.286, 4.743, 5.012]
Definition at line 6915 of file test_distributions.py.
qs
scipy.stats.tests.test_distributions.TestStudentizedRange.qs = np.concatenate((q05, q01, q001)) static
Definition at line 6933 of file test_distributions.py.
r_data
list scipy.stats.tests.test_distributions.TestStudentizedRange.r_data static
Initial value:
=  [
        (0.1, 3, 9001, 0.002752818526842),
        (1, 10, 1000, 0.000526142388912),
        (1, 3, np.inf, 0.240712641229283),
        (4, 3, np.inf, 0.987012338626815),
        (1, 10, np.inf, 0.000519869467083),
    ]
Definition at line 6942 of file test_distributions.py.
relative_path
str scipy.stats.tests.test_distributions.TestStudentizedRange.relative_path = "data/studentized_range_mpmath_ref.json" static
Definition at line 6964 of file test_distributions.py.
vs
list scipy.stats.tests.test_distributions.TestStudentizedRange.vs = [1, 3, 10, 20, 120, np.inf] static
Definition at line 6935 of file test_distributions.py.
Referenced by sklearn.neural_network._stochastic_optimizers.AdamOptimizer._get_updates().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/stats/tests/test_distributions.py