Code Cloning Analysis: numpy.lib.utils Namespace Reference
numpy.lib.utils Namespace Reference
Classes
class _Deprecate
Functions
show_runtime ()
get_include ()
_get_indent (lines)
deprecate (*args, **kwargs)
deprecate_with_doc (msg)
byte_bounds (a)
who (vardict=None)
_split_line (name, arguments, width)
_makenamedict (module='numpy')
_info (obj, output=None)
info (object=None, maxwidth=76, output=None, toplevel='numpy')
source (object, output=sys.stdout)
lookfor (what, module=None, import_modules=True, regenerate=False, output=None)
_lookfor_generate_cache (module, import_modules, regenerate)
_getmembers (item)
safe_eval (source)
_median_nancheck (data, result, axis)
_opt_info ()
drop_metadata (dtype)
Variables
list __all__
_namedict = None
_dictlist = None
dict _lookfor_caches = {}
_function_signature_re = re.compile(r"[a-z0-9_]+\‍(.*[,=].*\‍)", re.I)
Function Documentation
_get_indent()
numpy.lib.utils._get_indent (lines) protected
Determines the leading whitespace that could be removed from all the lines.
Definition at line 172 of file utils.py.
References numpy.core.fromnumeric.min().
Referenced by numpy.lib.utils._Deprecate.__call__().
_getmembers()
numpy.lib.utils._getmembers (item) protected
Definition at line 1017 of file utils.py.
_info()
numpy.lib.utils._info (obj, output = None) protected
Provide information about ndarray obj.
Parameters
----------
obj : ndarray
    Must be ndarray, not checked.
output
    Where printed output goes.
Notes
-----
Copied over from the numarray module prior to its removal.
Adapted somewhat as only numpy is an option now.
Called by info.
Definition at line 474 of file utils.py.
Referenced by info().
_lookfor_generate_cache()
numpy.lib.utils._lookfor_generate_cache (module, import_modules, regenerate) protected
Generate docstring cache for given module.
Parameters
----------
module : str, None, module
    Module for which to generate docstring cache
import_modules : bool
    Whether to import sub-modules in packages.
regenerate : bool
    Re-generate the docstring cache
Returns
-------
cache : dict {obj_full_name: (docstring, kind, index), ...}
    Docstring cache for the module, either cached one (regenerate=False)
    or newly generated.
Definition at line 878 of file utils.py.
References _lookfor_generate_cache().
Referenced by _lookfor_generate_cache(), and lookfor().
_makenamedict()
numpy.lib.utils._makenamedict (module = 'numpy') protected
Definition at line 454 of file utils.py.
_median_nancheck()
numpy.lib.utils._median_nancheck (data, result, axis) protected
Utility function to check median result from data for NaN values at the end
and return NaN in that case. Input result can also be a MaskedArray.
Parameters
----------
data : array
    Sorted input data to median function
result : Array or MaskedArray
    Result of median function.
axis : int
    Axis along which the median was computed.
Returns
-------
result : scalar or ndarray
    Median or NaN in axes which contained NaN in the input.  If the input
    was an array, NaN will be inserted in-place.  If a scalar, either the
    input itself or a scalar NaN.
Definition at line 1081 of file utils.py.
_opt_info()
numpy.lib.utils._opt_info () protected
Returns a string contains the supported CPU features by the current build.
The string format can be explained as follows:
    - dispatched features that are supported by the running machine
      end with `*`.
    - dispatched features that are "not" supported by the running machine
      end with `?`.
    - remained features are representing the baseline.
Definition at line 1123 of file utils.py.
_split_line()
numpy.lib.utils._split_line (name, arguments, width) protected
Definition at line 430 of file utils.py.
byte_bounds()
numpy.lib.utils.byte_bounds (a)
Returns pointers to the end-points of an array.
Parameters
----------
a : ndarray
    Input array. It must conform to the Python-side of the array
    interface.
Returns
-------
(low, high) : tuple of 2 integers
    The first integer is the first byte of the array, the second
    integer is just past the last byte of the array.  If `a` is not
    contiguous it will not use every byte between the (`low`, `high`)
    values.
Examples
--------
>>> I = np.eye(2, dtype='f'); I.dtype
dtype('float32')
>>> low, high = np.byte_bounds(I)
>>> high - low == I.size*I.itemsize
True
>>> I = np.eye(2); I.dtype
dtype('float64')
>>> low, high = np.byte_bounds(I)
>>> high - low == I.size*I.itemsize
True
Definition at line 270 of file utils.py.
deprecate()
numpy.lib.utils.deprecate (* args, ** kwargs)
Issues a DeprecationWarning, adds warning to `old_name`'s
docstring, rebinds ``old_name.__name__`` and returns the new
function object.
This function may also be used as a decorator.
Parameters
----------
func : function
    The function to be deprecated.
old_name : str, optional
    The name of the function to be deprecated. Default is None, in
    which case the name of `func` is used.
new_name : str, optional
    The new name for the function. Default is None, in which case the
    deprecation message is that `old_name` is deprecated. If given, the
    deprecation message is that `old_name` is deprecated and `new_name`
    should be used instead.
message : str, optional
    Additional explanation of the deprecation.  Displayed in the
    docstring after the warning.
Returns
-------
old_func : function
    The deprecated function.
Examples
--------
Note that ``olduint`` returns a value after printing Deprecation
Warning:
>>> olduint = np.deprecate(np.uint)
DeprecationWarning: `uint64` is deprecated! # may vary
>>> olduint(6)
6
Definition at line 186 of file utils.py.
Referenced by numpy.lib.tests.test_utils.old_func4(), numpy.lib.tests.test_utils.old_func5(), and numpy.lib.tests.test_utils.old_func6().
deprecate_with_doc()
numpy.lib.utils.deprecate_with_doc (msg)
Deprecates a function and includes the deprecation in its docstring.
This function is used as a decorator. It returns an object that can be
used to issue a DeprecationWarning, by passing the to-be decorated
function as argument, this adds warning to the to-be decorated function's
docstring and returns the new function object.
See Also
--------
deprecate : Decorate a function such that it issues a `DeprecationWarning`
Parameters
----------
msg : str
    Additional explanation of the deprecation. Displayed in the
    docstring after the warning.
Returns
-------
obj : object
Definition at line 239 of file utils.py.
drop_metadata()
numpy.lib.utils.drop_metadata (dtype)
Returns the dtype unchanged if it contained no metadata or a copy of the
dtype if it (or any of its structure dtypes) contained metadata.
This utility is used by `np.save` and `np.savez` to drop metadata before
saving.
.. note::
    Due to its limitation this function may move to a more appropriate
    home or change in the future and is considered semi-public API only.
.. warning::
    This function does not preserve more strange things like record dtypes
    and user dtypes may simply return the wrong thing.  If you need to be
    sure about the latter, check the result with:
    ``np.can_cast(new_dtype, dtype, casting="no")``.
Definition at line 1151 of file utils.py.
References drop_metadata().
Referenced by drop_metadata(), and numpy.lib.format.dtype_to_descr().
get_include()
numpy.lib.utils.get_include ()
Return the directory that contains the NumPy \\*.h header files.
Extension modules that need to compile against NumPy should use this
function to locate the appropriate include directory.
Notes
-----
When using ``distutils``, for example in ``setup.py``::
    import numpy as np
    ...
    Extension('extension_name', ...
            include_dirs=[np.get_include()])
    ...
Definition at line 75 of file utils.py.
info()
numpy.lib.utils.info (object = None, maxwidth = 76, output = None, toplevel = 'numpy')
Get help information for an array, function, class, or module.
Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is
    an `ndarray` instance, information about the array is printed.
    If `object` is a numpy object, its docstring is given. If it is
    a string, available modules are searched for matching objects.
    If None, information about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``None``, in which case ``sys.stdout`` will be used.
    The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.
See Also
--------
source, lookfor
Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.
Examples
--------
>>> np.info(np.polyval) # doctest: +SKIP
   polyval(p, x)
     Evaluate the polynomial p at x.
     ...
When using a string for `object` it is possible to get multiple results.
>>> np.info('fft') # doctest: +SKIP
     *** Found in numpy ***
Core FFT routines
...
     *** Found in numpy.fft ***
 fft(a, n=None, axis=-1)
...
     *** Repeat reference found in numpy.fft.fftpack ***
     *** Total of 3 references found. ***
When the argument is an array, information about the array is printed.
>>> a = np.array([[1 + 2j, 3, -4], [-5j, 6, 0]], dtype=np.complex64)
>>> np.info(a)
class:  ndarray
shape:  (2, 3)
strides:  (24, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x562b6e0d2860  # may vary
byteorder:  little
byteswap:  False
type: complex64
Definition at line 529 of file utils.py.
References _info().
lookfor()
numpy.lib.utils.lookfor (what, module = None, import_modules = True, regenerate = False, output = None)
Do a keyword search on docstrings.
A list of objects that matched the search is displayed,
sorted by relevance. All given keywords need to be found in the
docstring for it to be returned as a result, but the order does
not matter.
Parameters
----------
what : str
    String containing words to look for.
module : str or list, optional
    Name of module(s) whose docstrings to go through.
import_modules : bool, optional
    Whether to import sub-modules in packages. Default is True.
regenerate : bool, optional
    Whether to re-generate the docstring cache. Default is False.
output : file-like, optional
    File-like object to write the output to. If omitted, use a pager.
See Also
--------
source, info
Notes
-----
Relevance is determined only roughly, by checking if the keywords occur
in the function name, at the start of a docstring, etc.
Examples
--------
>>> np.lookfor('binary representation') # doctest: +SKIP
Search results for 'binary representation'
------------------------------------------
numpy.binary_repr
    Return the binary representation of the input number as a string.
numpy.core.setup_common.long_double_representation
    Given a binary dump as given by GNU od -b, look for long double
numpy.base_repr
    Return a string representation of a number in the given base system.
...
Definition at line 755 of file utils.py.
References _lookfor_generate_cache(), numpy.core.fromnumeric.all(), numpy.core.fromnumeric.max(), numpy.lib.shape_base.split(), and numpy.core.fromnumeric.sum().
safe_eval()
numpy.lib.utils.safe_eval (source)
Protected string evaluation.
Evaluate a string containing a Python literal expression without
allowing the execution of arbitrary non-literal code.
.. warning::
    This function is identical to :py:meth:`ast.literal_eval` and
    has the same security implications.  It may not always be safe
    to evaluate large input strings.
Parameters
----------
source : str
    The string to evaluate.
Returns
-------
obj : object
   The result of evaluating `source`.
Raises
------
SyntaxError
    If the code has invalid Python syntax, or if it contains
    non-literal code.
Examples
--------
>>> np.safe_eval('1')
1
>>> np.safe_eval('[1, 2, 3]')
[1, 2, 3]
>>> np.safe_eval('{"foo": ("bar", 10.0)}')
{'foo': ('bar', 10.0)}
>>> np.safe_eval('import os')
Traceback (most recent call last):
  ...
SyntaxError: invalid syntax
>>> np.safe_eval('open("/home/user/.ssh/id_dsa").read()')
Traceback (most recent call last):
  ...
ValueError: malformed node or string: <_ast.Call object at 0x...>
Definition at line 1027 of file utils.py.
Referenced by numpy.lib.format._read_array_header().
show_runtime()
numpy.lib.utils.show_runtime ()
Print information about various resources in the system
including available intrinsic support and BLAS/LAPACK library
in use
.. versionadded:: 1.24.0
See Also
--------
show_config : Show libraries in the system on which NumPy was built.
Notes
-----
1. Information is derived with the help of `threadpoolctl <https://pypi.org/project/threadpoolctl/>`_
   library if available.
2. SIMD related information is derived from ``__cpu_features__``,
   ``__cpu_baseline__`` and ``__cpu_dispatch__``
Definition at line 22 of file utils.py.
source()
numpy.lib.utils.source (object, output = sys.stdout)
Print or write to a file the source code for a NumPy object.
The source code is only returned for objects written in Python. Many
functions and classes are defined in C and will therefore not return
useful information.
Parameters
----------
object : numpy object
    Input object. This can be any object (function, class, module,
    ...).
output : file object, optional
    If `output` not supplied then source code is printed to screen
    (sys.stdout).  File object must be created with either write 'w' or
    append 'a' modes.
See Also
--------
lookfor, info
Examples
--------
>>> np.source(np.interp)                        #doctest: +SKIP
In file: /usr/lib/python2.6/dist-packages/numpy/lib/function_base.py
def interp(x, xp, fp, left=None, right=None):
    \"\"\".... (full docstring printed)\"\"\"
    if isinstance(x, (float, int, number)):
        return compiled_interp([x], xp, fp, left, right).item()
    else:
        return compiled_interp(x, xp, fp, left, right)
The source code is only returned for objects written in Python.
>>> np.source(np.array)                         #doctest: +SKIP
Not available for this object.
Definition at line 696 of file utils.py.
who()
numpy.lib.utils.who (vardict = None)
Print the NumPy arrays in the given dictionary.
If there is no dictionary passed in or `vardict` is None then returns
NumPy arrays in the globals() dictionary (all NumPy arrays in the
namespace).
Parameters
----------
vardict : dict, optional
    A dictionary possibly containing ndarrays.  Default is globals().
Returns
-------
out : None
    Returns 'None'.
Notes
-----
Prints out the name, shape, bytes and type of all of the ndarrays
present in `vardict`.
Examples
--------
>>> a = np.arange(10)
>>> b = np.ones(20)
>>> np.who()
Name            Shape            Bytes            Type
===========================================================
a               10               80               int64
b               20               160              float64
Upper bound on total bytes  =       240
>>> d = {'x': np.arange(2.0), 'y': np.arange(3.0), 'txt': 'Some str',
... 'idx':5}
>>> np.who(d)
Name            Shape            Bytes            Type
===========================================================
x               2                16               float64
y               3                24               float64
Upper bound on total bytes  =       40
Definition at line 327 of file utils.py.
References numpy.core.fromnumeric.max().
Variable Documentation
__all__
list numpy.lib.utils.__all__ private
Initial value:
=  [
    'issubclass_', 'issubsctype', 'issubdtype', 'deprecate',
    'deprecate_with_doc', 'get_include', 'info', 'source', 'who',
    'lookfor', 'byte_bounds', 'safe_eval', 'show_runtime'
    ]
Definition at line 15 of file utils.py.
_dictlist
numpy.lib.utils._dictlist = None protected
Definition at line 450 of file utils.py.
_function_signature_re
numpy.lib.utils._function_signature_re = re.compile(r"[a-z0-9_]+\‍(.*[,=].*\‍)", re.I) protected
Definition at line 751 of file utils.py.
_lookfor_caches
dict numpy.lib.utils._lookfor_caches = {} protected
Definition at line 747 of file utils.py.
_namedict
numpy.lib.utils._namedict = None protected
Definition at line 449 of file utils.py.