Code Cloning Analysis: sklearn.linear_model.tests.test_sgd._SparseSGDClassifier Class Reference
sklearn.linear_model.tests.test_sgd._SparseSGDClassifier Class Reference
Public Member Functions
fit (self, X, y, *args, **kw)
partial_fit (self, X, y, *args, **kw)
decision_function (self, X)
predict_proba (self, X)
Public Member Functions inherited from sklearn.linear_model._stochastic_gradient.SGDClassifier
__init__ (self, loss="hinge", *, penalty="l2", alpha=0.0001, l1_ratio=0.15, fit_intercept=True, max_iter=1000, tol=1e-3, shuffle=True, verbose=0, epsilon=DEFAULT_EPSILON, n_jobs=None, random_state=None, learning_rate="optimal", eta0=0.0, power_t=0.5, early_stopping=False, validation_fraction=0.1, n_iter_no_change=5, class_weight=None, warm_start=False, average=False)
predict_log_proba (self, X)
Public Member Functions inherited from sklearn.linear_model._stochastic_gradient.BaseSGDClassifier
__init__ (self, loss="hinge", *, penalty="l2", alpha=0.0001, l1_ratio=0.15, fit_intercept=True, max_iter=1000, tol=1e-3, shuffle=True, verbose=0, epsilon=DEFAULT_EPSILON, n_jobs=None, random_state=None, learning_rate="optimal", eta0=0.0, power_t=0.5, early_stopping=False, validation_fraction=0.1, n_iter_no_change=5, class_weight=None, warm_start=False, average=False)
__sklearn_tags__ (self)
Public Member Functions inherited from sklearn.linear_model._base.LinearClassifierMixin
predict (self, X)
Public Member Functions inherited from sklearn.base.ClassifierMixin
__sklearn_tags__ (self)
score (self, X, y, sample_weight=None)
Public Member Functions inherited from sklearn.linear_model._stochastic_gradient.BaseSGD
__init__ (self, loss, *, penalty="l2", alpha=0.0001, C=1.0, l1_ratio=0.15, fit_intercept=True, max_iter=1000, tol=1e-3, shuffle=True, verbose=0, epsilon=0.1, random_state=None, learning_rate="optimal", eta0=0.0, power_t=0.5, early_stopping=False, validation_fraction=0.1, n_iter_no_change=5, warm_start=False, average=False)
Public Member Functions inherited from sklearn.linear_model._base.SparseCoefMixin
densify (self)
sparsify (self)
Public Member Functions inherited from sklearn.base.BaseEstimator
get_params (self, deep=True)
set_params (self, **params)
__sklearn_clone__ (self)
__repr__ (self, N_CHAR_MAX=700)
__getstate__ (self)
__setstate__ (self, state)
__sklearn_tags__ (self)
Public Member Functions inherited from sklearn.utils._metadata_requests._MetadataRequester
set_fit_request (self, **kwargs)
set_partial_fit_request (self, **kwargs)
set_predict_request (self, **kwargs)
set_predict_proba_request (self, **kwargs)
set_predict_log_proba_request (self, **kwargs)
set_decision_function_request (self, **kwargs)
set_score_request (self, **kwargs)
set_split_request (self, **kwargs)
set_transform_request (self, **kwargs)
set_inverse_transform_request (self, **kwargs)
__init_subclass__ (cls, **kwargs)
get_metadata_routing (self)
Additional Inherited Members
Public Attributes inherited from sklearn.linear_model._stochastic_gradient.BaseSGDClassifier
str class_weight = class_weight
n_jobs = n_jobs
float t_ = 1.0
n_iter_ = self.max_iter
Public Attributes inherited from sklearn.linear_model._base.LinearClassifierMixin
classes_
Public Attributes inherited from sklearn.linear_model._stochastic_gradient.BaseSGD
loss = loss
str penalty = penalty
str learning_rate = learning_rate
epsilon = epsilon
alpha = alpha
C = C
l1_ratio = l1_ratio
fit_intercept = fit_intercept
shuffle = shuffle
random_state = random_state
verbose = verbose
eta0 = eta0
power_t = power_t
early_stopping = early_stopping
validation_fraction = validation_fraction
n_iter_no_change = n_iter_no_change
warm_start = warm_start
average = average
max_iter = max_iter
tol = tol
intercept_ = intercept_init
offset_
Public Attributes inherited from sklearn.linear_model._base.SparseCoefMixin
coef_
Static Public Attributes inherited from sklearn.linear_model._stochastic_gradient.BaseSGDClassifier
dict loss_functions
Protected Member Functions inherited from sklearn.linear_model._stochastic_gradient.SGDClassifier
_check_proba (self)
Protected Member Functions inherited from sklearn.linear_model._stochastic_gradient.BaseSGDClassifier
_partial_fit (self, X, y, alpha, C, loss, learning_rate, max_iter, classes, sample_weight, coef_init, intercept_init)
_fit (self, X, y, alpha, C, loss, learning_rate, coef_init=None, intercept_init=None, sample_weight=None)
_fit_binary (self, X, y, alpha, C, sample_weight, learning_rate, max_iter)
_fit_multiclass (self, X, y, alpha, C, learning_rate, sample_weight, max_iter)
Protected Member Functions inherited from sklearn.linear_model._base.LinearClassifierMixin
_predict_proba_lr (self, X)
Protected Member Functions inherited from sklearn.linear_model._stochastic_gradient.BaseSGD
_more_validate_params (self, for_partial_fit=False)
_get_l1_ratio (self)
_get_loss_function (self, loss)
_get_learning_rate_type (self, learning_rate)
_get_penalty_type (self, penalty)
_allocate_parameter_mem (self, n_classes, n_features, input_dtype, coef_init=None, intercept_init=None, one_class=0)
_make_validation_split (self, y, sample_mask)
_make_validation_score_cb (self, validation_mask, X, y, sample_weight, classes=None)
Protected Member Functions inherited from sklearn.base.BaseEstimator
_get_param_names (cls)
_get_params_html (self, deep=True)
_validate_params (self)
Protected Member Functions inherited from sklearn.utils._repr_html.base.ReprHTMLMixin
_repr_html_ (self)
_repr_html_inner (self)
_repr_mimebundle_ (self, **kwargs)
Protected Member Functions inherited from sklearn.utils._repr_html.base._HTMLDocumentationLinkMixin
_doc_link_template (self)
_doc_link_template (self, value)
_get_doc_link (self)
Protected Member Functions inherited from sklearn.utils._metadata_requests._MetadataRequester
_build_request_for_signature (cls, router, method)
_get_default_requests (cls)
_get_metadata_request (self)
Protected Attributes inherited from sklearn.linear_model._stochastic_gradient.BaseSGDClassifier
_expanded_class_weight
_loss_function_ = self._get_loss_function(loss)
Protected Attributes inherited from sklearn.linear_model._stochastic_gradient.BaseSGD
_standard_coef = self.coef_
_average_coef
int _standard_intercept = 1 - self.offset_
_average_intercept
Protected Attributes inherited from sklearn.base.BaseEstimator
_parameter_constraints
Static Protected Attributes inherited from sklearn.base.ClassifierMixin
str _estimator_type = "classifier"
Static Protected Attributes inherited from sklearn.base.BaseEstimator
_html_repr = estimator_html_repr
Static Protected Attributes inherited from sklearn.utils._repr_html.base._HTMLDocumentationLinkMixin
str _doc_link_module = "sklearn"
_doc_link_url_param_generator = None
Detailed Description
Definition at line 42 of file test_sgd.py.
Member Function Documentation
decision_function()
sklearn.linear_model.tests.test_sgd._SparseSGDClassifier.decision_function (self, X)
Predict confidence scores for samples.
The confidence score for a sample is proportional to the signed
distance of that sample to the hyperplane.
Parameters
----------
X : {array-like, sparse matrix} of shape (n_samples, n_features)
    The data matrix for which we want to get the confidence scores.
Returns
-------
scores : ndarray of shape (n_samples,) or (n_samples, n_classes)
    Confidence scores per `(n_samples, n_classes)` combination. In the
    binary case, confidence score for `self.classes_[1]` where >0 means
    this class would be predicted.
Reimplemented from sklearn.linear_model._base.LinearClassifierMixin.
Definition at line 51 of file test_sgd.py.
References decision_function().
Referenced by sklearn.neighbors._lof.LocalOutlierFactor._predict(), decision_function(), sklearn.multiclass.OneVsOneClassifier.predict(), sklearn.svm._base.BaseSVC.predict(), and sklearn.svm._classes.OneClassSVM.score_samples().
fit()
sklearn.linear_model.tests.test_sgd._SparseSGDClassifier.fit (self, X, y, * coef_init, ** intercept_init)
Fit linear model with Stochastic Gradient Descent.
Parameters
----------
X : {array-like, sparse matrix}, shape (n_samples, n_features)
    Training data.
y : ndarray of shape (n_samples,)
    Target values.
coef_init : ndarray of shape (n_classes, n_features), default=None
    The initial coefficients to warm-start the optimization.
intercept_init : ndarray of shape (n_classes,), default=None
    The initial intercept to warm-start the optimization.
sample_weight : array-like, shape (n_samples,), default=None
    Weights applied to individual samples.
    If not provided, uniform weights are assumed. These weights will
    be multiplied with class_weight (passed through the
    constructor) if class_weight is specified.
Returns
-------
self : object
    Returns an instance of self.
Reimplemented from sklearn.linear_model._stochastic_gradient.BaseSGDClassifier.
Definition at line 43 of file test_sgd.py.
References fit().
Referenced by fit(), sklearn.cluster._kmeans._BaseKMeans.fit_predict(), sklearn.neighbors._lof.LocalOutlierFactor.fit_predict(), sklearn.cluster._kmeans._BaseKMeans.fit_transform(), sklearn.manifold._spectral_embedding.SpectralEmbedding.fit_transform(), sklearn.neighbors._graph.KNeighborsTransformer.fit_transform(), sklearn.neighbors._graph.RadiusNeighborsTransformer.fit_transform(), sklearn.preprocessing._label.LabelBinarizer.fit_transform(), sklearn.preprocessing._label.MultiLabelBinarizer.fit_transform(), sklearn.tests.metadata_routing_common.ConsumingTransformer.fit_transform(), and sklearn.utils.tests.test_estimator_checks.SparseTransformer.fit_transform().
partial_fit()
sklearn.linear_model.tests.test_sgd._SparseSGDClassifier.partial_fit (self, X, y, * classes, ** sample_weight)
Perform one epoch of stochastic gradient descent on given samples.
Internally, this method uses ``max_iter = 1``. Therefore, it is not
guaranteed that a minimum of the cost function is reached after calling
it once. Matters such as objective convergence, early stopping, and
learning rate adjustments should be handled by the user.
Parameters
----------
X : {array-like, sparse matrix}, shape (n_samples, n_features)
    Subset of the training data.
y : ndarray of shape (n_samples,)
    Subset of the target values.
classes : ndarray of shape (n_classes,), default=None
    Classes across all calls to partial_fit.
    Can be obtained by via `np.unique(y_all)`, where y_all is the
    target vector of the entire dataset.
    This argument is required for the first call to partial_fit
    and can be omitted in the subsequent calls.
    Note that y doesn't need to contain all labels in `classes`.
sample_weight : array-like, shape (n_samples,), default=None
    Weights applied to individual samples.
    If not provided, uniform weights are assumed.
Returns
-------
self : object
    Returns an instance of self.
Reimplemented from sklearn.linear_model._stochastic_gradient.BaseSGDClassifier.
Definition at line 47 of file test_sgd.py.
References partial_fit().
Referenced by sklearn.preprocessing._data.MaxAbsScaler.fit(), sklearn.preprocessing._data.MinMaxScaler.fit(), sklearn.preprocessing._data.StandardScaler.fit(), and partial_fit().
predict_proba()
sklearn.linear_model.tests.test_sgd._SparseSGDClassifier.predict_proba (self, X)
Probability estimates.
This method is only available for log loss and modified Huber loss.
Multiclass probability estimates are derived from binary (one-vs.-rest)
estimates by simple normalization, as recommended by Zadrozny and
Elkan.
Binary probability estimates for loss="modified_huber" are given by
(clip(decision_function(X), -1, 1) + 1) / 2. For other loss functions
it is necessary to perform proper probability calibration by wrapping
the classifier with
:class:`~sklearn.calibration.CalibratedClassifierCV` instead.
Parameters
----------
X : {array-like, sparse matrix}, shape (n_samples, n_features)
    Input data for prediction.
Returns
-------
ndarray of shape (n_samples, n_classes)
    Returns the probability of the sample for each class in the model,
    where classes are ordered as they are in `self.classes_`.
References
----------
Zadrozny and Elkan, "Transforming classifier scores into multiclass
probability estimates", SIGKDD'02,
https://dl.acm.org/doi/pdf/10.1145/775047.775151
The justification for the formula in the loss="modified_huber"
case is in the appendix B in:
http://jmlr.csail.mit.edu/papers/volume2/zhang02c/zhang02c.pdf
Reimplemented from sklearn.linear_model._stochastic_gradient.SGDClassifier.
Definition at line 55 of file test_sgd.py.
References predict_proba().
Referenced by sklearn.neighbors._classification.KNeighborsClassifier.predict(), sklearn.neighbors._classification.RadiusNeighborsClassifier.predict(), sklearn.semi_supervised._label_propagation.BaseLabelPropagation.predict(), sklearn.multioutput.ClassifierChain.predict_log_proba(), sklearn.neural_network._multilayer_perceptron.MLPClassifier.predict_log_proba(), sklearn.svm._base.BaseSVC.predict_log_proba(), sklearn.tree._classes.DecisionTreeClassifier.predict_log_proba(), and predict_proba().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/sklearn/linear_model/tests/test_sgd.py