Code Cloning Analysis: fontTools.varLib.MasterFinder Class Reference
fontTools.varLib.MasterFinder Class Reference
Public Member Functions
__init__ (self, template)
__call__ (self, src_path)
Public Attributes
template = template
Detailed Description
Definition at line 1317 of file __init__.py.
Constructor & Destructor Documentation
__init__()
fontTools.varLib.MasterFinder.__init__ (self, template)
Definition at line 1318 of file __init__.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__call__()
fontTools.varLib.MasterFinder.__call__ (self, src_path)
Definition at line 1321 of file __init__.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), scipy.interpolate._fitpack2.SphereBivariateSpline.ev(), matplotlib.ticker.Formatter.format_data(), and matplotlib.ticker.LogFormatter.format_data().
Member Data Documentation
template
fontTools.varLib.MasterFinder.template = template
Definition at line 1319 of file __init__.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/varLib/__init__.py