Code Cloning Analysis: sklearn.covariance._shrunk_covariance.ShrunkCovariance Class Reference
sklearn.covariance._shrunk_covariance.ShrunkCovariance Class Reference
Public Member Functions
__init__ (self, *, store_precision=True, assume_centered=False, shrinkage=0.1)
fit (self, X, y=None)
Public Member Functions inherited from sklearn.covariance._empirical_covariance.EmpiricalCovariance
__init__ (self, *, store_precision=True, assume_centered=False)
get_precision (self)
score (self, X_test, y=None)
error_norm (self, comp_cov, norm="frobenius", scaling=True, squared=True)
mahalanobis (self, X)
Public Member Functions inherited from sklearn.base.BaseEstimator
get_params (self, deep=True)
set_params (self, **params)
__sklearn_clone__ (self)
__repr__ (self, N_CHAR_MAX=700)
__getstate__ (self)
__setstate__ (self, state)
__sklearn_tags__ (self)
Public Member Functions inherited from sklearn.utils._metadata_requests._MetadataRequester
set_fit_request (self, **kwargs)
set_partial_fit_request (self, **kwargs)
set_predict_request (self, **kwargs)
set_predict_proba_request (self, **kwargs)
set_predict_log_proba_request (self, **kwargs)
set_decision_function_request (self, **kwargs)
set_score_request (self, **kwargs)
set_split_request (self, **kwargs)
set_transform_request (self, **kwargs)
set_inverse_transform_request (self, **kwargs)
__init_subclass__ (cls, **kwargs)
get_metadata_routing (self)
Public Attributes
shrinkage = shrinkage
Public Attributes inherited from sklearn.covariance._empirical_covariance.EmpiricalCovariance
store_precision = store_precision
assume_centered = assume_centered
covariance_ = covariance
precision_ = linalg.pinvh(covariance, check_finite=False)
location_ = np.zeros(X.shape[1])
Static Public Attributes
None
closed
bool prefer_skip_nested_validation = True,
Additional Inherited Members
Protected Member Functions inherited from sklearn.covariance._empirical_covariance.EmpiricalCovariance
_set_covariance (self, covariance)
Protected Member Functions inherited from sklearn.base.BaseEstimator
_get_param_names (cls)
_get_params_html (self, deep=True)
_validate_params (self)
Protected Member Functions inherited from sklearn.utils._repr_html.base.ReprHTMLMixin
_repr_html_ (self)
_repr_html_inner (self)
_repr_mimebundle_ (self, **kwargs)
Protected Member Functions inherited from sklearn.utils._repr_html.base._HTMLDocumentationLinkMixin
_doc_link_template (self)
_doc_link_template (self, value)
_get_doc_link (self)
Protected Member Functions inherited from sklearn.utils._metadata_requests._MetadataRequester
_build_request_for_signature (cls, router, method)
_get_default_requests (cls)
_get_metadata_request (self)
Protected Attributes inherited from sklearn.base.BaseEstimator
_parameter_constraints
Static Protected Attributes inherited from sklearn.base.BaseEstimator
_html_repr = estimator_html_repr
Static Protected Attributes inherited from sklearn.utils._repr_html.base._HTMLDocumentationLinkMixin
str _doc_link_module = "sklearn"
_doc_link_url_param_generator = None
Detailed Description
Covariance estimator with shrinkage.
Read more in the :ref:`User Guide <shrunk_covariance>`.
Parameters
----------
store_precision : bool, default=True
    Specify if the estimated precision is stored.
assume_centered : bool, default=False
    If True, data will not be centered before computation.
    Useful when working with data whose mean is almost, but not exactly
    zero.
    If False, data will be centered before computation.
shrinkage : float, default=0.1
    Coefficient in the convex combination used for the computation
    of the shrunk estimate. Range is [0, 1].
Attributes
----------
covariance_ : ndarray of shape (n_features, n_features)
    Estimated covariance matrix
location_ : ndarray of shape (n_features,)
    Estimated location, i.e. the estimated mean.
precision_ : ndarray of shape (n_features, n_features)
    Estimated pseudo inverse matrix.
    (stored only if store_precision is True)
n_features_in_ : int
    Number of features seen during :term:`fit`.
    .. versionadded:: 0.24
feature_names_in_ : ndarray of shape (`n_features_in_`,)
    Names of features seen during :term:`fit`. Defined only when `X`
    has feature names that are all strings.
    .. versionadded:: 1.0
See Also
--------
EllipticEnvelope : An object for detecting outliers in
    a Gaussian distributed dataset.
EmpiricalCovariance : Maximum likelihood covariance estimator.
GraphicalLasso : Sparse inverse covariance estimation
    with an l1-penalized estimator.
GraphicalLassoCV : Sparse inverse covariance with cross-validated
    choice of the l1 penalty.
LedoitWolf : LedoitWolf Estimator.
MinCovDet : Minimum Covariance Determinant
    (robust estimator of covariance).
OAS : Oracle Approximating Shrinkage Estimator.
Notes
-----
The regularized covariance is given by:
(1 - shrinkage) * cov + shrinkage * mu * np.identity(n_features)
where mu = trace(cov) / n_features
Examples
--------
>>> import numpy as np
>>> from sklearn.covariance import ShrunkCovariance
>>> from sklearn.datasets import make_gaussian_quantiles
>>> real_cov = np.array([[.8, .3],
...                      [.3, .4]])
>>> rng = np.random.RandomState(0)
>>> X = rng.multivariate_normal(mean=[0, 0],
...                                   cov=real_cov,
...                                   size=500)
>>> cov = ShrunkCovariance().fit(X)
>>> cov.covariance_
array([[0.7387, 0.2536],
       [0.2536, 0.4110]])
>>> cov.location_
array([0.0622, 0.0193])
Definition at line 159 of file _shrunk_covariance.py.
Constructor & Destructor Documentation
__init__()
sklearn.covariance._shrunk_covariance.ShrunkCovariance.__init__ (self, * , store_precision = True, assume_centered = False, shrinkage = 0.1)
Definition at line 248 of file _shrunk_covariance.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params().
Member Function Documentation
fit()
sklearn.covariance._shrunk_covariance.ShrunkCovariance.fit (self, X, y = None)
Fit the shrunk covariance model to X.
Parameters
----------
X : array-like of shape (n_samples, n_features)
    Training data, where `n_samples` is the number of samples
    and `n_features` is the number of features.
y : Ignored
    Not used, present for API consistency by convention.
Returns
-------
self : object
    Returns the instance itself.
Reimplemented from sklearn.covariance._empirical_covariance.EmpiricalCovariance.
Definition at line 255 of file _shrunk_covariance.py.
References sklearn.covariance._empirical_covariance.EmpiricalCovariance._set_covariance(), sklearn.covariance._empirical_covariance.EmpiricalCovariance.assume_centered, sklearn.covariance._empirical_covariance.EmpiricalCovariance.location_, shrinkage, and sklearn.covariance._shrunk_covariance.shrunk_covariance().
Referenced by sklearn.cluster._kmeans._BaseKMeans.fit_predict(), sklearn.neighbors._lof.LocalOutlierFactor.fit_predict(), sklearn.cluster._kmeans._BaseKMeans.fit_transform(), sklearn.cross_decomposition._pls._PLS.fit_transform(), sklearn.cross_decomposition._pls.PLSSVD.fit_transform(), sklearn.decomposition._kernel_pca.KernelPCA.fit_transform(), sklearn.decomposition._lda.LatentDirichletAllocation.fit_transform(), sklearn.manifold._spectral_embedding.SpectralEmbedding.fit_transform(), sklearn.neighbors._graph.KNeighborsTransformer.fit_transform(), sklearn.neighbors._graph.RadiusNeighborsTransformer.fit_transform(), sklearn.preprocessing._label.LabelBinarizer.fit_transform(), sklearn.preprocessing._label.MultiLabelBinarizer.fit_transform(), sklearn.tests.metadata_routing_common.ConsumingTransformer.fit_transform(), and sklearn.utils.tests.test_estimator_checks.SparseTransformer.fit_transform().
Member Data Documentation
closed
sklearn.covariance._shrunk_covariance.ShrunkCovariance.closed static
Definition at line 293 of file _shrunk_covariance.py.
Referenced by pandas.core.dtypes.dtypes.IntervalDtype.__from_arrow__(), pandas.core.indexes.interval.IntervalIndex._getitem_slice(), pandas.core.indexes.interval.IntervalIndex._maybe_convert_i8(), pandas.core.indexes.interval.IntervalIndex.get_loc(), sklearn.utils._param_validation.Interval.is_satisfied_by(), and pandas.core.dtypes.dtypes.IntervalDtype.type().
None
sklearn.covariance._shrunk_covariance.ShrunkCovariance.None static
Definition at line 293 of file _shrunk_covariance.py.
prefer_skip_nested_validation
bool sklearn.covariance._shrunk_covariance.ShrunkCovariance.prefer_skip_nested_validation = True, static
Definition at line 295 of file _shrunk_covariance.py.
shrinkage
sklearn.covariance._shrunk_covariance.ShrunkCovariance.shrinkage = shrinkage
Definition at line 252 of file _shrunk_covariance.py.
Referenced by sklearn.ensemble._hist_gradient_boosting.grower.TreeGrower._apply_shrinkage(), fit(), and sklearn.discriminant_analysis.LinearDiscriminantAnalysis.fit().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/sklearn/covariance/_shrunk_covariance.py