Code Cloning Analysis: sklearn.utils._plotting._BinaryClassifierCurveDisplayMixin Class Reference
sklearn.utils._plotting._BinaryClassifierCurveDisplayMixin Class Reference
Protected Member Functions
_validate_plot_params (self, *, ax=None, name=None)
_validate_and_get_response_values (cls, estimator, X, y, *, response_method="auto", pos_label=None, name=None)
_validate_from_predictions_params (cls, y_true, y_pred, *, sample_weight=None, pos_label=None, name=None)
_validate_from_cv_results_params (cls, cv_results, X, y, *, sample_weight, pos_label)
Static Protected Member Functions
_get_legend_label (curve_legend_metric, curve_name, legend_metric_name)
_validate_curve_kwargs (n_curves, name, legend_metric, legend_metric_name, curve_kwargs, **kwargs)
Detailed Description
Mixin class to be used in Displays requiring a binary classifier.
The aim of this class is to centralize some validations regarding the estimator and
the target and gather the response of the estimator.
Definition at line 16 of file _plotting.py.
Member Function Documentation
_get_legend_label()
sklearn.utils._plotting._BinaryClassifierCurveDisplayMixin._get_legend_label (curve_legend_metric, curve_name, legend_metric_name) static protected
Helper to get legend label using `name` and `legend_metric`
Definition at line 119 of file _plotting.py.
_validate_and_get_response_values()
sklearn.utils._plotting._BinaryClassifierCurveDisplayMixin._validate_and_get_response_values (cls, estimator, X, y, * , response_method = "auto", pos_label = None, name = None) protected
Definition at line 37 of file _plotting.py.
Referenced by sklearn.calibration.CalibrationDisplay.from_estimator(), sklearn.metrics._plot.det_curve.DetCurveDisplay.from_estimator(), sklearn.metrics._plot.precision_recall_curve.PrecisionRecallDisplay.from_estimator(), and sklearn.metrics._plot.roc_curve.RocCurveDisplay.from_estimator().
_validate_curve_kwargs()
sklearn.utils._plotting._BinaryClassifierCurveDisplayMixin._validate_curve_kwargs (n_curves, name, legend_metric, legend_metric_name, curve_kwargs, ** kwargs) static protected
Get validated line kwargs for each curve.
Parameters
----------
n_curves : int
    Number of curves.
name : list of str or None
    Name for labeling legend entries.
legend_metric : dict
    Dictionary with "mean" and "std" keys, or "metric" key of metric
    values for each curve. If None, "label" will not contain metric values.
legend_metric_name : str
    Name of the summary value provided in `legend_metrics`.
curve_kwargs : dict or list of dict or None
    Dictionary with keywords passed to the matplotlib's `plot` function
    to draw the individual curves. If a list is provided, the
    parameters are applied to the curves sequentially. If a single
    dictionary is provided, the same parameters are applied to all
    curves.
**kwargs : dict
    Deprecated. Keyword arguments to be passed to matplotlib's `plot`.
Definition at line 132 of file _plotting.py.
References sklearn.utils._plotting._validate_style_kwargs().
Referenced by sklearn.metrics._plot.roc_curve.RocCurveDisplay.plot().
_validate_from_cv_results_params()
sklearn.utils._plotting._BinaryClassifierCurveDisplayMixin._validate_from_cv_results_params (cls, cv_results, X, y, * , sample_weight, pos_label) protected
Definition at line 73 of file _plotting.py.
Referenced by sklearn.metrics._plot.roc_curve.RocCurveDisplay.from_cv_results().
_validate_from_predictions_params()
sklearn.utils._plotting._BinaryClassifierCurveDisplayMixin._validate_from_predictions_params (cls, y_true, y_pred, * , sample_weight = None, pos_label = None, name = None) protected
Definition at line 54 of file _plotting.py.
Referenced by sklearn.calibration.CalibrationDisplay.from_predictions(), sklearn.metrics._plot.det_curve.DetCurveDisplay.from_predictions(), sklearn.metrics._plot.precision_recall_curve.PrecisionRecallDisplay.from_predictions(), and sklearn.metrics._plot.roc_curve.RocCurveDisplay.from_predictions().
_validate_plot_params()
sklearn.utils._plotting._BinaryClassifierCurveDisplayMixin._validate_plot_params (self, * , ax = None, name = None) protected
Definition at line 23 of file _plotting.py.
Referenced by sklearn.calibration.CalibrationDisplay.plot(), sklearn.metrics._plot.det_curve.DetCurveDisplay.plot(), and sklearn.metrics._plot.precision_recall_curve.PrecisionRecallDisplay.plot().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/sklearn/utils/_plotting.py