Code Cloning Analysis: PIL.PdfParser.PdfParser Class Reference
PIL.PdfParser.PdfParser Class Reference
Public Member Functions
None __init__ (self, str|None filename=None, IO[bytes]|None f=None, bytes|bytearray|None buf=None, int start_offset=0, str mode="rb")
PdfParser __enter__ (self)
None __exit__ (self, *object args)
None start_writing (self)
None close_buf (self)
None close (self)
None seek_end (self)
None write_header (self)
None write_comment (self, str s)
IndirectReference write_catalog (self)
None rewrite_pages (self)
None write_xref_and_trailer (self, IndirectReference|None new_root_ref=None)
IndirectReference write_page (self, int|IndirectReference|None ref, *Any objs, **Any dict_obj)
IndirectReference write_obj (self, IndirectReference|None ref, *Any objs, **Any dict_obj)
None del_root (self)
None read_pdf_info (self)
IndirectReference next_object_id (self, int|None offset=None)
None read_trailer (self)
None read_prev_trailer (self, int xref_section_offset)
dict[bytes, Any] interpret_trailer (cls, bytes trailer_data)
str|bytes interpret_name (cls, bytes raw, bool as_text=False)
tuple[Any, int|None] get_value (cls, bytes|bytearray|mmap.mmap data, int offset, IndirectReference|None expect_indirect=None, int max_nesting=-1)
tuple[bytes, int] get_literal_string (cls, bytes|bytearray|mmap.mmap data, int offset)
int read_xref_table (self, int xref_section_offset)
Any read_indirect (self, IndirectReference ref, int max_nesting=-1)
list[IndirectReference] linearize_page_tree (self, PdfDict|None node=None)
Static Public Member Functions
bytes|mmap.mmap get_buf_from_file (IO[bytes] f)
Public Attributes
filename = filename
bytes|bytearray|mmap.mmap|None buf = buf
f = f
start_offset = start_offset
bool should_close_buf = False
bool should_close_file = False
dict cached_objects = {}
IndirectReference|None root_ref = self.next_object_id(0)
IndirectReference|None info_ref
IndirectReference|None pages_ref = self.pages_ref)
int|None last_xref_section_offset
int file_size_total = 0
root = PdfDict()
info = PdfDict()
Any page_tree_root = PdfDict()
list pages = []
list orig_pages = []
dict trailer_dict = {}
xref_table = XrefTable()
int file_size_this = self.file_size_total - self.start_offset
Static Public Attributes
str delimiter = rb"[][()<>{}/%]"
str delimiter_or_ws = rb"[][()<>{}/%\000\011\012\014\015\040]"
str whitespace = rb"[\000\011\012\014\015\040]"
str whitespace_or_hex = rb"[\000\011\012\014\015\0400-9a-fA-F]"
str whitespace_optional = whitespace + b"*"
str whitespace_mandatory = whitespace + b"+"
str whitespace_optional_no_nl = rb"[\000\011\014\040]*"
str newline_only = rb"[\r\n]+"
str newline = whitespace_optional_no_nl + newline_only + whitespace_optional_no_nl
re_trailer_end
re_trailer_prev
re_whitespace_optional = re.compile(whitespace_optional)
re_name
re_dict_start = re.compile(whitespace_optional + rb"<<")
re_dict_end = re.compile(whitespace_optional + rb">>" + whitespace_optional)
re_hashes_in_name = re.compile(rb"([^#]*)(#([0-9a-fA-F]{2}))?")
re_null = re.compile(whitespace_optional + rb"null(?=" + delimiter_or_ws + rb")")
re_true = re.compile(whitespace_optional + rb"true(?=" + delimiter_or_ws + rb")")
re_false = re.compile(whitespace_optional + rb"false(?=" + delimiter_or_ws + rb")")
re_int
re_real
re_array_start = re.compile(whitespace_optional + rb"\[")
re_array_end = re.compile(whitespace_optional + rb"]")
re_string_hex
re_string_lit = re.compile(whitespace_optional + rb"\(")
re_indirect_reference
re_indirect_def_start
re_indirect_def_end
re_comment
re_stream_start = re.compile(whitespace_optional + rb"stream\r?\n")
re_stream_end
re_lit_str_token
dict escaped_chars
re_xref_section_start = re.compile(whitespace_optional + rb"xref" + newline)
re_xref_subsection_start
re_xref_entry = re.compile(rb"([0-9]{10}) ([0-9]{5}) ([fn])(\r| \n|\r\n)")
Detailed Description
Based on
https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/PDF32000_2008.pdf
Supports PDF up to 1.4
Definition at line 367 of file PdfParser.py.
Constructor & Destructor Documentation
__init__()
None PIL.PdfParser.PdfParser.__init__ (self, str | None filename = None, IO[bytes] | None f = None, bytes | bytearray | None buf = None, int start_offset = 0, str mode = "rb")
Definition at line 373 of file PdfParser.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
__enter__()
PdfParser PIL.PdfParser.PdfParser.__enter__ (self)
Definition at line 422 of file PdfParser.py.
__exit__()
None PIL.PdfParser.PdfParser.__exit__ (self, *object args)
Definition at line 425 of file PdfParser.py.
close()
None PIL.PdfParser.PdfParser.close (self)
Definition at line 437 of file PdfParser.py.
Referenced by pip._vendor.urllib3.util.ssltransport.SSLTransport.__init__(), pip._vendor.urllib3.contrib.securetransport.WrappedSocket._custom_validate(), pip._vendor.urllib3.contrib.securetransport.WrappedSocket._raise_on_error(), scipy.io._fortran.FortranFile.close(), scipy.io._netcdf.netcdf_file.close(), pip._vendor.urllib3.contrib.securetransport.WrappedSocket.handshake(), PIL.PngImagePlugin.ChunkStream.read(), and pip._vendor.urllib3.response.HTTPResponse.supports_chunked_reads().
close_buf()
None PIL.PdfParser.PdfParser.close_buf (self)
Definition at line 432 of file PdfParser.py.
del_root()
None PIL.PdfParser.PdfParser.del_root (self)
Definition at line 560 of file PdfParser.py.
get_buf_from_file()
bytes | mmap.mmap PIL.PdfParser.PdfParser.get_buf_from_file (IO[bytes] f) static
Definition at line 567 of file PdfParser.py.
get_literal_string()
tuple[bytes, int] PIL.PdfParser.PdfParser.get_literal_string (cls, bytes | bytearray | mmap.mmap data, int offset)
Definition at line 972 of file PdfParser.py.
get_value()
tuple[Any, int | None] PIL.PdfParser.PdfParser.get_value (cls, bytes | bytearray | mmap.mmap data, int offset, IndirectReference | None expect_indirect = None, int max_nesting = -1)
Definition at line 810 of file PdfParser.py.
interpret_name()
str | bytes PIL.PdfParser.PdfParser.interpret_name (cls, bytes raw, bool as_text = False)
Definition at line 748 of file PdfParser.py.
interpret_trailer()
dict[bytes, Any] PIL.PdfParser.PdfParser.interpret_trailer (cls, bytes trailer_data)
Definition at line 715 of file PdfParser.py.
linearize_page_tree()
list[IndirectReference] PIL.PdfParser.PdfParser.linearize_page_tree (self, PdfDict | None node = None)
Definition at line 1060 of file PdfParser.py.
next_object_id()
IndirectReference PIL.PdfParser.PdfParser.next_object_id (self, int | None offset = None)
Definition at line 614 of file PdfParser.py.
read_indirect()
Any PIL.PdfParser.PdfParser.read_indirect (self, IndirectReference ref, int max_nesting = -1)
Definition at line 1043 of file PdfParser.py.
read_pdf_info()
None PIL.PdfParser.PdfParser.read_pdf_info (self)
Definition at line 578 of file PdfParser.py.
read_prev_trailer()
None PIL.PdfParser.PdfParser.read_prev_trailer (self, int xref_section_offset)
Definition at line 687 of file PdfParser.py.
read_trailer()
None PIL.PdfParser.PdfParser.read_trailer (self)
Definition at line 664 of file PdfParser.py.
read_xref_table()
int PIL.PdfParser.PdfParser.read_xref_table (self, int xref_section_offset)
Definition at line 1010 of file PdfParser.py.
rewrite_pages()
None PIL.PdfParser.PdfParser.rewrite_pages (self)
Definition at line 471 of file PdfParser.py.
seek_end()
None PIL.PdfParser.PdfParser.seek_end (self)
Definition at line 444 of file PdfParser.py.
start_writing()
None PIL.PdfParser.PdfParser.start_writing (self)
Definition at line 428 of file PdfParser.py.
write_catalog()
IndirectReference PIL.PdfParser.PdfParser.write_catalog (self)
Definition at line 456 of file PdfParser.py.
write_comment()
None PIL.PdfParser.PdfParser.write_comment (self, str s)
Definition at line 452 of file PdfParser.py.
write_header()
None PIL.PdfParser.PdfParser.write_header (self)
Definition at line 448 of file PdfParser.py.
Referenced by scipy.io.matlab._mio4.VarWriter4.write(), scipy.io.matlab._mio5.VarWriter5.write(), scipy.io.matlab._mio5.VarWriter5.write_char(), scipy.io.matlab._mio5.VarWriter5.write_object(), scipy.io.matlab._mio4.VarWriter4.write_sparse(), and scipy.io.matlab._mio5.VarWriter5.write_sparse().
write_obj()
IndirectReference PIL.PdfParser.PdfParser.write_obj (self, IndirectReference | None ref, *Any objs, **Any dict_obj)
Definition at line 536 of file PdfParser.py.
write_page()
IndirectReference PIL.PdfParser.PdfParser.write_page (self, int | IndirectReference | None ref, *Any objs, **Any dict_obj)
Definition at line 526 of file PdfParser.py.
write_xref_and_trailer()
None PIL.PdfParser.PdfParser.write_xref_and_trailer (self, IndirectReference | None new_root_ref = None)
Definition at line 500 of file PdfParser.py.
Member Data Documentation
buf
PIL.PdfParser.PdfParser.buf = buf
Definition at line 385 of file PdfParser.py.
cached_objects
dict PIL.PdfParser.PdfParser.cached_objects = {}
Definition at line 398 of file PdfParser.py.
delimiter
str PIL.PdfParser.PdfParser.delimiter = rb"[][()<>{}/%]" static
Definition at line 624 of file PdfParser.py.
delimiter_or_ws
str PIL.PdfParser.PdfParser.delimiter_or_ws = rb"[][()<>{}/%\000\011\012\014\015\040]" static
Definition at line 625 of file PdfParser.py.
escaped_chars
dict PIL.PdfParser.PdfParser.escaped_chars static
Initial value:
=  {
        b"n": b"\n",
        b"r": b"\r",
        b"t": b"\t",
        b"b": b"\b",
        b"f": b"\f",
        b"(": b"(",
        b")": b")",
        b"\\": b"\\",
        ord(b"n"): b"\n",
        ord(b"r"): b"\r",
        ord(b"t"): b"\t",
        ord(b"b"): b"\b",
        ord(b"f"): b"\f",
        ord(b"("): b"(",
        ord(b")"): b")",
        ord(b"\\"): b"\\",
    }
Definition at line 952 of file PdfParser.py.
f
PIL.PdfParser.PdfParser.f = f
Definition at line 386 of file PdfParser.py.
Referenced by scipy.optimize._zeros_py.TOMS748Solver._callf(), scipy.integrate._ode.ode.integrate(), scipy.optimize._shgo_lib._vertex.VertexScalarField.maximiser(), scipy.optimize._shgo_lib._vertex.VertexScalarField.minimiser(), and scipy.optimize._zeros_py.TOMS748Solver.start().
file_size_this
int PIL.PdfParser.PdfParser.file_size_this = self.file_size_total - self.start_offset
Definition at line 581 of file PdfParser.py.
file_size_total
int PIL.PdfParser.PdfParser.file_size_total = 0
Definition at line 406 of file PdfParser.py.
filename
PIL.PdfParser.PdfParser.filename = filename
Definition at line 384 of file PdfParser.py.
Referenced by pip._internal.models.wheel.Wheel.__init__(), pip._vendor.distlib.wheel.Wheel.__init__(), scipy.io._netcdf.netcdf_file.__init__(), pip._vendor.distlib.wheel.Wheel.build(), pip._vendor.distlib.wheel.Wheel.filename(), scipy.io._netcdf.netcdf_file.flush(), pip._vendor.pygments.formatters.html.HtmlFormatter.get_style_defs(), PIL.ImageCms.Flags.GRIDPOINTS(), pip._vendor.distlib.wheel.Wheel.install(), pip._vendor.distlib.wheel.Wheel.is_mountable(), PIL.Image.Image.save(), and pip._vendor.distlib.wheel.Wheel.update().
info
PIL.PdfParser.PdfParser.info = PdfDict()
Definition at line 409 of file PdfParser.py.
Referenced by pandas.core.frame.DataFrame.__repr__(), joblib.memory.MemorizedFunc._cached_call(), pandas.core.frame.DataFrame._repr_html_(), pandas.io.formats.info._TableBuilderAbstract.display_memory_usage(), pandas.io.formats.info._TableBuilderAbstract.dtype_counts(), pandas.io.formats.info._TableBuilderAbstract.dtypes(), pandas.io.formats.info._TableBuilderAbstract.get_lines(), pip._vendor.distlib.wheel.Wheel.install(), pandas.io.formats.info._TableBuilderAbstract.memory_usage_string(), and pip._internal.models.direct_url.DirectUrl.redacted_url().
info_ref
IndirectReference | None PIL.PdfParser.PdfParser.info_ref
Definition at line 400 of file PdfParser.py.
last_xref_section_offset
int | None PIL.PdfParser.PdfParser.last_xref_section_offset
Definition at line 402 of file PdfParser.py.
newline
str PIL.PdfParser.PdfParser.newline = whitespace_optional_no_nl + newline_only + whitespace_optional_no_nl static
Definition at line 633 of file PdfParser.py.
Referenced by fontTools.misc.xmlWriter.XMLWriter._writeraw().
newline_only
str PIL.PdfParser.PdfParser.newline_only = rb"[\r\n]+" static
Definition at line 632 of file PdfParser.py.
orig_pages
PIL.PdfParser.PdfParser.orig_pages = []
Definition at line 413 of file PdfParser.py.
page_tree_root
Any PIL.PdfParser.PdfParser.page_tree_root = PdfDict()
Definition at line 411 of file PdfParser.py.
pages
PIL.PdfParser.PdfParser.pages = []
Definition at line 412 of file PdfParser.py.
pages_ref
PIL.PdfParser.PdfParser.pages_ref = self.pages_ref)
Definition at line 401 of file PdfParser.py.
re_array_end
PIL.PdfParser.PdfParser.re_array_end = re.compile(whitespace_optional + rb"]") static
Definition at line 773 of file PdfParser.py.
re_array_start
PIL.PdfParser.PdfParser.re_array_start = re.compile(whitespace_optional + rb"\[") static
Definition at line 772 of file PdfParser.py.
re_comment
PIL.PdfParser.PdfParser.re_comment static
Initial value:
=  re.compile(
        rb"(" + whitespace_optional + rb"%[^\r\n]*" + newline + rb")*"
    )
Definition at line 801 of file PdfParser.py.
re_dict_end
PIL.PdfParser.PdfParser.re_dict_end = re.compile(whitespace_optional + rb">>" + whitespace_optional) static
Definition at line 712 of file PdfParser.py.
re_dict_start
PIL.PdfParser.PdfParser.re_dict_start = re.compile(whitespace_optional + rb"<<") static
Definition at line 711 of file PdfParser.py.
re_false
PIL.PdfParser.PdfParser.re_false = re.compile(whitespace_optional + rb"false(?=" + delimiter_or_ws + rb")") static
Definition at line 762 of file PdfParser.py.
re_hashes_in_name
PIL.PdfParser.PdfParser.re_hashes_in_name = re.compile(rb"([^#]*)(#([0-9a-fA-F]{2}))?") static
Definition at line 745 of file PdfParser.py.
re_indirect_def_end
PIL.PdfParser.PdfParser.re_indirect_def_end static
Initial value:
=  re.compile(
        whitespace_optional + rb"endobj(?=" + delimiter_or_ws + rb")"
    )
Definition at line 798 of file PdfParser.py.
re_indirect_def_start
PIL.PdfParser.PdfParser.re_indirect_def_start static
Initial value:
=  re.compile(
        whitespace_optional
        + rb"([-+]?[0-9]+)"
        + whitespace_mandatory
        + rb"([-+]?[0-9]+)"
        + whitespace_mandatory
        + rb"obj(?="
        + delimiter_or_ws
        + rb")"
    )
Definition at line 788 of file PdfParser.py.
re_indirect_reference
PIL.PdfParser.PdfParser.re_indirect_reference static
Initial value:
=  re.compile(
        whitespace_optional
        + rb"([-+]?[0-9]+)"
        + whitespace_mandatory
        + rb"([-+]?[0-9]+)"
        + whitespace_mandatory
        + rb"R(?="
        + delimiter_or_ws
        + rb")"
    )
Definition at line 778 of file PdfParser.py.
re_int
PIL.PdfParser.PdfParser.re_int static
Initial value:
=  re.compile(
        whitespace_optional + rb"([-+]?[0-9]+)(?=" + delimiter_or_ws + rb")"
    )
Definition at line 763 of file PdfParser.py.
re_lit_str_token
PIL.PdfParser.PdfParser.re_lit_str_token static
Initial value:
=  re.compile(
        rb"(\\[nrtbf()\\])|(\\[0-9]{1,3})|(\\(\r\n|\r|\n))|(\r\n|\r|\n)|(\‍()|(\‍))"
    )
Definition at line 949 of file PdfParser.py.
re_name
PIL.PdfParser.PdfParser.re_name static
Initial value:
=  re.compile(
        whitespace_optional
        + rb"/([!-$&'*-.0-;=?-Z\\^-z|~]+)(?="
        + delimiter_or_ws
        + rb")"
    )
Definition at line 705 of file PdfParser.py.
re_null
PIL.PdfParser.PdfParser.re_null = re.compile(whitespace_optional + rb"null(?=" + delimiter_or_ws + rb")") static
Definition at line 760 of file PdfParser.py.
re_real
PIL.PdfParser.PdfParser.re_real static
Initial value:
=  re.compile(
        whitespace_optional
        + rb"([-+]?([0-9]+\.[0-9]*|[0-9]*\.[0-9]+))(?="
        + delimiter_or_ws
        + rb")"
    )
Definition at line 766 of file PdfParser.py.
re_stream_end
PIL.PdfParser.PdfParser.re_stream_end static
Initial value:
=  re.compile(
        whitespace_optional + rb"endstream(?=" + delimiter_or_ws + rb")"
    )
Definition at line 805 of file PdfParser.py.
re_stream_start
PIL.PdfParser.PdfParser.re_stream_start = re.compile(whitespace_optional + rb"stream\r?\n") static
Definition at line 804 of file PdfParser.py.
re_string_hex
PIL.PdfParser.PdfParser.re_string_hex static
Initial value:
=  re.compile(
        whitespace_optional + rb"<(" + whitespace_or_hex + rb"*)>"
    )
Definition at line 774 of file PdfParser.py.
re_string_lit
PIL.PdfParser.PdfParser.re_string_lit = re.compile(whitespace_optional + rb"\(") static
Definition at line 777 of file PdfParser.py.
re_trailer_end
PIL.PdfParser.PdfParser.re_trailer_end static
Initial value:
=  re.compile(
        whitespace_mandatory
        + rb"trailer"
        + whitespace_optional
        + rb"<<(.*>>)"
        + newline
        + rb"startxref"
        + newline
        + rb"([0-9]+)"
        + newline
        + rb"%%EOF"
        + whitespace_optional
        + rb"$",
        re.DOTALL,
    )
Definition at line 634 of file PdfParser.py.
re_trailer_prev
PIL.PdfParser.PdfParser.re_trailer_prev static
Initial value:
=  re.compile(
        whitespace_optional
        + rb"trailer"
        + whitespace_optional
        + rb"<<(.*?>>)"
        + newline
        + rb"startxref"
        + newline
        + rb"([0-9]+)"
        + newline
        + rb"%%EOF"
        + whitespace_optional,
        re.DOTALL,
    )
Definition at line 649 of file PdfParser.py.
re_true
PIL.PdfParser.PdfParser.re_true = re.compile(whitespace_optional + rb"true(?=" + delimiter_or_ws + rb")") static
Definition at line 761 of file PdfParser.py.
re_whitespace_optional
PIL.PdfParser.PdfParser.re_whitespace_optional = re.compile(whitespace_optional) static
Definition at line 704 of file PdfParser.py.
re_xref_entry
PIL.PdfParser.PdfParser.re_xref_entry = re.compile(rb"([0-9]{10}) ([0-9]{5}) ([fn])(\r| \n|\r\n)") static
Definition at line 1008 of file PdfParser.py.
re_xref_section_start
PIL.PdfParser.PdfParser.re_xref_section_start = re.compile(whitespace_optional + rb"xref" + newline) static
Definition at line 999 of file PdfParser.py.
re_xref_subsection_start
PIL.PdfParser.PdfParser.re_xref_subsection_start static
Initial value:
=  re.compile(
        whitespace_optional
        + rb"([0-9]+)"
        + whitespace_mandatory
        + rb"([0-9]+)"
        + whitespace_optional
        + newline_only
    )
Definition at line 1000 of file PdfParser.py.
root
PIL.PdfParser.PdfParser.root = PdfDict()
Definition at line 407 of file PdfParser.py.
Referenced by sklearn.ensemble._hist_gradient_boosting.grower.TreeGrower._initialize_root(), pandas.io.pytables.HDFStore.get_node(), and sklearn.ensemble._hist_gradient_boosting.grower.TreeGrower.make_predictor().
root_ref
PIL.PdfParser.PdfParser.root_ref = self.next_object_id(0)
Definition at line 399 of file PdfParser.py.
should_close_buf
bool PIL.PdfParser.PdfParser.should_close_buf = False
Definition at line 388 of file PdfParser.py.
should_close_file
bool PIL.PdfParser.PdfParser.should_close_file = False
Definition at line 389 of file PdfParser.py.
start_offset
PIL.PdfParser.PdfParser.start_offset = start_offset
Definition at line 387 of file PdfParser.py.
trailer_dict
dict PIL.PdfParser.PdfParser.trailer_dict = {}
Definition at line 416 of file PdfParser.py.
whitespace
str PIL.PdfParser.PdfParser.whitespace = rb"[\000\011\012\014\015\040]" static
Definition at line 626 of file PdfParser.py.
Referenced by pip._vendor.rich.pretty._Line.check_length(), and pip._vendor.rich.pretty._Line.expand().
whitespace_mandatory
str PIL.PdfParser.PdfParser.whitespace_mandatory = whitespace + b"+" static
Definition at line 629 of file PdfParser.py.
whitespace_optional
str PIL.PdfParser.PdfParser.whitespace_optional = whitespace + b"*" static
Definition at line 628 of file PdfParser.py.
whitespace_optional_no_nl
str PIL.PdfParser.PdfParser.whitespace_optional_no_nl = rb"[\000\011\014\040]*" static
Definition at line 631 of file PdfParser.py.
whitespace_or_hex
str PIL.PdfParser.PdfParser.whitespace_or_hex = rb"[\000\011\012\014\015\0400-9a-fA-F]" static
Definition at line 627 of file PdfParser.py.
xref_table
PIL.PdfParser.PdfParser.xref_table = XrefTable()
Definition at line 417 of file PdfParser.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/PIL/PdfParser.py