Code Cloning Analysis: pandas.io.common Namespace Reference
pandas.io.common Namespace Reference
Classes
class _BufferedWriter
class _BytesIOWrapper
class _BytesTarFile
class _BytesZipFile
class _IOWrapper
class IOArgs
class IOHandles
Functions
bool is_url (object url)
str _expand_user (str filepath_or_buffer)
BaseBufferT _expand_user (BaseBufferT filepath_or_buffer)
str|BaseBufferT _expand_user (str|BaseBufferT filepath_or_buffer)
None validate_header_arg (object header)
str stringify_path (FilePath filepath_or_buffer, bool convert_file_like=...)
BaseBufferT stringify_path (BaseBufferT filepath_or_buffer, bool convert_file_like=...)
str|BaseBufferT stringify_path (FilePath|BaseBufferT filepath_or_buffer, bool convert_file_like=False)
urlopen (*args, **kwargs)
bool is_fsspec_url (FilePath|BaseBuffer url)
IOArgs _get_filepath_or_buffer (FilePath|BaseBuffer filepath_or_buffer, str encoding="utf-8", CompressionOptions|None compression=None, str mode="r", StorageOptions|None storage_options=None)
str file_path_to_url (str path)
tuple[str|None, CompressionDict] get_compression_method (CompressionOptions compression)
str|None infer_compression (FilePath|BaseBuffer filepath_or_buffer, str|None compression)
None check_parent_directory (Path|str path)
IOHandles[bytes] get_handle (FilePath|BaseBuffer path_or_buf, str mode, *, str|None encoding=..., CompressionOptions compression=..., bool memory_map=..., Literal[False] is_text, str|None errors=..., StorageOptions storage_options=...)
IOHandles[str] get_handle (FilePath|BaseBuffer path_or_buf, str mode, *, str|None encoding=..., CompressionOptions compression=..., bool memory_map=..., Literal[True] is_text=..., str|None errors=..., StorageOptions storage_options=...)
IOHandles[str]|IOHandles[bytes] get_handle (FilePath|BaseBuffer path_or_buf, str mode, *, str|None encoding=..., CompressionOptions compression=..., bool memory_map=..., bool is_text=..., str|None errors=..., StorageOptions storage_options=...)
IOHandles[str]|IOHandles[bytes] get_handle (FilePath|BaseBuffer path_or_buf, str mode, *, str|None encoding=None, CompressionOptions|None compression=None, bool memory_map=False, bool is_text=True, str|None errors=None, StorageOptions|None storage_options=None)
tuple[str|BaseBuffer, bool, list[BaseBuffer]] _maybe_memory_map (str|BaseBuffer handle, bool memory_map)
bool file_exists (FilePath|BaseBuffer filepath_or_buffer)
bool _is_binary_mode (FilePath|BaseBuffer handle, str mode)
tuple[type,...] _get_binary_io_classes ()
bool is_potential_multi_index (Sequence[Hashable]|MultiIndex columns, bool|Sequence[int]|None index_col=None)
Sequence[Hashable] dedup_names (Sequence[Hashable] names, bool is_potential_multiindex)
Variables
_VALID_URLS = set(uses_relative + uses_netloc + uses_params)
_RFC_3986_PATTERN = re.compile(r"^[A-Za-z][A-Za-z0-9+\-+.]*://")
BaseBufferT = TypeVar("BaseBufferT", bound=BaseBuffer)
dict extension_to_compression
_supported_compressions = set(extension_to_compression.values())
Detailed Description
Common IO api utilities
Function Documentation
_expand_user() [1/3]
BaseBufferT pandas.io.common._expand_user (BaseBufferT filepath_or_buffer) protected
Definition at line 184 of file common.py.
_expand_user() [2/3]
str pandas.io.common._expand_user (str filepath_or_buffer) protected
Definition at line 179 of file common.py.
_expand_user() [3/3]
str | BaseBufferT pandas.io.common._expand_user (str | BaseBufferT filepath_or_buffer) protected
Return the argument with an initial component of ~ or ~user
replaced by that user's home directory.
Parameters
----------
filepath_or_buffer : object to be converted if possible
Returns
-------
expanded_filepath_or_buffer : an expanded filepath or the
                              input if not expandable
Definition at line 188 of file common.py.
_get_binary_io_classes()
tuple[type, ...] pandas.io.common._get_binary_io_classes () protected
IO classes that that expect bytes
Definition at line 1187 of file common.py.
Referenced by _is_binary_mode().
_get_filepath_or_buffer()
IOArgs pandas.io.common._get_filepath_or_buffer (FilePath | BaseBuffer filepath_or_buffer, str encoding = "utf-8", CompressionOptions | None compression = None, str mode = "r", StorageOptions | None storage_options = None) protected
If the filepath_or_buffer is a url, translate and return the buffer.
Otherwise passthrough.
Parameters
----------
filepath_or_buffer : a url, filepath (str, py.path.local or pathlib.Path),
                     or buffer
{compression_options}
    .. versionchanged:: 1.4.0 Zstandard support.
encoding : the encoding to use to decode bytes, default is 'utf-8'
mode : str, optional
{storage_options}
Returns the dataclass IOArgs.
Definition at line 308 of file common.py.
References get_compression_method(), infer_compression(), is_fsspec_url(), is_url(), and urlopen().
Referenced by get_handle().
_is_binary_mode()
bool pandas.io.common._is_binary_mode (FilePath | BaseBuffer handle, str mode) protected
Whether the handle is opened in binary mode
Definition at line 1165 of file common.py.
References _get_binary_io_classes().
Referenced by get_handle().
_maybe_memory_map()
tuple[str | BaseBuffer, bool, list[BaseBuffer]] pandas.io.common._maybe_memory_map (str | BaseBuffer handle, bool memory_map) protected
Try to memory map file/buffer.
Definition at line 1117 of file common.py.
Referenced by get_handle().
check_parent_directory()
None pandas.io.common.check_parent_directory (Path | str path)
Check if parent directory of a file exists, raise OSError if it does not
Parameters
----------
path: Path or str
    Path to check parent directory of
Definition at line 605 of file common.py.
Referenced by get_handle().
dedup_names()
Sequence[Hashable] pandas.io.common.dedup_names (Sequence[Hashable] names, bool is_potential_multiindex)
Rename column names if duplicates exist.
Currently the renaming is done by appending a period and an autonumeric,
but a custom pattern may be supported in the future.
Examples
--------
>>> dedup_names(["x", "y", "x", "x"], is_potential_multiindex=False)
['x', 'y', 'x.1', 'x.2']
Definition at line 1233 of file common.py.
file_exists()
bool pandas.io.common.file_exists (FilePath | BaseBuffer filepath_or_buffer)
Test whether file exists.
Definition at line 1151 of file common.py.
file_path_to_url()
str pandas.io.common.file_path_to_url (str path)
converts an absolute native path to a FILE URL.
Parameters
----------
path : a path in native format
Returns
-------
a valid FILE URL
Definition at line 483 of file common.py.
get_compression_method()
tuple[str | None, CompressionDict] pandas.io.common.get_compression_method (CompressionOptions compression)
Simplifies a compression argument to a compression method string and
a mapping containing additional arguments.
Parameters
----------
compression : str or mapping
    If string, specifies the compression method. If mapping, value at key
    'method' specifies compression method.
Returns
-------
tuple of ({compression method}, Optional[str]
          {compression arguments}, Dict[str, Any])
Raises
------
ValueError on mapping missing 'method' key
Definition at line 515 of file common.py.
Referenced by _get_filepath_or_buffer().
get_handle() [1/4]
IOHandles[str] | IOHandles[bytes] pandas.io.common.get_handle (FilePath | BaseBuffer path_or_buf, str mode, * , str | None encoding = ..., CompressionOptions compression = ..., bool memory_map = ..., bool is_text = ..., str | None errors = ..., StorageOptions storage_options = ...)
Definition at line 650 of file common.py.
get_handle() [2/4]
IOHandles[bytes] pandas.io.common.get_handle (FilePath | BaseBuffer path_or_buf, str mode, * , str | None encoding = ..., CompressionOptions compression = ..., bool memory_map = ..., Literal[False] is_text, str | None errors = ..., StorageOptions storage_options = ...)
Definition at line 620 of file common.py.
get_handle() [3/4]
IOHandles[str] pandas.io.common.get_handle (FilePath | BaseBuffer path_or_buf, str mode, * , str | None encoding = ..., CompressionOptions compression = ..., bool memory_map = ..., Literal[True] is_text = ..., str | None errors = ..., StorageOptions storage_options = ...)
Definition at line 635 of file common.py.
get_handle() [4/4]
IOHandles[str] | IOHandles[bytes] pandas.io.common.get_handle (FilePath | BaseBuffer path_or_buf, str mode, * , str | None encoding = None, CompressionOptions | None compression = None, bool memory_map = False, bool is_text = True, str | None errors = None, StorageOptions | None storage_options = None)
Get file handle for given path/buffer and mode.
Parameters
----------
path_or_buf : str or file handle
    File path or object.
mode : str
    Mode to open path_or_buf with.
encoding : str or None
    Encoding to use.
{compression_options}
       May be a dict with key 'method' as compression mode
       and other keys as compression options if compression
       mode is 'zip'.
       Passing compression options as keys in dict is
       supported for compression modes 'gzip', 'bz2', 'zstd' and 'zip'.
    .. versionchanged:: 1.4.0 Zstandard support.
memory_map : bool, default False
    See parsers._parser_params for more information. Only used by read_csv.
is_text : bool, default True
    Whether the type of the content passed to the file/buffer is string or
    bytes. This is not the same as `"b" not in mode`. If a string content is
    passed to a binary file/buffer, a wrapper is inserted.
errors : str, default 'strict'
    Specifies how encoding and decoding errors are to be handled.
    See the errors argument for :func:`open` for a full list
    of options.
storage_options: StorageOptions = None
    Passed to _get_filepath_or_buffer
Returns the dataclass IOHandles
Definition at line 665 of file common.py.
References _get_filepath_or_buffer(), _is_binary_mode(), _maybe_memory_map(), and check_parent_directory().
infer_compression()
str | None pandas.io.common.infer_compression (FilePath | BaseBuffer filepath_or_buffer, str | None compression)
Get the compression method for filepath_or_buffer. If compression='infer',
the inferred compression method is returned. Otherwise, the input
compression method is returned unchanged, unless it's invalid, in which
case an error is raised.
Parameters
----------
filepath_or_buffer : str or file handle
    File path or object.
{compression_options}
    .. versionchanged:: 1.4.0 Zstandard support.
Returns
-------
string or None
Raises
------
ValueError on invalid compression specified.
Definition at line 551 of file common.py.
Referenced by _get_filepath_or_buffer().
is_fsspec_url()
bool pandas.io.common.is_fsspec_url (FilePath | BaseBuffer url)
Returns true if the given URL looks like
something fsspec can handle
Definition at line 292 of file common.py.
Referenced by _get_filepath_or_buffer().
is_potential_multi_index()
bool pandas.io.common.is_potential_multi_index (Sequence[Hashable] | MultiIndex columns, bool | Sequence[int] | None index_col = None)
Check whether or not the `columns` parameter
could be converted into a MultiIndex.
Parameters
----------
columns : array-like
    Object which may or may not be convertible into a MultiIndex
index_col : None, bool or list, optional
    Column or columns to use as the (possibly hierarchical) index
Returns
-------
bool : Whether or not columns could become a MultiIndex
Definition at line 1204 of file common.py.
is_url()
bool pandas.io.common.is_url (object url)
Check to see if a URL has a valid protocol.
Parameters
----------
url : str or unicode
Returns
-------
isurl : bool
    If `url` has a valid protocol return True otherwise False.
Definition at line 160 of file common.py.
Referenced by _get_filepath_or_buffer().
stringify_path() [1/3]
BaseBufferT pandas.io.common.stringify_path (BaseBufferT filepath_or_buffer, bool convert_file_like = ...)
Definition at line 242 of file common.py.
stringify_path() [2/3]
str pandas.io.common.stringify_path (FilePath filepath_or_buffer, bool convert_file_like = ...)
Definition at line 237 of file common.py.
stringify_path() [3/3]
str | BaseBufferT pandas.io.common.stringify_path (FilePath | BaseBufferT filepath_or_buffer, bool convert_file_like = False)
Attempt to convert a path-like object to a string.
Parameters
----------
filepath_or_buffer : object to be converted
Returns
-------
str_filepath_or_buffer : maybe a string version of the object
Notes
-----
Objects supporting the fspath protocol are coerced
according to its __fspath__ method.
Any other object is passed through unchanged, which includes bytes,
strings, buffers, or anything else that's not even path-like.
Definition at line 248 of file common.py.
urlopen()
pandas.io.common.urlopen (* args, ** kwargs)
Lazy-import wrapper for stdlib urlopen, as that imports a big chunk of
the stdlib.
Definition at line 282 of file common.py.
Referenced by _get_filepath_or_buffer().
validate_header_arg()
None pandas.io.common.validate_header_arg (object header)
Definition at line 207 of file common.py.
Variable Documentation
_RFC_3986_PATTERN
pandas.io.common._RFC_3986_PATTERN = re.compile(r"^[A-Za-z][A-Za-z0-9+\-+.]*://") protected
Definition at line 77 of file common.py.
_supported_compressions
pandas.io.common._supported_compressions = set(extension_to_compression.values()) protected
Definition at line 512 of file common.py.
_VALID_URLS
pandas.io.common._VALID_URLS = set(uses_relative + uses_netloc + uses_params) protected
Definition at line 75 of file common.py.
BaseBufferT
pandas.io.common.BaseBufferT = TypeVar("BaseBufferT", bound=BaseBuffer)
Definition at line 79 of file common.py.
extension_to_compression
dict pandas.io.common.extension_to_compression
Initial value:
=  {
    ".tar": "tar",
    ".tar.gz": "tar",
    ".tar.bz2": "tar",
    ".tar.xz": "tar",
    ".gz": "gzip",
    ".bz2": "bz2",
    ".zip": "zip",
    ".xz": "xz",
    ".zst": "zstd",
}
Definition at line 501 of file common.py.