Code Cloning Analysis: scipy.optimize._differentiable_functions.ScalarFunction Class Reference
scipy.optimize._differentiable_functions.ScalarFunction Class Reference
Public Member Functions
__init__ (self, fun, x0, args, grad, hess, finite_diff_rel_step, finite_diff_bounds, epsilon=None)
fun (self, x)
grad (self, x)
hess (self, x)
fun_and_grad (self, x)
Public Attributes
x = np.atleast_1d(x0).astype(float)
n = self.x.size
int nfev = 0
int ngev = 0
int nhev = 0
bool f_updated = False
bool g_updated = False
bool H_updated = False
f = fun_wrapped(self.x)
g = grad_wrapped(self.x)
H = hess(np.copy(x0), *args)
x_prev = None
g_prev = None
Protected Member Functions
_update_fun (self)
_update_grad (self)
_update_hess (self)
Protected Attributes
_lowest_x = None
_lowest_f = np.inf
_update_fun_impl = update_fun
_update_grad_impl = update_grad
_update_hess_impl = update_hess
_update_x_impl = update_x
Detailed Description
Scalar function and its derivatives.
This class defines a scalar function F: R^n->R and methods for
computing or approximating its first and second derivatives.
Parameters
----------
fun : callable
    evaluates the scalar function. Must be of the form ``fun(x, *args)``,
    where ``x`` is the argument in the form of a 1-D array and ``args`` is
    a tuple of any additional fixed parameters needed to completely specify
    the function. Should return a scalar.
x0 : array-like
    Provides an initial set of variables for evaluating fun. Array of real
    elements of size (n,), where 'n' is the number of independent
    variables.
args : tuple, optional
    Any additional fixed parameters needed to completely specify the scalar
    function.
grad : {callable, '2-point', '3-point', 'cs'}
    Method for computing the gradient vector.
    If it is a callable, it should be a function that returns the gradient
    vector:
        ``grad(x, *args) -> array_like, shape (n,)``
    where ``x`` is an array with shape (n,) and ``args`` is a tuple with
    the fixed parameters.
    Alternatively, the keywords  {'2-point', '3-point', 'cs'} can be used
    to select a finite difference scheme for numerical estimation of the
    gradient with a relative step size. These finite difference schemes
    obey any specified `bounds`.
hess : {callable, '2-point', '3-point', 'cs', HessianUpdateStrategy}
    Method for computing the Hessian matrix. If it is callable, it should
    return the  Hessian matrix:
        ``hess(x, *args) -> {LinearOperator, spmatrix, array}, (n, n)``
    where x is a (n,) ndarray and `args` is a tuple with the fixed
    parameters. Alternatively, the keywords {'2-point', '3-point', 'cs'}
    select a finite difference scheme for numerical estimation. Or, objects
    implementing `HessianUpdateStrategy` interface can be used to
    approximate the Hessian.
    Whenever the gradient is estimated via finite-differences, the Hessian
    cannot be estimated with options {'2-point', '3-point', 'cs'} and needs
    to be estimated using one of the quasi-Newton strategies.
finite_diff_rel_step : None or array_like
    Relative step size to use. The absolute step size is computed as
    ``h = finite_diff_rel_step * sign(x0) * max(1, abs(x0))``, possibly
    adjusted to fit into the bounds. For ``method='3-point'`` the sign
    of `h` is ignored. If None then finite_diff_rel_step is selected
    automatically,
finite_diff_bounds : tuple of array_like
    Lower and upper bounds on independent variables. Defaults to no bounds,
    (-np.inf, np.inf). Each bound must match the size of `x0` or be a
    scalar, in the latter case the bound will be the same for all
    variables. Use it to limit the range of function evaluation.
epsilon : None or array_like, optional
    Absolute step size to use, possibly adjusted to fit into the bounds.
    For ``method='3-point'`` the sign of `epsilon` is ignored. By default
    relative steps are used, only if ``epsilon is not None`` are absolute
    steps used.
Notes
-----
This class implements a memoization logic. There are methods `fun`,
`grad`, hess` and corresponding attributes `f`, `g` and `H`. The following
things should be considered:
    1. Use only public methods `fun`, `grad` and `hess`.
    2. After one of the methods is called, the corresponding attribute
       will be set. However, a subsequent call with a different argument
       of *any* of the methods may overwrite the attribute.
Definition at line 11 of file _differentiable_functions.py.
Constructor & Destructor Documentation
__init__()
scipy.optimize._differentiable_functions.ScalarFunction.__init__ (self, fun, x0, args, grad, hess, finite_diff_rel_step, finite_diff_bounds, epsilon = None)
Definition at line 86 of file _differentiable_functions.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
_update_fun()
scipy.optimize._differentiable_functions.ScalarFunction._update_fun (self) protected
Definition at line 249 of file _differentiable_functions.py.
_update_grad()
scipy.optimize._differentiable_functions.ScalarFunction._update_grad (self) protected
Definition at line 254 of file _differentiable_functions.py.
_update_hess()
scipy.optimize._differentiable_functions.ScalarFunction._update_hess (self) protected
Definition at line 259 of file _differentiable_functions.py.
fun()
scipy.optimize._differentiable_functions.ScalarFunction.fun (self, x)
Definition at line 264 of file _differentiable_functions.py.
fun_and_grad()
scipy.optimize._differentiable_functions.ScalarFunction.fun_and_grad (self, x)
Definition at line 282 of file _differentiable_functions.py.
grad()
scipy.optimize._differentiable_functions.ScalarFunction.grad (self, x)
Definition at line 270 of file _differentiable_functions.py.
hess()
scipy.optimize._differentiable_functions.ScalarFunction.hess (self, x)
Definition at line 276 of file _differentiable_functions.py.
Member Data Documentation
_lowest_f
scipy.optimize._differentiable_functions.ScalarFunction._lowest_f = np.inf protected
Definition at line 117 of file _differentiable_functions.py.
_lowest_x
scipy.optimize._differentiable_functions.ScalarFunction._lowest_x = None protected
Definition at line 116 of file _differentiable_functions.py.
_update_fun_impl
scipy.optimize._differentiable_functions.ScalarFunction._update_fun_impl = update_fun protected
Definition at line 157 of file _differentiable_functions.py.
_update_grad_impl
scipy.optimize._differentiable_functions.ScalarFunction._update_grad_impl = update_grad protected
Definition at line 176 of file _differentiable_functions.py.
_update_hess_impl
scipy.optimize._differentiable_functions.ScalarFunction._update_hess_impl = update_hess protected
Definition at line 225 of file _differentiable_functions.py.
_update_x_impl
scipy.optimize._differentiable_functions.ScalarFunction._update_x_impl = update_x protected
Definition at line 247 of file _differentiable_functions.py.
f
scipy.optimize._differentiable_functions.ScalarFunction.f = fun_wrapped(self.x)
Definition at line 155 of file _differentiable_functions.py.
Referenced by scipy.optimize._zeros_py.TOMS748Solver._callf(), scipy.optimize._shgo_lib._vertex.VertexScalarField.maximiser(), scipy.optimize._shgo_lib._vertex.VertexScalarField.minimiser(), and scipy.optimize._zeros_py.TOMS748Solver.start().
f_updated
bool scipy.optimize._differentiable_functions.ScalarFunction.f_updated = False
Definition at line 112 of file _differentiable_functions.py.
g
scipy.optimize._differentiable_functions.ScalarFunction.g = grad_wrapped(self.x)
Definition at line 167 of file _differentiable_functions.py.
g_prev
scipy.optimize._differentiable_functions.ScalarFunction.g_prev = None
Definition at line 219 of file _differentiable_functions.py.
g_updated
bool scipy.optimize._differentiable_functions.ScalarFunction.g_updated = False
Definition at line 113 of file _differentiable_functions.py.
H
scipy.optimize._differentiable_functions.ScalarFunction.H = hess(np.copy(x0), *args)
Definition at line 181 of file _differentiable_functions.py.
Referenced by scipy.sparse.linalg._interface.LinearOperator._rmatmat(), scipy.sparse.linalg._interface.LinearOperator._rmatvec(), scipy.optimize._hessian_update_strategy.BFGS._update_hessian(), scipy.optimize._hessian_update_strategy.BFGS._update_inverse_hessian(), scipy.optimize._hessian_update_strategy.FullHessianUpdateStrategy.dot(), scipy.optimize._hessian_update_strategy.FullHessianUpdateStrategy.get_matrix(), scipy.optimize._hessian_update_strategy.FullHessianUpdateStrategy.initialize(), and scipy.optimize._hessian_update_strategy.FullHessianUpdateStrategy.update().
H_updated
bool scipy.optimize._differentiable_functions.ScalarFunction.H_updated = False
Definition at line 114 of file _differentiable_functions.py.
n
scipy.optimize._differentiable_functions.ScalarFunction.n = self.x.size
Definition at line 108 of file _differentiable_functions.py.
Referenced by scipy.signal._czt.CZT.__call__(), scipy.stats._morestats._ABW.__init__(), scipy.stats._morestats._ABW._recalc(), scipy.optimize._hessian_update_strategy.BFGS._update_hessian(), scipy.optimize._hessian_update_strategy.FullHessianUpdateStrategy.initialize(), scipy.stats._kde.gaussian_kde.integrate_kde(), scipy.optimize._shgo.SHGO.iterate_delaunay(), scipy.optimize._shgo.SHGO.iterate_hypercube(), scipy.stats._kde.gaussian_kde.marginal(), scipy.stats._binomtest.BinomTestResult.proportion_ci(), scipy.stats._kde.gaussian_kde.resample(), and scipy.optimize._nonlin.LowRankMatrix.rsolve().
nfev
int scipy.optimize._differentiable_functions.ScalarFunction.nfev = 0
Definition at line 109 of file _differentiable_functions.py.
Referenced by scipy.optimize._shgo_lib._vertex.VertexCacheField.compute_sfield(), scipy.optimize._shgo_lib._vertex.VertexCacheField.pproc_fpool_g(), and scipy.optimize._shgo_lib._vertex.VertexCacheField.pproc_fpool_nog().
ngev
int scipy.optimize._differentiable_functions.ScalarFunction.ngev = 0
Definition at line 110 of file _differentiable_functions.py.
nhev
int scipy.optimize._differentiable_functions.ScalarFunction.nhev = 0
Definition at line 111 of file _differentiable_functions.py.
x
scipy.optimize._differentiable_functions.ScalarFunction.x = np.atleast_1d(x0).astype(float)
Definition at line 107 of file _differentiable_functions.py.
Referenced by scipy.optimize._root_scalar.MemoizeDer.__call__(), scipy.optimize._shgo_lib._vertex.VertexBase.__init__(), scipy.optimize._differentialevolution.DifferentialEvolutionSolver.__next__(), matplotlib.widgets.ToolHandles.closest(), scipy.optimize._root_scalar.MemoizeDer.fprime(), scipy.optimize._root_scalar.MemoizeDer.fprime2(), scipy.optimize._differentialevolution.DifferentialEvolutionSolver.solve(), and scipy.spatial.tests.test_kdtree._Test_sorted_query_ball_point.test_return_sorted_None().
x_prev
scipy.optimize._differentiable_functions.ScalarFunction.x_prev = None
Definition at line 218 of file _differentiable_functions.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/optimize/_differentiable_functions.py