Code Cloning Analysis: scipy.integrate._ivp.bdf.BDF Class Reference
scipy.integrate._ivp.bdf.BDF Class Reference
Public Member Functions
__init__ (self, fun, t0, y0, t_bound, max_step=np.inf, rtol=1e-3, atol=1e-6, jac=None, jac_sparsity=None, vectorized=False, first_step=None, **extraneous)
Public Member Functions inherited from scipy.integrate._ivp.base.OdeSolver
__init__ (self, fun, t0, y0, t_bound, vectorized, support_complex=False)
step_size (self)
step (self)
dense_output (self)
Public Attributes
max_step = validate_max_step(max_step)
rtol
atol = validate_tol(rtol, atol, self.n)
h_abs
h_abs_old = None
error_norm_old = None
newton_tol = max(10 * EPS / rtol, min(0.03, rtol ** 0.5))
jac_factor = None
jac
J = self._validate_jac(jac, jac_sparsity)
lu = lu
solve_lu = solve_lu
I = I
gamma = np.hstack((0, np.cumsum(1 / np.arange(1, MAX_ORDER + 1))))
tuple alpha = (1 - kappa) * self.gamma
int error_const = kappa * self.gamma + 1 / np.arange(1, MAX_ORDER + 2)
D = D
int order = 1
int n_equal_steps = 0
LU = None
Public Attributes inherited from scipy.integrate._ivp.base.OdeSolver
t_old = None
t = t0
y = check_arguments(fun, y0, support_complex)
t_bound = t_bound
vectorized = vectorized
fun = fun
fun_single = fun_single
fun_vectorized = fun_vectorized
int direction = t0 else 1
int n = self.y.size
str status = 'running'
int nfev = 0
int njev = 0
int nlu = 0
Protected Member Functions
_validate_jac (self, jac, sparsity)
_step_impl (self)
_dense_output_impl (self)
Additional Inherited Members
Static Public Attributes inherited from scipy.integrate._ivp.base.OdeSolver
str TOO_SMALL_STEP = "Required step size is less than spacing between numbers."
Protected Attributes inherited from scipy.integrate._ivp.base.OdeSolver
_fun
Detailed Description
Implicit method based on backward-differentiation formulas.
This is a variable order method with the order varying automatically from
1 to 5. The general framework of the BDF algorithm is described in [1]_.
This class implements a quasi-constant step size as explained in [2]_.
The error estimation strategy for the constant-step BDF is derived in [3]_.
An accuracy enhancement using modified formulas (NDF) [2]_ is also implemented.
Can be applied in the complex domain.
Parameters
----------
fun : callable
    Right-hand side of the system: the time derivative of the state ``y``
    at time ``t``. The calling signature is ``fun(t, y)``, where ``t`` is a
    scalar and ``y`` is an ndarray with ``len(y) = len(y0)``. ``fun`` must
    return an array of the same shape as ``y``. See `vectorized` for more
    information.
t0 : float
    Initial time.
y0 : array_like, shape (n,)
    Initial state.
t_bound : float
    Boundary time - the integration won't continue beyond it. It also
    determines the direction of the integration.
first_step : float or None, optional
    Initial step size. Default is ``None`` which means that the algorithm
    should choose.
max_step : float, optional
    Maximum allowed step size. Default is np.inf, i.e., the step size is not
    bounded and determined solely by the solver.
rtol, atol : float and array_like, optional
    Relative and absolute tolerances. The solver keeps the local error
    estimates less than ``atol + rtol * abs(y)``. Here `rtol` controls a
    relative accuracy (number of correct digits), while `atol` controls
    absolute accuracy (number of correct decimal places). To achieve the
    desired `rtol`, set `atol` to be smaller than the smallest value that
    can be expected from ``rtol * abs(y)`` so that `rtol` dominates the
    allowable error. If `atol` is larger than ``rtol * abs(y)`` the
    number of correct digits is not guaranteed. Conversely, to achieve the
    desired `atol` set `rtol` such that ``rtol * abs(y)`` is always smaller
    than `atol`. If components of y have different scales, it might be
    beneficial to set different `atol` values for different components by
    passing array_like with shape (n,) for `atol`. Default values are
    1e-3 for `rtol` and 1e-6 for `atol`.
jac : {None, array_like, sparse_matrix, callable}, optional
    Jacobian matrix of the right-hand side of the system with respect to y,
    required by this method. The Jacobian matrix has shape (n, n) and its
    element (i, j) is equal to ``d f_i / d y_j``.
    There are three ways to define the Jacobian:
        * If array_like or sparse_matrix, the Jacobian is assumed to
          be constant.
        * If callable, the Jacobian is assumed to depend on both
          t and y; it will be called as ``jac(t, y)`` as necessary.
          For the 'Radau' and 'BDF' methods, the return value might be a
          sparse matrix.
        * If None (default), the Jacobian will be approximated by
          finite differences.
    It is generally recommended to provide the Jacobian rather than
    relying on a finite-difference approximation.
jac_sparsity : {None, array_like, sparse matrix}, optional
    Defines a sparsity structure of the Jacobian matrix for a
    finite-difference approximation. Its shape must be (n, n). This argument
    is ignored if `jac` is not `None`. If the Jacobian has only few non-zero
    elements in *each* row, providing the sparsity structure will greatly
    speed up the computations [4]_. A zero entry means that a corresponding
    element in the Jacobian is always zero. If None (default), the Jacobian
    is assumed to be dense.
vectorized : bool, optional
    Whether `fun` can be called in a vectorized fashion. Default is False.
    If ``vectorized`` is False, `fun` will always be called with ``y`` of
    shape ``(n,)``, where ``n = len(y0)``.
    If ``vectorized`` is True, `fun` may be called with ``y`` of shape
    ``(n, k)``, where ``k`` is an integer. In this case, `fun` must behave
    such that ``fun(t, y)[:, i] == fun(t, y[:, i])`` (i.e. each column of
    the returned array is the time derivative of the state corresponding
    with a column of ``y``).
    Setting ``vectorized=True`` allows for faster finite difference
    approximation of the Jacobian by this method, but may result in slower
    execution overall in some circumstances (e.g. small ``len(y0)``).
Attributes
----------
n : int
    Number of equations.
status : string
    Current status of the solver: 'running', 'finished' or 'failed'.
t_bound : float
    Boundary time.
direction : float
    Integration direction: +1 or -1.
t : float
    Current time.
y : ndarray
    Current state.
t_old : float
    Previous time. None if no steps were made yet.
step_size : float
    Size of the last successful step. None if no steps were made yet.
nfev : int
    Number of evaluations of the right-hand side.
njev : int
    Number of evaluations of the Jacobian.
nlu : int
    Number of LU decompositions.
References
----------
.. [1] G. D. Byrne, A. C. Hindmarsh, "A Polyalgorithm for the Numerical
       Solution of Ordinary Differential Equations", ACM Transactions on
       Mathematical Software, Vol. 1, No. 1, pp. 71-96, March 1975.
.. [2] L. F. Shampine, M. W. Reichelt, "THE MATLAB ODE SUITE", SIAM J. SCI.
       COMPUTE., Vol. 18, No. 1, pp. 1-22, January 1997.
.. [3] E. Hairer, G. Wanner, "Solving Ordinary Differential Equations I:
       Nonstiff Problems", Sec. III.2.
.. [4] A. Curtis, M. J. D. Powell, and J. Reid, "On the estimation of
       sparse Jacobian matrices", Journal of the Institute of Mathematics
       and its Applications, 13, pp. 117-120, 1974.
Definition at line 72 of file bdf.py.
Constructor & Destructor Documentation
__init__()
scipy.integrate._ivp.bdf.BDF.__init__ (self, fun, t0, y0, t_bound, max_step = np.inf, rtol = 1e-3, atol = 1e-6, jac = None, jac_sparsity = None, vectorized = False, first_step = None, ** extraneous)
Definition at line 197 of file bdf.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
_dense_output_impl()
scipy.integrate._ivp.bdf.BDF._dense_output_impl (self) protected
Reimplemented from scipy.integrate._ivp.base.OdeSolver.
Definition at line 452 of file bdf.py.
_step_impl()
scipy.integrate._ivp.bdf.BDF._step_impl (self) protected
Reimplemented from scipy.integrate._ivp.base.OdeSolver.
Definition at line 309 of file bdf.py.
_validate_jac()
scipy.integrate._ivp.bdf.BDF._validate_jac (self, jac, sparsity) protected
Definition at line 256 of file bdf.py.
Member Data Documentation
alpha
tuple scipy.integrate._ivp.bdf.BDF.alpha = (1 - kappa) * self.gamma
Definition at line 244 of file bdf.py.
Referenced by sklearn.gaussian_process.kernels.RationalQuadratic.__call__(), sklearn.neural_network._multilayer_perceptron.BaseMultilayerPerceptron._backprop(), sklearn.neural_network._multilayer_perceptron.BaseMultilayerPerceptron._compute_loss_grad(), sklearn.decomposition._sparse_pca.MiniBatchSparsePCA._fit(), sklearn.decomposition._sparse_pca.SparsePCA._fit(), sklearn.decomposition._kernel_pca.KernelPCA._fit_transform_in_place(), sklearn.ensemble._gb.GradientBoostingRegressor._get_loss(), sklearn.feature_selection._univariate_selection.SelectFdr._get_support_mask(), sklearn.feature_selection._univariate_selection.SelectFpr._get_support_mask(), sklearn.feature_selection._univariate_selection.SelectFwe._get_support_mask(), sklearn.ensemble._gb.BaseGradientBoosting._init_state(), sklearn.decomposition._dict_learning.MiniBatchDictionaryLearning._minibatch_step(), sklearn.decomposition._dict_learning._BaseSparseCoding._transform(), sklearn.naive_bayes._BaseDiscreteNB._update_class_log_prior(), scipy.optimize._nonlin.LowRankMatrix.collapse(), sklearn.cluster._hdbscan.hdbscan.HDBSCAN.fit(), sklearn.covariance._graph_lasso.GraphicalLasso.fit(), sklearn.gaussian_process._gpr.GaussianProcessRegressor.fit(), sklearn.kernel_ridge.KernelRidge.fit(), sklearn.linear_model._coordinate_descent.ElasticNet.fit(), sklearn.linear_model._coordinate_descent.MultiTaskElasticNet.fit(), sklearn.linear_model._glm.glm._GeneralizedLinearRegressor.fit(), sklearn.linear_model._huber.HuberRegressor.fit(), sklearn.linear_model._quantile.QuantileRegressor.fit(), sklearn.linear_model._ridge._BaseRidge.fit(), sklearn.linear_model._stochastic_gradient.BaseSGDClassifier.fit(), sklearn.linear_model._stochastic_gradient.BaseSGDRegressor.fit(), sklearn.semi_supervised._label_propagation.BaseLabelPropagation.fit(), sklearn.decomposition._dict_learning.DictionaryLearning.fit_transform(), sklearn.gaussian_process._gpr.GaussianProcessRegressor.log_marginal_likelihood(), scipy.optimize._nonlin.LowRankMatrix.matvec(), sklearn.linear_model._stochastic_gradient.BaseSGDClassifier.partial_fit(), sklearn.linear_model._stochastic_gradient.BaseSGDRegressor.partial_fit(), scipy.optimize._nonlin.LowRankMatrix.rmatvec(), scipy.optimize._nonlin.LowRankMatrix.rsolve(), and scipy.optimize._nonlin.LowRankMatrix.solve().
atol
scipy.integrate._ivp.bdf.BDF.atol = validate_tol(rtol, atol, self.n)
Definition at line 204 of file bdf.py.
Referenced by scipy.optimize._differentialevolution.DifferentialEvolutionSolver.converged(), scipy.integrate._ode.dop853.reset(), scipy.integrate._ode.dopri5.reset(), scipy.integrate._ode.lsoda.reset(), scipy.integrate._ode.vode.reset(), scipy.integrate._ode.zvode.reset(), and sklearn.neighbors._kde.KernelDensity.score_samples().
D
scipy.integrate._ivp.bdf.BDF.D = D
Definition at line 250 of file bdf.py.
Referenced by scipy.signal._ltisys.StateSpace.__add__(), scipy.signal._ltisys.StateSpace.__init__(), scipy.signal._ltisys.StateSpace.__mul__(), scipy.signal._ltisys.StateSpace.__neg__(), scipy.signal._ltisys.StateSpace.__repr__(), scipy.signal._ltisys.StateSpace.__rmul__(), scipy.signal._ltisys.StateSpace._copy(), and scipy.signal._ltisys.StateSpaceContinuous.to_discrete().
error_const
int scipy.integrate._ivp.bdf.BDF.error_const = kappa * self.gamma + 1 / np.arange(1, MAX_ORDER + 2)
Definition at line 245 of file bdf.py.
error_norm_old
scipy.integrate._ivp.bdf.BDF.error_norm_old = None
Definition at line 213 of file bdf.py.
gamma
scipy.integrate._ivp.bdf.BDF.gamma = np.hstack((0, np.cumsum(1 / np.arange(1, MAX_ORDER + 1))))
Definition at line 243 of file bdf.py.
Referenced by sklearn.gaussian_process.kernels.PairwiseKernel.__call__(), sklearn.manifold._spectral_embedding.SpectralEmbedding._get_affinity_matrix(), sklearn.cluster._spectral.SpectralClustering.fit(), sklearn.decomposition._kernel_pca.KernelPCA.fit(), sklearn.kernel_approximation.RBFSampler.fit(), sklearn.svm._base.BaseLibSVM.fit(), sklearn.gaussian_process.kernels.PairwiseKernel.is_stationary(), sklearn.kernel_approximation.Nystroem.transform(), and sklearn.kernel_approximation.PolynomialCountSketch.transform().
h_abs
scipy.integrate._ivp.bdf.BDF.h_abs
Initial value:
=  select_initial_step(self.fun, self.t, self.y, f,
                                             self.direction, 1,
                                             self.rtol, self.atol)
Definition at line 207 of file bdf.py.
h_abs_old
scipy.integrate._ivp.bdf.BDF.h_abs_old = None
Definition at line 212 of file bdf.py.
I
scipy.integrate._ivp.bdf.BDF.I = I
Definition at line 240 of file bdf.py.
J
scipy.integrate._ivp.bdf.BDF.J = self._validate_jac(jac, jac_sparsity)
Definition at line 218 of file bdf.py.
jac
scipy.integrate._ivp.bdf.BDF.jac
Definition at line 218 of file bdf.py.
Referenced by scipy.optimize._optimize.MemoizeJac.__call__(), scipy.optimize._trustregion_dogleg.DoglegSubproblem.cauchy_point(), scipy.optimize.tests.test_slsqp.TestSLSQP.fprime_ieqcon2(), scipy.optimize._trustregion_constr.tr_interior_point.BarrierSubproblem.gradient_and_jacobian(), scipy.integrate._ode.ode.integrate(), scipy.optimize.tests.test_slsqp.TestSLSQP.jac(), scipy.optimize._trustregion.BaseQuadraticSubproblem.jac_mag(), scipy.optimize._trustregion_dogleg.DoglegSubproblem.newton_point(), scipy.integrate._ode.ode.set_initial_value(), scipy.integrate._ode.ode.set_integrator(), scipy.integrate._ode.ode.set_solout(), scipy.optimize._trustregion_exact.IterativeSubproblem.solve(), and scipy.optimize._trustregion_ncg.CGSteihaugSubproblem.solve().
jac_factor
scipy.integrate._ivp.bdf.BDF.jac_factor = None
Definition at line 217 of file bdf.py.
LU
scipy.integrate._ivp.bdf.BDF.LU = None
Definition at line 254 of file bdf.py.
lu
scipy.integrate._ivp.bdf.BDF.lu = lu
Definition at line 238 of file bdf.py.
max_step
scipy.integrate._ivp.bdf.BDF.max_step = validate_max_step(max_step)
Definition at line 203 of file bdf.py.
Referenced by scipy.integrate._ode.dop853.reset(), scipy.integrate._ode.dopri5.reset(), scipy.integrate._ode.lsoda.reset(), scipy.integrate._ode.vode.reset(), and scipy.integrate._ode.zvode.reset().
n_equal_steps
int scipy.integrate._ivp.bdf.BDF.n_equal_steps = 0
Definition at line 253 of file bdf.py.
newton_tol
scipy.integrate._ivp.bdf.BDF.newton_tol = max(10 * EPS / rtol, min(0.03, rtol ** 0.5))
Definition at line 215 of file bdf.py.
order
scipy.integrate._ivp.bdf.BDF.order = 1
Definition at line 252 of file bdf.py.
Referenced by sklearn.multioutput._BaseChain.fit(), scipy.integrate._ode.vode.reset(), scipy.integrate._ode.zvode.reset(), sklearn.preprocessing._polynomial.PolynomialFeatures.transform(), and sklearn.preprocessing._polynomial.SplineTransformer.transform().
rtol
scipy.integrate._ivp.bdf.BDF.rtol
Definition at line 204 of file bdf.py.
Referenced by scipy.optimize._zeros_py.TOMS748Solver.get_status(), scipy.optimize._zeros_py.TOMS748Solver.iterate(), scipy.integrate._ode.dop853.reset(), scipy.integrate._ode.dopri5.reset(), scipy.integrate._ode.lsoda.reset(), scipy.integrate._ode.vode.reset(), scipy.integrate._ode.zvode.reset(), scipy.optimize.tests.test_zeros.TestScalarRootFinders.run_tests(), sklearn.neighbors._kde.KernelDensity.score_samples(), scipy.stats.tests.test_resampling.TestPermutationTest.test_against_spearmanr_in_R(), and scipy.stats.tests.test_resampling.TestPermutationTest.test_with_ties().
solve_lu
scipy.integrate._ivp.bdf.BDF.solve_lu = solve_lu
Definition at line 239 of file bdf.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/integrate/_ivp/bdf.py