Code Cloning Analysis: pandas.io.stata.StataNonCatValueLabel Class Reference
pandas.io.stata.StataNonCatValueLabel Class Reference
Public Member Functions
None __init__ (self, str labname, dict[float, str] value_labels, Literal["latin-1", "utf-8"] encoding="latin-1")
Public Member Functions inherited from pandas.io.stata.StataValueLabel
None __init__ (self, Series catarray, Literal["latin-1", "utf-8"] encoding="latin-1")
bytes generate_value_label (self, str byteorder)
Additional Inherited Members
Public Attributes inherited from pandas.io.stata.StataValueLabel
labname = catarray.name
value_labels = enumerate(categories)
int text_len = 0
list txt = []
int n = 0
off = np.array([], dtype=np.int32)
val = np.array([], dtype=np.int32)
int len = 0
Protected Member Functions inherited from pandas.io.stata.StataValueLabel
None _prepare_value_labels (self)
Protected Attributes inherited from pandas.io.stata.StataValueLabel
_encoding = encoding
Detailed Description
Prepare formatted version of value labels
Parameters
----------
labname : str
    Value label name
value_labels: Dictionary
    Mapping of values to labels
encoding : {"latin-1", "utf-8"}
    Encoding to use for value labels.
Definition at line 796 of file stata.py.
Constructor & Destructor Documentation
__init__()
None pandas.io.stata.StataNonCatValueLabel.__init__ (self, str labname, dict[float, str] value_labels, Literal["latin-1", "utf-8"] encoding = "latin-1")
Definition at line 810 of file stata.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/io/stata.py