Code Cloning Analysis: fontTools.misc.lazyTools.LazyList Class Reference
fontTools.misc.lazyTools.LazyList Class Reference
Public Member Functions
__getitem__ (self, k)
__add__ (self, other)
__radd__ (self, other)
Detailed Description
Definition at line 19 of file lazyTools.py.
Member Function Documentation
__add__()
fontTools.misc.lazyTools.LazyList.__add__ (self, other)
Definition at line 30 of file lazyTools.py.
Referenced by scipy.signal._ltisys.StateSpace.__add__(), scipy.sparse.linalg._interface.LinearOperator._rdot(), and scipy.sparse._base._spbase.power().
__getitem__()
fontTools.misc.lazyTools.LazyList.__getitem__ (self, k)
Definition at line 20 of file lazyTools.py.
__radd__()
fontTools.misc.lazyTools.LazyList.__radd__ (self, other)
Definition at line 39 of file lazyTools.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/misc/lazyTools.py