Code Cloning Analysis: pytz.tzfile Namespace Reference
pytz.tzfile Namespace Reference
Functions
_byte_string (s)
_std_string (s)
build_tzinfo (zone, fp)
Variables
_NULL = _byte_string('\0')
base = os.path.join(os.path.dirname(__file__), 'zoneinfo')
tz
Detailed Description
$Id: tzfile.py,v 1.8 2004/06/03 00:15:24 zenzen Exp $
Function Documentation
_byte_string()
pytz.tzfile._byte_string (s) protected
Cast a string or byte string to an ASCII byte string.
Definition at line 12 of file tzfile.py.
References _byte_string().
Referenced by _byte_string(), and _std_string().
_std_string()
pytz.tzfile._std_string (s) protected
Cast a string or byte string to an ASCII string.
Definition at line 19 of file tzfile.py.
References _byte_string(), and _std_string().
Referenced by _std_string().
build_tzinfo()
pytz.tzfile.build_tzinfo (zone, fp)
Definition at line 24 of file tzfile.py.
Variable Documentation
_NULL
pytz.tzfile._NULL = _byte_string('\0') protected
Definition at line 16 of file tzfile.py.
base
pytz.tzfile.base = os.path.join(os.path.dirname(__file__), 'zoneinfo')
Definition at line 128 of file tzfile.py.
tz
pytz.tzfile.tz
Initial value:
=  build_tzinfo('Australia/Melbourne',
                      open(os.path.join(base, 'Australia', 'Melbourne'), 'rb'))
Definition at line 129 of file tzfile.py.