Code Cloning Analysis: scipy.linalg.tests.test_sketches.TestClarksonWoodruffTransform Class Reference
scipy.linalg.tests.test_sketches.TestClarksonWoodruffTransform Class Reference
Public Member Functions
test_sketch_dimensions (self)
test_seed_returns_identical_transform_matrix (self)
test_seed_returns_identically (self)
test_sketch_preserves_frobenius_norm (self)
test_sketch_preserves_vector_norm (self)
Static Public Attributes
rng = np.random.RandomState(seed=1179103485)
int n_rows = 2000
int n_cols = 100
float density = 0.1
int n_sketch_rows = 200
list seeds
A_dense = rng.randn(n_rows, n_cols)
A_csc
A_csr
A_coo
list test_matrices
x = rng.randn(n_rows, 1) / np.sqrt(n_rows)
Detailed Description
Testing the Clarkson Woodruff Transform
Definition at line 11 of file test_sketches.py.
Member Function Documentation
test_seed_returns_identical_transform_matrix()
scipy.linalg.tests.test_sketches.TestClarksonWoodruffTransform.test_seed_returns_identical_transform_matrix (self)
Definition at line 57 of file test_sketches.py.
test_seed_returns_identically()
scipy.linalg.tests.test_sketches.TestClarksonWoodruffTransform.test_seed_returns_identically (self)
Definition at line 68 of file test_sketches.py.
test_sketch_dimensions()
scipy.linalg.tests.test_sketches.TestClarksonWoodruffTransform.test_sketch_dimensions (self)
Definition at line 49 of file test_sketches.py.
test_sketch_preserves_frobenius_norm()
scipy.linalg.tests.test_sketches.TestClarksonWoodruffTransform.test_sketch_preserves_frobenius_norm (self)
Definition at line 83 of file test_sketches.py.
test_sketch_preserves_vector_norm()
scipy.linalg.tests.test_sketches.TestClarksonWoodruffTransform.test_sketch_preserves_vector_norm (self)
Definition at line 106 of file test_sketches.py.
Member Data Documentation
A_coo
scipy.linalg.tests.test_sketches.TestClarksonWoodruffTransform.A_coo static
Initial value:
=  rand(
        n_rows, n_cols, density=density, format='coo', random_state=rng,
    )
Definition at line 37 of file test_sketches.py.
A_csc
scipy.linalg.tests.test_sketches.TestClarksonWoodruffTransform.A_csc static
Initial value:
=  rand(
        n_rows, n_cols, density=density, format='csc', random_state=rng,
    )
Definition at line 31 of file test_sketches.py.
A_csr
scipy.linalg.tests.test_sketches.TestClarksonWoodruffTransform.A_csr static
Initial value:
=  rand(
        n_rows, n_cols, density=density, format='csr', random_state=rng,
    )
Definition at line 34 of file test_sketches.py.
A_dense
scipy.linalg.tests.test_sketches.TestClarksonWoodruffTransform.A_dense = rng.randn(n_rows, n_cols) static
Definition at line 30 of file test_sketches.py.
density
float scipy.linalg.tests.test_sketches.TestClarksonWoodruffTransform.density = 0.1 static
Definition at line 21 of file test_sketches.py.
Referenced by sklearn.random_projection.SparseRandomProjection._make_random_matrix().
n_cols
int scipy.linalg.tests.test_sketches.TestClarksonWoodruffTransform.n_cols = 100 static
Definition at line 20 of file test_sketches.py.
n_rows
int scipy.linalg.tests.test_sketches.TestClarksonWoodruffTransform.n_rows = 2000 static
Definition at line 19 of file test_sketches.py.
n_sketch_rows
int scipy.linalg.tests.test_sketches.TestClarksonWoodruffTransform.n_sketch_rows = 200 static
Definition at line 24 of file test_sketches.py.
rng
scipy.linalg.tests.test_sketches.TestClarksonWoodruffTransform.rng = np.random.RandomState(seed=1179103485) static
Definition at line 16 of file test_sketches.py.
Referenced by scipy.stats._qmc.PoissonDisk._hypersphere_surface_sample(), scipy.stats._qmc.PoissonDisk._hypersphere_volume_sample(), scipy.stats._qmc.Halton._initialize_permutations(), scipy.stats._qmc.PoissonDisk._random(), scipy.stats._qmc.LatinHypercube._random_lhs(), scipy.stats._qmc.LatinHypercube._random_oa_lhs(), scipy.stats._qmc.Sobol._scramble(), sklearn.gaussian_process._gpc._BinaryGaussianProcessClassifierLaplace.fit(), and scipy.stats._qmc.QMCEngine.reset().
seeds
list scipy.linalg.tests.test_sketches.TestClarksonWoodruffTransform.seeds static
Initial value:
=  [1755490010, 934377150, 1391612830, 1752708722, 2008891431,
             1302443994, 1521083269, 1501189312, 1126232505, 1533465685]
Definition at line 27 of file test_sketches.py.
Referenced by sklearn.cluster._mean_shift.MeanShift.fit().
test_matrices
list scipy.linalg.tests.test_sketches.TestClarksonWoodruffTransform.test_matrices static
Initial value:
=  [
        A_dense, A_csc, A_csr, A_coo,
    ]
Definition at line 42 of file test_sketches.py.
x
scipy.linalg.tests.test_sketches.TestClarksonWoodruffTransform.x = rng.randn(n_rows, 1) / np.sqrt(n_rows) static
Definition at line 47 of file test_sketches.py.
Referenced by scipy.optimize._root_scalar.MemoizeDer.__call__(), scipy.optimize._shgo_lib._vertex.VertexBase.__init__(), scipy.optimize._differentialevolution.DifferentialEvolutionSolver.__next__(), scipy.optimize._basinhopping.BasinHoppingRunner._monte_carlo_step(), matplotlib.widgets.ToolHandles.closest(), scipy.optimize._root_scalar.MemoizeDer.fprime(), scipy.optimize._root_scalar.MemoizeDer.fprime2(), scipy.optimize._basinhopping.BasinHoppingRunner.one_cycle(), scipy.optimize._differentialevolution.DifferentialEvolutionSolver.solve(), and scipy.spatial.tests.test_kdtree._Test_sorted_query_ball_point.test_return_sorted_None().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/linalg/tests/test_sketches.py