Code Cloning Analysis: sklearn.covariance._robust_covariance Namespace Reference
sklearn.covariance._robust_covariance Namespace Reference
Classes
class MinCovDet
Functions
c_step (X, n_support, remaining_iterations=30, initial_estimates=None, verbose=False, cov_computation_method=empirical_covariance, random_state=None)
_c_step (X, n_support, random_state, remaining_iterations=30, initial_estimates=None, verbose=False, cov_computation_method=empirical_covariance)
select_candidates (X, n_support, n_trials, select=1, n_iter=30, verbose=False, cov_computation_method=empirical_covariance, random_state=None)
fast_mcd (X, support_fraction=None, cov_computation_method=empirical_covariance, random_state=None)
Detailed Description
Robust location and covariance estimators.
Here are implemented estimators that are resistant to outliers.
Function Documentation
_c_step()
sklearn.covariance._robust_covariance._c_step (X, n_support, random_state, remaining_iterations = 30, initial_estimates = None, verbose = False, cov_computation_method = empirical_covariance) protected
Definition at line 111 of file _robust_covariance.py.
c_step()
sklearn.covariance._robust_covariance.c_step (X, n_support, remaining_iterations = 30, initial_estimates = None, verbose = False, cov_computation_method = empirical_covariance, random_state = None)
C_step procedure described in [Rouseeuw1984]_ aiming at computing MCD.
Parameters
----------
X : array-like of shape (n_samples, n_features)
    Data set in which we look for the n_support observations whose
    scatter matrix has minimum determinant.
n_support : int
    Number of observations to compute the robust estimates of location
    and covariance from. This parameter must be greater than
    `n_samples / 2`.
remaining_iterations : int, default=30
    Number of iterations to perform.
    According to [Rouseeuw1999]_, two iterations are sufficient to get
    close to the minimum, and we never need more than 30 to reach
    convergence.
initial_estimates : tuple of shape (2,), default=None
    Initial estimates of location and shape from which to run the c_step
    procedure:
    - initial_estimates[0]: an initial location estimate
    - initial_estimates[1]: an initial covariance estimate
verbose : bool, default=False
    Verbose mode.
cov_computation_method : callable, \
        default=:func:`sklearn.covariance.empirical_covariance`
    The function which will be used to compute the covariance.
    Must return array of shape (n_features, n_features).
random_state : int, RandomState instance or None, default=None
    Determines the pseudo random number generator for shuffling the data.
    Pass an int for reproducible results across multiple function calls.
    See :term:`Glossary <random_state>`.
Returns
-------
location : ndarray of shape (n_features,)
    Robust location estimates.
covariance : ndarray of shape (n_features, n_features)
    Robust covariance estimates.
support : ndarray of shape (n_samples,)
    A mask for the `n_support` observations whose scatter matrix has
    minimum determinant.
References
----------
.. [Rouseeuw1999] A Fast Algorithm for the Minimum Covariance Determinant
    Estimator, 1999, American Statistical Association and the American
    Society for Quality, TECHNOMETRICS
Definition at line 33 of file _robust_covariance.py.
fast_mcd()
sklearn.covariance._robust_covariance.fast_mcd (X, support_fraction = None, cov_computation_method = empirical_covariance, random_state = None)
Estimate the Minimum Covariance Determinant matrix.
Read more in the :ref:`User Guide <robust_covariance>`.
Parameters
----------
X : array-like of shape (n_samples, n_features)
    The data matrix, with p features and n samples.
support_fraction : float, default=None
    The proportion of points to be included in the support of the raw
    MCD estimate. Default is `None`, which implies that the minimum
    value of `support_fraction` will be used within the algorithm:
    `(n_samples + n_features + 1) / 2 * n_samples`. This parameter must be
    in the range (0, 1).
cov_computation_method : callable, \
        default=:func:`sklearn.covariance.empirical_covariance`
    The function which will be used to compute the covariance.
    Must return an array of shape (n_features, n_features).
random_state : int, RandomState instance or None, default=None
    Determines the pseudo random number generator for shuffling the data.
    Pass an int for reproducible results across multiple function calls.
    See :term:`Glossary <random_state>`.
Returns
-------
location : ndarray of shape (n_features,)
    Robust location of the data.
covariance : ndarray of shape (n_features, n_features)
    Robust covariance of the features.
support : ndarray of shape (n_samples,), dtype=bool
    A mask of the observations that have been used to compute
    the robust location and covariance estimates of the data set.
Notes
-----
The FastMCD algorithm has been introduced by Rousseuw and Van Driessen
in "A Fast Algorithm for the Minimum Covariance Determinant Estimator,
1999, American Statistical Association and the American Society
for Quality, TECHNOMETRICS".
The principle is to compute robust estimates and random subsets before
pooling them into a larger subsets, and finally into the full data set.
Depending on the size of the initial sample, we have one, two or three
such computation levels.
Note that only raw estimates are returned. If one is interested in
the correction and reweighting steps described in [RouseeuwVan]_,
see the MinCovDet object.
References
----------
.. [RouseeuwVan] A Fast Algorithm for the Minimum Covariance
    Determinant Estimator, 1999, American Statistical Association
    and the American Society for Quality, TECHNOMETRICS
.. [Butler1993] R. W. Butler, P. L. Davies and M. Jhun,
    Asymptotics For The Minimum Covariance Determinant Estimator,
    The Annals of Statistics, 1993, Vol. 21, No. 3, 1385-1400
Definition at line 359 of file _robust_covariance.py.
References select_candidates().
Referenced by sklearn.covariance._robust_covariance.MinCovDet.fit().
select_candidates()
sklearn.covariance._robust_covariance.select_candidates (X, n_support, n_trials, select = 1, n_iter = 30, verbose = False, cov_computation_method = empirical_covariance, random_state = None)
Finds the best pure subset of observations to compute MCD from it.
The purpose of this function is to find the best sets of n_support
observations with respect to a minimization of their covariance
matrix determinant. Equivalently, it removes n_samples-n_support
observations to construct what we call a pure data set (i.e. not
containing outliers). The list of the observations of the pure
data set is referred to as the `support`.
Starting from a random support, the pure data set is found by the
c_step procedure introduced by Rousseeuw and Van Driessen in
[RV]_.
Parameters
----------
X : array-like of shape (n_samples, n_features)
    Data (sub)set in which we look for the n_support purest observations.
n_support : int
    The number of samples the pure data set must contain.
    This parameter must be in the range `[(n + p + 1)/2] < n_support < n`.
n_trials : int or tuple of shape (2,)
    Number of different initial sets of observations from which to
    run the algorithm. This parameter should be a strictly positive
    integer.
    Instead of giving a number of trials to perform, one can provide a
    list of initial estimates that will be used to iteratively run
    c_step procedures. In this case:
    - n_trials[0]: array-like, shape (n_trials, n_features)
      is the list of `n_trials` initial location estimates
    - n_trials[1]: array-like, shape (n_trials, n_features, n_features)
      is the list of `n_trials` initial covariances estimates
select : int, default=1
    Number of best candidates results to return. This parameter must be
    a strictly positive integer.
n_iter : int, default=30
    Maximum number of iterations for the c_step procedure.
    (2 is enough to be close to the final solution. "Never" exceeds 20).
    This parameter must be a strictly positive integer.
verbose : bool, default=False
    Control the output verbosity.
cov_computation_method : callable, \
        default=:func:`sklearn.covariance.empirical_covariance`
    The function which will be used to compute the covariance.
    Must return an array of shape (n_features, n_features).
random_state : int, RandomState instance or None, default=None
    Determines the pseudo random number generator for shuffling the data.
    Pass an int for reproducible results across multiple function calls.
    See :term:`Glossary <random_state>`.
See Also
---------
c_step
Returns
-------
best_locations : ndarray of shape (select, n_features)
    The `select` location estimates computed from the `select` best
    supports found in the data set (`X`).
best_covariances : ndarray of shape (select, n_features, n_features)
    The `select` covariance estimates computed from the `select`
    best supports found in the data set (`X`).
best_supports : ndarray of shape (select, n_samples)
    The `select` best supports found in the data set (`X`).
References
----------
.. [RV] A Fast Algorithm for the Minimum Covariance Determinant
    Estimator, 1999, American Statistical Association and the American
    Society for Quality, TECHNOMETRICS
Definition at line 213 of file _robust_covariance.py.
Referenced by fast_mcd().