Code Cloning Analysis: sklearn.base.BaseEstimator Class Reference
sklearn.base.BaseEstimator Class Reference
Inherits sklearn.utils._repr_html.base.ReprHTMLMixin, sklearn.utils._repr_html.base._HTMLDocumentationLinkMixin, and sklearn.utils._metadata_requests._MetadataRequester.
Inherited by sklearn.calibration.CalibratedClassifierCV, sklearn.calibration._SigmoidCalibration, sklearn.cluster._affinity_propagation.AffinityPropagation, sklearn.cluster._agglomerative.AgglomerativeClustering, sklearn.cluster._bicluster.BaseSpectral, sklearn.cluster._birch.Birch, sklearn.cluster._dbscan.DBSCAN, sklearn.cluster._hdbscan.hdbscan.HDBSCAN, sklearn.cluster._kmeans._BaseKMeans, sklearn.cluster._mean_shift.MeanShift, sklearn.cluster._optics.OPTICS, sklearn.cluster._spectral.SpectralClustering, sklearn.cluster.tests.test_bicluster.MockBiclustering, sklearn.compose._target.TransformedTargetRegressor, sklearn.compose.tests.test_column_transformer.DoubleTrans, sklearn.compose.tests.test_column_transformer.PandasOutTransformer, sklearn.compose.tests.test_column_transformer.SparseMatrixTrans, sklearn.compose.tests.test_column_transformer.Trans, sklearn.compose.tests.test_column_transformer.TransNo2D, sklearn.compose.tests.test_column_transformer.TransRaise, sklearn.compose.tests.test_target.DummyCheckerArrayTransformer, sklearn.compose.tests.test_target.DummyTransformer, sklearn.covariance._empirical_covariance.EmpiricalCovariance, sklearn.cross_decomposition._pls.PLSSVD, sklearn.cross_decomposition._pls._PLS, sklearn.decomposition._base._BasePCA, sklearn.decomposition._dict_learning.DictionaryLearning, sklearn.decomposition._dict_learning.MiniBatchDictionaryLearning, sklearn.decomposition._dict_learning.SparseCoder, sklearn.decomposition._factor_analysis.FactorAnalysis, sklearn.decomposition._fastica.FastICA, sklearn.decomposition._kernel_pca.KernelPCA, sklearn.decomposition._lda.LatentDirichletAllocation, sklearn.decomposition._nmf._BaseNMF, sklearn.decomposition._sparse_pca._BaseSparsePCA, sklearn.decomposition._truncated_svd.TruncatedSVD, sklearn.discriminant_analysis.LinearDiscriminantAnalysis, sklearn.discriminant_analysis.QuadraticDiscriminantAnalysis, sklearn.dummy.DummyClassifier, sklearn.dummy.DummyRegressor, sklearn.ensemble._base.BaseEnsemble, sklearn.ensemble._hist_gradient_boosting.binning._BinMapper, sklearn.ensemble._hist_gradient_boosting.gradient_boosting.BaseHistGradientBoosting, sklearn.ensemble.tests.test_bagging.DummySizeEstimator, sklearn.ensemble.tests.test_bagging.DummyZeroEstimator, sklearn.ensemble.tests.test_stacking.NoWeightClassifier, sklearn.ensemble.tests.test_stacking.NoWeightRegressor, sklearn.feature_extraction._dict_vectorizer.DictVectorizer, sklearn.feature_extraction._hash.FeatureHasher, sklearn.feature_extraction.image.PatchExtractor, sklearn.feature_extraction.text.CountVectorizer, sklearn.feature_extraction.text.HashingVectorizer, sklearn.feature_extraction.text.TfidfTransformer, sklearn.feature_selection._from_model.SelectFromModel, sklearn.feature_selection._rfe.RFE, sklearn.feature_selection._sequential.SequentialFeatureSelector, sklearn.feature_selection._univariate_selection._BaseFilter, sklearn.feature_selection._variance_threshold.VarianceThreshold, sklearn.feature_selection.tests.test_base.StepSelector, sklearn.feature_selection.tests.test_from_model.FixedImportanceEstimator, sklearn.feature_selection.tests.test_from_model.NaNTag, sklearn.feature_selection.tests.test_from_model.NoNaNTag, sklearn.feature_selection.tests.test_rfe.MockClassifier, sklearn.frozen._frozen.FrozenEstimator, sklearn.gaussian_process._gpc.GaussianProcessClassifier, sklearn.gaussian_process._gpc._BinaryGaussianProcessClassifierLaplace, sklearn.gaussian_process._gpr.GaussianProcessRegressor, sklearn.impute._base.MissingIndicator, sklearn.impute._base._BaseImputer, sklearn.inspection.tests.test_partial_dependence.NoPredictProbaNoDecisionFunction, sklearn.isotonic.IsotonicRegression, sklearn.kernel_approximation.AdditiveChi2Sampler, sklearn.kernel_approximation.Nystroem, sklearn.kernel_approximation.PolynomialCountSketch, sklearn.kernel_approximation.RBFSampler, sklearn.kernel_approximation.SkewedChi2Sampler, sklearn.kernel_ridge.KernelRidge, sklearn.linear_model._base.LinearModel, sklearn.linear_model._glm.glm._GeneralizedLinearRegressor, sklearn.linear_model._huber.HuberRegressor, sklearn.linear_model._logistic.LogisticRegression, sklearn.linear_model._logistic.LogisticRegressionCV, sklearn.linear_model._quantile.QuantileRegressor, sklearn.linear_model._ransac.RANSACRegressor, sklearn.linear_model._ridge._IdentityClassifier, sklearn.linear_model._ridge._IdentityRegressor, sklearn.linear_model._stochastic_gradient.BaseSGD, sklearn.manifold._isomap.Isomap, sklearn.manifold._locally_linear.LocallyLinearEmbedding, sklearn.manifold._mds.MDS, sklearn.manifold._spectral_embedding.SpectralEmbedding, sklearn.manifold._t_sne.TSNE, sklearn.metrics.tests.test_score_objects.EstimatorWithFit, sklearn.metrics.tests.test_score_objects.EstimatorWithFitAndPredict, sklearn.metrics.tests.test_score_objects.EstimatorWithFitAndScore, sklearn.mixture._base.BaseMixture, sklearn.model_selection._classification_threshold.BaseThresholdClassifier, sklearn.model_selection._search.BaseSearchCV, sklearn.model_selection.tests.test_search.BrokenClassifier, sklearn.model_selection.tests.test_search.FailingClassifier, sklearn.model_selection.tests.test_search.MockClassifier, sklearn.model_selection.tests.test_validation.DataDependentFailingClassifier, sklearn.model_selection.tests.test_validation.MockClassifier, sklearn.model_selection.tests.test_validation.MockEstimatorWithParameter, sklearn.model_selection.tests.test_validation.MockImprovingEstimator, sklearn.multiclass.OneVsOneClassifier, sklearn.multiclass.OneVsRestClassifier, sklearn.multiclass.OutputCodeClassifier, sklearn.multiclass._ConstantPredictor, sklearn.multioutput._BaseChain, sklearn.multioutput._MultiOutputEstimator, sklearn.naive_bayes._BaseNB, sklearn.neighbors._base.NeighborsBase, sklearn.neighbors._kde.KernelDensity, sklearn.neighbors._nca.NeighborhoodComponentsAnalysis, sklearn.neighbors._nearest_centroid.NearestCentroid, sklearn.neural_network._multilayer_perceptron.BaseMultilayerPerceptron, sklearn.neural_network._rbm.BernoulliRBM, sklearn.preprocessing._data.Binarizer, sklearn.preprocessing._data.KernelCenterer, sklearn.preprocessing._data.MaxAbsScaler, sklearn.preprocessing._data.MinMaxScaler, sklearn.preprocessing._data.Normalizer, sklearn.preprocessing._data.PowerTransformer, sklearn.preprocessing._data.QuantileTransformer, sklearn.preprocessing._data.RobustScaler, sklearn.preprocessing._data.StandardScaler, sklearn.preprocessing._discretization.KBinsDiscretizer, sklearn.preprocessing._encoders._BaseEncoder, sklearn.preprocessing._function_transformer.FunctionTransformer, sklearn.preprocessing._label.LabelBinarizer, sklearn.preprocessing._label.LabelEncoder, sklearn.preprocessing._label.MultiLabelBinarizer, sklearn.preprocessing._polynomial.PolynomialFeatures, sklearn.preprocessing._polynomial.SplineTransformer, sklearn.random_projection.BaseRandomProjection, sklearn.semi_supervised._label_propagation.BaseLabelPropagation, sklearn.semi_supervised._self_training.SelfTrainingClassifier, sklearn.svm._base.BaseLibSVM, sklearn.svm._classes.LinearSVC, sklearn.tests.metadata_routing_common.ConsumingClassifier, sklearn.tests.metadata_routing_common.ConsumingNoFitTransformTransformer, sklearn.tests.metadata_routing_common.ConsumingRegressor, sklearn.tests.metadata_routing_common.ConsumingTransformer, sklearn.tests.metadata_routing_common.MetaRegressor, sklearn.tests.metadata_routing_common.MetaTransformer, sklearn.tests.metadata_routing_common.NonConsumingClassifier, sklearn.tests.metadata_routing_common.NonConsumingRegressor, sklearn.tests.metadata_routing_common.WeightedMetaClassifier, sklearn.tests.metadata_routing_common.WeightedMetaRegressor, sklearn.tests.test_base.Buggy, sklearn.tests.test_base.EmptyEstimator, sklearn.tests.test_base.K, sklearn.tests.test_base.ModifyInitParams, sklearn.tests.test_base.MultiInheritanceEstimator, sklearn.tests.test_base.MyEstimator, sklearn.tests.test_base.NaNTag, sklearn.tests.test_base.NoNaNTag, sklearn.tests.test_base.SingleInheritanceEstimator, sklearn.tests.test_base.T, sklearn.tests.test_base.VargEstimator, sklearn.tests.test_common.CallableEstimator, sklearn.tests.test_metadata_routing.SimplePipeline, sklearn.tests.test_pipeline.DummyEstimatorParams, sklearn.tests.test_pipeline.FeatureNameSaver, sklearn.tests.test_pipeline.FitParamT, sklearn.tests.test_pipeline.Mult, sklearn.tests.test_pipeline.NoFit, sklearn.tests.test_pipeline.SimpleEstimator, sklearn.tree._classes.BaseDecisionTree, sklearn.utils._mocking.CheckingClassifier, sklearn.utils._mocking.NoSampleWeightWrapper, sklearn.utils._mocking._MockEstimatorOnOffPrediction, sklearn.utils.metaestimators._BaseComposition, sklearn.utils.tests.test_array_api.SimpleEstimator, sklearn.utils.tests.test_estimator_checks.BadTransformerWithoutMixin, sklearn.utils.tests.test_estimator_checks.BaseBadClassifier, sklearn.utils.tests.test_estimator_checks.BrokenArrayAPI, sklearn.utils.tests.test_estimator_checks.ChangesDict, sklearn.utils.tests.test_estimator_checks.ChangesUnderscoreAttribute, sklearn.utils.tests.test_estimator_checks.ChangesWrongAttribute, sklearn.utils.tests.test_estimator_checks.EstimatorInconsistentForPandas, sklearn.utils.tests.test_estimator_checks.HasImmutableParameters, sklearn.utils.tests.test_estimator_checks.HasMutableParameters, sklearn.utils.tests.test_estimator_checks.LargeSparseNotSupportedClassifier, sklearn.utils.tests.test_estimator_checks.ModifiesAnotherValue, sklearn.utils.tests.test_estimator_checks.ModifiesValueInsteadOfRaisingError, sklearn.utils.tests.test_estimator_checks.NoSampleWeightPandasSeriesType, sklearn.utils.tests.test_estimator_checks.NotInvariantPredict, sklearn.utils.tests.test_estimator_checks.NotInvariantSampleOrder, sklearn.utils.tests.test_estimator_checks.PartialFitChecksName, sklearn.utils.tests.test_estimator_checks.RaisesErrorInSetParams, sklearn.utils.tests.test_estimator_checks.SetsWrongAttribute, sklearn.utils.tests.test_estimator_checks.SparseTransformer, sklearn.utils.tests.test_estimator_checks._BaseMultiLabelClassifierMock, sklearn.utils.tests.test_param_validation._Estimator, sklearn.utils.tests.test_pprint.CountVectorizer, sklearn.utils.tests.test_pprint.GridSearchCV, sklearn.utils.tests.test_pprint.LogisticRegression, sklearn.utils.tests.test_pprint.NMF, sklearn.utils.tests.test_pprint.PCA, sklearn.utils.tests.test_pprint.Pipeline, sklearn.utils.tests.test_pprint.RFE, sklearn.utils.tests.test_pprint.SVC, sklearn.utils.tests.test_pprint.SimpleImputer, sklearn.utils.tests.test_pprint.StandardScaler, sklearn.utils.tests.test_tags.EmptyRegressor, sklearn.utils.tests.test_tags.EmptyTransformer, and sklearn.utils.tests.test_validation.PassthroughTransformer.
Public Member Functions
get_params (self, deep=True)
set_params (self, **params)
__sklearn_clone__ (self)
__repr__ (self, N_CHAR_MAX=700)
__getstate__ (self)
__setstate__ (self, state)
__sklearn_tags__ (self)
Public Member Functions inherited from sklearn.utils._metadata_requests._MetadataRequester
set_fit_request (self, **kwargs)
set_partial_fit_request (self, **kwargs)
set_predict_request (self, **kwargs)
set_predict_proba_request (self, **kwargs)
set_predict_log_proba_request (self, **kwargs)
set_decision_function_request (self, **kwargs)
set_score_request (self, **kwargs)
set_split_request (self, **kwargs)
set_transform_request (self, **kwargs)
set_inverse_transform_request (self, **kwargs)
__init_subclass__ (cls, **kwargs)
get_metadata_routing (self)
Protected Member Functions
_get_param_names (cls)
_get_params_html (self, deep=True)
_validate_params (self)
Protected Member Functions inherited from sklearn.utils._repr_html.base.ReprHTMLMixin
_repr_html_ (self)
_repr_html_inner (self)
_repr_mimebundle_ (self, **kwargs)
Protected Member Functions inherited from sklearn.utils._repr_html.base._HTMLDocumentationLinkMixin
_doc_link_template (self)
_doc_link_template (self, value)
_get_doc_link (self)
Protected Member Functions inherited from sklearn.utils._metadata_requests._MetadataRequester
_build_request_for_signature (cls, router, method)
_get_default_requests (cls)
_get_metadata_request (self)
Protected Attributes
_parameter_constraints
Static Protected Attributes
_html_repr = estimator_html_repr
Static Protected Attributes inherited from sklearn.utils._repr_html.base._HTMLDocumentationLinkMixin
str _doc_link_module = "sklearn"
_doc_link_url_param_generator = None
Detailed Description
Base class for all estimators in scikit-learn.
Inheriting from this class provides default implementations of:
- setting and getting parameters used by `GridSearchCV` and friends;
- textual and HTML representation displayed in terminals and IDEs;
- estimator serialization;
- parameters validation;
- data validation;
- feature names validation.
Read more in the :ref:`User Guide <rolling_your_own_estimator>`.
Notes
-----
All estimators should specify all the parameters that can be set
at the class level in their ``__init__`` as explicit keyword
arguments (no ``*args`` or ``**kwargs``).
Examples
--------
>>> import numpy as np
>>> from sklearn.base import BaseEstimator
>>> class MyEstimator(BaseEstimator):
...     def __init__(self, *, param=1):
...         self.param = param
...     def fit(self, X, y=None):
...         self.is_fitted_ = True
...         return self
...     def predict(self, X):
...         return np.full(shape=X.shape[0], fill_value=self.param)
>>> estimator = MyEstimator(param=2)
>>> estimator.get_params()
{'param': 2}
>>> X = np.array([[1, 2], [2, 3], [3, 4]])
>>> y = np.array([1, 0, 1])
>>> estimator.fit(X, y).predict(X)
array([2, 2, 2])
>>> estimator.set_params(param=3).fit(X, y).predict(X)
array([3, 3, 3])
Definition at line 156 of file base.py.
Member Function Documentation
__getstate__()
sklearn.base.BaseEstimator.__getstate__ (self)
Definition at line 416 of file base.py.
__repr__()
sklearn.base.BaseEstimator.__repr__ (self, N_CHAR_MAX = 700)
Definition at line 364 of file base.py.
__setstate__()
sklearn.base.BaseEstimator.__setstate__ (self, state)
Definition at line 438 of file base.py.
__sklearn_clone__()
sklearn.base.BaseEstimator.__sklearn_clone__ (self)
Definition at line 361 of file base.py.
__sklearn_tags__()
sklearn.base.BaseEstimator.__sklearn_tags__ (self)
Definition at line 454 of file base.py.
Referenced by sklearn.feature_selection._sequential.SequentialFeatureSelector.fit(), sklearn.multiclass.OneVsOneClassifier.fit(), and sklearn.tree._classes.BaseDecisionTree.get_n_leaves().
_get_param_names()
sklearn.base.BaseEstimator._get_param_names (cls) protected
Get parameter names for the estimator
Definition at line 203 of file base.py.
Referenced by sklearn.utils._metadata_requests.MetadataRouter._route_params(), and sklearn.utils._metadata_requests.MetadataRouter.validate_metadata().
_get_params_html()
sklearn.base.BaseEstimator._get_params_html (self, deep = True) protected
Get parameters for this estimator with a specific HTML representation.
Parameters
----------
deep : bool, default=True
    If True, will return the parameters for this estimator and
    contained subobjects that are estimators.
Returns
-------
params : ParamsDict
    Parameter names mapped to their values. We return a `ParamsDict`
    dictionary, which renders a specific HTML representation in table
    form.
Definition at line 257 of file base.py.
_validate_params()
sklearn.base.BaseEstimator._validate_params (self) protected
Validate types and values of constructor parameters
The expected type and values must be defined in the `_parameter_constraints`
class attribute, which is a dictionary `param_name: list of constraints`. See
the docstring of `validate_parameter_constraints` for a description of the
accepted constraints.
Definition at line 463 of file base.py.
get_params()
sklearn.base.BaseEstimator.get_params (self, deep = True)
Get parameters for this estimator.
Parameters
----------
deep : bool, default=True
    If True, will return the parameters for this estimator and
    contained subobjects that are estimators.
Returns
-------
params : dict
    Parameter names mapped to their values.
Reimplemented in sklearn.compose._column_transformer.ColumnTransformer, sklearn.ensemble._base._BaseHeterogeneousEnsemble, sklearn.feature_selection.tests.test_rfe.MockClassifier, sklearn.frozen._frozen.FrozenEstimator, sklearn.model_selection.tests.test_search.MockClassifier, sklearn.model_selection.tests.test_successive_halving.FastClassifier, sklearn.model_selection.tests.test_validation.MockClassifier, sklearn.pipeline.FeatureUnion, sklearn.pipeline.Pipeline, and sklearn.tests.test_pipeline.NoTrans.
Definition at line 233 of file base.py.
Referenced by sklearn.impute._iterative.IterativeImputer._initial_imputation(), sklearn.gaussian_process.kernels.Kernel.bounds(), sklearn.linear_model._coordinate_descent.LinearModelCV.fit(), sklearn.gaussian_process.kernels.Kernel.set_params(), sklearn.gaussian_process.kernels.Kernel.theta(), and sklearn.gaussian_process.kernels.Kernel.theta().
set_params()
sklearn.base.BaseEstimator.set_params (self, ** params)
Set the parameters of this estimator.
The method works on simple estimators as well as on nested objects
(such as :class:`~sklearn.pipeline.Pipeline`). The latter have
parameters of the form ``<component>__<parameter>`` so that it's
possible to update each component of a nested object.
Parameters
----------
**params : dict
    Estimator parameters.
Returns
-------
self : estimator instance
    Estimator instance.
Reimplemented in sklearn.compose._column_transformer.ColumnTransformer, sklearn.ensemble._base._BaseHeterogeneousEnsemble, sklearn.feature_selection.tests.test_rfe.MockClassifier, sklearn.frozen._frozen.FrozenEstimator, sklearn.model_selection.tests.test_search.MockClassifier, sklearn.pipeline.FeatureUnion, sklearn.pipeline.Pipeline, sklearn.tests.test_pipeline.NoTrans, sklearn.utils.tests.test_estimator_checks.ModifiesAnotherValue, sklearn.utils.tests.test_estimator_checks.ModifiesValueInsteadOfRaisingError, and sklearn.utils.tests.test_estimator_checks.RaisesErrorInSetParams.
Definition at line 317 of file base.py.
Referenced by sklearn.tree._classes.BaseDecisionTree.cost_complexity_pruning_path(), sklearn.model_selection._search.BaseSearchCV.fit(), and sklearn.gaussian_process.kernels.Kernel.theta().
Member Data Documentation
_html_repr
sklearn.base.BaseEstimator._html_repr = estimator_html_repr static protected
Definition at line 200 of file base.py.
Referenced by sklearn.utils._repr_html.base.ReprHTMLMixin._repr_html_inner().
_parameter_constraints
sklearn.base.BaseEstimator._parameter_constraints protected
Definition at line 472 of file base.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/sklearn/base.py