Code Cloning Analysis: dateutil.tz.tz._tzicalvtzcomp Class Reference
dateutil.tz.tz._tzicalvtzcomp Class Reference
Public Member Functions
__init__ (self, tzoffsetfrom, tzoffsetto, isdst, tzname=None, rrule=None)
Public Attributes
tzoffsetfrom = datetime.timedelta(seconds=tzoffsetfrom)
tzoffsetto = datetime.timedelta(seconds=tzoffsetto)
tzoffsetdiff = self.tzoffsetto - self.tzoffsetfrom
isdst = isdst
tzname = tzname
rrule = rrule
Detailed Description
Definition at line 1156 of file tz.py.
Constructor & Destructor Documentation
__init__()
dateutil.tz.tz._tzicalvtzcomp.__init__ (self, tzoffsetfrom, tzoffsetto, isdst, tzname = None, rrule = None)
Definition at line 1157 of file tz.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Data Documentation
isdst
dateutil.tz.tz._tzicalvtzcomp.isdst = isdst
Definition at line 1162 of file tz.py.
rrule
dateutil.tz.tz._tzicalvtzcomp.rrule = rrule
Definition at line 1164 of file tz.py.
tzname
dateutil.tz.tz._tzicalvtzcomp.tzname = tzname
Definition at line 1163 of file tz.py.
tzoffsetdiff
dateutil.tz.tz._tzicalvtzcomp.tzoffsetdiff = self.tzoffsetto - self.tzoffsetfrom
Definition at line 1161 of file tz.py.
tzoffsetfrom
dateutil.tz.tz._tzicalvtzcomp.tzoffsetfrom = datetime.timedelta(seconds=tzoffsetfrom)
Definition at line 1159 of file tz.py.
tzoffsetto
dateutil.tz.tz._tzicalvtzcomp.tzoffsetto = datetime.timedelta(seconds=tzoffsetto)
Definition at line 1160 of file tz.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/dateutil/tz/tz.py