Code Cloning Analysis: scipy.stats._multivariate.matrix_normal_frozen Class Reference
scipy.stats._multivariate.matrix_normal_frozen Class Reference
Public Member Functions
__init__ (self, mean=None, rowcov=1, colcov=1, seed=None)
logpdf (self, X)
pdf (self, X)
rvs (self, size=1, random_state=None)
entropy (self)
Public Member Functions inherited from scipy.stats._multivariate.multi_rv_frozen
random_state (self)
random_state (self, seed)
Public Attributes
dims
mean
rowcov
colcov
rowpsd = _PSD(self.rowcov, allow_singular=False)
colpsd = _PSD(self.colcov, allow_singular=False)
Protected Attributes
_dist = matrix_normal_gen(seed)
Detailed Description
Create a frozen matrix normal distribution.
Parameters
----------
%(_matnorm_doc_default_callparams)s
seed : {None, int, `numpy.random.Generator`, `numpy.random.RandomState`}, optional
    If `seed` is `None` the `~np.random.RandomState` singleton is used.
    If `seed` is an int, a new ``RandomState`` instance is used, seeded
    with seed.
    If `seed` is already a ``RandomState`` or ``Generator`` instance,
    then that object is used.
    Default is `None`.
Examples
--------
>>> import numpy as np
>>> from scipy.stats import matrix_normal
>>> distn = matrix_normal(mean=np.zeros((3,3)))
>>> X = distn.rvs(); X
array([[-0.02976962,  0.93339138, -0.09663178],
       [ 0.67405524,  0.28250467, -0.93308929],
       [-0.31144782,  0.74535536,  1.30412916]])
>>> distn.pdf(X)
2.5160642368346784e-05
>>> distn.logpdf(X)
-10.590229595124615
Definition at line 1300 of file _multivariate.py.
Constructor & Destructor Documentation
__init__()
scipy.stats._multivariate.matrix_normal_frozen.__init__ (self, mean = None, rowcov = 1, colcov = 1, seed = None)
Definition at line 1331 of file _multivariate.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params().
Member Function Documentation
entropy()
scipy.stats._multivariate.matrix_normal_frozen.entropy (self)
Definition at line 1352 of file _multivariate.py.
logpdf()
scipy.stats._multivariate.matrix_normal_frozen.logpdf (self, X)
Definition at line 1338 of file _multivariate.py.
Referenced by scipy.stats._multivariate.invwishart_frozen.__init__(), scipy.stats._multivariate.multivariate_t_frozen.__init__(), scipy.stats._multivariate.invwishart_gen.pdf(), scipy.stats._multivariate.vonmises_fisher_frozen.pdf(), and scipy.stats._multivariate.wishart_gen.pdf().
pdf()
scipy.stats._multivariate.matrix_normal_frozen.pdf (self, X)
Definition at line 1345 of file _multivariate.py.
rvs()
scipy.stats._multivariate.matrix_normal_frozen.rvs (self, size = 1, random_state = None)
Definition at line 1348 of file _multivariate.py.
Referenced by scipy.stats._multivariate.ortho_group_gen.rvs(), and scipy.stats._multivariate.unitary_group_gen.rvs().
Member Data Documentation
_dist
scipy.stats._multivariate.matrix_normal_frozen._dist = matrix_normal_gen(seed) protected
Definition at line 1332 of file _multivariate.py.
Referenced by scipy.stats._multivariate.invwishart_frozen.__init__(), scipy.stats._multivariate.multivariate_t_frozen.__init__(), scipy.stats._multivariate.ortho_group_frozen.__init__(), scipy.stats._multivariate.random_correlation_frozen.__init__(), scipy.stats._multivariate.special_ortho_group_frozen.__init__(), scipy.stats._multivariate.uniform_direction_frozen.__init__(), scipy.stats._multivariate.unitary_group_frozen.__init__(), scipy.stats._multivariate.vonmises_fisher_frozen.__init__(), scipy.stats._multivariate.vonmises_fisher_frozen.entropy(), scipy.stats._multivariate.vonmises_fisher_frozen.logpdf(), and scipy.stats._multivariate.vonmises_fisher_frozen.rvs().
colcov
scipy.stats._multivariate.matrix_normal_frozen.colcov
Initial value:
=  \
            self._dist._process_parameters(mean, rowcov, colcov)
Definition at line 1333 of file _multivariate.py.
colpsd
scipy.stats._multivariate.matrix_normal_frozen.colpsd = _PSD(self.colcov, allow_singular=False)
Definition at line 1336 of file _multivariate.py.
dims
scipy.stats._multivariate.matrix_normal_frozen.dims
Definition at line 1333 of file _multivariate.py.
mean
scipy.stats._multivariate.matrix_normal_frozen.mean
Definition at line 1333 of file _multivariate.py.
Referenced by scipy.stats._continuous_distns.norminvgauss_gen._fitstart(), numpy.ma.core.MaskedArray.anom(), and numpy.ma.core.MaskedArray.var().
rowcov
scipy.stats._multivariate.matrix_normal_frozen.rowcov
Definition at line 1333 of file _multivariate.py.
rowpsd
scipy.stats._multivariate.matrix_normal_frozen.rowpsd = _PSD(self.rowcov, allow_singular=False)
Definition at line 1335 of file _multivariate.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/stats/_multivariate.py