Code Cloning Analysis: pandas.tests.dtypes.test_generic.TestABCClasses Class Reference
pandas.tests.dtypes.test_generic.TestABCClasses Class Reference
Public Member Functions
test_abc_pairs_instance_check (self, abctype1, abctype2, inst, _)
test_abc_pairs_subclass_check (self, abctype1, abctype2, inst, _)
test_abc_hierarchy (self, parent, subs, abctype, inst)
test_abc_coverage (self, abctype)
Static Public Attributes
list tuples = [[1, 2, 2], ["red", "blue", "red"]]
multi_index = pd.MultiIndex.from_arrays(tuples, names=("number", "color"))
datetime_index = pd.to_datetime(["2000/1/1", "2010/1/1"])
timedelta_index = pd.to_timedelta(np.arange(5), unit="s")
period_index = pd.period_range("2000/1/1", "2010/1/1/", freq="M")
categorical = pd.Categorical([1, 2, 3], categories=[2, 3, 1])
categorical_df = pd.DataFrame({"values": [1, 2, 3]}, index=categorical)
df = pd.DataFrame({"names": ["a", "b", "c"]}, index=multi_index)
sparse_array = pd.arrays.SparseArray(np.random.default_rng(2).standard_normal(10))
datetime_array = pd.core.arrays.DatetimeArray._from_sequence(datetime_index)
timedelta_array = pd.core.arrays.TimedeltaArray._from_sequence(timedelta_index)
list abc_pairs
dict abc_subclasses
Detailed Description
Definition at line 12 of file test_generic.py.
Member Function Documentation
test_abc_coverage()
pandas.tests.dtypes.test_generic.TestABCClasses.test_abc_coverage (self, abctype)
Definition at line 95 of file test_generic.py.
test_abc_hierarchy()
pandas.tests.dtypes.test_generic.TestABCClasses.test_abc_hierarchy (self, parent, subs, abctype, inst)
Definition at line 87 of file test_generic.py.
test_abc_pairs_instance_check()
pandas.tests.dtypes.test_generic.TestABCClasses.test_abc_pairs_instance_check (self, abctype1, abctype2, inst, _)
Definition at line 48 of file test_generic.py.
test_abc_pairs_subclass_check()
pandas.tests.dtypes.test_generic.TestABCClasses.test_abc_pairs_subclass_check (self, abctype1, abctype2, inst, _)
Definition at line 58 of file test_generic.py.
Member Data Documentation
abc_pairs
pandas.tests.dtypes.test_generic.TestABCClasses.abc_pairs static
Initial value:
=  [
        ("ABCMultiIndex", multi_index),
        ("ABCDatetimeIndex", datetime_index),
        ("ABCRangeIndex", pd.RangeIndex(3)),
        ("ABCTimedeltaIndex", timedelta_index),
        ("ABCIntervalIndex", pd.interval_range(start=0, end=3)),
        (
            "ABCPeriodArray",
            pd.arrays.PeriodArray([2000, 2001, 2002], dtype="period[D]"),
        ),
        ("ABCNumpyExtensionArray", pd.arrays.NumpyExtensionArray(np.array([0, 1, 2]))),
        ("ABCPeriodIndex", period_index),
        ("ABCCategoricalIndex", categorical_df.index),
        ("ABCSeries", pd.Series([1, 2, 3])),
        ("ABCDataFrame", df),
        ("ABCCategorical", categorical),
        ("ABCDatetimeArray", datetime_array),
        ("ABCTimedeltaArray", timedelta_array),
    ]
Definition at line 26 of file test_generic.py.
abc_subclasses
dict pandas.tests.dtypes.test_generic.TestABCClasses.abc_subclasses static
Initial value:
=  {
        "ABCIndex": [
            abctype
            for abctype, _ in abc_pairs
            if "Index" in abctype and abctype != "ABCIndex"
        ],
        "ABCNDFrame": ["ABCSeries", "ABCDataFrame"],
        "ABCExtensionArray": [
            "ABCCategorical",
            "ABCDatetimeArray",
            "ABCPeriodArray",
            "ABCTimedeltaArray",
        ],
    }
Definition at line 70 of file test_generic.py.
categorical
pandas.tests.dtypes.test_generic.TestABCClasses.categorical = pd.Categorical([1, 2, 3], categories=[2, 3, 1]) static
Definition at line 18 of file test_generic.py.
categorical_df
pandas.tests.dtypes.test_generic.TestABCClasses.categorical_df = pd.DataFrame({"values": [1, 2, 3]}, index=categorical) static
Definition at line 19 of file test_generic.py.
datetime_array
pandas.tests.dtypes.test_generic.TestABCClasses.datetime_array = pd.core.arrays.DatetimeArray._from_sequence(datetime_index) static
Definition at line 23 of file test_generic.py.
datetime_index
pandas.tests.dtypes.test_generic.TestABCClasses.datetime_index = pd.to_datetime(["2000/1/1", "2010/1/1"]) static
Definition at line 15 of file test_generic.py.
df
pandas.tests.dtypes.test_generic.TestABCClasses.df = pd.DataFrame({"names": ["a", "b", "c"]}, index=multi_index) static
Definition at line 20 of file test_generic.py.
Referenced by scipy.stats._multivariate.invwishart_frozen.__init__(), scipy.stats._multivariate.multivariate_t_frozen.__init__(), scipy.stats._stats_py.TtestResult.confidence_interval(), and pandas.tests.frame.methods.test_rank.TestRank.method().
multi_index
pandas.tests.dtypes.test_generic.TestABCClasses.multi_index = pd.MultiIndex.from_arrays(tuples, names=("number", "color")) static
Definition at line 14 of file test_generic.py.
period_index
pandas.tests.dtypes.test_generic.TestABCClasses.period_index = pd.period_range("2000/1/1", "2010/1/1/", freq="M") static
Definition at line 17 of file test_generic.py.
sparse_array
pandas.tests.dtypes.test_generic.TestABCClasses.sparse_array = pd.arrays.SparseArray(np.random.default_rng(2).standard_normal(10)) static
Definition at line 21 of file test_generic.py.
timedelta_array
pandas.tests.dtypes.test_generic.TestABCClasses.timedelta_array = pd.core.arrays.TimedeltaArray._from_sequence(timedelta_index) static
Definition at line 24 of file test_generic.py.
timedelta_index
pandas.tests.dtypes.test_generic.TestABCClasses.timedelta_index = pd.to_timedelta(np.arange(5), unit="s") static
Definition at line 16 of file test_generic.py.
tuples
list pandas.tests.dtypes.test_generic.TestABCClasses.tuples = [[1, 2, 2], ["red", "blue", "red"]] static
Definition at line 13 of file test_generic.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/tests/dtypes/test_generic.py