Code Cloning Analysis: scipy.optimize.tests.test_minpack.TestCurveFit Class Reference
scipy.optimize.tests.test_minpack.TestCurveFit Class Reference
Public Member Functions
setup_method (self)
test_one_argument (self)
test_two_argument (self)
test_func_is_classmethod (self)
test_regression_2639 (self)
test_pcov (self)
test_array_like (self)
test_indeterminate_covariance (self)
test_NaN_handling (self)
test_nan_policy_1d (self, method)
test_nan_policy_2d (self, method)
test_nan_policy_2_3d (self, n, method)
test_empty_inputs (self)
test_function_zero_params (self)
test_None_x (self)
test_method_argument (self)
test_full_output (self)
test_bounds (self)
test_bounds_p0 (self)
test_jac (self)
test_maxfev_and_bounds (self)
test_curvefit_simplecovariance (self)
test_curvefit_covariance (self)
test_dtypes (self)
test_dtypes2 (self)
test_broadcast_y (self)
test_args_in_kwargs (self)
test_data_point_number_validation (self)
test_gh4555 (self)
test_gh4555b (self)
test_gh13670 (self)
Public Attributes
y = array([1.0, 3.2, 9.5, 13.7])
x = array([1.0, 2.0, 3.0, 4.0])
Static Protected Member Functions
_check_nan_policy (f, xdata_with_nan, xdata_without_nan, ydata_with_nan, ydata_without_nan, method)
Detailed Description
Definition at line 416 of file test_minpack.py.
Member Function Documentation
_check_nan_policy()
scipy.optimize.tests.test_minpack.TestCurveFit._check_nan_policy (f, xdata_with_nan, xdata_without_nan, ydata_with_nan, ydata_without_nan, method) static protected
Definition at line 562 of file test_minpack.py.
setup_method()
scipy.optimize.tests.test_minpack.TestCurveFit.setup_method (self)
Definition at line 417 of file test_minpack.py.
test_args_in_kwargs()
scipy.optimize.tests.test_minpack.TestCurveFit.test_args_in_kwargs (self)
Definition at line 921 of file test_minpack.py.
test_array_like()
scipy.optimize.tests.test_minpack.TestCurveFit.test_array_like (self)
Definition at line 530 of file test_minpack.py.
test_bounds()
scipy.optimize.tests.test_minpack.TestCurveFit.test_bounds (self)
Definition at line 687 of file test_minpack.py.
test_bounds_p0()
scipy.optimize.tests.test_minpack.TestCurveFit.test_bounds_p0 (self)
Definition at line 721 of file test_minpack.py.
test_broadcast_y()
scipy.optimize.tests.test_minpack.TestCurveFit.test_broadcast_y (self)
Definition at line 905 of file test_minpack.py.
test_curvefit_covariance()
scipy.optimize.tests.test_minpack.TestCurveFit.test_curvefit_covariance (self)
Definition at line 812 of file test_minpack.py.
test_curvefit_simplecovariance()
scipy.optimize.tests.test_minpack.TestCurveFit.test_curvefit_simplecovariance (self)
Definition at line 785 of file test_minpack.py.
test_data_point_number_validation()
scipy.optimize.tests.test_minpack.TestCurveFit.test_data_point_number_validation (self)
Definition at line 934 of file test_minpack.py.
test_dtypes()
scipy.optimize.tests.test_minpack.TestCurveFit.test_dtypes (self)
Definition at line 856 of file test_minpack.py.
test_dtypes2()
scipy.optimize.tests.test_minpack.TestCurveFit.test_dtypes2 (self)
Definition at line 877 of file test_minpack.py.
test_empty_inputs()
scipy.optimize.tests.test_minpack.TestCurveFit.test_empty_inputs (self)
Definition at line 636 of file test_minpack.py.
test_full_output()
scipy.optimize.tests.test_minpack.TestCurveFit.test_full_output (self)
Definition at line 667 of file test_minpack.py.
test_func_is_classmethod()
scipy.optimize.tests.test_minpack.TestCurveFit.test_func_is_classmethod (self)
Definition at line 447 of file test_minpack.py.
test_function_zero_params()
scipy.optimize.tests.test_minpack.TestCurveFit.test_function_zero_params (self)
Definition at line 645 of file test_minpack.py.
test_gh13670()
scipy.optimize.tests.test_minpack.TestCurveFit.test_gh13670 (self)
Definition at line 983 of file test_minpack.py.
test_gh4555()
scipy.optimize.tests.test_minpack.TestCurveFit.test_gh4555 (self)
Definition at line 944 of file test_minpack.py.
test_gh4555b()
scipy.optimize.tests.test_minpack.TestCurveFit.test_gh4555b (self)
Definition at line 963 of file test_minpack.py.
test_indeterminate_covariance()
scipy.optimize.tests.test_minpack.TestCurveFit.test_indeterminate_covariance (self)
Definition at line 539 of file test_minpack.py.
test_jac()
scipy.optimize.tests.test_minpack.TestCurveFit.test_jac (self)
Definition at line 738 of file test_minpack.py.
test_maxfev_and_bounds()
scipy.optimize.tests.test_minpack.TestCurveFit.test_maxfev_and_bounds (self)
Definition at line 774 of file test_minpack.py.
test_method_argument()
scipy.optimize.tests.test_minpack.TestCurveFit.test_method_argument (self)
Definition at line 654 of file test_minpack.py.
test_NaN_handling()
scipy.optimize.tests.test_minpack.TestCurveFit.test_NaN_handling (self)
Definition at line 546 of file test_minpack.py.
test_nan_policy_1d()
scipy.optimize.tests.test_minpack.TestCurveFit.test_nan_policy_1d (self, method)
Definition at line 590 of file test_minpack.py.
test_nan_policy_2_3d()
scipy.optimize.tests.test_minpack.TestCurveFit.test_nan_policy_2_3d (self, n, method)
Definition at line 620 of file test_minpack.py.
test_nan_policy_2d()
scipy.optimize.tests.test_minpack.TestCurveFit.test_nan_policy_2d (self, method)
Definition at line 603 of file test_minpack.py.
test_None_x()
scipy.optimize.tests.test_minpack.TestCurveFit.test_None_x (self)
Definition at line 649 of file test_minpack.py.
test_one_argument()
scipy.optimize.tests.test_minpack.TestCurveFit.test_one_argument (self)
Definition at line 421 of file test_minpack.py.
test_pcov()
scipy.optimize.tests.test_minpack.TestCurveFit.test_pcov (self)
Definition at line 482 of file test_minpack.py.
test_regression_2639()
scipy.optimize.tests.test_minpack.TestCurveFit.test_regression_2639 (self)
Definition at line 463 of file test_minpack.py.
test_two_argument()
scipy.optimize.tests.test_minpack.TestCurveFit.test_two_argument (self)
Definition at line 437 of file test_minpack.py.
Member Data Documentation
x
scipy.optimize.tests.test_minpack.TestCurveFit.x = array([1.0, 2.0, 3.0, 4.0])
Definition at line 419 of file test_minpack.py.
Referenced by matplotlib.widgets.ToolHandles.closest(), and scipy.spatial.tests.test_kdtree._Test_sorted_query_ball_point.test_return_sorted_None().
y
scipy.optimize.tests.test_minpack.TestCurveFit.y = array([1.0, 3.2, 9.5, 13.7])
Definition at line 418 of file test_minpack.py.
Referenced by matplotlib.widgets.ToolHandles.closest().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/optimize/tests/test_minpack.py