Code Cloning Analysis: numpy.ma.core._extrema_operation Class Reference
numpy.ma.core._extrema_operation Class Reference
Extrema functions #.
Public Member Functions
__init__ (self, ufunc, compare, fill_value)
__call__ (self, a, b)
reduce (self, target, axis=np._NoValue)
outer (self, a, b)
Public Member Functions inherited from numpy.ma.core._MaskedUFunc
__init__ (self, ufunc)
__str__ (self)
Public Attributes
compare = compare
fill_value_func = fill_value
Public Attributes inherited from numpy.ma.core._MaskedUFunc
f = ufunc
Detailed Description
Extrema functions #.
Generic class for maximum/minimum functions.
.. note::
  This is the base class for `_maximum_operation` and
  `_minimum_operation`.
Definition at line 6735 of file core.py.
Constructor & Destructor Documentation
__init__()
numpy.ma.core._extrema_operation.__init__ (self, ufunc, compare, fill_value)
Definition at line 6744 of file core.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__call__()
numpy.ma.core._extrema_operation.__call__ (self, a, b)
Definition at line 6749 of file core.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), and scipy.interpolate._fitpack2.SphereBivariateSpline.ev().
outer()
numpy.ma.core._extrema_operation.outer (self, a, b)
Definition at line 6786 of file core.py.
reduce()
numpy.ma.core._extrema_operation.reduce (self, target, axis = np._NoValue)
Definition at line 6754 of file core.py.
Referenced by PIL.Image.Image.resize().
Member Data Documentation
compare
numpy.ma.core._extrema_operation.compare = compare
Definition at line 6746 of file core.py.
Referenced by pandas.tests.io.formats.test_eng_formatting.TestEngFormatter.compare_all().
fill_value_func
numpy.ma.core._extrema_operation.fill_value_func = fill_value
Definition at line 6747 of file core.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/ma/core.py