Code Cloning Analysis: joblib.externals.loky.cloudpickle_wrapper.CallableObjectWrapper Class Reference
joblib.externals.loky.cloudpickle_wrapper.CallableObjectWrapper Class Reference
Public Member Functions
__call__ (self, *args, **kwargs)
Public Member Functions inherited from joblib.externals.loky.cloudpickle_wrapper.CloudpickledObjectWrapper
__init__ (self, obj, keep_wrapper=False)
__reduce__ (self)
__getattr__ (self, attr)
Additional Inherited Members
Protected Attributes inherited from joblib.externals.loky.cloudpickle_wrapper.CloudpickledObjectWrapper
_obj = obj
_keep_wrapper = keep_wrapper
Detailed Description
Definition at line 30 of file cloudpickle_wrapper.py.
Member Function Documentation
__call__()
joblib.externals.loky.cloudpickle_wrapper.CallableObjectWrapper.__call__ (self, * args, ** kwargs)
Definition at line 31 of file cloudpickle_wrapper.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), scipy.interpolate._fitpack2.SphereBivariateSpline.ev(), matplotlib.ticker.Formatter.format_data(), and matplotlib.ticker.LogFormatter.format_data().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/joblib/externals/loky/cloudpickle_wrapper.py