Code Cloning Analysis: fontTools.ttLib.tables.C_B_D_T_.cbdt_bitmap_format_18 Class Reference
fontTools.ttLib.tables.C_B_D_T_.cbdt_bitmap_format_18 Class Reference
Public Member Functions
decompile (self)
compile (self, ttFont)
Public Member Functions inherited from fontTools.ttLib.tables.E_B_D_T_.BitmapGlyph
__init__ (self, data, ttFont)
__getattr__ (self, attr)
ensureDecompiled (self, recurse=False)
getFormat (self)
toXML (self, strikeIndex, glyphName, writer, ttFont)
fromXML (self, name, attrs, content, ttFont)
writeMetrics (self, writer, ttFont)
readMetrics (self, name, attrs, content, ttFont)
writeData (self, strikeIndex, glyphName, writer, ttFont)
readData (self, name, attrs, content, ttFont)
Public Attributes
metrics = BigGlyphMetrics()
imageData = data[:dataLen]
Public Attributes inherited from fontTools.ttLib.tables.E_B_D_T_.BitmapGlyph
data = data
ttFont = ttFont
Additional Inherited Members
Static Public Attributes inherited from fontTools.ttLib.tables.E_B_D_T_.BitmapGlyph
str fileExtension = ".bin"
dict xmlDataFunctions
Detailed Description
Definition at line 77 of file C_B_D_T_.py.
Member Function Documentation
compile()
fontTools.ttLib.tables.C_B_D_T_.cbdt_bitmap_format_18.compile (self, ttFont)
Definition at line 88 of file C_B_D_T_.py.
Referenced by fontTools.ttLib.tables.TupleVariation.TupleVariation.getCoordWidth(), and PIL.FontFile.FontFile.save().
decompile()
fontTools.ttLib.tables.C_B_D_T_.cbdt_bitmap_format_18.decompile (self)
Definition at line 78 of file C_B_D_T_.py.
Referenced by fontTools.ttLib.tables._c_m_a_p.CmapSubtable.newSubtable().
Member Data Documentation
imageData
fontTools.ttLib.tables.C_B_D_T_.cbdt_bitmap_format_18.imageData = data[:dataLen]
Definition at line 86 of file C_B_D_T_.py.
Referenced by fontTools.ttLib.tables.sbixGlyph.Glyph.is_reference_type().
metrics
fontTools.ttLib.tables.C_B_D_T_.cbdt_bitmap_format_18.metrics = BigGlyphMetrics()
Definition at line 79 of file C_B_D_T_.py.
Referenced by PIL.FontFile.FontFile.compile(), and PIL.FontFile.FontFile.save().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ttLib/tables/C_B_D_T_.py