Code Cloning Analysis: sklearn.utils._unique Namespace Reference
sklearn.utils._unique Namespace Reference
Functions
_attach_unique (y)
attach_unique (*ys, return_tuple=False)
_cached_unique (y, xp=None)
cached_unique (*ys, xp=None)
Function Documentation
_attach_unique()
sklearn.utils._unique._attach_unique (y) protected
Attach unique values of y to y and return the result.
The result is a view of y, and the metadata (unique) is not attached to y.
Definition at line 9 of file _unique.py.
Referenced by attach_unique().
_cached_unique()
sklearn.utils._unique._cached_unique (y, xp = None) protected
Return the unique values of y.
Use the cached values from dtype.metadata if present.
This function does NOT cache the values in y, i.e. it doesn't change y.
Call `attach_unique` to attach the unique values to y.
Definition at line 62 of file _unique.py.
Referenced by cached_unique().
attach_unique()
sklearn.utils._unique.attach_unique (* ys, return_tuple = False)
Attach unique values of ys to ys and return the results.
The result is a view of y, and the metadata (unique) is not attached to y.
IMPORTANT: The output of this function should NEVER be returned in functions.
This is to avoid this pattern:
.. code:: python
    y = np.array([1, 2, 3])
    y = attach_unique(y)
    y[1] = -1
    # now np.unique(y) will be different from cached_unique(y)
Parameters
----------
*ys : sequence of array-like
    Input data arrays.
return_tuple : bool, default=False
    If True, always return a tuple even if there is only one array.
Returns
-------
ys : tuple of array-like or array-like
    Input data with unique values attached.
Definition at line 28 of file _unique.py.
References _attach_unique().
cached_unique()
sklearn.utils._unique.cached_unique (* ys, xp = None)
Return the unique values of ys.
Use the cached values from dtype.metadata if present.
This function does NOT cache the values in y, i.e. it doesn't change y.
Call `attach_unique` to attach the unique values to y.
Parameters
----------
*ys : sequence of array-like
    Input data arrays.
xp : module, default=None
    Precomputed array namespace module. When passed, typically from a caller
    that has already performed inspection of its own inputs, skips array
    namespace inspection.
Returns
-------
res : tuple of array-like or array-like
    Unique values of ys.
Definition at line 81 of file _unique.py.
References _cached_unique().