Code Cloning Analysis: matplotlib.text.OffsetFrom Class Reference
matplotlib.text.OffsetFrom Class Reference
Public Member Functions
__init__ (self, artist, ref_coord, unit="points")
set_unit (self, unit)
get_unit (self)
__call__ (self, renderer)
Protected Attributes
_artist = artist
_ref_coord = x, y
_unit = unit
Detailed Description
Callable helper class for working with `Annotation`.
Definition at line 1384 of file text.py.
Constructor & Destructor Documentation
__init__()
matplotlib.text.OffsetFrom.__init__ (self, artist, ref_coord, unit = "points")
Parameters
----------
artist : `~matplotlib.artist.Artist` or `.BboxBase` or `.Transform`
    The object to compute the offset from.
ref_coord : (float, float)
    If *artist* is an `.Artist` or `.BboxBase`, this values is
    the location to of the offset origin in fractions of the
    *artist* bounding box.
    If *artist* is a transform, the offset origin is the
    transform applied to this value.
unit : {'points, 'pixels'}, default: 'points'
    The screen units to use (pixels or points) for the offset input.
Definition at line 1387 of file text.py.
References _artist, _ref_coord, and set_unit().
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__call__()
matplotlib.text.OffsetFrom.__call__ (self, renderer)
Return the offset transform.
Parameters
----------
renderer : `RendererBase`
    The renderer to use to compute the offset
Returns
-------
`Transform`
    Maps (x, y) in pixel or point units to screen units
    relative to the given artist.
Definition at line 1425 of file text.py.
References _artist, _ref_coord, and _unit.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), scipy.interpolate._fitpack2.SphereBivariateSpline.ev(), matplotlib.ticker.Formatter.format_data(), and matplotlib.ticker.LogFormatter.format_data().
get_unit()
matplotlib.text.OffsetFrom.get_unit (self)
Return the unit for input to the transform used by ``__call__``.
Definition at line 1421 of file text.py.
References _unit.
set_unit()
matplotlib.text.OffsetFrom.set_unit (self, unit)
Set the unit for input to the transform used by ``__call__``.
Parameters
----------
unit : {'points', 'pixels'}
Definition at line 1410 of file text.py.
References _unit.
Referenced by __init__().
Member Data Documentation
_artist
matplotlib.text.OffsetFrom._artist = artist protected
Definition at line 1405 of file text.py.
Referenced by __call__(), and __init__().
_ref_coord
matplotlib.text.OffsetFrom._ref_coord = x, y protected
Definition at line 1407 of file text.py.
Referenced by __call__(), and __init__().
_unit
matplotlib.text.OffsetFrom._unit = unit protected
Definition at line 1419 of file text.py.
Referenced by __call__(), pandas.core.dtypes.dtypes.DatetimeTZDtype.__from_arrow__(), get_unit(), pandas.core.dtypes.dtypes.DatetimeTZDtype.na_value(), set_unit(), and pandas.core.dtypes.dtypes.DatetimeTZDtype.unit().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/text.py