Code Cloning Analysis: matplotlib.container.StemContainer Class Reference
matplotlib.container.StemContainer Class Reference
Public Member Functions
__init__ (self, markerline_stemlines_baseline, **kwargs)
Public Member Functions inherited from matplotlib.container.Container
__repr__ (self)
__new__ (cls, *args, **kwargs)
__init__ (self, kl, label=None)
remove (self)
get_children (self)
Public Attributes
markerline = markerline
stemlines = stemlines
baseline = baseline
Additional Inherited Members
Static Public Attributes inherited from matplotlib.container.Container
get_label = Artist.get_label
set_label = Artist.set_label
add_callback = Artist.add_callback
remove_callback = Artist.remove_callback
pchanged = Artist.pchanged
Protected Attributes inherited from matplotlib.container.Container
_callbacks = cbook.CallbackRegistry(signals=["pchanged"])
_remove_method = None
_label = str(label) if label is not None else None
Detailed Description
Container for the artists created in a :meth:`.Axes.stem` plot.
The container can be treated like a namedtuple ``(markerline, stemlines,
baseline)``.
Attributes
----------
markerline : `~matplotlib.lines.Line2D`
    The artist of the markers at the stem heads.
stemlines : `~matplotlib.collections.LineCollection`
    The artists of the vertical lines for all stems.
baseline : `~matplotlib.lines.Line2D`
    The artist of the horizontal baseline.
Definition at line 109 of file container.py.
Constructor & Destructor Documentation
__init__()
matplotlib.container.StemContainer.__init__ (self, markerline_stemlines_baseline, ** kwargs)
Parameters
----------
markerline_stemlines_baseline : tuple
    Tuple of ``(markerline, stemlines, baseline)``.
    ``markerline`` contains the `.Line2D` of the markers,
    ``stemlines`` is a `.LineCollection` of the main lines,
    ``baseline`` is the `.Line2D` of the baseline.
Definition at line 127 of file container.py.
References __init__(), baseline, markerline, and stemlines.
Referenced by __init__(), sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Data Documentation
baseline
matplotlib.container.StemContainer.baseline = baseline
Definition at line 140 of file container.py.
Referenced by __init__().
markerline
matplotlib.container.StemContainer.markerline = markerline
Definition at line 138 of file container.py.
Referenced by __init__().
stemlines
matplotlib.container.StemContainer.stemlines = stemlines
Definition at line 139 of file container.py.
Referenced by __init__().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/container.py