Code Cloning Analysis: scipy.special.tests.test_basic.TestBessel Class Reference
scipy.special.tests.test_basic.TestBessel Class Reference
Public Member Functions
test_itj0y0 (self)
test_it2j0y0 (self)
test_negv_iv (self)
test_j0 (self)
test_j1 (self)
test_jn (self)
test_negv_jv (self)
test_jv (self)
test_negv_jve (self)
test_jve (self)
test_jn_zeros (self)
test_jn_zeros_slow (self)
test_jnjnp_zeros (self)
test_jnp_zeros (self)
test_jnyn_zeros (self)
test_jvp (self)
test_k0 (self)
test_k0e (self)
test_k1 (self)
test_k1e (self)
test_jacobi (self)
test_kn (self)
test_negv_kv (self)
test_kv0 (self)
test_kv1 (self)
test_kv2 (self)
test_kn_largeorder (self)
test_kv_largearg (self)
test_negv_kve (self)
test_kve (self)
test_kvp_v0n1 (self)
test_kvp_n1 (self)
test_kvp_n2 (self)
test_y0 (self)
test_y1 (self)
test_y0_zeros (self)
test_y1_zeros (self)
test_y1p_zeros (self)
test_yn_zeros (self)
test_ynp_zeros (self)
test_ynp_zeros_large_order (self)
test_yn (self)
test_negv_yv (self)
test_yv (self)
test_negv_yve (self)
test_yve (self)
test_yvp (self)
check_cephes_vs_amos (self, f1, f2, rtol=1e-11, atol=0, skip=None)
test_jv_cephes_vs_amos (self)
test_yv_cephes_vs_amos (self)
test_yv_cephes_vs_amos_only_small_orders (self)
test_iv_cephes_vs_amos (self)
test_iv_cephes_vs_amos_mass_test (self)
test_kv_cephes_vs_amos (self)
test_ticket_623 (self)
test_ticket_853 (self)
test_ticket_854 (self)
test_gh_7909 (self)
test_ticket_503 (self)
test_iv_hyperg_poles (self)
iv_series (self, v, z, n=200)
test_i0_series (self)
test_i1_series (self)
test_iv_series (self)
test_i0 (self)
test_i0e (self)
test_i1 (self)
test_i1e (self)
test_iti0k0 (self)
test_it2i0k0 (self)
test_iv (self)
test_negv_ive (self)
test_ive (self)
test_ivp0 (self)
test_ivp (self)
Protected Member Functions
_cephes_vs_amos_points (self)
Detailed Description
Definition at line 2704 of file test_basic.py.
Member Function Documentation
_cephes_vs_amos_points()
scipy.special.tests.test_basic.TestBessel._cephes_vs_amos_points (self) protected
Yield points at which to compare Cephes implementation to AMOS
Definition at line 3019 of file test_basic.py.
References _cephes_vs_amos_points(), and check_cephes_vs_amos().
Referenced by _cephes_vs_amos_points().
check_cephes_vs_amos()
scipy.special.tests.test_basic.TestBessel.check_cephes_vs_amos (self, f1, f2, rtol = 1e-11, atol = 0, skip = None)
Definition at line 3031 of file test_basic.py.
Referenced by _cephes_vs_amos_points().
iv_series()
scipy.special.tests.test_basic.TestBessel.iv_series (self, v, z, n = 200)
Definition at line 3176 of file test_basic.py.
Referenced by test_ticket_503().
test_gh_7909()
scipy.special.tests.test_basic.TestBessel.test_gh_7909 (self)
Definition at line 3164 of file test_basic.py.
test_i0()
scipy.special.tests.test_basic.TestBessel.test_i0 (self)
Definition at line 3200 of file test_basic.py.
test_i0_series()
scipy.special.tests.test_basic.TestBessel.test_i0_series (self)
Definition at line 3184 of file test_basic.py.
test_i0e()
scipy.special.tests.test_basic.TestBessel.test_i0e (self)
Definition at line 3214 of file test_basic.py.
test_i1()
scipy.special.tests.test_basic.TestBessel.test_i1 (self)
Definition at line 3219 of file test_basic.py.
test_i1_series()
scipy.special.tests.test_basic.TestBessel.test_i1_series (self)
Definition at line 3189 of file test_basic.py.
test_i1e()
scipy.special.tests.test_basic.TestBessel.test_i1e (self)
Definition at line 3232 of file test_basic.py.
test_it2i0k0()
scipy.special.tests.test_basic.TestBessel.test_it2i0k0 (self)
Definition at line 3241 of file test_basic.py.
test_it2j0y0()
scipy.special.tests.test_basic.TestBessel.test_it2j0y0 (self)
Definition at line 2709 of file test_basic.py.
test_iti0k0()
scipy.special.tests.test_basic.TestBessel.test_iti0k0 (self)
Definition at line 3237 of file test_basic.py.
test_itj0y0()
scipy.special.tests.test_basic.TestBessel.test_itj0y0 (self)
Definition at line 2705 of file test_basic.py.
test_iv()
scipy.special.tests.test_basic.TestBessel.test_iv (self)
Definition at line 3245 of file test_basic.py.
test_iv_cephes_vs_amos()
scipy.special.tests.test_basic.TestBessel.test_iv_cephes_vs_amos (self)
Definition at line 3061 of file test_basic.py.
test_iv_cephes_vs_amos_mass_test()
scipy.special.tests.test_basic.TestBessel.test_iv_cephes_vs_amos_mass_test (self)
Definition at line 3066 of file test_basic.py.
test_iv_hyperg_poles()
scipy.special.tests.test_basic.TestBessel.test_iv_hyperg_poles (self)
Definition at line 3173 of file test_basic.py.
test_iv_series()
scipy.special.tests.test_basic.TestBessel.test_iv_series (self)
Definition at line 3194 of file test_basic.py.
test_ive()
scipy.special.tests.test_basic.TestBessel.test_ive (self)
Definition at line 3252 of file test_basic.py.
test_ivp()
scipy.special.tests.test_basic.TestBessel.test_ivp (self)
Definition at line 3260 of file test_basic.py.
test_ivp0()
scipy.special.tests.test_basic.TestBessel.test_ivp0 (self)
Definition at line 3257 of file test_basic.py.
test_j0()
scipy.special.tests.test_basic.TestBessel.test_j0 (self)
Definition at line 2716 of file test_basic.py.
test_j1()
scipy.special.tests.test_basic.TestBessel.test_j1 (self)
Definition at line 2721 of file test_basic.py.
test_jacobi()
scipy.special.tests.test_basic.TestBessel.test_jacobi (self)
Definition at line 2874 of file test_basic.py.
test_jn()
scipy.special.tests.test_basic.TestBessel.test_jn (self)
Definition at line 2726 of file test_basic.py.
test_jn_zeros()
scipy.special.tests.test_basic.TestBessel.test_jn_zeros (self)
Definition at line 2755 of file test_basic.py.
test_jn_zeros_slow()
scipy.special.tests.test_basic.TestBessel.test_jn_zeros_slow (self)
Definition at line 2783 of file test_basic.py.
test_jnjnp_zeros()
scipy.special.tests.test_basic.TestBessel.test_jnjnp_zeros (self)
Definition at line 2801 of file test_basic.py.
test_jnp_zeros()
scipy.special.tests.test_basic.TestBessel.test_jnp_zeros (self)
Definition at line 2816 of file test_basic.py.
test_jnyn_zeros()
scipy.special.tests.test_basic.TestBessel.test_jnyn_zeros (self)
Definition at line 2826 of file test_basic.py.
test_jv()
scipy.special.tests.test_basic.TestBessel.test_jv (self)
Definition at line 2733 of file test_basic.py.
test_jv_cephes_vs_amos()
scipy.special.tests.test_basic.TestBessel.test_jv_cephes_vs_amos (self)
Definition at line 3048 of file test_basic.py.
test_jve()
scipy.special.tests.test_basic.TestBessel.test_jve (self)
Definition at line 2747 of file test_basic.py.
test_jvp()
scipy.special.tests.test_basic.TestBessel.test_jvp (self)
Definition at line 2849 of file test_basic.py.
test_k0()
scipy.special.tests.test_basic.TestBessel.test_k0 (self)
Definition at line 2854 of file test_basic.py.
test_k0e()
scipy.special.tests.test_basic.TestBessel.test_k0e (self)
Definition at line 2859 of file test_basic.py.
test_k1()
scipy.special.tests.test_basic.TestBessel.test_k1 (self)
Definition at line 2864 of file test_basic.py.
test_k1e()
scipy.special.tests.test_basic.TestBessel.test_k1e (self)
Definition at line 2869 of file test_basic.py.
test_kn()
scipy.special.tests.test_basic.TestBessel.test_kn (self)
Definition at line 2892 of file test_basic.py.
test_kn_largeorder()
scipy.special.tests.test_basic.TestBessel.test_kn_largeorder (self)
Definition at line 2911 of file test_basic.py.
test_kv0()
scipy.special.tests.test_basic.TestBessel.test_kv0 (self)
Definition at line 2899 of file test_basic.py.
test_kv1()
scipy.special.tests.test_basic.TestBessel.test_kv1 (self)
Definition at line 2903 of file test_basic.py.
test_kv2()
scipy.special.tests.test_basic.TestBessel.test_kv2 (self)
Definition at line 2907 of file test_basic.py.
test_kv_cephes_vs_amos()
scipy.special.tests.test_basic.TestBessel.test_kv_cephes_vs_amos (self)
Definition at line 3094 of file test_basic.py.
test_kv_largearg()
scipy.special.tests.test_basic.TestBessel.test_kv_largearg (self)
Definition at line 2914 of file test_basic.py.
test_kve()
scipy.special.tests.test_basic.TestBessel.test_kve (self)
Definition at line 2920 of file test_basic.py.
test_kvp_n1()
scipy.special.tests.test_basic.TestBessel.test_kvp_n1 (self)
Definition at line 2933 of file test_basic.py.
test_kvp_n2()
scipy.special.tests.test_basic.TestBessel.test_kvp_n2 (self)
Definition at line 2940 of file test_basic.py.
test_kvp_v0n1()
scipy.special.tests.test_basic.TestBessel.test_kvp_v0n1 (self)
Definition at line 2929 of file test_basic.py.
test_negv_iv()
scipy.special.tests.test_basic.TestBessel.test_negv_iv (self)
Definition at line 2713 of file test_basic.py.
test_negv_ive()
scipy.special.tests.test_basic.TestBessel.test_negv_ive (self)
Definition at line 3249 of file test_basic.py.
test_negv_jv()
scipy.special.tests.test_basic.TestBessel.test_negv_jv (self)
Definition at line 2730 of file test_basic.py.
test_negv_jve()
scipy.special.tests.test_basic.TestBessel.test_negv_jve (self)
Definition at line 2744 of file test_basic.py.
test_negv_kv()
scipy.special.tests.test_basic.TestBessel.test_negv_kv (self)
Definition at line 2896 of file test_basic.py.
test_negv_kve()
scipy.special.tests.test_basic.TestBessel.test_negv_kve (self)
Definition at line 2917 of file test_basic.py.
test_negv_yv()
scipy.special.tests.test_basic.TestBessel.test_negv_yv (self)
Definition at line 2997 of file test_basic.py.
test_negv_yve()
scipy.special.tests.test_basic.TestBessel.test_negv_yve (self)
Definition at line 3004 of file test_basic.py.
test_ticket_503()
scipy.special.tests.test_basic.TestBessel.test_ticket_503 (self)
Real-valued Bessel I overflow
Definition at line 3168 of file test_basic.py.
References iv_series().
test_ticket_623()
scipy.special.tests.test_basic.TestBessel.test_ticket_623 (self)
Definition at line 3098 of file test_basic.py.
test_ticket_853()
scipy.special.tests.test_basic.TestBessel.test_ticket_853 (self)
Negative-order Bessels
Definition at line 3103 of file test_basic.py.
test_ticket_854()
scipy.special.tests.test_basic.TestBessel.test_ticket_854 (self)
Real-valued Bessel domains
Definition at line 3147 of file test_basic.py.
test_y0()
scipy.special.tests.test_basic.TestBessel.test_y0 (self)
Definition at line 2947 of file test_basic.py.
test_y0_zeros()
scipy.special.tests.test_basic.TestBessel.test_y0_zeros (self)
Definition at line 2957 of file test_basic.py.
test_y1()
scipy.special.tests.test_basic.TestBessel.test_y1 (self)
Definition at line 2952 of file test_basic.py.
test_y1_zeros()
scipy.special.tests.test_basic.TestBessel.test_y1_zeros (self)
Definition at line 2965 of file test_basic.py.
test_y1p_zeros()
scipy.special.tests.test_basic.TestBessel.test_y1p_zeros (self)
Definition at line 2969 of file test_basic.py.
test_yn()
scipy.special.tests.test_basic.TestBessel.test_yn (self)
Definition at line 2993 of file test_basic.py.
test_yn_zeros()
scipy.special.tests.test_basic.TestBessel.test_yn_zeros (self)
Definition at line 2973 of file test_basic.py.
test_ynp_zeros()
scipy.special.tests.test_basic.TestBessel.test_ynp_zeros (self)
Definition at line 2981 of file test_basic.py.
test_ynp_zeros_large_order()
scipy.special.tests.test_basic.TestBessel.test_ynp_zeros_large_order (self)
Definition at line 2989 of file test_basic.py.
test_yv()
scipy.special.tests.test_basic.TestBessel.test_yv (self)
Definition at line 3000 of file test_basic.py.
test_yv_cephes_vs_amos()
scipy.special.tests.test_basic.TestBessel.test_yv_cephes_vs_amos (self)
Definition at line 3053 of file test_basic.py.
test_yv_cephes_vs_amos_only_small_orders()
scipy.special.tests.test_basic.TestBessel.test_yv_cephes_vs_amos_only_small_orders (self)
Definition at line 3056 of file test_basic.py.
test_yve()
scipy.special.tests.test_basic.TestBessel.test_yve (self)
Definition at line 3007 of file test_basic.py.
test_yvp()
scipy.special.tests.test_basic.TestBessel.test_yvp (self)
Definition at line 3014 of file test_basic.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/special/tests/test_basic.py