Code Cloning Analysis: scipy.optimize._basinhopping.Storage Class Reference
scipy.optimize._basinhopping.Storage Class Reference
Public Member Functions
__init__ (self, minres)
update (self, minres)
get_lowest (self)
Public Attributes
minres = minres
Protected Member Functions
_add (self, minres)
Detailed Description
Class used to store the lowest energy structure
Definition at line 18 of file _basinhopping.py.
Constructor & Destructor Documentation
__init__()
scipy.optimize._basinhopping.Storage.__init__ (self, minres)
Definition at line 22 of file _basinhopping.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
_add()
scipy.optimize._basinhopping.Storage._add (self, minres) protected
Definition at line 25 of file _basinhopping.py.
get_lowest()
scipy.optimize._basinhopping.Storage.get_lowest (self)
Definition at line 37 of file _basinhopping.py.
update()
scipy.optimize._basinhopping.Storage.update (self, minres)
Definition at line 29 of file _basinhopping.py.
Referenced by matplotlib.patches.Shadow.__init__(), matplotlib.backends.backend_macosx.FigureCanvasMac.blit(), matplotlib.backends.backend_macosx.FigureCanvasMac.draw(), and matplotlib.backends.backend_qt.FigureCanvasQT.draw().
Member Data Documentation
minres
scipy.optimize._basinhopping.Storage.minres = minres
Definition at line 26 of file _basinhopping.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/optimize/_basinhopping.py