Code Cloning Analysis: pandas.core.arrays.datetimelike Namespace Reference
pandas.core.arrays.datetimelike Namespace Reference
Classes
class DatelikeOps
class DatetimeLikeArrayMixin
class TimelikeOps
Functions
_make_unpacked_invalid_op (str op_name)
F _period_dispatch (F meth)
bool _can_hold_na (self)
None __init__ (self, data, Dtype|None dtype=None, freq=None, bool copy=False)
type[DatetimeLikeScalar] _scalar_type (self)
DTScalarOrNaT _scalar_from_string (self, str value)
np.int64|np.datetime64|np.timedelta64 _unbox_scalar (self, DTScalarOrNaT value)
None _check_compatible_with (self, DTScalarOrNaT other)
_box_func (self, x)
np.ndarray _box_values (self, values)
Iterator __iter__ (self)
npt.NDArray[np.int64] asi8 (self)
npt.NDArray[np.object_] _format_native_types (self, *, str|float na_rep="NaT", date_format=None)
_formatter (self, bool boxed=False)
np.ndarray __array__ (self, NpDtype|None dtype=None, bool|None copy=None)
DTScalarOrNaT __getitem__ (self, ScalarIndexer item)
Self __getitem__ (self, SequenceIndexer|PositionalIndexerTuple item)
Self|DTScalarOrNaT __getitem__ (self, PositionalIndexer2D key)
BaseOffset|None _get_getitem_freq (self, key)
None __setitem__ (self, int|Sequence[int]|Sequence[bool]|slice key, NaTType|Any|Sequence[Any] value)
None _maybe_clear_freq (self)
astype (self, dtype, bool copy=True)
Self view (self)
DatetimeArray view (self, Literal["M8[ns]"] dtype)
TimedeltaArray view (self, Literal["m8[ns]"] dtype)
ArrayLike view (self, Dtype|None dtype=...)
_validate_comparison_value (self, other)
_validate_scalar (self, value, *, bool allow_listlike=False, bool unbox=True)
str _validation_error_message (self, value, bool allow_listlike=False)
_validate_listlike (self, value, bool allow_object=False)
_validate_setitem_value (self, value)
np.int64|np.datetime64|np.timedelta64|np.ndarray _unbox (self, other)
map (self, mapper, na_action=None)
npt.NDArray[np.bool_] isin (self, ArrayLike values)
npt.NDArray[np.bool_] isna (self)
npt.NDArray[np.bool_] _isnan (self)
bool _hasna (self)
np.ndarray _maybe_mask_results (self, np.ndarray result, fill_value=iNaT, convert=None)
str|None freqstr (self)
str|None inferred_freq (self)
Resolution|None _resolution_obj (self)
str resolution (self)
bool _is_monotonic_increasing (self)
bool _is_monotonic_decreasing (self)
bool _is_unique (self)
_cmp_method (self, other, op)
tuple[int|npt.NDArray[np.int64], None|npt.NDArray[np.bool_]] _get_i8_values_and_mask (self, other)
BaseOffset|None _get_arithmetic_result_freq (self, other)
DatetimeArray _add_datetimelike_scalar (self, other)
DatetimeArray _add_datetime_arraylike (self, DatetimeArray other)
TimedeltaArray _sub_datetimelike_scalar (self, datetime|np.datetime64 other)
TimedeltaArray _sub_datetime_arraylike (self, DatetimeArray other)
TimedeltaArray _sub_datetimelike (self, Timestamp|DatetimeArray other)
PeriodArray _add_period (self, Period other)
_add_offset (self, offset)
_add_timedeltalike_scalar (self, other)
_add_timedelta_arraylike (self, TimedeltaArray other)
_add_timedeltalike (self, Timedelta|TimedeltaArray other)
_add_nat (self)
_sub_nat (self)
npt.NDArray[np.object_] _sub_periodlike (self, Period|PeriodArray other)
_addsub_object_array (self, npt.NDArray[np.object_] other, op)
Self _accumulate (self, str name, *, bool skipna=True, **kwargs)
__add__ (self, other)
__radd__ (self, other)
__sub__ (self, other)
__rsub__ (self, other)
Self __iadd__ (self, other)
Self __isub__ (self, other)
Self _quantile (self, npt.NDArray[np.float64] qs, str interpolation)
min (self, *, AxisInt|None axis=None, bool skipna=True, **kwargs)
max (self, *, AxisInt|None axis=None, bool skipna=True, **kwargs)
mean (self, *, bool skipna=True, AxisInt|None axis=0)
median (self, *, AxisInt|None axis=None, bool skipna=True, **kwargs)
_mode (self, bool dropna=True)
_groupby_op (self, *, str how, bool has_dropped_na, int min_count, int ngroups, npt.NDArray[np.intp] ids, **kwargs)
tuple[ArrayLike, bool] ensure_arraylike_for_datetimelike (data, bool copy, str cls_name)
None validate_periods (None periods)
int validate_periods (int|float periods)
int|None validate_periods (int|float|None periods)
BaseOffset|None _validate_inferred_freq (BaseOffset|None freq, BaseOffset|None inferred_freq)
str dtype_to_unit (DatetimeTZDtype|np.dtype|ArrowDtype dtype)
Variables
DTScalarOrNaT = Union[DatetimeLikeScalar, NaTType]
tuple _infer_matches [str, ...]
Callable _is_recognized_dtype [[DtypeObj], bool]
tuple _recognized_scalars [type, ...]
np _ndarray .ndarray
BaseOffset freq | None
__pow__ = _make_unpacked_invalid_op("__pow__")
__rpow__ = _make_unpacked_invalid_op("__rpow__")
__mul__ = _make_unpacked_invalid_op("__mul__")
__rmul__ = _make_unpacked_invalid_op("__rmul__")
__truediv__ = _make_unpacked_invalid_op("__truediv__")
__rtruediv__ = _make_unpacked_invalid_op("__rtruediv__")
__floordiv__ = _make_unpacked_invalid_op("__floordiv__")
__rfloordiv__ = _make_unpacked_invalid_op("__rfloordiv__")
__mod__ = _make_unpacked_invalid_op("__mod__")
__rmod__ = _make_unpacked_invalid_op("__rmod__")
__divmod__ = _make_unpacked_invalid_op("__divmod__")
__rdivmod__ = _make_unpacked_invalid_op("__rdivmod__")
str _round_doc
str _round_example
str _floor_example
str _ceil_example
dtype = self._validation_error_message(value, allow_listlike)
_box_func
asi8 = bool)
shape = True)
_scalar_type
_hasna
_isnan = np.nan
BaseOffset _freq = result.freq
ndim
Function Documentation
__add__()
pandas.core.arrays.datetimelike.__add__ (self, other)
Definition at line 1386 of file datetimelike.py.
__array__()
np.ndarray pandas.core.arrays.datetimelike.__array__ (self, NpDtype | None dtype = None, bool | None copy = None)
Definition at line 356 of file datetimelike.py.
__getitem__() [1/3]
Self | DTScalarOrNaT pandas.core.arrays.datetimelike.__getitem__ (self, PositionalIndexer2D key)
This getitem defers to the underlying array, which by-definition can
only handle list-likes, slices, and integer scalars
Definition at line 390 of file datetimelike.py.
__getitem__() [2/3]
DTScalarOrNaT pandas.core.arrays.datetimelike.__getitem__ (self, ScalarIndexer item)
Definition at line 380 of file datetimelike.py.
__getitem__() [3/3]
Self pandas.core.arrays.datetimelike.__getitem__ (self, SequenceIndexer | PositionalIndexerTuple item)
Definition at line 384 of file datetimelike.py.
__iadd__()
Self pandas.core.arrays.datetimelike.__iadd__ (self, other)
Definition at line 1535 of file datetimelike.py.
__init__()
None pandas.core.arrays.datetimelike.__init__ (self, data, Dtype | None dtype = None, freq = None, bool copy = False)
Definition at line 222 of file datetimelike.py.
__isub__()
Self pandas.core.arrays.datetimelike.__isub__ (self, other)
Definition at line 1544 of file datetimelike.py.
__iter__()
Iterator pandas.core.arrays.datetimelike.__iter__ (self)
Definition at line 315 of file datetimelike.py.
__radd__()
pandas.core.arrays.datetimelike.__radd__ (self, other)
Definition at line 1441 of file datetimelike.py.
__rsub__()
pandas.core.arrays.datetimelike.__rsub__ (self, other)
Definition at line 1501 of file datetimelike.py.
__setitem__()
None pandas.core.arrays.datetimelike.__setitem__ (self, int | Sequence[int] | Sequence[bool] | slice key, NaTType | Any | Sequence[Any] value)
Definition at line 437 of file datetimelike.py.
__sub__()
pandas.core.arrays.datetimelike.__sub__ (self, other)
Definition at line 1446 of file datetimelike.py.
_accumulate()
Self pandas.core.arrays.datetimelike._accumulate (self, str name, * , bool skipna = True, ** kwargs) protected
Definition at line 1376 of file datetimelike.py.
_add_datetime_arraylike()
DatetimeArray pandas.core.arrays.datetimelike._add_datetime_arraylike (self, DatetimeArray other) protected
Definition at line 1140 of file datetimelike.py.
_add_datetimelike_scalar()
DatetimeArray pandas.core.arrays.datetimelike._add_datetimelike_scalar (self, other) protected
Definition at line 1106 of file datetimelike.py.
_add_nat()
pandas.core.arrays.datetimelike._add_nat (self) protected
Add pd.NaT to self
Definition at line 1273 of file datetimelike.py.
_add_offset()
pandas.core.arrays.datetimelike._add_offset (self, offset) protected
Definition at line 1214 of file datetimelike.py.
_add_period()
PeriodArray pandas.core.arrays.datetimelike._add_period (self, Period other) protected
Definition at line 1202 of file datetimelike.py.
_add_timedelta_arraylike()
pandas.core.arrays.datetimelike._add_timedelta_arraylike (self, TimedeltaArray other) protected
Add a delta of a TimedeltaIndex
Returns
-------
Same type as self
Definition at line 1237 of file datetimelike.py.
_add_timedeltalike()
pandas.core.arrays.datetimelike._add_timedeltalike (self, Timedelta | TimedeltaArray other) protected
Definition at line 1256 of file datetimelike.py.
_add_timedeltalike_scalar()
pandas.core.arrays.datetimelike._add_timedeltalike_scalar (self, other) protected
Add a delta of a timedeltalike
Returns
-------
Same type as self
Definition at line 1217 of file datetimelike.py.
_addsub_object_array()
pandas.core.arrays.datetimelike._addsub_object_array (self, npt.NDArray[np.object_] other, op) protected
Add or subtract array-like of DateOffset objects
Parameters
----------
other : np.ndarray[object]
op : {operator.add, operator.sub}
Returns
-------
np.ndarray[object]
    Except in fastpath case with length 1 where we operate on the
    contained scalar.
Definition at line 1341 of file datetimelike.py.
_box_func()
pandas.core.arrays.datetimelike._box_func (self, x) protected
box function to get object from internal representation
Definition at line 303 of file datetimelike.py.
_box_values()
np.ndarray pandas.core.arrays.datetimelike._box_values (self, values) protected
apply box func to passed values
Definition at line 309 of file datetimelike.py.
_can_hold_na()
bool pandas.core.arrays.datetimelike._can_hold_na (self) protected
Definition at line 219 of file datetimelike.py.
_check_compatible_with()
None pandas.core.arrays.datetimelike._check_compatible_with (self, DTScalarOrNaT other) protected
Verify that `self` and `other` are compatible.
* DatetimeArray verifies that the timezones (if any) match
* PeriodArray verifies that the freq matches
* Timedelta has no verification
In each case, NaT is considered compatible.
Parameters
----------
other
Raises
------
Exception
Definition at line 281 of file datetimelike.py.
_cmp_method()
pandas.core.arrays.datetimelike._cmp_method (self, other, op) protected
Definition at line 1000 of file datetimelike.py.
_format_native_types()
npt.NDArray[np.object_] pandas.core.arrays.datetimelike._format_native_types (self, * , str | float na_rep = "NaT", date_format = None) protected
Helper method for astype when converting to strings.
Returns
-------
ndarray[str]
Definition at line 337 of file datetimelike.py.
_formatter()
pandas.core.arrays.datetimelike._formatter (self, bool boxed = False) protected
Definition at line 349 of file datetimelike.py.
_get_arithmetic_result_freq()
BaseOffset | None pandas.core.arrays.datetimelike._get_arithmetic_result_freq (self, other) protected
Check if we can preserve self.freq in addition or subtraction.
Definition at line 1090 of file datetimelike.py.
_get_getitem_freq()
BaseOffset | None pandas.core.arrays.datetimelike._get_getitem_freq (self, key) protected
Find the `freq` attribute to assign to the result of a __getitem__ lookup.
Definition at line 407 of file datetimelike.py.
_get_i8_values_and_mask()
tuple[int | npt.NDArray[np.int64], None | npt.NDArray[np.bool_]] pandas.core.arrays.datetimelike._get_i8_values_and_mask (self, other) protected
Get the int64 values and b_mask to pass to add_overflowsafe.
Definition at line 1071 of file datetimelike.py.
_groupby_op()
pandas.core.arrays.datetimelike._groupby_op (self, * , str how, bool has_dropped_na, int min_count, int ngroups, npt.NDArray[np.intp] ids, ** kwargs) protected
Definition at line 1680 of file datetimelike.py.
_hasna()
bool pandas.core.arrays.datetimelike._hasna (self) protected
return if I have any nans; enables various perf speedups
Definition at line 867 of file datetimelike.py.
_is_monotonic_decreasing()
bool pandas.core.arrays.datetimelike._is_monotonic_decreasing (self) protected
Definition at line 990 of file datetimelike.py.
_is_monotonic_increasing()
bool pandas.core.arrays.datetimelike._is_monotonic_increasing (self) protected
Definition at line 986 of file datetimelike.py.
_is_unique()
bool pandas.core.arrays.datetimelike._is_unique (self) protected
Definition at line 994 of file datetimelike.py.
_isnan()
npt.NDArray[np.bool_] pandas.core.arrays.datetimelike._isnan (self) protected
return if each value is nan
Definition at line 860 of file datetimelike.py.
_make_unpacked_invalid_op()
pandas.core.arrays.datetimelike._make_unpacked_invalid_op (str op_name) protected
Definition at line 166 of file datetimelike.py.
_maybe_clear_freq()
None pandas.core.arrays.datetimelike._maybe_clear_freq (self) protected
Definition at line 459 of file datetimelike.py.
_maybe_mask_results()
np.ndarray pandas.core.arrays.datetimelike._maybe_mask_results (self, np.ndarray result, fill_value = iNaT, convert = None) protected
Parameters
----------
result : np.ndarray
fill_value : object, default iNaT
convert : str, dtype or None
Returns
-------
result : ndarray with values replace by the fill_value
mask the result if needed, convert to the provided dtype if its not
None
This is an internal routine.
Definition at line 873 of file datetimelike.py.
_mode()
pandas.core.arrays.datetimelike._mode (self, bool dropna = True) protected
Definition at line 1667 of file datetimelike.py.
_period_dispatch()
F pandas.core.arrays.datetimelike._period_dispatch (F meth) protected
For PeriodArray methods, dispatch to DatetimeArray and re-wrap the results
in PeriodArray.  We cannot use ._ndarray directly for the affected
methods because the i8 data has different semantics on NaT values.
Definition at line 171 of file datetimelike.py.
_quantile()
Self pandas.core.arrays.datetimelike._quantile (self, npt.NDArray[np.float64] qs, str interpolation) protected
Definition at line 1557 of file datetimelike.py.
_resolution_obj()
Resolution | None pandas.core.arrays.datetimelike._resolution_obj (self) protected
Definition at line 965 of file datetimelike.py.
_scalar_from_string()
DTScalarOrNaT pandas.core.arrays.datetimelike._scalar_from_string (self, str value) protected
Construct a scalar type from a string.
Parameters
----------
value : str
Returns
-------
Period, Timestamp, or Timedelta, or NaT
    Whatever the type of ``self._scalar_type`` is.
Notes
-----
This should call ``self._check_compatible_with`` before
unboxing the result.
Definition at line 238 of file datetimelike.py.
_scalar_type()
type[DatetimeLikeScalar] pandas.core.arrays.datetimelike._scalar_type (self) protected
The scalar associated with this datelike
* PeriodArray : Period
* DatetimeArray : Timestamp
* TimedeltaArray : Timedelta
Definition at line 228 of file datetimelike.py.
_sub_datetime_arraylike()
TimedeltaArray pandas.core.arrays.datetimelike._sub_datetime_arraylike (self, DatetimeArray other) protected
Definition at line 1169 of file datetimelike.py.
_sub_datetimelike()
TimedeltaArray pandas.core.arrays.datetimelike._sub_datetimelike (self, Timestamp | DatetimeArray other) protected
Definition at line 1182 of file datetimelike.py.
_sub_datetimelike_scalar()
TimedeltaArray pandas.core.arrays.datetimelike._sub_datetimelike_scalar (self, datetime | np.datetime64 other) protected
Definition at line 1150 of file datetimelike.py.
_sub_nat()
pandas.core.arrays.datetimelike._sub_nat (self) protected
Subtract pd.NaT from self
Definition at line 1296 of file datetimelike.py.
_sub_periodlike()
npt.NDArray[np.object_] pandas.core.arrays.datetimelike._sub_periodlike (self, Period | PeriodArray other) protected
Definition at line 1316 of file datetimelike.py.
_unbox()
np.int64 | np.datetime64 | np.timedelta64 | np.ndarray pandas.core.arrays.datetimelike._unbox (self, other) protected
Unbox either a scalar with _unbox_scalar or an instance of our own type.
Definition at line 742 of file datetimelike.py.
_unbox_scalar()
np.int64 | np.datetime64 | np.timedelta64 pandas.core.arrays.datetimelike._unbox_scalar (self, DTScalarOrNaT value) protected
Unbox the integer value of a scalar `value`.
Parameters
----------
value : Period, Timestamp, Timedelta, or NaT
    Depending on subclass.
Returns
-------
int
Examples
--------
>>> arr = pd.array(np.array(['1970-01-01'], 'datetime64[ns]'))
>>> arr._unbox_scalar(arr[0])
numpy.datetime64('1970-01-01T00:00:00.000000000')
Definition at line 258 of file datetimelike.py.
_validate_comparison_value()
pandas.core.arrays.datetimelike._validate_comparison_value (self, other) protected
Definition at line 547 of file datetimelike.py.
_validate_inferred_freq()
BaseOffset | None pandas.core.arrays.datetimelike._validate_inferred_freq (BaseOffset | None freq, BaseOffset | None inferred_freq) protected
If the user passes a freq and another freq is inferred from passed data,
require that they match.
Parameters
----------
freq : DateOffset or None
inferred_freq : DateOffset or None
Returns
-------
freq : DateOffset or None
Definition at line 2535 of file datetimelike.py.
Referenced by pandas.core.arrays.datetimelike.TimelikeOps._maybe_pin_freq().
_validate_listlike()
pandas.core.arrays.datetimelike._validate_listlike (self, value, bool allow_object = False) protected
Definition at line 675 of file datetimelike.py.
_validate_scalar()
pandas.core.arrays.datetimelike._validate_scalar (self, value, * , bool allow_listlike = False, bool unbox = True) protected
Validate that the input value can be cast to our scalar_type.
Parameters
----------
value : object
allow_listlike: bool, default False
    When raising an exception, whether the message should say
    listlike inputs are allowed.
unbox : bool, default True
    Whether to unbox the result before returning.  Note: unbox=False
    skips the setitem compatibility check.
Returns
-------
self._scalar_type or NaT
Definition at line 583 of file datetimelike.py.
_validate_setitem_value()
pandas.core.arrays.datetimelike._validate_setitem_value (self, value) protected
Definition at line 733 of file datetimelike.py.
_validation_error_message()
str pandas.core.arrays.datetimelike._validation_error_message (self, value, bool allow_listlike = False) protected
Construct an exception message on validation error.
Some methods allow only scalar inputs, while others allow either scalar
or listlike.
Parameters
----------
allow_listlike: bool, default False
Returns
-------
str
Definition at line 644 of file datetimelike.py.
asi8()
npt.NDArray[np.int64] pandas.core.arrays.datetimelike.asi8 (self)
Integer representation of the values.
Returns
-------
ndarray
    An ndarray with int64 dtype.
Definition at line 322 of file datetimelike.py.
astype()
pandas.core.arrays.datetimelike.astype (self, dtype, bool copy = True)
Definition at line 464 of file datetimelike.py.
dtype_to_unit()
str pandas.core.arrays.datetimelike.dtype_to_unit (DatetimeTZDtype | np.dtype | ArrowDtype dtype)
Return the unit str corresponding to the dtype's resolution.
Parameters
----------
dtype : DatetimeTZDtype or np.dtype
    If np.dtype, we assume it is a datetime64 dtype.
Returns
-------
str
Definition at line 2564 of file datetimelike.py.
Referenced by pandas.core.arrays.datetimelike.TimelikeOps._validate_frequency().
ensure_arraylike_for_datetimelike()
tuple[ArrayLike, bool] pandas.core.arrays.datetimelike.ensure_arraylike_for_datetimelike (data, bool copy, str cls_name)
Definition at line 2452 of file datetimelike.py.
freqstr()
str | None pandas.core.arrays.datetimelike.freqstr (self)
Return the frequency object as a string if it's set, otherwise None.
Examples
--------
For DatetimeIndex:
>>> idx = pd.DatetimeIndex(["1/1/2020 10:00:00+00:00"], freq="D")
>>> idx.freqstr
'D'
The frequency can be inferred if there are more than 2 points:
>>> idx = pd.DatetimeIndex(["2018-01-01", "2018-01-03", "2018-01-05"],
...                        freq="infer")
>>> idx.freqstr
'2D'
For PeriodIndex:
>>> idx = pd.PeriodIndex(["2023-1", "2023-2", "2023-3"], freq="M")
>>> idx.freqstr
'M'
Definition at line 904 of file datetimelike.py.
inferred_freq()
str | None pandas.core.arrays.datetimelike.inferred_freq (self)
Tries to return a string representing a frequency generated by infer_freq.
Returns None if it can't autodetect the frequency.
Examples
--------
For DatetimeIndex:
>>> idx = pd.DatetimeIndex(["2018-01-01", "2018-01-03", "2018-01-05"])
>>> idx.inferred_freq
'2D'
For TimedeltaIndex:
>>> tdelta_idx = pd.to_timedelta(["0 days", "10 days", "20 days"])
>>> tdelta_idx
TimedeltaIndex(['0 days', '10 days', '20 days'],
               dtype='timedelta64[ns]', freq=None)
>>> tdelta_idx.inferred_freq
'10D'
Definition at line 934 of file datetimelike.py.
isin()
npt.NDArray[np.bool_] pandas.core.arrays.datetimelike.isin (self, ArrayLike values)
Compute boolean array of whether each value is found in the
passed set of values.
Parameters
----------
values : np.ndarray or ExtensionArray
Returns
-------
ndarray[bool]
Definition at line 771 of file datetimelike.py.
References isin().
Referenced by isin().
isna()
npt.NDArray[np.bool_] pandas.core.arrays.datetimelike.isna (self)
Definition at line 856 of file datetimelike.py.
map()
pandas.core.arrays.datetimelike.map (self, mapper, na_action = None)
Definition at line 760 of file datetimelike.py.
max()
pandas.core.arrays.datetimelike.max (self, * , AxisInt | None axis = None, bool skipna = True, ** kwargs)
Return the maximum value of the Array or maximum along
an axis.
See Also
--------
numpy.ndarray.max
Index.max : Return the maximum value in an Index.
Series.max : Return the maximum value in a Series.
Definition at line 1583 of file datetimelike.py.
mean()
pandas.core.arrays.datetimelike.mean (self, * , bool skipna = True, AxisInt | None axis = 0)
Return the mean value of the Array.
Parameters
----------
skipna : bool, default True
    Whether to ignore any NaT elements.
axis : int, optional, default 0
Returns
-------
scalar
    Timestamp or Timedelta.
See Also
--------
numpy.ndarray.mean : Returns the average of array elements along a given axis.
Series.mean : Return the mean value in a Series.
Notes
-----
mean is only defined for Datetime and Timedelta dtypes, not for Period.
Examples
--------
For :class:`pandas.DatetimeIndex`:
>>> idx = pd.date_range('2001-01-01 00:00', periods=3)
>>> idx
DatetimeIndex(['2001-01-01', '2001-01-02', '2001-01-03'],
              dtype='datetime64[ns]', freq='D')
>>> idx.mean()
Timestamp('2001-01-02 00:00:00')
For :class:`pandas.TimedeltaIndex`:
>>> tdelta_idx = pd.to_timedelta([1, 2, 3], unit='D')
>>> tdelta_idx
TimedeltaIndex(['1 days', '2 days', '3 days'],
                dtype='timedelta64[ns]', freq=None)
>>> tdelta_idx.mean()
Timedelta('2 days 00:00:00')
Definition at line 1600 of file datetimelike.py.
median()
pandas.core.arrays.datetimelike.median (self, * , AxisInt | None axis = None, bool skipna = True, ** kwargs)
Definition at line 1658 of file datetimelike.py.
min()
pandas.core.arrays.datetimelike.min (self, * , AxisInt | None axis = None, bool skipna = True, ** kwargs)
Return the minimum value of the Array or minimum along
an axis.
See Also
--------
numpy.ndarray.min
Index.min : Return the minimum value in an Index.
Series.min : Return the minimum value in a Series.
Definition at line 1565 of file datetimelike.py.
resolution()
str pandas.core.arrays.datetimelike.resolution (self)
Returns day, hour, minute, second, millisecond or microsecond
Definition at line 975 of file datetimelike.py.
validate_periods() [1/3]
int pandas.core.arrays.datetimelike.validate_periods (int | float periods)
Definition at line 2497 of file datetimelike.py.
validate_periods() [2/3]
int | None pandas.core.arrays.datetimelike.validate_periods (int | float | None periods)
If a `periods` argument is passed to the Datetime/Timedelta Array/Index
constructor, cast it to an integer.
Parameters
----------
periods : None, float, int
Returns
-------
periods : None or int
Raises
------
TypeError
    if periods is None, float, or int
Definition at line 2501 of file datetimelike.py.
validate_periods() [3/3]
None pandas.core.arrays.datetimelike.validate_periods (None periods)
Definition at line 2492 of file datetimelike.py.
view() [1/4]
Self pandas.core.arrays.datetimelike.view (self)
Definition at line 522 of file datetimelike.py.
view() [2/4]
ArrayLike pandas.core.arrays.datetimelike.view (self, Dtype | None dtype = ...)
Definition at line 534 of file datetimelike.py.
view() [3/4]
DatetimeArray pandas.core.arrays.datetimelike.view (self, Literal["M8[ns]"] dtype)
Definition at line 526 of file datetimelike.py.
view() [4/4]
TimedeltaArray pandas.core.arrays.datetimelike.view (self, Literal["m8[ns]"] dtype)
Definition at line 530 of file datetimelike.py.
Variable Documentation
__divmod__
pandas.core.arrays.datetimelike.__divmod__ = _make_unpacked_invalid_op("__divmod__") private
Definition at line 1067 of file datetimelike.py.
__floordiv__
pandas.core.arrays.datetimelike.__floordiv__ = _make_unpacked_invalid_op("__floordiv__") private
Definition at line 1063 of file datetimelike.py.
__mod__
pandas.core.arrays.datetimelike.__mod__ = _make_unpacked_invalid_op("__mod__") private
Definition at line 1065 of file datetimelike.py.
__mul__
pandas.core.arrays.datetimelike.__mul__ = _make_unpacked_invalid_op("__mul__") private
Definition at line 1059 of file datetimelike.py.
__pow__
pandas.core.arrays.datetimelike.__pow__ = _make_unpacked_invalid_op("__pow__") private
Definition at line 1057 of file datetimelike.py.
__rdivmod__
pandas.core.arrays.datetimelike.__rdivmod__ = _make_unpacked_invalid_op("__rdivmod__") private
Definition at line 1068 of file datetimelike.py.
__rfloordiv__
pandas.core.arrays.datetimelike.__rfloordiv__ = _make_unpacked_invalid_op("__rfloordiv__") private
Definition at line 1064 of file datetimelike.py.
__rmod__
pandas.core.arrays.datetimelike.__rmod__ = _make_unpacked_invalid_op("__rmod__") private
Definition at line 1066 of file datetimelike.py.
__rmul__
pandas.core.arrays.datetimelike.__rmul__ = _make_unpacked_invalid_op("__rmul__") private
Definition at line 1060 of file datetimelike.py.
__rpow__
pandas.core.arrays.datetimelike.__rpow__ = _make_unpacked_invalid_op("__rpow__") private
Definition at line 1058 of file datetimelike.py.
__rtruediv__
pandas.core.arrays.datetimelike.__rtruediv__ = _make_unpacked_invalid_op("__rtruediv__") private
Definition at line 1062 of file datetimelike.py.
__truediv__
pandas.core.arrays.datetimelike.__truediv__ = _make_unpacked_invalid_op("__truediv__") private
Definition at line 1061 of file datetimelike.py.
_box_func
pandas.core.arrays.datetimelike._box_func protected
Definition at line 313 of file datetimelike.py.
_ceil_example
str pandas.core.arrays.datetimelike._ceil_example protected
Initial value:
=  """>>> rng.ceil('h')
    DatetimeIndex(['2018-01-01 12:00:00', '2018-01-01 12:00:00',
                   '2018-01-01 13:00:00'],
                  dtype='datetime64[ns]', freq=None)
    **Series**
    >>> pd.Series(rng).dt.ceil("h")
    0   2018-01-01 12:00:00
    1   2018-01-01 12:00:00
    2   2018-01-01 13:00:00
    dtype: datetime64[ns]
    When rounding near a daylight savings time transition, use ``ambiguous`` or
    ``nonexistent`` to control how the timestamp should be re-localized.
    >>> rng_tz = pd.DatetimeIndex(["2021-10-31 01:30:00"], tz="Europe/Amsterdam")
    >>> rng_tz.ceil("h", ambiguous=False)
    DatetimeIndex(['2021-10-31 02:00:00+01:00'],
                  dtype='datetime64[ns, Europe/Amsterdam]', freq=None)
    >>> rng_tz.ceil("h", ambiguous=True)
    DatetimeIndex(['2021-10-31 02:00:00+02:00'],
                  dtype='datetime64[ns, Europe/Amsterdam]', freq=None)
    """
Definition at line 1939 of file datetimelike.py.
_floor_example
str pandas.core.arrays.datetimelike._floor_example protected
Initial value:
=  """>>> rng.floor('h')
    DatetimeIndex(['2018-01-01 11:00:00', '2018-01-01 12:00:00',
                   '2018-01-01 12:00:00'],
                  dtype='datetime64[ns]', freq=None)
    **Series**
    >>> pd.Series(rng).dt.floor("h")
    0   2018-01-01 11:00:00
    1   2018-01-01 12:00:00
    2   2018-01-01 12:00:00
    dtype: datetime64[ns]
    When rounding near a daylight savings time transition, use ``ambiguous`` or
    ``nonexistent`` to control how the timestamp should be re-localized.
    >>> rng_tz = pd.DatetimeIndex(["2021-10-31 03:30:00"], tz="Europe/Amsterdam")
    >>> rng_tz.floor("2h", ambiguous=False)
    DatetimeIndex(['2021-10-31 02:00:00+01:00'],
                 dtype='datetime64[ns, Europe/Amsterdam]', freq=None)
    >>> rng_tz.floor("2h", ambiguous=True)
    DatetimeIndex(['2021-10-31 02:00:00+02:00'],
                  dtype='datetime64[ns, Europe/Amsterdam]', freq=None)
    """
Definition at line 1912 of file datetimelike.py.
_freq
BaseOffset pandas.core.arrays.datetimelike._freq = result.freq protected
Definition at line 1541 of file datetimelike.py.
_hasna
pandas.core.arrays.datetimelike._hasna protected
Definition at line 892 of file datetimelike.py.
_infer_matches
tuple pandas.core.arrays.datetimelike._infer_matches [str, ...] protected
Shared Base/Mixin class for DatetimeArray, TimedeltaArray, PeriodArray
Assumes that __new__/__init__ defines:
    _ndarray
and that inheriting subclass implements:
    freq
Definition at line 212 of file datetimelike.py.
_is_recognized_dtype
Callable pandas.core.arrays.datetimelike._is_recognized_dtype [[DtypeObj], bool] protected
Definition at line 213 of file datetimelike.py.
_isnan
pandas.core.arrays.datetimelike._isnan = np.nan protected
Definition at line 897 of file datetimelike.py.
_ndarray
pandas.core.arrays.datetimelike._ndarray .ndarray protected
Definition at line 215 of file datetimelike.py.
_recognized_scalars
pandas.core.arrays.datetimelike._recognized_scalars [type, ...] protected
Definition at line 214 of file datetimelike.py.
_round_doc
str pandas.core.arrays.datetimelike._round_doc protected
Definition at line 1822 of file datetimelike.py.
_round_example
str pandas.core.arrays.datetimelike._round_example protected
Initial value:
=  """>>> rng.round('h')
    DatetimeIndex(['2018-01-01 12:00:00', '2018-01-01 12:00:00',
                   '2018-01-01 12:00:00'],
                  dtype='datetime64[ns]', freq=None)
    **Series**
    >>> pd.Series(rng).dt.round("h")
    0   2018-01-01 12:00:00
    1   2018-01-01 12:00:00
    2   2018-01-01 12:00:00
    dtype: datetime64[ns]
    When rounding near a daylight savings time transition, use ``ambiguous`` or
    ``nonexistent`` to control how the timestamp should be re-localized.
    >>> rng_tz = pd.DatetimeIndex(["2021-10-31 03:30:00"], tz="Europe/Amsterdam")
    >>> rng_tz.floor("2h", ambiguous=False)
    DatetimeIndex(['2021-10-31 02:00:00+01:00'],
                  dtype='datetime64[ns, Europe/Amsterdam]', freq=None)
    >>> rng_tz.floor("2h", ambiguous=True)
    DatetimeIndex(['2021-10-31 02:00:00+02:00'],
                  dtype='datetime64[ns, Europe/Amsterdam]', freq=None)
    """
Definition at line 1885 of file datetimelike.py.
_scalar_type
pandas.core.arrays.datetimelike._scalar_type protected
Definition at line 607 of file datetimelike.py.
asi8
pandas.core.arrays.datetimelike.asi8 = bool)
Definition at line 319 of file datetimelike.py.
DTScalarOrNaT
pandas.core.arrays.datetimelike.DTScalarOrNaT = Union[DatetimeLikeScalar, NaTType]
Definition at line 163 of file datetimelike.py.
dtype
pandas.core.arrays.datetimelike.dtype = self._validation_error_message(value, allow_listlike)
Definition at line 180 of file datetimelike.py.
freq
pandas.core.arrays.datetimelike.freq | None
Definition at line 216 of file datetimelike.py.
ndim
pandas.core.arrays.datetimelike.ndim
Definition at line 1577 of file datetimelike.py.
shape
pandas.core.arrays.datetimelike.shape = True)
Definition at line 488 of file datetimelike.py.