Code Cloning Analysis: matplotlib.tri._triinterpolate.LinearTriInterpolator Class Reference
matplotlib.tri._triinterpolate.LinearTriInterpolator Class Reference
Public Member Functions
__init__ (self, triangulation, z, trifinder=None)
__call__ (self, x, y)
gradient (self, x, y)
Public Member Functions inherited from matplotlib.tri._triinterpolate.TriInterpolator
__init__ (self, triangulation, z, trifinder=None)
Protected Member Functions
_interpolate_single_key (self, return_key, tri_index, x, y)
Protected Member Functions inherited from matplotlib.tri._triinterpolate.TriInterpolator
_interpolate_multikeys (self, x, y, tri_index=None, return_keys=('z',))
Protected Attributes
_plane_coefficients
Protected Attributes inherited from matplotlib.tri._triinterpolate.TriInterpolator
_triangulation = triangulation
_z = np.asarray(z)
_trifinder = trifinder or self._triangulation.get_trifinder()
float _unit_x = 1.0
float _unit_y = 1.0
_tri_renum = None
Static Private Attributes
__doc__
Additional Inherited Members
Static Protected Attributes inherited from matplotlib.tri._triinterpolate.TriInterpolator
str _docstring__call__
str _docstringgradient
Detailed Description
Linear interpolator on a triangular grid.
Each triangle is represented by a plane so that an interpolated value at
point (x, y) lies on the plane of the triangle containing (x, y).
Interpolated values are therefore continuous across the triangulation, but
their first derivatives are discontinuous at edges between triangles.
Parameters
----------
triangulation : `~matplotlib.tri.Triangulation`
    The triangulation to interpolate over.
z : (npoints,) array-like
    Array of values, defined at grid points, to interpolate between.
trifinder : `~matplotlib.tri.TriFinder`, optional
    If this is not specified, the Triangulation's default TriFinder will
    be used by calling `.Triangulation.get_trifinder`.
Methods
-------
`__call__` (x, y) : Returns interpolated values at (x, y) points.
`gradient` (x, y) : Returns interpolated derivatives at (x, y) points.
Definition at line 232 of file _triinterpolate.py.
Constructor & Destructor Documentation
__init__()
matplotlib.tri._triinterpolate.LinearTriInterpolator.__init__ (self, triangulation, z, trifinder = None)
Definition at line 257 of file _triinterpolate.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__call__()
matplotlib.tri._triinterpolate.LinearTriInterpolator.__call__ (self, x, y)
Definition at line 264 of file _triinterpolate.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), and scipy.interpolate._fitpack2.SphereBivariateSpline.ev().
_interpolate_single_key()
matplotlib.tri._triinterpolate.LinearTriInterpolator._interpolate_single_key (self, return_key, tri_index, x, y) protected
Interpolate at points belonging to the triangulation
(inside an unmasked triangles).
Parameters
----------
return_key : {'z', 'dzdx', 'dzdy'}
    The requested values (z or its derivatives).
tri_index : 1D int array
    Valid triangle index (cannot be -1).
x, y : 1D arrays, same shape as `tri_index`
    Valid locations where interpolation is requested.
Returns
-------
1-d array
    Returned array of the same size as *tri_index*
Reimplemented from matplotlib.tri._triinterpolate.TriInterpolator.
Definition at line 274 of file _triinterpolate.py.
References _plane_coefficients.
gradient()
matplotlib.tri._triinterpolate.LinearTriInterpolator.gradient (self, x, y)
Definition at line 269 of file _triinterpolate.py.
Member Data Documentation
__doc__
matplotlib.tri._triinterpolate.LinearTriInterpolator.__doc__ static private
Definition at line 267 of file _triinterpolate.py.
Referenced by scipy.stats._multivariate.multivariate_t_gen.__init__(), scipy.stats._distn_infrastructure.rv_discrete._attach_methods(), scipy.stats._distn_infrastructure.rv_generic._construct_default_doc(), scipy.stats._distn_infrastructure.rv_generic._construct_doc(), and pip._vendor.pygments.sphinxext.PygmentsDoc.document_lexers_overview().
_plane_coefficients
matplotlib.tri._triinterpolate.LinearTriInterpolator._plane_coefficients protected
Initial value:
=  \
            self._triangulation.calculate_plane_coefficients(self._z)
Definition at line 261 of file _triinterpolate.py.
Referenced by _interpolate_single_key().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/tri/_triinterpolate.py