Code Cloning Analysis: joblib.hashing._ConsistentSet Class Reference
joblib.hashing._ConsistentSet Class Reference
Public Member Functions
__init__ (self, set_sequence)
Protected Attributes
_sequence = sorted(set_sequence)
Detailed Description
Class used to ensure the hash of Sets is preserved
whatever the order of its items.
Definition at line 21 of file hashing.py.
Constructor & Destructor Documentation
__init__()
joblib.hashing._ConsistentSet.__init__ (self, set_sequence)
Definition at line 26 of file hashing.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Data Documentation
_sequence
joblib.hashing._ConsistentSet._sequence = sorted(set_sequence) protected
Definition at line 33 of file hashing.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/joblib/hashing.py