Code Cloning Analysis: numpy.lib.tests.test__datasource.TestDataSourceOpen Class Reference
numpy.lib.tests.test__datasource.TestDataSourceOpen Class Reference
Public Member Functions
setup_method (self)
teardown_method (self)
test_ValidHTTP (self)
test_InvalidHTTP (self)
test_InvalidHTTPCacheURLError (self)
test_ValidFile (self)
test_InvalidFile (self)
test_ValidGzipFile (self)
test_ValidBz2File (self)
Public Attributes
tmpdir = mkdtemp()
ds = datasource.DataSource(self.tmpdir)
Detailed Description
Definition at line 89 of file test__datasource.py.
Member Function Documentation
setup_method()
numpy.lib.tests.test__datasource.TestDataSourceOpen.setup_method (self)
Definition at line 90 of file test__datasource.py.
teardown_method()
numpy.lib.tests.test__datasource.TestDataSourceOpen.teardown_method (self)
Definition at line 94 of file test__datasource.py.
test_InvalidFile()
numpy.lib.tests.test__datasource.TestDataSourceOpen.test_InvalidFile (self)
Definition at line 121 of file test__datasource.py.
test_InvalidHTTP()
numpy.lib.tests.test__datasource.TestDataSourceOpen.test_InvalidHTTP (self)
Definition at line 103 of file test__datasource.py.
test_InvalidHTTPCacheURLError()
numpy.lib.tests.test__datasource.TestDataSourceOpen.test_InvalidHTTPCacheURLError (self)
Definition at line 112 of file test__datasource.py.
test_ValidBz2File()
numpy.lib.tests.test__datasource.TestDataSourceOpen.test_ValidBz2File (self)
Definition at line 141 of file test__datasource.py.
test_ValidFile()
numpy.lib.tests.test__datasource.TestDataSourceOpen.test_ValidFile (self)
Definition at line 115 of file test__datasource.py.
test_ValidGzipFile()
numpy.lib.tests.test__datasource.TestDataSourceOpen.test_ValidGzipFile (self)
Definition at line 125 of file test__datasource.py.
test_ValidHTTP()
numpy.lib.tests.test__datasource.TestDataSourceOpen.test_ValidHTTP (self)
Definition at line 98 of file test__datasource.py.
Member Data Documentation
ds
numpy.lib.tests.test__datasource.TestDataSourceOpen.ds = datasource.DataSource(self.tmpdir)
Definition at line 92 of file test__datasource.py.
Referenced by scipy.optimize._nonlin.LowRankMatrix.collapse(), scipy.optimize._nonlin.LowRankMatrix.matvec(), scipy.optimize._nonlin.LowRankMatrix.restart_reduce(), scipy.optimize._nonlin.LowRankMatrix.rmatvec(), scipy.optimize._nonlin.LowRankMatrix.rsolve(), scipy.optimize._nonlin.LowRankMatrix.simple_reduce(), scipy.optimize._nonlin.LowRankMatrix.solve(), and scipy.optimize._nonlin.LowRankMatrix.svd_reduce().
tmpdir
numpy.lib.tests.test__datasource.TestDataSourceOpen.tmpdir = mkdtemp()
Definition at line 91 of file test__datasource.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/lib/tests/test__datasource.py