Code Cloning Analysis: sklearn.base Namespace Reference
sklearn.base Namespace Reference
Classes
class _UnstableArchMixin
class BaseEstimator
class BiclusterMixin
class ClassifierMixin
class ClassNamePrefixFeaturesOutMixin
class ClusterMixin
class DensityMixin
class MetaEstimatorMixin
class MultiOutputMixin
class OneToOneFeatureMixin
class OutlierMixin
class RegressorMixin
class TransformerMixin
Functions
clone (estimator, *, safe=True)
_clone_parametrized (estimator, *, safe=True)
is_classifier (estimator)
is_regressor (estimator)
is_clusterer (estimator)
is_outlier_detector (estimator)
_fit_context (*, prefer_skip_nested_validation)
Detailed Description
Base classes for all estimators and various utility functions.
Function Documentation
_clone_parametrized()
sklearn.base._clone_parametrized (estimator, * , safe = True) protected
Default implementation of clone. See :func:`sklearn.base.clone` for details.
Definition at line 98 of file base.py.
References clone().
Referenced by clone().
_fit_context()
sklearn.base._fit_context (* , prefer_skip_nested_validation) protected
Decorator to run the fit methods of estimators within context managers.
Parameters
----------
prefer_skip_nested_validation : bool
    If True, the validation of parameters of inner estimators or functions
    called during fit will be skipped.
    This is useful to avoid validating many times the parameters passed by the
    user from the public facing API. It's also useful to avoid validating
    parameters that we pass internally to inner functions that are guaranteed to
    be valid by the test suite.
    It should be set to True for most estimators, except for those that receive
    non-validated objects as parameters, such as meta-estimators that are given
    estimator objects.
Returns
-------
decorated_fit : method
    The decorated fit method.
Definition at line 1323 of file base.py.
clone()
sklearn.base.clone (estimator, * , safe = True)
Construct a new unfitted estimator with the same parameters.
Clone does a deep copy of the model in an estimator
without actually copying attached data. It returns a new estimator
with the same parameters that has not been fitted on any data.
.. versionchanged:: 1.3
    Delegates to `estimator.__sklearn_clone__` if the method exists.
Parameters
----------
estimator : {list, tuple, set} of estimator instance or a single \
        estimator instance
    The estimator or group of estimators to be cloned.
safe : bool, default=True
    If safe is False, clone will fall back to a deep copy on objects
    that are not estimators. Ignored if `estimator.__sklearn_clone__`
    exists.
Returns
-------
estimator : object
    The deep copy of the input, an estimator if input is an estimator.
Notes
-----
If the estimator's `random_state` parameter is an integer (or if the
estimator doesn't have a `random_state` parameter), an *exact clone* is
returned: the clone and the original estimator will give the exact same
results. Otherwise, *statistical clone* is returned: the clone might
return different results from the original estimator. More details can be
found in :ref:`randomness`.
Examples
--------
>>> from sklearn.base import clone
>>> from sklearn.linear_model import LogisticRegression
>>> X = [[-1, 0], [0, 1], [0, -1], [1, 0]]
>>> y = [0, 0, 1, 1]
>>> classifier = LogisticRegression().fit(X, y)
>>> cloned_classifier = clone(classifier)
>>> hasattr(classifier, "classes_")
True
>>> hasattr(cloned_classifier, "classes_")
False
>>> classifier is cloned_classifier
False
Definition at line 44 of file base.py.
References _clone_parametrized().
Referenced by _clone_parametrized().
is_classifier()
sklearn.base.is_classifier (estimator)
Return True if the given estimator is (probably) a classifier.
Parameters
----------
estimator : object
    Estimator object to test.
Returns
-------
out : bool
    True if estimator is a classifier and False otherwise.
Examples
--------
>>> from sklearn.base import is_classifier
>>> from sklearn.cluster import KMeans
>>> from sklearn.svm import SVC, SVR
>>> classifier = SVC()
>>> regressor = SVR()
>>> kmeans = KMeans()
>>> is_classifier(classifier)
True
>>> is_classifier(regressor)
False
>>> is_classifier(kmeans)
False
Definition at line 1176 of file base.py.
is_clusterer()
sklearn.base.is_clusterer (estimator)
Return True if the given estimator is (probably) a clusterer.
.. versionadded:: 1.6
Parameters
----------
estimator : object
    Estimator object to test.
Returns
-------
out : bool
    True if estimator is a clusterer and False otherwise.
Examples
--------
>>> from sklearn.base import is_clusterer
>>> from sklearn.cluster import KMeans
>>> from sklearn.svm import SVC, SVR
>>> classifier = SVC()
>>> regressor = SVR()
>>> kmeans = KMeans()
>>> is_clusterer(classifier)
False
>>> is_clusterer(regressor)
False
>>> is_clusterer(kmeans)
True
Definition at line 1256 of file base.py.
is_outlier_detector()
sklearn.base.is_outlier_detector (estimator)
Return True if the given estimator is (probably) an outlier detector.
Parameters
----------
estimator : estimator instance
    Estimator object to test.
Returns
-------
out : bool
    True if estimator is an outlier detector and False otherwise.
Definition at line 1298 of file base.py.
is_regressor()
sklearn.base.is_regressor (estimator)
Return True if the given estimator is (probably) a regressor.
Parameters
----------
estimator : estimator instance
    Estimator object to test.
Returns
-------
out : bool
    True if estimator is a regressor and False otherwise.
Examples
--------
>>> from sklearn.base import is_regressor
>>> from sklearn.cluster import KMeans
>>> from sklearn.svm import SVC, SVR
>>> classifier = SVC()
>>> regressor = SVR()
>>> kmeans = KMeans()
>>> is_regressor(classifier)
False
>>> is_regressor(regressor)
True
>>> is_regressor(kmeans)
False
Definition at line 1216 of file base.py.