Code Cloning Analysis: scipy.optimize.tests.test_minimize_constrained.HyperbolicIneq Class Reference
scipy.optimize.tests.test_minimize_constrained.HyperbolicIneq Class Reference
Public Member Functions
__init__ (self, constr_jac=None, constr_hess=None)
fun (self, x)
grad (self, x)
hess (self, x)
constr (self)
Public Attributes
list x0 = [0, 0]
list x_opt = [1.952823, 0.088659]
constr_jac = constr_jac
constr_hess = constr_hess
bounds = Bounds(0, np.inf)
Detailed Description
Problem 15.1 from Nocedal and Wright
The following optimization problem:
    minimize 1/2*(x[0] - 2)**2 + 1/2*(x[1] - 1/2)**2
    Subject to: 1/(x[0] + 1) - x[1] >= 1/4
                               x[0] >= 0
                               x[1] >= 0
Definition at line 162 of file test_minimize_constrained.py.
Constructor & Destructor Documentation
__init__()
scipy.optimize.tests.test_minimize_constrained.HyperbolicIneq.__init__ (self, constr_jac = None, constr_hess = None)
Definition at line 171 of file test_minimize_constrained.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
constr()
scipy.optimize.tests.test_minimize_constrained.HyperbolicIneq.constr (self)
Definition at line 188 of file test_minimize_constrained.py.
fun()
scipy.optimize.tests.test_minimize_constrained.HyperbolicIneq.fun (self, x)
Definition at line 178 of file test_minimize_constrained.py.
grad()
scipy.optimize.tests.test_minimize_constrained.HyperbolicIneq.grad (self, x)
Definition at line 181 of file test_minimize_constrained.py.
hess()
scipy.optimize.tests.test_minimize_constrained.HyperbolicIneq.hess (self, x)
Definition at line 184 of file test_minimize_constrained.py.
Member Data Documentation
bounds
scipy.optimize.tests.test_minimize_constrained.HyperbolicIneq.bounds = Bounds(0, np.inf)
Definition at line 176 of file test_minimize_constrained.py.
Referenced by sklearn.gaussian_process.kernels.Kernel._check_bounds_params(), and matplotlib.transforms.BboxBase.anchored().
constr_hess
scipy.optimize.tests.test_minimize_constrained.HyperbolicIneq.constr_hess = constr_hess
Definition at line 175 of file test_minimize_constrained.py.
constr_jac
scipy.optimize.tests.test_minimize_constrained.HyperbolicIneq.constr_jac = constr_jac
Definition at line 174 of file test_minimize_constrained.py.
x0
list scipy.optimize.tests.test_minimize_constrained.HyperbolicIneq.x0 = [0, 0]
Definition at line 172 of file test_minimize_constrained.py.
x_opt
list scipy.optimize.tests.test_minimize_constrained.HyperbolicIneq.x_opt = [1.952823, 0.088659]
Definition at line 173 of file test_minimize_constrained.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/optimize/tests/test_minimize_constrained.py