Code Cloning Analysis: scipy.signal.tests.test_ltisys.Test_abcd_normalize Class Reference
scipy.signal.tests.test_ltisys.Test_abcd_normalize Class Reference
Public Member Functions
setup_method (self)
test_no_matrix_fails (self)
test_A_nosquare_fails (self)
test_AB_mismatch_fails (self)
test_AC_mismatch_fails (self)
test_CD_mismatch_fails (self)
test_BD_mismatch_fails (self)
test_normalized_matrices_unchanged (self)
test_shapes (self)
test_zero_dimension_is_not_none1 (self)
test_zero_dimension_is_not_none2 (self)
test_missing_A (self)
test_missing_B (self)
test_missing_C (self)
test_missing_D (self)
test_missing_AB (self)
test_missing_AC (self)
test_missing_AD (self)
test_missing_BC (self)
test_missing_ABC_fails (self)
test_missing_BD_fails (self)
test_missing_CD_fails (self)
Public Attributes
A = np.array([[1.0, 2.0], [3.0, 4.0]])
B = np.array([[-1.0], [5.0]])
C = np.array([[4.0, 5.0]])
D = np.array([[2.5]])
Detailed Description
Definition at line 1001 of file test_ltisys.py.
Member Function Documentation
setup_method()
scipy.signal.tests.test_ltisys.Test_abcd_normalize.setup_method (self)
Definition at line 1002 of file test_ltisys.py.
test_A_nosquare_fails()
scipy.signal.tests.test_ltisys.Test_abcd_normalize.test_A_nosquare_fails (self)
Definition at line 1011 of file test_ltisys.py.
test_AB_mismatch_fails()
scipy.signal.tests.test_ltisys.Test_abcd_normalize.test_AB_mismatch_fails (self)
Definition at line 1015 of file test_ltisys.py.
test_AC_mismatch_fails()
scipy.signal.tests.test_ltisys.Test_abcd_normalize.test_AC_mismatch_fails (self)
Definition at line 1019 of file test_ltisys.py.
test_BD_mismatch_fails()
scipy.signal.tests.test_ltisys.Test_abcd_normalize.test_BD_mismatch_fails (self)
Definition at line 1027 of file test_ltisys.py.
test_CD_mismatch_fails()
scipy.signal.tests.test_ltisys.Test_abcd_normalize.test_CD_mismatch_fails (self)
Definition at line 1023 of file test_ltisys.py.
test_missing_A()
scipy.signal.tests.test_ltisys.Test_abcd_normalize.test_missing_A (self)
Definition at line 1066 of file test_ltisys.py.
test_missing_AB()
scipy.signal.tests.test_ltisys.Test_abcd_normalize.test_missing_AB (self)
Definition at line 1090 of file test_ltisys.py.
test_missing_ABC_fails()
scipy.signal.tests.test_ltisys.Test_abcd_normalize.test_missing_ABC_fails (self)
Definition at line 1125 of file test_ltisys.py.
test_missing_AC()
scipy.signal.tests.test_ltisys.Test_abcd_normalize.test_missing_AC (self)
Definition at line 1098 of file test_ltisys.py.
test_missing_AD()
scipy.signal.tests.test_ltisys.Test_abcd_normalize.test_missing_AD (self)
Definition at line 1107 of file test_ltisys.py.
test_missing_B()
scipy.signal.tests.test_ltisys.Test_abcd_normalize.test_missing_B (self)
Definition at line 1072 of file test_ltisys.py.
test_missing_BC()
scipy.signal.tests.test_ltisys.Test_abcd_normalize.test_missing_BC (self)
Definition at line 1116 of file test_ltisys.py.
test_missing_BD_fails()
scipy.signal.tests.test_ltisys.Test_abcd_normalize.test_missing_BD_fails (self)
Definition at line 1128 of file test_ltisys.py.
test_missing_C()
scipy.signal.tests.test_ltisys.Test_abcd_normalize.test_missing_C (self)
Definition at line 1078 of file test_ltisys.py.
test_missing_CD_fails()
scipy.signal.tests.test_ltisys.Test_abcd_normalize.test_missing_CD_fails (self)
Definition at line 1131 of file test_ltisys.py.
test_missing_D()
scipy.signal.tests.test_ltisys.Test_abcd_normalize.test_missing_D (self)
Definition at line 1084 of file test_ltisys.py.
test_no_matrix_fails()
scipy.signal.tests.test_ltisys.Test_abcd_normalize.test_no_matrix_fails (self)
Definition at line 1008 of file test_ltisys.py.
test_normalized_matrices_unchanged()
scipy.signal.tests.test_ltisys.Test_abcd_normalize.test_normalized_matrices_unchanged (self)
Definition at line 1031 of file test_ltisys.py.
test_shapes()
scipy.signal.tests.test_ltisys.Test_abcd_normalize.test_shapes (self)
Definition at line 1038 of file test_ltisys.py.
test_zero_dimension_is_not_none1()
scipy.signal.tests.test_ltisys.Test_abcd_normalize.test_zero_dimension_is_not_none1 (self)
Definition at line 1046 of file test_ltisys.py.
test_zero_dimension_is_not_none2()
scipy.signal.tests.test_ltisys.Test_abcd_normalize.test_zero_dimension_is_not_none2 (self)
Definition at line 1056 of file test_ltisys.py.
Member Data Documentation
A
scipy.signal.tests.test_ltisys.Test_abcd_normalize.A = np.array([[1.0, 2.0], [3.0, 4.0]])
Definition at line 1003 of file test_ltisys.py.
Referenced by scipy.sparse.linalg._matfuncs._ExpmPadeHelper.__init__(), scipy.sparse.linalg.tests.test_onenormest.MatrixProductOperator._matmat(), scipy.sparse.linalg._eigen.tests.test_svds.CheckingLinearOperator._matvec(), scipy.sparse.linalg.tests.test_onenormest.MatrixProductOperator._matvec(), scipy.sparse.linalg._eigen.tests.test_svds.CheckingLinearOperator._rmatvec(), and scipy.sparse.linalg.tests.test_onenormest.MatrixProductOperator._rmatvec().
B
scipy.signal.tests.test_ltisys.Test_abcd_normalize.B = np.array([[-1.0], [5.0]])
Definition at line 1004 of file test_ltisys.py.
Referenced by scipy.sparse.linalg.tests.test_onenormest.MatrixProductOperator._matmat(), scipy.sparse.linalg.tests.test_onenormest.MatrixProductOperator._matvec(), and scipy.sparse.linalg.tests.test_onenormest.MatrixProductOperator._rmatvec().
C
scipy.signal.tests.test_ltisys.Test_abcd_normalize.C = np.array([[4.0, 5.0]])
Definition at line 1005 of file test_ltisys.py.
Referenced by scipy.stats._multivariate.invwishart_frozen.__init__(), sklearn.svm._base.BaseLibSVM._decision_function(), sklearn.svm._base.BaseLibSVM._validate_targets(), sklearn.linear_model._logistic.LogisticRegression.fit(), sklearn.linear_model._passive_aggressive.PassiveAggressiveClassifier.fit(), sklearn.linear_model._passive_aggressive.PassiveAggressiveRegressor.fit(), sklearn.svm._classes.LinearSVC.fit(), sklearn.svm._classes.LinearSVR.fit(), sklearn.linear_model._passive_aggressive.PassiveAggressiveClassifier.partial_fit(), sklearn.linear_model._passive_aggressive.PassiveAggressiveRegressor.partial_fit(), and sklearn.svm._base.BaseSVC.predict_log_proba().
D
scipy.signal.tests.test_ltisys.Test_abcd_normalize.D = np.array([[2.5]])
Definition at line 1006 of file test_ltisys.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/signal/tests/test_ltisys.py