Code Cloning Analysis: fontTools.colorLib.table_builder.TableBuilder Class Reference
fontTools.colorLib.table_builder.TableBuilder Class Reference
Public Member Functions
__init__ (self, callbackTable=None)
build (self, cls, source)
Protected Member Functions
_convert (self, dest, field, converter, value)
Protected Attributes
_callbackTable = callbackTable
Detailed Description
Helps to populate things derived from BaseTable from maps, tuples, etc.
A table of lifecycle callbacks may be provided to add logic beyond what is possible
based on otData info for the target class. See BuildCallbacks.
Definition at line 75 of file table_builder.py.
Constructor & Destructor Documentation
__init__()
fontTools.colorLib.table_builder.TableBuilder.__init__ (self, callbackTable = None)
Definition at line 83 of file table_builder.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_convert()
fontTools.colorLib.table_builder.TableBuilder._convert (self, dest, field, converter, value) protected
Definition at line 88 of file table_builder.py.
build()
fontTools.colorLib.table_builder.TableBuilder.build (self, cls, source)
Definition at line 121 of file table_builder.py.
Member Data Documentation
_callbackTable
fontTools.colorLib.table_builder.TableBuilder._callbackTable = callbackTable protected
Definition at line 86 of file table_builder.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/colorLib/table_builder.py