Code Cloning Analysis: axisartist.grid_finder.FormatterPrettyPrint Class Reference
axisartist.grid_finder.FormatterPrettyPrint Class Reference
Public Member Functions
__init__ (self, useMathText=True)
__call__ (self, direction, factor, values)
Protected Attributes
_fmt
Detailed Description
Definition at line 296 of file grid_finder.py.
Constructor & Destructor Documentation
__init__()
axisartist.grid_finder.FormatterPrettyPrint.__init__ (self, useMathText = True)
Definition at line 297 of file grid_finder.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__call__()
axisartist.grid_finder.FormatterPrettyPrint.__call__ (self, direction, factor, values)
Definition at line 302 of file grid_finder.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), and scipy.interpolate._fitpack2.SphereBivariateSpline.ev().
Member Data Documentation
_fmt
axisartist.grid_finder.FormatterPrettyPrint._fmt protected
Initial value:
=  mticker.ScalarFormatter(
            useMathText=useMathText, useOffset=False)
Definition at line 298 of file grid_finder.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/mpl_toolkits/axisartist/grid_finder.py