Code Cloning Analysis: scipy.optimize._shgo_lib._vertex.VertexCube Class Reference
scipy.optimize._shgo_lib._vertex.VertexCube Class Reference
Public Member Functions
__init__ (self, x, nn=None, index=None)
connect (self, v)
disconnect (self, v)
Public Member Functions inherited from scipy.optimize._shgo_lib._vertex.VertexBase
__init__ (self, x, nn=None, index=None)
__hash__ (self)
__getattr__ (self, item)
star (self)
Additional Inherited Members
Public Attributes inherited from scipy.optimize._shgo_lib._vertex.VertexBase
x = x
hash = hash(self.x)
nn = set(nn)
index = index
x_a = np.array(self.x)
st = self.nn
Detailed Description
Vertex class to be used for a pure simplicial complex with no associated
differential geometry (single level domain that exists in R^n)
Definition at line 205 of file _vertex.py.
Constructor & Destructor Documentation
__init__()
scipy.optimize._shgo_lib._vertex.VertexCube.__init__ (self, x, nn = None, index = None)
Definition at line 208 of file _vertex.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
connect()
scipy.optimize._shgo_lib._vertex.VertexCube.connect (self, v)
Reimplemented from scipy.optimize._shgo_lib._vertex.VertexBase.
Definition at line 211 of file _vertex.py.
Referenced by matplotlib.patches.ConnectionStyle._Base.__call__().
disconnect()
scipy.optimize._shgo_lib._vertex.VertexCube.disconnect (self, v)
Reimplemented from scipy.optimize._shgo_lib._vertex.VertexBase.
Definition at line 216 of file _vertex.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/optimize/_shgo_lib/_vertex.py