Code Cloning Analysis: scipy.optimize.tests.test_least_squares.ExponentialFittingProblem Class Reference
scipy.optimize.tests.test_least_squares.ExponentialFittingProblem Class Reference
Public Member Functions
__init__ (self, a, b, noise, n_outliers=1, x_range=(-1, 1), n_points=11, random_seed=None)
fun (self, p)
jac (self, p)
Public Attributes
m = n_points
int n = 2
p0 = np.zeros(2)
x = np.linspace(x_range[0], x_range[1], n_points)
y = a + np.exp(b * self.x)
p_opt = np.array([a, b])
Detailed Description
Provide data and function for exponential fitting in the form
y = a + exp(b * x) + noise.
Definition at line 128 of file test_least_squares.py.
Constructor & Destructor Documentation
__init__()
scipy.optimize.tests.test_least_squares.ExponentialFittingProblem.__init__ (self, a, b, noise, n_outliers = 1, x_range = (-1, 1), n_points = 11, random_seed = None)
Definition at line 132 of file test_least_squares.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
fun()
scipy.optimize.tests.test_least_squares.ExponentialFittingProblem.fun (self, p)
Definition at line 149 of file test_least_squares.py.
jac()
scipy.optimize.tests.test_least_squares.ExponentialFittingProblem.jac (self, p)
Definition at line 152 of file test_least_squares.py.
Referenced by scipy.optimize.tests.test_slsqp.TestSLSQP.fprime_ieqcon2(), and scipy.optimize.tests.test_slsqp.TestSLSQP.jac().
Member Data Documentation
m
scipy.optimize.tests.test_least_squares.ExponentialFittingProblem.m = n_points
Definition at line 135 of file test_least_squares.py.
Referenced by scipy.spatial._kdtree.Rectangle.__init__(), scipy.stats._morestats._ABW.__init__(), scipy.stats._morestats._ABW._recalc(), and scipy.signal._czt.CZT.points().
n
int scipy.optimize.tests.test_least_squares.ExponentialFittingProblem.n = 2
Definition at line 136 of file test_least_squares.py.
Referenced by scipy.signal._czt.CZT.__call__(), scipy.stats._morestats._ABW.__init__(), scipy.stats._morestats._ABW._recalc(), scipy.stats._kde.gaussian_kde.integrate_kde(), scipy.stats._kde.gaussian_kde.marginal(), scipy.stats._binomtest.BinomTestResult.proportion_ci(), and scipy.stats._kde.gaussian_kde.resample().
p0
scipy.optimize.tests.test_least_squares.ExponentialFittingProblem.p0 = np.zeros(2)
Definition at line 138 of file test_least_squares.py.
p_opt
scipy.optimize.tests.test_least_squares.ExponentialFittingProblem.p_opt = np.array([a, b])
Definition at line 147 of file test_least_squares.py.
x
scipy.optimize.tests.test_least_squares.ExponentialFittingProblem.x = np.linspace(x_range[0], x_range[1], n_points)
Definition at line 139 of file test_least_squares.py.
Referenced by matplotlib.widgets.ToolHandles.closest(), and scipy.spatial.tests.test_kdtree._Test_sorted_query_ball_point.test_return_sorted_None().
y
scipy.optimize.tests.test_least_squares.ExponentialFittingProblem.y = a + np.exp(b * self.x)
Definition at line 141 of file test_least_squares.py.
Referenced by matplotlib.widgets.ToolHandles.closest().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/optimize/tests/test_least_squares.py