Code Cloning Analysis: sklearn.utils._param_validation Namespace Reference
sklearn.utils._param_validation Namespace Reference
Classes
class _ArrayLikes
class _Booleans
class _Callables
class _Constraint
class _CVObjects
class _InstancesOf
class _IterablesNotString
class _NanConstraint
class _NoneConstraint
class _PandasNAConstraint
class _RandomStates
class _SparseMatrices
class _VerboseHelper
class HasMethods
class Hidden
class Interval
class InvalidParameterError
class MissingValues
class Options
class RealNotInt
class StrOptions
Functions
validate_parameter_constraints (parameter_constraints, params, caller_name)
make_constraint (constraint)
validate_params (parameter_constraints, *, prefer_skip_nested_validation)
_type_name (t)
generate_invalid_param_val (constraint)
generate_valid_param (constraint)
Function Documentation
_type_name()
sklearn.utils._param_validation._type_name (t) protected
Convert type into human readable string.
Definition at line 248 of file _param_validation.py.
generate_invalid_param_val()
sklearn.utils._param_validation.generate_invalid_param_val (constraint)
Return a value that does not satisfy the constraint.
Raises a NotImplementedError if there exists no invalid value for this constraint.
This is only useful for testing purpose.
Parameters
----------
constraint : _Constraint instance
    The constraint to generate a value for.
Returns
-------
val : object
    A value that does not satisfy the constraint.
Definition at line 766 of file _param_validation.py.
generate_valid_param()
sklearn.utils._param_validation.generate_valid_param (constraint)
Return a value that does satisfy a constraint.
This is only useful for testing purpose.
Parameters
----------
constraint : Constraint instance
    The constraint to generate a value for.
Returns
-------
val : object
    A value that does satisfy the constraint.
Definition at line 828 of file _param_validation.py.
make_constraint()
sklearn.utils._param_validation.make_constraint (constraint)
Convert the constraint into the appropriate Constraint object.
Parameters
----------
constraint : object
    The constraint to convert.
Returns
-------
constraint : instance of _Constraint
    The converted constraint.
Definition at line 104 of file _param_validation.py.
References make_constraint().
Referenced by make_constraint().
validate_parameter_constraints()
sklearn.utils._param_validation.validate_parameter_constraints (parameter_constraints, params, caller_name)
Validate types and values of given parameters.
Parameters
----------
parameter_constraints : dict or {"no_validation"}
    If "no_validation", validation is skipped for this parameter.
    If a dict, it must be a dictionary `param_name: list of constraints`.
    A parameter is valid if it satisfies one of the constraints from the list.
    Constraints can be:
    - an Interval object, representing a continuous or discrete range of numbers
    - the string "array-like"
    - the string "sparse matrix"
    - the string "random_state"
    - callable
    - None, meaning that None is a valid value for the parameter
    - any type, meaning that any instance of this type is valid
    - an Options object, representing a set of elements of a given type
    - a StrOptions object, representing a set of strings
    - the string "boolean"
    - the string "verbose"
    - the string "cv_object"
    - the string "nan"
    - a MissingValues object representing markers for missing values
    - a HasMethods object, representing method(s) an object must have
    - a Hidden object, representing a constraint not meant to be exposed to the user
params : dict
    A dictionary `param_name: param_value`. The parameters to validate against the
    constraints.
caller_name : str
    The name of the estimator or function or method that called this function.
Definition at line 28 of file _param_validation.py.
Referenced by validate_params().
validate_params()
sklearn.utils._param_validation.validate_params (parameter_constraints, * , prefer_skip_nested_validation)
Decorator to validate types and values of functions and methods.
Parameters
----------
parameter_constraints : dict
    A dictionary `param_name: list of constraints`. See the docstring of
    `validate_parameter_constraints` for a description of the accepted constraints.
    Note that the *args and **kwargs parameters are not validated and must not be
    present in the parameter_constraints dictionary.
prefer_skip_nested_validation : bool
    If True, the validation of parameters of inner estimators or functions
    called by the decorated function will be skipped.
    This is useful to avoid validating many times the parameters passed by the
    user from the public facing API. It's also useful to avoid validating
    parameters that we pass internally to inner functions that are guaranteed to
    be valid by the test suite.
    It should be set to True for most functions, except for those that receive
    non-validated objects as parameters or that are just wrappers around classes
    because they only perform a partial validation.
Returns
-------
decorated_function : function or method
    The decorated function.
Definition at line 150 of file _param_validation.py.
References validate_parameter_constraints().