Code Cloning Analysis: PIL.ImageDraw Namespace Reference
PIL.ImageDraw Namespace Reference
Classes
class ImageDraw
Functions
ImageDraw Draw (Image.Image im, str|None mode=None)
tuple[ImageDraw2.Draw|None, ModuleType] getdraw (Image.Image|None im=None, list[str]|None hints=None)
None floodfill (Image.Image image, tuple[int, int] xy, float|tuple[int,...] value, float|tuple[int,...]|None border=None, float thresh=0)
list[tuple[float, float]] _compute_regular_polygon_vertices (Sequence[Sequence[float]|float] bounding_circle, int n_sides, float rotation)
float _color_diff (float|tuple[int,...] color1, float|tuple[int,...] color2)
Variables
Callable Outline = Image.core.outline
bool TYPE_CHECKING = False
_Ink = Union[float, tuple[int, ...], str]
Function Documentation
_color_diff()
float PIL.ImageDraw._color_diff (float | tuple[int, ...] color1, float | tuple[int, ...] color2) protected
Uses 1-norm distance to calculate difference between two values.
Definition at line 1223 of file ImageDraw.py.
Referenced by floodfill().
_compute_regular_polygon_vertices()
list[tuple[float, float]] PIL.ImageDraw._compute_regular_polygon_vertices (Sequence[Sequence[float] | float] bounding_circle, int n_sides, float rotation) protected
Generate a list of vertices for a 2D regular polygon.
:param bounding_circle: The bounding circle is a sequence defined
    by a point and radius. The polygon is inscribed in this circle.
    (e.g. ``bounding_circle=(x, y, r)`` or ``((x, y), r)``)
:param n_sides: Number of sides
    (e.g. ``n_sides=3`` for a triangle, ``6`` for a hexagon)
:param rotation: Apply an arbitrary rotation to the polygon
    (e.g. ``rotation=90``, applies a 90 degree rotation)
:return: List of regular polygon vertices
    (e.g. ``[(25, 50), (50, 50), (50, 25), (25, 25)]``)
How are the vertices computed?
1. Compute the following variables
    - theta: Angle between the apothem & the nearest polygon vertex
    - side_length: Length of each polygon edge
    - centroid: Center of bounding circle (1st, 2nd elements of bounding_circle)
    - polygon_radius: Polygon radius (last element of bounding_circle)
    - angles: Location of each polygon vertex in polar grid
        (e.g. A square with 0 degree rotation => [225.0, 315.0, 45.0, 135.0])
2. For each angle in angles, get the polygon vertex at that angle
    The vertex is computed using the equation below.
        X= xcos(φ) + ysin(φ)
        Y= −xsin(φ) + ycos(φ)
    Note:
        φ = angle in degrees
        x = 0
        y = polygon_radius
    The formula above assumes rotation around the origin.
    In our case, we are rotating around the centroid.
    To account for this, we use the formula below
        X = xcos(φ) + ysin(φ) + centroid_x
        Y = −xsin(φ) + ycos(φ) + centroid_y
Definition at line 1093 of file ImageDraw.py.
Referenced by PIL.ImageDraw.ImageDraw.regular_polygon().
Draw()
ImageDraw PIL.ImageDraw.Draw (Image.Image im, str | None mode = None)
A simple 2D drawing interface for PIL images.
:param im: The image to draw in.
:param mode: Optional mode to use for color values.  For RGB
   images, this argument can be RGB or RGBA (to blend the
   drawing into the image).  For all other modes, this argument
   must be the same as the image mode.  If omitted, the mode
   defaults to the mode of the image.
Definition at line 995 of file ImageDraw.py.
Referenced by PIL.ImageDraw.ImageDraw.polygon().
floodfill()
None PIL.ImageDraw.floodfill (Image.Image image, tuple[int, int] xy, float | tuple[int, ...] value, float | tuple[int, ...] | None border = None, float thresh = 0)
.. warning:: This method is experimental.
Fills a bounded region with a given color.
:param image: Target image.
:param xy: Seed position (a 2-item coordinate tuple). See
    :ref:`coordinate-system`.
:param value: Fill color.
:param border: Optional border value.  If given, the region consists of
    pixels with a color different from the border color.  If not given,
    the region consists of pixels having the same color as the seed
    pixel.
:param thresh: Optional threshold value which specifies a maximum
    tolerable difference of a pixel value from the 'background' in
    order for it to be replaced. Useful for filling regions of
    non-homogeneous, but similar, colors.
Definition at line 1028 of file ImageDraw.py.
References _color_diff().
getdraw()
tuple[ImageDraw2.Draw | None, ModuleType] PIL.ImageDraw.getdraw (Image.Image | None im = None, list[str] | None hints = None)
:param im: The image to draw in.
:param hints: An optional list of hints. Deprecated.
:returns: A (drawing context, drawing resource factory) tuple.
Definition at line 1012 of file ImageDraw.py.
Variable Documentation
_Ink
PIL.ImageDraw._Ink = Union[float, tuple[int, ...], str] protected
Definition at line 51 of file ImageDraw.py.
Outline
Callable PIL.ImageDraw.Outline = Image.core.outline
Definition at line 45 of file ImageDraw.py.
TYPE_CHECKING
bool PIL.ImageDraw.TYPE_CHECKING = False
Definition at line 47 of file ImageDraw.py.