Code Cloning Analysis: sklearn.utils._testing.MinimalRegressor Class Reference
sklearn.utils._testing.MinimalRegressor Class Reference
Public Member Functions
__init__ (self, param=None)
get_params (self, deep=True)
set_params (self, **params)
fit (self, X, y)
predict (self, X)
score (self, X, y)
__sklearn_tags__ (self)
Public Attributes
param = param
bool is_fitted_ = True
Protected Attributes
_mean = np.mean(y)
Detailed Description
Minimal regressor implementation without inheriting from BaseEstimator.
This estimator should be tested with:
* `check_estimator` in `test_estimator_checks.py`;
* within a `Pipeline` in `test_pipeline.py`;
* within a `SearchCV` in `test_search.py`.
Definition at line 1217 of file _testing.py.
Constructor & Destructor Documentation
__init__()
sklearn.utils._testing.MinimalRegressor.__init__ (self, param = None)
Definition at line 1227 of file _testing.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params().
Member Function Documentation
__sklearn_tags__()
sklearn.utils._testing.MinimalRegressor.__sklearn_tags__ (self)
Definition at line 1254 of file _testing.py.
fit()
sklearn.utils._testing.MinimalRegressor.fit (self, X, y)
Definition at line 1238 of file _testing.py.
Referenced by sklearn.cluster._kmeans._BaseKMeans.fit_predict(), sklearn.cluster._kmeans._BaseKMeans.fit_transform(), and sklearn.utils.tests.test_estimator_checks.SparseTransformer.fit_transform().
get_params()
sklearn.utils._testing.MinimalRegressor.get_params (self, deep = True)
Definition at line 1230 of file _testing.py.
predict()
sklearn.utils._testing.MinimalRegressor.predict (self, X)
Definition at line 1244 of file _testing.py.
score()
sklearn.utils._testing.MinimalRegressor.score (self, X, y)
Definition at line 1249 of file _testing.py.
set_params()
sklearn.utils._testing.MinimalRegressor.set_params (self, ** params)
Definition at line 1233 of file _testing.py.
Member Data Documentation
_mean
sklearn.utils._testing.MinimalRegressor._mean = np.mean(y) protected
Definition at line 1241 of file _testing.py.
Referenced by scipy.stats._multivariate.invwishart_gen.mean(), and scipy.stats._multivariate.wishart_gen.mean().
is_fitted_
bool sklearn.utils._testing.MinimalRegressor.is_fitted_ = True
Definition at line 1240 of file _testing.py.
param
sklearn.utils._testing.MinimalRegressor.param = param
Definition at line 1228 of file _testing.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/sklearn/utils/_testing.py