Code Cloning Analysis: numpy.lib.index_tricks.IndexExpression Class Reference
numpy.lib.index_tricks.IndexExpression Class Reference
Public Member Functions
__init__ (self, maketuple)
__getitem__ (self, item)
Public Attributes
maketuple = maketuple
Detailed Description
A nicer way to build up index tuples for arrays.
.. note::
   Use one of the two predefined instances `index_exp` or `s_`
   rather than directly using `IndexExpression`.
For any index combination, including slicing and axis insertion,
``a[indices]`` is the same as ``a[np.index_exp[indices]]`` for any
array `a`. However, ``np.index_exp[indices]`` can be used anywhere
in Python code and returns a tuple of slice objects that can be
used in the construction of complex index expressions.
Parameters
----------
maketuple : bool
    If True, always returns a tuple.
See Also
--------
index_exp : Predefined instance that always returns a tuple:
   `index_exp = IndexExpression(maketuple=True)`.
s_ : Predefined instance without tuple conversion:
   `s_ = IndexExpression(maketuple=False)`.
Notes
-----
You can do all this with `slice()` plus a few special objects,
but there's a lot to remember and this version is simpler because
it uses the standard array indexing syntax.
Examples
--------
>>> np.s_[2::2]
slice(2, None, 2)
>>> np.index_exp[2::2]
(slice(2, None, 2),)
>>> np.array([0, 1, 2, 3, 4])[np.s_[2::2]]
array([2, 4])
Definition at line 717 of file index_tricks.py.
Constructor & Destructor Documentation
__init__()
numpy.lib.index_tricks.IndexExpression.__init__ (self, maketuple)
Definition at line 761 of file index_tricks.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__getitem__()
numpy.lib.index_tricks.IndexExpression.__getitem__ (self, item)
Definition at line 764 of file index_tricks.py.
Member Data Documentation
maketuple
numpy.lib.index_tricks.IndexExpression.maketuple = maketuple
Definition at line 762 of file index_tricks.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/lib/index_tricks.py