Code Cloning Analysis: scipy.signal.tests.test_fir_filter_design.TestFirWinMore Class Reference
scipy.signal.tests.test_fir_filter_design.TestFirWinMore Class Reference
Public Member Functions
test_lowpass (self)
test_highpass (self)
test_bandpass (self)
test_bandstop_multi (self)
test_fs_nyq (self)
test_bad_cutoff (self)
test_even_highpass_raises_value_error (self)
test_bad_pass_zero (self)
test_nyq_deprecation (self)
Detailed Description
Different author, different style, different tests...
Definition at line 127 of file test_fir_filter_design.py.
Member Function Documentation
test_bad_cutoff()
scipy.signal.tests.test_fir_filter_design.TestFirWinMore.test_bad_cutoff (self)
Test that invalid cutoff argument raises ValueError.
Definition at line 235 of file test_fir_filter_design.py.
test_bad_pass_zero()
scipy.signal.tests.test_fir_filter_design.TestFirWinMore.test_bad_pass_zero (self)
Test degenerate pass_zero cases.
Definition at line 264 of file test_fir_filter_design.py.
References scipy.signal._fir_filter_design.firwin().
test_bandpass()
scipy.signal.tests.test_fir_filter_design.TestFirWinMore.test_bandpass (self)
Definition at line 170 of file test_fir_filter_design.py.
test_bandstop_multi()
scipy.signal.tests.test_fir_filter_design.TestFirWinMore.test_bandstop_multi (self)
Definition at line 189 of file test_fir_filter_design.py.
test_even_highpass_raises_value_error()
scipy.signal.tests.test_fir_filter_design.TestFirWinMore.test_even_highpass_raises_value_error (self)
Test that attempt to create a highpass filter with an even number
of taps raises a ValueError exception.
Definition at line 258 of file test_fir_filter_design.py.
test_fs_nyq()
scipy.signal.tests.test_fir_filter_design.TestFirWinMore.test_fs_nyq (self)
Test the fs and nyq keywords.
Definition at line 211 of file test_fir_filter_design.py.
References scipy.signal._fir_filter_design.firwin(), scipy.signal._filter_design.freqz(), and scipy.signal._fir_filter_design.kaiserord().
test_highpass()
scipy.signal.tests.test_fir_filter_design.TestFirWinMore.test_highpass (self)
Definition at line 148 of file test_fir_filter_design.py.
test_lowpass()
scipy.signal.tests.test_fir_filter_design.TestFirWinMore.test_lowpass (self)
Definition at line 130 of file test_fir_filter_design.py.
test_nyq_deprecation()
scipy.signal.tests.test_fir_filter_design.TestFirWinMore.test_nyq_deprecation (self)
Definition at line 277 of file test_fir_filter_design.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/signal/tests/test_fir_filter_design.py