Code Cloning Analysis: fontTools.varLib.models Namespace Reference
fontTools.varLib.models Namespace Reference
Classes
class VariationModel
Functions
nonNone (lst)
allNone (lst)
allEqualTo (ref, lst, mapper=None)
allEqual (lst, mapper=None)
subList (truth, lst)
normalizeValue (v, triple, extrapolate=False)
normalizeLocation (location, axes, extrapolate=False, *, validate=False)
supportScalar (location, support, ot=True, extrapolate=False, axisRanges=None)
piecewiseLinearMap (v, mapping)
main (args=None)
Variables
list __all__
Detailed Description
Variation fonts interpolation models.
Function Documentation
allEqual()
fontTools.varLib.models.allEqual (lst, mapper = None)
Definition at line 31 of file models.py.
allEqualTo()
fontTools.varLib.models.allEqualTo (ref, lst, mapper = None)
Definition at line 23 of file models.py.
allNone()
fontTools.varLib.models.allNone (lst)
Definition at line 19 of file models.py.
main()
fontTools.varLib.models.main (args = None)
Normalize locations on a given designspace
Definition at line 580 of file models.py.
nonNone()
fontTools.varLib.models.nonNone (lst)
Definition at line 15 of file models.py.
normalizeLocation()
fontTools.varLib.models.normalizeLocation (location, axes, extrapolate = False, * , validate = False)
Normalizes location based on axis min/default/max values from axes.
>>> axes = {"wght": (100, 400, 900)}
>>> normalizeLocation({"wght": 400}, axes)
{'wght': 0.0}
>>> normalizeLocation({"wght": 100}, axes)
{'wght': -1.0}
>>> normalizeLocation({"wght": 900}, axes)
{'wght': 1.0}
>>> normalizeLocation({"wght": 650}, axes)
{'wght': 0.5}
>>> normalizeLocation({"wght": 1000}, axes)
{'wght': 1.0}
>>> normalizeLocation({"wght": 0}, axes)
{'wght': -1.0}
>>> axes = {"wght": (0, 0, 1000)}
>>> normalizeLocation({"wght": 0}, axes)
{'wght': 0.0}
>>> normalizeLocation({"wght": -1}, axes)
{'wght': 0.0}
>>> normalizeLocation({"wght": 1000}, axes)
{'wght': 1.0}
>>> normalizeLocation({"wght": 500}, axes)
{'wght': 0.5}
>>> normalizeLocation({"wght": 1001}, axes)
{'wght': 1.0}
>>> axes = {"wght": (0, 1000, 1000)}
>>> normalizeLocation({"wght": 0}, axes)
{'wght': -1.0}
>>> normalizeLocation({"wght": -1}, axes)
{'wght': -1.0}
>>> normalizeLocation({"wght": 500}, axes)
{'wght': -0.5}
>>> normalizeLocation({"wght": 1000}, axes)
{'wght': 0.0}
>>> normalizeLocation({"wght": 1001}, axes)
{'wght': 0.0}
Definition at line 78 of file models.py.
References normalizeValue().
normalizeValue()
fontTools.varLib.models.normalizeValue (v, triple, extrapolate = False)
Normalizes value based on a min/default/max triple.
>>> normalizeValue(400, (100, 400, 900))
0.0
>>> normalizeValue(100, (100, 400, 900))
-1.0
>>> normalizeValue(650, (100, 400, 900))
0.5
Definition at line 47 of file models.py.
Referenced by normalizeLocation().
piecewiseLinearMap()
fontTools.varLib.models.piecewiseLinearMap (v, mapping)
Definition at line 560 of file models.py.
subList()
fontTools.varLib.models.subList (truth, lst)
Definition at line 42 of file models.py.
supportScalar()
fontTools.varLib.models.supportScalar (location, support, ot = True, extrapolate = False, axisRanges = None)
Returns the scalar multiplier at location, for a master
with support.  If ot is True, then a peak value of zero
for support of an axis means "axis does not participate".  That
is how OpenType Variation Font technology works.
If extrapolate is True, axisRanges must be a dict that maps axis
names to (axisMin, axisMax) tuples.
  >>> supportScalar({}, {})
  1.0
  >>> supportScalar({'wght':.2}, {})
  1.0
  >>> supportScalar({'wght':.2}, {'wght':(0,2,3)})
  0.1
  >>> supportScalar({'wght':2.5}, {'wght':(0,2,4)})
  0.75
  >>> supportScalar({'wght':2.5, 'wdth':0}, {'wght':(0,2,4), 'wdth':(-1,0,+1)})
  0.75
  >>> supportScalar({'wght':2.5, 'wdth':.5}, {'wght':(0,2,4), 'wdth':(-1,0,+1)}, ot=False)
  0.375
  >>> supportScalar({'wght':2.5, 'wdth':0}, {'wght':(0,2,4), 'wdth':(-1,0,+1)})
  0.75
  >>> supportScalar({'wght':2.5, 'wdth':.5}, {'wght':(0,2,4), 'wdth':(-1,0,+1)})
  0.75
  >>> supportScalar({'wght':3}, {'wght':(0,1,2)}, extrapolate=True, axisRanges={'wght':(0, 2)})
  -1.0
  >>> supportScalar({'wght':-1}, {'wght':(0,1,2)}, extrapolate=True, axisRanges={'wght':(0, 2)})
  -1.0
  >>> supportScalar({'wght':3}, {'wght':(0,2,2)}, extrapolate=True, axisRanges={'wght':(0, 2)})
  1.5
  >>> supportScalar({'wght':-1}, {'wght':(0,2,2)}, extrapolate=True, axisRanges={'wght':(0, 2)})
  -0.5
Definition at line 128 of file models.py.
Referenced by fontTools.varLib.models.VariationModel.getScalars(), and fontTools.varLib.models.VariationModel.getSubModel().
Variable Documentation
__all__
list fontTools.varLib.models.__all__ private
Initial value:
=  [
    "normalizeValue",
    "normalizeLocation",
    "supportScalar",
    "piecewiseLinearMap",
    "VariationModel",
]
Definition at line 3 of file models.py.