Code Cloning Analysis: sklearn.model_selection._split.BaseCrossValidator Class Reference
sklearn.model_selection._split.BaseCrossValidator Class Reference
Public Member Functions
split (self, X, y=None, groups=None)
get_n_splits (self, X=None, y=None, groups=None)
__repr__ (self)
Protected Member Functions
_iter_test_masks (self, X=None, y=None, groups=None)
_iter_test_indices (self, X=None, y=None, groups=None)
Static Private Attributes
dict __metadata_request__split = {"groups": metadata_routing.UNUSED}
Detailed Description
Base class for all cross-validators.
Implementations must define `_iter_test_masks` or `_iter_test_indices`.
Definition at line 104 of file _split.py.
Member Function Documentation
__repr__()
sklearn.model_selection._split.BaseCrossValidator.__repr__ (self)
Definition at line 167 of file _split.py.
_iter_test_indices()
sklearn.model_selection._split.BaseCrossValidator._iter_test_indices (self, X = None, y = None, groups = None) protected
Generates integer indices corresponding to test sets.
Reimplemented in sklearn.model_selection._split.GroupKFold, sklearn.model_selection._split.KFold, sklearn.model_selection._split.LeaveOneOut, sklearn.model_selection._split.LeavePOut, sklearn.model_selection._split.StratifiedGroupKFold, and sklearn.tests.metadata_routing_common.ConsumingSplitter.
Definition at line 159 of file _split.py.
Referenced by _iter_test_masks().
_iter_test_masks()
sklearn.model_selection._split.BaseCrossValidator._iter_test_masks (self, X = None, y = None, groups = None) protected
Generates boolean masks corresponding to test sets.
By default, delegates to _iter_test_indices(X, y, groups)
Reimplemented in sklearn.model_selection._split.LeaveOneGroupOut, sklearn.model_selection._split.LeavePGroupsOut, sklearn.model_selection._split.PredefinedSplit, and sklearn.model_selection._split.StratifiedKFold.
Definition at line 149 of file _split.py.
References _iter_test_indices().
Referenced by sklearn.model_selection._split.PredefinedSplit._split(), and split().
get_n_splits()
sklearn.model_selection._split.BaseCrossValidator.get_n_splits (self, X = None, y = None, groups = None)
Returns the number of splitting iterations in the cross-validator.
Reimplemented in sklearn.model_selection._split._BaseKFold, sklearn.model_selection._split._CVIterableWrapper, sklearn.model_selection._split.LeaveOneGroupOut, sklearn.model_selection._split.LeaveOneOut, sklearn.model_selection._split.LeavePGroupsOut, sklearn.model_selection._split.LeavePOut, sklearn.model_selection._split.PredefinedSplit, and sklearn.tests.metadata_routing_common.ConsumingSplitter.
Definition at line 164 of file _split.py.
split()
sklearn.model_selection._split.BaseCrossValidator.split (self, X, y = None, groups = None)
Generate indices to split data into training and test set.
Parameters
----------
X : array-like of shape (n_samples, n_features)
    Training data, where `n_samples` is the number of samples
    and `n_features` is the number of features.
y : array-like of shape (n_samples,)
    The target variable for supervised learning problems.
groups : array-like of shape (n_samples,), default=None
    Group labels for the samples used while splitting the dataset into
    train/test set.
Yields
------
train : ndarray
    The training set indices for that split.
test : ndarray
    The testing set indices for that split.
Reimplemented in sklearn.model_selection._split._BaseKFold, sklearn.model_selection._split._CVIterableWrapper, sklearn.model_selection._split.GroupKFold, sklearn.model_selection._split.LeaveOneGroupOut, sklearn.model_selection._split.LeavePGroupsOut, sklearn.model_selection._split.PredefinedSplit, sklearn.model_selection._split.StratifiedKFold, sklearn.model_selection._split.TimeSeriesSplit, and sklearn.tests.metadata_routing_common.ConsumingSplitter.
Definition at line 116 of file _split.py.
References _iter_test_masks().
Member Data Documentation
__metadata_request__split
dict sklearn.model_selection._split.BaseCrossValidator.__metadata_request__split = {"groups": metadata_routing.UNUSED} static private
Definition at line 114 of file _split.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/sklearn/model_selection/_split.py