Code Cloning Analysis: pandas.tests.extension.json.test_json.TestJSONArray Class Reference
pandas.tests.extension.json.test_json.TestJSONArray Class Reference
Public Member Functions
test_contains (self, data)
test_from_dtype (self, data)
test_series_constructor_no_data_with_index (self, dtype, na_value)
test_series_constructor_scalar_na_with_index (self, dtype, na_value)
test_series_constructor_scalar_with_index (self, data, dtype)
test_stack (self)
test_unstack (self, data, index)
test_fillna_series (self)
test_fillna_frame (self)
test_ffill_limit_area (self, data_missing, limit_area, input_ilocs, expected_ilocs)
test_value_counts (self, all_data, dropna)
test_value_counts_with_normalize (self, data)
test_sort_values_frame (self)
test_sort_values (self, data_for_sorting, ascending, sort_by_key)
test_sort_values_missing (self, data_missing_for_sorting, ascending, sort_by_key)
test_combine_le (self, data_repeated)
test_combine_first (self, data)
test_where_series (self, data, na_value)
test_searchsorted (self, data_for_sorting)
test_equals (self, data, na_value, as_series)
test_fillna_copy_frame (self, data_missing)
test_equals_same_data_different_object (self, data, using_copy_on_write, request)
test_astype_str (self)
test_groupby_extension_transform (self)
test_groupby_extension_apply (self)
test_groupby_extension_agg (self)
test_groupby_extension_no_sort (self)
test_arith_frame_with_scalar (self, data, all_arithmetic_operators, request)
test_compare_array (self, data, comparison_op, request)
test_setitem_loc_scalar_mixed (self, data)
test_setitem_loc_scalar_multiple_homogoneous (self, data)
test_setitem_iloc_scalar_mixed (self, data)
test_setitem_iloc_scalar_multiple_homogoneous (self, data)
test_setitem_mask (self, data, mask, box_in_series, request)
test_setitem_mask_raises (self, data, box_in_series, request)
test_setitem_mask_boolean_array_with_na (self, data, box_in_series)
test_setitem_integer_array (self, data, idx, box_in_series, request)
test_setitem_integer_with_missing_raises (self, data, idx, box_in_series)
test_setitem_scalar_key_sequence_raise (self, data)
test_setitem_with_expansion_dataframe_column (self, data, full_indexer, request)
test_setitem_frame_2d_values (self, data)
test_setitem_mask_broadcast (self, data, setter)
test_setitem_slice (self, data, box_in_series)
test_setitem_loc_iloc_slice (self, data)
test_setitem_slice_mismatch_length_raises (self, data)
test_setitem_slice_array (self, data)
test_setitem_invalid (self, data, invalid_scalar)
test_setitem_2d_values (self, data)
test_EA_types (self, engine, data, request)
Public Member Functions inherited from pandas.tests.extension.base.accumulate.BaseAccumulateTests
check_accumulate (self, pd.Series ser, str op_name, bool skipna)
test_accumulate_series (self, data, all_numeric_accumulations, skipna)
Public Member Functions inherited from pandas.tests.extension.base.casting.BaseCastingTests
test_astype_object_series (self, all_data)
test_astype_object_frame (self, all_data)
test_tolist (self, data)
test_astype_string (self, data, nullable_string_dtype)
test_to_numpy (self, data)
test_astype_empty_dataframe (self, dtype)
test_astype_own_type (self, data, copy)
Public Member Functions inherited from pandas.tests.extension.base.constructors.BaseConstructorsTests
test_from_sequence_from_cls (self, data)
test_array_from_scalars (self, data)
test_series_constructor (self, data)
test_dataframe_constructor_from_dict (self, data, from_series)
test_dataframe_from_series (self, data)
test_series_given_mismatched_index_raises (self, data)
test_pandas_array (self, data)
test_pandas_array_dtype (self, data)
test_construct_empty_dataframe (self, dtype)
test_empty (self, dtype)
Public Member Functions inherited from pandas.tests.extension.base.dtype.BaseDtypeTests
test_name (self, dtype)
test_kind (self, dtype)
test_is_dtype_from_name (self, dtype)
test_is_dtype_unboxes_dtype (self, data, dtype)
test_is_dtype_from_self (self, dtype)
test_is_dtype_other_input (self, dtype)
test_is_not_string_type (self, dtype)
test_is_not_object_type (self, dtype)
test_eq_with_str (self, dtype)
test_eq_with_numpy_object (self, dtype)
test_eq_with_self (self, dtype)
test_array_type (self, data, dtype)
test_check_dtype (self, data)
test_hashable (self, dtype)
test_str (self, dtype)
test_eq (self, dtype)
test_construct_from_string_own_name (self, dtype)
test_construct_from_string_another_type_raises (self, dtype)
test_construct_from_string_wrong_type_raises (self, dtype)
test_get_common_dtype (self, dtype)
test_infer_dtype (self, data, data_missing, skipna)
Public Member Functions inherited from pandas.tests.extension.base.groupby.BaseGroupbyTests
test_grouping_grouper (self, data_for_grouping)
test_groupby_agg_extension (self, data_for_grouping)
test_groupby_apply_identity (self, data_for_grouping)
test_in_numeric_groupby (self, data_for_grouping)
Public Member Functions inherited from pandas.tests.extension.base.interface.BaseInterfaceTests
test_len (self, data)
test_size (self, data)
test_ndim (self, data)
test_can_hold_na_valid (self, data)
test_memory_usage (self, data)
test_array_interface (self, data)
test_array_interface_copy (self, data)
test_is_extension_array_dtype (self, data)
test_no_values_attribute (self, data)
test_is_numeric_honored (self, data)
test_isna_extension_array (self, data_missing)
test_copy (self, data)
test_view (self, data)
test_tolist (self, data)
Public Member Functions inherited from pandas.tests.extension.base.methods.BaseMethodsTests
test_hash_pandas_object (self, data)
test_value_counts_default_dropna (self, data)
test_count (self, data_missing)
test_series_count (self, data_missing)
test_apply_simple_series (self, data)
test_map (self, data_missing, na_action)
test_argsort (self, data_for_sorting)
test_argsort_missing_array (self, data_missing_for_sorting)
test_argsort_missing (self, data_missing_for_sorting)
test_argmin_argmax (self, data_for_sorting, data_missing_for_sorting, na_value)
test_argmin_argmax_empty_array (self, method, data)
test_argmin_argmax_all_na (self, method, data, na_value)
test_argreduce_series (self, data_missing_for_sorting, op_name, skipna, expected)
test_argmax_argmin_no_skipna_notimplemented (self, data_missing_for_sorting)
test_nargsort (self, data_missing_for_sorting, na_position, expected)
test_duplicated (self, data, keep)
test_unique (self, data, box, method)
test_factorize (self, data_for_grouping)
test_factorize_equivalence (self, data_for_grouping)
test_factorize_empty (self, data)
test_fillna_copy_series (self, data_missing)
test_fillna_length_mismatch (self, data_missing)
test_combine_add (self, data_repeated)
test_container_shift (self, data, frame, periods, indices)
test_shift_0_periods (self, data)
test_diff (self, data, periods)
test_shift_non_empty_array (self, data, periods, indices)
test_shift_empty_array (self, data, periods)
test_shift_zero_copies (self, data)
test_shift_fill_value (self, data)
test_not_hashable (self, data)
test_hash_pandas_object_works (self, data, as_frame)
test_repeat (self, data, repeats, as_series, use_numpy)
test_repeat_raises (self, data, repeats, kwargs, error, msg, use_numpy)
test_delete (self, data)
test_insert (self, data)
test_insert_invalid (self, data, invalid_scalar)
test_insert_invalid_loc (self, data)
Public Member Functions inherited from pandas.tests.extension.base.printing.BasePrintingTests
test_array_repr (self, data, size)
test_array_repr_unicode (self, data)
test_series_repr (self, data)
test_dataframe_repr (self, data)
test_dtype_name_in_info (self, data)
Public Member Functions inherited from pandas.tests.extension.base.reshaping.BaseReshapingTests
test_concat (self, data, in_frame)
test_concat_all_na_block (self, data_missing, in_frame)
test_concat_mixed_dtypes (self, data)
test_concat_columns (self, data, na_value)
test_concat_extension_arrays_copy_false (self, data, na_value)
test_concat_with_reindex (self, data)
test_align (self, data, na_value)
test_align_frame (self, data, na_value)
test_align_series_frame (self, data, na_value)
test_set_frame_expand_regular_with_extension (self, data)
test_set_frame_expand_extension_with_regular (self, data)
test_set_frame_overwrite_object (self, data)
test_merge (self, data, na_value)
test_merge_on_extension_array (self, data)
test_merge_on_extension_array_duplicates (self, data)
test_ravel (self, data)
test_transpose (self, data)
test_transpose_frame (self, data)
Additional Inherited Members
Protected Member Functions inherited from pandas.tests.extension.base.accumulate.BaseAccumulateTests
bool _supports_accumulation (self, pd.Series ser, str op_name)
Protected Member Functions inherited from pandas.tests.extension.base.methods.BaseMethodsTests
_test_searchsorted_bool_dtypes (self, data_for_sorting, as_series)
Static Protected Attributes inherited from pandas.tests.extension.base.methods.BaseMethodsTests
Dtype _combine_le_expected_dtype = NumpyEADtype("bool")
Detailed Description
Definition at line 81 of file test_json.py.
Member Function Documentation
test_arith_frame_with_scalar()
pandas.tests.extension.json.test_json.TestJSONArray.test_arith_frame_with_scalar (self, data, all_arithmetic_operators, request)
Definition at line 287 of file test_json.py.
test_astype_str()
pandas.tests.extension.json.test_json.TestJSONArray.test_astype_str (self)
This currently fails in NumPy on np.array(self, dtype=str) with
*** ValueError: setting an array element with a sequence
Reimplemented from pandas.tests.extension.base.casting.BaseCastingTests.
Definition at line 241 of file test_json.py.
References test_astype_str().
Referenced by test_astype_str().
test_combine_first()
pandas.tests.extension.json.test_json.TestJSONArray.test_combine_first (self, data)
Reimplemented from pandas.tests.extension.base.methods.BaseMethodsTests.
Definition at line 210 of file test_json.py.
test_combine_le()
pandas.tests.extension.json.test_json.TestJSONArray.test_combine_le (self, data_repeated)
Reimplemented from pandas.tests.extension.base.methods.BaseMethodsTests.
Definition at line 201 of file test_json.py.
test_compare_array()
pandas.tests.extension.json.test_json.TestJSONArray.test_compare_array (self, data, comparison_op, request)
Definition at line 293 of file test_json.py.
test_contains()
pandas.tests.extension.json.test_json.TestJSONArray.test_contains (self, data)
Reimplemented from pandas.tests.extension.base.interface.BaseInterfaceTests.
Definition at line 85 of file test_json.py.
test_EA_types()
pandas.tests.extension.json.test_json.TestJSONArray.test_EA_types (self, engine, data, request)
Definition at line 426 of file test_json.py.
test_equals()
pandas.tests.extension.json.test_json.TestJSONArray.test_equals (self, data, na_value, as_series)
Reimplemented from pandas.tests.extension.base.methods.BaseMethodsTests.
Definition at line 225 of file test_json.py.
test_equals_same_data_different_object()
pandas.tests.extension.json.test_json.TestJSONArray.test_equals_same_data_different_object (self, data, using_copy_on_write, request)
Reimplemented from pandas.tests.extension.base.methods.BaseMethodsTests.
Definition at line 232 of file test_json.py.
test_ffill_limit_area()
pandas.tests.extension.json.test_json.TestJSONArray.test_ffill_limit_area (self, data_missing, limit_area, input_ilocs, expected_ilocs)
Definition at line 165 of file test_json.py.
test_fillna_copy_frame()
pandas.tests.extension.json.test_json.TestJSONArray.test_fillna_copy_frame (self, data_missing)
Reimplemented from pandas.tests.extension.base.methods.BaseMethodsTests.
Definition at line 229 of file test_json.py.
test_fillna_frame()
pandas.tests.extension.json.test_json.TestJSONArray.test_fillna_frame (self)
We treat dictionaries as a mapping in fillna, not a scalar.
Definition at line 148 of file test_json.py.
References test_fillna_frame().
Referenced by test_fillna_frame().
test_fillna_series()
pandas.tests.extension.json.test_json.TestJSONArray.test_fillna_series (self)
We treat dictionaries as a mapping in fillna, not a scalar.
Definition at line 143 of file test_json.py.
References test_fillna_series().
Referenced by test_fillna_series().
test_from_dtype()
pandas.tests.extension.json.test_json.TestJSONArray.test_from_dtype (self, data)
Reimplemented from pandas.tests.extension.base.constructors.BaseConstructorsTests.
Definition at line 90 of file test_json.py.
test_groupby_extension_agg()
pandas.tests.extension.json.test_json.TestJSONArray.test_groupby_extension_agg (self)
This fails when we get to tm.assert_series_equal when left.index
contains dictionaries, which are not hashable.
Reimplemented from pandas.tests.extension.base.groupby.BaseGroupbyTests.
Definition at line 272 of file test_json.py.
References test_groupby_extension_agg().
Referenced by test_groupby_extension_agg().
test_groupby_extension_apply()
pandas.tests.extension.json.test_json.TestJSONArray.test_groupby_extension_apply (self)
This fails in Index._do_unique_check with
>   hash(val)
E   TypeError: unhashable type: 'UserDict' with
I suspect that once we support Index[ExtensionArray],
we'll be able to dispatch unique.
Reimplemented from pandas.tests.extension.base.groupby.BaseGroupbyTests.
Definition at line 259 of file test_json.py.
References test_groupby_extension_apply().
Referenced by test_groupby_extension_apply().
test_groupby_extension_no_sort()
pandas.tests.extension.json.test_json.TestJSONArray.test_groupby_extension_no_sort (self)
This fails when we get to tm.assert_series_equal when left.index
contains dictionaries, which are not hashable.
Reimplemented from pandas.tests.extension.base.groupby.BaseGroupbyTests.
Definition at line 280 of file test_json.py.
References test_groupby_extension_no_sort().
Referenced by test_groupby_extension_no_sort().
test_groupby_extension_transform()
pandas.tests.extension.json.test_json.TestJSONArray.test_groupby_extension_transform (self)
This currently fails in Series.name.setter, since the
name must be hashable, but the value is a dictionary.
I think this is what we want, i.e. `.name` should be the original
values, and not the values for factorization.
Reimplemented from pandas.tests.extension.base.groupby.BaseGroupbyTests.
Definition at line 249 of file test_json.py.
References test_groupby_extension_transform().
Referenced by test_groupby_extension_transform().
test_searchsorted()
pandas.tests.extension.json.test_json.TestJSONArray.test_searchsorted (self, data_for_sorting)
Reimplemented from pandas.tests.extension.base.methods.BaseMethodsTests.
Definition at line 221 of file test_json.py.
test_series_constructor_no_data_with_index()
pandas.tests.extension.json.test_json.TestJSONArray.test_series_constructor_no_data_with_index (self, dtype, na_value)
Reimplemented from pandas.tests.extension.base.constructors.BaseConstructorsTests.
Definition at line 95 of file test_json.py.
test_series_constructor_scalar_na_with_index()
pandas.tests.extension.json.test_json.TestJSONArray.test_series_constructor_scalar_na_with_index (self, dtype, na_value)
Reimplemented from pandas.tests.extension.base.constructors.BaseConstructorsTests.
Definition at line 106 of file test_json.py.
test_series_constructor_scalar_with_index()
pandas.tests.extension.json.test_json.TestJSONArray.test_series_constructor_scalar_with_index (self, data, dtype)
Reimplemented from pandas.tests.extension.base.constructors.BaseConstructorsTests.
Definition at line 117 of file test_json.py.
test_setitem_2d_values()
pandas.tests.extension.json.test_json.TestJSONArray.test_setitem_2d_values (self, data)
Definition at line 421 of file test_json.py.
test_setitem_frame_2d_values()
pandas.tests.extension.json.test_json.TestJSONArray.test_setitem_frame_2d_values (self, data)
Definition at line 388 of file test_json.py.
test_setitem_iloc_scalar_mixed()
pandas.tests.extension.json.test_json.TestJSONArray.test_setitem_iloc_scalar_mixed (self, data)
Definition at line 308 of file test_json.py.
test_setitem_iloc_scalar_multiple_homogoneous()
pandas.tests.extension.json.test_json.TestJSONArray.test_setitem_iloc_scalar_multiple_homogoneous (self, data)
Definition at line 312 of file test_json.py.
test_setitem_integer_array()
pandas.tests.extension.json.test_json.TestJSONArray.test_setitem_integer_array (self, data, idx, box_in_series, request)
Definition at line 353 of file test_json.py.
test_setitem_integer_with_missing_raises()
pandas.tests.extension.json.test_json.TestJSONArray.test_setitem_integer_with_missing_raises (self, data, idx, box_in_series)
Definition at line 374 of file test_json.py.
test_setitem_invalid()
pandas.tests.extension.json.test_json.TestJSONArray.test_setitem_invalid (self, data, invalid_scalar)
Definition at line 417 of file test_json.py.
test_setitem_loc_iloc_slice()
pandas.tests.extension.json.test_json.TestJSONArray.test_setitem_loc_iloc_slice (self, data)
Definition at line 405 of file test_json.py.
test_setitem_loc_scalar_mixed()
pandas.tests.extension.json.test_json.TestJSONArray.test_setitem_loc_scalar_mixed (self, data)
Definition at line 300 of file test_json.py.
test_setitem_loc_scalar_multiple_homogoneous()
pandas.tests.extension.json.test_json.TestJSONArray.test_setitem_loc_scalar_multiple_homogoneous (self, data)
Definition at line 304 of file test_json.py.
test_setitem_mask()
pandas.tests.extension.json.test_json.TestJSONArray.test_setitem_mask (self, data, mask, box_in_series, request)
Definition at line 324 of file test_json.py.
test_setitem_mask_boolean_array_with_na()
pandas.tests.extension.json.test_json.TestJSONArray.test_setitem_mask_boolean_array_with_na (self, data, box_in_series)
Definition at line 345 of file test_json.py.
test_setitem_mask_broadcast()
pandas.tests.extension.json.test_json.TestJSONArray.test_setitem_mask_broadcast (self, data, setter)
Definition at line 395 of file test_json.py.
test_setitem_mask_raises()
pandas.tests.extension.json.test_json.TestJSONArray.test_setitem_mask_raises (self, data, box_in_series, request)
Definition at line 335 of file test_json.py.
test_setitem_scalar_key_sequence_raise()
pandas.tests.extension.json.test_json.TestJSONArray.test_setitem_scalar_key_sequence_raise (self, data)
Definition at line 378 of file test_json.py.
test_setitem_slice()
pandas.tests.extension.json.test_json.TestJSONArray.test_setitem_slice (self, data, box_in_series)
Definition at line 401 of file test_json.py.
test_setitem_slice_array()
pandas.tests.extension.json.test_json.TestJSONArray.test_setitem_slice_array (self, data)
Definition at line 413 of file test_json.py.
test_setitem_slice_mismatch_length_raises()
pandas.tests.extension.json.test_json.TestJSONArray.test_setitem_slice_mismatch_length_raises (self, data)
Definition at line 409 of file test_json.py.
test_setitem_with_expansion_dataframe_column()
pandas.tests.extension.json.test_json.TestJSONArray.test_setitem_with_expansion_dataframe_column (self, data, full_indexer, request)
Definition at line 381 of file test_json.py.
test_sort_values()
pandas.tests.extension.json.test_json.TestJSONArray.test_sort_values (self, data_for_sorting, ascending, sort_by_key)
Reimplemented from pandas.tests.extension.base.methods.BaseMethodsTests.
Definition at line 189 of file test_json.py.
test_sort_values_frame()
pandas.tests.extension.json.test_json.TestJSONArray.test_sort_values_frame (self)
Reimplemented from pandas.tests.extension.base.methods.BaseMethodsTests.
Definition at line 184 of file test_json.py.
test_sort_values_missing()
pandas.tests.extension.json.test_json.TestJSONArray.test_sort_values_missing (self, data_missing_for_sorting, ascending, sort_by_key)
Reimplemented from pandas.tests.extension.base.methods.BaseMethodsTests.
Definition at line 193 of file test_json.py.
test_stack()
pandas.tests.extension.json.test_json.TestJSONArray.test_stack (self)
The test does .astype(object).stack(future_stack=True). If we happen to have
any missing values in `data`, then we'll end up with different
rows since we consider `{}` NA, but `.astype(object)` doesn't.
Reimplemented from pandas.tests.extension.base.reshaping.BaseReshapingTests.
Definition at line 128 of file test_json.py.
References test_stack().
Referenced by test_stack().
test_unstack()
pandas.tests.extension.json.test_json.TestJSONArray.test_unstack (self, data, index)
Reimplemented from pandas.tests.extension.base.reshaping.BaseReshapingTests.
Definition at line 137 of file test_json.py.
test_value_counts()
pandas.tests.extension.json.test_json.TestJSONArray.test_value_counts (self, all_data, dropna)
Reimplemented from pandas.tests.extension.base.methods.BaseMethodsTests.
Definition at line 176 of file test_json.py.
test_value_counts_with_normalize()
pandas.tests.extension.json.test_json.TestJSONArray.test_value_counts_with_normalize (self, data)
Reimplemented from pandas.tests.extension.base.methods.BaseMethodsTests.
Definition at line 180 of file test_json.py.
test_where_series()
pandas.tests.extension.json.test_json.TestJSONArray.test_where_series (self, data, na_value)
Reimplemented from pandas.tests.extension.base.methods.BaseMethodsTests.
Definition at line 214 of file test_json.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/tests/extension/json/test_json.py