Code Cloning Analysis: numpy.core.defchararray Namespace Reference
numpy.core.defchararray Namespace Reference
Classes
class chararray
Functions
_is_unicode (arr)
_to_bytes_or_str_array (result, output_dtype_like=None)
_clean_args (*args)
_get_num_chars (a)
_binary_op_dispatcher (x1, x2)
equal (x1, x2)
not_equal (x1, x2)
greater_equal (x1, x2)
less_equal (x1, x2)
greater (x1, x2)
less (x1, x2)
_unary_op_dispatcher (a)
str_len (a)
add (x1, x2)
_multiply_dispatcher (a, i)
multiply (a, i)
_mod_dispatcher (a, values)
mod (a, values)
capitalize (a)
_center_dispatcher (a, width, fillchar=None)
center (a, width, fillchar=' ')
_count_dispatcher (a, sub, start=None, end=None)
count (a, sub, start=0, end=None)
_code_dispatcher (a, encoding=None, errors=None)
decode (a, encoding=None, errors=None)
encode (a, encoding=None, errors=None)
_endswith_dispatcher (a, suffix, start=None, end=None)
endswith (a, suffix, start=0, end=None)
_expandtabs_dispatcher (a, tabsize=None)
expandtabs (a, tabsize=8)
find (a, sub, start=0, end=None)
index (a, sub, start=0, end=None)
isalnum (a)
isalpha (a)
isdigit (a)
islower (a)
isspace (a)
istitle (a)
isupper (a)
_join_dispatcher (sep, seq)
join (sep, seq)
_just_dispatcher (a, width, fillchar=None)
ljust (a, width, fillchar=' ')
lower (a)
_strip_dispatcher (a, chars=None)
lstrip (a, chars=None)
_partition_dispatcher (a, sep)
partition (a, sep)
_replace_dispatcher (a, old, new, count=None)
replace (a, old, new, count=None)
rfind (a, sub, start=0, end=None)
rindex (a, sub, start=0, end=None)
rjust (a, width, fillchar=' ')
rpartition (a, sep)
_split_dispatcher (a, sep=None, maxsplit=None)
rsplit (a, sep=None, maxsplit=None)
rstrip (a, chars=None)
split (a, sep=None, maxsplit=None)
_splitlines_dispatcher (a, keepends=None)
splitlines (a, keepends=None)
_startswith_dispatcher (a, prefix, start=None, end=None)
startswith (a, prefix, start=0, end=None)
strip (a, chars=None)
swapcase (a)
title (a)
_translate_dispatcher (a, table, deletechars=None)
translate (a, table, deletechars=None)
upper (a)
_zfill_dispatcher (a, width)
zfill (a, width)
isnumeric (a)
isdecimal (a)
array (obj, itemsize=None, copy=True, unicode=None, order=None)
asarray (obj, itemsize=None, unicode=None, order=None)
Variables
list __all__
int _globalvar = 0
array_function_dispatch
Detailed Description
This module contains a set of functions for vectorized string
operations and methods.
.. note::
   The `chararray` class exists for backwards compatibility with
   Numarray, it is not recommended for new development. Starting from numpy
   1.4, if one needs arrays of strings, it is recommended to use arrays of
   `dtype` `object_`, `bytes_` or `str_`, and use the free functions
   in the `numpy.char` module for fast vectorized string operations.
Some methods will only be available if the corresponding string method is
available in your version of Python.
The preferred alias for `defchararray` is `numpy.char`.
Function Documentation
_binary_op_dispatcher()
numpy.core.defchararray._binary_op_dispatcher (x1, x2) protected
Definition at line 100 of file defchararray.py.
_center_dispatcher()
numpy.core.defchararray._center_dispatcher (a, width, fillchar = None) protected
Definition at line 461 of file defchararray.py.
_clean_args()
numpy.core.defchararray._clean_args (* args) protected
Helper function for delegating arguments to Python string
functions.
Many of the Python string operations that have optional arguments
do not use 'None' to indicate a default value.  In these cases,
we need to remove all None arguments, and those following them.
Definition at line 73 of file defchararray.py.
Referenced by count(), decode(), encode(), endswith(), find(), index(), replace(), rfind(), rindex(), rsplit(), split(), splitlines(), startswith(), strip(), and translate().
_code_dispatcher()
numpy.core.defchararray._code_dispatcher (a, encoding = None, errors = None) protected
Definition at line 568 of file defchararray.py.
_count_dispatcher()
numpy.core.defchararray._count_dispatcher (a, sub, start = None, end = None) protected
Definition at line 518 of file defchararray.py.
_endswith_dispatcher()
numpy.core.defchararray._endswith_dispatcher (a, suffix, start = None, end = None) protected
Definition at line 654 of file defchararray.py.
_expandtabs_dispatcher()
numpy.core.defchararray._expandtabs_dispatcher (a, tabsize = None) protected
Definition at line 702 of file defchararray.py.
_get_num_chars()
numpy.core.defchararray._get_num_chars (a) protected
Helper function that returns the number of characters per field in
a string or unicode array.  This is to abstract out the fact that
for a unicode array this is itemsize / 4.
Definition at line 89 of file defchararray.py.
Referenced by _to_bytes_or_str_array(), add(), and multiply().
_is_unicode()
numpy.core.defchararray._is_unicode (arr) protected
Returns True if arr is a string or a string array with a dtype that
represents a unicode string, otherwise returns False.
Definition at line 49 of file defchararray.py.
Referenced by isdecimal(), and isnumeric().
_join_dispatcher()
numpy.core.defchararray._join_dispatcher (sep, seq) protected
Definition at line 1023 of file defchararray.py.
_just_dispatcher()
numpy.core.defchararray._just_dispatcher (a, width, fillchar = None) protected
Definition at line 1063 of file defchararray.py.
_mod_dispatcher()
numpy.core.defchararray._mod_dispatcher (a, values) protected
Definition at line 390 of file defchararray.py.
_multiply_dispatcher()
numpy.core.defchararray._multiply_dispatcher (a, i) protected
Definition at line 339 of file defchararray.py.
_partition_dispatcher()
numpy.core.defchararray._partition_dispatcher (a, sep) protected
Definition at line 1197 of file defchararray.py.
_replace_dispatcher()
numpy.core.defchararray._replace_dispatcher (a, old, new, count = None) protected
Definition at line 1237 of file defchararray.py.
_split_dispatcher()
numpy.core.defchararray._split_dispatcher (a, sep = None, maxsplit = None) protected
Definition at line 1417 of file defchararray.py.
_splitlines_dispatcher()
numpy.core.defchararray._splitlines_dispatcher (a, keepends = None) protected
Definition at line 1543 of file defchararray.py.
_startswith_dispatcher()
numpy.core.defchararray._startswith_dispatcher (a, prefix, start = None, end = None) protected
Definition at line 1577 of file defchararray.py.
_strip_dispatcher()
numpy.core.defchararray._strip_dispatcher (a, chars = None) protected
Definition at line 1138 of file defchararray.py.
_to_bytes_or_str_array()
numpy.core.defchararray._to_bytes_or_str_array (result, output_dtype_like = None) protected
Helper function to cast a result back into an array
with the appropriate dtype if an object array must be used
as an intermediary.
Definition at line 60 of file defchararray.py.
References _get_num_chars().
Referenced by decode(), encode(), expandtabs(), join(), mod(), partition(), replace(), and rpartition().
_translate_dispatcher()
numpy.core.defchararray._translate_dispatcher (a, table, deletechars = None) protected
Definition at line 1736 of file defchararray.py.
_unary_op_dispatcher()
numpy.core.defchararray._unary_op_dispatcher (a) protected
Definition at line 261 of file defchararray.py.
_zfill_dispatcher()
numpy.core.defchararray._zfill_dispatcher (a, width) protected
Definition at line 1812 of file defchararray.py.
add()
numpy.core.defchararray.add (x1, x2)
Return element-wise string concatenation for two arrays of str or unicode.
Arrays `x1` and `x2` must have the same shape.
Parameters
----------
x1 : array_like of str or unicode
    Input array.
x2 : array_like of str or unicode
    Input array.
Returns
-------
add : ndarray
    Output array of `bytes_` or `str_`, depending on input types
    of the same shape as `x1` and `x2`.
Definition at line 302 of file defchararray.py.
References _get_num_chars().
Referenced by numpy.core.defchararray.chararray.__add__(), and numpy.core.defchararray.chararray.__radd__().
array()
numpy.core.defchararray.array (obj, itemsize = None, copy = True, unicode = None, order = None)
Create a `chararray`.
.. note::
   This class is provided for numarray backward-compatibility.
   New code (not concerned with numarray compatibility) should use
   arrays of type `bytes_` or `str_` and use the free functions
   in :mod:`numpy.char <numpy.core.defchararray>` for fast
   vectorized string operations instead.
Versus a regular NumPy array of type `str` or `unicode`, this
class adds the following functionality:
  1) values automatically have whitespace removed from the end
     when indexed
  2) comparison operators automatically remove whitespace from the
     end when comparing values
  3) vectorized string operations are provided as methods
     (e.g. `str.endswith`) and infix operators (e.g. ``+, *, %``)
Parameters
----------
obj : array of str or unicode-like
itemsize : int, optional
    `itemsize` is the number of characters per scalar in the
    resulting array.  If `itemsize` is None, and `obj` is an
    object array or a Python list, the `itemsize` will be
    automatically determined.  If `itemsize` is provided and `obj`
    is of type str or unicode, then the `obj` string will be
    chunked into `itemsize` pieces.
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy
    will only be made if __array__ returns a copy, if obj is a
    nested sequence, or if a copy is needed to satisfy any of the other
    requirements (`itemsize`, unicode, `order`, etc.).
unicode : bool, optional
    When true, the resulting `chararray` can contain Unicode
    characters, when false only 8-bit characters.  If unicode is
    None and `obj` is one of the following:
      - a `chararray`,
      - an ndarray of type `str` or `unicode`
      - a Python str or unicode object,
    then the unicode setting of the output array will be
    automatically determined.
order : {'C', 'F', 'A'}, optional
    Specify the order of the array.  If order is 'C' (default), then the
    array will be in C-contiguous order (last-index varies the
    fastest).  If order is 'F', then the returned array
    will be in Fortran-contiguous order (first-index varies the
    fastest).  If order is 'A', then the returned array may
    be in any order (either C-, Fortran-contiguous, or even
    discontiguous).
Definition at line 2731 of file defchararray.py.
Referenced by asarray().
asarray()
numpy.core.defchararray.asarray (obj, itemsize = None, unicode = None, order = None)
Convert the input to a `chararray`, copying the data only if
necessary.
Versus a regular NumPy array of type `str` or `unicode`, this
class adds the following functionality:
  1) values automatically have whitespace removed from the end
     when indexed
  2) comparison operators automatically remove whitespace from the
     end when comparing values
  3) vectorized string operations are provided as methods
     (e.g. `str.endswith`) and infix operators (e.g. ``+``, ``*``,``%``)
Parameters
----------
obj : array of str or unicode-like
itemsize : int, optional
    `itemsize` is the number of characters per scalar in the
    resulting array.  If `itemsize` is None, and `obj` is an
    object array or a Python list, the `itemsize` will be
    automatically determined.  If `itemsize` is provided and `obj`
    is of type str or unicode, then the `obj` string will be
    chunked into `itemsize` pieces.
unicode : bool, optional
    When true, the resulting `chararray` can contain Unicode
    characters, when false only 8-bit characters.  If unicode is
    None and `obj` is one of the following:
      - a `chararray`,
      - an ndarray of type `str` or 'unicode`
      - a Python str or unicode object,
    then the unicode setting of the output array will be
    automatically determined.
order : {'C', 'F'}, optional
    Specify the order of the array.  If order is 'C' (default), then the
    array will be in C-contiguous order (last-index varies the
    fastest).  If order is 'F', then the returned array
    will be in Fortran-contiguous order (first-index varies the
    fastest).
Definition at line 2865 of file defchararray.py.
References array().
Referenced by numpy.core.defchararray.chararray.__add__(), numpy.core.defchararray.chararray.__mod__(), numpy.core.defchararray.chararray.__mul__(), numpy.core.defchararray.chararray.__radd__(), numpy.core.defchararray.chararray.__rmul__(), numpy.core.defchararray.chararray.capitalize(), numpy.core.defchararray.chararray.center(), numpy.core.defchararray.chararray.expandtabs(), numpy.core.defchararray.chararray.ljust(), numpy.core.defchararray.chararray.lower(), numpy.core.defchararray.chararray.lstrip(), numpy.core.defchararray.chararray.partition(), numpy.core.defchararray.chararray.replace(), numpy.core.defchararray.chararray.rjust(), numpy.core.defchararray.chararray.rpartition(), numpy.core.defchararray.chararray.rstrip(), numpy.core.defchararray.chararray.strip(), numpy.core.defchararray.chararray.swapcase(), numpy.core.defchararray.chararray.title(), numpy.core.defchararray.chararray.translate(), numpy.core.defchararray.chararray.upper(), and numpy.core.defchararray.chararray.zfill().
capitalize()
numpy.core.defchararray.capitalize (a)
Return a copy of `a` with only the first character of each element
capitalized.
Calls `str.capitalize` element-wise.
For 8-bit strings, this method is locale-dependent.
Parameters
----------
a : array_like of str or unicode
    Input array of strings to capitalize.
Returns
-------
out : ndarray
    Output array of str or unicode, depending on input
    types
See Also
--------
str.capitalize
Examples
--------
>>> c = np.array(['a1b2','1b2a','b2a1','2a1b'],'S4'); c
array(['a1b2', '1b2a', 'b2a1', '2a1b'],
    dtype='|S4')
>>> np.char.capitalize(c)
array(['A1b2', '1b2a', 'B2a1', '2a1b'],
    dtype='|S4')
Definition at line 423 of file defchararray.py.
center()
numpy.core.defchararray.center (a, width, fillchar = ' ')
Return a copy of `a` with its elements centered in a string of
length `width`.
Calls `str.center` element-wise.
Parameters
----------
a : array_like of str or unicode
width : int
    The length of the resulting strings
fillchar : str or unicode, optional
    The padding character to use (default is space).
Returns
-------
out : ndarray
    Output array of str or unicode, depending on input
    types
See Also
--------
str.center
Notes
-----
This function is intended to work with arrays of strings.  The
fill character is not applied to numeric types.
Examples
--------
>>> c = np.array(['a1b2','1b2a','b2a1','2a1b']); c
array(['a1b2', '1b2a', 'b2a1', '2a1b'], dtype='<U4')
>>> np.char.center(c, width=9)
array(['   a1b2  ', '   1b2a  ', '   b2a1  ', '   2a1b  '], dtype='<U9')
>>> np.char.center(c, width=9, fillchar='*')
array(['***a1b2**', '***1b2a**', '***b2a1**', '***2a1b**'], dtype='<U9')
>>> np.char.center(c, width=1)
array(['a', '1', 'b', '2'], dtype='<U1')
Definition at line 466 of file defchararray.py.
count()
numpy.core.defchararray.count (a, sub, start = 0, end = None)
Returns an array with the number of non-overlapping occurrences of
substring `sub` in the range [`start`, `end`].
Calls `str.count` element-wise.
Parameters
----------
a : array_like of str or unicode
sub : str or unicode
   The substring to search for.
start, end : int, optional
   Optional arguments `start` and `end` are interpreted as slice
   notation to specify the range in which to count.
Returns
-------
out : ndarray
    Output array of ints.
See Also
--------
str.count
Examples
--------
>>> c = np.array(['aAaAaA', '  aA  ', 'abBABba'])
>>> c
array(['aAaAaA', '  aA  ', 'abBABba'], dtype='<U7')
>>> np.char.count(c, 'A')
array([3, 1, 1])
>>> np.char.count(c, 'aA')
array([3, 1, 0])
>>> np.char.count(c, 'A', start=1, end=4)
array([2, 1, 1])
>>> np.char.count(c, 'A', start=1, end=3)
array([1, 0, 0])
Definition at line 523 of file defchararray.py.
References _clean_args().
decode()
numpy.core.defchararray.decode (a, encoding = None, errors = None)
Calls ``bytes.decode`` element-wise.
The set of available codecs comes from the Python standard library,
and may be extended at runtime.  For more information, see the
:mod:`codecs` module.
Parameters
----------
a : array_like of str or unicode
encoding : str, optional
   The name of an encoding
errors : str, optional
   Specifies how to handle encoding errors
Returns
-------
out : ndarray
See Also
--------
:py:meth:`bytes.decode`
Notes
-----
The type of the result will depend on the encoding specified.
Examples
--------
>>> c = np.array([b'\x81\xc1\x81\xc1\x81\xc1', b'@@\x81\xc1@@',
...               b'\x81\x82\xc2\xc1\xc2\x82\x81'])
>>> c
array([b'\x81\xc1\x81\xc1\x81\xc1', b'@@\x81\xc1@@',
...    b'\x81\x82\xc2\xc1\xc2\x82\x81'], dtype='|S7')
>>> np.char.decode(c, encoding='cp037')
array(['aAaAaA', '  aA  ', 'abBABba'], dtype='<U7')
Definition at line 573 of file defchararray.py.
References _clean_args(), and _to_bytes_or_str_array().
encode()
numpy.core.defchararray.encode (a, encoding = None, errors = None)
Calls `str.encode` element-wise.
The set of available codecs comes from the Python standard library,
and may be extended at runtime. For more information, see the codecs
module.
Parameters
----------
a : array_like of str or unicode
encoding : str, optional
   The name of an encoding
errors : str, optional
   Specifies how to handle encoding errors
Returns
-------
out : ndarray
See Also
--------
str.encode
Notes
-----
The type of the result will depend on the encoding specified.
Definition at line 619 of file defchararray.py.
References _clean_args(), and _to_bytes_or_str_array().
endswith()
numpy.core.defchararray.endswith (a, suffix, start = 0, end = None)
Returns a boolean array which is `True` where the string element
in `a` ends with `suffix`, otherwise `False`.
Calls `str.endswith` element-wise.
Parameters
----------
a : array_like of str or unicode
suffix : str
start, end : int, optional
    With optional `start`, test beginning at that position. With
    optional `end`, stop comparing at that position.
Returns
-------
out : ndarray
    Outputs an array of bools.
See Also
--------
str.endswith
Examples
--------
>>> s = np.array(['foo', 'bar'])
>>> s[0] = 'foo'
>>> s[1] = 'bar'
>>> s
array(['foo', 'bar'], dtype='<U3')
>>> np.char.endswith(s, 'ar')
array([False,  True])
>>> np.char.endswith(s, 'a', start=1, end=2)
array([False,  True])
Definition at line 659 of file defchararray.py.
References _clean_args().
equal()
numpy.core.defchararray.equal (x1, x2)
Return (x1 == x2) element-wise.
Unlike `numpy.equal`, this comparison is performed by first
stripping whitespace characters from the end of the string.  This
behavior is provided for backward-compatibility with numarray.
Parameters
----------
x1, x2 : array_like of str or unicode
    Input arrays of the same shape.
Returns
-------
out : ndarray
    Output array of bools.
See Also
--------
not_equal, greater_equal, less_equal, greater, less
Definition at line 105 of file defchararray.py.
Referenced by numpy.core.defchararray.chararray.__eq__().
expandtabs()
numpy.core.defchararray.expandtabs (a, tabsize = 8)
Return a copy of each string element where all tab characters are
replaced by one or more spaces.
Calls `str.expandtabs` element-wise.
Return a copy of each string element where all tab characters are
replaced by one or more spaces, depending on the current column
and the given `tabsize`. The column number is reset to zero after
each newline occurring in the string. This doesn't understand other
non-printing characters or escape sequences.
Parameters
----------
a : array_like of str or unicode
    Input array
tabsize : int, optional
    Replace tabs with `tabsize` number of spaces.  If not given defaults
    to 8 spaces.
Returns
-------
out : ndarray
    Output array of str or unicode, depending on input type
See Also
--------
str.expandtabs
Definition at line 707 of file defchararray.py.
References _to_bytes_or_str_array().
find()
numpy.core.defchararray.find (a, sub, start = 0, end = None)
For each element, return the lowest index in the string where
substring `sub` is found.
Calls `str.find` element-wise.
For each element, return the lowest index in the string where
substring `sub` is found, such that `sub` is contained in the
range [`start`, `end`].
Parameters
----------
a : array_like of str or unicode
sub : str or unicode
start, end : int, optional
    Optional arguments `start` and `end` are interpreted as in
    slice notation.
Returns
-------
out : ndarray or int
    Output array of ints.  Returns -1 if `sub` is not found.
See Also
--------
str.find
Examples
--------
>>> a = np.array(["NumPy is a Python library"])
>>> np.char.find(a, "Python", start=0, end=None)
array([11])
Definition at line 743 of file defchararray.py.
References _clean_args().
greater()
numpy.core.defchararray.greater (x1, x2)
Return (x1 > x2) element-wise.
Unlike `numpy.greater`, this comparison is performed by first
stripping whitespace characters from the end of the string.  This
behavior is provided for backward-compatibility with numarray.
Parameters
----------
x1, x2 : array_like of str or unicode
    Input arrays of the same shape.
Returns
-------
out : ndarray
    Output array of bools.
See Also
--------
equal, not_equal, greater_equal, less_equal, less
Definition at line 210 of file defchararray.py.
Referenced by numpy.core.defchararray.chararray.__gt__().
greater_equal()
numpy.core.defchararray.greater_equal (x1, x2)
Return (x1 >= x2) element-wise.
Unlike `numpy.greater_equal`, this comparison is performed by
first stripping whitespace characters from the end of the string.
This behavior is provided for backward-compatibility with
numarray.
Parameters
----------
x1, x2 : array_like of str or unicode
    Input arrays of the same shape.
Returns
-------
out : ndarray
    Output array of bools.
See Also
--------
equal, not_equal, less_equal, greater, less
Definition at line 157 of file defchararray.py.
Referenced by numpy.core.defchararray.chararray.__ge__().
index()
numpy.core.defchararray.index (a, sub, start = 0, end = None)
Like `find`, but raises `ValueError` when the substring is not found.
Calls `str.index` element-wise.
Parameters
----------
a : array_like of str or unicode
sub : str or unicode
start, end : int, optional
Returns
-------
out : ndarray
    Output array of ints.  Returns -1 if `sub` is not found.
See Also
--------
find, str.find
Examples
--------
>>> a = np.array(["Computer Science"])
>>> np.char.index(a, "Science", start=0, end=None)
array([9])
Definition at line 785 of file defchararray.py.
References _clean_args().
isalnum()
numpy.core.defchararray.isalnum (a)
Returns true for each element if all characters in the string are
alphanumeric and there is at least one character, false otherwise.
Calls `str.isalnum` element-wise.
For 8-bit strings, this method is locale-dependent.
Parameters
----------
a : array_like of str or unicode
Returns
-------
out : ndarray
    Output array of str or unicode, depending on input type
See Also
--------
str.isalnum
Definition at line 820 of file defchararray.py.
isalpha()
numpy.core.defchararray.isalpha (a)
Returns true for each element if all characters in the string are
alphabetic and there is at least one character, false otherwise.
Calls `str.isalpha` element-wise.
For 8-bit strings, this method is locale-dependent.
Parameters
----------
a : array_like of str or unicode
Returns
-------
out : ndarray
    Output array of bools
See Also
--------
str.isalpha
Definition at line 846 of file defchararray.py.
isdecimal()
numpy.core.defchararray.isdecimal (a)
For each element, return True if there are only decimal
characters in the element.
Calls `str.isdecimal` element-wise.
Decimal characters include digit characters, and all characters
that can be used to form decimal-radix numbers,
e.g. ``U+0660, ARABIC-INDIC DIGIT ZERO``.
Parameters
----------
a : array_like, unicode
    Input array.
Returns
-------
out : ndarray, bool
    Array of booleans identical in shape to `a`.
See Also
--------
str.isdecimal
Examples
--------
>>> np.char.isdecimal(['12345', '4.99', '123ABC', ''])
array([ True, False, False, False])
Definition at line 1885 of file defchararray.py.
References _is_unicode().
isdigit()
numpy.core.defchararray.isdigit (a)
Returns true for each element if all characters in the string are
digits and there is at least one character, false otherwise.
Calls `str.isdigit` element-wise.
For 8-bit strings, this method is locale-dependent.
Parameters
----------
a : array_like of str or unicode
Returns
-------
out : ndarray
    Output array of bools
See Also
--------
str.isdigit
Examples
--------
>>> a = np.array(['a', 'b', '0'])
>>> np.char.isdigit(a)
array([False, False,  True])
>>> a = np.array([['a', 'b', '0'], ['c', '1', '2']])
>>> np.char.isdigit(a)
array([[False, False,  True], [False,  True,  True]])
Definition at line 872 of file defchararray.py.
islower()
numpy.core.defchararray.islower (a)
Returns true for each element if all cased characters in the
string are lowercase and there is at least one cased character,
false otherwise.
Calls `str.islower` element-wise.
For 8-bit strings, this method is locale-dependent.
Parameters
----------
a : array_like of str or unicode
Returns
-------
out : ndarray
    Output array of bools
See Also
--------
str.islower
Definition at line 907 of file defchararray.py.
isnumeric()
numpy.core.defchararray.isnumeric (a)
For each element, return True if there are only numeric
characters in the element.
Calls `str.isnumeric` element-wise.
Numeric characters include digit characters, and all characters
that have the Unicode numeric value property, e.g. ``U+2155,
VULGAR FRACTION ONE FIFTH``.
Parameters
----------
a : array_like, unicode
    Input array.
Returns
-------
out : ndarray, bool
    Array of booleans of same shape as `a`.
See Also
--------
str.isnumeric
Examples
--------
>>> np.char.isnumeric(['123', '123abc', '9.0', '1/4', 'VIII'])
array([ True, False, False, False, False])
Definition at line 1848 of file defchararray.py.
References _is_unicode().
isspace()
numpy.core.defchararray.isspace (a)
Returns true for each element if there are only whitespace
characters in the string and there is at least one character,
false otherwise.
Calls `str.isspace` element-wise.
For 8-bit strings, this method is locale-dependent.
Parameters
----------
a : array_like of str or unicode
Returns
-------
out : ndarray
    Output array of bools
See Also
--------
str.isspace
Definition at line 934 of file defchararray.py.
istitle()
numpy.core.defchararray.istitle (a)
Returns true for each element if the element is a titlecased
string and there is at least one character, false otherwise.
Call `str.istitle` element-wise.
For 8-bit strings, this method is locale-dependent.
Parameters
----------
a : array_like of str or unicode
Returns
-------
out : ndarray
    Output array of bools
See Also
--------
str.istitle
Definition at line 961 of file defchararray.py.
isupper()
numpy.core.defchararray.isupper (a)
Return true for each element if all cased characters in the
string are uppercase and there is at least one character, false
otherwise.
Call `str.isupper` element-wise.
For 8-bit strings, this method is locale-dependent.
Parameters
----------
a : array_like of str or unicode
Returns
-------
out : ndarray
    Output array of bools
See Also
--------
str.isupper
Examples
--------
>>> str = "GHC"
>>> np.char.isupper(str)
array(True)
>>> a = np.array(["hello", "HELLO", "Hello"])
>>> np.char.isupper(a)
array([False,  True, False])
Definition at line 987 of file defchararray.py.
join()
numpy.core.defchararray.join (sep, seq)
Return a string which is the concatenation of the strings in the
sequence `seq`.
Calls `str.join` element-wise.
Parameters
----------
sep : array_like of str or unicode
seq : array_like of str or unicode
Returns
-------
out : ndarray
    Output array of str or unicode, depending on input types
See Also
--------
str.join
Examples
--------
>>> np.char.join('-', 'osd')
array('o-s-d', dtype='<U5')
>>> np.char.join(['-', '.'], ['ghc', 'osd'])
array(['g-h-c', 'o.s.d'], dtype='<U5')
Definition at line 1028 of file defchararray.py.
References _to_bytes_or_str_array().
less()
numpy.core.defchararray.less (x1, x2)
Return (x1 < x2) element-wise.
Unlike `numpy.greater`, this comparison is performed by first
stripping whitespace characters from the end of the string.  This
behavior is provided for backward-compatibility with numarray.
Parameters
----------
x1, x2 : array_like of str or unicode
    Input arrays of the same shape.
Returns
-------
out : ndarray
    Output array of bools.
See Also
--------
equal, not_equal, greater_equal, less_equal, greater
Definition at line 236 of file defchararray.py.
Referenced by numpy.core.defchararray.chararray.__lt__().
less_equal()
numpy.core.defchararray.less_equal (x1, x2)
Return (x1 <= x2) element-wise.
Unlike `numpy.less_equal`, this comparison is performed by first
stripping whitespace characters from the end of the string.  This
behavior is provided for backward-compatibility with numarray.
Parameters
----------
x1, x2 : array_like of str or unicode
    Input arrays of the same shape.
Returns
-------
out : ndarray
    Output array of bools.
See Also
--------
equal, not_equal, greater_equal, greater, less
Definition at line 184 of file defchararray.py.
Referenced by numpy.core.defchararray.chararray.__le__().
ljust()
numpy.core.defchararray.ljust (a, width, fillchar = ' ')
Return an array with the elements of `a` left-justified in a
string of length `width`.
Calls `str.ljust` element-wise.
Parameters
----------
a : array_like of str or unicode
width : int
    The length of the resulting strings
fillchar : str or unicode, optional
    The character to use for padding
Returns
-------
out : ndarray
    Output array of str or unicode, depending on input type
See Also
--------
str.ljust
Definition at line 1068 of file defchararray.py.
lower()
numpy.core.defchararray.lower (a)
Return an array with the elements converted to lowercase.
Call `str.lower` element-wise.
For 8-bit strings, this method is locale-dependent.
Parameters
----------
a : array_like, {str, unicode}
    Input array.
Returns
-------
out : ndarray, {str, unicode}
    Output array of str or unicode, depending on input type
See Also
--------
str.lower
Examples
--------
>>> c = np.array(['A1B C', '1BCA', 'BCA1']); c
array(['A1B C', '1BCA', 'BCA1'], dtype='<U5')
>>> np.char.lower(c)
array(['a1b c', '1bca', 'bca1'], dtype='<U5')
Definition at line 1104 of file defchararray.py.
lstrip()
numpy.core.defchararray.lstrip (a, chars = None)
For each element in `a`, return a copy with the leading characters
removed.
Calls `str.lstrip` element-wise.
Parameters
----------
a : array-like, {str, unicode}
    Input array.
chars : {str, unicode}, optional
    The `chars` argument is a string specifying the set of
    characters to be removed. If omitted or None, the `chars`
    argument defaults to removing whitespace. The `chars` argument
    is not a prefix; rather, all combinations of its values are
    stripped.
Returns
-------
out : ndarray, {str, unicode}
    Output array of str or unicode, depending on input type
See Also
--------
str.lstrip
Examples
--------
>>> c = np.array(['aAaAaA', '  aA  ', 'abBABba'])
>>> c
array(['aAaAaA', '  aA  ', 'abBABba'], dtype='<U7')
The 'a' variable is unstripped from c[1] because whitespace leading.
>>> np.char.lstrip(c, 'a')
array(['AaAaA', '  aA  ', 'bBABba'], dtype='<U7')
>>> np.char.lstrip(c, 'A') # leaves c unchanged
array(['aAaAaA', '  aA  ', 'abBABba'], dtype='<U7')
>>> (np.char.lstrip(c, ' ') == np.char.lstrip(c, '')).all()
... # XXX: is this a regression? This used to return True
... # np.char.lstrip(c,'') does not modify c at all.
False
>>> (np.char.lstrip(c, ' ') == np.char.lstrip(c, None)).all()
True
Definition at line 1143 of file defchararray.py.
mod()
numpy.core.defchararray.mod (a, values)
Return (a % i), that is pre-Python 2.6 string formatting
(interpolation), element-wise for a pair of array_likes of str
or unicode.
Parameters
----------
a : array_like of str or unicode
values : array_like of values
   These values will be element-wise interpolated into the string.
Returns
-------
out : ndarray
    Output array of str or unicode, depending on input types
See Also
--------
str.__mod__
Definition at line 395 of file defchararray.py.
References _to_bytes_or_str_array().
multiply()
numpy.core.defchararray.multiply (a, i)
Return (a * i), that is string multiple concatenation,
element-wise.
Values in `i` of less than 0 are treated as 0 (which yields an
empty string).
Parameters
----------
a : array_like of str or unicode
i : array_like of ints
Returns
-------
out : ndarray
    Output array of str or unicode, depending on input types
Examples
--------
>>> a = np.array(["a", "b", "c"])
>>> np.char.multiply(x, 3)
array(['aaa', 'bbb', 'ccc'], dtype='<U3')
>>> i = np.array([1, 2, 3])
>>> np.char.multiply(a, i)
array(['a', 'bb', 'ccc'], dtype='<U3')
>>> np.char.multiply(np.array(['a']), i)
array(['a', 'aa', 'aaa'], dtype='<U3')
>>> a = np.array(['a', 'b', 'c', 'd', 'e', 'f']).reshape((2, 3))
>>> np.char.multiply(a, 3)
array([['aaa', 'bbb', 'ccc'],
       ['ddd', 'eee', 'fff']], dtype='<U3')
>>> np.char.multiply(a, i)
array([['a', 'bb', 'ccc'],
       ['d', 'ee', 'fff']], dtype='<U3')
Definition at line 344 of file defchararray.py.
References _get_num_chars(), and numpy.core.fromnumeric.max().
Referenced by numpy.core.defchararray.chararray.__mul__(), and numpy.core.defchararray.chararray.__rmul__().
not_equal()
numpy.core.defchararray.not_equal (x1, x2)
Return (x1 != x2) element-wise.
Unlike `numpy.not_equal`, this comparison is performed by first
stripping whitespace characters from the end of the string.  This
behavior is provided for backward-compatibility with numarray.
Parameters
----------
x1, x2 : array_like of str or unicode
    Input arrays of the same shape.
Returns
-------
out : ndarray
    Output array of bools.
See Also
--------
equal, greater_equal, less_equal, greater, less
Definition at line 131 of file defchararray.py.
Referenced by numpy.core.defchararray.chararray.__ne__().
partition()
numpy.core.defchararray.partition (a, sep)
Partition each element in `a` around `sep`.
Calls `str.partition` element-wise.
For each element in `a`, split the element as the first
occurrence of `sep`, and return 3 strings containing the part
before the separator, the separator itself, and the part after
the separator. If the separator is not found, return 3 strings
containing the string itself, followed by two empty strings.
Parameters
----------
a : array_like, {str, unicode}
    Input array
sep : {str, unicode}
    Separator to split each string element in `a`.
Returns
-------
out : ndarray, {str, unicode}
    Output array of str or unicode, depending on input type.
    The output array will have an extra dimension with 3
    elements per input element.
See Also
--------
str.partition
Definition at line 1202 of file defchararray.py.
References _to_bytes_or_str_array().
replace()
numpy.core.defchararray.replace (a, old, new, count = None)
For each element in `a`, return a copy of the string with all
occurrences of substring `old` replaced by `new`.
Calls `str.replace` element-wise.
Parameters
----------
a : array-like of str or unicode
old, new : str or unicode
count : int, optional
    If the optional argument `count` is given, only the first
    `count` occurrences are replaced.
Returns
-------
out : ndarray
    Output array of str or unicode, depending on input type
See Also
--------
str.replace
Examples
--------
>>> a = np.array(["That is a mango", "Monkeys eat mangos"])
>>> np.char.replace(a, 'mango', 'banana')
array(['That is a banana', 'Monkeys eat bananas'], dtype='<U19')
>>> a = np.array(["The dish is fresh", "This is it"])
>>> np.char.replace(a, 'is', 'was')
array(['The dwash was fresh', 'Thwas was it'], dtype='<U19')
Definition at line 1242 of file defchararray.py.
References _clean_args(), and _to_bytes_or_str_array().
rfind()
numpy.core.defchararray.rfind (a, sub, start = 0, end = None)
For each element in `a`, return the highest index in the string
where substring `sub` is found, such that `sub` is contained
within [`start`, `end`].
Calls `str.rfind` element-wise.
Parameters
----------
a : array-like of str or unicode
sub : str or unicode
start, end : int, optional
    Optional arguments `start` and `end` are interpreted as in
    slice notation.
Returns
-------
out : ndarray
   Output array of ints.  Return -1 on failure.
See Also
--------
str.rfind
Definition at line 1283 of file defchararray.py.
References _clean_args().
rindex()
numpy.core.defchararray.rindex (a, sub, start = 0, end = None)
Like `rfind`, but raises `ValueError` when the substring `sub` is
not found.
Calls `str.rindex` element-wise.
Parameters
----------
a : array-like of str or unicode
sub : str or unicode
start, end : int, optional
Returns
-------
out : ndarray
   Output array of ints.
See Also
--------
rfind, str.rindex
Definition at line 1316 of file defchararray.py.
References _clean_args().
rjust()
numpy.core.defchararray.rjust (a, width, fillchar = ' ')
Return an array with the elements of `a` right-justified in a
string of length `width`.
Calls `str.rjust` element-wise.
Parameters
----------
a : array_like of str or unicode
width : int
    The length of the resulting strings
fillchar : str or unicode, optional
    The character to use for padding
Returns
-------
out : ndarray
    Output array of str or unicode, depending on input type
See Also
--------
str.rjust
Definition at line 1346 of file defchararray.py.
rpartition()
numpy.core.defchararray.rpartition (a, sep)
Partition (split) each element around the right-most separator.
Calls `str.rpartition` element-wise.
For each element in `a`, split the element as the last
occurrence of `sep`, and return 3 strings containing the part
before the separator, the separator itself, and the part after
the separator. If the separator is not found, return 3 strings
containing the string itself, followed by two empty strings.
Parameters
----------
a : array_like of str or unicode
    Input array
sep : str or unicode
    Right-most separator to split each element in array.
Returns
-------
out : ndarray
    Output array of string or unicode, depending on input
    type.  The output array will have an extra dimension with
    3 elements per input element.
See Also
--------
str.rpartition
Definition at line 1382 of file defchararray.py.
References _to_bytes_or_str_array().
rsplit()
numpy.core.defchararray.rsplit (a, sep = None, maxsplit = None)
For each element in `a`, return a list of the words in the
string, using `sep` as the delimiter string.
Calls `str.rsplit` element-wise.
Except for splitting from the right, `rsplit`
behaves like `split`.
Parameters
----------
a : array_like of str or unicode
sep : str or unicode, optional
    If `sep` is not specified or None, any whitespace string
    is a separator.
maxsplit : int, optional
    If `maxsplit` is given, at most `maxsplit` splits are done,
    the rightmost ones.
Returns
-------
out : ndarray
   Array of list objects
See Also
--------
str.rsplit, split
Definition at line 1422 of file defchararray.py.
References _clean_args().
rstrip()
numpy.core.defchararray.rstrip (a, chars = None)
For each element in `a`, return a copy with the trailing
characters removed.
Calls `str.rstrip` element-wise.
Parameters
----------
a : array-like of str or unicode
chars : str or unicode, optional
   The `chars` argument is a string specifying the set of
   characters to be removed. If omitted or None, the `chars`
   argument defaults to removing whitespace. The `chars` argument
   is not a suffix; rather, all combinations of its values are
   stripped.
Returns
-------
out : ndarray
    Output array of str or unicode, depending on input type
See Also
--------
str.rstrip
Examples
--------
>>> c = np.array(['aAaAaA', 'abBABba'], dtype='S7'); c
array(['aAaAaA', 'abBABba'],
    dtype='|S7')
>>> np.char.rstrip(c, b'a')
array(['aAaAaA', 'abBABb'],
    dtype='|S7')
>>> np.char.rstrip(c, b'A')
array(['aAaAa', 'abBABba'],
    dtype='|S7')
Definition at line 1464 of file defchararray.py.
split()
numpy.core.defchararray.split (a, sep = None, maxsplit = None)
For each element in `a`, return a list of the words in the
string, using `sep` as the delimiter string.
Calls `str.split` element-wise.
Parameters
----------
a : array_like of str or unicode
sep : str or unicode, optional
   If `sep` is not specified or None, any whitespace string is a
   separator.
maxsplit : int, optional
    If `maxsplit` is given, at most `maxsplit` splits are done.
Returns
-------
out : ndarray
    Array of list objects
See Also
--------
str.split, rsplit
Definition at line 1509 of file defchararray.py.
References _clean_args().
splitlines()
numpy.core.defchararray.splitlines (a, keepends = None)
For each element in `a`, return a list of the lines in the
element, breaking at line boundaries.
Calls `str.splitlines` element-wise.
Parameters
----------
a : array_like of str or unicode
keepends : bool, optional
    Line breaks are not included in the resulting list unless
    keepends is given and true.
Returns
-------
out : ndarray
    Array of list objects
See Also
--------
str.splitlines
Definition at line 1548 of file defchararray.py.
References _clean_args().
startswith()
numpy.core.defchararray.startswith (a, prefix, start = 0, end = None)
Returns a boolean array which is `True` where the string element
in `a` starts with `prefix`, otherwise `False`.
Calls `str.startswith` element-wise.
Parameters
----------
a : array_like of str or unicode
prefix : str
start, end : int, optional
    With optional `start`, test beginning at that position. With
    optional `end`, stop comparing at that position.
Returns
-------
out : ndarray
    Array of booleans
See Also
--------
str.startswith
Definition at line 1582 of file defchararray.py.
References _clean_args().
str_len()
numpy.core.defchararray.str_len (a)
Return len(a) element-wise.
Parameters
----------
a : array_like of str or unicode
Returns
-------
out : ndarray
    Output array of integers
See Also
--------
len
Examples
--------
>>> a = np.array(['Grace Hopper Conference', 'Open Source Day'])
>>> np.char.str_len(a)
array([23, 15])
>>> a = np.array([u'\u0420', u'\u043e'])
>>> np.char.str_len(a)
array([1, 1])
>>> a = np.array([['hello', 'world'], [u'\u0420', u'\u043e']])
>>> np.char.str_len(a)
array([[5, 5], [1, 1]])
Definition at line 266 of file defchararray.py.
strip()
numpy.core.defchararray.strip (a, chars = None)
For each element in `a`, return a copy with the leading and
trailing characters removed.
Calls `str.strip` element-wise.
Parameters
----------
a : array-like of str or unicode
chars : str or unicode, optional
   The `chars` argument is a string specifying the set of
   characters to be removed. If omitted or None, the `chars`
   argument defaults to removing whitespace. The `chars` argument
   is not a prefix or suffix; rather, all combinations of its
   values are stripped.
Returns
-------
out : ndarray
    Output array of str or unicode, depending on input type
See Also
--------
str.strip
Examples
--------
>>> c = np.array(['aAaAaA', '  aA  ', 'abBABba'])
>>> c
array(['aAaAaA', '  aA  ', 'abBABba'], dtype='<U7')
>>> np.char.strip(c)
array(['aAaAaA', 'aA', 'abBABba'], dtype='<U7')
>>> np.char.strip(c, 'a') # 'a' unstripped from c[1] because whitespace leads
array(['AaAaA', '  aA  ', 'bBABb'], dtype='<U7')
>>> np.char.strip(c, 'A') # 'A' unstripped from c[1] because (unprinted) ws trails
array(['aAaAa', '  aA  ', 'abBABba'], dtype='<U7')
Definition at line 1614 of file defchararray.py.
References _clean_args().
swapcase()
numpy.core.defchararray.swapcase (a)
Return element-wise a copy of the string with
uppercase characters converted to lowercase and vice versa.
Calls `str.swapcase` element-wise.
For 8-bit strings, this method is locale-dependent.
Parameters
----------
a : array_like, {str, unicode}
    Input array.
Returns
-------
out : ndarray, {str, unicode}
    Output array of str or unicode, depending on input type
See Also
--------
str.swapcase
Examples
--------
>>> c=np.array(['a1B c','1b Ca','b Ca1','cA1b'],'S5'); c
array(['a1B c', '1b Ca', 'b Ca1', 'cA1b'],
    dtype='|S5')
>>> np.char.swapcase(c)
array(['A1b C', '1B cA', 'B cA1', 'Ca1B'],
    dtype='|S5')
Definition at line 1659 of file defchararray.py.
title()
numpy.core.defchararray.title (a)
Return element-wise title cased version of string or unicode.
Title case words start with uppercase characters, all remaining cased
characters are lowercase.
Calls `str.title` element-wise.
For 8-bit strings, this method is locale-dependent.
Parameters
----------
a : array_like, {str, unicode}
    Input array.
Returns
-------
out : ndarray
    Output array of str or unicode, depending on input type
See Also
--------
str.title
Examples
--------
>>> c=np.array(['a1b c','1b ca','b ca1','ca1b'],'S5'); c
array(['a1b c', '1b ca', 'b ca1', 'ca1b'],
    dtype='|S5')
>>> np.char.title(c)
array(['A1B C', '1B Ca', 'B Ca1', 'Ca1B'],
    dtype='|S5')
Definition at line 1697 of file defchararray.py.
translate()
numpy.core.defchararray.translate (a, table, deletechars = None)
For each element in `a`, return a copy of the string where all
characters occurring in the optional argument `deletechars` are
removed, and the remaining characters have been mapped through the
given translation table.
Calls `str.translate` element-wise.
Parameters
----------
a : array-like of str or unicode
table : str of length 256
deletechars : str
Returns
-------
out : ndarray
    Output array of str or unicode, depending on input type
See Also
--------
str.translate
Definition at line 1741 of file defchararray.py.
References _clean_args().
upper()
numpy.core.defchararray.upper (a)
Return an array with the elements converted to uppercase.
Calls `str.upper` element-wise.
For 8-bit strings, this method is locale-dependent.
Parameters
----------
a : array_like, {str, unicode}
    Input array.
Returns
-------
out : ndarray, {str, unicode}
    Output array of str or unicode, depending on input type
See Also
--------
str.upper
Examples
--------
>>> c = np.array(['a1b c', '1bca', 'bca1']); c
array(['a1b c', '1bca', 'bca1'], dtype='<U5')
>>> np.char.upper(c)
array(['A1B C', '1BCA', 'BCA1'], dtype='<U5')
Definition at line 1778 of file defchararray.py.
zfill()
numpy.core.defchararray.zfill (a, width)
Return the numeric string left-filled with zeros
Calls `str.zfill` element-wise.
Parameters
----------
a : array_like, {str, unicode}
    Input array.
width : int
    Width of string to left-fill elements in `a`.
Returns
-------
out : ndarray, {str, unicode}
    Output array of str or unicode, depending on input type
See Also
--------
str.zfill
Definition at line 1817 of file defchararray.py.
Variable Documentation
__all__
list numpy.core.defchararray.__all__ private
Initial value:
=  [
    'equal', 'not_equal', 'greater_equal', 'less_equal',
    'greater', 'less', 'str_len', 'add', 'multiply', 'mod', 'capitalize',
    'center', 'count', 'decode', 'encode', 'endswith', 'expandtabs',
    'find', 'index', 'isalnum', 'isalpha', 'isdigit', 'islower', 'isspace',
    'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'partition',
    'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit',
    'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase',
    'title', 'translate', 'upper', 'zfill', 'isnumeric', 'isdecimal',
    'array', 'asarray'
    ]
Definition at line 30 of file defchararray.py.
_globalvar
int numpy.core.defchararray._globalvar = 0 protected
Definition at line 43 of file defchararray.py.
array_function_dispatch
numpy.core.defchararray.array_function_dispatch
Initial value:
=  functools.partial(
    overrides.array_function_dispatch, module='numpy.char')
Definition at line 45 of file defchararray.py.