Code Cloning Analysis: scipy.linalg._interpolative_backend Namespace Reference
scipy.linalg._interpolative_backend Namespace Reference
Functions
_asfortranarray_copy (A)
id_srand (n)
id_srandi (t)
id_srando ()
idd_frm (n, w, x)
idd_sfrm (l, n, w, x)
idd_frmi (m)
idd_sfrmi (l, m)
iddp_id (eps, A)
iddr_id (A, k)
idd_reconid (B, idx, proj)
idd_reconint (idx, proj)
idd_copycols (A, k, idx)
idd_id2svd (B, idx, proj)
idd_snorm (m, n, matvect, matvec, its=20)
idd_diffsnorm (m, n, matvect, matvect2, matvec, matvec2, its=20)
iddr_svd (A, k)
iddp_svd (eps, A)
iddp_aid (eps, A)
idd_estrank (eps, A)
iddp_asvd (eps, A)
iddp_rid (eps, m, n, matvect)
idd_findrank (eps, m, n, matvect)
iddp_rsvd (eps, m, n, matvect, matvec)
iddr_aid (A, k)
iddr_aidi (m, n, k)
iddr_asvd (A, k)
iddr_rid (m, n, matvect, k)
iddr_rsvd (m, n, matvect, matvec, k)
idz_frm (n, w, x)
idz_sfrm (l, n, w, x)
idz_frmi (m)
idz_sfrmi (l, m)
idzp_id (eps, A)
idzr_id (A, k)
idz_reconid (B, idx, proj)
idz_reconint (idx, proj)
idz_copycols (A, k, idx)
idz_id2svd (B, idx, proj)
idz_snorm (m, n, matveca, matvec, its=20)
idz_diffsnorm (m, n, matveca, matveca2, matvec, matvec2, its=20)
idzr_svd (A, k)
idzp_svd (eps, A)
idzp_aid (eps, A)
idz_estrank (eps, A)
idzp_asvd (eps, A)
idzp_rid (eps, m, n, matveca)
idz_findrank (eps, m, n, matveca)
idzp_rsvd (eps, m, n, matveca, matvec)
idzr_aid (A, k)
idzr_aidi (m, n, k)
idzr_asvd (A, k)
idzr_rid (m, n, matveca, k)
idzr_rsvd (m, n, matveca, matvec, k)
Variables
_RETCODE_ERROR = RuntimeError("nonzero return code")
Detailed Description
Direct wrappers for Fortran `id_dist` backend.
Function Documentation
_asfortranarray_copy()
scipy.linalg._interpolative_backend._asfortranarray_copy (A) protected
Same as np.asfortranarray, but ensure a copy
Definition at line 40 of file _interpolative_backend.py.
Referenced by iddp_id(), iddr_id(), idzp_id(), and idzr_id().
id_srand()
scipy.linalg._interpolative_backend.id_srand (n)
Generate standard uniform pseudorandom numbers via a very efficient lagged
Fibonacci method.
:param n:
    Number of pseudorandom numbers to generate.
:type n: int
:return:
    Pseudorandom numbers.
:rtype: :class:`numpy.ndarray`
Definition at line 56 of file _interpolative_backend.py.
id_srandi()
scipy.linalg._interpolative_backend.id_srandi (t)
Initialize seed values for :func:`id_srand` (any appropriately random
numbers will do).
:param t:
    Array of 55 seed values.
:type t: :class:`numpy.ndarray`
Definition at line 72 of file _interpolative_backend.py.
id_srando()
scipy.linalg._interpolative_backend.id_srando ()
Reset seed values to their original values.
Definition at line 85 of file _interpolative_backend.py.
idd_copycols()
scipy.linalg._interpolative_backend.idd_copycols (A, k, idx)
Reconstruct skeleton matrix from real ID.
:param A:
    Original matrix.
:type A: :class:`numpy.ndarray`
:param k:
    Rank of ID.
:type k: int
:param idx:
    Column index array.
:type idx: :class:`numpy.ndarray`
:return:
    Skeleton matrix.
:rtype: :class:`numpy.ndarray`
Definition at line 293 of file _interpolative_backend.py.
idd_diffsnorm()
scipy.linalg._interpolative_backend.idd_diffsnorm (m, n, matvect, matvect2, matvec, matvec2, its = 20)
Estimate spectral norm of the difference of two real matrices by the
randomized power method.
:param m:
    Matrix row dimension.
:type m: int
:param n:
    Matrix column dimension.
:type n: int
:param matvect:
    Function to apply the transpose of the first matrix to a vector, with
    call signature `y = matvect(x)`, where `x` and `y` are the input and
    output vectors, respectively.
:type matvect: function
:param matvect2:
    Function to apply the transpose of the second matrix to a vector, with
    call signature `y = matvect2(x)`, where `x` and `y` are the input and
    output vectors, respectively.
:type matvect2: function
:param matvec:
    Function to apply the first matrix to a vector, with call signature
    `y = matvec(x)`, where `x` and `y` are the input and output vectors,
    respectively.
:type matvec: function
:param matvec2:
    Function to apply the second matrix to a vector, with call signature
    `y = matvec2(x)`, where `x` and `y` are the input and output vectors,
    respectively.
:type matvec2: function
:param its:
    Number of power method iterations.
:type its: int
:return:
    Spectral norm estimate of matrix difference.
:rtype: float
Definition at line 386 of file _interpolative_backend.py.
idd_estrank()
scipy.linalg._interpolative_backend.idd_estrank (eps, A)
Estimate rank of a real matrix to a specified relative precision using
random sampling.
The output rank is typically about 8 higher than the actual rank.
:param eps:
    Relative precision.
:type eps: float
:param A:
    Matrix.
:type A: :class:`numpy.ndarray`
:return:
    Rank estimate.
:rtype: int
Definition at line 527 of file _interpolative_backend.py.
References idd_frmi().
idd_findrank()
scipy.linalg._interpolative_backend.idd_findrank (eps, m, n, matvect)
Estimate rank of a real matrix to a specified relative precision using
random matrix-vector multiplication.
:param eps:
    Relative precision.
:type eps: float
:param m:
    Matrix row dimension.
:type m: int
:param n:
    Matrix column dimension.
:type n: int
:param matvect:
    Function to apply the matrix transpose to a vector, with call signature
    `y = matvect(x)`, where `x` and `y` are the input and output vectors,
    respectively.
:type matvect: function
:return:
    Rank estimate.
:rtype: int
Definition at line 637 of file _interpolative_backend.py.
idd_frm()
scipy.linalg._interpolative_backend.idd_frm (n, w, x)
Transform real vector via a composition of Rokhlin's random transform,
random subselection, and an FFT.
In contrast to :func:`idd_sfrm`, this routine works best when the length of
the transformed vector is the power-of-two integer output by
:func:`idd_frmi`, or when the length is not specified but instead
determined a posteriori from the output. The returned transformed vector is
randomly permuted.
:param n:
    Greatest power-of-two integer satisfying `n <= x.size` as obtained from
    :func:`idd_frmi`; `n` is also the length of the output vector.
:type n: int
:param w:
    Initialization array constructed by :func:`idd_frmi`.
:type w: :class:`numpy.ndarray`
:param x:
    Vector to be transformed.
:type x: :class:`numpy.ndarray`
:return:
    Transformed vector.
:rtype: :class:`numpy.ndarray`
Definition at line 96 of file _interpolative_backend.py.
idd_frmi()
scipy.linalg._interpolative_backend.idd_frmi (m)
Initialize data for :func:`idd_frm`.
:param m:
    Length of vector to be transformed.
:type m: int
:return:
    Greatest power-of-two integer `n` satisfying `n <= m`.
:rtype: int
:return:
    Initialization array to be used by :func:`idd_frm`.
:rtype: :class:`numpy.ndarray`
Definition at line 154 of file _interpolative_backend.py.
Referenced by idd_estrank(), and iddp_aid().
idd_id2svd()
scipy.linalg._interpolative_backend.idd_id2svd (B, idx, proj)
Convert real ID to SVD.
:param B:
    Skeleton matrix.
:type B: :class:`numpy.ndarray`
:param idx:
    Column index array.
:type idx: :class:`numpy.ndarray`
:param proj:
    Interpolation coefficients.
:type proj: :class:`numpy.ndarray`
:return:
    Left singular vectors.
:rtype: :class:`numpy.ndarray`
:return:
    Right singular vectors.
:rtype: :class:`numpy.ndarray`
:return:
    Singular values.
:rtype: :class:`numpy.ndarray`
Definition at line 319 of file _interpolative_backend.py.
idd_reconid()
scipy.linalg._interpolative_backend.idd_reconid (B, idx, proj)
Reconstruct matrix from real ID.
:param B:
    Skeleton matrix.
:type B: :class:`numpy.ndarray`
:param idx:
    Column index array.
:type idx: :class:`numpy.ndarray`
:param proj:
    Interpolation coefficients.
:type proj: :class:`numpy.ndarray`
:return:
    Reconstructed matrix.
:rtype: :class:`numpy.ndarray`
Definition at line 250 of file _interpolative_backend.py.
idd_reconint()
scipy.linalg._interpolative_backend.idd_reconint (idx, proj)
Reconstruct interpolation matrix from real ID.
:param idx:
    Column index array.
:type idx: :class:`numpy.ndarray`
:param proj:
    Interpolation coefficients.
:type proj: :class:`numpy.ndarray`
:return:
    Interpolation matrix.
:rtype: :class:`numpy.ndarray`
Definition at line 275 of file _interpolative_backend.py.
idd_sfrm()
scipy.linalg._interpolative_backend.idd_sfrm (l, n, w, x)
Transform real vector via a composition of Rokhlin's random transform,
random subselection, and an FFT.
In contrast to :func:`idd_frm`, this routine works best when the length of
the transformed vector is known a priori.
:param l:
    Length of transformed vector, satisfying `l <= n`.
:type l: int
:param n:
    Greatest power-of-two integer satisfying `n <= x.size` as obtained from
    :func:`idd_sfrmi`.
:type n: int
:param w:
    Initialization array constructed by :func:`idd_sfrmi`.
:type w: :class:`numpy.ndarray`
:param x:
    Vector to be transformed.
:type x: :class:`numpy.ndarray`
:return:
    Transformed vector.
:rtype: :class:`numpy.ndarray`
Definition at line 125 of file _interpolative_backend.py.
idd_sfrmi()
scipy.linalg._interpolative_backend.idd_sfrmi (l, m)
Initialize data for :func:`idd_sfrm`.
:param l:
    Length of output transformed vector.
:type l: int
:param m:
    Length of the vector to be transformed.
:type m: int
:return:
    Greatest power-of-two integer `n` satisfying `n <= m`.
:rtype: int
:return:
    Initialization array to be used by :func:`idd_sfrm`.
:rtype: :class:`numpy.ndarray`
Definition at line 172 of file _interpolative_backend.py.
idd_snorm()
scipy.linalg._interpolative_backend.idd_snorm (m, n, matvect, matvec, its = 20)
Estimate spectral norm of a real matrix by the randomized power method.
:param m:
    Matrix row dimension.
:type m: int
:param n:
    Matrix column dimension.
:type n: int
:param matvect:
    Function to apply the matrix transpose to a vector, with call signature
    `y = matvect(x)`, where `x` and `y` are the input and output vectors,
    respectively.
:type matvect: function
:param matvec:
    Function to apply the matrix to a vector, with call signature
    `y = matvec(x)`, where `x` and `y` are the input and output vectors,
    respectively.
:type matvec: function
:param its:
    Number of power method iterations.
:type its: int
:return:
    Spectral norm estimate.
:rtype: float
Definition at line 354 of file _interpolative_backend.py.
iddp_aid()
scipy.linalg._interpolative_backend.iddp_aid (eps, A)
Compute ID of a real matrix to a specified relative precision using random
sampling.
:param eps:
    Relative precision.
:type eps: float
:param A:
    Matrix.
:type A: :class:`numpy.ndarray`
:return:
    Rank of ID.
:rtype: int
:return:
    Column index array.
:rtype: :class:`numpy.ndarray`
:return:
    Interpolation coefficients.
:rtype: :class:`numpy.ndarray`
Definition at line 496 of file _interpolative_backend.py.
References idd_frmi().
iddp_asvd()
scipy.linalg._interpolative_backend.iddp_asvd (eps, A)
Compute SVD of a real matrix to a specified relative precision using random
sampling.
:param eps:
    Relative precision.
:type eps: float
:param A:
    Matrix.
:type A: :class:`numpy.ndarray`
:return:
    Left singular vectors.
:rtype: :class:`numpy.ndarray`
:return:
    Right singular vectors.
:rtype: :class:`numpy.ndarray`
:return:
    Singular values.
:rtype: :class:`numpy.ndarray`
Definition at line 557 of file _interpolative_backend.py.
iddp_id()
scipy.linalg._interpolative_backend.iddp_id (eps, A)
Compute ID of a real matrix to a specified relative precision.
:param eps:
    Relative precision.
:type eps: float
:param A:
    Matrix.
:type A: :class:`numpy.ndarray`
:return:
    Rank of ID.
:rtype: int
:return:
    Column index array.
:rtype: :class:`numpy.ndarray`
:return:
    Interpolation coefficients.
:rtype: :class:`numpy.ndarray`
Definition at line 197 of file _interpolative_backend.py.
References _asfortranarray_copy().
iddp_rid()
scipy.linalg._interpolative_backend.iddp_rid (eps, m, n, matvect)
Compute ID of a real matrix to a specified relative precision using random
matrix-vector multiplication.
:param eps:
    Relative precision.
:type eps: float
:param m:
    Matrix row dimension.
:type m: int
:param n:
    Matrix column dimension.
:type n: int
:param matvect:
    Function to apply the matrix transpose to a vector, with call signature
    `y = matvect(x)`, where `x` and `y` are the input and output vectors,
    respectively.
:type matvect: function
:return:
    Rank of ID.
:rtype: int
:return:
    Column index array.
:rtype: :class:`numpy.ndarray`
:return:
    Interpolation coefficients.
:rtype: :class:`numpy.ndarray`
Definition at line 599 of file _interpolative_backend.py.
iddp_rsvd()
scipy.linalg._interpolative_backend.iddp_rsvd (eps, m, n, matvect, matvec)
Compute SVD of a real matrix to a specified relative precision using random
matrix-vector multiplication.
:param eps:
    Relative precision.
:type eps: float
:param m:
    Matrix row dimension.
:type m: int
:param n:
    Matrix column dimension.
:type n: int
:param matvect:
    Function to apply the matrix transpose to a vector, with call signature
    `y = matvect(x)`, where `x` and `y` are the input and output vectors,
    respectively.
:type matvect: function
:param matvec:
    Function to apply the matrix to a vector, with call signature
    `y = matvec(x)`, where `x` and `y` are the input and output vectors,
    respectively.
:type matvec: function
:return:
    Left singular vectors.
:rtype: :class:`numpy.ndarray`
:return:
    Right singular vectors.
:rtype: :class:`numpy.ndarray`
:return:
    Singular values.
:rtype: :class:`numpy.ndarray`
Definition at line 671 of file _interpolative_backend.py.
iddp_svd()
scipy.linalg._interpolative_backend.iddp_svd (eps, A)
Compute SVD of a real matrix to a specified relative precision.
:param eps:
    Relative precision.
:type eps: float
:param A:
    Matrix.
:type A: :class:`numpy.ndarray`
:return:
    Left singular vectors.
:rtype: :class:`numpy.ndarray`
:return:
    Right singular vectors.
:rtype: :class:`numpy.ndarray`
:return:
    Singular values.
:rtype: :class:`numpy.ndarray`
Definition at line 460 of file _interpolative_backend.py.
iddr_aid()
scipy.linalg._interpolative_backend.iddr_aid (A, k)
Compute ID of a real matrix to a specified rank using random sampling.
:param A:
    Matrix.
:type A: :class:`numpy.ndarray`
:param k:
    Rank of ID.
:type k: int
:return:
    Column index array.
:rtype: :class:`numpy.ndarray`
:return:
    Interpolation coefficients.
:rtype: :class:`numpy.ndarray`
Definition at line 719 of file _interpolative_backend.py.
References iddr_aidi().
iddr_aidi()
scipy.linalg._interpolative_backend.iddr_aidi (m, n, k)
Initialize array for :func:`iddr_aid`.
:param m:
    Matrix row dimension.
:type m: int
:param n:
    Matrix column dimension.
:type n: int
:param k:
    Rank of ID.
:type k: int
:return:
    Initialization array to be used by :func:`iddr_aid`.
:rtype: :class:`numpy.ndarray`
Definition at line 748 of file _interpolative_backend.py.
Referenced by iddr_aid(), and iddr_asvd().
iddr_asvd()
scipy.linalg._interpolative_backend.iddr_asvd (A, k)
Compute SVD of a real matrix to a specified rank using random sampling.
:param A:
    Matrix.
:type A: :class:`numpy.ndarray`
:param k:
    Rank of SVD.
:type k: int
:return:
    Left singular vectors.
:rtype: :class:`numpy.ndarray`
:return:
    Right singular vectors.
:rtype: :class:`numpy.ndarray`
:return:
    Singular values.
:rtype: :class:`numpy.ndarray`
Definition at line 773 of file _interpolative_backend.py.
References iddr_aidi().
iddr_id()
scipy.linalg._interpolative_backend.iddr_id (A, k)
Compute ID of a real matrix to a specified rank.
:param A:
    Matrix.
:type A: :class:`numpy.ndarray`
:param k:
    Rank of ID.
:type k: int
:return:
    Column index array.
:rtype: :class:`numpy.ndarray`
:return:
    Interpolation coefficients.
:rtype: :class:`numpy.ndarray`
Definition at line 225 of file _interpolative_backend.py.
References _asfortranarray_copy().
iddr_rid()
scipy.linalg._interpolative_backend.iddr_rid (m, n, matvect, k)
Compute ID of a real matrix to a specified rank using random matrix-vector
multiplication.
:param m:
    Matrix row dimension.
:type m: int
:param n:
    Matrix column dimension.
:type n: int
:param matvect:
    Function to apply the matrix transpose to a vector, with call signature
    `y = matvect(x)`, where `x` and `y` are the input and output vectors,
    respectively.
:type matvect: function
:param k:
    Rank of ID.
:type k: int
:return:
    Column index array.
:rtype: :class:`numpy.ndarray`
:return:
    Interpolation coefficients.
:rtype: :class:`numpy.ndarray`
Definition at line 809 of file _interpolative_backend.py.
iddr_rsvd()
scipy.linalg._interpolative_backend.iddr_rsvd (m, n, matvect, matvec, k)
Compute SVD of a real matrix to a specified rank using random matrix-vector
multiplication.
:param m:
    Matrix row dimension.
:type m: int
:param n:
    Matrix column dimension.
:type n: int
:param matvect:
    Function to apply the matrix transpose to a vector, with call signature
    `y = matvect(x)`, where `x` and `y` are the input and output vectors,
    respectively.
:type matvect: function
:param matvec:
    Function to apply the matrix to a vector, with call signature
    `y = matvec(x)`, where `x` and `y` are the input and output vectors,
    respectively.
:type matvec: function
:param k:
    Rank of SVD.
:type k: int
:return:
    Left singular vectors.
:rtype: :class:`numpy.ndarray`
:return:
    Right singular vectors.
:rtype: :class:`numpy.ndarray`
:return:
    Singular values.
:rtype: :class:`numpy.ndarray`
Definition at line 845 of file _interpolative_backend.py.
iddr_svd()
scipy.linalg._interpolative_backend.iddr_svd (A, k)
Compute SVD of a real matrix to a specified rank.
:param A:
    Matrix.
:type A: :class:`numpy.ndarray`
:param k:
    Rank of SVD.
:type k: int
:return:
    Left singular vectors.
:rtype: :class:`numpy.ndarray`
:return:
    Right singular vectors.
:rtype: :class:`numpy.ndarray`
:return:
    Singular values.
:rtype: :class:`numpy.ndarray`
Definition at line 432 of file _interpolative_backend.py.
idz_copycols()
scipy.linalg._interpolative_backend.idz_copycols (A, k, idx)
Reconstruct skeleton matrix from complex ID.
:param A:
    Original matrix.
:type A: :class:`numpy.ndarray`
:param k:
    Rank of ID.
:type k: int
:param idx:
    Column index array.
:type idx: :class:`numpy.ndarray`
:return:
    Skeleton matrix.
:rtype: :class:`numpy.ndarray`
Definition at line 1087 of file _interpolative_backend.py.
idz_diffsnorm()
scipy.linalg._interpolative_backend.idz_diffsnorm (m, n, matveca, matveca2, matvec, matvec2, its = 20)
Estimate spectral norm of the difference of two complex matrices by the
randomized power method.
:param m:
    Matrix row dimension.
:type m: int
:param n:
    Matrix column dimension.
:type n: int
:param matveca:
    Function to apply the adjoint of the first matrix to a vector, with
    call signature `y = matveca(x)`, where `x` and `y` are the input and
    output vectors, respectively.
:type matveca: function
:param matveca2:
    Function to apply the adjoint of the second matrix to a vector, with
    call signature `y = matveca2(x)`, where `x` and `y` are the input and
    output vectors, respectively.
:type matveca2: function
:param matvec:
    Function to apply the first matrix to a vector, with call signature
    `y = matvec(x)`, where `x` and `y` are the input and output vectors,
    respectively.
:type matvec: function
:param matvec2:
    Function to apply the second matrix to a vector, with call signature
    `y = matvec2(x)`, where `x` and `y` are the input and output vectors,
    respectively.
:type matvec2: function
:param its:
    Number of power method iterations.
:type its: int
:return:
    Spectral norm estimate of matrix difference.
:rtype: float
Definition at line 1180 of file _interpolative_backend.py.
idz_estrank()
scipy.linalg._interpolative_backend.idz_estrank (eps, A)
Estimate rank of a complex matrix to a specified relative precision using
random sampling.
The output rank is typically about 8 higher than the actual rank.
:param eps:
    Relative precision.
:type eps: float
:param A:
    Matrix.
:type A: :class:`numpy.ndarray`
:return:
    Rank estimate.
:rtype: int
Definition at line 1321 of file _interpolative_backend.py.
References idz_frmi().
idz_findrank()
scipy.linalg._interpolative_backend.idz_findrank (eps, m, n, matveca)
Estimate rank of a complex matrix to a specified relative precision using
random matrix-vector multiplication.
:param eps:
    Relative precision.
:type eps: float
:param m:
    Matrix row dimension.
:type m: int
:param n:
    Matrix column dimension.
:type n: int
:param matveca:
    Function to apply the matrix adjoint to a vector, with call signature
    `y = matveca(x)`, where `x` and `y` are the input and output vectors,
    respectively.
:type matveca: function
:return:
    Rank estimate.
:rtype: int
Definition at line 1433 of file _interpolative_backend.py.
idz_frm()
scipy.linalg._interpolative_backend.idz_frm (n, w, x)
Transform complex vector via a composition of Rokhlin's random transform,
random subselection, and an FFT.
In contrast to :func:`idz_sfrm`, this routine works best when the length of
the transformed vector is the power-of-two integer output by
:func:`idz_frmi`, or when the length is not specified but instead
determined a posteriori from the output. The returned transformed vector is
randomly permuted.
:param n:
    Greatest power-of-two integer satisfying `n <= x.size` as obtained from
    :func:`idz_frmi`; `n` is also the length of the output vector.
:type n: int
:param w:
    Initialization array constructed by :func:`idz_frmi`.
:type w: :class:`numpy.ndarray`
:param x:
    Vector to be transformed.
:type x: :class:`numpy.ndarray`
:return:
    Transformed vector.
:rtype: :class:`numpy.ndarray`
Definition at line 890 of file _interpolative_backend.py.
idz_frmi()
scipy.linalg._interpolative_backend.idz_frmi (m)
Initialize data for :func:`idz_frm`.
:param m:
    Length of vector to be transformed.
:type m: int
:return:
    Greatest power-of-two integer `n` satisfying `n <= m`.
:rtype: int
:return:
    Initialization array to be used by :func:`idz_frm`.
:rtype: :class:`numpy.ndarray`
Definition at line 948 of file _interpolative_backend.py.
Referenced by idz_estrank(), and idzp_aid().
idz_id2svd()
scipy.linalg._interpolative_backend.idz_id2svd (B, idx, proj)
Convert complex ID to SVD.
:param B:
    Skeleton matrix.
:type B: :class:`numpy.ndarray`
:param idx:
    Column index array.
:type idx: :class:`numpy.ndarray`
:param proj:
    Interpolation coefficients.
:type proj: :class:`numpy.ndarray`
:return:
    Left singular vectors.
:rtype: :class:`numpy.ndarray`
:return:
    Right singular vectors.
:rtype: :class:`numpy.ndarray`
:return:
    Singular values.
:rtype: :class:`numpy.ndarray`
Definition at line 1113 of file _interpolative_backend.py.
idz_reconid()
scipy.linalg._interpolative_backend.idz_reconid (B, idx, proj)
Reconstruct matrix from complex ID.
:param B:
    Skeleton matrix.
:type B: :class:`numpy.ndarray`
:param idx:
    Column index array.
:type idx: :class:`numpy.ndarray`
:param proj:
    Interpolation coefficients.
:type proj: :class:`numpy.ndarray`
:return:
    Reconstructed matrix.
:rtype: :class:`numpy.ndarray`
Definition at line 1044 of file _interpolative_backend.py.
idz_reconint()
scipy.linalg._interpolative_backend.idz_reconint (idx, proj)
Reconstruct interpolation matrix from complex ID.
:param idx:
    Column index array.
:type idx: :class:`numpy.ndarray`
:param proj:
    Interpolation coefficients.
:type proj: :class:`numpy.ndarray`
:return:
    Interpolation matrix.
:rtype: :class:`numpy.ndarray`
Definition at line 1069 of file _interpolative_backend.py.
idz_sfrm()
scipy.linalg._interpolative_backend.idz_sfrm (l, n, w, x)
Transform complex vector via a composition of Rokhlin's random transform,
random subselection, and an FFT.
In contrast to :func:`idz_frm`, this routine works best when the length of
the transformed vector is known a priori.
:param l:
    Length of transformed vector, satisfying `l <= n`.
:type l: int
:param n:
    Greatest power-of-two integer satisfying `n <= x.size` as obtained from
    :func:`idz_sfrmi`.
:type n: int
:param w:
    Initialization array constructed by :func:`idd_sfrmi`.
:type w: :class:`numpy.ndarray`
:param x:
    Vector to be transformed.
:type x: :class:`numpy.ndarray`
:return:
    Transformed vector.
:rtype: :class:`numpy.ndarray`
Definition at line 919 of file _interpolative_backend.py.
idz_sfrmi()
scipy.linalg._interpolative_backend.idz_sfrmi (l, m)
Initialize data for :func:`idz_sfrm`.
:param l:
    Length of output transformed vector.
:type l: int
:param m:
    Length of the vector to be transformed.
:type m: int
:return:
    Greatest power-of-two integer `n` satisfying `n <= m`.
:rtype: int
:return:
    Initialization array to be used by :func:`idz_sfrm`.
:rtype: :class:`numpy.ndarray`
Definition at line 966 of file _interpolative_backend.py.
idz_snorm()
scipy.linalg._interpolative_backend.idz_snorm (m, n, matveca, matvec, its = 20)
Estimate spectral norm of a complex matrix by the randomized power method.
:param m:
    Matrix row dimension.
:type m: int
:param n:
    Matrix column dimension.
:type n: int
:param matveca:
    Function to apply the matrix adjoint to a vector, with call signature
    `y = matveca(x)`, where `x` and `y` are the input and output vectors,
    respectively.
:type matveca: function
:param matvec:
    Function to apply the matrix to a vector, with call signature
    `y = matvec(x)`, where `x` and `y` are the input and output vectors,
    respectively.
:type matvec: function
:param its:
    Number of power method iterations.
:type its: int
:return:
    Spectral norm estimate.
:rtype: float
Definition at line 1148 of file _interpolative_backend.py.
idzp_aid()
scipy.linalg._interpolative_backend.idzp_aid (eps, A)
Compute ID of a complex matrix to a specified relative precision using
random sampling.
:param eps:
    Relative precision.
:type eps: float
:param A:
    Matrix.
:type A: :class:`numpy.ndarray`
:return:
    Rank of ID.
:rtype: int
:return:
    Column index array.
:rtype: :class:`numpy.ndarray`
:return:
    Interpolation coefficients.
:rtype: :class:`numpy.ndarray`
Definition at line 1290 of file _interpolative_backend.py.
References idz_frmi().
idzp_asvd()
scipy.linalg._interpolative_backend.idzp_asvd (eps, A)
Compute SVD of a complex matrix to a specified relative precision using
random sampling.
:param eps:
    Relative precision.
:type eps: float
:param A:
    Matrix.
:type A: :class:`numpy.ndarray`
:return:
    Left singular vectors.
:rtype: :class:`numpy.ndarray`
:return:
    Right singular vectors.
:rtype: :class:`numpy.ndarray`
:return:
    Singular values.
:rtype: :class:`numpy.ndarray`
Definition at line 1351 of file _interpolative_backend.py.
idzp_id()
scipy.linalg._interpolative_backend.idzp_id (eps, A)
Compute ID of a complex matrix to a specified relative precision.
:param eps:
    Relative precision.
:type eps: float
:param A:
    Matrix.
:type A: :class:`numpy.ndarray`
:return:
    Rank of ID.
:rtype: int
:return:
    Column index array.
:rtype: :class:`numpy.ndarray`
:return:
    Interpolation coefficients.
:rtype: :class:`numpy.ndarray`
Definition at line 991 of file _interpolative_backend.py.
References _asfortranarray_copy().
idzp_rid()
scipy.linalg._interpolative_backend.idzp_rid (eps, m, n, matveca)
Compute ID of a complex matrix to a specified relative precision using
random matrix-vector multiplication.
:param eps:
    Relative precision.
:type eps: float
:param m:
    Matrix row dimension.
:type m: int
:param n:
    Matrix column dimension.
:type n: int
:param matveca:
    Function to apply the matrix adjoint to a vector, with call signature
    `y = matveca(x)`, where `x` and `y` are the input and output vectors,
    respectively.
:type matveca: function
:return:
    Rank of ID.
:rtype: int
:return:
    Column index array.
:rtype: :class:`numpy.ndarray`
:return:
    Interpolation coefficients.
:rtype: :class:`numpy.ndarray`
Definition at line 1393 of file _interpolative_backend.py.
idzp_rsvd()
scipy.linalg._interpolative_backend.idzp_rsvd (eps, m, n, matveca, matvec)
Compute SVD of a complex matrix to a specified relative precision using
random matrix-vector multiplication.
:param eps:
    Relative precision.
:type eps: float
:param m:
    Matrix row dimension.
:type m: int
:param n:
    Matrix column dimension.
:type n: int
:param matveca:
    Function to apply the matrix adjoint to a vector, with call signature
    `y = matveca(x)`, where `x` and `y` are the input and output vectors,
    respectively.
:type matveca: function
:param matvec:
    Function to apply the matrix to a vector, with call signature
    `y = matvec(x)`, where `x` and `y` are the input and output vectors,
    respectively.
:type matvec: function
:return:
    Left singular vectors.
:rtype: :class:`numpy.ndarray`
:return:
    Right singular vectors.
:rtype: :class:`numpy.ndarray`
:return:
    Singular values.
:rtype: :class:`numpy.ndarray`
Definition at line 1467 of file _interpolative_backend.py.
idzp_svd()
scipy.linalg._interpolative_backend.idzp_svd (eps, A)
Compute SVD of a complex matrix to a specified relative precision.
:param eps:
    Relative precision.
:type eps: float
:param A:
    Matrix.
:type A: :class:`numpy.ndarray`
:return:
    Left singular vectors.
:rtype: :class:`numpy.ndarray`
:return:
    Right singular vectors.
:rtype: :class:`numpy.ndarray`
:return:
    Singular values.
:rtype: :class:`numpy.ndarray`
Definition at line 1254 of file _interpolative_backend.py.
idzr_aid()
scipy.linalg._interpolative_backend.idzr_aid (A, k)
Compute ID of a complex matrix to a specified rank using random sampling.
:param A:
    Matrix.
:type A: :class:`numpy.ndarray`
:param k:
    Rank of ID.
:type k: int
:return:
    Column index array.
:rtype: :class:`numpy.ndarray`
:return:
    Interpolation coefficients.
:rtype: :class:`numpy.ndarray`
Definition at line 1515 of file _interpolative_backend.py.
References idzr_aidi().
idzr_aidi()
scipy.linalg._interpolative_backend.idzr_aidi (m, n, k)
Initialize array for :func:`idzr_aid`.
:param m:
    Matrix row dimension.
:type m: int
:param n:
    Matrix column dimension.
:type n: int
:param k:
    Rank of ID.
:type k: int
:return:
    Initialization array to be used by :func:`idzr_aid`.
:rtype: :class:`numpy.ndarray`
Definition at line 1544 of file _interpolative_backend.py.
Referenced by idzr_aid(), and idzr_asvd().
idzr_asvd()
scipy.linalg._interpolative_backend.idzr_asvd (A, k)
Compute SVD of a complex matrix to a specified rank using random sampling.
:param A:
    Matrix.
:type A: :class:`numpy.ndarray`
:param k:
    Rank of SVD.
:type k: int
:return:
    Left singular vectors.
:rtype: :class:`numpy.ndarray`
:return:
    Right singular vectors.
:rtype: :class:`numpy.ndarray`
:return:
    Singular values.
:rtype: :class:`numpy.ndarray`
Definition at line 1569 of file _interpolative_backend.py.
References idzr_aidi().
idzr_id()
scipy.linalg._interpolative_backend.idzr_id (A, k)
Compute ID of a complex matrix to a specified rank.
:param A:
    Matrix.
:type A: :class:`numpy.ndarray`
:param k:
    Rank of ID.
:type k: int
:return:
    Column index array.
:rtype: :class:`numpy.ndarray`
:return:
    Interpolation coefficients.
:rtype: :class:`numpy.ndarray`
Definition at line 1019 of file _interpolative_backend.py.
References _asfortranarray_copy().
idzr_rid()
scipy.linalg._interpolative_backend.idzr_rid (m, n, matveca, k)
Compute ID of a complex matrix to a specified rank using random
matrix-vector multiplication.
:param m:
    Matrix row dimension.
:type m: int
:param n:
    Matrix column dimension.
:type n: int
:param matveca:
    Function to apply the matrix adjoint to a vector, with call signature
    `y = matveca(x)`, where `x` and `y` are the input and output vectors,
    respectively.
:type matveca: function
:param k:
    Rank of ID.
:type k: int
:return:
    Column index array.
:rtype: :class:`numpy.ndarray`
:return:
    Interpolation coefficients.
:rtype: :class:`numpy.ndarray`
Definition at line 1607 of file _interpolative_backend.py.
idzr_rsvd()
scipy.linalg._interpolative_backend.idzr_rsvd (m, n, matveca, matvec, k)
Compute SVD of a complex matrix to a specified rank using random
matrix-vector multiplication.
:param m:
    Matrix row dimension.
:type m: int
:param n:
    Matrix column dimension.
:type n: int
:param matveca:
    Function to apply the matrix adjoint to a vector, with call signature
    `y = matveca(x)`, where `x` and `y` are the input and output vectors,
    respectively.
:type matveca: function
:param matvec:
    Function to apply the matrix to a vector, with call signature
    `y = matvec(x)`, where `x` and `y` are the input and output vectors,
    respectively.
:type matvec: function
:param k:
    Rank of SVD.
:type k: int
:return:
    Left singular vectors.
:rtype: :class:`numpy.ndarray`
:return:
    Right singular vectors.
:rtype: :class:`numpy.ndarray`
:return:
    Singular values.
:rtype: :class:`numpy.ndarray`
Definition at line 1643 of file _interpolative_backend.py.
idzr_svd()
scipy.linalg._interpolative_backend.idzr_svd (A, k)
Compute SVD of a complex matrix to a specified rank.
:param A:
    Matrix.
:type A: :class:`numpy.ndarray`
:param k:
    Rank of SVD.
:type k: int
:return:
    Left singular vectors.
:rtype: :class:`numpy.ndarray`
:return:
    Right singular vectors.
:rtype: :class:`numpy.ndarray`
:return:
    Singular values.
:rtype: :class:`numpy.ndarray`
Definition at line 1226 of file _interpolative_backend.py.
Variable Documentation
_RETCODE_ERROR
scipy.linalg._interpolative_backend._RETCODE_ERROR = RuntimeError("nonzero return code") protected
Definition at line 37 of file _interpolative_backend.py.