Code Cloning Analysis: axes_grid1.axes_size.Fixed Class Reference
axes_grid1.axes_size.Fixed Class Reference
Public Member Functions
__init__ (self, fixed_size)
get_size (self, renderer)
Public Member Functions inherited from axes_grid1.axes_size._Base
__rmul__ (self, other)
__mul__ (self, other)
__div__ (self, other)
__add__ (self, other)
__neg__ (self)
__radd__ (self, other)
__sub__ (self, other)
Public Attributes
fixed_size = fixed_size
Detailed Description
Simple fixed size with absolute part = *fixed_size* and relative part = 0.
Definition at line 73 of file axes_size.py.
Constructor & Destructor Documentation
__init__()
axes_grid1.axes_size.Fixed.__init__ (self, fixed_size)
Definition at line 78 of file axes_size.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
get_size()
axes_grid1.axes_size.Fixed.get_size (self, renderer)
Return two-float tuple with relative and absolute sizes.
Reimplemented from axes_grid1.axes_size._Base.
Definition at line 82 of file axes_size.py.
References fixed_size.
Referenced by matplotlib.text.Text.set_bbox(), matplotlib.text.Text.update_bbox_position_size(), and matplotlib.text.Annotation.update_positions().
Member Data Documentation
fixed_size
axes_grid1.axes_size.Fixed.fixed_size = fixed_size
Definition at line 80 of file axes_size.py.
Referenced by get_size().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/mpl_toolkits/axes_grid1/axes_size.py