Code Cloning Analysis: scipy.stats._distn_infrastructure Namespace Reference
scipy.stats._distn_infrastructure Namespace Reference
Classes
class _ShapeInfo
class rv_continuous
class rv_continuous_frozen
class rv_discrete
class rv_discrete_frozen
class rv_frozen
class rv_generic
class rv_sample
Functions
_moment (data, n, mu=None)
_moment_from_stats (n, mu, mu2, g1, g2, moment_func, args)
_skew (data)
_kurtosis (data)
_fit_determine_optimizer (optimizer)
_sum_finite (x)
argsreduce (cond, *args)
_get_fixed_fit_value (kwds, names)
_drv2_moment (self, n, *args)
_drv2_ppfsingle (self, q, *args)
_expect (fun, lb, ub, x0, inc, maxcount=1000, tolerance=1e-10, chunksize=32)
_iter_chunked (x0, x1, chunksize=4, inc=1)
_check_shape (argshape, size)
get_distribution_names (namespace_pairs, rv_base_class)
Variables
dict docheaders
str _doc_rvs
str _doc_pdf
str _doc_logpdf
str _doc_pmf
str _doc_logpmf
str _doc_cdf
str _doc_logcdf
str _doc_sf
str _doc_logsf
str _doc_ppf
str _doc_isf
str _doc_moment
str _doc_stats
str _doc_entropy
str _doc_fit
str _doc_expect
str _doc_expect_discrete
str _doc_median
str _doc_mean
str _doc_var
str _doc_std
str _doc_interval
str _doc_allmethods
str _doc_default_longsummary
str _doc_default_frozen_note
str _doc_default_example
str _doc_default_locscale
str _doc_default
str _doc_default_before_notes
dict docdict
dict docdict_discrete = docdict.copy()
list _doc_disc_methods
list _doc_disc_methods_err_varname = ['cdf', 'logcdf', 'sf', 'logsf']
str _doc_default_discrete_example
str _doc_default_discrete_locscale
str _doc_default_disc
str parse_arg_template
inc
Function Documentation
_check_shape()
scipy.stats._distn_infrastructure._check_shape (argshape, size) protected
This is a utility function used by `_rvs()` in the class geninvgauss_gen.
It compares the tuple argshape to the tuple size.
Parameters
----------
argshape : tuple of integers
    Shape of the arguments.
size : tuple of integers or integer
    Size argument of rvs().
Returns
-------
The function returns two tuples, scalar_shape and bc.
scalar_shape : tuple
    Shape to which the 1-d array of random variates returned by
    _rvs_scalar() is converted when it is copied into the
    output array of _rvs().
bc : tuple of booleans
    bc is an tuple the same length as size. bc[j] is True if the data
    associated with that index is generated in one call of _rvs_scalar().
Definition at line 3978 of file _distn_infrastructure.py.
_drv2_moment()
scipy.stats._distn_infrastructure._drv2_moment (self, n, * args) protected
Non-central moment of discrete distribution.
Definition at line 2954 of file _distn_infrastructure.py.
References _expect().
_drv2_ppfsingle()
scipy.stats._distn_infrastructure._drv2_ppfsingle (self, q, * args) protected
Definition at line 2963 of file _distn_infrastructure.py.
_expect()
scipy.stats._distn_infrastructure._expect (fun, lb, ub, x0, inc, maxcount = 1000, tolerance = 1e-10, chunksize = 32) protected
Helper for computing the expectation value of `fun`.
Definition at line 3776 of file _distn_infrastructure.py.
References _iter_chunked().
Referenced by _drv2_moment(), scipy.stats._distn_infrastructure.rv_discrete.expect(), and scipy.stats._distn_infrastructure.rv_discrete.isf().
_fit_determine_optimizer()
scipy.stats._distn_infrastructure._fit_determine_optimizer (optimizer) protected
Definition at line 421 of file _distn_infrastructure.py.
_get_fixed_fit_value()
scipy.stats._distn_infrastructure._get_fixed_fit_value (kwds, names) protected
Given names such as `['f0', 'fa', 'fix_a']`, check that there is
at most one non-None value in `kwds` associaed with those names.
Return that value, or None if none of the names occur in `kwds`.
As a side effect, all occurrences of those names in `kwds` are
removed.
Definition at line 1573 of file _distn_infrastructure.py.
Referenced by scipy.stats._distn_infrastructure.rv_continuous._reduce_func().
_iter_chunked()
scipy.stats._distn_infrastructure._iter_chunked (x0, x1, chunksize = 4, inc = 1) protected
Iterate from x0 to x1 in chunks of chunksize and steps inc.
x0 must be finite, x1 need not be. In the latter case, the iterator is
infinite.
Handles both x0 < x1 and x0 > x1. In the latter case, iterates downwards
(make sure to set inc < 0.)
>>> [x for x in _iter_chunked(2, 5, inc=2)]
[array([2, 4])]
>>> [x for x in _iter_chunked(2, 11, inc=2)]
[array([2, 4, 6, 8]), array([10])]
>>> [x for x in _iter_chunked(2, -5, inc=-2)]
[array([ 2,  0, -2, -4])]
>>> [x for x in _iter_chunked(2, -9, inc=-2)]
[array([ 2,  0, -2, -4]), array([-6, -8])]
Definition at line 3817 of file _distn_infrastructure.py.
Referenced by _expect().
_kurtosis()
scipy.stats._distn_infrastructure._kurtosis (data) protected
kurtosis is fourth central moment / variance**2 - 3.
Definition at line 412 of file _distn_infrastructure.py.
_moment()
scipy.stats._distn_infrastructure._moment (data, n, mu = None) protected
Definition at line 363 of file _distn_infrastructure.py.
_moment_from_stats()
scipy.stats._distn_infrastructure._moment_from_stats (n, mu, mu2, g1, g2, moment_func, args) protected
Definition at line 369 of file _distn_infrastructure.py.
_skew()
scipy.stats._distn_infrastructure._skew (data) protected
skew is third central moment / variance**(1.5)
Definition at line 401 of file _distn_infrastructure.py.
_sum_finite()
scipy.stats._distn_infrastructure._sum_finite (x) protected
For a 1D array x, return a tuple containing the sum of the
finite values of x and the number of nonfinite values.
This is a utility function used when evaluating the negative
loglikelihood for a distribution and an array of samples.
Examples
--------
>>> tot, nbad = _sum_finite(np.array([-2, -np.inf, 5, 1]))
>>> tot
4.0
>>> nbad
1
Definition at line 434 of file _distn_infrastructure.py.
Referenced by scipy.stats._distn_infrastructure.rv_continuous._nnlf_and_penalty().
argsreduce()
scipy.stats._distn_infrastructure.argsreduce (cond, * args)
Clean arguments to:
1. Ensure all arguments are iterable (arrays of dimension at least one
2. If cond != True and size > 1, ravel(args[i]) where ravel(condition) is
   True, in 1D.
Return list of processed arguments.
Examples
--------
>>> import numpy as np
>>> rng = np.random.default_rng()
>>> A = rng.random((4, 5))
>>> B = 2
>>> C = rng.random((1, 5))
>>> cond = np.ones(A.shape)
>>> [A1, B1, C1] = argsreduce(cond, A, B, C)
>>> A1.shape
(4, 5)
>>> B1.shape
(1,)
>>> C1.shape
(1, 5)
>>> cond[2,:] = 0
>>> [A1, B1, C1] = argsreduce(cond, A, B, C)
>>> A1.shape
(15,)
>>> B1.shape
(1,)
>>> C1.shape
(15,)
Definition at line 559 of file _distn_infrastructure.py.
Referenced by scipy.stats._distn_infrastructure.rv_continuous._nnlf_and_penalty(), scipy.stats._distn_infrastructure.rv_continuous.cdf(), scipy.stats._distn_infrastructure.rv_discrete.cdf(), scipy.stats._distn_infrastructure.rv_generic.entropy(), scipy.stats._distn_infrastructure.rv_continuous.isf(), scipy.stats._distn_infrastructure.rv_discrete.isf(), scipy.stats._distn_infrastructure.rv_continuous.logcdf(), scipy.stats._distn_infrastructure.rv_discrete.logcdf(), scipy.stats._distn_infrastructure.rv_continuous.logpdf(), scipy.stats._distn_infrastructure.rv_discrete.logpmf(), scipy.stats._distn_infrastructure.rv_continuous.logsf(), scipy.stats._distn_infrastructure.rv_discrete.logsf(), scipy.stats._distn_infrastructure.rv_generic.moment(), scipy.stats._distn_infrastructure.rv_generic.nnlf(), scipy.stats._distn_infrastructure.rv_continuous.pdf(), scipy.stats._distn_infrastructure.rv_discrete.pmf(), scipy.stats._distn_infrastructure.rv_continuous.ppf(), scipy.stats._distn_infrastructure.rv_discrete.ppf(), scipy.stats._distn_infrastructure.rv_continuous.sf(), scipy.stats._distn_infrastructure.rv_discrete.sf(), and scipy.stats._distn_infrastructure.rv_generic.stats().
get_distribution_names()
scipy.stats._distn_infrastructure.get_distribution_names (namespace_pairs, rv_base_class)
Collect names of statistical distributions and their generators.
Parameters
----------
namespace_pairs : sequence
    A snapshot of (name, value) pairs in the namespace of a module.
rv_base_class : class
    The base class of random variable generator classes in a module.
Returns
-------
distn_names : list of strings
    Names of the statistical distributions.
distn_gen_names : list of strings
    Names of the generators of the statistical distributions.
    Note that these are not simply the names of the statistical
    distributions, with a _gen suffix added.
Definition at line 4016 of file _distn_infrastructure.py.
Variable Documentation
_doc_allmethods
str scipy.stats._distn_infrastructure._doc_allmethods protected
Initial value:
=  ''.join([docheaders['methods'], _doc_rvs, _doc_pdf,
                           _doc_logpdf, _doc_cdf, _doc_logcdf, _doc_sf,
                           _doc_logsf, _doc_ppf, _doc_isf, _doc_moment,
                           _doc_stats, _doc_entropy, _doc_fit,
                           _doc_expect, _doc_median,
                           _doc_mean, _doc_var, _doc_std, _doc_interval])
Definition at line 141 of file _distn_infrastructure.py.
_doc_cdf
str scipy.stats._distn_infrastructure._doc_cdf protected
Initial value:
=  """\
cdf(x, %(shapes)s, loc=0, scale=1)
    Cumulative distribution function.
"""
Definition at line 71 of file _distn_infrastructure.py.
_doc_default
str scipy.stats._distn_infrastructure._doc_default protected
Initial value:
=  ''.join([_doc_default_longsummary,
                        _doc_allmethods,
                        '\n',
                        _doc_default_example])
Definition at line 220 of file _distn_infrastructure.py.
_doc_default_before_notes
str scipy.stats._distn_infrastructure._doc_default_before_notes protected
Initial value:
=  ''.join([_doc_default_longsummary,
                                     _doc_allmethods])
Definition at line 225 of file _distn_infrastructure.py.
_doc_default_disc
str scipy.stats._distn_infrastructure._doc_default_disc protected
Initial value:
=  ''.join([docdict_discrete['longsummary'],
                             docdict_discrete['allmethods'],
                             docdict_discrete['frozennote'],
                             docdict_discrete['example']])
Definition at line 351 of file _distn_infrastructure.py.
_doc_default_discrete_example
str scipy.stats._distn_infrastructure._doc_default_discrete_example protected
Definition at line 293 of file _distn_infrastructure.py.
_doc_default_discrete_locscale
str scipy.stats._distn_infrastructure._doc_default_discrete_locscale protected
Initial value:
=  """\
The probability mass function above is defined in the "standardized" form.
To shift distribution use the ``loc`` parameter.
Specifically, ``%(name)s.pmf(k, %(shapes)s, loc)`` is identically
equivalent to ``%(name)s.pmf(k - loc, %(shapes)s)``.
"""
Definition at line 337 of file _distn_infrastructure.py.
_doc_default_example
str scipy.stats._distn_infrastructure._doc_default_example protected
Definition at line 162 of file _distn_infrastructure.py.
_doc_default_frozen_note
str scipy.stats._distn_infrastructure._doc_default_frozen_note protected
Initial value:
=  """
Alternatively, the object may be called (as a function) to fix the shape,
location, and scale parameters returning a "frozen" continuous RV object:
rv = %(name)s(%(shapes)s, loc=0, scale=1)
    - Frozen RV object with the same methods but holding the given shape,
      location, and scale fixed.
"""
Definition at line 154 of file _distn_infrastructure.py.
_doc_default_locscale
str scipy.stats._distn_infrastructure._doc_default_locscale protected
Initial value:
=  """\
The probability density above is defined in the "standardized" form. To shift
and/or scale the distribution use the ``loc`` and ``scale`` parameters.
Specifically, ``%(name)s.pdf(x, %(shapes)s, loc, scale)`` is identically
equivalent to ``%(name)s.pdf(y, %(shapes)s) / scale`` with
``y = (x - loc) / scale``. Note that shifting the location of a distribution
does not make it a "noncentral" distribution; noncentral generalizations of
some distributions are available in separate classes.
"""
Definition at line 210 of file _distn_infrastructure.py.
_doc_default_longsummary
str scipy.stats._distn_infrastructure._doc_default_longsummary protected
Initial value:
=  """\
As an instance of the `rv_continuous` class, `%(name)s` object inherits from it
a collection of generic methods (see below for the full list),
and completes them with details specific for this particular distribution.
"""
Definition at line 148 of file _distn_infrastructure.py.
_doc_disc_methods
list scipy.stats._distn_infrastructure._doc_disc_methods protected
Initial value:
=  ['rvs', 'pmf', 'logpmf', 'cdf', 'logcdf', 'sf', 'logsf',
                     'ppf', 'isf', 'stats', 'entropy', 'expect', 'median',
                     'mean', 'var', 'std', 'interval']
Definition at line 264 of file _distn_infrastructure.py.
_doc_disc_methods_err_varname
list scipy.stats._distn_infrastructure._doc_disc_methods_err_varname = ['cdf', 'logcdf', 'sf', 'logsf'] protected
Definition at line 270 of file _distn_infrastructure.py.
_doc_entropy
str scipy.stats._distn_infrastructure._doc_entropy protected
Initial value:
=  """\
entropy(%(shapes)s, loc=0, scale=1)
    (Differential) entropy of the RV.
"""
Definition at line 103 of file _distn_infrastructure.py.
_doc_expect
str scipy.stats._distn_infrastructure._doc_expect protected
Initial value:
=  """\
expect(func, args=(%(shapes_)s), loc=0, scale=1, lb=None, ub=None, conditional=False, **kwds)
    Expected value of a function (of one argument) with respect to the distribution.
"""
Definition at line 113 of file _distn_infrastructure.py.
_doc_expect_discrete
str scipy.stats._distn_infrastructure._doc_expect_discrete protected
Initial value:
=  """\
expect(func, args=(%(shapes_)s), loc=0, lb=None, ub=None, conditional=False)
    Expected value of a function (of one argument) with respect to the distribution.
"""
Definition at line 117 of file _distn_infrastructure.py.
_doc_fit
str scipy.stats._distn_infrastructure._doc_fit protected
Initial value:
=  """\
fit(data)
    Parameter estimates for generic data.
    See `scipy.stats.rv_continuous.fit <https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.rv_continuous.fit.html#scipy.stats.rv_continuous.fit>`__ for detailed documentation of the
    keyword arguments.
"""
Definition at line 107 of file _distn_infrastructure.py.
_doc_interval
str scipy.stats._distn_infrastructure._doc_interval protected
Initial value:
=  """\
interval(confidence, %(shapes)s, loc=0, scale=1)
    Confidence interval with equal areas around the median.
"""
Definition at line 137 of file _distn_infrastructure.py.
_doc_isf
str scipy.stats._distn_infrastructure._doc_isf protected
Initial value:
=  """\
isf(q, %(shapes)s, loc=0, scale=1)
    Inverse survival function (inverse of ``sf``).
"""
Definition at line 91 of file _distn_infrastructure.py.
_doc_logcdf
str scipy.stats._distn_infrastructure._doc_logcdf protected
Initial value:
=  """\
logcdf(x, %(shapes)s, loc=0, scale=1)
    Log of the cumulative distribution function.
"""
Definition at line 75 of file _distn_infrastructure.py.
_doc_logpdf
str scipy.stats._distn_infrastructure._doc_logpdf protected
Initial value:
=  """\
logpdf(x, %(shapes)s, loc=0, scale=1)
    Log of the probability density function.
"""
Definition at line 59 of file _distn_infrastructure.py.
_doc_logpmf
str scipy.stats._distn_infrastructure._doc_logpmf protected
Initial value:
=  """\
logpmf(k, %(shapes)s, loc=0, scale=1)
    Log of the probability mass function.
"""
Definition at line 67 of file _distn_infrastructure.py.
_doc_logsf
str scipy.stats._distn_infrastructure._doc_logsf protected
Initial value:
=  """\
logsf(x, %(shapes)s, loc=0, scale=1)
    Log of the survival function.
"""
Definition at line 83 of file _distn_infrastructure.py.
_doc_mean
str scipy.stats._distn_infrastructure._doc_mean protected
Initial value:
=  """\
mean(%(shapes)s, loc=0, scale=1)
    Mean of the distribution.
"""
Definition at line 125 of file _distn_infrastructure.py.
_doc_median
str scipy.stats._distn_infrastructure._doc_median protected
Initial value:
=  """\
median(%(shapes)s, loc=0, scale=1)
    Median of the distribution.
"""
Definition at line 121 of file _distn_infrastructure.py.
_doc_moment
str scipy.stats._distn_infrastructure._doc_moment protected
Initial value:
=  """\
moment(order, %(shapes)s, loc=0, scale=1)
    Non-central moment of the specified order.
"""
Definition at line 95 of file _distn_infrastructure.py.
_doc_pdf
str scipy.stats._distn_infrastructure._doc_pdf protected
Initial value:
=  """\
pdf(x, %(shapes)s, loc=0, scale=1)
    Probability density function.
"""
Definition at line 55 of file _distn_infrastructure.py.
_doc_pmf
str scipy.stats._distn_infrastructure._doc_pmf protected
Initial value:
=  """\
pmf(k, %(shapes)s, loc=0, scale=1)
    Probability mass function.
"""
Definition at line 63 of file _distn_infrastructure.py.
_doc_ppf
str scipy.stats._distn_infrastructure._doc_ppf protected
Initial value:
=  """\
ppf(q, %(shapes)s, loc=0, scale=1)
    Percent point function (inverse of ``cdf`` --- percentiles).
"""
Definition at line 87 of file _distn_infrastructure.py.
_doc_rvs
str scipy.stats._distn_infrastructure._doc_rvs protected
Initial value:
=  """\
rvs(%(shapes)s, loc=0, scale=1, size=1, random_state=None)
    Random variates.
"""
Definition at line 51 of file _distn_infrastructure.py.
_doc_sf
str scipy.stats._distn_infrastructure._doc_sf protected
Initial value:
=  """\
sf(x, %(shapes)s, loc=0, scale=1)
    Survival function  (also defined as ``1 - cdf``, but `sf` is sometimes more accurate).
"""
Definition at line 79 of file _distn_infrastructure.py.
_doc_stats
str scipy.stats._distn_infrastructure._doc_stats protected
Initial value:
=  """\
stats(%(shapes)s, loc=0, scale=1, moments='mv')
    Mean('m'), variance('v'), skew('s'), and/or kurtosis('k').
"""
Definition at line 99 of file _distn_infrastructure.py.
_doc_std
str scipy.stats._distn_infrastructure._doc_std protected
Initial value:
=  """\
std(%(shapes)s, loc=0, scale=1)
    Standard deviation of the distribution.
"""
Definition at line 133 of file _distn_infrastructure.py.
_doc_var
str scipy.stats._distn_infrastructure._doc_var protected
Initial value:
=  """\
var(%(shapes)s, loc=0, scale=1)
    Variance of the distribution.
"""
Definition at line 129 of file _distn_infrastructure.py.
docdict
dict scipy.stats._distn_infrastructure.docdict
Initial value:
=  {
    'rvs': _doc_rvs,
    'pdf': _doc_pdf,
    'logpdf': _doc_logpdf,
    'cdf': _doc_cdf,
    'logcdf': _doc_logcdf,
    'sf': _doc_sf,
    'logsf': _doc_logsf,
    'ppf': _doc_ppf,
    'isf': _doc_isf,
    'stats': _doc_stats,
    'entropy': _doc_entropy,
    'fit': _doc_fit,
    'moment': _doc_moment,
    'expect': _doc_expect,
    'interval': _doc_interval,
    'mean': _doc_mean,
    'std': _doc_std,
    'var': _doc_var,
    'median': _doc_median,
    'allmethods': _doc_allmethods,
    'longsummary': _doc_default_longsummary,
    'frozennote': _doc_default_frozen_note,
    'example': _doc_default_example,
    'default': _doc_default,
    'before_notes': _doc_default_before_notes,
    'after_notes': _doc_default_locscale
}
Definition at line 228 of file _distn_infrastructure.py.
docdict_discrete
dict scipy.stats._distn_infrastructure.docdict_discrete = docdict.copy()
Definition at line 259 of file _distn_infrastructure.py.
docheaders
dict scipy.stats._distn_infrastructure.docheaders
Initial value:
=  {'methods': ,
              'notes': ,
              'examples': }
Definition at line 47 of file _distn_infrastructure.py.
inc
scipy.stats._distn_infrastructure.inc
Definition at line 2960 of file _distn_infrastructure.py.
parse_arg_template
str scipy.stats._distn_infrastructure.parse_arg_template
Initial value:
=  """
def _parse_args(self, %(shape_arg_str)s %(locscale_in)s):
    return (%(shape_arg_str)s), %(locscale_out)s
def _parse_args_rvs(self, %(shape_arg_str)s %(locscale_in)s, size=None):
    return self._argcheck_rvs(%(shape_arg_str)s %(locscale_out)s, size=size)
def _parse_args_stats(self, %(shape_arg_str)s %(locscale_in)s, moments='mv'):
    return (%(shape_arg_str)s), %(locscale_out)s, moments
"""
Definition at line 614 of file _distn_infrastructure.py.