Code Cloning Analysis: pip._internal.utils.models.KeyBasedCompareMixin Class Reference
pip._internal.utils.models.KeyBasedCompareMixin Class Reference
Public Member Functions
None __init__ (self, Any key, Type["KeyBasedCompareMixin"] defining_class)
int __hash__ (self)
bool __lt__ (self, Any other)
bool __le__ (self, Any other)
bool __gt__ (self, Any other)
bool __ge__ (self, Any other)
bool __eq__ (self, Any other)
Protected Member Functions
bool _compare (self, Any other, Callable[[Any, Any], bool] method)
Protected Attributes
_compare_key = key
_defining_class = defining_class
Static Private Attributes
list __slots__ = ["_compare_key", "_defining_class"]
Detailed Description
Provides comparison capabilities that is based on a key
Definition at line 8 of file models.py.
Constructor & Destructor Documentation
__init__()
None pip._internal.utils.models.KeyBasedCompareMixin.__init__ (self, Any key, Type["KeyBasedCompareMixin"] defining_class)
Definition at line 13 of file models.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
__eq__()
bool pip._internal.utils.models.KeyBasedCompareMixin.__eq__ (self, Any other)
Definition at line 32 of file models.py.
Referenced by pip._vendor.msgpack.ext.Timestamp.__ne__(), and pip._vendor.distlib.version.Matcher.match().
__ge__()
bool pip._internal.utils.models.KeyBasedCompareMixin.__ge__ (self, Any other)
Definition at line 29 of file models.py.
__gt__()
bool pip._internal.utils.models.KeyBasedCompareMixin.__gt__ (self, Any other)
Definition at line 26 of file models.py.
__hash__()
int pip._internal.utils.models.KeyBasedCompareMixin.__hash__ (self)
Definition at line 17 of file models.py.
Referenced by pip._vendor.rich.style.Style.pick_first().
__le__()
bool pip._internal.utils.models.KeyBasedCompareMixin.__le__ (self, Any other)
Definition at line 23 of file models.py.
__lt__()
bool pip._internal.utils.models.KeyBasedCompareMixin.__lt__ (self, Any other)
Definition at line 20 of file models.py.
_compare()
bool pip._internal.utils.models.KeyBasedCompareMixin._compare (self, Any other, Callable[[Any, Any], bool] method) protected
Definition at line 35 of file models.py.
Member Data Documentation
__slots__
list pip._internal.utils.models.KeyBasedCompareMixin.__slots__ = ["_compare_key", "_defining_class"] static private
Definition at line 11 of file models.py.
_compare_key
pip._internal.utils.models.KeyBasedCompareMixin._compare_key = key protected
Definition at line 14 of file models.py.
_defining_class
pip._internal.utils.models.KeyBasedCompareMixin._defining_class = defining_class protected
Definition at line 15 of file models.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pip/_internal/utils/models.py