Code Cloning Analysis: numpy.lib.tests.test__datasource.TestDataSourceAbspath Class Reference
numpy.lib.tests.test__datasource.TestDataSourceAbspath Class Reference
Public Member Functions
setup_method (self)
teardown_method (self)
test_ValidHTTP (self)
test_ValidFile (self)
test_InvalidHTTP (self)
test_InvalidFile (self)
test_sandboxing (self)
test_windows_os_sep (self)
Public Attributes
tmpdir = os.path.abspath(mkdtemp())
ds = datasource.DataSource(self.tmpdir)
Detailed Description
Definition at line 188 of file test__datasource.py.
Member Function Documentation
setup_method()
numpy.lib.tests.test__datasource.TestDataSourceAbspath.setup_method (self)
Definition at line 189 of file test__datasource.py.
teardown_method()
numpy.lib.tests.test__datasource.TestDataSourceAbspath.teardown_method (self)
Definition at line 193 of file test__datasource.py.
test_InvalidFile()
numpy.lib.tests.test__datasource.TestDataSourceAbspath.test_InvalidFile (self)
Definition at line 217 of file test__datasource.py.
test_InvalidHTTP()
numpy.lib.tests.test__datasource.TestDataSourceAbspath.test_InvalidHTTP (self)
Definition at line 211 of file test__datasource.py.
test_sandboxing()
numpy.lib.tests.test__datasource.TestDataSourceAbspath.test_sandboxing (self)
Definition at line 226 of file test__datasource.py.
test_ValidFile()
numpy.lib.tests.test__datasource.TestDataSourceAbspath.test_ValidFile (self)
Definition at line 203 of file test__datasource.py.
test_ValidHTTP()
numpy.lib.tests.test__datasource.TestDataSourceAbspath.test_ValidHTTP (self)
Definition at line 197 of file test__datasource.py.
test_windows_os_sep()
numpy.lib.tests.test__datasource.TestDataSourceAbspath.test_windows_os_sep (self)
Definition at line 240 of file test__datasource.py.
Member Data Documentation
ds
numpy.lib.tests.test__datasource.TestDataSourceAbspath.ds = datasource.DataSource(self.tmpdir)
Definition at line 191 of file test__datasource.py.
Referenced by scipy.optimize._nonlin.LowRankMatrix.collapse(), scipy.optimize._nonlin.LowRankMatrix.matvec(), scipy.optimize._nonlin.LowRankMatrix.restart_reduce(), scipy.optimize._nonlin.LowRankMatrix.rmatvec(), scipy.optimize._nonlin.LowRankMatrix.rsolve(), scipy.optimize._nonlin.LowRankMatrix.simple_reduce(), scipy.optimize._nonlin.LowRankMatrix.solve(), and scipy.optimize._nonlin.LowRankMatrix.svd_reduce().
tmpdir
numpy.lib.tests.test__datasource.TestDataSourceAbspath.tmpdir = os.path.abspath(mkdtemp())
Definition at line 190 of file test__datasource.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/lib/tests/test__datasource.py