Code Cloning Analysis: matplotlib.tri._triinterpolate Namespace Reference
matplotlib.tri._triinterpolate Namespace Reference
Classes
class _DOF_estimator
class _DOF_estimator_geom
class _DOF_estimator_min_E
class _DOF_estimator_user
class _ReducedHCT_Element
class _Sparse_Matrix_coo
class CubicTriInterpolator
class LinearTriInterpolator
class TriInterpolator
Functions
_cg (A, b, x0=None, tol=1.e-10, maxiter=1000)
_safe_inv22_vectorized (M)
_pseudo_inv22sym_vectorized (M)
_scalar_vectorized (scalar, M)
_transpose_vectorized (M)
_roll_vectorized (M, roll_indices, axis)
_to_matrix_vectorized (M)
_extract_submatrices (M, block_indices, block_size, axis)
Variables
tuple __all__ = ('TriInterpolator', 'LinearTriInterpolator', 'CubicTriInterpolator')
Detailed Description
Interpolation inside triangular grids.
Function Documentation
_cg()
matplotlib.tri._triinterpolate._cg (A, b, x0 = None, tol = 1.e-10, maxiter = 1000) protected
Use Preconditioned Conjugate Gradient iteration to solve A x = b
A simple Jacobi (diagonal) preconditioner is used.
Parameters
----------
A : _Sparse_Matrix_coo
    *A* must have been compressed before by compress_csc or
    compress_csr method.
b : array
    Right hand side of the linear system.
x0 : array, optional
    Starting guess for the solution. Defaults to the zero vector.
tol : float, optional
    Tolerance to achieve. The algorithm terminates when the relative
    residual is below tol. Default is 1e-10.
maxiter : int, optional
    Maximum number of iterations.  Iteration will stop after *maxiter*
    steps even if the specified tolerance has not been achieved. Defaults
    to 1000.
Returns
-------
x : array
    The converged solution.
err : float
    The absolute error np.linalg.norm(A.dot(x) - b)
Definition at line 1283 of file _triinterpolate.py.
Referenced by matplotlib.tri._triinterpolate._DOF_estimator_min_E.compute_dz().
_extract_submatrices()
matplotlib.tri._triinterpolate._extract_submatrices (M, block_indices, block_size, axis) protected
Extract selected blocks of a matrices *M* depending on parameters
*block_indices* and *block_size*.
Returns the array of extracted matrices *Mres* so that ::
    M_res[..., ir, :] = M[(block_indices*block_size+ir), :]
Definition at line 1547 of file _triinterpolate.py.
Referenced by matplotlib.tri._triinterpolate._ReducedHCT_Element.get_d2Sidksij2(), and matplotlib.tri._triinterpolate._ReducedHCT_Element.get_function_derivatives().
_pseudo_inv22sym_vectorized()
matplotlib.tri._triinterpolate._pseudo_inv22sym_vectorized (M) protected
Inversion of arrays of (2, 2) SYMMETRIC matrices; returns the
(Moore-Penrose) pseudo-inverse for rank-deficient matrices.
In case M is of rank 1, we have M = trace(M) x P where P is the orthogonal
projection on Im(M), and we return trace(M)^-1 x P == M / trace(M)**2
In case M is of rank 0, we return the null matrix.
*M* : array of (2, 2) matrices to inverse, shape (n, 2, 2)
Definition at line 1429 of file _triinterpolate.py.
Referenced by matplotlib.tri._triinterpolate.CubicTriInterpolator._get_alpha_vec().
_roll_vectorized()
matplotlib.tri._triinterpolate._roll_vectorized (M, roll_indices, axis) protected
Roll an array of matrices along *axis* (0: rows, 1: columns) according to
an array of indices *roll_indices*.
Definition at line 1489 of file _triinterpolate.py.
Referenced by matplotlib.tri._triinterpolate._ReducedHCT_Element.get_d2Sidksij2(), matplotlib.tri._triinterpolate._ReducedHCT_Element.get_function_derivatives(), and matplotlib.tri._triinterpolate._ReducedHCT_Element.get_function_values().
_safe_inv22_vectorized()
matplotlib.tri._triinterpolate._safe_inv22_vectorized (M) protected
Inversion of arrays of (2, 2) matrices, returns 0 for rank-deficient
matrices.
*M* : array of (2, 2) matrices to inverse, shape (n, 2, 2)
Definition at line 1399 of file _triinterpolate.py.
Referenced by matplotlib.tri._triinterpolate._DOF_estimator_geom.compute_geom_grads(), matplotlib.tri._triinterpolate._ReducedHCT_Element.get_function_derivatives(), and matplotlib.tri._triinterpolate._ReducedHCT_Element.get_Hrot_from_J().
_scalar_vectorized()
matplotlib.tri._triinterpolate._scalar_vectorized (scalar, M) protected
Scalar product between scalars and matrices.
Definition at line 1475 of file _triinterpolate.py.
Referenced by matplotlib.tri._triinterpolate._ReducedHCT_Element.get_bending_matrices(), matplotlib.tri._triinterpolate._ReducedHCT_Element.get_d2Sidksij2(), matplotlib.tri._triinterpolate._ReducedHCT_Element.get_function_derivatives(), and matplotlib.tri._triinterpolate._ReducedHCT_Element.get_function_values().
_to_matrix_vectorized()
matplotlib.tri._triinterpolate._to_matrix_vectorized (M) protected
Build an array of matrices from individuals np.arrays of identical shapes.
Parameters
----------
M
    ncols-list of nrows-lists of shape sh.
Returns
-------
M_res : np.array of shape (sh, nrow, ncols)
    *M_res* satisfies ``M_res[..., i, j] = M[i][j]``.
Definition at line 1517 of file _triinterpolate.py.
Referenced by matplotlib.tri._triinterpolate.CubicTriInterpolator._compute_tri_eccentricities(), matplotlib.tri._triinterpolate.CubicTriInterpolator._get_alpha_vec(), matplotlib.tri._triinterpolate.CubicTriInterpolator._get_jacobian(), matplotlib.tri._triinterpolate._ReducedHCT_Element.get_d2Sidksij2(), matplotlib.tri._triinterpolate._DOF_estimator.get_dof_vec(), matplotlib.tri._triinterpolate._ReducedHCT_Element.get_function_derivatives(), matplotlib.tri._triinterpolate._ReducedHCT_Element.get_function_values(), matplotlib.tri._triinterpolate._ReducedHCT_Element.get_Hrot_from_J(), and matplotlib.tri._triinterpolate._ReducedHCT_Element.get_Kff_and_Ff().
_transpose_vectorized()
matplotlib.tri._triinterpolate._transpose_vectorized (M) protected
Transposition of an array of matrices *M*.
Definition at line 1482 of file _triinterpolate.py.
Referenced by matplotlib.tri._triinterpolate.CubicTriInterpolator._compute_tri_eccentricities(), matplotlib.tri._triinterpolate.CubicTriInterpolator._get_alpha_vec(), matplotlib.tri._triinterpolate._ReducedHCT_Element.get_bending_matrices(), matplotlib.tri._triinterpolate._ReducedHCT_Element.get_function_derivatives(), matplotlib.tri._triinterpolate._ReducedHCT_Element.get_function_hessians(), and matplotlib.tri._triinterpolate._ReducedHCT_Element.get_Kff_and_Ff().
Variable Documentation
__all__
tuple matplotlib.tri._triinterpolate.__all__ = ('TriInterpolator', 'LinearTriInterpolator', 'CubicTriInterpolator') private
Definition at line 12 of file _triinterpolate.py.