Code Cloning Analysis: pandas.io.sql Namespace Reference
pandas.io.sql Namespace Reference
Classes
class ADBCDatabase
class BaseEngine
class PandasSQL
class SQLAlchemyEngine
class SQLDatabase
class SQLiteDatabase
class SQLiteTable
class SQLTable
Functions
_process_parse_dates_argument (parse_dates)
_handle_date_column (col, bool utc=False, str|dict[str, Any]|None format=None)
_parse_date_columns (data_frame, parse_dates)
DataFrame _convert_arrays_to_dataframe (data, columns, bool coerce_float=True, DtypeBackend|Literal["numpy"] dtype_backend="numpy")
_wrap_result (data, columns, index_col=None, bool coerce_float=True, parse_dates=None, DtypeArg|None dtype=None, DtypeBackend|Literal["numpy"] dtype_backend="numpy")
DataFrame _wrap_result_adbc (DataFrame df, *, index_col=None, parse_dates=None, DtypeArg|None dtype=None, DtypeBackend|Literal["numpy"] dtype_backend="numpy")
execute (sql, con, params=None)
DataFrame read_sql_table (str table_name, con, schema=..., str|list[str]|None index_col=..., coerce_float=..., list[str]|dict[str, str]|None parse_dates=..., list[str]|None columns=..., None chunksize=..., DtypeBackend|lib.NoDefault dtype_backend=...)
Iterator[DataFrame] read_sql_table (str table_name, con, schema=..., str|list[str]|None index_col=..., coerce_float=..., list[str]|dict[str, str]|None parse_dates=..., list[str]|None columns=..., int chunksize=..., DtypeBackend|lib.NoDefault dtype_backend=...)
DataFrame|Iterator[DataFrame] read_sql_table (str table_name, con, str|None schema=None, str|list[str]|None index_col=None, bool coerce_float=True, list[str]|dict[str, str]|None parse_dates=None, list[str]|None columns=None, int|None chunksize=None, DtypeBackend|lib.NoDefault dtype_backend=lib.no_default)
DataFrame read_sql_query (sql, con, str|list[str]|None index_col=..., coerce_float=..., list[Any]|Mapping[str, Any]|None params=..., list[str]|dict[str, str]|None parse_dates=..., None chunksize=..., DtypeArg|None dtype=..., DtypeBackend|lib.NoDefault dtype_backend=...)
Iterator[DataFrame] read_sql_query (sql, con, str|list[str]|None index_col=..., coerce_float=..., list[Any]|Mapping[str, Any]|None params=..., list[str]|dict[str, str]|None parse_dates=..., int chunksize=..., DtypeArg|None dtype=..., DtypeBackend|lib.NoDefault dtype_backend=...)
DataFrame|Iterator[DataFrame] read_sql_query (sql, con, str|list[str]|None index_col=None, bool coerce_float=True, list[Any]|Mapping[str, Any]|None params=None, list[str]|dict[str, str]|None parse_dates=None, int|None chunksize=None, DtypeArg|None dtype=None, DtypeBackend|lib.NoDefault dtype_backend=lib.no_default)
DataFrame read_sql (sql, con, str|list[str]|None index_col=..., coerce_float=..., params=..., parse_dates=..., list[str] columns=..., None chunksize=..., DtypeBackend|lib.NoDefault dtype_backend=..., DtypeArg|None dtype=None)
Iterator[DataFrame] read_sql (sql, con, str|list[str]|None index_col=..., coerce_float=..., params=..., parse_dates=..., list[str] columns=..., int chunksize=..., DtypeBackend|lib.NoDefault dtype_backend=..., DtypeArg|None dtype=None)
DataFrame|Iterator[DataFrame] read_sql (sql, con, str|list[str]|None index_col=None, bool coerce_float=True, params=None, parse_dates=None, list[str]|None columns=None, int|None chunksize=None, DtypeBackend|lib.NoDefault dtype_backend=lib.no_default, DtypeArg|None dtype=None)
int|None to_sql (frame, str name, con, str|None schema=None, Literal["fail", "replace", "append"] if_exists="fail", bool index=True, IndexLabel|None index_label=None, int|None chunksize=None, DtypeArg|None dtype=None, Literal["multi"]|Callable|None method=None, str engine="auto", **engine_kwargs)
bool has_table (str table_name, con, str|None schema=None)
PandasSQL pandasSQL_builder (con, str|None schema=None, bool need_transaction=False)
BaseEngine get_engine (str engine)
_get_unicode_name (object name)
_get_valid_sqlite_name (object name)
str get_schema (frame, str name, keys=None, con=None, DtypeArg|None dtype=None, str|None schema=None)
Variables
bool table_exists = has_table
dict _SQL_TYPES
Detailed Description
Collection of query wrappers / abstractions to both facilitate data
retrieval and to reduce dependency on DB-specific API.
Function Documentation
_convert_arrays_to_dataframe()
DataFrame pandas.io.sql._convert_arrays_to_dataframe (data, columns, bool coerce_float = True, DtypeBackend | Literal["numpy"] dtype_backend = "numpy") protected
Definition at line 162 of file sql.py.
_get_unicode_name()
pandas.io.sql._get_unicode_name (object name) protected
Definition at line 2442 of file sql.py.
_get_valid_sqlite_name()
pandas.io.sql._get_valid_sqlite_name (object name) protected
Definition at line 2450 of file sql.py.
_handle_date_column()
pandas.io.sql._handle_date_column (col, bool utc = False, str | dict[str, Any] | None format = None) protected
Definition at line 107 of file sql.py.
_parse_date_columns()
pandas.io.sql._parse_date_columns (data_frame, parse_dates) protected
Force non-datetime columns to be read as such.
Supports both string formatted and integer timestamp columns.
Definition at line 141 of file sql.py.
References _process_parse_dates_argument().
Referenced by _wrap_result(), and _wrap_result_adbc().
_process_parse_dates_argument()
pandas.io.sql._process_parse_dates_argument (parse_dates) protected
Process parse_dates argument for read_sql functions
Definition at line 96 of file sql.py.
Referenced by pandas.io.sql.SQLTable._harmonize_columns(), and _parse_date_columns().
_wrap_result()
pandas.io.sql._wrap_result (data, columns, index_col = None, bool coerce_float = True, parse_dates = None, DtypeArg | None dtype = None, DtypeBackend | Literal["numpy"] dtype_backend = "numpy") protected
Wrap result set of a SQLAlchemy query in a DataFrame.
Definition at line 196 of file sql.py.
References _parse_date_columns().
Referenced by pandas.io.sql.SQLDatabase._query_iterator(), pandas.io.sql.SQLiteDatabase._query_iterator(), and pandas.io.sql.SQLDatabase.read_query().
_wrap_result_adbc()
DataFrame pandas.io.sql._wrap_result_adbc (DataFrame df, * , index_col = None, parse_dates = None, DtypeArg | None dtype = None, DtypeBackend | Literal["numpy"] dtype_backend = "numpy") protected
Wrap result set of a SQLAlchemy query in a DataFrame.
Definition at line 219 of file sql.py.
References _parse_date_columns().
Referenced by pandas.io.sql.ADBCDatabase.read_query(), and pandas.io.sql.ADBCDatabase.read_table().
execute()
pandas.io.sql.execute (sql, con, params = None)
Execute the given SQL query using the provided connection object.
Parameters
----------
sql : string
    SQL query to be executed.
con : SQLAlchemy connection or sqlite3 connection
    If a DBAPI2 object, only sqlite3 is supported.
params : list or tuple, optional, default: None
    List of parameters to pass to execute method.
Returns
-------
Results Iterable
Definition at line 239 of file sql.py.
References pandasSQL_builder().
Referenced by pandas.io.sql.SQLTable._query_iterator().
get_engine()
BaseEngine pandas.io.sql.get_engine (str engine)
return our implementation
Definition at line 1582 of file sql.py.
Referenced by pandas.io.sql.SQLDatabase.to_sql().
get_schema()
str pandas.io.sql.get_schema (frame, str name, keys = None, con = None, DtypeArg | None dtype = None, str | None schema = None)
Get the SQL db table schema for the given frame.
Parameters
----------
frame : DataFrame
name : str
    name of SQL table
keys : string or sequence, default: None
    columns to use a primary key
con: ADBC Connection, SQLAlchemy connectable, sqlite3 connection, default: None
    ADBC provides high performance I/O with native type support, where available.
    Using SQLAlchemy makes it possible to use any DB supported by that
    library
    If a DBAPI2 object, only sqlite3 is supported.
dtype : dict of column name to SQL type, default None
    Optional specifying the datatype for columns. The SQL type should
    be a SQLAlchemy type, or a string for sqlite3 fallback connection.
schema: str, default: None
    Optional specifying the schema to be used in creating the table.
Definition at line 2884 of file sql.py.
References pandasSQL_builder().
has_table()
bool pandas.io.sql.has_table (str table_name, con, str | None schema = None)
Check if DataBase has named table.
Parameters
----------
table_name: string
    Name of SQL table.
con: ADBC Connection, SQLAlchemy connectable, str, or sqlite3 connection
    ADBC provides high performance I/O with native type support, where available.
    Using SQLAlchemy makes it possible to use any DB supported by that
    library.
    If a DBAPI2 object, only sqlite3 is supported.
schema : string, default None
    Name of SQL schema in database to write to (if database flavor supports
    this). If None, use default schema (default).
Returns
-------
boolean
Definition at line 859 of file sql.py.
References pandasSQL_builder().
pandasSQL_builder()
PandasSQL pandas.io.sql.pandasSQL_builder (con, str | None schema = None, bool need_transaction = False)
Convenience function to return the correct PandasSQL subclass based on the
provided parameters.  Also creates a sqlalchemy connection and transaction
if necessary.
Definition at line 887 of file sql.py.
Referenced by execute(), get_schema(), has_table(), read_sql(), read_sql_query(), read_sql_table(), and to_sql().
read_sql() [1/3]
Iterator[DataFrame] pandas.io.sql.read_sql (sql, con, str | list[str] | None index_col = ..., coerce_float = ..., params = ..., parse_dates = ..., list[str] columns = ..., int chunksize = ..., DtypeBackend | lib.NoDefault dtype_backend = ..., DtypeArg | None dtype = None)
Definition at line 557 of file sql.py.
read_sql() [2/3]
DataFrame pandas.io.sql.read_sql (sql, con, str | list[str] | None index_col = ..., coerce_float = ..., params = ..., parse_dates = ..., list[str] columns = ..., None chunksize = ..., DtypeBackend | lib.NoDefault dtype_backend = ..., DtypeArg | None dtype = None)
Definition at line 541 of file sql.py.
read_sql() [3/3]
DataFrame | Iterator[DataFrame] pandas.io.sql.read_sql (sql, con, str | list[str] | None index_col = None, bool coerce_float = True, params = None, parse_dates = None, list[str] | None columns = None, int | None chunksize = None, DtypeBackend | lib.NoDefault dtype_backend = lib.no_default, DtypeArg | None dtype = None)
Read SQL query or database table into a DataFrame.
This function is a convenience wrapper around ``read_sql_table`` and
``read_sql_query`` (for backward compatibility). It will delegate
to the specific function depending on the provided input. A SQL query
will be routed to ``read_sql_query``, while a database table name will
be routed to ``read_sql_table``. Note that the delegated function might
have more specific notes about their functionality not listed here.
Parameters
----------
sql : str or SQLAlchemy Selectable (select or text object)
    SQL query to be executed or a table name.
con : ADBC Connection, SQLAlchemy connectable, str, or sqlite3 connection
    ADBC provides high performance I/O with native type support, where available.
    Using SQLAlchemy makes it possible to use any DB supported by that
    library. If a DBAPI2 object, only sqlite3 is supported. The user is responsible
    for engine disposal and connection closure for the ADBC connection and
    SQLAlchemy connectable; str connections are closed automatically. See
    `here <https://docs.sqlalchemy.org/en/20/core/connections.html>`_.
index_col : str or list of str, optional, default: None
    Column(s) to set as index(MultiIndex).
coerce_float : bool, default True
    Attempts to convert values of non-string, non-numeric objects (like
    decimal.Decimal) to floating point, useful for SQL result sets.
params : list, tuple or dict, optional, default: None
    List of parameters to pass to execute method.  The syntax used
    to pass parameters is database driver dependent. Check your
    database driver documentation for which of the five syntax styles,
    described in PEP 249's paramstyle, is supported.
    Eg. for psycopg2, uses %(name)s so use params={'name' : 'value'}.
parse_dates : list or dict, default: None
    - List of column names to parse as dates.
    - Dict of ``{column_name: format string}`` where format string is
      strftime compatible in case of parsing string times, or is one of
      (D, s, ns, ms, us) in case of parsing integer timestamps.
    - Dict of ``{column_name: arg dict}``, where the arg dict corresponds
      to the keyword arguments of :func:`pandas.to_datetime`
      Especially useful with databases without native Datetime support,
      such as SQLite.
columns : list, default: None
    List of column names to select from SQL table (only used when reading
    a table).
chunksize : int, default None
    If specified, return an iterator where `chunksize` is the
    number of rows to include in each chunk.
dtype_backend : {'numpy_nullable', 'pyarrow'}, default 'numpy_nullable'
    Back-end data type applied to the resultant :class:`DataFrame`
    (still experimental). Behaviour is as follows:
    * ``"numpy_nullable"``: returns nullable-dtype-backed :class:`DataFrame`
      (default).
    * ``"pyarrow"``: returns pyarrow-backed nullable :class:`ArrowDtype`
      DataFrame.
    .. versionadded:: 2.0
dtype : Type name or dict of columns
    Data type for data or columns. E.g. np.float64 or
    {'a': np.float64, 'b': np.int32, 'c': 'Int64'}.
    The argument is ignored if a table is passed instead of a query.
    .. versionadded:: 2.0.0
Returns
-------
DataFrame or Iterator[DataFrame]
See Also
--------
read_sql_table : Read SQL database table into a DataFrame.
read_sql_query : Read SQL query into a DataFrame.
Examples
--------
Read data from SQL via either a SQL query or a SQL tablename.
When using a SQLite database only SQL queries are accepted,
providing only the SQL tablename will result in an error.
>>> from sqlite3 import connect
>>> conn = connect(':memory:')
>>> df = pd.DataFrame(data=[[0, '10/11/12'], [1, '12/11/10']],
...                   columns=['int_column', 'date_column'])
>>> df.to_sql(name='test_data', con=conn)
2
>>> pd.read_sql('SELECT int_column, date_column FROM test_data', conn)
   int_column date_column
0           0    10/11/12
1           1    12/11/10
>>> pd.read_sql('test_data', 'postgres:///db_name')  # doctest:+SKIP
Apply date parsing to columns through the ``parse_dates`` argument
The ``parse_dates`` argument calls ``pd.to_datetime`` on the provided columns.
Custom argument values for applying ``pd.to_datetime`` on a column are specified
via a dictionary format:
>>> pd.read_sql('SELECT int_column, date_column FROM test_data',
...             conn,
...             parse_dates={"date_column": {"format": "%d/%m/%y"}})
   int_column date_column
0           0  2012-11-10
1           1  2010-11-12
.. versionadded:: 2.2.0
   pandas now supports reading via ADBC drivers
>>> from adbc_driver_postgresql import dbapi  # doctest:+SKIP
>>> with dbapi.connect('postgres:///db_name') as conn:  # doctest:+SKIP
...     pd.read_sql('SELECT int_column FROM test_data', conn)
   int_column
0           0
1           1
Definition at line 572 of file sql.py.
References pandasSQL_builder().
read_sql_query() [1/3]
Iterator[DataFrame] pandas.io.sql.read_sql_query (sql, con, str | list[str] | None index_col = ..., coerce_float = ..., list[Any] | Mapping[str, Any] | None params = ..., list[str] | dict[str, str] | None parse_dates = ..., int chunksize = ..., DtypeArg | None dtype = ..., DtypeBackend | lib.NoDefault dtype_backend = ...)
Definition at line 422 of file sql.py.
read_sql_query() [2/3]
DataFrame pandas.io.sql.read_sql_query (sql, con, str | list[str] | None index_col = ..., coerce_float = ..., list[Any] | Mapping[str, Any] | None params = ..., list[str] | dict[str, str] | None parse_dates = ..., None chunksize = ..., DtypeArg | None dtype = ..., DtypeBackend | lib.NoDefault dtype_backend = ...)
Definition at line 407 of file sql.py.
read_sql_query() [3/3]
DataFrame | Iterator[DataFrame] pandas.io.sql.read_sql_query (sql, con, str | list[str] | None index_col = None, bool coerce_float = True, list[Any] | Mapping[str, Any] | None params = None, list[str] | dict[str, str] | None parse_dates = None, int | None chunksize = None, DtypeArg | None dtype = None, DtypeBackend | lib.NoDefault dtype_backend = lib.no_default)
Read SQL query into a DataFrame.
Returns a DataFrame corresponding to the result set of the query
string. Optionally provide an `index_col` parameter to use one of the
columns as the index, otherwise default integer index will be used.
Parameters
----------
sql : str SQL query or SQLAlchemy Selectable (select or text object)
    SQL query to be executed.
con : SQLAlchemy connectable, str, or sqlite3 connection
    Using SQLAlchemy makes it possible to use any DB supported by that
    library. If a DBAPI2 object, only sqlite3 is supported.
index_col : str or list of str, optional, default: None
    Column(s) to set as index(MultiIndex).
coerce_float : bool, default True
    Attempts to convert values of non-string, non-numeric objects (like
    decimal.Decimal) to floating point. Useful for SQL result sets.
params : list, tuple or mapping, optional, default: None
    List of parameters to pass to execute method.  The syntax used
    to pass parameters is database driver dependent. Check your
    database driver documentation for which of the five syntax styles,
    described in PEP 249's paramstyle, is supported.
    Eg. for psycopg2, uses %(name)s so use params={'name' : 'value'}.
parse_dates : list or dict, default: None
    - List of column names to parse as dates.
    - Dict of ``{column_name: format string}`` where format string is
      strftime compatible in case of parsing string times, or is one of
      (D, s, ns, ms, us) in case of parsing integer timestamps.
    - Dict of ``{column_name: arg dict}``, where the arg dict corresponds
      to the keyword arguments of :func:`pandas.to_datetime`
      Especially useful with databases without native Datetime support,
      such as SQLite.
chunksize : int, default None
    If specified, return an iterator where `chunksize` is the number of
    rows to include in each chunk.
dtype : Type name or dict of columns
    Data type for data or columns. E.g. np.float64 or
    {'a': np.float64, 'b': np.int32, 'c': 'Int64'}.
    .. versionadded:: 1.3.0
dtype_backend : {'numpy_nullable', 'pyarrow'}, default 'numpy_nullable'
    Back-end data type applied to the resultant :class:`DataFrame`
    (still experimental). Behaviour is as follows:
    * ``"numpy_nullable"``: returns nullable-dtype-backed :class:`DataFrame`
      (default).
    * ``"pyarrow"``: returns pyarrow-backed nullable :class:`ArrowDtype`
      DataFrame.
    .. versionadded:: 2.0
Returns
-------
DataFrame or Iterator[DataFrame]
See Also
--------
read_sql_table : Read SQL database table into a DataFrame.
read_sql : Read SQL query or database table into a DataFrame.
Notes
-----
Any datetime values with time zone information parsed via the `parse_dates`
parameter will be converted to UTC.
Examples
--------
>>> from sqlalchemy import create_engine  # doctest: +SKIP
>>> engine = create_engine("sqlite:///database.db")  # doctest: +SKIP
>>> with engine.connect() as conn, conn.begin():  # doctest: +SKIP
...     data = pd.read_sql_table("data", conn)  # doctest: +SKIP
Definition at line 436 of file sql.py.
References pandasSQL_builder().
read_sql_table() [1/3]
Iterator[DataFrame] pandas.io.sql.read_sql_table (str table_name, con, schema = ..., str | list[str] | None index_col = ..., coerce_float = ..., list[str] | dict[str, str] | None parse_dates = ..., list[str] | None columns = ..., int chunksize = ..., DtypeBackend | lib.NoDefault dtype_backend = ...)
Definition at line 290 of file sql.py.
read_sql_table() [2/3]
DataFrame pandas.io.sql.read_sql_table (str table_name, con, schema = ..., str | list[str] | None index_col = ..., coerce_float = ..., list[str] | dict[str, str] | None parse_dates = ..., list[str] | None columns = ..., None chunksize = ..., DtypeBackend | lib.NoDefault dtype_backend = ...)
Definition at line 275 of file sql.py.
read_sql_table() [3/3]
DataFrame | Iterator[DataFrame] pandas.io.sql.read_sql_table (str table_name, con, str | None schema = None, str | list[str] | None index_col = None, bool coerce_float = True, list[str] | dict[str, str] | None parse_dates = None, list[str] | None columns = None, int | None chunksize = None, DtypeBackend | lib.NoDefault dtype_backend = lib.no_default)
Read SQL database table into a DataFrame.
Given a table name and a SQLAlchemy connectable, returns a DataFrame.
This function does not support DBAPI connections.
Parameters
----------
table_name : str
    Name of SQL table in database.
con : SQLAlchemy connectable or str
    A database URI could be provided as str.
    SQLite DBAPI connection mode not supported.
schema : str, default None
    Name of SQL schema in database to query (if database flavor
    supports this). Uses default schema if None (default).
index_col : str or list of str, optional, default: None
    Column(s) to set as index(MultiIndex).
coerce_float : bool, default True
    Attempts to convert values of non-string, non-numeric objects (like
    decimal.Decimal) to floating point. Can result in loss of Precision.
parse_dates : list or dict, default None
    - List of column names to parse as dates.
    - Dict of ``{column_name: format string}`` where format string is
      strftime compatible in case of parsing string times or is one of
      (D, s, ns, ms, us) in case of parsing integer timestamps.
    - Dict of ``{column_name: arg dict}``, where the arg dict corresponds
      to the keyword arguments of :func:`pandas.to_datetime`
      Especially useful with databases without native Datetime support,
      such as SQLite.
columns : list, default None
    List of column names to select from SQL table.
chunksize : int, default None
    If specified, returns an iterator where `chunksize` is the number of
    rows to include in each chunk.
dtype_backend : {'numpy_nullable', 'pyarrow'}, default 'numpy_nullable'
    Back-end data type applied to the resultant :class:`DataFrame`
    (still experimental). Behaviour is as follows:
    * ``"numpy_nullable"``: returns nullable-dtype-backed :class:`DataFrame`
      (default).
    * ``"pyarrow"``: returns pyarrow-backed nullable :class:`ArrowDtype`
      DataFrame.
    .. versionadded:: 2.0
Returns
-------
DataFrame or Iterator[DataFrame]
    A SQL table is returned as two-dimensional data structure with labeled
    axes.
See Also
--------
read_sql_query : Read SQL query into a DataFrame.
read_sql : Read SQL query or database table into a DataFrame.
Notes
-----
Any datetime values with time zone information will be converted to UTC.
Examples
--------
>>> pd.read_sql_table('table_name', 'postgres:///db_name')  # doctest:+SKIP
Definition at line 304 of file sql.py.
References pandasSQL_builder().
to_sql()
int | None pandas.io.sql.to_sql (frame, str name, con, str | None schema = None, Literal["fail", "replace", "append"] if_exists = "fail", bool index = True, IndexLabel | None index_label = None, int | None chunksize = None, DtypeArg | None dtype = None, Literal["multi"] | Callable | None method = None, str engine = "auto", ** engine_kwargs)
Write records stored in a DataFrame to a SQL database.
Parameters
----------
frame : DataFrame, Series
name : str
    Name of SQL table.
con : ADBC Connection, SQLAlchemy connectable, str, or sqlite3 connection
    or sqlite3 DBAPI2 connection
    ADBC provides high performance I/O with native type support, where available.
    Using SQLAlchemy makes it possible to use any DB supported by that
    library.
    If a DBAPI2 object, only sqlite3 is supported.
schema : str, optional
    Name of SQL schema in database to write to (if database flavor
    supports this). If None, use default schema (default).
if_exists : {'fail', 'replace', 'append'}, default 'fail'
    - fail: If table exists, do nothing.
    - replace: If table exists, drop it, recreate it, and insert data.
    - append: If table exists, insert data. Create if does not exist.
index : bool, default True
    Write DataFrame index as a column.
index_label : str or sequence, optional
    Column label for index column(s). If None is given (default) and
    `index` is True, then the index names are used.
    A sequence should be given if the DataFrame uses MultiIndex.
chunksize : int, optional
    Specify the number of rows in each batch to be written at a time.
    By default, all rows will be written at once.
dtype : dict or scalar, optional
    Specifying the datatype for columns. If a dictionary is used, the
    keys should be the column names and the values should be the
    SQLAlchemy types or strings for the sqlite3 fallback mode. If a
    scalar is provided, it will be applied to all columns.
method : {None, 'multi', callable}, optional
    Controls the SQL insertion clause used:
    - None : Uses standard SQL ``INSERT`` clause (one per row).
    - ``'multi'``: Pass multiple values in a single ``INSERT`` clause.
    - callable with signature ``(pd_table, conn, keys, data_iter) -> int | None``.
    Details and a sample callable implementation can be found in the
    section :ref:`insert method <io.sql.method>`.
engine : {'auto', 'sqlalchemy'}, default 'auto'
    SQL engine library to use. If 'auto', then the option
    ``io.sql.engine`` is used. The default ``io.sql.engine``
    behavior is 'sqlalchemy'
    .. versionadded:: 1.3.0
**engine_kwargs
    Any additional kwargs are passed to the engine.
Returns
-------
None or int
    Number of rows affected by to_sql. None is returned if the callable
    passed into ``method`` does not return an integer number of rows.
    .. versionadded:: 1.4.0
Notes
-----
The returned rows affected is the sum of the ``rowcount`` attribute of ``sqlite3.Cursor``
or SQLAlchemy connectable. If using ADBC the returned rows are the result
of ``Cursor.adbc_ingest``. The returned value may not reflect the exact number of written
rows as stipulated in the
`sqlite3 <https://docs.python.org/3/library/sqlite3.html#sqlite3.Cursor.rowcount>`__ or
`SQLAlchemy <https://docs.sqlalchemy.org/en/14/core/connections.html#sqlalchemy.engine.BaseCursorResult.rowcount>`__
Definition at line 748 of file sql.py.
References pandasSQL_builder().
Variable Documentation
_SQL_TYPES
dict pandas.io.sql._SQL_TYPES protected
Initial value:
=  {
    "string": "TEXT",
    "floating": "REAL",
    "integer": "INTEGER",
    "datetime": "TIMESTAMP",
    "date": "DATE",
    "time": "TIME",
    "boolean": "INTEGER",
}
Definition at line 2431 of file sql.py.
table_exists
bool pandas.io.sql.table_exists = has_table
Definition at line 884 of file sql.py.