Code Cloning Analysis: pandas.tests.reshape.test_get_dummies.TestGetDummies Class Reference
pandas.tests.reshape.test_get_dummies.TestGetDummies Class Reference
Public Member Functions
df (self)
dtype (self, request)
sparse (self, request)
effective_dtype (self, dtype)
test_get_dummies_raises_on_dtype_object (self, df)
test_get_dummies_basic (self, sparse, dtype)
test_get_dummies_basic_types (self, sparse, dtype, using_infer_string)
test_get_dummies_just_na (self, sparse)
test_get_dummies_include_na (self, sparse, dtype)
test_get_dummies_unicode (self, sparse)
test_dataframe_dummies_all_obj (self, df, sparse)
test_dataframe_dummies_string_dtype (self, df, any_string_dtype)
test_dataframe_dummies_mix_default (self, df, sparse, dtype)
test_dataframe_dummies_prefix_list (self, df, sparse)
test_dataframe_dummies_prefix_str (self, df, sparse)
test_dataframe_dummies_subset (self, df, sparse)
test_dataframe_dummies_prefix_sep (self, df, sparse)
test_dataframe_dummies_prefix_bad_length (self, df, sparse)
test_dataframe_dummies_prefix_sep_bad_length (self, df, sparse)
test_dataframe_dummies_prefix_dict (self, sparse)
test_dataframe_dummies_with_na (self, df, sparse, dtype)
test_dataframe_dummies_with_categorical (self, df, sparse, dtype)
test_dataframe_dummies_unicode (self, get_dummies_kwargs, expected)
test_get_dummies_basic_drop_first (self, sparse)
test_get_dummies_basic_drop_first_one_level (self, sparse)
test_get_dummies_basic_drop_first_NA (self, sparse)
test_dataframe_dummies_drop_first (self, df, sparse)
test_dataframe_dummies_drop_first_with_categorical (self, df, sparse, dtype)
test_dataframe_dummies_drop_first_with_na (self, df, sparse)
test_get_dummies_int_int (self)
test_get_dummies_int_df (self, dtype)
test_dataframe_dummies_preserve_categorical_dtype (self, dtype, ordered)
test_get_dummies_dont_sparsify_all_columns (self, sparse)
test_get_dummies_duplicate_columns (self, df)
test_get_dummies_all_sparse (self)
test_get_dummies_with_string_values (self, values)
test_get_dummies_ea_dtype_series (self, any_numeric_ea_and_arrow_dtype)
test_get_dummies_ea_dtype_dataframe (self, any_numeric_ea_and_arrow_dtype)
test_get_dummies_ea_dtype (self, dtype_type, string_dtype_no_object)
test_get_dummies_arrow_dtype (self)
Detailed Description
Definition at line 33 of file test_get_dummies.py.
Member Function Documentation
df()
pandas.tests.reshape.test_get_dummies.TestGetDummies.df (self)
Definition at line 35 of file test_get_dummies.py.
Referenced by scipy.stats._stats_py.TtestResult.confidence_interval().
dtype()
pandas.tests.reshape.test_get_dummies.TestGetDummies.dtype (self, request)
Definition at line 39 of file test_get_dummies.py.
Referenced by pandas.core.arrays.base.ExtensionScalarOpsMixin._create_method(), scipy.sparse._index.IndexMixin._getcol(), pandas.core.generic.NDFrame._inplace_method(), scipy.sparse._index.IndexMixin._raise_on_1d_array_slice(), pandas.core.strings.object_array.ObjectStringArrayMixin._str_map(), numpy.matrixlib.defmatrix.matrix.H(), numpy.core.records.record.pprint(), pandas.core.frame.DataFrame.quantile(), and pandas.core.generic.NDFrame.rank().
effective_dtype()
pandas.tests.reshape.test_get_dummies.TestGetDummies.effective_dtype (self, dtype)
Definition at line 48 of file test_get_dummies.py.
sparse()
pandas.tests.reshape.test_get_dummies.TestGetDummies.sparse (self, request)
Definition at line 43 of file test_get_dummies.py.
test_dataframe_dummies_all_obj()
pandas.tests.reshape.test_get_dummies.TestGetDummies.test_dataframe_dummies_all_obj (self, df, sparse)
Definition at line 198 of file test_get_dummies.py.
test_dataframe_dummies_drop_first()
pandas.tests.reshape.test_get_dummies.TestGetDummies.test_dataframe_dummies_drop_first (self, df, sparse)
Definition at line 540 of file test_get_dummies.py.
test_dataframe_dummies_drop_first_with_categorical()
pandas.tests.reshape.test_get_dummies.TestGetDummies.test_dataframe_dummies_drop_first_with_categorical (self, df, sparse, dtype)
Definition at line 548 of file test_get_dummies.py.
test_dataframe_dummies_drop_first_with_na()
pandas.tests.reshape.test_get_dummies.TestGetDummies.test_dataframe_dummies_drop_first_with_na (self, df, sparse)
Definition at line 562 of file test_get_dummies.py.
test_dataframe_dummies_mix_default()
pandas.tests.reshape.test_get_dummies.TestGetDummies.test_dataframe_dummies_mix_default (self, df, sparse, dtype)
Definition at line 235 of file test_get_dummies.py.
test_dataframe_dummies_prefix_bad_length()
pandas.tests.reshape.test_get_dummies.TestGetDummies.test_dataframe_dummies_prefix_bad_length (self, df, sparse)
Definition at line 351 of file test_get_dummies.py.
test_dataframe_dummies_prefix_dict()
pandas.tests.reshape.test_get_dummies.TestGetDummies.test_dataframe_dummies_prefix_dict (self, sparse)
Definition at line 367 of file test_get_dummies.py.
test_dataframe_dummies_prefix_list()
pandas.tests.reshape.test_get_dummies.TestGetDummies.test_dataframe_dummies_prefix_list (self, df, sparse)
Definition at line 258 of file test_get_dummies.py.
test_dataframe_dummies_prefix_sep()
pandas.tests.reshape.test_get_dummies.TestGetDummies.test_dataframe_dummies_prefix_sep (self, df, sparse)
Definition at line 325 of file test_get_dummies.py.
test_dataframe_dummies_prefix_sep_bad_length()
pandas.tests.reshape.test_get_dummies.TestGetDummies.test_dataframe_dummies_prefix_sep_bad_length (self, df, sparse)
Definition at line 359 of file test_get_dummies.py.
test_dataframe_dummies_prefix_str()
pandas.tests.reshape.test_get_dummies.TestGetDummies.test_dataframe_dummies_prefix_str (self, df, sparse)
Definition at line 278 of file test_get_dummies.py.
test_dataframe_dummies_preserve_categorical_dtype()
pandas.tests.reshape.test_get_dummies.TestGetDummies.test_dataframe_dummies_preserve_categorical_dtype (self, dtype, ordered)
Definition at line 621 of file test_get_dummies.py.
test_dataframe_dummies_string_dtype()
pandas.tests.reshape.test_get_dummies.TestGetDummies.test_dataframe_dummies_string_dtype (self, df, any_string_dtype)
Definition at line 217 of file test_get_dummies.py.
test_dataframe_dummies_subset()
pandas.tests.reshape.test_get_dummies.TestGetDummies.test_dataframe_dummies_subset (self, df, sparse)
Definition at line 307 of file test_get_dummies.py.
test_dataframe_dummies_unicode()
pandas.tests.reshape.test_get_dummies.TestGetDummies.test_dataframe_dummies_unicode (self, get_dummies_kwargs, expected)
Definition at line 471 of file test_get_dummies.py.
test_dataframe_dummies_with_categorical()
pandas.tests.reshape.test_get_dummies.TestGetDummies.test_dataframe_dummies_with_categorical (self, df, sparse, dtype)
Definition at line 423 of file test_get_dummies.py.
test_dataframe_dummies_with_na()
pandas.tests.reshape.test_get_dummies.TestGetDummies.test_dataframe_dummies_with_na (self, df, sparse, dtype)
Definition at line 389 of file test_get_dummies.py.
test_get_dummies_all_sparse()
pandas.tests.reshape.test_get_dummies.TestGetDummies.test_get_dummies_all_sparse (self)
Definition at line 661 of file test_get_dummies.py.
test_get_dummies_arrow_dtype()
pandas.tests.reshape.test_get_dummies.TestGetDummies.test_get_dummies_arrow_dtype (self)
Definition at line 723 of file test_get_dummies.py.
test_get_dummies_basic()
pandas.tests.reshape.test_get_dummies.TestGetDummies.test_get_dummies_basic (self, sparse, dtype)
Definition at line 58 of file test_get_dummies.py.
test_get_dummies_basic_drop_first()
pandas.tests.reshape.test_get_dummies.TestGetDummies.test_get_dummies_basic_drop_first (self, sparse)
Definition at line 477 of file test_get_dummies.py.
test_get_dummies_basic_drop_first_NA()
pandas.tests.reshape.test_get_dummies.TestGetDummies.test_get_dummies_basic_drop_first_NA (self, sparse)
Definition at line 516 of file test_get_dummies.py.
test_get_dummies_basic_drop_first_one_level()
pandas.tests.reshape.test_get_dummies.TestGetDummies.test_get_dummies_basic_drop_first_one_level (self, sparse)
Definition at line 498 of file test_get_dummies.py.
test_get_dummies_basic_types()
pandas.tests.reshape.test_get_dummies.TestGetDummies.test_get_dummies_basic_types (self, sparse, dtype, using_infer_string)
Definition at line 82 of file test_get_dummies.py.
test_get_dummies_dont_sparsify_all_columns()
pandas.tests.reshape.test_get_dummies.TestGetDummies.test_get_dummies_dont_sparsify_all_columns (self, sparse)
Definition at line 635 of file test_get_dummies.py.
test_get_dummies_duplicate_columns()
pandas.tests.reshape.test_get_dummies.TestGetDummies.test_get_dummies_duplicate_columns (self, df)
Definition at line 643 of file test_get_dummies.py.
test_get_dummies_ea_dtype()
pandas.tests.reshape.test_get_dummies.TestGetDummies.test_get_dummies_ea_dtype (self, dtype_type, string_dtype_no_object)
Definition at line 711 of file test_get_dummies.py.
test_get_dummies_ea_dtype_dataframe()
pandas.tests.reshape.test_get_dummies.TestGetDummies.test_get_dummies_ea_dtype_dataframe (self, any_numeric_ea_and_arrow_dtype)
Definition at line 700 of file test_get_dummies.py.
test_get_dummies_ea_dtype_series()
pandas.tests.reshape.test_get_dummies.TestGetDummies.test_get_dummies_ea_dtype_series (self, any_numeric_ea_and_arrow_dtype)
Definition at line 690 of file test_get_dummies.py.
test_get_dummies_include_na()
pandas.tests.reshape.test_get_dummies.TestGetDummies.test_get_dummies_include_na (self, sparse, dtype)
Definition at line 150 of file test_get_dummies.py.
test_get_dummies_int_df()
pandas.tests.reshape.test_get_dummies.TestGetDummies.test_get_dummies_int_df (self, dtype)
Definition at line 602 of file test_get_dummies.py.
test_get_dummies_int_int()
pandas.tests.reshape.test_get_dummies.TestGetDummies.test_get_dummies_int_int (self)
Definition at line 589 of file test_get_dummies.py.
test_get_dummies_just_na()
pandas.tests.reshape.test_get_dummies.TestGetDummies.test_get_dummies_just_na (self, sparse)
Definition at line 133 of file test_get_dummies.py.
test_get_dummies_raises_on_dtype_object()
pandas.tests.reshape.test_get_dummies.TestGetDummies.test_get_dummies_raises_on_dtype_object (self, df)
Definition at line 53 of file test_get_dummies.py.
test_get_dummies_unicode()
pandas.tests.reshape.test_get_dummies.TestGetDummies.test_get_dummies_unicode (self, sparse)
Definition at line 185 of file test_get_dummies.py.
test_get_dummies_with_string_values()
pandas.tests.reshape.test_get_dummies.TestGetDummies.test_get_dummies_with_string_values (self, values)
Definition at line 674 of file test_get_dummies.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/tests/reshape/test_get_dummies.py