Code Cloning Analysis: matplotlib.tests.test_units.Quantity Class Reference
matplotlib.tests.test_units.Quantity Class Reference
Public Member Functions
__init__ (self, data, units)
to (self, new_units)
__copy__ (self)
__getattr__ (self, attr)
__getitem__ (self, item)
__array__ (self)
Public Attributes
magnitude = data
units = units
Detailed Description
Definition at line 16 of file test_units.py.
Constructor & Destructor Documentation
__init__()
matplotlib.tests.test_units.Quantity.__init__ (self, data, units)
Definition at line 17 of file test_units.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__array__()
matplotlib.tests.test_units.Quantity.__array__ (self)
Definition at line 43 of file test_units.py.
Referenced by numpy.matrixlib.defmatrix.matrix.A(), numpy.matrixlib.defmatrix.matrix.A1(), numpy.core.defchararray.chararray.argsort(), numpy.matrixlib.defmatrix.matrix.tolist(), and numpy.ma.mrecords.MaskedRecords.view().
__copy__()
matplotlib.tests.test_units.Quantity.__copy__ (self)
Definition at line 31 of file test_units.py.
__getattr__()
matplotlib.tests.test_units.Quantity.__getattr__ (self, attr)
Definition at line 34 of file test_units.py.
__getitem__()
matplotlib.tests.test_units.Quantity.__getitem__ (self, item)
Definition at line 37 of file test_units.py.
to()
matplotlib.tests.test_units.Quantity.to (self, new_units)
Definition at line 21 of file test_units.py.
Member Data Documentation
magnitude
matplotlib.tests.test_units.Quantity.magnitude = data
Definition at line 18 of file test_units.py.
units
matplotlib.tests.test_units.Quantity.units = units
Definition at line 19 of file test_units.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/tests/test_units.py