Code Cloning Analysis: fontTools.varLib.merger.Merger Class Reference
fontTools.varLib.merger.Merger Class Reference
Public Member Functions
__init__ (self, font=None)
merger (celf, clazzes, attrs=(None,))
mergersFor (celf, thing, _default={})
mergeObjects (self, out, lst, exclude=())
mergeLists (self, out, lst)
mergeThings (self, out, lst)
mergeTables (self, font, master_ttfs, tableTags)
Public Attributes
font = font
ttfs = None
Detailed Description
Definition at line 46 of file merger.py.
Constructor & Destructor Documentation
__init__()
fontTools.varLib.merger.Merger.__init__ (self, font = None)
Definition at line 47 of file merger.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
mergeLists()
fontTools.varLib.merger.Merger.mergeLists (self, out, lst)
Definition at line 120 of file merger.py.
Referenced by fontTools.varLib.merger.COLRVariationMerger.expandPaintColrLayers().
mergeObjects()
fontTools.varLib.merger.Merger.mergeObjects (self, out, lst, exclude = ())
Definition at line 95 of file merger.py.
merger()
fontTools.varLib.merger.Merger.merger (celf, clazzes, attrs = (None,))
Definition at line 53 of file merger.py.
mergersFor()
fontTools.varLib.merger.Merger.mergersFor (celf, thing, _default = {})
Definition at line 81 of file merger.py.
mergeTables()
fontTools.varLib.merger.Merger.mergeTables (self, font, master_ttfs, tableTags)
Definition at line 151 of file merger.py.
mergeThings()
fontTools.varLib.merger.Merger.mergeThings (self, out, lst)
Definition at line 130 of file merger.py.
Member Data Documentation
font
fontTools.varLib.merger.Merger.font = font
Definition at line 48 of file merger.py.
Referenced by fontTools.varLib.merger.COLRVariationMerger.expandPaintColrLayers(), matplotlib.dviread.Text.font_size(), matplotlib._mathtext.ParserState.get_current_underline_thickness(), matplotlib._mathtext.Char.get_kerning(), PIL.ImageDraw.ImageDraw.getfont(), matplotlib._mathtext.Accent.render(), and matplotlib._mathtext.Char.render().
ttfs
fontTools.varLib.merger.Merger.ttfs = None
Definition at line 50 of file merger.py.
Referenced by fontTools.varLib.merger.COLRVariationMerger.expandPaintColrLayers().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/varLib/merger.py