Code Cloning Analysis: numpy.core.tests.test_api Namespace Reference
numpy.core.tests.test_api Namespace Reference
Functions
test_array_array ()
test_array_impossible_casts (array)
test_fastCopyAndTranspose (a)
test_array_astype ()
test_array_astype_to_string_discovery_empty (dt)
test_array_astype_to_void (dt)
test_object_array_astype_to_void ()
test_array_astype_warning (t)
test_string_to_boolean_cast (dtype, out_dtype)
test_string_to_boolean_cast_errors (dtype, out_dtype)
test_string_to_complex_cast (str_type, scalar_type)
test_none_to_nan_cast (dtype)
test_copyto_fromscalar ()
test_copyto ()
test_copyto_permut ()
test_copy_order ()
test_contiguous_flags ()
test_broadcast_arrays ()
test_full_from_list (shape, fill_value, expected_output)
test_astype_copyflag ()
Function Documentation
test_array_array()
numpy.core.tests.test_api.test_array_array ()
Definition at line 12 of file test_api.py.
test_array_astype()
numpy.core.tests.test_api.test_array_astype ()
Definition at line 178 of file test_api.py.
test_array_astype_to_string_discovery_empty()
numpy.core.tests.test_api.test_array_astype_to_string_discovery_empty (dt)
Definition at line 291 of file test_api.py.
test_array_astype_to_void()
numpy.core.tests.test_api.test_array_astype_to_void (dt)
Definition at line 305 of file test_api.py.
test_array_astype_warning()
numpy.core.tests.test_api.test_array_astype_warning (t)
Definition at line 319 of file test_api.py.
test_array_impossible_casts()
numpy.core.tests.test_api.test_array_impossible_casts (array)
Definition at line 153 of file test_api.py.
test_astype_copyflag()
numpy.core.tests.test_api.test_astype_copyflag ()
Definition at line 589 of file test_api.py.
test_broadcast_arrays()
numpy.core.tests.test_api.test_broadcast_arrays ()
Definition at line 574 of file test_api.py.
test_contiguous_flags()
numpy.core.tests.test_api.test_contiguous_flags ()
Definition at line 542 of file test_api.py.
test_copy_order()
numpy.core.tests.test_api.test_copy_order ()
Definition at line 481 of file test_api.py.
test_copyto()
numpy.core.tests.test_api.test_copyto ()
Definition at line 392 of file test_api.py.
test_copyto_fromscalar()
numpy.core.tests.test_api.test_copyto_fromscalar ()
Definition at line 375 of file test_api.py.
test_copyto_permut()
numpy.core.tests.test_api.test_copyto_permut ()
Definition at line 428 of file test_api.py.
test_fastCopyAndTranspose()
numpy.core.tests.test_api.test_fastCopyAndTranspose (a)
Definition at line 171 of file test_api.py.
test_full_from_list()
numpy.core.tests.test_api.test_full_from_list (shape, fill_value, expected_output)
Definition at line 585 of file test_api.py.
test_none_to_nan_cast()
numpy.core.tests.test_api.test_none_to_nan_cast (dtype)
Definition at line 365 of file test_api.py.
test_object_array_astype_to_void()
numpy.core.tests.test_api.test_object_array_astype_to_void ()
Definition at line 310 of file test_api.py.
test_string_to_boolean_cast()
numpy.core.tests.test_api.test_string_to_boolean_cast (dtype, out_dtype)
Currently, for `astype` strings are cast to booleans effectively by
calling `bool(int(string)`. This is not consistent (see gh-9875) and
will eventually be deprecated.
Definition at line 328 of file test_api.py.
test_string_to_boolean_cast_errors()
numpy.core.tests.test_api.test_string_to_boolean_cast_errors (dtype, out_dtype)
These currently error out, since cast to integers fails, but should not
error out in the future.
Definition at line 342 of file test_api.py.
References numpy.core.fromnumeric.reshape(), numpy.core.fromnumeric.squeeze(), numpy.core.fromnumeric.sum(), and numpy.core.fromnumeric.swapaxes().
test_string_to_complex_cast()
numpy.core.tests.test_api.test_string_to_complex_cast (str_type, scalar_type)
Definition at line 355 of file test_api.py.