Code Cloning Analysis: numpy.linalg.tests.test_linalg Namespace Reference
numpy.linalg.tests.test_linalg Namespace Reference
Classes
class _TestNorm
class _TestNorm2D
class _TestNormBase
class _TestNormDoubleBase
class _TestNormGeneral
class _TestNormInt64Base
class _TestNormSingleBase
class CondCases
class DetCases
class EigCases
class EigvalsCases
class HermitianGeneralizedTestCase
class HermitianTestCase
class InvCases
class LinalgCase
class LinalgGeneralizedNonsquareTestCase
class LinalgGeneralizedSquareTestCase
class LinalgNonsquareTestCase
class LinalgSquareTestCase
class LinalgTestCase
class LstsqCases
class PinvCases
class PinvHermitianCases
class SolveCases
class SVDBaseTests
class SVDCases
class SVDHermitianCases
class TestCholesky
class TestCond
class TestDet
class TestEig
class TestEigh
class TestEighCases
class TestEigvals
class TestEigvalsh
class TestEigvalshCases
class TestInv
class TestLstsq
class TestMatrixPower
class TestMatrixRank
class TestMultiDot
class TestNorm_NonSystematic
class TestNormDouble
class TestNormInt64
class TestNormSingle
class TestPinv
class TestPinvHermitian
class TestQR
class TestSolve
class TestSVD
class TestSVDHermitian
class TestTensorinv
class TestTensorsolve
Functions
consistent_subclass (out, in_)
assert_almost_equal (a, b, single_decimal=6, double_decimal=12, **kw)
get_real_dtype (dtype)
get_complex_dtype (dtype)
get_rtol (dtype)
apply_tag (tag, cases)
_make_generalized_cases ()
_stride_comb_iter (x)
_make_strided_cases ()
dot_generalized (a, b)
identity_like_generalized (a)
test_reduced_rank ()
test_byteorder_check ()
test_generalized_raise_multiloop ()
test_xerbla_override ()
test_sdot_bug_8577 ()
test_unsupported_commontype ()
test_blas64_dot ()
test_blas64_geqrf_lwork_smoketest ()
Variables
old_assert_almost_equal = assert_almost_equal
dict all_tags
list CASES = []
Detailed Description
 Test functions for linalg module
Function Documentation
_make_generalized_cases()
numpy.linalg.tests.test_linalg._make_generalized_cases () protected
Definition at line 242 of file test_linalg.py.
_make_strided_cases()
numpy.linalg.tests.test_linalg._make_strided_cases () protected
Definition at line 324 of file test_linalg.py.
_stride_comb_iter()
numpy.linalg.tests.test_linalg._stride_comb_iter (x) protected
Generate cartesian product of strides for all axes
Definition at line 276 of file test_linalg.py.
References _stride_comb_iter().
Referenced by _stride_comb_iter().
apply_tag()
numpy.linalg.tests.test_linalg.apply_tag (tag, cases)
Add the given tag (a string) to each of the cases (a list of LinalgCase
objects)
Definition at line 98 of file test_linalg.py.
References apply_tag(), and numpy.core.fromnumeric.reshape().
Referenced by apply_tag().
assert_almost_equal()
numpy.linalg.tests.test_linalg.assert_almost_equal (a, b, single_decimal = 6, double_decimal = 12, ** kw)
Definition at line 43 of file test_linalg.py.
consistent_subclass()
numpy.linalg.tests.test_linalg.consistent_subclass (out, in_)
Definition at line 33 of file test_linalg.py.
dot_generalized()
numpy.linalg.tests.test_linalg.dot_generalized (a, b)
Definition at line 434 of file test_linalg.py.
get_complex_dtype()
numpy.linalg.tests.test_linalg.get_complex_dtype (dtype)
Definition at line 56 of file test_linalg.py.
get_real_dtype()
numpy.linalg.tests.test_linalg.get_real_dtype (dtype)
Definition at line 51 of file test_linalg.py.
get_rtol()
numpy.linalg.tests.test_linalg.get_rtol (dtype)
Definition at line 61 of file test_linalg.py.
identity_like_generalized()
numpy.linalg.tests.test_linalg.identity_like_generalized (a)
Definition at line 453 of file test_linalg.py.
test_blas64_dot()
numpy.linalg.tests.test_linalg.test_blas64_dot ()
Definition at line 2164 of file test_linalg.py.
test_blas64_geqrf_lwork_smoketest()
numpy.linalg.tests.test_linalg.test_blas64_geqrf_lwork_smoketest ()
Definition at line 2175 of file test_linalg.py.
test_byteorder_check()
numpy.linalg.tests.test_linalg.test_byteorder_check ()
Definition at line 1840 of file test_linalg.py.
test_generalized_raise_multiloop()
numpy.linalg.tests.test_linalg.test_generalized_raise_multiloop ()
Definition at line 1862 of file test_linalg.py.
test_reduced_rank()
numpy.linalg.tests.test_linalg.test_reduced_rank ()
Definition at line 1620 of file test_linalg.py.
test_sdot_bug_8577()
numpy.linalg.tests.test_linalg.test_sdot_bug_8577 ()
Definition at line 1927 of file test_linalg.py.
test_unsupported_commontype()
numpy.linalg.tests.test_linalg.test_unsupported_commontype ()
Definition at line 2152 of file test_linalg.py.
test_xerbla_override()
numpy.linalg.tests.test_linalg.test_xerbla_override ()
Definition at line 1876 of file test_linalg.py.
Variable Documentation
all_tags
dict numpy.linalg.tests.test_linalg.all_tags
Initial value:
=  {
  'square', 'nonsquare', 'hermitian',  # mutually exclusive
  'generalized', 'size-0', 'strided' # optional additions
}
Definition at line 70 of file test_linalg.py.
CASES
list numpy.linalg.tests.test_linalg.CASES = []
Definition at line 115 of file test_linalg.py.
old_assert_almost_equal
numpy.linalg.tests.test_linalg.old_assert_almost_equal = assert_almost_equal
Definition at line 40 of file test_linalg.py.