Code Cloning Analysis: fontTools.pens.cairoPen.CairoPen Class Reference
fontTools.pens.cairoPen.CairoPen Class Reference
Public Member Functions
__init__ (self, glyphSet, context)
Public Member Functions inherited from fontTools.pens.basePen.BasePen
__init__ (self, glyphSet=None)
closePath (self)
endPath (self)
moveTo (self, pt)
lineTo (self, pt)
curveTo (self, *points)
qCurveTo (self, *points)
Public Member Functions inherited from fontTools.pens.basePen.DecomposingPen
__init__ (self, glyphSet, *args, skipMissingComponents=None, reverseFlipped=False, **kwargs)
addComponent (self, glyphName, transformation)
addVarComponent (self, glyphName, transformation, location)
Public Member Functions inherited from fontTools.misc.loggingTools.LogMixin
log (self)
Public Attributes
context = context
Public Attributes inherited from fontTools.pens.basePen.DecomposingPen
glyphSet = glyphSet
reverseFlipped = reverseFlipped
Protected Member Functions
_moveTo (self, p)
_lineTo (self, p)
_curveToOne (self, p1, p2, p3)
_closePath (self)
Protected Member Functions inherited from fontTools.pens.basePen.BasePen
_endPath (self)
_qCurveToOne (self, pt1, pt2)
_getCurrentPoint (self)
Additional Inherited Members
Static Public Attributes inherited from fontTools.pens.basePen.DecomposingPen
bool skipMissingComponents = True
MissingComponentError = MissingComponentError
Protected Attributes inherited from fontTools.misc.loggingTools.LogMixin
_log = logging.getLogger(name)
Detailed Description
Pen to draw to a Cairo graphics library context.
Definition at line 9 of file cairoPen.py.
Constructor & Destructor Documentation
__init__()
fontTools.pens.cairoPen.CairoPen.__init__ (self, glyphSet, context)
Definition at line 12 of file cairoPen.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_closePath()
fontTools.pens.cairoPen.CairoPen._closePath (self) protected
Reimplemented from fontTools.pens.basePen.BasePen.
Definition at line 25 of file cairoPen.py.
_curveToOne()
fontTools.pens.cairoPen.CairoPen._curveToOne (self, p1, p2, p3) protected
Reimplemented from fontTools.pens.basePen.BasePen.
Definition at line 22 of file cairoPen.py.
_lineTo()
fontTools.pens.cairoPen.CairoPen._lineTo (self, p) protected
Reimplemented from fontTools.pens.basePen.BasePen.
Definition at line 19 of file cairoPen.py.
_moveTo()
fontTools.pens.cairoPen.CairoPen._moveTo (self, p) protected
Reimplemented from fontTools.pens.basePen.BasePen.
Definition at line 16 of file cairoPen.py.
Member Data Documentation
context
fontTools.pens.cairoPen.CairoPen.context = context
Definition at line 14 of file cairoPen.py.
Referenced by pip._vendor.distlib.database.Distribution.__init__(), pip._vendor.urllib3.contrib.securetransport.WrappedSocket._custom_validate(), pip._vendor.urllib3.contrib.securetransport.WrappedSocket._set_alpn_protocols(), pip._vendor.urllib3.contrib.securetransport.WrappedSocket._set_ciphers(), pip._vendor.urllib3.contrib.securetransport.WrappedSocket.handshake(), and pip._vendor.distlib.database.Distribution.provides().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/pens/cairoPen.py