Code Cloning Analysis: arithmetic.Object Class Reference
arithmetic.Object Class Reference
Public Member Functions
np.ndarray[Any, np.dtype[np.object_]] __array__ (self)
Object __sub__ (self, Any value)
Object __rsub__ (self, Any value)
Object __floordiv__ (self, Any value)
Object __rfloordiv__ (self, Any value)
Object __mul__ (self, Any value)
Object __rmul__ (self, Any value)
Object __pow__ (self, Any value)
Object __rpow__ (self, Any value)
Static Public Attributes
np AR_b = np.array([True])
np AR_u = np.array([1], dtype=np.uint32)
np AR_i = np.array([1])
np AR_f = np.array([1.0])
np AR_c = np.array([1j])
np AR_m = np.array([np.timedelta64(1, "D")])
np AR_M = np.array([np.datetime64(1, "D")])
np AR_O = np.array([Object()])
Detailed Description
Definition at line 28 of file arithmetic.py.
Member Function Documentation
__array__()
np.ndarray[Any, np.dtype[np.object_]] arithmetic.Object.__array__ (self)
Definition at line 29 of file arithmetic.py.
Referenced by numpy.matrixlib.defmatrix.matrix.A(), numpy.matrixlib.defmatrix.matrix.A1(), numpy.core.defchararray.chararray.argsort(), numpy.matrixlib.defmatrix.matrix.tolist(), and numpy.ma.mrecords.MaskedRecords.view().
__floordiv__()
Object arithmetic.Object.__floordiv__ (self, Any value)
Definition at line 40 of file arithmetic.py.
__mul__()
Object arithmetic.Object.__mul__ (self, Any value)
Definition at line 46 of file arithmetic.py.
Referenced by pip._vendor.pyparsing.core.ParserElement.__mul__(), pyparsing.core.ParserElement.__mul__(), scipy.signal._ltisys.StateSpace.__truediv__(), and scipy.sparse.linalg._interface.LinearOperator.dot().
__pow__()
Object arithmetic.Object.__pow__ (self, Any value)
Definition at line 52 of file arithmetic.py.
__rfloordiv__()
Object arithmetic.Object.__rfloordiv__ (self, Any value)
Definition at line 43 of file arithmetic.py.
__rmul__()
Object arithmetic.Object.__rmul__ (self, Any value)
Definition at line 49 of file arithmetic.py.
Referenced by scipy.sparse.linalg._interface.LinearOperator.dot().
__rpow__()
Object arithmetic.Object.__rpow__ (self, Any value)
Definition at line 55 of file arithmetic.py.
__rsub__()
Object arithmetic.Object.__rsub__ (self, Any value)
Definition at line 37 of file arithmetic.py.
__sub__()
Object arithmetic.Object.__sub__ (self, Any value)
Definition at line 34 of file arithmetic.py.
Member Data Documentation
AR_b
np arithmetic.Object.AR_b = np.array([True]) static
Definition at line 59 of file arithmetic.py.
AR_c
np arithmetic.Object.AR_c = np.array([1j]) static
Definition at line 63 of file arithmetic.py.
AR_f
np arithmetic.Object.AR_f = np.array([1.0]) static
Definition at line 62 of file arithmetic.py.
AR_i
np arithmetic.Object.AR_i = np.array([1]) static
Definition at line 61 of file arithmetic.py.
AR_M
np arithmetic.Object.AR_M = np.array([np.datetime64(1, "D")]) static
Definition at line 65 of file arithmetic.py.
AR_m
np arithmetic.Object.AR_m = np.array([np.timedelta64(1, "D")]) static
Definition at line 64 of file arithmetic.py.
AR_O
np arithmetic.Object.AR_O = np.array([Object()]) static
Definition at line 66 of file arithmetic.py.
AR_u
np arithmetic.Object.AR_u = np.array([1], dtype=np.uint32) static
Definition at line 60 of file arithmetic.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/typing/tests/data/pass/arithmetic.py