Code Cloning Analysis: fontTools.ttLib.tables.otConverters.STXHeader Class Reference
fontTools.ttLib.tables.otConverters.STXHeader Class Reference
Public Member Functions
__init__ (self, name, repeat, aux, tableClass, *, description="")
read (self, reader, font, tableDict)
write (self, writer, font, tableDict, value, repeatIndex=None)
xmlWrite (self, xmlWriter, font, value, name, attrs)
xmlRead (self, attrs, content, font)
Public Member Functions inherited from fontTools.ttLib.tables.otConverters.BaseConverter
__init__ (self, name, repeat, aux, tableClass=None, *, description="")
readArray (self, reader, font, tableDict, count)
getRecordSize (self, reader)
writeArray (self, writer, font, tableDict, values)
Optional[int] getVarIndexOffset (self)
Public Attributes
classLookup = AATLookup("GlyphClasses", None, None, UShort)
perGlyphLookup = AATLookup("PerGlyphLookup", None, None, GlyphID)
Public Attributes inherited from fontTools.ttLib.tables.otConverters.BaseConverter
name = name
repeat = repeat
aux = aux
tableClass = tableClass
isCount
str isLookupType = "MorphType"
isPropagated
description = description
Protected Member Functions
_readTransition (self, reader, entryIndex, font, actionReader)
_readLigatures (self, reader, font)
_countPerGlyphLookups (self, table)
_readPerGlyphLookups (self, table, reader, font)
_compileStates (self, font, states, glyphClassCount, actionIndex)
_compilePerGlyphLookups (self, table, font)
_compileLigComponents (self, table, font)
_compileLigatures (self, table, font)
_xmlWriteLigatures (self, xmlWriter, font, value, name, attrs)
_xmlReadState (self, attrs, content, font)
_xmlReadLigComponents (self, attrs, content, font)
_xmlReadLigatures (self, attrs, content, font)
Additional Inherited Members
Static Public Attributes inherited from fontTools.ttLib.tables.otConverters.BaseConverter
varIndexBasePlusOffsetRE = re.compile(r"VarIndexBase\s*\+\s*(\d+)")
Detailed Description
Definition at line 1268 of file otConverters.py.
Constructor & Destructor Documentation
__init__()
fontTools.ttLib.tables.otConverters.STXHeader.__init__ (self, name, repeat, aux, tableClass, * , description = "")
Definition at line 1269 of file otConverters.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_compileLigatures()
fontTools.ttLib.tables.otConverters.STXHeader._compileLigatures (self, table, font) protected
Definition at line 1469 of file otConverters.py.
Referenced by write().
_compileLigComponents()
fontTools.ttLib.tables.otConverters.STXHeader._compileLigComponents (self, table, font) protected
Definition at line 1461 of file otConverters.py.
Referenced by write().
_compilePerGlyphLookups()
fontTools.ttLib.tables.otConverters.STXHeader._compilePerGlyphLookups (self, table, font) protected
Definition at line 1445 of file otConverters.py.
Referenced by write().
_compileStates()
fontTools.ttLib.tables.otConverters.STXHeader._compileStates (self, font, states, glyphClassCount, actionIndex) protected
Definition at line 1419 of file otConverters.py.
Referenced by write().
_countPerGlyphLookups()
fontTools.ttLib.tables.otConverters.STXHeader._countPerGlyphLookups (self, table) protected
Definition at line 1340 of file otConverters.py.
Referenced by read(), and write().
_readLigatures()
fontTools.ttLib.tables.otConverters.STXHeader._readLigatures (self, reader, font) protected
Definition at line 1335 of file otConverters.py.
Referenced by read().
_readPerGlyphLookups()
fontTools.ttLib.tables.otConverters.STXHeader._readPerGlyphLookups (self, table, reader, font) protected
Definition at line 1355 of file otConverters.py.
Referenced by read().
_readTransition()
fontTools.ttLib.tables.otConverters.STXHeader._readTransition (self, reader, entryIndex, font, actionReader) protected
Definition at line 1327 of file otConverters.py.
Referenced by read().
_xmlReadLigatures()
fontTools.ttLib.tables.otConverters.STXHeader._xmlReadLigatures (self, attrs, content, font) protected
Definition at line 1567 of file otConverters.py.
Referenced by xmlRead().
_xmlReadLigComponents()
fontTools.ttLib.tables.otConverters.STXHeader._xmlReadLigComponents (self, attrs, content, font) protected
Definition at line 1560 of file otConverters.py.
Referenced by xmlRead().
_xmlReadState()
fontTools.ttLib.tables.otConverters.STXHeader._xmlReadState (self, attrs, content, font) protected
Definition at line 1550 of file otConverters.py.
Referenced by xmlRead().
_xmlWriteLigatures()
fontTools.ttLib.tables.otConverters.STXHeader._xmlWriteLigatures (self, xmlWriter, font, value, name, attrs) protected
Definition at line 1517 of file otConverters.py.
Referenced by xmlWrite().
read()
fontTools.ttLib.tables.otConverters.STXHeader.read (self, reader, font, tableDict)
Read a value from the reader.
Reimplemented from fontTools.ttLib.tables.otConverters.BaseConverter.
Definition at line 1280 of file otConverters.py.
References _countPerGlyphLookups(), _readLigatures(), _readPerGlyphLookups(), _readTransition(), classLookup, perGlyphLookup, read(), and fontTools.ttLib.tables.otConverters.BaseConverter.tableClass.
Referenced by pandas.io.parsers.python_parser.PythonParser.__init__(), pip._vendor.urllib3.util.ssltransport.SSLTransport.__init__(), pandas.io.sas.sas7bdat.SAS7BDATReader.column_types(), packaging._tokenizer.Tokenizer.consume(), pip._vendor.urllib3.response.HTTPResponse.drain_conn(), packaging._tokenizer.Tokenizer.expect(), pip._vendor.urllib3.response.HTTPResponse.from_httplib(), pandas.io.sas.sas_xport.XportReader.get_chunk(), packaging._tokenizer.Tokenizer.raise_syntax_error(), read(), PIL.ContainerIO.ContainerIO.readline(), and pip._vendor.urllib3.response.HTTPResponse.stream().
write()
fontTools.ttLib.tables.otConverters.STXHeader.write (self, writer, font, tableDict, value, repeatIndex = None)
Write a value to the writer.
Reimplemented from fontTools.ttLib.tables.otConverters.BaseConverter.
Definition at line 1364 of file otConverters.py.
References _compileLigatures(), _compileLigComponents(), _compilePerGlyphLookups(), _compileStates(), _countPerGlyphLookups(), classLookup, perGlyphLookup, fontTools.ttLib.tables.otConverters.BaseConverter.tableClass, and write().
Referenced by matplotlib.backends.backend_pdf.PdfFile.addGouraudTriangles(), matplotlib.backends.backend_pdf.PdfFile.close(), joblib.externals.cloudpickle.cloudpickle.Pickler.reducer_override(), write(), scipy.io.matlab._mio5.VarWriter5.write_sparse(), pandas.io.formats.html.HTMLFormatter.write_th(), scipy.io.matlab._mio5.VarWriter5.write_top(), matplotlib.backends.backend_pdf.PdfFile.writeTrailer(), and matplotlib.backends.backend_pdf.PdfFile.writeXref().
xmlRead()
fontTools.ttLib.tables.otConverters.STXHeader.xmlRead (self, attrs, content, font)
Read a value from XML.
Reimplemented from fontTools.ttLib.tables.otConverters.BaseConverter.
Definition at line 1528 of file otConverters.py.
References _xmlReadLigatures(), _xmlReadLigComponents(), _xmlReadState(), perGlyphLookup, fontTools.ttLib.tables.otConverters.BaseConverter.tableClass, and xmlRead().
Referenced by xmlRead().
xmlWrite()
fontTools.ttLib.tables.otConverters.STXHeader.xmlWrite (self, xmlWriter, font, value, name, attrs)
Write a value to XML.
Reimplemented from fontTools.ttLib.tables.otConverters.BaseConverter.
Definition at line 1477 of file otConverters.py.
References _xmlWriteLigatures().
Member Data Documentation
classLookup
fontTools.ttLib.tables.otConverters.STXHeader.classLookup = AATLookup("GlyphClasses", None, None, UShort)
Definition at line 1274 of file otConverters.py.
Referenced by read(), and write().
perGlyphLookup
fontTools.ttLib.tables.otConverters.STXHeader.perGlyphLookup = AATLookup("PerGlyphLookup", None, None, GlyphID)
Definition at line 1276 of file otConverters.py.
Referenced by read(), write(), and xmlRead().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ttLib/tables/otConverters.py