Code Cloning Analysis: matplotlib.axis._LazyTickList Class Reference
matplotlib.axis._LazyTickList Class Reference
Public Member Functions
__init__ (self, major)
__get__ (self, instance, owner)
Protected Attributes
_major = major
Detailed Description
A descriptor for lazy instantiation of tick lists.
See comment above definition of the ``majorTicks`` and ``minorTicks``
attributes.
Definition at line 523 of file axis.py.
Constructor & Destructor Documentation
__init__()
matplotlib.axis._LazyTickList.__init__ (self, major)
Definition at line 531 of file axis.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__get__()
matplotlib.axis._LazyTickList.__get__ (self, instance, owner)
Definition at line 534 of file axis.py.
Member Data Documentation
_major
matplotlib.axis._LazyTickList._major = major protected
Definition at line 532 of file axis.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/axis.py