Code Cloning Analysis: scipy.integrate.tests.test_quadrature.TestQuadrature Class Reference
scipy.integrate.tests.test_quadrature.TestQuadrature Class Reference
Public Member Functions
quad (self, x, a, b, args)
test_quadrature (self)
test_quadrature_rtol (self)
test_quadrature_miniter (self)
test_quadrature_single_args (self)
test_romberg (self)
test_romberg_rtol (self)
test_romb (self)
test_romb_gh_3731 (self)
test_non_dtype (self)
test_newton_cotes (self)
test_newton_cotes2 (self)
test_simpson (self)
test_simpson_even_is_deprecated (self)
test_simpson_2d_integer_no_x (self, droplast)
test_simps (self)
Detailed Description
Definition at line 30 of file test_quadrature.py.
Member Function Documentation
quad()
scipy.integrate.tests.test_quadrature.TestQuadrature.quad (self, x, a, b, args)
Definition at line 31 of file test_quadrature.py.
test_newton_cotes()
scipy.integrate.tests.test_quadrature.TestQuadrature.test_newton_cotes (self)
Test the first few degrees, for evenly spaced points.
Definition at line 106 of file test_quadrature.py.
References scipy.integrate._quadrature.newton_cotes().
test_newton_cotes2()
scipy.integrate.tests.test_quadrature.TestQuadrature.test_newton_cotes2 (self)
Test newton_cotes with points that are not evenly spaced.
Definition at line 128 of file test_quadrature.py.
References scipy.integrate._quadrature.newton_cotes(), scipy.integrate._quadrature.simps(), and scipy.integrate._quadrature.simpson().
test_non_dtype()
scipy.integrate.tests.test_quadrature.TestQuadrature.test_non_dtype (self)
Definition at line 99 of file test_quadrature.py.
test_quadrature()
scipy.integrate.tests.test_quadrature.TestQuadrature.test_quadrature (self)
Definition at line 34 of file test_quadrature.py.
test_quadrature_miniter()
scipy.integrate.tests.test_quadrature.TestQuadrature.test_quadrature_miniter (self)
Definition at line 49 of file test_quadrature.py.
test_quadrature_rtol()
scipy.integrate.tests.test_quadrature.TestQuadrature.test_quadrature_rtol (self)
Definition at line 42 of file test_quadrature.py.
test_quadrature_single_args()
scipy.integrate.tests.test_quadrature.TestQuadrature.test_quadrature_single_args (self)
Definition at line 59 of file test_quadrature.py.
test_romb()
scipy.integrate.tests.test_quadrature.TestQuadrature.test_romb (self)
Definition at line 82 of file test_quadrature.py.
test_romb_gh_3731()
scipy.integrate.tests.test_quadrature.TestQuadrature.test_romb_gh_3731 (self)
Definition at line 85 of file test_quadrature.py.
test_romberg()
scipy.integrate.tests.test_quadrature.TestQuadrature.test_romberg (self)
Definition at line 66 of file test_quadrature.py.
test_romberg_rtol()
scipy.integrate.tests.test_quadrature.TestQuadrature.test_romberg_rtol (self)
Definition at line 74 of file test_quadrature.py.
test_simps()
scipy.integrate.tests.test_quadrature.TestQuadrature.test_simps (self)
Definition at line 252 of file test_quadrature.py.
test_simpson()
scipy.integrate.tests.test_quadrature.TestQuadrature.test_simpson (self)
Definition at line 147 of file test_quadrature.py.
test_simpson_2d_integer_no_x()
scipy.integrate.tests.test_quadrature.TestQuadrature.test_simpson_2d_integer_no_x (self, droplast)
Definition at line 241 of file test_quadrature.py.
test_simpson_even_is_deprecated()
scipy.integrate.tests.test_quadrature.TestQuadrature.test_simpson_even_is_deprecated (self)
Definition at line 234 of file test_quadrature.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/integrate/tests/test_quadrature.py