Code Cloning Analysis: matplotlib.patches.ConnectionStyle.Arc3 Class Reference
matplotlib.patches.ConnectionStyle.Arc3 Class Reference
Public Member Functions
__init__ (self, rad=0.)
connect (self, posA, posB)
Public Member Functions inherited from matplotlib.patches.ConnectionStyle._Base
__call__ (self, posA, posB, shrinkA=2., shrinkB=2., patchA=None, patchB=None)
Public Attributes
rad = rad
Additional Inherited Members
Protected Member Functions inherited from matplotlib.patches.ConnectionStyle._Base
_in_patch (self, patch)
_clip (self, path, in_start, in_stop)
Detailed Description
Creates a simple quadratic Bézier curve between two
points. The curve is created so that the middle control point
(C1) is located at the same distance from the start (C0) and
end points(C2) and the distance of the C1 to the line
connecting C0-C2 is *rad* times the distance of C0-C2.
Definition at line 2845 of file patches.py.
Constructor & Destructor Documentation
__init__()
matplotlib.patches.ConnectionStyle.Arc3.__init__ (self, rad = 0.)
Parameters
----------
rad : float
  Curvature of the curve.
Definition at line 2854 of file patches.py.
References rad.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
connect()
matplotlib.patches.ConnectionStyle.Arc3.connect (self, posA, posB)
Definition at line 2863 of file patches.py.
Referenced by matplotlib.patches.ConnectionStyle._Base.__call__().
Member Data Documentation
rad
matplotlib.patches.ConnectionStyle.Arc3.rad = rad
Definition at line 2861 of file patches.py.
Referenced by matplotlib.patches.ConnectionStyle.Angle.__init__(), matplotlib.patches.ConnectionStyle.Arc.__init__(), and __init__().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/patches.py