Code Cloning Analysis: scipy.sparse.linalg._interface Namespace Reference
scipy.sparse.linalg._interface Namespace Reference
Classes
class _AdjointLinearOperator
class _AdjointMatrixOperator
class _CustomLinearOperator
class _PowerLinearOperator
class _ProductLinearOperator
class _ScaledLinearOperator
class _SumLinearOperator
class _TransposedLinearOperator
class IdentityOperator
class LinearOperator
class MatrixLinearOperator
Functions
_get_dtype (operators,dtypes=None)
aslinearoperator (A)
Variables
list __all__ = ['LinearOperator', 'aslinearoperator']
Detailed Description
Abstract linear algebra library.
This module defines a class hierarchy that implements a kind of "lazy"
matrix representation, called the ``LinearOperator``. It can be used to do
linear algebra with extremely large sparse or structured matrices, without
representing those explicitly in memory. Such matrices can be added,
multiplied, transposed, etc.
As a motivating example, suppose you want have a matrix where almost all of
the elements have the value one. The standard sparse matrix representation
skips the storage of zeros, but not ones. By contrast, a LinearOperator is
able to represent such matrices efficiently. First, we need a compact way to
represent an all-ones matrix::
    >>> import numpy as np
    >>> class Ones(LinearOperator):
    ...     def __init__(self, shape):
    ...         super().__init__(dtype=None, shape=shape)
    ...     def _matvec(self, x):
    ...         return np.repeat(x.sum(), self.shape[0])
Instances of this class emulate ``np.ones(shape)``, but using a constant
amount of storage, independent of ``shape``. The ``_matvec`` method specifies
how this linear operator multiplies with (operates on) a vector. We can now
add this operator to a sparse matrix that stores only offsets from one::
    >>> from scipy.sparse import csr_matrix
    >>> offsets = csr_matrix([[1, 0, 2], [0, -1, 0], [0, 0, 3]])
    >>> A = aslinearoperator(offsets) + Ones(offsets.shape)
    >>> A.dot([1, 2, 3])
    array([13,  4, 15])
The result is the same as that given by its dense, explicitly-stored
counterpart::
    >>> (np.ones(A.shape, A.dtype) + offsets.toarray()).dot([1, 2, 3])
    array([13,  4, 15])
Several algorithms in the ``scipy.sparse`` library are able to operate on
``LinearOperator`` instances.
Function Documentation
_get_dtype()
scipy.sparse.linalg._interface._get_dtype (operators, dtypes = None) protected
Definition at line 658 of file _interface.py.
aslinearoperator()
scipy.sparse.linalg._interface.aslinearoperator (A)
Return A as a LinearOperator.
'A' may be any of the following types:
 - ndarray
 - matrix
 - sparse matrix (e.g. csr_matrix, lil_matrix, etc.)
 - LinearOperator
 - An object with .shape and .matvec attributes
See the LinearOperator documentation for additional information.
Notes
-----
If 'A' has no .dtype attribute, the data type is determined by calling
:func:`LinearOperator.matvec()` - set the .dtype attribute to prevent this
call upon the linear operator creation.
Examples
--------
>>> import numpy as np
>>> from scipy.sparse.linalg import aslinearoperator
>>> M = np.array([[1,2,3],[4,5,6]], dtype=np.int32)
>>> aslinearoperator(M)
<2x3 MatrixLinearOperator with dtype=int32>
Definition at line 840 of file _interface.py.
Referenced by scipy.sparse.linalg._onenormest._algorithm_2_2(), scipy.sparse.linalg._onenormest._onenormest_core(), scipy.sparse.linalg._expm_multiply._onenormest_matrix_power(), scipy.sparse.linalg._isolve.lsmr.lsmr(), scipy.sparse.linalg._isolve.lsqr.lsqr(), scipy.sparse.linalg._isolve.utils.make_system(), scipy.sparse.linalg._onenormest.onenormest(), and scipy.sparse.linalg.tests.test_expm_multiply.test_expm_multiply_dtype().
Variable Documentation
__all__
list scipy.sparse.linalg._interface.__all__ = ['LinearOperator', 'aslinearoperator'] private
Definition at line 50 of file _interface.py.