Code Cloning Analysis: scipy.optimize._nonlin.DiagBroyden Class Reference
scipy.optimize._nonlin.DiagBroyden Class Reference
Public Member Functions
__init__ (self, alpha=None)
setup (self, x, F, func)
solve (self, f, tol=0)
matvec (self, f)
rsolve (self, f, tol=0)
rmatvec (self, f)
todense (self)
Public Member Functions inherited from scipy.optimize._nonlin.GenericBroyden
update (self, x, f)
Public Member Functions inherited from scipy.optimize._nonlin.Jacobian
__init__ (self, **kw)
aspreconditioner (self)
Public Attributes
d = np.full((self.shape[0],), 1 / self.alpha, dtype=self.dtype)
Public Attributes inherited from scipy.optimize._nonlin.GenericBroyden
last_f = f0
last_x = x0
float alpha = 0.5*max(norm(x0), 1) / normf0
Public Attributes inherited from scipy.optimize._nonlin.Jacobian
func = func
tuple shape = (F.size, x.size)
dtype = F.dtype
Protected Member Functions
_update (self, x, f, dx, df, dx_norm, df_norm)
Detailed Description
Find a root of a function, using diagonal Broyden Jacobian approximation.
The Jacobian approximation is derived from previous iterations, by
retaining only the diagonal of Broyden matrices.
.. warning::
   This algorithm may be useful for specific problems, but whether
   it will work may depend strongly on the problem.
Parameters
----------
%(params_basic)s
alpha : float, optional
    Initial guess for the Jacobian is (-1/alpha).
%(params_extra)s
See Also
--------
root : Interface to root finding algorithms for multivariate
       functions. See ``method='diagbroyden'`` in particular.
Examples
--------
The following functions define a system of nonlinear equations
>>> def fun(x):
...     return [x[0]  + 0.5 * (x[0] - x[1])**3 - 1.0,
...             0.5 * (x[1] - x[0])**3 + x[1]]
A solution can be obtained as follows.
>>> from scipy import optimize
>>> sol = optimize.diagbroyden(fun, [0, 0])
>>> sol
array([0.84116403, 0.15883384])
Definition at line 1138 of file _nonlin.py.
Constructor & Destructor Documentation
__init__()
scipy.optimize._nonlin.DiagBroyden.__init__ (self, alpha = None)
Definition at line 1179 of file _nonlin.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
_update()
scipy.optimize._nonlin.DiagBroyden._update (self, x, f, dx, df, dx_norm, df_norm) protected
Reimplemented from scipy.optimize._nonlin.GenericBroyden.
Definition at line 1202 of file _nonlin.py.
matvec()
scipy.optimize._nonlin.DiagBroyden.matvec (self, f)
Definition at line 1190 of file _nonlin.py.
Referenced by scipy.sparse.linalg._interface.LinearOperator._init_dtype(), scipy.sparse.linalg._interface.LinearOperator._matmat(), and scipy.sparse.linalg._interface.LinearOperator.dot().
rmatvec()
scipy.optimize._nonlin.DiagBroyden.rmatvec (self, f)
Definition at line 1196 of file _nonlin.py.
Referenced by scipy.sparse.linalg._interface.LinearOperator._rmatmat().
rsolve()
scipy.optimize._nonlin.DiagBroyden.rsolve (self, f, tol = 0)
Definition at line 1193 of file _nonlin.py.
setup()
scipy.optimize._nonlin.DiagBroyden.setup (self, x, F, func)
Reimplemented from scipy.optimize._nonlin.GenericBroyden.
Definition at line 1183 of file _nonlin.py.
solve()
scipy.optimize._nonlin.DiagBroyden.solve (self, f, tol = 0)
Reimplemented from scipy.optimize._nonlin.Jacobian.
Definition at line 1187 of file _nonlin.py.
todense()
scipy.optimize._nonlin.DiagBroyden.todense (self)
Definition at line 1199 of file _nonlin.py.
Referenced by scipy.sparse._base._spbase._divide(), scipy.sparse._compressed._cs_matrix._maximum_minimum(), scipy.sparse._compressed._cs_matrix._scalar_binopt(), scipy.sparse._dok._dok_base.get(), and scipy.sparse._base._spbase.power().
Member Data Documentation
d
scipy.optimize._nonlin.DiagBroyden.d = np.full((self.shape[0],), 1 / self.alpha, dtype=self.dtype)
Definition at line 1185 of file _nonlin.py.
Referenced by scipy.stats._qmc.PoissonDisk._hypersphere_surface_sample(), scipy.stats._qmc.PoissonDisk._hypersphere_volume_sample(), scipy.stats._qmc.PoissonDisk._initialize_grid_pool(), scipy.stats._qmc.Halton._random(), scipy.stats._qmc.PoissonDisk._random(), scipy.stats._qmc.Sobol._random(), scipy.stats._qmc.LatinHypercube._random_lhs(), scipy.stats._qmc.LatinHypercube._random_oa_lhs(), scipy.stats._qmc.Sobol._scramble(), scipy.sparse.linalg._expm_multiply.LazyOperatorNormInfo.alpha(), scipy.stats._kde.gaussian_kde.evaluate(), scipy.stats._qmc.Sobol.fast_forward(), scipy.stats._kde.gaussian_kde.integrate_box(), scipy.stats._kde.gaussian_kde.integrate_box_1d(), scipy.stats._kde.gaussian_kde.integrate_gaussian(), scipy.stats._kde.gaussian_kde.integrate_kde(), scipy.optimize._zeros_py.TOMS748Solver.iterate(), scipy.stats._kde.gaussian_kde.logpdf(), scipy.stats._kde.gaussian_kde.resample(), scipy.stats._kde.gaussian_kde.scotts_factor(), scipy.stats._kde.gaussian_kde.silverman_factor(), and scipy.optimize._zeros_py.TOMS748Solver.solve().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/optimize/_nonlin.py