Code Cloning Analysis: pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge Class Reference
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge Class Reference
Public Member Functions
prep_data (self, df, dedupe=False)
trades (self)
quotes (self)
asof (self)
tolerance (self)
allow_exact_matches (self, datapath)
allow_exact_matches_and_tolerance (self)
test_examples1 (self)
test_examples2 (self, unit)
test_examples3 (self)
test_examples4 (self)
test_basic (self, trades, asof, quotes)
test_basic_categorical (self, trades, asof, quotes)
test_basic_left_index (self, trades, asof, quotes)
test_basic_right_index (self, trades, asof, quotes)
test_basic_left_index_right_index (self, trades, asof, quotes)
test_multi_index_left (self, trades, quotes)
test_multi_index_right (self, trades, quotes)
test_on_and_index_left_on (self, trades, quotes)
test_on_and_index_right_on (self, trades, quotes)
test_basic_left_by_right_by (self, trades, asof, quotes)
test_missing_right_by (self, trades, asof, quotes)
test_multiby (self)
test_multiby_heterogeneous_types (self, dtype)
test_mismatched_index_dtype (self)
test_multiby_indexed (self)
test_basic2 (self, datapath)
test_basic_no_by (self, trades, asof, quotes)
test_valid_join_keys (self, trades, quotes)
test_with_duplicates (self, datapath, trades, quotes, asof)
test_with_duplicates_no_on (self)
test_valid_allow_exact_matches (self, trades, quotes)
test_valid_tolerance (self, trades, quotes)
test_non_sorted (self, trades, quotes)
test_tolerance (self, tolerance_ts, trades, quotes, tolerance)
test_tolerance_forward (self)
test_tolerance_nearest (self)
test_tolerance_tz (self, unit)
test_tolerance_float (self)
test_index_tolerance (self, trades, quotes, tolerance)
test_allow_exact_matches (self, trades, quotes, allow_exact_matches)
test_allow_exact_matches_forward (self)
test_allow_exact_matches_nearest (self)
test_allow_exact_matches_and_tolerance (self, trades, quotes, allow_exact_matches_and_tolerance)
test_allow_exact_matches_and_tolerance2 (self)
test_allow_exact_matches_and_tolerance3 (self)
test_allow_exact_matches_and_tolerance_forward (self)
test_allow_exact_matches_and_tolerance_nearest (self)
test_forward_by (self)
test_nearest_by (self)
test_by_int (self)
test_on_float (self)
test_on_specialized_type (self, any_real_numpy_dtype)
test_on_specialized_type_by_int (self, any_real_numpy_dtype)
test_on_float_by_int (self)
test_merge_datatype_error_raises (self)
test_merge_datatype_categorical_error_raises (self)
test_merge_groupby_multiple_column_with_categorical_column (self)
test_merge_on_nans (self, func, side)
test_by_nullable (self, any_numeric_ea_dtype, using_infer_string)
test_merge_by_col_tz_aware (self)
test_by_mixed_tz_aware (self, using_infer_string)
test_by_dtype (self, dtype)
test_timedelta_tolerance_nearest (self, unit)
test_int_type_tolerance (self, any_int_dtype)
test_merge_index_column_tz (self)
test_left_index_right_index_tolerance (self, unit)
Static Public Attributes
True
marks
Detailed Description
Definition at line 29 of file test_merge_asof.py.
Member Function Documentation
allow_exact_matches()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.allow_exact_matches (self, datapath)
Definition at line 616 of file test_merge_asof.py.
allow_exact_matches_and_tolerance()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.allow_exact_matches_and_tolerance (self)
Definition at line 856 of file test_merge_asof.py.
asof()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.asof (self)
Definition at line 104 of file test_merge_asof.py.
prep_data()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.prep_data (self, df, dedupe = False)
Definition at line 30 of file test_merge_asof.py.
Referenced by test_examples4().
quotes()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.quotes (self)
Definition at line 77 of file test_merge_asof.py.
test_allow_exact_matches()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_allow_exact_matches (self, trades, quotes, allow_exact_matches)
Definition at line 2631 of file test_merge_asof.py.
test_allow_exact_matches_and_tolerance()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_allow_exact_matches_and_tolerance (self, trades, quotes, allow_exact_matches_and_tolerance)
Definition at line 2668 of file test_merge_asof.py.
test_allow_exact_matches_and_tolerance2()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_allow_exact_matches_and_tolerance2 (self)
Definition at line 2682 of file test_merge_asof.py.
test_allow_exact_matches_and_tolerance3()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_allow_exact_matches_and_tolerance3 (self)
Definition at line 2732 of file test_merge_asof.py.
test_allow_exact_matches_and_tolerance_forward()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_allow_exact_matches_and_tolerance_forward (self)
Definition at line 2769 of file test_merge_asof.py.
test_allow_exact_matches_and_tolerance_nearest()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_allow_exact_matches_and_tolerance_nearest (self)
Definition at line 2789 of file test_merge_asof.py.
test_allow_exact_matches_forward()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_allow_exact_matches_forward (self)
Definition at line 2638 of file test_merge_asof.py.
test_allow_exact_matches_nearest()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_allow_exact_matches_nearest (self)
Definition at line 2653 of file test_merge_asof.py.
test_basic()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_basic (self, trades, asof, quotes)
Definition at line 1224 of file test_merge_asof.py.
test_basic2()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_basic2 (self, datapath)
Definition at line 1534 of file test_merge_asof.py.
test_basic_categorical()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_basic_categorical (self, trades, asof, quotes)
Definition at line 1230 of file test_merge_asof.py.
test_basic_left_by_right_by()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_basic_left_by_right_by (self, trades, asof, quotes)
Definition at line 1305 of file test_merge_asof.py.
test_basic_left_index()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_basic_left_index (self, trades, asof, quotes)
Definition at line 1239 of file test_merge_asof.py.
test_basic_left_index_right_index()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_basic_left_index_right_index (self, trades, asof, quotes)
Definition at line 1262 of file test_merge_asof.py.
test_basic_no_by()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_basic_no_by (self, trades, asof, quotes)
Definition at line 2393 of file test_merge_asof.py.
test_basic_right_index()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_basic_right_index (self, trades, asof, quotes)
Definition at line 1253 of file test_merge_asof.py.
test_by_dtype()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_by_dtype (self, dtype)
Definition at line 3235 of file test_merge_asof.py.
test_by_int()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_by_int (self)
Definition at line 2869 of file test_merge_asof.py.
test_by_mixed_tz_aware()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_by_mixed_tz_aware (self, using_infer_string)
Definition at line 3206 of file test_merge_asof.py.
test_by_nullable()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_by_nullable (self, any_numeric_ea_dtype, using_infer_string)
Definition at line 3137 of file test_merge_asof.py.
test_examples1()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_examples1 (self)
doc-string examples
Definition at line 1095 of file test_merge_asof.py.
test_examples2()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_examples2 (self, unit)
doc-string examples
Definition at line 1107 of file test_merge_asof.py.
test_examples3()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_examples3 (self)
doc-string examples
Definition at line 1196 of file test_merge_asof.py.
test_examples4()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_examples4 (self)
doc-string examples
Definition at line 1210 of file test_merge_asof.py.
References prep_data(), and pytz.timezone().
test_forward_by()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_forward_by (self)
Definition at line 2809 of file test_merge_asof.py.
test_index_tolerance()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_index_tolerance (self, trades, quotes, tolerance)
Definition at line 2615 of file test_merge_asof.py.
test_int_type_tolerance()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_int_type_tolerance (self, any_int_dtype)
Definition at line 3303 of file test_merge_asof.py.
test_left_index_right_index_tolerance()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_left_index_right_index_tolerance (self, unit)
Definition at line 3352 of file test_merge_asof.py.
test_merge_by_col_tz_aware()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_merge_by_col_tz_aware (self)
Definition at line 3183 of file test_merge_asof.py.
test_merge_datatype_categorical_error_raises()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_merge_datatype_categorical_error_raises (self)
Definition at line 3093 of file test_merge_asof.py.
test_merge_datatype_error_raises()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_merge_datatype_error_raises (self)
Definition at line 3084 of file test_merge_asof.py.
test_merge_groupby_multiple_column_with_categorical_column()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_merge_groupby_multiple_column_with_categorical_column (self)
Definition at line 3112 of file test_merge_asof.py.
test_merge_index_column_tz()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_merge_index_column_tz (self)
Definition at line 3319 of file test_merge_asof.py.
test_merge_on_nans()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_merge_on_nans (self, func, side)
Definition at line 3123 of file test_merge_asof.py.
test_mismatched_index_dtype()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_mismatched_index_dtype (self)
Definition at line 1456 of file test_merge_asof.py.
test_missing_right_by()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_missing_right_by (self, trades, asof, quotes)
Definition at line 1314 of file test_merge_asof.py.
test_multi_index_left()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_multi_index_left (self, trades, quotes)
Definition at line 1272 of file test_merge_asof.py.
test_multi_index_right()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_multi_index_right (self, trades, quotes)
Definition at line 1279 of file test_merge_asof.py.
test_multiby()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_multiby (self)
Definition at line 1322 of file test_merge_asof.py.
test_multiby_heterogeneous_types()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_multiby_heterogeneous_types (self, dtype)
Definition at line 1388 of file test_merge_asof.py.
test_multiby_indexed()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_multiby_indexed (self)
Definition at line 1484 of file test_merge_asof.py.
test_nearest_by()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_nearest_by (self)
Definition at line 2839 of file test_merge_asof.py.
test_non_sorted()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_non_sorted (self, trades, quotes)
Definition at line 2493 of file test_merge_asof.py.
test_on_and_index_left_on()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_on_and_index_left_on (self, trades, quotes)
Definition at line 1286 of file test_merge_asof.py.
test_on_and_index_right_on()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_on_and_index_right_on (self, trades, quotes)
Definition at line 1296 of file test_merge_asof.py.
test_on_float()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_on_float (self)
Definition at line 2930 of file test_merge_asof.py.
test_on_float_by_int()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_on_float_by_int (self)
Definition at line 3027 of file test_merge_asof.py.
test_on_specialized_type()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_on_specialized_type (self, any_real_numpy_dtype)
Definition at line 2960 of file test_merge_asof.py.
test_on_specialized_type_by_int()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_on_specialized_type_by_int (self, any_real_numpy_dtype)
Definition at line 2991 of file test_merge_asof.py.
test_timedelta_tolerance_nearest()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_timedelta_tolerance_nearest (self, unit)
Definition at line 3262 of file test_merge_asof.py.
test_tolerance()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_tolerance (self, tolerance_ts, trades, quotes, tolerance)
Definition at line 2521 of file test_merge_asof.py.
test_tolerance_float()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_tolerance_float (self)
Definition at line 2597 of file test_merge_asof.py.
test_tolerance_forward()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_tolerance_forward (self)
Definition at line 2528 of file test_merge_asof.py.
test_tolerance_nearest()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_tolerance_nearest (self)
Definition at line 2541 of file test_merge_asof.py.
test_tolerance_tz()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_tolerance_tz (self, unit)
Definition at line 2554 of file test_merge_asof.py.
test_valid_allow_exact_matches()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_valid_allow_exact_matches (self, trades, quotes)
Definition at line 2439 of file test_merge_asof.py.
test_valid_join_keys()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_valid_join_keys (self, trades, quotes)
Definition at line 2408 of file test_merge_asof.py.
test_valid_tolerance()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_valid_tolerance (self, trades, quotes)
Definition at line 2447 of file test_merge_asof.py.
test_with_duplicates()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_with_duplicates (self, datapath, trades, quotes, asof)
Definition at line 2420 of file test_merge_asof.py.
test_with_duplicates_no_on()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.test_with_duplicates_no_on (self)
Definition at line 2430 of file test_merge_asof.py.
tolerance()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.tolerance (self)
Definition at line 360 of file test_merge_asof.py.
trades()
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.trades (self)
Definition at line 39 of file test_merge_asof.py.
Member Data Documentation
marks
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.marks static
Definition at line 3381 of file test_merge_asof.py.
True
pandas.tests.reshape.merge.test_merge_asof.TestAsOfMerge.True static
Definition at line 3381 of file test_merge_asof.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/tests/reshape/merge/test_merge_asof.py