Code Cloning Analysis: matplotlib.backends.qt_editor._formlayout.FormComboWidget Class Reference
matplotlib.backends.qt_editor._formlayout.FormComboWidget Class Reference
Public Member Functions
__init__ (self, datalist, comment="", parent=None)
setup (self)
get (self)
Public Attributes
combobox = QtWidgets.QComboBox()
stackwidget = QtWidgets.QStackedWidget(self)
list widgetlist = []
Static Public Attributes
update_buttons = QtCore.Signal()
Detailed Description
Definition at line 360 of file _formlayout.py.
Constructor & Destructor Documentation
__init__()
matplotlib.backends.qt_editor._formlayout.FormComboWidget.__init__ (self, datalist, comment = "", parent = None)
Definition at line 363 of file _formlayout.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
get()
matplotlib.backends.qt_editor._formlayout.FormComboWidget.get (self)
Definition at line 386 of file _formlayout.py.
Referenced by pandas.io.pytables.HDFStore.__getattr__(), scipy._lib._docscrape.NumpyDocString._parse_summary(), pip._vendor.distlib.metadata.LegacyMetadata.check(), pandas.core.series.Series.combine(), pip._vendor.rich.layout.Layout.get(), fontTools.misc.macRes.ResourceReader.getNamedResource(), fontTools.misc.macRes.ResourceReader.getNames(), pandas.io.pytables.HDFStore.root(), and pip._vendor.distlib.metadata.LegacyMetadata.write_file().
setup()
matplotlib.backends.qt_editor._formlayout.FormComboWidget.setup (self)
Definition at line 382 of file _formlayout.py.
Member Data Documentation
combobox
matplotlib.backends.qt_editor._formlayout.FormComboWidget.combobox = QtWidgets.QComboBox()
Definition at line 367 of file _formlayout.py.
stackwidget
matplotlib.backends.qt_editor._formlayout.FormComboWidget.stackwidget = QtWidgets.QStackedWidget(self)
Definition at line 370 of file _formlayout.py.
update_buttons
matplotlib.backends.qt_editor._formlayout.FormComboWidget.update_buttons = QtCore.Signal() static
Definition at line 361 of file _formlayout.py.
widgetlist
list matplotlib.backends.qt_editor._formlayout.FormComboWidget.widgetlist = []
Definition at line 375 of file _formlayout.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/backends/qt_editor/_formlayout.py