Code Cloning Analysis: fontTools.ttLib.tables.otTables.LigAction Class Reference
fontTools.ttLib.tables.otTables.LigAction Class Reference
Public Member Functions
__init__ (self)
Public Attributes
bool Store = False
int GlyphIndexDelta = 0
Detailed Description
Definition at line 621 of file otTables.py.
Constructor & Destructor Documentation
__init__()
fontTools.ttLib.tables.otTables.LigAction.__init__ (self)
Definition at line 622 of file otTables.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Data Documentation
GlyphIndexDelta
int fontTools.ttLib.tables.otTables.LigAction.GlyphIndexDelta = 0
Definition at line 633 of file otTables.py.
Store
bool fontTools.ttLib.tables.otTables.LigAction.Store = False
Definition at line 623 of file otTables.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ttLib/tables/otTables.py