Code Cloning Analysis: scipy.io._harwell_boeing.hb.HBFile Class Reference
scipy.io._harwell_boeing.hb.HBFile Class Reference
Public Member Functions
__init__ (self, file, hb_info=None)
title (self)
key (self)
type (self)
structure (self)
storage (self)
read_matrix (self)
write_matrix (self, m)
Protected Attributes
_fid = file
_hb_info = HBInfo.from_file(file)
Detailed Description
Definition at line 422 of file hb.py.
Constructor & Destructor Documentation
__init__()
scipy.io._harwell_boeing.hb.HBFile.__init__ (self, file, hb_info = None)
Create a HBFile instance.
Parameters
----------
file : file-object
    StringIO work as well
hb_info : HBInfo, optional
    Should be given as an argument for writing, in which case the file
    should be writable.
Definition at line 423 of file hb.py.
References _fid, and _hb_info.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
key()
scipy.io._harwell_boeing.hb.HBFile.key (self)
Definition at line 447 of file hb.py.
read_matrix()
scipy.io._harwell_boeing.hb.HBFile.read_matrix (self)
Definition at line 462 of file hb.py.
storage()
scipy.io._harwell_boeing.hb.HBFile.storage (self)
Definition at line 459 of file hb.py.
structure()
scipy.io._harwell_boeing.hb.HBFile.structure (self)
Definition at line 455 of file hb.py.
title()
scipy.io._harwell_boeing.hb.HBFile.title (self)
Definition at line 443 of file hb.py.
type()
scipy.io._harwell_boeing.hb.HBFile.type (self)
Definition at line 451 of file hb.py.
write_matrix()
scipy.io._harwell_boeing.hb.HBFile.write_matrix (self, m)
Definition at line 465 of file hb.py.
Member Data Documentation
_fid
scipy.io._harwell_boeing.hb.HBFile._fid = file protected
Definition at line 434 of file hb.py.
Referenced by __init__().
_hb_info
scipy.io._harwell_boeing.hb.HBFile._hb_info = HBInfo.from_file(file) protected
Definition at line 436 of file hb.py.
Referenced by __init__().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/io/_harwell_boeing/hb.py