Code Cloning Analysis: matplotlib.tests.test_cbook.Test_callback_registry Class Reference
matplotlib.tests.test_cbook.Test_callback_registry Class Reference
Public Member Functions
setup_method (self)
connect (self, s, func, pickle)
disconnect (self, cid)
count (self)
is_empty (self)
is_not_empty (self)
test_cid_restore (self)
test_callback_complete (self, pickle, cls)
test_callback_disconnect (self, pickle, cls)
test_callback_wrong_disconnect (self, pickle, cls)
test_registration_on_non_empty_registry (self, pickle, cls)
test_pickling (self)
Public Attributes
str signal = 'test'
callbacks = cbook.CallbackRegistry()
Detailed Description
Definition at line 193 of file test_cbook.py.
Member Function Documentation
connect()
matplotlib.tests.test_cbook.Test_callback_registry.connect (self, s, func, pickle)
Definition at line 198 of file test_cbook.py.
Referenced by matplotlib.patches.ConnectionStyle._Base.__call__().
count()
matplotlib.tests.test_cbook.Test_callback_registry.count (self)
Definition at line 207 of file test_cbook.py.
Referenced by pandas.core.window.rolling.Rolling._validate_datetimelike_monotonic(), numpy.ma.core.MaskedArray.mean(), PIL.ImageStat.Stat.mean(), PIL.ImageStat.Stat.median(), PIL.ImageStat.Stat.rms(), numpy.ma.core.MaskedArray.var(), and PIL.ImageStat.Stat.var().
disconnect()
matplotlib.tests.test_cbook.Test_callback_registry.disconnect (self, cid)
Definition at line 204 of file test_cbook.py.
is_empty()
matplotlib.tests.test_cbook.Test_callback_registry.is_empty (self)
Definition at line 213 of file test_cbook.py.
is_not_empty()
matplotlib.tests.test_cbook.Test_callback_registry.is_not_empty (self)
Definition at line 219 of file test_cbook.py.
setup_method()
matplotlib.tests.test_cbook.Test_callback_registry.setup_method (self)
Definition at line 194 of file test_cbook.py.
test_callback_complete()
matplotlib.tests.test_cbook.Test_callback_registry.test_callback_complete (self, pickle, cls)
Definition at line 233 of file test_cbook.py.
test_callback_disconnect()
matplotlib.tests.test_cbook.Test_callback_registry.test_callback_disconnect (self, pickle, cls)
Definition at line 259 of file test_cbook.py.
test_callback_wrong_disconnect()
matplotlib.tests.test_cbook.Test_callback_registry.test_callback_wrong_disconnect (self, pickle, cls)
Definition at line 278 of file test_cbook.py.
test_cid_restore()
matplotlib.tests.test_cbook.Test_callback_registry.test_cid_restore (self)
Definition at line 224 of file test_cbook.py.
test_pickling()
matplotlib.tests.test_cbook.Test_callback_registry.test_pickling (self)
Definition at line 322 of file test_cbook.py.
test_registration_on_non_empty_registry()
matplotlib.tests.test_cbook.Test_callback_registry.test_registration_on_non_empty_registry (self, pickle, cls)
Definition at line 297 of file test_cbook.py.
Member Data Documentation
callbacks
matplotlib.tests.test_cbook.Test_callback_registry.callbacks = cbook.CallbackRegistry()
Definition at line 196 of file test_cbook.py.
signal
matplotlib.tests.test_cbook.Test_callback_registry.signal = 'test'
Definition at line 195 of file test_cbook.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/tests/test_cbook.py