Code Cloning Analysis: pyparsing.core Namespace Reference
pyparsing.core Namespace Reference
Classes
class __compat__
class __diag__
class _MultipleMatch
class _NullToken
class _ParseActionIndexError
class _PendingSkip
class _SingleCharLiteral
class And
class AtLineStart
class AtStringStart
class CaselessKeyword
class CaselessLiteral
class Char
class CharsNotIn
class CloseMatch
class Combine
class DelimitedList
class Diagnostics
class Dict
class Each
class Empty
class FollowedBy
class Forward
class GoToColumn
class Group
class IndentedBlock
class Keyword
class LineEnd
class LineStart
class Literal
class Located
class MatchFirst
class NoMatch
class NotAny
class OneOrMore
class Opt
class Or
class ParseElementEnhance
class ParseExpression
class ParserElement
class PositionToken
class PrecededBy
class QuotedString
class Regex
class SkipTo
class StringEnd
class StringStart
class Suppress
class Tag
class Token
class TokenConverter
class White
class Word
class WordEnd
class WordStart
class ZeroOrMore
Functions
None enable_diag (Diagnostics diag_enum)
None disable_diag (Diagnostics diag_enum)
None enable_all_warnings ()
bool _should_enable_warnings (typing.Iterable[str] cmd_line_warn_options, typing.Optional[str] warn_env_var)
_trim_arity (func, max_limit=3)
ParseAction condition_as_parse_action (ParseCondition fn, typing.Optional[str] message=None, bool fatal=False)
_default_start_debug_action (str instring, int loc, ParserElement expr, bool cache_hit=False)
_default_success_debug_action (str instring, int startloc, int endloc, ParserElement expr, ParseResults toks, bool cache_hit=False)
_default_exception_debug_action (str instring, int loc, ParserElement expr, Exception exc, bool cache_hit=False)
null_debug_action (*args)
ParseAction trace_parse_action (ParseAction f)
str srange (str s)
ParseAction token_map (func, *args)
None autoname_elements ()
Variables
_MAX_INT = sys.maxsize
tuple str_type = (str, bytes)
dict _single_arg_builtins
_generatorType = types.GeneratorType
ParseImplReturnType = tuple[int, Any]
PostParseReturnType = Union[ParseResults, Sequence[ParseResults]]
ParseCondition
ParseFailAction = Callable[[str, int, "ParserElement", Exception], None]
DebugStartAction = Callable[[str, int, "ParserElement", bool], None]
DebugSuccessAction
DebugExceptionAction = Callable[[str, int, "ParserElement", Exception, bool], None]
str alphas = string.ascii_uppercase + string.ascii_lowercase
str identchars = pyparsing_unicode.Latin1.identchars
str identbodychars = pyparsing_unicode.Latin1.identbodychars
str nums = "0123456789"
str hexnums = nums + "ABCDEFabcdef"
str alphanums = alphas + nums
str printables = "".join([c for c in string.printable if c not in string.whitespace])
tuple pa_call_line_synth = ()
Optional = Opt
empty = Empty().set_name("empty")
line_start = LineStart().set_name("line_start")
line_end = LineEnd().set_name("line_end")
string_start = StringStart().set_name("string_start")
string_end = StringEnd().set_name("string_end")
_escapedPunc
_escapedHexChar
_escapedOctChar
tuple _singleChar
_charRange = Group(_singleChar + Suppress("-") + _singleChar)
tuple _reBracketExpr
dbl_quoted_string
sgl_quoted_string
quoted_string
python_quoted_string
unicode_string = Combine("u" + quoted_string.copy()).set_name("unicode string literal")
str alphas8bit = srange(r"[\0xc0-\0xd6\0xd8-\0xf6\0xf8-\0xff]")
str punc8bit = srange(r"[\0xa1-\0xbf\0xd7\0xf7]")
list _builtin_exprs
sglQuotedString = sgl_quoted_string
dblQuotedString = dbl_quoted_string
quotedString = quoted_string
unicodeString = unicode_string
lineStart = line_start
lineEnd = line_end
stringStart = string_start
stringEnd = string_end
nullDebugAction = replaced_by_pep8("nullDebugAction", null_debug_action)
traceParseAction = replaced_by_pep8("traceParseAction", trace_parse_action)
conditionAsParseAction = replaced_by_pep8("conditionAsParseAction", condition_as_parse_action)
tokenMap = replaced_by_pep8("tokenMap", token_map)
Function Documentation
_default_exception_debug_action()
pyparsing.core._default_exception_debug_action (str instring, int loc, ParserElement expr, Exception exc, bool cache_hit = False) protected
Definition at line 374 of file core.py.
_default_start_debug_action()
pyparsing.core._default_start_debug_action (str instring, int loc, ParserElement expr, bool cache_hit = False) protected
Definition at line 349 of file core.py.
_default_success_debug_action()
pyparsing.core._default_success_debug_action (str instring, int startloc, int endloc, ParserElement expr, ParseResults toks, bool cache_hit = False) protected
Definition at line 362 of file core.py.
_should_enable_warnings()
bool pyparsing.core._should_enable_warnings (typing.Iterable[str] cmd_line_warn_options, typing.Optional[str] warn_env_var) protected
Definition at line 184 of file core.py.
_trim_arity()
pyparsing.core._trim_arity (func, max_limit = 3) protected
decorator to trim function calls to match the arity of the target
Definition at line 257 of file core.py.
Referenced by pyparsing.core.ParserElement.add_parse_action(), condition_as_parse_action(), pyparsing.core.ParserElement.set_parse_action(), and trace_parse_action().
autoname_elements()
None pyparsing.core.autoname_elements ()
Utility to simplify mass-naming of parser elements, for
generating railroad diagram with named subdiagrams.
Definition at line 6221 of file core.py.
References srange().
condition_as_parse_action()
ParseAction pyparsing.core.condition_as_parse_action (ParseCondition fn, typing.Optional[str] message = None, bool fatal = False)
Function to convert a simple predicate function that returns ``True`` or ``False``
into a parse action. Can be used in places when a parse action is required
and :class:`ParserElement.add_condition` cannot be used (such as when adding a condition
to an operator level in :class:`infix_notation`).
Optional keyword arguments:
- ``message`` - define a custom message to be used in the raised exception
- ``fatal`` - if True, will raise :class:`ParseFatalException` to stop parsing immediately;
  otherwise will raise :class:`ParseException`
Definition at line 321 of file core.py.
References _trim_arity().
Referenced by pyparsing.core.ParserElement.add_condition().
disable_diag()
None pyparsing.core.disable_diag (Diagnostics diag_enum)
Disable a global pyparsing diagnostic flag (see :class:`Diagnostics`).
Definition at line 166 of file core.py.
enable_all_warnings()
None pyparsing.core.enable_all_warnings ()
Enable all global pyparsing diagnostic warnings (see :class:`Diagnostics`).
Definition at line 173 of file core.py.
References enable_all_warnings().
Referenced by enable_all_warnings().
enable_diag()
None pyparsing.core.enable_diag (Diagnostics diag_enum)
Enable a global pyparsing diagnostic flag (see :class:`Diagnostics`).
Definition at line 159 of file core.py.
null_debug_action()
pyparsing.core.null_debug_action (* args)
'Do-nothing' debug action, to suppress debugging output during parsing.
Definition at line 385 of file core.py.
srange()
str pyparsing.core.srange (str s)
Helper to easily define string ranges for use in :class:`Word`
construction. Borrows syntax from regexp ``'[]'`` string range
definitions::
srange("[0-9]")   -> "0123456789"
srange("[a-z]")   -> "abcdefghijklmnopqrstuvwxyz"
srange("[a-z$_]") -> "abcdefghijklmnopqrstuvwxyz$_"
The input string must be enclosed in []'s, and the returned string
is the expanded character set joined into a single string. The
values enclosed in the []'s may be:
- a single character
- an escaped character with a leading backslash (such as ``\-``
or ``\]``)
- an escaped hex character with a leading ``'\x'``
(``\x21``, which is a ``'!'`` character) (``\0x##``
is also supported for backwards compatibility)
- an escaped octal character with a leading ``'\0'``
(``\041``, which is a ``'!'`` character)
- a range of any of the above, separated by a dash (``'a-z'``,
etc.)
- any combination of the above (``'aeiouy'``,
``'a-zA-Z0-9_$'``, etc.)
Definition at line 6134 of file core.py.
Referenced by autoname_elements().
token_map()
ParseAction pyparsing.core.token_map (func, * args)
Helper to define a parse action by mapping a function to all
elements of a :class:`ParseResults` list. If any additional args are passed,
they are forwarded to the given function as additional arguments
after the token, as in
``hex_integer = Word(hexnums).set_parse_action(token_map(int, 16))``,
which will convert the parsed data to an integer using base 16.
Example (compare the last to example in :class:`ParserElement.transform_string`::
    hex_ints = Word(hexnums)[1, ...].set_parse_action(token_map(int, 16))
    hex_ints.run_tests('''
        00 11 22 aa FF 0a 0d 1a
        ''')
    upperword = Word(alphas).set_parse_action(token_map(str.upper))
    upperword[1, ...].run_tests('''
        my kingdom for a horse
        ''')
    wd = Word(alphas).set_parse_action(token_map(str.title))
    wd[1, ...].set_parse_action(' '.join).run_tests('''
        now is the winter of our discontent made glorious summer by this sun of york
        ''')
prints::
    00 11 22 aa FF 0a 0d 1a
    [0, 17, 34, 170, 255, 10, 13, 26]
    my kingdom for a horse
    ['MY', 'KINGDOM', 'FOR', 'A', 'HORSE']
    now is the winter of our discontent made glorious summer by this sun of york
    ['Now Is The Winter Of Our Discontent Made Glorious Summer By This Sun Of York']
Definition at line 6175 of file core.py.
Referenced by pyparsing.common.pyparsing_common.strip_html_tags().
trace_parse_action()
ParseAction pyparsing.core.trace_parse_action (ParseAction f)
Decorator for debugging parse actions.
When the parse action is called, this decorator will print
``">> entering method-name(line:<current_source_line>, <parse_location>, <matched_tokens>)"``.
When the parse action completes, the decorator will print
``"<<"`` followed by the returned value, or any exception that the parse action raised.
Example::
    wd = Word(alphas)
    @trace_parse_action
    def remove_duplicate_chars(tokens):
        return ''.join(sorted(set(''.join(tokens))))
    wds = wd[1, ...].set_parse_action(remove_duplicate_chars)
    print(wds.parse_string("slkdjs sld sldd sdlf sdljf"))
prints::
    >>entering remove_duplicate_chars(line: 'slkdjs sld sldd sdlf sdljf', 0, (['slkdjs', 'sld', 'sldd', 'sdlf', 'sdljf'], {}))
    <<leaving remove_duplicate_chars (ret: 'dfjkls')
    ['dfjkls']
Definition at line 6059 of file core.py.
References _trim_arity().
Variable Documentation
_builtin_exprs
list pyparsing.core._builtin_exprs protected
Initial value:
=  [
    v for v in vars().values() if isinstance(v, ParserElement)
]
Definition at line 6281 of file core.py.
_charRange
pyparsing.core._charRange = Group(_singleChar + Suppress("-") + _singleChar) protected
Definition at line 6125 of file core.py.
_escapedHexChar
pyparsing.core._escapedHexChar protected
Initial value:
=  Regex(r"\\0?[xX][0-9a-fA-F]+").set_parse_action(
    lambda s, l, t: chr(int(t[0].lstrip(r"\0x"), 16))
)
Definition at line 6116 of file core.py.
_escapedOctChar
pyparsing.core._escapedOctChar protected
Initial value:
=  Regex(r"\\0[0-7]+").set_parse_action(
    lambda s, l, t: chr(int(t[0][1:], 8))
)
Definition at line 6119 of file core.py.
_escapedPunc
pyparsing.core._escapedPunc protected
Initial value:
=  Regex(r"\\[\\[\]\/\-\*\.\$\+\^\?()~ ]").set_parse_action(
    lambda s, l, t: t[0][1]
)
Definition at line 6113 of file core.py.
_generatorType
pyparsing.core._generatorType = types.GeneratorType protected
Definition at line 214 of file core.py.
_MAX_INT
pyparsing.core._MAX_INT = sys.maxsize protected
Definition at line 51 of file core.py.
_reBracketExpr
tuple pyparsing.core._reBracketExpr protected
Initial value:
=  (
    Literal("[")
    + Opt("^").set_results_name("negate")
    + Group(OneOrMore(_charRange | _singleChar)).set_results_name("body")
    + Literal("]")
)
Definition at line 6126 of file core.py.
_single_arg_builtins
dict pyparsing.core._single_arg_builtins protected
Initial value:
=  {
    sum, len, sorted, reversed, list, tuple, set, any, all, min, max
}
Definition at line 209 of file core.py.
_singleChar
tuple pyparsing.core._singleChar protected
Initial value:
=  (
    _escapedPunc | _escapedHexChar | _escapedOctChar | CharsNotIn(r"\]", exact=1)
)
Definition at line 6122 of file core.py.
alphanums
str pyparsing.core.alphanums = alphas + nums
Definition at line 237 of file core.py.
alphas
str pyparsing.core.alphas = string.ascii_uppercase + string.ascii_lowercase
Definition at line 232 of file core.py.
alphas8bit
str pyparsing.core.alphas8bit = srange(r"[\0xc0-\0xd6\0xd8-\0xf6\0xf8-\0xff]")
Definition at line 6276 of file core.py.
conditionAsParseAction
pyparsing.core.conditionAsParseAction = replaced_by_pep8("conditionAsParseAction", condition_as_parse_action)
Definition at line 6297 of file core.py.
dbl_quoted_string
pyparsing.core.dbl_quoted_string
Initial value:
=  Combine(
    Regex(r'"(?:[^"\n\r\\]|(?:"")|(?:\\(?:[^x]|x[0-9a-fA-F]+)))*') + '"'
).set_name("string enclosed in double quotes")
Definition at line 6241 of file core.py.
dblQuotedString
pyparsing.core.dblQuotedString = dbl_quoted_string
Definition at line 6288 of file core.py.
DebugExceptionAction
pyparsing.core.DebugExceptionAction = Callable[[str, int, "ParserElement", Exception, bool], None]
Definition at line 229 of file core.py.
DebugStartAction
pyparsing.core.DebugStartAction = Callable[[str, int, "ParserElement", bool], None]
Definition at line 225 of file core.py.
DebugSuccessAction
pyparsing.core.DebugSuccessAction
Initial value:
=  Callable[
    [str, int, int, "ParserElement", ParseResults, bool], None
]
Definition at line 226 of file core.py.
empty
pyparsing.core.empty = Empty().set_name("empty")
Definition at line 6107 of file core.py.
hexnums
str pyparsing.core.hexnums = nums + "ABCDEFabcdef"
Definition at line 236 of file core.py.
identbodychars
str pyparsing.core.identbodychars = pyparsing_unicode.Latin1.identbodychars
Definition at line 234 of file core.py.
identchars
str pyparsing.core.identchars = pyparsing_unicode.Latin1.identchars
Definition at line 233 of file core.py.
line_end
pyparsing.core.line_end = LineEnd().set_name("line_end")
Definition at line 6109 of file core.py.
line_start
pyparsing.core.line_start = LineStart().set_name("line_start")
Definition at line 6108 of file core.py.
lineEnd
pyparsing.core.lineEnd = line_end
Definition at line 6292 of file core.py.
lineStart
pyparsing.core.lineStart = line_start
Definition at line 6291 of file core.py.
nullDebugAction
pyparsing.core.nullDebugAction = replaced_by_pep8("nullDebugAction", null_debug_action)
Definition at line 6295 of file core.py.
nums
str pyparsing.core.nums = "0123456789"
Definition at line 235 of file core.py.
Optional
pyparsing.core.Optional = Opt
Definition at line 5389 of file core.py.
pa_call_line_synth
tuple pyparsing.core.pa_call_line_synth = ()
Definition at line 254 of file core.py.
ParseCondition
pyparsing.core.ParseCondition
Initial value:
=  Union[
    Callable[[], bool],
    Callable[[ParseResults], bool],
    Callable[[int, ParseResults], bool],
    Callable[[str, int, ParseResults], bool],
]
Definition at line 218 of file core.py.
ParseFailAction
pyparsing.core.ParseFailAction = Callable[[str, int, "ParserElement", Exception], None]
Definition at line 224 of file core.py.
ParseImplReturnType
pyparsing.core.ParseImplReturnType = tuple[int, Any]
Definition at line 215 of file core.py.
PostParseReturnType
pyparsing.core.PostParseReturnType = Union[ParseResults, Sequence[ParseResults]]
Definition at line 216 of file core.py.
printables
str pyparsing.core.printables = "".join([c for c in string.printable if c not in string.whitespace])
Definition at line 238 of file core.py.
punc8bit
str pyparsing.core.punc8bit = srange(r"[\0xa1-\0xbf\0xd7\0xf7]")
Definition at line 6277 of file core.py.
python_quoted_string
pyparsing.core.python_quoted_string
Initial value:
=  Combine(
    (Regex(r'"""(?:[^"\\]|""(?!")|"(?!"")|\\.)*', flags=re.MULTILINE) + '"""').set_name(
        "multiline double quoted string"
    )
    ^ (
        Regex(r"'''(?:[^'\\]|''(?!')|'(?!'')|\\.)*", flags=re.MULTILINE) + "'''"
    ).set_name("multiline single quoted string")
    ^ (Regex(r'"(?:[^"\n\r\\]|(?:\\")|(?:\\(?:[^x]|x[0-9a-fA-F]+)))*') + '"').set_name(
        "double quoted string"
    )
    ^ (Regex(r"'(?:[^'\n\r\\]|(?:\\')|(?:\\(?:[^x]|x[0-9a-fA-F]+)))*") + "'").set_name(
        "single quoted string"
    )
).set_name("Python quoted string")
Definition at line 6258 of file core.py.
quoted_string
pyparsing.core.quoted_string
Initial value:
=  Combine(
    (Regex(r'"(?:[^"\n\r\\]|(?:"")|(?:\\(?:[^x]|x[0-9a-fA-F]+)))*') + '"').set_name(
        "double quoted string"
    )
    | (Regex(r"'(?:[^'\n\r\\]|(?:'')|(?:\\(?:[^x]|x[0-9a-fA-F]+)))*") + "'").set_name(
        "single quoted string"
    )
).set_name("quoted string using single or double quotes")
Definition at line 6249 of file core.py.
quotedString
pyparsing.core.quotedString = quoted_string
Definition at line 6289 of file core.py.
sgl_quoted_string
pyparsing.core.sgl_quoted_string
Initial value:
=  Combine(
    Regex(r"'(?:[^'\n\r\\]|(?:'')|(?:\\(?:[^x]|x[0-9a-fA-F]+)))*") + "'"
).set_name("string enclosed in single quotes")
Definition at line 6245 of file core.py.
sglQuotedString
pyparsing.core.sglQuotedString = sgl_quoted_string
Definition at line 6287 of file core.py.
str_type
tuple pyparsing.core.str_type = (str, bytes)
Definition at line 52 of file core.py.
string_end
pyparsing.core.string_end = StringEnd().set_name("string_end")
Definition at line 6111 of file core.py.
string_start
pyparsing.core.string_start = StringStart().set_name("string_start")
Definition at line 6110 of file core.py.
stringEnd
pyparsing.core.stringEnd = string_end
Definition at line 6294 of file core.py.
stringStart
pyparsing.core.stringStart = string_start
Definition at line 6293 of file core.py.
tokenMap
pyparsing.core.tokenMap = replaced_by_pep8("tokenMap", token_map)
Definition at line 6298 of file core.py.
traceParseAction
pyparsing.core.traceParseAction = replaced_by_pep8("traceParseAction", trace_parse_action)
Definition at line 6296 of file core.py.
unicode_string
pyparsing.core.unicode_string = Combine("u" + quoted_string.copy()).set_name("unicode string literal")
Definition at line 6273 of file core.py.
unicodeString
pyparsing.core.unicodeString = unicode_string
Definition at line 6290 of file core.py.