Code Cloning Analysis: pandas.tests.io.formats.test_console.MockEncoding Class Reference
pandas.tests.io.formats.test_console.MockEncoding Class Reference
Public Member Functions
None __init__ (self, encoding)
encoding (self)
Static Public Member Functions
raise_or_return (val)
Public Attributes
val = encoding
Detailed Description
Used to add a side effect when accessing the 'encoding' property. If the
side effect is a str in nature, the value will be returned. Otherwise, the
side effect should be an exception that will be raised.
Definition at line 8 of file test_console.py.
Constructor & Destructor Documentation
__init__()
None pandas.tests.io.formats.test_console.MockEncoding.__init__ (self, encoding)
Definition at line 15 of file test_console.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
encoding()
pandas.tests.io.formats.test_console.MockEncoding.encoding (self)
Definition at line 20 of file test_console.py.
Referenced by pip._vendor.rich.console.ConsoleOptions.ascii_only(), sklearn.feature_extraction.text._VectorizerMixin.decode(), and pip._vendor.rich.console.Console.options().
raise_or_return()
pandas.tests.io.formats.test_console.MockEncoding.raise_or_return (val) static
Definition at line 24 of file test_console.py.
Member Data Documentation
val
pandas.tests.io.formats.test_console.MockEncoding.val = encoding
Definition at line 17 of file test_console.py.
Referenced by matplotlib.widgets.SliderBase.reset().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/tests/io/formats/test_console.py