Code Cloning Analysis: matplotlib.axes._base Namespace Reference
matplotlib.axes._base Namespace Reference
Classes
class _AxesBase
class _axis_method_wrapper
class _process_plot_var_args
class _TransformedBoundsLocator
Functions
_process_plot_format (fmt, *, ambiguous_fmt_datakey=False)
_draw_rasterized (figure, artists, renderer)
Variables
_log = logging.getLogger(__name__)
figure = figure
artists = artists
Function Documentation
_draw_rasterized()
matplotlib.axes._base._draw_rasterized (figure, artists, renderer) protected
A helper function for rasterizing the list of artists.
The bookkeeping to track if we are or are not in rasterizing mode
with the mixed-mode backends is relatively complicated and is now
handled in the matplotlib.artist.allow_rasterization decorator.
This helper defines the absolute minimum methods and attributes on a
shim class to be compatible with that decorator and then uses it to
rasterize the list of artists.
This is maybe too-clever, but allows us to reuse the same code that is
used on normal artists to participate in the "are we rasterizing"
accounting.
Please do not use this outside of the "rasterize below a given zorder"
functionality of Axes.
Parameters
----------
figure : matplotlib.figure.Figure
    The figure all of the artists belong to (not checked).  We need this
    because we can at the figure level suppress composition and insert each
    rasterized artist as its own image.
artists : List[matplotlib.artist.Artist]
    The list of Artists to be rasterized.  These are assumed to all
    be in the same Figure.
renderer : matplotlib.backendbases.RendererBase
    The currently active renderer
Returns
-------
None
Definition at line 4776 of file _base.py.
Referenced by matplotlib.axes._base._AxesBase._update_title_position().
_process_plot_format()
matplotlib.axes._base._process_plot_format (fmt, * , ambiguous_fmt_datakey = False) protected
Convert a MATLAB style color/line style format string to a (*linestyle*,
*marker*, *color*) tuple.
Example format strings include:
* 'ko': black circles
* '.b': blue dots
* 'r--': red dashed lines
* 'C2--': the third color in the color cycle, dashed lines
The format is absolute in the sense that if a linestyle or marker is not
defined in *fmt*, there is no line or marker. This is expressed by
returning 'None' for the respective quantity.
See Also
--------
matplotlib.Line2D.lineStyles, matplotlib.colors.cnames
    All possible styles and color format strings.
Definition at line 121 of file _base.py.
Referenced by matplotlib.axes._base._process_plot_var_args._plot_args(), and matplotlib.tri._triplot.triplot().
Variable Documentation
_log
matplotlib.axes._base._log = logging.getLogger(__name__) protected
Definition at line 32 of file _base.py.
artists
matplotlib.axes._base.artists = artists
Definition at line 4823 of file _base.py.
figure
matplotlib.axes._base.figure = figure
Definition at line 4822 of file _base.py.