Code Cloning Analysis: pandas.core.interchange.from_dataframe Namespace Reference
pandas.core.interchange.from_dataframe Namespace Reference
Functions
pd.DataFrame from_dataframe (df, bool allow_copy=True)
_from_dataframe (DataFrameXchg df, bool allow_copy=True)
pd.DataFrame protocol_df_chunk_to_pandas (DataFrameXchg df)
tuple[np.ndarray, Any] primitive_column_to_ndarray (Column col)
tuple[pd.Series, Any] categorical_column_to_series (Column col)
tuple[np.ndarray, Any] string_column_to_ndarray (Column col)
pd.Series|np.ndarray parse_datetime_format_str (format_str, data)
tuple[np.ndarray|pd.Series, Any] datetime_column_to_ndarray (Column col)
np.ndarray buffer_to_ndarray (Buffer buffer, tuple[DtypeKind, int, str, str] dtype, *, int length, int offset=0)
set_nulls (np.ndarray|pd.Series data, Column col, tuple[Buffer, tuple[DtypeKind, int, str, str]]|None validity, bool allow_modify_inplace=True)
Variables
dict _NP_DTYPES
Function Documentation
_from_dataframe()
pandas.core.interchange.from_dataframe._from_dataframe (DataFrameXchg df, bool allow_copy = True) protected
Build a ``pd.DataFrame`` from the DataFrame interchange object.
Parameters
----------
df : DataFrameXchg
    Object supporting the interchange protocol, i.e. `__dataframe__` method.
allow_copy : bool, default: True
    Whether to allow copying the memory to perform the conversion
    (if false then zero-copy approach is requested).
Returns
-------
pd.DataFrame
Definition at line 105 of file from_dataframe.py.
References protocol_df_chunk_to_pandas().
Referenced by from_dataframe().
buffer_to_ndarray()
np.ndarray pandas.core.interchange.from_dataframe.buffer_to_ndarray (Buffer buffer, tuple[DtypeKind, int, str, str] dtype, * , int length, int offset = 0)
Build a NumPy array from the passed buffer.
Parameters
----------
buffer : Buffer
    Buffer to build a NumPy array from.
dtype : tuple
    Data type of the buffer conforming protocol dtypes format.
offset : int, default: 0
    Number of elements to offset from the start of the buffer.
length : int, optional
    If the buffer is a bit-mask, specifies a number of bits to read
    from the buffer. Has no effect otherwise.
Returns
-------
np.ndarray
Notes
-----
The returned array doesn't own the memory. The caller of this function is
responsible for keeping the memory owner object alive as long as
the returned NumPy array is being used.
Definition at line 432 of file from_dataframe.py.
Referenced by categorical_column_to_series(), datetime_column_to_ndarray(), primitive_column_to_ndarray(), set_nulls(), and string_column_to_ndarray().
categorical_column_to_series()
tuple[pd.Series, Any] pandas.core.interchange.from_dataframe.categorical_column_to_series (Column col)
Convert a column holding categorical data to a pandas Series.
Parameters
----------
col : Column
Returns
-------
tuple
    Tuple of pd.Series holding the data and the memory owner object
    that keeps the memory alive.
Definition at line 215 of file from_dataframe.py.
References buffer_to_ndarray(), and set_nulls().
Referenced by protocol_df_chunk_to_pandas().
datetime_column_to_ndarray()
tuple[np.ndarray | pd.Series, Any] pandas.core.interchange.from_dataframe.datetime_column_to_ndarray (Column col)
Convert a column holding DateTime data to a NumPy array.
Parameters
----------
col : Column
Returns
-------
tuple
    Tuple of np.ndarray holding the data and the memory owner object
    that keeps the memory alive.
Definition at line 395 of file from_dataframe.py.
References buffer_to_ndarray(), parse_datetime_format_str(), and set_nulls().
Referenced by protocol_df_chunk_to_pandas().
from_dataframe()
pd.DataFrame pandas.core.interchange.from_dataframe.from_dataframe (df, bool allow_copy = True)
Build a ``pd.DataFrame`` from any DataFrame supporting the interchange protocol.
.. note::
   For new development, we highly recommend using the Arrow C Data Interface
   alongside the Arrow PyCapsule Interface instead of the interchange protocol.
   From pandas 2.3 onwards, `from_dataframe` uses the PyCapsule Interface,
   only falling back to the interchange protocol if that fails.
.. warning::
    Due to severe implementation issues, we recommend only considering using the
    interchange protocol in the following cases:
    - converting to pandas: for pandas >= 2.0.3
    - converting from pandas: for pandas >= 3.0.0
Parameters
----------
df : DataFrameXchg
    Object supporting the interchange protocol, i.e. `__dataframe__` method.
allow_copy : bool, default: True
    Whether to allow copying the memory to perform the conversion
    (if false then zero-copy approach is requested).
Returns
-------
pd.DataFrame
Examples
--------
>>> df_not_necessarily_pandas = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
>>> interchange_object = df_not_necessarily_pandas.__dataframe__()
>>> interchange_object.column_names()
Index(['A', 'B'], dtype='object')
>>> df_pandas = (pd.api.interchange.from_dataframe
...              (interchange_object.select_columns_by_name(['A'])))
>>> df_pandas
     A
0    1
1    2
These methods (``column_names``, ``select_columns_by_name``) should work
for any dataframe library which implements the interchange protocol.
Definition at line 35 of file from_dataframe.py.
References _from_dataframe().
parse_datetime_format_str()
pd.Series | np.ndarray pandas.core.interchange.from_dataframe.parse_datetime_format_str (format_str, data)
Parse datetime `format_str` to interpret the `data`.
Definition at line 362 of file from_dataframe.py.
Referenced by datetime_column_to_ndarray().
primitive_column_to_ndarray()
tuple[np.ndarray, Any] pandas.core.interchange.from_dataframe.primitive_column_to_ndarray (Column col)
Convert a column holding one of the primitive dtypes to a NumPy array.
A primitive type is one of: int, uint, float, bool.
Parameters
----------
col : Column
Returns
-------
tuple
    Tuple of np.ndarray holding the data and the memory owner object
    that keeps the memory alive.
Definition at line 188 of file from_dataframe.py.
References buffer_to_ndarray(), and set_nulls().
Referenced by protocol_df_chunk_to_pandas().
protocol_df_chunk_to_pandas()
pd.DataFrame pandas.core.interchange.from_dataframe.protocol_df_chunk_to_pandas (DataFrameXchg df)
Convert interchange protocol chunk to ``pd.DataFrame``.
Parameters
----------
df : DataFrameXchg
Returns
-------
pd.DataFrame
Definition at line 144 of file from_dataframe.py.
References categorical_column_to_series(), datetime_column_to_ndarray(), primitive_column_to_ndarray(), and string_column_to_ndarray().
Referenced by _from_dataframe().
set_nulls()
pandas.core.interchange.from_dataframe.set_nulls (np.ndarray | pd.Series data, Column col, tuple[Buffer, tuple[DtypeKind, int, str, str]] | None validity, bool allow_modify_inplace = True)
Set null values for the data according to the column null kind.
Parameters
----------
data : np.ndarray or pd.Series
    Data to set nulls in.
col : Column
    Column object that describes the `data`.
validity : tuple(Buffer, dtype) or None
    The return value of ``col.buffers()``. We do not access the ``col.buffers()``
    here to not take the ownership of the memory of buffer objects.
allow_modify_inplace : bool, default: True
    Whether to modify the `data` inplace when zero-copy is possible (True) or always
    modify a copy of the `data` (False).
Returns
-------
np.ndarray or pd.Series
    Data with the nulls being set.
Definition at line 494 of file from_dataframe.py.
References buffer_to_ndarray().
Referenced by categorical_column_to_series(), datetime_column_to_ndarray(), and primitive_column_to_ndarray().
string_column_to_ndarray()
tuple[np.ndarray, Any] pandas.core.interchange.from_dataframe.string_column_to_ndarray (Column col)
Convert a column holding string data to a NumPy array.
Parameters
----------
col : Column
Returns
-------
tuple
    Tuple of np.ndarray holding the data and the memory owner object
    that keeps the memory alive.
Definition at line 267 of file from_dataframe.py.
References buffer_to_ndarray().
Referenced by protocol_df_chunk_to_pandas().
Variable Documentation
_NP_DTYPES
dict pandas.core.interchange.from_dataframe._NP_DTYPES protected
Initial value:
=  {
    DtypeKind.INT: {8: np.int8, 16: np.int16, 32: np.int32, 64: np.int64},
    DtypeKind.UINT: {8: np.uint8, 16: np.uint16, 32: np.uint32, 64: np.uint64},
    DtypeKind.FLOAT: {32: np.float32, 64: np.float64},
    DtypeKind.BOOL: {1: bool, 8: bool},
}
Definition at line 27 of file from_dataframe.py.