Code Cloning Analysis: pip._vendor.pygments.filters.RaiseOnErrorTokenFilter Class Reference
pip._vendor.pygments.filters.RaiseOnErrorTokenFilter Class Reference
Public Member Functions
__init__ (self, **options)
filter (self, lexer, stream)
Public Member Functions inherited from pip._vendor.pygments.filter.Filter
__init__ (self, **options)
Public Attributes
exception = options.get('excclass', ErrorToken)
Public Attributes inherited from pip._vendor.pygments.filter.Filter
options = options
Detailed Description
Raise an exception when the lexer generates an error token.
Options accepted:
`excclass` : Exception class
  The exception class to raise.
  The default is `pygments.filters.ErrorToken`.
.. versionadded:: 0.8
Definition at line 760 of file __init__.py.
Constructor & Destructor Documentation
__init__()
pip._vendor.pygments.filters.RaiseOnErrorTokenFilter.__init__ (self, ** options)
Definition at line 772 of file __init__.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
filter()
pip._vendor.pygments.filters.RaiseOnErrorTokenFilter.filter (self, lexer, stream)
Reimplemented from pip._vendor.pygments.filter.Filter.
Definition at line 782 of file __init__.py.
Member Data Documentation
exception
pip._vendor.pygments.filters.RaiseOnErrorTokenFilter.exception = options.get('excclass', ErrorToken)
Definition at line 774 of file __init__.py.
Referenced by pip._vendor.tenacity.Future.failed().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pip/_vendor/pygments/filters/__init__.py