Code Cloning Analysis: fontTools.varLib.cff Namespace Reference
fontTools.varLib.cff Namespace Reference
Classes
class CFF2CharStringMergePen
class CFFToCFF2OutlineExtractor
class MergeOutlineExtractor
Functions
addCFFVarStore (varFont, varModel, varDataList, masterSupports)
convertCFFtoCFF2 (varFont)
conv_to_int (num)
get_private (regionFDArrays, fd_index, ri, fd_map)
merge_PrivateDicts (top_dicts, vsindex_dict, var_model, fd_map)
_cff_or_cff2 (font)
getfd_map (varFont, fonts_list)
merge_region_fonts (varFont, model, ordered_fonts_list, glyphOrder)
_get_cs (charstrings, glyphName, filterEmpty=False)
_add_new_vsindex (model, key, masterSupports, vsindex_dict, vsindex_by_key, varDataList)
merge_charstrings (glyphOrder, num_masters, top_dicts, masterModel)
Variables
MergeDictError = VarLibCFFDictMergeError
MergeTypeError = VarLibCFFPointTypeMergeError
tuple pd_blend_fields
CVarData = namedtuple("CVarData", "varDataList masterSupports vsindex_dict")
Function Documentation
_add_new_vsindex()
fontTools.varLib.cff._add_new_vsindex (model, key, masterSupports, vsindex_dict, vsindex_by_key, varDataList) protected
Definition at line 291 of file cff.py.
_cff_or_cff2()
fontTools.varLib.cff._cff_or_cff2 (font) protected
Definition at line 208 of file cff.py.
_get_cs()
fontTools.varLib.cff._get_cs (charstrings, glyphName, filterEmpty = False) protected
Definition at line 272 of file cff.py.
addCFFVarStore()
fontTools.varLib.cff.addCFFVarStore (varFont, varModel, varDataList, masterSupports)
Definition at line 38 of file cff.py.
conv_to_int()
fontTools.varLib.cff.conv_to_int (num)
Definition at line 60 of file cff.py.
convertCFFtoCFF2()
fontTools.varLib.cff.convertCFFtoCFF2 (varFont)
Definition at line 54 of file cff.py.
get_private()
fontTools.varLib.cff.get_private (regionFDArrays, fd_index, ri, fd_map)
Definition at line 81 of file cff.py.
getfd_map()
fontTools.varLib.cff.getfd_map (varFont, fonts_list)
Since a subset source font may have fewer FontDicts in their
FDArray than the default font, we have to match up the FontDicts in
the different fonts . We do this with the FDSelect array, and by
assuming that the same glyph will reference  matching FontDicts in
each source font. We return a mapping from fdIndex in the default
font to a dictionary which maps each master list index of each
region font to the equivalent fdIndex in the region font.
Definition at line 214 of file cff.py.
References getfd_map(), and merge_PrivateDicts().
Referenced by getfd_map().
merge_charstrings()
fontTools.varLib.cff.merge_charstrings (glyphOrder, num_masters, top_dicts, masterModel)
Definition at line 307 of file cff.py.
merge_PrivateDicts()
fontTools.varLib.cff.merge_PrivateDicts (top_dicts, vsindex_dict, var_model, fd_map)
I step through the FontDicts in the FDArray of the varfont TopDict.
For each varfont FontDict:
* step through each key in FontDict.Private.
* For each key, step through each relevant source font Private dict, and
  build a list of values to blend.
The 'relevant' source fonts are selected by first getting the right
submodel using ``vsindex_dict[vsindex]``. The indices of the
``subModel.locations`` are mapped to source font list indices by
assuming the latter order is the same as the order of the
``var_model.locations``. I can then get the index of each subModel
location in the list of ``var_model.locations``.
Definition at line 92 of file cff.py.
Referenced by getfd_map().
merge_region_fonts()
fontTools.varLib.cff.merge_region_fonts (varFont, model, ordered_fonts_list, glyphOrder)
Definition at line 260 of file cff.py.
Variable Documentation
CVarData
fontTools.varLib.cff.CVarData = namedtuple("CVarData", "varDataList masterSupports vsindex_dict")
Definition at line 257 of file cff.py.
MergeDictError
fontTools.varLib.cff.MergeDictError = VarLibCFFDictMergeError
Definition at line 34 of file cff.py.
MergeTypeError
fontTools.varLib.cff.MergeTypeError = VarLibCFFPointTypeMergeError
Definition at line 35 of file cff.py.
pd_blend_fields
tuple fontTools.varLib.cff.pd_blend_fields
Initial value:
=  (
    "BlueValues",
    "OtherBlues",
    "FamilyBlues",
    "FamilyOtherBlues",
    "BlueScale",
    "BlueShift",
    "BlueFuzz",
    "StdHW",
    "StdVW",
    "StemSnapH",
    "StemSnapV",
)
Definition at line 66 of file cff.py.