Code Cloning Analysis: pyparsing.actions Namespace Reference
pyparsing.actions Namespace Reference
Classes
class OnlyOnce
Functions
ParseAction match_only_at_col (int n)
ParseAction replace_with (str repl_str)
Any remove_quotes (str s, int l, ParseResults t)
ParseAction with_attribute (*tuple[str, str] args, **attr_dict)
ParseAction with_class (str classname, str namespace="")
Variables
ParseAction
ANY_VALUE
replaceWith = replaced_by_pep8("replaceWith", replace_with)
removeQuotes = replaced_by_pep8("removeQuotes", remove_quotes)
withAttribute = replaced_by_pep8("withAttribute", with_attribute)
withClass = replaced_by_pep8("withClass", with_class)
matchOnlyAtCol = replaced_by_pep8("matchOnlyAtCol", match_only_at_col)
Function Documentation
match_only_at_col()
ParseAction pyparsing.actions.match_only_at_col (int n)
Helper method for defining parse actions that require matching at
a specific column in the input text.
Definition at line 46 of file actions.py.
References pyparsing.util.col().
remove_quotes()
Any pyparsing.actions.remove_quotes (str s, int l, ParseResults t)
Helper parse action for removing quotation marks from parsed
quoted strings.
Example::
    # by default, quotation marks are included in parsed results
    quoted_string.parse_string("'Now is the Winter of our Discontent'") # -> ["'Now is the Winter of our Discontent'"]
    # use remove_quotes to strip quotation marks from parsed results
    quoted_string.set_parse_action(remove_quotes)
    quoted_string.parse_string("'Now is the Winter of our Discontent'") # -> ["Now is the Winter of our Discontent"]
Definition at line 76 of file actions.py.
replace_with()
ParseAction pyparsing.actions.replace_with (str repl_str)
Helper method for common parse actions that simply return
a literal value.  Especially useful when used with
:class:`transform_string<ParserElement.transform_string>` ().
Example::
    num = Word(nums).set_parse_action(lambda toks: int(toks[0]))
    na = one_of("N/A NA").set_parse_action(replace_with(math.nan))
    term = na | num
    term[1, ...].parse_string("324 234 N/A 234") # -> [324, 234, nan, 234]
Definition at line 59 of file actions.py.
Referenced by pyparsing.core.ParserElement.run_tests().
with_attribute()
ParseAction pyparsing.actions.with_attribute (*tuple[str, str] args, ** attr_dict)
Helper to create a validating parse action to be used with start
tags created with :class:`make_xml_tags` or
:class:`make_html_tags`. Use ``with_attribute`` to qualify
a starting tag with a required attribute value, to avoid false
matches on common tags such as ``<TD>`` or ``<DIV>``.
Call ``with_attribute`` with a series of attribute names and
values. Specify the list of filter attributes names and values as:
- keyword arguments, as in ``(align="right")``, or
- as an explicit dict with ``**`` operator, when an attribute
  name is also a Python reserved word, as in ``**{"class":"Customer", "align":"right"}``
- a list of name-value tuples, as in ``(("ns1:class", "Customer"), ("ns2:align", "right"))``
For attribute names with a namespace prefix, you must use the second
form.  Attribute names are matched insensitive to upper/lower case.
If just testing for ``class`` (with or without a namespace), use
:class:`with_class`.
To verify that the attribute exists, but without specifying a value,
pass ``with_attribute.ANY_VALUE`` as the value.
Example::
    html = '''
        <div>
        Some text
        <div type="grid">1 4 0 1 0</div>
        <div type="graph">1,3 2,3 1,1</div>
        <div>this has no type</div>
        </div>
    '''
    div,div_end = make_html_tags("div")
    # only match div tag having a type attribute with value "grid"
    div_grid = div().set_parse_action(with_attribute(type="grid"))
    grid_expr = div_grid + SkipTo(div | div_end)("body")
    for grid_header in grid_expr.search_string(html):
        print(grid_header.body)
    # construct a match with any div tag having a type attribute, regardless of the value
    div_any_type = div().set_parse_action(with_attribute(type=with_attribute.ANY_VALUE))
    div_expr = div_any_type + SkipTo(div | div_end)("body")
    for div_header in div_expr.search_string(html):
        print(div_header.body)
prints::
    1 4 0 1 0
    1 4 0 1 0
    1,3 2,3 1,1
Definition at line 93 of file actions.py.
Referenced by with_class().
with_class()
ParseAction pyparsing.actions.with_class (str classname, str namespace = "")
Simplified version of :class:`with_attribute` when
matching on a div class - made difficult because ``class`` is
a reserved word in Python.
Example::
    html = '''
        <div>
        Some text
        <div class="grid">1 4 0 1 0</div>
        <div class="graph">1,3 2,3 1,1</div>
        <div>this &lt;div&gt; has no class</div>
        </div>
    '''
    div,div_end = make_html_tags("div")
    div_grid = div().set_parse_action(with_class("grid"))
    grid_expr = div_grid + SkipTo(div | div_end)("body")
    for grid_header in grid_expr.search_string(html):
        print(grid_header.body)
    div_any_type = div().set_parse_action(with_class(withAttribute.ANY_VALUE))
    div_expr = div_any_type + SkipTo(div | div_end)("body")
    for div_header in div_expr.search_string(html):
        print(div_header.body)
prints::
    1 4 0 1 0
    1 4 0 1 0
    1,3 2,3 1,1
Definition at line 172 of file actions.py.
References with_attribute().
Variable Documentation
ANY_VALUE
pyparsing.actions.ANY_VALUE
Definition at line 169 of file actions.py.
matchOnlyAtCol
pyparsing.actions.matchOnlyAtCol = replaced_by_pep8("matchOnlyAtCol", match_only_at_col)
Definition at line 218 of file actions.py.
ParseAction
pyparsing.actions.ParseAction
Initial value:
=  Union[
    Callable[[], Any],
    Callable[[ParseResults], Any],
    Callable[[int, ParseResults], Any],
    Callable[[str, int, ParseResults], Any],
]
Definition at line 11 of file actions.py.
removeQuotes
pyparsing.actions.removeQuotes = replaced_by_pep8("removeQuotes", remove_quotes)
Definition at line 215 of file actions.py.
replaceWith
pyparsing.actions.replaceWith = replaced_by_pep8("replaceWith", replace_with)
Definition at line 214 of file actions.py.
withAttribute
pyparsing.actions.withAttribute = replaced_by_pep8("withAttribute", with_attribute)
Definition at line 216 of file actions.py.
withClass
pyparsing.actions.withClass = replaced_by_pep8("withClass", with_class)
Definition at line 217 of file actions.py.