Code Cloning Analysis: fontTools.voltLib.voltToFea.VoltToFea Class Reference
fontTools.voltLib.voltToFea.VoltToFea Class Reference
Public Member Functions
__init__ (self, file_or_path, font=None)
convert (self, tables=None, ignore_unsupported_settings=False)
Protected Member Functions
_lookupName (self, name)
_className (self, name)
_collectStatements (self, doc, tables, ignore_unsupported_settings=False)
_buildFeatureFile (self, tables)
_glyphName (self, glyph)
_groupName (self, group)
_glyphSet (self, item)
_coverage (self, coverage, flatten=False)
_context (self, context)
_groupDefinition (self, group)
_glyphDefinition (self, glyph)
_scriptDefinition (self, script)
_settingDefinition (self, setting, ignore_unsupported=False)
_adjustment (self, adjustment)
_anchor (self, adjustment)
_anchorDefinition (self, anchordef)
_gposLookup (self, lookup, fealookup)
_gposContextLookup (self, lookup, prefix, suffix, ignore, fealookup, chained)
_gsubLookup (self, lookup, fealookup)
_gsubContextLookup (self, lookup, prefix, suffix, ignore, fealookup, chained)
_lookupDefinition (self, lookup)
Protected Attributes
_doc
_file_or_path = file_or_path, None
_font = font
dict _glyph_map = {}
_glyph_order = None
dict _gdef = {}
dict _glyphclasses = {}
dict _features = {}
dict _lookups = {}
_marks = set()
dict _ligatures = {}
dict _markclasses = {}
dict _anchors = {}
dict _settings = {}
dict _lookup_names = {}
dict _class_names = {}
Static Protected Attributes
_NOT_LOOKUP_NAME_RE = re.compile(r"[^A-Za-z_0-9.]")
_NOT_CLASS_NAME_RE = re.compile(r"[^A-Za-z_0-9.\-]")
Detailed Description
Definition at line 96 of file voltToFea.py.
Constructor & Destructor Documentation
__init__()
fontTools.voltLib.voltToFea.VoltToFea.__init__ (self, file_or_path, font = None)
Definition at line 100 of file voltToFea.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_adjustment()
fontTools.voltLib.voltToFea.VoltToFea._adjustment (self, adjustment) protected
Definition at line 377 of file voltToFea.py.
_anchor()
fontTools.voltLib.voltToFea.VoltToFea._anchor (self, adjustment) protected
Definition at line 393 of file voltToFea.py.
_anchorDefinition()
fontTools.voltLib.voltToFea.VoltToFea._anchorDefinition (self, anchordef) protected
Definition at line 407 of file voltToFea.py.
_buildFeatureFile()
fontTools.voltLib.voltToFea.VoltToFea._buildFeatureFile (self, tables) protected
Definition at line 178 of file voltToFea.py.
_className()
fontTools.voltLib.voltToFea.VoltToFea._className (self, name) protected
Definition at line 134 of file voltToFea.py.
_collectStatements()
fontTools.voltLib.voltToFea.VoltToFea._collectStatements (self, doc, tables, ignore_unsupported_settings = False) protected
Definition at line 142 of file voltToFea.py.
_context()
fontTools.voltLib.voltToFea.VoltToFea._context (self, context) protected
Definition at line 323 of file voltToFea.py.
_coverage()
fontTools.voltLib.voltToFea.VoltToFea._coverage (self, coverage, flatten = False) protected
Definition at line 300 of file voltToFea.py.
_glyphDefinition()
fontTools.voltLib.voltToFea.VoltToFea._glyphDefinition (self, glyph) protected
Definition at line 341 of file voltToFea.py.
_glyphName()
fontTools.voltLib.voltToFea.VoltToFea._glyphName (self, glyph) protected
Definition at line 280 of file voltToFea.py.
_glyphSet()
fontTools.voltLib.voltToFea.VoltToFea._glyphSet (self, item) protected
Definition at line 294 of file voltToFea.py.
_gposContextLookup()
fontTools.voltLib.voltToFea.VoltToFea._gposContextLookup (self, lookup, prefix, suffix, ignore, fealookup, chained) protected
Definition at line 555 of file voltToFea.py.
_gposLookup()
fontTools.voltLib.voltToFea.VoltToFea._gposLookup (self, lookup, fealookup) protected
Definition at line 422 of file voltToFea.py.
_groupDefinition()
fontTools.voltLib.voltToFea.VoltToFea._groupDefinition (self, group) protected
Definition at line 334 of file voltToFea.py.
_groupName()
fontTools.voltLib.voltToFea.VoltToFea._groupName (self, group) protected
Definition at line 287 of file voltToFea.py.
_gsubContextLookup()
fontTools.voltLib.voltToFea.VoltToFea._gsubContextLookup (self, lookup, prefix, suffix, ignore, fealookup, chained) protected
Definition at line 696 of file voltToFea.py.
_gsubLookup()
fontTools.voltLib.voltToFea.VoltToFea._gsubLookup (self, lookup, fealookup) protected
Definition at line 601 of file voltToFea.py.
_lookupDefinition()
fontTools.voltLib.voltToFea.VoltToFea._lookupDefinition (self, lookup) protected
Definition at line 746 of file voltToFea.py.
_lookupName()
fontTools.voltLib.voltToFea.VoltToFea._lookupName (self, name) protected
Definition at line 126 of file voltToFea.py.
_scriptDefinition()
fontTools.voltLib.voltToFea.VoltToFea._scriptDefinition (self, script) protected
Definition at line 357 of file voltToFea.py.
_settingDefinition()
fontTools.voltLib.voltToFea.VoltToFea._settingDefinition (self, setting, ignore_unsupported = False) protected
Definition at line 371 of file voltToFea.py.
convert()
fontTools.voltLib.voltToFea.VoltToFea.convert (self, tables = None, ignore_unsupported_settings = False)
Definition at line 266 of file voltToFea.py.
Referenced by matplotlib.testing.jpl_units.Epoch.Epoch.__add__(), matplotlib.testing.jpl_units.Epoch.Epoch.__init__(), matplotlib.testing.jpl_units.Epoch.Epoch.__sub__(), matplotlib.testing.jpl_units.Epoch.Epoch._cmp(), pandas.core.computation.engines.NumExprEngine._evaluate(), pandas.core.internals.blocks.Block.convert(), PIL.Image.Image.reduce(), PIL.Image.Image.resize(), and PIL.Image.Image.transform().
Member Data Documentation
_anchors
dict fontTools.voltLib.voltToFea.VoltToFea._anchors = {} protected
Definition at line 119 of file voltToFea.py.
_class_names
dict fontTools.voltLib.voltToFea.VoltToFea._class_names = {} protected
Definition at line 124 of file voltToFea.py.
_doc
fontTools.voltLib.voltToFea.VoltToFea._doc protected
Definition at line 102 of file voltToFea.py.
Referenced by scipy._lib._docscrape.NumpyDocString._parse_summary().
_features
dict fontTools.voltLib.voltToFea.VoltToFea._features = {} protected
Definition at line 112 of file voltToFea.py.
_file_or_path
fontTools.voltLib.voltToFea.VoltToFea._file_or_path = file_or_path, None protected
Definition at line 102 of file voltToFea.py.
_font
fontTools.voltLib.voltToFea.VoltToFea._font = font protected
Definition at line 105 of file voltToFea.py.
_gdef
dict fontTools.voltLib.voltToFea.VoltToFea._gdef = {} protected
Definition at line 110 of file voltToFea.py.
_glyph_map
dict fontTools.voltLib.voltToFea.VoltToFea._glyph_map = {} protected
Definition at line 107 of file voltToFea.py.
Referenced by matplotlib.backends.backend_svg.RendererSVG._draw_text_as_path(), and matplotlib.backends.backend_svg.RendererSVG._update_glyph_map_defs().
_glyph_order
fontTools.voltLib.voltToFea.VoltToFea._glyph_order = None protected
Definition at line 108 of file voltToFea.py.
_glyphclasses
dict fontTools.voltLib.voltToFea.VoltToFea._glyphclasses = {} protected
Definition at line 111 of file voltToFea.py.
_ligatures
dict fontTools.voltLib.voltToFea.VoltToFea._ligatures = {} protected
Definition at line 116 of file voltToFea.py.
_lookup_names
dict fontTools.voltLib.voltToFea.VoltToFea._lookup_names = {} protected
Definition at line 123 of file voltToFea.py.
_lookups
dict fontTools.voltLib.voltToFea.VoltToFea._lookups = {} protected
Definition at line 113 of file voltToFea.py.
_markclasses
dict fontTools.voltLib.voltToFea.VoltToFea._markclasses = {} protected
Definition at line 118 of file voltToFea.py.
_marks
fontTools.voltLib.voltToFea.VoltToFea._marks = set() protected
Definition at line 115 of file voltToFea.py.
_NOT_CLASS_NAME_RE
fontTools.voltLib.voltToFea.VoltToFea._NOT_CLASS_NAME_RE = re.compile(r"[^A-Za-z_0-9.\-]") static protected
Definition at line 98 of file voltToFea.py.
_NOT_LOOKUP_NAME_RE
fontTools.voltLib.voltToFea.VoltToFea._NOT_LOOKUP_NAME_RE = re.compile(r"[^A-Za-z_0-9.]") static protected
Definition at line 97 of file voltToFea.py.
_settings
dict fontTools.voltLib.voltToFea.VoltToFea._settings = {} protected
Definition at line 121 of file voltToFea.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/voltLib/voltToFea.py