Code Cloning Analysis: pandas.core.dtypes.base.StorageExtensionDtype Class Reference
pandas.core.dtypes.base.StorageExtensionDtype Class Reference
Public Member Functions
None __init__ (self, str|None storage=None)
str __repr__ (self)
str __str__ (self)
bool __eq__ (self, object other)
int __hash__ (self)
libmissing.NAType na_value (self)
Public Member Functions inherited from pandas.core.dtypes.base.ExtensionDtype
str __str__ (self)
bool __eq__ (self, object other)
int __hash__ (self)
bool __ne__ (self, object other)
type_t[Any] type (self)
str kind (self)
str name (self)
list[str]|None names (self)
type_t[ExtensionArray] construct_array_type (cls)
ExtensionArray empty (self, Shape shape)
Self construct_from_string (cls, str string)
bool is_dtype (cls, object dtype)
type_t[Index] index_class (self)
Public Attributes
storage = storage
Public Attributes inherited from pandas.core.dtypes.base.ExtensionDtype
name
Additional Inherited Members
Protected Member Functions inherited from pandas.core.dtypes.base.ExtensionDtype
bool _is_numeric (self)
bool _is_boolean (self)
DtypeObj|None _get_common_dtype (self, list[DtypeObj] dtypes)
bool _can_hold_na (self)
bool _is_immutable (self)
bool _supports_2d (self)
bool _can_fast_transpose (self)
Static Protected Attributes inherited from pandas.core.dtypes.base.ExtensionDtype
tuple _metadata = ()
Detailed Description
ExtensionDtype that may be backed by more than one implementation.
Definition at line 449 of file base.py.
Constructor & Destructor Documentation
__init__()
None pandas.core.dtypes.base.StorageExtensionDtype.__init__ (self, str | None storage = None)
Definition at line 455 of file base.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__eq__()
bool pandas.core.dtypes.base.StorageExtensionDtype.__eq__ (self, object other)
Definition at line 464 of file base.py.
Referenced by pandas.io.pytables.IndexCol.__eq__(), pip._vendor.msgpack.ext.Timestamp.__ne__(), and pip._vendor.distlib.version.Matcher.match().
__hash__()
int pandas.core.dtypes.base.StorageExtensionDtype.__hash__ (self)
Definition at line 469 of file base.py.
Referenced by pip._vendor.rich.style.Style.pick_first().
__repr__()
str pandas.core.dtypes.base.StorageExtensionDtype.__repr__ (self)
Definition at line 458 of file base.py.
__str__()
str pandas.core.dtypes.base.StorageExtensionDtype.__str__ (self)
Definition at line 461 of file base.py.
na_value()
libmissing.NAType pandas.core.dtypes.base.StorageExtensionDtype.na_value (self)
Default NA value to use for this type.
This is used in e.g. ExtensionArray.take. This should be the
user-facing "boxed" version of the NA value, not the physical NA value
for storage.  e.g. for JSONArray, this is an empty dictionary.
Reimplemented from pandas.core.dtypes.base.ExtensionDtype.
Reimplemented in pandas.core.arrays.string_.StringDtype.
Definition at line 474 of file base.py.
Member Data Documentation
storage
pandas.core.dtypes.base.StorageExtensionDtype.storage = storage
Definition at line 456 of file base.py.
Referenced by scipy.optimize._basinhopping.BasinHoppingRunner.one_cycle(), and scipy.optimize._basinhopping.BasinHoppingRunner.print_report().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/core/dtypes/base.py