Code Cloning Analysis: scipy.integrate._quad_vec.DoubleInfiniteFunc Class Reference
scipy.integrate._quad_vec.DoubleInfiniteFunc Class Reference
Public Member Functions
__init__ (self, func)
get_t (self, x)
__call__ (self, t)
Protected Attributes
_func = func
float _tmin = sys.float_info.min**0.5
Detailed Description
Argument transform from (-oo, oo) to (-1, 1)
Definition at line 57 of file _quad_vec.py.
Constructor & Destructor Documentation
__init__()
scipy.integrate._quad_vec.DoubleInfiniteFunc.__init__ (self, func)
Definition at line 61 of file _quad_vec.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
__call__()
scipy.integrate._quad_vec.DoubleInfiniteFunc.__call__ (self, t)
Definition at line 71 of file _quad_vec.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), and scipy.interpolate._fitpack2.SphereBivariateSpline.ev().
get_t()
scipy.integrate._quad_vec.DoubleInfiniteFunc.get_t (self, x)
Definition at line 67 of file _quad_vec.py.
Member Data Documentation
_func
scipy.integrate._quad_vec.DoubleInfiniteFunc._func = func protected
Definition at line 62 of file _quad_vec.py.
_tmin
float scipy.integrate._quad_vec.DoubleInfiniteFunc._tmin = sys.float_info.min**0.5 protected
Definition at line 65 of file _quad_vec.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/integrate/_quad_vec.py