Code Cloning Analysis: fontTools.misc.filesystem._osfs.OSFS Class Reference
fontTools.misc.filesystem._osfs.OSFS Class Reference
Public Member Functions
__init__ (self, str|PathLike root, bool create=False)
IO[Any] open (self, str path, str mode="rb", **kwargs)
bool exists (self, str path)
bool isdir (self, str path)
bool isfile (self, str path)
list[str] listdir (self, str path)
SubFS makedir (self, str path, bool recreate=False)
SubFS makedirs (self, str path, bool recreate=False)
Info getinfo (self, str path, Collection[str]|None namespaces=None)
remove (self, str path)
removedir (self, str path)
removetree (self, str path)
movedir (self, str src_dir, str dst_dir, bool create=False)
str getsyspath (self, str path)
str __repr__ (self)
str __str__ (self)
Public Member Functions inherited from fontTools.misc.filesystem._base.FS
close (self)
bool isclosed (self)
Self __enter__ (self)
__exit__ (self, exc_type, exc, tb)
check (self)
SubFS opendir (self, str path, *, Type[SubFS]|None factory=None)
Iterator[Info] scandir (self, str path, Collection[str]|None namespaces=None)
BoundWalker walk (self)
bytes readbytes (self, str path)
writebytes (self, str path, bytes data)
create (self, str path, bool wipe=False)
copy (self, str src_path, str dst_path, overwrite=False)
copydir (self, str src_path, str dst_path, create=False)
Protected Member Functions
Path _abs (self, str rel_path)
SubFS _mkdir (self, str path, bool parents=False, bool exist_ok=False)
Protected Attributes
_root = Path(root).resolve()
Additional Inherited Members
Static Protected Attributes inherited from fontTools.misc.filesystem._base.FS
bool _closed = False
Detailed Description
Filesystem for a directory on the local disk.
A thin layer on top of `pathlib.Path`.
Definition at line 34 of file _osfs.py.
Constructor & Destructor Documentation
__init__()
fontTools.misc.filesystem._osfs.OSFS.__init__ (self, str | PathLike root, bool create = False)
Definition at line 40 of file _osfs.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__repr__()
str fontTools.misc.filesystem._osfs.OSFS.__repr__ (self)
Definition at line 160 of file _osfs.py.
__str__()
str fontTools.misc.filesystem._osfs.OSFS.__str__ (self)
Definition at line 163 of file _osfs.py.
Referenced by numpy.polynomial._polybase.ABCPolyBase._get_coefficients().
_abs()
Path fontTools.misc.filesystem._osfs.OSFS._abs (self, str rel_path) protected
Definition at line 51 of file _osfs.py.
_mkdir()
SubFS fontTools.misc.filesystem._osfs.OSFS._mkdir (self, str path, bool parents = False, bool exist_ok = False) protected
Definition at line 73 of file _osfs.py.
exists()
bool fontTools.misc.filesystem._osfs.OSFS.exists (self, str path)
Reimplemented from fontTools.misc.filesystem._base.FS.
Definition at line 61 of file _osfs.py.
Referenced by numpy.lib._datasource.DataSource._findfile().
getinfo()
Info fontTools.misc.filesystem._osfs.OSFS.getinfo (self, str path, Collection[str] | None namespaces = None)
Reimplemented from fontTools.misc.filesystem._base.FS.
Definition at line 83 of file _osfs.py.
getsyspath()
str fontTools.misc.filesystem._osfs.OSFS.getsyspath (self, str path)
Reimplemented from fontTools.misc.filesystem._base.FS.
Definition at line 157 of file _osfs.py.
isdir()
bool fontTools.misc.filesystem._osfs.OSFS.isdir (self, str path)
Reimplemented from fontTools.misc.filesystem._base.FS.
Definition at line 64 of file _osfs.py.
isfile()
bool fontTools.misc.filesystem._osfs.OSFS.isfile (self, str path)
Reimplemented from fontTools.misc.filesystem._base.FS.
Definition at line 67 of file _osfs.py.
listdir()
list[str] fontTools.misc.filesystem._osfs.OSFS.listdir (self, str path)
Reimplemented from fontTools.misc.filesystem._base.FS.
Definition at line 70 of file _osfs.py.
makedir()
SubFS fontTools.misc.filesystem._osfs.OSFS.makedir (self, str path, bool recreate = False)
Reimplemented from fontTools.misc.filesystem._base.FS.
Definition at line 77 of file _osfs.py.
makedirs()
SubFS fontTools.misc.filesystem._osfs.OSFS.makedirs (self, str path, bool recreate = False)
Reimplemented from fontTools.misc.filesystem._base.FS.
Definition at line 80 of file _osfs.py.
movedir()
fontTools.misc.filesystem._osfs.OSFS.movedir (self, str src_dir, str dst_dir, bool create = False)
Reimplemented from fontTools.misc.filesystem._base.FS.
Definition at line 133 of file _osfs.py.
open()
IO[Any] fontTools.misc.filesystem._osfs.OSFS.open (self, str path, str mode = "rb", ** kwargs)
Reimplemented from fontTools.misc.filesystem._base.FS.
Definition at line 55 of file _osfs.py.
remove()
fontTools.misc.filesystem._osfs.OSFS.remove (self, str path)
Reimplemented from fontTools.misc.filesystem._base.FS.
Definition at line 107 of file _osfs.py.
Referenced by pip._internal.operations.build.build_tracker.BuildTracker.remove(), pandas.io.pytables.HDFStore.root(), and pip._internal.operations.build.build_tracker.BuildTracker.track().
removedir()
fontTools.misc.filesystem._osfs.OSFS.removedir (self, str path)
Reimplemented from fontTools.misc.filesystem._base.FS.
Definition at line 119 of file _osfs.py.
removetree()
fontTools.misc.filesystem._osfs.OSFS.removetree (self, str path)
Reimplemented from fontTools.misc.filesystem._base.FS.
Definition at line 130 of file _osfs.py.
Member Data Documentation
_root
fontTools.misc.filesystem._osfs.OSFS._root = Path(root).resolve() protected
Definition at line 42 of file _osfs.py.
Referenced by pip._internal.operations.build.build_tracker.BuildTracker.add(), and pip._internal.operations.build.build_tracker.BuildTracker.remove().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/misc/filesystem/_osfs.py