Code Cloning Analysis: pandas.core.indexes.api Namespace Reference
pandas.core.indexes.api Namespace Reference
Functions
Index get_objs_combined_axis (objs, bool intersect=False, Axis axis=0, bool sort=True, bool copy=False)
list[Index] _get_distinct_objs (list[Index] objs)
Index _get_combined_index (list[Index] indexes, bool intersect=False, bool sort=False, bool copy=False)
Index safe_sort_index (Index index)
Index union_indexes (indexes, bool|None sort=True)
_sanitize_and_check (indexes)
bool all_indexes_same (indexes)
RangeIndex default_index (int n)
Variables
_sort_msg
list __all__
Function Documentation
_get_combined_index()
Index pandas.core.indexes.api._get_combined_index (list[Index] indexes, bool intersect = False, bool sort = False, bool copy = False) protected
Return the union or intersection of indexes.
Parameters
----------
indexes : list of Index or list objects
    When intersect=True, do not accept list of lists.
intersect : bool, default False
    If True, calculate the intersection between indexes. Otherwise,
    calculate the union.
sort : bool, default False
    Whether the result index should come out sorted or not.
copy : bool, default False
    If True, return a copy of the combined index.
Returns
-------
Index
Definition at line 120 of file api.py.
References _get_distinct_objs(), safe_sort_index(), and union_indexes().
Referenced by get_objs_combined_axis().
_get_distinct_objs()
list[Index] pandas.core.indexes.api._get_distinct_objs (list[Index] objs) protected
Return a list with distinct elements of "objs" (different ids).
Preserves order.
Definition at line 106 of file api.py.
Referenced by _get_combined_index().
_sanitize_and_check()
pandas.core.indexes.api._sanitize_and_check (indexes) protected
Verify the type of indexes and convert lists to Index.
Cases:
- [list, list, ...]: Return ([list, list, ...], 'list')
- [list, Index, ...]: Return _sanitize_and_check([Index, Index, ...])
    Lists are sorted and converted to Index.
- [Index, Index, ...]: Return ([Index, Index, ...], TYPE)
    TYPE = 'special' if at least one special type, 'array' otherwise.
Parameters
----------
indexes : list of Index or list objects
Returns
-------
sanitized_indexes : list of Index or list objects
type : {'list', 'array', 'special'}
Definition at line 330 of file api.py.
Referenced by union_indexes().
all_indexes_same()
bool pandas.core.indexes.api.all_indexes_same (indexes)
Determine if all indexes contain the same elements.
Parameters
----------
indexes : iterable of Index objects
Returns
-------
bool
    True if all indexes contain the same elements, False otherwise.
Definition at line 368 of file api.py.
default_index()
RangeIndex pandas.core.indexes.api.default_index (int n)
Definition at line 386 of file api.py.
get_objs_combined_axis()
Index pandas.core.indexes.api.get_objs_combined_axis (objs, bool intersect = False, Axis axis = 0, bool sort = True, bool copy = False)
Extract combined index: return intersection or union (depending on the
value of "intersect") of indexes on given axis, or None if all objects
lack indexes (e.g. they are numpy arrays).
Parameters
----------
objs : list
    Series or DataFrame objects, may be mix of the two.
intersect : bool, default False
    If True, calculate the intersection between indexes. Otherwise,
    calculate the union.
axis : {0 or 'index', 1 or 'outer'}, default 0
    The axis to extract indexes from.
sort : bool, default True
    Whether the result index should come out sorted or not.
copy : bool, default False
    If True, return a copy of the combined index.
Returns
-------
Index
Definition at line 72 of file api.py.
References _get_combined_index().
safe_sort_index()
Index pandas.core.indexes.api.safe_sort_index (Index index)
Returns the sorted index
We keep the dtypes and the name attributes.
Parameters
----------
index : an Index
Returns
-------
Index
Definition at line 168 of file api.py.
Referenced by _get_combined_index().
union_indexes()
Index pandas.core.indexes.api.union_indexes (indexes, bool | None sort = True)
Return the union of indexes.
The behavior of sort and names is not consistent.
Parameters
----------
indexes : list of Index or list objects
sort : bool, default True
    Whether the result index should come out sorted or not.
Returns
-------
Index
Definition at line 202 of file api.py.
References _sanitize_and_check().
Referenced by _get_combined_index().
Variable Documentation
__all__
list pandas.core.indexes.api.__all__ private
Initial value:
=  [
    "Index",
    "MultiIndex",
    "CategoricalIndex",
    "IntervalIndex",
    "RangeIndex",
    "InvalidIndexError",
    "TimedeltaIndex",
    "PeriodIndex",
    "DatetimeIndex",
    "_new_Index",
    "NaT",
    "ensure_index",
    "ensure_index_from_sequences",
    "get_objs_combined_axis",
    "union_indexes",
    "get_unanimous_names",
    "all_indexes_same",
    "default_index",
    "safe_sort_index",
]
Definition at line 49 of file api.py.
_sort_msg
pandas.core.indexes.api._sort_msg protected
Initial value:
=  textwrap.dedent(
)
Definition at line 37 of file api.py.