Code Cloning Analysis: numpy.lib.index_tricks.CClass Class Reference
numpy.lib.index_tricks.CClass Class Reference
Public Member Functions
__init__ (self)
Public Member Functions inherited from numpy.lib.index_tricks.AxisConcatenator
__init__ (self, axis=0, matrix=False, ndmin=1, trans1d=-1)
__getitem__ (self, key)
__len__ (self)
Additional Inherited Members
Public Attributes inherited from numpy.lib.index_tricks.AxisConcatenator
axis = axis
matrix = matrix
trans1d = trans1d
ndmin = ndmin
Static Public Attributes inherited from numpy.lib.index_tricks.AxisConcatenator
concatenate = staticmethod(_nx.concatenate)
makemat = staticmethod(matrixlib.matrix)
Detailed Description
Translates slice objects to concatenation along the second axis.
This is short-hand for ``np.r_['-1,2,0', index expression]``, which is
useful because of its common occurrence. In particular, arrays will be
stacked along their last axis after being upgraded to at least 2-D with
1's post-pended to the shape (column vectors made out of 1-D arrays).
See Also
--------
column_stack : Stack 1-D arrays as columns into a 2-D array.
r_ : For more detailed documentation.
Examples
--------
>>> np.c_[np.array([1,2,3]), np.array([4,5,6])]
array([[1, 4],
       [2, 5],
       [3, 6]])
>>> np.c_[np.array([[1,2,3]]), 0, 0, np.array([[4,5,6]])]
array([[1, 2, 3, ..., 4, 5, 6]])
Definition at line 537 of file index_tricks.py.
Constructor & Destructor Documentation
__init__()
numpy.lib.index_tricks.CClass.__init__ (self)
Definition at line 562 of file index_tricks.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/lib/index_tricks.py