Code Cloning Analysis: pandas.core.common Namespace Reference
pandas.core.common Namespace Reference
Functions
flatten (line)
consensus_name_attr (objs)
bool is_bool_indexer (Any key)
cast_scalar_indexer (val)
not_none (*args)
bool any_none (*args)
bool all_none (*args)
bool any_not_none (*args)
bool all_not_none (*args)
int count_not_none (*args)
np.ndarray asarray_tuplesafe (ArrayLike|list|tuple|zip values, NpDtype|None dtype=...)
ArrayLike asarray_tuplesafe (Iterable values, NpDtype|None dtype=...)
np.ndarray index_labels_to_array (np.ndarray|Iterable labels, NpDtype|None dtype=None)
maybe_make_list (obj)
Collection[T]|T maybe_iterable_to_list (Iterable[T]|T obj)
bool is_null_slice (obj)
bool is_empty_slice (obj)
list[bool] is_true_slices (line)
bool is_full_slice (obj, int line)
get_callable_name (obj)
apply_if_callable (maybe_callable, obj, **kwargs)
standardize_mapping (into)
np.random.Generator random_state (np.random.Generator state)
np.random.RandomState random_state (int|np.ndarray|np.random.BitGenerator|np.random.RandomState|None state)
random_state (RandomState|None state=None)
T pipe (obj, Callable[..., T]|tuple[Callable[..., T], str] func, *args, **kwargs)
get_rename_function (mapper)
list|AnyArrayLike convert_to_list_like (Hashable|Iterable|AnyArrayLike values)
Generator[None, None, None] temp_setattr (obj, str attr, value, bool condition=True)
None require_length_match (data, Index index)
str|None get_cython_func (Callable arg)
is_builtin_func (arg)
list[Hashable] fill_missing_names (Sequence[Hashable|None] names)
Variables
dict _builtin_table
dict _builtin_table_alias
dict _cython_table
Detailed Description
Misc tools for implementing data structures
Note: pandas.core.common is *not* part of the public API.
Function Documentation
all_none()
bool pandas.core.common.all_none (* args)
Returns a boolean indicating if all arguments are None.
Definition at line 188 of file common.py.
all_not_none()
bool pandas.core.common.all_not_none (* args)
Returns a boolean indicating if all arguments are not None.
Definition at line 202 of file common.py.
any_none()
bool pandas.core.common.any_none (* args)
Returns a boolean indicating if any argument is None.
Definition at line 181 of file common.py.
any_not_none()
bool pandas.core.common.any_not_none (* args)
Returns a boolean indicating if any argument is not None.
Definition at line 195 of file common.py.
apply_if_callable()
pandas.core.common.apply_if_callable (maybe_callable, obj, ** kwargs)
Evaluate possibly callable input using obj and kwargs if it is callable,
otherwise return as it is.
Parameters
----------
maybe_callable : possibly a callable
obj : NDFrame
**kwargs
Definition at line 372 of file common.py.
asarray_tuplesafe() [1/2]
np.ndarray pandas.core.common.asarray_tuplesafe (ArrayLike | list | tuple | zip values, NpDtype | None dtype = ...)
Definition at line 217 of file common.py.
asarray_tuplesafe() [2/2]
ArrayLike pandas.core.common.asarray_tuplesafe (Iterable values, NpDtype | None dtype = ...)
Definition at line 227 of file common.py.
cast_scalar_indexer()
pandas.core.common.cast_scalar_indexer (val)
Disallow indexing with a float key, even if that key is a round number.
Parameters
----------
val : scalar
Returns
-------
outval : scalar
Definition at line 152 of file common.py.
consensus_name_attr()
pandas.core.common.consensus_name_attr (objs)
Definition at line 86 of file common.py.
convert_to_list_like()
list | AnyArrayLike pandas.core.common.convert_to_list_like (Hashable | Iterable | AnyArrayLike values)
Convert list-like or scalar input to list-like. List, numpy and pandas array-like
inputs are returned unmodified whereas others are converted to list.
Definition at line 520 of file common.py.
count_not_none()
int pandas.core.common.count_not_none (* args)
Returns the count of arguments that are not None.
Definition at line 209 of file common.py.
fill_missing_names()
list[Hashable] pandas.core.common.fill_missing_names (Sequence[Hashable | None] names)
If a name is missing then replace it by level_n, where n is the count
.. versionadded:: 1.4.0
Parameters
----------
names : list-like
    list of column names or None values.
Returns
-------
list
    list of column names with the None values replaced.
Definition at line 641 of file common.py.
flatten()
pandas.core.common.flatten (line)
Flatten an arbitrarily nested sequence.
Parameters
----------
line : sequence
    The non string sequence to flatten
Notes
-----
This doesn't consider strings sequences.
Returns
-------
flattened : generator
Definition at line 62 of file common.py.
References flatten().
Referenced by flatten().
get_callable_name()
pandas.core.common.get_callable_name (obj)
Definition at line 355 of file common.py.
get_cython_func()
str | None pandas.core.common.get_cython_func (Callable arg)
if we define an internal function for this argument, return it
Definition at line 626 of file common.py.
get_rename_function()
pandas.core.common.get_rename_function (mapper)
Returns a function that will map names/labels, dependent if mapper
is a dict, Series or just a function.
Definition at line 505 of file common.py.
index_labels_to_array()
np.ndarray pandas.core.common.index_labels_to_array (np.ndarray | Iterable labels, NpDtype | None dtype = None)
Transform label or iterable of labels to array, for use in Index.
Parameters
----------
dtype : dtype
    If specified, use as dtype of the resulting array, otherwise infer.
Returns
-------
array
Definition at line 266 of file common.py.
is_bool_indexer()
bool pandas.core.common.is_bool_indexer (Any key)
Check whether `key` is a valid boolean indexer.
Parameters
----------
key : Any
    Only list-likes may be considered boolean indexers.
    All other types are not considered a boolean indexer.
    For array-like input, boolean ndarrays or ExtensionArrays
    with ``_is_boolean`` set are considered boolean indexers.
Returns
-------
bool
    Whether `key` is a valid boolean indexer.
Raises
------
ValueError
    When the array is an object-dtype ndarray or ExtensionArray
    and contains missing values.
See Also
--------
check_array_indexer : Check that `key` is a valid array to index,
    and convert to an ndarray.
Definition at line 97 of file common.py.
is_builtin_func()
pandas.core.common.is_builtin_func (arg)
if we define a builtin function for this argument, return it,
otherwise return the arg
Definition at line 633 of file common.py.
is_empty_slice()
bool pandas.core.common.is_empty_slice (obj)
We have an empty slice, e.g. no values are selected.
Definition at line 323 of file common.py.
is_full_slice()
bool pandas.core.common.is_full_slice (obj, int line)
We have a full length slice.
Definition at line 343 of file common.py.
is_null_slice()
bool pandas.core.common.is_null_slice (obj)
We have a null slice.
Definition at line 311 of file common.py.
Referenced by is_true_slices().
is_true_slices()
list[bool] pandas.core.common.is_true_slices (line)
Find non-trivial slices in "line": return a list of booleans with same length.
Definition at line 335 of file common.py.
References is_null_slice().
maybe_iterable_to_list()
Collection[T] | T pandas.core.common.maybe_iterable_to_list (Iterable[T] | T obj)
If obj is Iterable but not list-like, consume into list.
Definition at line 301 of file common.py.
maybe_make_list()
pandas.core.common.maybe_make_list (obj)
Definition at line 295 of file common.py.
not_none()
pandas.core.common.not_none (* args)
Returns a generator consisting of the arguments that are not None.
Definition at line 174 of file common.py.
pipe()
T pandas.core.common.pipe (obj, Callable[..., T] | tuple[Callable[..., T], str] func, * args, ** kwargs)
Apply a function ``func`` to object ``obj`` either by passing obj as the
first argument to the function or, in the case that the func is a tuple,
interpret the first element of the tuple as a function and pass the obj to
that function as a keyword argument whose key is the value of the second
element of the tuple.
Parameters
----------
func : callable or tuple of (callable, str)
    Function to apply to this object or, alternatively, a
    ``(callable, data_keyword)`` tuple where ``data_keyword`` is a
    string indicating the keyword of ``callable`` that expects the
    object.
*args : iterable, optional
    Positional arguments passed into ``func``.
**kwargs : dict, optional
    A dictionary of keyword arguments passed into ``func``.
Returns
-------
object : the return type of ``func``.
Definition at line 468 of file common.py.
random_state() [1/3]
np.random.RandomState pandas.core.common.random_state (int | np.ndarray | np.random.BitGenerator | np.random.RandomState | None state)
Definition at line 427 of file common.py.
random_state() [2/3]
np.random.Generator pandas.core.common.random_state (np.random.Generator state)
Definition at line 422 of file common.py.
random_state() [3/3]
pandas.core.common.random_state (RandomState | None state = None)
Helper function for processing random_state arguments.
Parameters
----------
state : int, array-like, BitGenerator, Generator, np.random.RandomState, None.
    If receives an int, array-like, or BitGenerator, passes to
    np.random.RandomState() as seed.
    If receives an np.random RandomState or Generator, just returns that unchanged.
    If receives `None`, returns np.random.
    If receives anything else, raises an informative ValueError.
    Default None.
Returns
-------
np.random.RandomState or np.random.Generator. If state is None, returns np.random
Definition at line 433 of file common.py.
require_length_match()
None pandas.core.common.require_length_match (data, Index index)
Check the length of data matches the length of the index.
Definition at line 568 of file common.py.
standardize_mapping()
pandas.core.common.standardize_mapping (into)
Helper function to standardize a supplied mapping.
Parameters
----------
into : instance or subclass of collections.abc.Mapping
    Must be a class, an initialized collections.defaultdict,
    or an instance of a collections.abc.Mapping subclass.
Returns
-------
mapping : a collections.abc.Mapping subclass or other constructor
    a callable object that can accept an iterator to create
    the desired Mapping.
See Also
--------
DataFrame.to_dict
Series.to_dict
Definition at line 389 of file common.py.
temp_setattr()
Generator[None, None, None] pandas.core.common.temp_setattr (obj, str attr, value, bool condition = True)
Temporarily set attribute on an object.
Parameters
----------
obj : object
    Object whose attribute will be modified.
attr : str
    Attribute to modify.
value : Any
    Value to temporarily set attribute to.
condition : bool, default True
    Whether to set the attribute. Provided in order to not have to
    conditionally use this context manager.
Yields
------
object : obj with modified attribute.
Definition at line 536 of file common.py.
Variable Documentation
_builtin_table
dict pandas.core.common._builtin_table protected
Initial value:
=  {
    builtins.sum: np.sum,
    builtins.max: np.maximum.reduce,
    builtins.min: np.minimum.reduce,
}
Definition at line 584 of file common.py.
_builtin_table_alias
dict pandas.core.common._builtin_table_alias protected
Initial value:
=  {
    builtins.sum: "np.sum",
    builtins.max: "np.maximum.reduce",
    builtins.min: "np.minimum.reduce",
}
Definition at line 591 of file common.py.
_cython_table
dict pandas.core.common._cython_table protected
Initial value:
=  {
    builtins.sum: "sum",
    builtins.max: "max",
    builtins.min: "min",
    np.all: "all",
    np.any: "any",
    np.sum: "sum",
    np.nansum: "sum",
    np.mean: "mean",
    np.nanmean: "mean",
    np.prod: "prod",
    np.nanprod: "prod",
    np.std: "std",
    np.nanstd: "std",
    np.var: "var",
    np.nanvar: "var",
    np.median: "median",
    np.nanmedian: "median",
    np.max: "max",
    np.nanmax: "max",
    np.min: "min",
    np.nanmin: "min",
    np.cumprod: "cumprod",
    np.nancumprod: "cumprod",
    np.cumsum: "cumsum",
    np.nancumsum: "cumsum",
}
Definition at line 597 of file common.py.