Code Cloning Analysis: scipy.integrate._ivp.radau.Radau Class Reference
scipy.integrate._ivp.radau.Radau Class Reference
Public Member Functions
__init__ (self, fun, t0, y0, t_bound, max_step=np.inf, rtol=1e-3, atol=1e-6, jac=None, jac_sparsity=None, vectorized=False, first_step=None, **extraneous)
Public Member Functions inherited from scipy.integrate._ivp.base.OdeSolver
__init__ (self, fun, t0, y0, t_bound, vectorized, support_complex=False)
step_size (self)
step (self)
dense_output (self)
Public Attributes
y_old = None
max_step = validate_max_step(max_step)
rtol
atol = validate_tol(rtol, atol, self.n)
f = self.fun(self.t, self.y)
h_abs
h_abs_old = None
error_norm_old = None
newton_tol = max(10 * EPS / rtol, min(0.03, rtol ** 0.5))
sol = None
jac_factor = None
jac
J = self._validate_jac(jac, jac_sparsity)
lu = lu
solve_lu = solve_lu
I = I
bool current_jac = True
LU_real = None
LU_complex = None
Z = None
Public Attributes inherited from scipy.integrate._ivp.base.OdeSolver
t_old = None
t = t0
y = check_arguments(fun, y0, support_complex)
t_bound = t_bound
vectorized = vectorized
fun = fun
fun_single = fun_single
fun_vectorized = fun_vectorized
int direction = t0 else 1
int n = self.y.size
str status = 'running'
int nfev = 0
int njev = 0
int nlu = 0
Protected Member Functions
_validate_jac (self, jac, sparsity)
_step_impl (self)
_compute_dense_output (self)
_dense_output_impl (self)
Additional Inherited Members
Static Public Attributes inherited from scipy.integrate._ivp.base.OdeSolver
str TOO_SMALL_STEP = "Required step size is less than spacing between numbers."
Protected Attributes inherited from scipy.integrate._ivp.base.OdeSolver
_fun
Detailed Description
Implicit Runge-Kutta method of Radau IIA family of order 5.
The implementation follows [1]_. The error is controlled with a
third-order accurate embedded formula. A cubic polynomial which satisfies
the collocation conditions is used for the dense output.
Parameters
----------
fun : callable
    Right-hand side of the system: the time derivative of the state ``y``
    at time ``t``. The calling signature is ``fun(t, y)``, where ``t`` is a
    scalar and ``y`` is an ndarray with ``len(y) = len(y0)``. ``fun`` must
    return an array of the same shape as ``y``. See `vectorized` for more
    information.
t0 : float
    Initial time.
y0 : array_like, shape (n,)
    Initial state.
t_bound : float
    Boundary time - the integration won't continue beyond it. It also
    determines the direction of the integration.
first_step : float or None, optional
    Initial step size. Default is ``None`` which means that the algorithm
    should choose.
max_step : float, optional
    Maximum allowed step size. Default is np.inf, i.e., the step size is not
    bounded and determined solely by the solver.
rtol, atol : float and array_like, optional
    Relative and absolute tolerances. The solver keeps the local error
    estimates less than ``atol + rtol * abs(y)``. HHere `rtol` controls a
    relative accuracy (number of correct digits), while `atol` controls
    absolute accuracy (number of correct decimal places). To achieve the
    desired `rtol`, set `atol` to be smaller than the smallest value that
    can be expected from ``rtol * abs(y)`` so that `rtol` dominates the
    allowable error. If `atol` is larger than ``rtol * abs(y)`` the
    number of correct digits is not guaranteed. Conversely, to achieve the
    desired `atol` set `rtol` such that ``rtol * abs(y)`` is always smaller
    than `atol`. If components of y have different scales, it might be
    beneficial to set different `atol` values for different components by
    passing array_like with shape (n,) for `atol`. Default values are
    1e-3 for `rtol` and 1e-6 for `atol`.
jac : {None, array_like, sparse_matrix, callable}, optional
    Jacobian matrix of the right-hand side of the system with respect to
    y, required by this method. The Jacobian matrix has shape (n, n) and
    its element (i, j) is equal to ``d f_i / d y_j``.
    There are three ways to define the Jacobian:
        * If array_like or sparse_matrix, the Jacobian is assumed to
          be constant.
        * If callable, the Jacobian is assumed to depend on both
          t and y; it will be called as ``jac(t, y)`` as necessary.
          For the 'Radau' and 'BDF' methods, the return value might be a
          sparse matrix.
        * If None (default), the Jacobian will be approximated by
          finite differences.
    It is generally recommended to provide the Jacobian rather than
    relying on a finite-difference approximation.
jac_sparsity : {None, array_like, sparse matrix}, optional
    Defines a sparsity structure of the Jacobian matrix for a
    finite-difference approximation. Its shape must be (n, n). This argument
    is ignored if `jac` is not `None`. If the Jacobian has only few non-zero
    elements in *each* row, providing the sparsity structure will greatly
    speed up the computations [2]_. A zero entry means that a corresponding
    element in the Jacobian is always zero. If None (default), the Jacobian
    is assumed to be dense.
vectorized : bool, optional
    Whether `fun` can be called in a vectorized fashion. Default is False.
    If ``vectorized`` is False, `fun` will always be called with ``y`` of
    shape ``(n,)``, where ``n = len(y0)``.
    If ``vectorized`` is True, `fun` may be called with ``y`` of shape
    ``(n, k)``, where ``k`` is an integer. In this case, `fun` must behave
    such that ``fun(t, y)[:, i] == fun(t, y[:, i])`` (i.e. each column of
    the returned array is the time derivative of the state corresponding
    with a column of ``y``).
    Setting ``vectorized=True`` allows for faster finite difference
    approximation of the Jacobian by this method, but may result in slower
    execution overall in some circumstances (e.g. small ``len(y0)``).
Attributes
----------
n : int
    Number of equations.
status : string
    Current status of the solver: 'running', 'finished' or 'failed'.
t_bound : float
    Boundary time.
direction : float
    Integration direction: +1 or -1.
t : float
    Current time.
y : ndarray
    Current state.
t_old : float
    Previous time. None if no steps were made yet.
step_size : float
    Size of the last successful step. None if no steps were made yet.
nfev : int
    Number of evaluations of the right-hand side.
njev : int
    Number of evaluations of the Jacobian.
nlu : int
    Number of LU decompositions.
References
----------
.. [1] E. Hairer, G. Wanner, "Solving Ordinary Differential Equations II:
       Stiff and Differential-Algebraic Problems", Sec. IV.8.
.. [2] A. Curtis, M. J. D. Powell, and J. Reid, "On the estimation of
       sparse Jacobian matrices", Journal of the Institute of Mathematics
       and its Applications, 13, pp. 117-120, 1974.
Definition at line 179 of file radau.py.
Constructor & Destructor Documentation
__init__()
scipy.integrate._ivp.radau.Radau.__init__ (self, fun, t0, y0, t_bound, max_step = np.inf, rtol = 1e-3, atol = 1e-6, jac = None, jac_sparsity = None, vectorized = False, first_step = None, ** extraneous)
Definition at line 295 of file radau.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
_compute_dense_output()
scipy.integrate._ivp.radau.Radau._compute_dense_output (self) protected
Definition at line 543 of file radau.py.
_dense_output_impl()
scipy.integrate._ivp.radau.Radau._dense_output_impl (self) protected
Reimplemented from scipy.integrate._ivp.base.OdeSolver.
Definition at line 547 of file radau.py.
_step_impl()
scipy.integrate._ivp.radau.Radau._step_impl (self) protected
Reimplemented from scipy.integrate._ivp.base.OdeSolver.
Definition at line 401 of file radau.py.
_validate_jac()
scipy.integrate._ivp.radau.Radau._validate_jac (self, jac, sparsity) protected
Definition at line 348 of file radau.py.
Member Data Documentation
atol
scipy.integrate._ivp.radau.Radau.atol = validate_tol(rtol, atol, self.n)
Definition at line 302 of file radau.py.
Referenced by scipy.optimize._differentialevolution.DifferentialEvolutionSolver.converged(), scipy.integrate._ode.dop853.reset(), scipy.integrate._ode.dopri5.reset(), scipy.integrate._ode.lsoda.reset(), scipy.integrate._ode.vode.reset(), scipy.integrate._ode.zvode.reset(), and sklearn.neighbors._kde.KernelDensity.score_samples().
current_jac
bool scipy.integrate._ivp.radau.Radau.current_jac = True
Definition at line 343 of file radau.py.
error_norm_old
scipy.integrate._ivp.radau.Radau.error_norm_old = None
Definition at line 313 of file radau.py.
f
scipy.integrate._ivp.radau.Radau.f = self.fun(self.t, self.y)
Definition at line 303 of file radau.py.
Referenced by scipy.optimize._zeros_py.TOMS748Solver._callf(), scipy.integrate._ode.ode.integrate(), scipy.optimize._shgo_lib._vertex.VertexScalarField.maximiser(), scipy.optimize._shgo_lib._vertex.VertexScalarField.minimiser(), and scipy.optimize._zeros_py.TOMS748Solver.start().
h_abs
scipy.integrate._ivp.radau.Radau.h_abs
Initial value:
=  select_initial_step(
                self.fun, self.t, self.y, self.f, self.direction,
                3, self.rtol, self.atol)
Definition at line 307 of file radau.py.
h_abs_old
scipy.integrate._ivp.radau.Radau.h_abs_old = None
Definition at line 312 of file radau.py.
I
scipy.integrate._ivp.radau.Radau.I = I
Definition at line 341 of file radau.py.
J
scipy.integrate._ivp.radau.Radau.J = self._validate_jac(jac, jac_sparsity)
Definition at line 319 of file radau.py.
jac
scipy.integrate._ivp.radau.Radau.jac
Definition at line 319 of file radau.py.
Referenced by scipy.optimize._optimize.MemoizeJac.__call__(), scipy.optimize._trustregion_dogleg.DoglegSubproblem.cauchy_point(), scipy.optimize.tests.test_slsqp.TestSLSQP.fprime_ieqcon2(), scipy.optimize._trustregion_constr.tr_interior_point.BarrierSubproblem.gradient_and_jacobian(), scipy.integrate._ode.ode.integrate(), scipy.optimize.tests.test_slsqp.TestSLSQP.jac(), scipy.optimize._trustregion.BaseQuadraticSubproblem.jac_mag(), scipy.optimize._trustregion_dogleg.DoglegSubproblem.newton_point(), scipy.integrate._ode.ode.set_initial_value(), scipy.integrate._ode.ode.set_integrator(), scipy.integrate._ode.ode.set_solout(), scipy.optimize._trustregion_exact.IterativeSubproblem.solve(), and scipy.optimize._trustregion_ncg.CGSteihaugSubproblem.solve().
jac_factor
scipy.integrate._ivp.radau.Radau.jac_factor = None
Definition at line 318 of file radau.py.
lu
scipy.integrate._ivp.radau.Radau.lu = lu
Definition at line 339 of file radau.py.
LU_complex
scipy.integrate._ivp.radau.Radau.LU_complex = None
Definition at line 345 of file radau.py.
LU_real
scipy.integrate._ivp.radau.Radau.LU_real = None
Definition at line 344 of file radau.py.
max_step
scipy.integrate._ivp.radau.Radau.max_step = validate_max_step(max_step)
Definition at line 301 of file radau.py.
Referenced by scipy.integrate._ode.dop853.reset(), scipy.integrate._ode.dopri5.reset(), scipy.integrate._ode.lsoda.reset(), scipy.integrate._ode.vode.reset(), and scipy.integrate._ode.zvode.reset().
newton_tol
scipy.integrate._ivp.radau.Radau.newton_tol = max(10 * EPS / rtol, min(0.03, rtol ** 0.5))
Definition at line 315 of file radau.py.
rtol
scipy.integrate._ivp.radau.Radau.rtol
Definition at line 302 of file radau.py.
Referenced by scipy.optimize._zeros_py.TOMS748Solver.get_status(), scipy.optimize._zeros_py.TOMS748Solver.iterate(), scipy.integrate._ode.dop853.reset(), scipy.integrate._ode.dopri5.reset(), scipy.integrate._ode.lsoda.reset(), scipy.integrate._ode.vode.reset(), scipy.integrate._ode.zvode.reset(), scipy.optimize.tests.test_zeros.TestScalarRootFinders.run_tests(), sklearn.neighbors._kde.KernelDensity.score_samples(), scipy.stats.tests.test_resampling.TestPermutationTest.test_against_spearmanr_in_R(), and scipy.stats.tests.test_resampling.TestPermutationTest.test_with_ties().
sol
scipy.integrate._ivp.radau.Radau.sol = None
Definition at line 316 of file radau.py.
Referenced by scipy.optimize.tests.test__basinhopping.TestBasinHopping.setup_method().
solve_lu
scipy.integrate._ivp.radau.Radau.solve_lu = solve_lu
Definition at line 340 of file radau.py.
y_old
scipy.integrate._ivp.radau.Radau.y_old = None
Definition at line 300 of file radau.py.
Z
scipy.integrate._ivp.radau.Radau.Z = None
Definition at line 346 of file radau.py.
Referenced by scipy.optimize._shgo.SHGO.g_topograph(), and scipy.optimize._shgo.SHGO.minimise_pool().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/integrate/_ivp/radau.py