Code Cloning Analysis: fontTools.ttLib.tables.otConverters.ExtSubTable Class Reference
fontTools.ttLib.tables.otConverters.ExtSubTable Class Reference
Public Member Functions
write (self, writer, font, tableDict, value, repeatIndex=None)
Public Member Functions inherited from fontTools.ttLib.tables.otConverters.LTable
readOffset (self, reader)
writeNullOffset (self, writer)
Public Member Functions inherited from fontTools.ttLib.tables.otConverters.Table
read (self, reader, font, tableDict)
Public Member Functions inherited from fontTools.ttLib.tables.otConverters.Struct
getRecordSize (self, reader)
xmlRead (self, attrs, content, font)
__repr__ (self)
Public Member Functions inherited from fontTools.ttLib.tables.otConverters.BaseConverter
__init__ (self, name, repeat, aux, tableClass=None, *, description="")
readArray (self, reader, font, tableDict, count)
writeArray (self, writer, font, tableDict, values)
Optional[int] getVarIndexOffset (self)
Public Member Functions inherited from fontTools.ttLib.tables.otConverters.SubTable
getConverter (self, tableType, lookupType)
xmlWrite (self, xmlWriter, font, value, name, attrs)
Additional Inherited Members
Public Attributes inherited from fontTools.ttLib.tables.otConverters.BaseConverter
name = name
repeat = repeat
aux = aux
tableClass = tableClass
isCount
str isLookupType = "MorphType"
isPropagated
description = description
Static Public Attributes inherited from fontTools.ttLib.tables.otConverters.Table
int staticSize = 2
Static Public Attributes inherited from fontTools.ttLib.tables.otConverters.BaseConverter
varIndexBasePlusOffsetRE = re.compile(r"VarIndexBase\s*\+\s*(\d+)")
Detailed Description
Definition at line 771 of file otConverters.py.
Member Function Documentation
write()
fontTools.ttLib.tables.otConverters.ExtSubTable.write (self, writer, font, tableDict, value, repeatIndex = None)
Write a value to the writer.
Reimplemented from fontTools.ttLib.tables.otConverters.Table.
Definition at line 772 of file otConverters.py.
Referenced by matplotlib.backends.backend_pdf.PdfFile.addGouraudTriangles(), matplotlib.backends.backend_pdf.PdfFile.close(), joblib.externals.cloudpickle.cloudpickle.Pickler.reducer_override(), scipy.io.matlab._mio5.VarWriter5.write_sparse(), pandas.io.formats.html.HTMLFormatter.write_th(), scipy.io.matlab._mio5.VarWriter5.write_top(), matplotlib.backends.backend_pdf.PdfFile.writeTrailer(), and matplotlib.backends.backend_pdf.PdfFile.writeXref().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ttLib/tables/otConverters.py