Code Cloning Analysis: scipy.interpolate.tests.test_bsplines.TestSmoothingSpline Class Reference
scipy.interpolate.tests.test_bsplines.TestSmoothingSpline Class Reference
Public Member Functions
test_invalid_input (self)
test_compare_with_GCVSPL (self)
test_non_regularized_case (self)
test_weighted_smoothing_spline (self)
Detailed Description
Definition at line 1535 of file test_bsplines.py.
Member Function Documentation
test_compare_with_GCVSPL()
scipy.interpolate.tests.test_bsplines.TestSmoothingSpline.test_compare_with_GCVSPL (self)
Data is generated in the following way:
>>> np.random.seed(1234)
>>> n = 100
>>> x = np.sort(np.random.random_sample(n) * 4 - 2)
>>> y = np.sin(x) + np.random.normal(scale=.5, size=n)
>>> np.savetxt('x.csv', x)
>>> np.savetxt('y.csv', y)
We obtain the result of performing the GCV smoothing splines
package (by Woltring, gcvspl) on the sample data points
using its version for Octave (https://github.com/srkuberski/gcvspl).
In order to use this implementation, one should clone the repository
and open the folder in Octave.
In Octave, we load up ``x`` and ``y`` (generated from Python code
above):
>>> x = csvread('x.csv');
>>> y = csvread('y.csv');
Then, in order to access the implementation, we compile gcvspl files in
Octave:
>>> mex gcvsplmex.c gcvspl.c
>>> mex spldermex.c gcvspl.c
The first function computes the vector of unknowns from the dataset
(x, y) while the second one evaluates the spline in certain points
with known vector of coefficients.
>>> c = gcvsplmex(x, y, 2);
>>> y0 = spldermex(x, c, 2, x, 0);
If we want to compare the results of the gcvspl code, we can save
``y0`` in csv file:
>>> csvwrite('y0.csv', y0);
Definition at line 1570 of file test_bsplines.py.
References scipy.interpolate._bsplines.make_smoothing_spline().
test_invalid_input()
scipy.interpolate.tests.test_bsplines.TestSmoothingSpline.test_invalid_input (self)
Definition at line 1539 of file test_bsplines.py.
test_non_regularized_case()
scipy.interpolate.tests.test_bsplines.TestSmoothingSpline.test_non_regularized_case (self)
In case the regularization parameter is 0, the resulting spline
is an interpolation spline with natural boundary conditions.
Definition at line 1624 of file test_bsplines.py.
References scipy.interpolate._bsplines.make_interp_spline(), and scipy.interpolate._bsplines.make_smoothing_spline().
test_weighted_smoothing_spline()
scipy.interpolate.tests.test_bsplines.TestSmoothingSpline.test_weighted_smoothing_spline (self)
Definition at line 1643 of file test_bsplines.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/interpolate/tests/test_bsplines.py