Code Cloning Analysis: numpy._typing._nested_sequence._NestedSequence Class Reference
numpy._typing._nested_sequence._NestedSequence Class Reference
Public Member Functions
int __len__ (self)
_T_co|_NestedSequence[_T_co] __getitem__ (self, int index)
bool __contains__ (self, object x)
Iterator[_T_co|_NestedSequence[_T_co]] __iter__ (self)
Iterator[_T_co|_NestedSequence[_T_co]] __reversed__ (self)
int count (self, Any value)
int index (self, Any value)
Detailed Description
A protocol for representing nested sequences.
Warning
-------
`_NestedSequence` currently does not work in combination with typevars,
*e.g.* ``def func(a: _NestedSequnce[T]) -> T: ...``.
See Also
--------
collections.abc.Sequence
    ABCs for read-only and mutable :term:`sequences`.
Examples
--------
.. code-block:: python
    >>> from __future__ import annotations
    >>> from typing import TYPE_CHECKING
    >>> import numpy as np
    >>> from numpy._typing import _NestedSequence
    >>> def get_dtype(seq: _NestedSequence[float]) -> np.dtype[np.float64]:
    ...     return np.asarray(seq).dtype
    >>> a = get_dtype([1.0])
    >>> b = get_dtype([[1.0]])
    >>> c = get_dtype([[[1.0]]])
    >>> d = get_dtype([[[[1.0]]]])
    >>> if TYPE_CHECKING:
    ...     reveal_locals()
    ...     # note: Revealed local types are:
    ...     # note:     a: numpy.dtype[numpy.floating[numpy._typing._64Bit]]
    ...     # note:     b: numpy.dtype[numpy.floating[numpy._typing._64Bit]]
    ...     # note:     c: numpy.dtype[numpy.floating[numpy._typing._64Bit]]
    ...     # note:     d: numpy.dtype[numpy.floating[numpy._typing._64Bit]]
Definition at line 19 of file _nested_sequence.py.
Member Function Documentation
__contains__()
bool numpy._typing._nested_sequence._NestedSequence.__contains__ (self, object x)
Implement ``x in self``.
Definition at line 68 of file _nested_sequence.py.
__getitem__()
_T_co | _NestedSequence[_T_co] numpy._typing._nested_sequence._NestedSequence.__getitem__ (self, int index)
Implement ``self[x]``.
Definition at line 64 of file _nested_sequence.py.
__iter__()
Iterator[_T_co | _NestedSequence[_T_co]] numpy._typing._nested_sequence._NestedSequence.__iter__ (self)
Implement ``iter(self)``.
Definition at line 72 of file _nested_sequence.py.
__len__()
int numpy._typing._nested_sequence._NestedSequence.__len__ (self)
Implement ``len(self)``.
Definition at line 60 of file _nested_sequence.py.
__reversed__()
Iterator[_T_co | _NestedSequence[_T_co]] numpy._typing._nested_sequence._NestedSequence.__reversed__ (self)
Implement ``reversed(self)``.
Definition at line 76 of file _nested_sequence.py.
count()
int numpy._typing._nested_sequence._NestedSequence.count (self, Any value)
Return the number of occurrences of `value`.
Definition at line 80 of file _nested_sequence.py.
Referenced by pandas.core.window.rolling.Rolling._validate_datetimelike_monotonic(), numpy.ma.core.MaskedArray.mean(), PIL.ImageStat.Stat.mean(), PIL.ImageStat.Stat.median(), PIL.ImageStat.Stat.rms(), numpy.ma.core.MaskedArray.var(), and PIL.ImageStat.Stat.var().
index()
int numpy._typing._nested_sequence._NestedSequence.index (self, Any value)
Return the first index of `value`.
Definition at line 84 of file _nested_sequence.py.
Referenced by pandas.core.apply.FrameApply.apply(), pandas.core.apply.FrameApply.apply_raw(), and pandas.core.internals.array_manager.SingleArrayManager.array_values().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/_typing/_nested_sequence.py