Code Cloning Analysis: pandas.core.arrays.timedeltas Namespace Reference
pandas.core.arrays.timedeltas Namespace Reference
Classes
class TimedeltaArray
Functions
_field_accessor (str name, str alias, str docstring)
tuple[np.ndarray, Tick|None] sequence_to_td64ns (data, bool copy=False, unit=None, DateTimeErrorChoices errors="raise")
_ints_to_td64ns (data, str unit="ns")
_objects_to_td64ns (data, unit=None, DateTimeErrorChoices errors="raise")
DtypeObj _validate_td64_dtype (dtype)
Variables
_hasna
Function Documentation
_field_accessor()
pandas.core.arrays.timedeltas._field_accessor (str name, str alias, str docstring) protected
Definition at line 81 of file timedeltas.py.
_ints_to_td64ns()
pandas.core.arrays.timedeltas._ints_to_td64ns (data, str unit = "ns") protected
Convert an ndarray with integer-dtype to timedelta64[ns] dtype, treating
the integers as multiples of the given timedelta unit.
Parameters
----------
data : numpy.ndarray with integer-dtype
unit : str, default "ns"
    The timedelta unit to treat integers as multiples of.
Returns
-------
numpy.ndarray : timedelta64[ns] array converted from data
bool : whether a copy was made
Definition at line 1094 of file timedeltas.py.
Referenced by sequence_to_td64ns().
_objects_to_td64ns()
pandas.core.arrays.timedeltas._objects_to_td64ns (data, unit = None, DateTimeErrorChoices errors = "raise") protected
Convert a object-dtyped or string-dtyped array into an
timedelta64[ns]-dtyped array.
Parameters
----------
data : ndarray or Index
unit : str, default "ns"
    The timedelta unit to treat integers as multiples of.
    Must not be specified if the data contains a str.
errors : {"raise", "coerce", "ignore"}, default "raise"
    How to handle elements that cannot be converted to timedelta64[ns].
    See ``pandas.to_timedelta`` for details.
Returns
-------
numpy.ndarray : timedelta64[ns] array converted from data
Raises
------
ValueError : Data cannot be converted to timedelta64[ns].
Notes
-----
Unlike `pandas.to_timedelta`, if setting `errors=ignore` will not cause
errors to be ignored; they are caught and subsequently ignored at a
higher level.
Definition at line 1134 of file timedeltas.py.
Referenced by sequence_to_td64ns().
_validate_td64_dtype()
DtypeObj pandas.core.arrays.timedeltas._validate_td64_dtype (dtype) protected
Definition at line 1170 of file timedeltas.py.
sequence_to_td64ns()
tuple[np.ndarray, Tick | None] pandas.core.arrays.timedeltas.sequence_to_td64ns (data, bool copy = False, unit = None, DateTimeErrorChoices errors = "raise")
Parameters
----------
data : list-like
copy : bool, default False
unit : str, optional
    The timedelta unit to treat integers as multiples of. For numeric
    data this defaults to ``'ns'``.
    Must be un-specified if the data contains a str and ``errors=="raise"``.
errors : {"raise", "coerce", "ignore"}, default "raise"
    How to handle elements that cannot be converted to timedelta64[ns].
    See ``pandas.to_timedelta`` for details.
Returns
-------
converted : numpy.ndarray
    The sequence converted to a numpy array with dtype ``timedelta64[ns]``.
inferred_freq : Tick or None
    The inferred frequency of the sequence.
Raises
------
ValueError : Data cannot be converted to timedelta64[ns].
Notes
-----
Unlike `pandas.to_timedelta`, if setting ``errors=ignore`` will not cause
errors to be ignored; they are caught and subsequently ignored at a
higher level.
Definition at line 998 of file timedeltas.py.
References _ints_to_td64ns(), and _objects_to_td64ns().
Referenced by pandas.core.arrays.timedeltas.TimedeltaArray._from_sequence_not_strict(), and pandas.core.arrays.timedeltas.TimedeltaArray.dtype().
Variable Documentation
_hasna
pandas.core.arrays.timedeltas._hasna protected
Definition at line 91 of file timedeltas.py.