Code Cloning Analysis: sklearn.utils.tests.test_pprint.LogisticRegression Class Reference
sklearn.utils.tests.test_pprint.LogisticRegression Class Reference
Public Member Functions
__init__ (self, penalty="l2", dual=False, tol=1e-4, C=1.0, fit_intercept=True, intercept_scaling=1, class_weight=None, random_state=None, solver="warn", max_iter=100, multi_class="warn", verbose=0, warm_start=False, n_jobs=None, l1_ratio=None)
fit (self, X, y)
Public Member Functions inherited from sklearn.base.BaseEstimator
get_params (self, deep=True)
set_params (self, **params)
__sklearn_clone__ (self)
__repr__ (self, N_CHAR_MAX=700)
__getstate__ (self)
__setstate__ (self, state)
__sklearn_tags__ (self)
Public Member Functions inherited from sklearn.utils._metadata_requests._MetadataRequester
set_fit_request (self, **kwargs)
set_partial_fit_request (self, **kwargs)
set_predict_request (self, **kwargs)
set_predict_proba_request (self, **kwargs)
set_predict_log_proba_request (self, **kwargs)
set_decision_function_request (self, **kwargs)
set_score_request (self, **kwargs)
set_split_request (self, **kwargs)
set_transform_request (self, **kwargs)
set_inverse_transform_request (self, **kwargs)
__init_subclass__ (cls, **kwargs)
get_metadata_routing (self)
Public Attributes
penalty = penalty
dual = dual
tol = tol
C = C
fit_intercept = fit_intercept
intercept_scaling = intercept_scaling
class_weight = class_weight
random_state = random_state
solver = solver
max_iter = max_iter
multi_class = multi_class
verbose = verbose
warm_start = warm_start
n_jobs = n_jobs
l1_ratio = l1_ratio
Additional Inherited Members
Protected Member Functions inherited from sklearn.base.BaseEstimator
_get_param_names (cls)
_get_params_html (self, deep=True)
_validate_params (self)
Protected Member Functions inherited from sklearn.utils._repr_html.base.ReprHTMLMixin
_repr_html_ (self)
_repr_html_inner (self)
_repr_mimebundle_ (self, **kwargs)
Protected Member Functions inherited from sklearn.utils._repr_html.base._HTMLDocumentationLinkMixin
_doc_link_template (self)
_doc_link_template (self, value)
_get_doc_link (self)
Protected Member Functions inherited from sklearn.utils._metadata_requests._MetadataRequester
_build_request_for_signature (cls, router, method)
_get_default_requests (cls)
_get_metadata_request (self)
Protected Attributes inherited from sklearn.base.BaseEstimator
_parameter_constraints
Static Protected Attributes inherited from sklearn.base.BaseEstimator
_html_repr = estimator_html_repr
Static Protected Attributes inherited from sklearn.utils._repr_html.base._HTMLDocumentationLinkMixin
str _doc_link_module = "sklearn"
_doc_link_url_param_generator = None
Detailed Description
Definition at line 16 of file test_pprint.py.
Constructor & Destructor Documentation
__init__()
sklearn.utils.tests.test_pprint.LogisticRegression.__init__ (self, penalty = "l2", dual = False, tol = 1e-4, C = 1.0, fit_intercept = True, intercept_scaling = 1, class_weight = None, random_state = None, solver = "warn", max_iter = 100, multi_class = "warn", verbose = 0, warm_start = False, n_jobs = None, l1_ratio = None)
Definition at line 17 of file test_pprint.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params().
Member Function Documentation
fit()
sklearn.utils.tests.test_pprint.LogisticRegression.fit (self, X, y)
Definition at line 51 of file test_pprint.py.
Referenced by sklearn.cluster._kmeans._BaseKMeans.fit_predict(), and sklearn.cluster._kmeans._BaseKMeans.fit_transform().
Member Data Documentation
C
sklearn.utils.tests.test_pprint.LogisticRegression.C = C
Definition at line 38 of file test_pprint.py.
class_weight
sklearn.utils.tests.test_pprint.LogisticRegression.class_weight = class_weight
Definition at line 41 of file test_pprint.py.
dual
sklearn.utils.tests.test_pprint.LogisticRegression.dual = dual
Definition at line 36 of file test_pprint.py.
fit_intercept
sklearn.utils.tests.test_pprint.LogisticRegression.fit_intercept = fit_intercept
Definition at line 39 of file test_pprint.py.
intercept_scaling
sklearn.utils.tests.test_pprint.LogisticRegression.intercept_scaling = intercept_scaling
Definition at line 40 of file test_pprint.py.
l1_ratio
sklearn.utils.tests.test_pprint.LogisticRegression.l1_ratio = l1_ratio
Definition at line 49 of file test_pprint.py.
max_iter
sklearn.utils.tests.test_pprint.LogisticRegression.max_iter = max_iter
Definition at line 44 of file test_pprint.py.
Referenced by sklearn.linear_model._least_angle.Lars.fit().
multi_class
sklearn.utils.tests.test_pprint.LogisticRegression.multi_class = multi_class
Definition at line 45 of file test_pprint.py.
n_jobs
sklearn.utils.tests.test_pprint.LogisticRegression.n_jobs = n_jobs
Definition at line 48 of file test_pprint.py.
Referenced by sklearn.ensemble._voting._BaseVoting.fit(), sklearn.neighbors._base.KNeighborsMixin.kneighbors(), and sklearn.neighbors._base.RadiusNeighborsMixin.radius_neighbors().
penalty
sklearn.utils.tests.test_pprint.LogisticRegression.penalty = penalty
Definition at line 35 of file test_pprint.py.
random_state
sklearn.utils.tests.test_pprint.LogisticRegression.random_state = random_state
Definition at line 42 of file test_pprint.py.
solver
sklearn.utils.tests.test_pprint.LogisticRegression.solver = solver
Definition at line 43 of file test_pprint.py.
tol
sklearn.utils.tests.test_pprint.LogisticRegression.tol = tol
Definition at line 37 of file test_pprint.py.
verbose
sklearn.utils.tests.test_pprint.LogisticRegression.verbose = verbose
Definition at line 46 of file test_pprint.py.
Referenced by joblib._store_backends.StoreBackendMixin.enforce_store_limits().
warm_start
sklearn.utils.tests.test_pprint.LogisticRegression.warm_start = warm_start
Definition at line 47 of file test_pprint.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/sklearn/utils/tests/test_pprint.py