Code Cloning Analysis: joblib.externals.loky.process_executor._ExecutorManagerThread Class Reference
joblib.externals.loky.process_executor._ExecutorManagerThread Class Reference
Public Member Functions
__init__ (self, executor)
run (self)
add_call_item_to_queue (self)
wait_result_broken_or_wakeup (self)
process_result_item (self, result_item)
is_shutting_down (self)
terminate_broken (self, bpe)
flag_executor_shutting_down (self)
kill_workers (self, reason="")
shutdown_workers (self)
join_executor_internals (self)
get_n_children_alive (self)
Public Attributes
thread_wakeup = executor._executor_manager_thread_wakeup
shutdown_lock = executor._shutdown_lock
executor_reference = weakref.ref(executor, weakref_cb)
executor_flags = executor._flags
processes = executor._processes
call_queue = executor._call_queue
result_queue = executor._result_queue
work_ids_queue = executor._work_ids
pending_work_items = executor._pending_work_items
running_work_items = executor._running_work_items
processes_management_lock = executor._processes_management_lock
bool daemon = True
Detailed Description
Manages the communication between this process and the worker processes.
The manager is run in a local thread.
Args:
    executor: A reference to the ProcessPoolExecutor that owns
        this thread. A weakref will be own by the manager as well as
        references to internal objects used to introspect the state of
        the executor.
Definition at line 541 of file process_executor.py.
Constructor & Destructor Documentation
__init__()
joblib.externals.loky.process_executor._ExecutorManagerThread.__init__ (self, executor)
Definition at line 553 of file process_executor.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
add_call_item_to_queue()
joblib.externals.loky.process_executor._ExecutorManagerThread.add_call_item_to_queue (self)
Definition at line 643 of file process_executor.py.
flag_executor_shutting_down()
joblib.externals.loky.process_executor._ExecutorManagerThread.flag_executor_shutting_down (self)
Definition at line 838 of file process_executor.py.
get_n_children_alive()
joblib.externals.loky.process_executor._ExecutorManagerThread.get_n_children_alive (self)
Definition at line 956 of file process_executor.py.
is_shutting_down()
joblib.externals.loky.process_executor._ExecutorManagerThread.is_shutting_down (self)
Definition at line 802 of file process_executor.py.
join_executor_internals()
joblib.externals.loky.process_executor._ExecutorManagerThread.join_executor_internals (self)
Definition at line 917 of file process_executor.py.
kill_workers()
joblib.externals.loky.process_executor._ExecutorManagerThread.kill_workers (self, reason = "")
Definition at line 858 of file process_executor.py.
process_result_item()
joblib.externals.loky.process_executor._ExecutorManagerThread.process_result_item (self, result_item)
Definition at line 750 of file process_executor.py.
run()
joblib.externals.loky.process_executor._ExecutorManagerThread.run (self)
Definition at line 617 of file process_executor.py.
Referenced by scipy.odr._odrpack.ODR.restart(), scipy.integrate._ode.lsoda.run_relax(), scipy.integrate._ode.vode.run_relax(), scipy.integrate._ode.lsoda.step(), and scipy.integrate._ode.vode.step().
shutdown_workers()
joblib.externals.loky.process_executor._ExecutorManagerThread.shutdown_workers (self)
Definition at line 870 of file process_executor.py.
terminate_broken()
joblib.externals.loky.process_executor._ExecutorManagerThread.terminate_broken (self, bpe)
Definition at line 816 of file process_executor.py.
wait_result_broken_or_wakeup()
joblib.externals.loky.process_executor._ExecutorManagerThread.wait_result_broken_or_wakeup (self)
Definition at line 671 of file process_executor.py.
Member Data Documentation
call_queue
joblib.externals.loky.process_executor._ExecutorManagerThread.call_queue = executor._call_queue
Definition at line 594 of file process_executor.py.
daemon
bool joblib.externals.loky.process_executor._ExecutorManagerThread.daemon = True
Definition at line 615 of file process_executor.py.
executor_flags
joblib.externals.loky.process_executor._ExecutorManagerThread.executor_flags = executor._flags
Definition at line 587 of file process_executor.py.
executor_reference
joblib.externals.loky.process_executor._ExecutorManagerThread.executor_reference = weakref.ref(executor, weakref_cb)
Definition at line 584 of file process_executor.py.
pending_work_items
joblib.externals.loky.process_executor._ExecutorManagerThread.pending_work_items = executor._pending_work_items
Definition at line 604 of file process_executor.py.
processes
joblib.externals.loky.process_executor._ExecutorManagerThread.processes = executor._processes
Definition at line 590 of file process_executor.py.
processes_management_lock
joblib.externals.loky.process_executor._ExecutorManagerThread.processes_management_lock = executor._processes_management_lock
Definition at line 611 of file process_executor.py.
result_queue
joblib.externals.loky.process_executor._ExecutorManagerThread.result_queue = executor._result_queue
Definition at line 597 of file process_executor.py.
running_work_items
joblib.externals.loky.process_executor._ExecutorManagerThread.running_work_items = executor._running_work_items
Definition at line 607 of file process_executor.py.
shutdown_lock
joblib.externals.loky.process_executor._ExecutorManagerThread.shutdown_lock = executor._shutdown_lock
Definition at line 560 of file process_executor.py.
thread_wakeup
joblib.externals.loky.process_executor._ExecutorManagerThread.thread_wakeup = executor._executor_manager_thread_wakeup
Definition at line 559 of file process_executor.py.
work_ids_queue
joblib.externals.loky.process_executor._ExecutorManagerThread.work_ids_queue = executor._work_ids
Definition at line 600 of file process_executor.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py