Code Cloning Analysis: scipy.optimize._nonlin.LinearMixing Class Reference
scipy.optimize._nonlin.LinearMixing Class Reference
Public Member Functions
__init__ (self, alpha=None)
solve (self, f, tol=0)
matvec (self, f)
rsolve (self, f, tol=0)
rmatvec (self, f)
todense (self)
Public Member Functions inherited from scipy.optimize._nonlin.GenericBroyden
setup (self, x0, f0, func)
update (self, x, f)
Public Member Functions inherited from scipy.optimize._nonlin.Jacobian
__init__ (self, **kw)
aspreconditioner (self)
Protected Member Functions
_update (self, x, f, dx, df, dx_norm, df_norm)
Additional Inherited Members
Public Attributes inherited from scipy.optimize._nonlin.GenericBroyden
last_f = f0
last_x = x0
float alpha = 0.5*max(norm(x0), 1) / normf0
Public Attributes inherited from scipy.optimize._nonlin.Jacobian
func = func
tuple shape = (F.size, x.size)
dtype = F.dtype
Detailed Description
Find a root of a function, using a scalar Jacobian approximation.
.. warning::
   This algorithm may be useful for specific problems, but whether
   it will work may depend strongly on the problem.
Parameters
----------
%(params_basic)s
alpha : float, optional
    The Jacobian approximation is (-1/alpha).
%(params_extra)s
See Also
--------
root : Interface to root finding algorithms for multivariate
       functions. See ``method='linearmixing'`` in particular.
Definition at line 1206 of file _nonlin.py.
Constructor & Destructor Documentation
__init__()
scipy.optimize._nonlin.LinearMixing.__init__ (self, alpha = None)
Definition at line 1229 of file _nonlin.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
_update()
scipy.optimize._nonlin.LinearMixing._update (self, x, f, dx, df, dx_norm, df_norm) protected
Reimplemented from scipy.optimize._nonlin.GenericBroyden.
Definition at line 1248 of file _nonlin.py.
matvec()
scipy.optimize._nonlin.LinearMixing.matvec (self, f)
Definition at line 1236 of file _nonlin.py.
Referenced by scipy.sparse.linalg._interface.LinearOperator._init_dtype(), scipy.sparse.linalg._interface.LinearOperator._matmat(), and scipy.sparse.linalg._interface.LinearOperator.dot().
rmatvec()
scipy.optimize._nonlin.LinearMixing.rmatvec (self, f)
Definition at line 1242 of file _nonlin.py.
Referenced by scipy.sparse.linalg._interface.LinearOperator._rmatmat().
rsolve()
scipy.optimize._nonlin.LinearMixing.rsolve (self, f, tol = 0)
Definition at line 1239 of file _nonlin.py.
solve()
scipy.optimize._nonlin.LinearMixing.solve (self, f, tol = 0)
Reimplemented from scipy.optimize._nonlin.Jacobian.
Definition at line 1233 of file _nonlin.py.
todense()
scipy.optimize._nonlin.LinearMixing.todense (self)
Definition at line 1245 of file _nonlin.py.
Referenced by scipy.sparse._base._spbase._divide(), scipy.sparse._compressed._cs_matrix._maximum_minimum(), scipy.sparse._compressed._cs_matrix._scalar_binopt(), scipy.sparse._dok._dok_base.get(), and scipy.sparse._base._spbase.power().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/optimize/_nonlin.py