Code Cloning Analysis: joblib.numpy_pickle Namespace Reference
joblib.numpy_pickle Namespace Reference
Classes
class NumpyArrayWrapper
class NumpyPickler
class NumpyUnpickler
Functions
dump (value, filename, compress=0, protocol=None)
_unpickle (fobj, ensure_native_byte_order, filename="", mmap_mode=None)
load_temporary_memmap (filename, mmap_mode, unlink_on_gc_collect)
load (filename, mmap_mode=None, ensure_native_byte_order="auto")
Variables
int NUMPY_ARRAY_ALIGNMENT_BYTES = 16
Utility objects for persistence.
Detailed Description
Utilities for fast persistence of big data, with optional compression.
Function Documentation
_unpickle()
joblib.numpy_pickle._unpickle (fobj, ensure_native_byte_order, filename = "", mmap_mode = None) protected
Internal unpickling function.
Definition at line 613 of file numpy_pickle.py.
References _unpickle().
Referenced by _unpickle(), and load().
dump()
joblib.numpy_pickle.dump (value, filename, compress = 0, protocol = None)
Persist an arbitrary Python object into one file.
Read more in the :ref:`User Guide <persistence>`.
Parameters
----------
value: any Python object
    The object to store to disk.
filename: str, pathlib.Path, or file object.
    The file object or path of the file in which it is to be stored.
    The compression method corresponding to one of the supported filename
    extensions ('.z', '.gz', '.bz2', '.xz' or '.lzma') will be used
    automatically.
compress: int from 0 to 9 or bool or 2-tuple, optional
    Optional compression level for the data. 0 or False is no compression.
    Higher value means more compression, but also slower read and
    write times. Using a value of 3 is often a good compromise.
    See the notes for more details.
    If compress is True, the compression level used is 3.
    If compress is a 2-tuple, the first element must correspond to a string
    between supported compressors (e.g 'zlib', 'gzip', 'bz2', 'lzma'
    'xz'), the second element must be an integer from 0 to 9, corresponding
    to the compression level.
protocol: int, optional
    Pickle protocol, see pickle.dump documentation for more details.
Returns
-------
filenames: list of strings
    The list of file names in which the data is stored. If
    compress is false, each array is stored in a different file.
See Also
--------
joblib.load : corresponding loader
Notes
-----
Memmapping on load cannot be used for compressed files. Thus
using compression can significantly slow down loading. In
addition, compressed files take up extra memory during
dump and load.
Definition at line 474 of file numpy_pickle.py.
References dump().
Referenced by dump().
load()
joblib.numpy_pickle.load (filename, mmap_mode = None, ensure_native_byte_order = "auto")
Reconstruct a Python object from a file persisted with joblib.dump.
Read more in the :ref:`User Guide <persistence>`.
WARNING: joblib.load relies on the pickle module and can therefore
execute arbitrary Python code. It should therefore never be used
to load files from untrusted sources.
Parameters
----------
filename: str, pathlib.Path, or file object.
    The file object or path of the file from which to load the object
mmap_mode: {None, 'r+', 'r', 'w+', 'c'}, optional
    If not None, the arrays are memory-mapped from the disk. This
    mode has no effect for compressed files. Note that in this
    case the reconstructed object might no longer match exactly
    the originally pickled object.
ensure_native_byte_order: bool, or 'auto', default=='auto'
    If True, ensures that the byte order of the loaded arrays matches the
    native byte ordering (or _endianness_) of the host system. This is not
    compatible with memory-mapped arrays and using non-null `mmap_mode`
    parameter at the same time will raise an error. The default 'auto'
    parameter is equivalent to True if `mmap_mode` is None, else False.
Returns
-------
result: any Python object
    The object stored in the file.
See Also
--------
joblib.dump : function to save an object
Notes
-----
This function can load numpy array files saved separately during the
dump. If the mmap_mode argument is given, it is passed to np.load and
arrays are loaded as memmaps. As a consequence, the reconstructed
object might not match the original pickled object. Note that if the
file was saved with compression, the arrays cannot be memmapped.
Definition at line 674 of file numpy_pickle.py.
References _unpickle().
load_temporary_memmap()
joblib.numpy_pickle.load_temporary_memmap (filename, mmap_mode, unlink_on_gc_collect)
Definition at line 647 of file numpy_pickle.py.
Variable Documentation
NUMPY_ARRAY_ALIGNMENT_BYTES
int joblib.numpy_pickle.NUMPY_ARRAY_ALIGNMENT_BYTES = 16
Utility objects for persistence.
Definition at line 61 of file numpy_pickle.py.