Code Cloning Analysis: pandas.core.arrays.period Namespace Reference
pandas.core.arrays.period Namespace Reference
Classes
class PeriodArray
Functions
_field_accessor (str name, str|None docstring=None)
IncompatibleFrequency raise_on_incompatible (left, right)
PeriodArray period_array (Sequence[Period|str|None]|AnyArrayLike data, str|Tick|BaseOffset|None freq=None, bool copy=False)
BaseOffsetT validate_dtype_freq (dtype, BaseOffsetT freq)
BaseOffset validate_dtype_freq (dtype, timedelta|str|None freq)
BaseOffsetT validate_dtype_freq (dtype, BaseOffsetT|BaseOffset|timedelta|str|None freq)
tuple[npt.NDArray[np.int64], BaseOffset] dt64arr_to_periodarr (data, freq, tz=None)
_get_ordinal_range (start, end, periods, freq, int mult=1)
tuple[np.ndarray, BaseOffset] _range_from_fields (year=None, month=None, quarter=None, day=None, hour=None, minute=None, second=None, freq=None)
list[np.ndarray] _make_field_arrays (*fields)
Variables
BaseOffsetT = TypeVar("BaseOffsetT", bound=BaseOffset)
dict _shared_doc_kwargs
Function Documentation
_field_accessor()
pandas.core.arrays.period._field_accessor (str name, str | None docstring = None) protected
Definition at line 108 of file period.py.
_get_ordinal_range()
pandas.core.arrays.period._get_ordinal_range (start, end, periods, freq, int mult = 1) protected
Definition at line 1216 of file period.py.
_make_field_arrays()
list[np.ndarray] pandas.core.arrays.period._make_field_arrays (* fields) protected
Definition at line 1314 of file period.py.
_range_from_fields()
tuple[np.ndarray, BaseOffset] pandas.core.arrays.period._range_from_fields (year = None, month = None, quarter = None, day = None, hour = None, minute = None, second = None, freq = None) protected
Definition at line 1265 of file period.py.
dt64arr_to_periodarr()
tuple[npt.NDArray[np.int64], BaseOffset] pandas.core.arrays.period.dt64arr_to_periodarr (data, freq, tz = None)
Convert an datetime-like array to values Period ordinals.
Parameters
----------
data : Union[Series[datetime64[ns]], DatetimeIndex, ndarray[datetime64ns]]
freq : Optional[Union[str, Tick]]
    Must match the `freq` on the `data` if `data` is a DatetimeIndex
    or Series.
tz : Optional[tzinfo]
Returns
-------
ordinals : ndarray[int64]
freq : Tick
    The frequency extracted from the Series or DatetimeIndex if that's
    used.
Definition at line 1176 of file period.py.
Referenced by pandas.core.arrays.period.PeriodArray._from_datetime64().
period_array()
PeriodArray pandas.core.arrays.period.period_array (Sequence[Period | str | None] | AnyArrayLike data, str | Tick | BaseOffset | None freq = None, bool copy = False)
Construct a new PeriodArray from a sequence of Period scalars.
Parameters
----------
data : Sequence of Period objects
    A sequence of Period objects. These are required to all have
    the same ``freq.`` Missing values can be indicated by ``None``
    or ``pandas.NaT``.
freq : str, Tick, or Offset
    The frequency of every element of the array. This can be specified
    to avoid inferring the `freq` from `data`.
copy : bool, default False
    Whether to ensure a copy of the data is made.
Returns
-------
PeriodArray
See Also
--------
PeriodArray
pandas.PeriodIndex
Examples
--------
>>> period_array([pd.Period('2017', freq='Y'),
...               pd.Period('2018', freq='Y')])
<PeriodArray>
['2017', '2018']
Length: 2, dtype: period[Y-DEC]
>>> period_array([pd.Period('2017', freq='Y'),
...               pd.Period('2018', freq='Y'),
...               pd.NaT])
<PeriodArray>
['2017', '2018', 'NaT']
Length: 3, dtype: period[Y-DEC]
Integers that look like years are handled
>>> period_array([2000, 2001, 2002], freq='D')
<PeriodArray>
['2000-01-01', '2001-01-01', '2002-01-01']
Length: 3, dtype: period[D]
Datetime-like strings may also be passed
>>> period_array(['2000-Q1', '2000-Q2', '2000-Q3', '2000-Q4'], freq='Q')
<PeriodArray>
['2000Q1', '2000Q2', '2000Q3', '2000Q4']
Length: 4, dtype: period[Q-DEC]
Definition at line 1030 of file period.py.
raise_on_incompatible()
IncompatibleFrequency pandas.core.arrays.period.raise_on_incompatible (left, right)
Helper function to render a consistent error message when raising
IncompatibleFrequency.
Parameters
----------
left : PeriodArray
right : None, DateOffset, Period, ndarray, or timedelta-like
Returns
-------
IncompatibleFrequency
    Exception to be raised by the caller.
Definition at line 994 of file period.py.
Referenced by pandas.core.arrays.period.PeriodArray._add_timedeltalike_scalar(), and pandas.core.arrays.period.PeriodArray._check_timedeltalike_freq_compat().
validate_dtype_freq() [1/3]
BaseOffsetT pandas.core.arrays.period.validate_dtype_freq (dtype, BaseOffsetT freq)
Definition at line 1130 of file period.py.
validate_dtype_freq() [2/3]
BaseOffsetT pandas.core.arrays.period.validate_dtype_freq (dtype, BaseOffsetT | BaseOffset | timedelta | str | None freq)
If both a dtype and a freq are available, ensure they match.  If only
dtype is available, extract the implied freq.
Parameters
----------
dtype : dtype
freq : DateOffset or None
Returns
-------
freq : DateOffset
Raises
------
ValueError : non-period dtype
IncompatibleFrequency : mismatch between dtype and freq
Definition at line 1139 of file period.py.
validate_dtype_freq() [3/3]
BaseOffset pandas.core.arrays.period.validate_dtype_freq (dtype, timedelta | str | None freq)
Definition at line 1135 of file period.py.
Variable Documentation
_shared_doc_kwargs
dict pandas.core.arrays.period._shared_doc_kwargs protected
Initial value:
=  {
    "klass": "PeriodArray",
}
Definition at line 103 of file period.py.
BaseOffsetT
pandas.core.arrays.period.BaseOffsetT = TypeVar("BaseOffsetT", bound=BaseOffset)
Definition at line 100 of file period.py.