Code Cloning Analysis: matplotlib.cbook Namespace Reference
matplotlib.cbook Namespace Reference
Classes
class _ExceptionInfo
class _OrderedSet
class _Stack
class _StrongRef
class _UnhashDict
class CallbackRegistry
class Grouper
class GrouperView
class silent_list
Functions
_get_running_interactive_framework ()
_exception_printer (exc)
_weak_or_strong_ref (func, callback)
_local_over_kwdict (local_var, kwargs, *keys, warning_cls=_api.MatplotlibDeprecationWarning)
strip_math (s)
_strip_comment (s)
is_writable_file_like (obj)
file_requires_unicode (x)
to_filehandle (fname, flag='r', return_opened=False, encoding=None)
open_file_cm (path_or_file, mode="r", encoding=None)
is_scalar_or_string (val)
get_sample_data (fname, asfileobj=True)
_get_data_path (*args)
flatten (seq, scalarp=is_scalar_or_string)
safe_masked_invalid (x, copy=False)
print_cycles (objects, outstream=sys.stdout, show_progress=False)
simple_linear_interpolation (a, steps)
delete_masked_points (*args)
_combine_masks (*args)
_broadcast_with_masks (*args, compress=False)
boxplot_stats (X, whis=1.5, bootstrap=None, labels=None, autorange=False)
contiguous_regions (mask)
is_math_text (s)
_to_unmasked_float_array (x)
_check_1d (x)
_reshape_2D (X, name)
violin_stats (X, method, points=100, quantiles=None)
pts_to_prestep (x, *args)
pts_to_poststep (x, *args)
pts_to_midstep (x, *args)
index_of (y)
safe_first_element (obj)
_safe_first_finite (obj)
sanitize_sequence (data)
normalize_kwargs (kw, alias_mapping=None)
_lock_path (path)
_topmost_artist (artists, _cached_max=functools.partial(max, key=operator.attrgetter("zorder")))
_str_equal (obj, s)
_str_lower_equal (obj, s)
_array_perimeter (arr)
_unfold (arr, axis, size, step)
_array_patch_perimeters (x, rstride, cstride)
_setattr_cm (obj, **kwargs)
_premultiplied_argb32_to_unmultiplied_rgba8888 (buf)
_unmultiplied_rgba8888_to_premultiplied_argb32 (rgba8888)
_get_nonzero_slices (buf)
_pformat_subprocess (command)
_check_and_log_subprocess (command, logger, **kwargs)
_setup_new_guiapp ()
_format_approx (number, precision)
_g_sig_digits (value, delta)
_unikey_or_keysym_to_mplkey (unikey, keysym)
_make_class_factory (mixin_class, fmt, attr_name=None)
_picklable_class_constructor (mixin_class, fmt, attr_name, base_class)
_is_torch_array (x)
_is_jax_array (x)
_is_tensorflow_array (x)
_unpack_to_numpy (x)
_auto_format_str (fmt, value)
_is_pandas_dataframe (x)
Variables
dict ls_mapper = {'-': 'solid', '--': 'dashed', '-.': 'dashdot', ':': 'dotted'}
dict ls_mapper_r = {v: k for k, v in ls_mapper.items()}
dict STEP_LOOKUP_MAP
Detailed Description
A collection of utility functions and classes.  Originally, many
(but not all) were from the Python Cookbook -- hence the name cbook.
Function Documentation
_array_patch_perimeters()
matplotlib.cbook._array_patch_perimeters (x, rstride, cstride) protected
Extract perimeters of patches from *arr*.
Extracted patches are of size (*rstride* + 1) x (*cstride* + 1) and
share perimeters with their neighbors. The ordering of the vertices matches
that returned by ``_array_perimeter``.
Parameters
----------
x : ndarray, shape (N, M)
    Input array
rstride : int
    Vertical (row) stride between corresponding elements of each patch
cstride : int
    Horizontal (column) stride between corresponding elements of each patch
Returns
-------
ndarray, shape (N/rstride * M/cstride, 2 * (rstride + cstride))
Definition at line 1971 of file cbook.py.
References _unfold().
_array_perimeter()
matplotlib.cbook._array_perimeter (arr) protected
Get the elements on the perimeter of *arr*.
Parameters
----------
arr : ndarray, shape (M, N)
    The input array.
Returns
-------
ndarray, shape (2*(M - 1) + 2*(N - 1),)
    The elements on the perimeter of the array::
       [arr[0, 0], ..., arr[0, -1], ..., arr[-1, -1], ..., arr[-1, 0], ...]
Examples
--------
>>> i, j = np.ogrid[:3, :4]
>>> a = i*10 + j
>>> a
array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])
>>> _array_perimeter(a)
array([ 0,  1,  2,  3, 13, 23, 22, 21, 20, 10])
Definition at line 1882 of file cbook.py.
_auto_format_str()
matplotlib.cbook._auto_format_str (fmt, value) protected
Apply *value* to the format string *fmt*.
This works both with unnamed %-style formatting and
unnamed {}-style formatting. %-style formatting has priority.
If *fmt* is %-style formattable that will be used. Otherwise,
{}-formatting is applied. Strings without formatting placeholders
are passed through as is.
Examples
--------
>>> _auto_format_str('%.2f m', 0.2)
'0.20 m'
>>> _auto_format_str('{} m', 0.2)
'0.2 m'
>>> _auto_format_str('const', 0.2)
'const'
>>> _auto_format_str('%d or {}', 0.2)
'0 or {}'
Definition at line 2379 of file cbook.py.
_broadcast_with_masks()
matplotlib.cbook._broadcast_with_masks (* args, compress = False) protected
Broadcast inputs, combining all masked arrays.
Parameters
----------
*args : array-like
    The inputs to broadcast.
compress : bool, default: False
    Whether to compress the masked arrays. If False, the masked values
    are replaced by NaNs.
Returns
-------
list of array-like
    The broadcasted and masked inputs.
Definition at line 1063 of file cbook.py.
_check_1d()
matplotlib.cbook._check_1d (x) protected
Convert scalars to 1D arrays; pass-through arrays as is.
Definition at line 1358 of file cbook.py.
References _unpack_to_numpy().
Referenced by index_of().
_check_and_log_subprocess()
matplotlib.cbook._check_and_log_subprocess (command, logger, ** kwargs) protected
Run *command*, returning its stdout output if it succeeds.
If it fails (exits with nonzero return code), raise an exception whose text
includes the failed command and captured stdout and stderr output.
Regardless of the return code, the command is logged at DEBUG level on
*logger*.  In case of success, the output is likewise logged.
Definition at line 2151 of file cbook.py.
References _pformat_subprocess().
_combine_masks()
matplotlib.cbook._combine_masks (* args) protected
Find all masked and/or non-finite points in a set of arguments,
and return the arguments as masked arrays with a common mask.
Arguments can be in any of 5 categories:
1) 1-D masked arrays
2) 1-D ndarrays
3) ndarrays with more than one dimension
4) other non-string iterables
5) anything else
The first argument must be in one of the first four categories;
any argument with a length differing from that of the first
argument (and hence anything in category 5) then will be
passed through unchanged.
Masks are obtained from all arguments of the correct length
in categories 1, 2, and 4; a point is bad if masked in a masked
array or if it is a nan or inf.  No attempt is made to
extract a mask from categories 2 and 4 if `numpy.isfinite`
does not yield a Boolean array.  Category 3 is included to
support RGB or RGBA ndarrays, which are assumed to have only
valid values and which are passed through unchanged.
All input arguments that are not passed unchanged are returned
as masked arrays if any masked points are found, otherwise as
ndarrays.
Definition at line 998 of file cbook.py.
References is_scalar_or_string().
_exception_printer()
matplotlib.cbook._exception_printer (exc) protected
Definition at line 108 of file cbook.py.
_format_approx()
matplotlib.cbook._format_approx (number, precision) protected
Format the number with at most the number of decimals given as precision.
Remove trailing zeros and possibly the decimal point.
Definition at line 2198 of file cbook.py.
_g_sig_digits()
matplotlib.cbook._g_sig_digits (value, delta) protected
Return the number of significant digits to %g-format *value*, assuming that
it is known with an error of *delta*.
Definition at line 2206 of file cbook.py.
_get_data_path()
matplotlib.cbook._get_data_path (* args) protected
Return the `pathlib.Path` to a resource file provided by Matplotlib.
``*args`` specify a path relative to the base data path.
Definition at line 597 of file cbook.py.
References matplotlib.get_data_path().
Referenced by get_sample_data().
_get_nonzero_slices()
matplotlib.cbook._get_nonzero_slices (buf) protected
Return the bounds of the nonzero region of a 2D array as a pair of slices.
``buf[_get_nonzero_slices(buf)]`` is the smallest sub-rectangle in *buf*
that encloses all non-zero entries in *buf*.  If *buf* is fully zero, then
``(slice(0, 0), slice(0, 0))`` is returned.
Definition at line 2127 of file cbook.py.
_get_running_interactive_framework()
matplotlib.cbook._get_running_interactive_framework () protected
Return the interactive framework whose event loop is currently running, if
any, or "headless" if no event loop can be started, or None.
Returns
-------
Optional[str]
    One of the following values: "qt", "gtk3", "gtk4", "wx", "tk",
    "macosx", "headless", ``None``.
Definition at line 58 of file cbook.py.
References _get_running_interactive_framework().
Referenced by _get_running_interactive_framework().
_is_jax_array()
matplotlib.cbook._is_jax_array (x) protected
Check if 'x' is a JAX Array.
Definition at line 2325 of file cbook.py.
Referenced by _unpack_to_numpy().
_is_pandas_dataframe()
matplotlib.cbook._is_pandas_dataframe (x) protected
Check if 'x' is a Pandas DataFrame.
Definition at line 2406 of file cbook.py.
_is_tensorflow_array()
matplotlib.cbook._is_tensorflow_array (x) protected
Check if 'x' is a TensorFlow Tensor or Variable.
Definition at line 2337 of file cbook.py.
Referenced by _unpack_to_numpy().
_is_torch_array()
matplotlib.cbook._is_torch_array (x) protected
Check if 'x' is a PyTorch Tensor.
Definition at line 2313 of file cbook.py.
Referenced by _unpack_to_numpy().
_local_over_kwdict()
matplotlib.cbook._local_over_kwdict (local_var, kwargs, * keys, warning_cls = _api.MatplotlibDeprecationWarning) protected
Definition at line 430 of file cbook.py.
_lock_path()
matplotlib.cbook._lock_path (path) protected
Context manager for locking a path.
Usage::
    with _lock_path(path):
        ...
Another thread or process that attempts to lock the same path will wait
until this context manager is exited.
The lock is implemented by creating a temporary file in the parent
directory, so that directory must exist and be writable.
Definition at line 1809 of file cbook.py.
_make_class_factory()
matplotlib.cbook._make_class_factory (mixin_class, fmt, attr_name = None) protected
Return a function that creates picklable classes inheriting from a mixin.
After ::
    factory = _make_class_factory(FooMixin, fmt, attr_name)
    FooAxes = factory(Axes)
``Foo`` is a class that inherits from ``FooMixin`` and ``Axes`` and **is
picklable** (picklability is what differentiates this from a plain call to
`type`).  Its ``__name__`` is set to ``fmt.format(Axes.__name__)`` and the
base class is stored in the ``attr_name`` attribute, if not None.
Moreover, the return value of ``factory`` is memoized: calls with the same
``Axes`` class always return the same subclass.
Definition at line 2260 of file cbook.py.
Referenced by _picklable_class_constructor().
_pformat_subprocess()
matplotlib.cbook._pformat_subprocess (command) protected
Pretty-format a subprocess command for printing/logging purposes.
Definition at line 2145 of file cbook.py.
Referenced by _check_and_log_subprocess().
_picklable_class_constructor()
matplotlib.cbook._picklable_class_constructor (mixin_class, fmt, attr_name, base_class) protected
Internal helper for _make_class_factory.
Definition at line 2306 of file cbook.py.
References _make_class_factory().
_premultiplied_argb32_to_unmultiplied_rgba8888()
matplotlib.cbook._premultiplied_argb32_to_unmultiplied_rgba8888 (buf) protected
Convert a premultiplied ARGB32 buffer to an unmultiplied RGBA8888 buffer.
Definition at line 2089 of file cbook.py.
_reshape_2D()
matplotlib.cbook._reshape_2D (X, name) protected
Use Fortran ordering to convert ndarrays and lists of iterables to lists of
1D arrays.
Lists of iterables are converted by applying `numpy.asanyarray` to each of
their elements.  1D ndarrays are returned in a singleton list containing
them.  2D ndarrays are converted to the list of their *columns*.
*name* is used to generate the error message for invalid inputs.
Definition at line 1373 of file cbook.py.
References _unpack_to_numpy().
Referenced by boxplot_stats(), and violin_stats().
_safe_first_finite()
matplotlib.cbook._safe_first_finite (obj) protected
Return the first finite element in *obj* if one is available and skip_nonfinite is
True. Otherwise, return the first element.
This is a method for internal use.
This is a type-independent way of obtaining the first finite element, supporting
both index access and the iterator protocol.
Definition at line 1705 of file cbook.py.
References safe_first_element().
_setattr_cm()
matplotlib.cbook._setattr_cm (obj, ** kwargs) protected
Temporarily set some attributes; restore original state at context exit.
Definition at line 2021 of file cbook.py.
_setup_new_guiapp()
matplotlib.cbook._setup_new_guiapp () protected
Perform OS-dependent setup when Matplotlib creates a new GUI application.
Definition at line 2184 of file cbook.py.
_str_equal()
matplotlib.cbook._str_equal (obj, s) protected
Return whether *obj* is a string equal to string *s*.
This helper solely exists to handle the case where *obj* is a numpy array,
because in such cases, a naive ``obj == s`` would yield an array, which
cannot be used in a boolean context.
Definition at line 1860 of file cbook.py.
_str_lower_equal()
matplotlib.cbook._str_lower_equal (obj, s) protected
Return whether *obj* is a string equal, when lowercased, to string *s*.
This helper solely exists to handle the case where *obj* is a numpy array,
because in such cases, a naive ``obj == s`` would yield an array, which
cannot be used in a boolean context.
Definition at line 1871 of file cbook.py.
_strip_comment()
matplotlib.cbook._strip_comment (s) protected
Strip everything from the first unquoted #.
Definition at line 468 of file cbook.py.
_to_unmasked_float_array()
matplotlib.cbook._to_unmasked_float_array (x) protected
Convert a sequence to a float array; if input was a masked array, masked
values are converted to nans.
Definition at line 1347 of file cbook.py.
_topmost_artist()
matplotlib.cbook._topmost_artist (artists, _cached_max = functools.partial(max, key=operator.attrgetter("zorder"))) protected
Get the topmost artist of a list.
In case of a tie, return the *last* of the tied artists, as it will be
drawn on top of the others. `max` returns the first maximum in case of
ties, so we need to iterate over the list in reverse order.
Definition at line 1847 of file cbook.py.
_unfold()
matplotlib.cbook._unfold (arr, axis, size, step) protected
Append an extra dimension containing sliding windows along *axis*.
All windows are of size *size* and begin with every *step* elements.
Parameters
----------
arr : ndarray, shape (N_1, ..., N_k)
    The input array
axis : int
    Axis along which the windows are extracted
size : int
    Size of the windows
step : int
    Stride between first elements of subsequent windows.
Returns
-------
ndarray, shape (N_1, ..., 1 + (N_axis-size)/step, ..., N_k, size)
Examples
--------
>>> i, j = np.ogrid[:3, :7]
>>> a = i*10 + j
>>> a
array([[ 0,  1,  2,  3,  4,  5,  6],
       [10, 11, 12, 13, 14, 15, 16],
       [20, 21, 22, 23, 24, 25, 26]])
>>> _unfold(a, axis=1, size=3, step=2)
array([[[ 0,  1,  2],
        [ 2,  3,  4],
        [ 4,  5,  6]],
       [[10, 11, 12],
        [12, 13, 14],
        [14, 15, 16]],
       [[20, 21, 22],
        [22, 23, 24],
        [24, 25, 26]]])
Definition at line 1921 of file cbook.py.
Referenced by _array_patch_perimeters().
_unikey_or_keysym_to_mplkey()
matplotlib.cbook._unikey_or_keysym_to_mplkey (unikey, keysym) protected
Convert a Unicode key or X keysym to a Matplotlib key name.
The Unicode key is checked first; this avoids having to list most printable
keysyms such as ``EuroSign``.
Definition at line 2231 of file cbook.py.
_unmultiplied_rgba8888_to_premultiplied_argb32()
matplotlib.cbook._unmultiplied_rgba8888_to_premultiplied_argb32 (rgba8888) protected
Convert an unmultiplied RGBA8888 buffer to a premultiplied ARGB32 buffer.
Definition at line 2107 of file cbook.py.
_unpack_to_numpy()
matplotlib.cbook._unpack_to_numpy (x) protected
Internal helper to extract data from e.g. pandas and xarray objects.
Definition at line 2352 of file cbook.py.
References _is_jax_array(), _is_tensorflow_array(), and _is_torch_array().
Referenced by _check_1d(), and _reshape_2D().
_weak_or_strong_ref()
matplotlib.cbook._weak_or_strong_ref (func, callback) protected
Return a `WeakMethod` wrapping *func* if possible, else a `_StrongRef`.
Definition at line 133 of file cbook.py.
Referenced by matplotlib.cbook.CallbackRegistry.connect().
boxplot_stats()
matplotlib.cbook.boxplot_stats (X, whis = 1.5, bootstrap = None, labels = None, autorange = False)
Return a list of dictionaries of statistics used to draw a series of box
and whisker plots using `~.Axes.bxp`.
Parameters
----------
X : array-like
Data that will be represented in the boxplots. Should have 2 or
fewer dimensions.
whis : float or (float, float), default: 1.5
The position of the whiskers.
If a float, the lower whisker is at the lowest datum above
``Q1 - whis*(Q3-Q1)``, and the upper whisker at the highest datum below
``Q3 + whis*(Q3-Q1)``, where Q1 and Q3 are the first and third
quartiles.  The default value of ``whis = 1.5`` corresponds to Tukey's
original definition of boxplots.
If a pair of floats, they indicate the percentiles at which to draw the
whiskers (e.g., (5, 95)).  In particular, setting this to (0, 100)
results in whiskers covering the whole range of the data.
In the edge case where ``Q1 == Q3``, *whis* is automatically set to
(0, 100) (cover the whole range of the data) if *autorange* is True.
Beyond the whiskers, data are considered outliers and are plotted as
individual points.
bootstrap : int, optional
Number of times the confidence intervals around the median
should be bootstrapped (percentile method).
labels : list of str, optional
Labels for each dataset. Length must be compatible with
dimensions of *X*.
autorange : bool, optional (False)
When `True` and the data are distributed such that the 25th and 75th
percentiles are equal, ``whis`` is set to (0, 100) such that the
whisker ends are at the minimum and maximum of the data.
Returns
-------
list of dict
A list of dictionaries containing the results for each column
of data. Keys of each dictionary are the following:
========   ===================================
Key        Value Description
========   ===================================
label      tick label for the boxplot
mean       arithmetic mean value
med        50th percentile
q1         first quartile (25th percentile)
q3         third quartile (75th percentile)
iqr        interquartile range
cilo       lower notch around the median
cihi       upper notch around the median
whislo     end of the lower whisker
whishi     end of the upper whisker
fliers     outliers
========   ===================================
Notes
-----
Non-bootstrapping approach to confidence interval uses Gaussian-based
asymptotic approximation:
.. math::
\mathrm{med} \pm 1.57 \times \frac{\mathrm{iqr}}{\sqrt{N}}
General approach from:
McGill, R., Tukey, J.W., and Larsen, W.A. (1978) "Variations of
Boxplots", The American Statistician, 32:12-16.
Definition at line 1101 of file cbook.py.
References _reshape_2D().
contiguous_regions()
matplotlib.cbook.contiguous_regions (mask)
Return a list of (ind0, ind1) such that ``mask[ind0:ind1].all()`` is
True and we cover all such regions.
Definition at line 1308 of file cbook.py.
delete_masked_points()
matplotlib.cbook.delete_masked_points (* args)
Find all masked and/or non-finite points in a set of arguments,
and return the arguments with only the unmasked points remaining.
Arguments can be in any of 5 categories:
1) 1-D masked arrays
2) 1-D ndarrays
3) ndarrays with more than one dimension
4) other non-string iterables
5) anything else
The first argument must be in one of the first four categories;
any argument with a length differing from that of the first
argument (and hence anything in category 5) then will be
passed through unchanged.
Masks are obtained from all arguments of the correct length
in categories 1, 2, and 4; a point is bad if masked in a masked
array or if it is a nan or inf.  No attempt is made to
extract a mask from categories 2, 3, and 4 if `numpy.isfinite`
does not yield a Boolean array.
All input arguments that are not passed unchanged are returned
as ndarrays after removing the points or rows corresponding to
masks in any of the arguments.
A vastly simpler version of this function was originally
written as a helper for Axes.scatter().
Definition at line 921 of file cbook.py.
References is_scalar_or_string().
file_requires_unicode()
matplotlib.cbook.file_requires_unicode (x)
Return whether the given writable file-like object requires Unicode to be
written to it.
Definition at line 493 of file cbook.py.
flatten()
matplotlib.cbook.flatten (seq, scalarp = is_scalar_or_string)
Return a generator of flattened nested containers.
For example:
    >>> from matplotlib.cbook import flatten
    >>> l = (('John', ['Hunter']), (1, 23), [[([42, (5, 23)], )]])
    >>> print(list(flatten(l)))
    ['John', 'Hunter', 1, 23, 42, 5, 23]
By: Composite of Holger Krekel and Luther Blissett
From: https://code.activestate.com/recipes/121294-simple-generator-for-flattening-nested-containers/
and Recipe 1.12 in cookbook
Definition at line 606 of file cbook.py.
References flatten().
Referenced by flatten().
get_sample_data()
matplotlib.cbook.get_sample_data (fname, asfileobj = True)
Return a sample data file.  *fname* is a path relative to the
:file:`mpl-data/sample_data` directory.  If *asfileobj* is `True`
return a file object, otherwise just a file path.
Sample data files are stored in the 'mpl-data/sample_data' directory within
the Matplotlib package.
If the filename ends in .gz, the file is implicitly ungzipped.  If the
filename ends with .npy or .npz, and *asfileobj* is `True`, the file is
loaded with `numpy.load`.
Definition at line 569 of file cbook.py.
References _get_data_path().
index_of()
matplotlib.cbook.index_of (y)
A helper function to create reasonable x values for the given *y*.
This is used for plotting (x, y) if x values are not explicitly given.
First try ``y.index`` (assuming *y* is a `pandas.Series`), if that
fails, use ``range(len(y))``.
This will be extended in the future to deal with more types of
labeled data.
Parameters
----------
y : float or array-like
Returns
-------
x, y : ndarray
   The x and y values to plot.
Definition at line 1650 of file cbook.py.
References _check_1d().
is_math_text()
matplotlib.cbook.is_math_text (s)
Return whether the string *s* contains math expressions.
This is done by checking whether *s* contains an even number of
non-escaped dollar signs.
Definition at line 1334 of file cbook.py.
is_scalar_or_string()
matplotlib.cbook.is_scalar_or_string (val)
Return whether the given object is a scalar or string like.
Definition at line 564 of file cbook.py.
Referenced by _combine_masks(), and delete_masked_points().
is_writable_file_like()
matplotlib.cbook.is_writable_file_like (obj)
Return whether *obj* looks like a file object with a *write* method.
Definition at line 488 of file cbook.py.
normalize_kwargs()
matplotlib.cbook.normalize_kwargs (kw, alias_mapping = None)
Helper function to normalize kwarg inputs.
Parameters
----------
kw : dict or None
    A dict of keyword arguments.  None is explicitly supported and treated
    as an empty dict, to support functions with an optional parameter of
    the form ``props=None``.
alias_mapping : dict or Artist subclass or Artist instance, optional
    A mapping between a canonical name to a list of aliases, in order of
    precedence from lowest to highest.
    If the canonical value is not in the list it is assumed to have the
    highest priority.
    If an Artist subclass or instance is passed, use its properties alias
    mapping.
Raises
------
TypeError
    To match what Python raises if invalid arguments/keyword arguments are
    passed to a callable.
Definition at line 1752 of file cbook.py.
open_file_cm()
matplotlib.cbook.open_file_cm (path_or_file, mode = "r", encoding = None)
Pass through file objects and context-manage path-likes.
Definition at line 558 of file cbook.py.
References to_filehandle().
print_cycles()
matplotlib.cbook.print_cycles (objects, outstream = sys.stdout, show_progress = False)
Print loops of cyclic references in the given *objects*.
It is often useful to pass in ``gc.garbage`` to find the cycles that are
preventing some objects from being garbage collected.
Parameters
----------
objects
    A list of objects to find cycles in.
outstream
    The stream for output.
show_progress : bool
    If True, print the number of objects reached as they are found.
Definition at line 697 of file cbook.py.
pts_to_midstep()
matplotlib.cbook.pts_to_midstep (x, * args)
Convert continuous line to mid-steps.
Given a set of ``N`` points convert to ``2N`` points which when connected
linearly give a step function which changes values at the middle of the
intervals.
Parameters
----------
x : array
    The x location of the steps. May be empty.
y1, ..., yp : array
    y arrays to be turned into steps; all must be the same length as
    ``x``.
Returns
-------
array
    The x and y values converted to steps in the same order as the input;
    can be unpacked as ``x_out, y1_out, ..., yp_out``.  If the input is
    length ``N``, each of these arrays will be length ``2N``.
Examples
--------
>>> x_s, y1_s, y2_s = pts_to_midstep(x, y1, y2)
Definition at line 1605 of file cbook.py.
pts_to_poststep()
matplotlib.cbook.pts_to_poststep (x, * args)
Convert continuous line to post-steps.
Given a set of ``N`` points convert to ``2N + 1`` points, which when
connected linearly give a step function which changes values at the end of
the intervals.
Parameters
----------
x : array
    The x location of the steps. May be empty.
y1, ..., yp : array
    y arrays to be turned into steps; all must be the same length as ``x``.
Returns
-------
array
    The x and y values converted to steps in the same order as the input;
    can be unpacked as ``x_out, y1_out, ..., yp_out``.  If the input is
    length ``N``, each of these arrays will be length ``2N + 1``. For
    ``N=0``, the length will be 0.
Examples
--------
>>> x_s, y1_s, y2_s = pts_to_poststep(x, y1, y2)
Definition at line 1569 of file cbook.py.
pts_to_prestep()
matplotlib.cbook.pts_to_prestep (x, * args)
Convert continuous line to pre-steps.
Given a set of ``N`` points, convert to ``2N - 1`` points, which when
connected linearly give a step function which changes values at the
beginning of the intervals.
Parameters
----------
x : array
    The x location of the steps. May be empty.
y1, ..., yp : array
    y arrays to be turned into steps; all must be the same length as ``x``.
Returns
-------
array
    The x and y values converted to steps in the same order as the input;
    can be unpacked as ``x_out, y1_out, ..., yp_out``.  If the input is
    length ``N``, each of these arrays will be length ``2N + 1``. For
    ``N=0``, the length will be 0.
Examples
--------
>>> x_s, y1_s, y2_s = pts_to_prestep(x, y1, y2)
Definition at line 1531 of file cbook.py.
safe_first_element()
matplotlib.cbook.safe_first_element (obj)
Return the first element in *obj*.
This is a type-independent way of obtaining the first element,
supporting both index access and the iterator protocol.
Definition at line 1685 of file cbook.py.
Referenced by _safe_first_finite().
safe_masked_invalid()
matplotlib.cbook.safe_masked_invalid (x, copy = False)
Definition at line 683 of file cbook.py.
sanitize_sequence()
matplotlib.cbook.sanitize_sequence (data)
Convert dictview objects to list. Other inputs are returned unchanged.
Definition at line 1744 of file cbook.py.
simple_linear_interpolation()
matplotlib.cbook.simple_linear_interpolation (a, steps)
Resample an array with ``steps - 1`` points between original point pairs.
Along each column of *a*, ``(steps - 1)`` points are introduced between
each original values; the values are linearly interpolated.
Parameters
----------
a : array, shape (n, ...)
steps : int
Returns
-------
array
    shape ``((n - 1) * steps + 1, ...)``
Definition at line 897 of file cbook.py.
strip_math()
matplotlib.cbook.strip_math (s)
Remove latex formatting from mathtext.
Only handles fully math and fully non-math strings.
Definition at line 445 of file cbook.py.
to_filehandle()
matplotlib.cbook.to_filehandle (fname, flag = 'r', return_opened = False, encoding = None)
Convert a path to an open file handle or pass-through a file-like object.
Consider using `open_file_cm` instead, as it allows one to properly close
newly created file objects more easily.
Parameters
----------
fname : str or path-like or file-like
    If `str` or `os.PathLike`, the file is opened using the flags specified
    by *flag* and *encoding*.  If a file-like object, it is passed through.
flag : str, default: 'r'
    Passed as the *mode* argument to `open` when *fname* is `str` or
    `os.PathLike`; ignored if *fname* is file-like.
return_opened : bool, default: False
    If True, return both the file object and a boolean indicating whether
    this was a new file (that the caller needs to close).  If False, return
    only the new file.
encoding : str or None, default: None
    Passed as the *mode* argument to `open` when *fname* is `str` or
    `os.PathLike`; ignored if *fname* is file-like.
Returns
-------
fh : file-like
opened : bool
    *opened* is only returned if *return_opened* is True.
Definition at line 506 of file cbook.py.
Referenced by open_file_cm().
violin_stats()
matplotlib.cbook.violin_stats (X, method, points = 100, quantiles = None)
Return a list of dictionaries of data which can be used to draw a series
of violin plots.
See the ``Returns`` section below to view the required keys of the
dictionary.
Users can skip this function and pass a user-defined set of dictionaries
with the same keys to `~.axes.Axes.violinplot` instead of using Matplotlib
to do the calculations. See the *Returns* section below for the keys
that must be present in the dictionaries.
Parameters
----------
X : array-like
    Sample data that will be used to produce the gaussian kernel density
    estimates. Must have 2 or fewer dimensions.
method : callable
    The method used to calculate the kernel density estimate for each
    column of data. When called via ``method(v, coords)``, it should
    return a vector of the values of the KDE evaluated at the values
    specified in coords.
points : int, default: 100
    Defines the number of points to evaluate each of the gaussian kernel
    density estimates at.
quantiles : array-like, default: None
    Defines (if not None) a list of floats in interval [0, 1] for each
    column of data, which represents the quantiles that will be rendered
    for that column of data. Must have 2 or fewer dimensions. 1D array will
    be treated as a singleton list containing them.
Returns
-------
list of dict
    A list of dictionaries containing the results for each column of data.
    The dictionaries contain at least the following:
    - coords: A list of scalars containing the coordinates this particular
      kernel density estimate was evaluated at.
    - vals: A list of scalars containing the values of the kernel density
      estimate at each of the coordinates given in *coords*.
    - mean: The mean value for this column of data.
    - median: The median value for this column of data.
    - min: The minimum value for this column of data.
    - max: The maximum value for this column of data.
    - quantiles: The quantile values for this column of data.
Definition at line 1433 of file cbook.py.
References _reshape_2D().
Variable Documentation
ls_mapper
dict matplotlib.cbook.ls_mapper = {'-': 'solid', '--': 'dashed', '-.': 'dashdot', ':': 'dotted'}
Definition at line 1303 of file cbook.py.
ls_mapper_r
dict matplotlib.cbook.ls_mapper_r = {v: k for k, v in ls_mapper.items()}
Definition at line 1305 of file cbook.py.
STEP_LOOKUP_MAP
dict matplotlib.cbook.STEP_LOOKUP_MAP
Initial value:
=  {'default': lambda x, y: (x, y),
                   'steps': pts_to_prestep,
                   'steps-pre': pts_to_prestep,
                   'steps-post': pts_to_poststep,
                   'steps-mid': pts_to_midstep}
Definition at line 1643 of file cbook.py.