Code Cloning Analysis: contourpy.util.mpl_renderer.MplRenderer Class Reference
contourpy.util.mpl_renderer.MplRenderer Class Reference
Public Member Functions
None __init__ (self, int nrows=1, int ncols=1, tuple[float, float] figsize=(9, 9), bool show_frame=True, str|None backend=None, dict[str, Any]|None gridspec_kw=None)
None __del__ (self)
None filled (self, cpy.FillReturn filled, FillType|str fill_type, Axes|int ax=0, str color="C0", float alpha=0.7)
None grid (self, ArrayLike x, ArrayLike y, Axes|int ax=0, str color="black", float alpha=0.1, str|None point_color=None, float quad_as_tri_alpha=0)
None lines (self, cpy.LineReturn lines, LineType|str line_type, Axes|int ax=0, str color="C0", float alpha=1.0, float linewidth=1)
None mask (self, ArrayLike x, ArrayLike y, ArrayLike|np.ma.MaskedArray[Any, Any] z, Axes|int ax=0, str color="black")
None save (self, str filename, bool transparent=False)
io.BytesIO save_to_buffer (self)
None show (self)
None title (self, str title, Axes|int ax=0, str|None color=None)
None z_values (self, ArrayLike x, ArrayLike y, ArrayLike z, Axes|int ax=0, str color="green", str fmt=".1f", bool quad_as_tri=False)
Public Member Functions inherited from contourpy.util.renderer.Renderer
None multi_filled (self, list[FillReturn] multi_filled, FillType|str fill_type, Any ax=0, str|None color=None, **Any kwargs)
None multi_lines (self, list[LineReturn] multi_lines, LineType|str line_type, Any ax=0, str|None color=None, **Any kwargs)
Protected Member Functions
None _autoscale (self)
Axes _get_ax (self, Axes|int ax)
Protected Member Functions inherited from contourpy.util.renderer.Renderer
tuple[CoordinateArray, CoordinateArray] _grid_as_2d (self, ArrayLike x, ArrayLike y)
Protected Attributes
_fig
bool _want_tight = True
Static Protected Attributes
Sequence _axes [Axes]
Detailed Description
Utility renderer using Matplotlib to render a grid of plots over the same (x, y) range.
Args:
    nrows (int, optional): Number of rows of plots, default ``1``.
    ncols (int, optional): Number of columns of plots, default ``1``.
    figsize (tuple(float, float), optional): Figure size in inches, default ``(9, 9)``.
    show_frame (bool, optional): Whether to show frame and axes ticks, default ``True``.
    backend (str, optional): Matplotlib backend to use or ``None`` for default backend.
        Default ``None``.
    gridspec_kw (dict, optional): Gridspec keyword arguments to pass to ``plt.subplots``,
        default None.
Definition at line 27 of file mpl_renderer.py.
Constructor & Destructor Documentation
__init__()
None contourpy.util.mpl_renderer.MplRenderer.__init__ (self, int nrows = 1, int ncols = 1, tuple[float, float] figsize = (9, 9), bool show_frame = True, str | None backend = None, dict[str, Any] | None gridspec_kw = None)
Definition at line 44 of file mpl_renderer.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
__del__()
None contourpy.util.mpl_renderer.MplRenderer.__del__ (self)
Definition at line 72 of file mpl_renderer.py.
Member Function Documentation
_autoscale()
None contourpy.util.mpl_renderer.MplRenderer._autoscale (self) protected
Definition at line 76 of file mpl_renderer.py.
Referenced by save(), save_to_buffer(), and show().
_get_ax()
Axes contourpy.util.mpl_renderer.MplRenderer._get_ax (self, Axes | int ax) protected
Definition at line 87 of file mpl_renderer.py.
Referenced by pandas.plotting._matplotlib.hist.HistPlot._calculate_bins(), contourpy.util.mpl_renderer.MplDebugRenderer.filled(), filled(), grid(), contourpy.util.mpl_renderer.MplDebugRenderer.lines(), lines(), mask(), pandas.plotting._matplotlib.core.MPLPlot.result(), title(), and z_values().
filled()
None contourpy.util.mpl_renderer.MplRenderer.filled (self, cpy.FillReturn filled, FillType | str fill_type, Axes | int ax = 0, str color = "C0", float alpha = 0.7)
Plot filled contours on a single Axes.
Args:
    filled (sequence of arrays): Filled contour data as returned by
        :meth:`~.ContourGenerator.filled`.
    fill_type (FillType or str): Type of :meth:`~.ContourGenerator.filled` data as returned
        by :attr:`~.ContourGenerator.fill_type`, or string equivalent
    ax (int or Maplotlib Axes, optional): Which axes to plot on, default ``0``.
    color (str, optional): Color to plot with. May be a string color or the letter ``"C"``
        followed by an integer in the range ``"C0"`` to ``"C9"`` to use a color from the
        ``tab10`` colormap. Default ``"C0"``.
    alpha (float, optional): Opacity to plot with, default ``0.7``.
Reimplemented from contourpy.util.renderer.Renderer.
Reimplemented in contourpy.util.mpl_renderer.MplDebugRenderer.
Definition at line 92 of file mpl_renderer.py.
References _get_ax().
Referenced by numpy.ma.core.MaskedArray._insert_masked_print(), numpy.ma.core.MaskedArray.all(), numpy.ma.core.MaskedArray.any(), numpy.ma.core.MaskedArray.argmax(), numpy.ma.core.MaskedArray.argmin(), numpy.ma.core.MaskedArray.argsort(), numpy.ma.core.MaskedArray.cumprod(), numpy.ma.core.MaskedArray.cumsum(), numpy.ma.core.MaskedArray.max(), numpy.ma.core.MaskedArray.min(), contourpy.util.renderer.Renderer.multi_filled(), numpy.ma.core.MaskedArray.nonzero(), numpy.ma.core.MaskedArray.prod(), numpy.ma.core.MaskedArray.sum(), numpy.ma.core.MaskedArray.tobytes(), numpy.ma.core.MaskedArray.tolist(), and numpy.ma.mrecords.MaskedRecords.tolist().
grid()
None contourpy.util.mpl_renderer.MplRenderer.grid (self, ArrayLike x, ArrayLike y, Axes | int ax = 0, str color = "black", float alpha = 0.1, str | None point_color = None, float quad_as_tri_alpha = 0)
Plot quad grid lines on a single Axes.
Args:
    x (array-like of shape (ny, nx) or (nx,)): The x-coordinates of the grid points.
    y (array-like of shape (ny, nx) or (ny,)): The y-coordinates of the grid points.
    ax (int or Matplotlib Axes, optional): Which Axes to plot on, default ``0``.
    color (str, optional): Color to plot grid lines, default ``"black"``.
    alpha (float, optional): Opacity to plot lines with, default ``0.1``.
    point_color (str, optional): Color to plot grid points or ``None`` if grid points
        should not be plotted, default ``None``.
    quad_as_tri_alpha (float, optional): Opacity to plot ``quad_as_tri`` grid, default 0.
Colors may be a string color or the letter ``"C"`` followed by an integer in the range
``"C0"`` to ``"C9"`` to use a color from the ``tab10`` colormap.
Warning:
    ``quad_as_tri_alpha > 0`` plots all quads as though they are unmasked.
Reimplemented from contourpy.util.renderer.Renderer.
Definition at line 121 of file mpl_renderer.py.
References _get_ax(), and contourpy.util.renderer.Renderer._grid_as_2d().
Referenced by matplotlib.axes._base._AxesBase.__clear(), matplotlib.projections.geo.GeoAxes.clear(), matplotlib.projections.polar.PolarAxes.clear(), mplot3d.axes3d.Axes3D.clear(), matplotlib.axes._axes.Axes.cohere(), matplotlib.axes._axes.Axes.csd(), and matplotlib.axes._axes.Axes.psd().
lines()
None contourpy.util.mpl_renderer.MplRenderer.lines (self, cpy.LineReturn lines, LineType | str line_type, Axes | int ax = 0, str color = "C0", float alpha = 1.0, float linewidth = 1)
Plot contour lines on a single Axes.
Args:
    lines (sequence of arrays): Contour line data as returned by
        :meth:`~.ContourGenerator.lines`.
    line_type (LineType or str): Type of :meth:`~.ContourGenerator.lines` data as returned
        by :attr:`~.ContourGenerator.line_type`, or string equivalent.
    ax (int or Matplotlib Axes, optional): Which Axes to plot on, default ``0``.
    color (str, optional): Color to plot lines. May be a string color or the letter ``"C"``
        followed by an integer in the range ``"C0"`` to ``"C9"`` to use a color from the
        ``tab10`` colormap. Default ``"C0"``.
    alpha (float, optional): Opacity to plot lines with, default ``1.0``.
    linewidth (float, optional): Width of lines, default ``1``.
Reimplemented from contourpy.util.renderer.Renderer.
Reimplemented in contourpy.util.mpl_renderer.MplDebugRenderer.
Definition at line 168 of file mpl_renderer.py.
References _get_ax().
Referenced by contourpy.util.renderer.Renderer.multi_lines().
mask()
None contourpy.util.mpl_renderer.MplRenderer.mask (self, ArrayLike x, ArrayLike y, ArrayLike | np.ma.MaskedArray[Any, Any] z, Axes | int ax = 0, str color = "black")
Plot masked out grid points as circles on a single Axes.
Args:
    x (array-like of shape (ny, nx) or (nx,)): The x-coordinates of the grid points.
    y (array-like of shape (ny, nx) or (ny,)): The y-coordinates of the grid points.
    z (masked array of shape (ny, nx): z-values.
    ax (int or Matplotlib Axes, optional): Which Axes to plot on, default ``0``.
    color (str, optional): Circle color, default ``"black"``.
Reimplemented from contourpy.util.renderer.Renderer.
Definition at line 199 of file mpl_renderer.py.
References _get_ax(), and contourpy.util.renderer.Renderer._grid_as_2d().
Referenced by pandas.core.series.Series.combine_first().
save()
None contourpy.util.mpl_renderer.MplRenderer.save (self, str filename, bool transparent = False)
Save plots to SVG or PNG file.
Args:
    filename (str): Filename to save to.
    transparent (bool, optional): Whether background should be transparent, default
        ``False``.
Reimplemented from contourpy.util.renderer.Renderer.
Definition at line 223 of file mpl_renderer.py.
References _autoscale(), and _fig.
Referenced by PIL.Image.Image._repr_image(), PIL.Image.Image.close(), joblib.externals.cloudpickle.cloudpickle.Pickler.reducer_override(), matplotlib.animation.Animation.to_html5_video(), and matplotlib.animation.Animation.to_jshtml().
save_to_buffer()
io.BytesIO contourpy.util.mpl_renderer.MplRenderer.save_to_buffer (self)
Save plots to an ``io.BytesIO`` buffer.
Return:
    BytesIO: PNG image buffer.
Reimplemented from contourpy.util.renderer.Renderer.
Definition at line 234 of file mpl_renderer.py.
References _autoscale(), and _fig.
show()
None contourpy.util.mpl_renderer.MplRenderer.show (self)
Show plots in an interactive window, in the usual Matplotlib manner.
Reimplemented from contourpy.util.renderer.Renderer.
Definition at line 246 of file mpl_renderer.py.
References _autoscale().
Referenced by matplotlib.backends.backend_nbagg.FigureManagerNbAgg.reshow().
title()
None contourpy.util.mpl_renderer.MplRenderer.title (self, str title, Axes | int ax = 0, str | None color = None)
Set the title of a single Axes.
Args:
    title (str): Title text.
    ax (int or Matplotlib Axes, optional): Which Axes to set the title of, default ``0``.
    color (str, optional): Color to set title. May be a string color or the letter ``"C"``
        followed by an integer in the range ``"C0"`` to ``"C9"`` to use a color from the
        ``tab10`` colormap. Default is ``None`` which uses Matplotlib's default title color
        that depends on the stylesheet in use.
Reimplemented from contourpy.util.renderer.Renderer.
Definition at line 252 of file mpl_renderer.py.
References _get_ax().
z_values()
None contourpy.util.mpl_renderer.MplRenderer.z_values (self, ArrayLike x, ArrayLike y, ArrayLike z, Axes | int ax = 0, str color = "green", str fmt = ".1f", bool quad_as_tri = False)
Show ``z`` values on a single Axes.
Args:
    x (array-like of shape (ny, nx) or (nx,)): The x-coordinates of the grid points.
    y (array-like of shape (ny, nx) or (ny,)): The y-coordinates of the grid points.
    z (array-like of shape (ny, nx): z-values.
    ax (int or Matplotlib Axes, optional): Which Axes to plot on, default ``0``.
    color (str, optional): Color of added text. May be a string color or the letter ``"C"``
        followed by an integer in the range ``"C0"`` to ``"C9"`` to use a color from the
        ``tab10`` colormap. Default ``"green"``.
    fmt (str, optional): Format to display z-values, default ``".1f"``.
    quad_as_tri (bool, optional): Whether to show z-values at the ``quad_as_tri`` centers
        of quads.
Warning:
    ``quad_as_tri=True`` shows z-values for all quads, even if masked.
Reimplemented from contourpy.util.renderer.Renderer.
Definition at line 268 of file mpl_renderer.py.
References _get_ax(), and contourpy.util.renderer.Renderer._grid_as_2d().
Member Data Documentation
_axes
contourpy.util.mpl_renderer.MplRenderer._axes [Axes] static protected
Definition at line 40 of file mpl_renderer.py.
Referenced by axes_grid1.axes_divider.AxesDivider.__init__(), matplotlib.axes._base._AxesBase.ArtistList.__init__(), matplotlib.quiver.Quiver.__init__(), matplotlib.table.Table.__init__(), pandas.core.internals.array_manager.BaseArrayManager._reindex_indexer(), matplotlib.projections.polar.RadialLocator._zero_in_bounds(), matplotlib.figure._AxesStack.add(), pandas.core.internals.array_manager.BaseArrayManager.add_references(), pandas.core.internals.array_manager.BaseArrayManager.apply(), pandas.core.internals.array_manager.SingleArrayManager.apply(), matplotlib.figure._AxesStack.as_list(), pandas.core.internals.array_manager.BaseArrayManager.axes(), pandas.core.internals.array_manager.SingleArrayManager.axes(), matplotlib.figure._AxesStack.bubble(), pandas.core.internals.array_manager.ArrayManager.column_setitem(), pandas.core.internals.array_manager.BaseArrayManager.copy(), matplotlib.figure._AxesStack.current(), matplotlib.table.Table.edges(), pandas.core.internals.array_manager.ArrayManager.fast_xs(), axes_grid1.axes_divider.AxesDivider.get_anchor(), axes_grid1.axes_divider.AxesDivider.get_aspect(), axes_grid1.axes_divider.AxesDivider.get_position(), axes_grid1.axes_size.AxesX.get_size(), axes_grid1.axes_size.AxesY.get_size(), pandas.core.internals.array_manager.ArrayManager.idelete(), pandas.core.internals.array_manager.SingleArrayManager.idelete(), pandas.core.internals.array_manager.ArrayManager.iget(), pandas.core.internals.array_manager.ArrayManager.insert(), pandas.core.internals.array_manager.BaseArrayManager.is_view(), pandas.core.internals.array_manager.ArrayManager.iset(), pandas.core.internals.array_manager.BaseArrayManager.make_empty(), pandas.core.internals.array_manager.ArrayManager.operate_blockwise(), matplotlib.figure._AxesStack.remove(), pandas.core.internals.array_manager.BaseArrayManager.take(), and pandas.core.internals.array_manager.ArrayManager.unstack().
_fig
contourpy.util.mpl_renderer.MplRenderer._fig protected
Definition at line 64 of file mpl_renderer.py.
Referenced by axes_grid1.axes_divider.Divider.__init__(), axes_grid1.axes_divider.Divider._locate(), axes_grid1.axes_divider.HBoxDivider._locate(), axes_grid1.axes_divider.VBoxDivider._locate(), matplotlib.animation.Animation._start(), matplotlib.animation.TimedAnimation._step(), axes_grid1.axes_divider.AxesDivider.append_axes(), matplotlib.animation.Animation.new_saved_frame_seq(), save(), matplotlib.animation.Animation.save(), and save_to_buffer().
_want_tight
bool contourpy.util.mpl_renderer.MplRenderer._want_tight = True protected
Definition at line 70 of file mpl_renderer.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/contourpy/util/mpl_renderer.py