Code Cloning Analysis: numpy.array_api.linalg Namespace Reference
numpy.array_api.linalg Namespace Reference
Classes
class EighResult
class QRResult
class SlogdetResult
class SVDResult
Functions
Array cholesky (Array x, *, bool upper=False)
Array cross (Array x1, Array x2, *, int axis=-1)
Array det (Array x)
Array diagonal (Array x, *, int offset=0)
EighResult eigh (Array x)
Array eigvalsh (Array x)
Array inv (Array x)
Array matmul (Array x1, Array x2)
Array matrix_norm (Array x, *, bool keepdims=False, Optional[Union[int, float, Literal['fro', 'nuc']]] ord='fro')
Array matrix_power (Array x, int n)
Array matrix_rank (Array x, *, Optional[Union[float, Array]] rtol=None)
Array matrix_transpose (Array x)
Array outer (Array x1, Array x2)
Array pinv (Array x, *, Optional[Union[float, Array]] rtol=None)
QRResult qr (Array x, *, Literal['reduced', 'complete'] mode='reduced')
SlogdetResult slogdet (Array x)
_solve (a, b)
Array solve (Array x1, Array x2)
SVDResult svd (Array x, *, bool full_matrices=True)
Union[Array, Tuple[Array,...]] svdvals (Array x)
Array tensordot (Array x1, Array x2, *, Union[int, Tuple[Sequence[int], Sequence[int]]] axes=2)
Array trace (Array x, *, int offset=0, Optional[Dtype] dtype=None)
Array vecdot (Array x1, Array x2, *, int axis=-1)
Array vector_norm (Array x, *, Optional[Union[int, Tuple[int,...]]] axis=None, bool keepdims=False, Optional[Union[int, float]] ord=2)
Variables
list __all__ = ['cholesky', 'cross', 'det', 'diagonal', 'eigh', 'eigvalsh', 'inv', 'matmul', 'matrix_norm', 'matrix_power', 'matrix_rank', 'matrix_transpose', 'outer', 'pinv', 'qr', 'slogdet', 'solve', 'svd', 'svdvals', 'tensordot', 'trace', 'vecdot', 'vector_norm']
Function Documentation
_solve()
numpy.array_api.linalg._solve (a, b) protected
Definition at line 303 of file linalg.py.
cholesky()
Array numpy.array_api.linalg.cholesky (Array x, * , bool upper = False)
Array API compatible wrapper for :py:func:`np.linalg.cholesky <numpy.linalg.cholesky>`.
See its docstring for more information.
Definition at line 45 of file linalg.py.
cross()
Array numpy.array_api.linalg.cross (Array x1, Array x2, * , int axis = -1)
Array API compatible wrapper for :py:func:`np.cross <numpy.cross>`.
See its docstring for more information.
Definition at line 64 of file linalg.py.
det()
Array numpy.array_api.linalg.det (Array x)
Array API compatible wrapper for :py:func:`np.linalg.det <numpy.linalg.det>`.
See its docstring for more information.
Definition at line 82 of file linalg.py.
diagonal()
Array numpy.array_api.linalg.diagonal (Array x, * , int offset = 0)
Array API compatible wrapper for :py:func:`np.diagonal <numpy.diagonal>`.
See its docstring for more information.
Definition at line 95 of file linalg.py.
eigh()
EighResult numpy.array_api.linalg.eigh (Array x)
Array API compatible wrapper for :py:func:`np.linalg.eigh <numpy.linalg.eigh>`.
See its docstring for more information.
Definition at line 106 of file linalg.py.
eigvalsh()
Array numpy.array_api.linalg.eigvalsh (Array x)
Array API compatible wrapper for :py:func:`np.linalg.eigvalsh <numpy.linalg.eigvalsh>`.
See its docstring for more information.
Definition at line 122 of file linalg.py.
inv()
Array numpy.array_api.linalg.inv (Array x)
Array API compatible wrapper for :py:func:`np.linalg.inv <numpy.linalg.inv>`.
See its docstring for more information.
Definition at line 135 of file linalg.py.
matmul()
Array numpy.array_api.linalg.matmul (Array x1, Array x2)
Array API compatible wrapper for :py:func:`np.matmul <numpy.matmul>`.
See its docstring for more information.
Definition at line 150 of file linalg.py.
matrix_norm()
Array numpy.array_api.linalg.matrix_norm (Array x, * , bool keepdims = False, Optional[Union[int, float, Literal['fro', 'nuc']]] ord = 'fro')
Array API compatible wrapper for :py:func:`np.linalg.norm <numpy.linalg.norm>`.
See its docstring for more information.
Definition at line 170 of file linalg.py.
matrix_power()
Array numpy.array_api.linalg.matrix_power (Array x, int n)
Array API compatible wrapper for :py:func:`np.matrix_power <numpy.matrix_power>`.
See its docstring for more information.
Definition at line 184 of file linalg.py.
matrix_rank()
Array numpy.array_api.linalg.matrix_rank (Array x, * , Optional[Union[float, Array]] rtol = None)
Array API compatible wrapper for :py:func:`np.matrix_rank <numpy.matrix_rank>`.
See its docstring for more information.
Definition at line 199 of file linalg.py.
References numpy.core.fromnumeric.max().
matrix_transpose()
Array numpy.array_api.linalg.matrix_transpose (Array x)
Definition at line 223 of file linalg.py.
outer()
Array numpy.array_api.linalg.outer (Array x1, Array x2)
Array API compatible wrapper for :py:func:`np.outer <numpy.outer>`.
See its docstring for more information.
Definition at line 229 of file linalg.py.
pinv()
Array numpy.array_api.linalg.pinv (Array x, * , Optional[Union[float, Array]] rtol = None)
Array API compatible wrapper for :py:func:`np.linalg.pinv <numpy.linalg.pinv>`.
See its docstring for more information.
Definition at line 247 of file linalg.py.
References numpy.core.fromnumeric.max().
qr()
QRResult numpy.array_api.linalg.qr (Array x, * , Literal['reduced', 'complete'] mode = 'reduced')
Array API compatible wrapper for :py:func:`np.linalg.qr <numpy.linalg.qr>`.
See its docstring for more information.
Definition at line 264 of file linalg.py.
slogdet()
SlogdetResult numpy.array_api.linalg.slogdet (Array x)
Array API compatible wrapper for :py:func:`np.linalg.slogdet <numpy.linalg.slogdet>`.
See its docstring for more information.
Definition at line 279 of file linalg.py.
solve()
Array numpy.array_api.linalg.solve (Array x1, Array x2)
Array API compatible wrapper for :py:func:`np.linalg.solve <numpy.linalg.solve>`.
See its docstring for more information.
Definition at line 331 of file linalg.py.
svd()
SVDResult numpy.array_api.linalg.svd (Array x, * , bool full_matrices = True)
Array API compatible wrapper for :py:func:`np.linalg.svd <numpy.linalg.svd>`.
See its docstring for more information.
Definition at line 344 of file linalg.py.
svdvals()
Union[Array, Tuple[Array, ...]] numpy.array_api.linalg.svdvals (Array x)
Definition at line 361 of file linalg.py.
tensordot()
Array numpy.array_api.linalg.tensordot (Array x1, Array x2, * , Union[int, Tuple[Sequence[int], Sequence[int]]] axes = 2)
Definition at line 369 of file linalg.py.
trace()
Array numpy.array_api.linalg.trace (Array x, * , int offset = 0, Optional[Dtype] dtype = None)
Array API compatible wrapper for :py:func:`np.trace <numpy.trace>`.
See its docstring for more information.
Definition at line 378 of file linalg.py.
References numpy.core.fromnumeric.max().
vecdot()
Array numpy.array_api.linalg.vecdot (Array x1, Array x2, * , int axis = -1)
Definition at line 399 of file linalg.py.
vector_norm()
Array numpy.array_api.linalg.vector_norm (Array x, * , Optional[Union[int, Tuple[int, ...]]] axis = None, bool keepdims = False, Optional[Union[int, float]] ord = 2)
Array API compatible wrapper for :py:func:`np.linalg.norm <numpy.linalg.norm>`.
See its docstring for more information.
Definition at line 421 of file linalg.py.
References numpy.core.numeric.normalize_axis_tuple(), and numpy.core.fromnumeric.reshape().
Variable Documentation
__all__
list numpy.array_api.linalg.__all__ = ['cholesky', 'cross', 'det', 'diagonal', 'eigh', 'eigvalsh', 'inv', 'matmul', 'matrix_norm', 'matrix_power', 'matrix_rank', 'matrix_transpose', 'outer', 'pinv', 'qr', 'slogdet', 'solve', 'svd', 'svdvals', 'tensordot', 'trace', 'vecdot', 'vector_norm'] private
Definition at line 466 of file linalg.py.