Code Cloning Analysis: numpy.lib.tests.test_histograms.TestHistogramdd Class Reference
numpy.lib.tests.test_histograms.TestHistogramdd Class Reference
Public Member Functions
test_simple (self)
test_shape_3d (self)
test_shape_4d (self)
test_weights (self)
test_identical_samples (self)
test_empty (self)
test_bins_errors (self)
test_inf_edges (self)
test_rightmost_binedge (self)
test_finite_range (self)
test_equal_edges (self)
test_edge_dtype (self)
test_large_integers (self)
test_density_non_uniform_2d (self)
test_density_non_uniform_1d (self)
Detailed Description
Definition at line 608 of file test_histograms.py.
Member Function Documentation
test_bins_errors()
numpy.lib.tests.test_histograms.TestHistogramdd.test_bins_errors (self)
Definition at line 692 of file test_histograms.py.
test_density_non_uniform_1d()
numpy.lib.tests.test_histograms.TestHistogramdd.test_density_non_uniform_1d (self)
Definition at line 809 of file test_histograms.py.
test_density_non_uniform_2d()
numpy.lib.tests.test_histograms.TestHistogramdd.test_density_non_uniform_2d (self)
Definition at line 782 of file test_histograms.py.
test_edge_dtype()
numpy.lib.tests.test_histograms.TestHistogramdd.test_edge_dtype (self)
 Test that if an edge array is input, its type is preserved
Definition at line 759 of file test_histograms.py.
References numpy.lib.histograms.histogram(), and numpy.lib.histograms.histogramdd().
test_empty()
numpy.lib.tests.test_histograms.TestHistogramdd.test_empty (self)
Definition at line 686 of file test_histograms.py.
test_equal_edges()
numpy.lib.tests.test_histograms.TestHistogramdd.test_equal_edges (self)
 Test that adjacent entries in an edge array can be equal
Definition at line 745 of file test_histograms.py.
References numpy.lib.histograms.histogramdd().
test_finite_range()
numpy.lib.tests.test_histograms.TestHistogramdd.test_finite_range (self)
Definition at line 737 of file test_histograms.py.
test_identical_samples()
numpy.lib.tests.test_histograms.TestHistogramdd.test_identical_samples (self)
Definition at line 681 of file test_histograms.py.
test_inf_edges()
numpy.lib.tests.test_histograms.TestHistogramdd.test_inf_edges (self)
Definition at line 702 of file test_histograms.py.
test_large_integers()
numpy.lib.tests.test_histograms.TestHistogramdd.test_large_integers (self)
Definition at line 770 of file test_histograms.py.
test_rightmost_binedge()
numpy.lib.tests.test_histograms.TestHistogramdd.test_rightmost_binedge (self)
Definition at line 714 of file test_histograms.py.
test_shape_3d()
numpy.lib.tests.test_histograms.TestHistogramdd.test_shape_3d (self)
Definition at line 647 of file test_histograms.py.
test_shape_4d()
numpy.lib.tests.test_histograms.TestHistogramdd.test_shape_4d (self)
Definition at line 656 of file test_histograms.py.
test_simple()
numpy.lib.tests.test_histograms.TestHistogramdd.test_simple (self)
Definition at line 610 of file test_histograms.py.
test_weights()
numpy.lib.tests.test_histograms.TestHistogramdd.test_weights (self)
Definition at line 670 of file test_histograms.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/lib/tests/test_histograms.py