Code Cloning Analysis: pandas.tests.dtypes.test_dtypes.TestPeriodDtype Class Reference
pandas.tests.dtypes.test_dtypes.TestPeriodDtype Class Reference
Public Member Functions
dtype (self)
test_hash_vs_equality (self, dtype)
test_construction (self)
test_cannot_use_custom_businessday (self)
test_subclass (self)
test_identity (self)
test_compat (self, dtype)
test_construction_from_string (self, dtype)
test_construct_dtype_from_string_invalid_raises (self, string)
test_is_dtype (self, dtype)
test_equality (self, dtype)
test_basic (self, dtype)
test_freq_argument_required (self)
test_not_string (self)
test_perioddtype_caching_dateoffset_normalize (self)
test_dont_keep_ref_after_del (self)
Public Member Functions inherited from pandas.tests.dtypes.test_dtypes.Base
test_hash (self, dtype)
test_equality_invalid (self, dtype)
test_numpy_informed (self, dtype)
test_pickle (self, dtype)
Detailed Description
Definition at line 402 of file test_dtypes.py.
Member Function Documentation
dtype()
pandas.tests.dtypes.test_dtypes.TestPeriodDtype.dtype (self)
Class level fixture of dtype for TestPeriodDtype
Definition at line 404 of file test_dtypes.py.
Referenced by pandas.core.arrays.base.ExtensionScalarOpsMixin._create_method(), scipy.sparse._index.IndexMixin._getcol(), pandas.core.generic.NDFrame._inplace_method(), scipy.sparse._index.IndexMixin._raise_on_1d_array_slice(), pandas.core.strings.object_array.ObjectStringArrayMixin._str_map(), numpy.matrixlib.defmatrix.matrix.H(), numpy.core.records.record.pprint(), pandas.core.frame.DataFrame.quantile(), and pandas.core.generic.NDFrame.rank().
test_basic()
pandas.tests.dtypes.test_dtypes.TestPeriodDtype.test_basic (self, dtype)
Definition at line 532 of file test_dtypes.py.
test_cannot_use_custom_businessday()
pandas.tests.dtypes.test_dtypes.TestPeriodDtype.test_cannot_use_custom_businessday (self)
Definition at line 446 of file test_dtypes.py.
test_compat()
pandas.tests.dtypes.test_dtypes.TestPeriodDtype.test_compat (self, dtype)
Definition at line 474 of file test_dtypes.py.
test_construct_dtype_from_string_invalid_raises()
pandas.tests.dtypes.test_dtypes.TestPeriodDtype.test_construct_dtype_from_string_invalid_raises (self, string)
Definition at line 499 of file test_dtypes.py.
test_construction()
pandas.tests.dtypes.test_dtypes.TestPeriodDtype.test_construction (self)
Definition at line 423 of file test_dtypes.py.
test_construction_from_string()
pandas.tests.dtypes.test_dtypes.TestPeriodDtype.test_construction_from_string (self, dtype)
Definition at line 480 of file test_dtypes.py.
test_dont_keep_ref_after_del()
pandas.tests.dtypes.test_dtypes.TestPeriodDtype.test_dont_keep_ref_after_del (self)
Definition at line 573 of file test_dtypes.py.
test_equality()
pandas.tests.dtypes.test_dtypes.TestPeriodDtype.test_equality (self, dtype)
Definition at line 523 of file test_dtypes.py.
test_freq_argument_required()
pandas.tests.dtypes.test_dtypes.TestPeriodDtype.test_freq_argument_required (self)
Definition at line 550 of file test_dtypes.py.
test_hash_vs_equality()
pandas.tests.dtypes.test_dtypes.TestPeriodDtype.test_hash_vs_equality (self, dtype)
Definition at line 410 of file test_dtypes.py.
test_identity()
pandas.tests.dtypes.test_dtypes.TestPeriodDtype.test_identity (self)
Definition at line 464 of file test_dtypes.py.
test_is_dtype()
pandas.tests.dtypes.test_dtypes.TestPeriodDtype.test_is_dtype (self, dtype)
Definition at line 504 of file test_dtypes.py.
test_not_string()
pandas.tests.dtypes.test_dtypes.TestPeriodDtype.test_not_string (self)
Definition at line 561 of file test_dtypes.py.
test_perioddtype_caching_dateoffset_normalize()
pandas.tests.dtypes.test_dtypes.TestPeriodDtype.test_perioddtype_caching_dateoffset_normalize (self)
Definition at line 565 of file test_dtypes.py.
test_subclass()
pandas.tests.dtypes.test_dtypes.TestPeriodDtype.test_subclass (self)
Definition at line 457 of file test_dtypes.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/tests/dtypes/test_dtypes.py