Code Cloning Analysis: scipy.stats._binomtest Namespace Reference
scipy.stats._binomtest Namespace Reference
Classes
class BinomTestResult
Functions
_findp (func)
_binom_exact_conf_int (k, n, confidence_level, alternative)
_binom_wilson_conf_int (k, n, confidence_level, alternative, correction)
binomtest (k, n, p=0.5, alternative='two-sided')
_binary_search_for_binom_tst (a, d, lo, hi)
Function Documentation
_binary_search_for_binom_tst()
scipy.stats._binomtest._binary_search_for_binom_tst (a, d, lo, hi) protected
Conducts an implicit binary search on a function specified by `a`.
Meant to be used on the binomial PMF for the case of two-sided tests
to obtain the value on the other side of the mode where the tail
probability should be computed. The values on either side of
the mode are always in order, meaning binary search is applicable.
Parameters
----------
a : callable
  The function over which to perform binary search. Its values
  for inputs lo and hi should be in ascending order.
d : float
  The value to search.
lo : int
  The lower end of range to search.
hi : int
  The higher end of the range to search.
Returns
-------
int
  The index, i between lo and hi
  such that a(i)<=d<a(i+1)
Definition at line 336 of file _binomtest.py.
Referenced by binomtest().
_binom_exact_conf_int()
scipy.stats._binomtest._binom_exact_conf_int (k, n, confidence_level, alternative) protected
Compute the estimate and confidence interval for the binomial test.
Returns proportion, prop_low, prop_high
Definition at line 129 of file _binomtest.py.
Referenced by scipy.stats._binomtest.BinomTestResult.proportion_ci().
_binom_wilson_conf_int()
scipy.stats._binomtest._binom_wilson_conf_int (k, n, confidence_level, alternative, correction) protected
Definition at line 162 of file _binomtest.py.
_findp()
scipy.stats._binomtest._findp (func) protected
Definition at line 117 of file _binomtest.py.
binomtest()
scipy.stats._binomtest.binomtest (k, n, p = 0.5, alternative = 'two-sided')
Perform a test that the probability of success is p.
The binomial test [1]_ is a test of the null hypothesis that the
probability of success in a Bernoulli experiment is `p`.
Details of the test can be found in many texts on statistics, such
as section 24.5 of [2]_.
Parameters
----------
k : int
    The number of successes.
n : int
    The number of trials.
p : float, optional
    The hypothesized probability of success, i.e. the expected
    proportion of successes.  The value must be in the interval
    ``0 <= p <= 1``. The default value is ``p = 0.5``.
alternative : {'two-sided', 'greater', 'less'}, optional
    Indicates the alternative hypothesis. The default value is
    'two-sided'.
Returns
-------
result : `~scipy.stats._result_classes.BinomTestResult` instance
    The return value is an object with the following attributes:
    k : int
        The number of successes (copied from `binomtest` input).
    n : int
        The number of trials (copied from `binomtest` input).
    alternative : str
        Indicates the alternative hypothesis specified in the input
        to `binomtest`.  It will be one of ``'two-sided'``, ``'greater'``,
        or ``'less'``.
    statistic : float
        The estimate of the proportion of successes.
    pvalue : float
        The p-value of the hypothesis test.
    The object has the following methods:
    proportion_ci(confidence_level=0.95, method='exact') :
        Compute the confidence interval for ``statistic``.
Notes
-----
.. versionadded:: 1.7.0
References
----------
.. [1] Binomial test, https://en.wikipedia.org/wiki/Binomial_test
.. [2] Jerrold H. Zar, Biostatistical Analysis (fifth edition),
       Prentice Hall, Upper Saddle River, New Jersey USA (2010)
Examples
--------
>>> from scipy.stats import binomtest
A car manufacturer claims that no more than 10% of their cars are unsafe.
15 cars are inspected for safety, 3 were found to be unsafe. Test the
manufacturer's claim:
>>> result = binomtest(3, n=15, p=0.1, alternative='greater')
>>> result.pvalue
0.18406106910639114
The null hypothesis cannot be rejected at the 5% level of significance
because the returned p-value is greater than the critical value of 5%.
The test statistic is equal to the estimated proportion, which is simply
``3/15``:
>>> result.statistic
0.2
We can use the `proportion_ci()` method of the result to compute the
confidence interval of the estimate:
>>> result.proportion_ci(confidence_level=0.95)
ConfidenceInterval(low=0.05684686759024681, high=1.0)
Definition at line 202 of file _binomtest.py.
References _binary_search_for_binom_tst().