Code Cloning Analysis: sklearn.ensemble._forest Namespace Reference
sklearn.ensemble._forest Namespace Reference
Classes
class BaseForest
class ExtraTreesClassifier
class ExtraTreesRegressor
class ForestClassifier
class ForestRegressor
class RandomForestClassifier
class RandomForestRegressor
class RandomTreesEmbedding
Functions
_get_n_samples_bootstrap (n_samples, max_samples)
_generate_sample_indices (random_state, n_samples, n_samples_bootstrap)
_generate_unsampled_indices (random_state, n_samples, n_samples_bootstrap)
_parallel_build_trees (tree, bootstrap, X, y, sample_weight, tree_idx, n_trees, verbose=0, class_weight=None, n_samples_bootstrap=None, missing_values_in_feature_mask=None)
_accumulate_prediction (predict, X, out, lock)
Variables
list __all__
MAX_INT = np.iinfo(np.int32).max
Detailed Description
Forest of trees-based ensemble methods.
Those methods include random forests and extremely randomized trees.
The module structure is the following:
- The ``BaseForest`` base class implements a common ``fit`` method for all
  the estimators in the module. The ``fit`` method of the base ``Forest``
  class calls the ``fit`` method of each sub-estimator on random samples
  (with replacement, a.k.a. bootstrap) of the training set.
  The init of the sub-estimator is further delegated to the
  ``BaseEnsemble`` constructor.
- The ``ForestClassifier`` and ``ForestRegressor`` base classes further
  implement the prediction logic by computing an average of the predicted
  outcomes of the sub-estimators.
- The ``RandomForestClassifier`` and ``RandomForestRegressor`` derived
  classes provide the user with concrete implementations of
  the forest ensemble method using classical, deterministic
  ``DecisionTreeClassifier`` and ``DecisionTreeRegressor`` as
  sub-estimator implementations.
- The ``ExtraTreesClassifier`` and ``ExtraTreesRegressor`` derived
  classes provide the user with concrete implementations of the
  forest ensemble method using the extremely randomized trees
  ``ExtraTreeClassifier`` and ``ExtraTreeRegressor`` as
  sub-estimator implementations.
Single and multi-output problems are both handled.
Function Documentation
_accumulate_prediction()
sklearn.ensemble._forest._accumulate_prediction (predict, X, out, lock) protected
This is a utility function for joblib's Parallel.
It can't go locally in ForestClassifier or ForestRegressor, because joblib
complains that it cannot pickle it when placed there.
Definition at line 723 of file _forest.py.
_generate_sample_indices()
sklearn.ensemble._forest._generate_sample_indices (random_state, n_samples, n_samples_bootstrap) protected
Private function used to _parallel_build_trees function.
Definition at line 124 of file _forest.py.
Referenced by _generate_unsampled_indices(), _parallel_build_trees(), and sklearn.ensemble._forest.BaseForest.feature_importances_().
_generate_unsampled_indices()
sklearn.ensemble._forest._generate_unsampled_indices (random_state, n_samples, n_samples_bootstrap) protected
Private function used to forest._set_oob_score function.
Definition at line 136 of file _forest.py.
References _generate_sample_indices().
_get_n_samples_bootstrap()
sklearn.ensemble._forest._get_n_samples_bootstrap (n_samples, max_samples) protected
Get the number of samples in a bootstrap sample.
Parameters
----------
n_samples : int
    Number of samples in the dataset.
max_samples : int or float
    The maximum number of samples to draw from the total available:
        - if float, this indicates a fraction of the total and should be
          the interval `(0.0, 1.0]`;
        - if int, this indicates the exact number of samples;
        - if None, this indicates the total number of samples.
Returns
-------
n_samples_bootstrap : int
    The total number of samples to draw for the bootstrap sample.
Definition at line 91 of file _forest.py.
Referenced by sklearn.ensemble._forest.BaseForest.fit().
_parallel_build_trees()
sklearn.ensemble._forest._parallel_build_trees (tree, bootstrap, X, y, sample_weight, tree_idx, n_trees, verbose = 0, class_weight = None, n_samples_bootstrap = None, missing_values_in_feature_mask = None) protected
Private function used to fit a single tree in parallel.
Definition at line 150 of file _forest.py.
References _generate_sample_indices().
Variable Documentation
__all__
list sklearn.ensemble._forest.__all__ private
Initial value:
=  [
    "ExtraTreesClassifier",
    "ExtraTreesRegressor",
    "RandomForestClassifier",
    "RandomForestRegressor",
    "RandomTreesEmbedding",
]
Definition at line 80 of file _forest.py.
MAX_INT
sklearn.ensemble._forest.MAX_INT = np.iinfo(np.int32).max
Definition at line 88 of file _forest.py.