Code Cloning Analysis: matplotlib.projections.geo.LambertAxes.LambertTransform Class Reference
matplotlib.projections.geo.LambertAxes.LambertTransform Class Reference
Public Member Functions
__init__ (self, center_longitude, center_latitude, resolution)
transform_non_affine (self, values)
inverted (self)
Public Member Functions inherited from matplotlib.projections.geo._GeoTransform
__init__ (self, resolution)
__str__ (self)
transform_path_non_affine (self, path)
Public Member Functions inherited from matplotlib.transforms.Transform
__init_subclass__ (cls)
__add__ (self, other)
depth (self)
contains_branch (self, other)
contains_branch_seperately (self, other_transform)
__sub__ (self, other)
__array__ (self, *args, **kwargs)
transform (self, values)
transform_affine (self, values)
transform_bbox (self, bbox)
get_affine (self)
get_matrix (self)
transform_point (self, point)
transform_path (self, path)
transform_path_affine (self, path)
transform_angles (self, angles, pts, radians=False, pushoff=1e-5)
Public Member Functions inherited from matplotlib.transforms.TransformNode
__init__ (self, shorthand_name=None)
__str__ (self)
__getstate__ (self)
__setstate__ (self, data_dict)
__copy__ (self)
invalidate (self)
set_children (self, *children)
frozen (self)
Protected Attributes
_center_longitude = center_longitude
_center_latitude = center_latitude
Protected Attributes inherited from matplotlib.projections.geo._GeoTransform
_resolution = resolution
Protected Attributes inherited from matplotlib.transforms.TransformNode
dict _parents = {}
_invalid = self._INVALID_FULL
str _shorthand_name = shorthand_name or ''
Additional Inherited Members
Static Public Attributes inherited from matplotlib.transforms.Transform
int input_dims = None
output_dims = None
bool is_separable = False
bool has_inverse = False
Static Public Attributes inherited from matplotlib.transforms.TransformNode
bool is_affine = False
is_bbox = _api.deprecated("3.9")(_api.classproperty(lambda cls: False))
bool pass_through = False
Protected Member Functions inherited from matplotlib.transforms.Transform
_iter_break_from_left_to_right (self)
Protected Member Functions inherited from matplotlib.transforms.TransformNode
_invalidate_internal (self, level, invalidating_node)
Static Protected Attributes inherited from matplotlib.transforms.TransformNode
_VALID
_INVALID_AFFINE_ONLY
_INVALID_FULL
Detailed Description
The base Lambert transform.
Definition at line 419 of file geo.py.
Constructor & Destructor Documentation
__init__()
matplotlib.projections.geo.LambertAxes.LambertTransform.__init__ (self, center_longitude, center_latitude, resolution)
Create a new Lambert transform.  Resolution is the number of steps
to interpolate between each input line segment to approximate its
path in curved Lambert space.
Definition at line 422 of file geo.py.
References _center_latitude, and _center_longitude.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
inverted()
matplotlib.projections.geo.LambertAxes.LambertTransform.inverted (self)
Return the corresponding inverse transformation.
It holds ``x == self.inverted().transform(self.transform(x))``.
The return value of this method should be treated as
temporary.  An update to *self* does not cause a corresponding
update to its inverted copy.
Reimplemented from matplotlib.transforms.Transform.
Definition at line 451 of file geo.py.
References _center_latitude, _center_longitude, and matplotlib.projections.geo._GeoTransform._resolution.
transform_non_affine()
matplotlib.projections.geo.LambertAxes.LambertTransform.transform_non_affine (self, values)
Apply only the non-affine part of this transformation.
``transform(values)`` is always equivalent to
``transform_affine(transform_non_affine(values))``.
In non-affine transformations, this is generally equivalent to
``transform(values)``.  In affine transformations, this is
always a no-op.
Parameters
----------
values : array
    The input values as an array of length :attr:`input_dims` or
    shape (N, :attr:`input_dims`).
Returns
-------
array
    The output values as an array of length :attr:`output_dims` or
    shape (N, :attr:`output_dims`), depending on the input.
Reimplemented from matplotlib.transforms.Transform.
Definition at line 432 of file geo.py.
References _center_latitude, and _center_longitude.
Referenced by matplotlib.projections.polar.PolarTransform.__init__(), matplotlib.transforms.Transform.transform(), and matplotlib.transforms.Transform.transform_path_non_affine().
Member Data Documentation
_center_latitude
matplotlib.projections.geo.LambertAxes.LambertTransform._center_latitude = center_latitude protected
Definition at line 430 of file geo.py.
Referenced by __init__(), matplotlib.projections.geo.LambertAxes.clear(), matplotlib.projections.geo.LambertAxes.InvertedLambertTransform.inverted(), inverted(), matplotlib.projections.geo.LambertAxes.InvertedLambertTransform.transform_non_affine(), and transform_non_affine().
_center_longitude
matplotlib.projections.geo.LambertAxes.LambertTransform._center_longitude = center_longitude protected
Definition at line 429 of file geo.py.
Referenced by __init__(), matplotlib.projections.geo.LambertAxes.clear(), matplotlib.projections.geo.LambertAxes.InvertedLambertTransform.inverted(), inverted(), matplotlib.projections.geo.LambertAxes.InvertedLambertTransform.transform_non_affine(), and transform_non_affine().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/projections/geo.py