Code Cloning Analysis: scipy.signal._ltisys Namespace Reference
scipy.signal._ltisys Namespace Reference
Classes
class Bunch
class dlti
class LinearTimeInvariant
class lti
class StateSpace
class StateSpaceContinuous
class StateSpaceDiscrete
class TransferFunction
class TransferFunctionContinuous
class TransferFunctionDiscrete
class ZerosPolesGain
class ZerosPolesGainContinuous
class ZerosPolesGainDiscrete
Functions
_atleast_2d_or_none (arg)
lsim2 (system, U=None, T=None, X0=None, **kwargs)
_cast_to_array_dtype (in1, in2)
lsim (system, U, T, X0=None, interp=True)
_default_response_times (A, n)
impulse (system, X0=None, T=None, N=None)
impulse2 (system, X0=None, T=None, N=None, **kwargs)
step (system, X0=None, T=None, N=None)
step2 (system, X0=None, T=None, N=None, **kwargs)
bode (system, w=None, n=100)
freqresp (system, w=None, n=10000)
_valid_inputs (A, B, poles, method, rtol, maxiter)
_order_complex_poles (poles)
_KNV0 (B, ker_pole, transfer_matrix, j, poles)
_YT_real (ker_pole, Q, transfer_matrix, i, j)
_YT_complex (ker_pole, Q, transfer_matrix, i, j)
_YT_loop (ker_pole, transfer_matrix, poles, B, maxiter, rtol)
_KNV0_loop (ker_pole, transfer_matrix, poles, B, maxiter, rtol)
place_poles (A, B, poles, method="YT", rtol=1e-3, maxiter=30)
dlsim (system, u, t=None, x0=None)
dimpulse (system, x0=None, t=None, n=None)
dstep (system, x0=None, t=None, n=None)
dfreqresp (system, w=None, n=10000, whole=False)
dbode (system, w=None, n=100)
Variables
list __all__
Detailed Description
ltisys -- a collection of classes and functions for modeling linear
time invariant systems.
Function Documentation
_atleast_2d_or_none()
scipy.signal._ltisys._atleast_2d_or_none (arg) protected
Definition at line 1223 of file _ltisys.py.
_cast_to_array_dtype()
scipy.signal._ltisys._cast_to_array_dtype (in1, in2) protected
Cast array to dtype of other array, while avoiding ComplexWarning.
Those can be raised when casting complex to real.
Definition at line 1959 of file _ltisys.py.
_default_response_times()
scipy.signal._ltisys._default_response_times (A, n) protected
Compute a reasonable set of time samples for the response time.
This function is used by `impulse`, `impulse2`, `step` and `step2`
to compute the response time when the `T` argument to the function
is None.
Parameters
----------
A : array_like
    The system matrix, which is square.
n : int
    The number of time samples to generate.
Returns
-------
t : ndarray
    The 1-D array of length `n` of time samples at which the response
    is to be computed.
Definition at line 2188 of file _ltisys.py.
Referenced by impulse(), impulse2(), step(), and step2().
_KNV0()
scipy.signal._ltisys._KNV0 (B, ker_pole, transfer_matrix, j, poles) protected
Algorithm "KNV0" Kautsky et Al. Robust pole
assignment in linear state feedback, Int journal of Control
1985, vol 41 p 1129->1155
https://la.epfl.ch/files/content/sites/la/files/
    users/105941/public/KautskyNicholsDooren
Definition at line 2795 of file _ltisys.py.
Referenced by _KNV0_loop(), and _YT_loop().
_KNV0_loop()
scipy.signal._ltisys._KNV0_loop (ker_pole, transfer_matrix, poles, B, maxiter, rtol) protected
Loop over all poles one by one and apply KNV method 0 algorithm
Definition at line 3081 of file _ltisys.py.
References _KNV0().
_order_complex_poles()
scipy.signal._ltisys._order_complex_poles (poles) protected
Check we have complex conjugates pairs and reorder P according to YT, ie
real_poles, complex_i, conjugate complex_i, ....
The lexicographic sort on the complex poles is added to help the user to
compare sets of poles.
Definition at line 2775 of file _ltisys.py.
Referenced by _valid_inputs(), and place_poles().
_valid_inputs()
scipy.signal._ltisys._valid_inputs (A, B, poles, method, rtol, maxiter) protected
Check the poles come in complex conjugage pairs
Check shapes of A, B and poles are compatible.
Check the method chosen is compatible with provided poles
Return update method to use and ordered poles
Definition at line 2724 of file _ltisys.py.
References _order_complex_poles().
Referenced by place_poles().
_YT_complex()
scipy.signal._ltisys._YT_complex (ker_pole, Q, transfer_matrix, i, j) protected
Applies algorithm from YT section 6.2 page 20 related to complex pairs
Definition at line 2907 of file _ltisys.py.
Referenced by _YT_loop().
_YT_loop()
scipy.signal._ltisys._YT_loop (ker_pole, transfer_matrix, poles, B, maxiter, rtol) protected
Algorithm "YT" Tits, Yang. Globally Convergent
Algorithms for Robust Pole Assignment by State Feedback
https://hdl.handle.net/1903/5598
The poles P have to be sorted accordingly to section 6.2 page 20
Definition at line 2958 of file _ltisys.py.
References _KNV0(), _YT_complex(), and _YT_real().
_YT_real()
scipy.signal._ltisys._YT_real (ker_pole, Q, transfer_matrix, i, j) protected
Applies algorithm from YT section 6.1 page 19 related to real pairs
Definition at line 2842 of file _ltisys.py.
Referenced by _YT_loop().
bode()
scipy.signal._ltisys.bode (system, w = None, n = 100)
Calculate Bode magnitude and phase data of a continuous-time system.
Parameters
----------
system : an instance of the LTI class or a tuple describing the system.
    The following gives the number of elements in the tuple and
    the interpretation:
        * 1 (instance of `lti`)
        * 2 (num, den)
        * 3 (zeros, poles, gain)
        * 4 (A, B, C, D)
w : array_like, optional
    Array of frequencies (in rad/s). Magnitude and phase data is calculated
    for every value in this array. If not given a reasonable set will be
    calculated.
n : int, optional
    Number of frequency points to compute if `w` is not given. The `n`
    frequencies are logarithmically spaced in an interval chosen to
    include the influence of the poles and zeros of the system.
Returns
-------
w : 1D ndarray
    Frequency array [rad/s]
mag : 1D ndarray
    Magnitude array [dB]
phase : 1D ndarray
    Phase array [deg]
Notes
-----
If (num, den) is passed in for ``system``, coefficients for both the
numerator and denominator should be specified in descending exponent
order (e.g. ``s^2 + 3s + 5`` would be represented as ``[1, 3, 5]``).
.. versionadded:: 0.11.0
Examples
--------
>>> from scipy import signal
>>> import matplotlib.pyplot as plt
>>> sys = signal.TransferFunction([1], [1, 1])
>>> w, mag, phase = signal.bode(sys)
>>> plt.figure()
>>> plt.semilogx(w, mag)    # Bode magnitude plot
>>> plt.figure()
>>> plt.semilogx(w, phase)  # Bode phase plot
>>> plt.show()
Definition at line 2568 of file _ltisys.py.
References freqresp().
dbode()
scipy.signal._ltisys.dbode (system, w = None, n = 100)
Calculate Bode magnitude and phase data of a discrete-time system.
Parameters
----------
system : an instance of the LTI class or a tuple describing the system.
The following gives the number of elements in the tuple and
the interpretation:
    * 1 (instance of `dlti`)
    * 2 (num, den, dt)
    * 3 (zeros, poles, gain, dt)
    * 4 (A, B, C, D, dt)
w : array_like, optional
Array of frequencies (in radians/sample). Magnitude and phase data is
calculated for every value in this array. If not given a reasonable
set will be calculated.
n : int, optional
Number of frequency points to compute if `w` is not given. The `n`
frequencies are logarithmically spaced in an interval chosen to
include the influence of the poles and zeros of the system.
Returns
-------
w : 1D ndarray
Frequency array [rad/time_unit]
mag : 1D ndarray
Magnitude array [dB]
phase : 1D ndarray
Phase array [deg]
Notes
-----
If (num, den) is passed in for ``system``, coefficients for both the
numerator and denominator should be specified in descending exponent
order (e.g. ``z^2 + 3z + 5`` would be represented as ``[1, 3, 5]``).
.. versionadded:: 0.18.0
Examples
--------
>>> from scipy import signal
>>> import matplotlib.pyplot as plt
Construct the transfer function :math:`H(z) = \frac{1}{z^2 + 2z + 3}` with
a sampling time of 0.05 seconds:
>>> sys = signal.TransferFunction([1], [1, 2, 3], dt=0.05)
Equivalent: sys.bode()
>>> w, mag, phase = signal.dbode(sys)
>>> plt.figure()
>>> plt.semilogx(w, mag)    # Bode magnitude plot
>>> plt.figure()
>>> plt.semilogx(w, phase)  # Bode phase plot
>>> plt.show()
Definition at line 3848 of file _ltisys.py.
References dfreqresp().
Referenced by scipy.signal._ltisys.dlti.bode().
dfreqresp()
scipy.signal._ltisys.dfreqresp (system, w = None, n = 10000, whole = False)
Calculate the frequency response of a discrete-time system.
Parameters
----------
system : an instance of the `dlti` class or a tuple describing the system.
    The following gives the number of elements in the tuple and
    the interpretation:
        * 1 (instance of `dlti`)
        * 2 (numerator, denominator, dt)
        * 3 (zeros, poles, gain, dt)
        * 4 (A, B, C, D, dt)
w : array_like, optional
    Array of frequencies (in radians/sample). Magnitude and phase data is
    calculated for every value in this array. If not given a reasonable
    set will be calculated.
n : int, optional
    Number of frequency points to compute if `w` is not given. The `n`
    frequencies are logarithmically spaced in an interval chosen to
    include the influence of the poles and zeros of the system.
whole : bool, optional
    Normally, if 'w' is not given, frequencies are computed from 0 to the
    Nyquist frequency, pi radians/sample (upper-half of unit-circle). If
    `whole` is True, compute frequencies from 0 to 2*pi radians/sample.
Returns
-------
w : 1D ndarray
    Frequency array [radians/sample]
H : 1D ndarray
    Array of complex magnitude values
Notes
-----
If (num, den) is passed in for ``system``, coefficients for both the
numerator and denominator should be specified in descending exponent
order (e.g. ``z^2 + 3z + 5`` would be represented as ``[1, 3, 5]``).
.. versionadded:: 0.18.0
Examples
--------
Generating the Nyquist plot of a transfer function
>>> from scipy import signal
>>> import matplotlib.pyplot as plt
Construct the transfer function
:math:`H(z) = \frac{1}{z^2 + 2z + 3}` with a sampling time of 0.05
seconds:
>>> sys = signal.TransferFunction([1], [1, 2, 3], dt=0.05)
>>> w, H = signal.dfreqresp(sys)
>>> plt.figure()
>>> plt.plot(H.real, H.imag, "b")
>>> plt.plot(H.real, -H.imag, "r")
>>> plt.show()
Definition at line 3748 of file _ltisys.py.
References scipy.signal._filter_design.freqz(), and scipy.signal._filter_design.freqz_zpk().
Referenced by dbode(), and scipy.signal._ltisys.dlti.freqresp().
dimpulse()
scipy.signal._ltisys.dimpulse (system, x0 = None, t = None, n = None)
Impulse response of discrete-time system.
Parameters
----------
system : tuple of array_like or instance of `dlti`
    A tuple describing the system.
    The following gives the number of elements in the tuple and
    the interpretation:
        * 1: (instance of `dlti`)
        * 3: (num, den, dt)
        * 4: (zeros, poles, gain, dt)
        * 5: (A, B, C, D, dt)
x0 : array_like, optional
    Initial state-vector.  Defaults to zero.
t : array_like, optional
    Time points.  Computed if not given.
n : int, optional
    The number of time points to compute (if `t` is not given).
Returns
-------
tout : ndarray
    Time values for the output, as a 1-D array.
yout : tuple of ndarray
    Impulse response of system.  Each element of the tuple represents
    the output of the system based on an impulse in each input.
See Also
--------
impulse, dstep, dlsim, cont2discrete
Examples
--------
>>> import numpy as np
>>> from scipy import signal
>>> import matplotlib.pyplot as plt
>>> butter = signal.dlti(*signal.butter(3, 0.5))
>>> t, y = signal.dimpulse(butter, n=25)
>>> plt.step(t, np.squeeze(y))
>>> plt.grid()
>>> plt.xlabel('n [samples]')
>>> plt.ylabel('Amplitude')
Definition at line 3575 of file _ltisys.py.
References dlsim().
Referenced by scipy.signal._ltisys.dlti.impulse().
dlsim()
scipy.signal._ltisys.dlsim (system, u, t = None, x0 = None)
Simulate output of a discrete-time linear system.
Parameters
----------
system : tuple of array_like or instance of `dlti`
    A tuple describing the system.
    The following gives the number of elements in the tuple and
    the interpretation:
        * 1: (instance of `dlti`)
        * 3: (num, den, dt)
        * 4: (zeros, poles, gain, dt)
        * 5: (A, B, C, D, dt)
u : array_like
    An input array describing the input at each time `t` (interpolation is
    assumed between given times).  If there are multiple inputs, then each
    column of the rank-2 array represents an input.
t : array_like, optional
    The time steps at which the input is defined.  If `t` is given, it
    must be the same length as `u`, and the final value in `t` determines
    the number of steps returned in the output.
x0 : array_like, optional
    The initial conditions on the state vector (zero by default).
Returns
-------
tout : ndarray
    Time values for the output, as a 1-D array.
yout : ndarray
    System response, as a 1-D array.
xout : ndarray, optional
    Time-evolution of the state-vector.  Only generated if the input is a
    `StateSpace` system.
See Also
--------
lsim, dstep, dimpulse, cont2discrete
Examples
--------
A simple integrator transfer function with a discrete time step of 1.0
could be implemented as:
>>> import numpy as np
>>> from scipy import signal
>>> tf = ([1.0,], [1.0, -1.0], 1.0)
>>> t_in = [0.0, 1.0, 2.0, 3.0]
>>> u = np.asarray([0.0, 0.0, 1.0, 1.0])
>>> t_out, y = signal.dlsim(tf, u, t=t_in)
>>> y.T
array([[ 0.,  0.,  0.,  1.]])
Definition at line 3458 of file _ltisys.py.
Referenced by dimpulse(), dstep(), scipy.signal._ltisys.dlti.output(), and scipy.signal.tests.test_cont2discrete.TestC2D.test_discrete_approx().
dstep()
scipy.signal._ltisys.dstep (system, x0 = None, t = None, n = None)
Step response of discrete-time system.
Parameters
----------
system : tuple of array_like
    A tuple describing the system.
    The following gives the number of elements in the tuple and
    the interpretation:
        * 1: (instance of `dlti`)
        * 3: (num, den, dt)
        * 4: (zeros, poles, gain, dt)
        * 5: (A, B, C, D, dt)
x0 : array_like, optional
    Initial state-vector.  Defaults to zero.
t : array_like, optional
    Time points.  Computed if not given.
n : int, optional
    The number of time points to compute (if `t` is not given).
Returns
-------
tout : ndarray
    Output time points, as a 1-D array.
yout : tuple of ndarray
    Step response of system.  Each element of the tuple represents
    the output of the system based on a step response to each input.
See Also
--------
step, dimpulse, dlsim, cont2discrete
Examples
--------
>>> import numpy as np
>>> from scipy import signal
>>> import matplotlib.pyplot as plt
>>> butter = signal.dlti(*signal.butter(3, 0.5))
>>> t, y = signal.dstep(butter, n=25)
>>> plt.step(t, np.squeeze(y))
>>> plt.grid()
>>> plt.xlabel('n [samples]')
>>> plt.ylabel('Amplitude')
Definition at line 3662 of file _ltisys.py.
References dlsim().
Referenced by scipy.signal._ltisys.dlti.step().
freqresp()
scipy.signal._ltisys.freqresp (system, w = None, n = 10000)
Calculate the frequency response of a continuous-time system.
Parameters
----------
system : an instance of the `lti` class or a tuple describing the system.
    The following gives the number of elements in the tuple and
    the interpretation:
        * 1 (instance of `lti`)
        * 2 (num, den)
        * 3 (zeros, poles, gain)
        * 4 (A, B, C, D)
w : array_like, optional
    Array of frequencies (in rad/s). Magnitude and phase data is
    calculated for every value in this array. If not given, a reasonable
    set will be calculated.
n : int, optional
    Number of frequency points to compute if `w` is not given. The `n`
    frequencies are logarithmically spaced in an interval chosen to
    include the influence of the poles and zeros of the system.
Returns
-------
w : 1D ndarray
    Frequency array [rad/s]
H : 1D ndarray
    Array of complex magnitude values
Notes
-----
If (num, den) is passed in for ``system``, coefficients for both the
numerator and denominator should be specified in descending exponent
order (e.g. ``s^2 + 3s + 5`` would be represented as ``[1, 3, 5]``).
Examples
--------
Generating the Nyquist plot of a transfer function
>>> from scipy import signal
>>> import matplotlib.pyplot as plt
Construct the transfer function :math:`H(s) = \frac{5}{(s-1)^3}`:
>>> s1 = signal.ZerosPolesGain([], [1, 1, 1], [5])
>>> w, H = signal.freqresp(s1)
>>> plt.figure()
>>> plt.plot(H.real, H.imag, "b")
>>> plt.plot(H.real, -H.imag, "r")
>>> plt.show()
Definition at line 2632 of file _ltisys.py.
References scipy.signal._filter_design.freqs(), and scipy.signal._filter_design.freqs_zpk().
Referenced by bode().
impulse()
scipy.signal._ltisys.impulse (system, X0 = None, T = None, N = None)
Impulse response of continuous-time system.
Parameters
----------
system : an instance of the LTI class or a tuple of array_like
    describing the system.
    The following gives the number of elements in the tuple and
    the interpretation:
        * 1 (instance of `lti`)
        * 2 (num, den)
        * 3 (zeros, poles, gain)
        * 4 (A, B, C, D)
X0 : array_like, optional
    Initial state-vector.  Defaults to zero.
T : array_like, optional
    Time points.  Computed if not given.
N : int, optional
    The number of time points to compute (if `T` is not given).
Returns
-------
T : ndarray
    A 1-D array of time points.
yout : ndarray
    A 1-D array containing the impulse response of the system (except for
    singularities at zero).
Notes
-----
If (num, den) is passed in for ``system``, coefficients for both the
numerator and denominator should be specified in descending exponent
order (e.g. ``s^2 + 3s + 5`` would be represented as ``[1, 3, 5]``).
Examples
--------
Compute the impulse response of a second order system with a repeated
root: ``x''(t) + 2*x'(t) + x(t) = u(t)``
>>> from scipy import signal
>>> system = ([1.0], [1.0, 2.0, 1.0])
>>> t, y = signal.impulse(system)
>>> import matplotlib.pyplot as plt
>>> plt.plot(t, y)
Definition at line 2220 of file _ltisys.py.
References _default_response_times(), and lsim().
impulse2()
scipy.signal._ltisys.impulse2 (system, X0 = None, T = None, N = None, ** kwargs)
Impulse response of a single-input, continuous-time linear system.
.. deprecated:: 1.11.0
    Function `impulse2` is deprecated in favor of the faster `impulse`
    function. `impulse2` will be removed in SciPy 1.13.
Parameters
----------
system : an instance of the LTI class or a tuple of array_like
    describing the system.
    The following gives the number of elements in the tuple and
    the interpretation:
        * 1 (instance of `lti`)
        * 2 (num, den)
        * 3 (zeros, poles, gain)
        * 4 (A, B, C, D)
X0 : 1-D array_like, optional
    The initial condition of the state vector.  Default: 0 (the
    zero vector).
T : 1-D array_like, optional
    The time steps at which the input is defined and at which the
    output is desired.  If `T` is not given, the function will
    generate a set of time samples automatically.
N : int, optional
    Number of time points to compute.  Default: 100.
kwargs : various types
    Additional keyword arguments are passed on to the function
    `scipy.signal.lsim2`, which in turn passes them on to
    `scipy.integrate.odeint`; see the latter's documentation for
    information about these arguments.
Returns
-------
T : ndarray
    The time values for the output.
yout : ndarray
    The output response of the system.
See Also
--------
impulse, lsim2, scipy.integrate.odeint
Notes
-----
The solution is generated by calling `scipy.signal.lsim2`, which uses
the differential equation solver `scipy.integrate.odeint`.
As `impulse2` is now deprecated, users are advised to switch to the faster
and more accurate `impulse` function. Keyword arguments for
`scipy.integrate.odeint` are not supported in `impulse`, but not needed in
general.
If (num, den) is passed in for ``system``, coefficients for both the
numerator and denominator should be specified in descending exponent
order (e.g. ``s^2 + 3s + 5`` would be represented as ``[1, 3, 5]``).
.. versionadded:: 0.8.0
Examples
--------
Compute the impulse response of a second order system with a repeated
root: ``x''(t) + 2*x'(t) + x(t) = u(t)``
>>> from scipy import signal
>>> system = ([1.0], [1.0, 2.0, 1.0])
>>> t, y = signal.impulse2(system)
>>> import matplotlib.pyplot as plt
>>> plt.plot(t, y)
Definition at line 2290 of file _ltisys.py.
References _default_response_times(), and lsim2().
lsim()
scipy.signal._ltisys.lsim (system, U, T, X0 = None, interp = True)
Simulate output of a continuous-time linear system.
Parameters
----------
system : an instance of the LTI class or a tuple describing the system.
    The following gives the number of elements in the tuple and
    the interpretation:
    * 1: (instance of `lti`)
    * 2: (num, den)
    * 3: (zeros, poles, gain)
    * 4: (A, B, C, D)
U : array_like
    An input array describing the input at each time `T`
    (interpolation is assumed between given times).  If there are
    multiple inputs, then each column of the rank-2 array
    represents an input.  If U = 0 or None, a zero input is used.
T : array_like
    The time steps at which the input is defined and at which the
    output is desired.  Must be nonnegative, increasing, and equally spaced.
X0 : array_like, optional
    The initial conditions on the state vector (zero by default).
interp : bool, optional
    Whether to use linear (True, the default) or zero-order-hold (False)
    interpolation for the input array.
Returns
-------
T : 1D ndarray
    Time values for the output.
yout : 1D ndarray
    System response.
xout : ndarray
    Time evolution of the state vector.
Notes
-----
If (num, den) is passed in for ``system``, coefficients for both the
numerator and denominator should be specified in descending exponent
order (e.g. ``s^2 + 3s + 5`` would be represented as ``[1, 3, 5]``).
Examples
--------
We'll use `lsim` to simulate an analog Bessel filter applied to
a signal.
>>> import numpy as np
>>> from scipy.signal import bessel, lsim
>>> import matplotlib.pyplot as plt
Create a low-pass Bessel filter with a cutoff of 12 Hz.
>>> b, a = bessel(N=5, Wn=2*np.pi*12, btype='lowpass', analog=True)
Generate data to which the filter is applied.
>>> t = np.linspace(0, 1.25, 500, endpoint=False)
The input signal is the sum of three sinusoidal curves, with
frequencies 4 Hz, 40 Hz, and 80 Hz.  The filter should mostly
eliminate the 40 Hz and 80 Hz components, leaving just the 4 Hz signal.
>>> u = (np.cos(2*np.pi*4*t) + 0.6*np.sin(2*np.pi*40*t) +
...      0.5*np.cos(2*np.pi*80*t))
Simulate the filter with `lsim`.
>>> tout, yout, xout = lsim((b, a), U=u, T=t)
Plot the result.
>>> plt.plot(t, u, 'r', alpha=0.5, linewidth=1, label='input')
>>> plt.plot(tout, yout, 'k', linewidth=1.5, label='output')
>>> plt.legend(loc='best', shadow=True, framealpha=1)
>>> plt.grid(alpha=0.3)
>>> plt.xlabel('t')
>>> plt.show()
In a second example, we simulate a double integrator ``y'' = u``, with
a constant input ``u = 1``.  We'll use the state space representation
of the integrator.
>>> from scipy.signal import lti
>>> A = np.array([[0.0, 1.0], [0.0, 0.0]])
>>> B = np.array([[0.0], [1.0]])
>>> C = np.array([[1.0, 0.0]])
>>> D = 0.0
>>> system = lti(A, B, C, D)
`t` and `u` define the time and input signal for the system to
be simulated.
>>> t = np.linspace(0, 5, num=50)
>>> u = np.ones_like(t)
Compute the simulation, and then plot `y`.  As expected, the plot shows
the curve ``y = 0.5*t**2``.
>>> tout, y, x = lsim(system, u, t)
>>> plt.plot(t, y)
>>> plt.grid(alpha=0.3)
>>> plt.xlabel('t')
>>> plt.show()
Definition at line 1973 of file _ltisys.py.
Referenced by impulse(), scipy.signal._ltisys.lti.output(), step(), and scipy.signal.tests.test_cont2discrete.TestC2D.test_discrete_approx().
lsim2()
scipy.signal._ltisys.lsim2 (system, U = None, T = None, X0 = None, ** kwargs)
Simulate output of a continuous-time linear system, by using
the ODE solver `scipy.integrate.odeint`.
.. deprecated:: 1.11.0
    Function `lsim2` is deprecated in favor of the faster `lsim` function.
    `lsim2` will be removed in SciPy 1.13.
Parameters
----------
system : an instance of the `lti` class or a tuple describing the system.
    The following gives the number of elements in the tuple and
    the interpretation:
    * 1: (instance of `lti`)
    * 2: (num, den)
    * 3: (zeros, poles, gain)
    * 4: (A, B, C, D)
U : array_like (1D or 2D), optional
    An input array describing the input at each time T.  Linear
    interpolation is used between given times.  If there are
    multiple inputs, then each column of the rank-2 array
    represents an input.  If U is not given, the input is assumed
    to be zero.
T : array_like (1D or 2D), optional
    The time steps at which the input is defined and at which the
    output is desired.  The default is 101 evenly spaced points on
    the interval [0,10.0].
X0 : array_like (1D), optional
    The initial condition of the state vector.  If `X0` is not
    given, the initial conditions are assumed to be 0.
kwargs : dict
    Additional keyword arguments are passed on to the function
    `odeint`.  See the notes below for more details.
Returns
-------
T : 1D ndarray
    The time values for the output.
yout : ndarray
    The response of the system.
xout : ndarray
    The time-evolution of the state-vector.
See Also
--------
lsim
Notes
-----
This function uses `scipy.integrate.odeint` to solve the system's
differential equations.  Additional keyword arguments given to `lsim2`
are passed on to `scipy.integrate.odeint`.  See the documentation
for `scipy.integrate.odeint` for the full list of arguments.
As `lsim2` is now deprecated, users are advised to switch to the faster
and more accurate `lsim` function. Keyword arguments for
`scipy.integrate.odeint` are not supported in `lsim`, but not needed in
general.
If (num, den) is passed in for ``system``, coefficients for both the
numerator and denominator should be specified in descending exponent
order (e.g. ``s^2 + 3s + 5`` would be represented as ``[1, 3, 5]``).
Examples
--------
We'll use `lsim2` to simulate an analog Bessel filter applied to
a signal.
>>> import numpy as np
>>> from scipy.signal import bessel, lsim2
>>> import matplotlib.pyplot as plt
Create a low-pass Bessel filter with a cutoff of 12 Hz.
>>> b, a = bessel(N=5, Wn=2*np.pi*12, btype='lowpass', analog=True)
Generate data to which the filter is applied.
>>> t = np.linspace(0, 1.25, 500, endpoint=False)
The input signal is the sum of three sinusoidal curves, with
frequencies 4 Hz, 40 Hz, and 80 Hz.  The filter should mostly
eliminate the 40 Hz and 80 Hz components, leaving just the 4 Hz signal.
>>> u = (np.cos(2*np.pi*4*t) + 0.6*np.sin(2*np.pi*40*t) +
...      0.5*np.cos(2*np.pi*80*t))
Simulate the filter with `lsim2`.
>>> tout, yout, xout = lsim2((b, a), U=u, T=t)
Plot the result.
>>> plt.plot(t, u, 'r', alpha=0.5, linewidth=1, label='input')
>>> plt.plot(tout, yout, 'k', linewidth=1.5, label='output')
>>> plt.legend(loc='best', shadow=True, framealpha=1)
>>> plt.grid(alpha=0.3)
>>> plt.xlabel('t')
>>> plt.show()
In a second example, we simulate a double integrator ``y'' = u``, with
a constant input ``u = 1``.  We'll use the state space representation
of the integrator.
>>> from scipy.signal import lti
>>> A = np.array([[0, 1], [0, 0]])
>>> B = np.array([[0], [1]])
>>> C = np.array([[1, 0]])
>>> D = 0
>>> system = lti(A, B, C, D)
`t` and `u` define the time and input signal for the system to
be simulated.
>>> t = np.linspace(0, 5, num=50)
>>> u = np.ones_like(t)
Compute the simulation, and then plot `y`.  As expected, the plot shows
the curve ``y = 0.5*t**2``.
>>> tout, y, x = lsim2(system, u, t)
>>> plt.plot(t, y)
>>> plt.grid(alpha=0.3)
>>> plt.xlabel('t')
>>> plt.show()
Definition at line 1768 of file _ltisys.py.
Referenced by impulse2(), and step2().
place_poles()
scipy.signal._ltisys.place_poles (A, B, poles, method = "YT", rtol = 1e-3, maxiter = 30)
Compute K such that eigenvalues (A - dot(B, K))=poles.
K is the gain matrix such as the plant described by the linear system
``AX+BU`` will have its closed-loop poles, i.e the eigenvalues ``A - B*K``,
as close as possible to those asked for in poles.
SISO, MISO and MIMO systems are supported.
Parameters
----------
A, B : ndarray
    State-space representation of linear system ``AX + BU``.
poles : array_like
    Desired real poles and/or complex conjugates poles.
    Complex poles are only supported with ``method="YT"`` (default).
method: {'YT', 'KNV0'}, optional
    Which method to choose to find the gain matrix K. One of:
        - 'YT': Yang Tits
        - 'KNV0': Kautsky, Nichols, Van Dooren update method 0
    See References and Notes for details on the algorithms.
rtol: float, optional
    After each iteration the determinant of the eigenvectors of
    ``A - B*K`` is compared to its previous value, when the relative
    error between these two values becomes lower than `rtol` the algorithm
    stops.  Default is 1e-3.
maxiter: int, optional
    Maximum number of iterations to compute the gain matrix.
    Default is 30.
Returns
-------
full_state_feedback : Bunch object
    full_state_feedback is composed of:
        gain_matrix : 1-D ndarray
            The closed loop matrix K such as the eigenvalues of ``A-BK``
            are as close as possible to the requested poles.
        computed_poles : 1-D ndarray
            The poles corresponding to ``A-BK`` sorted as first the real
            poles in increasing order, then the complex congugates in
            lexicographic order.
        requested_poles : 1-D ndarray
            The poles the algorithm was asked to place sorted as above,
            they may differ from what was achieved.
        X : 2-D ndarray
            The transfer matrix such as ``X * diag(poles) = (A - B*K)*X``
            (see Notes)
        rtol : float
            The relative tolerance achieved on ``det(X)`` (see Notes).
            `rtol` will be NaN if it is possible to solve the system
            ``diag(poles) = (A - B*K)``, or 0 when the optimization
            algorithms can't do anything i.e when ``B.shape[1] == 1``.
        nb_iter : int
            The number of iterations performed before converging.
            `nb_iter` will be NaN if it is possible to solve the system
            ``diag(poles) = (A - B*K)``, or 0 when the optimization
            algorithms can't do anything i.e when ``B.shape[1] == 1``.
Notes
-----
The Tits and Yang (YT), [2]_ paper is an update of the original Kautsky et
al. (KNV) paper [1]_.  KNV relies on rank-1 updates to find the transfer
matrix X such that ``X * diag(poles) = (A - B*K)*X``, whereas YT uses
rank-2 updates. This yields on average more robust solutions (see [2]_
pp 21-22), furthermore the YT algorithm supports complex poles whereas KNV
does not in its original version.  Only update method 0 proposed by KNV has
been implemented here, hence the name ``'KNV0'``.
KNV extended to complex poles is used in Matlab's ``place`` function, YT is
distributed under a non-free licence by Slicot under the name ``robpole``.
It is unclear and undocumented how KNV0 has been extended to complex poles
(Tits and Yang claim on page 14 of their paper that their method can not be
used to extend KNV to complex poles), therefore only YT supports them in
this implementation.
As the solution to the problem of pole placement is not unique for MIMO
systems, both methods start with a tentative transfer matrix which is
altered in various way to increase its determinant.  Both methods have been
proven to converge to a stable solution, however depending on the way the
initial transfer matrix is chosen they will converge to different
solutions and therefore there is absolutely no guarantee that using
``'KNV0'`` will yield results similar to Matlab's or any other
implementation of these algorithms.
Using the default method ``'YT'`` should be fine in most cases; ``'KNV0'``
is only provided because it is needed by ``'YT'`` in some specific cases.
Furthermore ``'YT'`` gives on average more robust results than ``'KNV0'``
when ``abs(det(X))`` is used as a robustness indicator.
[2]_ is available as a technical report on the following URL:
https://hdl.handle.net/1903/5598
References
----------
.. [1] J. Kautsky, N.K. Nichols and P. van Dooren, "Robust pole assignment
       in linear state feedback", International Journal of Control, Vol. 41
       pp. 1129-1155, 1985.
.. [2] A.L. Tits and Y. Yang, "Globally convergent algorithms for robust
       pole assignment by state feedback", IEEE Transactions on Automatic
       Control, Vol. 41, pp. 1432-1452, 1996.
Examples
--------
A simple example demonstrating real pole placement using both KNV and YT
algorithms.  This is example number 1 from section 4 of the reference KNV
publication ([1]_):
>>> import numpy as np
>>> from scipy import signal
>>> import matplotlib.pyplot as plt
>>> A = np.array([[ 1.380,  -0.2077,  6.715, -5.676  ],
...               [-0.5814, -4.290,   0,      0.6750 ],
...               [ 1.067,   4.273,  -6.654,  5.893  ],
...               [ 0.0480,  4.273,   1.343, -2.104  ]])
>>> B = np.array([[ 0,      5.679 ],
...               [ 1.136,  1.136 ],
...               [ 0,      0,    ],
...               [-3.146,  0     ]])
>>> P = np.array([-0.2, -0.5, -5.0566, -8.6659])
Now compute K with KNV method 0, with the default YT method and with the YT
method while forcing 100 iterations of the algorithm and print some results
after each call.
>>> fsf1 = signal.place_poles(A, B, P, method='KNV0')
>>> fsf1.gain_matrix
array([[ 0.20071427, -0.96665799,  0.24066128, -0.10279785],
       [ 0.50587268,  0.57779091,  0.51795763, -0.41991442]])
>>> fsf2 = signal.place_poles(A, B, P)  # uses YT method
>>> fsf2.computed_poles
array([-8.6659, -5.0566, -0.5   , -0.2   ])
>>> fsf3 = signal.place_poles(A, B, P, rtol=-1, maxiter=100)
>>> fsf3.X
array([[ 0.52072442+0.j, -0.08409372+0.j, -0.56847937+0.j,  0.74823657+0.j],
       [-0.04977751+0.j, -0.80872954+0.j,  0.13566234+0.j, -0.29322906+0.j],
       [-0.82266932+0.j, -0.19168026+0.j, -0.56348322+0.j, -0.43815060+0.j],
       [ 0.22267347+0.j,  0.54967577+0.j, -0.58387806+0.j, -0.40271926+0.j]])
The absolute value of the determinant of X is a good indicator to check the
robustness of the results, both ``'KNV0'`` and ``'YT'`` aim at maximizing
it.  Below a comparison of the robustness of the results above:
>>> abs(np.linalg.det(fsf1.X)) < abs(np.linalg.det(fsf2.X))
True
>>> abs(np.linalg.det(fsf2.X)) < abs(np.linalg.det(fsf3.X))
True
Now a simple example for complex poles:
>>> A = np.array([[ 0,  7/3.,  0,   0   ],
...               [ 0,   0,    0,  7/9. ],
...               [ 0,   0,    0,   0   ],
...               [ 0,   0,    0,   0   ]])
>>> B = np.array([[ 0,  0 ],
...               [ 0,  0 ],
...               [ 1,  0 ],
...               [ 0,  1 ]])
>>> P = np.array([-3, -1, -2-1j, -2+1j]) / 3.
>>> fsf = signal.place_poles(A, B, P, method='YT')
We can plot the desired and computed poles in the complex plane:
>>> t = np.linspace(0, 2*np.pi, 401)
>>> plt.plot(np.cos(t), np.sin(t), 'k--')  # unit circle
>>> plt.plot(fsf.requested_poles.real, fsf.requested_poles.imag,
...          'wo', label='Desired')
>>> plt.plot(fsf.computed_poles.real, fsf.computed_poles.imag, 'bx',
...          label='Placed')
>>> plt.grid()
>>> plt.axis('image')
>>> plt.axis([-1.1, 1.1, -1.1, 1.1])
>>> plt.legend(bbox_to_anchor=(1.05, 1), loc=2, numpoints=1)
Definition at line 3107 of file _ltisys.py.
References _order_complex_poles(), and _valid_inputs().
Referenced by scipy.signal.tests.test_ltisys.TestPlacePoles._check().
step()
scipy.signal._ltisys.step (system, X0 = None, T = None, N = None)
Step response of continuous-time system.
Parameters
----------
system : an instance of the LTI class or a tuple of array_like
    describing the system.
    The following gives the number of elements in the tuple and
    the interpretation:
        * 1 (instance of `lti`)
        * 2 (num, den)
        * 3 (zeros, poles, gain)
        * 4 (A, B, C, D)
X0 : array_like, optional
    Initial state-vector (default is zero).
T : array_like, optional
    Time points (computed if not given).
N : int, optional
    Number of time points to compute if `T` is not given.
Returns
-------
T : 1D ndarray
    Output time points.
yout : 1D ndarray
    Step response of system.
Notes
-----
If (num, den) is passed in for ``system``, coefficients for both the
numerator and denominator should be specified in descending exponent
order (e.g. ``s^2 + 3s + 5`` would be represented as ``[1, 3, 5]``).
Examples
--------
>>> from scipy import signal
>>> import matplotlib.pyplot as plt
>>> lti = signal.lti([1.0], [1.0, 1.0])
>>> t, y = signal.step(lti)
>>> plt.plot(t, y)
>>> plt.xlabel('Time [s]')
>>> plt.ylabel('Amplitude')
>>> plt.title('Step response for 1. Order Lowpass')
>>> plt.grid()
Definition at line 2400 of file _ltisys.py.
References _default_response_times(), and lsim().
step2()
scipy.signal._ltisys.step2 (system, X0 = None, T = None, N = None, ** kwargs)
Step response of continuous-time system.
This function is functionally the same as `scipy.signal.step`, but
it uses the function `scipy.signal.lsim2` to compute the step
response.
.. deprecated:: 1.11.0
    Function `step2` is deprecated in favor of the faster `step` function.
    `step2` will be removed in SciPy 1.13.
Parameters
----------
system : an instance of the LTI class or a tuple of array_like
    describing the system.
    The following gives the number of elements in the tuple and
    the interpretation:
        * 1 (instance of `lti`)
        * 2 (num, den)
        * 3 (zeros, poles, gain)
        * 4 (A, B, C, D)
X0 : array_like, optional
    Initial state-vector (default is zero).
T : array_like, optional
    Time points (computed if not given).
N : int, optional
    Number of time points to compute if `T` is not given.
kwargs : various types
    Additional keyword arguments are passed on the function
    `scipy.signal.lsim2`, which in turn passes them on to
    `scipy.integrate.odeint`.  See the documentation for
    `scipy.integrate.odeint` for information about these arguments.
Returns
-------
T : 1D ndarray
    Output time points.
yout : 1D ndarray
    Step response of system.
See Also
--------
scipy.signal.step
Notes
-----
As `step2` is now deprecated, users are advised to switch to the faster
and more accurate `step` function. Keyword arguments for
`scipy.integrate.odeint` are not supported in `step`, but not needed in
general.
If (num, den) is passed in for ``system``, coefficients for both the
numerator and denominator should be specified in descending exponent
order (e.g. ``s^2 + 3s + 5`` would be represented as ``[1, 3, 5]``).
.. versionadded:: 0.8.0
Examples
--------
>>> from scipy import signal
>>> import matplotlib.pyplot as plt
>>> lti = signal.lti([1.0], [1.0, 1.0])
>>> t, y = signal.step2(lti)
>>> plt.plot(t, y)
>>> plt.xlabel('Time [s]')
>>> plt.ylabel('Amplitude')
>>> plt.title('Step response for 1. Order Lowpass')
>>> plt.grid()
Definition at line 2467 of file _ltisys.py.
References _default_response_times(), and lsim2().
Variable Documentation
__all__
list scipy.signal._ltisys.__all__ private
Initial value:
=  ['lti', 'dlti', 'TransferFunction', 'ZerosPolesGain', 'StateSpace',
           'lsim', 'lsim2', 'impulse', 'impulse2', 'step', 'step2', 'bode',
           'freqresp', 'place_poles', 'dlsim', 'dstep', 'dimpulse',
           'dfreqresp', 'dbode']
Definition at line 42 of file _ltisys.py.