Code Cloning Analysis: pandas.io.pytables Namespace Reference
pandas.io.pytables Namespace Reference
Classes
class AppendableFrameTable
class AppendableMultiFrameTable
class AppendableMultiSeriesTable
class AppendableSeriesTable
class AppendableTable
class BlockManagerFixed
class DataCol
class DataIndexableCol
class Fixed
class FrameFixed
class GenericDataIndexableCol
class GenericFixed
class GenericIndexCol
class GenericTable
class HDFStore
class IndexCol
class Selection
class SeriesFixed
class Table
class TableIterator
class WORMTable
Functions
_ensure_decoded (s)
str _ensure_encoding (str|None encoding)
_ensure_str (name)
_ensure_term (where, int scope_level)
_tables ()
None to_hdf (FilePath|HDFStore path_or_buf, str key, DataFrame|Series value, str mode="a", int|None complevel=None, str|None complib=None, bool append=False, str|None format=None, bool index=True, int|dict[str, int]|None min_itemsize=None, nan_rep=None, bool|None dropna=None, Literal[True]|list[str]|None data_columns=None, str errors="strict", str encoding="UTF-8")
read_hdf (FilePath|HDFStore path_or_buf, key=None, str mode="r", str errors="strict", str|list|None where=None, int|None start=None, int|None stop=None, list[str]|None columns=None, bool iterator=False, int|None chunksize=None, **kwargs)
bool _is_metadata_of (Node group, Node parent_group)
DataFrame _reindex_axis (DataFrame obj, AxisInt axis, Index labels, other=None)
str|tzinfo _get_tz (tzinfo tz)
DatetimeIndex _set_tz (np.ndarray|Index values, str|tzinfo tz, bool coerce=False)
np.ndarray _set_tz (np.ndarray|Index values, None tz, bool coerce=False)
np.ndarray|DatetimeIndex _set_tz (np.ndarray|Index values, str|tzinfo|None tz, bool coerce=False)
IndexCol _convert_index (str name, Index index, str encoding, str errors)
np.ndarray|Index _unconvert_index (data, str kind, str encoding, str errors)
_maybe_convert_for_string_atom (str name, ArrayLike bvalues, existing_col, min_itemsize, nan_rep, encoding, errors, list[str] columns)
np.ndarray _convert_string_array (np.ndarray data, str encoding, str errors)
np.ndarray _unconvert_string_array (np.ndarray data, nan_rep, str encoding, str errors)
_maybe_convert (np.ndarray values, str val_kind, str encoding, str errors)
_get_converter (str kind, str encoding, str errors)
bool _need_convert (str kind)
str _maybe_adjust_name (str name, Sequence[int] version)
str _dtype_to_kind (str dtype_str)
_get_data_and_dtype_name (ArrayLike data)
Variables
str _version = "0.15.2"
str _default_encoding = "UTF-8"
Term = PyTablesExpr
Final incompatibility_doc
Final attribute_conflict_doc
Final performance_doc
dict _FORMAT_MAP = {"f": "fixed", "fixed": "fixed", "t": "table", "table": "table"}
dict _AXES_MAP = {DataFrame: [0]}
Final dropna_doc
Final format_doc
False
validator
_table_mod = None
bool _table_file_open_policy_is_strict = False
Detailed Description
High level interface to PyTables for reading and writing pandas data structures
to disk
Function Documentation
_convert_index()
IndexCol pandas.io.pytables._convert_index (str name, Index index, str encoding, str errors) protected
Definition at line 5061 of file pytables.py.
_convert_string_array()
np.ndarray pandas.io.pytables._convert_string_array (np.ndarray data, str encoding, str errors) protected
Take a string-like that is object dtype and coerce to a fixed size string type.
Parameters
----------
data : np.ndarray[object]
encoding : str
errors : str
    Handler for encoding errors.
Returns
-------
np.ndarray[fixed-length-string]
Definition at line 5233 of file pytables.py.
Referenced by _set_tz().
_dtype_to_kind()
str pandas.io.pytables._dtype_to_kind (str dtype_str) protected
Find the "kind" string describing the given dtype name.
Definition at line 5358 of file pytables.py.
References _ensure_decoded().
Referenced by pandas.io.pytables.DataCol.__eq__(), pandas.io.pytables.Table._create_axes(), _set_tz(), pandas.io.pytables.DataCol.convert(), and pandas.io.pytables.Table.indexables().
_ensure_decoded()
pandas.io.pytables._ensure_decoded (s) protected
if we have bytes, decode them to unicode
Definition at line 146 of file pytables.py.
Referenced by pandas.io.pytables.HDFStore._create_storer(), _dtype_to_kind(), _set_tz(), pandas.io.pytables.DataCol.convert(), pandas.io.pytables.IndexCol.convert(), pandas.io.pytables.GenericFixed.get_attrs(), pandas.io.pytables.Table.get_attrs(), pandas.io.pytables.IndexCol.maybe_set_size(), pandas.io.pytables.GenericFixed.read_array(), pandas.io.pytables.IndexCol.validate_col(), and pandas.io.pytables.Fixed.version().
_ensure_encoding()
str pandas.io.pytables._ensure_encoding (str | None encoding) protected
Definition at line 153 of file pytables.py.
_ensure_str()
pandas.io.pytables._ensure_str (name) protected
Ensure that an index / column name is a str (python 3); otherwise they
may be np.string dtype. Non-string dtypes are passed through unchanged.
https://github.com/pandas-dev/pandas/issues/13492
Definition at line 161 of file pytables.py.
Referenced by pandas.io.pytables.GenericFixed.read_array().
_ensure_term()
pandas.io.pytables._ensure_term (where, int scope_level) protected
Ensure that the where is a Term or a list of Term.
This makes sure that we are capturing the scope of variables that are
passed create the terms here with a frame_level=2 (we are 2 levels down)
Definition at line 176 of file pytables.py.
Referenced by read_hdf(), pandas.io.pytables.HDFStore.remove(), pandas.io.pytables.HDFStore.select(), pandas.io.pytables.HDFStore.select_as_coordinates(), and pandas.io.pytables.HDFStore.select_as_multiple().
_get_converter()
pandas.io.pytables._get_converter (str kind, str encoding, str errors) protected
Definition at line 5314 of file pytables.py.
_get_data_and_dtype_name()
pandas.io.pytables._get_data_and_dtype_name (ArrayLike data) protected
Convert the passed data into a storable form and a dtype string.
Definition at line 5393 of file pytables.py.
Referenced by pandas.io.pytables.DataCol.__eq__(), pandas.io.pytables.Table._create_axes(), _set_tz(), and pandas.io.pytables.DataCol.convert().
_get_tz()
str | tzinfo pandas.io.pytables._get_tz (tzinfo tz) protected
for a tz-aware type, return an encoded zone
Definition at line 5004 of file pytables.py.
Referenced by pandas.io.pytables.Table._create_axes(), pandas.io.pytables.GenericFixed.read_array(), and pandas.io.pytables.GenericFixed.write_array_empty().
_is_metadata_of()
bool pandas.io.pytables._is_metadata_of (Node group, Node parent_group) protected
Check if a given group is a metadata group for a given parent_group.
Definition at line 484 of file pytables.py.
Referenced by read_hdf().
_maybe_adjust_name()
str pandas.io.pytables._maybe_adjust_name (str name, Sequence[int] version) protected
Prior to 0.10.1, we named values blocks like: values_block_0 an the
name values_0, adjust the given name if necessary.
Parameters
----------
name : str
version : Tuple[int, int, int]
Returns
-------
str
Definition at line 5333 of file pytables.py.
Referenced by pandas.io.pytables.Table._create_axes(), and pandas.io.pytables.Table.indexables().
_maybe_convert()
pandas.io.pytables._maybe_convert (np.ndarray values, str val_kind, str encoding, str errors) protected
Definition at line 5306 of file pytables.py.
_maybe_convert_for_string_atom()
pandas.io.pytables._maybe_convert_for_string_atom (str name, ArrayLike bvalues, existing_col, min_itemsize, nan_rep, encoding, errors, list[str] columns) protected
Definition at line 5154 of file pytables.py.
_need_convert()
bool pandas.io.pytables._need_convert (str kind) protected
Definition at line 5327 of file pytables.py.
_reindex_axis()
DataFrame pandas.io.pytables._reindex_axis (DataFrame obj, AxisInt axis, Index labels, other = None) protected
Definition at line 4978 of file pytables.py.
_set_tz() [1/3]
np.ndarray pandas.io.pytables._set_tz (np.ndarray | Index values, None tz, bool coerce = False) protected
Definition at line 5018 of file pytables.py.
_set_tz() [2/3]
DatetimeIndex pandas.io.pytables._set_tz (np.ndarray | Index values, str | tzinfo tz, bool coerce = False) protected
Definition at line 5011 of file pytables.py.
_set_tz() [3/3]
np.ndarray | DatetimeIndex pandas.io.pytables._set_tz (np.ndarray | Index values, str | tzinfo | None tz, bool coerce = False) protected
coerce the values to a DatetimeIndex if tz is set
preserve the input shape if possible
Parameters
----------
values : ndarray or Index
tz : str or tzinfo
coerce : if we do not have a passed timezone, coerce to M8[ns] ndarray
Definition at line 5022 of file pytables.py.
References _convert_string_array(), _dtype_to_kind(), _ensure_decoded(), _get_data_and_dtype_name(), and _unconvert_string_array().
_tables()
pandas.io.pytables._tables () protected
Definition at line 244 of file pytables.py.
_unconvert_index()
np.ndarray | Index pandas.io.pytables._unconvert_index (data, str kind, str encoding, str errors) protected
Definition at line 5125 of file pytables.py.
_unconvert_string_array()
np.ndarray pandas.io.pytables._unconvert_string_array (np.ndarray data, nan_rep, str encoding, str errors) protected
Inverse of _convert_string_array.
Parameters
----------
data : np.ndarray[fixed-length-string]
nan_rep : the storage repr of NaN
encoding : str
errors : str
    Handler for encoding errors.
Returns
-------
np.ndarray[object]
    Decoded data.
Definition at line 5264 of file pytables.py.
References _unconvert_string_array().
Referenced by _set_tz(), _unconvert_string_array(), and pandas.io.pytables.DataCol.convert().
read_hdf()
pandas.io.pytables.read_hdf (FilePath | HDFStore path_or_buf, key = None, str mode = "r", str errors = "strict", str | list | None where = None, int | None start = None, int | None stop = None, list[str] | None columns = None, bool iterator = False, int | None chunksize = None, ** kwargs)
Read from the store, close it if we opened it.
Retrieve pandas object stored in file, optionally based on where
criteria.
.. warning::
   Pandas uses PyTables for reading and writing HDF5 files, which allows
   serializing object-dtype data with pickle when using the "fixed" format.
   Loading pickled data received from untrusted sources can be unsafe.
   See: https://docs.python.org/3/library/pickle.html for more.
Parameters
----------
path_or_buf : str, path object, pandas.HDFStore
    Any valid string path is acceptable. Only supports the local file system,
    remote URLs and file-like objects are not supported.
    If you want to pass in a path object, pandas accepts any
    ``os.PathLike``.
    Alternatively, pandas accepts an open :class:`pandas.HDFStore` object.
key : object, optional
    The group identifier in the store. Can be omitted if the HDF file
    contains a single pandas object.
mode : {'r', 'r+', 'a'}, default 'r'
    Mode to use when opening the file. Ignored if path_or_buf is a
    :class:`pandas.HDFStore`. Default is 'r'.
errors : str, default 'strict'
    Specifies how encoding and decoding errors are to be handled.
    See the errors argument for :func:`open` for a full list
    of options.
where : list, optional
    A list of Term (or convertible) objects.
start : int, optional
    Row number to start selection.
stop  : int, optional
    Row number to stop selection.
columns : list, optional
    A list of columns names to return.
iterator : bool, optional
    Return an iterator object.
chunksize : int, optional
    Number of rows to include in an iteration when using an iterator.
**kwargs
    Additional keyword arguments passed to HDFStore.
Returns
-------
object
    The selected object. Return type depends on the object stored.
See Also
--------
DataFrame.to_hdf : Write a HDF file from a DataFrame.
HDFStore : Low-level access to HDF files.
Notes
-----
When ``errors="surrogatepass"``, ``pd.options.future.infer_string`` is true,
and PyArrow is installed, if a UTF-16 surrogate is encountered when decoding
to UTF-8, the resulting dtype will be
``pd.StringDtype(storage="python", na_value=np.nan)``.
Examples
--------
>>> df = pd.DataFrame([[1, 1.0, 'a']], columns=['x', 'y', 'z'])  # doctest: +SKIP
>>> df.to_hdf('./store.h5', 'data')  # doctest: +SKIP
>>> reread = pd.read_hdf('./store.h5')  # doctest: +SKIP
Definition at line 322 of file pytables.py.
References _ensure_term(), and _is_metadata_of().
to_hdf()
None pandas.io.pytables.to_hdf (FilePath | HDFStore path_or_buf, str key, DataFrame | Series value, str mode = "a", int | None complevel = None, str | None complib = None, bool append = False, str | None format = None, bool index = True, int | dict[str, int] | None min_itemsize = None, nan_rep = None, bool | None dropna = None, Literal[True] | list[str] | None data_columns = None, str errors = "strict", str encoding = "UTF-8")
store this object, close it if we opened it
Definition at line 266 of file pytables.py.
Variable Documentation
_AXES_MAP
dict pandas.io.pytables._AXES_MAP = {DataFrame: [0]} protected
Definition at line 217 of file pytables.py.
_default_encoding
str pandas.io.pytables._default_encoding = "UTF-8" protected
Definition at line 143 of file pytables.py.
_FORMAT_MAP
dict pandas.io.pytables._FORMAT_MAP = {"f": "fixed", "fixed": "fixed", "t": "table", "table": "table"} protected
Definition at line 214 of file pytables.py.
_table_file_open_policy_is_strict
bool pandas.io.pytables._table_file_open_policy_is_strict = False protected
Definition at line 241 of file pytables.py.
_table_mod
pandas.io.pytables._table_mod = None protected
Definition at line 240 of file pytables.py.
_version
str pandas.io.pytables._version = "0.15.2" protected
Definition at line 140 of file pytables.py.
attribute_conflict_doc
Final pandas.io.pytables.attribute_conflict_doc
Initial value:
=  """
the [%s] attribute of the existing index is [%s] which conflicts with the new
[%s], resetting the attribute to None
"""
Definition at line 203 of file pytables.py.
dropna_doc
pandas.io.pytables.dropna_doc
Initial value:
=  """
: boolean
    drop ALL nan rows when appending to a table
"""
Definition at line 220 of file pytables.py.
False
pandas.io.pytables.False
Definition at line 231 of file pytables.py.
format_doc
Final pandas.io.pytables.format_doc
Initial value:
=  """
: format
    default format writing format, if None, then
    put will default to 'fixed' and append will default to 'table'
"""
Definition at line 224 of file pytables.py.
incompatibility_doc
Final pandas.io.pytables.incompatibility_doc
Initial value:
=  """
where criteria is being ignored as this version [%s] is too old (or
not-defined), read the file in and write it out to a new file to upgrade (with
the copy_to method)
"""
Definition at line 197 of file pytables.py.
performance_doc
Final pandas.io.pytables.performance_doc
Initial value:
=  """
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->%s,key->%s] [items->%s]
"""
Definition at line 208 of file pytables.py.
Term
pandas.io.pytables.Term = PyTablesExpr
Definition at line 173 of file pytables.py.
validator
pandas.io.pytables.validator
Definition at line 231 of file pytables.py.