Code Cloning Analysis: fontTools.ttLib.scaleUpem.ScalerVisitor Class Reference
fontTools.ttLib.scaleUpem.ScalerVisitor Class Reference
Public Member Functions
__init__ (self, scaleFactor)
scale (self, v)
Public Member Functions inherited from fontTools.ttLib.ttVisitor.TTVisitor
visitAttr (self, obj, attr, value, *args, **kwargs)
visit (self, obj, *args, **kwargs)
Public Member Functions inherited from fontTools.misc.visitor.Visitor
register (celf, clazzes)
register_attr (celf, clazzes, attrs)
register_attrs (celf, clazzes_attrs)
visitObject (self, obj, *args, **kwargs)
visitList (self, obj, *args, **kwargs)
visitDict (self, obj, *args, **kwargs)
visitLeaf (self, obj, *args, **kwargs)
Public Attributes
scaleFactor = scaleFactor
Additional Inherited Members
Static Public Attributes inherited from fontTools.misc.visitor.Visitor
bool defaultStop = False
Protected Member Functions inherited from fontTools.misc.visitor.Visitor
_register (celf, clazzes_attrs)
_visitorsFor (celf, thing, _default={})
Static Protected Attributes inherited from fontTools.misc.visitor.Visitor
dict _visitors
Detailed Description
Definition at line 22 of file scaleUpem.py.
Constructor & Destructor Documentation
__init__()
fontTools.ttLib.scaleUpem.ScalerVisitor.__init__ (self, scaleFactor)
Definition at line 23 of file scaleUpem.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
scale()
fontTools.ttLib.scaleUpem.ScalerVisitor.scale (self, v)
Definition at line 26 of file scaleUpem.py.
Referenced by fontTools.ttLib.tables._g_l_y_f.GlyphCoordinates.__imul__(), fontTools.ttLib.tables._g_l_y_f.GlyphCoordinates.__itruediv__(), and matplotlib.table.Table._offset().
Member Data Documentation
scaleFactor
fontTools.ttLib.scaleUpem.ScalerVisitor.scaleFactor = scaleFactor
Definition at line 24 of file scaleUpem.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ttLib/scaleUpem.py