Code Cloning Analysis: pandas.core.resample Namespace Reference
pandas.core.resample Namespace Reference
Classes
class _GroupByMixin
class DatetimeIndexResampler
class DatetimeIndexResamplerGroupby
class PeriodIndexResampler
class PeriodIndexResamplerGroupby
class Resampler
class TimedeltaIndexResampler
class TimedeltaIndexResamplerGroupby
class TimeGrouper
Functions
_resampler_cls (self)
Resampler get_resampler (Series|DataFrame obj, kind=None, **kwds)
Resampler get_resampler_for_grouping (GroupBy groupby, rule, how=None, fill_method=None, int|None limit=None, kind=None, on=None, bool include_groups=True, **kwargs)
NDFrameT _take_new_index (NDFrameT obj, npt.NDArray[np.intp] indexer, Index new_index, AxisInt axis=0)
tuple[Timestamp, Timestamp] _get_timestamp_range_edges (Timestamp first, Timestamp last, BaseOffset freq, str unit, Literal["right", "left"] closed="left", TimeGrouperOrigin origin="start_day", Timedelta|None offset=None)
tuple[Period, Period] _get_period_range_edges (Period first, Period last, BaseOffset freq, Literal["right", "left"] closed="left", TimeGrouperOrigin origin="start_day", Timedelta|None offset=None)
tuple[PeriodIndex, np.ndarray, PeriodIndex] _insert_nat_bin (PeriodIndex binner, np.ndarray bins, PeriodIndex labels, int nat_count)
tuple[Timestamp, Timestamp] _adjust_dates_anchored (Timestamp first, Timestamp last, Tick freq, Literal["right", "left"] closed="right", TimeGrouperOrigin origin="start_day", Timedelta|None offset=None, str unit="ns")
NDFrameT asfreq (NDFrameT obj, freq, method=None, how=None, bool normalize=False, fill_value=None)
_asfreq_compat (DatetimeIndex|PeriodIndex|TimedeltaIndex index, freq)
None maybe_warn_args_and_kwargs (cls, str kernel, args, kwargs)
DataFrame _apply (GroupBy grouped, Callable how, *args, bool include_groups, **kwargs)
Variables
dict _shared_docs_kwargs = {}
__doc__
Function Documentation
_adjust_dates_anchored()
tuple[Timestamp, Timestamp] pandas.core.resample._adjust_dates_anchored (Timestamp first, Timestamp last, Tick freq, Literal["right", "left"] closed = "right", TimeGrouperOrigin origin = "start_day", Timedelta | None offset = None, str unit = "ns") protected
Definition at line 2710 of file resample.py.
_apply()
DataFrame pandas.core.resample._apply (GroupBy grouped, Callable how, * args, bool include_groups, ** kwargs) protected
Definition at line 2908 of file resample.py.
_asfreq_compat()
pandas.core.resample._asfreq_compat (DatetimeIndex | PeriodIndex | TimedeltaIndex index, freq) protected
Helper to mimic asfreq on (empty) DatetimeIndex and TimedeltaIndex.
Parameters
----------
index : PeriodIndex, DatetimeIndex, or TimedeltaIndex
freq : DateOffset
Returns
-------
same type as index
Definition at line 2844 of file resample.py.
Referenced by pandas.core.resample.Resampler._wrap_result(), asfreq(), and pandas.core.resample.Resampler.var().
_get_period_range_edges()
tuple[Period, Period] pandas.core.resample._get_period_range_edges (Period first, Period last, BaseOffset freq, Literal["right", "left"] closed = "left", TimeGrouperOrigin origin = "start_day", Timedelta | None offset = None) protected
Adjust the provided `first` and `last` Periods to the respective Period of
the given offset that encompasses them.
Parameters
----------
first : pd.Period
    The beginning Period of the range to be adjusted.
last : pd.Period
    The ending Period of the range to be adjusted.
freq : pd.DateOffset
    The freq to which the Periods will be adjusted.
closed : {'right', 'left'}, default "left"
    Which side of bin interval is closed.
origin : {'epoch', 'start', 'start_day'}, Timestamp, default 'start_day'
    The timestamp on which to adjust the grouping. The timezone of origin must
    match the timezone of the index.
    If a timestamp is not used, these values are also supported:
    - 'epoch': `origin` is 1970-01-01
    - 'start': `origin` is the first value of the timeseries
    - 'start_day': `origin` is the first day at midnight of the timeseries
offset : pd.Timedelta, default is None
    An offset timedelta added to the origin.
Returns
-------
A tuple of length 2, containing the adjusted pd.Period objects.
Definition at line 2636 of file resample.py.
References _get_timestamp_range_edges().
Referenced by pandas.core.resample.TimeGrouper._get_grouper().
_get_timestamp_range_edges()
tuple[Timestamp, Timestamp] pandas.core.resample._get_timestamp_range_edges (Timestamp first, Timestamp last, BaseOffset freq, str unit, Literal["right", "left"] closed = "left", TimeGrouperOrigin origin = "start_day", Timedelta | None offset = None) protected
Adjust the `first` Timestamp to the preceding Timestamp that resides on
the provided offset. Adjust the `last` Timestamp to the following
Timestamp that resides on the provided offset. Input Timestamps that
already reside on the offset will be adjusted depending on the type of
offset and the `closed` parameter.
Parameters
----------
first : pd.Timestamp
    The beginning Timestamp of the range to be adjusted.
last : pd.Timestamp
    The ending Timestamp of the range to be adjusted.
freq : pd.DateOffset
    The dateoffset to which the Timestamps will be adjusted.
closed : {'right', 'left'}, default "left"
    Which side of bin interval is closed.
origin : {'epoch', 'start', 'start_day'} or Timestamp, default 'start_day'
    The timestamp on which to adjust the grouping. The timezone of origin must
    match the timezone of the index.
    If a timestamp is not used, these values are also supported:
    - 'epoch': `origin` is 1970-01-01
    - 'start': `origin` is the first value of the timeseries
    - 'start_day': `origin` is the first day at midnight of the timeseries
offset : pd.Timedelta, default is None
    An offset timedelta added to the origin.
Returns
-------
A tuple of length 2, containing the adjusted pd.Timestamp objects.
Definition at line 2557 of file resample.py.
Referenced by pandas.core.resample.TimeGrouper._get_grouper(), and _get_period_range_edges().
_insert_nat_bin()
tuple[PeriodIndex, np.ndarray, PeriodIndex] pandas.core.resample._insert_nat_bin (PeriodIndex binner, np.ndarray bins, PeriodIndex labels, int nat_count) protected
Definition at line 2692 of file resample.py.
_resampler_cls()
pandas.core.resample._resampler_cls (self) protected
Provides a resample of a groupby implementation
Provides a resample of a groupby implementation.
Definition at line 1874 of file resample.py.
_take_new_index()
NDFrameT pandas.core.resample._take_new_index (NDFrameT obj, npt.NDArray[np.intp] indexer, Index new_index, AxisInt axis = 0) protected
Definition at line 2538 of file resample.py.
asfreq()
NDFrameT pandas.core.resample.asfreq (NDFrameT obj, freq, method = None, how = None, bool normalize = False, fill_value = None)
Utility frequency conversion method for Series/DataFrame.
See :meth:`pandas.NDFrame.asfreq` for full documentation.
Definition at line 2794 of file resample.py.
References _asfreq_compat().
Referenced by pandas.core.resample.TimeGrouper._get_grouper().
get_resampler()
Resampler pandas.core.resample.get_resampler (Series | DataFrame obj, kind = None, ** kwds)
Create a TimeGrouper and return our resampler.
Definition at line 2045 of file resample.py.
get_resampler_for_grouping()
Resampler pandas.core.resample.get_resampler_for_grouping (GroupBy groupby, rule, how = None, fill_method = None, int | None limit = None, kind = None, on = None, bool include_groups = True, ** kwargs)
Return our appropriate resampler when grouping as well.
Definition at line 2056 of file resample.py.
maybe_warn_args_and_kwargs()
None pandas.core.resample.maybe_warn_args_and_kwargs (cls, str kernel, args, kwargs)
Warn for deprecation of args and kwargs in resample functions.
Parameters
----------
cls : type
    Class to warn about.
kernel : str
    Operation name.
args : tuple or None
    args passed by user. Will be None if and only if kernel does not have args.
kwargs : dict or None
    kwargs passed by user. Will be None if and only if kernel does not have kwargs.
Definition at line 2874 of file resample.py.
Referenced by pandas.core.resample.Resampler.max(), pandas.core.resample.Resampler.mean(), pandas.core.resample.Resampler.min(), pandas.core.resample.Resampler.prod(), pandas.core.resample.Resampler.std(), pandas.core.resample.Resampler.sum(), and pandas.core.resample.Resampler.var().
Variable Documentation
__doc__
pandas.core.resample.__doc__ private
Definition at line 2053 of file resample.py.
_shared_docs_kwargs
dict pandas.core.resample._shared_docs_kwargs = {} protected
Definition at line 118 of file resample.py.