Code Cloning Analysis: contourpy.util.bokeh_renderer.BokehRenderer Class Reference
contourpy.util.bokeh_renderer.BokehRenderer Class Reference
Public Member Functions
None __init__ (self, int nrows=1, int ncols=1, tuple[float, float] figsize=(9, 9), bool show_frame=True, bool want_svg=False)
None filled (self, FillReturn filled, FillType|str fill_type, figure|int ax=0, str color="C0", float alpha=0.7)
None grid (self, ArrayLike x, ArrayLike y, figure|int ax=0, str color="black", float alpha=0.1, str|None point_color=None, float quad_as_tri_alpha=0)
None lines (self, LineReturn lines, LineType|str line_type, figure|int ax=0, str color="C0", float alpha=1.0, float linewidth=1)
None mask (self, ArrayLike x, ArrayLike y, ArrayLike|np.ma.MaskedArray[Any, Any] z, figure|int ax=0, str color="black")
None save (self, str filename, bool transparent=False, *, WebDriver|None webdriver=None)
io.BytesIO save_to_buffer (self, *, WebDriver|None webdriver=None)
None show (self)
None title (self, str title, figure|int ax=0, str|None color=None)
None z_values (self, ArrayLike x, ArrayLike y, ArrayLike z, figure|int ax=0, str color="green", str fmt=".1f", bool quad_as_tri=False)
Public Member Functions inherited from contourpy.util.renderer.Renderer
None multi_filled (self, list[FillReturn] multi_filled, FillType|str fill_type, Any ax=0, str|None color=None, **Any kwargs)
None multi_lines (self, list[LineReturn] multi_lines, LineType|str line_type, Any ax=0, str|None color=None, **Any kwargs)
Protected Member Functions
str _convert_color (self, str color)
figure _get_figure (self, figure|int ax)
Protected Member Functions inherited from contourpy.util.renderer.Renderer
tuple[CoordinateArray, CoordinateArray] _grid_as_2d (self, ArrayLike x, ArrayLike y)
Protected Attributes
_want_svg = want_svg
_palette = Category10[10]
_layout
Static Protected Attributes
list _figures [figure]
Detailed Description
Utility renderer using Bokeh to render a grid of plots over the same (x, y) range.
Args:
    nrows (int, optional): Number of rows of plots, default ``1``.
    ncols (int, optional): Number of columns of plots, default ``1``.
    figsize (tuple(float, float), optional): Figure size in inches (assuming 100 dpi), default
        ``(9, 9)``.
    show_frame (bool, optional): Whether to show frame and axes ticks, default ``True``.
    want_svg (bool, optional): Whether output is required in SVG format or not, default
        ``False``.
Warning:
    :class:`~.BokehRenderer`, unlike :class:`~.MplRenderer`, needs to be told in advance if
    output to SVG format will be required later, otherwise it will assume PNG output.
Definition at line 29 of file bokeh_renderer.py.
Constructor & Destructor Documentation
__init__()
None contourpy.util.bokeh_renderer.BokehRenderer.__init__ (self, int nrows = 1, int ncols = 1, tuple[float, float] figsize = (9, 9), bool show_frame = True, bool want_svg = False)
Definition at line 50 of file bokeh_renderer.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_convert_color()
str contourpy.util.bokeh_renderer.BokehRenderer._convert_color (self, str color) protected
Definition at line 79 of file bokeh_renderer.py.
Referenced by filled(), lines(), mask(), title(), and z_values().
_get_figure()
figure contourpy.util.bokeh_renderer.BokehRenderer._get_figure (self, figure | int ax) protected
Definition at line 85 of file bokeh_renderer.py.
Referenced by filled(), grid(), lines(), mask(), title(), and z_values().
filled()
None contourpy.util.bokeh_renderer.BokehRenderer.filled (self, FillReturn filled, FillType | str fill_type, figure | int ax = 0, str color = "C0", float alpha = 0.7)
Plot filled contours on a single plot.
Args:
    filled (sequence of arrays): Filled contour data as returned by
        :meth:`~.ContourGenerator.filled`.
    fill_type (FillType or str): Type of :meth:`~.ContourGenerator.filled` data as returned
        by :attr:`~.ContourGenerator.fill_type`, or a string equivalent.
    ax (int or Bokeh Figure, optional): Which plot to use, default ``0``.
    color (str, optional): Color to plot with. May be a string color or the letter ``"C"``
        followed by an integer in the range ``"C0"`` to ``"C9"`` to use a color from the
        ``Category10`` palette. Default ``"C0"``.
    alpha (float, optional): Opacity to plot with, default ``0.7``.
Reimplemented from contourpy.util.renderer.Renderer.
Definition at line 90 of file bokeh_renderer.py.
References _convert_color(), and _get_figure().
Referenced by numpy.ma.core.MaskedArray._insert_masked_print(), numpy.ma.core.MaskedArray.all(), numpy.ma.core.MaskedArray.any(), numpy.ma.core.MaskedArray.argmax(), numpy.ma.core.MaskedArray.argmin(), numpy.ma.core.MaskedArray.argsort(), numpy.ma.core.MaskedArray.cumprod(), numpy.ma.core.MaskedArray.cumsum(), numpy.ma.core.MaskedArray.max(), numpy.ma.core.MaskedArray.min(), contourpy.util.renderer.Renderer.multi_filled(), numpy.ma.core.MaskedArray.nonzero(), numpy.ma.core.MaskedArray.prod(), numpy.ma.core.MaskedArray.sum(), numpy.ma.core.MaskedArray.tobytes(), numpy.ma.core.MaskedArray.tolist(), and numpy.ma.mrecords.MaskedRecords.tolist().
grid()
None contourpy.util.bokeh_renderer.BokehRenderer.grid (self, ArrayLike x, ArrayLike y, figure | int ax = 0, str color = "black", float alpha = 0.1, str | None point_color = None, float quad_as_tri_alpha = 0)
Plot quad grid lines on a single plot.
Args:
    x (array-like of shape (ny, nx) or (nx,)): The x-coordinates of the grid points.
    y (array-like of shape (ny, nx) or (ny,)): The y-coordinates of the grid points.
    ax (int or Bokeh Figure, optional): Which plot to use, default ``0``.
    color (str, optional): Color to plot grid lines, default ``"black"``.
    alpha (float, optional): Opacity to plot lines with, default ``0.1``.
    point_color (str, optional): Color to plot grid points or ``None`` if grid points
        should not be plotted, default ``None``.
    quad_as_tri_alpha (float, optional): Opacity to plot ``quad_as_tri`` grid, default
        ``0``.
Colors may be a string color or the letter ``"C"`` followed by an integer in the range
``"C0"`` to ``"C9"`` to use a color from the ``Category10`` palette.
Warning:
    ``quad_as_tri_alpha > 0`` plots all quads as though they are unmasked.
Reimplemented from contourpy.util.renderer.Renderer.
Definition at line 118 of file bokeh_renderer.py.
References _get_figure(), and contourpy.util.renderer.Renderer._grid_as_2d().
Referenced by matplotlib.axes._base._AxesBase.__clear(), matplotlib.projections.geo.GeoAxes.clear(), matplotlib.projections.polar.PolarAxes.clear(), mplot3d.axes3d.Axes3D.clear(), matplotlib.axes._axes.Axes.cohere(), matplotlib.axes._axes.Axes.csd(), and matplotlib.axes._axes.Axes.psd().
lines()
None contourpy.util.bokeh_renderer.BokehRenderer.lines (self, LineReturn lines, LineType | str line_type, figure | int ax = 0, str color = "C0", float alpha = 1.0, float linewidth = 1)
Plot contour lines on a single plot.
Args:
    lines (sequence of arrays): Contour line data as returned by
        :meth:`~.ContourGenerator.lines`.
    line_type (LineType or str): Type of :meth:`~.ContourGenerator.lines` data as returned
        by :attr:`~.ContourGenerator.line_type`, or a string equivalent.
    ax (int or Bokeh Figure, optional): Which plot to use, default ``0``.
    color (str, optional): Color to plot lines. May be a string color or the letter ``"C"``
        followed by an integer in the range ``"C0"`` to ``"C9"`` to use a color from the
        ``Category10`` palette. Default ``"C0"``.
    alpha (float, optional): Opacity to plot lines with, default ``1.0``.
    linewidth (float, optional): Width of lines, default ``1``.
Note:
    Assumes all lines are open line strips not closed line loops.
Reimplemented from contourpy.util.renderer.Renderer.
Definition at line 170 of file bokeh_renderer.py.
References _convert_color(), and _get_figure().
Referenced by contourpy.util.renderer.Renderer.multi_lines().
mask()
None contourpy.util.bokeh_renderer.BokehRenderer.mask (self, ArrayLike x, ArrayLike y, ArrayLike | np.ma.MaskedArray[Any, Any] z, figure | int ax = 0, str color = "black")
Plot masked out grid points as circles on a single plot.
Args:
    x (array-like of shape (ny, nx) or (nx,)): The x-coordinates of the grid points.
    y (array-like of shape (ny, nx) or (ny,)): The y-coordinates of the grid points.
    z (masked array of shape (ny, nx): z-values.
    ax (int or Bokeh Figure, optional): Which plot to use, default ``0``.
    color (str, optional): Circle color, default ``"black"``.
Reimplemented from contourpy.util.renderer.Renderer.
Definition at line 204 of file bokeh_renderer.py.
References _convert_color(), _get_figure(), and contourpy.util.renderer.Renderer._grid_as_2d().
Referenced by pandas.core.series.Series.combine_first().
save()
None contourpy.util.bokeh_renderer.BokehRenderer.save (self, str filename, bool transparent = False, * , WebDriver | None webdriver = None)
Save plots to SVG or PNG file.
Args:
    filename (str): Filename to save to.
    transparent (bool, optional): Whether background should be transparent, default
        ``False``.
    webdriver (WebDriver, optional): Selenium WebDriver instance to use to create the image.
        .. versionadded:: 1.1.1
Warning:
    To output to SVG file, ``want_svg=True`` must have been passed to the constructor.
Reimplemented from contourpy.util.renderer.Renderer.
Definition at line 229 of file bokeh_renderer.py.
References _figures, _layout, and _want_svg.
Referenced by PIL.Image.Image._repr_image(), PIL.Image.Image.close(), joblib.externals.cloudpickle.cloudpickle.Pickler.reducer_override(), matplotlib.animation.Animation.to_html5_video(), and matplotlib.animation.Animation.to_jshtml().
save_to_buffer()
io.BytesIO contourpy.util.bokeh_renderer.BokehRenderer.save_to_buffer (self, * , WebDriver | None webdriver = None)
Save plots to an ``io.BytesIO`` buffer.
Args:
    webdriver (WebDriver, optional): Selenium WebDriver instance to use to create the image.
        .. versionadded:: 1.1.1
Return:
    BytesIO: PNG image buffer.
Reimplemented from contourpy.util.renderer.Renderer.
Definition at line 259 of file bokeh_renderer.py.
References _layout.
show()
None contourpy.util.bokeh_renderer.BokehRenderer.show (self)
Show plots in web browser, in usual Bokeh manner.
Reimplemented from contourpy.util.renderer.Renderer.
Definition at line 275 of file bokeh_renderer.py.
References _layout, and show().
Referenced by matplotlib.backends.backend_nbagg.FigureManagerNbAgg.reshow(), and show().
title()
None contourpy.util.bokeh_renderer.BokehRenderer.title (self, str title, figure | int ax = 0, str | None color = None)
Set the title of a single plot.
Args:
    title (str): Title text.
    ax (int or Bokeh Figure, optional): Which plot to set the title of, default ``0``.
    color (str, optional): Color to set title. May be a string color or the letter ``"C"``
        followed by an integer in the range ``"C0"`` to ``"C9"`` to use a color from the
        ``Category10`` palette. Default ``None`` which is ``black``.
Reimplemented from contourpy.util.renderer.Renderer.
Definition at line 280 of file bokeh_renderer.py.
References _convert_color(), and _get_figure().
z_values()
None contourpy.util.bokeh_renderer.BokehRenderer.z_values (self, ArrayLike x, ArrayLike y, ArrayLike z, figure | int ax = 0, str color = "green", str fmt = ".1f", bool quad_as_tri = False)
Show ``z`` values on a single plot.
Args:
    x (array-like of shape (ny, nx) or (nx,)): The x-coordinates of the grid points.
    y (array-like of shape (ny, nx) or (ny,)): The y-coordinates of the grid points.
    z (array-like of shape (ny, nx): z-values.
    ax (int or Bokeh Figure, optional): Which plot to use, default ``0``.
    color (str, optional): Color of added text. May be a string color or the letter ``"C"``
        followed by an integer in the range ``"C0"`` to ``"C9"`` to use a color from the
        ``Category10`` palette. Default ``"green"``.
    fmt (str, optional): Format to display z-values, default ``".1f"``.
    quad_as_tri (bool, optional): Whether to show z-values at the ``quad_as_tri`` centres
        of quads.
Warning:
    ``quad_as_tri=True`` shows z-values for all quads, even if masked.
Reimplemented from contourpy.util.renderer.Renderer.
Definition at line 296 of file bokeh_renderer.py.
References _convert_color(), _get_figure(), and contourpy.util.renderer.Renderer._grid_as_2d().
Member Data Documentation
_figures
list contourpy.util.bokeh_renderer.BokehRenderer._figures [figure] static protected
Definition at line 45 of file bokeh_renderer.py.
Referenced by save().
_layout
contourpy.util.bokeh_renderer.BokehRenderer._layout protected
Initial value:
=  gridplot(
            self._figures, ncols=ncols, toolbar_location=None,  # type: ignore[arg-type]
            width=total_size[0] // ncols, height=total_size[1] // nrows)
Definition at line 75 of file bokeh_renderer.py.
Referenced by save(), save_to_buffer(), and show().
_palette
contourpy.util.bokeh_renderer.BokehRenderer._palette = Category10[10] protected
Definition at line 59 of file bokeh_renderer.py.
Referenced by PIL.ImagePalette.ImagePalette.getcolor(), and PIL.ImagePalette.ImagePalette.tobytes().
_want_svg
contourpy.util.bokeh_renderer.BokehRenderer._want_svg = want_svg protected
Definition at line 58 of file bokeh_renderer.py.
Referenced by save().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/contourpy/util/bokeh_renderer.py