Code Cloning Analysis: scipy.stats._qmc Namespace Reference
scipy.stats._qmc Namespace Reference
Classes
class Halton
class LatinHypercube
class MultinomialQMC
class MultivariateNormalQMC
class PoissonDisk
class QMCEngine
class Sobol
Functions
np.random.Generator check_random_state (IntNumber|None seed=...)
GeneratorType check_random_state (GeneratorType seed)
check_random_state (seed=None)
np.ndarray scale (npt.ArrayLike sample, npt.ArrayLike l_bounds, npt.ArrayLike u_bounds, *, bool reverse=False)
float discrepancy (npt.ArrayLike sample, *, bool iterative=False, Literal["CD", "WD", "MD", "L2-star"] method="CD", IntNumber workers=1)
float update_discrepancy (npt.ArrayLike x_new, npt.ArrayLike sample, DecimalNumber initial_disc)
_perturb_discrepancy (np.ndarray sample, int i1, int i2, int k, float disc)
np.ndarray primes_from_2_to (int n)
list[int] n_primes (IntNumber n)
np.ndarray _van_der_corput_permutations (IntNumber base, *, SeedType random_state=None)
np.ndarray van_der_corput (IntNumber n, IntNumber base=2, *, IntNumber start_index=0, bool scramble=False, npt.ArrayLike|None permutations=None, SeedType seed=None, IntNumber workers=1)
Callable|None _select_optimizer (Literal["random-cd", "lloyd"]|None optimization, dict config)
np.ndarray _random_cd (np.ndarray best_sample, int n_iters, int n_nochange, GeneratorType rng, **dict kwargs)
float _l1_norm (np.ndarray sample)
np.ndarray _lloyd_iteration (np.ndarray sample, float decay, str qhull_options)
np.ndarray _lloyd_centroidal_voronoi_tessellation (npt.ArrayLike sample, *, DecimalNumber tol=1e-5, IntNumber maxiter=10, str|None qhull_options=None, **dict kwargs)
IntNumber _validate_workers (IntNumber workers=1)
tuple[np.ndarray,...] _validate_bounds (npt.ArrayLike l_bounds, npt.ArrayLike u_bounds, int d)
Variables
list __all__
Detailed Description
Quasi-Monte Carlo engines and helpers.
Function Documentation
_l1_norm()
float scipy.stats._qmc._l1_norm (np.ndarray sample) protected
Definition at line 2373 of file _qmc.py.
_lloyd_centroidal_voronoi_tessellation()
np.ndarray scipy.stats._qmc._lloyd_centroidal_voronoi_tessellation (npt.ArrayLike sample, * , DecimalNumber tol = 1e-5, IntNumber maxiter = 10, str | None qhull_options = None, **dict kwargs) protected
Approximate Centroidal Voronoi Tessellation.
Perturb samples in N-dimensions using Lloyd-Max algorithm.
Parameters
----------
sample : array_like (n, d)
    The sample to iterate on. With ``n`` the number of samples and ``d``
    the dimension. Samples must be in :math:`[0, 1]^d`, with ``d>=2``.
tol : float, optional
    Tolerance for termination. If the min of the L1-norm over the samples
    changes less than `tol`, it stops the algorithm. Default is 1e-5.
maxiter : int, optional
    Maximum number of iterations. It will stop the algorithm even if
    `tol` is above the threshold.
    Too many iterations tend to cluster the samples as a hypersphere.
    Default is 10.
qhull_options : str, optional
    Additional options to pass to Qhull. See Qhull manual
    for details. (Default: "Qbb Qc Qz Qj Qx" for ndim > 4 and
    "Qbb Qc Qz Qj" otherwise.)
Returns
-------
sample : array_like (n, d)
    The sample after being processed by Lloyd-Max algorithm.
Notes
-----
Lloyd-Max algorithm is an iterative process with the purpose of improving
the dispersion of samples. For given sample: (i) compute a Voronoi
Tessellation; (ii) find the centroid of each Voronoi cell; (iii) move the
samples toward the centroid of their respective cell. See [1]_, [2]_.
A relaxation factor is used to control how fast samples can move at each
iteration. This factor is starting at 2 and ending at 1 after `maxiter`
following an exponential decay.
The process converges to equally spaced samples. It implies that measures
like the discrepancy could suffer from too many iterations. On the other
hand, L1 and L2 distances should improve. This is especially true with
QMC methods which tend to favor the discrepancy over other criteria.
.. note::
    The current implementation does not intersect the Voronoi Tessellation
    with the boundaries. This implies that for a low number of samples,
    empirically below 20, no Voronoi cell is touching the boundaries.
    Hence, samples cannot be moved close to the boundaries.
    Further improvements could consider the samples at infinity so that
    all boundaries are segments of some Voronoi cells. This would fix
    the computation of the centroid position.
.. warning::
   The Voronoi Tessellation step is expensive and quickly becomes
   intractable with dimensions as low as 10 even for a sample
   of size as low as 1000.
.. versionadded:: 1.9.0
References
----------
.. [1] Lloyd. "Least Squares Quantization in PCM".
   IEEE Transactions on Information Theory, 1982.
.. [2] Max J. "Quantizing for minimum distortion".
   IEEE Transactions on Information Theory, 1960.
Examples
--------
>>> import numpy as np
>>> from scipy.spatial import distance
>>> rng = np.random.default_rng()
>>> sample = rng.random((128, 2))
.. note::
    The samples need to be in :math:`[0, 1]^d`. `scipy.stats.qmc.scale`
    can be used to scale the samples from their
    original bounds to :math:`[0, 1]^d`. And back to their original bounds.
Compute the quality of the sample using the L1 criterion.
>>> def l1_norm(sample):
...    return distance.pdist(sample, 'cityblock').min()
>>> l1_norm(sample)
0.00161...  # random
Now process the sample using Lloyd's algorithm and check the improvement
on the L1. The value should increase.
>>> sample = _lloyd_centroidal_voronoi_tessellation(sample)
>>> l1_norm(sample)
0.0278...  # random
Definition at line 2441 of file _qmc.py.
References _lloyd_iteration().
_lloyd_iteration()
np.ndarray scipy.stats._qmc._lloyd_iteration (np.ndarray sample, float decay, str qhull_options) protected
Lloyd-Max algorithm iteration.
Based on the implementation of Stéfan van der Walt:
https://github.com/stefanv/lloyd
which is:
    Copyright (c) 2021-04-21 Stéfan van der Walt
    https://github.com/stefanv/lloyd
    MIT License
Parameters
----------
sample : array_like (n, d)
    The sample to iterate on.
decay : float
    Relaxation decay. A positive value would move the samples toward
    their centroid, and negative value would move them away.
    1 would move the samples to their centroid.
qhull_options : str
    Additional options to pass to Qhull. See Qhull manual
    for details. (Default: "Qbb Qc Qz Qj Qx" for ndim > 4 and
    "Qbb Qc Qz Qj" otherwise.)
Returns
-------
sample : array_like (n, d)
    The sample after an iteration of Lloyd's algorithm.
Definition at line 2377 of file _qmc.py.
Referenced by _lloyd_centroidal_voronoi_tessellation().
_perturb_discrepancy()
scipy.stats._qmc._perturb_discrepancy (np.ndarray sample, int i1, int i2, int k, float disc) protected
Centered discrepancy after an elementary perturbation of a LHS.
An elementary perturbation consists of an exchange of coordinates between
two points: ``sample[i1, k] <-> sample[i2, k]``. By construction,
this operation conserves the LHS properties.
Parameters
----------
sample : array_like (n, d)
    The sample (before permutation) to compute the discrepancy from.
i1 : int
    The first line of the elementary permutation.
i2 : int
    The second line of the elementary permutation.
k : int
    The column of the elementary permutation.
disc : float
    Centered discrepancy of the design before permutation.
Returns
-------
discrepancy : float
    Centered discrepancy of the design after permutation.
References
----------
.. [1] Jin et al. "An efficient algorithm for constructing optimal design
   of computer experiments", Journal of Statistical Planning and
   Inference, 2005.
Definition at line 370 of file _qmc.py.
Referenced by _random_cd().
_random_cd()
np.ndarray scipy.stats._qmc._random_cd (np.ndarray best_sample, int n_iters, int n_nochange, GeneratorType rng, **dict kwargs) protected
Optimal LHS on CD.
Create a base LHS and do random permutations of coordinates to
lower the centered discrepancy.
Because it starts with a normal LHS, it also works with the
`centered` keyword argument.
Two stopping criterion are used to stop the algorithm: at most,
`n_iters` iterations are performed; or if there is no improvement
for `n_nochange` consecutive iterations.
Definition at line 2318 of file _qmc.py.
References _perturb_discrepancy(), and discrepancy().
_select_optimizer()
Callable | None scipy.stats._qmc._select_optimizer (Literal["random-cd", "lloyd"] | None optimization, dict config) protected
A factory for optimization methods.
Definition at line 2290 of file _qmc.py.
_validate_bounds()
tuple[np.ndarray, ...] scipy.stats._qmc._validate_bounds (npt.ArrayLike l_bounds, npt.ArrayLike u_bounds, int d) protected
Bounds input validation.
Parameters
----------
l_bounds, u_bounds : array_like (d,)
    Lower and upper bounds.
d : int
    Dimension to use for broadcasting.
Returns
-------
l_bounds, u_bounds : array_like (d,)
    Lower and upper bounds.
Definition at line 2620 of file _qmc.py.
Referenced by scale().
_validate_workers()
IntNumber scipy.stats._qmc._validate_workers (IntNumber workers = 1) protected
Validate `workers` based on platform and value.
Parameters
----------
workers : int, optional
    Number of workers to use for parallel processing. If -1 is
    given all CPU threads are used. Default is 1.
Returns
-------
Workers : int
    Number of CPU used by the algorithm
Definition at line 2590 of file _qmc.py.
Referenced by scipy.stats._qmc.Halton._random(), and discrepancy().
_van_der_corput_permutations()
np.ndarray scipy.stats._qmc._van_der_corput_permutations (IntNumber base, * , SeedType random_state = None) protected
Permutations for scrambling a Van der Corput sequence.
Parameters
----------
base : int
    Base of the sequence.
random_state : {None, int, `numpy.random.Generator`}, optional
    If `seed` is an int or None, a new `numpy.random.Generator` is
    created using ``np.random.default_rng(seed)``.
    If `seed` is already a ``Generator`` instance, then the provided
    instance is used.
Returns
-------
permutations : array_like
    Permutation indices.
Notes
-----
In Algorithm 1 of Owen 2017, a permutation of `np.arange(base)` is
created for each positive integer `k` such that `1 - base**-k < 1`
using floating-point arithmetic. For double precision floats, the
condition `1 - base**-k < 1` can also be written as `base**-k >
2**-54`, which makes it more apparent how many permutations we need
to create.
Definition at line 531 of file _qmc.py.
Referenced by scipy.stats._qmc.Halton._initialize_permutations(), and van_der_corput().
check_random_state() [1/3]
GeneratorType scipy.stats._qmc.check_random_state (GeneratorType seed)
Definition at line 57 of file _qmc.py.
check_random_state() [2/3]
np.random.Generator scipy.stats._qmc.check_random_state (IntNumber | None seed = ...)
Definition at line 52 of file _qmc.py.
check_random_state() [3/3]
scipy.stats._qmc.check_random_state (seed = None)
Turn `seed` into a `numpy.random.Generator` instance.
Parameters
----------
seed : {None, int, `numpy.random.Generator`, `numpy.random.RandomState`}, optional  # noqa
    If `seed` is an int or None, a new `numpy.random.Generator` is
    created using ``np.random.default_rng(seed)``.
    If `seed` is already a ``Generator`` or ``RandomState`` instance, then
    the provided instance is used.
Returns
-------
seed : {`numpy.random.Generator`, `numpy.random.RandomState`}
    Random number generator.
Definition at line 62 of file _qmc.py.
discrepancy()
float scipy.stats._qmc.discrepancy (npt.ArrayLike sample, * , bool iterative = False, Literal["CD", "WD", "MD", "L2-star"] method = "CD", IntNumber workers = 1)
Discrepancy of a given sample.
Parameters
----------
sample : array_like (n, d)
    The sample to compute the discrepancy from.
iterative : bool, optional
    Must be False if not using it for updating the discrepancy.
    Default is False. Refer to the notes for more details.
method : str, optional
    Type of discrepancy, can be ``CD``, ``WD``, ``MD`` or ``L2-star``.
    Refer to the notes for more details. Default is ``CD``.
workers : int, optional
    Number of workers to use for parallel processing. If -1 is given all
    CPU threads are used. Default is 1.
Returns
-------
discrepancy : float
    Discrepancy.
Notes
-----
The discrepancy is a uniformity criterion used to assess the space filling
of a number of samples in a hypercube. A discrepancy quantifies the
distance between the continuous uniform distribution on a hypercube and the
discrete uniform distribution on :math:`n` distinct sample points.
The lower the value is, the better the coverage of the parameter space is.
For a collection of subsets of the hypercube, the discrepancy is the
difference between the fraction of sample points in one of those
subsets and the volume of that subset. There are different definitions of
discrepancy corresponding to different collections of subsets. Some
versions take a root mean square difference over subsets instead of
a maximum.
A measure of uniformity is reasonable if it satisfies the following
criteria [1]_:
1. It is invariant under permuting factors and/or runs.
2. It is invariant under rotation of the coordinates.
3. It can measure not only uniformity of the sample over the hypercube,
   but also the projection uniformity of the sample over non-empty
   subset of lower dimension hypercubes.
4. There is some reasonable geometric meaning.
5. It is easy to compute.
6. It satisfies the Koksma-Hlawka-like inequality.
7. It is consistent with other criteria in experimental design.
Four methods are available:
* ``CD``: Centered Discrepancy - subspace involves a corner of the
  hypercube
* ``WD``: Wrap-around Discrepancy - subspace can wrap around bounds
* ``MD``: Mixture Discrepancy - mix between CD/WD covering more criteria
* ``L2-star``: L2-star discrepancy - like CD BUT variant to rotation
See [2]_ for precise definitions of each method.
Lastly, using ``iterative=True``, it is possible to compute the
discrepancy as if we had :math:`n+1` samples. This is useful if we want
to add a point to a sampling and check the candidate which would give the
lowest discrepancy. Then you could just update the discrepancy with
each candidate using `update_discrepancy`. This method is faster than
computing the discrepancy for a large number of candidates.
References
----------
.. [1] Fang et al. "Design and modeling for computer experiments".
   Computer Science and Data Analysis Series, 2006.
.. [2] Zhou Y.-D. et al. "Mixture discrepancy for quasi-random point sets."
   Journal of Complexity, 29 (3-4) , pp. 283-301, 2013.
.. [3] T. T. Warnock. "Computational investigations of low discrepancy
   point sets." Applications of Number Theory to Numerical
   Analysis, Academic Press, pp. 319-343, 1972.
Examples
--------
Calculate the quality of the sample using the discrepancy:
>>> import numpy as np
>>> from scipy.stats import qmc
>>> space = np.array([[1, 3], [2, 6], [3, 2], [4, 5], [5, 1], [6, 4]])
>>> l_bounds = [0.5, 0.5]
>>> u_bounds = [6.5, 6.5]
>>> space = qmc.scale(space, l_bounds, u_bounds, reverse=True)
>>> space
array([[0.08333333, 0.41666667],
       [0.25      , 0.91666667],
       [0.41666667, 0.25      ],
       [0.58333333, 0.75      ],
       [0.75      , 0.08333333],
       [0.91666667, 0.58333333]])
>>> qmc.discrepancy(space)
0.008142039609053464
We can also compute iteratively the ``CD`` discrepancy by using
``iterative=True``.
>>> disc_init = qmc.discrepancy(space[:-1], iterative=True)
>>> disc_init
0.04769081147119336
>>> qmc.update_discrepancy(space[-1], space[:-1], disc_init)
0.008142039609053513
Definition at line 171 of file _qmc.py.
References _validate_workers().
Referenced by _random_cd().
n_primes()
list[int] scipy.stats._qmc.n_primes (IntNumber n)
List of the n-first prime numbers.
Parameters
----------
n : int
    Number of prime numbers wanted.
Returns
-------
primes : list(int)
    List of primes.
Definition at line 492 of file _qmc.py.
References primes_from_2_to().
primes_from_2_to()
np.ndarray scipy.stats._qmc.primes_from_2_to (int n)
Prime numbers from 2 to *n*.
Parameters
----------
n : int
    Sup bound with ``n >= 6``.
Returns
-------
primes : list(int)
    Primes in ``2 <= p < n``.
Notes
-----
Taken from [1]_ by P.T. Roy, written consent given on 23.04.2021
by the original author, Bruno Astrolino, for free use in SciPy under
the 3-clause BSD.
References
----------
.. [1] `StackOverflow <https://stackoverflow.com/questions/2068372>`_.
Definition at line 460 of file _qmc.py.
Referenced by scipy.stats._qmc.LatinHypercube._random_oa_lhs(), and n_primes().
scale()
np.ndarray scipy.stats._qmc.scale (npt.ArrayLike sample, npt.ArrayLike l_bounds, npt.ArrayLike u_bounds, * , bool reverse = False)
Sample scaling from unit hypercube to different bounds.
To convert a sample from :math:`[0, 1)` to :math:`[a, b), b>a`,
with :math:`a` the lower bounds and :math:`b` the upper bounds.
The following transformation is used:
.. math::
(b - a) \cdot \text{sample} + a
Parameters
----------
sample : array_like (n, d)
Sample to scale.
l_bounds, u_bounds : array_like (d,)
Lower and upper bounds (resp. :math:`a`, :math:`b`) of transformed
data. If `reverse` is True, range of the original data to transform
to the unit hypercube.
reverse : bool, optional
Reverse the transformation from different bounds to the unit hypercube.
Default is False.
Returns
-------
sample : array_like (n, d)
Scaled sample.
Examples
--------
Transform 3 samples in the unit hypercube to bounds:
>>> from scipy.stats import qmc
>>> l_bounds = [-2, 0]
>>> u_bounds = [6, 5]
>>> sample = [[0.5 , 0.75],
...           [0.5 , 0.5],
...           [0.75, 0.25]]
>>> sample_scaled = qmc.scale(sample, l_bounds, u_bounds)
>>> sample_scaled
array([[2.  , 3.75],
[2.  , 2.5 ],
[4.  , 1.25]])
And convert back to the unit hypercube:
>>> sample_ = qmc.scale(sample_scaled, l_bounds, u_bounds, reverse=True)
>>> sample_
array([[0.5 , 0.75],
[0.5 , 0.5 ],
[0.75, 0.25]])
Definition at line 88 of file _qmc.py.
References _validate_bounds().
update_discrepancy()
float scipy.stats._qmc.update_discrepancy (npt.ArrayLike x_new, npt.ArrayLike sample, DecimalNumber initial_disc)
Update the centered discrepancy with a new sample.
Parameters
----------
x_new : array_like (1, d)
    The new sample to add in `sample`.
sample : array_like (n, d)
    The initial sample.
initial_disc : float
    Centered discrepancy of the `sample`.
Returns
-------
discrepancy : float
    Centered discrepancy of the sample composed of `x_new` and `sample`.
Examples
--------
We can also compute iteratively the discrepancy by using
``iterative=True``.
>>> import numpy as np
>>> from scipy.stats import qmc
>>> space = np.array([[1, 3], [2, 6], [3, 2], [4, 5], [5, 1], [6, 4]])
>>> l_bounds = [0.5, 0.5]
>>> u_bounds = [6.5, 6.5]
>>> space = qmc.scale(space, l_bounds, u_bounds, reverse=True)
>>> disc_init = qmc.discrepancy(space[:-1], iterative=True)
>>> disc_init
0.04769081147119336
>>> qmc.update_discrepancy(space[-1], space[:-1], disc_init)
0.008142039609053513
Definition at line 309 of file _qmc.py.
van_der_corput()
np.ndarray scipy.stats._qmc.van_der_corput (IntNumber n, IntNumber base = 2, * , IntNumber start_index = 0, bool scramble = False, npt.ArrayLike | None permutations = None, SeedType seed = None, IntNumber workers = 1)
Van der Corput sequence.
Pseudo-random number generator based on a b-adic expansion.
Scrambling uses permutations of the remainders (see [1]_). Multiple
permutations are applied to construct a point. The sequence of
permutations has to be the same for all points of the sequence.
Parameters
----------
n : int
    Number of element of the sequence.
base : int, optional
    Base of the sequence. Default is 2.
start_index : int, optional
    Index to start the sequence from. Default is 0.
scramble : bool, optional
    If True, use Owen scrambling. Otherwise no scrambling is done.
    Default is True.
permutations : array_like, optional
    Permutations used for scrambling.
seed : {None, int, `numpy.random.Generator`}, optional
    If `seed` is an int or None, a new `numpy.random.Generator` is
    created using ``np.random.default_rng(seed)``.
    If `seed` is already a ``Generator`` instance, then the provided
    instance is used.
workers : int, optional
    Number of workers to use for parallel processing. If -1 is
    given all CPU threads are used. Default is 1.
Returns
-------
sequence : list (n,)
    Sequence of Van der Corput.
References
----------
.. [1] A. B. Owen. "A randomized Halton algorithm in R",
   :arxiv:`1706.02808`, 2017.
Definition at line 569 of file _qmc.py.
References _van_der_corput_permutations().
Referenced by scipy.stats._qmc.Halton._random().
Variable Documentation
__all__
list scipy.stats._qmc.__all__ private
Initial value:
=  ['scale', 'discrepancy', 'update_discrepancy',
           'QMCEngine', 'Sobol', 'Halton', 'LatinHypercube', 'PoissonDisk',
           'MultinomialQMC', 'MultivariateNormalQMC']
Definition at line 46 of file _qmc.py.