Code Cloning Analysis: numpy.matlib Namespace Reference
numpy.matlib Namespace Reference
Functions
empty (shape, dtype=None, order='C')
ones (shape, dtype=None, order='C')
zeros (shape, dtype=None, order='C')
identity (n, dtype=None)
eye (n, M=None, k=0, dtype=float, order='C')
rand (*args)
randn (*args)
repmat (a, m, n)
Variables
PendingDeprecationWarning
stacklevel
__version__ = np.__version__
__all__ = np.__all__[:]
Function Documentation
empty()
numpy.matlib.empty (shape, dtype = None, order = 'C')
Return a new matrix of given shape and type, without initializing entries.
Parameters
----------
shape : int or tuple of int
    Shape of the empty matrix.
dtype : data-type, optional
    Desired output data-type.
order : {'C', 'F'}, optional
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
See Also
--------
empty_like, zeros
Notes
-----
`empty`, unlike `zeros`, does not set the matrix values to zero,
and may therefore be marginally faster.  On the other hand, it requires
the user to manually set all the values in the array, and should be
used with caution.
Examples
--------
>>> import numpy.matlib
>>> np.matlib.empty((2, 2))    # filled with random data
matrix([[  6.76425276e-320,   9.79033856e-307], # random
        [  7.39337286e-309,   3.22135945e-309]])
>>> np.matlib.empty((2, 2), dtype=int)
matrix([[ 6600475,        0], # random
        [ 6586976, 22740995]])
Definition at line 24 of file matlib.py.
Referenced by identity().
eye()
numpy.matlib.eye (n, M = None, k = 0, dtype = float, order = 'C')
Return a matrix with ones on the diagonal and zeros elsewhere.
Parameters
----------
n : int
    Number of rows in the output.
M : int, optional
    Number of columns in the output, defaults to `n`.
k : int, optional
    Index of the diagonal: 0 refers to the main diagonal,
    a positive value refers to an upper diagonal,
    and a negative value to a lower diagonal.
dtype : dtype, optional
    Data-type of the returned matrix.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.
    .. versionadded:: 1.14.0
Returns
-------
I : matrix
    A `n` x `M` matrix where all elements are equal to zero,
    except for the `k`-th diagonal, whose values are equal to one.
See Also
--------
numpy.eye : Equivalent array function.
identity : Square identity matrix.
Examples
--------
>>> import numpy.matlib
>>> np.matlib.eye(3, k=1, dtype=float)
matrix([[0.,  1.,  0.],
        [0.,  0.,  1.],
        [0.,  0.,  0.]])
Definition at line 187 of file matlib.py.
References numpy.matrixlib.defmatrix.asmatrix().
identity()
numpy.matlib.identity (n, dtype = None)
Returns the square identity matrix of given size.
Parameters
----------
n : int
    Size of the returned identity matrix.
dtype : data-type, optional
    Data-type of the output. Defaults to ``float``.
Returns
-------
out : matrix
    `n` x `n` matrix with its main diagonal set to one,
    and all other elements zero.
See Also
--------
numpy.identity : Equivalent array function.
matlib.eye : More general matrix identity function.
Examples
--------
>>> import numpy.matlib
>>> np.matlib.identity(3, dtype=int)
matrix([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])
Definition at line 151 of file matlib.py.
References empty().
ones()
numpy.matlib.ones (shape, dtype = None, order = 'C')
Matrix of ones.
Return a matrix of given shape and type, filled with ones.
Parameters
----------
shape : {sequence of ints, int}
    Shape of the matrix
dtype : data-type, optional
    The desired data-type for the matrix, default is np.float64.
order : {'C', 'F'}, optional
    Whether to store matrix in C- or Fortran-contiguous order,
    default is 'C'.
Returns
-------
out : matrix
    Matrix of ones of given shape, dtype, and order.
See Also
--------
ones : Array of ones.
matlib.zeros : Zero matrix.
Notes
-----
If `shape` has length one i.e. ``(N,)``, or is a scalar ``N``,
`out` becomes a single row matrix of shape ``(1,N)``.
Examples
--------
>>> np.matlib.ones((2,3))
matrix([[1.,  1.,  1.],
        [1.,  1.,  1.]])
>>> np.matlib.ones(2)
matrix([[1.,  1.]])
Definition at line 62 of file matlib.py.
rand()
numpy.matlib.rand (* args)
Return a matrix of random values with given shape.
Create a matrix of the given shape and propagate it with
random samples from a uniform distribution over ``[0, 1)``.
Parameters
----------
\\*args : Arguments
    Shape of the output.
    If given as N integers, each integer specifies the size of one
    dimension.
    If given as a tuple, this tuple gives the complete shape.
Returns
-------
out : ndarray
    The matrix of random values with shape given by `\\*args`.
See Also
--------
randn, numpy.random.RandomState.rand
Examples
--------
>>> np.random.seed(123)
>>> import numpy.matlib
>>> np.matlib.rand(2, 3)
matrix([[0.69646919, 0.28613933, 0.22685145],
        [0.55131477, 0.71946897, 0.42310646]])
>>> np.matlib.rand((2, 3))
matrix([[0.9807642 , 0.68482974, 0.4809319 ],
        [0.39211752, 0.34317802, 0.72904971]])
If the first argument is a tuple, other arguments are ignored:
>>> np.matlib.rand((2, 3), 4)
matrix([[0.43857224, 0.0596779 , 0.39804426],
        [0.73799541, 0.18249173, 0.17545176]])
Definition at line 231 of file matlib.py.
References numpy.matrixlib.defmatrix.asmatrix().
randn()
numpy.matlib.randn (* args)
Return a random matrix with data from the "standard normal" distribution.
`randn` generates a matrix filled with random floats sampled from a
univariate "normal" (Gaussian) distribution of mean 0 and variance 1.
Parameters
----------
\\*args : Arguments
    Shape of the output.
    If given as N integers, each integer specifies the size of one
    dimension. If given as a tuple, this tuple gives the complete shape.
Returns
-------
Z : matrix of floats
    A matrix of floating-point samples drawn from the standard normal
    distribution.
See Also
--------
rand, numpy.random.RandomState.randn
Notes
-----
For random samples from the normal distribution with mean ``mu`` and
standard deviation ``sigma``, use::
    sigma * np.matlib.randn(...) + mu
Examples
--------
>>> np.random.seed(123)
>>> import numpy.matlib
>>> np.matlib.randn(1)
matrix([[-1.0856306]])
>>> np.matlib.randn(1, 2, 3)
matrix([[ 0.99734545,  0.2829785 , -1.50629471],
        [-0.57860025,  1.65143654, -2.42667924]])
Two-by-four matrix of samples from the normal distribution with
mean 3 and standard deviation 2.5:
>>> 2.5 * np.matlib.randn((2, 4)) + 3
matrix([[1.92771843, 6.16484065, 0.83314899, 1.30278462],
        [2.76322758, 6.72847407, 1.40274501, 1.8900451 ]])
Definition at line 277 of file matlib.py.
References numpy.matrixlib.defmatrix.asmatrix().
repmat()
numpy.matlib.repmat (a, m, n)
Repeat a 0-D to 2-D array or matrix MxN times.
Parameters
----------
a : array_like
    The array or matrix to be repeated.
m, n : int
    The number of times `a` is repeated along the first and second axes.
Returns
-------
out : ndarray
    The result of repeating `a`.
Examples
--------
>>> import numpy.matlib
>>> a0 = np.array(1)
>>> np.matlib.repmat(a0, 2, 3)
array([[1, 1, 1],
       [1, 1, 1]])
>>> a1 = np.arange(4)
>>> np.matlib.repmat(a1, 2, 2)
array([[0, 1, 2, 3, 0, 1, 2, 3],
       [0, 1, 2, 3, 0, 1, 2, 3]])
>>> a2 = np.asmatrix(np.arange(6).reshape(2, 3))
>>> np.matlib.repmat(a2, 2, 3)
matrix([[0, 1, 2, 0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5, 3, 4, 5],
        [0, 1, 2, 0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5, 3, 4, 5]])
Definition at line 330 of file matlib.py.
References numpy.core.fromnumeric.repeat(), and numpy.core.fromnumeric.reshape().
zeros()
numpy.matlib.zeros (shape, dtype = None, order = 'C')
Return a matrix of given shape and type, filled with zeros.
Parameters
----------
shape : int or sequence of ints
    Shape of the matrix
dtype : data-type, optional
    The desired data-type for the matrix, default is float.
order : {'C', 'F'}, optional
    Whether to store the result in C- or Fortran-contiguous order,
    default is 'C'.
Returns
-------
out : matrix
    Zero matrix of given shape, dtype, and order.
See Also
--------
numpy.zeros : Equivalent array function.
matlib.ones : Return a matrix of ones.
Notes
-----
If `shape` has length one i.e. ``(N,)``, or is a scalar ``N``,
`out` becomes a single row matrix of shape ``(1,N)``.
Examples
--------
>>> import numpy.matlib
>>> np.matlib.zeros((2, 3))
matrix([[0.,  0.,  0.],
        [0.,  0.,  0.]])
>>> np.matlib.zeros(2)
matrix([[0.,  0.]])
Definition at line 107 of file matlib.py.
Variable Documentation
__all__
numpy.matlib.__all__ = np.__all__[:] private
Definition at line 21 of file matlib.py.
__version__
numpy.matlib.__version__ = np.__version__ private
Definition at line 19 of file matlib.py.
PendingDeprecationWarning
numpy.matlib.PendingDeprecationWarning
Definition at line 10 of file matlib.py.
stacklevel
numpy.matlib.stacklevel
Definition at line 10 of file matlib.py.