Code Cloning Analysis: fontTools.ttLib.tables.E_B_L_C_.eblc_index_sub_table_5 Class Reference
fontTools.ttLib.tables.E_B_L_C_.eblc_index_sub_table_5 Class Reference
Public Member Functions
decompile (self)
compile (self, ttFont)
Public Member Functions inherited from fontTools.ttLib.tables.E_B_L_C_.FixedSizeIndexSubTableMixin
writeMetrics (self, writer, ttFont)
readMetrics (self, name, attrs, content, ttFont)
padBitmapData (self, data)
Public Member Functions inherited from fontTools.ttLib.tables.E_B_L_C_.EblcIndexSubTable
__init__ (self, data, ttFont)
__getattr__ (self, attr)
ensureDecompiled (self, recurse=False)
toXML (self, writer, ttFont)
fromXML (self, name, attrs, content, ttFont)
writeMetrics (self, writer, ttFont)
readMetrics (self, name, attrs, content, ttFont)
padBitmapData (self, data)
removeSkipGlyphs (self)
Public Attributes
int origDataLen = 0
Public Attributes inherited from fontTools.ttLib.tables.E_B_L_C_.FixedSizeIndexSubTableMixin
imageSize = safeEval(attrs["value"])
metrics = BigGlyphMetrics()
Public Attributes inherited from fontTools.ttLib.tables.E_B_L_C_.EblcIndexSubTable
data = data
ttFont = ttFont
indexFormat
imageFormat
imageDataOffset
firstGlyphIndex
lastGlyphIndex
list names = map(ttFont.getGlyphID, self.names)
locations = list(map(list, zip(*dataPairs)))
Detailed Description
Definition at line 677 of file E_B_L_C_.py.
Member Function Documentation
compile()
fontTools.ttLib.tables.E_B_L_C_.eblc_index_sub_table_5.compile (self, ttFont)
Reimplemented from fontTools.ttLib.tables.E_B_L_C_.EblcIndexSubTable.
Definition at line 698 of file E_B_L_C_.py.
Referenced by fontTools.ttLib.tables.TupleVariation.TupleVariation.getCoordWidth(), and PIL.FontFile.FontFile.save().
decompile()
fontTools.ttLib.tables.E_B_L_C_.eblc_index_sub_table_5.decompile (self)
Definition at line 678 of file E_B_L_C_.py.
Referenced by fontTools.ttLib.tables._c_m_a_p.CmapSubtable.newSubtable().
Member Data Documentation
origDataLen
int fontTools.ttLib.tables.E_B_L_C_.eblc_index_sub_table_5.origDataLen = 0
Definition at line 679 of file E_B_L_C_.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ttLib/tables/E_B_L_C_.py