Code Cloning Analysis: pip._vendor.tenacity.wait.wait_exponential_jitter Class Reference
pip._vendor.tenacity.wait.wait_exponential_jitter Class Reference
Public Member Functions
None __init__ (self, float initial=1, float max=_utils.MAX_WAIT, float exp_base=2, float jitter=1)
float __call__ (self, "RetryCallState" retry_state)
Public Member Functions inherited from pip._vendor.tenacity.wait.wait_base
float __call__ (self, "RetryCallState" retry_state)
"wait_combine" __add__ (self, "wait_base" other)
typing.Union["wait_combine", "wait_base"] __radd__ (self, "wait_base" other)
Public Attributes
initial = initial
max = max
exp_base = exp_base
jitter = jitter
Detailed Description
Wait strategy that applies exponential backoff and jitter.
It allows for a customized initial wait, maximum wait and jitter.
This implements the strategy described here:
https://cloud.google.com/storage/docs/retry-strategy
The wait time is min(initial * 2**n + random.uniform(0, jitter), maximum)
where n is the retry count.
Definition at line 197 of file wait.py.
Constructor & Destructor Documentation
__init__()
None pip._vendor.tenacity.wait.wait_exponential_jitter.__init__ (self, float initial = 1, float max = _utils.MAX_WAIT, float exp_base = 2, float jitter = 1)
Definition at line 209 of file wait.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
__call__()
float pip._vendor.tenacity.wait.wait_exponential_jitter.__call__ (self, "RetryCallState" retry_state)
Definition at line 221 of file wait.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), and scipy.interpolate._fitpack2.SphereBivariateSpline.ev().
Member Data Documentation
exp_base
pip._vendor.tenacity.wait.wait_exponential_jitter.exp_base = exp_base
Definition at line 218 of file wait.py.
initial
pip._vendor.tenacity.wait.wait_exponential_jitter.initial = initial
Definition at line 216 of file wait.py.
jitter
pip._vendor.tenacity.wait.wait_exponential_jitter.jitter = jitter
Definition at line 219 of file wait.py.
Referenced by sklearn.linear_model._least_angle.Lars.fit().
max
pip._vendor.tenacity.wait.wait_exponential_jitter.max = max
Definition at line 217 of file wait.py.
Referenced by pyparsing.core.DelimitedList.__init__(), and numpy.ma.core.MaskedArray.ptp().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pip/_vendor/tenacity/wait.py