Code Cloning Analysis: fontTools.misc.plistlib Namespace Reference
fontTools.misc.plistlib Namespace Reference
Classes
class Data
class PlistTarget
Functions
datetime _date_from_string (str s)
str _date_to_string (datetime d)
bytes _encode_base64 (bytes data, Optional[int] maxlinelength=76, int indent_level=1)
None start_dict (PlistTarget self)
None end_dict (PlistTarget self)
None end_key (PlistTarget self)
None start_array (PlistTarget self)
None end_array (PlistTarget self)
None end_true (PlistTarget self)
None end_false (PlistTarget self)
None end_integer (PlistTarget self)
None end_real (PlistTarget self)
None end_string (PlistTarget self)
None end_data (PlistTarget self)
None end_date (PlistTarget self)
etree.Element _string_element (str value, SimpleNamespace ctx)
etree.Element _bool_element (bool value, SimpleNamespace ctx)
etree.Element _integer_element (int value, SimpleNamespace ctx)
etree.Element _real_element (float value, SimpleNamespace ctx)
etree.Element _dict_element (Mapping[str, PlistEncodable] d, SimpleNamespace ctx)
etree.Element _array_element (Sequence[PlistEncodable] array, SimpleNamespace ctx)
etree.Element _date_element (datetime date, SimpleNamespace ctx)
etree.Element _data_element (bytes data, SimpleNamespace ctx)
etree.Element _string_or_data_element (bytes raw_bytes, SimpleNamespace ctx)
etree.Element _make_element (PlistEncodable value, SimpleNamespace ctx)
etree.Element totree (PlistEncodable value, bool sort_keys=True, bool skipkeys=False, Optional[bool] use_builtin_types=None, bool pretty_print=True, int indent_level=1)
Any fromtree (etree.Element tree, Optional[bool] use_builtin_types=None, Type[MutableMapping[str, Any]] dict_type=dict)
Any load (IO[bytes] fp, Optional[bool] use_builtin_types=None, Type[MutableMapping[str, Any]] dict_type=dict)
Any loads (bytes value, Optional[bool] use_builtin_types=None, Type[MutableMapping[str, Any]] dict_type=dict)
None dump (PlistEncodable value, IO[bytes] fp, bool sort_keys=True, bool skipkeys=False, Optional[bool] use_builtin_types=None, bool pretty_print=True)
bytes dumps (PlistEncodable value, bool sort_keys=True, bool skipkeys=False, Optional[bool] use_builtin_types=None, bool pretty_print=True)
Variables
bool USE_BUILTIN_TYPES = True
str XML_DECLARATION = b"""<?xml version='1.0' encoding='UTF-8'?>"""
tuple PLIST_DOCTYPE
_date_parser
PlistEncodable
dict _TARGET_START_HANDLERS
dict _TARGET_END_HANDLERS
current_key
_use_builtin_types
Function Documentation
_array_element()
etree.Element fontTools.misc.plistlib._array_element (Sequence[PlistEncodable] array, SimpleNamespace ctx) protected
Definition at line 376 of file __init__.py.
_bool_element()
etree.Element fontTools.misc.plistlib._bool_element (bool value, SimpleNamespace ctx) protected
Definition at line 336 of file __init__.py.
_data_element()
etree.Element fontTools.misc.plistlib._data_element (bytes data, SimpleNamespace ctx) protected
Definition at line 395 of file __init__.py.
_date_element()
etree.Element fontTools.misc.plistlib._date_element (datetime date, SimpleNamespace ctx) protected
Definition at line 389 of file __init__.py.
_date_from_string()
datetime fontTools.misc.plistlib._date_from_string (str s) protected
Definition at line 65 of file __init__.py.
_date_to_string()
str fontTools.misc.plistlib._date_to_string (datetime d) protected
Definition at line 81 of file __init__.py.
_dict_element()
etree.Element fontTools.misc.plistlib._dict_element (Mapping[str, PlistEncodable] d, SimpleNamespace ctx) protected
Definition at line 356 of file __init__.py.
_encode_base64()
bytes fontTools.misc.plistlib._encode_base64 (bytes data, Optional[int] maxlinelength = 76, int indent_level = 1) protected
Definition at line 128 of file __init__.py.
_integer_element()
etree.Element fontTools.misc.plistlib._integer_element (int value, SimpleNamespace ctx) protected
Definition at line 342 of file __init__.py.
_make_element()
etree.Element fontTools.misc.plistlib._make_element (PlistEncodable value, SimpleNamespace ctx) protected
Definition at line 425 of file __init__.py.
_real_element()
etree.Element fontTools.misc.plistlib._real_element (float value, SimpleNamespace ctx) protected
Definition at line 350 of file __init__.py.
_string_element()
etree.Element fontTools.misc.plistlib._string_element (str value, SimpleNamespace ctx) protected
Definition at line 330 of file __init__.py.
_string_or_data_element()
etree.Element fontTools.misc.plistlib._string_or_data_element (bytes raw_bytes, SimpleNamespace ctx) protected
Definition at line 406 of file __init__.py.
dump()
None fontTools.misc.plistlib.dump (PlistEncodable value, IO[bytes] fp, bool sort_keys = True, bool skipkeys = False, Optional[bool] use_builtin_types = None, bool pretty_print = True)
Write a Python object to a plist file.
Args:
    value: An object to write.
    fp: A file opened for writing.
    sort_keys (bool): Whether keys of dictionaries should be sorted.
    skipkeys (bool): Whether to silently skip non-string dictionary
        keys.
    use_builtin_types (bool): If true, byte strings will be
        encoded in Base-64 and wrapped in a ``data`` tag; if
        false, they will be either stored as ASCII strings or an
        exception raised if they cannot be represented. Defaults
    pretty_print (bool): Whether to indent the output.
    indent_level (int): Level of indentation when serializing.
Raises:
    ``TypeError``
        if non-string dictionary keys are serialized
        and ``skipkeys`` is false.
    ``ValueError``
        if non-representable binary data is present
        and `use_builtin_types` is false.
Definition at line 580 of file __init__.py.
References totree().
Referenced by dumps().
dumps()
bytes fontTools.misc.plistlib.dumps (PlistEncodable value, bool sort_keys = True, bool skipkeys = False, Optional[bool] use_builtin_types = None, bool pretty_print = True)
Write a Python object to a string in plist format.
Args:
    value: An object to write.
    sort_keys (bool): Whether keys of dictionaries should be sorted.
    skipkeys (bool): Whether to silently skip non-string dictionary
        keys.
    use_builtin_types (bool): If true, byte strings will be
        encoded in Base-64 and wrapped in a ``data`` tag; if
        false, they will be either stored as strings or an
        exception raised if they cannot be represented. Defaults
    pretty_print (bool): Whether to indent the output.
    indent_level (int): Level of indentation when serializing.
Returns:
    string: A plist representation of the Python object.
Raises:
    ``TypeError``
        if non-string dictionary keys are serialized
        and ``skipkeys`` is false.
    ``ValueError``
        if non-representable binary data is present
        and `use_builtin_types` is false.
Definition at line 640 of file __init__.py.
References dump().
end_array()
None fontTools.misc.plistlib.end_array (PlistTarget self)
Definition at line 273 of file __init__.py.
end_data()
None fontTools.misc.plistlib.end_data (PlistTarget self)
Definition at line 297 of file __init__.py.
end_date()
None fontTools.misc.plistlib.end_date (PlistTarget self)
Definition at line 304 of file __init__.py.
end_dict()
None fontTools.misc.plistlib.end_dict (PlistTarget self)
Definition at line 255 of file __init__.py.
end_false()
None fontTools.misc.plistlib.end_false (PlistTarget self)
Definition at line 281 of file __init__.py.
end_integer()
None fontTools.misc.plistlib.end_integer (PlistTarget self)
Definition at line 285 of file __init__.py.
end_key()
None fontTools.misc.plistlib.end_key (PlistTarget self)
Definition at line 261 of file __init__.py.
end_real()
None fontTools.misc.plistlib.end_real (PlistTarget self)
Definition at line 289 of file __init__.py.
end_string()
None fontTools.misc.plistlib.end_string (PlistTarget self)
Definition at line 293 of file __init__.py.
end_true()
None fontTools.misc.plistlib.end_true (PlistTarget self)
Definition at line 277 of file __init__.py.
fromtree()
Any fontTools.misc.plistlib.fromtree (etree.Element tree, Optional[bool] use_builtin_types = None, Type[MutableMapping[str, Any]] dict_type = dict)
Convert an XML tree to a plist structure.
Args:
    tree: An ``etree`` ``Element``.
    use_builtin_types: If True, binary data is deserialized to
        bytes strings. If False, it is wrapped in :py:class:`Data`
        objects. Defaults to True if not provided. Deprecated.
    dict_type: What type to use for dictionaries.
Returns: An object (usually a dictionary).
Definition at line 493 of file __init__.py.
load()
Any fontTools.misc.plistlib.load (IO[bytes] fp, Optional[bool] use_builtin_types = None, Type[MutableMapping[str, Any]] dict_type = dict)
Load a plist file into an object.
Args:
    fp: An opened file.
    use_builtin_types: If True, binary data is deserialized to
        bytes strings. If False, it is wrapped in :py:class:`Data`
        objects. Defaults to True if not provided. Deprecated.
    dict_type: What type to use for dictionaries.
Returns:
    An object (usually a dictionary) representing the top level of
    the plist file.
Definition at line 525 of file __init__.py.
Referenced by loads().
loads()
Any fontTools.misc.plistlib.loads (bytes value, Optional[bool] use_builtin_types = None, Type[MutableMapping[str, Any]] dict_type = dict)
Load a plist file from a string into an object.
Args:
    value: A bytes string containing a plist.
    use_builtin_types: If True, binary data is deserialized to
        bytes strings. If False, it is wrapped in :py:class:`Data`
        objects. Defaults to True if not provided. Deprecated.
    dict_type: What type to use for dictionaries.
Returns:
    An object (usually a dictionary) representing the top level of
    the plist file.
Definition at line 557 of file __init__.py.
References load().
start_array()
None fontTools.misc.plistlib.start_array (PlistTarget self)
Definition at line 267 of file __init__.py.
start_dict()
None fontTools.misc.plistlib.start_dict (PlistTarget self)
Definition at line 249 of file __init__.py.
totree()
etree.Element fontTools.misc.plistlib.totree (PlistEncodable value, bool sort_keys = True, bool skipkeys = False, Optional[bool] use_builtin_types = None, bool pretty_print = True, int indent_level = 1)
Convert a value derived from a plist into an XML tree.
Args:
    value: Any kind of value to be serialized to XML.
    sort_keys: Whether keys of dictionaries should be sorted.
    skipkeys (bool): Whether to silently skip non-string dictionary
        keys.
    use_builtin_types (bool): If true, byte strings will be
        encoded in Base-64 and wrapped in a ``data`` tag; if
        false, they will be either stored as ASCII strings or an
        exception raised if they cannot be decoded as such. Defaults
        to ``True`` if not present. Deprecated.
    pretty_print (bool): Whether to indent the output.
    indent_level (int): Level of indentation when serializing.
Returns: an ``etree`` ``Element`` object.
Raises:
    ``TypeError``
        if non-string dictionary keys are serialized
        and ``skipkeys`` is false.
    ``ValueError``
        if non-ASCII binary data is present
        and `use_builtin_types` is false.
Definition at line 446 of file __init__.py.
Referenced by dump().
Variable Documentation
_date_parser
fontTools.misc.plistlib._date_parser protected
Initial value:
=  re.compile(
    r"(?P<year>\d\d\d\d)"
    r"(?:-(?P<month>\d\d)"
    r"(?:-(?P<day>\d\d)"
    r"(?:T(?P<hour>\d\d)"
    r"(?::(?P<minute>\d\d)"
    r"(?::(?P<second>\d\d))"
    r"?)?)?)?)?Z",
    re.ASCII,
)
Definition at line 53 of file __init__.py.
_TARGET_END_HANDLERS
dict fontTools.misc.plistlib._TARGET_END_HANDLERS protected
Initial value:
=  {
    "dict": end_dict,
    "array": end_array,
    "key": end_key,
    "true": end_true,
    "false": end_false,
    "integer": end_integer,
    "real": end_real,
    "string": end_string,
    "data": end_data,
    "date": end_date,
}
Definition at line 313 of file __init__.py.
_TARGET_START_HANDLERS
dict fontTools.misc.plistlib._TARGET_START_HANDLERS protected
Initial value:
=  {
    "dict": start_dict,
    "array": start_array,
}
Definition at line 308 of file __init__.py.
_use_builtin_types
fontTools.misc.plistlib._use_builtin_types protected
Definition at line 298 of file __init__.py.
current_key
fontTools.misc.plistlib.current_key
Definition at line 256 of file __init__.py.
PLIST_DOCTYPE
tuple fontTools.misc.plistlib.PLIST_DOCTYPE
Initial value:
=  (
    b'<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" '
    b'"http://www.apple.com/DTDs/PropertyList-1.0.dtd">'
)
Definition at line 45 of file __init__.py.
PlistEncodable
fontTools.misc.plistlib.PlistEncodable
Initial value:
=  Union[
    bool,
    bytes,
    Data,
    datetime,
    float,
    Integral,
    Mapping[str, Any],
    Sequence[Any],
    str,
]
Definition at line 148 of file __init__.py.
USE_BUILTIN_TYPES
bool fontTools.misc.plistlib.USE_BUILTIN_TYPES = True
Definition at line 41 of file __init__.py.
XML_DECLARATION
str fontTools.misc.plistlib.XML_DECLARATION = b"""<?xml version='1.0' encoding='UTF-8'?>"""
Definition at line 43 of file __init__.py.