Code Cloning Analysis: sklearn.linear_model._theil_sen Namespace Reference
sklearn.linear_model._theil_sen Namespace Reference
Classes
class TheilSenRegressor
Functions
_modified_weiszfeld_step (X, x_old)
_spatial_median (X, max_iter=300, tol=1.0e-3)
_breakdown_point (n_samples, n_subsamples)
_lstsq (X, y, indices, fit_intercept)
Variables
_EPSILON = np.finfo(np.double).eps
Detailed Description
A Theil-Sen Estimator for Multiple Linear Regression Model
Function Documentation
_breakdown_point()
sklearn.linear_model._theil_sen._breakdown_point (n_samples, n_subsamples) protected
Approximation of the breakdown point.
Parameters
----------
n_samples : int
    Number of samples.
n_subsamples : int
    Number of subsamples to consider.
Returns
-------
breakdown_point : float
    Approximation of breakdown point.
Definition at line 136 of file _theil_sen.py.
Referenced by sklearn.linear_model._theil_sen.TheilSenRegressor.fit().
_lstsq()
sklearn.linear_model._theil_sen._lstsq (X, y, indices, fit_intercept) protected
Least Squares Estimator for TheilSenRegressor class.
This function calculates the least squares method on a subset of rows of X
and y defined by the indices array. Optionally, an intercept column is
added if intercept is set to true.
Parameters
----------
X : array-like of shape (n_samples, n_features)
    Design matrix, where `n_samples` is the number of samples and
    `n_features` is the number of features.
y : ndarray of shape (n_samples,)
    Target vector, where `n_samples` is the number of samples.
indices : ndarray of shape (n_subpopulation, n_subsamples)
    Indices of all subsamples with respect to the chosen subpopulation.
fit_intercept : bool
    Fit intercept or not.
Returns
-------
weights : ndarray of shape (n_subpopulation, n_features + intercept)
    Solution matrix of n_subpopulation solved least square problems.
Definition at line 163 of file _theil_sen.py.
_modified_weiszfeld_step()
sklearn.linear_model._theil_sen._modified_weiszfeld_step (X, x_old) protected
Modified Weiszfeld step.
This function defines one iteration step in order to approximate the
spatial median (L1 median). It is a form of an iteratively re-weighted
least squares method.
Parameters
----------
X : array-like of shape (n_samples, n_features)
    Training vector, where `n_samples` is the number of samples and
    `n_features` is the number of features.
x_old : ndarray of shape = (n_features,)
    Current start vector.
Returns
-------
x_new : ndarray of shape (n_features,)
    New iteration step.
References
----------
- On Computation of Spatial Median for Robust Data Mining, 2005
  T. Kärkkäinen and S. Äyrämö
  http://users.jyu.fi/~samiayr/pdf/ayramo_eurogen05.pdf
Definition at line 29 of file _theil_sen.py.
Referenced by _spatial_median().
_spatial_median()
sklearn.linear_model._theil_sen._spatial_median (X, max_iter = 300, tol = 1.0e-3) protected
Spatial median (L1 median).
The spatial median is member of a class of so-called M-estimators which
are defined by an optimization problem. Given a number of p points in an
n-dimensional space, the point x minimizing the sum of all distances to the
p other points is called spatial median.
Parameters
----------
X : array-like of shape (n_samples, n_features)
    Training vector, where `n_samples` is the number of samples and
    `n_features` is the number of features.
max_iter : int, default=300
    Maximum number of iterations.
tol : float, default=1.e-3
    Stop the algorithm if spatial_median has converged.
Returns
-------
spatial_median : ndarray of shape = (n_features,)
    Spatial median.
n_iter : int
    Number of iterations needed.
References
----------
- On Computation of Spatial Median for Robust Data Mining, 2005
  T. Kärkkäinen and S. Äyrämö
  http://users.jyu.fi/~samiayr/pdf/ayramo_eurogen05.pdf
Definition at line 80 of file _theil_sen.py.
References _modified_weiszfeld_step().
Referenced by sklearn.linear_model._theil_sen.TheilSenRegressor.fit().
Variable Documentation
_EPSILON
sklearn.linear_model._theil_sen._EPSILON = np.finfo(np.double).eps protected
Definition at line 26 of file _theil_sen.py.