Code Cloning Analysis: sklearn.model_selection._split.RepeatedStratifiedKFold Class Reference
sklearn.model_selection._split.RepeatedStratifiedKFold Class Reference
Public Member Functions
__init__ (self, *, n_splits=5, n_repeats=10, random_state=None)
split (self, X, y, groups=None)
Public Member Functions inherited from sklearn.model_selection._split._RepeatedSplits
__init__ (self, cv, *, n_repeats=10, random_state=None, **cvargs)
get_n_splits (self, X=None, y=None, groups=None)
__repr__ (self)
Additional Inherited Members
Public Attributes inherited from sklearn.model_selection._split._RepeatedSplits
cv = cv
n_repeats = n_repeats
random_state = random_state
cvargs = cvargs
Detailed Description
Repeated class-wise stratified K-Fold cross validator.
Repeats Stratified K-Fold n times with different randomization in each
repetition.
Read more in the :ref:`User Guide <repeated_k_fold>`.
.. note::
    Stratification on the class label solves an engineering problem rather
    than a statistical one. See :ref:`stratification` for more details.
Parameters
----------
n_splits : int, default=5
    Number of folds. Must be at least 2.
n_repeats : int, default=10
    Number of times cross-validator needs to be repeated.
random_state : int, RandomState instance or None, default=None
    Controls the generation of the random states for each repetition.
    Pass an int for reproducible output across multiple function calls.
    See :term:`Glossary <random_state>`.
Examples
--------
>>> import numpy as np
>>> from sklearn.model_selection import RepeatedStratifiedKFold
>>> X = np.array([[1, 2], [3, 4], [1, 2], [3, 4]])
>>> y = np.array([0, 0, 1, 1])
>>> rskf = RepeatedStratifiedKFold(n_splits=2, n_repeats=2,
...     random_state=36851234)
>>> rskf.get_n_splits(X, y)
4
>>> print(rskf)
RepeatedStratifiedKFold(n_repeats=2, n_splits=2, random_state=36851234)
>>> for i, (train_index, test_index) in enumerate(rskf.split(X, y)):
...     print(f"Fold {i}:")
...     print(f"  Train: index={train_index}")
...     print(f"  Test:  index={test_index}")
...
Fold 0:
  Train: index=[1 2]
  Test:  index=[0 3]
Fold 1:
  Train: index=[0 3]
  Test:  index=[1 2]
Fold 2:
  Train: index=[1 3]
  Test:  index=[0 2]
Fold 3:
  Train: index=[0 2]
  Test:  index=[1 3]
Notes
-----
Randomized CV splitters may return different results for each call of
split. You can make the results identical by setting `random_state`
to an integer.
See Also
--------
RepeatedKFold : Repeats K-Fold n times.
Definition at line 1741 of file _split.py.
Constructor & Destructor Documentation
__init__()
sklearn.model_selection._split.RepeatedStratifiedKFold.__init__ (self, * , n_splits = 5, n_repeats = 10, random_state = None)
Definition at line 1808 of file _split.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params().
Member Function Documentation
split()
sklearn.model_selection._split.RepeatedStratifiedKFold.split (self, X, y, groups = None)
Generate indices to split data into training and test set.
Parameters
----------
X : array-like of shape (n_samples, n_features)
    Training data, where `n_samples` is the number of samples
    and `n_features` is the number of features.
    Note that providing ``y`` is sufficient to generate the splits and
    hence ``np.zeros(n_samples)`` may be used as a placeholder for
    ``X`` instead of actual training data.
y : array-like of shape (n_samples,)
    The target variable for supervised learning problems.
    Stratification is done based on the y labels.
groups : object
    Always ignored, exists for compatibility.
Yields
------
train : ndarray
    The training set indices for that split.
test : ndarray
    The testing set indices for that split.
Notes
-----
Randomized CV splitters may return different results for each call of
split. You can make the results identical by setting `random_state`
to an integer.
Reimplemented from sklearn.model_selection._split._UnsupportedGroupCVMixin.
Definition at line 1816 of file _split.py.
References split().
Referenced by split().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/sklearn/model_selection/_split.py