Code Cloning Analysis: fontTools.voltLib.ast.PositionAdjustPairDefinition Class Reference
fontTools.voltLib.ast.PositionAdjustPairDefinition Class Reference
Public Member Functions
__init__ (self, coverages_1, coverages_2, adjust_pair, location=None)
__str__ (self)
Public Member Functions inherited from fontTools.voltLib.ast.Element
__init__ (self, location=None)
build (self, builder)
__str__ (self)
Public Attributes
coverages_1 = coverages_1
coverages_2 = coverages_2
adjust_pair = adjust_pair
Public Attributes inherited from fontTools.voltLib.ast.Element
location = location
Detailed Description
Definition at line 362 of file ast.py.
Constructor & Destructor Documentation
__init__()
fontTools.voltLib.ast.PositionAdjustPairDefinition.__init__ (self, coverages_1, coverages_2, adjust_pair, location = None)
Definition at line 363 of file ast.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__str__()
fontTools.voltLib.ast.PositionAdjustPairDefinition.__str__ (self)
Definition at line 369 of file ast.py.
Referenced by numpy.polynomial._polybase.ABCPolyBase._get_coefficients().
Member Data Documentation
adjust_pair
fontTools.voltLib.ast.PositionAdjustPairDefinition.adjust_pair = adjust_pair
Definition at line 367 of file ast.py.
coverages_1
fontTools.voltLib.ast.PositionAdjustPairDefinition.coverages_1 = coverages_1
Definition at line 365 of file ast.py.
coverages_2
fontTools.voltLib.ast.PositionAdjustPairDefinition.coverages_2 = coverages_2
Definition at line 366 of file ast.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/voltLib/ast.py