Code Cloning Analysis: matplotlib.testing.jpl_units.EpochConverter.EpochConverter Class Reference
matplotlib.testing.jpl_units.EpochConverter.EpochConverter Class Reference
Static Public Member Functions
axisinfo (unit, axis)
float2epoch (value, unit)
epoch2float (value, unit)
duration2float (value)
convert (value, unit, axis)
default_units (value, axis)
Static Public Attributes
float jdRef = 1721425.5
Detailed Description
Provides Matplotlib conversion functionality for Monte Epoch and Duration
classes.
Definition at line 9 of file EpochConverter.py.
Member Function Documentation
axisinfo()
matplotlib.testing.jpl_units.EpochConverter.EpochConverter.axisinfo (unit, axis) static
Return an `.AxisInfo` for the axis with the specified units.
Reimplemented from matplotlib.units.ConversionInterface.
Definition at line 18 of file EpochConverter.py.
convert()
matplotlib.testing.jpl_units.EpochConverter.EpochConverter.convert (obj, unit, axis) static
Convert *obj* using *unit* for the specified *axis*.
If *obj* is a sequence, return the converted sequence.  The output must
be a sequence of scalars that can be used by the numpy array layer.
Reimplemented from matplotlib.units.ConversionInterface.
Definition at line 73 of file EpochConverter.py.
Referenced by pandas.core.computation.engines.NumExprEngine._evaluate(), pandas.core.internals.blocks.Block.convert(), PIL.Image.Image.reduce(), PIL.Image.Image.resize(), and PIL.Image.Image.transform().
default_units()
matplotlib.testing.jpl_units.EpochConverter.EpochConverter.default_units (x, axis) static
Return the default unit for *x* or ``None`` for the given axis.
Reimplemented from matplotlib.units.ConversionInterface.
Definition at line 89 of file EpochConverter.py.
duration2float()
matplotlib.testing.jpl_units.EpochConverter.EpochConverter.duration2float (value) static
Convert a Duration value to a float suitable for plotting as a python
datetime object.
= INPUT VARIABLES
- value    A Duration or list of Durations that need to be converted.
= RETURN VALUE
- Returns the value parameter converted to floats.
Definition at line 59 of file EpochConverter.py.
epoch2float()
matplotlib.testing.jpl_units.EpochConverter.EpochConverter.epoch2float (value, unit) static
Convert an Epoch value to a float suitable for plotting as a python
datetime object.
= INPUT VARIABLES
- value    An Epoch or list of Epochs that need to be converted.
- unit     The units to use for an axis with Epoch data.
= RETURN VALUE
- Returns the value parameter converted to floats.
Definition at line 44 of file EpochConverter.py.
float2epoch()
matplotlib.testing.jpl_units.EpochConverter.EpochConverter.float2epoch (value, unit) static
Convert a Matplotlib floating-point date into an Epoch of the specified
units.
= INPUT VARIABLES
- value     The Matplotlib floating-point date.
- unit      The unit system to use for the Epoch.
= RETURN VALUE
- Returns the value converted to an Epoch in the specified time system.
Definition at line 25 of file EpochConverter.py.
Member Data Documentation
jdRef
float matplotlib.testing.jpl_units.EpochConverter.EpochConverter.jdRef = 1721425.5 static
Definition at line 15 of file EpochConverter.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/testing/jpl_units/EpochConverter.py