Code Cloning Analysis: fontTools.subset Namespace Reference
fontTools.subset Namespace Reference
Namespaces
namespace util
Classes
class Options
class Subsetter
Functions
_log_glyphs (self, glyphs, font=None)
_dict_subset (d, glyphs)
_list_subset (l, indices)
intersect (self, glyphs)
intersect_glyphs (self, glyphs)
subset (self, glyphs)
remap (self, coverage_map)
intersect_class (self, glyphs, klass)
subset (self, glyphs, remap=False, useClass0=True)
closure_glyphs (self, s, cur_glyphs)
subset_glyphs (self, s)
is_hinting (self)
prune_hints (self)
prune_post_subset (self, font, options)
subset_lookups (self, lookup_indices)
collect_lookups (self)
may_have_non_1to1 (self)
__subset_classify_context (self)
neuter_lookups (self, lookup_indices)
closure_lookups (self, lookup_indices)
subset_lookups (self, lookup_indices)
collect_lookups (self, feature_indices)
subset_features (self, feature_indices)
collect_features (self)
subset_features (self, feature_indices, keepEmptyDefaultLangSys=False)
subset_glyphs (self, s)
closure_glyphs (self, s)
retain_empty_scripts (self)
prune_lookups (self, remap=True)
subset_feature_tags (self, feature_tags)
subset_script_tags (self, tags)
prune_features (self)
prune_pre_subset (self, font, options)
remove_redundant_langsys (self)
_pruneGDEF (font)
_remap_index_map (s, varidx_map, table_map)
_paint_glyph_names (paint, colr)
remapComponentsFast (self, glyphidmap)
None _remap_select_name_ids (ttLib.TTFont font, set[int] needRemapping)
load_font (fontFile, options, checkChecksums=0, dontLoadGlyphNames=False, lazy=True)
save_font (font, outfile, options)
parse_unicodes (s)
parse_gids (s)
parse_glyphs (s)
usage ()
main (args=None)
Variables
str __usage__ = "fonttools subset font-file [glyph...] [--option=value]..."
tuple __doc__
log = logging.getLogger("fontTools.subset")
list glyphs
timer = Timer(logger=logging.getLogger("fontTools.subset.timer"))
dict NAME_IDS_TO_OBFUSCATE = {1, 2, 3, 4, 6, 16, 17, 18}
list __all__
dict classDefs
dict mapping
dict alternates
dict ligatures = {g: v for g, v in self.ligatures.items() if g in s.glyphs}
int Format = 1:
Substitute = _list_subset(self.Substitute, indices)
GlyphCount = len(self.Substitute)
list Value = [values[i] for i in indices if i < count]
ValueCount = len(self.Value)
int ValueFormat = 0
list PairSet = [pairs[i] for i in indices if i < count]
PairSetCount = len(self.PairSet)
list Class1Record = [self.Class1Record[i] for i in class1_map]
Class1Count = len(class1_map)
Class2Count = len(class2_map)
int ValueFormat1 = 0
ValueFormat2 = r.Value2.getEffectiveFormat()
list EntryExitRecord = [records[i] for i in indices if i < count]
EntryExitCount = len(self.EntryExitRecord)
ClassCount = len(class_indices)
Typ = Typ
Type = Type
Chain = Chain
ChainTyp = ChainTyp
InputIdx = InputIdx
DataLen = DataLen
str LookupRecord = Type + "LookupRecord"
Coverage = ChainCoverage
ContextData = ChainContextData
SetContextData = SetChainContextData
RuleData = ChainRuleData
SetRuleData = ChainSetRuleData
str Rule = ChainTyp + "Rule"
str RuleCount = ChainTyp + "RuleCount"
str RuleSet = ChainTyp + "RuleSet"
str RuleSetCount = ChainTyp + "RuleSetCount"
list Intersect = lambda glyphs, c, r: [r] if r in glyphs else []
str ClassDef = "InputClassDef" if Chain else "ClassDef"
int ClassDefIndex = 1 if Chain else 0
str Input = "Input" if Chain else "Class"
__class__ = "InputCoverage" if Chain else "Coverage"
list SubTable
SubTableCount = len(self.SubTable)
MarkFilteringSet = None
list Lookup
LookupCount = len(self.Lookup)
list LookupListIndex = [l for l in self.LookupListIndex if l in lookup_indices]
FeatureParams = len(self.LookupListIndex)
FeatureRecord
FeatureCount = len(self.FeatureRecord)
list SubstitutionRecord
SubstitutionCount = len(self.SubstitutionRecord)
FeatureVariationRecord
FeatureVariationCount = len(self.FeatureVariationRecord)
int ReqFeatureIndex = feature_indices.index(self.ReqFeatureIndex)
list FeatureIndex = [f for f in self.FeatureIndex if f in feature_indices]
DefaultLangSys = None
list LangSysRecord
LangSysCount = len(self.LangSysRecord)
list ScriptRecord
ScriptCount = len(self.ScriptRecord)
list strikes
list strikeData = [strike for strike in strikeData if strike]
table = _uniq_sort(feature_indices)
list kernTables = [t for t in self.kernTables if hasattr(t, "kernTable")]
metrics = _dict_subset(self.metrics, s.glyphs)
dict hdmx = {sz: _dict_subset(l, s.glyphs) for sz, l in self.hdmx.items()}
variations = _dict_subset(self.variations, s.glyphs)
glyphCount = len(self.variations)
dict VOriginRecords
numVertOriginYMetrics = len(self.VOriginRecords)
float formatType = 3.0
list extraNames = []
dict ColorLayers = self._decompileColorLayersV0(self.table)
dict ColorLayersV1
int version = 0:
palettes
numPaletteEntries = len(self.palettes[0])
paletteEntryLabels = []
MathGlyphVariantRecord
GlyphAssembly
VertGlyphCoverage
HorizGlyphCoverage = self.VertGlyphCoverage.intersect(glyphs)
ItalicsCorrection = _list_subset(self.ItalicsCorrection, indices)
ItalicsCorrectionCount = len(self.ItalicsCorrection)
TopAccentAttachment = _list_subset(self.TopAccentAttachment, indices)
TopAccentAttachmentCount = len(self.TopAccentAttachment)
MathKernInfoRecords = _list_subset(self.MathKernInfoRecords, indices)
MathKernCount = len(self.MathKernInfoRecords)
MathItalicsCorrectionInfo
MathTopAccentAttachment
MathKernInfo
ExtendedShapeCoverage
VertGlyphConstruction = _list_subset(self.VertGlyphConstruction, indices)
VertGlyphCount = len(self.VertGlyphConstruction)
HorizGlyphConstruction = _list_subset(self.HorizGlyphConstruction, indices)
HorizGlyphCount = len(self.HorizGlyphConstruction)
list glyphOrder
list tables = [t for t in self.tables if t.isUnicode() or t.isSymbol()]
numSubTables = len(self.tables)
int usNumSigs = 0
list signatureRecords = []
int tableVersion = 0x00010000:
int maxZones = 1
int maxTwilightPoints = 0
int maxStorage = 0
int maxFunctionDefs = 0
int maxInstructionDefs = 0
int maxStackElements = 0
int maxSizeOfInstructions = 0
list names = [n for n in self.names if n.nameID in nameIDs]
Function Documentation
__subset_classify_context()
fontTools.subset.__subset_classify_context (self) private
Definition at line 1022 of file __init__.py.
_dict_subset()
fontTools.subset._dict_subset (d, glyphs) protected
Definition at line 474 of file __init__.py.
_list_subset()
fontTools.subset._list_subset (l, indices) protected
Definition at line 478 of file __init__.py.
_log_glyphs()
fontTools.subset._log_glyphs (self, glyphs, font = None) protected
Definition at line 459 of file __init__.py.
_paint_glyph_names()
fontTools.subset._paint_glyph_names (paint, colr) protected
Definition at line 2451 of file __init__.py.
_pruneGDEF()
fontTools.subset._pruneGDEF (font) protected
Definition at line 2124 of file __init__.py.
_remap_index_map()
fontTools.subset._remap_index_map (s, varidx_map, table_map) protected
Definition at line 2293 of file __init__.py.
_remap_select_name_ids()
None fontTools.subset._remap_select_name_ids (ttLib.TTFont font, set[int] needRemapping) protected
Remap a set of IDs so that the originals can be safely scrambled or
dropped.
For each name record whose name id is in the `needRemapping` set, make a copy
and allocate a new unused name id in the font-specific range (> 255).
Finally update references to these in the `fvar` and `STAT` tables.
Definition at line 3049 of file __init__.py.
Referenced by prune_features().
closure_glyphs() [1/2]
fontTools.subset.closure_glyphs (self, s)
Definition at line 1834 of file __init__.py.
closure_glyphs() [2/2]
fontTools.subset.closure_glyphs (self, s, cur_glyphs = None)
Definition at line 553 of file __init__.py.
closure_lookups()
fontTools.subset.closure_lookups (self, lookup_indices)
Returns sorted index of all lookups reachable from lookup_indices.
Definition at line 1601 of file __init__.py.
collect_features()
fontTools.subset.collect_features (self)
Definition at line 1753 of file __init__.py.
collect_lookups() [1/2]
fontTools.subset.collect_lookups (self)
Definition at line 980 of file __init__.py.
collect_lookups() [2/2]
fontTools.subset.collect_lookups (self, feature_indices)
Definition at line 1652 of file __init__.py.
intersect()
fontTools.subset.intersect (self, glyphs)
Returns ascending list of matching coverage values.
Returns ascending list of matching class values.
Definition at line 484 of file __init__.py.
Referenced by prune_features(), subset_glyphs(), and subset_lookups().
intersect_class()
fontTools.subset.intersect_class (self, glyphs, klass)
Returns set of glyphs matching class.
Definition at line 519 of file __init__.py.
intersect_glyphs()
fontTools.subset.intersect_glyphs (self, glyphs)
Returns set of intersecting glyphs.
Definition at line 490 of file __init__.py.
Referenced by subset_lookups().
is_hinting()
fontTools.subset.is_hinting (self)
Definition at line 659 of file __init__.py.
load_font()
fontTools.subset.load_font (fontFile, options, checkChecksums = 0, dontLoadGlyphNames = False, lazy = True)
Definition at line 3696 of file __init__.py.
main()
fontTools.subset.main (args = None)
OpenType font subsetter and optimizer
Definition at line 3775 of file __init__.py.
may_have_non_1to1()
fontTools.subset.may_have_non_1to1 (self)
Definition at line 1002 of file __init__.py.
neuter_lookups()
fontTools.subset.neuter_lookups (self, lookup_indices)
Sets lookups not in lookup_indices to None.
Definition at line 1592 of file __init__.py.
parse_gids()
fontTools.subset.parse_gids (s)
Definition at line 3754 of file __init__.py.
parse_glyphs()
fontTools.subset.parse_glyphs (s)
Definition at line 3765 of file __init__.py.
parse_unicodes()
fontTools.subset.parse_unicodes (s)
Definition at line 3738 of file __init__.py.
prune_features()
fontTools.subset.prune_features (self)
Remove unreferenced features
Definition at line 1982 of file __init__.py.
References _remap_select_name_ids(), intersect(), and subset_glyphs().
prune_hints()
fontTools.subset.prune_hints (self)
Definition at line 664 of file __init__.py.
prune_lookups()
fontTools.subset.prune_lookups (self, remap = True)
Remove (default) or neuter unreferenced lookups
Definition at line 1912 of file __init__.py.
prune_post_subset()
fontTools.subset.prune_post_subset (self, font, options)
Definition at line 687 of file __init__.py.
prune_pre_subset()
fontTools.subset.prune_pre_subset (self, font, options)
Definition at line 1999 of file __init__.py.
remap()
fontTools.subset.remap (self, class_map)
Remaps coverage.
Remaps classes.
Definition at line 504 of file __init__.py.
Referenced by subset_glyphs(), and subset_lookups().
remapComponentsFast()
fontTools.subset.remapComponentsFast (self, glyphidmap)
Definition at line 2788 of file __init__.py.
remove_redundant_langsys()
fontTools.subset.remove_redundant_langsys (self)
Definition at line 2011 of file __init__.py.
retain_empty_scripts()
fontTools.subset.retain_empty_scripts (self)
Definition at line 1875 of file __init__.py.
save_font()
fontTools.subset.save_font (font, outfile, options)
Definition at line 3728 of file __init__.py.
subset() [1/2]
fontTools.subset.subset (self, glyphs)
Returns ascending list of remaining coverage values.
Definition at line 496 of file __init__.py.
subset() [2/2]
fontTools.subset.subset (self, glyphs, remap = False, useClass0 = True)
Returns ascending list of remaining classes.
Definition at line 527 of file __init__.py.
subset_feature_tags()
fontTools.subset.subset_feature_tags (self, feature_tags)
Definition at line 1936 of file __init__.py.
subset_features() [1/2]
fontTools.subset.subset_features (self, feature_indices)
Definition at line 1664 of file __init__.py.
subset_features() [2/2]
fontTools.subset.subset_features (self, feature_indices, keepEmptyDefaultLangSys = False)
Definition at line 1761 of file __init__.py.
subset_glyphs() [1/2]
fontTools.subset.subset_glyphs (self , s)
Returns the indices of nonempty lookups.
Definition at line 558 of file __init__.py.
References intersect(), and remap().
Referenced by prune_features(), and subset_lookups().
subset_glyphs() [2/2]
fontTools.subset.subset_glyphs (self, s)
Returns the indices of nonempty lookups.
Definition at line 1803 of file __init__.py.
subset_lookups() [1/2]
fontTools.subset.subset_lookups (self , lookup_indices)
 "Returns True if feature is non-empty afterwards.
Definition at line 963 of file __init__.py.
References intersect(), intersect_glyphs(), remap(), subset_glyphs(), and subset_lookups().
Referenced by subset_lookups().
subset_lookups() [2/2]
fontTools.subset.subset_lookups (self, lookup_indices)
Returns the indices of nonempty features.
Retains specified lookups, then removes empty features, language
systems, and scripts.
 "Returns True if feature is non-empty afterwards.
Definition at line 1638 of file __init__.py.
subset_script_tags()
fontTools.subset.subset_script_tags (self, tags)
Definition at line 1955 of file __init__.py.
usage()
fontTools.subset.usage ()
Definition at line 3769 of file __init__.py.
Variable Documentation
__all__
list fontTools.subset.__all__ private
Initial value:
=  [
    "Options",
    "Subsetter",
    "load_font",
    "save_font",
    "parse_gids",
    "parse_glyphs",
    "parse_unicodes",
    "main",
]
Definition at line 3920 of file __init__.py.
__class__
fontTools.subset.__class__ = "InputCoverage" if Chain else "Coverage" private
Definition at line 1168 of file __init__.py.
__doc__
tuple fontTools.subset.__doc__ private
Initial value:
=  (
    + __usage__
    +
)
Definition at line 32 of file __init__.py.
__usage__
str fontTools.subset.__usage__ = "fonttools subset font-file [glyph...] [--option=value]..." private
Definition at line 30 of file __init__.py.
alternates
fontTools.subset.alternates
Initial value:
=  {
        g: [v for v in vlist if v in s.glyphs]
        for g, vlist in self.alternates.items()
        if g in s.glyphs and any(v in s.glyphs for v in vlist)
    }
Definition at line 589 of file __init__.py.
Chain
fontTools.subset.Chain = Chain
Definition at line 1043 of file __init__.py.
ChainTyp
fontTools.subset.ChainTyp = ChainTyp
Definition at line 1044 of file __init__.py.
Class1Count
fontTools.subset.Class1Count = len(class1_map)
Definition at line 752 of file __init__.py.
Class1Record
list fontTools.subset.Class1Record = [self.Class1Record[i] for i in class1_map]
Definition at line 749 of file __init__.py.
Class2Count
fontTools.subset.Class2Count = len(class2_map)
Definition at line 753 of file __init__.py.
ClassCount
fontTools.subset.ClassCount = len(class_indices)
Definition at line 837 of file __init__.py.
ClassDef
str fontTools.subset.ClassDef = "InputClassDef" if Chain else "ClassDef"
Definition at line 1160 of file __init__.py.
ClassDefIndex
int fontTools.subset.ClassDefIndex = 1 if Chain else 0
Definition at line 1161 of file __init__.py.
classDefs
dict fontTools.subset.classDefs
Definition at line 522 of file __init__.py.
ColorLayers
fontTools.subset.ColorLayers = self._decompileColorLayersV0(self.table)
Definition at line 2472 of file __init__.py.
ColorLayersV1
dict fontTools.subset.ColorLayersV1
Initial value:
=  {
            rec.BaseGlyph: rec.Paint
            for rec in self.table.BaseGlyphList.BaseGlyphPaintRecord
        }
Definition at line 2473 of file __init__.py.
ContextData
fontTools.subset.ContextData = ChainContextData
Definition at line 1132 of file __init__.py.
Coverage
fontTools.subset.Coverage = ChainCoverage
Definition at line 1131 of file __init__.py.
DataLen
fontTools.subset.DataLen = DataLen
Definition at line 1046 of file __init__.py.
DefaultLangSys
fontTools.subset.DefaultLangSys = None
Definition at line 1767 of file __init__.py.
EntryExitCount
fontTools.subset.EntryExitCount = len(self.EntryExitRecord)
Definition at line 792 of file __init__.py.
EntryExitRecord
list fontTools.subset.EntryExitRecord = [records[i] for i in indices if i < count]
Definition at line 791 of file __init__.py.
ExtendedShapeCoverage
fontTools.subset.ExtendedShapeCoverage
Definition at line 2757 of file __init__.py.
extraNames
list fontTools.subset.extraNames = []
Definition at line 2424 of file __init__.py.
FeatureCount
fontTools.subset.FeatureCount = len(self.FeatureRecord)
Definition at line 1667 of file __init__.py.
FeatureIndex
list fontTools.subset.FeatureIndex = [f for f in self.FeatureIndex if f in feature_indices]
Definition at line 1743 of file __init__.py.
FeatureParams
fontTools.subset.FeatureParams = len(self.LookupListIndex)
Definition at line 1633 of file __init__.py.
FeatureRecord
fontTools.subset.FeatureRecord
Definition at line 1646 of file __init__.py.
FeatureVariationCount
fontTools.subset.FeatureVariationCount = len(self.FeatureVariationRecord)
Definition at line 1733 of file __init__.py.
FeatureVariationRecord
fontTools.subset.FeatureVariationRecord
Definition at line 1722 of file __init__.py.
Format
int fontTools.subset.Format = 1:
Definition at line 625 of file __init__.py.
formatType
float fontTools.subset.formatType = 3.0
Definition at line 2418 of file __init__.py.
GlyphAssembly
fontTools.subset.GlyphAssembly
Definition at line 2613 of file __init__.py.
GlyphCount
fontTools.subset.GlyphCount = len(self.Substitute)
Definition at line 646 of file __init__.py.
glyphCount
fontTools.subset.glyphCount = len(self.variations)
Definition at line 2289 of file __init__.py.
glyphOrder
list fontTools.subset.glyphOrder
Initial value:
=  [
        g for g in self.glyphOrder if g in s.glyphs or g in s.glyphs_emptied
    ]
Definition at line 2857 of file __init__.py.
glyphs
fontTools.subset.glyphs
Definition at line 467 of file __init__.py.
hdmx
fontTools.subset.hdmx = {sz: _dict_subset(l, s.glyphs) for sz, l in self.hdmx.items()}
Definition at line 2223 of file __init__.py.
HorizGlyphConstruction
fontTools.subset.HorizGlyphConstruction = _list_subset(self.HorizGlyphConstruction, indices)
Definition at line 2771 of file __init__.py.
HorizGlyphCount
fontTools.subset.HorizGlyphCount = len(self.HorizGlyphConstruction)
Definition at line 2772 of file __init__.py.
HorizGlyphCoverage
fontTools.subset.HorizGlyphCoverage = self.VertGlyphCoverage.intersect(glyphs)
Definition at line 2629 of file __init__.py.
Input
str fontTools.subset.Input = "Input" if Chain else "Class"
Definition at line 1162 of file __init__.py.
InputIdx
fontTools.subset.InputIdx = InputIdx
Definition at line 1045 of file __init__.py.
Intersect
list fontTools.subset.Intersect = lambda glyphs, c, r: [r] if r in glyphs else []
Definition at line 1148 of file __init__.py.
ItalicsCorrection
fontTools.subset.ItalicsCorrection = _list_subset(self.ItalicsCorrection, indices)
Definition at line 2728 of file __init__.py.
ItalicsCorrectionCount
fontTools.subset.ItalicsCorrectionCount = len(self.ItalicsCorrection)
Definition at line 2729 of file __init__.py.
kernTables
fontTools.subset.kernTables = [t for t in self.kernTables if hasattr(t, "kernTable")]
Definition at line 2188 of file __init__.py.
LangSysCount
fontTools.subset.LangSysCount = len(self.LangSysRecord)
Definition at line 1771 of file __init__.py.
LangSysRecord
list fontTools.subset.LangSysRecord
Initial value:
=  [
        l for l in self.LangSysRecord if l.LangSys.subset_features(feature_indices)
    ]
Definition at line 1768 of file __init__.py.
ligatures
fontTools.subset.ligatures = {g: v for g, v in self.ligatures.items() if g in s.glyphs}
Definition at line 610 of file __init__.py.
log
fontTools.subset.log = logging.getLogger("fontTools.subset")
Definition at line 456 of file __init__.py.
Lookup
list fontTools.subset.Lookup
Definition at line 1568 of file __init__.py.
LookupCount
fontTools.subset.LookupCount = len(self.Lookup)
Definition at line 1586 of file __init__.py.
LookupListIndex
list fontTools.subset.LookupListIndex = [l for l in self.LookupListIndex if l in lookup_indices]
Definition at line 1625 of file __init__.py.
LookupRecord
str fontTools.subset.LookupRecord = Type + "LookupRecord"
Definition at line 1048 of file __init__.py.
mapping
fontTools.subset.mapping
Initial value:
=  {
        g: v for g, v in self.mapping.items() if g in s.glyphs and v in s.glyphs
    }
Definition at line 559 of file __init__.py.
MarkFilteringSet
fontTools.subset.MarkFilteringSet = None
Definition at line 1531 of file __init__.py.
MathGlyphVariantRecord
fontTools.subset.MathGlyphVariantRecord
Definition at line 2611 of file __init__.py.
MathItalicsCorrectionInfo
fontTools.subset.MathItalicsCorrectionInfo
Definition at line 2751 of file __init__.py.
MathKernCount
fontTools.subset.MathKernCount = len(self.MathKernInfoRecords)
Definition at line 2745 of file __init__.py.
MathKernInfo
fontTools.subset.MathKernInfo
Definition at line 2755 of file __init__.py.
MathKernInfoRecords
fontTools.subset.MathKernInfoRecords = _list_subset(self.MathKernInfoRecords, indices)
Definition at line 2744 of file __init__.py.
MathTopAccentAttachment
fontTools.subset.MathTopAccentAttachment
Definition at line 2753 of file __init__.py.
maxFunctionDefs
int fontTools.subset.maxFunctionDefs = 0
Definition at line 3002 of file __init__.py.
maxInstructionDefs
int fontTools.subset.maxInstructionDefs = 0
Definition at line 3003 of file __init__.py.
maxSizeOfInstructions
int fontTools.subset.maxSizeOfInstructions = 0
Definition at line 3005 of file __init__.py.
maxStackElements
int fontTools.subset.maxStackElements = 0
Definition at line 3004 of file __init__.py.
maxStorage
int fontTools.subset.maxStorage = 0
Definition at line 3001 of file __init__.py.
maxTwilightPoints
int fontTools.subset.maxTwilightPoints = 0
Definition at line 3000 of file __init__.py.
maxZones
int fontTools.subset.maxZones = 1
Definition at line 2999 of file __init__.py.
metrics
fontTools.subset.metrics = _dict_subset(self.metrics, s.glyphs)
Definition at line 2207 of file __init__.py.
NAME_IDS_TO_OBFUSCATE
dict fontTools.subset.NAME_IDS_TO_OBFUSCATE = {1, 2, 3, 4, 6, 16, 17, 18}
Definition at line 3009 of file __init__.py.
names
list fontTools.subset.names = [n for n in self.names if n.nameID in nameIDs]
Definition at line 3019 of file __init__.py.
numPaletteEntries
fontTools.subset.numPaletteEntries = len(self.palettes[0])
Definition at line 2597 of file __init__.py.
numSubTables
fontTools.subset.numSubTables = len(self.tables)
Definition at line 2916 of file __init__.py.
numVertOriginYMetrics
fontTools.subset.numVertOriginYMetrics = len(self.VOriginRecords)
Definition at line 2390 of file __init__.py.
PairSet
list fontTools.subset.PairSet = [pairs[i] for i in indices if i < count]
Definition at line 724 of file __init__.py.
PairSetCount
fontTools.subset.PairSetCount = len(self.PairSet)
Definition at line 734 of file __init__.py.
paletteEntryLabels
fontTools.subset.paletteEntryLabels = []
Definition at line 2601 of file __init__.py.
palettes
fontTools.subset.palettes
Definition at line 2584 of file __init__.py.
ReqFeatureIndex
fontTools.subset.ReqFeatureIndex = feature_indices.index(self.ReqFeatureIndex)
Definition at line 1740 of file __init__.py.
Rule
str fontTools.subset.Rule = ChainTyp + "Rule"
Definition at line 1144 of file __init__.py.
RuleCount
str fontTools.subset.RuleCount = ChainTyp + "RuleCount"
Definition at line 1145 of file __init__.py.
RuleData
fontTools.subset.RuleData = ChainRuleData
Definition at line 1134 of file __init__.py.
RuleSet
str fontTools.subset.RuleSet = ChainTyp + "RuleSet"
Definition at line 1146 of file __init__.py.
RuleSetCount
str fontTools.subset.RuleSetCount = ChainTyp + "RuleSetCount"
Definition at line 1147 of file __init__.py.
ScriptCount
fontTools.subset.ScriptCount = len(self.ScriptRecord)
Definition at line 1792 of file __init__.py.
ScriptRecord
fontTools.subset.ScriptRecord
Initial value:
=  [
        s
        for s in self.ScriptRecord
        if s.Script.subset_features(feature_indices, s.ScriptTag == "DFLT")
        or retain_empty
    ]
Definition at line 1786 of file __init__.py.
SetContextData
fontTools.subset.SetContextData = SetChainContextData
Definition at line 1133 of file __init__.py.
SetRuleData
fontTools.subset.SetRuleData = ChainSetRuleData
Definition at line 1135 of file __init__.py.
signatureRecords
list fontTools.subset.signatureRecords = []
Definition at line 2991 of file __init__.py.
strikeData
list fontTools.subset.strikeData = [strike for strike in strikeData if strike]
Definition at line 1821 of file __init__.py.
strikes
list fontTools.subset.strikes
Definition at line 1804 of file __init__.py.
Substitute
fontTools.subset.Substitute = _list_subset(self.Substitute, indices)
Definition at line 641 of file __init__.py.
SubstitutionCount
fontTools.subset.SubstitutionCount = len(self.SubstitutionRecord)
Definition at line 1715 of file __init__.py.
SubstitutionRecord
list fontTools.subset.SubstitutionRecord
Initial value:
=  [
        r for r in self.SubstitutionRecord if r.FeatureIndex in feature_indices
    ]
Definition at line 1709 of file __init__.py.
SubTable
list fontTools.subset.SubTable
Definition at line 1519 of file __init__.py.
SubTableCount
fontTools.subset.SubTableCount = len(self.SubTable)
Definition at line 1528 of file __init__.py.
table
fontTools.subset.table = _uniq_sort(feature_indices)
Definition at line 1844 of file __init__.py.
tables
list fontTools.subset.tables = [t for t in self.tables if t.isUnicode() or t.isSymbol()]
Definition at line 2910 of file __init__.py.
tableVersion
int fontTools.subset.tableVersion = 0x00010000:
Definition at line 2998 of file __init__.py.
timer
fontTools.subset.timer = Timer(logger=logging.getLogger("fontTools.subset.timer"))
Definition at line 471 of file __init__.py.
TopAccentAttachment
fontTools.subset.TopAccentAttachment = _list_subset(self.TopAccentAttachment, indices)
Definition at line 2736 of file __init__.py.
TopAccentAttachmentCount
fontTools.subset.TopAccentAttachmentCount = len(self.TopAccentAttachment)
Definition at line 2737 of file __init__.py.
Typ
fontTools.subset.Typ = Typ
Definition at line 1041 of file __init__.py.
Type
fontTools.subset.Type = Type
Definition at line 1042 of file __init__.py.
usNumSigs
int fontTools.subset.usNumSigs = 0
Definition at line 2990 of file __init__.py.
Value
fontTools.subset.Value = [values[i] for i in indices if i < count]
Definition at line 679 of file __init__.py.
ValueCount
fontTools.subset.ValueCount = len(self.Value)
Definition at line 680 of file __init__.py.
ValueFormat
int fontTools.subset.ValueFormat = 0
Definition at line 689 of file __init__.py.
ValueFormat1
int fontTools.subset.ValueFormat1 = 0
Definition at line 772 of file __init__.py.
ValueFormat2
fontTools.subset.ValueFormat2 = r.Value2.getEffectiveFormat()
Definition at line 782 of file __init__.py.
variations
fontTools.subset.variations = _dict_subset(self.variations, s.glyphs)
Definition at line 2288 of file __init__.py.
version
int fontTools.subset.version = 0:
Definition at line 2517 of file __init__.py.
VertGlyphConstruction
fontTools.subset.VertGlyphConstruction = _list_subset(self.VertGlyphConstruction, indices)
Definition at line 2766 of file __init__.py.
VertGlyphCount
fontTools.subset.VertGlyphCount = len(self.VertGlyphConstruction)
Definition at line 2767 of file __init__.py.
VertGlyphCoverage
fontTools.subset.VertGlyphCoverage
Definition at line 2624 of file __init__.py.
VOriginRecords
dict fontTools.subset.VOriginRecords
Initial value:
=  {
        g: v for g, v in self.VOriginRecords.items() if g in s.glyphs
    }
Definition at line 2387 of file __init__.py.