Code Cloning Analysis: sklearn.utils._array_api Namespace Reference
sklearn.utils._array_api Namespace Reference
Functions
yield_namespaces (include_numpy_namespaces=True)
yield_namespace_device_dtype_combinations (include_numpy_namespaces=True)
_get_namespace_device_dtype_ids (param)
_check_array_api_dispatch (array_api_dispatch)
_single_array_device (array)
device (*array_list, remove_none=True, remove_types=(str,))
size (x)
_is_numpy_namespace (xp)
_union1d (a, b, xp)
isdtype (dtype, kind, *, xp)
_isdtype_single (dtype, kind, *, xp)
supported_float_dtypes (xp)
ensure_common_namespace_device (reference, *arrays)
_check_device_cpu (device)
_accept_device_cpu (func)
_remove_non_arrays (*arrays, remove_none=True, remove_types=(str,))
get_namespace (*arrays, remove_none=True, remove_types=(str,), xp=None)
get_namespace_and_device (*array_list, remove_none=True, remove_types=(str,), xp=None)
_expit (X, xp=None)
_fill_or_add_to_diagonal (array, value, xp, add_value=True, wrap=False)
_is_xp_namespace (xp, name)
_max_precision_float_dtype (xp, device)
_find_matching_floating_dtype (*arrays, xp)
_average (a, axis=None, weights=None, normalize=True, xp=None)
_xlogy (x, y, xp=None)
_nanmin (X, axis=None, xp=None)
_nanmax (X, axis=None, xp=None)
_nanmean (X, axis=None, xp=None)
_asarray_with_order (array, dtype=None, order=None, copy=None, *, xp=None, device=None)
_ravel (array, xp=None)
_convert_to_numpy (array, xp)
_estimator_with_converted_arrays (estimator, converter)
_atol_for_type (dtype_or_dtype_name)
indexing_dtype (xp)
_searchsorted (a, v, *, side="left", sorter=None, xp=None)
_isin (element, test_elements, xp, assume_unique=False, invert=False)
_in1d (ar1, ar2, xp, assume_unique=False, invert=False)
_count_nonzero (X, axis=None, sample_weight=None, xp=None, device=None)
_modify_in_place_if_numpy (xp, func, *args, out=None, **kwargs)
_bincount (array, weights=None, minlength=None, xp=None)
_tolist (array, xp=None)
Variables
list __all__ = ["xpx"]
dict _NUMPY_NAMESPACE_NAMES = {"numpy", "sklearn.externals.array_api_compat.numpy"}
Detailed Description
Tools to support array_api.
Function Documentation
_accept_device_cpu()
sklearn.utils._array_api._accept_device_cpu (func) protected
Definition at line 342 of file _array_api.py.
_asarray_with_order()
sklearn.utils._array_api._asarray_with_order (array, dtype = None, order = None, copy = None, * , xp = None, device = None) protected
Helper to support the order kwarg only for NumPy-backed arrays
Memory layout parameter `order` is not exposed in the Array API standard,
however some input validation code in scikit-learn needs to work both
for classes and functions that will leverage Array API only operations
and for code that inherently relies on NumPy backed data containers with
specific memory layout constraints (e.g. our own Cython code). The
purpose of this helper is to make it possible to share code for data
container validation without memory copies for both downstream use cases:
the `order` parameter is only enforced if the input array implementation
is NumPy based, otherwise `order` is just silently ignored.
Definition at line 736 of file _array_api.py.
References _is_numpy_namespace(), and get_namespace().
_atol_for_type()
sklearn.utils._array_api._atol_for_type (dtype_or_dtype_name) protected
Return the absolute tolerance for a given numpy dtype.
Definition at line 821 of file _array_api.py.
_average()
sklearn.utils._array_api._average (a, axis = None, weights = None, normalize = True, xp = None) protected
Partial port of np.average to support the Array API.
It does a best effort at mimicking the return dtype rule described at
https://numpy.org/doc/stable/reference/generated/numpy.average.html but
only for the common cases needed in scikit-learn.
Definition at line 606 of file _array_api.py.
References _find_matching_floating_dtype(), _is_numpy_namespace(), and get_namespace_and_device().
_bincount()
sklearn.utils._array_api._bincount (array, weights = None, minlength = None, xp = None) protected
Definition at line 985 of file _array_api.py.
_check_array_api_dispatch()
sklearn.utils._array_api._check_array_api_dispatch (array_api_dispatch) protected
Check that array_api_compat is installed and NumPy version is compatible.
array_api_compat follows NEP29, which has a higher minimum NumPy version than
scikit-learn.
Definition at line 127 of file _array_api.py.
Referenced by get_namespace().
_check_device_cpu()
sklearn.utils._array_api._check_device_cpu (device) protected
Definition at line 337 of file _array_api.py.
_convert_to_numpy()
sklearn.utils._array_api._convert_to_numpy (array, xp) protected
Convert X into a NumPy ndarray on the CPU.
Definition at line 780 of file _array_api.py.
Referenced by _count_nonzero(), and indexing_dtype().
_count_nonzero()
sklearn.utils._array_api._count_nonzero (X, axis = None, sample_weight = None, xp = None, device = None) protected
A variant of `sklearn.utils.sparsefuncs.count_nonzero` for the Array API.
If the array `X` is sparse, and we are using the numpy namespace then we
simply call the original function. This function only supports 2D arrays.
Definition at line 953 of file _array_api.py.
References _convert_to_numpy(), _is_numpy_namespace(), device(), and get_namespace().
_estimator_with_converted_arrays()
sklearn.utils._array_api._estimator_with_converted_arrays (estimator, converter) protected
Create new estimator which converting all attributes that are arrays.
The converter is called on all NumPy arrays and arrays that support the
`DLPack interface <https://dmlc.github.io/dlpack/latest/>`__.
Parameters
----------
estimator : Estimator
    Estimator to convert
converter : callable
    Callable that takes an array attribute and returns the converted array.
Returns
-------
new_estimator : Estimator
    Convert estimator
Definition at line 792 of file _array_api.py.
_expit()
sklearn.utils._array_api._expit (X, xp = None) protected
Definition at line 522 of file _array_api.py.
_fill_or_add_to_diagonal()
sklearn.utils._array_api._fill_or_add_to_diagonal (array, value, xp, add_value = True, wrap = False) protected
Implementation to facilitate adding or assigning specified values to the
diagonal of a 2-d array.
If ``add_value`` is `True` then the values will be added to the diagonal
elements otherwise the values will be assigned to the diagonal elements.
By default, ``add_value`` is set to `True. This is currently only
supported for 2-d arrays.
The implementation is taken from the `numpy.fill_diagonal` function:
https://github.com/numpy/numpy/blob/v2.0.0/numpy/lib/_index_tricks_impl.py#L799-L929
Definition at line 530 of file _array_api.py.
References device().
_find_matching_floating_dtype()
sklearn.utils._array_api._find_matching_floating_dtype (* arrays, xp) protected
Find a suitable floating point dtype when computing with arrays.
If any of the arrays are floating point, return the dtype with the highest
precision by following official type promotion rules:
https://data-apis.org/array-api/latest/API_specification/type_promotion.html
If there are no floating point input arrays (all integral inputs for
instance), return the default floating point dtype for the namespace.
Definition at line 581 of file _array_api.py.
Referenced by _average().
_get_namespace_device_dtype_ids()
sklearn.utils._array_api._get_namespace_device_dtype_ids (param) protected
Get pytest parametrization IDs for `yield_namespace_device_dtype_combinations`
Definition at line 110 of file _array_api.py.
_in1d()
sklearn.utils._array_api._in1d (ar1, ar2, xp, assume_unique = False, invert = False) protected
Checks whether each element of an array is also present in a
second array.
Returns a boolean array the same length as `ar1` that is True
where an element of `ar1` is in `ar2` and False otherwise.
This function has been adapted using the original implementation
present in numpy:
https://github.com/numpy/numpy/blob/v1.26.0/numpy/lib/arraysetops.py#L524-L758
Definition at line 904 of file _array_api.py.
References device(), get_namespace(), and size().
Referenced by _isin().
_is_numpy_namespace()
sklearn.utils._array_api._is_numpy_namespace (xp) protected
Return True if xp is backed by NumPy.
Definition at line 231 of file _array_api.py.
References _is_numpy_namespace().
Referenced by _asarray_with_order(), _average(), _count_nonzero(), _is_numpy_namespace(), _isin(), _ravel(), and get_namespace_and_device().
_is_xp_namespace()
sklearn.utils._array_api._is_xp_namespace (xp, name) protected
Definition at line 562 of file _array_api.py.
_isdtype_single()
sklearn.utils._array_api._isdtype_single (dtype, kind, * , xp) protected
Definition at line 259 of file _array_api.py.
_isin()
sklearn.utils._array_api._isin (element, test_elements, xp, assume_unique = False, invert = False) protected
Calculates ``element in test_elements``, broadcasting over `element`
only.
Returns a boolean array of the same shape as `element` that is True
where an element of `element` is in `test_elements` and False otherwise.
Definition at line 870 of file _array_api.py.
References _in1d(), and _is_numpy_namespace().
_max_precision_float_dtype()
sklearn.utils._array_api._max_precision_float_dtype (xp, device) protected
Return the float dtype with the highest precision supported by the device.
Definition at line 570 of file _array_api.py.
_modify_in_place_if_numpy()
sklearn.utils._array_api._modify_in_place_if_numpy (xp, func, * args, out = None, ** kwargs) protected
Definition at line 977 of file _array_api.py.
_nanmax()
sklearn.utils._array_api._nanmax (X, axis = None, xp = None) protected
Definition at line 701 of file _array_api.py.
_nanmean()
sklearn.utils._array_api._nanmean (X, axis = None, xp = None) protected
Definition at line 721 of file _array_api.py.
_nanmin()
sklearn.utils._array_api._nanmin (X, axis = None, xp = None) protected
Definition at line 681 of file _array_api.py.
_ravel()
sklearn.utils._array_api._ravel (array, xp = None) protected
Array API compliant version of np.ravel.
For non numpy namespaces, it just returns a flattened array, that might
be or not be a copy.
Definition at line 766 of file _array_api.py.
References _is_numpy_namespace(), and get_namespace().
_remove_non_arrays()
sklearn.utils._array_api._remove_non_arrays (* arrays, remove_none = True, remove_types = (str,)) protected
Filter arrays to exclude None and/or specific types.
Sparse arrays are always filtered out.
Parameters
----------
*arrays : array objects
    Array objects.
remove_none : bool, default=True
    Whether to ignore None objects passed in arrays.
remove_types : tuple or list, default=(str,)
    Types to ignore in the arrays.
Returns
-------
filtered_arrays : list
    List of arrays filtered as requested. An empty list is returned if no input
    passes the filters.
Definition at line 351 of file _array_api.py.
Referenced by device(), get_namespace(), and get_namespace_and_device().
_searchsorted()
sklearn.utils._array_api._searchsorted (a, v, * , side = "left", sorter = None, xp = None) protected
Definition at line 855 of file _array_api.py.
_single_array_device()
sklearn.utils._array_api._single_array_device (array) protected
Hardware device where the array data resides on.
Definition at line 154 of file _array_api.py.
Referenced by device().
_tolist()
sklearn.utils._array_api._tolist (array, xp = None) protected
Definition at line 1001 of file _array_api.py.
_union1d()
sklearn.utils._array_api._union1d (a, b, xp) protected
Definition at line 236 of file _array_api.py.
_xlogy()
sklearn.utils._array_api._xlogy (x, y, xp = None) protected
Definition at line 672 of file _array_api.py.
device()
sklearn.utils._array_api.device (* array_list, remove_none = True, remove_types = (str,))
Hardware device where the array data resides on.
If the hardware device is not the same for all arrays, an error is raised.
Parameters
----------
*array_list : arrays
    List of array instances from NumPy or an array API compatible library.
remove_none : bool, default=True
    Whether to ignore None objects passed in array_list.
remove_types : tuple or list, default=(str,)
    Types to ignore in array_list.
Returns
-------
out : device
    `device` object (see the "Device Support" section of the array API spec).
Definition at line 171 of file _array_api.py.
References _remove_non_arrays(), and _single_array_device().
Referenced by _count_nonzero(), _fill_or_add_to_diagonal(), _in1d(), ensure_common_namespace_device(), get_namespace_and_device(), and indexing_dtype().
ensure_common_namespace_device()
sklearn.utils._array_api.ensure_common_namespace_device (reference, * arrays)
Ensure that all arrays use the same namespace and device as reference.
If necessary the arrays are moved to the same namespace and device as
the reference array.
Parameters
----------
reference : array
    Reference array.
*arrays : array
    Arrays to check.
Returns
-------
arrays : list
    Arrays with the same namespace and device as reference.
Definition at line 308 of file _array_api.py.
References device(), and get_namespace().
get_namespace()
sklearn.utils._array_api.get_namespace (* arrays, remove_none = True, remove_types = (str,), xp = None)
Get namespace of arrays.
Introspect `arrays` arguments and return their common Array API compatible
namespace object, if any.
Note that sparse arrays are filtered by default.
See: https://numpy.org/neps/nep-0047-array-api-standard.html
If `arrays` are regular numpy arrays, `array_api_compat.numpy` is returned instead.
Namespace support is not enabled by default. To enabled it call:
  sklearn.set_config(array_api_dispatch=True)
or:
  with sklearn.config_context(array_api_dispatch=True):
      # your code here
Otherwise `array_api_compat.numpy` is
always returned irrespective of the fact that arrays implement the
`__array_namespace__` protocol or not.
Note that if no arrays pass the set filters, ``_NUMPY_API_WRAPPER_INSTANCE, False``
is returned.
Parameters
----------
*arrays : array objects
    Array objects.
remove_none : bool, default=True
    Whether to ignore None objects passed in arrays.
remove_types : tuple or list, default=(str,)
    Types to ignore in the arrays.
xp : module, default=None
    Precomputed array namespace module. When passed, typically from a caller
    that has already performed inspection of its own inputs, skips array
    namespace inspection.
Returns
-------
namespace : module
    Namespace shared by array objects. If any of the `arrays` are not arrays,
    the namespace defaults to the NumPy namespace.
is_array_api_compliant : bool
    True if the arrays are containers that implement the array API spec (see
    https://data-apis.org/array-api/latest/index.html).
    Always False when array_api_dispatch=False.
Definition at line 387 of file _array_api.py.
References _check_array_api_dispatch(), and _remove_non_arrays().
Referenced by _asarray_with_order(), _count_nonzero(), _in1d(), _ravel(), ensure_common_namespace_device(), get_namespace_and_device(), and indexing_dtype().
get_namespace_and_device()
sklearn.utils._array_api.get_namespace_and_device (* array_list, remove_none = True, remove_types = (str,), xp = None)
Combination into one single function of `get_namespace` and `device`.
Parameters
----------
*array_list : array objects
    Array objects.
remove_none : bool, default=True
    Whether to ignore None objects passed in arrays.
remove_types : tuple or list, default=(str,)
    Types to ignore in the arrays.
xp : module, default=None
    Precomputed array namespace module. When passed, typically from a caller
    that has already performed inspection of its own inputs, skips array
    namespace inspection.
Returns
-------
namespace : module
    Namespace shared by array objects. If any of the `arrays` are not arrays,
    the namespace defaults to NumPy.
is_array_api_compliant : bool
    True if the arrays are containers that implement the Array API spec.
    Always False when array_api_dispatch=False.
device : device
    `device` object (see the "Device Support" section of the array API spec).
Definition at line 473 of file _array_api.py.
References _is_numpy_namespace(), _remove_non_arrays(), device(), and get_namespace().
Referenced by _average().
indexing_dtype()
sklearn.utils._array_api.indexing_dtype (xp)
Return a platform-specific integer dtype suitable for indexing.
On 32-bit platforms, this will typically return int32 and int64 otherwise.
Note: using dtype is recommended for indexing transient array
datastructures. For long-lived arrays, such as the fitted attributes of
estimators, it is instead recommended to use platform-independent int32 if
we do not expect to index more 2B elements. Using fixed dtypes simplifies
the handling of serialized models, e.g. to deploy a model fit on a 64-bit
platform to a target 32-bit platform such as WASM/pyodide.
Definition at line 831 of file _array_api.py.
References _convert_to_numpy(), device(), and get_namespace().
isdtype()
sklearn.utils._array_api.isdtype (dtype, kind, * , xp)
Returns a boolean indicating whether a provided dtype is of type "kind".
Included in the v2022.12 of the Array API spec.
https://data-apis.org/array-api/latest/API_specification/generated/array_api.isdtype.html
Definition at line 247 of file _array_api.py.
References supported_float_dtypes().
size()
sklearn.utils._array_api.size (x)
Return the total number of elements of x.
Parameters
----------
x : array
    Array instance from NumPy or an array API compatible library.
Returns
-------
out : int
    Total number of elements.
Definition at line 215 of file _array_api.py.
Referenced by _in1d().
supported_float_dtypes()
sklearn.utils._array_api.supported_float_dtypes (xp)
Supported floating point types for the namespace.
Note: float16 is not officially part of the Array API spec at the
time of writing but scikit-learn estimators and functions can choose
to accept it when xp.float16 is defined.
https://data-apis.org/array-api/latest/API_specification/data_types.html
Definition at line 293 of file _array_api.py.
Referenced by isdtype().
yield_namespace_device_dtype_combinations()
sklearn.utils._array_api.yield_namespace_device_dtype_combinations (include_numpy_namespaces = True)
Yield supported namespace, device, dtype tuples for testing.
Use this to test that an estimator works with all combinations.
Use in conjunction with `ids=_get_namespace_device_dtype_ids` to give
clearer pytest parametrization ID names.
Parameters
----------
include_numpy_namespaces : bool, default=True
    If True, also yield numpy namespaces.
Returns
-------
array_namespace : str
    The name of the Array API namespace.
device : str
    The name of the device on which to allocate the arrays. Can be None to
    indicate that the default value should be used.
dtype_name : str
    The name of the data type to use for arrays. Can be None to indicate
    that the default value should be used.
Definition at line 59 of file _array_api.py.
References yield_namespaces().
yield_namespaces()
sklearn.utils._array_api.yield_namespaces (include_numpy_namespaces = True)
Yield supported namespace.
This is meant to be used for testing purposes only.
Parameters
----------
include_numpy_namespaces : bool, default=True
    If True, also yield numpy namespaces.
Returns
-------
array_namespace : str
    The name of the Array API namespace.
Definition at line 28 of file _array_api.py.
Referenced by yield_namespace_device_dtype_combinations().
Variable Documentation
__all__
list sklearn.utils._array_api.__all__ = ["xpx"] private
Definition at line 23 of file _array_api.py.
_NUMPY_NAMESPACE_NAMES
dict sklearn.utils._array_api._NUMPY_NAMESPACE_NAMES = {"numpy", "sklearn.externals.array_api_compat.numpy"} protected
Definition at line 25 of file _array_api.py.