Code Cloning Analysis: third_prompt Namespace Reference
third_prompt Namespace Reference
Classes
class Confidence
Defines the Confidence class, which is used to determine the structured ouput.
Functions
safe_parse_response (response)
Translates the given response from the model into the proper dictionary format.
ensemble_assessment (code1, code2, model_name, prompt, n=3)
Performs multiple assessments and aggregates predictions using voting.
determine_similarity (results)
rag_similarity_assessment (code1, code2, model_name, prompt)
Sends a prompt to the LLM to classify clone type and score similarities.
Variables
str DATA_DIR = "./data/data"
Path to the directory containing code files for similarity comparison.
str PAIRS_CSV = "./pairs.csv"
CSV file containing file pairs to compare.
str GROUND_TRUTH_CSV = "./ground_truth.csv"
CSV file containing ground truth similarity labels for file pairs.
list LLMS
List of model names to use for clone detection.
list PROMPTS
The first prompt we tested on.
pairs_df = pd.read_csv(PAIRS_CSV)
DataFrame of file pairs to compare.
ground_truth_df = pd.read_csv(GROUND_TRUTH_CSV)
DataFrame containing ground truth similarity labels.
ground_truth_map = dict(zip(ground_truth_df['pair-id'], ground_truth_df['similar']))
Dictionary mapping pair IDs to binary similarity values.
dict results_by_prompt = {i: {'truth': [], 'preds': []} for i in range(len(PROMPTS))}
Executes evaluation over prompts and saves results and metrics.
str output = f"./results/prompt_first_results_{LLMS[0]}_iteration_{iteration}.csv"
newline
writer = csv.writer(outfile)
file1_path = os.path.join(DATA_DIR, row['file1'])
file2_path = os.path.join(DATA_DIR, row['file2'])
pair_id = row['pair-id']
encoding
errors
code1 = f1.read()
code2 = f2.read()
ground_truth_sim = ground_truth_map.get(pair_id, "Unknown")
results
predicted_type
predicted_sim
model_name
prompt
n
str metrics_output = f'./results/prompt_first{LLMS[0]}_iteration_{iteration}.txt'
Calculate and write evaluation metrics for the prompt.
dict truth = results_by_prompt[prompt_id]['truth']
dict preds = results_by_prompt[prompt_id]['preds']
acc = accuracy_score(truth, preds)
prec = precision_score(truth, preds, zero_division=0)
rec = recall_score(truth, preds, zero_division=0)
f1s = f1_score(truth, preds, zero_division=0)
mse = mean_squared_error(truth, preds, zero_division=0)
file
Function Documentation
determine_similarity()
third_prompt.determine_similarity (results)
Definition at line 174 of file third_prompt.py.
ensemble_assessment()
third_prompt.ensemble_assessment (code1, code2, model_name, thr, n = 3)
Performs multiple assessments and aggregates predictions using voting.
Parameters
code1 First code string.
code2 Second code string.
model_name The name of the LLM model to use.
thr Threshold for similarity.
n Number of repeated assessments for ensemble.
Returns
Tuple of (average type scores, majority predicted type, majority binary similarity).
Definition at line 129 of file third_prompt.py.
References rag_similarity_assessment().
rag_similarity_assessment()
third_prompt.rag_similarity_assessment (code1, code2, model_name, thr)
Sends a prompt to the LLM to classify clone type and score similarities.
Parameters
code1 First code snippet to evaluate.
code2 Second code snippet to evaluate.
model_name Name of the language model to query.
thr Threshold for determining clone similarity.
Returns
Tuple of (type score dictionary, predicted type, binary similarity).
Definition at line 191 of file third_prompt.py.
References safe_parse_response().
Referenced by ensemble_assessment().
safe_parse_response()
third_prompt.safe_parse_response (response)
Translates the given response from the model into the proper dictionary format.
Parameters
response The RAG output.
Definition at line 100 of file third_prompt.py.
Referenced by rag_similarity_assessment().
Variable Documentation
acc
third_prompt.acc = accuracy_score(truth, preds)
Definition at line 257 of file third_prompt.py.
code1
third_prompt.code1 = f1.read()
Definition at line 230 of file third_prompt.py.
code2
third_prompt.code2 = f2.read()
Definition at line 231 of file third_prompt.py.
DATA_DIR
str third_prompt.DATA_DIR = "./data/data"
Path to the directory containing code files for similarity comparison.
Definition at line 26 of file third_prompt.py.
encoding
third_prompt.encoding
Definition at line 228 of file third_prompt.py.
errors
third_prompt.errors
Definition at line 228 of file third_prompt.py.
f1s
third_prompt.f1s = f1_score(truth, preds, zero_division=0)
Definition at line 260 of file third_prompt.py.
file
third_prompt.file
Definition at line 262 of file third_prompt.py.
file1_path
third_prompt.file1_path = os.path.join(DATA_DIR, row['file1'])
Definition at line 224 of file third_prompt.py.
file2_path
third_prompt.file2_path = os.path.join(DATA_DIR, row['file2'])
Definition at line 225 of file third_prompt.py.
GROUND_TRUTH_CSV
str third_prompt.GROUND_TRUTH_CSV = "./ground_truth.csv"
CSV file containing ground truth similarity labels for file pairs.
Definition at line 34 of file third_prompt.py.
ground_truth_df
third_prompt.ground_truth_df = pd.read_csv(GROUND_TRUTH_CSV)
DataFrame containing ground truth similarity labels.
Definition at line 90 of file third_prompt.py.
ground_truth_map
third_prompt.ground_truth_map = dict(zip(ground_truth_df['pair-id'], ground_truth_df['similar']))
Dictionary mapping pair IDs to binary similarity values.
Definition at line 94 of file third_prompt.py.
ground_truth_sim
third_prompt.ground_truth_sim = ground_truth_map.get(pair_id, "Unknown")
Definition at line 235 of file third_prompt.py.
LLMS
list third_prompt.LLMS
Initial value:
=  [
    "llama3.1:latest"
]
List of model names to use for clone detection.
Definition at line 38 of file third_prompt.py.
metrics_output
str third_prompt.metrics_output = f'./results/prompt_first{LLMS[0]}_iteration_{iteration}.txt'
Calculate and write evaluation metrics for the prompt.
Definition at line 251 of file third_prompt.py.
model_name
third_prompt.model_name
Definition at line 240 of file third_prompt.py.
mse
third_prompt.mse = mean_squared_error(truth, preds, zero_division=0)
Definition at line 261 of file third_prompt.py.
n
third_prompt.n
Definition at line 240 of file third_prompt.py.
newline
third_prompt.newline
Definition at line 215 of file third_prompt.py.
output
str third_prompt.output = f"./results/prompt_first_results_{LLMS[0]}_iteration_{iteration}.csv"
Definition at line 214 of file third_prompt.py.
pair_id
third_prompt.pair_id = row['pair-id']
Definition at line 226 of file third_prompt.py.
PAIRS_CSV
str third_prompt.PAIRS_CSV = "./pairs.csv"
CSV file containing file pairs to compare.
Definition at line 30 of file third_prompt.py.
pairs_df
third_prompt.pairs_df = pd.read_csv(PAIRS_CSV)
DataFrame of file pairs to compare.
Definition at line 86 of file third_prompt.py.
prec
third_prompt.prec = precision_score(truth, preds, zero_division=0)
Definition at line 258 of file third_prompt.py.
predicted_sim
third_prompt.predicted_sim
Definition at line 240 of file third_prompt.py.
predicted_type
third_prompt.predicted_type
Definition at line 240 of file third_prompt.py.
preds
dict third_prompt.preds = results_by_prompt[prompt_id]['preds']
Definition at line 255 of file third_prompt.py.
prompt
third_prompt.prompt
Definition at line 240 of file third_prompt.py.
PROMPTS
list third_prompt.PROMPTS
Initial value:
=  [
    # Prompt 3
]
The first prompt we tested on.
Definition at line 51 of file third_prompt.py.
rec
third_prompt.rec = recall_score(truth, preds, zero_division=0)
Definition at line 259 of file third_prompt.py.
results
third_prompt.results
Definition at line 240 of file third_prompt.py.
results_by_prompt
dict third_prompt.results_by_prompt = {i: {'truth': [], 'preds': []} for i in range(len(PROMPTS))}
Executes evaluation over prompts and saves results and metrics.
Definition at line 209 of file third_prompt.py.
truth
dict third_prompt.truth = results_by_prompt[prompt_id]['truth']
Definition at line 254 of file third_prompt.py.
writer
third_prompt.writer = csv.writer(outfile)
Definition at line 216 of file third_prompt.py.