Code Cloning Analysis: pandas._typing.BaseBuffer Class Reference
pandas._typing.BaseBuffer Class Reference
Public Member Functions
str mode (self)
int seek (self, int __offset, int __whence=...)
bool seekable (self)
int tell (self)
Detailed Description
Definition at line 262 of file _typing.py.
Member Function Documentation
mode()
str pandas._typing.BaseBuffer.mode (self)
Definition at line 264 of file _typing.py.
seek()
int pandas._typing.BaseBuffer.seek (self, int __offset, int __whence = ...)
Definition at line 268 of file _typing.py.
Referenced by pip._internal.network.lazy_wheel.LazyZipOverHTTP._download(), PIL.MicImagePlugin.MicImageFile._open(), PIL.TiffImagePlugin.TiffImageFile._open(), pip._internal.network.lazy_wheel.LazyZipOverHTTP._stay(), PIL.GifImagePlugin.GifImageFile.seek(), and PIL.WebPImagePlugin.WebPImageFile.seek().
seekable()
bool pandas._typing.BaseBuffer.seekable (self)
Definition at line 273 of file _typing.py.
tell()
int pandas._typing.BaseBuffer.tell (self)
Definition at line 277 of file _typing.py.
Referenced by PIL.TiffImagePlugin.TiffImageFile._open(), pip._internal.network.lazy_wheel.LazyZipOverHTTP._stay(), and pip._internal.network.lazy_wheel.LazyZipOverHTTP.read().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/_typing.py