Code Cloning Analysis: scipy.stats._mstats_basic Namespace Reference
scipy.stats._mstats_basic Namespace Reference
Functions
_chk_asarray (a, axis)
_chk2_asarray (a, b, axis)
_chk_size (a, b)
argstoarray (*args)
find_repeats (arr)
count_tied_groups (x, use_missing=False)
rankdata (data, axis=None, use_missing=False)
mode (a, axis=0)
_mode (a, axis=0, keepdims=True)
_betai (a, b, x)
msign (x)
pearsonr (x, y)
spearmanr (x, y=None, use_ties=True, axis=None, nan_policy='propagate', alternative='two-sided')
_kendall_p_exact (n, c, alternative='two-sided')
kendalltau (x, y, use_ties=True, use_missing=False, method='auto', alternative='two-sided')
kendalltau_seasonal (x)
pointbiserialr (x, y)
linregress (x, y=None)
theilslopes (y, x=None, alpha=0.95, method='separate')
siegelslopes (y, x=None, method="hierarchical")
sen_seasonal_slopes (x)
ttest_1samp (a, popmean, axis=0, alternative='two-sided')
ttest_ind (a, b, axis=0, equal_var=True, alternative='two-sided')
ttest_rel (a, b, axis=0, alternative='two-sided')
mannwhitneyu (x, y, use_continuity=True)
kruskal (*args)
ks_1samp (x, cdf, args=(), alternative="two-sided", method='auto')
ks_2samp (data1, data2, alternative="two-sided", method='auto')
kstest (data1, data2, args=(), alternative='two-sided', method='auto')
trima (a, limits=None, inclusive=(True, True))
trimr (a, limits=None, inclusive=(True, True), axis=None)
trim (a, limits=None, inclusive=(True, True), relative=False, axis=None)
trimboth (data, proportiontocut=0.2, inclusive=(True, True), axis=None)
trimtail (data, proportiontocut=0.2, tail='left', inclusive=(True, True), axis=None)
trimmed_mean (a, limits=(0.1, 0.1), inclusive=(1, 1), relative=True, axis=None)
trimmed_var (a, limits=(0.1, 0.1), inclusive=(1, 1), relative=True, axis=None, ddof=0)
trimmed_std (a, limits=(0.1, 0.1), inclusive=(1, 1), relative=True, axis=None, ddof=0)
trimmed_stde (a, limits=(0.1, 0.1), inclusive=(1, 1), axis=None)
_mask_to_limits (a, limits, inclusive)
tmean (a, limits=None, inclusive=(True, True), axis=None)
tvar (a, limits=None, inclusive=(True, True), axis=0, ddof=1)
tmin (a, lowerlimit=None, axis=0, inclusive=True)
tmax (a, upperlimit=None, axis=0, inclusive=True)
tsem (a, limits=None, inclusive=(True, True), axis=0, ddof=1)
winsorize (a, limits=None, inclusive=(True, True), inplace=False, axis=None, nan_policy='propagate')
moment (a, moment=1, axis=0)
_moment (a, moment, axis, *, mean=None)
variation (a, axis=0, ddof=0)
skew (a, axis=0, bias=True)
kurtosis (a, axis=0, fisher=True, bias=True)
describe (a, axis=0, ddof=0, bias=True)
stde_median (data, axis=None)
skewtest (a, axis=0, alternative='two-sided')
kurtosistest (a, axis=0, alternative='two-sided')
normaltest (a, axis=0)
mquantiles (a, prob=list([.25,.5,.75]), alphap=.4, betap=.4, axis=None, limit=())
scoreatpercentile (data, per, limit=(), alphap=.4, betap=.4)
plotting_positions (data, alpha=0.4, beta=0.4)
obrientransform (*args)
sem (a, axis=0, ddof=1)
f_oneway (*args)
friedmanchisquare (*args)
brunnermunzel (x, y, alternative="two-sided", distribution="t")
Variables
list __all__
ModeResult = namedtuple('ModeResult', ('mode', 'count'))
PointbiserialrResult
SenSeasonalSlopesResult
Ttest_1sampResult = namedtuple('Ttest_1sampResult', ('statistic', 'pvalue'))
ttest_onesamp = ttest_1samp
Ttest_indResult = namedtuple('Ttest_indResult', ('statistic', 'pvalue'))
Ttest_relResult = namedtuple('Ttest_relResult', ('statistic', 'pvalue'))
MannwhitneyuResult
KruskalResult = namedtuple('KruskalResult', ('statistic', 'pvalue'))
kruskalwallis = kruskal
ks_twosamp = ks_2samp
str trimdoc
__doc__
trim1 = trimtail
DescribeResult
SkewtestResult = namedtuple('SkewtestResult', ('statistic', 'pvalue'))
KurtosistestResult = namedtuple('KurtosistestResult', ('statistic', 'pvalue'))
NormaltestResult = namedtuple('NormaltestResult', ('statistic', 'pvalue'))
meppf = plotting_positions
F_onewayResult = namedtuple('F_onewayResult', ('statistic', 'pvalue'))
FriedmanchisquareResult
BrunnerMunzelResult = namedtuple('BrunnerMunzelResult', ('statistic', 'pvalue'))
Detailed Description
An extension of scipy.stats._stats_py to support masked arrays
Function Documentation
_betai()
scipy.stats._mstats_basic._betai (a, b, x) protected
Definition at line 371 of file _mstats_basic.py.
_chk2_asarray()
scipy.stats._mstats_basic._chk2_asarray (a, b, axis) protected
Definition at line 69 of file _mstats_basic.py.
_chk_asarray()
scipy.stats._mstats_basic._chk_asarray (a, axis) protected
Definition at line 58 of file _mstats_basic.py.
_chk_size()
scipy.stats._mstats_basic._chk_size (a, b) protected
Definition at line 81 of file _mstats_basic.py.
_kendall_p_exact()
scipy.stats._mstats_basic._kendall_p_exact (n, c, alternative = 'two-sided') protected
Definition at line 709 of file _mstats_basic.py.
_mask_to_limits()
scipy.stats._mstats_basic._mask_to_limits (a, limits, inclusive) protected
Mask an array for values outside of given limits.
This is primarily a utility function.
Parameters
----------
a : array
limits : (float or None, float or None)
A tuple consisting of the (lower limit, upper limit).  Values in the
input array less than the lower limit or greater than the upper limit
will be masked out. None implies no limit.
inclusive : (bool, bool)
A tuple consisting of the (lower flag, upper flag).  These flags
determine whether values exactly equal to lower or upper are allowed.
Returns
-------
A MaskedArray.
Raises
------
A ValueError if there are no values within the given limits.
Definition at line 2152 of file _mstats_basic.py.
Referenced by tvar().
_mode()
scipy.stats._mstats_basic._mode (a, axis = 0, keepdims = True) protected
Definition at line 338 of file _mstats_basic.py.
_moment()
scipy.stats._mstats_basic._moment (a, moment, axis, * , mean = None) protected
Definition at line 2603 of file _mstats_basic.py.
argstoarray()
scipy.stats._mstats_basic.argstoarray (* args)
Constructs a 2D array from a group of sequences.
Sequences are filled with missing values to match the length of the longest
sequence.
Parameters
----------
*args : sequences
    Group of sequences.
Returns
-------
argstoarray : MaskedArray
    A ( `m` x `n` ) masked array, where `m` is the number of arguments and
    `n` the length of the longest argument.
Notes
-----
`numpy.ma.vstack` has identical behavior, but is called with a sequence
of sequences.
Examples
--------
A 2D masked array constructed from a group of sequences is returned.
>>> from scipy.stats.mstats import argstoarray
>>> argstoarray([1, 2, 3], [4, 5, 6])
masked_array(
 data=[[1.0, 2.0, 3.0],
       [4.0, 5.0, 6.0]],
 mask=[[False, False, False],
       [False, False, False]],
 fill_value=1e+20)
The returned masked array filled with missing values when the lengths of
sequences are different.
>>> argstoarray([1, 3], [4, 5, 6])
masked_array(
 data=[[1.0, 3.0, --],
       [4.0, 5.0, 6.0]],
 mask=[[False, False,  True],
       [False, False, False]],
 fill_value=1e+20)
Definition at line 91 of file _mstats_basic.py.
Referenced by f_oneway(), friedmanchisquare(), kruskal(), and obrientransform().
brunnermunzel()
scipy.stats._mstats_basic.brunnermunzel (x, y, alternative = "two-sided", distribution = "t")
Computes the Brunner-Munzel test on samples x and y
Missing values in `x` and/or `y` are discarded.
Parameters
----------
x, y : array_like
    Array of samples, should be one-dimensional.
alternative : 'less', 'two-sided', or 'greater', optional
    Whether to get the p-value for the one-sided hypothesis ('less'
    or 'greater') or for the two-sided hypothesis ('two-sided').
    Defaults value is 'two-sided' .
distribution : 't' or 'normal', optional
    Whether to get the p-value by t-distribution or by standard normal
    distribution.
    Defaults value is 't' .
Returns
-------
statistic : float
    The Brunner-Munzer W statistic.
pvalue : float
    p-value assuming an t distribution. One-sided or
    two-sided, depending on the choice of `alternative` and `distribution`.
See Also
--------
mannwhitneyu : Mann-Whitney rank test on two samples.
Notes
-----
For more details on `brunnermunzel`, see `scipy.stats.brunnermunzel`.
Definition at line 3442 of file _mstats_basic.py.
References rankdata().
count_tied_groups()
scipy.stats._mstats_basic.count_tied_groups (x, use_missing = False)
Counts the number of tied values.
Parameters
----------
x : sequence
    Sequence of data on which to counts the ties
use_missing : bool, optional
    Whether to consider missing values as tied.
Returns
-------
count_tied_groups : dict
    Returns a dictionary (nb of ties: nb of groups).
Examples
--------
>>> from scipy.stats import mstats
>>> import numpy as np
>>> z = [0, 0, 0, 2, 2, 2, 3, 3, 4, 5, 6]
>>> mstats.count_tied_groups(z)
{2: 1, 3: 2}
In the above example, the ties were 0 (3x), 2 (3x) and 3 (2x).
>>> z = np.ma.array([0, 0, 1, 2, 2, 2, 3, 3, 4, 5, 6])
>>> mstats.count_tied_groups(z)
{2: 2, 3: 1}
>>> z[[1,-1]] = np.ma.masked
>>> mstats.count_tied_groups(z, use_missing=True)
{2: 2, 3: 1}
Definition at line 199 of file _mstats_basic.py.
References find_repeats().
Referenced by kendalltau(), kendalltau_seasonal(), kruskal(), and mannwhitneyu().
describe()
scipy.stats._mstats_basic.describe (a, axis = 0, ddof = 0, bias = True)
Computes several descriptive statistics of the passed array.
Parameters
----------
a : array_like
    Data array
axis : int or None, optional
    Axis along which to calculate statistics. Default 0. If None,
    compute over the whole array `a`.
ddof : int, optional
    degree of freedom (default 0); note that default ddof is different
    from the same routine in stats.describe
bias : bool, optional
    If False, then the skewness and kurtosis calculations are corrected for
    statistical bias.
Returns
-------
nobs : int
    (size of the data (discarding missing values)
minmax : (int, int)
    min, max
mean : float
    arithmetic mean
variance : float
    unbiased variance
skewness : float
    biased skewness
kurtosis : float
    biased kurtosis
Examples
--------
>>> import numpy as np
>>> from scipy.stats.mstats import describe
>>> ma = np.ma.array(range(6), mask=[0, 0, 0, 1, 1, 1])
>>> describe(ma)
DescribeResult(nobs=3, minmax=(masked_array(data=0,
             mask=False,
       fill_value=999999), masked_array(data=2,
             mask=False,
       fill_value=999999)), mean=1.0, variance=0.6666666666666666,
       skewness=masked_array(data=0., mask=False, fill_value=1e+20),
        kurtosis=-1.5)
Definition at line 2809 of file _mstats_basic.py.
References kurtosis(), and skew().
f_oneway()
scipy.stats._mstats_basic.f_oneway (* args)
Performs a 1-way ANOVA, returning an F-value and probability given
any number of groups.  From Heiman, pp.394-7.
Usage: ``f_oneway(*args)``, where ``*args`` is 2 or more arrays,
one per treatment group.
Returns
-------
statistic : float
    The computed F-value of the test.
pvalue : float
    The associated p-value from the F-distribution.
Definition at line 3354 of file _mstats_basic.py.
References argstoarray().
find_repeats()
scipy.stats._mstats_basic.find_repeats (arr)
Find repeats in arr and return a tuple (repeats, repeat_count).
The input is cast to float64. Masked values are discarded.
Parameters
----------
arr : sequence
    Input array. The array is flattened if it is not 1D.
Returns
-------
repeats : ndarray
    Array of repeated values.
counts : ndarray
    Array of counts.
Examples
--------
>>> from scipy.stats import mstats
>>> mstats.find_repeats([2, 1, 2, 3, 2, 2, 5])
(array([2.]), array([4]))
In the above example, 2 repeats 4 times.
>>> mstats.find_repeats([[10, 20, 1, 2], [5, 5, 4, 4]])
(array([4., 5.]), array([2, 2]))
In the above example, both 4 and 5 repeat 2 times.
Definition at line 154 of file _mstats_basic.py.
Referenced by count_tied_groups(), friedmanchisquare(), mode(), and rankdata().
friedmanchisquare()
scipy.stats._mstats_basic.friedmanchisquare (* args)
Friedman Chi-Square is a non-parametric, one-way within-subjects ANOVA.
This function calculates the Friedman Chi-square test for repeated measures
and returns the result, along with the associated probability value.
Each input is considered a given group. Ideally, the number of treatments
among each group should be equal. If this is not the case, only the first
n treatments are taken into account, where n is the number of treatments
of the smallest group.
If a group has some missing values, the corresponding treatments are masked
in the other groups.
The test statistic is corrected for ties.
Masked values in one group are propagated to the other groups.
Returns
-------
statistic : float
    the test statistic.
pvalue : float
    the associated p-value.
Definition at line 3391 of file _mstats_basic.py.
References argstoarray(), find_repeats(), and rankdata().
kendalltau()
scipy.stats._mstats_basic.kendalltau (x, y, use_ties = True, use_missing = False, method = 'auto', alternative = 'two-sided')
Computes Kendall's rank correlation tau on two variables *x* and *y*.
Parameters
----------
x : sequence
    First data list (for example, time).
y : sequence
    Second data list.
use_ties : {True, False}, optional
    Whether ties correction should be performed.
use_missing : {False, True}, optional
    Whether missing data should be allocated a rank of 0 (False) or the
    average rank (True)
method : {'auto', 'asymptotic', 'exact'}, optional
    Defines which method is used to calculate the p-value [1]_.
    'asymptotic' uses a normal approximation valid for large samples.
    'exact' computes the exact p-value, but can only be used if no ties
    are present. As the sample size increases, the 'exact' computation
    time may grow and the result may lose some precision.
    'auto' is the default and selects the appropriate
    method based on a trade-off between speed and accuracy.
alternative : {'two-sided', 'less', 'greater'}, optional
    Defines the alternative hypothesis. Default is 'two-sided'.
    The following options are available:
    * 'two-sided': the rank correlation is nonzero
    * 'less': the rank correlation is negative (less than zero)
    * 'greater':  the rank correlation is positive (greater than zero)
Returns
-------
res : SignificanceResult
    An object containing attributes:
    statistic : float
       The tau statistic.
    pvalue : float
       The p-value for a hypothesis test whose null hypothesis is
       an absence of association, tau = 0.
References
----------
.. [1] Maurice G. Kendall, "Rank Correlation Methods" (4th Edition),
       Charles Griffin & Co., 1970.
Definition at line 776 of file _mstats_basic.py.
References scipy.stats._stats_py._normtest_finish(), count_tied_groups(), and rankdata().
kendalltau_seasonal()
scipy.stats._mstats_basic.kendalltau_seasonal (x)
Computes a multivariate Kendall's rank correlation tau, for seasonal data.
Parameters
----------
x : 2-D ndarray
    Array of seasonal data, with seasons in columns.
Definition at line 903 of file _mstats_basic.py.
References count_tied_groups(), msign(), and rankdata().
kruskal()
scipy.stats._mstats_basic.kruskal (* args)
Compute the Kruskal-Wallis H-test for independent samples
Parameters
----------
sample1, sample2, ... : array_like
   Two or more arrays with the sample measurements can be given as
   arguments.
Returns
-------
statistic : float
   The Kruskal-Wallis H statistic, corrected for ties
pvalue : float
   The p-value for the test using the assumption that H has a chi
   square distribution
Notes
-----
For more details on `kruskal`, see `scipy.stats.kruskal`.
Examples
--------
>>> from scipy.stats.mstats import kruskal
Random samples from three different brands of batteries were tested
to see how long the charge lasted. Results were as follows:
>>> a = [6.3, 5.4, 5.7, 5.2, 5.0]
>>> b = [6.9, 7.0, 6.1, 7.9]
>>> c = [7.2, 6.9, 6.1, 6.5]
Test the hypotesis that the distribution functions for all of the brands'
durations are identical. Use 5% level of significance.
>>> kruskal(a, b, c)
KruskalResult(statistic=7.113812154696133, pvalue=0.028526948491942164)
The null hypothesis is rejected at the 5% level of significance
because the returned p-value is less than the critical value of 5%.
Definition at line 1574 of file _mstats_basic.py.
References argstoarray(), count_tied_groups(), and rankdata().
ks_1samp()
scipy.stats._mstats_basic.ks_1samp (x, cdf, args = (), alternative = "two-sided", method = 'auto')
Computes the Kolmogorov-Smirnov test on one sample of masked values.
Missing values in `x` are discarded.
Parameters
----------
x : array_like
    a 1-D array of observations of random variables.
cdf : str or callable
    If a string, it should be the name of a distribution in `scipy.stats`.
    If a callable, that callable is used to calculate the cdf.
args : tuple, sequence, optional
    Distribution parameters, used if `cdf` is a string.
alternative : {'two-sided', 'less', 'greater'}, optional
    Indicates the alternative hypothesis.  Default is 'two-sided'.
method : {'auto', 'exact', 'asymp'}, optional
    Defines the method used for calculating the p-value.
    The following options are available (default is 'auto'):
      * 'auto' : use 'exact' for small size arrays, 'asymp' for large
      * 'exact' : use approximation to exact distribution of test statistic
      * 'asymp' : use asymptotic distribution of test statistic
Returns
-------
d : float
    Value of the Kolmogorov Smirnov test
p : float
    Corresponding p-value.
Definition at line 1639 of file _mstats_basic.py.
References scipy.stats._stats_py.ks_1samp().
ks_2samp()
scipy.stats._mstats_basic.ks_2samp (data1, data2, alternative = "two-sided", method = 'auto')
Computes the Kolmogorov-Smirnov test on two samples.
Missing values in `x` and/or `y` are discarded.
Parameters
----------
data1 : array_like
    First data set
data2 : array_like
    Second data set
alternative : {'two-sided', 'less', 'greater'}, optional
    Indicates the alternative hypothesis.  Default is 'two-sided'.
method : {'auto', 'exact', 'asymp'}, optional
    Defines the method used for calculating the p-value.
    The following options are available (default is 'auto'):
      * 'auto' : use 'exact' for small size arrays, 'asymp' for large
      * 'exact' : use approximation to exact distribution of test statistic
      * 'asymp' : use asymptotic distribution of test statistic
Returns
-------
d : float
    Value of the Kolmogorov Smirnov test
p : float
    Corresponding p-value.
Definition at line 1679 of file _mstats_basic.py.
References scipy.stats._stats_py.ks_2samp().
kstest()
scipy.stats._mstats_basic.kstest (data1, data2, args = (), alternative = 'two-sided', method = 'auto')
Parameters
----------
data1 : array_like
data2 : str, callable or array_like
args : tuple, sequence, optional
    Distribution parameters, used if `data1` or `data2` are strings.
alternative : str, as documented in stats.kstest
method : str, as documented in stats.kstest
Returns
-------
tuple of (K-S statistic, probability)
Definition at line 1723 of file _mstats_basic.py.
References scipy.stats._stats_py.kstest().
kurtosis()
scipy.stats._mstats_basic.kurtosis (a, axis = 0, fisher = True, bias = True)
Computes the kurtosis (Fisher or Pearson) of a dataset.
Kurtosis is the fourth central moment divided by the square of the
variance. If Fisher's definition is used, then 3.0 is subtracted from
the result to give 0.0 for a normal distribution.
If bias is False then the kurtosis is calculated using k statistics to
eliminate bias coming from biased moment estimators
Use `kurtosistest` to see if result is close enough to normal.
Parameters
----------
a : array
    data for which the kurtosis is calculated
axis : int or None, optional
    Axis along which the kurtosis is calculated. Default is 0.
    If None, compute over the whole array `a`.
fisher : bool, optional
    If True, Fisher's definition is used (normal ==> 0.0). If False,
    Pearson's definition is used (normal ==> 3.0).
bias : bool, optional
    If False, then the calculations are corrected for statistical bias.
Returns
-------
kurtosis : array
    The kurtosis of values along an axis. If all values are equal,
    return -3 for Fisher's definition and 0 for Pearson's definition.
Notes
-----
For more details about `kurtosis`, see `scipy.stats.kurtosis`.
Definition at line 2744 of file _mstats_basic.py.
Referenced by describe(), and kurtosistest().
kurtosistest()
scipy.stats._mstats_basic.kurtosistest (a, axis = 0, alternative = 'two-sided')
Tests whether a dataset has normal kurtosis
Parameters
----------
a : array_like
    array of the sample data
axis : int or None, optional
   Axis along which to compute test. Default is 0. If None,
   compute over the whole array `a`.
alternative : {'two-sided', 'less', 'greater'}, optional
    Defines the alternative hypothesis.
    The following options are available (default is 'two-sided'):
    * 'two-sided': the kurtosis of the distribution underlying the sample
      is different from that of the normal distribution
    * 'less': the kurtosis of the distribution underlying the sample
      is less than that of the normal distribution
    * 'greater': the kurtosis of the distribution underlying the sample
      is greater than that of the normal distribution
    .. versionadded:: 1.7.0
Returns
-------
statistic : array_like
    The computed z-score for this test.
pvalue : array_like
    The p-value for the hypothesis test
Notes
-----
For more details about `kurtosistest`, see `scipy.stats.kurtosistest`.
Definition at line 2967 of file _mstats_basic.py.
References scipy.stats._stats_py._normtest_finish(), and kurtosis().
Referenced by normaltest().
linregress()
scipy.stats._mstats_basic.linregress (x, y = None)
Linear regression calculation
Note that the non-masked version is used, and that this docstring is
replaced by the non-masked docstring + some info on missing data.
Definition at line 1022 of file _mstats_basic.py.
mannwhitneyu()
scipy.stats._mstats_basic.mannwhitneyu (x, y, use_continuity = True)
Computes the Mann-Whitney statistic
Missing values in `x` and/or `y` are discarded.
Parameters
----------
x : sequence
    Input
y : sequence
    Input
use_continuity : {True, False}, optional
    Whether a continuity correction (1/2.) should be taken into account.
Returns
-------
statistic : float
    The minimum of the Mann-Whitney statistics
pvalue : float
    Approximate two-sided p-value assuming a normal distribution.
Definition at line 1524 of file _mstats_basic.py.
References count_tied_groups(), and rankdata().
mode()
scipy.stats._mstats_basic.mode (a, axis = 0)
Returns an array of the modal (most common) value in the passed array.
Parameters
----------
a : array_like
    n-dimensional array of which to find mode(s).
axis : int or None, optional
    Axis along which to operate. Default is 0. If None, compute over
    the whole array `a`.
Returns
-------
mode : ndarray
    Array of modal values.
count : ndarray
    Array of counts for each mode.
Notes
-----
For more details, see `scipy.stats.mode`.
Examples
--------
>>> import numpy as np
>>> from scipy import stats
>>> from scipy.stats import mstats
>>> m_arr = np.ma.array([1, 1, 0, 0, 0, 0], mask=[0, 0, 1, 1, 1, 0])
>>> mstats.mode(m_arr)  # note that most zeros are masked
ModeResult(mode=array([1.]), count=array([2.]))
Definition at line 302 of file _mstats_basic.py.
References find_repeats().
moment()
scipy.stats._mstats_basic.moment (a, moment = 1, axis = 0)
Calculates the nth moment about the mean for a sample.
Parameters
----------
a : array_like
   data
moment : int, optional
   order of central moment that is returned
axis : int or None, optional
   Axis along which the central moment is computed. Default is 0.
   If None, compute over the whole array `a`.
Returns
-------
n-th central moment : ndarray or float
   The appropriate moment along the given axis or over all values if axis
   is None. The denominator for the moment calculation is the number of
   observations, no degrees of freedom correction is done.
Notes
-----
For more details about `moment`, see `scipy.stats.moment`.
Definition at line 2554 of file _mstats_basic.py.
mquantiles()
scipy.stats._mstats_basic.mquantiles (a, prob = list([.25,.5,.75]), alphap = .4, betap = .4, axis = None, limit = ())
Computes empirical quantiles for a data array.
Samples quantile are defined by ``Q(p) = (1-gamma)*x[j] + gamma*x[j+1]``,
where ``x[j]`` is the j-th order statistic, and gamma is a function of
``j = floor(n*p + m)``, ``m = alphap + p*(1 - alphap - betap)`` and
``g = n*p + m - j``.
Reinterpreting the above equations to compare to **R** lead to the
equation: ``p(k) = (k - alphap)/(n + 1 - alphap - betap)``
Typical values of (alphap,betap) are:
    - (0,1)    : ``p(k) = k/n`` : linear interpolation of cdf
      (**R** type 4)
    - (.5,.5)  : ``p(k) = (k - 1/2.)/n`` : piecewise linear function
      (**R** type 5)
    - (0,0)    : ``p(k) = k/(n+1)`` :
      (**R** type 6)
    - (1,1)    : ``p(k) = (k-1)/(n-1)``: p(k) = mode[F(x[k])].
      (**R** type 7, **R** default)
    - (1/3,1/3): ``p(k) = (k-1/3)/(n+1/3)``: Then p(k) ~ median[F(x[k])].
      The resulting quantile estimates are approximately median-unbiased
      regardless of the distribution of x.
      (**R** type 8)
    - (3/8,3/8): ``p(k) = (k-3/8)/(n+1/4)``: Blom.
      The resulting quantile estimates are approximately unbiased
      if x is normally distributed
      (**R** type 9)
    - (.4,.4)  : approximately quantile unbiased (Cunnane)
    - (.35,.35): APL, used with PWM
Parameters
----------
a : array_like
    Input data, as a sequence or array of dimension at most 2.
prob : array_like, optional
    List of quantiles to compute.
alphap : float, optional
    Plotting positions parameter, default is 0.4.
betap : float, optional
    Plotting positions parameter, default is 0.4.
axis : int, optional
    Axis along which to perform the trimming.
    If None (default), the input array is first flattened.
limit : tuple, optional
    Tuple of (lower, upper) values.
    Values of `a` outside this open interval are ignored.
Returns
-------
mquantiles : MaskedArray
    An array containing the calculated quantiles.
Notes
-----
This formulation is very similar to **R** except the calculation of
``m`` from ``alphap`` and ``betap``, where in **R** ``m`` is defined
with each type.
References
----------
.. [1] *R* statistical software: https://www.r-project.org/
.. [2] *R* ``quantile`` function:
        http://stat.ethz.ch/R-manual/R-devel/library/stats/html/quantile.html
Examples
--------
>>> import numpy as np
>>> from scipy.stats.mstats import mquantiles
>>> a = np.array([6., 47., 49., 15., 42., 41., 7., 39., 43., 40., 36.])
>>> mquantiles(a)
array([ 19.2,  40. ,  42.8])
Using a 2D array, specifying axis and limit.
>>> data = np.array([[   6.,    7.,    1.],
...                  [  47.,   15.,    2.],
...                  [  49.,   36.,    3.],
...                  [  15.,   39.,    4.],
...                  [  42.,   40., -999.],
...                  [  41.,   41., -999.],
...                  [   7., -999., -999.],
...                  [  39., -999., -999.],
...                  [  43., -999., -999.],
...                  [  40., -999., -999.],
...                  [  36., -999., -999.]])
>>> print(mquantiles(data, axis=0, limit=(0, 50)))
[[19.2  14.6   1.45]
 [40.   37.5   2.5 ]
 [42.8  40.05  3.55]]
>>> data[:, 2] = -999.
>>> print(mquantiles(data, axis=0, limit=(0, 50)))
[[19.200000000000003 14.6 --]
 [40.0 37.5 --]
 [42.800000000000004 40.05 --]]
Definition at line 3074 of file _mstats_basic.py.
Referenced by scoreatpercentile().
msign()
scipy.stats._mstats_basic.msign (x)
Returns the sign of x, or 0 if x is masked.
Definition at line 377 of file _mstats_basic.py.
Referenced by kendalltau_seasonal().
normaltest()
scipy.stats._mstats_basic.normaltest (a, axis = 0)
Tests whether a sample differs from a normal distribution.
Parameters
----------
a : array_like
    The array containing the data to be tested.
axis : int or None, optional
    Axis along which to compute test. Default is 0. If None,
    compute over the whole array `a`.
Returns
-------
statistic : float or array
    ``s^2 + k^2``, where ``s`` is the z-score returned by `skewtest` and
    ``k`` is the z-score returned by `kurtosistest`.
pvalue : float or array
   A 2-sided chi squared probability for the hypothesis test.
Notes
-----
For more details about `normaltest`, see `scipy.stats.normaltest`.
Definition at line 3041 of file _mstats_basic.py.
References kurtosistest(), and skewtest().
obrientransform()
scipy.stats._mstats_basic.obrientransform (* args)
Computes a transform on input data (any number of columns).  Used to
test for homogeneity of variance prior to running one-way stats.  Each
array in ``*args`` is one level of a factor.  If an `f_oneway()` run on
the transformed data and found significant, variances are unequal.   From
Maxwell and Delaney, p.112.
Returns: transformed data for use in an ANOVA
Definition at line 3272 of file _mstats_basic.py.
References argstoarray().
pearsonr()
scipy.stats._mstats_basic.pearsonr (x, y)
Pearson correlation coefficient and p-value for testing non-correlation.
The Pearson correlation coefficient [1]_ measures the linear relationship
between two datasets.  The calculation of the p-value relies on the
assumption that each dataset is normally distributed.  (See Kowalski [3]_
for a discussion of the effects of non-normality of the input on the
distribution of the correlation coefficient.)  Like other correlation
coefficients, this one varies between -1 and +1 with 0 implying no
correlation. Correlations of -1 or +1 imply an exact linear relationship.
Parameters
----------
x : (N,) array_like
    Input array.
y : (N,) array_like
    Input array.
Returns
-------
r : float
    Pearson's correlation coefficient.
p-value : float
    Two-tailed p-value.
Warns
-----
PearsonRConstantInputWarning
    Raised if an input is a constant array.  The correlation coefficient
    is not defined in this case, so ``np.nan`` is returned.
PearsonRNearConstantInputWarning
    Raised if an input is "nearly" constant.  The array ``x`` is considered
    nearly constant if ``norm(x - mean(x)) < 1e-13 * abs(mean(x))``.
    Numerical errors in the calculation ``x - mean(x)`` in this case might
    result in an inaccurate calculation of r.
See Also
--------
spearmanr : Spearman rank-order correlation coefficient.
kendalltau : Kendall's tau, a correlation measure for ordinal data.
Notes
-----
The correlation coefficient is calculated as follows:
.. math::
    r = \frac{\sum (x - m_x) (y - m_y)}
             {\sqrt{\sum (x - m_x)^2 \sum (y - m_y)^2}}
where :math:`m_x` is the mean of the vector x and :math:`m_y` is
the mean of the vector y.
Under the assumption that x and y are drawn from
independent normal distributions (so the population correlation coefficient
is 0), the probability density function of the sample correlation
coefficient r is ([1]_, [2]_):
.. math::
    f(r) = \frac{{(1-r^2)}^{n/2-2}}{\mathrm{B}(\frac{1}{2},\frac{n}{2}-1)}
where n is the number of samples, and B is the beta function.  This
is sometimes referred to as the exact distribution of r.  This is
the distribution that is used in `pearsonr` to compute the p-value.
The distribution is a beta distribution on the interval [-1, 1],
with equal shape parameters a = b = n/2 - 1.  In terms of SciPy's
implementation of the beta distribution, the distribution of r is::
    dist = scipy.stats.beta(n/2 - 1, n/2 - 1, loc=-1, scale=2)
The p-value returned by `pearsonr` is a two-sided p-value. The p-value
roughly indicates the probability of an uncorrelated system
producing datasets that have a Pearson correlation at least as extreme
as the one computed from these datasets. More precisely, for a
given sample with correlation coefficient r, the p-value is
the probability that abs(r') of a random sample x' and y' drawn from
the population with zero correlation would be greater than or equal
to abs(r). In terms of the object ``dist`` shown above, the p-value
for a given r and length n can be computed as::
    p = 2*dist.cdf(-abs(r))
When n is 2, the above continuous distribution is not well-defined.
One can interpret the limit of the beta distribution as the shape
parameters a and b approach a = b = 0 as a discrete distribution with
equal probability masses at r = 1 and r = -1.  More directly, one
can observe that, given the data x = [x1, x2] and y = [y1, y2], and
assuming x1 != x2 and y1 != y2, the only possible values for r are 1
and -1.  Because abs(r') for any sample x' and y' with length 2 will
be 1, the two-sided p-value for a sample of length 2 is always 1.
References
----------
.. [1] "Pearson correlation coefficient", Wikipedia,
       https://en.wikipedia.org/wiki/Pearson_correlation_coefficient
.. [2] Student, "Probable error of a correlation coefficient",
       Biometrika, Volume 6, Issue 2-3, 1 September 1908, pp. 302-310.
.. [3] C. J. Kowalski, "On the Effects of Non-Normality on the Distribution
       of the Sample Product-Moment Correlation Coefficient"
       Journal of the Royal Statistical Society. Series C (Applied
       Statistics), Vol. 21, No. 1 (1972), pp. 1-12.
Examples
--------
>>> import numpy as np
>>> from scipy import stats
>>> from scipy.stats import mstats
>>> mstats.pearsonr([1, 2, 3, 4, 5], [10, 9, 2.5, 6, 4])
(-0.7426106572325057, 0.1505558088534455)
There is a linear dependence between x and y if y = a + b*x + e, where
a,b are constants and e is a random error term, assumed to be independent
of x. For simplicity, assume that x is standard normal, a=0, b=1 and let
e follow a normal distribution with mean zero and standard deviation s>0.
>>> s = 0.5
>>> x = stats.norm.rvs(size=500)
>>> e = stats.norm.rvs(scale=s, size=500)
>>> y = x + e
>>> mstats.pearsonr(x, y)
(0.9029601878969703, 8.428978827629898e-185) # may vary
This should be close to the exact value given by
>>> 1/np.sqrt(1 + s**2)
0.8944271909999159
For s=0.5, we observe a high level of correlation. In general, a large
variance of the noise reduces the correlation, while the correlation
approaches one as the variance of the error goes to zero.
It is important to keep in mind that no correlation does not imply
independence unless (x, y) is jointly normal. Correlation can even be zero
when there is a very simple dependence structure: if X follows a
standard normal distribution, let y = abs(x). Note that the correlation
between x and y is zero. Indeed, since the expectation of x is zero,
cov(x, y) = E[x*y]. By definition, this equals E[x*abs(x)] which is zero
by symmetry. The following lines of code illustrate this observation:
>>> y = np.abs(x)
>>> mstats.pearsonr(x, y)
(-0.016172891856853524, 0.7182823678751942) # may vary
A non-zero correlation coefficient can be misleading. For example, if X has
a standard normal distribution, define y = x if x < 0 and y = 0 otherwise.
A simple calculation shows that corr(x, y) = sqrt(2/Pi) = 0.797...,
implying a high level of correlation:
>>> y = np.where(x < 0, x, 0)
>>> mstats.pearsonr(x, y)
(0.8537091583771509, 3.183461621422181e-143) # may vary
This is unintuitive since there is no dependence of x and y if x is larger
than zero which happens in about half of the cases if we sample x and y.
Definition at line 382 of file _mstats_basic.py.
References scipy.stats._stats_py.pearsonr().
plotting_positions()
scipy.stats._mstats_basic.plotting_positions (data, alpha = 0.4, beta = 0.4)
Returns plotting positions (or empirical percentile points) for the data.
Plotting positions are defined as ``(i-alpha)/(n+1-alpha-beta)``, where:
    - i is the rank order statistics
    - n is the number of unmasked values along the given axis
    - `alpha` and `beta` are two parameters.
Typical values for `alpha` and `beta` are:
    - (0,1)    : ``p(k) = k/n``, linear interpolation of cdf (R, type 4)
    - (.5,.5)  : ``p(k) = (k-1/2.)/n``, piecewise linear function
      (R, type 5)
    - (0,0)    : ``p(k) = k/(n+1)``, Weibull (R type 6)
    - (1,1)    : ``p(k) = (k-1)/(n-1)``, in this case,
      ``p(k) = mode[F(x[k])]``. That's R default (R type 7)
    - (1/3,1/3): ``p(k) = (k-1/3)/(n+1/3)``, then
      ``p(k) ~ median[F(x[k])]``.
      The resulting quantile estimates are approximately median-unbiased
      regardless of the distribution of x. (R type 8)
    - (3/8,3/8): ``p(k) = (k-3/8)/(n+1/4)``, Blom.
      The resulting quantile estimates are approximately unbiased
      if x is normally distributed (R type 9)
    - (.4,.4)  : approximately quantile unbiased (Cunnane)
    - (.35,.35): APL, used with PWM
    - (.3175, .3175): used in scipy.stats.probplot
Parameters
----------
data : array_like
    Input data, as a sequence or array of dimension at most 2.
alpha : float, optional
    Plotting positions parameter. Default is 0.4.
beta : float, optional
    Plotting positions parameter. Default is 0.4.
Returns
-------
positions : MaskedArray
    The calculated plotting positions.
Definition at line 3218 of file _mstats_basic.py.
pointbiserialr()
scipy.stats._mstats_basic.pointbiserialr (x, y)
Calculates a point biserial correlation coefficient and its p-value.
Parameters
----------
x : array_like of bools
    Input array.
y : array_like
    Input array.
Returns
-------
correlation : float
    R value
pvalue : float
    2-tailed p-value
Notes
-----
Missing values are considered pair-wise: if a value is missing in x,
the corresponding value in y is masked.
For more details on `pointbiserialr`, see `scipy.stats.pointbiserialr`.
Definition at line 971 of file _mstats_basic.py.
rankdata()
scipy.stats._mstats_basic.rankdata (data, axis = None, use_missing = False)
Returns the rank (also known as order statistics) of each data point
along the given axis.
If some values are tied, their rank is averaged.
If some values are masked, their rank is set to 0 if use_missing is False,
or set to the average rank of the unmasked values if use_missing is True.
Parameters
----------
data : sequence
    Input data. The data is transformed to a masked array
axis : {None,int}, optional
    Axis along which to perform the ranking.
    If None, the array is first flattened. An exception is raised if
    the axis is specified for arrays with a dimension larger than 2
use_missing : bool, optional
    Whether the masked values have a rank of 0 (False) or equal to the
    average rank of the unmasked values (True).
Definition at line 251 of file _mstats_basic.py.
References find_repeats().
Referenced by brunnermunzel(), friedmanchisquare(), kendalltau(), kendalltau_seasonal(), kruskal(), mannwhitneyu(), and spearmanr().
scoreatpercentile()
scipy.stats._mstats_basic.scoreatpercentile (data, per, limit = (), alphap = .4, betap = .4)
Calculate the score at the given 'per' percentile of the
sequence a.  For example, the score at per=50 is the median.
This function is a shortcut to mquantile
Definition at line 3203 of file _mstats_basic.py.
References mquantiles().
sem()
scipy.stats._mstats_basic.sem (a, axis = 0, ddof = 1)
Calculates the standard error of the mean of the input array.
Also sometimes called standard error of measurement.
Parameters
----------
a : array_like
    An array containing the values for which the standard error is
    returned.
axis : int or None, optional
    If axis is None, ravel `a` first. If axis is an integer, this will be
    the axis over which to operate. Defaults to 0.
ddof : int, optional
    Delta degrees-of-freedom. How many degrees of freedom to adjust
    for bias in limited samples relative to the population estimate
    of variance. Defaults to 1.
Returns
-------
s : ndarray or float
    The standard error of the mean in the sample(s), along the input axis.
Notes
-----
The default value for `ddof` changed in scipy 0.15.0 to be consistent with
`scipy.stats.sem` as well as with the most common definition used (like in
the R documentation).
Examples
--------
Find standard error along the first axis:
>>> import numpy as np
>>> from scipy import stats
>>> a = np.arange(20).reshape(5,4)
>>> print(stats.mstats.sem(a))
[2.8284271247461903 2.8284271247461903 2.8284271247461903
 2.8284271247461903]
Find standard error across the whole array, using n degrees of freedom:
>>> print(stats.mstats.sem(a, axis=None, ddof=0))
1.2893796958227628
Definition at line 3298 of file _mstats_basic.py.
sen_seasonal_slopes()
scipy.stats._mstats_basic.sen_seasonal_slopes (x)
Computes seasonal Theil-Sen and Kendall slope estimators.
The seasonal generalization of Sen's slope computes the slopes between all
pairs of values within a "season" (column) of a 2D array. It returns an
array containing the median of these "within-season" slopes for each
season (the Theil-Sen slope estimator of each season), and it returns the
median of the within-season slopes across all seasons (the seasonal Kendall
slope estimator).
Parameters
----------
x : 2D array_like
    Each column of `x` contains measurements of the dependent variable
    within a season. The independent variable (usually time) of each season
    is assumed to be ``np.arange(x.shape[0])``.
Returns
-------
result : ``SenSeasonalSlopesResult`` instance
    The return value is an object with the following attributes:
    intra_slope : ndarray
        For each season, the Theil-Sen slope estimator: the median of
        within-season slopes.
    inter_slope : float
        The seasonal Kendall slope estimateor: the median of within-season
        slopes *across all* seasons.
See Also
--------
theilslopes : the analogous function for non-seasonal data
scipy.stats.theilslopes : non-seasonal slopes for non-masked arrays
Notes
-----
The slopes :math:`d_{ijk}` within season :math:`i` are:
.. math::
    d_{ijk} = \frac{x_{ij} - x_{ik}}
                        {j - k}
for pairs of distinct integer indices :math:`j, k` of :math:`x`.
Element :math:`i` of the returned `intra_slope` array is the median of the
:math:`d_{ijk}` over all :math:`j < k`; this is the Theil-Sen slope
estimator of season :math:`i`. The returned `inter_slope` value, better
known as the seasonal Kendall slope estimator, is the median of the
:math:`d_{ijk}` over all :math:`i, j, k`.
References
----------
.. [1] Hirsch, Robert M., James R. Slack, and Richard A. Smith.
       "Techniques of trend analysis for monthly water quality data."
       *Water Resources Research* 18.1 (1982): 107-121.
Examples
--------
Suppose we have 100 observations of a dependent variable for each of four
seasons:
>>> import numpy as np
>>> rng = np.random.default_rng()
>>> x = rng.random(size=(100, 4))
We compute the seasonal slopes as:
>>> from scipy import stats
>>> intra_slope, inter_slope = stats.mstats.sen_seasonal_slopes(x)
If we define a function to compute all slopes between observations within
a season:
>>> def dijk(yi):
...     n = len(yi)
...     x = np.arange(n)
...     dy = yi - yi[:, np.newaxis]
...     dx = x - x[:, np.newaxis]
...     # we only want unique pairs of distinct indices
...     mask = np.triu(np.ones((n, n), dtype=bool), k=1)
...     return dy[mask]/dx[mask]
then element ``i`` of ``intra_slope`` is the median of ``dijk[x[:, i]]``:
>>> i = 2
>>> np.allclose(np.median(dijk(x[:, i])), intra_slope[i])
True
and ``inter_slope`` is the median of the values returned by ``dijk`` for
all seasons:
>>> all_slopes = np.concatenate([dijk(x[:, i]) for i in range(x.shape[1])])
>>> np.allclose(np.median(all_slopes), inter_slope)
True
Because the data are randomly generated, we would expect the median slopes
to be nearly zero both within and across all seasons, and indeed they are:
>>> intra_slope.data
array([ 0.00124504, -0.00277761, -0.00221245, -0.00036338])
>>> inter_slope
-0.0010511779872922058
Definition at line 1200 of file _mstats_basic.py.
siegelslopes()
scipy.stats._mstats_basic.siegelslopes (y, x = None, method = "hierarchical")
Computes the Siegel estimator for a set of points (x, y).
`siegelslopes` implements a method for robust linear regression
using repeated medians to fit a line to the points (x, y).
The method is robust to outliers with an asymptotic breakdown point
of 50%.
Parameters
----------
y : array_like
    Dependent variable.
x : array_like or None, optional
    Independent variable. If None, use ``arange(len(y))`` instead.
method : {'hierarchical', 'separate'}
    If 'hierarchical', estimate the intercept using the estimated
    slope ``slope`` (default option).
    If 'separate', estimate the intercept independent of the estimated
    slope. See Notes for details.
Returns
-------
result : ``SiegelslopesResult`` instance
    The return value is an object with the following attributes:
    slope : float
        Estimate of the slope of the regression line.
    intercept : float
        Estimate of the intercept of the regression line.
See Also
--------
theilslopes : a similar technique without repeated medians
Notes
-----
For more details on `siegelslopes`, see `scipy.stats.siegelslopes`.
Definition at line 1139 of file _mstats_basic.py.
skew()
scipy.stats._mstats_basic.skew (a, axis = 0, bias = True)
Computes the skewness of a data set.
Parameters
----------
a : ndarray
    data
axis : int or None, optional
    Axis along which skewness is calculated. Default is 0.
    If None, compute over the whole array `a`.
bias : bool, optional
    If False, then the calculations are corrected for statistical bias.
Returns
-------
skewness : ndarray
    The skewness of values along an axis, returning 0 where all values are
    equal.
Notes
-----
For more details about `skew`, see `scipy.stats.skew`.
Definition at line 2699 of file _mstats_basic.py.
Referenced by describe(), and skewtest().
skewtest()
scipy.stats._mstats_basic.skewtest (a, axis = 0, alternative = 'two-sided')
Tests whether the skew is different from the normal distribution.
Parameters
----------
a : array_like
    The data to be tested
axis : int or None, optional
   Axis along which statistics are calculated. Default is 0.
   If None, compute over the whole array `a`.
alternative : {'two-sided', 'less', 'greater'}, optional
    Defines the alternative hypothesis. Default is 'two-sided'.
    The following options are available:
    * 'two-sided': the skewness of the distribution underlying the sample
      is different from that of the normal distribution (i.e. 0)
    * 'less': the skewness of the distribution underlying the sample
      is less than that of the normal distribution
    * 'greater': the skewness of the distribution underlying the sample
      is greater than that of the normal distribution
    .. versionadded:: 1.7.0
Returns
-------
statistic : array_like
    The computed z-score for this test.
pvalue : array_like
    A p-value for the hypothesis test
Notes
-----
For more details about `skewtest`, see `scipy.stats.skewtest`.
Definition at line 2906 of file _mstats_basic.py.
References scipy.stats._stats_py._normtest_finish(), and skew().
Referenced by normaltest().
spearmanr()
scipy.stats._mstats_basic.spearmanr (x, y = None, use_ties = True, axis = None, nan_policy = 'propagate', alternative = 'two-sided')
Calculates a Spearman rank-order correlation coefficient and the p-value
to test for non-correlation.
The Spearman correlation is a nonparametric measure of the linear
relationship between two datasets. Unlike the Pearson correlation, the
Spearman correlation does not assume that both datasets are normally
distributed. Like other correlation coefficients, this one varies
between -1 and +1 with 0 implying no correlation. Correlations of -1 or
+1 imply a monotonic relationship. Positive correlations imply that
as `x` increases, so does `y`. Negative correlations imply that as `x`
increases, `y` decreases.
Missing values are discarded pair-wise: if a value is missing in `x`, the
corresponding value in `y` is masked.
The p-value roughly indicates the probability of an uncorrelated system
producing datasets that have a Spearman correlation at least as extreme
as the one computed from these datasets. The p-values are not entirely
reliable but are probably reasonable for datasets larger than 500 or so.
Parameters
----------
x, y : 1D or 2D array_like, y is optional
    One or two 1-D or 2-D arrays containing multiple variables and
    observations. When these are 1-D, each represents a vector of
    observations of a single variable. For the behavior in the 2-D case,
    see under ``axis``, below.
use_ties : bool, optional
    DO NOT USE.  Does not do anything, keyword is only left in place for
    backwards compatibility reasons.
axis : int or None, optional
    If axis=0 (default), then each column represents a variable, with
    observations in the rows. If axis=1, the relationship is transposed:
    each row represents a variable, while the columns contain observations.
    If axis=None, then both arrays will be raveled.
nan_policy : {'propagate', 'raise', 'omit'}, optional
    Defines how to handle when input contains nan. 'propagate' returns nan,
    'raise' throws an error, 'omit' performs the calculations ignoring nan
    values. Default is 'propagate'.
alternative : {'two-sided', 'less', 'greater'}, optional
    Defines the alternative hypothesis. Default is 'two-sided'.
    The following options are available:
    * 'two-sided': the correlation is nonzero
    * 'less': the correlation is negative (less than zero)
    * 'greater':  the correlation is positive (greater than zero)
    .. versionadded:: 1.7.0
Returns
-------
res : SignificanceResult
    An object containing attributes:
    statistic : float or ndarray (2-D square)
        Spearman correlation matrix or correlation coefficient (if only 2
        variables are given as parameters). Correlation matrix is square
        with length equal to total number of variables (columns or rows) in
        ``a`` and ``b`` combined.
    pvalue : float
        The p-value for a hypothesis test whose null hypothesis
        is that two sets of data are linearly uncorrelated. See
        `alternative` above for alternative hypotheses. `pvalue` has the
        same shape as `statistic`.
References
----------
[CRCProbStat2000] section 14.7
Definition at line 554 of file _mstats_basic.py.
References scipy.stats._stats_py._ttest_finish(), and rankdata().
stde_median()
scipy.stats._mstats_basic.stde_median (data, axis = None)
Returns the McKean-Schrader estimate of the standard error of the sample
median along the given axis. masked values are discarded.
Parameters
----------
data : ndarray
    Data to trim.
axis : {None,int}, optional
    Axis along which to perform the trimming.
    If None, the input array is first flattened.
Definition at line 2873 of file _mstats_basic.py.
theilslopes()
scipy.stats._mstats_basic.theilslopes (y, x = None, alpha = 0.95, method = 'separate')
Computes the Theil-Sen estimator for a set of points (x, y).
`theilslopes` implements a method for robust linear regression.  It
computes the slope as the median of all slopes between paired values.
Parameters
----------
y : array_like
Dependent variable.
x : array_like or None, optional
Independent variable. If None, use ``arange(len(y))`` instead.
alpha : float, optional
Confidence degree between 0 and 1. Default is 95% confidence.
Note that `alpha` is symmetric around 0.5, i.e. both 0.1 and 0.9 are
interpreted as "find the 90% confidence interval".
method : {'joint', 'separate'}, optional
Method to be used for computing estimate for intercept.
Following methods are supported,
* 'joint': Uses np.median(y - slope * x) as intercept.
* 'separate': Uses np.median(y) - slope * np.median(x)
              as intercept.
The default is 'separate'.
.. versionadded:: 1.8.0
Returns
-------
result : ``TheilslopesResult`` instance
The return value is an object with the following attributes:
slope : float
Theil slope.
intercept : float
Intercept of the Theil line.
low_slope : float
Lower bound of the confidence interval on `slope`.
high_slope : float
Upper bound of the confidence interval on `slope`.
See Also
--------
siegelslopes : a similar technique using repeated medians
Notes
-----
For more details on `theilslopes`, see `scipy.stats.theilslopes`.
Definition at line 1069 of file _mstats_basic.py.
tmax()
scipy.stats._mstats_basic.tmax (a, upperlimit = None, axis = 0, inclusive = True)
Compute the trimmed maximum
This function computes the maximum value of an array along a given axis,
while ignoring values larger than a specified upper limit.
Parameters
----------
a : array_like
    array of values
upperlimit : None or float, optional
    Values in the input array greater than the given limit will be ignored.
    When upperlimit is None, then all values are used. The default value
    is None.
axis : int or None, optional
    Axis along which to operate. Default is 0. If None, compute over the
    whole array `a`.
inclusive : {True, False}, optional
    This flag determines whether values exactly equal to the upper limit
    are included.  The default value is True.
Returns
-------
tmax : float, int or ndarray
Notes
-----
For more details on `tmax`, see `scipy.stats.tmax`.
Examples
--------
>>> import numpy as np
>>> from scipy.stats import mstats
>>> a = np.array([[6, 8, 3, 0],
...               [3, 9, 1, 2],
...               [8, 7, 8, 2],
...               [5, 6, 0, 2],
...               [4, 5, 5, 2]])
...
...
>>> mstats.tmax(a, 4)
masked_array(data=[4, --, 3, 2],
             mask=[False,  True, False, False],
       fill_value=999999)
Definition at line 2341 of file _mstats_basic.py.
References trima().
tmean()
scipy.stats._mstats_basic.tmean (a, limits = None, inclusive = (True, True), axis = None)
Compute the trimmed mean.
Parameters
----------
a : array_like
    Array of values.
limits : None or (lower limit, upper limit), optional
    Values in the input array less than the lower limit or greater than the
    upper limit will be ignored.  When limits is None (default), then all
    values are used.  Either of the limit values in the tuple can also be
    None representing a half-open interval.
inclusive : (bool, bool), optional
    A tuple consisting of the (lower flag, upper flag).  These flags
    determine whether values exactly equal to the lower or upper limits
    are included.  The default value is (True, True).
axis : int or None, optional
    Axis along which to operate. If None, compute over the
    whole array. Default is None.
Returns
-------
tmean : float
Notes
-----
For more details on `tmean`, see `scipy.stats.tmean`.
Examples
--------
>>> import numpy as np
>>> from scipy.stats import mstats
>>> a = np.array([[6, 8, 3, 0],
...               [3, 9, 1, 2],
...               [8, 7, 8, 2],
...               [5, 6, 0, 2],
...               [4, 5, 5, 2]])
...
...
>>> mstats.tmean(a, (2,5))
3.3
>>> mstats.tmean(a, (2,5), axis=0)
masked_array(data=[4.0, 5.0, 4.0, 2.0],
             mask=[False, False, False, False],
       fill_value=1e+20)
Definition at line 2197 of file _mstats_basic.py.
References trima().
tmin()
scipy.stats._mstats_basic.tmin (a, lowerlimit = None, axis = 0, inclusive = True)
Compute the trimmed minimum
Parameters
----------
a : array_like
    array of values
lowerlimit : None or float, optional
    Values in the input array less than the given limit will be ignored.
    When lowerlimit is None, then all values are used. The default value
    is None.
axis : int or None, optional
    Axis along which to operate. Default is 0. If None, compute over the
    whole array `a`.
inclusive : {True, False}, optional
    This flag determines whether values exactly equal to the lower limit
    are included.  The default value is True.
Returns
-------
tmin : float, int or ndarray
Notes
-----
For more details on `tmin`, see `scipy.stats.tmin`.
Examples
--------
>>> import numpy as np
>>> from scipy.stats import mstats
>>> a = np.array([[6, 8, 3, 0],
...               [3, 2, 1, 2],
...               [8, 1, 8, 2],
...               [5, 3, 0, 2],
...               [4, 7, 5, 2]])
...
>>> mstats.tmin(a, 5)
masked_array(data=[5, 7, 5, --],
             mask=[False, False, False,  True],
       fill_value=999999)
Definition at line 2293 of file _mstats_basic.py.
References trima().
trim()
scipy.stats._mstats_basic.trim (a, limits = None, inclusive = (True,True), relative = False, axis = None)
Trims an array by masking the data outside some given limits.
Returns a masked version of the input array.
%s
Examples
--------
>>> from scipy.stats.mstats import trim
>>> z = [ 1, 2, 3, 4, 5, 6, 7, 8, 9,10]
>>> print(trim(z,(3,8)))
[-- -- 3 4 5 6 7 8 -- --]
>>> print(trim(z,(0.1,0.2),relative=True))
[-- 2 3 4 5 6 7 8 -- --]
Definition at line 1904 of file _mstats_basic.py.
References trima(), and trimr().
trima()
scipy.stats._mstats_basic.trima (a, limits = None, inclusive = (True,True))
Trims an array by masking the data outside some given limits.
Returns a masked version of the input array.
Parameters
----------
a : array_like
    Input array.
limits : {None, tuple}, optional
    Tuple of (lower limit, upper limit) in absolute values.
    Values of the input array lower (greater) than the lower (upper) limit
    will be masked.  A limit is None indicates an open interval.
inclusive : (bool, bool) tuple, optional
    Tuple of (lower flag, upper flag), indicating whether values exactly
    equal to the lower (upper) limit are allowed.
Examples
--------
>>> from scipy.stats.mstats import trima
>>> import numpy as np
>>> a = np.arange(10)
The interval is left-closed and right-open, i.e., `[2, 8)`.
Trim the array by keeping only values in the interval.
>>> trima(a, limits=(2, 8), inclusive=(True, False))
masked_array(data=[--, --, 2, 3, 4, 5, 6, 7, --, --],
             mask=[ True,  True, False, False, False, False, False, False,
                    True,  True],
       fill_value=999999)
Definition at line 1744 of file _mstats_basic.py.
Referenced by tmax(), tmean(), tmin(), trim(), trimmed_mean(), trimmed_std(), trimmed_var(), and tsem().
trimboth()
scipy.stats._mstats_basic.trimboth (data, proportiontocut = 0.2, inclusive = (True,True), axis = None)
Trims the smallest and largest data values.
Trims the `data` by masking the ``int(proportiontocut * n)`` smallest and
``int(proportiontocut * n)`` largest values of data along the given axis,
where n is the number of unmasked values before trimming.
Parameters
----------
data : ndarray
    Data to trim.
proportiontocut : float, optional
    Percentage of trimming (as a float between 0 and 1).
    If n is the number of unmasked values before trimming, the number of
    values after trimming is ``(1 - 2*proportiontocut) * n``.
    Default is 0.2.
inclusive : {(bool, bool) tuple}, optional
    Tuple indicating whether the number of data being masked on each side
    should be rounded (True) or truncated (False).
axis : int, optional
    Axis along which to perform the trimming.
    If None, the input array is first flattened.
Definition at line 1932 of file _mstats_basic.py.
References trimr().
trimmed_mean()
scipy.stats._mstats_basic.trimmed_mean (a, limits = (0.1,0.1), inclusive = (1,1), relative = True, axis = None)
Returns the trimmed mean of the data along the given axis.
%s
Definition at line 2006 of file _mstats_basic.py.
References trima(), and trimr().
trimmed_std()
scipy.stats._mstats_basic.trimmed_std (a, limits = (0.1,0.1), inclusive = (1,1), relative = True, axis = None, ddof = 0)
Returns the trimmed standard deviation of the data along the given axis.
%s
ddof : {0,integer}, optional
    Means Delta Degrees of Freedom. The denominator used during computations
    is (n-ddof). DDOF=0 corresponds to a biased estimate, DDOF=1 to an un-
    biased estimate of the variance.
Definition at line 2050 of file _mstats_basic.py.
References trima(), and trimr().
trimmed_stde()
scipy.stats._mstats_basic.trimmed_stde (a, limits = (0.1,0.1), inclusive = (1,1), axis = None)
Returns the standard error of the trimmed mean along the given axis.
Parameters
----------
a : sequence
    Input array
limits : {(0.1,0.1), tuple of float}, optional
    tuple (lower percentage, upper percentage) to cut  on each side of the
    array, with respect to the number of unmasked data.
    If n is the number of unmasked data before trimming, the values
    smaller than ``n * limits[0]`` and the values larger than
    ``n * `limits[1]`` are masked, and the total number of unmasked
    data after trimming is ``n * (1.-sum(limits))``.  In each case,
    the value of one limit can be set to None to indicate an open interval.
    If `limits` is None, no trimming is performed.
inclusive : {(bool, bool) tuple} optional
    Tuple indicating whether the number of data being masked on each side
    should be rounded (True) or truncated (False).
axis : int, optional
    Axis along which to trim.
Returns
-------
trimmed_stde : scalar or ndarray
Definition at line 2074 of file _mstats_basic.py.
trimmed_var()
scipy.stats._mstats_basic.trimmed_var (a, limits = (0.1,0.1), inclusive = (1,1), relative = True, axis = None, ddof = 0)
Returns the trimmed variance of the data along the given axis.
%s
ddof : {0,integer}, optional
    Means Delta Degrees of Freedom. The denominator used during computations
    is (n-ddof). DDOF=0 corresponds to a biased estimate, DDOF=1 to an un-
    biased estimate of the variance.
Definition at line 2025 of file _mstats_basic.py.
References trima(), and trimr().
trimr()
scipy.stats._mstats_basic.trimr (a, limits = None, inclusive = (True, True), axis = None)
Trims an array by masking some proportion of the data on each end.
Returns a masked version of the input array.
Parameters
----------
a : sequence
    Input array.
limits : {None, tuple}, optional
    Tuple of the percentages to cut on each side of the array, with respect
    to the number of unmasked data, as floats between 0. and 1.
    Noting n the number of unmasked data before trimming, the
    (n*limits[0])th smallest data and the (n*limits[1])th largest data are
    masked, and the total number of unmasked data after trimming is
    n*(1.-sum(limits)).  The value of one limit can be set to None to
    indicate an open interval.
inclusive : {(True,True) tuple}, optional
    Tuple of flags indicating whether the number of data being masked on
    the left (right) end should be truncated (True) or rounded (False) to
    integers.
axis : {None,int}, optional
    Axis along which to trim. If None, the whole array is trimmed, but its
    shape is maintained.
Definition at line 1803 of file _mstats_basic.py.
Referenced by trim(), trimboth(), trimmed_mean(), trimmed_std(), trimmed_var(), and trimtail().
trimtail()
scipy.stats._mstats_basic.trimtail (data, proportiontocut = 0.2, tail = 'left', inclusive = (True,True), axis = None)
Trims the data by masking values from one tail.
Parameters
----------
data : array_like
    Data to trim.
proportiontocut : float, optional
    Percentage of trimming. If n is the number of unmasked values
    before trimming, the number of values after trimming is
    ``(1 - proportiontocut) * n``.  Default is 0.2.
tail : {'left','right'}, optional
    If 'left' the `proportiontocut` lowest values will be masked.
    If 'right' the `proportiontocut` highest values will be masked.
    Default is 'left'.
inclusive : {(bool, bool) tuple}, optional
    Tuple indicating whether the number of data being masked on each side
    should be rounded (True) or truncated (False).  Default is
    (True, True).
axis : int, optional
    Axis along which to perform the trimming.
    If None, the input array is first flattened.  Default is None.
Returns
-------
trimtail : ndarray
    Returned array of same shape as `data` with masked tail values.
Definition at line 1961 of file _mstats_basic.py.
References trimr().
tsem()
scipy.stats._mstats_basic.tsem (a, limits = None, inclusive = (True, True), axis = 0, ddof = 1)
Compute the trimmed standard error of the mean.
This function finds the standard error of the mean for given
values, ignoring values outside the given `limits`.
Parameters
----------
a : array_like
    array of values
limits : None or (lower limit, upper limit), optional
    Values in the input array less than the lower limit or greater than the
    upper limit will be ignored. When limits is None, then all values are
    used. Either of the limit values in the tuple can also be None
    representing a half-open interval.  The default value is None.
inclusive : (bool, bool), optional
    A tuple consisting of the (lower flag, upper flag).  These flags
    determine whether values exactly equal to the lower or upper limits
    are included.  The default value is (True, True).
axis : int or None, optional
    Axis along which to operate. If None, compute over the
    whole array. Default is zero.
ddof : int, optional
    Delta degrees of freedom. Default is 1.
Returns
-------
tsem : float
Notes
-----
For more details on `tsem`, see `scipy.stats.tsem`.
Definition at line 2393 of file _mstats_basic.py.
References trima().
ttest_1samp()
scipy.stats._mstats_basic.ttest_1samp (a, popmean, axis = 0, alternative = 'two-sided')
Calculates the T-test for the mean of ONE group of scores.
Parameters
----------
a : array_like
    sample observation
popmean : float or array_like
    expected value in null hypothesis, if array_like than it must have the
    same shape as `a` excluding the axis dimension
axis : int or None, optional
    Axis along which to compute test. If None, compute over the whole
    array `a`.
alternative : {'two-sided', 'less', 'greater'}, optional
    Defines the alternative hypothesis.
    The following options are available (default is 'two-sided'):
    * 'two-sided': the mean of the underlying distribution of the sample
      is different than the given population mean (`popmean`)
    * 'less': the mean of the underlying distribution of the sample is
      less than the given population mean (`popmean`)
    * 'greater': the mean of the underlying distribution of the sample is
      greater than the given population mean (`popmean`)
    .. versionadded:: 1.7.0
Returns
-------
statistic : float or array
    t-statistic
pvalue : float or array
    The p-value
Notes
-----
For more details on `ttest_1samp`, see `scipy.stats.ttest_1samp`.
Definition at line 1319 of file _mstats_basic.py.
References scipy.stats._stats_py._ttest_finish().
ttest_ind()
scipy.stats._mstats_basic.ttest_ind (a, b, axis = 0, equal_var = True, alternative = 'two-sided')
Calculates the T-test for the means of TWO INDEPENDENT samples of scores.
Parameters
----------
a, b : array_like
    The arrays must have the same shape, except in the dimension
    corresponding to `axis` (the first, by default).
axis : int or None, optional
    Axis along which to compute test. If None, compute over the whole
    arrays, `a`, and `b`.
equal_var : bool, optional
    If True, perform a standard independent 2 sample test that assumes equal
    population variances.
    If False, perform Welch's t-test, which does not assume equal population
    variance.
    .. versionadded:: 0.17.0
alternative : {'two-sided', 'less', 'greater'}, optional
    Defines the alternative hypothesis.
    The following options are available (default is 'two-sided'):
    * 'two-sided': the means of the distributions underlying the samples
      are unequal.
    * 'less': the mean of the distribution underlying the first sample
      is less than the mean of the distribution underlying the second
      sample.
    * 'greater': the mean of the distribution underlying the first
      sample is greater than the mean of the distribution underlying
      the second sample.
    .. versionadded:: 1.7.0
Returns
-------
statistic : float or array
    The calculated t-statistic.
pvalue : float or array
    The p-value.
Notes
-----
For more details on `ttest_ind`, see `scipy.stats.ttest_ind`.
Definition at line 1381 of file _mstats_basic.py.
References scipy.stats._stats_py._ttest_finish().
ttest_rel()
scipy.stats._mstats_basic.ttest_rel (a, b, axis = 0, alternative = 'two-sided')
Calculates the T-test on TWO RELATED samples of scores, a and b.
Parameters
----------
a, b : array_like
    The arrays must have the same shape.
axis : int or None, optional
    Axis along which to compute test. If None, compute over the whole
    arrays, `a`, and `b`.
alternative : {'two-sided', 'less', 'greater'}, optional
    Defines the alternative hypothesis.
    The following options are available (default is 'two-sided'):
    * 'two-sided': the means of the distributions underlying the samples
      are unequal.
    * 'less': the mean of the distribution underlying the first sample
      is less than the mean of the distribution underlying the second
      sample.
    * 'greater': the mean of the distribution underlying the first
      sample is greater than the mean of the distribution underlying
      the second sample.
    .. versionadded:: 1.7.0
Returns
-------
statistic : float or array
    t-statistic
pvalue : float or array
    two-tailed p-value
Notes
-----
For more details on `ttest_rel`, see `scipy.stats.ttest_rel`.
Definition at line 1462 of file _mstats_basic.py.
References scipy.stats._stats_py._ttest_finish().
tvar()
scipy.stats._mstats_basic.tvar (a, limits = None, inclusive = (True, True), axis = 0, ddof = 1)
Compute the trimmed variance
This function computes the sample variance of an array of values,
while ignoring values which are outside of given `limits`.
Parameters
----------
a : array_like
    Array of values.
limits : None or (lower limit, upper limit), optional
    Values in the input array less than the lower limit or greater than the
    upper limit will be ignored. When limits is None, then all values are
    used. Either of the limit values in the tuple can also be None
    representing a half-open interval.  The default value is None.
inclusive : (bool, bool), optional
    A tuple consisting of the (lower flag, upper flag).  These flags
    determine whether values exactly equal to the lower or upper limits
    are included.  The default value is (True, True).
axis : int or None, optional
    Axis along which to operate. If None, compute over the
    whole array. Default is zero.
ddof : int, optional
    Delta degrees of freedom. Default is 1.
Returns
-------
tvar : float
    Trimmed variance.
Notes
-----
For more details on `tvar`, see `scipy.stats.tvar`.
Definition at line 2248 of file _mstats_basic.py.
References _mask_to_limits().
variation()
scipy.stats._mstats_basic.variation (a, axis = 0, ddof = 0)
Compute the coefficient of variation.
The coefficient of variation is the standard deviation divided by the
mean.  This function is equivalent to::
    np.std(x, axis=axis, ddof=ddof) / np.mean(x)
The default for ``ddof`` is 0, but many definitions of the coefficient
of variation use the square root of the unbiased sample variance
for the sample standard deviation, which corresponds to ``ddof=1``.
Parameters
----------
a : array_like
    Input array.
axis : int or None, optional
    Axis along which to calculate the coefficient of variation. Default
    is 0. If None, compute over the whole array `a`.
ddof : int, optional
    Delta degrees of freedom.  Default is 0.
Returns
-------
variation : ndarray
    The calculated variation along the requested axis.
Notes
-----
For more details about `variation`, see `scipy.stats.variation`.
Examples
--------
>>> import numpy as np
>>> from scipy.stats.mstats import variation
>>> a = np.array([2,8,4])
>>> variation(a)
0.5345224838248487
>>> b = np.array([2,8,3,4])
>>> c = np.ma.masked_array(b, mask=[0,0,1,0])
>>> variation(c)
0.5345224838248487
In the example above, it can be seen that this works the same as
`scipy.stats.variation` except 'stats.mstats.variation' ignores masked
array elements.
Definition at line 2646 of file _mstats_basic.py.
winsorize()
scipy.stats._mstats_basic.winsorize (a, limits = None, inclusive = (True, True), inplace = False, axis = None, nan_policy = 'propagate')
Returns a Winsorized version of the input array.
The (limits[0])th lowest values are set to the (limits[0])th percentile,
and the (limits[1])th highest values are set to the (1 - limits[1])th
percentile.
Masked values are skipped.
Parameters
----------
a : sequence
    Input array.
limits : {None, tuple of float}, optional
    Tuple of the percentages to cut on each side of the array, with respect
    to the number of unmasked data, as floats between 0. and 1.
    Noting n the number of unmasked data before trimming, the
    (n*limits[0])th smallest data and the (n*limits[1])th largest data are
    masked, and the total number of unmasked data after trimming
    is n*(1.-sum(limits)) The value of one limit can be set to None to
    indicate an open interval.
inclusive : {(True, True) tuple}, optional
    Tuple indicating whether the number of data being masked on each side
    should be truncated (True) or rounded (False).
inplace : {False, True}, optional
    Whether to winsorize in place (True) or to use a copy (False)
axis : {None, int}, optional
    Axis along which to trim. If None, the whole array is trimmed, but its
    shape is maintained.
nan_policy : {'propagate', 'raise', 'omit'}, optional
    Defines how to handle when input contains nan.
    The following options are available (default is 'propagate'):
      * 'propagate': allows nan values and may overwrite or propagate them
      * 'raise': throws an error
      * 'omit': performs the calculations ignoring nan values
Notes
-----
This function is applied to reduce the effect of possibly spurious outliers
by limiting the extreme values.
Examples
--------
>>> import numpy as np
>>> from scipy.stats.mstats import winsorize
A shuffled array contains integers from 1 to 10.
>>> a = np.array([10, 4, 9, 8, 5, 3, 7, 2, 1, 6])
The 10% of the lowest value (i.e., `1`) and the 20% of the highest
values (i.e., `9` and `10`) are replaced.
>>> winsorize(a, limits=[0.1, 0.2])
masked_array(data=[8, 4, 8, 8, 5, 3, 7, 2, 2, 6],
             mask=False,
       fill_value=999999)
Definition at line 2438 of file _mstats_basic.py.
Variable Documentation
__all__
list scipy.stats._mstats_basic.__all__ private
Initial value:
=  ['argstoarray',
           'count_tied_groups',
           'describe',
           'f_oneway', 'find_repeats','friedmanchisquare',
           'kendalltau','kendalltau_seasonal','kruskal','kruskalwallis',
           'ks_twosamp', 'ks_2samp', 'kurtosis', 'kurtosistest',
           'ks_1samp', 'kstest',
           'linregress',
           'mannwhitneyu', 'meppf','mode','moment','mquantiles','msign',
           'normaltest',
           'obrientransform',
           'pearsonr','plotting_positions','pointbiserialr',
           'rankdata',
           'scoreatpercentile','sem',
           'sen_seasonal_slopes','skew','skewtest','spearmanr',
           'siegelslopes', 'theilslopes',
           'tmax','tmean','tmin','trim','trimboth',
           'trimtail','trima','trimr','trimmed_mean','trimmed_std',
           'trimmed_stde','trimmed_var','tsem','ttest_1samp','ttest_onesamp',
           'ttest_ind','ttest_rel','tvar',
           'variation',
           'winsorize',
           'brunnermunzel',
           ]
Definition at line 8 of file _mstats_basic.py.
__doc__
scipy.stats._mstats_basic.__doc__ private
Definition at line 1929 of file _mstats_basic.py.
BrunnerMunzelResult
scipy.stats._mstats_basic.BrunnerMunzelResult = namedtuple('BrunnerMunzelResult', ('statistic', 'pvalue'))
Definition at line 3439 of file _mstats_basic.py.
DescribeResult
scipy.stats._mstats_basic.DescribeResult
Initial value:
=  namedtuple('DescribeResult', ('nobs', 'minmax', 'mean',
                                               'variance', 'skewness',
                                               'kurtosis'))
Definition at line 2804 of file _mstats_basic.py.
F_onewayResult
scipy.stats._mstats_basic.F_onewayResult = namedtuple('F_onewayResult', ('statistic', 'pvalue'))
Definition at line 3351 of file _mstats_basic.py.
FriedmanchisquareResult
scipy.stats._mstats_basic.FriedmanchisquareResult
Initial value:
=  namedtuple('FriedmanchisquareResult',
                                     ('statistic', 'pvalue'))
Definition at line 3387 of file _mstats_basic.py.
KruskalResult
scipy.stats._mstats_basic.KruskalResult = namedtuple('KruskalResult', ('statistic', 'pvalue'))
Definition at line 1571 of file _mstats_basic.py.
kruskalwallis
scipy.stats._mstats_basic.kruskalwallis = kruskal
Definition at line 1635 of file _mstats_basic.py.
ks_twosamp
scipy.stats._mstats_basic.ks_twosamp = ks_2samp
Definition at line 1719 of file _mstats_basic.py.
KurtosistestResult
scipy.stats._mstats_basic.KurtosistestResult = namedtuple('KurtosistestResult', ('statistic', 'pvalue'))
Definition at line 2964 of file _mstats_basic.py.
MannwhitneyuResult
scipy.stats._mstats_basic.MannwhitneyuResult
Initial value:
=  namedtuple('MannwhitneyuResult', ('statistic',
                                                       'pvalue'))
Definition at line 1520 of file _mstats_basic.py.
meppf
scipy.stats._mstats_basic.meppf = plotting_positions
Definition at line 3269 of file _mstats_basic.py.
ModeResult
scipy.stats._mstats_basic.ModeResult = namedtuple('ModeResult', ('mode', 'count'))
Definition at line 299 of file _mstats_basic.py.
NormaltestResult
scipy.stats._mstats_basic.NormaltestResult = namedtuple('NormaltestResult', ('statistic', 'pvalue'))
Definition at line 3038 of file _mstats_basic.py.
PointbiserialrResult
scipy.stats._mstats_basic.PointbiserialrResult
Initial value:
=  namedtuple('PointbiserialrResult', ('correlation',
                                                           'pvalue'))
Definition at line 967 of file _mstats_basic.py.
SenSeasonalSlopesResult
scipy.stats._mstats_basic.SenSeasonalSlopesResult
Initial value:
=  _make_tuple_bunch('SenSeasonalSlopesResult',
                                            ['intra_slope', 'inter_slope'])
Definition at line 1196 of file _mstats_basic.py.
SkewtestResult
scipy.stats._mstats_basic.SkewtestResult = namedtuple('SkewtestResult', ('statistic', 'pvalue'))
Definition at line 2903 of file _mstats_basic.py.
trim1
scipy.stats._mstats_basic.trim1 = trimtail
Definition at line 2003 of file _mstats_basic.py.
trimdoc
str scipy.stats._mstats_basic.trimdoc
Definition at line 1870 of file _mstats_basic.py.
Ttest_1sampResult
scipy.stats._mstats_basic.Ttest_1sampResult = namedtuple('Ttest_1sampResult', ('statistic', 'pvalue'))
Definition at line 1316 of file _mstats_basic.py.
Ttest_indResult
scipy.stats._mstats_basic.Ttest_indResult = namedtuple('Ttest_indResult', ('statistic', 'pvalue'))
Definition at line 1378 of file _mstats_basic.py.
ttest_onesamp
scipy.stats._mstats_basic.ttest_onesamp = ttest_1samp
Definition at line 1375 of file _mstats_basic.py.
Ttest_relResult
scipy.stats._mstats_basic.Ttest_relResult = namedtuple('Ttest_relResult', ('statistic', 'pvalue'))
Definition at line 1459 of file _mstats_basic.py.