Code Cloning Analysis: scipy.io.tests.test_mmio.TestMMIOArray Class Reference
scipy.io.tests.test_mmio.TestMMIOArray Class Reference
Public Member Functions
setup_method (self)
teardown_method (self)
check (self, a, info)
check_exact (self, a, info)
test_simple_integer (self, typeval, dtype)
test_32bit_integer (self, typeval, dtype)
test_64bit_integer (self)
test_64bit_unsigned_integer (self)
test_simple_upper_triangle_integer (self, typeval, dtype)
test_simple_lower_triangle_integer (self, typeval, dtype)
test_simple_rectangular_integer (self, typeval, dtype)
test_simple_rectangular_float (self)
test_simple_float (self)
test_simple_complex (self)
test_simple_symmetric_integer (self, typeval, dtype)
test_simple_skew_symmetric_integer (self)
test_simple_skew_symmetric_float (self)
test_simple_hermitian_complex (self)
test_random_symmetric_float (self)
test_random_rectangular_float (self)
test_bad_number_of_array_header_fields (self)
test_gh13634_non_skew_symmetric_int (self)
test_gh13634_non_skew_symmetric_float (self)
Public Attributes
tmpdir = mkdtemp()
fn = os.path.join(self.tmpdir, 'testfile.mtx')
Detailed Description
Definition at line 21 of file test_mmio.py.
Member Function Documentation
check()
scipy.io.tests.test_mmio.TestMMIOArray.check (self, a, info)
Definition at line 29 of file test_mmio.py.
check_exact()
scipy.io.tests.test_mmio.TestMMIOArray.check_exact (self, a, info)
Definition at line 35 of file test_mmio.py.
setup_method()
scipy.io.tests.test_mmio.TestMMIOArray.setup_method (self)
Definition at line 22 of file test_mmio.py.
teardown_method()
scipy.io.tests.test_mmio.TestMMIOArray.teardown_method (self)
Definition at line 26 of file test_mmio.py.
test_32bit_integer()
scipy.io.tests.test_mmio.TestMMIOArray.test_32bit_integer (self, typeval, dtype)
Definition at line 47 of file test_mmio.py.
test_64bit_integer()
scipy.io.tests.test_mmio.TestMMIOArray.test_64bit_integer (self)
Definition at line 51 of file test_mmio.py.
test_64bit_unsigned_integer()
scipy.io.tests.test_mmio.TestMMIOArray.test_64bit_unsigned_integer (self)
Definition at line 58 of file test_mmio.py.
test_bad_number_of_array_header_fields()
scipy.io.tests.test_mmio.TestMMIOArray.test_bad_number_of_array_header_fields (self)
Definition at line 117 of file test_mmio.py.
test_gh13634_non_skew_symmetric_float()
scipy.io.tests.test_mmio.TestMMIOArray.test_gh13634_non_skew_symmetric_float (self)
Definition at line 139 of file test_mmio.py.
test_gh13634_non_skew_symmetric_int()
scipy.io.tests.test_mmio.TestMMIOArray.test_gh13634_non_skew_symmetric_int (self)
Definition at line 135 of file test_mmio.py.
test_random_rectangular_float()
scipy.io.tests.test_mmio.TestMMIOArray.test_random_rectangular_float (self)
Definition at line 112 of file test_mmio.py.
test_random_symmetric_float()
scipy.io.tests.test_mmio.TestMMIOArray.test_random_symmetric_float (self)
Definition at line 106 of file test_mmio.py.
test_simple_complex()
scipy.io.tests.test_mmio.TestMMIOArray.test_simple_complex (self)
Definition at line 85 of file test_mmio.py.
test_simple_float()
scipy.io.tests.test_mmio.TestMMIOArray.test_simple_float (self)
Definition at line 81 of file test_mmio.py.
test_simple_hermitian_complex()
scipy.io.tests.test_mmio.TestMMIOArray.test_simple_hermitian_complex (self)
Definition at line 102 of file test_mmio.py.
test_simple_integer()
scipy.io.tests.test_mmio.TestMMIOArray.test_simple_integer (self, typeval, dtype)
Definition at line 42 of file test_mmio.py.
test_simple_lower_triangle_integer()
scipy.io.tests.test_mmio.TestMMIOArray.test_simple_lower_triangle_integer (self, typeval, dtype)
Definition at line 68 of file test_mmio.py.
test_simple_rectangular_float()
scipy.io.tests.test_mmio.TestMMIOArray.test_simple_rectangular_float (self)
Definition at line 77 of file test_mmio.py.
test_simple_rectangular_integer()
scipy.io.tests.test_mmio.TestMMIOArray.test_simple_rectangular_integer (self, typeval, dtype)
Definition at line 73 of file test_mmio.py.
test_simple_skew_symmetric_float()
scipy.io.tests.test_mmio.TestMMIOArray.test_simple_skew_symmetric_float (self)
Definition at line 98 of file test_mmio.py.
test_simple_skew_symmetric_integer()
scipy.io.tests.test_mmio.TestMMIOArray.test_simple_skew_symmetric_integer (self)
Definition at line 94 of file test_mmio.py.
test_simple_symmetric_integer()
scipy.io.tests.test_mmio.TestMMIOArray.test_simple_symmetric_integer (self, typeval, dtype)
Definition at line 90 of file test_mmio.py.
test_simple_upper_triangle_integer()
scipy.io.tests.test_mmio.TestMMIOArray.test_simple_upper_triangle_integer (self, typeval, dtype)
Definition at line 63 of file test_mmio.py.
Member Data Documentation
fn
scipy.io.tests.test_mmio.TestMMIOArray.fn = os.path.join(self.tmpdir, 'testfile.mtx')
Definition at line 24 of file test_mmio.py.
Referenced by scipy.optimize._shgo.SHGO.find_minima(), scipy.optimize._shgo.SHGO.iterate_all(), scipy.optimize._shgo.SHGO.iterate_delaunay(), scipy.optimize._shgo.SHGO.iterate_hypercube(), and scipy.optimize._shgo.SHGO.sort_result().
tmpdir
scipy.io.tests.test_mmio.TestMMIOArray.tmpdir = mkdtemp()
Definition at line 23 of file test_mmio.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/io/tests/test_mmio.py