Code Cloning Analysis: scipy.linalg.tests.test_lapack Namespace Reference
scipy.linalg.tests.test_lapack Namespace Reference
Classes
class TestBlockedQR
class TestDlasd4
class TestDpotr
class TestFlapackSimple
class TestHetrd
class TestLapack
class TestLeastSquaresSolvers
class TestRegression
class TestSytrd
class TestTbtrs
Functions
generate_random_dtype_array (shape, dtype)
test_lapack_documented ()
test_geqrf_lwork (dtype, shape)
test_lartg ()
test_rot ()
test_larfg_larf ()
test_sgesdd_lwork_bug_workaround ()
test_gglse ()
test_sycon_hecon ()
test_sygst ()
test_hegst ()
test_tzrzf ()
test_tfsm ()
test_ormrz_unmrz ()
test_tfttr_trttf ()
test_tpttr_trttp ()
test_pftrf ()
test_pftri ()
test_pftrs ()
test_sfrk_hfrk ()
test_syconv ()
test_pstrf ()
test_pstf2 ()
test_geequ ()
test_syequb ()
test_heequb ()
test_getc2_gesc2 ()
test_gejsv_general (size, dtype, joba, jobu, jobv, jobr, jobp, jobt=0)
test_gejsv_edge_arguments (dtype)
test_gejsv_invalid_job_arguments (kwargs)
test_gejsv_NAG (A, sva_expect, u_expect, v_expect)
test_gttrf_gttrs (dtype)
test_gttrf_gttrs_NAG_f07cdf_f07cef_f07crf_f07csf (du, d, dl, du_exp, d_exp, du2_exp, ipiv_exp, b, x)
test_geqrfp_lwork (dtype, shape)
test_pttrf_pttrs (ddtype, dtype)
test_pttrf_pttrs_errors_incompatible_shape (ddtype, dtype)
test_pttrf_pttrs_errors_singular_nonSPD (ddtype, dtype)
test_pttrf_pttrs_NAG (d, e, d_expect, e_expect, b, x_expect)
pteqr_get_d_e_A_z (dtype, realtype, n, compute_z)
test_pteqr (dtype, realtype, compute_z)
test_pteqr_error_non_spd (dtype, realtype, compute_z)
test_pteqr_raise_error_wrong_shape (dtype, realtype, compute_z)
test_pteqr_error_singular (dtype, realtype, compute_z)
test_pteqr_NAG_f08jgf (compute_z, d, e, d_expect, z_expect)
test_geqrfp (dtype, matrix_size)
test_geqrfp_errors_with_empty_array ()
test_standard_eigh_lworks (pfx, driver)
test_generalized_eigh_lworks (pfx, driver)
test_orcsd_uncsd_lwork (dtype_, m)
test_orcsd_uncsd (dtype_)
test_gtsvx (dtype, trans_bool, fact)
test_gtsvx_error_singular (dtype, trans_bool, fact)
test_gtsvx_error_incompatible_size (dtype, trans_bool, fact)
test_gtsvx_NAG (du, d, dl, b, x)
test_ptsvx (dtype, realtype, fact, df_de_lambda)
test_ptsvx_error_raise_errors (dtype, realtype, fact, df_de_lambda)
test_ptsvx_non_SPD_singular (dtype, realtype, fact, df_de_lambda)
test_ptsvx_NAG (d, e, b, x)
test_pptrs_pptri_pptrf_ppsv_ppcon (dtype, lower)
test_gees_trexc (dtype)
test_trexc_NAG (t, ifst, ilst, expect)
test_gges_tgexc (dtype)
test_gees_trsen (dtype)
test_trsen_NAG (t, q, select, expect, expect_s, expect_sep)
test_gges_tgsen (dtype)
Variables
CONFIG = None
clapack = None
list REAL_DTYPES = [np.float32, np.float64]
list COMPLEX_DTYPES = [np.complex64, np.complex128]
list DTYPES = REAL_DTYPES + COMPLEX_DTYPES
blas_provider = None
blas_version = CONFIG['Build Dependencies']['blas']['version']
Function Documentation
generate_random_dtype_array()
scipy.linalg.tests.test_lapack.generate_random_dtype_array (shape, dtype)
Definition at line 49 of file test_lapack.py.
pteqr_get_d_e_A_z()
scipy.linalg.tests.test_lapack.pteqr_get_d_e_A_z (dtype, realtype, n, compute_z)
Definition at line 2283 of file test_lapack.py.
test_geequ()
scipy.linalg.tests.test_lapack.test_geequ ()
Definition at line 1690 of file test_lapack.py.
test_gees_trexc()
scipy.linalg.tests.test_lapack.test_gees_trexc (dtype)
Definition at line 2985 of file test_lapack.py.
test_gees_trsen()
scipy.linalg.tests.test_lapack.test_gees_trsen (dtype)
Definition at line 3118 of file test_lapack.py.
test_gejsv_edge_arguments()
scipy.linalg.tests.test_lapack.test_gejsv_edge_arguments (dtype)
Test edge arguments return expected status
Definition at line 1910 of file test_lapack.py.
References scipy.linalg.lapack.get_lapack_funcs().
test_gejsv_general()
scipy.linalg.tests.test_lapack.test_gejsv_general (size, dtype, joba, jobu, jobv, jobr, jobp, jobt = 0)
Test the lapack routine ?gejsv.
This function tests that a singular value decomposition can be performed
on the random M-by-N matrix A. The test performs the SVD using ?gejsv
then performs the following checks:
* ?gejsv exist successfully (info == 0)
* The returned singular values are correct
* `A` can be reconstructed from `u`, `SIGMA`, `v`
* Ensure that u.T @ u is the identity matrix
* Ensure that v.T @ v is the identity matrix
* The reported matrix rank
* The reported number of singular values
* If denormalized floats are required
Notes
-----
joba specifies several choices effecting the calculation's accuracy
Although all arguments are tested, the tests only check that the correct
solution is returned - NOT that the prescribed actions are performed
internally.
jobt is, as of v3.9.0, still experimental and removed to cut down number of
test cases. However keyword itself is tested externally.
Definition at line 1808 of file test_lapack.py.
References scipy.linalg.lapack.get_lapack_funcs(), and scipy.linalg._decomp_svd.svd().
test_gejsv_invalid_job_arguments()
scipy.linalg.tests.test_lapack.test_gejsv_invalid_job_arguments (kwargs)
Test invalid job arguments raise an Exception
Definition at line 1953 of file test_lapack.py.
References scipy.linalg.lapack.get_lapack_funcs().
test_gejsv_NAG()
scipy.linalg.tests.test_lapack.test_gejsv_NAG (A, sva_expect, u_expect, v_expect)
This test implements the example found in the NAG manual, f08khf.
An example was not found for the complex case.
Definition at line 1978 of file test_lapack.py.
References scipy.linalg._decomp.eigh(), and scipy.linalg.lapack.get_lapack_funcs().
test_generalized_eigh_lworks()
scipy.linalg.tests.test_lapack.test_generalized_eigh_lworks (pfx, driver)
Definition at line 2507 of file test_lapack.py.
test_geqrf_lwork()
scipy.linalg.tests.test_lapack.test_geqrf_lwork (dtype, shape)
Definition at line 428 of file test_lapack.py.
test_geqrfp()
scipy.linalg.tests.test_lapack.test_geqrfp (dtype, matrix_size)
Definition at line 2419 of file test_lapack.py.
test_geqrfp_errors_with_empty_array()
scipy.linalg.tests.test_lapack.test_geqrfp_errors_with_empty_array ()
Definition at line 2483 of file test_lapack.py.
test_geqrfp_lwork()
scipy.linalg.tests.test_lapack.test_geqrfp_lwork (dtype, shape)
Definition at line 2152 of file test_lapack.py.
test_getc2_gesc2()
scipy.linalg.tests.test_lapack.test_getc2_gesc2 ()
Definition at line 1770 of file test_lapack.py.
test_gges_tgexc()
scipy.linalg.tests.test_lapack.test_gges_tgexc (dtype)
Definition at line 3062 of file test_lapack.py.
test_gges_tgsen()
scipy.linalg.tests.test_lapack.test_gges_tgsen (dtype)
Definition at line 3239 of file test_lapack.py.
test_gglse()
scipy.linalg.tests.test_lapack.test_gglse ()
Definition at line 930 of file test_lapack.py.
test_gtsvx()
scipy.linalg.tests.test_lapack.test_gtsvx (dtype, trans_bool, fact)
These tests uses ?gtsvx to solve a random Ax=b system for each dtype.
It tests that the outputs define an LU matrix, that inputs are unmodified,
transposal options, incompatible shapes, singular matrices, and
singular factorizations. It parametrizes DTYPES and the 'fact' value along
with the fact related inputs.
Definition at line 2585 of file test_lapack.py.
References scipy.linalg.lapack.get_lapack_funcs().
test_gtsvx_error_incompatible_size()
scipy.linalg.tests.test_lapack.test_gtsvx_error_incompatible_size (dtype, trans_bool, fact)
Definition at line 2697 of file test_lapack.py.
test_gtsvx_error_singular()
scipy.linalg.tests.test_lapack.test_gtsvx_error_singular (dtype, trans_bool, fact)
Definition at line 2646 of file test_lapack.py.
test_gtsvx_NAG()
scipy.linalg.tests.test_lapack.test_gtsvx_NAG (du, d, dl, b, x)
Definition at line 2765 of file test_lapack.py.
test_gttrf_gttrs()
scipy.linalg.tests.test_lapack.test_gttrf_gttrs (dtype)
Definition at line 1995 of file test_lapack.py.
test_gttrf_gttrs_NAG_f07cdf_f07cef_f07crf_f07csf()
scipy.linalg.tests.test_lapack.test_gttrf_gttrs_NAG_f07cdf_f07cef_f07crf_f07csf (du, d, dl, du_exp, d_exp, du2_exp, ipiv_exp, b, x)
Definition at line 2130 of file test_lapack.py.
test_heequb()
scipy.linalg.tests.test_lapack.test_heequb ()
Definition at line 1752 of file test_lapack.py.
test_hegst()
scipy.linalg.tests.test_lapack.test_hegst ()
Definition at line 1037 of file test_lapack.py.
test_lapack_documented()
scipy.linalg.tests.test_lapack.test_lapack_documented ()
Test that all entries are in the doc.
Definition at line 57 of file test_lapack.py.
test_larfg_larf()
scipy.linalg.tests.test_lapack.test_larfg_larf ()
Definition at line 713 of file test_lapack.py.
test_lartg()
scipy.linalg.tests.test_lapack.test_lartg ()
Definition at line 648 of file test_lapack.py.
test_orcsd_uncsd()
scipy.linalg.tests.test_lapack.test_orcsd_uncsd (dtype_)
Definition at line 2536 of file test_lapack.py.
test_orcsd_uncsd_lwork()
scipy.linalg.tests.test_lapack.test_orcsd_uncsd_lwork (dtype_, m)
Definition at line 2523 of file test_lapack.py.
test_ormrz_unmrz()
scipy.linalg.tests.test_lapack.test_ormrz_unmrz ()
This test performs a matrix multiplication with an arbitrary m x n matric C
and a unitary matrix Q without explicitly forming the array. The array data
is encoded in the rectangular part of A which is obtained from ?TZRZF. Q
size is inferred by m, n, side keywords.
Definition at line 1143 of file test_lapack.py.
References scipy.linalg.lapack._compute_lwork(), scipy.linalg.lapack.get_lapack_funcs(), and scipy.linalg._special_matrices.triu().
test_pftrf()
scipy.linalg.tests.test_lapack.test_pftrf ()
Test Cholesky factorization of a positive definite Rectengular Full
Packed (RFP) format array
Definition at line 1300 of file test_lapack.py.
References scipy.linalg._decomp_cholesky.cholesky(), and scipy.linalg.lapack.get_lapack_funcs().
test_pftri()
scipy.linalg.tests.test_lapack.test_pftri ()
Test Cholesky factorization of a positive definite Rectengular Full
Packed (RFP) format array to find its inverse
Definition at line 1327 of file test_lapack.py.
References scipy.linalg.lapack.get_lapack_funcs(), scipy.linalg._basic.inv(), and scipy.linalg._special_matrices.triu().
test_pftrs()
scipy.linalg.tests.test_lapack.test_pftrs ()
Test Cholesky factorization of a positive definite Rectengular Full
Packed (RFP) format array and solve a linear system
Definition at line 1359 of file test_lapack.py.
References scipy.linalg.lapack.get_lapack_funcs(), and scipy.linalg._basic.solve().
test_pptrs_pptri_pptrf_ppsv_ppcon()
scipy.linalg.tests.test_lapack.test_pptrs_pptri_pptrf_ppsv_ppcon (dtype, lower)
Definition at line 2938 of file test_lapack.py.
test_pstf2()
scipy.linalg.tests.test_lapack.test_pstf2 ()
Definition at line 1650 of file test_lapack.py.
test_pstrf()
scipy.linalg.tests.test_lapack.test_pstrf ()
Definition at line 1610 of file test_lapack.py.
test_pteqr()
scipy.linalg.tests.test_lapack.test_pteqr (dtype, realtype, compute_z)
Tests the ?pteqr lapack routine for all dtypes and compute_z parameters.
It generates random SPD matrix diagonals d and e, and then confirms
correct eigenvalues with scipy.linalg.eig. With applicable compute_z=2 it
tests that z can reform A.
Definition at line 2317 of file test_lapack.py.
References scipy.linalg._decomp.eigh(), and scipy.linalg.lapack.get_lapack_funcs().
test_pteqr_error_non_spd()
scipy.linalg.tests.test_lapack.test_pteqr_error_non_spd (dtype, realtype, compute_z)
Definition at line 2350 of file test_lapack.py.
test_pteqr_error_singular()
scipy.linalg.tests.test_lapack.test_pteqr_error_singular (dtype, realtype, compute_z)
Definition at line 2380 of file test_lapack.py.
test_pteqr_NAG_f08jgf()
scipy.linalg.tests.test_lapack.test_pteqr_NAG_f08jgf (compute_z, d, e, d_expect, z_expect)
Implements real (f08jgf) example from NAG Manual Mark 26.
Tests for correct outputs.
Definition at line 2402 of file test_lapack.py.
References scipy.linalg.lapack._compute_lwork(), scipy.linalg._special_matrices.block_diag(), scipy.linalg.lapack.get_lapack_funcs(), and scipy.linalg._decomp_qr.qr().
test_pteqr_raise_error_wrong_shape()
scipy.linalg.tests.test_lapack.test_pteqr_raise_error_wrong_shape (dtype, realtype, compute_z)
Definition at line 2365 of file test_lapack.py.
test_ptsvx()
scipy.linalg.tests.test_lapack.test_ptsvx (dtype, realtype, fact, df_de_lambda)
This tests the ?ptsvx lapack routine wrapper to solve a random system
Ax = b for all dtypes and input variations. Tests for: unmodified
input parameters, fact options, incompatible matrix shapes raise an error,
and singular matrices return info of illegal value.
Definition at line 2783 of file test_lapack.py.
References scipy.linalg._decomp_cholesky.cholesky(), scipy.linalg.lapack.get_lapack_funcs(), scipy.linalg._basic.inv(), and scipy.linalg._basic.solve().
test_ptsvx_error_raise_errors()
scipy.linalg.tests.test_lapack.test_ptsvx_error_raise_errors (dtype, realtype, fact, df_de_lambda)
Definition at line 2842 of file test_lapack.py.
test_ptsvx_NAG()
scipy.linalg.tests.test_lapack.test_ptsvx_NAG (d, e, b, x)
Definition at line 2923 of file test_lapack.py.
test_ptsvx_non_SPD_singular()
scipy.linalg.tests.test_lapack.test_ptsvx_non_SPD_singular (dtype, realtype, fact, df_de_lambda)
Definition at line 2869 of file test_lapack.py.
test_pttrf_pttrs()
scipy.linalg.tests.test_lapack.test_pttrf_pttrs (ddtype, dtype)
Definition at line 2161 of file test_lapack.py.
test_pttrf_pttrs_errors_incompatible_shape()
scipy.linalg.tests.test_lapack.test_pttrf_pttrs_errors_incompatible_shape (ddtype, dtype)
Definition at line 2210 of file test_lapack.py.
test_pttrf_pttrs_errors_singular_nonSPD()
scipy.linalg.tests.test_lapack.test_pttrf_pttrs_errors_singular_nonSPD (ddtype, dtype)
Definition at line 2222 of file test_lapack.py.
test_pttrf_pttrs_NAG()
scipy.linalg.tests.test_lapack.test_pttrf_pttrs_NAG (d, e, d_expect, e_expect, b, x_expect)
Definition at line 2260 of file test_lapack.py.
test_rot()
scipy.linalg.tests.test_lapack.test_rot ()
Definition at line 671 of file test_lapack.py.
test_sfrk_hfrk()
scipy.linalg.tests.test_lapack.test_sfrk_hfrk ()
Test for performing a symmetric rank-k operation for matrix in RFP format.
Definition at line 1396 of file test_lapack.py.
References scipy.linalg.lapack.get_lapack_funcs(), and scipy.linalg._special_matrices.triu().
test_sgesdd_lwork_bug_workaround()
scipy.linalg.tests.test_lapack.test_sgesdd_lwork_bug_workaround ()
Definition at line 755 of file test_lapack.py.
test_standard_eigh_lworks()
scipy.linalg.tests.test_lapack.test_standard_eigh_lworks (pfx, driver)
Definition at line 2492 of file test_lapack.py.
test_sycon_hecon()
scipy.linalg.tests.test_lapack.test_sycon_hecon ()
Definition at line 979 of file test_lapack.py.
test_syconv()
scipy.linalg.tests.test_lapack.test_syconv ()
Test for going back and forth between the returned format of he/sytrf to
L and D factors/permutations.
Definition at line 1423 of file test_lapack.py.
References scipy.linalg.lapack._compute_lwork(), scipy.linalg.lapack.get_lapack_funcs(), scipy.linalg._decomp_ldl.ldl(), scipy.linalg._special_matrices.tril(), and scipy.linalg._special_matrices.triu().
test_syequb()
scipy.linalg.tests.test_lapack.test_syequb ()
Definition at line 1735 of file test_lapack.py.
test_sygst()
scipy.linalg.tests.test_lapack.test_sygst ()
Definition at line 1006 of file test_lapack.py.
test_tfsm()
scipy.linalg.tests.test_lapack.test_tfsm ()
Test for solving a linear system with the coefficient matrix is a
triangular array stored in Full Packed (RFP) format.
Definition at line 1102 of file test_lapack.py.
References scipy.linalg.lapack.get_lapack_funcs(), scipy.linalg._basic.solve(), and scipy.linalg._special_matrices.triu().
test_tfttr_trttf()
scipy.linalg.tests.test_lapack.test_tfttr_trttf ()
Test conversion routines between the Rectengular Full Packed (RFP) format
and Standard Triangular Array (TR)
Definition at line 1201 of file test_lapack.py.
References scipy.linalg.lapack.get_lapack_funcs(), scipy.linalg._special_matrices.tril(), and scipy.linalg._special_matrices.triu().
test_tpttr_trttp()
scipy.linalg.tests.test_lapack.test_tpttr_trttp ()
Test conversion routines between the Rectengular Full Packed (RFP) format
and Standard Triangular Array (TR)
Definition at line 1259 of file test_lapack.py.
References scipy.linalg.lapack.get_lapack_funcs(), scipy.linalg._special_matrices.tril(), and scipy.linalg._special_matrices.triu().
test_trexc_NAG()
scipy.linalg.tests.test_lapack.test_trexc_NAG (t, ifst, ilst, expect)
This test implements the example found in the NAG manual,
f08qfc, f08qtc, f08qgc, f08quc.
Definition at line 3045 of file test_lapack.py.
References scipy.linalg.lapack._compute_lwork(), and scipy.linalg.lapack.get_lapack_funcs().
test_trsen_NAG()
scipy.linalg.tests.test_lapack.test_trsen_NAG (t, q, select, expect, expect_s, expect_sep)
This test implements the example found in the NAG manual,
f08qgc, f08quc.
Definition at line 3205 of file test_lapack.py.
References scipy.linalg.lapack._compute_lwork(), and scipy.linalg.lapack.get_lapack_funcs().
test_tzrzf()
scipy.linalg.tests.test_lapack.test_tzrzf ()
This test performs an RZ decomposition in which an m x n upper trapezoidal
array M (m <= n) is factorized as M = [R 0] * Z where R is upper triangular
and Z is unitary.
Definition at line 1068 of file test_lapack.py.
References scipy.linalg.lapack._compute_lwork(), scipy.linalg.lapack.get_lapack_funcs(), and scipy.linalg._special_matrices.triu().
Variable Documentation
blas_provider
scipy.linalg.tests.test_lapack.blas_provider = None
Definition at line 43 of file test_lapack.py.
blas_version
scipy.linalg.tests.test_lapack.blas_version = CONFIG['Build Dependencies']['blas']['version']
Definition at line 46 of file test_lapack.py.
clapack
scipy.linalg.tests.test_lapack.clapack = None
Definition at line 35 of file test_lapack.py.
COMPLEX_DTYPES
list scipy.linalg.tests.test_lapack.COMPLEX_DTYPES = [np.complex64, np.complex128]
Definition at line 40 of file test_lapack.py.
CONFIG
scipy.linalg.tests.test_lapack.CONFIG = None
Definition at line 30 of file test_lapack.py.
DTYPES
list scipy.linalg.tests.test_lapack.DTYPES = REAL_DTYPES + COMPLEX_DTYPES
Definition at line 41 of file test_lapack.py.
REAL_DTYPES
list scipy.linalg.tests.test_lapack.REAL_DTYPES = [np.float32, np.float64]
Definition at line 39 of file test_lapack.py.