Code Cloning Analysis: numpy.core.tests.test_multiarray.TestIO Class Reference
numpy.core.tests.test_multiarray.TestIO Class Reference
Public Member Functions
x (self)
tmp_filename (self, tmp_path, request)
test_nofile (self)
test_bool_fromstring (self)
test_uint64_fromstring (self)
test_int64_fromstring (self)
test_fromstring_count0 (self)
test_empty_files_text (self, tmp_filename)
test_empty_files_binary (self, tmp_filename)
test_roundtrip_file (self, x, tmp_filename)
test_roundtrip (self, x, tmp_filename)
test_roundtrip_dump_pathlib (self, x, tmp_filename)
test_roundtrip_binary_str (self, x)
test_roundtrip_str (self, x)
test_roundtrip_repr (self, x)
test_unseekable_fromfile (self, x, tmp_filename)
test_io_open_unbuffered_fromfile (self, x, tmp_filename)
test_largish_file (self, tmp_filename)
test_io_open_buffered_fromfile (self, x, tmp_filename)
test_file_position_after_fromfile (self, tmp_filename)
test_file_position_after_tofile (self, tmp_filename)
test_load_object_array_fromfile (self, tmp_filename)
test_fromfile_offset (self, x, tmp_filename)
test_fromfile_bad_dup (self, x, tmp_filename)
decimal_sep_localization (self, request)
test_nan (self, tmp_filename, decimal_sep_localization)
test_inf (self, tmp_filename, decimal_sep_localization)
test_numbers (self, tmp_filename, decimal_sep_localization)
test_binary (self, tmp_filename)
test_string (self, tmp_filename)
test_counted_string (self, tmp_filename, decimal_sep_localization)
test_string_with_ws (self, tmp_filename)
test_counted_string_with_ws (self, tmp_filename)
test_ascii (self, tmp_filename, decimal_sep_localization)
test_malformed (self, tmp_filename, decimal_sep_localization)
test_long_sep (self, tmp_filename)
test_dtype (self, tmp_filename)
test_dtype_bool (self, tmp_filename)
test_tofile_sep (self, tmp_filename, decimal_sep_localization)
test_tofile_format (self, tmp_filename, decimal_sep_localization)
test_tofile_cleanup (self, tmp_filename)
test_fromfile_subarray_binary (self, tmp_filename)
test_parsing_subarray_unsupported (self, tmp_filename)
test_read_shorter_than_count_subarray (self, tmp_filename)
Protected Member Functions
_check_from (self, s, value, filename, **kw)
Detailed Description
Test tofile, fromfile, tobytes, and fromstring
Definition at line 5259 of file test_multiarray.py.
Member Function Documentation
_check_from()
numpy.core.tests.test_multiarray.TestIO._check_from (self, s, value, filename, ** kw) protected
Definition at line 5520 of file test_multiarray.py.
Referenced by decimal_sep_localization().
decimal_sep_localization()
numpy.core.tests.test_multiarray.TestIO.decimal_sep_localization (self, request)
Including this fixture in a test will automatically
execute it with both types of decimal separator.
So::
    def test_decimal(decimal_sep_localization):
        pass
is equivalent to the following two tests::
    def test_decimal_period_separator():
        pass
    def test_decimal_comma_separator():
        with CommaDecimalPointLocale():
            pass
Definition at line 5533 of file test_multiarray.py.
References _check_from(), and numpy.core.fromnumeric.reshape().
test_ascii()
numpy.core.tests.test_multiarray.TestIO.test_ascii (self, tmp_filename, decimal_sep_localization)
Definition at line 5608 of file test_multiarray.py.
test_binary()
numpy.core.tests.test_multiarray.TestIO.test_binary (self, tmp_filename)
Definition at line 5581 of file test_multiarray.py.
test_bool_fromstring()
numpy.core.tests.test_multiarray.TestIO.test_bool_fromstring (self)
Definition at line 5288 of file test_multiarray.py.
test_counted_string()
numpy.core.tests.test_multiarray.TestIO.test_counted_string (self, tmp_filename, decimal_sep_localization)
Definition at line 5591 of file test_multiarray.py.
test_counted_string_with_ws()
numpy.core.tests.test_multiarray.TestIO.test_counted_string_with_ws (self, tmp_filename)
Definition at line 5603 of file test_multiarray.py.
test_dtype()
numpy.core.tests.test_multiarray.TestIO.test_dtype (self, tmp_filename)
Definition at line 5623 of file test_multiarray.py.
test_dtype_bool()
numpy.core.tests.test_multiarray.TestIO.test_dtype_bool (self, tmp_filename)
Definition at line 5627 of file test_multiarray.py.
test_empty_files_binary()
numpy.core.tests.test_multiarray.TestIO.test_empty_files_binary (self, tmp_filename)
Definition at line 5315 of file test_multiarray.py.
test_empty_files_text()
numpy.core.tests.test_multiarray.TestIO.test_empty_files_text (self, tmp_filename)
Definition at line 5309 of file test_multiarray.py.
test_file_position_after_fromfile()
numpy.core.tests.test_multiarray.TestIO.test_file_position_after_fromfile (self, tmp_filename)
Definition at line 5410 of file test_multiarray.py.
test_file_position_after_tofile()
numpy.core.tests.test_multiarray.TestIO.test_file_position_after_tofile (self, tmp_filename)
Definition at line 5430 of file test_multiarray.py.
test_fromfile_bad_dup()
numpy.core.tests.test_multiarray.TestIO.test_fromfile_bad_dup (self, x, tmp_filename)
Definition at line 5503 of file test_multiarray.py.
test_fromfile_offset()
numpy.core.tests.test_multiarray.TestIO.test_fromfile_offset (self, x, tmp_filename)
Definition at line 5468 of file test_multiarray.py.
test_fromfile_subarray_binary()
numpy.core.tests.test_multiarray.TestIO.test_fromfile_subarray_binary (self, tmp_filename)
Definition at line 5666 of file test_multiarray.py.
test_fromstring_count0()
numpy.core.tests.test_multiarray.TestIO.test_fromstring_count0 (self)
Definition at line 5305 of file test_multiarray.py.
test_inf()
numpy.core.tests.test_multiarray.TestIO.test_inf (self, tmp_filename, decimal_sep_localization)
Definition at line 5567 of file test_multiarray.py.
test_int64_fromstring()
numpy.core.tests.test_multiarray.TestIO.test_int64_fromstring (self)
Definition at line 5299 of file test_multiarray.py.
test_io_open_buffered_fromfile()
numpy.core.tests.test_multiarray.TestIO.test_io_open_buffered_fromfile (self, x, tmp_filename)
Definition at line 5403 of file test_multiarray.py.
test_io_open_unbuffered_fromfile()
numpy.core.tests.test_multiarray.TestIO.test_io_open_unbuffered_fromfile (self, x, tmp_filename)
Definition at line 5376 of file test_multiarray.py.
test_largish_file()
numpy.core.tests.test_multiarray.TestIO.test_largish_file (self, tmp_filename)
Definition at line 5383 of file test_multiarray.py.
test_load_object_array_fromfile()
numpy.core.tests.test_multiarray.TestIO.test_load_object_array_fromfile (self, tmp_filename)
Definition at line 5455 of file test_multiarray.py.
test_long_sep()
numpy.core.tests.test_multiarray.TestIO.test_long_sep (self, tmp_filename)
Definition at line 5619 of file test_multiarray.py.
test_malformed()
numpy.core.tests.test_multiarray.TestIO.test_malformed (self, tmp_filename, decimal_sep_localization)
Definition at line 5614 of file test_multiarray.py.
test_nan()
numpy.core.tests.test_multiarray.TestIO.test_nan (self, tmp_filename, decimal_sep_localization)
Definition at line 5560 of file test_multiarray.py.
test_nofile()
numpy.core.tests.test_multiarray.TestIO.test_nofile (self)
Definition at line 5280 of file test_multiarray.py.
test_numbers()
numpy.core.tests.test_multiarray.TestIO.test_numbers (self, tmp_filename, decimal_sep_localization)
Definition at line 5574 of file test_multiarray.py.
test_parsing_subarray_unsupported()
numpy.core.tests.test_multiarray.TestIO.test_parsing_subarray_unsupported (self, tmp_filename)
Definition at line 5679 of file test_multiarray.py.
test_read_shorter_than_count_subarray()
numpy.core.tests.test_multiarray.TestIO.test_read_shorter_than_count_subarray (self, tmp_filename)
Definition at line 5691 of file test_multiarray.py.
test_roundtrip()
numpy.core.tests.test_multiarray.TestIO.test_roundtrip (self, x, tmp_filename)
Definition at line 5329 of file test_multiarray.py.
test_roundtrip_binary_str()
numpy.core.tests.test_multiarray.TestIO.test_roundtrip_binary_str (self, x)
Definition at line 5340 of file test_multiarray.py.
test_roundtrip_dump_pathlib()
numpy.core.tests.test_multiarray.TestIO.test_roundtrip_dump_pathlib (self, x, tmp_filename)
Definition at line 5334 of file test_multiarray.py.
test_roundtrip_file()
numpy.core.tests.test_multiarray.TestIO.test_roundtrip_file (self, x, tmp_filename)
Definition at line 5321 of file test_multiarray.py.
test_roundtrip_repr()
numpy.core.tests.test_multiarray.TestIO.test_roundtrip_repr (self, x)
Definition at line 5358 of file test_multiarray.py.
test_roundtrip_str()
numpy.core.tests.test_multiarray.TestIO.test_roundtrip_str (self, x)
Definition at line 5349 of file test_multiarray.py.
test_string()
numpy.core.tests.test_multiarray.TestIO.test_string (self, tmp_filename)
Definition at line 5588 of file test_multiarray.py.
test_string_with_ws()
numpy.core.tests.test_multiarray.TestIO.test_string_with_ws (self, tmp_filename)
Definition at line 5599 of file test_multiarray.py.
test_tofile_cleanup()
numpy.core.tests.test_multiarray.TestIO.test_tofile_cleanup (self, tmp_filename)
Definition at line 5655 of file test_multiarray.py.
test_tofile_format()
numpy.core.tests.test_multiarray.TestIO.test_tofile_format (self, tmp_filename, decimal_sep_localization)
Definition at line 5647 of file test_multiarray.py.
test_tofile_sep()
numpy.core.tests.test_multiarray.TestIO.test_tofile_sep (self, tmp_filename, decimal_sep_localization)
Definition at line 5637 of file test_multiarray.py.
test_uint64_fromstring()
numpy.core.tests.test_multiarray.TestIO.test_uint64_fromstring (self)
Definition at line 5293 of file test_multiarray.py.
test_unseekable_fromfile()
numpy.core.tests.test_multiarray.TestIO.test_unseekable_fromfile (self, x, tmp_filename)
Definition at line 5364 of file test_multiarray.py.
tmp_filename()
numpy.core.tests.test_multiarray.TestIO.tmp_filename (self, tmp_path, request)
Definition at line 5271 of file test_multiarray.py.
x()
numpy.core.tests.test_multiarray.TestIO.x (self)
Definition at line 5263 of file test_multiarray.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/core/tests/test_multiarray.py