Code Cloning Analysis: pandas.core.reshape.merge Namespace Reference
pandas.core.reshape.merge Namespace Reference
Classes
class _AsOfMerge
class _MergeOperation
class _OrderedMerge
Functions
DataFrame merge (DataFrame|Series left, DataFrame|Series right, MergeHow how="inner", IndexLabel|AnyArrayLike|None on=None, IndexLabel|AnyArrayLike|None left_on=None, IndexLabel|AnyArrayLike|None right_on=None, bool left_index=False, bool right_index=False, bool sort=False, Suffixes suffixes=("_x", "_y"), bool|None copy=None, str|bool indicator=False, str|None validate=None)
DataFrame _cross_merge (DataFrame left, DataFrame right, IndexLabel|AnyArrayLike|None on=None, IndexLabel|AnyArrayLike|None left_on=None, IndexLabel|AnyArrayLike|None right_on=None, bool left_index=False, bool right_index=False, bool sort=False, Suffixes suffixes=("_x", "_y"), bool|None copy=None, str|bool indicator=False, str|None validate=None)
_groupby_and_merge (by, DataFrame|Series left, DataFrame|Series right, merge_pieces)
DataFrame merge_ordered (DataFrame|Series left, DataFrame|Series right, IndexLabel|None on=None, IndexLabel|None left_on=None, IndexLabel|None right_on=None, left_by=None, right_by=None, str|None fill_method=None, Suffixes suffixes=("_x", "_y"), JoinHow how="outer")
DataFrame merge_asof (DataFrame|Series left, DataFrame|Series right, IndexLabel|None on=None, IndexLabel|None left_on=None, IndexLabel|None right_on=None, bool left_index=False, bool right_index=False, by=None, left_by=None, right_by=None, Suffixes suffixes=("_x", "_y"), int|Timedelta|None tolerance=None, bool allow_exact_matches=True, str direction="backward")
tuple[npt.NDArray[np.intp]|None, npt.NDArray[np.intp]|None] get_join_indexers (list[ArrayLike] left_keys, list[ArrayLike] right_keys, bool sort=False, JoinHow how="inner")
tuple[npt.NDArray[np.intp], npt.NDArray[np.intp]] get_join_indexers_non_unique (ArrayLike left, ArrayLike right, bool sort=False, JoinHow how="inner")
tuple[FrozenList, FrozenList, FrozenList] restore_dropped_levels_multijoin (MultiIndex left, MultiIndex right, dropped_level_names, Index join_index, npt.NDArray[np.intp] lindexer, npt.NDArray[np.intp] rindexer)
_asof_by_function (str direction)
tuple[npt.NDArray[np.intp], npt.NDArray[np.intp]] _get_multiindex_indexer (list[ArrayLike] join_keys, MultiIndex index, bool sort)
tuple[npt.NDArray[np.intp], npt.NDArray[np.intp]] _get_empty_indexer ()
tuple[npt.NDArray[np.intp], npt.NDArray[np.intp]] _get_no_sort_one_missing_indexer (int n, bool left_missing)
tuple[Index, npt.NDArray[np.intp]|None, npt.NDArray[np.intp]] _left_join_on_index (Index left_ax, Index right_ax, list[ArrayLike] join_keys, bool sort=False)
tuple[npt.NDArray[np.intp], npt.NDArray[np.intp], int] _factorize_keys (ArrayLike lk, ArrayLike rk, bool sort=True)
tuple[type[libhashtable.Factorizer], ArrayLike, ArrayLike] _convert_arrays_and_get_rizer_klass (ArrayLike lk, ArrayLike rk)
tuple[npt.NDArray[np.intp], npt.NDArray[np.intp]] _sort_labels (np.ndarray uniques, npt.NDArray[np.intp] left, npt.NDArray[np.intp] right)
tuple[npt.NDArray[np.int64], npt.NDArray[np.int64]] _get_join_keys (list[npt.NDArray[np.int64|np.intp]] llab, list[npt.NDArray[np.int64|np.intp]] rlab, Shape shape, bool sort)
bool _should_fill (lname, rname)
bool _any (x)
DataFrame _validate_operand (DataFrame|Series obj)
tuple[Index, Index] _items_overlap_with_suffix (Index left, Index right, Suffixes suffixes)
Variables
dict _factorizers
tuple _known = (np.ndarray, ExtensionArray, Index, ABCSeries)
Detailed Description
SQL-style merge routines
Function Documentation
_any()
bool pandas.core.reshape.merge._any (x) protected
Definition at line 2680 of file merge.py.
_asof_by_function()
pandas.core.reshape.merge._asof_by_function (str direction) protected
Definition at line 1955 of file merge.py.
_convert_arrays_and_get_rizer_klass()
tuple[type[libhashtable.Factorizer], ArrayLike, ArrayLike] pandas.core.reshape.merge._convert_arrays_and_get_rizer_klass (ArrayLike lk, ArrayLike rk) protected
Definition at line 2588 of file merge.py.
_cross_merge()
DataFrame pandas.core.reshape.merge._cross_merge (DataFrame left, DataFrame right, IndexLabel | AnyArrayLike | None on = None, IndexLabel | AnyArrayLike | None left_on = None, IndexLabel | AnyArrayLike | None right_on = None, bool left_index = False, bool right_index = False, bool sort = False, Suffixes suffixes = ("_x", "_y"), bool | None copy = None, str | bool indicator = False, str | None validate = None) protected
See merge.__doc__ with how='cross'
Definition at line 187 of file merge.py.
_factorize_keys()
tuple[npt.NDArray[np.intp], npt.NDArray[np.intp], int] pandas.core.reshape.merge._factorize_keys (ArrayLike lk, ArrayLike rk, bool sort = True) protected
Encode left and right keys as enumerated types.
This is used to get the join indexers to be used when merging DataFrames.
Parameters
----------
lk : ndarray, ExtensionArray
    Left key.
rk : ndarray, ExtensionArray
    Right key.
sort : bool, defaults to True
    If True, the encoding is done such that the unique elements in the
    keys are sorted.
Returns
-------
np.ndarray[np.intp]
    Left (resp. right if called with `key='right'`) labels, as enumerated type.
np.ndarray[np.intp]
    Right (resp. left if called with `key='right'`) labels, as enumerated type.
int
    Number of unique elements in union of left and right labels.
See Also
--------
merge : Merge DataFrame or named Series objects
    with a database-style join.
algorithms.factorize : Encode the object as an enumerated type
    or categorical variable.
Examples
--------
>>> lk = np.array(["a", "c", "b"])
>>> rk = np.array(["a", "c"])
Here, the unique values are `'a', 'b', 'c'`. With the default
`sort=True`, the encoding will be `{0: 'a', 1: 'b', 2: 'c'}`:
>>> pd.core.reshape.merge._factorize_keys(lk, rk)
(array([0, 2, 1]), array([0, 2]), 3)
With the `sort=False`, the encoding will correspond to the order
in which the unique elements first appear: `{0: 'a', 1: 'c', 2: 'b'}`:
>>> pd.core.reshape.merge._factorize_keys(lk, rk, sort=False)
(array([0, 1, 2]), array([0, 1]), 3)
Definition at line 2399 of file merge.py.
References _factorize_keys().
Referenced by _factorize_keys(), pandas.core.reshape.merge._AsOfMerge._get_join_indexers(), _get_no_sort_one_missing_indexer(), get_join_indexers(), and get_join_indexers_non_unique().
_get_empty_indexer()
tuple[npt.NDArray[np.intp], npt.NDArray[np.intp]] pandas.core.reshape.merge._get_empty_indexer () protected
Return empty join indexers.
Definition at line 2334 of file merge.py.
Referenced by get_join_indexers().
_get_join_keys()
tuple[npt.NDArray[np.int64], npt.NDArray[np.int64]] pandas.core.reshape.merge._get_join_keys (list[npt.NDArray[np.int64 | np.intp]] llab, list[npt.NDArray[np.int64 | np.intp]] rlab, Shape shape, bool sort) protected
Definition at line 2637 of file merge.py.
_get_multiindex_indexer()
tuple[npt.NDArray[np.intp], npt.NDArray[np.intp]] pandas.core.reshape.merge._get_multiindex_indexer (list[ArrayLike] join_keys, MultiIndex index, bool sort) protected
Definition at line 2301 of file merge.py.
_get_no_sort_one_missing_indexer()
tuple[npt.NDArray[np.intp], npt.NDArray[np.intp]] pandas.core.reshape.merge._get_no_sort_one_missing_indexer (int n, bool left_missing) protected
Return join indexers where all of one side is selected without sorting
and none of the other side is selected.
Parameters
----------
n : int
    Length of indexers to create.
left_missing : bool
    If True, the left indexer will contain only -1's.
    If False, the right indexer will contain only -1's.
Returns
-------
np.ndarray[np.intp]
    Left indexer
np.ndarray[np.intp]
    Right indexer
Definition at line 2342 of file merge.py.
References _factorize_keys().
Referenced by get_join_indexers().
_groupby_and_merge()
pandas.core.reshape.merge._groupby_and_merge (by, DataFrame | Series left, DataFrame | Series right, merge_pieces) protected
groupby & merge; we are always performing a left-by type operation
Parameters
----------
by: field to group
left: DataFrame
right: DataFrame
merge_pieces: function for merging
Definition at line 242 of file merge.py.
Referenced by merge_ordered().
_items_overlap_with_suffix()
tuple[Index, Index] pandas.core.reshape.merge._items_overlap_with_suffix (Index left, Index right, Suffixes suffixes) protected
Suffixes type validation.
If two indices overlap, add suffixes to overlapping entries.
If corresponding suffix is empty, the entry is simply converted to string.
Definition at line 2697 of file merge.py.
Referenced by pandas.core.reshape.merge._MergeOperation._reindex_and_concat().
_left_join_on_index()
tuple[Index, npt.NDArray[np.intp] | None, npt.NDArray[np.intp]] pandas.core.reshape.merge._left_join_on_index (Index left_ax, Index right_ax, list[ArrayLike] join_keys, bool sort = False) protected
Definition at line 2371 of file merge.py.
_should_fill()
bool pandas.core.reshape.merge._should_fill (lname, rname) protected
Definition at line 2674 of file merge.py.
_sort_labels()
tuple[npt.NDArray[np.intp], npt.NDArray[np.intp]] pandas.core.reshape.merge._sort_labels (np.ndarray uniques, npt.NDArray[np.intp] left, npt.NDArray[np.intp] right) protected
Definition at line 2625 of file merge.py.
_validate_operand()
DataFrame pandas.core.reshape.merge._validate_operand (DataFrame | Series obj) protected
Definition at line 2684 of file merge.py.
get_join_indexers()
tuple[npt.NDArray[np.intp] | None, npt.NDArray[np.intp] | None] pandas.core.reshape.merge.get_join_indexers (list[ArrayLike] left_keys, list[ArrayLike] right_keys, bool sort = False, JoinHow how = "inner")
Parameters
----------
left_keys : list[ndarray, ExtensionArray, Index, Series]
right_keys : list[ndarray, ExtensionArray, Index, Series]
sort : bool, default False
how : {'inner', 'outer', 'left', 'right'}, default 'inner'
Returns
-------
np.ndarray[np.intp] or None
    Indexer into the left_keys.
np.ndarray[np.intp] or None
    Indexer into the right_keys.
Definition at line 1693 of file merge.py.
References _factorize_keys(), _get_empty_indexer(), _get_no_sort_one_missing_indexer(), and get_join_indexers_non_unique().
Referenced by pandas.core.reshape.merge._MergeOperation._get_join_indexers().
get_join_indexers_non_unique()
tuple[npt.NDArray[np.intp], npt.NDArray[np.intp]] pandas.core.reshape.merge.get_join_indexers_non_unique (ArrayLike left, ArrayLike right, bool sort = False, JoinHow how = "inner")
Get join indexers for left and right.
Parameters
----------
left : ArrayLike
right : ArrayLike
sort : bool, default False
how : {'inner', 'outer', 'left', 'right'}, default 'inner'
Returns
-------
np.ndarray[np.intp]
    Indexer into left.
np.ndarray[np.intp]
    Indexer into right.
Definition at line 1771 of file merge.py.
References _factorize_keys().
Referenced by get_join_indexers().
merge()
DataFrame pandas.core.reshape.merge.merge (DataFrame | Series left, DataFrame | Series right, MergeHow how = "inner", IndexLabel | AnyArrayLike | None on = None, IndexLabel | AnyArrayLike | None left_on = None, IndexLabel | AnyArrayLike | None right_on = None, bool left_index = False, bool right_index = False, bool sort = False, Suffixes suffixes = ("_x", "_y"), bool | None copy = None, str | bool indicator = False, str | None validate = None)
Definition at line 137 of file merge.py.
merge_asof()
DataFrame pandas.core.reshape.merge.merge_asof (DataFrame | Series left, DataFrame | Series right, IndexLabel | None on = None, IndexLabel | None left_on = None, IndexLabel | None right_on = None, bool left_index = False, bool right_index = False, by = None, left_by = None, right_by = None, Suffixes suffixes = ("_x", "_y"), int | Timedelta | None tolerance = None, bool allow_exact_matches = True, str direction = "backward")
Perform a merge by key distance.
This is similar to a left-join except that we match on nearest
key rather than equal keys. Both DataFrames must be sorted by the key.
For each row in the left DataFrame:
  - A "backward" search selects the last row in the right DataFrame whose
    'on' key is less than or equal to the left's key.
  - A "forward" search selects the first row in the right DataFrame whose
    'on' key is greater than or equal to the left's key.
  - A "nearest" search selects the row in the right DataFrame whose 'on'
    key is closest in absolute distance to the left's key.
Optionally match on equivalent keys with 'by' before searching with 'on'.
Parameters
----------
left : DataFrame or named Series
right : DataFrame or named Series
on : label
    Field name to join on. Must be found in both DataFrames.
    The data MUST be ordered. Furthermore this must be a numeric column,
    such as datetimelike, integer, or float. On or left_on/right_on
    must be given.
left_on : label
    Field name to join on in left DataFrame.
right_on : label
    Field name to join on in right DataFrame.
left_index : bool
    Use the index of the left DataFrame as the join key.
right_index : bool
    Use the index of the right DataFrame as the join key.
by : column name or list of column names
    Match on these columns before performing merge operation.
left_by : column name
    Field names to match on in the left DataFrame.
right_by : column name
    Field names to match on in the right DataFrame.
suffixes : 2-length sequence (tuple, list, ...)
    Suffix to apply to overlapping column names in the left and right
    side, respectively.
tolerance : int or Timedelta, optional, default None
    Select asof tolerance within this range; must be compatible
    with the merge index.
allow_exact_matches : bool, default True
    - If True, allow matching with the same 'on' value
      (i.e. less-than-or-equal-to / greater-than-or-equal-to)
    - If False, don't match the same 'on' value
      (i.e., strictly less-than / strictly greater-than).
direction : 'backward' (default), 'forward', or 'nearest'
    Whether to search for prior, subsequent, or closest matches.
Returns
-------
DataFrame
See Also
--------
merge : Merge with a database-style join.
merge_ordered : Merge with optional filling/interpolation.
Examples
--------
>>> left = pd.DataFrame({"a": [1, 5, 10], "left_val": ["a", "b", "c"]})
>>> left
    a left_val
0   1        a
1   5        b
2  10        c
>>> right = pd.DataFrame({"a": [1, 2, 3, 6, 7], "right_val": [1, 2, 3, 6, 7]})
>>> right
   a  right_val
0  1          1
1  2          2
2  3          3
3  6          6
4  7          7
>>> pd.merge_asof(left, right, on="a")
    a left_val  right_val
0   1        a          1
1   5        b          3
2  10        c          7
>>> pd.merge_asof(left, right, on="a", allow_exact_matches=False)
    a left_val  right_val
0   1        a        NaN
1   5        b        3.0
2  10        c        7.0
>>> pd.merge_asof(left, right, on="a", direction="forward")
    a left_val  right_val
0   1        a        1.0
1   5        b        6.0
2  10        c        NaN
>>> pd.merge_asof(left, right, on="a", direction="nearest")
    a left_val  right_val
0   1        a          1
1   5        b          6
2  10        c          7
We can use indexed DataFrames as well.
>>> left = pd.DataFrame({"left_val": ["a", "b", "c"]}, index=[1, 5, 10])
>>> left
   left_val
1         a
5         b
10        c
>>> right = pd.DataFrame({"right_val": [1, 2, 3, 6, 7]}, index=[1, 2, 3, 6, 7])
>>> right
   right_val
1          1
2          2
3          3
6          6
7          7
>>> pd.merge_asof(left, right, left_index=True, right_index=True)
   left_val  right_val
1         a          1
5         b          3
10        c          7
Here is a real-world times-series example
>>> quotes = pd.DataFrame(
...     {
...         "time": [
...             pd.Timestamp("2016-05-25 13:30:00.023"),
...             pd.Timestamp("2016-05-25 13:30:00.023"),
...             pd.Timestamp("2016-05-25 13:30:00.030"),
...             pd.Timestamp("2016-05-25 13:30:00.041"),
...             pd.Timestamp("2016-05-25 13:30:00.048"),
...             pd.Timestamp("2016-05-25 13:30:00.049"),
...             pd.Timestamp("2016-05-25 13:30:00.072"),
...             pd.Timestamp("2016-05-25 13:30:00.075")
...         ],
...         "ticker": [
...                "GOOG",
...                "MSFT",
...                "MSFT",
...                "MSFT",
...                "GOOG",
...                "AAPL",
...                "GOOG",
...                "MSFT"
...            ],
...            "bid": [720.50, 51.95, 51.97, 51.99, 720.50, 97.99, 720.50, 52.01],
...            "ask": [720.93, 51.96, 51.98, 52.00, 720.93, 98.01, 720.88, 52.03]
...     }
...)
>>> quotes
                     time ticker     bid     ask
0 2016-05-25 13:30:00.023   GOOG  720.50  720.93
1 2016-05-25 13:30:00.023   MSFT   51.95   51.96
2 2016-05-25 13:30:00.030   MSFT   51.97   51.98
3 2016-05-25 13:30:00.041   MSFT   51.99   52.00
4 2016-05-25 13:30:00.048   GOOG  720.50  720.93
5 2016-05-25 13:30:00.049   AAPL   97.99   98.01
6 2016-05-25 13:30:00.072   GOOG  720.50  720.88
7 2016-05-25 13:30:00.075   MSFT   52.01   52.03
>>> trades = pd.DataFrame(
...        {
...            "time": [
...                pd.Timestamp("2016-05-25 13:30:00.023"),
...                pd.Timestamp("2016-05-25 13:30:00.038"),
...                pd.Timestamp("2016-05-25 13:30:00.048"),
...                pd.Timestamp("2016-05-25 13:30:00.048"),
...                pd.Timestamp("2016-05-25 13:30:00.048")
...            ],
...            "ticker": ["MSFT", "MSFT", "GOOG", "GOOG", "AAPL"],
...            "price": [51.95, 51.95, 720.77, 720.92, 98.0],
...            "quantity": [75, 155, 100, 100, 100]
...        }
...)
>>> trades
                     time ticker   price  quantity
0 2016-05-25 13:30:00.023   MSFT   51.95        75
1 2016-05-25 13:30:00.038   MSFT   51.95       155
2 2016-05-25 13:30:00.048   GOOG  720.77       100
3 2016-05-25 13:30:00.048   GOOG  720.92       100
4 2016-05-25 13:30:00.048   AAPL   98.00       100
By default we are taking the asof of the quotes
>>> pd.merge_asof(trades, quotes, on="time", by="ticker")
                     time ticker   price  quantity     bid     ask
0 2016-05-25 13:30:00.023   MSFT   51.95        75   51.95   51.96
1 2016-05-25 13:30:00.038   MSFT   51.95       155   51.97   51.98
2 2016-05-25 13:30:00.048   GOOG  720.77       100  720.50  720.93
3 2016-05-25 13:30:00.048   GOOG  720.92       100  720.50  720.93
4 2016-05-25 13:30:00.048   AAPL   98.00       100     NaN     NaN
We only asof within 2ms between the quote time and the trade time
>>> pd.merge_asof(
...     trades, quotes, on="time", by="ticker", tolerance=pd.Timedelta("2ms")
...)
                     time ticker   price  quantity     bid     ask
0 2016-05-25 13:30:00.023   MSFT   51.95        75   51.95   51.96
1 2016-05-25 13:30:00.038   MSFT   51.95       155     NaN     NaN
2 2016-05-25 13:30:00.048   GOOG  720.77       100  720.50  720.93
3 2016-05-25 13:30:00.048   GOOG  720.92       100  720.50  720.93
4 2016-05-25 13:30:00.048   AAPL   98.00       100     NaN     NaN
We only asof within 10ms between the quote time and the trade time
and we exclude exact matches on time. However *prior* data will
propagate forward
>>> pd.merge_asof(
...     trades,
...     quotes,
...     on="time",
...     by="ticker",
...     tolerance=pd.Timedelta("10ms"),
...     allow_exact_matches=False
...)
                     time ticker   price  quantity     bid     ask
0 2016-05-25 13:30:00.023   MSFT   51.95        75     NaN     NaN
1 2016-05-25 13:30:00.038   MSFT   51.95       155   51.97   51.98
2 2016-05-25 13:30:00.048   GOOG  720.77       100     NaN     NaN
3 2016-05-25 13:30:00.048   GOOG  720.92       100     NaN     NaN
4 2016-05-25 13:30:00.048   AAPL   98.00       100     NaN     NaN
Definition at line 440 of file merge.py.
merge_ordered()
DataFrame pandas.core.reshape.merge.merge_ordered (DataFrame | Series left, DataFrame | Series right, IndexLabel | None on = None, IndexLabel | None left_on = None, IndexLabel | None right_on = None, left_by = None, right_by = None, str | None fill_method = None, Suffixes suffixes = ("_x", "_y"), JoinHow how = "outer")
Perform a merge for ordered data with optional filling/interpolation.
Designed for ordered data like time series data. Optionally
perform group-wise merge (see examples).
Parameters
----------
left : DataFrame or named Series
right : DataFrame or named Series
on : label or list
    Field names to join on. Must be found in both DataFrames.
left_on : label or list, or array-like
    Field names to join on in left DataFrame. Can be a vector or list of
    vectors of the length of the DataFrame to use a particular vector as
    the join key instead of columns.
right_on : label or list, or array-like
    Field names to join on in right DataFrame or vector/list of vectors per
    left_on docs.
left_by : column name or list of column names
    Group left DataFrame by group columns and merge piece by piece with
    right DataFrame. Must be None if either left or right are a Series.
right_by : column name or list of column names
    Group right DataFrame by group columns and merge piece by piece with
    left DataFrame. Must be None if either left or right are a Series.
fill_method : {'ffill', None}, default None
    Interpolation method for data.
suffixes : list-like, default is ("_x", "_y")
    A length-2 sequence where each element is optionally a string
    indicating the suffix to add to overlapping column names in
    `left` and `right` respectively. Pass a value of `None` instead
    of a string to indicate that the column name from `left` or
    `right` should be left as-is, with no suffix. At least one of the
    values must not be None.
how : {'left', 'right', 'outer', 'inner'}, default 'outer'
    * left: use only keys from left frame (SQL: left outer join)
    * right: use only keys from right frame (SQL: right outer join)
    * outer: use union of keys from both frames (SQL: full outer join)
    * inner: use intersection of keys from both frames (SQL: inner join).
Returns
-------
DataFrame
    The merged DataFrame output type will be the same as
    'left', if it is a subclass of DataFrame.
See Also
--------
merge : Merge with a database-style join.
merge_asof : Merge on nearest keys.
Examples
--------
>>> from pandas import merge_ordered
>>> df1 = pd.DataFrame(
...     {
...         "key": ["a", "c", "e", "a", "c", "e"],
...         "lvalue": [1, 2, 3, 1, 2, 3],
...         "group": ["a", "a", "a", "b", "b", "b"]
...     }
...)
>>> df1
  key  lvalue group
0   a       1     a
1   c       2     a
2   e       3     a
3   a       1     b
4   c       2     b
5   e       3     b
>>> df2 = pd.DataFrame({"key": ["b", "c", "d"], "rvalue": [1, 2, 3]})
>>> df2
  key  rvalue
0   b       1
1   c       2
2   d       3
>>> merge_ordered(df1, df2, fill_method="ffill", left_by="group")
  key  lvalue group  rvalue
0   a       1     a     NaN
1   b       1     a     1.0
2   c       2     a     2.0
3   d       2     a     3.0
4   e       3     a     3.0
5   a       1     b     NaN
6   b       1     b     1.0
7   c       2     b     2.0
8   d       2     b     3.0
9   e       3     b     3.0
Definition at line 299 of file merge.py.
References _groupby_and_merge().
restore_dropped_levels_multijoin()
tuple[FrozenList, FrozenList, FrozenList] pandas.core.reshape.merge.restore_dropped_levels_multijoin (MultiIndex left, MultiIndex right, dropped_level_names, Index join_index, npt.NDArray[np.intp] lindexer, npt.NDArray[np.intp] rindexer)
*this is an internal non-public method*
Returns the levels, labels and names of a multi-index to multi-index join.
Depending on the type of join, this method restores the appropriate
dropped levels of the joined multi-index.
The method relies on lindexer, rindexer which hold the index positions of
left and right, where a join was feasible
Parameters
----------
left : MultiIndex
    left index
right : MultiIndex
    right index
dropped_level_names : str array
    list of non-common level names
join_index : Index
    the index of the join between the
    common levels of left and right
lindexer : np.ndarray[np.intp]
    left indexer
rindexer : np.ndarray[np.intp]
    right indexer
Returns
-------
levels : list of Index
    levels of combined multiindexes
labels : np.ndarray[np.intp]
    labels of combined multiindexes
names : List[Hashable]
    names of combined multiindex levels
Definition at line 1806 of file merge.py.
Variable Documentation
_factorizers
dict pandas.core.reshape.merge._factorizers protected
Initial value:
=  {
    np.int64: libhashtable.Int64Factorizer,
    np.longlong: libhashtable.Int64Factorizer,
    np.int32: libhashtable.Int32Factorizer,
    np.int16: libhashtable.Int16Factorizer,
    np.int8: libhashtable.Int8Factorizer,
    np.uint64: libhashtable.UInt64Factorizer,
    np.uint32: libhashtable.UInt32Factorizer,
    np.uint16: libhashtable.UInt16Factorizer,
    np.uint8: libhashtable.UInt8Factorizer,
    np.bool_: libhashtable.UInt8Factorizer,
    np.float64: libhashtable.Float64Factorizer,
    np.float32: libhashtable.Float32Factorizer,
    np.complex64: libhashtable.Complex64Factorizer,
    np.complex128: libhashtable.Complex128Factorizer,
    np.object_: libhashtable.ObjectFactorizer,
}
Definition at line 110 of file merge.py.
_known
tuple pandas.core.reshape.merge._known = (np.ndarray, ExtensionArray, Index, ABCSeries) protected
Definition at line 132 of file merge.py.