Code Cloning Analysis: pandas.io.clipboard Namespace Reference
pandas.io.clipboard Namespace Reference
Classes
class CheckedCall
class PyperclipTimeoutException
Functions
str _stringifyText (text)
init_osx_pbcopy_clipboard ()
init_osx_pyobjc_clipboard ()
init_qt_clipboard ()
init_xclip_clipboard ()
init_xsel_clipboard ()
init_wl_clipboard ()
init_klipper_clipboard ()
init_dev_clipboard_clipboard ()
init_no_clipboard ()
init_windows_clipboard ()
init_wsl_clipboard ()
determine_clipboard ()
set_clipboard (clipboard)
lazy_load_stub_copy (text)
lazy_load_stub_paste ()
bool is_available ()
waitForPaste (timeout=None)
waitForNewPaste (timeout=None)
Variables
str __version__ = "1.8.2"
HAS_DISPLAY = os.getenv("DISPLAY")
str EXCEPT_MSG
str ENCODING = "utf-8"
copy
paste
list __all__
clipboard_get = paste
clipboard_set = copy
Detailed Description
Pyperclip
A cross-platform clipboard module for Python,
with copy & paste functions for plain text.
By Al Sweigart al@inventwithpython.com
Licence at LICENSES/PYPERCLIP_LICENSE
Usage:
  import pyperclip
  pyperclip.copy('The text to be copied to the clipboard.')
  spam = pyperclip.paste()
  if not pyperclip.is_available():
    print("Copy functionality unavailable!")
On Windows, no additional modules are needed.
On Mac, the pyobjc module is used, falling back to the pbcopy and pbpaste cli
    commands. (These commands should come with OS X.).
On Linux, install xclip, xsel, or wl-clipboard (for "wayland" sessions) via
package manager.
For example, in Debian:
    sudo apt-get install xclip
    sudo apt-get install xsel
    sudo apt-get install wl-clipboard
Otherwise on Linux, you will need the PyQt5 modules installed.
This module does not work with PyGObject yet.
Cygwin is currently not supported.
Security Note: This module runs programs with these names:
    - pbcopy
    - pbpaste
    - xclip
    - xsel
    - wl-copy/wl-paste
    - klipper
    - qdbus
A malicious user could rename or add programs with these names, tricking
Pyperclip into running them with whatever permissions the Python process has.
Function Documentation
_stringifyText()
str pandas.io.clipboard._stringifyText (text) protected
Definition at line 89 of file __init__.py.
determine_clipboard()
pandas.io.clipboard.determine_clipboard ()
Determine the OS/platform and set the copy() and paste() functions
accordingly.
Definition at line 527 of file __init__.py.
Referenced by lazy_load_stub_copy(), and lazy_load_stub_paste().
init_dev_clipboard_clipboard()
pandas.io.clipboard.init_dev_clipboard_clipboard ()
Definition at line 287 of file __init__.py.
init_klipper_clipboard()
pandas.io.clipboard.init_klipper_clipboard ()
Definition at line 249 of file __init__.py.
init_no_clipboard()
pandas.io.clipboard.init_no_clipboard ()
Definition at line 313 of file __init__.py.
init_osx_pbcopy_clipboard()
pandas.io.clipboard.init_osx_pbcopy_clipboard ()
Definition at line 99 of file __init__.py.
init_osx_pyobjc_clipboard()
pandas.io.clipboard.init_osx_pyobjc_clipboard ()
Definition at line 117 of file __init__.py.
init_qt_clipboard()
pandas.io.clipboard.init_qt_clipboard ()
Definition at line 136 of file __init__.py.
init_windows_clipboard()
pandas.io.clipboard.init_windows_clipboard ()
Definition at line 339 of file __init__.py.
init_wl_clipboard()
pandas.io.clipboard.init_wl_clipboard ()
Definition at line 223 of file __init__.py.
init_wsl_clipboard()
pandas.io.clipboard.init_wsl_clipboard ()
Definition at line 505 of file __init__.py.
init_xclip_clipboard()
pandas.io.clipboard.init_xclip_clipboard ()
Definition at line 165 of file __init__.py.
init_xsel_clipboard()
pandas.io.clipboard.init_xsel_clipboard ()
Definition at line 196 of file __init__.py.
is_available()
bool pandas.io.clipboard.is_available ()
Definition at line 684 of file __init__.py.
lazy_load_stub_copy()
pandas.io.clipboard.lazy_load_stub_copy (text)
A stub function for copy(), which will load the real copy() function when
called so that the real copy() function is used for later calls.
This allows users to import pyperclip without having determine_clipboard()
automatically run, which will automatically select a clipboard mechanism.
This could be a problem if it selects, say, the memory-heavy PyQt4 module
but the user was just going to immediately call set_clipboard() to use a
different clipboard mechanism.
The lazy loading this stub function implements gives the user a chance to
call set_clipboard() to pick another clipboard mechanism. Or, if the user
simply calls copy() or paste() without calling set_clipboard() first,
will fall back on whatever clipboard mechanism that determine_clipboard()
automatically chooses.
Definition at line 640 of file __init__.py.
References determine_clipboard().
lazy_load_stub_paste()
pandas.io.clipboard.lazy_load_stub_paste ()
A stub function for paste(), which will load the real paste() function when
called so that the real paste() function is used for later calls.
This allows users to import pyperclip without having determine_clipboard()
automatically run, which will automatically select a clipboard mechanism.
This could be a problem if it selects, say, the memory-heavy PyQt4 module
but the user was just going to immediately call set_clipboard() to use a
different clipboard mechanism.
The lazy loading this stub function implements gives the user a chance to
call set_clipboard() to pick another clipboard mechanism. Or, if the user
simply calls copy() or paste() without calling set_clipboard() first,
will fall back on whatever clipboard mechanism that determine_clipboard()
automatically chooses.
Definition at line 662 of file __init__.py.
References determine_clipboard().
set_clipboard()
pandas.io.clipboard.set_clipboard (clipboard)
Explicitly sets the clipboard mechanism. The "clipboard mechanism" is how
the copy() and paste() functions interact with the operating system to
implement the copy/paste feature. The clipboard parameter must be one of:
    - pbcopy
    - pyobjc (default on macOS)
    - qt
    - xclip
    - xsel
    - klipper
    - windows (default on Windows)
    - no (this is what is set when no clipboard mechanism can be found)
Definition at line 602 of file __init__.py.
waitForNewPaste()
pandas.io.clipboard.waitForNewPaste (timeout = None)
This function call blocks until a new text string exists on the
clipboard that is different from the text that was there when the function
was first called. It returns this text.
This function raises PyperclipTimeoutException if timeout was set to
a number of seconds that has elapsed without non-empty text being put on
the clipboard.
Definition at line 714 of file __init__.py.
waitForPaste()
pandas.io.clipboard.waitForPaste (timeout = None)
This function call blocks until a non-empty text string exists on the
clipboard. It returns this text.
This function raises PyperclipTimeoutException if timeout was set to
a number of seconds that has elapsed without non-empty text being put on
the clipboard.
Definition at line 694 of file __init__.py.
Variable Documentation
__all__
list pandas.io.clipboard.__all__ private
Initial value:
=  [
    "copy",
    "paste",
    "waitForPaste",
    "waitForNewPaste",
    "set_clipboard",
    "determine_clipboard",
]
Definition at line 736 of file __init__.py.
__version__
str pandas.io.clipboard.__version__ = "1.8.2" private
Definition at line 46 of file __init__.py.
clipboard_get
pandas.io.clipboard.clipboard_get = paste
Definition at line 746 of file __init__.py.
clipboard_set
pandas.io.clipboard.clipboard_set = copy
Definition at line 747 of file __init__.py.
copy
pandas.io.clipboard.copy
Definition at line 691 of file __init__.py.
ENCODING
str pandas.io.clipboard.ENCODING = "utf-8"
Definition at line 82 of file __init__.py.
EXCEPT_MSG
str pandas.io.clipboard.EXCEPT_MSG
Initial value:
=  """
    Pyperclip could not find a copy/paste mechanism for your system.
    For more information, please visit
    https://pyperclip.readthedocs.io/en/latest/index.html#not-implemented-error
    """
Definition at line 76 of file __init__.py.
HAS_DISPLAY
pandas.io.clipboard.HAS_DISPLAY = os.getenv("DISPLAY")
Definition at line 74 of file __init__.py.
paste
pandas.io.clipboard.paste
Definition at line 691 of file __init__.py.