Code Cloning Analysis: joblib._memmapping_reducer.TemporaryResourcesManager Class Reference
joblib._memmapping_reducer.TemporaryResourcesManager Class Reference
Public Member Functions
__init__ (self, temp_folder_root=None, context_id=None)
set_current_context (self, context_id)
register_new_context (self, context_id)
resolve_temp_folder_name (self)
register_folder_finalizer (self, pool_subfolder, context_id)
Protected Member Functions
_clean_temporary_resources (self, context_id=None, force=False, allow_non_empty=False)
Protected Attributes
_current_temp_folder = None
_temp_folder_root = temp_folder_root
_use_shared_mem = None
_cached_temp_folders = dict()
_id = uuid4().hex
dict _finalizers = {}
_current_context_id = context_id
Detailed Description
Stateful object able to manage temporary folder and pickles
It exposes:
- a per-context folder name resolving API that memmap-based reducers will
  rely on to know where to pickle the temporary memmaps
- a temporary file/folder management API that internally uses the
  resource_tracker.
Definition at line 578 of file _memmapping_reducer.py.
Constructor & Destructor Documentation
__init__()
joblib._memmapping_reducer.TemporaryResourcesManager.__init__ (self, temp_folder_root = None, context_id = None)
Definition at line 588 of file _memmapping_reducer.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_clean_temporary_resources()
joblib._memmapping_reducer.TemporaryResourcesManager._clean_temporary_resources (self, context_id = None, force = False, allow_non_empty = False) protected
Clean temporary resources created by a process-based pool
Definition at line 667 of file _memmapping_reducer.py.
References _cached_temp_folders, _clean_temporary_resources(), and _finalizers.
Referenced by _clean_temporary_resources().
register_folder_finalizer()
joblib._memmapping_reducer.TemporaryResourcesManager.register_folder_finalizer (self, pool_subfolder, context_id)
Definition at line 636 of file _memmapping_reducer.py.
register_new_context()
joblib._memmapping_reducer.TemporaryResourcesManager.register_new_context (self, context_id)
Definition at line 607 of file _memmapping_reducer.py.
resolve_temp_folder_name()
joblib._memmapping_reducer.TemporaryResourcesManager.resolve_temp_folder_name (self)
Return a folder name specific to the currently activated context
Definition at line 630 of file _memmapping_reducer.py.
References _cached_temp_folders, _current_context_id, and _finalizers.
set_current_context()
joblib._memmapping_reducer.TemporaryResourcesManager.set_current_context (self, context_id)
Definition at line 603 of file _memmapping_reducer.py.
Member Data Documentation
_cached_temp_folders
joblib._memmapping_reducer.TemporaryResourcesManager._cached_temp_folders = dict() protected
Definition at line 592 of file _memmapping_reducer.py.
Referenced by _clean_temporary_resources(), and resolve_temp_folder_name().
_current_context_id
joblib._memmapping_reducer.TemporaryResourcesManager._current_context_id = context_id protected
Definition at line 604 of file _memmapping_reducer.py.
Referenced by resolve_temp_folder_name().
_current_temp_folder
joblib._memmapping_reducer.TemporaryResourcesManager._current_temp_folder = None protected
Definition at line 589 of file _memmapping_reducer.py.
_finalizers
dict joblib._memmapping_reducer.TemporaryResourcesManager._finalizers = {} protected
Definition at line 594 of file _memmapping_reducer.py.
Referenced by _clean_temporary_resources(), and resolve_temp_folder_name().
_id
joblib._memmapping_reducer.TemporaryResourcesManager._id = uuid4().hex protected
Definition at line 593 of file _memmapping_reducer.py.
Referenced by joblib.parallel.Parallel.__call__(), pandas.core.indexes.base.Index._reset_identity(), pandas.core.indexes.multi.MultiIndex.copy(), pandas.core.indexes.base.Index.is_(), pandas.core.indexes.base.Index.ravel(), and pandas.core.indexes.multi.MultiIndex.view().
_temp_folder_root
joblib._memmapping_reducer.TemporaryResourcesManager._temp_folder_root = temp_folder_root protected
Definition at line 590 of file _memmapping_reducer.py.
_use_shared_mem
joblib._memmapping_reducer.TemporaryResourcesManager._use_shared_mem = None protected
Definition at line 591 of file _memmapping_reducer.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/joblib/_memmapping_reducer.py