Code Cloning Analysis: pip._vendor.cachecontrol.filewrapper.CallbackFileWrapper Class Reference
pip._vendor.cachecontrol.filewrapper.CallbackFileWrapper Class Reference
Public Member Functions
None __init__ (self, HTTPResponse fp, Callable[[bytes], None]|None callback)
Any __getattr__ (self, str name)
bytes read (self, int|None amt=None)
Protected Member Functions
None _close (self)
bytes _safe_read (self, int amt)
Private Member Functions
bool __is_fp_closed (self)
Private Attributes
__buf = NamedTemporaryFile("rb+", delete=True)
__fp = fp
__callback = callback
Detailed Description
Small wrapper around a fp object which will tee everything read into a
buffer, and when that file is closed it will execute a callback with the
contents of that buffer.
All attributes are proxied to the underlying file object.
This class uses members with a double underscore (__) leading prefix so as
not to accidentally shadow an attribute.
The data is stored in a temporary file until it is all available.  As long
as the temporary files directory is disk-based (sometimes it's a
memory-backed-``tmpfs`` on Linux), data will be unloaded to disk if memory
pressure is high.  For small files the disk usually won't be used at all,
it'll all be in the filesystem memory cache, so there should be no
performance impact.
Definition at line 14 of file filewrapper.py.
Constructor & Destructor Documentation
__init__()
None pip._vendor.cachecontrol.filewrapper.CallbackFileWrapper.__init__ (self, HTTPResponse fp, Callable[[bytes], None] | None callback)
Definition at line 33 of file filewrapper.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
__getattr__()
Any pip._vendor.cachecontrol.filewrapper.CallbackFileWrapper.__getattr__ (self, str name)
Definition at line 40 of file filewrapper.py.
__is_fp_closed()
bool pip._vendor.cachecontrol.filewrapper.CallbackFileWrapper.__is_fp_closed (self) private
Definition at line 52 of file filewrapper.py.
_close()
None pip._vendor.cachecontrol.filewrapper.CallbackFileWrapper._close (self) protected
Definition at line 70 of file filewrapper.py.
_safe_read()
bytes pip._vendor.cachecontrol.filewrapper.CallbackFileWrapper._safe_read (self, int amt) protected
Definition at line 108 of file filewrapper.py.
read()
bytes pip._vendor.cachecontrol.filewrapper.CallbackFileWrapper.read (self, int | None amt = None)
Definition at line 97 of file filewrapper.py.
Referenced by pip._vendor.urllib3.util.ssltransport.SSLTransport.__init__(), pip._vendor.urllib3.response.HTTPResponse.drain_conn(), pip._vendor.urllib3.response.HTTPResponse.from_httplib(), and pip._vendor.urllib3.response.HTTPResponse.stream().
Member Data Documentation
__buf
pip._vendor.cachecontrol.filewrapper.CallbackFileWrapper.__buf = NamedTemporaryFile("rb+", delete=True) private
Definition at line 36 of file filewrapper.py.
__callback
pip._vendor.cachecontrol.filewrapper.CallbackFileWrapper.__callback = callback private
Definition at line 38 of file filewrapper.py.
__fp
pip._vendor.cachecontrol.filewrapper.CallbackFileWrapper.__fp = fp private
Definition at line 37 of file filewrapper.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pip/_vendor/cachecontrol/filewrapper.py