Code Cloning Analysis: sklearn.feature_selection._univariate_selection Namespace Reference
sklearn.feature_selection._univariate_selection Namespace Reference
Classes
class _BaseFilter
Base classes.
class GenericUnivariateSelect
class SelectFdr
class SelectFpr
class SelectFwe
class SelectKBest
class SelectPercentile
Functions
_clean_nans (scores)
f_oneway (*args)
Scoring functions.
f_classif (X, y)
_chisquare (f_obs, f_exp)
chi2 (X, y)
r_regression (X, y, *, center=True, force_finite=True)
f_regression (X, y, *, center=True, force_finite=True)
Detailed Description
Univariate features selection.
Function Documentation
_chisquare()
sklearn.feature_selection._univariate_selection._chisquare (f_obs, f_exp) protected
Fast replacement for scipy.stats.chisquare.
Version from https://github.com/scipy/scipy/pull/2525 with additional
optimizations.
Definition at line 174 of file _univariate_selection.py.
Referenced by chi2().
_clean_nans()
sklearn.feature_selection._univariate_selection._clean_nans (scores) protected
Fixes Issue #1240: NaNs can't be properly compared, so change them to the
smallest value of scores's dtype. -inf seems to be unreliable.
Definition at line 22 of file _univariate_selection.py.
Referenced by sklearn.feature_selection._univariate_selection.SelectKBest._get_support_mask(), and sklearn.feature_selection._univariate_selection.SelectPercentile._get_support_mask().
chi2()
sklearn.feature_selection._univariate_selection.chi2 (X, y)
Compute chi-squared stats between each non-negative feature and class.
This score can be used to select the `n_features` features with the
highest values for the test chi-squared statistic from X, which must
contain only **non-negative integer feature values** such as booleans or frequencies
(e.g., term counts in document classification), relative to the classes.
If some of your features are continuous, you need to bin them, for
example by using :class:`~sklearn.preprocessing.KBinsDiscretizer`.
Recall that the chi-square test measures dependence between stochastic
variables, so using this function "weeds out" the features that are the
most likely to be independent of class and therefore irrelevant for
classification.
Read more in the :ref:`User Guide <univariate_feature_selection>`.
Parameters
----------
X : {array-like, sparse matrix} of shape (n_samples, n_features)
    Sample vectors.
y : array-like of shape (n_samples,)
    Target vector (class labels).
Returns
-------
chi2 : ndarray of shape (n_features,)
    Chi2 statistics for each feature.
p_values : ndarray of shape (n_features,)
    P-values for each feature.
See Also
--------
f_classif : ANOVA F-value between label/feature for classification tasks.
f_regression : F-value between label/feature for regression tasks.
Notes
-----
Complexity of this algorithm is O(n_classes * n_features).
Examples
--------
>>> import numpy as np
>>> from sklearn.feature_selection import chi2
>>> X = np.array([[1, 1, 3],
...               [0, 1, 5],
...               [5, 4, 1],
...               [6, 6, 2],
...               [1, 4, 0],
...               [0, 0, 0]])
>>> y = np.array([1, 1, 0, 0, 2, 2])
>>> chi2_stats, p_values = chi2(X, y)
>>> chi2_stats
array([15.3,  6.5       ,  8.9])
>>> p_values
array([0.000456, 0.0387, 0.0116 ])
Definition at line 200 of file _univariate_selection.py.
References _chisquare().
f_classif()
sklearn.feature_selection._univariate_selection.f_classif (X, y)
Compute the ANOVA F-value for the provided sample.
Read more in the :ref:`User Guide <univariate_feature_selection>`.
Parameters
----------
X : {array-like, sparse matrix} of shape (n_samples, n_features)
    The set of regressors that will be tested sequentially.
y : array-like of shape (n_samples,)
    The target vector.
Returns
-------
f_statistic : ndarray of shape (n_features,)
    F-statistic for each feature.
p_values : ndarray of shape (n_features,)
    P-values associated with the F-statistic.
See Also
--------
chi2 : Chi-squared stats of non-negative features for classification tasks.
f_regression : F-value between label/feature for regression tasks.
Examples
--------
>>> from sklearn.datasets import make_classification
>>> from sklearn.feature_selection import f_classif
>>> X, y = make_classification(
...     n_samples=100, n_features=10, n_informative=2, n_clusters_per_class=1,
...     shuffle=False, random_state=42
...)
>>> f_statistic, p_values = f_classif(X, y)
>>> f_statistic
array([2.21e+02, 7.02e-01, 1.70e+00, 9.31e-01,
       5.41e+00, 3.25e-01, 4.71e-02, 5.72e-01,
       7.54e-01, 8.90e-02])
>>> p_values
array([7.14e-27, 4.04e-01, 1.96e-01, 3.37e-01,
       2.21e-02, 5.70e-01, 8.29e-01, 4.51e-01,
       3.87e-01, 7.66e-01])
Definition at line 125 of file _univariate_selection.py.
References f_oneway().
f_oneway()
sklearn.feature_selection._univariate_selection.f_oneway (* args)
Scoring functions.
Perform a 1-way ANOVA.
The one-way ANOVA tests the null hypothesis that 2 or more groups have
the same population mean. The test is applied to samples from two or
more groups, possibly with differing sizes.
Read more in the :ref:`User Guide <univariate_feature_selection>`.
Parameters
----------
*args : {array-like, sparse matrix}
    Sample1, sample2... The sample measurements should be given as
    arguments.
Returns
-------
f_statistic : float
    The computed F-value of the test.
p_value : float
    The associated p-value from the F-distribution.
Notes
-----
The ANOVA test has important assumptions that must be satisfied in order
for the associated p-value to be valid.
1. The samples are independent
2. Each sample is from a normally distributed population
3. The population standard deviations of the groups are all equal. This
   property is known as homoscedasticity.
If these assumptions are not true for a given set of data, it may still be
possible to use the Kruskal-Wallis H-test (`scipy.stats.kruskal`_) although
with some loss of power.
The algorithm is from Heiman[2], pp.394-7.
See ``scipy.stats.f_oneway`` that should give the same results while
being less efficient.
References
----------
.. [1] Lowry, Richard.  "Concepts and Applications of Inferential
       Statistics". Chapter 14.
       http://vassarstats.net/textbook
.. [2] Heiman, G.W.  Research Methods in Statistics. 2002.
Definition at line 41 of file _univariate_selection.py.
Referenced by f_classif().
f_regression()
sklearn.feature_selection._univariate_selection.f_regression (X, y, * , center = True, force_finite = True)
Univariate linear regression tests returning F-statistic and p-values.
Quick linear model for testing the effect of a single regressor,
sequentially for many regressors.
This is done in 2 steps:
1. The cross correlation between each regressor and the target is computed
   using :func:`r_regression` as::
       E[(X[:, i] - mean(X[:, i])) * (y - mean(y))] / (std(X[:, i]) * std(y))
2. It is converted to an F score and then to a p-value.
:func:`f_regression` is derived from :func:`r_regression` and will rank
features in the same order if all the features are positively correlated
with the target.
Note however that contrary to :func:`f_regression`, :func:`r_regression`
values lie in [-1, 1] and can thus be negative. :func:`f_regression` is
therefore recommended as a feature selection criterion to identify
potentially predictive feature for a downstream classifier, irrespective of
the sign of the association with the target variable.
Furthermore :func:`f_regression` returns p-values while
:func:`r_regression` does not.
Read more in the :ref:`User Guide <univariate_feature_selection>`.
Parameters
----------
X : {array-like, sparse matrix} of shape (n_samples, n_features)
    The data matrix.
y : array-like of shape (n_samples,)
    The target vector.
center : bool, default=True
    Whether or not to center the data matrix `X` and the target vector `y`.
    By default, `X` and `y` will be centered.
force_finite : bool, default=True
    Whether or not to force the F-statistics and associated p-values to
    be finite. There are two cases where the F-statistic is expected to not
    be finite:
    - when the target `y` or some features in `X` are constant. In this
      case, the Pearson's R correlation is not defined leading to obtain
      `np.nan` values in the F-statistic and p-value. When
      `force_finite=True`, the F-statistic is set to `0.0` and the
      associated p-value is set to `1.0`.
    - when a feature in `X` is perfectly correlated (or
      anti-correlated) with the target `y`. In this case, the F-statistic
      is expected to be `np.inf`. When `force_finite=True`, the F-statistic
      is set to `np.finfo(dtype).max` and the associated p-value is set to
      `0.0`.
    .. versionadded:: 1.1
Returns
-------
f_statistic : ndarray of shape (n_features,)
    F-statistic for each feature.
p_values : ndarray of shape (n_features,)
    P-values associated with the F-statistic.
See Also
--------
r_regression: Pearson's R between label/feature for regression tasks.
f_classif: ANOVA F-value between label/feature for classification tasks.
chi2: Chi-squared stats of non-negative features for classification tasks.
SelectKBest: Select features based on the k highest scores.
SelectFpr: Select features based on a false positive rate test.
SelectFdr: Select features based on an estimated false discovery rate.
SelectFwe: Select features based on family-wise error rate.
SelectPercentile: Select features based on percentile of the highest
    scores.
Examples
--------
>>> from sklearn.datasets import make_regression
>>> from sklearn.feature_selection import f_regression
>>> X, y = make_regression(
...     n_samples=50, n_features=3, n_informative=1, noise=1e-4, random_state=42
...)
>>> f_statistic, p_values = f_regression(X, y)
>>> f_statistic
array([1.21, 2.67e13, 2.66])
>>> p_values
array([0.276, 1.54e-283, 0.11])
Definition at line 406 of file _univariate_selection.py.
References r_regression().
r_regression()
sklearn.feature_selection._univariate_selection.r_regression (X, y, * , center = True, force_finite = True)
Compute Pearson's r for each features and the target.
Pearson's r is also known as the Pearson correlation coefficient.
Linear model for testing the individual effect of each of many regressors.
This is a scoring function to be used in a feature selection procedure, not
a free standing feature selection procedure.
The cross correlation between each regressor and the target is computed
as::
    E[(X[:, i] - mean(X[:, i])) * (y - mean(y))] / (std(X[:, i]) * std(y))
For more on usage see the :ref:`User Guide <univariate_feature_selection>`.
.. versionadded:: 1.0
Parameters
----------
X : {array-like, sparse matrix} of shape (n_samples, n_features)
    The data matrix.
y : array-like of shape (n_samples,)
    The target vector.
center : bool, default=True
    Whether or not to center the data matrix `X` and the target vector `y`.
    By default, `X` and `y` will be centered.
force_finite : bool, default=True
    Whether or not to force the Pearson's R correlation to be finite.
    In the particular case where some features in `X` or the target `y`
    are constant, the Pearson's R correlation is not defined. When
    `force_finite=False`, a correlation of `np.nan` is returned to
    acknowledge this case. When `force_finite=True`, this value will be
    forced to a minimal correlation of `0.0`.
    .. versionadded:: 1.1
Returns
-------
correlation_coefficient : ndarray of shape (n_features,)
    Pearson's R correlation coefficients of features.
See Also
--------
f_regression: Univariate linear regression tests returning f-statistic
    and p-values.
mutual_info_regression: Mutual information for a continuous target.
f_classif: ANOVA F-value between label/feature for classification tasks.
chi2: Chi-squared stats of non-negative features for classification tasks.
Examples
--------
>>> from sklearn.datasets import make_regression
>>> from sklearn.feature_selection import r_regression
>>> X, y = make_regression(
...     n_samples=50, n_features=3, n_informative=1, noise=1e-4, random_state=42
...)
>>> r_regression(X, y)
array([-0.157,  1.        , -0.229])
Definition at line 301 of file _univariate_selection.py.
Referenced by f_regression().