Code Cloning Analysis: matplotlib.testing.decorators Namespace Reference
matplotlib.testing.decorators Namespace Reference
Classes
class _ImageComparisonBase
Functions
_cleanup_cm ()
_check_freetype_version (ver)
_checked_on_freetype_version (required_freetype_version)
remove_ticks_and_titles (figure)
_collect_new_figures ()
_raise_on_image_difference (expected, actual, tol)
_pytest_image_comparison (baseline_images, extensions, tol, freetype_version, remove_text, savefig_kwargs, style)
image_comparison (baseline_images, extensions=None, tol=0, freetype_version=None, remove_text=False, savefig_kwarg=None, style=("classic", "_classic_test_patch"))
check_figures_equal (*, extensions=("png", "pdf", "svg"), tol=0)
_image_directories (func)
Function Documentation
_check_freetype_version()
matplotlib.testing.decorators._check_freetype_version (ver) protected
Definition at line 34 of file decorators.py.
_checked_on_freetype_version()
matplotlib.testing.decorators._checked_on_freetype_version (required_freetype_version) protected
Definition at line 46 of file decorators.py.
_cleanup_cm()
matplotlib.testing.decorators._cleanup_cm () protected
Definition at line 23 of file decorators.py.
_collect_new_figures()
matplotlib.testing.decorators._collect_new_figures () protected
After::
    with _collect_new_figures() as figs:
        some_code()
the list *figs* contains the figures that have been created during the
execution of ``some_code``, sorted by figure number.
Definition at line 78 of file decorators.py.
Referenced by _pytest_image_comparison(), and check_figures_equal().
_image_directories()
matplotlib.testing.decorators._image_directories (func) protected
Compute the baseline and result image directories for testing *func*.
For test module ``foo.bar.test_baz``, the baseline directory is at
``foo/bar/baseline_images/test_baz`` and the result directory at
``$(pwd)/result_images/test_baz``.  The result directory is created if it
doesn't exist.
Definition at line 451 of file decorators.py.
Referenced by check_figures_equal().
_pytest_image_comparison()
matplotlib.testing.decorators._pytest_image_comparison (baseline_images, extensions, tol, freetype_version, remove_text, savefig_kwargs, style) protected
Decorate function with image comparison for pytest.
This function creates a decorator that wraps a figure-generating function
with image comparison code.
Definition at line 177 of file decorators.py.
References _collect_new_figures().
Referenced by image_comparison().
_raise_on_image_difference()
matplotlib.testing.decorators._raise_on_image_difference (expected, actual, tol) protected
Definition at line 100 of file decorators.py.
check_figures_equal()
matplotlib.testing.decorators.check_figures_equal (* , extensions = ("png", "pdf", "svg"), tol = 0)
Decorator for test cases that generate and compare two figures.
The decorated function must take two keyword arguments, *fig_test*
and *fig_ref*, and draw the test and reference images on them.
After the function returns, the figures are saved and compared.
This decorator should be preferred over `image_comparison` when possible in
order to keep the size of the test suite from ballooning.
Parameters
----------
extensions : list, default: ["png", "pdf", "svg"]
    The extensions to test.
tol : float
    The RMS threshold above which the test is considered failed.
Raises
------
RuntimeError
    If any new figures are created (and not subsequently closed) inside
    the test function.
Examples
--------
Check that calling `.Axes.plot` with a single argument plots it against
``[0, 1, 2, ...]``::
    @check_figures_equal()
    def test_plot(fig_test, fig_ref):
        fig_test.subplots().plot([1, 3, 5])
        fig_ref.subplots().plot([0, 1, 2], [1, 3, 5])
Definition at line 349 of file decorators.py.
References _collect_new_figures(), and _image_directories().
image_comparison()
matplotlib.testing.decorators.image_comparison (baseline_images, extensions = None, tol = 0, freetype_version = None, remove_text = False, savefig_kwarg = None, style = ("classic", "_classic_test_patch"))
Compare images generated by the test with those specified in
*baseline_images*, which must correspond, else an `.ImageComparisonFailure`
exception will be raised.
Parameters
----------
baseline_images : list or None
    A list of strings specifying the names of the images generated by
    calls to `.Figure.savefig`.
    If *None*, the test function must use the ``baseline_images`` fixture,
    either as a parameter or with `pytest.mark.usefixtures`. This value is
    only allowed when using pytest.
extensions : None or list of str
    The list of extensions to test, e.g. ``['png', 'pdf']``.
    If *None*, defaults to all supported extensions: png, pdf, and svg.
    When testing a single extension, it can be directly included in the
    names passed to *baseline_images*.  In that case, *extensions* must not
    be set.
    In order to keep the size of the test suite from ballooning, we only
    include the ``svg`` or ``pdf`` outputs if the test is explicitly
    exercising a feature dependent on that backend (see also the
    `check_figures_equal` decorator for that purpose).
tol : float, default: 0
    The RMS threshold above which the test is considered failed.
    Due to expected small differences in floating-point calculations, on
    32-bit systems an additional 0.06 is added to this threshold.
freetype_version : str or tuple
    The expected freetype version or range of versions for this test to
    pass.
remove_text : bool
    Remove the title and tick text from the figure before comparison.  This
    is useful to make the baseline images independent of variations in text
    rendering between different versions of FreeType.
    This does not remove other, more deliberate, text, such as legends and
    annotations.
savefig_kwarg : dict
    Optional arguments that are passed to the savefig method.
style : str, dict, or list
    The optional style(s) to apply to the image test. The test itself
    can also apply additional styles if desired. Defaults to ``["classic",
    "_classic_test_patch"]``.
Definition at line 259 of file decorators.py.
References _pytest_image_comparison().
remove_ticks_and_titles()
matplotlib.testing.decorators.remove_ticks_and_titles (figure)
Definition at line 56 of file decorators.py.