Code Cloning Analysis: scipy.signal._filter_design Namespace Reference
scipy.signal._filter_design Namespace Reference
Classes
class BadCoefficients
Functions
_is_int_type (x)
findfreqs (num, den, N, kind='ba')
freqs (b, a, worN=200, plot=None)
freqs_zpk (z, p, k, worN=200)
freqz (b, a=1, worN=512, whole=False, plot=None, fs=2 *pi, include_nyquist=False)
freqz_zpk (z, p, k, worN=512, whole=False, fs=2 *pi)
group_delay (system, w=512, whole=False, fs=2 *pi)
_validate_sos (sos)
sosfreqz (sos, worN=512, whole=False, fs=2 *pi)
_cplxreal (z, tol=None)
_cplxpair (z, tol=None)
tf2zpk (b, a)
zpk2tf (z, p, k)
tf2sos (b, a, pairing=None, *, analog=False)
sos2tf (sos)
sos2zpk (sos)
_nearest_real_complex_idx (fro, to, which)
_single_zpksos (z, p, k)
zpk2sos (z, p, k, pairing=None, *, analog=False)
_align_nums (nums)
normalize (b, a)
lp2lp (b, a, wo=1.0)
lp2hp (b, a, wo=1.0)
lp2bp (b, a, wo=1.0, bw=1.0)
lp2bs (b, a, wo=1.0, bw=1.0)
bilinear (b, a, fs=1.0)
_validate_gpass_gstop (gpass, gstop)
iirdesign (wp, ws, gpass, gstop, analog=False, ftype='ellip', output='ba', fs=None)
iirfilter (N, Wn, rp=None, rs=None, btype='band', analog=False, ftype='butter', output='ba', fs=None)
_relative_degree (z, p)
bilinear_zpk (z, p, k, fs)
lp2lp_zpk (z, p, k, wo=1.0)
lp2hp_zpk (z, p, k, wo=1.0)
lp2bp_zpk (z, p, k, wo=1.0, bw=1.0)
lp2bs_zpk (z, p, k, wo=1.0, bw=1.0)
butter (N, Wn, btype='low', analog=False, output='ba', fs=None)
cheby1 (N, rp, Wn, btype='low', analog=False, output='ba', fs=None)
cheby2 (N, rs, Wn, btype='low', analog=False, output='ba', fs=None)
ellip (N, rp, rs, Wn, btype='low', analog=False, output='ba', fs=None)
bessel (N, Wn, btype='low', analog=False, output='ba', norm='phase', fs=None)
maxflat ()
yulewalk ()
band_stop_obj (wp, ind, passb, stopb, gpass, gstop, type)
buttord (wp, ws, gpass, gstop, analog=False, fs=None)
cheb1ord (wp, ws, gpass, gstop, analog=False, fs=None)
cheb2ord (wp, ws, gpass, gstop, analog=False, fs=None)
_pow10m1 (x)
ellipord (wp, ws, gpass, gstop, analog=False, fs=None)
buttap (N)
cheb1ap (N, rp)
cheb2ap (N, rs)
_ellipdeg (n, m1)
_arc_jac_sn (w, m)
_arc_jac_sc1 (w, m)
ellipap (N, rp, rs)
_falling_factorial (x, n)
_bessel_poly (n, reverse=False)
_campos_zeros (n)
_aberth (f, fp, x0, tol=1e-15, maxiter=50)
_bessel_zeros (N)
_norm_factor (p, k)
besselap (N, norm='phase')
iirnotch (w0, Q, fs=2.0)
iirpeak (w0, Q, fs=2.0)
_design_notch_peak_filter (w0, Q, ftype, fs=2.0)
iircomb (w0, Q, ftype='notch', fs=2.0, *, pass_zero=False)
_hz_to_erb (hz)
gammatone (freq, ftype, order=None, numtaps=None, fs=None)
Variables
list __all__
abs = absolute
_POW10_LOG10 = np.log(10)
int EPSILON = 2e-16
int _ELLIPDEG_MMAX = 7
int _ARC_JAC_SN_MAXITER = 10
dict filter_dict
dict band_dict
dict bessel_norms
Detailed Description
Filter design.
Function Documentation
_aberth()
scipy.signal._filter_design._aberth (f, fp, x0, tol = 1e-15, maxiter = 50) protected
Given a function `f`, its first derivative `fp`, and a set of initial
guesses `x0`, simultaneously find the roots of the polynomial using the
Aberth-Ehrlich method.
``len(x0)`` should equal the number of roots of `f`.
(This is not a complete implementation of Bini's algorithm.)
Definition at line 4723 of file _filter_design.py.
Referenced by _bessel_zeros().
_align_nums()
scipy.signal._filter_design._align_nums (nums) protected
Aligns the shapes of multiple numerators.
Given an array of numerator coefficient arrays [[a_1, a_2,...,
a_n],..., [b_1, b_2,..., b_m]], this function pads shorter numerator
arrays with zero's so that all numerators have the same length. Such
alignment is necessary for functions like 'tf2ss', which needs the
alignment when dealing with SIMO transfer functions.
Parameters
----------
nums: array_like
    Numerator or list of numerators. Not necessarily with same length.
Returns
-------
nums: array
    The numerator. If `nums` input was a list of numerators then a 2-D
    array with padded zeros for shorter numerators is returned. Otherwise
    returns ``np.asarray(nums)``.
Definition at line 1615 of file _filter_design.py.
Referenced by normalize().
_arc_jac_sc1()
scipy.signal._filter_design._arc_jac_sc1 (w, m) protected
Real inverse Jacobian sc, with complementary modulus
Solve for z in w = sc(z, 1-m)
w - real scalar
m - modulus
From [1], sc(z, m) = -i * sn(i * z, 1 - m)
References
----------
# noqa: E501
.. [1] https://functions.wolfram.com/EllipticFunctions/JacobiSC/introductions/JacobiPQs/ShowAll.html,
   "Representations through other Jacobi functions"
Definition at line 4524 of file _filter_design.py.
References _arc_jac_sn().
Referenced by ellipap().
_arc_jac_sn()
scipy.signal._filter_design._arc_jac_sn (w, m) protected
Inverse Jacobian elliptic sn
Solve for z in w = sn(z, m)
Parameters
----------
w : complex scalar
    argument
m : scalar
    modulus; in interval [0, 1]
See [1], Eq. (56)
References
----------
.. [1] Orfanidis, "Lecture Notes on Elliptic Filter Design",
       https://www.ece.rutgers.edu/~orfanidi/ece521/notes.pdf
Definition at line 4463 of file _filter_design.py.
Referenced by _arc_jac_sc1().
_bessel_poly()
scipy.signal._filter_design._bessel_poly (n, reverse = False) protected
Return the coefficients of Bessel polynomial of degree `n`
If `reverse` is true, a reverse Bessel polynomial is output.
Output is a list of coefficients:
[1]                   = 1
[1,  1]               = 1*s   +  1
[1,  3,  3]           = 1*s^2 +  3*s   +  3
[1,  6, 15, 15]       = 1*s^3 +  6*s^2 + 15*s   +  15
[1, 10, 45, 105, 105] = 1*s^4 + 10*s^3 + 45*s^2 + 105*s + 105
etc.
Output is a Python list of arbitrary precision long ints, so n is only
limited by your hardware's memory.
Sequence is http://oeis.org/A001498, and output can be confirmed to
match http://oeis.org/A001498/b001498.txt :
>>> i = 0
>>> for n in range(51):
...     for x in _bessel_poly(n, reverse=True):
...         print(i, x)
...         i += 1
Definition at line 4654 of file _filter_design.py.
References _falling_factorial().
_bessel_zeros()
scipy.signal._filter_design._bessel_zeros (N) protected
Find zeros of ordinary Bessel polynomial of order `N`, by root-finding of
modified Bessel function of the second kind
Definition at line 4762 of file _filter_design.py.
References _aberth(), and _campos_zeros().
Referenced by besselap().
_campos_zeros()
scipy.signal._filter_design._campos_zeros (n) protected
Return approximate zero locations of Bessel polynomials y_n(x) for order
`n` using polynomial fit (Campos-Calderon 2011)
Definition at line 4698 of file _filter_design.py.
Referenced by _bessel_zeros().
_cplxpair()
scipy.signal._filter_design._cplxpair (z, tol = None) protected
Sort into pairs of complex conjugates.
Complex conjugates in `z` are sorted by increasing real part. In each
pair, the number with negative imaginary part appears first.
If pairs have identical real parts, they are sorted by increasing
imaginary magnitude.
Two complex numbers are considered a conjugate pair if their real and
imaginary parts differ in magnitude by less than ``tol * abs(z)``.  The
pairs are forced to be exact complex conjugates by averaging the positive
and negative values.
Purely real numbers are also sorted, but placed after the complex
conjugate pairs. A number is considered real if its imaginary part is
smaller than `tol` times the magnitude of the number.
Parameters
----------
z : array_like
    1-D input array to be sorted.
tol : float, optional
    Relative tolerance for testing realness and conjugate equality.
    Default is ``100 * spacing(1)`` of `z`'s data type (i.e., 2e-14 for
    float64)
Returns
-------
y : ndarray
    Complex conjugate pairs followed by real numbers.
Raises
------
ValueError
    If there are any complex numbers in `z` for which a conjugate
    cannot be found.
See Also
--------
_cplxreal
Examples
--------
>>> a = [4, 3, 1, 2-2j, 2+2j, 2-1j, 2+1j, 2-1j, 2+1j, 1+1j, 1-1j]
>>> z = _cplxpair(a)
>>> print(z)
[ 1.-1.j  1.+1.j  2.-1.j  2.+1.j  2.-1.j  2.+1.j  2.-2.j  2.+2.j  1.+0.j
  3.+0.j  4.+0.j]
Definition at line 958 of file _filter_design.py.
References _cplxreal().
_cplxreal()
scipy.signal._filter_design._cplxreal (z, tol = None) protected
Split into complex and real parts, combining conjugate pairs.
The 1-D input vector `z` is split up into its complex (`zc`) and real (`zr`)
elements. Every complex element must be part of a complex-conjugate pair,
which are combined into a single number (with positive imaginary part) in
the output. Two complex numbers are considered a conjugate pair if their
real and imaginary parts differ in magnitude by less than ``tol * abs(z)``.
Parameters
----------
z : array_like
    Vector of complex numbers to be sorted and split
tol : float, optional
    Relative tolerance for testing realness and conjugate equality.
    Default is ``100 * spacing(1)`` of `z`'s data type (i.e., 2e-14 for
    float64)
Returns
-------
zc : ndarray
    Complex elements of `z`, with each pair represented by a single value
    having positive imaginary part, sorted first by real part, and then
    by magnitude of imaginary part. The pairs are averaged when combined
    to reduce error.
zr : ndarray
    Real elements of `z` (those having imaginary part less than
    `tol` times their magnitude), sorted by value.
Raises
------
ValueError
    If there are any complex numbers in `z` for which a conjugate
    cannot be found.
See Also
--------
_cplxpair
Examples
--------
>>> a = [4, 3, 1, 2-2j, 2+2j, 2-1j, 2+1j, 2-1j, 2+1j, 1+1j, 1-1j]
>>> zc, zr = _cplxreal(a)
>>> print(zc)
[ 1.+1.j  2.+1.j  2.+1.j  2.+2.j]
>>> print(zr)
[ 1.  3.  4.]
Definition at line 854 of file _filter_design.py.
Referenced by _cplxpair(), and zpk2sos().
_design_notch_peak_filter()
scipy.signal._filter_design._design_notch_peak_filter (w0, Q, ftype, fs = 2.0) protected
Design notch or peak digital filter.
Parameters
----------
w0 : float
    Normalized frequency to remove from a signal. If `fs` is specified,
    this is in the same units as `fs`. By default, it is a normalized
    scalar that must satisfy  ``0 < w0 < 1``, with ``w0 = 1``
    corresponding to half of the sampling frequency.
Q : float
    Quality factor. Dimensionless parameter that characterizes
    notch filter -3 dB bandwidth ``bw`` relative to its center
    frequency, ``Q = w0/bw``.
ftype : str
    The type of IIR filter to design:
        - notch filter : ``notch``
        - peak filter  : ``peak``
fs : float, optional
    The sampling frequency of the digital system.
    .. versionadded:: 1.2.0:
Returns
-------
b, a : ndarray, ndarray
    Numerator (``b``) and denominator (``a``) polynomials
    of the IIR filter.
Definition at line 5099 of file _filter_design.py.
Referenced by iirnotch(), and iirpeak().
_ellipdeg()
scipy.signal._filter_design._ellipdeg (n, m1) protected
Solve degree equation using nomes
Given n, m1, solve
   n * K(m) / K'(m) = K1(m1) / K1'(m1)
for m
See [1], Eq. (49)
References
----------
.. [1] Orfanidis, "Lecture Notes on Elliptic Filter Design",
       https://www.ece.rutgers.edu/~orfanidi/ece521/notes.pdf
Definition at line 4428 of file _filter_design.py.
Referenced by ellipap().
_falling_factorial()
scipy.signal._filter_design._falling_factorial (x, n) protected
Return the factorial of `x` to the `n` falling.
This is defined as:
.. math::   x^\underline n = (x)_n = x (x-1) \cdots (x-n+1)
This can more efficiently calculate ratios of factorials, since:
n!/m! == falling_factorial(n, n-m)
where n >= m
skipping the factors that cancel out
the usual factorial n! == ff(n, n)
Definition at line 4630 of file _filter_design.py.
Referenced by _bessel_poly(), and besselap().
_hz_to_erb()
scipy.signal._filter_design._hz_to_erb (hz) protected
Utility for converting from frequency (Hz) to the
Equivalent Rectangular Bandwidth (ERB) scale
ERB = frequency / EarQ + minBW
Definition at line 5382 of file _filter_design.py.
Referenced by gammatone().
_is_int_type()
scipy.signal._filter_design._is_int_type (x) protected
Check if input is of a scalar integer type (so ``5`` and ``array(5)`` will
pass, while ``5.0`` and ``array([5])`` will fail.
Definition at line 41 of file _filter_design.py.
Referenced by freqs(), freqs_zpk(), freqz(), freqz_zpk(), and group_delay().
_nearest_real_complex_idx()
scipy.signal._filter_design._nearest_real_complex_idx (fro, to, which) protected
Get the next closest real or complex element based on distance
Definition at line 1275 of file _filter_design.py.
Referenced by zpk2sos().
_norm_factor()
scipy.signal._filter_design._norm_factor (p, k) protected
Numerically find frequency shift to apply to delay-normalized filter such
that -3 dB point is at 1 rad/sec.
`p` is an array_like of polynomial poles
`k` is a float gain
First 10 values are listed in "Bessel Scale Factors" table,
"Bessel Filters Polynomials, Poles and Circuit Elements 2003, C. Bond."
Definition at line 4801 of file _filter_design.py.
Referenced by besselap().
_pow10m1()
scipy.signal._filter_design._pow10m1 (x) protected
10 ** x - 1 for x near 0
Definition at line 4176 of file _filter_design.py.
Referenced by ellipap(), and ellipord().
_relative_degree()
scipy.signal._filter_design._relative_degree (z, p) protected
Return relative degree of transfer function from zeros and poles
Definition at line 2601 of file _filter_design.py.
Referenced by bilinear_zpk(), lp2bp_zpk(), lp2bs_zpk(), lp2hp_zpk(), and lp2lp_zpk().
_single_zpksos()
scipy.signal._filter_design._single_zpksos (z, p, k) protected
Create one second-order section from up to two zeros and poles
Definition at line 1288 of file _filter_design.py.
References zpk2tf().
Referenced by zpk2sos().
_validate_gpass_gstop()
scipy.signal._filter_design._validate_gpass_gstop (gpass, gstop) protected
Definition at line 2178 of file _filter_design.py.
_validate_sos()
scipy.signal._filter_design._validate_sos (sos) protected
Helper to validate a SOS input
Definition at line 718 of file _filter_design.py.
Referenced by scipy.signal._signaltools.sosfilt(), scipy.signal._signaltools.sosfiltfilt(), and sosfreqz().
band_stop_obj()
scipy.signal._filter_design.band_stop_obj (wp, ind, passb, stopb, gpass, gstop, type)
Band Stop Objective Function for order minimization.
Returns the non-integer order for an analog band stop filter.
Parameters
----------
wp : scalar
    Edge of passband `passb`.
ind : int, {0, 1}
    Index specifying which `passb` edge to vary (0 or 1).
passb : ndarray
    Two element sequence of fixed passband edges.
stopb : ndarray
    Two element sequence of fixed stopband edges.
gstop : float
    Amount of attenuation in stopband in dB.
gpass : float
    Amount of ripple in the passband in dB.
type : {'butter', 'cheby', 'ellip'}
    Type of filter.
Returns
-------
n : scalar
    Filter order (possibly non-integer).
Definition at line 3631 of file _filter_design.py.
bessel()
scipy.signal._filter_design.bessel (N, Wn, btype = 'low', analog = False, output = 'ba', norm = 'phase', fs = None)
Bessel/Thomson digital and analog filter design.
Design an Nth-order digital or analog Bessel filter and return the
filter coefficients.
Parameters
----------
N : int
    The order of the filter.
Wn : array_like
    A scalar or length-2 sequence giving the critical frequencies (defined
    by the `norm` parameter).
    For analog filters, `Wn` is an angular frequency (e.g., rad/s).
    For digital filters, `Wn` are in the same units as `fs`.  By default,
    `fs` is 2 half-cycles/sample, so these are normalized from 0 to 1,
    where 1 is the Nyquist frequency. (`Wn` is thus in
    half-cycles / sample.)
btype : {'lowpass', 'highpass', 'bandpass', 'bandstop'}, optional
    The type of filter.  Default is 'lowpass'.
analog : bool, optional
    When True, return an analog filter, otherwise a digital filter is
    returned. (See Notes.)
output : {'ba', 'zpk', 'sos'}, optional
    Type of output:  numerator/denominator ('ba'), pole-zero ('zpk'), or
    second-order sections ('sos'). Default is 'ba'.
norm : {'phase', 'delay', 'mag'}, optional
    Critical frequency normalization:
    ``phase``
        The filter is normalized such that the phase response reaches its
        midpoint at angular (e.g. rad/s) frequency `Wn`. This happens for
        both low-pass and high-pass filters, so this is the
        "phase-matched" case.
        The magnitude response asymptotes are the same as a Butterworth
        filter of the same order with a cutoff of `Wn`.
        This is the default, and matches MATLAB's implementation.
    ``delay``
        The filter is normalized such that the group delay in the passband
        is 1/`Wn` (e.g., seconds). This is the "natural" type obtained by
        solving Bessel polynomials.
    ``mag``
        The filter is normalized such that the gain magnitude is -3 dB at
        angular frequency `Wn`.
    .. versionadded:: 0.18.0
fs : float, optional
    The sampling frequency of the digital system.
    .. versionadded:: 1.2.0
Returns
-------
b, a : ndarray, ndarray
    Numerator (`b`) and denominator (`a`) polynomials of the IIR filter.
    Only returned if ``output='ba'``.
z, p, k : ndarray, ndarray, float
    Zeros, poles, and system gain of the IIR filter transfer
    function.  Only returned if ``output='zpk'``.
sos : ndarray
    Second-order sections representation of the IIR filter.
    Only returned if ``output='sos'``.
Notes
-----
Also known as a Thomson filter, the analog Bessel filter has maximally
flat group delay and maximally linear phase response, with very little
ringing in the step response. [1]_
The Bessel is inherently an analog filter. This function generates digital
Bessel filters using the bilinear transform, which does not preserve the
phase response of the analog filter. As such, it is only approximately
correct at frequencies below about fs/4. To get maximally-flat group
delay at higher frequencies, the analog Bessel filter must be transformed
using phase-preserving techniques.
See `besselap` for implementation details and references.
The ``'sos'`` output parameter was added in 0.16.0.
References
----------
.. [1] Thomson, W.E., "Delay Networks having Maximally Flat Frequency
       Characteristics", Proceedings of the Institution of Electrical
       Engineers, Part III, November 1949, Vol. 96, No. 44, pp. 487-490.
Examples
--------
Plot the phase-normalized frequency response, showing the relationship
to the Butterworth's cutoff frequency (green):
>>> from scipy import signal
>>> import matplotlib.pyplot as plt
>>> import numpy as np
>>> b, a = signal.butter(4, 100, 'low', analog=True)
>>> w, h = signal.freqs(b, a)
>>> plt.semilogx(w, 20 * np.log10(np.abs(h)), color='silver', ls='dashed')
>>> b, a = signal.bessel(4, 100, 'low', analog=True, norm='phase')
>>> w, h = signal.freqs(b, a)
>>> plt.semilogx(w, 20 * np.log10(np.abs(h)))
>>> plt.title('Bessel filter magnitude response (with Butterworth)')
>>> plt.xlabel('Frequency [radians / second]')
>>> plt.ylabel('Amplitude [dB]')
>>> plt.margins(0, 0.1)
>>> plt.grid(which='both', axis='both')
>>> plt.axvline(100, color='green')  # cutoff frequency
>>> plt.show()
and the phase midpoint:
>>> plt.figure()
>>> plt.semilogx(w, np.unwrap(np.angle(h)))
>>> plt.axvline(100, color='green')  # cutoff frequency
>>> plt.axhline(-np.pi, color='red')  # phase midpoint
>>> plt.title('Bessel filter phase response')
>>> plt.xlabel('Frequency [radians / second]')
>>> plt.ylabel('Phase [radians]')
>>> plt.margins(0, 0.1)
>>> plt.grid(which='both', axis='both')
>>> plt.show()
Plot the magnitude-normalized frequency response, showing the -3 dB cutoff:
>>> b, a = signal.bessel(3, 10, 'low', analog=True, norm='mag')
>>> w, h = signal.freqs(b, a)
>>> plt.semilogx(w, 20 * np.log10(np.abs(h)))
>>> plt.axhline(-3, color='red')  # -3 dB magnitude
>>> plt.axvline(10, color='green')  # cutoff frequency
>>> plt.title('Magnitude-normalized Bessel filter frequency response')
>>> plt.xlabel('Frequency [radians / second]')
>>> plt.ylabel('Amplitude [dB]')
>>> plt.margins(0, 0.1)
>>> plt.grid(which='both', axis='both')
>>> plt.show()
Plot the delay-normalized filter, showing the maximally-flat group delay
at 0.1 seconds:
>>> b, a = signal.bessel(5, 1/0.1, 'low', analog=True, norm='delay')
>>> w, h = signal.freqs(b, a)
>>> plt.figure()
>>> plt.semilogx(w[1:], -np.diff(np.unwrap(np.angle(h)))/np.diff(w))
>>> plt.axhline(0.1, color='red')  # 0.1 seconds group delay
>>> plt.title('Bessel filter group delay')
>>> plt.xlabel('Frequency [radians / second]')
>>> plt.ylabel('Group delay [seconds]')
>>> plt.margins(0, 0.1)
>>> plt.grid(which='both', axis='both')
>>> plt.show()
Definition at line 3460 of file _filter_design.py.
References iirfilter().
besselap()
scipy.signal._filter_design.besselap (N, norm = 'phase')
Return (z,p,k) for analog prototype of an Nth-order Bessel filter.
Parameters
----------
N : int
    The order of the filter.
norm : {'phase', 'delay', 'mag'}, optional
    Frequency normalization:
    ``phase``
        The filter is normalized such that the phase response reaches its
        midpoint at an angular (e.g., rad/s) cutoff frequency of 1. This
        happens for both low-pass and high-pass filters, so this is the
        "phase-matched" case. [6]_
        The magnitude response asymptotes are the same as a Butterworth
        filter of the same order with a cutoff of `Wn`.
        This is the default, and matches MATLAB's implementation.
    ``delay``
        The filter is normalized such that the group delay in the passband
        is 1 (e.g., 1 second). This is the "natural" type obtained by
        solving Bessel polynomials
    ``mag``
        The filter is normalized such that the gain magnitude is -3 dB at
        angular frequency 1. This is called "frequency normalization" by
        Bond. [1]_
    .. versionadded:: 0.18.0
Returns
-------
z : ndarray
    Zeros of the transfer function. Is always an empty array.
p : ndarray
    Poles of the transfer function.
k : scalar
    Gain of the transfer function. For phase-normalized, this is always 1.
See Also
--------
bessel : Filter design function using this prototype
Notes
-----
To find the pole locations, approximate starting points are generated [2]_
for the zeros of the ordinary Bessel polynomial [3]_, then the
Aberth-Ehrlich method [4]_ [5]_ is used on the Kv(x) Bessel function to
calculate more accurate zeros, and these locations are then inverted about
the unit circle.
References
----------
.. [1] C.R. Bond, "Bessel Filter Constants",
       http://www.crbond.com/papers/bsf.pdf
.. [2] Campos and Calderon, "Approximate closed-form formulas for the
       zeros of the Bessel Polynomials", :arXiv:`1105.0957`.
.. [3] Thomson, W.E., "Delay Networks having Maximally Flat Frequency
       Characteristics", Proceedings of the Institution of Electrical
       Engineers, Part III, November 1949, Vol. 96, No. 44, pp. 487-490.
.. [4] Aberth, "Iteration Methods for Finding all Zeros of a Polynomial
       Simultaneously", Mathematics of Computation, Vol. 27, No. 122,
       April 1973
.. [5] Ehrlich, "A modified Newton method for polynomials", Communications
       of the ACM, Vol. 10, Issue 2, pp. 107-108, Feb. 1967,
       :DOI:`10.1145/363067.363115`
.. [6] Miller and Bohn, "A Bessel Filter Crossover, and Its Relation to
       Others", RaneNote 147, 1998,
       https://www.ranecommercial.com/legacy/note147.html
Definition at line 4829 of file _filter_design.py.
References _bessel_zeros(), _falling_factorial(), and _norm_factor().
bilinear()
scipy.signal._filter_design.bilinear (b, a, fs = 1.0)
Return a digital IIR filter from an analog one using a bilinear transform.
Transform a set of poles and zeros from the analog s-plane to the digital
z-plane using Tustin's method, which substitutes ``2*fs*(z-1) / (z+1)`` for
``s``, maintaining the shape of the frequency response.
Parameters
----------
b : array_like
Numerator of the analog filter transfer function.
a : array_like
Denominator of the analog filter transfer function.
fs : float
Sample rate, as ordinary frequency (e.g., hertz). No prewarping is
done in this function.
Returns
-------
b : ndarray
Numerator of the transformed digital filter transfer function.
a : ndarray
Denominator of the transformed digital filter transfer function.
See Also
--------
lp2lp, lp2hp, lp2bp, lp2bs
bilinear_zpk
Examples
--------
>>> from scipy import signal
>>> import matplotlib.pyplot as plt
>>> import numpy as np
>>> fs = 100
>>> bf = 2 * np.pi * np.array([7, 13])
>>> filts = signal.lti(*signal.butter(4, bf, btype='bandpass',
...                                   analog=True))
>>> filtz = signal.lti(*signal.bilinear(filts.num, filts.den, fs))
>>> wz, hz = signal.freqz(filtz.num, filtz.den)
>>> ws, hs = signal.freqs(filts.num, filts.den, worN=fs*wz)
>>> plt.semilogx(wz*fs/(2*np.pi), 20*np.log10(np.abs(hz).clip(1e-15)),
...              label=r'$|H_z(e^{j \omega})|$')
>>> plt.semilogx(wz*fs/(2*np.pi), 20*np.log10(np.abs(hs).clip(1e-15)),
...              label=r'$|H(j \omega)|$')
>>> plt.legend()
>>> plt.xlabel('Frequency [Hz]')
>>> plt.ylabel('Magnitude [dB]')
>>> plt.grid(True)
Definition at line 2093 of file _filter_design.py.
References normalize().
bilinear_zpk()
scipy.signal._filter_design.bilinear_zpk (z, p, k, fs)
Return a digital IIR filter from an analog one using a bilinear transform.
Transform a set of poles and zeros from the analog s-plane to the digital
z-plane using Tustin's method, which substitutes ``2*fs*(z-1) / (z+1)`` for
``s``, maintaining the shape of the frequency response.
Parameters
----------
z : array_like
Zeros of the analog filter transfer function.
p : array_like
Poles of the analog filter transfer function.
k : float
System gain of the analog filter transfer function.
fs : float
Sample rate, as ordinary frequency (e.g., hertz). No prewarping is
done in this function.
Returns
-------
z : ndarray
Zeros of the transformed digital filter transfer function.
p : ndarray
Poles of the transformed digital filter transfer function.
k : float
System gain of the transformed digital filter.
See Also
--------
lp2lp_zpk, lp2hp_zpk, lp2bp_zpk, lp2bs_zpk
bilinear
Notes
-----
.. versionadded:: 1.1.0
Examples
--------
>>> import numpy as np
>>> from scipy import signal
>>> import matplotlib.pyplot as plt
>>> fs = 100
>>> bf = 2 * np.pi * np.array([7, 13])
>>> filts = signal.lti(*signal.butter(4, bf, btype='bandpass', analog=True,
...                                   output='zpk'))
>>> filtz = signal.lti(*signal.bilinear_zpk(filts.zeros, filts.poles,
...                                         filts.gain, fs))
>>> wz, hz = signal.freqz_zpk(filtz.zeros, filtz.poles, filtz.gain)
>>> ws, hs = signal.freqs_zpk(filts.zeros, filts.poles, filts.gain,
...                           worN=fs*wz)
>>> plt.semilogx(wz*fs/(2*np.pi), 20*np.log10(np.abs(hz).clip(1e-15)),
...              label=r'$|H_z(e^{j \omega})|$')
>>> plt.semilogx(wz*fs/(2*np.pi), 20*np.log10(np.abs(hs).clip(1e-15)),
...              label=r'$|H(j \omega)|$')
>>> plt.legend()
>>> plt.xlabel('Frequency [Hz]')
>>> plt.ylabel('Magnitude [dB]')
>>> plt.grid(True)
Definition at line 2613 of file _filter_design.py.
References _relative_degree().
Referenced by iirfilter().
buttap()
scipy.signal._filter_design.buttap (N)
Return (z,p,k) for analog prototype of Nth-order Butterworth filter.
The filter will have an angular (e.g., rad/s) cutoff frequency of 1.
See Also
--------
butter : Filter design function using this prototype
Definition at line 4322 of file _filter_design.py.
butter()
scipy.signal._filter_design.butter (N, Wn, btype = 'low', analog = False, output = 'ba', fs = None)
Butterworth digital and analog filter design.
Design an Nth-order digital or analog Butterworth filter and return
the filter coefficients.
Parameters
----------
N : int
    The order of the filter. For 'bandpass' and 'bandstop' filters,
    the resulting order of the final second-order sections ('sos')
    matrix is ``2*N``, with `N` the number of biquad sections
    of the desired system.
Wn : array_like
    The critical frequency or frequencies. For lowpass and highpass
    filters, Wn is a scalar; for bandpass and bandstop filters,
    Wn is a length-2 sequence.
    For a Butterworth filter, this is the point at which the gain
    drops to 1/sqrt(2) that of the passband (the "-3 dB point").
    For digital filters, if `fs` is not specified, `Wn` units are
    normalized from 0 to 1, where 1 is the Nyquist frequency (`Wn` is
    thus in half cycles / sample and defined as 2*critical frequencies
    / `fs`). If `fs` is specified, `Wn` is in the same units as `fs`.
    For analog filters, `Wn` is an angular frequency (e.g. rad/s).
btype : {'lowpass', 'highpass', 'bandpass', 'bandstop'}, optional
    The type of filter.  Default is 'lowpass'.
analog : bool, optional
    When True, return an analog filter, otherwise a digital filter is
    returned.
output : {'ba', 'zpk', 'sos'}, optional
    Type of output:  numerator/denominator ('ba'), pole-zero ('zpk'), or
    second-order sections ('sos'). Default is 'ba' for backwards
    compatibility, but 'sos' should be used for general-purpose filtering.
fs : float, optional
    The sampling frequency of the digital system.
    .. versionadded:: 1.2.0
Returns
-------
b, a : ndarray, ndarray
    Numerator (`b`) and denominator (`a`) polynomials of the IIR filter.
    Only returned if ``output='ba'``.
z, p, k : ndarray, ndarray, float
    Zeros, poles, and system gain of the IIR filter transfer
    function.  Only returned if ``output='zpk'``.
sos : ndarray
    Second-order sections representation of the IIR filter.
    Only returned if ``output='sos'``.
See Also
--------
buttord, buttap
Notes
-----
The Butterworth filter has maximally flat frequency response in the
passband.
The ``'sos'`` output parameter was added in 0.16.0.
If the transfer function form ``[b, a]`` is requested, numerical
problems can occur since the conversion between roots and
the polynomial coefficients is a numerically sensitive operation,
even for N >= 4. It is recommended to work with the SOS
representation.
.. warning::
    Designing high-order and narrowband IIR filters in TF form can
    result in unstable or incorrect filtering due to floating point
    numerical precision issues. Consider inspecting output filter
    characteristics `freqz` or designing the filters with second-order
    sections via ``output='sos'``.
Examples
--------
Design an analog filter and plot its frequency response, showing the
critical points:
>>> from scipy import signal
>>> import matplotlib.pyplot as plt
>>> import numpy as np
>>> b, a = signal.butter(4, 100, 'low', analog=True)
>>> w, h = signal.freqs(b, a)
>>> plt.semilogx(w, 20 * np.log10(abs(h)))
>>> plt.title('Butterworth filter frequency response')
>>> plt.xlabel('Frequency [radians / second]')
>>> plt.ylabel('Amplitude [dB]')
>>> plt.margins(0, 0.1)
>>> plt.grid(which='both', axis='both')
>>> plt.axvline(100, color='green') # cutoff frequency
>>> plt.show()
Generate a signal made up of 10 Hz and 20 Hz, sampled at 1 kHz
>>> t = np.linspace(0, 1, 1000, False)  # 1 second
>>> sig = np.sin(2*np.pi*10*t) + np.sin(2*np.pi*20*t)
>>> fig, (ax1, ax2) = plt.subplots(2, 1, sharex=True)
>>> ax1.plot(t, sig)
>>> ax1.set_title('10 Hz and 20 Hz sinusoids')
>>> ax1.axis([0, 1, -2, 2])
Design a digital high-pass filter at 15 Hz to remove the 10 Hz tone, and
apply it to the signal. (It's recommended to use second-order sections
format when filtering, to avoid numerical error with transfer function
(``ba``) format):
>>> sos = signal.butter(10, 15, 'hp', fs=1000, output='sos')
>>> filtered = signal.sosfilt(sos, sig)
>>> ax2.plot(t, filtered)
>>> ax2.set_title('After 15 Hz high-pass filter')
>>> ax2.axis([0, 1, -2, 2])
>>> ax2.set_xlabel('Time [seconds]')
>>> plt.tight_layout()
>>> plt.show()
Definition at line 2980 of file _filter_design.py.
References iirfilter().
Referenced by scipy.signal.tests.test_filter_design.TestSos2Zpk.test_fewer_zeros().
buttord()
scipy.signal._filter_design.buttord (wp, ws, gpass, gstop, analog = False, fs = None)
Butterworth filter order selection.
Return the order of the lowest order digital or analog Butterworth filter
that loses no more than `gpass` dB in the passband and has at least
`gstop` dB attenuation in the stopband.
Parameters
----------
wp, ws : float
    Passband and stopband edge frequencies.
    For digital filters, these are in the same units as `fs`. By default,
    `fs` is 2 half-cycles/sample, so these are normalized from 0 to 1,
    where 1 is the Nyquist frequency. (`wp` and `ws` are thus in
    half-cycles / sample.) For example:
        - Lowpass:   wp = 0.2,          ws = 0.3
        - Highpass:  wp = 0.3,          ws = 0.2
        - Bandpass:  wp = [0.2, 0.5],   ws = [0.1, 0.6]
        - Bandstop:  wp = [0.1, 0.6],   ws = [0.2, 0.5]
    For analog filters, `wp` and `ws` are angular frequencies (e.g., rad/s).
gpass : float
    The maximum loss in the passband (dB).
gstop : float
    The minimum attenuation in the stopband (dB).
analog : bool, optional
    When True, return an analog filter, otherwise a digital filter is
    returned.
fs : float, optional
    The sampling frequency of the digital system.
    .. versionadded:: 1.2.0
Returns
-------
ord : int
    The lowest order for a Butterworth filter which meets specs.
wn : ndarray or float
    The Butterworth natural frequency (i.e. the "3dB frequency"). Should
    be used with `butter` to give filter results. If `fs` is specified,
    this is in the same units, and `fs` must also be passed to `butter`.
See Also
--------
butter : Filter design using order and critical points
cheb1ord : Find order and critical points from passband and stopband spec
cheb2ord, ellipord
iirfilter : General filter design using order and critical frequencies
iirdesign : General filter design using passband and stopband spec
Examples
--------
Design an analog bandpass filter with passband within 3 dB from 20 to
50 rad/s, while rejecting at least -40 dB below 14 and above 60 rad/s.
Plot its frequency response, showing the passband and stopband
constraints in gray.
>>> from scipy import signal
>>> import matplotlib.pyplot as plt
>>> import numpy as np
>>> N, Wn = signal.buttord([20, 50], [14, 60], 3, 40, True)
>>> b, a = signal.butter(N, Wn, 'band', True)
>>> w, h = signal.freqs(b, a, np.logspace(1, 2, 500))
>>> plt.semilogx(w, 20 * np.log10(abs(h)))
>>> plt.title('Butterworth bandpass filter fit to constraints')
>>> plt.xlabel('Frequency [radians / second]')
>>> plt.ylabel('Amplitude [dB]')
>>> plt.grid(which='both', axis='both')
>>> plt.fill([1,  14,  14,   1], [-40, -40, 99, 99], '0.9', lw=0) # stop
>>> plt.fill([20, 20,  50,  50], [-99, -3, -3, -99], '0.9', lw=0) # pass
>>> plt.fill([60, 60, 1e9, 1e9], [99, -40, -40, 99], '0.9', lw=0) # stop
>>> plt.axis([10, 100, -60, 3])
>>> plt.show()
Definition at line 3690 of file _filter_design.py.
cheb1ap()
scipy.signal._filter_design.cheb1ap (N, rp)
Return (z,p,k) for Nth-order Chebyshev type I analog lowpass filter.
The returned filter prototype has `rp` decibels of ripple in the passband.
The filter's angular (e.g. rad/s) cutoff frequency is normalized to 1,
defined as the point at which the gain first drops below ``-rp``.
See Also
--------
cheby1 : Filter design function using this prototype
Definition at line 4342 of file _filter_design.py.
cheb1ord()
scipy.signal._filter_design.cheb1ord (wp, ws, gpass, gstop, analog = False, fs = None)
Chebyshev type I filter order selection.
Return the order of the lowest order digital or analog Chebyshev Type I
filter that loses no more than `gpass` dB in the passband and has at
least `gstop` dB attenuation in the stopband.
Parameters
----------
wp, ws : float
    Passband and stopband edge frequencies.
    For digital filters, these are in the same units as `fs`. By default,
    `fs` is 2 half-cycles/sample, so these are normalized from 0 to 1,
    where 1 is the Nyquist frequency. (`wp` and `ws` are thus in
    half-cycles / sample.)  For example:
        - Lowpass:   wp = 0.2,          ws = 0.3
        - Highpass:  wp = 0.3,          ws = 0.2
        - Bandpass:  wp = [0.2, 0.5],   ws = [0.1, 0.6]
        - Bandstop:  wp = [0.1, 0.6],   ws = [0.2, 0.5]
    For analog filters, `wp` and `ws` are angular frequencies (e.g., rad/s).
gpass : float
    The maximum loss in the passband (dB).
gstop : float
    The minimum attenuation in the stopband (dB).
analog : bool, optional
    When True, return an analog filter, otherwise a digital filter is
    returned.
fs : float, optional
    The sampling frequency of the digital system.
    .. versionadded:: 1.2.0
Returns
-------
ord : int
    The lowest order for a Chebyshev type I filter that meets specs.
wn : ndarray or float
    The Chebyshev natural frequency (the "3dB frequency") for use with
    `cheby1` to give filter results. If `fs` is specified,
    this is in the same units, and `fs` must also be passed to `cheby1`.
See Also
--------
cheby1 : Filter design using order and critical points
buttord : Find order and critical points from passband and stopband spec
cheb2ord, ellipord
iirfilter : General filter design using order and critical frequencies
iirdesign : General filter design using passband and stopband spec
Examples
--------
Design a digital lowpass filter such that the passband is within 3 dB up
to 0.2*(fs/2), while rejecting at least -40 dB above 0.3*(fs/2). Plot its
frequency response, showing the passband and stopband constraints in gray.
>>> from scipy import signal
>>> import matplotlib.pyplot as plt
>>> import numpy as np
>>> N, Wn = signal.cheb1ord(0.2, 0.3, 3, 40)
>>> b, a = signal.cheby1(N, 3, Wn, 'low')
>>> w, h = signal.freqz(b, a)
>>> plt.semilogx(w / np.pi, 20 * np.log10(abs(h)))
>>> plt.title('Chebyshev I lowpass filter fit to constraints')
>>> plt.xlabel('Normalized frequency')
>>> plt.ylabel('Amplitude [dB]')
>>> plt.grid(which='both', axis='both')
>>> plt.fill([.01, 0.2, 0.2, .01], [-3, -3, -99, -99], '0.9', lw=0) # stop
>>> plt.fill([0.3, 0.3,   2,   2], [ 9, -40, -40,  9], '0.9', lw=0) # pass
>>> plt.axis([0.08, 1, -60, 3])
>>> plt.show()
Definition at line 3865 of file _filter_design.py.
cheb2ap()
scipy.signal._filter_design.cheb2ap (N, rs)
Return (z,p,k) for Nth-order Chebyshev type I analog lowpass filter.
The returned filter prototype has `rs` decibels of ripple in the stopband.
The filter's angular (e.g. rad/s) cutoff frequency is normalized to 1,
defined as the point at which the gain first reaches ``-rs``.
See Also
--------
cheby2 : Filter design function using this prototype
Definition at line 4380 of file _filter_design.py.
cheb2ord()
scipy.signal._filter_design.cheb2ord (wp, ws, gpass, gstop, analog = False, fs = None)
Chebyshev type II filter order selection.
Return the order of the lowest order digital or analog Chebyshev Type II
filter that loses no more than `gpass` dB in the passband and has at least
`gstop` dB attenuation in the stopband.
Parameters
----------
wp, ws : float
    Passband and stopband edge frequencies.
    For digital filters, these are in the same units as `fs`. By default,
    `fs` is 2 half-cycles/sample, so these are normalized from 0 to 1,
    where 1 is the Nyquist frequency. (`wp` and `ws` are thus in
    half-cycles / sample.)  For example:
        - Lowpass:   wp = 0.2,          ws = 0.3
        - Highpass:  wp = 0.3,          ws = 0.2
        - Bandpass:  wp = [0.2, 0.5],   ws = [0.1, 0.6]
        - Bandstop:  wp = [0.1, 0.6],   ws = [0.2, 0.5]
    For analog filters, `wp` and `ws` are angular frequencies (e.g., rad/s).
gpass : float
    The maximum loss in the passband (dB).
gstop : float
    The minimum attenuation in the stopband (dB).
analog : bool, optional
    When True, return an analog filter, otherwise a digital filter is
    returned.
fs : float, optional
    The sampling frequency of the digital system.
    .. versionadded:: 1.2.0
Returns
-------
ord : int
    The lowest order for a Chebyshev type II filter that meets specs.
wn : ndarray or float
    The Chebyshev natural frequency (the "3dB frequency") for use with
    `cheby2` to give filter results. If `fs` is specified,
    this is in the same units, and `fs` must also be passed to `cheby2`.
See Also
--------
cheby2 : Filter design using order and critical points
buttord : Find order and critical points from passband and stopband spec
cheb1ord, ellipord
iirfilter : General filter design using order and critical frequencies
iirdesign : General filter design using passband and stopband spec
Examples
--------
Design a digital bandstop filter which rejects -60 dB from 0.2*(fs/2) to
0.5*(fs/2), while staying within 3 dB below 0.1*(fs/2) or above
0.6*(fs/2). Plot its frequency response, showing the passband and
stopband constraints in gray.
>>> from scipy import signal
>>> import matplotlib.pyplot as plt
>>> import numpy as np
>>> N, Wn = signal.cheb2ord([0.1, 0.6], [0.2, 0.5], 3, 60)
>>> b, a = signal.cheby2(N, 60, Wn, 'stop')
>>> w, h = signal.freqz(b, a)
>>> plt.semilogx(w / np.pi, 20 * np.log10(abs(h)))
>>> plt.title('Chebyshev II bandstop filter fit to constraints')
>>> plt.xlabel('Normalized frequency')
>>> plt.ylabel('Amplitude [dB]')
>>> plt.grid(which='both', axis='both')
>>> plt.fill([.01, .1, .1, .01], [-3,  -3, -99, -99], '0.9', lw=0) # stop
>>> plt.fill([.2,  .2, .5,  .5], [ 9, -60, -60,   9], '0.9', lw=0) # pass
>>> plt.fill([.6,  .6,  2,   2], [-99, -3,  -3, -99], '0.9', lw=0) # stop
>>> plt.axis([0.06, 1, -80, 3])
>>> plt.show()
Definition at line 4007 of file _filter_design.py.
cheby1()
scipy.signal._filter_design.cheby1 (N, rp, Wn, btype = 'low', analog = False, output = 'ba', fs = None)
Chebyshev type I digital and analog filter design.
Design an Nth-order digital or analog Chebyshev type I filter and
return the filter coefficients.
Parameters
----------
N : int
    The order of the filter.
rp : float
    The maximum ripple allowed below unity gain in the passband.
    Specified in decibels, as a positive number.
Wn : array_like
    A scalar or length-2 sequence giving the critical frequencies.
    For Type I filters, this is the point in the transition band at which
    the gain first drops below -`rp`.
    For digital filters, `Wn` are in the same units as `fs`. By default,
    `fs` is 2 half-cycles/sample, so these are normalized from 0 to 1,
    where 1 is the Nyquist frequency. (`Wn` is thus in
    half-cycles / sample.)
    For analog filters, `Wn` is an angular frequency (e.g., rad/s).
btype : {'lowpass', 'highpass', 'bandpass', 'bandstop'}, optional
    The type of filter.  Default is 'lowpass'.
analog : bool, optional
    When True, return an analog filter, otherwise a digital filter is
    returned.
output : {'ba', 'zpk', 'sos'}, optional
    Type of output:  numerator/denominator ('ba'), pole-zero ('zpk'), or
    second-order sections ('sos'). Default is 'ba' for backwards
    compatibility, but 'sos' should be used for general-purpose filtering.
fs : float, optional
    The sampling frequency of the digital system.
    .. versionadded:: 1.2.0
Returns
-------
b, a : ndarray, ndarray
    Numerator (`b`) and denominator (`a`) polynomials of the IIR filter.
    Only returned if ``output='ba'``.
z, p, k : ndarray, ndarray, float
    Zeros, poles, and system gain of the IIR filter transfer
    function.  Only returned if ``output='zpk'``.
sos : ndarray
    Second-order sections representation of the IIR filter.
    Only returned if ``output='sos'``.
See Also
--------
cheb1ord, cheb1ap
Notes
-----
The Chebyshev type I filter maximizes the rate of cutoff between the
frequency response's passband and stopband, at the expense of ripple in
the passband and increased ringing in the step response.
Type I filters roll off faster than Type II (`cheby2`), but Type II
filters do not have any ripple in the passband.
The equiripple passband has N maxima or minima (for example, a
5th-order filter has 3 maxima and 2 minima). Consequently, the DC gain is
unity for odd-order filters, or -rp dB for even-order filters.
The ``'sos'`` output parameter was added in 0.16.0.
Examples
--------
Design an analog filter and plot its frequency response, showing the
critical points:
>>> from scipy import signal
>>> import matplotlib.pyplot as plt
>>> import numpy as np
>>> b, a = signal.cheby1(4, 5, 100, 'low', analog=True)
>>> w, h = signal.freqs(b, a)
>>> plt.semilogx(w, 20 * np.log10(abs(h)))
>>> plt.title('Chebyshev Type I frequency response (rp=5)')
>>> plt.xlabel('Frequency [radians / second]')
>>> plt.ylabel('Amplitude [dB]')
>>> plt.margins(0, 0.1)
>>> plt.grid(which='both', axis='both')
>>> plt.axvline(100, color='green') # cutoff frequency
>>> plt.axhline(-5, color='green') # rp
>>> plt.show()
Generate a signal made up of 10 Hz and 20 Hz, sampled at 1 kHz
>>> t = np.linspace(0, 1, 1000, False)  # 1 second
>>> sig = np.sin(2*np.pi*10*t) + np.sin(2*np.pi*20*t)
>>> fig, (ax1, ax2) = plt.subplots(2, 1, sharex=True)
>>> ax1.plot(t, sig)
>>> ax1.set_title('10 Hz and 20 Hz sinusoids')
>>> ax1.axis([0, 1, -2, 2])
Design a digital high-pass filter at 15 Hz to remove the 10 Hz tone, and
apply it to the signal. (It's recommended to use second-order sections
format when filtering, to avoid numerical error with transfer function
(``ba``) format):
>>> sos = signal.cheby1(10, 1, 15, 'hp', fs=1000, output='sos')
>>> filtered = signal.sosfilt(sos, sig)
>>> ax2.plot(t, filtered)
>>> ax2.set_title('After 15 Hz high-pass filter')
>>> ax2.axis([0, 1, -2, 2])
>>> ax2.set_xlabel('Time [seconds]')
>>> plt.tight_layout()
>>> plt.show()
Definition at line 3105 of file _filter_design.py.
References iirfilter().
Referenced by scipy.signal._signaltools.decimate(), and scipy.signal.tests.test_filter_design.TestFreqz_zpk.test_ticket1441().
cheby2()
scipy.signal._filter_design.cheby2 (N, rs, Wn, btype = 'low', analog = False, output = 'ba', fs = None)
Chebyshev type II digital and analog filter design.
Design an Nth-order digital or analog Chebyshev type II filter and
return the filter coefficients.
Parameters
----------
N : int
    The order of the filter.
rs : float
    The minimum attenuation required in the stop band.
    Specified in decibels, as a positive number.
Wn : array_like
    A scalar or length-2 sequence giving the critical frequencies.
    For Type II filters, this is the point in the transition band at which
    the gain first reaches -`rs`.
    For digital filters, `Wn` are in the same units as `fs`. By default,
    `fs` is 2 half-cycles/sample, so these are normalized from 0 to 1,
    where 1 is the Nyquist frequency. (`Wn` is thus in
    half-cycles / sample.)
    For analog filters, `Wn` is an angular frequency (e.g., rad/s).
btype : {'lowpass', 'highpass', 'bandpass', 'bandstop'}, optional
    The type of filter.  Default is 'lowpass'.
analog : bool, optional
    When True, return an analog filter, otherwise a digital filter is
    returned.
output : {'ba', 'zpk', 'sos'}, optional
    Type of output:  numerator/denominator ('ba'), pole-zero ('zpk'), or
    second-order sections ('sos'). Default is 'ba' for backwards
    compatibility, but 'sos' should be used for general-purpose filtering.
fs : float, optional
    The sampling frequency of the digital system.
    .. versionadded:: 1.2.0
Returns
-------
b, a : ndarray, ndarray
    Numerator (`b`) and denominator (`a`) polynomials of the IIR filter.
    Only returned if ``output='ba'``.
z, p, k : ndarray, ndarray, float
    Zeros, poles, and system gain of the IIR filter transfer
    function.  Only returned if ``output='zpk'``.
sos : ndarray
    Second-order sections representation of the IIR filter.
    Only returned if ``output='sos'``.
See Also
--------
cheb2ord, cheb2ap
Notes
-----
The Chebyshev type II filter maximizes the rate of cutoff between the
frequency response's passband and stopband, at the expense of ripple in
the stopband and increased ringing in the step response.
Type II filters do not roll off as fast as Type I (`cheby1`).
The ``'sos'`` output parameter was added in 0.16.0.
Examples
--------
Design an analog filter and plot its frequency response, showing the
critical points:
>>> from scipy import signal
>>> import matplotlib.pyplot as plt
>>> import numpy as np
>>> b, a = signal.cheby2(4, 40, 100, 'low', analog=True)
>>> w, h = signal.freqs(b, a)
>>> plt.semilogx(w, 20 * np.log10(abs(h)))
>>> plt.title('Chebyshev Type II frequency response (rs=40)')
>>> plt.xlabel('Frequency [radians / second]')
>>> plt.ylabel('Amplitude [dB]')
>>> plt.margins(0, 0.1)
>>> plt.grid(which='both', axis='both')
>>> plt.axvline(100, color='green') # cutoff frequency
>>> plt.axhline(-40, color='green') # rs
>>> plt.show()
Generate a signal made up of 10 Hz and 20 Hz, sampled at 1 kHz
>>> t = np.linspace(0, 1, 1000, False)  # 1 second
>>> sig = np.sin(2*np.pi*10*t) + np.sin(2*np.pi*20*t)
>>> fig, (ax1, ax2) = plt.subplots(2, 1, sharex=True)
>>> ax1.plot(t, sig)
>>> ax1.set_title('10 Hz and 20 Hz sinusoids')
>>> ax1.axis([0, 1, -2, 2])
Design a digital high-pass filter at 17 Hz to remove the 10 Hz tone, and
apply it to the signal. (It's recommended to use second-order sections
format when filtering, to avoid numerical error with transfer function
(``ba``) format):
>>> sos = signal.cheby2(12, 20, 17, 'hp', fs=1000, output='sos')
>>> filtered = signal.sosfilt(sos, sig)
>>> ax2.plot(t, filtered)
>>> ax2.set_title('After 17 Hz high-pass filter')
>>> ax2.axis([0, 1, -2, 2])
>>> ax2.set_xlabel('Time [seconds]')
>>> plt.show()
Definition at line 3223 of file _filter_design.py.
References iirfilter().
ellip()
scipy.signal._filter_design.ellip (N, rp, rs, Wn, btype = 'low', analog = False, output = 'ba', fs = None)
Elliptic (Cauer) digital and analog filter design.
Design an Nth-order digital or analog elliptic filter and return
the filter coefficients.
Parameters
----------
N : int
    The order of the filter.
rp : float
    The maximum ripple allowed below unity gain in the passband.
    Specified in decibels, as a positive number.
rs : float
    The minimum attenuation required in the stop band.
    Specified in decibels, as a positive number.
Wn : array_like
    A scalar or length-2 sequence giving the critical frequencies.
    For elliptic filters, this is the point in the transition band at
    which the gain first drops below -`rp`.
    For digital filters, `Wn` are in the same units as `fs`. By default,
    `fs` is 2 half-cycles/sample, so these are normalized from 0 to 1,
    where 1 is the Nyquist frequency. (`Wn` is thus in
    half-cycles / sample.)
    For analog filters, `Wn` is an angular frequency (e.g., rad/s).
btype : {'lowpass', 'highpass', 'bandpass', 'bandstop'}, optional
    The type of filter. Default is 'lowpass'.
analog : bool, optional
    When True, return an analog filter, otherwise a digital filter is
    returned.
output : {'ba', 'zpk', 'sos'}, optional
    Type of output:  numerator/denominator ('ba'), pole-zero ('zpk'), or
    second-order sections ('sos'). Default is 'ba' for backwards
    compatibility, but 'sos' should be used for general-purpose filtering.
fs : float, optional
    The sampling frequency of the digital system.
    .. versionadded:: 1.2.0
Returns
-------
b, a : ndarray, ndarray
    Numerator (`b`) and denominator (`a`) polynomials of the IIR filter.
    Only returned if ``output='ba'``.
z, p, k : ndarray, ndarray, float
    Zeros, poles, and system gain of the IIR filter transfer
    function.  Only returned if ``output='zpk'``.
sos : ndarray
    Second-order sections representation of the IIR filter.
    Only returned if ``output='sos'``.
See Also
--------
ellipord, ellipap
Notes
-----
Also known as Cauer or Zolotarev filters, the elliptical filter maximizes
the rate of transition between the frequency response's passband and
stopband, at the expense of ripple in both, and increased ringing in the
step response.
As `rp` approaches 0, the elliptical filter becomes a Chebyshev
type II filter (`cheby2`). As `rs` approaches 0, it becomes a Chebyshev
type I filter (`cheby1`). As both approach 0, it becomes a Butterworth
filter (`butter`).
The equiripple passband has N maxima or minima (for example, a
5th-order filter has 3 maxima and 2 minima). Consequently, the DC gain is
unity for odd-order filters, or -rp dB for even-order filters.
The ``'sos'`` output parameter was added in 0.16.0.
Examples
--------
Design an analog filter and plot its frequency response, showing the
critical points:
>>> from scipy import signal
>>> import matplotlib.pyplot as plt
>>> import numpy as np
>>> b, a = signal.ellip(4, 5, 40, 100, 'low', analog=True)
>>> w, h = signal.freqs(b, a)
>>> plt.semilogx(w, 20 * np.log10(abs(h)))
>>> plt.title('Elliptic filter frequency response (rp=5, rs=40)')
>>> plt.xlabel('Frequency [radians / second]')
>>> plt.ylabel('Amplitude [dB]')
>>> plt.margins(0, 0.1)
>>> plt.grid(which='both', axis='both')
>>> plt.axvline(100, color='green') # cutoff frequency
>>> plt.axhline(-40, color='green') # rs
>>> plt.axhline(-5, color='green') # rp
>>> plt.show()
Generate a signal made up of 10 Hz and 20 Hz, sampled at 1 kHz
>>> t = np.linspace(0, 1, 1000, False)  # 1 second
>>> sig = np.sin(2*np.pi*10*t) + np.sin(2*np.pi*20*t)
>>> fig, (ax1, ax2) = plt.subplots(2, 1, sharex=True)
>>> ax1.plot(t, sig)
>>> ax1.set_title('10 Hz and 20 Hz sinusoids')
>>> ax1.axis([0, 1, -2, 2])
Design a digital high-pass filter at 17 Hz to remove the 10 Hz tone, and
apply it to the signal. (It's recommended to use second-order sections
format when filtering, to avoid numerical error with transfer function
(``ba``) format):
>>> sos = signal.ellip(8, 1, 100, 17, 'hp', fs=1000, output='sos')
>>> filtered = signal.sosfilt(sos, sig)
>>> ax2.plot(t, filtered)
>>> ax2.set_title('After 17 Hz high-pass filter')
>>> ax2.axis([0, 1, -2, 2])
>>> ax2.set_xlabel('Time [seconds]')
>>> plt.tight_layout()
>>> plt.show()
Definition at line 3335 of file _filter_design.py.
References iirfilter().
ellipap()
scipy.signal._filter_design.ellipap (N, rp, rs)
Return (z,p,k) of Nth-order elliptic analog lowpass filter.
The filter is a normalized prototype that has `rp` decibels of ripple
in the passband and a stopband `rs` decibels down.
The filter's angular (e.g., rad/s) cutoff frequency is normalized to 1,
defined as the point at which the gain first drops below ``-rp``.
See Also
--------
ellip : Filter design function using this prototype
References
----------
.. [1] Lutova, Tosic, and Evans, "Filter Design for Signal Processing",
       Chapters 5 and 12.
.. [2] Orfanidis, "Lecture Notes on Elliptic Filter Design",
       https://www.ece.rutgers.edu/~orfanidi/ece521/notes.pdf
Definition at line 4550 of file _filter_design.py.
References _arc_jac_sc1(), _ellipdeg(), and _pow10m1().
ellipord()
scipy.signal._filter_design.ellipord (wp, ws, gpass, gstop, analog = False, fs = None)
Elliptic (Cauer) filter order selection.
Return the order of the lowest order digital or analog elliptic filter
that loses no more than `gpass` dB in the passband and has at least
`gstop` dB attenuation in the stopband.
Parameters
----------
wp, ws : float
    Passband and stopband edge frequencies.
    For digital filters, these are in the same units as `fs`. By default,
    `fs` is 2 half-cycles/sample, so these are normalized from 0 to 1,
    where 1 is the Nyquist frequency. (`wp` and `ws` are thus in
    half-cycles / sample.) For example:
        - Lowpass:   wp = 0.2,          ws = 0.3
        - Highpass:  wp = 0.3,          ws = 0.2
        - Bandpass:  wp = [0.2, 0.5],   ws = [0.1, 0.6]
        - Bandstop:  wp = [0.1, 0.6],   ws = [0.2, 0.5]
    For analog filters, `wp` and `ws` are angular frequencies (e.g., rad/s).
gpass : float
    The maximum loss in the passband (dB).
gstop : float
    The minimum attenuation in the stopband (dB).
analog : bool, optional
    When True, return an analog filter, otherwise a digital filter is
    returned.
fs : float, optional
    The sampling frequency of the digital system.
    .. versionadded:: 1.2.0
Returns
-------
ord : int
    The lowest order for an Elliptic (Cauer) filter that meets specs.
wn : ndarray or float
    The Chebyshev natural frequency (the "3dB frequency") for use with
    `ellip` to give filter results. If `fs` is specified,
    this is in the same units, and `fs` must also be passed to `ellip`.
See Also
--------
ellip : Filter design using order and critical points
buttord : Find order and critical points from passband and stopband spec
cheb1ord, cheb2ord
iirfilter : General filter design using order and critical frequencies
iirdesign : General filter design using passband and stopband spec
Examples
--------
Design an analog highpass filter such that the passband is within 3 dB
above 30 rad/s, while rejecting -60 dB at 10 rad/s. Plot its
frequency response, showing the passband and stopband constraints in gray.
>>> from scipy import signal
>>> import matplotlib.pyplot as plt
>>> import numpy as np
>>> N, Wn = signal.ellipord(30, 10, 3, 60, True)
>>> b, a = signal.ellip(N, 3, 60, Wn, 'high', True)
>>> w, h = signal.freqs(b, a, np.logspace(0, 3, 500))
>>> plt.semilogx(w, 20 * np.log10(abs(h)))
>>> plt.title('Elliptical highpass filter fit to constraints')
>>> plt.xlabel('Frequency [radians / second]')
>>> plt.ylabel('Amplitude [dB]')
>>> plt.grid(which='both', axis='both')
>>> plt.fill([.1, 10,  10,  .1], [1e4, 1e4, -60, -60], '0.9', lw=0) # stop
>>> plt.fill([30, 30, 1e9, 1e9], [-99,  -3,  -3, -99], '0.9', lw=0) # pass
>>> plt.axis([1, 300, -80, 3])
>>> plt.show()
Definition at line 4181 of file _filter_design.py.
References _pow10m1().
findfreqs()
scipy.signal._filter_design.findfreqs (num, den, N, kind = 'ba')
Find array of frequencies for computing the response of an analog filter.
Parameters
----------
num, den : array_like, 1-D
    The polynomial coefficients of the numerator and denominator of the
    transfer function of the filter or LTI system, where the coefficients
    are ordered from highest to lowest degree. Or, the roots  of the
    transfer function numerator and denominator (i.e., zeroes and poles).
N : int
    The length of the array to be computed.
kind : str {'ba', 'zp'}, optional
    Specifies whether the numerator and denominator are specified by their
    polynomial coefficients ('ba'), or their roots ('zp').
Returns
-------
w : (N,) ndarray
    A 1-D array of frequencies, logarithmically spaced.
Examples
--------
Find a set of nine frequencies that span the "interesting part" of the
frequency response for the filter with the transfer function
    H(s) = s / (s^2 + 8s + 25)
>>> from scipy import signal
>>> signal.findfreqs([1, 0], [1, 8, 25], N=9)
array([  1.00000000e-02,   3.16227766e-02,   1.00000000e-01,
         3.16227766e-01,   1.00000000e+00,   3.16227766e+00,
         1.00000000e+01,   3.16227766e+01,   1.00000000e+02])
Definition at line 58 of file _filter_design.py.
Referenced by freqs(), and freqs_zpk().
freqs()
scipy.signal._filter_design.freqs (b, a, worN = 200, plot = None)
Compute frequency response of analog filter.
Given the M-order numerator `b` and N-order denominator `a` of an analog
filter, compute its frequency response::
         b[0]*(jw)**M + b[1]*(jw)**(M-1) + ... + b[M]
 H(w) = ----------------------------------------------
         a[0]*(jw)**N + a[1]*(jw)**(N-1) + ... + a[N]
Parameters
----------
b : array_like
    Numerator of a linear filter.
a : array_like
    Denominator of a linear filter.
worN : {None, int, array_like}, optional
    If None, then compute at 200 frequencies around the interesting parts
    of the response curve (determined by pole-zero locations). If a single
    integer, then compute at that many frequencies. Otherwise, compute the
    response at the angular frequencies (e.g., rad/s) given in `worN`.
plot : callable, optional
    A callable that takes two arguments. If given, the return parameters
    `w` and `h` are passed to plot. Useful for plotting the frequency
    response inside `freqs`.
Returns
-------
w : ndarray
    The angular frequencies at which `h` was computed.
h : ndarray
    The frequency response.
See Also
--------
freqz : Compute the frequency response of a digital filter.
Notes
-----
Using Matplotlib's "plot" function as the callable for `plot` produces
unexpected results, this plots the real part of the complex transfer
function, not the magnitude. Try ``lambda w, h: plot(w, abs(h))``.
Examples
--------
>>> from scipy.signal import freqs, iirfilter
>>> import numpy as np
>>> b, a = iirfilter(4, [1, 10], 1, 60, analog=True, ftype='cheby1')
>>> w, h = freqs(b, a, worN=np.logspace(-1, 2, 1000))
>>> import matplotlib.pyplot as plt
>>> plt.semilogx(w, 20 * np.log10(abs(h)))
>>> plt.xlabel('Frequency')
>>> plt.ylabel('Amplitude response [dB]')
>>> plt.grid(True)
>>> plt.show()
Definition at line 119 of file _filter_design.py.
References _is_int_type(), and findfreqs().
Referenced by scipy.signal._ltisys.freqresp().
freqs_zpk()
scipy.signal._filter_design.freqs_zpk (z, p, k, worN = 200)
Compute frequency response of analog filter.
Given the zeros `z`, poles `p`, and gain `k` of a filter, compute its
frequency response::
            (jw-z[0]) * (jw-z[1]) * ... * (jw-z[-1])
 H(w) = k * ----------------------------------------
            (jw-p[0]) * (jw-p[1]) * ... * (jw-p[-1])
Parameters
----------
z : array_like
    Zeroes of a linear filter
p : array_like
    Poles of a linear filter
k : scalar
    Gain of a linear filter
worN : {None, int, array_like}, optional
    If None, then compute at 200 frequencies around the interesting parts
    of the response curve (determined by pole-zero locations). If a single
    integer, then compute at that many frequencies. Otherwise, compute the
    response at the angular frequencies (e.g., rad/s) given in `worN`.
Returns
-------
w : ndarray
    The angular frequencies at which `h` was computed.
h : ndarray
    The frequency response.
See Also
--------
freqs : Compute the frequency response of an analog filter in TF form
freqz : Compute the frequency response of a digital filter in TF form
freqz_zpk : Compute the frequency response of a digital filter in ZPK form
Notes
-----
.. versionadded:: 0.19.0
Examples
--------
>>> import numpy as np
>>> from scipy.signal import freqs_zpk, iirfilter
>>> z, p, k = iirfilter(4, [1, 10], 1, 60, analog=True, ftype='cheby1',
...                     output='zpk')
>>> w, h = freqs_zpk(z, p, k, worN=np.logspace(-1, 2, 1000))
>>> import matplotlib.pyplot as plt
>>> plt.semilogx(w, 20 * np.log10(abs(h)))
>>> plt.xlabel('Frequency')
>>> plt.ylabel('Amplitude response [dB]')
>>> plt.grid(True)
>>> plt.show()
Definition at line 196 of file _filter_design.py.
References _is_int_type(), and findfreqs().
Referenced by scipy.signal._ltisys.freqresp().
freqz()
scipy.signal._filter_design.freqz (b, a = 1, worN = 512, whole = False, plot = None, fs = 2*pi, include_nyquist = False)
Compute the frequency response of a digital filter.
Given the M-order numerator `b` and N-order denominator `a` of a digital
filter, compute its frequency response::
             jw                 -jw              -jwM
    jw    B(e  )    b[0] + b[1]e    + ... + b[M]e
 H(e  ) = ------ = -----------------------------------
             jw                 -jw              -jwN
          A(e  )    a[0] + a[1]e    + ... + a[N]e
Parameters
----------
b : array_like
    Numerator of a linear filter. If `b` has dimension greater than 1,
    it is assumed that the coefficients are stored in the first dimension,
    and ``b.shape[1:]``, ``a.shape[1:]``, and the shape of the frequencies
    array must be compatible for broadcasting.
a : array_like
    Denominator of a linear filter. If `b` has dimension greater than 1,
    it is assumed that the coefficients are stored in the first dimension,
    and ``b.shape[1:]``, ``a.shape[1:]``, and the shape of the frequencies
    array must be compatible for broadcasting.
worN : {None, int, array_like}, optional
    If a single integer, then compute at that many frequencies (default is
    N=512). This is a convenient alternative to::
        np.linspace(0, fs if whole else fs/2, N, endpoint=include_nyquist)
    Using a number that is fast for FFT computations can result in
    faster computations (see Notes).
    If an array_like, compute the response at the frequencies given.
    These are in the same units as `fs`.
whole : bool, optional
    Normally, frequencies are computed from 0 to the Nyquist frequency,
    fs/2 (upper-half of unit-circle). If `whole` is True, compute
    frequencies from 0 to fs. Ignored if worN is array_like.
plot : callable
    A callable that takes two arguments. If given, the return parameters
    `w` and `h` are passed to plot. Useful for plotting the frequency
    response inside `freqz`.
fs : float, optional
    The sampling frequency of the digital system. Defaults to 2*pi
    radians/sample (so w is from 0 to pi).
    .. versionadded:: 1.2.0
include_nyquist : bool, optional
    If `whole` is False and `worN` is an integer, setting `include_nyquist`
    to True will include the last frequency (Nyquist frequency) and is
    otherwise ignored.
    .. versionadded:: 1.5.0
Returns
-------
w : ndarray
    The frequencies at which `h` was computed, in the same units as `fs`.
    By default, `w` is normalized to the range [0, pi) (radians/sample).
h : ndarray
    The frequency response, as complex numbers.
See Also
--------
freqz_zpk
sosfreqz
Notes
-----
Using Matplotlib's :func:`matplotlib.pyplot.plot` function as the callable
for `plot` produces unexpected results, as this plots the real part of the
complex transfer function, not the magnitude.
Try ``lambda w, h: plot(w, np.abs(h))``.
A direct computation via (R)FFT is used to compute the frequency response
when the following conditions are met:
1. An integer value is given for `worN`.
2. `worN` is fast to compute via FFT (i.e.,
   `next_fast_len(worN) <scipy.fft.next_fast_len>` equals `worN`).
3. The denominator coefficients are a single value (``a.shape[0] == 1``).
4. `worN` is at least as long as the numerator coefficients
   (``worN >= b.shape[0]``).
5. If ``b.ndim > 1``, then ``b.shape[-1] == 1``.
For long FIR filters, the FFT approach can have lower error and be much
faster than the equivalent direct polynomial calculation.
Examples
--------
>>> from scipy import signal
>>> import numpy as np
>>> b = signal.firwin(80, 0.5, window=('kaiser', 8))
>>> w, h = signal.freqz(b)
>>> import matplotlib.pyplot as plt
>>> fig, ax1 = plt.subplots()
>>> ax1.set_title('Digital filter frequency response')
>>> ax1.plot(w, 20 * np.log10(abs(h)), 'b')
>>> ax1.set_ylabel('Amplitude [dB]', color='b')
>>> ax1.set_xlabel('Frequency [rad/sample]')
>>> ax2 = ax1.twinx()
>>> angles = np.unwrap(np.angle(h))
>>> ax2.plot(w, angles, 'g')
>>> ax2.set_ylabel('Angle (radians)', color='g')
>>> ax2.grid(True)
>>> ax2.axis('tight')
>>> plt.show()
Broadcasting Examples
Suppose we have two FIR filters whose coefficients are stored in the
rows of an array with shape (2, 25). For this demonstration, we'll
use random data:
>>> rng = np.random.default_rng()
>>> b = rng.random((2, 25))
To compute the frequency response for these two filters with one call
to `freqz`, we must pass in ``b.T``, because `freqz` expects the first
axis to hold the coefficients. We must then extend the shape with a
trivial dimension of length 1 to allow broadcasting with the array
of frequencies.  That is, we pass in ``b.T[..., np.newaxis]``, which has
shape (25, 2, 1):
>>> w, h = signal.freqz(b.T[..., np.newaxis], worN=1024)
>>> w.shape
(1024,)
>>> h.shape
(2, 1024)
Now, suppose we have two transfer functions, with the same numerator
coefficients ``b = [0.5, 0.5]``. The coefficients for the two denominators
are stored in the first dimension of the 2-D array  `a`::
    a = [   1      1  ]
        [ -0.25, -0.5 ]
>>> b = np.array([0.5, 0.5])
>>> a = np.array([[1, 1], [-0.25, -0.5]])
Only `a` is more than 1-D. To make it compatible for
broadcasting with the frequencies, we extend it with a trivial dimension
in the call to `freqz`:
>>> w, h = signal.freqz(b, a[..., np.newaxis], worN=1024)
>>> w.shape
(1024,)
>>> h.shape
(2, 1024)
Definition at line 276 of file _filter_design.py.
References _is_int_type().
Referenced by scipy.signal._ltisys.dfreqresp(), scipy.signal.tests.test_fir_filter_design.TestFirwin.mse(), sosfreqz(), scipy.signal.tests.test_fir_filter_design.TestFirwin2.test05(), scipy.signal.tests.test_fir_filter_design.TestFirwin2.test06(), scipy.signal.tests.test_fir_filter_design.TestFirWinMore.test_fs_nyq(), scipy.signal.tests.test_filter_design.TestFreqz.test_ticket1441(), and scipy.signal.tests.test_filter_design.TestFreqz_zpk.test_ticket1441().
freqz_zpk()
scipy.signal._filter_design.freqz_zpk (z, p, k, worN = 512, whole = False, fs = 2*pi)
Compute the frequency response of a digital filter in ZPK form.
Given the Zeros, Poles and Gain of a digital filter, compute its frequency
response:
:math:`H(z)=k \prod_i (z - Z[i]) / \prod_j (z - P[j])`
where :math:`k` is the `gain`, :math:`Z` are the `zeros` and :math:`P` are
the `poles`.
Parameters
----------
z : array_like
Zeroes of a linear filter
p : array_like
Poles of a linear filter
k : scalar
Gain of a linear filter
worN : {None, int, array_like}, optional
If a single integer, then compute at that many frequencies (default is
N=512).
If an array_like, compute the response at the frequencies given.
These are in the same units as `fs`.
whole : bool, optional
Normally, frequencies are computed from 0 to the Nyquist frequency,
fs/2 (upper-half of unit-circle). If `whole` is True, compute
frequencies from 0 to fs. Ignored if w is array_like.
fs : float, optional
The sampling frequency of the digital system. Defaults to 2*pi
radians/sample (so w is from 0 to pi).
.. versionadded:: 1.2.0
Returns
-------
w : ndarray
The frequencies at which `h` was computed, in the same units as `fs`.
By default, `w` is normalized to the range [0, pi) (radians/sample).
h : ndarray
The frequency response, as complex numbers.
See Also
--------
freqs : Compute the frequency response of an analog filter in TF form
freqs_zpk : Compute the frequency response of an analog filter in ZPK form
freqz : Compute the frequency response of a digital filter in TF form
Notes
-----
.. versionadded:: 0.19.0
Examples
--------
Design a 4th-order digital Butterworth filter with cut-off of 100 Hz in a
system with sample rate of 1000 Hz, and plot the frequency response:
>>> import numpy as np
>>> from scipy import signal
>>> z, p, k = signal.butter(4, 100, output='zpk', fs=1000)
>>> w, h = signal.freqz_zpk(z, p, k, fs=1000)
>>> import matplotlib.pyplot as plt
>>> fig = plt.figure()
>>> ax1 = fig.add_subplot(1, 1, 1)
>>> ax1.set_title('Digital filter frequency response')
>>> ax1.plot(w, 20 * np.log10(abs(h)), 'b')
>>> ax1.set_ylabel('Amplitude [dB]', color='b')
>>> ax1.set_xlabel('Frequency [Hz]')
>>> ax1.grid(True)
>>> ax2 = ax1.twinx()
>>> angles = np.unwrap(np.angle(h))
>>> ax2.plot(w, angles, 'g')
>>> ax2.set_ylabel('Angle [radians]', color='g')
>>> plt.axis('tight')
>>> plt.show()
Definition at line 491 of file _filter_design.py.
References _is_int_type().
Referenced by scipy.signal._ltisys.dfreqresp(), and scipy.signal.tests.test_filter_design.TestFreqz_zpk.test_ticket1441().
gammatone()
scipy.signal._filter_design.gammatone (freq, ftype, order = None, numtaps = None, fs = None)
Gammatone filter design.
This function computes the coefficients of an FIR or IIR gammatone
digital filter [1]_.
Parameters
----------
freq : float
    Center frequency of the filter (expressed in the same units
    as `fs`).
ftype : {'fir', 'iir'}
    The type of filter the function generates. If 'fir', the function
    will generate an Nth order FIR gammatone filter. If 'iir', the
    function will generate an 8th order digital IIR filter, modeled as
    as 4th order gammatone filter.
order : int, optional
    The order of the filter. Only used when ``ftype='fir'``.
    Default is 4 to model the human auditory system. Must be between
    0 and 24.
numtaps : int, optional
    Length of the filter. Only used when ``ftype='fir'``.
    Default is ``fs*0.015`` if `fs` is greater than 1000,
    15 if `fs` is less than or equal to 1000.
fs : float, optional
    The sampling frequency of the signal. `freq` must be between
    0 and ``fs/2``. Default is 2.
Returns
-------
b, a : ndarray, ndarray
    Numerator (``b``) and denominator (``a``) polynomials of the filter.
Raises
------
ValueError
    If `freq` is less than or equal to 0 or greater than or equal to
    ``fs/2``, if `ftype` is not 'fir' or 'iir', if `order` is less than
    or equal to 0 or greater than 24 when ``ftype='fir'``
See Also
--------
firwin
iirfilter
References
----------
.. [1] Slaney, Malcolm, "An Efficient Implementation of the
    Patterson-Holdsworth Auditory Filter Bank", Apple Computer
    Technical Report 35, 1993, pp.3-8, 34-39.
Examples
--------
16-sample 4th order FIR Gammatone filter centered at 440 Hz
>>> from scipy import signal
>>> signal.gammatone(440, 'fir', numtaps=16, fs=16000)
(array([ 0.00000000e+00,  2.22196719e-07,  1.64942101e-06,  4.99298227e-06,
    1.01993969e-05,  1.63125770e-05,  2.14648940e-05,  2.29947263e-05,
    1.76776931e-05,  2.04980537e-06, -2.72062858e-05, -7.28455299e-05,
   -1.36651076e-04, -2.19066855e-04, -3.18905076e-04, -4.33156712e-04]),
   [1.0])
IIR Gammatone filter centered at 440 Hz
>>> import matplotlib.pyplot as plt
>>> import numpy as np
>>> b, a = signal.gammatone(440, 'iir', fs=16000)
>>> w, h = signal.freqz(b, a)
>>> plt.plot(w / ((2 * np.pi) / 16000), 20 * np.log10(abs(h)))
>>> plt.xscale('log')
>>> plt.title('Gammatone filter frequency response')
>>> plt.xlabel('Frequency')
>>> plt.ylabel('Amplitude [dB]')
>>> plt.margins(0, 0.1)
>>> plt.grid(which='both', axis='both')
>>> plt.axvline(440, color='green') # cutoff frequency
>>> plt.show()
Definition at line 5393 of file _filter_design.py.
References _hz_to_erb().
group_delay()
scipy.signal._filter_design.group_delay (system, w = 512, whole = False, fs = 2*pi)
Compute the group delay of a digital filter.
The group delay measures by how many samples amplitude envelopes of
various spectral components of a signal are delayed by a filter.
It is formally defined as the derivative of continuous (unwrapped) phase::
       d        jw
D(w) = - -- arg H(e)
      dw
Parameters
----------
system : tuple of array_like (b, a)
Numerator and denominator coefficients of a filter transfer function.
w : {None, int, array_like}, optional
If a single integer, then compute at that many frequencies (default is
N=512).
If an array_like, compute the delay at the frequencies given. These
are in the same units as `fs`.
whole : bool, optional
Normally, frequencies are computed from 0 to the Nyquist frequency,
fs/2 (upper-half of unit-circle). If `whole` is True, compute
frequencies from 0 to fs. Ignored if w is array_like.
fs : float, optional
The sampling frequency of the digital system. Defaults to 2*pi
radians/sample (so w is from 0 to pi).
.. versionadded:: 1.2.0
Returns
-------
w : ndarray
The frequencies at which group delay was computed, in the same units
as `fs`.  By default, `w` is normalized to the range [0, pi)
(radians/sample).
gd : ndarray
The group delay.
See Also
--------
freqz : Frequency response of a digital filter
Notes
-----
The similar function in MATLAB is called `grpdelay`.
If the transfer function :math:`H(z)` has zeros or poles on the unit
circle, the group delay at corresponding frequencies is undefined.
When such a case arises the warning is raised and the group delay
is set to 0 at those frequencies.
For the details of numerical computation of the group delay refer to [1]_.
.. versionadded:: 0.16.0
References
----------
.. [1] Richard G. Lyons, "Understanding Digital Signal Processing,
   3rd edition", p. 830.
Examples
--------
>>> from scipy import signal
>>> b, a = signal.iirdesign(0.1, 0.3, 5, 50, ftype='cheby1')
>>> w, gd = signal.group_delay((b, a))
>>> import matplotlib.pyplot as plt
>>> plt.title('Digital filter group delay')
>>> plt.plot(w, gd)
>>> plt.ylabel('Group delay [samples]')
>>> plt.xlabel('Frequency [rad/sample]')
>>> plt.show()
Definition at line 598 of file _filter_design.py.
References _is_int_type().
iircomb()
scipy.signal._filter_design.iircomb (w0, Q, ftype = 'notch', fs = 2.0, * , pass_zero = False)
Design IIR notching or peaking digital comb filter.
A notching comb filter consists of regularly-spaced band-stop filters with
a narrow bandwidth (high quality factor). Each rejects a narrow frequency
band and leaves the rest of the spectrum little changed.
A peaking comb filter consists of regularly-spaced band-pass filters with
a narrow bandwidth (high quality factor). Each rejects components outside
a narrow frequency band.
Parameters
----------
w0 : float
    The fundamental frequency of the comb filter (the spacing between its
    peaks). This must evenly divide the sampling frequency. If `fs` is
    specified, this is in the same units as `fs`. By default, it is
    a normalized scalar that must satisfy  ``0 < w0 < 1``, with
    ``w0 = 1`` corresponding to half of the sampling frequency.
Q : float
    Quality factor. Dimensionless parameter that characterizes
    notch filter -3 dB bandwidth ``bw`` relative to its center
    frequency, ``Q = w0/bw``.
ftype : {'notch', 'peak'}
    The type of comb filter generated by the function. If 'notch', then
    the Q factor applies to the notches. If 'peak', then the Q factor
    applies to the peaks.  Default is 'notch'.
fs : float, optional
    The sampling frequency of the signal. Default is 2.0.
pass_zero : bool, optional
    If False (default), the notches (nulls) of the filter are centered on
    frequencies [0, w0, 2*w0, ...], and the peaks are centered on the
    midpoints [w0/2, 3*w0/2, 5*w0/2, ...].  If True, the peaks are centered
    on [0, w0, 2*w0, ...] (passing zero frequency) and vice versa.
    .. versionadded:: 1.9.0
Returns
-------
b, a : ndarray, ndarray
    Numerator (``b``) and denominator (``a``) polynomials
    of the IIR filter.
Raises
------
ValueError
    If `w0` is less than or equal to 0 or greater than or equal to
    ``fs/2``, if `fs` is not divisible by `w0`, if `ftype`
    is not 'notch' or 'peak'
See Also
--------
iirnotch
iirpeak
Notes
-----
For implementation details, see [1]_. The TF implementation of the
comb filter is numerically stable even at higher orders due to the
use of a single repeated pole, which won't suffer from precision loss.
References
----------
.. [1] Sophocles J. Orfanidis, "Introduction To Signal Processing",
       Prentice-Hall, 1996, ch. 11, "Digital Filter Design"
Examples
--------
Design and plot notching comb filter at 20 Hz for a
signal sampled at 200 Hz, using quality factor Q = 30
>>> from scipy import signal
>>> import matplotlib.pyplot as plt
>>> import numpy as np
>>> fs = 200.0  # Sample frequency (Hz)
>>> f0 = 20.0  # Frequency to be removed from signal (Hz)
>>> Q = 30.0  # Quality factor
>>> # Design notching comb filter
>>> b, a = signal.iircomb(f0, Q, ftype='notch', fs=fs)
>>> # Frequency response
>>> freq, h = signal.freqz(b, a, fs=fs)
>>> response = abs(h)
>>> # To avoid divide by zero when graphing
>>> response[response == 0] = 1e-20
>>> # Plot
>>> fig, ax = plt.subplots(2, 1, figsize=(8, 6), sharex=True)
>>> ax[0].plot(freq, 20*np.log10(abs(response)), color='blue')
>>> ax[0].set_title("Frequency Response")
>>> ax[0].set_ylabel("Amplitude (dB)", color='blue')
>>> ax[0].set_xlim([0, 100])
>>> ax[0].set_ylim([-30, 10])
>>> ax[0].grid(True)
>>> ax[1].plot(freq, (np.angle(h)*180/np.pi+180)%360 - 180, color='green')
>>> ax[1].set_ylabel("Angle (degrees)", color='green')
>>> ax[1].set_xlabel("Frequency (Hz)")
>>> ax[1].set_xlim([0, 100])
>>> ax[1].set_yticks([-90, -60, -30, 0, 30, 60, 90])
>>> ax[1].set_ylim([-90, 90])
>>> ax[1].grid(True)
>>> plt.show()
Design and plot peaking comb filter at 250 Hz for a
signal sampled at 1000 Hz, using quality factor Q = 30
>>> fs = 1000.0  # Sample frequency (Hz)
>>> f0 = 250.0  # Frequency to be retained (Hz)
>>> Q = 30.0  # Quality factor
>>> # Design peaking filter
>>> b, a = signal.iircomb(f0, Q, ftype='peak', fs=fs, pass_zero=True)
>>> # Frequency response
>>> freq, h = signal.freqz(b, a, fs=fs)
>>> response = abs(h)
>>> # To avoid divide by zero when graphing
>>> response[response == 0] = 1e-20
>>> # Plot
>>> fig, ax = plt.subplots(2, 1, figsize=(8, 6), sharex=True)
>>> ax[0].plot(freq, 20*np.log10(np.maximum(abs(h), 1e-5)), color='blue')
>>> ax[0].set_title("Frequency Response")
>>> ax[0].set_ylabel("Amplitude (dB)", color='blue')
>>> ax[0].set_xlim([0, 500])
>>> ax[0].set_ylim([-80, 10])
>>> ax[0].grid(True)
>>> ax[1].plot(freq, (np.angle(h)*180/np.pi+180)%360 - 180, color='green')
>>> ax[1].set_ylabel("Angle (degrees)", color='green')
>>> ax[1].set_xlabel("Frequency (Hz)")
>>> ax[1].set_xlim([0, 500])
>>> ax[1].set_yticks([-90, -60, -30, 0, 30, 60, 90])
>>> ax[1].set_ylim([-90, 90])
>>> ax[1].grid(True)
>>> plt.show()
Definition at line 5174 of file _filter_design.py.
iirdesign()
scipy.signal._filter_design.iirdesign (wp, ws, gpass, gstop, analog = False, ftype = 'ellip', output = 'ba', fs = None)
Complete IIR digital and analog filter design.
Given passband and stopband frequencies and gains, construct an analog or
digital IIR filter of minimum order for a given basic type. Return the
output in numerator, denominator ('ba'), pole-zero ('zpk') or second order
sections ('sos') form.
Parameters
----------
wp, ws : float or array like, shape (2,)
    Passband and stopband edge frequencies. Possible values are scalars
    (for lowpass and highpass filters) or ranges (for bandpass and bandstop
    filters).
    For digital filters, these are in the same units as `fs`. By default,
    `fs` is 2 half-cycles/sample, so these are normalized from 0 to 1,
    where 1 is the Nyquist frequency. For example:
        - Lowpass:   wp = 0.2,          ws = 0.3
        - Highpass:  wp = 0.3,          ws = 0.2
        - Bandpass:  wp = [0.2, 0.5],   ws = [0.1, 0.6]
        - Bandstop:  wp = [0.1, 0.6],   ws = [0.2, 0.5]
    For analog filters, `wp` and `ws` are angular frequencies (e.g., rad/s).
    Note, that for bandpass and bandstop filters passband must lie strictly
    inside stopband or vice versa.
gpass : float
    The maximum loss in the passband (dB).
gstop : float
    The minimum attenuation in the stopband (dB).
analog : bool, optional
    When True, return an analog filter, otherwise a digital filter is
    returned.
ftype : str, optional
    The type of IIR filter to design:
        - Butterworth   : 'butter'
        - Chebyshev I   : 'cheby1'
        - Chebyshev II  : 'cheby2'
        - Cauer/elliptic: 'ellip'
output : {'ba', 'zpk', 'sos'}, optional
    Filter form of the output:
        - second-order sections (recommended): 'sos'
        - numerator/denominator (default)    : 'ba'
        - pole-zero                          : 'zpk'
    In general the second-order sections ('sos') form  is
    recommended because inferring the coefficients for the
    numerator/denominator form ('ba') suffers from numerical
    instabilities. For reasons of backward compatibility the default
    form is the numerator/denominator form ('ba'), where the 'b'
    and the 'a' in 'ba' refer to the commonly used names of the
    coefficients used.
    Note: Using the second-order sections form ('sos') is sometimes
    associated with additional computational costs: for
    data-intense use cases it is therefore recommended to also
    investigate the numerator/denominator form ('ba').
fs : float, optional
    The sampling frequency of the digital system.
    .. versionadded:: 1.2.0
Returns
-------
b, a : ndarray, ndarray
    Numerator (`b`) and denominator (`a`) polynomials of the IIR filter.
    Only returned if ``output='ba'``.
z, p, k : ndarray, ndarray, float
    Zeros, poles, and system gain of the IIR filter transfer
    function.  Only returned if ``output='zpk'``.
sos : ndarray
    Second-order sections representation of the IIR filter.
    Only returned if ``output='sos'``.
See Also
--------
butter : Filter design using order and critical points
cheby1, cheby2, ellip, bessel
buttord : Find order and critical points from passband and stopband spec
cheb1ord, cheb2ord, ellipord
iirfilter : General filter design using order and critical frequencies
Notes
-----
The ``'sos'`` output parameter was added in 0.16.0.
Examples
--------
>>> import numpy as np
>>> from scipy import signal
>>> import matplotlib.pyplot as plt
>>> import matplotlib.ticker
>>> wp = 0.2
>>> ws = 0.3
>>> gpass = 1
>>> gstop = 40
>>> system = signal.iirdesign(wp, ws, gpass, gstop)
>>> w, h = signal.freqz(*system)
>>> fig, ax1 = plt.subplots()
>>> ax1.set_title('Digital filter frequency response')
>>> ax1.plot(w, 20 * np.log10(abs(h)), 'b')
>>> ax1.set_ylabel('Amplitude [dB]', color='b')
>>> ax1.set_xlabel('Frequency [rad/sample]')
>>> ax1.grid(True)
>>> ax1.set_ylim([-120, 20])
>>> ax2 = ax1.twinx()
>>> angles = np.unwrap(np.angle(h))
>>> ax2.plot(w, angles, 'g')
>>> ax2.set_ylabel('Angle (radians)', color='g')
>>> ax2.grid(True)
>>> ax2.axis('tight')
>>> ax2.set_ylim([-6, 1])
>>> nticks = 8
>>> ax1.yaxis.set_major_locator(matplotlib.ticker.LinearLocator(nticks))
>>> ax2.yaxis.set_major_locator(matplotlib.ticker.LinearLocator(nticks))
Definition at line 2188 of file _filter_design.py.
References iirfilter().
iirfilter()
scipy.signal._filter_design.iirfilter (N, Wn, rp = None, rs = None, btype = 'band', analog = False, ftype = 'butter', output = 'ba', fs = None)
IIR digital and analog filter design given order and critical points.
Design an Nth-order digital or analog filter and return the filter
coefficients.
Parameters
----------
N : int
    The order of the filter.
Wn : array_like
    A scalar or length-2 sequence giving the critical frequencies.
    For digital filters, `Wn` are in the same units as `fs`. By default,
    `fs` is 2 half-cycles/sample, so these are normalized from 0 to 1,
    where 1 is the Nyquist frequency. (`Wn` is thus in
    half-cycles / sample.)
    For analog filters, `Wn` is an angular frequency (e.g., rad/s).
    When Wn is a length-2 sequence, ``Wn[0]`` must be less than ``Wn[1]``.
rp : float, optional
    For Chebyshev and elliptic filters, provides the maximum ripple
    in the passband. (dB)
rs : float, optional
    For Chebyshev and elliptic filters, provides the minimum attenuation
    in the stop band. (dB)
btype : {'bandpass', 'lowpass', 'highpass', 'bandstop'}, optional
    The type of filter.  Default is 'bandpass'.
analog : bool, optional
    When True, return an analog filter, otherwise a digital filter is
    returned.
ftype : str, optional
    The type of IIR filter to design:
        - Butterworth   : 'butter'
        - Chebyshev I   : 'cheby1'
        - Chebyshev II  : 'cheby2'
        - Cauer/elliptic: 'ellip'
        - Bessel/Thomson: 'bessel'
output : {'ba', 'zpk', 'sos'}, optional
    Filter form of the output:
        - second-order sections (recommended): 'sos'
        - numerator/denominator (default)    : 'ba'
        - pole-zero                          : 'zpk'
    In general the second-order sections ('sos') form  is
    recommended because inferring the coefficients for the
    numerator/denominator form ('ba') suffers from numerical
    instabilities. For reasons of backward compatibility the default
    form is the numerator/denominator form ('ba'), where the 'b'
    and the 'a' in 'ba' refer to the commonly used names of the
    coefficients used.
    Note: Using the second-order sections form ('sos') is sometimes
    associated with additional computational costs: for
    data-intense use cases it is therefore recommended to also
    investigate the numerator/denominator form ('ba').
fs : float, optional
    The sampling frequency of the digital system.
    .. versionadded:: 1.2.0
Returns
-------
b, a : ndarray, ndarray
    Numerator (`b`) and denominator (`a`) polynomials of the IIR filter.
    Only returned if ``output='ba'``.
z, p, k : ndarray, ndarray, float
    Zeros, poles, and system gain of the IIR filter transfer
    function.  Only returned if ``output='zpk'``.
sos : ndarray
    Second-order sections representation of the IIR filter.
    Only returned if ``output='sos'``.
See Also
--------
butter : Filter design using order and critical points
cheby1, cheby2, ellip, bessel
buttord : Find order and critical points from passband and stopband spec
cheb1ord, cheb2ord, ellipord
iirdesign : General filter design using passband and stopband spec
Notes
-----
The ``'sos'`` output parameter was added in 0.16.0.
Examples
--------
Generate a 17th-order Chebyshev II analog bandpass filter from 50 Hz to
200 Hz and plot the frequency response:
>>> import numpy as np
>>> from scipy import signal
>>> import matplotlib.pyplot as plt
>>> b, a = signal.iirfilter(17, [2*np.pi*50, 2*np.pi*200], rs=60,
...                         btype='band', analog=True, ftype='cheby2')
>>> w, h = signal.freqs(b, a, 1000)
>>> fig = plt.figure()
>>> ax = fig.add_subplot(1, 1, 1)
>>> ax.semilogx(w / (2*np.pi), 20 * np.log10(np.maximum(abs(h), 1e-5)))
>>> ax.set_title('Chebyshev Type II bandpass frequency response')
>>> ax.set_xlabel('Frequency [Hz]')
>>> ax.set_ylabel('Amplitude [dB]')
>>> ax.axis((10, 1000, -100, 10))
>>> ax.grid(which='both', axis='both')
>>> plt.show()
Create a digital filter with the same properties, in a system with
sampling rate of 2000 Hz, and plot the frequency response. (Second-order
sections implementation is required to ensure stability of a filter of
this order):
>>> sos = signal.iirfilter(17, [50, 200], rs=60, btype='band',
...                        analog=False, ftype='cheby2', fs=2000,
...                        output='sos')
>>> w, h = signal.sosfreqz(sos, 2000, fs=2000)
>>> fig = plt.figure()
>>> ax = fig.add_subplot(1, 1, 1)
>>> ax.semilogx(w, 20 * np.log10(np.maximum(abs(h), 1e-5)))
>>> ax.set_title('Chebyshev Type II bandpass frequency response')
>>> ax.set_xlabel('Frequency [Hz]')
>>> ax.set_ylabel('Amplitude [dB]')
>>> ax.axis((10, 1000, -100, 10))
>>> ax.grid(which='both', axis='both')
>>> plt.show()
Definition at line 2361 of file _filter_design.py.
References bilinear_zpk(), lp2bp_zpk(), lp2bs_zpk(), lp2hp_zpk(), lp2lp_zpk(), zpk2sos(), and zpk2tf().
Referenced by bessel(), butter(), cheby1(), cheby2(), ellip(), and iirdesign().
iirnotch()
scipy.signal._filter_design.iirnotch (w0, Q, fs = 2.0)
Design second-order IIR notch digital filter.
A notch filter is a band-stop filter with a narrow bandwidth
(high quality factor). It rejects a narrow frequency band and
leaves the rest of the spectrum little changed.
Parameters
----------
w0 : float
    Frequency to remove from a signal. If `fs` is specified, this is in
    the same units as `fs`. By default, it is a normalized scalar that must
    satisfy  ``0 < w0 < 1``, with ``w0 = 1`` corresponding to half of the
    sampling frequency.
Q : float
    Quality factor. Dimensionless parameter that characterizes
    notch filter -3 dB bandwidth ``bw`` relative to its center
    frequency, ``Q = w0/bw``.
fs : float, optional
    The sampling frequency of the digital system.
    .. versionadded:: 1.2.0
Returns
-------
b, a : ndarray, ndarray
    Numerator (``b``) and denominator (``a``) polynomials
    of the IIR filter.
See Also
--------
iirpeak
Notes
-----
.. versionadded:: 0.19.0
References
----------
.. [1] Sophocles J. Orfanidis, "Introduction To Signal Processing",
       Prentice-Hall, 1996
Examples
--------
Design and plot filter to remove the 60 Hz component from a
signal sampled at 200 Hz, using a quality factor Q = 30
>>> from scipy import signal
>>> import matplotlib.pyplot as plt
>>> import numpy as np
>>> fs = 200.0  # Sample frequency (Hz)
>>> f0 = 60.0  # Frequency to be removed from signal (Hz)
>>> Q = 30.0  # Quality factor
>>> # Design notch filter
>>> b, a = signal.iirnotch(f0, Q, fs)
>>> # Frequency response
>>> freq, h = signal.freqz(b, a, fs=fs)
>>> # Plot
>>> fig, ax = plt.subplots(2, 1, figsize=(8, 6))
>>> ax[0].plot(freq, 20*np.log10(abs(h)), color='blue')
>>> ax[0].set_title("Frequency Response")
>>> ax[0].set_ylabel("Amplitude (dB)", color='blue')
>>> ax[0].set_xlim([0, 100])
>>> ax[0].set_ylim([-25, 10])
>>> ax[0].grid(True)
>>> ax[1].plot(freq, np.unwrap(np.angle(h))*180/np.pi, color='green')
>>> ax[1].set_ylabel("Angle (degrees)", color='green')
>>> ax[1].set_xlabel("Frequency (Hz)")
>>> ax[1].set_xlim([0, 100])
>>> ax[1].set_yticks([-90, -60, -30, 0, 30, 60, 90])
>>> ax[1].set_ylim([-90, 90])
>>> ax[1].grid(True)
>>> plt.show()
Definition at line 4937 of file _filter_design.py.
References _design_notch_peak_filter().
iirpeak()
scipy.signal._filter_design.iirpeak (w0, Q, fs = 2.0)
Design second-order IIR peak (resonant) digital filter.
A peak filter is a band-pass filter with a narrow bandwidth
(high quality factor). It rejects components outside a narrow
frequency band.
Parameters
----------
w0 : float
    Frequency to be retained in a signal. If `fs` is specified, this is in
    the same units as `fs`. By default, it is a normalized scalar that must
    satisfy  ``0 < w0 < 1``, with ``w0 = 1`` corresponding to half of the
    sampling frequency.
Q : float
    Quality factor. Dimensionless parameter that characterizes
    peak filter -3 dB bandwidth ``bw`` relative to its center
    frequency, ``Q = w0/bw``.
fs : float, optional
    The sampling frequency of the digital system.
    .. versionadded:: 1.2.0
Returns
-------
b, a : ndarray, ndarray
    Numerator (``b``) and denominator (``a``) polynomials
    of the IIR filter.
See Also
--------
iirnotch
Notes
-----
.. versionadded:: 0.19.0
References
----------
.. [1] Sophocles J. Orfanidis, "Introduction To Signal Processing",
       Prentice-Hall, 1996
Examples
--------
Design and plot filter to remove the frequencies other than the 300 Hz
component from a signal sampled at 1000 Hz, using a quality factor Q = 30
>>> import numpy as np
>>> from scipy import signal
>>> import matplotlib.pyplot as plt
>>> fs = 1000.0  # Sample frequency (Hz)
>>> f0 = 300.0  # Frequency to be retained (Hz)
>>> Q = 30.0  # Quality factor
>>> # Design peak filter
>>> b, a = signal.iirpeak(f0, Q, fs)
>>> # Frequency response
>>> freq, h = signal.freqz(b, a, fs=fs)
>>> # Plot
>>> fig, ax = plt.subplots(2, 1, figsize=(8, 6))
>>> ax[0].plot(freq, 20*np.log10(np.maximum(abs(h), 1e-5)), color='blue')
>>> ax[0].set_title("Frequency Response")
>>> ax[0].set_ylabel("Amplitude (dB)", color='blue')
>>> ax[0].set_xlim([0, 500])
>>> ax[0].set_ylim([-50, 10])
>>> ax[0].grid(True)
>>> ax[1].plot(freq, np.unwrap(np.angle(h))*180/np.pi, color='green')
>>> ax[1].set_ylabel("Angle (degrees)", color='green')
>>> ax[1].set_xlabel("Frequency (Hz)")
>>> ax[1].set_xlim([0, 500])
>>> ax[1].set_yticks([-90, -60, -30, 0, 30, 60, 90])
>>> ax[1].set_ylim([-90, 90])
>>> ax[1].grid(True)
>>> plt.show()
Definition at line 5018 of file _filter_design.py.
References _design_notch_peak_filter().
lp2bp()
scipy.signal._filter_design.lp2bp (b, a, wo = 1.0, bw = 1.0)
Transform a lowpass filter prototype to a bandpass filter.
Return an analog band-pass filter with center frequency `wo` and
bandwidth `bw` from an analog low-pass filter prototype with unity
cutoff frequency, in transfer function ('ba') representation.
Parameters
----------
b : array_like
    Numerator polynomial coefficients.
a : array_like
    Denominator polynomial coefficients.
wo : float
    Desired passband center, as angular frequency (e.g., rad/s).
    Defaults to no change.
bw : float
    Desired passband width, as angular frequency (e.g., rad/s).
    Defaults to 1.
Returns
-------
b : array_like
    Numerator polynomial coefficients of the transformed band-pass filter.
a : array_like
    Denominator polynomial coefficients of the transformed band-pass filter.
See Also
--------
lp2lp, lp2hp, lp2bs, bilinear
lp2bp_zpk
Notes
-----
This is derived from the s-plane substitution
.. math:: s \rightarrow \frac{s^2 + {\omega_0}^2}{s \cdot \mathrm{BW}}
This is the "wideband" transformation, producing a passband with
geometric (log frequency) symmetry about `wo`.
Examples
--------
>>> from scipy import signal
>>> import matplotlib.pyplot as plt
>>> lp = signal.lti([1.0], [1.0, 1.0])
>>> bp = signal.lti(*signal.lp2bp(lp.num, lp.den))
>>> w, mag_lp, p_lp = lp.bode()
>>> w, mag_bp, p_bp = bp.bode(w)
>>> plt.plot(w, mag_lp, label='Lowpass')
>>> plt.plot(w, mag_bp, label='Bandpass')
>>> plt.semilogx()
>>> plt.grid(True)
>>> plt.xlabel('Frequency [rad/s]')
>>> plt.ylabel('Magnitude [dB]')
>>> plt.legend()
Definition at line 1915 of file _filter_design.py.
References normalize().
lp2bp_zpk()
scipy.signal._filter_design.lp2bp_zpk (z, p, k, wo = 1.0, bw = 1.0)
Transform a lowpass filter prototype to a bandpass filter.
Return an analog band-pass filter with center frequency `wo` and
bandwidth `bw` from an analog low-pass filter prototype with unity
cutoff frequency, using zeros, poles, and gain ('zpk') representation.
Parameters
----------
z : array_like
    Zeros of the analog filter transfer function.
p : array_like
    Poles of the analog filter transfer function.
k : float
    System gain of the analog filter transfer function.
wo : float
    Desired passband center, as angular frequency (e.g., rad/s).
    Defaults to no change.
bw : float
    Desired passband width, as angular frequency (e.g., rad/s).
    Defaults to 1.
Returns
-------
z : ndarray
    Zeros of the transformed band-pass filter transfer function.
p : ndarray
    Poles of the transformed band-pass filter transfer function.
k : float
    System gain of the transformed band-pass filter.
See Also
--------
lp2lp_zpk, lp2hp_zpk, lp2bs_zpk, bilinear
lp2bp
Notes
-----
This is derived from the s-plane substitution
.. math:: s \rightarrow \frac{s^2 + {\omega_0}^2}{s \cdot \mathrm{BW}}
This is the "wideband" transformation, producing a passband with
geometric (log frequency) symmetry about `wo`.
.. versionadded:: 1.1.0
Definition at line 2821 of file _filter_design.py.
References _relative_degree().
Referenced by iirfilter().
lp2bs()
scipy.signal._filter_design.lp2bs (b, a, wo = 1.0, bw = 1.0)
Transform a lowpass filter prototype to a bandstop filter.
Return an analog band-stop filter with center frequency `wo` and
bandwidth `bw` from an analog low-pass filter prototype with unity
cutoff frequency, in transfer function ('ba') representation.
Parameters
----------
b : array_like
    Numerator polynomial coefficients.
a : array_like
    Denominator polynomial coefficients.
wo : float
    Desired stopband center, as angular frequency (e.g., rad/s).
    Defaults to no change.
bw : float
    Desired stopband width, as angular frequency (e.g., rad/s).
    Defaults to 1.
Returns
-------
b : array_like
    Numerator polynomial coefficients of the transformed band-stop filter.
a : array_like
    Denominator polynomial coefficients of the transformed band-stop filter.
See Also
--------
lp2lp, lp2hp, lp2bp, bilinear
lp2bs_zpk
Notes
-----
This is derived from the s-plane substitution
.. math:: s \rightarrow \frac{s \cdot \mathrm{BW}}{s^2 + {\omega_0}^2}
This is the "wideband" transformation, producing a stopband with
geometric (log frequency) symmetry about `wo`.
Examples
--------
>>> from scipy import signal
>>> import matplotlib.pyplot as plt
>>> lp = signal.lti([1.0], [1.0, 1.5])
>>> bs = signal.lti(*signal.lp2bs(lp.num, lp.den))
>>> w, mag_lp, p_lp = lp.bode()
>>> w, mag_bs, p_bs = bs.bode(w)
>>> plt.plot(w, mag_lp, label='Lowpass')
>>> plt.plot(w, mag_bs, label='Bandstop')
>>> plt.semilogx()
>>> plt.grid(True)
>>> plt.xlabel('Frequency [rad/s]')
>>> plt.ylabel('Magnitude [dB]')
>>> plt.legend()
Definition at line 2004 of file _filter_design.py.
References normalize().
lp2bs_zpk()
scipy.signal._filter_design.lp2bs_zpk (z, p, k, wo = 1.0, bw = 1.0)
Transform a lowpass filter prototype to a bandstop filter.
Return an analog band-stop filter with center frequency `wo` and
stopband width `bw` from an analog low-pass filter prototype with unity
cutoff frequency, using zeros, poles, and gain ('zpk') representation.
Parameters
----------
z : array_like
    Zeros of the analog filter transfer function.
p : array_like
    Poles of the analog filter transfer function.
k : float
    System gain of the analog filter transfer function.
wo : float
    Desired stopband center, as angular frequency (e.g., rad/s).
    Defaults to no change.
bw : float
    Desired stopband width, as angular frequency (e.g., rad/s).
    Defaults to 1.
Returns
-------
z : ndarray
    Zeros of the transformed band-stop filter transfer function.
p : ndarray
    Poles of the transformed band-stop filter transfer function.
k : float
    System gain of the transformed band-stop filter.
See Also
--------
lp2lp_zpk, lp2hp_zpk, lp2bp_zpk, bilinear
lp2bs
Notes
-----
This is derived from the s-plane substitution
.. math:: s \rightarrow \frac{s \cdot \mathrm{BW}}{s^2 + {\omega_0}^2}
This is the "wideband" transformation, producing a stopband with
geometric (log frequency) symmetry about `wo`.
.. versionadded:: 1.1.0
Definition at line 2900 of file _filter_design.py.
References _relative_degree().
Referenced by iirfilter().
lp2hp()
scipy.signal._filter_design.lp2hp (b, a, wo = 1.0)
Transform a lowpass filter prototype to a highpass filter.
Return an analog high-pass filter with cutoff frequency `wo`
from an analog low-pass filter prototype with unity cutoff frequency, in
transfer function ('ba') representation.
Parameters
----------
b : array_like
    Numerator polynomial coefficients.
a : array_like
    Denominator polynomial coefficients.
wo : float
    Desired cutoff, as angular frequency (e.g., rad/s).
    Defaults to no change.
Returns
-------
b : array_like
    Numerator polynomial coefficients of the transformed high-pass filter.
a : array_like
    Denominator polynomial coefficients of the transformed high-pass filter.
See Also
--------
lp2lp, lp2bp, lp2bs, bilinear
lp2hp_zpk
Notes
-----
This is derived from the s-plane substitution
.. math:: s \rightarrow \frac{\omega_0}{s}
This maintains symmetry of the lowpass and highpass responses on a
logarithmic scale.
Examples
--------
>>> from scipy import signal
>>> import matplotlib.pyplot as plt
>>> lp = signal.lti([1.0], [1.0, 1.0])
>>> hp = signal.lti(*signal.lp2hp(lp.num, lp.den))
>>> w, mag_lp, p_lp = lp.bode()
>>> w, mag_hp, p_hp = hp.bode(w)
>>> plt.plot(w, mag_lp, label='Lowpass')
>>> plt.plot(w, mag_hp, label='Highpass')
>>> plt.semilogx()
>>> plt.grid(True)
>>> plt.xlabel('Frequency [rad/s]')
>>> plt.ylabel('Magnitude [dB]')
>>> plt.legend()
Definition at line 1832 of file _filter_design.py.
References normalize().
lp2hp_zpk()
scipy.signal._filter_design.lp2hp_zpk (z, p, k, wo = 1.0)
Transform a lowpass filter prototype to a highpass filter.
Return an analog high-pass filter with cutoff frequency `wo`
from an analog low-pass filter prototype with unity cutoff frequency,
using zeros, poles, and gain ('zpk') representation.
Parameters
----------
z : array_like
    Zeros of the analog filter transfer function.
p : array_like
    Poles of the analog filter transfer function.
k : float
    System gain of the analog filter transfer function.
wo : float
    Desired cutoff, as angular frequency (e.g., rad/s).
    Defaults to no change.
Returns
-------
z : ndarray
    Zeros of the transformed high-pass filter transfer function.
p : ndarray
    Poles of the transformed high-pass filter transfer function.
k : float
    System gain of the transformed high-pass filter.
See Also
--------
lp2lp_zpk, lp2bp_zpk, lp2bs_zpk, bilinear
lp2hp
Notes
-----
This is derived from the s-plane substitution
.. math:: s \rightarrow \frac{\omega_0}{s}
This maintains symmetry of the lowpass and highpass responses on a
logarithmic scale.
.. versionadded:: 1.1.0
Definition at line 2755 of file _filter_design.py.
References _relative_degree().
Referenced by iirfilter().
lp2lp()
scipy.signal._filter_design.lp2lp (b, a, wo = 1.0)
Transform a lowpass filter prototype to a different frequency.
Return an analog low-pass filter with cutoff frequency `wo`
from an analog low-pass filter prototype with unity cutoff frequency, in
transfer function ('ba') representation.
Parameters
----------
b : array_like
    Numerator polynomial coefficients.
a : array_like
    Denominator polynomial coefficients.
wo : float
    Desired cutoff, as angular frequency (e.g. rad/s).
    Defaults to no change.
Returns
-------
b : array_like
    Numerator polynomial coefficients of the transformed low-pass filter.
a : array_like
    Denominator polynomial coefficients of the transformed low-pass filter.
See Also
--------
lp2hp, lp2bp, lp2bs, bilinear
lp2lp_zpk
Notes
-----
This is derived from the s-plane substitution
.. math:: s \rightarrow \frac{s}{\omega_0}
Examples
--------
>>> from scipy import signal
>>> import matplotlib.pyplot as plt
>>> lp = signal.lti([1.0], [1.0, 1.0])
>>> lp2 = signal.lti(*signal.lp2lp(lp.num, lp.den, 2))
>>> w, mag_lp, p_lp = lp.bode()
>>> w, mag_lp2, p_lp2 = lp2.bode(w)
>>> plt.plot(w, mag_lp, label='Lowpass')
>>> plt.plot(w, mag_lp2, label='Transformed Lowpass')
>>> plt.semilogx()
>>> plt.grid(True)
>>> plt.xlabel('Frequency [rad/s]')
>>> plt.ylabel('Magnitude [dB]')
>>> plt.legend()
Definition at line 1760 of file _filter_design.py.
References normalize().
lp2lp_zpk()
scipy.signal._filter_design.lp2lp_zpk (z, p, k, wo = 1.0)
Transform a lowpass filter prototype to a different frequency.
Return an analog low-pass filter with cutoff frequency `wo`
from an analog low-pass filter prototype with unity cutoff frequency,
using zeros, poles, and gain ('zpk') representation.
Parameters
----------
z : array_like
    Zeros of the analog filter transfer function.
p : array_like
    Poles of the analog filter transfer function.
k : float
    System gain of the analog filter transfer function.
wo : float
    Desired cutoff, as angular frequency (e.g., rad/s).
    Defaults to no change.
Returns
-------
z : ndarray
    Zeros of the transformed low-pass filter transfer function.
p : ndarray
    Poles of the transformed low-pass filter transfer function.
k : float
    System gain of the transformed low-pass filter.
See Also
--------
lp2hp_zpk, lp2bp_zpk, lp2bs_zpk, bilinear
lp2lp
Notes
-----
This is derived from the s-plane substitution
.. math:: s \rightarrow \frac{s}{\omega_0}
.. versionadded:: 1.1.0
Definition at line 2695 of file _filter_design.py.
References _relative_degree().
Referenced by iirfilter().
maxflat()
scipy.signal._filter_design.maxflat ()
Definition at line 3623 of file _filter_design.py.
normalize()
scipy.signal._filter_design.normalize (b, a)
Normalize numerator/denominator of a continuous-time transfer function.
If values of `b` are too close to 0, they are removed. In that case, a
BadCoefficients warning is emitted.
Parameters
----------
b: array_like
    Numerator of the transfer function. Can be a 2-D array to normalize
    multiple transfer functions.
a: array_like
    Denominator of the transfer function. At most 1-D.
Returns
-------
num: array
    The numerator of the normalized transfer function. At least a 1-D
    array. A 2-D array if the input `num` is a 2-D array.
den: 1-D array
    The denominator of the normalized transfer function.
Notes
-----
Coefficients for both the numerator and denominator should be specified in
descending exponent order (e.g., ``s^2 + 3s + 5`` would be represented as
``[1, 3, 5]``).
Examples
--------
>>> from scipy.signal import normalize
Normalize the coefficients of the transfer function
``(3*s^2 - 2*s + 5) / (2*s^2 + 3*s + 1)``:
>>> b = [3, -2, 5]
>>> a = [2, 3, 1]
>>> normalize(b, a)
(array([ 1.5, -1. ,  2.5]), array([1. , 1.5, 0.5]))
A warning is generated if, for example, the first coefficient of
`b` is 0.  In the following example, the result is as expected:
>>> import warnings
>>> with warnings.catch_warnings(record=True) as w:
...     num, den = normalize([0, 3, 6], [2, -5, 4])
>>> num
array([1.5, 3. ])
>>> den
array([ 1. , -2.5,  2. ])
>>> print(w[0].message)
Badly conditioned filter coefficients (numerator): the results may be meaningless
Definition at line 1661 of file _filter_design.py.
References _align_nums().
Referenced by scipy.signal._ltisys.TransferFunction.__init__(), bilinear(), lp2bp(), lp2bs(), lp2hp(), lp2lp(), scipy.signal.tests.test_filter_design.TestNormalize.test_allclose(), scipy.signal._lti_conversion.tf2ss(), and tf2zpk().
sos2tf()
scipy.signal._filter_design.sos2tf (sos)
Return a single transfer function from a series of second-order sections
Parameters
----------
sos : array_like
    Array of second-order filter coefficients, must have shape
    ``(n_sections, 6)``. See `sosfilt` for the SOS filter format
    specification.
Returns
-------
b : ndarray
    Numerator polynomial coefficients.
a : ndarray
    Denominator polynomial coefficients.
Notes
-----
.. versionadded:: 0.16.0
Definition at line 1199 of file _filter_design.py.
sos2zpk()
scipy.signal._filter_design.sos2zpk (sos)
Return zeros, poles, and gain of a series of second-order sections
Parameters
----------
sos : array_like
    Array of second-order filter coefficients, must have shape
    ``(n_sections, 6)``. See `sosfilt` for the SOS filter format
    specification.
Returns
-------
z : ndarray
    Zeros of the transfer function.
p : ndarray
    Poles of the transfer function.
k : float
    System gain.
Notes
-----
The number of zeros and poles returned will be ``n_sections * 2``
even if some of these are (effectively) zero.
.. versionadded:: 0.16.0
Definition at line 1235 of file _filter_design.py.
References tf2zpk().
Referenced by scipy.signal.tests.test_filter_design.TestSos2Zpk.test_fewer_zeros().
sosfreqz()
scipy.signal._filter_design.sosfreqz (sos, worN = 512, whole = False, fs = 2*pi)
Compute the frequency response of a digital filter in SOS format.
Given `sos`, an array with shape (n, 6) of second order sections of
a digital filter, compute the frequency response of the system function::
           B0(z)   B1(z)         B{n-1}(z)
    H(z) = ----- * ----- * ... * ---------
           A0(z)   A1(z)         A{n-1}(z)
for z = exp(omega*1j), where B{k}(z) and A{k}(z) are numerator and
denominator of the transfer function of the k-th second order section.
Parameters
----------
sos : array_like
    Array of second-order filter coefficients, must have shape
    ``(n_sections, 6)``. Each row corresponds to a second-order
    section, with the first three columns providing the numerator
    coefficients and the last three providing the denominator
    coefficients.
worN : {None, int, array_like}, optional
    If a single integer, then compute at that many frequencies (default is
    N=512).  Using a number that is fast for FFT computations can result
    in faster computations (see Notes of `freqz`).
    If an array_like, compute the response at the frequencies given (must
    be 1-D). These are in the same units as `fs`.
whole : bool, optional
    Normally, frequencies are computed from 0 to the Nyquist frequency,
    fs/2 (upper-half of unit-circle). If `whole` is True, compute
    frequencies from 0 to fs.
fs : float, optional
    The sampling frequency of the digital system. Defaults to 2*pi
    radians/sample (so w is from 0 to pi).
    .. versionadded:: 1.2.0
Returns
-------
w : ndarray
    The frequencies at which `h` was computed, in the same units as `fs`.
    By default, `w` is normalized to the range [0, pi) (radians/sample).
h : ndarray
    The frequency response, as complex numbers.
See Also
--------
freqz, sosfilt
Notes
-----
.. versionadded:: 0.19.0
Examples
--------
Design a 15th-order bandpass filter in SOS format.
>>> from scipy import signal
>>> import numpy as np
>>> sos = signal.ellip(15, 0.5, 60, (0.2, 0.4), btype='bandpass',
...                    output='sos')
Compute the frequency response at 1500 points from DC to Nyquist.
>>> w, h = signal.sosfreqz(sos, worN=1500)
Plot the response.
>>> import matplotlib.pyplot as plt
>>> plt.subplot(2, 1, 1)
>>> db = 20*np.log10(np.maximum(np.abs(h), 1e-5))
>>> plt.plot(w/np.pi, db)
>>> plt.ylim(-75, 5)
>>> plt.grid(True)
>>> plt.yticks([0, -20, -40, -60])
>>> plt.ylabel('Gain [dB]')
>>> plt.title('Frequency Response')
>>> plt.subplot(2, 1, 2)
>>> plt.plot(w/np.pi, np.angle(h))
>>> plt.grid(True)
>>> plt.yticks([-np.pi, -0.5*np.pi, 0, 0.5*np.pi, np.pi],
...            [r'$-\pi$', r'$-\pi/2$', '0', r'$\pi/2$', r'$\pi$'])
>>> plt.ylabel('Phase [rad]')
>>> plt.xlabel('Normalized frequency (1.0 = Nyquist)')
>>> plt.show()
If the same filter is implemented as a single transfer function,
numerical error corrupts the frequency response:
>>> b, a = signal.ellip(15, 0.5, 60, (0.2, 0.4), btype='bandpass',
...                    output='ba')
>>> w, h = signal.freqz(b, a, worN=1500)
>>> plt.subplot(2, 1, 1)
>>> db = 20*np.log10(np.maximum(np.abs(h), 1e-5))
>>> plt.plot(w/np.pi, db)
>>> plt.ylim(-75, 5)
>>> plt.grid(True)
>>> plt.yticks([0, -20, -40, -60])
>>> plt.ylabel('Gain [dB]')
>>> plt.title('Frequency Response')
>>> plt.subplot(2, 1, 2)
>>> plt.plot(w/np.pi, np.angle(h))
>>> plt.grid(True)
>>> plt.yticks([-np.pi, -0.5*np.pi, 0, 0.5*np.pi, np.pi],
...            [r'$-\pi$', r'$-\pi/2$', '0', r'$\pi/2$', r'$\pi$'])
>>> plt.ylabel('Phase [rad]')
>>> plt.xlabel('Normalized frequency (1.0 = Nyquist)')
>>> plt.show()
Definition at line 731 of file _filter_design.py.
References _validate_sos(), and freqz().
tf2sos()
scipy.signal._filter_design.tf2sos (b, a, pairing = None, * , analog = False)
Return second-order sections from transfer function representation
Parameters
----------
b : array_like
    Numerator polynomial coefficients.
a : array_like
    Denominator polynomial coefficients.
pairing : {None, 'nearest', 'keep_odd', 'minimal'}, optional
    The method to use to combine pairs of poles and zeros into sections.
    See `zpk2sos` for information and restrictions on `pairing` and
    `analog` arguments.
analog : bool, optional
    If True, system is analog, otherwise discrete.
    .. versionadded:: 1.8.0
Returns
-------
sos : ndarray
    Array of second-order filter coefficients, with shape
    ``(n_sections, 6)``. See `sosfilt` for the SOS filter format
    specification.
See Also
--------
zpk2sos, sosfilt
Notes
-----
It is generally discouraged to convert from TF to SOS format, since doing
so usually will not improve numerical precision errors. Instead, consider
designing filters in ZPK format and converting directly to SOS. TF is
converted to SOS by first converting to ZPK format, then converting
ZPK to SOS.
.. versionadded:: 0.16.0
Definition at line 1156 of file _filter_design.py.
References tf2zpk(), and zpk2sos().
Referenced by scipy.signal.tests.test_signaltools.assert_allclose_cast(), and scipy.signal.tests.test_signaltools.cast_tf2sos().
tf2zpk()
scipy.signal._filter_design.tf2zpk (b, a)
Return zero, pole, gain (z, p, k) representation from a numerator,
denominator representation of a linear filter.
Parameters
----------
b : array_like
    Numerator polynomial coefficients.
a : array_like
    Denominator polynomial coefficients.
Returns
-------
z : ndarray
    Zeros of the transfer function.
p : ndarray
    Poles of the transfer function.
k : float
    System gain.
Notes
-----
If some values of `b` are too close to 0, they are removed. In that case,
a BadCoefficients warning is emitted.
The `b` and `a` arrays are interpreted as coefficients for positive,
descending powers of the transfer function variable. So the inputs
:math:`b = [b_0, b_1, ..., b_M]` and :math:`a =[a_0, a_1, ..., a_N]`
can represent an analog filter of the form:
.. math::
    H(s) = \frac
    {b_0 s^M + b_1 s^{(M-1)} + \cdots + b_M}
    {a_0 s^N + a_1 s^{(N-1)} + \cdots + a_N}
or a discrete-time filter of the form:
.. math::
    H(z) = \frac
    {b_0 z^M + b_1 z^{(M-1)} + \cdots + b_M}
    {a_0 z^N + a_1 z^{(N-1)} + \cdots + a_N}
This "positive powers" form is found more commonly in controls
engineering. If `M` and `N` are equal (which is true for all filters
generated by the bilinear transform), then this happens to be equivalent
to the "negative powers" discrete-time form preferred in DSP:
.. math::
    H(z) = \frac
    {b_0 + b_1 z^{-1} + \cdots + b_M z^{-M}}
    {a_0 + a_1 z^{-1} + \cdots + a_N z^{-N}}
Although this is true for common filters, remember that this is not true
in the general case. If `M` and `N` are not equal, the discrete-time
transfer function coefficients must first be converted to the "positive
powers" form before finding the poles and zeros.
Definition at line 1026 of file _filter_design.py.
References normalize().
Referenced by sos2zpk(), scipy.signal._lti_conversion.ss2zpk(), tf2sos(), and scipy.signal._ltisys.TransferFunction.to_zpk().
yulewalk()
scipy.signal._filter_design.yulewalk ()
Definition at line 3627 of file _filter_design.py.
zpk2sos()
scipy.signal._filter_design.zpk2sos (z, p, k, pairing = None, * , analog = False)
Return second-order sections from zeros, poles, and gain of a system
Parameters
----------
z : array_like
    Zeros of the transfer function.
p : array_like
    Poles of the transfer function.
k : float
    System gain.
pairing : {None, 'nearest', 'keep_odd', 'minimal'}, optional
    The method to use to combine pairs of poles and zeros into sections.
    If analog is False and pairing is None, pairing is set to 'nearest';
    if analog is True, pairing must be 'minimal', and is set to that if
    it is None.
analog : bool, optional
    If True, system is analog, otherwise discrete.
    .. versionadded:: 1.8.0
Returns
-------
sos : ndarray
    Array of second-order filter coefficients, with shape
    ``(n_sections, 6)``. See `sosfilt` for the SOS filter format
    specification.
See Also
--------
sosfilt
Notes
-----
The algorithm used to convert ZPK to SOS format is designed to
minimize errors due to numerical precision issues. The pairing
algorithm attempts to minimize the peak gain of each biquadratic
section. This is done by pairing poles with the nearest zeros, starting
with the poles closest to the unit circle for discrete-time systems, and
poles closest to the imaginary axis for continuous-time systems.
``pairing='minimal'`` outputs may not be suitable for `sosfilt`,
and ``analog=True`` outputs will never be suitable for `sosfilt`.
*Algorithms*
The steps in the ``pairing='nearest'``, ``pairing='keep_odd'``,
and ``pairing='minimal'`` algorithms are mostly shared. The
``'nearest'`` algorithm attempts to minimize the peak gain, while
``'keep_odd'`` minimizes peak gain under the constraint that
odd-order systems should retain one section as first order.
``'minimal'`` is similar to ``'keep_odd'``, but no additional
poles or zeros are introduced
The algorithm steps are as follows:
As a pre-processing step for ``pairing='nearest'``,
``pairing='keep_odd'``, add poles or zeros to the origin as
necessary to obtain the same number of poles and zeros for
pairing.  If ``pairing == 'nearest'`` and there are an odd number
of poles, add an additional pole and a zero at the origin.
The following steps are then iterated over until no more poles or
zeros remain:
1. Take the (next remaining) pole (complex or real) closest to the
   unit circle (or imaginary axis, for ``analog=True``) to
   begin a new filter section.
2. If the pole is real and there are no other remaining real poles [#]_,
   add the closest real zero to the section and leave it as a first
   order section. Note that after this step we are guaranteed to be
   left with an even number of real poles, complex poles, real zeros,
   and complex zeros for subsequent pairing iterations.
3. Else:
    1. If the pole is complex and the zero is the only remaining real
       zero*, then pair the pole with the *next* closest zero
       (guaranteed to be complex). This is necessary to ensure that
       there will be a real zero remaining to eventually create a
       first-order section (thus keeping the odd order).
    2. Else pair the pole with the closest remaining zero (complex or
       real).
    3. Proceed to complete the second-order section by adding another
       pole and zero to the current pole and zero in the section:
        1. If the current pole and zero are both complex, add their
           conjugates.
        2. Else if the pole is complex and the zero is real, add the
           conjugate pole and the next closest real zero.
        3. Else if the pole is real and the zero is complex, add the
           conjugate zero and the real pole closest to those zeros.
        4. Else (we must have a real pole and real zero) add the next
           real pole closest to the unit circle, and then add the real
           zero closest to that pole.
.. [#] This conditional can only be met for specific odd-order inputs
       with the ``pairing = 'keep_odd'`` or ``'minimal'`` methods.
.. versionadded:: 0.16.0
Examples
--------
Design a 6th order low-pass elliptic digital filter for a system with a
sampling rate of 8000 Hz that has a pass-band corner frequency of
1000 Hz. The ripple in the pass-band should not exceed 0.087 dB, and
the attenuation in the stop-band should be at least 90 dB.
In the following call to `ellip`, we could use ``output='sos'``,
but for this example, we'll use ``output='zpk'``, and then convert
to SOS format with `zpk2sos`:
>>> from scipy import signal
>>> import numpy as np
>>> z, p, k = signal.ellip(6, 0.087, 90, 1000/(0.5*8000), output='zpk')
Now convert to SOS format.
>>> sos = signal.zpk2sos(z, p, k)
The coefficients of the numerators of the sections:
>>> sos[:, :3]
array([[0.0014152 , 0.00248677, 0.0014152 ],
       [1.        , 0.72976874, 1.        ],
       [1.        , 0.17607852, 1.        ]])
The symmetry in the coefficients occurs because all the zeros are on the
unit circle.
The coefficients of the denominators of the sections:
>>> sos[:, 3:]
array([[ 1.        , -1.32544025,  0.46989976],
       [ 1.        , -1.26118294,  0.62625924],
       [ 1.        , -1.2570723 ,  0.8619958 ]])
The next example shows the effect of the `pairing` option.  We have a
system with three poles and three zeros, so the SOS array will have
shape (2, 6). The means there is, in effect, an extra pole and an extra
zero at the origin in the SOS representation.
>>> z1 = np.array([-1, -0.5-0.5j, -0.5+0.5j])
>>> p1 = np.array([0.75, 0.8+0.1j, 0.8-0.1j])
With ``pairing='nearest'`` (the default), we obtain
>>> signal.zpk2sos(z1, p1, 1)
array([[ 1.  ,  1.  ,  0.5 ,  1.  , -0.75,  0.  ],
       [ 1.  ,  1.  ,  0.  ,  1.  , -1.6 ,  0.65]])
The first section has the zeros {-0.5-0.05j, -0.5+0.5j} and the poles
{0, 0.75}, and the second section has the zeros {-1, 0} and poles
{0.8+0.1j, 0.8-0.1j}. Note that the extra pole and zero at the origin
have been assigned to different sections.
With ``pairing='keep_odd'``, we obtain:
>>> signal.zpk2sos(z1, p1, 1, pairing='keep_odd')
array([[ 1.  ,  1.  ,  0.  ,  1.  , -0.75,  0.  ],
       [ 1.  ,  1.  ,  0.5 ,  1.  , -1.6 ,  0.65]])
The extra pole and zero at the origin are in the same section.
The first section is, in effect, a first-order section.
With ``pairing='minimal'``, the first-order section doesn't have
the extra pole and zero at the origin:
>>> signal.zpk2sos(z1, p1, 1, pairing='minimal')
array([[ 0.  ,  1.  ,  1.  ,  0.  ,  1.  , -0.75],
       [ 1.  ,  1.  ,  0.5 ,  1.  , -1.6 ,  0.65]])
Definition at line 1297 of file _filter_design.py.
References _cplxreal(), _nearest_real_complex_idx(), and _single_zpksos().
Referenced by scipy.signal._signaltools.decimate(), iirfilter(), scipy.signal.tests.test_signaltools.TestSOSFiltFilt.test_equivalence(), and tf2sos().
zpk2tf()
scipy.signal._filter_design.zpk2tf (z, p, k)
Return polynomial transfer function representation from zeros and poles
Parameters
----------
z : array_like
    Zeros of the transfer function.
p : array_like
    Poles of the transfer function.
k : float
    System gain.
Returns
-------
b : ndarray
    Numerator polynomial coefficients.
a : ndarray
    Denominator polynomial coefficients.
Definition at line 1097 of file _filter_design.py.
Referenced by _single_zpksos(), scipy.signal.tests.test_signaltools.filtfilt_gust_opt(), iirfilter(), scipy.signal.tests.test_signaltools.TestSOSFiltFilt.test_equivalence(), scipy.signal.tests.test_filter_design.TestZpk2Tf.test_identity(), scipy.signal._ltisys.ZerosPolesGain.to_tf(), and scipy.signal._lti_conversion.zpk2ss().
Variable Documentation
__all__
list scipy.signal._filter_design.__all__ private
Initial value:
=  ['findfreqs', 'freqs', 'freqz', 'tf2zpk', 'zpk2tf', 'normalize',
           'lp2lp', 'lp2hp', 'lp2bp', 'lp2bs', 'bilinear', 'iirdesign',
           'iirfilter', 'butter', 'cheby1', 'cheby2', 'ellip', 'bessel',
           'band_stop_obj', 'buttord', 'cheb1ord', 'cheb2ord', 'ellipord',
           'buttap', 'cheb1ap', 'cheb2ap', 'ellipap', 'besselap',
           'BadCoefficients', 'freqs_zpk', 'freqz_zpk',
           'tf2sos', 'sos2tf', 'zpk2sos', 'sos2zpk', 'group_delay',
           'sosfreqz', 'iirnotch', 'iirpeak', 'bilinear_zpk',
           'lp2lp_zpk', 'lp2hp_zpk', 'lp2bp_zpk', 'lp2bs_zpk',
           'gammatone', 'iircomb']
Definition at line 21 of file _filter_design.py.
_ARC_JAC_SN_MAXITER
int scipy.signal._filter_design._ARC_JAC_SN_MAXITER = 10 protected
Definition at line 4460 of file _filter_design.py.
_ELLIPDEG_MMAX
int scipy.signal._filter_design._ELLIPDEG_MMAX = 7 protected
Definition at line 4425 of file _filter_design.py.
_POW10_LOG10
scipy.signal._filter_design._POW10_LOG10 = np.log(10) protected
Definition at line 4173 of file _filter_design.py.
abs
scipy.signal._filter_design.abs = absolute
Definition at line 38 of file _filter_design.py.
band_dict
dict scipy.signal._filter_design.band_dict
Initial value:
=  {'band': 'bandpass',
             'bandpass': 'bandpass',
             'pass': 'bandpass',
             'bp': 'bandpass',
             'bs': 'bandstop',
             'bandstop': 'bandstop',
             'bands': 'bandstop',
             'stop': 'bandstop',
             'l': 'lowpass',
             'low': 'lowpass',
             'lowpass': 'lowpass',
             'lp': 'lowpass',
             'high': 'highpass',
             'highpass': 'highpass',
             'h': 'highpass',
             'hp': 'highpass',
             }
Definition at line 5598 of file _filter_design.py.
bessel_norms
dict scipy.signal._filter_design.bessel_norms
Initial value:
=  {'bessel': 'phase',
                'bessel_phase': 'phase',
                'bessel_delay': 'delay',
                'bessel_mag': 'mag'}
Definition at line 5619 of file _filter_design.py.
EPSILON
int scipy.signal._filter_design.EPSILON = 2e-16
Definition at line 4422 of file _filter_design.py.
filter_dict
dict scipy.signal._filter_design.filter_dict
Initial value:
=  {'butter': [buttap, buttord],
               'butterworth': [buttap, buttord],
               'cauer': [ellipap, ellipord],
               'elliptic': [ellipap, ellipord],
               'ellip': [ellipap, ellipord],
               'bessel': [besselap],
               'bessel_phase': [besselap],
               'bessel_delay': [besselap],
               'bessel_mag': [besselap],
               'cheby1': [cheb1ap, cheb1ord],
               'chebyshev1': [cheb1ap, cheb1ord],
               'chebyshevi': [cheb1ap, cheb1ord],
               'cheby2': [cheb2ap, cheb2ord],
               'chebyshev2': [cheb2ap, cheb2ord],
               'chebyshevii': [cheb2ap, cheb2ord],
               }
Definition at line 5577 of file _filter_design.py.