Code Cloning Analysis: scipy.sparse.linalg.tests.test_norm.TestNorm Class Reference
scipy.sparse.linalg.tests.test_norm.TestNorm Class Reference
Public Member Functions
setup_method (self)
test_matrix_norm (self)
test_matrix_norm_axis (self)
test_vector_norm (self)
test_norm_exceptions (self)
Public Attributes
b = scipy.sparse.csr_matrix(b)
Detailed Description
Definition at line 27 of file test_norm.py.
Member Function Documentation
setup_method()
scipy.sparse.linalg.tests.test_norm.TestNorm.setup_method (self)
Definition at line 28 of file test_norm.py.
test_matrix_norm()
scipy.sparse.linalg.tests.test_norm.TestNorm.test_matrix_norm (self)
Definition at line 33 of file test_norm.py.
test_matrix_norm_axis()
scipy.sparse.linalg.tests.test_norm.TestNorm.test_matrix_norm_axis (self)
Definition at line 51 of file test_norm.py.
test_norm_exceptions()
scipy.sparse.linalg.tests.test_norm.TestNorm.test_norm_exceptions (self)
Definition at line 70 of file test_norm.py.
test_vector_norm()
scipy.sparse.linalg.tests.test_norm.TestNorm.test_vector_norm (self)
Definition at line 60 of file test_norm.py.
Member Data Documentation
b
scipy.sparse.linalg.tests.test_norm.TestNorm.b = scipy.sparse.csr_matrix(b)
Definition at line 31 of file test_norm.py.
Referenced by scipy.stats._continuous_distns.rv_histogram.__init__(), scipy.stats._discrete_distns.bernoulli_gen._get_support(), scipy.stats._distn_infrastructure.rv_generic._get_support(), scipy.stats._distn_infrastructure.rv_sample._get_support(), scipy.stats._distn_infrastructure.rv_continuous._updated_ctor_param(), scipy.stats._distn_infrastructure.rv_discrete._updated_ctor_param(), sklearn.tests.test_pipeline.NoTrans.get_params(), scipy.stats._page_trend_test._PageL.p_l_k_1(), scipy.stats._page_trend_test._PageL.pmf(), scipy.stats._page_trend_test._PageL.set_k(), sklearn.utils.tests.test_estimator_checks.ModifiesAnotherValue.set_params(), scipy.stats._page_trend_test._PageL.sf(), and scipy.special._mptestutils.Arg.values().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/sparse/linalg/tests/test_norm.py