Code Cloning Analysis: numpy.core.tests.test_dtype.TestDTypeMakeCanonical Class Reference
numpy.core.tests.test_dtype.TestDTypeMakeCanonical Class Reference
Public Member Functions
check_canonical (self, dtype, canonical)
test_simple (self)
test_object_flag_not_inherited (self)
test_make_canonical_hypothesis (self, dtype)
test_structured (self, dtype)
Detailed Description
Definition at line 1159 of file test_dtype.py.
Member Function Documentation
check_canonical()
numpy.core.tests.test_dtype.TestDTypeMakeCanonical.check_canonical (self, dtype, canonical)
Check most properties relevant to "canonical" versions of a dtype,
which is mainly native byte order for datatypes supporting this.
The main work is checking structured dtypes with fields, where we
reproduce most the actual logic used in the C-code.
Definition at line 1160 of file test_dtype.py.
References check_canonical(), and numpy.core.fromnumeric.max().
Referenced by check_canonical().
test_make_canonical_hypothesis()
numpy.core.tests.test_dtype.TestDTypeMakeCanonical.test_make_canonical_hypothesis (self, dtype)
Definition at line 1248 of file test_dtype.py.
test_object_flag_not_inherited()
numpy.core.tests.test_dtype.TestDTypeMakeCanonical.test_object_flag_not_inherited (self)
Definition at line 1238 of file test_dtype.py.
test_simple()
numpy.core.tests.test_dtype.TestDTypeMakeCanonical.test_simple (self)
Definition at line 1220 of file test_dtype.py.
test_structured()
numpy.core.tests.test_dtype.TestDTypeMakeCanonical.test_structured (self, dtype)
Definition at line 1260 of file test_dtype.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/core/tests/test_dtype.py