Code Cloning Analysis: scipy.interpolate.tests.test_bsplines.TestBSpline Class Reference
scipy.interpolate.tests.test_bsplines.TestBSpline Class Reference
Public Member Functions
test_ctor (self)
test_tck (self)
test_degree_0 (self)
test_degree_1 (self)
test_bernstein (self)
test_rndm_naive_eval (self)
test_rndm_splev (self)
test_rndm_splrep (self)
test_rndm_unity (self)
test_vectorization (self)
test_len_c (self)
test_endpoints (self)
test_continuity (self)
test_extrap (self)
test_default_extrap (self)
test_periodic_extrap (self)
test_ppoly (self)
test_derivative_rndm (self)
test_derivative_jumps (self)
test_basis_element_quadratic (self)
test_basis_element_rndm (self)
test_cmplx (self)
test_nan (self)
test_derivative_method (self)
test_antiderivative_method (self)
test_integral (self)
test_integrate_ppoly (self)
test_subclassing (self)
test_axis (self, axis)
test_neg_axis (self)
test_design_matrix_bc_types (self)
test_design_matrix_same_as_BSpline_call (self, extrapolate, degree)
test_design_matrix_x_shapes (self)
test_design_matrix_t_shapes (self)
test_design_matrix_asserts (self)
test_from_power_basis (self, bc_type)
test_from_power_basis_complex (self, bc_type)
test_from_power_basis_exmp (self)
test_read_only (self)
Detailed Description
Definition at line 19 of file test_bsplines.py.
Member Function Documentation
test_antiderivative_method()
scipy.interpolate.tests.test_bsplines.TestBSpline.test_antiderivative_method (self)
Definition at line 319 of file test_bsplines.py.
test_axis()
scipy.interpolate.tests.test_bsplines.TestBSpline.test_axis (self, axis)
Definition at line 392 of file test_bsplines.py.
test_basis_element_quadratic()
scipy.interpolate.tests.test_bsplines.TestBSpline.test_basis_element_quadratic (self)
Definition at line 273 of file test_bsplines.py.
test_basis_element_rndm()
scipy.interpolate.tests.test_bsplines.TestBSpline.test_basis_element_rndm (self)
Definition at line 286 of file test_bsplines.py.
test_bernstein()
scipy.interpolate.tests.test_bsplines.TestBSpline.test_bernstein (self)
Definition at line 88 of file test_bsplines.py.
test_cmplx()
scipy.interpolate.tests.test_bsplines.TestBSpline.test_cmplx (self)
Definition at line 292 of file test_bsplines.py.
test_continuity()
scipy.interpolate.tests.test_bsplines.TestBSpline.test_continuity (self)
Definition at line 176 of file test_bsplines.py.
test_ctor()
scipy.interpolate.tests.test_bsplines.TestBSpline.test_ctor (self)
Definition at line 21 of file test_bsplines.py.
test_default_extrap()
scipy.interpolate.tests.test_bsplines.TestBSpline.test_default_extrap (self)
Definition at line 198 of file test_bsplines.py.
test_degree_0()
scipy.interpolate.tests.test_bsplines.TestBSpline.test_degree_0 (self)
Definition at line 68 of file test_bsplines.py.
test_degree_1()
scipy.interpolate.tests.test_bsplines.TestBSpline.test_degree_1 (self)
Definition at line 77 of file test_bsplines.py.
test_derivative_jumps()
scipy.interpolate.tests.test_bsplines.TestBSpline.test_derivative_jumps (self)
Definition at line 245 of file test_bsplines.py.
test_derivative_method()
scipy.interpolate.tests.test_bsplines.TestBSpline.test_derivative_method (self)
Definition at line 310 of file test_bsplines.py.
test_derivative_rndm()
scipy.interpolate.tests.test_bsplines.TestBSpline.test_derivative_rndm (self)
Definition at line 232 of file test_bsplines.py.
test_design_matrix_asserts()
scipy.interpolate.tests.test_bsplines.TestBSpline.test_design_matrix_asserts (self)
Definition at line 526 of file test_bsplines.py.
test_design_matrix_bc_types()
scipy.interpolate.tests.test_bsplines.TestBSpline.test_design_matrix_bc_types (self)
Splines with different boundary conditions are built on different
types of vectors of knots. As far as design matrix depends only on
vector of knots, `k` and `x` it is useful to make tests for different
boundary conditions (and as following different vectors of knots).
Definition at line 431 of file test_bsplines.py.
References scipy.interpolate._bsplines.make_interp_spline().
test_design_matrix_same_as_BSpline_call()
scipy.interpolate.tests.test_bsplines.TestBSpline.test_design_matrix_same_as_BSpline_call (self, extrapolate, degree)
Test that design_matrix(x) is equivalent to BSpline(..)(x).
Definition at line 475 of file test_bsplines.py.
References scipy.interpolate._bsplines.make_interp_spline().
test_design_matrix_t_shapes()
scipy.interpolate.tests.test_bsplines.TestBSpline.test_design_matrix_t_shapes (self)
Definition at line 518 of file test_bsplines.py.
test_design_matrix_x_shapes()
scipy.interpolate.tests.test_bsplines.TestBSpline.test_design_matrix_x_shapes (self)
Definition at line 501 of file test_bsplines.py.
test_endpoints()
scipy.interpolate.tests.test_bsplines.TestBSpline.test_endpoints (self)
Definition at line 167 of file test_bsplines.py.
test_extrap()
scipy.interpolate.tests.test_bsplines.TestBSpline.test_extrap (self)
Definition at line 183 of file test_bsplines.py.
test_from_power_basis()
scipy.interpolate.tests.test_bsplines.TestBSpline.test_from_power_basis (self, bc_type)
Definition at line 546 of file test_bsplines.py.
test_from_power_basis_complex()
scipy.interpolate.tests.test_bsplines.TestBSpline.test_from_power_basis_complex (self, bc_type)
Definition at line 561 of file test_bsplines.py.
test_from_power_basis_exmp()
scipy.interpolate.tests.test_bsplines.TestBSpline.test_from_power_basis_exmp (self)
For x = [0, 1, 2, 3, 4] and y = [1, 1, 1, 1, 1]
the coefficients of Cubic Spline in the power basis:
$[[0, 0, 0, 0, 0],\\$
$[0, 0, 0, 0, 0],\\$
$[0, 0, 0, 0, 0],\\$
$[1, 1, 1, 1, 1]]$
It could be shown explicitly that coefficients of the interpolating
function in B-spline basis are c = [1, 1, 1, 1, 1, 1, 1]
Definition at line 576 of file test_bsplines.py.
References scipy.interpolate.tests.test_bsplines._make_multiples(), and scipy.interpolate._fitpack_py.splev().
test_integral()
scipy.interpolate.tests.test_bsplines.TestBSpline.test_integral (self)
Definition at line 333 of file test_bsplines.py.
test_integrate_ppoly()
scipy.interpolate.tests.test_bsplines.TestBSpline.test_integrate_ppoly (self)
Definition at line 370 of file test_bsplines.py.
test_len_c()
scipy.interpolate.tests.test_bsplines.TestBSpline.test_len_c (self)
Definition at line 149 of file test_bsplines.py.
test_nan()
scipy.interpolate.tests.test_bsplines.TestBSpline.test_nan (self)
Definition at line 305 of file test_bsplines.py.
test_neg_axis()
scipy.interpolate.tests.test_bsplines.TestBSpline.test_neg_axis (self)
Definition at line 421 of file test_bsplines.py.
test_periodic_extrap()
scipy.interpolate.tests.test_bsplines.TestBSpline.test_periodic_extrap (self)
Definition at line 206 of file test_bsplines.py.
test_ppoly()
scipy.interpolate.tests.test_bsplines.TestBSpline.test_ppoly (self)
Definition at line 224 of file test_bsplines.py.
test_read_only()
scipy.interpolate.tests.test_bsplines.TestBSpline.test_read_only (self)
Definition at line 595 of file test_bsplines.py.
test_rndm_naive_eval()
scipy.interpolate.tests.test_bsplines.TestBSpline.test_rndm_naive_eval (self)
Definition at line 102 of file test_bsplines.py.
test_rndm_splev()
scipy.interpolate.tests.test_bsplines.TestBSpline.test_rndm_splev (self)
Definition at line 116 of file test_bsplines.py.
test_rndm_splrep()
scipy.interpolate.tests.test_bsplines.TestBSpline.test_rndm_splrep (self)
Definition at line 122 of file test_bsplines.py.
test_rndm_unity()
scipy.interpolate.tests.test_bsplines.TestBSpline.test_rndm_unity (self)
Definition at line 134 of file test_bsplines.py.
test_subclassing()
scipy.interpolate.tests.test_bsplines.TestBSpline.test_subclassing (self)
Definition at line 381 of file test_bsplines.py.
test_tck()
scipy.interpolate.tests.test_bsplines.TestBSpline.test_tck (self)
Definition at line 56 of file test_bsplines.py.
test_vectorization()
scipy.interpolate.tests.test_bsplines.TestBSpline.test_vectorization (self)
Definition at line 140 of file test_bsplines.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/interpolate/tests/test_bsplines.py