Code Cloning Analysis: numpy.tests.test_warnings.ParseCall Class Reference
numpy.tests.test_warnings.ParseCall Class Reference
Public Member Functions
__init__ (self)
visit_Attribute (self, node)
visit_Name (self, node)
Public Attributes
list ls = []
Detailed Description
Definition at line 12 of file test_warnings.py.
Constructor & Destructor Documentation
__init__()
numpy.tests.test_warnings.ParseCall.__init__ (self)
Definition at line 13 of file test_warnings.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
visit_Attribute()
numpy.tests.test_warnings.ParseCall.visit_Attribute (self, node)
Definition at line 16 of file test_warnings.py.
Referenced by pandas.core.computation.expr.BaseExprVisitor.visit_Assign().
visit_Name()
numpy.tests.test_warnings.ParseCall.visit_Name (self, node)
Definition at line 20 of file test_warnings.py.
Member Data Documentation
ls
list numpy.tests.test_warnings.ParseCall.ls = []
Definition at line 14 of file test_warnings.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/tests/test_warnings.py