Code Cloning Analysis: numpy.core.tests.test_numeric.TestStdVar Class Reference
numpy.core.tests.test_numeric.TestStdVar Class Reference
Public Member Functions
setup_method (self)
test_basic (self)
test_scalars (self)
test_ddof1 (self)
test_ddof2 (self)
test_out_scalar (self)
Public Attributes
A = np.array([1, -1, 1, -1])
int real_var = 1
Detailed Description
Definition at line 2663 of file test_numeric.py.
Member Function Documentation
setup_method()
numpy.core.tests.test_numeric.TestStdVar.setup_method (self)
Definition at line 2664 of file test_numeric.py.
test_basic()
numpy.core.tests.test_numeric.TestStdVar.test_basic (self)
Definition at line 2668 of file test_numeric.py.
test_ddof1()
numpy.core.tests.test_numeric.TestStdVar.test_ddof1 (self)
Definition at line 2676 of file test_numeric.py.
test_ddof2()
numpy.core.tests.test_numeric.TestStdVar.test_ddof2 (self)
Definition at line 2682 of file test_numeric.py.
test_out_scalar()
numpy.core.tests.test_numeric.TestStdVar.test_out_scalar (self)
Definition at line 2688 of file test_numeric.py.
test_scalars()
numpy.core.tests.test_numeric.TestStdVar.test_scalars (self)
Definition at line 2672 of file test_numeric.py.
Member Data Documentation
A
numpy.core.tests.test_numeric.TestStdVar.A = np.array([1, -1, 1, -1])
Definition at line 2665 of file test_numeric.py.
Referenced by scipy.signal._ltisys.StateSpace.__add__(), scipy.signal._ltisys.StateSpace.__init__(), scipy.sparse.linalg._matfuncs._ExpmPadeHelper.__init__(), scipy.signal._ltisys.StateSpace.__mul__(), scipy.signal._ltisys.StateSpace.__neg__(), scipy.signal._ltisys.StateSpace.__repr__(), scipy.signal._ltisys.StateSpace.__rmul__(), scipy.signal._ltisys.StateSpace._copy(), scipy.sparse.linalg.tests.test_onenormest.MatrixProductOperator._matmat(), scipy.sparse.linalg._eigen.tests.test_svds.CheckingLinearOperator._matvec(), scipy.sparse.linalg.tests.test_onenormest.MatrixProductOperator._matvec(), scipy.sparse.linalg._eigen.tests.test_svds.CheckingLinearOperator._rmatvec(), scipy.sparse.linalg.tests.test_onenormest.MatrixProductOperator._rmatvec(), scipy.optimize._constraints.LinearConstraint.residual(), and scipy.signal._ltisys.StateSpaceContinuous.to_discrete().
real_var
numpy.core.tests.test_numeric.TestStdVar.real_var = 1
Definition at line 2666 of file test_numeric.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/core/tests/test_numeric.py