Code Cloning Analysis: numpy.lib.stride_tricks Namespace Reference
numpy.lib.stride_tricks Namespace Reference
Classes
class DummyArray
Functions
_maybe_view_as_subclass (original_array, new_array)
as_strided (x, shape=None, strides=None, subok=False, writeable=True)
_sliding_window_view_dispatcher (x, window_shape, axis=None, *, subok=None, writeable=None)
sliding_window_view (x, window_shape, axis=None, *, subok=False, writeable=False)
_broadcast_to (array, shape, subok, readonly)
_broadcast_to_dispatcher (array, shape, subok=None)
broadcast_to (array, shape, subok=False)
_broadcast_shape (*args)
broadcast_shapes (*args)
_broadcast_arrays_dispatcher (*args, subok=None)
broadcast_arrays (*args, subok=False)
Variables
list __all__ = ['broadcast_to', 'broadcast_arrays', 'broadcast_shapes']
Detailed Description
Utilities that manipulate strides to achieve desirable effects.
An explanation of strides can be found in the "ndarray.rst" file in the
NumPy reference guide.
Function Documentation
_broadcast_arrays_dispatcher()
numpy.lib.stride_tricks._broadcast_arrays_dispatcher (* args, subok = None) protected
Definition at line 476 of file stride_tricks.py.
_broadcast_shape()
numpy.lib.stride_tricks._broadcast_shape (* args) protected
Returns the shape of the arrays that would result from broadcasting the
supplied arrays against each other.
Definition at line 416 of file stride_tricks.py.
References broadcast_to().
Referenced by broadcast_arrays(), and broadcast_shapes().
_broadcast_to()
numpy.lib.stride_tricks._broadcast_to (array, shape, subok, readonly) protected
Definition at line 340 of file stride_tricks.py.
_broadcast_to_dispatcher()
numpy.lib.stride_tricks._broadcast_to_dispatcher (array, shape, subok = None) protected
Definition at line 363 of file stride_tricks.py.
_maybe_view_as_subclass()
numpy.lib.stride_tricks._maybe_view_as_subclass (original_array, new_array) protected
Definition at line 25 of file stride_tricks.py.
_sliding_window_view_dispatcher()
numpy.lib.stride_tricks._sliding_window_view_dispatcher (x, window_shape, axis = None, * , subok = None, writeable = None) protected
Definition at line 118 of file stride_tricks.py.
as_strided()
numpy.lib.stride_tricks.as_strided (x, shape = None, strides = None, subok = False, writeable = True)
Create a view into the array with the given shape and strides.
.. warning:: This function has to be used with extreme care, see notes.
Parameters
----------
x : ndarray
    Array to create a new.
shape : sequence of int, optional
    The shape of the new array. Defaults to ``x.shape``.
strides : sequence of int, optional
    The strides of the new array. Defaults to ``x.strides``.
subok : bool, optional
    .. versionadded:: 1.10
    If True, subclasses are preserved.
writeable : bool, optional
    .. versionadded:: 1.12
    If set to False, the returned array will always be readonly.
    Otherwise it will be writable if the original array was. It
    is advisable to set this to False if possible (see Notes).
Returns
-------
view : ndarray
See also
--------
broadcast_to : broadcast an array to a given shape.
reshape : reshape an array.
lib.stride_tricks.sliding_window_view :
    userfriendly and safe function for the creation of sliding window views.
Notes
-----
``as_strided`` creates a view into the array given the exact strides
and shape. This means it manipulates the internal data structure of
ndarray and, if done incorrectly, the array elements can point to
invalid memory and can corrupt results or crash your program.
It is advisable to always use the original ``x.strides`` when
calculating new strides to avoid reliance on a contiguous memory
layout.
Furthermore, arrays created with this function often contain self
overlapping memory, so that two elements are identical.
Vectorized write operations on such arrays will typically be
unpredictable. They may even give different results for small, large,
or transposed arrays.
Since writing to these arrays has to be tested and done with great
care, you may want to use ``writeable=False`` to avoid accidental write
operations.
For these reasons it is advisable to avoid ``as_strided`` when
possible.
Definition at line 38 of file stride_tricks.py.
Referenced by numpy.core.tests.test_mem_overlap._check_assignment(), numpy.core.tests.test_casting_unittests.TestCasting.get_data_variation(), and sliding_window_view().
broadcast_arrays()
numpy.lib.stride_tricks.broadcast_arrays (* args, subok = False)
Broadcast any number of arrays against each other.
Parameters
----------
`*args` : array_likes
    The arrays to broadcast.
subok : bool, optional
    If True, then sub-classes will be passed-through, otherwise
    the returned arrays will be forced to be a base-class array (default).
Returns
-------
broadcasted : list of arrays
    These arrays are views on the original arrays.  They are typically
    not contiguous.  Furthermore, more than one element of a
    broadcasted array may refer to a single memory location. If you need
    to write to the arrays, make copies first. While you can set the
    ``writable`` flag True, writing to a single output value may end up
    changing more than one location in the output array.
    .. deprecated:: 1.17
        The output is currently marked so that if written to, a deprecation
        warning will be emitted. A future version will set the
        ``writable`` flag False so writing to it will raise an error.
See Also
--------
broadcast
broadcast_to
broadcast_shapes
Examples
--------
>>> x = np.array([[1,2,3]])
>>> y = np.array([[4],[5]])
>>> np.broadcast_arrays(x, y)
[array([[1, 2, 3],
       [1, 2, 3]]), array([[4, 4, 4],
       [5, 5, 5]])]
Here is a useful idiom for getting contiguous copies instead of
non-contiguous views.
>>> [np.array(a) for a in np.broadcast_arrays(x, y)]
[array([[1, 2, 3],
       [1, 2, 3]]), array([[4, 4, 4],
       [5, 5, 5]])]
Definition at line 481 of file stride_tricks.py.
References _broadcast_shape(), and numpy.core.fromnumeric.all().
broadcast_shapes()
numpy.lib.stride_tricks.broadcast_shapes (* args)
Broadcast the input shapes into a single shape.
:ref:`Learn more about broadcasting here <basics.broadcasting>`.
.. versionadded:: 1.20.0
Parameters
----------
`*args` : tuples of ints, or ints
    The shapes to be broadcast against each other.
Returns
-------
tuple
    Broadcasted shape.
Raises
------
ValueError
    If the shapes are not compatible and cannot be broadcast according
    to NumPy's broadcasting rules.
See Also
--------
broadcast
broadcast_arrays
broadcast_to
Examples
--------
>>> np.broadcast_shapes((1, 2), (3, 1), (3, 2))
(3, 2)
>>> np.broadcast_shapes((6, 7), (5, 6, 1), (7,), (5, 1, 7))
(5, 6, 7)
Definition at line 434 of file stride_tricks.py.
References _broadcast_shape().
broadcast_to()
numpy.lib.stride_tricks.broadcast_to (array, shape, subok = False)
Broadcast an array to a new shape.
Parameters
----------
array : array_like
    The array to broadcast.
shape : tuple or int
    The shape of the desired array. A single integer ``i`` is interpreted
    as ``(i,)``.
subok : bool, optional
    If True, then sub-classes will be passed-through, otherwise
    the returned array will be forced to be a base-class array (default).
Returns
-------
broadcast : array
    A readonly view on the original array with the given shape. It is
    typically not contiguous. Furthermore, more than one element of a
    broadcasted array may refer to a single memory location.
Raises
------
ValueError
    If the array is not compatible with the new shape according to NumPy's
    broadcasting rules.
See Also
--------
broadcast
broadcast_arrays
broadcast_shapes
Notes
-----
.. versionadded:: 1.10.0
Examples
--------
>>> x = np.array([1, 2, 3])
>>> np.broadcast_to(x, (3, 3))
array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])
Definition at line 368 of file stride_tricks.py.
Referenced by _broadcast_shape(), numpy.lib.twodim_base.tril_indices(), and numpy.lib.twodim_base.triu_indices().
sliding_window_view()
numpy.lib.stride_tricks.sliding_window_view (x, window_shape, axis = None, * , subok = False, writeable = False)
Create a sliding window view into the array with the given window shape.
Also known as rolling or moving window, the window slides across all
dimensions of the array and extracts subsets of the array at all window
positions.
.. versionadded:: 1.20.0
Parameters
----------
x : array_like
    Array to create the sliding window view from.
window_shape : int or tuple of int
    Size of window over each axis that takes part in the sliding window.
    If `axis` is not present, must have same length as the number of input
    array dimensions. Single integers `i` are treated as if they were the
    tuple `(i,)`.
axis : int or tuple of int, optional
    Axis or axes along which the sliding window is applied.
    By default, the sliding window is applied to all axes and
    `window_shape[i]` will refer to axis `i` of `x`.
    If `axis` is given as a `tuple of int`, `window_shape[i]` will refer to
    the axis `axis[i]` of `x`.
    Single integers `i` are treated as if they were the tuple `(i,)`.
subok : bool, optional
    If True, sub-classes will be passed-through, otherwise the returned
    array will be forced to be a base-class array (default).
writeable : bool, optional
    When true, allow writing to the returned view. The default is false,
    as this should be used with caution: the returned view contains the
    same memory location multiple times, so writing to one location will
    cause others to change.
Returns
-------
view : ndarray
    Sliding window view of the array. The sliding window dimensions are
    inserted at the end, and the original dimensions are trimmed as
    required by the size of the sliding window.
    That is, ``view.shape = x_shape_trimmed + window_shape``, where
    ``x_shape_trimmed`` is ``x.shape`` with every entry reduced by one less
    than the corresponding window size.
See Also
--------
lib.stride_tricks.as_strided: A lower-level and less safe routine for
    creating arbitrary views from custom shape and strides.
broadcast_to: broadcast an array to a given shape.
Notes
-----
For many applications using a sliding window view can be convenient, but
potentially very slow. Often specialized solutions exist, for example:
- `scipy.signal.fftconvolve`
- filtering functions in `scipy.ndimage`
- moving window functions provided by
  `bottleneck <https://github.com/pydata/bottleneck>`_.
As a rough estimate, a sliding window approach with an input size of `N`
and a window size of `W` will scale as `O(N*W)` where frequently a special
algorithm can achieve `O(N)`. That means that the sliding window variant
for a window size of 100 can be a 100 times slower than a more specialized
version.
Nevertheless, for small window sizes, when no custom algorithm exists, or
as a prototyping and developing tool, this function can be a good solution.
Examples
--------
>>> x = np.arange(6)
>>> x.shape
(6,)
>>> v = sliding_window_view(x, 3)
>>> v.shape
(4, 3)
>>> v
array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])
This also works in more dimensions, e.g.
>>> i, j = np.ogrid[:3, :4]
>>> x = 10*i + j
>>> x.shape
(3, 4)
>>> x
array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])
>>> shape = (2,2)
>>> v = sliding_window_view(x, shape)
>>> v.shape
(2, 3, 2, 2)
>>> v
array([[[[ 0,  1],
         [10, 11]],
        [[ 1,  2],
         [11, 12]],
        [[ 2,  3],
         [12, 13]]],
       [[[10, 11],
         [20, 21]],
        [[11, 12],
         [21, 22]],
        [[12, 13],
         [22, 23]]]])
The axis can be specified explicitly:
>>> v = sliding_window_view(x, 3, 0)
>>> v.shape
(1, 4, 3)
>>> v
array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22],
        [ 3, 13, 23]]])
The same axis can be used several times. In that case, every use reduces
the corresponding original dimension:
>>> v = sliding_window_view(x, (2, 3), (1, 1))
>>> v.shape
(3, 1, 2, 3)
>>> v
array([[[[ 0,  1,  2],
         [ 1,  2,  3]]],
       [[[10, 11, 12],
         [11, 12, 13]]],
       [[[20, 21, 22],
         [21, 22, 23]]]])
Combining with stepped slicing (`::step`), this can be used to take sliding
views which skip elements:
>>> x = np.arange(7)
>>> sliding_window_view(x, 5)[:, ::2]
array([[0, 2, 4],
       [1, 3, 5],
       [2, 4, 6]])
or views which move by multiple elements
>>> x = np.arange(7)
>>> sliding_window_view(x, 3)[::2, :]
array([[0, 1, 2],
       [2, 3, 4],
       [4, 5, 6]])
A common application of `sliding_window_view` is the calculation of running
statistics. The simplest example is the
`moving average <https://en.wikipedia.org/wiki/Moving_average>`_:
>>> x = np.arange(6)
>>> x.shape
(6,)
>>> v = sliding_window_view(x, 3)
>>> v.shape
(4, 3)
>>> v
array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])
>>> moving_average = v.mean(axis=-1)
>>> moving_average
array([1., 2., 3., 4.])
Note that a sliding window approach is often **not** optimal (see Notes).
Definition at line 124 of file stride_tricks.py.
References numpy.core.fromnumeric.any(), as_strided(), and numpy.core.numeric.normalize_axis_tuple().
Variable Documentation
__all__
list numpy.lib.stride_tricks.__all__ = ['broadcast_to', 'broadcast_arrays', 'broadcast_shapes'] private
Definition at line 12 of file stride_tricks.py.