Code Cloning Analysis: pandas._config.config Namespace Reference
pandas._config.config Namespace Reference
Classes
class CallableDynamicDoc
class DeprecatedOption
class DictWrapper
class option_context
class OptionError
class RegisteredOption
Functions
str _get_single_key (str pat, bool silent)
Any _get_option (str pat, bool silent=False)
None _set_option (*args, **kwargs)
str|None _describe_option (str pat="", bool _print_desc=True)
None _reset_option (str pat, bool silent=False)
get_default_val (str pat)
None register_option (str key, object defval, str doc="", Callable[[object], Any]|None validator=None, Callable[[str], Any]|None cb=None)
None deprecate_option (str key, str|None msg=None, str|None rkey=None, str|None removal_ver=None)
list[str] _select_options (str pat)
tuple[dict[str, Any], str] _get_root (str key)
bool _is_deprecated (str key)
_get_deprecated_option (str key)
_get_registered_option (str key)
str _translate_key (str key)
bool _warn_if_deprecated (str key)
str _build_option_description (str k)
pp_options_list (Iterable[str] keys, int width=80, bool _print=False)
Generator[None, None, None] config_prefix (str prefix)
Callable[[Any], None] is_type_factory (type[Any] _type)
Callable[[Any], None] is_instance_factory (_type)
Callable[[Any], None] is_one_of_factory (legal_values)
None is_nonnegative_int (object value)
bool is_callable (obj)
Variables
str _get_option_tmpl
str _set_option_tmpl
str _describe_option_tmpl
str _reset_option_tmpl
get_option = CallableDynamicDoc(_get_option, _get_option_tmpl)
set_option = CallableDynamicDoc(_set_option, _set_option_tmpl)
reset_option = CallableDynamicDoc(_reset_option, _reset_option_tmpl)
describe_option = CallableDynamicDoc(_describe_option, _describe_option_tmpl)
options = DictWrapper(_global_config)
Callable[[Any], None] is_int = is_type_factory(int)
Callable[[Any], None] is_bool = is_type_factory(bool)
Callable[[Any], None] is_float = is_type_factory(float)
Callable[[Any], None] is_str = is_type_factory(str)
Callable[[Any], None] is_text = is_instance_factory((str, bytes))
Detailed Description
The config module holds package-wide configurables and provides
a uniform API for working with them.
Overview
========
This module supports the following requirements:
- options are referenced using keys in dot.notation, e.g. "x.y.option - z".
- keys are case-insensitive.
- functions should accept partial/regex keys, when unambiguous.
- options can be registered by modules at import time.
- options can be registered at init-time (via core.config_init)
- options have a default value, and (optionally) a description and
  validation function associated with them.
- options can be deprecated, in which case referencing them
  should produce a warning.
- deprecated options can optionally be rerouted to a replacement
  so that accessing a deprecated option reroutes to a differently
  named option.
- options can be reset to their default value.
- all option can be reset to their default value at once.
- all options in a certain sub - namespace can be reset at once.
- the user can set / get / reset or ask for the description of an option.
- a developer can register and mark an option as deprecated.
- you can register a callback to be invoked when the option value
  is set or reset. Changing the stored value is considered misuse, but
  is not verboten.
Implementation
==============
- Data is stored using nested dictionaries, and should be accessed
  through the provided API.
- "Registered options" and "Deprecated options" have metadata associated
  with them, which are stored in auxiliary dictionaries keyed on the
  fully-qualified key, e.g. "x.y.z.option".
- the config_init module is imported by the package's __init__.py file.
  placing any register_option() calls there will ensure those options
  are available as soon as pandas is loaded. If you use register_option
  in a module, it will only be available after that module is imported,
  which you should be aware of.
- `config_prefix` is a context_manager (for use with the `with` keyword)
  which can save developers some typing, see the docstring.
Function Documentation
_build_option_description()
str pandas._config.config._build_option_description (str k) protected
Builds a formatted description of a registered option and prints it
Definition at line 718 of file config.py.
References _get_deprecated_option(), and _get_registered_option().
_describe_option()
str | None pandas._config.config._describe_option (str pat = "", bool _print_desc = True) protected
Definition at line 185 of file config.py.
_get_deprecated_option()
pandas._config.config._get_deprecated_option (str key) protected
Retrieves the metadata for a deprecated option, if `key` is deprecated.
Returns
-------
DeprecatedOption (namedtuple) if key is deprecated, None otherwise
Definition at line 649 of file config.py.
Referenced by _build_option_description(), _translate_key(), and _warn_if_deprecated().
_get_option()
Any pandas._config.config._get_option (str pat, bool silent = False) protected
Definition at line 145 of file config.py.
_get_registered_option()
pandas._config.config._get_registered_option (str key) protected
Retrieves the option metadata if `key` is a registered option.
Returns
-------
RegisteredOption (namedtuple) if key is deprecated, None otherwise
Definition at line 665 of file config.py.
Referenced by _build_option_description().
_get_root()
tuple[dict[str, Any], str] pandas._config.config._get_root (str key) protected
Definition at line 635 of file config.py.
_get_single_key()
str pandas._config.config._get_single_key (str pat, bool silent) protected
Definition at line 127 of file config.py.
_is_deprecated()
bool pandas._config.config._is_deprecated (str key) protected
Returns True if the given option has been deprecated
Definition at line 643 of file config.py.
_reset_option()
None pandas._config.config._reset_option (str pat, bool silent = False) protected
Definition at line 198 of file config.py.
_select_options()
list[str] pandas._config.config._select_options (str pat) protected
returns a list of keys matching `pat`
if pat=="all", returns all registered options
Definition at line 617 of file config.py.
_set_option()
None pandas._config.config._set_option (* args, ** kwargs) protected
Definition at line 153 of file config.py.
_translate_key()
str pandas._config.config._translate_key (str key) protected
if key id deprecated and a replacement key defined, will return the
replacement key, otherwise returns `key` as - is
Definition at line 676 of file config.py.
References _get_deprecated_option().
_warn_if_deprecated()
bool pandas._config.config._warn_if_deprecated (str key) protected
Checks if `key` is a deprecated option and if so, prints a warning.
Returns
-------
bool - True if `key` is deprecated, False otherwise.
Definition at line 688 of file config.py.
References _get_deprecated_option().
config_prefix()
Generator[None, None, None] pandas._config.config.config_prefix (str prefix)
contextmanager for multiple invocations of API with a common prefix
supported API functions: (register / get / set)__option
Warning: This is not thread - safe, and won't work properly if you import
the API functions into your module using the "from x import y" construct.
Example
-------
import pandas._config.config as cf
with cf.config_prefix("display.font"):
    cf.register_option("color", "red")
    cf.register_option("size", " 5 pt")
    cf.set_option(size, " 6 pt")
    cf.get_option(size)
    ...
    etc'
will register options "display.font.color", "display.font.size", set the
value of "display.font.size"... and so on.
Definition at line 781 of file config.py.
deprecate_option()
None pandas._config.config.deprecate_option (str key, str | None msg = None, str | None rkey = None, str | None removal_ver = None)
Mark option `key` as deprecated, if code attempts to access this option,
a warning will be produced, using `msg` if given, or a default message
if not.
if `rkey` is given, any access to the key will be re-routed to `rkey`.
Neither the existence of `key` nor that if `rkey` is checked. If they
do not exist, any subsequence access will fail as usual, after the
deprecation warning is given.
Parameters
----------
key : str
    Name of the option to be deprecated.
    must be a fully-qualified option name (e.g "x.y.z.rkey").
msg : str, optional
    Warning message to output when the key is referenced.
    if no message is given a default message will be emitted.
rkey : str, optional
    Name of an option to reroute access to.
    If specified, any referenced `key` will be
    re-routed to `rkey` including set/get/reset.
    rkey must be a fully-qualified option name (e.g "x.y.z.rkey").
    used by the default message if no `msg` is specified.
removal_ver : str, optional
    Specifies the version in which this option will
    be removed. used by the default message if no `msg` is specified.
Raises
------
OptionError
    If the specified key has already been deprecated.
Definition at line 566 of file config.py.
get_default_val()
pandas._config.config.get_default_val (str pat)
Definition at line 215 of file config.py.
is_callable()
bool pandas._config.config.is_callable (obj)
Parameters
----------
`obj` - the object to be checked
Returns
-------
validator - returns True if object is callable
    raises ValueError otherwise.
Definition at line 933 of file config.py.
is_instance_factory()
Callable[[Any], None] pandas._config.config.is_instance_factory (_type)
Parameters
----------
`_type` - the type to be checked against
Returns
-------
validator - a function of a single argument x , which raises
            ValueError if x is not an instance of `_type`
Definition at line 856 of file config.py.
Referenced by is_nonnegative_int().
is_nonnegative_int()
None pandas._config.config.is_nonnegative_int (object value)
Verify that value is None or a positive int.
Parameters
----------
value : None or int
        The `value` to be checked.
Raises
------
ValueError
    When the value is not None or is a negative integer
Definition at line 899 of file config.py.
References is_instance_factory(), and is_type_factory().
is_one_of_factory()
Callable[[Any], None] pandas._config.config.is_one_of_factory (legal_values)
Definition at line 882 of file config.py.
is_type_factory()
Callable[[Any], None] pandas._config.config.is_type_factory (type[Any] _type)
Parameters
----------
`_type` - a type to be compared against (e.g. type(x) == `_type`)
Returns
-------
validator - a function of a single argument x , which raises
            ValueError if type(x) is not equal to `_type`
Definition at line 835 of file config.py.
Referenced by is_nonnegative_int().
pp_options_list()
pandas._config.config.pp_options_list (Iterable[str] keys, int width = 80, bool _print = False)
Builds a concise listing of available options, grouped by prefix
Definition at line 742 of file config.py.
register_option()
None pandas._config.config.register_option (str key, object defval, str doc = "", Callable[[object], Any] | None validator = None, Callable[[str], Any] | None cb = None)
Register an option in the package-wide pandas config object
Parameters
----------
key : str
    Fully-qualified key, e.g. "x.y.option - z".
defval : object
    Default value of the option.
doc : str
    Description of the option.
validator : Callable, optional
    Function of a single argument, should raise `ValueError` if
    called with a value which is not a legal value for the option.
cb
    a function of a single argument "key", which is called
    immediately after an option value is set/reset. key is
    the full name of the option.
Raises
------
ValueError if `validator` is specified and `defval` is not a valid value.
Definition at line 491 of file config.py.
Variable Documentation
_describe_option_tmpl
str pandas._config.config._describe_option_tmpl protected
Definition at line 370 of file config.py.
_get_option_tmpl
str pandas._config.config._get_option_tmpl protected
Definition at line 284 of file config.py.
_reset_option_tmpl
str pandas._config.config._reset_option_tmpl protected
Definition at line 410 of file config.py.
_set_option_tmpl
str pandas._config.config._set_option_tmpl protected
Definition at line 323 of file config.py.
describe_option
pandas._config.config.describe_option = CallableDynamicDoc(_describe_option, _describe_option_tmpl)
Definition at line 451 of file config.py.
get_option
pandas._config.config.get_option = CallableDynamicDoc(_get_option, _get_option_tmpl)
Definition at line 448 of file config.py.
is_bool
Callable[[Any], None] pandas._config.config.is_bool = is_type_factory(bool)
Definition at line 927 of file config.py.
is_float
Callable[[Any], None] pandas._config.config.is_float = is_type_factory(float)
Definition at line 928 of file config.py.
is_int
Callable[[Any], None] pandas._config.config.is_int = is_type_factory(int)
Definition at line 926 of file config.py.
is_str
Callable[[Any], None] pandas._config.config.is_str = is_type_factory(str)
Definition at line 929 of file config.py.
is_text
Callable[[Any], None] pandas._config.config.is_text = is_instance_factory((str, bytes))
Definition at line 930 of file config.py.
options
pandas._config.config.options = DictWrapper(_global_config)
Definition at line 452 of file config.py.
reset_option
pandas._config.config.reset_option = CallableDynamicDoc(_reset_option, _reset_option_tmpl)
Definition at line 450 of file config.py.
set_option
pandas._config.config.set_option = CallableDynamicDoc(_set_option, _set_option_tmpl)
Definition at line 449 of file config.py.