Code Cloning Analysis: matplotlib.spines.SpinesProxy Class Reference
matplotlib.spines.SpinesProxy Class Reference
Public Member Functions
__init__ (self, spine_dict)
__getattr__ (self, name)
__dir__ (self)
Protected Attributes
_spine_dict = spine_dict
Detailed Description
A proxy to broadcast ``set_*()`` and ``set()`` method calls to contained `.Spines`.
The proxy cannot be used for any other operations on its members.
The supported methods are determined dynamically based on the contained
spines. If not all spines support a given method, it's executed only on
the subset of spines that support it.
Definition at line 488 of file spines.py.
Constructor & Destructor Documentation
__init__()
matplotlib.spines.SpinesProxy.__init__ (self, spine_dict)
Definition at line 498 of file spines.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__dir__()
matplotlib.spines.SpinesProxy.__dir__ (self)
Definition at line 515 of file spines.py.
__getattr__()
matplotlib.spines.SpinesProxy.__getattr__ (self, name)
Definition at line 501 of file spines.py.
Member Data Documentation
_spine_dict
matplotlib.spines.SpinesProxy._spine_dict = spine_dict protected
Definition at line 499 of file spines.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/spines.py