Code Cloning Analysis: matplotlib.projections.ProjectionRegistry Class Reference
matplotlib.projections.ProjectionRegistry Class Reference
Public Member Functions
__init__ (self)
register (self, *projections)
get_projection_class (self, name)
get_projection_names (self)
Protected Attributes
dict _all_projection_types = {}
Detailed Description
A mapping of registered projection names to projection classes.
Definition at line 69 of file __init__.py.
Constructor & Destructor Documentation
__init__()
matplotlib.projections.ProjectionRegistry.__init__ (self)
Definition at line 72 of file __init__.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
get_projection_class()
matplotlib.projections.ProjectionRegistry.get_projection_class (self, name)
Get a projection class from its *name*.
Definition at line 81 of file __init__.py.
References _all_projection_types.
get_projection_names()
matplotlib.projections.ProjectionRegistry.get_projection_names (self)
Return the names of all projections currently registered.
Definition at line 85 of file __init__.py.
References _all_projection_types.
register()
matplotlib.projections.ProjectionRegistry.register (self, * projections)
Register a new set of projections.
Definition at line 75 of file __init__.py.
References _all_projection_types.
Member Data Documentation
_all_projection_types
matplotlib.projections.ProjectionRegistry._all_projection_types = {} protected
Definition at line 73 of file __init__.py.
Referenced by get_projection_class(), get_projection_names(), and register().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/projections/__init__.py