Code Cloning Analysis: scipy.stats.tests.test_rank.TestTieCorrect Class Reference
scipy.stats.tests.test_rank.TestTieCorrect Class Reference
Public Member Functions
test_empty (self)
test_one (self)
test_no_correction (self)
test_basic (self)
test_overflow (self)
Detailed Description
Definition at line 8 of file test_rank.py.
Member Function Documentation
test_basic()
scipy.stats.tests.test_rank.TestTieCorrect.test_basic (self)
Check a few basic examples of the tie correction factor.
Definition at line 31 of file test_rank.py.
References scipy.stats._stats_py.rankdata(), and scipy.stats._stats_py.tiecorrect().
test_empty()
scipy.stats.tests.test_rank.TestTieCorrect.test_empty (self)
An empty array requires no correction, should return 1.0.
Definition at line 10 of file test_rank.py.
References scipy.stats._stats_py.tiecorrect().
test_no_correction()
scipy.stats.tests.test_rank.TestTieCorrect.test_no_correction (self)
Arrays with no ties require no correction.
Definition at line 22 of file test_rank.py.
References scipy.stats._stats_py.tiecorrect().
test_one()
scipy.stats.tests.test_rank.TestTieCorrect.test_one (self)
A single element requires no correction, should return 1.0.
Definition at line 16 of file test_rank.py.
References scipy.stats._stats_py.tiecorrect().
test_overflow()
scipy.stats.tests.test_rank.TestTieCorrect.test_overflow (self)
Definition at line 66 of file test_rank.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/stats/tests/test_rank.py