Code Cloning Analysis: pip._vendor.pyparsing.util Namespace Reference
pip._vendor.pyparsing.util Namespace Reference
Classes
class __config_flags
class _FifoCache
class _UnboundedCache
class LRUMemo
class UnboundedMemo
Functions
int col (int loc, str strg)
int lineno (int loc, str strg)
str line (int loc, str strg)
str _escape_regex_range_chars (str s)
str _collapse_string_to_ranges (Union[str, Iterable[str]] s, bool re_escape=True)
list _flatten (list ll)
C _make_synonym_function (str compat_name, C fn)
Callable[[Callable], C] replaced_by_pep8 (C fn)
Variables
_bslash = chr(92)
C = TypeVar("C", bound=Callable)
Function Documentation
_collapse_string_to_ranges()
str pip._vendor.pyparsing.util._collapse_string_to_ranges (Union[str, Iterable[str]] s, bool re_escape = True) protected
Definition at line 186 of file util.py.
_escape_regex_range_chars()
str pip._vendor.pyparsing.util._escape_regex_range_chars (str s) protected
Definition at line 177 of file util.py.
_flatten()
list pip._vendor.pyparsing.util._flatten (list ll) protected
Definition at line 230 of file util.py.
_make_synonym_function()
C pip._vendor.pyparsing.util._make_synonym_function (str compat_name, C fn) protected
Definition at line 240 of file util.py.
col()
int pip._vendor.pyparsing.util.col (int loc, str strg)
Returns current column within a string, counting newlines as line separators.
The first column is number 1.
Note: the default parsing behavior is to expand tabs in the input string
before starting the parsing process.  See
:class:`ParserElement.parse_string` for more
information on parsing strings containing ``<TAB>`` s, and suggested
methods to maintain a consistent view of the parsed string, the parse
location, and line and column positions within the parsed string.
Definition at line 40 of file util.py.
Referenced by pip._vendor.pyparsing.core.And._ErrorStop._generateDefaultName(), pip._vendor.pyparsing.helpers.indentedBlock(), and pip._vendor.pyparsing.actions.match_only_at_col().
line()
str pip._vendor.pyparsing.util.line (int loc, str strg)
Returns the line of text containing loc within a string, counting newlines as line separators.
Definition at line 71 of file util.py.
lineno()
int pip._vendor.pyparsing.util.lineno (int loc, str strg)
Returns current line number within a string, counting newlines as line separators.
The first line is number 1.
Note - the default parsing behavior is to expand tabs in the input string
before starting the parsing process.  See :class:`ParserElement.parse_string`
for more information on parsing strings containing ``<TAB>`` s, and
suggested methods to maintain a consistent view of the parsed string, the
parse location, and line and column positions within the parsed string.
Definition at line 57 of file util.py.
replaced_by_pep8()
Callable[[Callable], C] pip._vendor.pyparsing.util.replaced_by_pep8 (C fn)
Decorator for pre-PEP8 compatibility synonyms, to link them to the new function.
Definition at line 280 of file util.py.
Variable Documentation
_bslash
pip._vendor.pyparsing.util._bslash = chr(92) protected
Definition at line 10 of file util.py.
C
pip._vendor.pyparsing.util.C = TypeVar("C", bound=Callable)
Definition at line 11 of file util.py.