Code Cloning Analysis: matplotlib.dates.DateConverter Class Reference
matplotlib.dates.DateConverter Class Reference
Public Member Functions
__init__ (self, *, interval_multiples=True)
axisinfo (self, unit, axis)
Static Public Member Functions
convert (value, unit, axis)
default_units (x, axis)
Protected Attributes
_interval_multiples = interval_multiples
Detailed Description
Converter for `datetime.date` and `datetime.datetime` data, or for
date/time data represented as it would be converted by `date2num`.
The 'unit' tag for such data is None or a `~datetime.tzinfo` instance.
Definition at line 1724 of file dates.py.
Constructor & Destructor Documentation
__init__()
matplotlib.dates.DateConverter.__init__ (self, * , interval_multiples = True)
Definition at line 1732 of file dates.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
axisinfo()
matplotlib.dates.DateConverter.axisinfo (self, unit, axis)
Return the `~matplotlib.units.AxisInfo` for *unit*.
*unit* is a `~datetime.tzinfo` instance or None.
The *axis* argument is required but not used.
Reimplemented from matplotlib.units.ConversionInterface.
Reimplemented in matplotlib.dates.ConciseDateConverter.
Definition at line 1736 of file dates.py.
References _interval_multiples.
convert()
matplotlib.dates.DateConverter.convert (value, unit, axis) static
If *value* is not already a number or sequence of numbers, convert it
with `date2num`.
The *unit* and *axis* arguments are not used.
Reimplemented from matplotlib.units.ConversionInterface.
Definition at line 1755 of file dates.py.
References matplotlib.dates.date2num().
Referenced by matplotlib.testing.jpl_units.Epoch.Epoch.__add__(), matplotlib.testing.jpl_units.Epoch.Epoch.__init__(), matplotlib.testing.jpl_units.Epoch.Epoch.__sub__(), matplotlib.testing.jpl_units.Epoch.Epoch._cmp(), pandas.core.computation.engines.NumExprEngine._evaluate(), pandas.core.internals.blocks.Block.convert(), PIL.Image.Image.reduce(), PIL.Image.Image.resize(), and PIL.Image.Image.transform().
default_units()
matplotlib.dates.DateConverter.default_units (x, axis) static
Return the `~datetime.tzinfo` instance of *x* or of its first element,
or None
Reimplemented from matplotlib.units.ConversionInterface.
Definition at line 1765 of file dates.py.
Member Data Documentation
_interval_multiples
matplotlib.dates.DateConverter._interval_multiples = interval_multiples protected
Definition at line 1733 of file dates.py.
Referenced by matplotlib.dates.ConciseDateConverter.axisinfo(), and axisinfo().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/dates.py