Code Cloning Analysis: matplotlib.testing.compare Namespace Reference
matplotlib.testing.compare Namespace Reference
Classes
class _Converter
class _ConverterError
class _GSConverter
class _SVGConverter
class _SVGWithMatplotlibFontsConverter
Functions
make_test_filename (fname, purpose)
_get_cache_path ()
get_cache_dir ()
get_file_hash (path, block_size=2 **20)
_update_converter ()
comparable_formats ()
convert (filename, cache)
_clean_conversion_cache ()
_register_conversion_cache_cleaner_once ()
crop_to_same (actual_path, actual_image, expected_path, expected_image)
calculate_rms (expected_image, actual_image)
_load_image (path)
compare_images (expected, actual, tol, in_decorator=False)
save_diff_image (expected, actual, output)
Variables
_log = logging.getLogger(__name__)
list __all__ = ['calculate_rms', 'comparable_formats', 'compare_images']
dict converter = {}
_svg_with_matplotlib_fonts_converter = _SVGWithMatplotlibFontsConverter()
Detailed Description
Utilities for comparing image results.
Function Documentation
_clean_conversion_cache()
matplotlib.testing.compare._clean_conversion_cache () protected
Definition at line 328 of file compare.py.
_get_cache_path()
matplotlib.testing.compare._get_cache_path () protected
Definition at line 38 of file compare.py.
_load_image()
matplotlib.testing.compare._load_image (path) protected
Definition at line 383 of file compare.py.
_register_conversion_cache_cleaner_once()
matplotlib.testing.compare._register_conversion_cache_cleaner_once () protected
Definition at line 352 of file compare.py.
_update_converter()
matplotlib.testing.compare._update_converter () protected
Definition at line 230 of file compare.py.
calculate_rms()
matplotlib.testing.compare.calculate_rms (expected_image, actual_image)
Calculate the per-pixel errors, then compute the root mean square error.
Definition at line 367 of file compare.py.
Referenced by compare_images().
comparable_formats()
matplotlib.testing.compare.comparable_formats ()
Return the list of file formats that `.compare_images` can compare
on this system.
Returns
-------
list of str
    E.g. ``['png', 'pdf', 'svg', 'eps']``.
Definition at line 252 of file compare.py.
compare_images()
matplotlib.testing.compare.compare_images (expected, actual, tol, in_decorator = False)
Compare two "image" files checking differences within a tolerance.
The two given filenames may point to files which are convertible to
PNG via the `.converter` dictionary. The underlying RMS is calculated
with the `.calculate_rms` function.
Parameters
----------
expected : str
    The filename of the expected image.
actual : str
    The filename of the actual image.
tol : float
    The tolerance (a color value difference, where 255 is the
    maximal difference).  The test fails if the average pixel
    difference is greater than this value.
in_decorator : bool
    Determines the output format. If called from image_comparison
    decorator, this should be True. (default=False)
Returns
-------
None or dict or str
    Return *None* if the images are equal within the given tolerance.
    If the images differ, the return value depends on  *in_decorator*.
    If *in_decorator* is true, a dict with the following entries is
    returned:
    - *rms*: The RMS of the image difference.
    - *expected*: The filename of the expected image.
    - *actual*: The filename of the actual image.
    - *diff_image*: The filename of the difference image.
    - *tol*: The comparison tolerance.
    Otherwise, a human-readable multi-line string representation of this
    information is returned.
Examples
--------
::
    img1 = "./baseline/plot.png"
    img2 = "./output/plot.png"
    compare_images(img1, img2, 0.001)
Definition at line 393 of file compare.py.
References calculate_rms(), convert(), make_test_filename(), and save_diff_image().
convert()
matplotlib.testing.compare.convert (filename, cache)
Convert the named file to png; return the name of the created file.
If *cache* is True, the result of the conversion is cached in
`matplotlib.get_cachedir() + '/test_cache/'`.  The caching is based on a
hash of the exact contents of the input file.  Old cache entries are
automatically deleted as needed to keep the size of the cache capped to
twice the size of all baseline images.
Definition at line 266 of file compare.py.
References convert().
Referenced by compare_images(), and convert().
crop_to_same()
matplotlib.testing.compare.crop_to_same (actual_path, actual_image, expected_path, expected_image)
Definition at line 356 of file compare.py.
get_cache_dir()
matplotlib.testing.compare.get_cache_dir ()
Definition at line 44 of file compare.py.
get_file_hash()
matplotlib.testing.compare.get_file_hash (path, block_size = 2 ** 20)
Definition at line 48 of file compare.py.
make_test_filename()
matplotlib.testing.compare.make_test_filename (fname, purpose)
Make a new filename by inserting *purpose* before the file's extension.
Definition at line 30 of file compare.py.
Referenced by compare_images().
save_diff_image()
matplotlib.testing.compare.save_diff_image (expected, actual, output)
Parameters
----------
expected : str
    File path of expected image.
actual : str
    File path of actual image.
output : str
    File path to save difference image to.
Definition at line 497 of file compare.py.
Referenced by compare_images().
Variable Documentation
__all__
list matplotlib.testing.compare.__all__ = ['calculate_rms', 'comparable_formats', 'compare_images'] private
Definition at line 27 of file compare.py.
_log
matplotlib.testing.compare._log = logging.getLogger(__name__) protected
Definition at line 25 of file compare.py.
_svg_with_matplotlib_fonts_converter
matplotlib.testing.compare._svg_with_matplotlib_fonts_converter = _SVGWithMatplotlibFontsConverter() protected
Definition at line 249 of file compare.py.
converter
dict matplotlib.testing.compare.converter = {}
Definition at line 247 of file compare.py.