Code Cloning Analysis: fontTools.pens.statisticsPen.StatisticsPen Class Reference
fontTools.pens.statisticsPen.StatisticsPen Class Reference
Public Member Functions
__init__ (self, glyphset=None)
Public Member Functions inherited from fontTools.pens.statisticsPen.StatisticsBase
__init__ (self)
Public Member Functions inherited from fontTools.pens.momentsPen.MomentsPen
__init__ (self, glyphset=None)
Public Member Functions inherited from fontTools.pens.basePen.BasePen
__init__ (self, glyphSet=None)
closePath (self)
endPath (self)
moveTo (self, pt)
lineTo (self, pt)
curveTo (self, *points)
qCurveTo (self, *points)
Public Member Functions inherited from fontTools.pens.basePen.DecomposingPen
__init__ (self, glyphSet, *args, skipMissingComponents=None, reverseFlipped=False, **kwargs)
addComponent (self, glyphName, transformation)
addVarComponent (self, glyphName, transformation, location)
Public Member Functions inherited from fontTools.misc.loggingTools.LogMixin
log (self)
Protected Member Functions
_closePath (self)
_update (self)
Protected Member Functions inherited from fontTools.pens.statisticsPen.StatisticsBase
_zero (self)
Protected Member Functions inherited from fontTools.pens.momentsPen.MomentsPen
_moveTo (self, p0)
_endPath (self)
_lineTo (self, p1)
_qCurveToOne (self, p1, p2)
_curveToOne (self, p1, p2, p3)
Protected Member Functions inherited from fontTools.pens.basePen.BasePen
_getCurrentPoint (self)
Additional Inherited Members
Public Attributes inherited from fontTools.pens.statisticsPen.StatisticsBase
int area = 0
int meanX = 0
int meanY = 0
int varianceX = 0
int varianceY = 0
int stddevX = 0
int stddevY = 0
int covariance = 0
int correlation = 0
int slant = 0
Public Attributes inherited from fontTools.pens.momentsPen.MomentsPen
int area = 0
int momentX = 0
int momentY = 0
int momentXX = 0
int momentXY = 0
int momentYY = 0
Public Attributes inherited from fontTools.pens.basePen.DecomposingPen
glyphSet = glyphSet
reverseFlipped = reverseFlipped
Static Public Attributes inherited from fontTools.pens.basePen.DecomposingPen
bool skipMissingComponents = True
MissingComponentError = MissingComponentError
Protected Attributes inherited from fontTools.pens.momentsPen.MomentsPen
_startPoint = p0
Protected Attributes inherited from fontTools.misc.loggingTools.LogMixin
_log = logging.getLogger(name)
Detailed Description
Pen calculating area, center of mass, variance and
standard-deviation, covariance and correlation, and slant,
of glyph shapes.
Note that if the glyph shape is self-intersecting, the values
are not correct (but well-defined). Moreover, area will be
negative if contour directions are clockwise.
Definition at line 55 of file statisticsPen.py.
Constructor & Destructor Documentation
__init__()
fontTools.pens.statisticsPen.StatisticsPen.__init__ (self, glyphset = None)
Definition at line 64 of file statisticsPen.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_closePath()
fontTools.pens.statisticsPen.StatisticsPen._closePath (self) protected
Reimplemented from fontTools.pens.momentsPen.MomentsPen.
Definition at line 68 of file statisticsPen.py.
_update()
fontTools.pens.statisticsPen.StatisticsPen._update (self) protected
Reimplemented from fontTools.pens.statisticsPen.StatisticsBase.
Definition at line 72 of file statisticsPen.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/pens/statisticsPen.py