Code Cloning Analysis: fontTools.ttLib.tables.otConverters.MorxSubtableConverter Class Reference
fontTools.ttLib.tables.otConverters.MorxSubtableConverter Class Reference
Public Member Functions
__init__ (self, name, repeat, aux, tableClass=None, *, description="")
read (self, reader, font, tableDict)
xmlWrite (self, xmlWriter, font, value, name, attrs)
xmlRead (self, attrs, content, font)
write (self, writer, font, tableDict, value, repeatIndex=None)
Public Member Functions inherited from fontTools.ttLib.tables.otConverters.BaseConverter
__init__ (self, name, repeat, aux, tableClass=None, *, description="")
readArray (self, reader, font, tableDict, count)
getRecordSize (self, reader)
writeArray (self, writer, font, tableDict, values)
Optional[int] getVarIndexOffset (self)
Protected Member Functions
_setTextDirectionFromCoverageFlags (self, flags, subtable)
Static Protected Attributes
dict _PROCESSING_ORDERS
dict _PROCESSING_ORDERS_REVERSED = {val: key for key, val in _PROCESSING_ORDERS.items()}
Additional Inherited Members
Public Attributes inherited from fontTools.ttLib.tables.otConverters.BaseConverter
name = name
repeat = repeat
aux = aux
tableClass = tableClass
isCount
str isLookupType = "MorphType"
isPropagated
description = description
Static Public Attributes inherited from fontTools.ttLib.tables.otConverters.BaseConverter
varIndexBasePlusOffsetRE = re.compile(r"VarIndexBase\s*\+\s*(\d+)")
Detailed Description
Definition at line 1139 of file otConverters.py.
Constructor & Destructor Documentation
__init__()
fontTools.ttLib.tables.otConverters.MorxSubtableConverter.__init__ (self, name, repeat, aux, tableClass = None, * , description = "")
Definition at line 1150 of file otConverters.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_setTextDirectionFromCoverageFlags()
fontTools.ttLib.tables.otConverters.MorxSubtableConverter._setTextDirectionFromCoverageFlags (self, flags, subtable) protected
Definition at line 1155 of file otConverters.py.
Referenced by read(), and xmlRead().
read()
fontTools.ttLib.tables.otConverters.MorxSubtableConverter.read (self, reader, font, tableDict)
Read a value from the reader.
Reimplemented from fontTools.ttLib.tables.otConverters.BaseConverter.
Definition at line 1163 of file otConverters.py.
References _PROCESSING_ORDERS, and _setTextDirectionFromCoverageFlags().
Referenced by pandas.io.parsers.python_parser.PythonParser.__init__(), pip._vendor.urllib3.util.ssltransport.SSLTransport.__init__(), pandas.io.sas.sas7bdat.SAS7BDATReader.column_types(), packaging._tokenizer.Tokenizer.consume(), pip._vendor.urllib3.response.HTTPResponse.drain_conn(), packaging._tokenizer.Tokenizer.expect(), pip._vendor.urllib3.response.HTTPResponse.from_httplib(), pandas.io.sas.sas_xport.XportReader.get_chunk(), packaging._tokenizer.Tokenizer.raise_syntax_error(), PIL.ContainerIO.ContainerIO.readline(), and pip._vendor.urllib3.response.HTTPResponse.stream().
write()
fontTools.ttLib.tables.otConverters.MorxSubtableConverter.write (self, writer, font, tableDict, value, repeatIndex = None)
Write a value to the writer.
Reimplemented from fontTools.ttLib.tables.otConverters.BaseConverter.
Definition at line 1242 of file otConverters.py.
References _PROCESSING_ORDERS_REVERSED.
Referenced by matplotlib.backends.backend_pdf.PdfFile.addGouraudTriangles(), matplotlib.backends.backend_pdf.PdfFile.close(), joblib.externals.cloudpickle.cloudpickle.Pickler.reducer_override(), scipy.io.matlab._mio5.VarWriter5.write_sparse(), pandas.io.formats.html.HTMLFormatter.write_th(), scipy.io.matlab._mio5.VarWriter5.write_top(), matplotlib.backends.backend_pdf.PdfFile.writeTrailer(), and matplotlib.backends.backend_pdf.PdfFile.writeXref().
xmlRead()
fontTools.ttLib.tables.otConverters.MorxSubtableConverter.xmlRead (self, attrs, content, font)
Read a value from XML.
Reimplemented from fontTools.ttLib.tables.otConverters.BaseConverter.
Definition at line 1210 of file otConverters.py.
References _PROCESSING_ORDERS, _PROCESSING_ORDERS_REVERSED, and _setTextDirectionFromCoverageFlags().
xmlWrite()
fontTools.ttLib.tables.otConverters.MorxSubtableConverter.xmlWrite (self, xmlWriter, font, value, name, attrs)
Write a value to XML.
Reimplemented from fontTools.ttLib.tables.otConverters.BaseConverter.
Definition at line 1190 of file otConverters.py.
Member Data Documentation
_PROCESSING_ORDERS
dict fontTools.ttLib.tables.otConverters.MorxSubtableConverter._PROCESSING_ORDERS static protected
Initial value:
=  {
        # bits 30 and 28 of morx.CoverageFlags; see morx spec
        (False, False): "LayoutOrder",
        (True, False): "ReversedLayoutOrder",
        (False, True): "LogicalOrder",
        (True, True): "ReversedLogicalOrder",
    }
Definition at line 1140 of file otConverters.py.
Referenced by read(), and xmlRead().
_PROCESSING_ORDERS_REVERSED
fontTools.ttLib.tables.otConverters.MorxSubtableConverter._PROCESSING_ORDERS_REVERSED = {val: key for key, val in _PROCESSING_ORDERS.items()} static protected
Definition at line 1148 of file otConverters.py.
Referenced by write(), and xmlRead().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ttLib/tables/otConverters.py