Code Cloning Analysis: sklearn.utils.estimator_checks._NotAnArray Class Reference
sklearn.utils.estimator_checks._NotAnArray Class Reference
Public Member Functions
__init__ (self, data)
__array__ (self, dtype=None, copy=None)
__array_function__ (self, func, types, args, kwargs)
Public Attributes
data = np.asarray(data)
Detailed Description
An object that is convertible to an array.
Parameters
----------
data : array-like
    The data.
Definition at line 938 of file estimator_checks.py.
Constructor & Destructor Documentation
__init__()
sklearn.utils.estimator_checks._NotAnArray.__init__ (self, data)
Definition at line 947 of file estimator_checks.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params().
Member Function Documentation
__array__()
sklearn.utils.estimator_checks._NotAnArray.__array__ (self, dtype = None, copy = None)
Definition at line 950 of file estimator_checks.py.
Referenced by numpy.matrixlib.defmatrix.matrix.A(), numpy.matrixlib.defmatrix.matrix.A1(), numpy.core.defchararray.chararray.argsort(), numpy.matrixlib.defmatrix.matrix.tolist(), and numpy.ma.mrecords.MaskedRecords.view().
__array_function__()
sklearn.utils.estimator_checks._NotAnArray.__array_function__ (self, func, types, args, kwargs)
Definition at line 953 of file estimator_checks.py.
Member Data Documentation
data
sklearn.utils.estimator_checks._NotAnArray.data = np.asarray(data)
Definition at line 948 of file estimator_checks.py.
Referenced by pandas.tests.extension.decimal.array.DecimalArray._reduce(), matplotlib.backends.backend_svg.XMLWriter.element(), numpy.core._internal._ctypes.get_data(), and PIL.GifImagePlugin.GifImageFile.seek().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/sklearn/utils/estimator_checks.py