Code Cloning Analysis: matplotlib.units.ConversionInterface Class Reference
matplotlib.units.ConversionInterface Class Reference
Static Public Member Functions
axisinfo (unit, axis)
default_units (x, axis)
convert (obj, unit, axis)
Detailed Description
The minimal interface for a converter to take custom data types (or
sequences) and convert them to values Matplotlib can use.
Definition at line 108 of file units.py.
Member Function Documentation
axisinfo()
matplotlib.units.ConversionInterface.axisinfo (unit, axis) static
Return an `.AxisInfo` for the axis with the specified units.
Reimplemented in matplotlib.category.StrCategoryConverter, matplotlib.dates.ConciseDateConverter, matplotlib.dates.DateConverter, matplotlib.testing.jpl_units.EpochConverter.EpochConverter, matplotlib.testing.jpl_units.StrConverter.StrConverter, and matplotlib.testing.jpl_units.UnitDblConverter.UnitDblConverter.
Definition at line 115 of file units.py.
convert()
matplotlib.units.ConversionInterface.convert (obj, unit, axis) static
Convert *obj* using *unit* for the specified *axis*.
If *obj* is a sequence, return the converted sequence.  The output must
be a sequence of scalars that can be used by the numpy array layer.
Reimplemented in matplotlib.category.StrCategoryConverter, matplotlib.dates.DateConverter, matplotlib.testing.jpl_units.EpochConverter.EpochConverter, matplotlib.testing.jpl_units.StrConverter.StrConverter, matplotlib.testing.jpl_units.UnitDblConverter.UnitDblConverter, and matplotlib.units.DecimalConverter.
Definition at line 125 of file units.py.
Referenced by pandas.core.computation.engines.NumExprEngine._evaluate(), pandas.core.internals.blocks.Block.convert(), PIL.Image.Image.reduce(), PIL.Image.Image.resize(), and PIL.Image.Image.transform().
default_units()
matplotlib.units.ConversionInterface.default_units (x, axis) static
Return the default unit for *x* or ``None`` for the given axis.
Reimplemented in matplotlib.category.StrCategoryConverter, matplotlib.dates.DateConverter, matplotlib.testing.jpl_units.EpochConverter.EpochConverter, matplotlib.testing.jpl_units.StrConverter.StrConverter, and matplotlib.testing.jpl_units.UnitDblConverter.UnitDblConverter.
Definition at line 120 of file units.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/units.py