Code Cloning Analysis: pandas.tests.groupby.test_categorical Namespace Reference
pandas.tests.groupby.test_categorical Namespace Reference
Functions
cartesian_product_for_groupers (result, args, names, fill_value=np.nan)
test_apply_use_categorical_name (df)
test_basic (using_infer_string)
test_level_get_group (observed)
test_sorting_with_different_categoricals ()
test_apply (ordered)
test_observed (request, using_infer_string, observed)
test_observed_codes_remap (observed)
test_observed_perf ()
test_observed_groups (observed)
test_unobserved_in_index (keys, expected_values, expected_index_levels, test_series)
test_observed_groups_with_nan (observed)
test_observed_nth ()
test_dataframe_categorical_with_nan (observed)
test_dataframe_categorical_ordered_observed_sort (ordered, observed, sort)
test_datetime ()
test_categorical_index ()
test_describe_categorical_columns ()
test_unstack_categorical ()
test_bins_unequal_len ()
test_categorical_series (series, data)
test_as_index ()
test_preserve_categories ()
test_preserve_categorical_dtype ()
test_preserve_on_ordered_ops (func, values)
test_categorical_no_compress ()
test_groupby_empty_with_category ()
test_sort ()
test_sort2 (sort, ordered)
test_sort_datetimelike (sort, ordered)
test_empty_sum ()
test_empty_prod ()
test_groupby_multiindex_categorical_datetime ()
test_groupby_agg_observed_true_single_column (as_index, expected)
test_shift (fill_value)
df_cat (df)
test_seriesgroupby_observed_true (df_cat, operation)
test_seriesgroupby_observed_false_or_none (df_cat, observed, operation)
test_seriesgroupby_observed_apply_dict (df_cat, observed, index, data)
test_groupby_categorical_series_dataframe_consistent (df_cat)
test_groupby_categorical_axis_1 (code)
test_groupby_cat_preserves_structure (observed, ordered)
test_get_nonexistent_category ()
test_series_groupby_on_2_categoricals_unobserved (reduction_func, observed)
test_series_groupby_on_2_categoricals_unobserved_zeroes_or_nans (reduction_func, request)
test_dataframe_groupby_on_2_categoricals_when_observed_is_true (reduction_func)
test_dataframe_groupby_on_2_categoricals_when_observed_is_false (reduction_func, observed)
test_series_groupby_categorical_aggregation_getitem ()
test_groupby_agg_categorical_columns (func, expected_values)
test_groupby_agg_non_numeric ()
test_groupby_first_returned_categorical_instead_of_dataframe (func)
test_read_only_category_no_sort ()
test_sorted_missing_category_values ()
test_agg_cython_category_not_implemented_fallback ()
test_aggregate_categorical_with_isnan ()
test_categorical_transform ()
test_series_groupby_first_on_categorical_col_grouped_on_2_categoricals (str func, bool observed)
test_df_groupby_first_on_categorical_col_grouped_on_2_categoricals (str func, bool observed)
test_groupby_categorical_indices_unused_categories ()
test_groupby_last_first_preserve_categoricaldtype (func)
test_groupby_categorical_observed_nunique ()
test_groupby_categorical_aggregate_functions ()
test_groupby_categorical_dropna (observed, dropna)
test_category_order_reducer (request, as_index, sort, observed, reduction_func, index_kind, ordered)
test_category_order_transformer (as_index, sort, observed, transformation_func, index_kind, ordered)
test_category_order_head_tail (as_index, sort, observed, method, index_kind, ordered)
test_category_order_apply (as_index, sort, observed, method, index_kind, ordered)
test_many_categories (as_index, sort, index_kind, ordered)
test_groupby_default_depr (cat_columns, keys)
test_agg_list (request, as_index, observed, reduction_func, test_series, keys)
Variables
dict _results_for_groupbys_with_missing_categories
Function Documentation
cartesian_product_for_groupers()
pandas.tests.groupby.test_categorical.cartesian_product_for_groupers (result, args, names, fill_value = np.nan)
Reindex to a cartesian production for the groupers,
preserving the nature (Categorical) of each grouper
Definition at line 21 of file test_categorical.py.
References cartesian_product_for_groupers().
Referenced by cartesian_product_for_groupers().
df_cat()
pandas.tests.groupby.test_categorical.df_cat (df)
DataFrame with multiple categorical columns and a column of integers.
Shortened so as not to contain all possible combinations of categories.
Useful for testing `observed` kwarg functionality on GroupBy objects.
Parameters
----------
df: DataFrame
    Non-categorical, longer DataFrame from another fixture, used to derive
    this one
Returns
-------
df_cat: DataFrame
Definition at line 1231 of file test_categorical.py.
References pandas.tests.groupby.get_groupby_method_args().
test_agg_cython_category_not_implemented_fallback()
pandas.tests.groupby.test_categorical.test_agg_cython_category_not_implemented_fallback ()
Definition at line 1678 of file test_categorical.py.
test_agg_list()
pandas.tests.groupby.test_categorical.test_agg_list (request, as_index, observed, reduction_func, test_series, keys)
Definition at line 2130 of file test_categorical.py.
test_aggregate_categorical_with_isnan()
pandas.tests.groupby.test_categorical.test_aggregate_categorical_with_isnan ()
Definition at line 1700 of file test_categorical.py.
test_apply()
pandas.tests.groupby.test_categorical.test_apply (ordered)
Definition at line 306 of file test_categorical.py.
test_apply_use_categorical_name()
pandas.tests.groupby.test_categorical.test_apply_use_categorical_name (df)
Definition at line 71 of file test_categorical.py.
test_as_index()
pandas.tests.groupby.test_categorical.test_as_index ()
Definition at line 795 of file test_categorical.py.
test_basic()
pandas.tests.groupby.test_categorical.test_basic (using_infer_string)
Definition at line 86 of file test_categorical.py.
test_bins_unequal_len()
pandas.tests.groupby.test_categorical.test_bins_unequal_len ()
Definition at line 763 of file test_categorical.py.
test_categorical_index()
pandas.tests.groupby.test_categorical.test_categorical_index ()
Definition at line 703 of file test_categorical.py.
test_categorical_no_compress()
pandas.tests.groupby.test_categorical.test_categorical_no_compress ()
Definition at line 946 of file test_categorical.py.
test_categorical_series()
pandas.tests.groupby.test_categorical.test_categorical_series (series, data)
Definition at line 785 of file test_categorical.py.
test_categorical_transform()
pandas.tests.groupby.test_categorical.test_categorical_transform ()
Definition at line 1727 of file test_categorical.py.
test_category_order_apply()
pandas.tests.groupby.test_categorical.test_category_order_apply (as_index, sort, observed, method, index_kind, ordered)
Definition at line 2038 of file test_categorical.py.
test_category_order_head_tail()
pandas.tests.groupby.test_categorical.test_category_order_head_tail (as_index, sort, observed, method, index_kind, ordered)
Definition at line 2002 of file test_categorical.py.
test_category_order_reducer()
pandas.tests.groupby.test_categorical.test_category_order_reducer (request, as_index, sort, observed, reduction_func, index_kind, ordered)
Definition at line 1917 of file test_categorical.py.
test_category_order_transformer()
pandas.tests.groupby.test_categorical.test_category_order_transformer (as_index, sort, observed, transformation_func, index_kind, ordered)
Definition at line 1967 of file test_categorical.py.
test_dataframe_categorical_ordered_observed_sort()
pandas.tests.groupby.test_categorical.test_dataframe_categorical_ordered_observed_sort (ordered, observed, sort)
Definition at line 628 of file test_categorical.py.
test_dataframe_categorical_with_nan()
pandas.tests.groupby.test_categorical.test_dataframe_categorical_with_nan (observed)
Definition at line 605 of file test_categorical.py.
test_dataframe_groupby_on_2_categoricals_when_observed_is_false()
pandas.tests.groupby.test_categorical.test_dataframe_groupby_on_2_categoricals_when_observed_is_false (reduction_func, observed)
Definition at line 1519 of file test_categorical.py.
test_dataframe_groupby_on_2_categoricals_when_observed_is_true()
pandas.tests.groupby.test_categorical.test_dataframe_groupby_on_2_categoricals_when_observed_is_true (reduction_func)
Definition at line 1492 of file test_categorical.py.
test_datetime()
pandas.tests.groupby.test_categorical.test_datetime ()
Definition at line 660 of file test_categorical.py.
test_describe_categorical_columns()
pandas.tests.groupby.test_categorical.test_describe_categorical_columns ()
Definition at line 728 of file test_categorical.py.
test_df_groupby_first_on_categorical_col_grouped_on_2_categoricals()
pandas.tests.groupby.test_categorical.test_df_groupby_first_on_categorical_col_grouped_on_2_categoricals (str func, bool observed)
Definition at line 1809 of file test_categorical.py.
test_empty_prod()
pandas.tests.groupby.test_categorical.test_empty_prod ()
Definition at line 1133 of file test_categorical.py.
test_empty_sum()
pandas.tests.groupby.test_categorical.test_empty_sum ()
Definition at line 1105 of file test_categorical.py.
test_get_nonexistent_category()
pandas.tests.groupby.test_categorical.test_get_nonexistent_category ()
Definition at line 1391 of file test_categorical.py.
test_groupby_agg_categorical_columns()
pandas.tests.groupby.test_categorical.test_groupby_agg_categorical_columns (func, expected_values)
Definition at line 1578 of file test_categorical.py.
test_groupby_agg_non_numeric()
pandas.tests.groupby.test_categorical.test_groupby_agg_non_numeric ()
Definition at line 1595 of file test_categorical.py.
test_groupby_agg_observed_true_single_column()
pandas.tests.groupby.test_categorical.test_groupby_agg_observed_true_single_column (as_index, expected)
Definition at line 1207 of file test_categorical.py.
test_groupby_cat_preserves_structure()
pandas.tests.groupby.test_categorical.test_groupby_cat_preserves_structure (observed, ordered)
Definition at line 1374 of file test_categorical.py.
test_groupby_categorical_aggregate_functions()
pandas.tests.groupby.test_categorical.test_groupby_categorical_aggregate_functions ()
Definition at line 1880 of file test_categorical.py.
test_groupby_categorical_axis_1()
pandas.tests.groupby.test_categorical.test_groupby_categorical_axis_1 (code)
Definition at line 1359 of file test_categorical.py.
test_groupby_categorical_dropna()
pandas.tests.groupby.test_categorical.test_groupby_categorical_dropna (observed, dropna)
Definition at line 1898 of file test_categorical.py.
test_groupby_categorical_indices_unused_categories()
pandas.tests.groupby.test_categorical.test_groupby_categorical_indices_unused_categories ()
Definition at line 1833 of file test_categorical.py.
test_groupby_categorical_observed_nunique()
pandas.tests.groupby.test_categorical.test_groupby_categorical_observed_nunique ()
Definition at line 1865 of file test_categorical.py.
test_groupby_categorical_series_dataframe_consistent()
pandas.tests.groupby.test_categorical.test_groupby_categorical_series_dataframe_consistent (df_cat)
Definition at line 1351 of file test_categorical.py.
test_groupby_default_depr()
pandas.tests.groupby.test_categorical.test_groupby_default_depr (cat_columns, keys)
Definition at line 2118 of file test_categorical.py.
test_groupby_empty_with_category()
pandas.tests.groupby.test_categorical.test_groupby_empty_with_category ()
Definition at line 983 of file test_categorical.py.
test_groupby_first_returned_categorical_instead_of_dataframe()
pandas.tests.groupby.test_categorical.test_groupby_first_returned_categorical_instead_of_dataframe (func)
Definition at line 1607 of file test_categorical.py.
test_groupby_last_first_preserve_categoricaldtype()
pandas.tests.groupby.test_categorical.test_groupby_last_first_preserve_categoricaldtype (func)
Definition at line 1854 of file test_categorical.py.
test_groupby_multiindex_categorical_datetime()
pandas.tests.groupby.test_categorical.test_groupby_multiindex_categorical_datetime ()
Definition at line 1157 of file test_categorical.py.
test_level_get_group()
pandas.tests.groupby.test_categorical.test_level_get_group (observed)
Definition at line 253 of file test_categorical.py.
test_many_categories()
pandas.tests.groupby.test_categorical.test_many_categories (as_index, sort, index_kind, ordered)
Definition at line 2077 of file test_categorical.py.
test_observed()
pandas.tests.groupby.test_categorical.test_observed (request, using_infer_string, observed)
Definition at line 343 of file test_categorical.py.
test_observed_codes_remap()
pandas.tests.groupby.test_categorical.test_observed_codes_remap (observed)
Definition at line 457 of file test_categorical.py.
test_observed_groups()
pandas.tests.groupby.test_categorical.test_observed_groups (observed)
Definition at line 498 of file test_categorical.py.
test_observed_groups_with_nan()
pandas.tests.groupby.test_categorical.test_observed_groups_with_nan (observed)
Definition at line 573 of file test_categorical.py.
test_observed_nth()
pandas.tests.groupby.test_categorical.test_observed_nth ()
Definition at line 594 of file test_categorical.py.
test_observed_perf()
pandas.tests.groupby.test_categorical.test_observed_perf ()
Definition at line 477 of file test_categorical.py.
test_preserve_categorical_dtype()
pandas.tests.groupby.test_categorical.test_preserve_categorical_dtype ()
Definition at line 885 of file test_categorical.py.
test_preserve_categories()
pandas.tests.groupby.test_categorical.test_preserve_categories ()
Definition at line 855 of file test_categorical.py.
test_preserve_on_ordered_ops()
pandas.tests.groupby.test_categorical.test_preserve_on_ordered_ops (func, values)
Definition at line 927 of file test_categorical.py.
test_read_only_category_no_sort()
pandas.tests.groupby.test_categorical.test_read_only_category_no_sort ()
Definition at line 1621 of file test_categorical.py.
test_series_groupby_categorical_aggregation_getitem()
pandas.tests.groupby.test_categorical.test_series_groupby_categorical_aggregation_getitem ()
Definition at line 1562 of file test_categorical.py.
test_series_groupby_first_on_categorical_col_grouped_on_2_categoricals()
pandas.tests.groupby.test_categorical.test_series_groupby_first_on_categorical_col_grouped_on_2_categoricals (str func, bool observed)
Definition at line 1784 of file test_categorical.py.
test_series_groupby_on_2_categoricals_unobserved()
pandas.tests.groupby.test_categorical.test_series_groupby_on_2_categoricals_unobserved (reduction_func, observed)
Definition at line 1402 of file test_categorical.py.
test_series_groupby_on_2_categoricals_unobserved_zeroes_or_nans()
pandas.tests.groupby.test_categorical.test_series_groupby_on_2_categoricals_unobserved_zeroes_or_nans (reduction_func, request)
Definition at line 1440 of file test_categorical.py.
test_seriesgroupby_observed_apply_dict()
pandas.tests.groupby.test_categorical.test_seriesgroupby_observed_apply_dict (df_cat, observed, index, data)
Definition at line 1342 of file test_categorical.py.
test_seriesgroupby_observed_false_or_none()
pandas.tests.groupby.test_categorical.test_seriesgroupby_observed_false_or_none (df_cat, observed, operation)
Definition at line 1274 of file test_categorical.py.
test_seriesgroupby_observed_true()
pandas.tests.groupby.test_categorical.test_seriesgroupby_observed_true (df_cat, operation)
Definition at line 1256 of file test_categorical.py.
test_shift()
pandas.tests.groupby.test_categorical.test_shift (fill_value)
Definition at line 1219 of file test_categorical.py.
test_sort()
pandas.tests.groupby.test_categorical.test_sort ()
Definition at line 997 of file test_categorical.py.
test_sort2()
pandas.tests.groupby.test_categorical.test_sort2 (sort, ordered)
Definition at line 1020 of file test_categorical.py.
test_sort_datetimelike()
pandas.tests.groupby.test_categorical.test_sort_datetimelike (sort, ordered)
Definition at line 1055 of file test_categorical.py.
test_sorted_missing_category_values()
pandas.tests.groupby.test_categorical.test_sorted_missing_category_values ()
Definition at line 1633 of file test_categorical.py.
test_sorting_with_different_categoricals()
pandas.tests.groupby.test_categorical.test_sorting_with_different_categoricals ()
Definition at line 283 of file test_categorical.py.
test_unobserved_in_index()
pandas.tests.groupby.test_categorical.test_unobserved_in_index (keys, expected_values, expected_index_levels, test_series)
Definition at line 539 of file test_categorical.py.
test_unstack_categorical()
pandas.tests.groupby.test_categorical.test_unstack_categorical ()
Definition at line 744 of file test_categorical.py.
Variable Documentation
_results_for_groupbys_with_missing_categories
dict pandas.tests.groupby.test_categorical._results_for_groupbys_with_missing_categories protected
Initial value:
=  {
    # This maps the builtin groupby functions to their expected outputs for
    # missing categories when they are called on a categorical grouper with
    # observed=False. Some functions are expected to return NaN, some zero.
    # These expected values can be used across several tests (i.e. they are
    # the same for SeriesGroupBy and DataFrameGroupBy) but they should only be
    # hardcoded in one place.
    "all": np.nan,
    "any": np.nan,
    "count": 0,
    "corrwith": np.nan,
    "first": np.nan,
    "idxmax": np.nan,
    "idxmin": np.nan,
    "last": np.nan,
    "max": np.nan,
    "mean": np.nan,
    "median": np.nan,
    "min": np.nan,
    "nth": np.nan,
    "nunique": 0,
    "prod": np.nan,
    "quantile": np.nan,
    "sem": np.nan,
    "size": 0,
    "skew": np.nan,
    "std": np.nan,
    "sum": 0,
    "var": np.nan,
}
Definition at line 38 of file test_categorical.py.