Code Cloning Analysis: fontTools.ufoLib.glifLib Namespace Reference
fontTools.ufoLib.glifLib Namespace Reference
Classes
class _BaseParser
class _DoneParsing
class _FetchComponentBasesParser
class _FetchImageFileNameParser
class _FetchUnicodesParser
class GLIFFormatVersion
class GLIFPointPen
class Glyph
class GlyphSet
Functions
glyphNameToFileName (glyphName, existingFileNames)
readGlyphFromString (aString, glyphObject=None, pointPen=None, formatVersions=None, validate=True)
_writeGlyphToBytes (glyphName, glyphObject=None, drawPointsFunc=None, writer=None, formatVersion=None, validate=True)
writeGlyphToString (glyphName, glyphObject=None, drawPointsFunc=None, formatVersion=None, validate=True)
_writeAdvance (glyphObject, element, validate)
_writeUnicodes (glyphObject, element, validate)
_writeNote (glyphObject, element, validate)
_writeImage (glyphObject, element, validate)
_writeGuidelines (glyphObject, element, identifiers, validate)
_writeAnchorsFormat1 (pen, anchors, validate)
_writeAnchors (glyphObject, element, identifiers, validate)
_writeLib (glyphObject, element, validate)
validateLayerInfoVersion3ValueForAttribute (attr, value)
validateLayerInfoVersion3Data (infoData)
_glifTreeFromFile (aFile)
_glifTreeFromString (aString)
_readGlyphFromTree (tree, glyphObject=None, pointPen=None, formatVersions=GLIFFormatVersion.supported_versions(), validate=True)
_readGlyphFromTreeFormat1 (tree, glyphObject=None, pointPen=None, validate=None, **kwargs)
_readGlyphFromTreeFormat2 (tree, glyphObject=None, pointPen=None, validate=None, formatMinor=0)
_readName (glyphObject, root, validate)
_readAdvance (glyphObject, advance)
_readNote (glyphObject, note)
_readLib (glyphObject, lib, validate)
_readImage (glyphObject, image, validate)
buildOutlineFormat1 (glyphObject, pen, outline, validate)
_buildAnchorFormat1 (point, validate)
_buildOutlineContourFormat1 (pen, contour, validate)
_buildOutlinePointsFormat1 (pen, contour)
_buildOutlineComponentFormat1 (pen, component, validate)
buildOutlineFormat2 (glyphObject, pen, outline, identifiers, validate)
_buildOutlineContourFormat2 (pen, contour, identifiers, validate)
_buildOutlinePointsFormat2 (pen, contour, identifiers, validate)
_buildOutlineComponentFormat2 (pen, component, identifiers, validate)
_validateAndMassagePointStructures (contour, pointAttributes, openContourOffCurveLeniency=False, validate=True)
_relaxedSetattr (object, attr, value)
_number (s)
_fetchUnicodes (glif)
_fetchImageFileName (glif)
_fetchComponentBases (glif)
Variables
list __all__
logger = logging.getLogger(__name__)
str CONTENTS_FILENAME = "contents.plist"
str LAYERINFO_FILENAME = "layerinfo.plist"
dict layerInfoVersion3ValueData
dict _READ_GLYPH_FROM_TREE_FUNCS
dict contourAttributesFormat2 = {"identifier"}
dict componentAttributesFormat1
dict componentAttributesFormat2 = componentAttributesFormat1 | {"identifier"}
dict pointAttributesFormat1 = {"x", "y", "type", "smooth", "name"}
dict pointAttributesFormat2 = pointAttributesFormat1 | {"identifier"}
dict pointSmoothOptions = {"no", "yes"}
dict pointTypeOptions = {"move", "line", "offcurve", "curve", "qcurve"}
list _transformationInfo
Detailed Description
Generic module for reading and writing the .glif format.
More info about the .glif format (GLyphInterchangeFormat) can be found here:
        http://unifiedfontobject.org
The main class in this module is :class:`GlyphSet`. It manages a set of .glif files
in a folder. It offers two ways to read glyph data, and one way to write
glyph data. See the class doc string for details.
Function Documentation
_buildAnchorFormat1()
fontTools.ufoLib.glifLib._buildAnchorFormat1 (point, validate) protected
Definition at line 1422 of file glifLib.py.
_buildOutlineComponentFormat1()
fontTools.ufoLib.glifLib._buildOutlineComponentFormat1 (pen, component, validate) protected
Definition at line 1465 of file glifLib.py.
_buildOutlineComponentFormat2()
fontTools.ufoLib.glifLib._buildOutlineComponentFormat2 (pen, component, identifiers, validate) protected
Definition at line 1565 of file glifLib.py.
_buildOutlineContourFormat1()
fontTools.ufoLib.glifLib._buildOutlineContourFormat1 (pen, contour, validate) protected
Definition at line 1440 of file glifLib.py.
_buildOutlineContourFormat2()
fontTools.ufoLib.glifLib._buildOutlineContourFormat2 (pen, contour, identifiers, validate) protected
Definition at line 1499 of file glifLib.py.
_buildOutlinePointsFormat1()
fontTools.ufoLib.glifLib._buildOutlinePointsFormat1 (pen, contour) protected
Definition at line 1455 of file glifLib.py.
_buildOutlinePointsFormat2()
fontTools.ufoLib.glifLib._buildOutlinePointsFormat2 (pen, contour, identifiers, validate) protected
Definition at line 1532 of file glifLib.py.
_fetchComponentBases()
fontTools.ufoLib.glifLib._fetchComponentBases (glif) protected
Get a list of component base glyphs listed in glif.
Definition at line 1844 of file glifLib.py.
Referenced by fontTools.ufoLib.glifLib.GlyphSet.getComponentReferences().
_fetchImageFileName()
fontTools.ufoLib.glifLib._fetchImageFileName (glif) protected
The image file name (if any) from glif.
Definition at line 1817 of file glifLib.py.
Referenced by fontTools.ufoLib.glifLib.GlyphSet.getImageReferences().
_fetchUnicodes()
fontTools.ufoLib.glifLib._fetchUnicodes (glif) protected
Get a list of unicodes listed in glif.
Definition at line 1783 of file glifLib.py.
Referenced by fontTools.ufoLib.glifLib.GlyphSet.getUnicodes().
_glifTreeFromFile()
fontTools.ufoLib.glifLib._glifTreeFromFile (aFile) protected
Definition at line 1086 of file glifLib.py.
_glifTreeFromString()
fontTools.ufoLib.glifLib._glifTreeFromString (aString) protected
Definition at line 1099 of file glifLib.py.
_number()
fontTools.ufoLib.glifLib._number (s) protected
Given a numeric string, return an integer or a float, whichever
the string indicates. _number("1") will return the integer 1,
_number("1.0") will return the float 1.0.
>>> _number("1")
1
>>> _number("1.0")
1.0
>>> _number("a")  # doctest: +IGNORE_EXCEPTION_DETAIL
Traceback (most recent call last):
    ...
GlifLibError: Could not convert a to an int or float.
Definition at line 1722 of file glifLib.py.
Referenced by validateLayerInfoVersion3Data().
_readAdvance()
fontTools.ufoLib.glifLib._readAdvance (glyphObject, advance) protected
Definition at line 1341 of file glifLib.py.
_readGlyphFromTree()
fontTools.ufoLib.glifLib._readGlyphFromTree (tree, glyphObject = None, pointPen = None, formatVersions = GLIFFormatVersion.supported_versions(), validate = True) protected
Definition at line 1116 of file glifLib.py.
_readGlyphFromTreeFormat1()
fontTools.ufoLib.glifLib._readGlyphFromTreeFormat1 (tree, glyphObject = None, pointPen = None, validate = None, ** kwargs) protected
Definition at line 1167 of file glifLib.py.
_readGlyphFromTreeFormat2()
fontTools.ufoLib.glifLib._readGlyphFromTreeFormat2 (tree, glyphObject = None, pointPen = None, validate = None, formatMinor = 0) protected
Definition at line 1226 of file glifLib.py.
_readImage()
fontTools.ufoLib.glifLib._readImage (glyphObject, image, validate) protected
Definition at line 1365 of file glifLib.py.
_readLib()
fontTools.ufoLib.glifLib._readLib (glyphObject, lib, validate) protected
Definition at line 1354 of file glifLib.py.
_readName()
fontTools.ufoLib.glifLib._readName (glyphObject, root, validate) protected
Definition at line 1333 of file glifLib.py.
_readNote()
fontTools.ufoLib.glifLib._readNote (glyphObject, note) protected
Definition at line 1348 of file glifLib.py.
_relaxedSetattr()
fontTools.ufoLib.glifLib._relaxedSetattr (object, attr, value) protected
Definition at line 1715 of file glifLib.py.
_validateAndMassagePointStructures()
fontTools.ufoLib.glifLib._validateAndMassagePointStructures (contour, pointAttributes, openContourOffCurveLeniency = False, validate = True) protected
Definition at line 1606 of file glifLib.py.
_writeAdvance()
fontTools.ufoLib.glifLib._writeAdvance (glyphObject, element, validate) protected
Definition at line 870 of file glifLib.py.
_writeAnchors()
fontTools.ufoLib.glifLib._writeAnchors (glyphObject, element, identifiers, validate) protected
Definition at line 983 of file glifLib.py.
_writeAnchorsFormat1()
fontTools.ufoLib.glifLib._writeAnchorsFormat1 (pen, anchors, validate) protected
Definition at line 966 of file glifLib.py.
_writeGlyphToBytes()
fontTools.ufoLib.glifLib._writeGlyphToBytes (glyphName, glyphObject = None, drawPointsFunc = None, writer = None, formatVersion = None, validate = True) protected
Return .glif data for a glyph as a UTF-8 encoded bytes string.
Definition at line 742 of file glifLib.py.
Referenced by fontTools.ufoLib.glifLib.GlyphSet.writeGlyph(), and writeGlyphToString().
_writeGuidelines()
fontTools.ufoLib.glifLib._writeGuidelines (glyphObject, element, identifiers, validate) protected
Definition at line 936 of file glifLib.py.
_writeImage()
fontTools.ufoLib.glifLib._writeImage (glyphObject, element, validate) protected
Definition at line 919 of file glifLib.py.
_writeLib()
fontTools.ufoLib.glifLib._writeLib (glyphObject, element, validate) protected
Definition at line 1008 of file glifLib.py.
_writeNote()
fontTools.ufoLib.glifLib._writeNote (glyphObject, element, validate) protected
Definition at line 910 of file glifLib.py.
_writeUnicodes()
fontTools.ufoLib.glifLib._writeUnicodes (glyphObject, element, validate) protected
Definition at line 895 of file glifLib.py.
buildOutlineFormat1()
fontTools.ufoLib.glifLib.buildOutlineFormat1 (glyphObject, pen, outline, validate)
Definition at line 1398 of file glifLib.py.
buildOutlineFormat2()
fontTools.ufoLib.glifLib.buildOutlineFormat2 (glyphObject, pen, outline, identifiers, validate)
Definition at line 1489 of file glifLib.py.
glyphNameToFileName()
fontTools.ufoLib.glifLib.glyphNameToFileName (glyphName, existingFileNames)
Wrapper around the userNameToFileName function in filenames.py
Note that existingFileNames should be a set for large glyphsets
or performance will suffer.
Definition at line 641 of file glifLib.py.
readGlyphFromString()
fontTools.ufoLib.glifLib.readGlyphFromString (aString, glyphObject = None, pointPen = None, formatVersions = None, validate = True)
Read .glif data from a string into a glyph object.
The 'glyphObject' argument can be any kind of object (even None);
the readGlyphFromString() method will attempt to set the following
attributes on it:
width
        the advance width of the glyph
height
        the advance height of the glyph
unicodes
        a list of unicode values for this glyph
note
        a string
lib
        a dictionary containing custom data
image
        a dictionary containing image data
guidelines
        a list of guideline data dictionaries
anchors
        a list of anchor data dictionaries
All attributes are optional, in two ways:
1) An attribute *won't* be set if the .glif file doesn't
   contain data for it. 'glyphObject' will have to deal
   with default values itself.
2) If setting the attribute fails with an AttributeError
   (for example if the 'glyphObject' attribute is read-
   only), readGlyphFromString() will not propagate that
   exception, but ignore that attribute.
To retrieve outline information, you need to pass an object
conforming to the PointPen protocol as the 'pointPen' argument.
This argument may be None if you don't need the outline data.
The formatVersions optional argument define the GLIF format versions
that are allowed to be read.
The type is Optional[Iterable[Tuple[int, int], int]]. It can contain
either integers (for the major versions to be allowed, with minor
digits defaulting to 0), or tuples of integers to specify both
(major, minor) versions.
By default when formatVersions is None all the GLIF format versions
currently defined are allowed to be read.
``validate`` will validate the read data. It is set to ``True`` by default.
Definition at line 658 of file glifLib.py.
validateLayerInfoVersion3Data()
fontTools.ufoLib.glifLib.validateLayerInfoVersion3Data (infoData)
This performs very basic validation of the value for infoData
following the UFO 3 layerinfo.plist specification. The results
of this should not be interpretted as *correct* for the font
that they are part of. This merely indicates that the values
are of the proper type and, where the specification defines
a set range of possible values for an attribute, that the
value is in the accepted range.
Definition at line 1062 of file glifLib.py.
References _number(), fontTools.ufoLib.validators.anchorsValidator(), fontTools.ufoLib.validators.glyphLibValidator(), fontTools.ufoLib.validators.guidelinesValidator(), fontTools.ufoLib.validators.identifierValidator(), fontTools.ufoLib.validators.imageValidator(), and validateLayerInfoVersion3ValueForAttribute().
Referenced by fontTools.ufoLib.glifLib.GlyphSet.readLayerInfo(), and fontTools.ufoLib.glifLib.GlyphSet.writeLayerInfo().
validateLayerInfoVersion3ValueForAttribute()
fontTools.ufoLib.glifLib.validateLayerInfoVersion3ValueForAttribute (attr, value)
This performs very basic validation of the value for attribute
following the UFO 3 fontinfo.plist specification. The results
of this should not be interpretted as *correct* for the font
that they are part of. This merely indicates that the value
is of the proper type and, where the specification defines
a set range of possible values for an attribute, that the
value is in the accepted range.
Definition at line 1034 of file glifLib.py.
Referenced by validateLayerInfoVersion3Data().
writeGlyphToString()
fontTools.ufoLib.glifLib.writeGlyphToString (glyphName, glyphObject = None, drawPointsFunc = None, formatVersion = None, validate = True)
Return .glif data for a glyph as a string. The XML declaration's
encoding is always set to "UTF-8".
The 'glyphObject' argument can be any kind of object (even None);
the writeGlyphToString() method will attempt to get the following
attributes from it:
width
        the advance width of the glyph
height
        the advance height of the glyph
unicodes
        a list of unicode values for this glyph
note
        a string
lib
        a dictionary containing custom data
image
        a dictionary containing image data
guidelines
        a list of guideline data dictionaries
anchors
        a list of anchor data dictionaries
All attributes are optional: if 'glyphObject' doesn't
have the attribute, it will simply be skipped.
To write outline data to the .glif file, writeGlyphToString() needs
a function (any callable object actually) that will take one
argument: an object that conforms to the PointPen protocol.
The function will be called by writeGlyphToString(); it has to call the
proper PointPen methods to transfer the outline to the .glif file.
The GLIF format version can be specified with the formatVersion argument.
This accepts either a tuple of integers for (major, minor), or a single
integer for the major digit only (with minor digit implied as 0).
By default when formatVesion is None the latest GLIF format version will
be used; currently it's 2.0, which is equivalent to formatVersion=(2, 0).
An UnsupportedGLIFFormat exception is raised if the requested UFO
formatVersion is not supported.
``validate`` will validate the written data. It is set to ``True`` by default.
Definition at line 809 of file glifLib.py.
References _writeGlyphToBytes(), fontTools.ufoLib.validators.anchorsValidator(), fontTools.ufoLib.validators.glyphLibValidator(), fontTools.ufoLib.validators.guidelinesValidator(), and fontTools.ufoLib.validators.imageValidator().
Variable Documentation
__all__
list fontTools.ufoLib.glifLib.__all__ private
Initial value:
=  [
    "GlyphSet",
    "GlifLibError",
    "readGlyphFromString",
    "writeGlyphToString",
    "glyphNameToFileName",
]
Definition at line 38 of file glifLib.py.
_READ_GLYPH_FROM_TREE_FUNCS
dict fontTools.ufoLib.glifLib._READ_GLYPH_FROM_TREE_FUNCS protected
Initial value:
=  {
    GLIFFormatVersion.FORMAT_1_0: _readGlyphFromTreeFormat1,
    GLIFFormatVersion.FORMAT_2_0: _readGlyphFromTreeFormat2,
}
Definition at line 1327 of file glifLib.py.
_transformationInfo
list fontTools.ufoLib.glifLib._transformationInfo protected
Initial value:
=  [
    # field name, default value
    ("xScale", 1),
    ("xyScale", 0),
    ("yxScale", 0),
    ("yScale", 1),
    ("xOffset", 0),
    ("yOffset", 0),
]
Definition at line 1882 of file glifLib.py.
componentAttributesFormat1
dict fontTools.ufoLib.glifLib.componentAttributesFormat1
Initial value:
=  {
    "base",
    "xScale",
    "xyScale",
    "yxScale",
    "yScale",
    "xOffset",
    "yOffset",
}
Definition at line 1380 of file glifLib.py.
componentAttributesFormat2
dict fontTools.ufoLib.glifLib.componentAttributesFormat2 = componentAttributesFormat1 | {"identifier"}
Definition at line 1389 of file glifLib.py.
CONTENTS_FILENAME
str fontTools.ufoLib.glifLib.CONTENTS_FILENAME = "contents.plist"
Definition at line 53 of file glifLib.py.
contourAttributesFormat2
dict fontTools.ufoLib.glifLib.contourAttributesFormat2 = {"identifier"}
Definition at line 1379 of file glifLib.py.
LAYERINFO_FILENAME
str fontTools.ufoLib.glifLib.LAYERINFO_FILENAME = "layerinfo.plist"
Definition at line 54 of file glifLib.py.
layerInfoVersion3ValueData
dict fontTools.ufoLib.glifLib.layerInfoVersion3ValueData
Initial value:
=  {
    "color": dict(type=str, valueValidator=colorValidator),
    "lib": dict(type=dict, valueValidator=genericTypeValidator),
}
Definition at line 1028 of file glifLib.py.
logger
fontTools.ufoLib.glifLib.logger = logging.getLogger(__name__)
Definition at line 46 of file glifLib.py.
pointAttributesFormat1
dict fontTools.ufoLib.glifLib.pointAttributesFormat1 = {"x", "y", "type", "smooth", "name"}
Definition at line 1390 of file glifLib.py.
pointAttributesFormat2
dict fontTools.ufoLib.glifLib.pointAttributesFormat2 = pointAttributesFormat1 | {"identifier"}
Definition at line 1391 of file glifLib.py.
pointSmoothOptions
dict fontTools.ufoLib.glifLib.pointSmoothOptions = {"no", "yes"}
Definition at line 1392 of file glifLib.py.
pointTypeOptions
dict fontTools.ufoLib.glifLib.pointTypeOptions = {"move", "line", "offcurve", "curve", "qcurve"}
Definition at line 1393 of file glifLib.py.