Code Cloning Analysis: matplotlib.animation.FFMpegFileWriter Class Reference
matplotlib.animation.FFMpegFileWriter Class Reference
Protected Member Functions
_args (self)
Protected Member Functions inherited from matplotlib.animation.FFMpegBase
_supports_transparency (self)
Protected Member Functions inherited from matplotlib.animation.FileMovieWriter
_base_temp_name (self)
Protected Member Functions inherited from matplotlib.animation.MovieWriter
_adjust_frame_size (self)
_run (self)
Protected Member Functions inherited from matplotlib.animation.AbstractMovieWriter
_supports_transparency (self)
Additional Inherited Members
Public Member Functions inherited from matplotlib.animation.FFMpegBase
output_args (self)
Public Member Functions inherited from matplotlib.animation.FileMovieWriter
__init__ (self, *args, **kwargs)
setup (self, fig, outfile, dpi=None, frame_prefix=None)
__del__ (self)
frame_format (self)
frame_format (self, frame_format)
grab_frame (self, **savefig_kwargs)
finish (self)
Public Member Functions inherited from matplotlib.animation.MovieWriter
__init__ (self, fps=5, codec=None, bitrate=None, extra_args=None, metadata=None)
bin_path (cls)
isAvailable (cls)
Public Member Functions inherited from matplotlib.animation.AbstractMovieWriter
__init__ (self, fps=5, metadata=None, codec=None, bitrate=None)
frame_size (self)
saving (self, fig, outfile, dpi, *args, **kwargs)
Public Attributes inherited from matplotlib.animation.FFMpegBase
str codec = suffix[1:]
Public Attributes inherited from matplotlib.animation.FileMovieWriter
temp_prefix = str(Path(self._tmpdir.name, 'tmp'))
str fname_format_str = '%s%%07d.%s'
Public Attributes inherited from matplotlib.animation.MovieWriter
extra_args = extra_args
Public Attributes inherited from matplotlib.animation.AbstractMovieWriter
fps = fps
metadata = metadata if metadata is not None else {}
codec = mpl._val_or_rc(codec, 'animation.codec')
bitrate = mpl._val_or_rc(bitrate, 'animation.bitrate')
outfile = outfile
fig = fig
dpi = dpi
Static Public Attributes inherited from matplotlib.animation.MovieWriter
list supported_formats = ["rgba"]
Protected Attributes inherited from matplotlib.animation.FileMovieWriter
_tmpdir = TemporaryDirectory()
int _frame_counter = 0
_temp_paths = list()
_frame_format = frame_format
Protected Attributes inherited from matplotlib.animation.MovieWriter
_w
_h = self._adjust_frame_size()
_proc
Static Protected Attributes inherited from matplotlib.animation.FFMpegBase
str _exec_key = 'animation.ffmpeg_path'
str _args_key = 'animation.ffmpeg_args'
Detailed Description
File-based ffmpeg writer.
Frames are written to temporary files on disk and then stitched together at the end.
This effectively works as a slideshow input to ffmpeg with the fps passed as
``-framerate``, so see also `their notes on frame rates`_ for further details.
.. _their notes on frame rates: https://trac.ffmpeg.org/wiki/Slideshow#Framerates
Definition at line 604 of file animation.py.
Member Function Documentation
_args()
matplotlib.animation.FFMpegFileWriter._args (self) protected
Assemble list of encoder-specific command-line arguments.
Reimplemented from matplotlib.animation.MovieWriter.
Definition at line 617 of file animation.py.
References matplotlib.animation.FileMovieWriter._base_temp_name(), matplotlib.animation.FileMovieWriter._frame_counter, matplotlib.animation.FileMovieWriter._tmpdir, matplotlib.animation.MovieWriter.bin_path(), matplotlib.animation.AbstractMovieWriter.fps, matplotlib.animation.MovieWriter.frame_format, matplotlib.animation.MovieWriter.frame_size, and matplotlib.animation.FFMpegBase.output_args().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/animation.py