Code Cloning Analysis: fontTools.varLib.instancer Namespace Reference
fontTools.varLib.instancer Namespace Reference
Namespaces
namespace names
Classes
class _BaseAxisLimits
class _TupleVarStoreAdapter
class AxisLimits
class AxisTriple
class NormalizedAxisLimits
class NormalizedAxisTriple
class NormalizedAxisTripleAndDistances
class OverlapMode
Functions
AxisRange (minimum, maximum)
NormalizedAxisRange (minimum, maximum)
instantiateVARC (varfont, axisLimits)
instantiateTupleVariationStore (variations, axisLimits, origCoords=None, endPts=None)
changeTupleVariationsAxisLimits (variations, axisLimits)
changeTupleVariationAxisLimit (var, axisTag, axisLimit)
instantiateCFF2 (varfont, axisLimits, *, round=round, specialize=True, generalize=False, downgrade=False)
_instantiateGvarGlyph (glyphname, glyf, gvar, hMetrics, vMetrics, axisLimits, optimize=True)
instantiateGvarGlyph (varfont, glyphname, axisLimits, optimize=True)
instantiateGvar (varfont, axisLimits, optimize=True)
setCvarDeltas (cvt, deltas)
instantiateCvar (varfont, axisLimits)
setMvarDeltas (varfont, deltas)
verticalMetricsKeptInSync (varfont)
instantiateMVAR (varfont, axisLimits)
_remapVarIdxMap (table, attrName, varIndexMapping, glyphOrder)
_instantiateVHVAR (varfont, axisLimits, tableFields, *, round=round)
instantiateHVAR (varfont, axisLimits)
instantiateVVAR (varfont, axisLimits)
instantiateItemVariationStore (itemVarStore, fvarAxes, axisLimits, hierarchical=False)
instantiateOTL (varfont, axisLimits)
_isValidAvarSegmentMap (axisTag, segmentMap)
instantiateAvar (varfont, axisLimits)
isInstanceWithinAxisRanges (location, axisRanges)
instantiateFvar (varfont, axisLimits)
instantiateSTAT (varfont, axisLimits)
axisValuesFromAxisLimits (stat, axisLimits)
setMacOverlapFlags (glyfTable)
normalize (value, triple, avarMapping)
sanityCheckVariableTables (varfont)
instantiateVariableFont (varfont, axisLimits, inplace=False, optimize=True, overlap=OverlapMode.KEEP_AND_SET_FLAGS, updateFontNames=False, *, downgradeCFF2=False)
setRibbiBits (font)
Dict[str, Optional[AxisTriple]] parseLimits (Iterable[str] limits)
parseArgs (args)
main (args=None)
Variables
log = logging.getLogger("fontTools.varLib.instancer")
Detailed Description
 Partially instantiate a variable font.
The module exports an `instantiateVariableFont` function and CLI that allow to
create full instances (i.e. static fonts) from variable fonts, as well as "partial"
variable fonts that only contain a subset of the original variation space.
For example, if you wish to pin the width axis to a given location while also
restricting the weight axis to 400..700 range, you can do:
.. code-block:: sh
    $ fonttools varLib.instancer ./NotoSans-VF.ttf wdth=85 wght=400:700
See `fonttools varLib.instancer --help` for more info on the CLI options.
The module's entry point is the `instantiateVariableFont` function, which takes
a TTFont object and a dict specifying either axis coodinates or (min, max) ranges,
and returns a new TTFont representing either a partial VF, or full instance if all
the VF axes were given an explicit coordinate.
E.g. here's how to pin the wght axis at a given location in a wght+wdth variable
font, keeping only the deltas associated with the wdth axis:
.. code-block:: pycon
    >>>
    >> from fontTools import ttLib
    >> from fontTools.varLib import instancer
    >> varfont = ttLib.TTFont("path/to/MyVariableFont.ttf")
    >> [a.axisTag for a in varfont["fvar"].axes]  # the varfont's current axes
    ['wght', 'wdth']
    >> partial = instancer.instantiateVariableFont(varfont, {"wght": 300})
    >> [a.axisTag for a in partial["fvar"].axes]  # axes left after pinning 'wght'
    ['wdth']
If the input location specifies all the axes, the resulting instance is no longer
'variable' (same as using fontools varLib.mutator):
.. code-block:: pycon
    >>>
    >> instance = instancer.instantiateVariableFont(
    ...     varfont, {"wght": 700, "wdth": 67.5}
    ... )
    >> "fvar" not in instance
    True
If one just want to drop an axis at the default location, without knowing in
advance what the default value for that axis is, one can pass a `None` value:
.. code-block:: pycon
    >>>
    >> instance = instancer.instantiateVariableFont(varfont, {"wght": None})
    >> len(varfont["fvar"].axes)
    1
From the console script, this is equivalent to passing `wght=drop` as input.
This module is similar to fontTools.varLib.mutator, which it's intended to supersede.
Note that, unlike varLib.mutator, when an axis is not mentioned in the input
location, the varLib.instancer will keep the axis and the corresponding deltas,
whereas mutator implicitly drops the axis at its default coordinate.
The module supports all the following "levels" of instancing, which can of
course be combined:
L1
    dropping one or more axes while leaving the default tables unmodified;
    .. code-block:: pycon
        >>>
        >> font = instancer.instantiateVariableFont(varfont, {"wght": None})
L2
    dropping one or more axes while pinning them at non-default locations;
    .. code-block:: pycon
        >>>
        >> font = instancer.instantiateVariableFont(varfont, {"wght": 700})
L3
    restricting the range of variation of one or more axes, by setting either
    a new minimum or maximum, potentially -- though not necessarily -- dropping
    entire regions of variations that fall completely outside this new range.
    .. code-block:: pycon
        >>>
        >> font = instancer.instantiateVariableFont(varfont, {"wght": (100, 300)})
L4
    moving the default location of an axis, by specifying (min,defalt,max) values:
    .. code-block:: pycon
        >>>
        >> font = instancer.instantiateVariableFont(varfont, {"wght": (100, 300, 700)})
Currently only TrueType-flavored variable fonts (i.e. containing 'glyf' table)
are supported, but support for CFF2 variable fonts will be added soon.
The discussion and implementation of these features are tracked at
https://github.com/fonttools/fonttools/issues/1537
Function Documentation
_instantiateGvarGlyph()
fontTools.varLib.instancer._instantiateGvarGlyph (glyphname, glyf, gvar, hMetrics, vMetrics, axisLimits, optimize = True) protected
Definition at line 890 of file __init__.py.
_instantiateVHVAR()
fontTools.varLib.instancer._instantiateVHVAR (varfont, axisLimits, tableFields, * , round = round) protected
Definition at line 1083 of file __init__.py.
_isValidAvarSegmentMap()
fontTools.varLib.instancer._isValidAvarSegmentMap (axisTag, segmentMap) protected
Definition at line 1358 of file __init__.py.
_remapVarIdxMap()
fontTools.varLib.instancer._remapVarIdxMap (table, attrName, varIndexMapping, glyphOrder) protected
Definition at line 1076 of file __init__.py.
AxisRange()
fontTools.varLib.instancer.AxisRange (minimum, maximum)
Definition at line 146 of file __init__.py.
axisValuesFromAxisLimits()
fontTools.varLib.instancer.axisValuesFromAxisLimits (stat, axisLimits)
Definition at line 1519 of file __init__.py.
changeTupleVariationAxisLimit()
fontTools.varLib.instancer.changeTupleVariationAxisLimit (var, axisTag, axisLimit)
Definition at line 591 of file __init__.py.
changeTupleVariationsAxisLimits()
fontTools.varLib.instancer.changeTupleVariationsAxisLimits (variations, axisLimits)
Definition at line 582 of file __init__.py.
instantiateAvar()
fontTools.varLib.instancer.instantiateAvar (varfont, axisLimits)
Definition at line 1380 of file __init__.py.
instantiateCFF2()
fontTools.varLib.instancer.instantiateCFF2 (varfont, axisLimits, * , round = round, specialize = True, generalize = False, downgrade = False)
Definition at line 629 of file __init__.py.
instantiateCvar()
fontTools.varLib.instancer.instantiateCvar (varfont, axisLimits)
Definition at line 989 of file __init__.py.
instantiateFvar()
fontTools.varLib.instancer.instantiateFvar (varfont, axisLimits)
Definition at line 1460 of file __init__.py.
instantiateGvar()
fontTools.varLib.instancer.instantiateGvar (varfont, axisLimits, optimize = True)
Definition at line 952 of file __init__.py.
instantiateGvarGlyph()
fontTools.varLib.instancer.instantiateGvarGlyph (varfont, glyphname, axisLimits, optimize = True)
Remove?
https://github.com/fonttools/fonttools/pull/2266
Definition at line 940 of file __init__.py.
References instantiateTupleVariationStore().
instantiateHVAR()
fontTools.varLib.instancer.instantiateHVAR (varfont, axisLimits)
Definition at line 1153 of file __init__.py.
instantiateItemVariationStore()
fontTools.varLib.instancer.instantiateItemVariationStore (itemVarStore, fvarAxes, axisLimits, hierarchical = False)
Compute deltas at partial location, and update varStore in-place.
Remove regions in which all axes were instanced, or fall outside the new axis
limits. Scale the deltas of the remaining regions where only some of the axes
were instanced.
The number of VarData subtables, and the number of items within each, are
not modified, in order to keep the existing VariationIndex valid.
One may call VarStore.optimize() method after this to further optimize those.
Args:
    varStore: An otTables.VarStore object (Item Variation Store)
    fvarAxes: list of fvar's Axis objects
    axisLimits: NormalizedAxisLimits: mapping axis tags to normalized
        min/default/max axis coordinates. May not specify coordinates/ranges for
        all the fvar axes.
Returns:
    defaultDeltas: to be added to the default instance, of type dict of floats
        keyed by VariationIndex compound values: i.e. (outer << 16) + inner.
Definition at line 1249 of file __init__.py.
References instantiateItemVariationStore().
Referenced by instantiateItemVariationStore(), instantiateTupleVariationStore(), and verticalMetricsKeptInSync().
instantiateMVAR()
fontTools.varLib.instancer.instantiateMVAR (varfont, axisLimits)
Definition at line 1057 of file __init__.py.
instantiateOTL()
fontTools.varLib.instancer.instantiateOTL (varfont, axisLimits)
Definition at line 1299 of file __init__.py.
instantiateSTAT()
fontTools.varLib.instancer.instantiateSTAT (varfont, axisLimits)
Definition at line 1501 of file __init__.py.
instantiateTupleVariationStore()
fontTools.varLib.instancer.instantiateTupleVariationStore (variations, axisLimits, origCoords = None, endPts = None)
Instantiate TupleVariation list at the given location, or limit axes' min/max.
The 'variations' list of TupleVariation objects is modified in-place.
The 'axisLimits' (dict) maps axis tags (str) to NormalizedAxisTriple namedtuples
specifying (minimum, default, maximum) in the -1,0,+1 normalized space. Pinned axes
have minimum == default == maximum.
A 'full' instance (i.e. static font) is produced when all the axes are pinned to
single coordinates; a 'partial' instance (i.e. a less variable font) is produced
when some of the axes are omitted, or restricted with a new range.
Tuples that do not participate are kept as they are. Those that have 0 influence
at the given location are removed from the variation store.
Those that are fully instantiated (i.e. all their axes are being pinned) are also
removed from the variation store, their scaled deltas accummulated and returned, so
that they can be added by the caller to the default instance's coordinates.
Tuples that are only partially instantiated (i.e. not all the axes that they
participate in are being pinned) are kept in the store, and their deltas multiplied
by the scalar support of the axes to be pinned at the desired location.
Args:
    variations: List[TupleVariation] from either 'gvar' or 'cvar'.
    axisLimits: NormalizedAxisLimits: map from axis tags to (min, default, max)
        normalized coordinates for the full or partial instance.
    origCoords: GlyphCoordinates: default instance's coordinates for computing 'gvar'
        inferred points (cf. table__g_l_y_f._getCoordinatesAndControls).
    endPts: List[int]: indices of contour end points, for inferring 'gvar' deltas.
Returns:
    List[float]: the overall delta adjustment after applicable deltas were summed.
Definition at line 521 of file __init__.py.
References instantiateItemVariationStore(), and instantiateTupleVariationStore().
Referenced by instantiateGvarGlyph(), and instantiateTupleVariationStore().
instantiateVARC()
fontTools.varLib.instancer.instantiateVARC (varfont, axisLimits)
Definition at line 485 of file __init__.py.
instantiateVariableFont()
fontTools.varLib.instancer.instantiateVariableFont (varfont, axisLimits, inplace = False, optimize = True, overlap = OverlapMode.KEEP_AND_SET_FLAGS, updateFontNames = False, * , downgradeCFF2 = False)
Instantiate variable font, either fully or partially.
Depending on whether the `axisLimits` dictionary references all or some of the
input varfont's axes, the output font will either be a full instance (static
font) or a variable font with possibly less variation data.
Args:
    varfont: a TTFont instance, which must contain at least an 'fvar' table.
    axisLimits: a dict keyed by axis tags (str) containing the coordinates (float)
        along one or more axes where the desired instance will be located.
        If the value is `None`, the default coordinate as per 'fvar' table for
        that axis is used.
        The limit values can also be (min, max) tuples for restricting an
        axis's variation range. The default axis value must be included in
        the new range.
    inplace (bool): whether to modify input TTFont object in-place instead of
        returning a distinct object.
    optimize (bool): if False, do not perform IUP-delta optimization on the
        remaining 'gvar' table's deltas. Possibly faster, and might work around
        rendering issues in some buggy environments, at the cost of a slightly
        larger file size.
    overlap (OverlapMode): variable fonts usually contain overlapping contours, and
        some font rendering engines on Apple platforms require that the
        `OVERLAP_SIMPLE` and `OVERLAP_COMPOUND` flags in the 'glyf' table be set to
        force rendering using a non-zero fill rule. Thus we always set these flags
        on all glyphs to maximise cross-compatibility of the generated instance.
        You can disable this by passing OverlapMode.KEEP_AND_DONT_SET_FLAGS.
        If you want to remove the overlaps altogether and merge overlapping
        contours and components, you can pass OverlapMode.REMOVE (or
        REMOVE_AND_IGNORE_ERRORS to not hard-fail on tricky glyphs). Note that this
        requires the skia-pathops package (available to pip install).
        The overlap parameter only has effect when generating full static instances.
    updateFontNames (bool): if True, update the instantiated font's name table using
        the Axis Value Tables from the STAT table. The name table and the style bits
        in the head and OS/2 table will be updated so they conform to the R/I/B/BI
        model. If the STAT table is missing or an Axis Value table is missing for
        a given axis coordinate, a ValueError will be raised.
    downgradeCFF2 (bool): if True, downgrade the CFF2 table to CFF table when possible
        ie. full instancing of all axes. This is useful for compatibility with older
        software that does not support CFF2. Defaults to False. Note that this
        operation also removes overlaps within glyph shapes, as CFF does not support
        overlaps but CFF2 does.
Definition at line 1588 of file __init__.py.
References setRibbiBits().
Referenced by main().
instantiateVVAR()
fontTools.varLib.instancer.instantiateVVAR (varfont, axisLimits)
Definition at line 1157 of file __init__.py.
isInstanceWithinAxisRanges()
fontTools.varLib.instancer.isInstanceWithinAxisRanges (location, axisRanges)
Definition at line 1451 of file __init__.py.
main()
fontTools.varLib.instancer.main (args = None)
Partially instantiate a variable font
Definition at line 1914 of file __init__.py.
References instantiateVariableFont(), and parseArgs().
normalize()
fontTools.varLib.instancer.normalize (value, triple, avarMapping)
Definition at line 1572 of file __init__.py.
NormalizedAxisRange()
fontTools.varLib.instancer.NormalizedAxisRange (minimum, maximum)
Definition at line 155 of file __init__.py.
parseArgs()
fontTools.varLib.instancer.parseArgs (args)
Parse argv.
Returns:
    3-tuple (infile, axisLimits, options)
    axisLimits is either a Dict[str, Optional[float]], for pinning variation axes
    to specific coordinates along those axes (with `None` as a placeholder for an
    axis' default value); or a Dict[str, Tuple(float, float)], meaning limit this
    axis to min/max range.
    Axes locations are in user-space coordinates, as defined in the "fvar" table.
Definition at line 1792 of file __init__.py.
Referenced by main().
parseLimits()
Dict[str, Optional[AxisTriple]] fontTools.varLib.instancer.parseLimits (Iterable[str] limits)
Definition at line 1763 of file __init__.py.
sanityCheckVariableTables()
fontTools.varLib.instancer.sanityCheckVariableTables (varfont)
Definition at line 1580 of file __init__.py.
setCvarDeltas()
fontTools.varLib.instancer.setCvarDeltas (cvt, deltas)
Definition at line 983 of file __init__.py.
setMacOverlapFlags()
fontTools.varLib.instancer.setMacOverlapFlags (glyfTable)
Definition at line 1559 of file __init__.py.
setMvarDeltas()
fontTools.varLib.instancer.setMvarDeltas (varfont, deltas)
Definition at line 1003 of file __init__.py.
setRibbiBits()
fontTools.varLib.instancer.setRibbiBits (font)
Set the `head.macStyle` and `OS/2.fsSelection` style bits
appropriately.
Definition at line 1726 of file __init__.py.
Referenced by instantiateVariableFont().
verticalMetricsKeptInSync()
fontTools.varLib.instancer.verticalMetricsKeptInSync (varfont)
Ensure hhea vertical metrics stay in sync with OS/2 ones after instancing.
When applying MVAR deltas to the OS/2 table, if the ascender, descender and
line gap change but they were the same as the respective hhea metrics in the
original font, this context manager ensures that hhea metrcs also get updated
accordingly.
The MVAR spec only has tags for the OS/2 metrics, but it is common in fonts
to have the hhea metrics be equal to those for compat reasons.
https://learn.microsoft.com/en-us/typography/opentype/spec/mvar
https://googlefonts.github.io/gf-guide/metrics.html#7-hhea-and-typo-metrics-should-be-equal
https://github.com/fonttools/fonttools/issues/3297
Definition at line 1021 of file __init__.py.
References instantiateItemVariationStore(), and verticalMetricsKeptInSync().
Referenced by verticalMetricsKeptInSync().
Variable Documentation
log
fontTools.varLib.instancer.log = logging.getLogger("fontTools.varLib.instancer")
Definition at line 143 of file __init__.py.