Code Cloning Analysis: numpy.core.tests.test_half.TestHalf Class Reference
numpy.core.tests.test_half.TestHalf Class Reference
Public Member Functions
setup_method (self)
test_half_conversions (self)
test_half_conversion_to_string (self, string_dt)
test_half_conversion_from_string (self, string_dt)
test_half_conversion_rounding (self, float_t, shift, offset)
test_half_conversion_denormal_round_even (self, float_t, uint_t, bits)
test_nans_infs (self)
test_half_values (self)
test_half_rounding (self)
test_half_correctness (self)
test_half_ordering (self)
test_half_funcs (self)
test_spacing_nextafter (self)
test_half_ufuncs (self)
test_half_coercion (self, weak_promotion)
test_half_fpe (self)
test_half_array_interface (self)
Public Attributes
all_f16 = np.arange(0x10000, dtype=uint16)
all_f32 = np.array(self.all_f16, dtype=float32)
all_f64 = np.array(self.all_f16, dtype=float64)
nonan_f16
nonan_f32 = np.array(self.nonan_f16, dtype=float32)
nonan_f64 = np.array(self.nonan_f16, dtype=float64)
finite_f16 = self.nonan_f16[1:-1]
finite_f32 = self.nonan_f32[1:-1]
finite_f64 = self.nonan_f64[1:-1]
Detailed Description
Definition at line 19 of file test_half.py.
Member Function Documentation
setup_method()
numpy.core.tests.test_half.TestHalf.setup_method (self)
Definition at line 20 of file test_half.py.
test_half_array_interface()
numpy.core.tests.test_half.TestHalf.test_half_array_interface (self)
Test that half is compatible with __array_interface__
Definition at line 562 of file test_half.py.
test_half_coercion()
numpy.core.tests.test_half.TestHalf.test_half_coercion (self, weak_promotion)
Test that half gets coerced properly with the other types
Definition at line 464 of file test_half.py.
test_half_conversion_denormal_round_even()
numpy.core.tests.test_half.TestHalf.test_half_conversion_denormal_round_even (self, float_t, uint_t, bits)
Definition at line 153 of file test_half.py.
test_half_conversion_from_string()
numpy.core.tests.test_half.TestHalf.test_half_conversion_from_string (self, string_dt)
Definition at line 89 of file test_half.py.
test_half_conversion_rounding()
numpy.core.tests.test_half.TestHalf.test_half_conversion_rounding (self, float_t, shift, offset)
Definition at line 97 of file test_half.py.
test_half_conversion_to_string()
numpy.core.tests.test_half.TestHalf.test_half_conversion_to_string (self, string_dt)
Definition at line 79 of file test_half.py.
test_half_conversions()
numpy.core.tests.test_half.TestHalf.test_half_conversions (self)
Checks that all 16-bit values survive conversion
   to/from 32-bit and 64-bit float
Definition at line 43 of file test_half.py.
References numpy.core.fromnumeric.all(), all_f16, all_f32, all_f64, numpy.core.fromnumeric.any(), and nonan_f16.
test_half_correctness()
numpy.core.tests.test_half.TestHalf.test_half_correctness (self)
Take every finite float16, and check the casting functions with
   a manual conversion.
Definition at line 255 of file test_half.py.
References finite_f16, finite_f32, and finite_f64.
test_half_fpe()
numpy.core.tests.test_half.TestHalf.test_half_fpe (self)
Definition at line 497 of file test_half.py.
test_half_funcs()
numpy.core.tests.test_half.TestHalf.test_half_funcs (self)
Test the various ArrFuncs
Definition at line 314 of file test_half.py.
test_half_ordering()
numpy.core.tests.test_half.TestHalf.test_half_ordering (self)
Make sure comparisons are working right
Definition at line 291 of file test_half.py.
References numpy.core.fromnumeric.all(), numpy.core.fromnumeric.any(), and nonan_f16.
test_half_rounding()
numpy.core.tests.test_half.TestHalf.test_half_rounding (self)
Checks that rounding when converting to half is correct
Definition at line 224 of file test_half.py.
test_half_ufuncs()
numpy.core.tests.test_half.TestHalf.test_half_ufuncs (self)
Test the various ufuncs
Definition at line 399 of file test_half.py.
test_half_values()
numpy.core.tests.test_half.TestHalf.test_half_values (self)
Confirms a small number of known half values
Definition at line 203 of file test_half.py.
test_nans_infs()
numpy.core.tests.test_half.TestHalf.test_nans_infs (self)
Definition at line 173 of file test_half.py.
test_spacing_nextafter()
numpy.core.tests.test_half.TestHalf.test_spacing_nextafter (self)
Test np.spacing and np.nextafter
Definition at line 354 of file test_half.py.
Member Data Documentation
all_f16
numpy.core.tests.test_half.TestHalf.all_f16 = np.arange(0x10000, dtype=uint16)
Definition at line 22 of file test_half.py.
Referenced by test_half_conversions().
all_f32
numpy.core.tests.test_half.TestHalf.all_f32 = np.array(self.all_f16, dtype=float32)
Definition at line 27 of file test_half.py.
Referenced by test_half_conversions().
all_f64
numpy.core.tests.test_half.TestHalf.all_f64 = np.array(self.all_f16, dtype=float64)
Definition at line 28 of file test_half.py.
Referenced by test_half_conversions().
finite_f16
numpy.core.tests.test_half.TestHalf.finite_f16 = self.nonan_f16[1:-1]
Definition at line 39 of file test_half.py.
Referenced by test_half_correctness().
finite_f32
numpy.core.tests.test_half.TestHalf.finite_f32 = self.nonan_f32[1:-1]
Definition at line 40 of file test_half.py.
Referenced by test_half_correctness().
finite_f64
numpy.core.tests.test_half.TestHalf.finite_f64 = self.nonan_f64[1:-1]
Definition at line 41 of file test_half.py.
Referenced by test_half_correctness().
nonan_f16
numpy.core.tests.test_half.TestHalf.nonan_f16
Initial value:
=  np.concatenate(
                                (np.arange(0xfc00, 0x7fff, -1, dtype=uint16),
                                 np.arange(0x0000, 0x7c01, 1, dtype=uint16)))
Definition at line 31 of file test_half.py.
Referenced by test_half_conversions(), and test_half_ordering().
nonan_f32
numpy.core.tests.test_half.TestHalf.nonan_f32 = np.array(self.nonan_f16, dtype=float32)
Definition at line 35 of file test_half.py.
nonan_f64
numpy.core.tests.test_half.TestHalf.nonan_f64 = np.array(self.nonan_f16, dtype=float64)
Definition at line 36 of file test_half.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/core/tests/test_half.py