Code Cloning Analysis: sklearn.feature_extraction.text.TfidfTransformer Class Reference
sklearn.feature_extraction.text.TfidfTransformer Class Reference
Public Member Functions
__init__ (self, *, norm="l2", use_idf=True, smooth_idf=True, sublinear_tf=False)
fit (self, X, y=None)
transform (self, X, copy=True)
__sklearn_tags__ (self)
Public Member Functions inherited from sklearn.base.OneToOneFeatureMixin
get_feature_names_out (self, input_features=None)
Public Member Functions inherited from sklearn.base.TransformerMixin
__sklearn_tags__ (self)
fit_transform (self, X, y=None, **fit_params)
Public Member Functions inherited from sklearn.utils._set_output._SetOutputMixin
__init_subclass__ (cls, auto_wrap_output_keys=("transform",), **kwargs)
set_output (self, *, transform=None)
Public Member Functions inherited from sklearn.base.BaseEstimator
get_params (self, deep=True)
set_params (self, **params)
__sklearn_clone__ (self)
__repr__ (self, N_CHAR_MAX=700)
__getstate__ (self)
__setstate__ (self, state)
__sklearn_tags__ (self)
Public Member Functions inherited from sklearn.utils._metadata_requests._MetadataRequester
set_fit_request (self, **kwargs)
set_partial_fit_request (self, **kwargs)
set_predict_request (self, **kwargs)
set_predict_proba_request (self, **kwargs)
set_predict_log_proba_request (self, **kwargs)
set_decision_function_request (self, **kwargs)
set_score_request (self, **kwargs)
set_split_request (self, **kwargs)
set_transform_request (self, **kwargs)
set_inverse_transform_request (self, **kwargs)
__init_subclass__ (cls, **kwargs)
get_metadata_routing (self)
Public Attributes
norm = norm
use_idf = use_idf
smooth_idf = smooth_idf
sublinear_tf = sublinear_tf
idf_ = np.full_like(df, fill_value=n_samples, dtype=dtype)
Additional Inherited Members
Protected Member Functions inherited from sklearn.base.BaseEstimator
_get_param_names (cls)
_get_params_html (self, deep=True)
_validate_params (self)
Protected Member Functions inherited from sklearn.utils._repr_html.base.ReprHTMLMixin
_repr_html_ (self)
_repr_html_inner (self)
_repr_mimebundle_ (self, **kwargs)
Protected Member Functions inherited from sklearn.utils._repr_html.base._HTMLDocumentationLinkMixin
_doc_link_template (self)
_doc_link_template (self, value)
_get_doc_link (self)
Protected Member Functions inherited from sklearn.utils._metadata_requests._MetadataRequester
_build_request_for_signature (cls, router, method)
_get_default_requests (cls)
_get_metadata_request (self)
Protected Attributes inherited from sklearn.utils._set_output._SetOutputMixin
_sklearn_auto_wrap_output_keys = set()
dict _sklearn_output_config = {}
Protected Attributes inherited from sklearn.base.BaseEstimator
_parameter_constraints
Static Protected Attributes inherited from sklearn.base.BaseEstimator
_html_repr = estimator_html_repr
Static Protected Attributes inherited from sklearn.utils._repr_html.base._HTMLDocumentationLinkMixin
str _doc_link_module = "sklearn"
_doc_link_url_param_generator = None
Detailed Description
Transform a count matrix to a normalized tf or tf-idf representation.
Tf means term-frequency while tf-idf means term-frequency times inverse
document-frequency. This is a common term weighting scheme in information
retrieval, that has also found good use in document classification.
The goal of using tf-idf instead of the raw frequencies of occurrence of a
token in a given document is to scale down the impact of tokens that occur
very frequently in a given corpus and that are hence empirically less
informative than features that occur in a small fraction of the training
corpus.
The formula that is used to compute the tf-idf for a term t of a document d
in a document set is tf-idf(t, d) = tf(t, d) * idf(t), and the idf is
computed as idf(t) = log [ n / df(t) ] + 1 (if ``smooth_idf=False``), where
n is the total number of documents in the document set and df(t) is the
document frequency of t; the document frequency is the number of documents
in the document set that contain the term t. The effect of adding "1" to
the idf in the equation above is that terms with zero idf, i.e., terms
that occur in all documents in a training set, will not be entirely
ignored.
(Note that the idf formula above differs from the standard textbook
notation that defines the idf as
idf(t) = log [ n / (df(t) + 1) ]).
If ``smooth_idf=True`` (the default), the constant "1" is added to the
numerator and denominator of the idf as if an extra document was seen
containing every term in the collection exactly once, which prevents
zero divisions: idf(t) = log [ (1 + n) / (1 + df(t)) ] + 1.
Furthermore, the formulas used to compute tf and idf depend
on parameter settings that correspond to the SMART notation used in IR
as follows:
Tf is "n" (natural) by default, "l" (logarithmic) when
``sublinear_tf=True``.
Idf is "t" when use_idf is given, "n" (none) otherwise.
Normalization is "c" (cosine) when ``norm='l2'``, "n" (none)
when ``norm=None``.
Read more in the :ref:`User Guide <text_feature_extraction>`.
Parameters
----------
norm : {'l1', 'l2'} or None, default='l2'
    Each output row will have unit norm, either:
    - 'l2': Sum of squares of vector elements is 1. The cosine
      similarity between two vectors is their dot product when l2 norm has
      been applied.
    - 'l1': Sum of absolute values of vector elements is 1.
      See :func:`~sklearn.preprocessing.normalize`.
    - None: No normalization.
use_idf : bool, default=True
    Enable inverse-document-frequency reweighting. If False, idf(t) = 1.
smooth_idf : bool, default=True
    Smooth idf weights by adding one to document frequencies, as if an
    extra document was seen containing every term in the collection
    exactly once. Prevents zero divisions.
sublinear_tf : bool, default=False
    Apply sublinear tf scaling, i.e. replace tf with 1 + log(tf).
Attributes
----------
idf_ : array of shape (n_features)
    The inverse document frequency (IDF) vector; only defined
    if  ``use_idf`` is True.
    .. versionadded:: 0.20
n_features_in_ : int
    Number of features seen during :term:`fit`.
    .. versionadded:: 1.0
feature_names_in_ : ndarray of shape (`n_features_in_`,)
    Names of features seen during :term:`fit`. Defined only when `X`
    has feature names that are all strings.
    .. versionadded:: 1.0
See Also
--------
CountVectorizer : Transforms text into a sparse matrix of n-gram counts.
TfidfVectorizer : Convert a collection of raw documents to a matrix of
    TF-IDF features.
HashingVectorizer : Convert a collection of text documents to a matrix
    of token occurrences.
References
----------
.. [Yates2011] R. Baeza-Yates and B. Ribeiro-Neto (2011). Modern
               Information Retrieval. Addison Wesley, pp. 68-74.
.. [MRS2008] C.D. Manning, P. Raghavan and H. Schütze  (2008).
               Introduction to Information Retrieval. Cambridge University
               Press, pp. 118-120.
Examples
--------
>>> from sklearn.feature_extraction.text import TfidfTransformer
>>> from sklearn.feature_extraction.text import CountVectorizer
>>> from sklearn.pipeline import Pipeline
>>> corpus = ['this is the first document',
...           'this document is the second document',
...           'and this is the third one',
...           'is this the first document']
>>> vocabulary = ['this', 'document', 'first', 'is', 'second', 'the',
...               'and', 'one']
>>> pipe = Pipeline([('count', CountVectorizer(vocabulary=vocabulary)),
...                  ('tfid', TfidfTransformer())]).fit(corpus)
>>> pipe['count'].transform(corpus).toarray()
array([[1, 1, 1, 1, 0, 1, 0, 0],
       [1, 2, 0, 1, 1, 1, 0, 0],
       [1, 0, 0, 1, 0, 1, 1, 1],
       [1, 1, 1, 1, 0, 1, 0, 0]])
>>> pipe['tfid'].idf_
array([1.        , 1.22314355, 1.51082562, 1.        , 1.91629073,
       1.        , 1.91629073, 1.91629073])
>>> pipe.transform(corpus).shape
(4, 8)
Definition at line 1490 of file text.py.
Constructor & Destructor Documentation
__init__()
sklearn.feature_extraction.text.TfidfTransformer.__init__ (self, * , norm = "l2", use_idf = True, smooth_idf = True, sublinear_tf = False)
Definition at line 1628 of file text.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params().
Member Function Documentation
__sklearn_tags__()
sklearn.feature_extraction.text.TfidfTransformer.__sklearn_tags__ (self)
Definition at line 1725 of file text.py.
fit()
sklearn.feature_extraction.text.TfidfTransformer.fit (self, X, y = None)
Learn the idf vector (global term weights).
Parameters
----------
X : sparse matrix of shape (n_samples, n_features)
    A matrix of term/token counts.
y : None
    This parameter is not needed to compute tf-idf.
Returns
-------
self : object
    Fitted transformer.
Definition at line 1635 of file text.py.
Referenced by sklearn.cluster._kmeans._BaseKMeans.fit_predict(), sklearn.neighbors._lof.LocalOutlierFactor.fit_predict(), sklearn.cluster._kmeans._BaseKMeans.fit_transform(), sklearn.manifold._spectral_embedding.SpectralEmbedding.fit_transform(), sklearn.neighbors._graph.KNeighborsTransformer.fit_transform(), sklearn.neighbors._graph.RadiusNeighborsTransformer.fit_transform(), sklearn.preprocessing._label.LabelBinarizer.fit_transform(), sklearn.preprocessing._label.MultiLabelBinarizer.fit_transform(), sklearn.tests.metadata_routing_common.ConsumingTransformer.fit_transform(), and sklearn.utils.tests.test_estimator_checks.SparseTransformer.fit_transform().
transform()
sklearn.feature_extraction.text.TfidfTransformer.transform (self, X, copy = True)
Transform a count matrix to a tf or tf-idf representation.
Parameters
----------
X : sparse matrix of (n_samples, n_features)
    A matrix of term/token counts.
copy : bool, default=True
    Whether to copy X and operate on the copy or perform in-place
    operations. `copy=False` will only be effective with CSR sparse matrix.
Returns
-------
vectors : sparse matrix of shape (n_samples, n_features)
    Tf-idf-weighted document-term matrix.
Definition at line 1682 of file text.py.
Referenced by sklearn.preprocessing._function_transformer.FunctionTransformer._check_inverse_transform(), sklearn.feature_selection._rfe.RFE.decision_function(), PIL.ImageCms.Flags.GRIDPOINTS(), sklearn.ensemble._stacking._BaseStacking.predict(), sklearn.feature_selection._rfe.RFE.predict(), sklearn.feature_selection._rfe.RFE.predict_log_proba(), sklearn.feature_selection._rfe.RFE.predict_proba(), sklearn.feature_selection._rfe.RFE.score(), and sklearn.preprocessing._polynomial.PolynomialFeatures.transform().
Member Data Documentation
idf_
sklearn.feature_extraction.text.TfidfTransformer.idf_ = np.full_like(df, fill_value=n_samples, dtype=dtype)
Definition at line 1674 of file text.py.
norm
sklearn.feature_extraction.text.TfidfTransformer.norm = norm
Definition at line 1629 of file text.py.
Referenced by matplotlib.contour.ContourSet.__init__(), matplotlib.contour.ContourSet._get_lowers_and_uppers(), matplotlib.contour.ContourSet._process_colors(), sklearn.naive_bayes.ComplementNB._update_feature_log_prob(), and sklearn.preprocessing._data.Normalizer.transform().
smooth_idf
sklearn.feature_extraction.text.TfidfTransformer.smooth_idf = smooth_idf
Definition at line 1631 of file text.py.
sublinear_tf
sklearn.feature_extraction.text.TfidfTransformer.sublinear_tf = sublinear_tf
Definition at line 1632 of file text.py.
use_idf
sklearn.feature_extraction.text.TfidfTransformer.use_idf = use_idf
Definition at line 1630 of file text.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/sklearn/feature_extraction/text.py