Code Cloning Analysis: pandas.core.window.expanding.Expanding Class Reference
pandas.core.window.expanding.Expanding Class Reference
Public Member Functions
None __init__ (self, NDFrame obj, int min_periods=1, Axis axis=0, str method="single", selection=None)
aggregate (self, func, *args, **kwargs)
count (self, bool numeric_only=False)
apply (self, Callable[..., Any] func, bool raw=False, Literal["cython", "numba"]|None engine=None, dict[str, bool]|None engine_kwargs=None, tuple[Any,...]|None args=None, dict[str, Any]|None kwargs=None)
sum (self, bool numeric_only=False, Literal["cython", "numba"]|None engine=None, dict[str, bool]|None engine_kwargs=None)
max (self, bool numeric_only=False, Literal["cython", "numba"]|None engine=None, dict[str, bool]|None engine_kwargs=None)
min (self, bool numeric_only=False, Literal["cython", "numba"]|None engine=None, dict[str, bool]|None engine_kwargs=None)
mean (self, bool numeric_only=False, Literal["cython", "numba"]|None engine=None, dict[str, bool]|None engine_kwargs=None)
median (self, bool numeric_only=False, Literal["cython", "numba"]|None engine=None, dict[str, bool]|None engine_kwargs=None)
std (self, int ddof=1, bool numeric_only=False, Literal["cython", "numba"]|None engine=None, dict[str, bool]|None engine_kwargs=None)
var (self, int ddof=1, bool numeric_only=False, Literal["cython", "numba"]|None engine=None, dict[str, bool]|None engine_kwargs=None)
sem (self, int ddof=1, bool numeric_only=False)
skew (self, bool numeric_only=False)
kurt (self, bool numeric_only=False)
quantile (self, float q, QuantileInterpolation interpolation="linear", bool numeric_only=False)
rank (self, WindowingRankType method="average", bool ascending=True, bool pct=False, bool numeric_only=False)
cov (self, DataFrame|Series|None other=None, bool|None pairwise=None, int ddof=1, bool numeric_only=False)
corr (self, DataFrame|Series|None other=None, bool|None pairwise=None, int ddof=1, bool numeric_only=False)
Public Member Functions inherited from pandas.core.window.rolling.BaseWindow
None __init__ (self, NDFrame obj, window=None, int|None min_periods=None, bool|None center=False, str|None win_type=None, Axis axis=0, str|Index|None on=None, str|None closed=None, int|None step=None, str method="single", *, selection=None)
__getattr__ (self, str attr)
str __repr__ (self)
Iterator __iter__ (self)
Public Member Functions inherited from pandas.core.base.SelectionMixin
int ndim (self)
__getitem__ (self, key)
Protected Member Functions
BaseIndexer _get_window_indexer (self)
Protected Member Functions inherited from pandas.core.window.rolling.RollingAndExpandingMixin
Callable[[np.ndarray, np.ndarray, np.ndarray, int], np.ndarray] _generate_cython_apply_func (self, tuple[Any,...] args, dict[str, Any] kwargs, bool|np.bool_ raw, Callable[..., Any] function)
Protected Member Functions inherited from pandas.core.window.rolling.BaseWindow
None _validate (self)
None _check_window_bounds (self, np.ndarray start, np.ndarray end, int num_vals)
Index _slice_axis_for_step (self, Index index, Sized|None result=None)
None _validate_numeric_only (self, str name, bool numeric_only)
NDFrameT _make_numeric_only (self, NDFrameT obj)
NDFrameT _create_data (self, NDFrameT obj, bool numeric_only=False)
_gotitem (self, key, ndim, subset=None)
_dir_additions (self)
np.ndarray _prep_values (self, ArrayLike values)
None _insert_on_column (self, DataFrame result, DataFrame obj)
npt.NDArray[np.int64]|None _index_array (self)
DataFrame _resolve_output (self, DataFrame out, DataFrame obj)
Series _apply_series (self, Callable[..., ArrayLike] homogeneous_func, str|None name=None)
DataFrame|Series _apply_columnwise (self, Callable[..., ArrayLike] homogeneous_func, str name, bool numeric_only=False)
DataFrame|Series _apply_tablewise (self, Callable[..., ArrayLike] homogeneous_func, str|None name=None, bool numeric_only=False)
DataFrame|Series _apply_pairwise (self, DataFrame|Series target, DataFrame|Series|None other, bool|None pairwise, Callable[[DataFrame|Series, DataFrame|Series], DataFrame|Series] func, bool numeric_only)
_apply (self, Callable[..., Any] func, str name, bool numeric_only=False, tuple[Any,...] numba_args=(), **kwargs)
_numba_apply (self, Callable[..., Any] func, dict[str, bool]|None engine_kwargs=None, **func_kwargs)
Protected Member Functions inherited from pandas.core.base.SelectionMixin
_selection_list (self)
_selected_obj (self)
_obj_with_exclusions (self)
_infer_selection (self, key, Series|DataFrame subset)
Additional Inherited Members
Public Attributes inherited from pandas.core.window.rolling.BaseWindow
on = on
closed = closed
step = step
window = window
min_periods = min_periods
center = center
win_type = win_type
int axis = obj._get_axis_number(axis) if axis is not None else None
str method = method
Public Attributes inherited from pandas.core.base.SelectionMixin
obj
Static Public Attributes inherited from pandas.core.base.SelectionMixin
frozenset exclusions [Hashable]
agg = aggregate
Protected Attributes inherited from pandas.core.window.rolling.BaseWindow
int|None _win_freq_i8 = None
_on = self.obj.index
Protected Attributes inherited from pandas.core.base.SelectionMixin
_selection_list
Static Protected Attributes inherited from pandas.core.window.rolling.BaseWindow
list _attributes = []
Static Protected Attributes inherited from pandas.core.base.SelectionMixin
IndexLabel _selection = None
list _internal_names = ["_cache", "__setstate__"]
_internal_names_set = set(_internal_names)
Detailed Description
Provide expanding window calculations.
Parameters
----------
min_periods : int, default 1
    Minimum number of observations in window required to have a value;
    otherwise, result is ``np.nan``.
axis : int or str, default 0
    If ``0`` or ``'index'``, roll across the rows.
    If ``1`` or ``'columns'``, roll across the columns.
    For `Series` this parameter is unused and defaults to 0.
method : str {'single', 'table'}, default 'single'
    Execute the rolling operation per single column or row (``'single'``)
    or over the entire object (``'table'``).
    This argument is only implemented when specifying ``engine='numba'``
    in the method call.
    .. versionadded:: 1.3.0
Returns
-------
pandas.api.typing.Expanding
See Also
--------
rolling : Provides rolling window calculations.
ewm : Provides exponential weighted functions.
Notes
-----
See :ref:`Windowing Operations <window.expanding>` for further usage details
and examples.
Examples
--------
>>> df = pd.DataFrame({"B": [0, 1, 2, np.nan, 4]})
>>> df
     B
0  0.0
1  1.0
2  2.0
3  NaN
4  4.0
**min_periods**
Expanding sum with 1 vs 3 observations needed to calculate a value.
>>> df.expanding(1).sum()
     B
0  0.0
1  1.0
2  3.0
3  3.0
4  7.0
>>> df.expanding(3).sum()
     B
0  NaN
1  NaN
2  3.0
3  3.0
4  7.0
Definition at line 51 of file expanding.py.
Constructor & Destructor Documentation
__init__()
None pandas.core.window.expanding.Expanding.__init__ (self, NDFrame obj, int min_periods = 1, Axis axis = 0, str method = "single", selection = None)
Definition at line 124 of file expanding.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_get_window_indexer()
BaseIndexer pandas.core.window.expanding.Expanding._get_window_indexer (self) protected
Return an indexer class that will compute the window start and end bounds
Reimplemented from pandas.core.window.rolling.BaseWindow.
Reimplemented in pandas.core.window.expanding.ExpandingGroupby.
Definition at line 140 of file expanding.py.
Referenced by pandas.core.window.rolling.BaseWindow.__repr__(), and pandas.core.window.rolling.BaseWindow._apply().
aggregate()
pandas.core.window.expanding.Expanding.aggregate (self, func, * args, ** kwargs)
Reimplemented from pandas.core.window.rolling.BaseWindow.
Definition at line 177 of file expanding.py.
apply()
pandas.core.window.expanding.Expanding.apply (self, Callable[..., Any] func, bool raw = False, Literal["cython", "numba"] | None engine = None, dict[str, bool] | None engine_kwargs = None, tuple[Any, ...] | None args = None, dict[str, Any] | None kwargs = None)
Reimplemented from pandas.core.window.rolling.RollingAndExpandingMixin.
Definition at line 231 of file expanding.py.
Referenced by pandas.core.window.rolling.BaseWindow._apply(), pandas.core.generic.NDFrame.backfill(), pandas.io.formats.style.Styler.background_gradient(), pandas.io.formats.style.Styler.bar(), sklearn.ensemble._forest.RandomTreesEmbedding.fit_transform(), PIL.ImageCms.Flags.GRIDPOINTS(), pandas.io.formats.style.Styler.highlight_between(), pandas.io.formats.style.Styler.highlight_max(), pandas.io.formats.style.Styler.highlight_min(), pandas.io.formats.style.Styler.highlight_null(), pandas.io.formats.style.Styler.highlight_quantile(), and sklearn.ensemble._forest.RandomTreesEmbedding.transform().
corr()
pandas.core.window.expanding.Expanding.corr (self, DataFrame | Series | None other = None, bool | None pairwise = None, int ddof = 1, bool numeric_only = False)
Reimplemented from pandas.core.window.rolling.RollingAndExpandingMixin.
Definition at line 930 of file expanding.py.
count()
pandas.core.window.expanding.Expanding.count (self, bool numeric_only = False)
Reimplemented from pandas.core.window.rolling.RollingAndExpandingMixin.
Definition at line 204 of file expanding.py.
Referenced by pandas.core.window.rolling.Rolling._validate_datetimelike_monotonic(), PIL.ImageStat.Stat.mean(), PIL.ImageStat.Stat.median(), PIL.ImageStat.Stat.rms(), and PIL.ImageStat.Stat.var().
cov()
pandas.core.window.expanding.Expanding.cov (self, DataFrame | Series | None other = None, bool | None pairwise = None, int ddof = 1, bool numeric_only = False)
Reimplemented from pandas.core.window.rolling.RollingAndExpandingMixin.
Definition at line 847 of file expanding.py.
kurt()
pandas.core.window.expanding.Expanding.kurt (self, bool numeric_only = False)
Reimplemented from pandas.core.window.rolling.RollingAndExpandingMixin.
Definition at line 669 of file expanding.py.
max()
pandas.core.window.expanding.Expanding.max (self, bool numeric_only = False, Literal["cython", "numba"] | None engine = None, dict[str, bool] | None engine_kwargs = None)
Reimplemented from pandas.core.window.rolling.RollingAndExpandingMixin.
Definition at line 315 of file expanding.py.
mean()
pandas.core.window.expanding.Expanding.mean (self, bool numeric_only = False, Literal["cython", "numba"] | None engine = None, dict[str, bool] | None engine_kwargs = None)
Reimplemented from pandas.core.window.rolling.RollingAndExpandingMixin.
Definition at line 393 of file expanding.py.
Referenced by scipy.stats._continuous_distns.norminvgauss_gen._fitstart().
median()
pandas.core.window.expanding.Expanding.median (self, bool numeric_only = False, Literal["cython", "numba"] | None engine = None, dict[str, bool] | None engine_kwargs = None)
Reimplemented from pandas.core.window.rolling.RollingAndExpandingMixin.
Definition at line 432 of file expanding.py.
min()
pandas.core.window.expanding.Expanding.min (self, bool numeric_only = False, Literal["cython", "numba"] | None engine = None, dict[str, bool] | None engine_kwargs = None)
Reimplemented from pandas.core.window.rolling.RollingAndExpandingMixin.
Definition at line 354 of file expanding.py.
quantile()
pandas.core.window.expanding.Expanding.quantile (self, float q, QuantileInterpolation interpolation = "linear", bool numeric_only = False)
Reimplemented from pandas.core.window.rolling.RollingAndExpandingMixin.
Definition at line 718 of file expanding.py.
rank()
pandas.core.window.expanding.Expanding.rank (self, WindowingRankType method = "average", bool ascending = True, bool pct = False, bool numeric_only = False)
Reimplemented from pandas.core.window.rolling.RollingAndExpandingMixin.
Definition at line 791 of file expanding.py.
sem()
pandas.core.window.expanding.Expanding.sem (self, int ddof = 1, bool numeric_only = False)
Reimplemented from pandas.core.window.rolling.RollingAndExpandingMixin.
Definition at line 598 of file expanding.py.
skew()
pandas.core.window.expanding.Expanding.skew (self, bool numeric_only = False)
Reimplemented from pandas.core.window.rolling.RollingAndExpandingMixin.
Definition at line 629 of file expanding.py.
std()
pandas.core.window.expanding.Expanding.std (self, int ddof = 1, bool numeric_only = False, Literal["cython", "numba"] | None engine = None, dict[str, bool] | None engine_kwargs = None)
Reimplemented from pandas.core.window.rolling.RollingAndExpandingMixin.
Definition at line 490 of file expanding.py.
Referenced by pandas.core.window.rolling.Rolling._validate_datetimelike_monotonic().
sum()
pandas.core.window.expanding.Expanding.sum (self, bool numeric_only = False, Literal["cython", "numba"] | None engine = None, dict[str, bool] | None engine_kwargs = None)
Reimplemented from pandas.core.window.rolling.RollingAndExpandingMixin.
Definition at line 276 of file expanding.py.
Referenced by PIL.ImageStat.Stat.mean(), numpy.core.tests.test_simd._SIMD_ALL.test_arithmetic_reduce_sum(), and PIL.ImageStat.Stat.var().
var()
pandas.core.window.expanding.Expanding.var (self, int ddof = 1, bool numeric_only = False, Literal["cython", "numba"] | None engine = None, dict[str, bool] | None engine_kwargs = None)
Reimplemented from pandas.core.window.rolling.RollingAndExpandingMixin.
Definition at line 550 of file expanding.py.
Referenced by pandas.core.window.rolling.Window._apply(), and PIL.ImageStat.Stat.stddev().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/core/window/expanding.py