Code Cloning Analysis: scipy.sparse.linalg._isolve.iterative Namespace Reference
scipy.sparse.linalg._isolve.iterative Namespace Reference
Functions
_stoptest (residual, atol)
_get_atol (tol, atol, bnrm2, get_residual, routine_name)
set_docstring (header, Ainfo, footer='', atol_default='0')
bicg (A, b, x0=None, tol=1e-5, maxiter=None, M=None, callback=None, atol=None)
bicgstab (A, b, x0=None, tol=1e-5, maxiter=None, M=None, callback=None, atol=None)
cg (A, b, x0=None, tol=1e-5, maxiter=None, M=None, callback=None, atol=None)
cgs (A, b, x0=None, tol=1e-5, maxiter=None, M=None, callback=None, atol=None)
gmres (A, b, x0=None, tol=1e-5, restart=None, maxiter=None, M=None, callback=None, restrt=None, atol=None, callback_type=None)
qmr (A, b, x0=None, tol=1e-5, maxiter=None, M1=None, M2=None, callback=None, atol=None)
Variables
list __all__ = ['bicg','bicgstab','cg','cgs','gmres','qmr']
dict _type_conv = {'f':'s', 'd':'d', 'F':'c', 'D':'z'}
str common_doc1
str common_doc2
Detailed Description
Iterative methods for solving linear systems
Function Documentation
_get_atol()
scipy.sparse.linalg._isolve.iterative._get_atol (tol, atol, bnrm2, get_residual, routine_name) protected
Parse arguments for absolute tolerance in termination condition.
Parameters
----------
tol, atol : object
    The arguments passed into the solver routine by user.
bnrm2 : float
    2-norm of the rhs vector.
get_residual : callable
    Callable ``get_residual()`` that returns the initial value of
    the residual.
routine_name : str
    Name of the routine.
Definition at line 78 of file iterative.py.
References _get_atol(), and _stoptest().
Referenced by _get_atol(), gmres(), and qmr().
_stoptest()
scipy.sparse.linalg._isolve.iterative._stoptest (residual, atol) protected
Successful termination condition for the solvers.
Definition at line 67 of file iterative.py.
Referenced by _get_atol(), gmres(), and qmr().
bicg()
scipy.sparse.linalg._isolve.iterative.bicg (A, b, x0 = None, tol = 1e-5, maxiter = None, M = None, callback = None, atol = None)
Definition at line 150 of file iterative.py.
bicgstab()
scipy.sparse.linalg._isolve.iterative.bicgstab (A, b, x0 = None, tol = 1e-5, maxiter = None, M = None, callback = None, atol = None)
Definition at line 241 of file iterative.py.
cg()
scipy.sparse.linalg._isolve.iterative.cg (A, b, x0 = None, tol = 1e-5, maxiter = None, M = None, callback = None, atol = None)
Definition at line 328 of file iterative.py.
cgs()
scipy.sparse.linalg._isolve.iterative.cgs (A, b, x0 = None, tol = 1e-5, maxiter = None, M = None, callback = None, atol = None)
Definition at line 419 of file iterative.py.
gmres()
scipy.sparse.linalg._isolve.iterative.gmres (A, b, x0 = None, tol = 1e-5, restart = None, maxiter = None, M = None, callback = None, restrt = None, atol = None, callback_type = None)
Use Generalized Minimal RESidual iteration to solve ``Ax = b``.
Parameters
----------
A : {sparse matrix, ndarray, LinearOperator}
    The real or complex N-by-N matrix of the linear system.
    Alternatively, ``A`` can be a linear operator which can
    produce ``Ax`` using, e.g.,
    ``scipy.sparse.linalg.LinearOperator``.
b : ndarray
    Right hand side of the linear system. Has shape (N,) or (N,1).
Returns
-------
x : ndarray
    The converged solution.
info : int
    Provides convergence information:
      * 0  : successful exit
      * >0 : convergence to tolerance not achieved, number of iterations
      * <0 : illegal input or breakdown
Other parameters
----------------
x0 : ndarray
    Starting guess for the solution (a vector of zeros by default).
tol, atol : float, optional
    Tolerances for convergence, ``norm(residual) <= max(tol*norm(b), atol)``.
    The default for ``atol`` is ``'legacy'``, which emulates
    a different legacy behavior.
    .. warning::
       The default value for `atol` will be changed in a future release.
       For future compatibility, specify `atol` explicitly.
restart : int, optional
    Number of iterations between restarts. Larger values increase
    iteration cost, but may be necessary for convergence.
    Default is 20.
maxiter : int, optional
    Maximum number of iterations (restart cycles).  Iteration will stop
    after maxiter steps even if the specified tolerance has not been
    achieved.
M : {sparse matrix, ndarray, LinearOperator}
    Inverse of the preconditioner of A.  M should approximate the
    inverse of A and be easy to solve for (see Notes).  Effective
    preconditioning dramatically improves the rate of convergence,
    which implies that fewer iterations are needed to reach a given
    error tolerance.  By default, no preconditioner is used.
    In this implementation, left preconditioning is used,
    and the preconditioned residual is minimized.
callback : function
    User-supplied function to call after each iteration.  It is called
    as `callback(args)`, where `args` are selected by `callback_type`.
callback_type : {'x', 'pr_norm', 'legacy'}, optional
    Callback function argument requested:
      - ``x``: current iterate (ndarray), called on every restart
      - ``pr_norm``: relative (preconditioned) residual norm (float),
        called on every inner iteration
      - ``legacy`` (default): same as ``pr_norm``, but also changes the
        meaning of 'maxiter' to count inner iterations instead of restart
        cycles.
restrt : int, optional, deprecated
    .. deprecated:: 0.11.0
       `gmres` keyword argument `restrt` is deprecated infavour of
       `restart` and will be removed in SciPy 1.12.0.
See Also
--------
LinearOperator
Notes
-----
A preconditioner, P, is chosen such that P is close to A but easy to solve
for. The preconditioner parameter required by this routine is
``M = P^-1``. The inverse should preferably not be calculated
explicitly.  Rather, use the following template to produce M::
  # Construct a linear operator that computes P^-1 @ x.
  import scipy.sparse.linalg as spla
  M_x = lambda x: spla.spsolve(P, x)
  M = spla.LinearOperator((n, n), M_x)
Examples
--------
>>> import numpy as np
>>> from scipy.sparse import csc_matrix
>>> from scipy.sparse.linalg import gmres
>>> A = csc_matrix([[3, 2, 0], [1, -1, 0], [0, 5, 1]], dtype=float)
>>> b = np.array([2, 4, -1], dtype=float)
>>> x, exitCode = gmres(A, b)
>>> print(exitCode)            # 0 indicates successful convergence
0
>>> np.allclose(A.dot(x), b)
True
Definition at line 492 of file iterative.py.
References _get_atol(), and _stoptest().
Referenced by scipy.sparse.linalg._eigen.arpack.arpack.gmres_loose().
qmr()
scipy.sparse.linalg._isolve.iterative.qmr (A, b, x0 = None, tol = 1e-5, maxiter = None, M1 = None, M2 = None, callback = None, atol = None)
Use Quasi-Minimal Residual iteration to solve ``Ax = b``.
Parameters
----------
A : {sparse matrix, ndarray, LinearOperator}
    The real-valued N-by-N matrix of the linear system.
    Alternatively, ``A`` can be a linear operator which can
    produce ``Ax`` and ``A^T x`` using, e.g.,
    ``scipy.sparse.linalg.LinearOperator``.
b : ndarray
    Right hand side of the linear system. Has shape (N,) or (N,1).
Returns
-------
x : ndarray
    The converged solution.
info : integer
    Provides convergence information:
        0  : successful exit
        >0 : convergence to tolerance not achieved, number of iterations
        <0 : illegal input or breakdown
Other Parameters
----------------
x0 : ndarray
    Starting guess for the solution.
tol, atol : float, optional
    Tolerances for convergence, ``norm(residual) <= max(tol*norm(b), atol)``.
    The default for ``atol`` is ``'legacy'``, which emulates
    a different legacy behavior.
    .. warning::
       The default value for `atol` will be changed in a future release.
       For future compatibility, specify `atol` explicitly.
maxiter : integer
    Maximum number of iterations.  Iteration will stop after maxiter
    steps even if the specified tolerance has not been achieved.
M1 : {sparse matrix, ndarray, LinearOperator}
    Left preconditioner for A.
M2 : {sparse matrix, ndarray, LinearOperator}
    Right preconditioner for A. Used together with the left
    preconditioner M1.  The matrix M1@A@M2 should have better
    conditioned than A alone.
callback : function
    User-supplied function to call after each iteration.  It is called
    as callback(xk), where xk is the current solution vector.
See Also
--------
LinearOperator
Examples
--------
>>> import numpy as np
>>> from scipy.sparse import csc_matrix
>>> from scipy.sparse.linalg import qmr
>>> A = csc_matrix([[3, 2, 0], [1, -1, 0], [0, 5, 1]], dtype=float)
>>> b = np.array([2, 4, -1], dtype=float)
>>> x, exitCode = qmr(A, b)
>>> print(exitCode)            # 0 indicates successful convergence
0
>>> np.allclose(A.dot(x), b)
True
Definition at line 736 of file iterative.py.
References _get_atol(), and _stoptest().
set_docstring()
scipy.sparse.linalg._isolve.iterative.set_docstring (header, Ainfo, footer = '', atol_default = '0')
Definition at line 119 of file iterative.py.
Variable Documentation
__all__
list scipy.sparse.linalg._isolve.iterative.__all__ = ['bicg','bicgstab','cg','cgs','gmres','qmr'] private
Definition at line 3 of file iterative.py.
_type_conv
dict scipy.sparse.linalg._isolve.iterative._type_conv = {'f':'s', 'd':'d', 'F':'c', 'D':'z'} protected
Definition at line 16 of file iterative.py.
common_doc1
str scipy.sparse.linalg._isolve.iterative.common_doc1
Initial value:
=  \
"""
Parameters
----------
A : {sparse matrix, ndarray, LinearOperator}"""
Definition at line 20 of file iterative.py.
common_doc2
str scipy.sparse.linalg._isolve.iterative.common_doc2
Definition at line 26 of file iterative.py.