Code Cloning Analysis: sklearn.model_selection._split.LeavePGroupsOut Class Reference
sklearn.model_selection._split.LeavePGroupsOut Class Reference
Public Member Functions
__init__ (self, n_groups)
get_n_splits (self, X=None, y=None, groups=None)
split (self, X, y=None, groups=None)
Public Member Functions inherited from sklearn.model_selection._split.BaseCrossValidator
__repr__ (self)
Public Attributes
n_groups = n_groups
Protected Member Functions
_iter_test_masks (self, X, y, groups)
Protected Member Functions inherited from sklearn.model_selection._split.BaseCrossValidator
_iter_test_indices (self, X=None, y=None, groups=None)
Detailed Description
Leave P Group(s) Out cross-validator.
Provides train/test indices to split data according to a third-party
provided group. This group information can be used to encode arbitrary
domain specific stratifications of the samples as integers.
For instance the groups could be the year of collection of the samples
and thus allow for cross-validation against time-based splits.
The difference between LeavePGroupsOut and LeaveOneGroupOut is that
the former builds the test sets with all the samples assigned to
``p`` different values of the groups while the latter uses samples
all assigned the same groups.
Read more in the :ref:`User Guide <leave_p_groups_out>`.
Parameters
----------
n_groups : int
    Number of groups (``p``) to leave out in the test split.
Examples
--------
>>> import numpy as np
>>> from sklearn.model_selection import LeavePGroupsOut
>>> X = np.array([[1, 2], [3, 4], [5, 6]])
>>> y = np.array([1, 2, 1])
>>> groups = np.array([1, 2, 3])
>>> lpgo = LeavePGroupsOut(n_groups=2)
>>> lpgo.get_n_splits(X, y, groups)
3
>>> lpgo.get_n_splits(groups=groups)  # 'groups' is always required
3
>>> print(lpgo)
LeavePGroupsOut(n_groups=2)
>>> for i, (train_index, test_index) in enumerate(lpgo.split(X, y, groups)):
...     print(f"Fold {i}:")
...     print(f"  Train: index={train_index}, group={groups[train_index]}")
...     print(f"  Test:  index={test_index}, group={groups[test_index]}")
Fold 0:
  Train: index=[2], group=[3]
  Test:  index=[0 1], group=[1 2]
Fold 1:
  Train: index=[1], group=[2]
  Test:  index=[0 2], group=[1 3]
Fold 2:
  Train: index=[0], group=[1]
  Test:  index=[1 2], group=[2 3]
See Also
--------
GroupKFold : K-fold iterator variant with non-overlapping groups.
Definition at line 1435 of file _split.py.
Constructor & Destructor Documentation
__init__()
sklearn.model_selection._split.LeavePGroupsOut.__init__ (self, n_groups)
Definition at line 1490 of file _split.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params().
Member Function Documentation
_iter_test_masks()
sklearn.model_selection._split.LeavePGroupsOut._iter_test_masks (self, X, y, groups) protected
Generates boolean masks corresponding to test sets.
By default, delegates to _iter_test_indices(X, y, groups)
Reimplemented from sklearn.model_selection._split.BaseCrossValidator.
Definition at line 1493 of file _split.py.
References n_groups.
get_n_splits()
sklearn.model_selection._split.LeavePGroupsOut.get_n_splits (self, X = None, y = None, groups = None)
Returns the number of splitting iterations in the cross-validator.
Parameters
----------
X : object
    Always ignored, exists for compatibility.
y : object
    Always ignored, exists for compatibility.
groups : array-like of shape (n_samples,)
    Group labels for the samples used while splitting the dataset into
    train/test set. This 'groups' parameter must always be specified to
    calculate the number of splits, though the other parameters can be
    omitted.
Returns
-------
n_splits : int
    Returns the number of splitting iterations in the cross-validator.
Reimplemented from sklearn.model_selection._split.BaseCrossValidator.
Definition at line 1514 of file _split.py.
References n_groups.
split()
sklearn.model_selection._split.LeavePGroupsOut.split (self, X, y = None, groups = None)
Generate indices to split data into training and test set.
Parameters
----------
X : array-like of shape (n_samples, n_features)
    Training data, where `n_samples` is the number of samples
    and `n_features` is the number of features.
y : array-like of shape (n_samples,), default=None
    The target variable for supervised learning problems.
groups : array-like of shape (n_samples,)
    Group labels for the samples used while splitting the dataset into
    train/test set.
Yields
------
train : ndarray
    The training set indices for that split.
test : ndarray
    The testing set indices for that split.
Reimplemented from sklearn.model_selection._split.BaseCrossValidator.
Definition at line 1541 of file _split.py.
References split().
Referenced by split().
Member Data Documentation
n_groups
sklearn.model_selection._split.LeavePGroupsOut.n_groups = n_groups
Definition at line 1491 of file _split.py.
Referenced by _iter_test_masks(), and get_n_splits().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/sklearn/model_selection/_split.py