Code Cloning Analysis: matplotlib.sphinxext.plot_directive Namespace Reference
matplotlib.sphinxext.plot_directive Namespace Reference
Classes
class ImageFile
class PlotDirective
class PlotError
Functions
_option_boolean (arg)
_option_context (arg)
_option_format (arg)
mark_plot_labels (app, document)
_copy_css_file (app, exc)
setup (app)
contains_doctest (text)
_split_code_at_show (text, function_name)
out_of_date (original, derived, includes=None)
_run_code (code, code_path, ns=None, function_name=None)
clear_state (plot_rcparams, close=True)
get_plot_formats (config)
_parse_srcset (entries)
render_figures (code, code_path, output_dir, output_base, context, function_name, config, context_reset=False, close_figs=False, code_includes=None)
run (arguments, content, options, state_machine, state, lineno)
Variables
int __version__ = 2
str _SOURCECODE
str TEMPLATE_SRCSET
str TEMPLATE
str exception_template
plot_context = dict()
Detailed Description
A directive for including a Matplotlib plot in a Sphinx document
================================================================
This is a Sphinx extension providing a reStructuredText directive
``.. plot::`` for including a plot in a Sphinx document.
In HTML output, ``.. plot::`` will include a .png file with a link
to a high-res .png and .pdf.  In LaTeX output, it will include a .pdf.
The plot content may be defined in one of three ways:
1. **A path to a source file** as the argument to the directive::
     .. plot:: path/to/plot.py
   When a path to a source file is given, the content of the
   directive may optionally contain a caption for the plot::
     .. plot:: path/to/plot.py
        The plot caption.
   Additionally, one may specify the name of a function to call (with
   no arguments) immediately after importing the module::
     .. plot:: path/to/plot.py plot_function1
2. Included as **inline content** to the directive::
     .. plot::
        import matplotlib.pyplot as plt
        plt.plot([1, 2, 3], [4, 5, 6])
        plt.title("A plotting exammple")
3. Using **doctest** syntax::
     .. plot::
        A plotting example:
        >>> import matplotlib.pyplot as plt
        >>> plt.plot([1, 2, 3], [4, 5, 6])
Options
-------
The ``.. plot::`` directive supports the following options:
``:format:`` : {'python', 'doctest'}
    The format of the input.  If unset, the format is auto-detected.
``:include-source:`` : bool
    Whether to display the source code. The default can be changed using
    the ``plot_include_source`` variable in :file:`conf.py` (which itself
    defaults to False).
``:show-source-link:`` : bool
    Whether to show a link to the source in HTML. The default can be
    changed using the ``plot_html_show_source_link`` variable in
    :file:`conf.py` (which itself defaults to True).
``:context:`` : bool or str
    If provided, the code will be run in the context of all previous plot
    directives for which the ``:context:`` option was specified.  This only
    applies to inline code plot directives, not those run from files. If
    the ``:context: reset`` option is specified, the context is reset
    for this and future plots, and previous figures are closed prior to
    running the code. ``:context: close-figs`` keeps the context but closes
    previous figures before running the code.
``:nofigs:`` : bool
    If specified, the code block will be run, but no figures will be
    inserted.  This is usually useful with the ``:context:`` option.
``:caption:`` : str
    If specified, the option's argument will be used as a caption for the
    figure. This overwrites the caption given in the content, when the plot
    is generated from a file.
Additionally, this directive supports all the options of the `image directive
<https://docutils.sourceforge.io/docs/ref/rst/directives.html#image>`_,
except for ``:target:`` (since plot will add its own target).  These include
``:alt:``, ``:height:``, ``:width:``, ``:scale:``, ``:align:`` and ``:class:``.
Configuration options
---------------------
The plot directive has the following configuration options:
plot_include_source
    Default value for the include-source option (default: False).
plot_html_show_source_link
    Whether to show a link to the source in HTML (default: True).
plot_pre_code
    Code that should be executed before each plot. If None (the default),
    it will default to a string containing::
        import numpy as np
        from matplotlib import pyplot as plt
plot_basedir
    Base directory, to which ``plot::`` file names are relative to.
    If None or empty (the default), file names are relative to the
    directory where the file containing the directive is.
plot_formats
    File formats to generate (default: ['png', 'hires.png', 'pdf']).
    List of tuples or strings::
        [(suffix, dpi), suffix, ...]
    that determine the file format and the DPI. For entries whose
    DPI was omitted, sensible defaults are chosen. When passing from
    the command line through sphinx_build the list should be passed as
    suffix:dpi,suffix:dpi, ...
plot_html_show_formats
    Whether to show links to the files in HTML (default: True).
plot_rcparams
    A dictionary containing any non-standard rcParams that should
    be applied before each plot (default: {}).
plot_apply_rcparams
    By default, rcParams are applied when ``:context:`` option is not used
    in a plot directive.  If set, this configuration option overrides this
    behavior and applies rcParams before each plot.
plot_working_directory
    By default, the working directory will be changed to the directory of
    the example, so the code can get at its data files, if any.  Also its
    path will be added to `sys.path` so it can import any helper modules
    sitting beside it.  This configuration option can be used to specify
    a central directory (also added to `sys.path`) where data files and
    helper modules for all code are located.
plot_template
    Provide a customized template for preparing restructured text.
plot_srcset
    Allow the srcset image option for responsive image resolutions. List of
    strings with the multiplicative factors followed by an "x".
    e.g. ["2.0x", "1.5x"].  "2.0x" will create a png with the default "png"
    resolution from plot_formats, multiplied by 2. If plot_srcset is
    specified, the plot directive uses the
    :doc:`/api/sphinxext_figmpl_directive_api` (instead of the usual figure
    directive) in the intermediary rst file that is generated.
    The plot_srcset option is incompatible with *singlehtml* builds, and an
    error will be raised.
Notes on how it works
---------------------
The plot directive runs the code it is given, either in the source file or the
code under the directive. The figure created (if any) is saved in the sphinx
build directory under a subdirectory named ``plot_directive``.  It then creates
an intermediate rst file that calls a ``.. figure:`` directive (or
``.. figmpl::`` directive if ``plot_srcset`` is being used) and has links to
the ``*.png`` files in the ``plot_directive`` directory.  These translations can
be customized by changing the *plot_template*.  See the source of
:doc:`/api/sphinxext_plot_directive_api` for the templates defined in *TEMPLATE*
and *TEMPLATE_SRCSET*.
Function Documentation
_copy_css_file()
matplotlib.sphinxext.plot_directive._copy_css_file (app, exc) protected
Definition at line 285 of file plot_directive.py.
_option_boolean()
matplotlib.sphinxext.plot_directive._option_boolean (arg) protected
Definition at line 202 of file plot_directive.py.
_option_context()
matplotlib.sphinxext.plot_directive._option_context (arg) protected
Definition at line 214 of file plot_directive.py.
_option_format()
matplotlib.sphinxext.plot_directive._option_format (arg) protected
Definition at line 220 of file plot_directive.py.
_parse_srcset()
matplotlib.sphinxext.plot_directive._parse_srcset (entries) protected
Parse srcset for multiples...
Definition at line 588 of file plot_directive.py.
Referenced by render_figures().
_run_code()
matplotlib.sphinxext.plot_directive._run_code (code, code_path, ns = None, function_name = None) protected
Import a Python module from a path, and run the function given by
name, if function_name is not None.
Definition at line 510 of file plot_directive.py.
Referenced by render_figures().
_split_code_at_show()
matplotlib.sphinxext.plot_directive._split_code_at_show (text, function_name) protected
Split code at plt.show().
Definition at line 335 of file plot_directive.py.
Referenced by render_figures().
clear_state()
matplotlib.sphinxext.plot_directive.clear_state (plot_rcparams, close = True)
Definition at line 563 of file plot_directive.py.
contains_doctest()
matplotlib.sphinxext.plot_directive.contains_doctest (text)
Definition at line 323 of file plot_directive.py.
get_plot_formats()
matplotlib.sphinxext.plot_directive.get_plot_formats (config)
Definition at line 570 of file plot_directive.py.
mark_plot_labels()
matplotlib.sphinxext.plot_directive.mark_plot_labels (app, document)
To make plots referenceable, we need to move the reference from the
"htmlonly" (or "latexonly") node to the actual figure node itself.
Definition at line 224 of file plot_directive.py.
out_of_date()
matplotlib.sphinxext.plot_directive.out_of_date (original, derived, includes = None)
Return whether *derived* is out-of-date relative to *original* or any of
the RST files included in it using the RST include directive (*includes*).
*derived* and *original* are full paths, and *includes* is optionally a
list of full paths which may have been included in the *original*.
Definition at line 484 of file plot_directive.py.
Referenced by render_figures().
render_figures()
matplotlib.sphinxext.plot_directive.render_figures (code, code_path, output_dir, output_base, context, function_name, config, context_reset = False, close_figs = False, code_includes = None)
Run a pyplot script and save the images in *output_dir*.
Save the images under *output_dir* with file names derived from
*output_base*
Definition at line 603 of file plot_directive.py.
References _parse_srcset(), _run_code(), _split_code_at_show(), out_of_date(), and render_figures().
Referenced by render_figures().
run()
matplotlib.sphinxext.plot_directive.run (arguments, content, options, state_machine, state, lineno)
Definition at line 723 of file plot_directive.py.
setup()
matplotlib.sphinxext.plot_directive.setup (app)
Definition at line 294 of file plot_directive.py.
Variable Documentation
__version__
int matplotlib.sphinxext.plot_directive.__version__ = 2 private
Definition at line 194 of file plot_directive.py.
_SOURCECODE
str matplotlib.sphinxext.plot_directive._SOURCECODE protected
Initial value:
=  """
{{ source_code }}
.. only:: html
   {% if src_name or (html_show_formats and not multi_image) %}
   (
   {%- if src_name -%}
   :download:`Source code <{{ build_dir }}/{{ src_name }}>`
   {%- endif -%}
   {%- if html_show_formats and not multi_image -%}
     {%- for img in images -%}
       {%- for fmt in img.formats -%}
         {%- if src_name or not loop.first -%}, {% endif -%}
         :download:`{{ fmt }} <{{ build_dir }}/{{ img.basename }}.{{ fmt }}>`
       {%- endfor -%}
     {%- endfor -%}
   {%- endif -%}
   )
   {% endif %}
"""
Definition at line 361 of file plot_directive.py.
exception_template
str matplotlib.sphinxext.plot_directive.exception_template
Initial value:
=  """
.. only:: html
   [`source code <%(linkdir)s/%(basename)s.py>`__]
Exception occurred rendering plot.
"""
Definition at line 457 of file plot_directive.py.
plot_context
matplotlib.sphinxext.plot_directive.plot_context = dict()
Definition at line 468 of file plot_directive.py.
TEMPLATE
str matplotlib.sphinxext.plot_directive.TEMPLATE
Definition at line 424 of file plot_directive.py.
TEMPLATE_SRCSET
str matplotlib.sphinxext.plot_directive.TEMPLATE_SRCSET
Definition at line 383 of file plot_directive.py.