Code Cloning Analysis: pip._vendor.chardet.charsetgroupprober.CharSetGroupProber Class Reference
pip._vendor.chardet.charsetgroupprober.CharSetGroupProber Class Reference
Public Member Functions
None __init__ (self, LanguageFilter lang_filter=LanguageFilter.NONE)
None reset (self)
Optional[str] charset_name (self)
Optional[str] language (self)
ProbingState feed (self, Union[bytes, bytearray] byte_str)
float get_confidence (self)
Public Member Functions inherited from pip._vendor.chardet.charsetprober.CharSetProber
None __init__ (self, LanguageFilter lang_filter=LanguageFilter.NONE)
ProbingState state (self)
Public Attributes
list probers = []
Public Attributes inherited from pip._vendor.chardet.charsetprober.CharSetProber
bool active = True
lang_filter = lang_filter
logger = logging.getLogger(__name__)
Protected Attributes
int _active_num = 0
Optional[CharSetProber] _best_guess_prober = None
Protected Attributes inherited from pip._vendor.chardet.charsetprober.CharSetProber
_state = ProbingState.DETECTING
Additional Inherited Members
Static Public Member Functions inherited from pip._vendor.chardet.charsetprober.CharSetProber
bytes filter_high_byte_only (Union[bytes, bytearray] buf)
bytearray filter_international_words (Union[bytes, bytearray] buf)
bytes remove_xml_tags (Union[bytes, bytearray] buf)
Static Public Attributes inherited from pip._vendor.chardet.charsetprober.CharSetProber
float SHORTCUT_THRESHOLD = 0.95
Detailed Description
Definition at line 34 of file charsetgroupprober.py.
Constructor & Destructor Documentation
__init__()
None pip._vendor.chardet.charsetgroupprober.CharSetGroupProber.__init__ (self, LanguageFilter lang_filter = LanguageFilter.NONE)
Definition at line 35 of file charsetgroupprober.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
charset_name()
Optional[str] pip._vendor.chardet.charsetgroupprober.CharSetGroupProber.charset_name (self)
Reimplemented from pip._vendor.chardet.charsetprober.CharSetProber.
Definition at line 51 of file charsetgroupprober.py.
feed()
ProbingState pip._vendor.chardet.charsetgroupprober.CharSetGroupProber.feed (self, Union[bytes, bytearray] byte_str)
Reimplemented from pip._vendor.chardet.charsetprober.CharSetProber.
Definition at line 66 of file charsetgroupprober.py.
get_confidence()
float pip._vendor.chardet.charsetgroupprober.CharSetGroupProber.get_confidence (self)
Reimplemented from pip._vendor.chardet.charsetprober.CharSetProber.
Definition at line 85 of file charsetgroupprober.py.
Referenced by pip._vendor.chardet.utf1632prober.UTF1632Prober.validate_utf16_characters().
language()
Optional[str] pip._vendor.chardet.charsetgroupprober.CharSetGroupProber.language (self)
Reimplemented from pip._vendor.chardet.charsetprober.CharSetProber.
Definition at line 59 of file charsetgroupprober.py.
reset()
None pip._vendor.chardet.charsetgroupprober.CharSetGroupProber.reset (self)
Reimplemented from pip._vendor.chardet.charsetprober.CharSetProber.
Definition at line 41 of file charsetgroupprober.py.
Referenced by scipy._lib._docscrape.Reader.__init__().
Member Data Documentation
_active_num
int pip._vendor.chardet.charsetgroupprober.CharSetGroupProber._active_num = 0 protected
Definition at line 37 of file charsetgroupprober.py.
_best_guess_prober
Optional[CharSetProber] pip._vendor.chardet.charsetgroupprober.CharSetGroupProber._best_guess_prober = None protected
Definition at line 39 of file charsetgroupprober.py.
probers
list pip._vendor.chardet.charsetgroupprober.CharSetGroupProber.probers = []
Definition at line 38 of file charsetgroupprober.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pip/_vendor/chardet/charsetgroupprober.py