Code Cloning Analysis: fontTools.varLib.errors.UnsupportedFormat Class Reference
fontTools.varLib.errors.UnsupportedFormat Class Reference
Public Member Functions
__init__ (self, merger=None, **kwargs)
reason (self)
Public Member Functions inherited from fontTools.varLib.errors.VarLibMergeError
__init__ (self, merger=None, **kwargs)
offender (self)
details (self)
__str__ (self)
Additional Inherited Members
Public Attributes inherited from fontTools.varLib.errors.VarLibMergeError
merger = merger
list stack = kwargs["stack"]
cause = kwargs
Protected Member Functions inherited from fontTools.varLib.errors.VarLibMergeError
_master_name (self, ix)
Detailed Description
an OpenType subtable (%s) had a format I didn't expect
Definition at line 157 of file errors.py.
Constructor & Destructor Documentation
__init__()
fontTools.varLib.errors.UnsupportedFormat.__init__ (self, merger = None, ** kwargs)
Definition at line 160 of file errors.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
reason()
fontTools.varLib.errors.UnsupportedFormat.reason (self)
Reimplemented from fontTools.varLib.errors.VarLibMergeError.
Definition at line 166 of file errors.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/varLib/errors.py