Code Cloning Analysis: scipy.signal.tests.test_signaltools Namespace Reference
scipy.signal.tests.test_signaltools Namespace Reference
Classes
class _TestConvolve
class _TestConvolve2d
class _TestLinearFilter
class TestAllFreqConvolves
class TestConvolve
class TestConvolve2d
class TestCorrelate
class TestCorrelate2d
class TestCorrelateComplex
class TestCorrelateReal
class TestCSpline1DEval
class TestDecimate
class TestDeconvolve
class TestDetrend
class TestFFTConvolve
class TestFiltFilt
class TestHilbert
class TestHilbert2
class TestLFilterZI
class TestLinearFilterComplex128
class TestLinearFilterComplex64
class TestLinearFilterComplexExtended
class TestLinearFilterDecimal
class TestLinearFilterFloat32
class TestLinearFilterFloat64
class TestLinearFilterFloatExtended
class TestLinearFilterObject
class TestMedFilt
class TestOAConvolve
class TestOrderFilt
class TestPartialFractionExpansion
class TestResample
class TestSOSFilt
class TestSOSFiltFilt
class TestUniqueRoots
class TestVectorstrength
class TestWiener
Functions
fftconvolve_err (*args, **kwargs)
gen_oa_shapes (sizes)
gen_oa_shapes_2d (sizes)
gen_oa_shapes_eq (sizes)
test_lfilter_bad_object ()
test_lfilter_notimplemented_input ()
test_correlation_lags (mode, behind, input_size)
filtfilt_gust_opt (b, a, x)
check_filtfilt_gust (b, a, shape, axis, irlen=None)
test_choose_conv_method ()
test_filtfilt_gust ()
cast_tf2sos (b, a)
assert_allclose_cast (actual, desired, rtol=1e-7, atol=0)
test_nonnumeric_dtypes (func)
Variables
list padtype_options = ["mean", "median", "minimum", "maximum", "line"]
Function Documentation
assert_allclose_cast()
scipy.signal.tests.test_signaltools.assert_allclose_cast (actual, desired, rtol = 1e-7, atol = 0)
Wrap assert_allclose while casting object arrays.
Definition at line 3344 of file test_signaltools.py.
References scipy.signal._signaltools.lfilter(), scipy.signal._signaltools.sosfilt(), and scipy.signal._filter_design.tf2sos().
cast_tf2sos()
scipy.signal.tests.test_signaltools.cast_tf2sos (b, a)
Convert TF2SOS, casting to complex128 and back to the original dtype.
Definition at line 3330 of file test_signaltools.py.
References scipy.signal._filter_design.tf2sos().
check_filtfilt_gust()
scipy.signal.tests.test_signaltools.check_filtfilt_gust (b, a, shape, axis, irlen = None)
Definition at line 2426 of file test_signaltools.py.
fftconvolve_err()
scipy.signal.tests.test_signaltools.fftconvolve_err (* args, ** kwargs)
Definition at line 814 of file test_signaltools.py.
filtfilt_gust_opt()
scipy.signal.tests.test_signaltools.filtfilt_gust_opt (b, a, x)
An alternative implementation of filtfilt with Gustafsson edges.
This function computes the same result as
`scipy.signal._signaltools._filtfilt_gust`, but only 1-d arrays
are accepted.  The problem is solved using `fmin` from `scipy.optimize`.
`_filtfilt_gust` is significanly faster than this implementation.
Definition at line 2382 of file test_signaltools.py.
References scipy.signal._signaltools._filtfilt_gust(), scipy.signal._signaltools.choose_conv_method(), scipy.signal._signaltools.filtfilt(), filtfilt_gust_opt(), scipy.signal._signaltools.lfilter(), scipy.signal._signaltools.lfilter_zi(), and scipy.signal._filter_design.zpk2tf().
Referenced by filtfilt_gust_opt().
gen_oa_shapes()
scipy.signal.tests.test_signaltools.gen_oa_shapes (sizes)
Definition at line 818 of file test_signaltools.py.
gen_oa_shapes_2d()
scipy.signal.tests.test_signaltools.gen_oa_shapes_2d (sizes)
Definition at line 823 of file test_signaltools.py.
gen_oa_shapes_eq()
scipy.signal.tests.test_signaltools.gen_oa_shapes_eq (sizes)
Definition at line 836 of file test_signaltools.py.
test_choose_conv_method()
scipy.signal.tests.test_signaltools.test_choose_conv_method ()
Definition at line 2458 of file test_signaltools.py.
test_correlation_lags()
scipy.signal.tests.test_signaltools.test_correlation_lags (mode, behind, input_size)
Definition at line 2086 of file test_signaltools.py.
test_filtfilt_gust()
scipy.signal.tests.test_signaltools.test_filtfilt_gust ()
Definition at line 2489 of file test_signaltools.py.
test_lfilter_bad_object()
scipy.signal.tests.test_signaltools.test_lfilter_bad_object ()
Definition at line 1901 of file test_signaltools.py.
test_lfilter_notimplemented_input()
scipy.signal.tests.test_signaltools.test_lfilter_notimplemented_input ()
Definition at line 1911 of file test_signaltools.py.
test_nonnumeric_dtypes()
scipy.signal.tests.test_signaltools.test_nonnumeric_dtypes (func)
Definition at line 3353 of file test_signaltools.py.
Variable Documentation
padtype_options
list scipy.signal.tests.test_signaltools.padtype_options = ["mean", "median", "minimum", "maximum", "line"]
Definition at line 1226 of file test_signaltools.py.