Code Cloning Analysis: pandas._typing.ReadCsvBuffer Class Reference
pandas._typing.ReadCsvBuffer Class Reference
Public Member Functions
Iterator[AnyStr_co] __iter__ (self)
int fileno (self)
AnyStr_co readline (self)
bool closed (self)
Public Member Functions inherited from pandas._typing.ReadBuffer
AnyStr_co read (self, int __n=...)
Public Member Functions inherited from pandas._typing.BaseBuffer
str mode (self)
int seek (self, int __offset, int __whence=...)
bool seekable (self)
int tell (self)
Detailed Description
Definition at line 308 of file _typing.py.
Member Function Documentation
__iter__()
Iterator[AnyStr_co] pandas._typing.ReadCsvBuffer.__iter__ (self)
Definition at line 309 of file _typing.py.
closed()
bool pandas._typing.ReadCsvBuffer.closed (self)
Definition at line 322 of file _typing.py.
Referenced by pandas.core.dtypes.dtypes.IntervalDtype.__from_arrow__(), pandas.core.indexes.interval.IntervalIndex._getitem_slice(), pandas.core.indexes.interval.IntervalIndex._maybe_convert_i8(), pandas.core.indexes.interval.IntervalIndex.get_loc(), and pandas.core.dtypes.dtypes.IntervalDtype.type().
fileno()
int pandas._typing.ReadCsvBuffer.fileno (self)
Definition at line 313 of file _typing.py.
readline()
AnyStr_co pandas._typing.ReadCsvBuffer.readline (self)
Definition at line 317 of file _typing.py.
Referenced by PIL.ContainerIO.ContainerIO.readlines().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/_typing.py