Code Cloning Analysis: pandas.plotting._matplotlib.style Namespace Reference
pandas.plotting._matplotlib.style Namespace Reference
Functions
get_standard_colors (int num_colors, Colormap|None colormap=None, str color_type="default", dict[str, Color]|Color|Collection[Color]|None color=None)
list[Color] _derive_colors (*, Color|Collection[Color]|None color, str|Colormap|None colormap, str color_type, int num_colors)
Iterator[Color] _cycle_colors (list[Color] colors, int num_colors)
list[Color] _get_colors_from_colormap (str|Colormap colormap, int num_colors)
Colormap _get_cmap_instance (str|Colormap colormap)
list[Color] _get_colors_from_color (Color|Collection[Color] color)
bool _is_single_color (Color|Collection[Color] color)
Iterator[Color] _gen_list_of_colors_from_iterable (Collection[Color] color)
bool _is_floats_color (Color|Collection[Color] color)
list[Color] _get_colors_from_color_type (str color_type, int num_colors)
list[Color] _get_default_colors (int num_colors)
list[Color] _get_random_colors (int num_colors)
list[float] _random_color (int column)
bool _is_single_string_color (Color color)
Function Documentation
_cycle_colors()
Iterator[Color] pandas.plotting._matplotlib.style._cycle_colors (list[Color] colors, int num_colors) protected
Cycle colors until achieving max of `num_colors` or length of `colors`.
Extra colors will be ignored by matplotlib if there are more colors
than needed and nothing needs to be done here.
Definition at line 132 of file style.py.
Referenced by get_standard_colors().
_derive_colors()
list[Color] pandas.plotting._matplotlib.style._derive_colors (* , Color | Collection[Color] | None color, str | Colormap | None colormap, str color_type, int num_colors) protected
Derive colors from either `colormap`, `color_type` or `color` inputs.
Get a list of colors either from `colormap`, or from `color`,
or from `color_type` (if both `colormap` and `color` are None).
Parameters
----------
color : str or sequence, optional
    Color(s) to be used for deriving sequence of colors.
    Can be either be a single color (single color string, or sequence of floats
    representing a single color), or a sequence of colors.
colormap : :py:class:`matplotlib.colors.Colormap`, optional
    Matplotlib colormap.
    When provided, the resulting colors will be derived from the colormap.
color_type : {"default", "random"}, optional
    Type of colors to derive. Used if provided `color` and `colormap` are None.
    Ignored if either `color` or `colormap`` are not None.
num_colors : int
    Number of colors to be extracted.
Returns
-------
list
    List of colors extracted.
Warns
-----
UserWarning
    If both `colormap` and `color` are provided.
    Parameter `color` will override.
Definition at line 80 of file style.py.
References _get_colors_from_color(), _get_colors_from_color_type(), and _get_colors_from_colormap().
Referenced by get_standard_colors().
_gen_list_of_colors_from_iterable()
Iterator[Color] pandas.plotting._matplotlib.style._gen_list_of_colors_from_iterable (Collection[Color] color) protected
Yield colors from string of several letters or from collection of colors.
Definition at line 198 of file style.py.
References _is_single_color().
Referenced by _get_colors_from_color().
_get_cmap_instance()
Colormap pandas.plotting._matplotlib.style._get_cmap_instance (str | Colormap colormap) protected
Get instance of matplotlib colormap.
Definition at line 151 of file style.py.
Referenced by _get_colors_from_colormap().
_get_colors_from_color()
list[Color] pandas.plotting._matplotlib.style._get_colors_from_color (Color | Collection[Color] color) protected
Get colors from user input color.
Definition at line 161 of file style.py.
References _gen_list_of_colors_from_iterable(), and _is_single_color().
Referenced by _derive_colors().
_get_colors_from_color_type()
list[Color] pandas.plotting._matplotlib.style._get_colors_from_color_type (str color_type, int num_colors) protected
Get colors from user input color type.
Definition at line 218 of file style.py.
References _get_default_colors(), and _get_random_colors().
Referenced by _derive_colors().
_get_colors_from_colormap()
list[Color] pandas.plotting._matplotlib.style._get_colors_from_colormap (str | Colormap colormap, int num_colors) protected
Get colors from colormap.
Definition at line 142 of file style.py.
References _get_cmap_instance().
Referenced by _derive_colors().
_get_default_colors()
list[Color] pandas.plotting._matplotlib.style._get_default_colors (int num_colors) protected
Get `num_colors` of default colors from matplotlib rc params.
Definition at line 228 of file style.py.
Referenced by _get_colors_from_color_type().
_get_random_colors()
list[Color] pandas.plotting._matplotlib.style._get_random_colors (int num_colors) protected
Get `num_colors` of random colors.
Definition at line 236 of file style.py.
References _random_color().
Referenced by _get_colors_from_color_type().
_is_floats_color()
bool pandas.plotting._matplotlib.style._is_floats_color (Color | Collection[Color] color) protected
Check if color comprises a sequence of floats representing color.
Definition at line 209 of file style.py.
Referenced by _is_single_color().
_is_single_color()
bool pandas.plotting._matplotlib.style._is_single_color (Color | Collection[Color] color) protected
Check if `color` is a single color, not a sequence of colors.
Single color is of these kinds:
    - Named color "red", "C0", "firebrick"
    - Alias "g"
    - Sequence of floats, such as (0.1, 0.2, 0.3) or (0.1, 0.2, 0.3, 0.4).
See Also
--------
_is_single_string_color
Definition at line 176 of file style.py.
References _is_floats_color(), and _is_single_string_color().
Referenced by _gen_list_of_colors_from_iterable(), and _get_colors_from_color().
_is_single_string_color()
bool pandas.plotting._matplotlib.style._is_single_string_color (Color color) protected
Check if `color` is a single string color.
Examples of single string colors:
    - 'r'
    - 'g'
    - 'red'
    - 'green'
    - 'C3'
    - 'firebrick'
Parameters
----------
color : Color
    Color string or sequence of floats.
Returns
-------
bool
    True if `color` looks like a valid color.
    False otherwise.
Definition at line 248 of file style.py.
Referenced by _is_single_color().
_random_color()
list[float] pandas.plotting._matplotlib.style._random_color (int column) protected
Get a random color represented as a list of length 3
Definition at line 241 of file style.py.
Referenced by _get_random_colors().
get_standard_colors()
pandas.plotting._matplotlib.style.get_standard_colors (int num_colors, Colormap | None colormap = None, str color_type = "default", dict[str, Color] | Color | Collection[Color] | None color = None)
Get standard colors based on `colormap`, `color_type` or `color` inputs.
Parameters
----------
num_colors : int
    Minimum number of colors to be returned.
    Ignored if `color` is a dictionary.
colormap : :py:class:`matplotlib.colors.Colormap`, optional
    Matplotlib colormap.
    When provided, the resulting colors will be derived from the colormap.
color_type : {"default", "random"}, optional
    Type of colors to derive. Used if provided `color` and `colormap` are None.
    Ignored if either `color` or `colormap` are not None.
color : dict or str or sequence, optional
    Color(s) to be used for deriving sequence of colors.
    Can be either be a dictionary, or a single color (single color string,
    or sequence of floats representing a single color),
    or a sequence of colors.
Returns
-------
dict or list
    Standard colors. Can either be a mapping if `color` was a dictionary,
    or a list of colors with a length of `num_colors` or more.
Warns
-----
UserWarning
    If both `colormap` and `color` are provided.
    Parameter `color` will override.
Definition at line 29 of file style.py.
References _cycle_colors(), and _derive_colors().