Code Cloning Analysis: fontTools.cffLib.PrivateDict Class Reference
fontTools.cffLib.PrivateDict Class Reference
Public Member Functions
__init__ (self, strings=None, file=None, offset=None, isCFF2=None, vstore=None)
in_cff2 (self)
getNumRegions (self, vi=None)
Public Member Functions inherited from fontTools.cffLib.BaseDict
__init__ (self, strings=None, file=None, offset=None, isCFF2=None)
decompile (self, data)
postDecompile (self)
getCompiler (self, strings, parent, isCFF2=None)
__getattr__ (self, name)
toXML (self, xmlWriter)
fromXML (self, name, attrs, content)
Public Attributes
vstore = vstore
nominalWidthX = None
Public Attributes inherited from fontTools.cffLib.BaseDict
dict rawDict = {}
list skipNames = []
strings = strings
file = file
offset = offset
order
Static Public Attributes
defaults = buildDefaults(privateDictOperators)
converters = buildConverters(privateDictOperators)
decompilerClass = PrivateDictDecompiler
compilerClass = PrivateDictCompiler
Additional Inherited Members
Protected Attributes inherited from fontTools.cffLib.BaseDict
_isCFF2 = isCFF2
Detailed Description
Definition at line 2710 of file __init__.py.
Constructor & Destructor Documentation
__init__()
fontTools.cffLib.PrivateDict.__init__ (self, strings = None, file = None, offset = None, isCFF2 = None, vstore = None)
Definition at line 2717 of file __init__.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
getNumRegions()
fontTools.cffLib.PrivateDict.getNumRegions (self, vi = None)
Definition at line 2736 of file __init__.py.
in_cff2()
fontTools.cffLib.PrivateDict.in_cff2 (self)
Definition at line 2733 of file __init__.py.
Member Data Documentation
compilerClass
fontTools.cffLib.PrivateDict.compilerClass = PrivateDictCompiler static
Definition at line 2715 of file __init__.py.
converters
fontTools.cffLib.PrivateDict.converters = buildConverters(privateDictOperators) static
Definition at line 2712 of file __init__.py.
Referenced by pandas.io.parsers.python_parser.PythonParser.__init__(), and pandas.io.parsers.base_parser.ParserBase._clean_mapping().
decompilerClass
fontTools.cffLib.PrivateDict.decompilerClass = PrivateDictDecompiler static
Definition at line 2714 of file __init__.py.
defaults
fontTools.cffLib.PrivateDict.defaults = buildDefaults(privateDictOperators) static
Definition at line 2711 of file __init__.py.
Referenced by pip._internal.cli.parser.ConfigOptionParser._update_defaults(), and pip._internal.cli.parser.ConfigOptionParser.get_default_values().
nominalWidthX
fontTools.cffLib.PrivateDict.nominalWidthX = None
Definition at line 2725 of file __init__.py.
vstore
fontTools.cffLib.PrivateDict.vstore = vstore
Definition at line 2719 of file __init__.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/cffLib/__init__.py