Code Cloning Analysis: numpy.lib.tests.test_function_base.TestCov Class Reference
numpy.lib.tests.test_function_base.TestCov Class Reference
Public Member Functions
test_basic (self)
test_complex (self)
test_xy (self)
test_empty (self)
test_wrong_ddof (self)
test_1D_rowvar (self)
test_1D_variance (self)
test_fweights (self)
test_aweights (self)
test_unit_fweights_and_aweights (self)
test_cov_dtype (self, test_type)
Static Public Attributes
x1 = np.array([[0, 2], [1, 1], [2, 0]]).T
res1 = np.array([[1., -1.], [-1., 1.]])
x2 = np.array([0.0, 1.0, 2.0], ndmin=2)
frequencies = np.array([1, 4, 1])
x2_repeats = np.array([[0.0], [1.0], [1.0], [1.0], [1.0], [2.0]]).T
res2 = np.array([[0.4, -0.4], [-0.4, 0.4]])
unit_frequencies = np.ones(3, dtype=np.int_)
weights = np.array([1.0, 4.0, 1.0])
res3 = np.array([[2. / 3., -2. / 3.], [-2. / 3., 2. / 3.]])
unit_weights = np.ones(3)
x3 = np.array([0.3942, 0.5969, 0.7730, 0.9918, 0.7964])
Detailed Description
Definition at line 2319 of file test_function_base.py.
Member Function Documentation
test_1D_rowvar()
numpy.lib.tests.test_function_base.TestCov.test_1D_rowvar (self)
Definition at line 2362 of file test_function_base.py.
test_1D_variance()
numpy.lib.tests.test_function_base.TestCov.test_1D_variance (self)
Definition at line 2367 of file test_function_base.py.
test_aweights()
numpy.lib.tests.test_function_base.TestCov.test_aweights (self)
Definition at line 2386 of file test_function_base.py.
test_basic()
numpy.lib.tests.test_function_base.TestCov.test_basic (self)
Definition at line 2332 of file test_function_base.py.
test_complex()
numpy.lib.tests.test_function_base.TestCov.test_complex (self)
Definition at line 2335 of file test_function_base.py.
test_cov_dtype()
numpy.lib.tests.test_function_base.TestCov.test_cov_dtype (self, test_type)
Definition at line 2419 of file test_function_base.py.
test_empty()
numpy.lib.tests.test_function_base.TestCov.test_empty (self)
Definition at line 2346 of file test_function_base.py.
test_fweights()
numpy.lib.tests.test_function_base.TestCov.test_fweights (self)
Definition at line 2370 of file test_function_base.py.
test_unit_fweights_and_aweights()
numpy.lib.tests.test_function_base.TestCov.test_unit_fweights_and_aweights (self)
Definition at line 2398 of file test_function_base.py.
test_wrong_ddof()
numpy.lib.tests.test_function_base.TestCov.test_wrong_ddof (self)
Definition at line 2355 of file test_function_base.py.
test_xy()
numpy.lib.tests.test_function_base.TestCov.test_xy (self)
Definition at line 2341 of file test_function_base.py.
Member Data Documentation
frequencies
numpy.lib.tests.test_function_base.TestCov.frequencies = np.array([1, 4, 1]) static
Definition at line 2323 of file test_function_base.py.
res1
numpy.lib.tests.test_function_base.TestCov.res1 = np.array([[1., -1.], [-1., 1.]]) static
Definition at line 2321 of file test_function_base.py.
res2
numpy.lib.tests.test_function_base.TestCov.res2 = np.array([[0.4, -0.4], [-0.4, 0.4]]) static
Definition at line 2325 of file test_function_base.py.
res3
numpy.lib.tests.test_function_base.TestCov.res3 = np.array([[2. / 3., -2. / 3.], [-2. / 3., 2. / 3.]]) static
Definition at line 2328 of file test_function_base.py.
unit_frequencies
numpy.lib.tests.test_function_base.TestCov.unit_frequencies = np.ones(3, dtype=np.int_) static
Definition at line 2326 of file test_function_base.py.
unit_weights
numpy.lib.tests.test_function_base.TestCov.unit_weights = np.ones(3) static
Definition at line 2329 of file test_function_base.py.
weights
numpy.lib.tests.test_function_base.TestCov.weights = np.array([1.0, 4.0, 1.0]) static
Definition at line 2327 of file test_function_base.py.
Referenced by sklearn.impute._knn.KNNImputer._calc_impute(), pandas.plotting._matplotlib.hist.HistPlot._calculate_bins(), scipy.stats._kde.gaussian_kde._compute_covariance(), sklearn.ensemble._voting._BaseVoting._weights_not_none(), scipy.stats._kde.gaussian_kde.evaluate(), sklearn.ensemble._voting._BaseVoting.fit(), scipy.stats._kde.gaussian_kde.integrate_box(), scipy.stats._kde.gaussian_kde.integrate_box_1d(), scipy.stats._kde.gaussian_kde.integrate_gaussian(), scipy.stats._kde.gaussian_kde.logpdf(), scipy.stats._kde.gaussian_kde.marginal(), sklearn.neighbors._classification.KNeighborsClassifier.predict(), sklearn.neighbors._regression.KNeighborsRegressor.predict(), sklearn.neighbors._regression.RadiusNeighborsRegressor.predict(), sklearn.neighbors._classification.KNeighborsClassifier.predict_proba(), sklearn.neighbors._classification.RadiusNeighborsClassifier.predict_proba(), and scipy.stats._kde.gaussian_kde.resample().
x1
numpy.lib.tests.test_function_base.TestCov.x1 = np.array([[0, 2], [1, 1], [2, 0]]).T static
Definition at line 2320 of file test_function_base.py.
x2
numpy.lib.tests.test_function_base.TestCov.x2 = np.array([0.0, 1.0, 2.0], ndmin=2) static
Definition at line 2322 of file test_function_base.py.
x2_repeats
numpy.lib.tests.test_function_base.TestCov.x2_repeats = np.array([[0.0], [1.0], [1.0], [1.0], [1.0], [2.0]]).T static
Definition at line 2324 of file test_function_base.py.
x3
numpy.lib.tests.test_function_base.TestCov.x3 = np.array([0.3942, 0.5969, 0.7730, 0.9918, 0.7964]) static
Definition at line 2330 of file test_function_base.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/lib/tests/test_function_base.py