Code Cloning Analysis: fontTools.ttLib.tables.otTables.LookupList Class Reference
fontTools.ttLib.tables.otTables.LookupList Class Reference
Public Member Functions
table (self)
toXML2 (self, xmlWriter, font)
Public Member Functions inherited from fontTools.ttLib.tables.otBase.BaseTable
__getattr__ (self, attr)
ensureDecompiled (self, recurse=False)
__getstate__ (self)
getRecordSize (cls, reader)
getConverters (self)
getConverterByName (self, name)
populateDefaults (self, propagator=None)
decompile (self, reader, font)
compile (self, writer, font)
readFormat (self, reader)
writeFormat (self, writer)
toXML (self, xmlWriter, font, attrs=None, name=None)
fromXML (self, name, attrs, content, font)
__ne__ (self, other)
__eq__ (self, other)
Iterator[SubTableEntry] iterSubTables (self)
getVariableAttrs (self)
Public Attributes
Lookup
Public Attributes inherited from fontTools.ttLib.tables.otBase.BaseTable
converters
Detailed Description
Definition at line 1687 of file otTables.py.
Member Function Documentation
table()
fontTools.ttLib.tables.otTables.LookupList.table (self)
Definition at line 1689 of file otTables.py.
Referenced by pandas.io.pytables.Table.create_index(), pandas.io.pytables.AppendableTable.delete(), pandas.io.pytables.AppendableFrameTable.get_object(), pandas.io.pytables.GenericTable.indexables(), pandas.io.pytables.Table.indexables(), pandas.io.pytables.Table.read_column(), pandas.io.pytables.Table.table(), and pandas.io.pytables.AppendableTable.write_data_chunk().
toXML2()
fontTools.ttLib.tables.otTables.LookupList.toXML2 (self, xmlWriter, font)
Reimplemented from fontTools.ttLib.tables.otBase.BaseTable.
Definition at line 1698 of file otTables.py.
Member Data Documentation
Lookup
fontTools.ttLib.tables.otTables.LookupList.Lookup
Definition at line 1690 of file otTables.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ttLib/tables/otTables.py