Code Cloning Analysis: pandas.core.computation.pytables.UnaryOp Class Reference
pandas.core.computation.pytables.UnaryOp Class Reference
Public Member Functions
prune (self, klass)
Public Member Functions inherited from pandas.core.computation.ops.UnaryOp
None __init__ (self, Literal["+", "-", "~", "not"] op, operand)
MathCall __call__ (self, env)
str __repr__ (self)
np.dtype return_type (self)
Public Member Functions inherited from pandas.core.computation.ops.Op
None __init__ (self, str op, Iterable[Term|Op] operands, encoding=None)
Iterator __iter__ (self)
str __repr__ (self)
bool has_invalid_return_type (self)
operand_types (self)
bool is_scalar (self)
bool is_datetime (self)
Additional Inherited Members
Public Attributes inherited from pandas.core.computation.ops.UnaryOp
operand = operand
func = _unary_ops_dict[op]
Public Attributes inherited from pandas.core.computation.ops.Op
op = _bool_op_map.get(op, op)
operands = operands
encoding = encoding
Detailed Description
Definition at line 401 of file pytables.py.
Member Function Documentation
prune()
pandas.core.computation.pytables.UnaryOp.prune (self, klass)
Definition at line 402 of file pytables.py.
Referenced by scipy.sparse._bsr._bsr_base.check_format(), scipy.sparse._compressed._cs_matrix.check_format(), scipy.sparse._bsr._bsr_base.eliminate_zeros(), scipy.sparse._compressed._cs_matrix.eliminate_zeros(), scipy.sparse._bsr._bsr_base.sum_duplicates(), and scipy.sparse._compressed._cs_matrix.sum_duplicates().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/core/computation/pytables.py