Code Cloning Analysis: sklearn.model_selection.tests.test_search Namespace Reference
sklearn.model_selection.tests.test_search Namespace Reference
Classes
class BrokenClassifier
class FailingClassifier
class LinearSVCNoScore
class MockClassifier
Functions
assert_grid_iter_equals_getitem (grid)
test_validate_parameter_input (klass, input, error_type, error_message)
test_parameter_grid ()
test_grid_search ()
test_grid_search_pipeline_steps ()
test_SearchCV_with_fit_params (SearchCV)
test_grid_search_no_score ()
test_grid_search_score_method ()
test_grid_search_groups ()
test_classes__property ()
test_trivial_cv_results_attr ()
test_no_refit ()
test_grid_search_error ()
test_grid_search_one_grid_point ()
test_grid_search_when_param_grid_includes_range ()
test_grid_search_bad_param_grid ()
test_grid_search_sparse (csr_container)
test_grid_search_sparse_scoring (csr_container)
test_grid_search_precomputed_kernel ()
test_grid_search_precomputed_kernel_error_nonsquare ()
test_refit ()
test_refit_callable ()
test_refit_callable_invalid_type ()
test_refit_callable_out_bound (out_bound_value, search_cv)
test_refit_callable_multi_metric ()
test_gridsearch_nd ()
test_X_as_list ()
test_y_as_list ()
test_pandas_input ()
test_unsupervised_grid_search ()
test_gridsearch_no_predict ()
test_param_sampler ()
check_cv_results_array_types (search, param_keys, score_keys, expected_cv_results_kinds)
check_cv_results_keys (cv_results, param_keys, score_keys, n_cand, extra_keys=())
test_grid_search_cv_results ()
test_random_search_cv_results ()
test_search_default_iid (SearchCV, specialized_params)
test_grid_search_cv_results_multimetric ()
test_random_search_cv_results_multimetric ()
compare_cv_results_multimetric_with_single (search_multi, search_acc, search_rec)
compare_refit_methods_when_refit_with_acc (search_multi, search_acc, refit)
test_search_cv_score_samples_error (search_cv)
test_unsupported_sample_weight_scorer ()
test_search_cv_sample_weight_equivalence (estimator)
test_search_cv_score_samples_method (search_cv)
test_search_cv_results_rank_tie_breaking ()
test_search_cv_results_none_param ()
test_search_cv_timing ()
test_grid_search_correct_score_results ()
test_pickle ()
test_grid_search_with_multioutput_data ()
test_predict_proba_disabled ()
test_grid_search_allows_nans ()
test_grid_search_failing_classifier ()
test_grid_search_classifier_all_fits_fail ()
test_grid_search_failing_classifier_raise ()
test_parameters_sampler_replacement ()
test_stochastic_gradient_loss_param ()
test_search_train_scores_set_to_false ()
test_grid_search_cv_splits_consistency ()
test_transform_inverse_transform_round_trip ()
test_custom_run_search ()
test__custom_fit_no_run_search ()
test_empty_cv_iterator_error ()
test_random_search_bad_cv ()
test_searchcv_raise_warning_with_non_finite_score (SearchCV, specialized_params, return_train_score)
test_callable_multimetric_confusion_matrix ()
test_callable_multimetric_same_as_list_of_strings ()
test_callable_single_metric_same_as_single_string ()
test_callable_multimetric_error_on_invalid_key ()
test_callable_multimetric_error_failing_clf ()
test_callable_multimetric_clf_all_fits_fail ()
test_n_features_in ()
test_search_cv_pairwise_property_delegated_to_base_estimator (pairwise)
test_search_cv__pairwise_property_delegated_to_base_estimator ()
test_search_cv_pairwise_property_equivalence_of_precomputed ()
test_scalar_fit_param (SearchCV, param_search)
test_scalar_fit_param_compat (SearchCV, param_search)
test_search_cv_using_minimal_compatible_estimator (SearchCV, Predictor)
test_search_cv_verbose_3 (capsys, return_train_score)
test_search_estimator_param (SearchCV, param_search)
test_search_with_2d_array ()
test_search_html_repr ()
test_multi_metric_search_forwards_metadata (SearchCV, param_search)
test_score_rejects_params_with_no_routing_enabled (SearchCV, param_search)
test_cv_results_dtype_issue_29074 ()
test_search_with_estimators_issue_29157 ()
test_cv_results_multi_size_array ()
test_array_api_search_cv_classifier (SearchCV, array_namespace, device, dtype)
test_yield_masked_array_for_each_param (candidate_params, expected)
test_yield_masked_array_no_runtime_warning ()
Variables
X = np.array([[-1, -1], [-2, -1], [1, 1], [2, 1]])
y = np.array([1, 1, 2, 2])
one_hot_encoder = OneHotEncoder()
ordinal_encoder = OrdinalEncoder()
ma_with_tuples = np.ma.MaskedArray(np.empty(2), mask=True, dtype=object)
int n_counts = 0
pairwise = pairwise
a = a
r_ = r
base_clf = base_clf
parameter1 = parameter1
parameter2 = parameter2
parameter3 = parameter3
parameter4 = parameter4
Detailed Description
Test the search module
Function Documentation
assert_grid_iter_equals_getitem()
sklearn.model_selection.tests.test_search.assert_grid_iter_equals_getitem (grid)
Definition at line 160 of file test_search.py.
check_cv_results_array_types()
sklearn.model_selection.tests.test_search.check_cv_results_array_types (search, param_keys, score_keys, expected_cv_results_kinds)
Definition at line 921 of file test_search.py.
check_cv_results_keys()
sklearn.model_selection.tests.test_search.check_cv_results_keys (cv_results, param_keys, score_keys, n_cand, extra_keys = ())
Definition at line 943 of file test_search.py.
compare_cv_results_multimetric_with_single()
sklearn.model_selection.tests.test_search.compare_cv_results_multimetric_with_single (search_multi, search_acc, search_rec)
Compare multi-metric cv_results with the ensemble of multiple
single metric cv_results from single metric grid/random search
Definition at line 1243 of file test_search.py.
Referenced by test_refit_callable_multi_metric().
compare_refit_methods_when_refit_with_acc()
sklearn.model_selection.tests.test_search.compare_refit_methods_when_refit_with_acc (search_multi, search_acc, refit)
Compare refit multi-metric search methods with single metric methods
Definition at line 1281 of file test_search.py.
Referenced by test_refit_callable_multi_metric().
test__custom_fit_no_run_search()
sklearn.model_selection.tests.test_search.test__custom_fit_no_run_search ()
Definition at line 2080 of file test_search.py.
test_array_api_search_cv_classifier()
sklearn.model_selection.tests.test_search.test_array_api_search_cv_classifier (SearchCV, array_namespace, device, dtype)
Definition at line 2865 of file test_search.py.
test_callable_multimetric_clf_all_fits_fail()
sklearn.model_selection.tests.test_search.test_callable_multimetric_clf_all_fits_fail ()
Definition at line 2332 of file test_search.py.
test_callable_multimetric_confusion_matrix()
sklearn.model_selection.tests.test_search.test_callable_multimetric_confusion_matrix ()
Definition at line 2206 of file test_search.py.
test_callable_multimetric_error_failing_clf()
sklearn.model_selection.tests.test_search.test_callable_multimetric_error_failing_clf ()
Definition at line 2304 of file test_search.py.
test_callable_multimetric_error_on_invalid_key()
sklearn.model_selection.tests.test_search.test_callable_multimetric_error_on_invalid_key ()
Definition at line 2283 of file test_search.py.
test_callable_multimetric_same_as_list_of_strings()
sklearn.model_selection.tests.test_search.test_callable_multimetric_same_as_list_of_strings ()
Definition at line 2229 of file test_search.py.
test_callable_single_metric_same_as_single_string()
sklearn.model_selection.tests.test_search.test_callable_single_metric_same_as_single_string ()
Definition at line 2255 of file test_search.py.
test_classes__property()
sklearn.model_selection.tests.test_search.test_classes__property ()
Definition at line 364 of file test_search.py.
test_custom_run_search()
sklearn.model_selection.tests.test_search.test_custom_run_search ()
Definition at line 2023 of file test_search.py.
test_cv_results_dtype_issue_29074()
sklearn.model_selection.tests.test_search.test_cv_results_dtype_issue_29074 ()
Non-regression test for https://github.com/scikit-learn/scikit-learn/issues/29074
Definition at line 2750 of file test_search.py.
test_cv_results_multi_size_array()
sklearn.model_selection.tests.test_search.test_cv_results_multi_size_array ()
Check that GridSearchCV works with params that are arrays of different sizes.
Non-regression test for #29277.
Definition at line 2828 of file test_search.py.
test_empty_cv_iterator_error()
sklearn.model_selection.tests.test_search.test_empty_cv_iterator_error ()
Definition at line 2100 of file test_search.py.
test_grid_search()
sklearn.model_selection.tests.test_search.test_grid_search ()
Definition at line 219 of file test_search.py.
test_grid_search_allows_nans()
sklearn.model_selection.tests.test_search.test_grid_search_allows_nans ()
Definition at line 1681 of file test_search.py.
test_grid_search_bad_param_grid()
sklearn.model_selection.tests.test_search.test_grid_search_bad_param_grid ()
Definition at line 477 of file test_search.py.
test_grid_search_classifier_all_fits_fail()
sklearn.model_selection.tests.test_search.test_grid_search_classifier_all_fits_fail ()
Definition at line 1795 of file test_search.py.
test_grid_search_correct_score_results()
sklearn.model_selection.tests.test_search.test_grid_search_correct_score_results ()
Definition at line 1571 of file test_search.py.
test_grid_search_cv_results()
sklearn.model_selection.tests.test_search.test_grid_search_cv_results ()
Definition at line 950 of file test_search.py.
test_grid_search_cv_results_multimetric()
sklearn.model_selection.tests.test_search.test_grid_search_cv_results_multimetric ()
Definition at line 1172 of file test_search.py.
test_grid_search_cv_splits_consistency()
sklearn.model_selection.tests.test_search.test_grid_search_cv_splits_consistency ()
Definition at line 1919 of file test_search.py.
test_grid_search_error()
sklearn.model_selection.tests.test_search.test_grid_search_error ()
Definition at line 444 of file test_search.py.
test_grid_search_failing_classifier()
sklearn.model_selection.tests.test_search.test_grid_search_failing_classifier ()
Definition at line 1714 of file test_search.py.
test_grid_search_failing_classifier_raise()
sklearn.model_selection.tests.test_search.test_grid_search_failing_classifier_raise ()
Definition at line 1817 of file test_search.py.
test_grid_search_groups()
sklearn.model_selection.tests.test_search.test_grid_search_groups ()
Definition at line 333 of file test_search.py.
test_grid_search_no_score()
sklearn.model_selection.tests.test_search.test_grid_search_no_score ()
Definition at line 281 of file test_search.py.
test_grid_search_one_grid_point()
sklearn.model_selection.tests.test_search.test_grid_search_one_grid_point ()
Definition at line 454 of file test_search.py.
test_grid_search_pipeline_steps()
sklearn.model_selection.tests.test_search.test_grid_search_pipeline_steps ()
Definition at line 244 of file test_search.py.
test_grid_search_precomputed_kernel()
sklearn.model_selection.tests.test_search.test_grid_search_precomputed_kernel ()
Definition at line 576 of file test_search.py.
test_grid_search_precomputed_kernel_error_nonsquare()
sklearn.model_selection.tests.test_search.test_grid_search_precomputed_kernel_error_nonsquare ()
Definition at line 605 of file test_search.py.
test_grid_search_score_method()
sklearn.model_selection.tests.test_search.test_grid_search_score_method ()
Definition at line 305 of file test_search.py.
test_grid_search_sparse()
sklearn.model_selection.tests.test_search.test_grid_search_sparse (csr_container)
Definition at line 518 of file test_search.py.
test_grid_search_sparse_scoring()
sklearn.model_selection.tests.test_search.test_grid_search_sparse_scoring (csr_container)
Definition at line 540 of file test_search.py.
test_grid_search_when_param_grid_includes_range()
sklearn.model_selection.tests.test_search.test_grid_search_when_param_grid_includes_range ()
Definition at line 468 of file test_search.py.
test_grid_search_with_multioutput_data()
sklearn.model_selection.tests.test_search.test_grid_search_with_multioutput_data ()
Definition at line 1626 of file test_search.py.
test_gridsearch_nd()
sklearn.model_selection.tests.test_search.test_gridsearch_nd ()
Definition at line 768 of file test_search.py.
test_gridsearch_no_predict()
sklearn.model_selection.tests.test_search.test_gridsearch_no_predict ()
Definition at line 878 of file test_search.py.
test_multi_metric_search_forwards_metadata()
sklearn.model_selection.tests.test_search.test_multi_metric_search_forwards_metadata (SearchCV, param_search)
Test that *SearchCV forwards metadata correctly when passed multiple metrics.
Definition at line 2694 of file test_search.py.
test_n_features_in()
sklearn.model_selection.tests.test_search.test_n_features_in ()
Definition at line 2362 of file test_search.py.
test_no_refit()
sklearn.model_selection.tests.test_search.test_no_refit ()
Definition at line 401 of file test_search.py.
test_pandas_input()
sklearn.model_selection.tests.test_search.test_pandas_input ()
Definition at line 819 of file test_search.py.
test_param_sampler()
sklearn.model_selection.tests.test_search.test_param_sampler ()
Definition at line 895 of file test_search.py.
test_parameter_grid()
sklearn.model_selection.tests.test_search.test_parameter_grid ()
Definition at line 183 of file test_search.py.
test_parameters_sampler_replacement()
sklearn.model_selection.tests.test_search.test_parameters_sampler_replacement ()
Definition at line 1838 of file test_search.py.
test_pickle()
sklearn.model_selection.tests.test_search.test_pickle ()
Definition at line 1608 of file test_search.py.
test_predict_proba_disabled()
sklearn.model_selection.tests.test_search.test_predict_proba_disabled ()
Definition at line 1672 of file test_search.py.
test_random_search_bad_cv()
sklearn.model_selection.tests.test_search.test_random_search_bad_cv ()
Definition at line 2125 of file test_search.py.
test_random_search_cv_results()
sklearn.model_selection.tests.test_search.test_random_search_cv_results ()
Definition at line 1040 of file test_search.py.
test_random_search_cv_results_multimetric()
sklearn.model_selection.tests.test_search.test_random_search_cv_results_multimetric ()
Definition at line 1207 of file test_search.py.
test_refit()
sklearn.model_selection.tests.test_search.test_refit ()
Definition at line 631 of file test_search.py.
test_refit_callable()
sklearn.model_selection.tests.test_search.test_refit_callable ()
Test refit=callable, which adds flexibility in identifying the
"best" estimator.
Definition at line 644 of file test_search.py.
test_refit_callable_invalid_type()
sklearn.model_selection.tests.test_search.test_refit_callable_invalid_type ()
Test implementation catches the errors when 'best_index_' returns an
invalid result.
Definition at line 689 of file test_search.py.
test_refit_callable_multi_metric()
sklearn.model_selection.tests.test_search.test_refit_callable_multi_metric ()
Test refit=callable in multiple metric evaluation setting
Definition at line 739 of file test_search.py.
References compare_cv_results_multimetric_with_single(), and compare_refit_methods_when_refit_with_acc().
test_refit_callable_out_bound()
sklearn.model_selection.tests.test_search.test_refit_callable_out_bound (out_bound_value, search_cv)
Test implementation catches the errors when 'best_index_' returns an
out of bound result.
Definition at line 715 of file test_search.py.
test_scalar_fit_param()
sklearn.model_selection.tests.test_search.test_scalar_fit_param (SearchCV, param_search)
Definition at line 2464 of file test_search.py.
test_scalar_fit_param_compat()
sklearn.model_selection.tests.test_search.test_scalar_fit_param_compat (SearchCV, param_search)
Definition at line 2491 of file test_search.py.
test_score_rejects_params_with_no_routing_enabled()
sklearn.model_selection.tests.test_search.test_score_rejects_params_with_no_routing_enabled (SearchCV, param_search)
*SearchCV should reject **params when metadata routing is not enabled
since this is added only when routing is enabled.
Definition at line 2733 of file test_search.py.
test_search_cv__pairwise_property_delegated_to_base_estimator()
sklearn.model_selection.tests.test_search.test_search_cv__pairwise_property_delegated_to_base_estimator ()
Test implementation of BaseSearchCV has the pairwise property
which matches the pairwise tag of its estimator.
This test make sure pairwise tag is delegated to the base estimator.
Non-regression test for issue #13920.
Definition at line 2401 of file test_search.py.
test_search_cv_pairwise_property_delegated_to_base_estimator()
sklearn.model_selection.tests.test_search.test_search_cv_pairwise_property_delegated_to_base_estimator (pairwise)
Test implementation of BaseSearchCV has the pairwise tag
which matches the pairwise tag of its estimator.
This test make sure pairwise tag is delegated to the base estimator.
Non-regression test for issue #13920.
Definition at line 2380 of file test_search.py.
test_search_cv_pairwise_property_equivalence_of_precomputed()
sklearn.model_selection.tests.test_search.test_search_cv_pairwise_property_equivalence_of_precomputed ()
Test implementation of BaseSearchCV has the pairwise tag
which matches the pairwise tag of its estimator.
This test ensures the equivalence of 'precomputed'.
Non-regression test for issue #13920.
Definition at line 2430 of file test_search.py.
test_search_cv_results_none_param()
sklearn.model_selection.tests.test_search.test_search_cv_results_none_param ()
Definition at line 1515 of file test_search.py.
test_search_cv_results_rank_tie_breaking()
sklearn.model_selection.tests.test_search.test_search_cv_results_rank_tie_breaking ()
Definition at line 1481 of file test_search.py.
test_search_cv_sample_weight_equivalence()
sklearn.model_selection.tests.test_search.test_search_cv_sample_weight_equivalence (estimator)
Definition at line 1368 of file test_search.py.
test_search_cv_score_samples_error()
sklearn.model_selection.tests.test_search.test_search_cv_score_samples_error (search_cv)
Definition at line 1312 of file test_search.py.
test_search_cv_score_samples_method()
sklearn.model_selection.tests.test_search.test_search_cv_score_samples_method (search_cv)
Definition at line 1448 of file test_search.py.
test_search_cv_timing()
sklearn.model_selection.tests.test_search.test_search_cv_timing ()
Definition at line 1531 of file test_search.py.
test_search_cv_using_minimal_compatible_estimator()
sklearn.model_selection.tests.test_search.test_search_cv_using_minimal_compatible_estimator (SearchCV, Predictor)
Definition at line 2545 of file test_search.py.
test_search_cv_verbose_3()
sklearn.model_selection.tests.test_search.test_search_cv_verbose_3 (capsys, return_train_score)
Check that search cv with verbose>2 shows the score for single
metrics. non-regression test for #19658.
Definition at line 2574 of file test_search.py.
test_search_default_iid()
sklearn.model_selection.tests.test_search.test_search_default_iid (SearchCV, specialized_params)
Definition at line 1116 of file test_search.py.
test_search_estimator_param()
sklearn.model_selection.tests.test_search.test_search_estimator_param (SearchCV, param_search)
Definition at line 2605 of file test_search.py.
test_search_html_repr()
sklearn.model_selection.tests.test_search.test_search_html_repr ()
Test different HTML representations for GridSearchCV.
Definition at line 2654 of file test_search.py.
test_search_train_scores_set_to_false()
sklearn.model_selection.tests.test_search.test_search_train_scores_set_to_false ()
Definition at line 1910 of file test_search.py.
test_search_with_2d_array()
sklearn.model_selection.tests.test_search.test_search_with_2d_array ()
Definition at line 2625 of file test_search.py.
test_search_with_estimators_issue_29157()
sklearn.model_selection.tests.test_search.test_search_with_estimators_issue_29157 ()
Check cv_results_ for estimators with a `dtype` parameter, e.g. OneHotEncoder.
Definition at line 2795 of file test_search.py.
test_searchcv_raise_warning_with_non_finite_score()
sklearn.model_selection.tests.test_search.test_searchcv_raise_warning_with_non_finite_score (SearchCV, specialized_params, return_train_score)
Definition at line 2161 of file test_search.py.
test_SearchCV_with_fit_params()
sklearn.model_selection.tests.test_search.test_SearchCV_with_fit_params (SearchCV)
Definition at line 263 of file test_search.py.
test_stochastic_gradient_loss_param()
sklearn.model_selection.tests.test_search.test_stochastic_gradient_loss_param ()
Definition at line 1878 of file test_search.py.
test_transform_inverse_transform_round_trip()
sklearn.model_selection.tests.test_search.test_transform_inverse_transform_round_trip ()
Definition at line 2014 of file test_search.py.
test_trivial_cv_results_attr()
sklearn.model_selection.tests.test_search.test_trivial_cv_results_attr ()
Definition at line 389 of file test_search.py.
test_unsupervised_grid_search()
sklearn.model_selection.tests.test_search.test_unsupervised_grid_search ()
Definition at line 850 of file test_search.py.
test_unsupported_sample_weight_scorer()
sklearn.model_selection.tests.test_search.test_unsupported_sample_weight_scorer ()
Checks that fitting with sample_weight raises a warning if the scorer does not
support sample_weight
Definition at line 1327 of file test_search.py.
test_validate_parameter_input()
sklearn.model_selection.tests.test_search.test_validate_parameter_input (klass, input, error_type, error_message)
Definition at line 178 of file test_search.py.
test_X_as_list()
sklearn.model_selection.tests.test_search.test_X_as_list ()
Definition at line 789 of file test_search.py.
test_y_as_list()
sklearn.model_selection.tests.test_search.test_y_as_list ()
Definition at line 804 of file test_search.py.
test_yield_masked_array_for_each_param()
sklearn.model_selection.tests.test_search.test_yield_masked_array_for_each_param (candidate_params, expected)
Definition at line 2952 of file test_search.py.
test_yield_masked_array_no_runtime_warning()
sklearn.model_selection.tests.test_search.test_yield_masked_array_no_runtime_warning ()
Definition at line 2961 of file test_search.py.
Variable Documentation
a
sklearn.model_selection.tests.test_search.a = a
Definition at line 2470 of file test_search.py.
base_clf
sklearn.model_selection.tests.test_search.base_clf = base_clf
Definition at line 2762 of file test_search.py.
ma_with_tuples
sklearn.model_selection.tests.test_search.ma_with_tuples = np.ma.MaskedArray(np.empty(2), mask=True, dtype=object)
Definition at line 2894 of file test_search.py.
n_counts
int sklearn.model_selection.tests.test_search.n_counts = 0
Definition at line 2174 of file test_search.py.
one_hot_encoder
sklearn.model_selection.tests.test_search.one_hot_encoder = OneHotEncoder()
Definition at line 2889 of file test_search.py.
ordinal_encoder
sklearn.model_selection.tests.test_search.ordinal_encoder = OrdinalEncoder()
Definition at line 2890 of file test_search.py.
pairwise
sklearn.model_selection.tests.test_search.pairwise = pairwise
Definition at line 2412 of file test_search.py.
parameter1
sklearn.model_selection.tests.test_search.parameter1 = parameter1
Definition at line 2763 of file test_search.py.
parameter2
sklearn.model_selection.tests.test_search.parameter2 = parameter2
Definition at line 2764 of file test_search.py.
parameter3
sklearn.model_selection.tests.test_search.parameter3 = parameter3
Definition at line 2765 of file test_search.py.
parameter4
sklearn.model_selection.tests.test_search.parameter4 = parameter4
Definition at line 2766 of file test_search.py.
r_
sklearn.model_selection.tests.test_search.r_ = r
Definition at line 2473 of file test_search.py.
X
sklearn.model_selection.tests.test_search.X = np.array([[-1, -1], [-2, -1], [1, 1], [2, 1]])
Definition at line 156 of file test_search.py.
y
sklearn.model_selection.tests.test_search.y = np.array([1, 1, 2, 2])
Definition at line 157 of file test_search.py.