Code Cloning Analysis: fontTools.ttLib.tables.otTables.ContextualMorphAction Class Reference
fontTools.ttLib.tables.otTables.ContextualMorphAction Class Reference
Public Member Functions
__init__ (self)
compile (self, writer, font, actionIndex)
decompile (self, reader, font, actionReader)
toXML (self, xmlWriter, font, attrs, name)
fromXML (self, name, attrs, content, font)
Public Attributes
int NewState = 0
bool SetMark
bool DontAdvance = False, False
int ReservedFlags = 0
MarkIndex = 0x4000
int CurrentIndex = 0xFFFF, 0xFFFF
Static Public Attributes
int staticSize = 8
int actionHeaderSize = 0
Additional Inherited Members
Static Public Member Functions inherited from fontTools.ttLib.tables.otTables.AATAction
compileActions (font, states)
Protected Member Functions inherited from fontTools.ttLib.tables.otTables.AATAction
_writeFlagsToXML (self, xmlWriter)
_setFlag (self, flag)
Static Protected Attributes inherited from fontTools.ttLib.tables.otTables.AATAction
_FLAGS = None
Detailed Description
Definition at line 556 of file otTables.py.
Constructor & Destructor Documentation
__init__()
fontTools.ttLib.tables.otTables.ContextualMorphAction.__init__ (self)
Definition at line 561 of file otTables.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
compile()
fontTools.ttLib.tables.otTables.ContextualMorphAction.compile (self, writer, font, actionIndex)
Definition at line 567 of file otTables.py.
Referenced by fontTools.ttLib.tables.TupleVariation.TupleVariation.getCoordWidth(), and PIL.FontFile.FontFile.save().
decompile()
fontTools.ttLib.tables.otTables.ContextualMorphAction.decompile (self, reader, font, actionReader)
Definition at line 579 of file otTables.py.
Referenced by fontTools.ttLib.tables._c_m_a_p.CmapSubtable.newSubtable().
fromXML()
fontTools.ttLib.tables.otTables.ContextualMorphAction.fromXML (self, name, attrs, content, font)
Definition at line 602 of file otTables.py.
toXML()
fontTools.ttLib.tables.otTables.ContextualMorphAction.toXML (self, xmlWriter, font, attrs, name)
Definition at line 589 of file otTables.py.
Member Data Documentation
actionHeaderSize
int fontTools.ttLib.tables.otTables.ContextualMorphAction.actionHeaderSize = 0 static
Definition at line 558 of file otTables.py.
CurrentIndex
fontTools.ttLib.tables.otTables.ContextualMorphAction.CurrentIndex = 0xFFFF, 0xFFFF
Definition at line 565 of file otTables.py.
DontAdvance
bool fontTools.ttLib.tables.otTables.ContextualMorphAction.DontAdvance = False, False
Definition at line 563 of file otTables.py.
MarkIndex
fontTools.ttLib.tables.otTables.ContextualMorphAction.MarkIndex = 0x4000
Definition at line 565 of file otTables.py.
NewState
fontTools.ttLib.tables.otTables.ContextualMorphAction.NewState = 0
Definition at line 562 of file otTables.py.
ReservedFlags
int fontTools.ttLib.tables.otTables.ContextualMorphAction.ReservedFlags = 0
Definition at line 564 of file otTables.py.
SetMark
bool fontTools.ttLib.tables.otTables.ContextualMorphAction.SetMark
Definition at line 563 of file otTables.py.
staticSize
int fontTools.ttLib.tables.otTables.ContextualMorphAction.staticSize = 8 static
Definition at line 557 of file otTables.py.
Referenced by fontTools.ttLib.tables.otConverters.BaseConverter.readArray().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ttLib/tables/otTables.py