Code Cloning Analysis: sklearn.decomposition._nmf Namespace Reference
sklearn.decomposition._nmf Namespace Reference
Classes
class _BaseNMF
class MiniBatchNMF
class NMF
Functions
norm (x)
trace_dot (X, Y)
_check_init (A, shape, whom)
_beta_divergence (X, W, H, beta, square_root=False)
_special_sparse_dot (W, H, X)
_beta_loss_to_float (beta_loss)
_initialize_nmf (X, n_components, init=None, eps=1e-6, random_state=None)
_update_coordinate_descent (X, W, Ht, l1_reg, l2_reg, shuffle, random_state)
_fit_coordinate_descent (X, W, H, tol=1e-4, max_iter=200, l1_reg_W=0, l1_reg_H=0, l2_reg_W=0, l2_reg_H=0, update_H=True, verbose=0, shuffle=False, random_state=None)
_multiplicative_update_w (X, W, H, beta_loss, l1_reg_W, l2_reg_W, gamma, H_sum=None, HHt=None, XHt=None, update_H=True)
_multiplicative_update_h (X, W, H, beta_loss, l1_reg_H, l2_reg_H, gamma, A=None, B=None, rho=None)
_fit_multiplicative_update (X, W, H, beta_loss="frobenius", max_iter=200, tol=1e-4, l1_reg_W=0, l1_reg_H=0, l2_reg_W=0, l2_reg_H=0, update_H=True, verbose=0)
non_negative_factorization (X, W=None, H=None, n_components="auto", *, init=None, update_H=True, solver="cd", beta_loss="frobenius", tol=1e-4, max_iter=200, alpha_W=0.0, alpha_H="same", l1_ratio=0.0, random_state=None, verbose=0, shuffle=False)
Variables
EPSILON = np.finfo(np.float32).eps
Detailed Description
Non-negative matrix factorization.
Function Documentation
_beta_divergence()
sklearn.decomposition._nmf._beta_divergence (X, W, H, beta, square_root = False) protected
Compute the beta-divergence of X and dot(W, H).
Parameters
----------
X : float or array-like of shape (n_samples, n_features)
W : float or array-like of shape (n_samples, n_components)
H : float or array-like of shape (n_components, n_features)
beta : float or {'frobenius', 'kullback-leibler', 'itakura-saito'}
    Parameter of the beta-divergence.
    If beta == 2, this is half the Frobenius *squared* norm.
    If beta == 1, this is the generalized Kullback-Leibler divergence.
    If beta == 0, this is the Itakura-Saito divergence.
    Else, this is the general beta-divergence.
square_root : bool, default=False
    If True, return np.sqrt(2 * res)
    For beta == 2, it corresponds to the Frobenius norm.
Returns
-------
    res : float
        Beta divergence of X and np.dot(X, H).
Definition at line 85 of file _nmf.py.
References _beta_loss_to_float(), _special_sparse_dot(), and trace_dot().
Referenced by _fit_multiplicative_update(), sklearn.decomposition._nmf.MiniBatchNMF._minibatch_step(), sklearn.decomposition._nmf.MiniBatchNMF.fit_transform(), and sklearn.decomposition._nmf.NMF.fit_transform().
_beta_loss_to_float()
sklearn.decomposition._nmf._beta_loss_to_float (beta_loss) protected
Convert string beta_loss to float.
Definition at line 213 of file _nmf.py.
Referenced by _beta_divergence(), and _fit_multiplicative_update().
_check_init()
sklearn.decomposition._nmf._check_init (A, shape, whom) protected
Definition at line 68 of file _nmf.py.
_fit_coordinate_descent()
sklearn.decomposition._nmf._fit_coordinate_descent (X, W, H, tol = 1e-4, max_iter = 200, l1_reg_W = 0, l1_reg_H = 0, l2_reg_W = 0, l2_reg_H = 0, update_H = True, verbose = 0, shuffle = False, random_state = None) protected
Compute Non-negative Matrix Factorization (NMF) with Coordinate Descent
The objective function is minimized with an alternating minimization of W
and H. Each minimization is done with a cyclic (up to a permutation of the
features) Coordinate Descent.
Parameters
----------
X : array-like of shape (n_samples, n_features)
    Constant matrix.
W : array-like of shape (n_samples, n_components)
    Initial guess for the solution.
H : array-like of shape (n_components, n_features)
    Initial guess for the solution.
tol : float, default=1e-4
    Tolerance of the stopping condition.
max_iter : int, default=200
    Maximum number of iterations before timing out.
l1_reg_W : float, default=0.
    L1 regularization parameter for W.
l1_reg_H : float, default=0.
    L1 regularization parameter for H.
l2_reg_W : float, default=0.
    L2 regularization parameter for W.
l2_reg_H : float, default=0.
    L2 regularization parameter for H.
update_H : bool, default=True
    Set to True, both W and H will be estimated from initial guesses.
    Set to False, only W will be estimated.
verbose : int, default=0
    The verbosity level.
shuffle : bool, default=False
    If true, randomize the order of coordinates in the CD solver.
random_state : int, RandomState instance or None, default=None
    Used to randomize the coordinates in the CD solver, when
    ``shuffle`` is set to ``True``. Pass an int for reproducible
    results across multiple function calls.
    See :term:`Glossary <random_state>`.
Returns
-------
W : ndarray of shape (n_samples, n_components)
    Solution to the non-negative least squares problem.
H : ndarray of shape (n_components, n_features)
    Solution to the non-negative least squares problem.
n_iter : int
    The number of iterations done by the algorithm.
References
----------
.. [1] :doi:`"Fast local algorithms for large scale nonnegative matrix and tensor
   factorizations" <10.1587/transfun.E92.A.708>`
   Cichocki, Andrzej, and P. H. A. N. Anh-Huy. IEICE transactions on fundamentals
   of electronics, communications and computer sciences 92.3: 708-721, 2009.
Definition at line 406 of file _nmf.py.
References _update_coordinate_descent().
Referenced by sklearn.decomposition._nmf.NMF._fit_transform().
_fit_multiplicative_update()
sklearn.decomposition._nmf._fit_multiplicative_update (X, W, H, beta_loss = "frobenius", max_iter = 200, tol = 1e-4, l1_reg_W = 0, l1_reg_H = 0, l2_reg_W = 0, l2_reg_H = 0, update_H = True, verbose = 0) protected
Compute Non-negative Matrix Factorization with Multiplicative Update.
The objective function is _beta_divergence(X, WH) and is minimized with an
alternating minimization of W and H. Each minimization is done with a
Multiplicative Update.
Parameters
----------
X : array-like of shape (n_samples, n_features)
    Constant input matrix.
W : array-like of shape (n_samples, n_components)
    Initial guess for the solution.
H : array-like of shape (n_components, n_features)
    Initial guess for the solution.
beta_loss : float or {'frobenius', 'kullback-leibler', \
        'itakura-saito'}, default='frobenius'
    String must be in {'frobenius', 'kullback-leibler', 'itakura-saito'}.
    Beta divergence to be minimized, measuring the distance between X
    and the dot product WH. Note that values different from 'frobenius'
    (or 2) and 'kullback-leibler' (or 1) lead to significantly slower
    fits. Note that for beta_loss <= 0 (or 'itakura-saito'), the input
    matrix X cannot contain zeros.
max_iter : int, default=200
    Number of iterations.
tol : float, default=1e-4
    Tolerance of the stopping condition.
l1_reg_W : float, default=0.
    L1 regularization parameter for W.
l1_reg_H : float, default=0.
    L1 regularization parameter for H.
l2_reg_W : float, default=0.
    L2 regularization parameter for W.
l2_reg_H : float, default=0.
    L2 regularization parameter for H.
update_H : bool, default=True
    Set to True, both W and H will be estimated from initial guesses.
    Set to False, only W will be estimated.
verbose : int, default=0
    The verbosity level.
Returns
-------
W : ndarray of shape (n_samples, n_components)
    Solution to the non-negative least squares problem.
H : ndarray of shape (n_components, n_features)
    Solution to the non-negative least squares problem.
n_iter : int
    The number of iterations done by the algorithm.
References
----------
Lee, D. D., & Seung, H., S. (2001). Algorithms for Non-negative Matrix
Factorization. Adv. Neural Inform. Process. Syst.. 13.
Fevotte, C., & Idier, J. (2011). Algorithms for nonnegative matrix
factorization with the beta-divergence. Neural Computation, 23(9).
Definition at line 731 of file _nmf.py.
References _beta_divergence(), _beta_loss_to_float(), _multiplicative_update_h(), and _multiplicative_update_w().
Referenced by sklearn.decomposition._nmf.NMF._fit_transform().
_initialize_nmf()
sklearn.decomposition._nmf._initialize_nmf (X, n_components, init = None, eps = 1e-6, random_state = None) protected
Algorithms for NMF initialization.
Computes an initial guess for the non-negative
rank k matrix approximation for X: X = WH.
Parameters
----------
X : array-like of shape (n_samples, n_features)
    The data matrix to be decomposed.
n_components : int
    The number of components desired in the approximation.
init :  {'random', 'nndsvd', 'nndsvda', 'nndsvdar'}, default=None
    Method used to initialize the procedure.
    Valid options:
    - None: 'nndsvda' if n_components <= min(n_samples, n_features),
        otherwise 'random'.
    - 'random': non-negative random matrices, scaled with:
        sqrt(X.mean() / n_components)
    - 'nndsvd': Nonnegative Double Singular Value Decomposition (NNDSVD)
        initialization (better for sparseness)
    - 'nndsvda': NNDSVD with zeros filled with the average of X
        (better when sparsity is not desired)
    - 'nndsvdar': NNDSVD with zeros filled with small random values
        (generally faster, less accurate alternative to NNDSVDa
        for when sparsity is not desired)
    - 'custom': use custom matrices W and H
    .. versionchanged:: 1.1
        When `init=None` and n_components is less than n_samples and n_features
        defaults to `nndsvda` instead of `nndsvd`.
eps : float, default=1e-6
    Truncate all values less then this in output to zero.
random_state : int, RandomState instance or None, default=None
    Used when ``init`` == 'nndsvdar' or 'random'. Pass an int for
    reproducible results across multiple function calls.
    See :term:`Glossary <random_state>`.
Returns
-------
W : array-like of shape (n_samples, n_components)
    Initial guesses for solving X ~= WH.
H : array-like of shape (n_components, n_features)
    Initial guesses for solving X ~= WH.
References
----------
C. Boutsidis, E. Gallopoulos: SVD based initialization: A head start for
nonnegative matrix factorization - Pattern Recognition, 2008
http://tinyurl.com/nndsvd
Definition at line 221 of file _nmf.py.
Referenced by sklearn.decomposition._nmf._BaseNMF._check_w_h().
_multiplicative_update_h()
sklearn.decomposition._nmf._multiplicative_update_h (X, W, H, beta_loss, l1_reg_H, l2_reg_H, gamma, A = None, B = None, rho = None) protected
update H in Multiplicative Update NMF.
Definition at line 634 of file _nmf.py.
References _special_sparse_dot().
Referenced by _fit_multiplicative_update(), and sklearn.decomposition._nmf.MiniBatchNMF._minibatch_step().
_multiplicative_update_w()
sklearn.decomposition._nmf._multiplicative_update_w (X, W, H, beta_loss, l1_reg_W, l2_reg_W, gamma, H_sum = None, HHt = None, XHt = None, update_H = True) protected
Update W in Multiplicative Update NMF.
Definition at line 526 of file _nmf.py.
References _special_sparse_dot().
Referenced by _fit_multiplicative_update(), sklearn.decomposition._nmf.MiniBatchNMF._minibatch_step(), and sklearn.decomposition._nmf.MiniBatchNMF._solve_W().
_special_sparse_dot()
sklearn.decomposition._nmf._special_sparse_dot (W, H, X) protected
Computes np.dot(W, H), only where X is non zero.
Definition at line 192 of file _nmf.py.
Referenced by _beta_divergence(), _multiplicative_update_h(), and _multiplicative_update_w().
_update_coordinate_descent()
sklearn.decomposition._nmf._update_coordinate_descent (X, W, Ht, l1_reg, l2_reg, shuffle, random_state) protected
Helper function for _fit_coordinate_descent.
Update W to minimize the objective function, iterating once over all
coordinates. By symmetry, to update H, one can call
_update_coordinate_descent(X.T, Ht, W, ...).
Definition at line 376 of file _nmf.py.
Referenced by _fit_coordinate_descent().
non_negative_factorization()
sklearn.decomposition._nmf.non_negative_factorization (X, W = None, H = None, n_components = "auto", * , init = None, update_H = True, solver = "cd", beta_loss = "frobenius", tol = 1e-4, max_iter = 200, alpha_W = 0.0, alpha_H = "same", l1_ratio = 0.0, random_state = None, verbose = 0, shuffle = False)
Compute Non-negative Matrix Factorization (NMF).
Find two non-negative matrices (W, H) whose product approximates the non-
negative matrix X. This factorization can be used for example for
dimensionality reduction, source separation or topic extraction.
The objective function is:
.. math::
    L(W, H) &= 0.5 * ||X - WH||_{loss}^2
            &+ alpha\\_W * l1\\_ratio * n\\_features * ||vec(W)||_1
            &+ alpha\\_H * l1\\_ratio * n\\_samples * ||vec(H)||_1
            &+ 0.5 * alpha\\_W * (1 - l1\\_ratio) * n\\_features * ||W||_{Fro}^2
            &+ 0.5 * alpha\\_H * (1 - l1\\_ratio) * n\\_samples * ||H||_{Fro}^2,
where :math:`||A||_{Fro}^2 = \\sum_{i,j} A_{ij}^2` (Frobenius norm) and
:math:`||vec(A)||_1 = \\sum_{i,j} abs(A_{ij})` (Elementwise L1 norm)
The generic norm :math:`||X - WH||_{loss}^2` may represent
the Frobenius norm or another supported beta-divergence loss.
The choice between options is controlled by the `beta_loss` parameter.
The regularization terms are scaled by `n_features` for `W` and by `n_samples` for
`H` to keep their impact balanced with respect to one another and to the data fit
term as independent as possible of the size `n_samples` of the training set.
The objective function is minimized with an alternating minimization of W
and H. If H is given and update_H=False, it solves for W only.
Note that the transformed data is named W and the components matrix is named H. In
the NMF literature, the naming convention is usually the opposite since the data
matrix X is transposed.
Parameters
----------
X : {array-like, sparse matrix} of shape (n_samples, n_features)
    Constant matrix.
W : array-like of shape (n_samples, n_components), default=None
    If `init='custom'`, it is used as initial guess for the solution.
    If `update_H=False`, it is initialised as an array of zeros, unless
    `solver='mu'`, then it is filled with values calculated by
    `np.sqrt(X.mean() / self._n_components)`.
    If `None`, uses the initialisation method specified in `init`.
H : array-like of shape (n_components, n_features), default=None
    If `init='custom'`, it is used as initial guess for the solution.
    If `update_H=False`, it is used as a constant, to solve for W only.
    If `None`, uses the initialisation method specified in `init`.
n_components : int or {'auto'} or None, default='auto'
    Number of components. If `None`, all features are kept.
    If `n_components='auto'`, the number of components is automatically inferred
    from `W` or `H` shapes.
    .. versionchanged:: 1.4
        Added `'auto'` value.
    .. versionchanged:: 1.6
        Default value changed from `None` to `'auto'`.
init : {'random', 'nndsvd', 'nndsvda', 'nndsvdar', 'custom'}, default=None
    Method used to initialize the procedure.
    Valid options:
    - None: 'nndsvda' if n_components < n_features, otherwise 'random'.
    - 'random': non-negative random matrices, scaled with:
      `sqrt(X.mean() / n_components)`
    - 'nndsvd': Nonnegative Double Singular Value Decomposition (NNDSVD)
      initialization (better for sparseness)
    - 'nndsvda': NNDSVD with zeros filled with the average of X
      (better when sparsity is not desired)
    - 'nndsvdar': NNDSVD with zeros filled with small random values
      (generally faster, less accurate alternative to NNDSVDa
      for when sparsity is not desired)
    - 'custom': If `update_H=True`, use custom matrices W and H which must both
      be provided. If `update_H=False`, then only custom matrix H is used.
    .. versionchanged:: 0.23
        The default value of `init` changed from 'random' to None in 0.23.
    .. versionchanged:: 1.1
        When `init=None` and n_components is less than n_samples and n_features
        defaults to `nndsvda` instead of `nndsvd`.
update_H : bool, default=True
    Set to True, both W and H will be estimated from initial guesses.
    Set to False, only W will be estimated.
solver : {'cd', 'mu'}, default='cd'
    Numerical solver to use:
    - 'cd' is a Coordinate Descent solver that uses Fast Hierarchical
      Alternating Least Squares (Fast HALS).
    - 'mu' is a Multiplicative Update solver.
    .. versionadded:: 0.17
       Coordinate Descent solver.
    .. versionadded:: 0.19
       Multiplicative Update solver.
beta_loss : float or {'frobenius', 'kullback-leibler', \
        'itakura-saito'}, default='frobenius'
    Beta divergence to be minimized, measuring the distance between X
    and the dot product WH. Note that values different from 'frobenius'
    (or 2) and 'kullback-leibler' (or 1) lead to significantly slower
    fits. Note that for beta_loss <= 0 (or 'itakura-saito'), the input
    matrix X cannot contain zeros. Used only in 'mu' solver.
    .. versionadded:: 0.19
tol : float, default=1e-4
    Tolerance of the stopping condition.
max_iter : int, default=200
    Maximum number of iterations before timing out.
alpha_W : float, default=0.0
    Constant that multiplies the regularization terms of `W`. Set it to zero
    (default) to have no regularization on `W`.
    .. versionadded:: 1.0
alpha_H : float or "same", default="same"
    Constant that multiplies the regularization terms of `H`. Set it to zero to
    have no regularization on `H`. If "same" (default), it takes the same value as
    `alpha_W`.
    .. versionadded:: 1.0
l1_ratio : float, default=0.0
    The regularization mixing parameter, with 0 <= l1_ratio <= 1.
    For l1_ratio = 0 the penalty is an elementwise L2 penalty
    (aka Frobenius Norm).
    For l1_ratio = 1 it is an elementwise L1 penalty.
    For 0 < l1_ratio < 1, the penalty is a combination of L1 and L2.
random_state : int, RandomState instance or None, default=None
    Used for NMF initialisation (when ``init`` == 'nndsvdar' or
    'random'), and in Coordinate Descent. Pass an int for reproducible
    results across multiple function calls.
    See :term:`Glossary <random_state>`.
verbose : int, default=0
    The verbosity level.
shuffle : bool, default=False
    If true, randomize the order of coordinates in the CD solver.
Returns
-------
W : ndarray of shape (n_samples, n_components)
    Solution to the non-negative least squares problem.
H : ndarray of shape (n_components, n_features)
    Solution to the non-negative least squares problem.
n_iter : int
    Actual number of iterations.
References
----------
.. [1] :doi:`"Fast local algorithms for large scale nonnegative matrix and tensor
   factorizations" <10.1587/transfun.E92.A.708>`
   Cichocki, Andrzej, and P. H. A. N. Anh-Huy. IEICE transactions on fundamentals
   of electronics, communications and computer sciences 92.3: 708-721, 2009.
.. [2] :doi:`"Algorithms for nonnegative matrix factorization with the
   beta-divergence" <10.1162/NECO_a_00168>`
   Fevotte, C., & Idier, J. (2011). Neural Computation, 23(9).
Examples
--------
>>> import numpy as np
>>> X = np.array([[1,1], [2, 1], [3, 1.2], [4, 1], [5, 0.8], [6, 1]])
>>> from sklearn.decomposition import non_negative_factorization
>>> W, H, n_iter = non_negative_factorization(
...     X, n_components=2, init='random', random_state=0)
Definition at line 905 of file _nmf.py.
norm()
sklearn.decomposition._nmf.norm (x)
Dot product-based Euclidean norm implementation.
See: http://fa.bianp.net/blog/2011/computing-the-vector-norm/
Parameters
----------
x : array-like
    Vector for which to compute the norm.
Definition at line 42 of file _nmf.py.
trace_dot()
sklearn.decomposition._nmf.trace_dot (X, Y)
Trace of np.dot(X, Y.T).
Parameters
----------
X : array-like
    First matrix.
Y : array-like
    Second matrix.
Definition at line 55 of file _nmf.py.
Referenced by _beta_divergence().
Variable Documentation
EPSILON
sklearn.decomposition._nmf.EPSILON = np.finfo(np.float32).eps
Definition at line 39 of file _nmf.py.