Code Cloning Analysis: matplotlib.tests.test_transforms.NonAffineForTest Class Reference
matplotlib.tests.test_transforms.NonAffineForTest Class Reference
Public Member Functions
__init__ (self, real_trans, *args, **kwargs)
transform_non_affine (self, values)
transform_path_non_affine (self, path)
Public Attributes
real_trans = real_trans
Static Public Attributes
bool is_affine = False
int output_dims = 2
int input_dims = 2
Detailed Description
A class which looks like a non affine transform, but does whatever
the given transform does (even if it is affine). This is very useful
for testing NonAffine behaviour with a simple Affine transform.
Definition at line 579 of file test_transforms.py.
Constructor & Destructor Documentation
__init__()
matplotlib.tests.test_transforms.NonAffineForTest.__init__ (self, real_trans, * args, ** kwargs)
Definition at line 590 of file test_transforms.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
transform_non_affine()
matplotlib.tests.test_transforms.NonAffineForTest.transform_non_affine (self, values)
Definition at line 594 of file test_transforms.py.
Referenced by matplotlib.transforms.Transform.transform(), and matplotlib.transforms.Transform.transform_path_non_affine().
transform_path_non_affine()
matplotlib.tests.test_transforms.NonAffineForTest.transform_path_non_affine (self, path)
Definition at line 597 of file test_transforms.py.
Referenced by matplotlib.transforms.Transform.transform_path().
Member Data Documentation
input_dims
int matplotlib.tests.test_transforms.NonAffineForTest.input_dims = 2 static
Definition at line 588 of file test_transforms.py.
Referenced by matplotlib.transforms.CompositeAffine2D.__init__(), matplotlib.transforms.CompositeGenericTransform.__init__(), matplotlib.transforms.Transform.transform(), matplotlib.transforms.Transform.transform_angles(), and matplotlib.transforms.Transform.transform_point().
is_affine
bool matplotlib.tests.test_transforms.NonAffineForTest.is_affine = False static
Definition at line 586 of file test_transforms.py.
Referenced by matplotlib.transforms.TransformNode.invalidate().
output_dims
int matplotlib.tests.test_transforms.NonAffineForTest.output_dims = 2 static
Definition at line 587 of file test_transforms.py.
Referenced by matplotlib.transforms.CompositeAffine2D.__init__(), matplotlib.transforms.CompositeGenericTransform.__init__(), matplotlib.transforms.CompositeGenericTransform.contains_branch_seperately(), matplotlib.transforms.Transform.contains_branch_seperately(), and matplotlib.transforms.Transform.transform_angles().
real_trans
matplotlib.tests.test_transforms.NonAffineForTest.real_trans = real_trans
Definition at line 591 of file test_transforms.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/tests/test_transforms.py