Code Cloning Analysis: pandas.tests.dtypes.test_common Namespace Reference
pandas.tests.dtypes.test_common Namespace Reference
Classes
class TestNumpyEADtype
Functions
to_ea_dtypes (dtypes)
to_numpy_dtypes (dtypes)
test_dtype_equal (name1, dtype1, name2, dtype2)
test_pyarrow_string_import_error (name, dtype)
test_dtype_equal_strict (dtype1, dtype2)
get_is_dtype_funcs ()
test_get_dtype_error_catch (func)
test_is_object ()
test_is_sparse (check_scipy)
test_is_scipy_sparse ()
test_is_datetime64_dtype ()
test_is_datetime64tz_dtype ()
test_custom_ea_kind_M_not_datetime64tz ()
test_is_timedelta64_dtype ()
test_is_period_dtype ()
test_is_interval_dtype ()
test_is_categorical_dtype ()
test_is_string_dtype (dtype, expected)
test_is_string_dtype_arraylike_with_object_elements_not_strings (data)
test_is_string_dtype_nullable (nullable_string_dtype)
test_is_integer_dtype (dtype)
test_is_not_integer_dtype (dtype)
test_is_signed_integer_dtype (dtype)
test_is_not_signed_integer_dtype (dtype)
test_is_unsigned_integer_dtype (dtype)
test_is_not_unsigned_integer_dtype (dtype)
test_is_int64_dtype (dtype)
test_type_comparison_with_numeric_ea_dtype (any_numeric_ea_dtype)
test_type_comparison_with_real_numpy_dtype (any_real_numpy_dtype)
test_type_comparison_with_signed_int_ea_dtype_and_signed_int_numpy_dtype (any_signed_int_ea_dtype, any_signed_int_numpy_dtype)
test_is_not_int64_dtype (dtype)
test_is_datetime64_any_dtype ()
test_is_datetime64_ns_dtype ()
test_is_timedelta64_ns_dtype ()
test_is_numeric_v_string_like ()
test_needs_i8_conversion ()
test_is_numeric_dtype ()
test_is_any_real_numeric_dtype ()
test_is_float_dtype ()
test_is_bool_dtype ()
test_is_bool_dtype_numpy_error ()
test_is_extension_array_dtype (check_scipy)
test_is_complex_dtype ()
test_get_dtype (input_param, result)
test_get_dtype_fails (input_param, expected_error_message)
test__is_dtype_type (input_param, result)
test_astype_nansafe_copy_false (any_int_numpy_dtype)
test_astype_object_preserves_datetime_na (from_type)
test_validate_allhashable ()
test_pandas_dtype_numpy_warning ()
test_pandas_dtype_ea_not_instance ()
test_pandas_dtype_string_dtypes (string_storage)
test_pandas_dtype_string_dtype_alias_with_storage ()
Variables
dict dtypes
list integer_dtypes = []
list signed_integer_dtypes = []
list unsigned_integer_dtypes = []
Function Documentation
get_is_dtype_funcs()
pandas.tests.dtypes.test_common.get_is_dtype_funcs ()
Get all functions in pandas.core.dtypes.common that
begin with 'is_' and end with 'dtype'
Definition at line 158 of file test_common.py.
References to_ea_dtypes(), and to_numpy_dtypes().
test__is_dtype_type()
pandas.tests.dtypes.test_common.test__is_dtype_type (input_param, result)
Definition at line 757 of file test_common.py.
test_astype_nansafe_copy_false()
pandas.tests.dtypes.test_common.test_astype_nansafe_copy_false (any_int_numpy_dtype)
Definition at line 761 of file test_common.py.
test_astype_object_preserves_datetime_na()
pandas.tests.dtypes.test_common.test_astype_object_preserves_datetime_na (from_type)
Definition at line 773 of file test_common.py.
test_custom_ea_kind_M_not_datetime64tz()
pandas.tests.dtypes.test_common.test_custom_ea_kind_M_not_datetime64tz ()
Definition at line 244 of file test_common.py.
test_dtype_equal()
pandas.tests.dtypes.test_common.test_dtype_equal (name1, dtype1, name2, dtype2)
Definition at line 126 of file test_common.py.
test_dtype_equal_strict()
pandas.tests.dtypes.test_common.test_dtype_equal_strict (dtype1, dtype2)
Definition at line 154 of file test_common.py.
test_get_dtype()
pandas.tests.dtypes.test_common.test_get_dtype (input_param, result)
Definition at line 701 of file test_common.py.
test_get_dtype_error_catch()
pandas.tests.dtypes.test_common.test_get_dtype_error_catch (func)
Definition at line 173 of file test_common.py.
test_get_dtype_fails()
pandas.tests.dtypes.test_common.test_get_dtype_fails (input_param, expected_error_message)
Definition at line 716 of file test_common.py.
test_is_any_real_numeric_dtype()
pandas.tests.dtypes.test_common.test_is_any_real_numeric_dtype ()
Definition at line 589 of file test_common.py.
test_is_bool_dtype()
pandas.tests.dtypes.test_common.test_is_bool_dtype ()
Definition at line 613 of file test_common.py.
test_is_bool_dtype_numpy_error()
pandas.tests.dtypes.test_common.test_is_bool_dtype_numpy_error ()
Definition at line 633 of file test_common.py.
test_is_categorical_dtype()
pandas.tests.dtypes.test_common.test_is_categorical_dtype ()
Definition at line 297 of file test_common.py.
test_is_complex_dtype()
pandas.tests.dtypes.test_common.test_is_complex_dtype ()
Definition at line 662 of file test_common.py.
test_is_datetime64_any_dtype()
pandas.tests.dtypes.test_common.test_is_datetime64_any_dtype ()
Definition at line 491 of file test_common.py.
test_is_datetime64_dtype()
pandas.tests.dtypes.test_common.test_is_datetime64_dtype ()
Definition at line 226 of file test_common.py.
test_is_datetime64_ns_dtype()
pandas.tests.dtypes.test_common.test_is_datetime64_ns_dtype ()
Definition at line 505 of file test_common.py.
test_is_datetime64tz_dtype()
pandas.tests.dtypes.test_common.test_is_datetime64tz_dtype ()
Definition at line 235 of file test_common.py.
test_is_extension_array_dtype()
pandas.tests.dtypes.test_common.test_is_extension_array_dtype (check_scipy)
Definition at line 641 of file test_common.py.
test_is_float_dtype()
pandas.tests.dtypes.test_common.test_is_float_dtype ()
Definition at line 603 of file test_common.py.
test_is_int64_dtype()
pandas.tests.dtypes.test_common.test_is_int64_dtype (dtype)
Definition at line 447 of file test_common.py.
test_is_integer_dtype()
pandas.tests.dtypes.test_common.test_is_integer_dtype (dtype)
Definition at line 352 of file test_common.py.
test_is_interval_dtype()
pandas.tests.dtypes.test_common.test_is_interval_dtype ()
Definition at line 284 of file test_common.py.
test_is_not_int64_dtype()
pandas.tests.dtypes.test_common.test_is_not_int64_dtype (dtype)
Definition at line 485 of file test_common.py.
test_is_not_integer_dtype()
pandas.tests.dtypes.test_common.test_is_not_integer_dtype (dtype)
Definition at line 368 of file test_common.py.
test_is_not_signed_integer_dtype()
pandas.tests.dtypes.test_common.test_is_not_signed_integer_dtype (dtype)
Definition at line 404 of file test_common.py.
test_is_not_unsigned_integer_dtype()
pandas.tests.dtypes.test_common.test_is_not_unsigned_integer_dtype (dtype)
Definition at line 440 of file test_common.py.
test_is_numeric_dtype()
pandas.tests.dtypes.test_common.test_is_numeric_dtype ()
Definition at line 557 of file test_common.py.
test_is_numeric_v_string_like()
pandas.tests.dtypes.test_common.test_is_numeric_v_string_like ()
Definition at line 533 of file test_common.py.
test_is_object()
pandas.tests.dtypes.test_common.test_is_object ()
Definition at line 193 of file test_common.py.
test_is_period_dtype()
pandas.tests.dtypes.test_common.test_is_period_dtype ()
Definition at line 273 of file test_common.py.
test_is_scipy_sparse()
pandas.tests.dtypes.test_common.test_is_scipy_sparse ()
Definition at line 218 of file test_common.py.
test_is_signed_integer_dtype()
pandas.tests.dtypes.test_common.test_is_signed_integer_dtype (dtype)
Definition at line 384 of file test_common.py.
test_is_sparse()
pandas.tests.dtypes.test_common.test_is_sparse (check_scipy)
Definition at line 205 of file test_common.py.
test_is_string_dtype()
pandas.tests.dtypes.test_common.test_is_string_dtype (dtype, expected)
Definition at line 320 of file test_common.py.
test_is_string_dtype_arraylike_with_object_elements_not_strings()
pandas.tests.dtypes.test_common.test_is_string_dtype_arraylike_with_object_elements_not_strings (data)
Definition at line 331 of file test_common.py.
test_is_string_dtype_nullable()
pandas.tests.dtypes.test_common.test_is_string_dtype_nullable (nullable_string_dtype)
Definition at line 336 of file test_common.py.
test_is_timedelta64_dtype()
pandas.tests.dtypes.test_common.test_is_timedelta64_dtype ()
Definition at line 258 of file test_common.py.
test_is_timedelta64_ns_dtype()
pandas.tests.dtypes.test_common.test_is_timedelta64_ns_dtype ()
Definition at line 525 of file test_common.py.
test_is_unsigned_integer_dtype()
pandas.tests.dtypes.test_common.test_is_unsigned_integer_dtype (dtype)
Definition at line 420 of file test_common.py.
test_needs_i8_conversion()
pandas.tests.dtypes.test_common.test_needs_i8_conversion ()
Definition at line 543 of file test_common.py.
test_pandas_dtype_ea_not_instance()
pandas.tests.dtypes.test_common.test_pandas_dtype_ea_not_instance ()
Definition at line 807 of file test_common.py.
test_pandas_dtype_numpy_warning()
pandas.tests.dtypes.test_common.test_pandas_dtype_numpy_warning ()
Definition at line 790 of file test_common.py.
test_pandas_dtype_string_dtype_alias_with_storage()
pandas.tests.dtypes.test_common.test_pandas_dtype_string_dtype_alias_with_storage ()
Definition at line 848 of file test_common.py.
test_pandas_dtype_string_dtypes()
pandas.tests.dtypes.test_common.test_pandas_dtype_string_dtypes (string_storage)
Definition at line 813 of file test_common.py.
test_pyarrow_string_import_error()
pandas.tests.dtypes.test_common.test_pyarrow_string_import_error (name, dtype)
Definition at line 134 of file test_common.py.
test_type_comparison_with_numeric_ea_dtype()
pandas.tests.dtypes.test_common.test_type_comparison_with_numeric_ea_dtype (any_numeric_ea_dtype)
Definition at line 453 of file test_common.py.
test_type_comparison_with_real_numpy_dtype()
pandas.tests.dtypes.test_common.test_type_comparison_with_real_numpy_dtype (any_real_numpy_dtype)
Definition at line 458 of file test_common.py.
test_type_comparison_with_signed_int_ea_dtype_and_signed_int_numpy_dtype()
pandas.tests.dtypes.test_common.test_type_comparison_with_signed_int_ea_dtype_and_signed_int_numpy_dtype (any_signed_int_ea_dtype, any_signed_int_numpy_dtype)
Definition at line 463 of file test_common.py.
test_validate_allhashable()
pandas.tests.dtypes.test_common.test_validate_allhashable ()
Definition at line 780 of file test_common.py.
to_ea_dtypes()
pandas.tests.dtypes.test_common.to_ea_dtypes (dtypes)
convert list of string dtypes to EA dtype
Definition at line 29 of file test_common.py.
Referenced by get_is_dtype_funcs().
to_numpy_dtypes()
pandas.tests.dtypes.test_common.to_numpy_dtypes (dtypes)
convert list of string dtypes to numpy dtype
Definition at line 34 of file test_common.py.
Referenced by get_is_dtype_funcs().
Variable Documentation
dtypes
dict pandas.tests.dtypes.test_common.dtypes
Initial value:
=  {
    "datetime_tz": com.pandas_dtype("datetime64[ns, US/Eastern]"),
    "datetime": com.pandas_dtype("datetime64[ns]"),
    "timedelta": com.pandas_dtype("timedelta64[ns]"),
    "period": PeriodDtype("D"),
    "integer": np.dtype(np.int64),
    "float": np.dtype(np.float64),
    "object": np.dtype(object),
    "category": com.pandas_dtype("category"),
    "string": pd.StringDtype(),
}
Definition at line 111 of file test_common.py.
integer_dtypes
list pandas.tests.dtypes.test_common.integer_dtypes = []
Definition at line 340 of file test_common.py.
signed_integer_dtypes
list pandas.tests.dtypes.test_common.signed_integer_dtypes = []
Definition at line 372 of file test_common.py.
unsigned_integer_dtypes
list pandas.tests.dtypes.test_common.unsigned_integer_dtypes = []
Definition at line 408 of file test_common.py.