Code Cloning Analysis: matplotlib.projections.polar.ThetaTick Class Reference
matplotlib.projections.polar.ThetaTick Class Reference
Public Member Functions
__init__ (self, axes, *args, **kwargs)
update_position (self, loc)
Protected Member Functions
_apply_params (self, **kwargs)
_update_padding (self, pad, angle)
Protected Attributes
_text1_translate
_text2_translate
Detailed Description
A theta-axis tick.
This subclass of `.XTick` provides angular ticks with some small
modification to their re-positioning such that ticks are rotated based on
tick location. This results in ticks that are correctly perpendicular to
the arc spine.
When 'auto' rotation is enabled, labels are also rotated to be parallel to
the spine. The label padding is also applied here since it's not possible
to use a generic axes transform to produce tick-specific padding.
Definition at line 326 of file polar.py.
Constructor & Destructor Documentation
__init__()
matplotlib.projections.polar.ThetaTick.__init__ (self, axes, * args, ** kwargs)
Definition at line 340 of file polar.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_apply_params()
matplotlib.projections.polar.ThetaTick._apply_params (self, ** kwargs) protected
Definition at line 353 of file polar.py.
_update_padding()
matplotlib.projections.polar.ThetaTick._update_padding (self, pad, angle) protected
Definition at line 363 of file polar.py.
update_position()
matplotlib.projections.polar.ThetaTick.update_position (self, loc)
Definition at line 371 of file polar.py.
Member Data Documentation
_text1_translate
matplotlib.projections.polar.ThetaTick._text1_translate protected
Initial value:
=  mtransforms.ScaledTranslation(
            0, 0, axes.get_figure(root=False).dpi_scale_trans)
Definition at line 341 of file polar.py.
_text2_translate
matplotlib.projections.polar.ThetaTick._text2_translate protected
Initial value:
=  mtransforms.ScaledTranslation(
            0, 0, axes.get_figure(root=False).dpi_scale_trans)
Definition at line 343 of file polar.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/projections/polar.py