Code Cloning Analysis: fontTools.varLib.instancer._TupleVarStoreAdapter Class Reference
fontTools.varLib.instancer._TupleVarStoreAdapter Class Reference
Public Member Functions
__init__ (self, regions, axisOrder, tupleVarData, itemCounts)
fromItemVarStore (cls, itemVarStore, fvarAxes)
rebuildRegions (self)
instantiate (self, axisLimits)
asItemVarStore (self)
Public Attributes
regions = regions
list axisOrder = axisOrder
tupleVarData = tupleVarData
itemCounts = itemCounts
Detailed Description
Definition at line 1161 of file __init__.py.
Constructor & Destructor Documentation
__init__()
fontTools.varLib.instancer._TupleVarStoreAdapter.__init__ (self, regions, axisOrder, tupleVarData, itemCounts)
Definition at line 1162 of file __init__.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
asItemVarStore()
fontTools.varLib.instancer._TupleVarStoreAdapter.asItemVarStore (self)
Definition at line 1225 of file __init__.py.
fromItemVarStore()
fontTools.varLib.instancer._TupleVarStoreAdapter.fromItemVarStore (cls, itemVarStore, fvarAxes)
Definition at line 1169 of file __init__.py.
instantiate()
fontTools.varLib.instancer._TupleVarStoreAdapter.instantiate (self, axisLimits)
Definition at line 1207 of file __init__.py.
rebuildRegions()
fontTools.varLib.instancer._TupleVarStoreAdapter.rebuildRegions (self)
Definition at line 1185 of file __init__.py.
Member Data Documentation
axisOrder
list fontTools.varLib.instancer._TupleVarStoreAdapter.axisOrder = axisOrder
Definition at line 1164 of file __init__.py.
Referenced by fontTools.varLib.models.VariationModel.getSubModel().
itemCounts
fontTools.varLib.instancer._TupleVarStoreAdapter.itemCounts = itemCounts
Definition at line 1166 of file __init__.py.
regions
fontTools.varLib.instancer._TupleVarStoreAdapter.regions = regions
Definition at line 1163 of file __init__.py.
Referenced by scipy.spatial._spherical_voronoi.SphericalVoronoi._calc_vertices_regions(), and scipy.spatial._spherical_voronoi.SphericalVoronoi.sort_vertices_of_regions().
tupleVarData
fontTools.varLib.instancer._TupleVarStoreAdapter.tupleVarData = tupleVarData
Definition at line 1165 of file __init__.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/varLib/instancer/__init__.py