Code Cloning Analysis: mplot3d.proj3d Namespace Reference
mplot3d.proj3d Namespace Reference
Functions
world_transformation (xmin, xmax, ymin, ymax, zmin, zmax, pb_aspect=None)
_rotation_about_vector (v, angle)
_view_axes (E, R, V, roll)
_view_transformation_uvw (u, v, w, E)
_persp_transformation (zfront, zback, focal_length)
_ortho_transformation (zfront, zback)
_proj_transform_vec (vec, M)
_proj_transform_vec_clip (vec, M, focal_length)
inv_transform (xs, ys, zs, invM)
_vec_pad_ones (xs, ys, zs)
proj_transform (xs, ys, zs, M)
proj_transform_clip (xs, ys, zs, M)
_proj_transform_clip (xs, ys, zs, M, focal_length)
_proj_points (points, M)
_proj_trans_points (points, M)
Detailed Description
Various transforms used for by the 3D code
Function Documentation
_ortho_transformation()
mplot3d.proj3d._ortho_transformation (zfront, zback) protected
Definition at line 123 of file proj3d.py.
_persp_transformation()
mplot3d.proj3d._persp_transformation (zfront, zback, focal_length) protected
Definition at line 111 of file proj3d.py.
_proj_points()
mplot3d.proj3d._proj_points (points, M) protected
Definition at line 212 of file proj3d.py.
_proj_trans_points()
mplot3d.proj3d._proj_trans_points (points, M) protected
Definition at line 216 of file proj3d.py.
_proj_transform_clip()
mplot3d.proj3d._proj_transform_clip (xs, ys, zs, M, focal_length) protected
Transform the points by the projection matrix
and return the clipping result
returns txs, tys, tzs, tis
Definition at line 202 of file proj3d.py.
References proj_transform().
Referenced by proj_transform().
_proj_transform_vec()
mplot3d.proj3d._proj_transform_vec (vec, M) protected
Definition at line 134 of file proj3d.py.
_proj_transform_vec_clip()
mplot3d.proj3d._proj_transform_vec_clip (vec, M, focal_length) protected
Definition at line 147 of file proj3d.py.
_rotation_about_vector()
mplot3d.proj3d._rotation_about_vector (v, angle) protected
Produce a rotation matrix for an angle in radians about a vector.
Definition at line 32 of file proj3d.py.
Referenced by _view_axes().
_vec_pad_ones()
mplot3d.proj3d._vec_pad_ones (xs, ys, zs) protected
Definition at line 182 of file proj3d.py.
_view_axes()
mplot3d.proj3d._view_axes (E, R, V, roll) protected
Get the unit viewing axes in data coordinates.
Parameters
----------
E : 3-element numpy array
    The coordinates of the eye/camera.
R : 3-element numpy array
    The coordinates of the center of the view box.
V : 3-element numpy array
    Unit vector in the direction of the vertical axis.
roll : float
    The roll angle in radians.
Returns
-------
u : 3-element numpy array
    Unit vector pointing towards the right of the screen.
v : 3-element numpy array
    Unit vector pointing towards the top of the screen.
w : 3-element numpy array
    Unit vector pointing out of the screen.
Definition at line 49 of file proj3d.py.
References _rotation_about_vector().
_view_transformation_uvw()
mplot3d.proj3d._view_transformation_uvw (u, v, w, E) protected
Return the view transformation matrix.
Parameters
----------
u : 3-element numpy array
    Unit vector pointing towards the right of the screen.
v : 3-element numpy array
    Unit vector pointing towards the top of the screen.
w : 3-element numpy array
    Unit vector pointing out of the screen.
E : 3-element numpy array
    The coordinates of the eye/camera.
Definition at line 88 of file proj3d.py.
inv_transform()
mplot3d.proj3d.inv_transform (xs, ys, zs, invM)
Transform the points by the inverse of the projection matrix, *invM*.
Definition at line 168 of file proj3d.py.
proj_transform()
mplot3d.proj3d.proj_transform (xs, ys, zs, M)
Transform the points by the projection matrix *M*.
Definition at line 189 of file proj3d.py.
References _proj_transform_clip().
Referenced by _proj_transform_clip().
proj_transform_clip()
mplot3d.proj3d.proj_transform_clip (xs, ys, zs, M)
Definition at line 198 of file proj3d.py.
world_transformation()
mplot3d.proj3d.world_transformation (xmin, xmax, ymin, ymax, zmin, zmax, pb_aspect = None)
Produce a matrix that scales homogeneous coords in the specified ranges
to [0, 1], or [0, pb_aspect[i]] if the plotbox aspect ratio is specified.
Definition at line 10 of file proj3d.py.