Code Cloning Analysis: matplotlib.widgets.Lasso Class Reference
matplotlib.widgets.Lasso Class Reference
Public Member Functions
__init__ (self, ax, xy, callback, *, useblit=True, props=None)
onrelease (self, event)
onmove (self, event)
Public Member Functions inherited from matplotlib.widgets.AxesWidget
__init__ (self, ax)
connect_event (self, event, callback)
disconnect_events (self)
Public Member Functions inherited from matplotlib.widgets.Widget
set_active (self, active)
get_active (self)
ignore (self, event)
Public Attributes
useblit = useblit and self.canvas.supports_blit
background = self.canvas.copy_from_bbox(self.ax.bbox)
list verts = [(x, y)]
line = Line2D([x], [y], **style)
callback = callback
onrelease
onmove
Public Attributes inherited from matplotlib.widgets.AxesWidget
ax = ax
Additional Inherited Members
Static Public Attributes inherited from matplotlib.widgets.Widget
bool drawon = True
bool eventson = True
Protected Member Functions inherited from matplotlib.widgets.AxesWidget
_get_data_coords (self, event)
Protected Attributes inherited from matplotlib.widgets.AxesWidget
list _cids = []
Static Protected Attributes inherited from matplotlib.widgets.Widget
bool _active = True
Properties inherited from matplotlib.widgets.AxesWidget
canvas = property(lambda self: self.ax.get_figure(root=True).canvas)
Properties inherited from matplotlib.widgets.Widget
active = property(get_active, set_active, doc="Is the widget active?")
Detailed Description
Selection curve of an arbitrary shape.
The selected path can be used in conjunction with
`~matplotlib.path.Path.contains_point` to select data points from an image.
Unlike `LassoSelector`, this must be initialized with a starting
point *xy*, and the `Lasso` events are destroyed upon release.
Parameters
----------
ax : `~matplotlib.axes.Axes`
    The parent Axes for the widget.
xy : (float, float)
    Coordinates of the start of the lasso.
callback : callable
    Whenever the lasso is released, the *callback* function is called and
    passed the vertices of the selected path.
useblit : bool, default: True
    Whether to use blitting for faster drawing (if supported by the
    backend). See the tutorial :ref:`blitting`
    for details.
props: dict, optional
    Lasso line properties. See `.Line2D` for valid properties.
    Default *props* are::
        {'linestyle' : '-', 'color' : 'black', 'lw' : 2}
    .. versionadded:: 3.9
Definition at line 4099 of file widgets.py.
Constructor & Destructor Documentation
__init__()
matplotlib.widgets.Lasso.__init__ (self, ax, xy, callback, * , useblit = True, props = None)
Definition at line 4130 of file widgets.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
onmove()
matplotlib.widgets.Lasso.onmove (self, event)
Definition at line 4161 of file widgets.py.
onrelease()
matplotlib.widgets.Lasso.onrelease (self, event)
Definition at line 4150 of file widgets.py.
Member Data Documentation
background
matplotlib.widgets.Lasso.background = self.canvas.copy_from_bbox(self.ax.bbox)
Definition at line 4135 of file widgets.py.
callback
matplotlib.widgets.Lasso.callback = callback
Definition at line 4146 of file widgets.py.
Referenced by sklearn.neighbors._nca.NeighborhoodComponentsAnalysis._callback(), sklearn.decomposition._sparse_pca.MiniBatchSparsePCA._fit(), sklearn.decomposition._dict_learning.MiniBatchDictionaryLearning.fit(), sklearn.decomposition._dict_learning.DictionaryLearning.fit_transform(), scipy.optimize._shgo.SHGO.minimize(), scipy.optimize._dual_annealing.EnergyState.reset(), and scipy.optimize._differentialevolution.DifferentialEvolutionSolver.solve().
line
matplotlib.widgets.Lasso.line = Line2D([x], [y], **style)
Definition at line 4144 of file widgets.py.
Referenced by axisartist.axis_artist.AxisArtist._get_tick_info(), axisartist.axis_artist.AxisArtist._init_line(), mplot3d.axis3d.Axis.draw_pane(), PIL.ImageDraw.ImageDraw.line(), pip._vendor.pyparsing.exceptions.ParseBaseException.mark_input_line(), and pyparsing.exceptions.ParseBaseException.mark_input_line().
onmove
matplotlib.widgets.Lasso.onmove
Definition at line 4148 of file widgets.py.
Referenced by matplotlib.widgets.MultiCursor.connect().
onrelease
matplotlib.widgets.Lasso.onrelease
Definition at line 4147 of file widgets.py.
useblit
matplotlib.widgets.Lasso.useblit = useblit and self.canvas.supports_blit
Definition at line 4133 of file widgets.py.
verts
matplotlib.widgets.Lasso.verts = [(x, y)]
Definition at line 4143 of file widgets.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/widgets.py