Code Cloning Analysis: pandas.core.ops.missing Namespace Reference
pandas.core.ops.missing Namespace Reference
Functions
_fill_zeros (np.ndarray result, x, y)
np.ndarray mask_zero_div_zero (x, y, np.ndarray result)
dispatch_fill_zeros (op, left, right, result)
Detailed Description
Missing data handling for arithmetic operations.
In particular, pandas conventions regarding division by zero differ
from numpy in the following ways:
    1) np.array([-1, 0, 1], dtype=dtype1) // np.array([0, 0, 0], dtype=dtype2)
       gives [nan, nan, nan] for most dtype combinations, and [0, 0, 0] for
       the remaining pairs
       (the remaining being dtype1==dtype2==intN and dtype==dtype2==uintN).
       pandas convention is to return [-inf, nan, inf] for all dtype
       combinations.
       Note: the numpy behavior described here is py3-specific.
    2) np.array([-1, 0, 1], dtype=dtype1) % np.array([0, 0, 0], dtype=dtype2)
       gives precisely the same results as the // operation.
       pandas convention is to return [nan, nan, nan] for all dtype
       combinations.
    3) divmod behavior consistent with 1) and 2).
Function Documentation
_fill_zeros()
pandas.core.ops.missing._fill_zeros (np.ndarray result, x, y) protected
If this is a reversed op, then flip x,y
If we have an integer value (or array in y)
and we have 0's, fill them with np.nan,
return the result.
Mask the nan's from x.
Definition at line 33 of file missing.py.
Referenced by dispatch_fill_zeros().
dispatch_fill_zeros()
pandas.core.ops.missing.dispatch_fill_zeros (op, left, right, result)
Call _fill_zeros with the appropriate fill value depending on the operation,
with special logic for divmod and rdivmod.
Parameters
----------
op : function (operator.add, operator.div, ...)
left : object (np.ndarray for non-reversed ops)
    We have excluded ExtensionArrays here
right : object (np.ndarray for reversed ops)
    We have excluded ExtensionArrays here
result : ndarray
Returns
-------
result : np.ndarray
Notes
-----
For divmod and rdivmod, the `result` parameter and returned `result`
is a 2-tuple of ndarray objects.
Definition at line 131 of file missing.py.
References _fill_zeros(), and mask_zero_div_zero().
mask_zero_div_zero()
np.ndarray pandas.core.ops.missing.mask_zero_div_zero (x, y, np.ndarray result)
Set results of  0 // 0 to np.nan, regardless of the dtypes
of the numerator or the denominator.
Parameters
----------
x : ndarray
y : ndarray
result : ndarray
Returns
-------
ndarray
    The filled result.
Examples
--------
>>> x = np.array([1, 0, -1], dtype=np.int64)
>>> x
array([ 1,  0, -1])
>>> y = 0       # int 0; numpy behavior is different with float
>>> result = x // y
>>> result      # raw numpy result does not fill division by zero
array([0, 0, 0])
>>> mask_zero_div_zero(x, y, result)
array([ inf,  nan, -inf])
Definition at line 71 of file missing.py.
Referenced by dispatch_fill_zeros().