Code Cloning Analysis: matplotlib._type1font._BinaryToken Class Reference
matplotlib._type1font._BinaryToken Class Reference
Public Member Functions
value (self)
Public Member Functions inherited from matplotlib._type1font._Token
__init__ (self, pos, raw)
__str__ (self)
endpos (self)
is_keyword (self, *names)
is_slash_name (self)
is_delim (self)
is_number (self)
Additional Inherited Members
Public Attributes inherited from matplotlib._type1font._Token
pos = pos
raw = raw
Static Public Attributes inherited from matplotlib._type1font._Token
str kind = '?'
Detailed Description
Definition at line 157 of file _type1font.py.
Member Function Documentation
value()
matplotlib._type1font._BinaryToken.value (self)
Reimplemented from matplotlib._type1font._Token.
Definition at line 160 of file _type1font.py.
Referenced by sklearn.externals.array_api_extra._lib._at._AtOp.__str__(), pip._internal.models.link.LinkHash.as_hashes(), pip._internal.models.link.LinkHash.find_hash_url_fragment(), and pip._internal.models.link.LinkHash.is_hash_allowed().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/_type1font.py