Code Cloning Analysis: sklearn.utils._indexing Namespace Reference
sklearn.utils._indexing Namespace Reference
Functions
_array_indexing (array, key, key_dtype, axis)
_pandas_indexing (X, key, key_dtype, axis)
_list_indexing (X, key, key_dtype)
_polars_indexing (X, key, key_dtype, axis)
_pyarrow_indexing (X, key, key_dtype, axis)
_determine_key_type (key, accept_slice=True)
_safe_indexing (X, indices, *, axis=0)
_safe_assign (X, values, *, row_indexer=None, column_indexer=None)
_get_column_indices_for_bool_or_int (key, n_columns)
_get_column_indices (X, key)
_get_column_indices_interchange (X_interchange, key, key_dtype)
resample (*arrays, replace=True, n_samples=None, random_state=None, stratify=None, sample_weight=None)
shuffle (*arrays, random_state=None, n_samples=None)
Function Documentation
_array_indexing()
sklearn.utils._indexing._array_indexing (array, key, key_dtype, axis) protected
Index an array or scipy.sparse consistently across NumPy version.
Definition at line 31 of file _indexing.py.
Referenced by _safe_indexing().
_determine_key_type()
sklearn.utils._indexing._determine_key_type (key, accept_slice = True) protected
Determine the data type of key.
Parameters
----------
key : scalar, slice or array-like
    The key from which we want to infer the data type.
accept_slice : bool, default=True
    Whether or not to raise an error if the key is a slice.
Returns
-------
dtype : {'int', 'str', 'bool', None}
    Returns the data type of key.
Definition at line 158 of file _indexing.py.
References _determine_key_type().
Referenced by _determine_key_type(), _get_column_indices(), and _safe_indexing().
_get_column_indices()
sklearn.utils._indexing._get_column_indices (X, key) protected
Get feature column indices for input data X and key.
For accepted values of `key`, see the docstring of
:func:`_safe_indexing`.
Definition at line 402 of file _indexing.py.
References _determine_key_type(), and _get_column_indices_interchange().
_get_column_indices_for_bool_or_int()
sklearn.utils._indexing._get_column_indices_for_bool_or_int (key, n_columns) protected
Definition at line 391 of file _indexing.py.
_get_column_indices_interchange()
sklearn.utils._indexing._get_column_indices_interchange (X_interchange, key, key_dtype) protected
Same as _get_column_indices but for X with __dataframe__ protocol.
Definition at line 456 of file _indexing.py.
Referenced by _get_column_indices().
_list_indexing()
sklearn.utils._indexing._list_indexing (X, key, key_dtype) protected
Index a Python list.
Definition at line 58 of file _indexing.py.
Referenced by _safe_indexing().
_pandas_indexing()
sklearn.utils._indexing._pandas_indexing (X, key, key_dtype, axis) protected
Index a pandas dataframe or a series.
Definition at line 43 of file _indexing.py.
Referenced by _safe_indexing().
_polars_indexing()
sklearn.utils._indexing._polars_indexing (X, key, key_dtype, axis) protected
Index a polars dataframe or series.
Definition at line 70 of file _indexing.py.
Referenced by _safe_indexing().
_pyarrow_indexing()
sklearn.utils._indexing._pyarrow_indexing (X, key, key_dtype, axis) protected
Index a pyarrow data.
Definition at line 99 of file _indexing.py.
Referenced by _safe_indexing().
_safe_assign()
sklearn.utils._indexing._safe_assign (X, values, * , row_indexer = None, column_indexer = None) protected
Safe assignment to a numpy array, sparse matrix, or pandas dataframe.
Parameters
----------
X : {ndarray, sparse-matrix, dataframe}
    Array to be modified. It is expected to be 2-dimensional.
values : ndarray
    The values to be assigned to `X`.
row_indexer : array-like, dtype={int, bool}, default=None
    A 1-dimensional array to select the rows of interest. If `None`, all
    rows are selected.
column_indexer : array-like, dtype={int, bool}, default=None
    A 1-dimensional array to select the columns of interest. If `None`, all
    columns are selected.
Definition at line 354 of file _indexing.py.
References _safe_indexing().
_safe_indexing()
sklearn.utils._indexing._safe_indexing (X, indices, * , axis = 0) protected
Return rows, items or columns of X using indices.
.. warning::
    This utility is documented, but **private**. This means that
    backward compatibility might be broken without any deprecation
    cycle.
Parameters
----------
X : array-like, sparse-matrix, list, pandas.DataFrame, pandas.Series
    Data from which to sample rows, items or columns. `list` are only
    supported when `axis=0`.
indices : bool, int, str, slice, array-like
    - If `axis=0`, boolean and integer array-like, integer slice,
      and scalar integer are supported.
    - If `axis=1`:
        - to select a single column, `indices` can be of `int` type for
          all `X` types and `str` only for dataframe. The selected subset
          will be 1D, unless `X` is a sparse matrix in which case it will
          be 2D.
        - to select multiples columns, `indices` can be one of the
          following: `list`, `array`, `slice`. The type used in
          these containers can be one of the following: `int`, 'bool' and
          `str`. However, `str` is only supported when `X` is a dataframe.
          The selected subset will be 2D.
axis : int, default=0
    The axis along which `X` will be subsampled. `axis=0` will select
    rows while `axis=1` will select columns.
Returns
-------
subset
    Subset of X on axis 0 or 1.
Notes
-----
CSR, CSC, and LIL sparse matrices are supported. COO sparse matrices are
not supported.
Examples
--------
>>> import numpy as np
>>> from sklearn.utils import _safe_indexing
>>> data = np.array([[1, 2], [3, 4], [5, 6]])
>>> _safe_indexing(data, 0, axis=0)  # select the first row
array([1, 2])
>>> _safe_indexing(data, 0, axis=1)  # select the first column
array([1, 3, 5])
Definition at line 242 of file _indexing.py.
References _array_indexing(), _determine_key_type(), _list_indexing(), _pandas_indexing(), _polars_indexing(), and _pyarrow_indexing().
Referenced by _safe_assign(), and resample().
resample()
sklearn.utils._indexing.resample (* arrays, replace = True, n_samples = None, random_state = None, stratify = None, sample_weight = None)
Resample arrays or sparse matrices in a consistent way.
The default strategy implements one step of the bootstrapping
procedure.
Parameters
----------
*arrays : sequence of array-like of shape (n_samples,) or \
        (n_samples, n_outputs)
    Indexable data-structures can be arrays, lists, dataframes or scipy
    sparse matrices with consistent first dimension.
replace : bool, default=True
    Implements resampling with replacement. It must be set to True
    whenever sampling with non-uniform weights: a few data points with very large
    weights are expected to be sampled several times with probability to preserve
    the distribution induced by the weights. If False, this will implement
    (sliced) random permutations.
n_samples : int, default=None
    Number of samples to generate. If left to None this is
    automatically set to the first dimension of the arrays.
    If replace is False it should not be larger than the length of
    arrays.
random_state : int, RandomState instance or None, default=None
    Determines random number generation for shuffling
    the data.
    Pass an int for reproducible results across multiple function calls.
    See :term:`Glossary <random_state>`.
stratify : {array-like, sparse matrix} of shape (n_samples,) or \
        (n_samples, n_outputs), default=None
    If not None, data is split in a stratified fashion, using this as
    the class labels.
sample_weight : array-like of shape (n_samples,), default=None
    Contains weight values to be associated with each sample. Values are
    normalized to sum to one and interpreted as probability for sampling
    each data point.
    .. versionadded:: 1.7
Returns
-------
resampled_arrays : sequence of array-like of shape (n_samples,) or \
        (n_samples, n_outputs)
    Sequence of resampled copies of the collections. The original arrays
    are not impacted.
See Also
--------
shuffle : Shuffle arrays or sparse matrices in a consistent way.
Examples
--------
It is possible to mix sparse and dense arrays in the same run::
  >>> import numpy as np
  >>> X = np.array([[1., 0.], [2., 1.], [0., 0.]])
  >>> y = np.array([0, 1, 2])
  >>> from scipy.sparse import coo_matrix
  >>> X_sparse = coo_matrix(X)
  >>> from sklearn.utils import resample
  >>> X, X_sparse, y = resample(X, X_sparse, y, random_state=0)
  >>> X
  array([[1., 0.],
         [2., 1.],
         [1., 0.]])
  >>> X_sparse
  <Compressed Sparse Row sparse matrix of dtype 'float64'
      with 4 stored elements and shape (3, 2)>
  >>> X_sparse.toarray()
  array([[1., 0.],
         [2., 1.],
         [1., 0.]])
  >>> y
  array([0, 1, 0])
  >>> resample(y, n_samples=2, random_state=0)
  array([0, 1])
Example using stratification::
  >>> y = [0, 0, 1, 1, 1, 1, 1, 1, 1]
  >>> resample(y, n_samples=5, replace=False, stratify=y,
  ...          random_state=0)
  [1, 1, 1, 0, 1]
Definition at line 500 of file _indexing.py.
References _safe_indexing().
Referenced by shuffle().
shuffle()
sklearn.utils._indexing.shuffle (* arrays, random_state = None, n_samples = None)
Shuffle arrays or sparse matrices in a consistent way.
This is a convenience alias to ``resample(*arrays, replace=False)`` to do
random permutations of the collections.
Parameters
----------
*arrays : sequence of indexable data-structures
    Indexable data-structures can be arrays, lists, dataframes or scipy
    sparse matrices with consistent first dimension.
random_state : int, RandomState instance or None, default=None
    Determines random number generation for shuffling
    the data.
    Pass an int for reproducible results across multiple function calls.
    See :term:`Glossary <random_state>`.
n_samples : int, default=None
    Number of samples to generate. If left to None this is
    automatically set to the first dimension of the arrays.  It should
    not be larger than the length of arrays.
Returns
-------
shuffled_arrays : sequence of indexable data-structures
    Sequence of shuffled copies of the collections. The original arrays
    are not impacted.
See Also
--------
resample : Resample arrays or sparse matrices in a consistent way.
Examples
--------
It is possible to mix sparse and dense arrays in the same run::
  >>> import numpy as np
  >>> X = np.array([[1., 0.], [2., 1.], [0., 0.]])
  >>> y = np.array([0, 1, 2])
  >>> from scipy.sparse import coo_matrix
  >>> X_sparse = coo_matrix(X)
  >>> from sklearn.utils import shuffle
  >>> X, X_sparse, y = shuffle(X, X_sparse, y, random_state=0)
  >>> X
  array([[0., 0.],
         [2., 1.],
         [1., 0.]])
  >>> X_sparse
  <Compressed Sparse Row sparse matrix of dtype 'float64'
      with 3 stored elements and shape (3, 2)>
  >>> X_sparse.toarray()
  array([[0., 0.],
         [2., 1.],
         [1., 0.]])
  >>> y
  array([2, 1, 0])
  >>> shuffle(y, n_samples=2, random_state=0)
  array([0, 1])
Definition at line 687 of file _indexing.py.
References resample().