Code Cloning Analysis: fontTools.agl Namespace Reference
fontTools.agl Namespace Reference
Classes
class AGLError
Functions
_builddicts ()
toUnicode (glyph, isZapfDingbats=False)
_glyphComponentToUnicode (component, isZapfDingbats)
_zapfDingbatsToUnicode (glyph)
_uniToUnicode (component)
_uToUnicode (component)
Variables
str _aglText
str _aglfnText
dict LEGACY_AGL2UV = {}
dict AGL2UV = {}
dict UV2AGL = {}
tuple _AGL_ZAPF_DINGBATS
_re_uni = re.compile("^uni([0-9A-F]+)$")
_re_u = re.compile("^u([0-9A-F]{4,6})$")
Detailed Description
Interface to the Adobe Glyph List
This module exists to convert glyph names from the Adobe Glyph List
to their Unicode equivalents. Example usage:
    >>> from fontTools.agl import toUnicode
    >>> toUnicode("nahiragana")
    'な'
It also contains two dictionaries, ``UV2AGL`` and ``AGL2UV``, which map from
Unicode codepoints to AGL names and vice versa:
    >>> import fontTools
    >>> fontTools.agl.UV2AGL[ord("?")]
    'question'
    >>> fontTools.agl.AGL2UV["wcircumflex"]
    373
This is used by fontTools when it has to construct glyph names for a font which
doesn't include any (e.g. format 3.0 post tables).
Function Documentation
_builddicts()
fontTools.agl._builddicts () protected
Definition at line 5070 of file agl.py.
_glyphComponentToUnicode()
fontTools.agl._glyphComponentToUnicode (component, isZapfDingbats) protected
Definition at line 5133 of file agl.py.
_uniToUnicode()
fontTools.agl._uniToUnicode (component) protected
Helper for toUnicode() to handle "uniABCD" components.
Definition at line 5203 of file agl.py.
Referenced by toUnicode().
_uToUnicode()
fontTools.agl._uToUnicode (component) protected
Helper for toUnicode() to handle "u1ABCD" components.
Definition at line 5221 of file agl.py.
Referenced by toUnicode().
_zapfDingbatsToUnicode()
fontTools.agl._zapfDingbatsToUnicode (glyph) protected
Helper for toUnicode().
Definition at line 5186 of file agl.py.
Referenced by toUnicode().
toUnicode()
fontTools.agl.toUnicode (glyph, isZapfDingbats = False)
Convert glyph names to Unicode, such as ``'longs_t.oldstyle'`` --> ``u'ſt'``
If ``isZapfDingbats`` is ``True``, the implementation recognizes additional
glyph names (as required by the AGL specification).
Definition at line 5110 of file agl.py.
References _uniToUnicode(), _uToUnicode(), and _zapfDingbatsToUnicode().
Variable Documentation
_AGL_ZAPF_DINGBATS
tuple fontTools.agl._AGL_ZAPF_DINGBATS protected
Initial value:
=  (
    " ✁✂✄☎✆✝✞✟✠✡☛☞✌✍✎✏✑✒✓✔✕✖✗✘✙✚✛✜✢✣✤✥✦✧★✩✪✫✬✭✮✯✰✱✲✳✴✵✶✷✸✹✺✻✼✽✾✿❀"
    "❁❂❃❄❅❆❇❈❉❊❋●❍■❏❑▲▼◆❖ ◗❘❙❚❯❱❲❳❨❩❬❭❪❫❴❵❛❜❝❞❡❢❣❤✐❥❦❧♠♥♦♣    ✉✈✇"
    "①②③④⑤⑥⑦⑧⑨⑩❶❷❸❹❺❻❼❽❾❿➀➁➂➃➄➅➆➇➈➉➊➋➌➍➎➏➐➑➒➓➔→➣↔"
    "↕➙➛➜➝➞➟➠➡➢➤➥➦➧➨➩➫➭➯➲➳➵➸➺➻➼➽➾➚➪➶➹➘➴➷➬➮➱✃❐❒❮❰"
)
Definition at line 5178 of file agl.py.
_aglfnText
str fontTools.agl._aglfnText protected
Definition at line 4362 of file agl.py.
_aglText
str fontTools.agl._aglText protected
Definition at line 33 of file agl.py.
_re_u
fontTools.agl._re_u = re.compile("^u([0-9A-F]{4,6})$") protected
Definition at line 5218 of file agl.py.
_re_uni
fontTools.agl._re_uni = re.compile("^uni([0-9A-F]+)$") protected
Definition at line 5200 of file agl.py.
AGL2UV
dict fontTools.agl.AGL2UV = {}
Definition at line 5066 of file agl.py.
LEGACY_AGL2UV
dict fontTools.agl.LEGACY_AGL2UV = {}
Definition at line 5065 of file agl.py.
UV2AGL
dict fontTools.agl.UV2AGL = {}
Definition at line 5067 of file agl.py.