Code Cloning Analysis: pandas.core.internals.blocks Namespace Reference
pandas.core.internals.blocks Namespace Reference
Classes
class Block
class DatetimeLikeBlock
class DatetimeTZBlock
class EABackedBlock
class ExtensionBlock
class NDArrayBackedExtensionBlock
class NumericBlock
class NumpyBlock
class ObjectBlock
Functions
F maybe_split (F meth)
ArrayLike maybe_coerce_values (ArrayLike values)
type[Block] get_block_type (DtypeObj dtype)
new_block_2d (ArrayLike values, BlockPlacement placement, BlockValuesRefs|None refs=None)
Block new_block (values, BlockPlacement placement, *, int ndim, BlockValuesRefs|None refs=None)
None check_ndim (values, BlockPlacement placement, int ndim)
tuple[ArrayLike, DtypeObj|None] extract_pandas_array (ArrayLike values, DtypeObj|None dtype, int ndim)
list[Block] extend_blocks (result, blocks=None)
ArrayLike ensure_block_shape (ArrayLike values, int ndim=1)
ArrayLike external_values (ArrayLike values)
Variables
_dtype_obj = np.dtype("object")
str COW_WARNING_GENERAL_MSG
str COW_WARNING_SETITEM_MSG
int ndim = 1:
Function Documentation
check_ndim()
None pandas.core.internals.blocks.check_ndim (values, BlockPlacement placement, int ndim)
ndim inference and validation.
Validates that values.ndim and ndim are consistent.
Validates that len(values) and len(placement) are consistent.
Parameters
----------
values : array-like
placement : BlockPlacement
ndim : int
Raises
------
ValueError : the number of dimensions do not match
Definition at line 2804 of file blocks.py.
ensure_block_shape()
ArrayLike pandas.core.internals.blocks.ensure_block_shape (ArrayLike values, int ndim = 1)
Reshape if possible to have values.ndim == ndim.
Definition at line 2884 of file blocks.py.
Referenced by pandas.core.internals.blocks.Block.convert(), and pandas.core.internals.blocks.Block.make_block().
extend_blocks()
list[Block] pandas.core.internals.blocks.extend_blocks (result, blocks = None)
return a new extended blocks, given the result
Definition at line 2868 of file blocks.py.
Referenced by pandas.core.internals.blocks.Block.coerce_to_target_dtype().
external_values()
ArrayLike pandas.core.internals.blocks.external_values (ArrayLike values)
The array that Series.values returns (public attribute).
This has some historical constraints, and is overridden in block
subclasses to return the correct array (e.g. period returns
object ndarray and datetimetz a datetime64[ns] ndarray instead of
proper extension array).
Definition at line 2900 of file blocks.py.
extract_pandas_array()
tuple[ArrayLike, DtypeObj | None] pandas.core.internals.blocks.extract_pandas_array (ArrayLike values, DtypeObj | None dtype, int ndim)
Ensure that we don't allow NumpyExtensionArray / NumpyEADtype in internals.
Definition at line 2846 of file blocks.py.
get_block_type()
type[Block] pandas.core.internals.blocks.get_block_type (DtypeObj dtype)
Find the appropriate Block subclass to use for the given values and dtype.
Parameters
----------
dtype : numpy or pandas dtype
Returns
-------
cls : class, subclass of Block
Definition at line 2747 of file blocks.py.
maybe_coerce_values()
ArrayLike pandas.core.internals.blocks.maybe_coerce_values (ArrayLike values)
Input validation for values passed to __init__. Ensure that
any datetime64/timedelta64 dtypes are in nanoseconds.  Ensure
that we do not have string dtypes.
Parameters
----------
values : np.ndarray or ExtensionArray
Returns
-------
values : np.ndarray or ExtensionArray
Definition at line 2718 of file blocks.py.
Referenced by pandas.core.internals.blocks.Block._downcast_2d(), pandas.core.internals.blocks.Block.apply(), pandas.core.internals.blocks.Block.astype(), and pandas.core.internals.blocks.Block.convert().
maybe_split()
F pandas.core.internals.blocks.maybe_split (F meth)
If we have a multi-column block, split and operate block-wise.  Otherwise
use the original method.
Definition at line 166 of file blocks.py.
new_block()
Block pandas.core.internals.blocks.new_block (values, BlockPlacement placement, * , int ndim, BlockValuesRefs | None refs = None)
Definition at line 2789 of file blocks.py.
new_block_2d()
pandas.core.internals.blocks.new_block_2d (ArrayLike values, BlockPlacement placement, BlockValuesRefs | None refs = None)
Definition at line 2776 of file blocks.py.
Variable Documentation
_dtype_obj
pandas.core.internals.blocks._dtype_obj = np.dtype("object") protected
Definition at line 140 of file blocks.py.
COW_WARNING_GENERAL_MSG
str pandas.core.internals.blocks.COW_WARNING_GENERAL_MSG
Initial value:
=  """\
Setting a value on a view: behaviour will change in pandas 3.0.
You are mutating a Series or DataFrame object, and currently this mutation will
also have effect on other Series or DataFrame objects that share data with this
object. In pandas 3.0 (with Copy-on-Write), updating one Series or DataFrame object
will never modify another.
"""
Definition at line 143 of file blocks.py.
COW_WARNING_SETITEM_MSG
str pandas.core.internals.blocks.COW_WARNING_SETITEM_MSG
Initial value:
=  """\
Setting a value on a view: behaviour will change in pandas 3.0.
Currently, the mutation will also have effect on the object that shares data
with this object. For example, when setting a value in a Series that was
extracted from a column of a DataFrame, that DataFrame will also be updated:
    ser = df["col"]
    ser[0] = 0     <--- in pandas 2, this also updates `df`
In pandas 3.0 (with Copy-on-Write), updating one Series/DataFrame will never
modify another, and thus in the example above, `df` will not be changed.
"""
Definition at line 152 of file blocks.py.
ndim
int pandas.core.internals.blocks.ndim = 1:
Definition at line 174 of file blocks.py.