Code Cloning Analysis: pyparsing.helpers Namespace Reference
pyparsing.helpers Namespace Reference
Classes
class OpAssoc
Functions
ParserElement counted_array (ParserElement expr, typing.Optional[ParserElement] int_expr=None, *, typing.Optional[ParserElement] intExpr=None)
ParserElement match_previous_literal (ParserElement expr)
ParserElement match_previous_expr (ParserElement expr)
ParserElement one_of (Union[typing.Iterable[str], str] strs, bool caseless=False, bool use_regex=True, bool as_keyword=False, *, bool useRegex=True, bool asKeyword=False)
Dict dict_of (ParserElement key, ParserElement value)
ParserElement original_text_for (ParserElement expr, bool as_string=True, *, bool asString=True)
ParserElement ungroup (ParserElement expr)
ParserElement locatedExpr (ParserElement expr)
ParserElement nested_expr (Union[str, ParserElement] opener="(", Union[str, ParserElement] closer=")", typing.Optional[ParserElement] content=None, ParserElement ignore_expr=_NO_IGNORE_EXPR_GIVEN, *, ParserElement ignoreExpr=_NO_IGNORE_EXPR_GIVEN)
_makeTags (tagStr, xml, suppress_LT=Suppress("<"), suppress_GT=Suppress(">"))
tuple[ParserElement, ParserElement] make_html_tags (Union[str, ParserElement] tag_str)
tuple[ParserElement, ParserElement] make_xml_tags (Union[str, ParserElement] tag_str)
replace_html_entity (s, l, t)
Forward infix_notation (ParserElement base_expr, list[InfixNotationOperatorSpec] op_list, Union[str, ParserElement] lpar=Suppress("("), Union[str, ParserElement] rpar=Suppress(")"))
indentedBlock (blockStatementExpr, indentStack, indent=True, backup_stacks=[])
ParserElement delimited_list (Union[str, ParserElement] expr, Union[str, ParserElement] delim=",", bool combine=False, typing.Optional[int] min=None, typing.Optional[int] max=None, *, bool allow_trailing_delim=False)
Variables
_NO_IGNORE_EXPR_GIVEN = NoMatch()
ParserElement any_open_tag
any_close_tag
dict _htmlEntityMap = {k.rstrip(";"): v for k, v in html.entities.html5.items()}
str _most_common_entities
common_html_entity
InfixNotationOperatorArgType
InfixNotationOperatorSpec
c_style_comment = Regex(r"/\*(?:[^*]|\*(?!/))*\*\/").set_name("C style comment")
html_comment = Regex(r"<!--[\s\S]*?-->").set_name("HTML comment")
rest_of_line = Regex(r".*").leave_whitespace().set_name("rest of line")
dbl_slash_comment = Regex(r"//(?:\\\n|[^\n])*").set_name("// comment")
cpp_style_comment
java_style_comment = cpp_style_comment
python_style_comment = Regex(r"#.*").set_name("Python style comment")
list _builtin_exprs
opAssoc = OpAssoc
ParserElement anyOpenTag = any_open_tag
anyCloseTag = any_close_tag
commonHTMLEntity = common_html_entity
cStyleComment = c_style_comment
htmlComment = html_comment
restOfLine = rest_of_line
dblSlashComment = dbl_slash_comment
cppStyleComment = cpp_style_comment
javaStyleComment = java_style_comment
pythonStyleComment = python_style_comment
delimitedList = replaced_by_pep8("delimitedList", DelimitedList)
delimited_list = replaced_by_pep8("delimited_list", DelimitedList)
countedArray = replaced_by_pep8("countedArray", counted_array)
matchPreviousLiteral = replaced_by_pep8("matchPreviousLiteral", match_previous_literal)
matchPreviousExpr = replaced_by_pep8("matchPreviousExpr", match_previous_expr)
oneOf = replaced_by_pep8("oneOf", one_of)
dictOf = replaced_by_pep8("dictOf", dict_of)
originalTextFor = replaced_by_pep8("originalTextFor", original_text_for)
nestedExpr = replaced_by_pep8("nestedExpr", nested_expr)
makeHTMLTags = replaced_by_pep8("makeHTMLTags", make_html_tags)
makeXMLTags = replaced_by_pep8("makeXMLTags", make_xml_tags)
replaceHTMLEntity = replaced_by_pep8("replaceHTMLEntity", replace_html_entity)
infixNotation = replaced_by_pep8("infixNotation", infix_notation)
Function Documentation
_makeTags()
pyparsing.helpers._makeTags (tagStr, xml, suppress_LT = Suppress("<"), suppress_GT = Suppress(">")) protected
Internal helper to construct opening and closing tag expressions, given a tag name
Definition at line 576 of file helpers.py.
Referenced by make_html_tags(), and make_xml_tags().
counted_array()
ParserElement pyparsing.helpers.counted_array (ParserElement expr, typing.Optional[ParserElement] int_expr = None, * , typing.Optional[ParserElement] intExpr = None)
Helper to define a counted list of expressions.
This helper defines a pattern of the form::
    integer expr expr expr...
where the leading integer tells how many expr expressions follow.
The matched tokens returns the array of expr tokens as a list - the
leading count token is suppressed.
If ``int_expr`` is specified, it should be a pyparsing expression
that produces an integer value.
Example::
    counted_array(Word(alphas)).parse_string('2 ab cd ef')  # -> ['ab', 'cd']
    # in this parser, the leading integer value is given in binary,
    # '10' indicating that 2 values are in the array
    binary_constant = Word('01').set_parse_action(lambda t: int(t[0], 2))
    counted_array(Word(alphas), int_expr=binary_constant).parse_string('10 ab cd ef')  # -> ['ab', 'cd']
    # if other fields must be parsed after the count but before the
    # list items, give the fields results names and they will
    # be preserved in the returned ParseResults:
    count_with_metadata = integer + Word(alphas)("type")
    typed_array = counted_array(Word(alphanums), int_expr=count_with_metadata)("items")
    result = typed_array.parse_string("3 bool True True False")
    print(result.dump())
    # prints
    # ['True', 'True', 'False']
    # - items: ['True', 'True', 'False']
    # - type: 'bool'
Definition at line 22 of file helpers.py.
delimited_list()
ParserElement pyparsing.helpers.delimited_list (Union[str, ParserElement] expr, Union[str, ParserElement] delim = ",", bool combine = False, typing.Optional[int] min = None, typing.Optional[int] max = None, * , bool allow_trailing_delim = False)
(DEPRECATED - use :class:`DelimitedList` class)
Definition at line 1090 of file helpers.py.
dict_of()
Dict pyparsing.helpers.dict_of (ParserElement key, ParserElement value)
Helper to easily and clearly define a dictionary by specifying
the respective patterns for the key and value.  Takes care of
defining the :class:`Dict`, :class:`ZeroOrMore`, and
:class:`Group` tokens in the proper order.  The key pattern
can include delimiting markers or punctuation, as long as they are
suppressed, thereby leaving the significant key text.  The value
pattern can include named results, so that the :class:`Dict` results
can include named token fields.
Example::
    text = "shape: SQUARE posn: upper left color: light blue texture: burlap"
    attr_expr = (label + Suppress(':') + OneOrMore(data_word, stop_on=label).set_parse_action(' '.join))
    print(attr_expr[1, ...].parse_string(text).dump())
    attr_label = label
    attr_value = Suppress(':') + OneOrMore(data_word, stop_on=label).set_parse_action(' '.join)
    # similar to Dict, but simpler call format
    result = dict_of(attr_label, attr_value).parse_string(text)
    print(result.dump())
    print(result['shape'])
    print(result.shape)  # object attribute access works too
    print(result.as_dict())
prints::
    [['shape', 'SQUARE'], ['posn', 'upper left'], ['color', 'light blue'], ['texture', 'burlap']]
    - color: 'light blue'
    - posn: 'upper left'
    - shape: 'SQUARE'
    - texture: 'burlap'
    SQUARE
    SQUARE
    {'color': 'light blue', 'shape': 'SQUARE', 'posn': 'upper left', 'texture': 'burlap'}
Definition at line 286 of file helpers.py.
indentedBlock()
pyparsing.helpers.indentedBlock (blockStatementExpr, indentStack, indent = True, backup_stacks = [])
(DEPRECATED - use :class:`IndentedBlock` class instead)
Helper method for defining space-delimited indentation blocks,
such as those used to define block statements in Python source code.
Parameters:
- ``blockStatementExpr`` - expression defining syntax of statement that
  is repeated within the indented block
- ``indentStack`` - list created by caller to manage indentation stack
  (multiple ``statementWithIndentedBlock`` expressions within a single
  grammar should share a common ``indentStack``)
- ``indent`` - boolean indicating whether block must be indented beyond
  the current level; set to ``False`` for block of left-most statements
  (default= ``True``)
A valid block must contain at least one ``blockStatement``.
(Note that indentedBlock uses internal parse actions which make it
incompatible with packrat parsing.)
Example::
    data = '''
    def A(z):
      A1
      B = 100
      G = A2
      A2
      A3
    B
    def BB(a,b,c):
      BB1
      def BBA():
        bba1
        bba2
        bba3
    C
    D
    def spam(x,y):
         def eggs(z):
             pass
    '''
    indentStack = [1]
    stmt = Forward()
    identifier = Word(alphas, alphanums)
    funcDecl = ("def" + identifier + Group("(" + Opt(delimitedList(identifier)) + ")") + ":")
    func_body = indentedBlock(stmt, indentStack)
    funcDef = Group(funcDecl + func_body)
    rvalue = Forward()
    funcCall = Group(identifier + "(" + Opt(delimitedList(rvalue)) + ")")
    rvalue << (funcCall | identifier | Word(nums))
    assignment = Group(identifier + "=" + rvalue)
    stmt << (funcDef | assignment | identifier)
    module_body = stmt[1, ...]
    parseTree = module_body.parseString(data)
    parseTree.pprint()
prints::
    [['def',
      'A',
      ['(', 'z', ')'],
      ':',
      [['A1'], [['B', '=', '100']], [['G', '=', 'A2']], ['A2'], ['A3']]],
     'B',
     ['def',
      'BB',
      ['(', 'a', 'b', 'c', ')'],
      ':',
      [['BB1'], [['def', 'BBA', ['(', ')'], ':', [['bba1'], ['bba2'], ['bba3']]]]]],
     'C',
     'D',
     ['def',
      'spam',
      ['(', 'x', 'y', ')'],
      ':',
      [[['def', 'eggs', ['(', 'z', ')'], ':', [['pass']]]]]]]
Definition at line 915 of file helpers.py.
References pyparsing.util.col().
infix_notation()
Forward pyparsing.helpers.infix_notation (ParserElement base_expr, list[InfixNotationOperatorSpec] op_list, Union[str, ParserElement] lpar = Suppress("("), Union[str, ParserElement] rpar = Suppress(")"))
Helper method for constructing grammars of expressions made up of
operators working in a precedence hierarchy.  Operators may be unary
or binary, left- or right-associative.  Parse actions can also be
attached to operator expressions. The generated parser will also
recognize the use of parentheses to override operator precedences
(see example below).
Note: if you define a deep operator list, you may see performance
issues when using infix_notation. See
:class:`ParserElement.enable_packrat` for a mechanism to potentially
improve your parser performance.
Parameters:
- ``base_expr`` - expression representing the most basic operand to
  be used in the expression
- ``op_list`` - list of tuples, one for each operator precedence level
  in the expression grammar; each tuple is of the form ``(op_expr,
  num_operands, right_left_assoc, (optional)parse_action)``, where:
  - ``op_expr`` is the pyparsing expression for the operator; may also
    be a string, which will be converted to a Literal; if ``num_operands``
    is 3, ``op_expr`` is a tuple of two expressions, for the two
    operators separating the 3 terms
  - ``num_operands`` is the number of terms for this operator (must be 1,
    2, or 3)
  - ``right_left_assoc`` is the indicator whether the operator is right
    or left associative, using the pyparsing-defined constants
    ``OpAssoc.RIGHT`` and ``OpAssoc.LEFT``.
  - ``parse_action`` is the parse action to be associated with
    expressions matching this operator expression (the parse action
    tuple member may be omitted); if the parse action is passed
    a tuple or list of functions, this is equivalent to calling
    ``set_parse_action(*fn)``
    (:class:`ParserElement.set_parse_action`)
- ``lpar`` - expression for matching left-parentheses; if passed as a
  str, then will be parsed as ``Suppress(lpar)``. If lpar is passed as
  an expression (such as ``Literal('(')``), then it will be kept in
  the parsed results, and grouped with them. (default= ``Suppress('(')``)
- ``rpar`` - expression for matching right-parentheses; if passed as a
  str, then will be parsed as ``Suppress(rpar)``. If rpar is passed as
  an expression (such as ``Literal(')')``), then it will be kept in
  the parsed results, and grouped with them. (default= ``Suppress(')')``)
Example::
    # simple example of four-function arithmetic with ints and
    # variable names
    integer = pyparsing_common.signed_integer
    varname = pyparsing_common.identifier
    arith_expr = infix_notation(integer | varname,
        [
        ('-', 1, OpAssoc.RIGHT),
        (one_of('* /'), 2, OpAssoc.LEFT),
        (one_of('+ -'), 2, OpAssoc.LEFT),
        ])
    arith_expr.run_tests('''
        5+3*6
        (5+3)*6
        -2--11
        ''', full_dump=False)
prints::
    5+3*6
    [[5, '+', [3, '*', 6]]]
    (5+3)*6
    [[[5, '+', 3], '*', 6]]
    (5+x)*y
    [[[5, '+', 'x'], '*', 'y']]
    -2--11
    [[['-', 2], '-', ['-', 11]]]
Definition at line 718 of file helpers.py.
locatedExpr()
ParserElement pyparsing.helpers.locatedExpr (ParserElement expr)
(DEPRECATED - future code should use the :class:`Located` class)
Helper to decorate a returned token with its starting and ending
locations in the input string.
This helper adds the following results names:
- ``locn_start`` - location where matched expression begins
- ``locn_end`` - location where matched expression ends
- ``value`` - the actual parsed results
Be careful if the input text contains ``<TAB>`` characters, you
may want to call :class:`ParserElement.parse_with_tabs`
Example::
    wd = Word(alphas)
    for match in locatedExpr(wd).search_string("ljsdf123lksdjjf123lkkjj1222"):
        print(match)
prints::
    [[0, 'ljsdf', 5]]
    [[8, 'lksdjjf', 15]]
    [[18, 'lkkjj', 23]]
Definition at line 386 of file helpers.py.
make_html_tags()
tuple[ParserElement, ParserElement] pyparsing.helpers.make_html_tags (Union[str, ParserElement] tag_str)
Helper to construct opening and closing tag expressions for HTML,
given a tag name. Matches tags in either upper or lower case,
attributes with namespaces and with quoted or unquoted values.
Example::
    text = '<td>More info at the <a href="https://github.com/pyparsing/pyparsing/wiki">pyparsing</a> wiki page</td>'
    # make_html_tags returns pyparsing expressions for the opening and
    # closing tags as a 2-tuple
    a, a_end = make_html_tags("A")
    link_expr = a + SkipTo(a_end)("link_text") + a_end
    for link in link_expr.search_string(text):
        # attributes in the <A> tag (like "href" shown here) are
        # also accessible as named results
        print(link.link_text, '->', link.href)
prints::
    pyparsing -> https://github.com/pyparsing/pyparsing/wiki
Definition at line 634 of file helpers.py.
References _makeTags().
Referenced by make_xml_tags().
make_xml_tags()
tuple[ParserElement, ParserElement] pyparsing.helpers.make_xml_tags (Union[str, ParserElement] tag_str)
Helper to construct opening and closing tag expressions for XML,
given a tag name. Matches tags only in the given upper/lower case.
Example: similar to :class:`make_html_tags`
Definition at line 661 of file helpers.py.
References _makeTags(), and make_html_tags().
match_previous_expr()
ParserElement pyparsing.helpers.match_previous_expr (ParserElement expr)
Helper to define an expression that is indirectly defined from
the tokens matched in a previous expression, that is, it looks for
a 'repeat' of a previous expression.  For example::
    first = Word(nums)
    second = match_previous_expr(first)
    match_expr = first + ":" + second
will match ``"1:1"``, but not ``"1:2"``.  Because this
matches by expressions, will *not* match the leading ``"1:1"``
in ``"1:10"``; the expressions are evaluated first, and then
compared, so ``"1"`` is compared with ``"10"``. Do *not* use
with packrat parsing enabled.
Definition at line 117 of file helpers.py.
match_previous_literal()
ParserElement pyparsing.helpers.match_previous_literal (ParserElement expr)
Helper to define an expression that is indirectly defined from
the tokens matched in a previous expression, that is, it looks for
a 'repeat' of a previous expression.  For example::
    first = Word(nums)
    second = match_previous_literal(first)
    match_expr = first + ":" + second
will match ``"1:1"``, but not ``"1:2"``.  Because this
matches a previous literal, will also match the leading
``"1:1"`` in ``"1:10"``. If this is not desired, use
:class:`match_previous_expr`. Do *not* use with packrat parsing
enabled.
Definition at line 82 of file helpers.py.
nested_expr()
ParserElement pyparsing.helpers.nested_expr (Union[str, ParserElement] opener = "(", Union[str, ParserElement] closer = ")", typing.Optional[ParserElement] content = None, ParserElement ignore_expr = _NO_IGNORE_EXPR_GIVEN, * , ParserElement ignoreExpr = _NO_IGNORE_EXPR_GIVEN)
Helper method for defining nested lists enclosed in opening and
closing delimiters (``"("`` and ``")"`` are the default).
Parameters:
- ``opener`` - opening character for a nested list
  (default= ``"("``); can also be a pyparsing expression
- ``closer`` - closing character for a nested list
  (default= ``")"``); can also be a pyparsing expression
- ``content`` - expression for items within the nested lists
  (default= ``None``)
- ``ignore_expr`` - expression for ignoring opening and closing delimiters
  (default= :class:`quoted_string`)
- ``ignoreExpr`` - this pre-PEP8 argument is retained for compatibility
  but will be removed in a future release
If an expression is not provided for the content argument, the
nested expression will capture all whitespace-delimited content
between delimiters as a list of separate values.
Use the ``ignore_expr`` argument to define expressions that may
contain opening or closing characters that should not be treated as
opening or closing characters for nesting, such as quoted_string or
a comment expression.  Specify multiple expressions using an
:class:`Or` or :class:`MatchFirst`. The default is
:class:`quoted_string`, but if no expressions are to be ignored, then
pass ``None`` for this argument.
Example::
    data_type = one_of("void int short long char float double")
    decl_data_type = Combine(data_type + Opt(Word('*')))
    ident = Word(alphas+'_', alphanums+'_')
    number = pyparsing_common.number
    arg = Group(decl_data_type + ident)
    LPAR, RPAR = map(Suppress, "()")
    code_body = nested_expr('{', '}', ignore_expr=(quoted_string | c_style_comment))
    c_function = (decl_data_type("type")
                  + ident("name")
                  + LPAR + Opt(DelimitedList(arg), [])("args") + RPAR
                  + code_body("body"))
    c_function.ignore(c_style_comment)
    source_code = '''
        int is_odd(int x) {
            return (x%2);
        }
        int dec_to_hex(char hchar) {
            if (hchar >= '0' && hchar <= '9') {
                return (ord(hchar)-ord('0'));
            } else {
                return (10+ord(hchar)-ord('A'));
            }
        }
    '''
    for func in c_function.search_string(source_code):
        print("%(name)s (%(type)s) args: %(args)s" % func)
prints::
    is_odd (int) args: [['int', 'x']]
    dec_to_hex (int) args: [['char', 'hchar']]
Definition at line 426 of file helpers.py.
one_of()
ParserElement pyparsing.helpers.one_of (Union[typing.Iterable[str], str] strs, bool caseless = False, bool use_regex = True, bool as_keyword = False, * , bool useRegex = True, bool asKeyword = False)
Helper to quickly define a set of alternative :class:`Literal` s,
and makes sure to do longest-first testing when there is a conflict,
regardless of the input order, but returns
a :class:`MatchFirst` for best performance.
Parameters:
- ``strs`` - a string of space-delimited literals, or a collection of
  string literals
- ``caseless`` - treat all literals as caseless - (default= ``False``)
- ``use_regex`` - as an optimization, will
  generate a :class:`Regex` object; otherwise, will generate
  a :class:`MatchFirst` object (if ``caseless=True`` or ``as_keyword=True``, or if
  creating a :class:`Regex` raises an exception) - (default= ``True``)
- ``as_keyword`` - enforce :class:`Keyword`-style matching on the
  generated expressions - (default= ``False``)
- ``asKeyword`` and ``useRegex`` are retained for pre-PEP8 compatibility,
  but will be removed in a future release
Example::
    comp_oper = one_of("< = > <= >= !=")
    var = Word(alphas)
    number = Word(nums)
    term = var | number
    comparison_expr = term + comp_oper + term
    print(comparison_expr.search_string("B = 12  AA=23 B<=AA AA>12"))
prints::
    [['B', '=', '12'], ['AA', '=', '23'], ['B', '<=', 'AA'], ['AA', '>', '12']]
Definition at line 153 of file helpers.py.
original_text_for()
ParserElement pyparsing.helpers.original_text_for (ParserElement expr, bool as_string = True, * , bool asString = True)
Helper to return the original, untokenized text for a given
expression.  Useful to restore the parsed fields of an HTML start
tag into the raw tag text itself, or to revert separate tokens with
intervening whitespace back to the original matching input text. By
default, returns a string containing the original parsed text.
If the optional ``as_string`` argument is passed as
``False``, then the return value is
a :class:`ParseResults` containing any results names that
were originally matched, and a single token containing the original
matched text from the input string.  So if the expression passed to
:class:`original_text_for` contains expressions with defined
results names, you must set ``as_string`` to ``False`` if you
want to preserve those results name values.
The ``asString`` pre-PEP8 argument is retained for compatibility,
but will be removed in a future release.
Example::
    src = "this is test <b> bold <i>text</i> </b> normal text "
    for tag in ("b", "i"):
        opener, closer = make_html_tags(tag)
        patt = original_text_for(opener + ... + closer)
        print(patt.search_string(src)[0])
prints::
    ['<b> bold <i>text</i> </b>']
    ['<i>text</i>']
Definition at line 326 of file helpers.py.
replace_html_entity()
pyparsing.helpers.replace_html_entity (s, l, t)
Helper parser action to replace common HTML entities with their special characters
Definition at line 687 of file helpers.py.
ungroup()
ParserElement pyparsing.helpers.ungroup (ParserElement expr)
Helper to undo pyparsing's default grouping of And expressions,
even if all but one are non-empty.
Definition at line 379 of file helpers.py.
Variable Documentation
_builtin_exprs
list pyparsing.helpers._builtin_exprs protected
Initial value:
=  [
    v for v in vars().values() if isinstance(v, ParserElement)
]
Definition at line 1084 of file helpers.py.
_htmlEntityMap
dict pyparsing.helpers._htmlEntityMap = {k.rstrip(";"): v for k, v in html.entities.html5.items()} protected
Definition at line 678 of file helpers.py.
_most_common_entities
str pyparsing.helpers._most_common_entities protected
Initial value:
=  "nbsp lt gt amp quot apos cent pound euro copy".replace(
    " ", "|"
)
Definition at line 679 of file helpers.py.
_NO_IGNORE_EXPR_GIVEN
pyparsing.helpers._NO_IGNORE_EXPR_GIVEN = NoMatch() protected
Definition at line 423 of file helpers.py.
any_close_tag
pyparsing.helpers.any_close_tag
Definition at line 674 of file helpers.py.
any_open_tag
ParserElement pyparsing.helpers.any_open_tag
Definition at line 674 of file helpers.py.
anyCloseTag
pyparsing.helpers.anyCloseTag = any_close_tag
Definition at line 1109 of file helpers.py.
anyOpenTag
ParserElement pyparsing.helpers.anyOpenTag = any_open_tag
Definition at line 1108 of file helpers.py.
c_style_comment
pyparsing.helpers.c_style_comment = Regex(r"/\*(?:[^*]|\*(?!/))*\*\/").set_name("C style comment")
Definition at line 1060 of file helpers.py.
common_html_entity
pyparsing.helpers.common_html_entity
Initial value:
=  Regex(
    lambda: f"&(?P<entity>{_most_common_entities}|{make_compressed_re(_htmlEntityMap)});"
).set_name("common HTML entity")
Definition at line 682 of file helpers.py.
commonHTMLEntity
pyparsing.helpers.commonHTMLEntity = common_html_entity
Definition at line 1110 of file helpers.py.
countedArray
pyparsing.helpers.countedArray = replaced_by_pep8("countedArray", counted_array)
Definition at line 1120 of file helpers.py.
cpp_style_comment
pyparsing.helpers.cpp_style_comment
Initial value:
=  Regex(
    r"(?:/\*(?:[^*]|\*(?!/))*\*\/)|(?://(?:\\\n|[^\n])*)"
).set_name("C++ style comment")
Definition at line 1070 of file helpers.py.
cppStyleComment
pyparsing.helpers.cppStyleComment = cpp_style_comment
Definition at line 1115 of file helpers.py.
cStyleComment
pyparsing.helpers.cStyleComment = c_style_comment
Definition at line 1111 of file helpers.py.
dbl_slash_comment
pyparsing.helpers.dbl_slash_comment = Regex(r"//(?:\\\n|[^\n])*").set_name("// comment")
Definition at line 1067 of file helpers.py.
dblSlashComment
pyparsing.helpers.dblSlashComment = dbl_slash_comment
Definition at line 1114 of file helpers.py.
delimited_list
pyparsing.helpers.delimited_list = replaced_by_pep8("delimited_list", DelimitedList)
Definition at line 1119 of file helpers.py.
delimitedList
pyparsing.helpers.delimitedList = replaced_by_pep8("delimitedList", DelimitedList)
Definition at line 1118 of file helpers.py.
dictOf
pyparsing.helpers.dictOf = replaced_by_pep8("dictOf", dict_of)
Definition at line 1124 of file helpers.py.
html_comment
pyparsing.helpers.html_comment = Regex(r"<!--[\s\S]*?-->").set_name("HTML comment")
Definition at line 1063 of file helpers.py.
htmlComment
pyparsing.helpers.htmlComment = html_comment
Definition at line 1112 of file helpers.py.
infixNotation
pyparsing.helpers.infixNotation = replaced_by_pep8("infixNotation", infix_notation)
Definition at line 1130 of file helpers.py.
InfixNotationOperatorArgType
pyparsing.helpers.InfixNotationOperatorArgType
Initial value:
=  Union[
    ParserElement, str, tuple[Union[ParserElement, str], Union[ParserElement, str]]
]
Definition at line 700 of file helpers.py.
InfixNotationOperatorSpec
pyparsing.helpers.InfixNotationOperatorSpec
Initial value:
=  Union[
    tuple[
        InfixNotationOperatorArgType,
        int,
        OpAssoc,
        typing.Optional[ParseAction],
    ],
    tuple[
        InfixNotationOperatorArgType,
        int,
        OpAssoc,
    ],
]
Definition at line 703 of file helpers.py.
java_style_comment
pyparsing.helpers.java_style_comment = cpp_style_comment
Definition at line 1075 of file helpers.py.
javaStyleComment
pyparsing.helpers.javaStyleComment = java_style_comment
Definition at line 1116 of file helpers.py.
makeHTMLTags
pyparsing.helpers.makeHTMLTags = replaced_by_pep8("makeHTMLTags", make_html_tags)
Definition at line 1127 of file helpers.py.
makeXMLTags
pyparsing.helpers.makeXMLTags = replaced_by_pep8("makeXMLTags", make_xml_tags)
Definition at line 1128 of file helpers.py.
matchPreviousExpr
pyparsing.helpers.matchPreviousExpr = replaced_by_pep8("matchPreviousExpr", match_previous_expr)
Definition at line 1122 of file helpers.py.
matchPreviousLiteral
pyparsing.helpers.matchPreviousLiteral = replaced_by_pep8("matchPreviousLiteral", match_previous_literal)
Definition at line 1121 of file helpers.py.
nestedExpr
pyparsing.helpers.nestedExpr = replaced_by_pep8("nestedExpr", nested_expr)
Definition at line 1126 of file helpers.py.
oneOf
pyparsing.helpers.oneOf = replaced_by_pep8("oneOf", one_of)
Definition at line 1123 of file helpers.py.
opAssoc
pyparsing.helpers.opAssoc = OpAssoc
Definition at line 1107 of file helpers.py.
originalTextFor
pyparsing.helpers.originalTextFor = replaced_by_pep8("originalTextFor", original_text_for)
Definition at line 1125 of file helpers.py.
python_style_comment
pyparsing.helpers.python_style_comment = Regex(r"#.*").set_name("Python style comment")
Definition at line 1078 of file helpers.py.
pythonStyleComment
pyparsing.helpers.pythonStyleComment = python_style_comment
Definition at line 1117 of file helpers.py.
replaceHTMLEntity
pyparsing.helpers.replaceHTMLEntity = replaced_by_pep8("replaceHTMLEntity", replace_html_entity)
Definition at line 1129 of file helpers.py.
rest_of_line
pyparsing.helpers.rest_of_line = Regex(r".*").leave_whitespace().set_name("rest of line")
Definition at line 1066 of file helpers.py.
restOfLine
pyparsing.helpers.restOfLine = rest_of_line
Definition at line 1113 of file helpers.py.