Code Cloning Analysis: fontTools.cffLib.CFFFontSet Class Reference
fontTools.cffLib.CFFFontSet Class Reference
Public Member Functions
decompile (self, file, otFont, isCFF2=None)
__len__ (self)
keys (self)
values (self)
__getitem__ (self, nameOrIndex)
compile (self, file, otFont, isCFF2=None)
toXML (self, xmlWriter)
fromXML (self, name, attrs, content, otFont=None)
convertCFFToCFF2 (self, otFont)
convertCFF2ToCFF (self, otFont)
desubroutinize (self)
remove_hints (self)
remove_unused_subroutines (self)
Public Attributes
otFont = otFont
int major = expected_major:
int offSize = struct.unpack("B", file.read(1))[0]
int hdrSize
list fontNames = list(tostr(s) for s in Index(file, isCFF2=isCFF2))
topDictIndex = TopDictIndex(file, isCFF2=isCFF2)
strings = IndexedStrings(file)
topDictSize = struct.unpack(">H", file.read(2))[0]
GlobalSubrs = GlobalSubrsIndex(file, isCFF2=isCFF2)
int minor = 0
Detailed Description
A CFF font "file" can contain more than one font, although this is
extremely rare (and not allowed within OpenType fonts).
This class is the entry point for parsing a CFF table. To actually
manipulate the data inside the CFF font, you will want to access the
``CFFFontSet``'s :class:`TopDict` object. To do this, a ``CFFFontSet``
object can either be treated as a dictionary (with appropriate
``keys()`` and ``values()`` methods) mapping font names to :class:`TopDict`
objects, or as a list.
.. code:: python
        from fontTools import ttLib
        tt = ttLib.TTFont("Tests/cffLib/data/LinLibertine_RBI.otf")
        tt["CFF "].cff
        # <fontTools.cffLib.CFFFontSet object at 0x101e24c90>
        tt["CFF "].cff[0] # Here's your actual font data
        # <fontTools.cffLib.TopDict object at 0x1020f1fd0>
Definition at line 48 of file __init__.py.
Member Function Documentation
__getitem__()
fontTools.cffLib.CFFFontSet.__getitem__ (self, nameOrIndex)
Return TopDict instance identified by name (str) or index (int
or any object that implements `__index__`).
Definition at line 124 of file __init__.py.
References fontNames, and topDictIndex.
__len__()
fontTools.cffLib.CFFFontSet.__len__ (self)
Definition at line 115 of file __init__.py.
compile()
fontTools.cffLib.CFFFontSet.compile (self, file, otFont, isCFF2 = None)
Write the object back into binary representation onto the given file.
``file`` should be a file handle object. ``otFont`` is the top-level
:py:class:`fontTools.ttLib.ttFont.TTFont` object containing this CFF file.
If ``isCFF2`` is passed and set to ``True`` or ``False``, then the
library makes an assertion that the CFF header is of the appropriate
version.
Definition at line 140 of file __init__.py.
References fontNames, GlobalSubrs, hdrSize, major, offSize, otFont, topDictIndex, and topDictSize.
Referenced by fontTools.ttLib.tables.TupleVariation.TupleVariation.getCoordWidth(), and PIL.FontFile.FontFile.save().
convertCFF2ToCFF()
fontTools.cffLib.CFFFontSet.convertCFF2ToCFF (self, otFont)
Definition at line 306 of file __init__.py.
convertCFFToCFF2()
fontTools.cffLib.CFFFontSet.convertCFFToCFF2 (self, otFont)
Definition at line 301 of file __init__.py.
decompile()
fontTools.cffLib.CFFFontSet.decompile (self, file, otFont, isCFF2 = None)
Parse a binary CFF file into an internal representation. ``file``
should be a file handle object. ``otFont`` is the top-level
:py:class:`fontTools.ttLib.ttFont.TTFont` object containing this CFF file.
If ``isCFF2`` is passed and set to ``True`` or ``False``, then the
library makes an assertion that the CFF header is of the appropriate
version.
Definition at line 70 of file __init__.py.
References fontNames, GlobalSubrs, hdrSize, major, offSize, otFont, strings, topDictIndex, and topDictSize.
Referenced by fontTools.ttLib.tables._c_m_a_p.CmapSubtable.newSubtable().
desubroutinize()
fontTools.cffLib.CFFFontSet.desubroutinize (self)
Definition at line 311 of file __init__.py.
fromXML()
fontTools.cffLib.CFFFontSet.fromXML (self, name, attrs, content, otFont = None)
Reads data from the XML element into the ``CFFFontSet`` object.
Definition at line 233 of file __init__.py.
References fontNames, GlobalSubrs, hdrSize, major, minor, offSize, otFont, and topDictIndex.
keys()
fontTools.cffLib.CFFFontSet.keys (self)
Definition at line 118 of file __init__.py.
Referenced by fontTools.ttLib.ttFont.TTFont._save(), sklearn.utils._bunch.Bunch._set_deprecated(), pandas.io.pytables.HDFStore.copy(), fontTools.ttLib.ttFont.TTFont.ensureDecompiled(), scipy.sparse._dok._dok_base.get(), pandas.io.pytables.HDFStore.info(), pandas.io.pytables.HDFStore.keys(), fontTools.varLib.instancer.AxisLimits.normalize(), pip._vendor.pyparsing.results.ParseResults.pprint(), pyparsing.results.ParseResults.pprint(), scipy.sparse._dok._dok_base.resize(), fontTools.ttLib.ttFont.TTFont.saveXML(), scipy.sparse._dok._dok_base.tocoo(), and pip._vendor.distlib.metadata.LegacyMetadata.todict().
remove_hints()
fontTools.cffLib.CFFFontSet.remove_hints (self)
Definition at line 316 of file __init__.py.
remove_unused_subroutines()
fontTools.cffLib.CFFFontSet.remove_unused_subroutines (self)
Definition at line 321 of file __init__.py.
toXML()
fontTools.cffLib.CFFFontSet.toXML (self, xmlWriter)
Write the object into XML representation onto the given
:class:`fontTools.misc.xmlWriter.XMLWriter`.
.. code:: python
        writer = xmlWriter.XMLWriter(sys.stdout)
        tt["CFF "].cff.toXML(writer)
Definition at line 204 of file __init__.py.
References fontNames, GlobalSubrs, major, minor, and toXML().
Referenced by toXML().
values()
fontTools.cffLib.CFFFontSet.values (self)
Definition at line 121 of file __init__.py.
Referenced by pandas.core.apply.FrameApply.apply_raw(), scipy.sparse._dok._dok_base.count_nonzero(), pandas.core.series.Series.dot(), and scipy.sparse._dok._dok_base.tocoo().
Member Data Documentation
fontNames
fontTools.cffLib.CFFFontSet.fontNames = list(tostr(s) for s in Index(file, isCFF2=isCFF2))
Definition at line 98 of file __init__.py.
Referenced by __getitem__(), matplotlib.backends.backend_pdf.PdfFile.__init__(), compile(), decompile(), matplotlib.backends.backend_pdf.PdfFile.dviFontName(), matplotlib.backends.backend_pdf.PdfFile.fontName(), fromXML(), and toXML().
GlobalSubrs
fontTools.cffLib.CFFFontSet.GlobalSubrs = GlobalSubrsIndex(file, isCFF2=isCFF2)
Definition at line 111 of file __init__.py.
Referenced by compile(), decompile(), fromXML(), and toXML().
hdrSize
fontTools.cffLib.CFFFontSet.hdrSize
Definition at line 97 of file __init__.py.
Referenced by compile(), decompile(), and fromXML().
major
fontTools.cffLib.CFFFontSet.major = expected_major:
Definition at line 89 of file __init__.py.
Referenced by matplotlib.axis.Axis.__init__(), numpy.lib._version.NumpyVersion._compare_version(), matplotlib.axis.Axis._update_axisinfo(), matplotlib.axis.Axis._update_ticks(), compile(), decompile(), mplot3d.axis3d.Axis.draw_pane(), fromXML(), matplotlib.axis.Axis.get_major_formatter(), matplotlib.axis.Axis.get_major_locator(), matplotlib.axis.Axis.get_majorticklocs(), matplotlib.axis.Axis.get_minorticklocs(), matplotlib.axis.Axis.get_tightbbox(), matplotlib.axis.Axis.set_major_formatter(), matplotlib.axis.Axis.set_major_locator(), matplotlib.axis.Axis.set_minor_formatter(), and toXML().
minor
int fontTools.cffLib.CFFFontSet.minor = 0
Definition at line 242 of file __init__.py.
Referenced by matplotlib.axis.Axis.__init__(), numpy.lib._version.NumpyVersion._compare_version(), matplotlib.axis.Axis._update_axisinfo(), matplotlib.axis.Axis._update_ticks(), fromXML(), matplotlib.axis.Axis.get_minor_formatter(), matplotlib.axis.Axis.get_minor_locator(), matplotlib.axis.Axis.get_minorticklocs(), matplotlib.axis.Axis.set_minor_formatter(), matplotlib.axis.Axis.set_minor_locator(), and toXML().
offSize
fontTools.cffLib.CFFFontSet.offSize = struct.unpack("B", file.read(1))[0]
Definition at line 96 of file __init__.py.
Referenced by compile(), decompile(), and fromXML().
otFont
fontTools.cffLib.CFFFontSet.otFont = otFont
Definition at line 80 of file __init__.py.
Referenced by compile(), decompile(), and fromXML().
strings
fontTools.cffLib.CFFFontSet.strings = IndexedStrings(file)
Definition at line 100 of file __init__.py.
Referenced by decompile().
topDictIndex
fontTools.cffLib.CFFFontSet.topDictIndex = TopDictIndex(file, isCFF2=isCFF2)
Definition at line 99 of file __init__.py.
Referenced by __getitem__(), compile(), decompile(), and fromXML().
topDictSize
fontTools.cffLib.CFFFontSet.topDictSize = struct.unpack(">H", file.read(2))[0]
Definition at line 102 of file __init__.py.
Referenced by compile(), and decompile().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/cffLib/__init__.py