Code Cloning Analysis: matplotlib.tests.test_animation.RegisteredNullMovieWriter Class Reference
matplotlib.tests.test_animation.RegisteredNullMovieWriter Class Reference
Public Member Functions
__init__ (self, fps=None, codec=None, bitrate=None, extra_args=None, metadata=None)
isAvailable (cls)
Public Member Functions inherited from matplotlib.tests.test_animation.NullMovieWriter
setup (self, fig, outfile, dpi, *args)
grab_frame (self, **savefig_kwargs)
finish (self)
Public Member Functions inherited from matplotlib.animation.AbstractMovieWriter
__init__ (self, fps=5, metadata=None, codec=None, bitrate=None)
frame_size (self)
saving (self, fig, outfile, dpi, *args, **kwargs)
Additional Inherited Members
Public Attributes inherited from matplotlib.tests.test_animation.NullMovieWriter
args = args
savefig_kwargs = savefig_kwargs
Public Attributes inherited from matplotlib.animation.AbstractMovieWriter
fps = fps
metadata = metadata if metadata is not None else {}
codec = mpl._val_or_rc(codec, 'animation.codec')
bitrate = mpl._val_or_rc(bitrate, 'animation.bitrate')
outfile = outfile
fig = fig
dpi = dpi
Protected Member Functions inherited from matplotlib.animation.AbstractMovieWriter
_supports_transparency (self)
Protected Attributes inherited from matplotlib.tests.test_animation.NullMovieWriter
int _count = 0
Detailed Description
Definition at line 131 of file test_animation.py.
Constructor & Destructor Documentation
__init__()
matplotlib.tests.test_animation.RegisteredNullMovieWriter.__init__ (self, fps = None, codec = None, bitrate = None, extra_args = None, metadata = None)
Definition at line 139 of file test_animation.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
isAvailable()
matplotlib.tests.test_animation.RegisteredNullMovieWriter.isAvailable (cls)
Definition at line 144 of file test_animation.py.
Referenced by matplotlib.animation.MovieWriterRegistry.is_available().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/tests/test_animation.py