Code Cloning Analysis: sklearn.utils.parallel Namespace Reference
sklearn.utils.parallel Namespace Reference
Classes
class _FuncWrapper
class Parallel
Functions
_with_config_and_warning_filters (delayed_func, config, warning_filters)
delayed (function)
_get_threadpool_controller ()
_threadpool_controller_decorator (limits=1, user_api="blas")
Variables
_threadpool_controller = None
Detailed Description
Customizations of :mod:`joblib` and :mod:`threadpoolctl` tools for scikit-learn
usage.
Function Documentation
_get_threadpool_controller()
sklearn.utils.parallel._get_threadpool_controller () protected
Return the global threadpool controller instance.
Definition at line 150 of file parallel.py.
Referenced by _threadpool_controller_decorator().
_threadpool_controller_decorator()
sklearn.utils.parallel._threadpool_controller_decorator (limits = 1, user_api = "blas") protected
Decorator to limit the number of threads used at the function level.
It should be preferred over `threadpoolctl.ThreadpoolController.wrap` because this
one only loads the shared libraries when the function is called while the latter
loads them at import time.
Definition at line 160 of file parallel.py.
References _get_threadpool_controller().
_with_config_and_warning_filters()
sklearn.utils.parallel._with_config_and_warning_filters (delayed_func, config, warning_filters) protected
Helper function that intends to attach a config to a delayed function.
Definition at line 24 of file parallel.py.
Referenced by sklearn.utils.parallel.Parallel.__call__().
delayed()
sklearn.utils.parallel.delayed (function)
Decorator used to capture the arguments of a function.
This alternative to `joblib.delayed` is meant to be used in conjunction
with `sklearn.utils.parallel.Parallel`. The latter captures the scikit-
learn configuration by calling `sklearn.get_config()` in the current
thread, prior to dispatching the first task. The captured configuration is
then propagated and enabled for the duration of the execution of the
delayed function in the joblib workers.
.. versionchanged:: 1.3
   `delayed` was moved from `sklearn.utils.fixes` to `sklearn.utils.parallel`
   in scikit-learn 1.3.
Parameters
----------
function : callable
    The function to be delayed.
Returns
-------
output: tuple
    Tuple containing the delayed function, the positional arguments, and the
    keyword arguments.
Definition at line 86 of file parallel.py.
Variable Documentation
_threadpool_controller
sklearn.utils.parallel._threadpool_controller = None protected
Definition at line 21 of file parallel.py.