Code Cloning Analysis: matplotlib.container.ErrorbarContainer Class Reference
matplotlib.container.ErrorbarContainer Class Reference
Public Member Functions
__init__ (self, lines, has_xerr=False, has_yerr=False, **kwargs)
Public Member Functions inherited from matplotlib.container.Container
__repr__ (self)
__new__ (cls, *args, **kwargs)
__init__ (self, kl, label=None)
remove (self)
get_children (self)
Public Attributes
lines = lines
has_xerr = has_xerr
has_yerr = has_yerr
Additional Inherited Members
Static Public Attributes inherited from matplotlib.container.Container
get_label = Artist.get_label
set_label = Artist.set_label
add_callback = Artist.add_callback
remove_callback = Artist.remove_callback
pchanged = Artist.pchanged
Protected Attributes inherited from matplotlib.container.Container
_callbacks = cbook.CallbackRegistry(signals=["pchanged"])
_remove_method = None
_label = str(label) if label is not None else None
Detailed Description
Container for the artists of error bars (e.g. created by `.Axes.errorbar`).
The container can be treated as the *lines* tuple itself.
Additionally, you can access these and further parameters by the
attributes.
Attributes
----------
lines : tuple
    Tuple of ``(data_line, caplines, barlinecols)``.
    - data_line : A `~matplotlib.lines.Line2D` instance of x, y plot markers
      and/or line.
    - caplines : A tuple of `~matplotlib.lines.Line2D` instances of the error
      bar caps.
    - barlinecols : A tuple of `~matplotlib.collections.LineCollection` with the
      horizontal and vertical error ranges.
has_xerr, has_yerr : bool
    ``True`` if the errorbar has x/y errors.
Definition at line 77 of file container.py.
Constructor & Destructor Documentation
__init__()
matplotlib.container.ErrorbarContainer.__init__ (self, lines, has_xerr = False, has_yerr = False, ** kwargs)
Definition at line 102 of file container.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Data Documentation
has_xerr
matplotlib.container.ErrorbarContainer.has_xerr = has_xerr
Definition at line 104 of file container.py.
has_yerr
matplotlib.container.ErrorbarContainer.has_yerr = has_yerr
Definition at line 105 of file container.py.
lines
matplotlib.container.ErrorbarContainer.lines = lines
Definition at line 103 of file container.py.
Referenced by pip._vendor.rich.segment.SegmentLines.__init__(), matplotlib.figure.FigureBase.clear(), matplotlib.figure.FigureBase.get_children(), contourpy.util.renderer.Renderer.multi_lines(), and pandas.io.json._json.JsonReader.read().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/container.py