Code Cloning Analysis: pandas.core.computation.ops.Constant Class Reference
pandas.core.computation.ops.Constant Class Reference
Public Member Functions
name (self)
str __repr__ (self)
Public Member Functions inherited from pandas.core.computation.ops.Term
__new__ (cls, name, env, side=None, encoding=None)
None __init__ (self, name, env, side=None, encoding=None)
str local_name (self)
str __repr__ (self)
__call__ (self, *args, **kwargs)
Term evaluate (self, *args, **kwargs)
None update (self, value)
bool is_scalar (self)
type (self)
str raw (self)
bool is_datetime (self)
value (self)
None value (self, new_value)
int ndim (self)
Protected Member Functions
_resolve_name (self)
Additional Inherited Members
Public Attributes inherited from pandas.core.computation.ops.Term
env = env
side = side
is_local = tname.startswith(LOCAL_TAG) or tname in DEFAULT_GLOBALS
encoding = encoding
local_name
value = value
Static Public Attributes inherited from pandas.core.computation.ops.Term
return_type = type
Protected Attributes inherited from pandas.core.computation.ops.Term
_name = name
_value = self._resolve_name()
Detailed Description
Definition at line 191 of file ops.py.
Member Function Documentation
__repr__()
str pandas.core.computation.ops.Constant.__repr__ (self)
Definition at line 199 of file ops.py.
_resolve_name()
pandas.core.computation.ops.Constant._resolve_name (self) protected
Reimplemented from pandas.core.computation.ops.Term.
Definition at line 192 of file ops.py.
name()
pandas.core.computation.ops.Constant.name (self)
Reimplemented from pandas.core.computation.ops.Term.
Definition at line 196 of file ops.py.
Referenced by pip._vendor.pyparsing.core.Regex.__init__(), pandas.core.groupby.grouper.Grouping.group_arraylike(), pip._vendor.distro.distro.LinuxDistribution.linux_distribution(), and pip._internal.resolution.resolvelib.requirements.SpecifierRequirement.name().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/core/computation/ops.py