Code Cloning Analysis: pandas.core.indexes.frozen.FrozenList Class Reference
pandas.core.indexes.frozen.FrozenList Class Reference
Public Member Functions
FrozenList union (self, other)
FrozenList difference (self, other)
__getitem__ (self, n)
Self __radd__ (self, other)
bool __eq__ (self, object other)
Self __mul__ (self, other)
__reduce__ (self)
int __hash__ (self)
str __str__ (self)
str __repr__ (self)
Public Member Functions inherited from pandas.core.base.PandasObject
str __repr__ (self)
int __sizeof__ (self)
Public Member Functions inherited from pandas.core.accessor.DirNamesMixin
list[str] __dir__ (self)
Static Public Attributes
NoReturn pop = _disabled
NoReturn remove = _disabled
Protected Member Functions
NoReturn _disabled (self, *args, **kwargs)
Protected Member Functions inherited from pandas.core.base.PandasObject
_constructor (self)
None _reset_cache (self, str|None key=None)
Protected Member Functions inherited from pandas.core.accessor.DirNamesMixin
set[str] _dir_deletions (self)
set[str] _dir_additions (self)
Static Private Attributes
FrozenList __add__ = union
bool __req__ = __eq__
Self __imul__ = __mul__
NoReturn __setitem__ = _disabled
NoReturn __delitem__ = _disabled
Additional Inherited Members
Static Protected Attributes inherited from pandas.core.base.PandasObject
dict _cache [str, Any]
Static Protected Attributes inherited from pandas.core.accessor.DirNamesMixin
set _accessors = set()
frozenset _hidden_attrs = frozenset()
Detailed Description
Container that doesn't allow setting item *but*
because it's technically hashable, will be used
for lookups, appropriately, etc.
Definition at line 24 of file frozen.py.
Member Function Documentation
__eq__()
bool pandas.core.indexes.frozen.FrozenList.__eq__ (self, object other)
Definition at line 86 of file frozen.py.
Referenced by pandas.io.pytables.IndexCol.__eq__(), pip._vendor.msgpack.ext.Timestamp.__ne__(), and pip._vendor.distlib.version.Matcher.match().
__getitem__()
pandas.core.indexes.frozen.FrozenList.__getitem__ (self, n)
Definition at line 76 of file frozen.py.
__hash__()
int pandas.core.indexes.frozen.FrozenList.__hash__ (self)
Definition at line 102 of file frozen.py.
Referenced by pip._vendor.rich.style.Style.pick_first().
__mul__()
Self pandas.core.indexes.frozen.FrozenList.__mul__ (self, other)
Definition at line 93 of file frozen.py.
Referenced by pip._vendor.pyparsing.core.ParserElement.__mul__(), pyparsing.core.ParserElement.__mul__(), scipy.signal._ltisys.StateSpace.__truediv__(), and scipy.sparse.linalg._interface.LinearOperator.dot().
__radd__()
Self pandas.core.indexes.frozen.FrozenList.__radd__ (self, other)
Definition at line 81 of file frozen.py.
__reduce__()
pandas.core.indexes.frozen.FrozenList.__reduce__ (self)
Definition at line 98 of file frozen.py.
__repr__()
str pandas.core.indexes.frozen.FrozenList.__repr__ (self)
Definition at line 114 of file frozen.py.
__str__()
str pandas.core.indexes.frozen.FrozenList.__str__ (self)
Definition at line 111 of file frozen.py.
_disabled()
NoReturn pandas.core.indexes.frozen.FrozenList._disabled (self, * args, ** kwargs) protected
This method will not function because object is immutable.
Definition at line 105 of file frozen.py.
difference()
FrozenList pandas.core.indexes.frozen.FrozenList.difference (self, other)
Returns a FrozenList with elements from other removed from self.
Parameters
----------
other : array-like
    The array-like whose elements we are removing self.
Returns
-------
FrozenList
    The collection difference between self and other.
Definition at line 52 of file frozen.py.
union()
FrozenList pandas.core.indexes.frozen.FrozenList.union (self, other)
Returns a FrozenList with other concatenated to the end of self.
Parameters
----------
other : array-like
    The array-like whose elements we are concatenating.
Returns
-------
FrozenList
    The collection difference between self and other.
Definition at line 34 of file frozen.py.
Member Data Documentation
__add__
FrozenList pandas.core.indexes.frozen.FrozenList.__add__ = union static private
Definition at line 74 of file frozen.py.
Referenced by scipy.signal._ltisys.StateSpace.__add__(), scipy.sparse.linalg._interface.LinearOperator._rdot(), dateutil.relativedelta.relativedelta.normalized(), and scipy.sparse._base._spbase.power().
__delitem__
NoReturn pandas.core.indexes.frozen.FrozenList.__delitem__ = _disabled static private
Definition at line 118 of file frozen.py.
__imul__
Self pandas.core.indexes.frozen.FrozenList.__imul__ = __mul__ static private
Definition at line 96 of file frozen.py.
__req__
bool pandas.core.indexes.frozen.FrozenList.__req__ = __eq__ static private
Definition at line 91 of file frozen.py.
__setitem__
NoReturn pandas.core.indexes.frozen.FrozenList.__setitem__ = _disabled static private
Definition at line 117 of file frozen.py.
pop
NoReturn pandas.core.indexes.frozen.FrozenList.pop = _disabled static
Definition at line 119 of file frozen.py.
Referenced by fontTools.misc.psCharStrings.DictDecompiler.arg_blendList(), matplotlib.backends.backend_pdf.GraphicsContextPdf.clip_cmd(), matplotlib.backends.backend_pdf.GraphicsContextPdf.finalize(), and fontTools.misc.psCharStrings.T2OutlineExtractor.op_hvcurveto().
remove
NoReturn pandas.core.indexes.frozen.FrozenList.remove = _disabled static
Definition at line 120 of file frozen.py.
Referenced by pip._internal.operations.build.build_tracker.BuildTracker.remove(), pandas.io.pytables.HDFStore.root(), and pip._internal.operations.build.build_tracker.BuildTracker.track().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/core/indexes/frozen.py