Code Cloning Analysis: scipy.stats.tests.test_discrete_distns.TestNCH Class Reference
scipy.stats.tests.test_discrete_distns.TestNCH Class Reference
Public Member Functions
test_nch_hypergeom (self, dist_name)
test_nchypergeom_fisher_naive (self)
test_nchypergeom_wallenius_naive (self)
test_wallenius_against_mpmath (self)
test_rvs_shape (self, dist_name)
Static Public Attributes
tuple shape = (2, 4, 3)
int max_m = 100
m1 = np.random.randint(1, max_m, size=shape)
m2 = np.random.randint(1, max_m, size=shape)
N = m1 + m2
n = randint.rvs(0, N, size=N.shape)
xl = np.maximum(0, n-m2)
xu = np.minimum(n, m1)
x = randint.rvs(xl, xu, size=xl.shape)
int odds = np.random.rand(*x.shape)*2
Detailed Description
Definition at line 347 of file test_discrete_distns.py.
Member Function Documentation
test_nch_hypergeom()
scipy.stats.tests.test_discrete_distns.TestNCH.test_nch_hypergeom (self, dist_name)
Definition at line 363 of file test_discrete_distns.py.
test_nchypergeom_fisher_naive()
scipy.stats.tests.test_discrete_distns.TestNCH.test_nchypergeom_fisher_naive (self)
Definition at line 373 of file test_discrete_distns.py.
test_nchypergeom_wallenius_naive()
scipy.stats.tests.test_discrete_distns.TestNCH.test_nchypergeom_wallenius_naive (self)
Definition at line 407 of file test_discrete_distns.py.
test_rvs_shape()
scipy.stats.tests.test_discrete_distns.TestNCH.test_rvs_shape (self, dist_name)
Definition at line 543 of file test_discrete_distns.py.
test_wallenius_against_mpmath()
scipy.stats.tests.test_discrete_distns.TestNCH.test_wallenius_against_mpmath (self)
Definition at line 499 of file test_discrete_distns.py.
Member Data Documentation
m1
scipy.stats.tests.test_discrete_distns.TestNCH.m1 = np.random.randint(1, max_m, size=shape) static
Definition at line 351 of file test_discrete_distns.py.
m2
scipy.stats.tests.test_discrete_distns.TestNCH.m2 = np.random.randint(1, max_m, size=shape) static
Definition at line 352 of file test_discrete_distns.py.
max_m
int scipy.stats.tests.test_discrete_distns.TestNCH.max_m = 100 static
Definition at line 350 of file test_discrete_distns.py.
N
scipy.stats.tests.test_discrete_distns.TestNCH.N = m1 + m2 static
Definition at line 353 of file test_discrete_distns.py.
n
scipy.stats.tests.test_discrete_distns.TestNCH.n = randint.rvs(0, N, size=N.shape) static
Definition at line 354 of file test_discrete_distns.py.
odds
int scipy.stats.tests.test_discrete_distns.TestNCH.odds = np.random.rand(*x.shape)*2 static
Definition at line 358 of file test_discrete_distns.py.
shape
tuple scipy.stats.tests.test_discrete_distns.TestNCH.shape = (2, 4, 3) static
Definition at line 349 of file test_discrete_distns.py.
Referenced by pandas.io.pytables.Fixed.__repr__(), pandas.core.internals.managers.BaseBlockManager._combine(), scipy.sparse._index.IndexMixin._getcol(), scipy.sparse._index.IndexMixin._getrow(), pandas.core.internals.managers.BlockManager._interleave(), scipy.sparse._index.IndexMixin._raise_on_1d_array_slice(), pandas.core.arrays.timedeltas.TimedeltaArray._scalar_divlike_op(), pandas.core.internals.managers.BaseBlockManager._slice_take_blocks_ax0(), pandas.core.internals.array_manager.ArrayManager.as_array(), pandas.core.internals.managers.BlockManager.as_array(), pandas.core.internals.blocks.Block.astype(), pandas.core.internals.blocks.Block.convert(), pandas.core.indexes.multi.MultiIndex.drop(), numpy.core._internal._ctypes.get_shape(), pandas.core.internals.array_manager.ArrayManager.idelete(), pandas.core.internals.array_manager.SingleArrayManager.idelete(), pandas.core.internals.managers.BlockManager.idelete(), pandas.core.internals.managers.BlockManager.iset(), pandas.core.internals.blocks.Block.make_block_same_class(), numpy.lib.arrayterator.Arrayterator.shape(), pandas.core.internals.blocks.Block.split_and_operate(), and pandas.core.internals.managers.BaseBlockManager.take().
x
scipy.stats.tests.test_discrete_distns.TestNCH.x = randint.rvs(xl, xu, size=xl.shape) static
Definition at line 357 of file test_discrete_distns.py.
Referenced by matplotlib.widgets.ToolHandles.closest().
xl
scipy.stats.tests.test_discrete_distns.TestNCH.xl = np.maximum(0, n-m2) static
Definition at line 355 of file test_discrete_distns.py.
xu
scipy.stats.tests.test_discrete_distns.TestNCH.xu = np.minimum(n, m1) static
Definition at line 356 of file test_discrete_distns.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/stats/tests/test_discrete_distns.py