Code Cloning Analysis: pip._vendor.webencodings.IncrementalEncoder Class Reference
pip._vendor.webencodings.IncrementalEncoder Class Reference
Public Member Functions
__init__ (self, encoding=UTF8, errors='strict')
Public Attributes
encode = encoding.codec_info.incrementalencoder(errors).encode
Detailed Description
“Push”-based encoder.
:param encoding: An :class:`Encoding` object or a label string.
:param errors: Type of error handling. See :func:`codecs.register`.
:raises: :exc:`~exceptions.LookupError` for an unknown encoding label.
.. method:: encode(input, final=False)
    :param input: An Unicode string.
    :param final:
        Indicate that no more input is available.
        Must be :obj:`True` if this is the last call.
    :returns: A byte string.
Definition at line 323 of file __init__.py.
Constructor & Destructor Documentation
__init__()
pip._vendor.webencodings.IncrementalEncoder.__init__ (self, encoding = UTF8, errors = 'strict')
Definition at line 340 of file __init__.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Data Documentation
encode
pip._vendor.webencodings.IncrementalEncoder.encode = encoding.codec_info.incrementalencoder(errors).encode
Definition at line 342 of file __init__.py.
Referenced by PIL.ImageFile.PyEncoder.encode_to_file(), PIL.ImageFile.PyEncoder.encode_to_pyfd(), sklearn.preprocessing._discretization.KBinsDiscretizer.fit(), sklearn.preprocessing._discretization.KBinsDiscretizer.inverse_transform(), and sklearn.preprocessing._discretization.KBinsDiscretizer.transform().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pip/_vendor/webencodings/__init__.py