Code Cloning Analysis: pandas.tests.dtypes.test_dtypes.TestCategoricalDtype Class Reference
pandas.tests.dtypes.test_dtypes.TestCategoricalDtype Class Reference
Public Member Functions
dtype (self)
test_hash_vs_equality (self, dtype)
test_equality (self, dtype)
test_construction_from_string (self, dtype)
test_constructor_invalid (self)
test_from_values_or_dtype (self, values, categories, ordered, dtype, expected)
test_from_values_or_dtype_raises (self, values, categories, ordered, dtype)
test_from_values_or_dtype_invalid_dtype (self)
test_is_dtype (self, dtype)
test_basic (self, dtype)
test_tuple_categories (self)
test_is_boolean (self, categories, expected)
test_dtype_specific_categorical_dtype (self)
test_not_string (self)
test_repr_range_categories (self)
test_update_dtype (self)
test_repr (self)
Public Member Functions inherited from pandas.tests.dtypes.test_dtypes.Base
test_hash (self, dtype)
test_equality_invalid (self, dtype)
test_numpy_informed (self, dtype)
test_pickle (self, dtype)
Static Public Attributes
dtype1 = CategoricalDtype(["a", "b"], ordered=True)
dtype2 = CategoricalDtype(["x", "y"], ordered=False)
c = Categorical([0, 1], dtype=dtype1)
Detailed Description
Definition at line 81 of file test_dtypes.py.
Member Function Documentation
dtype()
pandas.tests.dtypes.test_dtypes.TestCategoricalDtype.dtype (self)
Class level fixture of dtype for TestCategoricalDtype
Definition at line 83 of file test_dtypes.py.
Referenced by pandas.core.arrays.base.ExtensionScalarOpsMixin._create_method(), scipy.sparse._index.IndexMixin._getcol(), pandas.core.generic.NDFrame._inplace_method(), scipy.sparse._index.IndexMixin._raise_on_1d_array_slice(), pandas.core.strings.object_array.ObjectStringArrayMixin._str_map(), numpy.matrixlib.defmatrix.matrix.H(), numpy.core.records.record.pprint(), pandas.core.frame.DataFrame.quantile(), and pandas.core.generic.NDFrame.rank().
test_basic()
pandas.tests.dtypes.test_dtypes.TestCategoricalDtype.test_basic (self, dtype)
Definition at line 167 of file test_dtypes.py.
test_construction_from_string()
pandas.tests.dtypes.test_dtypes.TestCategoricalDtype.test_construction_from_string (self, dtype)
Definition at line 111 of file test_dtypes.py.
test_constructor_invalid()
pandas.tests.dtypes.test_dtypes.TestCategoricalDtype.test_constructor_invalid (self)
Definition at line 118 of file test_dtypes.py.
test_dtype_specific_categorical_dtype()
pandas.tests.dtypes.test_dtypes.TestCategoricalDtype.test_dtype_specific_categorical_dtype (self)
Definition at line 201 of file test_dtypes.py.
test_equality()
pandas.tests.dtypes.test_dtypes.TestCategoricalDtype.test_equality (self, dtype)
Definition at line 95 of file test_dtypes.py.
test_from_values_or_dtype()
pandas.tests.dtypes.test_dtypes.TestCategoricalDtype.test_from_values_or_dtype (self, values, categories, ordered, dtype, expected)
Definition at line 136 of file test_dtypes.py.
test_from_values_or_dtype_invalid_dtype()
pandas.tests.dtypes.test_dtypes.TestCategoricalDtype.test_from_values_or_dtype_invalid_dtype (self)
Definition at line 155 of file test_dtypes.py.
test_from_values_or_dtype_raises()
pandas.tests.dtypes.test_dtypes.TestCategoricalDtype.test_from_values_or_dtype_raises (self, values, categories, ordered, dtype)
Definition at line 150 of file test_dtypes.py.
test_hash_vs_equality()
pandas.tests.dtypes.test_dtypes.TestCategoricalDtype.test_hash_vs_equality (self, dtype)
Definition at line 89 of file test_dtypes.py.
test_is_boolean()
pandas.tests.dtypes.test_dtypes.TestCategoricalDtype.test_is_boolean (self, categories, expected)
Definition at line 195 of file test_dtypes.py.
test_is_dtype()
pandas.tests.dtypes.test_dtypes.TestCategoricalDtype.test_is_dtype (self, dtype)
Definition at line 160 of file test_dtypes.py.
test_not_string()
pandas.tests.dtypes.test_dtypes.TestCategoricalDtype.test_not_string (self)
Definition at line 207 of file test_dtypes.py.
test_repr()
pandas.tests.dtypes.test_dtypes.TestCategoricalDtype.test_repr (self)
Definition at line 228 of file test_dtypes.py.
test_repr_range_categories()
pandas.tests.dtypes.test_dtypes.TestCategoricalDtype.test_repr_range_categories (self)
Definition at line 211 of file test_dtypes.py.
test_tuple_categories()
pandas.tests.dtypes.test_dtypes.TestCategoricalDtype.test_tuple_categories (self)
Definition at line 181 of file test_dtypes.py.
test_update_dtype()
pandas.tests.dtypes.test_dtypes.TestCategoricalDtype.test_update_dtype (self)
Definition at line 222 of file test_dtypes.py.
Member Data Documentation
c
pandas.tests.dtypes.test_dtypes.TestCategoricalDtype.c = Categorical([0, 1], dtype=dtype1) static
Definition at line 125 of file test_dtypes.py.
Referenced by scipy.interpolate._bsplines.BSpline.__call__(), scipy.interpolate._interpolate._PPolyBase.__call__(), scipy.interpolate._interpolate.NdPPoly.__call__(), scipy.interpolate._interpolate.NdPPoly._antiderivative_inplace(), scipy.interpolate._interpolate.NdPPoly._derivative_inplace(), scipy.interpolate._bsplines.BSpline._ensure_c_contiguous(), scipy.interpolate._interpolate._PPolyBase._ensure_c_contiguous(), scipy.interpolate._polyint.KroghInterpolator._evaluate(), scipy.interpolate._bsplines.BSpline.antiderivative(), scipy.interpolate._interpolate.BPoly.antiderivative(), scipy.interpolate._interpolate.NdPPoly.antiderivative(), scipy.interpolate._interpolate.PPoly.antiderivative(), scipy.interpolate._bsplines.BSpline.construct_fast(), scipy.interpolate._interpolate._PPolyBase.construct_fast(), scipy.interpolate._interpolate.NdPPoly.construct_fast(), scipy.interpolate._bsplines.BSpline.derivative(), scipy.interpolate._interpolate.BPoly.derivative(), scipy.interpolate._interpolate.NdPPoly.derivative(), scipy.interpolate._interpolate.PPoly.derivative(), scipy.interpolate._interpolate._PPolyBase.extend(), scipy.interpolate._interpolate.BPoly.extend(), scipy.interpolate._bsplines.BSpline.integrate(), scipy.interpolate._interpolate.NdPPoly.integrate(), scipy.interpolate._interpolate.PPoly.integrate(), scipy.interpolate._interpolate.NdPPoly.integrate_1d(), scipy.interpolate._interpolate.PPoly.solve(), scipy.interpolate._bsplines.BSpline.tck(), and scipy.linalg.tests.test_blas.TestBLAS3Symm.test_symm_wrong_uplo().
dtype1
pandas.tests.dtypes.test_dtypes.TestCategoricalDtype.dtype1 = CategoricalDtype(["a", "b"], ordered=True) static
Definition at line 123 of file test_dtypes.py.
dtype2
pandas.tests.dtypes.test_dtypes.TestCategoricalDtype.dtype2 = CategoricalDtype(["x", "y"], ordered=False) static
Definition at line 124 of file test_dtypes.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/tests/dtypes/test_dtypes.py