Code Cloning Analysis: axisartist.grid_finder.FixedLocator Class Reference
axisartist.grid_finder.FixedLocator Class Reference
Public Member Functions
__init__ (self, locs)
__call__ (self, v1, v2)
Protected Attributes
_locs = locs
Detailed Description
Definition at line 284 of file grid_finder.py.
Constructor & Destructor Documentation
__init__()
axisartist.grid_finder.FixedLocator.__init__ (self, locs)
Definition at line 285 of file grid_finder.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__call__()
axisartist.grid_finder.FixedLocator.__call__ (self, v1, v2)
Definition at line 288 of file grid_finder.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), and scipy.interpolate._fitpack2.SphereBivariateSpline.ev().
Member Data Documentation
_locs
axisartist.grid_finder.FixedLocator._locs = locs protected
Definition at line 286 of file grid_finder.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/mpl_toolkits/axisartist/grid_finder.py