Code Cloning Analysis: scipy.sparse.linalg._dsolve.tests.test_linsolve.TestFactorized Class Reference
scipy.sparse.linalg._dsolve.tests.test_linsolve.TestFactorized Class Reference
Public Member Functions
setup_method (self)
test_singular_without_umfpack (self)
test_singular_with_umfpack (self)
test_non_singular_without_umfpack (self)
test_non_singular_with_umfpack (self)
test_cannot_factorize_nonsquare_matrix_without_umfpack (self)
test_factorizes_nonsquare_matrix_with_umfpack (self)
test_call_with_incorrectly_sized_matrix_without_umfpack (self)
test_call_with_incorrectly_sized_matrix_with_umfpack (self)
test_call_with_cast_to_complex_without_umfpack (self)
test_call_with_cast_to_complex_with_umfpack (self)
test_assume_sorted_indices_flag (self)
test_bug_8278 (self)
Public Attributes
n = n
A = spdiags((d, 2*d, d[::-1]), (-3, 0, 5), n, n).tocsc()
Protected Member Functions
_check_singular (self)
_check_non_singular (self)
Protected Attributes
_check_singular
Detailed Description
Definition at line 57 of file test_linsolve.py.
Member Function Documentation
_check_non_singular()
scipy.sparse.linalg._dsolve.tests.test_linsolve.TestFactorized._check_non_singular (self) protected
Definition at line 70 of file test_linsolve.py.
_check_singular()
scipy.sparse.linalg._dsolve.tests.test_linsolve.TestFactorized._check_singular (self) protected
Definition at line 65 of file test_linsolve.py.
setup_method()
scipy.sparse.linalg._dsolve.tests.test_linsolve.TestFactorized.setup_method (self)
Definition at line 58 of file test_linsolve.py.
test_assume_sorted_indices_flag()
scipy.sparse.linalg._dsolve.tests.test_linsolve.TestFactorized.test_assume_sorted_indices_flag (self)
Definition at line 160 of file test_linsolve.py.
test_bug_8278()
scipy.sparse.linalg._dsolve.tests.test_linsolve.TestFactorized.test_bug_8278 (self)
Definition at line 183 of file test_linsolve.py.
test_call_with_cast_to_complex_with_umfpack()
scipy.sparse.linalg._dsolve.tests.test_linsolve.TestFactorized.test_call_with_cast_to_complex_with_umfpack (self)
Definition at line 152 of file test_linsolve.py.
test_call_with_cast_to_complex_without_umfpack()
scipy.sparse.linalg._dsolve.tests.test_linsolve.TestFactorized.test_call_with_cast_to_complex_without_umfpack (self)
Definition at line 143 of file test_linsolve.py.
test_call_with_incorrectly_sized_matrix_with_umfpack()
scipy.sparse.linalg._dsolve.tests.test_linsolve.TestFactorized.test_call_with_incorrectly_sized_matrix_with_umfpack (self)
Definition at line 128 of file test_linsolve.py.
test_call_with_incorrectly_sized_matrix_without_umfpack()
scipy.sparse.linalg._dsolve.tests.test_linsolve.TestFactorized.test_call_with_incorrectly_sized_matrix_without_umfpack (self)
Definition at line 112 of file test_linsolve.py.
test_cannot_factorize_nonsquare_matrix_without_umfpack()
scipy.sparse.linalg._dsolve.tests.test_linsolve.TestFactorized.test_cannot_factorize_nonsquare_matrix_without_umfpack (self)
Definition at line 100 of file test_linsolve.py.
test_factorizes_nonsquare_matrix_with_umfpack()
scipy.sparse.linalg._dsolve.tests.test_linsolve.TestFactorized.test_factorizes_nonsquare_matrix_with_umfpack (self)
Definition at line 107 of file test_linsolve.py.
test_non_singular_with_umfpack()
scipy.sparse.linalg._dsolve.tests.test_linsolve.TestFactorized.test_non_singular_with_umfpack (self)
Definition at line 96 of file test_linsolve.py.
test_non_singular_without_umfpack()
scipy.sparse.linalg._dsolve.tests.test_linsolve.TestFactorized.test_non_singular_without_umfpack (self)
Definition at line 91 of file test_linsolve.py.
test_singular_with_umfpack()
scipy.sparse.linalg._dsolve.tests.test_linsolve.TestFactorized.test_singular_with_umfpack (self)
Definition at line 85 of file test_linsolve.py.
test_singular_without_umfpack()
scipy.sparse.linalg._dsolve.tests.test_linsolve.TestFactorized.test_singular_without_umfpack (self)
Definition at line 79 of file test_linsolve.py.
Member Data Documentation
_check_singular
scipy.sparse.linalg._dsolve.tests.test_linsolve.TestFactorized._check_singular protected
Definition at line 89 of file test_linsolve.py.
A
scipy.sparse.linalg._dsolve.tests.test_linsolve.TestFactorized.A = spdiags((d, 2*d, d[::-1]), (-3, 0, 5), n, n).tocsc()
Definition at line 62 of file test_linsolve.py.
Referenced by scipy.sparse.linalg._matfuncs._ExpmPadeHelper.__init__(), scipy.sparse.linalg.tests.test_onenormest.MatrixProductOperator._matmat(), scipy.sparse.linalg._eigen.tests.test_svds.CheckingLinearOperator._matvec(), scipy.sparse.linalg.tests.test_onenormest.MatrixProductOperator._matvec(), scipy.sparse.linalg._eigen.tests.test_svds.CheckingLinearOperator._rmatvec(), and scipy.sparse.linalg.tests.test_onenormest.MatrixProductOperator._rmatvec().
n
scipy.sparse.linalg._dsolve.tests.test_linsolve.TestFactorized.n = n
Definition at line 61 of file test_linsolve.py.
Referenced by scipy.stats._morestats._ABW.__init__(), scipy.stats._morestats._ABW._recalc(), scipy.stats._kde.gaussian_kde.integrate_kde(), scipy.stats._kde.gaussian_kde.marginal(), scipy.stats._binomtest.BinomTestResult.proportion_ci(), and scipy.stats._kde.gaussian_kde.resample().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/sparse/linalg/_dsolve/tests/test_linsolve.py