Code Cloning Analysis: sklearn.covariance._graph_lasso Namespace Reference
sklearn.covariance._graph_lasso Namespace Reference
Classes
class BaseGraphicalLasso
class GraphicalLasso
class GraphicalLassoCV
Functions
_objective (mle, precision_, alpha)
_dual_gap (emp_cov, precision_, alpha)
_graphical_lasso (emp_cov, alpha, *, cov_init=None, mode="cd", tol=1e-4, enet_tol=1e-4, max_iter=100, verbose=False, eps=np.finfo(np.float64).eps)
alpha_max (emp_cov)
graphical_lasso (emp_cov, alpha, *, mode="cd", tol=1e-4, enet_tol=1e-4, max_iter=100, verbose=False, return_costs=False, eps=np.finfo(np.float64).eps, return_n_iter=False)
graphical_lasso_path (X, alphas, cov_init=None, X_test=None, mode="cd", tol=1e-4, enet_tol=1e-4, max_iter=100, verbose=False, eps=np.finfo(np.float64).eps)
Detailed Description
GraphicalLasso: sparse inverse covariance estimation with an l1-penalized
estimator.
Function Documentation
_dual_gap()
sklearn.covariance._graph_lasso._dual_gap (emp_cov, precision_, alpha) protected
Expression of the dual gap convergence criterion
The specific definition is given in Duchi "Projected Subgradient Methods
for Learning Sparse Gaussians".
Definition at line 58 of file _graph_lasso.py.
References _dual_gap(), and _objective().
Referenced by _dual_gap().
_graphical_lasso()
sklearn.covariance._graph_lasso._graphical_lasso (emp_cov, alpha, * , cov_init = None, mode = "cd", tol = 1e-4, enet_tol = 1e-4, max_iter = 100, verbose = False, eps = np.finfo(np.float64).eps) protected
Definition at line 71 of file _graph_lasso.py.
_objective()
sklearn.covariance._graph_lasso._objective (mle, precision_, alpha) protected
Evaluation of the graphical-lasso objective function
the objective function is made of a shifted scaled version of the
normalized log-likelihood (i.e. its empirical mean over the samples) and a
penalisation term to promote sparsity
Definition at line 45 of file _graph_lasso.py.
Referenced by _dual_gap().
alpha_max()
sklearn.covariance._graph_lasso.alpha_max (emp_cov)
Find the maximum alpha for which there are some non-zeros off-diagonal.
Parameters
----------
emp_cov : ndarray of shape (n_features, n_features)
    The sample covariance matrix.
Notes
-----
This results from the bound for the all the Lasso that are solved
in GraphicalLasso: each time, the row of cov corresponds to Xy. As the
bound for alpha is given by `max(abs(Xy))`, the result follows.
Definition at line 204 of file _graph_lasso.py.
Referenced by sklearn.covariance._graph_lasso.GraphicalLassoCV.fit().
graphical_lasso()
sklearn.covariance._graph_lasso.graphical_lasso (emp_cov, alpha, * , mode = "cd", tol = 1e-4, enet_tol = 1e-4, max_iter = 100, verbose = False, return_costs = False, eps = np.finfo(np.float64).eps, return_n_iter = False)
L1-penalized covariance estimator.
Read more in the :ref:`User Guide <sparse_inverse_covariance>`.
.. versionchanged:: v0.20
    graph_lasso has been renamed to graphical_lasso
Parameters
----------
emp_cov : array-like of shape (n_features, n_features)
    Empirical covariance from which to compute the covariance estimate.
alpha : float
    The regularization parameter: the higher alpha, the more
    regularization, the sparser the inverse covariance.
    Range is (0, inf].
mode : {'cd', 'lars'}, default='cd'
    The Lasso solver to use: coordinate descent or LARS. Use LARS for
    very sparse underlying graphs, where p > n. Elsewhere prefer cd
    which is more numerically stable.
tol : float, default=1e-4
    The tolerance to declare convergence: if the dual gap goes below
    this value, iterations are stopped. Range is (0, inf].
enet_tol : float, default=1e-4
    The tolerance for the elastic net solver used to calculate the descent
    direction. This parameter controls the accuracy of the search direction
    for a given column update, not of the overall parameter estimate. Only
    used for mode='cd'. Range is (0, inf].
max_iter : int, default=100
    The maximum number of iterations.
verbose : bool, default=False
    If verbose is True, the objective function and dual gap are
    printed at each iteration.
return_costs : bool, default=False
    If return_costs is True, the objective function and dual gap
    at each iteration are returned.
eps : float, default=eps
    The machine-precision regularization in the computation of the
    Cholesky diagonal factors. Increase this for very ill-conditioned
    systems. Default is `np.finfo(np.float64).eps`.
return_n_iter : bool, default=False
    Whether or not to return the number of iterations.
Returns
-------
covariance : ndarray of shape (n_features, n_features)
    The estimated covariance matrix.
precision : ndarray of shape (n_features, n_features)
    The estimated (sparse) precision matrix.
costs : list of (objective, dual_gap) pairs
    The list of values of the objective function and the dual gap at
    each iteration. Returned only if return_costs is True.
n_iter : int
    Number of iterations. Returned only if `return_n_iter` is set to True.
See Also
--------
GraphicalLasso : Sparse inverse covariance estimation
    with an l1-penalized estimator.
GraphicalLassoCV : Sparse inverse covariance with
    cross-validated choice of the l1 penalty.
Notes
-----
The algorithm employed to solve this problem is the GLasso algorithm,
from the Friedman 2008 Biostatistics paper. It is the same algorithm
as in the R `glasso` package.
One possible difference with the `glasso` R package is that the
diagonal coefficients are not penalized.
Examples
--------
>>> import numpy as np
>>> from sklearn.datasets import make_sparse_spd_matrix
>>> from sklearn.covariance import empirical_covariance, graphical_lasso
>>> true_cov = make_sparse_spd_matrix(n_dim=3,random_state=42)
>>> rng = np.random.RandomState(42)
>>> X = rng.multivariate_normal(mean=np.zeros(3), cov=true_cov, size=3)
>>> emp_cov = empirical_covariance(X, assume_centered=True)
>>> emp_cov, _ = graphical_lasso(emp_cov, alpha=0.05)
>>> emp_cov
array([[ 1.687,  0.212, -0.209],
       [ 0.212,  0.221, -0.0817],
       [-0.209, -0.0817, 0.232]])
Definition at line 231 of file _graph_lasso.py.
graphical_lasso_path()
sklearn.covariance._graph_lasso.graphical_lasso_path (X, alphas, cov_init = None, X_test = None, mode = "cd", tol = 1e-4, enet_tol = 1e-4, max_iter = 100, verbose = False, eps = np.finfo(np.float64).eps)
l1-penalized covariance estimator along a path of decreasing alphas
Read more in the :ref:`User Guide <sparse_inverse_covariance>`.
Parameters
----------
X : ndarray of shape (n_samples, n_features)
    Data from which to compute the covariance estimate.
alphas : array-like of shape (n_alphas,)
    The list of regularization parameters, decreasing order.
cov_init : array of shape (n_features, n_features), default=None
    The initial guess for the covariance.
X_test : array of shape (n_test_samples, n_features), default=None
    Optional test matrix to measure generalisation error.
mode : {'cd', 'lars'}, default='cd'
    The Lasso solver to use: coordinate descent or LARS. Use LARS for
    very sparse underlying graphs, where p > n. Elsewhere prefer cd
    which is more numerically stable.
tol : float, default=1e-4
    The tolerance to declare convergence: if the dual gap goes below
    this value, iterations are stopped. The tolerance must be a positive
    number.
enet_tol : float, default=1e-4
    The tolerance for the elastic net solver used to calculate the descent
    direction. This parameter controls the accuracy of the search direction
    for a given column update, not of the overall parameter estimate. Only
    used for mode='cd'. The tolerance must be a positive number.
max_iter : int, default=100
    The maximum number of iterations. This parameter should be a strictly
    positive integer.
verbose : int or bool, default=False
    The higher the verbosity flag, the more information is printed
    during the fitting.
eps : float, default=eps
    The machine-precision regularization in the computation of the
    Cholesky diagonal factors. Increase this for very ill-conditioned
    systems. Default is `np.finfo(np.float64).eps`.
    .. versionadded:: 1.3
Returns
-------
covariances_ : list of shape (n_alphas,) of ndarray of shape \
        (n_features, n_features)
    The estimated covariance matrices.
precisions_ : list of shape (n_alphas,) of ndarray of shape \
        (n_features, n_features)
    The estimated (sparse) precision matrices.
scores_ : list of shape (n_alphas,), dtype=float
    The generalisation error (log-likelihood) on the test data.
    Returned only if test data is passed.
Definition at line 587 of file _graph_lasso.py.