Code Cloning Analysis: pandas.core.util.hashing Namespace Reference
pandas.core.util.hashing Namespace Reference
Functions
npt.NDArray[np.uint64] combine_hash_arrays (Iterator[np.ndarray] arrays, int num_items)
Series hash_pandas_object (Index|DataFrame|Series obj, bool index=True, str encoding="utf8", str|None hash_key=_default_hash_key, bool categorize=True)
npt.NDArray[np.uint64] hash_tuples (MultiIndex|Iterable[tuple[Hashable,...]] vals, str encoding="utf8", str hash_key=_default_hash_key)
npt.NDArray[np.uint64] hash_array (ArrayLike vals, str encoding="utf8", str hash_key=_default_hash_key, bool categorize=True)
npt.NDArray[np.uint64] _hash_ndarray (np.ndarray vals, str encoding="utf8", str hash_key=_default_hash_key, bool categorize=True)
Variables
str _default_hash_key = "0123456789123456"
Detailed Description
data hash pandas / numpy objects
Function Documentation
_hash_ndarray()
npt.NDArray[np.uint64] pandas.core.util.hashing._hash_ndarray (np.ndarray vals, str encoding = "utf8", str hash_key = _default_hash_key, bool categorize = True) protected
See hash_array.__doc__.
Definition at line 282 of file hashing.py.
References _hash_ndarray().
Referenced by _hash_ndarray(), and hash_array().
combine_hash_arrays()
npt.NDArray[np.uint64] pandas.core.util.hashing.combine_hash_arrays (Iterator[np.ndarray] arrays, int num_items)
Parameters
----------
arrays : Iterator[np.ndarray]
num_items : int
Returns
-------
np.ndarray[uint64]
Should be the same as CPython's tupleobject.c
Definition at line 47 of file hashing.py.
Referenced by hash_pandas_object(), and hash_tuples().
hash_array()
npt.NDArray[np.uint64] pandas.core.util.hashing.hash_array (ArrayLike vals, str encoding = "utf8", str hash_key = _default_hash_key, bool categorize = True)
Given a 1d array, return an array of deterministic integers.
Parameters
----------
vals : ndarray or ExtensionArray
encoding : str, default 'utf8'
    Encoding for data & key when strings.
hash_key : str, default _default_hash_key
    Hash_key for string key to encode.
categorize : bool, default True
    Whether to first categorize object arrays before hashing. This is more
    efficient when the array contains duplicate values.
Returns
-------
ndarray[np.uint64, ndim=1]
    Hashed values, same length as the vals.
Examples
--------
>>> pd.util.hash_array(np.array([1, 2, 3]))
array([ 6238072747940578789, 15839785061582574730,  2185194620014831856],
  dtype=uint64)
Definition at line 233 of file hashing.py.
References _hash_ndarray().
Referenced by hash_pandas_object().
hash_pandas_object()
Series pandas.core.util.hashing.hash_pandas_object (Index | DataFrame | Series obj, bool index = True, str encoding = "utf8", str | None hash_key = _default_hash_key, bool categorize = True)
Return a data hash of the Index/Series/DataFrame.
Parameters
----------
obj : Index, Series, or DataFrame
index : bool, default True
    Include the index in the hash (if Series/DataFrame).
encoding : str, default 'utf8'
    Encoding for data & key when strings.
hash_key : str, default _default_hash_key
    Hash_key for string key to encode.
categorize : bool, default True
    Whether to first categorize object arrays before hashing. This is more
    efficient when the array contains duplicate values.
Returns
-------
Series of uint64, same length as the object
Examples
--------
>>> pd.util.hash_pandas_object(pd.Series([1, 2, 3]))
0    14639053686158035780
1     3869563279212530728
2      393322362522515241
dtype: uint64
Definition at line 83 of file hashing.py.
References combine_hash_arrays(), hash_array(), hash_pandas_object(), and hash_tuples().
Referenced by hash_pandas_object().
hash_tuples()
npt.NDArray[np.uint64] pandas.core.util.hashing.hash_tuples (MultiIndex | Iterable[tuple[Hashable, ...]] vals, str encoding = "utf8", str hash_key = _default_hash_key)
Hash an MultiIndex / listlike-of-tuples efficiently.
Parameters
----------
vals : MultiIndex or listlike-of-tuples
encoding : str, default 'utf8'
hash_key : str, default _default_hash_key
Returns
-------
ndarray[np.uint64] of hashed values
Definition at line 183 of file hashing.py.
References combine_hash_arrays().
Referenced by hash_pandas_object().
Variable Documentation
_default_hash_key
str pandas.core.util.hashing._default_hash_key = "0123456789123456" protected
Definition at line 44 of file hashing.py.