Code Cloning Analysis: scipy.optimize.tests.test_zeros.TestNewton Class Reference
scipy.optimize.tests.test_zeros.TestNewton Class Reference
Public Member Functions
test_newton_collections (self)
test_halley_collections (self)
test_newton (self)
test_newton_by_name (self)
test_secant_by_name (self)
test_halley_by_name (self)
test_root_scalar_fail (self)
test_array_newton (self)
test_array_newton_complex (self)
test_array_secant_active_zero_der (self)
test_array_newton_integers (self)
test_array_newton_zero_der_failures (self)
test_newton_combined (self)
test_newton_full_output (self)
test_deriv_zero_warning (self)
test_newton_does_not_modify_x0 (self)
test_gh17570_defaults (self)
test_int_x0_gh19280 (self, method)
Public Member Functions inherited from scipy.optimize.tests.test_zeros.TestScalarRootFinders
run_tests (self, tests, method, name, known_fail=None, **kwargs)
run_collection (self, collection, method, name, smoothness=None, known_fail=None, **kwargs)
Additional Inherited Members
Static Public Attributes inherited from scipy.optimize.tests.test_zeros.TestScalarRootFinders
int xtol = 4 * np.finfo(float).eps
int rtol = 4 * np.finfo(float).eps
Protected Member Functions inherited from scipy.optimize.tests.test_zeros.TestScalarRootFinders
_run_one_test (self, tc, method, sig_args_keys=None, sig_kwargs_keys=None, **kwargs)
Detailed Description
Definition at line 208 of file test_zeros.py.
Member Function Documentation
test_array_newton()
scipy.optimize.tests.test_zeros.TestNewton.test_array_newton (self)
test newton with array
Definition at line 271 of file test_zeros.py.
test_array_newton_complex()
scipy.optimize.tests.test_zeros.TestNewton.test_array_newton_complex (self)
Definition at line 310 of file test_zeros.py.
test_array_newton_integers()
scipy.optimize.tests.test_zeros.TestNewton.test_array_newton_integers (self)
Definition at line 335 of file test_zeros.py.
test_array_newton_zero_der_failures()
scipy.optimize.tests.test_zeros.TestNewton.test_array_newton_zero_der_failures (self)
Definition at line 344 of file test_zeros.py.
test_array_secant_active_zero_der()
scipy.optimize.tests.test_zeros.TestNewton.test_array_secant_active_zero_der (self)
test secant doesn't continue to iterate zero derivatives
Definition at line 329 of file test_zeros.py.
References scipy.optimize._zeros_py.newton(), and scipy.optimize._root_scalar.root_scalar().
test_deriv_zero_warning()
scipy.optimize.tests.test_zeros.TestNewton.test_deriv_zero_warning (self)
Definition at line 414 of file test_zeros.py.
test_gh17570_defaults()
scipy.optimize.tests.test_zeros.TestNewton.test_gh17570_defaults (self)
Definition at line 430 of file test_zeros.py.
test_halley_by_name()
scipy.optimize.tests.test_zeros.TestNewton.test_halley_by_name (self)
Invoke halley through root_scalar()
Definition at line 256 of file test_zeros.py.
References scipy.optimize._root_scalar.root_scalar().
test_halley_collections()
scipy.optimize.tests.test_zeros.TestNewton.test_halley_collections (self)
Definition at line 216 of file test_zeros.py.
test_int_x0_gh19280()
scipy.optimize.tests.test_zeros.TestNewton.test_int_x0_gh19280 (self, method)
Definition at line 460 of file test_zeros.py.
test_newton()
scipy.optimize.tests.test_zeros.TestNewton.test_newton (self)
Definition at line 225 of file test_zeros.py.
test_newton_by_name()
scipy.optimize.tests.test_zeros.TestNewton.test_newton_by_name (self)
Invoke newton through root_scalar()
Definition at line 236 of file test_zeros.py.
References scipy.optimize._root_scalar.root_scalar().
test_newton_collections()
scipy.optimize.tests.test_zeros.TestNewton.test_newton_collections (self)
Definition at line 209 of file test_zeros.py.
test_newton_combined()
scipy.optimize.tests.test_zeros.TestNewton.test_newton_combined (self)
Definition at line 356 of file test_zeros.py.
test_newton_does_not_modify_x0()
scipy.optimize.tests.test_zeros.TestNewton.test_newton_does_not_modify_x0 (self)
Definition at line 423 of file test_zeros.py.
test_newton_full_output()
scipy.optimize.tests.test_zeros.TestNewton.test_newton_full_output (self)
Definition at line 377 of file test_zeros.py.
test_root_scalar_fail()
scipy.optimize.tests.test_zeros.TestNewton.test_root_scalar_fail (self)
Definition at line 263 of file test_zeros.py.
test_secant_by_name()
scipy.optimize.tests.test_zeros.TestNewton.test_secant_by_name (self)
Invoke secant through root_scalar()
Definition at line 245 of file test_zeros.py.
References scipy.optimize._root_scalar.root_scalar().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/optimize/tests/test_zeros.py