Code Cloning Analysis: sklearn.externals.array_api_extra._lib._utils._helpers Namespace Reference
sklearn.externals.array_api_extra._lib._utils._helpers Namespace Reference
Functions
Array in1d (Array x1, Array x2, *, bool assume_unique=False, bool invert=False, ModuleType|None xp=None)
Array mean (Array x, *, int|tuple[int,...]|None axis=None, bool keepdims=False, ModuleType|None xp=None)
TypeIs[complex] is_python_scalar (object x)
tuple[Array, Array] asarrays (Array|complex a, Array|complex b, ModuleType xp)
Generator[tuple[int,...]] ndindex (*int x)
tuple[int,...] eager_shape (Array x)
ModuleType meta_namespace (*Array|complex|None arrays, ModuleType|None xp=None)
Variables
list __all__
Detailed Description
Helper functions used by `array_api_extra/_funcs.py`.
Function Documentation
asarrays()
tuple[Array, Array] sklearn.externals.array_api_extra._lib._utils._helpers.asarrays (Array | complex a, Array | complex b, ModuleType xp)
Ensure both `a` and `b` are arrays.
If `b` is a python scalar, it is converted to the same dtype as `a`, and vice versa.
Behavior is not specified when mixing a Python ``float`` and an array with an
integer data type; this may give ``float32``, ``float64``, or raise an exception.
Behavior is implementation-specific.
Similarly, behavior is not specified when mixing a Python ``complex`` and an array
with a real-valued data type; this may give ``complex64``, ``complex128``, or raise
an exception. Behavior is implementation-specific.
Parameters
----------
a, b : Array | int | float | complex | bool
    Input arrays or scalars. At least one must be an array.
xp : array_namespace, optional
    The standard-compatible namespace for `x`. Default: infer.
Returns
-------
Array, Array
    The input arrays, possibly converted to arrays if they were scalars.
See Also
--------
mixing-arrays-with-python-scalars : Array API specification for the behavior.
Definition at line 127 of file _helpers.py.
References is_python_scalar().
eager_shape()
tuple[int, ...] sklearn.externals.array_api_extra._lib._utils._helpers.eager_shape (Array x)
Return shape of an array. Raise if shape is not fully defined.
Parameters
----------
x : Array
    Input array.
Returns
-------
tuple[int, ...]
    Shape of the array.
Definition at line 224 of file _helpers.py.
Referenced by in1d().
in1d()
Array sklearn.externals.array_api_extra._lib._utils._helpers.in1d (Array x1, Array x2, * , bool assume_unique = False, bool invert = False, ModuleType | None xp = None)
Check whether each element of an array is also present in a second array.
Returns a boolean array the same length as `x1` that is True
where an element of `x1` is in `x2` and False otherwise.
This function has been adapted using the original implementation
present in numpy:
https://github.com/numpy/numpy/blob/v1.26.0/numpy/lib/arraysetops.py#L524-L758
Definition at line 34 of file _helpers.py.
References eager_shape().
is_python_scalar()
TypeIs[complex] sklearn.externals.array_api_extra._lib._utils._helpers.is_python_scalar (object x)
Return True if `x` is a Python scalar, False otherwise.
Definition at line 119 of file _helpers.py.
Referenced by asarrays().
mean()
Array sklearn.externals.array_api_extra._lib._utils._helpers.mean (Array x, * , int | tuple[int, ...] | None axis = None, bool keepdims = False, ModuleType | None xp = None)
Complex mean, https://github.com/data-apis/array-api/issues/846.
Definition at line 96 of file _helpers.py.
meta_namespace()
ModuleType sklearn.externals.array_api_extra._lib._utils._helpers.meta_namespace (*Array | complex | None arrays, ModuleType | None xp = None)
Get the namespace of Dask chunks.
On all other backends, just return the namespace of the arrays.
Parameters
----------
*arrays : Array | int | float | complex | bool | None
    Input arrays.
xp : array_namespace, optional
    The standard-compatible namespace for the input arrays. Default: infer.
Returns
-------
array_namespace
    If xp is Dask, the namespace of the Dask chunks;
    otherwise, the namespace of the arrays.
Definition at line 246 of file _helpers.py.
ndindex()
Generator[tuple[int, ...]] sklearn.externals.array_api_extra._lib._utils._helpers.ndindex (*int x)
Generate all N-dimensional indices for a given array shape.
Given the shape of an array, an ndindex instance iterates over the N-dimensional
index of the array. At each iteration a tuple of indices is returned, the last
dimension is iterated over first.
This has an identical API to numpy.ndindex.
Parameters
----------
*x : int
    The shape of the array.
Definition at line 201 of file _helpers.py.
References ndindex().
Referenced by ndindex().
Variable Documentation
__all__
list sklearn.externals.array_api_extra._lib._utils._helpers.__all__ private
Initial value:
=  [
    "asarrays",
    "eager_shape",
    "in1d",
    "is_python_scalar",
    "mean",
    "meta_namespace",
]
Definition at line 24 of file _helpers.py.