Code Cloning Analysis: matplotlib.scale Namespace Reference
matplotlib.scale Namespace Reference
Classes
class AsinhScale
class AsinhTransform
class FuncScale
class FuncScaleLog
class FuncTransform
class InvertedAsinhTransform
class InvertedLogTransform
class InvertedSymmetricalLogTransform
class LinearScale
class LogisticTransform
class LogitScale
class LogitTransform
class LogScale
class LogTransform
class ScaleBase
class SymmetricalLogScale
class SymmetricalLogTransform
Functions
get_scale_names ()
scale_factory (scale, axis, **kwargs)
register_scale (scale_class)
_get_scale_docs ()
Variables
dict _scale_mapping
__doc__
scale_type
scale_docs
Detailed Description
Scales define the distribution of data values on an axis, e.g. a log scaling.
The mapping is implemented through `.Transform` subclasses.
The following scales are built-in:
.. _builtin_scales:
============= ===================== ================================ =================================
Name          Class                 Transform                        Inverted transform
============= ===================== ================================ =================================
"asinh"       `AsinhScale`          `AsinhTransform`                 `InvertedAsinhTransform`
"function"    `FuncScale`           `FuncTransform`                  `FuncTransform`
"functionlog" `FuncScaleLog`        `FuncTransform` + `LogTransform` `InvertedLogTransform` + `FuncTransform`
"linear"      `LinearScale`         `.IdentityTransform`             `.IdentityTransform`
"log"         `LogScale`            `LogTransform`                   `InvertedLogTransform`
"logit"       `LogitScale`          `LogitTransform`                 `LogisticTransform`
"symlog"      `SymmetricalLogScale` `SymmetricalLogTransform`        `InvertedSymmetricalLogTransform`
============= ===================== ================================ =================================
A user will often only use the scale name, e.g. when setting the scale through
`~.Axes.set_xscale`: ``ax.set_xscale("log")``.
See also the :ref:`scales examples <sphx_glr_gallery_scales>` in the documentation.
Custom scaling can be achieved through `FuncScale`, or by creating your own
`ScaleBase` subclass and corresponding transforms (see :doc:`/gallery/scales/custom_scale`).
Third parties can register their scales by name through `register_scale`.
Function Documentation
_get_scale_docs()
matplotlib.scale._get_scale_docs () protected
Helper function for generating docstrings related to scales.
Definition at line 748 of file scale.py.
References _get_scale_docs(), and get_scale_names().
Referenced by _get_scale_docs().
get_scale_names()
matplotlib.scale.get_scale_names ()
Return the names of the available scales.
Definition at line 713 of file scale.py.
Referenced by _get_scale_docs(), and scale_factory().
register_scale()
matplotlib.scale.register_scale (scale_class)
Register a new kind of scale.
Parameters
----------
scale_class : subclass of `ScaleBase`
    The scale to register.
Definition at line 736 of file scale.py.
scale_factory()
matplotlib.scale.scale_factory (scale, axis, ** kwargs)
Return a scale class by name.
Parameters
----------
scale : {%(names)s}
axis : `~matplotlib.axis.Axis`
Definition at line 718 of file scale.py.
References get_scale_names().
Variable Documentation
__doc__
matplotlib.scale.__doc__ private
Definition at line 732 of file scale.py.
_scale_mapping
dict matplotlib.scale._scale_mapping protected
Initial value:
=  {
    'linear': LinearScale,
    'log':    LogScale,
    'symlog': SymmetricalLogScale,
    'asinh':  AsinhScale,
    'logit':  LogitScale,
    'function': FuncScale,
    'functionlog': FuncScaleLog,
    }
Definition at line 702 of file scale.py.
scale_docs
matplotlib.scale.scale_docs
Definition at line 766 of file scale.py.
scale_type
matplotlib.scale.scale_type
Definition at line 765 of file scale.py.