Code Cloning Analysis: joblib.parallel.parallel_backend Class Reference
joblib.parallel.parallel_backend Class Reference
Public Member Functions
__init__ (self, backend, n_jobs=-1, inner_max_num_threads=None, **backend_params)
__enter__ (self)
Public Member Functions inherited from joblib.parallel.parallel_config
__init__ (self, backend=default_parallel_config["backend"], *, n_jobs=default_parallel_config["n_jobs"], verbose=default_parallel_config["verbose"], temp_folder=default_parallel_config["temp_folder"], max_nbytes=default_parallel_config["max_nbytes"], mmap_mode=default_parallel_config["mmap_mode"], prefer=default_parallel_config["prefer"], require=default_parallel_config["require"], inner_max_num_threads=None, **backend_params)
__enter__ (self)
__exit__ (self, type, value, traceback)
unregister (self)
Public Attributes
tuple old_backend_and_jobs = None
tuple new_backend_and_jobs
Public Attributes inherited from joblib.parallel.parallel_config
old_parallel_config = getattr(_backend, "config", default_parallel_config)
Additional Inherited Members
Protected Member Functions inherited from joblib.parallel.parallel_config
_check_backend (self, backend, inner_max_num_threads, **backend_params)
Detailed Description
Change the default backend used by Parallel inside a with block.
.. warning::
    It is advised to use the :class:`~joblib.parallel_config` context
    manager instead, which allows more fine-grained control over the
    backend configuration.
If ``backend`` is a string it must match a previously registered
implementation using the :func:`~register_parallel_backend` function.
By default the following backends are available:
- 'loky': single-host, process-based parallelism (used by default),
- 'threading': single-host, thread-based parallelism,
- 'multiprocessing': legacy single-host, process-based parallelism.
'loky' is recommended to run functions that manipulate Python objects.
'threading' is a low-overhead alternative that is most efficient for
functions that release the Global Interpreter Lock: e.g. I/O-bound code or
CPU-bound code in a few calls to native code that explicitly releases the
GIL. Note that on some rare systems (such as Pyodide),
multiprocessing and loky may not be available, in which case joblib
defaults to threading.
You can also use the `Dask <https://docs.dask.org/en/stable/>`_ joblib
backend to distribute work across machines. This works well with
scikit-learn estimators with the ``n_jobs`` parameter, for example::
>>> import joblib  # doctest: +SKIP
>>> from sklearn.model_selection import GridSearchCV  # doctest: +SKIP
>>> from dask.distributed import Client, LocalCluster # doctest: +SKIP
>>> # create a local Dask cluster
>>> cluster = LocalCluster()  # doctest: +SKIP
>>> client = Client(cluster)  # doctest: +SKIP
>>> grid_search = GridSearchCV(estimator, param_grid, n_jobs=-1)
... # doctest: +SKIP
>>> with joblib.parallel_backend("dask", scatter=[X, y]):  # doctest: +SKIP
...     grid_search.fit(X, y)
It is also possible to use the distributed 'ray' backend for distributing
the workload to a cluster of nodes. To use the 'ray' joblib backend add
the following lines::
 >>> from ray.util.joblib import register_ray  # doctest: +SKIP
 >>> register_ray()  # doctest: +SKIP
 >>> with parallel_backend("ray"):  # doctest: +SKIP
 ...     print(Parallel()(delayed(neg)(i + 1) for i in range(5)))
 [-1, -2, -3, -4, -5]
Alternatively the backend can be passed directly as an instance.
By default all available workers will be used (``n_jobs=-1``) unless the
caller passes an explicit value for the ``n_jobs`` parameter.
This is an alternative to passing a ``backend='backend_name'`` argument to
the :class:`~Parallel` class constructor. It is particularly useful when
calling into library code that uses joblib internally but does not expose
the backend argument in its own API.
>>> from operator import neg
>>> with parallel_backend('threading'):
...     print(Parallel()(delayed(neg)(i + 1) for i in range(5)))
...
[-1, -2, -3, -4, -5]
Joblib also tries to limit the oversubscription by limiting the number of
threads usable in some third-party library threadpools like OpenBLAS, MKL
or OpenMP. The default limit in each worker is set to
``max(cpu_count() // effective_n_jobs, 1)`` but this limit can be
overwritten with the ``inner_max_num_threads`` argument which will be used
to set this limit in the child processes.
.. versionadded:: 0.10
See Also
--------
joblib.parallel_config: context manager to change the backend configuration.
Definition at line 467 of file parallel.py.
Constructor & Destructor Documentation
__init__()
joblib.parallel.parallel_backend.__init__ (self, backend, n_jobs = -1, inner_max_num_threads = None, ** backend_params)
Definition at line 548 of file parallel.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__enter__()
joblib.parallel.parallel_backend.__enter__ (self)
Definition at line 570 of file parallel.py.
Member Data Documentation
new_backend_and_jobs
tuple joblib.parallel.parallel_backend.new_backend_and_jobs
Initial value:
=  (
            self.parallel_config["backend"],
            self.parallel_config["n_jobs"],
        )
Definition at line 565 of file parallel.py.
old_backend_and_jobs
tuple joblib.parallel.parallel_backend.old_backend_and_jobs = None
Definition at line 559 of file parallel.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/joblib/parallel.py