Code Cloning Analysis: pandas.tests.extension.decimal.array.DecimalDtype Class Reference
pandas.tests.extension.decimal.array.DecimalDtype Class Reference
Public Member Functions
None __init__ (self, context=None)
str __repr__ (self)
type_t[DecimalArray] construct_array_type (cls)
Public Member Functions inherited from pandas.core.dtypes.base.ExtensionDtype
str __str__ (self)
bool __eq__ (self, object other)
int __hash__ (self)
bool __ne__ (self, object other)
object na_value (self)
type_t[Any] type (self)
str kind (self)
str name (self)
list[str]|None names (self)
ExtensionArray empty (self, Shape shape)
Self construct_from_string (cls, str string)
bool is_dtype (cls, object dtype)
type_t[Index] index_class (self)
Public Attributes
context = context or decimal.getcontext()
Public Attributes inherited from pandas.core.dtypes.base.ExtensionDtype
name
Protected Member Functions
bool _is_numeric (self)
Protected Member Functions inherited from pandas.core.dtypes.base.ExtensionDtype
bool _is_boolean (self)
DtypeObj|None _get_common_dtype (self, list[DtypeObj] dtypes)
bool _can_hold_na (self)
bool _is_immutable (self)
bool _supports_2d (self)
bool _can_fast_transpose (self)
Additional Inherited Members
Static Protected Attributes inherited from pandas.core.dtypes.base.ExtensionDtype
tuple _metadata = ()
Detailed Description
Definition at line 41 of file array.py.
Constructor & Destructor Documentation
__init__()
None pandas.tests.extension.decimal.array.DecimalDtype.__init__ (self, context = None)
Definition at line 47 of file array.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
__repr__()
str pandas.tests.extension.decimal.array.DecimalDtype.__repr__ (self)
Definition at line 50 of file array.py.
_is_numeric()
bool pandas.tests.extension.decimal.array.DecimalDtype._is_numeric (self) protected
Whether columns with this dtype should be considered numeric.
By default ExtensionDtypes are assumed to be non-numeric.
They'll be excluded from operations that exclude non-numeric
columns, like (groupby) reductions, plotting, etc.
Reimplemented from pandas.core.dtypes.base.ExtensionDtype.
Definition at line 65 of file array.py.
construct_array_type()
type_t[DecimalArray] pandas.tests.extension.decimal.array.DecimalDtype.construct_array_type (cls)
Return the array type associated with this dtype.
Returns
-------
type
Reimplemented from pandas.core.dtypes.base.ExtensionDtype.
Reimplemented in pandas.tests.arrays.test_array.DecimalDtype2.
Definition at line 54 of file array.py.
Member Data Documentation
context
pandas.tests.extension.decimal.array.DecimalDtype.context = context or decimal.getcontext()
Definition at line 48 of file array.py.
Referenced by pip._vendor.distlib.database.Distribution.__init__(), pip._vendor.urllib3.contrib.securetransport.WrappedSocket._custom_validate(), pip._vendor.urllib3.contrib.securetransport.WrappedSocket._set_alpn_protocols(), pip._vendor.urllib3.contrib.securetransport.WrappedSocket._set_ciphers(), pip._vendor.urllib3.contrib.securetransport.WrappedSocket.handshake(), and pip._vendor.distlib.database.Distribution.provides().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/tests/extension/decimal/array.py