Code Cloning Analysis: pandas.core.strings.accessor Namespace Reference
pandas.core.strings.accessor Namespace Reference
Classes
class StringMethods
Functions
Callable[[F], F] forbid_nonstring_types (list[str]|None forbidden, str|None name=None)
_map_and_wrap (str|None name, str|None docstring)
cat_safe (list[npt.NDArray[np.object_]] list_of_columns, str sep)
cat_core (list list_of_columns, str sep)
_result_dtype (arr)
Hashable _get_single_group_name (re.Pattern regex)
list[Hashable] _get_group_names (re.Pattern regex)
DataFrame str_extractall (arr, pat, int flags=0)
Variables
dict _shared_docs = {}
tuple _cpython_optimized_encoders
tuple _cpython_optimized_decoders = _cpython_optimized_encoders + ("utf-16", "utf-32")
Function Documentation
_get_group_names()
list[Hashable] pandas.core.strings.accessor._get_group_names (re.Pattern regex) protected
Get named groups from compiled regex.
Unnamed groups are numbered.
Parameters
----------
regex : compiled regex
Returns
-------
list of column labels
Definition at line 3518 of file accessor.py.
References _get_group_names().
Referenced by _get_group_names(), and pandas.core.strings.accessor.StringMethods.extract().
_get_single_group_name()
Hashable pandas.core.strings.accessor._get_single_group_name (re.Pattern regex) protected
Definition at line 3511 of file accessor.py.
_map_and_wrap()
pandas.core.strings.accessor._map_and_wrap (str | None name, str | None docstring) protected
Definition at line 148 of file accessor.py.
_result_dtype()
pandas.core.strings.accessor._result_dtype (arr) protected
Definition at line 3500 of file accessor.py.
cat_core()
pandas.core.strings.accessor.cat_core (list list_of_columns, str sep)
Auxiliary function for :meth:`str.cat`
Parameters
----------
list_of_columns : list of numpy arrays
    List of arrays to be concatenated with sep;
    these arrays may not contain NaNs!
sep : string
    The separator string for concatenating the columns.
Returns
-------
nd.array
    The concatenation of list_of_columns with sep.
Definition at line 3473 of file accessor.py.
Referenced by cat_safe().
cat_safe()
pandas.core.strings.accessor.cat_safe (list[npt.NDArray[np.object_]] list_of_columns, str sep)
Auxiliary function for :meth:`str.cat`.
Same signature as cat_core, but handles TypeErrors in concatenation, which
happen if the arrays in list_of columns have the wrong dtypes or content.
Parameters
----------
list_of_columns : list of numpy arrays
    List of arrays to be concatenated with sep;
    these arrays may not contain NaNs!
sep : string
    The separator string for concatenating the columns.
Returns
-------
nd.array
    The concatenation of list_of_columns with sep.
Definition at line 3437 of file accessor.py.
References cat_core().
Referenced by pandas.core.strings.accessor.StringMethods.cat().
forbid_nonstring_types()
Callable[[F], F] pandas.core.strings.accessor.forbid_nonstring_types (list[str] | None forbidden, str | None name = None)
Decorator to forbid specific types for a method of StringMethods.
For calling `.str.{method}` on a Series or Index, it is necessary to first
initialize the :class:`StringMethods` object, and then call the method.
However, different methods allow different input types, and so this can not
be checked during :meth:`StringMethods.__init__`, but must be done on a
per-method basis. This decorator exists to facilitate this process, and
make it explicit which (inferred) types are disallowed by the method.
:meth:`StringMethods.__init__` allows the *union* of types its different
methods allow (after skipping NaNs; see :meth:`StringMethods._validate`),
namely: ['string', 'empty', 'bytes', 'mixed', 'mixed-integer'].
The default string types ['string', 'empty'] are allowed for all methods.
For the additional types ['bytes', 'mixed', 'mixed-integer'], each method
then needs to forbid the types it is not intended for.
Parameters
----------
forbidden : list-of-str or None
    List of forbidden non-string types, may be one or more of
    `['bytes', 'mixed', 'mixed-integer']`.
name : str, default None
    Name of the method to use in the error message. By default, this is
    None, in which case the name from the method being wrapped will be
    copied. However, for working with further wrappers (like _pat_wrapper
    and _noarg_wrapper), it is necessary to specify the name.
Returns
-------
func : wrapper
    The method to which the decorator is applied, with an added check that
    enforces the inferred type to not be in the list of forbidden types.
Raises
------
TypeError
    If the inferred type of the underlying data is in `forbidden`.
Definition at line 79 of file accessor.py.
str_extractall()
DataFrame pandas.core.strings.accessor.str_extractall (arr, pat, int flags = 0)
Definition at line 3536 of file accessor.py.
Variable Documentation
_cpython_optimized_decoders
tuple pandas.core.strings.accessor._cpython_optimized_decoders = _cpython_optimized_encoders + ("utf-16", "utf-32") protected
Definition at line 76 of file accessor.py.
_cpython_optimized_encoders
tuple pandas.core.strings.accessor._cpython_optimized_encoders protected
Initial value:
=  (
    "utf-8",
    "utf8",
    "latin-1",
    "latin1",
    "iso-8859-1",
    "mbcs",
    "ascii",
)
Definition at line 67 of file accessor.py.
_shared_docs
dict pandas.core.strings.accessor._shared_docs = {} protected
Definition at line 66 of file accessor.py.