Code Cloning Analysis: dateutil.tz._factories._TzOffsetFactory Class Reference
dateutil.tz._factories._TzOffsetFactory Class Reference
Public Member Functions
__init__ (cls, *args, **kwargs)
__call__ (cls, name, offset)
Public Member Functions inherited from dateutil.tz._factories._TzFactory
instance (cls, *args, **kwargs)
Protected Attributes
_cache_lock = _thread.allocate_lock()
Private Attributes
__instances = weakref.WeakValueDictionary()
__strong_cache = OrderedDict()
int __strong_cache_size = 8
Detailed Description
Definition at line 25 of file _factories.py.
Constructor & Destructor Documentation
__init__()
dateutil.tz._factories._TzOffsetFactory.__init__ (cls, * args, ** kwargs)
Definition at line 26 of file _factories.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__call__()
dateutil.tz._factories._TzOffsetFactory.__call__ (cls, name, offset)
Definition at line 33 of file _factories.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), scipy.interpolate._fitpack2.SphereBivariateSpline.ev(), matplotlib.ticker.Formatter.format_data(), and matplotlib.ticker.LogFormatter.format_data().
Member Data Documentation
__instances
dateutil.tz._factories._TzOffsetFactory.__instances = weakref.WeakValueDictionary() private
Definition at line 27 of file _factories.py.
Referenced by dateutil.tz.tz.tzical.get().
__strong_cache
dateutil.tz._factories._TzOffsetFactory.__strong_cache = OrderedDict() private
Definition at line 28 of file _factories.py.
Referenced by dateutil.tz.tz.tzical.get().
__strong_cache_size
int dateutil.tz._factories._TzOffsetFactory.__strong_cache_size = 8 private
Definition at line 29 of file _factories.py.
Referenced by dateutil.tz.tz.tzical.get().
_cache_lock
dateutil.tz._factories._TzOffsetFactory._cache_lock = _thread.allocate_lock() protected
Definition at line 31 of file _factories.py.
Referenced by dateutil.tz.tz.tzical.get().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/dateutil/tz/_factories.py