Code Cloning Analysis: matplotlib.ticker.SymmetricalLogLocator Class Reference
matplotlib.ticker.SymmetricalLogLocator Class Reference
Public Member Functions
__init__ (self, transform=None, subs=None, linthresh=None, base=None)
set_params (self, subs=None, numticks=None)
__call__ (self)
tick_values (self, vmin, vmax)
view_limits (self, vmin, vmax)
Public Member Functions inherited from matplotlib.ticker.Locator
__call__ (self)
raise_if_exceeds (self, locs)
nonsingular (self, v0, v1)
Public Member Functions inherited from matplotlib.ticker.TickHelper
set_axis (self, axis)
create_dummy_axis (self, **kwargs)
Public Attributes
int numticks = 15
Protected Attributes
_base = transform.base
_linthresh = transform.linthresh
list _subs = [1.0]
Additional Inherited Members
Static Public Attributes inherited from matplotlib.ticker.Locator
int MAXTICKS = 1000
Static Public Attributes inherited from matplotlib.ticker.TickHelper
axis = None
Detailed Description
Place ticks spaced linearly near zero and spaced logarithmically beyond a threshold.
Definition at line 2516 of file ticker.py.
Constructor & Destructor Documentation
__init__()
matplotlib.ticker.SymmetricalLogLocator.__init__ (self, transform = None, subs = None, linthresh = None, base = None)
Parameters
----------
transform : `~.scale.SymmetricalLogTransform`, optional
    If set, defines the *base* and *linthresh* of the symlog transform.
base, linthresh : float, optional
    The *base* and *linthresh* of the symlog transform, as documented
    for `.SymmetricalLogScale`.  These parameters are only used if
    *transform* is not set.
subs : sequence of float, default: [1]
    The multiples of integer powers of the base where ticks are placed,
    i.e., ticks are placed at
    ``[sub * base**i for i in ... for sub in subs]``.
Notes
-----
Either *transform*, or both *base* and *linthresh*, must be given.
Definition at line 2521 of file ticker.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__call__()
matplotlib.ticker.SymmetricalLogLocator.__call__ (self)
Return the locations of the ticks.
Definition at line 2562 of file ticker.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), and scipy.interpolate._fitpack2.SphereBivariateSpline.ev().
set_params()
matplotlib.ticker.SymmetricalLogLocator.set_params (self, subs = None, numticks = None)
Set parameters within this locator.
Reimplemented from matplotlib.ticker.Locator.
Definition at line 2555 of file ticker.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.theta().
tick_values()
matplotlib.ticker.SymmetricalLogLocator.tick_values (self, vmin, vmax)
Return the values of the located ticks given **vmin** and **vmax**.
.. note::
    To get tick locations with the vmin and vmax values defined
    automatically for the associated ``axis`` simply call
    the Locator instance::
        >>> print(type(loc))
        <type 'Locator'>
        >>> print(loc())
        [1, 2, 3, 4]
Reimplemented from matplotlib.ticker.Locator.
Definition at line 2568 of file ticker.py.
view_limits()
matplotlib.ticker.SymmetricalLogLocator.view_limits (self, vmin, vmax)
Try to choose the view limits intelligently.
Reimplemented from matplotlib.ticker.Locator.
Definition at line 2654 of file ticker.py.
Member Data Documentation
_base
matplotlib.ticker.SymmetricalLogLocator._base = transform.base protected
Definition at line 2541 of file ticker.py.
Referenced by pip._vendor.distlib.locators.Page.__init__().
_linthresh
matplotlib.ticker.SymmetricalLogLocator._linthresh = transform.linthresh protected
Definition at line 2542 of file ticker.py.
_subs
list matplotlib.ticker.SymmetricalLogLocator._subs = [1.0] protected
Definition at line 2550 of file ticker.py.
numticks
int matplotlib.ticker.SymmetricalLogLocator.numticks = 15
Definition at line 2553 of file ticker.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/ticker.py