Code Cloning Analysis: pandas.core.array_algos.quantile Namespace Reference
pandas.core.array_algos.quantile Namespace Reference
Functions
ArrayLike quantile_compat (ArrayLike values, npt.NDArray[np.float64] qs, str interpolation)
np.ndarray quantile_with_mask (np.ndarray values, npt.NDArray[np.bool_] mask, fill_value, npt.NDArray[np.float64] qs, str interpolation)
Scalar|np.ndarray _nanpercentile_1d (np.ndarray values, npt.NDArray[np.bool_] mask, npt.NDArray[np.float64] qs, Scalar na_value, str interpolation)
_nanpercentile (np.ndarray values, npt.NDArray[np.float64] qs, *, na_value, npt.NDArray[np.bool_] mask, str interpolation)
Function Documentation
_nanpercentile()
pandas.core.array_algos.quantile._nanpercentile (np.ndarray values, npt.NDArray[np.float64] qs, * , na_value, npt.NDArray[np.bool_] mask, str interpolation) protected
Wrapper for np.percentile that skips missing values.
Parameters
----------
values : np.ndarray[ndim=2]  over which to find quantiles
qs : np.ndarray[float64] of quantile indices to find
na_value : scalar
    value to return for empty or all-null values
mask : np.ndarray[bool]
    locations in values that should be considered missing
interpolation : str
Returns
-------
quantiles : scalar or array
Definition at line 155 of file quantile.py.
References _nanpercentile(), and _nanpercentile_1d().
Referenced by _nanpercentile(), and quantile_with_mask().
_nanpercentile_1d()
Scalar | np.ndarray pandas.core.array_algos.quantile._nanpercentile_1d (np.ndarray values, npt.NDArray[np.bool_] mask, npt.NDArray[np.float64] qs, Scalar na_value, str interpolation) protected
Wrapper for np.percentile that skips missing values, specialized to
1-dimensional case.
Parameters
----------
values : array over which to find quantiles
mask : ndarray[bool]
    locations in values that should be considered missing
qs : np.ndarray[float64] of quantile indices to find
na_value : scalar
    value to return for empty or all-null values
interpolation : str
Returns
-------
quantiles : scalar or array
Definition at line 111 of file quantile.py.
Referenced by _nanpercentile().
quantile_compat()
ArrayLike pandas.core.array_algos.quantile.quantile_compat (ArrayLike values, npt.NDArray[np.float64] qs, str interpolation)
Compute the quantiles of the given values for each quantile in `qs`.
Parameters
----------
values : np.ndarray or ExtensionArray
qs : np.ndarray[float64]
interpolation : str
Returns
-------
np.ndarray or ExtensionArray
Definition at line 20 of file quantile.py.
References quantile_with_mask().
quantile_with_mask()
np.ndarray pandas.core.array_algos.quantile.quantile_with_mask (np.ndarray values, npt.NDArray[np.bool_] mask, fill_value, npt.NDArray[np.float64] qs, str interpolation)
Compute the quantiles of the given values for each quantile in `qs`.
Parameters
----------
values : np.ndarray
    For ExtensionArray, this is _values_for_factorize()[0]
mask : np.ndarray[bool]
    mask = isna(values)
    For ExtensionArray, this is computed before calling _value_for_factorize
fill_value : Scalar
    The value to interpret fill NA entries with
    For ExtensionArray, this is _values_for_factorize()[1]
qs : np.ndarray[float64]
interpolation : str
    Type of interpolation
Returns
-------
np.ndarray
Notes
-----
Assumes values is already 2D.  For ExtensionArray this means np.atleast_2d
has been called on _values_for_factorize()[0]
Quantile is computed along axis=1.
Definition at line 44 of file quantile.py.
References _nanpercentile(), and quantile_with_mask().
Referenced by quantile_compat(), and quantile_with_mask().