Code Cloning Analysis: cycler Namespace Reference
cycler Namespace Reference
Classes
class Cycler
Functions
set[K] _process_keys (Cycler[K, V]|Iterable[dict[K, V]] left, Cycler[K, V]|Iterable[dict[K, V]]|None right)
Cycler[K, V|U] concat (Cycler[K, V] left, Cycler[K, U] right)
Cycler[K, V] cycler (Cycler[K, V] arg)
Cycler[str, V] cycler (**Iterable[V] kwargs)
Cycler[K, V] cycler (K label, Iterable[V] itr)
cycler (*args, **kwargs)
Cycler[K, V] _cycler (K label, Iterable[V] itr)
Variables
str __version__ = "0.12.1"
K = TypeVar("K", bound=Hashable)
L = TypeVar("L", bound=Hashable)
V = TypeVar("V")
U = TypeVar("U")
Detailed Description
Cycler
======
Cycling through combinations of values, producing dictionaries.
You can add cyclers::
    from cycler import cycler
    cc = (cycler(color=list('rgb')) +
          cycler(linestyle=['-', '--', '-.']))
    for d in cc:
        print(d)
Results in::
    {'color': 'r', 'linestyle': '-'}
    {'color': 'g', 'linestyle': '--'}
    {'color': 'b', 'linestyle': '-.'}
You can multiply cyclers::
    from cycler import cycler
    cc = (cycler(color=list('rgb')) *
          cycler(linestyle=['-', '--', '-.']))
    for d in cc:
        print(d)
Results in::
    {'color': 'r', 'linestyle': '-'}
    {'color': 'r', 'linestyle': '--'}
    {'color': 'r', 'linestyle': '-.'}
    {'color': 'g', 'linestyle': '-'}
    {'color': 'g', 'linestyle': '--'}
    {'color': 'g', 'linestyle': '-.'}
    {'color': 'b', 'linestyle': '-'}
    {'color': 'b', 'linestyle': '--'}
    {'color': 'b', 'linestyle': '-.'}
Function Documentation
_cycler()
Cycler[K, V] cycler._cycler (K label, Iterable[V] itr) protected
Create a new `Cycler` object from a property name and iterable of values.
Parameters
----------
label : hashable
    The property key.
itr : iterable
    Finite length iterable of the property values.
Returns
-------
cycler : Cycler
    New `Cycler` for the given property
Definition at line 546 of file __init__.py.
Referenced by cycler.Cycler.__mul__(), cycler.Cycler._from_iter(), concat(), cycler(), and cycler.Cycler.simplify().
_process_keys()
set[K] cycler._process_keys (Cycler[K, V] | Iterable[dict[K, V]] left, Cycler[K, V] | Iterable[dict[K, V]] | None right) protected
Helper function to compose cycler keys.
Parameters
----------
left, right : iterable of dictionaries or None
    The cyclers to be composed.
Returns
-------
keys : set
    The keys in the composition of the two cyclers.
Definition at line 62 of file __init__.py.
Referenced by cycler.Cycler.__iadd__(), cycler.Cycler.__imul__(), and cycler.Cycler.__init__().
concat()
Cycler[K, V | U] cycler.concat (Cycler[K, V] left, Cycler[K, U] right)
Concatenate `Cycler`\s, as if chained using `itertools.chain`.
The keys must match exactly.
Examples
--------
>>> num = cycler('a', range(3))
>>> let = cycler('a', 'abc')
>>> num.concat(let)
cycler('a', [0, 1, 2, 'a', 'b', 'c'])
Returns
-------
`Cycler`
    The concatenated cycler.
Definition at line 88 of file __init__.py.
References _cycler().
cycler() [1/4]
Cycler[str, V] cycler.cycler (**Iterable[V] kwargs)
Definition at line 473 of file __init__.py.
cycler() [2/4]
cycler.cycler (* args, ** kwargs)
Create a new `Cycler` object from a single positional argument,
a pair of positional arguments, or the combination of keyword arguments.
cycler(arg)
cycler(label1=itr1[, label2=iter2[, ...]])
cycler(label, itr)
Form 1 simply copies a given `Cycler` object.
Form 2 composes a `Cycler` as an inner product of the
pairs of keyword arguments. In other words, all of the
iterables are cycled simultaneously, as if through zip().
Form 3 creates a `Cycler` from a label and an iterable.
This is useful for when the label cannot be a keyword argument
(e.g., an integer or a name that has a space in it).
Parameters
----------
arg : Cycler
    Copy constructor for Cycler (does a shallow copy of iterables).
label : name
    The property key. In the 2-arg form of the function,
    the label can be any hashable object. In the keyword argument
    form of the function, it must be a valid python identifier.
itr : iterable
    Finite length iterable of the property values.
    Can be a single-property `Cycler` that would
    be like a key change, but as a shallow copy.
Returns
-------
cycler : Cycler
    New `Cycler` for the given property
Definition at line 482 of file __init__.py.
References _cycler().
cycler() [3/4]
Cycler[K, V] cycler.cycler (Cycler[K, V] arg)
Definition at line 468 of file __init__.py.
cycler() [4/4]
Cycler[K, V] cycler.cycler (K label, Iterable[V] itr)
Definition at line 478 of file __init__.py.
Variable Documentation
__version__
str cycler.__version__ = "0.12.1" private
Definition at line 54 of file __init__.py.
K
cycler.K = TypeVar("K", bound=Hashable)
Definition at line 56 of file __init__.py.
L
cycler.L = TypeVar("L", bound=Hashable)
Definition at line 57 of file __init__.py.
U
cycler.U = TypeVar("U")
Definition at line 59 of file __init__.py.
V
cycler.V = TypeVar("V")
Definition at line 58 of file __init__.py.