Code Cloning Analysis: scipy.sparse._index Namespace Reference
scipy.sparse._index Namespace Reference
Classes
class IndexMixin
Functions
_broadcast_arrays (a, b)
_unpack_index (index)
_check_ellipsis (index)
_maybe_bool_ndarray (idx)
_first_element_bool (idx, max_dim=2)
_compatible_boolean_index (idx)
_boolean_index_to_array (idx)
Variables
tuple INT_TYPES = (int, np.integer)
Detailed Description
Indexing mixin for sparse matrix classes.
Function Documentation
_boolean_index_to_array()
scipy.sparse._index._boolean_index_to_array (idx) protected
Definition at line 381 of file _index.py.
_broadcast_arrays()
scipy.sparse._index._broadcast_arrays (a, b) protected
Same as np.broadcast_arrays(a, b) but old writeability rules.
NumPy >= 1.17.0 transitions broadcast_arrays to return
read-only arrays. Set writeability explicitly to avoid warnings.
Retain the old writeability rules, as our Cython code assumes
the old behavior.
Definition at line 10 of file _index.py.
Referenced by scipy.sparse._index.IndexMixin._getcol(), and scipy.sparse._index.IndexMixin._raise_on_1d_array_slice().
_check_ellipsis()
scipy.sparse._index._check_ellipsis (index) protected
Process indices with Ellipsis. Returns modified index.
Definition at line 310 of file _index.py.
Referenced by _unpack_index().
_compatible_boolean_index()
scipy.sparse._index._compatible_boolean_index (idx) protected
Returns a boolean index array that can be converted to
integer array. Returns None if no such array exists.
Definition at line 371 of file _index.py.
References _first_element_bool(), and _maybe_bool_ndarray().
Referenced by _unpack_index().
_first_element_bool()
scipy.sparse._index._first_element_bool (idx, max_dim = 2) protected
Returns True if first element of the incompatible
array type is boolean.
Definition at line 356 of file _index.py.
References _first_element_bool().
Referenced by _compatible_boolean_index(), and _first_element_bool().
_maybe_bool_ndarray()
scipy.sparse._index._maybe_bool_ndarray (idx) protected
Returns a compatible array if elements are boolean.
Definition at line 347 of file _index.py.
Referenced by _compatible_boolean_index().
_unpack_index()
scipy.sparse._index._unpack_index (index) protected
 Parse index. Always return a tuple of the form (row, col).
Valid type for row/col is integer, slice, or array of integers.
Definition at line 264 of file _index.py.
References _check_ellipsis(), _compatible_boolean_index(), and scipy.sparse._base.issparse().
Referenced by scipy.sparse._index.IndexMixin._raise_on_1d_array_slice().
Variable Documentation
INT_TYPES
tuple scipy.sparse._index.INT_TYPES = (int, np.integer)
Definition at line 7 of file _index.py.