Code Cloning Analysis: numpy.core.tests.test_dtype.TestFromCTypes Class Reference
numpy.core.tests.test_dtype.TestFromCTypes Class Reference
Public Member Functions
test_array (self)
test_padded_structure (self)
test_bit_fields (self)
test_pointer (self)
test_void_pointer (self)
test_union (self)
test_union_with_struct_packed (self)
test_union_packed (self)
test_packed_structure (self)
test_large_packed_structure (self)
test_big_endian_structure_packed (self)
test_little_endian_structure_packed (self)
test_little_endian_structure (self)
test_big_endian_structure (self)
test_simple_endian_types (self)
test_pairs (self, pair)
Static Public Member Functions
check (ctype, dtype)
Static Public Attributes
all_types = set(np.typecodes['All'])
all_pairs = permutations(all_types, 2)
Detailed Description
Definition at line 1636 of file test_dtype.py.
Member Function Documentation
check()
numpy.core.tests.test_dtype.TestFromCTypes.check (ctype, dtype) static
Definition at line 1639 of file test_dtype.py.
Referenced by pandas.tests.indexing.test_floats.TestFloatIndexers.check(), packaging._tokenizer.Tokenizer.consume(), packaging._tokenizer.Tokenizer.expect(), packaging._tokenizer.Tokenizer.raise_syntax_error(), pip._vendor.pygments.scanner.Scanner.test(), and pandas.tests.indexing.test_floats.TestFloatIndexers.test_integer_positional_indexing().
test_array()
numpy.core.tests.test_dtype.TestFromCTypes.test_array (self)
Definition at line 1644 of file test_dtype.py.
test_big_endian_structure()
numpy.core.tests.test_dtype.TestFromCTypes.test_big_endian_structure (self)
Definition at line 1804 of file test_dtype.py.
test_big_endian_structure_packed()
numpy.core.tests.test_dtype.TestFromCTypes.test_big_endian_structure_packed (self)
Definition at line 1772 of file test_dtype.py.
test_bit_fields()
numpy.core.tests.test_dtype.TestFromCTypes.test_bit_fields (self)
Definition at line 1664 of file test_dtype.py.
test_large_packed_structure()
numpy.core.tests.test_dtype.TestFromCTypes.test_large_packed_structure (self)
Definition at line 1753 of file test_dtype.py.
test_little_endian_structure()
numpy.core.tests.test_dtype.TestFromCTypes.test_little_endian_structure (self)
Definition at line 1792 of file test_dtype.py.
test_little_endian_structure_packed()
numpy.core.tests.test_dtype.TestFromCTypes.test_little_endian_structure_packed (self)
Definition at line 1782 of file test_dtype.py.
test_packed_structure()
numpy.core.tests.test_dtype.TestFromCTypes.test_packed_structure (self)
Definition at line 1740 of file test_dtype.py.
test_padded_structure()
numpy.core.tests.test_dtype.TestFromCTypes.test_padded_structure (self)
Definition at line 1652 of file test_dtype.py.
test_pairs()
numpy.core.tests.test_dtype.TestFromCTypes.test_pairs (self, pair)
Check that np.dtype('x,y') matches [np.dtype('x'), np.dtype('y')]
Example: np.dtype('d,I') -> dtype([('f0', '<f8'), ('f1', '<u4')])
Definition at line 1826 of file test_dtype.py.
test_pointer()
numpy.core.tests.test_dtype.TestFromCTypes.test_pointer (self)
Definition at line 1673 of file test_dtype.py.
test_simple_endian_types()
numpy.core.tests.test_dtype.TestFromCTypes.test_simple_endian_types (self)
Definition at line 1816 of file test_dtype.py.
test_union()
numpy.core.tests.test_dtype.TestFromCTypes.test_union (self)
Definition at line 1680 of file test_dtype.py.
test_union_packed()
numpy.core.tests.test_dtype.TestFromCTypes.test_union_packed (self)
Definition at line 1717 of file test_dtype.py.
test_union_with_struct_packed()
numpy.core.tests.test_dtype.TestFromCTypes.test_union_with_struct_packed (self)
Definition at line 1694 of file test_dtype.py.
test_void_pointer()
numpy.core.tests.test_dtype.TestFromCTypes.test_void_pointer (self)
Definition at line 1677 of file test_dtype.py.
Member Data Documentation
all_pairs
numpy.core.tests.test_dtype.TestFromCTypes.all_pairs = permutations(all_types, 2) static
Definition at line 1823 of file test_dtype.py.
all_types
numpy.core.tests.test_dtype.TestFromCTypes.all_types = set(np.typecodes['All']) static
Definition at line 1822 of file test_dtype.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/core/tests/test_dtype.py