Code Cloning Analysis: fontTools.ttLib.tables.otTables.LigatureMorphAction Class Reference
fontTools.ttLib.tables.otTables.LigatureMorphAction Class Reference
Public Member Functions
__init__ (self)
compile (self, writer, font, actionIndex)
decompile (self, reader, font, actionReader)
compileLigActions (self)
fromXML (self, name, attrs, content, font)
toXML (self, xmlWriter, font, attrs, name)
Static Public Member Functions
compileActions (font, states)
Public Attributes
int NewState = 0
bool SetComponent
bool DontAdvance = False, False
int ReservedFlags = 0
list Actions = []
Static Public Attributes
int staticSize = 6
int actionHeaderSize = 12
Protected Member Functions
_decompileLigActions (self, actionReader, actionIndex)
Protected Member Functions inherited from fontTools.ttLib.tables.otTables.AATAction
_writeFlagsToXML (self, xmlWriter)
_setFlag (self, flag)
Additional Inherited Members
Static Protected Attributes inherited from fontTools.ttLib.tables.otTables.AATAction
_FLAGS = None
Detailed Description
Definition at line 636 of file otTables.py.
Constructor & Destructor Documentation
__init__()
fontTools.ttLib.tables.otTables.LigatureMorphAction.__init__ (self)
Definition at line 644 of file otTables.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_decompileLigActions()
fontTools.ttLib.tables.otTables.LigatureMorphAction._decompileLigActions (self, actionReader, actionIndex) protected
Definition at line 723 of file otTables.py.
compile()
fontTools.ttLib.tables.otTables.LigatureMorphAction.compile (self, writer, font, actionIndex)
Definition at line 650 of file otTables.py.
Referenced by fontTools.ttLib.tables.TupleVariation.TupleVariation.getCoordWidth(), and PIL.FontFile.FontFile.save().
compileActions()
fontTools.ttLib.tables.otTables.LigatureMorphAction.compileActions (font, states) static
Reimplemented from fontTools.ttLib.tables.otTables.AATAction.
Definition at line 687 of file otTables.py.
compileLigActions()
fontTools.ttLib.tables.otTables.LigatureMorphAction.compileLigActions (self)
Definition at line 713 of file otTables.py.
decompile()
fontTools.ttLib.tables.otTables.LigatureMorphAction.decompile (self, reader, font, actionReader)
Definition at line 667 of file otTables.py.
Referenced by fontTools.ttLib.tables._c_m_a_p.CmapSubtable.newSubtable().
fromXML()
fontTools.ttLib.tables.otTables.LigatureMorphAction.fromXML (self, name, attrs, content, font)
Definition at line 739 of file otTables.py.
toXML()
fontTools.ttLib.tables.otTables.LigatureMorphAction.toXML (self, xmlWriter, font, attrs, name)
Definition at line 761 of file otTables.py.
Member Data Documentation
actionHeaderSize
int fontTools.ttLib.tables.otTables.LigatureMorphAction.actionHeaderSize = 12 static
Definition at line 640 of file otTables.py.
Actions
fontTools.ttLib.tables.otTables.LigatureMorphAction.Actions = []
Definition at line 648 of file otTables.py.
DontAdvance
bool fontTools.ttLib.tables.otTables.LigatureMorphAction.DontAdvance = False, False
Definition at line 646 of file otTables.py.
NewState
fontTools.ttLib.tables.otTables.LigatureMorphAction.NewState = 0
Definition at line 645 of file otTables.py.
ReservedFlags
int fontTools.ttLib.tables.otTables.LigatureMorphAction.ReservedFlags = 0
Definition at line 647 of file otTables.py.
SetComponent
bool fontTools.ttLib.tables.otTables.LigatureMorphAction.SetComponent
Definition at line 646 of file otTables.py.
staticSize
int fontTools.ttLib.tables.otTables.LigatureMorphAction.staticSize = 6 static
Definition at line 637 of file otTables.py.
Referenced by fontTools.ttLib.tables.otConverters.BaseConverter.readArray().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ttLib/tables/otTables.py