Code Cloning Analysis: scipy.signal._signaltools Namespace Reference
scipy.signal._signaltools Namespace Reference
Functions
_valfrommode (mode)
_bvalfromboundary (boundary)
_inputs_swap_needed (mode, shape1, shape2, axes=None)
correlate (in1, in2, mode='full', method='auto')
correlation_lags (in1_len, in2_len, mode='full')
_centered (arr, newshape)
_init_freq_conv_axes (in1, in2, mode, axes, sorted_axes=False)
_freq_domain_conv (in1, in2, axes, shape, calc_fast_len=False)
_apply_conv_mode (ret, s1, s2, mode, axes)
fftconvolve (in1, in2, mode="full", axes=None)
_calc_oa_lens (s1, s2)
oaconvolve (in1, in2, mode="full", axes=None)
_numeric_arrays (arrays, kinds='buifc')
_conv_ops (x_shape, h_shape, mode)
_fftconv_faster (x, h, mode)
_reverse_and_conj (x)
_np_conv_ok (volume, kernel, mode)
_timeit_fast (stmt="pass", setup="pass", repeat=3)
choose_conv_method (in1, in2, mode='full', measure=False)
convolve (in1, in2, mode='full', method='auto')
order_filter (a, domain, rank)
medfilt (volume, kernel_size=None)
wiener (im, mysize=None, noise=None)
convolve2d (in1, in2, mode='full', boundary='fill', fillvalue=0)
correlate2d (in1, in2, mode='full', boundary='fill', fillvalue=0)
medfilt2d (input, kernel_size=3)
lfilter (b, a, x, axis=-1, zi=None)
lfiltic (b, a, y, x=None)
deconvolve (signal, divisor)
hilbert (x, N=None, axis=-1)
hilbert2 (x, N=None)
cmplx_sort (p)
unique_roots (p, tol=1e-3, rtype='min')
invres (r, p, k, tol=1e-3, rtype='avg')
_compute_factors (roots, multiplicity, include_powers=False)
_compute_residues (poles, multiplicity, numerator)
residue (b, a, tol=1e-3, rtype='avg')
residuez (b, a, tol=1e-3, rtype='avg')
_group_poles (poles, tol, rtype)
invresz (r, p, k, tol=1e-3, rtype='avg')
resample (x, num, t=None, axis=0, window=None, domain='time')
resample_poly (x, up, down, axis=0, window=('kaiser', 5.0), padtype='constant', cval=None)
vectorstrength (events, period)
detrend (data, axis=-1, type='linear', bp=0, overwrite_data=False)
lfilter_zi (b, a)
sosfilt_zi (sos)
_filtfilt_gust (b, a, x, axis=-1, irlen=None)
filtfilt (b, a, x, axis=-1, padtype='odd', padlen=None, method='pad', irlen=None)
_validate_pad (padtype, padlen, x, axis, ntaps)
_validate_x (x)
sosfilt (sos, x, axis=-1, zi=None)
sosfiltfilt (sos, x, axis=-1, padtype='odd', padlen=None)
decimate (x, q, n=None, ftype='iir', axis=-1, zero_phase=True)
Variables
list __all__
dict _modedict = {'valid': 0, 'same': 1, 'full': 2}
dict _boundarydict
Function Documentation
_apply_conv_mode()
scipy.signal._signaltools._apply_conv_mode (ret, s1, s2, mode, axes) protected
Calculate the convolution result shape based on the `mode` argument.
Returns the result sliced to the correct size for the given mode.
Parameters
----------
ret : array
    The result array, with the appropriate shape for the 'full' mode.
s1 : list of int
    The shape of the first input.
s2 : list of int
    The shape of the second input.
mode : str {'full', 'valid', 'same'}
    A string indicating the size of the output.
    See the documentation `fftconvolve` for more information.
axes : list of ints
    Axes over which to compute the convolution.
Returns
-------
ret : array
    A copy of `res`, sliced to the correct size for the given `mode`.
Definition at line 519 of file _signaltools.py.
Referenced by fftconvolve(), and oaconvolve().
_bvalfromboundary()
scipy.signal._signaltools._bvalfromboundary (boundary) protected
Definition at line 49 of file _signaltools.py.
_calc_oa_lens()
scipy.signal._signaltools._calc_oa_lens (s1, s2) protected
Calculate the optimal FFT lengths for overlapp-add convolution.
The calculation is done for a single dimension.
Parameters
----------
s1 : int
    Size of the dimension for the first array.
s2 : int
    Size of the dimension for the second array.
Returns
-------
block_size : int
    The size of the FFT blocks.
overlap : int
    The amount of overlap between two blocks.
in1_step : int
    The size of each step for the first array.
in2_step : int
    The size of each step for the first array.
Definition at line 675 of file _signaltools.py.
Referenced by oaconvolve().
_centered()
scipy.signal._signaltools._centered (arr, newshape) protected
Definition at line 388 of file _signaltools.py.
_compute_factors()
scipy.signal._signaltools._compute_factors (roots, multiplicity, include_powers = False) protected
Compute the total polynomial divided by factors for each root.
Definition at line 2659 of file _signaltools.py.
References _compute_factors().
Referenced by _compute_factors(), invres(), and invresz().
_compute_residues()
scipy.signal._signaltools._compute_residues (poles, multiplicity, numerator) protected
Definition at line 2684 of file _signaltools.py.
_conv_ops()
scipy.signal._signaltools._conv_ops (x_shape, h_shape, mode) protected
Find the number of operations required for direct/fft methods of
convolution. The direct operations were recorded by making a dummy class to
record the number of operations by overriding ``__mul__`` and ``__add__``.
The FFT operations rely on the (well-known) computational complexity of the
FFT (and the implementation of ``_freq_domain_conv``).
Definition at line 1015 of file _signaltools.py.
Referenced by _fftconv_faster().
_fftconv_faster()
scipy.signal._signaltools._fftconv_faster (x, h, mode) protected
See if using fftconvolve or convolve is faster.
Parameters
----------
x : np.ndarray
    Signal
h : np.ndarray
    Kernel
mode : str
    Mode passed to convolve
Returns
-------
fft_faster : bool
Notes
-----
See docstring of `choose_conv_method` for details on tuning hardware.
See pull request 11031 for more detail:
https://github.com/scipy/scipy/pull/11031.
Definition at line 1058 of file _signaltools.py.
References _conv_ops().
Referenced by choose_conv_method().
_filtfilt_gust()
scipy.signal._signaltools._filtfilt_gust (b, a, x, axis = -1, irlen = None) protected
Forward-backward IIR filter that uses Gustafsson's method.
Apply the IIR filter defined by `(b,a)` to `x` twice, first forward
then backward, using Gustafsson's initial conditions [1]_.
Let ``y_fb`` be the result of filtering first forward and then backward,
and let ``y_bf`` be the result of filtering first backward then forward.
Gustafsson's method is to compute initial conditions for the forward
pass and the backward pass such that ``y_fb == y_bf``.
Parameters
----------
b : scalar or 1-D ndarray
    Numerator coefficients of the filter.
a : scalar or 1-D ndarray
    Denominator coefficients of the filter.
x : ndarray
    Data to be filtered.
axis : int, optional
    Axis of `x` to be filtered.  Default is -1.
irlen : int or None, optional
    The length of the nonnegligible part of the impulse response.
    If `irlen` is None, or if the length of the signal is less than
    ``2 * irlen``, then no part of the impulse response is ignored.
Returns
-------
y : ndarray
    The filtered data.
x0 : ndarray
    Initial condition for the forward filter.
x1 : ndarray
    Initial condition for the backward filter.
Notes
-----
Typically the return values `x0` and `x1` are not needed by the
caller.  The intended use of these return values is in unit tests.
References
----------
.. [1] F. Gustaffson. Determining the initial states in forward-backward
       filtering. Transactions on Signal Processing, 46(4):988-992, 1996.
Definition at line 3810 of file _signaltools.py.
References lfilter().
Referenced by filtfilt(), and scipy.signal.tests.test_signaltools.filtfilt_gust_opt().
_freq_domain_conv()
scipy.signal._signaltools._freq_domain_conv (in1, in2, axes, shape, calc_fast_len = False) protected
Convolve two arrays in the frequency domain.
This function implements only base the FFT-related operations.
Specifically, it converts the signals to the frequency domain, multiplies
them, then converts them back to the time domain.  Calculations of axes,
shapes, convolution mode, etc. are implemented in higher level-functions,
such as `fftconvolve` and `oaconvolve`.  Those functions should be used
instead of this one.
Parameters
----------
in1 : array_like
    First input.
in2 : array_like
    Second input. Should have the same number of dimensions as `in1`.
axes : array_like of ints
    Axes over which to compute the FFTs.
shape : array_like of ints
    The sizes of the FFTs.
calc_fast_len : bool, optional
    If `True`, set each value of `shape` to the next fast FFT length.
    Default is `False`, use `axes` as-is.
Returns
-------
out : array
    An N-dimensional array containing the discrete linear convolution of
    `in1` with `in2`.
Definition at line 459 of file _signaltools.py.
Referenced by fftconvolve(), and oaconvolve().
_group_poles()
scipy.signal._signaltools._group_poles (poles, tol, rtype) protected
Definition at line 2931 of file _signaltools.py.
_init_freq_conv_axes()
scipy.signal._signaltools._init_freq_conv_axes (in1, in2, mode, axes, sorted_axes = False) protected
Handle the axes argument for frequency-domain convolution.
Returns the inputs and axes in a standard form, eliminating redundant axes,
swapping the inputs if necessary, and checking for various potential
errors.
Parameters
----------
in1 : array
    First input.
in2 : array
    Second input.
mode : str {'full', 'valid', 'same'}, optional
    A string indicating the size of the output.
    See the documentation `fftconvolve` for more information.
axes : list of ints
    Axes over which to compute the FFTs.
sorted_axes : bool, optional
    If `True`, sort the axes.
    Default is `False`, do not sort.
Returns
-------
in1 : array
    The first input, possible swapped with the second input.
in2 : array
    The second input, possible swapped with the first input.
axes : list of ints
    Axes over which to compute the FFTs.
Definition at line 398 of file _signaltools.py.
References _inputs_swap_needed().
Referenced by fftconvolve(), and oaconvolve().
_inputs_swap_needed()
scipy.signal._signaltools._inputs_swap_needed (mode, shape1, shape2, axes = None) protected
Determine if inputs arrays need to be swapped in `"valid"` mode.
If in `"valid"` mode, returns whether or not the input arrays need to be
swapped depending on whether `shape1` is at least as large as `shape2` in
every calculated dimension.
This is important for some of the correlation and convolution
implementations in this module, where the larger array input needs to come
before the smaller array input when operating in this mode.
Note that if the mode provided is not 'valid', False is immediately
returned.
Definition at line 57 of file _signaltools.py.
Referenced by _init_freq_conv_axes(), convolve(), convolve2d(), correlate(), and correlate2d().
_np_conv_ok()
scipy.signal._signaltools._np_conv_ok (volume, kernel, mode) protected
See if numpy supports convolution of `volume` and `kernel` (i.e. both are
1D ndarrays and of the appropriate shape).  NumPy's 'same' mode uses the
size of the larger input, while SciPy's uses the size of the first input.
Invalid mode strings will return False and be caught by the calling func.
Definition at line 1108 of file _signaltools.py.
Referenced by convolve(), and correlate().
_numeric_arrays()
scipy.signal._signaltools._numeric_arrays (arrays, kinds = 'buifc') protected
See if a list of arrays are all numeric.
Parameters
----------
arrays : array or list of arrays
    arrays to check if numeric.
kinds : string-like
    The dtypes of the arrays to be checked. If the dtype.kind of
    the ndarrays are not in this string the function returns False and
    otherwise returns True.
Definition at line 994 of file _signaltools.py.
Referenced by choose_conv_method().
_reverse_and_conj()
scipy.signal._signaltools._reverse_and_conj (x) protected
Reverse array `x` in all dimensions and perform the complex conjugate
Definition at line 1100 of file _signaltools.py.
Referenced by convolve(), and correlate().
_timeit_fast()
scipy.signal._signaltools._timeit_fast (stmt = "pass", setup = "pass", repeat = 3) protected
Returns the time the statement/function took, in seconds.
Faster, less precise version of IPython's timeit. `stmt` can be a statement
written as a string or a callable.
Will do only 1 loop (like IPython's timeit) with no repetitions
(unlike IPython) for very slow functions.  For fast functions, only does
enough loops to take 5 ms, which seems to produce similar results (on
Windows at least), and avoids doing an extraneous cycle that isn't
measured.
Definition at line 1125 of file _signaltools.py.
Referenced by choose_conv_method().
_valfrommode()
scipy.signal._signaltools._valfrommode (mode) protected
Definition at line 41 of file _signaltools.py.
_validate_pad()
scipy.signal._signaltools._validate_pad (padtype, padlen, x, axis, ntaps) protected
Helper to validate padding for filtfilt
Definition at line 4191 of file _signaltools.py.
Referenced by filtfilt(), and sosfiltfilt().
_validate_x()
scipy.signal._signaltools._validate_x (x) protected
Definition at line 4226 of file _signaltools.py.
choose_conv_method()
scipy.signal._signaltools.choose_conv_method (in1, in2, mode = 'full', measure = False)
Find the fastest convolution/correlation method.
This primarily exists to be called during the ``method='auto'`` option in
`convolve` and `correlate`. It can also be used to determine the value of
``method`` for many different convolutions of the same dtype/shape.
In addition, it supports timing the convolution to adapt the value of
``method`` to a particular set of inputs and/or hardware.
Parameters
----------
in1 : array_like
    The first argument passed into the convolution function.
in2 : array_like
    The second argument passed into the convolution function.
mode : str {'full', 'valid', 'same'}, optional
    A string indicating the size of the output:
    ``full``
       The output is the full discrete linear convolution
       of the inputs. (Default)
    ``valid``
       The output consists only of those elements that do not
       rely on the zero-padding.
    ``same``
       The output is the same size as `in1`, centered
       with respect to the 'full' output.
measure : bool, optional
    If True, run and time the convolution of `in1` and `in2` with both
    methods and return the fastest. If False (default), predict the fastest
    method using precomputed values.
Returns
-------
method : str
    A string indicating which convolution method is fastest, either
    'direct' or 'fft'
times : dict, optional
    A dictionary containing the times (in seconds) needed for each method.
    This value is only returned if ``measure=True``.
See Also
--------
convolve
correlate
Notes
-----
Generally, this method is 99% accurate for 2D signals and 85% accurate
for 1D signals for randomly chosen input sizes. For precision, use
``measure=True`` to find the fastest method by timing the convolution.
This can be used to avoid the minimal overhead of finding the fastest
``method`` later, or to adapt the value of ``method`` to a particular set
of inputs.
Experiments were run on an Amazon EC2 r5a.2xlarge machine to test this
function. These experiments measured the ratio between the time required
when using ``method='auto'`` and the time required for the fastest method
(i.e., ``ratio = time_auto / min(time_fft, time_direct)``). In these
experiments, we found:
* There is a 95% chance of this ratio being less than 1.5 for 1D signals
  and a 99% chance of being less than 2.5 for 2D signals.
* The ratio was always less than 2.5/5 for 1D/2D signals respectively.
* This function is most inaccurate for 1D convolutions that take between 1
  and 10 milliseconds with ``method='direct'``. A good proxy for this
  (at least in our experiments) is ``1e6 <= in1.size * in2.size <= 1e7``.
The 2D results almost certainly generalize to 3D/4D/etc because the
implementation is the same (the 1D implementation is different).
All the numbers above are specific to the EC2 machine. However, we did find
that this function generalizes fairly decently across hardware. The speed
tests were of similar quality (and even slightly better) than the same
tests performed on the machine to tune this function's numbers (a mid-2014
15-inch MacBook Pro with 16GB RAM and a 2.5GHz Intel i7 processor).
There are cases when `fftconvolve` supports the inputs but this function
returns `direct` (e.g., to protect against floating point integer
precision).
.. versionadded:: 0.19
Examples
--------
Estimate the fastest method for a given input:
>>> import numpy as np
>>> from scipy import signal
>>> rng = np.random.default_rng()
>>> img = rng.random((32, 32))
>>> filter = rng.random((8, 8))
>>> method = signal.choose_conv_method(img, filter, mode='same')
>>> method
'fft'
This can then be applied to other arrays of the same dtype and shape:
>>> img2 = rng.random((32, 32))
>>> filter2 = rng.random((8, 8))
>>> corr2 = signal.correlate(img2, filter2, mode='same', method=method)
>>> conv2 = signal.convolve(img2, filter2, mode='same', method=method)
The output of this function (``method``) works with `correlate` and
`convolve`.
Definition at line 1160 of file _signaltools.py.
References _fftconv_faster(), _numeric_arrays(), _timeit_fast(), and convolve().
Referenced by convolve(), and scipy.signal.tests.test_signaltools.filtfilt_gust_opt().
cmplx_sort()
scipy.signal._signaltools.cmplx_sort (p)
Sort roots based on magnitude.
Parameters
----------
p : array_like
    The roots to sort, as a 1-D array.
Returns
-------
p_sorted : ndarray
    Sorted roots.
indx : ndarray
    Array of indices needed to sort the input `p`.
Examples
--------
>>> from scipy import signal
>>> vals = [1, 4, 1+1.j, 3]
>>> p_sorted, indx = signal.cmplx_sort(vals)
>>> p_sorted
array([1.+0.j, 1.+1.j, 3.+0.j, 4.+0.j])
>>> indx
array([0, 2, 3, 1])
Definition at line 2467 of file _signaltools.py.
Referenced by residue(), and residuez().
convolve()
scipy.signal._signaltools.convolve (in1, in2, mode = 'full', method = 'auto')
Convolve two N-dimensional arrays.
Convolve `in1` and `in2`, with the output size determined by the
`mode` argument.
Parameters
----------
in1 : array_like
    First input.
in2 : array_like
    Second input. Should have the same number of dimensions as `in1`.
mode : str {'full', 'valid', 'same'}, optional
    A string indicating the size of the output:
    ``full``
       The output is the full discrete linear convolution
       of the inputs. (Default)
    ``valid``
       The output consists only of those elements that do not
       rely on the zero-padding. In 'valid' mode, either `in1` or `in2`
       must be at least as large as the other in every dimension.
    ``same``
       The output is the same size as `in1`, centered
       with respect to the 'full' output.
method : str {'auto', 'direct', 'fft'}, optional
    A string indicating which method to use to calculate the convolution.
    ``direct``
       The convolution is determined directly from sums, the definition of
       convolution.
    ``fft``
       The Fourier Transform is used to perform the convolution by calling
       `fftconvolve`.
    ``auto``
       Automatically chooses direct or Fourier method based on an estimate
       of which is faster (default).  See Notes for more detail.
       .. versionadded:: 0.19.0
Returns
-------
convolve : array
    An N-dimensional array containing a subset of the discrete linear
    convolution of `in1` with `in2`.
Warns
-----
RuntimeWarning
    Use of the FFT convolution on input containing NAN or INF will lead
    to the entire output being NAN or INF. Use method='direct' when your
    input contains NAN or INF values.
See Also
--------
numpy.polymul : performs polynomial multiplication (same operation, but
                also accepts poly1d objects)
choose_conv_method : chooses the fastest appropriate convolution method
fftconvolve : Always uses the FFT method.
oaconvolve : Uses the overlap-add method to do convolution, which is
             generally faster when the input arrays are large and
             significantly different in size.
Notes
-----
By default, `convolve` and `correlate` use ``method='auto'``, which calls
`choose_conv_method` to choose the fastest method using pre-computed
values (`choose_conv_method` can also measure real-world timing with a
keyword argument). Because `fftconvolve` relies on floating point numbers,
there are certain constraints that may force `method=direct` (more detail
in `choose_conv_method` docstring).
Examples
--------
Smooth a square pulse using a Hann window:
>>> import numpy as np
>>> from scipy import signal
>>> sig = np.repeat([0., 1., 0.], 100)
>>> win = signal.windows.hann(50)
>>> filtered = signal.convolve(sig, win, mode='same') / sum(win)
>>> import matplotlib.pyplot as plt
>>> fig, (ax_orig, ax_win, ax_filt) = plt.subplots(3, 1, sharex=True)
>>> ax_orig.plot(sig)
>>> ax_orig.set_title('Original pulse')
>>> ax_orig.margins(0, 0.1)
>>> ax_win.plot(win)
>>> ax_win.set_title('Filter impulse response')
>>> ax_win.margins(0, 0.1)
>>> ax_filt.plot(filtered)
>>> ax_filt.set_title('Filtered signal')
>>> ax_filt.margins(0, 0.1)
>>> fig.tight_layout()
>>> fig.show()
Definition at line 1299 of file _signaltools.py.
References _inputs_swap_needed(), _np_conv_ok(), _reverse_and_conj(), choose_conv_method(), correlate(), and fftconvolve().
Referenced by choose_conv_method(), correlate(), scipy.signal._wavelets.cwt(), and deconvolve().
convolve2d()
scipy.signal._signaltools.convolve2d (in1, in2, mode = 'full', boundary = 'fill', fillvalue = 0)
Convolve two 2-dimensional arrays.
Convolve `in1` and `in2` with output size determined by `mode`, and
boundary conditions determined by `boundary` and `fillvalue`.
Parameters
----------
in1 : array_like
    First input.
in2 : array_like
    Second input. Should have the same number of dimensions as `in1`.
mode : str {'full', 'valid', 'same'}, optional
    A string indicating the size of the output:
    ``full``
       The output is the full discrete linear convolution
       of the inputs. (Default)
    ``valid``
       The output consists only of those elements that do not
       rely on the zero-padding. In 'valid' mode, either `in1` or `in2`
       must be at least as large as the other in every dimension.
    ``same``
       The output is the same size as `in1`, centered
       with respect to the 'full' output.
boundary : str {'fill', 'wrap', 'symm'}, optional
    A flag indicating how to handle boundaries:
    ``fill``
       pad input arrays with fillvalue. (default)
    ``wrap``
       circular boundary conditions.
    ``symm``
       symmetrical boundary conditions.
fillvalue : scalar, optional
    Value to fill pad input arrays with. Default is 0.
Returns
-------
out : ndarray
    A 2-dimensional array containing a subset of the discrete linear
    convolution of `in1` with `in2`.
Examples
--------
Compute the gradient of an image by 2D convolution with a complex Scharr
operator.  (Horizontal operator is real, vertical is imaginary.)  Use
symmetric boundary condition to avoid creating edges at the image
boundaries.
>>> import numpy as np
>>> from scipy import signal
>>> from scipy import datasets
>>> ascent = datasets.ascent()
>>> scharr = np.array([[ -3-3j, 0-10j,  +3 -3j],
...                    [-10+0j, 0+ 0j, +10 +0j],
...                    [ -3+3j, 0+10j,  +3 +3j]]) # Gx + j*Gy
>>> grad = signal.convolve2d(ascent, scharr, boundary='symm', mode='same')
>>> import matplotlib.pyplot as plt
>>> fig, (ax_orig, ax_mag, ax_ang) = plt.subplots(3, 1, figsize=(6, 15))
>>> ax_orig.imshow(ascent, cmap='gray')
>>> ax_orig.set_title('Original')
>>> ax_orig.set_axis_off()
>>> ax_mag.imshow(np.absolute(grad), cmap='gray')
>>> ax_mag.set_title('Gradient magnitude')
>>> ax_mag.set_axis_off()
>>> ax_ang.imshow(np.angle(grad), cmap='hsv') # hsv is cyclic, like angles
>>> ax_ang.set_title('Gradient orientation')
>>> ax_ang.set_axis_off()
>>> fig.show()
Definition at line 1664 of file _signaltools.py.
References _inputs_swap_needed().
correlate()
scipy.signal._signaltools.correlate (in1, in2, mode = 'full', method = 'auto')
Cross-correlate two N-dimensional arrays.
Cross-correlate `in1` and `in2`, with the output size determined by the
`mode` argument.
Parameters
----------
in1 : array_like
First input.
in2 : array_like
Second input. Should have the same number of dimensions as `in1`.
mode : str {'full', 'valid', 'same'}, optional
A string indicating the size of the output:
``full``
The output is the full discrete linear cross-correlation
of the inputs. (Default)
``valid``
The output consists only of those elements that do not
rely on the zero-padding. In 'valid' mode, either `in1` or `in2`
must be at least as large as the other in every dimension.
``same``
The output is the same size as `in1`, centered
with respect to the 'full' output.
method : str {'auto', 'direct', 'fft'}, optional
A string indicating which method to use to calculate the correlation.
``direct``
The correlation is determined directly from sums, the definition of
correlation.
``fft``
The Fast Fourier Transform is used to perform the correlation more
quickly (only available for numerical arrays.)
``auto``
Automatically chooses direct or Fourier method based on an estimate
of which is faster (default).  See `convolve` Notes for more detail.
.. versionadded:: 0.19.0
Returns
-------
correlate : array
An N-dimensional array containing a subset of the discrete linear
cross-correlation of `in1` with `in2`.
See Also
--------
choose_conv_method : contains more documentation on `method`.
correlation_lags : calculates the lag / displacement indices array for 1D
cross-correlation.
Notes
-----
The correlation z of two d-dimensional arrays x and y is defined as::
z[...,k,...] = sum[..., i_l, ...] x[..., i_l,...] * conj(y[..., i_l - k,...])
This way, if x and y are 1-D arrays and ``z = correlate(x, y, 'full')``
then
.. math::
z[k] = (x * y)(k - N + 1)
= \sum_{l=0}^{||x||-1}x_l y_{l-k+N-1}^{*}
for :math:`k = 0, 1, ..., ||x|| + ||y|| - 2`
where :math:`||x||` is the length of ``x``, :math:`N = \max(||x||,||y||)`,
and :math:`y_m` is 0 when m is outside the range of y.
``method='fft'`` only works for numerical arrays as it relies on
`fftconvolve`. In certain cases (i.e., arrays of objects or when
rounding integers can lose precision), ``method='direct'`` is always used.
When using "same" mode with even-length inputs, the outputs of `correlate`
and `correlate2d` differ: There is a 1-index offset between them.
Examples
--------
Implement a matched filter using cross-correlation, to recover a signal
that has passed through a noisy channel.
>>> import numpy as np
>>> from scipy import signal
>>> import matplotlib.pyplot as plt
>>> rng = np.random.default_rng()
>>> sig = np.repeat([0., 1., 1., 0., 1., 0., 0., 1.], 128)
>>> sig_noise = sig + rng.standard_normal(len(sig))
>>> corr = signal.correlate(sig_noise, np.ones(128), mode='same') / 128
>>> clock = np.arange(64, len(sig), 128)
>>> fig, (ax_orig, ax_noise, ax_corr) = plt.subplots(3, 1, sharex=True)
>>> ax_orig.plot(sig)
>>> ax_orig.plot(clock, sig[clock], 'ro')
>>> ax_orig.set_title('Original signal')
>>> ax_noise.plot(sig_noise)
>>> ax_noise.set_title('Signal with noise')
>>> ax_corr.plot(corr)
>>> ax_corr.plot(clock, corr[clock], 'ro')
>>> ax_corr.axhline(0.5, ls=':')
>>> ax_corr.set_title('Cross-correlated with rectangular pulse')
>>> ax_orig.margins(0, 0.1)
>>> fig.tight_layout()
>>> plt.show()
Compute the cross-correlation of a noisy signal with the original signal.
>>> x = np.arange(128) / 128
>>> sig = np.sin(2 * np.pi * x)
>>> sig_noise = sig + rng.standard_normal(len(sig))
>>> corr = signal.correlate(sig_noise, sig)
>>> lags = signal.correlation_lags(len(sig), len(sig_noise))
>>> corr /= np.max(corr)
>>> fig, (ax_orig, ax_noise, ax_corr) = plt.subplots(3, 1, figsize=(4.8, 4.8))
>>> ax_orig.plot(sig)
>>> ax_orig.set_title('Original signal')
>>> ax_orig.set_xlabel('Sample Number')
>>> ax_noise.plot(sig_noise)
>>> ax_noise.set_title('Signal with noise')
>>> ax_noise.set_xlabel('Sample Number')
>>> ax_corr.plot(lags, corr)
>>> ax_corr.set_title('Cross-correlated signal')
>>> ax_corr.set_xlabel('Lag')
>>> ax_orig.margins(0, 0.1)
>>> ax_noise.margins(0, 0.1)
>>> ax_corr.margins(0, 0.1)
>>> fig.tight_layout()
>>> plt.show()
Definition at line 91 of file _signaltools.py.
References _inputs_swap_needed(), _np_conv_ok(), _reverse_and_conj(), and convolve().
Referenced by convolve(), and wiener().
correlate2d()
scipy.signal._signaltools.correlate2d (in1, in2, mode = 'full', boundary = 'fill', fillvalue = 0)
Cross-correlate two 2-dimensional arrays.
Cross correlate `in1` and `in2` with output size determined by `mode`, and
boundary conditions determined by `boundary` and `fillvalue`.
Parameters
----------
in1 : array_like
    First input.
in2 : array_like
    Second input. Should have the same number of dimensions as `in1`.
mode : str {'full', 'valid', 'same'}, optional
    A string indicating the size of the output:
    ``full``
       The output is the full discrete linear cross-correlation
       of the inputs. (Default)
    ``valid``
       The output consists only of those elements that do not
       rely on the zero-padding. In 'valid' mode, either `in1` or `in2`
       must be at least as large as the other in every dimension.
    ``same``
       The output is the same size as `in1`, centered
       with respect to the 'full' output.
boundary : str {'fill', 'wrap', 'symm'}, optional
    A flag indicating how to handle boundaries:
    ``fill``
       pad input arrays with fillvalue. (default)
    ``wrap``
       circular boundary conditions.
    ``symm``
       symmetrical boundary conditions.
fillvalue : scalar, optional
    Value to fill pad input arrays with. Default is 0.
Returns
-------
correlate2d : ndarray
    A 2-dimensional array containing a subset of the discrete linear
    cross-correlation of `in1` with `in2`.
Notes
-----
When using "same" mode with even-length inputs, the outputs of `correlate`
and `correlate2d` differ: There is a 1-index offset between them.
Examples
--------
Use 2D cross-correlation to find the location of a template in a noisy
image:
>>> import numpy as np
>>> from scipy import signal
>>> from scipy import datasets
>>> rng = np.random.default_rng()
>>> face = datasets.face(gray=True) - datasets.face(gray=True).mean()
>>> template = np.copy(face[300:365, 670:750])  # right eye
>>> template -= template.mean()
>>> face = face + rng.standard_normal(face.shape) * 50  # add noise
>>> corr = signal.correlate2d(face, template, boundary='symm', mode='same')
>>> y, x = np.unravel_index(np.argmax(corr), corr.shape)  # find the match
>>> import matplotlib.pyplot as plt
>>> fig, (ax_orig, ax_template, ax_corr) = plt.subplots(3, 1,
...                                                     figsize=(6, 15))
>>> ax_orig.imshow(face, cmap='gray')
>>> ax_orig.set_title('Original')
>>> ax_orig.set_axis_off()
>>> ax_template.imshow(template, cmap='gray')
>>> ax_template.set_title('Template')
>>> ax_template.set_axis_off()
>>> ax_corr.imshow(corr, cmap='gray')
>>> ax_corr.set_title('Cross-correlation')
>>> ax_corr.set_axis_off()
>>> ax_orig.plot(x, y, 'ro')
>>> fig.show()
Definition at line 1754 of file _signaltools.py.
References _inputs_swap_needed().
correlation_lags()
scipy.signal._signaltools.correlation_lags (in1_len, in2_len, mode = 'full')
Calculates the lag / displacement indices array for 1D cross-correlation.
Parameters
----------
in1_len : int
First input size.
in2_len : int
Second input size.
mode : str {'full', 'valid', 'same'}, optional
A string indicating the size of the output.
See the documentation `correlate` for more information.
Returns
-------
lags : array
Returns an array containing cross-correlation lag/displacement indices.
Indices can be indexed with the np.argmax of the correlation to return
the lag/displacement.
See Also
--------
correlate : Compute the N-dimensional cross-correlation.
Notes
-----
Cross-correlation for continuous functions :math:`f` and :math:`g` is
defined as:
.. math::
\left (f\star g \right)\left (\tau \right)
\triangleq \int_{t_0}^{t_0 +T}
\overline{f\left (t \right)}g\left (t+\tau \right)dt
Where :math:`\tau` is defined as the displacement, also known as the lag.
Cross correlation for discrete functions :math:`f` and :math:`g` is
defined as:
.. math::
\left (f\star g \right)\left [ n \right ]
\triangleq \sum_{-\infty}^{\infty}
\overline{f\left [ m \right ]}g\left [ m+n \right ]
Where :math:`n` is the lag.
Examples
--------
Cross-correlation of a signal with its time-delayed self.
>>> import numpy as np
>>> from scipy import signal
>>> rng = np.random.default_rng()
>>> x = rng.standard_normal(1000)
>>> y = np.concatenate([rng.standard_normal(100), x])
>>> correlation = signal.correlate(x, y, mode="full")
>>> lags = signal.correlation_lags(x.size, y.size, mode="full")
>>> lag = lags[np.argmax(correlation)]
Definition at line 291 of file _signaltools.py.
decimate()
scipy.signal._signaltools.decimate (x, q, n = None, ftype = 'iir', axis = -1, zero_phase = True)
Downsample the signal after applying an anti-aliasing filter.
By default, an order 8 Chebyshev type I filter is used. A 30 point FIR
filter with Hamming window is used if `ftype` is 'fir'.
Parameters
----------
x : array_like
    The signal to be downsampled, as an N-dimensional array.
q : int
    The downsampling factor. When using IIR downsampling, it is recommended
    to call `decimate` multiple times for downsampling factors higher than
    13.
n : int, optional
    The order of the filter (1 less than the length for 'fir'). Defaults to
    8 for 'iir' and 20 times the downsampling factor for 'fir'.
ftype : str {'iir', 'fir'} or ``dlti`` instance, optional
    If 'iir' or 'fir', specifies the type of lowpass filter. If an instance
    of an `dlti` object, uses that object to filter before downsampling.
axis : int, optional
    The axis along which to decimate.
zero_phase : bool, optional
    Prevent phase shift by filtering with `filtfilt` instead of `lfilter`
    when using an IIR filter, and shifting the outputs back by the filter's
    group delay when using an FIR filter. The default value of ``True`` is
    recommended, since a phase shift is generally not desired.
    .. versionadded:: 0.18.0
Returns
-------
y : ndarray
    The down-sampled signal.
See Also
--------
resample : Resample up or down using the FFT method.
resample_poly : Resample using polyphase filtering and an FIR filter.
Notes
-----
The ``zero_phase`` keyword was added in 0.18.0.
The possibility to use instances of ``dlti`` as ``ftype`` was added in
0.18.0.
Examples
--------
>>> import numpy as np
>>> from scipy import signal
>>> import matplotlib.pyplot as plt
Define wave parameters.
>>> wave_duration = 3
>>> sample_rate = 100
>>> freq = 2
>>> q = 5
Calculate number of samples.
>>> samples = wave_duration*sample_rate
>>> samples_decimated = int(samples/q)
Create cosine wave.
>>> x = np.linspace(0, wave_duration, samples, endpoint=False)
>>> y = np.cos(x*np.pi*freq*2)
Decimate cosine wave.
>>> ydem = signal.decimate(y, q)
>>> xnew = np.linspace(0, wave_duration, samples_decimated, endpoint=False)
Plot original and decimated waves.
>>> plt.plot(x, y, '.-', xnew, ydem, 'o-')
>>> plt.xlabel('Time, Seconds')
>>> plt.legend(['data', 'decimated'], loc='best')
>>> plt.show()
Definition at line 4458 of file _signaltools.py.
References scipy.signal._filter_design.cheby1(), filtfilt(), scipy.signal._fir_filter_design.firwin(), lfilter(), resample_poly(), sosfilt(), sosfiltfilt(), and scipy.signal._filter_design.zpk2sos().
deconvolve()
scipy.signal._signaltools.deconvolve (signal, divisor)
Deconvolves ``divisor`` out of ``signal`` using inverse filtering.
Returns the quotient and remainder such that
``signal = convolve(divisor, quotient) + remainder``
Parameters
----------
signal : (N,) array_like
    Signal data, typically a recorded signal
divisor : (N,) array_like
    Divisor data, typically an impulse response or filter that was
    applied to the original signal
Returns
-------
quotient : ndarray
    Quotient, typically the recovered original signal
remainder : ndarray
    Remainder
See Also
--------
numpy.polydiv : performs polynomial division (same operation, but
                also accepts poly1d objects)
Examples
--------
Deconvolve a signal that's been filtered:
>>> from scipy import signal
>>> original = [0, 1, 0, 0, 1, 1, 0, 0]
>>> impulse_response = [2, 1]
>>> recorded = signal.convolve(impulse_response, original)
>>> recorded
array([0, 2, 1, 0, 2, 3, 1, 0, 0])
>>> recovered, remainder = signal.deconvolve(recorded, impulse_response)
>>> recovered
array([ 0.,  1.,  0.,  0.,  1.,  1.,  0.,  0.])
Definition at line 2237 of file _signaltools.py.
References convolve(), and lfilter().
detrend()
scipy.signal._signaltools.detrend (data, axis = -1, type = 'linear', bp = 0, overwrite_data = False)
Remove linear trend along axis from data.
Parameters
----------
data : array_like
    The input data.
axis : int, optional
    The axis along which to detrend the data. By default this is the
    last axis (-1).
type : {'linear', 'constant'}, optional
    The type of detrending. If ``type == 'linear'`` (default),
    the result of a linear least-squares fit to `data` is subtracted
    from `data`.
    If ``type == 'constant'``, only the mean of `data` is subtracted.
bp : array_like of ints, optional
    A sequence of break points. If given, an individual linear fit is
    performed for each part of `data` between two break points.
    Break points are specified as indices into `data`. This parameter
    only has an effect when ``type == 'linear'``.
overwrite_data : bool, optional
    If True, perform in place detrending and avoid a copy. Default is False
Returns
-------
ret : ndarray
    The detrended input data.
Examples
--------
>>> import numpy as np
>>> from scipy import signal
>>> rng = np.random.default_rng()
>>> npoints = 1000
>>> noise = rng.standard_normal(npoints)
>>> x = 3 + 2*np.linspace(0, 1, npoints) + noise
>>> (signal.detrend(x) - noise).max()
0.06  # random
Definition at line 3510 of file _signaltools.py.
Referenced by scipy.signal._spectral_py._spectral_helper().
fftconvolve()
scipy.signal._signaltools.fftconvolve (in1, in2, mode = "full", axes = None)
Convolve two N-dimensional arrays using FFT.
Convolve `in1` and `in2` using the fast Fourier transform method, with
the output size determined by the `mode` argument.
This is generally much faster than `convolve` for large arrays (n > ~500),
but can be slower when only a few output values are needed, and can only
output float arrays (int or object array inputs will be cast to float).
As of v0.19, `convolve` automatically chooses this method or the direct
method based on an estimation of which is faster.
Parameters
----------
in1 : array_like
    First input.
in2 : array_like
    Second input. Should have the same number of dimensions as `in1`.
mode : str {'full', 'valid', 'same'}, optional
    A string indicating the size of the output:
    ``full``
       The output is the full discrete linear convolution
       of the inputs. (Default)
    ``valid``
       The output consists only of those elements that do not
       rely on the zero-padding. In 'valid' mode, either `in1` or `in2`
       must be at least as large as the other in every dimension.
    ``same``
       The output is the same size as `in1`, centered
       with respect to the 'full' output.
axes : int or array_like of ints or None, optional
    Axes over which to compute the convolution.
    The default is over all axes.
Returns
-------
out : array
    An N-dimensional array containing a subset of the discrete linear
    convolution of `in1` with `in2`.
See Also
--------
convolve : Uses the direct convolution or FFT convolution algorithm
           depending on which is faster.
oaconvolve : Uses the overlap-add method to do convolution, which is
             generally faster when the input arrays are large and
             significantly different in size.
Examples
--------
Autocorrelation of white noise is an impulse.
>>> import numpy as np
>>> from scipy import signal
>>> rng = np.random.default_rng()
>>> sig = rng.standard_normal(1000)
>>> autocorr = signal.fftconvolve(sig, sig[::-1], mode='full')
>>> import matplotlib.pyplot as plt
>>> fig, (ax_orig, ax_mag) = plt.subplots(2, 1)
>>> ax_orig.plot(sig)
>>> ax_orig.set_title('White noise')
>>> ax_mag.plot(np.arange(-len(sig)+1,len(sig)), autocorr)
>>> ax_mag.set_title('Autocorrelation')
>>> fig.tight_layout()
>>> fig.show()
Gaussian blur implemented using FFT convolution.  Notice the dark borders
around the image, due to the zero-padding beyond its boundaries.
The `convolve2d` function allows for other types of image boundaries,
but is far slower.
>>> from scipy import datasets
>>> face = datasets.face(gray=True)
>>> kernel = np.outer(signal.windows.gaussian(70, 8),
...                   signal.windows.gaussian(70, 8))
>>> blurred = signal.fftconvolve(face, kernel, mode='same')
>>> fig, (ax_orig, ax_kernel, ax_blurred) = plt.subplots(3, 1,
...                                                      figsize=(6, 15))
>>> ax_orig.imshow(face, cmap='gray')
>>> ax_orig.set_title('Original')
>>> ax_orig.set_axis_off()
>>> ax_kernel.imshow(kernel, cmap='gray')
>>> ax_kernel.set_title('Gaussian kernel')
>>> ax_kernel.set_axis_off()
>>> ax_blurred.imshow(blurred, cmap='gray')
>>> ax_blurred.set_title('Blurred')
>>> ax_blurred.set_axis_off()
>>> fig.show()
Definition at line 557 of file _signaltools.py.
References _apply_conv_mode(), _freq_domain_conv(), and _init_freq_conv_axes().
Referenced by convolve(), and oaconvolve().
filtfilt()
scipy.signal._signaltools.filtfilt (b, a, x, axis = -1, padtype = 'odd', padlen = None, method = 'pad', irlen = None)
Apply a digital filter forward and backward to a signal.
This function applies a linear digital filter twice, once forward and
once backwards.  The combined filter has zero phase and a filter order
twice that of the original.
The function provides options for handling the edges of the signal.
The function `sosfiltfilt` (and filter design using ``output='sos'``)
should be preferred over `filtfilt` for most filtering tasks, as
second-order sections have fewer numerical problems.
Parameters
----------
b : (N,) array_like
    The numerator coefficient vector of the filter.
a : (N,) array_like
    The denominator coefficient vector of the filter.  If ``a[0]``
    is not 1, then both `a` and `b` are normalized by ``a[0]``.
x : array_like
    The array of data to be filtered.
axis : int, optional
    The axis of `x` to which the filter is applied.
    Default is -1.
padtype : str or None, optional
    Must be 'odd', 'even', 'constant', or None.  This determines the
    type of extension to use for the padded signal to which the filter
    is applied.  If `padtype` is None, no padding is used.  The default
    is 'odd'.
padlen : int or None, optional
    The number of elements by which to extend `x` at both ends of
    `axis` before applying the filter.  This value must be less than
    ``x.shape[axis] - 1``.  ``padlen=0`` implies no padding.
    The default value is ``3 * max(len(a), len(b))``.
method : str, optional
    Determines the method for handling the edges of the signal, either
    "pad" or "gust".  When `method` is "pad", the signal is padded; the
    type of padding is determined by `padtype` and `padlen`, and `irlen`
    is ignored.  When `method` is "gust", Gustafsson's method is used,
    and `padtype` and `padlen` are ignored.
irlen : int or None, optional
    When `method` is "gust", `irlen` specifies the length of the
    impulse response of the filter.  If `irlen` is None, no part
    of the impulse response is ignored.  For a long signal, specifying
    `irlen` can significantly improve the performance of the filter.
Returns
-------
y : ndarray
    The filtered output with the same shape as `x`.
See Also
--------
sosfiltfilt, lfilter_zi, lfilter, lfiltic, savgol_filter, sosfilt
Notes
-----
When `method` is "pad", the function pads the data along the given axis
in one of three ways: odd, even or constant.  The odd and even extensions
have the corresponding symmetry about the end point of the data.  The
constant extension extends the data with the values at the end points. On
both the forward and backward passes, the initial condition of the
filter is found by using `lfilter_zi` and scaling it by the end point of
the extended data.
When `method` is "gust", Gustafsson's method [1]_ is used.  Initial
conditions are chosen for the forward and backward passes so that the
forward-backward filter gives the same result as the backward-forward
filter.
The option to use Gustaffson's method was added in scipy version 0.16.0.
References
----------
.. [1] F. Gustaffson, "Determining the initial states in forward-backward
       filtering", Transactions on Signal Processing, Vol. 46, pp. 988-992,
       1996.
Examples
--------
The examples will use several functions from `scipy.signal`.
>>> import numpy as np
>>> from scipy import signal
>>> import matplotlib.pyplot as plt
First we create a one second signal that is the sum of two pure sine
waves, with frequencies 5 Hz and 250 Hz, sampled at 2000 Hz.
>>> t = np.linspace(0, 1.0, 2001)
>>> xlow = np.sin(2 * np.pi * 5 * t)
>>> xhigh = np.sin(2 * np.pi * 250 * t)
>>> x = xlow + xhigh
Now create a lowpass Butterworth filter with a cutoff of 0.125 times
the Nyquist frequency, or 125 Hz, and apply it to ``x`` with `filtfilt`.
The result should be approximately ``xlow``, with no phase shift.
>>> b, a = signal.butter(8, 0.125)
>>> y = signal.filtfilt(b, a, x, padlen=150)
>>> np.abs(y - xlow).max()
9.1086182074789912e-06
We get a fairly clean result for this artificial example because
the odd extension is exact, and with the moderately long padding,
the filter's transients have dissipated by the time the actual data
is reached.  In general, transient effects at the edges are
unavoidable.
The following example demonstrates the option ``method="gust"``.
First, create a filter.
>>> b, a = signal.ellip(4, 0.01, 120, 0.125)  # Filter to be applied.
`sig` is a random input signal to be filtered.
>>> rng = np.random.default_rng()
>>> n = 60
>>> sig = rng.standard_normal(n)**3 + 3*rng.standard_normal(n).cumsum()
Apply `filtfilt` to `sig`, once using the Gustafsson method, and
once using padding, and plot the results for comparison.
>>> fgust = signal.filtfilt(b, a, sig, method="gust")
>>> fpad = signal.filtfilt(b, a, sig, padlen=50)
>>> plt.plot(sig, 'k-', label='input')
>>> plt.plot(fgust, 'b-', linewidth=4, label='gust')
>>> plt.plot(fpad, 'c-', linewidth=1.5, label='pad')
>>> plt.legend(loc='best')
>>> plt.show()
The `irlen` argument can be used to improve the performance
of Gustafsson's method.
Estimate the impulse response length of the filter.
>>> z, p, k = signal.tf2zpk(b, a)
>>> eps = 1e-9
>>> r = np.max(np.abs(p))
>>> approx_impulse_len = int(np.ceil(np.log(eps) / np.log(r)))
>>> approx_impulse_len
137
Apply the filter to a longer signal, with and without the `irlen`
argument.  The difference between `y1` and `y2` is small.  For long
signals, using `irlen` gives a significant performance improvement.
>>> x = rng.standard_normal(4000)
>>> y1 = signal.filtfilt(b, a, x, method='gust')
>>> y2 = signal.filtfilt(b, a, x, method='gust', irlen=approx_impulse_len)
>>> print(np.max(np.abs(y1 - y2)))
2.875334415008979e-10
Definition at line 3989 of file _signaltools.py.
References _filtfilt_gust(), _validate_pad(), lfilter(), and lfilter_zi().
Referenced by decimate(), and scipy.signal.tests.test_signaltools.filtfilt_gust_opt().
hilbert()
scipy.signal._signaltools.hilbert (x, N = None, axis = -1)
Compute the analytic signal, using the Hilbert transform.
The transformation is done along the last axis by default.
Parameters
----------
x : array_like
    Signal data.  Must be real.
N : int, optional
    Number of Fourier components.  Default: ``x.shape[axis]``
axis : int, optional
    Axis along which to do the transformation.  Default: -1.
Returns
-------
xa : ndarray
    Analytic signal of `x`, of each 1-D array along `axis`
Notes
-----
The analytic signal ``x_a(t)`` of signal ``x(t)`` is:
.. math:: x_a = F^{-1}(F(x) 2U) = x + i y
where `F` is the Fourier transform, `U` the unit step function,
and `y` the Hilbert transform of `x`. [1]_
In other words, the negative half of the frequency spectrum is zeroed
out, turning the real-valued signal into a complex signal.  The Hilbert
transformed signal can be obtained from ``np.imag(hilbert(x))``, and the
original signal from ``np.real(hilbert(x))``.
References
----------
.. [1] Wikipedia, "Analytic signal".
       https://en.wikipedia.org/wiki/Analytic_signal
.. [2] Leon Cohen, "Time-Frequency Analysis", 1995. Chapter 2.
.. [3] Alan V. Oppenheim, Ronald W. Schafer. Discrete-Time Signal
       Processing, Third Edition, 2009. Chapter 12.
       ISBN 13: 978-1292-02572-8
Examples
--------
In this example we use the Hilbert transform to determine the amplitude
envelope and instantaneous frequency of an amplitude-modulated signal.
>>> import numpy as np
>>> import matplotlib.pyplot as plt
>>> from scipy.signal import hilbert, chirp
>>> duration = 1.0
>>> fs = 400.0
>>> samples = int(fs*duration)
>>> t = np.arange(samples) / fs
We create a chirp of which the frequency increases from 20 Hz to 100 Hz and
apply an amplitude modulation.
>>> signal = chirp(t, 20.0, t[-1], 100.0)
>>> signal *= (1.0 + 0.5 * np.sin(2.0*np.pi*3.0*t))
The amplitude envelope is given by magnitude of the analytic signal. The
instantaneous frequency can be obtained by differentiating the
instantaneous phase in respect to time. The instantaneous phase corresponds
to the phase angle of the analytic signal.
>>> analytic_signal = hilbert(signal)
>>> amplitude_envelope = np.abs(analytic_signal)
>>> instantaneous_phase = np.unwrap(np.angle(analytic_signal))
>>> instantaneous_frequency = (np.diff(instantaneous_phase) /
...                            (2.0*np.pi) * fs)
>>> fig, (ax0, ax1) = plt.subplots(nrows=2)
>>> ax0.plot(t, signal, label='signal')
>>> ax0.plot(t, amplitude_envelope, label='envelope')
>>> ax0.set_xlabel("time in seconds")
>>> ax0.legend()
>>> ax1.plot(t[1:], instantaneous_frequency)
>>> ax1.set_xlabel("time in seconds")
>>> ax1.set_ylim(0.0, 120.0)
>>> fig.tight_layout()
Definition at line 2297 of file _signaltools.py.
hilbert2()
scipy.signal._signaltools.hilbert2 (x, N = None)
Compute the '2-D' analytic signal of `x`
Parameters
----------
x : array_like
    2-D signal data.
N : int or tuple of two ints, optional
    Number of Fourier components. Default is ``x.shape``
Returns
-------
xa : ndarray
    Analytic signal of `x` taken along axes (0,1).
References
----------
.. [1] Wikipedia, "Analytic signal",
    https://en.wikipedia.org/wiki/Analytic_signal
Definition at line 2407 of file _signaltools.py.
invres()
scipy.signal._signaltools.invres (r, p, k, tol = 1e-3, rtype = 'avg')
Compute b(s) and a(s) from partial fraction expansion.
If `M` is the degree of numerator `b` and `N` the degree of denominator
`a`::
          b(s)     b[0] s**(M) + b[1] s**(M-1) + ... + b[M]
  H(s) = ------ = ------------------------------------------
          a(s)     a[0] s**(N) + a[1] s**(N-1) + ... + a[N]
then the partial-fraction expansion H(s) is defined as::
           r[0]       r[1]             r[-1]
       = -------- + -------- + ... + --------- + k(s)
         (s-p[0])   (s-p[1])         (s-p[-1])
If there are any repeated roots (closer together than `tol`), then H(s)
has terms like::
      r[i]      r[i+1]              r[i+n-1]
    -------- + ----------- + ... + -----------
    (s-p[i])  (s-p[i])**2          (s-p[i])**n
This function is used for polynomials in positive powers of s or z,
such as analog filters or digital filters in controls engineering.  For
negative powers of z (typical for digital filters in DSP), use `invresz`.
Parameters
----------
r : array_like
    Residues corresponding to the poles. For repeated poles, the residues
    must be ordered to correspond to ascending by power fractions.
p : array_like
    Poles. Equal poles must be adjacent.
k : array_like
    Coefficients of the direct polynomial term.
tol : float, optional
    The tolerance for two roots to be considered equal in terms of
    the distance between them. Default is 1e-3. See `unique_roots`
    for further details.
rtype : {'avg', 'min', 'max'}, optional
    Method for computing a root to represent a group of identical roots.
    Default is 'avg'. See `unique_roots` for further details.
Returns
-------
b : ndarray
    Numerator polynomial coefficients.
a : ndarray
    Denominator polynomial coefficients.
See Also
--------
residue, invresz, unique_roots
Definition at line 2584 of file _signaltools.py.
References _compute_factors().
invresz()
scipy.signal._signaltools.invresz (r, p, k, tol = 1e-3, rtype = 'avg')
Compute b(z) and a(z) from partial fraction expansion.
If `M` is the degree of numerator `b` and `N` the degree of denominator
`a`::
            b(z)     b[0] + b[1] z**(-1) + ... + b[M] z**(-M)
    H(z) = ------ = ------------------------------------------
            a(z)     a[0] + a[1] z**(-1) + ... + a[N] z**(-N)
then the partial-fraction expansion H(z) is defined as::
             r[0]                   r[-1]
     = --------------- + ... + ---------------- + k[0] + k[1]z**(-1) ...
       (1-p[0]z**(-1))         (1-p[-1]z**(-1))
If there are any repeated roots (closer than `tol`), then the partial
fraction expansion has terms like::
         r[i]              r[i+1]                    r[i+n-1]
    -------------- + ------------------ + ... + ------------------
    (1-p[i]z**(-1))  (1-p[i]z**(-1))**2         (1-p[i]z**(-1))**n
This function is used for polynomials in negative powers of z,
such as digital filters in DSP.  For positive powers, use `invres`.
Parameters
----------
r : array_like
    Residues corresponding to the poles. For repeated poles, the residues
    must be ordered to correspond to ascending by power fractions.
p : array_like
    Poles. Equal poles must be adjacent.
k : array_like
    Coefficients of the direct polynomial term.
tol : float, optional
    The tolerance for two roots to be considered equal in terms of
    the distance between them. Default is 1e-3. See `unique_roots`
    for further details.
rtype : {'avg', 'min', 'max'}, optional
    Method for computing a root to represent a group of identical roots.
    Default is 'avg'. See `unique_roots` for further details.
Returns
-------
b : ndarray
    Numerator polynomial coefficients.
a : ndarray
    Denominator polynomial coefficients.
See Also
--------
residuez, unique_roots, invres
Definition at line 2962 of file _signaltools.py.
References _compute_factors().
lfilter()
scipy.signal._signaltools.lfilter (b, a, x, axis = -1, zi = None)
Filter data along one-dimension with an IIR or FIR filter.
Filter a data sequence, `x`, using a digital filter.  This works for many
fundamental data types (including Object type).  The filter is a direct
form II transposed implementation of the standard difference equation
(see Notes).
The function `sosfilt` (and filter design using ``output='sos'``) should be
preferred over `lfilter` for most filtering tasks, as second-order sections
have fewer numerical problems.
Parameters
----------
b : array_like
    The numerator coefficient vector in a 1-D sequence.
a : array_like
    The denominator coefficient vector in a 1-D sequence.  If ``a[0]``
    is not 1, then both `a` and `b` are normalized by ``a[0]``.
x : array_like
    An N-dimensional input array.
axis : int, optional
    The axis of the input data array along which to apply the
    linear filter. The filter is applied to each subarray along
    this axis.  Default is -1.
zi : array_like, optional
    Initial conditions for the filter delays.  It is a vector
    (or array of vectors for an N-dimensional input) of length
    ``max(len(a), len(b)) - 1``.  If `zi` is None or is not given then
    initial rest is assumed.  See `lfiltic` for more information.
Returns
-------
y : array
    The output of the digital filter.
zf : array, optional
    If `zi` is None, this is not returned, otherwise, `zf` holds the
    final filter delay values.
See Also
--------
lfiltic : Construct initial conditions for `lfilter`.
lfilter_zi : Compute initial state (steady state of step response) for
             `lfilter`.
filtfilt : A forward-backward filter, to obtain a filter with zero phase.
savgol_filter : A Savitzky-Golay filter.
sosfilt: Filter data using cascaded second-order sections.
sosfiltfilt: A forward-backward filter using second-order sections.
Notes
-----
The filter function is implemented as a direct II transposed structure.
This means that the filter implements::
   a[0]*y[n] = b[0]*x[n] + b[1]*x[n-1] + ... + b[M]*x[n-M]
                         - a[1]*y[n-1] - ... - a[N]*y[n-N]
where `M` is the degree of the numerator, `N` is the degree of the
denominator, and `n` is the sample number.  It is implemented using
the following difference equations (assuming M = N)::
     a[0]*y[n] = b[0] * x[n]               + d[0][n-1]
       d[0][n] = b[1] * x[n] - a[1] * y[n] + d[1][n-1]
       d[1][n] = b[2] * x[n] - a[2] * y[n] + d[2][n-1]
     ...
     d[N-2][n] = b[N-1]*x[n] - a[N-1]*y[n] + d[N-1][n-1]
     d[N-1][n] = b[N] * x[n] - a[N] * y[n]
where `d` are the state variables.
The rational transfer function describing this filter in the
z-transform domain is::
                         -1              -M
             b[0] + b[1]z  + ... + b[M] z
     Y(z) = -------------------------------- X(z)
                         -1              -N
             a[0] + a[1]z  + ... + a[N] z
Examples
--------
Generate a noisy signal to be filtered:
>>> import numpy as np
>>> from scipy import signal
>>> import matplotlib.pyplot as plt
>>> rng = np.random.default_rng()
>>> t = np.linspace(-1, 1, 201)
>>> x = (np.sin(2*np.pi*0.75*t*(1-t) + 2.1) +
...      0.1*np.sin(2*np.pi*1.25*t + 1) +
...      0.18*np.cos(2*np.pi*3.85*t))
>>> xn = x + rng.standard_normal(len(t)) * 0.08
Create an order 3 lowpass butterworth filter:
>>> b, a = signal.butter(3, 0.05)
Apply the filter to xn.  Use lfilter_zi to choose the initial condition of
the filter:
>>> zi = signal.lfilter_zi(b, a)
>>> z, _ = signal.lfilter(b, a, xn, zi=zi*xn[0])
Apply the filter again, to have a result filtered at an order the same as
filtfilt:
>>> z2, _ = signal.lfilter(b, a, z, zi=zi*z[0])
Use filtfilt to apply the filter:
>>> y = signal.filtfilt(b, a, xn)
Plot the original signal and the various filtered versions:
>>> plt.figure
>>> plt.plot(t, xn, 'b', alpha=0.75)
>>> plt.plot(t, z, 'r--', t, z2, 'r', t, y, 'k')
>>> plt.legend(('noisy signal', 'lfilter, once', 'lfilter, twice',
...             'filtfilt'), loc='best')
>>> plt.grid(True)
>>> plt.show()
Definition at line 1964 of file _signaltools.py.
Referenced by _filtfilt_gust(), scipy.signal.tests.test_signaltools.assert_allclose_cast(), decimate(), deconvolve(), filtfilt(), and scipy.signal.tests.test_signaltools.filtfilt_gust_opt().
lfilter_zi()
scipy.signal._signaltools.lfilter_zi (b, a)
Construct initial conditions for lfilter for step response steady-state.
Compute an initial state `zi` for the `lfilter` function that corresponds
to the steady state of the step response.
A typical use of this function is to set the initial state so that the
output of the filter starts at the same value as the first element of
the signal to be filtered.
Parameters
----------
b, a : array_like (1-D)
    The IIR filter coefficients. See `lfilter` for more
    information.
Returns
-------
zi : 1-D ndarray
    The initial state for the filter.
See Also
--------
lfilter, lfiltic, filtfilt
Notes
-----
A linear filter with order m has a state space representation (A, B, C, D),
for which the output y of the filter can be expressed as::
    z(n+1) = A*z(n) + B*x(n)
    y(n)   = C*z(n) + D*x(n)
where z(n) is a vector of length m, A has shape (m, m), B has shape
(m, 1), C has shape (1, m) and D has shape (1, 1) (assuming x(n) is
a scalar).  lfilter_zi solves::
    zi = A*zi + B
In other words, it finds the initial condition for which the response
to an input of all ones is a constant.
Given the filter coefficients `a` and `b`, the state space matrices
for the transposed direct form II implementation of the linear filter,
which is the implementation used by scipy.signal.lfilter, are::
    A = scipy.linalg.companion(a).T
    B = b[1:] - a[1:]*b[0]
assuming `a[0]` is 1.0; if `a[0]` is not 1, `a` and `b` are first
divided by a[0].
Examples
--------
The following code creates a lowpass Butterworth filter. Then it
applies that filter to an array whose values are all 1.0; the
output is also all 1.0, as expected for a lowpass filter.  If the
`zi` argument of `lfilter` had not been given, the output would have
shown the transient signal.
>>> from numpy import array, ones
>>> from scipy.signal import lfilter, lfilter_zi, butter
>>> b, a = butter(5, 0.25)
>>> zi = lfilter_zi(b, a)
>>> y, zo = lfilter(b, a, ones(10), zi=zi)
>>> y
array([1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])
Another example:
>>> x = array([0.5, 0.5, 0.5, 0.0, 0.0, 0.0, 0.0])
>>> y, zf = lfilter(b, a, x, zi=zi*x[0])
>>> y
array([ 0.5       ,  0.5       ,  0.5       ,  0.49836039,  0.48610528,
    0.44399389,  0.35505241])
Note that the `zi` argument to `lfilter` was computed using
`lfilter_zi` and scaled by `x[0]`.  Then the output `y` has no
transient until the input drops from 0.5 to 0.0.
Definition at line 3598 of file _signaltools.py.
Referenced by filtfilt(), scipy.signal.tests.test_signaltools.filtfilt_gust_opt(), and sosfilt_zi().
lfiltic()
scipy.signal._signaltools.lfiltic (b, a, y, x = None)
Construct initial conditions for lfilter given input and output vectors.
Given a linear filter (b, a) and initial conditions on the output `y`
and the input `x`, return the initial conditions on the state vector zi
which is used by `lfilter` to generate the output given the input.
Parameters
----------
b : array_like
    Linear filter term.
a : array_like
    Linear filter term.
y : array_like
    Initial conditions.
    If ``N = len(a) - 1``, then ``y = {y[-1], y[-2], ..., y[-N]}``.
    If `y` is too short, it is padded with zeros.
x : array_like, optional
    Initial conditions.
    If ``M = len(b) - 1``, then ``x = {x[-1], x[-2], ..., x[-M]}``.
    If `x` is not given, its initial conditions are assumed zero.
    If `x` is too short, it is padded with zeros.
Returns
-------
zi : ndarray
    The state vector ``zi = {z_0[-1], z_1[-1], ..., z_K-1[-1]}``,
    where ``K = max(M, N)``.
See Also
--------
lfilter, lfilter_zi
Definition at line 2159 of file _signaltools.py.
medfilt()
scipy.signal._signaltools.medfilt (volume, kernel_size = None)
Perform a median filter on an N-dimensional array.
Apply a median filter to the input array using a local window-size
given by `kernel_size`. The array will automatically be zero-padded.
Parameters
----------
volume : array_like
    An N-dimensional input array.
kernel_size : array_like, optional
    A scalar or an N-length list giving the size of the median filter
    window in each dimension.  Elements of `kernel_size` should be odd.
    If `kernel_size` is a scalar, then this scalar is used as the size in
    each dimension. Default size is 3 for each dimension.
Returns
-------
out : ndarray
    An array the same size as input containing the median filtered
    result.
Warns
-----
UserWarning
    If array size is smaller than kernel size along any dimension
See Also
--------
scipy.ndimage.median_filter
scipy.signal.medfilt2d
Notes
-----
The more general function `scipy.ndimage.median_filter` has a more
efficient implementation of a median filter and therefore runs much faster.
For 2-dimensional images with ``uint8``, ``float32`` or ``float64`` dtypes,
the specialised function `scipy.signal.medfilt2d` may be faster.
Definition at line 1510 of file _signaltools.py.
Referenced by medfilt2d().
medfilt2d()
scipy.signal._signaltools.medfilt2d (input, kernel_size = 3)
Median filter a 2-dimensional array.
Apply a median filter to the `input` array using a local window-size
given by `kernel_size` (must be odd). The array is zero-padded
automatically.
Parameters
----------
input : array_like
    A 2-dimensional input array.
kernel_size : array_like, optional
    A scalar or a list of length 2, giving the size of the
    median filter window in each dimension.  Elements of
    `kernel_size` should be odd.  If `kernel_size` is a scalar,
    then this scalar is used as the size in each dimension.
    Default is a kernel of size (3, 3).
Returns
-------
out : ndarray
    An array the same size as input containing the median filtered
    result.
See Also
--------
scipy.ndimage.median_filter
Notes
-----
This is faster than `medfilt` when the input dtype is ``uint8``,
``float32``, or ``float64``; for other types, this falls back to
`medfilt`. In some situations, `scipy.ndimage.median_filter` may be
faster than this function.
Examples
--------
>>> import numpy as np
>>> from scipy import signal
>>> x = np.arange(25).reshape(5, 5)
>>> x
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])
# Replaces i,j with the median out of 5*5 window
>>> signal.medfilt2d(x, kernel_size=5)
array([[ 0,  0,  2,  0,  0],
       [ 0,  3,  7,  4,  0],
       [ 2,  8, 12,  9,  4],
       [ 0,  8, 12,  9,  0],
       [ 0,  0, 12,  0,  0]])
# Replaces i,j with the median out of default 3*3 window
>>> signal.medfilt2d(x)
array([[ 0,  1,  2,  3,  0],
       [ 1,  6,  7,  8,  4],
       [ 6, 11, 12, 13,  9],
       [11, 16, 17, 18, 14],
       [ 0, 16, 17, 18,  0]])
# Replaces i,j with the median out of default 5*3 window
>>> signal.medfilt2d(x, kernel_size=[5,3])
array([[ 0,  1,  2,  3,  0],
       [ 0,  6,  7,  8,  3],
       [ 5, 11, 12, 13,  8],
       [ 5, 11, 12, 13,  8],
       [ 0, 11, 12, 13,  0]])
# Replaces i,j with the median out of default 3*5 window
>>> signal.medfilt2d(x, kernel_size=[3,5])
array([[ 0,  0,  2,  1,  0],
       [ 1,  5,  7,  6,  3],
       [ 6, 10, 12, 11,  8],
       [11, 15, 17, 16, 13],
       [ 0, 15, 17, 16,  0]])
# As seen in the examples,
# kernel numbers must be odd and not exceed original array dim
Definition at line 1856 of file _signaltools.py.
References medfilt().
oaconvolve()
scipy.signal._signaltools.oaconvolve (in1, in2, mode = "full", axes = None)
Convolve two N-dimensional arrays using the overlap-add method.
Convolve `in1` and `in2` using the overlap-add method, with
the output size determined by the `mode` argument.
This is generally much faster than `convolve` for large arrays (n > ~500),
and generally much faster than `fftconvolve` when one array is much
larger than the other, but can be slower when only a few output values are
needed or when the arrays are very similar in shape, and can only
output float arrays (int or object array inputs will be cast to float).
Parameters
----------
in1 : array_like
    First input.
in2 : array_like
    Second input. Should have the same number of dimensions as `in1`.
mode : str {'full', 'valid', 'same'}, optional
    A string indicating the size of the output:
    ``full``
       The output is the full discrete linear convolution
       of the inputs. (Default)
    ``valid``
       The output consists only of those elements that do not
       rely on the zero-padding. In 'valid' mode, either `in1` or `in2`
       must be at least as large as the other in every dimension.
    ``same``
       The output is the same size as `in1`, centered
       with respect to the 'full' output.
axes : int or array_like of ints or None, optional
    Axes over which to compute the convolution.
    The default is over all axes.
Returns
-------
out : array
    An N-dimensional array containing a subset of the discrete linear
    convolution of `in1` with `in2`.
See Also
--------
convolve : Uses the direct convolution or FFT convolution algorithm
           depending on which is faster.
fftconvolve : An implementation of convolution using FFT.
Notes
-----
.. versionadded:: 1.4.0
References
----------
.. [1] Wikipedia, "Overlap-add_method".
       https://en.wikipedia.org/wiki/Overlap-add_method
.. [2] Richard G. Lyons. Understanding Digital Signal Processing,
       Third Edition, 2011. Chapter 13.10.
       ISBN 13: 978-0137-02741-5
Examples
--------
Convolve a 100,000 sample signal with a 512-sample filter.
>>> import numpy as np
>>> from scipy import signal
>>> rng = np.random.default_rng()
>>> sig = rng.standard_normal(100000)
>>> filt = signal.firwin(512, 0.01)
>>> fsig = signal.oaconvolve(sig, filt)
>>> import matplotlib.pyplot as plt
>>> fig, (ax_orig, ax_mag) = plt.subplots(2, 1)
>>> ax_orig.plot(sig)
>>> ax_orig.set_title('White noise')
>>> ax_mag.plot(fsig)
>>> ax_mag.set_title('Filtered noise')
>>> fig.tight_layout()
>>> fig.show()
Definition at line 786 of file _signaltools.py.
References _apply_conv_mode(), _calc_oa_lens(), _freq_domain_conv(), _init_freq_conv_axes(), and fftconvolve().
order_filter()
scipy.signal._signaltools.order_filter (a, domain, rank)
Perform an order filter on an N-D array.
Perform an order filter on the array in. The domain argument acts as a
mask centered over each pixel. The non-zero elements of domain are
used to select elements surrounding each input pixel which are placed
in a list. The list is sorted, and the output for that pixel is the
element corresponding to rank in the sorted list.
Parameters
----------
a : ndarray
    The N-dimensional input array.
domain : array_like
    A mask array with the same number of dimensions as `a`.
    Each dimension should have an odd number of elements.
rank : int
    A non-negative integer which selects the element from the
    sorted list (0 corresponds to the smallest element, 1 is the
    next smallest element, etc.).
Returns
-------
out : ndarray
    The results of the order filter in an array with the same
    shape as `a`.
Examples
--------
>>> import numpy as np
>>> from scipy import signal
>>> x = np.arange(25).reshape(5, 5)
>>> domain = np.identity(3)
>>> x
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])
>>> signal.order_filter(x, domain, 0)
array([[  0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   1.,   2.,   0.],
       [  0.,   5.,   6.,   7.,   0.],
       [  0.,  10.,  11.,  12.,   0.],
       [  0.,   0.,   0.,   0.,   0.]])
>>> signal.order_filter(x, domain, 2)
array([[  6.,   7.,   8.,   9.,   4.],
       [ 11.,  12.,  13.,  14.,   9.],
       [ 16.,  17.,  18.,  19.,  14.],
       [ 21.,  22.,  23.,  24.,  19.],
       [ 20.,  21.,  22.,  23.,  24.]])
Definition at line 1437 of file _signaltools.py.
resample()
scipy.signal._signaltools.resample (x, num, t = None, axis = 0, window = None, domain = 'time')
Resample `x` to `num` samples using Fourier method along the given axis.
The resampled signal starts at the same value as `x` but is sampled
with a spacing of ``len(x) / num * (spacing of x)``.  Because a
Fourier method is used, the signal is assumed to be periodic.
Parameters
----------
x : array_like
    The data to be resampled.
num : int
    The number of samples in the resampled signal.
t : array_like, optional
    If `t` is given, it is assumed to be the equally spaced sample
    positions associated with the signal data in `x`.
axis : int, optional
    The axis of `x` that is resampled.  Default is 0.
window : array_like, callable, string, float, or tuple, optional
    Specifies the window applied to the signal in the Fourier
    domain.  See below for details.
domain : string, optional
    A string indicating the domain of the input `x`:
    ``time`` Consider the input `x` as time-domain (Default),
    ``freq`` Consider the input `x` as frequency-domain.
Returns
-------
resampled_x or (resampled_x, resampled_t)
    Either the resampled array, or, if `t` was given, a tuple
    containing the resampled array and the corresponding resampled
    positions.
See Also
--------
decimate : Downsample the signal after applying an FIR or IIR filter.
resample_poly : Resample using polyphase filtering and an FIR filter.
Notes
-----
The argument `window` controls a Fourier-domain window that tapers
the Fourier spectrum before zero-padding to alleviate ringing in
the resampled values for sampled signals you didn't intend to be
interpreted as band-limited.
If `window` is a function, then it is called with a vector of inputs
indicating the frequency bins (i.e. fftfreq(x.shape[axis])).
If `window` is an array of the same length as `x.shape[axis]` it is
assumed to be the window to be applied directly in the Fourier
domain (with dc and low-frequency first).
For any other type of `window`, the function `scipy.signal.get_window`
is called to generate the window.
The first sample of the returned vector is the same as the first
sample of the input vector.  The spacing between samples is changed
from ``dx`` to ``dx * len(x) / num``.
If `t` is not None, then it is used solely to calculate the resampled
positions `resampled_t`
As noted, `resample` uses FFT transformations, which can be very
slow if the number of input or output samples is large and prime;
see `scipy.fft.fft`.
Examples
--------
Note that the end of the resampled data rises to meet the first
sample of the next cycle:
>>> import numpy as np
>>> from scipy import signal
>>> x = np.linspace(0, 10, 20, endpoint=False)
>>> y = np.cos(-x**2/6.0)
>>> f = signal.resample(y, 100)
>>> xnew = np.linspace(0, 10, 100, endpoint=False)
>>> import matplotlib.pyplot as plt
>>> plt.plot(x, y, 'go-', xnew, f, '.-', 10, y[0], 'ro')
>>> plt.legend(['data', 'resampled'], loc='best')
>>> plt.show()
Definition at line 3036 of file _signaltools.py.
resample_poly()
scipy.signal._signaltools.resample_poly (x, up, down, axis = 0, window = ('kaiser', 5.0), padtype = 'constant', cval = None)
Resample `x` along the given axis using polyphase filtering.
The signal `x` is upsampled by the factor `up`, a zero-phase low-pass
FIR filter is applied, and then it is downsampled by the factor `down`.
The resulting sample rate is ``up / down`` times the original sample
rate. By default, values beyond the boundary of the signal are assumed
to be zero during the filtering step.
Parameters
----------
x : array_like
    The data to be resampled.
up : int
    The upsampling factor.
down : int
    The downsampling factor.
axis : int, optional
    The axis of `x` that is resampled. Default is 0.
window : string, tuple, or array_like, optional
    Desired window to use to design the low-pass filter, or the FIR filter
    coefficients to employ. See below for details.
padtype : string, optional
    `constant`, `line`, `mean`, `median`, `maximum`, `minimum` or any of
    the other signal extension modes supported by `scipy.signal.upfirdn`.
    Changes assumptions on values beyond the boundary. If `constant`,
    assumed to be `cval` (default zero). If `line` assumed to continue a
    linear trend defined by the first and last points. `mean`, `median`,
    `maximum` and `minimum` work as in `np.pad` and assume that the values
    beyond the boundary are the mean, median, maximum or minimum
    respectively of the array along the axis.
    .. versionadded:: 1.4.0
cval : float, optional
    Value to use if `padtype='constant'`. Default is zero.
    .. versionadded:: 1.4.0
Returns
-------
resampled_x : array
    The resampled array.
See Also
--------
decimate : Downsample the signal after applying an FIR or IIR filter.
resample : Resample up or down using the FFT method.
Notes
-----
This polyphase method will likely be faster than the Fourier method
in `scipy.signal.resample` when the number of samples is large and
prime, or when the number of samples is large and `up` and `down`
share a large greatest common denominator. The length of the FIR
filter used will depend on ``max(up, down) // gcd(up, down)``, and
the number of operations during polyphase filtering will depend on
the filter length and `down` (see `scipy.signal.upfirdn` for details).
The argument `window` specifies the FIR low-pass filter design.
If `window` is an array_like it is assumed to be the FIR filter
coefficients. Note that the FIR filter is applied after the upsampling
step, so it should be designed to operate on a signal at a sampling
frequency higher than the original by a factor of `up//gcd(up, down)`.
This function's output will be centered with respect to this array, so it
is best to pass a symmetric filter with an odd number of samples if, as
is usually the case, a zero-phase filter is desired.
For any other type of `window`, the functions `scipy.signal.get_window`
and `scipy.signal.firwin` are called to generate the appropriate filter
coefficients.
The first sample of the returned vector is the same as the first
sample of the input vector. The spacing between samples is changed
from ``dx`` to ``dx * down / float(up)``.
Examples
--------
By default, the end of the resampled data rises to meet the first
sample of the next cycle for the FFT method, and gets closer to zero
for the polyphase method:
>>> import numpy as np
>>> from scipy import signal
>>> import matplotlib.pyplot as plt
>>> x = np.linspace(0, 10, 20, endpoint=False)
>>> y = np.cos(-x**2/6.0)
>>> f_fft = signal.resample(y, 100)
>>> f_poly = signal.resample_poly(y, 100, 20)
>>> xnew = np.linspace(0, 10, 100, endpoint=False)
>>> plt.plot(xnew, f_fft, 'b.-', xnew, f_poly, 'r.-')
>>> plt.plot(x, y, 'ko-')
>>> plt.plot(10, y[0], 'bo', 10, 0., 'ro')  # boundaries
>>> plt.legend(['resample', 'resamp_poly', 'data'], loc='best')
>>> plt.show()
This default behaviour can be changed by using the padtype option:
>>> N = 5
>>> x = np.linspace(0, 1, N, endpoint=False)
>>> y = 2 + x**2 - 1.7*np.sin(x) + .2*np.cos(11*x)
>>> y2 = 1 + x**3 + 0.1*np.sin(x) + .1*np.cos(11*x)
>>> Y = np.stack([y, y2], axis=-1)
>>> up = 4
>>> xr = np.linspace(0, 1, N*up, endpoint=False)
>>> y2 = signal.resample_poly(Y, up, 1, padtype='constant')
>>> y3 = signal.resample_poly(Y, up, 1, padtype='mean')
>>> y4 = signal.resample_poly(Y, up, 1, padtype='line')
>>> for i in [0,1]:
...     plt.figure()
...     plt.plot(xr, y4[:,i], 'g.', label='line')
...     plt.plot(xr, y3[:,i], 'y.', label='mean')
...     plt.plot(xr, y2[:,i], 'r.', label='constant')
...     plt.plot(x, Y[:,i], 'k-')
...     plt.legend()
>>> plt.show()
Definition at line 3224 of file _signaltools.py.
References scipy.signal._fir_filter_design.firwin().
Referenced by decimate().
residue()
scipy.signal._signaltools.residue (b, a, tol = 1e-3, rtype = 'avg')
Compute partial-fraction expansion of b(s) / a(s).
If `M` is the degree of numerator `b` and `N` the degree of denominator
`a`::
          b(s)     b[0] s**(M) + b[1] s**(M-1) + ... + b[M]
  H(s) = ------ = ------------------------------------------
          a(s)     a[0] s**(N) + a[1] s**(N-1) + ... + a[N]
then the partial-fraction expansion H(s) is defined as::
           r[0]       r[1]             r[-1]
       = -------- + -------- + ... + --------- + k(s)
         (s-p[0])   (s-p[1])         (s-p[-1])
If there are any repeated roots (closer together than `tol`), then H(s)
has terms like::
      r[i]      r[i+1]              r[i+n-1]
    -------- + ----------- + ... + -----------
    (s-p[i])  (s-p[i])**2          (s-p[i])**n
This function is used for polynomials in positive powers of s or z,
such as analog filters or digital filters in controls engineering.  For
negative powers of z (typical for digital filters in DSP), use `residuez`.
See Notes for details about the algorithm.
Parameters
----------
b : array_like
    Numerator polynomial coefficients.
a : array_like
    Denominator polynomial coefficients.
tol : float, optional
    The tolerance for two roots to be considered equal in terms of
    the distance between them. Default is 1e-3. See `unique_roots`
    for further details.
rtype : {'avg', 'min', 'max'}, optional
    Method for computing a root to represent a group of identical roots.
    Default is 'avg'. See `unique_roots` for further details.
Returns
-------
r : ndarray
    Residues corresponding to the poles. For repeated poles, the residues
    are ordered to correspond to ascending by power fractions.
p : ndarray
    Poles ordered by magnitude in ascending order.
k : ndarray
    Coefficients of the direct polynomial term.
See Also
--------
invres, residuez, numpy.poly, unique_roots
Notes
-----
The "deflation through subtraction" algorithm is used for
computations --- method 6 in [1]_.
The form of partial fraction expansion depends on poles multiplicity in
the exact mathematical sense. However there is no way to exactly
determine multiplicity of roots of a polynomial in numerical computing.
Thus you should think of the result of `residue` with given `tol` as
partial fraction expansion computed for the denominator composed of the
computed poles with empirically determined multiplicity. The choice of
`tol` can drastically change the result if there are close poles.
References
----------
.. [1] J. F. Mahoney, B. D. Sivazlian, "Partial fractions expansion: a
       review of computational methodology and efficiency", Journal of
       Computational and Applied Mathematics, Vol. 9, 1983.
Definition at line 2711 of file _signaltools.py.
References cmplx_sort(), and unique_roots().
residuez()
scipy.signal._signaltools.residuez (b, a, tol = 1e-3, rtype = 'avg')
Compute partial-fraction expansion of b(z) / a(z).
If `M` is the degree of numerator `b` and `N` the degree of denominator
`a`::
            b(z)     b[0] + b[1] z**(-1) + ... + b[M] z**(-M)
    H(z) = ------ = ------------------------------------------
            a(z)     a[0] + a[1] z**(-1) + ... + a[N] z**(-N)
then the partial-fraction expansion H(z) is defined as::
             r[0]                   r[-1]
     = --------------- + ... + ---------------- + k[0] + k[1]z**(-1) ...
       (1-p[0]z**(-1))         (1-p[-1]z**(-1))
If there are any repeated roots (closer than `tol`), then the partial
fraction expansion has terms like::
         r[i]              r[i+1]                    r[i+n-1]
    -------------- + ------------------ + ... + ------------------
    (1-p[i]z**(-1))  (1-p[i]z**(-1))**2         (1-p[i]z**(-1))**n
This function is used for polynomials in negative powers of z,
such as digital filters in DSP.  For positive powers, use `residue`.
See Notes of `residue` for details about the algorithm.
Parameters
----------
b : array_like
    Numerator polynomial coefficients.
a : array_like
    Denominator polynomial coefficients.
tol : float, optional
    The tolerance for two roots to be considered equal in terms of
    the distance between them. Default is 1e-3. See `unique_roots`
    for further details.
rtype : {'avg', 'min', 'max'}, optional
    Method for computing a root to represent a group of identical roots.
    Default is 'avg'. See `unique_roots` for further details.
Returns
-------
r : ndarray
    Residues corresponding to the poles. For repeated poles, the residues
    are ordered to correspond to ascending by power fractions.
p : ndarray
    Poles ordered by magnitude in ascending order.
k : ndarray
    Coefficients of the direct polynomial term.
See Also
--------
invresz, residue, unique_roots
Definition at line 2826 of file _signaltools.py.
References cmplx_sort(), and unique_roots().
sosfilt()
scipy.signal._signaltools.sosfilt (sos, x, axis = -1, zi = None)
Filter data along one dimension using cascaded second-order sections.
Filter a data sequence, `x`, using a digital IIR filter defined by
`sos`.
Parameters
----------
sos : array_like
    Array of second-order filter coefficients, must have shape
    ``(n_sections, 6)``. Each row corresponds to a second-order
    section, with the first three columns providing the numerator
    coefficients and the last three providing the denominator
    coefficients.
x : array_like
    An N-dimensional input array.
axis : int, optional
    The axis of the input data array along which to apply the
    linear filter. The filter is applied to each subarray along
    this axis.  Default is -1.
zi : array_like, optional
    Initial conditions for the cascaded filter delays.  It is a (at
    least 2D) vector of shape ``(n_sections, ..., 2, ...)``, where
    ``..., 2, ...`` denotes the shape of `x`, but with ``x.shape[axis]``
    replaced by 2.  If `zi` is None or is not given then initial rest
    (i.e. all zeros) is assumed.
    Note that these initial conditions are *not* the same as the initial
    conditions given by `lfiltic` or `lfilter_zi`.
Returns
-------
y : ndarray
    The output of the digital filter.
zf : ndarray, optional
    If `zi` is None, this is not returned, otherwise, `zf` holds the
    final filter delay values.
See Also
--------
zpk2sos, sos2zpk, sosfilt_zi, sosfiltfilt, sosfreqz
Notes
-----
The filter function is implemented as a series of second-order filters
with direct-form II transposed structure. It is designed to minimize
numerical precision errors for high-order filters.
.. versionadded:: 0.16.0
Examples
--------
Plot a 13th-order filter's impulse response using both `lfilter` and
`sosfilt`, showing the instability that results from trying to do a
13th-order filter in a single stage (the numerical error pushes some poles
outside of the unit circle):
>>> import matplotlib.pyplot as plt
>>> from scipy import signal
>>> b, a = signal.ellip(13, 0.009, 80, 0.05, output='ba')
>>> sos = signal.ellip(13, 0.009, 80, 0.05, output='sos')
>>> x = signal.unit_impulse(700)
>>> y_tf = signal.lfilter(b, a, x)
>>> y_sos = signal.sosfilt(sos, x)
>>> plt.plot(y_tf, 'r', label='TF')
>>> plt.plot(y_sos, 'k', label='SOS')
>>> plt.legend(loc='best')
>>> plt.show()
Definition at line 4233 of file _signaltools.py.
References scipy.signal._filter_design._validate_sos().
Referenced by scipy.signal.tests.test_signaltools.assert_allclose_cast(), decimate(), and sosfiltfilt().
sosfilt_zi()
scipy.signal._signaltools.sosfilt_zi (sos)
Construct initial conditions for sosfilt for step response steady-state.
Compute an initial state `zi` for the `sosfilt` function that corresponds
to the steady state of the step response.
A typical use of this function is to set the initial state so that the
output of the filter starts at the same value as the first element of
the signal to be filtered.
Parameters
----------
sos : array_like
    Array of second-order filter coefficients, must have shape
    ``(n_sections, 6)``. See `sosfilt` for the SOS filter format
    specification.
Returns
-------
zi : ndarray
    Initial conditions suitable for use with ``sosfilt``, shape
    ``(n_sections, 2)``.
See Also
--------
sosfilt, zpk2sos
Notes
-----
.. versionadded:: 0.16.0
Examples
--------
Filter a rectangular pulse that begins at time 0, with and without
the use of the `zi` argument of `scipy.signal.sosfilt`.
>>> import numpy as np
>>> from scipy import signal
>>> import matplotlib.pyplot as plt
>>> sos = signal.butter(9, 0.125, output='sos')
>>> zi = signal.sosfilt_zi(sos)
>>> x = (np.arange(250) < 100).astype(int)
>>> f1 = signal.sosfilt(sos, x)
>>> f2, zo = signal.sosfilt(sos, x, zi=zi)
>>> plt.plot(x, 'k--', label='x')
>>> plt.plot(f1, 'b', alpha=0.5, linewidth=2, label='filtered')
>>> plt.plot(f2, 'g', alpha=0.25, linewidth=4, label='filtered with zi')
>>> plt.legend(loc='best')
>>> plt.show()
Definition at line 3734 of file _signaltools.py.
References lfilter_zi().
Referenced by sosfiltfilt().
sosfiltfilt()
scipy.signal._signaltools.sosfiltfilt (sos, x, axis = -1, padtype = 'odd', padlen = None)
A forward-backward digital filter using cascaded second-order sections.
See `filtfilt` for more complete information about this method.
Parameters
----------
sos : array_like
    Array of second-order filter coefficients, must have shape
    ``(n_sections, 6)``. Each row corresponds to a second-order
    section, with the first three columns providing the numerator
    coefficients and the last three providing the denominator
    coefficients.
x : array_like
    The array of data to be filtered.
axis : int, optional
    The axis of `x` to which the filter is applied.
    Default is -1.
padtype : str or None, optional
    Must be 'odd', 'even', 'constant', or None.  This determines the
    type of extension to use for the padded signal to which the filter
    is applied.  If `padtype` is None, no padding is used.  The default
    is 'odd'.
padlen : int or None, optional
    The number of elements by which to extend `x` at both ends of
    `axis` before applying the filter.  This value must be less than
    ``x.shape[axis] - 1``.  ``padlen=0`` implies no padding.
    The default value is::
        3 * (2 * len(sos) + 1 - min((sos[:, 2] == 0).sum(),
                                    (sos[:, 5] == 0).sum()))
    The extra subtraction at the end attempts to compensate for poles
    and zeros at the origin (e.g. for odd-order filters) to yield
    equivalent estimates of `padlen` to those of `filtfilt` for
    second-order section filters built with `scipy.signal` functions.
Returns
-------
y : ndarray
    The filtered output with the same shape as `x`.
See Also
--------
filtfilt, sosfilt, sosfilt_zi, sosfreqz
Notes
-----
.. versionadded:: 0.18.0
Examples
--------
>>> import numpy as np
>>> from scipy.signal import sosfiltfilt, butter
>>> import matplotlib.pyplot as plt
>>> rng = np.random.default_rng()
Create an interesting signal to filter.
>>> n = 201
>>> t = np.linspace(0, 1, n)
>>> x = 1 + (t < 0.5) - 0.25*t**2 + 0.05*rng.standard_normal(n)
Create a lowpass Butterworth filter, and use it to filter `x`.
>>> sos = butter(4, 0.125, output='sos')
>>> y = sosfiltfilt(sos, x)
For comparison, apply an 8th order filter using `sosfilt`.  The filter
is initialized using the mean of the first four values of `x`.
>>> from scipy.signal import sosfilt, sosfilt_zi
>>> sos8 = butter(8, 0.125, output='sos')
>>> zi = x[:4].mean() * sosfilt_zi(sos8)
>>> y2, zo = sosfilt(sos8, x, zi=zi)
Plot the results.  Note that the phase of `y` matches the input, while
`y2` has a significant phase delay.
>>> plt.plot(t, x, alpha=0.5, label='x(t)')
>>> plt.plot(t, y, label='y(t)')
>>> plt.plot(t, y2, label='y2(t)')
>>> plt.legend(framealpha=1, shadow=True)
>>> plt.grid(alpha=0.25)
>>> plt.xlabel('t')
>>> plt.show()
Definition at line 4345 of file _signaltools.py.
References _validate_pad(), scipy.signal._filter_design._validate_sos(), sosfilt(), and sosfilt_zi().
Referenced by decimate(), and scipy.signal.tests.test_signaltools.TestSOSFiltFilt.test_equivalence().
unique_roots()
scipy.signal._signaltools.unique_roots (p, tol = 1e-3, rtype = 'min')
Determine unique roots and their multiplicities from a list of roots.
Parameters
----------
p : array_like
    The list of roots.
tol : float, optional
    The tolerance for two roots to be considered equal in terms of
    the distance between them. Default is 1e-3. Refer to Notes about
    the details on roots grouping.
rtype : {'max', 'maximum', 'min', 'minimum', 'avg', 'mean'}, optional
    How to determine the returned root if multiple roots are within
    `tol` of each other.
      - 'max', 'maximum': pick the maximum of those roots
      - 'min', 'minimum': pick the minimum of those roots
      - 'avg', 'mean': take the average of those roots
    When finding minimum or maximum among complex roots they are compared
    first by the real part and then by the imaginary part.
Returns
-------
unique : ndarray
    The list of unique roots.
multiplicity : ndarray
    The multiplicity of each root.
Notes
-----
If we have 3 roots ``a``, ``b`` and ``c``, such that ``a`` is close to
``b`` and ``b`` is close to ``c`` (distance is less than `tol`), then it
doesn't necessarily mean that ``a`` is close to ``c``. It means that roots
grouping is not unique. In this function we use "greedy" grouping going
through the roots in the order they are given in the input `p`.
This utility function is not specific to roots but can be used for any
sequence of values for which uniqueness and multiplicity has to be
determined. For a more general routine, see `numpy.unique`.
Examples
--------
>>> from scipy import signal
>>> vals = [0, 1.3, 1.31, 2.8, 1.25, 2.2, 10.3]
>>> uniq, mult = signal.unique_roots(vals, tol=2e-2, rtype='avg')
Check which roots have multiplicity larger than 1:
>>> uniq[mult > 1]
array([ 1.305])
Definition at line 2497 of file _signaltools.py.
Referenced by residue(), and residuez().
vectorstrength()
scipy.signal._signaltools.vectorstrength (events, period)
Determine the vector strength of the events corresponding to the given
period.
The vector strength is a measure of phase synchrony, how well the
timing of the events is synchronized to a single period of a periodic
signal.
If multiple periods are used, calculate the vector strength of each.
This is called the "resonating vector strength".
Parameters
----------
events : 1D array_like
    An array of time points containing the timing of the events.
period : float or array_like
    The period of the signal that the events should synchronize to.
    The period is in the same units as `events`.  It can also be an array
    of periods, in which case the outputs are arrays of the same length.
Returns
-------
strength : float or 1D array
    The strength of the synchronization.  1.0 is perfect synchronization
    and 0.0 is no synchronization.  If `period` is an array, this is also
    an array with each element containing the vector strength at the
    corresponding period.
phase : float or array
    The phase that the events are most strongly synchronized to in radians.
    If `period` is an array, this is also an array with each element
    containing the phase for the corresponding period.
References
----------
van Hemmen, JL, Longtin, A, and Vollmayr, AN. Testing resonating vector
    strength: Auditory system, electric fish, and noise.
    Chaos 21, 047508 (2011);
    :doi:`10.1063/1.3670512`.
van Hemmen, JL.  Vector strength after Goldberg, Brown, and von Mises:
    biological and mathematical perspectives.  Biol Cybern.
    2013 Aug;107(4):385-96. :doi:`10.1007/s00422-013-0561-7`.
van Hemmen, JL and Vollmayr, AN.  Resonating vector strength: what happens
    when we vary the "probing" frequency while keeping the spike times
    fixed.  Biol Cybern. 2013 Aug;107(4):491-94.
    :doi:`10.1007/s00422-013-0560-8`.
Definition at line 3432 of file _signaltools.py.
wiener()
scipy.signal._signaltools.wiener (im, mysize = None, noise = None)
Perform a Wiener filter on an N-dimensional array.
Apply a Wiener filter to the N-dimensional array `im`.
Parameters
----------
im : ndarray
    An N-dimensional array.
mysize : int or array_like, optional
    A scalar or an N-length list giving the size of the Wiener filter
    window in each dimension.  Elements of mysize should be odd.
    If mysize is a scalar, then this scalar is used as the size
    in each dimension.
noise : float, optional
    The noise-power to use. If None, then noise is estimated as the
    average of the local variance of the input.
Returns
-------
out : ndarray
    Wiener filtered result with the same shape as `im`.
Notes
-----
This implementation is similar to wiener2 in Matlab/Octave.
For more details see [1]_
References
----------
.. [1] Lim, Jae S., Two-Dimensional Signal and Image Processing,
       Englewood Cliffs, NJ, Prentice Hall, 1990, p. 548.
Examples
--------
>>> from scipy.datasets import face
>>> from scipy.signal import wiener
>>> import matplotlib.pyplot as plt
>>> import numpy as np
>>> rng = np.random.default_rng()
>>> img = rng.random((40, 40))    #Create a random image
>>> filtered_img = wiener(img, (5, 5))  #Filter the image
>>> f, (plot1, plot2) = plt.subplots(1, 2)
>>> plot1.imshow(img)
>>> plot2.imshow(filtered_img)
>>> plt.show()
Definition at line 1589 of file _signaltools.py.
References correlate().
Variable Documentation
__all__
list scipy.signal._signaltools.__all__ private
Initial value:
=  ['correlate', 'correlation_lags', 'correlate2d',
           'convolve', 'convolve2d', 'fftconvolve', 'oaconvolve',
           'order_filter', 'medfilt', 'medfilt2d', 'wiener', 'lfilter',
           'lfiltic', 'sosfilt', 'deconvolve', 'hilbert', 'hilbert2',
           'cmplx_sort', 'unique_roots', 'invres', 'invresz', 'residue',
           'residuez', 'resample', 'resample_poly', 'detrend',
           'lfilter_zi', 'sosfilt_zi', 'sosfiltfilt', 'choose_conv_method',
           'filtfilt', 'decimate', 'vectorstrength']
Definition at line 25 of file _signaltools.py.
_boundarydict
dict scipy.signal._signaltools._boundarydict protected
Initial value:
=  {'fill': 0, 'pad': 0, 'wrap': 2, 'circular': 2, 'symm': 1,
                 'symmetric': 1, 'reflect': 4}
Definition at line 37 of file _signaltools.py.
_modedict
dict scipy.signal._signaltools._modedict = {'valid': 0, 'same': 1, 'full': 2} protected
Definition at line 35 of file _signaltools.py.