Code Cloning Analysis: fontTools.varLib.errors.VarLibMergeError Class Reference
fontTools.varLib.errors.VarLibMergeError Class Reference
Public Member Functions
__init__ (self, merger=None, **kwargs)
reason (self)
offender (self)
details (self)
__str__ (self)
Public Attributes
merger = merger
list stack = kwargs["stack"]
cause = kwargs
Protected Member Functions
_master_name (self, ix)
Detailed Description
Raised when input data cannot be merged into a variable font.
Definition at line 12 of file errors.py.
Constructor & Destructor Documentation
__init__()
fontTools.varLib.errors.VarLibMergeError.__init__ (self, merger = None, ** kwargs)
Definition at line 15 of file errors.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__str__()
fontTools.varLib.errors.VarLibMergeError.__str__ (self)
Definition at line 59 of file errors.py.
Referenced by numpy.polynomial._polybase.ABCPolyBase._get_coefficients().
_master_name()
fontTools.varLib.errors.VarLibMergeError._master_name (self, ix) protected
Definition at line 30 of file errors.py.
details()
fontTools.varLib.errors.VarLibMergeError.details (self)
Definition at line 52 of file errors.py.
offender()
fontTools.varLib.errors.VarLibMergeError.offender (self)
Definition at line 40 of file errors.py.
reason()
fontTools.varLib.errors.VarLibMergeError.reason (self)
Definition at line 27 of file errors.py.
Member Data Documentation
cause
fontTools.varLib.errors.VarLibMergeError.cause = kwargs
Definition at line 24 of file errors.py.
merger
fontTools.varLib.errors.VarLibMergeError.merger = merger
Definition at line 16 of file errors.py.
stack
list fontTools.varLib.errors.VarLibMergeError.stack = kwargs["stack"]
Definition at line 20 of file errors.py.
Referenced by matplotlib.dviread.Vf._read(), matplotlib.dviread.Dvi._read_arg(), joblib.numpy_pickle.NumpyUnpickler.load_build(), and joblib.numpy_pickle_compat.ZipNumpyUnpickler.load_build().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/varLib/errors.py