Code Cloning Analysis: scipy.optimize._optimize Namespace Reference
scipy.optimize._optimize Namespace Reference
Classes
class _Brute_Wrapper
class _LineSearchError
class _MaxFuncCallError
class BracketError
class Brent
class MemoizeJac
class OptimizeResult
class OptimizeWarning
Functions
_indenter (s, n=0)
_float_formatter_10 (x)
_dict_formatter (d, n=0, mplus=1, sorter=None)
_wrap_callback (callback, method=None)
_call_callback_maybe_halt (callback, res)
_check_unknown_options (unknown_options)
is_finite_scalar (x)
vecnorm (x, ord=2)
_prepare_scalar_function (fun, x0, jac=None, args=(), bounds=None, epsilon=None, finite_diff_rel_step=None, hess=None)
_clip_x_for_func (func, bounds)
_check_clip_x (x, bounds)
rosen (x)
rosen_der (x)
rosen_hess (x)
rosen_hess_prod (x, p)
_wrap_scalar_function (function, args)
_wrap_scalar_function_maxfun_validation (function, args, maxfun)
fmin (func, x0, args=(), xtol=1e-4, ftol=1e-4, maxiter=None, maxfun=None, full_output=0, disp=1, retall=0, callback=None, initial_simplex=None)
_minimize_neldermead (func, x0, args=(), callback=None, maxiter=None, maxfev=None, disp=False, return_all=False, initial_simplex=None, xatol=1e-4, fatol=1e-4, adaptive=False, bounds=None, **unknown_options)
approx_fprime (xk, f, epsilon=_epsilon, *args)
check_grad (func, grad, x0, *args, epsilon=_epsilon, direction='all', seed=None)
approx_fhess_p (x0, p, fprime, epsilon, *args)
_line_search_wolfe12 (f, fprime, xk, pk, gfk, old_fval, old_old_fval, **kwargs)
fmin_bfgs (f, x0, fprime=None, args=(), gtol=1e-5, norm=Inf, epsilon=_epsilon, maxiter=None, full_output=0, disp=1, retall=0, callback=None, xrtol=0)
_minimize_bfgs (fun, x0, args=(), jac=None, callback=None, gtol=1e-5, norm=Inf, eps=_epsilon, maxiter=None, disp=False, return_all=False, finite_diff_rel_step=None, xrtol=0, **unknown_options)
_print_success_message_or_warn (warnflag, message, warntype=None)
fmin_cg (f, x0, fprime=None, args=(), gtol=1e-5, norm=Inf, epsilon=_epsilon, maxiter=None, full_output=0, disp=1, retall=0, callback=None)
_minimize_cg (fun, x0, args=(), jac=None, callback=None, gtol=1e-5, norm=Inf, eps=_epsilon, maxiter=None, disp=False, return_all=False, finite_diff_rel_step=None, **unknown_options)
fmin_ncg (f, x0, fprime, fhess_p=None, fhess=None, args=(), avextol=1e-5, epsilon=_epsilon, maxiter=None, full_output=0, disp=1, retall=0, callback=None)
_minimize_newtoncg (fun, x0, args=(), jac=None, hess=None, hessp=None, callback=None, xtol=1e-5, eps=_epsilon, maxiter=None, disp=False, return_all=False, **unknown_options)
fminbound (func, x1, x2, args=(), xtol=1e-5, maxfun=500, full_output=0, disp=1)
_minimize_scalar_bounded (func, bounds, args=(), xatol=1e-5, maxiter=500, disp=0, **unknown_options)
brent (func, args=(), brack=None, tol=1.48e-8, full_output=0, maxiter=500)
_minimize_scalar_brent (func, brack=None, args=(), xtol=1.48e-8, maxiter=500, disp=0, **unknown_options)
golden (func, args=(), brack=None, tol=_epsilon, full_output=0, maxiter=5000)
_minimize_scalar_golden (func, brack=None, args=(), xtol=_epsilon, maxiter=5000, disp=0, **unknown_options)
bracket (func, xa=0.0, xb=1.0, args=(), grow_limit=110.0, maxiter=1000)
_recover_from_bracket_error (solver, fun, bracket, args, **options)
_line_for_search (x0, alpha, lower_bound, upper_bound)
_linesearch_powell (func, p, xi, tol=1e-3, lower_bound=None, upper_bound=None, fval=None)
fmin_powell (func, x0, args=(), xtol=1e-4, ftol=1e-4, maxiter=None, maxfun=None, full_output=0, disp=1, retall=0, callback=None, direc=None)
_minimize_powell (func, x0, args=(), callback=None, bounds=None, xtol=1e-4, ftol=1e-4, maxiter=None, maxfev=None, disp=False, direc=None, return_all=False, **unknown_options)
_endprint (x, flag, fval, maxfun, xtol, disp)
brute (func, ranges, args=(), Ns=20, full_output=0, finish=fmin, disp=False, workers=1)
show_options (solver=None, method=None, disp=True)
Variables
list __all__
str __docformat__ = "restructuredtext en"
dict _status_message
_epsilon = sqrt(np.finfo(float).eps)
Function Documentation
_call_callback_maybe_halt()
scipy.optimize._optimize._call_callback_maybe_halt (callback, res) protected
Call wrapped callback; return True if minimization should stop.
Parameters
----------
callback : callable or None
    A user-provided callback wrapped with `_wrap_callback`
res : OptimizeResult
    Information about the current iterate
Returns
-------
halt : bool
    True if minimization should stop
Definition at line 156 of file _optimize.py.
Referenced by _minimize_bfgs(), _minimize_cg(), scipy.optimize._lbfgsb_py._minimize_lbfgsb(), _minimize_neldermead(), _minimize_newtoncg(), _minimize_powell(), and scipy.optimize._trustregion._minimize_trust_region().
_check_clip_x()
scipy.optimize._optimize._check_clip_x (x, bounds) protected
Definition at line 402 of file _optimize.py.
_check_unknown_options()
scipy.optimize._optimize._check_unknown_options (unknown_options) protected
Definition at line 267 of file _optimize.py.
_clip_x_for_func()
scipy.optimize._optimize._clip_x_for_func (func, bounds) protected
Definition at line 389 of file _optimize.py.
_dict_formatter()
scipy.optimize._optimize._dict_formatter (d, n = 0, mplus = 1, sorter = None) protected
Pretty printer for dictionaries
`n` keeps track of the starting indentation;
lines are indented by this much after a line break.
`mplus` is additional left padding applied to keys
Definition at line 107 of file _optimize.py.
References _dict_formatter(), and _indenter().
Referenced by _dict_formatter().
_endprint()
scipy.optimize._optimize._endprint (x, flag, fval, maxfun, xtol, disp) protected
Definition at line 3596 of file _optimize.py.
_float_formatter_10()
scipy.optimize._optimize._float_formatter_10 (x) protected
Returns a string representation of a float with exactly ten characters
Definition at line 94 of file _optimize.py.
_indenter()
scipy.optimize._optimize._indenter (s, n = 0) protected
Ensures that lines after the first are indented by the specified amount
Definition at line 85 of file _optimize.py.
Referenced by _dict_formatter().
_line_for_search()
scipy.optimize._optimize._line_for_search (x0, alpha, lower_bound, upper_bound) protected
Given a parameter vector ``x0`` with length ``n`` and a direction
vector ``alpha`` with length ``n``, and lower and upper bounds on
each of the ``n`` parameters, what are the bounds on a scalar
``l`` such that ``lower_bound <= x0 + alpha * l <= upper_bound``.
Parameters
----------
x0 : np.array.
    The vector representing the current location.
    Note ``np.shape(x0) == (n,)``.
alpha : np.array.
    The vector representing the direction.
    Note ``np.shape(alpha) == (n,)``.
lower_bound : np.array.
    The lower bounds for each parameter in ``x0``. If the ``i``th
    parameter in ``x0`` is unbounded below, then ``lower_bound[i]``
    should be ``-np.inf``.
    Note ``np.shape(lower_bound) == (n,)``.
upper_bound : np.array.
    The upper bounds for each parameter in ``x0``. If the ``i``th
    parameter in ``x0`` is unbounded above, then ``upper_bound[i]``
    should be ``np.inf``.
    Note ``np.shape(upper_bound) == (n,)``.
Returns
-------
res : tuple ``(lmin, lmax)``
    The bounds for ``l`` such that
        ``lower_bound[i] <= x0[i] + alpha[i] * l <= upper_bound[i]``
    for all ``i``.
Definition at line 3091 of file _optimize.py.
Referenced by _linesearch_powell(), and _minimize_powell().
_line_search_wolfe12()
scipy.optimize._optimize._line_search_wolfe12 (f, fprime, xk, pk, gfk, old_fval, old_old_fval, ** kwargs) protected
Same as line_search_wolfe1, but fall back to line_search_wolfe2 if
suitable step length is not found, and raise an exception if a
suitable step length is not found.
Raises
------
_LineSearchError
    If no suitable step size is found
Definition at line 1199 of file _optimize.py.
Referenced by _minimize_bfgs(), _minimize_cg(), and _minimize_newtoncg().
_linesearch_powell()
scipy.optimize._optimize._linesearch_powell (func, p, xi, tol = 1e-3, lower_bound = None, upper_bound = None, fval = None) protected
Line-search algorithm using fminbound.
Find the minimium of the function ``func(x0 + alpha*direc)``.
lower_bound : np.array.
    The lower bounds for each parameter in ``x0``. If the ``i``th
    parameter in ``x0`` is unbounded below, then ``lower_bound[i]``
    should be ``-np.inf``.
    Note ``np.shape(lower_bound) == (n,)``.
upper_bound : np.array.
    The upper bounds for each parameter in ``x0``. If the ``i``th
    parameter in ``x0`` is unbounded above, then ``upper_bound[i]``
    should be ``np.inf``.
    Note ``np.shape(upper_bound) == (n,)``.
fval : number.
    ``fval`` is equal to ``func(p)``, the idea is just to avoid
    recomputing it so we can limit the ``fevals``.
Definition at line 3154 of file _optimize.py.
References _line_for_search(), _linesearch_powell(), and _minimize_scalar_bounded().
Referenced by _linesearch_powell(), and _minimize_powell().
_minimize_bfgs()
scipy.optimize._optimize._minimize_bfgs (fun, x0, args = (), jac = None, callback = None, gtol = 1e-5, norm = Inf, eps = _epsilon, maxiter = None, disp = False, return_all = False, finite_diff_rel_step = None, xrtol = 0, ** unknown_options) protected
Minimization of scalar function of one or more variables using the
BFGS algorithm.
Options
-------
disp : bool
    Set to True to print convergence messages.
maxiter : int
    Maximum number of iterations to perform.
gtol : float
    Terminate successfully if gradient norm is less than `gtol`.
norm : float
    Order of norm (Inf is max, -Inf is min).
eps : float or ndarray
    If `jac is None` the absolute step size used for numerical
    approximation of the jacobian via forward differences.
return_all : bool, optional
    Set to True to return a list of the best solution at each of the
    iterations.
finite_diff_rel_step : None or array_like, optional
    If `jac in ['2-point', '3-point', 'cs']` the relative step size to
    use for numerical approximation of the jacobian. The absolute step
    size is computed as ``h = rel_step * sign(x) * max(1, abs(x))``,
    possibly adjusted to fit into the bounds. For ``method='3-point'``
    the sign of `h` is ignored. If None (default) then step is selected
    automatically.
xrtol : float, default: 0
    Relative tolerance for `x`. Terminate successfully if step size is
    less than ``xk * xrtol`` where ``xk`` is the current parameter vector.
Definition at line 1375 of file _optimize.py.
References _call_callback_maybe_halt(), _line_search_wolfe12(), and _prepare_scalar_function().
Referenced by fmin_bfgs(), and scipy.optimize._minimize.minimize().
_minimize_cg()
scipy.optimize._optimize._minimize_cg (fun, x0, args = (), jac = None, callback = None, gtol = 1e-5, norm = Inf, eps = _epsilon, maxiter = None, disp = False, return_all = False, finite_diff_rel_step = None, ** unknown_options) protected
Minimization of scalar function of one or more variables using the
conjugate gradient algorithm.
Options
-------
disp : bool
    Set to True to print convergence messages.
maxiter : int
    Maximum number of iterations to perform.
gtol : float
    Gradient norm must be less than `gtol` before successful
    termination.
norm : float
    Order of norm (Inf is max, -Inf is min).
eps : float or ndarray
    If `jac is None` the absolute step size used for numerical
    approximation of the jacobian via forward differences.
return_all : bool, optional
    Set to True to return a list of the best solution at each of the
    iterations.
finite_diff_rel_step : None or array_like, optional
    If `jac in ['2-point', '3-point', 'cs']` the relative step size to
    use for numerical approximation of the jacobian. The absolute step
    size is computed as ``h = rel_step * sign(x) * max(1, abs(x))``,
    possibly adjusted to fit into the bounds. For ``method='3-point'``
    the sign of `h` is ignored. If None (default) then step is selected
    automatically.
Definition at line 1712 of file _optimize.py.
References _call_callback_maybe_halt(), _line_search_wolfe12(), and _prepare_scalar_function().
Referenced by fmin_cg(), and scipy.optimize._minimize.minimize().
_minimize_neldermead()
scipy.optimize._optimize._minimize_neldermead (func, x0, args = (), callback = None, maxiter = None, maxfev = None, disp = False, return_all = False, initial_simplex = None, xatol = 1e-4, fatol = 1e-4, adaptive = False, bounds = None, ** unknown_options) protected
Minimization of scalar function of one or more variables using the
Nelder-Mead algorithm.
Options
-------
disp : bool
    Set to True to print convergence messages.
maxiter, maxfev : int
    Maximum allowed number of iterations and function evaluations.
    Will default to ``N*200``, where ``N`` is the number of
    variables, if neither `maxiter` or `maxfev` is set. If both
    `maxiter` and `maxfev` are set, minimization will stop at the
    first reached.
return_all : bool, optional
    Set to True to return a list of the best solution at each of the
    iterations.
initial_simplex : array_like of shape (N + 1, N)
    Initial simplex. If given, overrides `x0`.
    ``initial_simplex[j,:]`` should contain the coordinates of
    the jth vertex of the ``N+1`` vertices in the simplex, where
    ``N`` is the dimension.
xatol : float, optional
    Absolute error in xopt between iterations that is acceptable for
    convergence.
fatol : number, optional
    Absolute error in func(xopt) between iterations that is acceptable for
    convergence.
adaptive : bool, optional
    Adapt algorithm parameters to dimensionality of problem. Useful for
    high-dimensional minimization [1]_.
bounds : sequence or `Bounds`, optional
    Bounds on variables. There are two ways to specify the bounds:
        1. Instance of `Bounds` class.
        2. Sequence of ``(min, max)`` pairs for each element in `x`. None
           is used to specify no bound.
    Note that this just clips all vertices in simplex based on
    the bounds.
References
----------
.. [1] Gao, F. and Han, L.
   Implementing the Nelder-Mead simplex algorithm with adaptive
   parameters. 2012. Computational Optimization and Applications.
   51:1, pp. 259-277
Definition at line 760 of file _optimize.py.
References _call_callback_maybe_halt().
Referenced by fmin(), and scipy.optimize._minimize.minimize().
_minimize_newtoncg()
scipy.optimize._optimize._minimize_newtoncg (fun, x0, args = (), jac = None, hess = None, hessp = None, callback = None, xtol = 1e-5, eps = _epsilon, maxiter = None, disp = False, return_all = False, ** unknown_options) protected
Minimization of scalar function of one or more variables using the
Newton-CG algorithm.
Note that the `jac` parameter (Jacobian) is required.
Options
-------
disp : bool
    Set to True to print convergence messages.
xtol : float
    Average relative error in solution `xopt` acceptable for
    convergence.
maxiter : int
    Maximum number of iterations to perform.
eps : float or ndarray
    If `hessp` is approximated, use this value for the step size.
return_all : bool, optional
    Set to True to return a list of the best solution at each of the
    iterations.
Definition at line 1972 of file _optimize.py.
References _call_callback_maybe_halt(), _line_search_wolfe12(), and _prepare_scalar_function().
Referenced by fmin_ncg(), and scipy.optimize._minimize.minimize().
_minimize_powell()
scipy.optimize._optimize._minimize_powell (func, x0, args = (), callback = None, bounds = None, xtol = 1e-4, ftol = 1e-4, maxiter = None, maxfev = None, disp = False, direc = None, return_all = False, ** unknown_options) protected
Minimization of scalar function of one or more variables using the
modified Powell algorithm.
Parameters
----------
fun : callable
    The objective function to be minimized.
        ``fun(x, *args) -> float``
    where ``x`` is a 1-D array with shape (n,) and ``args``
    is a tuple of the fixed parameters needed to completely
    specify the function.
x0 : ndarray, shape (n,)
    Initial guess. Array of real elements of size (n,),
    where ``n`` is the number of independent variables.
args : tuple, optional
    Extra arguments passed to the objective function and its
    derivatives (`fun`, `jac` and `hess` functions).
method : str or callable, optional
    The present documentation is specific to ``method='powell'``, but other
    options are available. See documentation for `scipy.optimize.minimize`.
bounds : sequence or `Bounds`, optional
    Bounds on decision variables. There are two ways to specify the bounds:
        1. Instance of `Bounds` class.
        2. Sequence of ``(min, max)`` pairs for each element in `x`. None
           is used to specify no bound.
    If bounds are not provided, then an unbounded line search will be used.
    If bounds are provided and the initial guess is within the bounds, then
    every function evaluation throughout the minimization procedure will be
    within the bounds. If bounds are provided, the initial guess is outside
    the bounds, and `direc` is full rank (or left to default), then some
    function evaluations during the first iteration may be outside the
    bounds, but every function evaluation after the first iteration will be
    within the bounds. If `direc` is not full rank, then some parameters
    may not be optimized and the solution is not guaranteed to be within
    the bounds.
options : dict, optional
    A dictionary of solver options. All methods accept the following
    generic options:
        maxiter : int
            Maximum number of iterations to perform. Depending on the
            method each iteration may use several function evaluations.
        disp : bool
            Set to True to print convergence messages.
    See method-specific options for ``method='powell'`` below.
callback : callable, optional
    Called after each iteration. The signature is:
        ``callback(xk)``
    where ``xk`` is the current parameter vector.
Returns
-------
res : OptimizeResult
    The optimization result represented as a ``OptimizeResult`` object.
    Important attributes are: ``x`` the solution array, ``success`` a
    Boolean flag indicating if the optimizer exited successfully and
    ``message`` which describes the cause of the termination. See
    `OptimizeResult` for a description of other attributes.
Options
-------
disp : bool
    Set to True to print convergence messages.
xtol : float
    Relative error in solution `xopt` acceptable for convergence.
ftol : float
    Relative error in ``fun(xopt)`` acceptable for convergence.
maxiter, maxfev : int
    Maximum allowed number of iterations and function evaluations.
    Will default to ``N*1000``, where ``N`` is the number of
    variables, if neither `maxiter` or `maxfev` is set. If both
    `maxiter` and `maxfev` are set, minimization will stop at the
    first reached.
direc : ndarray
    Initial set of direction vectors for the Powell method.
return_all : bool, optional
    Set to True to return a list of the best solution at each of the
    iterations.
Definition at line 3353 of file _optimize.py.
References _call_callback_maybe_halt(), _line_for_search(), and _linesearch_powell().
Referenced by fmin_powell(), and scipy.optimize._minimize.minimize().
_minimize_scalar_bounded()
scipy.optimize._optimize._minimize_scalar_bounded (func, bounds, args = (), xatol = 1e-5, maxiter = 500, disp = 0, ** unknown_options) protected
Options
-------
maxiter : int
    Maximum number of iterations to perform.
disp: int, optional
    If non-zero, print messages.
        0 : no message printing.
        1 : non-convergence notification messages only.
        2 : print a message on convergence too.
        3 : print iteration results.
xatol : float
    Absolute error in solution `xopt` acceptable for convergence.
Definition at line 2243 of file _optimize.py.
References is_finite_scalar().
Referenced by _linesearch_powell(), fminbound(), and scipy.optimize._minimize.minimize_scalar().
_minimize_scalar_brent()
scipy.optimize._optimize._minimize_scalar_brent (func, brack = None, args = (), xtol = 1.48e-8, maxiter = 500, disp = 0, ** unknown_options) protected
Options
-------
maxiter : int
    Maximum number of iterations to perform.
xtol : float
    Relative error in solution `xopt` acceptable for convergence.
disp: int, optional
    If non-zero, print messages.
        0 : no message printing.
        1 : non-convergence notification messages only.
        2 : print a message on convergence too.
        3 : print iteration results.
Notes
-----
Uses inverse parabolic interpolation when possible to speed up
convergence of golden section method.
Definition at line 2649 of file _optimize.py.
Referenced by brent().
_minimize_scalar_golden()
scipy.optimize._optimize._minimize_scalar_golden (func, brack = None, args = (), xtol = _epsilon, maxiter = 5000, disp = 0, ** unknown_options) protected
Options
-------
xtol : float
    Relative error in solution `xopt` acceptable for convergence.
maxiter : int
    Maximum number of iterations to perform.
disp: int, optional
    If non-zero, print messages.
        0 : no message printing.
        1 : non-convergence notification messages only.
        2 : print a message on convergence too.
        3 : print iteration results.
Definition at line 2778 of file _optimize.py.
References bracket().
Referenced by golden().
_prepare_scalar_function()
scipy.optimize._optimize._prepare_scalar_function (fun, x0, jac = None, args = (), bounds = None, epsilon = None, finite_diff_rel_step = None, hess = None) protected
Creates a ScalarFunction object for use with scalar minimizers
(BFGS/LBFGSB/SLSQP/TNC/CG/etc).
Parameters
----------
fun : callable
    The objective function to be minimized.
        ``fun(x, *args) -> float``
    where ``x`` is an 1-D array with shape (n,) and ``args``
    is a tuple of the fixed parameters needed to completely
    specify the function.
x0 : ndarray, shape (n,)
    Initial guess. Array of real elements of size (n,),
    where 'n' is the number of independent variables.
jac : {callable,  '2-point', '3-point', 'cs', None}, optional
    Method for computing the gradient vector. If it is a callable, it
    should be a function that returns the gradient vector:
        ``jac(x, *args) -> array_like, shape (n,)``
    If one of `{'2-point', '3-point', 'cs'}` is selected then the gradient
    is calculated with a relative step for finite differences. If `None`,
    then two-point finite differences with an absolute step is used.
args : tuple, optional
    Extra arguments passed to the objective function and its
    derivatives (`fun`, `jac` functions).
bounds : sequence, optional
    Bounds on variables. 'new-style' bounds are required.
eps : float or ndarray
    If `jac is None` the absolute step size used for numerical
    approximation of the jacobian via forward differences.
finite_diff_rel_step : None or array_like, optional
    If `jac in ['2-point', '3-point', 'cs']` the relative step size to
    use for numerical approximation of the jacobian. The absolute step
    size is computed as ``h = rel_step * sign(x0) * max(1, abs(x0))``,
    possibly adjusted to fit into the bounds. For ``method='3-point'``
    the sign of `h` is ignored. If None (default) then step is selected
    automatically.
hess : {callable,  '2-point', '3-point', 'cs', None}
    Computes the Hessian matrix. If it is callable, it should return the
    Hessian matrix:
        ``hess(x, *args) -> {LinearOperator, spmatrix, array}, (n, n)``
    Alternatively, the keywords {'2-point', '3-point', 'cs'} select a
    finite difference scheme for numerical estimation.
    Whenever the gradient is estimated via finite-differences, the Hessian
    cannot be estimated with options {'2-point', '3-point', 'cs'} and needs
    to be estimated using one of the quasi-Newton strategies.
Returns
-------
sf : ScalarFunction
Definition at line 295 of file _optimize.py.
Referenced by _minimize_bfgs(), _minimize_cg(), scipy.optimize._cobyla_py._minimize_cobyla(), scipy.optimize._lbfgsb_py._minimize_lbfgsb(), _minimize_newtoncg(), scipy.optimize._slsqp_py._minimize_slsqp(), scipy.optimize._tnc._minimize_tnc(), and scipy.optimize._trustregion._minimize_trust_region().
_print_success_message_or_warn()
scipy.optimize._optimize._print_success_message_or_warn (warnflag, message, warntype = None) protected
Definition at line 1530 of file _optimize.py.
_recover_from_bracket_error()
scipy.optimize._optimize._recover_from_bracket_error (solver, fun, bracket, args, ** options) protected
Definition at line 3057 of file _optimize.py.
_wrap_callback()
scipy.optimize._optimize._wrap_callback (callback, method = None) protected
Wrap a user-provided callback so that attributes can be attached.
Definition at line 135 of file _optimize.py.
Referenced by fmin(), fmin_bfgs(), fmin_cg(), scipy.optimize._lbfgsb_py.fmin_l_bfgs_b(), fmin_ncg(), fmin_powell(), and scipy.optimize._minimize.minimize().
_wrap_scalar_function()
scipy.optimize._optimize._wrap_scalar_function (function, args) protected
Definition at line 580 of file _optimize.py.
_wrap_scalar_function_maxfun_validation()
scipy.optimize._optimize._wrap_scalar_function_maxfun_validation (function, args, maxfun) protected
Definition at line 608 of file _optimize.py.
approx_fhess_p()
scipy.optimize._optimize.approx_fhess_p (x0, p, fprime, epsilon, * args)
Definition at line 1188 of file _optimize.py.
approx_fprime()
scipy.optimize._optimize.approx_fprime (xk, f, epsilon = _epsilon, * args)
Finite difference approximation of the derivatives of a
scalar or vector-valued function.
If a function maps from :math:`R^n` to :math:`R^m`, its derivatives form
an m-by-n matrix
called the Jacobian, where an element :math:`(i, j)` is a partial
derivative of f[i] with respect to ``xk[j]``.
Parameters
----------
xk : array_like
    The coordinate vector at which to determine the gradient of `f`.
f : callable
    Function of which to estimate the derivatives of. Has the signature
    ``f(xk, *args)`` where `xk` is the argument in the form of a 1-D array
    and `args` is a tuple of any additional fixed parameters needed to
    completely specify the function. The argument `xk` passed to this
    function is an ndarray of shape (n,) (never a scalar even if n=1).
    It must return a 1-D array_like of shape (m,) or a scalar.
    .. versionchanged:: 1.9.0
        `f` is now able to return a 1-D array-like, with the :math:`(m, n)`
        Jacobian being estimated.
epsilon : {float, array_like}, optional
    Increment to `xk` to use for determining the function gradient.
    If a scalar, uses the same finite difference delta for all partial
    derivatives. If an array, should contain one value per element of
    `xk`. Defaults to ``sqrt(np.finfo(float).eps)``, which is approximately
    1.49e-08.
\\*args : args, optional
    Any other arguments that are to be passed to `f`.
Returns
-------
jac : ndarray
    The partial derivatives of `f` to `xk`.
See Also
--------
check_grad : Check correctness of gradient function against approx_fprime.
Notes
-----
The function gradient is determined by the forward finite difference
formula::
             f(xk[i] + epsilon[i]) - f(xk[i])
    f'[i] = ---------------------------------
                        epsilon[i]
Examples
--------
>>> import numpy as np
>>> from scipy import optimize
>>> def func(x, c0, c1):
...     "Coordinate vector `x` should be an array of size two."
...     return c0 * x[0]**2 + c1*x[1]**2
>>> x = np.ones(2)
>>> c0, c1 = (1, 200)
>>> eps = np.sqrt(np.finfo(float).eps)
>>> optimize.approx_fprime(x, func, [eps, np.sqrt(200) * eps], c0, c1)
array([   2.        ,  400.00004198])
Definition at line 1019 of file _optimize.py.
Referenced by check_grad().
bracket()
scipy.optimize._optimize.bracket (func, xa = 0.0, xb = 1.0, args = (), grow_limit = 110.0, maxiter = 1000)
Bracket the minimum of a function.
Given a function and distinct initial points, search in the
downhill direction (as defined by the initial points) and return
three points that bracket the minimum of the function.
Parameters
----------
func : callable f(x,*args)
    Objective function to minimize.
xa, xb : float, optional
    Initial points. Defaults `xa` to 0.0, and `xb` to 1.0.
    A local minimum need not be contained within this interval.
args : tuple, optional
    Additional arguments (if present), passed to `func`.
grow_limit : float, optional
    Maximum grow limit.  Defaults to 110.0
maxiter : int, optional
    Maximum number of iterations to perform. Defaults to 1000.
Returns
-------
xa, xb, xc : float
    Final points of the bracket.
fa, fb, fc : float
    Objective function values at the bracket points.
funcalls : int
    Number of function evaluations made.
Raises
------
BracketError
    If no valid bracket is found before the algorithm terminates.
    See notes for conditions of a valid bracket.
Notes
-----
The algorithm attempts to find three strictly ordered points (i.e.
:math:`x_a < x_b < x_c` or :math:`x_c < x_b < x_a`) satisfying
:math:`f(x_b)  f(x_a)` and :math:`f(x_b)  f(x_c)`, where one of the
inequalities must be satistfied strictly and all :math:`x_i` must be
finite.
Examples
--------
This function can find a downward convex region of a function:
>>> import numpy as np
>>> import matplotlib.pyplot as plt
>>> from scipy.optimize import bracket
>>> def f(x):
...     return 10*x**2 + 3*x + 5
>>> x = np.linspace(-2, 2)
>>> y = f(x)
>>> init_xa, init_xb = 0.1, 1
>>> xa, xb, xc, fa, fb, fc, funcalls = bracket(f, xa=init_xa, xb=init_xb)
>>> plt.axvline(x=init_xa, color="k", linestyle="--")
>>> plt.axvline(x=init_xb, color="k", linestyle="--")
>>> plt.plot(x, y, "-k")
>>> plt.plot(xa, fa, "bx")
>>> plt.plot(xb, fb, "rx")
>>> plt.plot(xc, fc, "bx")
>>> plt.show()
Note that both initial points were to the right of the minimum, and the
third point was found in the "downhill" direction: the direction
in which the function appeared to be decreasing (to the left).
The final points are strictly ordered, and the function value
at the middle point is less than the function values at the endpoints;
it follows that a minimum must lie within the bracket.
Definition at line 2894 of file _optimize.py.
Referenced by _minimize_scalar_golden().
brent()
scipy.optimize._optimize.brent (func, args = (), brack = None, tol = 1.48e-8, full_output = 0, maxiter = 500)
Given a function of one variable and a possible bracket, return
a local minimizer of the function isolated to a fractional precision
of tol.
Parameters
----------
func : callable f(x,*args)
    Objective function.
args : tuple, optional
    Additional arguments (if present).
brack : tuple, optional
    Either a triple ``(xa, xb, xc)`` satisfying ``xa < xb < xc`` and
    ``func(xb) < func(xa) and  func(xb) < func(xc)``, or a pair
    ``(xa, xb)`` to be used as initial points for a downhill bracket search
    (see `scipy.optimize.bracket`).
    The minimizer ``x`` will not necessarily satisfy ``xa <= x <= xb``.
tol : float, optional
    Relative error in solution `xopt` acceptable for convergence.
full_output : bool, optional
    If True, return all output args (xmin, fval, iter,
    funcalls).
maxiter : int, optional
    Maximum number of iterations in solution.
Returns
-------
xmin : ndarray
    Optimum point.
fval : float
    (Optional output) Optimum function value.
iter : int
    (Optional output) Number of iterations.
funcalls : int
    (Optional output) Number of objective function evaluations made.
See also
--------
minimize_scalar: Interface to minimization algorithms for scalar
    univariate functions. See the 'Brent' `method` in particular.
Notes
-----
Uses inverse parabolic interpolation when possible to speed up
convergence of golden section method.
Does not ensure that the minimum lies in the range specified by
`brack`. See `scipy.optimize.fminbound`.
Examples
--------
We illustrate the behaviour of the function when `brack` is of
size 2 and 3 respectively. In the case where `brack` is of the
form ``(xa, xb)``, we can see for the given values, the output does
not necessarily lie in the range ``(xa, xb)``.
>>> def f(x):
...     return (x-1)**2
>>> from scipy import optimize
>>> minimizer = optimize.brent(f, brack=(1, 2))
>>> minimizer
1
>>> res = optimize.brent(f, brack=(-1, 0.5, 2), full_output=True)
>>> xmin, fval, iter, funcalls = res
>>> f(xmin), fval
(0.0, 0.0)
Definition at line 2569 of file _optimize.py.
References _minimize_scalar_brent().
brute()
scipy.optimize._optimize.brute (func, ranges, args = (), Ns = 20, full_output = 0, finish = fmin, disp = False, workers = 1)
Minimize a function over a given range by brute force.
Uses the "brute force" method, i.e., computes the function's value
at each point of a multidimensional grid of points, to find the global
minimum of the function.
The function is evaluated everywhere in the range with the datatype of the
first call to the function, as enforced by the ``vectorize`` NumPy
function. The value and type of the function evaluation returned when
``full_output=True`` are affected in addition by the ``finish`` argument
(see Notes).
The brute force approach is inefficient because the number of grid points
increases exponentially - the number of grid points to evaluate is
``Ns ** len(x)``. Consequently, even with coarse grid spacing, even
moderately sized problems can take a long time to run, and/or run into
memory limitations.
Parameters
----------
func : callable
    The objective function to be minimized. Must be in the
    form ``f(x, *args)``, where ``x`` is the argument in
    the form of a 1-D array and ``args`` is a tuple of any
    additional fixed parameters needed to completely specify
    the function.
ranges : tuple
    Each component of the `ranges` tuple must be either a
    "slice object" or a range tuple of the form ``(low, high)``.
    The program uses these to create the grid of points on which
    the objective function will be computed. See `Note 2` for
    more detail.
args : tuple, optional
    Any additional fixed parameters needed to completely specify
    the function.
Ns : int, optional
    Number of grid points along the axes, if not otherwise
    specified. See `Note2`.
full_output : bool, optional
    If True, return the evaluation grid and the objective function's
    values on it.
finish : callable, optional
    An optimization function that is called with the result of brute force
    minimization as initial guess. `finish` should take `func` and
    the initial guess as positional arguments, and take `args` as
    keyword arguments. It may additionally take `full_output`
    and/or `disp` as keyword arguments. Use None if no "polishing"
    function is to be used. See Notes for more details.
disp : bool, optional
    Set to True to print convergence messages from the `finish` callable.
workers : int or map-like callable, optional
    If `workers` is an int the grid is subdivided into `workers`
    sections and evaluated in parallel (uses
    `multiprocessing.Pool <multiprocessing>`).
    Supply `-1` to use all cores available to the Process.
    Alternatively supply a map-like callable, such as
    `multiprocessing.Pool.map` for evaluating the grid in parallel.
    This evaluation is carried out as ``workers(func, iterable)``.
    Requires that `func` be pickleable.
    .. versionadded:: 1.3.0
Returns
-------
x0 : ndarray
    A 1-D array containing the coordinates of a point at which the
    objective function had its minimum value. (See `Note 1` for
    which point is returned.)
fval : float
    Function value at the point `x0`. (Returned when `full_output` is
    True.)
grid : tuple
    Representation of the evaluation grid. It has the same
    length as `x0`. (Returned when `full_output` is True.)
Jout : ndarray
    Function values at each point of the evaluation
    grid, i.e., ``Jout = func(*grid)``. (Returned
    when `full_output` is True.)
See Also
--------
basinhopping, differential_evolution
Notes
-----
*Note 1*: The program finds the gridpoint at which the lowest value
of the objective function occurs. If `finish` is None, that is the
point returned. When the global minimum occurs within (or not very far
outside) the grid's boundaries, and the grid is fine enough, that
point will be in the neighborhood of the global minimum.
However, users often employ some other optimization program to
"polish" the gridpoint values, i.e., to seek a more precise
(local) minimum near `brute's` best gridpoint.
The `brute` function's `finish` option provides a convenient way to do
that. Any polishing program used must take `brute's` output as its
initial guess as a positional argument, and take `brute's` input values
for `args` as keyword arguments, otherwise an error will be raised.
It may additionally take `full_output` and/or `disp` as keyword arguments.
`brute` assumes that the `finish` function returns either an
`OptimizeResult` object or a tuple in the form:
``(xmin, Jmin, ... , statuscode)``, where ``xmin`` is the minimizing
value of the argument, ``Jmin`` is the minimum value of the objective
function, "..." may be some other returned values (which are not used
by `brute`), and ``statuscode`` is the status code of the `finish` program.
Note that when `finish` is not None, the values returned are those
of the `finish` program, *not* the gridpoint ones. Consequently,
while `brute` confines its search to the input grid points,
the `finish` program's results usually will not coincide with any
gridpoint, and may fall outside the grid's boundary. Thus, if a
minimum only needs to be found over the provided grid points, make
sure to pass in `finish=None`.
*Note 2*: The grid of points is a `numpy.mgrid` object.
For `brute` the `ranges` and `Ns` inputs have the following effect.
Each component of the `ranges` tuple can be either a slice object or a
two-tuple giving a range of values, such as (0, 5). If the component is a
slice object, `brute` uses it directly. If the component is a two-tuple
range, `brute` internally converts it to a slice object that interpolates
`Ns` points from its low-value to its high-value, inclusive.
Examples
--------
We illustrate the use of `brute` to seek the global minimum of a function
of two variables that is given as the sum of a positive-definite
quadratic and two deep "Gaussian-shaped" craters. Specifically, define
the objective function `f` as the sum of three other functions,
``f = f1 + f2 + f3``. We suppose each of these has a signature
``(z, *params)``, where ``z = (x, y)``,  and ``params`` and the functions
are as defined below.
>>> import numpy as np
>>> params = (2, 3, 7, 8, 9, 10, 44, -1, 2, 26, 1, -2, 0.5)
>>> def f1(z, *params):
...     x, y = z
...     a, b, c, d, e, f, g, h, i, j, k, l, scale = params
...     return (a * x**2 + b * x * y + c * y**2 + d*x + e*y + f)
>>> def f2(z, *params):
...     x, y = z
...     a, b, c, d, e, f, g, h, i, j, k, l, scale = params
...     return (-g*np.exp(-((x-h)**2 + (y-i)**2) / scale))
>>> def f3(z, *params):
...     x, y = z
...     a, b, c, d, e, f, g, h, i, j, k, l, scale = params
...     return (-j*np.exp(-((x-k)**2 + (y-l)**2) / scale))
>>> def f(z, *params):
...     return f1(z, *params) + f2(z, *params) + f3(z, *params)
Thus, the objective function may have local minima near the minimum
of each of the three functions of which it is composed. To
use `fmin` to polish its gridpoint result, we may then continue as
follows:
>>> rranges = (slice(-4, 4, 0.25), slice(-4, 4, 0.25))
>>> from scipy import optimize
>>> resbrute = optimize.brute(f, rranges, args=params, full_output=True,
...                           finish=optimize.fmin)
>>> resbrute[0]  # global minimum
array([-1.05665192,  1.80834843])
>>> resbrute[1]  # function value at global minimum
-3.4085818767
Note that if `finish` had been set to None, we would have gotten the
gridpoint [-1.0 1.75] where the rounded function value is -2.892.
Definition at line 3614 of file _optimize.py.
check_grad()
scipy.optimize._optimize.check_grad (func, grad, x0, * args, epsilon = _epsilon, direction = 'all', seed = None)
Check the correctness of a gradient function by comparing it against a
(forward) finite-difference approximation of the gradient.
Parameters
----------
func : callable ``func(x0, *args)``
    Function whose derivative is to be checked.
grad : callable ``grad(x0, *args)``
    Jacobian of `func`.
x0 : ndarray
    Points to check `grad` against forward difference approximation of grad
    using `func`.
args : \\*args, optional
    Extra arguments passed to `func` and `grad`.
epsilon : float, optional
    Step size used for the finite difference approximation. It defaults to
    ``sqrt(np.finfo(float).eps)``, which is approximately 1.49e-08.
direction : str, optional
    If set to ``'random'``, then gradients along a random vector
    are used to check `grad` against forward difference approximation
    using `func`. By default it is ``'all'``, in which case, all
    the one hot direction vectors are considered to check `grad`.
    If `func` is a vector valued function then only ``'all'`` can be used.
seed : {None, int, `numpy.random.Generator`, `numpy.random.RandomState`}, optional
    If `seed` is None (or `np.random`), the `numpy.random.RandomState`
    singleton is used.
    If `seed` is an int, a new ``RandomState`` instance is used,
    seeded with `seed`.
    If `seed` is already a ``Generator`` or ``RandomState`` instance then
    that instance is used.
    Specify `seed` for reproducing the return value from this function.
    The random numbers generated with this seed affect the random vector
    along which gradients are computed to check ``grad``. Note that `seed`
    is only used when `direction` argument is set to `'random'`.
Returns
-------
err : float
    The square root of the sum of squares (i.e., the 2-norm) of the
    difference between ``grad(x0, *args)`` and the finite difference
    approximation of `grad` using func at the points `x0`.
See Also
--------
approx_fprime
Examples
--------
>>> import numpy as np
>>> def func(x):
...     return x[0]**2 - 0.5 * x[1]**3
>>> def grad(x):
...     return [2 * x[0], -1.5 * x[1]**2]
>>> from scipy.optimize import check_grad
>>> check_grad(func, grad, [1.5, -1.5])
2.9802322387695312e-08  # may vary
>>> rng = np.random.default_rng()
>>> check_grad(func, grad, [1.5, -1.5],
...             direction='random', seed=rng)
2.9802322387695312e-08
Definition at line 1093 of file _optimize.py.
References approx_fprime().
fmin()
scipy.optimize._optimize.fmin (func, x0, args = (), xtol = 1e-4, ftol = 1e-4, maxiter = None, maxfun = None, full_output = 0, disp = 1, retall = 0, callback = None, initial_simplex = None)
Minimize a function using the downhill simplex algorithm.
This algorithm only uses function values, not derivatives or second
derivatives.
Parameters
----------
func : callable func(x,*args)
    The objective function to be minimized.
x0 : ndarray
    Initial guess.
args : tuple, optional
    Extra arguments passed to func, i.e., ``f(x,*args)``.
xtol : float, optional
    Absolute error in xopt between iterations that is acceptable for
    convergence.
ftol : number, optional
    Absolute error in func(xopt) between iterations that is acceptable for
    convergence.
maxiter : int, optional
    Maximum number of iterations to perform.
maxfun : number, optional
    Maximum number of function evaluations to make.
full_output : bool, optional
    Set to True if fopt and warnflag outputs are desired.
disp : bool, optional
    Set to True to print convergence messages.
retall : bool, optional
    Set to True to return list of solutions at each iteration.
callback : callable, optional
    Called after each iteration, as callback(xk), where xk is the
    current parameter vector.
initial_simplex : array_like of shape (N + 1, N), optional
    Initial simplex. If given, overrides `x0`.
    ``initial_simplex[j,:]`` should contain the coordinates of
    the jth vertex of the ``N+1`` vertices in the simplex, where
    ``N`` is the dimension.
Returns
-------
xopt : ndarray
    Parameter that minimizes function.
fopt : float
    Value of function at minimum: ``fopt = func(xopt)``.
iter : int
    Number of iterations performed.
funcalls : int
    Number of function calls made.
warnflag : int
    1 : Maximum number of function evaluations made.
    2 : Maximum number of iterations reached.
allvecs : list
    Solution at each iteration.
See also
--------
minimize: Interface to minimization algorithms for multivariate
    functions. See the 'Nelder-Mead' `method` in particular.
Notes
-----
Uses a Nelder-Mead simplex algorithm to find the minimum of function of
one or more variables.
This algorithm has a long history of successful use in applications.
But it will usually be slower than an algorithm that uses first or
second derivative information. In practice, it can have poor
performance in high-dimensional problems and is not robust to
minimizing complicated functions. Additionally, there currently is no
complete theory describing when the algorithm will successfully
converge to the minimum, or how fast it will if it does. Both the ftol and
xtol criteria must be met for convergence.
Examples
--------
>>> def f(x):
...     return x**2
>>> from scipy import optimize
>>> minimum = optimize.fmin(f, 1)
Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 17
         Function evaluations: 34
>>> minimum[0]
-8.8817841970012523e-16
References
----------
.. [1] Nelder, J.A. and Mead, R. (1965), "A simplex method for function
       minimization", The Computer Journal, 7, pp. 308-313
.. [2] Wright, M.H. (1996), "Direct Search Methods: Once Scorned, Now
       Respectable", in Numerical Analysis 1995, Proceedings of the
       1995 Dundee Biennial Conference in Numerical Analysis, D.F.
       Griffiths and G.A. Watson (Eds.), Addison Wesley Longman,
       Harlow, UK, pp. 191-208.
Definition at line 635 of file _optimize.py.
References _minimize_neldermead(), and _wrap_callback().
fmin_bfgs()
scipy.optimize._optimize.fmin_bfgs (f, x0, fprime = None, args = (), gtol = 1e-5, norm = Inf, epsilon = _epsilon, maxiter = None, full_output = 0, disp = 1, retall = 0, callback = None, xrtol = 0)
Minimize a function using the BFGS algorithm.
Parameters
----------
f : callable ``f(x,*args)``
    Objective function to be minimized.
x0 : ndarray
    Initial guess.
fprime : callable ``f'(x,*args)``, optional
    Gradient of f.
args : tuple, optional
    Extra arguments passed to f and fprime.
gtol : float, optional
    Terminate successfully if gradient norm is less than `gtol`
norm : float, optional
    Order of norm (Inf is max, -Inf is min)
epsilon : int or ndarray, optional
    If `fprime` is approximated, use this value for the step size.
callback : callable, optional
    An optional user-supplied function to call after each
    iteration. Called as ``callback(xk)``, where ``xk`` is the
    current parameter vector.
maxiter : int, optional
    Maximum number of iterations to perform.
full_output : bool, optional
    If True, return ``fopt``, ``func_calls``, ``grad_calls``, and
    ``warnflag`` in addition to ``xopt``.
disp : bool, optional
    Print convergence message if True.
retall : bool, optional
    Return a list of results at each iteration if True.
xrtol : float, default: 0
    Relative tolerance for `x`. Terminate successfully if step
    size is less than ``xk * xrtol`` where ``xk`` is the current
    parameter vector.
Returns
-------
xopt : ndarray
    Parameters which minimize f, i.e., ``f(xopt) == fopt``.
fopt : float
    Minimum value.
gopt : ndarray
    Value of gradient at minimum, f'(xopt), which should be near 0.
Bopt : ndarray
    Value of 1/f''(xopt), i.e., the inverse Hessian matrix.
func_calls : int
    Number of function_calls made.
grad_calls : int
    Number of gradient calls made.
warnflag : integer
    1 : Maximum number of iterations exceeded.
    2 : Gradient and/or function calls not changing.
    3 : NaN result encountered.
allvecs : list
    The value of `xopt` at each iteration. Only returned if `retall` is
    True.
Notes
-----
Optimize the function, `f`, whose gradient is given by `fprime`
using the quasi-Newton method of Broyden, Fletcher, Goldfarb,
and Shanno (BFGS).
See Also
--------
minimize: Interface to minimization algorithms for multivariate
    functions. See ``method='BFGS'`` in particular.
References
----------
Wright, and Nocedal 'Numerical Optimization', 1999, p. 198.
Examples
--------
>>> import numpy as np
>>> from scipy.optimize import fmin_bfgs
>>> def quadratic_cost(x, Q):
...     return x @ Q @ x
...
>>> x0 = np.array([-3, -4])
>>> cost_weight =  np.diag([1., 10.])
>>> # Note that a trailing comma is necessary for a tuple with single element
>>> fmin_bfgs(quadratic_cost, x0, args=(cost_weight,))
Optimization terminated successfully.
        Current function value: 0.000000
        Iterations: 7                   # may vary
        Function evaluations: 24        # may vary
        Gradient evaluations: 8         # may vary
array([ 2.85169950e-06, -4.61820139e-07])
>>> def quadratic_cost_grad(x, Q):
...     return 2 * Q @ x
...
>>> fmin_bfgs(quadratic_cost, x0, quadratic_cost_grad, args=(cost_weight,))
Optimization terminated successfully.
        Current function value: 0.000000
        Iterations: 7
        Function evaluations: 8
        Gradient evaluations: 8
array([ 2.85916637e-06, -4.54371951e-07])
Definition at line 1244 of file _optimize.py.
References _minimize_bfgs(), and _wrap_callback().
fmin_cg()
scipy.optimize._optimize.fmin_cg (f, x0, fprime = None, args = (), gtol = 1e-5, norm = Inf, epsilon = _epsilon, maxiter = None, full_output = 0, disp = 1, retall = 0, callback = None)
Minimize a function using a nonlinear conjugate gradient algorithm.
Parameters
----------
f : callable, ``f(x, *args)``
    Objective function to be minimized. Here `x` must be a 1-D array of
    the variables that are to be changed in the search for a minimum, and
    `args` are the other (fixed) parameters of `f`.
x0 : ndarray
    A user-supplied initial estimate of `xopt`, the optimal value of `x`.
    It must be a 1-D array of values.
fprime : callable, ``fprime(x, *args)``, optional
    A function that returns the gradient of `f` at `x`. Here `x` and `args`
    are as described above for `f`. The returned value must be a 1-D array.
    Defaults to None, in which case the gradient is approximated
    numerically (see `epsilon`, below).
args : tuple, optional
    Parameter values passed to `f` and `fprime`. Must be supplied whenever
    additional fixed parameters are needed to completely specify the
    functions `f` and `fprime`.
gtol : float, optional
    Stop when the norm of the gradient is less than `gtol`.
norm : float, optional
    Order to use for the norm of the gradient
    (``-np.inf`` is min, ``np.inf`` is max).
epsilon : float or ndarray, optional
    Step size(s) to use when `fprime` is approximated numerically. Can be a
    scalar or a 1-D array. Defaults to ``sqrt(eps)``, with eps the
    floating point machine precision.  Usually ``sqrt(eps)`` is about
    1.5e-8.
maxiter : int, optional
    Maximum number of iterations to perform. Default is ``200 * len(x0)``.
full_output : bool, optional
    If True, return `fopt`, `func_calls`, `grad_calls`, and `warnflag` in
    addition to `xopt`.  See the Returns section below for additional
    information on optional return values.
disp : bool, optional
    If True, return a convergence message, followed by `xopt`.
retall : bool, optional
    If True, add to the returned values the results of each iteration.
callback : callable, optional
    An optional user-supplied function, called after each iteration.
    Called as ``callback(xk)``, where ``xk`` is the current value of `x0`.
Returns
-------
xopt : ndarray
    Parameters which minimize f, i.e., ``f(xopt) == fopt``.
fopt : float, optional
    Minimum value found, f(xopt). Only returned if `full_output` is True.
func_calls : int, optional
    The number of function_calls made. Only returned if `full_output`
    is True.
grad_calls : int, optional
    The number of gradient calls made. Only returned if `full_output` is
    True.
warnflag : int, optional
    Integer value with warning status, only returned if `full_output` is
    True.
    0 : Success.
    1 : The maximum number of iterations was exceeded.
    2 : Gradient and/or function calls were not changing. May indicate
        that precision was lost, i.e., the routine did not converge.
    3 : NaN result encountered.
allvecs : list of ndarray, optional
    List of arrays, containing the results at each iteration.
    Only returned if `retall` is True.
See Also
--------
minimize : common interface to all `scipy.optimize` algorithms for
           unconstrained and constrained minimization of multivariate
           functions. It provides an alternative way to call
           ``fmin_cg``, by specifying ``method='CG'``.
Notes
-----
This conjugate gradient algorithm is based on that of Polak and Ribiere
[1]_.
Conjugate gradient methods tend to work better when:
1. `f` has a unique global minimizing point, and no local minima or
   other stationary points,
2. `f` is, at least locally, reasonably well approximated by a
   quadratic function of the variables,
3. `f` is continuous and has a continuous gradient,
4. `fprime` is not too large, e.g., has a norm less than 1000,
5. The initial guess, `x0`, is reasonably close to `f` 's global
   minimizing point, `xopt`.
References
----------
.. [1] Wright & Nocedal, "Numerical Optimization", 1999, pp. 120-122.
Examples
--------
Example 1: seek the minimum value of the expression
``a*u**2 + b*u*v + c*v**2 + d*u + e*v + f`` for given values
of the parameters and an initial guess ``(u, v) = (0, 0)``.
>>> import numpy as np
>>> args = (2, 3, 7, 8, 9, 10)  # parameter values
>>> def f(x, *args):
...     u, v = x
...     a, b, c, d, e, f = args
...     return a*u**2 + b*u*v + c*v**2 + d*u + e*v + f
>>> def gradf(x, *args):
...     u, v = x
...     a, b, c, d, e, f = args
...     gu = 2*a*u + b*v + d     # u-component of the gradient
...     gv = b*u + 2*c*v + e     # v-component of the gradient
...     return np.asarray((gu, gv))
>>> x0 = np.asarray((0, 0))  # Initial guess.
>>> from scipy import optimize
>>> res1 = optimize.fmin_cg(f, x0, fprime=gradf, args=args)
Optimization terminated successfully.
         Current function value: 1.617021
         Iterations: 4
         Function evaluations: 8
         Gradient evaluations: 8
>>> res1
array([-1.80851064, -0.25531915])
Example 2: solve the same problem using the `minimize` function.
(This `myopts` dictionary shows all of the available options,
although in practice only non-default values would be needed.
The returned value will be a dictionary.)
>>> opts = {'maxiter' : None,    # default value.
...         'disp' : True,    # non-default value.
...         'gtol' : 1e-5,    # default value.
...         'norm' : np.inf,  # default value.
...         'eps' : 1.4901161193847656e-08}  # default value.
>>> res2 = optimize.minimize(f, x0, jac=gradf, args=args,
...                          method='CG', options=opts)
Optimization terminated successfully.
        Current function value: 1.617021
        Iterations: 4
        Function evaluations: 8
        Gradient evaluations: 8
>>> res2.x  # minimum found
array([-1.80851064, -0.25531915])
Definition at line 1537 of file _optimize.py.
References _minimize_cg(), and _wrap_callback().
fmin_ncg()
scipy.optimize._optimize.fmin_ncg (f, x0, fprime, fhess_p = None, fhess = None, args = (), avextol = 1e-5, epsilon = _epsilon, maxiter = None, full_output = 0, disp = 1, retall = 0, callback = None)
Unconstrained minimization of a function using the Newton-CG method.
Parameters
----------
f : callable ``f(x, *args)``
    Objective function to be minimized.
x0 : ndarray
    Initial guess.
fprime : callable ``f'(x, *args)``
    Gradient of f.
fhess_p : callable ``fhess_p(x, p, *args)``, optional
    Function which computes the Hessian of f times an
    arbitrary vector, p.
fhess : callable ``fhess(x, *args)``, optional
    Function to compute the Hessian matrix of f.
args : tuple, optional
    Extra arguments passed to f, fprime, fhess_p, and fhess
    (the same set of extra arguments is supplied to all of
    these functions).
epsilon : float or ndarray, optional
    If fhess is approximated, use this value for the step size.
callback : callable, optional
    An optional user-supplied function which is called after
    each iteration. Called as callback(xk), where xk is the
    current parameter vector.
avextol : float, optional
    Convergence is assumed when the average relative error in
    the minimizer falls below this amount.
maxiter : int, optional
    Maximum number of iterations to perform.
full_output : bool, optional
    If True, return the optional outputs.
disp : bool, optional
    If True, print convergence message.
retall : bool, optional
    If True, return a list of results at each iteration.
Returns
-------
xopt : ndarray
    Parameters which minimize f, i.e., ``f(xopt) == fopt``.
fopt : float
    Value of the function at xopt, i.e., ``fopt = f(xopt)``.
fcalls : int
    Number of function calls made.
gcalls : int
    Number of gradient calls made.
hcalls : int
    Number of Hessian calls made.
warnflag : int
    Warnings generated by the algorithm.
    1 : Maximum number of iterations exceeded.
    2 : Line search failure (precision loss).
    3 : NaN result encountered.
allvecs : list
    The result at each iteration, if retall is True (see below).
See also
--------
minimize: Interface to minimization algorithms for multivariate
    functions. See the 'Newton-CG' `method` in particular.
Notes
-----
Only one of `fhess_p` or `fhess` need to be given.  If `fhess`
is provided, then `fhess_p` will be ignored. If neither `fhess`
nor `fhess_p` is provided, then the hessian product will be
approximated using finite differences on `fprime`. `fhess_p`
must compute the hessian times an arbitrary vector. If it is not
given, finite-differences on `fprime` are used to compute
it.
Newton-CG methods are also called truncated Newton methods. This
function differs from scipy.optimize.fmin_tnc because
1. scipy.optimize.fmin_ncg is written purely in Python using NumPy
    and scipy while scipy.optimize.fmin_tnc calls a C function.
2. scipy.optimize.fmin_ncg is only for unconstrained minimization
    while scipy.optimize.fmin_tnc is for unconstrained minimization
    or box constrained minimization. (Box constraints give
    lower and upper bounds for each variable separately.)
References
----------
Wright & Nocedal, 'Numerical Optimization', 1999, p. 140.
Definition at line 1858 of file _optimize.py.
References _minimize_newtoncg(), and _wrap_callback().
fmin_powell()
scipy.optimize._optimize.fmin_powell (func, x0, args = (), xtol = 1e-4, ftol = 1e-4, maxiter = None, maxfun = None, full_output = 0, disp = 1, retall = 0, callback = None, direc = None)
Minimize a function using modified Powell's method.
This method only uses function values, not derivatives.
Parameters
----------
func : callable f(x,*args)
    Objective function to be minimized.
x0 : ndarray
    Initial guess.
args : tuple, optional
    Extra arguments passed to func.
xtol : float, optional
    Line-search error tolerance.
ftol : float, optional
    Relative error in ``func(xopt)`` acceptable for convergence.
maxiter : int, optional
    Maximum number of iterations to perform.
maxfun : int, optional
    Maximum number of function evaluations to make.
full_output : bool, optional
    If True, ``fopt``, ``xi``, ``direc``, ``iter``, ``funcalls``, and
    ``warnflag`` are returned.
disp : bool, optional
    If True, print convergence messages.
retall : bool, optional
    If True, return a list of the solution at each iteration.
callback : callable, optional
    An optional user-supplied function, called after each
    iteration.  Called as ``callback(xk)``, where ``xk`` is the
    current parameter vector.
direc : ndarray, optional
    Initial fitting step and parameter order set as an (N, N) array, where N
    is the number of fitting parameters in `x0`. Defaults to step size 1.0
    fitting all parameters simultaneously (``np.eye((N, N))``). To
    prevent initial consideration of values in a step or to change initial
    step size, set to 0 or desired step size in the Jth position in the Mth
    block, where J is the position in `x0` and M is the desired evaluation
    step, with steps being evaluated in index order. Step size and ordering
    will change freely as minimization proceeds.
Returns
-------
xopt : ndarray
    Parameter which minimizes `func`.
fopt : number
    Value of function at minimum: ``fopt = func(xopt)``.
direc : ndarray
    Current direction set.
iter : int
    Number of iterations.
funcalls : int
    Number of function calls made.
warnflag : int
    Integer warning flag:
        1 : Maximum number of function evaluations.
        2 : Maximum number of iterations.
        3 : NaN result encountered.
        4 : The result is out of the provided bounds.
allvecs : list
    List of solutions at each iteration.
See also
--------
minimize: Interface to unconstrained minimization algorithms for
    multivariate functions. See the 'Powell' method in particular.
Notes
-----
Uses a modification of Powell's method to find the minimum of
a function of N variables. Powell's method is a conjugate
direction method.
The algorithm has two loops. The outer loop merely iterates over the inner
loop. The inner loop minimizes over each current direction in the direction
set. At the end of the inner loop, if certain conditions are met, the
direction that gave the largest decrease is dropped and replaced with the
difference between the current estimated x and the estimated x from the
beginning of the inner-loop.
The technical conditions for replacing the direction of greatest
increase amount to checking that
1. No further gain can be made along the direction of greatest increase
   from that iteration.
2. The direction of greatest increase accounted for a large sufficient
   fraction of the decrease in the function value from that iteration of
   the inner loop.
References
----------
Powell M.J.D. (1964) An efficient method for finding the minimum of a
function of several variables without calculating derivatives,
Computer Journal, 7 (2):155-162.
Press W., Teukolsky S.A., Vetterling W.T., and Flannery B.P.:
Numerical Recipes (any edition), Cambridge University Press
Examples
--------
>>> def f(x):
...     return x**2
>>> from scipy import optimize
>>> minimum = optimize.fmin_powell(f, -1)
Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 2
         Function evaluations: 16
>>> minimum
array(0.0)
Definition at line 3211 of file _optimize.py.
References _minimize_powell(), and _wrap_callback().
fminbound()
scipy.optimize._optimize.fminbound (func, x1, x2, args = (), xtol = 1e-5, maxfun = 500, full_output = 0, disp = 1)
Bounded minimization for scalar functions.
Parameters
----------
func : callable f(x,*args)
    Objective function to be minimized (must accept and return scalars).
x1, x2 : float or array scalar
    Finite optimization bounds.
args : tuple, optional
    Extra arguments passed to function.
xtol : float, optional
    The convergence tolerance.
maxfun : int, optional
    Maximum number of function evaluations allowed.
full_output : bool, optional
    If True, return optional outputs.
disp : int, optional
    If non-zero, print messages.
        0 : no message printing.
        1 : non-convergence notification messages only.
        2 : print a message on convergence too.
        3 : print iteration results.
Returns
-------
xopt : ndarray
    Parameters (over given interval) which minimize the
    objective function.
fval : number
    (Optional output) The function value evaluated at the minimizer.
ierr : int
    (Optional output) An error flag (0 if converged, 1 if maximum number of
    function calls reached).
numfunc : int
    (Optional output) The number of function calls made.
See also
--------
minimize_scalar: Interface to minimization algorithms for scalar
    univariate functions. See the 'Bounded' `method` in particular.
Notes
-----
Finds a local minimizer of the scalar function `func` in the
interval x1 < xopt < x2 using Brent's method. (See `brent`
for auto-bracketing.)
References
----------
.. [1] Forsythe, G.E., M. A. Malcolm, and C. B. Moler. "Computer Methods
       for Mathematical Computations." Prentice-Hall Series in Automatic
       Computation 259 (1977).
.. [2] Brent, Richard P. Algorithms for Minimization Without Derivatives.
       Courier Corporation, 2013.
Examples
--------
`fminbound` finds the minimizer of the function in the given range.
The following examples illustrate this.
>>> from scipy import optimize
>>> def f(x):
...     return (x-1)**2
>>> minimizer = optimize.fminbound(f, -4, 4)
>>> minimizer
1.0
>>> minimum = f(minimizer)
>>> minimum
0.0
>>> res = optimize.fminbound(f, 3, 4, full_output=True)
>>> minimizer, fval, ierr, numfunc = res
>>> minimizer
3.000005960860986
>>> minimum = f(minimizer)
>>> minimum, fval
(4.000023843479476, 4.000023843479476)
Definition at line 2152 of file _optimize.py.
References _minimize_scalar_bounded().
golden()
scipy.optimize._optimize.golden (func, args = (), brack = None, tol = _epsilon, full_output = 0, maxiter = 5000)
Return the minimizer of a function of one variable using the golden section
method.
Given a function of one variable and a possible bracketing interval,
return a minimizer of the function isolated to a fractional precision of
tol.
Parameters
----------
func : callable func(x,*args)
    Objective function to minimize.
args : tuple, optional
    Additional arguments (if present), passed to func.
brack : tuple, optional
    Either a triple ``(xa, xb, xc)`` where ``xa < xb < xc`` and
    ``func(xb) < func(xa) and  func(xb) < func(xc)``, or a pair (xa, xb)
    to be used as initial points for a downhill bracket search (see
    `scipy.optimize.bracket`).
    The minimizer ``x`` will not necessarily satisfy ``xa <= x <= xb``.
tol : float, optional
    x tolerance stop criterion
full_output : bool, optional
    If True, return optional outputs.
maxiter : int
    Maximum number of iterations to perform.
Returns
-------
xmin : ndarray
    Optimum point.
fval : float
    (Optional output) Optimum function value.
funcalls : int
    (Optional output) Number of objective function evaluations made.
See also
--------
minimize_scalar: Interface to minimization algorithms for scalar
    univariate functions. See the 'Golden' `method` in particular.
Notes
-----
Uses analog of bisection method to decrease the bracketed
interval.
Examples
--------
We illustrate the behaviour of the function when `brack` is of
size 2 and 3, respectively. In the case where `brack` is of the
form (xa,xb), we can see for the given values, the output need
not necessarily lie in the range ``(xa, xb)``.
>>> def f(x):
...     return (x-1)**2
>>> from scipy import optimize
>>> minimizer = optimize.golden(f, brack=(1, 2))
>>> minimizer
1
>>> res = optimize.golden(f, brack=(-1, 0.5, 2), full_output=True)
>>> xmin, fval, funcalls = res
>>> f(xmin), fval
(9.925165290385052e-18, 9.925165290385052e-18)
Definition at line 2701 of file _optimize.py.
References _minimize_scalar_golden().
is_finite_scalar()
scipy.optimize._optimize.is_finite_scalar (x)
Test whether `x` is either a finite scalar or a finite array scalar.
Definition at line 276 of file _optimize.py.
Referenced by _minimize_scalar_bounded().
rosen()
scipy.optimize._optimize.rosen (x)
The Rosenbrock function.
The function computed is::
    sum(100.0*(x[1:] - x[:-1]**2.0)**2.0 + (1 - x[:-1])**2.0)
Parameters
----------
x : array_like
    1-D array of points at which the Rosenbrock function is to be computed.
Returns
-------
f : float
    The value of the Rosenbrock function.
See Also
--------
rosen_der, rosen_hess, rosen_hess_prod
Examples
--------
>>> import numpy as np
>>> from scipy.optimize import rosen
>>> X = 0.1 * np.arange(10)
>>> rosen(X)
76.56
For higher-dimensional input ``rosen`` broadcasts.
In the following example, we use this to plot a 2D landscape.
Note that ``rosen_hess`` does not broadcast in this manner.
>>> import matplotlib.pyplot as plt
>>> from mpl_toolkits.mplot3d import Axes3D
>>> x = np.linspace(-1, 1, 50)
>>> X, Y = np.meshgrid(x, x)
>>> ax = plt.subplot(111, projection='3d')
>>> ax.plot_surface(X, Y, rosen([X, Y]))
>>> plt.show()
Definition at line 412 of file _optimize.py.
Referenced by scipy.optimize.tests.test__shgo.TestShgoFailures.test_6_1_lower_known_f_min().
rosen_der()
scipy.optimize._optimize.rosen_der (x)
The derivative (i.e. gradient) of the Rosenbrock function.
Parameters
----------
x : array_like
    1-D array of points at which the derivative is to be computed.
Returns
-------
rosen_der : (N,) ndarray
    The gradient of the Rosenbrock function at `x`.
See Also
--------
rosen, rosen_hess, rosen_hess_prod
Examples
--------
>>> import numpy as np
>>> from scipy.optimize import rosen_der
>>> X = 0.1 * np.arange(9)
>>> rosen_der(X)
array([ -2. ,  10.6,  15.6,  13.4,   6.4,  -3. , -12.4, -19.4,  62. ])
Definition at line 460 of file _optimize.py.
rosen_hess()
scipy.optimize._optimize.rosen_hess (x)
The Hessian matrix of the Rosenbrock function.
Parameters
----------
x : array_like
    1-D array of points at which the Hessian matrix is to be computed.
Returns
-------
rosen_hess : ndarray
    The Hessian matrix of the Rosenbrock function at `x`.
See Also
--------
rosen, rosen_der, rosen_hess_prod
Examples
--------
>>> import numpy as np
>>> from scipy.optimize import rosen_hess
>>> X = 0.1 * np.arange(4)
>>> rosen_hess(X)
array([[-38.,   0.,   0.,   0.],
       [  0., 134., -40.,   0.],
       [  0., -40., 130., -80.],
       [  0.,   0., -80., 200.]])
Definition at line 499 of file _optimize.py.
rosen_hess_prod()
scipy.optimize._optimize.rosen_hess_prod (x, p)
Product of the Hessian matrix of the Rosenbrock function with a vector.
Parameters
----------
x : array_like
    1-D array of points at which the Hessian matrix is to be computed.
p : array_like
    1-D array, the vector to be multiplied by the Hessian matrix.
Returns
-------
rosen_hess_prod : ndarray
    The Hessian matrix of the Rosenbrock function at `x` multiplied
    by the vector `p`.
See Also
--------
rosen, rosen_der, rosen_hess
Examples
--------
>>> import numpy as np
>>> from scipy.optimize import rosen_hess_prod
>>> X = 0.1 * np.arange(9)
>>> p = 0.5 * np.arange(9)
>>> rosen_hess_prod(X, p)
array([  -0.,   27.,  -10.,  -95., -192., -265., -278., -195., -180.])
Definition at line 539 of file _optimize.py.
show_options()
scipy.optimize._optimize.show_options (solver = None, method = None, disp = True)
Show documentation for additional options of optimization solvers.
These are method-specific options that can be supplied through the
``options`` dict.
Parameters
----------
solver : str
    Type of optimization solver. One of 'minimize', 'minimize_scalar',
    'root', 'root_scalar', 'linprog', or 'quadratic_assignment'.
method : str, optional
    If not given, shows all methods of the specified solver. Otherwise,
    show only the options for the specified method. Valid values
    corresponds to methods' names of respective solver (e.g., 'BFGS' for
    'minimize').
disp : bool, optional
    Whether to print the result rather than returning it.
Returns
-------
text
    Either None (for disp=True) or the text string (disp=False)
Notes
-----
The solver-specific methods are:
`scipy.optimize.minimize`
- :ref:`Nelder-Mead <optimize.minimize-neldermead>`
- :ref:`Powell      <optimize.minimize-powell>`
- :ref:`CG          <optimize.minimize-cg>`
- :ref:`BFGS        <optimize.minimize-bfgs>`
- :ref:`Newton-CG   <optimize.minimize-newtoncg>`
- :ref:`L-BFGS-B    <optimize.minimize-lbfgsb>`
- :ref:`TNC         <optimize.minimize-tnc>`
- :ref:`COBYLA      <optimize.minimize-cobyla>`
- :ref:`SLSQP       <optimize.minimize-slsqp>`
- :ref:`dogleg      <optimize.minimize-dogleg>`
- :ref:`trust-ncg   <optimize.minimize-trustncg>`
`scipy.optimize.root`
- :ref:`hybr              <optimize.root-hybr>`
- :ref:`lm                <optimize.root-lm>`
- :ref:`broyden1          <optimize.root-broyden1>`
- :ref:`broyden2          <optimize.root-broyden2>`
- :ref:`anderson          <optimize.root-anderson>`
- :ref:`linearmixing      <optimize.root-linearmixing>`
- :ref:`diagbroyden       <optimize.root-diagbroyden>`
- :ref:`excitingmixing    <optimize.root-excitingmixing>`
- :ref:`krylov            <optimize.root-krylov>`
- :ref:`df-sane           <optimize.root-dfsane>`
`scipy.optimize.minimize_scalar`
- :ref:`brent       <optimize.minimize_scalar-brent>`
- :ref:`golden      <optimize.minimize_scalar-golden>`
- :ref:`bounded     <optimize.minimize_scalar-bounded>`
`scipy.optimize.root_scalar`
- :ref:`bisect  <optimize.root_scalar-bisect>`
- :ref:`brentq  <optimize.root_scalar-brentq>`
- :ref:`brenth  <optimize.root_scalar-brenth>`
- :ref:`ridder  <optimize.root_scalar-ridder>`
- :ref:`toms748 <optimize.root_scalar-toms748>`
- :ref:`newton  <optimize.root_scalar-newton>`
- :ref:`secant  <optimize.root_scalar-secant>`
- :ref:`halley  <optimize.root_scalar-halley>`
`scipy.optimize.linprog`
- :ref:`simplex           <optimize.linprog-simplex>`
- :ref:`interior-point    <optimize.linprog-interior-point>`
- :ref:`revised simplex   <optimize.linprog-revised_simplex>`
- :ref:`highs             <optimize.linprog-highs>`
- :ref:`highs-ds          <optimize.linprog-highs-ds>`
- :ref:`highs-ipm         <optimize.linprog-highs-ipm>`
`scipy.optimize.quadratic_assignment`
- :ref:`faq             <optimize.qap-faq>`
- :ref:`2opt            <optimize.qap-2opt>`
Examples
--------
We can print documentations of a solver in stdout:
>>> from scipy.optimize import show_options
>>> show_options(solver="minimize")
...
Specifying a method is possible:
>>> show_options(solver="minimize", method="Nelder-Mead")
...
We can also get the documentations as a string:
>>> show_options(solver="minimize", method="Nelder-Mead", disp=False)
Minimization of scalar function of one or more variables using the ...
Definition at line 3890 of file _optimize.py.
References show_options().
Referenced by show_options(), and scipy.optimize.tests.test_optimize.test_equal_bounds().
vecnorm()
scipy.optimize._optimize.vecnorm (x, ord = 2)
Definition at line 286 of file _optimize.py.
Variable Documentation
__all__
list scipy.optimize._optimize.__all__ private
Initial value:
=  ['fmin', 'fmin_powell', 'fmin_bfgs', 'fmin_ncg', 'fmin_cg',
           'fminbound', 'brent', 'golden', 'bracket', 'rosen', 'rosen_der',
           'rosen_hess', 'rosen_hess_prod', 'brute', 'approx_fprime',
           'line_search', 'check_grad', 'OptimizeResult', 'show_options',
           'OptimizeWarning']
Definition at line 20 of file _optimize.py.
__docformat__
str scipy.optimize._optimize.__docformat__ = "restructuredtext en" private
Definition at line 26 of file _optimize.py.
_epsilon
scipy.optimize._optimize._epsilon = sqrt(np.finfo(float).eps) protected
Definition at line 283 of file _optimize.py.
_status_message
dict scipy.optimize._optimize._status_message protected
Initial value:
=  {'success': 'Optimization terminated successfully.',
                   'maxfev': 'Maximum number of function evaluations has '
                              'been exceeded.',
                   'maxiter': 'Maximum number of iterations has been '
                              'exceeded.',
                   'pr_loss': 'Desired error not necessarily achieved due '
                              'to precision loss.',
                   'nan': 'NaN result encountered.',
                   'out_of_bounds': 'The result is outside of the provided '
                                    'bounds.'}
Definition at line 46 of file _optimize.py.