Code Cloning Analysis: sklearn.cluster._optics Namespace Reference
sklearn.cluster._optics Namespace Reference
Classes
class OPTICS
Functions
_validate_size (size, n_samples, param_name)
_compute_core_distances_ (X, neighbors, min_samples, working_memory)
compute_optics_graph (X, *, min_samples, max_eps, metric, p, metric_params, algorithm, leaf_size, n_jobs)
_set_reach_dist (core_distances_, reachability_, predecessor_, point_index, processed, X, nbrs, metric, metric_params, p, max_eps)
cluster_optics_dbscan (*, reachability, core_distances, ordering, eps)
cluster_optics_xi (*, reachability, predecessor, ordering, min_samples, min_cluster_size=None, xi=0.05, predecessor_correction=True)
_extend_region (steep_point, xward_point, start, min_samples)
_update_filter_sdas (sdas, mib, xi_complement, reachability_plot)
_correct_predecessor (reachability_plot, predecessor_plot, ordering, s, e)
_xi_cluster (reachability_plot, predecessor_plot, ordering, xi, min_samples, min_cluster_size, predecessor_correction)
_extract_xi_labels (ordering, clusters)
Detailed Description
Ordering Points To Identify the Clustering Structure (OPTICS)
These routines execute the OPTICS algorithm, and implement various
cluster extraction methods of the ordered list.
Function Documentation
_compute_core_distances_()
sklearn.cluster._optics._compute_core_distances_ (X, neighbors, min_samples, working_memory) protected
Compute the k-th nearest neighbor of each sample.
Equivalent to neighbors.kneighbors(X, self.min_samples)[0][:, -1]
but with more memory efficiency.
Parameters
----------
X : array-like of shape (n_samples, n_features)
    The data.
neighbors : NearestNeighbors instance
    The fitted nearest neighbors estimator.
working_memory : int, default=None
    The sought maximum memory for temporary distance matrix chunks.
    When None (default), the value of
    ``sklearn.get_config()['working_memory']`` is used.
Returns
-------
core_distances : ndarray of shape (n_samples,)
    Distance at which each sample becomes a core point.
    Points which will never be core have a distance of inf.
Definition at line 406 of file _optics.py.
Referenced by compute_optics_graph().
_correct_predecessor()
sklearn.cluster._optics._correct_predecessor (reachability_plot, predecessor_plot, ordering, s, e) protected
Correct for predecessors.
Applies Algorithm 2 of [1]_.
Input parameters are ordered by the computer OPTICS ordering.
.. [1] Schubert, Erich, Michael Gertz.
   "Improving the Cluster Structure Extracted from OPTICS Plots." Proc. of
   the Conference "Lernen, Wissen, Daten, Analysen" (LWDA) (2018): 318-329.
Definition at line 999 of file _optics.py.
Referenced by _xi_cluster().
_extend_region()
sklearn.cluster._optics._extend_region (steep_point, xward_point, start, min_samples) protected
Extend the area until it's maximal.
It's the same function for both upward and downward reagions, depending on
the given input parameters. Assuming:
    - steep_{upward/downward}: bool array indicating whether a point is a
      steep {upward/downward};
    - upward/downward: bool array indicating whether a point is
      upward/downward;
To extend an upward reagion, ``steep_point=steep_upward`` and
``xward_point=downward`` are expected, and to extend a downward region,
``steep_point=steep_downward`` and ``xward_point=upward``.
Parameters
----------
steep_point : ndarray of shape (n_samples,), dtype=bool
    True if the point is steep downward (upward).
xward_point : ndarray of shape (n_samples,), dtype=bool
    True if the point is an upward (respectively downward) point.
start : int
    The start of the xward region.
min_samples : int
   The same as the min_samples given to OPTICS. Up and down steep
   regions can't have more then ``min_samples`` consecutive non-steep
   points.
Returns
-------
index : int
    The current index iterating over all the samples, i.e. where we are up
    to in our search.
end : int
    The end of the region, which can be behind the index. The region
    includes the ``end`` index.
Definition at line 922 of file _optics.py.
Referenced by _xi_cluster().
_extract_xi_labels()
sklearn.cluster._optics._extract_xi_labels (ordering, clusters) protected
Extracts the labels from the clusters returned by `_xi_cluster`.
We rely on the fact that clusters are stored
with the smaller clusters coming before the larger ones.
Parameters
----------
ordering : array-like of shape (n_samples,)
    The ordering of points calculated by OPTICS
clusters : array-like of shape (n_clusters, 2)
    List of clusters i.e. (start, end) tuples,
    as returned by `_xi_cluster`.
Returns
-------
labels : ndarray of shape (n_samples,)
Definition at line 1176 of file _optics.py.
Referenced by cluster_optics_xi().
_set_reach_dist()
sklearn.cluster._optics._set_reach_dist (core_distances_, reachability_, predecessor_, point_index, processed, X, nbrs, metric, metric_params, p, max_eps) protected
Definition at line 672 of file _optics.py.
_update_filter_sdas()
sklearn.cluster._optics._update_filter_sdas (sdas, mib, xi_complement, reachability_plot) protected
Update steep down areas (SDAs) using the new maximum in between (mib)
value, and the given complement of xi, i.e. ``1 - xi``.
Definition at line 985 of file _optics.py.
Referenced by _xi_cluster().
_validate_size()
sklearn.cluster._optics._validate_size (size, n_samples, param_name) protected
Definition at line 397 of file _optics.py.
_xi_cluster()
sklearn.cluster._optics._xi_cluster (reachability_plot, predecessor_plot, ordering, xi, min_samples, min_cluster_size, predecessor_correction) protected
Automatically extract clusters according to the Xi-steep method.
This is rouphly an implementation of Figure 19 of the OPTICS paper.
Parameters
----------
reachability_plot : array-like of shape (n_samples,)
    The reachability plot, i.e. reachability ordered according to
    the calculated ordering, all computed by OPTICS.
predecessor_plot : array-like of shape (n_samples,)
    Predecessors ordered according to the calculated ordering.
xi : float, between 0 and 1
    Determines the minimum steepness on the reachability plot that
    constitutes a cluster boundary. For example, an upwards point in the
    reachability plot is defined by the ratio from one point to its
    successor being at most 1-xi.
min_samples : int > 1
    The same as the min_samples given to OPTICS. Up and down steep regions
    can't have more then ``min_samples`` consecutive non-steep points.
min_cluster_size : int > 1
    Minimum number of samples in an OPTICS cluster.
predecessor_correction : bool
    Correct clusters based on the calculated predecessors.
Returns
-------
clusters : ndarray of shape (n_clusters, 2)
    The list of clusters in the form of [start, end] in each row, with all
    indices inclusive. The clusters are ordered in a way that larger
    clusters encompassing smaller clusters come after those smaller
    clusters.
Definition at line 1021 of file _optics.py.
References _correct_predecessor(), _extend_region(), and _update_filter_sdas().
Referenced by cluster_optics_xi().
cluster_optics_dbscan()
sklearn.cluster._optics.cluster_optics_dbscan (* , reachability, core_distances, ordering, eps)
Perform DBSCAN extraction for an arbitrary epsilon.
Extracting the clusters runs in linear time. Note that this results in
``labels_`` which are close to a :class:`~sklearn.cluster.DBSCAN` with
similar settings and ``eps``, only if ``eps`` is close to ``max_eps``.
Parameters
----------
reachability : ndarray of shape (n_samples,)
    Reachability distances calculated by OPTICS (``reachability_``).
core_distances : ndarray of shape (n_samples,)
    Distances at which points become core (``core_distances_``).
ordering : ndarray of shape (n_samples,)
    OPTICS ordered point indices (``ordering_``).
eps : float
    DBSCAN ``eps`` parameter. Must be set to < ``max_eps``. Results
    will be close to DBSCAN algorithm if ``eps`` and ``max_eps`` are close
    to one another.
Returns
-------
labels_ : array of shape (n_samples,)
    The estimated labels.
Examples
--------
>>> import numpy as np
>>> from sklearn.cluster import cluster_optics_dbscan, compute_optics_graph
>>> X = np.array([[1, 2], [2, 5], [3, 6],
...               [8, 7], [8, 8], [7, 3]])
>>> ordering, core_distances, reachability, predecessor = compute_optics_graph(
...     X,
...     min_samples=2,
...     max_eps=np.inf,
...     metric="minkowski",
...     p=2,
...     metric_params=None,
...     algorithm="auto",
...     leaf_size=30,
...     n_jobs=None,
...)
>>> eps = 4.5
>>> labels = cluster_optics_dbscan(
...     reachability=reachability,
...     core_distances=core_distances,
...     ordering=ordering,
...     eps=eps,
...)
>>> labels
array([0, 0, 0, 1, 1, 1])
Definition at line 727 of file _optics.py.
Referenced by sklearn.cluster._optics.OPTICS.fit().
cluster_optics_xi()
sklearn.cluster._optics.cluster_optics_xi (* , reachability, predecessor, ordering, min_samples, min_cluster_size = None, xi = 0.05, predecessor_correction = True)
Automatically extract clusters according to the Xi-steep method.
Parameters
----------
reachability : ndarray of shape (n_samples,)
    Reachability distances calculated by OPTICS (`reachability_`).
predecessor : ndarray of shape (n_samples,)
    Predecessors calculated by OPTICS.
ordering : ndarray of shape (n_samples,)
    OPTICS ordered point indices (`ordering_`).
min_samples : int > 1 or float between 0 and 1
    The same as the min_samples given to OPTICS. Up and down steep regions
    can't have more then ``min_samples`` consecutive non-steep points.
    Expressed as an absolute number or a fraction of the number of samples
    (rounded to be at least 2).
min_cluster_size : int > 1 or float between 0 and 1, default=None
    Minimum number of samples in an OPTICS cluster, expressed as an
    absolute number or a fraction of the number of samples (rounded to be
    at least 2). If ``None``, the value of ``min_samples`` is used instead.
xi : float between 0 and 1, default=0.05
    Determines the minimum steepness on the reachability plot that
    constitutes a cluster boundary. For example, an upwards point in the
    reachability plot is defined by the ratio from one point to its
    successor being at most 1-xi.
predecessor_correction : bool, default=True
    Correct clusters based on the calculated predecessors.
Returns
-------
labels : ndarray of shape (n_samples,)
    The labels assigned to samples. Points which are not included
    in any cluster are labeled as -1.
clusters : ndarray of shape (n_clusters, 2)
    The list of clusters in the form of ``[start, end]`` in each row, with
    all indices inclusive. The clusters are ordered according to ``(end,
    -start)`` (ascending) so that larger clusters encompassing smaller
    clusters come after such nested smaller clusters. Since ``labels`` does
    not reflect the hierarchy, usually ``len(clusters) >
    np.unique(labels)``.
Examples
--------
>>> import numpy as np
>>> from sklearn.cluster import cluster_optics_xi, compute_optics_graph
>>> X = np.array([[1, 2], [2, 5], [3, 6],
...               [8, 7], [8, 8], [7, 3]])
>>> ordering, core_distances, reachability, predecessor = compute_optics_graph(
...     X,
...     min_samples=2,
...     max_eps=np.inf,
...     metric="minkowski",
...     p=2,
...     metric_params=None,
...     algorithm="auto",
...     leaf_size=30,
...     n_jobs=None
...)
>>> min_samples = 2
>>> labels, clusters = cluster_optics_xi(
...     reachability=reachability,
...     predecessor=predecessor,
...     ordering=ordering,
...     min_samples=min_samples,
...)
>>> labels
array([0, 0, 0, 1, 1, 1])
>>> clusters
array([[0, 2],
       [3, 5],
       [0, 5]])
Definition at line 811 of file _optics.py.
References _extract_xi_labels(), and _xi_cluster().
Referenced by sklearn.cluster._optics.OPTICS.fit().
compute_optics_graph()
sklearn.cluster._optics.compute_optics_graph (X, * , min_samples, max_eps, metric, p, metric_params, algorithm, leaf_size, n_jobs)
Compute the OPTICS reachability graph.
Read more in the :ref:`User Guide <optics>`.
Parameters
----------
X : {ndarray, sparse matrix} of shape (n_samples, n_features), or \
        (n_samples, n_samples) if metric='precomputed'
    A feature array, or array of distances between samples if
    metric='precomputed'.
min_samples : int > 1 or float between 0 and 1
    The number of samples in a neighborhood for a point to be considered
    as a core point. Expressed as an absolute number or a fraction of the
    number of samples (rounded to be at least 2).
max_eps : float, default=np.inf
    The maximum distance between two samples for one to be considered as
    in the neighborhood of the other. Default value of ``np.inf`` will
    identify clusters across all scales; reducing ``max_eps`` will result
    in shorter run times.
metric : str or callable, default='minkowski'
    Metric to use for distance computation. Any metric from scikit-learn
    or scipy.spatial.distance can be used.
    If metric is a callable function, it is called on each
    pair of instances (rows) and the resulting value recorded. The callable
    should take two arrays as input and return one value indicating the
    distance between them. This works for Scipy's metrics, but is less
    efficient than passing the metric name as a string. If metric is
    "precomputed", X is assumed to be a distance matrix and must be square.
    Valid values for metric are:
    - from scikit-learn: ['cityblock', 'cosine', 'euclidean', 'l1', 'l2',
      'manhattan']
    - from scipy.spatial.distance: ['braycurtis', 'canberra', 'chebyshev',
      'correlation', 'dice', 'hamming', 'jaccard', 'kulsinski',
      'mahalanobis', 'minkowski', 'rogerstanimoto', 'russellrao',
      'seuclidean', 'sokalmichener', 'sokalsneath', 'sqeuclidean',
      'yule']
    See the documentation for scipy.spatial.distance for details on these
    metrics.
    .. note::
       `'kulsinski'` is deprecated from SciPy 1.9 and will be removed in SciPy 1.11.
p : float, default=2
    Parameter for the Minkowski metric from
    :class:`~sklearn.metrics.pairwise_distances`. When p = 1, this is
    equivalent to using manhattan_distance (l1), and euclidean_distance
    (l2) for p = 2. For arbitrary p, minkowski_distance (l_p) is used.
metric_params : dict, default=None
    Additional keyword arguments for the metric function.
algorithm : {'auto', 'ball_tree', 'kd_tree', 'brute'}, default='auto'
    Algorithm used to compute the nearest neighbors:
    - 'ball_tree' will use :class:`~sklearn.neighbors.BallTree`.
    - 'kd_tree' will use :class:`~sklearn.neighbors.KDTree`.
    - 'brute' will use a brute-force search.
    - 'auto' will attempt to decide the most appropriate algorithm
      based on the values passed to `fit` method. (default)
    Note: fitting on sparse input will override the setting of
    this parameter, using brute force.
leaf_size : int, default=30
    Leaf size passed to :class:`~sklearn.neighbors.BallTree` or
    :class:`~sklearn.neighbors.KDTree`. This can affect the speed of the
    construction and query, as well as the memory required to store the
    tree. The optimal value depends on the nature of the problem.
n_jobs : int, default=None
    The number of parallel jobs to run for neighbors search.
    ``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.
    ``-1`` means using all processors. See :term:`Glossary <n_jobs>`
    for more details.
Returns
-------
ordering_ : array of shape (n_samples,)
    The cluster ordered list of sample indices.
core_distances_ : array of shape (n_samples,)
    Distance at which each sample becomes a core point, indexed by object
    order. Points which will never be core have a distance of inf. Use
    ``clust.core_distances_[clust.ordering_]`` to access in cluster order.
reachability_ : array of shape (n_samples,)
    Reachability distances per sample, indexed by object order. Use
    ``clust.reachability_[clust.ordering_]`` to access in cluster order.
predecessor_ : array of shape (n_samples,)
    Point that a sample was reached from, indexed by object order.
    Seed points have a predecessor of -1.
References
----------
.. [1] Ankerst, Mihael, Markus M. Breunig, Hans-Peter Kriegel,
   and Jörg Sander. "OPTICS: ordering points to identify the clustering
   structure." ACM SIGMOD Record 28, no. 2 (1999): 49-60.
Examples
--------
>>> import numpy as np
>>> from sklearn.cluster import compute_optics_graph
>>> X = np.array([[1, 2], [2, 5], [3, 6],
...               [8, 7], [8, 8], [7, 3]])
>>> ordering, core_distances, reachability, predecessor = compute_optics_graph(
...     X,
...     min_samples=2,
...     max_eps=np.inf,
...     metric="minkowski",
...     p=2,
...     metric_params=None,
...     algorithm="auto",
...     leaf_size=30,
...     n_jobs=None,
...)
>>> ordering
array([0, 1, 2, 5, 3, 4])
>>> core_distances
array([3.16, 1.41, 1.41, 1.        , 1.        ,
       4.12])
>>> reachability
array([       inf, 3.16, 1.41, 4.12, 1.        ,
       5.        ])
>>> predecessor
array([-1,  0,  1,  5,  3,  2])
Definition at line 459 of file _optics.py.
References _compute_core_distances_().