Code Cloning Analysis: numpy.f2py.f2py2e Namespace Reference
numpy.f2py.f2py2e Namespace Reference
Classes
class CombineIncludePaths
Functions
scaninputline (inputline)
callcrackfortran (files, options)
buildmodules (lst)
dict_append (d_out, d_in)
run_main (comline_list)
filter_files (prefix, suffix, files, remove_prefix=None)
get_prefix (module)
include_parser ()
get_includes (iline)
make_f2py_compile_parser ()
preparse_sysargv ()
run_compile ()
validate_modulename (pyf_files, modulename='untitled')
main ()
Variables
f2py_version = __version__.version
numpy_version = __version__.version
errmess = sys.stderr.write
show = pprint.pprint
outmess = auxfuncs.outmess
tuple MESON_ONLY_VER = (sys.version_info >= (3, 12))
str __usage__
Detailed Description
f2py2e - Fortran to Python C/API generator. 2nd Edition.
         See __usage__ below.
Copyright 1999 -- 2011 Pearu Peterson all rights reserved.
Copyright 2011 -- present NumPy Developers.
Permission to use, modify, and distribute this software is given under the
terms of the NumPy License.
NO WARRANTY IS EXPRESSED OR IMPLIED.  USE AT YOUR OWN RISK.
Function Documentation
buildmodules()
numpy.f2py.f2py2e.buildmodules (lst)
Definition at line 371 of file f2py2e.py.
callcrackfortran()
numpy.f2py.f2py2e.callcrackfortran (files, options)
Definition at line 335 of file f2py2e.py.
dict_append()
numpy.f2py.f2py2e.dict_append (d_out, d_in)
Definition at line 406 of file f2py2e.py.
filter_files()
numpy.f2py.f2py2e.filter_files (prefix, suffix, files, remove_prefix = None)
Filter files by prefix and suffix.
Definition at line 504 of file f2py2e.py.
Referenced by run_compile(), and run_main().
get_includes()
numpy.f2py.f2py2e.get_includes (iline)
Definition at line 545 of file f2py2e.py.
get_prefix()
numpy.f2py.f2py2e.get_prefix (module)
Definition at line 522 of file f2py2e.py.
include_parser()
numpy.f2py.f2py2e.include_parser ()
Definition at line 538 of file f2py2e.py.
main()
numpy.f2py.f2py2e.main ()
Definition at line 755 of file f2py2e.py.
make_f2py_compile_parser()
numpy.f2py.f2py2e.make_f2py_compile_parser ()
Definition at line 554 of file f2py2e.py.
preparse_sysargv()
numpy.f2py.f2py2e.preparse_sysargv ()
Definition at line 561 of file f2py2e.py.
run_compile()
numpy.f2py.f2py2e.run_compile ()
Do it all in one call!
Definition at line 581 of file f2py2e.py.
References filter_files(), run_compile(), and numpy.lib.shape_base.split().
Referenced by run_compile().
run_main()
numpy.f2py.f2py2e.run_main (comline_list)
Equivalent to running::
    f2py <args>
where ``<args>=string.join(<list>,' ')``, but in Python.  Unless
``-h`` is used, this function returns a dictionary containing
information on generated modules and their dependencies on source
files.
You cannot build extension modules with this function, that is,
using ``-c`` is not allowed. Use the ``compile`` command instead.
Examples
--------
The command ``f2py -m scalar scalar.f`` can be executed from Python as
follows.
.. literalinclude:: ../../source/f2py/code/results/run_main_session.dat
    :language: python
Definition at line 416 of file f2py2e.py.
References numpy.lib.function_base.append(), and filter_files().
scaninputline()
numpy.f2py.f2py2e.scaninputline (inputline)
Definition at line 193 of file f2py2e.py.
validate_modulename()
numpy.f2py.f2py2e.validate_modulename (pyf_files, modulename = 'untitled')
Definition at line 741 of file f2py2e.py.
Variable Documentation
__usage__
str numpy.f2py.f2py2e.__usage__ private
Definition at line 41 of file f2py2e.py.
errmess
numpy.f2py.f2py2e.errmess = sys.stderr.write
Definition at line 35 of file f2py2e.py.
f2py_version
numpy.f2py.f2py2e.f2py_version = __version__.version
Definition at line 33 of file f2py2e.py.
MESON_ONLY_VER
tuple numpy.f2py.f2py2e.MESON_ONLY_VER = (sys.version_info >= (3, 12))
Definition at line 39 of file f2py2e.py.
numpy_version
numpy.f2py.f2py2e.numpy_version = __version__.version
Definition at line 34 of file f2py2e.py.
outmess
numpy.f2py.f2py2e.outmess = auxfuncs.outmess
Definition at line 38 of file f2py2e.py.
show
numpy.f2py.f2py2e.show = pprint.pprint
Definition at line 37 of file f2py2e.py.