Code Cloning Analysis: pandas.core.arrays.sparse.scipy_sparse Namespace Reference
pandas.core.arrays.sparse.scipy_sparse Namespace Reference
Functions
_check_is_partition (Iterable parts, Iterable whole)
tuple[npt.NDArray[np.intp], list[IndexLabel]] _levels_to_axis (ss, tuple[int]|list[int] levels, npt.NDArray[np.intp] valid_ilocs, bool sort_labels=False)
tuple[ np.ndarray, npt.NDArray[np.intp], npt.NDArray[np.intp], list[IndexLabel], list[IndexLabel],] _to_ijv (ss, tuple[int]|list[int] row_levels=(0,), tuple[int]|list[int] column_levels=(1,), bool sort_labels=False)
tuple[scipy.sparse.coo_matrix, list[IndexLabel], list[IndexLabel]] sparse_series_to_coo (Series ss, Iterable[int] row_levels=(0,), Iterable[int] column_levels=(1,), bool sort_labels=False)
Series coo_to_sparse_series (scipy.sparse.coo_matrix A, bool dense_index=False)
Detailed Description
Interaction with scipy.sparse matrices.
Currently only includes to_coo helpers.
Function Documentation
_check_is_partition()
pandas.core.arrays.sparse.scipy_sparse._check_is_partition (Iterable parts, Iterable whole) protected
Definition at line 30 of file scipy_sparse.py.
_levels_to_axis()
tuple[npt.NDArray[np.intp], list[IndexLabel]] pandas.core.arrays.sparse.scipy_sparse._levels_to_axis (ss, tuple[int] | list[int] levels, npt.NDArray[np.intp] valid_ilocs, bool sort_labels = False) protected
For a MultiIndexed sparse Series `ss`, return `ax_coords` and `ax_labels`,
where `ax_coords` are the coordinates along one of the two axes of the
destination sparse matrix, and `ax_labels` are the labels from `ss`' Index
which correspond to these coordinates.
Parameters
----------
ss : Series
levels : tuple/list
valid_ilocs : numpy.ndarray
    Array of integer positions of valid values for the sparse matrix in ss.
sort_labels : bool, default False
    Sort the axis labels before forming the sparse matrix. When `levels`
    refers to a single level, set to True for a faster execution.
Returns
-------
ax_coords : numpy.ndarray (axis coordinates)
ax_labels : list (axis labels)
Definition at line 39 of file scipy_sparse.py.
Referenced by _to_ijv().
_to_ijv()
tuple[ np.ndarray, npt.NDArray[np.intp], npt.NDArray[np.intp], list[IndexLabel], list[IndexLabel], ] pandas.core.arrays.sparse.scipy_sparse._to_ijv (ss, tuple[int] | list[int] row_levels = (0,), tuple[int] | list[int] column_levels = (1,), bool sort_labels = False) protected
For an arbitrary MultiIndexed sparse Series return (v, i, j, ilabels,
jlabels) where (v, (i, j)) is suitable for passing to scipy.sparse.coo
constructor, and ilabels and jlabels are the row and column labels
respectively.
Parameters
----------
ss : Series
row_levels : tuple/list
column_levels : tuple/list
sort_labels : bool, default False
    Sort the row and column labels before forming the sparse matrix.
    When `row_levels` and/or `column_levels` refer to a single level,
    set to `True` for a faster execution.
Returns
-------
values : numpy.ndarray
    Valid values to populate a sparse matrix, extracted from
    ss.
i_coords : numpy.ndarray (row coordinates of the values)
j_coords : numpy.ndarray (column coordinates of the values)
i_labels : list (row labels)
j_labels : list (column labels)
Definition at line 84 of file scipy_sparse.py.
References _levels_to_axis().
Referenced by sparse_series_to_coo().
coo_to_sparse_series()
Series pandas.core.arrays.sparse.scipy_sparse.coo_to_sparse_series (scipy.sparse.coo_matrix A, bool dense_index = False)
Convert a scipy.sparse.coo_matrix to a Series with type sparse.
Parameters
----------
A : scipy.sparse.coo_matrix
dense_index : bool, default False
Returns
-------
Series
Raises
------
TypeError if A is not a coo_matrix
Definition at line 175 of file scipy_sparse.py.
sparse_series_to_coo()
tuple[scipy.sparse.coo_matrix, list[IndexLabel], list[IndexLabel]] pandas.core.arrays.sparse.scipy_sparse.sparse_series_to_coo (Series ss, Iterable[int] row_levels = (0,), Iterable[int] column_levels = (1,), bool sort_labels = False)
Convert a sparse Series to a scipy.sparse.coo_matrix using index
levels row_levels, column_levels as the row and column
labels respectively. Returns the sparse_matrix, row and column labels.
Definition at line 142 of file scipy_sparse.py.
References _to_ijv().