Code Cloning Analysis: matplotlib.testing.jpl_units.UnitDblConverter.UnitDblConverter Class Reference
matplotlib.testing.jpl_units.UnitDblConverter.UnitDblConverter Class Reference
Static Public Member Functions
axisinfo (unit, axis)
convert (value, unit, axis)
default_units (value, axis)
Static Public Attributes
dict defaults
Detailed Description
Provides Matplotlib conversion functionality for the Monte UnitDbl class.
Definition at line 29 of file UnitDblConverter.py.
Member Function Documentation
axisinfo()
matplotlib.testing.jpl_units.UnitDblConverter.UnitDblConverter.axisinfo (unit, axis) static
Return an `.AxisInfo` for the axis with the specified units.
Reimplemented from matplotlib.units.ConversionInterface.
Definition at line 41 of file UnitDblConverter.py.
convert()
matplotlib.testing.jpl_units.UnitDblConverter.UnitDblConverter.convert (obj, unit, axis) static
Convert *obj* using *unit* for the specified *axis*.
If *obj* is a sequence, return the converted sequence.  The output must
be a sequence of scalars that can be used by the numpy array layer.
Reimplemented from matplotlib.units.ConversionInterface.
Definition at line 64 of file UnitDblConverter.py.
Referenced by pandas.core.computation.engines.NumExprEngine._evaluate(), pandas.core.internals.blocks.Block.convert(), PIL.Image.Image.reduce(), PIL.Image.Image.resize(), and PIL.Image.Image.transform().
default_units()
matplotlib.testing.jpl_units.UnitDblConverter.UnitDblConverter.default_units (x, axis) static
Return the default unit for *x* or ``None`` for the given axis.
Reimplemented from matplotlib.units.ConversionInterface.
Definition at line 78 of file UnitDblConverter.py.
Member Data Documentation
defaults
dict matplotlib.testing.jpl_units.UnitDblConverter.UnitDblConverter.defaults static
Initial value:
=  {
       "distance": 'km',
       "angle": 'deg',
       "time": 'sec',
       }
Definition at line 34 of file UnitDblConverter.py.
Referenced by pip._internal.cli.parser.ConfigOptionParser._update_defaults(), and pip._internal.cli.parser.ConfigOptionParser.get_default_values().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/testing/jpl_units/UnitDblConverter.py