Code Cloning Analysis: scipy.io.tests.test_mmio.TestMMIOCoordinate Class Reference
scipy.io.tests.test_mmio.TestMMIOCoordinate Class Reference
Public Member Functions
setup_method (self)
teardown_method (self)
check_read (self, example, a, info)
test_read_general (self)
test_read_hermitian (self)
test_read_skew (self)
test_read_symmetric (self)
test_read_symmetric_pattern (self)
test_read_empty_lines (self)
test_empty_write_read (self)
test_bzip2_py3 (self)
test_gzip_py3 (self)
test_real_write_read (self)
test_complex_write_read (self)
test_sparse_formats (self, tmp_path)
test_precision (self)
test_bad_number_of_coordinate_header_fields (self)
Public Attributes
tmpdir = mkdtemp()
fn = os.path.join(self.tmpdir, 'testfile.mtx')
Detailed Description
Definition at line 536 of file test_mmio.py.
Member Function Documentation
check_read()
scipy.io.tests.test_mmio.TestMMIOCoordinate.check_read (self, example, a, info)
Definition at line 544 of file test_mmio.py.
setup_method()
scipy.io.tests.test_mmio.TestMMIOCoordinate.setup_method (self)
Definition at line 537 of file test_mmio.py.
teardown_method()
scipy.io.tests.test_mmio.TestMMIOCoordinate.teardown_method (self)
Definition at line 541 of file test_mmio.py.
test_bad_number_of_coordinate_header_fields()
scipy.io.tests.test_mmio.TestMMIOCoordinate.test_bad_number_of_coordinate_header_fields (self)
Definition at line 738 of file test_mmio.py.
test_bzip2_py3()
scipy.io.tests.test_mmio.TestMMIOCoordinate.test_bzip2_py3 (self)
Definition at line 618 of file test_mmio.py.
test_complex_write_read()
scipy.io.tests.test_mmio.TestMMIOCoordinate.test_complex_write_read (self)
Definition at line 681 of file test_mmio.py.
test_empty_write_read()
scipy.io.tests.test_mmio.TestMMIOCoordinate.test_empty_write_read (self)
Definition at line 606 of file test_mmio.py.
test_gzip_py3()
scipy.io.tests.test_mmio.TestMMIOCoordinate.test_gzip_py3 (self)
Definition at line 642 of file test_mmio.py.
test_precision()
scipy.io.tests.test_mmio.TestMMIOCoordinate.test_precision (self)
Definition at line 721 of file test_mmio.py.
test_read_empty_lines()
scipy.io.tests.test_mmio.TestMMIOCoordinate.test_read_empty_lines (self)
Definition at line 597 of file test_mmio.py.
test_read_general()
scipy.io.tests.test_mmio.TestMMIOCoordinate.test_read_general (self)
Definition at line 552 of file test_mmio.py.
test_read_hermitian()
scipy.io.tests.test_mmio.TestMMIOCoordinate.test_read_hermitian (self)
Definition at line 561 of file test_mmio.py.
test_read_skew()
scipy.io.tests.test_mmio.TestMMIOCoordinate.test_read_skew (self)
Definition at line 570 of file test_mmio.py.
test_read_symmetric()
scipy.io.tests.test_mmio.TestMMIOCoordinate.test_read_symmetric (self)
Definition at line 579 of file test_mmio.py.
test_read_symmetric_pattern()
scipy.io.tests.test_mmio.TestMMIOCoordinate.test_read_symmetric_pattern (self)
Definition at line 588 of file test_mmio.py.
test_real_write_read()
scipy.io.tests.test_mmio.TestMMIOCoordinate.test_real_write_read (self)
Definition at line 666 of file test_mmio.py.
test_sparse_formats()
scipy.io.tests.test_mmio.TestMMIOCoordinate.test_sparse_formats (self, tmp_path)
Definition at line 697 of file test_mmio.py.
Member Data Documentation
fn
scipy.io.tests.test_mmio.TestMMIOCoordinate.fn = os.path.join(self.tmpdir, 'testfile.mtx')
Definition at line 539 of file test_mmio.py.
Referenced by scipy.optimize._shgo.SHGO.find_minima(), scipy.optimize._shgo.SHGO.iterate_all(), scipy.optimize._shgo.SHGO.iterate_delaunay(), scipy.optimize._shgo.SHGO.iterate_hypercube(), and scipy.optimize._shgo.SHGO.sort_result().
tmpdir
scipy.io.tests.test_mmio.TestMMIOCoordinate.tmpdir = mkdtemp()
Definition at line 538 of file test_mmio.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/io/tests/test_mmio.py