Code Cloning Analysis: scipy.interpolate._polyint._Interpolator1DWithDerivatives Class Reference
scipy.interpolate._polyint._Interpolator1DWithDerivatives Class Reference
Public Member Functions
derivatives (self, x, der=None)
derivative (self, x, der=1)
Public Member Functions inherited from scipy.interpolate._polyint._Interpolator1D
__init__ (self, xi=None, yi=None, axis=None)
__call__ (self, x)
Additional Inherited Members
Public Attributes inherited from scipy.interpolate._polyint._Interpolator1D
dtype = None
Protected Member Functions inherited from scipy.interpolate._polyint._Interpolator1D
_evaluate (self, x)
_prepare_x (self, x)
_finish_y (self, y, x_shape)
_reshape_yi (self, yi, check=False)
_set_yi (self, yi, xi=None, axis=None)
_set_dtype (self, dtype, union=False)
Protected Attributes inherited from scipy.interpolate._polyint._Interpolator1D
tuple _y_axis = axis
_y_extra_shape = None
Detailed Description
Definition at line 143 of file _polyint.py.
Member Function Documentation
derivative()
scipy.interpolate._polyint._Interpolator1DWithDerivatives.derivative (self, x, der = 1)
Evaluate one derivative of the polynomial at the point x
Parameters
----------
x : array_like
    Point or points at which to evaluate the derivatives
der : integer, optional
    Which derivative to extract. This number includes the
    function value as 0th derivative.
Returns
-------
d : ndarray
    Derivative interpolated at the x-points. Shape of d is
    determined by replacing the interpolation axis in the
    original array with the shape of x.
Notes
-----
This is computed by evaluating all derivatives up to the desired
one (using self.derivatives()) and then discarding the rest.
Definition at line 191 of file _polyint.py.
References scipy.interpolate._polyint.KroghInterpolator._evaluate_derivatives(), scipy.interpolate._polyint._Interpolator1D._finish_y(), and scipy.interpolate._polyint._Interpolator1D._prepare_x().
derivatives()
scipy.interpolate._polyint._Interpolator1DWithDerivatives.derivatives (self, x, der = None)
Evaluate many derivatives of the polynomial at the point x
Produce an array of all derivative values at the point x.
Parameters
----------
x : array_like
    Point or points at which to evaluate the derivatives
der : int or None, optional
    How many derivatives to extract; None for all potentially
    nonzero derivatives (that is a number equal to the number
    of points). This number includes the function value as 0th
    derivative.
Returns
-------
d : ndarray
    Array with derivatives; d[j] contains the jth derivative.
    Shape of d[j] is determined by replacing the interpolation
    axis in the original array with the shape of x.
Examples
--------
>>> from scipy.interpolate import KroghInterpolator
>>> KroghInterpolator([0,0,0],[1,2,3]).derivatives(0)
array([1.0,2.0,3.0])
>>> KroghInterpolator([0,0,0],[1,2,3]).derivatives([0,0])
array([[1.0,1.0],
       [2.0,2.0],
       [3.0,3.0]])
Definition at line 144 of file _polyint.py.
References scipy.interpolate._polyint.KroghInterpolator._evaluate_derivatives(), scipy.interpolate._polyint._Interpolator1D._prepare_x(), scipy.interpolate._polyint._Interpolator1D._y_axis, and scipy.interpolate._polyint._Interpolator1D._y_extra_shape.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/interpolate/_polyint.py