Code Cloning Analysis: fontTools.colorLib.unbuilder.LayerListUnbuilder Class Reference
fontTools.colorLib.unbuilder.LayerListUnbuilder Class Reference
Public Member Functions
__init__ (self, layers)
unbuildPaint (self, paint)
Public Attributes
layers = layers
tableUnbuilder = TableUnbuilder(callbacks)
Protected Member Functions
_unbuildPaintColrLayers (self, source)
Detailed Description
Definition at line 24 of file unbuilder.py.
Constructor & Destructor Documentation
__init__()
fontTools.colorLib.unbuilder.LayerListUnbuilder.__init__ (self, layers)
Definition at line 25 of file unbuilder.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_unbuildPaintColrLayers()
fontTools.colorLib.unbuilder.LayerListUnbuilder._unbuildPaintColrLayers (self, source) protected
Definition at line 40 of file unbuilder.py.
unbuildPaint()
fontTools.colorLib.unbuilder.LayerListUnbuilder.unbuildPaint (self, paint)
Definition at line 36 of file unbuilder.py.
Member Data Documentation
layers
fontTools.colorLib.unbuilder.LayerListUnbuilder.layers = layers
Definition at line 26 of file unbuilder.py.
Referenced by matplotlib.contour.ContourSet._process_colors(), matplotlib.contour.ContourSet._process_levels(), fontTools.varLib.merger.COLRVariationMerger.expandPaintColrLayers(), PIL.Jpeg2KImagePlugin.Jpeg2KImageFile.load(), and PIL.PsdImagePlugin.PsdImageFile.seek().
tableUnbuilder
fontTools.colorLib.unbuilder.LayerListUnbuilder.tableUnbuilder = TableUnbuilder(callbacks)
Definition at line 34 of file unbuilder.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/colorLib/unbuilder.py