Code Cloning Analysis: pandas.core.computation.pytables.PyTablesScope Class Reference
pandas.core.computation.pytables.PyTablesScope Class Reference
Public Member Functions
None __init__ (self, int level, global_dict=None, local_dict=None, dict[str, Any]|None queryables=None)
Static Public Attributes
dict queryables [str, Any]
Static Private Attributes
tuple __slots__ = ("queryables",)
Detailed Description
Definition at line 50 of file pytables.py.
Constructor & Destructor Documentation
__init__()
None pandas.core.computation.pytables.PyTablesScope.__init__ (self, int level, global_dict = None, local_dict = None, dict[str, Any] | None queryables = None)
Definition at line 55 of file pytables.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Data Documentation
__slots__
tuple pandas.core.computation.pytables.PyTablesScope.__slots__ = ("queryables",) static private
Definition at line 51 of file pytables.py.
queryables
dict pandas.core.computation.pytables.PyTablesScope.queryables [str, Any] static
Definition at line 53 of file pytables.py.
Referenced by pandas.core.computation.pytables.BinOp.is_in_table(), pandas.core.computation.pytables.BinOp.is_valid(), pandas.core.computation.pytables.BinOp.kind(), pandas.core.computation.pytables.BinOp.meta(), pandas.core.computation.pytables.BinOp.metadata(), and pandas.io.pytables.Table.validate_min_itemsize().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/core/computation/pytables.py