Code Cloning Analysis: fontTools.varLib.featureVars Namespace Reference
fontTools.varLib.featureVars Namespace Reference
Classes
class ShifterVisitor
Functions
addFeatureVariations (font, conditionalSubstitutions, featureTag="rvrn")
_existingVariableFeatures (table)
_checkSubstitutionGlyphsExist (glyphNames, substitutions)
overlayFeatureVariations (conditionalSubstitutions)
overlayBox (top, bot)
cleanupBox (box)
addFeatureVariationsRaw (font, table, conditionalSubstitutions, featureTag="rvrn")
buildGSUB ()
makeSubstitutionsHashable (conditionalSubstitutions)
visit (visitor, obj, attr, value)
buildSubstitutionLookups (gsub, allSubstitutions, processLast=False)
buildFeatureVariations (featureVariationRecords)
buildFeatureRecord (featureTag, lookupListIndices)
buildFeatureVariationRecord (conditionTable, substitutionRecords)
buildFeatureTableSubstitutionRecord (featureIndex, lookupListIndices)
buildConditionTable (axisIndex, filterRangeMinValue, filterRangeMaxValue)
findFeatureVariationRecord (featureVariations, conditionTable)
sortFeatureList (table)
remapFeatures (table, featureRemap)
_remapLangSys (langSys, featureRemap)
Detailed Description
Module to build FeatureVariation tables:
https://docs.microsoft.com/en-us/typography/opentype/spec/chapter2#featurevariations-table
NOTE: The API is experimental and subject to change.
Function Documentation
_checkSubstitutionGlyphsExist()
fontTools.varLib.featureVars._checkSubstitutionGlyphsExist (glyphNames, substitutions) protected
Definition at line 109 of file featureVars.py.
_existingVariableFeatures()
fontTools.varLib.featureVars._existingVariableFeatures (table) protected
Definition at line 99 of file featureVars.py.
_remapLangSys()
fontTools.varLib.featureVars._remapLangSys (langSys, featureRemap) protected
Definition at line 686 of file featureVars.py.
addFeatureVariations()
fontTools.varLib.featureVars.addFeatureVariations (font, conditionalSubstitutions, featureTag = "rvrn")
Add conditional substitutions to a Variable Font.
The `conditionalSubstitutions` argument is a list of (Region, Substitutions)
tuples.
A Region is a list of Boxes. A Box is a dict mapping axisTags to
(minValue, maxValue) tuples. Irrelevant axes may be omitted and they are
interpretted as extending to end of axis in each direction.  A Box represents
an orthogonal 'rectangular' subset of an N-dimensional design space.
A Region represents a more complex subset of an N-dimensional design space,
ie. the union of all the Boxes in the Region.
For efficiency, Boxes within a Region should ideally not overlap, but
functionality is not compromised if they do.
The minimum and maximum values are expressed in normalized coordinates.
A Substitution is a dict mapping source glyph names to substitute glyph names.
Example:
# >>> f = TTFont(srcPath)
# >>> condSubst = [
# ...     # A list of (Region, Substitution) tuples.
# ...     ([{"wdth": (0.5, 1.0)}], {"cent": "cent.rvrn"}),
# ...     ([{"wght": (0.5, 1.0)}], {"dollar": "dollar.rvrn"}),
# ... ]
# >>> addFeatureVariations(f, condSubst)
# >>> f.save(dstPath)
The `featureTag` parameter takes either a str or a iterable of str (the single str
is kept for backwards compatibility), and defines which feature(s) will be
associated with the feature variations.
Note, if this is "rvrn", then the substitution lookup will be inserted at the
beginning of the lookup list so that it is processed before others, otherwise
for any other feature tags it will be appended last.
Definition at line 18 of file featureVars.py.
References addFeatureVariationsRaw(), buildGSUB(), buildSubstitutionLookups(), makeSubstitutionsHashable(), and overlayFeatureVariations().
addFeatureVariationsRaw()
fontTools.varLib.featureVars.addFeatureVariationsRaw (font, table, conditionalSubstitutions, featureTag = "rvrn")
Low level implementation of addFeatureVariations that directly
models the possibilities of the FeatureVariations table.
Definition at line 351 of file featureVars.py.
References buildConditionTable(), buildFeatureRecord(), buildFeatureTableSubstitutionRecord(), buildFeatureVariationRecord(), buildFeatureVariations(), findFeatureVariationRecord(), and sortFeatureList().
Referenced by addFeatureVariations().
buildConditionTable()
fontTools.varLib.featureVars.buildConditionTable (axisIndex, filterRangeMinValue, filterRangeMaxValue)
Build a ConditionTable.
Definition at line 626 of file featureVars.py.
Referenced by addFeatureVariationsRaw().
buildFeatureRecord()
fontTools.varLib.featureVars.buildFeatureRecord (featureTag, lookupListIndices)
Build a FeatureRecord.
Definition at line 590 of file featureVars.py.
Referenced by addFeatureVariationsRaw().
buildFeatureTableSubstitutionRecord()
fontTools.varLib.featureVars.buildFeatureTableSubstitutionRecord (featureIndex, lookupListIndices)
Build a FeatureTableSubstitutionRecord.
Definition at line 616 of file featureVars.py.
Referenced by addFeatureVariationsRaw().
buildFeatureVariationRecord()
fontTools.varLib.featureVars.buildFeatureVariationRecord (conditionTable, substitutionRecords)
Build a FeatureVariationRecord.
Definition at line 600 of file featureVars.py.
Referenced by addFeatureVariationsRaw().
buildFeatureVariations()
fontTools.varLib.featureVars.buildFeatureVariations (featureVariationRecords)
Build the FeatureVariations subtable.
Definition at line 581 of file featureVars.py.
Referenced by addFeatureVariationsRaw().
buildGSUB()
fontTools.varLib.featureVars.buildGSUB ()
Build a GSUB table from scratch.
Definition at line 482 of file featureVars.py.
Referenced by addFeatureVariations().
buildSubstitutionLookups()
fontTools.varLib.featureVars.buildSubstitutionLookups (gsub, allSubstitutions, processLast = False)
Build the lookups for the glyph substitutions, return a dict mapping
the substitution to lookup indices.
Definition at line 550 of file featureVars.py.
Referenced by addFeatureVariations().
cleanupBox()
fontTools.varLib.featureVars.cleanupBox (box)
Return a sparse copy of `box`, without redundant (default) values.
>>> cleanupBox({})
{}
>>> cleanupBox({'wdth': (0.0, 1.0)})
{'wdth': (0.0, 1.0)}
>>> cleanupBox({'wdth': (-1.0, 1.0)})
{}
Definition at line 332 of file featureVars.py.
Referenced by overlayFeatureVariations().
findFeatureVariationRecord()
fontTools.varLib.featureVars.findFeatureVariationRecord (featureVariations, conditionTable)
Find a FeatureVariationRecord that has the same conditionTable.
Definition at line 636 of file featureVars.py.
Referenced by addFeatureVariationsRaw().
makeSubstitutionsHashable()
fontTools.varLib.featureVars.makeSubstitutionsHashable (conditionalSubstitutions)
Turn all the substitution dictionaries in sorted tuples of tuples so
they are hashable, to detect duplicates so we don't write out redundant
data.
Definition at line 515 of file featureVars.py.
Referenced by addFeatureVariations().
overlayBox()
fontTools.varLib.featureVars.overlayBox (top, bot)
Overlays ``top`` box on top of ``bot`` box.
Returns two items:
* Box for intersection of ``top`` and ``bot``, or None if they don't intersect.
* Box for remainder of ``bot``.  Remainder box might not be exact (since the
  remainder might not be a simple box), but is inclusive of the exact
  remainder.
Definition at line 247 of file featureVars.py.
Referenced by overlayFeatureVariations().
overlayFeatureVariations()
fontTools.varLib.featureVars.overlayFeatureVariations (conditionalSubstitutions)
Compute overlaps between all conditional substitutions.
The `conditionalSubstitutions` argument is a list of (Region, Substitutions)
tuples.
A Region is a list of Boxes. A Box is a dict mapping axisTags to
(minValue, maxValue) tuples. Irrelevant axes may be omitted and they are
interpretted as extending to end of axis in each direction.  A Box represents
an orthogonal 'rectangular' subset of an N-dimensional design space.
A Region represents a more complex subset of an N-dimensional design space,
ie. the union of all the Boxes in the Region.
For efficiency, Boxes within a Region should ideally not overlap, but
functionality is not compromised if they do.
The minimum and maximum values are expressed in normalized coordinates.
A Substitution is a dict mapping source glyph names to substitute glyph names.
Returns data is in similar but different format.  Overlaps of distinct
substitution Boxes (*not* Regions) are explicitly listed as distinct rules,
and rules with the same Box merged.  The more specific rules appear earlier
in the resulting list.  Moreover, instead of just a dictionary of substitutions,
a list of dictionaries is returned for substitutions corresponding to each
unique space, with each dictionary being identical to one of the input
substitution dictionaries.  These dictionaries are not merged to allow data
sharing when they are converted into font tables.
Example::
    >>> condSubst = [
    ...     # A list of (Region, Substitution) tuples.
    ...     ([{"wght": (0.5, 1.0)}], {"dollar": "dollar.rvrn"}),
    ...     ([{"wght": (0.5, 1.0)}], {"dollar": "dollar.rvrn"}),
    ...     ([{"wdth": (0.5, 1.0)}], {"cent": "cent.rvrn"}),
    ...     ([{"wght": (0.5, 1.0), "wdth": (-1, 1.0)}], {"dollar": "dollar.rvrn"}),
    ... ]
    >>> from pprint import pprint
    >>> pprint(overlayFeatureVariations(condSubst))
    [({'wdth': (0.5, 1.0), 'wght': (0.5, 1.0)},
      [{'dollar': 'dollar.rvrn'}, {'cent': 'cent.rvrn'}]),
     ({'wdth': (0.5, 1.0)}, [{'cent': 'cent.rvrn'}]),
     ({'wght': (0.5, 1.0)}, [{'dollar': 'dollar.rvrn'}])]
Definition at line 122 of file featureVars.py.
References cleanupBox(), and overlayBox().
Referenced by addFeatureVariations().
remapFeatures()
fontTools.varLib.featureVars.remapFeatures (table, featureRemap)
Go through the scripts list, and remap feature indices.
Definition at line 670 of file featureVars.py.
Referenced by sortFeatureList().
sortFeatureList()
fontTools.varLib.featureVars.sortFeatureList (table)
Sort the feature list by feature tag, and remap the feature indices
elsewhere. This is needed after the feature list has been modified.
Definition at line 651 of file featureVars.py.
References remapFeatures().
Referenced by addFeatureVariationsRaw().
visit()
fontTools.varLib.featureVars.visit (visitor, obj, attr, value)
Definition at line 537 of file featureVars.py.