Code Cloning Analysis: matplotlib.ticker.MultipleLocator Class Reference
matplotlib.ticker.MultipleLocator Class Reference
Public Member Functions
__init__ (self, base=1.0, offset=0.0)
set_params (self, base=None, offset=None)
__call__ (self)
tick_values (self, vmin, vmax)
view_limits (self, dmin, dmax)
Public Member Functions inherited from matplotlib.ticker.Locator
__call__ (self)
raise_if_exceeds (self, locs)
nonsingular (self, v0, v1)
Public Member Functions inherited from matplotlib.ticker.TickHelper
set_axis (self, axis)
create_dummy_axis (self, **kwargs)
Protected Attributes
_edge = _Edge_integer(base, 0)
_offset = offset
Additional Inherited Members
Static Public Attributes inherited from matplotlib.ticker.Locator
int MAXTICKS = 1000
Static Public Attributes inherited from matplotlib.ticker.TickHelper
axis = None
Detailed Description
Place ticks at every integer multiple of a base plus an offset.
Definition at line 1914 of file ticker.py.
Constructor & Destructor Documentation
__init__()
matplotlib.ticker.MultipleLocator.__init__ (self, base = 1.0, offset = 0.0)
Parameters
----------
base : float > 0, default: 1.0
    Interval between ticks.
offset : float, default: 0.0
    Value added to each multiple of *base*.
    .. versionadded:: 3.8
Definition at line 1919 of file ticker.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__call__()
matplotlib.ticker.MultipleLocator.__call__ (self)
Return the locations of the ticks.
Definition at line 1951 of file ticker.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), and scipy.interpolate._fitpack2.SphereBivariateSpline.ev().
set_params()
matplotlib.ticker.MultipleLocator.set_params (self, base = None, offset = None)
Set parameters within this locator.
Parameters
----------
base : float > 0, optional
    Interval between ticks.
offset : float, optional
    Value added to each multiple of *base*.
    .. versionadded:: 3.8
Reimplemented from matplotlib.ticker.Locator.
Definition at line 1933 of file ticker.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.theta().
tick_values()
matplotlib.ticker.MultipleLocator.tick_values (self, vmin, vmax)
Return the values of the located ticks given **vmin** and **vmax**.
.. note::
    To get tick locations with the vmin and vmax values defined
    automatically for the associated ``axis`` simply call
    the Locator instance::
        >>> print(type(loc))
        <type 'Locator'>
        >>> print(loc())
        [1, 2, 3, 4]
Reimplemented from matplotlib.ticker.Locator.
Definition at line 1956 of file ticker.py.
view_limits()
matplotlib.ticker.MultipleLocator.view_limits (self, dmin, dmax)
Set the view limits to the nearest tick values that contain the data.
Reimplemented from matplotlib.ticker.Locator.
Definition at line 1967 of file ticker.py.
Member Data Documentation
_edge
matplotlib.ticker.MultipleLocator._edge = _Edge_integer(base, 0) protected
Definition at line 1930 of file ticker.py.
_offset
matplotlib.ticker.MultipleLocator._offset = offset protected
Definition at line 1931 of file ticker.py.
Referenced by PIL.TiffImagePlugin.ImageFileDirectory_v2.__init__(), matplotlib.table.Table._offset(), PIL.TiffImagePlugin.ImageFileDirectory_v2.named(), and PIL.DcxImagePlugin.DcxImageFile.seek().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/ticker.py