Code Cloning Analysis: matplotlib.backend_tools.ToolPan Class Reference
matplotlib.backend_tools.ToolPan Class Reference
Public Member Functions
__init__ (self, *args)
Public Member Functions inherited from matplotlib.backend_tools.ZoomPanBase
__init__ (self, *args)
enable (self, event=None)
disable (self, event=None)
trigger (self, sender, event, data=None)
scroll_zoom (self, event)
Public Member Functions inherited from matplotlib.backend_tools.ToolToggleBase
__init__ (self, *args, **kwargs)
toggled (self)
set_figure (self, figure)
Public Member Functions inherited from matplotlib.backend_tools.ToolBase
__init__ (self, toolmanager, name)
Protected Member Functions
_cancel_action (self)
_press (self, event)
_release (self, event)
_mouse_move (self, event)
Protected Member Functions inherited from matplotlib.backend_tools.ToolBase
_make_classic_style_pseudo_toolbar (self)
Protected Attributes
_id_drag = None
Protected Attributes inherited from matplotlib.backend_tools.ZoomPanBase
_button_pressed = None
_xypress = None
_idPress = None
_idRelease = None
_idScroll = None
Protected Attributes inherited from matplotlib.backend_tools.ToolToggleBase
bool _toggled = kwargs.pop('toggled', self.default_toggled)
Protected Attributes inherited from matplotlib.backend_tools.ToolBase
_name = name
_toolmanager = toolmanager
_figure = None
Properties
default_keymap = property(lambda self: mpl.rcParams['keymap.pan'])
Properties inherited from matplotlib.backend_tools.ToolBase
name
toolmanager
canvas
figure
Additional Inherited Members
Public Attributes inherited from matplotlib.backend_tools.ZoomPanBase
int base_scale = 2.
int scrollthresh = .5
int lastscroll = time.time()-self.scrollthresh
Static Public Attributes inherited from matplotlib.backend_tools.ToolToggleBase
radio_group = None
cursor = None
bool default_toggled = False
Static Public Attributes inherited from matplotlib.backend_tools.ToolBase
default_keymap = None
description = None
image = None
Detailed Description
Pan Axes with left mouse, zoom with right.
Definition at line 825 of file backend_tools.py.
Constructor & Destructor Documentation
__init__()
matplotlib.backend_tools.ToolPan.__init__ (self, * args)
Definition at line 834 of file backend_tools.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_cancel_action()
matplotlib.backend_tools.ToolPan._cancel_action (self) protected
Definition at line 838 of file backend_tools.py.
Referenced by matplotlib.backend_tools.ZoomPanBase.disable().
_mouse_move()
matplotlib.backend_tools.ToolPan._mouse_move (self, event) protected
Definition at line 883 of file backend_tools.py.
_press()
matplotlib.backend_tools.ToolPan._press (self, event) protected
Definition at line 845 of file backend_tools.py.
Referenced by matplotlib.backend_tools.ZoomPanBase.enable(), and matplotlib.widgets._SelectorWidget.press().
_release()
matplotlib.backend_tools.ToolPan._release (self, event) protected
Definition at line 866 of file backend_tools.py.
Referenced by matplotlib.backend_tools.ZoomPanBase.enable().
Member Data Documentation
_id_drag
matplotlib.backend_tools.ToolPan._id_drag = None protected
Definition at line 836 of file backend_tools.py.
Property Documentation
default_keymap
matplotlib.backend_tools.ToolPan.default_keymap = property(lambda self: mpl.rcParams['keymap.pan']) static
Definition at line 828 of file backend_tools.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/backend_tools.py