Code Cloning Analysis: matplotlib._mathtext.StixFonts Class Reference
matplotlib._mathtext.StixFonts Class Reference
Public Member Functions
__init__ (self, FontProperties default_font_prop, LoadFlags load_glyph_flags)
list[tuple[str, str]]|list[tuple[int, str]] get_sized_alternatives_for_symbol (self, str fontname, str sym)
Public Member Functions inherited from matplotlib._mathtext.UnicodeFonts
__init__ (self, FontProperties default_font_prop, LoadFlags load_glyph_flags)
Public Member Functions inherited from matplotlib._mathtext.TruetypeFonts
__init__ (self, FontProperties default_font_prop, LoadFlags load_glyph_flags)
float get_xheight (self, str fontname, float fontsize, float dpi)
float get_underline_thickness (self, str font, float fontsize, float dpi)
float get_kern (self, str font1, str fontclass1, str sym1, float fontsize1, str font2, str fontclass2, str sym2, float fontsize2, float dpi)
Public Member Functions inherited from matplotlib._mathtext.Fonts
__init__ (self, FontProperties default_font_prop, LoadFlags load_glyph_flags)
FontMetrics get_metrics (self, str font, str font_class, str sym, float fontsize, float dpi)
None render_glyph (self, Output output, float ox, float oy, str font, str font_class, str sym, float fontsize, float dpi)
None render_rect_filled (self, Output output, float x1, float y1, float x2, float y2)
Protected Member Functions
tuple[str, int] _map_virtual_font (self, str fontname, str font_class, int uniindex)
Protected Member Functions inherited from matplotlib._mathtext.UnicodeFonts
tuple[FT2Font, int, bool] _get_glyph (self, str fontname, str font_class, str sym)
Protected Member Functions inherited from matplotlib._mathtext.TruetypeFonts
FT2Font _get_font (self, str|int font)
float _get_offset (self, FT2Font font, Glyph glyph, float fontsize, float dpi)
FontInfo _get_info (self, str fontname, str font_class, str sym, float fontsize, float dpi)
Static Protected Attributes
dict _fontmap
bool _sans = False
Static Protected Attributes inherited from matplotlib._mathtext.UnicodeFonts
dict _cmr10_substitutions
_slanted_symbols = set(r"\int \oint".split())
Additional Inherited Members
Public Attributes inherited from matplotlib._mathtext.TruetypeFonts
dict fontmap = {}
Public Attributes inherited from matplotlib._mathtext.Fonts
default_font_prop = default_font_prop
load_glyph_flags = load_glyph_flags
Protected Attributes inherited from matplotlib._mathtext.UnicodeFonts
tuple _fallback_font
Protected Attributes inherited from matplotlib._mathtext.TruetypeFonts
dict _fonts = {}
Detailed Description
A font handling class for the STIX fonts.
In addition to what UnicodeFonts provides, this class:
- supports "virtual fonts" which are complete alpha numeric
  character sets with different font styles at special Unicode
  code points, such as "Blackboard".
- handles sized alternative characters for the STIXSizeX fonts.
Definition at line 749 of file _mathtext.py.
Constructor & Destructor Documentation
__init__()
matplotlib._mathtext.StixFonts.__init__ (self, FontProperties default_font_prop, LoadFlags load_glyph_flags)
Definition at line 779 of file _mathtext.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_map_virtual_font()
tuple[str, int] matplotlib._mathtext.StixFonts._map_virtual_font (self, str fontname, str font_class, int uniindex) protected
Reimplemented from matplotlib._mathtext.UnicodeFonts.
Definition at line 786 of file _mathtext.py.
get_sized_alternatives_for_symbol()
list[tuple[str, str]] | list[tuple[int, str]] matplotlib._mathtext.StixFonts.get_sized_alternatives_for_symbol (self, str fontname, str sym)
Override if your font provides multiple sizes of the same
symbol.  Should return a list of symbols matching *sym* in
various sizes.  The expression renderer will select the most
appropriate size for a given situation from this list.
Reimplemented from matplotlib._mathtext.UnicodeFonts.
Definition at line 841 of file _mathtext.py.
References matplotlib._mathtext.Fonts._get_font(), and matplotlib._mathtext.get_unicode_index().
Member Data Documentation
_fontmap
dict matplotlib._mathtext.StixFonts._fontmap static protected
Initial value:
=  {
        'rm': 'STIXGeneral',
        'it': 'STIXGeneral:italic',
        'bf': 'STIXGeneral:weight=bold',
        'bfit': 'STIXGeneral:italic:bold',
        'nonunirm': 'STIXNonUnicode',
        'nonuniit': 'STIXNonUnicode:italic',
        'nonunibf': 'STIXNonUnicode:weight=bold',
        0: 'STIXGeneral',
        1: 'STIXSizeOneSym',
        2: 'STIXSizeTwoSym',
        3: 'STIXSizeThreeSym',
        4: 'STIXSizeFourSym',
        5: 'STIXSizeFiveSym',
    }
Definition at line 761 of file _mathtext.py.
_sans
bool matplotlib._mathtext.StixFonts._sans = False static protected
Definition at line 777 of file _mathtext.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/_mathtext.py