Code Cloning Analysis: pip._vendor.distlib.util.CSVWriter Class Reference
pip._vendor.distlib.util.CSVWriter Class Reference
Public Member Functions
__init__ (self, fn, **kwargs)
writerow (self, row)
Public Attributes
stream = _csv_open(fn, 'w')
writer = csv.writer(self.stream, **self.defaults)
Detailed Description
Definition at line 1683 of file util.py.
Constructor & Destructor Documentation
__init__()
pip._vendor.distlib.util.CSVWriter.__init__ (self, fn, ** kwargs)
Definition at line 1685 of file util.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
writerow()
pip._vendor.distlib.util.CSVWriter.writerow (self, row)
Definition at line 1689 of file util.py.
Member Data Documentation
stream
pip._vendor.distlib.util.CSVWriter.stream = _csv_open(fn, 'w')
Definition at line 1686 of file util.py.
Referenced by pip._vendor.urllib3.response.HTTPResponse.geturl(), pip._vendor.requests.sessions.Session.merge_environment_settings(), and pip._vendor.requests.sessions.Session.send().
writer
pip._vendor.distlib.util.CSVWriter.writer = csv.writer(self.stream, **self.defaults)
Definition at line 1687 of file util.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pip/_vendor/distlib/util.py