Code Cloning Analysis: pandas._testing Namespace Reference
pandas._testing Namespace Reference
Namespaces
namespace _hypothesis
namespace compat
Classes
class SubclassedDataFrame
class SubclassedSeries
Functions
box_expected (expected, box_cls, bool transpose=True)
to_array (obj)
str convert_rows_list_to_csv_str (list[str] rows_list)
ContextManager external_error_raised (type[Exception] expected_exception)
get_cython_table_params (ndframe, func_names_and_expected)
Callable get_op_from_name (str op_name)
getitem (x)
setitem (x)
loc (x)
iloc (x)
at (x)
iat (x)
get_finest_unit (str left, str right)
bool shares_memory (left, right)
Variables
list UNSIGNED_INT_NUMPY_DTYPES = ["uint8", "uint16", "uint32", "uint64"]
list UNSIGNED_INT_EA_DTYPES = ["UInt8", "UInt16", "UInt32", "UInt64"]
list SIGNED_INT_NUMPY_DTYPES = [int, "int8", "int16", "int32", "int64"]
list SIGNED_INT_EA_DTYPES = ["Int8", "Int16", "Int32", "Int64"]
list ALL_INT_NUMPY_DTYPES = UNSIGNED_INT_NUMPY_DTYPES + SIGNED_INT_NUMPY_DTYPES
list ALL_INT_EA_DTYPES = UNSIGNED_INT_EA_DTYPES + SIGNED_INT_EA_DTYPES
list ALL_INT_DTYPES = [*ALL_INT_NUMPY_DTYPES, *ALL_INT_EA_DTYPES]
list FLOAT_NUMPY_DTYPES = [float, "float32", "float64"]
list FLOAT_EA_DTYPES = ["Float32", "Float64"]
list ALL_FLOAT_DTYPES = [*FLOAT_NUMPY_DTYPES, *FLOAT_EA_DTYPES]
list COMPLEX_DTYPES = [complex, "complex64", "complex128"]
list STRING_DTYPES = ["U"]
list COMPLEX_FLOAT_DTYPES = [*COMPLEX_DTYPES, *FLOAT_NUMPY_DTYPES]
list DATETIME64_DTYPES = ["datetime64[ns]", "M8[ns]"]
list TIMEDELTA64_DTYPES = ["timedelta64[ns]", "m8[ns]"]
list BOOL_DTYPES = [bool, "bool"]
list BYTES_DTYPES = [bytes, "bytes"]
list OBJECT_DTYPES = [object, "object"]
list ALL_REAL_NUMPY_DTYPES = FLOAT_NUMPY_DTYPES + ALL_INT_NUMPY_DTYPES
list ALL_REAL_EXTENSION_DTYPES = FLOAT_EA_DTYPES + ALL_INT_EA_DTYPES
list ALL_REAL_DTYPES = [*ALL_REAL_NUMPY_DTYPES, *ALL_REAL_EXTENSION_DTYPES]
list ALL_NUMERIC_DTYPES = [*ALL_REAL_DTYPES, *COMPLEX_DTYPES]
tuple ALL_NUMPY_DTYPES
list NARROW_NP_DTYPES
list PYTHON_DATA_TYPES
dict ENDIAN = {"little": "<", "big": ">"}[byteorder]
list NULL_OBJECTS = [None, np.nan, pd.NaT, float("nan"), pd.NA, Decimal("NaN")]
list NP_NAT_OBJECTS
list UNSIGNED_INT_PYARROW_DTYPES = [pa.uint8(), pa.uint16(), pa.uint32(), pa.uint64()]
list SIGNED_INT_PYARROW_DTYPES = [pa.int8(), pa.int16(), pa.int32(), pa.int64()]
list ALL_INT_PYARROW_DTYPES = UNSIGNED_INT_PYARROW_DTYPES + SIGNED_INT_PYARROW_DTYPES
list ALL_INT_PYARROW_DTYPES_STR_REPR
list FLOAT_PYARROW_DTYPES = [pa.float32(), pa.float64()]
list FLOAT_PYARROW_DTYPES_STR_REPR
list DECIMAL_PYARROW_DTYPES = [pa.decimal128(7, 3)]
list STRING_PYARROW_DTYPES = [pa.string()]
list BINARY_PYARROW_DTYPES = [pa.binary()]
list TIME_PYARROW_DTYPES
list DATE_PYARROW_DTYPES = [pa.date32(), pa.date64()]
list DATETIME_PYARROW_DTYPES
list TIMEDELTA_PYARROW_DTYPES = [pa.duration(unit) for unit in ["s", "ms", "us", "ns"]]
list BOOL_PYARROW_DTYPES = [pa.bool_()]
tuple ALL_PYARROW_DTYPES
tuple ALL_REAL_PYARROW_DTYPES_STR_REPR
tuple ALL_REAL_NULLABLE_DTYPES
list arithmetic_dunder_methods
list comparison_dunder_methods = ["__eq__", "__ne__", "__le__", "__lt__", "__ge__", "__gt__"]
cython_table = pd.core.common._cython_table.items()
list _UNITS = ["s", "ms", "us", "ns"]
list __all__
Function Documentation
at()
pandas._testing.at (x)
Definition at line 481 of file __init__.py.
box_expected()
pandas._testing.box_expected (expected, box_cls, bool transpose = True)
Helper function to wrap the expected output of a test in a given box_class.
Parameters
----------
expected : np.ndarray, Index, Series
box_cls : {Index, Series, DataFrame}
Returns
-------
subclass of box_cls
Definition at line 277 of file __init__.py.
References to_array().
convert_rows_list_to_csv_str()
str pandas._testing.convert_rows_list_to_csv_str (list[str] rows_list)
Convert list of CSV rows to single CSV-formatted string for current OS.
This method is used for creating expected value of to_csv() method.
Parameters
----------
rows_list : List[str]
    Each element represents the row of csv.
Returns
-------
str
    Expected output of to_csv() in current OS.
Definition at line 366 of file __init__.py.
external_error_raised()
ContextManager pandas._testing.external_error_raised (type[Exception] expected_exception)
Helper function to mark pytest.raises that have an external error message.
Parameters
----------
expected_exception : Exception
    Expected error to raise.
Returns
-------
Callable
    Regular `pytest.raises` function with `match` equal to `None`.
Definition at line 386 of file __init__.py.
get_cython_table_params()
pandas._testing.get_cython_table_params (ndframe, func_names_and_expected)
Combine frame, functions from com._cython_table
keys and expected result.
Parameters
----------
ndframe : DataFrame or Series
func_names_and_expected : Sequence of two items
    The first item is a name of a NDFrame method ('sum', 'prod') etc.
    The second item is the expected return value.
Returns
-------
list
    List of three items (DataFrame, function, expected result)
Definition at line 408 of file __init__.py.
get_finest_unit()
pandas._testing.get_finest_unit (str left, str right)
Find the higher of two datetime64 units.
Definition at line 494 of file __init__.py.
get_op_from_name()
Callable pandas._testing.get_op_from_name (str op_name)
The operator function for a given op name.
Parameters
----------
op_name : str
    The op name, in form of "add" or "__add__".
Returns
-------
function
    A function performing the operation.
Definition at line 436 of file __init__.py.
getitem()
pandas._testing.getitem (x)
Definition at line 465 of file __init__.py.
iat()
pandas._testing.iat (x)
Definition at line 485 of file __init__.py.
iloc()
pandas._testing.iloc (x)
Definition at line 477 of file __init__.py.
loc()
pandas._testing.loc (x)
Definition at line 473 of file __init__.py.
setitem()
pandas._testing.setitem (x)
Definition at line 469 of file __init__.py.
shares_memory()
bool pandas._testing.shares_memory (left, right)
Pandas-compat for np.shares_memory.
Definition at line 503 of file __init__.py.
References shares_memory().
Referenced by shares_memory().
to_array()
pandas._testing.to_array (obj)
Similar to pd.array, but does not cast numpy dtypes to nullable dtypes.
Definition at line 324 of file __init__.py.
Referenced by box_expected().
Variable Documentation
__all__
list pandas._testing.__all__ private
Definition at line 556 of file __init__.py.
_UNITS
list pandas._testing._UNITS = ["s", "ms", "us", "ns"] protected
Definition at line 491 of file __init__.py.
ALL_FLOAT_DTYPES
list pandas._testing.ALL_FLOAT_DTYPES = [*FLOAT_NUMPY_DTYPES, *FLOAT_EA_DTYPES]
Definition at line 107 of file __init__.py.
ALL_INT_DTYPES
list pandas._testing.ALL_INT_DTYPES = [*ALL_INT_NUMPY_DTYPES, *ALL_INT_EA_DTYPES]
Definition at line 103 of file __init__.py.
ALL_INT_EA_DTYPES
list pandas._testing.ALL_INT_EA_DTYPES = UNSIGNED_INT_EA_DTYPES + SIGNED_INT_EA_DTYPES
Definition at line 102 of file __init__.py.
ALL_INT_NUMPY_DTYPES
list pandas._testing.ALL_INT_NUMPY_DTYPES = UNSIGNED_INT_NUMPY_DTYPES + SIGNED_INT_NUMPY_DTYPES
Definition at line 101 of file __init__.py.
ALL_INT_PYARROW_DTYPES
list pandas._testing.ALL_INT_PYARROW_DTYPES = UNSIGNED_INT_PYARROW_DTYPES + SIGNED_INT_PYARROW_DTYPES
Definition at line 195 of file __init__.py.
ALL_INT_PYARROW_DTYPES_STR_REPR
list pandas._testing.ALL_INT_PYARROW_DTYPES_STR_REPR
Initial value:
=  [
        str(ArrowDtype(typ)) for typ in ALL_INT_PYARROW_DTYPES
    ]
Definition at line 196 of file __init__.py.
ALL_NUMERIC_DTYPES
list pandas._testing.ALL_NUMERIC_DTYPES = [*ALL_REAL_DTYPES, *COMPLEX_DTYPES]
Definition at line 126 of file __init__.py.
ALL_NUMPY_DTYPES
tuple pandas._testing.ALL_NUMPY_DTYPES
Initial value:
=  (
    ALL_REAL_NUMPY_DTYPES
    + COMPLEX_DTYPES
    + STRING_DTYPES
    + DATETIME64_DTYPES
    + TIMEDELTA64_DTYPES
    + BOOL_DTYPES
    + OBJECT_DTYPES
    + BYTES_DTYPES
)
Definition at line 128 of file __init__.py.
ALL_PYARROW_DTYPES
list pandas._testing.ALL_PYARROW_DTYPES
Initial value:
=  (
        ALL_INT_PYARROW_DTYPES
        + FLOAT_PYARROW_DTYPES
        + DECIMAL_PYARROW_DTYPES
        + STRING_PYARROW_DTYPES
        + BINARY_PYARROW_DTYPES
        + TIME_PYARROW_DTYPES
        + DATE_PYARROW_DTYPES
        + DATETIME_PYARROW_DTYPES
        + TIMEDELTA_PYARROW_DTYPES
        + BOOL_PYARROW_DTYPES
    )
Definition at line 228 of file __init__.py.
ALL_REAL_DTYPES
list pandas._testing.ALL_REAL_DTYPES = [*ALL_REAL_NUMPY_DTYPES, *ALL_REAL_EXTENSION_DTYPES]
Definition at line 125 of file __init__.py.
ALL_REAL_EXTENSION_DTYPES
list pandas._testing.ALL_REAL_EXTENSION_DTYPES = FLOAT_EA_DTYPES + ALL_INT_EA_DTYPES
Definition at line 124 of file __init__.py.
ALL_REAL_NULLABLE_DTYPES
tuple pandas._testing.ALL_REAL_NULLABLE_DTYPES
Initial value:
=  (
    FLOAT_NUMPY_DTYPES + ALL_REAL_EXTENSION_DTYPES + ALL_REAL_PYARROW_DTYPES_STR_REPR
)
Definition at line 249 of file __init__.py.
ALL_REAL_NUMPY_DTYPES
list pandas._testing.ALL_REAL_NUMPY_DTYPES = FLOAT_NUMPY_DTYPES + ALL_INT_NUMPY_DTYPES
Definition at line 123 of file __init__.py.
ALL_REAL_PYARROW_DTYPES_STR_REPR
list pandas._testing.ALL_REAL_PYARROW_DTYPES_STR_REPR
Initial value:
=  (
        ALL_INT_PYARROW_DTYPES_STR_REPR + FLOAT_PYARROW_DTYPES_STR_REPR
    )
Definition at line 240 of file __init__.py.
arithmetic_dunder_methods
list pandas._testing.arithmetic_dunder_methods
Initial value:
=  [
    "__add__",
    "__radd__",
    "__sub__",
    "__rsub__",
    "__mul__",
    "__rmul__",
    "__floordiv__",
    "__rfloordiv__",
    "__truediv__",
    "__rtruediv__",
    "__pow__",
    "__rpow__",
    "__mod__",
    "__rmod__",
]
Definition at line 253 of file __init__.py.
BINARY_PYARROW_DTYPES
list pandas._testing.BINARY_PYARROW_DTYPES = [pa.binary()]
Definition at line 208 of file __init__.py.
BOOL_DTYPES
list pandas._testing.BOOL_DTYPES = [bool, "bool"]
Definition at line 119 of file __init__.py.
BOOL_PYARROW_DTYPES
list pandas._testing.BOOL_PYARROW_DTYPES = [pa.bool_()]
Definition at line 224 of file __init__.py.
BYTES_DTYPES
list pandas._testing.BYTES_DTYPES = [bytes, "bytes"]
Definition at line 120 of file __init__.py.
comparison_dunder_methods
list pandas._testing.comparison_dunder_methods = ["__eq__", "__ne__", "__le__", "__lt__", "__ge__", "__gt__"]
Definition at line 270 of file __init__.py.
COMPLEX_DTYPES
list pandas._testing.COMPLEX_DTYPES = [complex, "complex64", "complex128"]
Definition at line 109 of file __init__.py.
COMPLEX_FLOAT_DTYPES
list pandas._testing.COMPLEX_FLOAT_DTYPES = [*COMPLEX_DTYPES, *FLOAT_NUMPY_DTYPES]
Definition at line 114 of file __init__.py.
cython_table
pandas._testing.cython_table = pd.core.common._cython_table.items()
Definition at line 405 of file __init__.py.
DATE_PYARROW_DTYPES
list pandas._testing.DATE_PYARROW_DTYPES = [pa.date32(), pa.date64()]
Definition at line 216 of file __init__.py.
DATETIME64_DTYPES
list pandas._testing.DATETIME64_DTYPES = ["datetime64[ns]", "M8[ns]"]
Definition at line 116 of file __init__.py.
DATETIME_PYARROW_DTYPES
list pandas._testing.DATETIME_PYARROW_DTYPES
Initial value:
=  [
        pa.timestamp(unit=unit, tz=tz)
        for unit in ["s", "ms", "us", "ns"]
        for tz in [None, "UTC", "US/Pacific", "US/Eastern"]
    ]
Definition at line 217 of file __init__.py.
DECIMAL_PYARROW_DTYPES
list pandas._testing.DECIMAL_PYARROW_DTYPES = [pa.decimal128(7, 3)]
Definition at line 206 of file __init__.py.
ENDIAN
dict pandas._testing.ENDIAN = {"little": "<", "big": ">"}[byteorder]
Definition at line 167 of file __init__.py.
FLOAT_EA_DTYPES
list pandas._testing.FLOAT_EA_DTYPES = ["Float32", "Float64"]
Definition at line 106 of file __init__.py.
FLOAT_NUMPY_DTYPES
list pandas._testing.FLOAT_NUMPY_DTYPES = [float, "float32", "float64"]
Definition at line 105 of file __init__.py.
FLOAT_PYARROW_DTYPES
list pandas._testing.FLOAT_PYARROW_DTYPES = [pa.float32(), pa.float64()]
Definition at line 202 of file __init__.py.
FLOAT_PYARROW_DTYPES_STR_REPR
list pandas._testing.FLOAT_PYARROW_DTYPES_STR_REPR
Initial value:
=  [
        str(ArrowDtype(typ)) for typ in FLOAT_PYARROW_DTYPES
    ]
Definition at line 203 of file __init__.py.
NARROW_NP_DTYPES
list pandas._testing.NARROW_NP_DTYPES
Initial value:
=  [
    np.float16,
    np.float32,
    np.int8,
    np.int16,
    np.int32,
    np.uint8,
    np.uint16,
    np.uint32,
]
Definition at line 139 of file __init__.py.
NP_NAT_OBJECTS
list pandas._testing.NP_NAT_OBJECTS
Initial value:
=  [
    cls("NaT", unit)
    for cls in [np.datetime64, np.timedelta64]
    for unit in [
        "Y",
        "M",
        "W",
        "D",
        "h",
        "m",
        "s",
        "ms",
        "us",
        "ns",
        "ps",
        "fs",
        "as",
    ]
]
Definition at line 170 of file __init__.py.
NULL_OBJECTS
list pandas._testing.NULL_OBJECTS = [None, np.nan, pd.NaT, float("nan"), pd.NA, Decimal("NaN")]
Definition at line 169 of file __init__.py.
OBJECT_DTYPES
list pandas._testing.OBJECT_DTYPES = [object, "object"]
Definition at line 121 of file __init__.py.
PYTHON_DATA_TYPES
list pandas._testing.PYTHON_DATA_TYPES
Initial value:
=  [
    str,
    int,
    float,
    complex,
    list,
    tuple,
    range,
    dict,
    set,
    frozenset,
    bool,
    bytes,
    bytearray,
    memoryview,
]
Definition at line 150 of file __init__.py.
SIGNED_INT_EA_DTYPES
list pandas._testing.SIGNED_INT_EA_DTYPES = ["Int8", "Int16", "Int32", "Int64"]
Definition at line 100 of file __init__.py.
SIGNED_INT_NUMPY_DTYPES
list pandas._testing.SIGNED_INT_NUMPY_DTYPES = [int, "int8", "int16", "int32", "int64"]
Definition at line 99 of file __init__.py.
SIGNED_INT_PYARROW_DTYPES
list pandas._testing.SIGNED_INT_PYARROW_DTYPES = [pa.int8(), pa.int16(), pa.int32(), pa.int64()]
Definition at line 194 of file __init__.py.
STRING_DTYPES
list pandas._testing.STRING_DTYPES = ["U"]
Definition at line 111 of file __init__.py.
STRING_PYARROW_DTYPES
list pandas._testing.STRING_PYARROW_DTYPES = [pa.string()]
Definition at line 207 of file __init__.py.
TIME_PYARROW_DTYPES
list pandas._testing.TIME_PYARROW_DTYPES
Initial value:
=  [
        pa.time32("s"),
        pa.time32("ms"),
        pa.time64("us"),
        pa.time64("ns"),
    ]
Definition at line 210 of file __init__.py.
TIMEDELTA64_DTYPES
list pandas._testing.TIMEDELTA64_DTYPES = ["timedelta64[ns]", "m8[ns]"]
Definition at line 117 of file __init__.py.
TIMEDELTA_PYARROW_DTYPES
list pandas._testing.TIMEDELTA_PYARROW_DTYPES = [pa.duration(unit) for unit in ["s", "ms", "us", "ns"]]
Definition at line 222 of file __init__.py.
UNSIGNED_INT_EA_DTYPES
list pandas._testing.UNSIGNED_INT_EA_DTYPES = ["UInt8", "UInt16", "UInt32", "UInt64"]
Definition at line 98 of file __init__.py.
UNSIGNED_INT_NUMPY_DTYPES
list pandas._testing.UNSIGNED_INT_NUMPY_DTYPES = ["uint8", "uint16", "uint32", "uint64"]
Definition at line 97 of file __init__.py.
UNSIGNED_INT_PYARROW_DTYPES
list pandas._testing.UNSIGNED_INT_PYARROW_DTYPES = [pa.uint8(), pa.uint16(), pa.uint32(), pa.uint64()]
Definition at line 193 of file __init__.py.