Code Cloning Analysis: scipy.sparse.tests.test_base._NonCanonicalCompressedMixin Class Reference
scipy.sparse.tests.test_base._NonCanonicalCompressedMixin Class Reference
Protected Member Functions
_arg1_for_noncanonical (self, M, sorted_indices=False)
_insert_explicit_zero (self, M, i, j)
Additional Inherited Members
Public Member Functions inherited from scipy.sparse.tests.test_base._NonCanonicalMixin
spcreator (self, D, sorted_indices=False, **kwargs)
test_bool (self)
test_getnnz_axis (self)
test_empty (self)
Detailed Description
Definition at line 4818 of file test_base.py.
Member Function Documentation
_arg1_for_noncanonical()
scipy.sparse.tests.test_base._NonCanonicalCompressedMixin._arg1_for_noncanonical (self, M, sorted_indices = False) protected
Return non-canonical constructor arg1 equivalent to M
Definition at line 4819 of file test_base.py.
References scipy.sparse.tests.test_base._same_sum_duplicate().
Referenced by scipy.sparse.tests.test_base._NonCanonicalMixin.spcreator().
_insert_explicit_zero()
scipy.sparse.tests.test_base._NonCanonicalCompressedMixin._insert_explicit_zero (self, M, i, j) protected
Definition at line 4829 of file test_base.py.
Referenced by scipy.sparse.tests.test_base._NonCanonicalMixin.spcreator().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/sparse/tests/test_base.py