Code Cloning Analysis: matplotlib._mathtext Namespace Reference
matplotlib._mathtext Namespace Reference
Classes
class _GlueSpec
class Accent
class AutoHeightChar
class AutoWidthChar
class BakomaFonts
class Box
class Char
class ComputerModernFontConstants
class DejaVuFonts
class DejaVuSansFontConstants
class DejaVuSansFonts
class DejaVuSerifFontConstants
class DejaVuSerifFonts
class FontConstantsBase
class FontInfo
class FontMetrics
class Fonts
class Glue
class Hbox
class HCentered
class Hlist
class Hrule
class Kern
class List
class Node
class Output
class Parser
class ParserState
class RasterParse
class Rule
class STIXFontConstants
class StixFonts
class STIXSansFontConstants
class StixSansFonts
class TruetypeFonts
class UnicodeFonts
class Vbox
class VCentered
class VectorParse
class Vlist
class Vrule
Functions
int get_unicode_index (str symbol)
FONTS.
type[FontConstantsBase] _get_font_constant_set (ParserState state)
Output ship (Box box, tuple[float, float] xy=(0, 0))
ParserElement Error (str msg)
PARSER.
ParserElement cmd (str expr, ParserElement args)
Variables
_log = logging.getLogger("matplotlib.mathtext")
float SHRINK_FACTOR = 0.7
int NUM_SIZE_LEVELS = 6
dict _font_constant_mapping
Detailed Description
Implementation details for :mod:`.mathtext`.
Function Documentation
_get_font_constant_set()
type[FontConstantsBase] matplotlib._mathtext._get_font_constant_set (ParserState state) protected
Definition at line 999 of file _mathtext.py.
cmd()
ParserElement matplotlib._mathtext.cmd (str expr, ParserElement args)
Helper to define TeX commands.
``cmd("\cmd", args)`` is equivalent to
``"\cmd" - (args | Error("Expected \cmd{arg}{...}"))`` where the names in
the error message are taken from element names in *args*.  If *expr*
already includes arguments (e.g. "\cmd{arg}{...}"), then they are stripped
when constructing the parse element, but kept (and *expr* is used as is) in
the error message.
Definition at line 1789 of file _mathtext.py.
References Error().
Error()
ParserElement matplotlib._mathtext.Error (str msg)
PARSER.
Helper class to raise parser errors.
Definition at line 1743 of file _mathtext.py.
Referenced by cmd().
get_unicode_index()
int matplotlib._mathtext.get_unicode_index (str symbol)
FONTS.
    Return the integer index (from the Unicode table) of *symbol*.
    Parameters
    ----------
    symbol : str
        A single (Unicode) character, a TeX command (e.g. r'\pi') or a Type1
        symbol name (e.g. 'phi').
Definition at line 53 of file _mathtext.py.
Referenced by matplotlib._mathtext.StixFonts.get_sized_alternatives_for_symbol().
ship()
Output matplotlib._mathtext.ship (Box box, tuple[float, float] xy = (0, 0))
Ship out *box* at offset *xy*, converting it to an `Output`.
Since boxes can be inside of boxes inside of boxes, the main work of `ship`
is done by two mutually recursive routines, `hlist_out` and `vlist_out`,
which traverse the `Hlist` nodes and `Vlist` nodes inside of horizontal
and vertical boxes.  The global variables used in TeX to store state as it
processes have become local variables here.
Definition at line 1592 of file _mathtext.py.
Variable Documentation
_font_constant_mapping
dict matplotlib._mathtext._font_constant_mapping protected
Initial value:
=  {
    'DejaVu Sans': DejaVuSansFontConstants,
    'DejaVu Sans Mono': DejaVuSansFontConstants,
    'DejaVu Serif': DejaVuSerifFontConstants,
    'cmb10': ComputerModernFontConstants,
    'cmex10': ComputerModernFontConstants,
    'cmmi10': ComputerModernFontConstants,
    'cmr10': ComputerModernFontConstants,
    'cmss10': ComputerModernFontConstants,
    'cmsy10': ComputerModernFontConstants,
    'cmtt10': ComputerModernFontConstants,
    'STIXGeneral': STIXFontConstants,
    'STIXNonUnicode': STIXFontConstants,
    'STIXSizeFiveSym': STIXFontConstants,
    'STIXSizeFourSym': STIXFontConstants,
    'STIXSizeThreeSym': STIXFontConstants,
    'STIXSizeTwoSym': STIXFontConstants,
    'STIXSizeOneSym': STIXFontConstants,
    # Map the fonts we used to ship, just for good measure
    'Bitstream Vera Sans': DejaVuSansFontConstants,
    'Bitstream Vera': DejaVuSansFontConstants,
    }
Definition at line 975 of file _mathtext.py.
_log
matplotlib._mathtext._log = logging.getLogger("matplotlib.mathtext") protected
Definition at line 46 of file _mathtext.py.
NUM_SIZE_LEVELS
int matplotlib._mathtext.NUM_SIZE_LEVELS = 6
Definition at line 900 of file _mathtext.py.
SHRINK_FACTOR
float matplotlib._mathtext.SHRINK_FACTOR = 0.7
Definition at line 897 of file _mathtext.py.