Code Cloning Analysis: fontTools.ttLib.tables.E_B_D_T_.ebdt_bitmap_format_7 Class Reference
fontTools.ttLib.tables.E_B_D_T_.ebdt_bitmap_format_7 Class Reference
Public Member Functions
decompile (self)
compile (self, ttFont)
Public Member Functions inherited from fontTools.ttLib.tables.E_B_D_T_.BitAlignedBitmapMixin
getRow (self, row, bitDepth=1, metrics=None, reverseBytes=False)
setRows (self, dataRows, bitDepth=1, metrics=None, reverseBytes=False)
Public Member Functions inherited from fontTools.ttLib.tables.E_B_D_T_.BitmapGlyph
__init__ (self, data, ttFont)
__getattr__ (self, attr)
ensureDecompiled (self, recurse=False)
getFormat (self)
toXML (self, strikeIndex, glyphName, writer, ttFont)
fromXML (self, name, attrs, content, ttFont)
writeMetrics (self, writer, ttFont)
readMetrics (self, name, attrs, content, ttFont)
writeData (self, strikeIndex, glyphName, writer, ttFont)
readData (self, name, attrs, content, ttFont)
Public Attributes
metrics = BigGlyphMetrics()
Public Attributes inherited from fontTools.ttLib.tables.E_B_D_T_.BitAlignedBitmapMixin
imageData
Public Attributes inherited from fontTools.ttLib.tables.E_B_D_T_.BitmapGlyph
data = data
ttFont = ttFont
Additional Inherited Members
Static Public Attributes inherited from fontTools.ttLib.tables.E_B_D_T_.BitmapGlyph
str fileExtension = ".bin"
dict xmlDataFunctions
Protected Member Functions inherited from fontTools.ttLib.tables.E_B_D_T_.BitAlignedBitmapMixin
_getBitRange (self, row, bitDepth, metrics)
Detailed Description
Definition at line 726 of file E_B_D_T_.py.
Member Function Documentation
compile()
fontTools.ttLib.tables.E_B_D_T_.ebdt_bitmap_format_7.compile (self, ttFont)
Definition at line 734 of file E_B_D_T_.py.
Referenced by fontTools.ttLib.tables.TupleVariation.TupleVariation.getCoordWidth(), and PIL.FontFile.FontFile.save().
decompile()
fontTools.ttLib.tables.E_B_D_T_.ebdt_bitmap_format_7.decompile (self)
Definition at line 729 of file E_B_D_T_.py.
Referenced by fontTools.ttLib.tables._c_m_a_p.CmapSubtable.newSubtable().
Member Data Documentation
metrics
fontTools.ttLib.tables.E_B_D_T_.ebdt_bitmap_format_7.metrics = BigGlyphMetrics()
Definition at line 730 of file E_B_D_T_.py.
Referenced by PIL.FontFile.FontFile.compile(), and PIL.FontFile.FontFile.save().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ttLib/tables/E_B_D_T_.py