Code Cloning Analysis: joblib.externals.loky.cloudpickle_wrapper.CloudpickledObjectWrapper Class Reference
joblib.externals.loky.cloudpickle_wrapper.CloudpickledObjectWrapper Class Reference
Public Member Functions
__init__ (self, obj, keep_wrapper=False)
__reduce__ (self)
__getattr__ (self, attr)
Protected Attributes
_obj = obj
_keep_wrapper = keep_wrapper
Detailed Description
Definition at line 9 of file cloudpickle_wrapper.py.
Constructor & Destructor Documentation
__init__()
joblib.externals.loky.cloudpickle_wrapper.CloudpickledObjectWrapper.__init__ (self, obj, keep_wrapper = False)
Definition at line 10 of file cloudpickle_wrapper.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__getattr__()
joblib.externals.loky.cloudpickle_wrapper.CloudpickledObjectWrapper.__getattr__ (self, attr)
Definition at line 21 of file cloudpickle_wrapper.py.
__reduce__()
joblib.externals.loky.cloudpickle_wrapper.CloudpickledObjectWrapper.__reduce__ (self)
Definition at line 14 of file cloudpickle_wrapper.py.
Member Data Documentation
_keep_wrapper
joblib.externals.loky.cloudpickle_wrapper.CloudpickledObjectWrapper._keep_wrapper = keep_wrapper protected
Definition at line 12 of file cloudpickle_wrapper.py.
_obj
joblib.externals.loky.cloudpickle_wrapper.CloudpickledObjectWrapper._obj = obj protected
Definition at line 11 of file cloudpickle_wrapper.py.
Referenced by scipy._lib._docscrape.NumpyDocString._parse_summary(), and pandas.core.flags.Flags.allows_duplicate_labels().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/joblib/externals/loky/cloudpickle_wrapper.py