Code Cloning Analysis: fontTools.cffLib.FontDict Class Reference
fontTools.cffLib.FontDict Class Reference
Public Member Functions
__init__ (self, strings=None, file=None, offset=None, GlobalSubrs=None, isCFF2=None, vstore=None)
setCFF2 (self, isCFF2)
Public Member Functions inherited from fontTools.cffLib.BaseDict
__init__ (self, strings=None, file=None, offset=None, isCFF2=None)
decompile (self, data)
postDecompile (self)
getCompiler (self, strings, parent, isCFF2=None)
__getattr__ (self, name)
toXML (self, xmlWriter)
fromXML (self, name, attrs, content)
Public Attributes
vstore = vstore
Public Attributes inherited from fontTools.cffLib.BaseDict
dict rawDict = {}
list skipNames = []
strings = strings
file = file
offset = offset
order
Static Public Attributes
dict defaults = {}
converters = buildConverters(topDictOperators)
compilerClass = FontDictCompiler
list orderCFF = ["FontName", "FontMatrix", "Weight", "Private"]
list orderCFF2 = ["Private"]
decompilerClass = TopDictDecompiler
Additional Inherited Members
Protected Attributes inherited from fontTools.cffLib.BaseDict
_isCFF2 = isCFF2
Detailed Description
Definition at line 2652 of file __init__.py.
Constructor & Destructor Documentation
__init__()
fontTools.cffLib.FontDict.__init__ (self, strings = None, file = None, offset = None, GlobalSubrs = None, isCFF2 = None, vstore = None)
Definition at line 2687 of file __init__.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
setCFF2()
fontTools.cffLib.FontDict.setCFF2 (self, isCFF2)
Definition at line 2700 of file __init__.py.
Member Data Documentation
compilerClass
fontTools.cffLib.FontDict.compilerClass = FontDictCompiler static
Definition at line 2682 of file __init__.py.
converters
fontTools.cffLib.FontDict.converters = buildConverters(topDictOperators) static
Definition at line 2681 of file __init__.py.
Referenced by pandas.io.parsers.python_parser.PythonParser.__init__(), and pandas.io.parsers.base_parser.ParserBase._clean_mapping().
decompilerClass
fontTools.cffLib.FontDict.decompilerClass = TopDictDecompiler static
Definition at line 2685 of file __init__.py.
defaults
dict fontTools.cffLib.FontDict.defaults = {} static
Definition at line 2680 of file __init__.py.
Referenced by pip._internal.cli.parser.ConfigOptionParser._update_defaults(), and pip._internal.cli.parser.ConfigOptionParser.get_default_values().
orderCFF
list fontTools.cffLib.FontDict.orderCFF = ["FontName", "FontMatrix", "Weight", "Private"] static
Definition at line 2683 of file __init__.py.
orderCFF2
list fontTools.cffLib.FontDict.orderCFF2 = ["Private"] static
Definition at line 2684 of file __init__.py.
vstore
fontTools.cffLib.FontDict.vstore = vstore
Definition at line 2697 of file __init__.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/cffLib/__init__.py