Code Cloning Analysis: numpy.core.tests.test_umath Namespace Reference
numpy.core.tests.test_umath Namespace Reference
Classes
class _FilterInvalids
class TestAbsoluteNegative
class TestAdd
class TestArctan2SpecialValues
class TestAttributes
class TestAVXFloat32Transcendental
class TestAVXUfuncs
class TestBitwiseUFuncs
class TestBool
class TestCbrt
class TestChoose
class TestComparisons
class TestComplexFunctions
class TestConstants
class TestDegrees
class TestDivision
class TestDivisionIntegerOverflowsAndDivideByZero
class TestExp
class TestExp2
class TestExpm1
class TestFloat_power
class TestFloatingPoint
class TestFmax
class TestFmin
class TestFPClass
class TestFRExp
class TestFrompyfunc
class TestHeavside
class TestHypot
class TestHypotSpecialValues
class TestInt
class TestLDExp
class TestLdexp
class TestLog
class TestLog1p
class TestLog2
class TestLogAddExp
class TestLogAddExp2
class TestMaximum
class TestMinimum
class TestMinMax
class TestOut
class TestPositive
class TestPower
class TestRadians
class TestRationalFunctions
class TestRemainder
class TestRoundingFunctions
class TestSign
class TestSpecialFloats
class TestSpecialMethods
class TestSubclass
Functions
interesting_binop_operands (val1, val2, dtype)
on_powerpc ()
bad_arcsinh ()
floor_divide_and_remainder (x, y)
_signs (dt)
assert_hypot_isnan (x, y)
assert_hypot_isinf (x, y)
assert_arctan2_isnan (x, y)
assert_arctan2_ispinf (x, y)
assert_arctan2_isninf (x, y)
assert_arctan2_ispzero (x, y)
assert_arctan2_isnzero (x, y)
_check_branch_cut (f, x0, dx, re_sign=1, im_sign=-1, sig_zero_ok=False, dtype=complex)
test_copysign ()
_test_nextafter (t)
test_nextafter ()
test_nextafterf ()
test_nextafterl ()
test_nextafter_0 ()
_test_spacing (t)
test_spacing ()
test_spacingf ()
test_spacingl ()
test_spacing_gfortran ()
test_nextafter_vs_spacing ()
test_pos_nan ()
test_reduceat ()
test_reduceat_empty ()
test_complex_nan_comparisons ()
test_rint_big_int ()
test_memoverlap_accumulate (ftype)
test_memoverlap_accumulate_cmp (ufunc, dtype)
test_memoverlap_accumulate_symmetric (ufunc, dtype)
test_signaling_nan_exceptions ()
test_outer_subclass_preserve (arr)
test_outer_bad_subclass ()
test_outer_exceeds_maxdims ()
test_bad_legacy_ufunc_silent_errors ()
test_bad_legacy_gufunc_silent_errors (x1)
Variables
list UFUNCS
list UFUNCS_UNARY
list UFUNCS_UNARY_FP
list UFUNCS_BINARY
list UFUNCS_BINARY_ACC
dict avx_ufuncs
int ndim = 3:
shape = self.shape + (1,)
Function Documentation
_check_branch_cut()
numpy.core.tests.test_umath._check_branch_cut (f, x0, dx, re_sign = 1, im_sign = -1, sig_zero_ok = False, dtype = complex) protected
Check for a branch cut in a function.
Assert that `x0` lies on a branch cut of function `f` and `f` is
continuous from the direction `dx`.
Parameters
----------
f : func
    Function to check
x0 : array-like
    Point on branch cut
dx : array-like
    Direction to check continuity in
re_sign, im_sign : {1, -1}
    Change of sign of the real or imaginary part expected
sig_zero_ok : bool
    Whether to check if the branch cut respects signed zero (if applicable)
dtype : dtype
    Dtype to check (should be complex)
Definition at line 4365 of file test_umath.py.
_signs()
numpy.core.tests.test_umath._signs (dt) protected
Definition at line 699 of file test_umath.py.
_test_nextafter()
numpy.core.tests.test_umath._test_nextafter (t) protected
Definition at line 4434 of file test_umath.py.
_test_spacing()
numpy.core.tests.test_umath._test_spacing (t) protected
Definition at line 4473 of file test_umath.py.
assert_arctan2_isnan()
numpy.core.tests.test_umath.assert_arctan2_isnan (x, y)
Definition at line 2144 of file test_umath.py.
assert_arctan2_isninf()
numpy.core.tests.test_umath.assert_arctan2_isninf (x, y)
Definition at line 2152 of file test_umath.py.
assert_arctan2_isnzero()
numpy.core.tests.test_umath.assert_arctan2_isnzero (x, y)
Definition at line 2160 of file test_umath.py.
assert_arctan2_ispinf()
numpy.core.tests.test_umath.assert_arctan2_ispinf (x, y)
Definition at line 2148 of file test_umath.py.
assert_arctan2_ispzero()
numpy.core.tests.test_umath.assert_arctan2_ispzero (x, y)
Definition at line 2156 of file test_umath.py.
assert_hypot_isinf()
numpy.core.tests.test_umath.assert_hypot_isinf (x, y)
Definition at line 2121 of file test_umath.py.
assert_hypot_isnan()
numpy.core.tests.test_umath.assert_hypot_isnan (x, y)
Definition at line 2115 of file test_umath.py.
bad_arcsinh()
numpy.core.tests.test_umath.bad_arcsinh ()
The blocklisted trig functions are not accurate on aarch64/PPC for
complex256. Rather than dig through the actual problem skip the
test. This should be fixed when we can move past glibc2.17
which is the version in manylinux2014
Definition at line 104 of file test_umath.py.
References on_powerpc().
Referenced by numpy.core.tests.test_umath.TestComplexFunctions.test_loss_of_precision().
floor_divide_and_remainder()
numpy.core.tests.test_umath.floor_divide_and_remainder (x, y)
Definition at line 695 of file test_umath.py.
interesting_binop_operands()
numpy.core.tests.test_umath.interesting_binop_operands (val1, val2, dtype)
Helper to create "interesting" operands to cover common code paths:
* scalar inputs
* only first "values" is an array (e.g. scalar division fast-paths)
* Longer array (SIMD) placing the value of interest at different positions
* Oddly strided arrays which may not be SIMD compatible
It does not attempt to cover unaligned access or mixed dtypes.
These are normally handled by the casting/buffering machinery.
This is not a fixture (currently), since I believe a fixture normally
only yields once?
Definition at line 42 of file test_umath.py.
on_powerpc()
numpy.core.tests.test_umath.on_powerpc ()
 True if we are running on a Power PC platform.
Definition at line 98 of file test_umath.py.
Referenced by bad_arcsinh().
test_bad_legacy_gufunc_silent_errors()
numpy.core.tests.test_umath.test_bad_legacy_gufunc_silent_errors (x1)
Definition at line 4739 of file test_umath.py.
test_bad_legacy_ufunc_silent_errors()
numpy.core.tests.test_umath.test_bad_legacy_ufunc_silent_errors ()
Definition at line 4708 of file test_umath.py.
test_complex_nan_comparisons()
numpy.core.tests.test_umath.test_complex_nan_comparisons ()
Definition at line 4585 of file test_umath.py.
test_copysign()
numpy.core.tests.test_umath.test_copysign ()
Definition at line 4426 of file test_umath.py.
test_memoverlap_accumulate()
numpy.core.tests.test_umath.test_memoverlap_accumulate (ftype)
Definition at line 4617 of file test_umath.py.
test_memoverlap_accumulate_cmp()
numpy.core.tests.test_umath.test_memoverlap_accumulate_cmp (ufunc, dtype)
Definition at line 4631 of file test_umath.py.
test_memoverlap_accumulate_symmetric()
numpy.core.tests.test_umath.test_memoverlap_accumulate_symmetric (ufunc, dtype)
Definition at line 4647 of file test_umath.py.
test_nextafter()
numpy.core.tests.test_umath.test_nextafter ()
Definition at line 4445 of file test_umath.py.
test_nextafter_0()
numpy.core.tests.test_umath.test_nextafter_0 ()
Definition at line 4461 of file test_umath.py.
test_nextafter_vs_spacing()
numpy.core.tests.test_umath.test_nextafter_vs_spacing ()
Definition at line 4529 of file test_umath.py.
test_nextafterf()
numpy.core.tests.test_umath.test_nextafterf ()
Definition at line 4449 of file test_umath.py.
test_nextafterl()
numpy.core.tests.test_umath.test_nextafterl ()
Definition at line 4457 of file test_umath.py.
test_outer_bad_subclass()
numpy.core.tests.test_umath.test_outer_bad_subclass ()
Definition at line 4673 of file test_umath.py.
test_outer_exceeds_maxdims()
numpy.core.tests.test_umath.test_outer_exceeds_maxdims ()
Definition at line 4703 of file test_umath.py.
test_outer_subclass_preserve()
numpy.core.tests.test_umath.test_outer_subclass_preserve (arr)
Definition at line 4667 of file test_umath.py.
test_pos_nan()
numpy.core.tests.test_umath.test_pos_nan ()
Check np.nan is a positive nan.
Definition at line 4537 of file test_umath.py.
test_reduceat()
numpy.core.tests.test_umath.test_reduceat ()
Test bug in reduceat when structured arrays are not copied.
Definition at line 4541 of file test_umath.py.
test_reduceat_empty()
numpy.core.tests.test_umath.test_reduceat_empty ()
Reduceat should work with empty arrays
Definition at line 4569 of file test_umath.py.
References numpy.core.fromnumeric.reshape().
test_rint_big_int()
numpy.core.tests.test_umath.test_rint_big_int ()
Definition at line 4606 of file test_umath.py.
test_signaling_nan_exceptions()
numpy.core.tests.test_umath.test_signaling_nan_exceptions ()
Definition at line 4657 of file test_umath.py.
test_spacing()
numpy.core.tests.test_umath.test_spacing ()
Definition at line 4485 of file test_umath.py.
test_spacing_gfortran()
numpy.core.tests.test_umath.test_spacing_gfortran ()
Definition at line 4499 of file test_umath.py.
test_spacingf()
numpy.core.tests.test_umath.test_spacingf ()
Definition at line 4488 of file test_umath.py.
test_spacingl()
numpy.core.tests.test_umath.test_spacingl ()
Definition at line 4496 of file test_umath.py.
Variable Documentation
avx_ufuncs
dict numpy.core.tests.test_umath.avx_ufuncs
Initial value:
=  {'sqrt'        :[1,  0.,   100.],
              'absolute'    :[0, -100., 100.],
              'reciprocal'  :[1,  1.,   100.],
              'square'      :[1, -100., 100.],
              'rint'        :[0, -100., 100.],
              'floor'       :[0, -100., 100.],
              'ceil'        :[0, -100., 100.],
              'trunc'       :[0, -100., 100.]}
Definition at line 1935 of file test_umath.py.
ndim
int numpy.core.tests.test_umath.ndim = 3:
Definition at line 4677 of file test_umath.py.
shape
numpy.core.tests.test_umath.shape = self.shape + (1,)
Definition at line 4678 of file test_umath.py.
UFUNCS
list numpy.core.tests.test_umath.UFUNCS
Initial value:
=  [obj for obj in np.core.umath.__dict__.values()
         if isinstance(obj, np.ufunc)]
Definition at line 25 of file test_umath.py.
UFUNCS_BINARY
list numpy.core.tests.test_umath.UFUNCS_BINARY
Initial value:
=  [
    uf for uf in UFUNCS if uf.nin == 2
]
Definition at line 35 of file test_umath.py.
UFUNCS_BINARY_ACC
list numpy.core.tests.test_umath.UFUNCS_BINARY_ACC
Initial value:
=  [
    uf for uf in UFUNCS_BINARY if hasattr(uf, "accumulate") and uf.nout == 1
]
Definition at line 38 of file test_umath.py.
UFUNCS_UNARY
list numpy.core.tests.test_umath.UFUNCS_UNARY
Initial value:
=  [
    uf for uf in UFUNCS if uf.nin == 1
]
Definition at line 28 of file test_umath.py.
UFUNCS_UNARY_FP
list numpy.core.tests.test_umath.UFUNCS_UNARY_FP
Initial value:
=  [
    uf for uf in UFUNCS_UNARY if 'f->f' in uf.types
]
Definition at line 31 of file test_umath.py.