Code Cloning Analysis: axes_grid1.axes_size.Scaled Class Reference
axes_grid1.axes_size.Scaled Class Reference
Public Member Functions
__init__ (self, scalable_size)
get_size (self, renderer)
Public Member Functions inherited from axes_grid1.axes_size._Base
__rmul__ (self, other)
__mul__ (self, other)
__div__ (self, other)
__add__ (self, other)
__neg__ (self)
__radd__ (self, other)
__sub__ (self, other)
Protected Attributes
_scalable_size = scalable_size
Detailed Description
Simple scaled(?) size with absolute part = 0 and
relative part = *scalable_size*.
Definition at line 88 of file axes_size.py.
Constructor & Destructor Documentation
__init__()
axes_grid1.axes_size.Scaled.__init__ (self, scalable_size)
Definition at line 94 of file axes_size.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
get_size()
axes_grid1.axes_size.Scaled.get_size (self, renderer)
Return two-float tuple with relative and absolute sizes.
Reimplemented from axes_grid1.axes_size._Base.
Definition at line 97 of file axes_size.py.
References _scalable_size.
Referenced by matplotlib.text.Text.set_bbox(), matplotlib.text.Text.update_bbox_position_size(), and matplotlib.text.Annotation.update_positions().
Member Data Documentation
_scalable_size
axes_grid1.axes_size.Scaled._scalable_size = scalable_size protected
Definition at line 95 of file axes_size.py.
Referenced by get_size().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/mpl_toolkits/axes_grid1/axes_size.py