Code Cloning Analysis: scipy.interpolate._bsplines Namespace Reference
scipy.interpolate._bsplines Namespace Reference
Classes
class BSpline
Functions
_get_dtype (dtype)
_as_float_array (x, check_finite=False)
_dual_poly (j, k, t, y)
_diff_dual_poly (j, k, y, d, t)
_not_a_knot (x, k)
_augknt (x, k)
_convert_string_aliases (deriv, target_shape)
_process_deriv_spec (deriv)
_woodbury_algorithm (A, ur, ll, b, k)
_periodic_knots (x, k)
_make_interp_per_full_matr (x, y, t, k)
_make_periodic_spline (x, y, t, k, axis)
make_interp_spline (x, y, k=3, t=None, bc_type=None, axis=0, check_finite=True)
make_lsq_spline (x, y, t, k=3, w=None, axis=0, check_finite=True)
_compute_optimal_gcv_parameter (X, wE, y, w)
Smoothing spline helpers #.
_coeff_of_divided_diff (x)
make_smoothing_spline (x, y, w=None, lam=None)
Variables
list __all__
Function Documentation
_as_float_array()
scipy.interpolate._bsplines._as_float_array (x, check_finite = False) protected
Convert the input into a C contiguous float array.
NB: Upcasts half- and single-precision floats to double precision.
Definition at line 28 of file _bsplines.py.
References _get_dtype().
Referenced by scipy.interpolate._bsplines.BSpline.basis_element(), scipy.interpolate._bsplines.BSpline.design_matrix(), make_interp_spline(), and make_lsq_spline().
_augknt()
scipy.interpolate._bsplines._augknt (x, k) protected
Construct a knot vector appropriate for the order-k interpolation.
Definition at line 851 of file _bsplines.py.
Referenced by scipy.interpolate._bsplines.BSpline.from_power_basis(), and make_interp_spline().
_coeff_of_divided_diff()
scipy.interpolate._bsplines._coeff_of_divided_diff (x) protected
Returns the coefficients of the divided difference.
Parameters
----------
x : array, shape (n,)
    Array which is used for the computation of divided difference.
Returns
-------
res : array_like, shape (n,)
    Coefficients of the divided difference.
Notes
-----
Vector ``x`` should have unique elements, otherwise an error division by
zero might be raised.
No checks are performed.
Definition at line 1820 of file _bsplines.py.
Referenced by make_smoothing_spline().
_compute_optimal_gcv_parameter()
scipy.interpolate._bsplines._compute_optimal_gcv_parameter (X, wE, y, w) protected
Smoothing spline helpers #.
Returns an optimal regularization parameter from the GCV criteria [1].
Parameters
----------
X : array, shape (5, n)
    5 bands of the design matrix ``X`` stored in LAPACK banded storage.
wE : array, shape (5, n)
    5 bands of the penalty matrix :math:`W^{-1} E` stored in LAPACK banded
    storage.
y : array, shape (n,)
    Ordinates.
w : array, shape (n,)
    Vector of weights.
Returns
-------
lam : float
    An optimal from the GCV criteria point of view regularization
    parameter.
Notes
-----
No checks are performed.
References
----------
.. [1] G. Wahba, "Estimating the smoothing parameter" in Spline models
    for observational data, Philadelphia, Pennsylvania: Society for
    Industrial and Applied Mathematics, 1990, pp. 45-65.
    :doi:`10.1137/1.9781611970128`
Definition at line 1582 of file _bsplines.py.
Referenced by make_smoothing_spline().
_convert_string_aliases()
scipy.interpolate._bsplines._convert_string_aliases (deriv, target_shape) protected
Definition at line 856 of file _bsplines.py.
_diff_dual_poly()
scipy.interpolate._bsplines._diff_dual_poly (j, k, y, d, t) protected
d-th derivative of the dual polynomial $p_{j,k}(y)$
Definition at line 52 of file _bsplines.py.
References _dual_poly().
Referenced by scipy.interpolate._bsplines.BSpline.from_power_basis().
_dual_poly()
scipy.interpolate._bsplines._dual_poly (j, k, t, y) protected
Dual polynomial of the B-spline B_{j,k,t} -
polynomial which is associated with B_{j,k,t}:
$p_{j,k}(y) = (y - t_{j+1})(y - t_{j+2})...(y - t_{j+k})$
Definition at line 41 of file _bsplines.py.
Referenced by _diff_dual_poly().
_get_dtype()
scipy.interpolate._bsplines._get_dtype (dtype) protected
Return np.complex128 for complex dtypes, np.float64 otherwise.
Definition at line 20 of file _bsplines.py.
Referenced by _as_float_array(), and make_interp_spline().
_make_interp_per_full_matr()
scipy.interpolate._bsplines._make_interp_per_full_matr (x, y, t, k) protected
Returns a solution of a system for B-spline interpolation with periodic
boundary conditions. First ``k - 1`` rows of matrix are condtions of
periodicity (continuity of ``k - 1`` derivatives at the boundary points).
Last ``n`` rows are interpolation conditions.
RHS is ``k - 1`` zeros and ``n`` ordinates in this case.
Parameters
----------
x : 1-D array, shape (n,)
    Values of x - coordinate of a given set of points.
y : 1-D array, shape (n,)
    Values of y - coordinate of a given set of points.
t : 1-D array, shape(n+2*k,)
    Vector of knots.
k : int
    The maximum degree of spline
Returns
-------
c : 1-D array, shape (n+k-1,)
    B-spline coefficients
Notes
-----
``t`` is supposed to be taken on circle.
Definition at line 986 of file _bsplines.py.
Referenced by _make_periodic_spline().
_make_periodic_spline()
scipy.interpolate._bsplines._make_periodic_spline (x, y, t, k, axis) protected
Compute the (coefficients of) interpolating B-spline with periodic
boundary conditions.
Parameters
----------
x : array_like, shape (n,)
    Abscissas.
y : array_like, shape (n,)
    Ordinates.
k : int
    B-spline degree.
t : array_like, shape (n + 2 * k,).
    Knots taken on a circle, ``k`` on the left and ``k`` on the right
    of the vector ``x``.
Returns
-------
b : a BSpline object of the degree ``k`` and with knots ``t``.
Notes
-----
The original system is formed by ``n + k - 1`` equations where the first
``k - 1`` of them stand for the ``k - 1`` derivatives continuity on the
edges while the other equations correspond to an interpolating case
(matching all the input points). Due to a special form of knot vector, it
can be proved that in the original system the first and last ``k``
coefficients of a spline function are the same, respectively. It follows
from the fact that all ``k - 1`` derivatives are equal term by term at ends
and that the matrix of the original system of linear equations is
non-degenerate. So, we can reduce the number of equations to ``n - 1``
(first ``k - 1`` equations could be reduced). Another trick of this
implementation is cyclic shift of values of B-splines due to equality of
``k`` unknown coefficients. With this we can receive matrix of the system
with upper right and lower left blocks, and ``k`` diagonals.  It allows
to use Woodbury formula to optimize the computations.
Definition at line 1049 of file _bsplines.py.
References _make_interp_per_full_matr(), and _woodbury_algorithm().
Referenced by make_interp_spline().
_not_a_knot()
scipy.interpolate._bsplines._not_a_knot (x, k) protected
Given data x, construct the knot vector w/ not-a-knot BC.
cf de Boor, XIII(12).
Definition at line 838 of file _bsplines.py.
Referenced by scipy.interpolate._bsplines.BSpline.from_power_basis(), and make_interp_spline().
_periodic_knots()
scipy.interpolate._bsplines._periodic_knots (x, k) protected
returns vector of nodes on circle
Definition at line 966 of file _bsplines.py.
Referenced by scipy.interpolate._bsplines.BSpline.from_power_basis(), and make_interp_spline().
_process_deriv_spec()
scipy.interpolate._bsplines._process_deriv_spec (deriv) protected
Definition at line 867 of file _bsplines.py.
_woodbury_algorithm()
scipy.interpolate._bsplines._woodbury_algorithm (A, ur, ll, b, k) protected
Solve a cyclic banded linear system with upper right
and lower blocks of size ``(k-1) / 2`` using
the Woodbury formula
Parameters
----------
A : 2-D array, shape(k, n)
    Matrix of diagonals of original matrix (see
    ``solve_banded`` documentation).
ur : 2-D array, shape(bs, bs)
    Upper right block matrix.
ll : 2-D array, shape(bs, bs)
    Lower left block matrix.
b : 1-D array, shape(n,)
    Vector of constant terms of the system of linear equations.
k : int
    B-spline degree.
Returns
-------
c : 1-D array, shape(n,)
    Solution of the original system of linear equations.
Notes
-----
This algorithm works only for systems with banded matrix A plus
a correction term U @ V.T, where the matrix U @ V.T gives upper right
and lower left block of A
The system is solved with the following steps:
    1.  New systems of linear equations are constructed:
        A @ z_i = u_i,
        u_i - columnn vector of U,
        i = 1, ..., k - 1
    2.  Matrix Z is formed from vectors z_i:
        Z = [ z_1 | z_2 | ... | z_{k - 1} ]
    3.  Matrix H = (1 + V.T @ Z)^{-1}
    4.  The system A' @ y = b is solved
    5.  x = y - Z @ (H @ V.T @ y)
Also, ``n`` should be greater than ``k``, otherwise corner block
elements will intersect with diagonals.
Examples
--------
Consider the case of n = 8, k = 5 (size of blocks - 2 x 2).
The matrix of a system:       U:          V:
  x  x  x  *  *  a  b         a b 0 0     0 0 1 0
  x  x  x  x  *  *  c         0 c 0 0     0 0 0 1
  x  x  x  x  x  *  *         0 0 0 0     0 0 0 0
  *  x  x  x  x  x  *         0 0 0 0     0 0 0 0
  *  *  x  x  x  x  x         0 0 0 0     0 0 0 0
  d  *  *  x  x  x  x         0 0 d 0     1 0 0 0
  e  f  *  *  x  x  x         0 0 e f     0 1 0 0
References
----------
.. [1] William H. Press, Saul A. Teukolsky, William T. Vetterling
       and Brian P. Flannery, Numerical Recipes, 2007, Section 2.7.3
Definition at line 880 of file _bsplines.py.
Referenced by _make_periodic_spline(), and scipy.interpolate.tests.test_bsplines.TestInterp.test_woodbury().
make_interp_spline()
scipy.interpolate._bsplines.make_interp_spline (x, y, k = 3, t = None, bc_type = None, axis = 0, check_finite = True)
Compute the (coefficients of) interpolating B-spline.
Parameters
----------
x : array_like, shape (n,)
    Abscissas.
y : array_like, shape (n, ...)
    Ordinates.
k : int, optional
    B-spline degree. Default is cubic, ``k = 3``.
t : array_like, shape (nt + k + 1,), optional.
    Knots.
    The number of knots needs to agree with the number of data points and
    the number of derivatives at the edges. Specifically, ``nt - n`` must
    equal ``len(deriv_l) + len(deriv_r)``.
bc_type : 2-tuple or None
    Boundary conditions.
    Default is None, which means choosing the boundary conditions
    automatically. Otherwise, it must be a length-two tuple where the first
    element (``deriv_l``) sets the boundary conditions at ``x[0]`` and
    the second element (``deriv_r``) sets the boundary conditions at
    ``x[-1]``. Each of these must be an iterable of pairs
    ``(order, value)`` which gives the values of derivatives of specified
    orders at the given edge of the interpolation interval.
    Alternatively, the following string aliases are recognized:
    * ``"clamped"``: The first derivatives at the ends are zero. This is
       equivalent to ``bc_type=([(1, 0.0)], [(1, 0.0)])``.
    * ``"natural"``: The second derivatives at ends are zero. This is
      equivalent to ``bc_type=([(2, 0.0)], [(2, 0.0)])``.
    * ``"not-a-knot"`` (default): The first and second segments are the
      same polynomial. This is equivalent to having ``bc_type=None``.
    * ``"periodic"``: The values and the first ``k-1`` derivatives at the
      ends are equivalent.
axis : int, optional
    Interpolation axis. Default is 0.
check_finite : bool, optional
    Whether to check that the input arrays contain only finite numbers.
    Disabling may give a performance gain, but may result in problems
    (crashes, non-termination) if the inputs do contain infinities or NaNs.
    Default is True.
Returns
-------
b : a BSpline object of the degree ``k`` and with knots ``t``.
See Also
--------
BSpline : base class representing the B-spline objects
CubicSpline : a cubic spline in the polynomial basis
make_lsq_spline : a similar factory function for spline fitting
UnivariateSpline : a wrapper over FITPACK spline fitting routines
splrep : a wrapper over FITPACK spline fitting routines
Examples
--------
Use cubic interpolation on Chebyshev nodes:
>>> import numpy as np
>>> import matplotlib.pyplot as plt
>>> def cheb_nodes(N):
...     jj = 2.*np.arange(N) + 1
...     x = np.cos(np.pi * jj / 2 / N)[::-1]
...     return x
>>> x = cheb_nodes(20)
>>> y = np.sqrt(1 - x**2)
>>> from scipy.interpolate import BSpline, make_interp_spline
>>> b = make_interp_spline(x, y)
>>> np.allclose(b(x), y)
True
Note that the default is a cubic spline with a not-a-knot boundary condition
>>> b.k
3
Here we use a 'natural' spline, with zero 2nd derivatives at edges:
>>> l, r = [(2, 0.0)], [(2, 0.0)]
>>> b_n = make_interp_spline(x, y, bc_type=(l, r))  # or, bc_type="natural"
>>> np.allclose(b_n(x), y)
True
>>> x0, x1 = x[0], x[-1]
>>> np.allclose([b_n(x0, 2), b_n(x1, 2)], [0, 0])
True
Interpolation of parametric curves is also supported. As an example, we
compute a discretization of a snail curve in polar coordinates
>>> phi = np.linspace(0, 2.*np.pi, 40)
>>> r = 0.3 + np.cos(phi)
>>> x, y = r*np.cos(phi), r*np.sin(phi)  # convert to Cartesian coordinates
Build an interpolating curve, parameterizing it by the angle
>>> spl = make_interp_spline(phi, np.c_[x, y])
Evaluate the interpolant on a finer grid (note that we transpose the result
to unpack it into a pair of x- and y-arrays)
>>> phi_new = np.linspace(0, 2.*np.pi, 100)
>>> x_new, y_new = spl(phi_new).T
Plot the result
>>> plt.plot(x, y, 'o')
>>> plt.plot(x_new, y_new, '-')
>>> plt.show()
Build a B-spline curve with 2 dimensional y
>>> x = np.linspace(0, 2*np.pi, 10)
>>> y = np.array([np.sin(x), np.cos(x)])
Periodic condition is satisfied because y coordinates of points on the ends
are equivalent
>>> ax = plt.axes(projection='3d')
>>> xx = np.linspace(0, 2*np.pi, 100)
>>> bspl = make_interp_spline(x, y, k=5, bc_type='periodic', axis=1)
>>> ax.plot3D(xx, *bspl(xx))
>>> ax.scatter3D(x, *y, color='red')
>>> plt.show()
Definition at line 1138 of file _bsplines.py.
References _as_float_array(), _augknt(), _get_dtype(), _make_periodic_spline(), _not_a_knot(), and _periodic_knots().
Referenced by scipy.interpolate._rgi.RegularGridInterpolator.__call__(), scipy.interpolate._interpolate.interp1d.__init__(), scipy.interpolate.tests.test_bsplines.TestBSpline.test_design_matrix_bc_types(), scipy.interpolate.tests.test_bsplines.TestBSpline.test_design_matrix_same_as_BSpline_call(), and scipy.interpolate.tests.test_bsplines.TestSmoothingSpline.test_non_regularized_case().
make_lsq_spline()
scipy.interpolate._bsplines.make_lsq_spline (x, y, t, k = 3, w = None, axis = 0, check_finite = True)
Compute the (coefficients of) an LSQ (Least SQuared) based
fitting B-spline.
The result is a linear combination
.. math::
        S(x) = \sum_j c_j B_j(x; t)
of the B-spline basis elements, :math:`B_j(x; t)`, which minimizes
.. math::
    \sum_{j} \left( w_j \times (S(x_j) - y_j) \right)^2
Parameters
----------
x : array_like, shape (m,)
    Abscissas.
y : array_like, shape (m, ...)
    Ordinates.
t : array_like, shape (n + k + 1,).
    Knots.
    Knots and data points must satisfy Schoenberg-Whitney conditions.
k : int, optional
    B-spline degree. Default is cubic, ``k = 3``.
w : array_like, shape (m,), optional
    Weights for spline fitting. Must be positive. If ``None``,
    then weights are all equal.
    Default is ``None``.
axis : int, optional
    Interpolation axis. Default is zero.
check_finite : bool, optional
    Whether to check that the input arrays contain only finite numbers.
    Disabling may give a performance gain, but may result in problems
    (crashes, non-termination) if the inputs do contain infinities or NaNs.
    Default is True.
Returns
-------
b : a BSpline object of the degree ``k`` with knots ``t``.
See Also
--------
BSpline : base class representing the B-spline objects
make_interp_spline : a similar factory function for interpolating splines
LSQUnivariateSpline : a FITPACK-based spline fitting routine
splrep : a FITPACK-based fitting routine
Notes
-----
The number of data points must be larger than the spline degree ``k``.
Knots ``t`` must satisfy the Schoenberg-Whitney conditions,
i.e., there must be a subset of data points ``x[j]`` such that
``t[j] < x[j] < t[j+k+1]``, for ``j=0, 1,...,n-k-2``.
Examples
--------
Generate some noisy data:
>>> import numpy as np
>>> import matplotlib.pyplot as plt
>>> rng = np.random.default_rng()
>>> x = np.linspace(-3, 3, 50)
>>> y = np.exp(-x**2) + 0.1 * rng.standard_normal(50)
Now fit a smoothing cubic spline with a pre-defined internal knots.
Here we make the knot vector (k+1)-regular by adding boundary knots:
>>> from scipy.interpolate import make_lsq_spline, BSpline
>>> t = [-1, 0, 1]
>>> k = 3
>>> t = np.r_[(x[0],)*(k+1),
...           t,
...           (x[-1],)*(k+1)]
>>> spl = make_lsq_spline(x, y, t, k)
For comparison, we also construct an interpolating spline for the same
set of data:
>>> from scipy.interpolate import make_interp_spline
>>> spl_i = make_interp_spline(x, y)
Plot both:
>>> xs = np.linspace(-3, 3, 100)
>>> plt.plot(x, y, 'ro', ms=5)
>>> plt.plot(xs, spl(xs), 'g-', lw=3, label='LSQ spline')
>>> plt.plot(xs, spl_i(xs), 'b-', lw=3, alpha=0.7, label='interp spline')
>>> plt.legend(loc='best')
>>> plt.show()
**NaN handling**: If the input arrays contain ``nan`` values, the result is
not useful since the underlying spline fitting routines cannot deal with
``nan``. A workaround is to use zero weights for not-a-number data points:
>>> y[8] = np.nan
>>> w = np.isnan(y)
>>> y[w] = 0.
>>> tck = make_lsq_spline(x, y, t, w=~w)
Notice the need to replace a ``nan`` by a numerical value (precise value
does not matter as long as the corresponding weight is zero.)
Definition at line 1416 of file _bsplines.py.
References _as_float_array().
make_smoothing_spline()
scipy.interpolate._bsplines.make_smoothing_spline (x, y, w = None, lam = None)
Compute the (coefficients of) smoothing cubic spline function using
``lam`` to control the tradeoff between the amount of smoothness of the
curve and its proximity to the data. In case ``lam`` is None, using the
GCV criteria [1] to find it.
A smoothing spline is found as a solution to the regularized weighted
linear regression problem:
.. math::
    \sum\limits_{i=1}^n w_i\lvert y_i - f(x_i) \rvert^2 +
    \lambda\int\limits_{x_1}^{x_n} (f^{(2)}(u))^2 d u
where :math:`f` is a spline function, :math:`w` is a vector of weights and
:math:`\lambda` is a regularization parameter.
If ``lam`` is None, we use the GCV criteria to find an optimal
regularization parameter, otherwise we solve the regularized weighted
linear regression problem with given parameter. The parameter controls
the tradeoff in the following way: the larger the parameter becomes, the
smoother the function gets.
Parameters
----------
x : array_like, shape (n,)
    Abscissas. `n` must be larger than 5.
y : array_like, shape (n,)
    Ordinates. `n` must be larger than 5.
w : array_like, shape (n,), optional
    Vector of weights. Default is ``np.ones_like(x)``.
lam : float, (:math:`\lambda \geq 0`), optional
    Regularization parameter. If ``lam`` is None, then it is found from
    the GCV criteria. Default is None.
Returns
-------
func : a BSpline object.
    A callable representing a spline in the B-spline basis
    as a solution of the problem of smoothing splines using
    the GCV criteria [1] in case ``lam`` is None, otherwise using the
    given parameter ``lam``.
Notes
-----
This algorithm is a clean room reimplementation of the algorithm
introduced by Woltring in FORTRAN [2]. The original version cannot be used
in SciPy source code because of the license issues. The details of the
reimplementation are discussed here (available only in Russian) [4].
If the vector of weights ``w`` is None, we assume that all the points are
equal in terms of weights, and vector of weights is vector of ones.
Note that in weighted residual sum of squares, weights are not squared:
:math:`\sum\limits_{i=1}^n w_i\lvert y_i - f(x_i) \rvert^2` while in
``splrep`` the sum is built from the squared weights.
In cases when the initial problem is ill-posed (for example, the product
:math:`X^T W X` where :math:`X` is a design matrix is not a positive
defined matrix) a ValueError is raised.
References
----------
.. [1] G. Wahba, "Estimating the smoothing parameter" in Spline models for
    observational data, Philadelphia, Pennsylvania: Society for Industrial
    and Applied Mathematics, 1990, pp. 45-65.
    :doi:`10.1137/1.9781611970128`
.. [2] H. J. Woltring, A Fortran package for generalized, cross-validatory
    spline smoothing and differentiation, Advances in Engineering
    Software, vol. 8, no. 2, pp. 104-113, 1986.
    :doi:`10.1016/0141-1195(86)90098-7`
.. [3] T. Hastie, J. Friedman, and R. Tisbshirani, "Smoothing Splines" in
    The elements of Statistical Learning: Data Mining, Inference, and
    prediction, New York: Springer, 2017, pp. 241-249.
    :doi:`10.1007/978-0-387-84858-7`
.. [4] E. Zemlyanoy, "Generalized cross-validation smoothing splines",
    BSc thesis, 2022.
    `<https://www.hse.ru/ba/am/students/diplomas/620910604>`_ (in
    Russian)
Examples
--------
Generate some noisy data
>>> import numpy as np
>>> np.random.seed(1234)
>>> n = 200
>>> def func(x):
...    return x**3 + x**2 * np.sin(4 * x)
>>> x = np.sort(np.random.random_sample(n) * 4 - 2)
>>> y = func(x) + np.random.normal(scale=1.5, size=n)
Make a smoothing spline function
>>> from scipy.interpolate import make_smoothing_spline
>>> spl = make_smoothing_spline(x, y)
Plot both
>>> import matplotlib.pyplot as plt
>>> grid = np.linspace(x[0], x[-1], 400)
>>> plt.plot(grid, spl(grid), label='Spline')
>>> plt.plot(grid, func(grid), label='Original function')
>>> plt.scatter(x, y, marker='.')
>>> plt.legend(loc='best')
>>> plt.show()
Definition at line 1853 of file _bsplines.py.
References _coeff_of_divided_diff(), and _compute_optimal_gcv_parameter().
Referenced by scipy.interpolate.tests.test_bsplines.TestSmoothingSpline.test_compare_with_GCVSPL(), and scipy.interpolate.tests.test_bsplines.TestSmoothingSpline.test_non_regularized_case().
Variable Documentation
__all__
list scipy.interpolate._bsplines.__all__ private
Initial value:
=  ["BSpline", "make_interp_spline", "make_lsq_spline",
           "make_smoothing_spline"]
Definition at line 16 of file _bsplines.py.