Code Cloning Analysis: scipy._lib._docscrape.ClassDoc Class Reference
scipy._lib._docscrape.ClassDoc Class Reference
Public Member Functions
__init__ (self, cls, doc=None, modulename='', func_doc=FunctionDoc, config={})
methods (self)
properties (self)
Public Member Functions inherited from scipy._lib._docscrape.NumpyDocString
__init__ (self, docstring, config={})
__getitem__ (self, key)
__setitem__ (self, key, val)
__iter__ (self)
__len__ (self)
__str__ (self, func_role='')
Public Attributes
show_inherited_members
methods = config.get('exclude-members', [])
properties
Static Public Attributes
list extra_public_methods = ['__call__']
Static Public Attributes inherited from scipy._lib._docscrape.NumpyDocString
dict sections
str empty_description = '..'
Protected Member Functions
_is_show_member (self, name)
Protected Member Functions inherited from scipy._lib._docscrape.NumpyDocString
_is_at_section (self)
_strip (self, doc)
_read_to_next_section (self)
_read_sections (self)
_parse_param_list (self, content, single_element_is_type=False)
_parse_see_also (self, content)
_parse_index (self, section, content)
_parse_summary (self)
_parse (self)
_error_location (self, msg, error=True)
_str_header (self, name, symbol='-')
_str_indent (self, doc, indent=4)
_str_signature (self)
_str_summary (self)
_str_extended_summary (self)
_str_param_list (self, name)
_str_section (self, name)
_str_see_also (self, func_role)
_str_index (self)
Protected Attributes
_cls = cls
_mod = modulename
Protected Attributes inherited from scipy._lib._docscrape.NumpyDocString
_doc = Reader(docstring)
_parsed_data = copy.deepcopy(self.sections)
Additional Inherited Members
Static Protected Attributes inherited from scipy._lib._docscrape.NumpyDocString
str _role = r":(?P<role>\w+):"
str _funcbacktick = r"`(?P<name>(?:~\w+\.)?[a-zA-Z0-9_\.-]+)`"
str _funcplain = r"(?P<name2>[a-zA-Z0-9_\.-]+)"
str _funcname = r"(" + _role + _funcbacktick + r"|" + _funcplain + r")"
str _funcnamenext = _funcname.replace('role', 'rolenext')
str _description = r"(?P<description>\s*:(\s+(?P<desc>\S+.*))?)?\s*$"
_func_rgx = re.compile(r"^\s*" + _funcname + r"\s*")
_line_rgx
Detailed Description
Definition at line 599 of file _docscrape.py.
Constructor & Destructor Documentation
__init__()
scipy._lib._docscrape.ClassDoc.__init__ (self, cls, doc = None, modulename = '', func_doc = FunctionDoc, config = {})
Definition at line 603 of file _docscrape.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
_is_show_member()
scipy._lib._docscrape.ClassDoc._is_show_member (self, name) protected
Definition at line 675 of file _docscrape.py.
methods()
scipy._lib._docscrape.ClassDoc.methods (self)
Definition at line 656 of file _docscrape.py.
properties()
scipy._lib._docscrape.ClassDoc.properties (self)
Definition at line 666 of file _docscrape.py.
Member Data Documentation
_cls
scipy._lib._docscrape.ClassDoc._cls = cls protected
Definition at line 607 of file _docscrape.py.
_mod
scipy._lib._docscrape.ClassDoc._mod = modulename protected
Definition at line 619 of file _docscrape.py.
extra_public_methods
scipy._lib._docscrape.ClassDoc.extra_public_methods = ['__call__'] static
Definition at line 601 of file _docscrape.py.
methods
scipy._lib._docscrape.ClassDoc.methods = config.get('exclude-members', [])
Definition at line 639 of file _docscrape.py.
Referenced by sklearn.utils._param_validation.HasMethods.is_satisfied_by().
properties
scipy._lib._docscrape.ClassDoc.properties
Definition at line 640 of file _docscrape.py.
Referenced by matplotlib.artist.ArtistInspector.pprint_getters().
show_inherited_members
scipy._lib._docscrape.ClassDoc.show_inherited_members
Initial value:
=  config.get(
                    'show_inherited_class_members', True)
Definition at line 614 of file _docscrape.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/_lib/_docscrape.py