Code Cloning Analysis: scipy.io.arff._arffread Namespace Reference
scipy.io.arff._arffread Namespace Reference
Classes
class ArffError
class Attribute
class DateAttribute
class MetaData
class NominalAttribute
class NumericAttribute
class ParseArffError
class RelationalAttribute
class StringAttribute
Functions
to_attribute (name, attr_string)
csv_sniffer_has_bug_last_field ()
workaround_csv_sniffer_bug_last_field (sniff_line, dialect, delimiters)
split_data_line (line, dialect=None)
tokenize_attribute (iterable, attribute)
tokenize_single_comma (val)
tokenize_single_wcomma (val)
read_relational_attribute (ofile, relational_attribute, i)
read_header (ofile)
loadarff (f)
_loadarff (ofile)
basic_stats (data)
print_attribute (name, tp, data)
test_weka (filename)
Variables
list __all__ = ['MetaData', 'loadarff', 'ArffError', 'ParseArffError']
r_meta = re.compile(r'^\s*@')
r_comment = re.compile(r'^%')
r_empty = re.compile(r'^\s+$')
r_headerline = re.compile(r'^\s*@\S*')
r_datameta = re.compile(r'^@[Dd][Aa][Tt][Aa]')
r_relation = re.compile(r'^@[Rr][Ee][Ll][Aa][Tt][Ii][Oo][Nn]\s*(\S*)')
r_attribute = re.compile(r'^\s*@[Aa][Tt][Tt][Rr][Ii][Bb][Uu][Tt][Ee]\s*(..*$)')
r_nominal = re.compile(r'{(.+)}')
r_date = re.compile(r"[Dd][Aa][Tt][Ee]\s+[\"']?(.+?)[\"']?$")
r_comattrval = re.compile(r"'(..+)'\s+(..+$)")
r_wcomattrval = re.compile(r"(\S+)\s+(..+$)")
__test__
filename = sys.argv[1]
Function Documentation
_loadarff()
scipy.io.arff._arffread._loadarff (ofile) protected
Definition at line 808 of file _arffread.py.
basic_stats()
scipy.io.arff._arffread.basic_stats (data)
Definition at line 876 of file _arffread.py.
csv_sniffer_has_bug_last_field()
scipy.io.arff._arffread.csv_sniffer_has_bug_last_field ()
Checks if the bug https://bugs.python.org/issue30157 is unpatched.
Definition at line 401 of file _arffread.py.
Referenced by workaround_csv_sniffer_bug_last_field().
loadarff()
scipy.io.arff._arffread.loadarff (f)
Read an arff file.
The data is returned as a record array, which can be accessed much like
a dictionary of NumPy arrays. For example, if one of the attributes is
called 'pressure', then its first 10 data points can be accessed from the
``data`` record array like so: ``data['pressure'][0:10]``
Parameters
----------
f : file-like or str
   File-like object to read from, or filename to open.
Returns
-------
data : record array
   The data of the arff file, accessible by attribute names.
meta : `MetaData`
   Contains information about the arff file such as name and
   type of attributes, the relation (name of the dataset), etc.
Raises
------
ParseArffError
    This is raised if the given file is not ARFF-formatted.
NotImplementedError
    The ARFF file has an attribute which is not supported yet.
Notes
-----
This function should be able to read most arff files. Not
implemented functionality include:
* date type attributes
* string type attributes
It can read files with numeric and nominal attributes. It cannot read
files with sparse data ({} in the file). However, this function can
read files with missing data (? in the file), representing the data
points as NaNs.
Examples
--------
>>> from scipy.io import arff
>>> from io import StringIO
>>> content = \"\"\"
... @relation foo
... @attribute width  numeric
... @attribute height numeric
... @attribute color  {red,green,blue,yellow,black}
... @data
... 5.0,3.25,blue
... 4.5,3.75,green
... 3.0,4.00,red
... \"\"\"
>>> f = StringIO(content)
>>> data, meta = arff.loadarff(f)
>>> data
array([(5.0, 3.25, 'blue'), (4.5, 3.75, 'green'), (3.0, 4.0, 'red')],
      dtype=[('width', '<f8'), ('height', '<f8'), ('color', '|S6')])
>>> meta
Dataset: foo
\twidth's type is numeric
\theight's type is numeric
\tcolor's type is nominal, range is ('red', 'green', 'blue', 'yellow', 'black')
Definition at line 727 of file _arffread.py.
References loadarff(), and read_header().
Referenced by loadarff().
print_attribute()
scipy.io.arff._arffread.print_attribute (name, tp, data)
Definition at line 881 of file _arffread.py.
read_header()
scipy.io.arff._arffread.read_header (ofile)
Read the header of the iterable ofile.
Definition at line 622 of file _arffread.py.
References tokenize_attribute().
Referenced by loadarff().
read_relational_attribute()
scipy.io.arff._arffread.read_relational_attribute (ofile, relational_attribute, i)
Read the nested attributes of a relational attribute
Definition at line 600 of file _arffread.py.
References tokenize_attribute().
Referenced by tokenize_attribute().
split_data_line()
scipy.io.arff._arffread.split_data_line (line, dialect = None)
Definition at line 467 of file _arffread.py.
test_weka()
scipy.io.arff._arffread.test_weka (filename)
Definition at line 890 of file _arffread.py.
to_attribute()
scipy.io.arff._arffread.to_attribute (name, attr_string)
Definition at line 389 of file _arffread.py.
tokenize_attribute()
scipy.io.arff._arffread.tokenize_attribute (iterable, attribute)
Parse a raw string in header (e.g., starts by @attribute).
Given a raw string attribute, try to get the name and type of the
attribute. Constraints:
* The first line must start with @attribute (case insensitive, and
  space like characters before @attribute are allowed)
* Works also if the attribute is spread on multilines.
* Works if empty lines or comments are in between
Parameters
----------
attribute : str
   the attribute string.
Returns
-------
name : str
   name of the attribute
value : str
   value of the attribute
next : str
   next line to be parsed
Examples
--------
If attribute is a string defined in python as r"floupi real", will
return floupi as name, and real as value.
>>> iterable = iter([0] * 10) # dummy iterator
>>> tokenize_attribute(iterable, r"@attribute floupi real")
('floupi', 'real', 0)
If attribute is r"'floupi 2' real", will return 'floupi 2' as name,
and real as value.
>>> tokenize_attribute(iterable, r"  @attribute 'floupi 2' real   ")
('floupi 2', 'real', 0)
Definition at line 502 of file _arffread.py.
References read_relational_attribute().
Referenced by read_header(), and read_relational_attribute().
tokenize_single_comma()
scipy.io.arff._arffread.tokenize_single_comma (val)
Definition at line 570 of file _arffread.py.
tokenize_single_wcomma()
scipy.io.arff._arffread.tokenize_single_wcomma (val)
Definition at line 585 of file _arffread.py.
workaround_csv_sniffer_bug_last_field()
scipy.io.arff._arffread.workaround_csv_sniffer_bug_last_field (sniff_line, dialect, delimiters)
Workaround for the bug https://bugs.python.org/issue30157 if is unpatched.
Definition at line 417 of file _arffread.py.
References csv_sniffer_has_bug_last_field(), and workaround_csv_sniffer_bug_last_field().
Referenced by workaround_csv_sniffer_bug_last_field().
Variable Documentation
__all__
list scipy.io.arff._arffread.__all__ = ['MetaData', 'loadarff', 'ArffError', 'ParseArffError'] private
Definition at line 12 of file _arffread.py.
__test__
scipy.io.arff._arffread.__test__ private
Definition at line 899 of file _arffread.py.
filename
scipy.io.arff._arffread.filename = sys.argv[1]
Definition at line 904 of file _arffread.py.
r_attribute
scipy.io.arff._arffread.r_attribute = re.compile(r'^\s*@[Aa][Tt][Tt][Rr][Ii][Bb][Uu][Tt][Ee]\s*(..*$)')
Definition at line 39 of file _arffread.py.
r_comattrval
scipy.io.arff._arffread.r_comattrval = re.compile(r"'(..+)'\s+(..+$)")
Definition at line 45 of file _arffread.py.
r_comment
scipy.io.arff._arffread.r_comment = re.compile(r'^%')
Definition at line 32 of file _arffread.py.
r_datameta
scipy.io.arff._arffread.r_datameta = re.compile(r'^@[Dd][Aa][Tt][Aa]')
Definition at line 37 of file _arffread.py.
r_date
scipy.io.arff._arffread.r_date = re.compile(r"[Dd][Aa][Tt][Ee]\s+[\"']?(.+?)[\"']?$")
Definition at line 42 of file _arffread.py.
r_empty
scipy.io.arff._arffread.r_empty = re.compile(r'^\s+$')
Definition at line 34 of file _arffread.py.
r_headerline
scipy.io.arff._arffread.r_headerline = re.compile(r'^\s*@\S*')
Definition at line 36 of file _arffread.py.
r_meta
scipy.io.arff._arffread.r_meta = re.compile(r'^\s*@')
Definition at line 30 of file _arffread.py.
r_nominal
scipy.io.arff._arffread.r_nominal = re.compile(r'{(.+)}')
Definition at line 41 of file _arffread.py.
r_relation
scipy.io.arff._arffread.r_relation = re.compile(r'^@[Rr][Ee][Ll][Aa][Tt][Ii][Oo][Nn]\s*(\S*)')
Definition at line 38 of file _arffread.py.
r_wcomattrval
scipy.io.arff._arffread.r_wcomattrval = re.compile(r"(\S+)\s+(..+$)")
Definition at line 47 of file _arffread.py.