Code Cloning Analysis: sklearn.covariance._empirical_covariance Namespace Reference
sklearn.covariance._empirical_covariance Namespace Reference
Classes
class EmpiricalCovariance
Functions
log_likelihood (emp_cov, precision)
empirical_covariance (X, *, assume_centered=False)
Detailed Description
Maximum likelihood covariance estimator.
Function Documentation
empirical_covariance()
sklearn.covariance._empirical_covariance.empirical_covariance (X, * , assume_centered = False)
Compute the Maximum likelihood covariance estimator.
Parameters
----------
X : ndarray of shape (n_samples, n_features)
    Data from which to compute the covariance estimate.
assume_centered : bool, default=False
    If `True`, data will not be centered before computation.
    Useful when working with data whose mean is almost, but not exactly
    zero.
    If `False`, data will be centered before computation.
Returns
-------
covariance : ndarray of shape (n_features, n_features)
    Empirical covariance (Maximum Likelihood Estimator).
Examples
--------
>>> from sklearn.covariance import empirical_covariance
>>> X = [[1,1,1],[1,1,1],[1,1,1],
...      [0,0,0],[0,0,0],[0,0,0]]
>>> empirical_covariance(X)
array([[0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25]])
Definition at line 67 of file _empirical_covariance.py.
Referenced by sklearn.covariance._empirical_covariance.EmpiricalCovariance.fit(), and sklearn.covariance._empirical_covariance.EmpiricalCovariance.score().
log_likelihood()
sklearn.covariance._empirical_covariance.log_likelihood (emp_cov, precision)
Compute the sample mean of the log_likelihood under a covariance model.
Computes the empirical expected log-likelihood, allowing for universal
comparison (beyond this software package), and accounts for normalization
terms and scaling.
Parameters
----------
emp_cov : ndarray of shape (n_features, n_features)
    Maximum Likelihood Estimator of covariance.
precision : ndarray of shape (n_features, n_features)
    The precision matrix of the covariance model to be tested.
Returns
-------
log_likelihood_ : float
    Sample mean of the log-likelihood.
Definition at line 33 of file _empirical_covariance.py.
Referenced by sklearn.covariance._empirical_covariance.EmpiricalCovariance.score().