Code Cloning Analysis: pandas.core.computation.pytables.JointFilterBinOp Class Reference
pandas.core.computation.pytables.JointFilterBinOp Class Reference
Public Member Functions
format (self)
Self evaluate (self)
Public Member Functions inherited from pandas.core.computation.pytables.FilterBinOp
str __repr__ (self)
Self invert (self)
generate_filter_op (self, bool invert=False)
Public Member Functions inherited from pandas.core.computation.pytables.BinOp
None __init__ (self, str op, lhs, rhs, dict[str, Any] queryables, encoding)
prune (self, klass)
conform (self, rhs)
bool is_valid (self)
bool is_in_table (self)
kind (self)
meta (self)
metadata (self)
str generate (self, v)
TermValue convert_value (self, v)
None convert_values (self)
Public Member Functions inherited from pandas.core.computation.ops.BinOp
None __init__ (self, str op, lhs, rhs)
__call__ (self, env)
Public Member Functions inherited from pandas.core.computation.ops.Op
None __init__ (self, str op, Iterable[Term|Op] operands, encoding=None)
Iterator __iter__ (self)
str __repr__ (self)
return_type (self)
bool has_invalid_return_type (self)
operand_types (self)
bool is_scalar (self)
bool is_datetime (self)
Additional Inherited Members
Public Attributes inherited from pandas.core.computation.ops.BinOp
lhs = lhs
rhs = rhs
func = _binary_ops_dict[op]
Public Attributes inherited from pandas.core.computation.ops.Op
op = _bool_op_map.get(op, op)
operands = operands
encoding = encoding
return_type = object and types - obj_dtype_set
Static Public Attributes inherited from pandas.core.computation.pytables.FilterBinOp
tuple filter = None
Static Public Attributes inherited from pandas.core.computation.pytables.BinOp
dict queryables [str, Any]
str condition | None
Protected Member Functions inherited from pandas.core.computation.pytables.BinOp
None _disallow_scalar_only_bool_ops (self)
Static Protected Attributes inherited from pandas.core.computation.pytables.BinOp
int _max_selectors = 31
Detailed Description
Definition at line 340 of file pytables.py.
Member Function Documentation
evaluate()
Self pandas.core.computation.pytables.JointFilterBinOp.evaluate (self)
Evaluate a binary operation *before* being passed to the engine.
Parameters
----------
env : Scope
engine : str
parser : str
term_type : type
eval_in_python : list
Returns
-------
term_type
    The "pre-evaluated" expression as an instance of ``term_type``
Reimplemented from pandas.core.computation.pytables.FilterBinOp.
Definition at line 345 of file pytables.py.
Referenced by pip._vendor.distlib.markers.Evaluator.evaluate(), scipy.stats._kde.gaussian_kde.pdf(), and scipy.stats._survival.EmpiricalDistributionFunction.plot().
format()
pandas.core.computation.pytables.JointFilterBinOp.format (self)
return the actual filter format
Reimplemented from pandas.core.computation.pytables.FilterBinOp.
Definition at line 341 of file pytables.py.
Referenced by fontTools.ttLib.sfnt.SFNTReader.__getitem__(), scipy.io._mmio.MMFile._init_attrs(), scipy.sparse._base._spbase.asformat(), scipy.sparse._base._spbase.astype(), pip._internal.utils.logging.RichPipStreamHandler.emit(), pip._vendor.rich.logging.RichHandler.emit(), scipy.sparse._base._spbase.getformat(), scipy.sparse._matrix.spmatrix.getformat(), scipy.sparse._base._spbase.nnz(), scipy.sparse._base._spbase.set_shape(), scipy.sparse._dok.dok_matrix.set_shape(), and scipy.sparse._matrix.spmatrix.set_shape().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/core/computation/pytables.py