Code Cloning Analysis: matplotlib._mathtext.TruetypeFonts Class Reference
matplotlib._mathtext.TruetypeFonts Class Reference
Public Member Functions
__init__ (self, FontProperties default_font_prop, LoadFlags load_glyph_flags)
float get_xheight (self, str fontname, float fontsize, float dpi)
float get_underline_thickness (self, str font, float fontsize, float dpi)
float get_kern (self, str font1, str fontclass1, str sym1, float fontsize1, str font2, str fontclass2, str sym2, float fontsize2, float dpi)
Public Member Functions inherited from matplotlib._mathtext.Fonts
__init__ (self, FontProperties default_font_prop, LoadFlags load_glyph_flags)
FontMetrics get_metrics (self, str font, str font_class, str sym, float fontsize, float dpi)
None render_glyph (self, Output output, float ox, float oy, str font, str font_class, str sym, float fontsize, float dpi)
None render_rect_filled (self, Output output, float x1, float y1, float x2, float y2)
list[tuple[str, str]] get_sized_alternatives_for_symbol (self, str fontname, str sym)
Public Attributes
dict fontmap = {}
Public Attributes inherited from matplotlib._mathtext.Fonts
default_font_prop = default_font_prop
load_glyph_flags = load_glyph_flags
Protected Member Functions
FT2Font _get_font (self, str|int font)
float _get_offset (self, FT2Font font, Glyph glyph, float fontsize, float dpi)
tuple[FT2Font, int, bool] _get_glyph (self, str fontname, str font_class, str sym)
FontInfo _get_info (self, str fontname, str font_class, str sym, float fontsize, float dpi)
Protected Attributes
dict _fonts = {}
Detailed Description
A generic base class for all font setups that use Truetype fonts
(through FT2Font).
Definition at line 329 of file _mathtext.py.
Constructor & Destructor Documentation
__init__()
matplotlib._mathtext.TruetypeFonts.__init__ (self, FontProperties default_font_prop, LoadFlags load_glyph_flags)
Definition at line 335 of file _mathtext.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_get_font()
FT2Font matplotlib._mathtext.TruetypeFonts._get_font (self, str | int font) protected
Reimplemented from matplotlib._mathtext.Fonts.
Definition at line 347 of file _mathtext.py.
Referenced by matplotlib.textpath.TextToPath._get_char_id(), and matplotlib.textpath.TextToPath.get_text_path().
_get_glyph()
tuple[FT2Font, int, bool] matplotlib._mathtext.TruetypeFonts._get_glyph (self, str fontname, str font_class, str sym) protected
Definition at line 368 of file _mathtext.py.
_get_info()
FontInfo matplotlib._mathtext.TruetypeFonts._get_info (self, str fontname, str font_class, str sym, float fontsize, float dpi) protected
Reimplemented from matplotlib._mathtext.Fonts.
Definition at line 373 of file _mathtext.py.
_get_offset()
float matplotlib._mathtext.TruetypeFonts._get_offset (self, FT2Font font, Glyph glyph, float fontsize, float dpi) protected
Definition at line 362 of file _mathtext.py.
get_kern()
float matplotlib._mathtext.TruetypeFonts.get_kern (self, str font1, str fontclass1, str sym1, float fontsize1, str font2, str fontclass2, str sym2, float fontsize2, float dpi)
Get the kerning distance for font between *sym1* and *sym2*.
See `~.Fonts.get_metrics` for a detailed description of the parameters.
Reimplemented from matplotlib._mathtext.Fonts.
Definition at line 422 of file _mathtext.py.
References _get_info, and get_kern().
Referenced by get_kern().
get_underline_thickness()
float matplotlib._mathtext.TruetypeFonts.get_underline_thickness (self, str font, float fontsize, float dpi)
Get the line thickness that matches the given font.  Used as a
base unit for drawing lines such as in a fraction or radical.
Reimplemented from matplotlib._mathtext.Fonts.
Definition at line 416 of file _mathtext.py.
get_xheight()
float matplotlib._mathtext.TruetypeFonts.get_xheight (self, str font, float fontsize, float dpi)
Get the xheight for the given *font* and *fontsize*.
Reimplemented from matplotlib._mathtext.Fonts.
Definition at line 404 of file _mathtext.py.
References matplotlib._mathtext.Fonts._get_font(), and matplotlib._mathtext.Fonts.get_metrics().
Member Data Documentation
_fonts
dict matplotlib._mathtext.TruetypeFonts._fonts = {} protected
Definition at line 339 of file _mathtext.py.
fontmap
dict matplotlib._mathtext.TruetypeFonts.fontmap = {}
Definition at line 340 of file _mathtext.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/_mathtext.py