Code Cloning Analysis: pip._vendor.tomli._parser.Flags Class Reference
pip._vendor.tomli._parser.Flags Class Reference
Public Member Functions
None __init__ (self)
None add_pending (self, Key key, int flag)
None finalize_pending (self)
None unset_all (self, Key key)
None set (self, Key key, int flag, *, bool recursive)
bool is_ (self, Key key, int flag)
Static Public Attributes
int FROZEN = 0
int EXPLICIT_NEST = 1
Protected Attributes
dict _flags = {}
set[tuple[Key, int]] _pending_flags = set()
Detailed Description
Flags that map to parsed keys/namespaces.
Definition at line 135 of file _parser.py.
Constructor & Destructor Documentation
__init__()
None pip._vendor.tomli._parser.Flags.__init__ (self)
Definition at line 144 of file _parser.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
add_pending()
None pip._vendor.tomli._parser.Flags.add_pending (self, Key key, int flag)
Definition at line 148 of file _parser.py.
finalize_pending()
None pip._vendor.tomli._parser.Flags.finalize_pending (self)
Definition at line 151 of file _parser.py.
is_()
bool pip._vendor.tomli._parser.Flags.is_ (self, Key key, int flag)
Definition at line 175 of file _parser.py.
set()
None pip._vendor.tomli._parser.Flags.set (self, Key key, int flag, * , bool recursive)
Definition at line 164 of file _parser.py.
Referenced by matplotlib.contour.ContourSet.__init__(), matplotlib.axes._base._AxesBase._set_view(), mplot3d.axes3d.Axes3D._set_view(), matplotlib.axes._axes.Axes.pie(), and numpy.core.tests.test_simd._SIMD_ALL.test_lut().
unset_all()
None pip._vendor.tomli._parser.Flags.unset_all (self, Key key)
Definition at line 156 of file _parser.py.
Member Data Documentation
_flags
dict pip._vendor.tomli._parser.Flags._flags = {} protected
Definition at line 145 of file _parser.py.
Referenced by pandas.core.generic.NDFrame.flags().
_pending_flags
set[tuple[Key, int]] pip._vendor.tomli._parser.Flags._pending_flags = set() protected
Definition at line 146 of file _parser.py.
EXPLICIT_NEST
int pip._vendor.tomli._parser.Flags.EXPLICIT_NEST = 1 static
Definition at line 142 of file _parser.py.
FROZEN
int pip._vendor.tomli._parser.Flags.FROZEN = 0 static
Definition at line 139 of file _parser.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pip/_vendor/tomli/_parser.py