Code Cloning Analysis: sklearn.utils.tests.test_testing.MockEst Class Reference
sklearn.utils.tests.test_testing.MockEst Class Reference
Public Member Functions
__init__ (self)
fit (self, X, y)
predict (self, X)
predict_proba (self, X)
score (self, X)
Detailed Description
Definition at line 335 of file test_testing.py.
Constructor & Destructor Documentation
__init__()
sklearn.utils.tests.test_testing.MockEst.__init__ (self)
MockEstimator
Definition at line 336 of file test_testing.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params().
Member Function Documentation
fit()
sklearn.utils.tests.test_testing.MockEst.fit (self, X, y)
Definition at line 339 of file test_testing.py.
Referenced by sklearn.cluster._kmeans._BaseKMeans.fit_predict(), and sklearn.cluster._kmeans._BaseKMeans.fit_transform().
predict()
sklearn.utils.tests.test_testing.MockEst.predict (self, X)
Definition at line 342 of file test_testing.py.
predict_proba()
sklearn.utils.tests.test_testing.MockEst.predict_proba (self, X)
Definition at line 345 of file test_testing.py.
score()
sklearn.utils.tests.test_testing.MockEst.score (self, X)
Definition at line 348 of file test_testing.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/sklearn/utils/tests/test_testing.py