Code Cloning Analysis: scipy.sparse.tests.test_base.BinopTester_with_shape Class Reference
scipy.sparse.tests.test_base.BinopTester_with_shape Class Reference
Public Member Functions
__init__ (self, shape)
shape (self)
ndim (self)
__add__ (self, mat)
__mul__ (self, mat)
__sub__ (self, mat)
__radd__ (self, mat)
__rmul__ (self, mat)
__rsub__ (self, mat)
__matmul__ (self, mat)
__rmatmul__ (self, mat)
Protected Attributes
_shape = shape
Detailed Description
Definition at line 198 of file test_base.py.
Constructor & Destructor Documentation
__init__()
scipy.sparse.tests.test_base.BinopTester_with_shape.__init__ (self, shape)
Definition at line 201 of file test_base.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
__add__()
scipy.sparse.tests.test_base.BinopTester_with_shape.__add__ (self, mat)
Definition at line 210 of file test_base.py.
__matmul__()
scipy.sparse.tests.test_base.BinopTester_with_shape.__matmul__ (self, mat)
Definition at line 228 of file test_base.py.
__mul__()
scipy.sparse.tests.test_base.BinopTester_with_shape.__mul__ (self, mat)
Definition at line 213 of file test_base.py.
__radd__()
scipy.sparse.tests.test_base.BinopTester_with_shape.__radd__ (self, mat)
Definition at line 219 of file test_base.py.
__rmatmul__()
scipy.sparse.tests.test_base.BinopTester_with_shape.__rmatmul__ (self, mat)
Definition at line 231 of file test_base.py.
__rmul__()
scipy.sparse.tests.test_base.BinopTester_with_shape.__rmul__ (self, mat)
Definition at line 222 of file test_base.py.
__rsub__()
scipy.sparse.tests.test_base.BinopTester_with_shape.__rsub__ (self, mat)
Definition at line 225 of file test_base.py.
__sub__()
scipy.sparse.tests.test_base.BinopTester_with_shape.__sub__ (self, mat)
Definition at line 216 of file test_base.py.
ndim()
scipy.sparse.tests.test_base.BinopTester_with_shape.ndim (self)
Definition at line 207 of file test_base.py.
Referenced by numpy.lib.arrayterator.Arrayterator.__getitem__(), pandas.core.arrays.datetimes.DatetimeArray.__iter__(), and pandas.core.arrays.datetimelike.TimelikeOps.freq().
shape()
scipy.sparse.tests.test_base.BinopTester_with_shape.shape (self)
Definition at line 204 of file test_base.py.
Referenced by scipy.sparse._index.IndexMixin._getcol(), scipy.sparse._index.IndexMixin._getrow(), scipy.sparse._index.IndexMixin._raise_on_1d_array_slice(), and pandas.core.arrays.timedeltas.TimedeltaArray._scalar_divlike_op().
Member Data Documentation
_shape
scipy.sparse.tests.test_base.BinopTester_with_shape._shape = shape protected
Definition at line 202 of file test_base.py.
Referenced by pandas.util._doctools.TablePlotter._get_cells(), scipy.sparse._matrix.spmatrix.get_shape(), pandas.util._doctools.TablePlotter.plot(), and scipy.stats._covariance.Covariance.shape().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/sparse/tests/test_base.py