Code Cloning Analysis: scipy.sparse.linalg._isolve.tests.test_lsmr.TestLSMRReturns Class Reference
scipy.sparse.linalg._isolve.tests.test_lsmr.TestLSMRReturns Class Reference
Public Member Functions
setup_method (self)
test_unchanged_x0 (self)
testNormr (self)
testNormar (self)
testNormx (self)
Public Attributes
int n = 10
A = lowerBidiagonalMatrix(20, self.n)
xtrue = transpose(arange(self.n, 0, -1))
Afun = aslinearoperator(self.A)
b = self.Afun.matvec(self.xtrue)
x0 = ones(self.n)
x00 = self.x0.copy()
returnValues = lsmr(self.A, self.b)
returnValuesX0 = lsmr(self.A, self.b, x0=self.x0)
Detailed Description
Definition at line 128 of file test_lsmr.py.
Member Function Documentation
setup_method()
scipy.sparse.linalg._isolve.tests.test_lsmr.TestLSMRReturns.setup_method (self)
Definition at line 129 of file test_lsmr.py.
test_unchanged_x0()
scipy.sparse.linalg._isolve.tests.test_lsmr.TestLSMRReturns.test_unchanged_x0 (self)
Definition at line 140 of file test_lsmr.py.
testNormar()
scipy.sparse.linalg._isolve.tests.test_lsmr.TestLSMRReturns.testNormar (self)
Definition at line 148 of file test_lsmr.py.
testNormr()
scipy.sparse.linalg._isolve.tests.test_lsmr.TestLSMRReturns.testNormr (self)
Definition at line 144 of file test_lsmr.py.
testNormx()
scipy.sparse.linalg._isolve.tests.test_lsmr.TestLSMRReturns.testNormx (self)
Definition at line 153 of file test_lsmr.py.
Member Data Documentation
A
scipy.sparse.linalg._isolve.tests.test_lsmr.TestLSMRReturns.A = lowerBidiagonalMatrix(20, self.n)
Definition at line 131 of file test_lsmr.py.
Referenced by scipy.sparse.linalg._matfuncs._ExpmPadeHelper.__init__(), scipy.sparse.linalg.tests.test_onenormest.MatrixProductOperator._matmat(), scipy.sparse.linalg.tests.test_onenormest.MatrixProductOperator._matvec(), and scipy.sparse.linalg.tests.test_onenormest.MatrixProductOperator._rmatvec().
Afun
scipy.sparse.linalg._isolve.tests.test_lsmr.TestLSMRReturns.Afun = aslinearoperator(self.A)
Definition at line 133 of file test_lsmr.py.
b
scipy.sparse.linalg._isolve.tests.test_lsmr.TestLSMRReturns.b = self.Afun.matvec(self.xtrue)
Definition at line 134 of file test_lsmr.py.
Referenced by scipy.stats._continuous_distns.rv_histogram.__init__(), scipy.stats._discrete_distns.bernoulli_gen._get_support(), scipy.stats._distn_infrastructure.rv_generic._get_support(), scipy.stats._distn_infrastructure.rv_sample._get_support(), scipy.stats._distn_infrastructure.rv_continuous._updated_ctor_param(), scipy.stats._distn_infrastructure.rv_discrete._updated_ctor_param(), sklearn.tests.test_pipeline.NoTrans.get_params(), scipy.stats._page_trend_test._PageL.p_l_k_1(), scipy.stats._page_trend_test._PageL.pmf(), scipy.stats._page_trend_test._PageL.set_k(), sklearn.utils.tests.test_estimator_checks.ModifiesAnotherValue.set_params(), scipy.stats._page_trend_test._PageL.sf(), and scipy.special._mptestutils.Arg.values().
n
int scipy.sparse.linalg._isolve.tests.test_lsmr.TestLSMRReturns.n = 10
Definition at line 130 of file test_lsmr.py.
Referenced by scipy.stats._morestats._ABW.__init__(), scipy.stats._morestats._ABW._recalc(), scipy.stats._kde.gaussian_kde.integrate_kde(), scipy.stats._kde.gaussian_kde.marginal(), scipy.stats._binomtest.BinomTestResult.proportion_ci(), and scipy.stats._kde.gaussian_kde.resample().
returnValues
scipy.sparse.linalg._isolve.tests.test_lsmr.TestLSMRReturns.returnValues = lsmr(self.A, self.b)
Definition at line 137 of file test_lsmr.py.
returnValuesX0
scipy.sparse.linalg._isolve.tests.test_lsmr.TestLSMRReturns.returnValuesX0 = lsmr(self.A, self.b, x0=self.x0)
Definition at line 138 of file test_lsmr.py.
x0
scipy.sparse.linalg._isolve.tests.test_lsmr.TestLSMRReturns.x0 = ones(self.n)
Definition at line 135 of file test_lsmr.py.
x00
scipy.sparse.linalg._isolve.tests.test_lsmr.TestLSMRReturns.x00 = self.x0.copy()
Definition at line 136 of file test_lsmr.py.
xtrue
scipy.sparse.linalg._isolve.tests.test_lsmr.TestLSMRReturns.xtrue = transpose(arange(self.n, 0, -1))
Definition at line 132 of file test_lsmr.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/sparse/linalg/_isolve/tests/test_lsmr.py