Code Cloning Analysis: sklearn.utils._metadata_requests Namespace Reference
sklearn.utils._metadata_requests Namespace Reference
Classes
class _MetadataRequester
class _RoutingNotSupportedMixin
class MetadataRequest
class MetadataRouter
class MethodMapping
class MethodMetadataRequest
class RequestMethod
Functions
_routing_enabled ()
_raise_for_params (params, owner, method, allow=None)
_raise_for_unsupported_routing (obj, method, **kwargs)
request_is_alias (item)
request_is_valid (item)
get_routing_for_object (obj=None)
process_routing (_obj, _method, **kwargs)
Variables
list SIMPLE_METHODS
dict COMPOSITE_METHODS
list METHODS = SIMPLE_METHODS + list(COMPOSITE_METHODS.keys())
str UNUSED = "$UNUSED$"
str WARN = "$WARN$"
str UNCHANGED = "$UNCHANGED$"
list VALID_REQUEST_VALUES = [False, True, None, UNUSED, WARN]
RouterMappingPair = namedtuple("RouterMappingPair", ["mapping", "router"])
MethodPair = namedtuple("MethodPair", ["caller", "callee"])
str REQUESTER_DOC
str REQUESTER_DOC_PARAM
str REQUESTER_DOC_RETURN
Detailed Description
Metadata Routing Utility
In order to better understand the components implemented in this file, one
needs to understand their relationship to one another.
The only relevant public API for end users are the ``set_{method}_request`` methods,
e.g. ``estimator.set_fit_request(sample_weight=True)``. However, third-party
developers and users who implement custom meta-estimators, need to deal with
the objects implemented in this file.
The routing is coordinated by building ``MetadataRequest`` objects
for objects that consume metadata, and ``MetadataRouter`` objects for objects that
can route metadata, which are then aligned during a call to `process_routing()`. This
function returns a Bunch object (dictionary-like) with all the information on the
consumers and which metadata they had requested and the actual metadata values. A
routing method (such as `fit` in a meta-estimator) can now provide the metadata to the
relevant consuming method (such as `fit` in a sub-estimator).
The ``MetadataRequest`` and ``MetadataRouter`` objects are constructed via a
``get_metadata_routing`` method, which all scikit-learn estimators provide.
This method is automatically implemented via ``BaseEstimator`` for all simple
estimators, but needs a custom implementation for meta-estimators.
MetadataRequest
~~~~~~~~~~~~~~~
In non-routing consumers, the simplest case, e.g. ``SVM``, ``get_metadata_routing``
returns a ``MetadataRequest`` object  which is assigned to the consumer's
`_metadata_request` attribute. It stores which metadata is required by each method of
the consumer by including one ``MethodMetadataRequest`` per method in ``METHODS``
(e. g. ``fit``, ``score``, etc).
Users and developers almost never need to directly add a new ``MethodMetadataRequest``,
to the consumer's `_metadata_request` attribute, since these are generated
automatically. This attribute is modified while running `set_{method}_request` methods
(such as `set_fit_request()`), which adds the request via
`method_metadata_request.add_request(param=prop, alias=alias)`.
The ``alias`` in the ``add_request`` method has to be either a string (an alias),
or one of ``[True (requested), False (unrequested), None (error if passed)]``. There
are some other special values such as ``UNUSED`` and ``WARN`` which are used
for purposes such as warning of removing a metadata in a child class, but not
used by the end users.
MetadataRouter
~~~~~~~~~~~~~~
In routers (such as meta-estimators or multi metric scorers), ``get_metadata_routing``
returns a ``MetadataRouter`` object. It provides information about which method, from
the router object, calls which method in a consumer's object, and also, which metadata
had been requested by the consumer's methods, thus specifying how metadata is to be
passed. If a sub-estimator is a router as well, their routing information is also stored
in the meta-estimators router.
Conceptually, this information looks like:
```
{
    "sub_estimator1": (
        mapping=[(caller="fit", callee="transform"), ...],
        router=MetadataRequest(...),  # or another MetadataRouter
    ),
    ...
}
```
The `MetadataRouter` objects are never stored and are always recreated anew whenever
the object's `get_metadata_routing` method is called.
An object that is both a router and a consumer, e.g. a meta-estimator which
consumes ``sample_weight`` and routes ``sample_weight`` to its sub-estimators
also returns a ``MetadataRouter`` object. Its routing information includes both
information about what metadata is required by the object itself (added via
``MetadataRouter.add_self_request``), as well as the routing information for its
sub-estimators (added via ``MetadataRouter.add``).
Implementation Details
~~~~~~~~~~~~~~~~~~~~~~
To give the above representation some structure, we use the following objects:
- ``(caller=..., callee=...)`` is a namedtuple called ``MethodPair``.
- The list of ``MethodPair`` stored in the ``mapping`` field of a `RouterMappingPair` is
  a ``MethodMapping`` object.
- ``(mapping=..., router=...)`` is a namedtuple called ``RouterMappingPair``.
The ``set_{method}_request`` methods are dynamically generated for estimators
which inherit from ``BaseEstimator``. This is done by attaching instances
of the ``RequestMethod`` descriptor to classes, which is done in the
``_MetadataRequester`` class, and ``BaseEstimator`` inherits from this mixin.
This mixin also implements the ``get_metadata_routing``, which meta-estimators
need to override, but it works for simple consumers as is.
Function Documentation
_raise_for_params()
sklearn.utils._metadata_requests._raise_for_params (params, owner, method, allow = None) protected
Raise an error if metadata routing is not enabled and params are passed.
.. versionadded:: 1.4
Parameters
----------
params : dict
    The metadata passed to a method.
owner : object
    The object to which the method belongs.
method : str
    The name of the method, e.g. "fit".
allow : list of str, default=None
    A list of parameters which are allowed to be passed even if metadata
    routing is not enabled.
Raises
------
ValueError
    If metadata routing is not enabled and params are passed.
Definition at line 154 of file _metadata_requests.py.
References _routing_enabled().
_raise_for_unsupported_routing()
sklearn.utils._metadata_requests._raise_for_unsupported_routing (obj, method, ** kwargs) protected
Raise when metadata routing is enabled and metadata is passed.
This is used in meta-estimators which have not implemented metadata routing
to prevent silent bugs. There is no need to use this function if the
meta-estimator is not accepting any metadata, especially in `fit`, since
if a meta-estimator accepts any metadata, they would do that in `fit` as
well.
Parameters
----------
obj : estimator
    The estimator for which we're raising the error.
method : str
    The method where the error is raised.
**kwargs : dict
    The metadata passed to the method.
Definition at line 195 of file _metadata_requests.py.
References _routing_enabled().
_routing_enabled()
sklearn.utils._metadata_requests._routing_enabled () protected
Return whether metadata routing is enabled.
.. versionadded:: 1.3
Returns
-------
enabled : bool
    Whether metadata routing is enabled. If the config is not set, it
    defaults to False.
Definition at line 140 of file _metadata_requests.py.
Referenced by _raise_for_params(), and _raise_for_unsupported_routing().
get_routing_for_object()
sklearn.utils._metadata_requests.get_routing_for_object (obj = None)
Get a ``Metadata{Router, Request}`` instance from the given object.
This function returns a
:class:`~sklearn.utils.metadata_routing.MetadataRouter` or a
:class:`~sklearn.utils.metadata_routing.MetadataRequest` from the given input.
This function always returns a copy or an instance constructed from the
input, such that changing the output of this function will not change the
original object.
.. versionadded:: 1.3
Parameters
----------
obj : object
    - If the object provides a `get_metadata_routing` method, return a copy
        of the output of that method.
    - If the object is already a
        :class:`~sklearn.utils.metadata_routing.MetadataRequest` or a
        :class:`~sklearn.utils.metadata_routing.MetadataRouter`, return a copy
        of that.
    - Returns an empty :class:`~sklearn.utils.metadata_routing.MetadataRequest`
        otherwise.
Returns
-------
obj : MetadataRequest or MetadataRouter
    A ``MetadataRequest`` or a ``MetadataRouter`` taken or created from
    the given object.
Definition at line 1151 of file _metadata_requests.py.
Referenced by sklearn.utils._metadata_requests._MetadataRequester._get_metadata_request(), sklearn.utils._metadata_requests.MetadataRouter.add(), and process_routing().
process_routing()
sklearn.utils._metadata_requests.process_routing (_obj, _method, ** kwargs)
Validate and route metadata.
This function is used inside a :term:`router`'s method, e.g. :term:`fit`,
to validate the metadata and handle the routing.
Assuming this signature of a router's fit method:
``fit(self, X, y, sample_weight=None, **fit_params)``,
a call to this function would be:
``process_routing(self, "fit", sample_weight=sample_weight, **fit_params)``.
Note that if routing is not enabled and ``kwargs`` is empty, then it
returns an empty routing where ``process_routing(...).ANYTHING.ANY_METHOD``
is always an empty dictionary.
.. versionadded:: 1.3
Parameters
----------
_obj : object
    An object implementing ``get_metadata_routing``. Typically a
    :term:`meta-estimator`.
_method : str
    The name of the router's method in which this function is called.
**kwargs : dict
    Metadata to be routed.
Returns
-------
routed_params : Bunch
    A :class:`~utils.Bunch` of the form ``{"object_name": {"method_name":
    {metadata: value}}}`` which can be used to pass the required metadata to
    A :class:`~sklearn.utils.Bunch` of the form ``{"object_name": {"method_name":
    {metadata: value}}}`` which can be used to pass the required metadata to
    corresponding methods or corresponding child objects. The object names
    are those defined in `obj.get_metadata_routing()`.
Definition at line 1557 of file _metadata_requests.py.
References get_routing_for_object().
request_is_alias()
sklearn.utils._metadata_requests.request_is_alias (item)
Check if an item is a valid string alias for a metadata.
Values in ``VALID_REQUEST_VALUES`` are not considered aliases in this
context. Only a string which is a valid identifier is.
Parameters
----------
item : object
    The given item to be checked if it can be an alias for the metadata.
Returns
-------
result : bool
    Whether the given item is a valid alias.
Definition at line 265 of file _metadata_requests.py.
Referenced by sklearn.utils._metadata_requests.MethodMetadataRequest.add_request().
request_is_valid()
sklearn.utils._metadata_requests.request_is_valid (item)
Check if an item is a valid request value (and not an alias).
Parameters
----------
item : object
    The given item to be checked.
Returns
-------
result : bool
    Whether the given item is valid.
Definition at line 288 of file _metadata_requests.py.
Referenced by sklearn.utils._metadata_requests.MethodMetadataRequest._get_param_names(), and sklearn.utils._metadata_requests.MethodMetadataRequest.add_request().
Variable Documentation
COMPOSITE_METHODS
dict sklearn.utils._metadata_requests.COMPOSITE_METHODS
Initial value:
=  {
    "fit_transform": ["fit", "transform"],
    "fit_predict": ["fit", "predict"],
}
Definition at line 132 of file _metadata_requests.py.
MethodPair
sklearn.utils._metadata_requests.MethodPair = namedtuple("MethodPair", ["caller", "callee"])
Definition at line 730 of file _metadata_requests.py.
METHODS
list sklearn.utils._metadata_requests.METHODS = SIMPLE_METHODS + list(COMPOSITE_METHODS.keys())
Definition at line 137 of file _metadata_requests.py.
REQUESTER_DOC
str sklearn.utils._metadata_requests.REQUESTER_DOC
Definition at line 1200 of file _metadata_requests.py.
REQUESTER_DOC_PARAM
str sklearn.utils._metadata_requests.REQUESTER_DOC_PARAM
Initial value:
=  """        {metadata} : str, True, False, or None, \
                    default=sklearn.utils.metadata_routing.UNCHANGED
            Metadata routing for ``{metadata}`` parameter in ``{method}``.
"""
Definition at line 1233 of file _metadata_requests.py.
REQUESTER_DOC_RETURN
str sklearn.utils._metadata_requests.REQUESTER_DOC_RETURN
Initial value:
=  """        Returns
        -------
        self : object
            The updated object.
"""
Definition at line 1238 of file _metadata_requests.py.
RouterMappingPair
sklearn.utils._metadata_requests.RouterMappingPair = namedtuple("RouterMappingPair", ["mapping", "router"])
Definition at line 726 of file _metadata_requests.py.
SIMPLE_METHODS
list sklearn.utils._metadata_requests.SIMPLE_METHODS
Initial value:
=  [
    "fit",
    "partial_fit",
    "predict",
    "predict_proba",
    "predict_log_proba",
    "decision_function",
    "score",
    "split",
    "transform",
    "inverse_transform",
]
Definition at line 116 of file _metadata_requests.py.
UNCHANGED
str sklearn.utils._metadata_requests.UNCHANGED = "$UNCHANGED$"
Definition at line 260 of file _metadata_requests.py.
UNUSED
str sklearn.utils._metadata_requests.UNUSED = "$UNUSED$"
Definition at line 250 of file _metadata_requests.py.
VALID_REQUEST_VALUES
list sklearn.utils._metadata_requests.VALID_REQUEST_VALUES = [False, True, None, UNUSED, WARN]
Definition at line 262 of file _metadata_requests.py.
WARN
str sklearn.utils._metadata_requests.WARN = "$WARN$"
Definition at line 256 of file _metadata_requests.py.