Code Cloning Analysis: scipy.spatial.transform.tests.test_rotation_groups Namespace Reference
scipy.spatial.transform.tests.test_rotation_groups Namespace Reference
Functions
_calculate_rmsd (P, Q)
_generate_pyramid (n, axis)
_generate_prism (n, axis)
_generate_icosahedron ()
_generate_octahedron ()
_generate_tetrahedron ()
test_group_type (name)
test_group_name (name)
test_group_order_positive (name)
test_axis_valid (axis)
test_icosahedral ()
test_octahedral ()
test_tetrahedral ()
test_dicyclic (n, axis)
test_cyclic (n, axis)
test_group_sizes (name, size)
test_group_no_duplicates (name, size)
test_group_symmetry (name, size)
test_reduction (name)
test_single_reduction (name)
Variables
int TOL = 1E-12
NS = range(1, 13)
list NAMES = ["I", "O", "T"] + ["C%d" % n for n in NS] + ["D%d" % n for n in NS]
list SIZES = [60, 24, 12] + list(NS) + [2 * n for n in NS]
Function Documentation
_calculate_rmsd()
scipy.spatial.transform.tests.test_rotation_groups._calculate_rmsd (P, Q) protected
Calculates the root-mean-square distance between the points of P and Q.
The distance is taken as the minimum over all possible matchings. It is
zero if P and Q are identical and non-zero if not.
Definition at line 18 of file test_rotation_groups.py.
Referenced by test_cyclic(), test_dicyclic(), test_icosahedral(), test_octahedral(), and test_tetrahedral().
_generate_icosahedron()
scipy.spatial.transform.tests.test_rotation_groups._generate_icosahedron () protected
Definition at line 43 of file test_rotation_groups.py.
_generate_octahedron()
scipy.spatial.transform.tests.test_rotation_groups._generate_octahedron () protected
Definition at line 51 of file test_rotation_groups.py.
_generate_prism()
scipy.spatial.transform.tests.test_rotation_groups._generate_prism (n, axis) protected
Definition at line 35 of file test_rotation_groups.py.
_generate_pyramid()
scipy.spatial.transform.tests.test_rotation_groups._generate_pyramid (n, axis) protected
Definition at line 28 of file test_rotation_groups.py.
_generate_tetrahedron()
scipy.spatial.transform.tests.test_rotation_groups._generate_tetrahedron () protected
Definition at line 56 of file test_rotation_groups.py.
test_axis_valid()
scipy.spatial.transform.tests.test_rotation_groups.test_axis_valid (axis)
Definition at line 82 of file test_rotation_groups.py.
test_cyclic()
scipy.spatial.transform.tests.test_rotation_groups.test_cyclic (n, axis)
Test that the cyclic group correctly fixes the rotations of a
pyramid.
Definition at line 126 of file test_rotation_groups.py.
References _calculate_rmsd().
test_dicyclic()
scipy.spatial.transform.tests.test_rotation_groups.test_dicyclic (n, axis)
Test that the dicyclic group correctly fixes the rotations of a
prism.
Definition at line 116 of file test_rotation_groups.py.
References _calculate_rmsd().
test_group_name()
scipy.spatial.transform.tests.test_rotation_groups.test_group_name (name)
Definition at line 68 of file test_rotation_groups.py.
test_group_no_duplicates()
scipy.spatial.transform.tests.test_rotation_groups.test_group_no_duplicates (name, size)
Definition at line 140 of file test_rotation_groups.py.
test_group_order_positive()
scipy.spatial.transform.tests.test_rotation_groups.test_group_order_positive (name)
Definition at line 75 of file test_rotation_groups.py.
test_group_sizes()
scipy.spatial.transform.tests.test_rotation_groups.test_group_sizes (name, size)
Definition at line 135 of file test_rotation_groups.py.
test_group_symmetry()
scipy.spatial.transform.tests.test_rotation_groups.test_group_symmetry (name, size)
Definition at line 147 of file test_rotation_groups.py.
test_group_type()
scipy.spatial.transform.tests.test_rotation_groups.test_group_type (name)
Definition at line 61 of file test_rotation_groups.py.
test_icosahedral()
scipy.spatial.transform.tests.test_rotation_groups.test_icosahedral ()
The icosahedral group fixes the rotations of an icosahedron. Here we
test that the icosahedron is invariant after application of the elements
of the rotation group.
Definition at line 88 of file test_rotation_groups.py.
References _calculate_rmsd().
test_octahedral()
scipy.spatial.transform.tests.test_rotation_groups.test_octahedral ()
Test that the octahedral group correctly fixes the rotations of an
octahedron.
Definition at line 98 of file test_rotation_groups.py.
References _calculate_rmsd().
test_reduction()
scipy.spatial.transform.tests.test_rotation_groups.test_reduction (name)
Test that the elements of the rotation group are correctly
mapped onto the identity rotation.
Definition at line 156 of file test_rotation_groups.py.
test_single_reduction()
scipy.spatial.transform.tests.test_rotation_groups.test_single_reduction (name)
Definition at line 165 of file test_rotation_groups.py.
test_tetrahedral()
scipy.spatial.transform.tests.test_rotation_groups.test_tetrahedral ()
Test that the tetrahedral group correctly fixes the rotations of a
tetrahedron.
Definition at line 106 of file test_rotation_groups.py.
References _calculate_rmsd().
Variable Documentation
NAMES
list scipy.spatial.transform.tests.test_rotation_groups.NAMES = ["I", "O", "T"] + ["C%d" % n for n in NS] + ["D%d" % n for n in NS]
Definition at line 14 of file test_rotation_groups.py.
NS
scipy.spatial.transform.tests.test_rotation_groups.NS = range(1, 13)
Definition at line 13 of file test_rotation_groups.py.
SIZES
list scipy.spatial.transform.tests.test_rotation_groups.SIZES = [60, 24, 12] + list(NS) + [2 * n for n in NS]
Definition at line 15 of file test_rotation_groups.py.
TOL
int scipy.spatial.transform.tests.test_rotation_groups.TOL = 1E-12
Definition at line 12 of file test_rotation_groups.py.