Code Cloning Analysis: sklearn.datasets._kddcup99 Namespace Reference
sklearn.datasets._kddcup99 Namespace Reference
Functions
fetch_kddcup99 (*, subset=None, data_home=None, shuffle=False, random_state=None, percent10=True, download_if_missing=True, return_X_y=False, as_frame=False, n_retries=3, delay=1.0)
_fetch_brute_kddcup99 (data_home=None, download_if_missing=True, percent10=True, n_retries=3, delay=1.0)
_mkdirp (d)
Variables
ARCHIVE
ARCHIVE_10_PERCENT
logger = logging.getLogger(__name__)
Detailed Description
KDDCUP 99 dataset.
A classic dataset for anomaly detection.
The dataset page is available from UCI Machine Learning Repository
https://archive.ics.uci.edu/ml/machine-learning-databases/kddcup99-mld/kddcup.data.gz
Function Documentation
_fetch_brute_kddcup99()
sklearn.datasets._kddcup99._fetch_brute_kddcup99 (data_home = None, download_if_missing = True, percent10 = True, n_retries = 3, delay = 1.0) protected
Load the kddcup99 dataset, downloading it if necessary.
Parameters
----------
data_home : str, default=None
    Specify another download and cache folder for the datasets. By default
    all scikit-learn data is stored in '~/scikit_learn_data' subfolders.
download_if_missing : bool, default=True
    If False, raise an OSError if the data is not locally available
    instead of trying to download the data from the source site.
percent10 : bool, default=True
    Whether to load only 10 percent of the data.
n_retries : int, default=3
    Number of retries when HTTP errors are encountered.
delay : float, default=1.0
    Number of seconds between retries.
Returns
-------
dataset : :class:`~sklearn.utils.Bunch`
    Dictionary-like object, with the following attributes.
    data : ndarray of shape (494021, 41)
        Each row corresponds to the 41 features in the dataset.
    target : ndarray of shape (494021,)
        Each value corresponds to one of the 21 attack types or to the
        label 'normal.'.
    feature_names : list
        The names of the dataset columns
    target_names: list
        The names of the target columns
    DESCR : str
        Description of the kddcup99 dataset.
Definition at line 266 of file _kddcup99.py.
References _mkdirp().
Referenced by fetch_kddcup99().
_mkdirp()
sklearn.datasets._kddcup99._mkdirp (d) protected
Ensure directory d exists (like mkdir -p on Unix)
No guarantee that the directory is writable.
Definition at line 421 of file _kddcup99.py.
Referenced by _fetch_brute_kddcup99().
fetch_kddcup99()
sklearn.datasets._kddcup99.fetch_kddcup99 (* , subset = None, data_home = None, shuffle = False, random_state = None, percent10 = True, download_if_missing = True, return_X_y = False, as_frame = False, n_retries = 3, delay = 1.0)
Load the kddcup99 dataset (classification).
Download it if necessary.
=================   ====================================
Classes                                               23
Samples total                                    4898431
Dimensionality                                        41
Features            discrete (int) or continuous (float)
=================   ====================================
Read more in the :ref:`User Guide <kddcup99_dataset>`.
.. versionadded:: 0.18
Parameters
----------
subset : {'SA', 'SF', 'http', 'smtp'}, default=None
    To return the corresponding classical subsets of kddcup 99.
    If None, return the entire kddcup 99 dataset.
data_home : str or path-like, default=None
    Specify another download and cache folder for the datasets. By default
    all scikit-learn data is stored in '~/scikit_learn_data' subfolders.
    .. versionadded:: 0.19
shuffle : bool, default=False
    Whether to shuffle dataset.
random_state : int, RandomState instance or None, default=None
    Determines random number generation for dataset shuffling and for
    selection of abnormal samples if `subset='SA'`. Pass an int for
    reproducible output across multiple function calls.
    See :term:`Glossary <random_state>`.
percent10 : bool, default=True
    Whether to load only 10 percent of the data.
download_if_missing : bool, default=True
    If False, raise an OSError if the data is not locally available
    instead of trying to download the data from the source site.
return_X_y : bool, default=False
    If True, returns ``(data, target)`` instead of a Bunch object. See
    below for more information about the `data` and `target` object.
    .. versionadded:: 0.20
as_frame : bool, default=False
    If `True`, returns a pandas Dataframe for the ``data`` and ``target``
    objects in the `Bunch` returned object; `Bunch` return object will also
    have a ``frame`` member.
    .. versionadded:: 0.24
n_retries : int, default=3
    Number of retries when HTTP errors are encountered.
    .. versionadded:: 1.5
delay : float, default=1.0
    Number of seconds between retries.
    .. versionadded:: 1.5
Returns
-------
data : :class:`~sklearn.utils.Bunch`
    Dictionary-like object, with the following attributes.
    data : {ndarray, dataframe} of shape (494021, 41)
        The data matrix to learn. If `as_frame=True`, `data` will be a
        pandas DataFrame.
    target : {ndarray, series} of shape (494021,)
        The regression target for each sample. If `as_frame=True`, `target`
        will be a pandas Series.
    frame : dataframe of shape (494021, 42)
        Only present when `as_frame=True`. Contains `data` and `target`.
    DESCR : str
        The full description of the dataset.
    feature_names : list
        The names of the dataset columns
    target_names: list
        The names of the target columns
(data, target) : tuple if ``return_X_y`` is True
    A tuple of two ndarray. The first containing a 2D array of
    shape (n_samples, n_features) with each row representing one
    sample and each column representing the features. The second
    ndarray of shape (n_samples,) containing the target samples.
    .. versionadded:: 0.20
Definition at line 69 of file _kddcup99.py.
References _fetch_brute_kddcup99().
Variable Documentation
ARCHIVE
sklearn.datasets._kddcup99.ARCHIVE
Initial value:
=  RemoteFileMetadata(
    filename="kddcup99_data",
    url="https://ndownloader.figshare.com/files/5976045",
    checksum="3b6c942aa0356c0ca35b7b595a26c89d343652c9db428893e7494f837b274292",
)
Definition at line 37 of file _kddcup99.py.
ARCHIVE_10_PERCENT
sklearn.datasets._kddcup99.ARCHIVE_10_PERCENT
Initial value:
=  RemoteFileMetadata(
    filename="kddcup99_10_data",
    url="https://ndownloader.figshare.com/files/5976042",
    checksum="8045aca0d84e70e622d1148d7df782496f6333bf6eb979a1b0837c42a9fd9561",
)
Definition at line 45 of file _kddcup99.py.
logger
sklearn.datasets._kddcup99.logger = logging.getLogger(__name__)
Definition at line 51 of file _kddcup99.py.