Code Cloning Analysis: sklearn.linear_model.tests.test_linear_loss Namespace Reference
sklearn.linear_model.tests.test_linear_loss Namespace Reference
Functions
random_X_y_coef (linear_model_loss, n_samples, n_features, coef_bound=(-2, 2), seed=42)
test_init_zero_coef (base_loss, fit_intercept, n_features, dtype, global_random_seed)
test_loss_grad_hess_are_the_same (base_loss, fit_intercept, sample_weight, l2_reg_strength, csr_container, global_random_seed)
test_loss_gradients_hessp_intercept (base_loss, sample_weight, l2_reg_strength, X_container, global_random_seed)
test_gradients_hessians_numerically (base_loss, fit_intercept, sample_weight, l2_reg_strength, global_random_seed)
test_multinomial_coef_shape (fit_intercept, global_random_seed)
test_multinomial_hessian_3_classes (sample_weight, global_random_seed)
test_linear_loss_gradient_hessian_raises_wrong_out_parameters ()
Variables
list LOSSES = [HalfBinomialLoss, HalfMultinomialLoss, HalfPoissonLoss]
Detailed Description
Tests for LinearModelLoss
Note that correctness of losses (which compose LinearModelLoss) is already well
covered in the _loss module.
Function Documentation
random_X_y_coef()
sklearn.linear_model.tests.test_linear_loss.random_X_y_coef (linear_model_loss, n_samples, n_features, coef_bound = (-2, 2), seed = 42)
Random generate y, X and coef in valid range.
Definition at line 28 of file test_linear_loss.py.
Referenced by test_gradients_hessians_numerically(), test_loss_grad_hess_are_the_same(), test_loss_gradients_hessp_intercept(), test_multinomial_coef_shape(), and test_multinomial_hessian_3_classes().
test_gradients_hessians_numerically()
sklearn.linear_model.tests.test_linear_loss.test_gradients_hessians_numerically (base_loss, fit_intercept, sample_weight, l2_reg_strength, global_random_seed)
Test gradients and hessians with numerical derivatives.
Gradient should equal the numerical derivatives of the loss function.
Hessians should equal the numerical derivatives of gradients.
Definition at line 266 of file test_linear_loss.py.
References random_X_y_coef().
test_init_zero_coef()
sklearn.linear_model.tests.test_linear_loss.test_init_zero_coef (base_loss, fit_intercept, n_features, dtype, global_random_seed)
Test that init_zero_coef initializes coef correctly.
Definition at line 84 of file test_linear_loss.py.
test_linear_loss_gradient_hessian_raises_wrong_out_parameters()
sklearn.linear_model.tests.test_linear_loss.test_linear_loss_gradient_hessian_raises_wrong_out_parameters ()
Test that wrong gradient_out and hessian_out raises errors.
Definition at line 464 of file test_linear_loss.py.
test_loss_grad_hess_are_the_same()
sklearn.linear_model.tests.test_linear_loss.test_loss_grad_hess_are_the_same (base_loss, fit_intercept, sample_weight, l2_reg_strength, csr_container, global_random_seed)
Test that loss and gradient are the same across different functions.
Definition at line 112 of file test_linear_loss.py.
References random_X_y_coef().
test_loss_gradients_hessp_intercept()
sklearn.linear_model.tests.test_linear_loss.test_loss_gradients_hessp_intercept (base_loss, sample_weight, l2_reg_strength, X_container, global_random_seed)
Test that loss and gradient handle intercept correctly.
Definition at line 207 of file test_linear_loss.py.
References random_X_y_coef().
test_multinomial_coef_shape()
sklearn.linear_model.tests.test_linear_loss.test_multinomial_coef_shape (fit_intercept, global_random_seed)
Test that multinomial LinearModelLoss respects shape of coef.
Definition at line 351 of file test_linear_loss.py.
References random_X_y_coef().
test_multinomial_hessian_3_classes()
sklearn.linear_model.tests.test_linear_loss.test_multinomial_hessian_3_classes (sample_weight, global_random_seed)
Test multinomial hessian for 3 classes and 2 points.
For n_classes = 3 and n_samples = 2, we have
  p0 = [p0_0, p0_1]
  p1 = [p1_0, p1_1]
  p2 = [p2_0, p2_1]
and with 2 x 2 diagonal subblocks
  H = [p0 * (1-p0),    -p0 * p1,    -p0 * p2]
      [   -p0 * p1, p1 * (1-p1),    -p1 * p2]
      [   -p0 * p2,    -p1 * p2, p2 * (1-p2)]
  hess = X' H X
Definition at line 392 of file test_linear_loss.py.
References random_X_y_coef().
Variable Documentation
LOSSES
list sklearn.linear_model.tests.test_linear_loss.LOSSES = [HalfBinomialLoss, HalfMultinomialLoss, HalfPoissonLoss]
Definition at line 25 of file test_linear_loss.py.