Code Cloning Analysis: numpy.lib.tests.test_utils Namespace Reference
numpy.lib.tests.test_utils Namespace Reference
Classes
class TestByteBounds
Functions
test_lookfor ()
old_func (self, x)
old_func2 (self, x)
old_func3 (self, x)
old_func4 (self, x)
old_func5 (self, x)
old_func6 (self, x)
old_func7 (self, x)
test_deprecate_decorator ()
test_deprecate_decorator_message ()
test_deprecate_fn ()
test_deprecate_with_doc_decorator_message ()
test_deprecate_help_indentation (old_func, new_func)
_compare_docs (old_func, new_func)
test_deprecate_preserve_whitespace ()
test_deprecate_module ()
test_safe_eval_nameconstant ()
test_assert_raises_regex_context_manager ()
test_info_method_heading ()
test_drop_metadata ()
test_drop_metadata_identity_and_copy (dtype)
Variables
new_func3 = deprecate(old_func3, old_name="old_func3", new_name="new_func3")
new_func4 = deprecate(old_func4)
new_func5 = deprecate(old_func5, message="This function is\ndeprecated.")
new_func6 = deprecate(old_func6)
Function Documentation
_compare_docs()
numpy.lib.tests.test_utils._compare_docs (old_func, new_func) protected
Definition at line 107 of file test_utils.py.
old_func()
numpy.lib.tests.test_utils.old_func (self, x)
Definition at line 28 of file test_utils.py.
old_func2()
numpy.lib.tests.test_utils.old_func2 (self, x)
Definition at line 33 of file test_utils.py.
old_func3()
numpy.lib.tests.test_utils.old_func3 (self, x)
Definition at line 37 of file test_utils.py.
old_func4()
numpy.lib.tests.test_utils.old_func4 (self, x)
Summary.
Further info.
Definition at line 42 of file test_utils.py.
References numpy.lib.utils.deprecate().
old_func5()
numpy.lib.tests.test_utils.old_func5 (self, x)
Summary.
    Bizarre indentation.
Definition at line 51 of file test_utils.py.
References numpy.lib.utils.deprecate().
old_func6()
numpy.lib.tests.test_utils.old_func6 (self, x)
Also in PEP-257.
Definition at line 60 of file test_utils.py.
References numpy.lib.utils.deprecate().
old_func7()
numpy.lib.tests.test_utils.old_func7 (self, x)
Definition at line 69 of file test_utils.py.
test_assert_raises_regex_context_manager()
numpy.lib.tests.test_utils.test_assert_raises_regex_context_manager ()
Definition at line 158 of file test_utils.py.
test_deprecate_decorator()
numpy.lib.tests.test_utils.test_deprecate_decorator ()
Definition at line 73 of file test_utils.py.
test_deprecate_decorator_message()
numpy.lib.tests.test_utils.test_deprecate_decorator_message ()
Definition at line 77 of file test_utils.py.
test_deprecate_fn()
numpy.lib.tests.test_utils.test_deprecate_fn ()
Definition at line 81 of file test_utils.py.
test_deprecate_help_indentation()
numpy.lib.tests.test_utils.test_deprecate_help_indentation (old_func, new_func)
Definition at line 96 of file test_utils.py.
test_deprecate_module()
numpy.lib.tests.test_utils.test_deprecate_module ()
Definition at line 119 of file test_utils.py.
test_deprecate_preserve_whitespace()
numpy.lib.tests.test_utils.test_deprecate_preserve_whitespace ()
Definition at line 115 of file test_utils.py.
test_deprecate_with_doc_decorator_message()
numpy.lib.tests.test_utils.test_deprecate_with_doc_decorator_message ()
Definition at line 86 of file test_utils.py.
test_drop_metadata()
numpy.lib.tests.test_utils.test_drop_metadata ()
Definition at line 182 of file test_utils.py.
test_drop_metadata_identity_and_copy()
numpy.lib.tests.test_utils.test_drop_metadata_identity_and_copy (dtype)
Definition at line 222 of file test_utils.py.
test_info_method_heading()
numpy.lib.tests.test_utils.test_info_method_heading ()
Definition at line 163 of file test_utils.py.
test_lookfor()
numpy.lib.tests.test_utils.test_lookfor ()
Definition at line 19 of file test_utils.py.
test_safe_eval_nameconstant()
numpy.lib.tests.test_utils.test_safe_eval_nameconstant ()
Definition at line 123 of file test_utils.py.
Variable Documentation
new_func3
numpy.lib.tests.test_utils.new_func3 = deprecate(old_func3, old_name="old_func3", new_name="new_func3")
Definition at line 39 of file test_utils.py.
new_func4
numpy.lib.tests.test_utils.new_func4 = deprecate(old_func4)
Definition at line 48 of file test_utils.py.
new_func5
numpy.lib.tests.test_utils.new_func5 = deprecate(old_func5, message="This function is\ndeprecated.")
Definition at line 57 of file test_utils.py.
new_func6
numpy.lib.tests.test_utils.new_func6 = deprecate(old_func6)
Definition at line 65 of file test_utils.py.