Code Cloning Analysis: numpy.tests.test_warnings.FindFuncs Class Reference
numpy.tests.test_warnings.FindFuncs Class Reference
Public Member Functions
__init__ (self, filename)
visit_Call (self, node)
Private Attributes
__filename = filename
Detailed Description
Definition at line 24 of file test_warnings.py.
Constructor & Destructor Documentation
__init__()
numpy.tests.test_warnings.FindFuncs.__init__ (self, filename)
Definition at line 25 of file test_warnings.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
visit_Call()
numpy.tests.test_warnings.FindFuncs.visit_Call (self, node)
Definition at line 29 of file test_warnings.py.
Member Data Documentation
__filename
numpy.tests.test_warnings.FindFuncs.__filename = filename private
Definition at line 27 of file test_warnings.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/tests/test_warnings.py