Code Cloning Analysis: matplotlib.dviread.PsfontsMap Class Reference
matplotlib.dviread.PsfontsMap Class Reference
Public Member Functions
__new__ (cls, filename)
__getitem__ (self, texname)
Protected Member Functions
_parse_and_cache_line (self, line)
Protected Attributes
_filename = os.fsdecode(filename)
dict _unparsed = {}
dict _parsed = {}
Static Private Attributes
tuple __slots__ = ('_filename', '_unparsed', '_parsed')
Detailed Description
A psfonts.map formatted file, mapping TeX fonts to PS fonts.
Parameters
----------
filename : str or path-like
Notes
-----
For historical reasons, TeX knows many Type-1 fonts by different
names than the outside world. (For one thing, the names have to
fit in eight characters.) Also, TeX's native fonts are not Type-1
but Metafont, which is nontrivial to convert to PostScript except
as a bitmap. While high-quality conversions to Type-1 format exist
and are shipped with modern TeX distributions, we need to know
which Type-1 fonts are the counterparts of which native fonts. For
these reasons a mapping is needed from internal font names to font
file names.
A texmf tree typically includes mapping files called e.g.
:file:`psfonts.map`, :file:`pdftex.map`, or :file:`dvipdfm.map`.
The file :file:`psfonts.map` is used by :program:`dvips`,
:file:`pdftex.map` by :program:`pdfTeX`, and :file:`dvipdfm.map`
by :program:`dvipdfm`. :file:`psfonts.map` might avoid embedding
the 35 PostScript fonts (i.e., have no filename for them, as in
the Times-Bold example above), while the pdf-related files perhaps
only avoid the "Base 14" pdf fonts. But the user may have
configured these files differently.
Examples
--------
>>> map = PsfontsMap(find_tex_file('pdftex.map'))
>>> entry = map[b'ptmbo8r']
>>> entry.texname
b'ptmbo8r'
>>> entry.psname
b'Times-Bold'
>>> entry.encoding
'/usr/local/texlive/2008/texmf-dist/fonts/enc/dvips/base/8r.enc'
>>> entry.effects
{'slant': 0.16700000000000001}
>>> entry.filename
Definition at line 821 of file dviread.py.
Member Function Documentation
__getitem__()
matplotlib.dviread.PsfontsMap.__getitem__ (self, texname)
Definition at line 886 of file dviread.py.
__new__()
matplotlib.dviread.PsfontsMap.__new__ (cls, filename)
Definition at line 871 of file dviread.py.
Referenced by matplotlib.path.Path._fast_from_codes_and_verts(), pandas.core.generic.NDFrame._from_mgr(), pandas.core.arrays.string_.StringArray._from_sequence(), scipy.interpolate._fitpack2._BivariateSplineBase._from_tck(), scipy.interpolate._fitpack2.UnivariateSpline._from_tck(), matplotlib.colors.Colormap._get_rgba_and_mask(), pip._vendor.rich.style.Style.clear_meta_and_links(), matplotlib.colors.MultivarColormap.copy(), pip._vendor.rich.style.Style.copy(), pip._vendor.rich.style.Style.from_color(), pip._vendor.rich.json.JSON.from_data(), pip._vendor.rich.style.Style.from_meta(), matplotlib.colors.BivarColormap.lut(), pip._vendor.rich.style.Style.test(), pip._vendor.rich.style.Style.update_link(), and pip._vendor.rich.style.Style.without_color().
_parse_and_cache_line()
matplotlib.dviread.PsfontsMap._parse_and_cache_line (self, line) protected
Parse a line in the font mapping file.
The format is (partially) documented at
http://mirrors.ctan.org/systems/doc/pdftex/manual/pdftex-a.pdf
https://tug.org/texinfohtml/dvips.html#psfonts_002emap
Each line can have the following fields:
- tfmname (first, only required field),
- psname (defaults to tfmname, must come immediately after tfmname if
  present),
- fontflags (integer, must come immediately after psname if present,
  ignored by us),
- special (SlantFont and ExtendFont, only field that is double-quoted),
- fontfile, encodingfile (optional, prefixed by <, <<, or <[; << always
  precedes a font, <[ always precedes an encoding, < can precede either
  but then an encoding file must have extension .enc; < and << also
  request different font subsetting behaviors but we ignore that; < can
  be separated from the filename by whitespace).
special, fontfile, and encodingfile can appear in any order.
Definition at line 902 of file dviread.py.
References _parsed, and matplotlib.dviread.find_tex_file().
Member Data Documentation
__slots__
tuple matplotlib.dviread.PsfontsMap.__slots__ = ('_filename', '_unparsed', '_parsed') static private
Definition at line 865 of file dviread.py.
_filename
matplotlib.dviread.PsfontsMap._filename = os.fsdecode(filename) protected
Definition at line 873 of file dviread.py.
Referenced by pip._vendor.distlib.wheel.Wheel.__init__().
_parsed
dict matplotlib.dviread.PsfontsMap._parsed = {} protected
Definition at line 883 of file dviread.py.
Referenced by _parse_and_cache_line().
_unparsed
dict matplotlib.dviread.PsfontsMap._unparsed = {} protected
Definition at line 879 of file dviread.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/dviread.py