Code Cloning Analysis: pandas.tests.internals.test_internals.TestCanHoldElement Class Reference
pandas.tests.internals.test_internals.TestCanHoldElement Class Reference
Public Member Functions
element (self, request)
test_datetime_block_can_hold_element (self)
test_interval_can_hold_element_emptylist (self, dtype, element)
test_interval_can_hold_element (self, dtype, element)
test_period_can_hold_element_emptylist (self)
test_period_can_hold_element (self, element)
check_can_hold_element (self, obj, elem, bool inplace)
check_series_setitem (self, elem, Index index, bool inplace)
Detailed Description
Definition at line 1229 of file test_internals.py.
Member Function Documentation
check_can_hold_element()
pandas.tests.internals.test_internals.TestCanHoldElement.check_can_hold_element (self, obj, elem, bool inplace)
Definition at line 1341 of file test_internals.py.
Referenced by element().
check_series_setitem()
pandas.tests.internals.test_internals.TestCanHoldElement.check_series_setitem (self, elem, Index index, bool inplace)
Definition at line 1348 of file test_internals.py.
Referenced by element().
element()
pandas.tests.internals.test_internals.TestCanHoldElement.element (self, request)
Functions that take an Index and return an element that should have
blk._can_hold_element(element) for a Block with this index's dtype.
Definition at line 1242 of file test_internals.py.
References check_can_hold_element(), check_series_setitem(), pandas.tests.internals.test_internals.create_block(), and element().
Referenced by element().
test_datetime_block_can_hold_element()
pandas.tests.internals.test_internals.TestCanHoldElement.test_datetime_block_can_hold_element (self)
Definition at line 1249 of file test_internals.py.
test_interval_can_hold_element()
pandas.tests.internals.test_internals.TestCanHoldElement.test_interval_can_hold_element (self, dtype, element)
Definition at line 1288 of file test_internals.py.
test_interval_can_hold_element_emptylist()
pandas.tests.internals.test_internals.TestCanHoldElement.test_interval_can_hold_element_emptylist (self, dtype, element)
Definition at line 1279 of file test_internals.py.
test_period_can_hold_element()
pandas.tests.internals.test_internals.TestCanHoldElement.test_period_can_hold_element (self, element)
Definition at line 1323 of file test_internals.py.
test_period_can_hold_element_emptylist()
pandas.tests.internals.test_internals.TestCanHoldElement.test_period_can_hold_element_emptylist (self)
Definition at line 1317 of file test_internals.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/tests/internals/test_internals.py