Code Cloning Analysis: sklearn.cluster._hdbscan.hdbscan Namespace Reference
sklearn.cluster._hdbscan.hdbscan Namespace Reference
Classes
class HDBSCAN
Functions
_brute_mst (mutual_reachability, min_samples)
_process_mst (min_spanning_tree)
_hdbscan_brute (X, min_samples=5, alpha=None, metric="euclidean", n_jobs=None, copy=False, **metric_params)
_hdbscan_prims (X, algo, min_samples=5, alpha=1.0, metric="euclidean", leaf_size=40, n_jobs=None, **metric_params)
remap_single_linkage_tree (tree, internal_to_raw, non_finite)
_get_finite_row_indices (matrix)
Variables
FAST_METRICS = set(KDTree.valid_metrics + BallTree.valid_metrics)
dict _OUTLIER_ENCODING
Detailed Description
HDBSCAN: Hierarchical Density-Based Spatial Clustering
         of Applications with Noise
Function Documentation
_brute_mst()
sklearn.cluster._hdbscan.hdbscan._brute_mst (mutual_reachability, min_samples) protected
Builds a minimum spanning tree (MST) from the provided mutual-reachability
values. This function dispatches to a custom Cython implementation for
dense arrays, and `scipy.sparse.csgraph.minimum_spanning_tree` for sparse
arrays/matrices.
Parameters
----------
mututal_reachability_graph: {ndarray, sparse matrix} of shape \
        (n_samples, n_samples)
    Weighted adjacency matrix of the mutual reachability graph.
min_samples : int, default=None
    The number of samples in a neighborhood for a point
    to be considered as a core point. This includes the point itself.
Returns
-------
mst : ndarray of shape (n_samples - 1,), dtype=MST_edge_dtype
    The MST representation of the mutual-reachability graph. The MST is
    represented as a collection of edges.
Definition at line 83 of file hdbscan.py.
Referenced by _hdbscan_brute().
_get_finite_row_indices()
sklearn.cluster._hdbscan.hdbscan._get_finite_row_indices (matrix) protected
Returns the indices of the purely finite rows of a
sparse matrix or dense ndarray
Definition at line 405 of file hdbscan.py.
Referenced by sklearn.cluster._hdbscan.hdbscan.HDBSCAN.fit().
_hdbscan_brute()
sklearn.cluster._hdbscan.hdbscan._hdbscan_brute (X, min_samples = 5, alpha = None, metric = "euclidean", n_jobs = None, copy = False, ** metric_params) protected
Builds a single-linkage tree (SLT) from the input data `X`. If
`metric="precomputed"` then `X` must be a symmetric array of distances.
Otherwise, the pairwise distances are calculated directly and passed to
`mutual_reachability_graph`.
Parameters
----------
X : ndarray of shape (n_samples, n_features) or (n_samples, n_samples)
    Either the raw data from which to compute the pairwise distances,
    or the precomputed distances.
min_samples : int, default=None
    The number of samples in a neighborhood for a point
    to be considered as a core point. This includes the point itself.
alpha : float, default=1.0
    A distance scaling parameter as used in robust single linkage.
metric : str or callable, default='euclidean'
    The metric to use when calculating distance between instances in a
    feature array.
    - If metric is a string or callable, it must be one of
      the options allowed by :func:`~sklearn.metrics.pairwise_distances`
      for its metric parameter.
    - If metric is "precomputed", X is assumed to be a distance matrix and
      must be square.
n_jobs : int, default=None
    The number of jobs to use for computing the pairwise distances. This
    works by breaking down the pairwise matrix into n_jobs even slices and
    computing them in parallel. This parameter is passed directly to
    :func:`~sklearn.metrics.pairwise_distances`.
    ``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.
    ``-1`` means using all processors. See :term:`Glossary <n_jobs>`
    for more details.
copy : bool, default=False
    If `copy=True` then any time an in-place modifications would be made
    that would overwrite `X`, a copy will first be made, guaranteeing that
    the original data will be unchanged. Currently, it only applies when
    `metric="precomputed"`, when passing a dense array or a CSR sparse
    array/matrix.
metric_params : dict, default=None
    Arguments passed to the distance metric.
Returns
-------
single_linkage : ndarray of shape (n_samples - 1,), dtype=HIERARCHY_dtype
    The single-linkage tree tree (dendrogram) built from the MST.
Definition at line 167 of file hdbscan.py.
References _brute_mst(), and _process_mst().
_hdbscan_prims()
sklearn.cluster._hdbscan.hdbscan._hdbscan_prims (X, algo, min_samples = 5, alpha = 1.0, metric = "euclidean", leaf_size = 40, n_jobs = None, ** metric_params) protected
Builds a single-linkage tree (SLT) from the input data `X`. If
`metric="precomputed"` then `X` must be a symmetric array of distances.
Otherwise, the pairwise distances are calculated directly and passed to
`mutual_reachability_graph`.
Parameters
----------
X : ndarray of shape (n_samples, n_features)
    The raw data.
min_samples : int, default=None
    The number of samples in a neighborhood for a point
    to be considered as a core point. This includes the point itself.
alpha : float, default=1.0
    A distance scaling parameter as used in robust single linkage.
metric : str or callable, default='euclidean'
    The metric to use when calculating distance between instances in a
    feature array. `metric` must be one of the options allowed by
    :func:`~sklearn.metrics.pairwise_distances` for its metric
    parameter.
n_jobs : int, default=None
    The number of jobs to use for computing the pairwise distances. This
    works by breaking down the pairwise matrix into n_jobs even slices and
    computing them in parallel. This parameter is passed directly to
    :func:`~sklearn.metrics.pairwise_distances`.
    ``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.
    ``-1`` means using all processors. See :term:`Glossary <n_jobs>`
    for more details.
copy : bool, default=False
    If `copy=True` then any time an in-place modifications would be made
    that would overwrite `X`, a copy will first be made, guaranteeing that
    the original data will be unchanged. Currently, it only applies when
    `metric="precomputed"`, when passing a dense array or a CSR sparse
    array/matrix.
metric_params : dict, default=None
    Arguments passed to the distance metric.
Returns
-------
single_linkage : ndarray of shape (n_samples - 1,), dtype=HIERARCHY_dtype
    The single-linkage tree tree (dendrogram) built from the MST.
Definition at line 278 of file hdbscan.py.
References _process_mst().
_process_mst()
sklearn.cluster._hdbscan.hdbscan._process_mst (min_spanning_tree) protected
Builds a single-linkage tree (SLT) from the provided minimum spanning tree
(MST). The MST is first sorted then processed by a custom Cython routine.
Parameters
----------
min_spanning_tree : ndarray of shape (n_samples - 1,), dtype=MST_edge_dtype
    The MST representation of the mutual-reachability graph. The MST is
    represented as a collection of edges.
Returns
-------
single_linkage : ndarray of shape (n_samples - 1,), dtype=HIERARCHY_dtype
    The single-linkage tree tree (dendrogram) built from the MST.
Definition at line 144 of file hdbscan.py.
Referenced by _hdbscan_brute(), and _hdbscan_prims().
remap_single_linkage_tree()
sklearn.cluster._hdbscan.hdbscan.remap_single_linkage_tree (tree, internal_to_raw, non_finite)
Takes an internal single_linkage_tree structure and adds back in a set of points
that were initially detected as non-finite and returns that new tree.
These points will all be merged into the final node at np.inf distance and
considered noise points.
Parameters
----------
tree : ndarray of shape (n_samples - 1,), dtype=HIERARCHY_dtype
    The single-linkage tree tree (dendrogram) built from the MST.
internal_to_raw: dict
    A mapping from internal integer index to the raw integer index
non_finite : ndarray
    Boolean array of which entries in the raw data are non-finite
Definition at line 360 of file hdbscan.py.
Referenced by sklearn.cluster._hdbscan.hdbscan.HDBSCAN.fit().
Variable Documentation
_OUTLIER_ENCODING
dict sklearn.cluster._hdbscan.hdbscan._OUTLIER_ENCODING protected
Initial value:
=  {
    "infinite": {
        "label": -2,
        # The probability could also be 1, since infinite points are certainly
        # infinite outliers, however 0 is convention from the HDBSCAN library
        # implementation.
        "prob": 0,
    },
    "missing": {
        "label": -3,
        # A nan probability is chosen to emphasize the fact that the
        # corresponding data was not considered in the clustering problem.
        "prob": np.nan,
    },
}
Definition at line 66 of file hdbscan.py.
FAST_METRICS
sklearn.cluster._hdbscan.hdbscan.FAST_METRICS = set(KDTree.valid_metrics + BallTree.valid_metrics)
Definition at line 61 of file hdbscan.py.