Code Cloning Analysis: sklearn.compose._column_transformer Namespace Reference
sklearn.compose._column_transformer Namespace Reference
Classes
class ColumnTransformer
class make_column_selector
Functions
_check_X (X)
_is_empty_column_selection (column)
_get_transformer_list (estimators)
make_column_transformer (*transformers, remainder="drop", sparse_threshold=0.3, n_jobs=None, verbose=False, verbose_feature_names_out=True, force_int_remainder_cols="deprecated")
str _feature_names_out_with_str_format (str transformer_name, str feature_name, str str_format)
Variables
list __all__ = ["ColumnTransformer", "make_column_selector", "make_column_transformer"]
tuple _ERR_MSG_1DCOLUMN
Detailed Description
The :mod:`sklearn.compose._column_transformer` module implements utilities
to work with heterogeneous data and to apply different transformers to
different columns.
Function Documentation
_check_X()
sklearn.compose._column_transformer._check_X (X) protected
Use check_array only when necessary, e.g. on lists and other non-array-likes.
Definition at line 1330 of file _column_transformer.py.
Referenced by sklearn.compose._column_transformer.ColumnTransformer.fit_transform(), and sklearn.compose._column_transformer.ColumnTransformer.transform().
_feature_names_out_with_str_format()
str sklearn.compose._column_transformer._feature_names_out_with_str_format (str transformer_name, str feature_name, str str_format) protected
Definition at line 1594 of file _column_transformer.py.
_get_transformer_list()
sklearn.compose._column_transformer._get_transformer_list (estimators) protected
Construct (name, trans, column) tuples from list
Definition at line 1357 of file _column_transformer.py.
Referenced by make_column_transformer().
_is_empty_column_selection()
sklearn.compose._column_transformer._is_empty_column_selection (column) protected
Return True if the column selection is empty (empty list or all-False
boolean array).
Definition at line 1341 of file _column_transformer.py.
Referenced by sklearn.compose._column_transformer.ColumnTransformer._iter(), and sklearn.compose._column_transformer.ColumnTransformer._update_fitted_transformers().
make_column_transformer()
sklearn.compose._column_transformer.make_column_transformer (* transformers, remainder = "drop", sparse_threshold = 0.3, n_jobs = None, verbose = False, verbose_feature_names_out = True, force_int_remainder_cols = "deprecated")
Construct a ColumnTransformer from the given transformers.
This is a shorthand for the ColumnTransformer constructor; it does not
require, and does not permit, naming the transformers. Instead, they will
be given names automatically based on their types. It also does not allow
weighting with ``transformer_weights``.
Read more in the :ref:`User Guide <make_column_transformer>`.
Parameters
----------
*transformers : tuples
    Tuples of the form (transformer, columns) specifying the
    transformer objects to be applied to subsets of the data.
    transformer : {'drop', 'passthrough'} or estimator
        Estimator must support :term:`fit` and :term:`transform`.
        Special-cased strings 'drop' and 'passthrough' are accepted as
        well, to indicate to drop the columns or to pass them through
        untransformed, respectively.
    columns : str,  array-like of str, int, array-like of int, slice, \
            array-like of bool or callable
        Indexes the data on its second axis. Integers are interpreted as
        positional columns, while strings can reference DataFrame columns
        by name. A scalar string or int should be used where
        ``transformer`` expects X to be a 1d array-like (vector),
        otherwise a 2d array will be passed to the transformer.
        A callable is passed the input data `X` and can return any of the
        above. To select multiple columns by name or dtype, you can use
        :obj:`make_column_selector`.
remainder : {'drop', 'passthrough'} or estimator, default='drop'
    By default, only the specified columns in `transformers` are
    transformed and combined in the output, and the non-specified
    columns are dropped. (default of ``'drop'``).
    By specifying ``remainder='passthrough'``, all remaining columns that
    were not specified in `transformers` will be automatically passed
    through. This subset of columns is concatenated with the output of
    the transformers.
    By setting ``remainder`` to be an estimator, the remaining
    non-specified columns will use the ``remainder`` estimator. The
    estimator must support :term:`fit` and :term:`transform`.
sparse_threshold : float, default=0.3
    If the transformed output consists of a mix of sparse and dense data,
    it will be stacked as a sparse matrix if the density is lower than this
    value. Use ``sparse_threshold=0`` to always return dense.
    When the transformed output consists of all sparse or all dense data,
    the stacked result will be sparse or dense, respectively, and this
    keyword will be ignored.
n_jobs : int, default=None
    Number of jobs to run in parallel.
    ``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.
    ``-1`` means using all processors. See :term:`Glossary <n_jobs>`
    for more details.
verbose : bool, default=False
    If True, the time elapsed while fitting each transformer will be
    printed as it is completed.
verbose_feature_names_out : bool, default=True
    If True, :meth:`ColumnTransformer.get_feature_names_out` will prefix
    all feature names with the name of the transformer that generated that
    feature.
    If False, :meth:`ColumnTransformer.get_feature_names_out` will not
    prefix any feature names and will error if feature names are not
    unique.
    .. versionadded:: 1.0
force_int_remainder_cols : bool, default=True
    This parameter has no effect.
    .. note::
        If you do not access the list of columns for the remainder columns
        in the :attr:`ColumnTransformer.transformers_` fitted attribute,
        you do not need to set this parameter.
    .. versionadded:: 1.5
    .. versionchanged:: 1.7
       The default value for `force_int_remainder_cols` will change from
       `True` to `False` in version 1.7.
    .. deprecated:: 1.7
       `force_int_remainder_cols` is deprecated and will be removed in version 1.9.
Returns
-------
ct : ColumnTransformer
    Returns a :class:`ColumnTransformer` object.
See Also
--------
ColumnTransformer : Class that allows combining the
    outputs of multiple transformer objects used on column subsets
    of the data into a single feature space.
Examples
--------
>>> from sklearn.preprocessing import StandardScaler, OneHotEncoder
>>> from sklearn.compose import make_column_transformer
>>> make_column_transformer(
...     (StandardScaler(), ['numerical_column']),
...     (OneHotEncoder(), ['categorical_column']))
ColumnTransformer(transformers=[('standardscaler', StandardScaler(...),
                                 ['numerical_column']),
                                ('onehotencoder', OneHotEncoder(...),
                                 ['categorical_column'])])
Definition at line 1371 of file _column_transformer.py.
References _get_transformer_list().
Variable Documentation
__all__
list sklearn.compose._column_transformer.__all__ = ["ColumnTransformer", "make_column_selector", "make_column_transformer"] private
Definition at line 53 of file _column_transformer.py.
_ERR_MSG_1DCOLUMN
tuple sklearn.compose._column_transformer._ERR_MSG_1DCOLUMN protected
Initial value:
=  (
    "1D data passed to a transformer that expects 2D data. "
    "Try to specify the column selection as a list of one "
    "item instead of a scalar."
)
Definition at line 56 of file _column_transformer.py.