Code Cloning Analysis: matplotlib.backends.backend_pdf Namespace Reference
matplotlib.backends.backend_pdf Namespace Reference
Classes
class _BackendPdf
class FigureCanvasPdf
class GraphicsContextPdf
class Name
class Op
class PdfFile
class PdfPages
class Reference
class RendererPdf
class Stream
class Verbatim
Functions
_fill (strings, linelen=75)
_create_pdf_info_dict (backend, metadata)
_datetime_to_pdf (d)
_calculate_quad_point_coordinates (x, y, width, height, angle=0)
_get_coordinates_of_block (x, y, width, height, angle=0)
_get_link_annotation (gc, x, y, width, height, angle=0)
pdfRepr (obj)
_font_supports_glyph (fonttype, glyph)
_get_pdf_charprocs (font_path, glyph_ids)
Variables
_log = logging.getLogger(__name__)
_str_escapes
FigureManagerPdf = FigureManagerBase
Detailed Description
A PDF Matplotlib backend.
Author: Jouni K Seppänen <jks@iki.fi> and others.
Function Documentation
_calculate_quad_point_coordinates()
matplotlib.backends.backend_pdf._calculate_quad_point_coordinates (x, y, width, height, angle = 0) protected
Calculate the coordinates of rectangle when rotated by angle around x, y
Definition at line 228 of file backend_pdf.py.
Referenced by _get_coordinates_of_block().
_create_pdf_info_dict()
matplotlib.backends.backend_pdf._create_pdf_info_dict (backend, metadata) protected
Create a PDF infoDict based on user-supplied metadata.
A default ``Creator``, ``Producer``, and ``CreationDate`` are added, though
the user metadata may override it. The date may be the current time, or a
time set by the ``SOURCE_DATE_EPOCH`` environment variable.
Metadata is verified to have the correct keys and their expected types. Any
unknown keys/types will raise a warning.
Parameters
----------
backend : str
    The name of the backend to use in the Producer value.
metadata : dict[str, Union[str, datetime, Name]]
    A dictionary of metadata supplied by the user with information
    following the PDF specification, also defined in
    `~.backend_pdf.PdfPages` below.
    If any value is *None*, then the key will be removed. This can be used
    to remove any pre-defined values.
Returns
-------
dict[str, Union[str, datetime, Name]]
    A validated dictionary of metadata.
Definition at line 117 of file backend_pdf.py.
Referenced by matplotlib.backends.backend_pdf.PdfFile.__init__().
_datetime_to_pdf()
matplotlib.backends.backend_pdf._datetime_to_pdf (d) protected
Convert a datetime to a PDF string representing it.
Used for PDF and PGF.
Definition at line 204 of file backend_pdf.py.
Referenced by pdfRepr().
_fill()
matplotlib.backends.backend_pdf._fill (strings, linelen = 75) protected
Make one string from sequence of strings, with whitespace in between.
The whitespace is chosen to form lines of at most *linelen* characters,
if possible.
Definition at line 95 of file backend_pdf.py.
Referenced by matplotlib.backends.backend_pdf.PdfFile.close(), and pdfRepr().
_font_supports_glyph()
matplotlib.backends.backend_pdf._font_supports_glyph (fonttype, glyph) protected
Returns True if the font is able to provide codepoint *glyph* in a PDF.
For a Type 3 font, this method returns True only for single-byte
characters. For Type 42 fonts this method return True if the character is
from the Basic Multilingual Plane.
Definition at line 372 of file backend_pdf.py.
Referenced by matplotlib.backends.backend_pdf.RendererPdf.draw_gouraud_triangles(), matplotlib.backends.backend_pdf.RendererPdf.draw_text(), and matplotlib.backends.backend_pdf.PdfFile.embedTTF().
_get_coordinates_of_block()
matplotlib.backends.backend_pdf._get_coordinates_of_block (x, y, width, height, angle = 0) protected
Get the coordinates of rotated rectangle and rectangle that covers the
rotated rectangle.
Definition at line 245 of file backend_pdf.py.
References _calculate_quad_point_coordinates().
Referenced by _get_link_annotation().
_get_link_annotation()
matplotlib.backends.backend_pdf._get_link_annotation (gc, x, y, width, height, angle = 0) protected
Create a link annotation object for embedding URLs.
Definition at line 269 of file backend_pdf.py.
References _get_coordinates_of_block().
Referenced by matplotlib.backends.backend_pdf.RendererPdf.draw_gouraud_triangles(), matplotlib.backends.backend_pdf.RendererPdf.draw_tex(), and matplotlib.backends.backend_pdf.RendererPdf.draw_text().
_get_pdf_charprocs()
matplotlib.backends.backend_pdf._get_pdf_charprocs (font_path, glyph_ids) protected
Definition at line 614 of file backend_pdf.py.
pdfRepr()
matplotlib.backends.backend_pdf.pdfRepr (obj)
Map Python objects to PDF syntax.
Definition at line 299 of file backend_pdf.py.
References _datetime_to_pdf(), _fill(), and pdfRepr().
Referenced by matplotlib.backends.backend_pdf.Stream.__init__(), matplotlib.backends.backend_pdf.PdfFile.close(), pdfRepr(), and matplotlib.backends.backend_pdf.PdfFile.writeTrailer().
Variable Documentation
_log
matplotlib.backends.backend_pdf._log = logging.getLogger(__name__) protected
Definition at line 45 of file backend_pdf.py.
_str_escapes
matplotlib.backends.backend_pdf._str_escapes protected
Initial value:
=  str.maketrans({
    '\\': '\\\\', '(': '\\(', ')': '\\)', '\n': '\\n', '\r': '\\r'})
Definition at line 295 of file backend_pdf.py.
FigureManagerPdf
matplotlib.backends.backend_pdf.FigureManagerPdf = FigureManagerBase
Definition at line 2801 of file backend_pdf.py.