Code Cloning Analysis: scipy.sparse._base Namespace Reference
scipy.sparse._base Namespace Reference
Classes
class _spbase
class sparray
class SparseEfficiencyWarning
class SparseFormatWarning
class SparseWarning
Functions
issparse (x)
isspmatrix (x)
Variables
list __all__
dict _formats
_ufuncs_with_fixed_point_at_zero
int MAXPRINT = 50
Detailed Description
Base class for sparse matrices
Function Documentation
issparse()
scipy.sparse._base.issparse (x)
Is `x` of a sparse array type?
Parameters
----------
x
    object to check for being a sparse array
Returns
-------
bool
    True if `x` is a sparse array or a sparse matrix, False otherwise
Examples
--------
>>> import numpy as np
>>> from scipy.sparse import csr_array, csr_matrix, issparse
>>> issparse(csr_matrix([[5]]))
True
>>> issparse(csr_array([[5]]))
True
>>> issparse(np.array([[5]]))
False
>>> issparse(5)
False
Definition at line 1461 of file _base.py.
Referenced by scipy.sparse._base._spbase._divide(), scipy.sparse.linalg._eigen.arpack.arpack._fast_spmatrix_to_csc(), scipy.sparse._lil._lil_base._get_row_ranges(), scipy.sparse._compressed._cs_matrix._maximum_minimum(), scipy.sparse._base._spbase._mul_dispatch(), scipy.sparse.linalg._matfuncs._onenorm_matrix_power_nnm(), scipy.sparse._index.IndexMixin._raise_on_1d_array_slice(), scipy.sparse.linalg._interface.LinearOperator._rdot(), scipy.sparse._compressed._cs_matrix._scalar_binopt(), scipy.sparse.linalg._matfuncs._smart_matrix_product(), scipy.sparse.linalg._matfuncs._solve_P_Q(), scipy.sparse._index._unpack_index(), scipy.sparse._construct.block_diag(), scipy.sparse._spfuncs.count_blocks(), scipy.sparse.linalg._interface.LinearOperator.dot(), scipy.sparse.linalg._eigen.arpack.arpack.eigs(), scipy.sparse.linalg._eigen.arpack.arpack.eigsh(), scipy.sparse._spfuncs.estimate_blocksize(), scipy.sparse.linalg._matfuncs.expm(), scipy.sparse.linalg._dsolve.linsolve.factorized(), scipy.sparse._dok._dok_base.get(), scipy.sparse.csgraph._laplacian.laplacian(), scipy.sparse.linalg._eigen.lobpcg.lobpcg.lobpcg(), scipy.sparse.linalg._interface.LinearOperator.matmat(), scipy.sparse._compressed._cs_matrix.multiply(), scipy.sparse.linalg._norm.norm(), scipy.sparse._base._spbase.power(), scipy.sparse.linalg._interface.LinearOperator.rmatmat(), scipy.sparse.linalg._dsolve.linsolve.spilu(), scipy.sparse.linalg._dsolve.linsolve.splu(), scipy.sparse.linalg._dsolve.linsolve.spsolve(), scipy.sparse.linalg._dsolve.linsolve.spsolve_triangular(), and scipy.sparse.csgraph._validation.validate_graph().
isspmatrix()
scipy.sparse._base.isspmatrix (x)
Is `x` of a sparse matrix type?
Parameters
----------
x
    object to check for being a sparse matrix
Returns
-------
bool
    True if `x` is a sparse matrix, False otherwise
Examples
--------
>>> import numpy as np
>>> from scipy.sparse import csr_array, csr_matrix, isspmatrix
>>> isspmatrix(csr_matrix([[5]]))
True
>>> isspmatrix(csr_array([[5]]))
False
>>> isspmatrix(np.array([[5]]))
False
>>> isspmatrix(5)
False
Definition at line 1490 of file _base.py.
Variable Documentation
__all__
list scipy.sparse._base.__all__ private
Initial value:
=  ['isspmatrix', 'issparse', 'sparray',
           'SparseWarning', 'SparseEfficiencyWarning']
Definition at line 12 of file _base.py.
_formats
dict scipy.sparse._base._formats protected
Initial value:
=  {'csc': [0, "Compressed Sparse Column"],
            'csr': [1, "Compressed Sparse Row"],
            'dok': [2, "Dictionary Of Keys"],
            'lil': [3, "List of Lists"],
            'dod': [4, "Dictionary of Dictionaries"],
            'sss': [5, "Symmetric Sparse Skyline"],
            'coo': [6, "COOrdinate"],
            'lba': [7, "Linpack BAnded"],
            'egd': [8, "Ellpack-itpack Generalized Diagonal"],
            'dia': [9, "DIAgonal"],
            'bsr': [10, "Block Sparse Row"],
            'msr': [11, "Modified compressed Sparse Row"],
            'bsc': [12, "Block Sparse Column"],
            'msc': [13, "Modified compressed Sparse Column"],
            'ssk': [14, "Symmetric SKyline"],
            'nsk': [15, "Nonsymmetric SKyline"],
            'jad': [16, "JAgged Diagonal"],
            'uss': [17, "Unsymmetric Sparse Skyline"],
            'vbr': [18, "Variable Block Row"],
            'und': [19, "Undefined"]
            }
Definition at line 29 of file _base.py.
_ufuncs_with_fixed_point_at_zero
scipy.sparse._base._ufuncs_with_fixed_point_at_zero protected
Initial value:
=  frozenset([
        np.sin, np.tan, np.arcsin, np.arctan, np.sinh, np.tanh, np.arcsinh,
        np.arctanh, np.rint, np.sign, np.expm1, np.log1p, np.deg2rad,
        np.rad2deg, np.floor, np.ceil, np.trunc, np.sqrt])
Definition at line 53 of file _base.py.
MAXPRINT
int scipy.sparse._base.MAXPRINT = 50
Definition at line 59 of file _base.py.