Code Cloning Analysis: scipy.optimize.tests.test_differentiable_functions.ExVectorialFunction Class Reference
scipy.optimize.tests.test_differentiable_functions.ExVectorialFunction Class Reference
Public Member Functions
__init__ (self)
fun (self, x)
jac (self, x)
hess (self, x, v)
Public Attributes
int nfev = 0
int njev = 0
int nhev = 0
Detailed Description
Definition at line 366 of file test_differentiable_functions.py.
Constructor & Destructor Documentation
__init__()
scipy.optimize.tests.test_differentiable_functions.ExVectorialFunction.__init__ (self)
Definition at line 368 of file test_differentiable_functions.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
fun()
scipy.optimize.tests.test_differentiable_functions.ExVectorialFunction.fun (self, x)
Definition at line 373 of file test_differentiable_functions.py.
hess()
scipy.optimize.tests.test_differentiable_functions.ExVectorialFunction.hess (self, x, v)
Definition at line 383 of file test_differentiable_functions.py.
jac()
scipy.optimize.tests.test_differentiable_functions.ExVectorialFunction.jac (self, x)
Definition at line 378 of file test_differentiable_functions.py.
Referenced by scipy.optimize.tests.test_slsqp.TestSLSQP.fprime_ieqcon2(), and scipy.optimize.tests.test_slsqp.TestSLSQP.jac().
Member Data Documentation
nfev
int scipy.optimize.tests.test_differentiable_functions.ExVectorialFunction.nfev = 0
Definition at line 369 of file test_differentiable_functions.py.
nhev
int scipy.optimize.tests.test_differentiable_functions.ExVectorialFunction.nhev = 0
Definition at line 371 of file test_differentiable_functions.py.
njev
int scipy.optimize.tests.test_differentiable_functions.ExVectorialFunction.njev = 0
Definition at line 370 of file test_differentiable_functions.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/optimize/tests/test_differentiable_functions.py