Code Cloning Analysis: fontTools.misc.xmlWriter Namespace Reference
fontTools.misc.xmlWriter Namespace Reference
Classes
class XMLWriter
Functions
escape (data)
escapeattr (data)
escape8bit (data)
hexStr (s)
Variables
str INDENT = " "
TTX_LOG = logging.getLogger("fontTools.ttx")
str REPLACEMENT = "?"
ILLEGAL_XML_CHARS
Detailed Description
xmlWriter.py -- Simple XML authoring class
Function Documentation
escape()
fontTools.misc.xmlWriter.escape (data)
Escape characters not allowed in `XML 1.0 <https://www.w3.org/TR/xml/#NT-Char>`_.
Definition at line 184 of file xmlWriter.py.
References escape().
Referenced by fontTools.misc.xmlWriter.XMLWriter._writeraw(), escape(), fontTools.misc.xmlWriter.XMLWriter.write(), and fontTools.misc.xmlWriter.XMLWriter.write_noindent().
escape8bit()
fontTools.misc.xmlWriter.escape8bit (data)
Input is Unicode string.
Definition at line 212 of file xmlWriter.py.
Referenced by fontTools.misc.xmlWriter.XMLWriter.write8bit().
escapeattr()
fontTools.misc.xmlWriter.escapeattr (data)
Definition at line 206 of file xmlWriter.py.
hexStr()
fontTools.misc.xmlWriter.hexStr (s)
Definition at line 225 of file xmlWriter.py.
Variable Documentation
ILLEGAL_XML_CHARS
fontTools.misc.xmlWriter.ILLEGAL_XML_CHARS
Initial value:
=  dict.fromkeys(
    itertools.chain(
        range(0x00, 0x09),
        (0x0B, 0x0C),
        range(0x0E, 0x20),
        range(0xD800, 0xE000),
        (0xFFFE, 0xFFFF),
    ),
    REPLACEMENT,
)
Definition at line 13 of file xmlWriter.py.
INDENT
str fontTools.misc.xmlWriter.INDENT = " "
Definition at line 10 of file xmlWriter.py.
REPLACEMENT
str fontTools.misc.xmlWriter.REPLACEMENT = "?"
Definition at line 12 of file xmlWriter.py.
TTX_LOG
fontTools.misc.xmlWriter.TTX_LOG = logging.getLogger("fontTools.ttx")
Definition at line 11 of file xmlWriter.py.