Code Cloning Analysis: sklearn.metrics.tests.test_classification Namespace Reference
sklearn.metrics.tests.test_classification Namespace Reference
Functions
make_prediction (dataset=None, binary=False)
Utilities for testing.
test_classification_report_dictionary_output ()
Tests.
test_classification_report_output_dict_empty_input ()
test_classification_report_zero_division_warning (zero_division)
test_classification_report_labels_subset_superset (labels, show_micro_avg)
test_multilabel_accuracy_score_subset_accuracy ()
test_precision_recall_f1_score_binary ()
test_precision_recall_f_binary_single_class ()
test_precision_recall_f_extra_labels ()
test_precision_recall_f_ignored_labels ()
test_average_precision_score_non_binary_class ()
test_average_precision_score_duplicate_values (y_true, y_score)
test_average_precision_score_tied_values (y_true, y_score)
test_precision_recall_f_unused_pos_label ()
test_confusion_matrix_binary ()
test_multilabel_confusion_matrix_binary ()
test_multilabel_confusion_matrix_multiclass ()
test_multilabel_confusion_matrix_multilabel (csc_container, csr_container)
test_multilabel_confusion_matrix_errors ()
test_confusion_matrix_normalize (normalize, cm_dtype, expected_results)
test_confusion_matrix_normalize_single_class ()
test_confusion_matrix_single_label ()
test_likelihood_ratios_warnings (params, warn_msg)
test_likelihood_ratios_errors (params, err_msg)
test_likelihood_ratios ()
test_likelihood_ratios_raise_warning_deprecation (raise_warning)
test_likelihood_ratios_replace_undefined_by_worst ()
test_likelihood_ratios_wrong_dict_replace_undefined_by (replace_undefined_by)
test_likelihood_ratios_replace_undefined_by_0_fp (replace_undefined_by, expected)
test_likelihood_ratios_replace_undefined_by_0_tn (replace_undefined_by, expected)
test_cohen_kappa ()
test_cohen_kappa_score_error_wrong_label ()
test_zero_division_nan_no_warning (metric, y_true, y_pred, zero_division)
test_zero_division_nan_warning (metric, y_true, y_pred)
test_matthews_corrcoef_against_numpy_corrcoef (global_random_seed)
test_matthews_corrcoef_against_jurman (global_random_seed)
test_matthews_corrcoef (global_random_seed)
test_matthews_corrcoef_multiclass (global_random_seed)
test_matthews_corrcoef_overflow (n_points, global_random_seed)
test_precision_recall_f1_score_multiclass ()
test_precision_refcall_f1_score_multilabel_unordered_labels (average)
test_precision_recall_f1_score_binary_averaged ()
test_zero_precision_recall ()
test_confusion_matrix_multiclass_subset_labels ()
test_confusion_matrix_error (labels, err_msg)
test_confusion_matrix_on_zero_length_input (labels)
test_confusion_matrix_dtype ()
test_confusion_matrix_pandas_nullable (dtype)
test_classification_report_multiclass ()
test_classification_report_multiclass_balanced ()
test_classification_report_multiclass_with_label_detection ()
test_classification_report_multiclass_with_digits ()
test_classification_report_multiclass_with_string_label ()
test_classification_report_multiclass_with_unicode_label ()
test_classification_report_multiclass_with_long_string_label ()
test_classification_report_labels_target_names_unequal_length ()
test_classification_report_no_labels_target_names_unequal_length ()
test_multilabel_classification_report ()
test_multilabel_zero_one_loss_subset ()
test_multilabel_hamming_loss ()
test_jaccard_score_validation ()
test_multilabel_jaccard_score (recwarn)
test_multiclass_jaccard_score (recwarn)
test_average_binary_jaccard_score (recwarn)
test_jaccard_score_zero_division_warning ()
test_jaccard_score_zero_division_set_value (zero_division, expected_score)
test_precision_recall_f1_score_multilabel_1 ()
test_precision_recall_f1_score_multilabel_2 ()
test_precision_recall_f1_score_with_an_empty_prediction (zero_division, zero_division_expected)
test_precision_recall_f1_no_labels (beta, average, zero_division)
test_precision_recall_f1_no_labels_check_warnings (average)
test_precision_recall_f1_no_labels_average_none (zero_division)
test_precision_recall_f1_no_labels_average_none_warn ()
test_prf_warnings ()
test_prf_no_warnings_if_zero_division_set (zero_division)
test_recall_warnings (zero_division)
test_precision_warnings (zero_division)
test_fscore_warnings (zero_division)
test_prf_average_binary_data_non_binary ()
test__check_targets ()
test__check_targets_multiclass_with_both_y_true_and_y_pred_binary ()
test_hinge_loss_binary ()
test_hinge_loss_multiclass ()
test_hinge_loss_multiclass_missing_labels_with_labels_none ()
test_hinge_loss_multiclass_no_consistent_pred_decision_shape ()
test_hinge_loss_multiclass_with_missing_labels ()
test_hinge_loss_multiclass_missing_labels_only_two_unq_in_y_true ()
test_hinge_loss_multiclass_invariance_lists ()
test_log_loss ()
test_log_loss_eps (dtype)
test_log_loss_not_probabilities_warning (dtype)
test_log_loss_perfect_predictions (y_true, y_pred)
test_log_loss_pandas_input ()
test_log_loss_warnings ()
test_brier_score_loss_binary ()
test_brier_score_loss_multiclass ()
test_brier_score_loss_invalid_inputs ()
test_brier_score_loss_warnings ()
test_balanced_accuracy_score_unseen ()
test_balanced_accuracy_score (y_true, y_pred)
test_classification_metric_pos_label_types (metric, classes)
test_f1_for_small_binary_inputs_with_zero_division (y_true, y_pred, expected_score)
test_classification_metric_division_by_zero_nan_validaton (scoring)
test_d2_log_loss_score ()
test_d2_log_loss_score_missing_labels ()
test_d2_log_loss_score_label_order ()
test_d2_log_loss_score_raises ()
Function Documentation
make_prediction()
sklearn.metrics.tests.test_classification.make_prediction (dataset = None, binary = False)
Utilities for testing.
Make some classification predictions on a toy dataset using a SVC
If binary is True restrict to a binary classification problem instead of a
multiclass classification problem
Definition at line 58 of file test_classification.py.
Referenced by test_average_precision_score_duplicate_values(), test_classification_report_dictionary_output(), test_classification_report_labels_subset_superset(), test_confusion_matrix_pandas_nullable(), and test_zero_division_nan_warning().
test__check_targets()
sklearn.metrics.tests.test_classification.test__check_targets ()
Definition at line 2470 of file test_classification.py.
test__check_targets_multiclass_with_both_y_true_and_y_pred_binary()
sklearn.metrics.tests.test_classification.test__check_targets_multiclass_with_both_y_true_and_y_pred_binary ()
Definition at line 2568 of file test_classification.py.
test_average_binary_jaccard_score()
sklearn.metrics.tests.test_classification.test_average_binary_jaccard_score (recwarn)
Definition at line 1748 of file test_classification.py.
test_average_precision_score_duplicate_values()
sklearn.metrics.tests.test_classification.test_average_precision_score_duplicate_values (y_true, y_score)
Duplicate values with precision-recall require a different
processing than when computing the AUC of a ROC, because the
precision-recall curve is a decreasing curve
The following situation corresponds to a perfect
test statistic, the average_precision_score should be 1.
Definition at line 423 of file test_classification.py.
References make_prediction().
test_average_precision_score_non_binary_class()
sklearn.metrics.tests.test_classification.test_average_precision_score_non_binary_class ()
Test multiclass-multiouptut for `average_precision_score`.
Definition at line 376 of file test_classification.py.
test_average_precision_score_tied_values()
sklearn.metrics.tests.test_classification.test_average_precision_score_tied_values (y_true, y_score)
Definition at line 455 of file test_classification.py.
test_balanced_accuracy_score()
sklearn.metrics.tests.test_classification.test_balanced_accuracy_score (y_true, y_pred)
Definition at line 3073 of file test_classification.py.
test_balanced_accuracy_score_unseen()
sklearn.metrics.tests.test_classification.test_balanced_accuracy_score_unseen ()
Definition at line 3059 of file test_classification.py.
test_brier_score_loss_binary()
sklearn.metrics.tests.test_classification.test_brier_score_loss_binary ()
Definition at line 2890 of file test_classification.py.
test_brier_score_loss_invalid_inputs()
sklearn.metrics.tests.test_classification.test_brier_score_loss_invalid_inputs ()
Definition at line 2964 of file test_classification.py.
test_brier_score_loss_multiclass()
sklearn.metrics.tests.test_classification.test_brier_score_loss_multiclass ()
Definition at line 2929 of file test_classification.py.
test_brier_score_loss_warnings()
sklearn.metrics.tests.test_classification.test_brier_score_loss_warnings ()
Definition at line 3040 of file test_classification.py.
test_classification_metric_division_by_zero_nan_validaton()
sklearn.metrics.tests.test_classification.test_classification_metric_division_by_zero_nan_validaton (scoring)
Check that we validate `np.nan` properly for classification metrics.
With `n_jobs=2` in cross-validation, the `np.nan` used for the singleton will be
different in the sub-process and we should not use the `is` operator but
`math.isnan`.
Non-regression test for:
https://github.com/scikit-learn/scikit-learn/issues/27563
Definition at line 3146 of file test_classification.py.
test_classification_metric_pos_label_types()
sklearn.metrics.tests.test_classification.test_classification_metric_pos_label_types (metric, classes)
Check that the metric works with different types of `pos_label`.
We can expect `pos_label` to be a bool, an integer, a float, a string.
No error should be raised for those types.
Definition at line 3101 of file test_classification.py.
test_classification_report_dictionary_output()
sklearn.metrics.tests.test_classification.test_classification_report_dictionary_output ()
Tests.
Definition at line 106 of file test_classification.py.
References make_prediction().
test_classification_report_labels_subset_superset()
sklearn.metrics.tests.test_classification.test_classification_report_labels_subset_superset (labels, show_micro_avg)
Check the behaviour of passing `labels` as a superset or subset of the labels.
WHen a superset, we expect to show the "accuracy" in the report while it should be
the micro-averaging if this is a subset.
Non-regression test for:
https://github.com/scikit-learn/scikit-learn/issues/27927
Definition at line 220 of file test_classification.py.
References make_prediction().
test_classification_report_labels_target_names_unequal_length()
sklearn.metrics.tests.test_classification.test_classification_report_labels_target_names_unequal_length ()
Definition at line 1505 of file test_classification.py.
test_classification_report_multiclass()
sklearn.metrics.tests.test_classification.test_classification_report_multiclass ()
Definition at line 1334 of file test_classification.py.
test_classification_report_multiclass_balanced()
sklearn.metrics.tests.test_classification.test_classification_report_multiclass_balanced ()
Definition at line 1360 of file test_classification.py.
test_classification_report_multiclass_with_digits()
sklearn.metrics.tests.test_classification.test_classification_report_multiclass_with_digits ()
Definition at line 1398 of file test_classification.py.
test_classification_report_multiclass_with_label_detection()
sklearn.metrics.tests.test_classification.test_classification_report_multiclass_with_label_detection ()
Definition at line 1378 of file test_classification.py.
test_classification_report_multiclass_with_long_string_label()
sklearn.metrics.tests.test_classification.test_classification_report_multiclass_with_long_string_label ()
Definition at line 1482 of file test_classification.py.
test_classification_report_multiclass_with_string_label()
sklearn.metrics.tests.test_classification.test_classification_report_multiclass_with_string_label ()
Definition at line 1425 of file test_classification.py.
test_classification_report_multiclass_with_unicode_label()
sklearn.metrics.tests.test_classification.test_classification_report_multiclass_with_unicode_label ()
Definition at line 1460 of file test_classification.py.
test_classification_report_no_labels_target_names_unequal_length()
sklearn.metrics.tests.test_classification.test_classification_report_no_labels_target_names_unequal_length ()
Definition at line 1515 of file test_classification.py.
test_classification_report_output_dict_empty_input()
sklearn.metrics.tests.test_classification.test_classification_report_output_dict_empty_input ()
Definition at line 171 of file test_classification.py.
test_classification_report_zero_division_warning()
sklearn.metrics.tests.test_classification.test_classification_report_zero_division_warning (zero_division)
Definition at line 202 of file test_classification.py.
test_cohen_kappa()
sklearn.metrics.tests.test_classification.test_cohen_kappa ()
Definition at line 879 of file test_classification.py.
test_cohen_kappa_score_error_wrong_label()
sklearn.metrics.tests.test_classification.test_cohen_kappa_score_error_wrong_label ()
Test that correct error is raised when users pass labels that are not in y1.
Definition at line 910 of file test_classification.py.
test_confusion_matrix_binary()
sklearn.metrics.tests.test_classification.test_confusion_matrix_binary ()
Definition at line 482 of file test_classification.py.
test_confusion_matrix_dtype()
sklearn.metrics.tests.test_classification.test_confusion_matrix_dtype ()
Definition at line 1289 of file test_classification.py.
test_confusion_matrix_error()
sklearn.metrics.tests.test_classification.test_confusion_matrix_error (labels, err_msg)
Definition at line 1273 of file test_classification.py.
test_confusion_matrix_multiclass_subset_labels()
sklearn.metrics.tests.test_classification.test_confusion_matrix_multiclass_subset_labels ()
Definition at line 1246 of file test_classification.py.
test_confusion_matrix_normalize()
sklearn.metrics.tests.test_classification.test_confusion_matrix_normalize (normalize, cm_dtype, expected_results)
Definition at line 631 of file test_classification.py.
test_confusion_matrix_normalize_single_class()
sklearn.metrics.tests.test_classification.test_confusion_matrix_normalize_single_class ()
Definition at line 639 of file test_classification.py.
test_confusion_matrix_on_zero_length_input()
sklearn.metrics.tests.test_classification.test_confusion_matrix_on_zero_length_input (labels)
Definition at line 1282 of file test_classification.py.
test_confusion_matrix_pandas_nullable()
sklearn.metrics.tests.test_classification.test_confusion_matrix_pandas_nullable (dtype)
Checks that confusion_matrix works with pandas nullable dtypes.
Non-regression test for gh-25635.
Definition at line 1317 of file test_classification.py.
References make_prediction().
test_confusion_matrix_single_label()
sklearn.metrics.tests.test_classification.test_confusion_matrix_single_label ()
Test `confusion_matrix` warns when only one label found.
Definition at line 658 of file test_classification.py.
test_d2_log_loss_score()
sklearn.metrics.tests.test_classification.test_d2_log_loss_score ()
Definition at line 3161 of file test_classification.py.
test_d2_log_loss_score_label_order()
sklearn.metrics.tests.test_classification.test_d2_log_loss_score_label_order ()
Check that d2_log_loss_score doesn't depend on the order of the labels.
Definition at line 3340 of file test_classification.py.
test_d2_log_loss_score_missing_labels()
sklearn.metrics.tests.test_classification.test_d2_log_loss_score_missing_labels ()
Check that d2_log_loss_score works when not all labels are present in y_true
non-regression test for https://github.com/scikit-learn/scikit-learn/issues/30713
Definition at line 3311 of file test_classification.py.
test_d2_log_loss_score_raises()
sklearn.metrics.tests.test_classification.test_d2_log_loss_score_raises ()
Test that d2_log_loss_score raises the appropriate errors on
invalid inputs.
Definition at line 3351 of file test_classification.py.
test_f1_for_small_binary_inputs_with_zero_division()
sklearn.metrics.tests.test_classification.test_f1_for_small_binary_inputs_with_zero_division (y_true, y_pred, expected_score)
Check the behaviour of `zero_division` for f1-score.
Non-regression test for:
https://github.com/scikit-learn/scikit-learn/issues/26965
Definition at line 3128 of file test_classification.py.
test_fscore_warnings()
sklearn.metrics.tests.test_classification.test_fscore_warnings (zero_division)
Definition at line 2401 of file test_classification.py.
test_hinge_loss_binary()
sklearn.metrics.tests.test_classification.test_hinge_loss_binary ()
Definition at line 2575 of file test_classification.py.
test_hinge_loss_multiclass()
sklearn.metrics.tests.test_classification.test_hinge_loss_multiclass ()
Definition at line 2585 of file test_classification.py.
test_hinge_loss_multiclass_invariance_lists()
sklearn.metrics.tests.test_classification.test_hinge_loss_multiclass_invariance_lists ()
Definition at line 2715 of file test_classification.py.
test_hinge_loss_multiclass_missing_labels_only_two_unq_in_y_true()
sklearn.metrics.tests.test_classification.test_hinge_loss_multiclass_missing_labels_only_two_unq_in_y_true ()
Definition at line 2683 of file test_classification.py.
test_hinge_loss_multiclass_missing_labels_with_labels_none()
sklearn.metrics.tests.test_classification.test_hinge_loss_multiclass_missing_labels_with_labels_none ()
Definition at line 2612 of file test_classification.py.
test_hinge_loss_multiclass_no_consistent_pred_decision_shape()
sklearn.metrics.tests.test_classification.test_hinge_loss_multiclass_no_consistent_pred_decision_shape ()
Definition at line 2629 of file test_classification.py.
test_hinge_loss_multiclass_with_missing_labels()
sklearn.metrics.tests.test_classification.test_hinge_loss_multiclass_with_missing_labels ()
Definition at line 2657 of file test_classification.py.
test_jaccard_score_validation()
sklearn.metrics.tests.test_classification.test_jaccard_score_validation ()
Definition at line 1594 of file test_classification.py.
test_jaccard_score_zero_division_set_value()
sklearn.metrics.tests.test_classification.test_jaccard_score_zero_division_set_value (zero_division, expected_score)
Definition at line 1787 of file test_classification.py.
test_jaccard_score_zero_division_warning()
sklearn.metrics.tests.test_classification.test_jaccard_score_zero_division_warning ()
Definition at line 1771 of file test_classification.py.
test_likelihood_ratios()
sklearn.metrics.tests.test_classification.test_likelihood_ratios ()
Definition at line 737 of file test_classification.py.
test_likelihood_ratios_errors()
sklearn.metrics.tests.test_classification.test_likelihood_ratios_errors (params, err_msg)
Definition at line 730 of file test_classification.py.
test_likelihood_ratios_raise_warning_deprecation()
sklearn.metrics.tests.test_classification.test_likelihood_ratios_raise_warning_deprecation (raise_warning)
Test that class_likelihood_ratios raises a `FutureWarning` when `raise_warning`
param is set.
Definition at line 764 of file test_classification.py.
test_likelihood_ratios_replace_undefined_by_0_fp()
sklearn.metrics.tests.test_classification.test_likelihood_ratios_replace_undefined_by_0_fp (replace_undefined_by, expected)
Test that the `replace_undefined_by` param returns the right value for the
positive_likelihood_ratio as defined by the user.
Definition at line 833 of file test_classification.py.
test_likelihood_ratios_replace_undefined_by_0_tn()
sklearn.metrics.tests.test_classification.test_likelihood_ratios_replace_undefined_by_0_tn (replace_undefined_by, expected)
Test that the `replace_undefined_by` param returns the right value for the
negative_likelihood_ratio as defined by the user.
Definition at line 861 of file test_classification.py.
test_likelihood_ratios_replace_undefined_by_worst()
sklearn.metrics.tests.test_classification.test_likelihood_ratios_replace_undefined_by_worst ()
Test that class_likelihood_ratios returns the worst scores `1.0` for both LR+ and
LR- when `replace_undefined_by=1` is set.
Definition at line 775 of file test_classification.py.
test_likelihood_ratios_warnings()
sklearn.metrics.tests.test_classification.test_likelihood_ratios_warnings (params, warn_msg)
Definition at line 707 of file test_classification.py.
test_likelihood_ratios_wrong_dict_replace_undefined_by()
sklearn.metrics.tests.test_classification.test_likelihood_ratios_wrong_dict_replace_undefined_by (replace_undefined_by)
Test that class_likelihood_ratios raises a `ValueError` if the input dict for
`replace_undefined_by` is in the wrong format or contains impossible values.
Definition at line 810 of file test_classification.py.
test_log_loss()
sklearn.metrics.tests.test_classification.test_log_loss ()
Definition at line 2743 of file test_classification.py.
test_log_loss_eps()
sklearn.metrics.tests.test_classification.test_log_loss_eps (dtype)
Check the behaviour internal eps that changes depending on the input dtype.
Non-regression test for:
https://github.com/scikit-learn/scikit-learn/issues/24315
Definition at line 2820 of file test_classification.py.
test_log_loss_not_probabilities_warning()
sklearn.metrics.tests.test_classification.test_log_loss_not_probabilities_warning (dtype)
Check that log_loss raises a warning when y_pred values don't sum to 1.
Definition at line 2834 of file test_classification.py.
test_log_loss_pandas_input()
sklearn.metrics.tests.test_classification.test_log_loss_pandas_input ()
Definition at line 2857 of file test_classification.py.
test_log_loss_perfect_predictions()
sklearn.metrics.tests.test_classification.test_log_loss_perfect_predictions (y_true, y_pred)
Check that log_loss returns 0 for perfect predictions.
Definition at line 2851 of file test_classification.py.
test_log_loss_warnings()
sklearn.metrics.tests.test_classification.test_log_loss_warnings ()
Definition at line 2875 of file test_classification.py.
test_matthews_corrcoef()
sklearn.metrics.tests.test_classification.test_matthews_corrcoef (global_random_seed)
Definition at line 1014 of file test_classification.py.
test_matthews_corrcoef_against_jurman()
sklearn.metrics.tests.test_classification.test_matthews_corrcoef_against_jurman (global_random_seed)
Definition at line 975 of file test_classification.py.
test_matthews_corrcoef_against_numpy_corrcoef()
sklearn.metrics.tests.test_classification.test_matthews_corrcoef_against_numpy_corrcoef (global_random_seed)
Definition at line 965 of file test_classification.py.
test_matthews_corrcoef_multiclass()
sklearn.metrics.tests.test_classification.test_matthews_corrcoef_multiclass (global_random_seed)
Definition at line 1049 of file test_classification.py.
test_matthews_corrcoef_overflow()
sklearn.metrics.tests.test_classification.test_matthews_corrcoef_overflow (n_points, global_random_seed)
Definition at line 1106 of file test_classification.py.
test_multiclass_jaccard_score()
sklearn.metrics.tests.test_classification.test_multiclass_jaccard_score (recwarn)
Definition at line 1711 of file test_classification.py.
test_multilabel_accuracy_score_subset_accuracy()
sklearn.metrics.tests.test_classification.test_multilabel_accuracy_score_subset_accuracy ()
Definition at line 240 of file test_classification.py.
test_multilabel_classification_report()
sklearn.metrics.tests.test_classification.test_multilabel_classification_report ()
Definition at line 1530 of file test_classification.py.
test_multilabel_confusion_matrix_binary()
sklearn.metrics.tests.test_classification.test_multilabel_confusion_matrix_binary ()
Definition at line 503 of file test_classification.py.
test_multilabel_confusion_matrix_errors()
sklearn.metrics.tests.test_classification.test_multilabel_confusion_matrix_errors ()
Definition at line 592 of file test_classification.py.
test_multilabel_confusion_matrix_multiclass()
sklearn.metrics.tests.test_classification.test_multilabel_confusion_matrix_multiclass ()
Definition at line 515 of file test_classification.py.
test_multilabel_confusion_matrix_multilabel()
sklearn.metrics.tests.test_classification.test_multilabel_confusion_matrix_multilabel (csc_container, csr_container)
Definition at line 552 of file test_classification.py.
test_multilabel_hamming_loss()
sklearn.metrics.tests.test_classification.test_multilabel_hamming_loss ()
Definition at line 1574 of file test_classification.py.
test_multilabel_jaccard_score()
sklearn.metrics.tests.test_classification.test_multilabel_jaccard_score (recwarn)
Definition at line 1634 of file test_classification.py.
test_multilabel_zero_one_loss_subset()
sklearn.metrics.tests.test_classification.test_multilabel_zero_one_loss_subset ()
Definition at line 1560 of file test_classification.py.
test_precision_recall_f1_no_labels()
sklearn.metrics.tests.test_classification.test_precision_recall_f1_no_labels (beta, average, zero_division)
Definition at line 2033 of file test_classification.py.
test_precision_recall_f1_no_labels_average_none()
sklearn.metrics.tests.test_classification.test_precision_recall_f1_no_labels_average_none (zero_division)
Definition at line 2091 of file test_classification.py.
test_precision_recall_f1_no_labels_average_none_warn()
sklearn.metrics.tests.test_classification.test_precision_recall_f1_no_labels_average_none_warn ()
Definition at line 2126 of file test_classification.py.
test_precision_recall_f1_no_labels_check_warnings()
sklearn.metrics.tests.test_classification.test_precision_recall_f1_no_labels_check_warnings (average)
Definition at line 2071 of file test_classification.py.
test_precision_recall_f1_score_binary()
sklearn.metrics.tests.test_classification.test_precision_recall_f1_score_binary ()
Definition at line 254 of file test_classification.py.
test_precision_recall_f1_score_binary_averaged()
sklearn.metrics.tests.test_classification.test_precision_recall_f1_score_binary_averaged ()
Definition at line 1212 of file test_classification.py.
test_precision_recall_f1_score_multiclass()
sklearn.metrics.tests.test_classification.test_precision_recall_f1_score_multiclass ()
Definition at line 1139 of file test_classification.py.
test_precision_recall_f1_score_multilabel_1()
sklearn.metrics.tests.test_classification.test_precision_recall_f1_score_multilabel_1 ()
Definition at line 1800 of file test_classification.py.
test_precision_recall_f1_score_multilabel_2()
sklearn.metrics.tests.test_classification.test_precision_recall_f1_score_multilabel_2 ()
Definition at line 1867 of file test_classification.py.
test_precision_recall_f1_score_with_an_empty_prediction()
sklearn.metrics.tests.test_classification.test_precision_recall_f1_score_with_an_empty_prediction (zero_division, zero_division_expected)
Definition at line 1936 of file test_classification.py.
test_precision_recall_f_binary_single_class()
sklearn.metrics.tests.test_classification.test_precision_recall_f_binary_single_class ()
Definition at line 289 of file test_classification.py.
test_precision_recall_f_extra_labels()
sklearn.metrics.tests.test_classification.test_precision_recall_f_extra_labels ()
Definition at line 308 of file test_classification.py.
test_precision_recall_f_ignored_labels()
sklearn.metrics.tests.test_classification.test_precision_recall_f_ignored_labels ()
Definition at line 354 of file test_classification.py.
test_precision_recall_f_unused_pos_label()
sklearn.metrics.tests.test_classification.test_precision_recall_f_unused_pos_label ()
Definition at line 466 of file test_classification.py.
test_precision_refcall_f1_score_multilabel_unordered_labels()
sklearn.metrics.tests.test_classification.test_precision_refcall_f1_score_multilabel_unordered_labels (average)
Definition at line 1198 of file test_classification.py.
test_precision_warnings()
sklearn.metrics.tests.test_classification.test_precision_warnings (zero_division)
Definition at line 2361 of file test_classification.py.
test_prf_average_binary_data_non_binary()
sklearn.metrics.tests.test_classification.test_prf_average_binary_data_non_binary ()
Definition at line 2439 of file test_classification.py.
test_prf_no_warnings_if_zero_division_set()
sklearn.metrics.tests.test_classification.test_prf_no_warnings_if_zero_division_set (zero_division)
Definition at line 2259 of file test_classification.py.
test_prf_warnings()
sklearn.metrics.tests.test_classification.test_prf_warnings ()
Definition at line 2154 of file test_classification.py.
test_recall_warnings()
sklearn.metrics.tests.test_classification.test_recall_warnings (zero_division)
Definition at line 2321 of file test_classification.py.
test_zero_division_nan_no_warning()
sklearn.metrics.tests.test_classification.test_zero_division_nan_no_warning (metric, y_true, y_pred, zero_division)
Check the behaviour of `zero_division` when setting to 0, 1 or np.nan.
No warnings should be raised.
Definition at line 932 of file test_classification.py.
test_zero_division_nan_warning()
sklearn.metrics.tests.test_classification.test_zero_division_nan_warning (metric, y_true, y_pred)
Check the behaviour of `zero_division` when setting to "warn".
A `UndefinedMetricWarning` should be raised.
Definition at line 956 of file test_classification.py.
References make_prediction().
test_zero_precision_recall()
sklearn.metrics.tests.test_classification.test_zero_precision_recall ()
Definition at line 1229 of file test_classification.py.