Code Cloning Analysis: matplotlib.dates.ConciseDateConverter Class Reference
matplotlib.dates.ConciseDateConverter Class Reference
Public Member Functions
__init__ (self, formats=None, zero_formats=None, offset_formats=None, show_offset=True, *, interval_multiples=True)
axisinfo (self, unit, axis)
Public Member Functions inherited from matplotlib.dates.DateConverter
__init__ (self, *, interval_multiples=True)
Protected Attributes
_formats = formats
_zero_formats = zero_formats
_offset_formats = offset_formats
_show_offset = show_offset
Protected Attributes inherited from matplotlib.dates.DateConverter
_interval_multiples = interval_multiples
Additional Inherited Members
Static Public Member Functions inherited from matplotlib.dates.DateConverter
convert (value, unit, axis)
default_units (x, axis)
Detailed Description
Definition at line 1785 of file dates.py.
Constructor & Destructor Documentation
__init__()
matplotlib.dates.ConciseDateConverter.__init__ (self, formats = None, zero_formats = None, offset_formats = None, show_offset = True, * , interval_multiples = True)
Definition at line 1788 of file dates.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
axisinfo()
matplotlib.dates.ConciseDateConverter.axisinfo (self, unit, axis)
Return the `~matplotlib.units.AxisInfo` for *unit*.
*unit* is a `~datetime.tzinfo` instance or None.
The *axis* argument is required but not used.
Reimplemented from matplotlib.dates.DateConverter.
Definition at line 1797 of file dates.py.
References _formats, matplotlib.dates.DateConverter._interval_multiples, _offset_formats, _show_offset, and _zero_formats.
Member Data Documentation
_formats
matplotlib.dates.ConciseDateConverter._formats = formats protected
Definition at line 1790 of file dates.py.
Referenced by pip._internal.index.package_finder.LinkEvaluator.__init__(), axisinfo(), and pip._internal.index.package_finder.LinkEvaluator.evaluate_link().
_offset_formats
matplotlib.dates.ConciseDateConverter._offset_formats = offset_formats protected
Definition at line 1792 of file dates.py.
Referenced by axisinfo().
_show_offset
matplotlib.dates.ConciseDateConverter._show_offset = show_offset protected
Definition at line 1793 of file dates.py.
Referenced by axisinfo().
_zero_formats
matplotlib.dates.ConciseDateConverter._zero_formats = zero_formats protected
Definition at line 1791 of file dates.py.
Referenced by axisinfo().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/dates.py