Code Cloning Analysis: numpy.lib.shape_base Namespace Reference
numpy.lib.shape_base Namespace Reference
Functions
_make_along_axis_idx (arr_shape, indices, axis)
_take_along_axis_dispatcher (arr, indices, axis)
take_along_axis (arr, indices, axis)
_put_along_axis_dispatcher (arr, indices, values, axis)
put_along_axis (arr, indices, values, axis)
_apply_along_axis_dispatcher (func1d, axis, arr, *args, **kwargs)
apply_along_axis (func1d, axis, arr, *args, **kwargs)
_apply_over_axes_dispatcher (func, a, axes)
apply_over_axes (func, a, axes)
_expand_dims_dispatcher (a, axis)
expand_dims (a, axis)
_column_stack_dispatcher (tup)
column_stack (tup)
_dstack_dispatcher (tup)
dstack (tup)
_replace_zero_by_x_arrays (sub_arys)
_array_split_dispatcher (ary, indices_or_sections, axis=None)
array_split (ary, indices_or_sections, axis=0)
_split_dispatcher (ary, indices_or_sections, axis=None)
split (ary, indices_or_sections, axis=0)
_hvdsplit_dispatcher (ary, indices_or_sections)
hsplit (ary, indices_or_sections)
vsplit (ary, indices_or_sections)
dsplit (ary, indices_or_sections)
get_array_prepare (*args)
get_array_wrap (*args)
_kron_dispatcher (a, b)
kron (a, b)
_tile_dispatcher (A, reps)
tile (A, reps)
Variables
list __all__
array_function_dispatch
row_stack = vstack
Function Documentation
_apply_along_axis_dispatcher()
numpy.lib.shape_base._apply_along_axis_dispatcher (func1d, axis, arr, * args, ** kwargs) protected
Definition at line 263 of file shape_base.py.
_apply_over_axes_dispatcher()
numpy.lib.shape_base._apply_over_axes_dispatcher (func, a, axes) protected
Definition at line 417 of file shape_base.py.
_array_split_dispatcher()
numpy.lib.shape_base._array_split_dispatcher (ary, indices_or_sections, axis = None) protected
Definition at line 727 of file shape_base.py.
_column_stack_dispatcher()
numpy.lib.shape_base._column_stack_dispatcher (tup) protected
Definition at line 608 of file shape_base.py.
_dstack_dispatcher()
numpy.lib.shape_base._dstack_dispatcher (tup) protected
Definition at line 655 of file shape_base.py.
_expand_dims_dispatcher()
numpy.lib.shape_base._expand_dims_dispatcher (a, axis) protected
Definition at line 508 of file shape_base.py.
_hvdsplit_dispatcher()
numpy.lib.shape_base._hvdsplit_dispatcher (ary, indices_or_sections) protected
Definition at line 869 of file shape_base.py.
_kron_dispatcher()
numpy.lib.shape_base._kron_dispatcher (a, b) protected
Definition at line 1063 of file shape_base.py.
_make_along_axis_idx()
numpy.lib.shape_base._make_along_axis_idx (arr_shape, indices, axis) protected
Definition at line 27 of file shape_base.py.
_put_along_axis_dispatcher()
numpy.lib.shape_base._put_along_axis_dispatcher (arr, indices, values, axis) protected
Definition at line 173 of file shape_base.py.
_replace_zero_by_x_arrays()
numpy.lib.shape_base._replace_zero_by_x_arrays (sub_arys) protected
Definition at line 718 of file shape_base.py.
_split_dispatcher()
numpy.lib.shape_base._split_dispatcher (ary, indices_or_sections, axis = None) protected
Definition at line 787 of file shape_base.py.
_take_along_axis_dispatcher()
numpy.lib.shape_base._take_along_axis_dispatcher (arr, indices, axis) protected
Definition at line 50 of file shape_base.py.
_tile_dispatcher()
numpy.lib.shape_base._tile_dispatcher (A, reps) protected
Definition at line 1181 of file shape_base.py.
apply_along_axis()
numpy.lib.shape_base.apply_along_axis (func1d, axis, arr, * args, ** kwargs)
Apply a function to 1-D slices along the given axis.
Execute `func1d(a, *args, **kwargs)` where `func1d` operates on 1-D arrays
and `a` is a 1-D slice of `arr` along `axis`.
This is equivalent to (but faster than) the following use of `ndindex` and
`s_`, which sets each of ``ii``, ``jj``, and ``kk`` to a tuple of indices::
    Ni, Nk = a.shape[:axis], a.shape[axis+1:]
    for ii in ndindex(Ni):
        for kk in ndindex(Nk):
            f = func1d(arr[ii + s_[:,] + kk])
            Nj = f.shape
            for jj in ndindex(Nj):
                out[ii + jj + kk] = f[jj]
Equivalently, eliminating the inner loop, this can be expressed as::
    Ni, Nk = a.shape[:axis], a.shape[axis+1:]
    for ii in ndindex(Ni):
        for kk in ndindex(Nk):
            out[ii + s_[...,] + kk] = func1d(arr[ii + s_[:,] + kk])
Parameters
----------
func1d : function (M,) -> (Nj...)
    This function should accept 1-D arrays. It is applied to 1-D
    slices of `arr` along the specified axis.
axis : integer
    Axis along which `arr` is sliced.
arr : ndarray (Ni..., M, Nk...)
    Input array.
args : any
    Additional arguments to `func1d`.
kwargs : any
    Additional named arguments to `func1d`.
    .. versionadded:: 1.9.0
Returns
-------
out : ndarray  (Ni..., Nj..., Nk...)
    The output array. The shape of `out` is identical to the shape of
    `arr`, except along the `axis` dimension. This axis is removed, and
    replaced with new dimensions equal to the shape of the return value
    of `func1d`. So if `func1d` returns a scalar `out` will have one
    fewer dimensions than `arr`.
See Also
--------
apply_over_axes : Apply a function repeatedly over multiple axes.
Examples
--------
>>> def my_func(a):
...     \"\"\"Average first and last element of a 1-D array\"\"\"
...     return (a[0] + a[-1]) * 0.5
>>> b = np.array([[1,2,3], [4,5,6], [7,8,9]])
>>> np.apply_along_axis(my_func, 0, b)
array([4., 5., 6.])
>>> np.apply_along_axis(my_func, 1, b)
array([2.,  5.,  8.])
For a function that returns a 1D array, the number of dimensions in
`outarr` is the same as `arr`.
>>> b = np.array([[8,1,7], [4,3,9], [5,2,6]])
>>> np.apply_along_axis(sorted, 1, b)
array([[1, 7, 8],
       [3, 4, 9],
       [2, 5, 6]])
For a function that returns a higher dimensional array, those dimensions
are inserted in place of the `axis` dimension.
>>> b = np.array([[1,2,3], [4,5,6], [7,8,9]])
>>> np.apply_along_axis(np.diag, -1, b)
array([[[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]],
       [[4, 0, 0],
        [0, 5, 0],
        [0, 0, 6]],
       [[7, 0, 0],
        [0, 8, 0],
        [0, 0, 9]]])
Definition at line 268 of file shape_base.py.
References numpy.core.fromnumeric.transpose().
apply_over_axes()
numpy.lib.shape_base.apply_over_axes (func, a, axes)
Apply a function repeatedly over multiple axes.
`func` is called as `res = func(a, axis)`, where `axis` is the first
element of `axes`.  The result `res` of the function call must have
either the same dimensions as `a` or one less dimension.  If `res`
has one less dimension than `a`, a dimension is inserted before
`axis`.  The call to `func` is then repeated for each axis in `axes`,
with `res` as the first argument.
Parameters
----------
func : function
    This function must take two arguments, `func(a, axis)`.
a : array_like
    Input array.
axes : array_like
    Axes over which `func` is applied; the elements must be integers.
Returns
-------
apply_over_axis : ndarray
    The output array.  The number of dimensions is the same as `a`,
    but the shape can be different.  This depends on whether `func`
    changes the shape of its output with respect to its input.
See Also
--------
apply_along_axis :
    Apply a function to 1-D slices of an array along the given axis.
Notes
-----
This function is equivalent to tuple axis arguments to reorderable ufuncs
with keepdims=True. Tuple axis arguments to ufuncs have been available since
version 1.7.0.
Examples
--------
>>> a = np.arange(24).reshape(2,3,4)
>>> a
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],
       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])
Sum over axes 0 and 2. The result has same number of dimensions
as the original array:
>>> np.apply_over_axes(np.sum, a, [0,2])
array([[[ 60],
        [ 92],
        [124]]])
Tuple axis arguments to ufuncs are equivalent:
>>> np.sum(a, axis=(0,2), keepdims=True)
array([[[ 60],
        [ 92],
        [124]]])
Definition at line 422 of file shape_base.py.
References expand_dims().
array_split()
numpy.lib.shape_base.array_split (ary, indices_or_sections, axis = 0)
Split an array into multiple sub-arrays.
Please refer to the ``split`` documentation.  The only difference
between these functions is that ``array_split`` allows
`indices_or_sections` to be an integer that does *not* equally
divide the axis. For an array of length l that should be split
into n sections, it returns l % n sub-arrays of size l//n + 1
and the rest of size l//n.
See Also
--------
split : Split array into multiple sub-arrays of equal size.
Examples
--------
>>> x = np.arange(8.0)
>>> np.array_split(x, 3)
[array([0.,  1.,  2.]), array([3.,  4.,  5.]), array([6.,  7.])]
>>> x = np.arange(9)
>>> np.array_split(x, 4)
[array([0, 1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]
Definition at line 732 of file shape_base.py.
References numpy.core.fromnumeric.cumsum().
Referenced by split(), and numpy.lib.tests.test_shape_base.TestArraySplit.test_integer_split_2D_default().
column_stack()
numpy.lib.shape_base.column_stack (tup)
Stack 1-D arrays as columns into a 2-D array.
Take a sequence of 1-D arrays and stack them as columns
to make a single 2-D array. 2-D arrays are stacked as-is,
just like with `hstack`.  1-D arrays are turned into 2-D columns
first.
Parameters
----------
tup : sequence of 1-D or 2-D arrays.
    Arrays to stack. All of them must have the same first dimension.
Returns
-------
stacked : 2-D array
    The array formed by stacking the given arrays.
See Also
--------
stack, hstack, vstack, concatenate
Examples
--------
>>> a = np.array((1,2,3))
>>> b = np.array((2,3,4))
>>> np.column_stack((a,b))
array([[1, 2],
       [2, 3],
       [3, 4]])
Definition at line 613 of file shape_base.py.
dsplit()
numpy.lib.shape_base.dsplit (ary, indices_or_sections)
Split array into multiple sub-arrays along the 3rd axis (depth).
Please refer to the `split` documentation.  `dsplit` is equivalent
to `split` with ``axis=2``, the array is always split along the third
axis provided the array dimension is greater than or equal to 3.
See Also
--------
split : Split an array into multiple sub-arrays of equal size.
Examples
--------
>>> x = np.arange(16.0).reshape(2, 2, 4)
>>> x
array([[[ 0.,   1.,   2.,   3.],
        [ 4.,   5.,   6.,   7.]],
       [[ 8.,   9.,  10.,  11.],
        [12.,  13.,  14.,  15.]]])
>>> np.dsplit(x, 2)
[array([[[ 0.,  1.],
        [ 4.,  5.]],
       [[ 8.,  9.],
        [12., 13.]]]), array([[[ 2.,  3.],
        [ 6.,  7.]],
       [[10., 11.],
        [14., 15.]]])]
>>> np.dsplit(x, np.array([3, 6]))
[array([[[ 0.,   1.,   2.],
        [ 4.,   5.,   6.]],
       [[ 8.,   9.,  10.],
        [12.,  13.,  14.]]]),
 array([[[ 3.],
        [ 7.]],
       [[11.],
        [15.]]]),
array([], shape=(2, 2, 0), dtype=float64)]
Definition at line 993 of file shape_base.py.
References split().
dstack()
numpy.lib.shape_base.dstack (tup)
Stack arrays in sequence depth wise (along third axis).
This is equivalent to concatenation along the third axis after 2-D arrays
of shape `(M,N)` have been reshaped to `(M,N,1)` and 1-D arrays of shape
`(N,)` have been reshaped to `(1,N,1)`. Rebuilds arrays divided by
`dsplit`.
This function makes most sense for arrays with up to 3 dimensions. For
instance, for pixel-data with a height (first axis), width (second axis),
and r/g/b channels (third axis). The functions `concatenate`, `stack` and
`block` provide more general stacking and concatenation operations.
Parameters
----------
tup : sequence of arrays
    The arrays must have the same shape along all but the third axis.
    1-D or 2-D arrays must have the same shape.
Returns
-------
stacked : ndarray
    The array formed by stacking the given arrays, will be at least 3-D.
See Also
--------
concatenate : Join a sequence of arrays along an existing axis.
stack : Join a sequence of arrays along a new axis.
block : Assemble an nd-array from nested lists of blocks.
vstack : Stack arrays in sequence vertically (row wise).
hstack : Stack arrays in sequence horizontally (column wise).
column_stack : Stack 1-D arrays as columns into a 2-D array.
dsplit : Split array along third axis.
Examples
--------
>>> a = np.array((1,2,3))
>>> b = np.array((2,3,4))
>>> np.dstack((a,b))
array([[[1, 2],
        [2, 3],
        [3, 4]]])
>>> a = np.array([[1],[2],[3]])
>>> b = np.array([[2],[3],[4]])
>>> np.dstack((a,b))
array([[[1, 2]],
       [[2, 3]],
       [[3, 4]]])
Definition at line 660 of file shape_base.py.
References numpy.core.shape_base.atleast_3d().
expand_dims()
numpy.lib.shape_base.expand_dims (a, axis)
Expand the shape of an array.
Insert a new axis that will appear at the `axis` position in the expanded
array shape.
Parameters
----------
a : array_like
    Input array.
axis : int or tuple of ints
    Position in the expanded axes where the new axis (or axes) is placed.
    .. deprecated:: 1.13.0
        Passing an axis where ``axis > a.ndim`` will be treated as
        ``axis == a.ndim``, and passing ``axis < -a.ndim - 1`` will
        be treated as ``axis == 0``. This behavior is deprecated.
    .. versionchanged:: 1.18.0
        A tuple of axes is now supported.  Out of range axes as
        described above are now forbidden and raise an `AxisError`.
Returns
-------
result : ndarray
    View of `a` with the number of dimensions increased.
See Also
--------
squeeze : The inverse operation, removing singleton dimensions
reshape : Insert, remove, and combine dimensions, and resize existing ones
doc.indexing, atleast_1d, atleast_2d, atleast_3d
Examples
--------
>>> x = np.array([1, 2])
>>> x.shape
(2,)
The following is equivalent to ``x[np.newaxis, :]`` or ``x[np.newaxis]``:
>>> y = np.expand_dims(x, axis=0)
>>> y
array([[1, 2]])
>>> y.shape
(1, 2)
The following is equivalent to ``x[:, np.newaxis]``:
>>> y = np.expand_dims(x, axis=1)
>>> y
array([[1],
       [2]])
>>> y.shape
(2, 1)
``axis`` may also be a tuple:
>>> y = np.expand_dims(x, axis=(0, 1))
>>> y
array([[[1, 2]]])
>>> y = np.expand_dims(x, axis=(2, 0))
>>> y
array([[[1],
        [2]]])
Note that some examples may use ``None`` instead of ``np.newaxis``.  These
are the same objects:
>>> np.newaxis is None
True
Definition at line 513 of file shape_base.py.
References numpy.core.numeric.normalize_axis_tuple().
Referenced by numpy.ma.core.MaskedArray.anom(), apply_over_axes(), and kron().
get_array_prepare()
numpy.lib.shape_base.get_array_prepare (* args)
Find the wrapper for the array with the highest priority.
In case of ties, leftmost wins. If no wrapper is found, return None
Definition at line 1037 of file shape_base.py.
get_array_wrap()
numpy.lib.shape_base.get_array_wrap (* args)
Find the wrapper for the array with the highest priority.
In case of ties, leftmost wins. If no wrapper is found, return None
Definition at line 1050 of file shape_base.py.
hsplit()
numpy.lib.shape_base.hsplit (ary, indices_or_sections)
Split an array into multiple sub-arrays horizontally (column-wise).
Please refer to the `split` documentation.  `hsplit` is equivalent
to `split` with ``axis=1``, the array is always split along the second
axis except for 1-D arrays, where it is split at ``axis=0``.
See Also
--------
split : Split an array into multiple sub-arrays of equal size.
Examples
--------
>>> x = np.arange(16.0).reshape(4, 4)
>>> x
array([[ 0.,   1.,   2.,   3.],
       [ 4.,   5.,   6.,   7.],
       [ 8.,   9.,  10.,  11.],
       [12.,  13.,  14.,  15.]])
>>> np.hsplit(x, 2)
[array([[  0.,   1.],
       [  4.,   5.],
       [  8.,   9.],
       [12.,  13.]]),
 array([[  2.,   3.],
       [  6.,   7.],
       [10.,  11.],
       [14.,  15.]])]
>>> np.hsplit(x, np.array([3, 6]))
[array([[ 0.,   1.,   2.],
       [ 4.,   5.,   6.],
       [ 8.,   9.,  10.],
       [12.,  13.,  14.]]),
 array([[ 3.],
       [ 7.],
       [11.],
       [15.]]),
 array([], shape=(4, 0), dtype=float64)]
With a higher dimensional array the split is still along the second axis.
>>> x = np.arange(8.0).reshape(2, 2, 2)
>>> x
array([[[0.,  1.],
        [2.,  3.]],
       [[4.,  5.],
        [6.,  7.]]])
>>> np.hsplit(x, 2)
[array([[[0.,  1.]],
       [[4.,  5.]]]),
 array([[[2.,  3.]],
       [[6.,  7.]]])]
With a 1-D array, the split is along axis 0.
>>> x = np.array([0, 1, 2, 3, 4, 5])
>>> np.hsplit(x, 2)
[array([0, 1, 2]), array([3, 4, 5])]
Definition at line 874 of file shape_base.py.
References split().
kron()
numpy.lib.shape_base.kron (a, b)
Kronecker product of two arrays.
Computes the Kronecker product, a composite array made of blocks of the
second array scaled by the first.
Parameters
----------
a, b : array_like
Returns
-------
out : ndarray
See Also
--------
outer : The outer product
Notes
-----
The function assumes that the number of dimensions of `a` and `b`
are the same, if necessary prepending the smallest with ones.
If ``a.shape = (r0,r1,..,rN)`` and ``b.shape = (s0,s1,...,sN)``,
the Kronecker product has shape ``(r0*s0, r1*s1, ..., rN*SN)``.
The elements are products of elements from `a` and `b`, organized
explicitly by::
    kron(a,b)[k0,k1,...,kN] = a[i0,i1,...,iN] * b[j0,j1,...,jN]
where::
    kt = it * st + jt,  t = 0,...,N
In the common 2-D case (N=1), the block structure can be visualized::
    [[ a[0,0]*b,   a[0,1]*b,  ... , a[0,-1]*b  ],
     [  ...                              ...   ],
     [ a[-1,0]*b,  a[-1,1]*b, ... , a[-1,-1]*b ]]
Examples
--------
>>> np.kron([1,10,100], [5,6,7])
array([  5,   6,   7, ..., 500, 600, 700])
>>> np.kron([5,6,7], [1,10,100])
array([  5,  50, 500, ...,   7,  70, 700])
>>> np.kron(np.eye(2), np.ones((2,2)))
array([[1.,  1.,  0.,  0.],
       [1.,  1.,  0.,  0.],
       [0.,  0.,  1.,  1.],
       [0.,  0.,  1.,  1.]])
>>> a = np.arange(100).reshape((2,5,2,5))
>>> b = np.arange(24).reshape((2,3,4))
>>> c = np.kron(a,b)
>>> c.shape
(2, 10, 6, 20)
>>> I = (1,3,0,2)
>>> J = (0,2,1)
>>> J1 = (0,) + J             # extend to ndim=4
>>> S1 = (1,) + b.shape
>>> K = tuple(np.array(I) * np.array(S1) + np.array(J1))
>>> c[K] == a[I]*b[J]
True
Definition at line 1068 of file shape_base.py.
References expand_dims(), numpy.core.fromnumeric.max(), and numpy.core.fromnumeric.reshape().
put_along_axis()
numpy.lib.shape_base.put_along_axis (arr, indices, values, axis)
Put values into the destination array by matching 1d index and data slices.
This iterates over matching 1d slices oriented along the specified axis in
the index and data arrays, and uses the former to place values into the
latter. These slices can be different lengths.
Functions returning an index along an axis, like `argsort` and
`argpartition`, produce suitable indices for this function.
.. versionadded:: 1.15.0
Parameters
----------
arr : ndarray (Ni..., M, Nk...)
    Destination array.
indices : ndarray (Ni..., J, Nk...)
    Indices to change along each 1d slice of `arr`. This must match the
    dimension of arr, but dimensions in Ni and Nj may be 1 to broadcast
    against `arr`.
values : array_like (Ni..., J, Nk...)
    values to insert at those indices. Its shape and dimension are
    broadcast to match that of `indices`.
axis : int
    The axis to take 1d slices along. If axis is None, the destination
    array is treated as if a flattened 1d view had been created of it.
Notes
-----
This is equivalent to (but faster than) the following use of `ndindex` and
`s_`, which sets each of ``ii`` and ``kk`` to a tuple of indices::
    Ni, M, Nk = a.shape[:axis], a.shape[axis], a.shape[axis+1:]
    J = indices.shape[axis]  # Need not equal M
    for ii in ndindex(Ni):
        for kk in ndindex(Nk):
            a_1d       = a      [ii + s_[:,] + kk]
            indices_1d = indices[ii + s_[:,] + kk]
            values_1d  = values [ii + s_[:,] + kk]
            for j in range(J):
                a_1d[indices_1d[j]] = values_1d[j]
Equivalently, eliminating the inner loop, the last two lines would be::
            a_1d[indices_1d] = values_1d
See Also
--------
take_along_axis :
    Take values from the input array by matching 1d index and data slices
Examples
--------
For this sample array
>>> a = np.array([[10, 30, 20], [60, 40, 50]])
We can replace the maximum values with:
>>> ai = np.argmax(a, axis=1, keepdims=True)
>>> ai
array([[1],
       [0]])
>>> np.put_along_axis(a, ai, 99, axis=1)
>>> a
array([[10, 99, 20],
       [99, 40, 50]])
Definition at line 178 of file shape_base.py.
Referenced by numpy.lib.tests.test_shape_base.TestPutAlongAxis.test_broadcast().
split()
numpy.lib.shape_base.split (ary, indices_or_sections, axis = 0)
Split an array into multiple sub-arrays as views into `ary`.
Parameters
----------
ary : ndarray
    Array to be divided into sub-arrays.
indices_or_sections : int or 1-D array
    If `indices_or_sections` is an integer, N, the array will be divided
    into N equal arrays along `axis`.  If such a split is not possible,
    an error is raised.
    If `indices_or_sections` is a 1-D array of sorted integers, the entries
    indicate where along `axis` the array is split.  For example,
    ``[2, 3]`` would, for ``axis=0``, result in
      - ary[:2]
      - ary[2:3]
      - ary[3:]
    If an index exceeds the dimension of the array along `axis`,
    an empty sub-array is returned correspondingly.
axis : int, optional
    The axis along which to split, default is 0.
Returns
-------
sub-arrays : list of ndarrays
    A list of sub-arrays as views into `ary`.
Raises
------
ValueError
    If `indices_or_sections` is given as an integer, but
    a split does not result in equal division.
See Also
--------
array_split : Split an array into multiple sub-arrays of equal or
              near-equal size.  Does not raise an exception if
              an equal division cannot be made.
hsplit : Split array into multiple sub-arrays horizontally (column-wise).
vsplit : Split array into multiple sub-arrays vertically (row wise).
dsplit : Split array into multiple sub-arrays along the 3rd axis (depth).
concatenate : Join a sequence of arrays along an existing axis.
stack : Join a sequence of arrays along a new axis.
hstack : Stack arrays in sequence horizontally (column wise).
vstack : Stack arrays in sequence vertically (row wise).
dstack : Stack arrays in sequence depth wise (along third dimension).
Examples
--------
>>> x = np.arange(9.0)
>>> np.split(x, 3)
[array([0.,  1.,  2.]), array([3.,  4.,  5.]), array([6.,  7.,  8.])]
>>> x = np.arange(8.0)
>>> np.split(x, [3, 5, 6, 10])
[array([0.,  1.,  2.]),
 array([3.,  4.]),
 array([5.]),
 array([6.,  7.]),
 array([], dtype=float64)]
Definition at line 792 of file shape_base.py.
References array_split().
Referenced by numpy.lib.utils._Deprecate.__call__(), numpy.f2py.crackfortran.analyzeline(), numpy.f2py.crackfortran.analyzevars(), numpy.f2py.rules.buildmodule(), dsplit(), numpy.f2py.capi_maps.f2cexpr(), numpy.ma.mrecords.fromtextfile(), hsplit(), numpy.testing._private.utils.jiffies(), numpy.lib.utils.lookfor(), numpy.testing._private.utils.memusage(), numpy.f2py.crackfortran.param_eval(), numpy.f2py.crackfortran.param_parse(), numpy.f2py.crackfortran.postcrack(), numpy.f2py.f2py2e.run_compile(), numpy.f2py.capi_maps.sign2map(), numpy.f2py.crackfortran.split_by_unquoted(), numpy.f2py.tests.test_f2py2e.test_build_dir(), numpy.f2py.tests.test_f2py2e.test_debugcapi(), numpy.f2py.tests.test_f2py2e.test_debugcapi_bld(), numpy.testing.tests.test_utils.TestAlmostEqual.test_error_message(), numpy.testing.tests.test_utils.TestAlmostEqual.test_error_message_2(), numpy.testing.tests.test_utils.TestAssertAllclose.test_error_message_unsigned(), numpy.lib.tests.test_loadtxt.test_exception_negative_row_limits(), numpy.f2py.tests.test_f2py2e.test_f2py_only(), numpy.f2py.tests.test_f2py2e.test_f2py_skip(), numpy.f2py.tests.test_f2py2e.test_file_processing_switch(), numpy.f2py.tests.test_f2py2e.test_gen_pyf(), numpy.f2py.tests.test_f2py2e.test_gen_pyf_no_overwrite(), numpy.f2py.tests.test_f2py2e.test_gen_pyf_stdout(), numpy.f2py.tests.test_f2py2e.test_gh22819_cli(), numpy.f2py.tests.test_f2py2e.test_gh22819_many_pyf(), numpy.f2py.tests.test_f2py2e.test_inclheader(), numpy.f2py.tests.test_f2py2e.test_latexdoc(), numpy.f2py.tests.test_f2py2e.test_lower_cmod(), numpy.f2py.tests.test_f2py2e.test_lower_sig(), numpy.f2py.tests.test_f2py2e.test_mod_gen_f77(), numpy.f2py.tests.test_f2py2e.test_mod_gen_gh25263(), numpy.f2py.tests.test_f2py2e.test_no_py312_distutils_fcompiler(), numpy.f2py.tests.test_f2py2e.test_nolatexdoc(), numpy.f2py.tests.test_f2py2e.test_norestexdoc(), numpy.f2py.tests.test_f2py2e.test_nowrapfunc(), numpy.f2py.tests.test_f2py2e.test_npdistop(), numpy.f2py.tests.test_f2py2e.test_overwrite(), numpy.f2py.tests.test_f2py2e.test_quiet(), numpy.f2py.tests.test_f2py2e.test_restdoc(), numpy.f2py.tests.test_f2py2e.test_shortlatex(), numpy.f2py.tests.test_f2py2e.test_untitled_cli(), numpy.f2py.tests.test_f2py2e.test_verbose(), numpy.f2py.tests.test_f2py2e.test_version(), numpy.f2py.tests.test_f2py2e.test_wrapfunc_def(), numpy.f2py.crackfortran.updatevars(), and vsplit().
take_along_axis()
numpy.lib.shape_base.take_along_axis (arr, indices, axis)
Take values from the input array by matching 1d index and data slices.
This iterates over matching 1d slices oriented along the specified axis in
the index and data arrays, and uses the former to look up values in the
latter. These slices can be different lengths.
Functions returning an index along an axis, like `argsort` and
`argpartition`, produce suitable indices for this function.
.. versionadded:: 1.15.0
Parameters
----------
arr : ndarray (Ni..., M, Nk...)
    Source array
indices : ndarray (Ni..., J, Nk...)
    Indices to take along each 1d slice of `arr`. This must match the
    dimension of arr, but dimensions Ni and Nj only need to broadcast
    against `arr`.
axis : int
    The axis to take 1d slices along. If axis is None, the input array is
    treated as if it had first been flattened to 1d, for consistency with
    `sort` and `argsort`.
Returns
-------
out: ndarray (Ni..., J, Nk...)
    The indexed result.
Notes
-----
This is equivalent to (but faster than) the following use of `ndindex` and
`s_`, which sets each of ``ii`` and ``kk`` to a tuple of indices::
    Ni, M, Nk = a.shape[:axis], a.shape[axis], a.shape[axis+1:]
    J = indices.shape[axis]  # Need not equal M
    out = np.empty(Ni + (J,) + Nk)
    for ii in ndindex(Ni):
        for kk in ndindex(Nk):
            a_1d       = a      [ii + s_[:,] + kk]
            indices_1d = indices[ii + s_[:,] + kk]
            out_1d     = out    [ii + s_[:,] + kk]
            for j in range(J):
                out_1d[j] = a_1d[indices_1d[j]]
Equivalently, eliminating the inner loop, the last two lines would be::
            out_1d[:] = a_1d[indices_1d]
See Also
--------
take : Take along an axis, using the same indices for every 1d slice
put_along_axis :
    Put values into the destination array by matching 1d index and data slices
Examples
--------
For this sample array
>>> a = np.array([[10, 30, 20], [60, 40, 50]])
We can sort either by using sort directly, or argsort and this function
>>> np.sort(a, axis=1)
array([[10, 20, 30],
       [40, 50, 60]])
>>> ai = np.argsort(a, axis=1)
>>> ai
array([[0, 2, 1],
       [1, 2, 0]])
>>> np.take_along_axis(a, ai, axis=1)
array([[10, 20, 30],
       [40, 50, 60]])
The same works for max and min, if you maintain the trivial dimension
with ``keepdims``:
>>> np.max(a, axis=1, keepdims=True)
array([[30],
       [60]])
>>> ai = np.argmax(a, axis=1, keepdims=True)
>>> ai
array([[1],
       [0]])
>>> np.take_along_axis(a, ai, axis=1)
array([[30],
       [60]])
If we want to get the max and min at the same time, we can stack the
indices first
>>> ai_min = np.argmin(a, axis=1, keepdims=True)
>>> ai_max = np.argmax(a, axis=1, keepdims=True)
>>> ai = np.concatenate([ai_min, ai_max], axis=1)
>>> ai
array([[0, 1],
       [1, 0]])
>>> np.take_along_axis(a, ai, axis=1)
array([[10, 30],
       [40, 60]])
Definition at line 55 of file shape_base.py.
Referenced by numpy.lib.tests.test_shape_base.TestTakeAlongAxis.test_argequivalent(), numpy.lib.tests.test_shape_base.TestPutAlongAxis.test_broadcast(), numpy.lib.tests.test_shape_base.TestTakeAlongAxis.test_broadcast(), numpy.lib.tests.test_shape_base.TestTakeAlongAxis.test_empty(), and numpy.lib.tests.test_shape_base.TestTakeAlongAxis.test_invalid().
tile()
numpy.lib.shape_base.tile (A, reps)
Construct an array by repeating A the number of times given by reps.
If `reps` has length ``d``, the result will have dimension of
``max(d, A.ndim)``.
If ``A.ndim < d``, `A` is promoted to be d-dimensional by prepending new
axes. So a shape (3,) array is promoted to (1, 3) for 2-D replication,
or shape (1, 1, 3) for 3-D replication. If this is not the desired
behavior, promote `A` to d-dimensions manually before calling this
function.
If ``A.ndim > d``, `reps` is promoted to `A`.ndim by pre-pending 1's to it.
Thus for an `A` of shape (2, 3, 4, 5), a `reps` of (2, 2) is treated as
(1, 1, 2, 2).
Note : Although tile may be used for broadcasting, it is strongly
recommended to use numpy's broadcasting operations and functions.
Parameters
----------
A : array_like
    The input array.
reps : array_like
    The number of repetitions of `A` along each axis.
Returns
-------
c : ndarray
    The tiled output array.
See Also
--------
repeat : Repeat elements of an array.
broadcast_to : Broadcast an array to a new shape
Examples
--------
>>> a = np.array([0, 1, 2])
>>> np.tile(a, 2)
array([0, 1, 2, 0, 1, 2])
>>> np.tile(a, (2, 2))
array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])
>>> np.tile(a, (2, 1, 2))
array([[[0, 1, 2, 0, 1, 2]],
       [[0, 1, 2, 0, 1, 2]]])
>>> b = np.array([[1, 2], [3, 4]])
>>> np.tile(b, 2)
array([[1, 2, 1, 2],
       [3, 4, 3, 4]])
>>> np.tile(b, (2, 1))
array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])
>>> c = np.array([1,2,3,4])
>>> np.tile(c,(4,1))
array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])
Definition at line 1186 of file shape_base.py.
References numpy.core.fromnumeric.all(), and numpy.core.fromnumeric.repeat().
vsplit()
numpy.lib.shape_base.vsplit (ary, indices_or_sections)
Split an array into multiple sub-arrays vertically (row-wise).
Please refer to the ``split`` documentation.  ``vsplit`` is equivalent
to ``split`` with `axis=0` (default), the array is always split along the
first axis regardless of the array dimension.
See Also
--------
split : Split an array into multiple sub-arrays of equal size.
Examples
--------
>>> x = np.arange(16.0).reshape(4, 4)
>>> x
array([[ 0.,   1.,   2.,   3.],
       [ 4.,   5.,   6.,   7.],
       [ 8.,   9.,  10.,  11.],
       [12.,  13.,  14.,  15.]])
>>> np.vsplit(x, 2)
[array([[0., 1., 2., 3.],
       [4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])]
>>> np.vsplit(x, np.array([3, 6]))
[array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]]), array([[12., 13., 14., 15.]]), array([], shape=(0, 4), dtype=float64)]
With a higher dimensional array the split is still along the first axis.
>>> x = np.arange(8.0).reshape(2, 2, 2)
>>> x
array([[[0.,  1.],
        [2.,  3.]],
       [[4.,  5.],
        [6.,  7.]]])
>>> np.vsplit(x, 2)
[array([[[0., 1.],
        [2., 3.]]]), array([[[4., 5.],
        [6., 7.]]])]
Definition at line 944 of file shape_base.py.
References split().
Variable Documentation
__all__
list numpy.lib.shape_base.__all__ private
Initial value:
=  [
    'column_stack', 'row_stack', 'dstack', 'array_split', 'split',
    'hsplit', 'vsplit', 'dsplit', 'apply_over_axes', 'expand_dims',
    'apply_along_axis', 'kron', 'tile', 'get_array_wrap', 'take_along_axis',
    'put_along_axis'
    ]
Definition at line 15 of file shape_base.py.
array_function_dispatch
numpy.lib.shape_base.array_function_dispatch
Initial value:
=  functools.partial(
    overrides.array_function_dispatch, module='numpy')
Definition at line 23 of file shape_base.py.
row_stack
numpy.lib.shape_base.row_stack = vstack
Definition at line 605 of file shape_base.py.