Code Cloning Analysis: fontTools.cu2qu.errors.IncompatibleFontsError Class Reference
fontTools.cu2qu.errors.IncompatibleFontsError Class Reference
Public Member Functions
__init__ (self, glyph_errors)
__str__ (self)
Public Attributes
glyph_errors = glyph_errors
Detailed Description
Definition at line 70 of file errors.py.
Constructor & Destructor Documentation
__init__()
fontTools.cu2qu.errors.IncompatibleFontsError.__init__ (self, glyph_errors)
Definition at line 71 of file errors.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__str__()
fontTools.cu2qu.errors.IncompatibleFontsError.__str__ (self)
Definition at line 74 of file errors.py.
Referenced by numpy.polynomial._polybase.ABCPolyBase._get_coefficients().
Member Data Documentation
glyph_errors
fontTools.cu2qu.errors.IncompatibleFontsError.glyph_errors = glyph_errors
Definition at line 72 of file errors.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/cu2qu/errors.py