Code Cloning Analysis: matplotlib.backends.registry.BackendRegistry Class Reference
matplotlib.backends.registry.BackendRegistry Class Reference
Public Member Functions
__init__ (self)
backend_for_gui_framework (self, framework)
is_valid_backend (self, backend)
list_all (self)
list_builtin (self, filter_=None)
list_gui_frameworks (self)
load_backend_module (self, backend)
resolve_backend (self, backend)
resolve_gui_or_backend (self, gui_or_backend)
Protected Member Functions
_backend_module_name (self, backend)
_clear (self)
_ensure_entry_points_loaded (self)
_get_gui_framework_by_loading (self, backend)
_read_entry_points (self)
_validate_and_store_entry_points (self, entries)
Protected Attributes
bool _loaded_entry_points = False
dict _backend_to_gui_framework = {}
dict _name_to_module
Static Protected Attributes
dict _BUILTIN_BACKEND_TO_GUI_FRAMEWORK
dict _GUI_FRAMEWORK_TO_BACKEND
Detailed Description
Registry of backends available within Matplotlib.
This is the single source of truth for available backends.
All use of ``BackendRegistry`` should be via the singleton instance
``backend_registry`` which can be imported from ``matplotlib.backends``.
Each backend has a name, a module name containing the backend code, and an
optional GUI framework that must be running if the backend is interactive.
There are three sources of backends: built-in (source code is within the
Matplotlib repository), explicit ``module://some.backend`` syntax (backend is
obtained by loading the module), or via an entry point (self-registering
backend in an external package).
.. versionadded:: 3.9
Definition at line 15 of file registry.py.
Constructor & Destructor Documentation
__init__()
matplotlib.backends.registry.BackendRegistry.__init__ (self)
Definition at line 77 of file registry.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_backend_module_name()
matplotlib.backends.registry.BackendRegistry._backend_module_name (self, backend) protected
Definition at line 95 of file registry.py.
Referenced by load_backend_module().
_clear()
matplotlib.backends.registry.BackendRegistry._clear (self) protected
Definition at line 109 of file registry.py.
Referenced by matplotlib.spines.Spine.clear().
_ensure_entry_points_loaded()
matplotlib.backends.registry.BackendRegistry._ensure_entry_points_loaded (self) protected
Definition at line 113 of file registry.py.
Referenced by is_valid_backend(), list_all(), and resolve_backend().
_get_gui_framework_by_loading()
matplotlib.backends.registry.BackendRegistry._get_gui_framework_by_loading (self, backend) protected
Definition at line 120 of file registry.py.
Referenced by resolve_backend().
_read_entry_points()
matplotlib.backends.registry.BackendRegistry._read_entry_points (self) protected
Definition at line 128 of file registry.py.
_validate_and_store_entry_points()
matplotlib.backends.registry.BackendRegistry._validate_and_store_entry_points (self, entries) protected
Definition at line 165 of file registry.py.
backend_for_gui_framework()
matplotlib.backends.registry.BackendRegistry.backend_for_gui_framework (self, framework)
Return the name of the backend corresponding to the specified GUI framework.
Parameters
----------
framework : str
    GUI framework such as "qt".
Returns
-------
str or None
    Backend name or None if GUI framework not recognised.
Definition at line 186 of file registry.py.
References _GUI_FRAMEWORK_TO_BACKEND.
Referenced by resolve_gui_or_backend().
is_valid_backend()
matplotlib.backends.registry.BackendRegistry.is_valid_backend (self, backend)
Return True if the backend name is valid, False otherwise.
A backend name is valid if it is one of the built-in backends or has been
dynamically added via an entry point. Those beginning with ``module://`` are
always considered valid and are added to the current list of all backends
within this function.
Even if a name is valid, it may not be importable or usable. This can only be
determined by loading and using the backend module.
Parameters
----------
backend : str
    Name of backend.
Returns
-------
bool
    True if backend is valid, False otherwise.
Definition at line 202 of file registry.py.
References _backend_to_gui_framework, _BUILTIN_BACKEND_TO_GUI_FRAMEWORK, and _ensure_entry_points_loaded().
list_all()
matplotlib.backends.registry.BackendRegistry.list_all (self)
Return list of all known backends.
These include built-in backends and those obtained at runtime either from entry
points or explicit ``module://some.backend`` syntax.
Entry points will be loaded if they haven't been already.
Returns
-------
list of str
    Backend names.
Definition at line 250 of file registry.py.
References _backend_to_gui_framework, _ensure_entry_points_loaded(), and list_builtin().
list_builtin()
matplotlib.backends.registry.BackendRegistry.list_builtin (self, filter_ = None)
Return list of backends that are built into Matplotlib.
Parameters
----------
filter_ : `~.BackendFilter`, optional
    Filter to apply to returned backends. For example, to return only
    non-interactive backends use `.BackendFilter.NON_INTERACTIVE`.
Returns
-------
list of str
    Backend names.
Definition at line 267 of file registry.py.
References _BUILTIN_BACKEND_TO_GUI_FRAMEWORK.
Referenced by list_all().
list_gui_frameworks()
matplotlib.backends.registry.BackendRegistry.list_gui_frameworks (self)
Return list of GUI frameworks used by Matplotlib backends.
Returns
-------
list of str
    GUI framework names.
Definition at line 291 of file registry.py.
References _GUI_FRAMEWORK_TO_BACKEND.
load_backend_module()
matplotlib.backends.registry.BackendRegistry.load_backend_module (self, backend)
Load and return the module containing the specified backend.
Parameters
----------
backend : str
    Name of backend to load.
Returns
-------
Module
    Module containing backend.
Definition at line 302 of file registry.py.
References _backend_module_name().
resolve_backend()
matplotlib.backends.registry.BackendRegistry.resolve_backend (self, backend)
Return the backend and GUI framework for the specified backend name.
If the GUI framework is not yet known then it will be determined by loading the
backend module and checking the ``FigureCanvas.required_interactive_framework``
attribute.
This function only loads entry points if they have not already been loaded and
the backend is not built-in and not of ``module://some.backend`` format.
Parameters
----------
backend : str or None
    Name of backend, or None to use the default backend.
Returns
-------
backend : str
    The backend name.
framework : str or None
    The GUI framework, which will be None for a backend that is non-interactive.
Definition at line 319 of file registry.py.
References _backend_to_gui_framework, _BUILTIN_BACKEND_TO_GUI_FRAMEWORK, _ensure_entry_points_loaded(), _get_gui_framework_by_loading(), _loaded_entry_points, and matplotlib.get_backend().
Referenced by resolve_gui_or_backend().
resolve_gui_or_backend()
matplotlib.backends.registry.BackendRegistry.resolve_gui_or_backend (self, gui_or_backend)
Return the backend and GUI framework for the specified string that may be
either a GUI framework or a backend name, tested in that order.
This is for use with the IPython %matplotlib magic command which may be a GUI
framework such as ``%matplotlib qt`` or a backend name such as
``%matplotlib qtagg``.
This function only loads entry points if they have not already been loaded and
the backend is not built-in and not of ``module://some.backend`` format.
Parameters
----------
gui_or_backend : str or None
    Name of GUI framework or backend, or None to use the default backend.
Returns
-------
backend : str
    The backend name.
framework : str or None
    The GUI framework, which will be None for a backend that is non-interactive.
Definition at line 373 of file registry.py.
References backend_for_gui_framework(), and resolve_backend().
Member Data Documentation
_backend_to_gui_framework
matplotlib.backends.registry.BackendRegistry._backend_to_gui_framework = {} protected
Definition at line 85 of file registry.py.
Referenced by is_valid_backend(), list_all(), and resolve_backend().
_BUILTIN_BACKEND_TO_GUI_FRAMEWORK
dict matplotlib.backends.registry.BackendRegistry._BUILTIN_BACKEND_TO_GUI_FRAMEWORK static protected
Initial value:
=  {
        "gtk3agg": "gtk3",
        "gtk3cairo": "gtk3",
        "gtk4agg": "gtk4",
        "gtk4cairo": "gtk4",
        "macosx": "macosx",
        "nbagg": "nbagg",
        "notebook": "nbagg",
        "qtagg": "qt",
        "qtcairo": "qt",
        "qt5agg": "qt5",
        "qt5cairo": "qt5",
        "tkagg": "tk",
        "tkcairo": "tk",
        "webagg": "webagg",
        "wx": "wx",
        "wxagg": "wx",
        "wxcairo": "wx",
        "agg": "headless",
        "cairo": "headless",
        "pdf": "headless",
        "pgf": "headless",
        "ps": "headless",
        "svg": "headless",
        "template": "headless",
    }
Definition at line 37 of file registry.py.
Referenced by is_valid_backend(), list_builtin(), and resolve_backend().
_GUI_FRAMEWORK_TO_BACKEND
dict matplotlib.backends.registry.BackendRegistry._GUI_FRAMEWORK_TO_BACKEND static protected
Initial value:
=  {
        "gtk3": "gtk3agg",
        "gtk4": "gtk4agg",
        "headless": "agg",
        "macosx": "macosx",
        "qt": "qtagg",
        "qt5": "qt5agg",
        "qt6": "qtagg",
        "tk": "tkagg",
        "wx": "wxagg",
    }
Definition at line 65 of file registry.py.
Referenced by backend_for_gui_framework(), and list_gui_frameworks().
_loaded_entry_points
bool matplotlib.backends.registry.BackendRegistry._loaded_entry_points = False protected
Definition at line 79 of file registry.py.
Referenced by resolve_backend().
_name_to_module
dict matplotlib.backends.registry.BackendRegistry._name_to_module protected
Initial value:
=  {
            "notebook": "nbagg",
        }
Definition at line 91 of file registry.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/backends/registry.py