Code Cloning Analysis: pandas.io.parquet.PyArrowImpl Class Reference
pandas.io.parquet.PyArrowImpl Class Reference
Public Member Functions
None __init__ (self)
None write (self, DataFrame df, FilePath|WriteBuffer[bytes] path, str|None compression="snappy", bool|None index=None, StorageOptions|None storage_options=None, list[str]|None partition_cols=None, filesystem=None, **kwargs)
DataFrame read (self, path, columns=None, filters=None, bool use_nullable_dtypes=False, DtypeBackend|lib.NoDefault dtype_backend=lib.no_default, StorageOptions|None storage_options=None, filesystem=None, **kwargs)
Public Attributes
api = pyarrow
Additional Inherited Members
Static Public Member Functions inherited from pandas.io.parquet.BaseImpl
None validate_dataframe (DataFrame df)
Detailed Description
Definition at line 162 of file parquet.py.
Constructor & Destructor Documentation
__init__()
None pandas.io.parquet.PyArrowImpl.__init__ (self)
Definition at line 163 of file parquet.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
read()
DataFrame pandas.io.parquet.PyArrowImpl.read (self, path, columns = None, filters = None, bool use_nullable_dtypes = False, DtypeBackend | lib.NoDefault dtype_backend = lib.no_default, StorageOptions | None storage_options = None, filesystem = None, ** kwargs)
Reimplemented from pandas.io.parquet.BaseImpl.
Definition at line 240 of file parquet.py.
Referenced by pandas.io.parsers.python_parser.PythonParser.__init__(), pip._vendor.urllib3.util.ssltransport.SSLTransport.__init__(), pandas.io.sas.sas7bdat.SAS7BDATReader.column_types(), pip._vendor.urllib3.response.HTTPResponse.drain_conn(), pip._vendor.urllib3.response.HTTPResponse.from_httplib(), pandas.io.sas.sas_xport.XportReader.get_chunk(), PIL.ContainerIO.ContainerIO.readline(), and pip._vendor.urllib3.response.HTTPResponse.stream().
write()
None pandas.io.parquet.PyArrowImpl.write (self, DataFrame df, FilePath | WriteBuffer[bytes] path, str | None compression = "snappy", bool | None index = None, StorageOptions | None storage_options = None, list[str] | None partition_cols = None, filesystem = None, ** kwargs)
Reimplemented from pandas.io.parquet.BaseImpl.
Definition at line 174 of file parquet.py.
Referenced by joblib.externals.cloudpickle.cloudpickle.Pickler.reducer_override(), scipy.io.matlab._mio5.VarWriter5.write_sparse(), and scipy.io.matlab._mio5.VarWriter5.write_top().
Member Data Documentation
api
pandas.io.parquet.PyArrowImpl.api = pyarrow
Definition at line 172 of file parquet.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/io/parquet.py