Code Cloning Analysis: numpy.f2py.tests.test_f2py2e Namespace Reference
numpy.f2py.tests.test_f2py2e Namespace Reference
Functions
get_io_paths (fname_inp, mname="untitled")
hello_world_f90 (tmpdir_factory)
CLI Fixtures and Tests #.
gh23598_warn (tmpdir_factory)
gh22819_cli (tmpdir_factory)
hello_world_f77 (tmpdir_factory)
retreal_f77 (tmpdir_factory)
f2cmap_f90 (tmpdir_factory)
test_gh22819_cli (capfd, gh22819_cli, monkeypatch)
test_gh22819_many_pyf (capfd, gh22819_cli, monkeypatch)
test_gh23598_warn (capfd, gh23598_warn, monkeypatch)
test_gen_pyf (capfd, hello_world_f90, monkeypatch)
test_gen_pyf_stdout (capfd, hello_world_f90, monkeypatch)
test_gen_pyf_no_overwrite (capfd, hello_world_f90, monkeypatch)
test_untitled_cli (capfd, hello_world_f90, monkeypatch)
test_no_py312_distutils_fcompiler (capfd, hello_world_f90, monkeypatch)
test_f2py_skip (capfd, retreal_f77, monkeypatch)
test_f2py_only (capfd, retreal_f77, monkeypatch)
test_file_processing_switch (capfd, hello_world_f90, retreal_f77, monkeypatch)
test_mod_gen_f77 (capfd, hello_world_f90, monkeypatch)
test_mod_gen_gh25263 (capfd, hello_world_f77, monkeypatch)
test_lower_cmod (capfd, hello_world_f77, monkeypatch)
test_lower_sig (capfd, hello_world_f77, monkeypatch)
test_build_dir (capfd, hello_world_f90, monkeypatch)
test_overwrite (capfd, hello_world_f90, monkeypatch)
test_latexdoc (capfd, hello_world_f90, monkeypatch)
test_nolatexdoc (capfd, hello_world_f90, monkeypatch)
test_shortlatex (capfd, hello_world_f90, monkeypatch)
test_restdoc (capfd, hello_world_f90, monkeypatch)
test_norestexdoc (capfd, hello_world_f90, monkeypatch)
test_debugcapi (capfd, hello_world_f90, monkeypatch)
test_debugcapi_bld (hello_world_f90, monkeypatch)
test_wrapfunc_def (capfd, hello_world_f90, monkeypatch)
test_nowrapfunc (capfd, hello_world_f90, monkeypatch)
test_inclheader (capfd, hello_world_f90, monkeypatch)
test_inclpath ()
test_hlink ()
test_f2cmap (capfd, f2cmap_f90, monkeypatch)
test_quiet (capfd, hello_world_f90, monkeypatch)
test_verbose (capfd, hello_world_f90, monkeypatch)
test_version (capfd, monkeypatch)
test_npdistop (hello_world_f90, monkeypatch)
test_npd_fcompiler ()
test_npd_compiler ()
test_npd_help_fcompiler ()
test_npd_f77exec ()
test_npd_f90exec ()
test_npd_f77flags ()
test_npd_f90flags ()
test_npd_opt ()
test_npd_arch ()
test_npd_noopt ()
test_npd_noarch ()
test_npd_debug ()
test_npd_link_auto ()
test_npd_lib ()
test_npd_define ()
test_npd_undefine ()
test_npd_incl ()
test_npd_linker ()
Variables
PPaths = namedtuple("PPaths", "finp, f90inp, pyf, wrap77, wrap90, cmodf")
CLI utils and classes #.
Function Documentation
f2cmap_f90()
numpy.f2py.tests.test_f2py2e.f2cmap_f90 (tmpdir_factory)
Generates a single f90 file for testing
Definition at line 102 of file test_f2py2e.py.
get_io_paths()
numpy.f2py.tests.test_f2py2e.get_io_paths (fname_inp, mname = "untitled")
Takes in a temporary file for testing and returns the expected output and input paths
Here expected output is essentially one of any of the possible generated
files.
..note::
     Since this does not actually run f2py, none of these are guaranteed to
     exist, and module names are typically incorrect
Parameters
----------
fname_inp : str
            The input filename
mname : str, optional
            The name of the module, untitled by default
Returns
-------
genp : NamedTuple PPaths
        The possible paths which are generated, not all of which exist
Definition at line 18 of file test_f2py2e.py.
References PPaths.
Referenced by test_f2py_only(), test_f2py_skip(), test_file_processing_switch(), test_gh22819_many_pyf(), test_lower_cmod(), test_lower_sig(), test_mod_gen_f77(), test_mod_gen_gh25263(), and test_no_py312_distutils_fcompiler().
gh22819_cli()
numpy.f2py.tests.test_f2py2e.gh22819_cli (tmpdir_factory)
F90 file for testing disallowed CLI arguments in ghff819
Definition at line 76 of file test_f2py2e.py.
gh23598_warn()
numpy.f2py.tests.test_f2py2e.gh23598_warn (tmpdir_factory)
F90 file for testing warnings in gh23598
Definition at line 67 of file test_f2py2e.py.
hello_world_f77()
numpy.f2py.tests.test_f2py2e.hello_world_f77 (tmpdir_factory)
Generates a single f77 file for testing
Definition at line 85 of file test_f2py2e.py.
hello_world_f90()
numpy.f2py.tests.test_f2py2e.hello_world_f90 (tmpdir_factory)
CLI Fixtures and Tests #.
Generates a single f90 file for testing
Definition at line 58 of file test_f2py2e.py.
retreal_f77()
numpy.f2py.tests.test_f2py2e.retreal_f77 (tmpdir_factory)
Generates a single f77 file for testing
Definition at line 94 of file test_f2py2e.py.
test_build_dir()
numpy.f2py.tests.test_f2py2e.test_build_dir (capfd, hello_world_f90, monkeypatch)
Ensures that the build directory can be specified
CLI :: --build-dir
Definition at line 423 of file test_f2py2e.py.
References numpy.lib.shape_base.split().
test_debugcapi()
numpy.f2py.tests.test_f2py2e.test_debugcapi (capfd, hello_world_f90, monkeypatch)
Ensures that debugging wrappers are written
CLI :: --debug-capi
Definition at line 547 of file test_f2py2e.py.
References numpy.lib.shape_base.split().
test_debugcapi_bld()
numpy.f2py.tests.test_f2py2e.test_debugcapi_bld (hello_world_f90, monkeypatch)
Ensures that debugging wrappers work
CLI :: --debug-capi -c
Definition at line 564 of file test_f2py2e.py.
References numpy.lib.shape_base.split().
test_f2cmap()
numpy.f2py.tests.test_f2py2e.test_f2cmap (capfd, f2cmap_f90, monkeypatch)
Check that Fortran-to-Python KIND specs can be passed
CLI :: --f2cmap
Definition at line 675 of file test_f2py2e.py.
test_f2py_only()
numpy.f2py.tests.test_f2py2e.test_f2py_only (capfd, retreal_f77, monkeypatch)
Test that functions can be kept by only:
CLI :: only:
Definition at line 272 of file test_f2py2e.py.
References get_io_paths(), and numpy.lib.shape_base.split().
test_f2py_skip()
numpy.f2py.tests.test_f2py2e.test_f2py_skip (capfd, retreal_f77, monkeypatch)
Tests that functions can be skipped
CLI :: skip:
Definition at line 249 of file test_f2py2e.py.
References get_io_paths(), and numpy.lib.shape_base.split().
test_file_processing_switch()
numpy.f2py.tests.test_f2py2e.test_file_processing_switch (capfd, hello_world_f90, retreal_f77, monkeypatch)
Tests that it is possible to return to file processing mode
CLI :: :
BUG: numpy-gh #20520
Definition at line 295 of file test_f2py2e.py.
References get_io_paths(), and numpy.lib.shape_base.split().
test_gen_pyf()
numpy.f2py.tests.test_f2py2e.test_gen_pyf (capfd, hello_world_f90, monkeypatch)
Ensures that a signature file is generated via the CLI
CLI :: -h
Definition at line 158 of file test_f2py2e.py.
References numpy.lib.shape_base.split().
test_gen_pyf_no_overwrite()
numpy.f2py.tests.test_f2py2e.test_gen_pyf_no_overwrite (capfd, hello_world_f90, monkeypatch)
Ensures that the CLI refuses to overwrite signature files
CLI :: -h without --overwrite-signature
Definition at line 186 of file test_f2py2e.py.
References numpy.lib.shape_base.split().
test_gen_pyf_stdout()
numpy.f2py.tests.test_f2py2e.test_gen_pyf_stdout (capfd, hello_world_f90, monkeypatch)
Ensures that a signature file can be dumped to stdout
CLI :: -h
Definition at line 173 of file test_f2py2e.py.
References numpy.lib.shape_base.split().
test_gh22819_cli()
numpy.f2py.tests.test_f2py2e.test_gh22819_cli (capfd, gh22819_cli, monkeypatch)
Check that module names are handled correctly
gh-22819
Essentially, the -m name cannot be used to import the module, so the module
named in the .pyf needs to be used instead
CLI :: -m and a .pyf file
Definition at line 113 of file test_f2py2e.py.
References numpy.lib.shape_base.split().
test_gh22819_many_pyf()
numpy.f2py.tests.test_f2py2e.test_gh22819_many_pyf (capfd, gh22819_cli, monkeypatch)
Only one .pyf file allowed
gh-22819
CLI :: .pyf files
Definition at line 133 of file test_f2py2e.py.
References get_io_paths(), and numpy.lib.shape_base.split().
test_gh23598_warn()
numpy.f2py.tests.test_f2py2e.test_gh23598_warn (capfd, gh23598_warn, monkeypatch)
Definition at line 145 of file test_f2py2e.py.
test_hlink()
numpy.f2py.tests.test_f2py2e.test_hlink ()
Add to the include directories
CLI :: --help-link
Definition at line 666 of file test_f2py2e.py.
test_inclheader()
numpy.f2py.tests.test_f2py2e.test_inclheader (capfd, hello_world_f90, monkeypatch)
Add to the include directories
CLI :: -include
TODO: Document this in the help string
Definition at line 634 of file test_f2py2e.py.
References numpy.lib.shape_base.split().
test_inclpath()
numpy.f2py.tests.test_f2py2e.test_inclpath ()
Add to the include directories
CLI :: --include-paths
Definition at line 657 of file test_f2py2e.py.
test_latexdoc()
numpy.f2py.tests.test_f2py2e.test_latexdoc (capfd, hello_world_f90, monkeypatch)
Ensures that TeX documentation is written out
CLI :: --latex-doc
Definition at line 457 of file test_f2py2e.py.
References numpy.lib.shape_base.split().
test_lower_cmod()
numpy.f2py.tests.test_f2py2e.test_lower_cmod (capfd, hello_world_f77, monkeypatch)
Lowers cases by flag or when -h is present
CLI :: --[no-]lower
Definition at line 358 of file test_f2py2e.py.
References get_io_paths(), and numpy.lib.shape_base.split().
test_lower_sig()
numpy.f2py.tests.test_f2py2e.test_lower_sig (capfd, hello_world_f77, monkeypatch)
Lowers cases in signature files by flag or when -h is present
CLI :: --[no-]lower -h
Definition at line 384 of file test_f2py2e.py.
References get_io_paths(), and numpy.lib.shape_base.split().
test_mod_gen_f77()
numpy.f2py.tests.test_f2py2e.test_mod_gen_f77 (capfd, hello_world_f90, monkeypatch)
Checks the generation of files based on a module name
CLI :: -m
Definition at line 325 of file test_f2py2e.py.
References get_io_paths(), and numpy.lib.shape_base.split().
test_mod_gen_gh25263()
numpy.f2py.tests.test_f2py2e.test_mod_gen_gh25263 (capfd, hello_world_f77, monkeypatch)
Check that pyf files are correctly generated with module structure
CLI :: -m <name> -h pyf_file
BUG: numpy-gh #20520
Definition at line 342 of file test_f2py2e.py.
References get_io_paths(), and numpy.lib.shape_base.split().
test_no_py312_distutils_fcompiler()
numpy.f2py.tests.test_f2py2e.test_no_py312_distutils_fcompiler (capfd, hello_world_f90, monkeypatch)
Check that no distutils imports are performed on 3.12
CLI :: --fcompiler --help-link --backend distutils
Definition at line 217 of file test_f2py2e.py.
References get_io_paths(), and numpy.lib.shape_base.split().
test_nolatexdoc()
numpy.f2py.tests.test_f2py2e.test_nolatexdoc (capfd, hello_world_f90, monkeypatch)
Ensures that TeX documentation is written out
CLI :: --no-latex-doc
Definition at line 475 of file test_f2py2e.py.
References numpy.lib.shape_base.split().
test_norestexdoc()
numpy.f2py.tests.test_f2py2e.test_norestexdoc (capfd, hello_world_f90, monkeypatch)
Ensures that TeX documentation is written out
CLI :: --no-rest-doc
Definition at line 531 of file test_f2py2e.py.
References numpy.lib.shape_base.split().
test_nowrapfunc()
numpy.f2py.tests.test_f2py2e.test_nowrapfunc (capfd, hello_world_f90, monkeypatch)
Ensures that fortran subroutine wrappers for F77 can be disabled
CLI :: --no-wrap-functions
Definition at line 618 of file test_f2py2e.py.
References numpy.lib.shape_base.split().
test_npd_arch()
numpy.f2py.tests.test_f2py2e.test_npd_arch ()
CLI :: -c --arch
Definition at line 819 of file test_f2py2e.py.
test_npd_compiler()
numpy.f2py.tests.test_f2py2e.test_npd_compiler ()
CLI :: -c --compiler
Definition at line 763 of file test_f2py2e.py.
test_npd_debug()
numpy.f2py.tests.test_f2py2e.test_npd_debug ()
CLI :: -c --debug
Definition at line 843 of file test_f2py2e.py.
test_npd_define()
numpy.f2py.tests.test_f2py2e.test_npd_define ()
CLI :: -D<define>
Definition at line 867 of file test_f2py2e.py.
test_npd_f77exec()
numpy.f2py.tests.test_f2py2e.test_npd_f77exec ()
CLI :: -c --f77exec
Definition at line 779 of file test_f2py2e.py.
test_npd_f77flags()
numpy.f2py.tests.test_f2py2e.test_npd_f77flags ()
CLI :: -c --f77flags
Definition at line 795 of file test_f2py2e.py.
test_npd_f90exec()
numpy.f2py.tests.test_f2py2e.test_npd_f90exec ()
CLI :: -c --f90exec
Definition at line 787 of file test_f2py2e.py.
test_npd_f90flags()
numpy.f2py.tests.test_f2py2e.test_npd_f90flags ()
CLI :: -c --f90flags
Definition at line 803 of file test_f2py2e.py.
test_npd_fcompiler()
numpy.f2py.tests.test_f2py2e.test_npd_fcompiler ()
CLI :: -c --fcompiler
Definition at line 755 of file test_f2py2e.py.
test_npd_help_fcompiler()
numpy.f2py.tests.test_f2py2e.test_npd_help_fcompiler ()
CLI :: -c --help-fcompiler
Definition at line 771 of file test_f2py2e.py.
test_npd_incl()
numpy.f2py.tests.test_f2py2e.test_npd_incl ()
CLI :: -I/path/to/include/
Definition at line 883 of file test_f2py2e.py.
test_npd_lib()
numpy.f2py.tests.test_f2py2e.test_npd_lib ()
CLI :: -c -L/path/to/lib/ -l<libname>
Definition at line 859 of file test_f2py2e.py.
test_npd_link_auto()
numpy.f2py.tests.test_f2py2e.test_npd_link_auto ()
CLI :: -c --link-<resource>
Definition at line 851 of file test_f2py2e.py.
test_npd_linker()
numpy.f2py.tests.test_f2py2e.test_npd_linker ()
CLI :: <filename>.o <filename>.so <filename>.a
Definition at line 891 of file test_f2py2e.py.
test_npd_noarch()
numpy.f2py.tests.test_f2py2e.test_npd_noarch ()
CLI :: -c --noarch
Definition at line 835 of file test_f2py2e.py.
test_npd_noopt()
numpy.f2py.tests.test_f2py2e.test_npd_noopt ()
CLI :: -c --noopt
Definition at line 827 of file test_f2py2e.py.
test_npd_opt()
numpy.f2py.tests.test_f2py2e.test_npd_opt ()
CLI :: -c --opt
Definition at line 811 of file test_f2py2e.py.
test_npd_undefine()
numpy.f2py.tests.test_f2py2e.test_npd_undefine ()
CLI :: -U<name>
Definition at line 875 of file test_f2py2e.py.
test_npdistop()
numpy.f2py.tests.test_f2py2e.test_npdistop (hello_world_f90, monkeypatch)
CLI :: -c
Definition at line 736 of file test_f2py2e.py.
References numpy.lib.shape_base.split().
test_overwrite()
numpy.f2py.tests.test_f2py2e.test_overwrite (capfd, hello_world_f90, monkeypatch)
Ensures that the build directory can be specified
CLI :: --overwrite-signature
Definition at line 440 of file test_f2py2e.py.
References numpy.lib.shape_base.split().
test_quiet()
numpy.f2py.tests.test_f2py2e.test_quiet (capfd, hello_world_f90, monkeypatch)
Reduce verbosity
CLI :: --quiet
Definition at line 693 of file test_f2py2e.py.
References numpy.lib.shape_base.split().
test_restdoc()
numpy.f2py.tests.test_f2py2e.test_restdoc (capfd, hello_world_f90, monkeypatch)
Ensures that RsT documentation is written out
CLI :: --rest-doc
Definition at line 513 of file test_f2py2e.py.
References numpy.lib.shape_base.split().
test_shortlatex()
numpy.f2py.tests.test_f2py2e.test_shortlatex (capfd, hello_world_f90, monkeypatch)
Ensures that truncated documentation is written out
TODO: Test to ensure this has no effect without --latex-doc
CLI :: --latex-doc --short-latex
Definition at line 491 of file test_f2py2e.py.
References numpy.lib.shape_base.split().
test_untitled_cli()
numpy.f2py.tests.test_f2py2e.test_untitled_cli (capfd, hello_world_f90, monkeypatch)
Check that modules are named correctly
CLI :: defaults
Definition at line 203 of file test_f2py2e.py.
References numpy.lib.shape_base.split().
test_verbose()
numpy.f2py.tests.test_f2py2e.test_verbose (capfd, hello_world_f90, monkeypatch)
Increase verbosity
CLI :: --verbose
Definition at line 707 of file test_f2py2e.py.
References numpy.lib.shape_base.split().
test_version()
numpy.f2py.tests.test_f2py2e.test_version (capfd, monkeypatch)
Ensure version
CLI :: -v
Definition at line 721 of file test_f2py2e.py.
References numpy.lib.shape_base.split().
test_wrapfunc_def()
numpy.f2py.tests.test_f2py2e.test_wrapfunc_def (capfd, hello_world_f90, monkeypatch)
Ensures that fortran subroutine wrappers for F77 are included by default
CLI :: --[no]-wrap-functions
Definition at line 593 of file test_f2py2e.py.
References numpy.lib.shape_base.split().
Variable Documentation
PPaths
numpy.f2py.tests.test_f2py2e.PPaths = namedtuple("PPaths", "finp, f90inp, pyf, wrap77, wrap90, cmodf")
CLI utils and classes #.
Definition at line 15 of file test_f2py2e.py.
Referenced by get_io_paths().