Code Cloning Analysis: matplotlib._mathtext.UnicodeFonts Class Reference
matplotlib._mathtext.UnicodeFonts Class Reference
Public Member Functions
__init__ (self, FontProperties default_font_prop, LoadFlags load_glyph_flags)
list[tuple[str, str]] get_sized_alternatives_for_symbol (self, str fontname, str sym)
Public Member Functions inherited from matplotlib._mathtext.TruetypeFonts
__init__ (self, FontProperties default_font_prop, LoadFlags load_glyph_flags)
float get_xheight (self, str fontname, float fontsize, float dpi)
float get_underline_thickness (self, str font, float fontsize, float dpi)
float get_kern (self, str font1, str fontclass1, str sym1, float fontsize1, str font2, str fontclass2, str sym2, float fontsize2, float dpi)
Public Member Functions inherited from matplotlib._mathtext.Fonts
__init__ (self, FontProperties default_font_prop, LoadFlags load_glyph_flags)
FontMetrics get_metrics (self, str font, str font_class, str sym, float fontsize, float dpi)
None render_glyph (self, Output output, float ox, float oy, str font, str font_class, str sym, float fontsize, float dpi)
None render_rect_filled (self, Output output, float x1, float y1, float x2, float y2)
Protected Member Functions
tuple[str, int] _map_virtual_font (self, str fontname, str font_class, int uniindex)
tuple[FT2Font, int, bool] _get_glyph (self, str fontname, str font_class, str sym)
Protected Member Functions inherited from matplotlib._mathtext.TruetypeFonts
FT2Font _get_font (self, str|int font)
float _get_offset (self, FT2Font font, Glyph glyph, float fontsize, float dpi)
FontInfo _get_info (self, str fontname, str font_class, str sym, float fontsize, float dpi)
Protected Attributes
tuple _fallback_font
Protected Attributes inherited from matplotlib._mathtext.TruetypeFonts
dict _fonts = {}
Static Protected Attributes
dict _cmr10_substitutions
_slanted_symbols = set(r"\int \oint".split())
Additional Inherited Members
Public Attributes inherited from matplotlib._mathtext.TruetypeFonts
dict fontmap = {}
Public Attributes inherited from matplotlib._mathtext.Fonts
default_font_prop = default_font_prop
load_glyph_flags = load_glyph_flags
Detailed Description
An abstract base class for handling Unicode fonts.
While some reasonably complete Unicode fonts (such as DejaVu) may
work in some situations, the only Unicode font I'm aware of with a
complete set of math symbols is STIX.
This class will "fallback" on the Bakoma fonts when a required
symbol cannot be found in the font.
Definition at line 540 of file _mathtext.py.
Constructor & Destructor Documentation
__init__()
matplotlib._mathtext.UnicodeFonts.__init__ (self, FontProperties default_font_prop, LoadFlags load_glyph_flags)
Definition at line 560 of file _mathtext.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_get_glyph()
tuple[FT2Font, int, bool] matplotlib._mathtext.UnicodeFonts._get_glyph (self, str fontname, str font_class, str sym) protected
Reimplemented from matplotlib._mathtext.TruetypeFonts.
Definition at line 601 of file _mathtext.py.
_map_virtual_font()
tuple[str, int] matplotlib._mathtext.UnicodeFonts._map_virtual_font (self, str fontname, str font_class, int uniindex) protected
Definition at line 597 of file _mathtext.py.
get_sized_alternatives_for_symbol()
list[tuple[str, str]] matplotlib._mathtext.UnicodeFonts.get_sized_alternatives_for_symbol (self, str fontname, str sym)
Override if your font provides multiple sizes of the same
symbol.  Should return a list of symbols matching *sym* in
various sizes.  The expression renderer will select the most
appropriate size for a given situation from this list.
Reimplemented from matplotlib._mathtext.Fonts.
Reimplemented in matplotlib._mathtext.StixFonts.
Definition at line 664 of file _mathtext.py.
References _fallback_font, and get_sized_alternatives_for_symbol().
Referenced by get_sized_alternatives_for_symbol().
Member Data Documentation
_cmr10_substitutions
dict matplotlib._mathtext.UnicodeFonts._cmr10_substitutions static protected
Initial value:
=  {
        0x00D7: 0x00A3,  # Multiplication sign.
        0x2212: 0x00A1,  # Minus sign.
    }
Definition at line 555 of file _mathtext.py.
_fallback_font
matplotlib._mathtext.UnicodeFonts._fallback_font protected
Initial value:
=  (font_cls(default_font_prop, load_glyph_flags)
                               if font_cls else None)
Definition at line 568 of file _mathtext.py.
Referenced by get_sized_alternatives_for_symbol().
_slanted_symbols
matplotlib._mathtext.UnicodeFonts._slanted_symbols = set(r"\int \oint".split()) static protected
Definition at line 595 of file _mathtext.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/_mathtext.py