Code Cloning Analysis: pandas.core.nanops Namespace Reference
pandas.core.nanops Namespace Reference
Classes
class bottleneck_switch
class disallow
Functions
None set_use_bottleneck (bool v=True)
bool _bn_ok_dtype (DtypeObj dtype, str name)
bool _has_infs (result)
_get_fill_value (DtypeObj dtype, Scalar|None fill_value=None, fill_value_typ=None)
npt.NDArray[np.bool_]|None _maybe_get_mask (np.ndarray values, bool skipna, npt.NDArray[np.bool_]|None mask)
tuple[np.ndarray, npt.NDArray[np.bool_]|None] _get_values (np.ndarray values, bool skipna, Any fill_value=None, str|None fill_value_typ=None, npt.NDArray[np.bool_]|None mask=None)
np.dtype _get_dtype_max (np.dtype dtype)
bool _na_ok_dtype (DtypeObj dtype)
_wrap_results (result, np.dtype dtype, fill_value=None)
F _datetimelike_compat (F func)
Scalar|np.ndarray _na_for_min_count (np.ndarray values, AxisInt|None axis)
F maybe_operate_rowwise (F func)
bool nanany (np.ndarray values, *, AxisInt|None axis=None, bool skipna=True, npt.NDArray[np.bool_]|None mask=None)
bool nanall (np.ndarray values, *, AxisInt|None axis=None, bool skipna=True, npt.NDArray[np.bool_]|None mask=None)
float nansum (np.ndarray values, *, AxisInt|None axis=None, bool skipna=True, int min_count=0, npt.NDArray[np.bool_]|None mask=None)
np.ndarray|np.datetime64|np.timedelta64|NaTType _mask_datetimelike_result (np.ndarray|np.datetime64|np.timedelta64 result, AxisInt|None axis, npt.NDArray[np.bool_] mask, np.ndarray orig_values)
float nanmean (np.ndarray values, *, AxisInt|None axis=None, bool skipna=True, npt.NDArray[np.bool_]|None mask=None)
nanmedian (values, *, AxisInt|None axis=None, bool skipna=True, mask=None)
np.ndarray _get_empty_reduction_result (Shape shape, AxisInt axis)
tuple[float|np.ndarray, float|np.ndarray] _get_counts_nanvar (Shape values_shape, npt.NDArray[np.bool_]|None mask, AxisInt|None axis, int ddof, np.dtype dtype=np.dtype(np.float64))
nanstd (values, *, AxisInt|None axis=None, bool skipna=True, int ddof=1, mask=None)
nanvar (np.ndarray values, *, AxisInt|None axis=None, bool skipna=True, int ddof=1, mask=None)
float nansem (np.ndarray values, *, AxisInt|None axis=None, bool skipna=True, int ddof=1, npt.NDArray[np.bool_]|None mask=None)
_nanminmax (meth, fill_value_typ)
int|np.ndarray nanargmax (np.ndarray values, *, AxisInt|None axis=None, bool skipna=True, npt.NDArray[np.bool_]|None mask=None)
int|np.ndarray nanargmin (np.ndarray values, *, AxisInt|None axis=None, bool skipna=True, npt.NDArray[np.bool_]|None mask=None)
float nanskew (np.ndarray values, *, AxisInt|None axis=None, bool skipna=True, npt.NDArray[np.bool_]|None mask=None)
float nankurt (np.ndarray values, *, AxisInt|None axis=None, bool skipna=True, npt.NDArray[np.bool_]|None mask=None)
float nanprod (np.ndarray values, *, AxisInt|None axis=None, bool skipna=True, int min_count=0, npt.NDArray[np.bool_]|None mask=None)
np.ndarray|int _maybe_arg_null_out (np.ndarray result, AxisInt|None axis, npt.NDArray[np.bool_]|None mask, bool skipna)
np.floating|npt.NDArray[np.floating] _get_counts (Shape values_shape, npt.NDArray[np.bool_]|None mask, AxisInt|None axis, np.dtype[np.floating] dtype=np.dtype(np.float64))
np.ndarray|float|NaTType _maybe_null_out (np.ndarray|float|NaTType result, AxisInt|None axis, npt.NDArray[np.bool_]|None mask, tuple[int,...] shape, int min_count=1)
bool check_below_min_count (tuple[int,...] shape, npt.NDArray[np.bool_]|None mask, int min_count)
_zero_out_fperr (arg)
float nancorr (np.ndarray a, np.ndarray b, *, CorrelationMethod method="pearson", int|None min_periods=None)
Callable[[np.ndarray, np.ndarray], float] get_corr_func (CorrelationMethod method)
float nancov (np.ndarray a, np.ndarray b, *, int|None min_periods=None, int|None ddof=1)
_ensure_numeric (x)
ArrayLike na_accum_func (ArrayLike values, accum_func, *, bool skipna)
Variables
bn = import_optional_dependency("bottleneck", errors="warn")
_BOTTLENECK_INSTALLED = bn is not None
bool _USE_BOTTLENECK = False
nanmin = _nanminmax("min", fill_value_typ="+inf")
nanmax = _nanminmax("max", fill_value_typ="-inf")
Function Documentation
_bn_ok_dtype()
bool pandas.core.nanops._bn_ok_dtype (DtypeObj dtype, str name) protected
Definition at line 154 of file nanops.py.
_datetimelike_compat()
F pandas.core.nanops._datetimelike_compat (F func) protected
If we have datetime64 or timedelta64 values, ensure we have a correct
mask before calling the wrapped function, then cast back afterwards.
Definition at line 383 of file nanops.py.
References _wrap_results().
_ensure_numeric()
pandas.core.nanops._ensure_numeric (x) protected
Definition at line 1678 of file nanops.py.
_get_counts()
np.floating | npt.NDArray[np.floating] pandas.core.nanops._get_counts (Shape values_shape, npt.NDArray[np.bool_] | None mask, AxisInt | None axis, np.dtype[np.floating] dtype = np.dtype(np.float64)) protected
Get the count of non-null values along an axis
Parameters
----------
values_shape : tuple of int
    shape tuple from values ndarray, used if mask is None
mask : Optional[ndarray[bool]]
    locations in values that should be considered missing
axis : Optional[int]
    axis to count along
dtype : type, optional
    type to use for count
Returns
-------
count : scalar or array
Definition at line 1458 of file nanops.py.
Referenced by _get_counts_nanvar(), nankurt(), nanmean(), and nanskew().
_get_counts_nanvar()
tuple[float | np.ndarray, float | np.ndarray] pandas.core.nanops._get_counts_nanvar (Shape values_shape, npt.NDArray[np.bool_] | None mask, AxisInt | None axis, int ddof, np.dtype dtype = np.dtype(np.float64)) protected
Get the count of non-null values along an axis, accounting
for degrees of freedom.
Parameters
----------
values_shape : Tuple[int, ...]
    shape tuple from values ndarray, used if mask is None
mask : Optional[ndarray[bool]]
    locations in values that should be considered missing
axis : Optional[int]
    axis to count along
ddof : int
    degrees of freedom
dtype : type, optional
    type to use for count
Returns
-------
count : int, np.nan or np.ndarray
d : int, np.nan or np.ndarray
Definition at line 858 of file nanops.py.
References _get_counts().
Referenced by nansem(), and nanvar().
_get_dtype_max()
np.dtype pandas.core.nanops._get_dtype_max (np.dtype dtype) protected
Definition at line 324 of file nanops.py.
_get_empty_reduction_result()
np.ndarray pandas.core.nanops._get_empty_reduction_result (Shape shape, AxisInt axis) protected
The result from a reduction on an empty ndarray.
Parameters
----------
shape : Tuple[int, ...]
axis : int
Returns
-------
np.ndarray
Definition at line 835 of file nanops.py.
Referenced by nanmedian().
_get_fill_value()
pandas.core.nanops._get_fill_value (DtypeObj dtype, Scalar | None fill_value = None, fill_value_typ = None) protected
return the correct fill value for the dtype of the values
Definition at line 187 of file nanops.py.
Referenced by _get_values().
_get_values()
tuple[np.ndarray, npt.NDArray[np.bool_] | None] pandas.core.nanops._get_values (np.ndarray values, bool skipna, Any fill_value = None, str | None fill_value_typ = None, npt.NDArray[np.bool_] | None mask = None) protected
Utility to get the values view, mask, dtype, dtype_max, and fill_value.
If both mask and fill_value/fill_value_typ are not None and skipna is True,
the values array will be copied.
For input arrays of boolean or integer dtypes, copies will only occur if a
precomputed mask, a fill_value/fill_value_typ, and skipna=True are
provided.
Parameters
----------
values : ndarray
    input array to potentially compute mask for
skipna : bool
    boolean for whether NaNs should be skipped
fill_value : Any
    value to fill NaNs with
fill_value_typ : str
    Set to '+inf' or '-inf' to handle dtype-specific infinities
mask : Optional[np.ndarray[bool]]
    nan-mask if known
Returns
-------
values : ndarray
    Potential copy of input value array
mask : Optional[ndarray[bool]]
    Mask for values, if deemed necessary to compute
Definition at line 253 of file nanops.py.
References _get_fill_value(), and _maybe_get_mask().
Referenced by nanall(), nanany(), nanargmax(), nanargmin(), nanmean(), nanmedian(), nansem(), nanstd(), and nansum().
_has_infs()
bool pandas.core.nanops._has_infs (result) protected
Definition at line 174 of file nanops.py.
_mask_datetimelike_result()
np.ndarray | np.datetime64 | np.timedelta64 | NaTType pandas.core.nanops._mask_datetimelike_result (np.ndarray | np.datetime64 | np.timedelta64 result, AxisInt | None axis, npt.NDArray[np.bool_] mask, np.ndarray orig_values) protected
Definition at line 652 of file nanops.py.
_maybe_arg_null_out()
np.ndarray | int pandas.core.nanops._maybe_arg_null_out (np.ndarray result, AxisInt | None axis, npt.NDArray[np.bool_] | None mask, bool skipna) protected
Definition at line 1431 of file nanops.py.
_maybe_get_mask()
npt.NDArray[np.bool_] | None pandas.core.nanops._maybe_get_mask (np.ndarray values, bool skipna, npt.NDArray[np.bool_] | None mask) protected
Compute a mask if and only if necessary.
This function will compute a mask iff it is necessary. Otherwise,
return the provided mask (potentially None) when a mask does not need to be
computed.
A mask is never necessary if the values array is of boolean or integer
dtypes, as these are incapable of storing NaNs. If passing a NaN-capable
dtype that is interpretable as either boolean or integer data (eg,
timedelta64), a mask must be provided.
If the skipna parameter is False, a new mask will not be computed.
The mask is computed using isna() by default. Setting invert=True selects
notna() as the masking function.
Parameters
----------
values : ndarray
    input array to potentially compute mask for
skipna : bool
    boolean for whether NaNs should be skipped
mask : Optional[ndarray]
    nan-mask if known
Returns
-------
Optional[np.ndarray[bool]]
Definition at line 209 of file nanops.py.
Referenced by _get_values(), nankurt(), nanprod(), nansem(), nanskew(), and nanvar().
_maybe_null_out()
np.ndarray | float | NaTType pandas.core.nanops._maybe_null_out (np.ndarray | float | NaTType result, AxisInt | None axis, npt.NDArray[np.bool_] | None mask, tuple[int, ...] shape, int min_count = 1) protected
Returns
-------
Dtype
    The product of all elements on a given axis. ( NaNs are treated as 1)
Definition at line 1499 of file nanops.py.
References check_below_min_count().
Referenced by nanprod(), nansem(), and nansum().
_na_for_min_count()
Scalar | np.ndarray pandas.core.nanops._na_for_min_count (np.ndarray values, AxisInt | None axis) protected
Return the missing value for `values`.
Parameters
----------
values : ndarray
axis : int or None
    axis for the reduction, required if values.ndim > 1.
Returns
-------
result : scalar or ndarray
    For 1-D values, returns a scalar of the correct missing type.
    For 2-D values, returns a 1-D array where each element is missing.
Definition at line 417 of file nanops.py.
Referenced by nansem().
_na_ok_dtype()
bool pandas.core.nanops._na_ok_dtype (DtypeObj dtype) protected
Definition at line 336 of file nanops.py.
_nanminmax()
pandas.core.nanops._nanminmax (meth, fill_value_typ) protected
Definition at line 1082 of file nanops.py.
_wrap_results()
pandas.core.nanops._wrap_results (result, np.dtype dtype, fill_value = None) protected
wrap our results if needed
Definition at line 342 of file nanops.py.
Referenced by _datetimelike_compat(), nanmedian(), and nanstd().
_zero_out_fperr()
pandas.core.nanops._zero_out_fperr (arg) protected
Definition at line 1578 of file nanops.py.
check_below_min_count()
bool pandas.core.nanops.check_below_min_count (tuple[int, ...] shape, npt.NDArray[np.bool_] | None mask, int min_count)
Check for the `min_count` keyword. Returns True if below `min_count` (when
missing value should be returned from the reduction).
Parameters
----------
shape : tuple
    The shape of the values (`values.shape`).
mask : ndarray[bool] or None
    Boolean numpy array (typically of same shape as `shape`) or None.
min_count : int
    Keyword passed through from sum/prod call.
Returns
-------
bool
Definition at line 1547 of file nanops.py.
Referenced by _maybe_null_out().
get_corr_func()
Callable[[np.ndarray, np.ndarray], float] pandas.core.nanops.get_corr_func (CorrelationMethod method)
Definition at line 1618 of file nanops.py.
maybe_operate_rowwise()
F pandas.core.nanops.maybe_operate_rowwise (F func)
NumPy operations on C-contiguous ndarrays with axis=1 can be
very slow if axis 1 >> axis 0.
Operate row-by-row and concatenate the results.
Definition at line 448 of file nanops.py.
na_accum_func()
ArrayLike pandas.core.nanops.na_accum_func (ArrayLike values, accum_func, * , bool skipna)
Cumulative function with skipna support.
Parameters
----------
values : np.ndarray or ExtensionArray
accum_func : {np.cumprod, np.maximum.accumulate, np.cumsum, np.minimum.accumulate}
skipna : bool
Returns
-------
np.ndarray or ExtensionArray
Definition at line 1714 of file nanops.py.
nanall()
bool pandas.core.nanops.nanall (np.ndarray values, * , AxisInt | None axis = None, bool skipna = True, npt.NDArray[np.bool_] | None mask = None)
Check if all elements along an axis evaluate to True.
Parameters
----------
values : ndarray
axis : int, optional
skipna : bool, default True
mask : ndarray[bool], optional
    nan-mask if known
Returns
-------
result : bool
Examples
--------
>>> from pandas.core import nanops
>>> s = pd.Series([1, 2, np.nan])
>>> nanops.nanall(s.values)
True
>>> from pandas.core import nanops
>>> s = pd.Series([1, 0])
>>> nanops.nanall(s.values)
False
Definition at line 543 of file nanops.py.
References _get_values().
nanany()
bool pandas.core.nanops.nanany (np.ndarray values, * , AxisInt | None axis = None, bool skipna = True, npt.NDArray[np.bool_] | None mask = None)
Check if any elements along an axis evaluate to True.
Parameters
----------
values : ndarray
axis : int, optional
skipna : bool, default True
mask : ndarray[bool], optional
    nan-mask if known
Returns
-------
result : bool
Examples
--------
>>> from pandas.core import nanops
>>> s = pd.Series([1, 2])
>>> nanops.nanany(s.values)
True
>>> from pandas.core import nanops
>>> s = pd.Series([np.nan])
>>> nanops.nanany(s.values)
False
Definition at line 482 of file nanops.py.
References _get_values().
nanargmax()
int | np.ndarray pandas.core.nanops.nanargmax (np.ndarray values, * , AxisInt | None axis = None, bool skipna = True, npt.NDArray[np.bool_] | None mask = None)
Parameters
----------
values : ndarray
axis : int, optional
skipna : bool, default True
mask : ndarray[bool], optional
    nan-mask if known
Returns
-------
result : int or ndarray[int]
    The index/indices  of max value in specified axis or -1 in the NA case
Examples
--------
>>> from pandas.core import nanops
>>> arr = np.array([1, 2, 3, np.nan, 4])
>>> nanops.nanargmax(arr)
4
>>> arr = np.array(range(12), dtype=np.float64).reshape(4, 3)
>>> arr[2:, 2] = np.nan
>>> arr
array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7., nan],
       [ 9., 10., nan]])
>>> nanops.nanargmax(arr, axis=1)
array([2, 2, 1, 1])
Definition at line 1109 of file nanops.py.
References _get_values().
nanargmin()
int | np.ndarray pandas.core.nanops.nanargmin (np.ndarray values, * , AxisInt | None axis = None, bool skipna = True, npt.NDArray[np.bool_] | None mask = None)
Parameters
----------
values : ndarray
axis : int, optional
skipna : bool, default True
mask : ndarray[bool], optional
    nan-mask if known
Returns
-------
result : int or ndarray[int]
    The index/indices of min value in specified axis or -1 in the NA case
Examples
--------
>>> from pandas.core import nanops
>>> arr = np.array([1, 2, 3, np.nan, 4])
>>> nanops.nanargmin(arr)
0
>>> arr = np.array(range(12), dtype=np.float64).reshape(4, 3)
>>> arr[2:, 0] = np.nan
>>> arr
array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [nan,  7.,  8.],
       [nan, 10., 11.]])
>>> nanops.nanargmin(arr, axis=1)
array([0, 0, 1, 1])
Definition at line 1155 of file nanops.py.
References _get_values().
nancorr()
float pandas.core.nanops.nancorr (np.ndarray a, np.ndarray b, * , CorrelationMethod method = "pearson", int | None min_periods = None)
a, b: ndarrays
Definition at line 1587 of file nanops.py.
nancov()
float pandas.core.nanops.nancov (np.ndarray a, np.ndarray b, * , int | None min_periods = None, int | None ddof = 1)
Definition at line 1651 of file nanops.py.
nankurt()
float pandas.core.nanops.nankurt (np.ndarray values, * , AxisInt | None axis = None, bool skipna = True, npt.NDArray[np.bool_] | None mask = None)
Compute the sample excess kurtosis
The statistic computed here is the adjusted Fisher-Pearson standardized
moment coefficient G2, computed directly from the second and fourth
central moment.
Parameters
----------
values : ndarray
axis : int, optional
skipna : bool, default True
mask : ndarray[bool], optional
    nan-mask if known
Returns
-------
result : float64
    Unless input is a float array, in which case use the same
    precision as the input array.
Examples
--------
>>> from pandas.core import nanops
>>> s = pd.Series([1, np.nan, 1, 3, 2])
>>> nanops.nankurt(s.values)
-1.2892561983471076
Definition at line 1291 of file nanops.py.
References _get_counts(), and _maybe_get_mask().
nanmean()
float pandas.core.nanops.nanmean (np.ndarray values, * , AxisInt | None axis = None, bool skipna = True, npt.NDArray[np.bool_] | None mask = None)
Compute the mean of the element along an axis ignoring NaNs
Parameters
----------
values : ndarray
axis : int, optional
skipna : bool, default True
mask : ndarray[bool], optional
    nan-mask if known
Returns
-------
float
    Unless input is a float array, in which case use the same
    precision as the input array.
Examples
--------
>>> from pandas.core import nanops
>>> s = pd.Series([1, 2, np.nan])
>>> nanops.nanmean(s.values)
1.5
Definition at line 673 of file nanops.py.
References _get_counts(), and _get_values().
nanmedian()
pandas.core.nanops.nanmedian (values, * , AxisInt | None axis = None, bool skipna = True, mask = None)
Parameters
----------
values : ndarray
axis : int, optional
skipna : bool, default True
mask : ndarray[bool], optional
    nan-mask if known
Returns
-------
result : float
    Unless input is a float array, in which case use the same
    precision as the input array.
Examples
--------
>>> from pandas.core import nanops
>>> s = pd.Series([1, np.nan, 2, 2])
>>> nanops.nanmedian(s.values)
2.0
Definition at line 737 of file nanops.py.
References _get_empty_reduction_result(), _get_values(), and _wrap_results().
nanprod()
float pandas.core.nanops.nanprod (np.ndarray values, * , AxisInt | None axis = None, bool skipna = True, int min_count = 0, npt.NDArray[np.bool_] | None mask = None)
Parameters
----------
values : ndarray[dtype]
axis : int, optional
skipna : bool, default True
min_count: int, default 0
mask : ndarray[bool], optional
    nan-mask if known
Returns
-------
Dtype
    The product of all elements on a given axis. ( NaNs are treated as 1)
Examples
--------
>>> from pandas.core import nanops
>>> s = pd.Series([1, 2, 3, np.nan])
>>> nanops.nanprod(s.values)
6.0
Definition at line 1388 of file nanops.py.
References _maybe_get_mask(), and _maybe_null_out().
nansem()
float pandas.core.nanops.nansem (np.ndarray values, * , AxisInt | None axis = None, bool skipna = True, int ddof = 1, npt.NDArray[np.bool_] | None mask = None)
Compute the standard error in the mean along given axis while ignoring NaNs
Parameters
----------
values : ndarray
axis : int, optional
skipna : bool, default True
ddof : int, default 1
    Delta Degrees of Freedom. The divisor used in calculations is N - ddof,
    where N represents the number of elements.
mask : ndarray[bool], optional
    nan-mask if known
Returns
-------
result : float64
    Unless input is a float array, in which case use the same
    precision as the input array.
Examples
--------
>>> from pandas.core import nanops
>>> s = pd.Series([1, np.nan, 2, 3])
>>> nanops.nansem(s.values)
 0.5773502691896258
Definition at line 1030 of file nanops.py.
References _get_counts_nanvar(), _get_values(), _maybe_get_mask(), _maybe_null_out(), _na_for_min_count(), and nanvar().
nanskew()
float pandas.core.nanops.nanskew (np.ndarray values, * , AxisInt | None axis = None, bool skipna = True, npt.NDArray[np.bool_] | None mask = None)
Compute the sample skewness.
The statistic computed here is the adjusted Fisher-Pearson standardized
moment coefficient G1. The algorithm computes this coefficient directly
from the second and third central moment.
Parameters
----------
values : ndarray
axis : int, optional
skipna : bool, default True
mask : ndarray[bool], optional
    nan-mask if known
Returns
-------
result : float64
    Unless input is a float array, in which case use the same
    precision as the input array.
Examples
--------
>>> from pandas.core import nanops
>>> s = pd.Series([1, np.nan, 1, 2])
>>> nanops.nanskew(s.values)
1.7320508075688787
Definition at line 1203 of file nanops.py.
References _get_counts(), and _maybe_get_mask().
nanstd()
pandas.core.nanops.nanstd (values, * , AxisInt | None axis = None, bool skipna = True, int ddof = 1, mask = None)
Compute the standard deviation along given axis while ignoring NaNs
Parameters
----------
values : ndarray
axis : int, optional
skipna : bool, default True
ddof : int, default 1
    Delta Degrees of Freedom. The divisor used in calculations is N - ddof,
    where N represents the number of elements.
mask : ndarray[bool], optional
    nan-mask if known
Returns
-------
result : float
    Unless input is a float array, in which case use the same
    precision as the input array.
Examples
--------
>>> from pandas.core import nanops
>>> s = pd.Series([1, np.nan, 2, 3])
>>> nanops.nanstd(s.values)
1.0
Definition at line 909 of file nanops.py.
References _get_values(), _wrap_results(), and nanvar().
nansum()
float pandas.core.nanops.nansum (np.ndarray values, * , AxisInt | None axis = None, bool skipna = True, int min_count = 0, npt.NDArray[np.bool_] | None mask = None)
Sum the elements along an axis ignoring NaNs
Parameters
----------
values : ndarray[dtype]
axis : int, optional
skipna : bool, default True
min_count: int, default 0
mask : ndarray[bool], optional
    nan-mask if known
Returns
-------
result : dtype
Examples
--------
>>> from pandas.core import nanops
>>> s = pd.Series([1, 2, np.nan])
>>> nanops.nansum(s.values)
3.0
Definition at line 607 of file nanops.py.
References _get_values(), and _maybe_null_out().
nanvar()
pandas.core.nanops.nanvar (np.ndarray values, * , AxisInt | None axis = None, bool skipna = True, int ddof = 1, mask = None)
Compute the variance along given axis while ignoring NaNs
Parameters
----------
values : ndarray
axis : int, optional
skipna : bool, default True
ddof : int, default 1
    Delta Degrees of Freedom. The divisor used in calculations is N - ddof,
    where N represents the number of elements.
mask : ndarray[bool], optional
    nan-mask if known
Returns
-------
result : float
    Unless input is a float array, in which case use the same
    precision as the input array.
Examples
--------
>>> from pandas.core import nanops
>>> s = pd.Series([1, np.nan, 2, 3])
>>> nanops.nanvar(s.values)
1.0
Definition at line 956 of file nanops.py.
References _get_counts_nanvar(), and _maybe_get_mask().
Referenced by nansem(), and nanstd().
set_use_bottleneck()
None pandas.core.nanops.set_use_bottleneck (bool v = True)
Definition at line 57 of file nanops.py.
Variable Documentation
_BOTTLENECK_INSTALLED
pandas.core.nanops._BOTTLENECK_INSTALLED = bn is not None protected
Definition at line 53 of file nanops.py.
_USE_BOTTLENECK
bool pandas.core.nanops._USE_BOTTLENECK = False protected
Definition at line 54 of file nanops.py.
bn
pandas.core.nanops.bn = import_optional_dependency("bottleneck", errors="warn")
Definition at line 52 of file nanops.py.
nanmax
pandas.core.nanops.nanmax = _nanminmax("max", fill_value_typ="-inf")
Definition at line 1106 of file nanops.py.
nanmin
pandas.core.nanops.nanmin = _nanminmax("min", fill_value_typ="+inf")
Definition at line 1105 of file nanops.py.