Code Cloning Analysis: scipy.sparse.linalg._interface._AdjointMatrixOperator Class Reference
scipy.sparse.linalg._interface._AdjointMatrixOperator Class Reference
Public Member Functions
__init__ (self, adjoint)
dtype (self)
Public Member Functions inherited from scipy.sparse.linalg._interface.MatrixLinearOperator
__init__ (self, A)
Public Member Functions inherited from scipy.sparse.linalg._interface.LinearOperator
__new__ (cls, *args, **kwargs)
__init__ (self, dtype, shape)
matvec (self, x)
rmatvec (self, x)
matmat (self, X)
rmatmat (self, X)
__call__ (self, x)
__mul__ (self, x)
__truediv__ (self, other)
dot (self, x)
__matmul__ (self, other)
__rmatmul__ (self, other)
__rmul__ (self, x)
__pow__ (self, p)
__add__ (self, x)
__neg__ (self)
__sub__ (self, x)
__repr__ (self)
adjoint (self)
transpose (self)
Protected Member Functions
_adjoint (self)
Protected Member Functions inherited from scipy.sparse.linalg._interface.MatrixLinearOperator
_matmat (self, X)
Protected Member Functions inherited from scipy.sparse.linalg._interface.LinearOperator
_init_dtype (self)
_matvec (self, x)
_rmatvec (self, x)
_rmatmat (self, X)
_rdot (self, x)
_transpose (self)
Private Attributes
__adjoint = adjoint
Additional Inherited Members
Public Attributes inherited from scipy.sparse.linalg._interface.MatrixLinearOperator
A = A
tuple args = (A,)
Public Attributes inherited from scipy.sparse.linalg._interface.LinearOperator
shape = shape
Static Public Attributes inherited from scipy.sparse.linalg._interface.LinearOperator
int ndim = 2
Properties inherited from scipy.sparse.linalg._interface.LinearOperator
H = property(adjoint)
T = property(transpose)
Detailed Description
Definition at line 805 of file _interface.py.
Constructor & Destructor Documentation
__init__()
scipy.sparse.linalg._interface._AdjointMatrixOperator.__init__ (self, adjoint)
Definition at line 806 of file _interface.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
_adjoint()
scipy.sparse.linalg._interface._AdjointMatrixOperator._adjoint (self) protected
Default implementation of _adjoint; defers to rmatvec.
Reimplemented from scipy.sparse.linalg._interface.MatrixLinearOperator.
Definition at line 816 of file _interface.py.
dtype()
scipy.sparse.linalg._interface._AdjointMatrixOperator.dtype (self)
Reimplemented from scipy.sparse.linalg._interface.LinearOperator.
Definition at line 813 of file _interface.py.
Referenced by pandas.core.arrays.base.ExtensionScalarOpsMixin._create_method(), scipy.sparse._index.IndexMixin._getcol(), pandas.core.generic.NDFrame._inplace_method(), scipy.sparse._index.IndexMixin._raise_on_1d_array_slice(), pandas.core.strings.object_array.ObjectStringArrayMixin._str_map(), numpy.matrixlib.defmatrix.matrix.H(), numpy.core.records.record.pprint(), pandas.core.frame.DataFrame.quantile(), and pandas.core.generic.NDFrame.rank().
Member Data Documentation
__adjoint
scipy.sparse.linalg._interface._AdjointMatrixOperator.__adjoint = adjoint private
Definition at line 808 of file _interface.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/sparse/linalg/_interface.py