Code Cloning Analysis: matplotlib.tests.test_colorbar Namespace Reference
matplotlib.tests.test_colorbar Namespace Reference
Functions
_get_cmap_norms ()
_colorbar_extension_shape (spacing)
_colorbar_extension_length (spacing)
test_colorbar_extension_shape ()
test_colorbar_extension_length ()
test_colorbar_extension_inverted_axis (orientation, extend, expected)
test_colorbar_positioning (use_gridspec)
test_colorbar_single_ax_panchor_false ()
test_colorbar_single_ax_panchor_east (constrained)
test_contour_colorbar ()
test_gridspec_make_colorbar ()
test_colorbar_single_scatter ()
test_remove_from_figure (nested_gridspecs, use_gridspec)
test_remove_from_figure_cl ()
test_colorbarbase ()
test_parentless_mappable ()
test_colorbar_closed_patch ()
test_colorbar_ticks ()
test_colorbar_minorticks_on_off ()
test_cbar_minorticks_for_rc_xyminortickvisible ()
test_colorbar_autoticks ()
test_colorbar_autotickslog ()
test_colorbar_get_ticks ()
test_colorbar_lognorm_extension (extend)
test_colorbar_powernorm_extension ()
test_colorbar_axes_kw ()
test_colorbar_log_minortick_labels ()
test_colorbar_renorm ()
test_colorbar_format (fmt)
test_colorbar_scale_reset ()
test_colorbar_get_ticks_2 ()
test_colorbar_inverted_ticks ()
test_mappable_no_alpha ()
test_mappable_2d_alpha ()
test_colorbar_label ()
test_keeping_xlabel ()
test_colorbar_int (clim)
test_anchored_cbar_position_using_specgrid ()
test_colorbar_change_lim_scale ()
test_axes_handles_same_functions (fig_ref, fig_test)
test_inset_colorbar_layout ()
test_twoslope_colorbar ()
test_remove_cb_whose_mappable_has_no_figure (fig_ref, fig_test)
test_aspects ()
test_proportional_colorbars ()
test_colorbar_extend_drawedges ()
test_colorbar_contourf_extend_patches ()
test_negative_boundarynorm ()
test_centerednorm ()
test_nonorm ()
test_boundaries ()
test_colorbar_no_warning_rcparams_grid_true ()
test_colorbar_set_formatter_locator ()
test_colorbar_extend_alpha ()
test_offset_text_loc ()
test_title_text_loc ()
test_passing_location (fig_ref, fig_test)
test_colorbar_errors (kwargs, error, message)
test_colorbar_axes_parmeters ()
test_colorbar_wrong_figure ()
test_colorbar_format_string_and_old ()
Function Documentation
_colorbar_extension_length()
matplotlib.tests.test_colorbar._colorbar_extension_length (spacing) protected
Produce 12 colorbars with variable length extensions for either
uniform or proportional spacing.
Helper function for test_colorbar_extension_length.
Definition at line 74 of file test_colorbar.py.
References _get_cmap_norms().
Referenced by test_colorbar_extension_length().
_colorbar_extension_shape()
matplotlib.tests.test_colorbar._colorbar_extension_shape (spacing) protected
Produce 4 colorbars with rectangular extensions for either uniform
or proportional spacing.
Helper function for test_colorbar_extension_shape.
Definition at line 42 of file test_colorbar.py.
References _get_cmap_norms().
Referenced by test_colorbar_extension_shape().
_get_cmap_norms()
matplotlib.tests.test_colorbar._get_cmap_norms () protected
Define a colormap and appropriate norms for each of the four
possible settings of the extend keyword.
Helper function for _colorbar_extension_shape and
colorbar_extension_length.
Definition at line 22 of file test_colorbar.py.
Referenced by _colorbar_extension_length(), and _colorbar_extension_shape().
test_anchored_cbar_position_using_specgrid()
matplotlib.tests.test_colorbar.test_anchored_cbar_position_using_specgrid ()
Definition at line 755 of file test_colorbar.py.
test_aspects()
matplotlib.tests.test_colorbar.test_aspects ()
Definition at line 903 of file test_colorbar.py.
test_axes_handles_same_functions()
matplotlib.tests.test_colorbar.test_axes_handles_same_functions (fig_ref, fig_test)
Definition at line 851 of file test_colorbar.py.
test_boundaries()
matplotlib.tests.test_colorbar.test_boundaries ()
Definition at line 1096 of file test_colorbar.py.
test_cbar_minorticks_for_rc_xyminortickvisible()
matplotlib.tests.test_colorbar.test_cbar_minorticks_for_rc_xyminortickvisible ()
issue gh-16468.
Making sure that minor ticks on the colorbar are turned on
(internally) using the cbar.minorticks_on() method when
rcParams['xtick.minor.visible'] = True (for horizontal cbar)
rcParams['ytick.minor.visible'] = True (for vertical cbar).
Using cbar.minorticks_on() ensures that the minor ticks
don't overflow into the extend regions of the colorbar.
Definition at line 425 of file test_colorbar.py.
References matplotlib.rc_context().
test_centerednorm()
matplotlib.tests.test_colorbar.test_centerednorm ()
Definition at line 1069 of file test_colorbar.py.
test_colorbar_autoticks()
matplotlib.tests.test_colorbar.test_colorbar_autoticks ()
Definition at line 453 of file test_colorbar.py.
test_colorbar_autotickslog()
matplotlib.tests.test_colorbar.test_colorbar_autotickslog ()
Definition at line 478 of file test_colorbar.py.
test_colorbar_axes_kw()
matplotlib.tests.test_colorbar.test_colorbar_axes_kw ()
Definition at line 560 of file test_colorbar.py.
test_colorbar_axes_parmeters()
matplotlib.tests.test_colorbar.test_colorbar_axes_parmeters ()
Definition at line 1211 of file test_colorbar.py.
test_colorbar_change_lim_scale()
matplotlib.tests.test_colorbar.test_colorbar_change_lim_scale ()
Definition at line 839 of file test_colorbar.py.
test_colorbar_closed_patch()
matplotlib.tests.test_colorbar.test_colorbar_closed_patch ()
Definition at line 330 of file test_colorbar.py.
test_colorbar_contourf_extend_patches()
matplotlib.tests.test_colorbar.test_colorbar_contourf_extend_patches ()
Definition at line 1012 of file test_colorbar.py.
test_colorbar_errors()
matplotlib.tests.test_colorbar.test_colorbar_errors (kwargs, error, message)
Definition at line 1202 of file test_colorbar.py.
test_colorbar_extend_alpha()
matplotlib.tests.test_colorbar.test_colorbar_extend_alpha ()
Definition at line 1147 of file test_colorbar.py.
test_colorbar_extend_drawedges()
matplotlib.tests.test_colorbar.test_colorbar_extend_drawedges ()
Definition at line 964 of file test_colorbar.py.
test_colorbar_extension_inverted_axis()
matplotlib.tests.test_colorbar.test_colorbar_extension_inverted_axis (orientation, extend, expected)
Test extension color with an inverted axis
Definition at line 135 of file test_colorbar.py.
test_colorbar_extension_length()
matplotlib.tests.test_colorbar.test_colorbar_extension_length ()
Test variable length colorbar extensions.
Definition at line 121 of file test_colorbar.py.
References _colorbar_extension_length().
test_colorbar_extension_shape()
matplotlib.tests.test_colorbar.test_colorbar_extension_shape ()
Test rectangular colorbar extensions.
Definition at line 108 of file test_colorbar.py.
References _colorbar_extension_shape().
test_colorbar_format()
matplotlib.tests.test_colorbar.test_colorbar_format (fmt)
Definition at line 615 of file test_colorbar.py.
test_colorbar_format_string_and_old()
matplotlib.tests.test_colorbar.test_colorbar_format_string_and_old ()
Definition at line 1237 of file test_colorbar.py.
test_colorbar_get_ticks()
matplotlib.tests.test_colorbar.test_colorbar_get_ticks ()
Definition at line 502 of file test_colorbar.py.
test_colorbar_get_ticks_2()
matplotlib.tests.test_colorbar.test_colorbar_get_ticks_2 ()
Definition at line 663 of file test_colorbar.py.
test_colorbar_int()
matplotlib.tests.test_colorbar.test_colorbar_int (clim)
Definition at line 745 of file test_colorbar.py.
test_colorbar_inverted_ticks()
matplotlib.tests.test_colorbar.test_colorbar_inverted_ticks ()
Definition at line 671 of file test_colorbar.py.
test_colorbar_label()
matplotlib.tests.test_colorbar.test_colorbar_label ()
Test the label parameter. It should just be mapped to the xlabel/ylabel of
the axes, depending on the orientation.
Definition at line 712 of file test_colorbar.py.
test_colorbar_log_minortick_labels()
matplotlib.tests.test_colorbar.test_colorbar_log_minortick_labels ()
Definition at line 569 of file test_colorbar.py.
test_colorbar_lognorm_extension()
matplotlib.tests.test_colorbar.test_colorbar_lognorm_extension (extend)
Definition at line 544 of file test_colorbar.py.
test_colorbar_minorticks_on_off()
matplotlib.tests.test_colorbar.test_colorbar_minorticks_on_off ()
Definition at line 374 of file test_colorbar.py.
test_colorbar_no_warning_rcparams_grid_true()
matplotlib.tests.test_colorbar.test_colorbar_no_warning_rcparams_grid_true ()
Definition at line 1103 of file test_colorbar.py.
test_colorbar_positioning()
matplotlib.tests.test_colorbar.test_colorbar_positioning (use_gridspec)
Definition at line 163 of file test_colorbar.py.
test_colorbar_powernorm_extension()
matplotlib.tests.test_colorbar.test_colorbar_powernorm_extension ()
Definition at line 552 of file test_colorbar.py.
test_colorbar_renorm()
matplotlib.tests.test_colorbar.test_colorbar_renorm ()
Definition at line 584 of file test_colorbar.py.
test_colorbar_scale_reset()
matplotlib.tests.test_colorbar.test_colorbar_scale_reset ()
Definition at line 639 of file test_colorbar.py.
test_colorbar_set_formatter_locator()
matplotlib.tests.test_colorbar.test_colorbar_set_formatter_locator ()
Definition at line 1115 of file test_colorbar.py.
test_colorbar_single_ax_panchor_east()
matplotlib.tests.test_colorbar.test_colorbar_single_ax_panchor_east (constrained)
Definition at line 229 of file test_colorbar.py.
test_colorbar_single_ax_panchor_false()
matplotlib.tests.test_colorbar.test_colorbar_single_ax_panchor_false ()
Definition at line 217 of file test_colorbar.py.
test_colorbar_single_scatter()
matplotlib.tests.test_colorbar.test_colorbar_single_scatter ()
Definition at line 269 of file test_colorbar.py.
test_colorbar_ticks()
matplotlib.tests.test_colorbar.test_colorbar_ticks ()
Definition at line 360 of file test_colorbar.py.
test_colorbar_wrong_figure()
matplotlib.tests.test_colorbar.test_colorbar_wrong_figure ()
Definition at line 1223 of file test_colorbar.py.
test_colorbarbase()
matplotlib.tests.test_colorbar.test_colorbarbase ()
Definition at line 317 of file test_colorbar.py.
test_contour_colorbar()
matplotlib.tests.test_colorbar.test_contour_colorbar ()
Definition at line 239 of file test_colorbar.py.
test_gridspec_make_colorbar()
matplotlib.tests.test_colorbar.test_gridspec_make_colorbar ()
Definition at line 251 of file test_colorbar.py.
test_inset_colorbar_layout()
matplotlib.tests.test_colorbar.test_inset_colorbar_layout ()
Definition at line 867 of file test_colorbar.py.
test_keeping_xlabel()
matplotlib.tests.test_colorbar.test_keeping_xlabel ()
Definition at line 734 of file test_colorbar.py.
test_mappable_2d_alpha()
matplotlib.tests.test_colorbar.test_mappable_2d_alpha ()
Definition at line 700 of file test_colorbar.py.
test_mappable_no_alpha()
matplotlib.tests.test_colorbar.test_mappable_no_alpha ()
Definition at line 692 of file test_colorbar.py.
test_negative_boundarynorm()
matplotlib.tests.test_colorbar.test_negative_boundarynorm ()
Definition at line 1040 of file test_colorbar.py.
test_nonorm()
matplotlib.tests.test_colorbar.test_nonorm ()
Definition at line 1081 of file test_colorbar.py.
test_offset_text_loc()
matplotlib.tests.test_colorbar.test_offset_text_loc ()
Definition at line 1153 of file test_colorbar.py.
test_parentless_mappable()
matplotlib.tests.test_colorbar.test_parentless_mappable ()
Definition at line 323 of file test_colorbar.py.
test_passing_location()
matplotlib.tests.test_colorbar.test_passing_location (fig_ref, fig_test)
Definition at line 1181 of file test_colorbar.py.
test_proportional_colorbars()
matplotlib.tests.test_colorbar.test_proportional_colorbars ()
Definition at line 938 of file test_colorbar.py.
test_remove_cb_whose_mappable_has_no_figure()
matplotlib.tests.test_colorbar.test_remove_cb_whose_mappable_has_no_figure (fig_ref, fig_test)
Definition at line 897 of file test_colorbar.py.
test_remove_from_figure()
matplotlib.tests.test_colorbar.test_remove_from_figure (nested_gridspecs, use_gridspec)
Test `remove` with the specified ``use_gridspec`` setting.
Definition at line 283 of file test_colorbar.py.
test_remove_from_figure_cl()
matplotlib.tests.test_colorbar.test_remove_from_figure_cl ()
Test `remove` with constrained_layout.
Definition at line 302 of file test_colorbar.py.
References matplotlib.rc_context().
test_title_text_loc()
matplotlib.tests.test_colorbar.test_title_text_loc ()
Definition at line 1166 of file test_colorbar.py.
test_twoslope_colorbar()
matplotlib.tests.test_colorbar.test_twoslope_colorbar ()
Definition at line 883 of file test_colorbar.py.