Code Cloning Analysis: sklearn.manifold._mds Namespace Reference
sklearn.manifold._mds Namespace Reference
Classes
class MDS
Functions
_smacof_single (dissimilarities, metric=True, n_components=2, init=None, max_iter=300, verbose=0, eps=1e-6, random_state=None, normalized_stress=False)
smacof (dissimilarities, *, metric=True, n_components=2, init=None, n_init="warn", n_jobs=None, max_iter=300, verbose=0, eps=1e-6, random_state=None, return_n_iter=False, normalized_stress="auto")
Detailed Description
Multi-dimensional Scaling (MDS).
Function Documentation
_smacof_single()
sklearn.manifold._mds._smacof_single (dissimilarities, metric = True, n_components = 2, init = None, max_iter = 300, verbose = 0, eps = 1e-6, random_state = None, normalized_stress = False) protected
Computes multidimensional scaling using SMACOF algorithm.
Parameters
----------
dissimilarities : ndarray of shape (n_samples, n_samples)
    Pairwise dissimilarities between the points. Must be symmetric.
metric : bool, default=True
    Compute metric or nonmetric SMACOF algorithm.
    When ``False`` (i.e. non-metric MDS), dissimilarities with 0 are considered as
    missing values.
n_components : int, default=2
    Number of dimensions in which to immerse the dissimilarities. If an
    ``init`` array is provided, this option is overridden and the shape of
    ``init`` is used to determine the dimensionality of the embedding
    space.
init : ndarray of shape (n_samples, n_components), default=None
    Starting configuration of the embedding to initialize the algorithm. By
    default, the algorithm is initialized with a randomly chosen array.
max_iter : int, default=300
    Maximum number of iterations of the SMACOF algorithm for a single run.
verbose : int, default=0
    Level of verbosity.
eps : float, default=1e-6
    The tolerance with respect to stress (normalized by the sum of squared
    embedding distances) at which to declare convergence.
    .. versionchanged:: 1.7
       The default value for `eps` has changed from 1e-3 to 1e-6, as a result
       of a bugfix in the computation of the convergence criterion.
random_state : int, RandomState instance or None, default=None
    Determines the random number generator used to initialize the centers.
    Pass an int for reproducible results across multiple function calls.
    See :term:`Glossary <random_state>`.
normalized_stress : bool, default=False
    Whether to return normalized stress value (Stress-1) instead of raw
    stress.
    .. versionadded:: 1.2
    .. versionchanged:: 1.7
       Normalized stress is now supported for metric MDS as well.
Returns
-------
X : ndarray of shape (n_samples, n_components)
    Coordinates of the points in a ``n_components``-space.
stress : float
    The final value of the stress (sum of squared distance of the
    disparities and the distances for all constrained points).
    If `normalized_stress=True`, returns Stress-1.
    A value of 0 indicates "perfect" fit, 0.025 excellent, 0.05 good,
    0.1 fair, and 0.2 poor [1]_.
n_iter : int
    The number of iterations corresponding to the best stress.
References
----------
.. [1] "Nonmetric multidimensional scaling: a numerical method" Kruskal, J.
       Psychometrika, 29 (1964)
.. [2] "Multidimensional scaling by optimizing goodness of fit to a nonmetric
       hypothesis" Kruskal, J. Psychometrika, 29, (1964)
.. [3] "Modern Multidimensional Scaling - Theory and Applications" Borg, I.;
       Groenen P. Springer Series in Statistics (1997)
Definition at line 23 of file _mds.py.
Referenced by smacof().
smacof()
sklearn.manifold._mds.smacof (dissimilarities, * , metric = True, n_components = 2, init = None, n_init = "warn", n_jobs = None, max_iter = 300, verbose = 0, eps = 1e-6, random_state = None, return_n_iter = False, normalized_stress = "auto")
Compute multidimensional scaling using the SMACOF algorithm.
The SMACOF (Scaling by MAjorizing a COmplicated Function) algorithm is a
multidimensional scaling algorithm which minimizes an objective function
(the *stress*) using a majorization technique. Stress majorization, also
known as the Guttman Transform, guarantees a monotone convergence of
stress, and is more powerful than traditional techniques such as gradient
descent.
The SMACOF algorithm for metric MDS can be summarized by the following
steps:
1. Set an initial start configuration, randomly or not.
2. Compute the stress
3. Compute the Guttman Transform
4. Iterate 2 and 3 until convergence.
The nonmetric algorithm adds a monotonic regression step before computing
the stress.
Parameters
----------
dissimilarities : array-like of shape (n_samples, n_samples)
    Pairwise dissimilarities between the points. Must be symmetric.
metric : bool, default=True
    Compute metric or nonmetric SMACOF algorithm.
    When ``False`` (i.e. non-metric MDS), dissimilarities with 0 are considered as
    missing values.
n_components : int, default=2
    Number of dimensions in which to immerse the dissimilarities. If an
    ``init`` array is provided, this option is overridden and the shape of
    ``init`` is used to determine the dimensionality of the embedding
    space.
init : array-like of shape (n_samples, n_components), default=None
    Starting configuration of the embedding to initialize the algorithm. By
    default, the algorithm is initialized with a randomly chosen array.
n_init : int, default=8
    Number of times the SMACOF algorithm will be run with different
    initializations. The final results will be the best output of the runs,
    determined by the run with the smallest final stress. If ``init`` is
    provided, this option is overridden and a single run is performed.
    .. versionchanged:: 1.9
       The default value for `n_iter` will change from 8 to 1 in version 1.9.
n_jobs : int, default=None
    The number of jobs to use for the computation. If multiple
    initializations are used (``n_init``), each run of the algorithm is
    computed in parallel.
    ``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.
    ``-1`` means using all processors. See :term:`Glossary <n_jobs>`
    for more details.
max_iter : int, default=300
    Maximum number of iterations of the SMACOF algorithm for a single run.
verbose : int, default=0
    Level of verbosity.
eps : float, default=1e-6
    The tolerance with respect to stress (normalized by the sum of squared
    embedding distances) at which to declare convergence.
    .. versionchanged:: 1.7
       The default value for `eps` has changed from 1e-3 to 1e-6, as a result
       of a bugfix in the computation of the convergence criterion.
random_state : int, RandomState instance or None, default=None
    Determines the random number generator used to initialize the centers.
    Pass an int for reproducible results across multiple function calls.
    See :term:`Glossary <random_state>`.
return_n_iter : bool, default=False
    Whether or not to return the number of iterations.
normalized_stress : bool or "auto", default="auto"
    Whether to return normalized stress value (Stress-1) instead of raw
    stress. By default, metric MDS returns raw stress while non-metric MDS
    returns normalized stress.
    .. versionadded:: 1.2
    .. versionchanged:: 1.4
       The default value changed from `False` to `"auto"` in version 1.4.
    .. versionchanged:: 1.7
       Normalized stress is now supported for metric MDS as well.
Returns
-------
X : ndarray of shape (n_samples, n_components)
    Coordinates of the points in a ``n_components``-space.
stress : float
    The final value of the stress (sum of squared distance of the
    disparities and the distances for all constrained points).
    If `normalized_stress=True`, returns Stress-1.
    A value of 0 indicates "perfect" fit, 0.025 excellent, 0.05 good,
    0.1 fair, and 0.2 poor [1]_.
n_iter : int
    The number of iterations corresponding to the best stress. Returned
    only if ``return_n_iter`` is set to ``True``.
References
----------
.. [1] "Nonmetric multidimensional scaling: a numerical method" Kruskal, J.
       Psychometrika, 29 (1964)
.. [2] "Multidimensional scaling by optimizing goodness of fit to a nonmetric
       hypothesis" Kruskal, J. Psychometrika, 29, (1964)
.. [3] "Modern Multidimensional Scaling - Theory and Applications" Borg, I.;
       Groenen P. Springer Series in Statistics (1997)
Examples
--------
>>> import numpy as np
>>> from sklearn.manifold import smacof
>>> from sklearn.metrics import euclidean_distances
>>> X = np.array([[0, 1, 2], [1, 0, 3], [2, 3, 0]])
>>> dissimilarities = euclidean_distances(X)
>>> Z, stress = smacof(
...     dissimilarities, n_components=2, n_init=1, eps=1e-6, random_state=42
...)
>>> Z.shape
(3, 2)
>>> np.round(stress, 6).item()
3.2e-05
Definition at line 210 of file _mds.py.
References _smacof_single().
Referenced by sklearn.manifold._mds.MDS.fit_transform().