Code Cloning Analysis: numpy.lib._datasource._FileOpeners Class Reference
numpy.lib._datasource._FileOpeners Class Reference
Public Member Functions
__init__ (self)
keys (self)
__getitem__ (self, key)
Protected Member Functions
_load (self)
Protected Attributes
bool _loaded = False
dict _file_openers = {None: io.open}
Detailed Description
Container for different methods to open (un-)compressed files.
`_FileOpeners` contains a dictionary that holds one method for each
supported file format. Attribute lookup is implemented in such a way
that an instance of `_FileOpeners` itself can be indexed with the keys
of that dictionary. Currently uncompressed files as well as files
compressed with ``gzip``, ``bz2`` or ``xz`` compression are supported.
Notes
-----
`_file_openers`, an instance of `_FileOpeners`, is made available for
use in the `_datasource` module.
Examples
--------
>>> import gzip
>>> np.lib._datasource._file_openers.keys()
[None, '.bz2', '.gz', '.xz', '.lzma']
>>> np.lib._datasource._file_openers['.gz'] is gzip.open
True
Definition at line 74 of file _datasource.py.
Constructor & Destructor Documentation
__init__()
numpy.lib._datasource._FileOpeners.__init__ (self)
Definition at line 99 of file _datasource.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__getitem__()
numpy.lib._datasource._FileOpeners.__getitem__ (self, key)
Definition at line 149 of file _datasource.py.
_load()
numpy.lib._datasource._FileOpeners._load (self) protected
Definition at line 103 of file _datasource.py.
Referenced by PIL.BlpImagePlugin._BLPBaseDecoder.decode(), and keys().
keys()
numpy.lib._datasource._FileOpeners.keys (self)
Return the keys of currently supported file openers.
Parameters
----------
None
Returns
-------
keys : list
    The keys are None for uncompressed files and the file extension
    strings (i.e. ``'.gz'``, ``'.xz'``) for supported compression
    methods.
Definition at line 130 of file _datasource.py.
References _file_openers, _load(), and keys().
Referenced by sklearn.utils._bunch.Bunch._set_deprecated(), pandas.io.pytables.HDFStore.copy(), scipy.sparse._dok._dok_base.get(), pandas.io.pytables.HDFStore.info(), keys(), pandas.io.pytables.HDFStore.keys(), fontTools.varLib.instancer.AxisLimits.normalize(), pip._vendor.pyparsing.results.ParseResults.pprint(), pyparsing.results.ParseResults.pprint(), scipy.sparse._dok._dok_base.resize(), scipy.sparse._dok._dok_base.tocoo(), and pip._vendor.distlib.metadata.LegacyMetadata.todict().
Member Data Documentation
_file_openers
dict numpy.lib._datasource._FileOpeners._file_openers = {None: io.open} protected
Definition at line 101 of file _datasource.py.
Referenced by keys().
_loaded
bool numpy.lib._datasource._FileOpeners._loaded = False protected
Definition at line 100 of file _datasource.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/lib/_datasource.py