Code Cloning Analysis: fontTools.pens.basePen.AbstractPen Class Reference
fontTools.pens.basePen.AbstractPen Class Reference
Public Member Functions
None moveTo (self, Tuple[float, float] pt)
None lineTo (self, Tuple[float, float] pt)
None curveTo (self, *Tuple[float, float] points)
None qCurveTo (self, *Tuple[float, float] points)
None closePath (self)
None endPath (self)
None addComponent (self, str glyphName, Tuple[float, float, float, float, float, float] transformation)
None addVarComponent (self, str glyphName, DecomposedTransform transformation, Dict[str, float] location)
Detailed Description
Definition at line 62 of file basePen.py.
Member Function Documentation
addComponent()
None fontTools.pens.basePen.AbstractPen.addComponent (self, str glyphName, Tuple[float, float, float, float, float, float] transformation)
Add a sub glyph. The 'transformation' argument must be a 6-tuple
containing an affine transformation, or a Transform object from the
fontTools.misc.transform module. More precisely: it should be a
sequence containing 6 numbers.
Reimplemented in fontTools.cu2qu.ufo.GetSegmentsPen, fontTools.pens.basePen.DecomposingPen, fontTools.pens.basePen.NullPen, fontTools.pens.pointPen.SegmentToPointPen, fontTools.pens.recordingPen.RecordingPen, fontTools.pens.teePen.TeePen, and fontTools.varLib.interpolatableHelpers.PerContourOrComponentPen.
Definition at line 123 of file basePen.py.
addVarComponent()
None fontTools.pens.basePen.AbstractPen.addVarComponent (self, str glyphName, DecomposedTransform transformation, Dict[str, float] location)
Add a VarComponent sub glyph. The 'transformation' argument
must be a DecomposedTransform from the fontTools.misc.transform module,
and the 'location' argument must be a dictionary mapping axis tags
to their locations.
Reimplemented in fontTools.pens.basePen.DecomposingPen, fontTools.pens.basePen.NullPen, and fontTools.pens.recordingPen.RecordingPen.
Definition at line 135 of file basePen.py.
closePath()
None fontTools.pens.basePen.AbstractPen.closePath (self)
Close the current sub path. You must call either pen.closePath()
or pen.endPath() after each sub path.
Reimplemented in fontTools.cu2qu.ufo.GetSegmentsPen, fontTools.pens.basePen.BasePen, fontTools.pens.basePen.NullPen, fontTools.pens.filterPen.ContourFilterPen, fontTools.pens.filterPen.FilterPen, fontTools.pens.pointPen.SegmentToPointPen, fontTools.pens.recordingPen.RecordingPen, fontTools.pens.teePen.TeePen, fontTools.pens.transformPen.TransformPen, and fontTools.pens.ttGlyphPen.TTGlyphPen.
Definition at line 111 of file basePen.py.
Referenced by fontTools.pens.ttGlyphPen.TTGlyphPen.endPath(), fontTools.pens.pointInsidePen.PointInsidePen.getResult(), and fontTools.pens.pointInsidePen.PointInsidePen.setTestPoint().
curveTo()
None fontTools.pens.basePen.AbstractPen.curveTo (self, *Tuple[float, float] points)
Draw a cubic bezier with an arbitrary number of control points.
The last point specified is on-curve, all others are off-curve
(control) points. If the number of control points is > 2, the
segment is split into multiple bezier segments. This works
like this:
Let n be the number of control points (which is the number of
arguments to this call minus 1). If n==2, a plain vanilla cubic
bezier is drawn. If n==1, we fall back to a quadratic segment and
if n==0 we draw a straight line. It gets interesting when n>2:
n-1 PostScript-style cubic segments will be drawn as if it were
one curve. See decomposeSuperBezierSegment().
The conversion algorithm used for n>2 is inspired by NURB
splines, and is conceptually equivalent to the TrueType "implied
points" principle. See also decomposeQuadraticSegment().
Reimplemented in fontTools.cu2qu.ufo.GetSegmentsPen, fontTools.pens.basePen.BasePen, fontTools.pens.basePen.NullPen, fontTools.pens.cu2quPen.Cu2QuPen, fontTools.pens.filterPen.FilterPen, fontTools.pens.pointPen.SegmentToPointPen, fontTools.pens.recordingPen.RecordingPen, fontTools.pens.roundingPen.RoundingPen, fontTools.pens.teePen.TeePen, fontTools.pens.transformPen.TransformPen, and fontTools.pens.ttGlyphPen.TTGlyphPen.
Definition at line 73 of file basePen.py.
endPath()
None fontTools.pens.basePen.AbstractPen.endPath (self)
End the current sub path, but don't close it. You must call
either pen.closePath() or pen.endPath() after each sub path.
Reimplemented in fontTools.cu2qu.ufo.GetSegmentsPen, fontTools.pens.basePen.BasePen, fontTools.pens.basePen.NullPen, fontTools.pens.filterPen.ContourFilterPen, fontTools.pens.filterPen.FilterPen, fontTools.pens.pointPen.SegmentToPointPen, fontTools.pens.recordingPen.RecordingPen, fontTools.pens.teePen.TeePen, fontTools.pens.transformPen.TransformPen, and fontTools.pens.ttGlyphPen.TTGlyphPen.
Definition at line 117 of file basePen.py.
lineTo()
None fontTools.pens.basePen.AbstractPen.lineTo (self, Tuple[float, float] pt)
Draw a straight line from the current point to 'pt'.
Reimplemented in fontTools.cu2qu.ufo.GetSegmentsPen, fontTools.pens.basePen.BasePen, fontTools.pens.basePen.NullPen, fontTools.pens.filterPen.FilterPen, fontTools.pens.pointPen.SegmentToPointPen, fontTools.pens.recordingPen.RecordingPen, fontTools.pens.roundingPen.RoundingPen, fontTools.pens.teePen.TeePen, fontTools.pens.transformPen.TransformPen, and fontTools.pens.ttGlyphPen.TTGlyphPen.
Definition at line 69 of file basePen.py.
Referenced by fontTools.pens.basePen.BasePen.curveTo(), fontTools.pens.pointInsidePen.PointInsidePen.getResult(), and fontTools.pens.basePen.BasePen.qCurveTo().
moveTo()
None fontTools.pens.basePen.AbstractPen.moveTo (self, Tuple[float, float] pt)
Begin a new sub path, set the current point to 'pt'. You must
end each sub path with a call to pen.closePath() or pen.endPath().
Reimplemented in fontTools.cu2qu.ufo.GetSegmentsPen, fontTools.pens.basePen.BasePen, fontTools.pens.basePen.NullPen, fontTools.pens.filterPen.FilterPen, fontTools.pens.pointPen.SegmentToPointPen, fontTools.pens.recordingPen.RecordingPen, fontTools.pens.roundingPen.RoundingPen, fontTools.pens.teePen.TeePen, fontTools.pens.transformPen.TransformPen, and fontTools.pens.ttGlyphPen.TTGlyphPen.
Definition at line 63 of file basePen.py.
qCurveTo()
None fontTools.pens.basePen.AbstractPen.qCurveTo (self, *Tuple[float, float] points)
Draw a whole string of quadratic curve segments.
The last point specified is on-curve, all others are off-curve
points.
This method implements TrueType-style curves, breaking up curves
using 'implied points': between each two consequtive off-curve points,
there is one implied point exactly in the middle between them. See
also decomposeQuadraticSegment().
The last argument (normally the on-curve point) may be None.
This is to support contours that have NO on-curve points (a rarely
seen feature of TrueType outlines).
Reimplemented in fontTools.cu2qu.ufo.GetSegmentsPen, fontTools.pens.basePen.BasePen, fontTools.pens.basePen.NullPen, fontTools.pens.filterPen.FilterPen, fontTools.pens.pointPen.SegmentToPointPen, fontTools.pens.recordingPen.RecordingPen, fontTools.pens.roundingPen.RoundingPen, fontTools.pens.teePen.TeePen, fontTools.pens.transformPen.TransformPen, and fontTools.pens.ttGlyphPen.TTGlyphPen.
Definition at line 94 of file basePen.py.
Referenced by fontTools.pens.basePen.BasePen.curveTo(), and fontTools.pens.cu2quPen.Cu2QuPen.curveTo().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/pens/basePen.py