Code Cloning Analysis: fontTools.ttLib.tables.G__l_o_c.table_G__l_o_c Class Reference
fontTools.ttLib.tables.G__l_o_c.table_G__l_o_c Class Reference
Public Member Functions
__init__ (self, tag=None)
decompile (self, data, ttFont)
compile (self, ttFont)
set (self, locations)
toXML (self, writer, ttFont)
fromXML (self, name, attrs, content, ttFont)
__getitem__ (self, index)
__len__ (self)
__iter__ (self)
Public Member Functions inherited from fontTools.ttLib.tables.DefaultTable.DefaultTable
__init__ (self, tag=None)
__repr__ (self)
__eq__ (self, other)
__ne__ (self, other)
Public Attributes
attribIds = None
int numAttribs = 0
locations = array.array("I" if flags & 1 else "H")
Public Attributes inherited from fontTools.ttLib.tables.DefaultTable.DefaultTable
tableTag = Tag(tag)
data = data
ERROR
Additional Inherited Members
Static Public Attributes inherited from fontTools.ttLib.tables.DefaultTable.DefaultTable
list dependencies = []
Detailed Description
Graphite Index to Glyph Atttributes table
See also https://graphite.sil.org/graphite_techAbout#graphite-font-tables
Definition at line 17 of file G__l_o_c.py.
Constructor & Destructor Documentation
__init__()
fontTools.ttLib.tables.G__l_o_c.table_G__l_o_c.__init__ (self, tag = None)
Definition at line 25 of file G__l_o_c.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__getitem__()
fontTools.ttLib.tables.G__l_o_c.table_G__l_o_c.__getitem__ (self, index)
Definition at line 78 of file G__l_o_c.py.
__iter__()
fontTools.ttLib.tables.G__l_o_c.table_G__l_o_c.__iter__ (self)
Definition at line 84 of file G__l_o_c.py.
__len__()
fontTools.ttLib.tables.G__l_o_c.table_G__l_o_c.__len__ (self)
Definition at line 81 of file G__l_o_c.py.
compile()
fontTools.ttLib.tables.G__l_o_c.table_G__l_o_c.compile (self, ttFont)
Reimplemented from fontTools.ttLib.tables.DefaultTable.DefaultTable.
Definition at line 44 of file G__l_o_c.py.
Referenced by fontTools.ttLib.tables.TupleVariation.TupleVariation.getCoordWidth(), and PIL.FontFile.FontFile.save().
decompile()
fontTools.ttLib.tables.G__l_o_c.table_G__l_o_c.decompile (self, data, ttFont)
Reimplemented from fontTools.ttLib.tables.DefaultTable.DefaultTable.
Definition at line 30 of file G__l_o_c.py.
Referenced by fontTools.ttLib.tables._c_m_a_p.CmapSubtable.newSubtable().
fromXML()
fontTools.ttLib.tables.G__l_o_c.table_G__l_o_c.fromXML (self, name, attrs, content, ttFont)
Reimplemented from fontTools.ttLib.tables.DefaultTable.DefaultTable.
Definition at line 74 of file G__l_o_c.py.
set()
fontTools.ttLib.tables.G__l_o_c.table_G__l_o_c.set (self, locations)
Definition at line 66 of file G__l_o_c.py.
Referenced by matplotlib.contour.ContourSet.__init__(), matplotlib.layout_engine.ConstrainedLayoutEngine.__init__(), matplotlib.layout_engine.TightLayoutEngine.__init__(), matplotlib.transforms.TransformWrapper.__init__(), pip._vendor.requests.cookies.RequestsCookieJar.__setitem__(), matplotlib.axes._base._AxesBase._set_view(), mplot3d.axes3d.Axes3D._set_view(), matplotlib.axes._axes.Axes.pie(), pip._vendor.distlib.metadata.LegacyMetadata.read_file(), matplotlib.layout_engine.ConstrainedLayoutEngine.set(), matplotlib.layout_engine.TightLayoutEngine.set(), numpy.core.tests.test_simd._SIMD_ALL.test_lut(), and pip._vendor.distlib.metadata.LegacyMetadata.update().
toXML()
fontTools.ttLib.tables.G__l_o_c.table_G__l_o_c.toXML (self, writer, ttFont)
Reimplemented from fontTools.ttLib.tables.DefaultTable.DefaultTable.
Definition at line 70 of file G__l_o_c.py.
Member Data Documentation
attribIds
fontTools.ttLib.tables.G__l_o_c.table_G__l_o_c.attribIds = None
Definition at line 27 of file G__l_o_c.py.
locations
fontTools.ttLib.tables.G__l_o_c.table_G__l_o_c.locations = array.array("I" if flags & 1 else "H")
Definition at line 34 of file G__l_o_c.py.
Referenced by fontTools.varLib.models.VariationModel.getSubModel().
numAttribs
int fontTools.ttLib.tables.G__l_o_c.table_G__l_o_c.numAttribs = 0
Definition at line 28 of file G__l_o_c.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ttLib/tables/G__l_o_c.py