Code Cloning Analysis: fontTools.colorLib.builder.LayerReuseCache Class Reference
fontTools.colorLib.builder.LayerReuseCache Class Reference
Public Member Functions
__init__ (self)
List[ot.Paint] try_reuse (self, List[ot.Paint] layers)
add (self, List[ot.Paint] layers, int first_layer_index)
Static Public Attributes
Mapping reusePool [Tuple[Any, ...], int]
Mapping tuples [int, Tuple[Any, ...]]
List keepAlive [ot.Paint]
Protected Member Functions
_paint_tuple (self, ot.Paint paint)
Tuple[Any,...] _as_tuple (self, Sequence[ot.Paint] paints)
Detailed Description
Definition at line 455 of file builder.py.
Constructor & Destructor Documentation
__init__()
fontTools.colorLib.builder.LayerReuseCache.__init__ (self)
Definition at line 460 of file builder.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_as_tuple()
Tuple[Any, ...] fontTools.colorLib.builder.LayerReuseCache._as_tuple (self, Sequence[ot.Paint] paints) protected
Definition at line 487 of file builder.py.
_paint_tuple()
fontTools.colorLib.builder.LayerReuseCache._paint_tuple (self, ot.Paint paint) protected
Definition at line 465 of file builder.py.
add()
fontTools.colorLib.builder.LayerReuseCache.add (self, List[ot.Paint] layers, int first_layer_index)
Definition at line 515 of file builder.py.
Referenced by matplotlib.sankey.Sankey.__init__(), pip._internal.req.req_uninstall.UninstallPathSet._permitted(), pip._vendor.distlib.manifest.Manifest.add_many(), pip._vendor.urllib3._collections.HTTPHeaderDict.extend(), numpy.core.tests.test_simd._SIMD_ALL.test_conversion_expand(), numpy.core.tests.test_simd._SIMD_ALL.test_mask_conditional(), pip._internal.operations.build.build_tracker.BuildTracker.track(), and fontTools.misc.classifyTools.Classifier.update().
try_reuse()
List[ot.Paint] fontTools.colorLib.builder.LayerReuseCache.try_reuse (self, List[ot.Paint] layers)
Definition at line 490 of file builder.py.
Member Data Documentation
keepAlive
List fontTools.colorLib.builder.LayerReuseCache.keepAlive [ot.Paint] static
Definition at line 458 of file builder.py.
reusePool
Mapping fontTools.colorLib.builder.LayerReuseCache.reusePool [Tuple[Any, ...], int] static
Definition at line 456 of file builder.py.
tuples
Mapping fontTools.colorLib.builder.LayerReuseCache.tuples [int, Tuple[Any, ...]] static
Definition at line 457 of file builder.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/colorLib/builder.py