Code Cloning Analysis: contourpy.util.mpl_renderer.MplTestRenderer Class Reference
contourpy.util.mpl_renderer.MplTestRenderer Class Reference
Public Member Functions
None __init__ (self, int nrows=1, int ncols=1, tuple[float, float] figsize=(9, 9))
Public Member Functions inherited from contourpy.util.mpl_renderer.MplRenderer
None __init__ (self, int nrows=1, int ncols=1, tuple[float, float] figsize=(9, 9), bool show_frame=True, str|None backend=None, dict[str, Any]|None gridspec_kw=None)
None __del__ (self)
None filled (self, cpy.FillReturn filled, FillType|str fill_type, Axes|int ax=0, str color="C0", float alpha=0.7)
None grid (self, ArrayLike x, ArrayLike y, Axes|int ax=0, str color="black", float alpha=0.1, str|None point_color=None, float quad_as_tri_alpha=0)
None lines (self, cpy.LineReturn lines, LineType|str line_type, Axes|int ax=0, str color="C0", float alpha=1.0, float linewidth=1)
None mask (self, ArrayLike x, ArrayLike y, ArrayLike|np.ma.MaskedArray[Any, Any] z, Axes|int ax=0, str color="black")
None save (self, str filename, bool transparent=False)
io.BytesIO save_to_buffer (self)
None show (self)
None title (self, str title, Axes|int ax=0, str|None color=None)
None z_values (self, ArrayLike x, ArrayLike y, ArrayLike z, Axes|int ax=0, str color="green", str fmt=".1f", bool quad_as_tri=False)
Public Member Functions inherited from contourpy.util.renderer.Renderer
None multi_filled (self, list[FillReturn] multi_filled, FillType|str fill_type, Any ax=0, str|None color=None, **Any kwargs)
None multi_lines (self, list[LineReturn] multi_lines, LineType|str line_type, Any ax=0, str|None color=None, **Any kwargs)
Additional Inherited Members
Protected Member Functions inherited from contourpy.util.mpl_renderer.MplRenderer
None _autoscale (self)
Axes _get_ax (self, Axes|int ax)
Protected Member Functions inherited from contourpy.util.renderer.Renderer
tuple[CoordinateArray, CoordinateArray] _grid_as_2d (self, ArrayLike x, ArrayLike y)
Protected Attributes inherited from contourpy.util.mpl_renderer.MplRenderer
_fig
bool _want_tight = True
Static Protected Attributes inherited from contourpy.util.mpl_renderer.MplRenderer
Sequence _axes [Axes]
Detailed Description
Test renderer implemented using Matplotlib.
No whitespace around plots and no spines/ticks displayed.
Uses Agg backend, so can only save to file/buffer, cannot call ``show()``.
Definition at line 313 of file mpl_renderer.py.
Constructor & Destructor Documentation
__init__()
None contourpy.util.mpl_renderer.MplTestRenderer.__init__ (self, int nrows = 1, int ncols = 1, tuple[float, float] figsize = (9, 9))
Definition at line 319 of file mpl_renderer.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/contourpy/util/mpl_renderer.py