Code Cloning Analysis: pandas.io.html Namespace Reference
pandas.io.html Namespace Reference
Classes
class _BeautifulSoupHtml5LibFrameParser
class _HtmlFrameParser
class _LxmlFrameParser
Functions
str _remove_whitespace (str s, Pattern regex=_RE_WHITESPACE)
int|Sequence[int] _get_skiprows (int|Sequence[int]|slice|None skiprows)
str|bytes _read (FilePath|BaseBuffer obj, str|None encoding, StorageOptions|None storage_options)
str _build_xpath_expr (attrs)
None _expand_elements (body)
_data_to_frame (**kwargs)
type[_HtmlFrameParser] _parser_dispatch (HTMLFlavors|None flavor)
str _print_as_set (s)
_validate_flavor (flavor)
_parse (flavor, io, match, attrs, encoding, displayed_only, extract_links, storage_options, **kwargs)
list[DataFrame] read_html (FilePath|ReadBuffer[str] io, *, str|Pattern match=".+", HTMLFlavors|Sequence[HTMLFlavors]|None flavor=None, int|Sequence[int]|None header=None, int|Sequence[int]|None index_col=None, int|Sequence[int]|slice|None skiprows=None, dict[str, str]|None attrs=None, bool parse_dates=False, str|None thousands=",", str|None encoding=None, str decimal=".", dict|None converters=None, Iterable[object]|None na_values=None, bool keep_default_na=True, bool displayed_only=True, Literal[None, "header", "footer", "body", "all"] extract_links=None, DtypeBackend|lib.NoDefault dtype_backend=lib.no_default, StorageOptions storage_options=None)
Variables
_RE_WHITESPACE = re.compile(r"[\r\n]+|\s{2,}")
READ HTML #.
dict _re_namespace = {"re": "http://exslt.org/regular-expressions"}
dict _valid_parsers
Detailed Description
:mod:`pandas.io.html` is a module containing functionality for dealing with
HTML IO.
Function Documentation
_build_xpath_expr()
str pandas.io.html._build_xpath_expr (attrs) protected
Build an xpath expression to simulate bs4's ability to pass in kwargs to
search for attributes when using the lxml parser.
Parameters
----------
attrs : dict
    A dict of HTML attributes. These are NOT checked for validity.
Returns
-------
expr : unicode
    An XPath expression that checks for the given HTML attributes.
Definition at line 669 of file html.py.
Referenced by pandas.io.html._LxmlFrameParser._parse_tables().
_data_to_frame()
pandas.io.html._data_to_frame (** kwargs) protected
Definition at line 855 of file html.py.
_expand_elements()
None pandas.io.html._expand_elements (body) protected
Definition at line 844 of file html.py.
_get_skiprows()
int | Sequence[int] pandas.io.html._get_skiprows (int | Sequence[int] | slice | None skiprows) protected
Get an iterator given an integer, slice or container.
Parameters
----------
skiprows : int, slice, container
    The iterator to use to skip rows; can also be a slice.
Raises
------
TypeError
    * If `skiprows` is not a slice, integer, or Container
Returns
-------
it : iterable
    A proper iterator to use to skip rows of a DataFrame.
Definition at line 92 of file html.py.
Referenced by pandas.io.html._LxmlFrameParser._parse_tfoot_tr().
_parse()
pandas.io.html._parse (flavor, io, match, attrs, encoding, displayed_only, extract_links, storage_options, ** kwargs) protected
Definition at line 955 of file html.py.
_parser_dispatch()
type[_HtmlFrameParser] pandas.io.html._parser_dispatch (HTMLFlavors | None flavor) protected
Choose the parser based on the input flavor.
Parameters
----------
flavor : {{"lxml", "html5lib", "bs4"}} or None
    The type of parser to use. This must be a valid backend.
Returns
-------
cls : _HtmlFrameParser subclass
    The parser class based on the requested input flavor.
Raises
------
ValueError
    * If `flavor` is not a valid backend.
ImportError
    * If you do not have the requested `flavor`
Definition at line 887 of file html.py.
References _parser_dispatch().
Referenced by _parser_dispatch().
_print_as_set()
str pandas.io.html._print_as_set (s) protected
Definition at line 922 of file html.py.
_read()
str | bytes pandas.io.html._read (FilePath | BaseBuffer obj, str | None encoding, StorageOptions | None storage_options) protected
Try to read from a url, file or string.
Parameters
----------
obj : str, unicode, path object, or file-like object
Returns
-------
raw_text : str
Definition at line 121 of file html.py.
Referenced by pandas.io.html._BeautifulSoupHtml5LibFrameParser._parse_tfoot_tr().
_remove_whitespace()
str pandas.io.html._remove_whitespace (str s, Pattern regex = _RE_WHITESPACE) protected
Replace extra whitespace inside of a string with a single space.
Parameters
----------
s : str or unicode
    The string from which to remove extra whitespace.
regex : re.Pattern
    The regular expression to use to remove extra whitespace.
Returns
-------
subd : str or unicode
    `s` with all extra whitespace replaced with a single space.
Definition at line 73 of file html.py.
Referenced by pandas.io.html._HtmlFrameParser._expand_colspan_rowspan().
_validate_flavor()
pandas.io.html._validate_flavor (flavor) protected
Definition at line 927 of file html.py.
read_html()
list[DataFrame] pandas.io.html.read_html (FilePath | ReadBuffer[str] io, * , str | Pattern match = ".+", HTMLFlavors | Sequence[HTMLFlavors] | None flavor = None, int | Sequence[int] | None header = None, int | Sequence[int] | None index_col = None, int | Sequence[int] | slice | None skiprows = None, dict[str, str] | None attrs = None, bool parse_dates = False, str | None thousands = ",", str | None encoding = None, str decimal = ".", dict | None converters = None, Iterable[object] | None na_values = None, bool keep_default_na = True, bool displayed_only = True, Literal[None, "header", "footer", "body", "all"] extract_links = None, DtypeBackend | lib.NoDefault dtype_backend = lib.no_default, StorageOptions storage_options = None)
Read HTML tables into a ``list`` of ``DataFrame`` objects.
Parameters
----------
io : str, path object, or file-like object
String, path object (implementing ``os.PathLike[str]``), or file-like
object implementing a string ``read()`` function.
The string can represent a URL or the HTML itself. Note that
lxml only accepts the http, ftp and file url protocols. If you have a
URL that starts with ``'https'`` you might try removing the ``'s'``.
.. deprecated:: 2.1.0
Passing html literal strings is deprecated.
Wrap literal string/bytes input in ``io.StringIO``/``io.BytesIO`` instead.
match : str or compiled regular expression, optional
The set of tables containing text matching this regex or string will be
returned. Unless the HTML is extremely simple you will probably need to
pass a non-empty string here. Defaults to '.+' (match any non-empty
string). The default value will return all tables contained on a page.
This value is converted to a regular expression so that there is
consistent behavior between Beautiful Soup and lxml.
flavor : {{"lxml", "html5lib", "bs4"}} or list-like, optional
The parsing engine (or list of parsing engines) to use. 'bs4' and
'html5lib' are synonymous with each other, they are both there for
backwards compatibility. The default of ``None`` tries to use ``lxml``
to parse and if that fails it falls back on ``bs4`` + ``html5lib``.
header : int or list-like, optional
The row (or list of rows for a :class:`~pandas.MultiIndex`) to use to
make the columns headers.
index_col : int or list-like, optional
The column (or list of columns) to use to create the index.
skiprows : int, list-like or slice, optional
Number of rows to skip after parsing the column integer. 0-based. If a
sequence of integers or a slice is given, will skip the rows indexed by
that sequence.  Note that a single element sequence means 'skip the nth
row' whereas an integer means 'skip n rows'.
attrs : dict, optional
This is a dictionary of attributes that you can pass to use to identify
the table in the HTML. These are not checked for validity before being
passed to lxml or Beautiful Soup. However, these attributes must be
valid HTML table attributes to work correctly. For example, ::
attrs = {{'id': 'table'}}
is a valid attribute dictionary because the 'id' HTML tag attribute is
a valid HTML attribute for *any* HTML tag as per `this document
<https://html.spec.whatwg.org/multipage/dom.html#global-attributes>`__. ::
attrs = {{'asdf': 'table'}}
is *not* a valid attribute dictionary because 'asdf' is not a valid
HTML attribute even if it is a valid XML attribute.  Valid HTML 4.01
table attributes can be found `here
<http://www.w3.org/TR/REC-html40/struct/tables.html#h-11.2>`__. A
working draft of the HTML 5 spec can be found `here
<https://html.spec.whatwg.org/multipage/tables.html>`__. It contains the
latest information on table attributes for the modern web.
parse_dates : bool, optional
See :func:`~read_csv` for more details.
thousands : str, optional
Separator to use to parse thousands. Defaults to ``','``.
encoding : str, optional
The encoding used to decode the web page. Defaults to ``None``.``None``
preserves the previous encoding behavior, which depends on the
underlying parser library (e.g., the parser library will try to use
the encoding provided by the document).
decimal : str, default '.'
Character to recognize as decimal point (e.g. use ',' for European
data).
converters : dict, default None
Dict of functions for converting values in certain columns. Keys can
either be integers or column labels, values are functions that take one
input argument, the cell (not column) content, and return the
transformed content.
na_values : iterable, default None
Custom NA values.
keep_default_na : bool, default True
If na_values are specified and keep_default_na is False the default NaN
values are overridden, otherwise they're appended to.
displayed_only : bool, default True
Whether elements with "display: none" should be parsed.
extract_links : {{None, "all", "header", "body", "footer"}}
Table elements in the specified section(s) with <a> tags will have their
href extracted.
.. versionadded:: 1.5.0
dtype_backend : {{'numpy_nullable', 'pyarrow'}}, default 'numpy_nullable'
Back-end data type applied to the resultant :class:`DataFrame`
(still experimental). Behaviour is as follows:
* ``"numpy_nullable"``: returns nullable-dtype-backed :class:`DataFrame`
(default).
* ``"pyarrow"``: returns pyarrow-backed nullable :class:`ArrowDtype`
DataFrame.
.. versionadded:: 2.0
{storage_options}
.. versionadded:: 2.1.0
Returns
-------
dfs
A list of DataFrames.
See Also
--------
read_csv : Read a comma-separated values (csv) file into DataFrame.
Notes
-----
Before using this function you should read the :ref:`gotchas about the
HTML parsing libraries <io.html.gotchas>`.
Expect to do some cleanup after you call this function. For example, you
might need to manually assign column names if the column names are
converted to NaN when you pass the `header=0` argument. We try to assume as
little as possible about the structure of the table and push the
idiosyncrasies of the HTML contained in the table to the user.
This function searches for ``<table>`` elements and only for ``<tr>``
and ``<th>`` rows and ``<td>`` elements within each ``<tr>`` or ``<th>``
element in the table. ``<td>`` stands for "table data". This function
attempts to properly handle ``colspan`` and ``rowspan`` attributes.
If the function has a ``<thead>`` argument, it is used to construct
the header, otherwise the function attempts to find the header within
the body (by putting rows with only ``<th>`` elements into the header).
Similar to :func:`~read_csv` the `header` argument is applied
**after** `skiprows` is applied.
This function will *always* return a list of :class:`DataFrame` *or*
it will fail, e.g., it will *not* return an empty list.
Examples
--------
See the :ref:`read_html documentation in the IO section of the docs
<io.read_html>` for some examples of reading in HTML tables.
Definition at line 1027 of file html.py.
Variable Documentation
_re_namespace
dict pandas.io.html._re_namespace = {"re": "http://exslt.org/regular-expressions"} protected
Definition at line 692 of file html.py.
_RE_WHITESPACE
pandas.io.html._RE_WHITESPACE = re.compile(r"[\r\n]+|\s{2,}") protected
READ HTML #.
Definition at line 70 of file html.py.
_valid_parsers
dict pandas.io.html._valid_parsers protected
Initial value:
=  {
    "lxml": _LxmlFrameParser,
    None: _LxmlFrameParser,
    "html5lib": _BeautifulSoupHtml5LibFrameParser,
    "bs4": _BeautifulSoupHtml5LibFrameParser,
}
Definition at line 879 of file html.py.