Code Cloning Analysis: sklearn.utils.tests.test_testing.MockMetaEstimator Class Reference
sklearn.utils.tests.test_testing.MockMetaEstimator Class Reference
Public Member Functions
__init__ (self, delegate)
predict (self, X)
score (self, X)
predict_proba (self, X)
fit (self, X, y)
Public Attributes
delegate = delegate
Detailed Description
Definition at line 352 of file test_testing.py.
Constructor & Destructor Documentation
__init__()
sklearn.utils.tests.test_testing.MockMetaEstimator.__init__ (self, delegate)
MetaEstimator to check if doctest on delegated methods work.
Parameters
---------
delegate : estimator
    Delegated estimator.
Definition at line 353 of file test_testing.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params().
Member Function Documentation
fit()
sklearn.utils.tests.test_testing.MockMetaEstimator.fit (self, X, y)
Incorrect docstring but should not be tested
Definition at line 397 of file test_testing.py.
Referenced by sklearn.cluster._kmeans._BaseKMeans.fit_predict(), and sklearn.cluster._kmeans._BaseKMeans.fit_transform().
predict()
sklearn.utils.tests.test_testing.MockMetaEstimator.predict (self, X)
This is available only if delegate has predict.
Parameters
----------
y : ndarray
    Parameter y
Definition at line 364 of file test_testing.py.
predict_proba()
sklearn.utils.tests.test_testing.MockMetaEstimator.predict_proba (self, X)
This is available only if delegate has predict_proba.
Parameters
---------
X : ndarray
    Parameter X
Definition at line 386 of file test_testing.py.
score()
sklearn.utils.tests.test_testing.MockMetaEstimator.score (self, X)
This is available only if delegate has score.
Parameters
---------
y : ndarray
    Parameter y
Definition at line 376 of file test_testing.py.
Member Data Documentation
delegate
sklearn.utils.tests.test_testing.MockMetaEstimator.delegate = delegate
Definition at line 361 of file test_testing.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/sklearn/utils/tests/test_testing.py