Code Cloning Analysis: scipy.fftpack._realtransforms Namespace Reference
scipy.fftpack._realtransforms Namespace Reference
Functions
dctn (x, type=2, shape=None, axes=None, norm=None, overwrite_x=False)
idctn (x, type=2, shape=None, axes=None, norm=None, overwrite_x=False)
dstn (x, type=2, shape=None, axes=None, norm=None, overwrite_x=False)
idstn (x, type=2, shape=None, axes=None, norm=None, overwrite_x=False)
dct (x, type=2, n=None, axis=-1, norm=None, overwrite_x=False)
idct (x, type=2, n=None, axis=-1, norm=None, overwrite_x=False)
dst (x, type=2, n=None, axis=-1, norm=None, overwrite_x=False)
idst (x, type=2, n=None, axis=-1, norm=None, overwrite_x=False)
Variables
list __all__ = ['dct', 'idct', 'dst', 'idst', 'dctn', 'idctn', 'dstn', 'idstn']
dict _inverse_typemap = {1: 1, 2: 3, 3: 2, 4: 4}
Detailed Description
Real spectrum transforms (DCT, DST, MDCT)
Function Documentation
dct()
scipy.fftpack._realtransforms.dct (x, type = 2, n = None, axis = -1, norm = None, overwrite_x = False)
Return the Discrete Cosine Transform of arbitrary type sequence x.
Parameters
----------
x : array_like
    The input array.
type : {1, 2, 3, 4}, optional
    Type of the DCT (see Notes). Default type is 2.
n : int, optional
    Length of the transform.  If ``n < x.shape[axis]``, `x` is
    truncated.  If ``n > x.shape[axis]``, `x` is zero-padded. The
    default results in ``n = x.shape[axis]``.
axis : int, optional
    Axis along which the dct is computed; the default is over the
    last axis (i.e., ``axis=-1``).
norm : {None, 'ortho'}, optional
    Normalization mode (see Notes). Default is None.
overwrite_x : bool, optional
    If True, the contents of `x` can be destroyed; the default is False.
Returns
-------
y : ndarray of real
    The transformed input array.
See Also
--------
idct : Inverse DCT
Notes
-----
For a single dimension array ``x``, ``dct(x, norm='ortho')`` is equal to
MATLAB ``dct(x)``.
There are, theoretically, 8 types of the DCT, only the first 4 types are
implemented in scipy. 'The' DCT generally refers to DCT type 2, and 'the'
Inverse DCT generally refers to DCT type 3.
**Type I**
There are several definitions of the DCT-I; we use the following
(for ``norm=None``)
.. math::
   y_k = x_0 + (-1)^k x_{N-1} + 2 \sum_{n=1}^{N-2} x_n \cos\left(
   \frac{\pi k n}{N-1} \right)
If ``norm='ortho'``, ``x[0]`` and ``x[N-1]`` are multiplied by a scaling
factor of :math:`\sqrt{2}`, and ``y[k]`` is multiplied by a scaling factor
``f``
.. math::
    f = \begin{cases}
     \frac{1}{2}\sqrt{\frac{1}{N-1}} & \text{if }k=0\text{ or }N-1, \\
     \frac{1}{2}\sqrt{\frac{2}{N-1}} & \text{otherwise} \end{cases}
.. versionadded:: 1.2.0
   Orthonormalization in DCT-I.
.. note::
   The DCT-I is only supported for input size > 1.
**Type II**
There are several definitions of the DCT-II; we use the following
(for ``norm=None``)
.. math::
   y_k = 2 \sum_{n=0}^{N-1} x_n \cos\left(\frac{\pi k(2n+1)}{2N} \right)
If ``norm='ortho'``, ``y[k]`` is multiplied by a scaling factor ``f``
.. math::
   f = \begin{cases}
   \sqrt{\frac{1}{4N}} & \text{if }k=0, \\
   \sqrt{\frac{1}{2N}} & \text{otherwise} \end{cases}
which makes the corresponding matrix of coefficients orthonormal
(``O @ O.T = np.eye(N)``).
**Type III**
There are several definitions, we use the following (for ``norm=None``)
.. math::
   y_k = x_0 + 2 \sum_{n=1}^{N-1} x_n \cos\left(\frac{\pi(2k+1)n}{2N}\right)
or, for ``norm='ortho'``
.. math::
   y_k = \frac{x_0}{\sqrt{N}} + \sqrt{\frac{2}{N}} \sum_{n=1}^{N-1} x_n
   \cos\left(\frac{\pi(2k+1)n}{2N}\right)
The (unnormalized) DCT-III is the inverse of the (unnormalized) DCT-II, up
to a factor `2N`. The orthonormalized DCT-III is exactly the inverse of
the orthonormalized DCT-II.
**Type IV**
There are several definitions of the DCT-IV; we use the following
(for ``norm=None``)
.. math::
   y_k = 2 \sum_{n=0}^{N-1} x_n \cos\left(\frac{\pi(2k+1)(2n+1)}{4N} \right)
If ``norm='ortho'``, ``y[k]`` is multiplied by a scaling factor ``f``
.. math::
    f = \frac{1}{\sqrt{2N}}
.. versionadded:: 1.2.0
   Support for DCT-IV.
References
----------
.. [1] 'A Fast Cosine Transform in One and Two Dimensions', by J.
       Makhoul, `IEEE Transactions on acoustics, speech and signal
       processing` vol. 28(1), pp. 27-34,
       :doi:`10.1109/TASSP.1980.1163351` (1980).
.. [2] Wikipedia, "Discrete cosine transform",
       https://en.wikipedia.org/wiki/Discrete_cosine_transform
Examples
--------
The Type 1 DCT is equivalent to the FFT (though faster) for real,
even-symmetrical inputs. The output is also real and even-symmetrical.
Half of the FFT input is used to generate half of the FFT output:
>>> from scipy.fftpack import fft, dct
>>> import numpy as np
>>> fft(np.array([4., 3., 5., 10., 5., 3.])).real
array([ 30.,  -8.,   6.,  -2.,   6.,  -8.])
>>> dct(np.array([4., 3., 5., 10.]), 1)
array([ 30.,  -8.,   6.,  -2.])
Definition at line 235 of file _realtransforms.py.
Referenced by scipy.fftpack.tests.test_real_transforms.dct_2d_ref().
dctn()
scipy.fftpack._realtransforms.dctn (x, type = 2, shape = None, axes = None, norm = None, overwrite_x = False)
Return multidimensional Discrete Cosine Transform along the specified axes.
Parameters
----------
x : array_like
    The input array.
type : {1, 2, 3, 4}, optional
    Type of the DCT (see Notes). Default type is 2.
shape : int or array_like of ints or None, optional
    The shape of the result. If both `shape` and `axes` (see below) are
    None, `shape` is ``x.shape``; if `shape` is None but `axes` is
    not None, then `shape` is ``numpy.take(x.shape, axes, axis=0)``.
    If ``shape[i] > x.shape[i]``, the ith dimension is padded with zeros.
    If ``shape[i] < x.shape[i]``, the ith dimension is truncated to
    length ``shape[i]``.
    If any element of `shape` is -1, the size of the corresponding
    dimension of `x` is used.
axes : int or array_like of ints or None, optional
    Axes along which the DCT is computed.
    The default is over all axes.
norm : {None, 'ortho'}, optional
    Normalization mode (see Notes). Default is None.
overwrite_x : bool, optional
    If True, the contents of `x` can be destroyed; the default is False.
Returns
-------
y : ndarray of real
    The transformed input array.
See Also
--------
idctn : Inverse multidimensional DCT
Notes
-----
For full details of the DCT types and normalization modes, as well as
references, see `dct`.
Examples
--------
>>> import numpy as np
>>> from scipy.fftpack import dctn, idctn
>>> rng = np.random.default_rng()
>>> y = rng.standard_normal((16, 16))
>>> np.allclose(y, idctn(dctn(y, norm='ortho'), norm='ortho'))
True
Definition at line 13 of file _realtransforms.py.
References scipy.fftpack._helper._good_shape().
dst()
scipy.fftpack._realtransforms.dst (x, type = 2, n = None, axis = -1, norm = None, overwrite_x = False)
Return the Discrete Sine Transform of arbitrary type sequence x.
Parameters
----------
x : array_like
    The input array.
type : {1, 2, 3, 4}, optional
    Type of the DST (see Notes). Default type is 2.
n : int, optional
    Length of the transform.  If ``n < x.shape[axis]``, `x` is
    truncated.  If ``n > x.shape[axis]``, `x` is zero-padded. The
    default results in ``n = x.shape[axis]``.
axis : int, optional
    Axis along which the dst is computed; the default is over the
    last axis (i.e., ``axis=-1``).
norm : {None, 'ortho'}, optional
    Normalization mode (see Notes). Default is None.
overwrite_x : bool, optional
    If True, the contents of `x` can be destroyed; the default is False.
Returns
-------
dst : ndarray of reals
    The transformed input array.
See Also
--------
idst : Inverse DST
Notes
-----
For a single dimension array ``x``.
There are, theoretically, 8 types of the DST for different combinations of
even/odd boundary conditions and boundary off sets [1]_, only the first
4 types are implemented in scipy.
**Type I**
There are several definitions of the DST-I; we use the following
for ``norm=None``. DST-I assumes the input is odd around `n=-1` and `n=N`.
.. math::
    y_k = 2 \sum_{n=0}^{N-1} x_n \sin\left(\frac{\pi(k+1)(n+1)}{N+1}\right)
Note that the DST-I is only supported for input size > 1.
The (unnormalized) DST-I is its own inverse, up to a factor `2(N+1)`.
The orthonormalized DST-I is exactly its own inverse.
**Type II**
There are several definitions of the DST-II; we use the following for
``norm=None``. DST-II assumes the input is odd around `n=-1/2` and
`n=N-1/2`; the output is odd around :math:`k=-1` and even around `k=N-1`
.. math::
    y_k = 2 \sum_{n=0}^{N-1} x_n \sin\left(\frac{\pi(k+1)(2n+1)}{2N}\right)
if ``norm='ortho'``, ``y[k]`` is multiplied by a scaling factor ``f``
.. math::
    f = \begin{cases}
    \sqrt{\frac{1}{4N}} & \text{if }k = 0, \\
    \sqrt{\frac{1}{2N}} & \text{otherwise} \end{cases}
**Type III**
There are several definitions of the DST-III, we use the following (for
``norm=None``). DST-III assumes the input is odd around `n=-1` and even
around `n=N-1`
.. math::
    y_k = (-1)^k x_{N-1} + 2 \sum_{n=0}^{N-2} x_n \sin\left(
    \frac{\pi(2k+1)(n+1)}{2N}\right)
The (unnormalized) DST-III is the inverse of the (unnormalized) DST-II, up
to a factor `2N`. The orthonormalized DST-III is exactly the inverse of the
orthonormalized DST-II.
.. versionadded:: 0.11.0
**Type IV**
There are several definitions of the DST-IV, we use the following (for
``norm=None``). DST-IV assumes the input is odd around `n=-0.5` and even
around `n=N-0.5`
.. math::
    y_k = 2 \sum_{n=0}^{N-1} x_n \sin\left(\frac{\pi(2k+1)(2n+1)}{4N}\right)
The (unnormalized) DST-IV is its own inverse, up to a factor `2N`. The
orthonormalized DST-IV is exactly its own inverse.
.. versionadded:: 1.2.0
   Support for DST-IV.
References
----------
.. [1] Wikipedia, "Discrete sine transform",
       https://en.wikipedia.org/wiki/Discrete_sine_transform
Definition at line 443 of file _realtransforms.py.
Referenced by scipy.fftpack.tests.test_real_transforms.dst_2d_ref().
dstn()
scipy.fftpack._realtransforms.dstn (x, type = 2, shape = None, axes = None, norm = None, overwrite_x = False)
Return multidimensional Discrete Sine Transform along the specified axes.
Parameters
----------
x : array_like
    The input array.
type : {1, 2, 3, 4}, optional
    Type of the DST (see Notes). Default type is 2.
shape : int or array_like of ints or None, optional
    The shape of the result.  If both `shape` and `axes` (see below) are
    None, `shape` is ``x.shape``; if `shape` is None but `axes` is
    not None, then `shape` is ``numpy.take(x.shape, axes, axis=0)``.
    If ``shape[i] > x.shape[i]``, the ith dimension is padded with zeros.
    If ``shape[i] < x.shape[i]``, the ith dimension is truncated to
    length ``shape[i]``.
    If any element of `shape` is -1, the size of the corresponding
    dimension of `x` is used.
axes : int or array_like of ints or None, optional
    Axes along which the DCT is computed.
    The default is over all axes.
norm : {None, 'ortho'}, optional
    Normalization mode (see Notes). Default is None.
overwrite_x : bool, optional
    If True, the contents of `x` can be destroyed; the default is False.
Returns
-------
y : ndarray of real
    The transformed input array.
See Also
--------
idstn : Inverse multidimensional DST
Notes
-----
For full details of the DST types and normalization modes, as well as
references, see `dst`.
Examples
--------
>>> import numpy as np
>>> from scipy.fftpack import dstn, idstn
>>> rng = np.random.default_rng()
>>> y = rng.standard_normal((16, 16))
>>> np.allclose(y, idstn(dstn(y, norm='ortho'), norm='ortho'))
True
Definition at line 124 of file _realtransforms.py.
References scipy.fftpack._helper._good_shape().
idct()
scipy.fftpack._realtransforms.idct (x, type = 2, n = None, axis = -1, norm = None, overwrite_x = False)
Return the Inverse Discrete Cosine Transform of an arbitrary type sequence.
Parameters
----------
x : array_like
    The input array.
type : {1, 2, 3, 4}, optional
    Type of the DCT (see Notes). Default type is 2.
n : int, optional
    Length of the transform.  If ``n < x.shape[axis]``, `x` is
    truncated.  If ``n > x.shape[axis]``, `x` is zero-padded. The
    default results in ``n = x.shape[axis]``.
axis : int, optional
    Axis along which the idct is computed; the default is over the
    last axis (i.e., ``axis=-1``).
norm : {None, 'ortho'}, optional
    Normalization mode (see Notes). Default is None.
overwrite_x : bool, optional
    If True, the contents of `x` can be destroyed; the default is False.
Returns
-------
idct : ndarray of real
    The transformed input array.
See Also
--------
dct : Forward DCT
Notes
-----
For a single dimension array `x`, ``idct(x, norm='ortho')`` is equal to
MATLAB ``idct(x)``.
'The' IDCT is the IDCT of type 2, which is the same as DCT of type 3.
IDCT of type 1 is the DCT of type 1, IDCT of type 2 is the DCT of type
3, and IDCT of type 3 is the DCT of type 2. IDCT of type 4 is the DCT
of type 4. For the definition of these types, see `dct`.
Examples
--------
The Type 1 DCT is equivalent to the DFT for real, even-symmetrical
inputs. The output is also real and even-symmetrical. Half of the IFFT
input is used to generate half of the IFFT output:
>>> from scipy.fftpack import ifft, idct
>>> import numpy as np
>>> ifft(np.array([ 30.,  -8.,   6.,  -2.,   6.,  -8.])).real
array([  4.,   3.,   5.,  10.,   5.,   3.])
>>> idct(np.array([ 30.,  -8.,   6.,  -2.]), 1) / 6
array([  4.,   3.,   5.,  10.])
Definition at line 383 of file _realtransforms.py.
Referenced by scipy.fftpack.tests.test_real_transforms.idct_2d_ref().
idctn()
scipy.fftpack._realtransforms.idctn (x, type = 2, shape = None, axes = None, norm = None, overwrite_x = False)
Return multidimensional Discrete Cosine Transform along the specified axes.
Parameters
----------
x : array_like
    The input array.
type : {1, 2, 3, 4}, optional
    Type of the DCT (see Notes). Default type is 2.
shape : int or array_like of ints or None, optional
    The shape of the result.  If both `shape` and `axes` (see below) are
    None, `shape` is ``x.shape``; if `shape` is None but `axes` is
    not None, then `shape` is ``numpy.take(x.shape, axes, axis=0)``.
    If ``shape[i] > x.shape[i]``, the ith dimension is padded with zeros.
    If ``shape[i] < x.shape[i]``, the ith dimension is truncated to
    length ``shape[i]``.
    If any element of `shape` is -1, the size of the corresponding
    dimension of `x` is used.
axes : int or array_like of ints or None, optional
    Axes along which the IDCT is computed.
    The default is over all axes.
norm : {None, 'ortho'}, optional
    Normalization mode (see Notes). Default is None.
overwrite_x : bool, optional
    If True, the contents of `x` can be destroyed; the default is False.
Returns
-------
y : ndarray of real
    The transformed input array.
See Also
--------
dctn : multidimensional DCT
Notes
-----
For full details of the IDCT types and normalization modes, as well as
references, see `idct`.
Examples
--------
>>> import numpy as np
>>> from scipy.fftpack import dctn, idctn
>>> rng = np.random.default_rng()
>>> y = rng.standard_normal((16, 16))
>>> np.allclose(y, idctn(dctn(y, norm='ortho'), norm='ortho'))
True
Definition at line 68 of file _realtransforms.py.
References scipy.fftpack._helper._good_shape().
idst()
scipy.fftpack._realtransforms.idst (x, type = 2, n = None, axis = -1, norm = None, overwrite_x = False)
Return the Inverse Discrete Sine Transform of an arbitrary type sequence.
Parameters
----------
x : array_like
    The input array.
type : {1, 2, 3, 4}, optional
    Type of the DST (see Notes). Default type is 2.
n : int, optional
    Length of the transform.  If ``n < x.shape[axis]``, `x` is
    truncated. If ``n > x.shape[axis]``, `x` is zero-padded. The
    default results in ``n = x.shape[axis]``.
axis : int, optional
    Axis along which the idst is computed; the default is over the
    last axis (i.e., ``axis=-1``).
norm : {None, 'ortho'}, optional
    Normalization mode (see Notes). Default is None.
overwrite_x : bool, optional
    If True, the contents of `x` can be destroyed; the default is False.
Returns
-------
idst : ndarray of real
    The transformed input array.
See Also
--------
dst : Forward DST
Notes
-----
'The' IDST is the IDST of type 2, which is the same as DST of type 3.
IDST of type 1 is the DST of type 1, IDST of type 2 is the DST of type
3, and IDST of type 3 is the DST of type 2. For the definition of these
types, see `dst`.
.. versionadded:: 0.11.0
Definition at line 555 of file _realtransforms.py.
Referenced by scipy.fftpack.tests.test_real_transforms.idst_2d_ref().
idstn()
scipy.fftpack._realtransforms.idstn (x, type = 2, shape = None, axes = None, norm = None, overwrite_x = False)
Return multidimensional Discrete Sine Transform along the specified axes.
Parameters
----------
x : array_like
    The input array.
type : {1, 2, 3, 4}, optional
    Type of the DST (see Notes). Default type is 2.
shape : int or array_like of ints or None, optional
    The shape of the result.  If both `shape` and `axes` (see below) are
    None, `shape` is ``x.shape``; if `shape` is None but `axes` is
    not None, then `shape` is ``numpy.take(x.shape, axes, axis=0)``.
    If ``shape[i] > x.shape[i]``, the ith dimension is padded with zeros.
    If ``shape[i] < x.shape[i]``, the ith dimension is truncated to
    length ``shape[i]``.
    If any element of `shape` is -1, the size of the corresponding
    dimension of `x` is used.
axes : int or array_like of ints or None, optional
    Axes along which the IDST is computed.
    The default is over all axes.
norm : {None, 'ortho'}, optional
    Normalization mode (see Notes). Default is None.
overwrite_x : bool, optional
    If True, the contents of `x` can be destroyed; the default is False.
Returns
-------
y : ndarray of real
    The transformed input array.
See Also
--------
dstn : multidimensional DST
Notes
-----
For full details of the IDST types and normalization modes, as well as
references, see `idst`.
Examples
--------
>>> import numpy as np
>>> from scipy.fftpack import dstn, idstn
>>> rng = np.random.default_rng()
>>> y = rng.standard_normal((16, 16))
>>> np.allclose(y, idstn(dstn(y, norm='ortho'), norm='ortho'))
True
Definition at line 179 of file _realtransforms.py.
References scipy.fftpack._helper._good_shape().
Variable Documentation
__all__
list scipy.fftpack._realtransforms.__all__ = ['dct', 'idct', 'dst', 'idst', 'dctn', 'idctn', 'dstn', 'idstn'] private
Definition at line 5 of file _realtransforms.py.
_inverse_typemap
dict scipy.fftpack._realtransforms._inverse_typemap = {1: 1, 2: 3, 3: 2, 4: 4} protected
Definition at line 10 of file _realtransforms.py.