Code Cloning Analysis: fontTools.voltLib.parser.Parser Class Reference
fontTools.voltLib.parser.Parser Class Reference
Public Member Functions
__init__ (self, path)
make_lexer_ (self, file_or_path)
parse (self)
parse_def_glyph_ (self)
parse_def_group_ (self)
parse_def_script_ (self)
parse_langsys_ (self)
parse_feature_ (self)
parse_def_lookup_ (self)
parse_context_ (self)
parse_substitution_ (self, reversal)
parse_position_ (self)
parse_attach_ (self)
parse_attach_cursive_ (self)
parse_adjust_pair_ (self)
parse_adjust_single_ (self)
parse_def_anchor_ (self)
parse_adjust_by_ (self)
parse_pos_ (self)
parse_unicode_values_ (self)
parse_enum_ (self)
parse_coverage_ (self)
resolve_group (self, group_name)
glyph_range (self, start, end)
parse_ppem_ (self)
parse_noarg_option_ (self)
parse_cmap_format (self)
is_cur_keyword_ (self, k)
expect_string_ (self)
expect_keyword_ (self, keyword)
expect_name_ (self)
expect_number_ (self)
advance_lexer_ (self)
Public Attributes
doc_ = ast.VoltFile()
glyphs_ = OrderedSymbolTable()
groups_ = SymbolTable()
dict anchors_ = {}
scripts_ = SymbolTable()
langs_ = SymbolTable()
lookups_ = SymbolTable()
next_token_type_ = self.expect_string_()
tuple next_token_ = (None, None)
next_token_location_ = None
lexer_ = Lexer(data, filename)
tuple cur_token_location_ = keyword:
cur_token_ = k)
cur_token_type_
Detailed Description
Definition at line 22 of file parser.py.
Constructor & Destructor Documentation
__init__()
fontTools.voltLib.parser.Parser.__init__ (self, path)
Definition at line 23 of file parser.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
advance_lexer_()
fontTools.voltLib.parser.Parser.advance_lexer_ (self)
Definition at line 605 of file parser.py.
expect_keyword_()
fontTools.voltLib.parser.Parser.expect_keyword_ (self, keyword)
Definition at line 587 of file parser.py.
expect_name_()
fontTools.voltLib.parser.Parser.expect_name_ (self)
Definition at line 593 of file parser.py.
expect_number_()
fontTools.voltLib.parser.Parser.expect_number_ (self)
Definition at line 599 of file parser.py.
expect_string_()
fontTools.voltLib.parser.Parser.expect_string_ (self)
Definition at line 581 of file parser.py.
glyph_range()
fontTools.voltLib.parser.Parser.glyph_range (self, start, end)
Definition at line 554 of file parser.py.
is_cur_keyword_()
fontTools.voltLib.parser.Parser.is_cur_keyword_ (self, k)
Definition at line 578 of file parser.py.
make_lexer_()
fontTools.voltLib.parser.Parser.make_lexer_ (self, file_or_path)
Definition at line 36 of file parser.py.
parse()
fontTools.voltLib.parser.Parser.parse (self)
Definition at line 46 of file parser.py.
Referenced by pandas.io.formats.css.CSSResolver.__call__(), and pip._vendor.rich.style.Style.normalize().
parse_adjust_by_()
fontTools.voltLib.parser.Parser.parse_adjust_by_ (self)
Definition at line 472 of file parser.py.
parse_adjust_pair_()
fontTools.voltLib.parser.Parser.parse_adjust_pair_ (self)
Definition at line 397 of file parser.py.
parse_adjust_single_()
fontTools.voltLib.parser.Parser.parse_adjust_single_ (self)
Definition at line 424 of file parser.py.
parse_attach_()
fontTools.voltLib.parser.Parser.parse_attach_ (self)
Definition at line 362 of file parser.py.
parse_attach_cursive_()
fontTools.voltLib.parser.Parser.parse_attach_cursive_ (self)
Definition at line 380 of file parser.py.
parse_cmap_format()
fontTools.voltLib.parser.Parser.parse_cmap_format (self)
Definition at line 571 of file parser.py.
parse_context_()
fontTools.voltLib.parser.Parser.parse_context_ (self)
Definition at line 273 of file parser.py.
parse_coverage_()
fontTools.voltLib.parser.Parser.parse_coverage_ (self)
Definition at line 528 of file parser.py.
parse_def_anchor_()
fontTools.voltLib.parser.Parser.parse_def_anchor_ (self)
Definition at line 437 of file parser.py.
parse_def_glyph_()
fontTools.voltLib.parser.Parser.parse_def_glyph_ (self)
Definition at line 62 of file parser.py.
parse_def_group_()
fontTools.voltLib.parser.Parser.parse_def_group_ (self)
Definition at line 99 of file parser.py.
parse_def_lookup_()
fontTools.voltLib.parser.Parser.parse_def_lookup_ (self)
Definition at line 186 of file parser.py.
parse_def_script_()
fontTools.voltLib.parser.Parser.parse_def_script_ (self)
Definition at line 117 of file parser.py.
parse_enum_()
fontTools.voltLib.parser.Parser.parse_enum_ (self)
Definition at line 521 of file parser.py.
parse_feature_()
fontTools.voltLib.parser.Parser.parse_feature_ (self)
Definition at line 170 of file parser.py.
parse_langsys_()
fontTools.voltLib.parser.Parser.parse_langsys_ (self)
Definition at line 152 of file parser.py.
parse_noarg_option_()
fontTools.voltLib.parser.Parser.parse_noarg_option_ (self)
Definition at line 564 of file parser.py.
parse_pos_()
fontTools.voltLib.parser.Parser.parse_pos_ (self)
Definition at line 480 of file parser.py.
parse_position_()
fontTools.voltLib.parser.Parser.parse_position_ (self)
Definition at line 343 of file parser.py.
parse_ppem_()
fontTools.voltLib.parser.Parser.parse_ppem_ (self)
Definition at line 557 of file parser.py.
parse_substitution_()
fontTools.voltLib.parser.Parser.parse_substitution_ (self, reversal)
Definition at line 300 of file parser.py.
parse_unicode_values_()
fontTools.voltLib.parser.Parser.parse_unicode_values_ (self)
Definition at line 512 of file parser.py.
resolve_group()
fontTools.voltLib.parser.Parser.resolve_group (self, group_name)
Definition at line 551 of file parser.py.
Member Data Documentation
anchors_
dict fontTools.voltLib.parser.Parser.anchors_ = {}
Definition at line 27 of file parser.py.
cur_token_
fontTools.voltLib.parser.Parser.cur_token_ = k)
Definition at line 579 of file parser.py.
cur_token_location_
fontTools.voltLib.parser.Parser.cur_token_location_ = keyword:
Definition at line 58 of file parser.py.
cur_token_type_
fontTools.voltLib.parser.Parser.cur_token_type_
Definition at line 606 of file parser.py.
doc_
fontTools.voltLib.parser.Parser.doc_ = ast.VoltFile()
Definition at line 24 of file parser.py.
glyphs_
fontTools.voltLib.parser.Parser.glyphs_ = OrderedSymbolTable()
Definition at line 25 of file parser.py.
groups_
fontTools.voltLib.parser.Parser.groups_ = SymbolTable()
Definition at line 26 of file parser.py.
langs_
fontTools.voltLib.parser.Parser.langs_ = SymbolTable()
Definition at line 29 of file parser.py.
lexer_
fontTools.voltLib.parser.Parser.lexer_ = Lexer(data, filename)
Definition at line 44 of file parser.py.
lookups_
fontTools.voltLib.parser.Parser.lookups_ = SymbolTable()
Definition at line 30 of file parser.py.
next_token_
fontTools.voltLib.parser.Parser.next_token_ = (None, None)
Definition at line 31 of file parser.py.
next_token_location_
fontTools.voltLib.parser.Parser.next_token_location_ = None
Definition at line 32 of file parser.py.
next_token_type_
fontTools.voltLib.parser.Parser.next_token_type_ = self.expect_string_()
Definition at line 31 of file parser.py.
scripts_
fontTools.voltLib.parser.Parser.scripts_ = SymbolTable()
Definition at line 28 of file parser.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/voltLib/parser.py