Code Cloning Analysis: numpy.testing._private.utils.clear_and_catch_warnings Class Reference
numpy.testing._private.utils.clear_and_catch_warnings Class Reference
Public Member Functions
__init__ (self, record=False, modules=())
__enter__ (self)
__exit__ (self, *exc_info)
Public Attributes
modules = set(modules).union(self.class_modules)
Static Public Attributes
tuple class_modules = ()
Protected Attributes
dict _warnreg_copies = {}
Detailed Description
 Context manager that resets warning registry for catching warnings
Warnings can be slippery, because, whenever a warning is triggered, Python
adds a ``__warningregistry__`` member to the *calling* module.  This makes
it impossible to retrigger the warning in this module, whatever you put in
the warnings filters.  This context manager accepts a sequence of `modules`
as a keyword argument to its constructor and:
* stores and removes any ``__warningregistry__`` entries in given `modules`
  on entry;
* resets ``__warningregistry__`` to its previous state on exit.
This makes it possible to trigger any warning afresh inside the context
manager without disturbing the state of warnings outside.
For compatibility with Python 3.0, please consider all arguments to be
keyword-only.
Parameters
----------
record : bool, optional
    Specifies whether warnings should be captured by a custom
    implementation of ``warnings.showwarning()`` and be appended to a list
    returned by the context manager. Otherwise None is returned by the
    context manager. The objects appended to the list are arguments whose
    attributes mirror the arguments to ``showwarning()``.
modules : sequence, optional
    Sequence of modules for which to reset warnings registry on entry and
    restore on exit. To work correctly, all 'ignore' filters should
    filter by one of these modules.
Examples
--------
>>> import warnings
>>> with np.testing.clear_and_catch_warnings(
...         modules=[np.core.fromnumeric]):
...     warnings.simplefilter('always')
...     warnings.filterwarnings('ignore', module='np.core.fromnumeric')
...     # do something that raises a warning but ignore those in
...     # np.core.fromnumeric
Definition at line 1938 of file utils.py.
Constructor & Destructor Documentation
__init__()
numpy.testing._private.utils.clear_and_catch_warnings.__init__ (self, record = False, modules = ())
Definition at line 1982 of file utils.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__enter__()
numpy.testing._private.utils.clear_and_catch_warnings.__enter__ (self)
Definition at line 1987 of file utils.py.
__exit__()
numpy.testing._private.utils.clear_and_catch_warnings.__exit__ (self, * exc_info)
Definition at line 1995 of file utils.py.
Member Data Documentation
_warnreg_copies
dict numpy.testing._private.utils.clear_and_catch_warnings._warnreg_copies = {} protected
Definition at line 1984 of file utils.py.
class_modules
tuple numpy.testing._private.utils.clear_and_catch_warnings.class_modules = () static
Definition at line 1980 of file utils.py.
modules
numpy.testing._private.utils.clear_and_catch_warnings.modules = set(modules).union(self.class_modules)
Definition at line 1983 of file utils.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/testing/_private/utils.py