Code Cloning Analysis: pandas._testing._warnings Namespace Reference
pandas._testing._warnings Namespace Reference
Functions
Generator[list[warnings.WarningMessage], None, None] assert_produces_warning (type[Warning]|bool|tuple[type[Warning],...]|None expected_warning=Warning, Literal["error", "ignore", "always", "default", "module", "once"] filter_level="always", bool check_stacklevel=True, bool raise_on_extra_warnings=True, str|None match=None)
maybe_produces_warning (type[Warning] warning, bool condition, **kwargs)
None _assert_caught_expected_warning (*, Sequence[warnings.WarningMessage] caught_warnings, type[Warning] expected_warning, str|None match, bool check_stacklevel)
None _assert_caught_no_extra_warnings (*, Sequence[warnings.WarningMessage] caught_warnings, type[Warning]|bool|tuple[type[Warning],...]|None expected_warning)
bool _is_unexpected_warning (warnings.WarningMessage actual_warning, type[Warning]|bool|tuple[type[Warning],...]|None expected_warning)
None _assert_raised_with_correct_stacklevel (warnings.WarningMessage actual_warning)
Function Documentation
_assert_caught_expected_warning()
None pandas._testing._warnings._assert_caught_expected_warning (* , Sequence[warnings.WarningMessage] caught_warnings, type[Warning] expected_warning, str | None match, bool check_stacklevel) protected
Assert that there was the expected warning among the caught warnings.
Definition at line 125 of file _warnings.py.
Referenced by assert_produces_warning().
_assert_caught_no_extra_warnings()
None pandas._testing._warnings._assert_caught_no_extra_warnings (* , Sequence[warnings.WarningMessage] caught_warnings, type[Warning] | bool | tuple[type[Warning], ...] | None expected_warning) protected
Assert that no extra warnings apart from the expected ones are caught.
Definition at line 164 of file _warnings.py.
References _is_unexpected_warning().
Referenced by assert_produces_warning().
_assert_raised_with_correct_stacklevel()
None pandas._testing._warnings._assert_raised_with_correct_stacklevel (warnings.WarningMessage actual_warning) protected
Definition at line 214 of file _warnings.py.
_is_unexpected_warning()
bool pandas._testing._warnings._is_unexpected_warning (warnings.WarningMessage actual_warning, type[Warning] | bool | tuple[type[Warning], ...] | None expected_warning) protected
Check if the actual warning issued is unexpected.
Definition at line 203 of file _warnings.py.
Referenced by _assert_caught_no_extra_warnings().
assert_produces_warning()
Generator[list[warnings.WarningMessage], None, None] pandas._testing._warnings.assert_produces_warning (type[Warning] | bool | tuple[type[Warning], ...] | None expected_warning = Warning, Literal[ "error", "ignore", "always", "default", "module", "once" ] filter_level = "always", bool check_stacklevel = True, bool raise_on_extra_warnings = True, str | None match = None)
Context manager for running code expected to either raise a specific warning,
multiple specific warnings, or not raise any warnings. Verifies that the code
raises the expected warning(s), and that it does not raise any other unexpected
warnings. It is basically a wrapper around ``warnings.catch_warnings``.
Parameters
----------
expected_warning : {Warning, False, tuple[Warning, ...], None}, default Warning
    The type of Exception raised. ``exception.Warning`` is the base
    class for all warnings. To raise multiple types of exceptions,
    pass them as a tuple. To check that no warning is returned,
    specify ``False`` or ``None``.
filter_level : str or None, default "always"
    Specifies whether warnings are ignored, displayed, or turned
    into errors.
    Valid values are:
    * "error" - turns matching warnings into exceptions
    * "ignore" - discard the warning
    * "always" - always emit a warning
    * "default" - print the warning the first time it is generated
      from each location
    * "module" - print the warning the first time it is generated
      from each module
    * "once" - print the warning the first time it is generated
check_stacklevel : bool, default True
    If True, displays the line that called the function containing
    the warning to show were the function is called. Otherwise, the
    line that implements the function is displayed.
raise_on_extra_warnings : bool, default True
    Whether extra warnings not of the type `expected_warning` should
    cause the test to fail.
match : str, optional
    Match warning message.
Examples
--------
>>> import warnings
>>> with assert_produces_warning():
...     warnings.warn(UserWarning())
...
>>> with assert_produces_warning(False):
...     warnings.warn(RuntimeWarning())
...
Traceback (most recent call last):
    ...
AssertionError: Caused unexpected warning(s): ['RuntimeWarning'].
>>> with assert_produces_warning(UserWarning):
...     warnings.warn(RuntimeWarning())
Traceback (most recent call last):
    ...
AssertionError: Did not see expected warning of class 'UserWarning'.
..warn:: This is *not* thread-safe.
Definition at line 27 of file _warnings.py.
References _assert_caught_expected_warning(), and _assert_caught_no_extra_warnings().
Referenced by maybe_produces_warning().
maybe_produces_warning()
pandas._testing._warnings.maybe_produces_warning (type[Warning] warning, bool condition, ** kwargs)
Return a context manager that possibly checks a warning based on the condition
Definition at line 115 of file _warnings.py.
References assert_produces_warning().