Code Cloning Analysis: matplotlib.tri._trirefine.TriRefiner Class Reference
matplotlib.tri._trirefine.TriRefiner Class Reference
Public Member Functions
__init__ (self, triangulation)
Protected Attributes
_triangulation = triangulation
Detailed Description
Abstract base class for classes implementing mesh refinement.
A TriRefiner encapsulates a Triangulation object and provides tools for
mesh refinement and interpolation.
Derived classes must implement:
- ``refine_triangulation(return_tri_index=False, **kwargs)`` , where
  the optional keyword arguments *kwargs* are defined in each
  TriRefiner concrete implementation, and which returns:
  - a refined triangulation,
  - optionally (depending on *return_tri_index*), for each
    point of the refined triangulation: the index of
    the initial triangulation triangle to which it belongs.
- ``refine_field(z, triinterpolator=None, **kwargs)``, where:
  - *z* array of field values (to refine) defined at the base
    triangulation nodes,
  - *triinterpolator* is an optional `~matplotlib.tri.TriInterpolator`,
  - the other optional keyword arguments *kwargs* are defined in
    each TriRefiner concrete implementation;
  and which returns (as a tuple) a refined triangular mesh and the
  interpolated values of the field at the refined triangulation nodes.
Definition at line 12 of file _trirefine.py.
Constructor & Destructor Documentation
__init__()
matplotlib.tri._trirefine.TriRefiner.__init__ (self, triangulation)
Definition at line 42 of file _trirefine.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Data Documentation
_triangulation
matplotlib.tri._trirefine.TriRefiner._triangulation = triangulation protected
Definition at line 44 of file _trirefine.py.
Referenced by matplotlib.tri._tritools.TriAnalyzer._get_compressed_triangulation(), matplotlib.tri._tritools.TriAnalyzer.circle_ratios(), matplotlib.tri._tritools.TriAnalyzer.get_flat_tri_mask(), matplotlib.tri._trirefine.UniformTriRefiner.refine_field(), matplotlib.tri._trirefine.UniformTriRefiner.refine_triangulation(), and matplotlib.tri._tritools.TriAnalyzer.scale_factors().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/tri/_trirefine.py