Code Cloning Analysis: scipy.interpolate.tests.test_bsplines Namespace Reference
scipy.interpolate.tests.test_bsplines Namespace Reference
Classes
class TestBSpline
class TestInterop
class TestInterp
class TestLSQ
class TestSmoothingSpline
Functions
test_knots_multiplicity ()
_naive_B (x, k, i, t)
stolen from @pv, verbatim
_naive_eval (x, t, c, k)
stolen from @pv, verbatim
_naive_eval_2 (x, t, c, k)
_sum_basis_elements (x, t, c, k)
B_012 (x)
B_0123 (x, der=0)
_make_random_spline (n=35, k=3)
_make_multiples (b)
make_interp_full_matr (x, y, t, k)
make_lsq_full_matrix (x, y, t, k=3)
data_file (basename)
Function Documentation
_make_multiples()
scipy.interpolate.tests.test_bsplines._make_multiples (b) protected
Increase knot multiplicity.
Definition at line 718 of file test_bsplines.py.
Referenced by scipy.interpolate.tests.test_bsplines.TestBSpline.test_from_power_basis_exmp().
_make_random_spline()
scipy.interpolate.tests.test_bsplines._make_random_spline (n = 35, k = 3) protected
Definition at line 711 of file test_bsplines.py.
_naive_B()
scipy.interpolate.tests.test_bsplines._naive_B (x, k, i, t) protected
stolen from @pv, verbatim
Naive way to compute B-spline basis functions. Useful only for testing!
computes B(x; t[i],..., t[i+k+1])
Definition at line 632 of file test_bsplines.py.
References _naive_B().
Referenced by _naive_B(), _naive_eval(), and _naive_eval_2().
_naive_eval()
scipy.interpolate.tests.test_bsplines._naive_eval (x, t, c, k) protected
stolen from @pv, verbatim
Naive B-spline evaluation. Useful only for testing!
Definition at line 651 of file test_bsplines.py.
References _naive_B().
_naive_eval_2()
scipy.interpolate.tests.test_bsplines._naive_eval_2 (x, t, c, k) protected
Naive B-spline evaluation, another way.
Definition at line 664 of file test_bsplines.py.
References _naive_B().
_sum_basis_elements()
scipy.interpolate.tests.test_bsplines._sum_basis_elements (x, t, c, k) protected
Definition at line 673 of file test_bsplines.py.
B_012()
scipy.interpolate.tests.test_bsplines.B_012 (x)
 A linear B-spline function B(x | 0, 1, 2).
Definition at line 684 of file test_bsplines.py.
B_0123()
scipy.interpolate.tests.test_bsplines.B_0123 (x, der = 0)
A quadratic B-spline function B(x | 0, 1, 2, 3).
Definition at line 693 of file test_bsplines.py.
data_file()
scipy.interpolate.tests.test_bsplines.data_file (basename)
Definition at line 1530 of file test_bsplines.py.
make_interp_full_matr()
scipy.interpolate.tests.test_bsplines.make_interp_full_matr (x, y, t, k)
Assemble an spline order k with knots t to interpolate
y(x) using full matrices.
Not-a-knot BC only.
This routine is here for testing only (even though it's functional).
Definition at line 1385 of file test_bsplines.py.
make_lsq_full_matrix()
scipy.interpolate.tests.test_bsplines.make_lsq_full_matrix (x, y, t, k = 3)
Make the least-square spline, full matrices.
Definition at line 1413 of file test_bsplines.py.
test_knots_multiplicity()
scipy.interpolate.tests.test_bsplines.test_knots_multiplicity ()
Definition at line 609 of file test_bsplines.py.