Code Cloning Analysis: matplotlib.projections.geo.AitoffAxes Class Reference
matplotlib.projections.geo.AitoffAxes Class Reference
Classes
class AitoffTransform
class InvertedAitoffTransform
Public Member Functions
__init__ (self, *args, **kwargs)
Public Member Functions inherited from matplotlib.projections.geo.GeoAxes
clear (self)
get_xaxis_transform (self, which='grid')
get_xaxis_text1_transform (self, pad)
get_xaxis_text2_transform (self, pad)
get_yaxis_transform (self, which='grid')
get_yaxis_text1_transform (self, pad)
get_yaxis_text2_transform (self, pad)
set_yscale (self, *args, **kwargs)
set_xlim (self, *args, **kwargs)
invert_xaxis (self)
format_coord (self, lon, lat)
set_longitude_grid (self, degrees)
set_latitude_grid (self, degrees)
set_longitude_grid_ends (self, degrees)
get_data_ratio (self)
can_zoom (self)
Interactive panning.
can_pan (self)
start_pan (self, x, y, button)
end_pan (self)
drag_pan (self, button, key, x, y)
Public Member Functions inherited from matplotlib.axes._axes.Axes
get_title (self, loc="center")
Labelling, legend and texts.
set_title (self, label, fontdict=None, loc=None, pad=None, *, y=None, **kwargs)
get_legend_handles_labels (self, legend_handler_map=None)
legend (self, *args, **kwargs)
inset_axes (self, bounds, *, transform=None, zorder=5, **kwargs)
indicate_inset (self, bounds=None, inset_ax=None, *, transform=None, facecolor='none', edgecolor='0.5', alpha=0.5, zorder=None, **kwargs)
indicate_inset_zoom (self, inset_ax, **kwargs)
secondary_xaxis (self, location, functions=None, *, transform=None, **kwargs)
secondary_yaxis (self, location, functions=None, *, transform=None, **kwargs)
text (self, x, y, s, fontdict=None, **kwargs)
annotate (self, text, xy, xytext=None, xycoords='data', textcoords=None, arrowprops=None, annotation_clip=None, **kwargs)
axhline (self, y=0, xmin=0, xmax=1, **kwargs)
Lines and spans.
axvline (self, x=0, ymin=0, ymax=1, **kwargs)
axline (self, xy1, xy2=None, *, slope=None, **kwargs)
axhspan (self, ymin, ymax, xmin=0, xmax=1, **kwargs)
axvspan (self, xmin, xmax, ymin=0, ymax=1, **kwargs)
hlines (self, y, xmin, xmax, colors=None, linestyles='solid', label='', **kwargs)
vlines (self, x, ymin, ymax, colors=None, linestyles='solid', label='', **kwargs)
eventplot (self, positions, orientation='horizontal', lineoffsets=1, linelengths=1, linewidths=None, colors=None, alpha=None, linestyles='solid', **kwargs)
plot (self, *args, scalex=True, scaley=True, data=None, **kwargs)
Basic plotting.
plot_date (self, x, y, fmt='o', tz=None, xdate=True, ydate=False, **kwargs)
loglog (self, *args, **kwargs)
semilogx (self, *args, **kwargs)
semilogy (self, *args, **kwargs)
acorr (self, x, **kwargs)
xcorr (self, x, y, normed=True, detrend=mlab.detrend_none, usevlines=True, maxlags=10, **kwargs)
step (self, x, y, *args, where='pre', data=None, **kwargs)
Specialized plotting.
bar (self, x, height, width=0.8, bottom=None, *, align="center", **kwargs)
barh (self, y, width, height=0.8, left=None, *, align="center", data=None, **kwargs)
bar_label (self, container, labels=None, *, fmt="%g", label_type="edge", padding=0, **kwargs)
broken_barh (self, xranges, yrange, **kwargs)
stem (self, *args, linefmt=None, markerfmt=None, basefmt=None, bottom=0, label=None, orientation='vertical')
pie (self, x, explode=None, labels=None, colors=None, autopct=None, pctdistance=0.6, shadow=False, labeldistance=1.1, startangle=0, radius=1, counterclock=True, wedgeprops=None, textprops=None, center=(0, 0), frame=False, rotatelabels=False, *, normalize=True, hatch=None)
errorbar (self, x, y, yerr=None, xerr=None, fmt='', ecolor=None, elinewidth=None, capsize=None, barsabove=False, lolims=False, uplims=False, xlolims=False, xuplims=False, errorevery=1, capthick=None, **kwargs)
boxplot (self, x, notch=None, sym=None, vert=None, orientation='vertical', whis=None, positions=None, widths=None, patch_artist=None, bootstrap=None, usermedians=None, conf_intervals=None, meanline=None, showmeans=None, showcaps=None, showbox=None, showfliers=None, boxprops=None, tick_labels=None, flierprops=None, medianprops=None, meanprops=None, capprops=None, whiskerprops=None, manage_ticks=True, autorange=False, zorder=None, capwidths=None, label=None)
bxp (self, bxpstats, positions=None, widths=None, vert=None, orientation='vertical', patch_artist=False, shownotches=False, showmeans=False, showcaps=True, showbox=True, showfliers=True, boxprops=None, whiskerprops=None, flierprops=None, medianprops=None, capprops=None, meanprops=None, meanline=False, manage_ticks=True, zorder=None, capwidths=None, label=None)
scatter (self, x, y, s=None, c=None, marker=None, cmap=None, norm=None, vmin=None, vmax=None, alpha=None, linewidths=None, *, edgecolors=None, colorizer=None, plotnonfinite=False, **kwargs)
hexbin (self, x, y, C=None, gridsize=100, bins=None, xscale='linear', yscale='linear', extent=None, cmap=None, norm=None, vmin=None, vmax=None, alpha=None, linewidths=None, edgecolors='face', reduce_C_function=np.mean, mincnt=None, marginals=False, colorizer=None, **kwargs)
arrow (self, x, y, dx, dy, **kwargs)
quiverkey (self, Q, X, Y, U, label, **kwargs)
quiver (self, *args, **kwargs)
barbs (self, *args, **kwargs)
fill (self, *args, data=None, **kwargs)
fill_between (self, x, y1, y2=0, where=None, interpolate=False, step=None, **kwargs)
fill_betweenx (self, y, x1, x2=0, where=None, step=None, interpolate=False, **kwargs)
imshow (self, X, cmap=None, norm=None, *, aspect=None, interpolation=None, alpha=None, vmin=None, vmax=None, colorizer=None, origin=None, extent=None, interpolation_stage=None, filternorm=True, filterrad=4.0, resample=None, url=None, **kwargs)
plotting z(x, y): imshow, pcolor and relatives, contour
pcolor (self, *args, shading=None, alpha=None, norm=None, cmap=None, vmin=None, vmax=None, colorizer=None, **kwargs)
pcolormesh (self, *args, alpha=None, norm=None, cmap=None, vmin=None, vmax=None, colorizer=None, shading=None, antialiased=False, **kwargs)
pcolorfast (self, *args, alpha=None, norm=None, cmap=None, vmin=None, vmax=None, colorizer=None, **kwargs)
contour (self, *args, **kwargs)
contourf (self, *args, **kwargs)
clabel (self, CS, levels=None, **kwargs)
hist (self, x, bins=None, range=None, density=False, weights=None, cumulative=False, bottom=None, histtype='bar', align='mid', orientation='vertical', rwidth=None, log=False, color=None, label=None, stacked=False, **kwargs)
Data analysis.
stairs (self, values, edges=None, *, orientation='vertical', baseline=0, fill=False, **kwargs)
hist2d (self, x, y, bins=10, range=None, density=False, weights=None, cmin=None, cmax=None, **kwargs)
ecdf (self, x, weights=None, *, complementary=False, orientation="vertical", compress=False, **kwargs)
psd (self, x, NFFT=None, Fs=None, Fc=None, detrend=None, window=None, noverlap=None, pad_to=None, sides=None, scale_by_freq=None, return_line=None, **kwargs)
csd (self, x, y, NFFT=None, Fs=None, Fc=None, detrend=None, window=None, noverlap=None, pad_to=None, sides=None, scale_by_freq=None, return_line=None, **kwargs)
magnitude_spectrum (self, x, Fs=None, Fc=None, window=None, pad_to=None, sides=None, scale=None, **kwargs)
angle_spectrum (self, x, Fs=None, Fc=None, window=None, pad_to=None, sides=None, **kwargs)
phase_spectrum (self, x, Fs=None, Fc=None, window=None, pad_to=None, sides=None, **kwargs)
cohere (self, x, y, NFFT=256, Fs=2, Fc=0, detrend=mlab.detrend_none, window=mlab.window_hanning, noverlap=0, pad_to=None, sides='default', scale_by_freq=None, **kwargs)
specgram (self, x, NFFT=None, Fs=None, Fc=None, detrend=None, window=None, noverlap=None, cmap=None, xextent=None, pad_to=None, sides=None, scale_by_freq=None, mode=None, scale=None, vmin=None, vmax=None, **kwargs)
spy (self, Z, precision=0, marker=None, markersize=None, aspect='equal', origin="upper", **kwargs)
matshow (self, Z, **kwargs)
violinplot (self, dataset, positions=None, vert=None, orientation='vertical', widths=0.5, showmeans=False, showextrema=True, showmedians=False, quantiles=None, points=100, bw_method=None, side='both')
violin (self, vpstats, positions=None, vert=None, orientation='vertical', widths=0.5, showmeans=False, showextrema=True, showmedians=False, side='both')
Public Member Functions inherited from matplotlib.axes._base._AxesBase
__str__ (self)
__init__ (self, fig, *args, facecolor=None, frameon=True, sharex=None, sharey=None, label='', xscale=None, yscale=None, box_aspect=None, forward_navigation_events="auto", **kwargs)
__init_subclass__ (cls, **kwargs)
__getstate__ (self)
__setstate__ (self, state)
__repr__ (self)
get_subplotspec (self)
set_subplotspec (self, subplotspec)
get_gridspec (self)
get_window_extent (self, renderer=None)
set_figure (self, fig)
viewLim (self)
get_position (self, original=False)
set_position (self, pos, which='both')
reset_position (self)
set_axes_locator (self, locator)
get_axes_locator (self)
sharex (self, other)
sharey (self, other)
cla (self)
artists (self)
collections (self)
images (self)
lines (self)
patches (self)
tables (self)
texts (self)
get_facecolor (self)
set_facecolor (self, color)
set_prop_cycle (self, *args, **kwargs)
get_aspect (self)
set_aspect (self, aspect, adjustable=None, anchor=None, share=False)
get_adjustable (self)
set_adjustable (self, adjustable, share=False)
get_box_aspect (self)
set_box_aspect (self, aspect=None)
get_anchor (self)
set_anchor (self, anchor, share=False)
apply_aspect (self, position=None)
axis (self, arg=None, *, emit=True, **kwargs)
get_legend (self)
get_images (self)
get_lines (self)
get_xaxis (self)
get_yaxis (self)
has_data (self)
add_artist (self, a)
add_child_axes (self, ax)
add_collection (self, collection, autolim=True)
add_image (self, image)
add_line (self, line)
add_patch (self, p)
add_table (self, tab)
add_container (self, container)
relim (self, visible_only=False)
update_datalim (self, xys, updatex=True, updatey=True)
in_axes (self, mouseevent)
get_autoscale_on (self)
set_autoscale_on (self, b)
use_sticky_edges (self)
use_sticky_edges (self, b)
get_xmargin (self)
get_ymargin (self)
set_xmargin (self, m)
set_ymargin (self, m)
margins (self, *margins, x=None, y=None, tight=True)
set_rasterization_zorder (self, z)
get_rasterization_zorder (self)
autoscale (self, enable=True, axis='both', tight=None)
autoscale_view (self, tight=None, scalex=True, scaley=True)
draw (self, renderer)
draw_artist (self, a)
redraw_in_frame (self)
get_frame_on (self)
set_frame_on (self, b)
get_axisbelow (self)
set_axisbelow (self, b)
grid (self, visible=None, which='major', axis='both', **kwargs)
ticklabel_format (self, *, axis='both', style=None, scilimits=None, useOffset=None, useLocale=None, useMathText=None)
locator_params (self, axis='both', tight=None, **kwargs)
tick_params (self, axis='both', **kwargs)
set_axis_off (self)
set_axis_on (self)
get_xlabel (self)
set_xlabel (self, xlabel, fontdict=None, labelpad=None, *, loc=None, **kwargs)
get_xbound (self)
set_xbound (self, lower=None, upper=None)
get_xlim (self)
get_ylabel (self)
set_ylabel (self, ylabel, fontdict=None, labelpad=None, *, loc=None, **kwargs)
invert_yaxis (self)
get_ybound (self)
set_ybound (self, lower=None, upper=None)
get_ylim (self)
set_ylim (self, bottom=None, top=None, *, emit=True, auto=False, ymin=None, ymax=None)
format_xdata (self, x)
format_ydata (self, y)
minorticks_on (self)
minorticks_off (self)
get_navigate (self)
set_navigate (self, b)
get_navigate_mode (self)
set_navigate_mode (self, b)
get_children (self)
contains (self, mouseevent)
contains_point (self, point)
get_default_bbox_extra_artists (self)
get_tightbbox (self, renderer=None, *, call_axes_locator=True, bbox_extra_artists=None, for_layout_only=False)
twinx (self)
twiny (self)
get_shared_x_axes (self)
get_shared_y_axes (self)
label_outer (self, remove_inner_ticks=False)
set_forward_navigation_events (self, forward)
get_forward_navigation_events (self)
Protected Member Functions
_get_core_transform (self, resolution)
Protected Member Functions inherited from matplotlib.projections.geo.GeoAxes
_init_axis (self)
_set_lim_and_transforms (self)
_get_affine_transform (self)
_gen_axes_patch (self)
_gen_axes_spines (self)
Protected Member Functions inherited from matplotlib.axes._axes.Axes
_remove_legend (self, legend)
_parse_bar_color_args (self, kwargs)
_quiver_units (self, args, kwargs)
_fill_between_x_or_y (self, ind_dir, ind, dep1, dep2=0, *, where=None, interpolate=False, step=None, **kwargs)
_fill_between_process_units (self, ind_dir, dep_dir, ind, dep1, dep2, **kwargs)
_pcolorargs (self, funcname, *args, shading='auto', **kwargs)
_get_aspect_ratio (self)
Protected Member Functions inherited from matplotlib.axes._base._AxesBase
_axis_map (self)
_unstale_viewLim (self)
_request_autoscale_view (self, axis="all", tight=None)
_update_transScale (self)
_set_position (self, pos, which='both')
_set_artist_props (self, a)
_set_title_offset_trans (self, title_offset_points)
_sci (self, im)
_gci (self)
_update_image_limits (self, image)
_add_text (self, txt)
_update_line_limits (self, line)
_update_patch_limits (self, patch)
_unit_change_handler (self, axis_name, event=None)
_process_unit_info (self, datasets=None, kwargs=None, *, convert=True)
_update_title_position (self, renderer)
_validate_converted_limits (self, limit, convert)
_get_view (self)
_set_view (self, view)
_prepare_view_from_bbox (self, bbox, direction='in', mode=None, twinx=False, twiny=False)
_set_view_from_bbox (self, bbox, direction='in', mode=None, twinx=False, twiny=False)
_get_pan_points (self, button, key, x, y)
_make_twin_axes (self, *args, **kwargs)
_label_outer_xaxis (self, *, skip_non_rectangular_axes, remove_inner_ticks=False)
_label_outer_yaxis (self, *, skip_non_rectangular_axes, remove_inner_ticks=False)
Additional Inherited Members
Public Attributes inherited from matplotlib.projections.geo.GeoAxes
transProjection = self._get_core_transform(self.RESOLUTION)
transAffine = self._get_affine_transform()
Public Attributes inherited from matplotlib.axes._axes.Axes
hlines
vlines
Public Attributes inherited from matplotlib.axes._base._AxesBase
axes = self
fmt_xdata = None
fmt_ydata = None
bbox
transScale
transAxes = mtransforms.BboxTransformTo(self.bbox)
transLimits
transData = self.transScale + (self.transLimits + self.transAxes)
bool stale = True
bool ignore_existing_data_limits = True
callbacks
list child_axes = []
legend_ = None
list containers = []
title
patch = self._gen_axes_patch()
titleOffsetTrans
images
lines
use_sticky_edges = np.array([])
set_xbound
set_ybound
bool axison
zorder
Static Public Attributes inherited from matplotlib.projections.geo.GeoAxes
RESOLUTION
Static Public Attributes inherited from matplotlib.axes._axes.Axes
dir
ind
dep
fill_between
fill_betweenx
table = _make_axes_method(mtable.table)
stackplot = _preprocess_data()(_make_axes_method(mstack.stackplot))
streamplot
tricontour = _make_axes_method(mtri.tricontour)
tricontourf = _make_axes_method(mtri.tricontourf)
tripcolor = _make_axes_method(mtri.tripcolor)
triplot = _make_axes_method(mtri.triplot)
Static Public Attributes inherited from matplotlib.axes._base._AxesBase
str name = "rectilinear"
mtransforms dataLim .Bbox
mspines spines .Spines
maxis xaxis .XAxis
maxis yaxis .YAxis
get_xgridlines = _axis_method_wrapper("xaxis", "get_gridlines")
get_xticklines = _axis_method_wrapper("xaxis", "get_ticklines")
get_ygridlines = _axis_method_wrapper("yaxis", "get_gridlines")
get_yticklines = _axis_method_wrapper("yaxis", "get_ticklines")
get_autoscalex_on = _axis_method_wrapper("xaxis", "_get_autoscale_on")
get_autoscaley_on = _axis_method_wrapper("yaxis", "_get_autoscale_on")
set_autoscalex_on = _axis_method_wrapper("xaxis", "_set_autoscale_on")
set_autoscaley_on = _axis_method_wrapper("yaxis", "_set_autoscale_on")
xaxis_inverted = _axis_method_wrapper("xaxis", "get_inverted")
get_xscale = _axis_method_wrapper("xaxis", "get_scale")
set_xscale = _axis_method_wrapper("xaxis", "_set_axes_scale")
get_xticks = _axis_method_wrapper("xaxis", "get_ticklocs")
set_xticks
get_xmajorticklabels = _axis_method_wrapper("xaxis", "get_majorticklabels")
get_xminorticklabels = _axis_method_wrapper("xaxis", "get_minorticklabels")
get_xticklabels = _axis_method_wrapper("xaxis", "get_ticklabels")
set_xticklabels
yaxis_inverted = _axis_method_wrapper("yaxis", "get_inverted")
get_yscale = _axis_method_wrapper("yaxis", "get_scale")
get_yticks = _axis_method_wrapper("yaxis", "get_ticklocs")
set_yticks
get_ymajorticklabels = _axis_method_wrapper("yaxis", "get_majorticklabels")
get_yminorticklabels = _axis_method_wrapper("yaxis", "get_minorticklabels")
get_yticklabels = _axis_method_wrapper("yaxis", "get_ticklabels")
set_yticklabels
xaxis_date = _axis_method_wrapper("xaxis", "axis_date")
yaxis_date = _axis_method_wrapper("yaxis", "axis_date")
Static Protected Member Functions inherited from matplotlib.axes._axes.Axes
_check_no_units (vals, names)
_convert_dx (dx, x0, xconv, convert)
_errorevery_to_mask (x, errorevery)
_parse_scatter_color_args (c, edgecolors, kwargs, xsize, get_next_color_func)
Protected Attributes inherited from matplotlib.projections.geo.GeoAxes
_xaxis_pretransform
_xaxis_text1_transform
_xaxis_text2_transform
_yaxis_text1_transform
_yaxis_text2_transform
_longitude_cap = np.deg2rad(degrees)
Protected Attributes inherited from matplotlib.axes._base._AxesBase
_position = args[0].frozen()
_originalPosition = self._position.frozen()
str _aspect = 'auto'
str _adjustable = 'box'
str _anchor = 'C'
_stale_viewlims = dict.fromkeys(self._axis_names, False)
_forward_navigation_events = forward_navigation_events
_sharex = sharex
_sharey = sharey
_subplotspec = None
_axes_locator = None
list _children = []
list _colorbars = []
_facecolor = facecolor
_frameon = frameon
_rasterization_zorder = None
bool _stale = True
_viewLim = mtransforms.Bbox.unit()
_tight = tight
_xaxis_transform
_yaxis_transform
int _xmargin = mpl.rcParams['axes.xmargin']
int _ymargin = mpl.rcParams['axes.ymargin']
bool _use_sticky_edges = True
_get_lines = _process_plot_var_args()
_get_patches_for_fill = _process_plot_var_args('Polygon')
_gridOn = mpl.rcParams['axes.grid']
_mouseover_set = _OrderedSet()
_current_image = None
_projection_init = None
bool _autotitlepos = True
_left_title
_right_title
_unit_change_handler
_axis_map = object())
_axisbelow = validate_axisbelow(b)
_navigate = b
_navigate_mode = b
_pan_start
Static Protected Attributes inherited from matplotlib.axes._base._AxesBase
tuple _axis_names = ("x", "y")
dict _shared_axes = {name: cbook.Grouper() for name in _axis_names}
_twinned_axes = cbook.Grouper()
bool _subclass_uses_cla = False
Detailed Description
Definition at line 255 of file geo.py.
Constructor & Destructor Documentation
__init__()
matplotlib.projections.geo.AitoffAxes.__init__ (self, * args, ** kwargs)
Definition at line 291 of file geo.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_get_core_transform()
matplotlib.projections.geo.AitoffAxes._get_core_transform (self, resolution) protected
Definition at line 297 of file geo.py.
Referenced by matplotlib.projections.geo.GeoAxes._set_lim_and_transforms().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/projections/geo.py