Code Cloning Analysis: sklearn.mixture.tests.test_gaussian_mixture Namespace Reference
sklearn.mixture.tests.test_gaussian_mixture Namespace Reference
Classes
class RandomData
Functions
generate_data (n_samples, n_features, weights, means, precisions, covariance_type, dtype=np.float64)
test_gaussian_mixture_attributes ()
test_check_weights ()
test_check_means ()
test_check_precisions ()
test_suffstat_sk_full ()
test_suffstat_sk_tied ()
test_suffstat_sk_diag ()
test_gaussian_suffstat_sk_spherical (global_dtype)
test_compute_log_det_cholesky (global_dtype)
_naive_lmvnpdf_diag (X, means, covars)
test_gaussian_mixture_log_probabilities ()
test_gaussian_mixture_estimate_log_prob_resp ()
test_gaussian_mixture_predict_predict_proba ()
test_gaussian_mixture_fit_predict (seed, max_iter, tol, global_dtype)
test_gaussian_mixture_fit_predict_n_init ()
test_gaussian_mixture_fit (global_dtype)
test_gaussian_mixture_fit_best_params ()
test_gaussian_mixture_fit_convergence_warning ()
test_multiple_init ()
test_gaussian_mixture_n_parameters ()
test_bic_1d_1component ()
test_gaussian_mixture_aic_bic ()
test_gaussian_mixture_verbose ()
test_warm_start (seed)
test_convergence_detected_with_warm_start ()
test_score (global_dtype)
test_score_samples ()
test_monotonic_likelihood ()
test_regularisation ()
test_fitted_precision_covariance_concistency (covar_type, global_dtype)
test_sample ()
test_init ()
test_gaussian_mixture_setting_best_params ()
test_init_means_not_duplicated (init_params, global_random_seed)
test_means_for_all_inits (init_params, global_random_seed, global_dtype)
test_max_iter_zero ()
test_gaussian_mixture_precisions_init_diag (global_dtype)
_generate_data (seed, n_samples, n_features, n_components, dtype=np.float64)
_calculate_precisions (X, resp, covariance_type)
test_gaussian_mixture_precisions_init (covariance_type, global_random_seed, global_dtype)
test_gaussian_mixture_single_component_stable ()
test_gaussian_mixture_all_init_does_not_estimate_gaussian_parameters (monkeypatch, global_random_seed)
Variables
list COVARIANCE_TYPE = ["full", "tied", "diag", "spherical"]
Function Documentation
_calculate_precisions()
sklearn.mixture.tests.test_gaussian_mixture._calculate_precisions (X, resp, covariance_type) protected
Calculate precision matrix of X and its Cholesky decomposition
for the given covariance type.
Definition at line 1385 of file test_gaussian_mixture.py.
Referenced by test_gaussian_mixture_precisions_init().
_generate_data()
sklearn.mixture.tests.test_gaussian_mixture._generate_data (seed, n_samples, n_features, n_components, dtype = np.float64) protected
Randomly generate samples and responsibilities.
Definition at line 1376 of file test_gaussian_mixture.py.
Referenced by test_gaussian_mixture_precisions_init().
_naive_lmvnpdf_diag()
sklearn.mixture.tests.test_gaussian_mixture._naive_lmvnpdf_diag (X, means, covars) protected
Definition at line 447 of file test_gaussian_mixture.py.
generate_data()
sklearn.mixture.tests.test_gaussian_mixture.generate_data (n_samples, n_features, weights, means, precisions, covariance_type, dtype = np.float64)
Definition at line 43 of file test_gaussian_mixture.py.
test_bic_1d_1component()
sklearn.mixture.tests.test_gaussian_mixture.test_bic_1d_1component ()
Definition at line 759 of file test_gaussian_mixture.py.
test_check_means()
sklearn.mixture.tests.test_gaussian_mixture.test_check_means ()
Definition at line 219 of file test_gaussian_mixture.py.
test_check_precisions()
sklearn.mixture.tests.test_gaussian_mixture.test_check_precisions ()
Definition at line 242 of file test_gaussian_mixture.py.
test_check_weights()
sklearn.mixture.tests.test_gaussian_mixture.test_check_weights ()
Definition at line 171 of file test_gaussian_mixture.py.
test_compute_log_det_cholesky()
sklearn.mixture.tests.test_gaussian_mixture.test_compute_log_det_cholesky (global_dtype)
Definition at line 420 of file test_gaussian_mixture.py.
test_convergence_detected_with_warm_start()
sklearn.mixture.tests.test_gaussian_mixture.test_convergence_detected_with_warm_start ()
Definition at line 910 of file test_gaussian_mixture.py.
test_fitted_precision_covariance_concistency()
sklearn.mixture.tests.test_gaussian_mixture.test_fitted_precision_covariance_concistency (covar_type, global_dtype)
Definition at line 1073 of file test_gaussian_mixture.py.
test_gaussian_mixture_aic_bic()
sklearn.mixture.tests.test_gaussian_mixture.test_gaussian_mixture_aic_bic ()
Definition at line 785 of file test_gaussian_mixture.py.
test_gaussian_mixture_all_init_does_not_estimate_gaussian_parameters()
sklearn.mixture.tests.test_gaussian_mixture.test_gaussian_mixture_all_init_does_not_estimate_gaussian_parameters (monkeypatch, global_random_seed)
When all init parameters are provided, the Gaussian parameters
are not estimated.
Non-regression test for gh-26015.
Definition at line 1445 of file test_gaussian_mixture.py.
test_gaussian_mixture_attributes()
sklearn.mixture.tests.test_gaussian_mixture.test_gaussian_mixture_attributes ()
Definition at line 144 of file test_gaussian_mixture.py.
test_gaussian_mixture_estimate_log_prob_resp()
sklearn.mixture.tests.test_gaussian_mixture.test_gaussian_mixture_estimate_log_prob_resp ()
Definition at line 503 of file test_gaussian_mixture.py.
test_gaussian_mixture_fit()
sklearn.mixture.tests.test_gaussian_mixture.test_gaussian_mixture_fit (global_dtype)
Definition at line 609 of file test_gaussian_mixture.py.
test_gaussian_mixture_fit_best_params()
sklearn.mixture.tests.test_gaussian_mixture.test_gaussian_mixture_fit_best_params ()
Definition at line 666 of file test_gaussian_mixture.py.
test_gaussian_mixture_fit_convergence_warning()
sklearn.mixture.tests.test_gaussian_mixture.test_gaussian_mixture_fit_convergence_warning ()
Definition at line 696 of file test_gaussian_mixture.py.
test_gaussian_mixture_fit_predict()
sklearn.mixture.tests.test_gaussian_mixture.test_gaussian_mixture_fit_predict (seed, max_iter, tol, global_dtype)
Definition at line 572 of file test_gaussian_mixture.py.
test_gaussian_mixture_fit_predict_n_init()
sklearn.mixture.tests.test_gaussian_mixture.test_gaussian_mixture_fit_predict_n_init ()
Definition at line 600 of file test_gaussian_mixture.py.
test_gaussian_mixture_log_probabilities()
sklearn.mixture.tests.test_gaussian_mixture.test_gaussian_mixture_log_probabilities ()
Definition at line 455 of file test_gaussian_mixture.py.
test_gaussian_mixture_n_parameters()
sklearn.mixture.tests.test_gaussian_mixture.test_gaussian_mixture_n_parameters ()
Definition at line 746 of file test_gaussian_mixture.py.
test_gaussian_mixture_precisions_init()
sklearn.mixture.tests.test_gaussian_mixture.test_gaussian_mixture_precisions_init (covariance_type, global_random_seed, global_dtype)
Non-regression test for #26415.
Definition at line 1407 of file test_gaussian_mixture.py.
References _calculate_precisions(), and _generate_data().
test_gaussian_mixture_precisions_init_diag()
sklearn.mixture.tests.test_gaussian_mixture.test_gaussian_mixture_precisions_init_diag (global_dtype)
Check that we properly initialize `precision_cholesky_` when we manually
provide the precision matrix.
In this regard, we check the consistency between estimating the precision
matrix and providing the same precision matrix as initialization. It should
lead to the same results with the same number of iterations.
If the initialization is wrong then the number of iterations will increase.
Non-regression test for:
https://github.com/scikit-learn/scikit-learn/issues/16944
Definition at line 1308 of file test_gaussian_mixture.py.
test_gaussian_mixture_predict_predict_proba()
sklearn.mixture.tests.test_gaussian_mixture.test_gaussian_mixture_predict_predict_proba ()
Definition at line 532 of file test_gaussian_mixture.py.
test_gaussian_mixture_setting_best_params()
sklearn.mixture.tests.test_gaussian_mixture.test_gaussian_mixture_setting_best_params ()
`GaussianMixture`'s best_parameters, `n_iter_` and `lower_bound_`
must be set appropriately in the case of divergence.
Non-regression test for:
https://github.com/scikit-learn/scikit-learn/issues/18216
Definition at line 1174 of file test_gaussian_mixture.py.
test_gaussian_mixture_single_component_stable()
sklearn.mixture.tests.test_gaussian_mixture.test_gaussian_mixture_single_component_stable ()
Non-regression test for #23032 ensuring 1-component GM works on only a
few samples.
Definition at line 1434 of file test_gaussian_mixture.py.
test_gaussian_mixture_verbose()
sklearn.mixture.tests.test_gaussian_mixture.test_gaussian_mixture_verbose ()
Definition at line 809 of file test_gaussian_mixture.py.
test_gaussian_suffstat_sk_spherical()
sklearn.mixture.tests.test_gaussian_mixture.test_gaussian_suffstat_sk_spherical (global_dtype)
Definition at line 396 of file test_gaussian_mixture.py.
test_init()
sklearn.mixture.tests.test_gaussian_mixture.test_init ()
Definition at line 1155 of file test_gaussian_mixture.py.
test_init_means_not_duplicated()
sklearn.mixture.tests.test_gaussian_mixture.test_init_means_not_duplicated (init_params, global_random_seed)
Definition at line 1247 of file test_gaussian_mixture.py.
test_max_iter_zero()
sklearn.mixture.tests.test_gaussian_mixture.test_max_iter_zero ()
Definition at line 1288 of file test_gaussian_mixture.py.
test_means_for_all_inits()
sklearn.mixture.tests.test_gaussian_mixture.test_means_for_all_inits (init_params, global_random_seed, global_dtype)
Definition at line 1267 of file test_gaussian_mixture.py.
test_monotonic_likelihood()
sklearn.mixture.tests.test_gaussian_mixture.test_monotonic_likelihood ()
Definition at line 1006 of file test_gaussian_mixture.py.
test_multiple_init()
sklearn.mixture.tests.test_gaussian_mixture.test_multiple_init ()
Definition at line 720 of file test_gaussian_mixture.py.
test_regularisation()
sklearn.mixture.tests.test_gaussian_mixture.test_regularisation ()
Definition at line 1040 of file test_gaussian_mixture.py.
test_sample()
sklearn.mixture.tests.test_gaussian_mixture.test_sample ()
Definition at line 1097 of file test_gaussian_mixture.py.
test_score()
sklearn.mixture.tests.test_gaussian_mixture.test_score (global_dtype)
Definition at line 932 of file test_gaussian_mixture.py.
test_score_samples()
sklearn.mixture.tests.test_gaussian_mixture.test_score_samples ()
Definition at line 980 of file test_gaussian_mixture.py.
test_suffstat_sk_diag()
sklearn.mixture.tests.test_gaussian_mixture.test_suffstat_sk_diag ()
Definition at line 371 of file test_gaussian_mixture.py.
test_suffstat_sk_full()
sklearn.mixture.tests.test_gaussian_mixture.test_suffstat_sk_full ()
Definition at line 299 of file test_gaussian_mixture.py.
test_suffstat_sk_tied()
sklearn.mixture.tests.test_gaussian_mixture.test_suffstat_sk_tied ()
Definition at line 341 of file test_gaussian_mixture.py.
test_warm_start()
sklearn.mixture.tests.test_gaussian_mixture.test_warm_start (seed)
Definition at line 842 of file test_gaussian_mixture.py.
Variable Documentation
COVARIANCE_TYPE
list sklearn.mixture.tests.test_gaussian_mixture.COVARIANCE_TYPE = ["full", "tied", "diag", "spherical"]
Definition at line 40 of file test_gaussian_mixture.py.