Code Cloning Analysis: joblib.externals.loky.process_executor Namespace Reference
joblib.externals.loky.process_executor Namespace Reference
Classes
class _CallItem
class _ExceptionWithTraceback
class _ExecutorFlags
class _ExecutorManagerThread
class _RemoteTraceback
class _ResultItem
class _SafeQueue
class _ThreadWakeup
class _WorkItem
class BrokenProcessPool
class LokyRecursionError
class ProcessPoolExecutor
class ShutdownExecutorError
class TerminatedWorkerError
Functions
_get_memory_usage (pid, force_gc=False)
_python_exit ()
_rebuild_exc (exc, tb)
_get_chunks (chunksize, *iterables)
_process_chunk (fn, chunk)
_sendback_result (result_queue, work_id, result=None, exception=None)
_enable_faulthandler_if_needed ()
_process_worker (call_queue, result_queue, initializer, initargs, processes_management_lock, timeout, worker_exit_lock, current_depth)
_check_system_limits ()
_chain_from_iterable_of_lists (iterable)
_check_max_depth (context)
Variables
str __author__ = "Thomas Moreau (thomas.moreau.2010@gmail.com)"
Re-implementation of the ProcessPoolExecutor more robust to faults.
MAX_DEPTH = int(os.environ.get("LOKY_MAX_DEPTH", 10))
int _CURRENT_DEPTH = 0
float _MEMORY_LEAK_CHECK_DELAY = 1.0
_MAX_MEMORY_LEAK_SIZE = int(3e8)
bool _USE_PSUTIL = True
bool _global_shutdown = False
_global_shutdown_lock = threading.Lock()
_threads_wakeups = weakref.WeakKeyDictionary()
process_pool_executor_at_exit = None
int EXTRA_QUEUED_CALLS = 1
bool _system_limits_checked = False
_system_limited = None
BrokenExecutor = BrokenProcessPool
Function Documentation
_chain_from_iterable_of_lists()
joblib.externals.loky.process_executor._chain_from_iterable_of_lists (iterable) protected
Specialized implementation of itertools.chain.from_iterable.
Each item in *iterable* should be a list.  This function is
careful not to keep references to yielded objects.
Definition at line 991 of file process_executor.py.
Referenced by joblib.externals.loky.process_executor.ProcessPoolExecutor.map().
_check_max_depth()
joblib.externals.loky.process_executor._check_max_depth (context) protected
Definition at line 1003 of file process_executor.py.
_check_system_limits()
joblib.externals.loky.process_executor._check_system_limits () protected
Definition at line 966 of file process_executor.py.
_enable_faulthandler_if_needed()
joblib.externals.loky.process_executor._enable_faulthandler_if_needed () protected
Definition at line 381 of file process_executor.py.
_get_chunks()
joblib.externals.loky.process_executor._get_chunks (chunksize, * iterables) protected
Iterates over zip()ed iterables in chunks.
Definition at line 348 of file process_executor.py.
Referenced by joblib.externals.loky.process_executor.ProcessPoolExecutor.map().
_get_memory_usage()
joblib.externals.loky.process_executor._get_memory_usage (pid, force_gc = False) protected
Definition at line 108 of file process_executor.py.
_process_chunk()
joblib.externals.loky.process_executor._process_chunk (fn, chunk) protected
Processes a chunk of an iterable passed to map.
Runs the function passed to map() on a chunk of the
iterable passed to map.
This function is run in a separate process.
Definition at line 358 of file process_executor.py.
_process_worker()
joblib.externals.loky.process_executor._process_worker (call_queue, result_queue, initializer, initargs, processes_management_lock, timeout, worker_exit_lock, current_depth) protected
Evaluates calls from call_queue and places the results in result_queue.
This worker is run in a separate process.
Args:
    call_queue: A ctx.Queue of _CallItems that will be read and
        evaluated by the worker.
    result_queue: A ctx.Queue of _ResultItems that will written
        to by the worker.
    initializer: A callable initializer, or None
    initargs: A tuple of args for the initializer
    processes_management_lock: A ctx.Lock avoiding worker timeout while
        some workers are being spawned.
    timeout: maximum time to wait for a new item in the call_queue. If that
        time is expired, the worker will shutdown.
    worker_exit_lock: Lock to avoid flagging the executor as broken on
        workers timeout.
    current_depth: Nested parallelism level, to avoid infinite spawning.
Definition at line 403 of file process_executor.py.
References _sendback_result().
_python_exit()
joblib.externals.loky.process_executor._python_exit () protected
Definition at line 187 of file process_executor.py.
_rebuild_exc()
joblib.externals.loky.process_executor._rebuild_exc (exc, tb) protected
Definition at line 256 of file process_executor.py.
_sendback_result()
joblib.externals.loky.process_executor._sendback_result (result_queue, work_id, result = None, exception = None) protected
Safely send back the given result or exception
Definition at line 370 of file process_executor.py.
Referenced by _process_worker().
Variable Documentation
__author__
str joblib.externals.loky.process_executor.__author__ = "Thomas Moreau (thomas.moreau.2010@gmail.com)" private
Re-implementation of the ProcessPoolExecutor more robust to faults.
author: Thomas Moreau and Olivier Grisel
adapted from concurrent/futures/process_pool_executor.py (17/02/2017)
Add an extra management thread to detect executor_manager_thread failures,
Improve the shutdown process to avoid deadlocks,
Add timeout for workers,
More robust pickling process.
Copyright 2009 Brian Quinlan. All Rights Reserved. Licensed to PSF under a Contributor Agreement.
Definition at line 58 of file process_executor.py.
_CURRENT_DEPTH
int joblib.externals.loky.process_executor._CURRENT_DEPTH = 0 protected
Definition at line 94 of file process_executor.py.
_global_shutdown
bool joblib.externals.loky.process_executor._global_shutdown = False protected
Definition at line 182 of file process_executor.py.
_global_shutdown_lock
joblib.externals.loky.process_executor._global_shutdown_lock = threading.Lock() protected
Definition at line 183 of file process_executor.py.
_MAX_MEMORY_LEAK_SIZE
joblib.externals.loky.process_executor._MAX_MEMORY_LEAK_SIZE = int(3e8) protected
Definition at line 100 of file process_executor.py.
_MEMORY_LEAK_CHECK_DELAY
float joblib.externals.loky.process_executor._MEMORY_LEAK_CHECK_DELAY = 1.0 protected
Definition at line 97 of file process_executor.py.
_system_limited
joblib.externals.loky.process_executor._system_limited = None protected
Definition at line 963 of file process_executor.py.
_system_limits_checked
bool joblib.externals.loky.process_executor._system_limits_checked = False protected
Definition at line 962 of file process_executor.py.
_threads_wakeups
joblib.externals.loky.process_executor._threads_wakeups = weakref.WeakKeyDictionary() protected
Definition at line 184 of file process_executor.py.
_USE_PSUTIL
bool joblib.externals.loky.process_executor._USE_PSUTIL = True protected
Definition at line 106 of file process_executor.py.
BrokenExecutor
joblib.externals.loky.process_executor.BrokenExecutor = BrokenProcessPool
Definition at line 1043 of file process_executor.py.
EXTRA_QUEUED_CALLS
int joblib.externals.loky.process_executor.EXTRA_QUEUED_CALLS = 1
Definition at line 227 of file process_executor.py.
MAX_DEPTH
joblib.externals.loky.process_executor.MAX_DEPTH = int(os.environ.get("LOKY_MAX_DEPTH", 10))
Definition at line 93 of file process_executor.py.
process_pool_executor_at_exit
joblib.externals.loky.process_executor.process_pool_executor_at_exit = None
Definition at line 221 of file process_executor.py.