Code Cloning Analysis: pip._vendor.chardet.chardistribution.CharDistributionAnalysis Class Reference
pip._vendor.chardet.chardistribution.CharDistributionAnalysis Class Reference
Public Member Functions
None __init__ (self)
None reset (self)
None feed (self, Union[bytes, bytearray] char, int char_len)
float get_confidence (self)
bool got_enough_data (self)
int get_order (self, Union[bytes, bytearray] _)
Public Attributes
float typical_distribution_ratio = 0.0
Static Public Attributes
int ENOUGH_DATA_THRESHOLD = 1024
float SURE_YES = 0.99
float SURE_NO = 0.01
int MINIMUM_DATA_THRESHOLD = 3
Protected Attributes
Tuple[int,...] _char_to_freq_order = tuple()
int _table_size = 0
bool _done = False
int _total_chars = 0
int _freq_chars = 0
Detailed Description
Definition at line 58 of file chardistribution.py.
Constructor & Destructor Documentation
__init__()
None pip._vendor.chardet.chardistribution.CharDistributionAnalysis.__init__ (self)
Definition at line 64 of file chardistribution.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
feed()
None pip._vendor.chardet.chardistribution.CharDistributionAnalysis.feed (self, Union[bytes, bytearray] char, int char_len)
feed a character with known length
Definition at line 88 of file chardistribution.py.
References _char_to_freq_order, _freq_chars, _table_size, _total_chars, and get_order().
get_confidence()
float pip._vendor.chardet.chardistribution.CharDistributionAnalysis.get_confidence (self)
return confidence based on existing data
Definition at line 102 of file chardistribution.py.
References _freq_chars, _total_chars, ENOUGH_DATA_THRESHOLD, MINIMUM_DATA_THRESHOLD, SURE_NO, SURE_YES, and typical_distribution_ratio.
Referenced by pip._vendor.chardet.utf1632prober.UTF1632Prober.validate_utf16_characters().
get_order()
int pip._vendor.chardet.chardistribution.CharDistributionAnalysis.get_order (self, Union[bytes, bytearray] _)
Definition at line 124 of file chardistribution.py.
Referenced by feed().
got_enough_data()
bool pip._vendor.chardet.chardistribution.CharDistributionAnalysis.got_enough_data (self)
Definition at line 119 of file chardistribution.py.
reset()
None pip._vendor.chardet.chardistribution.CharDistributionAnalysis.reset (self)
reset analyser, clear any state
Definition at line 79 of file chardistribution.py.
References _done, _freq_chars, and _total_chars.
Referenced by scipy._lib._docscrape.Reader.__init__().
Member Data Documentation
_char_to_freq_order
Tuple[int, ...] pip._vendor.chardet.chardistribution.CharDistributionAnalysis._char_to_freq_order = tuple() protected
Definition at line 67 of file chardistribution.py.
Referenced by feed().
_done
bool pip._vendor.chardet.chardistribution.CharDistributionAnalysis._done = False protected
Definition at line 74 of file chardistribution.py.
Referenced by reset().
_freq_chars
int pip._vendor.chardet.chardistribution.CharDistributionAnalysis._freq_chars = 0 protected
Definition at line 76 of file chardistribution.py.
Referenced by feed(), get_confidence(), and reset().
_table_size
int pip._vendor.chardet.chardistribution.CharDistributionAnalysis._table_size = 0 protected
Definition at line 68 of file chardistribution.py.
Referenced by feed().
_total_chars
int pip._vendor.chardet.chardistribution.CharDistributionAnalysis._total_chars = 0 protected
Definition at line 75 of file chardistribution.py.
Referenced by feed(), get_confidence(), and reset().
ENOUGH_DATA_THRESHOLD
int pip._vendor.chardet.chardistribution.CharDistributionAnalysis.ENOUGH_DATA_THRESHOLD = 1024 static
Definition at line 59 of file chardistribution.py.
Referenced by get_confidence().
MINIMUM_DATA_THRESHOLD
int pip._vendor.chardet.chardistribution.CharDistributionAnalysis.MINIMUM_DATA_THRESHOLD = 3 static
Definition at line 62 of file chardistribution.py.
Referenced by get_confidence().
SURE_NO
float pip._vendor.chardet.chardistribution.CharDistributionAnalysis.SURE_NO = 0.01 static
Definition at line 61 of file chardistribution.py.
Referenced by get_confidence().
SURE_YES
float pip._vendor.chardet.chardistribution.CharDistributionAnalysis.SURE_YES = 0.99 static
Definition at line 60 of file chardistribution.py.
Referenced by get_confidence().
typical_distribution_ratio
float pip._vendor.chardet.chardistribution.CharDistributionAnalysis.typical_distribution_ratio = 0.0
Definition at line 73 of file chardistribution.py.
Referenced by get_confidence().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pip/_vendor/chardet/chardistribution.py