Code Cloning Analysis: sklearn.pipeline Namespace Reference
sklearn.pipeline Namespace Reference
Classes
class FeatureUnion
class Pipeline
Functions
_raise_or_warn_if_not_fitted (estimator)
_final_estimator_has (attr)
_cached_transform (sub_pipeline, *, cache, param_name, param_value, transform_params)
_name_estimators (estimators)
make_pipeline (*steps, memory=None, transform_input=None, verbose=False)
_transform_one (transformer, X, y, weight, params)
_fit_transform_one (transformer, X, y, weight, message_clsname="", message=None, params=None)
_fit_one (transformer, X, y, weight, message_clsname="", message=None, params=None)
make_union (*transformers, n_jobs=None, verbose=False, verbose_feature_names_out=True)
Variables
list __all__ = ["FeatureUnion", "Pipeline", "make_pipeline", "make_union"]
_final_estimator
Detailed Description
Utilities to build a composite estimator as a chain of transforms and estimators.
Function Documentation
_cached_transform()
sklearn.pipeline._cached_transform (sub_pipeline, * , cache, param_name, param_value, transform_params) protected
Transform a parameter value using a sub-pipeline and cache the result.
Parameters
----------
sub_pipeline : Pipeline
    The sub-pipeline to be used for transformation.
cache : dict
    The cache dictionary to store the transformed values.
param_name : str
    The name of the parameter to be transformed.
param_value : object
    The value of the parameter to be transformed.
transform_params : dict
    The metadata to be used for transformation. This passed to the
    `transform` method of the sub-pipeline.
Returns
-------
transformed_value : object
    The transformed value of the parameter.
Definition at line 83 of file pipeline.py.
Referenced by sklearn.pipeline.Pipeline._get_metadata_for_step().
_final_estimator_has()
sklearn.pipeline._final_estimator_has (attr) protected
Check that final_estimator has `attr`.
Used together with `available_if` in `Pipeline`.
Definition at line 70 of file pipeline.py.
_fit_one()
sklearn.pipeline._fit_one (transformer, X, y, weight, message_clsname = "", message = None, params = None) protected
Fits ``transformer`` to ``X`` and ``y``.
Definition at line 1551 of file pipeline.py.
_fit_transform_one()
sklearn.pipeline._fit_transform_one (transformer, X, y, weight, message_clsname = "", message = None, params = None) protected
Fits ``transformer`` to ``X`` and ``y``. The transformed result is returned
with the fitted transformer. If ``weight`` is not ``None``, the result will
be multiplied by ``weight``.
``params`` needs to be of the form ``process_routing()["step_name"]``.
Definition at line 1527 of file pipeline.py.
_name_estimators()
sklearn.pipeline._name_estimators (estimators) protected
Generate names for estimators.
Definition at line 1410 of file pipeline.py.
Referenced by make_pipeline(), and make_union().
_raise_or_warn_if_not_fitted()
sklearn.pipeline._raise_or_warn_if_not_fitted (estimator) protected
A context manager to make sure a NotFittedError is raised, if a sub-estimator
raises the error.
Otherwise, we raise a warning if the pipeline is not fitted, with the deprecation.
TODO(1.8): remove this context manager and replace with check_is_fitted.
Definition at line 44 of file pipeline.py.
Referenced by sklearn.pipeline.Pipeline.decision_function(), sklearn.pipeline.Pipeline.inverse_transform(), sklearn.pipeline.Pipeline.predict(), sklearn.pipeline.Pipeline.predict_log_proba(), sklearn.pipeline.Pipeline.predict_proba(), sklearn.pipeline.Pipeline.score(), sklearn.pipeline.Pipeline.score_samples(), and sklearn.pipeline.Pipeline.transform().
_transform_one()
sklearn.pipeline._transform_one (transformer, X, y, weight, params) protected
Call transform and apply weight to output.
Parameters
----------
transformer : estimator
    Estimator to be used for transformation.
X : {array-like, sparse matrix} of shape (n_samples, n_features)
    Input data to be transformed.
y : ndarray of shape (n_samples,)
    Ignored.
weight : float
    Weight to be applied to the output of the transformation.
params : dict
    Parameters to be passed to the transformer's ``transform`` method.
    This should be of the form ``process_routing()["step_name"]``.
Definition at line 1498 of file pipeline.py.
make_pipeline()
sklearn.pipeline.make_pipeline (* steps, memory = None, transform_input = None, verbose = False)
Construct a :class:`Pipeline` from the given estimators.
This is a shorthand for the :class:`Pipeline` constructor; it does not
require, and does not permit, naming the estimators. Instead, their names
will be set to the lowercase of their types automatically.
Parameters
----------
*steps : list of Estimator objects
    List of the scikit-learn estimators that are chained together.
memory : str or object with the joblib.Memory interface, default=None
    Used to cache the fitted transformers of the pipeline. The last step
    will never be cached, even if it is a transformer. By default, no
    caching is performed. If a string is given, it is the path to the
    caching directory. Enabling caching triggers a clone of the transformers
    before fitting. Therefore, the transformer instance given to the
    pipeline cannot be inspected directly. Use the attribute ``named_steps``
    or ``steps`` to inspect estimators within the pipeline. Caching the
    transformers is advantageous when fitting is time consuming.
transform_input : list of str, default=None
    This enables transforming some input arguments to ``fit`` (other than ``X``)
    to be transformed by the steps of the pipeline up to the step which requires
    them. Requirement is defined via :ref:`metadata routing <metadata_routing>`.
    This can be used to pass a validation set through the pipeline for instance.
    You can only set this if metadata routing is enabled, which you
    can enable using ``sklearn.set_config(enable_metadata_routing=True)``.
    .. versionadded:: 1.6
verbose : bool, default=False
    If True, the time elapsed while fitting each step will be printed as it
    is completed.
Returns
-------
p : Pipeline
    Returns a scikit-learn :class:`Pipeline` object.
See Also
--------
Pipeline : Class for creating a pipeline of transforms with a final
    estimator.
Examples
--------
>>> from sklearn.naive_bayes import GaussianNB
>>> from sklearn.preprocessing import StandardScaler
>>> from sklearn.pipeline import make_pipeline
>>> make_pipeline(StandardScaler(), GaussianNB(priors=None))
Pipeline(steps=[('standardscaler', StandardScaler()),
                ('gaussiannb', GaussianNB())])
Definition at line 1434 of file pipeline.py.
References _name_estimators().
make_union()
sklearn.pipeline.make_union (* transformers, n_jobs = None, verbose = False, verbose_feature_names_out = True)
Construct a :class:`FeatureUnion` from the given transformers.
This is a shorthand for the :class:`FeatureUnion` constructor; it does not
require, and does not permit, naming the transformers. Instead, they will
be given names automatically based on their types. It also does not allow
weighting.
Parameters
----------
*transformers : list of estimators
    One or more estimators.
n_jobs : int, default=None
    Number of jobs to run in parallel.
    ``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.
    ``-1`` means using all processors. See :term:`Glossary <n_jobs>`
    for more details.
    .. versionchanged:: v0.20
       `n_jobs` default changed from 1 to None.
verbose : bool, default=False
    If True, the time elapsed while fitting each transformer will be
    printed as it is completed.
verbose_feature_names_out : bool, default=True
    If True, the feature names generated by `get_feature_names_out` will
    include prefixes derived from the transformer names.
Returns
-------
f : FeatureUnion
    A :class:`FeatureUnion` object for concatenating the results of multiple
    transformer objects.
See Also
--------
FeatureUnion : Class for concatenating the results of multiple transformer
    objects.
Examples
--------
>>> from sklearn.decomposition import PCA, TruncatedSVD
>>> from sklearn.pipeline import make_union
>>> make_union(PCA(), TruncatedSVD())
 FeatureUnion(transformer_list=[('pca', PCA()),
                               ('truncatedsvd', TruncatedSVD())])
Definition at line 2132 of file pipeline.py.
References _name_estimators().
Variable Documentation
__all__
list sklearn.pipeline.__all__ = ["FeatureUnion", "Pipeline", "make_pipeline", "make_union"] private
Definition at line 40 of file pipeline.py.
_final_estimator
sklearn.pipeline._final_estimator protected
Definition at line 77 of file pipeline.py.