Code Cloning Analysis: dateutil.parser._parser.parserinfo Class Reference
dateutil.parser._parser.parserinfo Class Reference
Public Member Functions
__init__ (self, dayfirst=False, yearfirst=False)
jump (self, name)
weekday (self, name)
month (self, name)
hms (self, name)
ampm (self, name)
pertain (self, name)
utczone (self, name)
tzoffset (self, name)
convertyear (self, year, century_specified=False)
validate (self, res)
Public Attributes
dayfirst = dayfirst
yearfirst = yearfirst
Static Public Attributes
list JUMP
list WEEKDAYS
list MONTHS
list HMS
list AMPM
list UTCZONE = ["UTC", "GMT", "Z", "z"]
list PERTAIN = ["of"]
dict TZOFFSET = {}
Protected Member Functions
_convert (self, lst)
Protected Attributes
_jump = self._convert(self.JUMP)
_weekdays = self._convert(self.WEEKDAYS)
_months = self._convert(self.MONTHS)
_hms = self._convert(self.HMS)
_ampm = self._convert(self.AMPM)
_utczone = self._convert(self.UTCZONE)
_pertain = self._convert(self.PERTAIN)
_year = time.localtime().tm_year
int _century = self._year // 100 * 100
Detailed Description
Class which handles what inputs are accepted. Subclass this to customize
the language and acceptable values for each parameter.
:param dayfirst:
    Whether to interpret the first value in an ambiguous 3-integer date
    (e.g. 01/05/09) as the day (``True``) or month (``False``). If
    ``yearfirst`` is set to ``True``, this distinguishes between YDM
    and YMD. Default is ``False``.
:param yearfirst:
    Whether to interpret the first value in an ambiguous 3-integer date
    (e.g. 01/05/09) as the year. If ``True``, the first number is taken
    to be the year, otherwise the last number is taken to be the year.
    Default is ``False``.
Definition at line 241 of file _parser.py.
Constructor & Destructor Documentation
__init__()
dateutil.parser._parser.parserinfo.__init__ (self, dayfirst = False, yearfirst = False)
Definition at line 294 of file _parser.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_convert()
dateutil.parser._parser.parserinfo._convert (self, lst) protected
Definition at line 309 of file _parser.py.
ampm()
dateutil.parser._parser.parserinfo.ampm (self, name)
Definition at line 342 of file _parser.py.
convertyear()
dateutil.parser._parser.parserinfo.convertyear (self, year, century_specified = False)
Converts two-digit years to year within [-50, 49]
range of self._year (current local time)
Definition at line 360 of file _parser.py.
References _century, _year, convertyear(), and utczone().
Referenced by convertyear().
hms()
dateutil.parser._parser.parserinfo.hms (self, name)
Definition at line 336 of file _parser.py.
jump()
dateutil.parser._parser.parserinfo.jump (self, name)
Definition at line 319 of file _parser.py.
month()
dateutil.parser._parser.parserinfo.month (self, name)
Definition at line 329 of file _parser.py.
pertain()
dateutil.parser._parser.parserinfo.pertain (self, name)
Definition at line 348 of file _parser.py.
tzoffset()
dateutil.parser._parser.parserinfo.tzoffset (self, name)
Definition at line 354 of file _parser.py.
utczone()
dateutil.parser._parser.parserinfo.utczone (self, name)
Definition at line 351 of file _parser.py.
Referenced by convertyear().
validate()
dateutil.parser._parser.parserinfo.validate (self, res)
Definition at line 380 of file _parser.py.
Referenced by pip._vendor.distlib.metadata.Metadata.get_requirements(), and numpy.lib._iotools.NameValidator.validate().
weekday()
dateutil.parser._parser.parserinfo.weekday (self, name)
Definition at line 322 of file _parser.py.
Member Data Documentation
_ampm
dateutil.parser._parser.parserinfo._ampm = self._convert(self.AMPM) protected
Definition at line 299 of file _parser.py.
_century
int dateutil.parser._parser.parserinfo._century = self._year // 100 * 100 protected
Definition at line 307 of file _parser.py.
Referenced by convertyear().
_hms
dateutil.parser._parser.parserinfo._hms = self._convert(self.HMS) protected
Definition at line 298 of file _parser.py.
_jump
dateutil.parser._parser.parserinfo._jump = self._convert(self.JUMP) protected
Definition at line 295 of file _parser.py.
_months
dateutil.parser._parser.parserinfo._months = self._convert(self.MONTHS) protected
Definition at line 297 of file _parser.py.
_pertain
dateutil.parser._parser.parserinfo._pertain = self._convert(self.PERTAIN) protected
Definition at line 301 of file _parser.py.
_utczone
dateutil.parser._parser.parserinfo._utczone = self._convert(self.UTCZONE) protected
Definition at line 300 of file _parser.py.
_weekdays
dateutil.parser._parser.parserinfo._weekdays = self._convert(self.WEEKDAYS) protected
Definition at line 296 of file _parser.py.
_year
dateutil.parser._parser.parserinfo._year = time.localtime().tm_year protected
Definition at line 306 of file _parser.py.
Referenced by convertyear().
AMPM
list dateutil.parser._parser.parserinfo.AMPM static
Initial value:
=  [("am", "a"),
            ("pm", "p")]
Definition at line 286 of file _parser.py.
dayfirst
dateutil.parser._parser.parserinfo.dayfirst = dayfirst
Definition at line 303 of file _parser.py.
HMS
list dateutil.parser._parser.parserinfo.HMS static
Initial value:
=  [("h", "hour", "hours"),
           ("m", "minute", "minutes"),
           ("s", "second", "seconds")]
Definition at line 283 of file _parser.py.
JUMP
list dateutil.parser._parser.parserinfo.JUMP static
Initial value:
=  [" ", ".", ",", ";", "-", "/", "'",
            "at", "on", "and", "ad", "m", "t", "of",
            "st", "nd", "rd", "th"]
Definition at line 260 of file _parser.py.
MONTHS
list dateutil.parser._parser.parserinfo.MONTHS static
Initial value:
=  [("Jan", "January"),
              ("Feb", "February"),      # TODO: "Febr"
              ("Mar", "March"),
              ("Apr", "April"),
              ("May", "May"),
              ("Jun", "June"),
              ("Jul", "July"),
              ("Aug", "August"),
              ("Sep", "Sept", "September"),
              ("Oct", "October"),
              ("Nov", "November"),
              ("Dec", "December")]
Definition at line 271 of file _parser.py.
PERTAIN
list dateutil.parser._parser.parserinfo.PERTAIN = ["of"] static
Definition at line 289 of file _parser.py.
TZOFFSET
dict dateutil.parser._parser.parserinfo.TZOFFSET = {} static
Definition at line 290 of file _parser.py.
UTCZONE
list dateutil.parser._parser.parserinfo.UTCZONE = ["UTC", "GMT", "Z", "z"] static
Definition at line 288 of file _parser.py.
WEEKDAYS
list dateutil.parser._parser.parserinfo.WEEKDAYS static
Initial value:
=  [("Mon", "Monday"),
                ("Tue", "Tuesday"),     # TODO: "Tues"
                ("Wed", "Wednesday"),
                ("Thu", "Thursday"),    # TODO: "Thurs"
                ("Fri", "Friday"),
                ("Sat", "Saturday"),
                ("Sun", "Sunday")]
Definition at line 264 of file _parser.py.
yearfirst
dateutil.parser._parser.parserinfo.yearfirst = yearfirst
Definition at line 304 of file _parser.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/dateutil/parser/_parser.py