Code Cloning Analysis: fontTools.ttLib.tables.otConverters.Version Class Reference
fontTools.ttLib.tables.otConverters.Version Class Reference
Public Member Functions
read (self, reader, font, tableDict)
write (self, writer, font, tableDict, value, repeatIndex=None)
Public Member Functions inherited from fontTools.ttLib.tables.otConverters.SimpleValue
xmlWrite (self, xmlWriter, font, value, name, attrs)
xmlRead (self, attrs, content, font)
Public Member Functions inherited from fontTools.ttLib.tables.otConverters.BaseConverter
__init__ (self, name, repeat, aux, tableClass=None, *, description="")
readArray (self, reader, font, tableDict, count)
getRecordSize (self, reader)
writeArray (self, writer, font, tableDict, values)
Optional[int] getVarIndexOffset (self)
Static Public Member Functions
fromString (value)
toString (value)
fromFloat (v)
Static Public Attributes
int staticSize = 4
Static Public Attributes inherited from fontTools.ttLib.tables.otConverters.BaseConverter
varIndexBasePlusOffsetRE = re.compile(r"VarIndexBase\s*\+\s*(\d+)")
Additional Inherited Members
Public Attributes inherited from fontTools.ttLib.tables.otConverters.BaseConverter
name = name
repeat = repeat
aux = aux
tableClass = tableClass
isCount
str isLookupType = "MorphType"
isPropagated
description = description
Detailed Description
Definition at line 542 of file otConverters.py.
Member Function Documentation
fromFloat()
fontTools.ttLib.tables.otConverters.Version.fromFloat (v) static
Definition at line 562 of file otConverters.py.
fromString()
fontTools.ttLib.tables.otConverters.Version.fromString (value) static
Reimplemented from fontTools.ttLib.tables.otConverters.SimpleValue.
Definition at line 554 of file otConverters.py.
read()
fontTools.ttLib.tables.otConverters.Version.read (self, reader, font, tableDict)
Read a value from the reader.
Reimplemented from fontTools.ttLib.tables.otConverters.BaseConverter.
Definition at line 545 of file otConverters.py.
Referenced by pandas.io.parsers.python_parser.PythonParser.__init__(), pip._vendor.urllib3.util.ssltransport.SSLTransport.__init__(), pandas.io.sas.sas7bdat.SAS7BDATReader.column_types(), packaging._tokenizer.Tokenizer.consume(), pip._vendor.urllib3.response.HTTPResponse.drain_conn(), packaging._tokenizer.Tokenizer.expect(), pip._vendor.urllib3.response.HTTPResponse.from_httplib(), pandas.io.sas.sas_xport.XportReader.get_chunk(), packaging._tokenizer.Tokenizer.raise_syntax_error(), PIL.ContainerIO.ContainerIO.readline(), and pip._vendor.urllib3.response.HTTPResponse.stream().
toString()
fontTools.ttLib.tables.otConverters.Version.toString (value) static
Reimplemented from fontTools.ttLib.tables.otConverters.SimpleValue.
Definition at line 558 of file otConverters.py.
write()
fontTools.ttLib.tables.otConverters.Version.write (self, writer, font, tableDict, value, repeatIndex = None)
Write a value to the writer.
Reimplemented from fontTools.ttLib.tables.otConverters.BaseConverter.
Definition at line 549 of file otConverters.py.
Referenced by matplotlib.backends.backend_pdf.PdfFile.addGouraudTriangles(), matplotlib.backends.backend_pdf.PdfFile.close(), joblib.externals.cloudpickle.cloudpickle.Pickler.reducer_override(), scipy.io.matlab._mio5.VarWriter5.write_sparse(), pandas.io.formats.html.HTMLFormatter.write_th(), scipy.io.matlab._mio5.VarWriter5.write_top(), matplotlib.backends.backend_pdf.PdfFile.writeTrailer(), and matplotlib.backends.backend_pdf.PdfFile.writeXref().
Member Data Documentation
staticSize
int fontTools.ttLib.tables.otConverters.Version.staticSize = 4 static
Definition at line 543 of file otConverters.py.
Referenced by fontTools.ttLib.tables.otConverters.Char64.read(), fontTools.ttLib.tables.otConverters.BaseConverter.readArray(), fontTools.ttLib.tables.otConverters.Char64.write(), and fontTools.ttLib.tables.otConverters.Table.write().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ttLib/tables/otConverters.py