Code Cloning Analysis: pandas.tests.plotting.common Namespace Reference
pandas.tests.plotting.common Namespace Reference
Functions
_check_legend_labels (axes, labels=None, visible=True)
_check_legend_marker (ax, expected_markers=None, visible=True)
_check_data (xp, rs)
_check_visible (collections, visible=True)
None _check_patches_all_filled (Axes|Sequence[Axes] axes, bool filled=True)
_get_colors_mapped (series, colors)
_check_colors (collections, linecolors=None, facecolors=None, mapping=None)
_check_text_labels (texts, expected)
_check_ticks_props (axes, xlabelsize=None, xrot=None, ylabelsize=None, yrot=None)
_check_ax_scales (axes, xaxis="linear", yaxis="linear")
_check_axes_shape (axes, axes_num=None, layout=None, figsize=None)
Sequence[Axes] _flatten_visible (Axes|Sequence[Axes] axes)
_check_has_errorbars (axes, xerr=0, yerr=0)
_check_box_return_type (returned, return_type, expected_keys=None, check_ax_title=True)
_check_grid_settings (obj, kinds, kws={})
_unpack_cycler (rcParams, field="color")
get_x_axis (ax)
get_y_axis (ax)
_check_plot_works (f, default_axes=False, **kwargs)
_gen_default_plot (f, fig, **kwargs)
_gen_two_subplots (f, fig, **kwargs)
Detailed Description
Module consolidating common testing functions for checking plotting.
Function Documentation
_check_ax_scales()
pandas.tests.plotting.common._check_ax_scales (axes, xaxis = "linear", yaxis = "linear") protected
Check each axes has expected scales
Parameters
----------
axes : matplotlib Axes object, or its list-like
xaxis : {'linear', 'log'}
    expected xaxis scale
yaxis : {'linear', 'log'}
    expected yaxis scale
Definition at line 269 of file common.py.
References _flatten_visible().
_check_axes_shape()
pandas.tests.plotting.common._check_axes_shape (axes, axes_num = None, layout = None, figsize = None) protected
Check expected number of axes is drawn in expected layout
Parameters
----------
axes : matplotlib Axes object, or its list-like
axes_num : number
    expected number of axes. Unnecessary axes should be set to
    invisible.
layout : tuple
    expected layout, (expected number of rows , columns)
figsize : tuple
    expected figsize. default is matplotlib default
Definition at line 287 of file common.py.
References _flatten_visible().
_check_box_return_type()
pandas.tests.plotting.common._check_box_return_type (returned, return_type, expected_keys = None, check_ax_title = True) protected
Check box returned type is correct
Parameters
----------
returned : object to be tested, returned from boxplot
return_type : str
    return_type passed to boxplot
expected_keys : list-like, optional
    group labels in subplot case. If not passed,
    the function checks assuming boxplot uses single ax
check_ax_title : bool
    Whether to check the ax.title is the same as expected_key
    Intended to be checked by calling from ``boxplot``.
    Normal ``plot`` doesn't attach ``ax.title``, it must be disabled.
Definition at line 375 of file common.py.
References _flatten_visible().
_check_colors()
pandas.tests.plotting.common._check_colors (collections, linecolors = None, facecolors = None, mapping = None) protected
Check each artist has expected line colors and face colors
Parameters
----------
collections : list-like
    list or collection of target artist
linecolors : list-like which has the same length as collections
    list of expected line colors
facecolors : list-like which has the same length as collections
    list of expected face colors
mapping : Series
    Series used for color grouping key
    used for andrew_curves, parallel_coordinates, radviz test
Definition at line 138 of file common.py.
_check_data()
pandas.tests.plotting.common._check_data (xp, rs) protected
Check each axes has identical lines
Parameters
----------
xp : matplotlib Axes object
rs : matplotlib Axes object
Definition at line 70 of file common.py.
_check_grid_settings()
pandas.tests.plotting.common._check_grid_settings (obj, kinds, kws = {}) protected
Definition at line 436 of file common.py.
_check_has_errorbars()
pandas.tests.plotting.common._check_has_errorbars (axes, xerr = 0, yerr = 0) protected
Check axes has expected number of errorbars
Parameters
----------
axes : matplotlib Axes object, or its list-like
xerr : number
    expected number of x errorbar
yerr : number
    expected number of y errorbar
Definition at line 347 of file common.py.
References _flatten_visible().
_check_legend_labels()
pandas.tests.plotting.common._check_legend_labels (axes, labels = None, visible = True) protected
Check each axes has expected legend labels
Parameters
----------
axes : matplotlib Axes object, or its list-like
labels : list-like
    expected legend labels
visible : bool
    expected legend visibility. labels are checked only when visible is
    True
Definition at line 23 of file common.py.
References _check_text_labels(), and _flatten_visible().
_check_legend_marker()
pandas.tests.plotting.common._check_legend_marker (ax, expected_markers = None, visible = True) protected
Check ax has expected legend markers
Parameters
----------
ax : matplotlib Axes object
expected_markers : list-like
    expected legend markers
visible : bool
    expected legend visibility. labels are checked only when visible is
    True
Definition at line 47 of file common.py.
_check_patches_all_filled()
None pandas.tests.plotting.common._check_patches_all_filled (Axes | Sequence[Axes] axes, bool filled = True) protected
Check for each artist whether it is filled or not
Parameters
----------
axes : matplotlib Axes object, or its list-like
filled : bool
    expected filling
Definition at line 113 of file common.py.
References _flatten_visible().
_check_plot_works()
pandas.tests.plotting.common._check_plot_works (f, default_axes = False, ** kwargs) protected
Create plot and ensure that plot return object is valid.
Parameters
----------
f : func
    Plotting function.
default_axes : bool, optional
    If False (default):
        - If `ax` not in `kwargs`, then create subplot(211) and plot there
        - Create new subplot(212) and plot there as well
        - Mind special corner case for bootstrap_plot (see `_gen_two_subplots`)
    If True:
        - Simply run plotting function with kwargs provided
        - All required axes instances will be created automatically
        - It is recommended to use it when the plotting function
        creates multiple axes itself. It helps avoid warnings like
        'UserWarning: To output multiple subplots,
        the figure containing the passed axes is being cleared'
**kwargs
    Keyword arguments passed to the plotting function.
Returns
-------
Plot object returned by the last plotting.
Definition at line 496 of file common.py.
_check_text_labels()
pandas.tests.plotting.common._check_text_labels (texts, expected) protected
Check each text has expected labels
Parameters
----------
texts : matplotlib Text object, or its list-like
    target text, or its list
expected : str or list-like which has the same length as texts
    expected text label, or its list
Definition at line 202 of file common.py.
Referenced by _check_legend_labels().
_check_ticks_props()
pandas.tests.plotting.common._check_ticks_props (axes, xlabelsize = None, xrot = None, ylabelsize = None, yrot = None) protected
Check each axes has expected tick properties
Parameters
----------
axes : matplotlib Axes object, or its list-like
xlabelsize : number
    expected xticks font size
xrot : number
    expected xticks rotation
ylabelsize : number
    expected yticks font size
yrot : number
    expected yticks rotation
Definition at line 222 of file common.py.
References _flatten_visible().
_check_visible()
pandas.tests.plotting.common._check_visible (collections, visible = True) protected
Check each artist is visible or not
Parameters
----------
collections : matplotlib Artist or its list-like
    target Artist or its list or collection
visible : bool
    expected visibility
Definition at line 93 of file common.py.
_flatten_visible()
Sequence[Axes] pandas.tests.plotting.common._flatten_visible (Axes | Sequence[Axes] axes) protected
Flatten axes, and filter only visible
Parameters
----------
axes : matplotlib Axes object, or its list-like
Definition at line 331 of file common.py.
Referenced by _check_ax_scales(), _check_axes_shape(), _check_box_return_type(), _check_has_errorbars(), _check_legend_labels(), _check_patches_all_filled(), and _check_ticks_props().
_gen_default_plot()
pandas.tests.plotting.common._gen_default_plot (f, fig, ** kwargs) protected
Create plot in a default way.
Definition at line 544 of file common.py.
_gen_two_subplots()
pandas.tests.plotting.common._gen_two_subplots (f, fig, ** kwargs) protected
Create plot on two subplots forcefully created.
Definition at line 551 of file common.py.
_get_colors_mapped()
pandas.tests.plotting.common._get_colors_mapped (series, colors) protected
Definition at line 130 of file common.py.
_unpack_cycler()
pandas.tests.plotting.common._unpack_cycler (rcParams, field = "color") protected
Auxiliary function for correctly unpacking cycler after MPL >= 1.5
Definition at line 481 of file common.py.
get_x_axis()
pandas.tests.plotting.common.get_x_axis (ax)
Definition at line 488 of file common.py.
get_y_axis()
pandas.tests.plotting.common.get_y_axis (ax)
Definition at line 492 of file common.py.