Code Cloning Analysis: sklearn.linear_model._omp Namespace Reference
sklearn.linear_model._omp Namespace Reference
Classes
class OrthogonalMatchingPursuit
class OrthogonalMatchingPursuitCV
Functions
_cholesky_omp (X, y, n_nonzero_coefs, tol=None, copy_X=True, return_path=False)
_gram_omp (Gram, Xy, n_nonzero_coefs, tol_0=None, tol=None, copy_Gram=True, copy_Xy=True, return_path=False)
orthogonal_mp (X, y, *, n_nonzero_coefs=None, tol=None, precompute=False, copy_X=True, return_path=False, return_n_iter=False)
orthogonal_mp_gram (Gram, Xy, *, n_nonzero_coefs=None, tol=None, norms_squared=None, copy_Gram=True, copy_Xy=True, return_path=False, return_n_iter=False)
_omp_path_residues (X_train, y_train, X_test, y_test, copy=True, fit_intercept=True, max_iter=100)
Variables
tuple premature
Detailed Description
Orthogonal matching pursuit algorithms
Function Documentation
_cholesky_omp()
sklearn.linear_model._omp._cholesky_omp (X, y, n_nonzero_coefs, tol = None, copy_X = True, return_path = False) protected
Orthogonal Matching Pursuit step using the Cholesky decomposition.
Parameters
----------
X : ndarray of shape (n_samples, n_features)
    Input dictionary. Columns are assumed to have unit norm.
y : ndarray of shape (n_samples,)
    Input targets.
n_nonzero_coefs : int
    Targeted number of non-zero elements.
tol : float, default=None
    Targeted squared error, if not None overrides n_nonzero_coefs.
copy_X : bool, default=True
    Whether the design matrix X must be copied by the algorithm. A false
    value is only helpful if X is already Fortran-ordered, otherwise a
    copy is made anyway.
return_path : bool, default=False
    Whether to return every value of the nonzero coefficients along the
    forward path. Useful for cross-validation.
Returns
-------
gamma : ndarray of shape (n_nonzero_coefs,)
    Non-zero elements of the solution.
idx : ndarray of shape (n_nonzero_coefs,)
    Indices of the positions of the elements in gamma within the solution
    vector.
coef : ndarray of shape (n_features, n_nonzero_coefs)
    The first k values of column k correspond to the coefficient value
    for the active features at that step. The lower left triangle contains
    garbage. Only returned if ``return_path=True``.
n_active : int
    Number of active features at convergence.
Definition at line 36 of file _omp.py.
Referenced by orthogonal_mp().
_gram_omp()
sklearn.linear_model._omp._gram_omp (Gram, Xy, n_nonzero_coefs, tol_0 = None, tol = None, copy_Gram = True, copy_Xy = True, return_path = False) protected
Orthogonal Matching Pursuit step on a precomputed Gram matrix.
This function uses the Cholesky decomposition method.
Parameters
----------
Gram : ndarray of shape (n_features, n_features)
    Gram matrix of the input data matrix.
Xy : ndarray of shape (n_features,)
    Input targets.
n_nonzero_coefs : int
    Targeted number of non-zero elements.
tol_0 : float, default=None
    Squared norm of y, required if tol is not None.
tol : float, default=None
    Targeted squared error, if not None overrides n_nonzero_coefs.
copy_Gram : bool, default=True
    Whether the gram matrix must be copied by the algorithm. A false
    value is only helpful if it is already Fortran-ordered, otherwise a
    copy is made anyway.
copy_Xy : bool, default=True
    Whether the covariance vector Xy must be copied by the algorithm.
    If False, it may be overwritten.
return_path : bool, default=False
    Whether to return every value of the nonzero coefficients along the
    forward path. Useful for cross-validation.
Returns
-------
gamma : ndarray of shape (n_nonzero_coefs,)
    Non-zero elements of the solution.
idx : ndarray of shape (n_nonzero_coefs,)
    Indices of the positions of the elements in gamma within the solution
    vector.
coefs : ndarray of shape (n_features, n_nonzero_coefs)
    The first k values of column k correspond to the coefficient value
    for the active features at that step. The lower left triangle contains
    garbage. Only returned if ``return_path=True``.
n_active : int
    Number of active features at convergence.
Definition at line 152 of file _omp.py.
Referenced by orthogonal_mp_gram().
_omp_path_residues()
sklearn.linear_model._omp._omp_path_residues (X_train, y_train, X_test, y_test, copy = True, fit_intercept = True, max_iter = 100) protected
Compute the residues on left-out data for a full LARS path.
Parameters
----------
X_train : ndarray of shape (n_samples, n_features)
    The data to fit the LARS on.
y_train : ndarray of shape (n_samples)
    The target variable to fit LARS on.
X_test : ndarray of shape (n_samples, n_features)
    The data to compute the residues on.
y_test : ndarray of shape (n_samples)
    The target variable to compute the residues on.
copy : bool, default=True
    Whether X_train, X_test, y_train and y_test should be copied.  If
    False, they may be overwritten.
fit_intercept : bool, default=True
    Whether to calculate the intercept for this model. If set
    to false, no intercept will be used in calculations
    (i.e. data is expected to be centered).
max_iter : int, default=100
    Maximum numbers of iterations to perform, therefore maximum features
    to include. 100 by default.
Returns
-------
residues : ndarray of shape (n_samples, max_features)
    Residues of the prediction on the test data.
Definition at line 819 of file _omp.py.
References orthogonal_mp().
orthogonal_mp()
sklearn.linear_model._omp.orthogonal_mp (X, y, * , n_nonzero_coefs = None, tol = None, precompute = False, copy_X = True, return_path = False, return_n_iter = False)
Orthogonal Matching Pursuit (OMP).
Solves n_targets Orthogonal Matching Pursuit problems.
An instance of the problem has the form:
When parametrized by the number of non-zero coefficients using
`n_nonzero_coefs`:
argmin ||y - X\gamma||^2 subject to ||\gamma||_0 <= n_{nonzero coefs}
When parametrized by error using the parameter `tol`:
argmin ||\gamma||_0 subject to ||y - X\gamma||^2 <= tol
Read more in the :ref:`User Guide <omp>`.
Parameters
----------
X : array-like of shape (n_samples, n_features)
    Input data. Columns are assumed to have unit norm.
y : ndarray of shape (n_samples,) or (n_samples, n_targets)
    Input targets.
n_nonzero_coefs : int, default=None
    Desired number of non-zero entries in the solution. If None (by
    default) this value is set to 10% of n_features.
tol : float, default=None
    Maximum squared norm of the residual. If not None, overrides n_nonzero_coefs.
precompute : 'auto' or bool, default=False
    Whether to perform precomputations. Improves performance when n_targets
    or n_samples is very large.
copy_X : bool, default=True
    Whether the design matrix X must be copied by the algorithm. A false
    value is only helpful if X is already Fortran-ordered, otherwise a
    copy is made anyway.
return_path : bool, default=False
    Whether to return every value of the nonzero coefficients along the
    forward path. Useful for cross-validation.
return_n_iter : bool, default=False
    Whether or not to return the number of iterations.
Returns
-------
coef : ndarray of shape (n_features,) or (n_features, n_targets)
    Coefficients of the OMP solution. If `return_path=True`, this contains
    the whole coefficient path. In this case its shape is
    (n_features, n_features) or (n_features, n_targets, n_features) and
    iterating over the last axis generates coefficients in increasing order
    of active features.
n_iters : array-like or int
    Number of active features across every target. Returned only if
    `return_n_iter` is set to True.
See Also
--------
OrthogonalMatchingPursuit : Orthogonal Matching Pursuit model.
orthogonal_mp_gram : Solve OMP problems using Gram matrix and the product X.T * y.
lars_path : Compute Least Angle Regression or Lasso path using LARS algorithm.
sklearn.decomposition.sparse_encode : Sparse coding.
Notes
-----
Orthogonal matching pursuit was introduced in S. Mallat, Z. Zhang,
Matching pursuits with time-frequency dictionaries, IEEE Transactions on
Signal Processing, Vol. 41, No. 12. (December 1993), pp. 3397-3415.
(https://www.di.ens.fr/~mallat/papiers/MallatPursuit93.pdf)
This implementation is based on Rubinstein, R., Zibulevsky, M. and Elad,
M., Efficient Implementation of the K-SVD Algorithm using Batch Orthogonal
Matching Pursuit Technical Report - CS Technion, April 2008.
https://www.cs.technion.ac.il/~ronrubin/Publications/KSVD-OMP-v2.pdf
Examples
--------
>>> from sklearn.datasets import make_regression
>>> from sklearn.linear_model import orthogonal_mp
>>> X, y = make_regression(noise=4, random_state=0)
>>> coef = orthogonal_mp(X, y)
>>> coef.shape
(100,)
>>> X[:1,] @ coef
array([-78.68])
Definition at line 303 of file _omp.py.
References _cholesky_omp(), and orthogonal_mp_gram().
Referenced by _omp_path_residues(), and sklearn.linear_model._omp.OrthogonalMatchingPursuit.fit().
orthogonal_mp_gram()
sklearn.linear_model._omp.orthogonal_mp_gram (Gram, Xy, * , n_nonzero_coefs = None, tol = None, norms_squared = None, copy_Gram = True, copy_Xy = True, return_path = False, return_n_iter = False)
Gram Orthogonal Matching Pursuit (OMP).
Solves n_targets Orthogonal Matching Pursuit problems using only
the Gram matrix X.T * X and the product X.T * y.
Read more in the :ref:`User Guide <omp>`.
Parameters
----------
Gram : array-like of shape (n_features, n_features)
    Gram matrix of the input data: `X.T * X`.
Xy : array-like of shape (n_features,) or (n_features, n_targets)
    Input targets multiplied by `X`: `X.T * y`.
n_nonzero_coefs : int, default=None
    Desired number of non-zero entries in the solution. If `None` (by
    default) this value is set to 10% of n_features.
tol : float, default=None
    Maximum squared norm of the residual. If not `None`,
    overrides `n_nonzero_coefs`.
norms_squared : array-like of shape (n_targets,), default=None
    Squared L2 norms of the lines of `y`. Required if `tol` is not None.
copy_Gram : bool, default=True
    Whether the gram matrix must be copied by the algorithm. A `False`
    value is only helpful if it is already Fortran-ordered, otherwise a
    copy is made anyway.
copy_Xy : bool, default=True
    Whether the covariance vector `Xy` must be copied by the algorithm.
    If `False`, it may be overwritten.
return_path : bool, default=False
    Whether to return every value of the nonzero coefficients along the
    forward path. Useful for cross-validation.
return_n_iter : bool, default=False
    Whether or not to return the number of iterations.
Returns
-------
coef : ndarray of shape (n_features,) or (n_features, n_targets)
    Coefficients of the OMP solution. If `return_path=True`, this contains
    the whole coefficient path. In this case its shape is
    `(n_features, n_features)` or `(n_features, n_targets, n_features)` and
    iterating over the last axis yields coefficients in increasing order
    of active features.
n_iters : list or int
    Number of active features across every target. Returned only if
    `return_n_iter` is set to True.
See Also
--------
OrthogonalMatchingPursuit : Orthogonal Matching Pursuit model (OMP).
orthogonal_mp : Solves n_targets Orthogonal Matching Pursuit problems.
lars_path : Compute Least Angle Regression or Lasso path using
    LARS algorithm.
sklearn.decomposition.sparse_encode : Generic sparse coding.
    Each column of the result is the solution to a Lasso problem.
Notes
-----
Orthogonal matching pursuit was introduced in G. Mallat, Z. Zhang,
Matching pursuits with time-frequency dictionaries, IEEE Transactions on
Signal Processing, Vol. 41, No. 12. (December 1993), pp. 3397-3415.
(https://www.di.ens.fr/~mallat/papiers/MallatPursuit93.pdf)
This implementation is based on Rubinstein, R., Zibulevsky, M. and Elad,
M., Efficient Implementation of the K-SVD Algorithm using Batch Orthogonal
Matching Pursuit Technical Report - CS Technion, April 2008.
https://www.cs.technion.ac.il/~ronrubin/Publications/KSVD-OMP-v2.pdf
Examples
--------
>>> from sklearn.datasets import make_regression
>>> from sklearn.linear_model import orthogonal_mp_gram
>>> X, y = make_regression(noise=4, random_state=0)
>>> coef = orthogonal_mp_gram(X.T @ X, X.T @ y)
>>> coef.shape
(100,)
>>> X[:1,] @ coef
array([-78.68])
Definition at line 481 of file _omp.py.
References _gram_omp().
Referenced by sklearn.linear_model._omp.OrthogonalMatchingPursuit.fit(), and orthogonal_mp().
Variable Documentation
premature
tuple sklearn.linear_model._omp.premature
Initial value:
=  (
    "Orthogonal matching pursuit ended prematurely due to linear"
    " dependence in the dictionary. The requested precision might"
    " not have been met."
)
Definition at line 29 of file _omp.py.