Code Cloning Analysis: pandas.core.array_algos.masked_reductions Namespace Reference
pandas.core.array_algos.masked_reductions Namespace Reference
Functions
_reductions (Callable func, np.ndarray values, npt.NDArray[np.bool_] mask, *, bool skipna=True, int min_count=0, AxisInt|None axis=None, **kwargs)
sum (np.ndarray values, npt.NDArray[np.bool_] mask, *, bool skipna=True, int min_count=0, AxisInt|None axis=None)
prod (np.ndarray values, npt.NDArray[np.bool_] mask, *, bool skipna=True, int min_count=0, AxisInt|None axis=None)
_minmax (Callable func, np.ndarray values, npt.NDArray[np.bool_] mask, *, bool skipna=True, AxisInt|None axis=None)
min (np.ndarray values, npt.NDArray[np.bool_] mask, *, bool skipna=True, AxisInt|None axis=None)
max (np.ndarray values, npt.NDArray[np.bool_] mask, *, bool skipna=True, AxisInt|None axis=None)
mean (np.ndarray values, npt.NDArray[np.bool_] mask, *, bool skipna=True, AxisInt|None axis=None)
var (np.ndarray values, npt.NDArray[np.bool_] mask, *, bool skipna=True, AxisInt|None axis=None, int ddof=1)
std (np.ndarray values, npt.NDArray[np.bool_] mask, *, bool skipna=True, AxisInt|None axis=None, int ddof=1)
Detailed Description
masked_reductions.py is for reduction algorithms using a mask-based approach
for missing values.
Function Documentation
_minmax()
pandas.core.array_algos.masked_reductions._minmax (Callable func, np.ndarray values, npt.NDArray[np.bool_] mask, * , bool skipna = True, AxisInt | None axis = None) protected
Reduction for 1D masked array.
Parameters
----------
func : np.min or np.max
values : np.ndarray
    Numpy array with the values (can be of any dtype that support the
    operation).
mask : np.ndarray[bool]
    Boolean numpy array (True values indicate missing values).
skipna : bool, default True
    Whether to skip NA.
axis : int, optional, default None
Definition at line 98 of file masked_reductions.py.
References _minmax(), and _reductions().
Referenced by _minmax().
_reductions()
pandas.core.array_algos.masked_reductions._reductions (Callable func, np.ndarray values, npt.NDArray[np.bool_] mask, * , bool skipna = True, int min_count = 0, AxisInt | None axis = None, ** kwargs) protected
Sum, mean or product for 1D masked array.
Parameters
----------
func : np.sum or np.prod
values : np.ndarray
    Numpy array with the values (can be of any dtype that support the
    operation).
mask : np.ndarray[bool]
    Boolean numpy array (True values indicate missing values).
skipna : bool, default True
    Whether to skip NA.
min_count : int, default 0
    The required number of valid values to perform the operation. If fewer than
    ``min_count`` non-NA values are present the result will be NA.
axis : int, optional, default None
Definition at line 26 of file masked_reductions.py.
References _reductions().
Referenced by _minmax(), and _reductions().
max()
pandas.core.array_algos.masked_reductions.max (np.ndarray values, npt.NDArray[np.bool_] mask, * , bool skipna = True, AxisInt | None axis = None)
Definition at line 146 of file masked_reductions.py.
mean()
pandas.core.array_algos.masked_reductions.mean (np.ndarray values, npt.NDArray[np.bool_] mask, * , bool skipna = True, AxisInt | None axis = None)
Definition at line 156 of file masked_reductions.py.
min()
pandas.core.array_algos.masked_reductions.min (np.ndarray values, npt.NDArray[np.bool_] mask, * , bool skipna = True, AxisInt | None axis = None)
Definition at line 136 of file masked_reductions.py.
prod()
pandas.core.array_algos.masked_reductions.prod (np.ndarray values, npt.NDArray[np.bool_] mask, * , bool skipna = True, int min_count = 0, AxisInt | None axis = None)
Definition at line 85 of file masked_reductions.py.
std()
pandas.core.array_algos.masked_reductions.std (np.ndarray values, npt.NDArray[np.bool_] mask, * , bool skipna = True, AxisInt | None axis = None, int ddof = 1)
Definition at line 186 of file masked_reductions.py.
sum()
pandas.core.array_algos.masked_reductions.sum (np.ndarray values, npt.NDArray[np.bool_] mask, * , bool skipna = True, int min_count = 0, AxisInt | None axis = None)
Definition at line 72 of file masked_reductions.py.
var()
pandas.core.array_algos.masked_reductions.var (np.ndarray values, npt.NDArray[np.bool_] mask, * , bool skipna = True, AxisInt | None axis = None, int ddof = 1)
Definition at line 168 of file masked_reductions.py.