Code Cloning Analysis: pip._vendor.pyparsing.util.__config_flags Class Reference
pip._vendor.pyparsing.util.__config_flags Class Reference
Static Public Attributes
enable = classmethod(lambda cls, name: cls._set(name, True))
disable = classmethod(lambda cls, name: cls._set(name, False))
Protected Member Functions
_set (cls, dname, value)
Static Protected Attributes
list _all_names = []
list _fixed_names = []
str _type_desc = "configuration"
Detailed Description
Internal class for defining compatibility and debugging flags
Definition at line 14 of file util.py.
Member Function Documentation
_set()
pip._vendor.pyparsing.util.__config_flags._set (cls, dname, value) protected
Definition at line 22 of file util.py.
Member Data Documentation
_all_names
list pip._vendor.pyparsing.util.__config_flags._all_names = [] static protected
Definition at line 17 of file util.py.
Referenced by pyparsing.results.ParseResults.clear(), pyparsing.results.ParseResults.copy(), and pyparsing.results.ParseResults.pprint().
_fixed_names
list pip._vendor.pyparsing.util.__config_flags._fixed_names = [] static protected
Definition at line 18 of file util.py.
_type_desc
str pip._vendor.pyparsing.util.__config_flags._type_desc = "configuration" static protected
Definition at line 19 of file util.py.
disable
pip._vendor.pyparsing.util.__config_flags.disable = classmethod(lambda cls, name: cls._set(name, False)) static
Definition at line 36 of file util.py.
Referenced by pip._vendor.rich.progress.Progress.refresh(), pip._vendor.rich.progress.Progress.start(), and matplotlib.backend_tools.ToolToggleBase.trigger().
enable
pip._vendor.pyparsing.util.__config_flags.enable = classmethod(lambda cls, name: cls._set(name, True)) static
Definition at line 35 of file util.py.
Referenced by matplotlib.backend_tools.ToolToggleBase.trigger().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pip/_vendor/pyparsing/util.py