Code Cloning Analysis: fontTools.qu2cu.qu2cu Namespace Reference
fontTools.qu2cu.qu2cu Namespace Reference
Functions
cubic_farthest_fit_inside (p0, p1, p2, p3, tolerance)
elevate_quadratic (p0, p1, p2)
merge_curves (curves, start, n)
add_implicit_on_curves (p)
List[Tuple[Point,...]] quadratic_to_curves (List[List[Point]] quads, float max_err=0.5, bool all_cubic=False)
spline_to_curves (q, costs, tolerance=0.5, all_cubic=False)
main ()
Variables
COMPILED = cython.compiled
list __all__ = ["quadratic_to_curves"]
Point = Union[Tuple[float, float], complex]
Solution = namedtuple("Solution", ["num_points", "error", "start_index", "is_cubic"])
Function Documentation
add_implicit_on_curves()
fontTools.qu2cu.qu2cu.add_implicit_on_curves (p)
Definition at line 162 of file qu2cu.py.
cubic_farthest_fit_inside()
fontTools.qu2cu.qu2cu.cubic_farthest_fit_inside (p0, p1, p2, p3, tolerance)
Check if a cubic Bezier lies within a given distance of the origin.
"Origin" means *the* origin (0,0), not the start of the curve. Note that no
checks are made on the start and end positions of the curve; this function
only checks the inside of the curve.
Args:
    p0 (complex): Start point of curve.
    p1 (complex): First handle of curve.
    p2 (complex): Second handle of curve.
    p3 (complex): End point of curve.
    tolerance (double): Distance from origin.
Returns:
    bool: True if the cubic Bezier ``p`` entirely lies within a distance
    ``tolerance`` of the origin, False otherwise.
Definition at line 50 of file qu2cu.py.
References cubic_farthest_fit_inside().
Referenced by cubic_farthest_fit_inside(), and spline_to_curves().
elevate_quadratic()
fontTools.qu2cu.qu2cu.elevate_quadratic (p0, p1, p2)
Given a quadratic bezier curve, return its degree-elevated cubic.
Definition at line 88 of file qu2cu.py.
Referenced by spline_to_curves().
main()
fontTools.qu2cu.qu2cu.main ()
Definition at line 386 of file qu2cu.py.
merge_curves()
fontTools.qu2cu.qu2cu.merge_curves (curves, start, n)
Give a cubic-Bezier spline, reconstruct one cubic-Bezier
that has the same endpoints and tangents and approxmates
the spline.
Definition at line 115 of file qu2cu.py.
Referenced by spline_to_curves().
quadratic_to_curves()
List[Tuple[Point, ...]] fontTools.qu2cu.qu2cu.quadratic_to_curves (List[List[Point]] quads, float max_err = 0.5, bool all_cubic = False)
Converts a connecting list of quadratic splines to a list of quadratic
and cubic curves.
A quadratic spline is specified as a list of points.  Either each point is
a 2-tuple of X,Y coordinates, or each point is a complex number with
real/imaginary components representing X,Y coordinates.
The first and last points are on-curve points and the rest are off-curve
points, with an implied on-curve point in the middle between every two
consequtive off-curve points.
Returns:
    The output is a list of tuples of points. Points are represented
    in the same format as the input, either as 2-tuples or complex numbers.
    Each tuple is either of length three, for a quadratic curve, or four,
    for a cubic curve.  Each curve's last point is the same as the next
    curve's first point.
Args:
    quads: quadratic splines
    max_err: absolute error tolerance; defaults to 0.5
    all_cubic: if True, only cubic curves are generated; defaults to False
Definition at line 182 of file qu2cu.py.
References spline_to_curves().
Referenced by spline_to_curves().
spline_to_curves()
fontTools.qu2cu.qu2cu.spline_to_curves (q, costs, tolerance = 0.5, all_cubic = False)
q: quadratic spline with alternating on-curve / off-curve points.
costs: cumulative list of encoding cost of q in terms of number of
  points that need to be encoded.  Implied on-curve points do not
  contribute to the cost. If all points need to be encoded, then
  costs will be range(1, len(q)+1).
Definition at line 265 of file qu2cu.py.
References cubic_farthest_fit_inside(), elevate_quadratic(), merge_curves(), and quadratic_to_curves().
Referenced by quadratic_to_curves().
Variable Documentation
__all__
list fontTools.qu2cu.qu2cu.__all__ = ["quadratic_to_curves"] private
Definition at line 36 of file qu2cu.py.
COMPILED
fontTools.qu2cu.qu2cu.COMPILED = cython.compiled
Definition at line 24 of file qu2cu.py.
Point
fontTools.qu2cu.qu2cu.Point = Union[Tuple[float, float], complex]
Definition at line 175 of file qu2cu.py.
Solution
fontTools.qu2cu.qu2cu.Solution = namedtuple("Solution", ["num_points", "error", "start_index", "is_cubic"])
Definition at line 239 of file qu2cu.py.