Code Cloning Analysis: matplotlib.testing.jpl_units.UnitDblFormatter.UnitDblFormatter Class Reference
matplotlib.testing.jpl_units.UnitDblFormatter.UnitDblFormatter Class Reference
Public Member Functions
__call__ (self, x, pos=None)
format_data_short (self, value)
format_data (self, value)
Public Member Functions inherited from matplotlib.ticker.ScalarFormatter
__init__ (self, useOffset=None, useMathText=None, useLocale=None, *, usetex=None)
get_usetex (self)
set_usetex (self, val)
get_useOffset (self)
set_useOffset (self, val)
get_useLocale (self)
set_useLocale (self, val)
get_useMathText (self)
set_useMathText (self, val)
__call__ (self, x, pos=None)
set_scientific (self, b)
set_powerlimits (self, lims)
get_offset (self)
set_locs (self, locs)
Public Member Functions inherited from matplotlib.ticker.Formatter
__call__ (self, x, pos=None)
format_ticks (self, values)
Public Member Functions inherited from matplotlib.ticker.TickHelper
set_axis (self, axis)
create_dummy_axis (self, **kwargs)
Additional Inherited Members
Static Public Member Functions inherited from matplotlib.ticker.Formatter
fix_minus (s)
Public Attributes inherited from matplotlib.ticker.ScalarFormatter
int orderOfMagnitude = 0
str format = ''
int offset = 0
Static Public Attributes inherited from matplotlib.ticker.Formatter
list locs = []
Static Public Attributes inherited from matplotlib.ticker.TickHelper
axis = None
Protected Member Functions inherited from matplotlib.ticker.ScalarFormatter
_format_maybe_minus_and_locale (self, fmt, arg)
_compute_offset (self)
_set_order_of_magnitude (self)
_set_format (self)
Protected Member Functions inherited from matplotlib.ticker.Formatter
_set_locator (self, locator)
Protected Attributes inherited from matplotlib.ticker.ScalarFormatter
_offset_threshold
bool _scientific = True
_powerlimits = mpl.rcParams['axes.formatter.limits']
_usetex = mpl._val_or_rc(val, 'text.usetex')
bool _useOffset = val
_useLocale = mpl.rcParams['axes.formatter.use_locale']
_useMathText = mpl.rcParams['axes.formatter.use_mathtext']
Properties inherited from matplotlib.ticker.ScalarFormatter
usetex = property(fget=get_usetex, fset=set_usetex)
useOffset = property(fget=get_useOffset, fset=set_useOffset)
useLocale = property(fget=get_useLocale, fset=set_useLocale)
useMathText = property(fget=get_useMathText, fset=set_useMathText)
Detailed Description
The formatter for UnitDbl data types.
This allows for formatting with the unit string.
Definition at line 8 of file UnitDblFormatter.py.
Member Function Documentation
__call__()
matplotlib.testing.jpl_units.UnitDblFormatter.UnitDblFormatter.__call__ (self, x, pos = None)
Definition at line 15 of file UnitDblFormatter.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), scipy.interpolate._fitpack2.SphereBivariateSpline.ev(), matplotlib.ticker.Formatter.format_data(), and matplotlib.ticker.LogFormatter.format_data().
format_data()
matplotlib.testing.jpl_units.UnitDblFormatter.UnitDblFormatter.format_data (self, value)
Return the full string representation of the value with the
position unspecified.
Reimplemented from matplotlib.ticker.ScalarFormatter.
Definition at line 26 of file UnitDblFormatter.py.
Referenced by matplotlib.ticker.EngFormatter.__call__(), matplotlib.ticker.Formatter.format_data_short(), matplotlib.ticker.EngFormatter.format_eng(), matplotlib.ticker.EngFormatter.get_offset(), and matplotlib.ticker.ScalarFormatter.get_offset().
format_data_short()
matplotlib.testing.jpl_units.UnitDblFormatter.UnitDblFormatter.format_data_short (self, value)
Return a short string version of the tick value.
Defaults to the position-independent long value.
Reimplemented from matplotlib.ticker.ScalarFormatter.
Definition at line 22 of file UnitDblFormatter.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/testing/jpl_units/UnitDblFormatter.py