Code Cloning Analysis: pandas.tests.indexes.numeric.test_numeric.TestFloatNumericIndex Class Reference
pandas.tests.indexes.numeric.test_numeric.TestFloatNumericIndex Class Reference
Public Member Functions
dtype (self, request)
simple_index (self, dtype)
index (self, request, dtype)
mixed_index (self, dtype)
float_index (self, dtype)
test_repr_roundtrip (self, index)
check_coerce (self, a, b, is_float_index=True)
test_constructor_from_list_no_dtype (self)
test_constructor (self, dtype)
test_constructor_invalid (self)
test_constructor_coerce (self, mixed_index, float_index)
test_constructor_explicit (self, mixed_index, float_index)
test_type_coercion_fail (self, any_int_numpy_dtype)
test_equals_numeric (self)
test_equals_numeric_other_index_type (self, other)
test_lookups_datetimelike_values (self, vals, dtype)
test_doesnt_contain_all_the_things (self)
test_nan_multiple_containment (self)
test_fillna_float64 (self)
test_logical_compat (self, simple_index)
Detailed Description
Definition at line 12 of file test_numeric.py.
Member Function Documentation
check_coerce()
pandas.tests.indexes.numeric.test_numeric.TestFloatNumericIndex.check_coerce (self, a, b, is_float_index = True)
Definition at line 45 of file test_numeric.py.
dtype()
pandas.tests.indexes.numeric.test_numeric.TestFloatNumericIndex.dtype (self, request)
Definition at line 14 of file test_numeric.py.
Referenced by pandas.core.arrays.base.ExtensionScalarOpsMixin._create_method(), scipy.sparse._index.IndexMixin._getcol(), pandas.core.generic.NDFrame._inplace_method(), scipy.sparse._index.IndexMixin._raise_on_1d_array_slice(), pandas.core.strings.object_array.ObjectStringArrayMixin._str_map(), numpy.matrixlib.defmatrix.matrix.H(), numpy.core.records.record.pprint(), pandas.core.frame.DataFrame.quantile(), and pandas.core.generic.NDFrame.rank().
float_index()
pandas.tests.indexes.numeric.test_numeric.TestFloatNumericIndex.float_index (self, dtype)
Definition at line 39 of file test_numeric.py.
index()
pandas.tests.indexes.numeric.test_numeric.TestFloatNumericIndex.index (self, request, dtype)
Definition at line 31 of file test_numeric.py.
mixed_index()
pandas.tests.indexes.numeric.test_numeric.TestFloatNumericIndex.mixed_index (self, dtype)
Definition at line 35 of file test_numeric.py.
simple_index()
pandas.tests.indexes.numeric.test_numeric.TestFloatNumericIndex.simple_index (self, dtype)
Definition at line 18 of file test_numeric.py.
test_constructor()
pandas.tests.indexes.numeric.test_numeric.TestFloatNumericIndex.test_constructor (self, dtype)
Definition at line 57 of file test_numeric.py.
test_constructor_coerce()
pandas.tests.indexes.numeric.test_numeric.TestFloatNumericIndex.test_constructor_coerce (self, mixed_index, float_index)
Definition at line 107 of file test_numeric.py.
test_constructor_explicit()
pandas.tests.indexes.numeric.test_numeric.TestFloatNumericIndex.test_constructor_explicit (self, mixed_index, float_index)
Definition at line 115 of file test_numeric.py.
test_constructor_from_list_no_dtype()
pandas.tests.indexes.numeric.test_numeric.TestFloatNumericIndex.test_constructor_from_list_no_dtype (self)
Definition at line 53 of file test_numeric.py.
test_constructor_invalid()
pandas.tests.indexes.numeric.test_numeric.TestFloatNumericIndex.test_constructor_invalid (self)
Definition at line 96 of file test_numeric.py.
test_doesnt_contain_all_the_things()
pandas.tests.indexes.numeric.test_numeric.TestFloatNumericIndex.test_doesnt_contain_all_the_things (self)
Definition at line 197 of file test_numeric.py.
test_equals_numeric()
pandas.tests.indexes.numeric.test_numeric.TestFloatNumericIndex.test_equals_numeric (self)
Definition at line 130 of file test_numeric.py.
test_equals_numeric_other_index_type()
pandas.tests.indexes.numeric.test_numeric.TestFloatNumericIndex.test_equals_numeric_other_index_type (self, other)
Definition at line 155 of file test_numeric.py.
test_fillna_float64()
pandas.tests.indexes.numeric.test_numeric.TestFloatNumericIndex.test_fillna_float64 (self)
Definition at line 214 of file test_numeric.py.
test_logical_compat()
pandas.tests.indexes.numeric.test_numeric.TestFloatNumericIndex.test_logical_compat (self, simple_index)
Definition at line 230 of file test_numeric.py.
test_lookups_datetimelike_values()
pandas.tests.indexes.numeric.test_numeric.TestFloatNumericIndex.test_lookups_datetimelike_values (self, vals, dtype)
Definition at line 167 of file test_numeric.py.
test_nan_multiple_containment()
pandas.tests.indexes.numeric.test_numeric.TestFloatNumericIndex.test_nan_multiple_containment (self)
Definition at line 203 of file test_numeric.py.
test_repr_roundtrip()
pandas.tests.indexes.numeric.test_numeric.TestFloatNumericIndex.test_repr_roundtrip (self, index)
Definition at line 42 of file test_numeric.py.
test_type_coercion_fail()
pandas.tests.indexes.numeric.test_numeric.TestFloatNumericIndex.test_type_coercion_fail (self, any_int_numpy_dtype)
Definition at line 124 of file test_numeric.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/tests/indexes/numeric/test_numeric.py