Code Cloning Analysis: scipy.integrate._quad_vec Namespace Reference
scipy.integrate._quad_vec Namespace Reference
Classes
class _Bunch
class DoubleInfiniteFunc
class LRUDict
class SemiInfiniteFunc
Functions
_max_norm (x)
_get_sizeof (obj)
quad_vec (f, a, b, epsabs=1e-200, epsrel=1e-8, norm='2', cache_size=100e6, limit=10000, workers=1, points=None, quadrature=None, full_output=False, *, args=())
_subdivide_interval (args)
_quadrature_trapezoid (x1, x2, f, norm_func)
_quadrature_gk (a, b, f, norm_func, x, w, v)
_quadrature_gk21 (a, b, f, norm_func)
_quadrature_gk15 (a, b, f, norm_func)
Variables
cache_size
num_eval
Function Documentation
_get_sizeof()
scipy.integrate._quad_vec._get_sizeof (obj) protected
Definition at line 84 of file _quad_vec.py.
_max_norm()
scipy.integrate._quad_vec._max_norm (x) protected
Definition at line 80 of file _quad_vec.py.
_quadrature_gk()
scipy.integrate._quad_vec._quadrature_gk (a, b, f, norm_func, x, w, v) protected
Generic Gauss-Kronrod quadrature
Definition at line 484 of file _quad_vec.py.
Referenced by _quadrature_gk15(), and _quadrature_gk21().
_quadrature_gk15()
scipy.integrate._quad_vec._quadrature_gk15 (a, b, f, norm_func) protected
Gauss-Kronrod 15 quadrature with error estimate
Definition at line 603 of file _quad_vec.py.
References _quadrature_gk().
_quadrature_gk21()
scipy.integrate._quad_vec._quadrature_gk21 (a, b, f, norm_func) protected
Gauss-Kronrod 21 quadrature with error estimate
Definition at line 535 of file _quad_vec.py.
References _quadrature_gk().
_quadrature_trapezoid()
scipy.integrate._quad_vec._quadrature_trapezoid (x1, x2, f, norm_func) protected
Composite trapezoid quadrature
Definition at line 460 of file _quad_vec.py.
_subdivide_interval()
scipy.integrate._quad_vec._subdivide_interval (args) protected
Definition at line 431 of file _quad_vec.py.
quad_vec()
scipy.integrate._quad_vec.quad_vec (f, a, b, epsabs = 1e-200, epsrel = 1e-8, norm = '2', cache_size = 100e6, limit = 10000, workers = 1, points = None, quadrature = None, full_output = False, * , args = ())
Adaptive integration of a vector-valued function.
Parameters
----------
f : callable
Vector-valued function f(x) to integrate.
a : float
Initial point.
b : float
Final point.
epsabs : float, optional
Absolute tolerance.
epsrel : float, optional
Relative tolerance.
norm : {'max', '2'}, optional
Vector norm to use for error estimation.
cache_size : int, optional
Number of bytes to use for memoization.
limit : float or int, optional
An upper bound on the number of subintervals used in the adaptive
algorithm.
workers : int or map-like callable, optional
If `workers` is an integer, part of the computation is done in
parallel subdivided to this many tasks (using
:class:`python:multiprocessing.pool.Pool`).
Supply `-1` to use all cores available to the Process.
Alternatively, supply a map-like callable, such as
:meth:`python:multiprocessing.pool.Pool.map` for evaluating the
population in parallel.
This evaluation is carried out as ``workers(func, iterable)``.
points : list, optional
List of additional breakpoints.
quadrature : {'gk21', 'gk15', 'trapezoid'}, optional
Quadrature rule to use on subintervals.
Options: 'gk21' (Gauss-Kronrod 21-point rule),
'gk15' (Gauss-Kronrod 15-point rule),
'trapezoid' (composite trapezoid rule).
Default: 'gk21' for finite intervals and 'gk15' for (semi-)infinite
full_output : bool, optional
Return an additional ``info`` dictionary.
args : tuple, optional
Extra arguments to pass to function, if any.
.. versionadded:: 1.8.0
Returns
-------
res : {float, array-like}
Estimate for the result
err : float
Error estimate for the result in the given norm
info : dict
Returned only when ``full_output=True``.
Info dictionary. Is an object with the attributes:
success : bool
Whether integration reached target precision.
status : int
Indicator for convergence, success (0),
failure (1), and failure due to rounding error (2).
neval : int
Number of function evaluations.
intervals : ndarray, shape (num_intervals, 2)
Start and end points of subdivision intervals.
integrals : ndarray, shape (num_intervals, ...)
Integral for each interval.
Note that at most ``cache_size`` values are recorded,
and the array may contains *nan* for missing items.
errors : ndarray, shape (num_intervals,)
Estimated integration error for each interval.
Notes
-----
The algorithm mainly follows the implementation of QUADPACK's
DQAG* algorithms, implementing global error control and adaptive
subdivision.
The algorithm here has some differences to the QUADPACK approach:
Instead of subdividing one interval at a time, the algorithm
subdivides N intervals with largest errors at once. This enables
(partial) parallelization of the integration.
The logic of subdividing "next largest" intervals first is then
not implemented, and we rely on the above extension to avoid
concentrating on "small" intervals only.
The Wynn epsilon table extrapolation is not used (QUADPACK uses it
for infinite intervals). This is because the algorithm here is
supposed to work on vector-valued functions, in an user-specified
norm, and the extension of the epsilon algorithm to this case does
not appear to be widely agreed. For max-norm, using elementwise
Wynn epsilon could be possible, but we do not do this here with
the hope that the epsilon extrapolation is mainly useful in
special cases.
References
----------
[1] R. Piessens, E. de Doncker, QUADPACK (1983).
Examples
--------
We can compute integrations of a vector-valued function:
>>> from scipy.integrate import quad_vec
>>> import numpy as np
>>> import matplotlib.pyplot as plt
>>> alpha = np.linspace(0.0, 2.0, num=30)
>>> f = lambda x: x**alpha
>>> x0, x1 = 0, 2
>>> y, err = quad_vec(f, x0, x1)
>>> plt.plot(alpha, y)
>>> plt.xlabel(r"$\alpha$")
>>> plt.ylabel(r"$\int_{0}^{2} x^\alpha dx$")
>>> plt.show()
Definition at line 104 of file _quad_vec.py.
References quad_vec().
Referenced by quad_vec().
Variable Documentation
cache_size
scipy.integrate._quad_vec.cache_size
Definition at line 480 of file _quad_vec.py.
num_eval
scipy.integrate._quad_vec.num_eval
Definition at line 481 of file _quad_vec.py.