Code Cloning Analysis: sklearn.discriminant_analysis Namespace Reference
sklearn.discriminant_analysis Namespace Reference
Classes
class DiscriminantAnalysisPredictionMixin
class LinearDiscriminantAnalysis
class QuadraticDiscriminantAnalysis
Functions
_cov (X, shrinkage=None, covariance_estimator=None)
_class_means (X, y)
_class_cov (X, y, priors, shrinkage=None, covariance_estimator=None)
Variables
list __all__ = ["LinearDiscriminantAnalysis", "QuadraticDiscriminantAnalysis"]
Detailed Description
Linear and quadratic discriminant analysis.
Function Documentation
_class_cov()
sklearn.discriminant_analysis._class_cov (X, y, priors, shrinkage = None, covariance_estimator = None) protected
Compute weighted within-class covariance matrix.
The per-class covariance are weighted by the class priors.
Parameters
----------
X : array-like of shape (n_samples, n_features)
    Input data.
y : array-like of shape (n_samples,) or (n_samples, n_targets)
    Target values.
priors : array-like of shape (n_classes,)
    Class priors.
shrinkage : 'auto' or float, default=None
    Shrinkage parameter, possible values:
      - None: no shrinkage (default).
      - 'auto': automatic shrinkage using the Ledoit-Wolf lemma.
      - float between 0 and 1: fixed shrinkage parameter.
    Shrinkage parameter is ignored if `covariance_estimator` is not None.
covariance_estimator : estimator, default=None
    If not None, `covariance_estimator` is used to estimate
    the covariance matrices instead of relying the empirical
    covariance estimator (with potential shrinkage).
    The object should have a fit method and a ``covariance_`` attribute
    like the estimators in sklearn.covariance.
    If None, the shrinkage parameter drives the estimate.
    .. versionadded:: 0.24
Returns
-------
cov : array-like of shape (n_features, n_features)
    Weighted within-class covariance matrix
Definition at line 124 of file discriminant_analysis.py.
References _cov().
Referenced by sklearn.discriminant_analysis.LinearDiscriminantAnalysis._solve_eigen(), sklearn.discriminant_analysis.LinearDiscriminantAnalysis._solve_lstsq(), and sklearn.discriminant_analysis.LinearDiscriminantAnalysis._solve_svd().
_class_means()
sklearn.discriminant_analysis._class_means (X, y) protected
Compute class means.
Parameters
----------
X : array-like of shape (n_samples, n_features)
    Input data.
y : array-like of shape (n_samples,) or (n_samples, n_targets)
    Target values.
Returns
-------
means : array-like of shape (n_classes, n_features)
    Class means.
Definition at line 92 of file discriminant_analysis.py.
Referenced by sklearn.discriminant_analysis.LinearDiscriminantAnalysis._solve_eigen(), sklearn.discriminant_analysis.LinearDiscriminantAnalysis._solve_lstsq(), and sklearn.discriminant_analysis.LinearDiscriminantAnalysis._solve_svd().
_cov()
sklearn.discriminant_analysis._cov (X, shrinkage = None, covariance_estimator = None) protected
Estimate covariance matrix (using optional covariance_estimator).
Parameters
----------
X : array-like of shape (n_samples, n_features)
    Input data.
shrinkage : {'empirical', 'auto'} or float, default=None
    Shrinkage parameter, possible values:
      - None or 'empirical': no shrinkage (default).
      - 'auto': automatic shrinkage using the Ledoit-Wolf lemma.
      - float between 0 and 1: fixed shrinkage parameter.
    Shrinkage parameter is ignored if  `covariance_estimator`
    is not None.
covariance_estimator : estimator, default=None
    If not None, `covariance_estimator` is used to estimate
    the covariance matrices instead of relying on the empirical
    covariance estimator (with potential shrinkage).
    The object should have a fit method and a ``covariance_`` attribute
    like the estimators in :mod:`sklearn.covariance``.
    if None the shrinkage parameter drives the estimate.
    .. versionadded:: 0.24
Returns
-------
s : ndarray of shape (n_features, n_features)
    Estimated covariance matrix.
Definition at line 32 of file discriminant_analysis.py.
Referenced by _class_cov(), and sklearn.discriminant_analysis.LinearDiscriminantAnalysis._solve_eigen().
Variable Documentation
__all__
list sklearn.discriminant_analysis.__all__ = ["LinearDiscriminantAnalysis", "QuadraticDiscriminantAnalysis"] private
Definition at line 29 of file discriminant_analysis.py.