Code Cloning Analysis: scipy.optimize._differentiable_functions.VectorFunction Class Reference
scipy.optimize._differentiable_functions.VectorFunction Class Reference
Public Member Functions
__init__ (self, fun, x0, jac, hess, finite_diff_rel_step, finite_diff_jac_sparsity, finite_diff_bounds, sparse_jacobian)
fun (self, x)
jac (self, x)
hess (self, x, v)
Public Attributes
x = np.atleast_1d(x0).astype(float)
n = self.x.size
int nfev = 0
int njev = 0
int nhev = 0
bool f_updated = False
bool J_updated = False
bool H_updated = False
x_diff = np.copy(self.x)
f = fun_wrapped(self.x)
v = np.zeros_like(self.f)
m = self.v.size
J = jac(self.x)
bool sparse_jacobian = True
H = hess(self.x, self.v)
x_prev = None
J_prev = None
Protected Member Functions
_update_v (self, v)
_update_x (self, x)
_update_fun (self)
_update_jac (self)
_update_hess (self)
Protected Attributes
_update_fun_impl = update_fun
_update_jac_impl = update_jac
_update_hess_impl = update_hess
_update_x_impl = update_x
Detailed Description
Vector function and its derivatives.
This class defines a vector function F: R^n->R^m and methods for
computing or approximating its first and second derivatives.
Notes
-----
This class implements a memoization logic. There are methods `fun`,
`jac`, hess` and corresponding attributes `f`, `J` and `H`. The following
things should be considered:
    1. Use only public methods `fun`, `jac` and `hess`.
    2. After one of the methods is called, the corresponding attribute
       will be set. However, a subsequent call with a different argument
       of *any* of the methods may overwrite the attribute.
Definition at line 290 of file _differentiable_functions.py.
Constructor & Destructor Documentation
__init__()
scipy.optimize._differentiable_functions.VectorFunction.__init__ (self, fun, x0, jac, hess, finite_diff_rel_step, finite_diff_jac_sparsity, finite_diff_bounds, sparse_jacobian)
Definition at line 307 of file _differentiable_functions.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
_update_fun()
scipy.optimize._differentiable_functions.VectorFunction._update_fun (self) protected
Definition at line 518 of file _differentiable_functions.py.
_update_hess()
scipy.optimize._differentiable_functions.VectorFunction._update_hess (self) protected
Definition at line 528 of file _differentiable_functions.py.
_update_jac()
scipy.optimize._differentiable_functions.VectorFunction._update_jac (self) protected
Definition at line 523 of file _differentiable_functions.py.
_update_v()
scipy.optimize._differentiable_functions.VectorFunction._update_v (self, v) protected
Definition at line 509 of file _differentiable_functions.py.
_update_x()
scipy.optimize._differentiable_functions.VectorFunction._update_x (self, x) protected
Definition at line 514 of file _differentiable_functions.py.
fun()
scipy.optimize._differentiable_functions.VectorFunction.fun (self, x)
Definition at line 533 of file _differentiable_functions.py.
hess()
scipy.optimize._differentiable_functions.VectorFunction.hess (self, x, v)
Definition at line 543 of file _differentiable_functions.py.
jac()
scipy.optimize._differentiable_functions.VectorFunction.jac (self, x)
Definition at line 538 of file _differentiable_functions.py.
Referenced by scipy.optimize.tests.test_slsqp.TestSLSQP.fprime_ieqcon2(), and scipy.optimize.tests.test_slsqp.TestSLSQP.jac().
Member Data Documentation
_update_fun_impl
scipy.optimize._differentiable_functions.VectorFunction._update_fun_impl = update_fun protected
Definition at line 364 of file _differentiable_functions.py.
_update_hess_impl
scipy.optimize._differentiable_functions.VectorFunction._update_hess_impl = update_hess protected
Definition at line 488 of file _differentiable_functions.py.
_update_jac_impl
scipy.optimize._differentiable_functions.VectorFunction._update_jac_impl = update_jac protected
Definition at line 433 of file _differentiable_functions.py.
_update_x_impl
scipy.optimize._differentiable_functions.VectorFunction._update_x_impl = update_x protected
Definition at line 507 of file _differentiable_functions.py.
f
scipy.optimize._differentiable_functions.VectorFunction.f = fun_wrapped(self.x)
Definition at line 362 of file _differentiable_functions.py.
Referenced by scipy.optimize._zeros_py.TOMS748Solver._callf(), scipy.optimize._shgo_lib._vertex.VertexScalarField.maximiser(), scipy.optimize._shgo_lib._vertex.VertexScalarField.minimiser(), and scipy.optimize._zeros_py.TOMS748Solver.start().
f_updated
bool scipy.optimize._differentiable_functions.VectorFunction.f_updated = False
Definition at line 331 of file _differentiable_functions.py.
H
scipy.optimize._differentiable_functions.VectorFunction.H = hess(self.x, self.v)
Definition at line 437 of file _differentiable_functions.py.
Referenced by scipy.sparse.linalg._interface.LinearOperator._rmatmat(), scipy.sparse.linalg._interface.LinearOperator._rmatvec(), scipy.optimize._hessian_update_strategy.BFGS._update_hessian(), scipy.optimize._hessian_update_strategy.BFGS._update_inverse_hessian(), scipy.optimize._hessian_update_strategy.FullHessianUpdateStrategy.dot(), scipy.optimize._hessian_update_strategy.FullHessianUpdateStrategy.get_matrix(), scipy.optimize._hessian_update_strategy.FullHessianUpdateStrategy.initialize(), and scipy.optimize._hessian_update_strategy.FullHessianUpdateStrategy.update().
H_updated
bool scipy.optimize._differentiable_functions.VectorFunction.H_updated = False
Definition at line 333 of file _differentiable_functions.py.
J
scipy.optimize._differentiable_functions.VectorFunction.J = jac(self.x)
Definition at line 372 of file _differentiable_functions.py.
J_prev
scipy.optimize._differentiable_functions.VectorFunction.J_prev = None
Definition at line 477 of file _differentiable_functions.py.
J_updated
bool scipy.optimize._differentiable_functions.VectorFunction.J_updated = False
Definition at line 332 of file _differentiable_functions.py.
m
scipy.optimize._differentiable_functions.VectorFunction.m = self.v.size
Definition at line 368 of file _differentiable_functions.py.
Referenced by scipy.spatial._kdtree.Rectangle.__init__(), scipy.stats._morestats._ABW.__init__(), scipy.stats._morestats._ABW._recalc(), and scipy.signal._czt.CZT.points().
n
scipy.optimize._differentiable_functions.VectorFunction.n = self.x.size
Definition at line 327 of file _differentiable_functions.py.
Referenced by scipy.signal._czt.CZT.__call__(), scipy.stats._morestats._ABW.__init__(), scipy.stats._morestats._ABW._recalc(), scipy.optimize._hessian_update_strategy.BFGS._update_hessian(), scipy.optimize._hessian_update_strategy.FullHessianUpdateStrategy.initialize(), scipy.stats._kde.gaussian_kde.integrate_kde(), scipy.optimize._shgo.SHGO.iterate_delaunay(), scipy.optimize._shgo.SHGO.iterate_hypercube(), scipy.stats._kde.gaussian_kde.marginal(), scipy.stats._binomtest.BinomTestResult.proportion_ci(), scipy.stats._kde.gaussian_kde.resample(), and scipy.optimize._nonlin.LowRankMatrix.rsolve().
nfev
int scipy.optimize._differentiable_functions.VectorFunction.nfev = 0
Definition at line 328 of file _differentiable_functions.py.
Referenced by scipy.optimize._shgo_lib._vertex.VertexCacheField.compute_sfield(), scipy.optimize._shgo_lib._vertex.VertexCacheField.pproc_fpool_g(), and scipy.optimize._shgo_lib._vertex.VertexCacheField.pproc_fpool_nog().
nhev
int scipy.optimize._differentiable_functions.VectorFunction.nhev = 0
Definition at line 330 of file _differentiable_functions.py.
njev
int scipy.optimize._differentiable_functions.VectorFunction.njev = 0
Definition at line 329 of file _differentiable_functions.py.
sparse_jacobian
bool scipy.optimize._differentiable_functions.VectorFunction.sparse_jacobian = True
Definition at line 382 of file _differentiable_functions.py.
v
scipy.optimize._differentiable_functions.VectorFunction.v = np.zeros_like(self.f)
Definition at line 367 of file _differentiable_functions.py.
x
scipy.optimize._differentiable_functions.VectorFunction.x = np.atleast_1d(x0).astype(float)
Definition at line 326 of file _differentiable_functions.py.
Referenced by scipy.optimize._root_scalar.MemoizeDer.__call__(), scipy.optimize._shgo_lib._vertex.VertexBase.__init__(), scipy.optimize._differentialevolution.DifferentialEvolutionSolver.__next__(), matplotlib.widgets.ToolHandles.closest(), scipy.optimize._root_scalar.MemoizeDer.fprime(), scipy.optimize._root_scalar.MemoizeDer.fprime2(), scipy.optimize._differentialevolution.DifferentialEvolutionSolver.solve(), and scipy.spatial.tests.test_kdtree._Test_sorted_query_ball_point.test_return_sorted_None().
x_diff
scipy.optimize._differentiable_functions.VectorFunction.x_diff = np.copy(self.x)
Definition at line 344 of file _differentiable_functions.py.
x_prev
scipy.optimize._differentiable_functions.VectorFunction.x_prev = None
Definition at line 476 of file _differentiable_functions.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/optimize/_differentiable_functions.py