Code Cloning Analysis: numpy.testing.tests.test_utils._GenericTest Class Reference
numpy.testing.tests.test_utils._GenericTest Class Reference
Public Member Functions
test_array_rank1_eq (self)
test_array_rank1_noteq (self)
test_array_rank2_eq (self)
test_array_diffshape (self)
test_objarray (self)
test_array_likes (self)
Protected Member Functions
_test_equal (self, a, b)
_test_not_equal (self, a, b)
Detailed Description
Definition at line 19 of file test_utils.py.
Member Function Documentation
_test_equal()
numpy.testing.tests.test_utils._GenericTest._test_equal (self, a, b) protected
Definition at line 21 of file test_utils.py.
Referenced by test_array_rank1_eq(), test_array_rank2_eq(), numpy.testing.tests.test_utils.TestArrayEqual.test_array_vs_scalar_is_equal(), numpy.testing.tests.test_utils.TestArrayEqual.test_generic_rank1(), numpy.testing.tests.test_utils.TestArrayEqual.test_generic_rank3(), numpy.testing.tests.test_utils.TestArrayEqual.test_nan_array(), test_objarray(), numpy.testing.tests.test_utils.TestArrayEqual.test_recarrays(), and numpy.testing.tests.test_utils.TestArrayEqual.test_string_arrays().
_test_not_equal()
numpy.testing.tests.test_utils._GenericTest._test_not_equal (self, a, b) protected
Definition at line 24 of file test_utils.py.
Referenced by test_array_diffshape(), test_array_rank1_noteq(), numpy.testing.tests.test_utils.TestArrayEqual.test_array_vs_scalar_not_equal(), numpy.testing.tests.test_utils.TestArrayEqual.test_generic_rank1(), numpy.testing.tests.test_utils.TestArrayEqual.test_generic_rank3(), numpy.testing.tests.test_utils.TestArrayEqual.test_nan_array(), numpy.testing.tests.test_utils.TestArrayEqual.test_recarrays(), and numpy.testing.tests.test_utils.TestArrayEqual.test_string_arrays().
test_array_diffshape()
numpy.testing.tests.test_utils._GenericTest.test_array_diffshape (self)
Test two arrays with different shapes are found not equal.
Definition at line 49 of file test_utils.py.
References _test_not_equal().
test_array_likes()
numpy.testing.tests.test_utils._GenericTest.test_array_likes (self)
Definition at line 61 of file test_utils.py.
test_array_rank1_eq()
numpy.testing.tests.test_utils._GenericTest.test_array_rank1_eq (self)
Test two equal array of rank 1 are found equal.
Definition at line 28 of file test_utils.py.
References _test_equal().
test_array_rank1_noteq()
numpy.testing.tests.test_utils._GenericTest.test_array_rank1_noteq (self)
Test two different array of rank 1 are found not equal.
Definition at line 35 of file test_utils.py.
References _test_not_equal().
test_array_rank2_eq()
numpy.testing.tests.test_utils._GenericTest.test_array_rank2_eq (self)
Test two equal array of rank 2 are found equal.
Definition at line 42 of file test_utils.py.
References _test_equal().
test_objarray()
numpy.testing.tests.test_utils._GenericTest.test_objarray (self)
Test object arrays.
Definition at line 56 of file test_utils.py.
References _test_equal().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/testing/tests/test_utils.py