Code Cloning Analysis: scipy.stats._mannwhitneyu._MWU Class Reference
scipy.stats._mannwhitneyu._MWU Class Reference
Public Member Functions
__init__ (self)
pmf (self, k, m, n)
pmf_recursive (self, k, m, n)
pmf_iterative (self, k, m, n)
cdf (self, k, m, n)
sf (self, k, m, n)
Protected Member Functions
_resize_fmnks (self, m, n, k)
_f (self, m, n, k)
Protected Attributes
_fmnks = -np.ones((1, 1, 1))
_recursive = None
Detailed Description
Distribution of MWU statistic under the null hypothesis
Definition at line 19 of file _mannwhitneyu.py.
Constructor & Destructor Documentation
__init__()
scipy.stats._mannwhitneyu._MWU.__init__ (self)
Minimal initializer
Definition at line 23 of file _mannwhitneyu.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params().
Member Function Documentation
_f()
scipy.stats._mannwhitneyu._MWU._f (self, m, n, k) protected
Recursive implementation of function of [3] Theorem 2.5
Definition at line 83 of file _mannwhitneyu.py.
Referenced by sklearn.gaussian_process.tests._mini_sequence_kernel.MiniSeqKernel.diag().
_resize_fmnks()
scipy.stats._mannwhitneyu._MWU._resize_fmnks (self, m, n, k) protected
If necessary, expand the array that remembers PMF values
Definition at line 71 of file _mannwhitneyu.py.
cdf()
scipy.stats._mannwhitneyu._MWU.cdf (self, k, m, n)
Cumulative distribution function
Definition at line 52 of file _mannwhitneyu.py.
Referenced by scipy.stats._multivariate.multivariate_normal_frozen.__init__().
pmf()
scipy.stats._mannwhitneyu._MWU.pmf (self, k, m, n)
Definition at line 28 of file _mannwhitneyu.py.
Referenced by scipy.stats._page_trend_test._PageL.pmf(), and scipy.stats._page_trend_test._PageL.sf().
pmf_iterative()
scipy.stats._mannwhitneyu._MWU.pmf_iterative (self, k, m, n)
Probability mass function, iterative version
Definition at line 44 of file _mannwhitneyu.py.
pmf_recursive()
scipy.stats._mannwhitneyu._MWU.pmf_recursive (self, k, m, n)
Probability mass function, recursive version
Definition at line 35 of file _mannwhitneyu.py.
sf()
scipy.stats._mannwhitneyu._MWU.sf (self, k, m, n)
Survival function
Definition at line 61 of file _mannwhitneyu.py.
Member Data Documentation
_fmnks
scipy.stats._mannwhitneyu._MWU._fmnks = -np.ones((1, 1, 1)) protected
Definition at line 25 of file _mannwhitneyu.py.
_recursive
scipy.stats._mannwhitneyu._MWU._recursive = None protected
Definition at line 26 of file _mannwhitneyu.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/stats/_mannwhitneyu.py