Code Cloning Analysis: axisartist.angle_helper.LocatorBase Class Reference
axisartist.angle_helper.LocatorBase Class Reference
Public Member Functions
__init__ (self, nbins, include_last=True)
set_params (self, nbins=None)
Public Attributes
nbins = nbins
Protected Attributes
_include_last = include_last
Detailed Description
Definition at line 142 of file angle_helper.py.
Constructor & Destructor Documentation
__init__()
axisartist.angle_helper.LocatorBase.__init__ (self, nbins, include_last = True)
Definition at line 143 of file angle_helper.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
set_params()
axisartist.angle_helper.LocatorBase.set_params (self, nbins = None)
Definition at line 147 of file angle_helper.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.theta().
Member Data Documentation
_include_last
axisartist.angle_helper.LocatorBase._include_last = include_last protected
Definition at line 145 of file angle_helper.py.
nbins
axisartist.angle_helper.LocatorBase.nbins = nbins
Definition at line 144 of file angle_helper.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/mpl_toolkits/axisartist/angle_helper.py