Code Cloning Analysis: complete_repo_results Namespace Reference
complete_repo_results Namespace Reference
Functions
get_all_embeddings_from_all_collections (db_path, col_pair)
Gets all embeddings from database given the primary and forked collection names.
get_code_and_embedding_by_id (all_embeddings, file_id)
find_top_k_similar (target_embedding, all_embeddings, target_file_id, target_collection, top_k)
Gets the most cosine similar file from primary (its match)
determine_similarity (results)
Determines the predicted type and binary similarity from score dictionary.
rag_similarity_assessment (target_code, similar_codes, model_name, target_fid, target_col, results_writer, db_name)
Sends a prompt to the LLM to classify clone type and score similarities.
main ()
The entire program that runs through the database and saves prediction results in a CSV.
Variables
int TOP_K = 1
Number of cosine similar files to look at.
str DIR_NAME = "./repo_results"
Output directory name.
str DB_PATH = "./DB_Paths"
Directory name that holds all Milvus databases.
list LLMS
List of LLMs to be used.
list collection_pairs = [["fork_M1", "primary_M1"], ["fork_M2", "primary_M2"], ["fork_M3", "primary_M3"]]
List of collection names.
Function Documentation
determine_similarity()
complete_repo_results.determine_similarity (results)
Determines the predicted type and binary similarity from score dictionary.
Parameters
results Dictionary mapping clone types to similarity scores.
Returns
Tuple of (predicted type, binary similarity: 1 if above threshold, else 0).
Definition at line 97 of file complete_repo_results.py.
Referenced by rag_similarity_assessment().
find_top_k_similar()
complete_repo_results.find_top_k_similar (target_embedding, all_embeddings, target_file_id, target_collection, top_k)
Gets the most cosine similar file from primary (its match)
Parameters
target_embedding Target embedding
all_embeddings All embeddings from collection
target_file_id File ID you're finding the pri similar to
target_collection Collection where the target_file_id is located
top_k Same as the global variable TOP_K
Definition at line 77 of file complete_repo_results.py.
Referenced by main().
get_all_embeddings_from_all_collections()
complete_repo_results.get_all_embeddings_from_all_collections (db_path, col_pair)
Gets all embeddings from database given the primary and forked collection names.
Parameters
db_path Path of database
db_path Collection pair (fork, primary)
Definition at line 42 of file complete_repo_results.py.
Referenced by main().
get_code_and_embedding_by_id()
complete_repo_results.get_code_and_embedding_by_id (all_embeddings, file_id)
Definition at line 70 of file complete_repo_results.py.
main()
complete_repo_results.main ()
The entire program that runs through the database and saves prediction results in a CSV.
Definition at line 170 of file complete_repo_results.py.
References find_top_k_similar(), get_all_embeddings_from_all_collections(), and rag_similarity_assessment().
rag_similarity_assessment()
complete_repo_results.rag_similarity_assessment (target_code, similar_codes, model_name, target_fid, target_col, results_writer, db_name)
Sends a prompt to the LLM to classify clone type and score similarities.
Parameters
code1 First code snippet to evaluate.
code2 Second code snippet to evaluate.
model_name Name of the language model to query.
thr Threshold for determining clone similarity.
Returns
Tuple of (type score dictionary, predicted type, binary similarity).
Definition at line 108 of file complete_repo_results.py.
References determine_similarity().
Referenced by main().
Variable Documentation
collection_pairs
list complete_repo_results.collection_pairs = [["fork_M1", "primary_M1"], ["fork_M2", "primary_M2"], ["fork_M3", "primary_M3"]]
List of collection names.
Definition at line 39 of file complete_repo_results.py.
DB_PATH
str complete_repo_results.DB_PATH = "./DB_Paths"
Directory name that holds all Milvus databases.
Definition at line 29 of file complete_repo_results.py.
DIR_NAME
str complete_repo_results.DIR_NAME = "./repo_results"
Output directory name.
Definition at line 25 of file complete_repo_results.py.
LLMS
list complete_repo_results.LLMS
Initial value:
=  [
    "devstral:24b",
]
List of LLMs to be used.
Definition at line 33 of file complete_repo_results.py.
TOP_K
int complete_repo_results.TOP_K = 1
Number of cosine similar files to look at.
Definition at line 21 of file complete_repo_results.py.