Code Cloning Analysis: fontTools.t1Lib Namespace Reference
fontTools.t1Lib Namespace Reference
Classes
class T1Error
class T1Font
Functions
read (path, onlyHeader=False)
write (path, data, kind="OTHER", dohex=False)
readLWFN (path, onlyHeader=False)
readPFB (path, onlyHeader=False)
readOther (path)
writeLWFN (path, data)
writePFB (path, data)
writeOther (path, data, dohex=False)
isHex (text)
decryptType1 (data)
findEncryptedChunks (data)
deHexString (hexstring)
assertType1 (data)
longToString (long)
stringToLong (s)
Variables
str __author__ = "jvr"
str __version__ = "1.0b3"
int DEBUG = 0
int haveMacSupport = 0
int LWFNCHUNKSIZE = 2000
int HEXLINELENGTH = 80
str EEXECBEGIN = b"currentfile eexec"
EEXECEND = re.compile(b"(0[ \t\r\n]*){512}", flags=re.M)
str EEXECINTERNALEND = b"currentfile closefile"
str EEXECBEGINMARKER = b"%-- eexec start\r"
str EEXECENDMARKER = b"%-- eexec end\r"
_ishexRE = re.compile(b"[0-9A-Fa-f]*$")
_fontType1RE = re.compile(rb"/FontType\s+1\s+def")
font_dictionary_keys = list(_type1_pre_eexec_order)
FontInfo_dictionary_keys = list(_type1_fontinfo_order)
Detailed Description
fontTools.t1Lib.py -- Tools for PostScript Type 1 fonts.
Functions for reading and writing raw Type 1 data:
read(path)
    reads any Type 1 font file, returns the raw data and a type indicator:
    'LWFN', 'PFB' or 'OTHER', depending on the format of the file pointed
    to by 'path'.
    Raises an error when the file does not contain valid Type 1 data.
write(path, data, kind='OTHER', dohex=False)
    writes raw Type 1 data to the file pointed to by 'path'.
    'kind' can be one of 'LWFN', 'PFB' or 'OTHER'; it defaults to 'OTHER'.
    'dohex' is a flag which determines whether the eexec encrypted
    part should be written as hexadecimal or binary, but only if kind
    is 'OTHER'.
Function Documentation
assertType1()
fontTools.t1Lib.assertType1 (data)
Definition at line 550 of file __init__.py.
decryptType1()
fontTools.t1Lib.decryptType1 (data)
Definition at line 492 of file __init__.py.
deHexString()
fontTools.t1Lib.deHexString (hexstring)
Definition at line 541 of file __init__.py.
findEncryptedChunks()
fontTools.t1Lib.findEncryptedChunks (data)
Definition at line 516 of file __init__.py.
isHex()
fontTools.t1Lib.isHex (text)
Definition at line 488 of file __init__.py.
longToString()
fontTools.t1Lib.longToString (long)
Definition at line 567 of file __init__.py.
read()
fontTools.t1Lib.read (path, onlyHeader = False)
reads any Type 1 font file, returns raw data
Definition at line 303 of file __init__.py.
References readLWFN(), readOther(), and readPFB().
readLWFN()
fontTools.t1Lib.readLWFN (path, onlyHeader = False)
reads an LWFN font file, returns raw data
Definition at line 346 of file __init__.py.
Referenced by read().
readOther()
fontTools.t1Lib.readOther (path)
reads any (font) file, returns raw data
Definition at line 401 of file __init__.py.
Referenced by read().
readPFB()
fontTools.t1Lib.readPFB (path, onlyHeader = False)
reads a PFB font file, returns raw data
Definition at line 377 of file __init__.py.
Referenced by read().
stringToLong()
fontTools.t1Lib.stringToLong (s)
Definition at line 574 of file __init__.py.
write()
fontTools.t1Lib.write (path, data, kind = "OTHER", dohex = False)
Definition at line 316 of file __init__.py.
writeLWFN()
fontTools.t1Lib.writeLWFN (path, data)
Definition at line 419 of file __init__.py.
writeOther()
fontTools.t1Lib.writeOther (path, data, dohex = False)
Definition at line 457 of file __init__.py.
writePFB()
fontTools.t1Lib.writePFB (path, data)
Definition at line 443 of file __init__.py.
Variable Documentation
__author__
str fontTools.t1Lib.__author__ = "jvr" private
Definition at line 32 of file __init__.py.
__version__
str fontTools.t1Lib.__version__ = "1.0b3" private
Definition at line 33 of file __init__.py.
_fontType1RE
fontTools.t1Lib._fontType1RE = re.compile(rb"/FontType\s+1\s+def") protected
Definition at line 547 of file __init__.py.
_ishexRE
fontTools.t1Lib._ishexRE = re.compile(b"[0-9A-Fa-f]*$") protected
Definition at line 485 of file __init__.py.
DEBUG
int fontTools.t1Lib.DEBUG = 0
Definition at line 34 of file __init__.py.
EEXECBEGIN
str fontTools.t1Lib.EEXECBEGIN = b"currentfile eexec"
Definition at line 477 of file __init__.py.
EEXECBEGINMARKER
str fontTools.t1Lib.EEXECBEGINMARKER = b"%-- eexec start\r"
Definition at line 482 of file __init__.py.
EEXECEND
fontTools.t1Lib.EEXECEND = re.compile(b"(0[ \t\r\n]*){512}", flags=re.M)
Definition at line 480 of file __init__.py.
EEXECENDMARKER
str fontTools.t1Lib.EEXECENDMARKER = b"%-- eexec end\r"
Definition at line 483 of file __init__.py.
EEXECINTERNALEND
str fontTools.t1Lib.EEXECINTERNALEND = b"currentfile closefile"
Definition at line 481 of file __init__.py.
font_dictionary_keys
fontTools.t1Lib.font_dictionary_keys = list(_type1_pre_eexec_order)
Definition at line 585 of file __init__.py.
FontInfo_dictionary_keys
fontTools.t1Lib.FontInfo_dictionary_keys = list(_type1_fontinfo_order)
Definition at line 590 of file __init__.py.
haveMacSupport
int fontTools.t1Lib.haveMacSupport = 0
Definition at line 43 of file __init__.py.
HEXLINELENGTH
int fontTools.t1Lib.HEXLINELENGTH = 80
Definition at line 343 of file __init__.py.
LWFNCHUNKSIZE
int fontTools.t1Lib.LWFNCHUNKSIZE = 2000
Definition at line 342 of file __init__.py.