Code Cloning Analysis: scipy.optimize.tests.test_optimize.TestLBFGSBBounds Class Reference
scipy.optimize.tests.test_optimize.TestLBFGSBBounds Class Reference
Public Member Functions
setup_method (self)
fun (self, x, p=2.0)
jac (self, x, p=2.0)
fj (self, x, p=2.0)
test_l_bfgs_b_bounds (self)
test_l_bfgs_b_funjac (self)
test_minimize_l_bfgs_b_bounds (self)
test_minimize_l_bfgs_b_incorrect_bounds (self, bounds)
test_minimize_l_bfgs_b_bounds_FD (self)
Public Attributes
tuple bounds = ((1, None), (None, None))
tuple solution = (1, 0)
fun
Detailed Description
Definition at line 1625 of file test_optimize.py.
Member Function Documentation
fj()
scipy.optimize.tests.test_optimize.TestLBFGSBBounds.fj (self, x, p = 2.0)
Definition at line 1636 of file test_optimize.py.
fun()
scipy.optimize.tests.test_optimize.TestLBFGSBBounds.fun (self, x, p = 2.0)
Definition at line 1630 of file test_optimize.py.
jac()
scipy.optimize.tests.test_optimize.TestLBFGSBBounds.jac (self, x, p = 2.0)
Definition at line 1633 of file test_optimize.py.
Referenced by scipy.optimize.tests.test_slsqp.TestSLSQP.fprime_ieqcon2(), and scipy.optimize.tests.test_slsqp.TestSLSQP.jac().
setup_method()
scipy.optimize.tests.test_optimize.TestLBFGSBBounds.setup_method (self)
Definition at line 1626 of file test_optimize.py.
test_l_bfgs_b_bounds()
scipy.optimize.tests.test_optimize.TestLBFGSBBounds.test_l_bfgs_b_bounds (self)
Definition at line 1639 of file test_optimize.py.
test_l_bfgs_b_funjac()
scipy.optimize.tests.test_optimize.TestLBFGSBBounds.test_l_bfgs_b_funjac (self)
Definition at line 1646 of file test_optimize.py.
test_minimize_l_bfgs_b_bounds()
scipy.optimize.tests.test_optimize.TestLBFGSBBounds.test_minimize_l_bfgs_b_bounds (self)
Definition at line 1653 of file test_optimize.py.
test_minimize_l_bfgs_b_bounds_FD()
scipy.optimize.tests.test_optimize.TestLBFGSBBounds.test_minimize_l_bfgs_b_bounds_FD (self)
Definition at line 1670 of file test_optimize.py.
test_minimize_l_bfgs_b_incorrect_bounds()
scipy.optimize.tests.test_optimize.TestLBFGSBBounds.test_minimize_l_bfgs_b_incorrect_bounds (self, bounds)
Definition at line 1665 of file test_optimize.py.
Member Data Documentation
bounds
tuple scipy.optimize.tests.test_optimize.TestLBFGSBBounds.bounds = ((1, None), (None, None))
Definition at line 1627 of file test_optimize.py.
Referenced by sklearn.gaussian_process.kernels.Kernel._check_bounds_params(), and matplotlib.transforms.BboxBase.anchored().
fun
scipy.optimize.tests.test_optimize.TestLBFGSBBounds.fun
Definition at line 1667 of file test_optimize.py.
Referenced by sklearn.decomposition._fastica.FastICA._fit_transform(), scipy.optimize.tests.test_slsqp.TestSLSQP.fprime_ieqcon2(), scipy.optimize.tests.test_optimize.TestOptimizeScalar.fun(), and scipy.optimize.tests.test_slsqp.TestSLSQP.jac().
solution
scipy.optimize.tests.test_optimize.TestLBFGSBBounds.solution = (1, 0)
Definition at line 1628 of file test_optimize.py.
Referenced by scipy.optimize.tests.test_optimize.TestOptimizeScalar.fun().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/optimize/tests/test_optimize.py