Code Cloning Analysis: matplotlib.axes._base._axis_method_wrapper Class Reference
matplotlib.axes._base._axis_method_wrapper Class Reference
Public Member Functions
__init__ (self, attr_name, method_name, *, doc_sub=None)
__set_name__ (self, owner, name)
Public Attributes
attr_name = attr_name
method_name = method_name
Protected Attributes
list _missing_subs = []
Private Attributes
__doc__ = doc
Detailed Description
Helper to generate Axes methods wrapping Axis methods.
After ::
    get_foo = _axis_method_wrapper("xaxis", "get_bar")
(in the body of a class) ``get_foo`` is a method that forwards it arguments
to the ``get_bar`` method of the ``xaxis`` attribute, and gets its
signature and docstring from ``Axis.get_bar``.
The docstring of ``get_foo`` is built by replacing "this Axis" by "the
{attr_name}" (i.e., "the xaxis", "the yaxis") in the wrapped method's
dedented docstring; additional replacements can be given in *doc_sub*.
Definition at line 35 of file _base.py.
Constructor & Destructor Documentation
__init__()
matplotlib.axes._base._axis_method_wrapper.__init__ (self, attr_name, method_name, * , doc_sub = None)
Definition at line 52 of file _base.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__set_name__()
matplotlib.axes._base._axis_method_wrapper.__set_name__ (self, owner, name)
Definition at line 67 of file _base.py.
Member Data Documentation
__doc__
matplotlib.axes._base._axis_method_wrapper.__doc__ = doc private
Definition at line 65 of file _base.py.
Referenced by scipy.stats._multivariate.multivariate_t_gen.__init__(), scipy.stats._distn_infrastructure.rv_discrete._attach_methods(), scipy.stats._distn_infrastructure.rv_generic._construct_default_doc(), scipy.stats._distn_infrastructure.rv_generic._construct_doc(), and pip._vendor.pygments.sphinxext.PygmentsDoc.document_lexers_overview().
_missing_subs
matplotlib.axes._base._axis_method_wrapper._missing_subs = [] protected
Definition at line 58 of file _base.py.
attr_name
matplotlib.axes._base._axis_method_wrapper.attr_name = attr_name
Definition at line 53 of file _base.py.
method_name
matplotlib.axes._base._axis_method_wrapper.method_name = method_name
Definition at line 54 of file _base.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/axes/_base.py