Code Cloning Analysis: sklearn.covariance._empirical_covariance.EmpiricalCovariance Class Reference
sklearn.covariance._empirical_covariance.EmpiricalCovariance Class Reference
Public Member Functions
__init__ (self, *, store_precision=True, assume_centered=False)
get_precision (self)
fit (self, X, y=None)
score (self, X_test, y=None)
error_norm (self, comp_cov, norm="frobenius", scaling=True, squared=True)
mahalanobis (self, X)
Public Member Functions inherited from sklearn.base.BaseEstimator
get_params (self, deep=True)
set_params (self, **params)
__sklearn_clone__ (self)
__repr__ (self, N_CHAR_MAX=700)
__getstate__ (self)
__setstate__ (self, state)
__sklearn_tags__ (self)
Public Member Functions inherited from sklearn.utils._metadata_requests._MetadataRequester
set_fit_request (self, **kwargs)
set_partial_fit_request (self, **kwargs)
set_predict_request (self, **kwargs)
set_predict_proba_request (self, **kwargs)
set_predict_log_proba_request (self, **kwargs)
set_decision_function_request (self, **kwargs)
set_score_request (self, **kwargs)
set_split_request (self, **kwargs)
set_transform_request (self, **kwargs)
set_inverse_transform_request (self, **kwargs)
__init_subclass__ (cls, **kwargs)
get_metadata_routing (self)
Public Attributes
store_precision = store_precision
assume_centered = assume_centered
covariance_ = covariance
precision_ = linalg.pinvh(covariance, check_finite=False)
location_ = np.zeros(X.shape[1])
Protected Member Functions
_set_covariance (self, covariance)
Protected Member Functions inherited from sklearn.base.BaseEstimator
_get_param_names (cls)
_get_params_html (self, deep=True)
_validate_params (self)
Protected Member Functions inherited from sklearn.utils._repr_html.base.ReprHTMLMixin
_repr_html_ (self)
_repr_html_inner (self)
_repr_mimebundle_ (self, **kwargs)
Protected Member Functions inherited from sklearn.utils._repr_html.base._HTMLDocumentationLinkMixin
_doc_link_template (self)
_doc_link_template (self, value)
_get_doc_link (self)
Protected Member Functions inherited from sklearn.utils._metadata_requests._MetadataRequester
_build_request_for_signature (cls, router, method)
_get_default_requests (cls)
_get_metadata_request (self)
Static Private Attributes
dict __metadata_request__score = {"X_test": metadata_routing.UNUSED}
Additional Inherited Members
Protected Attributes inherited from sklearn.base.BaseEstimator
_parameter_constraints
Static Protected Attributes inherited from sklearn.base.BaseEstimator
_html_repr = estimator_html_repr
Static Protected Attributes inherited from sklearn.utils._repr_html.base._HTMLDocumentationLinkMixin
str _doc_link_module = "sklearn"
_doc_link_url_param_generator = None
Detailed Description
Maximum likelihood covariance estimator.
Read more in the :ref:`User Guide <covariance>`.
Parameters
----------
store_precision : bool, default=True
    Specifies if the estimated precision is stored.
assume_centered : bool, default=False
    If True, data are not centered before computation.
    Useful when working with data whose mean is almost, but not exactly
    zero.
    If False (default), data are centered before computation.
Attributes
----------
location_ : ndarray of shape (n_features,)
    Estimated location, i.e. the estimated mean.
covariance_ : ndarray of shape (n_features, n_features)
    Estimated covariance matrix.
precision_ : ndarray of shape (n_features, n_features)
    Estimated pseudo-inverse matrix.
    (stored only if store_precision is True)
n_features_in_ : int
    Number of features seen during :term:`fit`.
    .. versionadded:: 0.24
feature_names_in_ : ndarray of shape (`n_features_in_`,)
    Names of features seen during :term:`fit`. Defined only when `X`
    has feature names that are all strings.
    .. versionadded:: 1.0
See Also
--------
EllipticEnvelope : An object for detecting outliers in
    a Gaussian distributed dataset.
GraphicalLasso : Sparse inverse covariance estimation
    with an l1-penalized estimator.
LedoitWolf : LedoitWolf Estimator.
MinCovDet : Minimum Covariance Determinant
    (robust estimator of covariance).
OAS : Oracle Approximating Shrinkage Estimator.
ShrunkCovariance : Covariance estimator with shrinkage.
Examples
--------
>>> import numpy as np
>>> from sklearn.covariance import EmpiricalCovariance
>>> from sklearn.datasets import make_gaussian_quantiles
>>> real_cov = np.array([[.8, .3],
...                      [.3, .4]])
>>> rng = np.random.RandomState(0)
>>> X = rng.multivariate_normal(mean=[0, 0],
...                             cov=real_cov,
...                             size=500)
>>> cov = EmpiricalCovariance().fit(X)
>>> cov.covariance_
array([[0.7569, 0.2818],
       [0.2818, 0.3928]])
>>> cov.location_
array([0.0622, 0.0193])
Definition at line 116 of file _empirical_covariance.py.
Constructor & Destructor Documentation
__init__()
sklearn.covariance._empirical_covariance.EmpiricalCovariance.__init__ (self, * , store_precision = True, assume_centered = False)
Definition at line 194 of file _empirical_covariance.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params().
Member Function Documentation
_set_covariance()
sklearn.covariance._empirical_covariance.EmpiricalCovariance._set_covariance (self, covariance) protected
Saves the covariance and precision estimates
Storage is done accordingly to `self.store_precision`.
Precision stored only if invertible.
Parameters
----------
covariance : array-like of shape (n_features, n_features)
    Estimated covariance matrix to be stored, and from which precision
    is computed.
Definition at line 198 of file _empirical_covariance.py.
References covariance_, precision_, and store_precision.
Referenced by fit(), sklearn.covariance._shrunk_covariance.LedoitWolf.fit(), sklearn.covariance._shrunk_covariance.OAS.fit(), sklearn.covariance._shrunk_covariance.ShrunkCovariance.fit(), and sklearn.covariance._robust_covariance.MinCovDet.reweight_covariance().
error_norm()
sklearn.covariance._empirical_covariance.EmpiricalCovariance.error_norm (self, comp_cov, norm = "frobenius", scaling = True, squared = True)
Compute the Mean Squared Error between two covariance estimators.
Parameters
----------
comp_cov : array-like of shape (n_features, n_features)
    The covariance to compare with.
norm : {"frobenius", "spectral"}, default="frobenius"
    The type of norm used to compute the error. Available error types:
    - 'frobenius' (default): sqrt(tr(A^t.A))
    - 'spectral': sqrt(max(eigenvalues(A^t.A))
    where A is the error ``(comp_cov - self.covariance_)``.
scaling : bool, default=True
    If True (default), the squared error norm is divided by n_features.
    If False, the squared error norm is not rescaled.
squared : bool, default=True
    Whether to compute the squared error norm or the error norm.
    If True (default), the squared error norm is returned.
    If False, the error norm is returned.
Returns
-------
result : float
    The Mean Squared Error (in the sense of the Frobenius norm) between
    `self` and `comp_cov` covariance estimators.
Definition at line 292 of file _empirical_covariance.py.
References covariance_.
fit()
sklearn.covariance._empirical_covariance.EmpiricalCovariance.fit (self, X, y = None)
Fit the maximum likelihood covariance estimator to X.
Parameters
----------
X : array-like of shape (n_samples, n_features)
  Training data, where `n_samples` is the number of samples and
  `n_features` is the number of features.
y : Ignored
    Not used, present for API consistency by convention.
Returns
-------
self : object
    Returns the instance itself.
Reimplemented in sklearn.covariance._elliptic_envelope.EllipticEnvelope, sklearn.covariance._graph_lasso.GraphicalLasso, sklearn.covariance._graph_lasso.GraphicalLassoCV, sklearn.covariance._robust_covariance.MinCovDet, sklearn.covariance._shrunk_covariance.LedoitWolf, sklearn.covariance._shrunk_covariance.OAS, and sklearn.covariance._shrunk_covariance.ShrunkCovariance.
Definition at line 234 of file _empirical_covariance.py.
References _set_covariance(), assume_centered, sklearn.covariance._empirical_covariance.empirical_covariance(), and location_.
Referenced by sklearn.cluster._kmeans._BaseKMeans.fit_predict(), sklearn.neighbors._lof.LocalOutlierFactor.fit_predict(), sklearn.cluster._kmeans._BaseKMeans.fit_transform(), sklearn.cross_decomposition._pls._PLS.fit_transform(), sklearn.cross_decomposition._pls.PLSSVD.fit_transform(), sklearn.decomposition._kernel_pca.KernelPCA.fit_transform(), sklearn.decomposition._lda.LatentDirichletAllocation.fit_transform(), sklearn.manifold._spectral_embedding.SpectralEmbedding.fit_transform(), sklearn.neighbors._graph.KNeighborsTransformer.fit_transform(), sklearn.neighbors._graph.RadiusNeighborsTransformer.fit_transform(), sklearn.preprocessing._label.LabelBinarizer.fit_transform(), sklearn.preprocessing._label.MultiLabelBinarizer.fit_transform(), sklearn.tests.metadata_routing_common.ConsumingTransformer.fit_transform(), and sklearn.utils.tests.test_estimator_checks.SparseTransformer.fit_transform().
get_precision()
sklearn.covariance._empirical_covariance.EmpiricalCovariance.get_precision (self)
Getter for the precision matrix.
Returns
-------
precision_ : array-like of shape (n_features, n_features)
    The precision matrix associated to the current covariance object.
Definition at line 219 of file _empirical_covariance.py.
References covariance_, precision_, and store_precision.
Referenced by mahalanobis(), sklearn.covariance._robust_covariance.MinCovDet.reweight_covariance(), score(), sklearn.decomposition._factor_analysis.FactorAnalysis.score_samples(), and sklearn.decomposition._pca.PCA.score_samples().
mahalanobis()
sklearn.covariance._empirical_covariance.EmpiricalCovariance.mahalanobis (self, X)
Compute the squared Mahalanobis distances of given observations.
For a detailed example of how outliers affects the Mahalanobis distance,
see :ref:`sphx_glr_auto_examples_covariance_plot_mahalanobis_distances.py`.
Parameters
----------
X : array-like of shape (n_samples, n_features)
    The observations, the Mahalanobis distances of the which we
    compute. Observations are assumed to be drawn from the same
    distribution than the data used in fit.
Returns
-------
dist : ndarray of shape (n_samples,)
    Squared Mahalanobis distances of the observations.
Definition at line 343 of file _empirical_covariance.py.
References get_precision(), and location_.
Referenced by sklearn.covariance._elliptic_envelope.EllipticEnvelope.score_samples().
score()
sklearn.covariance._empirical_covariance.EmpiricalCovariance.score (self, X_test, y = None)
Compute the log-likelihood of `X_test` under the estimated Gaussian model.
The Gaussian model is defined by its mean and covariance matrix which are
represented respectively by `self.location_` and `self.covariance_`.
Parameters
----------
X_test : array-like of shape (n_samples, n_features)
    Test data of which we compute the likelihood, where `n_samples` is
    the number of samples and `n_features` is the number of features.
    `X_test` is assumed to be drawn from the same distribution than
    the data used in fit (including centering).
y : Ignored
    Not used, present for API consistency by convention.
Returns
-------
res : float
    The log-likelihood of `X_test` with `self.location_` and `self.covariance_`
    as estimators of the Gaussian model mean and covariance matrix respectively.
Reimplemented in sklearn.covariance._elliptic_envelope.EllipticEnvelope.
Definition at line 261 of file _empirical_covariance.py.
References sklearn.covariance._empirical_covariance.empirical_covariance(), get_precision(), location_, and sklearn.covariance._empirical_covariance.log_likelihood().
Member Data Documentation
__metadata_request__score
dict sklearn.covariance._empirical_covariance.EmpiricalCovariance.__metadata_request__score = {"X_test": metadata_routing.UNUSED} static private
Definition at line 187 of file _empirical_covariance.py.
assume_centered
sklearn.covariance._empirical_covariance.EmpiricalCovariance.assume_centered = assume_centered
Definition at line 196 of file _empirical_covariance.py.
Referenced by fit(), sklearn.covariance._graph_lasso.GraphicalLasso.fit(), sklearn.covariance._graph_lasso.GraphicalLassoCV.fit(), sklearn.covariance._robust_covariance.MinCovDet.fit(), sklearn.covariance._shrunk_covariance.LedoitWolf.fit(), sklearn.covariance._shrunk_covariance.OAS.fit(), sklearn.covariance._shrunk_covariance.ShrunkCovariance.fit(), and sklearn.covariance._robust_covariance.MinCovDet.reweight_covariance().
covariance_
sklearn.covariance._empirical_covariance.EmpiricalCovariance.covariance_ = covariance
Definition at line 212 of file _empirical_covariance.py.
Referenced by _set_covariance(), sklearn.discriminant_analysis.LinearDiscriminantAnalysis._solve_eigen(), sklearn.discriminant_analysis.LinearDiscriminantAnalysis._solve_lstsq(), sklearn.discriminant_analysis.LinearDiscriminantAnalysis._solve_svd(), error_norm(), sklearn.covariance._graph_lasso.GraphicalLasso.fit(), sklearn.covariance._graph_lasso.GraphicalLassoCV.fit(), sklearn.discriminant_analysis.QuadraticDiscriminantAnalysis.fit(), and get_precision().
location_
sklearn.covariance._empirical_covariance.EmpiricalCovariance.location_ = np.zeros(X.shape[1])
Definition at line 253 of file _empirical_covariance.py.
Referenced by fit(), sklearn.covariance._graph_lasso.GraphicalLasso.fit(), sklearn.covariance._graph_lasso.GraphicalLassoCV.fit(), sklearn.covariance._robust_covariance.MinCovDet.fit(), sklearn.covariance._shrunk_covariance.LedoitWolf.fit(), sklearn.covariance._shrunk_covariance.OAS.fit(), sklearn.covariance._shrunk_covariance.ShrunkCovariance.fit(), mahalanobis(), sklearn.covariance._robust_covariance.MinCovDet.reweight_covariance(), and score().
precision_
sklearn.covariance._empirical_covariance.EmpiricalCovariance.precision_ = linalg.pinvh(covariance, check_finite=False)
Definition at line 215 of file _empirical_covariance.py.
Referenced by _set_covariance(), sklearn.covariance._graph_lasso.GraphicalLasso.fit(), sklearn.covariance._graph_lasso.GraphicalLassoCV.fit(), and get_precision().
store_precision
sklearn.covariance._empirical_covariance.EmpiricalCovariance.store_precision = store_precision
Definition at line 195 of file _empirical_covariance.py.
Referenced by _set_covariance(), and get_precision().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/sklearn/covariance/_empirical_covariance.py