Code Cloning Analysis: fontTools.misc.psOperators.ps_mark Class Reference
fontTools.misc.psOperators.ps_mark Class Reference
Public Member Functions
__init__ (self)
Public Member Functions inherited from fontTools.misc.psOperators.ps_object
__init__ (self, value)
__repr__ (self)
Additional Inherited Members
Public Attributes inherited from fontTools.misc.psOperators.ps_object
str type = self.__class__.__name__[3:] + "type"
Static Public Attributes inherited from fontTools.misc.psOperators.ps_object
int literal = 1
int access = 0
value = None
Detailed Description
Definition at line 191 of file psOperators.py.
Constructor & Destructor Documentation
__init__()
fontTools.misc.psOperators.ps_mark.__init__ (self)
Definition at line 192 of file psOperators.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/misc/psOperators.py