Code Cloning Analysis: scipy.linalg.tests.test_decomp.TestEigBanded Class Reference
scipy.linalg.tests.test_decomp.TestEigBanded Class Reference
Public Member Functions
setup_method (self)
create_bandmat (self)
test_dsbev (self)
test_dsbevd (self)
test_dsbevx (self)
test_zhbevd (self)
test_zhbevx (self)
test_eigvals_banded (self)
test_eig_banded (self)
test_dgbtrf (self)
test_zgbtrf (self)
test_dgbtrs (self)
test_zgbtrs (self)
Public Attributes
int KL = 2
int KU = 2
tuple sym_mat
tuple herm_mat
tuple real_mat
tuple comp_mat
w_sym_lin = ew[args]
evec_sym_lin = ev[:, args]
w_herm_lin = ew[args]
evec_herm_lin = ev[:, args]
bandmat_sym = zeros((LDAB, N), dtype=float)
bandmat_herm = zeros((LDAB, N), dtype=complex)
bandmat_real = zeros((LDAB, N), dtype=float)
bandmat_comp = zeros((LDAB, N), dtype=complex)
float b = 1.0*arange(N)
float bc = self.b * (1 + 1j)
Detailed Description
Definition at line 357 of file test_decomp.py.
Member Function Documentation
create_bandmat()
scipy.linalg.tests.test_decomp.TestEigBanded.create_bandmat (self)
Create the full matrix `self.fullmat` and
   the corresponding band matrix `self.bandmat`.
Definition at line 361 of file test_decomp.py.
setup_method()
scipy.linalg.tests.test_decomp.TestEigBanded.setup_method (self)
Definition at line 358 of file test_decomp.py.
test_dgbtrf()
scipy.linalg.tests.test_decomp.TestEigBanded.test_dgbtrf (self)
Compare dgbtrf  LU factorisation with the LU factorisation result
   of linalg.lu.
Definition at line 588 of file test_decomp.py.
test_dgbtrs()
scipy.linalg.tests.test_decomp.TestEigBanded.test_dgbtrs (self)
Compare dgbtrs  solutions for linear equation system  A*x = b
   with solutions of linalg.solve.
Definition at line 616 of file test_decomp.py.
test_dsbev()
scipy.linalg.tests.test_decomp.TestEigBanded.test_dsbev (self)
Compare dsbev eigenvalues and eigenvectors with
   the result of linalg.eig.
Definition at line 442 of file test_decomp.py.
test_dsbevd()
scipy.linalg.tests.test_decomp.TestEigBanded.test_dsbevd (self)
Compare dsbevd eigenvalues and eigenvectors with
   the result of linalg.eig.
Definition at line 450 of file test_decomp.py.
test_dsbevx()
scipy.linalg.tests.test_decomp.TestEigBanded.test_dsbevx (self)
Compare dsbevx eigenvalues and eigenvectors
   with the result of linalg.eig.
Definition at line 458 of file test_decomp.py.
test_eig_banded()
scipy.linalg.tests.test_decomp.TestEigBanded.test_eig_banded (self)
Compare eigenvalues and eigenvectors of eig_banded
   with those of linalg.eig.
Definition at line 530 of file test_decomp.py.
test_eigvals_banded()
scipy.linalg.tests.test_decomp.TestEigBanded.test_eigvals_banded (self)
Compare eigenvalues of eigvals_banded with those of linalg.eig.
Definition at line 488 of file test_decomp.py.
test_zgbtrf()
scipy.linalg.tests.test_decomp.TestEigBanded.test_zgbtrf (self)
Compare zgbtrf  LU factorisation with the LU factorisation result
   of linalg.lu.
Definition at line 602 of file test_decomp.py.
test_zgbtrs()
scipy.linalg.tests.test_decomp.TestEigBanded.test_zgbtrs (self)
Compare zgbtrs  solutions for linear equation system  A*x = b
   with solutions of linalg.solve.
Definition at line 626 of file test_decomp.py.
test_zhbevd()
scipy.linalg.tests.test_decomp.TestEigBanded.test_zhbevd (self)
Compare zhbevd eigenvalues and eigenvectors
   with the result of linalg.eig.
Definition at line 469 of file test_decomp.py.
test_zhbevx()
scipy.linalg.tests.test_decomp.TestEigBanded.test_zhbevx (self)
Compare zhbevx eigenvalues and eigenvectors
   with the result of linalg.eig.
Definition at line 477 of file test_decomp.py.
Member Data Documentation
b
float scipy.linalg.tests.test_decomp.TestEigBanded.b = 1.0*arange(N)
Definition at line 437 of file test_decomp.py.
Referenced by scipy.stats._continuous_distns.rv_histogram.__init__(), scipy.stats._discrete_distns.bernoulli_gen._get_support(), scipy.stats._distn_infrastructure.rv_generic._get_support(), scipy.stats._distn_infrastructure.rv_sample._get_support(), scipy.stats._distn_infrastructure.rv_continuous._updated_ctor_param(), scipy.stats._distn_infrastructure.rv_discrete._updated_ctor_param(), sklearn.tests.test_pipeline.NoTrans.get_params(), scipy.stats._page_trend_test._PageL.p_l_k_1(), scipy.stats._page_trend_test._PageL.pmf(), scipy.stats._page_trend_test._PageL.set_k(), sklearn.utils.tests.test_estimator_checks.ModifiesAnotherValue.set_params(), scipy.stats._page_trend_test._PageL.sf(), and scipy.special._mptestutils.Arg.values().
bandmat_comp
scipy.linalg.tests.test_decomp.TestEigBanded.bandmat_comp = zeros((LDAB, N), dtype=complex)
Definition at line 427 of file test_decomp.py.
bandmat_herm
scipy.linalg.tests.test_decomp.TestEigBanded.bandmat_herm = zeros((LDAB, N), dtype=complex)
Definition at line 410 of file test_decomp.py.
bandmat_real
scipy.linalg.tests.test_decomp.TestEigBanded.bandmat_real = zeros((LDAB, N), dtype=float)
Definition at line 418 of file test_decomp.py.
bandmat_sym
scipy.linalg.tests.test_decomp.TestEigBanded.bandmat_sym = zeros((LDAB, N), dtype=float)
Definition at line 409 of file test_decomp.py.
bc
float scipy.linalg.tests.test_decomp.TestEigBanded.bc = self.b * (1 + 1j)
Definition at line 438 of file test_decomp.py.
comp_mat
tuple scipy.linalg.tests.test_decomp.TestEigBanded.comp_mat
Initial value:
=  (1j*diag(full(N, 1.0))
                         + diag(full(N-1, -1.0), -1)
                         + 1j*diag(full(N-1, -3.0), 1)
                         + diag(full(N-2, 2.0), -2)
                         + diag(full(N-2, -2.0), 2))
Definition at line 386 of file test_decomp.py.
evec_herm_lin
scipy.linalg.tests.test_decomp.TestEigBanded.evec_herm_lin = ev[:, args]
Definition at line 403 of file test_decomp.py.
evec_sym_lin
scipy.linalg.tests.test_decomp.TestEigBanded.evec_sym_lin = ev[:, args]
Definition at line 397 of file test_decomp.py.
herm_mat
tuple scipy.linalg.tests.test_decomp.TestEigBanded.herm_mat
Initial value:
=  (diag(full(N, -1.0))
                         + 1j*diag(full(N-1, 1.0), -1)
                         - 1j*diag(full(N-1, 1.0), 1)
                         + diag(full(N-2, -2.0), -2)
                         + diag(full(N-2, -2.0), 2))
Definition at line 374 of file test_decomp.py.
KL
scipy.linalg.tests.test_decomp.TestEigBanded.KL = 2
Definition at line 365 of file test_decomp.py.
KU
scipy.linalg.tests.test_decomp.TestEigBanded.KU = 2
Definition at line 366 of file test_decomp.py.
real_mat
tuple scipy.linalg.tests.test_decomp.TestEigBanded.real_mat
Initial value:
=  (diag(full(N, 1.0))
                         + diag(full(N-1, -1.0), -1) + diag(full(N-1, -3.0), 1)
                         + diag(full(N-2, 2.0), -2) + diag(full(N-2, -2.0), 2))
Definition at line 381 of file test_decomp.py.
sym_mat
tuple scipy.linalg.tests.test_decomp.TestEigBanded.sym_mat
Initial value:
=  (diag(full(N, 1.0))
                        + diag(full(N-1, -1.0), -1) + diag(full(N-1, -1.0), 1)
                        + diag(full(N-2, -2.0), -2) + diag(full(N-2, -2.0), 2))
Definition at line 369 of file test_decomp.py.
w_herm_lin
scipy.linalg.tests.test_decomp.TestEigBanded.w_herm_lin = ew[args]
Definition at line 402 of file test_decomp.py.
w_sym_lin
scipy.linalg.tests.test_decomp.TestEigBanded.w_sym_lin = ew[args]
Definition at line 396 of file test_decomp.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/linalg/tests/test_decomp.py