Code Cloning Analysis: sklearn.datasets._twenty_newsgroups Namespace Reference
sklearn.datasets._twenty_newsgroups Namespace Reference
Functions
_download_20newsgroups (target_dir, cache_path, n_retries, delay)
strip_newsgroup_header (text)
strip_newsgroup_quoting (text)
strip_newsgroup_footer (text)
fetch_20newsgroups (*, data_home=None, subset="train", categories=None, shuffle=True, random_state=42, remove=(), download_if_missing=True, return_X_y=False, n_retries=3, delay=1.0)
fetch_20newsgroups_vectorized (*, subset="train", remove=(), data_home=None, download_if_missing=True, return_X_y=False, normalize=True, as_frame=False, n_retries=3, delay=1.0)
Variables
logger = logging.getLogger(__name__)
ARCHIVE
str CACHE_NAME = "20news-bydate.pkz"
str TRAIN_FOLDER = "20news-bydate-train"
str TEST_FOLDER = "20news-bydate-test"
_QUOTE_RE
Detailed Description
Caching loader for the 20 newsgroups text classification dataset.
The description of the dataset is available on the official website at:
    http://people.csail.mit.edu/jrennie/20Newsgroups/
Quoting the introduction:
    The 20 Newsgroups data set is a collection of approximately 20,000
    newsgroup documents, partitioned (nearly) evenly across 20 different
    newsgroups. To the best of my knowledge, it was originally collected
    by Ken Lang, probably for his Newsweeder: Learning to filter netnews
    paper, though he does not explicitly mention this collection. The 20
    newsgroups collection has become a popular data set for experiments
    in text applications of machine learning techniques, such as text
    classification and text clustering.
This dataset loader will download the recommended "by date" variant of the
dataset and which features a point in time split between the train and
test sets. The compressed dataset size is around 14 Mb compressed. Once
uncompressed the train set is 52 MB and the test set is 34 MB.
Function Documentation
_download_20newsgroups()
sklearn.datasets._twenty_newsgroups._download_20newsgroups (target_dir, cache_path, n_retries, delay) protected
Download the 20 newsgroups data and stored it as a zipped pickle.
Definition at line 71 of file _twenty_newsgroups.py.
Referenced by fetch_20newsgroups().
fetch_20newsgroups()
sklearn.datasets._twenty_newsgroups.fetch_20newsgroups (* , data_home = None, subset = "train", categories = None, shuffle = True, random_state = 42, remove = (), download_if_missing = True, return_X_y = False, n_retries = 3, delay = 1.0)
Load the filenames and data from the 20 newsgroups dataset \
(classification).
Download it if necessary.
=================   ==========
Classes                     20
Samples total            18846
Dimensionality               1
Features                  text
=================   ==========
Read more in the :ref:`User Guide <20newsgroups_dataset>`.
Parameters
----------
data_home : str or path-like, default=None
    Specify a download and cache folder for the datasets. If None,
    all scikit-learn data is stored in '~/scikit_learn_data' subfolders.
subset : {'train', 'test', 'all'}, default='train'
    Select the dataset to load: 'train' for the training set, 'test'
    for the test set, 'all' for both, with shuffled ordering.
categories : array-like, dtype=str, default=None
    If None (default), load all the categories.
    If not None, list of category names to load (other categories
    ignored).
shuffle : bool, default=True
    Whether or not to shuffle the data: might be important for models that
    make the assumption that the samples are independent and identically
    distributed (i.i.d.), such as stochastic gradient descent.
random_state : int, RandomState instance or None, default=42
    Determines random number generation for dataset shuffling. Pass an int
    for reproducible output across multiple function calls.
    See :term:`Glossary <random_state>`.
remove : tuple, default=()
    May contain any subset of ('headers', 'footers', 'quotes'). Each of
    these are kinds of text that will be detected and removed from the
    newsgroup posts, preventing classifiers from overfitting on
    metadata.
    'headers' removes newsgroup headers, 'footers' removes blocks at the
    ends of posts that look like signatures, and 'quotes' removes lines
    that appear to be quoting another post.
    'headers' follows an exact standard; the other filters are not always
    correct.
download_if_missing : bool, default=True
    If False, raise an OSError if the data is not locally available
    instead of trying to download the data from the source site.
return_X_y : bool, default=False
    If True, returns `(data.data, data.target)` instead of a Bunch
    object.
    .. versionadded:: 0.22
n_retries : int, default=3
    Number of retries when HTTP errors are encountered.
    .. versionadded:: 1.5
delay : float, default=1.0
    Number of seconds between retries.
    .. versionadded:: 1.5
Returns
-------
bunch : :class:`~sklearn.utils.Bunch`
    Dictionary-like object, with the following attributes.
    data : list of shape (n_samples,)
        The data list to learn.
    target: ndarray of shape (n_samples,)
        The target labels.
    filenames: list of shape (n_samples,)
        The path to the location of the data.
    DESCR: str
        The full description of the dataset.
    target_names: list of shape (n_classes,)
        The names of target classes.
(data, target) : tuple if `return_X_y=True`
    A tuple of two ndarrays. The first contains a 2D array of shape
    (n_samples, n_classes) with each row representing one sample and each
    column representing the features. The second array of shape
    (n_samples,) contains the target samples.
    .. versionadded:: 0.22
Examples
--------
>>> from sklearn.datasets import fetch_20newsgroups
>>> cats = ['alt.atheism', 'sci.space']
>>> newsgroups_train = fetch_20newsgroups(subset='train', categories=cats)
>>> list(newsgroups_train.target_names)
['alt.atheism', 'sci.space']
>>> newsgroups_train.filenames.shape
(1073,)
>>> newsgroups_train.target.shape
(1073,)
>>> newsgroups_train.target[:10]
array([0, 1, 1, 1, 0, 1, 1, 0, 0, 0])
Definition at line 177 of file _twenty_newsgroups.py.
References _download_20newsgroups(), strip_newsgroup_footer(), strip_newsgroup_header(), and strip_newsgroup_quoting().
Referenced by fetch_20newsgroups_vectorized().
fetch_20newsgroups_vectorized()
sklearn.datasets._twenty_newsgroups.fetch_20newsgroups_vectorized (* , subset = "train", remove = (), data_home = None, download_if_missing = True, return_X_y = False, normalize = True, as_frame = False, n_retries = 3, delay = 1.0)
Load and vectorize the 20 newsgroups dataset (classification).
Download it if necessary.
This is a convenience function; the transformation is done using the
default settings for
:class:`~sklearn.feature_extraction.text.CountVectorizer`. For more
advanced usage (stopword filtering, n-gram extraction, etc.), combine
fetch_20newsgroups with a custom
:class:`~sklearn.feature_extraction.text.CountVectorizer`,
:class:`~sklearn.feature_extraction.text.HashingVectorizer`,
:class:`~sklearn.feature_extraction.text.TfidfTransformer` or
:class:`~sklearn.feature_extraction.text.TfidfVectorizer`.
The resulting counts are normalized using
:func:`sklearn.preprocessing.normalize` unless normalize is set to False.
=================   ==========
Classes                     20
Samples total            18846
Dimensionality          130107
Features                  real
=================   ==========
Read more in the :ref:`User Guide <20newsgroups_dataset>`.
Parameters
----------
subset : {'train', 'test', 'all'}, default='train'
    Select the dataset to load: 'train' for the training set, 'test'
    for the test set, 'all' for both, with shuffled ordering.
remove : tuple, default=()
    May contain any subset of ('headers', 'footers', 'quotes'). Each of
    these are kinds of text that will be detected and removed from the
    newsgroup posts, preventing classifiers from overfitting on
    metadata.
    'headers' removes newsgroup headers, 'footers' removes blocks at the
    ends of posts that look like signatures, and 'quotes' removes lines
    that appear to be quoting another post.
data_home : str or path-like, default=None
    Specify an download and cache folder for the datasets. If None,
    all scikit-learn data is stored in '~/scikit_learn_data' subfolders.
download_if_missing : bool, default=True
    If False, raise an OSError if the data is not locally available
    instead of trying to download the data from the source site.
return_X_y : bool, default=False
    If True, returns ``(data.data, data.target)`` instead of a Bunch
    object.
    .. versionadded:: 0.20
normalize : bool, default=True
    If True, normalizes each document's feature vector to unit norm using
    :func:`sklearn.preprocessing.normalize`.
    .. versionadded:: 0.22
as_frame : bool, default=False
    If True, the data is a pandas DataFrame including columns with
    appropriate dtypes (numeric, string, or categorical). The target is
    a pandas DataFrame or Series depending on the number of
    `target_columns`.
    .. versionadded:: 0.24
n_retries : int, default=3
    Number of retries when HTTP errors are encountered.
    .. versionadded:: 1.5
delay : float, default=1.0
    Number of seconds between retries.
    .. versionadded:: 1.5
Returns
-------
bunch : :class:`~sklearn.utils.Bunch`
    Dictionary-like object, with the following attributes.
    data: {sparse matrix, dataframe} of shape (n_samples, n_features)
        The input data matrix. If ``as_frame`` is `True`, ``data`` is
        a pandas DataFrame with sparse columns.
    target: {ndarray, series} of shape (n_samples,)
        The target labels. If ``as_frame`` is `True`, ``target`` is a
        pandas Series.
    target_names: list of shape (n_classes,)
        The names of target classes.
    DESCR: str
        The full description of the dataset.
    frame: dataframe of shape (n_samples, n_features + 1)
        Only present when `as_frame=True`. Pandas DataFrame with ``data``
        and ``target``.
        .. versionadded:: 0.24
(data, target) : tuple if ``return_X_y`` is True
    `data` and `target` would be of the format defined in the `Bunch`
    description above.
    .. versionadded:: 0.20
Examples
--------
>>> from sklearn.datasets import fetch_20newsgroups_vectorized
>>> newsgroups_vectorized = fetch_20newsgroups_vectorized(subset='test')
>>> newsgroups_vectorized.data.shape
(7532, 130107)
>>> newsgroups_vectorized.target.shape
(7532,)
Definition at line 403 of file _twenty_newsgroups.py.
References fetch_20newsgroups().
strip_newsgroup_footer()
sklearn.datasets._twenty_newsgroups.strip_newsgroup_footer (text)
Given text in "news" format, attempt to remove a signature block.
As a rough heuristic, we assume that signatures are set apart by either
a blank line or a line made of hyphens, and that it is the last such line
in the file (disregarding blank lines at the end).
Parameters
----------
text : str
    The text from which to remove the signature block.
Definition at line 137 of file _twenty_newsgroups.py.
Referenced by fetch_20newsgroups().
strip_newsgroup_header()
sklearn.datasets._twenty_newsgroups.strip_newsgroup_header (text)
Given text in "news" format, strip the headers, by removing everything
before the first blank line.
Parameters
----------
text : str
    The text from which to remove the signature block.
Definition at line 103 of file _twenty_newsgroups.py.
Referenced by fetch_20newsgroups().
strip_newsgroup_quoting()
sklearn.datasets._twenty_newsgroups.strip_newsgroup_quoting (text)
Given text in "news" format, strip lines beginning with the quote
characters > or |, plus lines that often introduce a quoted section
(for example, because they contain the string 'writes:'.)
Parameters
----------
text : str
    The text from which to remove the signature block.
Definition at line 122 of file _twenty_newsgroups.py.
Referenced by fetch_20newsgroups().
Variable Documentation
_QUOTE_RE
sklearn.datasets._twenty_newsgroups._QUOTE_RE protected
Initial value:
=  re.compile(
    r"(writes in|writes:|wrote:|says:|said:|^In article|^Quoted from|^\||^>)"
)
Definition at line 117 of file _twenty_newsgroups.py.
ARCHIVE
sklearn.datasets._twenty_newsgroups.ARCHIVE
Initial value:
=  RemoteFileMetadata(
    filename="20news-bydate.tar.gz",
    url="https://ndownloader.figshare.com/files/5975967",
    checksum="8f1b2514ca22a5ade8fbb9cfa5727df95fa587f4c87b786e15c759fa66d95610",
)
Definition at line 60 of file _twenty_newsgroups.py.
CACHE_NAME
str sklearn.datasets._twenty_newsgroups.CACHE_NAME = "20news-bydate.pkz"
Definition at line 66 of file _twenty_newsgroups.py.
logger
sklearn.datasets._twenty_newsgroups.logger = logging.getLogger(__name__)
Definition at line 56 of file _twenty_newsgroups.py.
TEST_FOLDER
str sklearn.datasets._twenty_newsgroups.TEST_FOLDER = "20news-bydate-test"
Definition at line 68 of file _twenty_newsgroups.py.
TRAIN_FOLDER
str sklearn.datasets._twenty_newsgroups.TRAIN_FOLDER = "20news-bydate-train"
Definition at line 67 of file _twenty_newsgroups.py.