Code Cloning Analysis: pandas.core.arrays.integer.UInt32Dtype Class Reference
pandas.core.arrays.integer.UInt32Dtype Class Reference
Static Private Attributes
__doc__ = _dtype_docstring.format(dtype="uint32")
Additional Inherited Members
Public Member Functions inherited from pandas.core.arrays.integer.IntegerDtype
type[IntegerArray] construct_array_type (cls)
Public Member Functions inherited from pandas.core.arrays.numeric.NumericDtype
str __repr__ (self)
bool is_signed_integer (self)
bool is_unsigned_integer (self)
BaseMaskedArray __from_arrow__ (self, pyarrow.Array|pyarrow.ChunkedArray array)
Public Member Functions inherited from pandas.core.dtypes.dtypes.BaseMaskedDtype
libmissing.NAType na_value (self)
np.dtype numpy_dtype (self)
str kind (self)
int itemsize (self)
BaseMaskedDtype from_numpy_dtype (cls, np.dtype dtype)
Public Member Functions inherited from pandas.core.dtypes.base.ExtensionDtype
str __str__ (self)
bool __eq__ (self, object other)
int __hash__ (self)
bool __ne__ (self, object other)
type_t[Any] type (self)
str name (self)
list[str]|None names (self)
ExtensionArray empty (self, Shape shape)
Self construct_from_string (cls, str string)
bool is_dtype (cls, object dtype)
type_t[Index] index_class (self)
Public Attributes inherited from pandas.core.dtypes.base.ExtensionDtype
name
Static Public Attributes inherited from pandas.core.dtypes.dtypes.BaseMaskedDtype
base = None
Protected Member Functions inherited from pandas.core.arrays.integer.IntegerDtype
dict[np.dtype, IntegerDtype] _get_dtype_mapping (cls)
np.ndarray _safe_cast (cls, np.ndarray values, np.dtype dtype, bool copy)
Protected Member Functions inherited from pandas.core.arrays.numeric.NumericDtype
bool _is_numeric (self)
NumericDtype _standardize_dtype (cls, NumericDtype|str|np.dtype dtype)
Protected Member Functions inherited from pandas.core.dtypes.dtypes.BaseMaskedDtype
DtypeObj|None _get_common_dtype (self, list[DtypeObj] dtypes)
Protected Member Functions inherited from pandas.core.dtypes.base.ExtensionDtype
bool _is_boolean (self)
bool _can_hold_na (self)
bool _is_immutable (self)
bool _supports_2d (self)
bool _can_fast_transpose (self)
Static Protected Attributes inherited from pandas.core.arrays.numeric.NumericDtype
np _default_np_dtype .dtype
Callable _checker [[Any], bool]
Static Protected Attributes inherited from pandas.core.dtypes.base.ExtensionDtype
tuple _metadata = ()
Detailed Description
Definition at line 250 of file integer.py.
Member Data Documentation
__doc__
pandas.core.arrays.integer.UInt32Dtype.__doc__ = _dtype_docstring.format(dtype="uint32") static private
Definition at line 253 of file integer.py.
Referenced by scipy.stats._multivariate.multivariate_t_gen.__init__(), scipy.stats._distn_infrastructure.rv_discrete._attach_methods(), scipy.stats._distn_infrastructure.rv_generic._construct_default_doc(), scipy.stats._distn_infrastructure.rv_generic._construct_doc(), and pip._vendor.pygments.sphinxext.PygmentsDoc.document_lexers_overview().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/core/arrays/integer.py