Code Cloning Analysis: numpy.core.tests.test_multiarray.TestDot Class Reference
numpy.core.tests.test_multiarray.TestDot Class Reference
Public Member Functions
setup_method (self)
test_dotmatmat (self)
test_dotmatvec (self)
test_dotmatvec2 (self)
test_dotvecmat (self)
test_dotvecmat2 (self)
test_dotvecmat3 (self)
test_dotvecvecouter (self)
test_dotvecvecinner (self)
test_dotcolumnvect1 (self)
test_dotcolumnvect2 (self)
test_dotvecscalar (self)
test_dotvecscalar2 (self)
test_all (self)
test_vecobject (self)
test_dot_2args (self)
test_dot_3args (self)
test_dot_3args_errors (self)
test_dot_out_result (self)
test_dot_out_aliasing (self)
test_dot_array_order (self)
test_accelerate_framework_sgemv_fix (self)
test_huge_vectordot (self, dtype)
test_dtype_discovery_fails (self)
Public Attributes
A = np.random.rand(4, 2)
b1 = np.random.rand(2, 1)
b2 = np.random.rand(2)
b3 = np.random.rand(1, 2)
b4 = np.random.rand(4)
int N = 7
array = np.array(sequence)
Detailed Description
Definition at line 6495 of file test_multiarray.py.
Member Function Documentation
setup_method()
numpy.core.tests.test_multiarray.TestDot.setup_method (self)
Definition at line 6496 of file test_multiarray.py.
test_accelerate_framework_sgemv_fix()
numpy.core.tests.test_multiarray.TestDot.test_accelerate_framework_sgemv_fix (self)
Definition at line 6717 of file test_multiarray.py.
test_all()
numpy.core.tests.test_multiarray.TestDot.test_all (self)
Definition at line 6585 of file test_multiarray.py.
test_dot_2args()
numpy.core.tests.test_multiarray.TestDot.test_dot_2args (self)
Definition at line 6629 of file test_multiarray.py.
test_dot_3args()
numpy.core.tests.test_multiarray.TestDot.test_dot_3args (self)
Definition at line 6639 of file test_multiarray.py.
test_dot_3args_errors()
numpy.core.tests.test_multiarray.TestDot.test_dot_3args_errors (self)
Definition at line 6661 of file test_multiarray.py.
test_dot_array_order()
numpy.core.tests.test_multiarray.TestDot.test_dot_array_order (self)
Definition at line 6707 of file test_multiarray.py.
test_dot_out_aliasing()
numpy.core.tests.test_multiarray.TestDot.test_dot_out_aliasing (self)
Definition at line 6699 of file test_multiarray.py.
test_dot_out_result()
numpy.core.tests.test_multiarray.TestDot.test_dot_out_result (self)
Definition at line 6691 of file test_multiarray.py.
test_dotcolumnvect1()
numpy.core.tests.test_multiarray.TestDot.test_dotcolumnvect1 (self)
Definition at line 6555 of file test_multiarray.py.
test_dotcolumnvect2()
numpy.core.tests.test_multiarray.TestDot.test_dotcolumnvect2 (self)
Definition at line 6562 of file test_multiarray.py.
test_dotmatmat()
numpy.core.tests.test_multiarray.TestDot.test_dotmatmat (self)
Definition at line 6505 of file test_multiarray.py.
test_dotmatvec()
numpy.core.tests.test_multiarray.TestDot.test_dotmatvec (self)
Definition at line 6512 of file test_multiarray.py.
test_dotmatvec2()
numpy.core.tests.test_multiarray.TestDot.test_dotmatvec2 (self)
Definition at line 6519 of file test_multiarray.py.
test_dotvecmat()
numpy.core.tests.test_multiarray.TestDot.test_dotvecmat (self)
Definition at line 6525 of file test_multiarray.py.
test_dotvecmat2()
numpy.core.tests.test_multiarray.TestDot.test_dotvecmat2 (self)
Definition at line 6531 of file test_multiarray.py.
test_dotvecmat3()
numpy.core.tests.test_multiarray.TestDot.test_dotvecmat3 (self)
Definition at line 6537 of file test_multiarray.py.
test_dotvecscalar()
numpy.core.tests.test_multiarray.TestDot.test_dotvecscalar (self)
Definition at line 6569 of file test_multiarray.py.
test_dotvecscalar2()
numpy.core.tests.test_multiarray.TestDot.test_dotvecscalar2 (self)
Definition at line 6577 of file test_multiarray.py.
test_dotvecvecinner()
numpy.core.tests.test_multiarray.TestDot.test_dotvecvecinner (self)
Definition at line 6549 of file test_multiarray.py.
test_dotvecvecouter()
numpy.core.tests.test_multiarray.TestDot.test_dotvecvecouter (self)
Definition at line 6543 of file test_multiarray.py.
test_dtype_discovery_fails()
numpy.core.tests.test_multiarray.TestDot.test_dtype_discovery_fails (self)
Definition at line 6791 of file test_multiarray.py.
test_huge_vectordot()
numpy.core.tests.test_multiarray.TestDot.test_huge_vectordot (self, dtype)
Definition at line 6784 of file test_multiarray.py.
test_vecobject()
numpy.core.tests.test_multiarray.TestDot.test_vecobject (self)
Definition at line 6596 of file test_multiarray.py.
Member Data Documentation
A
numpy.core.tests.test_multiarray.TestDot.A = np.random.rand(4, 2)
Definition at line 6498 of file test_multiarray.py.
Referenced by scipy.signal._ltisys.StateSpace.__add__(), scipy.signal._ltisys.StateSpace.__init__(), scipy.sparse.linalg._matfuncs._ExpmPadeHelper.__init__(), scipy.signal._ltisys.StateSpace.__mul__(), scipy.signal._ltisys.StateSpace.__neg__(), scipy.signal._ltisys.StateSpace.__repr__(), scipy.signal._ltisys.StateSpace.__rmul__(), scipy.signal._ltisys.StateSpace._copy(), scipy.sparse.linalg.tests.test_onenormest.MatrixProductOperator._matmat(), scipy.sparse.linalg._eigen.tests.test_svds.CheckingLinearOperator._matvec(), scipy.sparse.linalg.tests.test_onenormest.MatrixProductOperator._matvec(), scipy.sparse.linalg._eigen.tests.test_svds.CheckingLinearOperator._rmatvec(), scipy.sparse.linalg.tests.test_onenormest.MatrixProductOperator._rmatvec(), scipy.optimize._constraints.LinearConstraint.residual(), and scipy.signal._ltisys.StateSpaceContinuous.to_discrete().
array
numpy.core.tests.test_multiarray.TestDot.array = np.array(sequence)
Definition at line 6601 of file test_multiarray.py.
Referenced by pandas.core.base.IndexOpsMixin._memory_usage(), pandas.core.internals.array_manager.SingleArrayManager.apply(), pandas.core.internals.array_manager.SingleArrayManager.array_values(), pandas.core.internals.array_manager.SingleArrayManager.axes(), pandas.core.internals.array_manager.SingleArrayManager.external_values(), pandas.core.internals.array_manager.SingleArrayManager.idelete(), pandas.core.internals.array_manager.SingleArrayManager.internal_values(), pandas.core.indexes.base.Index.ravel(), pandas.core.internals.base.SingleDataManager.setitem_inplace(), fontTools.pens.freetypePen.FreeTypePen.show(), numpy.ma.timer_comparison.ModuleTester.test_2(), numpy.ma.timer_comparison.ModuleTester.test_4(), numpy.ma.timer_comparison.ModuleTester.test_6(), numpy.f2py.tests.test_array_from_pyobj.TestSharedMemory.test_in_nocopy(), pandas.core.base.IndexOpsMixin.to_numpy(), and pandas.core.series.Series.view().
b1
numpy.core.tests.test_multiarray.TestDot.b1 = np.random.rand(2, 1)
Definition at line 6499 of file test_multiarray.py.
b2
numpy.core.tests.test_multiarray.TestDot.b2 = np.random.rand(2)
Definition at line 6500 of file test_multiarray.py.
b3
numpy.core.tests.test_multiarray.TestDot.b3 = np.random.rand(1, 2)
Definition at line 6501 of file test_multiarray.py.
b4
numpy.core.tests.test_multiarray.TestDot.b4 = np.random.rand(4)
Definition at line 6502 of file test_multiarray.py.
N
int numpy.core.tests.test_multiarray.TestDot.N = 7
Definition at line 6503 of file test_multiarray.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/core/tests/test_multiarray.py