Code Cloning Analysis: numpy.ma.mrecords Namespace Reference
numpy.ma.mrecords Namespace Reference
Classes
class MaskedRecords
Functions
_checknames (descr, names=None)
_get_fieldmask (self)
_mrreconstruct (subtype, baseclass, baseshape, basetype)
fromarrays (arraylist, dtype=None, shape=None, formats=None, names=None, titles=None, aligned=False, byteorder=None, fill_value=None)
Constructors #.
fromrecords (reclist, dtype=None, shape=None, formats=None, names=None, titles=None, aligned=False, byteorder=None, fill_value=None, mask=nomask)
_guessvartypes (arr)
openfile (fname)
fromtextfile (fname, delimiter=None, commentchar='#', missingchar='', varnames=None, vartypes=None, *, delimitor=np._NoValue)
addfield (mrecord, newfield, newfieldname=None)
Variables
_byteorderconv = np.core.records._byteorderconv
_check_fill_value = ma.core._check_fill_value
list __all__
list reserved_fields = ['_data', '_mask', '_fieldmask', 'dtype']
mrecarray = MaskedRecords
Detailed Description
:mod:`numpy.ma..mrecords`
Defines the equivalent of :class:`numpy.recarrays` for masked arrays,
where fields can be accessed as attributes.
Note that :class:`numpy.ma.MaskedArray` already supports structured datatypes
and the masking of individual fields.
.. moduleauthor:: Pierre Gerard-Marchant
Function Documentation
_checknames()
numpy.ma.mrecords._checknames (descr, names = None) protected
Checks that field names ``descr`` are not reserved keywords.
If this is the case, a default 'f%i' is substituted.  If the argument
`names` is not None, updates the field names to valid names.
Definition at line 45 of file mrecords.py.
_get_fieldmask()
numpy.ma.mrecords._get_fieldmask (self) protected
Definition at line 79 of file mrecords.py.
_guessvartypes()
numpy.ma.mrecords._guessvartypes (arr) protected
Tries to guess the dtypes of the str_ ndarray `arr`.
Guesses by testing element-wise conversion. Returns a list of dtypes.
The array is first converted to ndarray. If the array is 2D, the test
is performed on the first line. An exception is raised if the file is
3D or more.
Definition at line 612 of file mrecords.py.
Referenced by fromtextfile().
_mrreconstruct()
numpy.ma.mrecords._mrreconstruct (subtype, baseclass, baseshape, basetype) protected
Build a new MaskedArray from the information stored in a pickle.
Definition at line 487 of file mrecords.py.
addfield()
numpy.ma.mrecords.addfield (mrecord, newfield, newfieldname = None)
Adds a new field to the masked record array
Uses `newfield` as data and `newfieldname` as name. If `newfieldname`
is None, the new field name is set to 'fi', where `i` is the number of
existing fields.
Definition at line 749 of file mrecords.py.
References numpy.ma.core.getmaskarray().
fromarrays()
numpy.ma.mrecords.fromarrays (arraylist, dtype = None, shape = None, formats = None, names = None, titles = None, aligned = False, byteorder = None, fill_value = None)
Constructors #.
Creates a mrecarray from a (flat) list of masked arrays.
Parameters
----------
arraylist : sequence
    A list of (masked) arrays. Each element of the sequence is first converted
    to a masked array if needed. If a 2D array is passed as argument, it is
    processed line by line
dtype : {None, dtype}, optional
    Data type descriptor.
shape : {None, integer}, optional
    Number of records. If None, shape is defined from the shape of the
    first array in the list.
formats : {None, sequence}, optional
    Sequence of formats for each individual field. If None, the formats will
    be autodetected by inspecting the fields and selecting the highest dtype
    possible.
names : {None, sequence}, optional
    Sequence of the names of each field.
fill_value : {None, sequence}, optional
    Sequence of data to be used as filling values.
Notes
-----
Lists of tuples should be preferred over lists of lists for faster processing.
Definition at line 504 of file mrecords.py.
References numpy.ma.core.getdata(), and numpy.ma.core.getmaskarray().
Referenced by fromtextfile().
fromrecords()
numpy.ma.mrecords.fromrecords (reclist, dtype = None, shape = None, formats = None, names = None, titles = None, aligned = False, byteorder = None, fill_value = None, mask = nomask)
Creates a MaskedRecords from a list of records.
Parameters
----------
reclist : sequence
    A list of records. Each element of the sequence is first converted
    to a masked array if needed. If a 2D array is passed as argument, it is
    processed line by line
dtype : {None, dtype}, optional
    Data type descriptor.
shape : {None,int}, optional
    Number of records. If None, ``shape`` is defined from the shape of the
    first array in the list.
formats : {None, sequence}, optional
    Sequence of formats for each individual field. If None, the formats will
    be autodetected by inspecting the fields and selecting the highest dtype
    possible.
names : {None, sequence}, optional
    Sequence of the names of each field.
fill_value : {None, sequence}, optional
    Sequence of data to be used as filling values.
mask : {nomask, sequence}, optional.
    External mask to apply on the data.
Notes
-----
Lists of tuples should be preferred over lists of lists for faster processing.
Definition at line 547 of file mrecords.py.
fromtextfile()
numpy.ma.mrecords.fromtextfile (fname, delimiter = None, commentchar = '#', missingchar = '', varnames = None, vartypes = None, * , delimitor = np._NoValue)
Creates a mrecarray from data stored in the file `filename`.
Parameters
----------
fname : {file name/handle}
    Handle of an opened file.
delimiter : {None, string}, optional
    Alphanumeric character used to separate columns in the file.
    If None, any (group of) white spacestring(s) will be used.
commentchar : {'#', string}, optional
    Alphanumeric character used to mark the start of a comment.
missingchar : {'', string}, optional
    String indicating missing data, and used to create the masks.
varnames : {None, sequence}, optional
    Sequence of the variable names. If None, a list will be created from
    the first non empty line of the file.
vartypes : {None, sequence}, optional
    Sequence of the variables dtypes. If None, it will be estimated from
    the first non-commented line.
Ultra simple: the varnames are in the header, one line
Definition at line 669 of file mrecords.py.
References _guessvartypes(), fromarrays(), openfile(), and numpy.lib.shape_base.split().
openfile()
numpy.ma.mrecords.openfile (fname)
Opens the file handle of file `fname`.
Definition at line 649 of file mrecords.py.
Referenced by fromtextfile().
Variable Documentation
__all__
list numpy.ma.mrecords.__all__ private
Initial value:
=  [
    'MaskedRecords', 'mrecarray', 'fromarrays', 'fromrecords',
    'fromtextfile', 'addfield',
]
Definition at line 37 of file mrecords.py.
_byteorderconv
numpy.ma.mrecords._byteorderconv = np.core.records._byteorderconv protected
Definition at line 31 of file mrecords.py.
_check_fill_value
numpy.ma.mrecords._check_fill_value = ma.core._check_fill_value protected
Definition at line 34 of file mrecords.py.
mrecarray
numpy.ma.mrecords.mrecarray = MaskedRecords
Definition at line 496 of file mrecords.py.
reserved_fields
list numpy.ma.mrecords.reserved_fields = ['_data', '_mask', '_fieldmask', 'dtype']
Definition at line 42 of file mrecords.py.