Code Cloning Analysis: scipy.optimize._hessian_update_strategy.HessianUpdateStrategy Class Reference
scipy.optimize._hessian_update_strategy.HessianUpdateStrategy Class Reference
Public Member Functions
initialize (self, n, approx_type)
update (self, delta_x, delta_grad)
dot (self, p)
get_matrix (self)
Detailed Description
Interface for implementing Hessian update strategies.
Many optimization methods make use of Hessian (or inverse Hessian)
approximations, such as the quasi-Newton methods BFGS, SR1, L-BFGS.
Some of these  approximations, however, do not actually need to store
the entire matrix or can compute the internal matrix product with a
given vector in a very efficiently manner. This class serves as an
abstract interface between the optimization algorithm and the
quasi-Newton update strategies, giving freedom of implementation
to store and update the internal matrix as efficiently as possible.
Different choices of initialization and update procedure will result
in different quasi-Newton strategies.
Four methods should be implemented in derived classes: ``initialize``,
``update``, ``dot`` and ``get_matrix``.
Notes
-----
Any instance of a class that implements this interface,
can be accepted by the method ``minimize`` and used by
the compatible solvers to approximate the Hessian (or
inverse Hessian) used by the optimization algorithms.
Definition at line 11 of file _hessian_update_strategy.py.
Member Function Documentation
dot()
scipy.optimize._hessian_update_strategy.HessianUpdateStrategy.dot (self, p)
Compute the product of the internal matrix with the given vector.
Parameters
----------
p : array_like
    1-D array representing a vector.
Returns
-------
Hp : array
    1-D represents the result of multiplying the approximation matrix
    by vector p.
Reimplemented in scipy.optimize._hessian_update_strategy.FullHessianUpdateStrategy.
Definition at line 72 of file _hessian_update_strategy.py.
Referenced by scipy.sparse.linalg._interface.LinearOperator._rmatmat(), and scipy.optimize._hessian_update_strategy.BFGS._update_hessian().
get_matrix()
scipy.optimize._hessian_update_strategy.HessianUpdateStrategy.get_matrix (self)
Return current internal matrix.
Returns
-------
H : ndarray, shape (n, n)
    Dense matrix containing either the Hessian
    or its inverse (depending on how 'approx_type'
    is defined).
Reimplemented in scipy.optimize._hessian_update_strategy.FullHessianUpdateStrategy.
Definition at line 89 of file _hessian_update_strategy.py.
initialize()
scipy.optimize._hessian_update_strategy.HessianUpdateStrategy.initialize (self, n, approx_type)
Initialize internal matrix.
Allocate internal memory for storing and updating
the Hessian or its inverse.
Parameters
----------
n : int
    Problem dimension.
approx_type : {'hess', 'inv_hess'}
    Selects either the Hessian or the inverse Hessian.
    When set to 'hess' the Hessian will be stored and updated.
    When set to 'inv_hess' its inverse will be used instead.
Reimplemented in scipy.optimize._hessian_update_strategy.FullHessianUpdateStrategy.
Definition at line 36 of file _hessian_update_strategy.py.
update()
scipy.optimize._hessian_update_strategy.HessianUpdateStrategy.update (self, delta_x, delta_grad)
Update internal matrix.
Update Hessian matrix or its inverse (depending on how 'approx_type'
is defined) using information about the last evaluated points.
Parameters
----------
delta_x : ndarray
    The difference between two points the gradient
    function have been evaluated at: ``delta_x = x2 - x1``.
delta_grad : ndarray
    The difference between the gradients:
    ``delta_grad = grad(x2) - grad(x1)``.
Reimplemented in scipy.optimize._hessian_update_strategy.FullHessianUpdateStrategy.
Definition at line 54 of file _hessian_update_strategy.py.
Referenced by matplotlib.patches.Shadow.__init__(), matplotlib.backends.backend_macosx.FigureCanvasMac.blit(), matplotlib.backends.backend_macosx.FigureCanvasMac.draw(), and matplotlib.backends.backend_qt.FigureCanvasQT.draw().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/optimize/_hessian_update_strategy.py