Code Cloning Analysis: scipy.optimize.tests.test_linesearch.TestLineSearch Class Reference
scipy.optimize.tests.test_linesearch.TestLineSearch Class Reference
Public Member Functions
setup_method (self)
scalar_iter (self)
line_iter (self)
test_scalar_search_wolfe1 (self)
test_scalar_search_wolfe2 (self)
test_scalar_search_wolfe2_with_low_amax (self)
test_scalar_search_wolfe2_regression (self)
test_scalar_search_armijo (self)
test_line_search_wolfe1 (self)
test_line_search_wolfe2 (self)
test_line_search_wolfe2_bounds (self)
test_line_search_armijo (self)
test_armijo_terminate_1 (self)
test_wolfe_terminate (self)
Public Attributes
list scalar_funcs = []
list line_funcs = []
int N = 20
int fcount = 0
A = np.random.randn(self.N, self.N)
Protected Member Functions
_scalar_func_1 (self, s)
_scalar_func_2 (self, s)
_scalar_func_3 (self, s)
_line_func_1 (self, x)
_line_func_2 (self, x)
Detailed Description
Definition at line 54 of file test_linesearch.py.
Member Function Documentation
_line_func_1()
scipy.optimize.tests.test_linesearch.TestLineSearch._line_func_1 (self, x) protected
Definition at line 76 of file test_linesearch.py.
_line_func_2()
scipy.optimize.tests.test_linesearch.TestLineSearch._line_func_2 (self, x) protected
Definition at line 82 of file test_linesearch.py.
_scalar_func_1()
scipy.optimize.tests.test_linesearch.TestLineSearch._scalar_func_1 (self, s) protected
Definition at line 56 of file test_linesearch.py.
_scalar_func_2()
scipy.optimize.tests.test_linesearch.TestLineSearch._scalar_func_2 (self, s) protected
Definition at line 62 of file test_linesearch.py.
_scalar_func_3()
scipy.optimize.tests.test_linesearch.TestLineSearch._scalar_func_3 (self, s) protected
Definition at line 68 of file test_linesearch.py.
line_iter()
scipy.optimize.tests.test_linesearch.TestLineSearch.line_iter (self)
Definition at line 118 of file test_linesearch.py.
scalar_iter()
scipy.optimize.tests.test_linesearch.TestLineSearch.scalar_iter (self)
Definition at line 113 of file test_linesearch.py.
setup_method()
scipy.optimize.tests.test_linesearch.TestLineSearch.setup_method (self)
Definition at line 90 of file test_linesearch.py.
test_armijo_terminate_1()
scipy.optimize.tests.test_linesearch.TestLineSearch.test_armijo_terminate_1 (self)
Definition at line 284 of file test_linesearch.py.
test_line_search_armijo()
scipy.optimize.tests.test_linesearch.TestLineSearch.test_line_search_armijo (self)
Definition at line 269 of file test_linesearch.py.
test_line_search_wolfe1()
scipy.optimize.tests.test_linesearch.TestLineSearch.test_line_search_wolfe1 (self)
Definition at line 194 of file test_linesearch.py.
test_line_search_wolfe2()
scipy.optimize.tests.test_linesearch.TestLineSearch.test_line_search_wolfe2 (self)
Definition at line 216 of file test_linesearch.py.
test_line_search_wolfe2_bounds()
scipy.optimize.tests.test_linesearch.TestLineSearch.test_line_search_wolfe2_bounds (self)
Definition at line 241 of file test_linesearch.py.
test_scalar_search_armijo()
scipy.optimize.tests.test_linesearch.TestLineSearch.test_scalar_search_armijo (self)
Definition at line 186 of file test_linesearch.py.
test_scalar_search_wolfe1()
scipy.optimize.tests.test_linesearch.TestLineSearch.test_scalar_search_wolfe1 (self)
Definition at line 133 of file test_linesearch.py.
test_scalar_search_wolfe2()
scipy.optimize.tests.test_linesearch.TestLineSearch.test_scalar_search_wolfe2 (self)
Definition at line 145 of file test_linesearch.py.
test_scalar_search_wolfe2_regression()
scipy.optimize.tests.test_linesearch.TestLineSearch.test_scalar_search_wolfe2_regression (self)
Definition at line 166 of file test_linesearch.py.
test_scalar_search_wolfe2_with_low_amax()
scipy.optimize.tests.test_linesearch.TestLineSearch.test_scalar_search_wolfe2_with_low_amax (self)
Definition at line 155 of file test_linesearch.py.
test_wolfe_terminate()
scipy.optimize.tests.test_linesearch.TestLineSearch.test_wolfe_terminate (self)
Definition at line 297 of file test_linesearch.py.
Member Data Documentation
A
scipy.optimize.tests.test_linesearch.TestLineSearch.A = np.random.randn(self.N, self.N)
Definition at line 111 of file test_linesearch.py.
Referenced by scipy.signal._ltisys.StateSpace.__add__(), scipy.signal._ltisys.StateSpace.__init__(), scipy.sparse.linalg._matfuncs._ExpmPadeHelper.__init__(), scipy.signal._ltisys.StateSpace.__mul__(), scipy.signal._ltisys.StateSpace.__neg__(), scipy.signal._ltisys.StateSpace.__repr__(), scipy.signal._ltisys.StateSpace.__rmul__(), scipy.signal._ltisys.StateSpace._copy(), scipy.sparse.linalg.tests.test_onenormest.MatrixProductOperator._matmat(), scipy.sparse.linalg._eigen.tests.test_svds.CheckingLinearOperator._matvec(), scipy.sparse.linalg.tests.test_onenormest.MatrixProductOperator._matvec(), scipy.sparse.linalg._eigen.tests.test_svds.CheckingLinearOperator._rmatvec(), scipy.sparse.linalg.tests.test_onenormest.MatrixProductOperator._rmatvec(), and scipy.signal._ltisys.StateSpaceContinuous.to_discrete().
fcount
scipy.optimize.tests.test_linesearch.TestLineSearch.fcount = 0
Definition at line 94 of file test_linesearch.py.
line_funcs
list scipy.optimize.tests.test_linesearch.TestLineSearch.line_funcs = []
Definition at line 92 of file test_linesearch.py.
N
int scipy.optimize.tests.test_linesearch.TestLineSearch.N = 20
Definition at line 93 of file test_linesearch.py.
scalar_funcs
list scipy.optimize.tests.test_linesearch.TestLineSearch.scalar_funcs = []
Definition at line 91 of file test_linesearch.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/optimize/tests/test_linesearch.py