Code Cloning Analysis: scipy.linalg._expm_frechet Namespace Reference
scipy.linalg._expm_frechet Namespace Reference
Functions
expm_frechet (A, E, method=None, compute_expm=True, check_finite=True)
expm_frechet_block_enlarge (A, E)
_diff_pade3 (A, E, ident)
_diff_pade5 (A, E, ident)
_diff_pade7 (A, E, ident)
_diff_pade9 (A, E, ident)
expm_frechet_algo_64 (A, E)
vec (M)
expm_frechet_kronform (A, method=None, check_finite=True)
expm_cond (A, check_finite=True)
Variables
list __all__ = ['expm_frechet', 'expm_cond']
tuple ell_table_61
Detailed Description
Frechet derivative of the matrix exponential.
Function Documentation
_diff_pade3()
scipy.linalg._expm_frechet._diff_pade3 (A, E, ident) protected
Definition at line 166 of file _expm_frechet.py.
_diff_pade5()
scipy.linalg._expm_frechet._diff_pade5 (A, E, ident) protected
Definition at line 177 of file _expm_frechet.py.
_diff_pade7()
scipy.linalg._expm_frechet._diff_pade7 (A, E, ident) protected
Definition at line 191 of file _expm_frechet.py.
_diff_pade9()
scipy.linalg._expm_frechet._diff_pade9 (A, E, ident) protected
Definition at line 207 of file _expm_frechet.py.
expm_cond()
scipy.linalg._expm_frechet.expm_cond (A, check_finite = True)
Relative condition number of the matrix exponential in the Frobenius norm.
Parameters
----------
A : 2-D array_like
    Square input matrix with shape (N, N).
check_finite : bool, optional
    Whether to check that the input matrix contains only finite numbers.
    Disabling may give a performance gain, but may result in problems
    (crashes, non-termination) if the inputs do contain infinities or NaNs.
Returns
-------
kappa : float
    The relative condition number of the matrix exponential
    in the Frobenius norm
See Also
--------
expm : Compute the exponential of a matrix.
expm_frechet : Compute the Frechet derivative of the matrix exponential.
Notes
-----
A faster estimate for the condition number in the 1-norm
has been published but is not yet implemented in SciPy.
.. versionadded:: 0.14.0
Examples
--------
>>> import numpy as np
>>> from scipy.linalg import expm_cond
>>> A = np.array([[-0.3, 0.2, 0.6], [0.6, 0.3, -0.1], [-0.7, 1.2, 0.9]])
>>> k = expm_cond(A)
>>> k
1.7787805864469866
Definition at line 354 of file _expm_frechet.py.
References expm_frechet_kronform().
expm_frechet()
scipy.linalg._expm_frechet.expm_frechet (A, E, method = None, compute_expm = True, check_finite = True)
Frechet derivative of the matrix exponential of A in the direction E.
Parameters
----------
A : (N, N) array_like
    Matrix of which to take the matrix exponential.
E : (N, N) array_like
    Matrix direction in which to take the Frechet derivative.
method : str, optional
    Choice of algorithm. Should be one of
    - `SPS` (default)
    - `blockEnlarge`
compute_expm : bool, optional
    Whether to compute also `expm_A` in addition to `expm_frechet_AE`.
    Default is True.
check_finite : bool, optional
    Whether to check that the input matrix contains only finite numbers.
    Disabling may give a performance gain, but may result in problems
    (crashes, non-termination) if the inputs do contain infinities or NaNs.
Returns
-------
expm_A : ndarray
    Matrix exponential of A.
expm_frechet_AE : ndarray
    Frechet derivative of the matrix exponential of A in the direction E.
For ``compute_expm = False``, only `expm_frechet_AE` is returned.
See Also
--------
expm : Compute the exponential of a matrix.
Notes
-----
This section describes the available implementations that can be selected
by the `method` parameter. The default method is *SPS*.
Method *blockEnlarge* is a naive algorithm.
Method *SPS* is Scaling-Pade-Squaring [1]_.
It is a sophisticated implementation which should take
only about 3/8 as much time as the naive implementation.
The asymptotics are the same.
.. versionadded:: 0.13.0
References
----------
.. [1] Awad H. Al-Mohy and Nicholas J. Higham (2009)
       Computing the Frechet Derivative of the Matrix Exponential,
       with an application to Condition Number Estimation.
       SIAM Journal On Matrix Analysis and Applications.,
       30 (4). pp. 1639-1657. ISSN 1095-7162
Examples
--------
>>> import numpy as np
>>> from scipy import linalg
>>> rng = np.random.default_rng()
>>> A = rng.standard_normal((3, 3))
>>> E = rng.standard_normal((3, 3))
>>> expm_A, expm_frechet_AE = linalg.expm_frechet(A, E)
>>> expm_A.shape, expm_frechet_AE.shape
((3, 3), (3, 3))
Create a 6x6 matrix containg [[A, E], [0, A]]:
>>> M = np.zeros((6, 6))
>>> M[:3, :3] = A
>>> M[:3, 3:] = E
>>> M[3:, 3:] = A
>>> expm_M = linalg.expm(M)
>>> np.allclose(expm_A, expm_M[:3, :3])
True
>>> np.allclose(expm_frechet_AE, expm_M[:3, 3:])
True
Definition at line 8 of file _expm_frechet.py.
References expm_frechet_block_enlarge().
Referenced by expm_frechet_kronform().
expm_frechet_algo_64()
scipy.linalg._expm_frechet.expm_frechet_algo_64 (A, E)
Definition at line 226 of file _expm_frechet.py.
expm_frechet_block_enlarge()
scipy.linalg._expm_frechet.expm_frechet_block_enlarge (A, E)
This is a helper function, mostly for testing and profiling.
Return expm(A), frechet(A, E)
Definition at line 118 of file _expm_frechet.py.
Referenced by expm_frechet().
expm_frechet_kronform()
scipy.linalg._expm_frechet.expm_frechet_kronform (A, method = None, check_finite = True)
Construct the Kronecker form of the Frechet derivative of expm.
Parameters
----------
A : array_like with shape (N, N)
    Matrix to be expm'd.
method : str, optional
    Extra keyword to be passed to expm_frechet.
check_finite : bool, optional
    Whether to check that the input matrix contains only finite numbers.
    Disabling may give a performance gain, but may result in problems
    (crashes, non-termination) if the inputs do contain infinities or NaNs.
Returns
-------
K : 2-D ndarray with shape (N*N, N*N)
    Kronecker form of the Frechet derivative of the matrix exponential.
Notes
-----
This function is used to help compute the condition number
of the matrix exponential.
See Also
--------
expm : Compute a matrix exponential.
expm_frechet : Compute the Frechet derivative of the matrix exponential.
expm_cond : Compute the relative condition number of the matrix exponential
            in the Frobenius norm.
Definition at line 302 of file _expm_frechet.py.
References expm_frechet(), and vec().
Referenced by expm_cond().
vec()
scipy.linalg._expm_frechet.vec (M)
Stack columns of M to construct a single vector.
This is somewhat standard notation in linear algebra.
Parameters
----------
M : 2-D array_like
    Input matrix
Returns
-------
v : 1-D ndarray
    Output vector
Definition at line 282 of file _expm_frechet.py.
Referenced by expm_frechet_kronform().
Variable Documentation
__all__
list scipy.linalg._expm_frechet.__all__ = ['expm_frechet', 'expm_cond'] private
Definition at line 5 of file _expm_frechet.py.
ell_table_61
tuple scipy.linalg._expm_frechet.ell_table_61
Initial value:
=  (
        None,
        # 1
        2.11e-8,
        3.56e-4,
        1.08e-2,
        6.49e-2,
        2.00e-1,
        4.37e-1,
        7.83e-1,
        1.23e0,
        1.78e0,
        2.42e0,
        # 11
        3.13e0,
        3.90e0,
        4.74e0,
        5.63e0,
        6.56e0,
        7.52e0,
        8.53e0,
        9.56e0,
        1.06e1,
        1.17e1,
        )
Definition at line 135 of file _expm_frechet.py.