Code Cloning Analysis: numpy.ma.tests.test_subclassing.WrappedArray Class Reference
numpy.ma.tests.test_subclassing.WrappedArray Class Reference
Public Member Functions
__init__ (self, array, **attrs)
__repr__ (self)
__array__ (self)
__array_ufunc__ (self, ufunc, method, *inputs, **kwargs)
Public Attributes
attrs = attrs
Protected Attributes
_array = array
Static Private Attributes
tuple __slots__ = ('_array', 'attrs')
int __array_priority__ = 20
Detailed Description
Wrapping a MaskedArray rather than subclassing to test that
ufunc deferrals are commutative.
See: https://github.com/numpy/numpy/issues/15200)
Definition at line 151 of file test_subclassing.py.
Constructor & Destructor Documentation
__init__()
numpy.ma.tests.test_subclassing.WrappedArray.__init__ (self, array, ** attrs)
Definition at line 160 of file test_subclassing.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__array__()
numpy.ma.tests.test_subclassing.WrappedArray.__array__ (self)
Definition at line 167 of file test_subclassing.py.
Referenced by numpy.matrixlib.defmatrix.matrix.A(), numpy.matrixlib.defmatrix.matrix.A1(), numpy.core.defchararray.chararray.argsort(), numpy.matrixlib.defmatrix.matrix.tolist(), and numpy.ma.mrecords.MaskedRecords.view().
__array_ufunc__()
numpy.ma.tests.test_subclassing.WrappedArray.__array_ufunc__ (self, ufunc, method, * inputs, ** kwargs)
Definition at line 170 of file test_subclassing.py.
__repr__()
numpy.ma.tests.test_subclassing.WrappedArray.__repr__ (self)
Definition at line 164 of file test_subclassing.py.
Member Data Documentation
__array_priority__
int numpy.ma.tests.test_subclassing.WrappedArray.__array_priority__ = 20 static private
Definition at line 158 of file test_subclassing.py.
__slots__
tuple numpy.ma.tests.test_subclassing.WrappedArray.__slots__ = ('_array', 'attrs') static private
Definition at line 157 of file test_subclassing.py.
_array
numpy.ma.tests.test_subclassing.WrappedArray._array = array protected
Definition at line 161 of file test_subclassing.py.
attrs
numpy.ma.tests.test_subclassing.WrappedArray.attrs = attrs
Definition at line 162 of file test_subclassing.py.
Referenced by pandas.core.generic.NDFrame.__finalize__(), pandas.core.generic.NDFrame.empty(), pandas.io.pytables.GenericFixed.get_attrs(), pandas.io.pytables.Table.get_attrs(), pandas.io.pytables.Table.indexables(), pandas.io.html._HtmlFrameParser.parse_tables(), pandas.io.pytables.GenericFixed.read_array(), pandas.io.pytables.DataCol.set_attr(), pandas.io.pytables.IndexCol.set_attr(), pandas.io.pytables.GenericFixed.set_attrs(), pandas.io.pytables.Table.set_attrs(), pandas.io.pytables.Fixed.set_object_info(), pandas.io.pytables.DataCol.validate_attr(), and pandas.io.pytables.IndexCol.validate_col().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/ma/tests/test_subclassing.py