Code Cloning Analysis: numpy.core.arrayprint.SubArrayFormat Class Reference
numpy.core.arrayprint.SubArrayFormat Class Reference
Public Member Functions
__init__ (self, format_function, **options)
__call__ (self, a)
format_array (self, a)
Public Attributes
format_function = format_function
threshold = options['threshold']
edge_items = options['edgeitems']
str summary_insert = "..." if a.size > self.threshold else ""
Detailed Description
Definition at line 1341 of file arrayprint.py.
Constructor & Destructor Documentation
__init__()
numpy.core.arrayprint.SubArrayFormat.__init__ (self, format_function, ** options)
Definition at line 1342 of file arrayprint.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__call__()
numpy.core.arrayprint.SubArrayFormat.__call__ (self, a)
Definition at line 1347 of file arrayprint.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), and scipy.interpolate._fitpack2.SphereBivariateSpline.ev().
format_array()
numpy.core.arrayprint.SubArrayFormat.format_array (self, a)
Definition at line 1351 of file arrayprint.py.
Member Data Documentation
edge_items
numpy.core.arrayprint.SubArrayFormat.edge_items = options['edgeitems']
Definition at line 1345 of file arrayprint.py.
format_function
numpy.core.arrayprint.SubArrayFormat.format_function = format_function
Definition at line 1343 of file arrayprint.py.
summary_insert
str numpy.core.arrayprint.SubArrayFormat.summary_insert = "..." if a.size > self.threshold else ""
Definition at line 1348 of file arrayprint.py.
threshold
numpy.core.arrayprint.SubArrayFormat.threshold = options['threshold']
Definition at line 1344 of file arrayprint.py.
Referenced by sklearn.feature_selection._from_model.SelectFromModel._get_support_mask(), sklearn.feature_selection._variance_threshold.VarianceThreshold._get_support_mask(), sklearn.feature_selection._variance_threshold.VarianceThreshold.fit(), sklearn.cluster._birch._CFNode.insert_cf_subcluster(), sklearn.model_selection._classification_threshold.FixedThresholdClassifier.predict(), sklearn.feature_selection._from_model.SelectFromModel.threshold_(), and sklearn.preprocessing._data.Binarizer.transform().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/core/arrayprint.py