Code Cloning Analysis: matplotlib.pyplot Namespace Reference
matplotlib.pyplot Namespace Reference
Functions
Callable[[Callable[_P, _R]], Callable[_P, _R]] _copy_docstring_and_deprecators (Any method, Literal[None] func=None)
Callable[_P, _R] _copy_docstring_and_deprecators (Any method, Callable[_P, _R] func)
Callable[[Callable[_P, _R]], Callable[_P, _R]]|Callable[_P, _R] _copy_docstring_and_deprecators (Any method, Callable[_P, _R]|None func=None)
_add_pyplot_note (func, wrapped_func)
None _draw_all_if_interactive ()
None install_repl_displayhook ()
None uninstall_repl_displayhook ()
None set_loglevel (*args, **kwargs)
list[Artist] findobj (Artist|None o=None, Callable[[Artist], bool]|type[Artist]|None match=None, bool include_self=True)
type[matplotlib.backend_bases._Backend] _get_backend_mod ()
None switch_backend (str newbackend)
None _warn_if_gui_out_of_main_thread ()
new_figure_manager (*args, **kwargs)
draw_if_interactive (*args, **kwargs)
None show (*args, **kwargs)
bool isinteractive ()
AbstractContextManager ioff ()
AbstractContextManager ion ()
None pause (float interval)
None rc (str group, **kwargs)
AbstractContextManager[None] rc_context (dict[str, Any]|None rc=None, str|pathlib.Path|os.PathLike|None fname=None)
None rcdefaults ()
getp (obj, *args, **kwargs)
get (obj, *args, **kwargs)
setp (obj, *args, **kwargs)
ExitStack xkcd (float scale=1, float length=100, float randomness=2)
Figure figure (int|str|Figure|SubFigure|None num=None, ArrayLike|None figsize=None, float|None dpi=None, *, ColorType|None facecolor=None, ColorType|None edgecolor=None, bool frameon=True, type[Figure] FigureClass=Figure, bool clear=False, **kwargs)
Figures ##.
_auto_draw_if_interactive (fig, val)
Figure gcf ()
bool fignum_exists (int|str num)
list[int] get_fignums ()
list[Any] get_figlabels ()
FigureManagerBase|None get_current_fig_manager ()
int connect (str s, Callable[[Event], Any] func)
None disconnect (int cid)
None close (None|int|str|Figure|Literal["all"] fig=None)
None clf ()
None draw ()
None savefig (*args, **kwargs)
Legend figlegend (*args, **kwargs)
Putting things in figures ##.
matplotlib.axes.Axes axes (None|tuple[float, float, float, float] arg=None, **kwargs)
Axes ##.
None delaxes (matplotlib.axes.Axes|None ax=None)
None sca (Axes ax)
None cla ()
Axes subplot (*args, **kwargs)
More ways of creating Axes ##.
tuple[Figure, Axes] subplots (Literal[1] nrows=..., Literal[1] ncols=..., *, bool|Literal["none", "all", "row", "col"] sharex=..., bool|Literal["none", "all", "row", "col"] sharey=..., Literal[True] squeeze=..., Sequence[float]|None width_ratios=..., Sequence[float]|None height_ratios=..., dict[str, Any]|None subplot_kw=..., dict[str, Any]|None gridspec_kw=..., **fig_kw)
tuple[Figure, np.ndarray] subplots (int nrows=..., int ncols=..., *, bool|Literal["none", "all", "row", "col"] sharex=..., bool|Literal["none", "all", "row", "col"] sharey=..., Literal[False] squeeze, Sequence[float]|None width_ratios=..., Sequence[float]|None height_ratios=..., dict[str, Any]|None subplot_kw=..., dict[str, Any]|None gridspec_kw=..., **fig_kw)
tuple[Figure, Any] subplots (int nrows=..., int ncols=..., *, bool|Literal["none", "all", "row", "col"] sharex=..., bool|Literal["none", "all", "row", "col"] sharey=..., bool squeeze=..., Sequence[float]|None width_ratios=..., Sequence[float]|None height_ratios=..., dict[str, Any]|None subplot_kw=..., dict[str, Any]|None gridspec_kw=..., **fig_kw)
tuple[Figure, dict[str, matplotlib.axes.Axes]] subplot_mosaic (str mosaic, *, bool sharex=..., bool sharey=..., ArrayLike|None width_ratios=..., ArrayLike|None height_ratios=..., str empty_sentinel=..., dict[str, Any]|None subplot_kw=..., dict[str, Any]|None gridspec_kw=..., dict[str|tuple[str,...], dict[str, Any]]|None per_subplot_kw=..., **Any fig_kw)
tuple[Figure, dict[_T, matplotlib.axes.Axes]] subplot_mosaic (list[HashableList[_T]] mosaic, *, bool sharex=..., bool sharey=..., ArrayLike|None width_ratios=..., ArrayLike|None height_ratios=..., _T empty_sentinel=..., dict[str, Any]|None subplot_kw=..., dict[str, Any]|None gridspec_kw=..., dict[_T|tuple[_T,...], dict[str, Any]]|None per_subplot_kw=..., **Any fig_kw)
tuple[Figure, dict[Hashable, matplotlib.axes.Axes]] subplot_mosaic (list[HashableList[Hashable]] mosaic, *, bool sharex=..., bool sharey=..., ArrayLike|None width_ratios=..., ArrayLike|None height_ratios=..., Any empty_sentinel=..., dict[str, Any]|None subplot_kw=..., dict[str, Any]|None gridspec_kw=..., dict[Hashable|tuple[Hashable,...], dict[str, Any]]|None per_subplot_kw=..., **Any fig_kw)
tuple[Figure, dict[str, matplotlib.axes.Axes]]|\ tuple[Figure, dict[_T, matplotlib.axes.Axes]]|\ tuple[Figure, dict[Hashable, matplotlib.axes.Axes]] subplot_mosaic (str|list[HashableList[_T]]|list[HashableList[Hashable]] mosaic, *, bool sharex=False, bool sharey=False, ArrayLike|None width_ratios=None, ArrayLike|None height_ratios=None, Any empty_sentinel='.', dict[str, Any]|None subplot_kw=None, dict[str, Any]|None gridspec_kw=None, dict[str|tuple[str,...], dict[str, Any]]|dict[_T|tuple[_T,...], dict[str, Any]]|dict[Hashable|tuple[Hashable,...], dict[str, Any]]|None per_subplot_kw=None, **Any fig_kw)
matplotlib.axes.Axes subplot2grid (tuple[int, int] shape, tuple[int, int] loc, int rowspan=1, int colspan=1, Figure|None fig=None, **kwargs)
_AxesBase twinx (matplotlib.axes.Axes|None ax=None)
_AxesBase twiny (matplotlib.axes.Axes|None ax=None)
SubplotTool|None subplot_tool (Figure|None targetfig=None)
None box (bool|None on=None)
tuple[float, float] xlim (*args, **kwargs)
Axis ##.
tuple[float, float] ylim (*args, **kwargs)
tuple[list[Tick]|np.ndarray, list[Text]] xticks (ArrayLike|None ticks=None, Sequence[str]|None labels=None, *, bool minor=False, **kwargs)
tuple[list[Tick]|np.ndarray, list[Text]] yticks (ArrayLike|None ticks=None, Sequence[str]|None labels=None, *, bool minor=False, **kwargs)
tuple[list[Line2D], list[Text]] rgrids (ArrayLike|None radii=None, Sequence[str|Text]|None labels=None, float|None angle=None, str|None fmt=None, **kwargs)
tuple[list[Line2D], list[Text]] thetagrids (ArrayLike|None angles=None, Sequence[str|Text]|None labels=None, str|None fmt=None, **kwargs)
list[str] get_plot_commands ()
list[str] _get_pyplot_commands ()
Colorbar colorbar (ScalarMappable|ColorizingArtist|None mappable=None, matplotlib.axes.Axes|None cax=None, matplotlib.axes.Axes|Iterable[matplotlib.axes.Axes]|None ax=None, **kwargs)
Plotting part 1: manually generated functions and wrappers ##.
None clim (float|None vmin=None, float|None vmax=None)
Colormap get_cmap (Colormap|str|None name=None, int|None lut=None)
None set_cmap (Colormap|str cmap)
np.ndarray imread (str|pathlib.Path|BinaryIO fname, str|None format=None)
None imsave (str|os.PathLike|BinaryIO fname, ArrayLike arr, **kwargs)
AxesImage matshow (ArrayLike A, None|int fignum=None, **kwargs)
list[Line2D] polar (*args, **kwargs)
FigureImage figimage (ArrayLike X, int xo=0, int yo=0, float|None alpha=None, str|Normalize|None norm=None, str|Colormap|None cmap=None, float|None vmin=None, float|None vmax=None, Literal["upper", "lower"]|None origin=None, bool resize=False, *, Colorizer|None colorizer=None, **kwargs)
REMAINING CONTENT GENERATED BY boilerplate.py ##############.
Text figtext (float x, float y, str s, dict[str, Any]|None fontdict=None, **kwargs)
Axes gca ()
ColorizingArtist|None gci ()
list[tuple[int, int]] ginput (int n=1, float timeout=30, bool show_clicks=True, MouseButton mouse_add=MouseButton.LEFT, MouseButton mouse_pop=MouseButton.RIGHT, MouseButton mouse_stop=MouseButton.MIDDLE)
None subplots_adjust (float|None left=None, float|None bottom=None, float|None right=None, float|None top=None, float|None wspace=None, float|None hspace=None)
Text suptitle (str t, **kwargs)
None tight_layout (*, float pad=1.08, float|None h_pad=None, float|None w_pad=None, tuple[float, float, float, float]|None rect=None)
None|bool waitforbuttonpress (float timeout=-1)
tuple[np.ndarray, np.ndarray, LineCollection|Line2D, Line2D|None] acorr (ArrayLike x, *, data=None, **kwargs)
tuple[np.ndarray, np.ndarray, Line2D] angle_spectrum (ArrayLike x, float|None Fs=None, int|None Fc=None, Callable[[ArrayLike], ArrayLike]|ArrayLike|None window=None, int|None pad_to=None, Literal["default", "onesided", "twosided"]|None sides=None, *, data=None, **kwargs)
Annotation annotate (str text, tuple[float, float] xy, tuple[float, float]|None xytext=None, CoordsType xycoords="data", CoordsType|None textcoords=None, dict[str, Any]|None arrowprops=None, bool|None annotation_clip=None, **kwargs)
FancyArrow arrow (float x, float y, float dx, float dy, **kwargs)
None autoscale (bool enable=True, Literal["both", "x", "y"] axis="both", bool|None tight=None)
Line2D axhline (float y=0, float xmin=0, float xmax=1, **kwargs)
Rectangle axhspan (float ymin, float ymax, float xmin=0, float xmax=1, **kwargs)
tuple[float, float, float, float] axis (tuple[float, float, float, float]|bool|str|None arg=None, *, bool emit=True, **kwargs)
AxLine axline (tuple[float, float] xy1, tuple[float, float]|None xy2=None, *, float|None slope=None, **kwargs)
Line2D axvline (float x=0, float ymin=0, float ymax=1, **kwargs)
Rectangle axvspan (float xmin, float xmax, float ymin=0, float ymax=1, **kwargs)
BarContainer bar (float|ArrayLike x, float|ArrayLike height, float|ArrayLike width=0.8, float|ArrayLike|None bottom=None, *, Literal["center", "edge"] align="center", data=None, **kwargs)
Barbs barbs (*args, data=None, **kwargs)
BarContainer barh (float|ArrayLike y, float|ArrayLike width, float|ArrayLike height=0.8, float|ArrayLike|None left=None, *, Literal["center", "edge"] align="center", data=None, **kwargs)
list[Annotation] bar_label (BarContainer container, ArrayLike|None labels=None, *, str|Callable[[float], str] fmt="%g", Literal["center", "edge"] label_type="edge", float padding=0, **kwargs)
dict[str, Any] boxplot (ArrayLike|Sequence[ArrayLike] x, bool|None notch=None, str|None sym=None, bool|None vert=None, Literal["vertical", "horizontal"] orientation="vertical", float|tuple[float, float]|None whis=None, ArrayLike|None positions=None, float|ArrayLike|None widths=None, bool|None patch_artist=None, int|None bootstrap=None, ArrayLike|None usermedians=None, ArrayLike|None conf_intervals=None, bool|None meanline=None, bool|None showmeans=None, bool|None showcaps=None, bool|None showbox=None, bool|None showfliers=None, dict[str, Any]|None boxprops=None, Sequence[str]|None tick_labels=None, dict[str, Any]|None flierprops=None, dict[str, Any]|None medianprops=None, dict[str, Any]|None meanprops=None, dict[str, Any]|None capprops=None, dict[str, Any]|None whiskerprops=None, bool manage_ticks=True, bool autorange=False, float|None zorder=None, float|ArrayLike|None capwidths=None, Sequence[str]|None label=None, *, data=None)
PolyCollection broken_barh (Sequence[tuple[float, float]] xranges, tuple[float, float] yrange, *, data=None, **kwargs)
list[Text] clabel (ContourSet CS, ArrayLike|None levels=None, **kwargs)
tuple[np.ndarray, np.ndarray] cohere (ArrayLike x, ArrayLike y, int NFFT=256, float Fs=2, int Fc=0, Literal["none", "mean", "linear"]|Callable[[ArrayLike], ArrayLike] detrend=mlab.detrend_none, Callable[[ArrayLike], ArrayLike]|ArrayLike window=mlab.window_hanning, int noverlap=0, int|None pad_to=None, Literal["default", "onesided", "twosided"] sides="default", bool|None scale_by_freq=None, *, data=None, **kwargs)
QuadContourSet contour (*args, data=None, **kwargs)
QuadContourSet contourf (*args, data=None, **kwargs)
tuple[np.ndarray, np.ndarray]|tuple[np.ndarray, np.ndarray, Line2D] csd (ArrayLike x, ArrayLike y, int|None NFFT=None, float|None Fs=None, int|None Fc=None, Literal["none", "mean", "linear"]|Callable[[ArrayLike], ArrayLike]|None detrend=None, Callable[[ArrayLike], ArrayLike]|ArrayLike|None window=None, int|None noverlap=None, int|None pad_to=None, Literal["default", "onesided", "twosided"]|None sides=None, bool|None scale_by_freq=None, bool|None return_line=None, *, data=None, **kwargs)
Line2D ecdf (ArrayLike x, ArrayLike|None weights=None, *, bool complementary=False, Literal["vertical", "horizontal"] orientation="vertical", bool compress=False, data=None, **kwargs)
ErrorbarContainer errorbar (float|ArrayLike x, float|ArrayLike y, float|ArrayLike|None yerr=None, float|ArrayLike|None xerr=None, str fmt="", ColorType|None ecolor=None, float|None elinewidth=None, float|None capsize=None, bool barsabove=False, bool|ArrayLike lolims=False, bool|ArrayLike uplims=False, bool|ArrayLike xlolims=False, bool|ArrayLike xuplims=False, int|tuple[int, int] errorevery=1, float|None capthick=None, *, data=None, **kwargs)
EventCollection eventplot (ArrayLike|Sequence[ArrayLike] positions, Literal["horizontal", "vertical"] orientation="horizontal", float|Sequence[float] lineoffsets=1, float|Sequence[float] linelengths=1, float|Sequence[float]|None linewidths=None, ColorType|Sequence[ColorType]|None colors=None, float|Sequence[float]|None alpha=None, LineStyleType|Sequence[LineStyleType] linestyles="solid", *, data=None, **kwargs)
list[Polygon] fill (*args, data=None, **kwargs)
FillBetweenPolyCollection fill_between (ArrayLike x, ArrayLike|float y1, ArrayLike|float y2=0, Sequence[bool]|None where=None, bool interpolate=False, Literal["pre", "post", "mid"]|None step=None, *, data=None, **kwargs)
FillBetweenPolyCollection fill_betweenx (ArrayLike y, ArrayLike|float x1, ArrayLike|float x2=0, Sequence[bool]|None where=None, Literal["pre", "post", "mid"]|None step=None, bool interpolate=False, *, data=None, **kwargs)
None grid (bool|None visible=None, Literal["major", "minor", "both"] which="major", Literal["both", "x", "y"] axis="both", **kwargs)
PolyCollection hexbin (ArrayLike x, ArrayLike y, ArrayLike|None C=None, int|tuple[int, int] gridsize=100, Literal["log"]|int|Sequence[float]|None bins=None, Literal["linear", "log"] xscale="linear", Literal["linear", "log"] yscale="linear", tuple[float, float, float, float]|None extent=None, str|Colormap|None cmap=None, str|Normalize|None norm=None, float|None vmin=None, float|None vmax=None, float|None alpha=None, float|None linewidths=None, Literal["face", "none"]|ColorType edgecolors="face", Callable[[np.ndarray|list[float]], float] reduce_C_function=np.mean, int|None mincnt=None, bool marginals=False, Colorizer|None colorizer=None, *, data=None, **kwargs)
tuple[ np.ndarray|list[np.ndarray], np.ndarray, BarContainer|Polygon|list[BarContainer|Polygon],] hist (ArrayLike|Sequence[ArrayLike] x, int|Sequence[float]|str|None bins=None, tuple[float, float]|None range=None, bool density=False, ArrayLike|None weights=None, bool|float cumulative=False, ArrayLike|float|None bottom=None, Literal["bar", "barstacked", "step", "stepfilled"] histtype="bar", Literal["left", "mid", "right"] align="mid", Literal["vertical", "horizontal"] orientation="vertical", float|None rwidth=None, bool log=False, ColorType|Sequence[ColorType]|None color=None, str|Sequence[str]|None label=None, bool stacked=False, *, data=None, **kwargs)
StepPatch stairs (ArrayLike values, ArrayLike|None edges=None, *, Literal["vertical", "horizontal"] orientation="vertical", float|ArrayLike|None baseline=0, bool fill=False, data=None, **kwargs)
tuple[np.ndarray, np.ndarray, np.ndarray, QuadMesh] hist2d (ArrayLike x, ArrayLike y, None|int|tuple[int, int]|ArrayLike|tuple[ArrayLike, ArrayLike] bins=10, ArrayLike|None range=None, bool density=False, ArrayLike|None weights=None, float|None cmin=None, float|None cmax=None, *, data=None, **kwargs)
LineCollection hlines (float|ArrayLike y, float|ArrayLike xmin, float|ArrayLike xmax, ColorType|Sequence[ColorType]|None colors=None, LineStyleType linestyles="solid", str label="", *, data=None, **kwargs)
AxesImage imshow (ArrayLike|PIL.Image.Image X, str|Colormap|None cmap=None, str|Normalize|None norm=None, *, Literal["equal", "auto"]|float|None aspect=None, str|None interpolation=None, float|ArrayLike|None alpha=None, float|None vmin=None, float|None vmax=None, Colorizer|None colorizer=None, Literal["upper", "lower"]|None origin=None, tuple[float, float, float, float]|None extent=None, Literal["data", "rgba", "auto"]|None interpolation_stage=None, bool filternorm=True, float filterrad=4.0, bool|None resample=None, str|None url=None, data=None, **kwargs)
Legend legend (*args, **kwargs)
None locator_params (Literal["both", "x", "y"] axis="both", bool|None tight=None, **kwargs)
list[Line2D] loglog (*args, **kwargs)
tuple[np.ndarray, np.ndarray, Line2D] magnitude_spectrum (ArrayLike x, float|None Fs=None, int|None Fc=None, Callable[[ArrayLike], ArrayLike]|ArrayLike|None window=None, int|None pad_to=None, Literal["default", "onesided", "twosided"]|None sides=None, Literal["default", "linear", "dB"]|None scale=None, *, data=None, **kwargs)
tuple[float, float]|None margins (*float margins, float|None x=None, float|None y=None, bool|None tight=True)
None minorticks_off ()
None minorticks_on ()
Collection pcolor (*ArrayLike args, Literal["flat", "nearest", "auto"]|None shading=None, float|None alpha=None, str|Normalize|None norm=None, str|Colormap|None cmap=None, float|None vmin=None, float|None vmax=None, Colorizer|None colorizer=None, data=None, **kwargs)
QuadMesh pcolormesh (*ArrayLike args, float|None alpha=None, str|Normalize|None norm=None, str|Colormap|None cmap=None, float|None vmin=None, float|None vmax=None, Colorizer|None colorizer=None, Literal["flat", "nearest", "gouraud", "auto"]|None shading=None, bool antialiased=False, data=None, **kwargs)
tuple[np.ndarray, np.ndarray, Line2D] phase_spectrum (ArrayLike x, float|None Fs=None, int|None Fc=None, Callable[[ArrayLike], ArrayLike]|ArrayLike|None window=None, int|None pad_to=None, Literal["default", "onesided", "twosided"]|None sides=None, *, data=None, **kwargs)
tuple[list[Wedge], list[Text]]|tuple[list[Wedge], list[Text], list[Text]] pie (ArrayLike x, ArrayLike|None explode=None, Sequence[str]|None labels=None, ColorType|Sequence[ColorType]|None colors=None, str|Callable[[float], str]|None autopct=None, float pctdistance=0.6, bool shadow=False, float|None labeldistance=1.1, float startangle=0, float radius=1, bool counterclock=True, dict[str, Any]|None wedgeprops=None, dict[str, Any]|None textprops=None, tuple[float, float] center=(0, 0), bool frame=False, bool rotatelabels=False, *, bool normalize=True, str|Sequence[str]|None hatch=None, data=None)
list[Line2D] plot (*float|ArrayLike|str args, bool scalex=True, bool scaley=True, data=None, **kwargs)
list[Line2D] plot_date (ArrayLike x, ArrayLike y, str fmt="o", str|datetime.tzinfo|None tz=None, bool xdate=True, bool ydate=False, *, data=None, **kwargs)
tuple[np.ndarray, np.ndarray]|tuple[np.ndarray, np.ndarray, Line2D] psd (ArrayLike x, int|None NFFT=None, float|None Fs=None, int|None Fc=None, Literal["none", "mean", "linear"]|Callable[[ArrayLike], ArrayLike]|None detrend=None, Callable[[ArrayLike], ArrayLike]|ArrayLike|None window=None, int|None noverlap=None, int|None pad_to=None, Literal["default", "onesided", "twosided"]|None sides=None, bool|None scale_by_freq=None, bool|None return_line=None, *, data=None, **kwargs)
Quiver quiver (*args, data=None, **kwargs)
QuiverKey quiverkey (Quiver Q, float X, float Y, float U, str label, **kwargs)
PathCollection scatter (float|ArrayLike x, float|ArrayLike y, float|ArrayLike|None s=None, ArrayLike|Sequence[ColorType]|ColorType|None c=None, MarkerType|None marker=None, str|Colormap|None cmap=None, str|Normalize|None norm=None, float|None vmin=None, float|None vmax=None, float|None alpha=None, float|Sequence[float]|None linewidths=None, *, Literal["face", "none"]|ColorType|Sequence[ColorType]|None edgecolors=None, Colorizer|None colorizer=None, bool plotnonfinite=False, data=None, **kwargs)
list[Line2D] semilogx (*args, **kwargs)
list[Line2D] semilogy (*args, **kwargs)
tuple[np.ndarray, np.ndarray, np.ndarray, AxesImage] specgram (ArrayLike x, int|None NFFT=None, float|None Fs=None, int|None Fc=None, Literal["none", "mean", "linear"]|Callable[[ArrayLike], ArrayLike]|None detrend=None, Callable[[ArrayLike], ArrayLike]|ArrayLike|None window=None, int|None noverlap=None, str|Colormap|None cmap=None, tuple[float, float]|None xextent=None, int|None pad_to=None, Literal["default", "onesided", "twosided"]|None sides=None, bool|None scale_by_freq=None, Literal["default", "psd", "magnitude", "angle", "phase"]|None mode=None, Literal["default", "linear", "dB"]|None scale=None, float|None vmin=None, float|None vmax=None, *, data=None, **kwargs)
AxesImage spy (ArrayLike Z, float|Literal["present"] precision=0, str|None marker=None, float|None markersize=None, Literal["equal", "auto"]|float|None aspect="equal", Literal["upper", "lower"] origin="upper", **kwargs)
stackplot (x, *args, labels=(), colors=None, hatch=None, baseline="zero", data=None, **kwargs)
StemContainer stem (*ArrayLike|str args, str|None linefmt=None, str|None markerfmt=None, str|None basefmt=None, float bottom=0, str|None label=None, Literal["vertical", "horizontal"] orientation="vertical", data=None)
list[Line2D] step (ArrayLike x, ArrayLike y, *args, Literal["pre", "post", "mid"] where="pre", data=None, **kwargs)
streamplot (x, y, u, v, density=1, linewidth=None, color=None, cmap=None, norm=None, arrowsize=1, arrowstyle="-|>", minlength=0.1, transform=None, zorder=None, start_points=None, maxlength=4.0, integration_direction="both", broken_streamlines=True, *, data=None)
table (cellText=None, cellColours=None, cellLoc="right", colWidths=None, rowLabels=None, rowColours=None, rowLoc="left", colLabels=None, colColours=None, colLoc="center", loc="bottom", bbox=None, edges="closed", **kwargs)
Text text (float x, float y, str s, dict[str, Any]|None fontdict=None, **kwargs)
None tick_params (Literal["both", "x", "y"] axis="both", **kwargs)
None ticklabel_format (*, Literal["both", "x", "y"] axis="both", Literal["", "sci", "scientific", "plain"]|None style=None, tuple[int, int]|None scilimits=None, bool|float|None useOffset=None, bool|None useLocale=None, bool|None useMathText=None)
tricontour (*args, **kwargs)
tricontourf (*args, **kwargs)
tripcolor (*args, alpha=1.0, norm=None, cmap=None, vmin=None, vmax=None, shading="flat", facecolors=None, **kwargs)
triplot (*args, **kwargs)
dict[str, Collection] violinplot (ArrayLike|Sequence[ArrayLike] dataset, ArrayLike|None positions=None, bool|None vert=None, Literal["vertical", "horizontal"] orientation="vertical", float|ArrayLike widths=0.5, bool showmeans=False, bool showextrema=True, bool showmedians=False, Sequence[float|Sequence[float]]|None quantiles=None, int points=100, Literal["scott", "silverman"]|float|Callable[[GaussianKDE], float]|None bw_method=None, Literal["both", "low", "high"] side="both", *, data=None)
LineCollection vlines (float|ArrayLike x, float|ArrayLike ymin, float|ArrayLike ymax, ColorType|Sequence[ColorType]|None colors=None, LineStyleType linestyles="solid", str label="", *, data=None, **kwargs)
tuple[np.ndarray, np.ndarray, LineCollection|Line2D, Line2D|None] xcorr (ArrayLike x, ArrayLike y, bool normed=True, Callable[[ArrayLike], ArrayLike] detrend=mlab.detrend_none, bool usevlines=True, int maxlags=10, *, data=None, **kwargs)
None sci (ColorizingArtist im)
Text title (str label, dict[str, Any]|None fontdict=None, Literal["left", "center", "right"]|None loc=None, float|None pad=None, *, float|None y=None, **kwargs)
Text xlabel (str xlabel, dict[str, Any]|None fontdict=None, float|None labelpad=None, *, Literal["left", "center", "right"]|None loc=None, **kwargs)
Text ylabel (str ylabel, dict[str, Any]|None fontdict=None, float|None labelpad=None, *, Literal["bottom", "center", "top"]|None loc=None, **kwargs)
None xscale (str|ScaleBase value, **kwargs)
None yscale (str|ScaleBase value, **kwargs)
None autumn ()
None bone ()
None cool ()
None copper ()
None flag ()
None gray ()
None hot ()
None hsv ()
None jet ()
None pink ()
None prism ()
None spring ()
None summer ()
None winter ()
None magma ()
None inferno ()
None plasma ()
None viridis ()
None nipy_spectral ()
Variables
_P = ParamSpec('_P')
_R = TypeVar('_R')
_T = TypeVar('_T')
_log = logging.getLogger(__name__)
colormaps = _colormaps
color_sequences = _color_sequences
list _NO_PYPLOT_NOTE
_ReplDisplayHook = Enum("_ReplDisplayHook", ["NONE", "PLAIN", "IPYTHON"])
Global ##.
_REPL_DISPLAYHOOK = _ReplDisplayHook.NONE
draw_all = _pylab_helpers.Gcf.draw_all
type _backend_mod = None
__doc__
requested_backend = rcParams._get_backend_or_none()
available_backends = backend_registry.list_builtin(BackendFilter.INTERACTIVE)
Detailed Description
`matplotlib.pyplot` is a state-based interface to matplotlib. It provides
an implicit,  MATLAB-like, way of plotting.  It also opens figures on your
screen, and acts as the figure GUI manager.
pyplot is mainly intended for interactive plots and simple cases of
programmatic plot generation::
    import numpy as np
    import matplotlib.pyplot as plt
    x = np.arange(0, 5, 0.1)
    y = np.sin(x)
    plt.plot(x, y)
    plt.show()
The explicit object-oriented API is recommended for complex plots, though
pyplot is still usually used to create the figure and often the Axes in the
figure. See `.pyplot.figure`, `.pyplot.subplots`, and
`.pyplot.subplot_mosaic` to create figures, and
:doc:`Axes API </api/axes_api>` for the plotting methods on an Axes::
    import numpy as np
    import matplotlib.pyplot as plt
    x = np.arange(0, 5, 0.1)
    y = np.sin(x)
    fig, ax = plt.subplots()
    ax.plot(x, y)
    plt.show()
See :ref:`api_interfaces` for an explanation of the tradeoffs between the
implicit and explicit interfaces.
Function Documentation
_add_pyplot_note()
matplotlib.pyplot._add_pyplot_note (func, wrapped_func) protected
Add a note to the docstring of *func* that it is a pyplot wrapper.
The note is added to the "Notes" section of the docstring. If that does
not exist, a "Notes" section is created. In numpydoc, the "Notes"
section is the third last possible section, only potentially followed by
"References" and "Examples".
Definition at line 209 of file pyplot.py.
_auto_draw_if_interactive()
matplotlib.pyplot._auto_draw_if_interactive (fig, val) protected
An internal helper function for making sure that auto-redrawing
works as intended in the plain python repl.
Parameters
----------
fig : Figure
    A figure object which is assumed to be associated with a canvas
Definition at line 1074 of file pyplot.py.
References matplotlib.is_interactive().
_copy_docstring_and_deprecators() [1/3]
Callable[_P, _R] matplotlib.pyplot._copy_docstring_and_deprecators (Any method, Callable[_P, _R] func) protected
Definition at line 172 of file pyplot.py.
_copy_docstring_and_deprecators() [2/3]
Callable[[Callable[_P, _R]], Callable[_P, _R]] | Callable[_P, _R] matplotlib.pyplot._copy_docstring_and_deprecators (Any method, Callable[_P, _R] | None func = None) protected
Definition at line 176 of file pyplot.py.
_copy_docstring_and_deprecators() [3/3]
Callable[[Callable[_P, _R]], Callable[_P, _R]] matplotlib.pyplot._copy_docstring_and_deprecators (Any method, Literal[None] func = None) protected
Definition at line 165 of file pyplot.py.
_draw_all_if_interactive()
None matplotlib.pyplot._draw_all_if_interactive () protected
Definition at line 277 of file pyplot.py.
_get_backend_mod()
type[matplotlib.backend_bases._Backend] matplotlib.pyplot._get_backend_mod () protected
Ensure that a backend is selected and return it.
This is currently private, but may be made public in the future.
Definition at line 359 of file pyplot.py.
References switch_backend().
Referenced by draw_if_interactive(), new_figure_manager(), show(), and switch_backend().
_get_pyplot_commands()
list[str] matplotlib.pyplot._get_pyplot_commands () protected
Definition at line 2504 of file pyplot.py.
_warn_if_gui_out_of_main_thread()
None matplotlib.pyplot._warn_if_gui_out_of_main_thread () protected
Definition at line 526 of file pyplot.py.
acorr()
tuple[np.ndarray, np.ndarray, LineCollection | Line2D, Line2D | None] matplotlib.pyplot.acorr (ArrayLike x, * , data = None, ** kwargs)
Definition at line 2855 of file pyplot.py.
angle_spectrum()
tuple[np.ndarray, np.ndarray, Line2D] matplotlib.pyplot.angle_spectrum (ArrayLike x, float | None Fs = None, int | None Fc = None, Callable[[ArrayLike], ArrayLike] | ArrayLike | None window = None, int | None pad_to = None, Literal["default", "onesided", "twosided"] | None sides = None, * , data = None, ** kwargs)
Definition at line 2863 of file pyplot.py.
annotate()
Annotation matplotlib.pyplot.annotate (str text, tuple[float, float] xy, tuple[float, float] | None xytext = None, CoordsType xycoords = "data", CoordsType | None textcoords = None, dict[str, Any] | None arrowprops = None, bool | None annotation_clip = None, ** kwargs)
Definition at line 2888 of file pyplot.py.
arrow()
FancyArrow matplotlib.pyplot.arrow (float x, float y, float dx, float dy, ** kwargs)
Definition at line 2912 of file pyplot.py.
autoscale()
None matplotlib.pyplot.autoscale (bool enable = True, Literal["both", "x", "y"] axis = "both", bool | None tight = None)
Definition at line 2918 of file pyplot.py.
autumn()
None matplotlib.pyplot.autumn ()
Set the colormap to 'autumn'.
This changes the default colormap as well as the colormap of the current
image if there is one. See ``help(colormaps)`` for more information.
Definition at line 4440 of file pyplot.py.
References set_cmap().
axes()
matplotlib.axes.Axes matplotlib.pyplot.axes (None | tuple[float, float, float, float] arg = None, ** kwargs)
Axes ##.
Add an Axes to the current figure and make it the current Axes.
Call signatures::
    plt.axes()
    plt.axes(rect, projection=None, polar=False, **kwargs)
    plt.axes(ax)
Parameters
----------
arg : None or 4-tuple
    The exact behavior of this function depends on the type:
    - *None*: A new full window Axes is added using
      ``subplot(**kwargs)``.
    - 4-tuple of floats *rect* = ``(left, bottom, width, height)``.
      A new Axes is added with dimensions *rect* in normalized
      (0, 1) units using `~.Figure.add_axes` on the current figure.
projection : {None, 'aitoff', 'hammer', 'lambert', 'mollweide', \
'polar', 'rectilinear', str}, optional
    The projection type of the `~.axes.Axes`. *str* is the name of
    a custom projection, see `~matplotlib.projections`. The default
    None results in a 'rectilinear' projection.
polar : bool, default: False
    If True, equivalent to projection='polar'.
sharex, sharey : `~matplotlib.axes.Axes`, optional
    Share the x or y `~matplotlib.axis` with sharex and/or sharey.
    The axis will have the same limits, ticks, and scale as the axis
    of the shared Axes.
label : str
    A label for the returned Axes.
Returns
-------
`~.axes.Axes`, or a subclass of `~.axes.Axes`
    The returned Axes class depends on the projection used. It is
    `~.axes.Axes` if rectilinear projection is used and
    `.projections.polar.PolarAxes` if polar projection is used.
Other Parameters
----------------
**kwargs
    This method also takes the keyword arguments for
    the returned Axes class. The keyword arguments for the
    rectilinear Axes class `~.axes.Axes` can be found in
    the following table but there might also be other keyword
    arguments if another projection is used, see the actual Axes
    class.
    %(Axes:kwdoc)s
See Also
--------
.Figure.add_axes
.pyplot.subplot
.Figure.add_subplot
.Figure.subplots
.pyplot.subplots
Examples
--------
::
    # Creating a new full window Axes
    plt.axes()
    # Creating a new Axes with specified dimensions and a grey background
    plt.axes((left, bottom, width, height), facecolor='grey')
Definition at line 1271 of file pyplot.py.
References gcf().
axhline()
Line2D matplotlib.pyplot.axhline (float y = 0, float xmin = 0, float xmax = 1, ** kwargs)
Definition at line 2928 of file pyplot.py.
axhspan()
Rectangle matplotlib.pyplot.axhspan (float ymin, float ymax, float xmin = 0, float xmax = 1, ** kwargs)
Definition at line 2934 of file pyplot.py.
axis()
tuple[float, float, float, float] matplotlib.pyplot.axis (tuple[float, float, float, float] | bool | str | None arg = None, * , bool emit = True, ** kwargs)
Definition at line 2942 of file pyplot.py.
axline()
AxLine matplotlib.pyplot.axline (tuple[float, float] xy1, tuple[float, float] | None xy2 = None, * , float | None slope = None, ** kwargs)
Definition at line 2954 of file pyplot.py.
axvline()
Line2D matplotlib.pyplot.axvline (float x = 0, float ymin = 0, float ymax = 1, ** kwargs)
Definition at line 2966 of file pyplot.py.
axvspan()
Rectangle matplotlib.pyplot.axvspan (float xmin, float xmax, float ymin = 0, float ymax = 1, ** kwargs)
Definition at line 2972 of file pyplot.py.
bar()
BarContainer matplotlib.pyplot.bar (float | ArrayLike x, float | ArrayLike height, float | ArrayLike width = 0.8, float | ArrayLike | None bottom = None, * , Literal["center", "edge"] align = "center", data = None, ** kwargs)
Definition at line 2980 of file pyplot.py.
bar_label()
list[Annotation] matplotlib.pyplot.bar_label (BarContainer container, ArrayLike | None labels = None, * , str | Callable[[float], str] fmt = "%g", Literal["center", "edge"] label_type = "edge", float padding = 0, ** kwargs)
Definition at line 3032 of file pyplot.py.
barbs()
Barbs matplotlib.pyplot.barbs (* args, data = None, ** kwargs)
Definition at line 3003 of file pyplot.py.
barh()
BarContainer matplotlib.pyplot.barh (float | ArrayLike y, float | ArrayLike width, float | ArrayLike height = 0.8, float | ArrayLike | None left = None, * , Literal["center", "edge"] align = "center", data = None, ** kwargs)
Definition at line 3009 of file pyplot.py.
bone()
None matplotlib.pyplot.bone ()
Set the colormap to 'bone'.
This changes the default colormap as well as the colormap of the current
image if there is one. See ``help(colormaps)`` for more information.
Definition at line 4451 of file pyplot.py.
References set_cmap().
box()
None matplotlib.pyplot.box (bool | None on = None)
Turn the Axes box on or off on the current Axes.
Parameters
----------
on : bool or None
    The new `~matplotlib.axes.Axes` box state. If ``None``, toggle
    the state.
See Also
--------
:meth:`matplotlib.axes.Axes.set_frame_on`
:meth:`matplotlib.axes.Axes.get_frame_on`
Definition at line 2069 of file pyplot.py.
boxplot()
dict[str, Any] matplotlib.pyplot.boxplot (ArrayLike | Sequence[ArrayLike] x, bool | None notch = None, str | None sym = None, bool | None vert = None, Literal["vertical", "horizontal"] orientation = "vertical", float | tuple[float, float] | None whis = None, ArrayLike | None positions = None, float | ArrayLike | None widths = None, bool | None patch_artist = None, int | None bootstrap = None, ArrayLike | None usermedians = None, ArrayLike | None conf_intervals = None, bool | None meanline = None, bool | None showmeans = None, bool | None showcaps = None, bool | None showbox = None, bool | None showfliers = None, dict[str, Any] | None boxprops = None, Sequence[str] | None tick_labels = None, dict[str, Any] | None flierprops = None, dict[str, Any] | None medianprops = None, dict[str, Any] | None meanprops = None, dict[str, Any] | None capprops = None, dict[str, Any] | None whiskerprops = None, bool manage_ticks = True, bool autorange = False, float | None zorder = None, float | ArrayLike | None capwidths = None, Sequence[str] | None label = None, * , data = None)
Definition at line 3053 of file pyplot.py.
broken_barh()
PolyCollection matplotlib.pyplot.broken_barh (Sequence[tuple[float, float]] xranges, tuple[float, float] yrange, * , data = None, ** kwargs)
Definition at line 3122 of file pyplot.py.
cla()
None matplotlib.pyplot.cla ()
Clear the current Axes.
Definition at line 1381 of file pyplot.py.
References cla().
Referenced by cla().
clabel()
list[Text] matplotlib.pyplot.clabel (ContourSet CS, ArrayLike | None levels = None, ** kwargs)
Definition at line 3136 of file pyplot.py.
clf()
None matplotlib.pyplot.clf ()
Clear the current figure.
Definition at line 1221 of file pyplot.py.
References gcf().
clim()
None matplotlib.pyplot.clim (float | None vmin = None, float | None vmax = None)
Set the color limits of the current image.
If either *vmin* or *vmax* is None, the image min/max respectively
will be used for color scaling.
If you want to set the clim of multiple images, use
`~.ScalarMappable.set_clim` on every image, for example::
  for im in gca().get_images():
      im.set_clim(0, 0.5)
Definition at line 2538 of file pyplot.py.
close()
None matplotlib.pyplot.close (None | int | str | Figure | Literal["all"] fig = None)
Close a figure window, and unregister it from pyplot.
Parameters
----------
fig : None or int or str or `.Figure`
    The figure to close. There are a number of ways to specify this:
    - *None*: the current figure
    - `.Figure`: the given `.Figure` instance
    - ``int``: a figure number
    - ``str``: a figure name
    - 'all': all figures
Notes
-----
pyplot maintains a reference to figures created with `figure()`. When
work on the figure is completed, it should be closed, i.e. deregistered
from pyplot, to free its memory (see also :rc:figure.max_open_warning).
Closing a figure window created by `show()` automatically deregisters the
figure. For all other use cases, most prominently `savefig()` without
`show()`, the figure must be deregistered explicitly using `close()`.
Definition at line 1171 of file pyplot.py.
References get_figlabels(), and get_fignums().
cohere()
tuple[np.ndarray, np.ndarray] matplotlib.pyplot.cohere (ArrayLike x, ArrayLike y, int NFFT = 256, float Fs = 2, int Fc = 0, Literal["none", "mean", "linear"] | Callable[[ArrayLike], ArrayLike] detrend = mlab.detrend_none, Callable[[ArrayLike], ArrayLike] | ArrayLike window = mlab.window_hanning, int noverlap = 0, int | None pad_to = None, Literal["default", "onesided", "twosided"] sides = "default", bool | None scale_by_freq = None, * , data = None, ** kwargs)
Definition at line 3142 of file pyplot.py.
colorbar()
Colorbar matplotlib.pyplot.colorbar (ScalarMappable | ColorizingArtist | None mappable = None, matplotlib.axes.Axes | None cax = None, matplotlib.axes.Axes | Iterable[matplotlib.axes.Axes] | None ax = None, ** kwargs)
Plotting part 1: manually generated functions and wrappers ##.
Definition at line 2521 of file pyplot.py.
References gcf().
connect()
int matplotlib.pyplot.connect (str s, Callable[[Event], Any] func)
Definition at line 1162 of file pyplot.py.
contour()
QuadContourSet matplotlib.pyplot.contour (* args, data = None, ** kwargs)
Definition at line 3178 of file pyplot.py.
contourf()
QuadContourSet matplotlib.pyplot.contourf (* args, data = None, ** kwargs)
Definition at line 3189 of file pyplot.py.
cool()
None matplotlib.pyplot.cool ()
Set the colormap to 'cool'.
This changes the default colormap as well as the colormap of the current
image if there is one. See ``help(colormaps)`` for more information.
Definition at line 4462 of file pyplot.py.
References set_cmap().
copper()
None matplotlib.pyplot.copper ()
Set the colormap to 'copper'.
This changes the default colormap as well as the colormap of the current
image if there is one. See ``help(colormaps)`` for more information.
Definition at line 4473 of file pyplot.py.
References set_cmap().
csd()
tuple[np.ndarray, np.ndarray] | tuple[np.ndarray, np.ndarray, Line2D] matplotlib.pyplot.csd (ArrayLike x, ArrayLike y, int | None NFFT = None, float | None Fs = None, int | None Fc = None, Literal["none", "mean", "linear"] | Callable[[ArrayLike], ArrayLike] | None detrend = None, Callable[[ArrayLike], ArrayLike] | ArrayLike | None window = None, int | None noverlap = None, int | None pad_to = None, Literal["default", "onesided", "twosided"] | None sides = None, bool | None scale_by_freq = None, bool | None return_line = None, * , data = None, ** kwargs)
Definition at line 3200 of file pyplot.py.
delaxes()
None matplotlib.pyplot.delaxes (matplotlib.axes.Axes | None ax = None)
Remove an `~.axes.Axes` (defaulting to the current Axes) from its figure.
Definition at line 1360 of file pyplot.py.
disconnect()
None matplotlib.pyplot.disconnect (int cid)
Definition at line 1167 of file pyplot.py.
draw()
None matplotlib.pyplot.draw ()
Redraw the current figure.
This is used to update a figure that has been altered, but not
automatically re-drawn.  If interactive mode is on (via `.ion()`), this
should be only rarely needed, but there may be ways to modify the state of
a figure without marking it as "stale".  Please report these cases as bugs.
This is equivalent to calling ``fig.canvas.draw_idle()``, where ``fig`` is
the current figure.
See Also
--------
.FigureCanvasBase.draw_idle
.FigureCanvasBase.draw
Definition at line 1226 of file pyplot.py.
References gcf().
draw_if_interactive()
matplotlib.pyplot.draw_if_interactive (* args, ** kwargs)
Redraw the current figure if in interactive mode.
.. warning::
    End users will typically not have to call this function because the
    the interactive mode takes care of this.
Definition at line 556 of file pyplot.py.
References _get_backend_mod(), and draw_if_interactive().
Referenced by draw_if_interactive(), and figure().
ecdf()
Line2D matplotlib.pyplot.ecdf (ArrayLike x, ArrayLike | None weights = None, * , bool complementary = False, Literal["vertical", "horizontal"] orientation = "vertical", bool compress = False, data = None, ** kwargs)
Definition at line 3239 of file pyplot.py.
errorbar()
ErrorbarContainer matplotlib.pyplot.errorbar (float | ArrayLike x, float | ArrayLike y, float | ArrayLike | None yerr = None, float | ArrayLike | None xerr = None, str fmt = "", ColorType | None ecolor = None, float | None elinewidth = None, float | None capsize = None, bool barsabove = False, bool | ArrayLike lolims = False, bool | ArrayLike uplims = False, bool | ArrayLike xlolims = False, bool | ArrayLike xuplims = False, int | tuple[int, int] errorevery = 1, float | None capthick = None, * , data = None, ** kwargs)
Definition at line 3262 of file pyplot.py.
eventplot()
EventCollection matplotlib.pyplot.eventplot (ArrayLike | Sequence[ArrayLike] positions, Literal["horizontal", "vertical"] orientation = "horizontal", float | Sequence[float] lineoffsets = 1, float | Sequence[float] linelengths = 1, float | Sequence[float] | None linewidths = None, ColorType | Sequence[ColorType] | None colors = None, float | Sequence[float] | None alpha = None, LineStyleType | Sequence[LineStyleType] linestyles = "solid", * , data = None, ** kwargs)
Definition at line 3305 of file pyplot.py.
figimage()
FigureImage matplotlib.pyplot.figimage (ArrayLike X, int xo = 0, int yo = 0, float | None alpha = None, str | Normalize | None norm = None, str | Colormap | None cmap = None, float | None vmin = None, float | None vmax = None, Literal["upper", "lower"] | None origin = None, bool resize = False, * , Colorizer | None colorizer = None, ** kwargs)
REMAINING CONTENT GENERATED BY boilerplate.py ##############.
Definition at line 2743 of file pyplot.py.
References figimage(), and gcf().
Referenced by figimage().
figlegend()
Legend matplotlib.pyplot.figlegend (* args, ** kwargs)
Putting things in figures ##.
Definition at line 1259 of file pyplot.py.
References gcf().
fignum_exists()
bool matplotlib.pyplot.fignum_exists (int | str num)
Return whether the figure with the given id exists.
Parameters
----------
num : int or str
    A figure identifier.
Returns
-------
bool
    Whether or not a figure with id *num* exists.
Definition at line 1111 of file pyplot.py.
References get_figlabels().
Referenced by matshow().
figtext()
Text matplotlib.pyplot.figtext (float x, float y, str s, dict[str, Any] | None fontdict = None, ** kwargs)
Definition at line 2776 of file pyplot.py.
figure()
Figure matplotlib.pyplot.figure (int | str | Figure | SubFigure | None num = None, ArrayLike | None figsize = None, float | None dpi = None, * , ColorType | None facecolor = None, ColorType | None edgecolor = None, bool frameon = True, type[Figure] FigureClass = Figure, bool clear = False, ** kwargs)
Figures ##.
Create a new figure, or activate an existing figure.
Parameters
----------
num : int or str or `.Figure` or `.SubFigure`, optional
    A unique identifier for the figure.
    If a figure with that identifier already exists, this figure is made
    active and returned. An integer refers to the ``Figure.number``
    attribute, a string refers to the figure label.
    If there is no figure with the identifier or *num* is not given, a new
    figure is created, made active and returned.  If *num* is an int, it
    will be used for the ``Figure.number`` attribute, otherwise, an
    auto-generated integer value is used (starting at 1 and incremented
    for each new figure). If *num* is a string, the figure label and the
    window title is set to this value.  If num is a ``SubFigure``, its
    parent ``Figure`` is activated.
figsize : (float, float), default: :rc:`figure.figsize`
    Width, height in inches.
dpi : float, default: :rc:`figure.dpi`
    The resolution of the figure in dots-per-inch.
facecolor : :mpltype:`color`, default: :rc:`figure.facecolor`
    The background color.
edgecolor : :mpltype:`color`, default: :rc:`figure.edgecolor`
    The border color.
frameon : bool, default: True
    If False, suppress drawing the figure frame.
FigureClass : subclass of `~matplotlib.figure.Figure`
    If set, an instance of this subclass will be created, rather than a
    plain `.Figure`.
clear : bool, default: False
    If True and the figure already exists, then it is cleared.
layout : {'constrained', 'compressed', 'tight', 'none', `.LayoutEngine`, None}, \
default: None
    The layout mechanism for positioning of plot elements to avoid
    overlapping Axes decorations (labels, ticks, etc). Note that layout
    managers can measurably slow down figure display.
    - 'constrained': The constrained layout solver adjusts Axes sizes
      to avoid overlapping Axes decorations.  Can handle complex plot
      layouts and colorbars, and is thus recommended.
      See :ref:`constrainedlayout_guide`
      for examples.
    - 'compressed': uses the same algorithm as 'constrained', but
      removes extra space between fixed-aspect-ratio Axes.  Best for
      simple grids of Axes.
    - 'tight': Use the tight layout mechanism. This is a relatively
      simple algorithm that adjusts the subplot parameters so that
      decorations do not overlap. See `.Figure.set_tight_layout` for
      further details.
    - 'none': Do not use a layout engine.
    - A `.LayoutEngine` instance. Builtin layout classes are
      `.ConstrainedLayoutEngine` and `.TightLayoutEngine`, more easily
      accessible by 'constrained' and 'tight'.  Passing an instance
      allows third parties to provide their own layout engine.
    If not given, fall back to using the parameters *tight_layout* and
    *constrained_layout*, including their config defaults
    :rc:`figure.autolayout` and :rc:`figure.constrained_layout.use`.
**kwargs
    Additional keyword arguments are passed to the `.Figure` constructor.
Returns
-------
`~matplotlib.figure.Figure`
Notes
-----
A newly created figure is passed to the `~.FigureCanvasBase.new_manager`
method or the `new_figure_manager` function provided by the current
backend, which install a canvas and a manager on the figure.
Once this is done, :rc:`figure.hooks` are called, one at a time, on the
figure; these hooks allow arbitrary customization of the figure (e.g.,
attaching callbacks) or of associated elements (e.g., modifying the
toolbar).  See :doc:`/gallery/user_interfaces/mplcvd` for an example of
toolbar customization.
If you are creating many figures, make sure you explicitly call
`.pyplot.close` on the figures you are not using, because this will
enable pyplot to properly clean up the memory.
`~matplotlib.rcParams` defines the default values, which can be modified
in the matplotlibrc file.
Definition at line 872 of file pyplot.py.
References draw_if_interactive(), get_figlabels(), get_fignums(), and new_figure_manager().
fill()
list[Polygon] matplotlib.pyplot.fill (* args, data = None, ** kwargs)
Definition at line 3334 of file pyplot.py.
fill_between()
FillBetweenPolyCollection matplotlib.pyplot.fill_between (ArrayLike x, ArrayLike | float y1, ArrayLike | float y2 = 0, Sequence[bool] | None where = None, bool interpolate = False, Literal["pre", "post", "mid"] | None step = None, * , data = None, ** kwargs)
Definition at line 3340 of file pyplot.py.
fill_betweenx()
FillBetweenPolyCollection matplotlib.pyplot.fill_betweenx (ArrayLike y, ArrayLike | float x1, ArrayLike | float x2 = 0, Sequence[bool] | None where = None, Literal["pre", "post", "mid"] | None step = None, bool interpolate = False, * , data = None, ** kwargs)
Definition at line 3365 of file pyplot.py.
findobj()
list[Artist] matplotlib.pyplot.findobj (Artist | None o = None, Callable[[Artist], bool] | type[Artist] | None match = None, bool include_self = True)
Definition at line 346 of file pyplot.py.
flag()
None matplotlib.pyplot.flag ()
Set the colormap to 'flag'.
This changes the default colormap as well as the colormap of the current
image if there is one. See ``help(colormaps)`` for more information.
Definition at line 4484 of file pyplot.py.
References set_cmap().
gca()
Axes matplotlib.pyplot.gca ()
Definition at line 2784 of file pyplot.py.
gcf()
Figure matplotlib.pyplot.gcf ()
Get the current figure.
If there is currently no figure on the pyplot figure stack, a new one is
created using `~.pyplot.figure()`.  (To test whether there is currently a
figure on the pyplot figure stack, check whether `~.pyplot.get_fignums()`
is empty.)
Definition at line 1095 of file pyplot.py.
Referenced by axes(), clf(), colorbar(), draw(), figimage(), figlegend(), get_current_fig_manager(), polar(), subplot(), subplot2grid(), subplot_tool(), and uninstall_repl_displayhook().
gci()
ColorizingArtist | None matplotlib.pyplot.gci ()
Definition at line 2790 of file pyplot.py.
get()
matplotlib.pyplot.get (obj, * args, ** kwargs)
Definition at line 792 of file pyplot.py.
get_cmap()
Colormap matplotlib.pyplot.get_cmap (Colormap | str | None name = None, int | None lut = None)
Get a colormap instance, defaulting to rc values if *name* is None.
Parameters
----------
name : `~matplotlib.colors.Colormap` or str or None, default: None
    If a `.Colormap` instance, it will be returned. Otherwise, the name of
    a colormap known to Matplotlib, which will be resampled by *lut*. The
    default, None, means :rc:`image.cmap`.
lut : int or None, default: None
    If *name* is not already a Colormap instance and *lut* is not None, the
    colormap will be resampled to have *lut* entries in the lookup table.
Returns
-------
Colormap
Definition at line 2559 of file pyplot.py.
Referenced by set_cmap().
get_current_fig_manager()
FigureManagerBase | None matplotlib.pyplot.get_current_fig_manager ()
Return the figure manager of the current figure.
The figure manager is a container for the actual backend-depended window
that displays the figure on screen.
If no current figure exists, a new one is created, and its figure
manager is returned.
Returns
-------
`.FigureManagerBase` or backend-dependent subclass thereof
Definition at line 1144 of file pyplot.py.
References gcf().
get_figlabels()
list[Any] matplotlib.pyplot.get_figlabels ()
Return a list of existing figure labels.
Definition at line 1137 of file pyplot.py.
Referenced by close(), fignum_exists(), and figure().
get_fignums()
list[int] matplotlib.pyplot.get_fignums ()
Return a list of existing figure numbers.
Definition at line 1132 of file pyplot.py.
Referenced by close(), and figure().
get_plot_commands()
list[str] matplotlib.pyplot.get_plot_commands ()
Get a sorted list of all of the plotting commands.
Definition at line 2493 of file pyplot.py.
getp()
matplotlib.pyplot.getp (obj, * args, ** kwargs)
Definition at line 787 of file pyplot.py.
ginput()
list[tuple[int, int]] matplotlib.pyplot.ginput (int n = 1, float timeout = 30, bool show_clicks = True, MouseButton mouse_add = MouseButton.LEFT, MouseButton mouse_pop = MouseButton.RIGHT, MouseButton mouse_stop = MouseButton.MIDDLE)
Definition at line 2796 of file pyplot.py.
gray()
None matplotlib.pyplot.gray ()
Set the colormap to 'gray'.
This changes the default colormap as well as the colormap of the current
image if there is one. See ``help(colormaps)`` for more information.
Definition at line 4495 of file pyplot.py.
References set_cmap().
grid()
None matplotlib.pyplot.grid (bool | None visible = None, Literal["major", "minor", "both"] which = "major", Literal["both", "x", "y"] axis = "both", ** kwargs)
Definition at line 3390 of file pyplot.py.
hexbin()
PolyCollection matplotlib.pyplot.hexbin (ArrayLike x, ArrayLike y, ArrayLike | None C = None, int | tuple[int, int] gridsize = 100, Literal["log"] | int | Sequence[float] | None bins = None, Literal["linear", "log"] xscale = "linear", Literal["linear", "log"] yscale = "linear", tuple[float, float, float, float] | None extent = None, str | Colormap | None cmap = None, str | Normalize | None norm = None, float | None vmin = None, float | None vmax = None, float | None alpha = None, float | None linewidths = None, Literal["face", "none"] | ColorType edgecolors = "face", Callable[[np.ndarray | list[float]], float] reduce_C_function = np.mean, int | None mincnt = None, bool marginals = False, Colorizer | None colorizer = None, * , data = None, ** kwargs)
Definition at line 3401 of file pyplot.py.
hist()
tuple[ np.ndarray | list[np.ndarray], np.ndarray, BarContainer | Polygon | list[BarContainer | Polygon], ] matplotlib.pyplot.hist (ArrayLike | Sequence[ArrayLike] x, int | Sequence[float] | str | None bins = None, tuple[float, float] | None range = None, bool density = False, ArrayLike | None weights = None, bool | float cumulative = False, ArrayLike | float | None bottom = None, Literal["bar", "barstacked", "step", "stepfilled"] histtype = "bar", Literal["left", "mid", "right"] align = "mid", Literal["vertical", "horizontal"] orientation = "vertical", float | None rwidth = None, bool log = False, ColorType | Sequence[ColorType] | None color = None, str | Sequence[str] | None label = None, bool stacked = False, * , data = None, ** kwargs)
Definition at line 3454 of file pyplot.py.
hist2d()
tuple[np.ndarray, np.ndarray, np.ndarray, QuadMesh] matplotlib.pyplot.hist2d (ArrayLike x, ArrayLike y, None | int | tuple[int, int] | ArrayLike | tuple[ArrayLike, ArrayLike] bins = 10, ArrayLike | None range = None, bool density = False, ArrayLike | None weights = None, float | None cmin = None, float | None cmax = None, * , data = None, ** kwargs)
Definition at line 3524 of file pyplot.py.
hlines()
LineCollection matplotlib.pyplot.hlines (float | ArrayLike y, float | ArrayLike xmin, float | ArrayLike xmax, ColorType | Sequence[ColorType] | None colors = None, LineStyleType linestyles = "solid", str label = "", * , data = None, ** kwargs)
Definition at line 3555 of file pyplot.py.
hot()
None matplotlib.pyplot.hot ()
Set the colormap to 'hot'.
This changes the default colormap as well as the colormap of the current
image if there is one. See ``help(colormaps)`` for more information.
Definition at line 4506 of file pyplot.py.
References set_cmap().
hsv()
None matplotlib.pyplot.hsv ()
Set the colormap to 'hsv'.
This changes the default colormap as well as the colormap of the current
image if there is one. See ``help(colormaps)`` for more information.
Definition at line 4517 of file pyplot.py.
References set_cmap().
imread()
np.ndarray matplotlib.pyplot.imread (str | pathlib.Path | BinaryIO fname, str | None format = None)
Definition at line 2612 of file pyplot.py.
imsave()
None matplotlib.pyplot.imsave (str | os.PathLike | BinaryIO fname, ArrayLike arr, ** kwargs)
Definition at line 2619 of file pyplot.py.
imshow()
AxesImage matplotlib.pyplot.imshow (ArrayLike | PIL.Image.Image X, str | Colormap | None cmap = None, str | Normalize | None norm = None, * , Literal["equal", "auto"] | float | None aspect = None, str | None interpolation = None, float | ArrayLike | None alpha = None, float | None vmin = None, float | None vmax = None, Colorizer | None colorizer = None, Literal["upper", "lower"] | None origin = None, tuple[float, float, float, float] | None extent = None, Literal["data", "rgba", "auto"] | None interpolation_stage = None, bool filternorm = True, float filterrad = 4.0, bool | None resample = None, str | None url = None, data = None, ** kwargs)
Definition at line 3580 of file pyplot.py.
inferno()
None matplotlib.pyplot.inferno ()
Set the colormap to 'inferno'.
This changes the default colormap as well as the colormap of the current
image if there is one. See ``help(colormaps)`` for more information.
Definition at line 4605 of file pyplot.py.
References set_cmap().
install_repl_displayhook()
None matplotlib.pyplot.install_repl_displayhook ()
Connect to the display hook of the current shell.
The display hook gets called when the read-evaluate-print-loop (REPL) of
the shell has finished the execution of a command. We use this callback
to be able to automatically update a figure in interactive mode.
This works both with IPython and with vanilla python shells.
Definition at line 282 of file pyplot.py.
References matplotlib.get_backend().
Referenced by ion(), and switch_backend().
ioff()
AbstractContextManager matplotlib.pyplot.ioff ()
Disable interactive mode.
See `.pyplot.isinteractive` for more details.
See Also
--------
ion : Enable interactive mode.
isinteractive : Whether interactive mode is enabled.
show : Show all figures (and maybe block).
pause : Show all figures, and block for a time.
Notes
-----
For a temporary change, this can be used as a context manager::
    # if interactive mode is on
    # then figures will be shown on creation
    plt.ion()
    # This figure will be shown immediately
    fig = plt.figure()
    with plt.ioff():
        # interactive mode will be off
        # figures will not automatically be shown
        fig2 = plt.figure()
        # ...
To enable optional usage as a context manager, this function returns a
context manager object, which is not intended to be stored or
accessed by the user.
Definition at line 651 of file pyplot.py.
References matplotlib.interactive(), isinteractive(), and uninstall_repl_displayhook().
ion()
AbstractContextManager matplotlib.pyplot.ion ()
Enable interactive mode.
See `.pyplot.isinteractive` for more details.
See Also
--------
ioff : Disable interactive mode.
isinteractive : Whether interactive mode is enabled.
show : Show all figures (and maybe block).
pause : Show all figures, and block for a time.
Notes
-----
For a temporary change, this can be used as a context manager::
    # if interactive mode is off
    # then figures will not be shown on creation
    plt.ioff()
    # This figure will not be shown immediately
    fig = plt.figure()
    with plt.ion():
        # interactive mode will be on
        # figures will automatically be shown
        fig2 = plt.figure()
        # ...
To enable optional usage as a context manager, this function returns a
context manager object, which is not intended to be stored or
accessed by the user.
Definition at line 695 of file pyplot.py.
References install_repl_displayhook(), matplotlib.interactive(), and isinteractive().
isinteractive()
bool matplotlib.pyplot.isinteractive ()
Return whether plots are updated after every plotting command.
The interactive mode is mainly useful if you build plots from the command
line and want to see the effect of each command while you are building the
figure.
In interactive mode:
- newly created figures will be shown immediately;
- figures will automatically redraw on change;
- `.pyplot.show` will not block by default.
In non-interactive mode:
- newly created figures and changes to figures will not be reflected until
  explicitly asked to be;
- `.pyplot.show` will block by default.
See Also
--------
ion : Enable interactive mode.
ioff : Disable interactive mode.
show : Show all figures (and maybe block).
pause : Show all figures, and block for a time.
Definition at line 617 of file pyplot.py.
References matplotlib.is_interactive().
Referenced by ioff(), and ion().
jet()
None matplotlib.pyplot.jet ()
Set the colormap to 'jet'.
This changes the default colormap as well as the colormap of the current
image if there is one. See ``help(colormaps)`` for more information.
Definition at line 4528 of file pyplot.py.
References set_cmap().
legend()
Legend matplotlib.pyplot.legend (* args, ** kwargs)
Definition at line 3627 of file pyplot.py.
locator_params()
None matplotlib.pyplot.locator_params (Literal["both", "x", "y"] axis = "both", bool | None tight = None, ** kwargs)
Definition at line 3633 of file pyplot.py.
loglog()
list[Line2D] matplotlib.pyplot.loglog (* args, ** kwargs)
Definition at line 3641 of file pyplot.py.
magma()
None matplotlib.pyplot.magma ()
Set the colormap to 'magma'.
This changes the default colormap as well as the colormap of the current
image if there is one. See ``help(colormaps)`` for more information.
Definition at line 4594 of file pyplot.py.
References set_cmap().
magnitude_spectrum()
tuple[np.ndarray, np.ndarray, Line2D] matplotlib.pyplot.magnitude_spectrum (ArrayLike x, float | None Fs = None, int | None Fc = None, Callable[[ArrayLike], ArrayLike] | ArrayLike | None window = None, int | None pad_to = None, Literal["default", "onesided", "twosided"] | None sides = None, Literal["default", "linear", "dB"] | None scale = None, * , data = None, ** kwargs)
Definition at line 3647 of file pyplot.py.
margins()
tuple[float, float] | None matplotlib.pyplot.margins (*float margins, float | None x = None, float | None y = None, bool | None tight = True)
Definition at line 3674 of file pyplot.py.
matshow()
AxesImage matplotlib.pyplot.matshow (ArrayLike A, None | int fignum = None, ** kwargs)
Display a 2D array as a matrix in a new figure window.
The origin is set at the upper left hand corner.
The indexing is ``(row, column)`` so that the first index runs vertically
and the second index runs horizontally in the figure:
.. code-block:: none
    A[0, 0]    A[0, M-1]
    A[N-1, 0]  A[N-1, M-1]
The aspect ratio of the figure window is that of the array,
unless this would make an excessively short or narrow figure.
Tick labels for the xaxis are placed on top.
Parameters
----------
A : 2D array-like
    The matrix to be displayed.
fignum : None or int
    If *None*, create a new, appropriately sized figure window.
    If 0, use the current Axes (creating one if there is none, without ever
    adjusting the figure size).
    Otherwise, create a new Axes on the figure with the given number
    (creating it at the appropriate size if it does not exist, but not
    adjusting the figure size otherwise).  Note that this will be drawn on
    top of any preexisting Axes on the figure.
Returns
-------
`~matplotlib.image.AxesImage`
Other Parameters
----------------
**kwargs : `~matplotlib.axes.Axes.imshow` arguments
Definition at line 2625 of file pyplot.py.
References fignum_exists().
minorticks_off()
None matplotlib.pyplot.minorticks_off ()
Definition at line 3685 of file pyplot.py.
minorticks_on()
None matplotlib.pyplot.minorticks_on ()
Definition at line 3691 of file pyplot.py.
new_figure_manager()
matplotlib.pyplot.new_figure_manager (* args, ** kwargs)
Create a new figure manager instance.
Definition at line 549 of file pyplot.py.
References _get_backend_mod(), and new_figure_manager().
Referenced by figure(), and new_figure_manager().
nipy_spectral()
None matplotlib.pyplot.nipy_spectral ()
Set the colormap to 'nipy_spectral'.
This changes the default colormap as well as the colormap of the current
image if there is one. See ``help(colormaps)`` for more information.
Definition at line 4638 of file pyplot.py.
References set_cmap().
pause()
None matplotlib.pyplot.pause (float interval)
Run the GUI event loop for *interval* seconds.
If there is an active figure, it will be updated and displayed before the
pause, and the GUI event loop (if any) will run during the pause.
This can be used for crude animation.  For more complex animation use
:mod:`matplotlib.animation`.
If there is no active figure, sleep for *interval* seconds instead.
See Also
--------
matplotlib.animation : Proper animations
show : Show all figures and optional block until all figures are closed.
Definition at line 735 of file pyplot.py.
References matplotlib.artist.getp(), matplotlib.is_interactive(), matplotlib.rc(), matplotlib.rc_context(), matplotlib.rcdefaults(), matplotlib.artist.setp(), and show().
pcolor()
Collection matplotlib.pyplot.pcolor (*ArrayLike args, Literal["flat", "nearest", "auto"] | None shading = None, float | None alpha = None, str | Normalize | None norm = None, str | Colormap | None cmap = None, float | None vmin = None, float | None vmax = None, Colorizer | None colorizer = None, data = None, ** kwargs)
Definition at line 3697 of file pyplot.py.
pcolormesh()
QuadMesh matplotlib.pyplot.pcolormesh (*ArrayLike args, float | None alpha = None, str | Normalize | None norm = None, str | Colormap | None cmap = None, float | None vmin = None, float | None vmax = None, Colorizer | None colorizer = None, Literal["flat", "nearest", "gouraud", "auto"] | None shading = None, bool antialiased = False, data = None, ** kwargs)
Definition at line 3727 of file pyplot.py.
phase_spectrum()
tuple[np.ndarray, np.ndarray, Line2D] matplotlib.pyplot.phase_spectrum (ArrayLike x, float | None Fs = None, int | None Fc = None, Callable[[ArrayLike], ArrayLike] | ArrayLike | None window = None, int | None pad_to = None, Literal["default", "onesided", "twosided"] | None sides = None, * , data = None, ** kwargs)
Definition at line 3759 of file pyplot.py.
pie()
tuple[list[Wedge], list[Text]] | tuple[list[Wedge], list[Text], list[Text]] matplotlib.pyplot.pie (ArrayLike x, ArrayLike | None explode = None, Sequence[str] | None labels = None, ColorType | Sequence[ColorType] | None colors = None, str | Callable[[float], str] | None autopct = None, float pctdistance = 0.6, bool shadow = False, float | None labeldistance = 1.1, float startangle = 0, float radius = 1, bool counterclock = True, dict[str, Any] | None wedgeprops = None, dict[str, Any] | None textprops = None, tuple[float, float] center = (0, 0), bool frame = False, bool rotatelabels = False, * , bool normalize = True, str | Sequence[str] | None hatch = None, data = None)
Definition at line 3784 of file pyplot.py.
pink()
None matplotlib.pyplot.pink ()
Set the colormap to 'pink'.
This changes the default colormap as well as the colormap of the current
image if there is one. See ``help(colormaps)`` for more information.
Definition at line 4539 of file pyplot.py.
References set_cmap().
plasma()
None matplotlib.pyplot.plasma ()
Set the colormap to 'plasma'.
This changes the default colormap as well as the colormap of the current
image if there is one. See ``help(colormaps)`` for more information.
Definition at line 4616 of file pyplot.py.
References set_cmap().
plot()
list[Line2D] matplotlib.pyplot.plot (*float | ArrayLike | str args, bool scalex = True, bool scaley = True, data = None, ** kwargs)
Definition at line 3831 of file pyplot.py.
plot_date()
list[Line2D] matplotlib.pyplot.plot_date (ArrayLike x, ArrayLike y, str fmt = "o", str | datetime.tzinfo | None tz = None, bool xdate = True, bool ydate = False, * , data = None, ** kwargs)
Definition at line 3849 of file pyplot.py.
polar()
list[Line2D] matplotlib.pyplot.polar (* args, ** kwargs)
Make a polar plot.
call signature::
  polar(theta, r, [fmt], **kwargs)
This is a convenience wrapper around `.pyplot.plot`. It ensures that the
current Axes is polar (or creates one if needed) and then passes all parameters
to ``.pyplot.plot``.
.. note::
    When making polar plots using the :ref:`pyplot API <pyplot_interface>`,
    ``polar()`` should typically be the first command because that makes sure
    a polar Axes is created. Using other commands such as ``plt.title()``
    before this can lead to the implicit creation of a rectangular Axes, in which
    case a subsequent ``polar()`` call will fail.
Definition at line 2686 of file pyplot.py.
References gcf().
prism()
None matplotlib.pyplot.prism ()
Set the colormap to 'prism'.
This changes the default colormap as well as the colormap of the current
image if there is one. See ``help(colormaps)`` for more information.
Definition at line 4550 of file pyplot.py.
References set_cmap().
psd()
tuple[np.ndarray, np.ndarray] | tuple[np.ndarray, np.ndarray, Line2D] matplotlib.pyplot.psd (ArrayLike x, int | None NFFT = None, float | None Fs = None, int | None Fc = None, Literal["none", "mean", "linear"] | Callable[[ArrayLike], ArrayLike] | None detrend = None, Callable[[ArrayLike], ArrayLike] | ArrayLike | None window = None, int | None noverlap = None, int | None pad_to = None, Literal["default", "onesided", "twosided"] | None sides = None, bool | None scale_by_freq = None, bool | None return_line = None, * , data = None, ** kwargs)
Definition at line 3874 of file pyplot.py.
quiver()
Quiver matplotlib.pyplot.quiver (* args, data = None, ** kwargs)
Definition at line 3911 of file pyplot.py.
quiverkey()
QuiverKey matplotlib.pyplot.quiverkey (Quiver Q, float X, float Y, float U, str label, ** kwargs)
Definition at line 3921 of file pyplot.py.
rc()
None matplotlib.pyplot.rc (str group, ** kwargs)
Definition at line 764 of file pyplot.py.
rc_context()
AbstractContextManager[None] matplotlib.pyplot.rc_context (dict[str, Any] | None rc = None, str | pathlib.Path | os.PathLike | None fname = None)
Definition at line 769 of file pyplot.py.
rcdefaults()
None matplotlib.pyplot.rcdefaults ()
Definition at line 777 of file pyplot.py.
rgrids()
tuple[list[Line2D], list[Text]] matplotlib.pyplot.rgrids (ArrayLike | None radii = None, Sequence[str | Text] | None labels = None, float | None angle = None, str | None fmt = None, ** kwargs)
Get or set the radial gridlines on the current polar plot.
Call signatures::
 lines, labels = rgrids()
 lines, labels = rgrids(radii, labels=None, angle=22.5, fmt=None, **kwargs)
When called with no arguments, `.rgrids` simply returns the tuple
(*lines*, *labels*). When called with arguments, the labels will
appear at the specified radial distances and angle.
Parameters
----------
radii : tuple with floats
    The radii for the radial gridlines
labels : tuple with strings or None
    The labels to use at each radial gridline. The
    `matplotlib.ticker.ScalarFormatter` will be used if None.
angle : float
    The angular position of the radius labels in degrees.
fmt : str or None
    Format string used in `matplotlib.ticker.FormatStrFormatter`.
    For example '%f'.
Returns
-------
lines : list of `.lines.Line2D`
    The radial gridlines.
labels : list of `.text.Text`
    The tick labels.
Other Parameters
----------------
**kwargs
    *kwargs* are optional `.Text` properties for the labels.
See Also
--------
.pyplot.thetagrids
.projections.polar.PolarAxes.set_rgrids
.Axis.get_gridlines
.Axis.get_ticklabels
Examples
--------
::
  # set the locations of the radial gridlines
  lines, labels = rgrids( (0.25, 0.5, 1.0) )
  # set the locations and labels of the radial gridlines
  lines, labels = rgrids( (0.25, 0.5, 1.0), ('Tom', 'Dick', 'Harry' ))
Definition at line 2337 of file pyplot.py.
savefig()
None matplotlib.pyplot.savefig (* args, ** kwargs)
Definition at line 1247 of file pyplot.py.
sca()
None matplotlib.pyplot.sca (Axes ax)
Set the current Axes to *ax* and the current Figure to the parent of *ax*.
Definition at line 1369 of file pyplot.py.
scatter()
PathCollection matplotlib.pyplot.scatter (float | ArrayLike x, float | ArrayLike y, float | ArrayLike | None s = None, ArrayLike | Sequence[ColorType] | ColorType | None c = None, MarkerType | None marker = None, str | Colormap | None cmap = None, str | Normalize | None norm = None, float | None vmin = None, float | None vmax = None, float | None alpha = None, float | Sequence[float] | None linewidths = None, * , Literal["face", "none"] | ColorType | Sequence[ColorType] | None edgecolors = None, Colorizer | None colorizer = None, bool plotnonfinite = False, data = None, ** kwargs)
Definition at line 3929 of file pyplot.py.
sci()
None matplotlib.pyplot.sci (ColorizingArtist im)
Definition at line 4379 of file pyplot.py.
semilogx()
list[Line2D] matplotlib.pyplot.semilogx (* args, ** kwargs)
Definition at line 3972 of file pyplot.py.
semilogy()
list[Line2D] matplotlib.pyplot.semilogy (* args, ** kwargs)
Definition at line 3978 of file pyplot.py.
set_cmap()
None matplotlib.pyplot.set_cmap (Colormap | str cmap)
Set the default colormap, and applies it to the current image if any.
Parameters
----------
cmap : `~matplotlib.colors.Colormap` or str
    A colormap instance or the name of a registered colormap.
See Also
--------
colormaps
get_cmap
Definition at line 2588 of file pyplot.py.
References get_cmap(), matplotlib.image.imread(), and matplotlib.image.imsave().
Referenced by autumn(), bone(), cool(), copper(), flag(), gray(), hot(), hsv(), inferno(), jet(), magma(), nipy_spectral(), pink(), plasma(), prism(), spring(), summer(), viridis(), and winter().
set_loglevel()
None matplotlib.pyplot.set_loglevel (* args, ** kwargs)
Definition at line 341 of file pyplot.py.
setp()
matplotlib.pyplot.setp (obj, * args, ** kwargs)
Definition at line 797 of file pyplot.py.
show()
None matplotlib.pyplot.show (* args, ** kwargs)
Display all open figures.
Parameters
----------
block : bool, optional
    Whether to wait for all figures to be closed before returning.
    If `True` block and run the GUI main loop until all figure windows
    are closed.
    If `False` ensure that all figure windows are displayed and return
    immediately.  In this case, you are responsible for ensuring
    that the event loop is running to have responsive figures.
    Defaults to True in non-interactive mode and to False in interactive
    mode (see `.pyplot.isinteractive`).
See Also
--------
ion : Enable interactive mode, which shows / updates the figure after
      every plotting command, so that calling ``show()`` is not necessary.
ioff : Disable interactive mode.
savefig : Save the figure to an image file instead of showing it on screen.
Notes
-----
**Saving figures to file and showing a window at the same time**
If you want an image file as well as a user interface window, use
`.pyplot.savefig` before `.pyplot.show`. At the end of (a blocking)
``show()`` the figure is closed and thus unregistered from pyplot. Calling
`.pyplot.savefig` afterwards would save a new and thus empty figure. This
limitation of command order does not apply if the show is non-blocking or
if you keep a reference to the figure and use `.Figure.savefig`.
**Auto-show in jupyter notebooks**
The jupyter backends (activated via ``%matplotlib inline``,
``%matplotlib notebook``, or ``%matplotlib widget``), call ``show()`` at
the end of every cell by default. Thus, you usually don't have to call it
explicitly there.
Definition at line 569 of file pyplot.py.
References _get_backend_mod(), and show().
Referenced by pause(), and show().
specgram()
tuple[np.ndarray, np.ndarray, np.ndarray, AxesImage] matplotlib.pyplot.specgram (ArrayLike x, int | None NFFT = None, float | None Fs = None, int | None Fc = None, Literal["none", "mean", "linear"] | Callable[[ArrayLike], ArrayLike] | None detrend = None, Callable[[ArrayLike], ArrayLike] | ArrayLike | None window = None, int | None noverlap = None, str | Colormap | None cmap = None, tuple[float, float] | None xextent = None, int | None pad_to = None, Literal["default", "onesided", "twosided"] | None sides = None, bool | None scale_by_freq = None, Literal["default", "psd", "magnitude", "angle", "phase"] | None mode = None, Literal["default", "linear", "dB"] | None scale = None, float | None vmin = None, float | None vmax = None, * , data = None, ** kwargs)
Definition at line 3984 of file pyplot.py.
spring()
None matplotlib.pyplot.spring ()
Set the colormap to 'spring'.
This changes the default colormap as well as the colormap of the current
image if there is one. See ``help(colormaps)`` for more information.
Definition at line 4561 of file pyplot.py.
References set_cmap().
spy()
AxesImage matplotlib.pyplot.spy (ArrayLike Z, float | Literal["present"] precision = 0, str | None marker = None, float | None markersize = None, Literal["equal", "auto"] | float | None aspect = "equal", Literal["upper", "lower"] origin = "upper", ** kwargs)
Definition at line 4033 of file pyplot.py.
stackplot()
matplotlib.pyplot.stackplot (x, * args, labels = (), colors = None, hatch = None, baseline = "zero", data = None, ** kwargs)
Definition at line 4058 of file pyplot.py.
stairs()
StepPatch matplotlib.pyplot.stairs (ArrayLike values, ArrayLike | None edges = None, * , Literal["vertical", "horizontal"] orientation = "vertical", float | ArrayLike | None baseline = 0, bool fill = False, data = None, ** kwargs)
Definition at line 3501 of file pyplot.py.
stem()
StemContainer matplotlib.pyplot.stem (*ArrayLike | str args, str | None linefmt = None, str | None markerfmt = None, str | None basefmt = None, float bottom = 0, str | None label = None, Literal["vertical", "horizontal"] orientation = "vertical", data = None)
Definition at line 4075 of file pyplot.py.
step()
list[Line2D] matplotlib.pyplot.step (ArrayLike x, ArrayLike y, * args, Literal["pre", "post", "mid"] where = "pre", data = None, ** kwargs)
Definition at line 4099 of file pyplot.py.
streamplot()
matplotlib.pyplot.streamplot (x, y, u, v, density = 1, linewidth = None, color = None, cmap = None, norm = None, arrowsize = 1, arrowstyle = "-|>", minlength = 0.1, transform = None, zorder = None, start_points = None, maxlength = 4.0, integration_direction = "both", broken_streamlines = True, * , data = None)
Definition at line 4119 of file pyplot.py.
subplot()
Axes matplotlib.pyplot.subplot (* args, ** kwargs)
More ways of creating Axes ##.
Add an Axes to the current figure or retrieve an existing Axes.
This is a wrapper of `.Figure.add_subplot` which provides additional
behavior when working with the implicit API (see the notes section).
Call signatures::
   subplot(nrows, ncols, index, **kwargs)
   subplot(pos, **kwargs)
   subplot(**kwargs)
   subplot(ax)
Parameters
----------
*args : int, (int, int, *index*), or `.SubplotSpec`, default: (1, 1, 1)
    The position of the subplot described by one of
    - Three integers (*nrows*, *ncols*, *index*). The subplot will take the
      *index* position on a grid with *nrows* rows and *ncols* columns.
      *index* starts at 1 in the upper left corner and increases to the
      right. *index* can also be a two-tuple specifying the (*first*,
      *last*) indices (1-based, and including *last*) of the subplot, e.g.,
      ``fig.add_subplot(3, 1, (1, 2))`` makes a subplot that spans the
      upper 2/3 of the figure.
    - A 3-digit integer. The digits are interpreted as if given separately
      as three single-digit integers, i.e. ``fig.add_subplot(235)`` is the
      same as ``fig.add_subplot(2, 3, 5)``. Note that this can only be used
      if there are no more than 9 subplots.
    - A `.SubplotSpec`.
projection : {None, 'aitoff', 'hammer', 'lambert', 'mollweide', \
'polar', 'rectilinear', str}, optional
    The projection type of the subplot (`~.axes.Axes`). *str* is the name
    of a custom projection, see `~matplotlib.projections`. The default
    None results in a 'rectilinear' projection.
polar : bool, default: False
    If True, equivalent to projection='polar'.
sharex, sharey : `~matplotlib.axes.Axes`, optional
    Share the x or y `~matplotlib.axis` with sharex and/or sharey. The
    axis will have the same limits, ticks, and scale as the axis of the
    shared Axes.
label : str
    A label for the returned Axes.
Returns
-------
`~.axes.Axes`
    The Axes of the subplot. The returned Axes can actually be an instance
    of a subclass, such as `.projections.polar.PolarAxes` for polar
    projections.
Other Parameters
----------------
**kwargs
    This method also takes the keyword arguments for the returned Axes
    base class; except for the *figure* argument. The keyword arguments
    for the rectilinear base class `~.axes.Axes` can be found in
    the following table but there might also be other keyword
    arguments if another projection is used.
    %(Axes:kwdoc)s
Notes
-----
.. versionchanged:: 3.8
    In versions prior to 3.8, any preexisting Axes that overlap with the new Axes
    beyond sharing a boundary was deleted. Deletion does not happen in more
    recent versions anymore. Use `.Axes.remove` explicitly if needed.
If you do not want this behavior, use the `.Figure.add_subplot` method
or the `.pyplot.axes` function instead.
If no *kwargs* are passed and there exists an Axes in the location
specified by *args* then that Axes will be returned rather than a new
Axes being created.
If *kwargs* are passed and there exists an Axes in the location
specified by *args*, the projection type is the same, and the
*kwargs* match with the existing Axes, then the existing Axes is
returned.  Otherwise a new Axes is created with the specified
parameters.  We save a reference to the *kwargs* which we use
for this comparison.  If any of the values in *kwargs* are
mutable we will not detect the case where they are mutated.
In these cases we suggest using `.Figure.add_subplot` and the
explicit Axes API rather than the implicit pyplot API.
See Also
--------
.Figure.add_subplot
.pyplot.subplots
.pyplot.axes
.Figure.subplots
Examples
--------
::
    plt.subplot(221)
    # equivalent but more general
    ax1 = plt.subplot(2, 2, 1)
    # add a subplot with no frame
    ax2 = plt.subplot(222, frameon=False)
    # add a polar subplot
    plt.subplot(223, projection='polar')
    # add a red subplot that shares the x-axis with ax1
    plt.subplot(224, sharex=ax1, facecolor='red')
    # delete ax2 from the figure
    plt.delaxes(ax2)
    # add ax2 to the figure again
    plt.subplot(ax2)
    # make the first Axes "current" again
    plt.subplot(221)
Definition at line 1390 of file pyplot.py.
References gcf().
subplot2grid()
matplotlib.axes.Axes matplotlib.pyplot.subplot2grid (tuple[int, int] shape, tuple[int, int] loc, int rowspan = 1, int colspan = 1, Figure | None fig = None, ** kwargs)
Create a subplot at a specific location inside a regular grid.
Parameters
----------
shape : (int, int)
    Number of rows and of columns of the grid in which to place axis.
loc : (int, int)
    Row number and column number of the axis location within the grid.
rowspan : int, default: 1
    Number of rows for the axis to span downwards.
colspan : int, default: 1
    Number of columns for the axis to span to the right.
fig : `.Figure`, optional
    Figure to place the subplot in. Defaults to the current figure.
**kwargs
    Additional keyword arguments are handed to `~.Figure.add_subplot`.
Returns
-------
`~.axes.Axes`
    The Axes of the subplot. The returned Axes can actually be an instance
    of a subclass, such as `.projections.polar.PolarAxes` for polar
    projections.
Notes
-----
The following call ::
    ax = subplot2grid((nrows, ncols), (row, col), rowspan, colspan)
is identical to ::
    fig = gcf()
    gs = fig.add_gridspec(nrows, ncols)
    ax = fig.add_subplot(gs[row:row+rowspan, col:col+colspan])
Definition at line 1962 of file pyplot.py.
References gcf().
subplot_mosaic() [1/4]
tuple[Figure, dict[_T, matplotlib.axes.Axes]] matplotlib.pyplot.subplot_mosaic (list[HashableList[_T]] mosaic, * , bool sharex = ..., bool sharey = ..., ArrayLike | None width_ratios = ..., ArrayLike | None height_ratios = ..., _T empty_sentinel = ..., dict[str, Any] | None subplot_kw = ..., dict[str, Any] | None gridspec_kw = ..., dict[_T | tuple[_T, ...], dict[str, Any]] | None per_subplot_kw = ..., **Any fig_kw)
Definition at line 1802 of file pyplot.py.
subplot_mosaic() [2/4]
tuple[Figure, dict[Hashable, matplotlib.axes.Axes]] matplotlib.pyplot.subplot_mosaic (list[HashableList[Hashable]] mosaic, * , bool sharex = ..., bool sharey = ..., ArrayLike | None width_ratios = ..., ArrayLike | None height_ratios = ..., Any empty_sentinel = ..., dict[str, Any] | None subplot_kw = ..., dict[str, Any] | None gridspec_kw = ..., dict[Hashable | tuple[Hashable, ...], dict[str, Any]] | None per_subplot_kw = ..., **Any fig_kw)
Definition at line 1818 of file pyplot.py.
subplot_mosaic() [3/4]
tuple[Figure, dict[str, matplotlib.axes.Axes]] matplotlib.pyplot.subplot_mosaic (str mosaic, * , bool sharex = ..., bool sharey = ..., ArrayLike | None width_ratios = ..., ArrayLike | None height_ratios = ..., str empty_sentinel = ..., dict[str, Any] | None subplot_kw = ..., dict[str, Any] | None gridspec_kw = ..., dict[str | tuple[str, ...], dict[str, Any]] | None per_subplot_kw = ..., **Any fig_kw)
Definition at line 1786 of file pyplot.py.
subplot_mosaic() [4/4]
tuple[Figure, dict[str, matplotlib.axes.Axes]] | \ tuple[Figure, dict[_T, matplotlib.axes.Axes]] | \ tuple[Figure, dict[Hashable, matplotlib.axes.Axes]] matplotlib.pyplot.subplot_mosaic (str | list[HashableList[_T]] | list[HashableList[Hashable]] mosaic, * , bool sharex = False, bool sharey = False, ArrayLike | None width_ratios = None, ArrayLike | None height_ratios = None, Any empty_sentinel = '.', dict[str, Any] | None subplot_kw = None, dict[str, Any] | None gridspec_kw = None, dict[str | tuple[str, ...], dict[str, Any]] | dict[_T | tuple[_T, ...], dict[str, Any]] | dict[Hashable | tuple[Hashable, ...], dict[str, Any]] | None per_subplot_kw = None, **Any fig_kw)
Build a layout of Axes based on ASCII art or nested lists.
This is a helper function to build complex GridSpec layouts visually.
See :ref:`mosaic`
for an example and full API documentation
Parameters
----------
mosaic : list of list of {hashable or nested} or str
    A visual layout of how you want your Axes to be arranged
    labeled as strings.  For example ::
       x = [['A panel', 'A panel', 'edge'],
            ['C panel', '.',       'edge']]
    produces 4 Axes:
    - 'A panel' which is 1 row high and spans the first two columns
    - 'edge' which is 2 rows high and is on the right edge
    - 'C panel' which in 1 row and 1 column wide in the bottom left
    - a blank space 1 row and 1 column wide in the bottom center
    Any of the entries in the layout can be a list of lists
    of the same form to create nested layouts.
    If input is a str, then it must be of the form ::
      '''
      AAE
      C.E
      '''
    where each character is a column and each line is a row.
    This only allows only single character Axes labels and does
    not allow nesting but is very terse.
sharex, sharey : bool, default: False
    If True, the x-axis (*sharex*) or y-axis (*sharey*) will be shared
    among all subplots.  In that case, tick label visibility and axis units
    behave as for `subplots`.  If False, each subplot's x- or y-axis will
    be independent.
width_ratios : array-like of length *ncols*, optional
    Defines the relative widths of the columns. Each column gets a
    relative width of ``width_ratios[i] / sum(width_ratios)``.
    If not given, all columns will have the same width.  Convenience
    for ``gridspec_kw={'width_ratios': [...]}``.
height_ratios : array-like of length *nrows*, optional
    Defines the relative heights of the rows. Each row gets a
    relative height of ``height_ratios[i] / sum(height_ratios)``.
    If not given, all rows will have the same height. Convenience
    for ``gridspec_kw={'height_ratios': [...]}``.
empty_sentinel : object, optional
    Entry in the layout to mean "leave this space empty".  Defaults
    to ``'.'``. Note, if *layout* is a string, it is processed via
    `inspect.cleandoc` to remove leading white space, which may
    interfere with using white-space as the empty sentinel.
subplot_kw : dict, optional
    Dictionary with keywords passed to the `.Figure.add_subplot` call
    used to create each subplot.  These values may be overridden by
    values in *per_subplot_kw*.
per_subplot_kw : dict, optional
    A dictionary mapping the Axes identifiers or tuples of identifiers
    to a dictionary of keyword arguments to be passed to the
    `.Figure.add_subplot` call used to create each subplot.  The values
    in these dictionaries have precedence over the values in
    *subplot_kw*.
    If *mosaic* is a string, and thus all keys are single characters,
    it is possible to use a single string instead of a tuple as keys;
    i.e. ``"AB"`` is equivalent to ``("A", "B")``.
    .. versionadded:: 3.7
gridspec_kw : dict, optional
    Dictionary with keywords passed to the `.GridSpec` constructor used
    to create the grid the subplots are placed on.
**fig_kw
    All additional keyword arguments are passed to the
    `.pyplot.figure` call.
Returns
-------
fig : `.Figure`
   The new figure
dict[label, Axes]
   A dictionary mapping the labels to the Axes objects.  The order of
   the Axes is left-to-right and top-to-bottom of their position in the
   total layout.
Definition at line 1833 of file pyplot.py.
subplot_tool()
SubplotTool | None matplotlib.pyplot.subplot_tool (Figure | None targetfig = None)
Launch a subplot tool window for a figure.
Returns
-------
`matplotlib.widgets.SubplotTool`
Definition at line 2046 of file pyplot.py.
References gcf().
subplots() [1/3]
tuple[Figure, Any] matplotlib.pyplot.subplots (int nrows = 1, int ncols = 1, * , bool|Literal sharex["none", "all", "row", "col"] = False, bool|Literal sharey["none", "all", "row", "col"] = False, bool squeeze = True, Sequence|None width_ratios[float] = None, Sequence|None height_ratios[float] = None, dict|None subplot_kw[str, Any] = None, dict|None gridspec_kw[str, Any] = None, ** fig_kw)
Create a figure and a set of subplots.
This utility wrapper makes it convenient to create common layouts of
subplots, including the enclosing figure object, in a single call.
Parameters
----------
nrows, ncols : int, default: 1
    Number of rows/columns of the subplot grid.
sharex, sharey : bool or {'none', 'all', 'row', 'col'}, default: False
    Controls sharing of properties among x (*sharex*) or y (*sharey*)
    axes:
    - True or 'all': x- or y-axis will be shared among all subplots.
    - False or 'none': each subplot x- or y-axis will be independent.
    - 'row': each subplot row will share an x- or y-axis.
    - 'col': each subplot column will share an x- or y-axis.
    When subplots have a shared x-axis along a column, only the x tick
    labels of the bottom subplot are created. Similarly, when subplots
    have a shared y-axis along a row, only the y tick labels of the first
    column subplot are created. To later turn other subplots' ticklabels
    on, use `~matplotlib.axes.Axes.tick_params`.
    When subplots have a shared axis that has units, calling
    `.Axis.set_units` will update each axis with the new units.
    Note that it is not possible to unshare axes.
squeeze : bool, default: True
    - If True, extra dimensions are squeezed out from the returned
      array of `~matplotlib.axes.Axes`:
      - if only one subplot is constructed (nrows=ncols=1), the
        resulting single Axes object is returned as a scalar.
      - for Nx1 or 1xM subplots, the returned object is a 1D numpy
        object array of Axes objects.
      - for NxM, subplots with N>1 and M>1 are returned as a 2D array.
    - If False, no squeezing at all is done: the returned Axes object is
      always a 2D array containing Axes instances, even if it ends up
      being 1x1.
width_ratios : array-like of length *ncols*, optional
    Defines the relative widths of the columns. Each column gets a
    relative width of ``width_ratios[i] / sum(width_ratios)``.
    If not given, all columns will have the same width.  Equivalent
    to ``gridspec_kw={'width_ratios': [...]}``.
height_ratios : array-like of length *nrows*, optional
    Defines the relative heights of the rows. Each row gets a
    relative height of ``height_ratios[i] / sum(height_ratios)``.
    If not given, all rows will have the same height. Convenience
    for ``gridspec_kw={'height_ratios': [...]}``.
subplot_kw : dict, optional
    Dict with keywords passed to the
    `~matplotlib.figure.Figure.add_subplot` call used to create each
    subplot.
gridspec_kw : dict, optional
    Dict with keywords passed to the `~matplotlib.gridspec.GridSpec`
    constructor used to create the grid the subplots are placed on.
**fig_kw
    All additional keyword arguments are passed to the
    `.pyplot.figure` call.
Returns
-------
fig : `.Figure`
ax : `~matplotlib.axes.Axes` or array of Axes
    *ax* can be either a single `~.axes.Axes` object, or an array of Axes
    objects if more than one subplot was created.  The dimensions of the
    resulting array can be controlled with the squeeze keyword, see above.
    Typical idioms for handling the return value are::
        # using the variable ax for single a Axes
        fig, ax = plt.subplots()
        # using the variable axs for multiple Axes
        fig, axs = plt.subplots(2, 2)
        # using tuple unpacking for multiple Axes
        fig, (ax1, ax2) = plt.subplots(1, 2)
        fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2, 2)
    The names ``ax`` and pluralized ``axs`` are preferred over ``axes``
    because for the latter it's not clear if it refers to a single
    `~.axes.Axes` instance or a collection of these.
See Also
--------
.pyplot.figure
.pyplot.subplot
.pyplot.axes
.Figure.subplots
.Figure.add_subplot
Examples
--------
::
    # First create some toy data:
    x = np.linspace(0, 2*np.pi, 400)
    y = np.sin(x**2)
    # Create just a figure and only one subplot
    fig, ax = plt.subplots()
    ax.plot(x, y)
    ax.set_title('Simple plot')
    # Create two subplots and unpack the output array immediately
    f, (ax1, ax2) = plt.subplots(1, 2, sharey=True)
    ax1.plot(x, y)
    ax1.set_title('Sharing Y axis')
    ax2.scatter(x, y)
    # Create four polar Axes and access them through the returned array
    fig, axs = plt.subplots(2, 2, subplot_kw=dict(projection="polar"))
    axs[0, 0].plot(x, y)
    axs[1, 1].scatter(x, y)
    # Share a X axis with each column of subplots
    plt.subplots(2, 2, sharex='col')
    # Share a Y axis with each row of subplots
    plt.subplots(2, 2, sharey='row')
    # Share both X and Y axes with all subplots
    plt.subplots(2, 2, sharex='all', sharey='all')
    # Note that this is the same as
    plt.subplots(2, 2, sharex=True, sharey=True)
    # Create figure number 10 with a single subplot
    # and clears it if it already exists.
    fig, ax = plt.subplots(num=10, clear=True)
Definition at line 1606 of file pyplot.py.
subplots() [2/3]
tuple[Figure, np.ndarray] matplotlib.pyplot.subplots (int nrows = ..., int ncols = ..., * , bool | Literal["none", "all", "row", "col"] sharex = ..., bool | Literal["none", "all", "row", "col"] sharey = ..., Literal[False] squeeze, Sequence[float] | None width_ratios = ..., Sequence[float] | None height_ratios = ..., dict[str, Any] | None subplot_kw = ..., dict[str, Any] | None gridspec_kw = ..., ** fig_kw)
Definition at line 1589 of file pyplot.py.
subplots() [3/3]
tuple[Figure, Axes] matplotlib.pyplot.subplots (Literal[1] nrows = ..., Literal[1] ncols = ..., * , bool | Literal["none", "all", "row", "col"] sharex = ..., bool | Literal["none", "all", "row", "col"] sharey = ..., Literal[True] squeeze = ..., Sequence[float] | None width_ratios = ..., Sequence[float] | None height_ratios = ..., dict[str, Any] | None subplot_kw = ..., dict[str, Any] | None gridspec_kw = ..., ** fig_kw)
Definition at line 1572 of file pyplot.py.
subplots_adjust()
None matplotlib.pyplot.subplots_adjust (float | None left = None, float | None bottom = None, float | None right = None, float | None top = None, float | None wspace = None, float | None hspace = None)
Definition at line 2816 of file pyplot.py.
summer()
None matplotlib.pyplot.summer ()
Set the colormap to 'summer'.
This changes the default colormap as well as the colormap of the current
image if there is one. See ``help(colormaps)`` for more information.
Definition at line 4572 of file pyplot.py.
References set_cmap().
suptitle()
Text matplotlib.pyplot.suptitle (str t, ** kwargs)
Definition at line 2831 of file pyplot.py.
switch_backend()
None matplotlib.pyplot.switch_backend (str newbackend)
Set the pyplot backend.
Switching to an interactive backend is possible only if no event loop for
another interactive backend has started.  Switching to and from
non-interactive backends is always possible.
If the new backend is different than the current backend then all open
Figures will be closed via ``plt.close('all')``.
Parameters
----------
newbackend : str
    The case-insensitive name of the backend to use.
Definition at line 373 of file pyplot.py.
References _get_backend_mod(), matplotlib._parse_to_version_info(), install_repl_displayhook(), matplotlib.is_interactive(), and switch_backend().
Referenced by _get_backend_mod(), and switch_backend().
table()
matplotlib.pyplot.table (cellText = None, cellColours = None, cellLoc = "right", colWidths = None, rowLabels = None, rowColours = None, rowLoc = "left", colLabels = None, colColours = None, colLoc = "center", loc = "bottom", bbox = None, edges = "closed", ** kwargs)
Definition at line 4168 of file pyplot.py.
text()
Text matplotlib.pyplot.text (float x, float y, str s, dict[str, Any] | None fontdict = None, ** kwargs)
Definition at line 4204 of file pyplot.py.
thetagrids()
tuple[list[Line2D], list[Text]] matplotlib.pyplot.thetagrids (ArrayLike | None angles = None, Sequence[str | Text] | None labels = None, str | None fmt = None, ** kwargs)
Get or set the theta gridlines on the current polar plot.
Call signatures::
 lines, labels = thetagrids()
 lines, labels = thetagrids(angles, labels=None, fmt=None, **kwargs)
When called with no arguments, `.thetagrids` simply returns the tuple
(*lines*, *labels*). When called with arguments, the labels will
appear at the specified angles.
Parameters
----------
angles : tuple with floats, degrees
    The angles of the theta gridlines.
labels : tuple with strings or None
    The labels to use at each radial gridline. The
    `.projections.polar.ThetaFormatter` will be used if None.
fmt : str or None
    Format string used in `matplotlib.ticker.FormatStrFormatter`.
    For example '%f'. Note that the angle in radians will be used.
Returns
-------
lines : list of `.lines.Line2D`
    The theta gridlines.
labels : list of `.text.Text`
    The tick labels.
Other Parameters
----------------
**kwargs
    *kwargs* are optional `.Text` properties for the labels.
See Also
--------
.pyplot.rgrids
.projections.polar.PolarAxes.set_thetagrids
.Axis.get_gridlines
.Axis.get_ticklabels
Examples
--------
::
  # set the locations of the angular gridlines
  lines, labels = thetagrids(range(45, 360, 90))
  # set the locations and labels of the angular gridlines
  lines, labels = thetagrids(range(45, 360, 90), ('NE', 'NW', 'SW', 'SE'))
Definition at line 2416 of file pyplot.py.
tick_params()
None matplotlib.pyplot.tick_params (Literal["both", "x", "y"] axis = "both", ** kwargs)
Definition at line 4212 of file pyplot.py.
ticklabel_format()
None matplotlib.pyplot.ticklabel_format (* , Literal["both", "x", "y"] axis = "both", Literal["", "sci", "scientific", "plain"] | None style = None, tuple[int, int] | None scilimits = None, bool | float | None useOffset = None, bool | None useLocale = None, bool | None useMathText = None)
Definition at line 4218 of file pyplot.py.
tight_layout()
None matplotlib.pyplot.tight_layout (* , float pad = 1.08, float | None h_pad = None, float | None w_pad = None, tuple[float, float, float, float] | None rect = None)
Definition at line 2837 of file pyplot.py.
title()
Text matplotlib.pyplot.title (str label, dict[str, Any] | None fontdict = None, Literal["left", "center", "right"] | None loc = None, float | None pad = None, * , float | None y = None, ** kwargs)
Definition at line 4385 of file pyplot.py.
tricontour()
matplotlib.pyplot.tricontour (* args, ** kwargs)
Definition at line 4239 of file pyplot.py.
tricontourf()
matplotlib.pyplot.tricontourf (* args, ** kwargs)
Definition at line 4248 of file pyplot.py.
tripcolor()
matplotlib.pyplot.tripcolor (* args, alpha = 1.0, norm = None, cmap = None, vmin = None, vmax = None, shading = "flat", facecolors = None, ** kwargs)
Definition at line 4257 of file pyplot.py.
triplot()
matplotlib.pyplot.triplot (* args, ** kwargs)
Definition at line 4285 of file pyplot.py.
twinx()
_AxesBase matplotlib.pyplot.twinx (matplotlib.axes.Axes | None ax = None)
Make and return a second Axes that shares the *x*-axis.  The new Axes will
overlay *ax* (or the current Axes if *ax* is *None*), and its ticks will be
on the right.
Examples
--------
:doc:`/gallery/subplots_axes_and_figures/two_scales`
Definition at line 2014 of file pyplot.py.
twiny()
_AxesBase matplotlib.pyplot.twiny (matplotlib.axes.Axes | None ax = None)
Make and return a second Axes that shares the *y*-axis.  The new Axes will
overlay *ax* (or the current Axes if *ax* is *None*), and its ticks will be
on the top.
Examples
--------
:doc:`/gallery/subplots_axes_and_figures/two_scales`
Definition at line 2030 of file pyplot.py.
uninstall_repl_displayhook()
None matplotlib.pyplot.uninstall_repl_displayhook ()
Disconnect from the display hook of the current shell.
Definition at line 326 of file pyplot.py.
References gcf(), and matplotlib.set_loglevel().
Referenced by ioff().
violinplot()
dict[str, Collection] matplotlib.pyplot.violinplot (ArrayLike | Sequence[ArrayLike] dataset, ArrayLike | None positions = None, bool | None vert = None, Literal["vertical", "horizontal"] orientation = "vertical", float | ArrayLike widths = 0.5, bool showmeans = False, bool showextrema = True, bool showmedians = False, Sequence[float | Sequence[float]] | None quantiles = None, int points = 100, Literal["scott", "silverman"] | float | Callable[[GaussianKDE], float] | None bw_method = None, Literal["both", "low", "high"] side = "both", * , data = None)
Definition at line 4291 of file pyplot.py.
viridis()
None matplotlib.pyplot.viridis ()
Set the colormap to 'viridis'.
This changes the default colormap as well as the colormap of the current
image if there is one. See ``help(colormaps)`` for more information.
Definition at line 4627 of file pyplot.py.
References set_cmap().
vlines()
LineCollection matplotlib.pyplot.vlines (float | ArrayLike x, float | ArrayLike ymin, float | ArrayLike ymax, ColorType | Sequence[ColorType] | None colors = None, LineStyleType linestyles = "solid", str label = "", * , data = None, ** kwargs)
Definition at line 4329 of file pyplot.py.
waitforbuttonpress()
None | bool matplotlib.pyplot.waitforbuttonpress (float timeout = -1)
Definition at line 2849 of file pyplot.py.
winter()
None matplotlib.pyplot.winter ()
Set the colormap to 'winter'.
This changes the default colormap as well as the colormap of the current
image if there is one. See ``help(colormaps)`` for more information.
Definition at line 4583 of file pyplot.py.
References set_cmap().
xcorr()
tuple[np.ndarray, np.ndarray, LineCollection | Line2D, Line2D | None] matplotlib.pyplot.xcorr (ArrayLike x, ArrayLike y, bool normed = True, Callable[[ArrayLike], ArrayLike] detrend = mlab.detrend_none, bool usevlines = True, int maxlags = 10, * , data = None, ** kwargs)
Definition at line 4354 of file pyplot.py.
xkcd()
ExitStack matplotlib.pyplot.xkcd (float scale = 1, float length = 100, float randomness = 2)
Turn on `xkcd <https://xkcd.com/>`_ sketch-style drawing mode.
This will only have an effect on things drawn after this function is called.
For best results, install the `xkcd script <https://github.com/ipython/xkcd-font/>`_
font; xkcd fonts are not packaged with Matplotlib.
Parameters
----------
scale : float, optional
    The amplitude of the wiggle perpendicular to the source line.
length : float, optional
    The length of the wiggle along the line.
randomness : float, optional
    The scale factor by which the length is shrunken or expanded.
Notes
-----
This function works by a number of rcParams, so it will probably
override others you have set before.
If you want the effects of this function to be temporary, it can
be used as a context manager, for example::
    with plt.xkcd():
        # This figure will be in XKCD-style
        fig1 = plt.figure()
        # ...
    # This figure will be in regular style
    fig2 = plt.figure()
Definition at line 801 of file pyplot.py.
xlabel()
Text matplotlib.pyplot.xlabel (str xlabel, dict[str, Any] | None fontdict = None, float | None labelpad = None, * , Literal["left", "center", "right"] | None loc = None, ** kwargs)
Definition at line 4399 of file pyplot.py.
xlim()
tuple[float, float] matplotlib.pyplot.xlim (* args, ** kwargs)
Axis ##.
Get or set the x limits of the current Axes.
Call signatures::
    left, right = xlim()  # return the current xlim
    xlim((left, right))   # set the xlim to left, right
    xlim(left, right)     # set the xlim to left, right
If you do not specify args, you can pass *left* or *right* as kwargs,
i.e.::
    xlim(right=3)  # adjust the right leaving left unchanged
    xlim(left=1)  # adjust the left leaving right unchanged
Setting limits turns autoscaling off for the x-axis.
Returns
-------
left, right
    A tuple of the new x-axis limits.
Notes
-----
Calling this function with no arguments (e.g. ``xlim()``) is the pyplot
equivalent of calling `~.Axes.get_xlim` on the current Axes.
Calling this function with arguments is the pyplot equivalent of calling
`~.Axes.set_xlim` on the current Axes. All arguments are passed though.
Definition at line 2092 of file pyplot.py.
xscale()
None matplotlib.pyplot.xscale (str | ScaleBase value, ** kwargs)
Definition at line 4429 of file pyplot.py.
xticks()
tuple[list[Tick] | np.ndarray, list[Text]] matplotlib.pyplot.xticks (ArrayLike | None ticks = None, Sequence[str] | None labels = None, * , bool minor = False, ** kwargs)
Get or set the current tick locations and labels of the x-axis.
Pass no arguments to return the current values without modifying them.
Parameters
----------
ticks : array-like, optional
    The list of xtick locations.  Passing an empty list removes all xticks.
labels : array-like, optional
    The labels to place at the given *ticks* locations.  This argument can
    only be passed if *ticks* is passed as well.
minor : bool, default: False
    If ``False``, get/set the major ticks/labels; if ``True``, the minor
    ticks/labels.
**kwargs
    `.Text` properties can be used to control the appearance of the labels.
    .. warning::
        This only sets the properties of the current ticks, which is
        only sufficient if you either pass *ticks*, resulting in a
        fixed list of ticks, or if the plot is static.
        Ticks are not guaranteed to be persistent. Various operations
        can create, delete and modify the Tick instances. There is an
        imminent risk that these settings can get lost if you work on
        the figure further (including also panning/zooming on a
        displayed figure).
        Use `~.pyplot.tick_params` instead if possible.
Returns
-------
locs
    The list of xtick locations.
labels
    The list of xlabel `.Text` objects.
Notes
-----
Calling this function with no arguments (e.g. ``xticks()``) is the pyplot
equivalent of calling `~.Axes.get_xticks` and `~.Axes.get_xticklabels` on
the current Axes.
Calling this function with arguments is the pyplot equivalent of calling
`~.Axes.set_xticks` and `~.Axes.set_xticklabels` on the current Axes.
Examples
--------
>>> locs, labels = xticks()  # Get the current locations and labels.
>>> xticks(np.arange(0, 1, step=0.2))  # Set label locations.
>>> xticks(np.arange(3), ['Tom', 'Dick', 'Sue'])  # Set text labels.
>>> xticks([0, 1, 2], ['January', 'February', 'March'],
...        rotation=20)  # Set text labels and properties.
>>> xticks([])  # Disable xticks.
Definition at line 2166 of file pyplot.py.
ylabel()
Text matplotlib.pyplot.ylabel (str ylabel, dict[str, Any] | None fontdict = None, float | None labelpad = None, * , Literal["bottom", "center", "top"] | None loc = None, ** kwargs)
Definition at line 4414 of file pyplot.py.
ylim()
tuple[float, float] matplotlib.pyplot.ylim (* args, ** kwargs)
Get or set the y-limits of the current Axes.
Call signatures::
    bottom, top = ylim()  # return the current ylim
    ylim((bottom, top))   # set the ylim to bottom, top
    ylim(bottom, top)     # set the ylim to bottom, top
If you do not specify args, you can alternatively pass *bottom* or
*top* as kwargs, i.e.::
    ylim(top=3)  # adjust the top leaving bottom unchanged
    ylim(bottom=1)  # adjust the bottom leaving top unchanged
Setting limits turns autoscaling off for the y-axis.
Returns
-------
bottom, top
    A tuple of the new y-axis limits.
Notes
-----
Calling this function with no arguments (e.g. ``ylim()``) is the pyplot
equivalent of calling `~.Axes.get_ylim` on the current Axes.
Calling this function with arguments is the pyplot equivalent of calling
`~.Axes.set_ylim` on the current Axes. All arguments are passed though.
Definition at line 2129 of file pyplot.py.
yscale()
None matplotlib.pyplot.yscale (str | ScaleBase value, ** kwargs)
Definition at line 4435 of file pyplot.py.
yticks()
tuple[list[Tick] | np.ndarray, list[Text]] matplotlib.pyplot.yticks (ArrayLike | None ticks = None, Sequence[str] | None labels = None, * , bool minor = False, ** kwargs)
Get or set the current tick locations and labels of the y-axis.
Pass no arguments to return the current values without modifying them.
Parameters
----------
ticks : array-like, optional
    The list of ytick locations.  Passing an empty list removes all yticks.
labels : array-like, optional
    The labels to place at the given *ticks* locations.  This argument can
    only be passed if *ticks* is passed as well.
minor : bool, default: False
    If ``False``, get/set the major ticks/labels; if ``True``, the minor
    ticks/labels.
**kwargs
    `.Text` properties can be used to control the appearance of the labels.
    .. warning::
        This only sets the properties of the current ticks, which is
        only sufficient if you either pass *ticks*, resulting in a
        fixed list of ticks, or if the plot is static.
        Ticks are not guaranteed to be persistent. Various operations
        can create, delete and modify the Tick instances. There is an
        imminent risk that these settings can get lost if you work on
        the figure further (including also panning/zooming on a
        displayed figure).
        Use `~.pyplot.tick_params` instead if possible.
Returns
-------
locs
    The list of ytick locations.
labels
    The list of ylabel `.Text` objects.
Notes
-----
Calling this function with no arguments (e.g. ``yticks()``) is the pyplot
equivalent of calling `~.Axes.get_yticks` and `~.Axes.get_yticklabels` on
the current Axes.
Calling this function with arguments is the pyplot equivalent of calling
`~.Axes.set_yticks` and `~.Axes.set_yticklabels` on the current Axes.
Examples
--------
>>> locs, labels = yticks()  # Get the current locations and labels.
>>> yticks(np.arange(0, 1, step=0.2))  # Set label locations.
>>> yticks(np.arange(3), ['Tom', 'Dick', 'Sue'])  # Set text labels.
>>> yticks([0, 1, 2], ['January', 'February', 'March'],
...        rotation=45)  # Set text labels and properties.
>>> yticks([])  # Disable yticks.
Definition at line 2252 of file pyplot.py.
Variable Documentation
__doc__
matplotlib.pyplot.__doc__ private
Definition at line 1262 of file pyplot.py.
_backend_mod
type matplotlib.pyplot._backend_mod = None protected
Definition at line 356 of file pyplot.py.
_log
matplotlib.pyplot._log = logging.getLogger(__name__) protected
Definition at line 156 of file pyplot.py.
_NO_PYPLOT_NOTE
list matplotlib.pyplot._NO_PYPLOT_NOTE protected
Initial value:
=  [
    'FigureBase._gci',  # wrapped_func is private
    '_AxesBase._sci',  # wrapped_func is private
    'Artist.findobj',  # not a standard pyplot wrapper because it does not operate
                       # on the current Figure / Axes. Explanation of relation would
                       # be more complex and is not too important.
]
Definition at line 200 of file pyplot.py.
_P
matplotlib.pyplot._P = ParamSpec('_P') protected
Definition at line 137 of file pyplot.py.
_R
matplotlib.pyplot._R = TypeVar('_R') protected
Definition at line 138 of file pyplot.py.
_REPL_DISPLAYHOOK
matplotlib.pyplot._REPL_DISPLAYHOOK = _ReplDisplayHook.NONE protected
Definition at line 274 of file pyplot.py.
_ReplDisplayHook
matplotlib.pyplot._ReplDisplayHook = Enum("_ReplDisplayHook", ["NONE", "PLAIN", "IPYTHON"]) protected
Global ##.
Definition at line 273 of file pyplot.py.
_T
matplotlib.pyplot._T = TypeVar('_T') protected
Definition at line 139 of file pyplot.py.
available_backends
matplotlib.pyplot.available_backends = backend_registry.list_builtin(BackendFilter.INTERACTIVE)
Definition at line 2729 of file pyplot.py.
color_sequences
matplotlib.pyplot.color_sequences = _color_sequences
Definition at line 161 of file pyplot.py.
colormaps
matplotlib.pyplot.colormaps = _colormaps
Definition at line 160 of file pyplot.py.
draw_all
matplotlib.pyplot.draw_all = _pylab_helpers.Gcf.draw_all
Definition at line 336 of file pyplot.py.
requested_backend
matplotlib.pyplot.requested_backend = rcParams._get_backend_or_none()
Definition at line 2727 of file pyplot.py.