Code Cloning Analysis: pip._vendor.chardet.eucjpprober.EUCJPProber Class Reference
pip._vendor.chardet.eucjpprober.EUCJPProber Class Reference
Public Member Functions
None __init__ (self)
None reset (self)
str charset_name (self)
str language (self)
ProbingState feed (self, Union[bytes, bytearray] byte_str)
float get_confidence (self)
Public Member Functions inherited from pip._vendor.chardet.mbcharsetprober.MultiByteCharSetProber
None __init__ (self, LanguageFilter lang_filter=LanguageFilter.NONE)
Public Member Functions inherited from pip._vendor.chardet.charsetprober.CharSetProber
None __init__ (self, LanguageFilter lang_filter=LanguageFilter.NONE)
ProbingState state (self)
Public Attributes
context_analyzer = EUCJPContextAnalysis()
Public Attributes inherited from pip._vendor.chardet.mbcharsetprober.MultiByteCharSetProber
Optional[CharDistributionAnalysis] distribution_analyzer = None
Optional[CodingStateMachine] coding_sm = None
Public Attributes inherited from pip._vendor.chardet.charsetprober.CharSetProber
bool active = True
lang_filter = lang_filter
logger = logging.getLogger(__name__)
Additional Inherited Members
Static Public Member Functions inherited from pip._vendor.chardet.charsetprober.CharSetProber
bytes filter_high_byte_only (Union[bytes, bytearray] buf)
bytearray filter_international_words (Union[bytes, bytearray] buf)
bytes remove_xml_tags (Union[bytes, bytearray] buf)
Static Public Attributes inherited from pip._vendor.chardet.charsetprober.CharSetProber
float SHORTCUT_THRESHOLD = 0.95
Protected Attributes inherited from pip._vendor.chardet.mbcharsetprober.MultiByteCharSetProber
_last_char = bytearray(b"\0\0")
Protected Attributes inherited from pip._vendor.chardet.charsetprober.CharSetProber
_state = ProbingState.DETECTING
Detailed Description
Definition at line 38 of file eucjpprober.py.
Constructor & Destructor Documentation
__init__()
None pip._vendor.chardet.eucjpprober.EUCJPProber.__init__ (self)
Definition at line 39 of file eucjpprober.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
charset_name()
str pip._vendor.chardet.eucjpprober.EUCJPProber.charset_name (self)
Reimplemented from pip._vendor.chardet.mbcharsetprober.MultiByteCharSetProber.
Definition at line 51 of file eucjpprober.py.
feed()
ProbingState pip._vendor.chardet.eucjpprober.EUCJPProber.feed (self, Union[bytes, bytearray] byte_str)
Reimplemented from pip._vendor.chardet.mbcharsetprober.MultiByteCharSetProber.
Definition at line 58 of file eucjpprober.py.
get_confidence()
float pip._vendor.chardet.eucjpprober.EUCJPProber.get_confidence (self)
Reimplemented from pip._vendor.chardet.mbcharsetprober.MultiByteCharSetProber.
Definition at line 97 of file eucjpprober.py.
language()
str pip._vendor.chardet.eucjpprober.EUCJPProber.language (self)
Reimplemented from pip._vendor.chardet.mbcharsetprober.MultiByteCharSetProber.
Definition at line 55 of file eucjpprober.py.
reset()
None pip._vendor.chardet.eucjpprober.EUCJPProber.reset (self)
Reimplemented from pip._vendor.chardet.mbcharsetprober.MultiByteCharSetProber.
Definition at line 46 of file eucjpprober.py.
Referenced by scipy._lib._docscrape.Reader.__init__().
Member Data Documentation
context_analyzer
pip._vendor.chardet.eucjpprober.EUCJPProber.context_analyzer = EUCJPContextAnalysis()
Definition at line 43 of file eucjpprober.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pip/_vendor/chardet/eucjpprober.py