Code Cloning Analysis: fontTools.ttLib.ttGlyphSet.LerpGlyphSet Class Reference
fontTools.ttLib.ttGlyphSet.LerpGlyphSet Class Reference
Public Member Functions
__init__ (self, glyphset1, glyphset2, factor=0.5)
__getitem__ (self, glyphname)
__contains__ (self, glyphname)
__iter__ (self)
__len__ (self)
Public Attributes
glyphset1 = glyphset1
glyphset2 = glyphset2
factor = factor
Detailed Description
A glyphset that interpolates between two other glyphsets.
Factor is typically between 0 and 1. 0 means the first glyphset,
1 means the second glyphset, and 0.5 means the average of the
two glyphsets. Other values are possible, and can be useful to
extrapolate. Defaults to 0.5.
Definition at line 444 of file ttGlyphSet.py.
Constructor & Destructor Documentation
__init__()
fontTools.ttLib.ttGlyphSet.LerpGlyphSet.__init__ (self, glyphset1, glyphset2, factor = 0.5)
Definition at line 453 of file ttGlyphSet.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__contains__()
fontTools.ttLib.ttGlyphSet.LerpGlyphSet.__contains__ (self, glyphname)
Definition at line 463 of file ttGlyphSet.py.
__getitem__()
fontTools.ttLib.ttGlyphSet.LerpGlyphSet.__getitem__ (self, glyphname)
Definition at line 458 of file ttGlyphSet.py.
__iter__()
fontTools.ttLib.ttGlyphSet.LerpGlyphSet.__iter__ (self)
Definition at line 466 of file ttGlyphSet.py.
__len__()
fontTools.ttLib.ttGlyphSet.LerpGlyphSet.__len__ (self)
Definition at line 471 of file ttGlyphSet.py.
Member Data Documentation
factor
fontTools.ttLib.ttGlyphSet.LerpGlyphSet.factor = factor
Definition at line 456 of file ttGlyphSet.py.
Referenced by scipy.stats._kde.gaussian_kde._compute_covariance(), and sklearn.model_selection._search_successive_halving.BaseSuccessiveHalving._run_search().
glyphset1
fontTools.ttLib.ttGlyphSet.LerpGlyphSet.glyphset1 = glyphset1
Definition at line 454 of file ttGlyphSet.py.
glyphset2
fontTools.ttLib.ttGlyphSet.LerpGlyphSet.glyphset2 = glyphset2
Definition at line 455 of file ttGlyphSet.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ttLib/ttGlyphSet.py