Code Cloning Analysis: fontTools.svgLib.path.shapes.PathBuilder Class Reference
fontTools.svgLib.path.shapes.PathBuilder Class Reference
Public Member Functions
__init__ (self)
M (self, x, y)
m (self, x, y)
A (self, rx, ry, x, y, large_arc=0)
a (self, rx, ry, x, y, large_arc=0)
H (self, x)
h (self, x)
V (self, y)
v (self, y)
L (self, x, y)
l (self, x, y)
add_path_from_element (self, el)
Public Attributes
list paths = []
list transforms = []
Protected Member Functions
_start_path (self, initial_path="")
_end_path (self)
_add (self, path_snippet)
_move (self, c, x, y)
_arc (self, c, rx, ry, x, y, large_arc)
_vhline (self, c, x)
_line (self, c, x, y)
_parse_line (self, line)
_parse_rect (self, rect)
_parse_path (self, path)
_parse_polygon (self, poly)
_parse_polyline (self, poly)
_parse_circle (self, circle)
_parse_ellipse (self, ellipse)
Detailed Description
Definition at line 36 of file shapes.py.
Constructor & Destructor Documentation
__init__()
fontTools.svgLib.path.shapes.PathBuilder.__init__ (self)
Definition at line 37 of file shapes.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_add()
fontTools.svgLib.path.shapes.PathBuilder._add (self, path_snippet) protected
Definition at line 48 of file shapes.py.
Referenced by numpy.polynomial._polybase.ABCPolyBase._str_term_ascii(), and pip._vendor.rich.style.Style.test().
_arc()
fontTools.svgLib.path.shapes.PathBuilder._arc (self, c, rx, ry, x, y, large_arc) protected
Definition at line 65 of file shapes.py.
Referenced by matplotlib.sankey.Sankey._add_input(), and matplotlib.sankey.Sankey._add_output().
_end_path()
fontTools.svgLib.path.shapes.PathBuilder._end_path (self) protected
Definition at line 45 of file shapes.py.
_line()
fontTools.svgLib.path.shapes.PathBuilder._line (self, c, x, y) protected
Definition at line 92 of file shapes.py.
Referenced by numpy.polynomial._polybase.ABCPolyBase.identity().
_move()
fontTools.svgLib.path.shapes.PathBuilder._move (self, c, x, y) protected
Definition at line 56 of file shapes.py.
_parse_circle()
fontTools.svgLib.path.shapes.PathBuilder._parse_circle (self, circle) protected
Definition at line 152 of file shapes.py.
_parse_ellipse()
fontTools.svgLib.path.shapes.PathBuilder._parse_ellipse (self, ellipse) protected
Definition at line 163 of file shapes.py.
_parse_line()
fontTools.svgLib.path.shapes.PathBuilder._parse_line (self, line) protected
Definition at line 101 of file shapes.py.
_parse_path()
fontTools.svgLib.path.shapes.PathBuilder._parse_path (self, path) protected
Definition at line 139 of file shapes.py.
_parse_polygon()
fontTools.svgLib.path.shapes.PathBuilder._parse_polygon (self, poly) protected
Definition at line 143 of file shapes.py.
_parse_polyline()
fontTools.svgLib.path.shapes.PathBuilder._parse_polyline (self, poly) protected
Definition at line 148 of file shapes.py.
_parse_rect()
fontTools.svgLib.path.shapes.PathBuilder._parse_rect (self, rect) protected
Definition at line 111 of file shapes.py.
_start_path()
fontTools.svgLib.path.shapes.PathBuilder._start_path (self, initial_path = "") protected
Definition at line 41 of file shapes.py.
_vhline()
fontTools.svgLib.path.shapes.PathBuilder._vhline (self, c, x) protected
Definition at line 77 of file shapes.py.
A()
fontTools.svgLib.path.shapes.PathBuilder.A (self, rx, ry, x, y, large_arc = 0)
Definition at line 71 of file shapes.py.
a()
fontTools.svgLib.path.shapes.PathBuilder.a (self, rx, ry, x, y, large_arc = 0)
Definition at line 74 of file shapes.py.
add_path_from_element()
fontTools.svgLib.path.shapes.PathBuilder.add_path_from_element (self, el)
Definition at line 175 of file shapes.py.
H()
fontTools.svgLib.path.shapes.PathBuilder.H (self, x)
Definition at line 80 of file shapes.py.
h()
fontTools.svgLib.path.shapes.PathBuilder.h (self, x)
Definition at line 83 of file shapes.py.
L()
fontTools.svgLib.path.shapes.PathBuilder.L (self, x, y)
Definition at line 95 of file shapes.py.
l()
fontTools.svgLib.path.shapes.PathBuilder.l (self, x, y)
Definition at line 98 of file shapes.py.
M()
fontTools.svgLib.path.shapes.PathBuilder.M (self, x, y)
Definition at line 59 of file shapes.py.
m()
fontTools.svgLib.path.shapes.PathBuilder.m (self, x, y)
Definition at line 62 of file shapes.py.
V()
fontTools.svgLib.path.shapes.PathBuilder.V (self, y)
Definition at line 86 of file shapes.py.
v()
fontTools.svgLib.path.shapes.PathBuilder.v (self, y)
Definition at line 89 of file shapes.py.
Member Data Documentation
paths
list fontTools.svgLib.path.shapes.PathBuilder.paths = []
Definition at line 38 of file shapes.py.
Referenced by matplotlib.backends.backend_pdf.PdfFile.__init__(), matplotlib.backends.backend_pdf.PdfFile.finalize(), and matplotlib.backends.backend_pdf.PdfFile.markerObject().
transforms
list fontTools.svgLib.path.shapes.PathBuilder.transforms = []
Definition at line 39 of file shapes.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/svgLib/path/shapes.py