Code Cloning Analysis: pandas.io.excel._base.BaseExcelReader Class Reference
pandas.io.excel._base.BaseExcelReader Class Reference
Public Member Functions
None __init__ (self, filepath_or_buffer, StorageOptions|None storage_options=None, dict|None engine_kwargs=None)
_WorkbookT load_workbook (self, filepath_or_buffer, engine_kwargs)
None close (self)
list[str] sheet_names (self)
get_sheet_by_name (self, str name)
get_sheet_by_index (self, int index)
get_sheet_data (self, sheet, int|None rows=None)
None raise_if_bad_sheet_by_index (self, int index)
None raise_if_bad_sheet_by_name (self, str name)
parse (self, str|int|list[int]|list[str]|None sheet_name=0, int|Sequence[int]|None header=0, SequenceNotStr[Hashable]|range|None names=None, int|Sequence[int]|None index_col=None, usecols=None, DtypeArg|None dtype=None, Iterable[Hashable]|None true_values=None, Iterable[Hashable]|None false_values=None, Sequence[int]|int|Callable[[int], object]|None skiprows=None, int|None nrows=None, na_values=None, bool verbose=False, list|dict|bool parse_dates=False, Callable|lib.NoDefault date_parser=lib.no_default, dict[Hashable, str]|str|None date_format=None, str|None thousands=None, str decimal=".", str|None comment=None, int skipfooter=0, DtypeBackend|lib.NoDefault dtype_backend=lib.no_default, **kwds)
Public Attributes
handles
_WorkbookT book = self.handles.handle
sheet_names
Protected Member Functions
type[_WorkbookT] _workbook_class (self)
int _check_skiprows_func (self, Callable skiprows, int rows_to_use)
int|None _calc_rows (self, int|Sequence[int]|None header, int|Sequence[int]|None index_col, Sequence[int]|int|Callable[[int], object]|None skiprows, int|None nrows)
Protected Attributes
_workbook_class
Detailed Description
Definition at line 543 of file _base.py.
Constructor & Destructor Documentation
__init__()
None pandas.io.excel._base.BaseExcelReader.__init__ (self, filepath_or_buffer, StorageOptions | None storage_options = None, dict | None engine_kwargs = None)
Definition at line 546 of file _base.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_calc_rows()
int | None pandas.io.excel._base.BaseExcelReader._calc_rows (self, int | Sequence[int] | None header, int | Sequence[int] | None index_col, Sequence[int] | int | Callable[[int], object] | None skiprows, int | None nrows) protected
If nrows specified, find the number of rows needed from the
file, otherwise return None.
Parameters
----------
header : int, list of int, or None
    See read_excel docstring.
index_col : int, str, list of int, or None
    See read_excel docstring.
skiprows : list-like, int, callable, or None
    See read_excel docstring.
nrows : int or None
    See read_excel docstring.
Returns
-------
int or None
Definition at line 655 of file _base.py.
References _calc_rows(), _check_skiprows_func(), get_sheet_by_index(), get_sheet_by_name(), get_sheet_data(), and sheet_names.
Referenced by _calc_rows().
_check_skiprows_func()
int pandas.io.excel._base.BaseExcelReader._check_skiprows_func (self, Callable skiprows, int rows_to_use) protected
Determine how many file rows are required to obtain `nrows` data
rows when `skiprows` is a function.
Parameters
----------
skiprows : function
    The function passed to read_excel by the user.
rows_to_use : int
    The number of rows that will be needed for the header and
    the data.
Returns
-------
int
Definition at line 626 of file _base.py.
Referenced by _calc_rows().
_workbook_class()
type[_WorkbookT] pandas.io.excel._base.BaseExcelReader._workbook_class (self) protected
Definition at line 583 of file _base.py.
close()
None pandas.io.excel._base.BaseExcelReader.close (self)
Definition at line 589 of file _base.py.
Referenced by pandas.io.pytables.HDFStore.__contains__(), pandas.io.parsers.python_parser.PythonParser.__init__(), pip._vendor.urllib3.util.ssltransport.SSLTransport.__init__(), pip._vendor.urllib3.contrib.securetransport.WrappedSocket._custom_validate(), pandas.io.excel._odfreader.ODFReader._get_row_repeat(), pip._vendor.urllib3.contrib.securetransport.WrappedSocket._raise_on_error(), pandas.io.parsers.c_parser_wrapper.CParserWrapper._set_noconvert_columns(), pandas.io.excel._base.ExcelWriter.check_extension(), pandas.io.excel._base.ExcelFile.close(), pandas.io.json._json.JsonReader.close(), scipy.io._fortran.FortranFile.close(), scipy.io._netcdf.netcdf_file.close(), pandas.io.sas.sas7bdat.SAS7BDATReader.column_types(), PIL.ImageFile.Parser.feed(), pandas.io.sas.sas_xport.XportReader.get_chunk(), pip._vendor.urllib3.contrib.securetransport.WrappedSocket.handshake(), pandas.io.pytables.HDFStore.open(), PIL.PngImagePlugin.ChunkStream.read(), PIL.ContainerIO.ContainerIO.readlines(), pandas.io.excel._odfreader.ODFReader.sheet_names(), and pip._vendor.urllib3.response.HTTPResponse.supports_chunked_reads().
get_sheet_by_index()
pandas.io.excel._base.BaseExcelReader.get_sheet_by_index (self, int index)
Definition at line 609 of file _base.py.
Referenced by _calc_rows().
get_sheet_by_name()
pandas.io.excel._base.BaseExcelReader.get_sheet_by_name (self, str name)
Definition at line 606 of file _base.py.
Referenced by _calc_rows().
get_sheet_data()
pandas.io.excel._base.BaseExcelReader.get_sheet_data (self, sheet, int | None rows = None)
Reimplemented in pandas.io.excel._odfreader.ODFReader.
Definition at line 612 of file _base.py.
Referenced by _calc_rows().
load_workbook()
_WorkbookT pandas.io.excel._base.BaseExcelReader.load_workbook (self, filepath_or_buffer, engine_kwargs)
Definition at line 586 of file _base.py.
parse()
pandas.io.excel._base.BaseExcelReader.parse (self, str | int | list[int] | list[str] | None sheet_name = 0, int | Sequence[int] | None header = 0, SequenceNotStr[Hashable] | range | None names = None, int | Sequence[int] | None index_col = None, usecols = None, DtypeArg | None dtype = None, Iterable[Hashable] | None true_values = None, Iterable[Hashable] | None false_values = None, Sequence[int] | int | Callable[[int], object] | None skiprows = None, int | None nrows = None, na_values = None, bool verbose = False, list | dict | bool parse_dates = False, Callable | lib.NoDefault date_parser = lib.no_default, dict[Hashable, str] | str | None date_format = None, str | None thousands = None, str decimal = ".", str | None comment = None, int skipfooter = 0, DtypeBackend | lib.NoDefault dtype_backend = lib.no_default, ** kwds)
Definition at line 719 of file _base.py.
Referenced by pandas.io.formats.css.CSSResolver.__call__(), and pip._vendor.rich.style.Style.normalize().
raise_if_bad_sheet_by_index()
None pandas.io.excel._base.BaseExcelReader.raise_if_bad_sheet_by_index (self, int index)
Definition at line 615 of file _base.py.
Referenced by pandas.io.excel._calamine.CalamineReader.__init__(), pandas.io.excel._openpyxl.OpenpyxlReader.__init__(), pandas.io.excel._pyxlsb.PyxlsbReader.__init__(), pandas.io.excel._xlrd.XlrdReader.__init__(), and pandas.io.excel._odfreader.ODFReader.sheet_names().
raise_if_bad_sheet_by_name()
None pandas.io.excel._base.BaseExcelReader.raise_if_bad_sheet_by_name (self, str name)
Definition at line 622 of file _base.py.
Referenced by pandas.io.excel._calamine.CalamineReader.__init__(), pandas.io.excel._openpyxl.OpenpyxlReader.__init__(), pandas.io.excel._pyxlsb.PyxlsbReader.__init__(), pandas.io.excel._xlrd.XlrdReader.__init__(), and pandas.io.excel._odfreader.ODFReader.sheet_names().
sheet_names()
list[str] pandas.io.excel._base.BaseExcelReader.sheet_names (self)
Reimplemented in pandas.io.excel._odfreader.ODFReader.
Definition at line 603 of file _base.py.
Member Data Documentation
_workbook_class
pandas.io.excel._base.BaseExcelReader._workbook_class protected
Initial value:
=  get_handle(
                filepath_or_buffer, "rb", storage_options=storage_options, is_text=False
            )
Definition at line 562 of file _base.py.
book
pandas.io.excel._base.BaseExcelReader.book = self.handles.handle
Definition at line 568 of file _base.py.
Referenced by pandas.io.excel._calamine.CalamineReader.__init__(), pandas.io.excel._openpyxl.OpenpyxlReader.__init__(), pandas.io.excel._pyxlsb.PyxlsbReader.__init__(), pandas.io.excel._xlrd.XlrdReader.__init__(), pandas.io.excel._odswriter.ODSWriter._create_freeze_panes(), pandas.io.excel._odswriter.ODSWriter._process_style(), pandas.io.excel._odswriter.ODSWriter._save(), pandas.io.excel._openpyxl.OpenpyxlWriter._save(), pandas.io.excel._xlsxwriter.XlsxWriter._save(), pandas.io.excel._odswriter.ODSWriter._write_cells(), pandas.io.excel._openpyxl.OpenpyxlWriter._write_cells(), pandas.io.excel._xlsxwriter.XlsxWriter._write_cells(), pandas.io.excel._odfreader.ODFReader.sheet_names(), pandas.io.excel._odswriter.ODSWriter.sheets(), pandas.io.excel._openpyxl.OpenpyxlWriter.sheets(), and pandas.io.excel._xlsxwriter.XlsxWriter.sheets().
handles
pandas.io.excel._base.BaseExcelReader.handles
Initial value:
=  IOHandles(
            handle=filepath_or_buffer, compression={"method": None}
        )
Definition at line 559 of file _base.py.
Referenced by pandas.io.json._json.JsonReader._get_data_from_filepath(), pandas.io.json._json.JsonReader.close(), and pandas.io.sas.sas7bdat.SAS7BDATReader.column_types().
sheet_names
pandas.io.excel._base.BaseExcelReader.sheet_names
Reimplemented in pandas.io.excel._odfreader.ODFReader.
Definition at line 623 of file _base.py.
Referenced by _calc_rows().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/io/excel/_base.py