Code Cloning Analysis: pandas.core.arrays.datetimes Namespace Reference
pandas.core.arrays.datetimes Namespace Reference
Classes
class DatetimeArray
Functions
DatetimeTZDtype tz_to_dtype (tzinfo tz, str unit=...)
np.dtype[np.datetime64] tz_to_dtype (None tz, str unit=...)
np.dtype[np.datetime64]|DatetimeTZDtype tz_to_dtype (tzinfo|None tz, str unit="ns")
_field_accessor (str name, str field, str|None docstring=None)
_sequence_to_dt64 (ArrayLike data, *, bool copy=False, tzinfo|None tz=None, bool dayfirst=False, bool yearfirst=False, TimeAmbiguous ambiguous="raise", str|None out_unit=None)
tuple[np.ndarray, bool] _construct_from_dt64_naive (np.ndarray data, *, tzinfo|None tz, bool copy, TimeAmbiguous ambiguous)
objects_to_datetime64 (np.ndarray data, dayfirst, yearfirst, bool utc=False, DateTimeErrorChoices errors="raise", bool allow_object=False, str out_unit="ns")
maybe_convert_dtype (data, bool copy, tzinfo|None tz=None)
tzinfo|None _maybe_infer_tz (tzinfo|None tz, tzinfo|None inferred_tz)
_validate_dt64_dtype (dtype)
tzinfo|None _validate_tz_from_dtype (dtype, tzinfo|None tz, bool explicit_tz_none=False)
tzinfo|None _infer_tz_from_endpoints (Timestamp start, Timestamp end, tzinfo|None tz)
_maybe_normalize_endpoints (Timestamp|None start, Timestamp|None end, bool normalize)
Timestamp|None _maybe_localize_point (Timestamp|None ts, freq, tz, ambiguous, nonexistent)
_generate_range (Timestamp|None start, Timestamp|None end, int|None periods, BaseOffset offset, *, str unit)
Variables
int _ITER_CHUNKSIZE = 10_000
_bool_ops
_object_ops = fields.get_date_field(values, field, reso=self._creso)
Function Documentation
_construct_from_dt64_naive()
tuple[np.ndarray, bool] pandas.core.arrays.datetimes._construct_from_dt64_naive (np.ndarray data, * , tzinfo | None tz, bool copy, TimeAmbiguous ambiguous) protected
Convert datetime64 data to a supported dtype, localizing if necessary.
Definition at line 2327 of file datetimes.py.
Referenced by _sequence_to_dt64().
_field_accessor()
pandas.core.arrays.datetimes._field_accessor (str name, str field, str | None docstring = None) protected
Definition at line 126 of file datetimes.py.
_generate_range()
pandas.core.arrays.datetimes._generate_range (Timestamp | None start, Timestamp | None end, int | None periods, BaseOffset offset, * , str unit) protected
Generates a sequence of dates corresponding to the specified time
offset. Similar to dateutil.rrule except uses pandas DateOffset
objects to represent time increments.
Parameters
----------
start : Timestamp or None
end : Timestamp or None
periods : int or None
offset : DateOffset
unit : str
Notes
-----
* This method is faster for generating weekdays than dateutil.rrule
* At least two of (start, end, periods) must be specified.
* If both start and end are specified, the returned dates will
satisfy start <= date <= end.
Returns
-------
dates : generator object
Definition at line 2729 of file datetimes.py.
_infer_tz_from_endpoints()
tzinfo | None pandas.core.arrays.datetimes._infer_tz_from_endpoints (Timestamp start, Timestamp end, tzinfo | None tz) protected
If a timezone is not explicitly given via `tz`, see if one can
be inferred from the `start` and `end` endpoints.  If more than one
of these inputs provides a timezone, require that they all agree.
Parameters
----------
start : Timestamp
end : Timestamp
tz : tzinfo or None
Returns
-------
tz : tzinfo or None
Raises
------
TypeError : if start and end timezones do not agree
Definition at line 2640 of file datetimes.py.
Referenced by pandas.core.arrays.datetimes.DatetimeArray._from_sequence_not_strict().
_maybe_infer_tz()
tzinfo | None pandas.core.arrays.datetimes._maybe_infer_tz (tzinfo | None tz, tzinfo | None inferred_tz) protected
If a timezone is inferred from data, check that it is compatible with
the user-provided timezone, if any.
Parameters
----------
tz : tzinfo or None
inferred_tz : tzinfo or None
Returns
-------
tz : tzinfo or None
Raises
------
TypeError : if both timezones are present but do not match
Definition at line 2501 of file datetimes.py.
Referenced by _sequence_to_dt64().
_maybe_localize_point()
Timestamp | None pandas.core.arrays.datetimes._maybe_localize_point (Timestamp | None ts, freq, tz, ambiguous, nonexistent) protected
Localize a start or end Timestamp to the timezone of the corresponding
start or end Timestamp
Parameters
----------
ts : start or end Timestamp to potentially localize
freq : Tick, DateOffset, or None
tz : str, timezone object or None
ambiguous: str, localization behavior for ambiguous times
nonexistent: str, localization behavior for nonexistent times
Returns
-------
ts : Timestamp
Definition at line 2696 of file datetimes.py.
Referenced by pandas.core.arrays.datetimes.DatetimeArray._from_sequence_not_strict().
_maybe_normalize_endpoints()
pandas.core.arrays.datetimes._maybe_normalize_endpoints (Timestamp | None start, Timestamp | None end, bool normalize) protected
Definition at line 2683 of file datetimes.py.
_sequence_to_dt64()
pandas.core.arrays.datetimes._sequence_to_dt64 (ArrayLike data, * , bool copy = False, tzinfo | None tz = None, bool dayfirst = False, bool yearfirst = False, TimeAmbiguous ambiguous = "raise", str | None out_unit = None) protected
Parameters
----------
data : np.ndarray or ExtensionArray
    dtl.ensure_arraylike_for_datetimelike has already been called.
copy : bool, default False
tz : tzinfo or None, default None
dayfirst : bool, default False
yearfirst : bool, default False
ambiguous : str, bool, or arraylike, default 'raise'
    See pandas._libs.tslibs.tzconversion.tz_localize_to_utc.
out_unit : str or None, default None
    Desired output resolution.
Returns
-------
result : numpy.ndarray
    The sequence converted to a numpy array with dtype ``datetime64[unit]``.
    Where `unit` is "ns" unless specified otherwise by `out_unit`.
tz : tzinfo or None
    Either the user-provided tzinfo or one inferred from the data.
Raises
------
TypeError : PeriodDType data is passed
Definition at line 2201 of file datetimes.py.
References _construct_from_dt64_naive(), _maybe_infer_tz(), maybe_convert_dtype(), and objects_to_datetime64().
Referenced by pandas.core.arrays.datetimes.DatetimeArray._from_sequence_not_strict().
_validate_dt64_dtype()
pandas.core.arrays.datetimes._validate_dt64_dtype (dtype) protected
Check that a dtype, if passed, represents either a numpy datetime64[ns]
dtype or a pandas DatetimeTZDtype.
Parameters
----------
dtype : object
Returns
-------
dtype : None, numpy.dtype, or DatetimeTZDtype
Raises
------
ValueError : invalid dtype
Notes
-----
Unlike _validate_tz_from_dtype, this does _not_ allow non-existent
tz errors to go through
Definition at line 2531 of file datetimes.py.
Referenced by pandas.core.arrays.datetimes.DatetimeArray._from_sequence_not_strict().
_validate_tz_from_dtype()
tzinfo | None pandas.core.arrays.datetimes._validate_tz_from_dtype (dtype, tzinfo | None tz, bool explicit_tz_none = False) protected
If the given dtype is a DatetimeTZDtype, extract the implied
tzinfo object from it and check that it does not conflict with the given
tz.
Parameters
----------
dtype : dtype, str
tz : None, tzinfo
explicit_tz_none : bool, default False
    Whether tz=None was passed explicitly, as opposed to lib.no_default.
Returns
-------
tz : consensus tzinfo
Raises
------
ValueError : on tzinfo mismatch
Definition at line 2587 of file datetimes.py.
Referenced by pandas.core.arrays.datetimes.DatetimeArray._from_sequence_not_strict().
maybe_convert_dtype()
pandas.core.arrays.datetimes.maybe_convert_dtype (data, bool copy, tzinfo | None tz = None)
Convert data based on dtype conventions, issuing
errors where appropriate.
Parameters
----------
data : np.ndarray or pd.Index
copy : bool
tz : tzinfo or None, default None
Returns
-------
data : np.ndarray or pd.Index
copy : bool
Raises
------
TypeError : PeriodDType data is passed
Definition at line 2445 of file datetimes.py.
Referenced by _sequence_to_dt64().
objects_to_datetime64()
pandas.core.arrays.datetimes.objects_to_datetime64 (np.ndarray data, dayfirst, yearfirst, bool utc = False, DateTimeErrorChoices errors = "raise", bool allow_object = False, str out_unit = "ns")
Convert data to array of timestamps.
Parameters
----------
data : np.ndarray[object]
dayfirst : bool
yearfirst : bool
utc : bool, default False
    Whether to convert/localize timestamps to UTC.
errors : {'raise', 'ignore', 'coerce'}
allow_object : bool
    Whether to return an object-dtype ndarray instead of raising if the
    data contains more than one timezone.
out_unit : str, default "ns"
Returns
-------
result : ndarray
    np.datetime64[out_unit] if returned values represent wall times or UTC
    timestamps.
    object if mixed timezones
inferred_tz : tzinfo or None
    If not None, then the datetime64 values in `result` denote UTC timestamps.
Raises
------
ValueError : if data cannot be converted to datetimes
TypeError  : When a type cannot be converted to datetime
Definition at line 2371 of file datetimes.py.
Referenced by _sequence_to_dt64().
tz_to_dtype() [1/3]
np.dtype[np.datetime64] pandas.core.arrays.datetimes.tz_to_dtype (None tz, str unit = ...)
Definition at line 101 of file datetimes.py.
tz_to_dtype() [2/3]
DatetimeTZDtype pandas.core.arrays.datetimes.tz_to_dtype (tzinfo tz, str unit = ...)
Definition at line 96 of file datetimes.py.
tz_to_dtype() [3/3]
np.dtype[np.datetime64] | DatetimeTZDtype pandas.core.arrays.datetimes.tz_to_dtype (tzinfo | None tz, str unit = "ns")
Return a datetime64[ns] dtype appropriate for the given timezone.
Parameters
----------
tz : tzinfo or None
unit : str, default "ns"
Returns
-------
np.dtype or Datetime64TZDType
Definition at line 105 of file datetimes.py.
Variable Documentation
_bool_ops
pandas.core.arrays.datetimes._bool_ops protected
Definition at line 130 of file datetimes.py.
_ITER_CHUNKSIZE
int pandas.core.arrays.datetimes._ITER_CHUNKSIZE = 10_000 protected
Definition at line 92 of file datetimes.py.
_object_ops
pandas.core.arrays.datetimes._object_ops = fields.get_date_field(values, field, reso=self._creso) protected
Definition at line 149 of file datetimes.py.