Code Cloning Analysis: sklearn.feature_extraction.text.HashingVectorizer Class Reference
sklearn.feature_extraction.text.HashingVectorizer Class Reference
Public Member Functions
__init__ (self, *, input="content", encoding="utf-8", decode_error="strict", strip_accents=None, lowercase=True, preprocessor=None, tokenizer=None, stop_words=None, token_pattern=r"(?u)\b\w\w+\b", ngram_range=(1, 1), analyzer="word", n_features=(2 **20), binary=False, norm="l2", alternate_sign=True, dtype=np.float64)
partial_fit (self, X, y=None)
fit (self, X, y=None)
transform (self, X)
fit_transform (self, X, y=None)
__sklearn_tags__ (self)
Public Member Functions inherited from sklearn.base.TransformerMixin
__sklearn_tags__ (self)
Public Member Functions inherited from sklearn.utils._set_output._SetOutputMixin
__init_subclass__ (cls, auto_wrap_output_keys=("transform",), **kwargs)
set_output (self, *, transform=None)
Public Member Functions inherited from sklearn.feature_extraction.text._VectorizerMixin
decode (self, doc)
build_preprocessor (self)
build_tokenizer (self)
get_stop_words (self)
build_analyzer (self)
Public Member Functions inherited from sklearn.base.BaseEstimator
get_params (self, deep=True)
set_params (self, **params)
__sklearn_clone__ (self)
__repr__ (self, N_CHAR_MAX=700)
__getstate__ (self)
__setstate__ (self, state)
__sklearn_tags__ (self)
Public Member Functions inherited from sklearn.utils._metadata_requests._MetadataRequester
set_fit_request (self, **kwargs)
set_partial_fit_request (self, **kwargs)
set_predict_request (self, **kwargs)
set_predict_proba_request (self, **kwargs)
set_predict_log_proba_request (self, **kwargs)
set_decision_function_request (self, **kwargs)
set_score_request (self, **kwargs)
set_split_request (self, **kwargs)
set_transform_request (self, **kwargs)
set_inverse_transform_request (self, **kwargs)
__init_subclass__ (cls, **kwargs)
get_metadata_routing (self)
Public Attributes
encoding = encoding
decode_error = decode_error
preprocessor = preprocessor
tokenizer = tokenizer
lowercase = lowercase
token_pattern = token_pattern
n_features = n_features
binary = binary
norm = norm
alternate_sign = alternate_sign
dtype = dtype
Public Attributes inherited from sklearn.feature_extraction.text._VectorizerMixin
str input = "filename":
str strip_accents = None
stop_words
str analyzer = (1, 1)
bool fixed_vocabulary_ = True
vocabulary_ = dict(vocabulary)
ngram_range
Protected Member Functions
_get_hasher (self)
Protected Member Functions inherited from sklearn.feature_extraction.text._VectorizerMixin
_word_ngrams (self, tokens, stop_words=None)
_char_ngrams (self, text_document)
_char_wb_ngrams (self, text_document)
_check_stop_words_consistency (self, stop_words, preprocess, tokenize)
_validate_vocabulary (self)
_check_vocabulary (self)
_validate_ngram_range (self)
_warn_for_unused_params (self)
Protected Member Functions inherited from sklearn.base.BaseEstimator
_get_param_names (cls)
_get_params_html (self, deep=True)
_validate_params (self)
Protected Member Functions inherited from sklearn.utils._repr_html.base.ReprHTMLMixin
_repr_html_ (self)
_repr_html_inner (self)
_repr_mimebundle_ (self, **kwargs)
Protected Member Functions inherited from sklearn.utils._repr_html.base._HTMLDocumentationLinkMixin
_doc_link_template (self)
_doc_link_template (self, value)
_get_doc_link (self)
Protected Member Functions inherited from sklearn.utils._metadata_requests._MetadataRequester
_build_request_for_signature (cls, router, method)
_get_default_requests (cls)
_get_metadata_request (self)
Additional Inherited Members
Protected Attributes inherited from sklearn.utils._set_output._SetOutputMixin
_sklearn_auto_wrap_output_keys = set()
dict _sklearn_output_config = {}
Protected Attributes inherited from sklearn.feature_extraction.text._VectorizerMixin
_stop_words_id = id(self.stop_words)
Protected Attributes inherited from sklearn.base.BaseEstimator
_parameter_constraints
Static Protected Attributes inherited from sklearn.feature_extraction.text._VectorizerMixin
_white_spaces = re.compile(r"\s\s+")
Static Protected Attributes inherited from sklearn.base.BaseEstimator
_html_repr = estimator_html_repr
Static Protected Attributes inherited from sklearn.utils._repr_html.base._HTMLDocumentationLinkMixin
str _doc_link_module = "sklearn"
_doc_link_url_param_generator = None
Detailed Description
Convert a collection of text documents to a matrix of token occurrences.
It turns a collection of text documents into a scipy.sparse matrix holding
token occurrence counts (or binary occurrence information), possibly
normalized as token frequencies if norm='l1' or projected on the euclidean
unit sphere if norm='l2'.
This text vectorizer implementation uses the hashing trick to find the
token string name to feature integer index mapping.
This strategy has several advantages:
- it is very low memory scalable to large datasets as there is no need to
  store a vocabulary dictionary in memory.
- it is fast to pickle and un-pickle as it holds no state besides the
  constructor parameters.
- it can be used in a streaming (partial fit) or parallel pipeline as there
  is no state computed during fit.
There are also a couple of cons (vs using a CountVectorizer with an
in-memory vocabulary):
- there is no way to compute the inverse transform (from feature indices to
  string feature names) which can be a problem when trying to introspect
  which features are most important to a model.
- there can be collisions: distinct tokens can be mapped to the same
  feature index. However in practice this is rarely an issue if n_features
  is large enough (e.g. 2 ** 18 for text classification problems).
- no IDF weighting as this would render the transformer stateful.
The hash function employed is the signed 32-bit version of Murmurhash3.
For an efficiency comparison of the different feature extractors, see
:ref:`sphx_glr_auto_examples_text_plot_hashing_vs_dict_vectorizer.py`.
For an example of document clustering and comparison with
:class:`~sklearn.feature_extraction.text.TfidfVectorizer`, see
:ref:`sphx_glr_auto_examples_text_plot_document_clustering.py`.
Read more in the :ref:`User Guide <text_feature_extraction>`.
Parameters
----------
input : {'filename', 'file', 'content'}, default='content'
    - If `'filename'`, the sequence passed as an argument to fit is
      expected to be a list of filenames that need reading to fetch
      the raw content to analyze.
    - If `'file'`, the sequence items must have a 'read' method (file-like
      object) that is called to fetch the bytes in memory.
    - If `'content'`, the input is expected to be a sequence of items that
      can be of type string or byte.
encoding : str, default='utf-8'
    If bytes or files are given to analyze, this encoding is used to
    decode.
decode_error : {'strict', 'ignore', 'replace'}, default='strict'
    Instruction on what to do if a byte sequence is given to analyze that
    contains characters not of the given `encoding`. By default, it is
    'strict', meaning that a UnicodeDecodeError will be raised. Other
    values are 'ignore' and 'replace'.
strip_accents : {'ascii', 'unicode'} or callable, default=None
    Remove accents and perform other character normalization
    during the preprocessing step.
    'ascii' is a fast method that only works on characters that have
    a direct ASCII mapping.
    'unicode' is a slightly slower method that works on any character.
    None (default) means no character normalization is performed.
    Both 'ascii' and 'unicode' use NFKD normalization from
    :func:`unicodedata.normalize`.
lowercase : bool, default=True
    Convert all characters to lowercase before tokenizing.
preprocessor : callable, default=None
    Override the preprocessing (string transformation) stage while
    preserving the tokenizing and n-grams generation steps.
    Only applies if ``analyzer`` is not callable.
tokenizer : callable, default=None
    Override the string tokenization step while preserving the
    preprocessing and n-grams generation steps.
    Only applies if ``analyzer == 'word'``.
stop_words : {'english'}, list, default=None
    If 'english', a built-in stop word list for English is used.
    There are several known issues with 'english' and you should
    consider an alternative (see :ref:`stop_words`).
    If a list, that list is assumed to contain stop words, all of which
    will be removed from the resulting tokens.
    Only applies if ``analyzer == 'word'``.
token_pattern : str or None, default=r"(?u)\\b\\w\\w+\\b"
    Regular expression denoting what constitutes a "token", only used
    if ``analyzer == 'word'``. The default regexp selects tokens of 2
    or more alphanumeric characters (punctuation is completely ignored
    and always treated as a token separator).
    If there is a capturing group in token_pattern then the
    captured group content, not the entire match, becomes the token.
    At most one capturing group is permitted.
ngram_range : tuple (min_n, max_n), default=(1, 1)
    The lower and upper boundary of the range of n-values for different
    n-grams to be extracted. All values of n such that min_n <= n <= max_n
    will be used. For example an ``ngram_range`` of ``(1, 1)`` means only
    unigrams, ``(1, 2)`` means unigrams and bigrams, and ``(2, 2)`` means
    only bigrams.
    Only applies if ``analyzer`` is not callable.
analyzer : {'word', 'char', 'char_wb'} or callable, default='word'
    Whether the feature should be made of word or character n-grams.
    Option 'char_wb' creates character n-grams only from text inside
    word boundaries; n-grams at the edges of words are padded with space.
    If a callable is passed it is used to extract the sequence of features
    out of the raw, unprocessed input.
    .. versionchanged:: 0.21
        Since v0.21, if ``input`` is ``'filename'`` or ``'file'``, the data
        is first read from the file and then passed to the given callable
        analyzer.
n_features : int, default=(2 ** 20)
    The number of features (columns) in the output matrices. Small numbers
    of features are likely to cause hash collisions, but large numbers
    will cause larger coefficient dimensions in linear learners.
binary : bool, default=False
    If True, all non zero counts are set to 1. This is useful for discrete
    probabilistic models that model binary events rather than integer
    counts.
norm : {'l1', 'l2'}, default='l2'
    Norm used to normalize term vectors. None for no normalization.
alternate_sign : bool, default=True
    When True, an alternating sign is added to the features as to
    approximately conserve the inner product in the hashed space even for
    small n_features. This approach is similar to sparse random projection.
    .. versionadded:: 0.19
dtype : type, default=np.float64
    Type of the matrix returned by fit_transform() or transform().
See Also
--------
CountVectorizer : Convert a collection of text documents to a matrix of
    token counts.
TfidfVectorizer : Convert a collection of raw documents to a matrix of
    TF-IDF features.
Notes
-----
This estimator is :term:`stateless` and does not need to be fitted.
However, we recommend to call :meth:`fit_transform` instead of
:meth:`transform`, as parameter validation is only performed in
:meth:`fit`.
Examples
--------
>>> from sklearn.feature_extraction.text import HashingVectorizer
>>> corpus = [
...     'This is the first document.',
...     'This document is the second document.',
...     'And this is the third one.',
...     'Is this the first document?',
... ]
>>> vectorizer = HashingVectorizer(n_features=2**4)
>>> X = vectorizer.fit_transform(corpus)
>>> print(X.shape)
(4, 16)
Definition at line 558 of file text.py.
Constructor & Destructor Documentation
__init__()
sklearn.feature_extraction.text.HashingVectorizer.__init__ (self, * , input = "content", encoding = "utf-8", decode_error = "strict", strip_accents = None, lowercase = True, preprocessor = None, tokenizer = None, stop_words = None, token_pattern = r"(?u)\b\w\w+\b", ngram_range = (1, 1), analyzer = "word", n_features = (2**20), binary = False, norm = "l2", alternate_sign = True, dtype = np.float64)
Definition at line 764 of file text.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params().
Member Function Documentation
__sklearn_tags__()
sklearn.feature_extraction.text.HashingVectorizer.__sklearn_tags__ (self)
Definition at line 913 of file text.py.
_get_hasher()
sklearn.feature_extraction.text.HashingVectorizer._get_hasher (self) protected
Definition at line 905 of file text.py.
fit()
sklearn.feature_extraction.text.HashingVectorizer.fit (self, X, y = None)
Only validates estimator's parameters.
This method allows to: (i) validate the estimator's parameters and
(ii) be consistent with the scikit-learn transformer API.
Parameters
----------
X : ndarray of shape [n_samples, n_features]
    Training data.
y : Ignored
    Not used, present for API consistency by convention.
Returns
-------
self : object
    HashingVectorizer instance.
Definition at line 824 of file text.py.
Referenced by sklearn.cluster._kmeans._BaseKMeans.fit_predict(), sklearn.neighbors._lof.LocalOutlierFactor.fit_predict(), sklearn.cluster._kmeans._BaseKMeans.fit_transform(), sklearn.manifold._spectral_embedding.SpectralEmbedding.fit_transform(), sklearn.neighbors._graph.KNeighborsTransformer.fit_transform(), sklearn.neighbors._graph.RadiusNeighborsTransformer.fit_transform(), sklearn.preprocessing._label.LabelBinarizer.fit_transform(), sklearn.preprocessing._label.MultiLabelBinarizer.fit_transform(), sklearn.tests.metadata_routing_common.ConsumingTransformer.fit_transform(), and sklearn.utils.tests.test_estimator_checks.SparseTransformer.fit_transform().
fit_transform()
sklearn.feature_extraction.text.HashingVectorizer.fit_transform (self, X, y = None)
Transform a sequence of documents to a document-term matrix.
Parameters
----------
X : iterable over raw text documents, length = n_samples
    Samples. Each sample must be a text document (either bytes or
    unicode strings, file name or file object depending on the
    constructor argument) which will be tokenized and hashed.
y : any
    Ignored. This parameter exists only for compatibility with
    sklearn.pipeline.Pipeline.
Returns
-------
X : sparse matrix of shape (n_samples, n_features)
    Document-term matrix.
Reimplemented from sklearn.base.TransformerMixin.
Definition at line 885 of file text.py.
Referenced by sklearn.manifold._mds.MDS.fit().
partial_fit()
sklearn.feature_extraction.text.HashingVectorizer.partial_fit (self, X, y = None)
Only validates estimator's parameters.
This method allows to: (i) validate the estimator's parameters and
(ii) be consistent with the scikit-learn transformer API.
Parameters
----------
X : ndarray of shape [n_samples, n_features]
    Training data.
y : Ignored
    Not used, present for API consistency by convention.
Returns
-------
self : object
    HashingVectorizer instance.
Definition at line 802 of file text.py.
Referenced by sklearn.preprocessing._data.MaxAbsScaler.fit(), sklearn.preprocessing._data.MinMaxScaler.fit(), and sklearn.preprocessing._data.StandardScaler.fit().
transform()
sklearn.feature_extraction.text.HashingVectorizer.transform (self, X)
Transform a sequence of documents to a document-term matrix.
Parameters
----------
X : iterable over raw text documents, length = n_samples
    Samples. Each sample must be a text document (either bytes or
    unicode strings, file name or file object depending on the
    constructor argument) which will be tokenized and hashed.
Returns
-------
X : sparse matrix of shape (n_samples, n_features)
    Document-term matrix.
Definition at line 855 of file text.py.
Referenced by sklearn.preprocessing._function_transformer.FunctionTransformer._check_inverse_transform(), sklearn.feature_selection._rfe.RFE.decision_function(), PIL.ImageCms.Flags.GRIDPOINTS(), sklearn.ensemble._stacking._BaseStacking.predict(), sklearn.feature_selection._rfe.RFE.predict(), sklearn.feature_selection._rfe.RFE.predict_log_proba(), sklearn.feature_selection._rfe.RFE.predict_proba(), sklearn.feature_selection._rfe.RFE.score(), and sklearn.preprocessing._polynomial.PolynomialFeatures.transform().
Member Data Documentation
alternate_sign
sklearn.feature_extraction.text.HashingVectorizer.alternate_sign = alternate_sign
Definition at line 798 of file text.py.
binary
sklearn.feature_extraction.text.HashingVectorizer.binary = binary
Definition at line 796 of file text.py.
decode_error
sklearn.feature_extraction.text.HashingVectorizer.decode_error = decode_error
Definition at line 786 of file text.py.
Referenced by sklearn.feature_extraction.text._VectorizerMixin.decode().
dtype
sklearn.feature_extraction.text.HashingVectorizer.dtype = dtype
Definition at line 799 of file text.py.
Referenced by pandas.core.arrays.base.ExtensionScalarOpsMixin._create_method(), pandas.core.interchange.column.PandasColumn._get_data_buffer(), pandas.core.interchange.column.PandasColumn._get_offsets_buffer(), pandas.core.interchange.column.PandasColumn._get_validity_buffer(), scipy.sparse._index.IndexMixin._getcol(), pandas.core.generic.NDFrame._inplace_method(), scipy.sparse._index.IndexMixin._raise_on_1d_array_slice(), pandas.core.strings.object_array.ObjectStringArrayMixin._str_map(), pandas.core.arrays.timedeltas.TimedeltaArray._vector_divlike_op(), pandas.core.interchange.column.PandasColumn.describe_categorical(), pandas.core.interchange.column.PandasColumn.describe_null(), sklearn.preprocessing._discretization.KBinsDiscretizer.fit(), sklearn.preprocessing._encoders.OrdinalEncoder.fit(), numpy.matrixlib.defmatrix.matrix.H(), pandas.core.internals.array_manager.SingleArrayManager.make_empty(), numpy.core.records.record.pprint(), pandas.core.frame.DataFrame.quantile(), pandas.core.generic.NDFrame.rank(), sklearn.preprocessing._discretization.KBinsDiscretizer.transform(), sklearn.preprocessing._encoders.OneHotEncoder.transform(), sklearn.preprocessing._encoders.OrdinalEncoder.transform(), pandas.io.pytables.AppendableTable.write_data(), and pandas.io.pytables.AppendableTable.write_data_chunk().
encoding
sklearn.feature_extraction.text.HashingVectorizer.encoding = encoding
Definition at line 785 of file text.py.
Referenced by pip._vendor.rich.console.ConsoleOptions.ascii_only(), sklearn.feature_extraction.text._VectorizerMixin.decode(), and pip._vendor.rich.console.Console.options().
lowercase
sklearn.feature_extraction.text.HashingVectorizer.lowercase = lowercase
Definition at line 791 of file text.py.
Referenced by sklearn.feature_extraction.text._VectorizerMixin.build_preprocessor().
n_features
sklearn.feature_extraction.text.HashingVectorizer.n_features = n_features
Definition at line 794 of file text.py.
norm
sklearn.feature_extraction.text.HashingVectorizer.norm = norm
Definition at line 797 of file text.py.
Referenced by matplotlib.contour.ContourSet.__init__(), matplotlib.contour.ContourSet._get_lowers_and_uppers(), matplotlib.contour.ContourSet._process_colors(), sklearn.naive_bayes.ComplementNB._update_feature_log_prob(), and sklearn.preprocessing._data.Normalizer.transform().
preprocessor
sklearn.feature_extraction.text.HashingVectorizer.preprocessor = preprocessor
Definition at line 788 of file text.py.
Referenced by sklearn.feature_extraction.text._VectorizerMixin.build_preprocessor().
token_pattern
sklearn.feature_extraction.text.HashingVectorizer.token_pattern = token_pattern
Definition at line 792 of file text.py.
Referenced by sklearn.feature_extraction.text._VectorizerMixin.build_tokenizer().
tokenizer
sklearn.feature_extraction.text.HashingVectorizer.tokenizer = tokenizer
Definition at line 789 of file text.py.
Referenced by sklearn.feature_extraction.text._VectorizerMixin.build_tokenizer().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/sklearn/feature_extraction/text.py