Code Cloning Analysis: matplotlib.ticker.AutoLocator Class Reference
matplotlib.ticker.AutoLocator Class Reference
Public Member Functions
__init__ (self)
Public Member Functions inherited from matplotlib.ticker.MaxNLocator
__init__ (self, nbins=None, **kwargs)
set_params (self, **kwargs)
__call__ (self)
tick_values (self, vmin, vmax)
view_limits (self, dmin, dmax)
Public Member Functions inherited from matplotlib.ticker.Locator
__call__ (self)
raise_if_exceeds (self, locs)
nonsingular (self, v0, v1)
Public Member Functions inherited from matplotlib.ticker.TickHelper
set_axis (self, axis)
create_dummy_axis (self, **kwargs)
Additional Inherited Members
Static Public Attributes inherited from matplotlib.ticker.MaxNLocator
default_params
Static Public Attributes inherited from matplotlib.ticker.Locator
int MAXTICKS = 1000
Static Public Attributes inherited from matplotlib.ticker.TickHelper
axis = None
Protected Member Functions inherited from matplotlib.ticker.MaxNLocator
_raw_ticks (self, vmin, vmax)
Static Protected Member Functions inherited from matplotlib.ticker.MaxNLocator
_validate_steps (steps)
_staircase (steps)
Protected Attributes inherited from matplotlib.ticker.MaxNLocator
str _nbins = kwargs.pop('nbins')
_symmetric = kwargs.pop('symmetric')
_prune = prune
_min_n_ticks = max(1, kwargs.pop('min_n_ticks'))
_steps = np.array([1, 1.5, 2, 2.5, 3, 4, 5, 6, 8, 10])
_extended_steps = self._staircase(self._steps)
_integer = kwargs.pop('integer')
Detailed Description
Place evenly spaced ticks, with the step size and maximum number of ticks chosen
automatically.
This is a subclass of `~matplotlib.ticker.MaxNLocator`, with parameters
*nbins = 'auto'* and *steps = [1, 2, 2.5, 5, 10]*.
Definition at line 2908 of file ticker.py.
Constructor & Destructor Documentation
__init__()
matplotlib.ticker.AutoLocator.__init__ (self)
To know the values of the non-public parameters, please have a
look to the defaults of `~matplotlib.ticker.MaxNLocator`.
Definition at line 2916 of file ticker.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/ticker.py