Code Cloning Analysis: sklearn.linear_model.tests.test_sgd._SparseSGDOneClassSVM Class Reference
sklearn.linear_model.tests.test_sgd._SparseSGDOneClassSVM Class Reference
Public Member Functions
fit (self, X, *args, **kw)
partial_fit (self, X, *args, **kw)
decision_function (self, X, *args, **kw)
Public Member Functions inherited from sklearn.linear_model._stochastic_gradient.SGDOneClassSVM
__init__ (self, nu=0.5, fit_intercept=True, max_iter=1000, tol=1e-3, shuffle=True, verbose=0, random_state=None, learning_rate="optimal", eta0=0.0, power_t=0.5, warm_start=False, average=False)
score_samples (self, X)
predict (self, X)
__sklearn_tags__ (self)
Public Member Functions inherited from sklearn.base.OutlierMixin
__sklearn_tags__ (self)
fit_predict (self, X, y=None, **kwargs)
Public Member Functions inherited from sklearn.linear_model._stochastic_gradient.BaseSGD
__init__ (self, loss, *, penalty="l2", alpha=0.0001, C=1.0, l1_ratio=0.15, fit_intercept=True, max_iter=1000, tol=1e-3, shuffle=True, verbose=0, epsilon=0.1, random_state=None, learning_rate="optimal", eta0=0.0, power_t=0.5, early_stopping=False, validation_fraction=0.1, n_iter_no_change=5, warm_start=False, average=False)
Public Member Functions inherited from sklearn.linear_model._base.SparseCoefMixin
densify (self)
sparsify (self)
Public Member Functions inherited from sklearn.base.BaseEstimator
get_params (self, deep=True)
set_params (self, **params)
__sklearn_clone__ (self)
__repr__ (self, N_CHAR_MAX=700)
__getstate__ (self)
__setstate__ (self, state)
__sklearn_tags__ (self)
Public Member Functions inherited from sklearn.utils._metadata_requests._MetadataRequester
set_fit_request (self, **kwargs)
set_partial_fit_request (self, **kwargs)
set_predict_request (self, **kwargs)
set_predict_proba_request (self, **kwargs)
set_predict_log_proba_request (self, **kwargs)
set_decision_function_request (self, **kwargs)
set_score_request (self, **kwargs)
set_split_request (self, **kwargs)
set_transform_request (self, **kwargs)
set_inverse_transform_request (self, **kwargs)
__init_subclass__ (cls, **kwargs)
get_metadata_routing (self)
Additional Inherited Members
Public Attributes inherited from sklearn.linear_model._stochastic_gradient.SGDOneClassSVM
nu = nu
n_iter_
float t_ = 1.0
Public Attributes inherited from sklearn.linear_model._stochastic_gradient.BaseSGD
loss = loss
str penalty = penalty
str learning_rate = learning_rate
epsilon = epsilon
alpha = alpha
C = C
l1_ratio = l1_ratio
fit_intercept = fit_intercept
shuffle = shuffle
random_state = random_state
verbose = verbose
eta0 = eta0
power_t = power_t
early_stopping = early_stopping
validation_fraction = validation_fraction
n_iter_no_change = n_iter_no_change
warm_start = warm_start
average = average
max_iter = max_iter
tol = tol
intercept_ = intercept_init
offset_
Public Attributes inherited from sklearn.linear_model._base.SparseCoefMixin
coef_
Static Public Attributes inherited from sklearn.linear_model._stochastic_gradient.SGDOneClassSVM
dict loss_functions = {"hinge": (Hinge, 1.0)}
Protected Member Functions inherited from sklearn.linear_model._stochastic_gradient.SGDOneClassSVM
_fit_one_class (self, X, alpha, C, sample_weight, learning_rate, max_iter)
_partial_fit (self, X, alpha, C, loss, learning_rate, max_iter, sample_weight, coef_init, offset_init)
_fit (self, X, alpha, C, loss, learning_rate, coef_init=None, offset_init=None, sample_weight=None)
Protected Member Functions inherited from sklearn.linear_model._stochastic_gradient.BaseSGD
_more_validate_params (self, for_partial_fit=False)
_get_l1_ratio (self)
_get_loss_function (self, loss)
_get_learning_rate_type (self, learning_rate)
_get_penalty_type (self, penalty)
_allocate_parameter_mem (self, n_classes, n_features, input_dtype, coef_init=None, intercept_init=None, one_class=0)
_make_validation_split (self, y, sample_mask)
_make_validation_score_cb (self, validation_mask, X, y, sample_weight, classes=None)
Protected Member Functions inherited from sklearn.base.BaseEstimator
_get_param_names (cls)
_get_params_html (self, deep=True)
_validate_params (self)
Protected Member Functions inherited from sklearn.utils._repr_html.base.ReprHTMLMixin
_repr_html_ (self)
_repr_html_inner (self)
_repr_mimebundle_ (self, **kwargs)
Protected Member Functions inherited from sklearn.utils._repr_html.base._HTMLDocumentationLinkMixin
_doc_link_template (self)
_doc_link_template (self, value)
_get_doc_link (self)
Protected Member Functions inherited from sklearn.utils._metadata_requests._MetadataRequester
_build_request_for_signature (cls, router, method)
_get_default_requests (cls)
_get_metadata_request (self)
Protected Attributes inherited from sklearn.linear_model._stochastic_gradient.SGDOneClassSVM
_loss_function_ = self._get_loss_function(loss)
Protected Attributes inherited from sklearn.linear_model._stochastic_gradient.BaseSGD
_standard_coef = self.coef_
_average_coef
int _standard_intercept = 1 - self.offset_
_average_intercept
Protected Attributes inherited from sklearn.base.BaseEstimator
_parameter_constraints
Static Protected Attributes inherited from sklearn.base.OutlierMixin
str _estimator_type = "outlier_detector"
Static Protected Attributes inherited from sklearn.base.BaseEstimator
_html_repr = estimator_html_repr
Static Protected Attributes inherited from sklearn.utils._repr_html.base._HTMLDocumentationLinkMixin
str _doc_link_module = "sklearn"
_doc_link_url_param_generator = None
Detailed Description
Definition at line 75 of file test_sgd.py.
Member Function Documentation
decision_function()
sklearn.linear_model.tests.test_sgd._SparseSGDOneClassSVM.decision_function (self, X, * args, ** kw)
Signed distance to the separating hyperplane.
Signed distance is positive for an inlier and negative for an
outlier.
Parameters
----------
X : {array-like, sparse matrix}, shape (n_samples, n_features)
    Testing data.
Returns
-------
dec : array-like, shape (n_samples,)
    Decision function values of the samples.
Reimplemented from sklearn.linear_model._stochastic_gradient.SGDOneClassSVM.
Definition at line 84 of file test_sgd.py.
Referenced by sklearn.neighbors._lof.LocalOutlierFactor._predict(), sklearn.multiclass.OneVsOneClassifier.predict(), sklearn.svm._base.BaseSVC.predict(), and sklearn.svm._classes.OneClassSVM.score_samples().
fit()
sklearn.linear_model.tests.test_sgd._SparseSGDOneClassSVM.fit (self, X, * y, ** coef_init)
Fit linear One-Class SVM with Stochastic Gradient Descent.
This solves an equivalent optimization problem of the
One-Class SVM primal optimization problem and returns a weight vector
w and an offset rho such that the decision function is given by
<w, x> - rho.
Parameters
----------
X : {array-like, sparse matrix}, shape (n_samples, n_features)
    Training data.
y : Ignored
    Not used, present for API consistency by convention.
coef_init : array, shape (n_classes, n_features)
    The initial coefficients to warm-start the optimization.
offset_init : array, shape (n_classes,)
    The initial offset to warm-start the optimization.
sample_weight : array-like, shape (n_samples,), optional
    Weights applied to individual samples.
    If not provided, uniform weights are assumed. These weights will
    be multiplied with class_weight (passed through the
    constructor) if class_weight is specified.
Returns
-------
self : object
    Returns a fitted instance of self.
Reimplemented from sklearn.linear_model._stochastic_gradient.SGDOneClassSVM.
Definition at line 76 of file test_sgd.py.
Referenced by sklearn.cluster._kmeans._BaseKMeans.fit_predict(), sklearn.neighbors._lof.LocalOutlierFactor.fit_predict(), sklearn.cluster._kmeans._BaseKMeans.fit_transform(), sklearn.manifold._spectral_embedding.SpectralEmbedding.fit_transform(), sklearn.neighbors._graph.KNeighborsTransformer.fit_transform(), sklearn.neighbors._graph.RadiusNeighborsTransformer.fit_transform(), sklearn.preprocessing._label.LabelBinarizer.fit_transform(), sklearn.preprocessing._label.MultiLabelBinarizer.fit_transform(), sklearn.tests.metadata_routing_common.ConsumingTransformer.fit_transform(), and sklearn.utils.tests.test_estimator_checks.SparseTransformer.fit_transform().
partial_fit()
sklearn.linear_model.tests.test_sgd._SparseSGDOneClassSVM.partial_fit (self, X, * y, ** sample_weight)
Fit linear One-Class SVM with Stochastic Gradient Descent.
Parameters
----------
X : {array-like, sparse matrix}, shape (n_samples, n_features)
    Subset of the training data.
y : Ignored
    Not used, present for API consistency by convention.
sample_weight : array-like, shape (n_samples,), optional
    Weights applied to individual samples.
    If not provided, uniform weights are assumed.
Returns
-------
self : object
    Returns a fitted instance of self.
Reimplemented from sklearn.linear_model._stochastic_gradient.SGDOneClassSVM.
Definition at line 80 of file test_sgd.py.
Referenced by sklearn.preprocessing._data.MaxAbsScaler.fit(), sklearn.preprocessing._data.MinMaxScaler.fit(), and sklearn.preprocessing._data.StandardScaler.fit().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/sklearn/linear_model/tests/test_sgd.py