Code Cloning Analysis: pip._internal.metadata.base.BaseEntryPoint Class Reference
pip._internal.metadata.base.BaseEntryPoint Class Reference
Public Member Functions
str name (self)
str value (self)
str group (self)
Detailed Description
Definition at line 56 of file base.py.
Member Function Documentation
group()
str pip._internal.metadata.base.BaseEntryPoint.group (self)
Definition at line 66 of file base.py.
name()
str pip._internal.metadata.base.BaseEntryPoint.name (self)
Definition at line 58 of file base.py.
Referenced by pip._vendor.pyparsing.core.Regex.__init__(), pip._vendor.distro.distro.LinuxDistribution.linux_distribution(), and pip._internal.resolution.resolvelib.requirements.SpecifierRequirement.name().
value()
str pip._internal.metadata.base.BaseEntryPoint.value (self)
Definition at line 62 of file base.py.
Referenced by sklearn.externals.array_api_extra._lib._at._AtOp.__str__(), pip._internal.models.link.LinkHash.as_hashes(), pip._internal.models.link.LinkHash.find_hash_url_fragment(), and pip._internal.models.link.LinkHash.is_hash_allowed().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pip/_internal/metadata/base.py