Code Cloning Analysis: matplotlib.backends.backend_gtk3.NavigationToolbar2GTK3 Class Reference
matplotlib.backends.backend_gtk3.NavigationToolbar2GTK3 Class Reference
Public Member Functions
__init__ (self, canvas)
save_figure (self, *args)
Public Attributes
toolitems
message = Gtk.Label()
Protected Attributes
dict _gtk_ids = {}
Detailed Description
Definition at line 303 of file backend_gtk3.py.
Constructor & Destructor Documentation
__init__()
matplotlib.backends.backend_gtk3.NavigationToolbar2GTK3.__init__ (self, canvas)
Definition at line 304 of file backend_gtk3.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
save_figure()
matplotlib.backends.backend_gtk3.NavigationToolbar2GTK3.save_figure (self, * args)
Definition at line 352 of file backend_gtk3.py.
Member Data Documentation
_gtk_ids
dict matplotlib.backends.backend_gtk3.NavigationToolbar2GTK3._gtk_ids = {} protected
Definition at line 309 of file backend_gtk3.py.
message
matplotlib.backends.backend_gtk3.NavigationToolbar2GTK3.message = Gtk.Label()
Definition at line 344 of file backend_gtk3.py.
Referenced by numpy.lib.utils._Deprecate.__call__(), numpy.core.tests.test_deprecations._DeprecationTestCase.assert_deprecated(), matplotlib.backends._backend_gtk._NavigationToolbar2GTK.set_message(), and matplotlib.backends.backend_webagg_core.NavigationToolbar2WebAgg.set_message().
toolitems
matplotlib.backends.backend_gtk3.NavigationToolbar2GTK3.toolitems
Definition at line 310 of file backend_gtk3.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/backends/backend_gtk3.py