Code Cloning Analysis: scipy.optimize._nonlin.ExcitingMixing Class Reference
scipy.optimize._nonlin.ExcitingMixing Class Reference
Public Member Functions
__init__ (self, alpha=None, alphamax=1.0)
setup (self, x, F, func)
solve (self, f, tol=0)
matvec (self, f)
rsolve (self, f, tol=0)
rmatvec (self, f)
todense (self)
Public Member Functions inherited from scipy.optimize._nonlin.GenericBroyden
update (self, x, f)
Public Member Functions inherited from scipy.optimize._nonlin.Jacobian
__init__ (self, **kw)
aspreconditioner (self)
Public Attributes
alphamax = alphamax
beta = None
Public Attributes inherited from scipy.optimize._nonlin.GenericBroyden
last_f = f0
last_x = x0
float alpha = 0.5*max(norm(x0), 1) / normf0
Public Attributes inherited from scipy.optimize._nonlin.Jacobian
func = func
tuple shape = (F.size, x.size)
dtype = F.dtype
Protected Member Functions
_update (self, x, f, dx, df, dx_norm, df_norm)
Detailed Description
Find a root of a function, using a tuned diagonal Jacobian approximation.
The Jacobian matrix is diagonal and is tuned on each iteration.
.. warning::
   This algorithm may be useful for specific problems, but whether
   it will work may depend strongly on the problem.
See Also
--------
root : Interface to root finding algorithms for multivariate
       functions. See ``method='excitingmixing'`` in particular.
Parameters
----------
%(params_basic)s
alpha : float, optional
    Initial Jacobian approximation is (-1/alpha).
alphamax : float, optional
    The entries of the diagonal Jacobian are kept in the range
    ``[alpha, alphamax]``.
%(params_extra)s
Definition at line 1252 of file _nonlin.py.
Constructor & Destructor Documentation
__init__()
scipy.optimize._nonlin.ExcitingMixing.__init__ (self, alpha = None, alphamax = 1.0)
Definition at line 1279 of file _nonlin.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
_update()
scipy.optimize._nonlin.ExcitingMixing._update (self, x, f, dx, df, dx_norm, df_norm) protected
Reimplemented from scipy.optimize._nonlin.GenericBroyden.
Definition at line 1304 of file _nonlin.py.
matvec()
scipy.optimize._nonlin.ExcitingMixing.matvec (self, f)
Definition at line 1292 of file _nonlin.py.
Referenced by scipy.sparse.linalg._interface.LinearOperator._init_dtype(), scipy.sparse.linalg._interface.LinearOperator._matmat(), and scipy.sparse.linalg._interface.LinearOperator.dot().
rmatvec()
scipy.optimize._nonlin.ExcitingMixing.rmatvec (self, f)
Definition at line 1298 of file _nonlin.py.
Referenced by scipy.sparse.linalg._interface.LinearOperator._rmatmat().
rsolve()
scipy.optimize._nonlin.ExcitingMixing.rsolve (self, f, tol = 0)
Definition at line 1295 of file _nonlin.py.
setup()
scipy.optimize._nonlin.ExcitingMixing.setup (self, x, F, func)
Reimplemented from scipy.optimize._nonlin.GenericBroyden.
Definition at line 1285 of file _nonlin.py.
solve()
scipy.optimize._nonlin.ExcitingMixing.solve (self, f, tol = 0)
Reimplemented from scipy.optimize._nonlin.Jacobian.
Definition at line 1289 of file _nonlin.py.
todense()
scipy.optimize._nonlin.ExcitingMixing.todense (self)
Definition at line 1301 of file _nonlin.py.
Referenced by scipy.sparse._base._spbase._divide(), scipy.sparse._compressed._cs_matrix._maximum_minimum(), scipy.sparse._compressed._cs_matrix._scalar_binopt(), scipy.sparse._dok._dok_base.get(), and scipy.sparse._base._spbase.power().
Member Data Documentation
alphamax
scipy.optimize._nonlin.ExcitingMixing.alphamax = alphamax
Definition at line 1282 of file _nonlin.py.
beta
scipy.optimize._nonlin.ExcitingMixing.beta = None
Definition at line 1283 of file _nonlin.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/optimize/_nonlin.py