Code Cloning Analysis: PIL.PdfParser.IndirectReference Class Reference
PIL.PdfParser.IndirectReference Class Reference
Public Member Functions
str __str__ (self)
bytes __bytes__ (self)
bool __eq__ (self, object other)
bool __ne__ (self, object other)
int __hash__ (self)
Public Attributes
object_id
generation
Detailed Description
Definition at line 89 of file PdfParser.py.
Member Function Documentation
__bytes__()
bytes PIL.PdfParser.IndirectReference.__bytes__ (self)
Definition at line 93 of file PdfParser.py.
__eq__()
bool PIL.PdfParser.IndirectReference.__eq__ (self, object other)
Definition at line 96 of file PdfParser.py.
Referenced by pip._vendor.msgpack.ext.Timestamp.__ne__(), and pip._vendor.distlib.version.Matcher.match().
__hash__()
int PIL.PdfParser.IndirectReference.__hash__ (self)
Definition at line 105 of file PdfParser.py.
Referenced by pip._vendor.rich.style.Style.pick_first().
__ne__()
bool PIL.PdfParser.IndirectReference.__ne__ (self, object other)
Definition at line 102 of file PdfParser.py.
__str__()
str PIL.PdfParser.IndirectReference.__str__ (self)
Definition at line 90 of file PdfParser.py.
Member Data Documentation
generation
PIL.PdfParser.IndirectReference.generation
Definition at line 106 of file PdfParser.py.
object_id
PIL.PdfParser.IndirectReference.object_id
Definition at line 106 of file PdfParser.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/PIL/PdfParser.py