Code Cloning Analysis: scipy.special._orthogonal.orthopoly1d Class Reference
scipy.special._orthogonal.orthopoly1d Class Reference
Public Member Functions
__init__ (self, roots, weights=None, hn=1.0, kn=1.0, wfunc=None, limits=None, monic=False, eval_func=None)
__call__ (self, v)
Public Attributes
weights = np.array(list(zip(roots, weights, equiv_weights)))
weight_func = wfunc
limits = limits
normcoef = mu
Protected Member Functions
_scale (self, p)
Protected Attributes
_eval_func = eval_func
Detailed Description
Definition at line 115 of file _orthogonal.py.
Constructor & Destructor Documentation
__init__()
scipy.special._orthogonal.orthopoly1d.__init__ (self, roots, weights = None, hn = 1.0, kn = 1.0, wfunc = None, limits = None, monic = False, eval_func = None)
Definition at line 117 of file _orthogonal.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
__call__()
scipy.special._orthogonal.orthopoly1d.__call__ (self, v)
Definition at line 143 of file _orthogonal.py.
_scale()
scipy.special._orthogonal.orthopoly1d._scale (self, p) protected
Definition at line 149 of file _orthogonal.py.
Member Data Documentation
_eval_func
scipy.special._orthogonal.orthopoly1d._eval_func = eval_func protected
Definition at line 141 of file _orthogonal.py.
limits
scipy.special._orthogonal.orthopoly1d.limits = limits
Definition at line 137 of file _orthogonal.py.
normcoef
scipy.special._orthogonal.orthopoly1d.normcoef = mu
Definition at line 138 of file _orthogonal.py.
weight_func
scipy.special._orthogonal.orthopoly1d.weight_func = wfunc
Definition at line 136 of file _orthogonal.py.
weights
scipy.special._orthogonal.orthopoly1d.weights = np.array(list(zip(roots, weights, equiv_weights)))
Definition at line 135 of file _orthogonal.py.
Referenced by sklearn.impute._knn.KNNImputer._calc_impute(), scipy.stats._kde.gaussian_kde._compute_covariance(), sklearn.ensemble._voting._BaseVoting._weights_not_none(), scipy.stats._kde.gaussian_kde.evaluate(), sklearn.ensemble._voting._BaseVoting.fit(), scipy.stats._kde.gaussian_kde.integrate_box(), scipy.stats._kde.gaussian_kde.integrate_box_1d(), scipy.stats._kde.gaussian_kde.integrate_gaussian(), scipy.stats._kde.gaussian_kde.logpdf(), scipy.stats._kde.gaussian_kde.marginal(), sklearn.neighbors._classification.KNeighborsClassifier.predict(), sklearn.neighbors._regression.KNeighborsRegressor.predict(), sklearn.neighbors._regression.RadiusNeighborsRegressor.predict(), sklearn.neighbors._classification.KNeighborsClassifier.predict_proba(), sklearn.neighbors._classification.RadiusNeighborsClassifier.predict_proba(), and scipy.stats._kde.gaussian_kde.resample().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/special/_orthogonal.py