Code Cloning Analysis: matplotlib.cbook._OrderedSet Class Reference
matplotlib.cbook._OrderedSet Class Reference
Public Member Functions
__init__ (self)
__contains__ (self, key)
__iter__ (self)
__len__ (self)
add (self, key)
discard (self, key)
Protected Attributes
_od = collections.OrderedDict()
Detailed Description
Definition at line 2064 of file cbook.py.
Constructor & Destructor Documentation
__init__()
matplotlib.cbook._OrderedSet.__init__ (self)
Definition at line 2065 of file cbook.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__contains__()
matplotlib.cbook._OrderedSet.__contains__ (self, key)
Definition at line 2068 of file cbook.py.
__iter__()
matplotlib.cbook._OrderedSet.__iter__ (self)
Definition at line 2071 of file cbook.py.
__len__()
matplotlib.cbook._OrderedSet.__len__ (self)
Definition at line 2074 of file cbook.py.
add()
matplotlib.cbook._OrderedSet.add (self, key)
Definition at line 2077 of file cbook.py.
Referenced by matplotlib.sankey.Sankey.__init__(), pip._internal.req.req_uninstall.UninstallPathSet._permitted(), pip._vendor.distlib.manifest.Manifest.add_many(), pip._vendor.urllib3._collections.HTTPHeaderDict.extend(), numpy.core.tests.test_simd._SIMD_ALL.test_conversion_expand(), numpy.core.tests.test_simd._SIMD_ALL.test_mask_conditional(), and pip._internal.operations.build.build_tracker.BuildTracker.track().
discard()
matplotlib.cbook._OrderedSet.discard (self, key)
Definition at line 2081 of file cbook.py.
Member Data Documentation
_od
matplotlib.cbook._OrderedSet._od = collections.OrderedDict() protected
Definition at line 2066 of file cbook.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/cbook.py