Code Cloning Analysis: axes_grid1.anchored_artists.AnchoredDrawingArea Class Reference
axes_grid1.anchored_artists.AnchoredDrawingArea Class Reference
Public Member Functions
__init__ (self, width, height, xdescent, ydescent, loc, pad=0.4, borderpad=0.5, prop=None, frameon=True, **kwargs)
Public Member Functions inherited from matplotlib.offsetbox.AnchoredOffsetbox
__init__ (self, loc, *, pad=0.4, borderpad=0.5, child=None, prop=None, frameon=True, bbox_to_anchor=None, bbox_transform=None, **kwargs)
set_child (self, child)
get_child (self)
get_children (self)
get_bbox (self, renderer)
get_bbox_to_anchor (self)
set_bbox_to_anchor (self, bbox, transform=None)
get_offset (self, bbox, renderer)
update_frame (self, bbox, fontsize=None)
draw (self, renderer)
Public Member Functions inherited from matplotlib.offsetbox.OffsetBox
__init__ (self, *args, **kwargs)
set_figure (self, fig)
axes (self, ax)
contains (self, mouseevent)
set_offset (self, xy)
set_width (self, width)
set_height (self, height)
get_visible_children (self)
get_window_extent (self, renderer=None)
Public Attributes
da = DrawingArea(width, height, xdescent, ydescent)
drawing_area = self.da
Public Attributes inherited from matplotlib.offsetbox.AnchoredOffsetbox
loc = loc
borderpad = borderpad
pad = pad
prop = FontProperties(size=mpl.rcParams["legend.fontsize"])
patch
Public Attributes inherited from matplotlib.offsetbox.OffsetBox
bool stale = True
width = width
height = height
Additional Inherited Members
Static Public Attributes inherited from matplotlib.offsetbox.AnchoredOffsetbox
int zorder = 5
dict codes
Protected Member Functions inherited from matplotlib.offsetbox.OffsetBox
_get_bbox_and_child_offsets (self, renderer)
Protected Attributes inherited from matplotlib.offsetbox.AnchoredOffsetbox
_child = child
_bbox_to_anchor
_bbox_to_anchor_transform = transform
Protected Attributes inherited from matplotlib.offsetbox.OffsetBox
list _children = []
tuple _offset = (0, 0)
Detailed Description
Definition at line 12 of file anchored_artists.py.
Constructor & Destructor Documentation
__init__()
axes_grid1.anchored_artists.AnchoredDrawingArea.__init__ (self, width, height, xdescent, ydescent, loc, pad = 0.4, borderpad = 0.5, prop = None, frameon = True, ** kwargs)
An anchored container with a fixed size and fillable `.DrawingArea`.
Artists added to the *drawing_area* will have their coordinates
interpreted as pixels. Any transformations set on the artists will be
overridden.
Parameters
----------
width, height : float
    Width and height of the container, in pixels.
xdescent, ydescent : float
    Descent of the container in the x- and y- direction, in pixels.
loc : str
    Location of this artist.  Valid locations are
    'upper left', 'upper center', 'upper right',
    'center left', 'center', 'center right',
    'lower left', 'lower center', 'lower right'.
    For backward compatibility, numeric values are accepted as well.
    See the parameter *loc* of `.Legend` for details.
pad : float, default: 0.4
    Padding around the child objects, in fraction of the font size.
borderpad : float, default: 0.5
    Border padding, in fraction of the font size.
prop : `~matplotlib.font_manager.FontProperties`, optional
    Font property used as a reference for paddings.
frameon : bool, default: True
    If True, draw a box around this artist.
**kwargs
    Keyword arguments forwarded to `.AnchoredOffsetbox`.
Attributes
----------
drawing_area : `~matplotlib.offsetbox.DrawingArea`
    A container for artists to display.
Examples
--------
To display blue and red circles of different sizes in the upper right
of an Axes *ax*:
>>> ada = AnchoredDrawingArea(20, 20, 0, 0,
...                           loc='upper right', frameon=False)
>>> ada.drawing_area.add_artist(Circle((10, 10), 10, fc="b"))
>>> ada.drawing_area.add_artist(Circle((30, 10), 5, fc="r"))
>>> ax.add_artist(ada)
Definition at line 13 of file anchored_artists.py.
References __init__(), da, and drawing_area.
Referenced by __init__(), sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Data Documentation
da
axes_grid1.anchored_artists.AnchoredDrawingArea.da = DrawingArea(width, height, xdescent, ydescent)
Definition at line 63 of file anchored_artists.py.
Referenced by __init__().
drawing_area
axes_grid1.anchored_artists.AnchoredDrawingArea.drawing_area = self.da
Definition at line 64 of file anchored_artists.py.
Referenced by axes_grid1.anchored_artists.AnchoredAuxTransformBox.__init__(), and __init__().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/mpl_toolkits/axes_grid1/anchored_artists.py