Code Cloning Analysis: numpy.f2py.crackfortran Namespace Reference
numpy.f2py.crackfortran Namespace Reference
Functions
reset_global_f2py_vars ()
outmess (line, flag=1)
rmbadname1 (name)
rmbadname (names)
undo_rmbadname1 (name)
undo_rmbadname (names)
openhook (filename, mode)
is_free_format (fname)
readfortrancode (ffile, dowithline=show, istop=1)
split_by_unquoted (line, characters)
_simplifyargs (argsline)
crackline (line, reset=0)
markouterparen (line)
markoutercomma (line, comma=',')
unmarkouterparen (line)
appenddecl (decl, decl2, force=1)
_is_intent_callback (vdecl)
_resolvetypedefpattern (line)
parse_name_for_bind (line)
_resolvenameargspattern (line)
analyzeline (m, case, line)
appendmultiline (group, context_name, ml)
cracktypespec0 (typespec, ll)
removespaces (expr)
markinnerspaces (line)
updatevars (typespec, selector, attrspec, entitydecl)
cracktypespec (typespec, selector)
setattrspec (decl, attr, force=0)
setkindselector (decl, sel, force=0)
setcharselector (decl, sel, force=0)
getblockname (block, unknown='unknown')
setmesstext (block)
get_usedict (block)
get_useparameters (block, param_map=None)
postcrack2 (block, tab='', param_map=None)
postcrack (block, args=None, tab='')
sortvarnames (vars)
analyzecommon (block)
analyzebody (block, args, tab='')
buildimplicitrules (block)
myeval (e, g=None, l=None)
getlincoef (e, xset)
_get_depend_dict (name, vars, deps)
_calc_depend_dict (vars)
get_sorted_names (vars)
_kind_func (string)
_selected_int_kind_func (r)
_selected_real_kind_func (p, r=0, radix=0)
get_parameters (vars, global_params={})
_eval_length (length, params)
_eval_scalar (value, params)
analyzevars (block)
param_eval (v, g_params, params, dimspec=None)
param_parse (d, params)
expr2name (a, block, args=[])
analyzeargs (block)
_ensure_exprdict (r)
determineexprtype (expr, vars, rules={})
crack2fortrangen (block, tab='\n', as_interface=False)
common2fortran (common, tab='')
use2fortran (use, tab='')
true_intent_list (var)
vars2fortran (block, vars, args, tab='', as_interface=False)
crackfortran (files)
crack2fortran (block)
_is_visit_pair (obj)
traverse (obj, visit, parents=[], result=None, *args, **kwargs)
character_backward_compatibility_hook (item, parents, result, *args, **kwargs)
Variables
charset_normalizer = None
f2py_version = __version__.version
int strictf77 = 1
str sourcecodeform = 'fix'
int quiet = 0
int verbose = 1
int tabchar = 4 * ' '
str pyffilename = ''
str f77modulename = ''
int skipemptyends = 0
int ignorecontains = 1
int dolowercase = 1
list debug = []
str beginpattern = ''
str currentfilename = ''
int expectbegin = 1
dict f90modulevars = {}
str filepositiontext = ''
int gotnextfile = 1
groupcache = None
int groupcounter = 0
dict grouplist = {groupcounter: []}
str groupname = ''
list include_paths = []
int neededmodule = -1
list onlyfuncs = []
previous_context = None
int skipblocksuntil = -1
list skipfuncs = []
list skipfunctions = []
list usermodules = []
_MAXCACHE
dict defaultimplicitrules = {}
dict badnames = {}
dict invbadnames = {}
_has_f_header = re.compile(r'-\*-\s*fortran\s*-\*-', re.I).search
_has_f90_header = re.compile(r'-\*-\s*f90\s*-\*-', re.I).search
_has_fix_header = re.compile(r'-\*-\s*fix\s*-\*-', re.I).search
_free_f90_start = re.compile(r'[^c*]\s*[^\s\d\t]', re.I).match
list COMMON_FREE_EXTENSIONS = ['.f90', '.f95', '.f03', '.f08']
list COMMON_FIXED_EXTENSIONS = ['.for', '.ftn', '.f77', '.f']
str beforethisafter
str fortrantypes = r'character|logical|integer|real|complex|double\s*(precision\s*(complex|)|complex)|type(?=\s*\‍([\w\s,=(*)]*\‍))|byte'
str typespattern
typespattern4implicit
str functionpattern
str subroutinepattern
str groupbegins77 = r'program|block\s*data'
str beginpattern77
str groupbegins90
str beginpattern90
tuple groupends
str endpattern
str endifs
str endifpattern
str moduleprocedures = r'module\s*procedure'
str moduleprocedurepattern
str implicitpattern
str dimensionpattern
str externalpattern
str optionalpattern
str requiredpattern
str publicpattern
str privatepattern
str intrinsicpattern
str intentpattern
str parameterpattern
str datapattern
str callpattern
str entrypattern
str callfunpattern
str commonpattern
str usepattern
str containspattern
str formatpattern
str f2pyenhancementspattern
str multilinepattern
crackline_re_1 = re.compile(r'\s*(?P<result>\b[a-z]+\w*\b)\s*=.*', re.I)
crackline_bind_1 = re.compile(r'\s*(?P<bind>\b[a-z]+\w*\b)\s*=.*', re.I)
crackline_bindlang = re.compile(r'\s*bind\(\s*(?P<lang>[^,]+)\s*,\s*name\s*=\s*"(?P<lang_name>[^"]+)"\s*\‍)', re.I)
selectpattern
typedefpattern
nameargspattern
operatorpattern
callnameargspattern
real16pattern
real8pattern
_intentcallbackpattern = re.compile(r'intent\s*\‍(.*?\bcallback\b', re.I)
namepattern = re.compile(r'\s*(?P<name>\b\w+\b)\s*(?P<after>.*)\s*\Z', re.I)
kindselector
charselector
lenkindpattern
lenarraypattern
getlincoef_re_1 = re.compile(r'\A\b\w+\b\Z', re.I)
word_pattern = re.compile(r'\b[a-z][\w$]*\b', re.I)
_is_kind_number = re.compile(r'\d+_').match
analyzeargs_re_1 = re.compile(r'\A[a-z]+[\w$]*\Z', re.I)
determineexprtype_re_1 = re.compile(r'\A\(.+?,.+?\‍)\Z', re.I)
determineexprtype_re_2 = re.compile(r'\A[+-]?\d+(_(?P<name>\w+)|)\Z', re.I)
determineexprtype_re_3
determineexprtype_re_4 = re.compile(r'\A\(.*\‍)\Z', re.I)
determineexprtype_re_5 = re.compile(r'\A(?P<name>\w+)\s*\‍(.*?\‍)\s*\Z', re.I)
list post_processing_hooks = []
list files = []
list funcs = []
int f = 1
int f2 = 0
int f3 = 0
int showblocklist = 0
postlist = crackfortran(files)
pyf = crack2fortran(postlist)
Detailed Description
crackfortran --- read fortran (77,90) code and extract declaration information.
Copyright 1999 -- 2011 Pearu Peterson all rights reserved.
Copyright 2011 -- present NumPy Developers.
Permission to use, modify, and distribute this software is given under the
terms of the NumPy License.
NO WARRANTY IS EXPRESSED OR IMPLIED.  USE AT YOUR OWN RISK.
Usage of crackfortran:
======================
Command line keys: -quiet,-verbose,-fix,-f77,-f90,-show,-h <pyffilename>
                   -m <module name for f77 routines>,--ignore-contains
Functions: crackfortran, crack2fortran
The following Fortran statements/constructions are supported
(or will be if needed):
   block data,byte,call,character,common,complex,contains,data,
   dimension,double complex,double precision,end,external,function,
   implicit,integer,intent,interface,intrinsic,
   logical,module,optional,parameter,private,public,
   program,real,(sequence?),subroutine,type,use,virtual,
   include,pythonmodule
Note: 'virtual' is mapped to 'dimension'.
Note: 'implicit integer (z) static (z)' is 'implicit static (z)' (this is minor bug).
Note: code after 'contains' will be ignored until its scope ends.
Note: 'common' statement is extended: dimensions are moved to variable definitions
Note: f2py directive: <commentchar>f2py<line> is read as <line>
Note: pythonmodule is introduced to represent Python module
Usage:
  `postlist=crackfortran(files)`
  `postlist` contains declaration information read from the list of files `files`.
  `crack2fortran(postlist)` returns a fortran code to be saved to pyf-file
  `postlist` has the following structure:
 *** it is a list of dictionaries containing `blocks':
     B = {'block','body','vars','parent_block'[,'name','prefix','args','result',
          'implicit','externals','interfaced','common','sortvars',
          'commonvars','note']}
     B['block'] = 'interface' | 'function' | 'subroutine' | 'module' |
                  'program' | 'block data' | 'type' | 'pythonmodule' |
                  'abstract interface'
     B['body'] --- list containing `subblocks' with the same structure as `blocks'
     B['parent_block'] --- dictionary of a parent block:
                             C['body'][<index>]['parent_block'] is C
     B['vars'] --- dictionary of variable definitions
     B['sortvars'] --- dictionary of variable definitions sorted by dependence (independent first)
     B['name'] --- name of the block (not if B['block']=='interface')
     B['prefix'] --- prefix string (only if B['block']=='function')
     B['args'] --- list of argument names if B['block']== 'function' | 'subroutine'
     B['result'] --- name of the return value (only if B['block']=='function')
     B['implicit'] --- dictionary {'a':<variable definition>,'b':...} | None
     B['externals'] --- list of variables being external
     B['interfaced'] --- list of variables being external and defined
     B['common'] --- dictionary of common blocks (list of objects)
     B['commonvars'] --- list of variables used in common blocks (dimensions are moved to variable definitions)
     B['from'] --- string showing the 'parents' of the current block
     B['use'] --- dictionary of modules used in current block:
         {<modulename>:{['only':<0|1>],['map':{<local_name1>:<use_name1>,...}]}}
     B['note'] --- list of LaTeX comments on the block
     B['f2pyenhancements'] --- optional dictionary
          {'threadsafe':'','fortranname':<name>,
           'callstatement':<C-expr>|<multi-line block>,
           'callprotoargument':<C-expr-list>,
           'usercode':<multi-line block>|<list of multi-line blocks>,
           'pymethoddef:<multi-line block>'
           }
     B['entry'] --- dictionary {entryname:argslist,..}
     B['varnames'] --- list of variable names given in the order of reading the
                       Fortran code, useful for derived types.
     B['saved_interface'] --- a string of scanned routine signature, defines explicit interface
 *** Variable definition is a dictionary
     D = B['vars'][<variable name>] =
     {'typespec'[,'attrspec','kindselector','charselector','=','typename']}
     D['typespec'] = 'byte' | 'character' | 'complex' | 'double complex' |
                     'double precision' | 'integer' | 'logical' | 'real' | 'type'
     D['attrspec'] --- list of attributes (e.g. 'dimension(<arrayspec>)',
                       'external','intent(in|out|inout|hide|c|callback|cache|aligned4|aligned8|aligned16)',
                       'optional','required', etc)
     K = D['kindselector'] = {['*','kind']} (only if D['typespec'] =
                         'complex' | 'integer' | 'logical' | 'real' )
     C = D['charselector'] = {['*','len','kind','f2py_len']}
                             (only if D['typespec']=='character')
     D['='] --- initialization expression string
     D['typename'] --- name of the type if D['typespec']=='type'
     D['dimension'] --- list of dimension bounds
     D['intent'] --- list of intent specifications
     D['depend'] --- list of variable names on which current variable depends on
     D['check'] --- list of C-expressions; if C-expr returns zero, exception is raised
     D['note'] --- list of LaTeX comments on the variable
 *** Meaning of kind/char selectors (few examples):
     D['typespec>']*K['*']
     D['typespec'](kind=K['kind'])
     character*C['*']
     character(len=C['len'],kind=C['kind'], f2py_len=C['f2py_len'])
     (see also fortran type declaration statement formats below)
Fortran 90 type declaration statement format (F77 is subset of F90)
====================================================================
(Main source: IBM XL Fortran 5.1 Language Reference Manual)
type declaration = <typespec> [[<attrspec>]::] <entitydecl>
<typespec> = byte                          |
             character[<charselector>]     |
             complex[<kindselector>]       |
             double complex                |
             double precision              |
             integer[<kindselector>]       |
             logical[<kindselector>]       |
             real[<kindselector>]          |
             type(<typename>)
<charselector> = * <charlen>               |
             ([len=]<len>[,[kind=]<kind>]) |
             (kind=<kind>[,len=<len>])
<kindselector> = * <intlen>                |
             ([kind=]<kind>)
<attrspec> = comma separated list of attributes.
             Only the following attributes are used in
             building up the interface:
                external
                (parameter --- affects '=' key)
                optional
                intent
             Other attributes are ignored.
<intentspec> = in | out | inout
<arrayspec> = comma separated list of dimension bounds.
<entitydecl> = <name> [[*<charlen>][(<arrayspec>)] | [(<arrayspec>)]*<charlen>]
                      [/<init_expr>/ | =<init_expr>] [,<entitydecl>]
In addition, the following attributes are used: check,depend,note
TODO:
    * Apply 'parameter' attribute (e.g. 'integer parameter :: i=2' 'real x(i)'
                                   -> 'real x(2)')
    The above may be solved by creating appropriate preprocessor program, for example.
Function Documentation
_calc_depend_dict()
numpy.f2py.crackfortran._calc_depend_dict (vars) protected
Definition at line 2408 of file crackfortran.py.
_ensure_exprdict()
numpy.f2py.crackfortran._ensure_exprdict (r) protected
Definition at line 3213 of file crackfortran.py.
_eval_length()
numpy.f2py.crackfortran._eval_length (length, params) protected
Definition at line 2581 of file crackfortran.py.
_eval_scalar()
numpy.f2py.crackfortran._eval_scalar (value, params) protected
Definition at line 2590 of file crackfortran.py.
_get_depend_dict()
numpy.f2py.crackfortran._get_depend_dict (name, vars, deps) protected
Definition at line 2386 of file crackfortran.py.
_is_intent_callback()
numpy.f2py.crackfortran._is_intent_callback (vdecl) protected
Definition at line 952 of file crackfortran.py.
_is_visit_pair()
numpy.f2py.crackfortran._is_visit_pair (obj) protected
Definition at line 3559 of file crackfortran.py.
_kind_func()
numpy.f2py.crackfortran._kind_func (string) protected
Definition at line 2434 of file crackfortran.py.
_resolvenameargspattern()
numpy.f2py.crackfortran._resolvenameargspattern (line) protected
Definition at line 979 of file crackfortran.py.
_resolvetypedefpattern()
numpy.f2py.crackfortran._resolvetypedefpattern (line) protected
Definition at line 959 of file crackfortran.py.
_selected_int_kind_func()
numpy.f2py.crackfortran._selected_int_kind_func (r) protected
Definition at line 2445 of file crackfortran.py.
_selected_real_kind_func()
numpy.f2py.crackfortran._selected_real_kind_func (p, r = 0, radix = 0) protected
Definition at line 2461 of file crackfortran.py.
_simplifyargs()
numpy.f2py.crackfortran._simplifyargs (argsline) protected
Definition at line 688 of file crackfortran.py.
analyzeargs()
numpy.f2py.crackfortran.analyzeargs (block)
Definition at line 3179 of file crackfortran.py.
analyzebody()
numpy.f2py.crackfortran.analyzebody (block, args, tab = '')
Definition at line 2237 of file crackfortran.py.
analyzecommon()
numpy.f2py.crackfortran.analyzecommon (block)
Definition at line 2194 of file crackfortran.py.
analyzeline()
numpy.f2py.crackfortran.analyzeline (m, case, line)
Reads each line in the input file in sequence and updates global vars.
Effectively reads and collects information from the input file to the
global variable groupcache, a dictionary containing info about each part
of the fortran module.
At the end of analyzeline, information is filtered into the correct dict
keys, but parameter values and dimensions are not yet interpreted.
Definition at line 995 of file crackfortran.py.
References numpy.core.fromnumeric.any(), numpy.lib.function_base.append(), numpy.lib.shape_base.split(), and updatevars().
Referenced by crackline().
analyzevars()
numpy.f2py.crackfortran.analyzevars (block)
Sets correct dimension information for each variable/parameter
Definition at line 2606 of file crackfortran.py.
References numpy.lib.function_base.append(), param_parse(), and numpy.lib.shape_base.split().
Referenced by postcrack().
appenddecl()
numpy.f2py.crackfortran.appenddecl (decl, decl2, force = 1)
Definition at line 901 of file crackfortran.py.
appendmultiline()
numpy.f2py.crackfortran.appendmultiline (group, context_name, ml)
Definition at line 1590 of file crackfortran.py.
buildimplicitrules()
numpy.f2py.crackfortran.buildimplicitrules (block)
Definition at line 2282 of file crackfortran.py.
character_backward_compatibility_hook()
numpy.f2py.crackfortran.character_backward_compatibility_hook (item, parents, result, * args, ** kwargs)
Previously, Fortran character was incorrectly treated as
character*1. This hook fixes the usage of the corresponding
variables in `check`, `dimension`, `=`, and `callstatement`
expressions.
The usage of `char*` in `callprotoargument` expression can be left
unchanged because C `character` is C typedef of `char`, although,
new implementations should use `character*` in the corresponding
expressions.
See https://github.com/numpy/numpy/pull/19388 for more information.
Definition at line 3631 of file crackfortran.py.
common2fortran()
numpy.f2py.crackfortran.common2fortran (common, tab = '')
Definition at line 3345 of file crackfortran.py.
crack2fortran()
numpy.f2py.crackfortran.crack2fortran (block)
Definition at line 3544 of file crackfortran.py.
crack2fortrangen()
numpy.f2py.crackfortran.crack2fortrangen (block, tab = '\n', as_interface = False)
Definition at line 3270 of file crackfortran.py.
crackfortran()
numpy.f2py.crackfortran.crackfortran (files)
Definition at line 3527 of file crackfortran.py.
crackline()
numpy.f2py.crackfortran.crackline (line, reset = 0)
reset=-1  --- initialize
reset=0   --- crack the line
reset=1   --- final check if mismatch of blocks occurred
Cracked data is saved in grouplist[0].
Definition at line 700 of file crackfortran.py.
References analyzeline(), numpy.lib.function_base.append(), crackline(), and split_by_unquoted().
Referenced by crackline().
cracktypespec()
numpy.f2py.crackfortran.cracktypespec (typespec, selector)
Definition at line 1860 of file crackfortran.py.
cracktypespec0()
numpy.f2py.crackfortran.cracktypespec0 (typespec, ll)
Definition at line 1600 of file crackfortran.py.
determineexprtype()
numpy.f2py.crackfortran.determineexprtype (expr, vars, rules = {})
Definition at line 3225 of file crackfortran.py.
expr2name()
numpy.f2py.crackfortran.expr2name (a, block, args = [])
Definition at line 3142 of file crackfortran.py.
get_parameters()
numpy.f2py.crackfortran.get_parameters (vars, global_params = {})
Definition at line 2480 of file crackfortran.py.
get_sorted_names()
numpy.f2py.crackfortran.get_sorted_names (vars)
Definition at line 2416 of file crackfortran.py.
get_usedict()
numpy.f2py.crackfortran.get_usedict (block)
Definition at line 1993 of file crackfortran.py.
get_useparameters()
numpy.f2py.crackfortran.get_useparameters (block, param_map = None)
Definition at line 2002 of file crackfortran.py.
getblockname()
numpy.f2py.crackfortran.getblockname (block, unknown = 'unknown')
Definition at line 1976 of file crackfortran.py.
getlincoef()
numpy.f2py.crackfortran.getlincoef (e, xset)
Obtain ``a`` and ``b`` when ``e == "a*x+b"``, where ``x`` is a symbol in
xset.
>>> getlincoef('2*x + 1', {'x'})
(2, 1, 'x')
>>> getlincoef('3*x + x*2 + 2 + 1', {'x'})
(5, 3, 'x')
>>> getlincoef('0', {'x'})
(0, 0, None)
>>> getlincoef('0*x', {'x'})
(0, 0, 'x')
>>> getlincoef('x*x', {'x'})
(None, None, None)
This can be tricked by sufficiently complex expressions
>>> getlincoef('(x - 0.5)*(x - 1.5)*(x - 1)*x + 2*x + 3', {'x'})
(2.0, 3.0, 'x')
Definition at line 2311 of file crackfortran.py.
References myeval(), and param_eval().
is_free_format()
numpy.f2py.crackfortran.is_free_format (fname)
Check if file is in free format Fortran.
Definition at line 332 of file crackfortran.py.
References openhook().
Referenced by readfortrancode().
markinnerspaces()
numpy.f2py.crackfortran.markinnerspaces (line)
The function replace all spaces in the input variable line which are
surrounded with quotation marks, with the triplet "@_@".
For instance, for the input "a 'b c'" the function returns "a 'b@_@c'"
Parameters
----------
line : str
Returns
-------
str
Definition at line 1654 of file crackfortran.py.
Referenced by updatevars().
markoutercomma()
numpy.f2py.crackfortran.markoutercomma (line, comma = ',')
Definition at line 877 of file crackfortran.py.
markouterparen()
numpy.f2py.crackfortran.markouterparen (line)
Definition at line 859 of file crackfortran.py.
myeval()
numpy.f2py.crackfortran.myeval (e, g = None, l = None)
 Like `eval` but returns only integers and floats
Definition at line 2301 of file crackfortran.py.
Referenced by getlincoef().
openhook()
numpy.f2py.crackfortran.openhook (filename, mode)
Ensures that filename is opened with correct encoding parameter.
This function uses charset_normalizer package, when available, for
determining the encoding of the file to be opened. When charset_normalizer
is not available, the function detects only UTF encodings, otherwise, ASCII
encoding is used as fallback.
Definition at line 301 of file crackfortran.py.
References numpy.core.fromnumeric.min().
Referenced by is_free_format().
outmess()
numpy.f2py.crackfortran.outmess (line, flag = 1)
Definition at line 236 of file crackfortran.py.
param_eval()
numpy.f2py.crackfortran.param_eval (v, g_params, params, dimspec = None)
Creates a dictionary of indices and values for each parameter in a
parameter array to be evaluated later.
WARNING: It is not possible to initialize multidimensional array
parameters e.g. dimension(-3:1, 4, 3:5) at this point. This is because in
Fortran initialization through array constructor requires the RESHAPE
intrinsic function. Since the right-hand side of the parameter declaration
is not executed in f2py, but rather at the compiled c/fortran extension,
later, it is not possible to execute a reshape of a parameter array.
One issue remains: if the user wants to access the array parameter from
python, we should either
1) allow them to access the parameter array using python standard indexing
   (which is often incompatible with the original fortran indexing)
2) allow the parameter array to be accessed in python as a dictionary with
   fortran indices as keys
We are choosing 2 for now.
Definition at line 3000 of file crackfortran.py.
References param_parse(), and numpy.lib.shape_base.split().
Referenced by getlincoef().
param_parse()
numpy.f2py.crackfortran.param_parse (d, params)
Recursively parse array dimensions.
Parses the declaration of an array variable or parameter
`dimension` keyword, and is called recursively if the
dimension for this array is a previously defined parameter
(found in `params`).
Parameters
----------
d : str
    Fortran expression describing the dimension of an array.
params : dict
    Previously parsed parameters declared in the Fortran source file.
Returns
-------
out : str
    Parsed dimension expression.
Examples
--------
* If the line being analyzed is
  `integer, parameter, dimension(2) :: pa = (/ 3, 5 /)`
  then `d = 2` and we return immediately, with
>>> d = '2'
>>> param_parse(d, params)
2
* If the line being analyzed is
  `integer, parameter, dimension(pa) :: pb = (/1, 2, 3/)`
  then `d = 'pa'`; since `pa` is a previously parsed parameter,
  and `pa = 3`, we call `param_parse` recursively, to obtain
>>> d = 'pa'
>>> params = {'pa': 3}
>>> param_parse(d, params)
3
* If the line being analyzed is
  `integer, parameter, dimension(pa(1)) :: pb = (/1, 2, 3/)`
  then `d = 'pa(1)'`; since `pa` is a previously parsed parameter,
  and `pa(1) = 3`, we call `param_parse` recursively, to obtain
>>> d = 'pa(1)'
>>> params = dict(pa={1: 3, 2: 5})
>>> param_parse(d, params)
3
Definition at line 3062 of file crackfortran.py.
References numpy.lib.function_base.append(), param_parse(), postcrack(), readfortrancode(), numpy.lib.shape_base.split(), and traverse().
Referenced by analyzevars(), param_eval(), and param_parse().
parse_name_for_bind()
numpy.f2py.crackfortran.parse_name_for_bind (line)
Definition at line 969 of file crackfortran.py.
postcrack()
numpy.f2py.crackfortran.postcrack (block, args = None, tab = '')
TODO:
      function return values
      determine expression types if in argument list
Definition at line 2064 of file crackfortran.py.
References analyzevars(), numpy.lib.function_base.append(), postcrack(), and numpy.lib.shape_base.split().
Referenced by param_parse(), and postcrack().
postcrack2()
numpy.f2py.crackfortran.postcrack2 (block, tab = '', param_map = None)
Definition at line 2032 of file crackfortran.py.
readfortrancode()
numpy.f2py.crackfortran.readfortrancode (ffile, dowithline = show, istop = 1)
Read fortran codes from files and
 1) Get rid of comments, line continuations, and empty lines; lower cases.
 2) Call dowithline(line) on every line.
 3) Recursively call itself when statement \"include '<filename>'\" is met.
Definition at line 358 of file crackfortran.py.
References is_free_format(), readfortrancode(), and split_by_unquoted().
Referenced by param_parse(), and readfortrancode().
removespaces()
numpy.f2py.crackfortran.removespaces (expr)
Definition at line 1639 of file crackfortran.py.
reset_global_f2py_vars()
numpy.f2py.crackfortran.reset_global_f2py_vars ()
Definition at line 198 of file crackfortran.py.
rmbadname()
numpy.f2py.crackfortran.rmbadname (names)
Definition at line 275 of file crackfortran.py.
rmbadname1()
numpy.f2py.crackfortran.rmbadname1 (name)
Definition at line 267 of file crackfortran.py.
setattrspec()
numpy.f2py.crackfortran.setattrspec (decl, attr, force = 0)
Definition at line 1920 of file crackfortran.py.
setcharselector()
numpy.f2py.crackfortran.setcharselector (decl, sel, force = 0)
Definition at line 1961 of file crackfortran.py.
setkindselector()
numpy.f2py.crackfortran.setkindselector (decl, sel, force = 0)
Definition at line 1947 of file crackfortran.py.
setmesstext()
numpy.f2py.crackfortran.setmesstext (block)
Definition at line 1984 of file crackfortran.py.
sortvarnames()
numpy.f2py.crackfortran.sortvarnames (vars)
Definition at line 2160 of file crackfortran.py.
split_by_unquoted()
numpy.f2py.crackfortran.split_by_unquoted (line, characters)
Splits the line into (line[:i], line[i:]),
where i is the index of first occurrence of one of the characters
not within quotes, or len(line) if no such index exists
Definition at line 668 of file crackfortran.py.
References numpy.lib.shape_base.split().
Referenced by crackline(), and readfortrancode().
traverse()
numpy.f2py.crackfortran.traverse (obj, visit, parents = [], result = None, * args, ** kwargs)
Traverse f2py data structure with the following visit function:
def visit(item, parents, result, *args, **kwargs):
    """
    parents is a list of key-"f2py data structure" pairs from which
    items are taken from.
    result is a f2py data structure that is filled with the
    return value of the visit function.
    item is 2-tuple (index, value) if parents[-1][1] is a list
    item is 2-tuple (key, value) if parents[-1][1] is a dict
    The return value of visit must be None, or of the same kind as
    item, that is, if parents[-1] is a list, the return value must
    be 2-tuple (new_index, new_value), or if parents[-1] is a
    dict, the return value must be 2-tuple (new_key, new_value).
    If new_index or new_value is None, the return value of visit
    is ignored, that is, it will not be added to the result.
    If the return value is None, the content of obj will be
    traversed, otherwise not.
    """
Definition at line 3565 of file crackfortran.py.
References traverse().
Referenced by param_parse(), and traverse().
true_intent_list()
numpy.f2py.crackfortran.true_intent_list (var)
Definition at line 3379 of file crackfortran.py.
undo_rmbadname()
numpy.f2py.crackfortran.undo_rmbadname (names)
Definition at line 287 of file crackfortran.py.
undo_rmbadname1()
numpy.f2py.crackfortran.undo_rmbadname1 (name)
Definition at line 279 of file crackfortran.py.
unmarkouterparen()
numpy.f2py.crackfortran.unmarkouterparen (line)
Definition at line 896 of file crackfortran.py.
updatevars()
numpy.f2py.crackfortran.updatevars (typespec, selector, attrspec, entitydecl)
Returns last_name, the variable name without special chars, parenthesis
    or dimension specifiers.
Alters groupcache to add the name, typespec, attrspec (and possibly value)
of current variable.
Definition at line 1691 of file crackfortran.py.
References numpy.lib.function_base.append(), markinnerspaces(), and numpy.lib.shape_base.split().
Referenced by analyzeline().
use2fortran()
numpy.f2py.crackfortran.use2fortran (use, tab = '')
Definition at line 3355 of file crackfortran.py.
vars2fortran()
numpy.f2py.crackfortran.vars2fortran (block, vars, args, tab = '', as_interface = False)
Definition at line 3393 of file crackfortran.py.
Variable Documentation
_free_f90_start
numpy.f2py.crackfortran._free_f90_start = re.compile(r'[^c*]\s*[^\s\d\t]', re.I).match protected
Definition at line 294 of file crackfortran.py.
_has_f90_header
numpy.f2py.crackfortran._has_f90_header = re.compile(r'-\*-\s*f90\s*-\*-', re.I).search protected
Definition at line 292 of file crackfortran.py.
_has_f_header
numpy.f2py.crackfortran._has_f_header = re.compile(r'-\*-\s*fortran\s*-\*-', re.I).search protected
Definition at line 291 of file crackfortran.py.
_has_fix_header
numpy.f2py.crackfortran._has_fix_header = re.compile(r'-\*-\s*fix\s*-\*-', re.I).search protected
Definition at line 293 of file crackfortran.py.
_intentcallbackpattern
numpy.f2py.crackfortran._intentcallbackpattern = re.compile(r'intent\s*\‍(.*?\bcallback\b', re.I) protected
Definition at line 949 of file crackfortran.py.
_is_kind_number
numpy.f2py.crackfortran._is_kind_number = re.compile(r'\d+_').match protected
Definition at line 2587 of file crackfortran.py.
_MAXCACHE
numpy.f2py.crackfortran._MAXCACHE protected
Definition at line 246 of file crackfortran.py.
analyzeargs_re_1
numpy.f2py.crackfortran.analyzeargs_re_1 = re.compile(r'\A[a-z]+[\w$]*\Z', re.I)
Definition at line 2997 of file crackfortran.py.
badnames
dict numpy.f2py.crackfortran.badnames = {}
Definition at line 252 of file crackfortran.py.
beforethisafter
str numpy.f2py.crackfortran.beforethisafter
Initial value:
=  r'\s*(?P<before>%s(?=\s*(\b(%s)\b)))' + \
    r'\s*(?P<this>(\b(%s)\b))' + \
    r'\s*(?P<after>%s)\s*\Z'
Definition at line 587 of file crackfortran.py.
beginpattern
str numpy.f2py.crackfortran.beginpattern = ''
Definition at line 178 of file crackfortran.py.
beginpattern77
str numpy.f2py.crackfortran.beginpattern77
Initial value:
=  re.compile(
    beforethisafter % ('', groupbegins77, groupbegins77, '.*'), re.I), 'begin'
Definition at line 604 of file crackfortran.py.
beginpattern90
str numpy.f2py.crackfortran.beginpattern90
Initial value:
=  re.compile(
    beforethisafter % ('', groupbegins90, groupbegins90, '.*'), re.I), 'begin'
Definition at line 609 of file crackfortran.py.
callfunpattern
str numpy.f2py.crackfortran.callfunpattern
Initial value:
=  re.compile(
    beforethisafter % ('', 'callfun', 'callfun', '.*'), re.I), 'callfun'
Definition at line 651 of file crackfortran.py.
callnameargspattern
numpy.f2py.crackfortran.callnameargspattern
Initial value:
=  re.compile(
    r'\s*(?P<name>\b[\w$]+\b)\s*@\‍(@\s*(?P<args>.*)\s*@\‍)@\s*\Z', re.I)
Definition at line 942 of file crackfortran.py.
callpattern
str numpy.f2py.crackfortran.callpattern
Initial value:
=  re.compile(
    beforethisafter % ('', 'call', 'call', '.*'), re.I), 'call'
Definition at line 647 of file crackfortran.py.
charselector
numpy.f2py.crackfortran.charselector
Initial value:
=  re.compile(
    r'\s*(\‍((?P<lenkind>.*)\‍)|\*\s*(?P<charlen>.*))\s*\Z', re.I)
Definition at line 1629 of file crackfortran.py.
charset_normalizer
numpy.f2py.crackfortran.charset_normalizer = None
Definition at line 152 of file crackfortran.py.
COMMON_FIXED_EXTENSIONS
list numpy.f2py.crackfortran.COMMON_FIXED_EXTENSIONS = ['.for', '.ftn', '.f77', '.f']
Definition at line 298 of file crackfortran.py.
COMMON_FREE_EXTENSIONS
list numpy.f2py.crackfortran.COMMON_FREE_EXTENSIONS = ['.f90', '.f95', '.f03', '.f08']
Definition at line 297 of file crackfortran.py.
commonpattern
str numpy.f2py.crackfortran.commonpattern
Initial value:
=  re.compile(
    beforethisafter % ('', 'common', 'common', '.*'), re.I), 'common'
Definition at line 653 of file crackfortran.py.
containspattern
str numpy.f2py.crackfortran.containspattern
Initial value:
=  re.compile(
    beforethisafter % ('', 'contains', 'contains', ''), re.I), 'contains'
Definition at line 657 of file crackfortran.py.
crackline_bind_1
numpy.f2py.crackfortran.crackline_bind_1 = re.compile(r'\s*(?P<bind>\b[a-z]+\w*\b)\s*=.*', re.I)
Definition at line 697 of file crackfortran.py.
crackline_bindlang
numpy.f2py.crackfortran.crackline_bindlang = re.compile(r'\s*bind\(\s*(?P<lang>[^,]+)\s*,\s*name\s*=\s*"(?P<lang_name>[^"]+)"\s*\‍)', re.I)
Definition at line 698 of file crackfortran.py.
crackline_re_1
numpy.f2py.crackfortran.crackline_re_1 = re.compile(r'\s*(?P<result>\b[a-z]+\w*\b)\s*=.*', re.I)
Definition at line 696 of file crackfortran.py.
currentfilename
str numpy.f2py.crackfortran.currentfilename = ''
Definition at line 179 of file crackfortran.py.
datapattern
str numpy.f2py.crackfortran.datapattern
Initial value:
=  re.compile(
    beforethisafter % ('', 'data', 'data', '.*'), re.I), 'data'
Definition at line 645 of file crackfortran.py.
debug
list numpy.f2py.crackfortran.debug = []
Definition at line 175 of file crackfortran.py.
defaultimplicitrules
dict numpy.f2py.crackfortran.defaultimplicitrules = {}
Definition at line 247 of file crackfortran.py.
determineexprtype_re_1
numpy.f2py.crackfortran.determineexprtype_re_1 = re.compile(r'\A\(.+?,.+?\‍)\Z', re.I)
Definition at line 3205 of file crackfortran.py.
determineexprtype_re_2
numpy.f2py.crackfortran.determineexprtype_re_2 = re.compile(r'\A[+-]?\d+(_(?P<name>\w+)|)\Z', re.I)
Definition at line 3206 of file crackfortran.py.
determineexprtype_re_3
numpy.f2py.crackfortran.determineexprtype_re_3
Initial value:
=  re.compile(
    r'\A[+-]?[\d.]+[-\d+de.]*(_(?P<name>\w+)|)\Z', re.I)
Definition at line 3207 of file crackfortran.py.
determineexprtype_re_4
numpy.f2py.crackfortran.determineexprtype_re_4 = re.compile(r'\A\(.*\‍)\Z', re.I)
Definition at line 3209 of file crackfortran.py.
determineexprtype_re_5
numpy.f2py.crackfortran.determineexprtype_re_5 = re.compile(r'\A(?P<name>\w+)\s*\‍(.*?\‍)\s*\Z', re.I)
Definition at line 3210 of file crackfortran.py.
dimensionpattern
str numpy.f2py.crackfortran.dimensionpattern
Initial value:
=  re.compile(beforethisafter % (
    '', 'dimension|virtual', 'dimension|virtual', '.*'), re.I), 'dimension'
Definition at line 627 of file crackfortran.py.
dolowercase
int numpy.f2py.crackfortran.dolowercase = 1
Definition at line 174 of file crackfortran.py.
endifpattern
str numpy.f2py.crackfortran.endifpattern
Initial value:
=  re.compile(
    beforethisafter % (r'[\w]*?', endifs, endifs, '.*'), re.I), 'endif'
Definition at line 618 of file crackfortran.py.
endifs
str numpy.f2py.crackfortran.endifs
Initial value:
=  r'end\s*(if|do|where|select|while|forall|associate|' + \
         r'critical|enum|team)'
Definition at line 616 of file crackfortran.py.
endpattern
str numpy.f2py.crackfortran.endpattern
Initial value:
=  re.compile(
    beforethisafter % ('', groupends, groupends, '.*'), re.I), 'end'
Definition at line 613 of file crackfortran.py.
entrypattern
str numpy.f2py.crackfortran.entrypattern
Initial value:
=  re.compile(
    beforethisafter % ('', 'entry', 'entry', '.*'), re.I), 'entry'
Definition at line 649 of file crackfortran.py.
expectbegin
int numpy.f2py.crackfortran.expectbegin = 1
Definition at line 180 of file crackfortran.py.
externalpattern
str numpy.f2py.crackfortran.externalpattern
Initial value:
=  re.compile(
    beforethisafter % ('', 'external', 'external', '.*'), re.I), 'external'
Definition at line 629 of file crackfortran.py.
f
int numpy.f2py.crackfortran.f = 1
Definition at line 3697 of file crackfortran.py.
f2
int numpy.f2py.crackfortran.f2 = 0
Definition at line 3698 of file crackfortran.py.
f2py_version
numpy.f2py.crackfortran.f2py_version = __version__.version
Definition at line 162 of file crackfortran.py.
f2pyenhancementspattern
str numpy.f2py.crackfortran.f2pyenhancementspattern
Initial value:
=  re.compile(beforethisafter % ('', 'threadsafe|fortranname|callstatement|callprotoargument|usercode|pymethoddef',
                                                        'threadsafe|fortranname|callstatement|callprotoargument|usercode|pymethoddef', '.*'), re.I | re.S), 'f2pyenhancements'
Definition at line 662 of file crackfortran.py.
f3
int numpy.f2py.crackfortran.f3 = 0
Definition at line 3699 of file crackfortran.py.
f77modulename
numpy.f2py.crackfortran.f77modulename = ''
Definition at line 171 of file crackfortran.py.
f90modulevars
dict numpy.f2py.crackfortran.f90modulevars = {}
Definition at line 181 of file crackfortran.py.
filepositiontext
str numpy.f2py.crackfortran.filepositiontext = ''
Definition at line 182 of file crackfortran.py.
files
list numpy.f2py.crackfortran.files = []
Definition at line 3695 of file crackfortran.py.
formatpattern
str numpy.f2py.crackfortran.formatpattern
Initial value:
=  re.compile(
    beforethisafter % ('', 'format', 'format', '.*'), re.I), 'format'
Definition at line 659 of file crackfortran.py.
fortrantypes
str numpy.f2py.crackfortran.fortrantypes = r'character|logical|integer|real|complex|double\s*(precision\s*(complex|)|complex)|type(?=\s*\‍([\w\s,=(*)]*\‍))|byte'
Definition at line 591 of file crackfortran.py.
funcs
list numpy.f2py.crackfortran.funcs = []
Definition at line 3696 of file crackfortran.py.
functionpattern
str numpy.f2py.crackfortran.functionpattern
Initial value:
=  re.compile(beforethisafter % (
    r'([a-z]+[\w\s(=*+-/)]*?|)', 'function', 'function', '.*'), re.I), 'begin'
Definition at line 597 of file crackfortran.py.
getlincoef_re_1
numpy.f2py.crackfortran.getlincoef_re_1 = re.compile(r'\A\b\w+\b\Z', re.I)
Definition at line 2308 of file crackfortran.py.
gotnextfile
int numpy.f2py.crackfortran.gotnextfile = 1
Definition at line 183 of file crackfortran.py.
groupbegins77
str numpy.f2py.crackfortran.groupbegins77 = r'program|block\s*data'
Definition at line 603 of file crackfortran.py.
groupbegins90
str numpy.f2py.crackfortran.groupbegins90
Initial value:
=  groupbegins77 + \
    r'|module(?!\s*procedure)|python\s*module|(abstract|)\s*interface|' + \
    r'type(?!\s*\‍()'
Definition at line 606 of file crackfortran.py.
groupcache
numpy.f2py.crackfortran.groupcache = None
Definition at line 184 of file crackfortran.py.
groupcounter
int numpy.f2py.crackfortran.groupcounter = 0
Definition at line 185 of file crackfortran.py.
groupends
tuple numpy.f2py.crackfortran.groupends
Initial value:
=  (r'end|endprogram|endblockdata|endmodule|endpythonmodule|'
             r'endinterface|endsubroutine|endfunction')
Definition at line 611 of file crackfortran.py.
grouplist
dict numpy.f2py.crackfortran.grouplist = {groupcounter: []}
Definition at line 186 of file crackfortran.py.
groupname
str numpy.f2py.crackfortran.groupname = ''
Definition at line 187 of file crackfortran.py.
ignorecontains
int numpy.f2py.crackfortran.ignorecontains = 1
Definition at line 173 of file crackfortran.py.
implicitpattern
str numpy.f2py.crackfortran.implicitpattern
Initial value:
=  re.compile(
    beforethisafter % ('', 'implicit', 'implicit', '.*'), re.I), 'implicit'
Definition at line 625 of file crackfortran.py.
include_paths
list numpy.f2py.crackfortran.include_paths = []
Definition at line 188 of file crackfortran.py.
intentpattern
str numpy.f2py.crackfortran.intentpattern
Initial value:
=  re.compile(beforethisafter % (
    '', 'intent|depend|note|check', 'intent|depend|note|check', r'\s*\‍(.*?\‍).*'), re.I), 'intent'
Definition at line 641 of file crackfortran.py.
intrinsicpattern
str numpy.f2py.crackfortran.intrinsicpattern
Initial value:
=  re.compile(
    beforethisafter % ('', 'intrinsic', 'intrinsic', '.*'), re.I), 'intrinsic'
Definition at line 639 of file crackfortran.py.
invbadnames
dict numpy.f2py.crackfortran.invbadnames = {}
Definition at line 253 of file crackfortran.py.
kindselector
numpy.f2py.crackfortran.kindselector
Initial value:
=  re.compile(
    r'\s*(\‍(\s*(kind\s*=)?\s*(?P<kind>.*)\s*\‍)|\*\s*(?P<kind2>.*?))\s*\Z', re.I)
Definition at line 1627 of file crackfortran.py.
lenarraypattern
numpy.f2py.crackfortran.lenarraypattern
Initial value:
=  re.compile(
    r'\s*(@\‍(@\s*(?!/)\s*(?P<array>.*?)\s*@\‍)@\s*\*\s*(?P<len>.*?)|(\*\s*(?P<len2>.*?)|)\s*(@\‍(@\s*(?!/)\s*(?P<array2>.*?)\s*@\‍)@|))\s*(=\s*(?P<init>.*?)|(@\‍(@|)/\s*(?P<init2>.*?)\s*/(@\‍)@|)|)\s*\Z', re.I)
Definition at line 1635 of file crackfortran.py.
lenkindpattern
numpy.f2py.crackfortran.lenkindpattern
Initial value:
=  re.compile(
    r'\s*(kind\s*=\s*(?P<kind>.*?)\s*(@,@\s*len\s*=\s*(?P<len>.*)|)'
    r'|(len\s*=\s*|)(?P<len2>.*?)\s*(@,@\s*(kind\s*=\s*|)(?P<kind2>.*)'
    r'|(f2py_len\s*=\s*(?P<f2py_len>.*))|))\s*\Z', re.I)
Definition at line 1631 of file crackfortran.py.
moduleprocedurepattern
str numpy.f2py.crackfortran.moduleprocedurepattern
Initial value:
=  re.compile(
    beforethisafter % ('', moduleprocedures, moduleprocedures, '.*'), re.I), \
    'moduleprocedure'
Definition at line 622 of file crackfortran.py.
moduleprocedures
str numpy.f2py.crackfortran.moduleprocedures = r'module\s*procedure'
Definition at line 621 of file crackfortran.py.
multilinepattern
str numpy.f2py.crackfortran.multilinepattern
Initial value:
=  re.compile(
    r"\s*(?P<before>''')(?P<this>.*?)(?P<after>''')\s*\Z", re.S), 'multiline'
Definition at line 664 of file crackfortran.py.
nameargspattern
numpy.f2py.crackfortran.nameargspattern
Initial value:
=  re.compile(
    r'\s*(?P<name>\b[\w$]+\b)\s*(@\‍(@\s*(?P<args>[\w\s,]*)\s*@\‍)@|)\s*((result(\s*@\‍(@\s*(?P<result>\b[\w$]+\b)\s*@\‍)@|))|(bind\s*@\‍(@\s*(?P<bind>(?:(?!@\‍)@).)*)\s*@\‍)@))*\s*\Z', re.I)
Definition at line 937 of file crackfortran.py.
namepattern
numpy.f2py.crackfortran.namepattern = re.compile(r'\s*(?P<name>\b\w+\b)\s*(?P<after>.*)\s*\Z', re.I)
Definition at line 1626 of file crackfortran.py.
neededmodule
int numpy.f2py.crackfortran.neededmodule = -1
Definition at line 189 of file crackfortran.py.
onlyfuncs
list numpy.f2py.crackfortran.onlyfuncs = []
Definition at line 190 of file crackfortran.py.
operatorpattern
numpy.f2py.crackfortran.operatorpattern
Initial value:
=  re.compile(
    r'\s*(?P<scheme>(operator|assignment))'
    r'@\‍(@\s*(?P<name>[^)]+)\s*@\‍)@\s*\Z', re.I)
Definition at line 939 of file crackfortran.py.
optionalpattern
str numpy.f2py.crackfortran.optionalpattern
Initial value:
=  re.compile(
    beforethisafter % ('', 'optional', 'optional', '.*'), re.I), 'optional'
Definition at line 631 of file crackfortran.py.
parameterpattern
str numpy.f2py.crackfortran.parameterpattern
Initial value:
=  re.compile(
    beforethisafter % ('', 'parameter', 'parameter', r'\s*\‍(.*'), re.I), 'parameter'
Definition at line 643 of file crackfortran.py.
post_processing_hooks
list numpy.f2py.crackfortran.post_processing_hooks = []
Definition at line 3524 of file crackfortran.py.
postlist
numpy.f2py.crackfortran.postlist = crackfortran(files)
Definition at line 3760 of file crackfortran.py.
previous_context
numpy.f2py.crackfortran.previous_context = None
Definition at line 191 of file crackfortran.py.
privatepattern
str numpy.f2py.crackfortran.privatepattern
Initial value:
=  re.compile(
    beforethisafter % ('', 'private', 'private', '.*'), re.I), 'private'
Definition at line 637 of file crackfortran.py.
publicpattern
str numpy.f2py.crackfortran.publicpattern
Initial value:
=  re.compile(
    beforethisafter % ('', 'public', 'public', '.*'), re.I), 'public'
Definition at line 635 of file crackfortran.py.
pyf
numpy.f2py.crackfortran.pyf = crack2fortran(postlist)
Definition at line 3763 of file crackfortran.py.
pyffilename
numpy.f2py.crackfortran.pyffilename = ''
Definition at line 170 of file crackfortran.py.
quiet
int numpy.f2py.crackfortran.quiet = 0
Definition at line 167 of file crackfortran.py.
real16pattern
numpy.f2py.crackfortran.real16pattern
Initial value:
=  re.compile(
    r'([-+]?(?:\d+(?:\.\d*)?|\d*\.\d+))[dD]((?:[-+]?\d+)?)')
Definition at line 944 of file crackfortran.py.
real8pattern
numpy.f2py.crackfortran.real8pattern
Initial value:
=  re.compile(
    r'([-+]?((?:\d+(?:\.\d*)?|\d*\.\d+))[eE]((?:[-+]?\d+)?)|(\d+\.\d*))')
Definition at line 946 of file crackfortran.py.
requiredpattern
str numpy.f2py.crackfortran.requiredpattern
Initial value:
=  re.compile(
    beforethisafter % ('', 'required', 'required', '.*'), re.I), 'required'
Definition at line 633 of file crackfortran.py.
selectpattern
numpy.f2py.crackfortran.selectpattern
Initial value:
=  re.compile(
    r'\s*(?P<this>(@\‍(@.*?@\‍)@|\*[\d*]+|\*\s*@\‍(@.*?@\‍)@|))(?P<after>.*)\Z', re.I)
Definition at line 932 of file crackfortran.py.
showblocklist
int numpy.f2py.crackfortran.showblocklist = 0
Definition at line 3700 of file crackfortran.py.
skipblocksuntil
int numpy.f2py.crackfortran.skipblocksuntil = -1
Definition at line 192 of file crackfortran.py.
skipemptyends
int numpy.f2py.crackfortran.skipemptyends = 0
Definition at line 172 of file crackfortran.py.
skipfuncs
list numpy.f2py.crackfortran.skipfuncs = []
Definition at line 193 of file crackfortran.py.
skipfunctions
list numpy.f2py.crackfortran.skipfunctions = []
Definition at line 194 of file crackfortran.py.
sourcecodeform
str numpy.f2py.crackfortran.sourcecodeform = 'fix'
Definition at line 166 of file crackfortran.py.
strictf77
int numpy.f2py.crackfortran.strictf77 = 1
Definition at line 165 of file crackfortran.py.
subroutinepattern
str numpy.f2py.crackfortran.subroutinepattern
Initial value:
=  re.compile(beforethisafter % (
    r'[a-z\s]*?', 'subroutine', 'subroutine', '.*'), re.I), 'begin'
Definition at line 599 of file crackfortran.py.
tabchar
int numpy.f2py.crackfortran.tabchar = 4 * ' '
Definition at line 169 of file crackfortran.py.
typedefpattern
numpy.f2py.crackfortran.typedefpattern
Initial value:
=  re.compile(
    r'(?:,(?P<attributes>[\w(),]+))?(::)?(?P<name>\b[a-z$_][\w$]*\b)'
    r'(?:\‍((?P<params>[\w,]*)\‍))?\Z', re.I)
Definition at line 934 of file crackfortran.py.
typespattern
str numpy.f2py.crackfortran.typespattern
Initial value:
=  re.compile(
    beforethisafter % ('', fortrantypes, fortrantypes, '.*'), re.I), 'type'
Definition at line 592 of file crackfortran.py.
typespattern4implicit
numpy.f2py.crackfortran.typespattern4implicit
Initial value:
=  re.compile(beforethisafter % (
    '', fortrantypes + '|static|automatic|undefined', fortrantypes + '|static|automatic|undefined', '.*'), re.I)
Definition at line 594 of file crackfortran.py.
usepattern
str numpy.f2py.crackfortran.usepattern
Initial value:
=  re.compile(
    beforethisafter % ('', 'use', 'use', '.*'), re.I), 'use'
Definition at line 655 of file crackfortran.py.
usermodules
list numpy.f2py.crackfortran.usermodules = []
Definition at line 195 of file crackfortran.py.
verbose
int numpy.f2py.crackfortran.verbose = 1
Definition at line 168 of file crackfortran.py.
word_pattern
numpy.f2py.crackfortran.word_pattern = re.compile(r'\b[a-z][\w$]*\b', re.I)
Definition at line 2383 of file crackfortran.py.