Code Cloning Analysis: scipy.fft.tests.mock_backend._MockFunction Class Reference
scipy.fft.tests.mock_backend._MockFunction Class Reference
Public Member Functions
__init__ (self, return_value=None)
__call__ (self, *args, **kwargs)
Public Attributes
int number_calls = 0
return_value = return_value
tuple last_args = ([], {})
Detailed Description
Definition at line 3 of file mock_backend.py.
Constructor & Destructor Documentation
__init__()
scipy.fft.tests.mock_backend._MockFunction.__init__ (self, return_value = None)
Definition at line 4 of file mock_backend.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
__call__()
scipy.fft.tests.mock_backend._MockFunction.__call__ (self, * args, ** kwargs)
Definition at line 9 of file mock_backend.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), and scipy.interpolate._fitpack2.SphereBivariateSpline.ev().
Member Data Documentation
last_args
tuple scipy.fft.tests.mock_backend._MockFunction.last_args = ([], {})
Definition at line 7 of file mock_backend.py.
number_calls
int scipy.fft.tests.mock_backend._MockFunction.number_calls = 0
Definition at line 5 of file mock_backend.py.
return_value
scipy.fft.tests.mock_backend._MockFunction.return_value = return_value
Definition at line 6 of file mock_backend.py.
Referenced by sklearn.utils.tests.test_metaestimators.AvailableParameterEstimator.available_func().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/fft/tests/mock_backend.py