Code Cloning Analysis: matplotlib.hatch.Circles Class Reference
matplotlib.hatch.Circles Class Reference
Public Member Functions
__init__ (self, hatch, density)
Public Member Functions inherited from matplotlib.hatch.Shapes
__init__ (self, hatch, density)
set_vertices_and_codes (self, vertices, codes)
Public Attributes
shape_vertices = path.vertices
shape_codes = path.codes
Public Attributes inherited from matplotlib.hatch.Shapes
int num_rows = 0:
int num_shapes = 0
int num_vertices = 0
Additional Inherited Members
Static Public Attributes inherited from matplotlib.hatch.Shapes
bool filled = False
Detailed Description
Definition at line 124 of file hatch.py.
Constructor & Destructor Documentation
__init__()
matplotlib.hatch.Circles.__init__ (self, hatch, density)
Definition at line 125 of file hatch.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Data Documentation
shape_codes
matplotlib.hatch.Circles.shape_codes = path.codes
Definition at line 128 of file hatch.py.
shape_vertices
matplotlib.hatch.Circles.shape_vertices = path.vertices
Definition at line 127 of file hatch.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/hatch.py