Code Cloning Analysis: scipy.stats.tests.test_hypotests.TestBoschlooExact Class Reference
scipy.stats.tests.test_hypotests.TestBoschlooExact Class Reference
Public Member Functions
test_less (self, input_sample, expected)
test_greater (self, input_sample, expected)
test_two_sided (self, input_sample, expected)
test_raises (self)
test_row_or_col_zero (self, input_sample, expected)
test_two_sided_gt_1 (self)
test_against_fisher_exact (self, alternative)
Static Public Attributes
int ATOL = 1e-7
Detailed Description
Some tests to show that boschloo_exact() works correctly.
Definition at line 1170 of file test_hypotests.py.
Member Function Documentation
test_against_fisher_exact()
scipy.stats.tests.test_hypotests.TestBoschlooExact.test_against_fisher_exact (self, alternative)
Definition at line 1314 of file test_hypotests.py.
test_greater()
scipy.stats.tests.test_hypotests.TestBoschlooExact.test_greater (self, input_sample, expected)
The expected values have been generated by R, using a resolution
for the nuisance parameter of 1e-8 :
```R
library(Exact)
options(digits=10)
data <- matrix(c(43, 10, 40, 39), 2, 2, byrow=TRUE)
a = exact.test(data, method="Boschloo", alternative="greater",
               tsmethod="central", np.interval=TRUE, beta=1e-8)
```
Definition at line 1220 of file test_hypotests.py.
References ATOL, and scipy.stats._hypotests.boschloo_exact().
test_less()
scipy.stats.tests.test_hypotests.TestBoschlooExact.test_less (self, input_sample, expected)
The expected values have been generated by R, using a resolution
for the nuisance parameter of 1e-8 :
```R
library(Exact)
options(digits=10)
data <- matrix(c(43, 10, 40, 39), 2, 2, byrow=TRUE)
a = exact.test(data, method="Boschloo", alternative="less",
               tsmethod="central", np.interval=TRUE, beta=1e-8)
```
Definition at line 1189 of file test_hypotests.py.
References ATOL, and scipy.stats._hypotests.boschloo_exact().
test_raises()
scipy.stats.tests.test_hypotests.TestBoschlooExact.test_raises (self)
Definition at line 1264 of file test_hypotests.py.
test_row_or_col_zero()
scipy.stats.tests.test_hypotests.TestBoschlooExact.test_row_or_col_zero (self, input_sample, expected)
Definition at line 1297 of file test_hypotests.py.
test_two_sided()
scipy.stats.tests.test_hypotests.TestBoschlooExact.test_two_sided (self, input_sample, expected)
The expected values have been generated by R, using a resolution
for the nuisance parameter of 1e-8 :
```R
library(Exact)
options(digits=10)
data <- matrix(c(43, 10, 40, 39), 2, 2, byrow=TRUE)
a = exact.test(data, method="Boschloo", alternative="two.sided",
               tsmethod="central", np.interval=TRUE, beta=1e-8)
```
Definition at line 1248 of file test_hypotests.py.
References ATOL, and scipy.stats._hypotests.boschloo_exact().
test_two_sided_gt_1()
scipy.stats.tests.test_hypotests.TestBoschlooExact.test_two_sided_gt_1 (self)
Definition at line 1303 of file test_hypotests.py.
Member Data Documentation
ATOL
int scipy.stats.tests.test_hypotests.TestBoschlooExact.ATOL = 1e-7 static
Definition at line 1173 of file test_hypotests.py.
Referenced by test_greater(), test_less(), and test_two_sided().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/stats/tests/test_hypotests.py