Code Cloning Analysis: sklearn.linear_model._coordinate_descent.LassoCV Class Reference
sklearn.linear_model._coordinate_descent.LassoCV Class Reference
Public Member Functions
__init__ (self, *, eps=1e-3, n_alphas="deprecated", alphas="warn", fit_intercept=True, precompute="auto", max_iter=1000, tol=1e-4, copy_X=True, cv=None, verbose=False, n_jobs=None, positive=False, random_state=None, selection="cyclic")
fit (self, X, y, sample_weight=None, **params)
Public Member Functions inherited from sklearn.base.RegressorMixin
__sklearn_tags__ (self)
score (self, X, y, sample_weight=None)
Public Member Functions inherited from sklearn.linear_model._coordinate_descent.LinearModelCV
__init__ (self, eps=1e-3, n_alphas="deprecated", alphas="warn", fit_intercept=True, precompute="auto", max_iter=1000, tol=1e-4, copy_X=True, cv=None, verbose=False, n_jobs=None, positive=False, random_state=None, selection="cyclic")
get_metadata_routing (self)
__sklearn_tags__ (self)
Public Member Functions inherited from sklearn.base.MultiOutputMixin
__sklearn_tags__ (self)
Public Member Functions inherited from sklearn.linear_model._base.LinearModel
predict (self, X)
Public Member Functions inherited from sklearn.base.BaseEstimator
get_params (self, deep=True)
set_params (self, **params)
__sklearn_clone__ (self)
__repr__ (self, N_CHAR_MAX=700)
__getstate__ (self)
__setstate__ (self, state)
__sklearn_tags__ (self)
Public Member Functions inherited from sklearn.utils._metadata_requests._MetadataRequester
set_fit_request (self, **kwargs)
set_partial_fit_request (self, **kwargs)
set_predict_request (self, **kwargs)
set_predict_proba_request (self, **kwargs)
set_predict_log_proba_request (self, **kwargs)
set_decision_function_request (self, **kwargs)
set_score_request (self, **kwargs)
set_split_request (self, **kwargs)
set_transform_request (self, **kwargs)
set_inverse_transform_request (self, **kwargs)
__init_subclass__ (cls, **kwargs)
Protected Member Functions
_get_estimator (self)
_is_multitask (self)
Protected Member Functions inherited from sklearn.linear_model._base.LinearModel
_decision_function (self, X)
_set_intercept (self, X_offset, y_offset, X_scale)
Protected Member Functions inherited from sklearn.base.BaseEstimator
_get_param_names (cls)
_get_params_html (self, deep=True)
_validate_params (self)
Protected Member Functions inherited from sklearn.utils._repr_html.base.ReprHTMLMixin
_repr_html_ (self)
_repr_html_inner (self)
_repr_mimebundle_ (self, **kwargs)
Protected Member Functions inherited from sklearn.utils._repr_html.base._HTMLDocumentationLinkMixin
_doc_link_template (self)
_doc_link_template (self, value)
_get_doc_link (self)
Protected Member Functions inherited from sklearn.utils._metadata_requests._MetadataRequester
_build_request_for_signature (cls, router, method)
_get_default_requests (cls)
_get_metadata_request (self)
Additional Inherited Members
Static Public Member Functions inherited from sklearn.linear_model._coordinate_descent.LinearModelCV
path (X, y, **kwargs)
Public Attributes inherited from sklearn.linear_model._coordinate_descent.LinearModelCV
eps = eps
str n_alphas = n_alphas
str alphas = alphas
precompute = precompute
max_iter = max_iter
tol = tol
copy_X = copy_X
cv = cv
verbose = verbose
n_jobs = n_jobs
positive = positive
random_state = random_state
selection = selection
mse_path_ = np.squeeze(np.moveaxis(mse_paths, 2, 1))
l1_ratio_ = best_l1_ratio
alpha_ = best_alpha
alphas_ = np.asarray(alphas)
coef_ = model.coef_
dual_gap_ = model.dual_gap_
n_iter_ = model.n_iter_
Public Attributes inherited from sklearn.linear_model._base.LinearModel
fit_intercept
float intercept_ = intercept_
Protected Attributes inherited from sklearn.linear_model._coordinate_descent.LinearModelCV
int _alphas = 100
Protected Attributes inherited from sklearn.base.BaseEstimator
_parameter_constraints
Static Protected Attributes inherited from sklearn.base.RegressorMixin
str _estimator_type = "regressor"
Static Protected Attributes inherited from sklearn.base.BaseEstimator
_html_repr = estimator_html_repr
Static Protected Attributes inherited from sklearn.utils._repr_html.base._HTMLDocumentationLinkMixin
str _doc_link_module = "sklearn"
_doc_link_url_param_generator = None
Detailed Description
Lasso linear model with iterative fitting along a regularization path.
See glossary entry for :term:`cross-validation estimator`.
The best model is selected by cross-validation.
The optimization objective for Lasso is::
    (1 / (2 * n_samples)) * ||y - Xw||^2_2 + alpha * ||w||_1
Read more in the :ref:`User Guide <lasso>`.
Parameters
----------
eps : float, default=1e-3
    Length of the path. ``eps=1e-3`` means that
    ``alpha_min / alpha_max = 1e-3``.
n_alphas : int, default=100
    Number of alphas along the regularization path.
    .. deprecated:: 1.7
        `n_alphas` was deprecated in 1.7 and will be removed in 1.9. Use `alphas`
        instead.
alphas : array-like or int, default=None
    Values of alphas to test along the regularization path.
    If int, `alphas` values are generated automatically.
    If array-like, list of alpha values to use.
    .. versionchanged:: 1.7
        `alphas` accepts an integer value which removes the need to pass
        `n_alphas`.
    .. deprecated:: 1.7
        `alphas=None` was deprecated in 1.7 and will be removed in 1.9, at which
        point the default value will be set to 100.
fit_intercept : bool, default=True
    Whether to calculate the intercept for this model. If set
    to false, no intercept will be used in calculations
    (i.e. data is expected to be centered).
precompute : 'auto', bool or array-like of shape \
        (n_features, n_features), default='auto'
    Whether to use a precomputed Gram matrix to speed up
    calculations. If set to ``'auto'`` let us decide. The Gram
    matrix can also be passed as argument.
max_iter : int, default=1000
    The maximum number of iterations.
tol : float, default=1e-4
    The tolerance for the optimization: if the updates are
    smaller than ``tol``, the optimization code checks the
    dual gap for optimality and continues until it is smaller
    than ``tol``.
copy_X : bool, default=True
    If ``True``, X will be copied; else, it may be overwritten.
cv : int, cross-validation generator or iterable, default=None
    Determines the cross-validation splitting strategy.
    Possible inputs for cv are:
    - None, to use the default 5-fold cross-validation,
    - int, to specify the number of folds.
    - :term:`CV splitter`,
    - An iterable yielding (train, test) splits as arrays of indices.
    For int/None inputs, :class:`~sklearn.model_selection.KFold` is used.
    Refer :ref:`User Guide <cross_validation>` for the various
    cross-validation strategies that can be used here.
    .. versionchanged:: 0.22
        ``cv`` default value if None changed from 3-fold to 5-fold.
verbose : bool or int, default=False
    Amount of verbosity.
n_jobs : int, default=None
    Number of CPUs to use during the cross validation.
    ``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.
    ``-1`` means using all processors. See :term:`Glossary <n_jobs>`
    for more details.
positive : bool, default=False
    If positive, restrict regression coefficients to be positive.
random_state : int, RandomState instance, default=None
    The seed of the pseudo random number generator that selects a random
    feature to update. Used when ``selection`` == 'random'.
    Pass an int for reproducible output across multiple function calls.
    See :term:`Glossary <random_state>`.
selection : {'cyclic', 'random'}, default='cyclic'
    If set to 'random', a random coefficient is updated every iteration
    rather than looping over features sequentially by default. This
    (setting to 'random') often leads to significantly faster convergence
    especially when tol is higher than 1e-4.
Attributes
----------
alpha_ : float
    The amount of penalization chosen by cross validation.
coef_ : ndarray of shape (n_features,) or (n_targets, n_features)
    Parameter vector (w in the cost function formula).
intercept_ : float or ndarray of shape (n_targets,)
    Independent term in decision function.
mse_path_ : ndarray of shape (n_alphas, n_folds)
    Mean square error for the test set on each fold, varying alpha.
alphas_ : ndarray of shape (n_alphas,)
    The grid of alphas used for fitting.
dual_gap_ : float or ndarray of shape (n_targets,)
    The dual gap at the end of the optimization for the optimal alpha
    (``alpha_``).
n_iter_ : int
    Number of iterations run by the coordinate descent solver to reach
    the specified tolerance for the optimal alpha.
n_features_in_ : int
    Number of features seen during :term:`fit`.
    .. versionadded:: 0.24
feature_names_in_ : ndarray of shape (`n_features_in_`,)
    Names of features seen during :term:`fit`. Defined only when `X`
    has feature names that are all strings.
    .. versionadded:: 1.0
See Also
--------
lars_path : Compute Least Angle Regression or Lasso path using LARS
    algorithm.
lasso_path : Compute Lasso path with coordinate descent.
Lasso : The Lasso is a linear model that estimates sparse coefficients.
LassoLars : Lasso model fit with Least Angle Regression a.k.a. Lars.
LassoCV : Lasso linear model with iterative fitting along a regularization
    path.
LassoLarsCV : Cross-validated Lasso using the LARS algorithm.
Notes
-----
In `fit`, once the best parameter `alpha` is found through
cross-validation, the model is fit again using the entire training set.
To avoid unnecessary memory duplication the `X` argument of the `fit`
method should be directly passed as a Fortran-contiguous numpy array.
For an example, see :ref:`examples/linear_model/plot_lasso_model_selection.py
<sphx_glr_auto_examples_linear_model_plot_lasso_model_selection.py>`.
:class:`LassoCV` leads to different results than a hyperparameter
search using :class:`~sklearn.model_selection.GridSearchCV` with a
:class:`Lasso` model. In :class:`LassoCV`, a model for a given
penalty `alpha` is warm started using the coefficients of the
closest model (trained at the previous iteration) on the
regularization path. It tends to speed up the hyperparameter
search.
Examples
--------
>>> from sklearn.linear_model import LassoCV
>>> from sklearn.datasets import make_regression
>>> X, y = make_regression(noise=4, random_state=0)
>>> reg = LassoCV(cv=5, random_state=0).fit(X, y)
>>> reg.score(X, y)
0.9993
>>> reg.predict(X[:1,])
array([-78.4951])
Definition at line 1929 of file _coordinate_descent.py.
Constructor & Destructor Documentation
__init__()
sklearn.linear_model._coordinate_descent.LassoCV.__init__ (self, * , eps = 1e-3, n_alphas = "deprecated", alphas = "warn", fit_intercept = True, precompute = "auto", max_iter = 1000, tol = 1e-4, copy_X = True, cv = None, verbose = False, n_jobs = None, positive = False, random_state = None, selection = "cyclic")
Definition at line 2112 of file _coordinate_descent.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params().
Member Function Documentation
_get_estimator()
sklearn.linear_model._coordinate_descent.LassoCV._get_estimator (self) protected
Model to be fitted after the best alpha has been determined.
Reimplemented from sklearn.linear_model._coordinate_descent.LinearModelCV.
Definition at line 2147 of file _coordinate_descent.py.
Referenced by sklearn.multioutput._BaseChain.fit(), sklearn.multioutput.ClassifierChain.get_metadata_routing(), sklearn.multioutput.RegressorChain.get_metadata_routing(), and sklearn.multioutput._BaseChain.predict().
_is_multitask()
sklearn.linear_model._coordinate_descent.LassoCV._is_multitask (self) protected
Bool indicating if class is meant for multidimensional target.
Reimplemented from sklearn.linear_model._coordinate_descent.LinearModelCV.
Definition at line 2150 of file _coordinate_descent.py.
fit()
sklearn.linear_model._coordinate_descent.LassoCV.fit (self, X, y, sample_weight = None, ** params)
Fit Lasso model with coordinate descent.
Fit is on grid of alphas and best alpha estimated by cross-validation.
Parameters
----------
X : {array-like, sparse matrix} of shape (n_samples, n_features)
    Training data. Pass directly as Fortran-contiguous data
    to avoid unnecessary memory duplication. If y is mono-output,
    X can be sparse. Note that large sparse matrices and arrays
    requiring `int64` indices are not accepted.
y : array-like of shape (n_samples,)
    Target values.
sample_weight : float or array-like of shape (n_samples,), \
        default=None
    Sample weights used for fitting and evaluation of the weighted
    mean squared error of each cv-fold. Note that the cross validated
    MSE that is finally used to find the best model is the unweighted
    mean over the (weighted) MSEs of each test fold.
**params : dict, default=None
    Parameters to be passed to the CV splitter.
    .. versionadded:: 1.4
        Only available if `enable_metadata_routing=True`,
        which can be set by using
        ``sklearn.set_config(enable_metadata_routing=True)``.
        See :ref:`Metadata Routing User Guide <metadata_routing>` for
        more details.
Returns
-------
self : object
    Returns an instance of fitted model.
Reimplemented from sklearn.linear_model._coordinate_descent.LinearModelCV.
Definition at line 2153 of file _coordinate_descent.py.
References fit().
Referenced by fit(), sklearn.cluster._kmeans._BaseKMeans.fit_predict(), sklearn.neighbors._lof.LocalOutlierFactor.fit_predict(), sklearn.cluster._kmeans._BaseKMeans.fit_transform(), sklearn.manifold._spectral_embedding.SpectralEmbedding.fit_transform(), sklearn.neighbors._graph.KNeighborsTransformer.fit_transform(), sklearn.neighbors._graph.RadiusNeighborsTransformer.fit_transform(), sklearn.preprocessing._label.LabelBinarizer.fit_transform(), sklearn.preprocessing._label.MultiLabelBinarizer.fit_transform(), sklearn.tests.metadata_routing_common.ConsumingTransformer.fit_transform(), and sklearn.utils.tests.test_estimator_checks.SparseTransformer.fit_transform().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py