Code Cloning Analysis: pandas.core.indexes.multi Namespace Reference
pandas.core.indexes.multi Namespace Reference
Classes
class MultiIndex
class MultiIndexPyIntEngine
class MultiIndexUIntEngine
Functions
F names_compat (F meth)
int _lexsort_depth (list[np.ndarray] codes, int nlevels)
sparsify_labels (label_list, int start=0, object sentinel="")
str _get_na_rep (DtypeObj dtype)
Index maybe_droplevels (Index index, key)
np.ndarray _coerce_indexer_frozen (array_like, categories, bool copy=False)
_require_listlike (level, arr, str arrname)
Variables
_index_doc_kwargs = dict(ibase._index_doc_kwargs)
Function Documentation
_coerce_indexer_frozen()
np.ndarray pandas.core.indexes.multi._coerce_indexer_frozen (array_like, categories, bool copy = False) protected
Coerce the array-like indexer to the smallest integer dtype that can encode all
of the given categories.
Parameters
----------
array_like : array-like
categories : array-like
copy : bool
Returns
-------
np.ndarray
    Non-writeable.
Definition at line 4139 of file multi.py.
Referenced by pandas.core.indexes.multi.MultiIndex.levshape().
_get_na_rep()
str pandas.core.indexes.multi._get_na_rep (DtypeObj dtype) protected
Definition at line 4097 of file multi.py.
_lexsort_depth()
int pandas.core.indexes.multi._lexsort_depth (list[np.ndarray] codes, int nlevels) protected
Count depth (up to a maximum of `nlevels`) with which codes are lexsorted.
Definition at line 4056 of file multi.py.
_require_listlike()
pandas.core.indexes.multi._require_listlike (level, arr, str arrname) protected
Ensure that level is either None or listlike, and arr is list-of-listlike.
Definition at line 4162 of file multi.py.
Referenced by pandas.core.indexes.multi.MultiIndex.set_codes(), and pandas.core.indexes.multi.MultiIndex.set_levels().
maybe_droplevels()
Index pandas.core.indexes.multi.maybe_droplevels (Index index, key)
Attempt to drop level or levels from the given index.
Parameters
----------
index: Index
key : scalar or tuple
Returns
-------
Index
Definition at line 4106 of file multi.py.
names_compat()
F pandas.core.indexes.multi.names_compat (F meth)
A decorator to allow either `name` or `names` keyword but not both.
This makes it easier to share code with base class.
Definition at line 209 of file multi.py.
sparsify_labels()
pandas.core.indexes.multi.sparsify_labels (label_list, int start = 0, object sentinel = "")
Definition at line 4065 of file multi.py.
Variable Documentation
_index_doc_kwargs
pandas.core.indexes.multi._index_doc_kwargs = dict(ibase._index_doc_kwargs) protected
Definition at line 123 of file multi.py.