Code Cloning Analysis: matplotlib.backend_managers.ToolTriggerEvent Class Reference
matplotlib.backend_managers.ToolTriggerEvent Class Reference
Public Member Functions
__init__ (self, name, sender, tool, canvasevent=None, data=None)
Public Member Functions inherited from matplotlib.backend_managers.ToolEvent
__init__ (self, name, sender, tool, data=None)
Public Attributes
canvasevent = canvasevent
Public Attributes inherited from matplotlib.backend_managers.ToolEvent
name = name
sender = sender
tool = tool
data = data
Detailed Description
Event to inform that a tool has been triggered.
Definition at line 13 of file backend_managers.py.
Constructor & Destructor Documentation
__init__()
matplotlib.backend_managers.ToolTriggerEvent.__init__ (self, name, sender, tool, canvasevent = None, data = None)
Definition at line 15 of file backend_managers.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Data Documentation
canvasevent
matplotlib.backend_managers.ToolTriggerEvent.canvasevent = canvasevent
Definition at line 17 of file backend_managers.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/backend_managers.py