Code Cloning Analysis: scipy.stats._levy_stable Namespace Reference
scipy.stats._levy_stable Namespace Reference
Classes
class levy_stable_gen
Functions
_Phi_Z0 (alpha, t)
_Phi_Z1 (alpha, t)
_cf (Phi, t, alpha, beta)
_pdf_single_value_cf_integrate (Phi, x, alpha, beta, **kwds)
_nolan_round_difficult_input (x0, alpha, beta, zeta, x_tol_near_zeta, alpha_tol_near_one)
_pdf_single_value_piecewise_Z1 (x, alpha, beta, **kwds)
_pdf_single_value_piecewise_Z0 (x0, alpha, beta, **kwds)
_pdf_single_value_piecewise_post_rounding_Z0 (x0, alpha, beta, quad_eps)
_cdf_single_value_piecewise_Z1 (x, alpha, beta, **kwds)
_cdf_single_value_piecewise_Z0 (x0, alpha, beta, **kwds)
_cdf_single_value_piecewise_post_rounding_Z0 (x0, alpha, beta, quad_eps)
_rvs_Z1 (alpha, beta, size=None, random_state=None)
_fitstart_S0 (data)
_fitstart_S1 (data)
pdf_from_cf_with_fft (cf, h=0.01, q=9, level=3)
Variables
list __all__ = ["levy_stable", "levy_stable_gen", "pdf_from_cf_with_fft"]
float _QUAD_EPS = 1.2e-14
_cf_Z0 = partial(_cf, _Phi_Z0)
_cf_Z1 = partial(_cf, _Phi_Z1)
_pdf_single_value_cf_integrate_Z0
_pdf_single_value_cf_integrate_Z1
Cotes_table
Cotes
levy_stable = levy_stable_gen(name="levy_stable")
Function Documentation
_cdf_single_value_piecewise_post_rounding_Z0()
scipy.stats._levy_stable._cdf_single_value_piecewise_post_rounding_Z0 (x0, alpha, beta, quad_eps) protected
Calculate cdf using Nolan's methods as detailed in [NO].
Definition at line 335 of file __init__.py.
References _cdf_single_value_piecewise_post_rounding_Z0().
Referenced by _cdf_single_value_piecewise_post_rounding_Z0(), and _pdf_single_value_piecewise_post_rounding_Z0().
_cdf_single_value_piecewise_Z0()
scipy.stats._levy_stable._cdf_single_value_piecewise_Z0 (x0, alpha, beta, ** kwds) protected
Definition at line 300 of file __init__.py.
_cdf_single_value_piecewise_Z1()
scipy.stats._levy_stable._cdf_single_value_piecewise_Z1 (x, alpha, beta, ** kwds) protected
Definition at line 290 of file __init__.py.
_cf()
scipy.stats._levy_stable._cf (Phi, t, alpha, beta) protected
Characteristic function.
Definition at line 62 of file __init__.py.
Referenced by scipy.stats._levy_stable.levy_stable_gen.cdf(), and scipy.stats._levy_stable.levy_stable_gen.pdf().
_fitstart_S0()
scipy.stats._levy_stable._fitstart_S0 (data) protected
Definition at line 474 of file __init__.py.
_fitstart_S1()
scipy.stats._levy_stable._fitstart_S1 (data) protected
Definition at line 488 of file __init__.py.
_nolan_round_difficult_input()
scipy.stats._levy_stable._nolan_round_difficult_input (x0, alpha, beta, zeta, x_tol_near_zeta, alpha_tol_near_one) protected
Round difficult input values for Nolan's method in [NO].
Definition at line 131 of file __init__.py.
References _nolan_round_difficult_input(), and _pdf_single_value_piecewise_post_rounding_Z0().
Referenced by _nolan_round_difficult_input(), and _pdf_single_value_piecewise_post_rounding_Z0().
_pdf_single_value_cf_integrate()
scipy.stats._levy_stable._pdf_single_value_cf_integrate (Phi, x, alpha, beta, ** kwds) protected
To improve DNI accuracy convert characteristic function in to real
valued integral using Euler's formula, then exploit cosine symmetry to
change limits to [0, inf). Finally use cosine addition formula to split
into two parts that can be handled by weighted quad pack.
Definition at line 73 of file __init__.py.
_pdf_single_value_piecewise_post_rounding_Z0()
scipy.stats._levy_stable._pdf_single_value_piecewise_post_rounding_Z0 (x0, alpha, beta, quad_eps) protected
Calculate pdf using Nolan's methods as detailed in [NO].
Definition at line 218 of file __init__.py.
References _cdf_single_value_piecewise_post_rounding_Z0(), _nolan_round_difficult_input(), and _pdf_single_value_piecewise_post_rounding_Z0().
Referenced by _nolan_round_difficult_input(), and _pdf_single_value_piecewise_post_rounding_Z0().
_pdf_single_value_piecewise_Z0()
scipy.stats._levy_stable._pdf_single_value_piecewise_Z0 (x0, alpha, beta, ** kwds) protected
Definition at line 176 of file __init__.py.
_pdf_single_value_piecewise_Z1()
scipy.stats._levy_stable._pdf_single_value_piecewise_Z1 (x, alpha, beta, ** kwds) protected
Definition at line 166 of file __init__.py.
_Phi_Z0()
scipy.stats._levy_stable._Phi_Z0 (alpha, t) protected
Definition at line 46 of file __init__.py.
_Phi_Z1()
scipy.stats._levy_stable._Phi_Z1 (alpha, t) protected
Definition at line 54 of file __init__.py.
_rvs_Z1()
scipy.stats._levy_stable._rvs_Z1 (alpha, beta, size = None, random_state = None) protected
Simulate random variables using Nolan's methods as detailed in [NO].
Definition at line 410 of file __init__.py.
Referenced by scipy.stats._levy_stable.levy_stable_gen.rvs().
pdf_from_cf_with_fft()
scipy.stats._levy_stable.pdf_from_cf_with_fft (cf, h = 0.01, q = 9, level = 3)
Calculates pdf from characteristic function.
Uses fast Fourier transform with Newton-Cotes integration following [WZ].
Defaults to using Simpson's method (3-point Newton-Cotes integration).
Parameters
----------
cf : callable
    Single argument function from float -> complex expressing a
    characteristic function for some distribution.
h : Optional[float]
    Step size for Newton-Cotes integration. Default: 0.01
q : Optional[int]
    Use 2**q steps when peforming Newton-Cotes integration.
    The infinite integral in the inverse Fourier transform will then
    be restricted to the interval [-2**q * h / 2, 2**q * h / 2]. Setting
    the number of steps equal to a power of 2 allows the fft to be
    calculated in O(n*log(n)) time rather than O(n**2).
    Default: 9
level : Optional[int]
    Calculate integral using n-point Newton-Cotes integration for
    n = level. The 3-point Newton-Cotes formula corresponds to Simpson's
    rule. Default: 3
Returns
-------
x_l : ndarray
    Array of points x at which pdf is estimated. 2**q equally spaced
    points from -pi/h up to but not including pi/h.
density : ndarray
    Estimated values of pdf corresponding to cf at points in x_l.
References
----------
.. [WZ] Wang, Li and Zhang, Ji-Hong, 2008. Simpson's rule based FFT method
    to compute densities of stable distribution.
Definition at line 1136 of file __init__.py.
Referenced by scipy.stats._levy_stable.levy_stable_gen.cdf(), and scipy.stats._levy_stable.levy_stable_gen.pdf().
Variable Documentation
__all__
list scipy.stats._levy_stable.__all__ = ["levy_stable", "levy_stable_gen", "pdf_from_cf_with_fft"] private
Definition at line 21 of file __init__.py.
_cf_Z0
scipy.stats._levy_stable._cf_Z0 = partial(_cf, _Phi_Z0) protected
Definition at line 69 of file __init__.py.
_cf_Z1
scipy.stats._levy_stable._cf_Z1 = partial(_cf, _Phi_Z1) protected
Definition at line 70 of file __init__.py.
_pdf_single_value_cf_integrate_Z0
scipy.stats._levy_stable._pdf_single_value_cf_integrate_Z0 protected
Initial value:
=  partial(
    _pdf_single_value_cf_integrate, _Phi_Z0
)
Definition at line 123 of file __init__.py.
_pdf_single_value_cf_integrate_Z1
scipy.stats._levy_stable._pdf_single_value_cf_integrate_Z1 protected
Initial value:
=  partial(
    _pdf_single_value_cf_integrate, _Phi_Z1
)
Definition at line 126 of file __init__.py.
_QUAD_EPS
float scipy.stats._levy_stable._QUAD_EPS = 1.2e-14 protected
Definition at line 43 of file __init__.py.
Cotes
scipy.stats._levy_stable.Cotes
Initial value:
=  np.array(
    [
        np.pad(r, (0, len(Cotes_table) - 1 - len(r)), mode='constant')
        for r in Cotes_table
    ]
)
Definition at line 1128 of file __init__.py.
Cotes_table
scipy.stats._levy_stable.Cotes_table
Initial value:
=  np.array(
    [[], [1]] + [v[2] for v in _builtincoeffs.values()], dtype=object
)
Definition at line 1125 of file __init__.py.
levy_stable
scipy.stats._levy_stable.levy_stable = levy_stable_gen(name="levy_stable")
Definition at line 1199 of file __init__.py.