Code Cloning Analysis: pandas.core.missing Namespace Reference
pandas.core.missing Namespace Reference
Functions
check_value_size (value, npt.NDArray[np.bool_] mask, int length)
npt.NDArray[np.bool_] mask_missing (ArrayLike arr, values_to_mask)
Literal["pad", "backfill"] clean_fill_method (Literal["ffill", "pad", "bfill", "backfill"] method, *, Literal[False] allow_nearest=...)
Literal["pad", "backfill", "nearest"] clean_fill_method (Literal["ffill", "pad", "bfill", "backfill", "nearest"] method, *, Literal[True] allow_nearest)
Literal["pad", "backfill", "nearest"] clean_fill_method (Literal["ffill", "pad", "bfill", "backfill", "nearest"] method, *, bool allow_nearest=False)
str clean_interp_method (str method, Index index, **kwargs)
int|None find_valid_index (str how, npt.NDArray[np.bool_] is_valid)
Literal["forward", "backward", "both"] validate_limit_direction (str limit_direction)
Literal["inside", "outside"]|None validate_limit_area (str|None limit_area)
Literal["backward", "forward", "both"] infer_limit_direction (Literal["backward", "forward", "both"]|None limit_direction, str method)
Index get_interp_index (method, Index index)
None interpolate_2d_inplace (np.ndarray data, Index index, AxisInt axis, str method="linear", int|None limit=None, str limit_direction="forward", str|None limit_area=None, Any|None fill_value=None, mask=None, **kwargs)
np.ndarray _index_to_interp_indices (Index index, str method)
None _interpolate_1d (np.ndarray indices, np.ndarray yvalues, str method="linear", int|None limit=None, str limit_direction="forward", Literal["inside", "outside"]|None limit_area=None, Any|None fill_value=None, bool bounds_error=False, int|None order=None, mask=None, **kwargs)
_interpolate_scipy_wrapper (np.ndarray x, np.ndarray y, np.ndarray new_x, str method, fill_value=None, bool bounds_error=False, order=None, **kwargs)
_from_derivatives (np.ndarray xi, np.ndarray yi, np.ndarray x, order=None, int|list[int]|None der=0, bool extrapolate=False)
_akima_interpolate (np.ndarray xi, np.ndarray yi, np.ndarray x, int|list[int]|None der=0, AxisInt axis=0)
_cubicspline_interpolate (np.ndarray xi, np.ndarray yi, np.ndarray x, AxisInt axis=0, str|tuple[Any, Any] bc_type="not-a-knot", extrapolate=None)
None _interpolate_with_limit_area (np.ndarray values, Literal["pad", "backfill"] method, int|None limit, Literal["inside", "outside"] limit_area)
None pad_or_backfill_inplace (np.ndarray values, Literal["pad", "backfill"] method="pad", AxisInt axis=0, int|None limit=None, Literal["inside", "outside"]|None limit_area=None)
npt.NDArray[np.bool_] _fillna_prep (values, npt.NDArray[np.bool_]|None mask=None)
F _datetimelike_compat (F func)
tuple[np.ndarray, npt.NDArray[np.bool_]] _pad_1d (np.ndarray values, int|None limit=None, Literal["inside", "outside"]|None limit_area=None, npt.NDArray[np.bool_]|None mask=None)
tuple[np.ndarray, npt.NDArray[np.bool_]] _backfill_1d (np.ndarray values, int|None limit=None, Literal["inside", "outside"]|None limit_area=None, npt.NDArray[np.bool_]|None mask=None)
_pad_2d (np.ndarray values, int|None limit=None, Literal["inside", "outside"]|None limit_area=None, npt.NDArray[np.bool_]|None mask=None)
_backfill_2d (values, int|None limit=None, Literal["inside", "outside"]|None limit_area=None, npt.NDArray[np.bool_]|None mask=None)
None _fill_limit_area_1d (npt.NDArray[np.bool_] mask, Literal["outside", "inside"] limit_area)
None _fill_limit_area_2d (npt.NDArray[np.bool_] mask, Literal["outside", "inside"] limit_area)
get_fill_func (method, int ndim=1)
ReindexMethod|None clean_reindex_fill_method (method)
_interp_limit (npt.NDArray[np.bool_] invalid, int|None fw_limit, int|None bw_limit)
npt.NDArray[np.bool_] _rolling_window (npt.NDArray[np.bool_] a, int window)
Variables
list NP_METHODS = ["linear", "time", "index", "values"]
list SP_METHODS
dict _fill_methods = {"pad": _pad_1d, "backfill": _backfill_1d}
Detailed Description
Routines for filling missing data.
Function Documentation
_akima_interpolate()
pandas.core.missing._akima_interpolate (np.ndarray xi, np.ndarray yi, np.ndarray x, int | list[int] | None der = 0, AxisInt axis = 0) protected
Convenience function for akima interpolation.
xi and yi are arrays of values used to approximate some function f,
with ``yi = f(xi)``.
See `Akima1DInterpolator` for details.
Parameters
----------
xi : np.ndarray
    A sorted list of x-coordinates, of length N.
yi : np.ndarray
    A 1-D array of real values.  `yi`'s length along the interpolation
    axis must be equal to the length of `xi`. If N-D array, use axis
    parameter to select correct axis.
x : np.ndarray
    Of length M.
der : int, optional
    How many derivatives to extract; None for all potentially
    nonzero derivatives (that is a number equal to the number
    of points), or a list of derivatives to extract. This number
    includes the function value as 0th derivative.
axis : int, optional
    Axis in the yi array corresponding to the x-coordinate values.
See Also
--------
scipy.interpolate.Akima1DInterpolator
Returns
-------
y : scalar or array-like
    The result, of length R or length M or M by R,
Definition at line 670 of file missing.py.
_backfill_1d()
tuple[np.ndarray, npt.NDArray[np.bool_]] pandas.core.missing._backfill_1d (np.ndarray values, int | None limit = None, Literal["inside", "outside"] | None limit_area = None, npt.NDArray[np.bool_] | None mask = None) protected
Definition at line 955 of file missing.py.
_backfill_2d()
pandas.core.missing._backfill_2d (values, int | None limit = None, Literal["inside", "outside"] | None limit_area = None, npt.NDArray[np.bool_] | None mask = None) protected
Definition at line 988 of file missing.py.
_cubicspline_interpolate()
pandas.core.missing._cubicspline_interpolate (np.ndarray xi, np.ndarray yi, np.ndarray x, AxisInt axis = 0, str | tuple[Any, Any] bc_type = "not-a-knot", extrapolate = None) protected
Convenience function for cubic spline data interpolator.
See `scipy.interpolate.CubicSpline` for details.
Parameters
----------
xi : np.ndarray, shape (n,)
    1-d array containing values of the independent variable.
    Values must be real, finite and in strictly increasing order.
yi : np.ndarray
    Array containing values of the dependent variable. It can have
    arbitrary number of dimensions, but the length along ``axis``
    (see below) must match the length of ``x``. Values must be finite.
x : np.ndarray, shape (m,)
axis : int, optional
    Axis along which `y` is assumed to be varying. Meaning that for
    ``x[i]`` the corresponding values are ``np.take(y, i, axis=axis)``.
    Default is 0.
bc_type : string or 2-tuple, optional
    Boundary condition type. Two additional equations, given by the
    boundary conditions, are required to determine all coefficients of
    polynomials on each segment [2]_.
    If `bc_type` is a string, then the specified condition will be applied
    at both ends of a spline. Available conditions are:
    * 'not-a-knot' (default): The first and second segment at a curve end
      are the same polynomial. It is a good default when there is no
      information on boundary conditions.
    * 'periodic': The interpolated functions is assumed to be periodic
      of period ``x[-1] - x[0]``. The first and last value of `y` must be
      identical: ``y[0] == y[-1]``. This boundary condition will result in
      ``y'[0] == y'[-1]`` and ``y''[0] == y''[-1]``.
    * 'clamped': The first derivative at curves ends are zero. Assuming
      a 1D `y`, ``bc_type=((1, 0.0), (1, 0.0))`` is the same condition.
    * 'natural': The second derivative at curve ends are zero. Assuming
      a 1D `y`, ``bc_type=((2, 0.0), (2, 0.0))`` is the same condition.
    If `bc_type` is a 2-tuple, the first and the second value will be
    applied at the curve start and end respectively. The tuple values can
    be one of the previously mentioned strings (except 'periodic') or a
    tuple `(order, deriv_values)` allowing to specify arbitrary
    derivatives at curve ends:
    * `order`: the derivative order, 1 or 2.
    * `deriv_value`: array-like containing derivative values, shape must
      be the same as `y`, excluding ``axis`` dimension. For example, if
      `y` is 1D, then `deriv_value` must be a scalar. If `y` is 3D with
      the shape (n0, n1, n2) and axis=2, then `deriv_value` must be 2D
      and have the shape (n0, n1).
extrapolate : {bool, 'periodic', None}, optional
    If bool, determines whether to extrapolate to out-of-bounds points
    based on first and last intervals, or to return NaNs. If 'periodic',
    periodic extrapolation is used. If None (default), ``extrapolate`` is
    set to 'periodic' for ``bc_type='periodic'`` and to True otherwise.
See Also
--------
scipy.interpolate.CubicHermiteSpline
Returns
-------
y : scalar or array-like
    The result, of shape (m,)
References
----------
.. [1] `Cubic Spline Interpolation
        <https://en.wikiversity.org/wiki/Cubic_Spline_Interpolation>`_
        on Wikiversity.
.. [2] Carl de Boor, "A Practical Guide to Splines", Springer-Verlag, 1978.
Definition at line 719 of file missing.py.
_datetimelike_compat()
F pandas.core.missing._datetimelike_compat (F func) protected
Wrapper to handle datetime64 and timedelta64 dtypes.
Definition at line 913 of file missing.py.
References _fill_limit_area_1d(), and _fill_limit_area_2d().
_fill_limit_area_1d()
None pandas.core.missing._fill_limit_area_1d (npt.NDArray[np.bool_] mask, Literal["outside", "inside"] limit_area) protected
Prepare 1d mask for ffill/bfill with limit_area.
Caller is responsible for checking at least one value of mask is False.
When called, mask will no longer faithfully represent when
the corresponding are NA or not.
Parameters
----------
mask : np.ndarray[bool, ndim=1]
    Mask representing NA values when filling.
limit_area : { "outside", "inside" }
    Whether to limit filling to outside or inside the outer most non-NA value.
Definition at line 1006 of file missing.py.
Referenced by _datetimelike_compat().
_fill_limit_area_2d()
None pandas.core.missing._fill_limit_area_2d (npt.NDArray[np.bool_] mask, Literal["outside", "inside"] limit_area) protected
Prepare 2d mask for ffill/bfill with limit_area.
When called, mask will no longer faithfully represent when
the corresponding are NA or not.
Parameters
----------
mask : np.ndarray[bool, ndim=1]
    Mask representing NA values when filling.
limit_area : { "outside", "inside" }
    Whether to limit filling to outside or inside the outer most non-NA value.
Definition at line 1032 of file missing.py.
Referenced by _datetimelike_compat().
_fillna_prep()
npt.NDArray[np.bool_] pandas.core.missing._fillna_prep (values, npt.NDArray[np.bool_] | None mask = None) protected
Definition at line 902 of file missing.py.
_from_derivatives()
pandas.core.missing._from_derivatives (np.ndarray xi, np.ndarray yi, np.ndarray x, order = None, int | list[int] | None der = 0, bool extrapolate = False) protected
Convenience function for interpolate.BPoly.from_derivatives.
Construct a piecewise polynomial in the Bernstein basis, compatible
with the specified values and derivatives at breakpoints.
Parameters
----------
xi : array-like
    sorted 1D array of x-coordinates
yi : array-like or list of array-likes
    yi[i][j] is the j-th derivative known at xi[i]
order: None or int or array-like of ints. Default: None.
    Specifies the degree of local polynomials. If not None, some
    derivatives are ignored.
der : int or list
    How many derivatives to extract; None for all potentially nonzero
    derivatives (that is a number equal to the number of points), or a
    list of derivatives to extract. This number includes the function
    value as 0th derivative.
 extrapolate : bool, optional
    Whether to extrapolate to ouf-of-bounds points based on first and last
    intervals, or to return NaNs. Default: True.
See Also
--------
scipy.interpolate.BPoly.from_derivatives
Returns
-------
y : scalar or array-like
    The result, of length R or length M or M by R.
Definition at line 620 of file missing.py.
_index_to_interp_indices()
np.ndarray pandas.core.missing._index_to_interp_indices (Index index, str method) protected
Convert Index to ndarray of indices to pass to NumPy/SciPy.
Definition at line 413 of file missing.py.
Referenced by interpolate_2d_inplace().
_interp_limit()
pandas.core.missing._interp_limit (npt.NDArray[np.bool_] invalid, int | None fw_limit, int | None bw_limit) protected
Get indexers of values that won't be filled
because they exceed the limits.
Parameters
----------
invalid : np.ndarray[bool]
fw_limit : int or None
    forward limit to index
bw_limit : int or None
    backward limit to index
Returns
-------
set of indexers
Notes
-----
This is equivalent to the more readable, but slower
.. code-block:: python
    def _interp_limit(invalid, fw_limit, bw_limit):
        for x in np.where(invalid)[0]:
            if invalid[max(0, x - fw_limit):x + bw_limit + 1].all():
                yield x
Definition at line 1079 of file missing.py.
References _rolling_window().
Referenced by _interpolate_1d().
_interpolate_1d()
None pandas.core.missing._interpolate_1d (np.ndarray indices, np.ndarray yvalues, str method = "linear", int | None limit = None, str limit_direction = "forward", Literal["inside", "outside"] | None limit_area = None, Any | None fill_value = None, bool bounds_error = False, int | None order = None, mask = None, ** kwargs) protected
Logic for the 1-d interpolation.  The input
indices and yvalues will each be 1-d arrays of the same length.
Bounds_error is currently hardcoded to False since non-scipy ones don't
take it as an argument.
Notes
-----
Fills 'yvalues' in-place.
Definition at line 435 of file missing.py.
References _interp_limit(), _interpolate_scipy_wrapper(), and find_valid_index().
Referenced by interpolate_2d_inplace().
_interpolate_scipy_wrapper()
pandas.core.missing._interpolate_scipy_wrapper (np.ndarray x, np.ndarray y, np.ndarray new_x, str method, fill_value = None, bool bounds_error = False, order = None, ** kwargs) protected
Passed off to scipy.interpolate.interp1d. method is scipy's kind.
Returns an array interpolated at new_x.  Add any new methods to
the list in _clean_interp_method.
Definition at line 549 of file missing.py.
Referenced by _interpolate_1d().
_interpolate_with_limit_area()
None pandas.core.missing._interpolate_with_limit_area (np.ndarray values, Literal["pad", "backfill"] method, int | None limit, Literal["inside", "outside"] limit_area) protected
Apply interpolation and limit_area logic to values along a to-be-specified axis.
Parameters
----------
values: np.ndarray
    Input array.
method: str
    Interpolation method. Could be "bfill" or "pad"
limit: int, optional
    Index limit on interpolation.
limit_area: {'inside', 'outside'}
    Limit area for interpolation.
Notes
-----
Modifies values in-place.
Definition at line 805 of file missing.py.
References find_valid_index(), and pad_or_backfill_inplace().
_pad_1d()
tuple[np.ndarray, npt.NDArray[np.bool_]] pandas.core.missing._pad_1d (np.ndarray values, int | None limit = None, Literal["inside", "outside"] | None limit_area = None, npt.NDArray[np.bool_] | None mask = None) protected
Definition at line 941 of file missing.py.
_pad_2d()
pandas.core.missing._pad_2d (np.ndarray values, int | None limit = None, Literal["inside", "outside"] | None limit_area = None, npt.NDArray[np.bool_] | None mask = None) protected
Definition at line 969 of file missing.py.
_rolling_window()
npt.NDArray[np.bool_] pandas.core.missing._rolling_window (npt.NDArray[np.bool_] a, int window) protected
[True, True, False, True, False], 2 ->
[
    [True,  True],
    [True, False],
    [False, True],
    [True, False],
]
Definition at line 1144 of file missing.py.
Referenced by _interp_limit().
check_value_size()
pandas.core.missing.check_value_size (value, npt.NDArray[np.bool_] mask, int length)
Validate the size of the values passed to ExtensionArray.fillna.
Definition at line 51 of file missing.py.
clean_fill_method() [1/3]
Literal["pad", "backfill", "nearest"] pandas.core.missing.clean_fill_method (Literal["ffill", "pad", "bfill", "backfill", "nearest"] method, * , bool allow_nearest = False)
Definition at line 157 of file missing.py.
clean_fill_method() [2/3]
Literal["pad", "backfill", "nearest"] pandas.core.missing.clean_fill_method (Literal["ffill", "pad", "bfill", "backfill", "nearest"] method, * , Literal[True] allow_nearest)
Definition at line 149 of file missing.py.
clean_fill_method() [3/3]
Literal["pad", "backfill"] pandas.core.missing.clean_fill_method (Literal["ffill", "pad", "bfill", "backfill"] method, * , Literal[False] allow_nearest = ...)
Definition at line 140 of file missing.py.
clean_interp_method()
str pandas.core.missing.clean_interp_method (str method, Index index, ** kwargs)
Definition at line 205 of file missing.py.
clean_reindex_fill_method()
ReindexMethod | None pandas.core.missing.clean_reindex_fill_method (method)
Definition at line 1073 of file missing.py.
find_valid_index()
int | None pandas.core.missing.find_valid_index (str how, npt.NDArray[np.bool_] is_valid)
Retrieves the positional index of the first valid value.
Parameters
----------
how : {'first', 'last'}
    Use this parameter to change between the first or last valid index.
is_valid: np.ndarray
    Mask to find na_values.
Returns
-------
int or None
Definition at line 224 of file missing.py.
Referenced by _interpolate_1d(), and _interpolate_with_limit_area().
get_fill_func()
pandas.core.missing.get_fill_func (method, int ndim = 1)
Definition at line 1066 of file missing.py.
get_interp_index()
Index pandas.core.missing.get_interp_index (method, Index index)
Definition at line 312 of file missing.py.
infer_limit_direction()
Literal["backward", "forward", "both"] pandas.core.missing.infer_limit_direction (Literal["backward", "forward", "both"] | None limit_direction, str method)
Definition at line 291 of file missing.py.
interpolate_2d_inplace()
None pandas.core.missing.interpolate_2d_inplace (np.ndarray data, Index index, AxisInt axis, str method = "linear", int | None limit = None, str limit_direction = "forward", str | None limit_area = None, Any | None fill_value = None, mask = None, ** kwargs)
Column-wise application of _interpolate_1d.
Notes
-----
Alters 'data' in-place.
The signature does differ from _interpolate_1d because it only
includes what is needed for Block.interpolate.
Definition at line 343 of file missing.py.
References _index_to_interp_indices(), and _interpolate_1d().
mask_missing()
npt.NDArray[np.bool_] pandas.core.missing.mask_missing (ArrayLike arr, values_to_mask)
Return a masking array of same size/shape as arr
with entries equaling any member of values_to_mask set to True
Parameters
----------
arr : ArrayLike
values_to_mask: list, tuple, or scalar
Returns
-------
np.ndarray[bool]
Definition at line 66 of file missing.py.
pad_or_backfill_inplace()
None pandas.core.missing.pad_or_backfill_inplace (np.ndarray values, Literal["pad", "backfill"] method = "pad", AxisInt axis = 0, int | None limit = None, Literal["inside", "outside"] | None limit_area = None)
Perform an actual interpolation of values, values will be make 2-d if
needed fills inplace, returns the result.
Parameters
----------
values: np.ndarray
    Input array.
method: str, default "pad"
    Interpolation method. Could be "bfill" or "pad"
axis: 0 or 1
    Interpolation axis
limit: int, optional
    Index limit on interpolation.
limit_area: str, optional
    Limit area for interpolation. Can be "inside" or "outside"
Notes
-----
Modifies values in-place.
Definition at line 858 of file missing.py.
Referenced by _interpolate_with_limit_area().
validate_limit_area()
Literal["inside", "outside"] | None pandas.core.missing.validate_limit_area (str | None limit_area)
Definition at line 277 of file missing.py.
validate_limit_direction()
Literal["forward", "backward", "both"] pandas.core.missing.validate_limit_direction (str limit_direction)
Definition at line 262 of file missing.py.
Variable Documentation
_fill_methods
dict pandas.core.missing._fill_methods = {"pad": _pad_1d, "backfill": _backfill_1d} protected
Definition at line 1063 of file missing.py.
NP_METHODS
list pandas.core.missing.NP_METHODS = ["linear", "time", "index", "values"]
Definition at line 183 of file missing.py.
SP_METHODS
list pandas.core.missing.SP_METHODS
Initial value:
=  [
    "nearest",
    "zero",
    "slinear",
    "quadratic",
    "cubic",
    "barycentric",
    "krogh",
    "spline",
    "polynomial",
    "from_derivatives",
    "piecewise_polynomial",
    "pchip",
    "akima",
    "cubicspline",
]
Definition at line 187 of file missing.py.