Code Cloning Analysis: sklearn.feature_selection._mutual_info Namespace Reference
sklearn.feature_selection._mutual_info Namespace Reference
Functions
_compute_mi_cc (x, y, n_neighbors)
_compute_mi_cd (c, d, n_neighbors)
_compute_mi (x, y, x_discrete, y_discrete, n_neighbors=3)
_iterate_columns (X, columns=None)
_estimate_mi (X, y, *, discrete_features="auto", discrete_target=False, n_neighbors=3, copy=True, random_state=None, n_jobs=None)
mutual_info_regression (X, y, *, discrete_features="auto", n_neighbors=3, copy=True, random_state=None, n_jobs=None)
mutual_info_classif (X, y, *, discrete_features="auto", n_neighbors=3, copy=True, random_state=None, n_jobs=None)
Function Documentation
_compute_mi()
sklearn.feature_selection._mutual_info._compute_mi (x, y, x_discrete, y_discrete, n_neighbors = 3) protected
Compute mutual information between two variables.
This is a simple wrapper which selects a proper function to call based on
whether `x` and `y` are discrete or not.
Definition at line 156 of file _mutual_info.py.
References _compute_mi_cc(), and _compute_mi_cd().
_compute_mi_cc()
sklearn.feature_selection._mutual_info._compute_mi_cc (x, y, n_neighbors) protected
Compute mutual information between two continuous variables.
Parameters
----------
x, y : ndarray, shape (n_samples,)
    Samples of two continuous random variables, must have an identical
    shape.
n_neighbors : int
    Number of nearest neighbors to search for each point, see [1]_.
Returns
-------
mi : float
    Estimated mutual information in nat units. If it turned out to be
    negative it is replaced by 0.
Notes
-----
True mutual information can't be negative. If its estimate by a numerical
method is negative, it means (providing the method is adequate) that the
mutual information is close to 0 and replacing it by 0 is a reasonable
strategy.
References
----------
.. [1] A. Kraskov, H. Stogbauer and P. Grassberger, "Estimating mutual
       information". Phys. Rev. E 69, 2004.
Definition at line 20 of file _mutual_info.py.
Referenced by _compute_mi().
_compute_mi_cd()
sklearn.feature_selection._mutual_info._compute_mi_cd (c, d, n_neighbors) protected
Compute mutual information between continuous and discrete variables.
Parameters
----------
c : ndarray, shape (n_samples,)
    Samples of a continuous random variable.
d : ndarray, shape (n_samples,)
    Samples of a discrete random variable.
n_neighbors : int
    Number of nearest neighbors to search for each point, see [1]_.
Returns
-------
mi : float
    Estimated mutual information in nat units. If it turned out to be
    negative it is replaced by 0.
Notes
-----
True mutual information can't be negative. If its estimate by a numerical
method is negative, it means (providing the method is adequate) that the
mutual information is close to 0 and replacing it by 0 is a reasonable
strategy.
References
----------
.. [1] B. C. Ross "Mutual Information between Discrete and Continuous
   Data Sets". PLoS ONE 9(2), 2014.
Definition at line 83 of file _mutual_info.py.
Referenced by _compute_mi().
_estimate_mi()
sklearn.feature_selection._mutual_info._estimate_mi (X, y, * , discrete_features = "auto", discrete_target = False, n_neighbors = 3, copy = True, random_state = None, n_jobs = None) protected
Estimate mutual information between the features and the target.
Parameters
----------
X : array-like or sparse matrix, shape (n_samples, n_features)
    Feature matrix.
y : array-like of shape (n_samples,)
    Target vector.
discrete_features : {'auto', bool, array-like}, default='auto'
    If bool, then determines whether to consider all features discrete
    or continuous. If array, then it should be either a boolean mask
    with shape (n_features,) or array with indices of discrete features.
    If 'auto', it is assigned to False for dense `X` and to True for
    sparse `X`.
discrete_target : bool, default=False
    Whether to consider `y` as a discrete variable.
n_neighbors : int, default=3
    Number of neighbors to use for MI estimation for continuous variables,
    see [1]_ and [2]_. Higher values reduce variance of the estimation, but
    could introduce a bias.
copy : bool, default=True
    Whether to make a copy of the given data. If set to False, the initial
    data will be overwritten.
random_state : int, RandomState instance or None, default=None
    Determines random number generation for adding small noise to
    continuous variables in order to remove repeated values.
    Pass an int for reproducible results across multiple function calls.
    See :term:`Glossary <random_state>`.
n_jobs : int, default=None
    The number of jobs to use for computing the mutual information.
    The parallelization is done on the columns of `X`.
    ``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.
    ``-1`` means using all processors. See :term:`Glossary <n_jobs>`
    for more details.
    .. versionadded:: 1.5
Returns
-------
mi : ndarray, shape (n_features,)
    Estimated mutual information between each feature and the target in
    nat units. A negative value will be replaced by 0.
References
----------
.. [1] A. Kraskov, H. Stogbauer and P. Grassberger, "Estimating mutual
       information". Phys. Rev. E 69, 2004.
.. [2] B. C. Ross "Mutual Information between Discrete and Continuous
       Data Sets". PLoS ONE 9(2), 2014.
Definition at line 202 of file _mutual_info.py.
References _iterate_columns().
Referenced by mutual_info_classif(), and mutual_info_regression().
_iterate_columns()
sklearn.feature_selection._mutual_info._iterate_columns (X, columns = None) protected
Iterate over columns of a matrix.
Parameters
----------
X : ndarray or csc_matrix, shape (n_samples, n_features)
    Matrix over which to iterate.
columns : iterable or None, default=None
    Indices of columns to iterate over. If None, iterate over all columns.
Yields
------
x : ndarray, shape (n_samples,)
    Columns of `X` in dense format.
Definition at line 172 of file _mutual_info.py.
Referenced by _estimate_mi().
mutual_info_classif()
sklearn.feature_selection._mutual_info.mutual_info_classif (X, y, * , discrete_features = "auto", n_neighbors = 3, copy = True, random_state = None, n_jobs = None)
Estimate mutual information for a discrete target variable.
Mutual information (MI) [1]_ between two random variables is a non-negative
value, which measures the dependency between the variables. It is equal
to zero if and only if two random variables are independent, and higher
values mean higher dependency.
The function relies on nonparametric methods based on entropy estimation
from k-nearest neighbors distances as described in [2]_ and [3]_. Both
methods are based on the idea originally proposed in [4]_.
It can be used for univariate features selection, read more in the
:ref:`User Guide <univariate_feature_selection>`.
Parameters
----------
X : {array-like, sparse matrix} of shape (n_samples, n_features)
    Feature matrix.
y : array-like of shape (n_samples,)
    Target vector.
discrete_features : 'auto', bool or array-like, default='auto'
    If bool, then determines whether to consider all features discrete
    or continuous. If array, then it should be either a boolean mask
    with shape (n_features,) or array with indices of discrete features.
    If 'auto', it is assigned to False for dense `X` and to True for
    sparse `X`.
n_neighbors : int, default=3
    Number of neighbors to use for MI estimation for continuous variables,
    see [2]_ and [3]_. Higher values reduce variance of the estimation, but
    could introduce a bias.
copy : bool, default=True
    Whether to make a copy of the given data. If set to False, the initial
    data will be overwritten.
random_state : int, RandomState instance or None, default=None
    Determines random number generation for adding small noise to
    continuous variables in order to remove repeated values.
    Pass an int for reproducible results across multiple function calls.
    See :term:`Glossary <random_state>`.
n_jobs : int, default=None
    The number of jobs to use for computing the mutual information.
    The parallelization is done on the columns of `X`.
    ``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.
    ``-1`` means using all processors. See :term:`Glossary <n_jobs>`
    for more details.
    .. versionadded:: 1.5
Returns
-------
mi : ndarray, shape (n_features,)
    Estimated mutual information between each feature and the target in
    nat units.
Notes
-----
1. The term "discrete features" is used instead of naming them
   "categorical", because it describes the essence more accurately.
   For example, pixel intensities of an image are discrete features
   (but hardly categorical) and you will get better results if mark them
   as such. Also note, that treating a continuous variable as discrete and
   vice versa will usually give incorrect results, so be attentive about
   that.
2. True mutual information can't be negative. If its estimate turns out
   to be negative, it is replaced by zero.
References
----------
.. [1] `Mutual Information
       <https://en.wikipedia.org/wiki/Mutual_information>`_
       on Wikipedia.
.. [2] A. Kraskov, H. Stogbauer and P. Grassberger, "Estimating mutual
       information". Phys. Rev. E 69, 2004.
.. [3] B. C. Ross "Mutual Information between Discrete and Continuous
       Data Sets". PLoS ONE 9(2), 2014.
.. [4] L. F. Kozachenko, N. N. Leonenko, "Sample Estimate of the Entropy
       of a Random Vector:, Probl. Peredachi Inf., 23:2 (1987), 9-16
Examples
--------
>>> from sklearn.datasets import make_classification
>>> from sklearn.feature_selection import mutual_info_classif
>>> X, y = make_classification(
...     n_samples=100, n_features=10, n_informative=2, n_clusters_per_class=1,
...     shuffle=False, random_state=42
...)
>>> mutual_info_classif(X, y)
array([0.589, 0.107, 0.196, 0.0968 , 0.,
       0.   , 0.   , 0.   , 0.     , 0.])
Definition at line 465 of file _mutual_info.py.
References _estimate_mi().
mutual_info_regression()
sklearn.feature_selection._mutual_info.mutual_info_regression (X, y, * , discrete_features = "auto", n_neighbors = 3, copy = True, random_state = None, n_jobs = None)
Estimate mutual information for a continuous target variable.
Mutual information (MI) [1]_ between two random variables is a non-negative
value, which measures the dependency between the variables. It is equal
to zero if and only if two random variables are independent, and higher
values mean higher dependency.
The function relies on nonparametric methods based on entropy estimation
from k-nearest neighbors distances as described in [2]_ and [3]_. Both
methods are based on the idea originally proposed in [4]_.
It can be used for univariate features selection, read more in the
:ref:`User Guide <univariate_feature_selection>`.
Parameters
----------
X : array-like or sparse matrix, shape (n_samples, n_features)
    Feature matrix.
y : array-like of shape (n_samples,)
    Target vector.
discrete_features : {'auto', bool, array-like}, default='auto'
    If bool, then determines whether to consider all features discrete
    or continuous. If array, then it should be either a boolean mask
    with shape (n_features,) or array with indices of discrete features.
    If 'auto', it is assigned to False for dense `X` and to True for
    sparse `X`.
n_neighbors : int, default=3
    Number of neighbors to use for MI estimation for continuous variables,
    see [2]_ and [3]_. Higher values reduce variance of the estimation, but
    could introduce a bias.
copy : bool, default=True
    Whether to make a copy of the given data. If set to False, the initial
    data will be overwritten.
random_state : int, RandomState instance or None, default=None
    Determines random number generation for adding small noise to
    continuous variables in order to remove repeated values.
    Pass an int for reproducible results across multiple function calls.
    See :term:`Glossary <random_state>`.
n_jobs : int, default=None
    The number of jobs to use for computing the mutual information.
    The parallelization is done on the columns of `X`.
    ``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.
    ``-1`` means using all processors. See :term:`Glossary <n_jobs>`
    for more details.
    .. versionadded:: 1.5
Returns
-------
mi : ndarray, shape (n_features,)
    Estimated mutual information between each feature and the target in
    nat units.
Notes
-----
1. The term "discrete features" is used instead of naming them
   "categorical", because it describes the essence more accurately.
   For example, pixel intensities of an image are discrete features
   (but hardly categorical) and you will get better results if mark them
   as such. Also note, that treating a continuous variable as discrete and
   vice versa will usually give incorrect results, so be attentive about
   that.
2. True mutual information can't be negative. If its estimate turns out
   to be negative, it is replaced by zero.
References
----------
.. [1] `Mutual Information
       <https://en.wikipedia.org/wiki/Mutual_information>`_
       on Wikipedia.
.. [2] A. Kraskov, H. Stogbauer and P. Grassberger, "Estimating mutual
       information". Phys. Rev. E 69, 2004.
.. [3] B. C. Ross "Mutual Information between Discrete and Continuous
       Data Sets". PLoS ONE 9(2), 2014.
.. [4] L. F. Kozachenko, N. N. Leonenko, "Sample Estimate of the Entropy
       of a Random Vector", Probl. Peredachi Inf., 23:2 (1987), 9-16
Examples
--------
>>> from sklearn.datasets import make_regression
>>> from sklearn.feature_selection import mutual_info_regression
>>> X, y = make_regression(
...     n_samples=50, n_features=3, n_informative=1, noise=1e-4, random_state=42
...)
>>> mutual_info_regression(X, y)
array([0.117, 2.645, 0.0287])
Definition at line 337 of file _mutual_info.py.
References _estimate_mi().