Code Cloning Analysis: scipy.integrate._ivp.common.OdeSolution Class Reference
scipy.integrate._ivp.common.OdeSolution Class Reference
Public Member Functions
__init__ (self, ts, interpolants)
__call__ (self, t)
Public Attributes
n_segments = len(interpolants)
ts = ts
interpolants = interpolants
t_min = ts[0]
t_max = ts[-1]
bool ascending = True
ts_sorted = ts
Protected Member Functions
_call_single (self, t)
Detailed Description
Continuous ODE solution.
It is organized as a collection of `DenseOutput` objects which represent
local interpolants. It provides an algorithm to select a right interpolant
for each given point.
The interpolants cover the range between `t_min` and `t_max` (see
Attributes below). Evaluation outside this interval is not forbidden, but
the accuracy is not guaranteed.
When evaluating at a breakpoint (one of the values in `ts`) a segment with
the lower index is selected.
Parameters
----------
ts : array_like, shape (n_segments + 1,)
    Time instants between which local interpolants are defined. Must
    be strictly increasing or decreasing (zero segment with two points is
    also allowed).
interpolants : list of DenseOutput with n_segments elements
    Local interpolants. An i-th interpolant is assumed to be defined
    between ``ts[i]`` and ``ts[i + 1]``.
Attributes
----------
t_min, t_max : float
    Time range of the interpolation.
Definition at line 124 of file common.py.
Constructor & Destructor Documentation
__init__()
scipy.integrate._ivp.common.OdeSolution.__init__ (self, ts, interpolants)
Definition at line 153 of file common.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
__call__()
scipy.integrate._ivp.common.OdeSolution.__call__ (self, t)
Evaluate the solution.
Parameters
----------
t : float or array_like with shape (n_points,)
    Points to evaluate at.
Returns
-------
y : ndarray, shape (n_states,) or (n_states, n_points)
    Computed values. Shape depends on whether `t` is a scalar or a
    1-D array.
Definition at line 193 of file common.py.
References _call_single(), ascending, interpolants, n_segments, and ts_sorted.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), and scipy.interpolate._fitpack2.SphereBivariateSpline.ev().
_call_single()
scipy.integrate._ivp.common.OdeSolution._call_single (self, t) protected
Definition at line 179 of file common.py.
Referenced by __call__().
Member Data Documentation
ascending
bool scipy.integrate._ivp.common.OdeSolution.ascending = True
Definition at line 171 of file common.py.
Referenced by __call__().
interpolants
scipy.integrate._ivp.common.OdeSolution.interpolants = interpolants
Definition at line 167 of file common.py.
Referenced by __call__().
n_segments
scipy.integrate._ivp.common.OdeSolution.n_segments = len(interpolants)
Definition at line 161 of file common.py.
Referenced by __call__().
t_max
scipy.integrate._ivp.common.OdeSolution.t_max = ts[-1]
Definition at line 170 of file common.py.
t_min
scipy.integrate._ivp.common.OdeSolution.t_min = ts[0]
Definition at line 169 of file common.py.
ts
scipy.integrate._ivp.common.OdeSolution.ts = ts
Definition at line 166 of file common.py.
ts_sorted
scipy.integrate._ivp.common.OdeSolution.ts_sorted = ts
Definition at line 172 of file common.py.
Referenced by __call__().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/integrate/_ivp/common.py