Code Cloning Analysis: scipy.linalg.tests.test_decomp_update.BaseQRdeltas Class Reference
scipy.linalg.tests.test_decomp_update.BaseQRdeltas Class Reference
Public Member Functions
setup_method (self)
generate (self, type, mode='full')
Public Attributes
float rtol = 10.0 ** -(np.finfo(self.dtype).precision-2)
int atol = 10 * np.finfo(self.dtype).eps
Detailed Description
Definition at line 90 of file test_decomp_update.py.
Member Function Documentation
generate()
scipy.linalg.tests.test_decomp_update.BaseQRdeltas.generate (self, type, mode = 'full')
Definition at line 95 of file test_decomp_update.py.
setup_method()
scipy.linalg.tests.test_decomp_update.BaseQRdeltas.setup_method (self)
Definition at line 91 of file test_decomp_update.py.
Member Data Documentation
atol
int scipy.linalg.tests.test_decomp_update.BaseQRdeltas.atol = 10 * np.finfo(self.dtype).eps
Definition at line 93 of file test_decomp_update.py.
Referenced by scipy.optimize._differentialevolution.DifferentialEvolutionSolver.converged(), and sklearn.neighbors._kde.KernelDensity.score_samples().
rtol
float scipy.linalg.tests.test_decomp_update.BaseQRdeltas.rtol = 10.0 ** -(np.finfo(self.dtype).precision-2)
Definition at line 92 of file test_decomp_update.py.
Referenced by scipy.optimize._zeros_py.TOMS748Solver.get_status(), scipy.optimize._zeros_py.TOMS748Solver.iterate(), scipy.optimize.tests.test_zeros.TestScalarRootFinders.run_tests(), sklearn.neighbors._kde.KernelDensity.score_samples(), scipy.stats.tests.test_resampling.TestPermutationTest.test_against_spearmanr_in_R(), and scipy.stats.tests.test_resampling.TestPermutationTest.test_with_ties().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/linalg/tests/test_decomp_update.py