Code Cloning Analysis: matplotlib.spines.Spines Class Reference
matplotlib.spines.Spines Class Reference
Public Member Functions
__init__ (self, **kwargs)
from_dict (cls, d)
__getstate__ (self)
__setstate__ (self, state)
__getattr__ (self, name)
__getitem__ (self, key)
__setitem__ (self, key, value)
__delitem__ (self, key)
__iter__ (self)
__len__ (self)
Protected Attributes
_dict = kwargs
Detailed Description
The container of all `.Spine`\s in an Axes.
The interface is dict-like mapping names (e.g. 'left') to `.Spine` objects.
Additionally, it implements some pandas.Series-like features like accessing
elements by attribute::
    spines['top'].set_visible(False)
    spines.top.set_visible(False)
Multiple spines can be addressed simultaneously by passing a list::
    spines[['top', 'right']].set_visible(False)
Use an open slice to address all spines::
    spines[:].set_visible(False)
The latter two indexing methods will return a `SpinesProxy` that broadcasts all
``set_*()`` and ``set()`` calls to its members, but cannot be used for any other
operation.
Definition at line 523 of file spines.py.
Constructor & Destructor Documentation
__init__()
matplotlib.spines.Spines.__init__ (self, ** kwargs)
Definition at line 546 of file spines.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__delitem__()
matplotlib.spines.Spines.__delitem__ (self, key)
Definition at line 588 of file spines.py.
__getattr__()
matplotlib.spines.Spines.__getattr__ (self, name)
Definition at line 559 of file spines.py.
__getitem__()
matplotlib.spines.Spines.__getitem__ (self, key)
Definition at line 566 of file spines.py.
__getstate__()
matplotlib.spines.Spines.__getstate__ (self)
Definition at line 553 of file spines.py.
Referenced by numpy.ma.core.MaskedArray.__reduce__(), and numpy.ma.mrecords.MaskedRecords.__reduce__().
__iter__()
matplotlib.spines.Spines.__iter__ (self)
Definition at line 592 of file spines.py.
__len__()
matplotlib.spines.Spines.__len__ (self)
Definition at line 595 of file spines.py.
__setitem__()
matplotlib.spines.Spines.__setitem__ (self, key, value)
Definition at line 584 of file spines.py.
__setstate__()
matplotlib.spines.Spines.__setstate__ (self, state)
Definition at line 556 of file spines.py.
from_dict()
matplotlib.spines.Spines.from_dict (cls, d)
Definition at line 550 of file spines.py.
Referenced by pip._vendor.pyparsing.results.ParseResults.from_dict(), pyparsing.results.ParseResults.from_dict(), and pip._internal.models.direct_url.DirectUrl.redacted_url().
Member Data Documentation
_dict
matplotlib.spines.Spines._dict = kwargs protected
Definition at line 547 of file spines.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/spines.py