Code Cloning Analysis: sklearn.conftest Namespace Reference
sklearn.conftest Namespace Reference
Functions
raccoon_face_or_skip ()
global_dtype (request)
_fetch_fixture (f)
pytest_collection_modifyitems (config, items)
pyplot ()
pytest_generate_tests (metafunc)
pytest_configure (config)
hide_available_pandas (monkeypatch)
print_changed_only_false ()
Variables
dt_config = None
scipy_datasets_require_network = parse_version("1.10")
dict dataset_fetchers
_SKIP32_MARK
fetch_20newsgroups_fxt = _fetch_fixture(fetch_20newsgroups)
fetch_20newsgroups_vectorized_fxt = _fetch_fixture(fetch_20newsgroups_vectorized)
fetch_california_housing_fxt = _fetch_fixture(fetch_california_housing)
fetch_covtype_fxt = _fetch_fixture(fetch_covtype)
fetch_kddcup99_fxt = _fetch_fixture(fetch_kddcup99)
fetch_lfw_pairs_fxt = _fetch_fixture(fetch_lfw_pairs)
fetch_lfw_people_fxt = _fetch_fixture(fetch_lfw_people)
fetch_olivetti_faces_fxt = _fetch_fixture(fetch_olivetti_faces)
fetch_rcv1_fxt = _fetch_fixture(fetch_rcv1)
fetch_species_distributions_fxt = _fetch_fixture(fetch_species_distributions)
raccoon_face_fxt = pytest.fixture(raccoon_face_or_skip)
strict_check
Function Documentation
_fetch_fixture()
sklearn.conftest._fetch_fixture (f) protected
Fetch dataset (download if missing and requested by environment).
Definition at line 102 of file conftest.py.
References _fetch_fixture().
Referenced by _fetch_fixture().
global_dtype()
sklearn.conftest.global_dtype (request)
Definition at line 98 of file conftest.py.
hide_available_pandas()
sklearn.conftest.hide_available_pandas (monkeypatch)
Pretend pandas was not installed.
Definition at line 352 of file conftest.py.
print_changed_only_false()
sklearn.conftest.print_changed_only_false ()
Set `print_changed_only` to False for the duration of the test.
Definition at line 365 of file conftest.py.
pyplot()
sklearn.conftest.pyplot ()
Setup and teardown fixture for matplotlib.
This fixture checks if we can import matplotlib. If not, the tests will be
skipped. Otherwise, we close the figures before and after running the
functions.
Returns
-------
pyplot : module
    The ``matplotlib.pyplot`` module.
Definition at line 258 of file conftest.py.
pytest_collection_modifyitems()
sklearn.conftest.pytest_collection_modifyitems (config, items)
Called after collect is completed.
Parameters
----------
config : pytest config
items : list of collected items
Definition at line 133 of file conftest.py.
pytest_configure()
sklearn.conftest.pytest_configure (config)
Definition at line 321 of file conftest.py.
pytest_generate_tests()
sklearn.conftest.pytest_generate_tests (metafunc)
Parametrization of global_random_seed fixture
based on the SKLEARN_TESTS_GLOBAL_RANDOM_SEED environment variable.
The goal of this fixture is to prevent tests that use it to be sensitive
to a specific seed value while still being deterministic by default.
See the documentation for the SKLEARN_TESTS_GLOBAL_RANDOM_SEED
variable for instructions on how to use this fixture.
https://scikit-learn.org/dev/computing/parallelism.html#sklearn-tests-global-random-seed
Definition at line 276 of file conftest.py.
References matplotlib.use().
raccoon_face_or_skip()
sklearn.conftest.raccoon_face_or_skip ()
Definition at line 55 of file conftest.py.
Variable Documentation
_SKIP32_MARK
sklearn.conftest._SKIP32_MARK protected
Initial value:
=  pytest.mark.skipif(
    environ.get("SKLEARN_RUN_FLOAT32_TESTS", "0") != "1",
    reason="Set SKLEARN_RUN_FLOAT32_TESTS=1 to run float32 dtype tests",
)
Definition at line 90 of file conftest.py.
dataset_fetchers
dict sklearn.conftest.dataset_fetchers
Initial value:
=  {
    "fetch_20newsgroups_fxt": fetch_20newsgroups,
    "fetch_20newsgroups_vectorized_fxt": fetch_20newsgroups_vectorized,
    "fetch_california_housing_fxt": fetch_california_housing,
    "fetch_covtype_fxt": fetch_covtype,
    "fetch_kddcup99_fxt": fetch_kddcup99,
    "fetch_lfw_pairs_fxt": fetch_lfw_pairs,
    "fetch_lfw_people_fxt": fetch_lfw_people,
    "fetch_olivetti_faces_fxt": fetch_olivetti_faces,
    "fetch_rcv1_fxt": fetch_rcv1,
    "fetch_species_distributions_fxt": fetch_species_distributions,
}
Definition at line 74 of file conftest.py.
dt_config
sklearn.conftest.dt_config = None
Definition at line 44 of file conftest.py.
fetch_20newsgroups_fxt
sklearn.conftest.fetch_20newsgroups_fxt = _fetch_fixture(fetch_20newsgroups)
Definition at line 120 of file conftest.py.
fetch_20newsgroups_vectorized_fxt
sklearn.conftest.fetch_20newsgroups_vectorized_fxt = _fetch_fixture(fetch_20newsgroups_vectorized)
Definition at line 121 of file conftest.py.
fetch_california_housing_fxt
sklearn.conftest.fetch_california_housing_fxt = _fetch_fixture(fetch_california_housing)
Definition at line 122 of file conftest.py.
fetch_covtype_fxt
sklearn.conftest.fetch_covtype_fxt = _fetch_fixture(fetch_covtype)
Definition at line 123 of file conftest.py.
fetch_kddcup99_fxt
sklearn.conftest.fetch_kddcup99_fxt = _fetch_fixture(fetch_kddcup99)
Definition at line 124 of file conftest.py.
fetch_lfw_pairs_fxt
sklearn.conftest.fetch_lfw_pairs_fxt = _fetch_fixture(fetch_lfw_pairs)
Definition at line 125 of file conftest.py.
fetch_lfw_people_fxt
sklearn.conftest.fetch_lfw_people_fxt = _fetch_fixture(fetch_lfw_people)
Definition at line 126 of file conftest.py.
fetch_olivetti_faces_fxt
sklearn.conftest.fetch_olivetti_faces_fxt = _fetch_fixture(fetch_olivetti_faces)
Definition at line 127 of file conftest.py.
fetch_rcv1_fxt
sklearn.conftest.fetch_rcv1_fxt = _fetch_fixture(fetch_rcv1)
Definition at line 128 of file conftest.py.
fetch_species_distributions_fxt
sklearn.conftest.fetch_species_distributions_fxt = _fetch_fixture(fetch_species_distributions)
Definition at line 129 of file conftest.py.
raccoon_face_fxt
sklearn.conftest.raccoon_face_fxt = pytest.fixture(raccoon_face_or_skip)
Definition at line 130 of file conftest.py.
scipy_datasets_require_network
sklearn.conftest.scipy_datasets_require_network = parse_version("1.10")
Definition at line 52 of file conftest.py.
strict_check
sklearn.conftest.strict_check
Definition at line 374 of file conftest.py.