Code Cloning Analysis: pandas.plotting._core Namespace Reference
pandas.plotting._core Namespace Reference
Classes
class PlotAccessor
Functions
hist_series (Series self, by=None, ax=None, bool grid=True, int|None xlabelsize=None, float|None xrot=None, int|None ylabelsize=None, float|None yrot=None, tuple[int, int]|None figsize=None, int|Sequence[int] bins=10, str|None backend=None, bool legend=False, **kwargs)
hist_frame (DataFrame data, IndexLabel|None column=None, by=None, bool grid=True, int|None xlabelsize=None, float|None xrot=None, int|None ylabelsize=None, float|None yrot=None, ax=None, bool sharex=False, bool sharey=False, tuple[int, int]|None figsize=None, tuple[int, int]|None layout=None, int|Sequence[int] bins=10, str|None backend=None, bool legend=False, **kwargs)
boxplot (DataFrame data, str|list[str]|None column=None, str|list[str]|None by=None, Axes|None ax=None, float|str|None fontsize=None, int rot=0, bool grid=True, tuple[float, float]|None figsize=None, tuple[int, int]|None layout=None, str|None return_type=None, **kwargs)
boxplot_frame (DataFrame self, column=None, by=None, ax=None, int|None fontsize=None, int rot=0, bool grid=True, tuple[float, float]|None figsize=None, layout=None, return_type=None, backend=None, **kwargs)
boxplot_frame_groupby (DataFrameGroupBy grouped, bool subplots=True, column=None, int|None fontsize=None, int rot=0, bool grid=True, ax=None, tuple[float, float]|None figsize=None, layout=None, bool sharex=False, bool sharey=True, backend=None, **kwargs)
types.ModuleType _load_backend (str backend)
_get_plot_backend (str|None backend=None)
Variables
str _boxplot_doc
str _backend_doc
str _bar_or_line_doc
Function Documentation
_get_plot_backend()
pandas.plotting._core._get_plot_backend (str | None backend = None) protected
Return the plotting backend to use (e.g. `pandas.plotting._matplotlib`).
The plotting system of pandas uses matplotlib by default, but the idea here
is that it can also work with other third-party backends. This function
returns the module which provides a top-level `.plot` method that will
actually do the plotting. The backend is specified from a string, which
either comes from the keyword argument `backend`, or, if not specified, from
the option `pandas.options.plotting.backend`. All the rest of the code in
this file uses the backend specified there for the plotting.
The backend is imported lazily, as matplotlib is a soft dependency, and
pandas can be used without it being installed.
Notes
-----
Modifies `_backends` with imported backend as a side effect.
Definition at line 1920 of file _core.py.
References _load_backend().
Referenced by pandas.plotting._core.PlotAccessor._get_call_args(), boxplot_frame_groupby(), hist_frame(), hist_series(), and pandas.tests.plotting.test_backend.restore_backend().
_load_backend()
types.ModuleType pandas.plotting._core._load_backend (str backend) protected
Load a pandas plotting backend.
Parameters
----------
backend : str
    The identifier for the backend. Either an entrypoint item registered
    with importlib.metadata, "matplotlib", or a module name.
Returns
-------
types.ModuleType
    The imported backend.
Definition at line 1851 of file _core.py.
Referenced by _get_plot_backend().
boxplot()
pandas.plotting._core.boxplot (DataFrame data, str | list[str] | None column = None, str | list[str] | None by = None, Axes | None ax = None, float | str | None fontsize = None, int rot = 0, bool grid = True, tuple[float, float] | None figsize = None, tuple[int, int] | None layout = None, str | None return_type = None, ** kwargs)
Definition at line 487 of file _core.py.
boxplot_frame()
pandas.plotting._core.boxplot_frame (DataFrame self, column = None, by = None, ax = None, int | None fontsize = None, int rot = 0, bool grid = True, tuple[float, float] | None figsize = None, layout = None, return_type = None, backend = None, ** kwargs)
Definition at line 518 of file _core.py.
boxplot_frame_groupby()
pandas.plotting._core.boxplot_frame_groupby (DataFrameGroupBy grouped, bool subplots = True, column = None, int | None fontsize = None, int rot = 0, bool grid = True, ax = None, tuple[float, float] | None figsize = None, layout = None, bool sharex = False, bool sharey = True, backend = None, ** kwargs)
Make box plots from DataFrameGroupBy data.
Parameters
----------
grouped : Grouped DataFrame
subplots : bool
    * ``False`` - no subplots will be used
    * ``True`` - create a subplot for each group.
column : column name or list of names, or vector
    Can be any valid input to groupby.
fontsize : float or str
rot : label rotation angle
grid : Setting this to True will show the grid
ax : Matplotlib axis object, default None
figsize : A tuple (width, height) in inches
layout : tuple (optional)
    The layout of the plot: (rows, columns).
sharex : bool, default False
    Whether x-axes will be shared among subplots.
sharey : bool, default True
    Whether y-axes will be shared among subplots.
backend : str, default None
    Backend to use instead of the backend specified in the option
    ``plotting.backend``. For instance, 'matplotlib'. Alternatively, to
    specify the ``plotting.backend`` for the whole session, set
    ``pd.options.plotting.backend``.
**kwargs
    All other plotting keyword arguments to be passed to
    matplotlib's boxplot function.
Returns
-------
dict of key/value = group key/DataFrame.boxplot return value
or DataFrame.boxplot return value in case subplots=figures=False
Examples
--------
You can create boxplots for grouped data and show them as separate subplots:
.. plot::
    :context: close-figs
    >>> import itertools
    >>> tuples = [t for t in itertools.product(range(1000), range(4))]
    >>> index = pd.MultiIndex.from_tuples(tuples, names=['lvl0', 'lvl1'])
    >>> data = np.random.randn(len(index), 4)
    >>> df = pd.DataFrame(data, columns=list('ABCD'), index=index)
    >>> grouped = df.groupby(level='lvl1')
    >>> grouped.boxplot(rot=45, fontsize=12, figsize=(8, 10))  # doctest: +SKIP
The ``subplots=False`` option shows the boxplots in a single figure.
.. plot::
    :context: close-figs
    >>> grouped.boxplot(subplots=False, rot=45, fontsize=12)  # doctest: +SKIP
Definition at line 548 of file _core.py.
References _get_plot_backend().
hist_frame()
pandas.plotting._core.hist_frame (DataFrame data, IndexLabel | None column = None, by = None, bool grid = True, int | None xlabelsize = None, float | None xrot = None, int | None ylabelsize = None, float | None yrot = None, ax = None, bool sharex = False, bool sharey = False, tuple[int, int] | None figsize = None, tuple[int, int] | None layout = None, int | Sequence[int] bins = 10, str | None backend = None, bool legend = False, ** kwargs)
Make a histogram of the DataFrame's columns.
A `histogram`_ is a representation of the distribution of data.
This function calls :meth:`matplotlib.pyplot.hist`, on each series in
the DataFrame, resulting in one histogram per column.
.. _histogram: https://en.wikipedia.org/wiki/Histogram
Parameters
----------
data : DataFrame
    The pandas object holding the data.
column : str or sequence, optional
    If passed, will be used to limit data to a subset of columns.
by : object, optional
    If passed, then used to form histograms for separate groups.
grid : bool, default True
    Whether to show axis grid lines.
xlabelsize : int, default None
    If specified changes the x-axis label size.
xrot : float, default None
    Rotation of x axis labels. For example, a value of 90 displays the
    x labels rotated 90 degrees clockwise.
ylabelsize : int, default None
    If specified changes the y-axis label size.
yrot : float, default None
    Rotation of y axis labels. For example, a value of 90 displays the
    y labels rotated 90 degrees clockwise.
ax : Matplotlib axes object, default None
    The axes to plot the histogram on.
sharex : bool, default True if ax is None else False
    In case subplots=True, share x axis and set some x axis labels to
    invisible; defaults to True if ax is None otherwise False if an ax
    is passed in.
    Note that passing in both an ax and sharex=True will alter all x axis
    labels for all subplots in a figure.
sharey : bool, default False
    In case subplots=True, share y axis and set some y axis labels to
    invisible.
figsize : tuple, optional
    The size in inches of the figure to create. Uses the value in
    `matplotlib.rcParams` by default.
layout : tuple, optional
    Tuple of (rows, columns) for the layout of the histograms.
bins : int or sequence, default 10
    Number of histogram bins to be used. If an integer is given, bins + 1
    bin edges are calculated and returned. If bins is a sequence, gives
    bin edges, including left edge of first bin and right edge of last
    bin. In this case, bins is returned unmodified.
backend : str, default None
    Backend to use instead of the backend specified in the option
    ``plotting.backend``. For instance, 'matplotlib'. Alternatively, to
    specify the ``plotting.backend`` for the whole session, set
    ``pd.options.plotting.backend``.
legend : bool, default False
    Whether to show the legend.
**kwargs
    All other plotting keyword arguments to be passed to
    :meth:`matplotlib.pyplot.hist`.
Returns
-------
matplotlib.AxesSubplot or numpy.ndarray of them
See Also
--------
matplotlib.pyplot.hist : Plot a histogram using matplotlib.
Examples
--------
This example draws a histogram based on the length and width of
some animals, displayed in three bins
.. plot::
    :context: close-figs
    >>> data = {'length': [1.5, 0.5, 1.2, 0.9, 3],
    ...         'width': [0.7, 0.2, 0.15, 0.2, 1.1]}
    >>> index = ['pig', 'rabbit', 'duck', 'chicken', 'horse']
    >>> df = pd.DataFrame(data, index=index)
    >>> hist = df.hist(bins=3)
Definition at line 145 of file _core.py.
References _get_plot_backend().
hist_series()
pandas.plotting._core.hist_series (Series self, by = None, ax = None, bool grid = True, int | None xlabelsize = None, float | None xrot = None, int | None ylabelsize = None, float | None yrot = None, tuple[int, int] | None figsize = None, int | Sequence[int] bins = 10, str | None backend = None, bool legend = False, ** kwargs)
Draw histogram of the input series using matplotlib.
Parameters
----------
by : object, optional
    If passed, then used to form histograms for separate groups.
ax : matplotlib axis object
    If not passed, uses gca().
grid : bool, default True
    Whether to show axis grid lines.
xlabelsize : int, default None
    If specified changes the x-axis label size.
xrot : float, default None
    Rotation of x axis labels.
ylabelsize : int, default None
    If specified changes the y-axis label size.
yrot : float, default None
    Rotation of y axis labels.
figsize : tuple, default None
    Figure size in inches by default.
bins : int or sequence, default 10
    Number of histogram bins to be used. If an integer is given, bins + 1
    bin edges are calculated and returned. If bins is a sequence, gives
    bin edges, including left edge of first bin and right edge of last
    bin. In this case, bins is returned unmodified.
backend : str, default None
    Backend to use instead of the backend specified in the option
    ``plotting.backend``. For instance, 'matplotlib'. Alternatively, to
    specify the ``plotting.backend`` for the whole session, set
    ``pd.options.plotting.backend``.
legend : bool, default False
    Whether to show the legend.
**kwargs
    To be passed to the actual plotting function.
Returns
-------
matplotlib.AxesSubplot
    A histogram plot.
See Also
--------
matplotlib.axes.Axes.hist : Plot a histogram using matplotlib.
Examples
--------
For Series:
.. plot::
    :context: close-figs
    >>> lst = ['a', 'a', 'a', 'b', 'b', 'b']
    >>> ser = pd.Series([1, 2, 2, 4, 6, 6], index=lst)
    >>> hist = ser.hist()
For Groupby:
.. plot::
    :context: close-figs
    >>> lst = ['a', 'a', 'a', 'b', 'b', 'b']
    >>> ser = pd.Series([1, 2, 2, 4, 6, 6], index=lst)
    >>> hist = ser.groupby(level=0).hist()
Definition at line 47 of file _core.py.
References _get_plot_backend().
Variable Documentation
_backend_doc
str pandas.plotting._core._backend_doc protected
Initial value:
=  """\
backend : str, default None
    Backend to use instead of the backend specified in the option
    ``plotting.backend``. For instance, 'matplotlib'. Alternatively, to
    specify the ``plotting.backend`` for the whole session, set
    ``pd.options.plotting.backend``.
"""
Definition at line 437 of file _core.py.
_bar_or_line_doc
str pandas.plotting._core._bar_or_line_doc protected
Definition at line 446 of file _core.py.
_boxplot_doc
str pandas.plotting._core._boxplot_doc protected
Definition at line 271 of file _core.py.