Code Cloning Analysis: numpy.lib.tests.test_shape_base.TestTakeAlongAxis Class Reference
numpy.lib.tests.test_shape_base.TestTakeAlongAxis Class Reference
Public Member Functions
test_argequivalent (self)
test_invalid (self)
test_empty (self)
test_broadcast (self)
Detailed Description
Definition at line 30 of file test_shape_base.py.
Member Function Documentation
test_argequivalent()
numpy.lib.tests.test_shape_base.TestTakeAlongAxis.test_argequivalent (self)
 Test it translates from arg<func> to <func>
Definition at line 31 of file test_shape_base.py.
References numpy.lib.tests.test_shape_base._add_keepdims(), and numpy.lib.shape_base.take_along_axis().
test_broadcast()
numpy.lib.tests.test_shape_base.TestTakeAlongAxis.test_broadcast (self)
 Test that non-indexing dimensions are broadcast in both directions
Definition at line 74 of file test_shape_base.py.
References numpy.lib.shape_base.take_along_axis().
test_empty()
numpy.lib.tests.test_shape_base.TestTakeAlongAxis.test_empty (self)
 Test everything is ok with empty results, even with inserted dims
Definition at line 66 of file test_shape_base.py.
References numpy.lib.shape_base.take_along_axis().
test_invalid()
numpy.lib.tests.test_shape_base.TestTakeAlongAxis.test_invalid (self)
 Test it errors when indices has too few dimensions
Definition at line 49 of file test_shape_base.py.
References numpy.lib.shape_base.take_along_axis().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/lib/tests/test_shape_base.py