Code Cloning Analysis: joblib.test.test_hashing Namespace Reference
joblib.test.test_hashing Namespace Reference
Classes
class Klass
class KlassWithCachedMethod
Functions
unicode (s)
time_func (func, *args)
Helper functions for the tests.
relative_time (func1, func2, *args)
test_trivial_hash (obj1, obj2)
test_hash_methods ()
three_np_arrays ()
test_hash_numpy_arrays (three_np_arrays)
test_hash_numpy_dict_of_arrays (three_np_arrays)
test_numpy_datetime_array (dtype)
test_hash_numpy_noncontiguous ()
test_hash_memmap (tmpdir, coerce_mmap)
test_hash_numpy_performance ()
test_bound_methods_hash ()
test_bound_cached_methods_hash (tmpdir)
test_hash_object_dtype ()
test_numpy_scalar ()
test_dict_hash (tmpdir)
test_set_hash (tmpdir)
test_set_decimal_hash ()
test_string ()
test_numpy_dtype_pickling ()
test_hashes_stay_the_same (to_hash, expected)
test_hashes_are_different_between_c_and_fortran_contiguous_arrays ()
test_0d_array ()
test_0d_and_1d_array_hashing_is_different ()
test_hashes_stay_the_same_with_numpy_objects ()
test_hashing_pickling_error ()
test_wrong_hash_name ()
Variables
list input_list
Detailed Description
Test the hashing module.
Function Documentation
relative_time()
joblib.test.test_hashing.relative_time (func1, func2, * args)
Return the relative time between func1 and func2 applied on
*args.
Definition at line 44 of file test_hashing.py.
References time_func().
Referenced by test_hash_numpy_performance().
test_0d_and_1d_array_hashing_is_different()
joblib.test.test_hashing.test_0d_and_1d_array_hashing_is_different ()
Definition at line 433 of file test_hashing.py.
test_0d_array()
joblib.test.test_hashing.test_0d_array ()
Definition at line 428 of file test_hashing.py.
test_bound_cached_methods_hash()
joblib.test.test_hashing.test_bound_cached_methods_hash (tmpdir)
Make sure that calling the same _cached_ method on two different
instances of the same class does resolve to the same hashes.
Definition at line 250 of file test_hashing.py.
test_bound_methods_hash()
joblib.test.test_hashing.test_bound_methods_hash ()
Make sure that calling the same method on two different instances
of the same class does resolve to the same hashes.
Definition at line 241 of file test_hashing.py.
test_dict_hash()
joblib.test.test_hashing.test_dict_hash (tmpdir)
Definition at line 280 of file test_hashing.py.
test_hash_memmap()
joblib.test.test_hashing.test_hash_memmap (tmpdir, coerce_mmap)
Check that memmap and arrays hash identically if coerce_mmap is True.
Definition at line 183 of file test_hashing.py.
test_hash_methods()
joblib.test.test_hashing.test_hash_methods ()
Definition at line 119 of file test_hashing.py.
test_hash_numpy_arrays()
joblib.test.test_hashing.test_hash_numpy_arrays (three_np_arrays)
Definition at line 139 of file test_hashing.py.
test_hash_numpy_dict_of_arrays()
joblib.test.test_hashing.test_hash_numpy_dict_of_arrays (three_np_arrays)
Definition at line 150 of file test_hashing.py.
test_hash_numpy_noncontiguous()
joblib.test.test_hashing.test_hash_numpy_noncontiguous ()
Definition at line 172 of file test_hashing.py.
test_hash_numpy_performance()
joblib.test.test_hashing.test_hash_numpy_performance ()
Check the performance of hashing numpy arrays:
In [22]: a = np.random.random(1000000)
In [23]: %timeit hashlib.md5(a).hexdigest()
100 loops, best of 3: 20.7 ms per loop
In [24]: %timeit hashlib.md5(pickle.dumps(a, protocol=2)).hexdigest()
1 loops, best of 3: 73.1 ms per loop
In [25]: %timeit hashlib.md5(cPickle.dumps(a, protocol=2)).hexdigest()
10 loops, best of 3: 53.9 ms per loop
In [26]: %timeit hash(a)
100 loops, best of 3: 20.8 ms per loop
Definition at line 207 of file test_hashing.py.
References relative_time(), and time_func().
test_hash_object_dtype()
joblib.test.test_hashing.test_hash_object_dtype ()
Make sure that ndarrays with dtype `object' hash correctly.
Definition at line 262 of file test_hashing.py.
test_hashes_are_different_between_c_and_fortran_contiguous_arrays()
joblib.test.test_hashing.test_hashes_are_different_between_c_and_fortran_contiguous_arrays ()
Definition at line 418 of file test_hashing.py.
test_hashes_stay_the_same()
joblib.test.test_hashing.test_hashes_stay_the_same (to_hash, expected)
Definition at line 408 of file test_hashing.py.
test_hashes_stay_the_same_with_numpy_objects()
joblib.test.test_hashing.test_hashes_stay_the_same_with_numpy_objects ()
Definition at line 438 of file test_hashing.py.
test_hashing_pickling_error()
joblib.test.test_hashing.test_hashing_pickling_error ()
Definition at line 507 of file test_hashing.py.
test_numpy_datetime_array()
joblib.test.test_hashing.test_numpy_datetime_array (dtype)
Definition at line 163 of file test_hashing.py.
test_numpy_dtype_pickling()
joblib.test.test_hashing.test_numpy_dtype_pickling ()
Definition at line 355 of file test_hashing.py.
test_numpy_scalar()
joblib.test.test_hashing.test_numpy_scalar ()
Definition at line 272 of file test_hashing.py.
test_set_decimal_hash()
joblib.test.test_hashing.test_set_decimal_hash ()
Definition at line 336 of file test_hashing.py.
test_set_hash()
joblib.test.test_hashing.test_set_hash (tmpdir)
Definition at line 307 of file test_hashing.py.
test_string()
joblib.test.test_hashing.test_string ()
Definition at line 344 of file test_hashing.py.
test_trivial_hash()
joblib.test.test_hashing.test_trivial_hash (obj1, obj2)
Smoke test hash on various types.
Definition at line 111 of file test_hashing.py.
test_wrong_hash_name()
joblib.test.test_hashing.test_wrong_hash_name ()
Definition at line 516 of file test_hashing.py.
three_np_arrays()
joblib.test.test_hashing.three_np_arrays ()
Definition at line 130 of file test_hashing.py.
time_func()
joblib.test.test_hashing.time_func (func, * args)
Helper functions for the tests.
Time function func on *args.
Definition at line 34 of file test_hashing.py.
Referenced by relative_time(), and test_hash_numpy_performance().
unicode()
joblib.test.test_hashing.unicode (s)
Definition at line 28 of file test_hashing.py.
Variable Documentation
input_list
list joblib.test.test_hashing.input_list
Definition at line 71 of file test_hashing.py.