Code Cloning Analysis: fontTools.misc.visitor.Visitor Class Reference
fontTools.misc.visitor.Visitor Class Reference
Public Member Functions
register (celf, clazzes)
register_attr (celf, clazzes, attrs)
register_attrs (celf, clazzes_attrs)
visitObject (self, obj, *args, **kwargs)
visitAttr (self, obj, attr, value, *args, **kwargs)
visitList (self, obj, *args, **kwargs)
visitDict (self, obj, *args, **kwargs)
visitLeaf (self, obj, *args, **kwargs)
visit (self, obj, *args, **kwargs)
Static Public Attributes
bool defaultStop = False
Protected Member Functions
_register (celf, clazzes_attrs)
_visitorsFor (celf, thing, _default={})
Static Protected Attributes
dict _visitors
Detailed Description
Definition at line 7 of file visitor.py.
Member Function Documentation
_register()
fontTools.misc.visitor.Visitor._register (celf, clazzes_attrs) protected
Definition at line 18 of file visitor.py.
_visitorsFor()
fontTools.misc.visitor.Visitor._visitorsFor (celf, thing, _default = {}) protected
Definition at line 64 of file visitor.py.
Referenced by visitObject().
register()
fontTools.misc.visitor.Visitor.register (celf, clazzes)
Definition at line 43 of file visitor.py.
register_attr()
fontTools.misc.visitor.Visitor.register_attr (celf, clazzes, attrs)
Definition at line 49 of file visitor.py.
register_attrs()
fontTools.misc.visitor.Visitor.register_attrs (celf, clazzes_attrs)
Definition at line 60 of file visitor.py.
visit()
fontTools.misc.visitor.Visitor.visit (self, obj, * args, ** kwargs)
This is the main entry to the visitor. The visitor will visit object
obj.
The visitor will first determine if there is a registered (via
@register()) visit function for the type of object. If there is, it
will be called, and (visitor, obj, *args, **kwargs) will be passed to
the user visit function.
If there is no user-registered visit function, of if there is and it
returns True, or it returns None (or doesn't return anything) and
visitor.defaultStop is False (default), then the visitor will proceed
to dispatch to one of self.visitObject(), self.visitList(),
self.visitDict(), or self.visitLeaf() (any of which can be overriden in
a subclass).
Reimplemented in fontTools.ttLib.ttVisitor.TTVisitor.
Definition at line 122 of file visitor.py.
Referenced by pandas.core.computation.expr.BaseExprVisitor.visit_Assign(), pandas.core.computation.expr.BaseExprVisitor.visit_Index(), pandas.core.computation.expr.BaseExprVisitor.visit_Slice(), visitAttr(), visitDict(), and visitList().
visitAttr()
fontTools.misc.visitor.Visitor.visitAttr (self, obj, attr, value, * args, ** kwargs)
Called to visit an attribute of an object.
Reimplemented in fontTools.ttLib.ttVisitor.TTVisitor.
Definition at line 103 of file visitor.py.
References visit().
Referenced by visitObject().
visitDict()
fontTools.misc.visitor.Visitor.visitDict (self, obj, * args, ** kwargs)
Called to visit any value that is a dictionary.
Definition at line 112 of file visitor.py.
References visit().
visitLeaf()
fontTools.misc.visitor.Visitor.visitLeaf (self, obj, * args, ** kwargs)
Called to visit any value that is not an object, list,
or dictionary.
Definition at line 117 of file visitor.py.
visitList()
fontTools.misc.visitor.Visitor.visitList (self, obj, * args, ** kwargs)
Called to visit any value that is a list.
Definition at line 107 of file visitor.py.
References visit().
visitObject()
fontTools.misc.visitor.Visitor.visitObject (self, obj, * args, ** kwargs)
Called to visit an object. This function loops over all non-private
attributes of the objects and calls any user-registered (via
@register_attr() or @register_attrs()) visit() functions.
If there is no user-registered visit function, of if there is and it
returns True, or it returns None (or doesn't return anything) and
visitor.defaultStop is False (default), then the visitor will proceed
to call self.visitAttr()
Definition at line 79 of file visitor.py.
References _visitorsFor(), defaultStop, and visitAttr().
Member Data Documentation
_visitors
dict fontTools.misc.visitor.Visitor._visitors static protected
Initial value:
=  {
        # By default we skip visiting weak references to avoid recursion
        # issues. Users can override this by registering a visit
        # function for weakref.ProxyType.
        weakref.ProxyType: {None: lambda self, obj, *args, **kwargs: False}
    }
Definition at line 10 of file visitor.py.
defaultStop
bool fontTools.misc.visitor.Visitor.defaultStop = False static
Definition at line 8 of file visitor.py.
Referenced by visitObject().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/misc/visitor.py