Code Cloning Analysis: matplotlib.patheffects Namespace Reference
matplotlib.patheffects Namespace Reference
Classes
class AbstractPathEffect
class Normal
class PathEffectRenderer
class PathPatchEffect
class SimpleLineShadow
class SimplePatchShadow
class Stroke
class TickedStroke
Functions
_subclass_with_normal (effect_class)
Variables
withStroke = _subclass_with_normal(effect_class=Stroke)
withSimplePatchShadow = _subclass_with_normal(effect_class=SimplePatchShadow)
withTickedStroke = _subclass_with_normal(effect_class=TickedStroke)
Detailed Description
Defines classes for path effects. The path effects are supported in `.Text`,
`.Line2D` and `.Patch`.
.. seealso::
   :ref:`patheffects_guide`
Function Documentation
_subclass_with_normal()
matplotlib.patheffects._subclass_with_normal (effect_class) protected
Create a PathEffect class combining *effect_class* and a normal draw.
Definition at line 163 of file patheffects.py.
Referenced by matplotlib.patheffects.SimplePatchShadow.draw_path(), matplotlib.patheffects.Stroke.draw_path(), and matplotlib.patheffects.TickedStroke.draw_path().
Variable Documentation
withSimplePatchShadow
matplotlib.patheffects.withSimplePatchShadow = _subclass_with_normal(effect_class=SimplePatchShadow)
Definition at line 283 of file patheffects.py.
withStroke
matplotlib.patheffects.withStroke = _subclass_with_normal(effect_class=Stroke)
Definition at line 215 of file patheffects.py.
withTickedStroke
matplotlib.patheffects.withTickedStroke = _subclass_with_normal(effect_class=TickedStroke)
Definition at line 511 of file patheffects.py.