Code Cloning Analysis: matplotlib.layout_engine.LayoutEngine Class Reference
matplotlib.layout_engine.LayoutEngine Class Reference
Public Member Functions
__init__ (self, **kwargs)
set (self, **kwargs)
colorbar_gridspec (self)
adjust_compatible (self)
get (self)
execute (self, fig)
Protected Attributes
dict _params = {}
Static Protected Attributes
_adjust_compatible = None
_colorbar_gridspec = None
Detailed Description
Base class for Matplotlib layout engines.
A layout engine can be passed to a figure at instantiation or at any time
with `~.figure.Figure.set_layout_engine`.  Once attached to a figure, the
layout engine ``execute`` function is called at draw time by
`~.figure.Figure.draw`, providing a special draw-time hook.
.. note::
   However, note that layout engines affect the creation of colorbars, so
   `~.figure.Figure.set_layout_engine` should be called before any
   colorbars are created.
Currently, there are two properties of `LayoutEngine` classes that are
consulted while manipulating the figure:
- ``engine.colorbar_gridspec`` tells `.Figure.colorbar` whether to make the
   axes using the gridspec method (see `.colorbar.make_axes_gridspec`) or
   not (see `.colorbar.make_axes`);
- ``engine.adjust_compatible`` stops `.Figure.subplots_adjust` from being
    run if it is not compatible with the layout engine.
To implement a custom `LayoutEngine`:
1. override ``_adjust_compatible`` and ``_colorbar_gridspec``
2. override `LayoutEngine.set` to update *self._params*
3. override `LayoutEngine.execute` with your implementation
Definition at line 32 of file layout_engine.py.
Constructor & Destructor Documentation
__init__()
matplotlib.layout_engine.LayoutEngine.__init__ (self, ** kwargs)
Definition at line 67 of file layout_engine.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
adjust_compatible()
matplotlib.layout_engine.LayoutEngine.adjust_compatible (self)
Return a boolean if the layout engine is compatible with
`~.Figure.subplots_adjust`.
Definition at line 88 of file layout_engine.py.
References _adjust_compatible.
colorbar_gridspec()
matplotlib.layout_engine.LayoutEngine.colorbar_gridspec (self)
Return a boolean if the layout engine creates colorbars using a
gridspec.
Definition at line 78 of file layout_engine.py.
References _colorbar_gridspec.
execute()
matplotlib.layout_engine.LayoutEngine.execute (self, fig)
Execute the layout on the figure given by *fig*.
Reimplemented in matplotlib.layout_engine.ConstrainedLayoutEngine, matplotlib.layout_engine.PlaceHolderLayoutEngine, and matplotlib.layout_engine.TightLayoutEngine.
Definition at line 103 of file layout_engine.py.
Referenced by pandas.io.sql.SQLiteDatabase._query_iterator(), pandas.io.sql.SQLDatabase.read_query(), and pandas.io.sql.SQLiteDatabase.to_sql().
get()
matplotlib.layout_engine.LayoutEngine.get (self)
Return copy of the parameters for the layout engine.
Definition at line 97 of file layout_engine.py.
References _params.
Referenced by pandas.io.pytables.HDFStore.__getattr__(), scipy._lib._docscrape.NumpyDocString._parse_summary(), pip._vendor.distlib.metadata.LegacyMetadata.check(), pandas.core.series.Series.combine(), pip._vendor.rich.layout.Layout.get(), fontTools.misc.macRes.ResourceReader.getNamedResource(), fontTools.misc.macRes.ResourceReader.getNames(), pandas.io.pytables.HDFStore.root(), and pip._vendor.distlib.metadata.LegacyMetadata.write_file().
set()
matplotlib.layout_engine.LayoutEngine.set (self, ** kwargs)
Set the parameters for the layout engine.
Reimplemented in matplotlib.layout_engine.ConstrainedLayoutEngine, and matplotlib.layout_engine.TightLayoutEngine.
Definition at line 71 of file layout_engine.py.
Referenced by matplotlib.contour.ContourSet.__init__(), matplotlib.layout_engine.ConstrainedLayoutEngine.__init__(), matplotlib.layout_engine.TightLayoutEngine.__init__(), matplotlib.transforms.TransformWrapper.__init__(), pip._vendor.requests.cookies.RequestsCookieJar.__setitem__(), matplotlib.axes._base._AxesBase._set_view(), mplot3d.axes3d.Axes3D._set_view(), matplotlib.axes._axes.Axes.pie(), pip._vendor.distlib.metadata.LegacyMetadata.read_file(), matplotlib.layout_engine.ConstrainedLayoutEngine.set(), matplotlib.layout_engine.TightLayoutEngine.set(), numpy.core.tests.test_simd._SIMD_ALL.test_lut(), and pip._vendor.distlib.metadata.LegacyMetadata.update().
Member Data Documentation
_adjust_compatible
matplotlib.layout_engine.LayoutEngine._adjust_compatible = None static protected
Definition at line 64 of file layout_engine.py.
Referenced by adjust_compatible().
_colorbar_gridspec
matplotlib.layout_engine.LayoutEngine._colorbar_gridspec = None static protected
Definition at line 65 of file layout_engine.py.
Referenced by colorbar_gridspec().
_params
matplotlib.layout_engine.LayoutEngine._params = {} protected
Definition at line 69 of file layout_engine.py.
Referenced by matplotlib.layout_engine.TightLayoutEngine.__init__(), matplotlib.layout_engine.ConstrainedLayoutEngine.execute(), matplotlib.layout_engine.TightLayoutEngine.execute(), get(), matplotlib.layout_engine.ConstrainedLayoutEngine.set(), and matplotlib.layout_engine.TightLayoutEngine.set().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/layout_engine.py