Code Cloning Analysis: joblib.hashing.NumpyHasher Class Reference
joblib.hashing.NumpyHasher Class Reference
Public Member Functions
__init__ (self, hash_name="md5", coerce_mmap=False)
save (self, obj)
Public Member Functions inherited from joblib.hashing.Hasher
__init__ (self, hash_name="md5")
hash (self, obj, return_digest=True)
memoize (self, obj)
save_global (self, obj, name=None, pack=struct.pack)
save_set (self, set_items)
Public Attributes
coerce_mmap = coerce_mmap
np = np
Public Attributes inherited from joblib.hashing.Hasher
stream = io.BytesIO()
Protected Attributes
_getbuffer = np.getbuffer
Protected Attributes inherited from joblib.hashing.Hasher
_hash = hashlib.new(hash_name, usedforsecurity=False)
Additional Inherited Members
Static Public Attributes inherited from joblib.hashing.Hasher
dispatch = Pickler.dispatch.copy()
Protected Member Functions inherited from joblib.hashing.Hasher
_batch_setitems (self, items, *args)
Detailed Description
Special case the hasher for when numpy is loaded.
Definition at line 158 of file hashing.py.
Constructor & Destructor Documentation
__init__()
joblib.hashing.NumpyHasher.__init__ (self, hash_name = "md5", coerce_mmap = False)
Parameters
----------
hash_name: string
    The hash algorithm to be used
coerce_mmap: boolean
    Make no difference between np.memmap and np.ndarray
    objects.
Definition at line 161 of file hashing.py.
References _getbuffer, coerce_mmap, and np.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
save()
joblib.hashing.NumpyHasher.save (self, obj)
Subclass the save method, to hash ndarray subclass, rather
than pickling them. Off course, this is a total abuse of
the Pickler class.
Reimplemented from joblib.hashing.Hasher.
Definition at line 182 of file hashing.py.
References _getbuffer, joblib.hashing.Hasher._hash, coerce_mmap, and np.
Referenced by PIL.Image.Image._repr_image(), PIL.Image.Image.close(), joblib.externals.cloudpickle.cloudpickle.Pickler.reducer_override(), matplotlib.animation.Animation.to_html5_video(), and matplotlib.animation.Animation.to_jshtml().
Member Data Documentation
_getbuffer
joblib.hashing.NumpyHasher._getbuffer = np.getbuffer protected
Definition at line 178 of file hashing.py.
Referenced by __init__(), and save().
coerce_mmap
joblib.hashing.NumpyHasher.coerce_mmap = coerce_mmap
Definition at line 171 of file hashing.py.
Referenced by __init__(), and save().
np
joblib.hashing.NumpyHasher.np = np
Definition at line 176 of file hashing.py.
Referenced by __init__(), joblib.numpy_pickle_compat.ZipNumpyUnpickler.__init__(), joblib.numpy_pickle.NumpyUnpickler.load_build(), joblib.numpy_pickle_compat.ZipNumpyUnpickler.load_build(), save(), and joblib.numpy_pickle.NumpyPickler.save().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/joblib/hashing.py