Code Cloning Analysis: scipy.signal.tests.test_peak_finding.TestPeakWidths Class Reference
scipy.signal.tests.test_peak_finding.TestPeakWidths Class Reference
Public Member Functions
test_empty (self)
test_basic (self)
test_non_contiguous (self)
test_exceptions (self)
test_warnings (self)
test_mismatching_prominence_data (self)
test_intersection_rules (self)
Detailed Description
Definition at line 438 of file test_peak_finding.py.
Member Function Documentation
test_basic()
scipy.signal.tests.test_peak_finding.TestPeakWidths.test_basic (self)
Test a simple use case with easy to verify results at different relative
heights.
Definition at line 456 of file test_peak_finding.py.
References scipy.signal._peak_finding.peak_widths().
test_empty()
scipy.signal.tests.test_peak_finding.TestPeakWidths.test_empty (self)
Test if an empty array is returned if no peaks are provided.
Definition at line 440 of file test_peak_finding.py.
References scipy.signal._peak_finding.peak_widths().
test_exceptions()
scipy.signal.tests.test_peak_finding.TestPeakWidths.test_exceptions (self)
Verify that argument validation works as intended.
Definition at line 488 of file test_peak_finding.py.
References scipy.signal._peak_finding.peak_widths().
test_intersection_rules()
scipy.signal.tests.test_peak_finding.TestPeakWidths.test_intersection_rules (self)
Test if x == eval_height counts as an intersection.
Definition at line 563 of file test_peak_finding.py.
References scipy.signal._peak_finding.peak_widths().
test_mismatching_prominence_data()
scipy.signal.tests.test_peak_finding.TestPeakWidths.test_mismatching_prominence_data (self)
Test with mismatching peak and / or prominence data.
Definition at line 537 of file test_peak_finding.py.
References scipy.signal._peak_finding.peak_widths().
test_non_contiguous()
scipy.signal.tests.test_peak_finding.TestPeakWidths.test_non_contiguous (self)
Test with non-C-contiguous input arrays.
Definition at line 479 of file test_peak_finding.py.
References scipy.signal._peak_finding.peak_widths().
test_warnings()
scipy.signal.tests.test_peak_finding.TestPeakWidths.test_warnings (self)
Verify that appropriate warnings are raised.
Definition at line 520 of file test_peak_finding.py.
References scipy.signal._peak_finding.peak_widths().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/signal/tests/test_peak_finding.py