Code Cloning Analysis: pandas.tests.io.test_stata.TestStata Class Reference
pandas.tests.io.test_stata.TestStata Class Reference
Public Member Functions
read_dta (self, file)
read_csv (self, file)
test_read_empty_dta (self, version)
test_read_empty_dta_with_dtypes (self, version)
test_read_index_col_none (self, version)
test_read_dta1 (self, file, datapath)
test_read_dta2 (self, datapath)
test_read_dta3 (self, file, datapath)
test_read_dta4 (self, file, datapath)
test_read_dta12 (self, datapath)
test_read_dta18 (self, datapath)
test_read_write_dta5 (self)
test_write_dta6 (self, datapath)
test_read_write_dta10 (self, version, using_infer_string)
test_stata_doc_examples (self)
test_write_preserves_original (self)
test_encoding (self, version, datapath)
test_read_write_dta11 (self)
test_read_write_dta12 (self, version)
test_read_write_dta13 (self)
test_read_write_reread_dta14 (self, file, parsed_114, version, datapath)
test_read_write_reread_dta15 (self, file, datapath)
test_timestamp_and_label (self, version)
test_invalid_timestamp (self, version)
test_numeric_column_names (self)
test_nan_to_missing_value (self, version)
test_no_index (self)
test_string_no_dates (self)
test_large_value_conversion (self)
test_dates_invalid_column (self)
test_105 (self, datapath)
test_value_labels_old_format (self, datapath)
test_date_export_formats (self)
test_write_missing_strings (self)
test_bool_uint (self, byteorder, version)
test_variable_labels (self, datapath)
test_minimal_size_col (self)
test_excessively_long_string (self)
test_missing_value_generator (self)
test_missing_value_conversion (self, file, datapath)
test_big_dates (self, datapath)
test_dtype_conversion (self, datapath)
test_drop_column (self, datapath)
test_categorical_writing (self, version)
test_categorical_warnings_and_errors (self)
test_categorical_with_stata_missing_values (self, version)
test_categorical_order (self, file, datapath)
test_categorical_sorting (self, file, datapath)
test_categorical_ordering (self, file, datapath)
test_read_chunks_117 (self, file, chunksize, convert_categoricals, convert_dates, datapath)
test_iterator (self, datapath)
test_read_chunks_115 (self, file, chunksize, convert_categoricals, convert_dates, datapath)
test_read_chunks_columns (self, datapath)
test_write_variable_labels (self, version, mixed_frame)
test_invalid_variable_labels (self, version, mixed_frame)
test_invalid_variable_label_encoding (self, version, mixed_frame)
test_write_variable_label_errors (self, mixed_frame)
test_default_date_conversion (self)
test_unsupported_type (self)
test_unsupported_datetype (self)
test_repeated_column_labels (self, datapath)
test_stata_111 (self, datapath)
test_out_of_range_double (self)
test_out_of_range_float (self)
test_inf (self, infval)
test_path_pathlib (self)
test_pickle_path_localpath (self)
test_value_labels_iterator (self, write_index)
test_set_index (self)
test_date_parsing_ignores_format_details (self, column, datapath)
test_writer_117 (self, using_infer_string)
test_convert_strl_name_swap (self)
test_invalid_date_conversion (self)
test_nonfile_writing (self, version)
test_gzip_writing (self)
test_unicode_dta_118 (self, datapath)
test_mixed_string_strl (self, using_infer_string)
test_all_none_exception (self, version)
test_invalid_file_not_written (self, version)
test_strl_latin1 (self)
test_encoding_latin1_118 (self, datapath)
test_stata_119 (self, datapath)
test_utf8_writer (self, version)
test_writer_118_exceptions (self)
test_read_write_ea_dtypes (self, dtype_backend)
Static Protected Member Functions
DataFrame _convert_categorical (DataFrame from_frame)
Detailed Description
Definition at line 57 of file test_stata.py.
Member Function Documentation
_convert_categorical()
DataFrame pandas.tests.io.test_stata.TestStata._convert_categorical (DataFrame from_frame) static protected
Emulate the categorical casting behavior we expect from roundtripping.
Definition at line 1208 of file test_stata.py.
References _convert_categorical(), and read_dta().
Referenced by _convert_categorical().
read_csv()
pandas.tests.io.test_stata.TestStata.read_csv (self, file)
Definition at line 62 of file test_stata.py.
read_dta()
pandas.tests.io.test_stata.TestStata.read_dta (self, file)
Definition at line 58 of file test_stata.py.
Referenced by _convert_categorical().
test_105()
pandas.tests.io.test_stata.TestStata.test_105 (self, datapath)
Definition at line 648 of file test_stata.py.
test_all_none_exception()
pandas.tests.io.test_stata.TestStata.test_all_none_exception (self, version)
Definition at line 1808 of file test_stata.py.
test_big_dates()
pandas.tests.io.test_stata.TestStata.test_big_dates (self, datapath)
Definition at line 845 of file test_stata.py.
test_bool_uint()
pandas.tests.io.test_stata.TestStata.test_bool_uint (self, byteorder, version)
Definition at line 716 of file test_stata.py.
test_categorical_order()
pandas.tests.io.test_stata.TestStata.test_categorical_order (self, file, datapath)
Definition at line 1094 of file test_stata.py.
test_categorical_ordering()
pandas.tests.io.test_stata.TestStata.test_categorical_ordering (self, file, datapath)
Definition at line 1147 of file test_stata.py.
test_categorical_sorting()
pandas.tests.io.test_stata.TestStata.test_categorical_sorting (self, file, datapath)
Definition at line 1130 of file test_stata.py.
test_categorical_warnings_and_errors()
pandas.tests.io.test_stata.TestStata.test_categorical_warnings_and_errors (self)
Definition at line 1039 of file test_stata.py.
test_categorical_with_stata_missing_values()
pandas.tests.io.test_stata.TestStata.test_categorical_with_stata_missing_values (self, version)
Definition at line 1070 of file test_stata.py.
test_categorical_writing()
pandas.tests.io.test_stata.TestStata.test_categorical_writing (self, version)
Definition at line 987 of file test_stata.py.
test_convert_strl_name_swap()
pandas.tests.io.test_stata.TestStata.test_convert_strl_name_swap (self)
Definition at line 1698 of file test_stata.py.
test_date_export_formats()
pandas.tests.io.test_stata.TestStata.test_date_export_formats (self)
Definition at line 671 of file test_stata.py.
test_date_parsing_ignores_format_details()
pandas.tests.io.test_stata.TestStata.test_date_parsing_ignores_format_details (self, column, datapath)
Definition at line 1606 of file test_stata.py.
test_dates_invalid_column()
pandas.tests.io.test_stata.TestStata.test_dates_invalid_column (self)
Definition at line 634 of file test_stata.py.
test_default_date_conversion()
pandas.tests.io.test_stata.TestStata.test_default_date_conversion (self)
Definition at line 1397 of file test_stata.py.
test_drop_column()
pandas.tests.io.test_stata.TestStata.test_drop_column (self, datapath)
Definition at line 934 of file test_stata.py.
test_dtype_conversion()
pandas.tests.io.test_stata.TestStata.test_dtype_conversion (self, datapath)
Definition at line 904 of file test_stata.py.
test_encoding()
pandas.tests.io.test_stata.TestStata.test_encoding (self, version, datapath)
Definition at line 394 of file test_stata.py.
test_encoding_latin1_118()
pandas.tests.io.test_stata.TestStata.test_encoding_latin1_118 (self, datapath)
Definition at line 1851 of file test_stata.py.
test_excessively_long_string()
pandas.tests.io.test_stata.TestStata.test_excessively_long_string (self)
Definition at line 780 of file test_stata.py.
test_gzip_writing()
pandas.tests.io.test_stata.TestStata.test_gzip_writing (self)
Definition at line 1751 of file test_stata.py.
test_inf()
pandas.tests.io.test_stata.TestStata.test_inf (self, infval)
Definition at line 1544 of file test_stata.py.
test_invalid_date_conversion()
pandas.tests.io.test_stata.TestStata.test_invalid_date_conversion (self)
Definition at line 1713 of file test_stata.py.
test_invalid_file_not_written()
pandas.tests.io.test_stata.TestStata.test_invalid_file_not_written (self, version)
Definition at line 1817 of file test_stata.py.
test_invalid_timestamp()
pandas.tests.io.test_stata.TestStata.test_invalid_timestamp (self, version)
Definition at line 545 of file test_stata.py.
test_invalid_variable_label_encoding()
pandas.tests.io.test_stata.TestStata.test_invalid_variable_label_encoding (self, version, mixed_frame)
Definition at line 1355 of file test_stata.py.
test_invalid_variable_labels()
pandas.tests.io.test_stata.TestStata.test_invalid_variable_labels (self, version, mixed_frame)
Definition at line 1344 of file test_stata.py.
test_iterator()
pandas.tests.io.test_stata.TestStata.test_iterator (self, datapath)
Definition at line 1226 of file test_stata.py.
test_large_value_conversion()
pandas.tests.io.test_stata.TestStata.test_large_value_conversion (self)
Definition at line 614 of file test_stata.py.
test_minimal_size_col()
pandas.tests.io.test_stata.TestStata.test_minimal_size_col (self)
Definition at line 763 of file test_stata.py.
test_missing_value_conversion()
pandas.tests.io.test_stata.TestStata.test_missing_value_conversion (self, file, datapath)
Definition at line 830 of file test_stata.py.
test_missing_value_generator()
pandas.tests.io.test_stata.TestStata.test_missing_value_generator (self)
Definition at line 798 of file test_stata.py.
test_mixed_string_strl()
pandas.tests.io.test_stata.TestStata.test_mixed_string_strl (self, using_infer_string)
Definition at line 1783 of file test_stata.py.
test_nan_to_missing_value()
pandas.tests.io.test_stata.TestStata.test_nan_to_missing_value (self, version)
Definition at line 574 of file test_stata.py.
test_no_index()
pandas.tests.io.test_stata.TestStata.test_no_index (self)
Definition at line 591 of file test_stata.py.
test_nonfile_writing()
pandas.tests.io.test_stata.TestStata.test_nonfile_writing (self, version)
Definition at line 1734 of file test_stata.py.
test_numeric_column_names()
pandas.tests.io.test_stata.TestStata.test_numeric_column_names (self)
Definition at line 554 of file test_stata.py.
test_out_of_range_double()
pandas.tests.io.test_stata.TestStata.test_out_of_range_double (self)
Definition at line 1499 of file test_stata.py.
test_out_of_range_float()
pandas.tests.io.test_stata.TestStata.test_out_of_range_float (self)
Definition at line 1515 of file test_stata.py.
test_path_pathlib()
pandas.tests.io.test_stata.TestStata.test_path_pathlib (self)
Definition at line 1555 of file test_stata.py.
test_pickle_path_localpath()
pandas.tests.io.test_stata.TestStata.test_pickle_path_localpath (self)
Definition at line 1566 of file test_stata.py.
test_read_chunks_115()
pandas.tests.io.test_stata.TestStata.test_read_chunks_115 (self, file, chunksize, convert_categoricals, convert_dates, datapath)
Definition at line 1271 of file test_stata.py.
test_read_chunks_117()
pandas.tests.io.test_stata.TestStata.test_read_chunks_117 (self, file, chunksize, convert_categoricals, convert_dates, datapath)
Definition at line 1178 of file test_stata.py.
test_read_chunks_columns()
pandas.tests.io.test_stata.TestStata.test_read_chunks_columns (self, datapath)
Definition at line 1303 of file test_stata.py.
test_read_dta1()
pandas.tests.io.test_stata.TestStata.test_read_dta1 (self, file, datapath)
Definition at line 123 of file test_stata.py.
test_read_dta12()
pandas.tests.io.test_stata.TestStata.test_read_dta12 (self, datapath)
Definition at line 264 of file test_stata.py.
test_read_dta18()
pandas.tests.io.test_stata.TestStata.test_read_dta18 (self, datapath)
Definition at line 277 of file test_stata.py.
test_read_dta2()
pandas.tests.io.test_stata.TestStata.test_read_dta2 (self, datapath)
Definition at line 140 of file test_stata.py.
test_read_dta3()
pandas.tests.io.test_stata.TestStata.test_read_dta3 (self, file, datapath)
Definition at line 205 of file test_stata.py.
test_read_dta4()
pandas.tests.io.test_stata.TestStata.test_read_dta4 (self, file, datapath)
Definition at line 220 of file test_stata.py.
test_read_empty_dta()
pandas.tests.io.test_stata.TestStata.test_read_empty_dta (self, version)
Definition at line 66 of file test_stata.py.
test_read_empty_dta_with_dtypes()
pandas.tests.io.test_stata.TestStata.test_read_empty_dta_with_dtypes (self, version)
Definition at line 75 of file test_stata.py.
test_read_index_col_none()
pandas.tests.io.test_stata.TestStata.test_read_index_col_none (self, version)
Definition at line 110 of file test_stata.py.
test_read_write_dta10()
pandas.tests.io.test_stata.TestStata.test_read_write_dta10 (self, version, using_infer_string)
Definition at line 349 of file test_stata.py.
test_read_write_dta11()
pandas.tests.io.test_stata.TestStata.test_read_write_dta11 (self)
Definition at line 409 of file test_stata.py.
test_read_write_dta12()
pandas.tests.io.test_stata.TestStata.test_read_write_dta12 (self, version)
Definition at line 437 of file test_stata.py.
test_read_write_dta13()
pandas.tests.io.test_stata.TestStata.test_read_write_dta13 (self)
Definition at line 474 of file test_stata.py.
test_read_write_dta5()
pandas.tests.io.test_stata.TestStata.test_read_write_dta5 (self)
Definition at line 317 of file test_stata.py.
test_read_write_ea_dtypes()
pandas.tests.io.test_stata.TestStata.test_read_write_ea_dtypes (self, dtype_backend)
Definition at line 1947 of file test_stata.py.
test_read_write_reread_dta14()
pandas.tests.io.test_stata.TestStata.test_read_write_reread_dta14 (self, file, parsed_114, version, datapath)
Definition at line 496 of file test_stata.py.
test_read_write_reread_dta15()
pandas.tests.io.test_stata.TestStata.test_read_write_reread_dta15 (self, file, datapath)
Definition at line 514 of file test_stata.py.
test_repeated_column_labels()
pandas.tests.io.test_stata.TestStata.test_repeated_column_labels (self, datapath)
Definition at line 1465 of file test_stata.py.
test_set_index()
pandas.tests.io.test_stata.TestStata.test_set_index (self)
Definition at line 1590 of file test_stata.py.
test_stata_111()
pandas.tests.io.test_stata.TestStata.test_stata_111 (self, datapath)
Definition at line 1483 of file test_stata.py.
test_stata_119()
pandas.tests.io.test_stata.TestStata.test_stata_119 (self, datapath)
Definition at line 1872 of file test_stata.py.
test_stata_doc_examples()
pandas.tests.io.test_stata.TestStata.test_stata_doc_examples (self)
Definition at line 374 of file test_stata.py.
test_string_no_dates()
pandas.tests.io.test_stata.TestStata.test_string_no_dates (self)
Definition at line 601 of file test_stata.py.
test_strl_latin1()
pandas.tests.io.test_stata.TestStata.test_strl_latin1 (self)
Definition at line 1832 of file test_stata.py.
test_timestamp_and_label()
pandas.tests.io.test_stata.TestStata.test_timestamp_and_label (self, version)
Definition at line 531 of file test_stata.py.
test_unicode_dta_118()
pandas.tests.io.test_stata.TestStata.test_unicode_dta_118 (self, datapath)
Definition at line 1766 of file test_stata.py.
test_unsupported_datetype()
pandas.tests.io.test_stata.TestStata.test_unsupported_datetype (self)
Definition at line 1434 of file test_stata.py.
test_unsupported_type()
pandas.tests.io.test_stata.TestStata.test_unsupported_type (self)
Definition at line 1426 of file test_stata.py.
test_utf8_writer()
pandas.tests.io.test_stata.TestStata.test_utf8_writer (self, version)
Definition at line 1885 of file test_stata.py.
test_value_labels_iterator()
pandas.tests.io.test_stata.TestStata.test_value_labels_iterator (self, write_index)
Definition at line 1578 of file test_stata.py.
test_value_labels_old_format()
pandas.tests.io.test_stata.TestStata.test_value_labels_old_format (self, datapath)
Definition at line 662 of file test_stata.py.
test_variable_labels()
pandas.tests.io.test_stata.TestStata.test_variable_labels (self, datapath)
Definition at line 750 of file test_stata.py.
test_write_dta6()
pandas.tests.io.test_stata.TestStata.test_write_dta6 (self, datapath)
Definition at line 332 of file test_stata.py.
test_write_missing_strings()
pandas.tests.io.test_stata.TestStata.test_write_missing_strings (self)
Definition at line 699 of file test_stata.py.
test_write_preserves_original()
pandas.tests.io.test_stata.TestStata.test_write_preserves_original (self)
Definition at line 381 of file test_stata.py.
test_write_variable_label_errors()
pandas.tests.io.test_stata.TestStata.test_write_variable_label_errors (self, mixed_frame)
Definition at line 1367 of file test_stata.py.
test_write_variable_labels()
pandas.tests.io.test_stata.TestStata.test_write_variable_labels (self, version, mixed_frame)
Definition at line 1320 of file test_stata.py.
test_writer_117()
pandas.tests.io.test_stata.TestStata.test_writer_117 (self, using_infer_string)
Definition at line 1623 of file test_stata.py.
test_writer_118_exceptions()
pandas.tests.io.test_stata.TestStata.test_writer_118_exceptions (self)
Definition at line 1934 of file test_stata.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/tests/io/test_stata.py