Code Cloning Analysis: sklearn.externals._arff.NominalConversor Class Reference
sklearn.externals._arff.NominalConversor Class Reference
Public Member Functions
__init__ (self, values)
__call__ (self, value)
Public Attributes
values = set(values)
zero_value = values[0]
Detailed Description
Definition at line 439 of file _arff.py.
Constructor & Destructor Documentation
__init__()
sklearn.externals._arff.NominalConversor.__init__ (self, values)
Definition at line 440 of file _arff.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params().
Member Function Documentation
__call__()
sklearn.externals._arff.NominalConversor.__call__ (self, value)
Definition at line 444 of file _arff.py.
Member Data Documentation
values
sklearn.externals._arff.NominalConversor.values = set(values)
Definition at line 441 of file _arff.py.
Referenced by pandas.core.apply.FrameApply.apply_raw(), scipy.sparse._dok._dok_base.count_nonzero(), pandas.core.series.Series.dot(), and scipy.sparse._dok._dok_base.tocoo().
zero_value
sklearn.externals._arff.NominalConversor.zero_value = values[0]
Definition at line 442 of file _arff.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/sklearn/externals/_arff.py