Code Cloning Analysis: pyparsing.util Namespace Reference
pyparsing.util Namespace Reference
Classes
class __config_flags
class _FifoCache
class _GroupConsecutive
class _UnboundedCache
class LRUMemo
class UnboundedMemo
Functions
int col (int loc, str strg)
int lineno (int loc, str strg)
str line (int loc, str strg)
str _escape_regex_range_chars (str s)
str _collapse_string_to_ranges (Union[str, Iterable[str]] s, bool re_escape=True)
list _flatten (Iterable ll)
str make_compressed_re (Iterable[str] word_list, int max_level=2, *, bool non_capturing_groups=True, int _level=1)
C replaced_by_pep8 (str compat_name, C fn)
Variables
_bslash = chr(92)
C = TypeVar("C", bound=Callable)
Function Documentation
_collapse_string_to_ranges()
str pyparsing.util._collapse_string_to_ranges (Union[str, Iterable[str]] s, bool re_escape = True) protected
Take a string or list of single-character strings, and return
a string of the consecutive characters in that string collapsed
into groups, as might be used in a regular expression '[a-z]'
character set:
'a' -> 'a' -> '[a]'
'bc' -> 'bc' -> '[bc]'
'defgh' -> 'd-h' -> '[d-h]'
'fdgeh' -> 'd-h' -> '[d-h]'
'jklnpqrtu' -> 'j-lnp-rtu' -> '[j-lnp-rtu]'
Duplicates get collapsed out:
'aaa' -> 'a' -> '[a]'
'bcbccb' -> 'bc' -> '[bc]'
'defghhgf' -> 'd-h' -> '[d-h]'
'jklnpqrjjjtu' -> 'j-lnp-rtu' -> '[j-lnp-rtu]'
Spaces are preserved:
'ab c' -> ' a-c' -> '[ a-c]'
Characters that are significant when defining regex ranges
get escaped:
'acde[]-' -> r'\-\[\]ac-e' -> r'[\-\[\]ac-e]'
Definition at line 210 of file util.py.
Referenced by pyparsing.core.CharsNotIn._generateDefaultName(), and pyparsing.core.Word._generateDefaultName().
_escape_regex_range_chars()
str pyparsing.util._escape_regex_range_chars (str s) protected
Definition at line 176 of file util.py.
_flatten()
list pyparsing.util._flatten (Iterable ll) protected
Definition at line 294 of file util.py.
col()
int pyparsing.util.col (int loc, str strg)
Returns current column within a string, counting newlines as line separators.
The first column is number 1.
Note: the default parsing behavior is to expand tabs in the input string
before starting the parsing process.  See
:class:`ParserElement.parse_string` for more
information on parsing strings containing ``<TAB>`` s, and suggested
methods to maintain a consistent view of the parsed string, the parse
location, and line and column positions within the parsed string.
Definition at line 41 of file util.py.
Referenced by pyparsing.core.And._ErrorStop._generateDefaultName(), pyparsing.helpers.indentedBlock(), and pyparsing.actions.match_only_at_col().
line()
str pyparsing.util.line (int loc, str strg)
Returns the line of text containing loc within a string, counting newlines as line separators.
Definition at line 72 of file util.py.
lineno()
int pyparsing.util.lineno (int loc, str strg)
Returns current line number within a string, counting newlines as line separators.
The first line is number 1.
Note - the default parsing behavior is to expand tabs in the input string
before starting the parsing process.  See :class:`ParserElement.parse_string`
for more information on parsing strings containing ``<TAB>`` s, and
suggested methods to maintain a consistent view of the parsed string, the
parse location, and line and column positions within the parsed string.
Definition at line 58 of file util.py.
make_compressed_re()
str pyparsing.util.make_compressed_re (Iterable[str] word_list, int max_level = 2, * , bool non_capturing_groups = True, int _level = 1)
Create a regular expression string from a list of words, collapsing by common
prefixes and optional suffixes.
Calls itself recursively to build nested sublists for each group of suffixes
that have a shared prefix.
Definition at line 306 of file util.py.
References make_compressed_re().
Referenced by make_compressed_re().
replaced_by_pep8()
C pyparsing.util.replaced_by_pep8 (str compat_name, C fn)
Definition at line 401 of file util.py.
Variable Documentation
_bslash
pyparsing.util._bslash = chr(92) protected
Definition at line 11 of file util.py.
C
pyparsing.util.C = TypeVar("C", bound=Callable)
Definition at line 12 of file util.py.