Code Cloning Analysis: scipy.sparse.linalg._eigen.arpack.tests.test_arpack Namespace Reference
scipy.sparse.linalg._eigen.arpack.tests.test_arpack Namespace Reference
Classes
class DictWithRepr
class NonSymmetricParams
class SymmetricParams
Functions
_get_test_tolerance (type_char, mattype=None, D_type=None, which=None)
generate_matrix (N, complex_=False, hermitian=False, pos_definite=False, sparse=False)
generate_matrix_symmetric (N, pos_definite=False, sparse=False)
assert_allclose_cc (actual, desired, **kw)
argsort_which (eigenvalues, typ, k, which, sigma=None, OPpart=None, mode=None)
eval_evec (symmetric, d, typ, k, which, v0=None, sigma=None, mattype=np.asarray, OPpart=None, mode='normal')
test_symmetric_modes ()
test_hermitian_modes ()
test_symmetric_starting_vector ()
test_symmetric_no_convergence ()
test_real_nonsymmetric_modes ()
test_complex_nonsymmetric_modes ()
test_standard_nonsymmetric_starting_vector ()
test_general_nonsymmetric_starting_vector ()
test_standard_nonsymmetric_no_convergence ()
test_eigen_bad_shapes ()
test_eigen_bad_kwargs ()
test_ticket_1459_arpack_crash ()
test_linearoperator_deallocation ()
test_parallel_threads ()
test_reentering ()
test_regression_arpackng_1315 ()
test_eigs_for_k_greater ()
test_eigsh_for_k_greater ()
test_real_eigs_real_k_subset ()
Variables
str __usage__
dict _ndigits = {'f': 3, 'd': 11, 'F': 3, 'D': 11}
Function Documentation
_get_test_tolerance()
scipy.sparse.linalg._eigen.arpack.tests.test_arpack._get_test_tolerance (type_char, mattype = None, D_type = None, which = None) protected
Return tolerance values suitable for a given test:
Parameters
----------
type_char : {'f', 'd', 'F', 'D'}
    Data type in ARPACK eigenvalue problem
mattype : {csr_matrix, aslinearoperator, asarray}, optional
    Linear operator type
Returns
-------
tol
    Tolerance to pass to the ARPACK routine
rtol
    Relative tolerance for outputs
atol
    Absolute tolerance for outputs
Definition at line 31 of file test_arpack.py.
Referenced by argsort_which().
argsort_which()
scipy.sparse.linalg._eigen.arpack.tests.test_arpack.argsort_which (eigenvalues, typ, k, which, sigma = None, OPpart = None, mode = None)
Return sorted indices of eigenvalues using the "which" keyword
from eigs and eigsh
Definition at line 141 of file test_arpack.py.
References _get_test_tolerance(), argsort_which(), and assert_allclose_cc().
Referenced by argsort_which().
assert_allclose_cc()
scipy.sparse.linalg._eigen.arpack.tests.test_arpack.assert_allclose_cc (actual, desired, ** kw)
Almost equal or complex conjugates almost equal
Definition at line 133 of file test_arpack.py.
Referenced by argsort_which().
eval_evec()
scipy.sparse.linalg._eigen.arpack.tests.test_arpack.eval_evec (symmetric, d, typ, k, which, v0 = None, sigma = None, mattype = np.asarray, OPpart = None, mode = 'normal')
Definition at line 187 of file test_arpack.py.
generate_matrix()
scipy.sparse.linalg._eigen.arpack.tests.test_arpack.generate_matrix (N, complex_ = False, hermitian = False, pos_definite = False, sparse = False)
Definition at line 85 of file test_arpack.py.
generate_matrix_symmetric()
scipy.sparse.linalg._eigen.arpack.tests.test_arpack.generate_matrix_symmetric (N, pos_definite = False, sparse = False)
Definition at line 116 of file test_arpack.py.
test_complex_nonsymmetric_modes()
scipy.sparse.linalg._eigen.arpack.tests.test_arpack.test_complex_nonsymmetric_modes ()
Definition at line 467 of file test_arpack.py.
test_eigen_bad_kwargs()
scipy.sparse.linalg._eigen.arpack.tests.test_arpack.test_eigen_bad_kwargs ()
Definition at line 528 of file test_arpack.py.
test_eigen_bad_shapes()
scipy.sparse.linalg._eigen.arpack.tests.test_arpack.test_eigen_bad_shapes ()
Definition at line 522 of file test_arpack.py.
test_eigs_for_k_greater()
scipy.sparse.linalg._eigen.arpack.tests.test_arpack.test_eigs_for_k_greater ()
Definition at line 630 of file test_arpack.py.
test_eigsh_for_k_greater()
scipy.sparse.linalg._eigen.arpack.tests.test_arpack.test_eigsh_for_k_greater ()
Definition at line 656 of file test_arpack.py.
test_general_nonsymmetric_starting_vector()
scipy.sparse.linalg._eigen.arpack.tests.test_arpack.test_general_nonsymmetric_starting_vector ()
Definition at line 493 of file test_arpack.py.
test_hermitian_modes()
scipy.sparse.linalg._eigen.arpack.tests.test_arpack.test_hermitian_modes ()
Definition at line 413 of file test_arpack.py.
test_linearoperator_deallocation()
scipy.sparse.linalg._eigen.arpack.tests.test_arpack.test_linearoperator_deallocation ()
Definition at line 554 of file test_arpack.py.
test_parallel_threads()
scipy.sparse.linalg._eigen.arpack.tests.test_arpack.test_parallel_threads ()
Definition at line 575 of file test_arpack.py.
test_real_eigs_real_k_subset()
scipy.sparse.linalg._eigen.arpack.tests.test_arpack.test_real_eigs_real_k_subset ()
Definition at line 681 of file test_arpack.py.
test_real_nonsymmetric_modes()
scipy.sparse.linalg._eigen.arpack.tests.test_arpack.test_real_nonsymmetric_modes ()
Definition at line 453 of file test_arpack.py.
test_reentering()
scipy.sparse.linalg._eigen.arpack.tests.test_arpack.test_reentering ()
Definition at line 599 of file test_arpack.py.
test_regression_arpackng_1315()
scipy.sparse.linalg._eigen.arpack.tests.test_arpack.test_regression_arpackng_1315 ()
Definition at line 612 of file test_arpack.py.
test_standard_nonsymmetric_no_convergence()
scipy.sparse.linalg._eigen.arpack.tests.test_arpack.test_standard_nonsymmetric_no_convergence ()
Definition at line 506 of file test_arpack.py.
test_standard_nonsymmetric_starting_vector()
scipy.sparse.linalg._eigen.arpack.tests.test_arpack.test_standard_nonsymmetric_starting_vector ()
Definition at line 480 of file test_arpack.py.
test_symmetric_modes()
scipy.sparse.linalg._eigen.arpack.tests.test_arpack.test_symmetric_modes ()
Definition at line 399 of file test_arpack.py.
test_symmetric_no_convergence()
scipy.sparse.linalg._eigen.arpack.tests.test_arpack.test_symmetric_no_convergence ()
Definition at line 438 of file test_arpack.py.
test_symmetric_starting_vector()
scipy.sparse.linalg._eigen.arpack.tests.test_arpack.test_symmetric_starting_vector ()
Definition at line 428 of file test_arpack.py.
test_ticket_1459_arpack_crash()
scipy.sparse.linalg._eigen.arpack.tests.test_arpack.test_ticket_1459_arpack_crash ()
Definition at line 534 of file test_arpack.py.
Variable Documentation
__usage__
str scipy.sparse.linalg._eigen.arpack.tests.test_arpack.__usage__ private
Initial value:
=  """
To run tests locally:
  python tests/test_arpack.py [-l<int>] [-v<int>]
"""
Definition at line 1 of file test_arpack.py.
_ndigits
dict scipy.sparse.linalg._eigen.arpack.tests.test_arpack._ndigits = {'f': 3, 'd': 11, 'F': 3, 'D': 11} protected
Definition at line 28 of file test_arpack.py.