Code Cloning Analysis: numpy.polynomial.tests.test_symbol.TestBinaryOperatorsDifferentSymbol Class Reference
numpy.polynomial.tests.test_symbol.TestBinaryOperatorsDifferentSymbol Class Reference
Public Member Functions
test_binops_fails (self, f)
Static Public Attributes
p = poly.Polynomial([1, 2, 3], symbol='x')
other = poly.Polynomial([4, 5, 6], symbol='y')
tuple ops = (p.__add__, p.__sub__, p.__mul__, p.__floordiv__, p.__mod__)
Detailed Description
Definition at line 127 of file test_symbol.py.
Member Function Documentation
test_binops_fails()
numpy.polynomial.tests.test_symbol.TestBinaryOperatorsDifferentSymbol.test_binops_fails (self, f)
Definition at line 133 of file test_symbol.py.
Member Data Documentation
ops
tuple numpy.polynomial.tests.test_symbol.TestBinaryOperatorsDifferentSymbol.ops = (p.__add__, p.__sub__, p.__mul__, p.__floordiv__, p.__mod__) static
Definition at line 130 of file test_symbol.py.
other
numpy.polynomial.tests.test_symbol.TestBinaryOperatorsDifferentSymbol.other = poly.Polynomial([4, 5, 6], symbol='y') static
Definition at line 129 of file test_symbol.py.
Referenced by pip._vendor.urllib3.util.retry.Retry.increment(), and pip._vendor.urllib3.util.retry.Retry.is_exhausted().
p
numpy.polynomial.tests.test_symbol.TestBinaryOperatorsDifferentSymbol.p = poly.Polynomial([1, 2, 3], symbol='x') static
Definition at line 128 of file test_symbol.py.
Referenced by sklearn.model_selection._split.LeavePOut._iter_test_indices(), sklearn.cluster._dbscan.DBSCAN.fit(), sklearn.cluster._optics.OPTICS.fit(), sklearn.model_selection._split.LeavePOut.get_n_splits(), sklearn.neighbors._classification.KNeighborsClassifier.predict_proba(), sklearn.neighbors._classification.RadiusNeighborsClassifier.predict_proba(), sklearn.utils.tests.test_estimator_checks.ModifiesValueInsteadOfRaisingError.set_params(), and sklearn.utils.tests.test_estimator_checks.RaisesErrorInSetParams.set_params().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/polynomial/tests/test_symbol.py