Code Cloning Analysis: kiwisolver.exceptions.UnknownEditVariable Class Reference
kiwisolver.exceptions.UnknownEditVariable Class Reference
Public Member Functions
__init__ (self, edit_variable)
Public Attributes
edit_variable = edit_variable
Static Private Attributes
tuple __slots__ = ("edit_variable",)
Detailed Description
Definition at line 40 of file exceptions.py.
Constructor & Destructor Documentation
__init__()
kiwisolver.exceptions.UnknownEditVariable.__init__ (self, edit_variable)
Definition at line 43 of file exceptions.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Data Documentation
__slots__
tuple kiwisolver.exceptions.UnknownEditVariable.__slots__ = ("edit_variable",) static private
Definition at line 41 of file exceptions.py.
edit_variable
kiwisolver.exceptions.UnknownEditVariable.edit_variable = edit_variable
Definition at line 44 of file exceptions.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/kiwisolver/exceptions.py