Code Cloning Analysis: fontTools.misc.psCharStrings.T1CharString Class Reference
fontTools.misc.psCharStrings.T1CharString Class Reference
Public Member Functions
__init__ (self, bytecode=None, program=None, subrs=None)
getIntEncoder (self)
getFixedEncoder (self)
decompile (self)
draw (self, pen)
Public Member Functions inherited from fontTools.misc.psCharStrings.T2CharString
__init__ (self, bytecode=None, program=None, private=None, globalSubrs=None)
getNumRegions (self, vsindex=None)
__repr__ (self)
calcBounds (self, glyphSet)
compile (self, isCFF2=False)
needsDecompilation (self)
setProgram (self, program)
setBytecode (self, bytecode)
getToken (self, index, len=len, byteord=byteord, isinstance=isinstance)
getBytes (self, index, nBytes)
handle_operator (self, operator)
toXML (self, xmlWriter, ttFont=None)
fromXML (self, name, attrs, content)
Public Attributes
subrs = subrs
Public Attributes inherited from fontTools.misc.psCharStrings.T2CharString
bytecode = bytecode
program = program
private = private
globalSubrs = globalSubrs if globalSubrs is not None else []
width = extractor.width
Additional Inherited Members
Static Public Attributes inherited from fontTools.misc.psCharStrings.T2CharString
operandEncoding = t2OperandEncoding
operators
opcodes
decompilerClass = SimpleT2Decompiler
outlineExtractor = T2OutlineExtractor
Protected Attributes inherited from fontTools.misc.psCharStrings.T2CharString
int _cur_vsindex = None
Detailed Description
Definition at line 1334 of file psCharStrings.py.
Constructor & Destructor Documentation
__init__()
fontTools.misc.psCharStrings.T1CharString.__init__ (self, bytecode = None, program = None, subrs = None)
Definition at line 1338 of file psCharStrings.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
decompile()
fontTools.misc.psCharStrings.T1CharString.decompile (self)
Reimplemented from fontTools.misc.psCharStrings.T2CharString.
Definition at line 1349 of file psCharStrings.py.
Referenced by fontTools.ttLib.tables._c_m_a_p.CmapSubtable.newSubtable().
draw()
fontTools.misc.psCharStrings.T1CharString.draw (self, pen)
Reimplemented from fontTools.misc.psCharStrings.T2CharString.
Definition at line 1361 of file psCharStrings.py.
Referenced by matplotlib.backends.backend_macosx.FigureCanvasMac._draw_idle(), matplotlib.backends.backend_gtk4.FigureCanvasGTK4._mpl_coords(), matplotlib.backends.backend_wx._FigureCanvasWxBase._on_paint(), matplotlib.backends.backend_gtk4cairo.FigureCanvasGTK4Cairo._set_device_pixel_ratio(), matplotlib.backends.backend_qt.FigureCanvasQT.blit(), matplotlib.backends.backend_wx._FigureCanvasWxBase.Copy_to_Clipboard(), matplotlib.backends.backend_wx.FigureCanvasWx.draw(), matplotlib.backends._backend_tk.FigureCanvasTk.draw_idle(), fontTools.ttLib.ttGlyphSet._TTGlyph.drawPoints(), matplotlib.backends.backend_template.FigureCanvasTemplate.print_foo(), and matplotlib.axes._base._AxesBase.redraw_in_frame().
getFixedEncoder()
fontTools.misc.psCharStrings.T1CharString.getFixedEncoder (self)
Reimplemented from fontTools.misc.psCharStrings.T2CharString.
Definition at line 1345 of file psCharStrings.py.
getIntEncoder()
fontTools.misc.psCharStrings.T1CharString.getIntEncoder (self)
Reimplemented from fontTools.misc.psCharStrings.T2CharString.
Definition at line 1342 of file psCharStrings.py.
Member Data Documentation
subrs
fontTools.misc.psCharStrings.T1CharString.subrs = subrs
Definition at line 1340 of file psCharStrings.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/misc/psCharStrings.py