Code Cloning Analysis: axes_grid1.mpl_axes.SimpleChainedObjects Class Reference
axes_grid1.mpl_axes.SimpleChainedObjects Class Reference
Public Member Functions
__init__ (self, objects)
__getattr__ (self, k)
__call__ (self, *args, **kwargs)
Protected Attributes
_objects = objects
Detailed Description
Definition at line 6 of file mpl_axes.py.
Constructor & Destructor Documentation
__init__()
axes_grid1.mpl_axes.SimpleChainedObjects.__init__ (self, objects)
Definition at line 7 of file mpl_axes.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__call__()
axes_grid1.mpl_axes.SimpleChainedObjects.__call__ (self, * args, ** kwargs)
Definition at line 14 of file mpl_axes.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), and scipy.interpolate._fitpack2.SphereBivariateSpline.ev().
__getattr__()
axes_grid1.mpl_axes.SimpleChainedObjects.__getattr__ (self, k)
Definition at line 10 of file mpl_axes.py.
Member Data Documentation
_objects
axes_grid1.mpl_axes.SimpleChainedObjects._objects = objects protected
Definition at line 8 of file mpl_axes.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/mpl_toolkits/axes_grid1/mpl_axes.py