Code Cloning Analysis: matplotlib._api.deprecation.deprecate_privatize_attribute Class Reference
matplotlib._api.deprecation.deprecate_privatize_attribute Class Reference
Public Member Functions
__init__ (self, *args, **kwargs)
__set_name__ (self, owner, name)
Public Attributes
deprecator = deprecated(*args, **kwargs)
Detailed Description
Helper to deprecate public access to an attribute (or method).
This helper should only be used at class scope, as follows::
    class Foo:
        attr = _deprecate_privatize_attribute(*args, **kwargs)
where *all* parameters are forwarded to `deprecated`.  This form makes
``attr`` a property which forwards read and write access to ``self._attr``
(same name but with a leading underscore), with a deprecation warning.
Note that the attribute name is derived from *the name this helper is
assigned to*.  This helper also works for deprecating methods.
Definition at line 221 of file deprecation.py.
Constructor & Destructor Documentation
__init__()
matplotlib._api.deprecation.deprecate_privatize_attribute.__init__ (self, * args, ** kwargs)
Definition at line 237 of file deprecation.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__set_name__()
matplotlib._api.deprecation.deprecate_privatize_attribute.__set_name__ (self, owner, name)
Definition at line 240 of file deprecation.py.
Member Data Documentation
deprecator
matplotlib._api.deprecation.deprecate_privatize_attribute.deprecator = deprecated(*args, **kwargs)
Definition at line 238 of file deprecation.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/_api/deprecation.py