Code Cloning Analysis: scipy.stats._multivariate.multivariate_hypergeom_frozen Class Reference
scipy.stats._multivariate.multivariate_hypergeom_frozen Class Reference
Public Member Functions
__init__ (self, m, n, seed=None)
logpmf (self, x)
pmf (self, x)
mean (self)
var (self)
cov (self)
rvs (self, size=1, random_state=None)
Public Member Functions inherited from scipy.stats._multivariate.multi_rv_frozen
random_state (self)
random_state (self, seed)
Public Attributes
M
m
n
mcond
ncond
mncond
Protected Attributes
_dist = multivariate_hypergeom_gen(seed)
Detailed Description
Definition at line 5224 of file _multivariate.py.
Constructor & Destructor Documentation
__init__()
scipy.stats._multivariate.multivariate_hypergeom_frozen.__init__ (self, m, n, seed = None)
Definition at line 5225 of file _multivariate.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params().
Member Function Documentation
cov()
scipy.stats._multivariate.multivariate_hypergeom_frozen.cov (self)
Definition at line 5250 of file _multivariate.py.
logpmf()
scipy.stats._multivariate.multivariate_hypergeom_frozen.logpmf (self, x)
Definition at line 5238 of file _multivariate.py.
Referenced by scipy.stats._multivariate.dirichlet_multinomial_gen.pmf(), and scipy.stats._multivariate.random_table_gen.pmf().
mean()
scipy.stats._multivariate.multivariate_hypergeom_frozen.mean (self)
Definition at line 5244 of file _multivariate.py.
pmf()
scipy.stats._multivariate.multivariate_hypergeom_frozen.pmf (self, x)
Definition at line 5241 of file _multivariate.py.
Referenced by scipy.stats._page_trend_test._PageL.pmf(), and scipy.stats._page_trend_test._PageL.sf().
rvs()
scipy.stats._multivariate.multivariate_hypergeom_frozen.rvs (self, size = 1, random_state = None)
Definition at line 5253 of file _multivariate.py.
var()
scipy.stats._multivariate.multivariate_hypergeom_frozen.var (self)
Definition at line 5247 of file _multivariate.py.
Member Data Documentation
_dist
scipy.stats._multivariate.multivariate_hypergeom_frozen._dist = multivariate_hypergeom_gen(seed) protected
Definition at line 5226 of file _multivariate.py.
Referenced by scipy.stats._multivariate.uniform_direction_frozen.__init__(), scipy.stats._multivariate.vonmises_fisher_frozen.__init__(), scipy.stats._multivariate.vonmises_fisher_frozen.entropy(), scipy.stats._multivariate.vonmises_fisher_frozen.logpdf(), and scipy.stats._multivariate.vonmises_fisher_frozen.rvs().
M
scipy.stats._multivariate.multivariate_hypergeom_frozen.M
Definition at line 5227 of file _multivariate.py.
m
scipy.stats._multivariate.multivariate_hypergeom_frozen.m
Definition at line 5227 of file _multivariate.py.
mcond
scipy.stats._multivariate.multivariate_hypergeom_frozen.mcond
Definition at line 5228 of file _multivariate.py.
mncond
scipy.stats._multivariate.multivariate_hypergeom_frozen.mncond
Definition at line 5229 of file _multivariate.py.
n
scipy.stats._multivariate.multivariate_hypergeom_frozen.n
Definition at line 5227 of file _multivariate.py.
ncond
scipy.stats._multivariate.multivariate_hypergeom_frozen.ncond
Definition at line 5228 of file _multivariate.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/stats/_multivariate.py