Code Cloning Analysis: numpy.typing.tests.test_typing Namespace Reference
numpy.typing.tests.test_typing Namespace Reference
Functions
str _key_func (str key)
tuple[int, str] _strip_filename (str msg)
str strip_func (re.Match[str] match)
None run_mypy ()
Iterator[ParameterSet] get_test_cases (str directory)
None test_success (path)
None test_fail (str path)
None _test_fail (str path, str expression, str error, None|str expected_error, int lineno)
None test_reveal (str path)
None test_code_runs (str path)
None test_extended_precision ()
Variables
str RUN_MYPY = "NPY_RUN_MYPY_IN_TESTSUITE" in os.environ
pytestmark
bool NO_MYPY = True
DATA_DIR = os.path.join(os.path.dirname(__file__), "data")
PASS_DIR = os.path.join(DATA_DIR, "pass")
FAIL_DIR = os.path.join(DATA_DIR, "fail")
REVEAL_DIR = os.path.join(DATA_DIR, "reveal")
MISC_DIR = os.path.join(DATA_DIR, "misc")
MYPY_INI = os.path.join(DATA_DIR, "mypy.ini")
CACHE_DIR = os.path.join(DATA_DIR, ".mypy_cache")
defaultdict OUTPUT_MYPY = defaultdict(list)
str _FAIL_MSG1
str _FAIL_MSG2
str _REVEAL_MSG
dict LINENO_MAPPING
Function Documentation
_key_func()
str numpy.typing.tests.test_typing._key_func (str key) protected
Split at the first occurrence of the ``:`` character.
Windows drive-letters (*e.g.* ``C:``) are ignored herein.
Definition at line 68 of file test_typing.py.
Referenced by run_mypy().
_strip_filename()
tuple[int, str] numpy.typing.tests.test_typing._strip_filename (str msg) protected
Strip the filename and line number from a mypy message.
Definition at line 77 of file test_typing.py.
Referenced by run_mypy(), test_code_runs(), and test_reveal().
_test_fail()
None numpy.typing.tests.test_typing._test_fail (str path, str expression, str error, None | str expected_error, int lineno) protected
Definition at line 208 of file test_typing.py.
get_test_cases()
Iterator[ParameterSet] numpy.typing.tests.test_typing.get_test_cases (str directory)
Definition at line 135 of file test_typing.py.
run_mypy()
None numpy.typing.tests.test_typing.run_mypy ()
Clears the cache and run mypy before running any of the typing tests.
The mypy results are cached in `OUTPUT_MYPY` for further use.
The cache refresh can be skipped using
NUMPY_TYPING_TEST_CLEAR_CACHE=0 pytest numpy/typing/tests
Definition at line 90 of file test_typing.py.
References _key_func(), _strip_filename(), and numpy.lib.function_base.append().
strip_func()
str numpy.typing.tests.test_typing.strip_func (re.Match[str] match)
`re.sub` helper function for stripping module names.
Definition at line 84 of file test_typing.py.
test_code_runs()
None numpy.typing.tests.test_typing.test_code_runs (str path)
Validate that the code in `path` properly during runtime.
Definition at line 250 of file test_typing.py.
References _strip_filename().
test_extended_precision()
None numpy.typing.tests.test_typing.test_extended_precision ()
Definition at line 283 of file test_typing.py.
test_fail()
None numpy.typing.tests.test_typing.test_fail (str path)
Definition at line 159 of file test_typing.py.
test_reveal()
None numpy.typing.tests.test_typing.test_reveal (str path)
Validate that mypy correctly infers the return-types of
the expressions in `path`.
Definition at line 232 of file test_typing.py.
References _strip_filename().
test_success()
None numpy.typing.tests.test_typing.test_success (path)
Definition at line 147 of file test_typing.py.
Variable Documentation
_FAIL_MSG1
str numpy.typing.tests.test_typing._FAIL_MSG1 protected
Initial value:
=  """Extra error at line {}
Expression: {}
Extra error: {!r}
"""
Definition at line 194 of file test_typing.py.
_FAIL_MSG2
str numpy.typing.tests.test_typing._FAIL_MSG2 protected
Initial value:
=  """Error mismatch at line {}
Expression: {}
Expected error: {}
Observed error: {!r}
"""
Definition at line 200 of file test_typing.py.
_REVEAL_MSG
str numpy.typing.tests.test_typing._REVEAL_MSG protected
Initial value:
=  """Reveal mismatch at line {}
{}
"""
Definition at line 223 of file test_typing.py.
CACHE_DIR
numpy.typing.tests.test_typing.CACHE_DIR = os.path.join(DATA_DIR, ".mypy_cache")
Definition at line 61 of file test_typing.py.
DATA_DIR
numpy.typing.tests.test_typing.DATA_DIR = os.path.join(os.path.dirname(__file__), "data")
Definition at line 55 of file test_typing.py.
FAIL_DIR
numpy.typing.tests.test_typing.FAIL_DIR = os.path.join(DATA_DIR, "fail")
Definition at line 57 of file test_typing.py.
LINENO_MAPPING
dict numpy.typing.tests.test_typing.LINENO_MAPPING
Initial value:
=  {
    11: "uint128",
    12: "uint256",
    14: "int128",
    15: "int256",
    17: "float80",
    18: "float96",
    19: "float128",
    20: "float256",
    22: "complex160",
    23: "complex192",
    24: "complex256",
    25: "complex512",
}
Definition at line 265 of file test_typing.py.
MISC_DIR
numpy.typing.tests.test_typing.MISC_DIR = os.path.join(DATA_DIR, "misc")
Definition at line 59 of file test_typing.py.
MYPY_INI
numpy.typing.tests.test_typing.MYPY_INI = os.path.join(DATA_DIR, "mypy.ini")
Definition at line 60 of file test_typing.py.
NO_MYPY
bool numpy.typing.tests.test_typing.NO_MYPY = True
Definition at line 46 of file test_typing.py.
OUTPUT_MYPY
defaultdict numpy.typing.tests.test_typing.OUTPUT_MYPY = defaultdict(list)
Definition at line 65 of file test_typing.py.
PASS_DIR
numpy.typing.tests.test_typing.PASS_DIR = os.path.join(DATA_DIR, "pass")
Definition at line 56 of file test_typing.py.
pytestmark
numpy.typing.tests.test_typing.pytestmark
Initial value:
=  pytest.mark.skipif(
    not RUN_MYPY,
    reason="`NPY_RUN_MYPY_IN_TESTSUITE` not set"
)
Definition at line 23 of file test_typing.py.
REVEAL_DIR
numpy.typing.tests.test_typing.REVEAL_DIR = os.path.join(DATA_DIR, "reveal")
Definition at line 58 of file test_typing.py.
RUN_MYPY
bool numpy.typing.tests.test_typing.RUN_MYPY = "NPY_RUN_MYPY_IN_TESTSUITE" in os.environ
Definition at line 18 of file test_typing.py.