Code Cloning Analysis: fontTools.cffLib.width Namespace Reference
fontTools.cffLib.width Namespace Reference
Classes
class missingdict
Functions
cumSum (f, op=add, start=0, decreasing=False)
byteCost (widths, default, nominal)
optimizeWidthsBruteforce (widths)
optimizeWidths (widths)
main (args=None)
Variables
list __all__ = ["optimizeWidths", "main"]
Detailed Description
T2CharString glyph width optimizer.
CFF glyphs whose width equals the CFF Private dictionary's ``defaultWidthX``
value do not need to specify their width in their charstring, saving bytes.
This module determines the optimum ``defaultWidthX`` and ``nominalWidthX``
values for a font, when provided with a list of glyph widths.
Function Documentation
byteCost()
fontTools.cffLib.width.byteCost (widths, default, nominal)
Definition at line 50 of file width.py.
cumSum()
fontTools.cffLib.width.cumSum (f, op = add, start = 0, decreasing = False)
Definition at line 27 of file width.py.
main()
fontTools.cffLib.width.main (args = None)
Calculate optimum defaultWidthX/nominalWidthX values
Definition at line 167 of file width.py.
References optimizeWidths(), and optimizeWidthsBruteforce().
optimizeWidths()
fontTools.cffLib.width.optimizeWidths (widths)
Given a list of glyph widths, or dictionary mapping glyph width to number of
glyphs having that, returns a tuple of best CFF default and nominal glyph widths.
This algorithm is linear in UPEM+numGlyphs.
Definition at line 100 of file width.py.
Referenced by main().
optimizeWidthsBruteforce()
fontTools.cffLib.width.optimizeWidthsBruteforce (widths)
Bruteforce version.  Veeeeeeeeeeeeeeeeery slow.  Only works for smallests of fonts.
Definition at line 71 of file width.py.
Referenced by main().
Variable Documentation
__all__
list fontTools.cffLib.width.__all__ = ["optimizeWidths", "main"] private
Definition at line 16 of file width.py.