Code Cloning Analysis: joblib.externals.loky.backend.context Namespace Reference
joblib.externals.loky.backend.context Namespace Reference
Classes
class LokyContext
class LokyInitMainContext
Functions
get_context (method=None)
set_start_method (method, force=False)
get_start_method ()
cpu_count (only_physical_cores=False)
_cpu_count_cgroup (os_cpu_count)
_cpu_count_affinity (os_cpu_count)
_cpu_count_user (os_cpu_count)
_count_physical_cores ()
_count_physical_cores_linux ()
_count_physical_cores_win32 ()
_count_physical_cores_darwin ()
Variables
int _MAX_WINDOWS_WORKERS = _MAX_WINDOWS_WORKERS - 1
list START_METHODS = ["loky", "loky_init_main", "spawn"]
_DEFAULT_START_METHOD = None
physical_cores_cache = None
ctx_loky = LokyContext()
Function Documentation
_count_physical_cores()
joblib.externals.loky.backend.context._count_physical_cores () protected
Return a tuple (number of physical cores, exception)
If the number of physical cores is found, exception is set to None.
If it has not been found, return ("not found", exception).
The number of physical cores is cached to avoid repeating subprocess calls.
Definition at line 227 of file context.py.
Referenced by cpu_count().
_count_physical_cores_darwin()
joblib.externals.loky.backend.context._count_physical_cores_darwin () protected
Definition at line 311 of file context.py.
_count_physical_cores_linux()
joblib.externals.loky.backend.context._count_physical_cores_linux () protected
Definition at line 267 of file context.py.
_count_physical_cores_win32()
joblib.externals.loky.backend.context._count_physical_cores_win32 () protected
Definition at line 286 of file context.py.
_cpu_count_affinity()
joblib.externals.loky.backend.context._cpu_count_affinity (os_cpu_count) protected
Definition at line 179 of file context.py.
_cpu_count_cgroup()
joblib.externals.loky.backend.context._cpu_count_cgroup (os_cpu_count) protected
Definition at line 143 of file context.py.
_cpu_count_user()
joblib.externals.loky.backend.context._cpu_count_user (os_cpu_count) protected
Number of user defined available CPUs
Definition at line 215 of file context.py.
Referenced by cpu_count().
cpu_count()
joblib.externals.loky.backend.context.cpu_count (only_physical_cores = False)
Return the number of CPUs the current process can use.
The returned number of CPUs accounts for:
 * the number of CPUs in the system, as given by
   ``multiprocessing.cpu_count``;
 * the CPU affinity settings of the current process
   (available on some Unix systems);
 * Cgroup CPU bandwidth limit (available on Linux only, typically
   set by docker and similar container orchestration systems);
 * the value of the LOKY_MAX_CPU_COUNT environment variable if defined.
and is given as the minimum of these constraints.
If ``only_physical_cores`` is True, return the number of physical cores
instead of the number of logical cores (hyperthreading / SMT). Note that
this option is not enforced if the number of usable cores is controlled in
any other way such as: process affinity, Cgroup restricted CPU bandwidth
or the LOKY_MAX_CPU_COUNT environment variable. If the number of physical
cores is not found, return the number of logical cores.
Note that on Windows, the returned number of CPUs cannot exceed 61 (or 60 for
Python < 3.10), see:
https://bugs.python.org/issue26903.
It is also always larger or equal to 1.
Definition at line 78 of file context.py.
References _count_physical_cores(), and _cpu_count_user().
get_context()
joblib.externals.loky.backend.context.get_context (method = None)
Definition at line 42 of file context.py.
get_start_method()
joblib.externals.loky.backend.context.get_start_method ()
Definition at line 74 of file context.py.
set_start_method()
joblib.externals.loky.backend.context.set_start_method (method, force = False)
Definition at line 62 of file context.py.
Variable Documentation
_DEFAULT_START_METHOD
joblib.externals.loky.backend.context._DEFAULT_START_METHOD = None protected
Definition at line 35 of file context.py.
_MAX_WINDOWS_WORKERS
int joblib.externals.loky.backend.context._MAX_WINDOWS_WORKERS = _MAX_WINDOWS_WORKERS - 1 protected
Definition at line 29 of file context.py.
ctx_loky
joblib.externals.loky.backend.context.ctx_loky = LokyContext()
Definition at line 403 of file context.py.
physical_cores_cache
joblib.externals.loky.backend.context.physical_cores_cache = None
Definition at line 39 of file context.py.
START_METHODS
list joblib.externals.loky.backend.context.START_METHODS = ["loky", "loky_init_main", "spawn"]
Definition at line 31 of file context.py.