Code Cloning Analysis: sklearn.mixture._gaussian_mixture Namespace Reference
sklearn.mixture._gaussian_mixture Namespace Reference
Classes
class GaussianMixture
Functions
_check_weights (weights, n_components)
Gaussian mixture shape checkers used by the GaussianMixture class.
_check_means (means, n_components, n_features)
_check_precision_positivity (precision, covariance_type)
_check_precision_matrix (precision, covariance_type)
_check_precisions_full (precisions, covariance_type)
_check_precisions (precisions, covariance_type, n_components, n_features)
_estimate_gaussian_covariances_full (resp, X, nk, means, reg_covar)
Gaussian mixture parameters estimators (used by the M-Step)
_estimate_gaussian_covariances_tied (resp, X, nk, means, reg_covar)
_estimate_gaussian_covariances_diag (resp, X, nk, means, reg_covar)
_estimate_gaussian_covariances_spherical (resp, X, nk, means, reg_covar)
_estimate_gaussian_parameters (X, resp, reg_covar, covariance_type)
_compute_precision_cholesky (covariances, covariance_type)
_flipudlr (array)
_compute_precision_cholesky_from_precisions (precisions, covariance_type)
_compute_log_det_cholesky (matrix_chol, covariance_type, n_features)
Gaussian mixture probability estimators.
_estimate_log_gaussian_prob (X, means, precisions_chol, covariance_type)
Detailed Description
Gaussian Mixture Model.
Function Documentation
_check_means()
sklearn.mixture._gaussian_mixture._check_means (means, n_components, n_features) protected
Validate the provided 'means'.
Parameters
----------
means : array-like of shape (n_components, n_features)
    The centers of the current components.
n_components : int
    Number of components.
n_features : int
    Number of features.
Returns
-------
means : array, (n_components, n_features)
Definition at line 54 of file _gaussian_mixture.py.
Referenced by sklearn.mixture._gaussian_mixture.GaussianMixture._check_parameters().
_check_precision_matrix()
sklearn.mixture._gaussian_mixture._check_precision_matrix (precision, covariance_type) protected
Check a precision matrix is symmetric and positive-definite.
Definition at line 83 of file _gaussian_mixture.py.
Referenced by _check_precisions_full().
_check_precision_positivity()
sklearn.mixture._gaussian_mixture._check_precision_positivity (precision, covariance_type) protected
Check a precision vector is positive-definite.
Definition at line 77 of file _gaussian_mixture.py.
_check_precisions()
sklearn.mixture._gaussian_mixture._check_precisions (precisions, covariance_type, n_components, n_features) protected
Validate user provided precisions.
Parameters
----------
precisions : array-like
    'full' : shape of (n_components, n_features, n_features)
    'tied' : shape of (n_features, n_features)
    'diag' : shape of (n_components, n_features)
    'spherical' : shape of (n_components,)
covariance_type : str
n_components : int
    Number of components.
n_features : int
    Number of features.
Returns
-------
precisions : array
Definition at line 99 of file _gaussian_mixture.py.
Referenced by sklearn.mixture._gaussian_mixture.GaussianMixture._check_parameters().
_check_precisions_full()
sklearn.mixture._gaussian_mixture._check_precisions_full (precisions, covariance_type) protected
Check the precision matrices are symmetric and positive-definite.
Definition at line 93 of file _gaussian_mixture.py.
References _check_precision_matrix().
_check_weights()
sklearn.mixture._gaussian_mixture._check_weights (weights, n_components) protected
Gaussian mixture shape checkers used by the GaussianMixture class.
Check the user provided 'weights'.
Parameters
----------
weights : array-like of shape (n_components,)
    The proportions of components of each mixture.
n_components : int
    Number of components.
Returns
-------
weights : array, shape (n_components,)
Definition at line 18 of file _gaussian_mixture.py.
Referenced by sklearn.mixture._gaussian_mixture.GaussianMixture._check_parameters().
_compute_log_det_cholesky()
sklearn.mixture._gaussian_mixture._compute_log_det_cholesky (matrix_chol, covariance_type, n_features) protected
Gaussian mixture probability estimators.
Compute the log-det of the cholesky decomposition of matrices.
Parameters
----------
matrix_chol : array-like
    Cholesky decompositions of the matrices.
    'full' : shape of (n_components, n_features, n_features)
    'tied' : shape of (n_features, n_features)
    'diag' : shape of (n_components, n_features)
    'spherical' : shape of (n_components,)
covariance_type : {'full', 'tied', 'diag', 'spherical'}
n_features : int
    Number of features.
Returns
-------
log_det_precision_chol : array-like of shape (n_components,)
    The determinant of the precision matrix for each component.
Definition at line 413 of file _gaussian_mixture.py.
Referenced by _estimate_log_gaussian_prob().
_compute_precision_cholesky()
sklearn.mixture._gaussian_mixture._compute_precision_cholesky (covariances, covariance_type) protected
Compute the Cholesky decomposition of the precisions.
Parameters
----------
covariances : array-like
    The covariance matrix of the current components.
    The shape depends of the covariance_type.
covariance_type : {'full', 'tied', 'diag', 'spherical'}
    The type of precision matrices.
Returns
-------
precisions_cholesky : array-like
    The cholesky decomposition of sample precisions of the current
    components. The shape depends of the covariance_type.
Definition at line 298 of file _gaussian_mixture.py.
Referenced by sklearn.mixture._gaussian_mixture.GaussianMixture._initialize(), and sklearn.mixture._gaussian_mixture.GaussianMixture._m_step().
_compute_precision_cholesky_from_precisions()
sklearn.mixture._gaussian_mixture._compute_precision_cholesky_from_precisions (precisions, covariance_type) protected
Compute the Cholesky decomposition of precisions using precisions themselves.
As implemented in :func:`_compute_precision_cholesky`, the `precisions_cholesky_` is
an upper-triangular matrix for each Gaussian component, which can be expressed as
the $UU^T$ factorization of the precision matrix for each Gaussian component, where
$U$ is an upper-triangular matrix.
In order to use the Cholesky decomposition to get $UU^T$, the precision matrix
$\Lambda$ needs to be permutated such that its rows and columns are reversed, which
can be done by applying a similarity transformation with an exchange matrix $J$,
where the 1 elements reside on the anti-diagonal and all other elements are 0. In
particular, the Cholesky decomposition of the transformed precision matrix is
$J\Lambda J=LL^T$, where $L$ is a lower-triangular matrix. Because $\Lambda=UU^T$
and $J=J^{-1}=J^T$, the `precisions_cholesky_` for each Gaussian component can be
expressed as $JLJ$.
Refer to #26415 for details.
Parameters
----------
precisions : array-like
    The precision matrix of the current components.
    The shape depends on the covariance_type.
covariance_type : {'full', 'tied', 'diag', 'spherical'}
    The type of precision matrices.
Returns
-------
precisions_cholesky : array-like
    The cholesky decomposition of sample precisions of the current
    components. The shape depends on the covariance_type.
Definition at line 361 of file _gaussian_mixture.py.
References _flipudlr().
Referenced by sklearn.mixture._gaussian_mixture.GaussianMixture._initialize().
_estimate_gaussian_covariances_diag()
sklearn.mixture._gaussian_mixture._estimate_gaussian_covariances_diag (resp, X, nk, means, reg_covar) protected
Estimate the diagonal covariance vectors.
Parameters
----------
responsibilities : array-like of shape (n_samples, n_components)
X : array-like of shape (n_samples, n_features)
nk : array-like of shape (n_components,)
means : array-like of shape (n_components, n_features)
reg_covar : float
Returns
-------
covariances : array, shape (n_components, n_features)
    The covariance vector of the current components.
Definition at line 210 of file _gaussian_mixture.py.
Referenced by _estimate_gaussian_covariances_spherical().
_estimate_gaussian_covariances_full()
sklearn.mixture._gaussian_mixture._estimate_gaussian_covariances_full (resp, X, nk, means, reg_covar) protected
Gaussian mixture parameters estimators (used by the M-Step)
Estimate the full covariance matrices.
Parameters
----------
resp : array-like of shape (n_samples, n_components)
X : array-like of shape (n_samples, n_features)
nk : array-like of shape (n_components,)
means : array-like of shape (n_components, n_features)
reg_covar : float
Returns
-------
covariances : array, shape (n_components, n_features, n_features)
    The covariance matrix of the current components.
Definition at line 153 of file _gaussian_mixture.py.
_estimate_gaussian_covariances_spherical()
sklearn.mixture._gaussian_mixture._estimate_gaussian_covariances_spherical (resp, X, nk, means, reg_covar) protected
Estimate the spherical variance values.
Parameters
----------
responsibilities : array-like of shape (n_samples, n_components)
X : array-like of shape (n_samples, n_features)
nk : array-like of shape (n_components,)
means : array-like of shape (n_components, n_features)
reg_covar : float
Returns
-------
variances : array, shape (n_components,)
    The variance values of each components.
Definition at line 235 of file _gaussian_mixture.py.
References _estimate_gaussian_covariances_diag().
_estimate_gaussian_covariances_tied()
sklearn.mixture._gaussian_mixture._estimate_gaussian_covariances_tied (resp, X, nk, means, reg_covar) protected
Estimate the tied covariance matrix.
Parameters
----------
resp : array-like of shape (n_samples, n_components)
X : array-like of shape (n_samples, n_features)
nk : array-like of shape (n_components,)
means : array-like of shape (n_components, n_features)
reg_covar : float
Returns
-------
covariance : array, shape (n_features, n_features)
    The tied covariance matrix of the components.
Definition at line 182 of file _gaussian_mixture.py.
_estimate_gaussian_parameters()
sklearn.mixture._gaussian_mixture._estimate_gaussian_parameters (X, resp, reg_covar, covariance_type) protected
Estimate the Gaussian distribution parameters.
Parameters
----------
X : array-like of shape (n_samples, n_features)
    The input data array.
resp : array-like of shape (n_samples, n_components)
    The responsibilities for each data sample in X.
reg_covar : float
    The regularization added to the diagonal of the covariance matrices.
covariance_type : {'full', 'tied', 'diag', 'spherical'}
    The type of precision matrices.
Returns
-------
nk : array-like of shape (n_components,)
    The numbers of data samples in the current components.
means : array-like of shape (n_components, n_features)
    The centers of the current components.
covariances : array-like
    The covariance matrix of the current components.
    The shape depends of the covariance_type.
Definition at line 258 of file _gaussian_mixture.py.
Referenced by sklearn.mixture._gaussian_mixture.GaussianMixture._initialize(), and sklearn.mixture._gaussian_mixture.GaussianMixture._m_step().
_estimate_log_gaussian_prob()
sklearn.mixture._gaussian_mixture._estimate_log_gaussian_prob (X, means, precisions_chol, covariance_type) protected
Estimate the log Gaussian probability.
Parameters
----------
X : array-like of shape (n_samples, n_features)
means : array-like of shape (n_components, n_features)
precisions_chol : array-like
    Cholesky decompositions of the precision matrices.
    'full' : shape of (n_components, n_features, n_features)
    'tied' : shape of (n_features, n_features)
    'diag' : shape of (n_components, n_features)
    'spherical' : shape of (n_components,)
covariance_type : {'full', 'tied', 'diag', 'spherical'}
Returns
-------
log_prob : array, shape (n_samples, n_components)
Definition at line 453 of file _gaussian_mixture.py.
References _compute_log_det_cholesky().
Referenced by sklearn.mixture._gaussian_mixture.GaussianMixture._estimate_log_prob().
_flipudlr()
sklearn.mixture._gaussian_mixture._flipudlr (array) protected
Reverse the rows and columns of an array.
Definition at line 356 of file _gaussian_mixture.py.
Referenced by _compute_precision_cholesky_from_precisions().