Code Cloning Analysis: fontTools.ttLib.tables._c_m_a_p.cmap_format_2 Class Reference
fontTools.ttLib.tables._c_m_a_p.cmap_format_2 Class Reference
Public Member Functions
setIDDelta (self, subHeader)
decompile (self, data, ttFont)
compile (self, ttFont)
fromXML (self, name, attrs, content, ttFont)
Public Member Functions inherited from fontTools.ttLib.tables._c_m_a_p.CmapSubtable
__init__ (self, format)
ensureDecompiled (self, recurse=False)
__getattr__ (self, attr)
decompileHeader (self, data, ttFont)
toXML (self, writer, ttFont)
getEncoding (self, default=None)
isUnicode (self)
isSymbol (self)
__lt__ (self, other)
Public Attributes
dict cmap = _make_map(self.ttFont, charCodes, gids)
Public Attributes inherited from fontTools.ttLib.tables._c_m_a_p.CmapSubtable
format = format
data = None
ttFont = None
int platformID = None
platEncID = None
tuple language
length = int(length)
Additional Inherited Members
Static Public Member Functions inherited from fontTools.ttLib.tables._c_m_a_p.CmapSubtable
getSubtableClass (format)
newSubtable (format)
Protected Member Functions inherited from fontTools.ttLib.tables._c_m_a_p.CmapSubtable
_writeCodes (self, codes, writer)
Detailed Description
Definition at line 444 of file _c_m_a_p.py.
Member Function Documentation
compile()
fontTools.ttLib.tables._c_m_a_p.cmap_format_2.compile (self, ttFont)
Definition at line 592 of file _c_m_a_p.py.
Referenced by fontTools.ttLib.tables.TupleVariation.TupleVariation.getCoordWidth(), and PIL.FontFile.FontFile.save().
decompile()
fontTools.ttLib.tables._c_m_a_p.cmap_format_2.decompile (self, data, ttFont)
Definition at line 473 of file _c_m_a_p.py.
Referenced by fontTools.ttLib.tables._c_m_a_p.CmapSubtable.newSubtable().
fromXML()
fontTools.ttLib.tables._c_m_a_p.cmap_format_2.fromXML (self, name, attrs, content, ttFont)
Definition at line 771 of file _c_m_a_p.py.
setIDDelta()
fontTools.ttLib.tables._c_m_a_p.cmap_format_2.setIDDelta (self, subHeader)
Definition at line 445 of file _c_m_a_p.py.
Member Data Documentation
cmap
dict fontTools.ttLib.tables._c_m_a_p.cmap_format_2.cmap = _make_map(self.ttFont, charCodes, gids)
Definition at line 590 of file _c_m_a_p.py.
Referenced by matplotlib.colorbar.Colorbar.__init__(), matplotlib.colorbar.Colorbar._add_solids(), matplotlib.colorbar.Colorbar._do_extends(), matplotlib.contour.ContourSet._process_colors(), matplotlib.colorbar.Colorbar._process_values(), matplotlib.colorizer._ColorizerInterface.colorbar(), matplotlib.collections.PathCollection.legend_elements(), fontTools.ttLib.tables._c_m_a_p.CmapSubtable.newSubtable(), matplotlib.colorizer._ColorizerInterface.set_cmap(), matplotlib.colorizer.Colorizer.to_rgba(), matplotlib.collections.Collection.update_from(), and matplotlib.colorbar.Colorbar.update_normal().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ttLib/tables/_c_m_a_p.py