Code Cloning Analysis: matplotlib._api.classproperty Class Reference
matplotlib._api.classproperty Class Reference
Public Member Functions
__init__ (self, fget, fset=None, fdel=None, doc=None)
__get__ (self, instance, owner)
fget (self)
Public Attributes
fset = fset
fdel = fdel
Protected Attributes
_fget = fget
_doc = doc
Detailed Description
Like `property`, but also triggers on access via the class, and it is the
*class* that's passed as argument.
Examples
--------
::
    class C:
        @classproperty
        def foo(cls):
            return cls.__name__
    assert C.foo == "C"
Definition at line 28 of file __init__.py.
Constructor & Destructor Documentation
__init__()
matplotlib._api.classproperty.__init__ (self, fget, fset = None, fdel = None, doc = None)
Definition at line 45 of file __init__.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__get__()
matplotlib._api.classproperty.__get__ (self, instance, owner)
Definition at line 54 of file __init__.py.
fget()
matplotlib._api.classproperty.fget (self)
Definition at line 58 of file __init__.py.
Member Data Documentation
_doc
matplotlib._api.classproperty._doc = doc protected
Definition at line 52 of file __init__.py.
Referenced by scipy._lib._docscrape.NumpyDocString._parse_summary().
_fget
matplotlib._api.classproperty._fget = fget protected
Definition at line 46 of file __init__.py.
fdel
matplotlib._api.classproperty.fdel = fdel
Definition at line 50 of file __init__.py.
fset
matplotlib._api.classproperty.fset = fset
Definition at line 49 of file __init__.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/_api/__init__.py