Code Cloning Analysis: numpy.lib._datasource.Repository Class Reference
numpy.lib._datasource.Repository Class Reference
Public Member Functions
__init__ (self, baseurl, destpath=os.curdir)
__del__ (self)
abspath (self, path)
exists (self, path)
open (self, path, mode='r', encoding=None, newline=None)
listdir (self)
Public Member Functions inherited from numpy.lib._datasource.DataSource
__init__ (self, destpath=os.curdir)
__del__ (self)
Protected Member Functions
_fullpath (self, path)
_findfile (self, path)
Protected Member Functions inherited from numpy.lib._datasource.DataSource
_iszip (self, filename)
_iswritemode (self, mode)
_splitzipext (self, filename)
_possible_names (self, filename)
_isurl (self, path)
_cache (self, path)
_sanitize_relative_path (self, path)
Protected Attributes
_baseurl = baseurl
Protected Attributes inherited from numpy.lib._datasource.DataSource
_destpath = os.path.abspath(destpath)
bool _istmpdest = False
Detailed Description
Repository(baseurl, destpath='.')
A data repository where multiple DataSource's share a base
URL/directory.
`Repository` extends `DataSource` by prepending a base URL (or
directory) to all the files it handles. Use `Repository` when you will
be working with multiple files from one base URL.  Initialize
`Repository` with the base URL, then refer to each file by its filename
only.
Parameters
----------
baseurl : str
    Path to the local directory or remote location that contains the
    data files.
destpath : str or None, optional
    Path to the directory where the source file gets downloaded to for
    use.  If `destpath` is None, a temporary directory will be created.
    The default path is the current directory.
Examples
--------
To analyze all files in the repository, do something like this
(note: this is not self-contained code)::
    >>> repos = np.lib._datasource.Repository('/home/user/data/dir/')
    >>> for filename in filelist:
    ...     fp = repos.open(filename)
    ...     fp.analyze()
    ...     fp.close()
Similarly you could use a URL for a repository::
    >>> repos = np.lib._datasource.Repository('http://www.xyz.edu/data')
Definition at line 536 of file _datasource.py.
Constructor & Destructor Documentation
__init__()
numpy.lib._datasource.Repository.__init__ (self, baseurl, destpath = os.curdir)
Create a Repository with a shared url or directory of baseurl.
Definition at line 576 of file _datasource.py.
References _baseurl.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
__del__()
numpy.lib._datasource.Repository.__del__ (self)
Definition at line 581 of file _datasource.py.
Member Function Documentation
_findfile()
numpy.lib._datasource.Repository._findfile (self, path) protected
Extend DataSource method to prepend baseurl to ``path``.
Reimplemented from numpy.lib._datasource.DataSource.
Definition at line 593 of file _datasource.py.
References _fullpath().
_fullpath()
numpy.lib._datasource.Repository._fullpath (self, path) protected
Return complete path for path.  Prepends baseurl if necessary.
Definition at line 584 of file _datasource.py.
References _baseurl.
Referenced by _findfile(), abspath(), exists(), and open().
abspath()
numpy.lib._datasource.Repository.abspath (self, path)
Return absolute path of file in the Repository directory.
If `path` is an URL, then `abspath` will return either the location
the file exists locally or the location it would exist when opened
using the `open` method.
Parameters
----------
path : str
    Can be a local file or a remote URL. This may, but does not
    have to, include the `baseurl` with which the `Repository` was
    initialized.
Returns
-------
out : str
    Complete path, including the `DataSource` destination directory.
Reimplemented from numpy.lib._datasource.DataSource.
Definition at line 597 of file _datasource.py.
References _fullpath().
exists()
numpy.lib._datasource.Repository.exists (self, path)
Test if path exists prepending Repository base URL to path.
Test if `path` exists as (and in this order):
- a local file.
- a remote URL that has been downloaded and stored locally in the
  `DataSource` directory.
- a remote URL that has not been downloaded, but is valid and
  accessible.
Parameters
----------
path : str
    Can be a local file or a remote URL. This may, but does not
    have to, include the `baseurl` with which the `Repository` was
    initialized.
Returns
-------
out : bool
    True if `path` exists.
Notes
-----
When `path` is an URL, `exists` will return True if it's either
stored locally in the `DataSource` directory, or is a valid remote
URL.  `DataSource` does not discriminate between the two, the file
is accessible if it exists in either location.
Reimplemented from numpy.lib._datasource.DataSource.
Definition at line 620 of file _datasource.py.
References _fullpath().
listdir()
numpy.lib._datasource.Repository.listdir (self)
List files in the source Repository.
Returns
-------
files : list of str
    List of file names (not containing a directory part).
Notes
-----
Does not currently work for remote repositories.
Definition at line 686 of file _datasource.py.
References _baseurl, and numpy.lib._datasource.DataSource._isurl().
open()
numpy.lib._datasource.Repository.open (self, path, mode = 'r', encoding = None, newline = None)
Open and return file-like object prepending Repository base URL.
If `path` is an URL, it will be downloaded, stored in the
DataSource directory and opened from there.
Parameters
----------
path : str
    Local file path or URL to open. This may, but does not have to,
    include the `baseurl` with which the `Repository` was
    initialized.
mode : {'r', 'w', 'a'}, optional
    Mode to open `path`.  Mode 'r' for reading, 'w' for writing,
    'a' to append. Available modes depend on the type of object
    specified by `path`. Default is 'r'.
encoding : {None, str}, optional
    Open text file with given encoding. The default encoding will be
    what `io.open` uses.
newline : {None, str}, optional
    Newline to use when reading text file.
Returns
-------
out : file object
    File object.
Reimplemented from numpy.lib._datasource.DataSource.
Definition at line 654 of file _datasource.py.
References _fullpath().
Member Data Documentation
_baseurl
numpy.lib._datasource.Repository._baseurl = baseurl protected
Definition at line 579 of file _datasource.py.
Referenced by __init__(), _fullpath(), and listdir().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/lib/_datasource.py