Code Cloning Analysis: matplotlib.sphinxext.mathmpl.MathDirective Class Reference
matplotlib.sphinxext.mathmpl.MathDirective Class Reference
Public Member Functions
run (self)
Static Public Attributes
bool has_content = True
int required_arguments = 0
int optional_arguments = 0
bool final_argument_whitespace = False
dict option_spec
Detailed Description
The ``.. mathmpl::`` directive, as documented in the module's docstring.
Definition at line 109 of file mathmpl.py.
Member Function Documentation
run()
matplotlib.sphinxext.mathmpl.MathDirective.run (self)
Definition at line 120 of file mathmpl.py.
Referenced by scipy.odr._odrpack.ODR.restart(), scipy.integrate._ode.lsoda.run_relax(), scipy.integrate._ode.vode.run_relax(), scipy.integrate._ode.lsoda.step(), and scipy.integrate._ode.vode.step().
Member Data Documentation
final_argument_whitespace
bool matplotlib.sphinxext.mathmpl.MathDirective.final_argument_whitespace = False static
Definition at line 116 of file mathmpl.py.
has_content
bool matplotlib.sphinxext.mathmpl.MathDirective.has_content = True static
Definition at line 113 of file mathmpl.py.
option_spec
dict matplotlib.sphinxext.mathmpl.MathDirective.option_spec static
Initial value:
=  {'fontset': fontset_choice,
                   'fontsize': validate_float_or_None}
Definition at line 117 of file mathmpl.py.
optional_arguments
int matplotlib.sphinxext.mathmpl.MathDirective.optional_arguments = 0 static
Definition at line 115 of file mathmpl.py.
required_arguments
int matplotlib.sphinxext.mathmpl.MathDirective.required_arguments = 0 static
Definition at line 114 of file mathmpl.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/sphinxext/mathmpl.py