Code Cloning Analysis: fontTools.ttLib.ttVisitor.TTVisitor Class Reference
fontTools.ttLib.ttVisitor.TTVisitor Class Reference
Public Member Functions
visitAttr (self, obj, attr, value, *args, **kwargs)
visit (self, obj, *args, **kwargs)
Public Member Functions inherited from fontTools.misc.visitor.Visitor
register (celf, clazzes)
register_attr (celf, clazzes, attrs)
register_attrs (celf, clazzes_attrs)
visitObject (self, obj, *args, **kwargs)
visitList (self, obj, *args, **kwargs)
visitDict (self, obj, *args, **kwargs)
visitLeaf (self, obj, *args, **kwargs)
Additional Inherited Members
Static Public Attributes inherited from fontTools.misc.visitor.Visitor
bool defaultStop = False
Protected Member Functions inherited from fontTools.misc.visitor.Visitor
_register (celf, clazzes_attrs)
_visitorsFor (celf, thing, _default={})
Static Protected Attributes inherited from fontTools.misc.visitor.Visitor
dict _visitors
Detailed Description
Definition at line 7 of file ttVisitor.py.
Member Function Documentation
visit()
fontTools.ttLib.ttVisitor.TTVisitor.visit (self, obj, * args, ** kwargs)
This is the main entry to the visitor. The visitor will visit object
obj.
The visitor will first determine if there is a registered (via
@register()) visit function for the type of object. If there is, it
will be called, and (visitor, obj, *args, **kwargs) will be passed to
the user visit function.
If there is no user-registered visit function, of if there is and it
returns True, or it returns None (or doesn't return anything) and
visitor.defaultStop is False (default), then the visitor will proceed
to dispatch to one of self.visitObject(), self.visitList(),
self.visitDict(), or self.visitLeaf() (any of which can be overriden in
a subclass).
Reimplemented from fontTools.misc.visitor.Visitor.
Definition at line 13 of file ttVisitor.py.
References visit().
Referenced by visit(), pandas.core.computation.expr.BaseExprVisitor.visit_Assign(), pandas.core.computation.expr.BaseExprVisitor.visit_Index(), and pandas.core.computation.expr.BaseExprVisitor.visit_Slice().
visitAttr()
fontTools.ttLib.ttVisitor.TTVisitor.visitAttr (self, obj, attr, value, * args, ** kwargs)
Called to visit an attribute of an object.
Reimplemented from fontTools.misc.visitor.Visitor.
Definition at line 8 of file ttVisitor.py.
References visitAttr().
Referenced by visitAttr().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ttLib/ttVisitor.py