Code Cloning Analysis: scipy.sparse._sputils Namespace Reference
scipy.sparse._sputils Namespace Reference
Functions
upcast (*args)
upcast_char (*args)
upcast_scalar (dtype, scalar)
downcast_intp_index (arr)
to_native (A)
getdtype (dtype, a=None, default=None)
np.ndarray getdata (obj, dtype=None, copy=False)
get_index_dtype (arrays=(), maxval=None, check_contents=False)
get_sum_dtype (dtype)
bool isscalarlike (x)
bool isintlike (x)
bool isshape (x, nonneg=False, allow_ndim=False)
bool issequence (t)
bool ismatrix (t)
bool isdense (x)
None validateaxis (axis)
check_shape (args, current_shape=None)
check_reshape_kwargs (kwargs)
bool is_pydata_spmatrix (m)
matrix (*args, **kwargs)
Wrappers for NumPy types that are deprecated.
asmatrix (data, dtype=None)
np.ndarray _todata (s)
Variables
list __all__
list supported_dtypes
dict _upcast_memo = {}
Detailed Description
 Utility functions for sparse matrix module
Function Documentation
_todata()
np.ndarray scipy.sparse._sputils._todata (s) protected
Access nonzero values, possibly after summing duplicates.
Parameters
----------
s : sparse array
    Input sparse array.
Returns
-------
data: ndarray
  Nonzero values of the array, with shape (s.nnz,)
Definition at line 386 of file _sputils.py.
asmatrix()
scipy.sparse._sputils.asmatrix (data, dtype = None)
Definition at line 378 of file _sputils.py.
check_reshape_kwargs()
scipy.sparse._sputils.check_reshape_kwargs (kwargs)
Unpack keyword arguments for reshape function.
This is useful because keyword arguments after star arguments are not
allowed in Python 2, but star keyword arguments are. This function unpacks
'order' and 'copy' from the star keyword arguments (with defaults) and
throws an error for any remaining.
Definition at line 343 of file _sputils.py.
check_shape()
scipy.sparse._sputils.check_shape (args, current_shape = None)
Imitate numpy.matrix handling of shape arguments
Definition at line 294 of file _sputils.py.
downcast_intp_index()
scipy.sparse._sputils.downcast_intp_index (arr)
Down-cast index array to np.intp dtype if it is of a larger dtype.
Raise an error if the array contains a value that is too large for
intp.
Definition at line 73 of file _sputils.py.
get_index_dtype()
scipy.sparse._sputils.get_index_dtype (arrays = (), maxval = None, check_contents = False)
Based on input (integer) arrays `a`, determine a suitable index data
type that can hold the data in the arrays.
Parameters
----------
arrays : tuple of array_like
    Input arrays whose types/contents to check
maxval : float, optional
    Maximum value needed
check_contents : bool, optional
    Whether to check the values in the arrays and not just their types.
    Default: False (check only the types)
Returns
-------
dtype : dtype
    Suitable index data type (int32 or int64)
Definition at line 147 of file _sputils.py.
get_sum_dtype()
scipy.sparse._sputils.get_sum_dtype (dtype)
Mimic numpy's casting for np.sum
Definition at line 202 of file _sputils.py.
getdata()
np.ndarray scipy.sparse._sputils.getdata (obj, dtype = None, copy = False)
This is a wrapper of `np.array(obj, dtype=dtype, copy=copy)`
that will generate a warning if the result is an object array.
Definition at line 135 of file _sputils.py.
References getdtype().
getdtype()
scipy.sparse._sputils.getdtype (dtype, a = None, default = None)
Function used to simplify argument processing. If 'dtype' is not
specified (is None), returns a.dtype; otherwise returns a np.dtype
object created from the specified dtype argument. If 'dtype' and 'a'
are both None, construct a data type out of the 'default' parameter.
Furthermore, 'dtype' must be in 'allowed' set.
Definition at line 109 of file _sputils.py.
Referenced by getdata().
is_pydata_spmatrix()
bool scipy.sparse._sputils.is_pydata_spmatrix (m)
Check whether object is pydata/sparse matrix, avoiding importing the module.
Definition at line 360 of file _sputils.py.
isdense()
bool scipy.sparse._sputils.isdense (x)
Definition at line 267 of file _sputils.py.
isintlike()
bool scipy.sparse._sputils.isintlike (x)
Is x appropriate as an index into a sparse matrix? Returns True
if it can be cast safely to a machine int.
Definition at line 216 of file _sputils.py.
Referenced by isshape().
ismatrix()
bool scipy.sparse._sputils.ismatrix (t)
Definition at line 261 of file _sputils.py.
isscalarlike()
bool scipy.sparse._sputils.isscalarlike (x)
Is x either a scalar, an array scalar, or a 0-dim array?
Definition at line 211 of file _sputils.py.
issequence()
bool scipy.sparse._sputils.issequence (t)
Definition at line 255 of file _sputils.py.
isshape()
bool scipy.sparse._sputils.isshape (x, nonneg = False, allow_ndim = False)
Is x a valid tuple of dimensions?
If nonneg, also checks that the dimensions are non-negative.
If allow_ndim, shapes of any dimensionality are allowed.
Definition at line 238 of file _sputils.py.
References isintlike().
matrix()
scipy.sparse._sputils.matrix (* args, ** kwargs)
Wrappers for NumPy types that are deprecated.
Definition at line 374 of file _sputils.py.
to_native()
scipy.sparse._sputils.to_native (A)
Ensure that the data type of the NumPy array `A` has native byte order.
`A` must be a NumPy array.  If the data type of `A` does not have native
byte order, a copy of `A` with a native byte order is returned. Otherwise
`A` is returned.
Definition at line 93 of file _sputils.py.
upcast()
scipy.sparse._sputils.upcast (* args)
Returns the nearest supported sparse dtype for the
combination of one or more types.
upcast(t0, t1, ..., tn) -> T  where T is a supported dtype
Examples
--------
>>> upcast('int32')
<type 'numpy.int32'>
>>> upcast('bool')
<type 'numpy.bool_'>
>>> upcast('int32','float32')
<type 'numpy.float64'>
>>> upcast('bool',complex,float)
<type 'numpy.complex128'>
Definition at line 22 of file _sputils.py.
Referenced by upcast_char().
upcast_char()
scipy.sparse._sputils.upcast_char (* args)
Same as `upcast` but taking dtype.char as input (faster).
Definition at line 56 of file _sputils.py.
References upcast().
upcast_scalar()
scipy.sparse._sputils.upcast_scalar (dtype, scalar)
Determine data type for binary operation between an array of
type `dtype` and a scalar.
Definition at line 66 of file _sputils.py.
validateaxis()
None scipy.sparse._sputils.validateaxis (axis)
Definition at line 271 of file _sputils.py.
Variable Documentation
__all__
list scipy.sparse._sputils.__all__ private
Initial value:
=  ['upcast', 'getdtype', 'getdata', 'isscalarlike', 'isintlike',
           'isshape', 'issequence', 'isdense', 'ismatrix', 'get_sum_dtype']
Definition at line 11 of file _sputils.py.
_upcast_memo
dict scipy.sparse._sputils._upcast_memo = {} protected
Definition at line 19 of file _sputils.py.
supported_dtypes
list scipy.sparse._sputils.supported_dtypes
Initial value:
=  [np.bool_, np.byte, np.ubyte, np.short, np.ushort, np.intc,
                    np.uintc, np.int_, np.uint, np.longlong, np.ulonglong,
                    np.single, np.double,
                    np.longdouble, np.csingle, np.cdouble, np.clongdouble]
Definition at line 14 of file _sputils.py.