Code Cloning Analysis: axes_grid1.axes_size.MaxHeight Class Reference
axes_grid1.axes_size.MaxHeight Class Reference
Public Member Functions
__init__ (self, artist_list)
Public Member Functions inherited from axes_grid1.axes_size.MaxExtent
__init__ (self, artist_list, w_or_h)
add_artist (self, a)
get_size (self, renderer)
Public Member Functions inherited from axes_grid1.axes_size._Base
__rmul__ (self, other)
__mul__ (self, other)
__div__ (self, other)
__add__ (self, other)
__neg__ (self)
__radd__ (self, other)
__sub__ (self, other)
Additional Inherited Members
Protected Attributes inherited from axes_grid1.axes_size.MaxExtent
_artist_list = artist_list
_w_or_h = w_or_h
Detailed Description
Size whose absolute part is the largest height of the given *artist_list*.
Definition at line 197 of file axes_size.py.
Constructor & Destructor Documentation
__init__()
axes_grid1.axes_size.MaxHeight.__init__ (self, artist_list)
Definition at line 202 of file axes_size.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/mpl_toolkits/axes_grid1/axes_size.py