Code Cloning Analysis: joblib.pool.MemmappingPool Class Reference
joblib.pool.MemmappingPool Class Reference
Public Member Functions
__init__ (self, processes=None, temp_folder=None, max_nbytes=1e6, mmap_mode="r", forward_reducers=None, backward_reducers=None, verbose=0, prewarm=False, **kwargs)
terminate (self)
Public Member Functions inherited from joblib.pool.PicklingPool
__init__ (self, processes=None, forward_reducers=None, backward_reducers=None, **kwargs)
Protected Member Functions
_temp_folder (self)
Protected Member Functions inherited from joblib.pool.PicklingPool
_setup_queues (self)
Protected Attributes
_temp_folder_manager = manager
tuple _cached_temp_folder
Protected Attributes inherited from joblib.pool.PicklingPool
_forward_reducers = forward_reducers
_backward_reducers = backward_reducers
_inqueue = CustomizablePicklingQueue(context, self._forward_reducers)
_outqueue = CustomizablePicklingQueue(context, self._backward_reducers)
_quick_put = self._inqueue._send
_quick_get = self._outqueue._recv
Detailed Description
Process pool that shares large arrays to avoid memory copy.
This drop-in replacement for `multiprocessing.pool.Pool` makes
it possible to work efficiently with shared memory in a numpy
context.
Existing instances of numpy.memmap are preserved: the child
suprocesses will have access to the same shared memory in the
original mode except for the 'w+' mode that is automatically
transformed as 'r+' to avoid zeroing the original data upon
instantiation.
Furthermore large arrays from the parent process are automatically
dumped to a temporary folder on the filesystem such as child
processes to access their content via memmapping (file system
backed shared memory).
Note: it is important to call the terminate method to collect
the temporary folder used by the pool.
Parameters
----------
processes: int, optional
    Number of worker processes running concurrently in the pool.
initializer: callable, optional
    Callable executed on worker process creation.
initargs: tuple, optional
    Arguments passed to the initializer callable.
temp_folder: (str, callable) optional
    If str:
      Folder to be used by the pool for memmapping large arrays
      for sharing memory with worker processes. If None, this will try in
      order:
      - a folder pointed by the JOBLIB_TEMP_FOLDER environment variable,
      - /dev/shm if the folder exists and is writable: this is a RAMdisk
        filesystem available by default on modern Linux distributions,
      - the default system temporary folder that can be overridden
        with TMP, TMPDIR or TEMP environment variables, typically /tmp
        under Unix operating systems.
    if callable:
        An callable in charge of dynamically resolving a temporary folder
        for memmapping large arrays.
max_nbytes int or None, optional, 1e6 by default
    Threshold on the size of arrays passed to the workers that
    triggers automated memory mapping in temp_folder.
    Use None to disable memmapping of large arrays.
mmap_mode: {'r+', 'r', 'w+', 'c'}
    Memmapping mode for numpy arrays passed to workers.
    See 'max_nbytes' parameter documentation for more details.
forward_reducers: dictionary, optional
    Reducers used to pickle objects passed from main process to worker
    processes: see below.
backward_reducers: dictionary, optional
    Reducers used to pickle return values from workers back to the
    main process.
verbose: int, optional
    Make it possible to monitor how the communication of numpy arrays
    with the subprocess is handled (pickling or memmapping)
prewarm: bool or str, optional, "auto" by default.
    If True, force a read on newly memmapped array to make sure that OS
    pre-cache it in memory. This can be useful to avoid concurrent disk
    access when the same data array is passed to different worker
    processes. If "auto" (by default), prewarm is set to True, unless the
    Linux shared memory partition /dev/shm is available and used as temp
    folder.
`forward_reducers` and `backward_reducers` are expected to be
dictionaries with key/values being `(type, callable)` pairs where
`callable` is a function that give an instance of `type` will return
a tuple `(constructor, tuple_of_objects)` to rebuild an instance out
of the pickled `tuple_of_objects` as would return a `__reduce__`
method. See the standard library documentation on pickling for more
details.
Definition at line 214 of file pool.py.
Constructor & Destructor Documentation
__init__()
joblib.pool.MemmappingPool.__init__ (self, processes = None, temp_folder = None, max_nbytes = 1e6, mmap_mode = "r", forward_reducers = None, backward_reducers = None, verbose = 0, prewarm = False, ** kwargs)
Definition at line 291 of file pool.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_temp_folder()
joblib.pool.MemmappingPool._temp_folder (self) protected
Definition at line 350 of file pool.py.
terminate()
joblib.pool.MemmappingPool.terminate (self)
Definition at line 329 of file pool.py.
Member Data Documentation
_cached_temp_folder
tuple joblib.pool.MemmappingPool._cached_temp_folder protected
Initial value:
=  (
                self._temp_folder_manager.resolve_temp_folder_name()
            )
Definition at line 359 of file pool.py.
_temp_folder_manager
joblib.pool.MemmappingPool._temp_folder_manager = manager protected
Definition at line 304 of file pool.py.
Referenced by joblib.executor.MemmappingExecutor.get_memmapping_executor().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/joblib/pool.py