Code Cloning Analysis: sklearn.utils.tests.test_estimator_checks.TaggedBinaryClassifier Class Reference
sklearn.utils.tests.test_estimator_checks.TaggedBinaryClassifier Class Reference
Public Member Functions
fit (self, X, y)
__sklearn_tags__ (self)
Public Member Functions inherited from sklearn.utils.tests.test_estimator_checks.UntaggedBinaryClassifier
partial_fit (self, X, y, classes=None, sample_weight=None)
Public Member Functions inherited from sklearn.linear_model._stochastic_gradient.SGDClassifier
__init__ (self, loss="hinge", *, penalty="l2", alpha=0.0001, l1_ratio=0.15, fit_intercept=True, max_iter=1000, tol=1e-3, shuffle=True, verbose=0, epsilon=DEFAULT_EPSILON, n_jobs=None, random_state=None, learning_rate="optimal", eta0=0.0, power_t=0.5, early_stopping=False, validation_fraction=0.1, n_iter_no_change=5, class_weight=None, warm_start=False, average=False)
predict_proba (self, X)
predict_log_proba (self, X)
Public Member Functions inherited from sklearn.linear_model._stochastic_gradient.BaseSGDClassifier
__init__ (self, loss="hinge", *, penalty="l2", alpha=0.0001, l1_ratio=0.15, fit_intercept=True, max_iter=1000, tol=1e-3, shuffle=True, verbose=0, epsilon=DEFAULT_EPSILON, n_jobs=None, random_state=None, learning_rate="optimal", eta0=0.0, power_t=0.5, early_stopping=False, validation_fraction=0.1, n_iter_no_change=5, class_weight=None, warm_start=False, average=False)
__sklearn_tags__ (self)
Public Member Functions inherited from sklearn.linear_model._base.LinearClassifierMixin
decision_function (self, X)
predict (self, X)
Public Member Functions inherited from sklearn.base.ClassifierMixin
__sklearn_tags__ (self)
score (self, X, y, sample_weight=None)
Public Member Functions inherited from sklearn.linear_model._stochastic_gradient.BaseSGD
__init__ (self, loss, *, penalty="l2", alpha=0.0001, C=1.0, l1_ratio=0.15, fit_intercept=True, max_iter=1000, tol=1e-3, shuffle=True, verbose=0, epsilon=0.1, random_state=None, learning_rate="optimal", eta0=0.0, power_t=0.5, early_stopping=False, validation_fraction=0.1, n_iter_no_change=5, warm_start=False, average=False)
Public Member Functions inherited from sklearn.linear_model._base.SparseCoefMixin
densify (self)
sparsify (self)
Public Member Functions inherited from sklearn.base.BaseEstimator
get_params (self, deep=True)
set_params (self, **params)
__sklearn_clone__ (self)
__repr__ (self, N_CHAR_MAX=700)
__getstate__ (self)
__setstate__ (self, state)
__sklearn_tags__ (self)
Public Member Functions inherited from sklearn.utils._metadata_requests._MetadataRequester
set_fit_request (self, **kwargs)
set_partial_fit_request (self, **kwargs)
set_predict_request (self, **kwargs)
set_predict_proba_request (self, **kwargs)
set_predict_log_proba_request (self, **kwargs)
set_decision_function_request (self, **kwargs)
set_score_request (self, **kwargs)
set_split_request (self, **kwargs)
set_transform_request (self, **kwargs)
set_inverse_transform_request (self, **kwargs)
__init_subclass__ (cls, **kwargs)
get_metadata_routing (self)
Additional Inherited Members
Public Attributes inherited from sklearn.linear_model._stochastic_gradient.BaseSGDClassifier
str class_weight = class_weight
n_jobs = n_jobs
float t_ = 1.0
n_iter_ = self.max_iter
Public Attributes inherited from sklearn.linear_model._base.LinearClassifierMixin
classes_
Public Attributes inherited from sklearn.linear_model._stochastic_gradient.BaseSGD
loss = loss
str penalty = penalty
str learning_rate = learning_rate
epsilon = epsilon
alpha = alpha
C = C
l1_ratio = l1_ratio
fit_intercept = fit_intercept
shuffle = shuffle
random_state = random_state
verbose = verbose
eta0 = eta0
power_t = power_t
early_stopping = early_stopping
validation_fraction = validation_fraction
n_iter_no_change = n_iter_no_change
warm_start = warm_start
average = average
max_iter = max_iter
tol = tol
intercept_ = intercept_init
offset_
Public Attributes inherited from sklearn.linear_model._base.SparseCoefMixin
coef_
Static Public Attributes inherited from sklearn.linear_model._stochastic_gradient.BaseSGDClassifier
dict loss_functions
Protected Member Functions inherited from sklearn.linear_model._stochastic_gradient.SGDClassifier
_check_proba (self)
Protected Member Functions inherited from sklearn.linear_model._stochastic_gradient.BaseSGDClassifier
_partial_fit (self, X, y, alpha, C, loss, learning_rate, max_iter, classes, sample_weight, coef_init, intercept_init)
_fit (self, X, y, alpha, C, loss, learning_rate, coef_init=None, intercept_init=None, sample_weight=None)
_fit_binary (self, X, y, alpha, C, sample_weight, learning_rate, max_iter)
_fit_multiclass (self, X, y, alpha, C, learning_rate, sample_weight, max_iter)
Protected Member Functions inherited from sklearn.linear_model._base.LinearClassifierMixin
_predict_proba_lr (self, X)
Protected Member Functions inherited from sklearn.linear_model._stochastic_gradient.BaseSGD
_more_validate_params (self, for_partial_fit=False)
_get_l1_ratio (self)
_get_loss_function (self, loss)
_get_learning_rate_type (self, learning_rate)
_get_penalty_type (self, penalty)
_allocate_parameter_mem (self, n_classes, n_features, input_dtype, coef_init=None, intercept_init=None, one_class=0)
_make_validation_split (self, y, sample_mask)
_make_validation_score_cb (self, validation_mask, X, y, sample_weight, classes=None)
Protected Member Functions inherited from sklearn.base.BaseEstimator
_get_param_names (cls)
_get_params_html (self, deep=True)
_validate_params (self)
Protected Member Functions inherited from sklearn.utils._repr_html.base.ReprHTMLMixin
_repr_html_ (self)
_repr_html_inner (self)
_repr_mimebundle_ (self, **kwargs)
Protected Member Functions inherited from sklearn.utils._repr_html.base._HTMLDocumentationLinkMixin
_doc_link_template (self)
_doc_link_template (self, value)
_get_doc_link (self)
Protected Member Functions inherited from sklearn.utils._metadata_requests._MetadataRequester
_build_request_for_signature (cls, router, method)
_get_default_requests (cls)
_get_metadata_request (self)
Protected Attributes inherited from sklearn.linear_model._stochastic_gradient.BaseSGDClassifier
_expanded_class_weight
_loss_function_ = self._get_loss_function(loss)
Protected Attributes inherited from sklearn.linear_model._stochastic_gradient.BaseSGD
_standard_coef = self.coef_
_average_coef
int _standard_intercept = 1 - self.offset_
_average_intercept
Protected Attributes inherited from sklearn.base.BaseEstimator
_parameter_constraints
Static Protected Attributes inherited from sklearn.base.ClassifierMixin
str _estimator_type = "classifier"
Static Protected Attributes inherited from sklearn.base.BaseEstimator
_html_repr = estimator_html_repr
Static Protected Attributes inherited from sklearn.utils._repr_html.base._HTMLDocumentationLinkMixin
str _doc_link_module = "sklearn"
_doc_link_url_param_generator = None
Detailed Description
Definition at line 493 of file test_estimator_checks.py.
Member Function Documentation
__sklearn_tags__()
sklearn.utils.tests.test_estimator_checks.TaggedBinaryClassifier.__sklearn_tags__ (self)
Definition at line 504 of file test_estimator_checks.py.
fit()
sklearn.utils.tests.test_estimator_checks.TaggedBinaryClassifier.fit (self, X, y)
Fit linear model with Stochastic Gradient Descent.
Parameters
----------
X : {array-like, sparse matrix}, shape (n_samples, n_features)
    Training data.
y : ndarray of shape (n_samples,)
    Target values.
coef_init : ndarray of shape (n_classes, n_features), default=None
    The initial coefficients to warm-start the optimization.
intercept_init : ndarray of shape (n_classes,), default=None
    The initial intercept to warm-start the optimization.
sample_weight : array-like, shape (n_samples,), default=None
    Weights applied to individual samples.
    If not provided, uniform weights are assumed. These weights will
    be multiplied with class_weight (passed through the
    constructor) if class_weight is specified.
Returns
-------
self : object
    Returns an instance of self.
Reimplemented from sklearn.utils.tests.test_estimator_checks.UntaggedBinaryClassifier.
Definition at line 494 of file test_estimator_checks.py.
References fit().
Referenced by fit(), sklearn.cluster._kmeans._BaseKMeans.fit_predict(), and sklearn.cluster._kmeans._BaseKMeans.fit_transform().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/sklearn/utils/tests/test_estimator_checks.py