Code Cloning Analysis: fontTools.pens.roundingPen.RoundingPen Class Reference
fontTools.pens.roundingPen.RoundingPen Class Reference
Public Member Functions
__init__ (self, outPen, roundFunc=otRound, transformRoundFunc=noRound)
moveTo (self, pt)
lineTo (self, pt)
curveTo (self, *points)
qCurveTo (self, *points)
addComponent (self, glyphName, transformation)
Public Member Functions inherited from fontTools.pens.filterPen.FilterPen
__init__ (self, outPen)
closePath (self)
endPath (self)
Public Member Functions inherited from fontTools.pens.basePen.AbstractPen
None addVarComponent (self, str glyphName, DecomposedTransform transformation, Dict[str, float] location)
Public Attributes
roundFunc = roundFunc
transformRoundFunc = transformRoundFunc
Public Attributes inherited from fontTools.pens.filterPen.FilterPen
current_pt = None
Additional Inherited Members
Protected Attributes inherited from fontTools.pens.filterPen.FilterPen
_outPen = outPen
Detailed Description
Filter pen that rounds point coordinates and component XY offsets to integer. For
rounding the component transform values, a separate round function can be passed to
the pen.
>>> from fontTools.pens.recordingPen import RecordingPen
>>> recpen = RecordingPen()
>>> roundpen = RoundingPen(recpen)
>>> roundpen.moveTo((0.4, 0.6))
>>> roundpen.lineTo((1.6, 2.5))
>>> roundpen.qCurveTo((2.4, 4.6), (3.3, 5.7), (4.9, 6.1))
>>> roundpen.curveTo((6.4, 8.6), (7.3, 9.7), (8.9, 10.1))
>>> roundpen.addComponent("a", (1.5, 0, 0, 1.5, 10.5, -10.5))
>>> recpen.value == [
...     ('moveTo', ((0, 1),)),
...     ('lineTo', ((2, 3),)),
...     ('qCurveTo', ((2, 5), (3, 6), (5, 6))),
...     ('curveTo', ((6, 9), (7, 10), (9, 10))),
...     ('addComponent', ('a', (1.5, 0, 0, 1.5, 11, -10))),
... ]
True
Definition at line 9 of file roundingPen.py.
Constructor & Destructor Documentation
__init__()
fontTools.pens.roundingPen.RoundingPen.__init__ (self, outPen, roundFunc = otRound, transformRoundFunc = noRound)
Definition at line 33 of file roundingPen.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
addComponent()
fontTools.pens.roundingPen.RoundingPen.addComponent (self, glyphName, transformation)
Reimplemented from fontTools.pens.filterPen._PassThruComponentsMixin.
Definition at line 54 of file roundingPen.py.
curveTo()
fontTools.pens.roundingPen.RoundingPen.curveTo (self, * points)
Draw a cubic bezier with an arbitrary number of control points.
The last point specified is on-curve, all others are off-curve
(control) points. If the number of control points is > 2, the
segment is split into multiple bezier segments. This works
like this:
Let n be the number of control points (which is the number of
arguments to this call minus 1). If n==2, a plain vanilla cubic
bezier is drawn. If n==1, we fall back to a quadratic segment and
if n==0 we draw a straight line. It gets interesting when n>2:
n-1 PostScript-style cubic segments will be drawn as if it were
one curve. See decomposeSuperBezierSegment().
The conversion algorithm used for n>2 is inspired by NURB
splines, and is conceptually equivalent to the TrueType "implied
points" principle. See also decomposeQuadraticSegment().
Reimplemented from fontTools.pens.filterPen.FilterPen.
Definition at line 44 of file roundingPen.py.
References fontTools.pens.filterPen.FilterPen._outPen, curveTo(), and roundFunc.
Referenced by curveTo().
lineTo()
fontTools.pens.roundingPen.RoundingPen.lineTo (self, pt)
Draw a straight line from the current point to 'pt'.
Reimplemented from fontTools.pens.filterPen.FilterPen.
Definition at line 41 of file roundingPen.py.
References fontTools.pens.filterPen.FilterPen._outPen, lineTo(), and roundFunc.
Referenced by lineTo().
moveTo()
fontTools.pens.roundingPen.RoundingPen.moveTo (self, pt)
Begin a new sub path, set the current point to 'pt'. You must
end each sub path with a call to pen.closePath() or pen.endPath().
Reimplemented from fontTools.pens.filterPen.FilterPen.
Definition at line 38 of file roundingPen.py.
References fontTools.pens.filterPen.FilterPen._outPen, moveTo(), and roundFunc.
Referenced by moveTo().
qCurveTo()
fontTools.pens.roundingPen.RoundingPen.qCurveTo (self, * points)
Draw a whole string of quadratic curve segments.
The last point specified is on-curve, all others are off-curve
points.
This method implements TrueType-style curves, breaking up curves
using 'implied points': between each two consequtive off-curve points,
there is one implied point exactly in the middle between them. See
also decomposeQuadraticSegment().
The last argument (normally the on-curve point) may be None.
This is to support contours that have NO on-curve points (a rarely
seen feature of TrueType outlines).
Reimplemented from fontTools.pens.filterPen.FilterPen.
Definition at line 49 of file roundingPen.py.
References fontTools.pens.filterPen.FilterPen._outPen, qCurveTo(), roundFunc, and transformRoundFunc.
Referenced by qCurveTo().
Member Data Documentation
roundFunc
fontTools.pens.roundingPen.RoundingPen.roundFunc = roundFunc
Definition at line 35 of file roundingPen.py.
Referenced by fontTools.pens.roundingPen.RoundingPointPen.addPoint(), curveTo(), lineTo(), moveTo(), and qCurveTo().
transformRoundFunc
fontTools.pens.roundingPen.RoundingPen.transformRoundFunc = transformRoundFunc
Definition at line 36 of file roundingPen.py.
Referenced by fontTools.pens.roundingPen.RoundingPointPen.addPoint(), and qCurveTo().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/pens/roundingPen.py