Code Cloning Analysis: matplotlib.dviread Namespace Reference
matplotlib.dviread Namespace Reference
Classes
class _LuatexKpsewhich
class Dvi
class DviFont
class PsfontsMap
class Text
class Tfm
class Vf
Functions
_dispatch (table, min, max=None, state=None, args=('raw',))
_mul2012 (num1, num2)
_parse_enc (path)
find_tex_file (filename)
_fontfile (cls, suffix, texname)
Variables
_log = logging.getLogger(__name__)
_dvistate = enum.Enum('DviState', 'pre outer inpage post_post finale')
Page = namedtuple('Page', 'text boxes height width descent')
Box = namedtuple('Box', 'x y height width')
_arg_mapping
PsFont = namedtuple('PsFont', 'texname psname effects encoding filename')
_tfmfile = partial(_fontfile, Tfm, ".tfm")
_vffile = partial(_fontfile, Vf, ".vf")
parser = ArgumentParser()
nargs
type
float
default
args = parser.parse_args()
fontmap = PsfontsMap(find_tex_file('pdftex.map'))
sep
width
Detailed Description
A module for reading dvi files output by TeX. Several limitations make
this not (currently) useful as a general-purpose dvi preprocessor, but
it is currently used by the pdf backend for processing usetex text.
Interface::
  with Dvi(filename, 72) as dvi:
      # iterate over pages:
      for page in dvi:
          w, h, d = page.width, page.height, page.descent
          for x, y, font, glyph, width in page.text:
              fontname = font.texname
              pointsize = font.size
              ...
          for x, y, height, width in page.boxes:
              ...
Function Documentation
_dispatch()
matplotlib.dviread._dispatch (table, min, max = None, state = None, args = ('raw',)) protected
Decorator for dispatch by opcode. Sets the values in *table*
from *min* to *max* to this method, adds a check that the Dvi state
matches *state* if not None, reads arguments from the file according
to *args*.
Parameters
----------
table : dict[int, callable]
    The dispatch table to be filled in.
min, max : int
    Range of opcodes that calls the registered function; *max* defaults to
    *min*.
state : _dvistate, optional
    State of the Dvi object in which these opcodes are allowed.
args : list[str], default: ['raw']
    Sequence of argument specifications:
    - 'raw': opcode minus minimum
    - 'u1': read one unsigned byte
    - 'u4': read four bytes, treat as an unsigned number
    - 's4': read four bytes, treat as a signed number
    - 'slen': read (opcode - minimum) bytes, treat as signed
    - 'slen1': read (opcode - minimum + 1) bytes, treat as signed
    - 'ulen1': read (opcode - minimum + 1) bytes, treat as unsigned
    - 'olen1': read (opcode - minimum + 1) bytes, treat as unsigned
      if under four bytes, signed if four bytes
Definition at line 152 of file dviread.py.
_fontfile()
matplotlib.dviread._fontfile (cls, suffix, texname) protected
Definition at line 1105 of file dviread.py.
_mul2012()
matplotlib.dviread._mul2012 (num1, num2) protected
Multiply two numbers in 20.12 fixed point format.
Definition at line 764 of file dviread.py.
Referenced by matplotlib.dviread.DviFont._height_depth_of(), matplotlib.dviread.Dvi._read_arg(), and matplotlib.dviread.DviFont._width_of().
_parse_enc()
matplotlib.dviread._parse_enc (path) protected
Parse a \*.enc file referenced from a psfonts.map style file.
The format supported by this function is a tiny subset of PostScript.
Parameters
----------
path : `os.PathLike`
Returns
-------
list
The nth entry of the list is the PostScript glyph name of the nth
glyph.
Definition at line 998 of file dviread.py.
Referenced by matplotlib.dviread.Text.glyph_name_or_index().
find_tex_file()
matplotlib.dviread.find_tex_file (filename)
Find a file in the texmf tree using kpathsea_.
The kpathsea library, provided by most existing TeX distributions, both
on Unix-like systems and on Windows (MikTeX), is invoked via a long-lived
luatex process if luatex is installed, or via kpsewhich otherwise.
.. _kpathsea: https://www.tug.org/kpathsea/
Parameters
----------
filename : str or path-like
Raises
------
FileNotFoundError
    If the file is not found.
Definition at line 1046 of file dviread.py.
References find_tex_file().
Referenced by matplotlib.dviread.PsfontsMap._parse_and_cache_line(), and find_tex_file().
Variable Documentation
_arg_mapping
matplotlib.dviread._arg_mapping protected
Initial value:
=  dict(
    # raw: Return delta as is.
    raw=lambda dvi, delta: delta,
    # u1: Read 1 byte as an unsigned number.
    u1=lambda dvi, delta: dvi._read_arg(1, signed=False),
    # u4: Read 4 bytes as an unsigned number.
    u4=lambda dvi, delta: dvi._read_arg(4, signed=False),
    # s4: Read 4 bytes as a signed number.
    s4=lambda dvi, delta: dvi._read_arg(4, signed=True),
    # slen: Read delta bytes as a signed number, or None if delta is None.
    slen=lambda dvi, delta: dvi._read_arg(delta, signed=True) if delta else None,
    # slen1: Read (delta + 1) bytes as a signed number.
    slen1=lambda dvi, delta: dvi._read_arg(delta + 1, signed=True),
    # ulen1: Read (delta + 1) bytes as an unsigned number.
    ulen1=lambda dvi, delta: dvi._read_arg(delta + 1, signed=False),
    # olen1: Read (delta + 1) bytes as an unsigned number if less than 4 bytes,
    # as a signed number if 4 bytes.
    olen1=lambda dvi, delta: dvi._read_arg(delta + 1, signed=(delta == 3)),
)
Definition at line 131 of file dviread.py.
_dvistate
matplotlib.dviread._dvistate = enum.Enum('DviState', 'pre outer inpage post_post finale') protected
Definition at line 57 of file dviread.py.
_log
matplotlib.dviread._log = logging.getLogger(__name__) protected
Definition at line 35 of file dviread.py.
_tfmfile
matplotlib.dviread._tfmfile = partial(_fontfile, Tfm, ".tfm") protected
Definition at line 1109 of file dviread.py.
_vffile
matplotlib.dviread._vffile = partial(_fontfile, Vf, ".vf") protected
Definition at line 1110 of file dviread.py.
args
matplotlib.dviread.args = parser.parse_args()
Definition at line 1120 of file dviread.py.
Box
matplotlib.dviread.Box = namedtuple('Box', 'x y height width')
Definition at line 61 of file dviread.py.
default
matplotlib.dviread.default
Definition at line 1119 of file dviread.py.
float
matplotlib.dviread.float
Definition at line 1119 of file dviread.py.
fontmap
matplotlib.dviread.fontmap = PsfontsMap(find_tex_file('pdftex.map'))
Definition at line 1122 of file dviread.py.
nargs
matplotlib.dviread.nargs
Definition at line 1119 of file dviread.py.
Page
matplotlib.dviread.Page = namedtuple('Page', 'text boxes height width descent')
Definition at line 60 of file dviread.py.
parser
matplotlib.dviread.parser = ArgumentParser()
Definition at line 1117 of file dviread.py.
PsFont
matplotlib.dviread.PsFont = namedtuple('PsFont', 'texname psname effects encoding filename')
Definition at line 818 of file dviread.py.
sep
matplotlib.dviread.sep
Definition at line 1130 of file dviread.py.
type
matplotlib.dviread.type
Definition at line 1119 of file dviread.py.
width
matplotlib.dviread.width
Definition at line 1135 of file dviread.py.