Code Cloning Analysis: sklearn.metrics.tests.test_pairwise_distances_reduction Namespace Reference
sklearn.metrics.tests.test_pairwise_distances_reduction Namespace Reference
Functions
_get_metric_params_list (str metric, int n_features, int seed=1)
assert_same_distances_for_common_neighbors (query_idx, dist_row_a, dist_row_b, indices_row_a, indices_row_b, rtol, atol)
assert_no_missing_neighbors (query_idx, dist_row_a, dist_row_b, indices_row_a, indices_row_b, threshold)
assert_compatible_argkmin_results (neighbors_dists_a, neighbors_dists_b, neighbors_indices_a, neighbors_indices_b, rtol=1e-5, atol=1e-6)
_non_trivial_radius (*, X=None, Y=None, metric=None, precomputed_dists=None, expected_n_neighbors=10, n_subsampled_queries=10, **metric_kwargs)
assert_compatible_radius_results (neighbors_dists_a, neighbors_dists_b, neighbors_indices_a, neighbors_indices_b, radius, check_sorted=True, rtol=1e-5, atol=1e-6)
test_assert_compatible_argkmin_results ()
test_assert_compatible_radius_results (check_sorted)
test_pairwise_distances_reduction_is_usable_for (csr_container)
test_argkmin_factory_method_wrong_usages ()
test_argkmin_classmode_factory_method_wrong_usages ()
test_radius_neighbors_factory_method_wrong_usages ()
test_radius_neighbors_classmode_factory_method_wrong_usages ()
test_chunk_size_agnosticism (global_random_seed, Dispatcher, dtype, n_features=100)
test_n_threads_agnosticism (global_random_seed, Dispatcher, dtype, n_features=100)
test_format_agnosticism (global_random_seed, Dispatcher, dtype, csr_container)
test_strategies_consistency (global_random_seed, global_dtype, Dispatcher, n_features=10)
test_pairwise_distances_argkmin (global_random_seed, metric, strategy, dtype, csr_container, n_queries=5, n_samples=100, k=10)
test_pairwise_distances_radius_neighbors (global_random_seed, metric, strategy, dtype, n_queries=5, n_samples=100)
test_memmap_backed_data (metric, Dispatcher, dtype)
test_sqeuclidean_row_norms (global_random_seed, dtype, csr_container)
test_argkmin_classmode_strategy_consistent ()
test_radius_neighbors_classmode_strategy_consistent (outlier_label)
Variables
list CDIST_PAIRWISE_DISTANCES_REDUCTION_COMMON_METRICS
dict FLOAT32_TOLS
dict FLOAT64_TOLS
dict ASSERT_RESULT
Function Documentation
_get_metric_params_list()
sklearn.metrics.tests.test_pairwise_distances_reduction._get_metric_params_list (str metric, int n_features, int seed = 1) protected
Return list of dummy DistanceMetric kwargs for tests.
Definition at line 43 of file test_pairwise_distances_reduction.py.
Referenced by test_strategies_consistency().
_non_trivial_radius()
sklearn.metrics.tests.test_pairwise_distances_reduction._non_trivial_radius (* , X = None, Y = None, metric = None, precomputed_dists = None, expected_n_neighbors = 10, n_subsampled_queries = 10, ** metric_kwargs) protected
Definition at line 216 of file test_pairwise_distances_reduction.py.
assert_compatible_argkmin_results()
sklearn.metrics.tests.test_pairwise_distances_reduction.assert_compatible_argkmin_results (neighbors_dists_a, neighbors_dists_b, neighbors_indices_a, neighbors_indices_b, rtol = 1e-5, atol = 1e-6)
Assert that argkmin results are valid up to rounding errors.
This function asserts that the results of argkmin queries are valid up to:
- rounding error tolerance on distance values;
- permutations of indices for distances values that differ up to the
  expected precision level.
Furthermore, the distances must be sorted.
To be used for testing neighbors queries on float32 datasets: we accept
neighbors rank swaps only if they are caused by small rounding errors on
the distance computations.
Definition at line 142 of file test_pairwise_distances_reduction.py.
References assert_no_missing_neighbors(), and assert_same_distances_for_common_neighbors().
Referenced by assert_compatible_radius_results().
assert_compatible_radius_results()
sklearn.metrics.tests.test_pairwise_distances_reduction.assert_compatible_radius_results (neighbors_dists_a, neighbors_dists_b, neighbors_indices_a, neighbors_indices_b, radius, check_sorted = True, rtol = 1e-5, atol = 1e-6)
Assert that radius neighborhood results are valid up to:
  - relative and absolute tolerance on computed distance values
  - permutations of indices for distances values that differ up to
    a precision level
  - missing or extra last elements if their distance is
    close to the radius
To be used for testing neighbors queries on float32 datasets: we
accept neighbors rank swaps only if they are caused by small
rounding errors on the distance computations.
Input arrays must be sorted w.r.t distances.
Definition at line 245 of file test_pairwise_distances_reduction.py.
References assert_compatible_argkmin_results(), assert_compatible_radius_results(), assert_no_missing_neighbors(), and assert_same_distances_for_common_neighbors().
Referenced by assert_compatible_radius_results().
assert_no_missing_neighbors()
sklearn.metrics.tests.test_pairwise_distances_reduction.assert_no_missing_neighbors (query_idx, dist_row_a, dist_row_b, indices_row_a, indices_row_b, threshold)
Compare the indices of neighbors in two results sets.
Any neighbor index with a distance below the precision threshold should
match one in the other result set. We ignore the last few neighbors beyond
the threshold as those can typically be missing due to rounding errors.
For radius queries, the threshold is just the radius minus the expected
precision level.
For k-NN queries, it is the maximum distance to the k-th neighbor minus the
expected precision level.
Definition at line 106 of file test_pairwise_distances_reduction.py.
Referenced by assert_compatible_argkmin_results(), and assert_compatible_radius_results().
assert_same_distances_for_common_neighbors()
sklearn.metrics.tests.test_pairwise_distances_reduction.assert_same_distances_for_common_neighbors (query_idx, dist_row_a, dist_row_b, indices_row_a, indices_row_b, rtol, atol)
Check that the distances of common neighbors are equal up to tolerance.
This does not check if there are missing neighbors in either result set.
Missingness is handled by assert_no_missing_neighbors.
Definition at line 68 of file test_pairwise_distances_reduction.py.
Referenced by assert_compatible_argkmin_results(), and assert_compatible_radius_results().
test_argkmin_classmode_factory_method_wrong_usages()
sklearn.metrics.tests.test_pairwise_distances_reduction.test_argkmin_classmode_factory_method_wrong_usages ()
Definition at line 799 of file test_pairwise_distances_reduction.py.
test_argkmin_classmode_strategy_consistent()
sklearn.metrics.tests.test_pairwise_distances_reduction.test_argkmin_classmode_strategy_consistent ()
Definition at line 1577 of file test_pairwise_distances_reduction.py.
test_argkmin_factory_method_wrong_usages()
sklearn.metrics.tests.test_pairwise_distances_reduction.test_argkmin_factory_method_wrong_usages ()
Definition at line 722 of file test_pairwise_distances_reduction.py.
test_assert_compatible_argkmin_results()
sklearn.metrics.tests.test_pairwise_distances_reduction.test_assert_compatible_argkmin_results ()
Definition at line 351 of file test_pairwise_distances_reduction.py.
test_assert_compatible_radius_results()
sklearn.metrics.tests.test_pairwise_distances_reduction.test_assert_compatible_radius_results (check_sorted)
Definition at line 491 of file test_pairwise_distances_reduction.py.
test_chunk_size_agnosticism()
sklearn.metrics.tests.test_pairwise_distances_reduction.test_chunk_size_agnosticism (global_random_seed, Dispatcher, dtype, n_features = 100)
Check that results do not depend on the chunk size.
Definition at line 1121 of file test_pairwise_distances_reduction.py.
test_format_agnosticism()
sklearn.metrics.tests.test_pairwise_distances_reduction.test_format_agnosticism (global_random_seed, Dispatcher, dtype, csr_container)
Check that results do not depend on the format (dense, sparse) of the input.
Definition at line 1228 of file test_pairwise_distances_reduction.py.
test_memmap_backed_data()
sklearn.metrics.tests.test_pairwise_distances_reduction.test_memmap_backed_data (metric, Dispatcher, dtype)
Check that the results do not depend on the datasets writability.
Definition at line 1499 of file test_pairwise_distances_reduction.py.
test_n_threads_agnosticism()
sklearn.metrics.tests.test_pairwise_distances_reduction.test_n_threads_agnosticism (global_random_seed, Dispatcher, dtype, n_features = 100)
Check that results do not depend on the number of threads.
Definition at line 1171 of file test_pairwise_distances_reduction.py.
test_pairwise_distances_argkmin()
sklearn.metrics.tests.test_pairwise_distances_reduction.test_pairwise_distances_argkmin (global_random_seed, metric, strategy, dtype, csr_container, n_queries = 5, n_samples = 100, k = 10)
Definition at line 1370 of file test_pairwise_distances_reduction.py.
test_pairwise_distances_radius_neighbors()
sklearn.metrics.tests.test_pairwise_distances_reduction.test_pairwise_distances_radius_neighbors (global_random_seed, metric, strategy, dtype, n_queries = 5, n_samples = 100)
Definition at line 1436 of file test_pairwise_distances_reduction.py.
test_pairwise_distances_reduction_is_usable_for()
sklearn.metrics.tests.test_pairwise_distances_reduction.test_pairwise_distances_reduction_is_usable_for (csr_container)
Definition at line 654 of file test_pairwise_distances_reduction.py.
test_radius_neighbors_classmode_factory_method_wrong_usages()
sklearn.metrics.tests.test_pairwise_distances_reduction.test_radius_neighbors_classmode_factory_method_wrong_usages ()
Definition at line 1009 of file test_pairwise_distances_reduction.py.
test_radius_neighbors_classmode_strategy_consistent()
sklearn.metrics.tests.test_pairwise_distances_reduction.test_radius_neighbors_classmode_strategy_consistent (outlier_label)
Definition at line 1611 of file test_pairwise_distances_reduction.py.
test_radius_neighbors_factory_method_wrong_usages()
sklearn.metrics.tests.test_pairwise_distances_reduction.test_radius_neighbors_factory_method_wrong_usages ()
Definition at line 917 of file test_pairwise_distances_reduction.py.
test_sqeuclidean_row_norms()
sklearn.metrics.tests.test_pairwise_distances_reduction.test_sqeuclidean_row_norms (global_random_seed, dtype, csr_container)
Definition at line 1550 of file test_pairwise_distances_reduction.py.
test_strategies_consistency()
sklearn.metrics.tests.test_pairwise_distances_reduction.test_strategies_consistency (global_random_seed, global_dtype, Dispatcher, n_features = 10)
Check that the results do not depend on the strategy used.
Definition at line 1287 of file test_pairwise_distances_reduction.py.
References _get_metric_params_list().
Variable Documentation
ASSERT_RESULT
dict sklearn.metrics.tests.test_pairwise_distances_reduction.ASSERT_RESULT
Initial value:
=  {
    (ArgKmin, np.float64): partial(assert_compatible_argkmin_results, **FLOAT64_TOLS),
    (ArgKmin, np.float32): partial(assert_compatible_argkmin_results, **FLOAT32_TOLS),
    (
        RadiusNeighbors,
        np.float64,
    ): partial(assert_compatible_radius_results, **FLOAT64_TOLS),
    (
        RadiusNeighbors,
        np.float32,
    ): partial(assert_compatible_radius_results, **FLOAT32_TOLS),
}
Definition at line 337 of file test_pairwise_distances_reduction.py.
CDIST_PAIRWISE_DISTANCES_REDUCTION_COMMON_METRICS
list sklearn.metrics.tests.test_pairwise_distances_reduction.CDIST_PAIRWISE_DISTANCES_REDUCTION_COMMON_METRICS
Initial value:
=  [
    "braycurtis",
    "canberra",
    "chebyshev",
    "cityblock",
    "euclidean",
    "minkowski",
    "seuclidean",
]
Definition at line 32 of file test_pairwise_distances_reduction.py.
FLOAT32_TOLS
dict sklearn.metrics.tests.test_pairwise_distances_reduction.FLOAT32_TOLS
Initial value:
=  {
    "atol": 1e-7,
    "rtol": 1e-5,
}
Definition at line 329 of file test_pairwise_distances_reduction.py.
FLOAT64_TOLS
dict sklearn.metrics.tests.test_pairwise_distances_reduction.FLOAT64_TOLS
Initial value:
=  {
    "atol": 1e-9,
    "rtol": 1e-7,
}
Definition at line 333 of file test_pairwise_distances_reduction.py.