Code Cloning Analysis: pandas.tests.arrays.test_datetimes.TestNonNano Class Reference
pandas.tests.arrays.test_datetimes.TestNonNano Class Reference
Public Member Functions
unit (self, request)
dtype (self, unit, tz_naive_fixture)
dta_dti (self, unit, dtype)
dta (self, dta_dti)
test_non_nano (self, unit, dtype)
test_fields (self, unit, field, dtype, dta_dti)
test_normalize (self, unit)
test_simple_new_requires_match (self, unit)
test_std_non_nano (self, unit)
test_to_period (self, dta_dti)
test_iter (self, dta)
test_astype_object (self, dta)
test_to_pydatetime (self, dta_dti)
test_time_date (self, dta_dti, meth)
test_format_native_types (self, unit, dtype, dta_dti)
test_repr (self, dta_dti, unit)
test_compare_mismatched_resolutions (self, comparison_op)
test_add_mismatched_reso_doesnt_downcast (self)
test_add_timedeltalike_scalar_mismatched_reso (self, dta_dti, scalar)
test_sub_datetimelike_scalar_mismatch (self)
test_sub_datetime64_reso_mismatch (self)
Detailed Description
Definition at line 30 of file test_datetimes.py.
Member Function Documentation
dta()
pandas.tests.arrays.test_datetimes.TestNonNano.dta (self, dta_dti)
Definition at line 60 of file test_datetimes.py.
dta_dti()
pandas.tests.arrays.test_datetimes.TestNonNano.dta_dti (self, unit, dtype)
Definition at line 45 of file test_datetimes.py.
dtype()
pandas.tests.arrays.test_datetimes.TestNonNano.dtype (self, unit, tz_naive_fixture)
Definition at line 37 of file test_datetimes.py.
Referenced by pandas.core.arrays.base.ExtensionScalarOpsMixin._create_method(), scipy.sparse._index.IndexMixin._getcol(), pandas.core.generic.NDFrame._inplace_method(), scipy.sparse._index.IndexMixin._raise_on_1d_array_slice(), pandas.core.strings.object_array.ObjectStringArrayMixin._str_map(), numpy.matrixlib.defmatrix.matrix.H(), numpy.core.records.record.pprint(), pandas.core.frame.DataFrame.quantile(), and pandas.core.generic.NDFrame.rank().
test_add_mismatched_reso_doesnt_downcast()
pandas.tests.arrays.test_datetimes.TestNonNano.test_add_mismatched_reso_doesnt_downcast (self)
Definition at line 209 of file test_datetimes.py.
test_add_timedeltalike_scalar_mismatched_reso()
pandas.tests.arrays.test_datetimes.TestNonNano.test_add_timedeltalike_scalar_mismatched_reso (self, dta_dti, scalar)
Definition at line 231 of file test_datetimes.py.
test_astype_object()
pandas.tests.arrays.test_datetimes.TestNonNano.test_astype_object (self, dta)
Definition at line 139 of file test_datetimes.py.
test_compare_mismatched_resolutions()
pandas.tests.arrays.test_datetimes.TestNonNano.test_compare_mismatched_resolutions (self, comparison_op)
Definition at line 174 of file test_datetimes.py.
test_fields()
pandas.tests.arrays.test_datetimes.TestNonNano.test_fields (self, unit, field, dtype, dta_dti)
Definition at line 76 of file test_datetimes.py.
test_format_native_types()
pandas.tests.arrays.test_datetimes.TestNonNano.test_format_native_types (self, unit, dtype, dta_dti)
Definition at line 159 of file test_datetimes.py.
test_iter()
pandas.tests.arrays.test_datetimes.TestNonNano.test_iter (self, dta)
Definition at line 130 of file test_datetimes.py.
test_non_nano()
pandas.tests.arrays.test_datetimes.TestNonNano.test_non_nano (self, unit, dtype)
Definition at line 64 of file test_datetimes.py.
test_normalize()
pandas.tests.arrays.test_datetimes.TestNonNano.test_normalize (self, unit)
Definition at line 85 of file test_datetimes.py.
test_repr()
pandas.tests.arrays.test_datetimes.TestNonNano.test_repr (self, dta_dti, unit)
Definition at line 168 of file test_datetimes.py.
test_simple_new_requires_match()
pandas.tests.arrays.test_datetimes.TestNonNano.test_simple_new_requires_match (self, unit)
Definition at line 100 of file test_datetimes.py.
test_std_non_nano()
pandas.tests.arrays.test_datetimes.TestNonNano.test_std_non_nano (self, unit)
Definition at line 111 of file test_datetimes.py.
test_sub_datetime64_reso_mismatch()
pandas.tests.arrays.test_datetimes.TestNonNano.test_sub_datetime64_reso_mismatch (self)
Definition at line 259 of file test_datetimes.py.
test_sub_datetimelike_scalar_mismatch()
pandas.tests.arrays.test_datetimes.TestNonNano.test_sub_datetimelike_scalar_mismatch (self)
Definition at line 248 of file test_datetimes.py.
test_time_date()
pandas.tests.arrays.test_datetimes.TestNonNano.test_time_date (self, dta_dti, meth)
Definition at line 152 of file test_datetimes.py.
test_to_period()
pandas.tests.arrays.test_datetimes.TestNonNano.test_to_period (self, dta_dti)
Definition at line 123 of file test_datetimes.py.
test_to_pydatetime()
pandas.tests.arrays.test_datetimes.TestNonNano.test_to_pydatetime (self, dta_dti)
Definition at line 144 of file test_datetimes.py.
unit()
pandas.tests.arrays.test_datetimes.TestNonNano.unit (self, request)
Fixture returning parametrized time units
Definition at line 32 of file test_datetimes.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/tests/arrays/test_datetimes.py