Code Cloning Analysis: fontTools.pens.momentsPen.MomentsPen Class Reference
fontTools.pens.momentsPen.MomentsPen Class Reference
Public Member Functions
__init__ (self, glyphset=None)
Public Member Functions inherited from fontTools.pens.basePen.BasePen
__init__ (self, glyphSet=None)
closePath (self)
endPath (self)
moveTo (self, pt)
lineTo (self, pt)
curveTo (self, *points)
qCurveTo (self, *points)
Public Member Functions inherited from fontTools.pens.basePen.DecomposingPen
__init__ (self, glyphSet, *args, skipMissingComponents=None, reverseFlipped=False, **kwargs)
addComponent (self, glyphName, transformation)
addVarComponent (self, glyphName, transformation, location)
Public Member Functions inherited from fontTools.misc.loggingTools.LogMixin
log (self)
Public Attributes
int area = 0
int momentX = 0
int momentY = 0
int momentXX = 0
int momentXY = 0
int momentYY = 0
Public Attributes inherited from fontTools.pens.basePen.DecomposingPen
glyphSet = glyphSet
reverseFlipped = reverseFlipped
Protected Member Functions
_moveTo (self, p0)
_closePath (self)
_endPath (self)
_lineTo (self, p1)
_qCurveToOne (self, p1, p2)
_curveToOne (self, p1, p2, p3)
Protected Member Functions inherited from fontTools.pens.basePen.BasePen
_getCurrentPoint (self)
Protected Attributes
_startPoint = p0
Protected Attributes inherited from fontTools.misc.loggingTools.LogMixin
_log = logging.getLogger(name)
Additional Inherited Members
Static Public Attributes inherited from fontTools.pens.basePen.DecomposingPen
bool skipMissingComponents = True
MissingComponentError = MissingComponentError
Detailed Description
Definition at line 14 of file momentsPen.py.
Constructor & Destructor Documentation
__init__()
fontTools.pens.momentsPen.MomentsPen.__init__ (self, glyphset = None)
Definition at line 16 of file momentsPen.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_closePath()
fontTools.pens.momentsPen.MomentsPen._closePath (self) protected
Reimplemented from fontTools.pens.basePen.BasePen.
Definition at line 29 of file momentsPen.py.
_curveToOne()
fontTools.pens.momentsPen.MomentsPen._curveToOne (self, p1, p2, p3) protected
Reimplemented from fontTools.pens.basePen.BasePen.
Definition at line 447 of file momentsPen.py.
_endPath()
fontTools.pens.momentsPen.MomentsPen._endPath (self) protected
Reimplemented from fontTools.pens.basePen.BasePen.
Definition at line 34 of file momentsPen.py.
_lineTo()
fontTools.pens.momentsPen.MomentsPen._lineTo (self, p1) protected
Reimplemented from fontTools.pens.basePen.BasePen.
Definition at line 54 of file momentsPen.py.
_moveTo()
fontTools.pens.momentsPen.MomentsPen._moveTo (self, p0) protected
Reimplemented from fontTools.pens.basePen.BasePen.
Definition at line 26 of file momentsPen.py.
_qCurveToOne()
fontTools.pens.momentsPen.MomentsPen._qCurveToOne (self, pt1, pt2) protected
This method implements the basic quadratic curve type. The
default implementation delegates the work to the cubic curve
function. Optionally override with a native implementation.
Reimplemented from fontTools.pens.basePen.BasePen.
Definition at line 156 of file momentsPen.py.
References fontTools.pens.basePen.BasePen._getCurrentPoint(), area, momentX, momentXX, momentXY, momentY, and momentYY.
Member Data Documentation
_startPoint
fontTools.pens.momentsPen.MomentsPen._startPoint = p0 protected
Definition at line 27 of file momentsPen.py.
Referenced by fontTools.pens.statisticsPen.StatisticsControlPen._qCurveToOne().
area
int fontTools.pens.momentsPen.MomentsPen.area = 0
Definition at line 19 of file momentsPen.py.
Referenced by _qCurveToOne(), and fontTools.pens.statisticsPen.StatisticsControlPen._qCurveToOne().
momentX
int fontTools.pens.momentsPen.MomentsPen.momentX = 0
Definition at line 20 of file momentsPen.py.
Referenced by _qCurveToOne().
momentXX
int fontTools.pens.momentsPen.MomentsPen.momentXX = 0
Definition at line 22 of file momentsPen.py.
Referenced by _qCurveToOne().
momentXY
int fontTools.pens.momentsPen.MomentsPen.momentXY = 0
Definition at line 23 of file momentsPen.py.
Referenced by _qCurveToOne().
momentY
int fontTools.pens.momentsPen.MomentsPen.momentY = 0
Definition at line 21 of file momentsPen.py.
Referenced by _qCurveToOne().
momentYY
int fontTools.pens.momentsPen.MomentsPen.momentYY = 0
Definition at line 24 of file momentsPen.py.
Referenced by _qCurveToOne().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/pens/momentsPen.py