Code Cloning Analysis: pandas.core.indexes.base Namespace Reference
pandas.core.indexes.base Namespace Reference
Classes
class Index
Functions
F _maybe_return_indexers (F meth)
_new_Index (cls, d)
Index ensure_index_from_sequences (sequences, names=None)
Index ensure_index (Axes index_like, bool copy=False)
ensure_has_len (seq)
list[str] trim_front (list[str] strings)
None _validate_join_method (str method)
Hashable maybe_extract_name (name, obj, cls)
tuple[Hashable,...] get_unanimous_names (*Index indexes)
DtypeObj _unpack_nested_dtype (Index other)
_maybe_try_sort (Index|ArrayLike result, bool|None sort)
npt.NDArray[np.object_] get_values_for_csv (ArrayLike values, *, date_format, str na_rep="nan", quoting=None, float_format=None, str decimal=".")
Variables
list __all__ = ["Index"]
_unsortable_types = frozenset(("mixed", "mixed-integer"))
dict _index_doc_kwargs
dict _index_shared_docs = {}
str_t = str
_dtype_obj = np.dtype("object")
dict _masked_engines
Function Documentation
_maybe_return_indexers()
F pandas.core.indexes.base._maybe_return_indexers (F meth) protected
Decorator to simplify 'return_indexers' checks in Index.join.
Definition at line 264 of file base.py.
_maybe_try_sort()
pandas.core.indexes.base._maybe_try_sort (Index | ArrayLike result, bool | None sort) protected
Definition at line 7816 of file base.py.
_new_Index()
pandas.core.indexes.base._new_Index (cls, d) protected
This is called upon unpickling, rather than the default which doesn't
have arguments and breaks __new__.
Definition at line 292 of file base.py.
_unpack_nested_dtype()
DtypeObj pandas.core.indexes.base._unpack_nested_dtype (Index other) protected
When checking if our dtype is comparable with another, we need
to unpack CategoricalDtype to look at its categories.dtype.
Parameters
----------
other : Index
Returns
-------
np.dtype or ExtensionDtype
Definition at line 7789 of file base.py.
Referenced by pandas.core.indexes.base.Index._get_indexer_non_comparable(), pandas.core.indexes.base.Index._should_compare(), and pandas.core.indexes.base.Index.union().
_validate_join_method()
None pandas.core.indexes.base._validate_join_method (str method) protected
Definition at line 7749 of file base.py.
ensure_has_len()
pandas.core.indexes.base.ensure_has_len (seq)
If seq is an iterator, put its values into a list.
Definition at line 7718 of file base.py.
Referenced by pandas.core.indexes.base.Index.reindex().
ensure_index()
Index pandas.core.indexes.base.ensure_index (Axes index_like, bool copy = False)
Ensure that we have an index from some index-like object.
Parameters
----------
index_like : sequence
    An Index or other sequence
copy : bool, default False
Returns
-------
index : Index or MultiIndex
See Also
--------
ensure_index_from_sequences
Examples
--------
>>> ensure_index(['a', 'b'])
Index(['a', 'b'], dtype='object')
>>> ensure_index([('a', 'a'),  ('b', 'c')])
Index([('a', 'a'), ('b', 'c')], dtype='object')
>>> ensure_index([['a', 'a'], ['b', 'c']])
MultiIndex([('a', 'b'),
        ('a', 'c')],
       )
Definition at line 7659 of file base.py.
Referenced by pandas.core.indexes.base.Index._maybe_cast_listlike_indexer(), pandas.core.indexes.base.Index._raise_if_missing(), pandas.core.indexes.base.Index._reindex_non_unique(), pandas.core.indexes.base.Index.join(), and pandas.core.indexes.base.Index.reindex().
ensure_index_from_sequences()
Index pandas.core.indexes.base.ensure_index_from_sequences (sequences, names = None)
Construct an index from sequences of data.
A single sequence returns an Index. Many sequences returns a
MultiIndex.
Parameters
----------
sequences : sequence of sequences
names : sequence of str
Returns
-------
index : Index or MultiIndex
Examples
--------
>>> ensure_index_from_sequences([[1, 2, 3]], names=["name"])
Index([1, 2, 3], dtype='int64', name='name')
>>> ensure_index_from_sequences([["a", "a"], ["a", "b"]], names=["L1", "L2"])
MultiIndex([('a', 'a'),
            ('a', 'b')],
           names=['L1', 'L2'])
See Also
--------
ensure_index
Definition at line 7619 of file base.py.
get_unanimous_names()
tuple[Hashable, ...] pandas.core.indexes.base.get_unanimous_names (*Index indexes)
Return common name if all indices agree, otherwise None (level-by-level).
Parameters
----------
indexes : list of Index objects
Returns
-------
list
    A list representing the unanimous 'names' found.
Definition at line 7770 of file base.py.
get_values_for_csv()
npt.NDArray[np.object_] pandas.core.indexes.base.get_values_for_csv (ArrayLike values, * , date_format, str na_rep = "nan", quoting = None, float_format = None, str decimal = ".")
Convert to types which can be consumed by the standard library's
csv.writer.writerows.
Definition at line 7836 of file base.py.
Referenced by pandas.core.indexes.base.Index._format_flat().
maybe_extract_name()
Hashable pandas.core.indexes.base.maybe_extract_name (name, obj, cls)
If no name is passed, then extract it from data, validating hashability.
Definition at line 7754 of file base.py.
Referenced by pandas.core.indexes.base.Index.name().
trim_front()
list[str] pandas.core.indexes.base.trim_front (list[str] strings)
Trims zeros and decimal points.
Examples
--------
>>> trim_front([" a", " b"])
['a', 'b']
>>> trim_front([" a", " "])
['a', '']
Definition at line 7730 of file base.py.
Referenced by pandas.core.indexes.base.Index._format_flat().
Variable Documentation
__all__
list pandas.core.indexes.base.__all__ = ["Index"] private
Definition at line 217 of file base.py.
_dtype_obj
pandas.core.indexes.base._dtype_obj = np.dtype("object") protected
Definition at line 232 of file base.py.
_index_doc_kwargs
dict pandas.core.indexes.base._index_doc_kwargs protected
Initial value:
=  {
    "klass": "Index",
    "inplace": "",
    "target_klass": "Index",
    "raises_section": "",
    "unique": "Index",
    "duplicated": "np.ndarray",
}
Definition at line 221 of file base.py.
_index_shared_docs
dict pandas.core.indexes.base._index_shared_docs = {} protected
Definition at line 229 of file base.py.
_masked_engines
dict pandas.core.indexes.base._masked_engines protected
Initial value:
=  {
    "Complex128": libindex.MaskedComplex128Engine,
    "Complex64": libindex.MaskedComplex64Engine,
    "Float64": libindex.MaskedFloat64Engine,
    "Float32": libindex.MaskedFloat32Engine,
    "UInt64": libindex.MaskedUInt64Engine,
    "UInt32": libindex.MaskedUInt32Engine,
    "UInt16": libindex.MaskedUInt16Engine,
    "UInt8": libindex.MaskedUInt8Engine,
    "Int64": libindex.MaskedInt64Engine,
    "Int32": libindex.MaskedInt32Engine,
    "Int16": libindex.MaskedInt16Engine,
    "Int8": libindex.MaskedInt8Engine,
    "boolean": libindex.MaskedBoolEngine,
    "double[pyarrow]": libindex.MaskedFloat64Engine,
    "float64[pyarrow]": libindex.MaskedFloat64Engine,
    "float32[pyarrow]": libindex.MaskedFloat32Engine,
    "float[pyarrow]": libindex.MaskedFloat32Engine,
    "uint64[pyarrow]": libindex.MaskedUInt64Engine,
    "uint32[pyarrow]": libindex.MaskedUInt32Engine,
    "uint16[pyarrow]": libindex.MaskedUInt16Engine,
    "uint8[pyarrow]": libindex.MaskedUInt8Engine,
    "int64[pyarrow]": libindex.MaskedInt64Engine,
    "int32[pyarrow]": libindex.MaskedInt32Engine,
    "int16[pyarrow]": libindex.MaskedInt16Engine,
    "int8[pyarrow]": libindex.MaskedInt8Engine,
    "bool[pyarrow]": libindex.MaskedBoolEngine,
}
Definition at line 234 of file base.py.
_unsortable_types
pandas.core.indexes.base._unsortable_types = frozenset(("mixed", "mixed-integer")) protected
Definition at line 219 of file base.py.
str_t
pandas.core.indexes.base.str_t = str
Definition at line 230 of file base.py.