Code Cloning Analysis: fontTools.ttLib.tables._c_v_a_r.table__c_v_a_r Class Reference
fontTools.ttLib.tables._c_v_a_r.table__c_v_a_r Class Reference
Public Member Functions
__init__ (self, tag=None)
compile (self, ttFont, useSharedPoints=False)
decompile (self, data, ttFont)
fromXML (self, name, attrs, content, ttFont)
toXML (self, writer, ttFont)
Public Member Functions inherited from fontTools.ttLib.tables.DefaultTable.DefaultTable
__init__ (self, tag=None)
__repr__ (self)
__eq__ (self, other)
__ne__ (self, other)
Public Attributes
int majorVersion
int minorVersion = 1, 0
list variations = []
Public Attributes inherited from fontTools.ttLib.tables.DefaultTable.DefaultTable
tableTag = Tag(tag)
data = data
ERROR
Additional Inherited Members
Static Public Attributes inherited from fontTools.ttLib.tables.DefaultTable.DefaultTable
list dependencies = []
Detailed Description
Control Value Table (CVT) variations table
The ``cvar`` table contains variations for the values in a ``cvt``
table.
See also https://learn.microsoft.com/en-us/typography/opentype/spec/cvar
Definition at line 26 of file _c_v_a_r.py.
Constructor & Destructor Documentation
__init__()
fontTools.ttLib.tables._c_v_a_r.table__c_v_a_r.__init__ (self, tag = None)
Definition at line 37 of file _c_v_a_r.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
compile()
fontTools.ttLib.tables._c_v_a_r.table__c_v_a_r.compile (self, ttFont, useSharedPoints = False)
Reimplemented from fontTools.ttLib.tables.DefaultTable.DefaultTable.
Definition at line 42 of file _c_v_a_r.py.
Referenced by fontTools.ttLib.tables.TupleVariation.TupleVariation.getCoordWidth(), and PIL.FontFile.FontFile.save().
decompile()
fontTools.ttLib.tables._c_v_a_r.table__c_v_a_r.decompile (self, data, ttFont)
Reimplemented from fontTools.ttLib.tables.DefaultTable.DefaultTable.
Definition at line 58 of file _c_v_a_r.py.
Referenced by fontTools.ttLib.tables._c_m_a_p.CmapSubtable.newSubtable().
fromXML()
fontTools.ttLib.tables._c_v_a_r.table__c_v_a_r.fromXML (self, name, attrs, content, ttFont)
Reimplemented from fontTools.ttLib.tables.DefaultTable.DefaultTable.
Definition at line 76 of file _c_v_a_r.py.
toXML()
fontTools.ttLib.tables._c_v_a_r.table__c_v_a_r.toXML (self, writer, ttFont)
Reimplemented from fontTools.ttLib.tables.DefaultTable.DefaultTable.
Definition at line 89 of file _c_v_a_r.py.
Member Data Documentation
majorVersion
int fontTools.ttLib.tables._c_v_a_r.table__c_v_a_r.majorVersion
Definition at line 39 of file _c_v_a_r.py.
Referenced by fontTools.ttLib.sfnt.SFNTReader.__getitem__(), fontTools.ttLib.woff2.WOFF2FlavorData.__init__(), and fontTools.ttLib.woff2.WOFF2Writer.close().
minorVersion
int fontTools.ttLib.tables._c_v_a_r.table__c_v_a_r.minorVersion = 1, 0
Definition at line 39 of file _c_v_a_r.py.
Referenced by fontTools.ttLib.sfnt.SFNTReader.__getitem__(), and fontTools.ttLib.woff2.WOFF2Writer.close().
variations
list fontTools.ttLib.tables._c_v_a_r.table__c_v_a_r.variations = []
Definition at line 40 of file _c_v_a_r.py.
Referenced by fontTools.ttLib.tables._g_v_a_r.table__g_v_a_r.compileOffsets_().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ttLib/tables/_c_v_a_r.py