Code Cloning Analysis: TRON Class Reference
TRON Class Reference
Public Member Functions
TRON (const function *fun_obj, double eps=0.1, int max_iter=1000, BlasFunctions *blas=0)
int tron (double *w)
void set_print_string (void(*i_print)(const char *buf))
Private Member Functions
int trcg (double delta, double *g, double *s, double *r)
double norm_inf (int n, double *x)
void info (const char *fmt,...)
Private Attributes
double eps
int max_iter
function * fun_obj
BlasFunctions * blas
void(* tron_print_string)(const char *buf)
Detailed Description
Definition at line 17 of file tron.h.
Constructor & Destructor Documentation
TRON()
TRON::TRON (const function * fun_obj, double eps = 0.1, int max_iter = 1000, BlasFunctions * blas = 0)
Definition at line 31 of file tron.cpp.
~TRON()
TRON::~TRON ()
Definition at line 40 of file tron.cpp.
Member Function Documentation
info()
void TRON::info (const char * fmt, ...) private
Definition at line 21 of file tron.cpp.
Referenced by pandas.io.formats.info._TableBuilderAbstract::display_memory_usage(), pandas.io.formats.info._TableBuilderAbstract::dtype_counts(), pandas.io.formats.info._TableBuilderAbstract::dtypes(), pandas.io.formats.info._TableBuilderAbstract::get_lines(), and pandas.io.formats.info._TableBuilderAbstract::memory_usage_string().
norm_inf()
double TRON::norm_inf (int n, double * x) private
Definition at line 211 of file tron.cpp.
set_print_string()
void TRON::set_print_string (void(* i_print)(const char *buf))
Definition at line 220 of file tron.cpp.
trcg()
int TRON::trcg (double delta, double * g, double * s, double * r) private
Definition at line 149 of file tron.cpp.
tron()
int TRON::tron (double * w)
Definition at line 44 of file tron.cpp.
Member Data Documentation
blas
BlasFunctions* TRON::blas private
Definition at line 33 of file tron.h.
eps
double TRON::eps private
Definition at line 30 of file tron.h.
fun_obj
function* TRON::fun_obj private
Definition at line 32 of file tron.h.
max_iter
int TRON::max_iter private
Definition at line 31 of file tron.h.
Referenced by sklearn.linear_model._least_angle.Lars::fit().
tron_print_string
void(* TRON::tron_print_string) (const char *buf) private
Definition at line 35 of file tron.h.
The documentation for this class was generated from the following files:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/sklearn/svm/src/liblinear/tron.h
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/sklearn/svm/src/liblinear/tron.cpp