Code Cloning Analysis: pandas.io.formats.html.NotebookFormatter Class Reference
pandas.io.formats.html.NotebookFormatter Class Reference
Public Member Functions
None write_style (self)
list[str] render (self)
Public Member Functions inherited from pandas.io.formats.html.HTMLFormatter
None __init__ (self, DataFrameFormatter formatter, str|list[str]|tuple[str,...]|None classes=None, int|bool|None border=None, str|None table_id=None, bool render_links=False)
str to_string (self)
bool should_show_dimensions (self)
bool show_row_idx_names (self)
bool show_col_idx_names (self)
int row_levels (self)
bool is_truncated (self)
int ncols (self)
None write (self, Any s, int indent=0)
None write_th (self, Any s, bool header=False, int indent=0, str|None tags=None)
None write_td (self, Any s, int indent=0, str|None tags=None)
None write_tr (self, Iterable line, int indent=0, int indent_delta=0, bool header=False, str|None align=None, dict[int, str]|None tags=None, int nindex_levels=0)
Protected Member Functions
dict[int, list[str]] _get_formatted_values (self)
list[str] _get_columns_formatted_values (self)
Protected Member Functions inherited from pandas.io.formats.html.HTMLFormatter
None _write_cell (self, Any s, str kind="td", int indent=0, str|None tags=None)
None _write_table (self, int indent=0)
None _write_col_header (self, int indent)
None _write_row_header (self, int indent)
None _write_header (self, int indent)
None _write_body (self, int indent)
None _write_regular_rows (self, Mapping[int, list[str]] fmt_values, int indent)
None _write_hierarchical_rows (self, Mapping[int, list[str]] fmt_values, int indent)
Additional Inherited Members
Public Attributes inherited from pandas.io.formats.html.HTMLFormatter
fmt = formatter
classes = classes
frame = self.fmt.frame
columns = self.fmt.tr_frame.columns
list elements = []
bold_rows = self.fmt.bold_rows
escape = self.fmt.escape
show_dimensions = self.fmt.show_dimensions
border = border
table_id = table_id
render_links = render_links
dict col_space = {}
should_show_dimensions
show_col_idx_names
show_row_idx_names = f' border="{self.border}"'
ncols = []
Static Public Attributes inherited from pandas.io.formats.html.HTMLFormatter
Final indent_delta = 2
Detailed Description
Internal class for formatting output data in html for display in Jupyter
Notebooks. This class is intended for functionality specific to
DataFrame._repr_html_() and DataFrame.to_html(notebook=True)
Definition at line 599 of file html.py.
Member Function Documentation
_get_columns_formatted_values()
list[str] pandas.io.formats.html.NotebookFormatter._get_columns_formatted_values (self) protected
Reimplemented from pandas.io.formats.html.HTMLFormatter.
Definition at line 609 of file html.py.
_get_formatted_values()
dict[int, list[str]] pandas.io.formats.html.NotebookFormatter._get_formatted_values (self) protected
Reimplemented from pandas.io.formats.html.HTMLFormatter.
Definition at line 606 of file html.py.
render()
list[str] pandas.io.formats.html.NotebookFormatter.render (self)
Reimplemented from pandas.io.formats.html.HTMLFormatter.
Definition at line 641 of file html.py.
Referenced by pip._vendor.rich.progress.ProgressColumn.__call__(), pip._vendor.rich.logging.RichHandler.emit(), pip._vendor.rich.console.Console.log(), pip._vendor.rich.console.Console.print(), pip._vendor.rich.console.Console.render(), pip._vendor.rich.layout.Layout.render(), pip._vendor.rich.console.Console.render_lines(), and pip._vendor.rich.console.Console.update_screen_lines().
write_style()
None pandas.io.formats.html.NotebookFormatter.write_style (self)
Definition at line 613 of file html.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/io/formats/html.py