Code Cloning Analysis: threadpoolctl.ThreadpoolController Class Reference
threadpoolctl.ThreadpoolController Class Reference
Public Member Functions
__init__ (self)
info (self)
select (self, **kwargs)
limit (self, *, limits=None, user_api=None)
wrap (self, *, limits=None, user_api=None)
__len__ (self)
Public Attributes
list lib_controllers = []
Protected Member Functions
_from_controllers (cls, lib_controllers)
_get_params_for_sequential_blas_under_openmp (self)
_load_libraries (self)
_find_libraries_with_dl_iterate_phdr (self)
_find_libraries_with_dyld (self)
_find_libraries_with_enum_process_module_ex (self)
_find_libraries_pyodide (self)
_make_controller_from_path (self, filepath)
_check_prefix (self, library_basename, filename_prefixes)
_warn_if_incompatible_openmp (self)
_get_libc (cls)
_get_windll (cls, dll_name)
Static Protected Attributes
_system_libraries = dict()
Detailed Description
Collection of LibController objects for all loaded supported libraries
Attributes
----------
lib_controllers : list of `LibController` objects
    The list of library controllers of all loaded supported libraries.
Definition at line 801 of file threadpoolctl.py.
Constructor & Destructor Documentation
__init__()
threadpoolctl.ThreadpoolController.__init__ (self)
Definition at line 816 of file threadpoolctl.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params().
Member Function Documentation
__len__()
threadpoolctl.ThreadpoolController.__len__ (self)
Definition at line 964 of file threadpoolctl.py.
_check_prefix()
threadpoolctl.ThreadpoolController._check_prefix (self, library_basename, filename_prefixes) protected
Return the prefix library_basename starts with
Return None if none matches.
Definition at line 1201 of file threadpoolctl.py.
_find_libraries_pyodide()
threadpoolctl.ThreadpoolController._find_libraries_pyodide (self) protected
Pyodide specific implementation for finding loaded libraries.
Adapted from suggestion in https://github.com/joblib/threadpoolctl/pull/169#issuecomment-1946696449.
One day, we may have a simpler solution. libc dl_iterate_phdr needs to
be implemented in Emscripten and exposed in Pyodide, see
https://github.com/emscripten-core/emscripten/issues/21354 for more
details.
Definition at line 1116 of file threadpoolctl.py.
_find_libraries_with_dl_iterate_phdr()
threadpoolctl.ThreadpoolController._find_libraries_with_dl_iterate_phdr (self) protected
Loop through loaded libraries and return binders on supported ones
This function is expected to work on POSIX system only.
This code is adapted from code by Intel developer @anton-malakhov
available at https://github.com/IntelPython/smp
Copyright (c) 2017, Intel Corporation published under the BSD 3-Clause
license
Definition at line 978 of file threadpoolctl.py.
_find_libraries_with_dyld()
threadpoolctl.ThreadpoolController._find_libraries_with_dyld (self) protected
Loop through loaded libraries and return binders on supported ones
This function is expected to work on OSX system only
Definition at line 1019 of file threadpoolctl.py.
_find_libraries_with_enum_process_module_ex()
threadpoolctl.ThreadpoolController._find_libraries_with_enum_process_module_ex (self) protected
Loop through loaded libraries and return binders on supported ones
This function is expected to work on windows system only.
This code is adapted from code by Philipp Hagemeister @phihag available
at https://stackoverflow.com/questions/17474574
Definition at line 1042 of file threadpoolctl.py.
_from_controllers()
threadpoolctl.ThreadpoolController._from_controllers (cls, lib_controllers) protected
Definition at line 822 of file threadpoolctl.py.
_get_libc()
threadpoolctl.ThreadpoolController._get_libc (cls) protected
Load the lib-C for unix systems.
Definition at line 1229 of file threadpoolctl.py.
_get_params_for_sequential_blas_under_openmp()
threadpoolctl.ThreadpoolController._get_params_for_sequential_blas_under_openmp (self) protected
Return appropriate params to use for a sequential BLAS call in an OpenMP loop
This function takes into account the unexpected behavior of OpenBLAS with the
OpenMP threading layer.
Definition at line 858 of file threadpoolctl.py.
_get_windll()
threadpoolctl.ThreadpoolController._get_windll (cls, dll_name) protected
Load a windows DLL
Definition at line 1244 of file threadpoolctl.py.
_load_libraries()
threadpoolctl.ThreadpoolController._load_libraries (self) protected
Loop through loaded shared libraries and store the supported ones
Definition at line 967 of file threadpoolctl.py.
_make_controller_from_path()
threadpoolctl.ThreadpoolController._make_controller_from_path (self, filepath) protected
Store a library controller if it is supported and selected
Definition at line 1143 of file threadpoolctl.py.
_warn_if_incompatible_openmp()
threadpoolctl.ThreadpoolController._warn_if_incompatible_openmp (self) protected
Raise a warning if llvm-OpenMP and intel-OpenMP are both loaded
Definition at line 1211 of file threadpoolctl.py.
info()
threadpoolctl.ThreadpoolController.info (self)
Return lib_controllers info as a list of dicts
Definition at line 827 of file threadpoolctl.py.
Referenced by pandas.io.formats.info._TableBuilderAbstract.display_memory_usage(), pandas.io.formats.info._TableBuilderAbstract.dtype_counts(), pandas.io.formats.info._TableBuilderAbstract.dtypes(), pandas.io.formats.info._TableBuilderAbstract.get_lines(), and pandas.io.formats.info._TableBuilderAbstract.memory_usage_string().
limit()
threadpoolctl.ThreadpoolController.limit (self, * , limits = None, user_api = None)
Change the maximal number of threads that can be used in thread pools.
This function returns an object that can be used either as a callable (the
construction of this object limits the number of threads) or as a context
manager, in a `with` block to automatically restore the original state of the
controlled libraries when exiting the block.
Set the maximal number of threads that can be used in thread pools used in
the supported libraries to `limits`. This function works for libraries that
are already loaded in the interpreter and can be changed dynamically.
This effect is global and impacts the whole Python process. There is no thread
level isolation as these libraries do not offer thread-local APIs to configure
the number of threads to use in nested parallel calls.
Parameters
----------
limits : int, dict, 'sequential_blas_under_openmp' or None (default=None)
    The maximal number of threads that can be used in thread pools
    - If int, sets the maximum number of threads to `limits` for each
      library selected by `user_api`.
    - If it is a dictionary `{{key: max_threads}}`, this function sets a
      custom maximum number of threads for each `key` which can be either a
      `user_api` or a `prefix` for a specific library.
    - If 'sequential_blas_under_openmp', it will chose the appropriate `limits`
      and `user_api` parameters for the specific use case of sequential BLAS
      calls within an OpenMP parallel region. The `user_api` parameter is
      ignored.
    - If None, this function does not do anything.
user_api : {USER_APIS} or None (default=None)
    APIs of libraries to limit. Used only if `limits` is an int.
    - If "blas", it will only limit BLAS supported libraries ({BLAS_LIBS}).
    - If "openmp", it will only limit OpenMP supported libraries
      ({OPENMP_LIBS}). Note that it can affect the number of threads used
      by the BLAS libraries if they rely on OpenMP.
    - If None, this function will apply to all supported libraries.
Definition at line 875 of file threadpoolctl.py.
select()
threadpoolctl.ThreadpoolController.select (self, ** kwargs)
Return a ThreadpoolController containing a subset of its current
library controllers
It will select all libraries matching at least one pair (key, value) from kwargs
where key is an entry of the library info dict (like "user_api", "internal_api",
"prefix", ...) and value is the value or a list of acceptable values for that
entry.
For instance, `ThreadpoolController().select(internal_api=["blis", "openblas"])`
will select all library controllers whose internal_api is either "blis" or
"openblas".
Definition at line 831 of file threadpoolctl.py.
Referenced by numpy.core.tests.test_simd._SIMD_ALL.test_lut().
wrap()
threadpoolctl.ThreadpoolController.wrap (self, * , limits = None, user_api = None)
Change the maximal number of threads that can be used in thread pools.
This function returns an object that can be used as a decorator.
Set the maximal number of threads that can be used in thread pools used in
the supported libraries to `limits`. This function works for libraries that
are already loaded in the interpreter and can be changed dynamically.
Parameters
----------
limits : int, dict or None (default=None)
    The maximal number of threads that can be used in thread pools
    - If int, sets the maximum number of threads to `limits` for each
      library selected by `user_api`.
    - If it is a dictionary `{{key: max_threads}}`, this function sets a
      custom maximum number of threads for each `key` which can be either a
      `user_api` or a `prefix` for a specific library.
    - If None, this function does not do anything.
user_api : {USER_APIS} or None (default=None)
    APIs of libraries to limit. Used only if `limits` is an int.
    - If "blas", it will only limit BLAS supported libraries ({BLAS_LIBS}).
    - If "openmp", it will only limit OpenMP supported libraries
      ({OPENMP_LIBS}). Note that it can affect the number of threads used
      by the BLAS libraries if they rely on OpenMP.
    - If None, this function will apply to all supported libraries.
Definition at line 928 of file threadpoolctl.py.
Member Data Documentation
_system_libraries
threadpoolctl.ThreadpoolController._system_libraries = dict() static protected
Definition at line 814 of file threadpoolctl.py.
lib_controllers
threadpoolctl.ThreadpoolController.lib_controllers = []
Definition at line 817 of file threadpoolctl.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/threadpoolctl.py