Code Cloning Analysis: sklearn.utils.metaestimators._BaseComposition Class Reference
sklearn.utils.metaestimators._BaseComposition Class Reference
Public Member Functions
__init__ (self)
Public Member Functions inherited from sklearn.base.BaseEstimator
get_params (self, deep=True)
set_params (self, **params)
__sklearn_clone__ (self)
__repr__ (self, N_CHAR_MAX=700)
__getstate__ (self)
__setstate__ (self, state)
__sklearn_tags__ (self)
Public Member Functions inherited from sklearn.utils._metadata_requests._MetadataRequester
set_fit_request (self, **kwargs)
set_partial_fit_request (self, **kwargs)
set_predict_request (self, **kwargs)
set_predict_proba_request (self, **kwargs)
set_predict_log_proba_request (self, **kwargs)
set_decision_function_request (self, **kwargs)
set_score_request (self, **kwargs)
set_split_request (self, **kwargs)
set_transform_request (self, **kwargs)
set_inverse_transform_request (self, **kwargs)
__init_subclass__ (cls, **kwargs)
get_metadata_routing (self)
Static Public Attributes
List steps [Any]
Protected Member Functions
_get_params (self, attr, deep=True)
_set_params (self, attr, **params)
_replace_estimator (self, attr, name, new_val)
_validate_names (self, names)
Protected Member Functions inherited from sklearn.base.BaseEstimator
_get_param_names (cls)
_get_params_html (self, deep=True)
_validate_params (self)
Protected Member Functions inherited from sklearn.utils._repr_html.base.ReprHTMLMixin
_repr_html_ (self)
_repr_html_inner (self)
_repr_mimebundle_ (self, **kwargs)
Protected Member Functions inherited from sklearn.utils._repr_html.base._HTMLDocumentationLinkMixin
_doc_link_template (self)
_doc_link_template (self, value)
_get_doc_link (self)
Protected Member Functions inherited from sklearn.utils._metadata_requests._MetadataRequester
_build_request_for_signature (cls, router, method)
_get_default_requests (cls)
_get_metadata_request (self)
Additional Inherited Members
Protected Attributes inherited from sklearn.base.BaseEstimator
_parameter_constraints
Static Protected Attributes inherited from sklearn.base.BaseEstimator
_html_repr = estimator_html_repr
Static Protected Attributes inherited from sklearn.utils._repr_html.base._HTMLDocumentationLinkMixin
str _doc_link_module = "sklearn"
_doc_link_url_param_generator = None
Detailed Description
Handles parameter management for classifiers composed of named estimators.
Definition at line 20 of file metaestimators.py.
Constructor & Destructor Documentation
__init__()
sklearn.utils.metaestimators._BaseComposition.__init__ (self)
Definition at line 26 of file metaestimators.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params().
Member Function Documentation
_get_params()
sklearn.utils.metaestimators._BaseComposition._get_params (self, attr, deep = True) protected
Definition at line 29 of file metaestimators.py.
Referenced by sklearn.compose._column_transformer.ColumnTransformer.get_params(), sklearn.pipeline.FeatureUnion.get_params(), and sklearn.pipeline.Pipeline.get_params().
_replace_estimator()
sklearn.utils.metaestimators._BaseComposition._replace_estimator (self, attr, name, new_val) protected
Definition at line 72 of file metaestimators.py.
_set_params()
sklearn.utils.metaestimators._BaseComposition._set_params (self, attr, ** params) protected
Definition at line 51 of file metaestimators.py.
Referenced by sklearn.compose._column_transformer.ColumnTransformer.set_params(), sklearn.pipeline.FeatureUnion.set_params(), and sklearn.pipeline.Pipeline.set_params().
_validate_names()
sklearn.utils.metaestimators._BaseComposition._validate_names (self, names) protected
Definition at line 81 of file metaestimators.py.
Referenced by sklearn.ensemble._stacking.StackingClassifier._validate_estimators(), sklearn.compose._column_transformer.ColumnTransformer._validate_transformers(), sklearn.ensemble._base._BaseHeterogeneousEnsemble.named_estimators(), sklearn.pipeline.FeatureUnion.set_params(), and sklearn.pipeline.Pipeline.set_params().
Member Data Documentation
steps
List sklearn.utils.metaestimators._BaseComposition.steps [Any] static
Definition at line 23 of file metaestimators.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/sklearn/utils/metaestimators.py