Code Cloning Analysis: numpy.core._dtype_ctypes Namespace Reference
numpy.core._dtype_ctypes Namespace Reference
Functions
_from_ctypes_array (t)
_from_ctypes_structure (t)
_from_ctypes_scalar (t)
_from_ctypes_union (t)
dtype_from_ctypes_type (t)
Detailed Description
Conversion from ctypes to dtype.
In an ideal world, we could achieve this through the PEP3118 buffer protocol,
something like::
    def dtype_from_ctypes_type(t):
        # needed to ensure that the shape of `t` is within memoryview.format
        class DummyStruct(ctypes.Structure):
            _fields_ = [('a', t)]
        # empty to avoid memory allocation
        ctype_0 = (DummyStruct * 0)()
        mv = memoryview(ctype_0)
        # convert the struct, and slice back out the field
        return _dtype_from_pep3118(mv.format)['a']
Unfortunately, this fails because:
* ctypes cannot handle length-0 arrays with PEP3118 (bpo-32782)
* PEP3118 cannot represent unions, but both numpy and ctypes can
* ctypes cannot handle big-endian structs with PEP3118 (bpo-32780)
Function Documentation
_from_ctypes_array()
numpy.core._dtype_ctypes._from_ctypes_array (t) protected
Definition at line 32 of file _dtype_ctypes.py.
_from_ctypes_scalar()
numpy.core._dtype_ctypes._from_ctypes_scalar (t) protected
Return the dtype type with endianness included if it's the case
Definition at line 71 of file _dtype_ctypes.py.
References dtype_from_ctypes_type().
Referenced by dtype_from_ctypes_type().
_from_ctypes_structure()
numpy.core._dtype_ctypes._from_ctypes_structure (t) protected
Definition at line 36 of file _dtype_ctypes.py.
_from_ctypes_union()
numpy.core._dtype_ctypes._from_ctypes_union (t) protected
Definition at line 83 of file _dtype_ctypes.py.
dtype_from_ctypes_type()
numpy.core._dtype_ctypes.dtype_from_ctypes_type (t)
Construct a dtype object from a ctypes type
Definition at line 100 of file _dtype_ctypes.py.
References _from_ctypes_scalar().
Referenced by _from_ctypes_scalar().