Code Cloning Analysis: scipy.integrate.tests.test_banded_ode_solvers Namespace Reference
scipy.integrate.tests.test_banded_ode_solvers Namespace Reference
Functions
_band_count (a)
_linear_func (t, y, a)
_linear_jac (t, y, a)
_linear_banded_jac (t, y, a)
_solve_linear_sys (a, y0, tend=1, dt=0.1, solver=None, method='bdf', use_jac=True, with_jacobian=False, banded=False)
_analytical_solution (a, y0, t)
test_banded_ode_solvers ()
Function Documentation
_analytical_solution()
scipy.integrate.tests.test_banded_ode_solvers._analytical_solution (a, y0, t) protected
Analytical solution to the linear differential equations dy/dt = a*y.
The solution is only valid if `a` is diagonalizable.
Returns a 2-D array with shape (len(t), len(y0)).
Definition at line 112 of file test_banded_ode_solvers.py.
References _analytical_solution(), and _solve_linear_sys().
Referenced by _analytical_solution().
_band_count()
scipy.integrate.tests.test_banded_ode_solvers._band_count (a) protected
Returns ml and mu, the lower and upper band sizes of a.
Definition at line 7 of file test_banded_ode_solvers.py.
Referenced by _linear_banded_jac(), and _solve_linear_sys().
_linear_banded_jac()
scipy.integrate.tests.test_banded_ode_solvers._linear_banded_jac (t, y, a) protected
Banded Jacobian.
Definition at line 33 of file test_banded_ode_solvers.py.
References _band_count().
_linear_func()
scipy.integrate.tests.test_banded_ode_solvers._linear_func (t, y, a) protected
Linear system dy/dt = a * y
Definition at line 23 of file test_banded_ode_solvers.py.
_linear_jac()
scipy.integrate.tests.test_banded_ode_solvers._linear_jac (t, y, a) protected
Jacobian of a * y is a.
Definition at line 28 of file test_banded_ode_solvers.py.
_solve_linear_sys()
scipy.integrate.tests.test_banded_ode_solvers._solve_linear_sys (a, y0, tend = 1, dt = 0.1, solver = None, method = 'bdf', use_jac = True, with_jacobian = False, banded = False) protected
Use scipy.integrate.ode to solve a linear system of ODEs.
a : square ndarray
    Matrix of the linear system to be solved.
y0 : ndarray
    Initial condition
tend : float
    Stop time.
dt : float
    Step size of the output.
solver : str
    If not None, this must be "vode", "lsoda" or "zvode".
method : str
    Either "bdf" or "adams".
use_jac : bool
    Determines if the jacobian function is passed to ode().
with_jacobian : bool
    Passed to ode.set_integrator().
banded : bool
    Determines whether a banded or full jacobian is used.
    If `banded` is True, `lband` and `uband` are determined by the
    values in `a`.
Definition at line 43 of file test_banded_ode_solvers.py.
References _band_count().
Referenced by _analytical_solution().
test_banded_ode_solvers()
scipy.integrate.tests.test_banded_ode_solvers.test_banded_ode_solvers ()
Definition at line 127 of file test_banded_ode_solvers.py.