Code Cloning Analysis: sklearn.cluster._agglomerative Namespace Reference
sklearn.cluster._agglomerative Namespace Reference
Classes
class AgglomerativeClustering
class FeatureAgglomeration
Functions
_fix_connectivity (X, connectivity, affinity)
For non fully-connected graphs.
_single_linkage_tree (connectivity, n_samples, n_nodes, n_clusters, n_connected_components, return_distance)
ward_tree (X, *, connectivity=None, n_clusters=None, return_distance=False)
Hierarchical tree building functions.
linkage_tree (X, connectivity=None, n_clusters=None, linkage="complete", affinity="euclidean", return_distance=False)
_complete_linkage (*args, **kwargs)
_average_linkage (*args, **kwargs)
_single_linkage (*args, **kwargs)
_hc_cut (n_clusters, children, n_leaves)
Functions for cutting hierarchical clustering tree.
Variables
_TREE_BUILDERS
Detailed Description
Hierarchical Agglomerative Clustering
These routines perform some hierarchical agglomerative clustering of some
input data.
Function Documentation
_average_linkage()
sklearn.cluster._agglomerative._average_linkage (* args, ** kwargs) protected
Definition at line 708 of file _agglomerative.py.
_complete_linkage()
sklearn.cluster._agglomerative._complete_linkage (* args, ** kwargs) protected
Definition at line 703 of file _agglomerative.py.
_fix_connectivity()
sklearn.cluster._agglomerative._fix_connectivity (X, connectivity, affinity) protected
For non fully-connected graphs.
Fixes the connectivity matrix.
The different steps are:
- copies it
- makes it symmetric
- converts it to LIL if necessary
- completes it if necessary.
Parameters
----------
X : array-like of shape (n_samples, n_features)
    Feature matrix representing `n_samples` samples to be clustered.
connectivity : sparse matrix, default=None
    Connectivity matrix. Defines for each sample the neighboring samples
    following a given structure of the data. The matrix is assumed to
    be symmetric and only the upper triangular half is used.
    Default is `None`, i.e, the Ward algorithm is unstructured.
affinity : {"euclidean", "precomputed"}, default="euclidean"
    Which affinity to use. At the moment `precomputed` and
    ``euclidean`` are supported. `euclidean` uses the
    negative squared Euclidean distance between points.
Returns
-------
connectivity : sparse matrix
    The fixed connectivity matrix.
n_connected_components : int
    The number of connected components in the graph.
Definition at line 46 of file _agglomerative.py.
Referenced by linkage_tree(), and ward_tree().
_hc_cut()
sklearn.cluster._agglomerative._hc_cut (n_clusters, children, n_leaves) protected
Functions for cutting hierarchical clustering tree.
Function cutting the ward tree for a given number of clusters.
Parameters
----------
n_clusters : int or ndarray
    The number of clusters to form.
children : ndarray of shape (n_nodes-1, 2)
    The children of each non-leaf node. Values less than `n_samples`
    correspond to leaves of the tree which are the original samples.
    A node `i` greater than or equal to `n_samples` is a non-leaf
    node and has children `children_[i - n_samples]`. Alternatively
    at the i-th iteration, children[i][0] and children[i][1]
    are merged to form node `n_samples + i`.
n_leaves : int
    Number of leaves of the tree.
Returns
-------
labels : array [n_samples]
    Cluster labels for each point.
Definition at line 729 of file _agglomerative.py.
Referenced by sklearn.cluster._agglomerative.AgglomerativeClustering._fit().
_single_linkage()
sklearn.cluster._agglomerative._single_linkage (* args, ** kwargs) protected
Definition at line 713 of file _agglomerative.py.
_single_linkage_tree()
sklearn.cluster._agglomerative._single_linkage_tree (connectivity, n_samples, n_nodes, n_clusters, n_connected_components, return_distance) protected
Perform single linkage clustering on sparse data via the minimum
spanning tree from scipy.sparse.csgraph, then using union-find to label.
The parent array is then generated by walking through the tree.
Definition at line 122 of file _agglomerative.py.
Referenced by linkage_tree().
linkage_tree()
sklearn.cluster._agglomerative.linkage_tree (X, connectivity = None, n_clusters = None, linkage = "complete", affinity = "euclidean", return_distance = False)
Linkage agglomerative clustering based on a Feature matrix.
The inertia matrix uses a Heapq-based representation.
This is the structured version, that takes into account some topological
structure between samples.
Read more in the :ref:`User Guide <hierarchical_clustering>`.
Parameters
----------
X : array-like of shape (n_samples, n_features)
    Feature matrix representing `n_samples` samples to be clustered.
connectivity : sparse matrix, default=None
    Connectivity matrix. Defines for each sample the neighboring samples
    following a given structure of the data. The matrix is assumed to
    be symmetric and only the upper triangular half is used.
    Default is `None`, i.e, the Ward algorithm is unstructured.
n_clusters : int, default=None
    Stop early the construction of the tree at `n_clusters`. This is
    useful to decrease computation time if the number of clusters is
    not small compared to the number of samples. In this case, the
    complete tree is not computed, thus the 'children' output is of
    limited use, and the 'parents' output should rather be used.
    This option is valid only when specifying a connectivity matrix.
linkage : {"average", "complete", "single"}, default="complete"
    Which linkage criteria to use. The linkage criterion determines which
    distance to use between sets of observation.
        - "average" uses the average of the distances of each observation of
          the two sets.
        - "complete" or maximum linkage uses the maximum distances between
          all observations of the two sets.
        - "single" uses the minimum of the distances between all
          observations of the two sets.
affinity : str or callable, default='euclidean'
    Which metric to use. Can be 'euclidean', 'manhattan', or any
    distance known to paired distance (see metric.pairwise).
return_distance : bool, default=False
    Whether or not to return the distances between the clusters.
Returns
-------
children : ndarray of shape (n_nodes-1, 2)
    The children of each non-leaf node. Values less than `n_samples`
    correspond to leaves of the tree which are the original samples.
    A node `i` greater than or equal to `n_samples` is a non-leaf
    node and has children `children_[i - n_samples]`. Alternatively
    at the i-th iteration, children[i][0] and children[i][1]
    are merged to form node `n_samples + i`.
n_connected_components : int
    The number of connected components in the graph.
n_leaves : int
    The number of leaves in the tree.
parents : ndarray of shape (n_nodes,) or None
    The parent of each node. Only returned when a connectivity matrix
    is specified, elsewhere 'None' is returned.
distances : ndarray of shape (n_nodes-1,)
    Returned when `return_distance` is set to `True`.
    distances[i] refers to the distance between children[i][0] and
    children[i][1] when they are merged.
See Also
--------
ward_tree : Hierarchical clustering with ward linkage.
Definition at line 426 of file _agglomerative.py.
References _fix_connectivity(), _single_linkage_tree(), and linkage_tree().
Referenced by linkage_tree().
ward_tree()
sklearn.cluster._agglomerative.ward_tree (X, * , connectivity = None, n_clusters = None, return_distance = False)
Hierarchical tree building functions.
Ward clustering based on a Feature matrix.
Recursively merges the pair of clusters that minimally increases
within-cluster variance.
The inertia matrix uses a Heapq-based representation.
This is the structured version, that takes into account some topological
structure between samples.
Read more in the :ref:`User Guide <hierarchical_clustering>`.
Parameters
----------
X : array-like of shape (n_samples, n_features)
    Feature matrix representing `n_samples` samples to be clustered.
connectivity : {array-like, sparse matrix}, default=None
    Connectivity matrix. Defines for each sample the neighboring samples
    following a given structure of the data. The matrix is assumed to
    be symmetric and only the upper triangular half is used.
    Default is None, i.e, the Ward algorithm is unstructured.
n_clusters : int, default=None
    `n_clusters` should be less than `n_samples`.  Stop early the
    construction of the tree at `n_clusters.` This is useful to decrease
    computation time if the number of clusters is not small compared to the
    number of samples. In this case, the complete tree is not computed, thus
    the 'children' output is of limited use, and the 'parents' output should
    rather be used. This option is valid only when specifying a connectivity
    matrix.
return_distance : bool, default=False
    If `True`, return the distance between the clusters.
Returns
-------
children : ndarray of shape (n_nodes-1, 2)
    The children of each non-leaf node. Values less than `n_samples`
    correspond to leaves of the tree which are the original samples.
    A node `i` greater than or equal to `n_samples` is a non-leaf
    node and has children `children_[i - n_samples]`. Alternatively
    at the i-th iteration, children[i][0] and children[i][1]
    are merged to form node `n_samples + i`.
n_connected_components : int
    The number of connected components in the graph.
n_leaves : int
    The number of leaves in the tree.
parents : ndarray of shape (n_nodes,) or None
    The parent of each node. Only returned when a connectivity matrix
    is specified, elsewhere 'None' is returned.
distances : ndarray of shape (n_nodes-1,)
    Only returned if `return_distance` is set to `True` (for compatibility).
    The distances between the centers of the nodes. `distances[i]`
    corresponds to a weighted Euclidean distance between
    the nodes `children[i, 1]` and `children[i, 2]`. If the nodes refer to
    leaves of the tree, then `distances[i]` is their unweighted Euclidean
    distance. Distances are updated in the following way
    (from scipy.hierarchy.linkage):
    The new entry :math:`d(u,v)` is computed as follows,
    .. math::
       d(u,v) = \\sqrt{\\frac{|v|+|s|}
                           {T}d(v,s)^2
                    + \\frac{|v|+|t|}
                           {T}d(v,t)^2
                    - \\frac{|v|}
                           {T}d(s,t)^2}
    where :math:`u` is the newly joined cluster consisting of
    clusters :math:`s` and :math:`t`, :math:`v` is an unused
    cluster in the forest, :math:`T=|v|+|s|+|t|`, and
    :math:`|*|` is the cardinality of its argument. This is also
    known as the incremental algorithm.
Examples
--------
>>> import numpy as np
>>> from sklearn.cluster import ward_tree
>>> X = np.array([[1, 2], [1, 4], [1, 0],
...               [4, 2], [4, 4], [4, 0]])
>>> children, n_connected_components, n_leaves, parents = ward_tree(X)
>>> children
array([[0, 1],
       [3, 5],
       [2, 6],
       [4, 7],
       [8, 9]])
>>> n_connected_components
1
>>> n_leaves
6
Definition at line 191 of file _agglomerative.py.
References _fix_connectivity().
Variable Documentation
_TREE_BUILDERS
sklearn.cluster._agglomerative._TREE_BUILDERS protected
Initial value:
=  dict(
    ward=ward_tree,
    complete=_complete_linkage,
    average=_average_linkage,
    single=_single_linkage,
)
Definition at line 718 of file _agglomerative.py.