Code Cloning Analysis: matplotlib.cm.ColormapRegistry Class Reference
matplotlib.cm.ColormapRegistry Class Reference
Public Member Functions
__init__ (self, cmaps)
__getitem__ (self, item)
__iter__ (self)
__len__ (self)
__str__ (self)
__call__ (self)
register (self, cmap, *, name=None, force=False)
unregister (self, name)
get_cmap (self, cmap)
Protected Attributes
_cmaps = cmaps
_builtin_cmaps = tuple(cmaps)
Detailed Description
Container for colormaps that are known to Matplotlib by name.
The universal registry instance is `matplotlib.colormaps`. There should be
no need for users to instantiate `.ColormapRegistry` themselves.
Read access uses a dict-like interface mapping names to `.Colormap`\s::
    import matplotlib as mpl
    cmap = mpl.colormaps['viridis']
Returned `.Colormap`\s are copies, so that their modification does not
change the global definition of the colormap.
Additional colormaps can be added via `.ColormapRegistry.register`::
    mpl.colormaps.register(my_colormap)
To get a list of all registered colormaps, you can do::
    from matplotlib import colormaps
    list(colormaps)
Definition at line 66 of file cm.py.
Constructor & Destructor Documentation
__init__()
matplotlib.cm.ColormapRegistry.__init__ (self, cmaps)
Definition at line 90 of file cm.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__call__()
matplotlib.cm.ColormapRegistry.__call__ (self)
Return a list of the registered colormap names.
This exists only for backward-compatibility in `.pyplot` which had a
``plt.colormaps()`` method. The recommended way to get this list is
now ``list(colormaps)``.
Definition at line 110 of file cm.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), scipy.interpolate._fitpack2.SphereBivariateSpline.ev(), matplotlib.ticker.Formatter.format_data(), and matplotlib.ticker.LogFormatter.format_data().
__getitem__()
matplotlib.cm.ColormapRegistry.__getitem__ (self, item)
Definition at line 94 of file cm.py.
__iter__()
matplotlib.cm.ColormapRegistry.__iter__ (self)
Definition at line 100 of file cm.py.
__len__()
matplotlib.cm.ColormapRegistry.__len__ (self)
Definition at line 103 of file cm.py.
__str__()
matplotlib.cm.ColormapRegistry.__str__ (self)
Definition at line 106 of file cm.py.
Referenced by numpy.polynomial._polybase.ABCPolyBase._get_coefficients().
get_cmap()
matplotlib.cm.ColormapRegistry.get_cmap (self, cmap)
Return a color map specified through *cmap*.
Parameters
----------
cmap : str or `~matplotlib.colors.Colormap` or None
    - if a `.Colormap`, return it
    - if a string, look it up in ``mpl.colormaps``
    - if None, return the Colormap defined in :rc:`image.cmap`
Returns
-------
Colormap
Definition at line 202 of file cm.py.
References matplotlib.cm._gen_cmap_registry().
register()
matplotlib.cm.ColormapRegistry.register (self, cmap, * , name = None, force = False)
Register a new colormap.
The colormap name can then be used as a string argument to any ``cmap``
parameter in Matplotlib. It is also available in ``pyplot.get_cmap``.
The colormap registry stores a copy of the given colormap, so that
future changes to the original colormap instance do not affect the
registered colormap. Think of this as the registry taking a snapshot
of the colormap at registration.
Parameters
----------
cmap : matplotlib.colors.Colormap
    The colormap to register.
name : str, optional
    The name for the colormap. If not given, ``cmap.name`` is used.
force : bool, default: False
    If False, a ValueError is raised if trying to overwrite an already
    registered name. True supports overwriting registered colormaps
    other than the builtin colormaps.
Definition at line 120 of file cm.py.
References _builtin_cmaps, and _cmaps.
unregister()
matplotlib.cm.ColormapRegistry.unregister (self, name)
Remove a colormap from the registry.
You cannot remove built-in colormaps.
If the named colormap is not registered, returns with no error, raises
if you try to de-register a default colormap.
.. warning::
    Colormap names are currently a shared namespace that may be used
    by multiple packages. Use `unregister` only if you know you
    have registered that name before. In particular, do not
    unregister just in case to clean the name before registering a
    new colormap.
Parameters
----------
name : str
    The name of the colormap to be removed.
Raises
------
ValueError
    If you try to remove a default built-in colormap.
Definition at line 170 of file cm.py.
References _builtin_cmaps, and _cmaps.
Member Data Documentation
_builtin_cmaps
matplotlib.cm.ColormapRegistry._builtin_cmaps = tuple(cmaps) protected
Definition at line 92 of file cm.py.
Referenced by register(), and unregister().
_cmaps
matplotlib.cm.ColormapRegistry._cmaps = cmaps protected
Definition at line 91 of file cm.py.
Referenced by register(), and unregister().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/cm.py