Code Cloning Analysis: numpy.lib.histograms Namespace Reference
numpy.lib.histograms Namespace Reference
Functions
_ptp (x)
_hist_bin_sqrt (x, range)
_hist_bin_sturges (x, range)
_hist_bin_rice (x, range)
_hist_bin_scott (x, range)
_hist_bin_stone (x, range)
_hist_bin_doane (x, range)
_hist_bin_fd (x, range)
_hist_bin_auto (x, range)
_ravel_and_check_weights (a, weights)
_get_outer_edges (a, range)
_unsigned_subtract (a, b)
_get_bin_edges (a, bins, range, weights)
_search_sorted_inclusive (a, v)
_histogram_bin_edges_dispatcher (a, bins=None, range=None, weights=None)
histogram_bin_edges (a, bins=10, range=None, weights=None)
_histogram_dispatcher (a, bins=None, range=None, density=None, weights=None)
histogram (a, bins=10, range=None, density=None, weights=None)
_histogramdd_dispatcher (sample, bins=None, range=None, density=None, weights=None)
histogramdd (sample, bins=10, range=None, density=None, weights=None)
Variables
list __all__ = ['histogram', 'histogramdd', 'histogram_bin_edges']
array_function_dispatch
_range = range
dict _hist_bin_selectors
Detailed Description
Histogram-related functions
Function Documentation
_get_bin_edges()
numpy.lib.histograms._get_bin_edges (a, bins, range, weights) protected
Computes the bins used internally by `histogram`.
Parameters
==========
a : ndarray
    Ravelled data array
bins, range
    Forwarded arguments from `histogram`.
weights : ndarray, optional
    Ravelled weights array, or None
Returns
=======
bin_edges : ndarray
    Array of bin edges
uniform_bins : (Number, Number, int):
    The upper bound, lowerbound, and number of bins, used in the optimized
    implementation of `histogram` that works on uniform bins.
Definition at line 360 of file histograms.py.
References _get_outer_edges(), and _unsigned_subtract().
Referenced by histogram(), and histogram_bin_edges().
_get_outer_edges()
numpy.lib.histograms._get_outer_edges (a, range) protected
Determine the outer bin edges to use, from either the data or the range
argument
Definition at line 304 of file histograms.py.
Referenced by _get_bin_edges(), and histogramdd().
_hist_bin_auto()
numpy.lib.histograms._hist_bin_auto (x, range) protected
Histogram bin estimator that uses the minimum width of the
Freedman-Diaconis and Sturges estimators if the FD bin width is non-zero.
If the bin width from the FD estimator is 0, the Sturges estimator is used.
The FD estimator is usually the most robust method, but its width
estimate tends to be too large for small `x` and bad for data with limited
variance. The Sturges estimator is quite good for small (<1000) datasets
and is the default in the R language. This method gives good off-the-shelf
behaviour.
.. versionchanged:: 1.15.0
If there is limited variance the IQR can be 0, which results in the
FD bin width being 0 too. This is not a valid bin width, so
``np.histogram_bin_edges`` chooses 1 bin instead, which may not be optimal.
If the IQR is 0, it's unlikely any variance-based estimators will be of
use, so we revert to the Sturges estimator, which only uses the size of the
dataset in its calculation.
Parameters
----------
x : array_like
    Input data that is to be histogrammed, trimmed to range. May not
    be empty.
Returns
-------
h : An estimate of the optimal bin width for the given data.
See Also
--------
_hist_bin_fd, _hist_bin_sturges
Definition at line 229 of file histograms.py.
References _hist_bin_fd(), _hist_bin_sturges(), and numpy.core.fromnumeric.min().
_hist_bin_doane()
numpy.lib.histograms._hist_bin_doane (x, range) protected
Doane's histogram bin estimator.
Improved version of Sturges' formula which works better for
non-normal data. See
stats.stackexchange.com/questions/55134/doanes-formula-for-histogram-binning
Parameters
----------
x : array_like
    Input data that is to be histogrammed, trimmed to range. May not
    be empty.
Returns
-------
h : An estimate of the optimal bin width for the given data.
Definition at line 164 of file histograms.py.
References _ptp().
_hist_bin_fd()
numpy.lib.histograms._hist_bin_fd (x, range) protected
The Freedman-Diaconis histogram bin estimator.
The Freedman-Diaconis rule uses interquartile range (IQR) to
estimate binwidth. It is considered a variation of the Scott rule
with more robustness as the IQR is less affected by outliers than
the standard deviation. However, the IQR depends on fewer points
than the standard deviation, so it is less accurate, especially for
long tailed distributions.
If the IQR is 0, this function returns 0 for the bin width.
Binwidth is inversely proportional to the cube root of data size
(asymptotically optimal).
Parameters
----------
x : array_like
    Input data that is to be histogrammed, trimmed to range. May not
    be empty.
Returns
-------
h : An estimate of the optimal bin width for the given data.
Definition at line 199 of file histograms.py.
Referenced by _hist_bin_auto().
_hist_bin_rice()
numpy.lib.histograms._hist_bin_rice (x, range) protected
Rice histogram bin estimator.
Another simple estimator with no normality assumption. It has better
performance for large data than Sturges, but tends to overestimate
the number of bins. The number of bins is proportional to the cube
root of data size (asymptotically optimal). The estimate depends
only on size of the data.
Parameters
----------
x : array_like
    Input data that is to be histogrammed, trimmed to range. May not
    be empty.
Returns
-------
h : An estimate of the optimal bin width for the given data.
Definition at line 76 of file histograms.py.
References _ptp().
_hist_bin_scott()
numpy.lib.histograms._hist_bin_scott (x, range) protected
Scott histogram bin estimator.
The binwidth is proportional to the standard deviation of the data
and inversely proportional to the cube root of data size
(asymptotically optimal).
Parameters
----------
x : array_like
    Input data that is to be histogrammed, trimmed to range. May not
    be empty.
Returns
-------
h : An estimate of the optimal bin width for the given data.
Definition at line 100 of file histograms.py.
_hist_bin_sqrt()
numpy.lib.histograms._hist_bin_sqrt (x, range) protected
Square root histogram bin estimator.
Bin width is inversely proportional to the data size. Used by many
programs for its simplicity.
Parameters
----------
x : array_like
    Input data that is to be histogrammed, trimmed to range. May not
    be empty.
Returns
-------
h : An estimate of the optimal bin width for the given data.
Definition at line 32 of file histograms.py.
References _ptp().
_hist_bin_stone()
numpy.lib.histograms._hist_bin_stone (x, range) protected
Histogram bin estimator based on minimizing the estimated integrated squared error (ISE).
The number of bins is chosen by minimizing the estimated ISE against the unknown true distribution.
The ISE is estimated using cross-validation and can be regarded as a generalization of Scott's rule.
https://en.wikipedia.org/wiki/Histogram#Scott.27s_normal_reference_rule
This paper by Stone appears to be the origination of this rule.
http://digitalassets.lib.berkeley.edu/sdtr/ucb/text/34.pdf
Parameters
----------
x : array_like
    Input data that is to be histogrammed, trimmed to range. May not
    be empty.
range : (float, float)
    The lower and upper range of the bins.
Returns
-------
h : An estimate of the optimal bin width for the given data.
Definition at line 122 of file histograms.py.
References _ptp(), numpy.core.fromnumeric.max(), and numpy.core.fromnumeric.min().
_hist_bin_sturges()
numpy.lib.histograms._hist_bin_sturges (x, range) protected
Sturges histogram bin estimator.
A very simplistic estimator based on the assumption of normality of
the data. This estimator has poor performance for non-normal data,
which becomes especially obvious for large data sets. The estimate
depends only on size of the data.
Parameters
----------
x : array_like
    Input data that is to be histogrammed, trimmed to range. May not
    be empty.
Returns
-------
h : An estimate of the optimal bin width for the given data.
Definition at line 53 of file histograms.py.
References _ptp().
Referenced by _hist_bin_auto().
_histogram_bin_edges_dispatcher()
numpy.lib.histograms._histogram_bin_edges_dispatcher (a, bins = None, range = None, weights = None) protected
Definition at line 466 of file histograms.py.
_histogram_dispatcher()
numpy.lib.histograms._histogram_dispatcher (a, bins = None, range = None, density = None, weights = None) protected
Definition at line 673 of file histograms.py.
_histogramdd_dispatcher()
numpy.lib.histograms._histogramdd_dispatcher (sample, bins = None, range = None, density = None, weights = None) protected
Definition at line 890 of file histograms.py.
_ptp()
numpy.lib.histograms._ptp (x) protected
Peak-to-peak value of x.
This implementation avoids the problem of signed integer arrays having a
peak-to-peak value that cannot be represented with the array's data type.
This function returns an unsigned value for signed integer arrays.
Definition at line 22 of file histograms.py.
References _unsigned_subtract().
Referenced by _hist_bin_doane(), _hist_bin_rice(), _hist_bin_sqrt(), _hist_bin_stone(), and _hist_bin_sturges().
_ravel_and_check_weights()
numpy.lib.histograms._ravel_and_check_weights (a, weights) protected
 Check a and weights have matching shapes, and ravel both
Definition at line 283 of file histograms.py.
Referenced by histogram(), and histogram_bin_edges().
_search_sorted_inclusive()
numpy.lib.histograms._search_sorted_inclusive (a, v) protected
Like `searchsorted`, but where the last item in `v` is placed on the right.
In the context of a histogram, this makes the last bin edge inclusive
Definition at line 454 of file histograms.py.
Referenced by histogram().
_unsigned_subtract()
numpy.lib.histograms._unsigned_subtract (a, b) protected
Subtract two values where a >= b, and produce an unsigned result
This is needed when finding the difference between the upper and lower
bound of an int16 histogram
Definition at line 334 of file histograms.py.
Referenced by _get_bin_edges(), _ptp(), and histogram().
histogram()
numpy.lib.histograms.histogram (a, bins = 10, range = None, density = None, weights = None)
Compute the histogram of a dataset.
Parameters
----------
a : array_like
    Input data. The histogram is computed over the flattened array.
bins : int or sequence of scalars or str, optional
    If `bins` is an int, it defines the number of equal-width
    bins in the given range (10, by default). If `bins` is a
    sequence, it defines a monotonically increasing array of bin edges,
    including the rightmost edge, allowing for non-uniform bin widths.
    .. versionadded:: 1.11.0
    If `bins` is a string, it defines the method used to calculate the
    optimal bin width, as defined by `histogram_bin_edges`.
range : (float, float), optional
    The lower and upper range of the bins.  If not provided, range
    is simply ``(a.min(), a.max())``.  Values outside the range are
    ignored. The first element of the range must be less than or
    equal to the second. `range` affects the automatic bin
    computation as well. While bin width is computed to be optimal
    based on the actual data within `range`, the bin count will fill
    the entire range including portions containing no data.
weights : array_like, optional
    An array of weights, of the same shape as `a`.  Each value in
    `a` only contributes its associated weight towards the bin count
    (instead of 1). If `density` is True, the weights are
    normalized, so that the integral of the density over the range
    remains 1.
density : bool, optional
    If ``False``, the result will contain the number of samples in
    each bin. If ``True``, the result is the value of the
    probability *density* function at the bin, normalized such that
    the *integral* over the range is 1. Note that the sum of the
    histogram values will not be equal to 1 unless bins of unity
    width are chosen; it is not a probability *mass* function.
Returns
-------
hist : array
    The values of the histogram. See `density` and `weights` for a
    description of the possible semantics.
bin_edges : array of dtype float
    Return the bin edges ``(length(hist)+1)``.
See Also
--------
histogramdd, bincount, searchsorted, digitize, histogram_bin_edges
Notes
-----
All but the last (righthand-most) bin is half-open.  In other words,
if `bins` is::
  [1, 2, 3, 4]
then the first bin is ``[1, 2)`` (including 1, but excluding 2) and
the second ``[2, 3)``.  The last bin, however, is ``[3, 4]``, which
*includes* 4.
Examples
--------
>>> np.histogram([1, 2, 1], bins=[0, 1, 2, 3])
(array([0, 2, 1]), array([0, 1, 2, 3]))
>>> np.histogram(np.arange(4), bins=np.arange(5), density=True)
(array([0.25, 0.25, 0.25, 0.25]), array([0, 1, 2, 3, 4]))
>>> np.histogram([[1, 2, 1], [1, 0, 1]], bins=[0,1,2,3])
(array([1, 4, 1]), array([0, 1, 2, 3]))
>>> a = np.arange(5)
>>> hist, bin_edges = np.histogram(a, density=True)
>>> hist
array([0.5, 0. , 0.5, 0. , 0. , 0.5, 0. , 0.5, 0. , 0.5])
>>> hist.sum()
2.4999999999999996
>>> np.sum(hist * np.diff(bin_edges))
1.0
.. versionadded:: 1.11.0
Automated Bin Selection Methods example, using 2 peak random data
with 2000 points:
>>> import matplotlib.pyplot as plt
>>> rng = np.random.RandomState(10)  # deterministic random data
>>> a = np.hstack((rng.normal(size=1000),
...                rng.normal(loc=5, scale=2, size=1000)))
>>> _ = plt.hist(a, bins='auto')  # arguments are passed to np.histogram
>>> plt.title("Histogram with 'auto' bins")
Text(0.5, 1.0, "Histogram with 'auto' bins")
>>> plt.show()
Definition at line 679 of file histograms.py.
References _get_bin_edges(), _ravel_and_check_weights(), _search_sorted_inclusive(), and _unsigned_subtract().
Referenced by numpy.lib.tests.test_histograms.TestHistogramdd.test_edge_dtype().
histogram_bin_edges()
numpy.lib.histograms.histogram_bin_edges (a, bins = 10, range = None, weights = None)
Function to calculate only the edges of the bins used by the `histogram`
function.
Parameters
----------
a : array_like
    Input data. The histogram is computed over the flattened array.
bins : int or sequence of scalars or str, optional
    If `bins` is an int, it defines the number of equal-width
    bins in the given range (10, by default). If `bins` is a
    sequence, it defines the bin edges, including the rightmost
    edge, allowing for non-uniform bin widths.
    If `bins` is a string from the list below, `histogram_bin_edges` will use
    the method chosen to calculate the optimal bin width and
    consequently the number of bins (see `Notes` for more detail on
    the estimators) from the data that falls within the requested
    range. While the bin width will be optimal for the actual data
    in the range, the number of bins will be computed to fill the
    entire range, including the empty portions. For visualisation,
    using the 'auto' option is suggested. Weighted data is not
    supported for automated bin size selection.
    'auto'
        Maximum of the 'sturges' and 'fd' estimators. Provides good
        all around performance.
    'fd' (Freedman Diaconis Estimator)
        Robust (resilient to outliers) estimator that takes into
        account data variability and data size.
    'doane'
        An improved version of Sturges' estimator that works better
        with non-normal datasets.
    'scott'
        Less robust estimator that takes into account data variability
        and data size.
    'stone'
        Estimator based on leave-one-out cross-validation estimate of
        the integrated squared error. Can be regarded as a generalization
        of Scott's rule.
    'rice'
        Estimator does not take variability into account, only data
        size. Commonly overestimates number of bins required.
    'sturges'
        R's default method, only accounts for data size. Only
        optimal for gaussian data and underestimates number of bins
        for large non-gaussian datasets.
    'sqrt'
        Square root (of data size) estimator, used by Excel and
        other programs for its speed and simplicity.
range : (float, float), optional
    The lower and upper range of the bins.  If not provided, range
    is simply ``(a.min(), a.max())``.  Values outside the range are
    ignored. The first element of the range must be less than or
    equal to the second. `range` affects the automatic bin
    computation as well. While bin width is computed to be optimal
    based on the actual data within `range`, the bin count will fill
    the entire range including portions containing no data.
weights : array_like, optional
    An array of weights, of the same shape as `a`.  Each value in
    `a` only contributes its associated weight towards the bin count
    (instead of 1). This is currently not used by any of the bin estimators,
    but may be in the future.
Returns
-------
bin_edges : array of dtype float
    The edges to pass into `histogram`
See Also
--------
histogram
Notes
-----
The methods to estimate the optimal number of bins are well founded
in literature, and are inspired by the choices R provides for
histogram visualisation. Note that having the number of bins
proportional to :math:`n^{1/3}` is asymptotically optimal, which is
why it appears in most estimators. These are simply plug-in methods
that give good starting points for number of bins. In the equations
below, :math:`h` is the binwidth and :math:`n_h` is the number of
bins. All estimators that compute bin counts are recast to bin width
using the `ptp` of the data. The final bin count is obtained from
``np.round(np.ceil(range / h))``. The final bin width is often less
than what is returned by the estimators below.
'auto' (maximum of the 'sturges' and 'fd' estimators)
    A compromise to get a good value. For small datasets the Sturges
    value will usually be chosen, while larger datasets will usually
    default to FD.  Avoids the overly conservative behaviour of FD
    and Sturges for small and large datasets respectively.
    Switchover point is usually :math:`a.size \approx 1000`.
'fd' (Freedman Diaconis Estimator)
    .. math:: h = 2 \frac{IQR}{n^{1/3}}
    The binwidth is proportional to the interquartile range (IQR)
    and inversely proportional to cube root of a.size. Can be too
    conservative for small datasets, but is quite good for large
    datasets. The IQR is very robust to outliers.
'scott'
    .. math:: h = \sigma \sqrt[3]{\frac{24 \sqrt{\pi}}{n}}
    The binwidth is proportional to the standard deviation of the
    data and inversely proportional to cube root of ``x.size``. Can
    be too conservative for small datasets, but is quite good for
    large datasets. The standard deviation is not very robust to
    outliers. Values are very similar to the Freedman-Diaconis
    estimator in the absence of outliers.
'rice'
    .. math:: n_h = 2n^{1/3}
    The number of bins is only proportional to cube root of
    ``a.size``. It tends to overestimate the number of bins and it
    does not take into account data variability.
'sturges'
    .. math:: n_h = \log _{2}(n) + 1
    The number of bins is the base 2 log of ``a.size``.  This
    estimator assumes normality of data and is too conservative for
    larger, non-normal datasets. This is the default method in R's
    ``hist`` method.
'doane'
    .. math:: n_h = 1 + \log_{2}(n) +
                    \log_{2}\left(1 + \frac{|g_1|}{\sigma_{g_1}}\right)
        g_1 = mean\left[\left(\frac{x - \mu}{\sigma}\right)^3\right]
        \sigma_{g_1} = \sqrt{\frac{6(n - 2)}{(n + 1)(n + 3)}}
    An improved version of Sturges' formula that produces better
    estimates for non-normal datasets. This estimator attempts to
    account for the skew of the data.
'sqrt'
    .. math:: n_h = \sqrt n
    The simplest and fastest estimator. Only takes into account the
    data size.
Examples
--------
>>> arr = np.array([0, 0, 0, 1, 2, 3, 3, 4, 5])
>>> np.histogram_bin_edges(arr, bins='auto', range=(0, 1))
array([0.  , 0.25, 0.5 , 0.75, 1.  ])
>>> np.histogram_bin_edges(arr, bins=2)
array([0. , 2.5, 5. ])
For consistency with histogram, an array of pre-computed bins is
passed through unmodified:
>>> np.histogram_bin_edges(arr, [1, 2])
array([1, 2])
This function allows one set of bins to be computed, and reused across
multiple histograms:
>>> shared_bins = np.histogram_bin_edges(arr, bins='auto')
>>> shared_bins
array([0., 1., 2., 3., 4., 5.])
>>> group_id = np.array([0, 1, 1, 0, 1, 1, 0, 1, 1])
>>> hist_0, _ = np.histogram(arr[group_id == 0], bins=shared_bins)
>>> hist_1, _ = np.histogram(arr[group_id == 1], bins=shared_bins)
>>> hist_0; hist_1
array([1, 1, 0, 1, 0])
array([2, 0, 1, 1, 2])
Which gives more easily comparable results than using separate bins for
each histogram:
>>> hist_0, bins_0 = np.histogram(arr[group_id == 0], bins='auto')
>>> hist_1, bins_1 = np.histogram(arr[group_id == 1], bins='auto')
>>> hist_0; hist_1
array([1, 1, 1])
array([2, 1, 1, 2])
>>> bins_0; bins_1
array([0., 1., 2., 3.])
array([0.  , 1.25, 2.5 , 3.75, 5.  ])
Definition at line 471 of file histograms.py.
References _get_bin_edges(), and _ravel_and_check_weights().
Referenced by numpy.lib.tests.test_histograms.TestHistogramOptimBinNums.test_limited_variance().
histogramdd()
numpy.lib.histograms.histogramdd (sample, bins = 10, range = None, density = None, weights = None)
Compute the multidimensional histogram of some data.
Parameters
----------
sample : (N, D) array, or (N, D) array_like
    The data to be histogrammed.
    Note the unusual interpretation of sample when an array_like:
    * When an array, each row is a coordinate in a D-dimensional space -
      such as ``histogramdd(np.array([p1, p2, p3]))``.
    * When an array_like, each element is the list of values for single
      coordinate - such as ``histogramdd((X, Y, Z))``.
    The first form should be preferred.
bins : sequence or int, optional
    The bin specification:
    * A sequence of arrays describing the monotonically increasing bin
      edges along each dimension.
    * The number of bins for each dimension (nx, ny, ... =bins)
    * The number of bins for all dimensions (nx=ny=...=bins).
range : sequence, optional
    A sequence of length D, each an optional (lower, upper) tuple giving
    the outer bin edges to be used if the edges are not given explicitly in
    `bins`.
    An entry of None in the sequence results in the minimum and maximum
    values being used for the corresponding dimension.
    The default, None, is equivalent to passing a tuple of D None values.
density : bool, optional
    If False, the default, returns the number of samples in each bin.
    If True, returns the probability *density* function at the bin,
    ``bin_count / sample_count / bin_volume``.
weights : (N,) array_like, optional
    An array of values `w_i` weighing each sample `(x_i, y_i, z_i, ...)`.
    Weights are normalized to 1 if density is True. If density is False,
    the values of the returned histogram are equal to the sum of the
    weights belonging to the samples falling into each bin.
Returns
-------
H : ndarray
    The multidimensional histogram of sample x. See density and weights
    for the different possible semantics.
edges : list
    A list of D arrays describing the bin edges for each dimension.
See Also
--------
histogram: 1-D histogram
histogram2d: 2-D histogram
Examples
--------
>>> r = np.random.randn(100,3)
>>> H, edges = np.histogramdd(r, bins = (5, 8, 4))
>>> H.shape, edges[0].size, edges[1].size, edges[2].size
((5, 8, 4), 6, 9, 5)
Definition at line 902 of file histograms.py.
References _get_outer_edges(), numpy.core.fromnumeric.any(), and numpy.core.fromnumeric.reshape().
Referenced by numpy.lib.twodim_base.histogram2d(), numpy.lib.tests.test_histograms.TestHistogramdd.test_edge_dtype(), and numpy.lib.tests.test_histograms.TestHistogramdd.test_equal_edges().
Variable Documentation
__all__
list numpy.lib.histograms.__all__ = ['histogram', 'histogramdd', 'histogram_bin_edges'] private
Definition at line 12 of file histograms.py.
_hist_bin_selectors
dict numpy.lib.histograms._hist_bin_selectors protected
Initial value:
=  {'stone': _hist_bin_stone,
                       'auto': _hist_bin_auto,
                       'doane': _hist_bin_doane,
                       'fd': _hist_bin_fd,
                       'rice': _hist_bin_rice,
                       'scott': _hist_bin_scott,
                       'sqrt': _hist_bin_sqrt,
                       'sturges': _hist_bin_sturges}
Definition at line 273 of file histograms.py.
_range
numpy.lib.histograms._range = range protected
Definition at line 19 of file histograms.py.
array_function_dispatch
numpy.lib.histograms.array_function_dispatch
Initial value:
=  functools.partial(
    overrides.array_function_dispatch, module='numpy')
Definition at line 14 of file histograms.py.