Code Cloning Analysis: pip._vendor.requests.cookies.MockRequest Class Reference
pip._vendor.requests.cookies.MockRequest Class Reference
Public Member Functions
__init__ (self, request)
get_type (self)
get_host (self)
get_origin_req_host (self)
get_full_url (self)
is_unverifiable (self)
has_header (self, name)
get_header (self, name, default=None)
add_header (self, key, val)
add_unredirected_header (self, name, value)
get_new_headers (self)
unverifiable (self)
origin_req_host (self)
host (self)
Public Attributes
type = urlparse(self._r.url).scheme
Protected Attributes
_r = request
dict _new_headers = {}
Detailed Description
Wraps a `requests.Request` to mimic a `urllib2.Request`.
The code in `cookielib.CookieJar` expects this interface in order to correctly
manage cookie policies, i.e., determine whether a cookie can be set, given the
domains of the request and the cookie.
The original request object is read-only. The client is responsible for collecting
the new headers via `get_new_headers()` and interpreting them appropriately. You
probably want `get_cookie_header`, defined below.
Definition at line 23 of file cookies.py.
Constructor & Destructor Documentation
__init__()
pip._vendor.requests.cookies.MockRequest.__init__ (self, request)
Definition at line 35 of file cookies.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
add_header()
pip._vendor.requests.cookies.MockRequest.add_header (self, key, val)
cookielib has no legitimate use for this method; add it back if you find one.
Definition at line 78 of file cookies.py.
References _new_headers, get_host(), get_origin_req_host(), and is_unverifiable().
add_unredirected_header()
pip._vendor.requests.cookies.MockRequest.add_unredirected_header (self, name, value)
Definition at line 84 of file cookies.py.
get_full_url()
pip._vendor.requests.cookies.MockRequest.get_full_url (self)
Definition at line 49 of file cookies.py.
get_header()
pip._vendor.requests.cookies.MockRequest.get_header (self, name, default = None)
Definition at line 75 of file cookies.py.
get_host()
pip._vendor.requests.cookies.MockRequest.get_host (self)
Definition at line 43 of file cookies.py.
Referenced by add_header().
get_new_headers()
pip._vendor.requests.cookies.MockRequest.get_new_headers (self)
Definition at line 87 of file cookies.py.
get_origin_req_host()
pip._vendor.requests.cookies.MockRequest.get_origin_req_host (self)
Definition at line 46 of file cookies.py.
Referenced by add_header().
get_type()
pip._vendor.requests.cookies.MockRequest.get_type (self)
Definition at line 40 of file cookies.py.
has_header()
pip._vendor.requests.cookies.MockRequest.has_header (self, name)
Definition at line 72 of file cookies.py.
host()
pip._vendor.requests.cookies.MockRequest.host (self)
Definition at line 99 of file cookies.py.
is_unverifiable()
pip._vendor.requests.cookies.MockRequest.is_unverifiable (self)
Definition at line 69 of file cookies.py.
Referenced by add_header().
origin_req_host()
pip._vendor.requests.cookies.MockRequest.origin_req_host (self)
Definition at line 95 of file cookies.py.
unverifiable()
pip._vendor.requests.cookies.MockRequest.unverifiable (self)
Definition at line 91 of file cookies.py.
Member Data Documentation
_new_headers
dict pip._vendor.requests.cookies.MockRequest._new_headers = {} protected
Definition at line 37 of file cookies.py.
Referenced by add_header().
_r
pip._vendor.requests.cookies.MockRequest._r = request protected
Definition at line 36 of file cookies.py.
Referenced by pip._vendor.resolvelib.resolvers.Resolution._backjump(), pip._vendor.resolvelib.resolvers.Resolution._push_new_state(), and pip._vendor.resolvelib.resolvers.Resolution._remove_information_from_criteria().
type
pip._vendor.requests.cookies.MockRequest.type = urlparse(self._r.url).scheme
Definition at line 38 of file cookies.py.
Referenced by pip._vendor.rich.color.Color.__rich__(), pip._vendor.rich.color.Color.downgrade(), pip._vendor.rich.color.Color.get_ansi_codes(), pip._vendor.rich.color.Color.get_truecolor(), pip._vendor.rich.color.Color.is_default(), sklearn.utils._param_validation._InstancesOf.is_satisfied_by(), sklearn.utils._param_validation.Interval.is_satisfied_by(), sklearn.utils._param_validation.Options.is_satisfied_by(), pip._vendor.rich.color.Color.system(), and pandas.core.computation.ops.Term.update().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pip/_vendor/requests/cookies.py