Code Cloning Analysis: fontTools.pens.filterPen._DecomposingFilterPenMixin Class Reference
fontTools.pens.filterPen._DecomposingFilterPenMixin Class Reference
Public Member Functions
__init__ (self, outPen, glyphSet, skipMissingComponents=None, reverseFlipped=False, set[str]|None include=None, bool decomposeNested=True)
addComponent (self, baseGlyphName, transformation, **kwargs)
Public Attributes
include = include
decomposeNested = decomposeNested
Static Public Attributes
bool skipMissingComponents = False
Detailed Description
Mixin class that decomposes components as regular contours.
Shared by both DecomposingFilterPen and DecomposingFilterPointPen.
Takes two required parameters, another (segment or point) pen 'outPen' to draw
with, and a 'glyphSet' dict of drawable glyph objects to draw components from.
The 'skipMissingComponents' and 'reverseFlipped' optional arguments work the
same as in the DecomposingPen/DecomposingPointPen. Both are False by default.
In addition, the decomposing filter pens also take the following two options:
'include' is an optional set of component base glyph names to consider for
decomposition; the default include=None means decompose all components no matter
the base glyph name).
'decomposeNested' (bool) controls whether to recurse decomposition into nested
components of components (this only matters when 'include' was also provided);
if False, only decompose top-level components included in the set, but not
also their children.
Definition at line 168 of file filterPen.py.
Constructor & Destructor Documentation
__init__()
fontTools.pens.filterPen._DecomposingFilterPenMixin.__init__ (self, outPen, glyphSet, skipMissingComponents = None, reverseFlipped = False, set[str] | None include = None, bool decomposeNested = True)
Definition at line 194 of file filterPen.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
addComponent()
fontTools.pens.filterPen._DecomposingFilterPenMixin.addComponent (self, baseGlyphName, transformation, ** kwargs)
Definition at line 212 of file filterPen.py.
Member Data Documentation
decomposeNested
fontTools.pens.filterPen._DecomposingFilterPenMixin.decomposeNested = decomposeNested
Definition at line 210 of file filterPen.py.
include
fontTools.pens.filterPen._DecomposingFilterPenMixin.include = include
Definition at line 209 of file filterPen.py.
Referenced by pandas.core.methods.describe.DataFrameDescriber._select_data().
skipMissingComponents
bool fontTools.pens.filterPen._DecomposingFilterPenMixin.skipMissingComponents = False static
Definition at line 192 of file filterPen.py.
Referenced by fontTools.pens.pointPen.DecomposingPointPen.__init__(), and fontTools.pens.pointPen.DecomposingPointPen.addComponent().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/pens/filterPen.py