Code Cloning Analysis: sklearn.random_projection Namespace Reference
sklearn.random_projection Namespace Reference
Classes
class BaseRandomProjection
class GaussianRandomProjection
class SparseRandomProjection
Functions
johnson_lindenstrauss_min_dim (n_samples, *, eps=0.1)
_check_density (density, n_features)
_check_input_size (n_components, n_features)
_gaussian_random_matrix (n_components, n_features, random_state=None)
_sparse_random_matrix (n_components, n_features, density="auto", random_state=None)
Variables
list __all__
Detailed Description
Random projection transformers.
Random projections are a simple and computationally efficient way to
reduce the dimensionality of the data by trading a controlled amount
of accuracy (as additional variance) for faster processing times and
smaller model sizes.
The dimensions and distribution of random projections matrices are
controlled so as to preserve the pairwise distances between any two
samples of the dataset.
The main theoretical result behind the efficiency of random projection is the
`Johnson-Lindenstrauss lemma (quoting Wikipedia)
<https://en.wikipedia.org/wiki/Johnson%E2%80%93Lindenstrauss_lemma>`_:
  In mathematics, the Johnson-Lindenstrauss lemma is a result
  concerning low-distortion embeddings of points from high-dimensional
  into low-dimensional Euclidean space. The lemma states that a small set
  of points in a high-dimensional space can be embedded into a space of
  much lower dimension in such a way that distances between the points are
  nearly preserved. The map used for the embedding is at least Lipschitz,
  and can even be taken to be an orthogonal projection.
Function Documentation
_check_density()
sklearn.random_projection._check_density (density, n_features) protected
Factorize density check according to Li et al.
Definition at line 149 of file random_projection.py.
Referenced by sklearn.random_projection.SparseRandomProjection._make_random_matrix(), and _sparse_random_matrix().
_check_input_size()
sklearn.random_projection._check_input_size (n_components, n_features) protected
Factorize argument checking for random matrix generation.
Definition at line 159 of file random_projection.py.
Referenced by _gaussian_random_matrix(), and _sparse_random_matrix().
_gaussian_random_matrix()
sklearn.random_projection._gaussian_random_matrix (n_components, n_features, random_state = None) protected
Generate a dense Gaussian random matrix.
The components of the random matrix are drawn from
    N(0, 1.0 / n_components).
Read more in the :ref:`User Guide <gaussian_random_matrix>`.
Parameters
----------
n_components : int,
    Dimensionality of the target projection space.
n_features : int,
    Dimensionality of the original source space.
random_state : int, RandomState instance or None, default=None
    Controls the pseudo random number generator used to generate the matrix
    at fit time.
    Pass an int for reproducible output across multiple function calls.
    See :term:`Glossary <random_state>`.
Returns
-------
components : ndarray of shape (n_components, n_features)
    The generated Gaussian random matrix.
See Also
--------
GaussianRandomProjection
Definition at line 169 of file random_projection.py.
References _check_input_size().
Referenced by sklearn.random_projection.GaussianRandomProjection._make_random_matrix().
_sparse_random_matrix()
sklearn.random_projection._sparse_random_matrix (n_components, n_features, density = "auto", random_state = None) protected
Generalized Achlioptas random sparse matrix for random projection.
Setting density to 1 / 3 will yield the original matrix by Dimitris
Achlioptas while setting a lower value will yield the generalization
by Ping Li et al.
If we note :math:`s = 1 / density`, the components of the random matrix are
drawn from:
  - -sqrt(s) / sqrt(n_components)   with probability 1 / 2s
  -  0                              with probability 1 - 1 / s
  - +sqrt(s) / sqrt(n_components)   with probability 1 / 2s
Read more in the :ref:`User Guide <sparse_random_matrix>`.
Parameters
----------
n_components : int,
    Dimensionality of the target projection space.
n_features : int,
    Dimensionality of the original source space.
density : float or 'auto', default='auto'
    Ratio of non-zero component in the random projection matrix in the
    range `(0, 1]`
    If density = 'auto', the value is set to the minimum density
    as recommended by Ping Li et al.: 1 / sqrt(n_features).
    Use density = 1 / 3.0 if you want to reproduce the results from
    Achlioptas, 2001.
random_state : int, RandomState instance or None, default=None
    Controls the pseudo random number generator used to generate the matrix
    at fit time.
    Pass an int for reproducible output across multiple function calls.
    See :term:`Glossary <random_state>`.
Returns
-------
components : {ndarray, sparse matrix} of shape (n_components, n_features)
    The generated Gaussian random matrix. Sparse matrix will be of CSR
    format.
See Also
--------
SparseRandomProjection
References
----------
.. [1] Ping Li, T. Hastie and K. W. Church, 2006,
       "Very Sparse Random Projections".
       https://web.stanford.edu/~hastie/Papers/Ping/KDD06_rp.pdf
.. [2] D. Achlioptas, 2001, "Database-friendly random projections",
       https://cgi.di.uoa.gr/~optas/papers/jl.pdf
Definition at line 209 of file random_projection.py.
References _check_density(), and _check_input_size().
Referenced by sklearn.random_projection.SparseRandomProjection._make_random_matrix().
johnson_lindenstrauss_min_dim()
sklearn.random_projection.johnson_lindenstrauss_min_dim (n_samples, * , eps = 0.1)
Find a 'safe' number of components to randomly project to.
The distortion introduced by a random projection `p` only changes the
distance between two points by a factor (1 +- eps) in a euclidean space
with good probability. The projection `p` is an eps-embedding as defined
by:
.. code-block:: text
  (1 - eps) ||u - v||^2 < ||p(u) - p(v)||^2 < (1 + eps) ||u - v||^2
Where u and v are any rows taken from a dataset of shape (n_samples,
n_features), eps is in ]0, 1[ and p is a projection by a random Gaussian
N(0, 1) matrix of shape (n_components, n_features) (or a sparse
Achlioptas matrix).
The minimum number of components to guarantee the eps-embedding is
given by:
.. code-block:: text
  n_components >= 4 log(n_samples) / (eps^2 / 2 - eps^3 / 3)
Note that the number of dimensions is independent of the original
number of features but instead depends on the size of the dataset:
the larger the dataset, the higher is the minimal dimensionality of
an eps-embedding.
Read more in the :ref:`User Guide <johnson_lindenstrauss>`.
Parameters
----------
n_samples : int or array-like of int
    Number of samples that should be an integer greater than 0. If an array
    is given, it will compute a safe number of components array-wise.
eps : float or array-like of shape (n_components,), dtype=float, \
        default=0.1
    Maximum distortion rate in the range (0, 1) as defined by the
    Johnson-Lindenstrauss lemma. If an array is given, it will compute a
    safe number of components array-wise.
Returns
-------
n_components : int or ndarray of int
    The minimal number of components to guarantee with good probability
    an eps-embedding with n_samples.
References
----------
.. [1] https://en.wikipedia.org/wiki/Johnson%E2%80%93Lindenstrauss_lemma
.. [2] `Sanjoy Dasgupta and Anupam Gupta, 1999,
       "An elementary proof of the Johnson-Lindenstrauss Lemma."
       <https://citeseerx.ist.psu.edu/doc_view/pid/95cd464d27c25c9c8690b378b894d337cdf021f9>`_
Examples
--------
>>> from sklearn.random_projection import johnson_lindenstrauss_min_dim
>>> johnson_lindenstrauss_min_dim(1e6, eps=0.5)
np.int64(663)
>>> johnson_lindenstrauss_min_dim(1e6, eps=[0.5, 0.1, 0.01])
array([    663,   11841, 1112658])
>>> johnson_lindenstrauss_min_dim([1e4, 1e5, 1e6], eps=0.1)
array([ 7894,  9868, 11841])
Definition at line 63 of file random_projection.py.
Referenced by sklearn.random_projection.BaseRandomProjection.fit().
Variable Documentation
__all__
list sklearn.random_projection.__all__ private
Initial value:
=  [
    "GaussianRandomProjection",
    "SparseRandomProjection",
    "johnson_lindenstrauss_min_dim",
]
Definition at line 49 of file random_projection.py.