Code Cloning Analysis: pandas.io.parsers.readers Namespace Reference
pandas.io.parsers.readers Namespace Reference
Classes
class _C_Parser_Defaults
class _DeprecationConfig
class _Fwf_Defaults
class TextFileReader
Functions
None validate_integer (str name, None val, int min_val=...)
int validate_integer (str name, float val, int min_val=...)
int|None validate_integer (str name, int|None val, int min_val=...)
int|None validate_integer (str name, int|float|None val, int min_val=0)
None _validate_names (Sequence[Hashable]|None names)
DataFrame|TextFileReader _read (FilePath|ReadCsvBuffer[bytes]|ReadCsvBuffer[str] filepath_or_buffer, kwds)
TextFileReader read_csv (FilePath|ReadCsvBuffer[bytes]|ReadCsvBuffer[str] filepath_or_buffer, *, str|None|lib.NoDefault sep=..., str|None|lib.NoDefault delimiter=..., int|Sequence[int]|None|Literal["infer"] header=..., Sequence[Hashable]|None|lib.NoDefault names=..., IndexLabel|Literal[False]|None index_col=..., UsecolsArgType usecols=..., DtypeArg|None dtype=..., CSVEngine|None engine=..., Mapping[Hashable, Callable]|None converters=..., list|None true_values=..., list|None false_values=..., bool skipinitialspace=..., list[int]|int|Callable[[Hashable], bool]|None skiprows=..., int skipfooter=..., int|None nrows=..., Hashable|Iterable[Hashable]|Mapping[Hashable, Iterable[Hashable]]|None na_values=..., bool na_filter=..., bool|lib.NoDefault verbose=..., bool skip_blank_lines=..., bool|Sequence[Hashable]|None parse_dates=..., bool|lib.NoDefault infer_datetime_format=..., bool|lib.NoDefault keep_date_col=..., Callable|lib.NoDefault date_parser=..., str|dict[Hashable, str]|None date_format=..., bool dayfirst=..., bool cache_dates=..., Literal[True] iterator, int|None chunksize=..., CompressionOptions compression=..., str|None thousands=..., str decimal=..., str|None lineterminator=..., str quotechar=..., int quoting=..., bool doublequote=..., str|None escapechar=..., str|None comment=..., str|None encoding=..., str|None encoding_errors=..., str|csv.Dialect|None dialect=..., on_bad_lines=..., bool|lib.NoDefault delim_whitespace=..., bool low_memory=..., bool memory_map=..., Literal["high", "legacy"]|None float_precision=..., StorageOptions storage_options=..., DtypeBackend|lib.NoDefault dtype_backend=...)
TextFileReader read_csv (FilePath|ReadCsvBuffer[bytes]|ReadCsvBuffer[str] filepath_or_buffer, *, str|None|lib.NoDefault sep=..., str|None|lib.NoDefault delimiter=..., int|Sequence[int]|None|Literal["infer"] header=..., Sequence[Hashable]|None|lib.NoDefault names=..., IndexLabel|Literal[False]|None index_col=..., UsecolsArgType usecols=..., DtypeArg|None dtype=..., CSVEngine|None engine=..., Mapping[Hashable, Callable]|None converters=..., list|None true_values=..., list|None false_values=..., bool skipinitialspace=..., list[int]|int|Callable[[Hashable], bool]|None skiprows=..., int skipfooter=..., int|None nrows=..., Hashable|Iterable[Hashable]|Mapping[Hashable, Iterable[Hashable]]|None na_values=..., bool keep_default_na=..., bool na_filter=..., bool|lib.NoDefault verbose=..., bool skip_blank_lines=..., bool|Sequence[Hashable]|None parse_dates=..., bool|lib.NoDefault infer_datetime_format=..., bool|lib.NoDefault keep_date_col=..., Callable|lib.NoDefault date_parser=..., str|dict[Hashable, str]|None date_format=..., bool dayfirst=..., bool cache_dates=..., bool iterator=..., int chunksize, CompressionOptions compression=..., str|None thousands=..., str decimal=..., str|None lineterminator=..., str quotechar=..., int quoting=..., bool doublequote=..., str|None escapechar=..., str|None comment=..., str|None encoding=..., str|None encoding_errors=..., str|csv.Dialect|None dialect=..., on_bad_lines=..., bool|lib.NoDefault delim_whitespace=..., bool low_memory=..., bool memory_map=..., Literal["high", "legacy"]|None float_precision=..., StorageOptions storage_options=..., DtypeBackend|lib.NoDefault dtype_backend=...)
DataFrame read_csv (FilePath|ReadCsvBuffer[bytes]|ReadCsvBuffer[str] filepath_or_buffer, *, str|None|lib.NoDefault sep=..., str|None|lib.NoDefault delimiter=..., int|Sequence[int]|None|Literal["infer"] header=..., Sequence[Hashable]|None|lib.NoDefault names=..., IndexLabel|Literal[False]|None index_col=..., UsecolsArgType usecols=..., DtypeArg|None dtype=..., CSVEngine|None engine=..., Mapping[Hashable, Callable]|None converters=..., list|None true_values=..., list|None false_values=..., bool skipinitialspace=..., list[int]|int|Callable[[Hashable], bool]|None skiprows=..., int skipfooter=..., int|None nrows=..., Hashable|Iterable[Hashable]|Mapping[Hashable, Iterable[Hashable]]|None na_values=..., bool keep_default_na=..., bool na_filter=..., bool|lib.NoDefault verbose=..., bool skip_blank_lines=..., bool|Sequence[Hashable]|None parse_dates=..., bool|lib.NoDefault infer_datetime_format=..., bool|lib.NoDefault keep_date_col=..., Callable|lib.NoDefault date_parser=..., str|dict[Hashable, str]|None date_format=..., bool dayfirst=..., bool cache_dates=..., Literal[False] iterator=..., None chunksize=..., CompressionOptions compression=..., str|None thousands=..., str decimal=..., str|None lineterminator=..., str quotechar=..., int quoting=..., bool doublequote=..., str|None escapechar=..., str|None comment=..., str|None encoding=..., str|None encoding_errors=..., str|csv.Dialect|None dialect=..., on_bad_lines=..., bool|lib.NoDefault delim_whitespace=..., bool low_memory=..., bool memory_map=..., Literal["high", "legacy"]|None float_precision=..., StorageOptions storage_options=..., DtypeBackend|lib.NoDefault dtype_backend=...)
DataFrame|TextFileReader read_csv (FilePath|ReadCsvBuffer[bytes]|ReadCsvBuffer[str] filepath_or_buffer, *, str|None|lib.NoDefault sep=..., str|None|lib.NoDefault delimiter=..., int|Sequence[int]|None|Literal["infer"] header=..., Sequence[Hashable]|None|lib.NoDefault names=..., IndexLabel|Literal[False]|None index_col=..., UsecolsArgType usecols=..., DtypeArg|None dtype=..., CSVEngine|None engine=..., Mapping[Hashable, Callable]|None converters=..., list|None true_values=..., list|None false_values=..., bool skipinitialspace=..., list[int]|int|Callable[[Hashable], bool]|None skiprows=..., int skipfooter=..., int|None nrows=..., Hashable|Iterable[Hashable]|Mapping[Hashable, Iterable[Hashable]]|None na_values=..., bool keep_default_na=..., bool na_filter=..., bool|lib.NoDefault verbose=..., bool skip_blank_lines=..., bool|Sequence[Hashable]|None parse_dates=..., bool|lib.NoDefault infer_datetime_format=..., bool|lib.NoDefault keep_date_col=..., Callable|lib.NoDefault date_parser=..., str|dict[Hashable, str]|None date_format=..., bool dayfirst=..., bool cache_dates=..., bool iterator=..., int|None chunksize=..., CompressionOptions compression=..., str|None thousands=..., str decimal=..., str|None lineterminator=..., str quotechar=..., int quoting=..., bool doublequote=..., str|None escapechar=..., str|None comment=..., str|None encoding=..., str|None encoding_errors=..., str|csv.Dialect|None dialect=..., on_bad_lines=..., bool|lib.NoDefault delim_whitespace=..., bool low_memory=..., bool memory_map=..., Literal["high", "legacy"]|None float_precision=..., StorageOptions storage_options=..., DtypeBackend|lib.NoDefault dtype_backend=...)
DataFrame|TextFileReader read_csv (FilePath|ReadCsvBuffer[bytes]|ReadCsvBuffer[str] filepath_or_buffer, *, str|None|lib.NoDefault sep=lib.no_default, str|None|lib.NoDefault delimiter=None, int|Sequence[int]|None|Literal["infer"] header="infer", Sequence[Hashable]|None|lib.NoDefault names=lib.no_default, IndexLabel|Literal[False]|None index_col=None, UsecolsArgType usecols=None, DtypeArg|None dtype=None, CSVEngine|None engine=None, Mapping[Hashable, Callable]|None converters=None, list|None true_values=None, list|None false_values=None, bool skipinitialspace=False, list[int]|int|Callable[[Hashable], bool]|None skiprows=None, int skipfooter=0, int|None nrows=None, Hashable|Iterable[Hashable]|Mapping[Hashable, Iterable[Hashable]]|None na_values=None, bool keep_default_na=True, bool na_filter=True, bool|lib.NoDefault verbose=lib.no_default, bool skip_blank_lines=True, bool|Sequence[Hashable]|None parse_dates=None, bool|lib.NoDefault infer_datetime_format=lib.no_default, bool|lib.NoDefault keep_date_col=lib.no_default, Callable|lib.NoDefault date_parser=lib.no_default, str|dict[Hashable, str]|None date_format=None, bool dayfirst=False, bool cache_dates=True, bool iterator=False, int|None chunksize=None, CompressionOptions compression="infer", str|None thousands=None, str decimal=".", str|None lineterminator=None, str quotechar='"', int quoting=csv.QUOTE_MINIMAL, bool doublequote=True, str | None escapechar=None, str | None comment=None, str | None encoding=None, str | None encoding_errors="strict", str | csv.Dialect | None dialect=None, str on_bad_lines="error", bool | lib.NoDefault delim_whitespace=lib.no_default, bool low_memory=_c_parser_defaults["low_memory"], bool memory_map=False, Literal["high", "legacy"] | None float_precision=None, StorageOptions | None storage_options=None, DtypeBackend | lib.NoDefault dtype_backend=lib.no_default)
TextFileReader read_table (FilePath|ReadCsvBuffer[bytes]|ReadCsvBuffer[str] filepath_or_buffer, *, str|None|lib.NoDefault sep=..., str|None|lib.NoDefault delimiter=..., int|Sequence[int]|None|Literal["infer"] header=..., Sequence[Hashable]|None|lib.NoDefault names=..., IndexLabel|Literal[False]|None index_col=..., UsecolsArgType usecols=..., DtypeArg|None dtype=..., CSVEngine|None engine=..., Mapping[Hashable, Callable]|None converters=..., list|None true_values=..., list|None false_values=..., bool skipinitialspace=..., list[int]|int|Callable[[Hashable], bool]|None skiprows=..., int skipfooter=..., int|None nrows=..., Sequence[str]|Mapping[str, Sequence[str]]|None na_values=..., bool keep_default_na=..., bool na_filter=..., bool|lib.NoDefault verbose=..., bool skip_blank_lines=..., bool|Sequence[Hashable] parse_dates=..., bool|lib.NoDefault infer_datetime_format=..., bool|lib.NoDefault keep_date_col=..., Callable|lib.NoDefault date_parser=..., str|dict[Hashable, str]|None date_format=..., bool dayfirst=..., bool cache_dates=..., Literal[True] iterator, int|None chunksize=..., CompressionOptions compression=..., str|None thousands=..., str decimal=..., str|None lineterminator=..., str quotechar=..., int quoting=..., bool doublequote=..., str|None escapechar=..., str|None comment=..., str|None encoding=..., str|None encoding_errors=..., str|csv.Dialect|None dialect=..., on_bad_lines=..., bool delim_whitespace=..., bool low_memory=..., bool memory_map=..., str|None float_precision=..., StorageOptions storage_options=..., DtypeBackend|lib.NoDefault dtype_backend=...)
TextFileReader read_table (FilePath|ReadCsvBuffer[bytes]|ReadCsvBuffer[str] filepath_or_buffer, *, str|None|lib.NoDefault sep=..., str|None|lib.NoDefault delimiter=..., int|Sequence[int]|None|Literal["infer"] header=..., Sequence[Hashable]|None|lib.NoDefault names=..., IndexLabel|Literal[False]|None index_col=..., UsecolsArgType usecols=..., DtypeArg|None dtype=..., CSVEngine|None engine=..., Mapping[Hashable, Callable]|None converters=..., list|None true_values=..., list|None false_values=..., bool skipinitialspace=..., list[int]|int|Callable[[Hashable], bool]|None skiprows=..., int skipfooter=..., int|None nrows=..., Sequence[str]|Mapping[str, Sequence[str]]|None na_values=..., bool keep_default_na=..., bool na_filter=..., bool|lib.NoDefault verbose=..., bool skip_blank_lines=..., bool|Sequence[Hashable] parse_dates=..., bool|lib.NoDefault infer_datetime_format=..., bool|lib.NoDefault keep_date_col=..., Callable|lib.NoDefault date_parser=..., str|dict[Hashable, str]|None date_format=..., bool dayfirst=..., bool cache_dates=..., bool iterator=..., int chunksize, CompressionOptions compression=..., str|None thousands=..., str decimal=..., str|None lineterminator=..., str quotechar=..., int quoting=..., bool doublequote=..., str|None escapechar=..., str|None comment=..., str|None encoding=..., str|None encoding_errors=..., str|csv.Dialect|None dialect=..., on_bad_lines=..., bool delim_whitespace=..., bool low_memory=..., bool memory_map=..., str|None float_precision=..., StorageOptions storage_options=..., DtypeBackend|lib.NoDefault dtype_backend=...)
DataFrame read_table (FilePath|ReadCsvBuffer[bytes]|ReadCsvBuffer[str] filepath_or_buffer, *, str|None|lib.NoDefault sep=..., str|None|lib.NoDefault delimiter=..., int|Sequence[int]|None|Literal["infer"] header=..., Sequence[Hashable]|None|lib.NoDefault names=..., IndexLabel|Literal[False]|None index_col=..., UsecolsArgType usecols=..., DtypeArg|None dtype=..., CSVEngine|None engine=..., Mapping[Hashable, Callable]|None converters=..., list|None true_values=..., list|None false_values=..., bool skipinitialspace=..., list[int]|int|Callable[[Hashable], bool]|None skiprows=..., int skipfooter=..., int|None nrows=..., Sequence[str]|Mapping[str, Sequence[str]]|None na_values=..., bool keep_default_na=..., bool na_filter=..., bool|lib.NoDefault verbose=..., bool skip_blank_lines=..., bool|Sequence[Hashable] parse_dates=..., bool|lib.NoDefault infer_datetime_format=..., bool|lib.NoDefault keep_date_col=..., Callable|lib.NoDefault date_parser=..., str|dict[Hashable, str]|None date_format=..., bool dayfirst=..., bool cache_dates=..., Literal[False] iterator=..., None chunksize=..., CompressionOptions compression=..., str|None thousands=..., str decimal=..., str|None lineterminator=..., str quotechar=..., int quoting=..., bool doublequote=..., str|None escapechar=..., str|None comment=..., str|None encoding=..., str|None encoding_errors=..., str|csv.Dialect|None dialect=..., on_bad_lines=..., bool delim_whitespace=..., bool low_memory=..., bool memory_map=..., str|None float_precision=..., StorageOptions storage_options=..., DtypeBackend|lib.NoDefault dtype_backend=...)
DataFrame|TextFileReader read_table (FilePath|ReadCsvBuffer[bytes]|ReadCsvBuffer[str] filepath_or_buffer, *, str|None|lib.NoDefault sep=..., str|None|lib.NoDefault delimiter=..., int|Sequence[int]|None|Literal["infer"] header=..., Sequence[Hashable]|None|lib.NoDefault names=..., IndexLabel|Literal[False]|None index_col=..., UsecolsArgType usecols=..., DtypeArg|None dtype=..., CSVEngine|None engine=..., Mapping[Hashable, Callable]|None converters=..., list|None true_values=..., list|None false_values=..., bool skipinitialspace=..., list[int]|int|Callable[[Hashable], bool]|None skiprows=..., int skipfooter=..., int|None nrows=..., Sequence[str]|Mapping[str, Sequence[str]]|None na_values=..., bool keep_default_na=..., bool na_filter=..., bool|lib.NoDefault verbose=..., bool skip_blank_lines=..., bool|Sequence[Hashable] parse_dates=..., bool|lib.NoDefault infer_datetime_format=..., bool|lib.NoDefault keep_date_col=..., Callable|lib.NoDefault date_parser=..., str|dict[Hashable, str]|None date_format=..., bool dayfirst=..., bool cache_dates=..., bool iterator=..., int|None chunksize=..., CompressionOptions compression=..., str|None thousands=..., str decimal=..., str|None lineterminator=..., str quotechar=..., int quoting=..., bool doublequote=..., str|None escapechar=..., str|None comment=..., str|None encoding=..., str|None encoding_errors=..., str|csv.Dialect|None dialect=..., on_bad_lines=..., bool delim_whitespace=..., bool low_memory=..., bool memory_map=..., str|None float_precision=..., StorageOptions storage_options=..., DtypeBackend|lib.NoDefault dtype_backend=...)
DataFrame|TextFileReader read_table (FilePath|ReadCsvBuffer[bytes]|ReadCsvBuffer[str] filepath_or_buffer, *, str|None|lib.NoDefault sep=lib.no_default, str|None|lib.NoDefault delimiter=None, int|Sequence[int]|None|Literal["infer"] header="infer", Sequence[Hashable]|None|lib.NoDefault names=lib.no_default, IndexLabel|Literal[False]|None index_col=None, UsecolsArgType usecols=None, DtypeArg|None dtype=None, CSVEngine|None engine=None, Mapping[Hashable, Callable]|None converters=None, list|None true_values=None, list|None false_values=None, bool skipinitialspace=False, list[int]|int|Callable[[Hashable], bool]|None skiprows=None, int skipfooter=0, int|None nrows=None, Sequence[str]|Mapping[str, Sequence[str]]|None na_values=None, bool keep_default_na=True, bool na_filter=True, bool|lib.NoDefault verbose=lib.no_default, bool skip_blank_lines=True, bool|Sequence[Hashable] parse_dates=False, bool|lib.NoDefault infer_datetime_format=lib.no_default, bool|lib.NoDefault keep_date_col=lib.no_default, Callable|lib.NoDefault date_parser=lib.no_default, str|dict[Hashable, str]|None date_format=None, bool dayfirst=False, bool cache_dates=True, bool iterator=False, int|None chunksize=None, CompressionOptions compression="infer", str|None thousands=None, str decimal=".", str|None lineterminator=None, str quotechar='"', int quoting=csv.QUOTE_MINIMAL, bool doublequote=True, str | None escapechar=None, str | None comment=None, str | None encoding=None, str | None encoding_errors="strict", str | csv.Dialect | None dialect=None, str on_bad_lines="error", bool | lib.NoDefault delim_whitespace=lib.no_default, bool low_memory=_c_parser_defaults["low_memory"], bool memory_map=False, str | None float_precision=None, StorageOptions | None storage_options=None, DtypeBackend | lib.NoDefault dtype_backend=lib.no_default)
TextFileReader read_fwf (FilePath|ReadCsvBuffer[bytes]|ReadCsvBuffer[str] filepath_or_buffer, *, Sequence[tuple[int, int]]|str|None colspecs=..., Sequence[int]|None widths=..., int infer_nrows=..., DtypeBackend|lib.NoDefault dtype_backend=..., Literal[True] iterator, int|None chunksize=..., **kwds)
TextFileReader read_fwf (FilePath|ReadCsvBuffer[bytes]|ReadCsvBuffer[str] filepath_or_buffer, *, Sequence[tuple[int, int]]|str|None colspecs=..., Sequence[int]|None widths=..., int infer_nrows=..., DtypeBackend|lib.NoDefault dtype_backend=..., bool iterator=..., int chunksize, **kwds)
DataFrame read_fwf (FilePath|ReadCsvBuffer[bytes]|ReadCsvBuffer[str] filepath_or_buffer, *, Sequence[tuple[int, int]]|str|None colspecs=..., Sequence[int]|None widths=..., int infer_nrows=..., DtypeBackend|lib.NoDefault dtype_backend=..., Literal[False] iterator=..., None chunksize=..., **kwds)
DataFrame|TextFileReader read_fwf (FilePath|ReadCsvBuffer[bytes]|ReadCsvBuffer[str] filepath_or_buffer, *, Sequence[tuple[int, int]]|str|None colspecs="infer", Sequence[int]|None widths=None, int infer_nrows=100, DtypeBackend|lib.NoDefault dtype_backend=lib.no_default, bool iterator=False, int|None chunksize=None, **kwds)
TextFileReader TextParser (*args, **kwds)
_clean_na_values (na_values, bool keep_default_na=True, bool floatify=True)
_floatify_na_values (na_values)
_stringify_na_values (na_values, bool floatify)
_refine_defaults_read (str|csv.Dialect|None dialect, str|None|lib.NoDefault delimiter, bool delim_whitespace, CSVEngine|None engine, str|None|lib.NoDefault sep, str|Callable on_bad_lines, Sequence[Hashable]|None|lib.NoDefault names, dict[str, Any] defaults, DtypeBackend|lib.NoDefault dtype_backend)
csv.Dialect|None _extract_dialect (dict[str, Any] kwds)
None _validate_dialect (csv.Dialect dialect)
dict[str, Any] _merge_with_dialect_properties (csv.Dialect dialect, dict[str, Any] defaults)
None _validate_skipfooter (dict[str, Any] kwds)
Variables
tuple _doc_read_csv_and_table
dict _c_unsupported = {"skipfooter"}
dict _python_unsupported = {"low_memory", "float_precision"}
dict _pyarrow_unsupported
tuple MANDATORY_DIALECT_ATTRS
Detailed Description
Module contains tools for processing files into DataFrames or other objects
GH#48849 provides a convenient way of deprecating keyword arguments
Function Documentation
_clean_na_values()
pandas.io.parsers.readers._clean_na_values (na_values, bool keep_default_na = True, bool floatify = True) protected
Definition at line 2056 of file readers.py.
_extract_dialect()
csv.Dialect | None pandas.io.parsers.readers._extract_dialect (dict[str, Any] kwds) protected
Extract concrete csv dialect instance.
Returns
-------
csv.Dialect or None
Definition at line 2267 of file readers.py.
References _validate_dialect().
_floatify_na_values()
pandas.io.parsers.readers._floatify_na_values (na_values) protected
Definition at line 2093 of file readers.py.
_merge_with_dialect_properties()
dict[str, Any] pandas.io.parsers.readers._merge_with_dialect_properties (csv.Dialect dialect, dict[str, Any] defaults) protected
Merge default kwargs in TextFileReader with dialect parameters.
Parameters
----------
dialect : csv.Dialect
    Concrete csv dialect. See csv.Dialect documentation for more details.
defaults : dict
    Keyword arguments passed to TextFileReader.
Returns
-------
kwds : dict
    Updated keyword arguments, merged with dialect parameters.
Definition at line 2311 of file readers.py.
_read()
DataFrame | TextFileReader pandas.io.parsers.readers._read (FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str] filepath_or_buffer, kwds) protected
Generic reader of line files.
Definition at line 583 of file readers.py.
References _read(), _refine_defaults_read(), and _validate_names().
Referenced by _read(), and read_fwf().
_refine_defaults_read()
pandas.io.parsers.readers._refine_defaults_read (str | csv.Dialect | None dialect, str | None | lib.NoDefault delimiter, bool delim_whitespace, CSVEngine | None engine, str | None | lib.NoDefault sep, str | Callable on_bad_lines, Sequence[Hashable] | None | lib.NoDefault names, dict[str, Any] defaults, DtypeBackend | lib.NoDefault dtype_backend) protected
Validate/refine default values of input parameters of read_csv, read_table.
Parameters
----------
dialect : str or csv.Dialect
    If provided, this parameter will override values (default or not) for the
    following parameters: `delimiter`, `doublequote`, `escapechar`,
    `skipinitialspace`, `quotechar`, and `quoting`. If it is necessary to
    override values, a ParserWarning will be issued. See csv.Dialect
    documentation for more details.
delimiter : str or object
    Alias for sep.
delim_whitespace : bool
    Specifies whether or not whitespace (e.g. ``' '`` or ``'\t'``) will be
    used as the sep. Equivalent to setting ``sep='\\s+'``. If this option
    is set to True, nothing should be passed in for the ``delimiter``
    parameter.
    .. deprecated:: 2.2.0
        Use ``sep="\\s+"`` instead.
engine : {{'c', 'python'}}
    Parser engine to use. The C engine is faster while the python engine is
    currently more feature-complete.
sep : str or object
    A delimiter provided by the user (str) or a sentinel value, i.e.
    pandas._libs.lib.no_default.
on_bad_lines : str, callable
    An option for handling bad lines or a sentinel value(None).
names : array-like, optional
    List of column names to use. If the file contains a header row,
    then you should explicitly pass ``header=0`` to override the column names.
    Duplicates in this list are not allowed.
defaults: dict
    Default values of input parameters.
Returns
-------
kwds : dict
    Input parameters with correct values.
Raises
------
ValueError :
    If a delimiter was specified with ``sep`` (or ``delimiter``) and
    ``delim_whitespace=True``.
Definition at line 2133 of file readers.py.
Referenced by _read().
_stringify_na_values()
pandas.io.parsers.readers._stringify_na_values (na_values, bool floatify) protected
return a stringified and numeric for these values
Definition at line 2106 of file readers.py.
Referenced by TextParser().
_validate_dialect()
None pandas.io.parsers.readers._validate_dialect (csv.Dialect dialect) protected
Validate csv dialect instance.
Raises
------
ValueError
    If incorrect dialect is provided.
Definition at line 2297 of file readers.py.
Referenced by _extract_dialect().
_validate_names()
None pandas.io.parsers.readers._validate_names (Sequence[Hashable] | None names) protected
Raise ValueError if the `names` parameter contains duplicates or has an
invalid data type.
Parameters
----------
names : array-like or None
    An array containing a list of the names used for the output DataFrame.
Raises
------
ValueError
    If names are not unique or are not ordered (e.g. set).
Definition at line 559 of file readers.py.
Referenced by _read().
_validate_skipfooter()
None pandas.io.parsers.readers._validate_skipfooter (dict[str, Any] kwds) protected
Check whether skipfooter is compatible with other kwargs in TextFileReader.
Parameters
----------
kwds : dict
    Keyword arguments passed to TextFileReader.
Raises
------
ValueError
    If skipfooter is not compatible with other parameters.
Definition at line 2365 of file readers.py.
read_csv() [1/5]
TextFileReader pandas.io.parsers.readers.read_csv (FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str] filepath_or_buffer, * , str | None | lib.NoDefault sep = ..., str | None | lib.NoDefault delimiter = ..., int | Sequence[int] | None | Literal["infer"] header = ..., Sequence[Hashable] | None | lib.NoDefault names = ..., IndexLabel | Literal[False] | None index_col = ..., UsecolsArgType usecols = ..., DtypeArg | None dtype = ..., CSVEngine | None engine = ..., Mapping[Hashable, Callable] | None converters = ..., list | None true_values = ..., list | None false_values = ..., bool skipinitialspace = ..., list[int] | int | Callable[[Hashable], bool] | None skiprows = ..., int skipfooter = ..., int | None nrows = ..., Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None na_values = ..., bool keep_default_na = ..., bool na_filter = ..., bool | lib.NoDefault verbose = ..., bool skip_blank_lines = ..., bool | Sequence[Hashable] | None parse_dates = ..., bool | lib.NoDefault infer_datetime_format = ..., bool | lib.NoDefault keep_date_col = ..., Callable | lib.NoDefault date_parser = ..., str | dict[Hashable, str] | None date_format = ..., bool dayfirst = ..., bool cache_dates = ..., bool iterator = ..., int chunksize, CompressionOptions compression = ..., str | None thousands = ..., str decimal = ..., str | None lineterminator = ..., str quotechar = ..., int quoting = ..., bool doublequote = ..., str | None escapechar = ..., str | None comment = ..., str | None encoding = ..., str | None encoding_errors = ..., str | csv.Dialect | None dialect = ..., on_bad_lines = ..., bool | lib.NoDefault delim_whitespace = ..., bool low_memory = ..., bool memory_map = ..., Literal["high", "legacy"] | None float_precision = ..., StorageOptions storage_options = ..., DtypeBackend | lib.NoDefault dtype_backend = ...)
Definition at line 690 of file readers.py.
read_csv() [2/5]
DataFrame | TextFileReader pandas.io.parsers.readers.read_csv (FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str] filepath_or_buffer, * , str | None | lib.NoDefault sep = ..., str | None | lib.NoDefault delimiter = ..., int | Sequence[int] | None | Literal["infer"] header = ..., Sequence[Hashable] | None | lib.NoDefault names = ..., IndexLabel | Literal[False] | None index_col = ..., UsecolsArgType usecols = ..., DtypeArg | None dtype = ..., CSVEngine | None engine = ..., Mapping[Hashable, Callable] | None converters = ..., list | None true_values = ..., list | None false_values = ..., bool skipinitialspace = ..., list[int] | int | Callable[[Hashable], bool] | None skiprows = ..., int skipfooter = ..., int | None nrows = ..., Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None na_values = ..., bool keep_default_na = ..., bool na_filter = ..., bool | lib.NoDefault verbose = ..., bool skip_blank_lines = ..., bool | Sequence[Hashable] | None parse_dates = ..., bool | lib.NoDefault infer_datetime_format = ..., bool | lib.NoDefault keep_date_col = ..., Callable | lib.NoDefault date_parser = ..., str | dict[Hashable, str] | None date_format = ..., bool dayfirst = ..., bool cache_dates = ..., bool iterator = ..., int | None chunksize = ..., CompressionOptions compression = ..., str | None thousands = ..., str decimal = ..., str | None lineterminator = ..., str quotechar = ..., int quoting = ..., bool doublequote = ..., str | None escapechar = ..., str | None comment = ..., str | None encoding = ..., str | None encoding_errors = ..., str | csv.Dialect | None dialect = ..., on_bad_lines = ..., bool | lib.NoDefault delim_whitespace = ..., bool low_memory = ..., bool memory_map = ..., Literal["high", "legacy"] | None float_precision = ..., StorageOptions storage_options = ..., DtypeBackend | lib.NoDefault dtype_backend = ...)
Definition at line 810 of file readers.py.
read_csv() [3/5]
DataFrame pandas.io.parsers.readers.read_csv (FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str] filepath_or_buffer, * , str | None | lib.NoDefault sep = ..., str | None | lib.NoDefault delimiter = ..., int | Sequence[int] | None | Literal["infer"] header = ..., Sequence[Hashable] | None | lib.NoDefault names = ..., IndexLabel | Literal[False] | None index_col = ..., UsecolsArgType usecols = ..., DtypeArg | None dtype = ..., CSVEngine | None engine = ..., Mapping[Hashable, Callable] | None converters = ..., list | None true_values = ..., list | None false_values = ..., bool skipinitialspace = ..., list[int] | int | Callable[[Hashable], bool] | None skiprows = ..., int skipfooter = ..., int | None nrows = ..., Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None na_values = ..., bool keep_default_na = ..., bool na_filter = ..., bool | lib.NoDefault verbose = ..., bool skip_blank_lines = ..., bool | Sequence[Hashable] | None parse_dates = ..., bool | lib.NoDefault infer_datetime_format = ..., bool | lib.NoDefault keep_date_col = ..., Callable | lib.NoDefault date_parser = ..., str | dict[Hashable, str] | None date_format = ..., bool dayfirst = ..., bool cache_dates = ..., Literal[False] iterator = ..., None chunksize = ..., CompressionOptions compression = ..., str | None thousands = ..., str decimal = ..., str | None lineterminator = ..., str quotechar = ..., int quoting = ..., bool doublequote = ..., str | None escapechar = ..., str | None comment = ..., str | None encoding = ..., str | None encoding_errors = ..., str | csv.Dialect | None dialect = ..., on_bad_lines = ..., bool | lib.NoDefault delim_whitespace = ..., bool low_memory = ..., bool memory_map = ..., Literal["high", "legacy"] | None float_precision = ..., StorageOptions storage_options = ..., DtypeBackend | lib.NoDefault dtype_backend = ...)
Definition at line 750 of file readers.py.
read_csv() [4/5]
TextFileReader pandas.io.parsers.readers.read_csv (FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str] filepath_or_buffer, * , str | None | lib.NoDefault sep = ..., str | None | lib.NoDefault delimiter = ..., int | Sequence[int] | None | Literal["infer"] header = ..., Sequence[Hashable] | None | lib.NoDefault names = ..., IndexLabel | Literal[False] | None index_col = ..., UsecolsArgType usecols = ..., DtypeArg | None dtype = ..., CSVEngine | None engine = ..., Mapping[Hashable, Callable] | None converters = ..., list | None true_values = ..., list | None false_values = ..., bool skipinitialspace = ..., list[int] | int | Callable[[Hashable], bool] | None skiprows = ..., int skipfooter = ..., int | None nrows = ..., Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None na_values = ..., bool na_filter = ..., bool | lib.NoDefault verbose = ..., bool skip_blank_lines = ..., bool | Sequence[Hashable] | None parse_dates = ..., bool | lib.NoDefault infer_datetime_format = ..., bool | lib.NoDefault keep_date_col = ..., Callable | lib.NoDefault date_parser = ..., str | dict[Hashable, str] | None date_format = ..., bool dayfirst = ..., bool cache_dates = ..., Literal[True] iterator, int | None chunksize = ..., CompressionOptions compression = ..., str | None thousands = ..., str decimal = ..., str | None lineterminator = ..., str quotechar = ..., int quoting = ..., bool doublequote = ..., str | None escapechar = ..., str | None comment = ..., str | None encoding = ..., str | None encoding_errors = ..., str | csv.Dialect | None dialect = ..., on_bad_lines = ..., bool | lib.NoDefault delim_whitespace = ..., bool low_memory = ..., bool memory_map = ..., Literal["high", "legacy"] | None float_precision = ..., StorageOptions storage_options = ..., DtypeBackend | lib.NoDefault dtype_backend = ...)
Definition at line 631 of file readers.py.
read_csv() [5/5]
DataFrame | TextFileReader pandas.io.parsers.readers.read_csv (FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str] filepath_or_buffer, * , str | None | lib.NoDefault sep = lib.no_default, str | None | lib.NoDefault delimiter = None, int | Sequence[int] | None | Literal["infer"] header = "infer", Sequence[Hashable] | None | lib.NoDefault names = lib.no_default, IndexLabel | Literal[False] | None index_col = None, UsecolsArgType usecols = None, DtypeArg | None dtype = None, CSVEngine | None engine = None, Mapping[Hashable, Callable] | None converters = None, list | None true_values = None, list | None false_values = None, bool skipinitialspace = False, list[int] | int | Callable[[Hashable], bool] | None skiprows = None, int skipfooter = 0, int | None nrows = None, Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None na_values = None, bool keep_default_na = True, bool na_filter = True, bool | lib.NoDefault verbose = lib.no_default, bool skip_blank_lines = True, bool | Sequence[Hashable] | None parse_dates = None, bool | lib.NoDefault infer_datetime_format = lib.no_default, bool | lib.NoDefault keep_date_col = lib.no_default, Callable | lib.NoDefault date_parser = lib.no_default, str | dict[Hashable, str] | None date_format = None, bool dayfirst = False, bool cache_dates = True, bool iterator = False, int | None chunksize = None, CompressionOptions compression = "infer", str | None thousands = None, str decimal = ".", str | None lineterminator = None, str quotechar = '"', int quoting = csv.QUOTE_MINIMAL, bool doublequote = True, str | None escapechar = None, str | None comment = None, str | None encoding = None, str | None encoding_errors = "strict", str | csv.Dialect | None dialect = None, str on_bad_lines = "error", bool | lib.NoDefault delim_whitespace = lib.no_default, bool low_memory = _c_parser_defaults["low_memory"], bool memory_map = False, Literal["high", "legacy"] | None float_precision = None, StorageOptions | None storage_options = None, DtypeBackend | lib.NoDefault dtype_backend = lib.no_default)
Definition at line 880 of file readers.py.
read_fwf() [1/4]
DataFrame | TextFileReader pandas.io.parsers.readers.read_fwf (FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str] filepath_or_buffer, * , Sequence[tuple[int, int]] | str | None colspecs = "infer", Sequence[int] | None widths = None, int infer_nrows = 100, DtypeBackend | lib.NoDefault dtype_backend = lib.no_default, bool iterator = False, int | None chunksize = None, ** kwds)
Read a table of fixed-width formatted lines into DataFrame.
Also supports optionally iterating or breaking of the file
into chunks.
Additional help can be found in the `online docs for IO Tools
<https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html>`_.
Parameters
----------
filepath_or_buffer : str, path object, or file-like object
    String, path object (implementing ``os.PathLike[str]``), or file-like
    object implementing a text ``read()`` function.The string could be a URL.
    Valid URL schemes include http, ftp, s3, and file. For file URLs, a host is
    expected. A local file could be:
    ``file://localhost/path/to/table.csv``.
colspecs : list of tuple (int, int) or 'infer'. optional
    A list of tuples giving the extents of the fixed-width
    fields of each line as half-open intervals (i.e.,  [from, to[ ).
    String value 'infer' can be used to instruct the parser to try
    detecting the column specifications from the first 100 rows of
    the data which are not being skipped via skiprows (default='infer').
widths : list of int, optional
    A list of field widths which can be used instead of 'colspecs' if
    the intervals are contiguous.
infer_nrows : int, default 100
    The number of rows to consider when letting the parser determine the
    `colspecs`.
dtype_backend : {'numpy_nullable', 'pyarrow'}, default 'numpy_nullable'
    Back-end data type applied to the resultant :class:`DataFrame`
    (still experimental). Behaviour is as follows:
    * ``"numpy_nullable"``: returns nullable-dtype-backed :class:`DataFrame`
      (default).
    * ``"pyarrow"``: returns pyarrow-backed nullable :class:`ArrowDtype`
      DataFrame.
    .. versionadded:: 2.0
**kwds : optional
    Optional keyword arguments can be passed to ``TextFileReader``.
Returns
-------
DataFrame or TextFileReader
    A comma-separated values (csv) file is returned as two-dimensional
    data structure with labeled axes.
See Also
--------
DataFrame.to_csv : Write DataFrame to a comma-separated values (csv) file.
read_csv : Read a comma-separated values (csv) file into DataFrame.
Examples
--------
>>> pd.read_fwf('data.csv')  # doctest: +SKIP
Definition at line 1453 of file readers.py.
References _read().
read_fwf() [2/4]
TextFileReader pandas.io.parsers.readers.read_fwf (FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str] filepath_or_buffer, * , Sequence[tuple[int, int]] | str | None colspecs = ..., Sequence[int] | None widths = ..., int infer_nrows = ..., DtypeBackend | lib.NoDefault dtype_backend = ..., bool iterator = ..., int chunksize, ** kwds)
Definition at line 1424 of file readers.py.
read_fwf() [3/4]
DataFrame pandas.io.parsers.readers.read_fwf (FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str] filepath_or_buffer, * , Sequence[tuple[int, int]] | str | None colspecs = ..., Sequence[int] | None widths = ..., int infer_nrows = ..., DtypeBackend | lib.NoDefault dtype_backend = ..., Literal[False] iterator = ..., None chunksize = ..., ** kwds)
Definition at line 1439 of file readers.py.
read_fwf() [4/4]
TextFileReader pandas.io.parsers.readers.read_fwf (FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str] filepath_or_buffer, * , Sequence[tuple[int, int]] | str | None colspecs = ..., Sequence[int] | None widths = ..., int infer_nrows = ..., DtypeBackend | lib.NoDefault dtype_backend = ..., Literal[True] iterator, int | None chunksize = ..., ** kwds)
Definition at line 1409 of file readers.py.
read_table() [1/5]
TextFileReader pandas.io.parsers.readers.read_table (FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str] filepath_or_buffer, * , str | None | lib.NoDefault sep = ..., str | None | lib.NoDefault delimiter = ..., int | Sequence[int] | None | Literal["infer"] header = ..., Sequence[Hashable] | None | lib.NoDefault names = ..., IndexLabel | Literal[False] | None index_col = ..., UsecolsArgType usecols = ..., DtypeArg | None dtype = ..., CSVEngine | None engine = ..., Mapping[Hashable, Callable] | None converters = ..., list | None true_values = ..., list | None false_values = ..., bool skipinitialspace = ..., list[int] | int | Callable[[Hashable], bool] | None skiprows = ..., int skipfooter = ..., int | None nrows = ..., Sequence[str] | Mapping[str, Sequence[str]] | None na_values = ..., bool keep_default_na = ..., bool na_filter = ..., bool | lib.NoDefault verbose = ..., bool skip_blank_lines = ..., bool | Sequence[Hashable] parse_dates = ..., bool | lib.NoDefault infer_datetime_format = ..., bool | lib.NoDefault keep_date_col = ..., Callable | lib.NoDefault date_parser = ..., str | dict[Hashable, str] | None date_format = ..., bool dayfirst = ..., bool cache_dates = ..., bool iterator = ..., int chunksize, CompressionOptions compression = ..., str | None thousands = ..., str decimal = ..., str | None lineterminator = ..., str quotechar = ..., int quoting = ..., bool doublequote = ..., str | None escapechar = ..., str | None comment = ..., str | None encoding = ..., str | None encoding_errors = ..., str | csv.Dialect | None dialect = ..., on_bad_lines = ..., bool delim_whitespace = ..., bool low_memory = ..., bool memory_map = ..., str | None float_precision = ..., StorageOptions storage_options = ..., DtypeBackend | lib.NoDefault dtype_backend = ...)
Definition at line 1088 of file readers.py.
read_table() [2/5]
DataFrame | TextFileReader pandas.io.parsers.readers.read_table (FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str] filepath_or_buffer, * , str | None | lib.NoDefault sep = ..., str | None | lib.NoDefault delimiter = ..., int | Sequence[int] | None | Literal["infer"] header = ..., Sequence[Hashable] | None | lib.NoDefault names = ..., IndexLabel | Literal[False] | None index_col = ..., UsecolsArgType usecols = ..., DtypeArg | None dtype = ..., CSVEngine | None engine = ..., Mapping[Hashable, Callable] | None converters = ..., list | None true_values = ..., list | None false_values = ..., bool skipinitialspace = ..., list[int] | int | Callable[[Hashable], bool] | None skiprows = ..., int skipfooter = ..., int | None nrows = ..., Sequence[str] | Mapping[str, Sequence[str]] | None na_values = ..., bool keep_default_na = ..., bool na_filter = ..., bool | lib.NoDefault verbose = ..., bool skip_blank_lines = ..., bool | Sequence[Hashable] parse_dates = ..., bool | lib.NoDefault infer_datetime_format = ..., bool | lib.NoDefault keep_date_col = ..., Callable | lib.NoDefault date_parser = ..., str | dict[Hashable, str] | None date_format = ..., bool dayfirst = ..., bool cache_dates = ..., bool iterator = ..., int | None chunksize = ..., CompressionOptions compression = ..., str | None thousands = ..., str decimal = ..., str | None lineterminator = ..., str quotechar = ..., int quoting = ..., bool doublequote = ..., str | None escapechar = ..., str | None comment = ..., str | None encoding = ..., str | None encoding_errors = ..., str | csv.Dialect | None dialect = ..., on_bad_lines = ..., bool delim_whitespace = ..., bool low_memory = ..., bool memory_map = ..., str | None float_precision = ..., StorageOptions storage_options = ..., DtypeBackend | lib.NoDefault dtype_backend = ...)
Definition at line 1202 of file readers.py.
read_table() [3/5]
DataFrame pandas.io.parsers.readers.read_table (FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str] filepath_or_buffer, * , str | None | lib.NoDefault sep = ..., str | None | lib.NoDefault delimiter = ..., int | Sequence[int] | None | Literal["infer"] header = ..., Sequence[Hashable] | None | lib.NoDefault names = ..., IndexLabel | Literal[False] | None index_col = ..., UsecolsArgType usecols = ..., DtypeArg | None dtype = ..., CSVEngine | None engine = ..., Mapping[Hashable, Callable] | None converters = ..., list | None true_values = ..., list | None false_values = ..., bool skipinitialspace = ..., list[int] | int | Callable[[Hashable], bool] | None skiprows = ..., int skipfooter = ..., int | None nrows = ..., Sequence[str] | Mapping[str, Sequence[str]] | None na_values = ..., bool keep_default_na = ..., bool na_filter = ..., bool | lib.NoDefault verbose = ..., bool skip_blank_lines = ..., bool | Sequence[Hashable] parse_dates = ..., bool | lib.NoDefault infer_datetime_format = ..., bool | lib.NoDefault keep_date_col = ..., Callable | lib.NoDefault date_parser = ..., str | dict[Hashable, str] | None date_format = ..., bool dayfirst = ..., bool cache_dates = ..., Literal[False] iterator = ..., None chunksize = ..., CompressionOptions compression = ..., str | None thousands = ..., str decimal = ..., str | None lineterminator = ..., str quotechar = ..., int quoting = ..., bool doublequote = ..., str | None escapechar = ..., str | None comment = ..., str | None encoding = ..., str | None encoding_errors = ..., str | csv.Dialect | None dialect = ..., on_bad_lines = ..., bool delim_whitespace = ..., bool low_memory = ..., bool memory_map = ..., str | None float_precision = ..., StorageOptions storage_options = ..., DtypeBackend | lib.NoDefault dtype_backend = ...)
Definition at line 1145 of file readers.py.
read_table() [4/5]
TextFileReader pandas.io.parsers.readers.read_table (FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str] filepath_or_buffer, * , str | None | lib.NoDefault sep = ..., str | None | lib.NoDefault delimiter = ..., int | Sequence[int] | None | Literal["infer"] header = ..., Sequence[Hashable] | None | lib.NoDefault names = ..., IndexLabel | Literal[False] | None index_col = ..., UsecolsArgType usecols = ..., DtypeArg | None dtype = ..., CSVEngine | None engine = ..., Mapping[Hashable, Callable] | None converters = ..., list | None true_values = ..., list | None false_values = ..., bool skipinitialspace = ..., list[int] | int | Callable[[Hashable], bool] | None skiprows = ..., int skipfooter = ..., int | None nrows = ..., Sequence[str] | Mapping[str, Sequence[str]] | None na_values = ..., bool keep_default_na = ..., bool na_filter = ..., bool | lib.NoDefault verbose = ..., bool skip_blank_lines = ..., bool | Sequence[Hashable] parse_dates = ..., bool | lib.NoDefault infer_datetime_format = ..., bool | lib.NoDefault keep_date_col = ..., Callable | lib.NoDefault date_parser = ..., str | dict[Hashable, str] | None date_format = ..., bool dayfirst = ..., bool cache_dates = ..., Literal[True] iterator, int | None chunksize = ..., CompressionOptions compression = ..., str | None thousands = ..., str decimal = ..., str | None lineterminator = ..., str quotechar = ..., int quoting = ..., bool doublequote = ..., str | None escapechar = ..., str | None comment = ..., str | None encoding = ..., str | None encoding_errors = ..., str | csv.Dialect | None dialect = ..., on_bad_lines = ..., bool delim_whitespace = ..., bool low_memory = ..., bool memory_map = ..., str | None float_precision = ..., StorageOptions storage_options = ..., DtypeBackend | lib.NoDefault dtype_backend = ...)
Definition at line 1031 of file readers.py.
read_table() [5/5]
DataFrame | TextFileReader pandas.io.parsers.readers.read_table (FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str] filepath_or_buffer, * , str | None | lib.NoDefault sep = lib.no_default, str | None | lib.NoDefault delimiter = None, int | Sequence[int] | None | Literal["infer"] header = "infer", Sequence[Hashable] | None | lib.NoDefault names = lib.no_default, IndexLabel | Literal[False] | None index_col = None, UsecolsArgType usecols = None, DtypeArg | None dtype = None, CSVEngine | None engine = None, Mapping[Hashable, Callable] | None converters = None, list | None true_values = None, list | None false_values = None, bool skipinitialspace = False, list[int] | int | Callable[[Hashable], bool] | None skiprows = None, int skipfooter = 0, int | None nrows = None, Sequence[str] | Mapping[str, Sequence[str]] | None na_values = None, bool keep_default_na = True, bool na_filter = True, bool | lib.NoDefault verbose = lib.no_default, bool skip_blank_lines = True, bool | Sequence[Hashable] parse_dates = False, bool | lib.NoDefault infer_datetime_format = lib.no_default, bool | lib.NoDefault keep_date_col = lib.no_default, Callable | lib.NoDefault date_parser = lib.no_default, str | dict[Hashable, str] | None date_format = None, bool dayfirst = False, bool cache_dates = True, bool iterator = False, int | None chunksize = None, CompressionOptions compression = "infer", str | None thousands = None, str decimal = ".", str | None lineterminator = None, str quotechar = '"', int quoting = csv.QUOTE_MINIMAL, bool doublequote = True, str | None escapechar = None, str | None comment = None, str | None encoding = None, str | None encoding_errors = "strict", str | csv.Dialect | None dialect = None, str on_bad_lines = "error", bool | lib.NoDefault delim_whitespace = lib.no_default, bool low_memory = _c_parser_defaults["low_memory"], bool memory_map = False, str | None float_precision = None, StorageOptions | None storage_options = None, DtypeBackend | lib.NoDefault dtype_backend = lib.no_default)
Definition at line 1271 of file readers.py.
TextParser()
TextFileReader pandas.io.parsers.readers.TextParser (* args, ** kwds)
Converts lists of lists/tuples into DataFrames with proper type inference
and optional (e.g. string to datetime) conversion. Also enables iterating
lazily over chunks of large files
Parameters
----------
data : file-like object or list
delimiter : separator character to use
dialect : str or csv.Dialect instance, optional
    Ignored if delimiter is longer than 1 character
names : sequence, default
header : int, default 0
    Row to use to parse column labels. Defaults to the first row. Prior
    rows will be discarded
index_col : int or list, optional
    Column or columns to use as the (possibly hierarchical) index
has_index_names: bool, default False
    True if the cols defined in index_col have an index name and are
    not in the header.
na_values : scalar, str, list-like, or dict, optional
    Additional strings to recognize as NA/NaN.
keep_default_na : bool, default True
thousands : str, optional
    Thousands separator
comment : str, optional
    Comment out remainder of line
parse_dates : bool, default False
keep_date_col : bool, default False
date_parser : function, optional
    .. deprecated:: 2.0.0
date_format : str or dict of column -> format, default ``None``
    .. versionadded:: 2.0.0
skiprows : list of integers
    Row numbers to skip
skipfooter : int
    Number of line at bottom of file to skip
converters : dict, optional
    Dict of functions for converting values in certain columns. Keys can
    either be integers or column labels, values are functions that take one
    input argument, the cell (not column) content, and return the
    transformed content.
encoding : str, optional
    Encoding to use for UTF when reading/writing (ex. 'utf-8')
float_precision : str, optional
    Specifies which converter the C engine should use for floating-point
    values. The options are `None` or `high` for the ordinary converter,
    `legacy` for the original lower precision pandas converter, and
    `round_trip` for the round-trip converter.
Definition at line 1999 of file readers.py.
References _stringify_na_values().
validate_integer() [1/4]
int pandas.io.parsers.readers.validate_integer (str name, float val, int min_val = ...)
Definition at line 518 of file readers.py.
validate_integer() [2/4]
int | None pandas.io.parsers.readers.validate_integer (str name, int | float | None val, int min_val = 0)
Checks whether the 'name' parameter for parsing is either
an integer OR float that can SAFELY be cast to an integer
without losing accuracy. Raises a ValueError if that is
not the case.
Parameters
----------
name : str
    Parameter name (used for error reporting)
val : int or float
    The value to check
min_val : int
    Minimum allowed value (val < min_val will result in a ValueError)
Definition at line 527 of file readers.py.
validate_integer() [3/4]
int | None pandas.io.parsers.readers.validate_integer (str name, int | None val, int min_val = ...)
Definition at line 523 of file readers.py.
validate_integer() [4/4]
None pandas.io.parsers.readers.validate_integer (str name, None val, int min_val = ...)
Definition at line 513 of file readers.py.
Variable Documentation
_c_unsupported
dict pandas.io.parsers.readers._c_unsupported = {"skipfooter"} protected
Definition at line 484 of file readers.py.
_doc_read_csv_and_table
tuple pandas.io.parsers.readers._doc_read_csv_and_table protected
Initial value:
=  (
    + fill('", "'.join(sorted(STR_NA_VALUES)), 70, subsequent_indent="    ")
    +
)
Definition at line 94 of file readers.py.
_pyarrow_unsupported
dict pandas.io.parsers.readers._pyarrow_unsupported protected
Initial value:
=  {
    "skipfooter",
    "float_precision",
    "chunksize",
    "comment",
    "nrows",
    "thousands",
    "memory_map",
    "dialect",
    "delim_whitespace",
    "quoting",
    "lineterminator",
    "converters",
    "iterator",
    "dayfirst",
    "verbose",
    "skipinitialspace",
    "low_memory",
}
Definition at line 486 of file readers.py.
_python_unsupported
dict pandas.io.parsers.readers._python_unsupported = {"low_memory", "float_precision"} protected
Definition at line 485 of file readers.py.
MANDATORY_DIALECT_ATTRS
tuple pandas.io.parsers.readers.MANDATORY_DIALECT_ATTRS
Initial value:
=  (
    "delimiter",
    "doublequote",
    "escapechar",
    "skipinitialspace",
    "quotechar",
    "quoting",
)
Definition at line 2287 of file readers.py.