Code Cloning Analysis: dateutil.tz.tz.tzstr Class Reference
dateutil.tz.tz.tzstr Class Reference
Public Member Functions
__init__ (self, s, posix_offset=False)
__repr__ (self)
Public Member Functions inherited from dateutil.tz.tz.tzrange
__init__ (self, stdabbr, stdoffset=None, dstabbr=None, dstoffset=None, start=None, end=None)
transitions (self, year)
__eq__ (self, other)
Public Member Functions inherited from dateutil.tz._common.tzrangebase
__init__ (self)
utcoffset (self, dt)
dst (self, dt)
tzname (self, dt)
fromutc (self, dt)
is_ambiguous (self, dt)
__ne__ (self, other)
__repr__ (self)
Protected Member Functions
_delta (self, x, isend=0)
Protected Member Functions inherited from dateutil.tz.tz.tzrange
_dst_base_offset (self)
Protected Member Functions inherited from dateutil.tz._common.tzrangebase
_isdst (self, dt)
_naive_isdst (self, dt, transitions)
Protected Member Functions inherited from dateutil.tz._common._tzinfo
_fold_status (self, dt_utc, dt_wall)
_fold (self, dt)
_fromutc (self, dt)
Protected Attributes
_s = s
Protected Attributes inherited from dateutil.tz.tz.tzrange
_std_abbr = stdabbr
_dst_abbr = dstabbr
_std_offset = datetime.timedelta(seconds=stdoffset)
_dst_offset = datetime.timedelta(seconds=dstoffset)
_start_delta
_end_delta
_dst_base_offset_ = self._dst_offset - self._std_offset
Additional Inherited Members
Public Attributes inherited from dateutil.tz._common.tzrangebase
hasdst
Detailed Description
``tzstr`` objects are time zone objects specified by a time-zone string as
it would be passed to a ``TZ`` variable on POSIX-style systems (see
the `GNU C Library: TZ Variable`_ for more details).
There is one notable exception, which is that POSIX-style time zones use an
inverted offset format, so normally ``GMT+3`` would be parsed as an offset
3 hours *behind* GMT. The ``tzstr`` time zone object will parse this as an
offset 3 hours *ahead* of GMT. If you would like to maintain the POSIX
behavior, pass a ``True`` value to ``posix_offset``.
The :class:`tzrange` object provides the same functionality, but is
specified using :class:`relativedelta.relativedelta` objects. rather than
strings.
:param s:
    A time zone string in ``TZ`` variable format. This can be a
    :class:`bytes` (2.x: :class:`str`), :class:`str` (2.x:
    :class:`unicode`) or a stream emitting unicode characters
    (e.g. :class:`StringIO`).
:param posix_offset:
    Optional. If set to ``True``, interpret strings such as ``GMT+3`` or
    ``UTC+3`` as being 3 hours *behind* UTC rather than ahead, per the
    POSIX standard.
.. caution::
    Prior to version 2.7.0, this function also supported time zones
    in the format:
        * ``EST5EDT,4,0,6,7200,10,0,26,7200,3600``
        * ``EST5EDT,4,1,0,7200,10,-1,0,7200,3600``
    This format is non-standard and has been deprecated; this function
    will raise a :class:`DeprecatedTZFormatWarning` until
    support is removed in a future version.
.. _`GNU C Library: TZ Variable`:
    https://www.gnu.org/software/libc/manual/html_node/TZ-Variable.html
Definition at line 1037 of file tz.py.
Constructor & Destructor Documentation
__init__()
dateutil.tz.tz.tzstr.__init__ (self, s, posix_offset = False)
Definition at line 1079 of file tz.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__repr__()
dateutil.tz.tz.tzstr.__repr__ (self)
Definition at line 1152 of file tz.py.
_delta()
dateutil.tz.tz.tzstr._delta (self, x, isend = 0) protected
Definition at line 1111 of file tz.py.
Referenced by PIL.QoiImagePlugin.QoiEncoder.encode().
Member Data Documentation
_s
dateutil.tz.tz.tzstr._s = s protected
Definition at line 1083 of file tz.py.
Referenced by dateutil.tz.tz.tzical.get().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/dateutil/tz/tz.py