Code Cloning Analysis: pandas.tests.util.test_assert_almost_equal Namespace Reference
pandas.tests.util.test_assert_almost_equal Namespace Reference
Functions
_assert_almost_equal_both (a, b, **kwargs)
_assert_not_almost_equal (a, b, **kwargs)
_assert_not_almost_equal_both (a, b, **kwargs)
test_assert_almost_equal_numbers (a, b)
test_assert_not_almost_equal_numbers (a, b)
test_assert_almost_equal_numbers_atol (a, b)
test_assert_not_almost_equal_numbers_atol (a, b)
test_assert_almost_equal_numbers_rtol (a, b)
test_assert_not_almost_equal_numbers_rtol (a, b)
test_assert_almost_equal_complex_numbers (a, b, rtol)
test_assert_not_almost_equal_complex_numbers (a, b, rtol)
test_assert_almost_equal_numbers_with_zeros (a, b)
test_assert_not_almost_equal_numbers_with_zeros (a, b)
test_assert_not_almost_equal_numbers_with_mixed (a, b)
test_assert_almost_equal_edge_case_ndarrays (left_dtype, right_dtype)
test_assert_almost_equal_sets ()
test_assert_almost_not_equal_sets ()
test_assert_almost_equal_dicts ()
test_assert_not_almost_equal_dicts (a, b)
test_assert_almost_equal_dict_like_object (val)
test_assert_almost_equal_strings ()
test_assert_not_almost_equal_strings (a, b)
test_assert_almost_equal_iterables (a, b)
test_assert_not_almost_equal_iterables (a, b)
test_assert_almost_equal_null ()
test_assert_not_almost_equal_null (a, b)
test_assert_almost_equal_inf (a, b)
test_mismatched_na_assert_almost_equal_deprecation (left, right)
test_assert_not_almost_equal_inf ()
test_assert_almost_equal_pandas (a, b)
test_assert_almost_equal_object ()
test_assert_almost_equal_value_mismatch ()
test_assert_almost_equal_class_mismatch (a, b, klass1, klass2)
test_assert_almost_equal_value_mismatch1 ()
test_assert_almost_equal_value_mismatch2 ()
test_assert_almost_equal_value_mismatch3 ()
test_assert_almost_equal_value_mismatch4 ()
test_assert_almost_equal_shape_mismatch_override ()
test_assert_almost_equal_unicode ()
test_assert_almost_equal_timestamp ()
test_assert_almost_equal_iterable_length_mismatch ()
test_assert_almost_equal_iterable_values_mismatch ()
test_assert_almost_equal_array_nested (a, b)
Variables
list objs = [NA, np.nan, NaT, None, np.datetime64("NaT"), np.timedelta64("NaT")]
subarr = np.empty(2, dtype=object)
dtype
list NESTED_CASES
Function Documentation
_assert_almost_equal_both()
pandas.tests.util.test_assert_almost_equal._assert_almost_equal_both (a, b, ** kwargs) protected
Check that two objects are approximately equal.
This check is performed commutatively.
Parameters
----------
a : object
    The first object to compare.
b : object
    The second object to compare.
**kwargs
    The arguments passed to `tm.assert_almost_equal`.
Definition at line 15 of file test_assert_almost_equal.py.
Referenced by _assert_not_almost_equal_both().
_assert_not_almost_equal()
pandas.tests.util.test_assert_almost_equal._assert_not_almost_equal (a, b, ** kwargs) protected
Check that two objects are not approximately equal.
Parameters
----------
a : object
    The first object to compare.
b : object
    The second object to compare.
**kwargs
    The arguments passed to `tm.assert_almost_equal`.
Definition at line 34 of file test_assert_almost_equal.py.
Referenced by _assert_not_almost_equal_both().
_assert_not_almost_equal_both()
pandas.tests.util.test_assert_almost_equal._assert_not_almost_equal_both (a, b, ** kwargs) protected
Check that two objects are not approximately equal.
This check is performed commutatively.
Parameters
----------
a : object
    The first object to compare.
b : object
    The second object to compare.
**kwargs
    The arguments passed to `tm.assert_almost_equal`.
Definition at line 55 of file test_assert_almost_equal.py.
References _assert_almost_equal_both(), _assert_not_almost_equal(), and _assert_not_almost_equal_both().
Referenced by _assert_not_almost_equal_both().
test_assert_almost_equal_array_nested()
pandas.tests.util.test_assert_almost_equal.test_assert_almost_equal_array_nested (a, b)
Definition at line 585 of file test_assert_almost_equal.py.
test_assert_almost_equal_class_mismatch()
pandas.tests.util.test_assert_almost_equal.test_assert_almost_equal_class_mismatch (a, b, klass1, klass2)
Definition at line 390 of file test_assert_almost_equal.py.
test_assert_almost_equal_complex_numbers()
pandas.tests.util.test_assert_almost_equal.test_assert_almost_equal_complex_numbers (a, b, rtol)
Definition at line 155 of file test_assert_almost_equal.py.
test_assert_almost_equal_dict_like_object()
pandas.tests.util.test_assert_almost_equal.test_assert_almost_equal_dict_like_object (val)
Definition at line 238 of file test_assert_almost_equal.py.
test_assert_almost_equal_dicts()
pandas.tests.util.test_assert_almost_equal.test_assert_almost_equal_dicts ()
Definition at line 219 of file test_assert_almost_equal.py.
test_assert_almost_equal_edge_case_ndarrays()
pandas.tests.util.test_assert_almost_equal.test_assert_almost_equal_edge_case_ndarrays (left_dtype, right_dtype)
Definition at line 198 of file test_assert_almost_equal.py.
test_assert_almost_equal_inf()
pandas.tests.util.test_assert_almost_equal.test_assert_almost_equal_inf (a, b)
Definition at line 309 of file test_assert_almost_equal.py.
test_assert_almost_equal_iterable_length_mismatch()
pandas.tests.util.test_assert_almost_equal.test_assert_almost_equal_iterable_length_mismatch ()
Definition at line 483 of file test_assert_almost_equal.py.
test_assert_almost_equal_iterable_values_mismatch()
pandas.tests.util.test_assert_almost_equal.test_assert_almost_equal_iterable_values_mismatch ()
Definition at line 494 of file test_assert_almost_equal.py.
test_assert_almost_equal_iterables()
pandas.tests.util.test_assert_almost_equal.test_assert_almost_equal_iterables (a, b)
Definition at line 270 of file test_assert_almost_equal.py.
test_assert_almost_equal_null()
pandas.tests.util.test_assert_almost_equal.test_assert_almost_equal_null ()
Definition at line 292 of file test_assert_almost_equal.py.
test_assert_almost_equal_numbers()
pandas.tests.util.test_assert_almost_equal.test_assert_almost_equal_numbers (a, b)
Definition at line 84 of file test_assert_almost_equal.py.
test_assert_almost_equal_numbers_atol()
pandas.tests.util.test_assert_almost_equal.test_assert_almost_equal_numbers_atol (a, b)
Definition at line 116 of file test_assert_almost_equal.py.
test_assert_almost_equal_numbers_rtol()
pandas.tests.util.test_assert_almost_equal.test_assert_almost_equal_numbers_rtol (a, b)
Definition at line 137 of file test_assert_almost_equal.py.
test_assert_almost_equal_numbers_with_zeros()
pandas.tests.util.test_assert_almost_equal.test_assert_almost_equal_numbers_with_zeros (a, b)
Definition at line 178 of file test_assert_almost_equal.py.
test_assert_almost_equal_object()
pandas.tests.util.test_assert_almost_equal.test_assert_almost_equal_object ()
Definition at line 373 of file test_assert_almost_equal.py.
test_assert_almost_equal_pandas()
pandas.tests.util.test_assert_almost_equal.test_assert_almost_equal_pandas (a, b)
Definition at line 369 of file test_assert_almost_equal.py.
test_assert_almost_equal_sets()
pandas.tests.util.test_assert_almost_equal.test_assert_almost_equal_sets ()
Definition at line 207 of file test_assert_almost_equal.py.
test_assert_almost_equal_shape_mismatch_override()
pandas.tests.util.test_assert_almost_equal.test_assert_almost_equal_shape_mismatch_override ()
Definition at line 447 of file test_assert_almost_equal.py.
test_assert_almost_equal_strings()
pandas.tests.util.test_assert_almost_equal.test_assert_almost_equal_strings ()
Definition at line 256 of file test_assert_almost_equal.py.
test_assert_almost_equal_timestamp()
pandas.tests.util.test_assert_almost_equal.test_assert_almost_equal_timestamp ()
Definition at line 469 of file test_assert_almost_equal.py.
test_assert_almost_equal_unicode()
pandas.tests.util.test_assert_almost_equal.test_assert_almost_equal_unicode ()
Definition at line 457 of file test_assert_almost_equal.py.
test_assert_almost_equal_value_mismatch()
pandas.tests.util.test_assert_almost_equal.test_assert_almost_equal_value_mismatch ()
Definition at line 379 of file test_assert_almost_equal.py.
test_assert_almost_equal_value_mismatch1()
pandas.tests.util.test_assert_almost_equal.test_assert_almost_equal_value_mismatch1 ()
Definition at line 401 of file test_assert_almost_equal.py.
test_assert_almost_equal_value_mismatch2()
pandas.tests.util.test_assert_almost_equal.test_assert_almost_equal_value_mismatch2 ()
Definition at line 412 of file test_assert_almost_equal.py.
test_assert_almost_equal_value_mismatch3()
pandas.tests.util.test_assert_almost_equal.test_assert_almost_equal_value_mismatch3 ()
Definition at line 423 of file test_assert_almost_equal.py.
test_assert_almost_equal_value_mismatch4()
pandas.tests.util.test_assert_almost_equal.test_assert_almost_equal_value_mismatch4 ()
Definition at line 436 of file test_assert_almost_equal.py.
test_assert_almost_not_equal_sets()
pandas.tests.util.test_assert_almost_equal.test_assert_almost_not_equal_sets ()
Definition at line 212 of file test_assert_almost_equal.py.
test_assert_not_almost_equal_complex_numbers()
pandas.tests.util.test_assert_almost_equal.test_assert_not_almost_equal_complex_numbers (a, b, rtol)
Definition at line 171 of file test_assert_almost_equal.py.
test_assert_not_almost_equal_dicts()
pandas.tests.util.test_assert_almost_equal.test_assert_not_almost_equal_dicts (a, b)
Definition at line 233 of file test_assert_almost_equal.py.
test_assert_not_almost_equal_inf()
pandas.tests.util.test_assert_almost_equal.test_assert_not_almost_equal_inf ()
Definition at line 356 of file test_assert_almost_equal.py.
test_assert_not_almost_equal_iterables()
pandas.tests.util.test_assert_almost_equal.test_assert_not_almost_equal_iterables (a, b)
Definition at line 288 of file test_assert_almost_equal.py.
test_assert_not_almost_equal_null()
pandas.tests.util.test_assert_almost_equal.test_assert_not_almost_equal_null (a, b)
Definition at line 297 of file test_assert_almost_equal.py.
test_assert_not_almost_equal_numbers()
pandas.tests.util.test_assert_almost_equal.test_assert_not_almost_equal_numbers (a, b)
Definition at line 100 of file test_assert_almost_equal.py.
test_assert_not_almost_equal_numbers_atol()
pandas.tests.util.test_assert_almost_equal.test_assert_not_almost_equal_numbers_atol (a, b)
Definition at line 122 of file test_assert_almost_equal.py.
test_assert_not_almost_equal_numbers_rtol()
pandas.tests.util.test_assert_almost_equal.test_assert_not_almost_equal_numbers_rtol (a, b)
Definition at line 142 of file test_assert_almost_equal.py.
test_assert_not_almost_equal_numbers_with_mixed()
pandas.tests.util.test_assert_almost_equal.test_assert_not_almost_equal_numbers_with_mixed (a, b)
Definition at line 188 of file test_assert_almost_equal.py.
test_assert_not_almost_equal_numbers_with_zeros()
pandas.tests.util.test_assert_almost_equal.test_assert_not_almost_equal_numbers_with_zeros (a, b)
Definition at line 183 of file test_assert_almost_equal.py.
test_assert_not_almost_equal_strings()
pandas.tests.util.test_assert_almost_equal.test_assert_not_almost_equal_strings (a, b)
Definition at line 263 of file test_assert_almost_equal.py.
test_mismatched_na_assert_almost_equal_deprecation()
pandas.tests.util.test_assert_almost_equal.test_mismatched_na_assert_almost_equal_deprecation (left, right)
Definition at line 318 of file test_assert_almost_equal.py.
Variable Documentation
dtype
pandas.tests.util.test_assert_almost_equal.dtype
Definition at line 506 of file test_assert_almost_equal.py.
NESTED_CASES
list pandas.tests.util.test_assert_almost_equal.NESTED_CASES
Definition at line 508 of file test_assert_almost_equal.py.
objs
list pandas.tests.util.test_assert_almost_equal.objs = [NA, np.nan, NaT, None, np.datetime64("NaT"), np.timedelta64("NaT")]
Definition at line 313 of file test_assert_almost_equal.py.
subarr
pandas.tests.util.test_assert_almost_equal.subarr = np.empty(2, dtype=object)
Definition at line 505 of file test_assert_almost_equal.py.