Code Cloning Analysis: scipy.integrate._quadpack_py._OptFunc Class Reference
scipy.integrate._quadpack_py._OptFunc Class Reference
Public Member Functions
__init__ (self, opt)
__call__ (self, *args)
Public Attributes
opt = opt
Detailed Description
Definition at line 1195 of file _quadpack_py.py.
Constructor & Destructor Documentation
__init__()
scipy.integrate._quadpack_py._OptFunc.__init__ (self, opt)
Definition at line 1196 of file _quadpack_py.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
__call__()
scipy.integrate._quadpack_py._OptFunc.__call__ (self, * args)
Return stored dict.
Definition at line 1199 of file _quadpack_py.py.
References opt.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), and scipy.interpolate._fitpack2.SphereBivariateSpline.ev().
Member Data Documentation
opt
scipy.integrate._quadpack_py._OptFunc.opt = opt
Definition at line 1197 of file _quadpack_py.py.
Referenced by __call__().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/integrate/_quadpack_py.py