Code Cloning Analysis: fontTools.varLib.merger.VariationMerger Class Reference
fontTools.varLib.merger.VariationMerger Class Reference
Public Member Functions
__init__ (self, model, axisTags, font)
setModel (self, model)
mergeThings (self, out, lst)
Public Member Functions inherited from fontTools.varLib.merger.Merger
__init__ (self, font=None)
merger (celf, clazzes, attrs=(None,))
mergersFor (celf, thing, _default={})
mergeObjects (self, out, lst, exclude=())
mergeLists (self, out, lst)
mergeTables (self, font, master_ttfs, tableTags)
Public Attributes
store_builder = varStore.OnlineVarStoreBuilder(axisTags)
model = model
Public Attributes inherited from fontTools.varLib.merger.Merger
font = font
ttfs = None
Detailed Description
A merger that takes multiple master fonts, and builds a
variable font.
Definition at line 1214 of file merger.py.
Constructor & Destructor Documentation
__init__()
fontTools.varLib.merger.VariationMerger.__init__ (self, model, axisTags, font)
Definition at line 1218 of file merger.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
mergeThings()
fontTools.varLib.merger.VariationMerger.mergeThings (self, out, lst)
Reimplemented from fontTools.varLib.merger.Merger.
Definition at line 1227 of file merger.py.
setModel()
fontTools.varLib.merger.VariationMerger.setModel (self, model)
Definition at line 1223 of file merger.py.
Member Data Documentation
model
fontTools.varLib.merger.VariationMerger.model = model
Definition at line 1224 of file merger.py.
Referenced by scipy.odr._odrpack.ODR._check(), scipy.odr._odrpack.ODR._gen_work(), and scipy.odr._odrpack.ODR.run().
store_builder
fontTools.varLib.merger.VariationMerger.store_builder = varStore.OnlineVarStoreBuilder(axisTags)
Definition at line 1220 of file merger.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/varLib/merger.py