Code Cloning Analysis: axisartist.axislines._FloatingAxisArtistHelperBase Class Reference
axisartist.axislines._FloatingAxisArtistHelperBase Class Reference
Public Member Functions
__init__ (self, nth_coord, value)
get_line (self, axes)
Public Member Functions inherited from axisartist.axislines._AxisArtistHelperBase
__init__ (self, nth_coord)
update_lim (self, axes)
get_nth_coord (self)
Protected Attributes
_value = value
Additional Inherited Members
Public Attributes inherited from axisartist.axislines._AxisArtistHelperBase
int nth_coord = nth_coord
Protected Member Functions inherited from axisartist.axislines._AxisArtistHelperBase
_to_xy (self, values, const)
Detailed Description
Definition at line 161 of file axislines.py.
Constructor & Destructor Documentation
__init__()
axisartist.axislines._FloatingAxisArtistHelperBase.__init__ (self, nth_coord, value)
Definition at line 162 of file axislines.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
get_line()
axisartist.axislines._FloatingAxisArtistHelperBase.get_line (self, axes)
Definition at line 166 of file axislines.py.
Member Data Documentation
_value
axisartist.axislines._FloatingAxisArtistHelperBase._value = value protected
Definition at line 163 of file axislines.py.
Referenced by scipy.optimize._optimize.MemoizeJac.__call__(), axisartist.axislines.FloatingAxisArtistHelperRectilinear.get_axislabel_pos_angle(), axisartist.axislines.FloatingAxisArtistHelperRectilinear.get_tick_iterators(), pandas.core.computation.ops.Term.update(), and pandas.io.stata.StataMissingValue.value().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/mpl_toolkits/axisartist/axislines.py