Code Cloning Analysis: fontTools.mtiLib.ContextHelper Class Reference
fontTools.mtiLib.ContextHelper Class Reference
Public Member Functions
__init__ (self, klassName, Format)
Public Attributes
Typ = Typ
Type = Type
Chain = Chain
ChainTyp = ChainTyp
InputIdx = InputIdx
DataLen = DataLen
str LookupRecord = Type + "LookupRecord"
Coverage = ChainCoverage
ContextData = ChainContextData
SetContextData = SetChainContextData
RuleData = ChainRuleData
SetRuleData = ChainSetRuleData
str Rule = ChainTyp + "Rule"
str RuleCount = ChainTyp + "RuleCount"
str RuleSet = ChainTyp + "RuleSet"
str RuleSetCount = ChainTyp + "RuleSetCount"
Intersect = lambda glyphs, c, r: [r] if r in glyphs else []
str ClassDef = "InputClassDef" if Chain else "ClassDef"
int ClassDefIndex = 1 if Chain else 0
str Input = "Input" if Chain else "Class"
Detailed Description
Definition at line 589 of file __init__.py.
Constructor & Destructor Documentation
__init__()
fontTools.mtiLib.ContextHelper.__init__ (self, klassName, Format)
Definition at line 590 of file __init__.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Data Documentation
Chain
fontTools.mtiLib.ContextHelper.Chain = Chain
Definition at line 609 of file __init__.py.
ChainTyp
fontTools.mtiLib.ContextHelper.ChainTyp = ChainTyp
Definition at line 610 of file __init__.py.
ClassDef
str fontTools.mtiLib.ContextHelper.ClassDef = "InputClassDef" if Chain else "ClassDef"
Definition at line 726 of file __init__.py.
ClassDefIndex
int fontTools.mtiLib.ContextHelper.ClassDefIndex = 1 if Chain else 0
Definition at line 727 of file __init__.py.
ContextData
fontTools.mtiLib.ContextHelper.ContextData = ChainContextData
Definition at line 698 of file __init__.py.
Coverage
fontTools.mtiLib.ContextHelper.Coverage = ChainCoverage
Definition at line 697 of file __init__.py.
DataLen
fontTools.mtiLib.ContextHelper.DataLen = DataLen
Definition at line 612 of file __init__.py.
Input
str fontTools.mtiLib.ContextHelper.Input = "Input" if Chain else "Class"
Definition at line 728 of file __init__.py.
InputIdx
fontTools.mtiLib.ContextHelper.InputIdx = InputIdx
Definition at line 611 of file __init__.py.
Intersect
fontTools.mtiLib.ContextHelper.Intersect = lambda glyphs, c, r: [r] if r in glyphs else []
Definition at line 714 of file __init__.py.
LookupRecord
str fontTools.mtiLib.ContextHelper.LookupRecord = Type + "LookupRecord"
Definition at line 614 of file __init__.py.
Rule
str fontTools.mtiLib.ContextHelper.Rule = ChainTyp + "Rule"
Definition at line 710 of file __init__.py.
RuleCount
str fontTools.mtiLib.ContextHelper.RuleCount = ChainTyp + "RuleCount"
Definition at line 711 of file __init__.py.
RuleData
fontTools.mtiLib.ContextHelper.RuleData = ChainRuleData
Definition at line 700 of file __init__.py.
RuleSet
str fontTools.mtiLib.ContextHelper.RuleSet = ChainTyp + "RuleSet"
Definition at line 712 of file __init__.py.
RuleSetCount
str fontTools.mtiLib.ContextHelper.RuleSetCount = ChainTyp + "RuleSetCount"
Definition at line 713 of file __init__.py.
SetContextData
fontTools.mtiLib.ContextHelper.SetContextData = SetChainContextData
Definition at line 699 of file __init__.py.
SetRuleData
fontTools.mtiLib.ContextHelper.SetRuleData = ChainSetRuleData
Definition at line 701 of file __init__.py.
Typ
fontTools.mtiLib.ContextHelper.Typ = Typ
Definition at line 607 of file __init__.py.
Type
fontTools.mtiLib.ContextHelper.Type = Type
Definition at line 608 of file __init__.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/mtiLib/__init__.py