Code Cloning Analysis: fontTools.otlLib.maxContextCalc Namespace Reference
fontTools.otlLib.maxContextCalc Namespace Reference
Functions
maxCtxFont (font)
maxCtxSubtable (maxCtx, tag, lookupType, st)
maxCtxContextualSubtable (maxCtx, st, ruleType, chain="")
maxCtxContextualRule (maxCtx, st, chain)
Variables
list __all__ = ["maxCtxFont"]
Function Documentation
maxCtxContextualRule()
fontTools.otlLib.maxContextCalc.maxCtxContextualRule (maxCtx, st, chain)
Calculate usMaxContext based on a contextual feature rule.
Definition at line 89 of file maxContextCalc.py.
Referenced by maxCtxContextualSubtable(), and maxCtxSubtable().
maxCtxContextualSubtable()
fontTools.otlLib.maxContextCalc.maxCtxContextualSubtable (maxCtx, st, ruleType, chain = "")
Calculate usMaxContext based on a contextual feature subtable.
Definition at line 62 of file maxContextCalc.py.
References maxCtxContextualRule().
Referenced by maxCtxSubtable().
maxCtxFont()
fontTools.otlLib.maxContextCalc.maxCtxFont (font)
Calculate the usMaxContext value for an entire font.
Definition at line 4 of file maxContextCalc.py.
References maxCtxSubtable().
maxCtxSubtable()
fontTools.otlLib.maxContextCalc.maxCtxSubtable (maxCtx, tag, lookupType, st)
Calculate usMaxContext based on a single lookup table (and an existing
max value).
Definition at line 20 of file maxContextCalc.py.
References maxCtxContextualRule(), maxCtxContextualSubtable(), and maxCtxSubtable().
Referenced by maxCtxFont(), and maxCtxSubtable().
Variable Documentation
__all__
list fontTools.otlLib.maxContextCalc.__all__ = ["maxCtxFont"] private
Definition at line 1 of file maxContextCalc.py.