Code Cloning Analysis: numpy.lib.mixins.NDArrayOperatorsMixin Class Reference
numpy.lib.mixins.NDArrayOperatorsMixin Class Reference
Static Private Attributes
tuple __slots__ = ()
__lt__ = _binary_method(um.less, 'lt')
__le__ = _binary_method(um.less_equal, 'le')
__eq__ = _binary_method(um.equal, 'eq')
__ne__ = _binary_method(um.not_equal, 'ne')
__gt__ = _binary_method(um.greater, 'gt')
__ge__ = _binary_method(um.greater_equal, 'ge')
__add__
__radd__
__iadd__
__sub__
__rsub__
__isub__
__mul__
__rmul__
__imul__
__matmul__
__rmatmul__
__imatmul__
__truediv__
__rtruediv__
__itruediv__
__floordiv__
__rfloordiv__
__ifloordiv__
__mod__
__rmod__
__imod__
__divmod__ = _binary_method(um.divmod, 'divmod')
__rdivmod__ = _reflected_binary_method(um.divmod, 'divmod')
__pow__
__rpow__
__ipow__
__lshift__
__rlshift__
__ilshift__
__rshift__
__rrshift__
__irshift__
__and__
__rand__
__iand__
__xor__
__rxor__
__ixor__
__or__
__ror__
__ior__
__neg__ = _unary_method(um.negative, 'neg')
__pos__ = _unary_method(um.positive, 'pos')
__abs__ = _unary_method(um.absolute, 'abs')
__invert__ = _unary_method(um.invert, 'invert')
Detailed Description
Mixin defining all operator special methods using __array_ufunc__.
This class implements the special methods for almost all of Python's
builtin operators defined in the `operator` module, including comparisons
(``==``, ``>``, etc.) and arithmetic (``+``, ``*``, ``-``, etc.), by
deferring to the ``__array_ufunc__`` method, which subclasses must
implement.
It is useful for writing classes that do not inherit from `numpy.ndarray`,
but that should support arithmetic and numpy universal functions like
arrays as described in `A Mechanism for Overriding Ufuncs
<https://numpy.org/neps/nep-0013-ufunc-overrides.html>`_.
As an trivial example, consider this implementation of an ``ArrayLike``
class that simply wraps a NumPy array and ensures that the result of any
arithmetic operation is also an ``ArrayLike`` object::
    class ArrayLike(np.lib.mixins.NDArrayOperatorsMixin):
        def __init__(self, value):
            self.value = np.asarray(value)
        # One might also consider adding the built-in list type to this
        # list, to support operations like np.add(array_like, list)
        _HANDLED_TYPES = (np.ndarray, numbers.Number)
        def __array_ufunc__(self, ufunc, method, *inputs, **kwargs):
            out = kwargs.get('out', ())
            for x in inputs + out:
                # Only support operations with instances of _HANDLED_TYPES.
                # Use ArrayLike instead of type(self) for isinstance to
                # allow subclasses that don't override __array_ufunc__ to
                # handle ArrayLike objects.
                if not isinstance(x, self._HANDLED_TYPES + (ArrayLike,)):
                    return NotImplemented
            # Defer to the implementation of the ufunc on unwrapped values.
            inputs = tuple(x.value if isinstance(x, ArrayLike) else x
                           for x in inputs)
            if out:
                kwargs['out'] = tuple(
                    x.value if isinstance(x, ArrayLike) else x
                    for x in out)
            result = getattr(ufunc, method)(*inputs, **kwargs)
            if type(result) is tuple:
                # multiple return values
                return tuple(type(self)(x) for x in result)
            elif method == 'at':
                # no return value
                return None
            else:
                # one return value
                return type(self)(result)
        def __repr__(self):
            return '%s(%r)' % (type(self).__name__, self.value)
In interactions between ``ArrayLike`` objects and numbers or numpy arrays,
the result is always another ``ArrayLike``:
    >>> x = ArrayLike([1, 2, 3])
    >>> x - 1
    ArrayLike(array([0, 1, 2]))
    >>> 1 - x
    ArrayLike(array([ 0, -1, -2]))
    >>> np.arange(3) - x
    ArrayLike(array([-1, -1, -1]))
    >>> x - np.arange(3)
    ArrayLike(array([1, 1, 1]))
Note that unlike ``numpy.ndarray``, ``ArrayLike`` does not allow operations
with arbitrary, unrecognized types. This ensures that interactions with
ArrayLike preserve a well-defined casting hierarchy.
.. versionadded:: 1.13
Definition at line 59 of file mixins.py.
Member Data Documentation
__abs__
numpy.lib.mixins.NDArrayOperatorsMixin.__abs__ = _unary_method(um.absolute, 'abs') static private
Definition at line 176 of file mixins.py.
__add__
numpy.lib.mixins.NDArrayOperatorsMixin.__add__ static private
Definition at line 149 of file mixins.py.
Referenced by scipy.signal._ltisys.StateSpace.__add__(), scipy.sparse.linalg._interface.LinearOperator._rdot(), dateutil.relativedelta.relativedelta.normalized(), and scipy.sparse._base._spbase.power().
__and__
numpy.lib.mixins.NDArrayOperatorsMixin.__and__ static private
Definition at line 169 of file mixins.py.
__divmod__
numpy.lib.mixins.NDArrayOperatorsMixin.__divmod__ = _binary_method(um.divmod, 'divmod') static private
Definition at line 160 of file mixins.py.
Referenced by numpy.polynomial._polybase.ABCPolyBase._str_term_ascii().
__eq__
numpy.lib.mixins.NDArrayOperatorsMixin.__eq__ = _binary_method(um.equal, 'eq') static private
Definition at line 143 of file mixins.py.
Referenced by fontTools.ttLib.tables.ttProgram.Program.__bool__(), pandas.core.dtypes.base.ExtensionDtype.__eq__(), pandas.io.pytables.IndexCol.__eq__(), fontTools.ttLib.tables._g_l_y_f.GlyphCoordinates.__ne__(), pip._vendor.msgpack.ext.Timestamp.__ne__(), numpy.polynomial._polybase.ABCPolyBase._str_term_ascii(), fontTools.ttLib.tables._g_l_y_f.Glyph.drawPoints(), fontTools.ttLib.tables.otBase.OTTableWriter.getDataForHarfbuzz(), pip._vendor.distlib.version.Matcher.match(), pandas.core.dtypes.dtypes.PeriodDtype.na_value(), dateutil.relativedelta.relativedelta.normalized(), and numpy.lib.polynomial.poly1d.roots().
__floordiv__
numpy.lib.mixins.NDArrayOperatorsMixin.__floordiv__ static private
Definition at line 157 of file mixins.py.
Referenced by numpy.polynomial._polybase.ABCPolyBase._str_term_ascii().
__ge__
numpy.lib.mixins.NDArrayOperatorsMixin.__ge__ = _binary_method(um.greater_equal, 'ge') static private
Definition at line 146 of file mixins.py.
__gt__
numpy.lib.mixins.NDArrayOperatorsMixin.__gt__ = _binary_method(um.greater, 'gt') static private
Definition at line 145 of file mixins.py.
__iadd__
numpy.lib.mixins.NDArrayOperatorsMixin.__iadd__ static private
Definition at line 149 of file mixins.py.
Referenced by pip._vendor.pyparsing.results.ParseResults.extend(), and pyparsing.results.ParseResults.extend().
__iand__
numpy.lib.mixins.NDArrayOperatorsMixin.__iand__ static private
Definition at line 169 of file mixins.py.
__ifloordiv__
numpy.lib.mixins.NDArrayOperatorsMixin.__ifloordiv__ static private
Definition at line 157 of file mixins.py.
__ilshift__
numpy.lib.mixins.NDArrayOperatorsMixin.__ilshift__ static private
Definition at line 165 of file mixins.py.
__imatmul__
numpy.lib.mixins.NDArrayOperatorsMixin.__imatmul__ static private
Definition at line 152 of file mixins.py.
__imod__
numpy.lib.mixins.NDArrayOperatorsMixin.__imod__ static private
Definition at line 159 of file mixins.py.
__imul__
numpy.lib.mixins.NDArrayOperatorsMixin.__imul__ static private
Definition at line 151 of file mixins.py.
__invert__
numpy.lib.mixins.NDArrayOperatorsMixin.__invert__ = _unary_method(um.invert, 'invert') static private
Definition at line 177 of file mixins.py.
__ior__
numpy.lib.mixins.NDArrayOperatorsMixin.__ior__ static private
Definition at line 171 of file mixins.py.
__ipow__
numpy.lib.mixins.NDArrayOperatorsMixin.__ipow__ static private
Definition at line 164 of file mixins.py.
__irshift__
numpy.lib.mixins.NDArrayOperatorsMixin.__irshift__ static private
Definition at line 167 of file mixins.py.
__isub__
numpy.lib.mixins.NDArrayOperatorsMixin.__isub__ static private
Definition at line 150 of file mixins.py.
__itruediv__
numpy.lib.mixins.NDArrayOperatorsMixin.__itruediv__ static private
Definition at line 155 of file mixins.py.
Referenced by scipy.sparse._base._spbase._divide().
__ixor__
numpy.lib.mixins.NDArrayOperatorsMixin.__ixor__ static private
Definition at line 170 of file mixins.py.
__le__
numpy.lib.mixins.NDArrayOperatorsMixin.__le__ = _binary_method(um.less_equal, 'le') static private
Definition at line 142 of file mixins.py.
__lshift__
numpy.lib.mixins.NDArrayOperatorsMixin.__lshift__ static private
Definition at line 165 of file mixins.py.
__lt__
numpy.lib.mixins.NDArrayOperatorsMixin.__lt__ = _binary_method(um.less, 'lt') static private
Definition at line 141 of file mixins.py.
__matmul__
numpy.lib.mixins.NDArrayOperatorsMixin.__matmul__ static private
Definition at line 152 of file mixins.py.
__mod__
numpy.lib.mixins.NDArrayOperatorsMixin.__mod__ static private
Definition at line 159 of file mixins.py.
__mul__
numpy.lib.mixins.NDArrayOperatorsMixin.__mul__ static private
Definition at line 151 of file mixins.py.
Referenced by pip._vendor.pyparsing.core.ParserElement.__mul__(), pyparsing.core.ParserElement.__mul__(), scipy.signal._ltisys.StateSpace.__truediv__(), scipy.sparse.linalg._interface.LinearOperator.dot(), and dateutil.relativedelta.relativedelta.normalized().
__ne__
numpy.lib.mixins.NDArrayOperatorsMixin.__ne__ = _binary_method(um.not_equal, 'ne') static private
Definition at line 144 of file mixins.py.
__neg__
numpy.lib.mixins.NDArrayOperatorsMixin.__neg__ = _unary_method(um.negative, 'neg') static private
Definition at line 174 of file mixins.py.
Referenced by dateutil.relativedelta.relativedelta.normalized().
__or__
numpy.lib.mixins.NDArrayOperatorsMixin.__or__ static private
Definition at line 171 of file mixins.py.
__pos__
numpy.lib.mixins.NDArrayOperatorsMixin.__pos__ = _unary_method(um.positive, 'pos') static private
Definition at line 175 of file mixins.py.
__pow__
numpy.lib.mixins.NDArrayOperatorsMixin.__pow__ static private
Definition at line 164 of file mixins.py.
__radd__
numpy.lib.mixins.NDArrayOperatorsMixin.__radd__ static private
Definition at line 149 of file mixins.py.
__rand__
numpy.lib.mixins.NDArrayOperatorsMixin.__rand__ static private
Definition at line 169 of file mixins.py.
__rdivmod__
numpy.lib.mixins.NDArrayOperatorsMixin.__rdivmod__ = _reflected_binary_method(um.divmod, 'divmod') static private
Definition at line 161 of file mixins.py.
Referenced by numpy.polynomial._polybase.ABCPolyBase._str_term_ascii().
__rfloordiv__
numpy.lib.mixins.NDArrayOperatorsMixin.__rfloordiv__ static private
Definition at line 157 of file mixins.py.
Referenced by numpy.polynomial._polybase.ABCPolyBase._str_term_ascii().
__rlshift__
numpy.lib.mixins.NDArrayOperatorsMixin.__rlshift__ static private
Definition at line 165 of file mixins.py.
__rmatmul__
numpy.lib.mixins.NDArrayOperatorsMixin.__rmatmul__ static private
Definition at line 152 of file mixins.py.
__rmod__
numpy.lib.mixins.NDArrayOperatorsMixin.__rmod__ static private
Definition at line 159 of file mixins.py.
__rmul__
numpy.lib.mixins.NDArrayOperatorsMixin.__rmul__ static private
Definition at line 151 of file mixins.py.
Referenced by scipy.sparse.linalg._interface.LinearOperator.dot().
__ror__
numpy.lib.mixins.NDArrayOperatorsMixin.__ror__ static private
Definition at line 171 of file mixins.py.
__rpow__
numpy.lib.mixins.NDArrayOperatorsMixin.__rpow__ static private
Definition at line 164 of file mixins.py.
__rrshift__
numpy.lib.mixins.NDArrayOperatorsMixin.__rrshift__ static private
Definition at line 167 of file mixins.py.
__rshift__
numpy.lib.mixins.NDArrayOperatorsMixin.__rshift__ static private
Definition at line 167 of file mixins.py.
__rsub__
numpy.lib.mixins.NDArrayOperatorsMixin.__rsub__ static private
Definition at line 150 of file mixins.py.
__rtruediv__
numpy.lib.mixins.NDArrayOperatorsMixin.__rtruediv__ static private
Definition at line 155 of file mixins.py.
__rxor__
numpy.lib.mixins.NDArrayOperatorsMixin.__rxor__ static private
Definition at line 170 of file mixins.py.
__slots__
tuple numpy.lib.mixins.NDArrayOperatorsMixin.__slots__ = () static private
Definition at line 136 of file mixins.py.
__sub__
numpy.lib.mixins.NDArrayOperatorsMixin.__sub__ static private
Definition at line 150 of file mixins.py.
__truediv__
numpy.lib.mixins.NDArrayOperatorsMixin.__truediv__ static private
Definition at line 155 of file mixins.py.
__xor__
numpy.lib.mixins.NDArrayOperatorsMixin.__xor__ static private
Definition at line 170 of file mixins.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/lib/mixins.py