Code Cloning Analysis: axisartist.axis_artist.LabelBase Class Reference
axisartist.axis_artist.LabelBase Class Reference
Public Member Functions
__init__ (self, *args, **kwargs)
draw (self, renderer)
get_window_extent (self, renderer=None)
Public Attributes
list locs_angles_labels = []
Protected Member Functions
_text_ref_angle (self)
_offset_ref_angle (self)
Protected Attributes
int _ref_angle = 0
int _offset_radius = 0.
bool _text_follow_ref_angle = True
Static Protected Attributes
dict _get_opposite_direction
Detailed Description
A base class for `.AxisLabel` and `.TickLabels`. The position and
angle of the text are calculated by the offset_ref_angle,
text_ref_angle, and offset_radius attributes.
Definition at line 203 of file axis_artist.py.
Constructor & Destructor Documentation
__init__()
axisartist.axis_artist.LabelBase.__init__ (self, * args, ** kwargs)
Definition at line 210 of file axis_artist.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_offset_ref_angle()
axisartist.axis_artist.LabelBase._offset_ref_angle (self) protected
Definition at line 228 of file axis_artist.py.
_text_ref_angle()
axisartist.axis_artist.LabelBase._text_ref_angle (self) protected
Definition at line 221 of file axis_artist.py.
draw()
axisartist.axis_artist.LabelBase.draw (self, renderer)
Definition at line 236 of file axis_artist.py.
get_window_extent()
axisartist.axis_artist.LabelBase.get_window_extent (self, renderer = None)
Definition at line 254 of file axis_artist.py.
Member Data Documentation
_get_opposite_direction
dict axisartist.axis_artist.LabelBase._get_opposite_direction static protected
Initial value:
=  {"left": "right",
                               "right": "left",
                               "top": "bottom",
                               "bottom": "top"}.__getitem__
Definition at line 231 of file axis_artist.py.
Referenced by axisartist.axis_artist.TickLabels.set_axis_direction().
_offset_radius
int axisartist.axis_artist.LabelBase._offset_radius = 0. protected
Definition at line 213 of file axis_artist.py.
Referenced by axisartist.axis_artist.TickLabels._get_ticklabels_offsets(), and axisartist.axis_artist.AxisLabel.set_axis_direction().
_ref_angle
int axisartist.axis_artist.LabelBase._ref_angle = 0 protected
Definition at line 212 of file axis_artist.py.
Referenced by axisartist.axis_artist.TickLabels._get_ticklabels_offsets().
_text_follow_ref_angle
bool axisartist.axis_artist.LabelBase._text_follow_ref_angle = True protected
Definition at line 218 of file axis_artist.py.
locs_angles_labels
list axisartist.axis_artist.LabelBase.locs_angles_labels = []
Definition at line 211 of file axis_artist.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/mpl_toolkits/axisartist/axis_artist.py