Code Cloning Analysis: sklearn.cluster._bicluster Namespace Reference
sklearn.cluster._bicluster Namespace Reference
Classes
class BaseSpectral
class SpectralBiclustering
class SpectralCoclustering
Functions
_scale_normalize (X)
_bistochastic_normalize (X, max_iter=1000, tol=1e-5)
_log_normalize (X)
Variables
list __all__ = ["SpectralBiclustering", "SpectralCoclustering"]
Detailed Description
Spectral biclustering algorithms.
Function Documentation
_bistochastic_normalize()
sklearn.cluster._bicluster._bistochastic_normalize (X, max_iter = 1000, tol = 1e-5) protected
Normalize rows and columns of ``X`` simultaneously so that all
rows sum to one constant and all columns sum to a different
constant.
Definition at line 45 of file _bicluster.py.
References _scale_normalize().
Referenced by sklearn.cluster._bicluster.SpectralBiclustering._check_parameters().
_log_normalize()
sklearn.cluster._bicluster._log_normalize (X) protected
Normalize ``X`` according to Kluger's log-interactions scheme.
Definition at line 66 of file _bicluster.py.
Referenced by sklearn.cluster._bicluster.SpectralBiclustering._check_parameters().
_scale_normalize()
sklearn.cluster._bicluster._scale_normalize (X) protected
Normalize ``X`` by scaling rows and columns independently.
Returns the normalized matrix and the row and column scaling
factors.
Definition at line 24 of file _bicluster.py.
Referenced by _bistochastic_normalize(), sklearn.cluster._bicluster.SpectralBiclustering._check_parameters(), and sklearn.cluster._bicluster.SpectralCoclustering._check_parameters().
Variable Documentation
__all__
list sklearn.cluster._bicluster.__all__ = ["SpectralBiclustering", "SpectralCoclustering"] private
Definition at line 21 of file _bicluster.py.