Code Cloning Analysis: matplotlib.tests.test_subplots Namespace Reference
matplotlib.tests.test_subplots Namespace Reference
Functions
check_shared (axs, x_shared, y_shared)
check_ticklabel_visible (axs, x_visible, y_visible)
check_tick1_visible (axs, x_visible, y_visible)
test_shared ()
test_label_outer (remove_ticks)
test_label_outer_span ()
test_label_outer_non_gridspec ()
test_shared_and_moved ()
test_exceptions ()
test_subplots_offsettext ()
test_subplots_hide_ticklabels (top, bottom, left, right)
test_subplots_hide_axislabels (xlabel_position, ylabel_position)
test_get_gridspec ()
test_dont_mutate_kwargs ()
test_width_and_height_ratios (fig_test, fig_ref, height_ratios, width_ratios)
test_width_and_height_ratios_mosaic (fig_test, fig_ref, height_ratios, width_ratios)
test_ratio_overlapping_kws (method, args)
test_old_subplot_compat ()
Function Documentation
check_shared()
matplotlib.tests.test_subplots.check_shared (axs, x_shared, y_shared)
x_shared and y_shared are n x n boolean matrices; entry (i, j) indicates
whether the x (or y) axes of subplots i and j should be shared.
Definition at line 12 of file test_subplots.py.
Referenced by check_tick1_visible().
check_tick1_visible()
matplotlib.tests.test_subplots.check_tick1_visible (axs, x_visible, y_visible)
Check that the x and y tick visibility is as specified.
Note: This only checks the tick1line, i.e. bottom / left ticks.
Definition at line 45 of file test_subplots.py.
References check_shared(), check_tick1_visible(), and check_ticklabel_visible().
Referenced by check_tick1_visible().
check_ticklabel_visible()
matplotlib.tests.test_subplots.check_ticklabel_visible (axs, x_visible, y_visible)
Check that the x and y ticklabel visibility is as specified.
Definition at line 28 of file test_subplots.py.
Referenced by check_tick1_visible().
test_dont_mutate_kwargs()
matplotlib.tests.test_subplots.test_dont_mutate_kwargs ()
Definition at line 234 of file test_subplots.py.
test_exceptions()
matplotlib.tests.test_subplots.test_exceptions ()
Definition at line 169 of file test_subplots.py.
test_get_gridspec()
matplotlib.tests.test_subplots.test_get_gridspec ()
Definition at line 228 of file test_subplots.py.
test_label_outer()
matplotlib.tests.test_subplots.test_label_outer (remove_ticks)
Definition at line 114 of file test_subplots.py.
test_label_outer_non_gridspec()
matplotlib.tests.test_subplots.test_label_outer_non_gridspec ()
Definition at line 149 of file test_subplots.py.
test_label_outer_span()
matplotlib.tests.test_subplots.test_label_outer_span ()
Definition at line 129 of file test_subplots.py.
test_old_subplot_compat()
matplotlib.tests.test_subplots.test_old_subplot_compat ()
Definition at line 282 of file test_subplots.py.
test_ratio_overlapping_kws()
matplotlib.tests.test_subplots.test_ratio_overlapping_kws (method, args)
Definition at line 273 of file test_subplots.py.
test_shared()
matplotlib.tests.test_subplots.test_shared ()
Definition at line 59 of file test_subplots.py.
test_shared_and_moved()
matplotlib.tests.test_subplots.test_shared_and_moved ()
Definition at line 155 of file test_subplots.py.
test_subplots_hide_axislabels()
matplotlib.tests.test_subplots.test_subplots_hide_axislabels (xlabel_position, ylabel_position)
Definition at line 213 of file test_subplots.py.
test_subplots_hide_ticklabels()
matplotlib.tests.test_subplots.test_subplots_hide_ticklabels (top, bottom, left, right)
Definition at line 193 of file test_subplots.py.
test_subplots_offsettext()
matplotlib.tests.test_subplots.test_subplots_offsettext ()
Definition at line 179 of file test_subplots.py.
test_width_and_height_ratios()
matplotlib.tests.test_subplots.test_width_and_height_ratios (fig_test, fig_ref, height_ratios, width_ratios)
Definition at line 246 of file test_subplots.py.
test_width_and_height_ratios_mosaic()
matplotlib.tests.test_subplots.test_width_and_height_ratios_mosaic (fig_test, fig_ref, height_ratios, width_ratios)
Definition at line 258 of file test_subplots.py.