Code Cloning Analysis: pandas.core.computation.parsing Namespace Reference
pandas.core.computation.parsing Namespace Reference
Functions
str create_valid_python_identifier (str name)
tuple[int, str] clean_backtick_quoted_toks (tuple[int, str] tok)
Hashable clean_column_name (Hashable name)
tuple[int, str] tokenize_backtick_quoted_string (Iterator[tokenize.TokenInfo] token_generator, str source, int string_start)
Iterator[tuple[int, str]] tokenize_string (str source)
Variables
int BACKTICK_QUOTED_STRING = 100
Detailed Description
:func:`~pandas.eval` source string parsing functions
Function Documentation
clean_backtick_quoted_toks()
tuple[int, str] pandas.core.computation.parsing.clean_backtick_quoted_toks (tuple[int, str] tok)
Clean up a column name if surrounded by backticks.
Backtick quoted string are indicated by a certain tokval value. If a string
is a backtick quoted token it will processed by
:func:`_create_valid_python_identifier` so that the parser can find this
string when the query is executed.
In this case the tok will get the NAME tokval.
Parameters
----------
tok : tuple of int, str
    ints correspond to the all caps constants in the tokenize module
Returns
-------
tok : Tuple[int, str]
    Either the input or token or the replacement values
Definition at line 73 of file parsing.py.
References create_valid_python_identifier().
clean_column_name()
Hashable pandas.core.computation.parsing.clean_column_name (Hashable name)
Function to emulate the cleaning of a backtick quoted name.
The purpose for this function is to see what happens to the name of
identifier if it goes to the process of being parsed a Python code
inside a backtick quoted string and than being cleaned
(removed of any special characters).
Parameters
----------
name : hashable
    Name to be cleaned.
Returns
-------
name : hashable
    Returns the name after tokenizing and cleaning.
Notes
-----
    For some cases, a name cannot be converted to a valid Python identifier.
    In that case :func:`tokenize_string` raises a SyntaxError.
    In that case, we just return the name unmodified.
    If this name was used in the query string (this makes the query call impossible)
    an error will be raised by :func:`tokenize_backtick_quoted_string` instead,
    which is not caught and propagates to the user level.
Definition at line 99 of file parsing.py.
References create_valid_python_identifier(), and tokenize_string().
create_valid_python_identifier()
str pandas.core.computation.parsing.create_valid_python_identifier (str name)
Create valid Python identifiers from any string.
Check if name contains any special characters. If it contains any
special characters, the special characters will be replaced by
a special string and a prefix is added.
Raises
------
SyntaxError
    If the returned name is not a Python valid identifier, raise an exception.
    This can happen if there is a hashtag in the name, as the tokenizer will
    than terminate and not find the backtick.
    But also for characters that fall out of the range of (U+0001..U+007F).
Definition at line 22 of file parsing.py.
Referenced by clean_backtick_quoted_toks(), and clean_column_name().
tokenize_backtick_quoted_string()
tuple[int, str] pandas.core.computation.parsing.tokenize_backtick_quoted_string (Iterator[tokenize.TokenInfo] token_generator, str source, int string_start)
Creates a token from a backtick quoted string.
Moves the token_generator forwards till right after the next backtick.
Parameters
----------
token_generator : Iterator[tokenize.TokenInfo]
    The generator that yields the tokens of the source string (Tuple[int, str]).
    The generator is at the first token after the backtick (`)
source : str
    The Python source code string.
string_start : int
    This is the start of backtick quoted string inside the source string.
Returns
-------
tok: Tuple[int, str]
    The token that represents the backtick quoted string.
    The integer is equal to BACKTICK_QUOTED_STRING (100).
Definition at line 136 of file parsing.py.
Referenced by tokenize_string().
tokenize_string()
Iterator[tuple[int, str]] pandas.core.computation.parsing.tokenize_string (str source)
Tokenize a Python source code string.
Parameters
----------
source : str
    The Python source code string.
Returns
-------
tok_generator : Iterator[Tuple[int, str]]
    An iterator yielding all tokens with only toknum and tokval (Tuple[ing, str]).
Definition at line 170 of file parsing.py.
References tokenize_backtick_quoted_string().
Referenced by clean_column_name().
Variable Documentation
BACKTICK_QUOTED_STRING
int pandas.core.computation.parsing.BACKTICK_QUOTED_STRING = 100
Definition at line 19 of file parsing.py.