Code Cloning Analysis: scipy.linalg.tests.test_basic.TestDet Class Reference
scipy.linalg.tests.test_basic.TestDet Class Reference
Public Member Functions
setup_method (self)
test_1x1_all_singleton_dims (self)
test_1by1_stacked_input_output (self)
test_simple_det_shapes_real_complex (self, shape)
test_for_known_det_values (self)
test_sample_compatible_dtype_input (self, typ)
test_incompatible_dtype_input (self)
test_empty_edge_cases (self)
test_overwrite_a (self)
test_readonly_array (self)
test_simple_check_finite (self)
Public Attributes
rng = np.random.default_rng(1680305949878959)
Detailed Description
Definition at line 931 of file test_basic.py.
Member Function Documentation
setup_method()
scipy.linalg.tests.test_basic.TestDet.setup_method (self)
Definition at line 932 of file test_basic.py.
test_1by1_stacked_input_output()
scipy.linalg.tests.test_basic.TestDet.test_1by1_stacked_input_output (self)
Definition at line 952 of file test_basic.py.
test_1x1_all_singleton_dims()
scipy.linalg.tests.test_basic.TestDet.test_1x1_all_singleton_dims (self)
Definition at line 935 of file test_basic.py.
test_empty_edge_cases()
scipy.linalg.tests.test_basic.TestDet.test_empty_edge_cases (self)
Definition at line 1034 of file test_basic.py.
test_for_known_det_values()
scipy.linalg.tests.test_basic.TestDet.test_for_known_det_values (self)
Definition at line 976 of file test_basic.py.
test_incompatible_dtype_input()
scipy.linalg.tests.test_basic.TestDet.test_incompatible_dtype_input (self)
Definition at line 1020 of file test_basic.py.
test_overwrite_a()
scipy.linalg.tests.test_basic.TestDet.test_overwrite_a (self)
Definition at line 1047 of file test_basic.py.
test_readonly_array()
scipy.linalg.tests.test_basic.TestDet.test_readonly_array (self)
Definition at line 1058 of file test_basic.py.
test_sample_compatible_dtype_input()
scipy.linalg.tests.test_basic.TestDet.test_sample_compatible_dtype_input (self, typ)
Definition at line 1015 of file test_basic.py.
test_simple_check_finite()
scipy.linalg.tests.test_basic.TestDet.test_simple_check_finite (self)
Definition at line 1064 of file test_basic.py.
test_simple_det_shapes_real_complex()
scipy.linalg.tests.test_basic.TestDet.test_simple_det_shapes_real_complex (self, shape)
Definition at line 966 of file test_basic.py.
Member Data Documentation
rng
scipy.linalg.tests.test_basic.TestDet.rng = np.random.default_rng(1680305949878959)
Definition at line 933 of file test_basic.py.
Referenced by scipy.stats._qmc.PoissonDisk._hypersphere_surface_sample(), scipy.stats._qmc.PoissonDisk._hypersphere_volume_sample(), scipy.stats._qmc.Halton._initialize_permutations(), scipy.stats._qmc.PoissonDisk._random(), scipy.stats._qmc.LatinHypercube._random_lhs(), scipy.stats._qmc.LatinHypercube._random_oa_lhs(), scipy.stats._qmc.Sobol._scramble(), sklearn.gaussian_process._gpc._BinaryGaussianProcessClassifierLaplace.fit(), and scipy.stats._qmc.QMCEngine.reset().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/linalg/tests/test_basic.py