Code Cloning Analysis: contourpy.array Namespace Reference
contourpy.array Namespace Reference
Functions
cpy.CodeArray codes_from_offsets (cpy.OffsetArray offsets)
cpy.CodeArray codes_from_offsets_and_points (cpy.OffsetArray offsets, cpy.PointArray points)
cpy.CodeArray codes_from_points (cpy.PointArray points)
cpy.CodeArray concat_codes (list[cpy.CodeArray] list_of_codes)
cpy.CodeArray|None concat_codes_or_none (list[cpy.CodeArray|None] list_of_codes_or_none)
cpy.OffsetArray concat_offsets (list[cpy.OffsetArray] list_of_offsets)
cpy.OffsetArray|None concat_offsets_or_none (list[cpy.OffsetArray|None] list_of_offsets_or_none)
cpy.PointArray concat_points (list[cpy.PointArray] list_of_points)
cpy.PointArray|None concat_points_or_none (list[cpy.PointArray|None] list_of_points_or_none)
cpy.PointArray|None concat_points_or_none_with_nan (list[cpy.PointArray|None] list_of_points_or_none)
cpy.PointArray concat_points_with_nan (list[cpy.PointArray] list_of_points)
cpy.PointArray insert_nan_at_offsets (cpy.PointArray points, cpy.OffsetArray offsets)
cpy.OffsetArray offsets_from_codes (cpy.CodeArray codes)
cpy.OffsetArray offsets_from_lengths (list[cpy.PointArray] list_of_points)
cpy.OffsetArray outer_offsets_from_list_of_codes (list[cpy.CodeArray] list_of_codes)
cpy.OffsetArray outer_offsets_from_list_of_offsets (list[cpy.OffsetArray] list_of_offsets)
tuple[cpy.PointArray, cpy.OffsetArray] remove_nan (cpy.PointArray points)
list[cpy.CodeArray] split_codes_by_offsets (cpy.CodeArray codes, cpy.OffsetArray offsets)
list[cpy.PointArray] split_points_by_offsets (cpy.PointArray points, cpy.OffsetArray offsets)
list[cpy.PointArray] split_points_at_nan (cpy.PointArray points)
Function Documentation
codes_from_offsets()
cpy.CodeArray contourpy.array.codes_from_offsets (cpy.OffsetArray offsets)
Determine codes from offsets, assuming they all correspond to closed polygons.
Definition at line 15 of file array.py.
codes_from_offsets_and_points()
cpy.CodeArray contourpy.array.codes_from_offsets_and_points (cpy.OffsetArray offsets, cpy.PointArray points)
Determine codes from offsets and points, using the equality of the start and end points of
each line to determine if lines are closed or not.
Definition at line 27 of file array.py.
codes_from_points()
cpy.CodeArray contourpy.array.codes_from_points (cpy.PointArray points)
Determine codes for a single line, using the equality of the start and end points to
determine if the line is closed or not.
Definition at line 47 of file array.py.
concat_codes()
cpy.CodeArray contourpy.array.concat_codes (list[cpy.CodeArray] list_of_codes)
Concatenate a list of codes arrays into a single code array.
Definition at line 61 of file array.py.
Referenced by concat_codes_or_none().
concat_codes_or_none()
cpy.CodeArray | None contourpy.array.concat_codes_or_none (list[cpy.CodeArray | None] list_of_codes_or_none)
Concatenate a list of codes arrays or None into a single code array or None.
Definition at line 70 of file array.py.
References concat_codes().
concat_offsets()
cpy.OffsetArray contourpy.array.concat_offsets (list[cpy.OffsetArray] list_of_offsets)
Concatenate a list of offsets arrays into a single offset array.
Definition at line 80 of file array.py.
Referenced by concat_offsets_or_none().
concat_offsets_or_none()
cpy.OffsetArray | None contourpy.array.concat_offsets_or_none (list[cpy.OffsetArray | None] list_of_offsets_or_none)
Concatenate a list of offsets arrays or None into a single offset array or None.
Definition at line 95 of file array.py.
References concat_offsets().
concat_points()
cpy.PointArray contourpy.array.concat_points (list[cpy.PointArray] list_of_points)
Concatenate a list of point arrays into a single point array.
Definition at line 107 of file array.py.
Referenced by concat_points_or_none(), and concat_points_with_nan().
concat_points_or_none()
cpy.PointArray | None contourpy.array.concat_points_or_none (list[cpy.PointArray | None] list_of_points_or_none)
Concatenate a list of point arrays or None into a single point array or None.
Definition at line 116 of file array.py.
References concat_points().
concat_points_or_none_with_nan()
cpy.PointArray | None contourpy.array.concat_points_or_none_with_nan (list[cpy.PointArray | None] list_of_points_or_none)
Concatenate a list of points or None into a single point array or None, with NaNs used to
separate each line.
Definition at line 128 of file array.py.
References concat_points_with_nan().
concat_points_with_nan()
cpy.PointArray contourpy.array.concat_points_with_nan (list[cpy.PointArray] list_of_points)
Concatenate a list of points into a single point array with NaNs used to separate each line.
Definition at line 141 of file array.py.
References concat_points().
Referenced by concat_points_or_none_with_nan().
insert_nan_at_offsets()
cpy.PointArray contourpy.array.insert_nan_at_offsets (cpy.PointArray points, cpy.OffsetArray offsets)
Insert NaNs into a point array at locations specified by an offset array.
Definition at line 156 of file array.py.
offsets_from_codes()
cpy.OffsetArray contourpy.array.offsets_from_codes (cpy.CodeArray codes)
Determine offsets from codes using locations of MOVETO codes.
Definition at line 170 of file array.py.
offsets_from_lengths()
cpy.OffsetArray contourpy.array.offsets_from_lengths (list[cpy.PointArray] list_of_points)
Determine offsets from lengths of point arrays.
Definition at line 178 of file array.py.
outer_offsets_from_list_of_codes()
cpy.OffsetArray contourpy.array.outer_offsets_from_list_of_codes (list[cpy.CodeArray] list_of_codes)
Determine outer offsets from codes using locations of MOVETO codes.
Definition at line 187 of file array.py.
outer_offsets_from_list_of_offsets()
cpy.OffsetArray contourpy.array.outer_offsets_from_list_of_offsets (list[cpy.OffsetArray] list_of_offsets)
Determine outer offsets from a list of offsets.
Definition at line 197 of file array.py.
remove_nan()
tuple[cpy.PointArray, cpy.OffsetArray] contourpy.array.remove_nan (cpy.PointArray points)
Remove NaN from a points array, also return the offsets corresponding to the NaN removed.
Definition at line 206 of file array.py.
split_codes_by_offsets()
list[cpy.CodeArray] contourpy.array.split_codes_by_offsets (cpy.CodeArray codes, cpy.OffsetArray offsets)
Split a code array at locations specified by an offset array into a list of code arrays.
Definition at line 224 of file array.py.
split_points_at_nan()
list[cpy.PointArray] contourpy.array.split_points_at_nan (cpy.PointArray points)
Split a points array at NaNs into a list of point arrays.
Definition at line 251 of file array.py.
split_points_by_offsets()
list[cpy.PointArray] contourpy.array.split_points_by_offsets (cpy.PointArray points, cpy.OffsetArray offsets)
Split a point array at locations specified by an offset array into a list of point arrays.
Definition at line 236 of file array.py.