Code Cloning Analysis: pandas.io.formats.excel.CssExcelCell Class Reference
pandas.io.formats.excel.CssExcelCell Class Reference
Public Member Functions
None __init__ (self, int row, int col, val, dict|None style, dict[tuple[int, int], list[tuple[str, Any]]]|None css_styles, int css_row, int css_col, Callable|None css_converter, **kwargs)
Public Member Functions inherited from pandas.io.formats.excel.ExcelCell
None __init__ (self, int row, int col, val, style=None, int|None mergestart=None, int|None mergeend=None)
Additional Inherited Members
Public Attributes inherited from pandas.io.formats.excel.ExcelCell
row = row
col = col
val = val
style = style
mergestart = mergestart
mergeend = mergeend
Detailed Description
Definition at line 84 of file excel.py.
Constructor & Destructor Documentation
__init__()
None pandas.io.formats.excel.CssExcelCell.__init__ (self, int row, int col, val, dict | None style, dict[tuple[int, int], list[tuple[str, Any]]] | None css_styles, int css_row, int css_col, Callable | None css_converter, ** kwargs)
Definition at line 85 of file excel.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/io/formats/excel.py