Code Cloning Analysis: pandas.core.reshape.reshape Namespace Reference
pandas.core.reshape.reshape Namespace Reference
Classes
class _Unstacker
Functions
_unstack_multiple (Series|DataFrame data, clocs, fill_value=None, bool sort=True)
unstack (Series|DataFrame obj, level, fill_value=None, bool sort=True)
DataFrame _unstack_frame (DataFrame obj, level, fill_value=None, bool sort=True)
DataFrame _unstack_extension_series (Series series, level, fill_value, bool sort)
stack (DataFrame frame, level=-1, bool dropna=True, bool sort=True)
stack_multiple (DataFrame frame, level, bool dropna=True, bool sort=True)
MultiIndex _stack_multi_column_index (MultiIndex columns)
DataFrame _stack_multi_columns (DataFrame frame, int level_num=-1, bool dropna=True, bool sort=True)
ExtensionArray _reorder_for_extension_array_stack (ExtensionArray arr, int n_rows, int n_columns)
Series|DataFrame stack_v3 (DataFrame frame, list[int] level)
Function Documentation
_reorder_for_extension_array_stack()
ExtensionArray pandas.core.reshape.reshape._reorder_for_extension_array_stack (ExtensionArray arr, int n_rows, int n_columns) protected
Re-orders the values when stacking multiple extension-arrays.
The indirect stacking method used for EAs requires a followup
take to get the order correct.
Parameters
----------
arr : ExtensionArray
n_rows, n_columns : int
    The number of rows and columns in the original DataFrame.
Returns
-------
taken : ExtensionArray
    The original `arr` with elements re-ordered appropriately
Examples
--------
>>> arr = np.array(['a', 'b', 'c', 'd', 'e', 'f'])
>>> _reorder_for_extension_array_stack(arr, 2, 3)
array(['a', 'c', 'e', 'b', 'd', 'f'], dtype='<U1')
>>> _reorder_for_extension_array_stack(arr, 3, 2)
array(['a', 'd', 'b', 'e', 'c', 'f'], dtype='<U1')
Definition at line 848 of file reshape.py.
Referenced by stack().
_stack_multi_column_index()
MultiIndex pandas.core.reshape.reshape._stack_multi_column_index (MultiIndex columns) protected
Creates a MultiIndex from the first N-1 levels of this MultiIndex.
Definition at line 689 of file reshape.py.
References _stack_multi_column_index().
Referenced by _stack_multi_column_index().
_stack_multi_columns()
DataFrame pandas.core.reshape.reshape._stack_multi_columns (DataFrame frame, int level_num = -1, bool dropna = True, bool sort = True) protected
Definition at line 716 of file reshape.py.
_unstack_extension_series()
DataFrame pandas.core.reshape.reshape._unstack_extension_series (Series series, level, fill_value, bool sort) protected
Unstack an ExtensionArray-backed Series.
The ExtensionDtype is preserved.
Parameters
----------
series : Series
    A Series with an ExtensionArray for values
level : Any
    The level name or number.
fill_value : Any
    The user-level (not physical storage) fill value to use for
    missing values introduced by the reshape. Passed to
    ``series.values.take``.
sort : bool
    Whether to sort the resulting MuliIndex levels
Returns
-------
DataFrame
    Each column of the DataFrame will have the same dtype as
    the input Series.
Definition at line 542 of file reshape.py.
_unstack_frame()
DataFrame pandas.core.reshape.reshape._unstack_frame (DataFrame obj, level, fill_value = None, bool sort = True) protected
Definition at line 525 of file reshape.py.
_unstack_multiple()
pandas.core.reshape.reshape._unstack_multiple (Series | DataFrame data, clocs, fill_value = None, bool sort = True) protected
Definition at line 398 of file reshape.py.
stack()
pandas.core.reshape.reshape.stack (DataFrame frame, level = -1, bool dropna = True, bool sort = True)
Convert DataFrame to Series with multi-level Index. Columns become the
second level of the resulting hierarchical index
Returns
-------
stacked : Series or DataFrame
Definition at line 579 of file reshape.py.
References _reorder_for_extension_array_stack(), and stack().
Referenced by stack().
stack_multiple()
pandas.core.reshape.reshape.stack_multiple (DataFrame frame, level, bool dropna = True, bool sort = True)
Definition at line 656 of file reshape.py.
stack_v3()
Series | DataFrame pandas.core.reshape.reshape.stack_v3 (DataFrame frame, list[int] level)
Definition at line 885 of file reshape.py.
unstack()
pandas.core.reshape.reshape.unstack (Series | DataFrame obj, level, fill_value = None, bool sort = True)
Definition at line 489 of file reshape.py.