Code Cloning Analysis: pip._vendor.chardet.utf8prober.UTF8Prober Class Reference
pip._vendor.chardet.utf8prober.UTF8Prober Class Reference
Public Member Functions
None __init__ (self)
None reset (self)
str charset_name (self)
str language (self)
ProbingState feed (self, Union[bytes, bytearray] byte_str)
float get_confidence (self)
Public Member Functions inherited from pip._vendor.chardet.charsetprober.CharSetProber
None __init__ (self, LanguageFilter lang_filter=LanguageFilter.NONE)
ProbingState state (self)
Public Attributes
coding_sm = CodingStateMachine(UTF8_SM_MODEL)
Public Attributes inherited from pip._vendor.chardet.charsetprober.CharSetProber
bool active = True
lang_filter = lang_filter
logger = logging.getLogger(__name__)
Static Public Attributes
float ONE_CHAR_PROB = 0.5
Static Public Attributes inherited from pip._vendor.chardet.charsetprober.CharSetProber
float SHORTCUT_THRESHOLD = 0.95
Protected Attributes
int _num_mb_chars = 0
Protected Attributes inherited from pip._vendor.chardet.charsetprober.CharSetProber
_state = ProbingState.DETECTING
Additional Inherited Members
Static Public Member Functions inherited from pip._vendor.chardet.charsetprober.CharSetProber
bytes filter_high_byte_only (Union[bytes, bytearray] buf)
bytearray filter_international_words (Union[bytes, bytearray] buf)
bytes remove_xml_tags (Union[bytes, bytearray] buf)
Detailed Description
Definition at line 36 of file utf8prober.py.
Constructor & Destructor Documentation
__init__()
None pip._vendor.chardet.utf8prober.UTF8Prober.__init__ (self)
Definition at line 39 of file utf8prober.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
charset_name()
str pip._vendor.chardet.utf8prober.UTF8Prober.charset_name (self)
Reimplemented from pip._vendor.chardet.charsetprober.CharSetProber.
Definition at line 51 of file utf8prober.py.
feed()
ProbingState pip._vendor.chardet.utf8prober.UTF8Prober.feed (self, Union[bytes, bytearray] byte_str)
Reimplemented from pip._vendor.chardet.charsetprober.CharSetProber.
Definition at line 58 of file utf8prober.py.
get_confidence()
float pip._vendor.chardet.utf8prober.UTF8Prober.get_confidence (self)
Reimplemented from pip._vendor.chardet.charsetprober.CharSetProber.
Definition at line 77 of file utf8prober.py.
language()
str pip._vendor.chardet.utf8prober.UTF8Prober.language (self)
Reimplemented from pip._vendor.chardet.charsetprober.CharSetProber.
Definition at line 55 of file utf8prober.py.
reset()
None pip._vendor.chardet.utf8prober.UTF8Prober.reset (self)
Reimplemented from pip._vendor.chardet.charsetprober.CharSetProber.
Definition at line 45 of file utf8prober.py.
Referenced by scipy._lib._docscrape.Reader.__init__().
Member Data Documentation
_num_mb_chars
int pip._vendor.chardet.utf8prober.UTF8Prober._num_mb_chars = 0 protected
Definition at line 42 of file utf8prober.py.
coding_sm
pip._vendor.chardet.utf8prober.UTF8Prober.coding_sm = CodingStateMachine(UTF8_SM_MODEL)
Definition at line 41 of file utf8prober.py.
ONE_CHAR_PROB
float pip._vendor.chardet.utf8prober.UTF8Prober.ONE_CHAR_PROB = 0.5 static
Definition at line 37 of file utf8prober.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pip/_vendor/chardet/utf8prober.py