Code Cloning Analysis: scipy.linalg.tests.test_matmul_toeplitz.TestMatmulToeplitz Class Reference
scipy.linalg.tests.test_matmul_toeplitz.TestMatmulToeplitz Class Reference
Public Member Functions
setup_method (self)
test_real (self)
test_complex (self)
test_exceptions (self)
do (self, x, c, r=None, check_finite=False, workers=None)
Public Attributes
rng = np.random.RandomState(42)
float tolerance = 1.5e-13
Detailed Description
Definition at line 11 of file test_matmul_toeplitz.py.
Member Function Documentation
do()
scipy.linalg.tests.test_matmul_toeplitz.TestMatmulToeplitz.do (self, x, c, r = None, check_finite = False, workers = None)
Definition at line 118 of file test_matmul_toeplitz.py.
setup_method()
scipy.linalg.tests.test_matmul_toeplitz.TestMatmulToeplitz.setup_method (self)
Definition at line 13 of file test_matmul_toeplitz.py.
test_complex()
scipy.linalg.tests.test_matmul_toeplitz.TestMatmulToeplitz.test_complex (self)
Definition at line 82 of file test_matmul_toeplitz.py.
test_exceptions()
scipy.linalg.tests.test_matmul_toeplitz.TestMatmulToeplitz.test_exceptions (self)
Definition at line 97 of file test_matmul_toeplitz.py.
test_real()
scipy.linalg.tests.test_matmul_toeplitz.TestMatmulToeplitz.test_real (self)
Definition at line 17 of file test_matmul_toeplitz.py.
Member Data Documentation
rng
scipy.linalg.tests.test_matmul_toeplitz.TestMatmulToeplitz.rng = np.random.RandomState(42)
Definition at line 14 of file test_matmul_toeplitz.py.
Referenced by scipy.stats._qmc.PoissonDisk._hypersphere_surface_sample(), scipy.stats._qmc.PoissonDisk._hypersphere_volume_sample(), scipy.stats._qmc.Halton._initialize_permutations(), scipy.stats._qmc.PoissonDisk._random(), scipy.stats._qmc.LatinHypercube._random_lhs(), scipy.stats._qmc.LatinHypercube._random_oa_lhs(), scipy.stats._qmc.Sobol._scramble(), sklearn.gaussian_process._gpc._BinaryGaussianProcessClassifierLaplace.fit(), and scipy.stats._qmc.QMCEngine.reset().
tolerance
float scipy.linalg.tests.test_matmul_toeplitz.TestMatmulToeplitz.tolerance = 1.5e-13
Definition at line 15 of file test_matmul_toeplitz.py.
Referenced by scipy.optimize._trustregion_constr.tr_interior_point.BarrierSubproblem.stop_criteria().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/linalg/tests/test_matmul_toeplitz.py