Code Cloning Analysis: pandas.core.computation.expr Namespace Reference
pandas.core.computation.expr Namespace Reference
Classes
class BaseExprVisitor
class Expr
class PandasExprVisitor
class PythonExprVisitor
Functions
tuple[int, str] _rewrite_assign (tuple[int, str] tok)
tuple[int, str] _replace_booleans (tuple[int, str] tok)
tuple[int, str] _replace_locals (tuple[int, str] tok)
_compose2 (f, g)
_compose (*funcs)
str _preparse (str source, f=_compose(_replace_locals, _replace_booleans, _rewrite_assign, clean_backtick_quoted_toks))
_is_type (t)
_filter_nodes (superclass, all_nodes=_all_nodes)
Callable[..., None] _node_not_implemented (str node_name)
Callable[[type[_T]], type[_T]] disallow (set[str] nodes)
_op_maker (op_class, op_symbol)
add_ops (op_classes)
Variables
_is_list = _is_type(list)
_is_str = _is_type(str)
_all_nodes
_all_node_names = frozenset(x.__name__ for x in _all_nodes)
_mod_nodes = _filter_nodes(ast.mod)
_stmt_nodes = _filter_nodes(ast.stmt)
_expr_nodes = _filter_nodes(ast.expr)
_expr_context_nodes = _filter_nodes(ast.expr_context)
_boolop_nodes = _filter_nodes(ast.boolop)
_operator_nodes = _filter_nodes(ast.operator)
_unary_op_nodes = _filter_nodes(ast.unaryop)
_cmp_op_nodes = _filter_nodes(ast.cmpop)
_comprehension_nodes = _filter_nodes(ast.comprehension)
_handler_nodes = _filter_nodes(ast.excepthandler)
_arguments_nodes = _filter_nodes(ast.arguments)
_keyword_nodes = _filter_nodes(ast.keyword)
_alias_nodes = _filter_nodes(ast.alias)
_hacked_nodes = frozenset(["Assign", "Module", "Expr"])
_unsupported_expr_nodes
tuple _unsupported_nodes
tuple _base_supported_nodes = (_all_node_names - _unsupported_nodes) | _hacked_nodes
tuple intersection = _unsupported_nodes & _base_supported_nodes
str _msg = f"cannot both support and not support {intersection}"
_T = TypeVar("_T")
dict _op_classes = {"binary": BinOp, "unary": UnaryOp}
_python_not_supported = frozenset(["Dict", "BoolOp", "In", "NotIn"])
_numexpr_supported_calls = frozenset(REDUCTIONS + MATHOPS)
dict PARSERS = {"python": PythonExprVisitor, "pandas": PandasExprVisitor}
tuple unsupported_nodes = ()
Detailed Description
:func:`~pandas.eval` parsers.
Function Documentation
_compose()
pandas.core.computation.expr._compose (* funcs) protected
Compose 2 or more callables.
Definition at line 128 of file expr.py.
Referenced by _preparse().
_compose2()
pandas.core.computation.expr._compose2 (f, g) protected
Compose 2 callables.
Definition at line 121 of file expr.py.
_filter_nodes()
pandas.core.computation.expr._filter_nodes (superclass, all_nodes = _all_nodes) protected
Filter out AST nodes that are subclasses of ``superclass``.
Definition at line 189 of file expr.py.
References _filter_nodes().
Referenced by _filter_nodes().
_is_type()
pandas.core.computation.expr._is_type (t) protected
Factory for a type checking function of type ``t`` or tuple of types.
Definition at line 170 of file expr.py.
References _is_type().
Referenced by _is_type().
_node_not_implemented()
Callable[..., None] pandas.core.computation.expr._node_not_implemented (str node_name) protected
Return a function that raises a NotImplementedError with a passed node name.
Definition at line 254 of file expr.py.
Referenced by disallow().
_op_maker()
pandas.core.computation.expr._op_maker (op_class, op_symbol) protected
Return a function to create an op class with its symbol already passed.
Returns
-------
callable
Definition at line 295 of file expr.py.
Referenced by add_ops().
_preparse()
str pandas.core.computation.expr._preparse (str source, f = _compose(_replace_locals, _replace_booleans, _rewrite_assign, clean_backtick_quoted_toks)) protected
Compose a collection of tokenization functions.
Parameters
----------
source : str
    A Python source code string
f : callable
    This takes a tuple of (toknum, tokval) as its argument and returns a
    tuple with the same structure but possibly different elements. Defaults
    to the composition of ``_rewrite_assign``, ``_replace_booleans``, and
    ``_replace_locals``.
Returns
-------
str
    Valid Python source code
Notes
-----
The `f` parameter can be any callable that takes *and* returns input of the
form ``(toknum, tokval)``, where ``toknum`` is one of the constants from
the ``tokenize`` module and ``tokval`` is a string.
Definition at line 136 of file expr.py.
References _compose().
_replace_booleans()
tuple[int, str] pandas.core.computation.expr._replace_booleans (tuple[int, str] tok) protected
Replace ``&`` with ``and`` and ``|`` with ``or`` so that bitwise
precedence is changed to boolean precedence.
Parameters
----------
tok : tuple of int, str
    ints correspond to the all caps constants in the tokenize module
Returns
-------
tuple of int, str
    Either the input or token or the replacement values
Definition at line 70 of file expr.py.
_replace_locals()
tuple[int, str] pandas.core.computation.expr._replace_locals (tuple[int, str] tok) protected
Replace local variables with a syntactically valid name.
Parameters
----------
tok : tuple of int, str
    ints correspond to the all caps constants in the tokenize module
Returns
-------
tuple of int, str
    Either the input or token or the replacement values
Notes
-----
This is somewhat of a hack in that we rewrite a string such as ``'@a'`` as
``'__pd_eval_local_a'`` by telling the tokenizer that ``__pd_eval_local_``
is a ``tokenize.OP`` and to replace the ``'@'`` symbol with it.
Definition at line 95 of file expr.py.
_rewrite_assign()
tuple[int, str] pandas.core.computation.expr._rewrite_assign (tuple[int, str] tok) protected
Rewrite the assignment operator for PyTables expressions that use ``=``
as a substitute for ``==``.
Parameters
----------
tok : tuple of int, str
    ints correspond to the all caps constants in the tokenize module
Returns
-------
tuple of int, str
    Either the input or token or the replacement values
Definition at line 51 of file expr.py.
add_ops()
pandas.core.computation.expr.add_ops (op_classes)
Decorator to add default implementation of ops.
Definition at line 320 of file expr.py.
References _op_maker().
disallow()
Callable[[type[_T]], type[_T]] pandas.core.computation.expr.disallow (set[str] nodes)
Decorator to disallow certain nodes from parsing. Raises a
NotImplementedError instead.
Returns
-------
callable
Definition at line 271 of file expr.py.
References _node_not_implemented().
Variable Documentation
_alias_nodes
pandas.core.computation.expr._alias_nodes = _filter_nodes(ast.alias) protected
Definition at line 210 of file expr.py.
_all_node_names
pandas.core.computation.expr._all_node_names = frozenset(x.__name__ for x in _all_nodes) protected
Definition at line 197 of file expr.py.
_all_nodes
pandas.core.computation.expr._all_nodes protected
Initial value:
=  frozenset(
    node
    for node in (getattr(ast, name) for name in dir(ast))
    if isinstance(node, type) and issubclass(node, ast.AST)
)
Definition at line 182 of file expr.py.
_arguments_nodes
pandas.core.computation.expr._arguments_nodes = _filter_nodes(ast.arguments) protected
Definition at line 208 of file expr.py.
_base_supported_nodes
tuple pandas.core.computation.expr._base_supported_nodes = (_all_node_names - _unsupported_nodes) | _hacked_nodes protected
Definition at line 248 of file expr.py.
_boolop_nodes
pandas.core.computation.expr._boolop_nodes = _filter_nodes(ast.boolop) protected
Definition at line 202 of file expr.py.
_cmp_op_nodes
pandas.core.computation.expr._cmp_op_nodes = _filter_nodes(ast.cmpop) protected
Definition at line 205 of file expr.py.
_comprehension_nodes
pandas.core.computation.expr._comprehension_nodes = _filter_nodes(ast.comprehension) protected
Definition at line 206 of file expr.py.
_expr_context_nodes
pandas.core.computation.expr._expr_context_nodes = _filter_nodes(ast.expr_context) protected
Definition at line 201 of file expr.py.
_expr_nodes
pandas.core.computation.expr._expr_nodes = _filter_nodes(ast.expr) protected
Definition at line 200 of file expr.py.
_hacked_nodes
pandas.core.computation.expr._hacked_nodes = frozenset(["Assign", "Module", "Expr"]) protected
Definition at line 214 of file expr.py.
_handler_nodes
pandas.core.computation.expr._handler_nodes = _filter_nodes(ast.excepthandler) protected
Definition at line 207 of file expr.py.
_is_list
pandas.core.computation.expr._is_list = _is_type(list) protected
Definition at line 177 of file expr.py.
_is_str
pandas.core.computation.expr._is_str = _is_type(str) protected
Definition at line 178 of file expr.py.
_keyword_nodes
pandas.core.computation.expr._keyword_nodes = _filter_nodes(ast.keyword) protected
Definition at line 209 of file expr.py.
_mod_nodes
pandas.core.computation.expr._mod_nodes = _filter_nodes(ast.mod) protected
Definition at line 198 of file expr.py.
_msg
str pandas.core.computation.expr._msg = f"cannot both support and not support {intersection}" protected
Definition at line 250 of file expr.py.
_numexpr_supported_calls
pandas.core.computation.expr._numexpr_supported_calls = frozenset(REDUCTIONS + MATHOPS) protected
Definition at line 750 of file expr.py.
_op_classes
dict pandas.core.computation.expr._op_classes = {"binary": BinOp, "unary": UnaryOp} protected
Definition at line 317 of file expr.py.
_operator_nodes
pandas.core.computation.expr._operator_nodes = _filter_nodes(ast.operator) protected
Definition at line 203 of file expr.py.
_python_not_supported
pandas.core.computation.expr._python_not_supported = frozenset(["Dict", "BoolOp", "In", "NotIn"]) protected
Definition at line 749 of file expr.py.
_stmt_nodes
pandas.core.computation.expr._stmt_nodes = _filter_nodes(ast.stmt) protected
Definition at line 199 of file expr.py.
_T
pandas.core.computation.expr._T = TypeVar("_T") protected
Definition at line 268 of file expr.py.
_unary_op_nodes
pandas.core.computation.expr._unary_op_nodes = _filter_nodes(ast.unaryop) protected
Definition at line 204 of file expr.py.
_unsupported_expr_nodes
pandas.core.computation.expr._unsupported_expr_nodes protected
Initial value:
=  frozenset(
    [
        "Yield",
        "GeneratorExp",
        "IfExp",
        "DictComp",
        "SetComp",
        "Repr",
        "Lambda",
        "Set",
        "AST",
        "Is",
        "IsNot",
    ]
)
Definition at line 217 of file expr.py.
_unsupported_nodes
tuple pandas.core.computation.expr._unsupported_nodes protected
Initial value:
=  (
    _stmt_nodes
    | _mod_nodes
    | _handler_nodes
    | _arguments_nodes
    | _keyword_nodes
    | _alias_nodes
    | _expr_context_nodes
    | _unsupported_expr_nodes
) - _hacked_nodes
Definition at line 234 of file expr.py.
intersection
tuple pandas.core.computation.expr.intersection = _unsupported_nodes & _base_supported_nodes
Definition at line 249 of file expr.py.
PARSERS
dict pandas.core.computation.expr.PARSERS = {"python": PythonExprVisitor, "pandas": PandasExprVisitor}
Definition at line 840 of file expr.py.
unsupported_nodes
tuple pandas.core.computation.expr.unsupported_nodes = ()
Definition at line 283 of file expr.py.