Code Cloning Analysis: sklearn.cross_decomposition._pls Namespace Reference
sklearn.cross_decomposition._pls Namespace Reference
Classes
class _PLS
class CCA
class PLSCanonical
class PLSRegression
class PLSSVD
Functions
_pinv2_old (a)
_get_first_singular_vectors_power_method (X, y, mode="A", max_iter=500, tol=1e-06, norm_y_weights=False)
_get_first_singular_vectors_svd (X, y)
_center_scale_xy (X, y, scale=True)
_svd_flip_1d (u, v)
Variables
list __all__ = ["PLSSVD", "PLSCanonical", "PLSRegression"]
Detailed Description
The :mod:`sklearn.pls` module implements Partial Least Squares (PLS).
Function Documentation
_center_scale_xy()
sklearn.cross_decomposition._pls._center_scale_xy (X, y, scale = True) protected
Center X, y and scale if the scale parameter==True
Returns
-------
    X, y, x_mean, y_mean, x_std, y_std
Definition at line 119 of file _pls.py.
Referenced by sklearn.cross_decomposition._pls._PLS.fit(), and sklearn.cross_decomposition._pls.PLSSVD.fit().
_get_first_singular_vectors_power_method()
sklearn.cross_decomposition._pls._get_first_singular_vectors_power_method (X, y, mode = "A", max_iter = 500, tol = 1e-06, norm_y_weights = False) protected
Return the first left and right singular vectors of X'y.
Provides an alternative to the svd(X'y) and uses the power method instead.
With norm_y_weights to True and in mode A, this corresponds to the
algorithm section 11.3 of the Wegelin's review, except this starts at the
"update saliences" part.
Definition at line 50 of file _pls.py.
Referenced by sklearn.cross_decomposition._pls._PLS.fit().
_get_first_singular_vectors_svd()
sklearn.cross_decomposition._pls._get_first_singular_vectors_svd (X, y) protected
Return the first left and right singular vectors of X'y.
Here the whole SVD is computed.
Definition at line 109 of file _pls.py.
Referenced by sklearn.cross_decomposition._pls._PLS.fit().
_pinv2_old()
sklearn.cross_decomposition._pls._pinv2_old (a) protected
Definition at line 32 of file _pls.py.
_svd_flip_1d()
sklearn.cross_decomposition._pls._svd_flip_1d (u, v) protected
Same as svd_flip but works on 1d arrays, and is inplace
Definition at line 145 of file _pls.py.
Referenced by sklearn.cross_decomposition._pls._PLS.fit().
Variable Documentation
__all__
list sklearn.cross_decomposition._pls.__all__ = ["PLSSVD", "PLSCanonical", "PLSRegression"] private
Definition at line 29 of file _pls.py.