Code Cloning Analysis: pandas.util.version._BaseVersion Class Reference
pandas.util.version._BaseVersion Class Reference
Public Member Functions
int __hash__ (self)
bool __lt__ (self, _BaseVersion other)
bool __le__ (self, _BaseVersion other)
bool __eq__ (self, object other)
bool __ge__ (self, _BaseVersion other)
bool __gt__ (self, _BaseVersion other)
bool __ne__ (self, object other)
Static Protected Attributes
CmpKey _key | LegacyCmpKey
Detailed Description
Definition at line 140 of file __init__.py.
Member Function Documentation
__eq__()
bool pandas.util.version._BaseVersion.__eq__ (self, object other)
Definition at line 161 of file __init__.py.
Referenced by pip._vendor.msgpack.ext.Timestamp.__ne__(), and pip._vendor.distlib.version.Matcher.match().
__ge__()
bool pandas.util.version._BaseVersion.__ge__ (self, _BaseVersion other)
Definition at line 167 of file __init__.py.
__gt__()
bool pandas.util.version._BaseVersion.__gt__ (self, _BaseVersion other)
Definition at line 173 of file __init__.py.
__hash__()
int pandas.util.version._BaseVersion.__hash__ (self)
Definition at line 143 of file __init__.py.
Referenced by pip._vendor.rich.style.Style.pick_first().
__le__()
bool pandas.util.version._BaseVersion.__le__ (self, _BaseVersion other)
Definition at line 155 of file __init__.py.
__lt__()
bool pandas.util.version._BaseVersion.__lt__ (self, _BaseVersion other)
Definition at line 149 of file __init__.py.
__ne__()
bool pandas.util.version._BaseVersion.__ne__ (self, object other)
Definition at line 179 of file __init__.py.
Member Data Documentation
_key
pandas.util.version._BaseVersion._key | LegacyCmpKey static protected
Definition at line 141 of file __init__.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/util/version/__init__.py