Code Cloning Analysis: numpy.lib.index_tricks.nd_grid Class Reference
numpy.lib.index_tricks.nd_grid Class Reference
Public Member Functions
__init__ (self, sparse=False)
__getitem__ (self, key)
Public Attributes
sparse = sparse
Detailed Description
Construct a multi-dimensional "meshgrid".
``grid = nd_grid()`` creates an instance which will return a mesh-grid
when indexed.  The dimension and number of the output arrays are equal
to the number of indexing dimensions.  If the step length is not a
complex number, then the stop is not inclusive.
However, if the step length is a **complex number** (e.g. 5j), then the
integer part of its magnitude is interpreted as specifying the
number of points to create between the start and stop values, where
the stop value **is inclusive**.
If instantiated with an argument of ``sparse=True``, the mesh-grid is
open (or not fleshed out) so that only one-dimension of each returned
argument is greater than 1.
Parameters
----------
sparse : bool, optional
    Whether the grid is sparse or not. Default is False.
Notes
-----
Two instances of `nd_grid` are made available in the NumPy namespace,
`mgrid` and `ogrid`, approximately defined as::
    mgrid = nd_grid(sparse=False)
    ogrid = nd_grid(sparse=True)
Users should use these pre-defined instances instead of using `nd_grid`
directly.
Definition at line 109 of file index_tricks.py.
Constructor & Destructor Documentation
__init__()
numpy.lib.index_tricks.nd_grid.__init__ (self, sparse = False)
Definition at line 144 of file index_tricks.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__getitem__()
numpy.lib.index_tricks.nd_grid.__getitem__ (self, key)
Definition at line 147 of file index_tricks.py.
Member Data Documentation
sparse
numpy.lib.index_tricks.nd_grid.sparse = sparse
Definition at line 145 of file index_tricks.py.
Referenced by sklearn.impute._base.MissingIndicator._get_missing_features_info(), and sklearn.feature_extraction._dict_vectorizer.DictVectorizer.fit().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/lib/index_tricks.py