Code Cloning Analysis: pip._vendor.tenacity._asyncio.AsyncRetrying Class Reference
pip._vendor.tenacity._asyncio.AsyncRetrying Class Reference
Public Member Functions
None __init__ (self, t.Callable[[float], t.Awaitable[t.Any]] sleep=sleep, **t.Any kwargs)
WrappedFnReturnT __call__ (self, WrappedFn fn, *t.Any args, **t.Any kwargs)
t.Generator[AttemptManager, None, None] __iter__ (self)
"AsyncRetrying" __aiter__ (self)
AttemptManager __anext__ (self)
WrappedFn wraps (self, WrappedFn fn)
Public Member Functions inherited from pip._vendor.tenacity.BaseRetrying
__init__ (self, t.Callable[[t.Union[int, float]], None] sleep=sleep, "StopBaseT" stop=stop_never, "WaitBaseT" wait=wait_none(), "RetryBaseT" retry=retry_if_exception_type(), t.Callable[["RetryCallState"], None] before=before_nothing, t.Callable[["RetryCallState"], None] after=after_nothing, t.Optional[t.Callable[["RetryCallState"], None]] before_sleep=None, bool reraise=False, t.Type[RetryError] retry_error_cls=RetryError, t.Optional[t.Callable[["RetryCallState"], t.Any]] retry_error_callback=None)
"BaseRetrying" copy (self, t.Union[t.Callable[[t.Union[int, float]], None], object] sleep=_unset, t.Union["StopBaseT", object] stop=_unset, t.Union["WaitBaseT", object] wait=_unset, t.Union[retry_base, object] retry=_unset, t.Union[t.Callable[["RetryCallState"], None], object] before=_unset, t.Union[t.Callable[["RetryCallState"], None], object] after=_unset, t.Union[t.Optional[t.Callable[["RetryCallState"], None]], object] before_sleep=_unset, t.Union[bool, object] reraise=_unset, t.Union[t.Type[RetryError], object] retry_error_cls=_unset, t.Union[t.Optional[t.Callable[["RetryCallState"], t.Any]], object] retry_error_callback=_unset)
str __repr__ (self)
t.Dict[str, t.Any] statistics (self)
None begin (self)
t.Union[DoAttempt, DoSleep, t.Any] iter (self, "RetryCallState" retry_state)
t.Generator[AttemptManager, None, None] __iter__ (self)
WrappedFnReturnT __call__ (self, t.Callable[..., WrappedFnReturnT] fn, *t.Any args, **t.Any kwargs)
Protected Attributes
_retry_state = RetryCallState(self, fn=None, args=(), kwargs={})
Protected Attributes inherited from pip._vendor.tenacity.BaseRetrying
_local = threading.local()
Additional Inherited Members
Public Attributes inherited from pip._vendor.tenacity.BaseRetrying
sleep = sleep
stop = stop
wait = wait
retry = retry
before = before
after = after
before_sleep = before_sleep
reraise = reraise
retry_error_cls = retry_error_cls
retry_error_callback = retry_error_callback
Detailed Description
Definition at line 33 of file _asyncio.py.
Constructor & Destructor Documentation
__init__()
None pip._vendor.tenacity._asyncio.AsyncRetrying.__init__ (self, t.Callable[[float], t.Awaitable[t.Any]] sleep = sleep, **t.Any kwargs)
Definition at line 36 of file _asyncio.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
__aiter__()
"AsyncRetrying" pip._vendor.tenacity._asyncio.AsyncRetrying.__aiter__ (self)
Definition at line 64 of file _asyncio.py.
__anext__()
AttemptManager pip._vendor.tenacity._asyncio.AsyncRetrying.__anext__ (self)
Definition at line 69 of file _asyncio.py.
__call__()
WrappedFnReturnT pip._vendor.tenacity._asyncio.AsyncRetrying.__call__ (self, WrappedFn fn, *t.Any args, **t.Any kwargs)
Definition at line 40 of file _asyncio.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), and scipy.interpolate._fitpack2.SphereBivariateSpline.ev().
__iter__()
t.Generator[AttemptManager, None, None] pip._vendor.tenacity._asyncio.AsyncRetrying.__iter__ (self)
Definition at line 61 of file _asyncio.py.
wraps()
WrappedFn pip._vendor.tenacity._asyncio.AsyncRetrying.wraps (self, WrappedFn f)
Wrap a function for retrying.
:param f: A function to wraps for retrying.
Reimplemented from pip._vendor.tenacity.BaseRetrying.
Definition at line 82 of file _asyncio.py.
References wraps().
Referenced by wraps().
Member Data Documentation
_retry_state
pip._vendor.tenacity._asyncio.AsyncRetrying._retry_state = RetryCallState(self, fn=None, args=(), kwargs={}) protected
Definition at line 66 of file _asyncio.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pip/_vendor/tenacity/_asyncio.py