Code Cloning Analysis: pandas.io.excel._util Namespace Reference
pandas.io.excel._util Namespace Reference
Functions
None register_writer (ExcelWriter_t klass)
str get_default_engine (str ext, Literal["reader", "writer"] mode="reader")
ExcelWriter_t get_writer (str engine_name)
int _excel2num (str x)
list[int] _range2cols (str areas)
list[int] maybe_convert_usecols (str|list[int] usecols)
list[str] maybe_convert_usecols (list[str] usecols)
usecols_func maybe_convert_usecols (usecols_func usecols)
None maybe_convert_usecols (None usecols)
None|list[int]|list[str]|usecols_func maybe_convert_usecols (str|list[int]|list[str]|usecols_func|None usecols)
Literal[True] validate_freeze_panes (tuple[int, int] freeze_panes)
Literal[False] validate_freeze_panes (None freeze_panes)
bool validate_freeze_panes (tuple[int, int]|None freeze_panes)
tuple[list[Hashable], list[bool]] fill_mi_header (list[Hashable] row, list[bool] control_row)
tuple[Hashable|None, list[Hashable]] pop_header_name (list[Hashable] row, int|Sequence[int] index_col)
dict combine_kwargs (dict[str, Any]|None engine_kwargs, dict kwargs)
Variables
ExcelWriter_t = type[ExcelWriter]
usecols_func = TypeVar("usecols_func", bound=Callable[[Hashable], object])
dict _writers = {}
Function Documentation
_excel2num()
int pandas.io.excel._util._excel2num (str x) protected
Convert Excel column name like 'AB' to 0-based column index.
Parameters
----------
x : str
    The Excel column name to convert to a 0-based column index.
Returns
-------
num : int
    The column index corresponding to the name.
Raises
------
ValueError
    Part of the Excel column name was invalid.
Definition at line 98 of file _util.py.
Referenced by _range2cols().
_range2cols()
list[int] pandas.io.excel._util._range2cols (str areas) protected
Convert comma separated list of column names and ranges to indices.
Parameters
----------
areas : str
    A string containing a sequence of column ranges (or areas).
Returns
-------
cols : list
    A list of 0-based column indices.
Examples
--------
>>> _range2cols('A:E')
[0, 1, 2, 3, 4]
>>> _range2cols('A,C,Z:AB')
[0, 2, 25, 26, 27]
Definition at line 130 of file _util.py.
References _excel2num().
Referenced by maybe_convert_usecols().
combine_kwargs()
dict pandas.io.excel._util.combine_kwargs (dict[str, Any] | None engine_kwargs, dict kwargs)
Used to combine two sources of kwargs for the backend engine.
Use of kwargs is deprecated, this function is solely for use in 1.3 and should
be removed in 1.4/2.0. Also _base.ExcelWriter.__new__ ensures either engine_kwargs
or kwargs must be None or empty respectively.
Parameters
----------
engine_kwargs: dict
    kwargs to be passed through to the engine.
kwargs: dict
    kwargs to be psased through to the engine (deprecated)
Returns
-------
engine_kwargs combined with kwargs
Definition at line 310 of file _util.py.
fill_mi_header()
tuple[list[Hashable], list[bool]] pandas.io.excel._util.fill_mi_header (list[Hashable] row, list[bool] control_row)
Forward fill blank entries in row but only inside the same parent index.
Used for creating headers in Multiindex.
Parameters
----------
row : list
    List of items in a single row.
control_row : list of bool
    Helps to determine if particular column is in same parent index as the
    previous value. Used to stop propagation of empty cells between
    different indexes.
Returns
-------
Returns changed row and control_row
Definition at line 241 of file _util.py.
get_default_engine()
str pandas.io.excel._util.get_default_engine (str ext, Literal["reader", "writer"] mode = "reader")
Return the default reader/writer for the given extension.
Parameters
----------
ext : str
    The excel file extension for which to get the default engine.
mode : str {'reader', 'writer'}
    Whether to get the default engine for reading or writing.
    Either 'reader' or 'writer'
Returns
-------
str
    The default engine for the extension.
Definition at line 50 of file _util.py.
get_writer()
ExcelWriter_t pandas.io.excel._util.get_writer (str engine_name)
Definition at line 91 of file _util.py.
maybe_convert_usecols() [1/5]
list[str] pandas.io.excel._util.maybe_convert_usecols (list[str] usecols)
Definition at line 169 of file _util.py.
maybe_convert_usecols() [2/5]
None pandas.io.excel._util.maybe_convert_usecols (None usecols)
Definition at line 179 of file _util.py.
maybe_convert_usecols() [3/5]
list[int] pandas.io.excel._util.maybe_convert_usecols (str | list[int] usecols)
Definition at line 164 of file _util.py.
maybe_convert_usecols() [4/5]
None | list[int] | list[str] | usecols_func pandas.io.excel._util.maybe_convert_usecols (str | list[int] | list[str] | usecols_func | None usecols)
Convert `usecols` into a compatible format for parsing in `parsers.py`.
Parameters
----------
usecols : object
    The use-columns object to potentially convert.
Returns
-------
converted : object
    The compatible format of `usecols`.
Definition at line 183 of file _util.py.
References _range2cols().
maybe_convert_usecols() [5/5]
usecols_func pandas.io.excel._util.maybe_convert_usecols (usecols_func usecols)
Definition at line 174 of file _util.py.
pop_header_name()
tuple[Hashable | None, list[Hashable]] pandas.io.excel._util.pop_header_name (list[Hashable] row, int | Sequence[int] index_col)
Pop the header name for MultiIndex parsing.
Parameters
----------
row : list
    The data row to parse for the header name.
index_col : int, list
    The index columns for our data. Assumed to be non-null.
Returns
-------
header_name : str
    The extracted header name.
trimmed_row : list
    The original data row with the header name removed.
Definition at line 276 of file _util.py.
register_writer()
None pandas.io.excel._util.register_writer (ExcelWriter_t klass)
Add engine to the excel writer registry.io.excel.
You must use this method to integrate with ``to_excel``.
Parameters
----------
klass : ExcelWriter
Definition at line 34 of file _util.py.
validate_freeze_panes() [1/3]
Literal[False] pandas.io.excel._util.validate_freeze_panes (None freeze_panes)
Definition at line 220 of file _util.py.
validate_freeze_panes() [2/3]
Literal[True] pandas.io.excel._util.validate_freeze_panes (tuple[int, int] freeze_panes)
Definition at line 215 of file _util.py.
validate_freeze_panes() [3/3]
bool pandas.io.excel._util.validate_freeze_panes (tuple[int, int] | None freeze_panes)
Definition at line 224 of file _util.py.
Variable Documentation
_writers
dict pandas.io.excel._util._writers = {} protected
Definition at line 31 of file _util.py.
ExcelWriter_t
pandas.io.excel._util.ExcelWriter_t = type[ExcelWriter]
Definition at line 28 of file _util.py.
usecols_func
pandas.io.excel._util.usecols_func = TypeVar("usecols_func", bound=Callable[[Hashable], object])
Definition at line 29 of file _util.py.