Code Cloning Analysis: scipy.sparse.linalg._expm_multiply Namespace Reference
scipy.sparse.linalg._expm_multiply Namespace Reference
Classes
class LazyOperatorNormInfo
Functions
_exact_inf_norm (A)
_exact_1_norm (A)
_trace (A)
traceest (A, m3, seed=None)
_ident_like (A)
expm_multiply (A, B, start=None, stop=None, num=None, endpoint=None, traceA=None)
_expm_multiply_simple (A, B, t=1.0, traceA=None, balance=False)
_expm_multiply_simple_core (A, B, t, mu, m_star, s, tol=None, balance=False)
_onenormest_matrix_power (A, p, t=2, itmax=5, compute_v=False, compute_w=False)
_compute_cost_div_m (m, p, norm_info)
_compute_p_max (m_max)
_fragment_3_1 (norm_info, n0, tol, m_max=55, ell=2)
_condition_3_13 (A_1_norm, n0, m_max, ell)
_expm_multiply_interval (A, B, start=None, stop=None, num=None, endpoint=None, traceA=None, balance=False, status_only=False)
_expm_multiply_interval_core_0 (A, X, h, mu, q, norm_info, tol, ell, n0)
_expm_multiply_interval_core_1 (A, X, h, mu, m_star, s, q, tol)
_expm_multiply_interval_core_2 (A, X, h, mu, m_star, s, q, tol)
Variables
list __all__ = ['expm_multiply']
dict _theta
Detailed Description
Compute the action of the matrix exponential.
Function Documentation
_compute_cost_div_m()
scipy.sparse.linalg._expm_multiply._compute_cost_div_m (m, p, norm_info) protected
A helper function for computing bounds.
This is equation (3.10).
It measures cost in terms of the number of required matrix products.
Parameters
----------
m : int
    A valid key of _theta.
p : int
    A matrix power.
norm_info : LazyOperatorNormInfo
    Information about 1-norms of related operators.
Returns
-------
cost_div_m : int
    Required number of matrix products divided by m.
Definition at line 459 of file _expm_multiply.py.
Referenced by _fragment_3_1().
_compute_p_max()
scipy.sparse.linalg._expm_multiply._compute_p_max (m_max) protected
Compute the largest positive integer p such that p*(p-1) <= m_max + 1.
Do this in a slightly dumb way, but safe and not too slow.
Parameters
----------
m_max : int
    A count related to bounds.
Definition at line 484 of file _expm_multiply.py.
Referenced by _condition_3_13(), and _fragment_3_1().
_condition_3_13()
scipy.sparse.linalg._expm_multiply._condition_3_13 (A_1_norm, n0, m_max, ell) protected
A helper function for the _expm_multiply_* functions.
Parameters
----------
A_1_norm : float
    The precomputed 1-norm of A.
n0 : int
    Number of columns in the _expm_multiply_* B matrix.
m_max : int
    A value related to a bound.
ell : int
    The number of columns used in the 1-norm approximation.
    This is usually taken to be small, maybe between 1 and 5.
Returns
-------
value : bool
    Indicates whether or not the condition has been met.
Notes
-----
This is condition (3.13) in Al-Mohy and Higham (2011).
Definition at line 560 of file _expm_multiply.py.
References _compute_p_max().
Referenced by _fragment_3_1().
_exact_1_norm()
scipy.sparse.linalg._expm_multiply._exact_1_norm (A) protected
Definition at line 27 of file _expm_multiply.py.
_exact_inf_norm()
scipy.sparse.linalg._expm_multiply._exact_inf_norm (A) protected
Definition at line 17 of file _expm_multiply.py.
_expm_multiply_interval()
scipy.sparse.linalg._expm_multiply._expm_multiply_interval (A, B, start = None, stop = None, num = None, endpoint = None, traceA = None, balance = False, status_only = False) protected
Compute the action of the matrix exponential at multiple time points.
Parameters
----------
A : transposable linear operator
    The operator whose exponential is of interest.
B : ndarray
    The matrix to be multiplied by the matrix exponential of A.
start : scalar, optional
    The starting time point of the sequence.
stop : scalar, optional
    The end time point of the sequence, unless `endpoint` is set to False.
    In that case, the sequence consists of all but the last of ``num + 1``
    evenly spaced time points, so that `stop` is excluded.
    Note that the step size changes when `endpoint` is False.
num : int, optional
    Number of time points to use.
traceA : scalar, optional
    Trace of `A`. If not given the trace is estimated for linear operators,
    or calculated exactly for sparse matrices. It is used to precondition
    `A`, thus an approximate trace is acceptable
endpoint : bool, optional
    If True, `stop` is the last time point. Otherwise, it is not included.
balance : bool
    Indicates whether or not to apply balancing.
status_only : bool
    A flag that is set to True for some debugging and testing operations.
Returns
-------
F : ndarray
    :math:`e^{t_k A} B`
status : int
    An integer status for testing and debugging.
Notes
-----
This is algorithm (5.2) in Al-Mohy and Higham (2011).
There seems to be a typo, where line 15 of the algorithm should be
moved to line 6.5 (between lines 6 and 7).
Definition at line 596 of file _expm_multiply.py.
References _expm_multiply_interval_core_0(), _expm_multiply_interval_core_1(), _expm_multiply_interval_core_2(), _expm_multiply_simple_core(), _fragment_3_1(), scipy.sparse.linalg._onenormest.onenormest(), and traceest().
Referenced by expm_multiply().
_expm_multiply_interval_core_0()
scipy.sparse.linalg._expm_multiply._expm_multiply_interval_core_0 (A, X, h, mu, q, norm_info, tol, ell, n0) protected
A helper function, for the case q <= s.
Definition at line 729 of file _expm_multiply.py.
References _expm_multiply_simple_core(), and _fragment_3_1().
Referenced by _expm_multiply_interval().
_expm_multiply_interval_core_1()
scipy.sparse.linalg._expm_multiply._expm_multiply_interval_core_1 (A, X, h, mu, m_star, s, q, tol) protected
A helper function, for the case q > s and q % s == 0.
Definition at line 748 of file _expm_multiply.py.
Referenced by _expm_multiply_interval().
_expm_multiply_interval_core_2()
scipy.sparse.linalg._expm_multiply._expm_multiply_interval_core_2 (A, X, h, mu, m_star, s, q, tol) protected
A helper function, for the case q > s and q % s > 0.
Definition at line 777 of file _expm_multiply.py.
Referenced by _expm_multiply_interval().
_expm_multiply_simple()
scipy.sparse.linalg._expm_multiply._expm_multiply_simple (A, B, t = 1.0, traceA = None, balance = False) protected
Compute the action of the matrix exponential at a single time point.
Parameters
----------
A : transposable linear operator
    The operator whose exponential is of interest.
B : ndarray
    The matrix to be multiplied by the matrix exponential of A.
t : float
    A time point.
traceA : scalar, optional
    Trace of `A`. If not given the trace is estimated for linear operators,
    or calculated exactly for sparse matrices. It is used to precondition
    `A`, thus an approximate trace is acceptable
balance : bool
    Indicates whether or not to apply balancing.
Returns
-------
F : ndarray
    :math:`e^{t A} B`
Notes
-----
This is algorithm (3.2) in Al-Mohy and Higham (2011).
Definition at line 214 of file _expm_multiply.py.
References _expm_multiply_simple_core(), _fragment_3_1(), scipy.sparse.linalg._onenormest.onenormest(), and traceest().
Referenced by expm_multiply().
_expm_multiply_simple_core()
scipy.sparse.linalg._expm_multiply._expm_multiply_simple_core (A, B, t, mu, m_star, s, tol = None, balance = False) protected
A helper function.
Definition at line 280 of file _expm_multiply.py.
Referenced by _expm_multiply_interval(), _expm_multiply_interval_core_0(), and _expm_multiply_simple().
_fragment_3_1()
scipy.sparse.linalg._expm_multiply._fragment_3_1 (norm_info, n0, tol, m_max = 55, ell = 2) protected
A helper function for the _expm_multiply_* functions.
Parameters
----------
norm_info : LazyOperatorNormInfo
    Information about norms of certain linear operators of interest.
n0 : int
    Number of columns in the _expm_multiply_* B matrix.
tol : float
    Expected to be
    :math:`2^{-24}` for single precision or
    :math:`2^{-53}` for double precision.
m_max : int
    A value related to a bound.
ell : int
    The number of columns used in the 1-norm approximation.
    This is usually taken to be small, maybe between 1 and 5.
Returns
-------
best_m : int
    Related to bounds for error control.
best_s : int
    Amount of scaling.
Notes
-----
This is code fragment (3.1) in Al-Mohy and Higham (2011).
The discussion of default values for m_max and ell
is given between the definitions of equation (3.11)
and the definition of equation (3.12).
Definition at line 502 of file _expm_multiply.py.
References _compute_cost_div_m(), _compute_p_max(), and _condition_3_13().
Referenced by _expm_multiply_interval(), _expm_multiply_interval_core_0(), and _expm_multiply_simple().
_ident_like()
scipy.sparse.linalg._expm_multiply._ident_like (A) protected
Definition at line 92 of file _expm_multiply.py.
_onenormest_matrix_power()
scipy.sparse.linalg._expm_multiply._onenormest_matrix_power (A, p, t = 2, itmax = 5, compute_v = False, compute_w = False) protected
Efficiently estimate the 1-norm of A^p.
Parameters
----------
A : ndarray
    Matrix whose 1-norm of a power is to be computed.
p : int
    Non-negative integer power.
t : int, optional
    A positive parameter controlling the tradeoff between
    accuracy versus time and memory usage.
    Larger values take longer and use more memory
    but give more accurate output.
itmax : int, optional
    Use at most this many iterations.
compute_v : bool, optional
    Request a norm-maximizing linear operator input vector if True.
compute_w : bool, optional
    Request a norm-maximizing linear operator output vector if True.
Returns
-------
est : float
    An underestimate of the 1-norm of the sparse matrix.
v : ndarray, optional
    The vector such that ||Av||_1 == est*||v||_1.
    It can be thought of as an input to the linear operator
    that gives an output with particularly large norm.
w : ndarray, optional
    The vector Av which has relatively large 1-norm.
    It can be thought of as an output of the linear operator
    that is relatively large in norm compared to the input.
Definition at line 353 of file _expm_multiply.py.
References scipy.sparse.linalg._interface.aslinearoperator(), and scipy.sparse.linalg._onenormest.onenormest().
Referenced by scipy.sparse.linalg._expm_multiply.LazyOperatorNormInfo.d().
_trace()
scipy.sparse.linalg._expm_multiply._trace (A) protected
Definition at line 37 of file _expm_multiply.py.
expm_multiply()
scipy.sparse.linalg._expm_multiply.expm_multiply (A, B, start = None, stop = None, num = None, endpoint = None, traceA = None)
Compute the action of the matrix exponential of A on B.
Parameters
----------
A : transposable linear operator
    The operator whose exponential is of interest.
B : ndarray
    The matrix or vector to be multiplied by the matrix exponential of A.
start : scalar, optional
    The starting time point of the sequence.
stop : scalar, optional
    The end time point of the sequence, unless `endpoint` is set to False.
    In that case, the sequence consists of all but the last of ``num + 1``
    evenly spaced time points, so that `stop` is excluded.
    Note that the step size changes when `endpoint` is False.
num : int, optional
    Number of time points to use.
endpoint : bool, optional
    If True, `stop` is the last time point.  Otherwise, it is not included.
traceA : scalar, optional
    Trace of `A`. If not given the trace is estimated for linear operators,
    or calculated exactly for sparse matrices. It is used to precondition
    `A`, thus an approximate trace is acceptable.
    For linear operators, `traceA` should be provided to ensure performance
    as the estimation is not guaranteed to be reliable for all cases.
    .. versionadded:: 1.9.0
Returns
-------
expm_A_B : ndarray
     The result of the action :math:`e^{t_k A} B`.
Warns
-----
UserWarning
    If `A` is a linear operator and ``traceA=None`` (default).
Notes
-----
The optional arguments defining the sequence of evenly spaced time points
are compatible with the arguments of `numpy.linspace`.
The output ndarray shape is somewhat complicated so I explain it here.
The ndim of the output could be either 1, 2, or 3.
It would be 1 if you are computing the expm action on a single vector
at a single time point.
It would be 2 if you are computing the expm action on a vector
at multiple time points, or if you are computing the expm action
on a matrix at a single time point.
It would be 3 if you want the action on a matrix with multiple
columns at multiple time points.
If multiple time points are requested, expm_A_B[0] will always
be the action of the expm at the first time point,
regardless of whether the action is on a vector or a matrix.
References
----------
.. [1] Awad H. Al-Mohy and Nicholas J. Higham (2011)
       "Computing the Action of the Matrix Exponential,
       with an Application to Exponential Integrators."
       SIAM Journal on Scientific Computing,
       33 (2). pp. 488-511. ISSN 1064-8275
       http://eprints.ma.man.ac.uk/1591/
.. [2] Nicholas J. Higham and Awad H. Al-Mohy (2010)
       "Computing Matrix Functions."
       Acta Numerica,
       19. 159-208. ISSN 0962-4929
       http://eprints.ma.man.ac.uk/1451/
Examples
--------
>>> import numpy as np
>>> from scipy.sparse import csc_matrix
>>> from scipy.sparse.linalg import expm, expm_multiply
>>> A = csc_matrix([[1, 0], [0, 1]])
>>> A.toarray()
array([[1, 0],
       [0, 1]], dtype=int64)
>>> B = np.array([np.exp(-1.), np.exp(-2.)])
>>> B
array([ 0.36787944,  0.13533528])
>>> expm_multiply(A, B, start=1, stop=2, num=3, endpoint=True)
array([[ 1.        ,  0.36787944],
       [ 1.64872127,  0.60653066],
       [ 2.71828183,  1.        ]])
>>> expm(A).dot(B)                  # Verify 1st timestep
array([ 1.        ,  0.36787944])
>>> expm(1.5*A).dot(B)              # Verify 2nd timestep
array([ 1.64872127,  0.60653066])
>>> expm(2*A).dot(B)                # Verify 3rd timestep
array([ 2.71828183,  1.        ])
Definition at line 109 of file _expm_multiply.py.
References _expm_multiply_interval(), and _expm_multiply_simple().
Referenced by scipy.sparse.linalg.tests.test_expm_multiply.test_expm_multiply_dtype().
traceest()
scipy.sparse.linalg._expm_multiply.traceest (A, m3, seed = None)
Estimate `np.trace(A)` using `3*m3` matrix-vector products.
The result is not deterministic.
Parameters
----------
A : LinearOperator
    Linear operator whose trace will be estimated. Has to be square.
m3 : int
    Number of matrix-vector products divided by 3 used to estimate the
    trace.
seed : optional
    Seed for `numpy.random.default_rng`.
    Can be provided to obtain deterministic results.
Returns
-------
trace : LinearOperator.dtype
    Estimate of the trace
Notes
-----
This is the Hutch++ algorithm given in [1]_.
References
----------
.. [1] Meyer, Raphael A., Cameron Musco, Christopher Musco, and David P.
   Woodruff. "Hutch++: Optimal Stochastic Trace Estimation." In Symposium
   on Simplicity in Algorithms (SOSA), pp. 142-155. Society for Industrial
   and Applied Mathematics, 2021
   https://doi.org/10.1137/1.9781611976496.16
Definition at line 45 of file _expm_multiply.py.
Referenced by _expm_multiply_interval(), and _expm_multiply_simple().
Variable Documentation
__all__
list scipy.sparse.linalg._expm_multiply.__all__ = ['expm_multiply'] private
Definition at line 14 of file _expm_multiply.py.
_theta
dict scipy.sparse.linalg._expm_multiply._theta protected
Definition at line 309 of file _expm_multiply.py.