Code Cloning Analysis: pandas.io.json._table_schema Namespace Reference
pandas.io.json._table_schema Namespace Reference
Functions
str as_json_table_type (DtypeObj x)
set_default_names (data)
dict[str, JSONSerializable] convert_pandas_type_to_json_field (arr)
str|CategoricalDtype convert_json_field_to_pandas_type (field)
dict[str, JSONSerializable] build_table_schema (DataFrame|Series data, bool index=True, bool|None primary_key=None, bool version=True)
DataFrame parse_table_schema (json, bool precise_float)
Variables
str TABLE_SCHEMA_VERSION = "1.4.0"
Detailed Description
Table Schema builders
https://specs.frictionlessdata.io/table-schema/
Function Documentation
as_json_table_type()
str pandas.io.json._table_schema.as_json_table_type (DtypeObj x)
Convert a NumPy / pandas type to its corresponding json_table.
Parameters
----------
x : np.dtype or ExtensionDtype
Returns
-------
str
    the Table Schema data types
Notes
-----
This table shows the relationship between NumPy / pandas dtypes,
and Table Schema dtypes.
==============  =================
Pandas type     Table Schema type
==============  =================
int64           integer
float64         number
bool            boolean
datetime64[ns]  datetime
timedelta64[ns] duration
object          str
categorical     any
=============== =================
Definition at line 53 of file _table_schema.py.
Referenced by set_default_names().
build_table_schema()
dict[str, JSONSerializable] pandas.io.json._table_schema.build_table_schema (DataFrame | Series data, bool index = True, bool | None primary_key = None, bool version = True)
Create a Table schema from ``data``.
Parameters
----------
data : Series, DataFrame
index : bool, default True
    Whether to include ``data.index`` in the schema.
primary_key : bool or None, default True
    Column names to designate as the primary key.
    The default `None` will set `'primaryKey'` to the index
    level or levels if the index is unique.
version : bool, default True
    Whether to include a field `pandas_version` with the version
    of pandas that last revised the table schema. This version
    can be different from the installed pandas version.
Returns
-------
dict
Notes
-----
See `Table Schema
<https://pandas.pydata.org/docs/user_guide/io.html#table-schema>`__ for
conversion types.
Timedeltas as converted to ISO8601 duration format with
9 decimal places after the seconds field for nanosecond precision.
Categoricals are converted to the `any` dtype, and use the `enum` field
constraint to list the allowed values. The `ordered` attribute is included
in an `ordered` field.
Examples
--------
>>> from pandas.io.json._table_schema import build_table_schema
>>> df = pd.DataFrame(
...     {'A': [1, 2, 3],
...      'B': ['a', 'b', 'c'],
...      'C': pd.date_range('2016-01-01', freq='d', periods=3),
...     }, index=pd.Index(range(3), name='idx'))
>>> build_table_schema(df)
{'fields': \
[{'name': 'idx', 'type': 'integer'}, \
{'name': 'A', 'type': 'integer'}, \
{'name': 'B', 'type': 'string'}, \
{'name': 'C', 'type': 'datetime'}], \
'primaryKey': ['idx'], \
'pandas_version': '1.4.0'}
Definition at line 234 of file _table_schema.py.
References set_default_names().
convert_json_field_to_pandas_type()
str | CategoricalDtype pandas.io.json._table_schema.convert_json_field_to_pandas_type (field)
Converts a JSON field descriptor into its corresponding NumPy / pandas type
Parameters
----------
field
    A JSON field descriptor
Returns
-------
dtype
Raises
------
ValueError
    If the type of the provided field is unknown or currently unsupported
Examples
--------
>>> convert_json_field_to_pandas_type({"name": "an_int", "type": "integer"})
'int64'
>>> convert_json_field_to_pandas_type(
...     {
...         "name": "a_categorical",
...         "type": "any",
...         "constraints": {"enum": ["a", "b", "c"]},
...         "ordered": True,
...     }
...)
CategoricalDtype(categories=['a', 'b', 'c'], ordered=True, categories_dtype=object)
>>> convert_json_field_to_pandas_type({"name": "a_datetime", "type": "datetime"})
'datetime64[ns]'
>>> convert_json_field_to_pandas_type(
...     {"name": "a_datetime_with_tz", "type": "datetime", "tz": "US/Central"}
...)
'datetime64[ns, US/Central]'
Definition at line 157 of file _table_schema.py.
Referenced by parse_table_schema().
convert_pandas_type_to_json_field()
dict[str, JSONSerializable] pandas.io.json._table_schema.convert_pandas_type_to_json_field (arr)
Definition at line 125 of file _table_schema.py.
parse_table_schema()
DataFrame pandas.io.json._table_schema.parse_table_schema (json, bool precise_float)
Builds a DataFrame from a given schema
Parameters
----------
json :
    A JSON table schema
precise_float : bool
    Flag controlling precision when decoding string to double values, as
    dictated by ``read_json``
Returns
-------
df : DataFrame
Raises
------
NotImplementedError
    If the JSON table schema contains either timezone or timedelta data
Notes
-----
    Because :func:`DataFrame.to_json` uses the string 'index' to denote a
    name-less :class:`Index`, this function sets the name of the returned
    :class:`DataFrame` to ``None`` when said string is encountered with a
    normal :class:`Index`. For a :class:`MultiIndex`, the same limitation
    applies to any strings beginning with 'level_'. Therefore, an
    :class:`Index` name of 'index'  and :class:`MultiIndex` names starting
    with 'level_' are not supported.
See Also
--------
build_table_schema : Inverse function.
pandas.read_json
Definition at line 326 of file _table_schema.py.
References convert_json_field_to_pandas_type().
set_default_names()
pandas.io.json._table_schema.set_default_names (data)
Sets index names to 'index' for regular, or 'level_x' for Multi
Definition at line 101 of file _table_schema.py.
References as_json_table_type().
Referenced by build_table_schema().
Variable Documentation
TABLE_SCHEMA_VERSION
str pandas.io.json._table_schema.TABLE_SCHEMA_VERSION = "1.4.0"
Definition at line 50 of file _table_schema.py.