Code Cloning Analysis: matplotlib._afm Namespace Reference
matplotlib._afm Namespace Reference
Classes
class AFM
Functions
_to_int (x)
_to_float (x)
_to_str (x)
_to_list_of_ints (s)
_to_list_of_floats (s)
_to_bool (s)
_parse_header (fh)
_parse_char_metrics (fh)
_parse_kern_pairs (fh)
_parse_composites (fh)
_parse_optional (fh)
Variables
_log = logging.getLogger(__name__)
CharMetrics = namedtuple('CharMetrics', 'width, name, bbox')
__doc__
CompositePart = namedtuple('CompositePart', 'name, dx, dy')
Detailed Description
A python interface to Adobe Font Metrics Files.
Although a number of other Python implementations exist, and may be more
complete than this, it was decided not to go with them because they were
either:
1) copyrighted or used a non-BSD compatible license
2) had too many dependencies and a free standing lib was needed
3) did more than needed and it was easier to write afresh rather than
   figure out how to get just what was needed.
It is pretty easy to use, and has no external dependencies:
>>> import matplotlib as mpl
>>> from pathlib import Path
>>> afm_path = Path(mpl.get_data_path(), 'fonts', 'afm', 'ptmr8a.afm')
>>>
>>> from matplotlib.afm import AFM
>>> with afm_path.open('rb') as fh:
...     afm = AFM(fh)
>>> afm.string_width_height('What the heck?')
(6220.0, 694)
>>> afm.get_fontname()
'Times-Roman'
>>> afm.get_kern_dist('A', 'f')
0
>>> afm.get_kern_dist('A', 'y')
-92.0
>>> afm.get_bbox_char('!')
[130, -9, 238, 676]
As in the Adobe Font Metrics File Format Specification, all dimensions
are given in units of 1/1000 of the scale factor (point size) of the font
being used.
Function Documentation
_parse_char_metrics()
matplotlib._afm._parse_char_metrics (fh) protected
Parse the given filehandle for character metrics information and return
the information as dicts.
It is assumed that the file cursor is on the line behind
'StartCharMetrics'.
Returns
-------
ascii_d : dict
     A mapping "ASCII num of the character" to `.CharMetrics`.
name_d : dict
     A mapping "character name" to `.CharMetrics`.
Notes
-----
This function is incomplete per the standard, but thus far parses
all the sample afm files tried.
Definition at line 186 of file _afm.py.
Referenced by matplotlib._afm.AFM.__init__().
_parse_composites()
matplotlib._afm._parse_composites (fh) protected
Parse the given filehandle for composites information return them as a
dict.
It is assumed that the file cursor is on the line behind 'StartComposites'.
Returns
-------
dict
    A dict mapping composite character names to a parts list. The parts
    list is a list of `.CompositePart` entries describing the parts of
    the composite.
Examples
--------
A composite definition line::
  CC Aacute 2 ; PCC A 0 0 ; PCC acute 160 170 ;
will be represented as::
  composites['Aacute'] = [CompositePart(name='A', dx=0, dy=0),
                          CompositePart(name='acute', dx=160, dy=170)]
Definition at line 280 of file _afm.py.
_parse_header()
matplotlib._afm._parse_header (fh) protected
Read the font metrics header (up to the char metrics) and returns
a dictionary mapping *key* to *val*.  *val* will be converted to the
appropriate python type as necessary; e.g.:
    * 'False'->False
    * '0'->0
    * '-168 -218 1000 898'-> [-168, -218, 1000, 898]
Dictionary keys are
  StartFontMetrics, FontName, FullName, FamilyName, Weight,
  ItalicAngle, IsFixedPitch, FontBBox, UnderlinePosition,
  UnderlineThickness, Version, Notice, EncodingScheme, CapHeight,
  XHeight, Ascender, Descender, StartCharMetrics
Definition at line 88 of file _afm.py.
Referenced by matplotlib._afm.AFM.__init__().
_parse_kern_pairs()
matplotlib._afm._parse_kern_pairs (fh) protected
Return a kern pairs dictionary; keys are (*char1*, *char2*) tuples and
values are the kern pair value.  For example, a kern pairs line like
``KPX A y -50``
will be represented as::
  d[ ('A', 'y') ] = -50
Definition at line 240 of file _afm.py.
_parse_optional()
matplotlib._afm._parse_optional (fh) protected
Parse the optional fields for kern pair data and composites.
Returns
-------
kern_data : dict
    A dict containing kerning information. May be empty.
    See `._parse_kern_pairs`.
composites : dict
    A dict containing composite information. May be empty.
    See `._parse_composites`.
Definition at line 326 of file _afm.py.
Referenced by matplotlib._afm.AFM.__init__().
_to_bool()
matplotlib._afm._to_bool (s) protected
Definition at line 81 of file _afm.py.
_to_float()
matplotlib._afm._to_float (x) protected
Definition at line 57 of file _afm.py.
_to_int()
matplotlib._afm._to_int (x) protected
Definition at line 48 of file _afm.py.
_to_list_of_floats()
matplotlib._afm._to_list_of_floats (s) protected
Definition at line 77 of file _afm.py.
_to_list_of_ints()
matplotlib._afm._to_list_of_ints (s) protected
Definition at line 72 of file _afm.py.
_to_str()
matplotlib._afm._to_str (x) protected
Definition at line 68 of file _afm.py.
Variable Documentation
__doc__
matplotlib._afm.__doc__ private
Definition at line 172 of file _afm.py.
_log
matplotlib._afm._log = logging.getLogger(__name__) protected
Definition at line 45 of file _afm.py.
CharMetrics
matplotlib._afm.CharMetrics = namedtuple('CharMetrics', 'width, name, bbox')
Definition at line 171 of file _afm.py.
CompositePart
matplotlib._afm.CompositePart = namedtuple('CompositePart', 'name, dx, dy')
Definition at line 272 of file _afm.py.