Code Cloning Analysis: numpy.lib.npyio.BagObj Class Reference
numpy.lib.npyio.BagObj Class Reference
Public Member Functions
__init__ (self, obj)
__getattribute__ (self, key)
__dir__ (self)
Protected Attributes
_obj = weakref.proxy(obj)
Detailed Description
BagObj(obj)
Convert attribute look-ups to getitems on the object passed in.
Parameters
----------
obj : class instance
    Object on which attribute look-up is performed.
Examples
--------
>>> from numpy.lib.npyio import BagObj as BO
>>> class BagDemo:
...     def __getitem__(self, key): # An instance of BagObj(BagDemo)
...                                 # will call this method when any
...                                 # attribute look-up is required
...         result = "Doesn't matter what you want, "
...         return result + "you're gonna get this"
...
>>> demo_obj = BagDemo()
>>> bagobj = BO(demo_obj)
>>> bagobj.hello_there
"Doesn't matter what you want, you're gonna get this"
>>> bagobj.I_can_be_anything
"Doesn't matter what you want, you're gonna get this"
Definition at line 42 of file npyio.py.
Constructor & Destructor Documentation
__init__()
numpy.lib.npyio.BagObj.__init__ (self, obj)
Definition at line 72 of file npyio.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__dir__()
numpy.lib.npyio.BagObj.__dir__ (self)
Enables dir(bagobj) to list the files in an NpzFile.
This also enables tab-completion in an interpreter or IPython.
Definition at line 82 of file npyio.py.
__getattribute__()
numpy.lib.npyio.BagObj.__getattribute__ (self, key)
Definition at line 76 of file npyio.py.
Member Data Documentation
_obj
numpy.lib.npyio.BagObj._obj = weakref.proxy(obj) protected
Definition at line 74 of file npyio.py.
Referenced by scipy._lib._docscrape.NumpyDocString._parse_summary(), and pandas.core.flags.Flags.allows_duplicate_labels().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/lib/npyio.py