Code Cloning Analysis: prompt_script5 Namespace Reference
prompt_script5 Namespace Reference
Functions
truncate_code (code, max_lines=50)
parse_json_response (response_text)
ensemble_assessment (code1, code2, model_name, prompt, n=3)
determine_similarity (results)
rag_similarity_assessment (code1, code2, model_name, prompt)
Variables
str DATA_DIR = "/projappl/project_2014646/shreya/data/data"
str PAIRS_CSV = "/projappl/project_2014646/shreya/pairs.csv"
str GROUND_TRUTH_CSV = "/projappl/project_2014646/shreya/ground_truth.csv"
list LLMS
list PROMPTS
pairs_df = pd.read_csv(PAIRS_CSV)
ground_truth_df = pd.read_csv(GROUND_TRUTH_CSV)
ground_truth_map = dict(zip(ground_truth_df['pair-id'], ground_truth_df['similar']))
dict results_by_prompt = {i: {'truth': [], 'preds': []} for i in range(len(PROMPTS))}
str output = f"/projappl/project_2014646/shreya/results/RAG_vs_CodeNet_prompt_results_ds14b_iteration_{iteration}.csv"
newline
writer = csv.writer(outfile)
file1_path = os.path.join(DATA_DIR, row['file1'])
file2_path = os.path.join(DATA_DIR, row['file2'])
pair_id = row['pair-id']
encoding
errors
code1 = f1.read()
code2 = f2.read()
ground_truth_sim = ground_truth_map.get(pair_id, "Unknown")
results
predicted_type
predicted_sim
model_name
prompt
n
str metrics_output = f'/projappl/project_2014646/shreya/results/metrics_ds14b_prompt_iteration_{iteration}.txt'
file
dict truth = results_by_prompt[prompt_id]['truth']
dict preds = results_by_prompt[prompt_id]['preds']
acc = accuracy_score(truth, preds)
prec = precision_score(truth, preds, zero_division=0)
rec = recall_score(truth, preds, zero_division=0)
f1s = f1_score(truth, preds, zero_division=0)
mse = mean_squared_error(truth, preds)
Function Documentation
determine_similarity()
prompt_script5.determine_similarity (results)
Determine if codes are similar based on clone type results
Definition at line 235 of file prompt_script5.1.py.
References determine_similarity(), and parse_json_response().
Referenced by determine_similarity().
ensemble_assessment()
prompt_script5.ensemble_assessment (code1, code2, model_name, prompt, n = 3)
Definition at line 184 of file prompt_script5.1.py.
parse_json_response()
prompt_script5.parse_json_response (response_text)
Enhanced JSON parsing with multiple fallback strategies for yes/no responses
Definition at line 103 of file prompt_script5.1.py.
Referenced by determine_similarity().
rag_similarity_assessment()
prompt_script5.rag_similarity_assessment (code1, code2, model_name, prompt)
Definition at line 252 of file prompt_script5.1.py.
truncate_code()
prompt_script5.truncate_code (code, max_lines = 50)
Definition at line 98 of file prompt_script5.1.py.
Variable Documentation
acc
prompt_script5.acc = accuracy_score(truth, preds)
Definition at line 353 of file prompt_script5.1.py.
code1
prompt_script5.code1 = f1.read()
Definition at line 319 of file prompt_script5.1.py.
code2
prompt_script5.code2 = f2.read()
Definition at line 320 of file prompt_script5.1.py.
DATA_DIR
str prompt_script5.DATA_DIR = "/projappl/project_2014646/shreya/data/data"
Definition at line 10 of file prompt_script5.1.py.
encoding
prompt_script5.encoding
Definition at line 317 of file prompt_script5.1.py.
errors
prompt_script5.errors
Definition at line 317 of file prompt_script5.1.py.
f1s
prompt_script5.f1s = f1_score(truth, preds, zero_division=0)
Definition at line 356 of file prompt_script5.1.py.
file
prompt_script5.file
Definition at line 346 of file prompt_script5.1.py.
file1_path
prompt_script5.file1_path = os.path.join(DATA_DIR, row['file1'])
Definition at line 312 of file prompt_script5.1.py.
file2_path
prompt_script5.file2_path = os.path.join(DATA_DIR, row['file2'])
Definition at line 313 of file prompt_script5.1.py.
GROUND_TRUTH_CSV
str prompt_script5.GROUND_TRUTH_CSV = "/projappl/project_2014646/shreya/ground_truth.csv"
Definition at line 12 of file prompt_script5.1.py.
ground_truth_df
prompt_script5.ground_truth_df = pd.read_csv(GROUND_TRUTH_CSV)
Definition at line 94 of file prompt_script5.1.py.
ground_truth_map
prompt_script5.ground_truth_map = dict(zip(ground_truth_df['pair-id'], ground_truth_df['similar']))
Definition at line 95 of file prompt_script5.1.py.
ground_truth_sim
prompt_script5.ground_truth_sim = ground_truth_map.get(pair_id, "Unknown")
Definition at line 325 of file prompt_script5.1.py.
LLMS
list prompt_script5.LLMS
Initial value:
=  [
    "deepseek-r1:14b"
]
Definition at line 14 of file prompt_script5.1.py.
metrics_output
str prompt_script5.metrics_output = f'/projappl/project_2014646/shreya/results/metrics_ds14b_prompt_iteration_{iteration}.txt'
Definition at line 344 of file prompt_script5.1.py.
model_name
prompt_script5.model_name
Definition at line 332 of file prompt_script5.1.py.
mse
prompt_script5.mse = mean_squared_error(truth, preds)
Definition at line 357 of file prompt_script5.1.py.
n
prompt_script5.n
Definition at line 332 of file prompt_script5.1.py.
newline
prompt_script5.newline
Definition at line 300 of file prompt_script5.1.py.
output
str prompt_script5.output = f"/projappl/project_2014646/shreya/results/RAG_vs_CodeNet_prompt_results_ds14b_iteration_{iteration}.csv"
Definition at line 298 of file prompt_script5.1.py.
pair_id
prompt_script5.pair_id = row['pair-id']
Definition at line 314 of file prompt_script5.1.py.
PAIRS_CSV
str prompt_script5.PAIRS_CSV = "/projappl/project_2014646/shreya/pairs.csv"
Definition at line 11 of file prompt_script5.1.py.
pairs_df
prompt_script5.pairs_df = pd.read_csv(PAIRS_CSV)
Definition at line 93 of file prompt_script5.1.py.
prec
prompt_script5.prec = precision_score(truth, preds, zero_division=0)
Definition at line 354 of file prompt_script5.1.py.
predicted_sim
prompt_script5.predicted_sim
Definition at line 332 of file prompt_script5.1.py.
predicted_type
prompt_script5.predicted_type
Definition at line 332 of file prompt_script5.1.py.
preds
dict prompt_script5.preds = results_by_prompt[prompt_id]['preds']
Definition at line 350 of file prompt_script5.1.py.
prompt
prompt_script5.prompt
Definition at line 332 of file prompt_script5.1.py.
PROMPTS
list prompt_script5.PROMPTS
Initial value:
=  [
    # Prompt 1
    ,
    # Prompt 2
    ,
    # Prompt 3
]
Definition at line 19 of file prompt_script5.1.py.
rec
prompt_script5.rec = recall_score(truth, preds, zero_division=0)
Definition at line 355 of file prompt_script5.1.py.
results
prompt_script5.results
Definition at line 332 of file prompt_script5.1.py.
results_by_prompt
dict prompt_script5.results_by_prompt = {i: {'truth': [], 'preds': []} for i in range(len(PROMPTS))}
Definition at line 294 of file prompt_script5.1.py.
truth
dict prompt_script5.truth = results_by_prompt[prompt_id]['truth']
Definition at line 349 of file prompt_script5.1.py.
writer
prompt_script5.writer = csv.writer(outfile)
Definition at line 301 of file prompt_script5.1.py.