Code Cloning Analysis: scipy.optimize.tests.test__dual_annealing.TestDualAnnealing Class Reference
scipy.optimize.tests.test__dual_annealing.TestDualAnnealing Class Reference
Public Member Functions
setup_method (self)
callback (self, x, f, context)
func (self, x, args=())
rosen_der_wrapper (self, x, args=())
test_visiting_stepping (self, qv)
test_visiting_dist_high_temperature (self, qv)
test_reset (self)
test_low_dim (self)
test_high_dim (self)
test_low_dim_no_ls (self)
test_high_dim_no_ls (self)
test_nb_fun_call (self)
test_nb_fun_call_no_ls (self)
test_max_reinit (self)
test_reproduce (self)
test_rand_gen (self)
test_bounds_integrity (self)
test_bound_validity (self)
test_deprecated_local_search_options_bounds (self)
test_minimizer_kwargs_bounds (self)
test_max_fun_ls (self)
test_max_fun_no_ls (self)
test_maxiter (self)
test_fun_args_ls (self)
test_fun_args_no_ls (self)
test_callback_stop (self)
test_multi_ls_minimizer (self, method, atol)
test_wrong_restart_temp (self)
test_gradient_gnev (self)
test_from_docstring (self)
test_accept_reject_probabilistic (self, new_e, temp_step, accepted, accept_rate)
test_bounds_class (self)
test_callable_jac_with_args_gh11052 (self)
Public Attributes
weirdfunc = lambda x: np.inf
list ld_bounds = [(-5.12, 5.12)] * 2
list hd_bounds = self.ld_bounds * 4
int nbtestvalues = 5000
int high_temperature = 5230
float low_temperature = 0.1
float qv = 2.62
int seed = 1234
rs = check_random_state(self.seed)
int nb_fun_call = 0
int ngev = 0
func = [(-5, 5), (0, np.inf), (-5, 5)]
Detailed Description
Definition at line 23 of file test__dual_annealing.py.
Member Function Documentation
callback()
scipy.optimize.tests.test__dual_annealing.TestDualAnnealing.callback (self, x, f, context)
Definition at line 42 of file test__dual_annealing.py.
func()
scipy.optimize.tests.test__dual_annealing.TestDualAnnealing.func (self, x, args = ())
Definition at line 48 of file test__dual_annealing.py.
rosen_der_wrapper()
scipy.optimize.tests.test__dual_annealing.TestDualAnnealing.rosen_der_wrapper (self, x, args = ())
Definition at line 59 of file test__dual_annealing.py.
setup_method()
scipy.optimize.tests.test__dual_annealing.TestDualAnnealing.setup_method (self)
Definition at line 25 of file test__dual_annealing.py.
test_accept_reject_probabilistic()
scipy.optimize.tests.test__dual_annealing.TestDualAnnealing.test_accept_reject_probabilistic (self, new_e, temp_step, accepted, accept_rate)
Definition at line 301 of file test__dual_annealing.py.
test_bound_validity()
scipy.optimize.tests.test__dual_annealing.TestDualAnnealing.test_bound_validity (self)
Definition at line 168 of file test__dual_annealing.py.
test_bounds_class()
scipy.optimize.tests.test__dual_annealing.TestDualAnnealing.test_bounds_class (self)
Definition at line 336 of file test__dual_annealing.py.
test_bounds_integrity()
scipy.optimize.tests.test__dual_annealing.TestDualAnnealing.test_bounds_integrity (self)
Definition at line 163 of file test__dual_annealing.py.
test_callable_jac_with_args_gh11052()
scipy.optimize.tests.test__dual_annealing.TestDualAnnealing.test_callable_jac_with_args_gh11052 (self)
Definition at line 364 of file test__dual_annealing.py.
test_callback_stop()
scipy.optimize.tests.test__dual_annealing.TestDualAnnealing.test_callback_stop (self)
Definition at line 242 of file test__dual_annealing.py.
test_deprecated_local_search_options_bounds()
scipy.optimize.tests.test__dual_annealing.TestDualAnnealing.test_deprecated_local_search_options_bounds (self)
Definition at line 179 of file test__dual_annealing.py.
test_from_docstring()
scipy.optimize.tests.test__dual_annealing.TestDualAnnealing.test_from_docstring (self)
Definition at line 281 of file test__dual_annealing.py.
test_fun_args_ls()
scipy.optimize.tests.test__dual_annealing.TestDualAnnealing.test_fun_args_ls (self)
Definition at line 230 of file test__dual_annealing.py.
test_fun_args_no_ls()
scipy.optimize.tests.test__dual_annealing.TestDualAnnealing.test_fun_args_no_ls (self)
Definition at line 236 of file test__dual_annealing.py.
test_gradient_gnev()
scipy.optimize.tests.test__dual_annealing.TestDualAnnealing.test_gradient_gnev (self)
Definition at line 272 of file test__dual_annealing.py.
test_high_dim()
scipy.optimize.tests.test__dual_annealing.TestDualAnnealing.test_high_dim (self)
Definition at line 113 of file test__dual_annealing.py.
test_high_dim_no_ls()
scipy.optimize.tests.test__dual_annealing.TestDualAnnealing.test_high_dim_no_ls (self)
Definition at line 123 of file test__dual_annealing.py.
test_low_dim()
scipy.optimize.tests.test__dual_annealing.TestDualAnnealing.test_low_dim (self)
Definition at line 107 of file test__dual_annealing.py.
test_low_dim_no_ls()
scipy.optimize.tests.test__dual_annealing.TestDualAnnealing.test_low_dim_no_ls (self)
Definition at line 118 of file test__dual_annealing.py.
test_max_fun_ls()
scipy.optimize.tests.test__dual_annealing.TestDualAnnealing.test_max_fun_ls (self)
Definition at line 207 of file test__dual_annealing.py.
test_max_fun_no_ls()
scipy.optimize.tests.test__dual_annealing.TestDualAnnealing.test_max_fun_no_ls (self)
Definition at line 218 of file test__dual_annealing.py.
test_max_reinit()
scipy.optimize.tests.test__dual_annealing.TestDualAnnealing.test_max_reinit (self)
Definition at line 137 of file test__dual_annealing.py.
test_maxiter()
scipy.optimize.tests.test__dual_annealing.TestDualAnnealing.test_maxiter (self)
Definition at line 224 of file test__dual_annealing.py.
test_minimizer_kwargs_bounds()
scipy.optimize.tests.test__dual_annealing.TestDualAnnealing.test_minimizer_kwargs_bounds (self)
Definition at line 191 of file test__dual_annealing.py.
test_multi_ls_minimizer()
scipy.optimize.tests.test__dual_annealing.TestDualAnnealing.test_multi_ls_minimizer (self, method, atol)
Definition at line 260 of file test__dual_annealing.py.
test_nb_fun_call()
scipy.optimize.tests.test__dual_annealing.TestDualAnnealing.test_nb_fun_call (self)
Definition at line 128 of file test__dual_annealing.py.
test_nb_fun_call_no_ls()
scipy.optimize.tests.test__dual_annealing.TestDualAnnealing.test_nb_fun_call_no_ls (self)
Definition at line 132 of file test__dual_annealing.py.
test_rand_gen()
scipy.optimize.tests.test__dual_annealing.TestDualAnnealing.test_rand_gen (self)
Definition at line 150 of file test__dual_annealing.py.
test_reproduce()
scipy.optimize.tests.test__dual_annealing.TestDualAnnealing.test_reproduce (self)
Definition at line 141 of file test__dual_annealing.py.
test_reset()
scipy.optimize.tests.test__dual_annealing.TestDualAnnealing.test_reset (self)
Definition at line 99 of file test__dual_annealing.py.
test_visiting_dist_high_temperature()
scipy.optimize.tests.test__dual_annealing.TestDualAnnealing.test_visiting_dist_high_temperature (self, qv)
Definition at line 82 of file test__dual_annealing.py.
test_visiting_stepping()
scipy.optimize.tests.test__dual_annealing.TestDualAnnealing.test_visiting_stepping (self, qv)
Definition at line 66 of file test__dual_annealing.py.
test_wrong_restart_temp()
scipy.optimize.tests.test__dual_annealing.TestDualAnnealing.test_wrong_restart_temp (self)
Definition at line 266 of file test__dual_annealing.py.
Member Data Documentation
func
scipy.optimize.tests.test__dual_annealing.TestDualAnnealing.func = [(-5, 5), (0, np.inf), (-5, 5)]
Definition at line 165 of file test__dual_annealing.py.
Referenced by scipy.special._testutils.FuncData.__repr__(), sklearn.compose._target.TransformedTargetRegressor._fit_transformer(), sklearn.preprocessing._function_transformer.FunctionTransformer._get_function_name(), scipy.special._testutils.FuncData.check(), sklearn.preprocessing._function_transformer.FunctionTransformer.fit(), and sklearn.preprocessing._function_transformer.FunctionTransformer.transform().
hd_bounds
list scipy.optimize.tests.test__dual_annealing.TestDualAnnealing.hd_bounds = self.ld_bounds * 4
Definition at line 31 of file test__dual_annealing.py.
high_temperature
int scipy.optimize.tests.test__dual_annealing.TestDualAnnealing.high_temperature = 5230
Definition at line 34 of file test__dual_annealing.py.
ld_bounds
scipy.optimize.tests.test__dual_annealing.TestDualAnnealing.ld_bounds = [(-5.12, 5.12)] * 2
Definition at line 29 of file test__dual_annealing.py.
low_temperature
float scipy.optimize.tests.test__dual_annealing.TestDualAnnealing.low_temperature = 0.1
Definition at line 35 of file test__dual_annealing.py.
nb_fun_call
scipy.optimize.tests.test__dual_annealing.TestDualAnnealing.nb_fun_call = 0
Definition at line 39 of file test__dual_annealing.py.
nbtestvalues
int scipy.optimize.tests.test__dual_annealing.TestDualAnnealing.nbtestvalues = 5000
Definition at line 33 of file test__dual_annealing.py.
ngev
int scipy.optimize.tests.test__dual_annealing.TestDualAnnealing.ngev = 0
Definition at line 40 of file test__dual_annealing.py.
qv
float scipy.optimize.tests.test__dual_annealing.TestDualAnnealing.qv = 2.62
Definition at line 36 of file test__dual_annealing.py.
rs
scipy.optimize.tests.test__dual_annealing.TestDualAnnealing.rs = check_random_state(self.seed)
Definition at line 38 of file test__dual_annealing.py.
seed
int scipy.optimize.tests.test__dual_annealing.TestDualAnnealing.seed = 1234
Definition at line 37 of file test__dual_annealing.py.
weirdfunc
scipy.optimize.tests.test__dual_annealing.TestDualAnnealing.weirdfunc = lambda x: np.inf
Definition at line 27 of file test__dual_annealing.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/optimize/tests/test__dual_annealing.py