Code Cloning Analysis: fontTools.ttLib.tables.V_O_R_G_.VOriginRecord Class Reference
fontTools.ttLib.tables.V_O_R_G_.VOriginRecord Class Reference
Public Member Functions
__init__ (self, name=None, vOrigin=None)
toXML (self, writer, ttFont)
fromXML (self, name, attrs, content, ttFont)
Public Attributes
glyphName = name
vOrigin = vOrigin
Detailed Description
Definition at line 145 of file V_O_R_G_.py.
Constructor & Destructor Documentation
__init__()
fontTools.ttLib.tables.V_O_R_G_.VOriginRecord.__init__ (self, name = None, vOrigin = None)
Definition at line 146 of file V_O_R_G_.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
fromXML()
fontTools.ttLib.tables.V_O_R_G_.VOriginRecord.fromXML (self, name, attrs, content, ttFont)
Definition at line 160 of file V_O_R_G_.py.
toXML()
fontTools.ttLib.tables.V_O_R_G_.VOriginRecord.toXML (self, writer, ttFont)
Definition at line 150 of file V_O_R_G_.py.
Member Data Documentation
glyphName
fontTools.ttLib.tables.V_O_R_G_.VOriginRecord.glyphName = name
Definition at line 147 of file V_O_R_G_.py.
Referenced by fontTools.ufoLib.glifLib.Glyph.drawPoints().
vOrigin
fontTools.ttLib.tables.V_O_R_G_.VOriginRecord.vOrigin = vOrigin
Definition at line 148 of file V_O_R_G_.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ttLib/tables/V_O_R_G_.py