Code Cloning Analysis: numpy.lib.tests.test_arraypad.TestAsPairs Class Reference
numpy.lib.tests.test_arraypad.TestAsPairs Class Reference
Public Member Functions
test_single_value (self)
test_two_values (self)
test_with_none (self)
test_pass_through (self)
test_as_index (self)
test_exceptions (self)
Detailed Description
Definition at line 32 of file test_arraypad.py.
Member Function Documentation
test_as_index()
numpy.lib.tests.test_arraypad.TestAsPairs.test_as_index (self)
Test results if `as_index=True`.
Definition at line 90 of file test_arraypad.py.
References numpy.lib.arraypad._as_pairs().
test_exceptions()
numpy.lib.tests.test_arraypad.TestAsPairs.test_exceptions (self)
Ensure faulty usage is discovered.
Definition at line 105 of file test_arraypad.py.
References numpy.lib.arraypad._as_pairs().
test_pass_through()
numpy.lib.tests.test_arraypad.TestAsPairs.test_pass_through (self)
Test if `x` already matching desired output are passed through.
Definition at line 82 of file test_arraypad.py.
References numpy.lib.arraypad._as_pairs(), and numpy.core.fromnumeric.reshape().
test_single_value()
numpy.lib.tests.test_arraypad.TestAsPairs.test_single_value (self)
Test casting for a single value.
Definition at line 33 of file test_arraypad.py.
References numpy.lib.arraypad._as_pairs().
test_two_values()
numpy.lib.tests.test_arraypad.TestAsPairs.test_two_values (self)
Test proper casting for two different values.
Definition at line 46 of file test_arraypad.py.
References numpy.lib.arraypad._as_pairs().
test_with_none()
numpy.lib.tests.test_arraypad.TestAsPairs.test_with_none (self)
Definition at line 71 of file test_arraypad.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/lib/tests/test_arraypad.py