Code Cloning Analysis: fontTools.voltLib.__main__ Namespace Reference
fontTools.voltLib.__main__ Namespace Reference
Functions
invalid_fea_glyph_name (name)
sanitize_glyph_name (name)
main (args=None)
Variables
log = logging.getLogger("fontTools.feaLib")
SUPPORTED_TABLES = TABLES + ["cmap"]
Function Documentation
invalid_fea_glyph_name()
fontTools.voltLib.__main__.invalid_fea_glyph_name (name)
Check if the glyph name is valid according to FEA syntax.
Definition at line 21 of file __main__.py.
Referenced by main().
main()
fontTools.voltLib.__main__.main (args = None)
Build tables from a MS VOLT project into an OTF font
Definition at line 44 of file __main__.py.
References invalid_fea_glyph_name(), and sanitize_glyph_name().
sanitize_glyph_name()
fontTools.voltLib.__main__.sanitize_glyph_name (name)
Sanitize the glyph name to ensure it is valid according to FEA syntax.
Definition at line 30 of file __main__.py.
Referenced by main().
Variable Documentation
log
fontTools.voltLib.__main__.log = logging.getLogger("fontTools.feaLib")
Definition at line 16 of file __main__.py.
SUPPORTED_TABLES
fontTools.voltLib.__main__.SUPPORTED_TABLES = TABLES + ["cmap"]
Definition at line 18 of file __main__.py.