Code Cloning Analysis: numpy.core._type_aliases Namespace Reference
numpy.core._type_aliases Namespace Reference
Functions
_bits_of (obj)
bitname (obj)
_add_types ()
_add_aliases ()
_add_integer_aliases ()
_set_up_aliases ()
_add_array_type (typename, bits)
_set_array_types ()
Variables
dict sctypeDict = {}
dict allTypes = {}
dict _abstract_types = {}
dict _concrete_typeinfo = {}
k = english_lower(k)
dict _concrete_types = {v.type for k, v in _concrete_typeinfo.items()}
list _int_ctypes = ['long', 'longlong', 'int', 'short', 'byte']
_uint_ctypes = list('u' + t for t in _int_ctypes)
dict void = allTypes['void']
dict sctypes
list _toadd
Detailed Description
Due to compatibility, numpy has a very large number of different naming
conventions for the scalar types (those subclassing from `numpy.generic`).
This file produces a convoluted set of dictionaries mapping names to types,
and sometimes other mappings too.
.. data:: allTypes
    A dictionary of names to types that will be exposed as attributes through
    ``np.core.numerictypes.*``
.. data:: sctypeDict
    Similar to `allTypes`, but maps a broader set of aliases to their types.
.. data:: sctypes
    A dictionary keyed by a "type group" string, providing a list of types
    under that group.
Function Documentation
_add_aliases()
numpy.core._type_aliases._add_aliases () protected
Definition at line 94 of file _type_aliases.py.
_add_array_type()
numpy.core._type_aliases._add_array_type (typename, bits) protected
Definition at line 203 of file _type_aliases.py.
_add_integer_aliases()
numpy.core._type_aliases._add_integer_aliases () protected
Definition at line 123 of file _type_aliases.py.
_add_types()
numpy.core._type_aliases._add_types () protected
Definition at line 74 of file _type_aliases.py.
_bits_of()
numpy.core._type_aliases._bits_of (obj) protected
Definition at line 44 of file _type_aliases.py.
_set_array_types()
numpy.core._type_aliases._set_array_types () protected
Definition at line 211 of file _type_aliases.py.
_set_up_aliases()
numpy.core._type_aliases._set_up_aliases () protected
Definition at line 151 of file _type_aliases.py.
bitname()
numpy.core._type_aliases.bitname (obj)
Return a bit-width name for a given type object
Definition at line 58 of file _type_aliases.py.
References numpy.lib.function_base.append(), bitname(), and numpy.lib.function_base.insert().
Referenced by bitname().
Variable Documentation
_abstract_types
dict numpy.core._type_aliases._abstract_types = {} protected
Definition at line 31 of file _type_aliases.py.
_concrete_typeinfo
dict numpy.core._type_aliases._concrete_typeinfo = {} protected
Definition at line 32 of file _type_aliases.py.
_concrete_types
dict numpy.core._type_aliases._concrete_types = {v.type for k, v in _concrete_typeinfo.items()} protected
Definition at line 41 of file _type_aliases.py.
_int_ctypes
list numpy.core._type_aliases._int_ctypes = ['long', 'longlong', 'int', 'short', 'byte'] protected
Definition at line 91 of file _type_aliases.py.
_toadd
list numpy.core._type_aliases._toadd protected
Initial value:
=  ['int', 'float', 'complex', 'bool', 'object',
          'str', 'bytes', ('a', 'bytes_'),
          ('int0', 'intp'), ('uint0', 'uintp')]
Definition at line 235 of file _type_aliases.py.
_uint_ctypes
numpy.core._type_aliases._uint_ctypes = list('u' + t for t in _int_ctypes) protected
Definition at line 92 of file _type_aliases.py.
allTypes
dict numpy.core._type_aliases.allTypes = {}
Definition at line 27 of file _type_aliases.py.
k
numpy.core._type_aliases.k = english_lower(k)
Definition at line 35 of file _type_aliases.py.
sctypeDict
dict numpy.core._type_aliases.sctypeDict = {}
Definition at line 26 of file _type_aliases.py.
sctypes
dict numpy.core._type_aliases.sctypes
Initial value:
=  {'int': [],
           'uint':[],
           'float':[],
           'complex':[],
           'others':[bool, object, bytes, unicode, void]}
Definition at line 197 of file _type_aliases.py.
void
dict numpy.core._type_aliases.void = allTypes['void']
Definition at line 145 of file _type_aliases.py.