Code Cloning Analysis: pandas.core._numba.extensions.SeriesModel Class Reference
pandas.core._numba.extensions.SeriesModel Class Reference
Public Member Functions
None __init__ (self, dmm, fe_type)
Detailed Description
Definition at line 193 of file extensions.py.
Constructor & Destructor Documentation
__init__()
None pandas.core._numba.extensions.SeriesModel.__init__ (self, dmm, fe_type)
Definition at line 194 of file extensions.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/core/_numba/extensions.py