Code Cloning Analysis: pandas.core.computation.pytables.Term Class Reference
pandas.core.computation.pytables.Term Class Reference
Public Member Functions
__new__ (cls, name, env, side=None, encoding=None)
None __init__ (self, name, PyTablesScope env, side=None, encoding=None)
value (self)
Public Member Functions inherited from pandas.core.computation.ops.Term
__new__ (cls, name, env, side=None, encoding=None)
None __init__ (self, name, env, side=None, encoding=None)
str local_name (self)
str __repr__ (self)
__call__ (self, *args, **kwargs)
Term evaluate (self, *args, **kwargs)
None update (self, value)
bool is_scalar (self)
type (self)
str raw (self)
bool is_datetime (self)
name (self)
int ndim (self)
Protected Member Functions
_resolve_name (self)
Additional Inherited Members
Public Attributes inherited from pandas.core.computation.ops.Term
env = env
side = side
is_local = tname.startswith(LOCAL_TAG) or tname in DEFAULT_GLOBALS
encoding = encoding
name
local_name
Static Public Attributes inherited from pandas.core.computation.ops.Term
return_type = type
Protected Attributes inherited from pandas.core.computation.ops.Term
_name = name
_value = self._resolve_name()
Detailed Description
Definition at line 66 of file pytables.py.
Constructor & Destructor Documentation
__init__()
None pandas.core.computation.pytables.Term.__init__ (self, name, PyTablesScope env, side = None, encoding = None)
Definition at line 76 of file pytables.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__new__()
pandas.core.computation.pytables.Term.__new__ (cls, name, env, side = None, encoding = None)
Definition at line 69 of file pytables.py.
Referenced by matplotlib.path.Path._fast_from_codes_and_verts(), pandas.core.generic.NDFrame._from_mgr(), pandas.core.arrays.string_.StringArray._from_sequence(), scipy.interpolate._fitpack2._BivariateSplineBase._from_tck(), scipy.interpolate._fitpack2.UnivariateSpline._from_tck(), matplotlib.colors.Colormap._get_rgba_and_mask(), pip._vendor.rich.style.Style.clear_meta_and_links(), matplotlib.colors.MultivarColormap.copy(), pip._vendor.rich.style.Style.copy(), pip._vendor.rich.style.Style.from_color(), pip._vendor.rich.json.JSON.from_data(), pip._vendor.rich.style.Style.from_meta(), matplotlib.colors.BivarColormap.lut(), pip._vendor.rich.style.Style.test(), pip._vendor.rich.style.Style.update_link(), and pip._vendor.rich.style.Style.without_color().
_resolve_name()
pandas.core.computation.pytables.Term._resolve_name (self) protected
Reimplemented from pandas.core.computation.ops.Term.
Definition at line 79 of file pytables.py.
value()
pandas.core.computation.pytables.Term.value (self)
Reimplemented from pandas.core.computation.ops.Term.
Definition at line 95 of file pytables.py.
Referenced by sklearn.externals.array_api_extra._lib._at._AtOp.__str__(), pip._internal.models.link.LinkHash.as_hashes(), pip._internal.models.link.LinkHash.find_hash_url_fragment(), and pip._internal.models.link.LinkHash.is_hash_allowed().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/core/computation/pytables.py