Code Cloning Analysis: sklearn.externals.array_api_compat.common._aliases Namespace Reference
sklearn.externals.array_api_compat.common._aliases Namespace Reference
Classes
class UniqueAllResult
class UniqueCountsResult
class UniqueInverseResult
Functions
Array arange (float start, float|None stop=None, float step=1, *, Namespace xp, DType|None dtype=None, Device|None device=None, **object kwargs)
Array empty (int|tuple[int,...] shape, Namespace xp, *, DType|None dtype=None, Device|None device=None, **object kwargs)
Array empty_like (Array x, Namespace xp, *, DType|None dtype=None, Device|None device=None, **object kwargs)
Array eye (int n_rows, int|None n_cols=None, *, Namespace xp, int k=0, DType|None dtype=None, Device|None device=None, **object kwargs)
Array full (int|tuple[int,...] shape, complex fill_value, Namespace xp, *, DType|None dtype=None, Device|None device=None, **object kwargs)
Array full_like (Array x, complex fill_value, *, Namespace xp, DType|None dtype=None, Device|None device=None, **object kwargs)
Array linspace (float start, float stop, int num, *, Namespace xp, DType|None dtype=None, Device|None device=None, bool endpoint=True, **object kwargs)
Array ones (int|tuple[int,...] shape, Namespace xp, *, DType|None dtype=None, Device|None device=None, **object kwargs)
Array ones_like (Array x, Namespace xp, *, DType|None dtype=None, Device|None device=None, **object kwargs)
Array zeros (int|tuple[int,...] shape, Namespace xp, *, DType|None dtype=None, Device|None device=None, **object kwargs)
Array zeros_like (Array x, Namespace xp, *, DType|None dtype=None, Device|None device=None, **object kwargs)
dict[str, bool] _unique_kwargs (Namespace xp)
UniqueAllResult unique_all (Array x, Namespace xp)
UniqueCountsResult unique_counts (Array x, Namespace xp)
UniqueInverseResult unique_inverse (Array x, Namespace xp)
Array unique_values (Array x, Namespace xp)
Array std (Array x, Namespace xp, *, int|tuple[int,...]|None axis=None, float correction=0.0, bool keepdims=False, **object kwargs)
Array var (Array x, Namespace xp, *, int|tuple[int,...]|None axis=None, float correction=0.0, bool keepdims=False, **object kwargs)
Array cumulative_sum (Array x, Namespace xp, *, int|None axis=None, DType|None dtype=None, bool include_initial=False, **object kwargs)
Array cumulative_prod (Array x, Namespace xp, *, int|None axis=None, DType|None dtype=None, bool include_initial=False, **object kwargs)
Array clip (Array x, float|Array|None min=None, float|Array|None max=None, *, Namespace xp, Array|None out=None)
Array permute_dims (Array x, tuple[int,...] axes, Namespace xp)
Array reshape (Array x, tuple[int,...] shape, Namespace xp, *, Optional[bool] copy=None, **object kwargs)
Array argsort (Array x, Namespace xp, *, int axis=-1, bool descending=False, bool stable=True, **object kwargs)
Array sort (Array x, Namespace xp, *, int axis=-1, bool descending=False, bool stable=True, **object kwargs)
tuple[Array,...] nonzero (Array x, Namespace xp, **object kwargs)
Array ceil (Array x, Namespace xp, **object kwargs)
Array floor (Array x, Namespace xp, **object kwargs)
Array trunc (Array x, Namespace xp, **object kwargs)
Array matmul (Array x1, Array x2, Namespace xp, **object kwargs)
Array matrix_transpose (Array x, Namespace xp)
Array tensordot (Array x1, Array x2, Namespace xp, *, int|tuple[Sequence[int], Sequence[int]] axes=2, **object kwargs)
Array vecdot (Array x1, Array x2, Namespace xp, *, int axis=-1)
bool isdtype (DType dtype, DType|str|tuple[DType|str,...] kind, Namespace xp, *, bool _tuple=True)
tuple[Array,...] unstack (Array x, Namespace xp, *, int axis=0)
Array sign (Array x, Namespace xp, **object kwargs)
Any finfo (DType|Array type_, Namespace xp)
Any iinfo (DType|Array type_, Namespace xp)
list[str] __dir__ ()
Variables
list __all__
list _all_ignore = ["inspect", "array_namespace", "NamedTuple"]
Detailed Description
These are functions that are just aliases of existing functions in NumPy.
Function Documentation
__dir__()
list[str] sklearn.externals.array_api_compat.common._aliases.__dir__ ()
Definition at line 726 of file _aliases.py.
_unique_kwargs()
dict[str, bool] sklearn.externals.array_api_compat.common._aliases._unique_kwargs (Namespace xp) protected
Definition at line 199 of file _aliases.py.
arange()
Array sklearn.externals.array_api_compat.common._aliases.arange (float start, float | None stop = None, float step = 1, * , Namespace xp, DType | None dtype = None, Device | None device = None, **object kwargs)
Definition at line 24 of file _aliases.py.
argsort()
Array sklearn.externals.array_api_compat.common._aliases.argsort (Array x, Namespace xp, * , int axis = -1, bool descending = False, bool stable = True, **object kwargs)
Definition at line 467 of file _aliases.py.
ceil()
Array sklearn.externals.array_api_compat.common._aliases.ceil (Array x, Namespace xp, **object kwargs)
Definition at line 530 of file _aliases.py.
clip()
Array sklearn.externals.array_api_compat.common._aliases.clip (Array x, float | Array | None min = None, float | Array | None max = None, * , Namespace xp, Array | None out = None)
Definition at line 374 of file _aliases.py.
cumulative_prod()
Array sklearn.externals.array_api_compat.common._aliases.cumulative_prod (Array x, Namespace xp, * , int | None axis = None, DType | None dtype = None, bool include_initial = False, **object kwargs)
Definition at line 335 of file _aliases.py.
cumulative_sum()
Array sklearn.externals.array_api_compat.common._aliases.cumulative_sum (Array x, Namespace xp, * , int | None axis = None, DType | None dtype = None, bool include_initial = False, **object kwargs)
Definition at line 297 of file _aliases.py.
empty()
Array sklearn.externals.array_api_compat.common._aliases.empty (int | tuple[int, ...] shape, Namespace xp, * , DType | None dtype = None, Device | None device = None, **object kwargs)
Definition at line 39 of file _aliases.py.
empty_like()
Array sklearn.externals.array_api_compat.common._aliases.empty_like (Array x, Namespace xp, * , DType | None dtype = None, Device | None device = None, **object kwargs)
Definition at line 51 of file _aliases.py.
eye()
Array sklearn.externals.array_api_compat.common._aliases.eye (int n_rows, int | None n_cols = None, * , Namespace xp, int k = 0, DType | None dtype = None, Device | None device = None, **object kwargs)
Definition at line 64 of file _aliases.py.
finfo()
Any sklearn.externals.array_api_compat.common._aliases.finfo (DType | Array type_, Namespace xp)
Definition at line 665 of file _aliases.py.
floor()
Array sklearn.externals.array_api_compat.common._aliases.floor (Array x, Namespace xp, **object kwargs)
Definition at line 536 of file _aliases.py.
full()
Array sklearn.externals.array_api_compat.common._aliases.full (int | tuple[int, ...] shape, complex fill_value, Namespace xp, * , DType | None dtype = None, Device | None device = None, **object kwargs)
Definition at line 79 of file _aliases.py.
full_like()
Array sklearn.externals.array_api_compat.common._aliases.full_like (Array x, complex fill_value, * , Namespace xp, DType | None dtype = None, Device | None device = None, **object kwargs)
Definition at line 92 of file _aliases.py.
iinfo()
Any sklearn.externals.array_api_compat.common._aliases.iinfo (DType | Array type_, Namespace xp)
Definition at line 674 of file _aliases.py.
isdtype()
bool sklearn.externals.array_api_compat.common._aliases.isdtype (DType dtype, DType | str | tuple[DType | str, ...] kind, Namespace xp, * , bool _tuple = True)
Returns a boolean indicating whether a provided dtype is of a specified data type ``kind``.
Note that outside of this function, this compat library does not yet fully
support complex numbers.
See
https://data-apis.org/array-api/latest/API_specification/generated/array_api.isdtype.html
for more details
Definition at line 594 of file _aliases.py.
References isdtype().
Referenced by isdtype(), and sklearn.externals.array_api_compat.torch._aliases.isdtype().
linspace()
Array sklearn.externals.array_api_compat.common._aliases.linspace (float start, float stop, int num, * , Namespace xp, DType | None dtype = None, Device | None device = None, bool endpoint = True, **object kwargs)
Definition at line 106 of file _aliases.py.
matmul()
Array sklearn.externals.array_api_compat.common._aliases.matmul (Array x1, Array x2, Namespace xp, **object kwargs)
Definition at line 551 of file _aliases.py.
matrix_transpose()
Array sklearn.externals.array_api_compat.common._aliases.matrix_transpose (Array x, Namespace xp)
Definition at line 556 of file _aliases.py.
nonzero()
tuple[Array, ...] sklearn.externals.array_api_compat.common._aliases.nonzero (Array x, Namespace xp, **object kwargs)
Definition at line 521 of file _aliases.py.
ones()
Array sklearn.externals.array_api_compat.common._aliases.ones (int | tuple[int, ...] shape, Namespace xp, * , DType | None dtype = None, Device | None device = None, **object kwargs)
Definition at line 122 of file _aliases.py.
ones_like()
Array sklearn.externals.array_api_compat.common._aliases.ones_like (Array x, Namespace xp, * , DType | None dtype = None, Device | None device = None, **object kwargs)
Definition at line 134 of file _aliases.py.
permute_dims()
Array sklearn.externals.array_api_compat.common._aliases.permute_dims (Array x, tuple[int, ...] axes, Namespace xp)
Definition at line 442 of file _aliases.py.
reshape()
Array sklearn.externals.array_api_compat.common._aliases.reshape (Array x, tuple[int, ...] shape, Namespace xp, * , Optional[bool] copy = None, **object kwargs)
Definition at line 447 of file _aliases.py.
sign()
Array sklearn.externals.array_api_compat.common._aliases.sign (Array x, Namespace xp, **object kwargs)
Definition at line 651 of file _aliases.py.
sort()
Array sklearn.externals.array_api_compat.common._aliases.sort (Array x, Namespace xp, * , int axis = -1, bool descending = False, bool stable = True, **object kwargs)
Definition at line 499 of file _aliases.py.
std()
Array sklearn.externals.array_api_compat.common._aliases.std (Array x, Namespace xp, * , int | tuple[int, ...] | None axis = None, float correction = 0.0, bool keepdims = False, **object kwargs)
Definition at line 267 of file _aliases.py.
tensordot()
Array sklearn.externals.array_api_compat.common._aliases.tensordot (Array x1, Array x2, Namespace xp, * , int | tuple[Sequence[int], Sequence[int]] axes = 2, **object kwargs)
Definition at line 562 of file _aliases.py.
trunc()
Array sklearn.externals.array_api_compat.common._aliases.trunc (Array x, Namespace xp, **object kwargs)
Definition at line 542 of file _aliases.py.
unique_all()
UniqueAllResult sklearn.externals.array_api_compat.common._aliases.unique_all (Array x, Namespace xp)
Definition at line 209 of file _aliases.py.
unique_counts()
UniqueCountsResult sklearn.externals.array_api_compat.common._aliases.unique_counts (Array x, Namespace xp)
Definition at line 229 of file _aliases.py.
unique_inverse()
UniqueInverseResult sklearn.externals.array_api_compat.common._aliases.unique_inverse (Array x, Namespace xp)
Definition at line 238 of file _aliases.py.
unique_values()
Array sklearn.externals.array_api_compat.common._aliases.unique_values (Array x, Namespace xp)
Definition at line 253 of file _aliases.py.
unstack()
tuple[Array, ...] sklearn.externals.array_api_compat.common._aliases.unstack (Array x, Namespace xp, * , int axis = 0)
Definition at line 642 of file _aliases.py.
var()
Array sklearn.externals.array_api_compat.common._aliases.var (Array x, Namespace xp, * , int | tuple[int, ...] | None axis = None, float correction = 0.0, bool keepdims = False, **object kwargs)
Definition at line 280 of file _aliases.py.
vecdot()
Array sklearn.externals.array_api_compat.common._aliases.vecdot (Array x1, Array x2, Namespace xp, * , int axis = -1)
Definition at line 574 of file _aliases.py.
zeros()
Array sklearn.externals.array_api_compat.common._aliases.zeros (int | tuple[int, ...] shape, Namespace xp, * , DType | None dtype = None, Device | None device = None, **object kwargs)
Definition at line 147 of file _aliases.py.
zeros_like()
Array sklearn.externals.array_api_compat.common._aliases.zeros_like (Array x, Namespace xp, * , DType | None dtype = None, Device | None device = None, **object kwargs)
Definition at line 159 of file _aliases.py.
Variable Documentation
__all__
list sklearn.externals.array_api_compat.common._aliases.__all__ private
Definition at line 681 of file _aliases.py.
_all_ignore
list sklearn.externals.array_api_compat.common._aliases._all_ignore = ["inspect", "array_namespace", "NamedTuple"] protected
Definition at line 723 of file _aliases.py.