Code Cloning Analysis: fontTools.voltLib.voltToFea.Lookup Class Reference
fontTools.voltLib.voltToFea.Lookup Class Reference
Public Member Functions
__init__ (self, name, use_extension=False, location=None)
Public Member Functions inherited from fontTools.feaLib.ast.LookupBlock
__init__ (self, name, use_extension=False, location=None)
build (self, builder)
asFea (self, indent="")
Public Member Functions inherited from fontTools.feaLib.ast.Block
__init__ (self, location=None)
Public Member Functions inherited from fontTools.feaLib.ast.Element
__init__ (self, location=None)
__str__ (self)
Public Attributes
list chained = []
Public Attributes inherited from fontTools.feaLib.ast.LookupBlock
name
use_extension = name, use_extension
Public Attributes inherited from fontTools.feaLib.ast.Block
list statements = []
Public Attributes inherited from fontTools.feaLib.ast.Element
location = location
Detailed Description
Definition at line 90 of file voltToFea.py.
Constructor & Destructor Documentation
__init__()
fontTools.voltLib.voltToFea.Lookup.__init__ (self, name, use_extension = False, location = None)
Definition at line 91 of file voltToFea.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Data Documentation
chained
list fontTools.voltLib.voltToFea.Lookup.chained = []
Definition at line 93 of file voltToFea.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/voltLib/voltToFea.py