Code Cloning Analysis: matplotlib._api Namespace Reference
matplotlib._api Namespace Reference
Namespaces
namespace deprecation
Classes
class classproperty
Functions
check_isinstance (types, **kwargs)
check_in_list (values, *, _print_supported_values=True, **kwargs)
check_shape (shape, **kwargs)
check_getitem (mapping, **kwargs)
caching_module_getattr (cls)
define_aliases (alias_d, cls=None)
select_matching_signature (funcs, *args, **kwargs)
nargs_error (name, takes, given)
kwarg_error (name, kw)
recursive_subclasses (cls)
warn_external (message, category=None)
Variables
str __name__ = "__getattr__"
dict _alias_map = {**preexisting_aliases, **alias_d}
Detailed Description
Helper functions for managing the Matplotlib API.
This documentation is only relevant for Matplotlib developers, not for users.
.. warning::
    This module and its submodules are for internal use only.  Do not use them
    in your own code.  We may change the API at any time with no warning.
Function Documentation
caching_module_getattr()
matplotlib._api.caching_module_getattr (cls)
Helper decorator for implementing module-level ``__getattr__`` as a class.
This decorator must be used at the module toplevel as follows::
    @caching_module_getattr
    class __getattr__:  # The class *must* be named ``__getattr__``.
        @property  # Only properties are taken into account.
        def name(self): ...
The ``__getattr__`` class will be replaced by a ``__getattr__``
function such that trying to access ``name`` on the module will
resolve the corresponding property (which may be decorated e.g. with
``_api.deprecated`` for deprecating module globals).  The properties are
all implicitly cached.  Moreover, a suitable AttributeError is generated
and raised if no property with the given name exists.
Definition at line 189 of file __init__.py.
check_getitem()
matplotlib._api.check_getitem (mapping, ** kwargs)
*kwargs* must consist of a single *key, value* pair.  If *key* is in
*mapping*, return ``mapping[value]``; else, raise an appropriate
ValueError.
Examples
--------
>>> _api.check_getitem({"foo": "bar"}, arg=arg)
Definition at line 168 of file __init__.py.
check_in_list()
matplotlib._api.check_in_list (values, * , _print_supported_values = True, ** kwargs)
For each *key, value* pair in *kwargs*, check that *value* is in *values*;
if not, raise an appropriate ValueError.
Parameters
----------
values : iterable
    Sequence of values to check on.
_print_supported_values : bool, default: True
    Whether to print *values* when raising ValueError.
**kwargs : dict
    *key, value* pairs as keyword arguments to find in *values*.
Raises
------
ValueError
    If any *value* in *kwargs* is not found in *values*.
Examples
--------
>>> _api.check_in_list(["foo", "bar"], arg=arg, other_arg=other_arg)
Definition at line 100 of file __init__.py.
check_isinstance()
matplotlib._api.check_isinstance (types, ** kwargs)
For each *key, value* pair in *kwargs*, check that *value* is an instance
of one of *types*; if not, raise an appropriate TypeError.
As a special case, a ``None`` entry in *types* is treated as NoneType.
Examples
--------
>>> _api.check_isinstance((SomeClass, None), arg=arg)
Definition at line 65 of file __init__.py.
check_shape()
matplotlib._api.check_shape (shape, ** kwargs)
For each *key, value* pair in *kwargs*, check that *value* has the shape *shape*;
if not, raise an appropriate ValueError.
*None* in the shape is treated as a "free" size that can have any length.
e.g. (None, 2) -> (N, 2)
The values checked must be numpy arrays.
Examples
--------
To check for (N, 2) shaped arrays
>>> _api.check_shape((None, 2), arg=arg, other_arg=other_arg)
Definition at line 133 of file __init__.py.
define_aliases()
matplotlib._api.define_aliases (alias_d, cls = None)
Class decorator for defining property aliases.
Use as ::
    @_api.define_aliases({"property": ["alias", ...], ...})
    class C: ...
For each property, if the corresponding ``get_property`` is defined in the
class so far, an alias named ``get_alias`` will be defined; the same will
be done for setters.  If neither the getter nor the setter exists, an
exception will be raised.
The alias map is stored as the ``_alias_map`` attribute on the class and
can be used by `.normalize_kwargs` (which assumes that higher priority
aliases come last).
Definition at line 224 of file __init__.py.
kwarg_error()
matplotlib._api.kwarg_error (name, kw)
Generate a TypeError to be raised by function calls with wrong kwarg.
Parameters
----------
name : str
    The name of the calling function.
kw : str or Iterable[str]
    Either the invalid keyword argument name, or an iterable yielding
    invalid keyword arguments (e.g., a ``kwargs`` dict).
Definition at line 337 of file __init__.py.
nargs_error()
matplotlib._api.nargs_error (name, takes, given)
Generate a TypeError to be raised by function calls with wrong arity.
Definition at line 331 of file __init__.py.
recursive_subclasses()
matplotlib._api.recursive_subclasses (cls)
Yield *cls* and direct and indirect subclasses of *cls*.
Definition at line 354 of file __init__.py.
References recursive_subclasses().
Referenced by recursive_subclasses().
select_matching_signature()
matplotlib._api.select_matching_signature (funcs, * args, ** kwargs)
Select and call the function that accepts ``*args, **kwargs``.
*funcs* is a list of functions which should not raise any exception (other
than `TypeError` if the arguments passed do not match their signature).
`select_matching_signature` tries to call each of the functions in *funcs*
with ``*args, **kwargs`` (in the order in which they are given).  Calls
that fail with a `TypeError` are silently skipped.  As soon as a call
succeeds, `select_matching_signature` returns its return value.  If no
function accepts ``*args, **kwargs``, then the `TypeError` raised by the
last failing call is re-raised.
Callers should normally make sure that any ``*args, **kwargs`` can only
bind a single *func* (to avoid any ambiguity), although this is not checked
by `select_matching_signature`.
Notes
-----
`select_matching_signature` is intended to help implementing
signature-overloaded functions.  In general, such functions should be
avoided, except for back-compatibility concerns.  A typical use pattern is
::
    def my_func(*args, **kwargs):
        params = select_matching_signature(
            [lambda old1, old2: locals(), lambda new: locals()],
            *args, **kwargs)
        if "old1" in params:
            warn_deprecated(...)
            old1, old2 = params.values()  # note that locals() is ordered.
        else:
            new, = params.values()
        # do things with params
which allows *my_func* to be called either with two parameters (*old1* and
*old2*) or a single one (*new*).  Note that the new signature is given
last, so that callers get a `TypeError` corresponding to the new signature
if the arguments they passed in do not match any signature.
Definition at line 279 of file __init__.py.
warn_external()
matplotlib._api.warn_external (message, category = None)
`warnings.warn` wrapper that sets *stacklevel* to "outside Matplotlib".
The original emitter of the warning can be obtained by patching this
function back to `warnings.warn`, i.e. ``_api.warn_external =
warnings.warn`` (or ``functools.partial(warnings.warn, stacklevel=2)``,
etc.).
Definition at line 361 of file __init__.py.
Referenced by matplotlib._api.deprecation.warn_deprecated().
Variable Documentation
__name__
str matplotlib._api.__name__ = "__getattr__" private
Definition at line 208 of file __init__.py.
_alias_map
dict matplotlib._api._alias_map = {**preexisting_aliases, **alias_d} protected
Definition at line 275 of file __init__.py.