Code Cloning Analysis: numpy.core.getlimits Namespace Reference
numpy.core.getlimits Namespace Reference
Classes
class finfo
class iinfo
class MachArLike
Functions
_fr0 (a)
_fr1 (a)
_register_type (machar, bytepat)
_register_known_types ()
_get_machar (ftype)
_discovered_machar (ftype)
Variables
list __all__ = ['finfo', 'iinfo']
dict _convert_to_float
str _title_fmt = 'numpy {} precision floating point number'
dict _MACHAR_PARAMS
dict _KNOWN_TYPES = {}
dict _float_ma = {}
Detailed Description
Machine limits for Float32 and Float64 and (long double) if available...
Function Documentation
_discovered_machar()
numpy.core.getlimits._discovered_machar (ftype) protected
 Create MachAr instance with found information on float types
TODO: MachAr should be retired completely ideally.  We currently only
      ever use it system with broken longdouble (valgrind, WSL).
Definition at line 364 of file getlimits.py.
References _fr0().
Referenced by _get_machar(), and numpy.core.tests.test_getlimits.test_subnormal_warning().
_fr0()
numpy.core.getlimits._fr0 (a) protected
fix rank-0 --> rank-1
Definition at line 16 of file getlimits.py.
Referenced by _discovered_machar(), and numpy.core.getlimits.MachArLike._float_to_str().
_fr1()
numpy.core.getlimits._fr1 (a) protected
fix rank > 0 --> rank-0
Definition at line 24 of file getlimits.py.
Referenced by numpy.core.getlimits.MachArLike._float_to_float().
_get_machar()
numpy.core.getlimits._get_machar (ftype) protected
 Get MachAr instance or MachAr-like instance
Get parameters for floating point type, by first trying signatures of
various known floating point types, then, if none match, attempting to
identify parameters by analysis.
Parameters
----------
ftype : class
    Numpy floating point type class (e.g. ``np.float64``)
Returns
-------
ma_like : instance of :class:`MachAr` or :class:`MachArLike`
    Object giving floating point parameters for `ftype`.
Warns
-----
UserWarning
    If the binary signature of the float type is not in the dictionary of
    known float types.
Definition at line 307 of file getlimits.py.
References _discovered_machar().
_register_known_types()
numpy.core.getlimits._register_known_types () protected
Definition at line 162 of file getlimits.py.
_register_type()
numpy.core.getlimits._register_type (machar, bytepat) protected
Definition at line 157 of file getlimits.py.
Variable Documentation
__all__
list numpy.core.getlimits.__all__ = ['finfo', 'iinfo'] private
Definition at line 4 of file getlimits.py.
_convert_to_float
dict numpy.core.getlimits._convert_to_float protected
Initial value:
=  {
    ntypes.csingle: ntypes.single,
    ntypes.complex_: ntypes.float_,
    ntypes.clongfloat: ntypes.longfloat
    }
Definition at line 122 of file getlimits.py.
_float_ma
dict numpy.core.getlimits._float_ma = {} protected
Definition at line 159 of file getlimits.py.
_KNOWN_TYPES
dict numpy.core.getlimits._KNOWN_TYPES = {} protected
Definition at line 156 of file getlimits.py.
_MACHAR_PARAMS
dict numpy.core.getlimits._MACHAR_PARAMS protected
Initial value:
=  {
    ntypes.double: dict(
        itype = ntypes.int64,
        fmt = '%24.16e',
        title = _title_fmt.format('double')),
    ntypes.single: dict(
        itype = ntypes.int32,
        fmt = '%15.7e',
        title = _title_fmt.format('single')),
    ntypes.longdouble: dict(
        itype = ntypes.longlong,
        fmt = '%s',
        title = _title_fmt.format('long double')),
    ntypes.half: dict(
        itype = ntypes.int16,
        fmt = '%12.5e',
        title = _title_fmt.format('half'))}
Definition at line 130 of file getlimits.py.
_title_fmt
str numpy.core.getlimits._title_fmt = 'numpy {} precision floating point number' protected
Definition at line 129 of file getlimits.py.