Code Cloning Analysis: fontTools.varLib.merger Namespace Reference
fontTools.varLib.merger Namespace Reference
Classes
class AligningMerger
class COLRVariationMerger
class InstancerMerger
class Merger
class MutatorMerger
class VariationMerger
Functions
merge (merger, self, lst)
_SinglePosUpgradeToFormat2 (self)
_merge_GlyphOrders (font, lst, values_lst=None, default=None)
_Lookup_SinglePos_get_effective_value (merger, subtables, glyph)
_Lookup_PairPos_get_effective_value_pair (merger, subtables, firstGlyph, secondGlyph)
_PairPosFormat1_merge (self, lst, merger)
_ClassDef_invert (self, allGlyphs=None)
_ClassDef_merge_classify (lst, allGlyphses=None)
_PairPosFormat2_align_matrices (self, lst, font, transparent=False)
_PairPosFormat2_merge (self, lst, merger)
_MarkBasePosFormat1_merge (self, lst, merger, Mark="Mark", Base="Base")
_PairSet_flatten (lst, font)
_Lookup_PairPosFormat1_subtables_flatten (lst, font)
_Lookup_PairPosFormat2_subtables_flatten (lst, font)
_Lookup_PairPos_subtables_canonicalize (lst, font)
_Lookup_SinglePos_subtables_flatten (lst, font, min_inclusive_rec_format)
buildVarDevTable (store_builder, master_values)
_flatten_layers (root, colr)
_merge_PaintColrLayers (self, out, lst)
Variables
log = logging.getLogger("fontTools.varLib.merger")
dict classDefs = {}
int Format = 2:
__dict__ = lst[0].__dict__.copy()
ValueFormat = reduce(int.__or__, [l.ValueFormat for l in lst], 0)
list Value = otBase.ValueRecord(valueFormat, self.Value)
ValueCount = len(self.Value)
list PairValueRecord = []
PairValueCount = len(self.PairValueRecord)
list PairSet = [ot.PairSet() for _ in glyphs]
PairSetCount = len(self.PairSet)
ClassDef1
Class1Count = len(classes)
ClassDef2 = new_matrices
Class2Count = len(classes)
Class1Record = list(matrices[0])
ValueFormat1 = vf1
ValueFormat2 = vf2
ClassCount = max(l.ClassCount for l in lst)
Coverage = ot.Coverage()
list EntryExitRecord = []
EntryExitCount = len(self.EntryExitRecord)
EntryAnchor = None
ExitAnchor = None
SubTable = False
SubTableCount = len(self.SubTable)
Coordinate
XCoordinate
YCoordinate
DeviceTable = DeviceTable
XDeviceTable = XDeviceTable
YDeviceTable = YDeviceTable
LayerCount = len(merger.layers)
Paint = merger.layers
ttfs
VarIndexBase = varIndexBase
ColorStop
Detailed Description
Merge OpenType Layout tables (GDEF / GPOS / GSUB).
Function Documentation
_ClassDef_invert()
fontTools.varLib.merger._ClassDef_invert (self, allGlyphs = None) protected
Definition at line 457 of file merger.py.
_ClassDef_merge_classify()
fontTools.varLib.merger._ClassDef_merge_classify (lst, allGlyphses = None) protected
Definition at line 485 of file merger.py.
_flatten_layers()
fontTools.varLib.merger._flatten_layers (root, colr) protected
Definition at line 1569 of file merger.py.
_Lookup_PairPos_get_effective_value_pair()
fontTools.varLib.merger._Lookup_PairPos_get_effective_value_pair (merger, subtables, firstGlyph, secondGlyph) protected
Definition at line 281 of file merger.py.
_Lookup_PairPos_subtables_canonicalize()
fontTools.varLib.merger._Lookup_PairPos_subtables_canonicalize (lst, font) protected
Merge multiple Format1 subtables at the beginning of lst,
and merge multiple consecutive Format2 subtables that have the same
Class2 (ie. were split because of offset overflows).  Returns new list.
Definition at line 871 of file merger.py.
References _Lookup_PairPos_subtables_canonicalize(), and _merge_GlyphOrders().
Referenced by _Lookup_PairPos_subtables_canonicalize().
_Lookup_PairPosFormat1_subtables_flatten()
fontTools.varLib.merger._Lookup_PairPosFormat1_subtables_flatten (lst, font) protected
Definition at line 816 of file merger.py.
_Lookup_PairPosFormat2_subtables_flatten()
fontTools.varLib.merger._Lookup_PairPosFormat2_subtables_flatten (lst, font) protected
Definition at line 841 of file merger.py.
_Lookup_SinglePos_get_effective_value()
fontTools.varLib.merger._Lookup_SinglePos_get_effective_value (merger, subtables, glyph) protected
Definition at line 263 of file merger.py.
_Lookup_SinglePos_subtables_flatten()
fontTools.varLib.merger._Lookup_SinglePos_subtables_flatten (lst, font, min_inclusive_rec_format) protected
Definition at line 892 of file merger.py.
_MarkBasePosFormat1_merge()
fontTools.varLib.merger._MarkBasePosFormat1_merge (self, lst, merger, Mark = "Mark", Base = "Base") protected
Definition at line 675 of file merger.py.
_merge_GlyphOrders()
fontTools.varLib.merger._merge_GlyphOrders (font, lst, values_lst = None, default = None) protected
Takes font and list of glyph lists (must be sorted by glyph id), and returns
two things:
- Combined glyph list,
- If values_lst is None, return input glyph lists, but padded with None when a glyph
  was missing in a list.  Otherwise, return values_lst list-of-list, padded with None
  to match combined glyph lists.
Definition at line 210 of file merger.py.
References _merge_GlyphOrders().
Referenced by _Lookup_PairPos_subtables_canonicalize(), and _merge_GlyphOrders().
_merge_PaintColrLayers()
fontTools.varLib.merger._merge_PaintColrLayers (self, out, lst) protected
Definition at line 1578 of file merger.py.
_PairPosFormat1_merge()
fontTools.varLib.merger._PairPosFormat1_merge (self, lst, merger) protected
Definition at line 424 of file merger.py.
_PairPosFormat2_align_matrices()
fontTools.varLib.merger._PairPosFormat2_align_matrices (self, lst, font, transparent = False) protected
Definition at line 512 of file merger.py.
_PairPosFormat2_merge()
fontTools.varLib.merger._PairPosFormat2_merge (self, lst, merger) protected
Definition at line 590 of file merger.py.
_PairSet_flatten()
fontTools.varLib.merger._PairSet_flatten (lst, font) protected
Definition at line 791 of file merger.py.
_SinglePosUpgradeToFormat2()
fontTools.varLib.merger._SinglePosUpgradeToFormat2 (self) protected
Definition at line 196 of file merger.py.
buildVarDevTable()
fontTools.varLib.merger.buildVarDevTable (store_builder, master_values)
Definition at line 1254 of file merger.py.
merge()
fontTools.varLib.merger.merge (merger, self, lst)
Definition at line 171 of file merger.py.
Variable Documentation
__dict__
fontTools.varLib.merger.__dict__ = lst[0].__dict__.copy() private
Definition at line 251 of file merger.py.
Class1Count
fontTools.varLib.merger.Class1Count = len(classes)
Definition at line 519 of file merger.py.
Class1Record
fontTools.varLib.merger.Class1Record = list(matrices[0])
Definition at line 627 of file merger.py.
Class2Count
fontTools.varLib.merger.Class2Count = len(classes)
Definition at line 565 of file merger.py.
ClassCount
fontTools.varLib.merger.ClassCount = max(l.ClassCount for l in lst)
Definition at line 676 of file merger.py.
ClassDef1
fontTools.varLib.merger.ClassDef1
Definition at line 516 of file merger.py.
ClassDef2
fontTools.varLib.merger.ClassDef2 = new_matrices
Definition at line 564 of file merger.py.
classDefs
dict fontTools.varLib.merger.classDefs = {}
Definition at line 178 of file merger.py.
ColorStop
fontTools.varLib.merger.ColorStop
Definition at line 1708 of file merger.py.
Coordinate
fontTools.varLib.merger.Coordinate
Initial value:
=  otRound(
        model.interpolateFromValuesAndScalars(Coords, masterScalars)
    )
Definition at line 1072 of file merger.py.
Coverage
fontTools.varLib.merger.Coverage = ot.Coverage()
Definition at line 793 of file merger.py.
DeviceTable
fontTools.varLib.merger.DeviceTable = DeviceTable
Definition at line 1270 of file merger.py.
EntryAnchor
fontTools.varLib.merger.EntryAnchor = None
Definition at line 943 of file merger.py.
EntryExitCount
fontTools.varLib.merger.EntryExitCount = len(self.EntryExitRecord)
Definition at line 937 of file merger.py.
EntryExitRecord
fontTools.varLib.merger.EntryExitRecord = []
Definition at line 928 of file merger.py.
ExitAnchor
fontTools.varLib.merger.ExitAnchor = None
Definition at line 945 of file merger.py.
Format
fontTools.varLib.merger.Format = 2:
Definition at line 197 of file merger.py.
LayerCount
fontTools.varLib.merger.LayerCount = len(merger.layers)
Definition at line 1565 of file merger.py.
log
fontTools.varLib.merger.log = logging.getLogger("fontTools.varLib.merger")
Definition at line 29 of file merger.py.
Paint
fontTools.varLib.merger.Paint = merger.layers
Definition at line 1566 of file merger.py.
PairSet
fontTools.varLib.merger.PairSet = [ot.PairSet() for _ in glyphs]
Definition at line 449 of file merger.py.
PairSetCount
fontTools.varLib.merger.PairSetCount = len(self.PairSet)
Definition at line 450 of file merger.py.
PairValueCount
fontTools.varLib.merger.PairValueCount = len(self.PairValueRecord)
Definition at line 390 of file merger.py.
PairValueRecord
fontTools.varLib.merger.PairValueRecord = []
Definition at line 379 of file merger.py.
SubTable
fontTools.varLib.merger.SubTable = False
Definition at line 954 of file merger.py.
SubTableCount
fontTools.varLib.merger.SubTableCount = len(self.SubTable)
Definition at line 1006 of file merger.py.
ttfs
fontTools.varLib.merger.ttfs
Definition at line 1586 of file merger.py.
Value
fontTools.varLib.merger.Value = otBase.ValueRecord(valueFormat, self.Value)
Definition at line 319 of file merger.py.
ValueCount
fontTools.varLib.merger.ValueCount = len(self.Value)
Definition at line 342 of file merger.py.
ValueFormat
fontTools.varLib.merger.ValueFormat = reduce(int.__or__, [l.ValueFormat for l in lst], 0)
Definition at line 310 of file merger.py.
ValueFormat1
fontTools.varLib.merger.ValueFormat1 = vf1
Definition at line 671 of file merger.py.
ValueFormat2
fontTools.varLib.merger.ValueFormat2 = vf2
Definition at line 672 of file merger.py.
VarIndexBase
fontTools.varLib.merger.VarIndexBase = varIndexBase
Definition at line 1677 of file merger.py.
XCoordinate
fontTools.varLib.merger.XCoordinate
Initial value:
=  otRound(
        model.interpolateFromValuesAndScalars(XCoords, masterScalars)
    )
Definition at line 1084 of file merger.py.
XDeviceTable
fontTools.varLib.merger.XDeviceTable = XDeviceTable
Definition at line 1297 of file merger.py.
YCoordinate
fontTools.varLib.merger.YCoordinate
Initial value:
=  otRound(
        model.interpolateFromValuesAndScalars(YCoords, masterScalars)
    )
Definition at line 1087 of file merger.py.
YDeviceTable
fontTools.varLib.merger.YDeviceTable = YDeviceTable
Definition at line 1298 of file merger.py.