Code Cloning Analysis: numpy.core.arrayprint.BoolFormat Class Reference
numpy.core.arrayprint.BoolFormat Class Reference
Public Member Functions
__init__ (self, data, **kwargs)
__call__ (self, x)
Public Attributes
tuple truestr = () else 'True'
Detailed Description
Definition at line 1235 of file arrayprint.py.
Constructor & Destructor Documentation
__init__()
numpy.core.arrayprint.BoolFormat.__init__ (self, data, ** kwargs)
Definition at line 1236 of file arrayprint.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__call__()
numpy.core.arrayprint.BoolFormat.__call__ (self, x)
Definition at line 1241 of file arrayprint.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), and scipy.interpolate._fitpack2.SphereBivariateSpline.ev().
Member Data Documentation
truestr
tuple numpy.core.arrayprint.BoolFormat.truestr = () else 'True'
Definition at line 1239 of file arrayprint.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/core/arrayprint.py