Code Cloning Analysis: numpy.ma.core Namespace Reference
numpy.ma.core Namespace Reference
Classes
class _convert2ma
class _DomainCheckInterval
class _DomainedBinaryOperation
class _DomainGreater
class _DomainGreaterEqual
class _DomainSafeDivide
class _DomainTan
class _extrema_operation
Extrema functions #.
class _frommethod
Definition of functions from the corresponding methods #.
class _MaskedBinaryOperation
class _MaskedPrintOption
Printing options #.
class _MaskedUFunc
class _MaskedUnaryOperation
class MAError
Exceptions #.
class MaskedArray
class MaskedArrayFutureWarning
class MaskedConstant
class MaskedIterator
class MaskError
class mvoid
Functions
_deprecate_argsort_axis (arr)
doc_note (initialdoc, note)
get_object_signature (obj)
_recursive_fill_value (dtype, f)
_get_dtype_of (obj)
default_fill_value (obj)
_extremum_fill_value (obj, extremum, extremum_name)
minimum_fill_value (obj)
maximum_fill_value (obj)
_recursive_set_fill_value (fillvalue, dt)
_check_fill_value (fill_value, ndtype)
set_fill_value (a, fill_value)
get_fill_value (a)
common_fill_value (a, b)
filled (a, fill_value=None)
get_masked_subclass (*arrays)
getdata (a, subok=True)
fix_invalid (a, mask=nomask, copy=True, fill_value=None)
is_string_or_list_of_strings (val)
_replace_dtype_fields_recursive (dtype, primitive_dtype)
Mask creation functions #.
_replace_dtype_fields (dtype, primitive_dtype)
make_mask_descr (ndtype)
getmask (a)
getmaskarray (arr)
is_mask (m)
_shrink_mask (m)
make_mask (m, copy=False, shrink=True, dtype=MaskType)
make_mask_none (newshape, dtype=None)
_recursive_mask_or (m1, m2, newmask)
mask_or (m1, m2, copy=False, shrink=True)
flatten_mask (mask)
_check_mask_axis (mask, axis, keepdims=np._NoValue)
masked_where (condition, a, copy=True)
Masking functions #.
masked_greater (x, value, copy=True)
masked_greater_equal (x, value, copy=True)
masked_less (x, value, copy=True)
masked_less_equal (x, value, copy=True)
masked_not_equal (x, value, copy=True)
masked_equal (x, value, copy=True)
masked_inside (x, v1, v2, copy=True)
masked_outside (x, v1, v2, copy=True)
masked_object (x, value, copy=True, shrink=True)
masked_values (x, value, rtol=1e-5, atol=1e-8, copy=True, shrink=True)
masked_invalid (a, copy=True)
_recursive_printoption (result, mask, printopt)
_recursive_filled (a, mask, fill_value)
MaskedArray class #.
flatten_structured_array (a)
_arraymethod (funcname, onmask=True)
_mareconstruct (subtype, baseclass, baseshape, basetype)
isMaskedArray (x)
array (data, dtype=None, copy=False, order=None, mask=nomask, fill_value=None, keep_mask=True, hard_mask=False, shrink=True, subok=True, ndmin=0)
is_masked (x)
min (obj, axis=None, out=None, fill_value=None, keepdims=np._NoValue)
max (obj, axis=None, out=None, fill_value=None, keepdims=np._NoValue)
ptp (obj, axis=None, out=None, fill_value=None, keepdims=np._NoValue)
take (a, indices, axis=None, out=None, mode='raise')
power (a, b, third=None)
argsort (a, axis=np._NoValue, kind=None, order=None, endwith=True, fill_value=None)
sort (a, axis=-1, kind=None, order=None, endwith=True, fill_value=None)
compressed (x)
concatenate (arrays, axis=0)
diag (v, k=0)
left_shift (a, n)
right_shift (a, n)
put (a, indices, values, mode='raise')
putmask (a, mask, values)
transpose (a, axes=None)
reshape (a, new_shape, order='C')
resize (x, new_shape)
ndim (obj)
shape (obj)
size (obj, axis=None)
diff (a, n=1, axis=-1, prepend=np._NoValue, append=np._NoValue)
where (condition, x=_NoValue, y=_NoValue)
Extra functions #.
choose (indices, choices, out=None, mode='raise')
round_ (a, decimals=0, out=None)
_mask_propagate (a, axis)
dot (a, b, strict=False, out=None)
inner (a, b)
outer (a, b)
_convolve_or_correlate (f, a, v, mode, propagate_mask)
correlate (a, v, mode='valid', propagate_mask=True)
convolve (a, v, mode='full', propagate_mask=True)
allequal (a, b, fill_value=True)
allclose (a, b, masked_equal=True, rtol=1e-5, atol=1e-8)
asarray (a, dtype=None, order=None)
asanyarray (a, dtype=None)
fromfile (file, dtype=float, count=-1, sep='')
Pickling #.
fromflex (fxarray)
append (a, b, axis=None)
Variables
list __all__
MaskType = np.bool_
nomask = MaskType(0)
dict default_filler
list float_types_list
max_filler = ntypes._minvals
min_filler = ntypes._maxvals
get_data = getdata
dict ufunc_domain = {}
Ufuncs #.
dict ufunc_fills = {}
exp = _MaskedUnaryOperation(umath.exp)
conjugate = _MaskedUnaryOperation(umath.conjugate)
sin = _MaskedUnaryOperation(umath.sin)
cos = _MaskedUnaryOperation(umath.cos)
arctan = _MaskedUnaryOperation(umath.arctan)
arcsinh = _MaskedUnaryOperation(umath.arcsinh)
sinh = _MaskedUnaryOperation(umath.sinh)
cosh = _MaskedUnaryOperation(umath.cosh)
tanh = _MaskedUnaryOperation(umath.tanh)
abs = _MaskedUnaryOperation(umath.absolute)
angle = _MaskedUnaryOperation(angle)
fabs = _MaskedUnaryOperation(umath.fabs)
negative = _MaskedUnaryOperation(umath.negative)
floor = _MaskedUnaryOperation(umath.floor)
ceil = _MaskedUnaryOperation(umath.ceil)
around = _MaskedUnaryOperation(np.round_)
logical_not = _MaskedUnaryOperation(umath.logical_not)
sqrt
log
log2
log10
tan
arcsin
arccos
arccosh
arctanh
add = _MaskedBinaryOperation(umath.add)
subtract = _MaskedBinaryOperation(umath.subtract)
multiply = _MaskedBinaryOperation(umath.multiply, 1, 1)
arctan2 = _MaskedBinaryOperation(umath.arctan2, 0.0, 1.0)
equal = _MaskedBinaryOperation(umath.equal)
reduce
not_equal = _MaskedBinaryOperation(umath.not_equal)
less_equal = _MaskedBinaryOperation(umath.less_equal)
greater_equal = _MaskedBinaryOperation(umath.greater_equal)
less = _MaskedBinaryOperation(umath.less)
greater = _MaskedBinaryOperation(umath.greater)
logical_and = _MaskedBinaryOperation(umath.logical_and)
alltrue = _MaskedBinaryOperation(umath.logical_and, 1, 1).reduce
logical_or = _MaskedBinaryOperation(umath.logical_or)
sometrue = logical_or.reduce
logical_xor = _MaskedBinaryOperation(umath.logical_xor)
bitwise_and = _MaskedBinaryOperation(umath.bitwise_and)
bitwise_or = _MaskedBinaryOperation(umath.bitwise_or)
bitwise_xor = _MaskedBinaryOperation(umath.bitwise_xor)
hypot = _MaskedBinaryOperation(umath.hypot)
divide = _DomainedBinaryOperation(umath.divide, _DomainSafeDivide(), 0, 1)
true_divide
floor_divide
remainder
fmod = _DomainedBinaryOperation(umath.fmod, _DomainSafeDivide(), 0, 1)
mod = _DomainedBinaryOperation(umath.mod, _DomainSafeDivide(), 0, 1)
get_mask = getmask
masked_print_option = _MaskedPrintOption('--')
_legacy_print_templates
isarray = isMaskedArray
isMA = isMaskedArray
masked = MaskedConstant()
masked_array = MaskedArray
__doc__
all = _frommethod('all')
anomalies = _frommethod('anom')
any = _frommethod('any')
compress = _frommethod('compress', reversed=True)
cumprod = _frommethod('cumprod')
cumsum = _frommethod('cumsum')
copy = _frommethod('copy')
diagonal = _frommethod('diagonal')
harden_mask = _frommethod('harden_mask')
ids = _frommethod('ids')
maximum = _extrema_operation(umath.maximum, greater, maximum_fill_value)
mean = _frommethod('mean')
minimum = _extrema_operation(umath.minimum, less, minimum_fill_value)
nonzero = _frommethod('nonzero')
prod = _frommethod('prod')
product = _frommethod('prod')
ravel = _frommethod('ravel')
repeat = _frommethod('repeat')
shrink_mask = _frommethod('shrink_mask')
soften_mask = _frommethod('soften_mask')
std = _frommethod('std')
sum = _frommethod('sum')
swapaxes = _frommethod('swapaxes')
trace = _frommethod('trace')
var = _frommethod('var')
count = _frommethod('count')
argmin = _frommethod('argmin')
argmax = _frommethod('argmax')
round = round_
innerproduct = inner
outerproduct = outer
arange
clip
empty
empty_like
frombuffer
fromfunction
identity
indices
ones
ones_like
squeeze
zeros
zeros_like
Detailed Description
numpy.ma : a package to handle missing or invalid values.
This package was initially written for numarray by Paul F. Dubois
at Lawrence Livermore National Laboratory.
In 2006, the package was completely rewritten by Pierre Gerard-Marchant
(University of Georgia) to make the MaskedArray class a subclass of ndarray,
and to improve support of structured arrays.
Copyright 1999, 2000, 2001 Regents of the University of California.
Released for unlimited redistribution.
* Adapted for numpy_core 2005 by Travis Oliphant and (mainly) Paul Dubois.
* Subclassing of the base `ndarray` 2006 by Pierre Gerard-Marchant
  (pgmdevlist_AT_gmail_DOT_com)
* Improvements suggested by Reggie Dugard (reggie_AT_merfinllc_DOT_com)
.. moduleauthor:: Pierre Gerard-Marchant
Function Documentation
_arraymethod()
numpy.ma.core._arraymethod (funcname, onmask = True) protected
Return a class method wrapper around a basic array method.
Creates a class method which returns a masked array, where the new
``_data`` array is the output of the corresponding basic method called
on the original ``_data``.
If `onmask` is True, the new mask is the output of the method called
on the initial mask. Otherwise, the new mask is just a reference
to the initial mask.
Parameters
----------
funcname : str
    Name of the function to apply on data.
onmask : bool
    Whether the mask must be processed also (True) or left
    alone (False). Default is True. Make available as `_onmask`
    attribute.
Returns
-------
method : instancemethod
    Class method wrapper of the specified basic array method.
Definition at line 2544 of file core.py.
Referenced by numpy.ma.core.MaskedArray.take().
_check_fill_value()
numpy.ma.core._check_fill_value (fill_value, ndtype) protected
Private function validating the given `fill_value` for the given dtype.
If fill_value is None, it is set to the default corresponding to the dtype.
If fill_value is not None, its value is forced to the given dtype.
The result is always a 0d array.
Definition at line 433 of file core.py.
References _recursive_set_fill_value(), and default_fill_value().
Referenced by numpy.ma.core.MaskedArray.__array_finalize__(), numpy.ma.core.MaskedArray.__new__(), numpy.ma.core.MaskedArray._comparison(), numpy.ma.core.MaskedArray.fill_value(), and numpy.ma.core.MaskedArray.filled().
_check_mask_axis()
numpy.ma.core._check_mask_axis (mask, axis, keepdims = np._NoValue) protected
Definition at line 1816 of file core.py.
_convolve_or_correlate()
numpy.ma.core._convolve_or_correlate (f, a, v, mode, propagate_mask) protected
Helper function for ma.correlate and ma.convolve
Definition at line 7963 of file core.py.
References filled(), getdata(), and getmaskarray().
Referenced by convolve(), and correlate().
_deprecate_argsort_axis()
numpy.ma.core._deprecate_argsort_axis (arr) protected
Adjust the axis passed to argsort, warning if necessary
Parameters
----------
arr
    The array which argsort was called on
np.ma.argsort has a long-term bug where the default of the axis argument
is wrong (gh-8701), which now must be kept for backwards compatibility.
Thankfully, this only makes a difference when arrays are 2- or more-
dimensional, so we only need a warning then.
Definition at line 87 of file core.py.
Referenced by numpy.ma.core.MaskedArray.argsort(), and power().
_extremum_fill_value()
numpy.ma.core._extremum_fill_value (obj, extremum, extremum_name) protected
Definition at line 285 of file core.py.
_get_dtype_of()
numpy.ma.core._get_dtype_of (obj) protected
 Convert the argument for *_fill_value into a dtype
Definition at line 220 of file core.py.
Referenced by default_fill_value().
_mareconstruct()
numpy.ma.core._mareconstruct (subtype, baseclass, baseshape, basetype) protected
Internal function that builds a new MaskedArray from the
information stored in a pickle.
Definition at line 6335 of file core.py.
References make_mask_descr().
_mask_propagate()
numpy.ma.core._mask_propagate (a, axis) protected
Mask whole 1-d vectors of an array that contain masked values.
Definition at line 7825 of file core.py.
References array(), getmask(), and numpy.core.numeric.normalize_axis_tuple().
Referenced by dot().
_recursive_fill_value()
numpy.ma.core._recursive_fill_value (dtype, f) protected
Recursively produce a fill value for `dtype`, calling f on scalar dtypes
Definition at line 199 of file core.py.
References _recursive_fill_value().
Referenced by _recursive_fill_value(), and default_fill_value().
_recursive_filled()
numpy.ma.core._recursive_filled (a, mask, fill_value) protected
MaskedArray class #.
Recursively fill `a` with `fill_value`.
Definition at line 2475 of file core.py.
References _recursive_filled().
Referenced by _recursive_filled(), and numpy.ma.core.MaskedArray.filled().
_recursive_mask_or()
numpy.ma.core._recursive_mask_or (m1, m2, newmask) protected
Definition at line 1694 of file core.py.
_recursive_printoption()
numpy.ma.core._recursive_printoption (result, mask, printopt) protected
Puts printoptions in result where mask is True.
Private function allowing for recursion
Definition at line 2423 of file core.py.
References _recursive_printoption().
Referenced by numpy.ma.core.mvoid.__getitem__(), numpy.ma.core.MaskedArray._insert_masked_print(), and _recursive_printoption().
_recursive_set_fill_value()
numpy.ma.core._recursive_set_fill_value (fillvalue, dt) protected
Create a fill value for a structured dtype.
Parameters
----------
fillvalue : scalar or array_like
    Scalar or array representing the fill value. If it is of shorter
    length than the number of fields in dt, it will be resized.
dt : dtype
    The structured dtype for which to create the fill value.
Returns
-------
val : tuple
    A tuple of values corresponding to the structured fill value.
Definition at line 401 of file core.py.
References _recursive_set_fill_value().
Referenced by _check_fill_value(), and _recursive_set_fill_value().
_replace_dtype_fields()
numpy.ma.core._replace_dtype_fields (dtype, primitive_dtype) protected
Construct a dtype description list from a given dtype.
Returns a new dtype object, with all fields and subtypes in the given type
recursively replaced with `primitive_dtype`.
Arguments are coerced to dtypes first.
Definition at line 1315 of file core.py.
References _replace_dtype_fields_recursive().
Referenced by numpy.ma.core.mvoid.__getitem__(), numpy.ma.core.MaskedArray._insert_masked_print(), and make_mask_descr().
_replace_dtype_fields_recursive()
numpy.ma.core._replace_dtype_fields_recursive (dtype, primitive_dtype) protected
Mask creation functions #.
Definition at line 1283 of file core.py.
Referenced by _replace_dtype_fields().
_shrink_mask()
numpy.ma.core._shrink_mask (m) protected
Shrink a mask to nomask if possible
Definition at line 1545 of file core.py.
Referenced by concatenate(), make_mask(), masked_where(), numpy.ma.core.MaskedArray.shrink_mask(), and where().
allclose()
numpy.ma.core.allclose (a, b, masked_equal = True, rtol = 1e-5, atol = 1e-8)
Returns True if two arrays are element-wise equal within a tolerance.
This function is equivalent to `allclose` except that masked values
are treated as equal (default) or unequal, depending on the `masked_equal`
argument.
Parameters
----------
a, b : array_like
    Input arrays to compare.
masked_equal : bool, optional
    Whether masked values in `a` and `b` are considered equal (True) or not
    (False). They are considered equal by default.
rtol : float, optional
    Relative tolerance. The relative difference is equal to ``rtol * b``.
    Default is 1e-5.
atol : float, optional
    Absolute tolerance. The absolute difference is equal to `atol`.
    Default is 1e-8.
Returns
-------
y : bool
    Returns True if the two arrays are equal within the given
    tolerance, False otherwise. If either array contains NaN, then
    False is returned.
See Also
--------
all, any
numpy.allclose : the non-masked `allclose`.
Notes
-----
If the following equation is element-wise True, then `allclose` returns
True::
  absolute(`a` - `b`) <= (`atol` + `rtol` * absolute(`b`))
Return True if all elements of `a` and `b` are equal subject to
given tolerances.
Examples
--------
>>> a = np.ma.array([1e10, 1e-7, 42.0], mask=[0, 0, 1])
>>> a
masked_array(data=[10000000000.0, 1e-07, --],
             mask=[False, False,  True],
       fill_value=1e+20)
>>> b = np.ma.array([1e10, 1e-8, -42.0], mask=[0, 0, 1])
>>> np.ma.allclose(a, b)
False
>>> a = np.ma.array([1e10, 1e-8, 42.0], mask=[0, 0, 1])
>>> b = np.ma.array([1.00001e10, 1e-9, -42.0], mask=[0, 0, 1])
>>> np.ma.allclose(a, b)
True
>>> np.ma.allclose(a, b, masked_equal=False)
False
Masked values are not compared directly.
>>> a = np.ma.array([1e10, 1e-8, 42.0], mask=[0, 0, 1])
>>> b = np.ma.array([1.00001e10, 1e-9, 42.0], mask=[0, 0, 1])
>>> np.ma.allclose(a, b)
True
>>> np.ma.allclose(a, b, masked_equal=False)
False
Definition at line 8096 of file core.py.
References filled(), getmask(), and mask_or().
allequal()
numpy.ma.core.allequal (a, b, fill_value = True)
Return True if all entries of a and b are equal, using
fill_value as a truth value where either or both are masked.
Parameters
----------
a, b : array_like
    Input arrays to compare.
fill_value : bool, optional
    Whether masked values in a or b are considered equal (True) or not
    (False).
Returns
-------
y : bool
    Returns True if the two arrays are equal within the given
    tolerance, False otherwise. If either array contains NaN,
    then False is returned.
See Also
--------
all, any
numpy.ma.allclose
Examples
--------
>>> a = np.ma.array([1e10, 1e-7, 42.0], mask=[0, 0, 1])
>>> a
masked_array(data=[10000000000.0, 1e-07, --],
             mask=[False, False,  True],
       fill_value=1e+20)
>>> b = np.array([1e10, 1e-7, -42.0])
>>> b
array([  1.00000000e+10,   1.00000000e-07,  -4.20000000e+01])
>>> np.ma.allequal(a, b, fill_value=False)
False
>>> np.ma.allequal(a, b)
True
Definition at line 8038 of file core.py.
References array(), getdata(), getmask(), and mask_or().
append()
numpy.ma.core.append (a, b, axis = None)
Append values to the end of an array.
.. versionadded:: 1.9.0
Parameters
----------
a : array_like
    Values are appended to a copy of this array.
b : array_like
    These values are appended to a copy of `a`.  It must be of the
    correct shape (the same shape as `a`, excluding `axis`).  If `axis`
    is not specified, `b` can be any shape and will be flattened
    before use.
axis : int, optional
    The axis along which `v` are appended.  If `axis` is not given,
    both `a` and `b` are flattened before use.
Returns
-------
append : MaskedArray
    A copy of `a` with `b` appended to `axis`.  Note that `append`
    does not occur in-place: a new array is allocated and filled.  If
    `axis` is None, the result is a flattened array.
See Also
--------
numpy.append : Equivalent function in the top-level NumPy module.
Examples
--------
>>> import numpy.ma as ma
>>> a = ma.masked_values([1, 2, 3], 2)
>>> b = ma.masked_values([[4, 5, 6], [7, 8, 9]], 7)
>>> ma.append(a, b)
masked_array(data=[1, --, 3, 4, 5, 6, --, 8, 9],
             mask=[False,  True, False, False, False, False,  True, False,
                   False],
       fill_value=999999)
Definition at line 8525 of file core.py.
References concatenate().
argsort()
numpy.ma.core.argsort (a, axis = np._NoValue, kind = None, order = None, endwith = True, fill_value = None)
Definition at line 7001 of file core.py.
array()
numpy.ma.core.array (data, dtype = None, copy = False, order = None, mask = nomask, fill_value = None, keep_mask = True, hard_mask = False, shrink = True, subok = True, ndmin = 0)
Shortcut to MaskedArray.
The options are in a different order for convenience and backwards
compatibility.
Definition at line 6660 of file core.py.
Referenced by numpy.ma.extras._covhelper(), _mask_propagate(), allequal(), numpy.ma.extras.apply_along_axis(), numpy.ma.extras.apply_over_axes(), numpy.ma.extras.mask_rowcols(), numpy.ma.extras.notmasked_edges(), and numpy.ma.tests.test_core.test_ufunc_with_out_varied().
asanyarray()
numpy.ma.core.asanyarray (a, dtype = None)
Convert the input to a masked array, conserving subclasses.
If `a` is a subclass of `MaskedArray`, its class is conserved.
No copy is performed if the input is already an `ndarray`.
Parameters
----------
a : array_like
    Input data, in any form that can be converted to an array.
dtype : dtype, optional
    By default, the data-type is inferred from the input data.
order : {'C', 'F'}, optional
    Whether to use row-major ('C') or column-major ('FORTRAN') memory
    representation.  Default is 'C'.
Returns
-------
out : MaskedArray
    MaskedArray interpretation of `a`.
See Also
--------
asarray : Similar to `asanyarray`, but does not conserve subclass.
Examples
--------
>>> x = np.arange(10.).reshape(2, 5)
>>> x
array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])
>>> np.ma.asanyarray(x)
masked_array(
  data=[[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]],
  mask=False,
  fill_value=1e+20)
>>> type(np.ma.asanyarray(x))
<class 'numpy.ma.core.MaskedArray'>
Definition at line 8253 of file core.py.
Referenced by compressed().
asarray()
numpy.ma.core.asarray (a, dtype = None, order = None)
Convert the input to a masked array of the given data-type.
No copy is performed if the input is already an `ndarray`. If `a` is
a subclass of `MaskedArray`, a base class `MaskedArray` is returned.
Parameters
----------
a : array_like
    Input data, in any form that can be converted to a masked array. This
    includes lists, lists of tuples, tuples, tuples of tuples, tuples
    of lists, ndarrays and masked arrays.
dtype : dtype, optional
    By default, the data-type is inferred from the input data.
order : {'C', 'F'}, optional
    Whether to use row-major ('C') or column-major ('FORTRAN') memory
    representation.  Default is 'C'.
Returns
-------
out : MaskedArray
    Masked array interpretation of `a`.
See Also
--------
asanyarray : Similar to `asarray`, but conserves subclasses.
Examples
--------
>>> x = np.arange(10.).reshape(2, 5)
>>> x
array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])
>>> np.ma.asarray(x)
masked_array(
  data=[[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]],
  mask=False,
  fill_value=1e+20)
>>> type(np.ma.asarray(x))
<class 'numpy.ma.core.MaskedArray'>
Definition at line 8204 of file core.py.
Referenced by numpy.ma.extras.apply_along_axis(), numpy.ma.extras.apply_over_axes(), numpy.ma.extras.average(), numpy.ma.extras.compress_cols(), numpy.ma.extras.compress_nd(), numpy.ma.extras.compress_rowcols(), numpy.ma.extras.compress_rows(), numpy.ma.core.mvoid.filled(), numpy.ma.extras.notmasked_contiguous(), numpy.ma.extras.notmasked_edges(), and numpy.ma.extras.polyfit().
choose()
numpy.ma.core.choose (indices, choices, out = None, mode = 'raise')
Use an index array to construct a new array from a list of choices.
Given an array of integers and a list of n choice arrays, this method
will create a new array that merges each of the choice arrays.  Where a
value in `index` is i, the new array will have the value that choices[i]
contains in the same place.
Parameters
----------
indices : ndarray of ints
    This array must contain integers in ``[0, n-1]``, where n is the
    number of choices.
choices : sequence of arrays
    Choice arrays. The index array and all of the choices should be
    broadcastable to the same shape.
out : array, optional
    If provided, the result will be inserted into this array. It should
    be of the appropriate shape and `dtype`.
mode : {'raise', 'wrap', 'clip'}, optional
    Specifies how out-of-bounds indices will behave.
    * 'raise' : raise an error
    * 'wrap' : wrap around
    * 'clip' : clip to the range
Returns
-------
merged_array : array
See Also
--------
choose : equivalent function
Examples
--------
>>> choice = np.array([[1,1,1], [2,2,2], [3,3,3]])
>>> a = np.array([2, 1, 0])
>>> np.ma.choose(a, choice)
masked_array(data=[3, 2, 1],
             mask=False,
       fill_value=999999)
Definition at line 7694 of file core.py.
References filled(), getmask(), make_mask(), and mask_or().
common_fill_value()
numpy.ma.core.common_fill_value (a, b)
Return the common filling value of two masked arrays, if any.
If ``a.fill_value == b.fill_value``, return the fill value,
otherwise return None.
Parameters
----------
a, b : MaskedArray
    The masked arrays for which to compare fill values.
Returns
-------
fill_value : scalar or None
    The common fill value, or None.
Examples
--------
>>> x = np.ma.array([0, 1.], fill_value=3)
>>> y = np.ma.array([0, 1.], fill_value=3)
>>> np.ma.common_fill_value(x, y)
3.0
Definition at line 555 of file core.py.
References get_fill_value().
compressed()
numpy.ma.core.compressed (x)
Return all the non-masked data as a 1-D array.
This function is equivalent to calling the "compressed" method of a
`ma.MaskedArray`, see `ma.MaskedArray.compressed` for details.
See Also
--------
ma.MaskedArray.compressed : Equivalent method.
Examples
--------
Create an array with negative values masked:
>>> import numpy as np
>>> x = np.array([[1, -1, 0], [2, -1, 3], [7, 4, -1]])
>>> masked_x = np.ma.masked_array(x, mask=x < 0)
>>> masked_x
masked_array(
  data=[[1, --, 0],
        [2, --, 3],
        [7, 4, --]],
  mask=[[False,  True, False],
        [False,  True, False],
        [False, False,  True]],
  fill_value=999999)
Compress the masked array into a 1-D array of non-masked values:
>>> np.ma.compressed(masked_x)
array([1, 0, 2, 3, 7, 4])
Definition at line 7057 of file core.py.
References asanyarray(), and compressed().
Referenced by compressed(), and numpy.ma.extras.notmasked_edges().
concatenate()
numpy.ma.core.concatenate (arrays, axis = 0)
Concatenate a sequence of arrays along the given axis.
Parameters
----------
arrays : sequence of array_like
    The arrays must have the same shape, except in the dimension
    corresponding to `axis` (the first, by default).
axis : int, optional
    The axis along which the arrays will be joined. Default is 0.
Returns
-------
result : MaskedArray
    The concatenated array with any masked entries preserved.
See Also
--------
numpy.concatenate : Equivalent function in the top-level NumPy module.
Examples
--------
>>> import numpy.ma as ma
>>> a = ma.arange(3)
>>> a[1] = ma.masked
>>> b = ma.arange(2, 5)
>>> a
masked_array(data=[0, --, 2],
             mask=[False,  True, False],
       fill_value=999999)
>>> b
masked_array(data=[2, 3, 4],
             mask=False,
       fill_value=999999)
>>> ma.concatenate([a, b])
masked_array(data=[0, --, 2, 2, 3, 4],
             mask=[False,  True, False, False, False, False],
       fill_value=999999)
Definition at line 7095 of file core.py.
References _shrink_mask(), get_masked_subclass(), getdata(), getmask(), and getmaskarray().
Referenced by append().
convolve()
numpy.ma.core.convolve (a, v, mode = 'full', propagate_mask = True)
Returns the discrete, linear convolution of two one-dimensional sequences.
Parameters
----------
a, v : array_like
    Input sequences.
mode : {'valid', 'same', 'full'}, optional
    Refer to the `np.convolve` docstring.
propagate_mask : bool
    If True, then if any masked element is included in the sum for a result
    element, then the result is masked.
    If False, then the result element is only masked if no non-masked cells
    contribute towards it
Returns
-------
out : MaskedArray
    Discrete, linear convolution of `a` and `v`.
See Also
--------
numpy.convolve : Equivalent function in the top-level NumPy module.
Definition at line 8010 of file core.py.
References _convolve_or_correlate().
correlate()
numpy.ma.core.correlate (a, v, mode = 'valid', propagate_mask = True)
Cross-correlation of two 1-dimensional sequences.
Parameters
----------
a, v : array_like
    Input sequences.
mode : {'valid', 'same', 'full'}, optional
    Refer to the `np.convolve` docstring.  Note that the default
    is 'valid', unlike `convolve`, which uses 'full'.
propagate_mask : bool
    If True, then a result element is masked if any masked element contributes towards it.
    If False, then a result element is only masked if no non-masked element
    contribute towards it
Returns
-------
out : MaskedArray
    Discrete cross-correlation of `a` and `v`.
See Also
--------
numpy.correlate : Equivalent function in the top-level NumPy module.
Definition at line 7982 of file core.py.
References _convolve_or_correlate().
default_fill_value()
numpy.ma.core.default_fill_value (obj)
Return the default fill value for the argument object.
The default filling value depends on the datatype of the input
array or the type of the input scalar:
   ========  ========
   datatype  default
   ========  ========
   bool      True
   int       999999
   float     1.e20
   complex   1.e20+0j
   object    '?'
   string    'N/A'
   ========  ========
For structured types, a structured scalar is returned, with each field the
default fill value for its type.
For subarray types, the fill value is an array of the same size containing
the default scalar fill value.
Parameters
----------
obj : ndarray, dtype or scalar
    The array data-type or scalar for which the default fill value
    is returned.
Returns
-------
fill_value : scalar
    The default fill value.
Examples
--------
>>> np.ma.default_fill_value(1)
999999
>>> np.ma.default_fill_value(np.array([1.1, 2., np.pi]))
1e+20
>>> np.ma.default_fill_value(np.dtype(complex))
(1e+20+0j)
Definition at line 230 of file core.py.
References _get_dtype_of(), and _recursive_fill_value().
Referenced by _check_fill_value(), and get_fill_value().
diag()
numpy.ma.core.diag (v, k = 0)
Extract a diagonal or construct a diagonal array.
This function is the equivalent of `numpy.diag` that takes masked
values into account, see `numpy.diag` for details.
See Also
--------
numpy.diag : Equivalent function for ndarrays.
Examples
--------
Create an array with negative values masked:
>>> import numpy as np
>>> x = np.array([[11.2, -3.973, 18], [0.801, -1.41, 12], [7, 33, -12]])
>>> masked_x = np.ma.masked_array(x, mask=x < 0)
>>> masked_x
masked_array(
  data=[[11.2, --, 18.0],
        [0.801, --, 12.0],
        [7.0, 33.0, --]],
  mask=[[False,  True, False],
        [False,  True, False],
        [False, False,  True]],
  fill_value=1e+20)
Isolate the main diagonal from the masked array:
>>> np.ma.diag(masked_x)
masked_array(data=[11.2, --, --],
             mask=[False,  True,  True],
       fill_value=1e+20)
Isolate the first diagonal below the main diagonal:
>>> np.ma.diag(masked_x, -1)
masked_array(data=[0.801, 33.0],
             mask=[False, False],
       fill_value=1e+20)
Definition at line 7155 of file core.py.
References getmask().
diff()
numpy.ma.core.diff (a, n = 1, axis = -1, prepend = np._NoValue, append = np._NoValue)
Calculate the n-th discrete difference along the given axis.
The first difference is given by ``out[i] = a[i+1] - a[i]`` along
the given axis, higher differences are calculated by using `diff`
recursively.
Preserves the input mask.
Parameters
----------
a : array_like
    Input array
n : int, optional
    The number of times values are differenced. If zero, the input
    is returned as-is.
axis : int, optional
    The axis along which the difference is taken, default is the
    last axis.
prepend, append : array_like, optional
    Values to prepend or append to `a` along axis prior to
    performing the difference.  Scalar values are expanded to
    arrays with length 1 in the direction of axis and the shape
    of the input array in along all other axes.  Otherwise the
    dimension and shape must match `a` except along axis.
Returns
-------
diff : MaskedArray
    The n-th differences. The shape of the output is the same as `a`
    except along `axis` where the dimension is smaller by `n`. The
    type of the output is the same as the type of the difference
    between any two elements of `a`. This is the same as the type of
    `a` in most cases. A notable exception is `datetime64`, which
    results in a `timedelta64` output array.
See Also
--------
numpy.diff : Equivalent function in the top-level NumPy module.
Notes
-----
Type is preserved for boolean arrays, so the result will contain
`False` when consecutive elements are the same and `True` when they
differ.
For unsigned integer arrays, the results will also be unsigned. This
should not be surprising, as the result is consistent with
calculating the difference directly:
>>> u8_arr = np.array([1, 0], dtype=np.uint8)
>>> np.ma.diff(u8_arr)
masked_array(data=[255],
             mask=False,
       fill_value=999999,
            dtype=uint8)
>>> u8_arr[1,...] - u8_arr[0,...]
255
If this is not desirable, then the array should be cast to a larger
integer type first:
>>> i16_arr = u8_arr.astype(np.int16)
>>> np.ma.diff(i16_arr)
masked_array(data=[-1],
             mask=False,
       fill_value=999999,
            dtype=int16)
Examples
--------
>>> a = np.array([1, 2, 3, 4, 7, 0, 2, 3])
>>> x = np.ma.masked_where(a < 2, a)
>>> np.ma.diff(x)
masked_array(data=[--, 1, 1, 3, --, --, 1],
        mask=[ True, False, False, False,  True,  True, False],
    fill_value=999999)
>>> np.ma.diff(x, n=2)
masked_array(data=[--, 0, 2, --, --, --],
            mask=[ True, False, False,  True,  True,  True],
    fill_value=999999)
>>> a = np.array([[1, 3, 1, 5, 10], [0, 1, 5, 6, 8]])
>>> x = np.ma.masked_equal(a, value=1)
>>> np.ma.diff(x)
masked_array(
    data=[[--, --, --, 5],
            [--, --, 1, 2]],
    mask=[[ True,  True,  True, False],
            [ True,  True, False, False]],
    fill_value=1)
>>> np.ma.diff(x, axis=0)
masked_array(data=[[--, --, --, 1, -2]],
        mask=[[ True,  True,  True, False, False]],
    fill_value=1)
Definition at line 7463 of file core.py.
doc_note()
numpy.ma.core.doc_note (initialdoc, note)
Adds a Notes section to an existing docstring.
Definition at line 115 of file core.py.
Referenced by inner().
dot()
numpy.ma.core.dot (a, b, strict = False, out = None)
Return the dot product of two arrays.
This function is the equivalent of `numpy.dot` that takes masked values
into account. Note that `strict` and `out` are in different position
than in the method version. In order to maintain compatibility with the
corresponding method, it is recommended that the optional arguments be
treated as keyword only.  At some point that may be mandatory.
Parameters
----------
a, b : masked_array_like
    Inputs arrays.
strict : bool, optional
    Whether masked data are propagated (True) or set to 0 (False) for
    the computation. Default is False.  Propagating the mask means that
    if a masked value appears in a row or column, the whole row or
    column is considered masked.
out : masked_array, optional
    Output argument. This must have the exact kind that would be returned
    if it was not used. In particular, it must have the right type, must be
    C-contiguous, and its dtype must be the dtype that would be returned
    for `dot(a,b)`. This is a performance feature. Therefore, if these
    conditions are not met, an exception is raised, instead of attempting
    to be flexible.
    .. versionadded:: 1.10.2
See Also
--------
numpy.dot : Equivalent function for ndarrays.
Examples
--------
>>> a = np.ma.array([[1, 2, 3], [4, 5, 6]], mask=[[1, 0, 0], [0, 0, 0]])
>>> b = np.ma.array([[1, 2], [3, 4], [5, 6]], mask=[[1, 0], [0, 0], [0, 0]])
>>> np.ma.dot(a, b)
masked_array(
  data=[[21, 26],
        [45, 64]],
  mask=[[False, False],
        [False, False]],
  fill_value=999999)
>>> np.ma.dot(a, b, strict=True)
masked_array(
  data=[[--, --],
        [--, 64]],
  mask=[[ True,  True],
        [ True, False]],
  fill_value=999999)
Definition at line 7843 of file core.py.
References _mask_propagate(), filled(), get_masked_subclass(), and getmaskarray().
Referenced by numpy.ma.extras.corrcoef(), and numpy.ma.extras.cov().
filled()
numpy.ma.core.filled (a, fill_value = None)
Return input as an array with masked data replaced by a fill value.
If `a` is not a `MaskedArray`, `a` itself is returned.
If `a` is a `MaskedArray` and `fill_value` is None, `fill_value` is set to
``a.fill_value``.
Parameters
----------
a : MaskedArray or array_like
    An input object.
fill_value : array_like, optional.
    Can be scalar or non-scalar. If non-scalar, the
    resulting filled array should be broadcastable
    over input array. Default is None.
Returns
-------
a : ndarray
    The filled array.
See Also
--------
compressed
Examples
--------
>>> x = np.ma.array(np.arange(9).reshape(3, 3), mask=[[1, 0, 0],
...                                                   [1, 0, 0],
...                                                   [0, 0, 0]])
>>> x.filled()
array([[999999,      1,      2],
       [999999,      4,      5],
       [     6,      7,      8]])
>>> x.filled(fill_value=333)
array([[333,   1,   2],
       [333,   4,   5],
       [  6,   7,   8]])
>>> x.filled(fill_value=np.arange(3))
array([[0, 1, 2],
       [0, 4, 5],
       [6, 7, 8]])
Definition at line 587 of file core.py.
Referenced by _convolve_or_correlate(), numpy.ma.core._MaskedBinaryOperation.accumulate(), allclose(), numpy.ma.testutils.almost(), numpy.ma.testutils.approx(), choose(), dot(), inner(), left_shift(), make_mask(), masked_inside(), masked_outside(), masked_values(), numpy.ma.core._MaskedBinaryOperation.reduce(), right_shift(), and where().
fix_invalid()
numpy.ma.core.fix_invalid (a, mask = nomask, copy = True, fill_value = None)
Return input with invalid data masked and replaced by a fill value.
Invalid data means values of `nan`, `inf`, etc.
Parameters
----------
a : array_like
    Input array, a (subclass of) ndarray.
mask : sequence, optional
    Mask. Must be convertible to an array of booleans with the same
    shape as `data`. True indicates a masked (i.e. invalid) data.
copy : bool, optional
    Whether to use a copy of `a` (True) or to fix `a` in place (False).
    Default is True.
fill_value : scalar, optional
    Value used for fixing invalid data. Default is None, in which case
    the ``a.fill_value`` is used.
Returns
-------
b : MaskedArray
    The input array with invalid entries fixed.
Notes
-----
A copy is performed by default.
Examples
--------
>>> x = np.ma.array([1., -1, np.nan, np.inf], mask=[1] + [0]*3)
>>> x
masked_array(data=[--, -1.0, nan, inf],
             mask=[ True, False, False, False],
       fill_value=1e+20)
>>> np.ma.fix_invalid(x)
masked_array(data=[--, -1.0, --, --],
             mask=[ True, False,  True,  True],
       fill_value=1e+20)
>>> fixed = np.ma.fix_invalid(x)
>>> fixed.data
array([ 1.e+00, -1.e+00,  1.e+20,  1.e+20])
>>> x.data
array([ 1., -1., nan, inf])
Definition at line 725 of file core.py.
flatten_mask()
numpy.ma.core.flatten_mask (mask)
Returns a completely flattened version of the mask, where nested fields
are collapsed.
Parameters
----------
mask : array_like
    Input array, which will be interpreted as booleans.
Returns
-------
flattened_mask : ndarray of bools
    The flattened input.
Examples
--------
>>> mask = np.array([0, 0, 1])
>>> np.ma.flatten_mask(mask)
array([False, False,  True])
>>> mask = np.array([(0, 0), (0, 1)], dtype=[('a', bool), ('b', bool)])
>>> np.ma.flatten_mask(mask)
array([False, False, False,  True])
>>> mdtype = [('a', bool), ('b', [('ba', bool), ('bb', bool)])]
>>> mask = np.array([(0, (0, 0)), (0, (0, 1))], dtype=mdtype)
>>> np.ma.flatten_mask(mask)
array([False, False, False, False, False,  True])
Definition at line 1760 of file core.py.
References flatten_mask().
Referenced by flatten_mask().
flatten_structured_array()
numpy.ma.core.flatten_structured_array (a)
Flatten a structured array.
The data type of the output is chosen such that it can represent all of the
(nested) fields.
Parameters
----------
a : structured array
Returns
-------
output : masked array or ndarray
    A flattened masked array if the input is a masked array, otherwise a
    standard ndarray.
Examples
--------
>>> ndtype = [('a', int), ('b', float)]
>>> a = np.array([(1, 1), (2, 2)], dtype=ndtype)
>>> np.ma.flatten_structured_array(a)
array([[1., 1.],
       [2., 2.]])
Definition at line 2489 of file core.py.
References getmaskarray().
Referenced by numpy.ma.core.MaskedArray.recordmask().
fromfile()
numpy.ma.core.fromfile (file, dtype = float, count = -1, sep = '')
Pickling #.
Definition at line 8307 of file core.py.
fromflex()
numpy.ma.core.fromflex (fxarray)
Build a masked array from a suitable flexible-type array.
The input array has to have a data-type with ``_data`` and ``_mask``
fields. This type of array is output by `MaskedArray.toflex`.
Parameters
----------
fxarray : ndarray
    The structured input array, containing ``_data`` and ``_mask``
    fields. If present, other fields are discarded.
Returns
-------
result : MaskedArray
    The constructed masked array.
See Also
--------
MaskedArray.toflex : Build a flexible-type array from a masked array.
Examples
--------
>>> x = np.ma.array(np.arange(9).reshape(3, 3), mask=[0] + [1, 0] * 4)
>>> rec = x.toflex()
>>> rec
array([[(0, False), (1,  True), (2, False)],
       [(3,  True), (4, False), (5,  True)],
       [(6, False), (7,  True), (8, False)]],
      dtype=[('_data', '<i8'), ('_mask', '?')])
>>> x2 = np.ma.fromflex(rec)
>>> x2
masked_array(
  data=[[0, --, 2],
        [--, 4, --],
        [6, --, 8]],
  mask=[[False,  True, False],
        [ True, False,  True],
        [False,  True, False]],
  fill_value=999999)
Extra fields can be present in the structured array but are discarded:
>>> dt = [('_data', '<i4'), ('_mask', '|b1'), ('field3', '<f4')]
>>> rec2 = np.zeros((2, 2), dtype=dt)
>>> rec2
array([[(0, False, 0.), (0, False, 0.)],
       [(0, False, 0.), (0, False, 0.)]],
      dtype=[('_data', '<i4'), ('_mask', '?'), ('field3', '<f4')])
>>> y = np.ma.fromflex(rec2)
>>> y
masked_array(
  data=[[0, 0],
        [0, 0]],
  mask=[[False, False],
        [False, False]],
  fill_value=999999,
  dtype=int32)
Definition at line 8312 of file core.py.
get_fill_value()
numpy.ma.core.get_fill_value (a)
Return the filling value of a, if any.  Otherwise, returns the
default filling value for that type.
Definition at line 542 of file core.py.
References default_fill_value().
Referenced by common_fill_value().
get_masked_subclass()
numpy.ma.core.get_masked_subclass (* arrays)
Return the youngest subclass of MaskedArray from a list of (masked) arrays.
In case of siblings, the first listed takes over.
Definition at line 644 of file core.py.
Referenced by numpy.ma.core._MaskedBinaryOperation.__call__(), numpy.ma.core._MaskedUnaryOperation.__call__(), numpy.ma.core._DomainedBinaryOperation.__init__(), numpy.ma.core._MaskedBinaryOperation.accumulate(), concatenate(), dot(), numpy.ma.core._MaskedBinaryOperation.outer(), numpy.ma.core._MaskedBinaryOperation.reduce(), and resize().
get_object_signature()
numpy.ma.core.get_object_signature (obj)
Get the signature from obj
Definition at line 131 of file core.py.
getdata()
numpy.ma.core.getdata (a, subok = True)
Return the data of a masked array as an ndarray.
Return the data of `a` (if any) as an ndarray if `a` is a ``MaskedArray``,
else return `a` as a ndarray or subclass (depending on `subok`) if not.
Parameters
----------
a : array_like
    Input ``MaskedArray``, alternatively a ndarray or a subclass thereof.
subok : bool
    Whether to force the output to be a `pure` ndarray (False) or to
    return a subclass of ndarray if appropriate (True, default).
See Also
--------
getmask : Return the mask of a masked array, or nomask.
getmaskarray : Return the mask of a masked array, or full array of False.
Examples
--------
>>> import numpy.ma as ma
>>> a = ma.masked_equal([[1,2],[3,4]], 2)
>>> a
masked_array(
  data=[[1, --],
        [3, 4]],
  mask=[[False,  True],
        [False, False]],
  fill_value=2)
>>> ma.getdata(a)
array([[1, 2],
       [3, 4]])
Equivalently use the ``MaskedArray`` `data` attribute.
>>> a.data
array([[1, 2],
       [3, 4]])
Definition at line 671 of file core.py.
Referenced by numpy.ma.core._MaskedBinaryOperation.__call__(), numpy.ma.core._MaskedUnaryOperation.__call__(), numpy.ma.core.MaskedArray.__iadd__(), numpy.ma.core.MaskedArray.__idiv__(), numpy.ma.core.MaskedArray.__ifloordiv__(), numpy.ma.core.MaskedArray.__imul__(), numpy.ma.core._DomainedBinaryOperation.__init__(), numpy.ma.core.MaskedArray.__ipow__(), numpy.ma.core.MaskedArray.__isub__(), numpy.ma.core.MaskedArray.__itruediv__(), numpy.ma.core.MaskedArray._comparison(), _convolve_or_correlate(), allequal(), concatenate(), numpy.ma.mrecords.fromarrays(), numpy.ma.extras.median(), ndim(), numpy.ma.core._MaskedBinaryOperation.outer(), power(), putmask(), round_(), and where().
getmask()
numpy.ma.core.getmask (a)
Return the mask of a masked array, or nomask.
Return the mask of `a` as an ndarray if `a` is a `MaskedArray` and the
mask is not `nomask`, else return `nomask`. To guarantee a full array
of booleans of the same shape as a, use `getmaskarray`.
Parameters
----------
a : array_like
    Input `MaskedArray` for which the mask is required.
See Also
--------
getdata : Return the data of a masked array as an ndarray.
getmaskarray : Return the mask of a masked array, or full array of False.
Examples
--------
>>> import numpy.ma as ma
>>> a = ma.masked_equal([[1,2],[3,4]], 2)
>>> a
masked_array(
  data=[[1, --],
        [3, 4]],
  mask=[[False,  True],
        [False, False]],
  fill_value=2)
>>> ma.getmask(a)
array([[False,  True],
       [False, False]])
Equivalently use the `MaskedArray` `mask` attribute.
>>> a.mask
array([[False,  True],
       [False, False]])
Result when mask == `nomask`
>>> b = ma.masked_array([[1,2],[3,4]])
>>> b
masked_array(
  data=[[1, 2],
        [3, 4]],
  mask=False,
  fill_value=999999)
>>> ma.nomask
False
>>> ma.getmask(b) == ma.nomask
True
>>> b.mask == ma.nomask
True
Definition at line 1362 of file core.py.
Referenced by numpy.ma.core.MaskedArray.__array_finalize__(), numpy.ma.core._MaskedBinaryOperation.__call__(), numpy.ma.core._MaskedUnaryOperation.__call__(), numpy.ma.core.MaskedArray.__iadd__(), numpy.ma.core.MaskedArray.__idiv__(), numpy.ma.core.MaskedArray.__ifloordiv__(), numpy.ma.core.MaskedArray.__imul__(), numpy.ma.core._DomainedBinaryOperation.__init__(), numpy.ma.core.MaskedArray.__ipow__(), numpy.ma.core.MaskedArray.__isub__(), numpy.ma.core.MaskedArray.__itruediv__(), numpy.ma.core.MaskedArray.__new__(), numpy.ma.core.MaskedArray.__setitem__(), numpy.ma.core.MaskedArray._comparison(), _mask_propagate(), allclose(), allequal(), numpy.ma.testutils.almost(), numpy.ma.testutils.approx(), numpy.ma.testutils.assert_array_compare(), numpy.ma.extras.average(), choose(), numpy.ma.extras.compress_nd(), concatenate(), diag(), numpy.ma.extras.flatnotmasked_contiguous(), numpy.ma.extras.flatnotmasked_edges(), getmaskarray(), inner(), is_masked(), left_shift(), numpy.ma.extras.mask_rowcols(), masked_where(), numpy.ma.core.MaskedArray.max(), numpy.ma.core.MaskedArray.mean(), numpy.ma.core.MaskedArray.min(), numpy.ma.core._MaskedBinaryOperation.outer(), numpy.ma.extras.polyfit(), power(), numpy.ma.core.MaskedArray.prod(), numpy.ma.core.MaskedArray.put(), putmask(), numpy.ma.core._MaskedBinaryOperation.reduce(), resize(), right_shift(), round_(), numpy.ma.core.MaskedArray.sum(), numpy.ma.core.MaskedArray.take(), numpy.ma.extras.vander(), numpy.ma.core.MaskedArray.var(), and numpy.ma.core.MaskedArray.view().
getmaskarray()
numpy.ma.core.getmaskarray (arr)
Return the mask of a masked array, or full boolean array of False.
Return the mask of `arr` as an ndarray if `arr` is a `MaskedArray` and
the mask is not `nomask`, else return a full boolean array of False of
the same shape as `arr`.
Parameters
----------
arr : array_like
    Input `MaskedArray` for which the mask is required.
See Also
--------
getmask : Return the mask of a masked array, or nomask.
getdata : Return the data of a masked array as an ndarray.
Examples
--------
>>> import numpy.ma as ma
>>> a = ma.masked_equal([[1,2],[3,4]], 2)
>>> a
masked_array(
  data=[[1, --],
        [3, 4]],
  mask=[[False,  True],
        [False, False]],
  fill_value=2)
>>> ma.getmaskarray(a)
array([[False,  True],
       [False, False]])
Result when mask == ``nomask``
>>> b = ma.masked_array([[1,2],[3,4]])
>>> b
masked_array(
  data=[[1, 2],
        [3, 4]],
  mask=False,
  fill_value=999999)
>>> ma.getmaskarray(b)
array([[False, False],
       [False, False]])
Definition at line 1424 of file core.py.
References getmask(), and make_mask_none().
Referenced by numpy.ma.core.MaskedArray.__array_finalize__(), numpy.ma.core.MaskedArray.__array_wrap__(), numpy.ma.core._MaskedBinaryOperation.__call__(), numpy.ma.core.MaskedArray.__getitem__(), numpy.ma.core.MaskedArray.__getstate__(), numpy.ma.core.MaskedArray.__new__(), numpy.ma.mrecords.MaskedRecords.__setattr__(), _convolve_or_correlate(), numpy.ma.mrecords.addfield(), concatenate(), numpy.ma.extras.count_masked(), dot(), flatten_structured_array(), numpy.ma.mrecords.fromarrays(), inner(), numpy.ma.extras.ndenumerate(), numpy.ma.extras.notmasked_edges(), numpy.ma.core._MaskedBinaryOperation.outer(), numpy.ma.core.MaskedArray.put(), putmask(), and where().
inner()
numpy.ma.core.inner (a, b)
Returns the inner product of a and b for arrays of floating point types.
Like the generic NumPy equivalent the product sum is over the last dimension
of a and b. The first argument is not conjugated.
Definition at line 7925 of file core.py.
References doc_note(), filled(), getmask(), getmaskarray(), and make_mask().
is_mask()
numpy.ma.core.is_mask (m)
Return True if m is a valid, standard mask.
This function does not check the contents of the input, only that the
type is MaskType. In particular, this function returns False if the
mask has a flexible dtype.
Parameters
----------
m : array_like
    Array to test.
Returns
-------
result : bool
    True if `m.dtype.type` is MaskType, False otherwise.
See Also
--------
ma.isMaskedArray : Test whether input is an instance of MaskedArray.
Examples
--------
>>> import numpy.ma as ma
>>> m = ma.masked_equal([0, 1, 0, 2, 3], 0)
>>> m
masked_array(data=[--, 1, --, 2, 3],
             mask=[ True, False,  True, False, False],
       fill_value=0)
>>> ma.is_mask(m)
False
>>> ma.is_mask(m.mask)
True
Input must be an ndarray (or have similar attributes)
for it to be considered a valid mask.
>>> m = [False, True, False]
>>> ma.is_mask(m)
False
>>> m = np.array([False, True, False])
>>> m
array([False,  True, False])
>>> ma.is_mask(m)
True
Arrays with complex dtypes don't return True.
>>> dtype = np.dtype({'names':['monty', 'pithon'],
...                   'formats':[bool, bool]})
>>> dtype
dtype([('monty', '|b1'), ('pithon', '|b1')])
>>> m = np.array([(True, False), (False, True), (True, False)],
...              dtype=dtype)
>>> m
array([(True, False), (False,  True), (True, False)],
      dtype=[('monty', '?'), ('pithon', '?')])
>>> ma.is_mask(m)
False
Definition at line 1477 of file core.py.
Referenced by mask_or().
is_masked()
numpy.ma.core.is_masked (x)
Determine whether input has masked values.
Accepts any object as input, but always returns False unless the
input is a MaskedArray containing masked values.
Parameters
----------
x : array_like
    Array to check for masked values.
Returns
-------
result : bool
    True if `x` is a MaskedArray with masked values, False otherwise.
Examples
--------
>>> import numpy.ma as ma
>>> x = ma.masked_equal([0, 1, 0, 2, 3], 0)
>>> x
masked_array(data=[--, 1, --, 2, 3],
             mask=[ True, False,  True, False, False],
       fill_value=0)
>>> ma.is_masked(x)
True
>>> x = ma.masked_equal([0, 1, 0, 2, 3], 42)
>>> x
masked_array(data=[0, 1, 0, 2, 3],
             mask=False,
       fill_value=42)
>>> ma.is_masked(x)
False
Always returns False if `x` isn't a MaskedArray.
>>> x = [False, True, False]
>>> ma.is_masked(x)
False
>>> x = 'a string'
>>> ma.is_masked(x)
False
Definition at line 6677 of file core.py.
References getmask().
is_string_or_list_of_strings()
numpy.ma.core.is_string_or_list_of_strings (val)
Definition at line 783 of file core.py.
isMaskedArray()
numpy.ma.core.isMaskedArray (x)
Test whether input is an instance of MaskedArray.
This function returns True if `x` is an instance of MaskedArray
and returns False otherwise.  Any object is accepted as input.
Parameters
----------
x : object
    Object to test.
Returns
-------
result : bool
    True if `x` is a MaskedArray.
See Also
--------
isMA : Alias to isMaskedArray.
isarray : Alias to isMaskedArray.
Examples
--------
>>> import numpy.ma as ma
>>> a = np.eye(3, 3)
>>> a
array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])
>>> m = ma.masked_values(a, 0)
>>> m
masked_array(
  data=[[1.0, --, --],
        [--, 1.0, --],
        [--, --, 1.0]],
  mask=[[False,  True,  True],
        [ True, False,  True],
        [ True,  True, False]],
  fill_value=0.0)
>>> ma.isMaskedArray(a)
False
>>> ma.isMaskedArray(m)
True
>>> ma.isMaskedArray([0, 1, 2])
False
Definition at line 6485 of file core.py.
Referenced by masked_object().
left_shift()
numpy.ma.core.left_shift (a, n)
Shift the bits of an integer to the left.
This is the masked array version of `numpy.left_shift`, for details
see that function.
See Also
--------
numpy.left_shift
Definition at line 7205 of file core.py.
References filled(), and getmask().
make_mask()
numpy.ma.core.make_mask (m, copy = False, shrink = True, dtype = MaskType)
Create a boolean mask from an array.
Return `m` as a boolean mask, creating a copy if necessary or requested.
The function can accept any sequence that is convertible to integers,
or ``nomask``.  Does not require that contents must be 0s and 1s, values
of 0 are interpreted as False, everything else as True.
Parameters
----------
m : array_like
    Potential mask.
copy : bool, optional
    Whether to return a copy of `m` (True) or `m` itself (False).
shrink : bool, optional
    Whether to shrink `m` to ``nomask`` if all its values are False.
dtype : dtype, optional
    Data-type of the output mask. By default, the output mask has a
    dtype of MaskType (bool). If the dtype is flexible, each field has
    a boolean dtype. This is ignored when `m` is ``nomask``, in which
    case ``nomask`` is always returned.
Returns
-------
result : ndarray
    A boolean mask derived from `m`.
Examples
--------
>>> import numpy.ma as ma
>>> m = [True, False, True, True]
>>> ma.make_mask(m)
array([ True, False,  True,  True])
>>> m = [1, 0, 1, 1]
>>> ma.make_mask(m)
array([ True, False,  True,  True])
>>> m = [1, 0, 2, -3]
>>> ma.make_mask(m)
array([ True, False,  True,  True])
Effect of the `shrink` parameter.
>>> m = np.zeros(4)
>>> m
array([0., 0., 0., 0.])
>>> ma.make_mask(m)
False
>>> ma.make_mask(m, shrink=False)
array([False, False, False, False])
Using a flexible `dtype`.
>>> m = [1, 0, 1, 1]
>>> n = [0, 1, 0, 0]
>>> arr = []
>>> for man, mouse in zip(m, n):
...     arr.append((man, mouse))
>>> arr
[(1, 0), (0, 1), (1, 0), (1, 0)]
>>> dtype = np.dtype({'names':['man', 'mouse'],
...                   'formats':[np.int64, np.int64]})
>>> arr = np.array(arr, dtype=dtype)
>>> arr
array([(1, 0), (0, 1), (1, 0), (1, 0)],
      dtype=[('man', '<i8'), ('mouse', '<i8')])
>>> ma.make_mask(arr, dtype=dtype)
array([(True, False), (False, True), (True, False), (True, False)],
      dtype=[('man', '|b1'), ('mouse', '|b1')])
Definition at line 1555 of file core.py.
References _shrink_mask(), filled(), and make_mask_descr().
Referenced by choose(), inner(), mask_or(), masked_object(), masked_where(), numpy.ma.core.MaskedArray.put(), and numpy.ma.core._MaskedBinaryOperation.reduce().
make_mask_descr()
numpy.ma.core.make_mask_descr (ndtype)
Construct a dtype description list from a given dtype.
Returns a new dtype object, with the type of all fields in `ndtype` to a
boolean type. Field names are not altered.
Parameters
----------
ndtype : dtype
    The dtype to convert.
Returns
-------
result : dtype
    A dtype that looks like `ndtype`, the type of all fields is boolean.
Examples
--------
>>> import numpy.ma as ma
>>> dtype = np.dtype({'names':['foo', 'bar'],
...                   'formats':[np.float32, np.int64]})
>>> dtype
dtype([('foo', '<f4'), ('bar', '<i8')])
>>> ma.make_mask_descr(dtype)
dtype([('foo', '|b1'), ('bar', '|b1')])
>>> ma.make_mask_descr(np.float32)
dtype('bool')
Definition at line 1329 of file core.py.
References _replace_dtype_fields().
Referenced by numpy.ma.core.MaskedArray.__array_finalize__(), numpy.ma.core.MaskedArray.__new__(), numpy.ma.core.MaskedArray.__setitem__(), numpy.ma.core.MaskedArray.__setstate__(), _mareconstruct(), make_mask(), make_mask_none(), numpy.ma.extras.masked_all(), and numpy.ma.extras.masked_all_like().
make_mask_none()
numpy.ma.core.make_mask_none (newshape, dtype = None)
Return a boolean mask of the given shape, filled with False.
This function returns a boolean ndarray with all entries False, that can
be used in common mask manipulations. If a complex dtype is specified, the
type of each field is converted to a boolean type.
Parameters
----------
newshape : tuple
    A tuple indicating the shape of the mask.
dtype : {None, dtype}, optional
    If None, use a MaskType instance. Otherwise, use a new datatype with
    the same fields as `dtype`, converted to boolean types.
Returns
-------
result : ndarray
    An ndarray of appropriate shape and dtype, filled with False.
See Also
--------
make_mask : Create a boolean mask from an array.
make_mask_descr : Construct a dtype description list from a given dtype.
Examples
--------
>>> import numpy.ma as ma
>>> ma.make_mask_none((3,))
array([False, False, False])
Defining a more complex dtype.
>>> dtype = np.dtype({'names':['foo', 'bar'],
...                   'formats':[np.float32, np.int64]})
>>> dtype
dtype([('foo', '<f4'), ('bar', '<i8')])
>>> ma.make_mask_none((3,), dtype=dtype)
array([(False, False), (False, False), (False, False)],
      dtype=[('foo', '|b1'), ('bar', '|b1')])
Definition at line 1644 of file core.py.
References make_mask_descr().
Referenced by numpy.ma.core.MaskedArray.__iadd__(), numpy.ma.core.MaskedArray.__imul__(), numpy.ma.core.MaskedArray.__isub__(), numpy.ma.core.MaskedArray.__setitem__(), numpy.ma.core.MaskedArray.__setmask__(), getmaskarray(), masked_invalid(), numpy.ma.core.MaskedArray.max(), numpy.ma.core.MaskedArray.mean(), numpy.ma.core.MaskedArray.min(), numpy.ma.core.MaskedArray.prod(), putmask(), numpy.ma.core.MaskedArray.sum(), and numpy.ma.core.MaskedArray.toflex().
mask_or()
numpy.ma.core.mask_or (m1, m2, copy = False, shrink = True)
Combine two masks with the ``logical_or`` operator.
The result may be a view on `m1` or `m2` if the other is `nomask`
(i.e. False).
Parameters
----------
m1, m2 : array_like
    Input masks.
copy : bool, optional
    If copy is False and one of the inputs is `nomask`, return a view
    of the other input mask. Defaults to False.
shrink : bool, optional
    Whether to shrink the output to `nomask` if all its values are
    False. Defaults to True.
Returns
-------
mask : output mask
    The result masks values that are masked in either `m1` or `m2`.
Raises
------
ValueError
    If `m1` and `m2` have different flexible dtypes.
Examples
--------
>>> m1 = np.ma.make_mask([0, 1, 1, 0])
>>> m2 = np.ma.make_mask([1, 0, 0, 0])
>>> np.ma.mask_or(m1, m2)
array([ True,  True,  True, False])
Definition at line 1704 of file core.py.
References is_mask(), and make_mask().
Referenced by numpy.ma.core.MaskedArray.__idiv__(), numpy.ma.core.MaskedArray.__ifloordiv__(), numpy.ma.core.MaskedArray.__ipow__(), numpy.ma.core.MaskedArray.__itruediv__(), numpy.ma.core.MaskedArray.__setitem__(), numpy.ma.core.MaskedArray._comparison(), allclose(), allequal(), numpy.ma.testutils.almost(), numpy.ma.testutils.approx(), numpy.ma.testutils.assert_array_compare(), choose(), masked_object(), masked_where(), numpy.ma.extras.polyfit(), power(), and numpy.ma.core.MaskedArray.var().
masked_equal()
numpy.ma.core.masked_equal (x, value, copy = True)
Mask an array where equal to a given value.
Return a MaskedArray, masked where the data in array `x` are
equal to `value`. The fill_value of the returned MaskedArray
is set to `value`.
For floating point arrays, consider using ``masked_values(x, value)``.
See Also
--------
masked_where : Mask where a condition is met.
masked_values : Mask using floating point equality.
Examples
--------
>>> import numpy.ma as ma
>>> a = np.arange(4)
>>> a
array([0, 1, 2, 3])
>>> ma.masked_equal(a, 2)
masked_array(data=[0, 1, --, 3],
             mask=[False, False,  True, False],
       fill_value=2)
Definition at line 2080 of file core.py.
References masked_where().
masked_greater()
numpy.ma.core.masked_greater (x, value, copy = True)
Mask an array where greater than a given value.
This function is a shortcut to ``masked_where``, with
`condition` = (x > value).
See Also
--------
masked_where : Mask where a condition is met.
Examples
--------
>>> import numpy.ma as ma
>>> a = np.arange(4)
>>> a
array([0, 1, 2, 3])
>>> ma.masked_greater(a, 2)
masked_array(data=[0, 1, 2, --],
             mask=[False, False, False,  True],
       fill_value=999999)
Definition at line 1950 of file core.py.
References masked_where().
masked_greater_equal()
numpy.ma.core.masked_greater_equal (x, value, copy = True)
Mask an array where greater than or equal to a given value.
This function is a shortcut to ``masked_where``, with
`condition` = (x >= value).
See Also
--------
masked_where : Mask where a condition is met.
Examples
--------
>>> import numpy.ma as ma
>>> a = np.arange(4)
>>> a
array([0, 1, 2, 3])
>>> ma.masked_greater_equal(a, 2)
masked_array(data=[0, 1, --, --],
             mask=[False, False,  True,  True],
       fill_value=999999)
Definition at line 1976 of file core.py.
References masked_where().
masked_inside()
numpy.ma.core.masked_inside (x, v1, v2, copy = True)
Mask an array inside a given interval.
Shortcut to ``masked_where``, where `condition` is True for `x` inside
the interval [v1,v2] (v1 <= x <= v2).  The boundaries `v1` and `v2`
can be given in either order.
See Also
--------
masked_where : Mask where a condition is met.
Notes
-----
The array `x` is prefilled with its filling value.
Examples
--------
>>> import numpy.ma as ma
>>> x = [0.31, 1.2, 0.01, 0.2, -0.4, -1.1]
>>> ma.masked_inside(x, -0.3, 0.3)
masked_array(data=[0.31, 1.2, --, --, -0.4, -1.1],
             mask=[False, False,  True,  True, False, False],
       fill_value=1e+20)
The order of `v1` and `v2` doesn't matter.
>>> ma.masked_inside(x, 0.3, -0.3)
masked_array(data=[0.31, 1.2, --, --, -0.4, -1.1],
             mask=[False, False,  True,  True, False, False],
       fill_value=1e+20)
Definition at line 2112 of file core.py.
References filled(), and masked_where().
masked_invalid()
numpy.ma.core.masked_invalid (a, copy = True)
Mask an array where invalid values occur (NaNs or infs).
This function is a shortcut to ``masked_where``, with
`condition` = ~(np.isfinite(a)). Any pre-existing mask is conserved.
Only applies to arrays with a dtype where NaNs or infs make sense
(i.e. floating point types), but accepts any array_like object.
See Also
--------
masked_where : Mask where a condition is met.
Examples
--------
>>> import numpy.ma as ma
>>> a = np.arange(5, dtype=float)
>>> a[2] = np.NaN
>>> a[3] = np.PINF
>>> a
array([ 0.,  1., nan, inf,  4.])
>>> ma.masked_invalid(a)
masked_array(data=[0.0, 1.0, --, --, 4.0],
             mask=[False, False,  True,  True, False],
       fill_value=1e+20)
Definition at line 2332 of file core.py.
References make_mask_none(), and masked_where().
masked_less()
numpy.ma.core.masked_less (x, value, copy = True)
Mask an array where less than a given value.
This function is a shortcut to ``masked_where``, with
`condition` = (x < value).
See Also
--------
masked_where : Mask where a condition is met.
Examples
--------
>>> import numpy.ma as ma
>>> a = np.arange(4)
>>> a
array([0, 1, 2, 3])
>>> ma.masked_less(a, 2)
masked_array(data=[--, --, 2, 3],
             mask=[ True,  True, False, False],
       fill_value=999999)
Definition at line 2002 of file core.py.
References masked_where().
masked_less_equal()
numpy.ma.core.masked_less_equal (x, value, copy = True)
Mask an array where less than or equal to a given value.
This function is a shortcut to ``masked_where``, with
`condition` = (x <= value).
See Also
--------
masked_where : Mask where a condition is met.
Examples
--------
>>> import numpy.ma as ma
>>> a = np.arange(4)
>>> a
array([0, 1, 2, 3])
>>> ma.masked_less_equal(a, 2)
masked_array(data=[--, --, --, 3],
             mask=[ True,  True,  True, False],
       fill_value=999999)
Definition at line 2028 of file core.py.
References masked_where().
masked_not_equal()
numpy.ma.core.masked_not_equal (x, value, copy = True)
Mask an array where `not` equal to a given value.
This function is a shortcut to ``masked_where``, with
`condition` = (x != value).
See Also
--------
masked_where : Mask where a condition is met.
Examples
--------
>>> import numpy.ma as ma
>>> a = np.arange(4)
>>> a
array([0, 1, 2, 3])
>>> ma.masked_not_equal(a, 2)
masked_array(data=[--, --, 2, --],
             mask=[ True,  True, False,  True],
       fill_value=999999)
Definition at line 2054 of file core.py.
References masked_where().
masked_object()
numpy.ma.core.masked_object (x, value, copy = True, shrink = True)
Mask the array `x` where the data are exactly equal to value.
This function is similar to `masked_values`, but only suitable
for object arrays: for floating point, use `masked_values` instead.
Parameters
----------
x : array_like
    Array to mask
value : object
    Comparison value
copy : {True, False}, optional
    Whether to return a copy of `x`.
shrink : {True, False}, optional
    Whether to collapse a mask full of False to nomask
Returns
-------
result : MaskedArray
    The result of masking `x` where equal to `value`.
See Also
--------
masked_where : Mask where a condition is met.
masked_equal : Mask where equal to a given value (integers).
masked_values : Mask using floating point equality.
Examples
--------
>>> import numpy.ma as ma
>>> food = np.array(['green_eggs', 'ham'], dtype=object)
>>> # don't eat spoiled food
>>> eat = ma.masked_object(food, 'green_eggs')
>>> eat
masked_array(data=[--, 'ham'],
             mask=[ True, False],
       fill_value='green_eggs',
            dtype=object)
>>> # plain ol` ham is boring
>>> fresh_food = np.array(['cheese', 'ham', 'pineapple'], dtype=object)
>>> eat = ma.masked_object(fresh_food, 'green_eggs')
>>> eat
masked_array(data=['cheese', 'ham', 'pineapple'],
             mask=False,
       fill_value='green_eggs',
            dtype=object)
Note that `mask` is set to ``nomask`` if possible.
>>> eat
masked_array(data=['cheese', 'ham', 'pineapple'],
             mask=False,
       fill_value='green_eggs',
            dtype=object)
Definition at line 2192 of file core.py.
References isMaskedArray(), make_mask(), and mask_or().
masked_outside()
numpy.ma.core.masked_outside (x, v1, v2, copy = True)
Mask an array outside a given interval.
Shortcut to ``masked_where``, where `condition` is True for `x` outside
the interval [v1,v2] (x < v1)|(x > v2).
The boundaries `v1` and `v2` can be given in either order.
See Also
--------
masked_where : Mask where a condition is met.
Notes
-----
The array `x` is prefilled with its filling value.
Examples
--------
>>> import numpy.ma as ma
>>> x = [0.31, 1.2, 0.01, 0.2, -0.4, -1.1]
>>> ma.masked_outside(x, -0.3, 0.3)
masked_array(data=[--, --, 0.01, 0.2, --, --],
             mask=[ True,  True, False, False,  True,  True],
       fill_value=1e+20)
The order of `v1` and `v2` doesn't matter.
>>> ma.masked_outside(x, 0.3, -0.3)
masked_array(data=[--, --, 0.01, 0.2, --, --],
             mask=[ True,  True, False, False,  True,  True],
       fill_value=1e+20)
Definition at line 2152 of file core.py.
References filled(), and masked_where().
masked_values()
numpy.ma.core.masked_values (x, value, rtol = 1e-5, atol = 1e-8, copy = True, shrink = True)
Mask using floating point equality.
Return a MaskedArray, masked where the data in array `x` are approximately
equal to `value`, determined using `isclose`. The default tolerances for
`masked_values` are the same as those for `isclose`.
For integer types, exact equality is used, in the same way as
`masked_equal`.
The fill_value is set to `value` and the mask is set to ``nomask`` if
possible.
Parameters
----------
x : array_like
    Array to mask.
value : float
    Masking value.
rtol, atol : float, optional
    Tolerance parameters passed on to `isclose`
copy : bool, optional
    Whether to return a copy of `x`.
shrink : bool, optional
    Whether to collapse a mask full of False to ``nomask``.
Returns
-------
result : MaskedArray
    The result of masking `x` where approximately equal to `value`.
See Also
--------
masked_where : Mask where a condition is met.
masked_equal : Mask where equal to a given value (integers).
Examples
--------
>>> import numpy.ma as ma
>>> x = np.array([1, 1.1, 2, 1.1, 3])
>>> ma.masked_values(x, 1.1)
masked_array(data=[1.0, --, 2.0, --, 3.0],
             mask=[False,  True, False,  True, False],
       fill_value=1.1)
Note that `mask` is set to ``nomask`` if possible.
>>> ma.masked_values(x, 2.1)
masked_array(data=[1. , 1.1, 2. , 1.1, 3. ],
             mask=False,
       fill_value=2.1)
Unlike `masked_equal`, `masked_values` can perform approximate equalities.
>>> ma.masked_values(x, 2.1, atol=1e-1)
masked_array(data=[1.0, 1.1, --, 1.1, 3.0],
             mask=[False, False,  True, False, False],
       fill_value=2.1)
Definition at line 2260 of file core.py.
References filled().
masked_where()
numpy.ma.core.masked_where (condition, a, copy = True)
Masking functions #.
Mask an array where a condition is met.
Return `a` as an array masked where `condition` is True.
Any masked values of `a` or `condition` are also masked in the output.
Parameters
----------
condition : array_like
    Masking condition.  When `condition` tests floating point values for
    equality, consider using ``masked_values`` instead.
a : array_like
    Array to mask.
copy : bool
    If True (default) make a copy of `a` in the result.  If False modify
    `a` in place and return a view.
Returns
-------
result : MaskedArray
    The result of masking `a` where `condition` is True.
See Also
--------
masked_values : Mask using floating point equality.
masked_equal : Mask where equal to a given value.
masked_not_equal : Mask where `not` equal to a given value.
masked_less_equal : Mask where less than or equal to a given value.
masked_greater_equal : Mask where greater than or equal to a given value.
masked_less : Mask where less than a given value.
masked_greater : Mask where greater than a given value.
masked_inside : Mask inside a given interval.
masked_outside : Mask outside a given interval.
masked_invalid : Mask invalid values (NaNs or infs).
Examples
--------
>>> import numpy.ma as ma
>>> a = np.arange(4)
>>> a
array([0, 1, 2, 3])
>>> ma.masked_where(a <= 2, a)
masked_array(data=[--, --, --, 3],
             mask=[ True,  True,  True, False],
       fill_value=999999)
Mask array `b` conditional on `a`.
>>> b = ['a', 'b', 'c', 'd']
>>> ma.masked_where(a == 2, b)
masked_array(data=['a', 'b', --, 'd'],
             mask=[False, False,  True, False],
       fill_value='N/A',
            dtype='<U1')
Effect of the `copy` argument.
>>> c = ma.masked_where(a <= 2, a)
>>> c
masked_array(data=[--, --, --, 3],
             mask=[ True,  True,  True, False],
       fill_value=999999)
>>> c[0] = 99
>>> c
masked_array(data=[99, --, --, 3],
             mask=[False,  True,  True, False],
       fill_value=999999)
>>> a
array([0, 1, 2, 3])
>>> c = ma.masked_where(a <= 2, a, copy=False)
>>> c[0] = 99
>>> c
masked_array(data=[99, --, --, 3],
             mask=[False,  True,  True, False],
       fill_value=999999)
>>> a
array([99,  1,  2,  3])
When `condition` or `a` contain masked values.
>>> a = np.arange(4)
>>> a = ma.masked_where(a == 2, a)
>>> a
masked_array(data=[0, 1, --, 3],
             mask=[False, False,  True, False],
       fill_value=999999)
>>> b = np.arange(4)
>>> b = ma.masked_where(b == 0, b)
>>> b
masked_array(data=[--, 1, 2, 3],
             mask=[ True, False, False, False],
       fill_value=999999)
>>> ma.masked_where(a == 3, b)
masked_array(data=[--, 1, --, --],
             mask=[ True, False,  True,  True],
       fill_value=999999)
Definition at line 1828 of file core.py.
References _shrink_mask(), getmask(), make_mask(), and mask_or().
Referenced by masked_equal(), masked_greater(), masked_greater_equal(), masked_inside(), masked_invalid(), masked_less(), masked_less_equal(), masked_not_equal(), and masked_outside().
max()
numpy.ma.core.max (obj, axis = None, out = None, fill_value = None, keepdims = np._NoValue)
Definition at line 6814 of file core.py.
maximum_fill_value()
numpy.ma.core.maximum_fill_value (obj)
Return the minimum value that can be represented by the dtype of an object.
This function is useful for calculating a fill value suitable for
taking the maximum of an array with a given dtype.
Parameters
----------
obj : ndarray, dtype or scalar
    An object that can be queried for it's numeric type.
Returns
-------
val : scalar
    The minimum representable value.
Raises
------
TypeError
    If `obj` isn't a suitable numeric type.
See Also
--------
minimum_fill_value : The inverse function.
set_fill_value : Set the filling value of a masked array.
MaskedArray.fill_value : Return current fill value.
Examples
--------
>>> import numpy.ma as ma
>>> a = np.int8()
>>> ma.maximum_fill_value(a)
-128
>>> a = np.int32()
>>> ma.maximum_fill_value(a)
-2147483648
An array of numeric data can also be passed.
>>> a = np.array([1, 2, 3], dtype=np.int8)
>>> ma.maximum_fill_value(a)
-128
>>> a = np.array([1, 2, 3], dtype=np.float32)
>>> ma.maximum_fill_value(a)
-inf
Definition at line 350 of file core.py.
Referenced by numpy.ma.core.MaskedArray.argmax(), numpy.ma.core.MaskedArray.argsort(), and numpy.ma.core.MaskedArray.max().
min()
numpy.ma.core.min (obj, axis = None, out = None, fill_value = None, keepdims = np._NoValue)
Definition at line 6802 of file core.py.
minimum_fill_value()
numpy.ma.core.minimum_fill_value (obj)
Return the maximum value that can be represented by the dtype of an object.
This function is useful for calculating a fill value suitable for
taking the minimum of an array with a given dtype.
Parameters
----------
obj : ndarray, dtype or scalar
    An object that can be queried for it's numeric type.
Returns
-------
val : scalar
    The maximum representable value.
Raises
------
TypeError
    If `obj` isn't a suitable numeric type.
See Also
--------
maximum_fill_value : The inverse function.
set_fill_value : Set the filling value of a masked array.
MaskedArray.fill_value : Return current fill value.
Examples
--------
>>> import numpy.ma as ma
>>> a = np.int8()
>>> ma.minimum_fill_value(a)
127
>>> a = np.int32()
>>> ma.minimum_fill_value(a)
2147483647
An array of numeric data can also be passed.
>>> a = np.array([1, 2, 3], dtype=np.int8)
>>> ma.minimum_fill_value(a)
127
>>> a = np.array([1, 2, 3], dtype=np.float32)
>>> ma.minimum_fill_value(a)
inf
Definition at line 299 of file core.py.
Referenced by numpy.ma.core.MaskedArray.argmin(), numpy.ma.core.MaskedArray.argsort(), and numpy.ma.core.MaskedArray.min().
ndim()
numpy.ma.core.ndim (obj)
maskedarray version of the numpy function.
Definition at line 7441 of file core.py.
References getdata().
outer()
numpy.ma.core.outer (a, b)
Definition at line 7945 of file core.py.
power()
numpy.ma.core.power (a, b, third = None)
Returns element-wise base array raised to power from second array.
This is the masked array version of `numpy.power`. For details see
`numpy.power`.
See Also
--------
numpy.power
Notes
-----
The *out* argument to `numpy.power` is not supported, `third` has to be
None.
Examples
--------
>>> import numpy.ma as ma
>>> x = [11.2, -3.973, 0.801, -1.41]
>>> mask = [0, 0, 0, 1]
>>> masked_x = ma.masked_array(x, mask)
>>> masked_x
masked_array(data=[11.2, -3.973, 0.801, --],
         mask=[False, False, False,  True],
   fill_value=1e+20)
>>> ma.power(masked_x, 2)
masked_array(data=[125.43999999999998, 15.784728999999999,
               0.6416010000000001, --],
         mask=[False, False, False,  True],
   fill_value=1e+20)
>>> y = [-0.5, 2, 0, 17]
>>> masked_y = ma.masked_array(y, mask)
>>> masked_y
masked_array(data=[-0.5, 2.0, 0.0, --],
         mask=[False, False, False,  True],
   fill_value=1e+20)
>>> ma.power(masked_x, masked_y)
masked_array(data=[0.29880715233359845, 15.784728999999999, 1.0, --],
         mask=[False, False, False,  True],
   fill_value=1e+20)
Definition at line 6921 of file core.py.
References _deprecate_argsort_axis(), getdata(), getmask(), and mask_or().
Referenced by numpy.ma.core.MaskedArray.__pow__(), and numpy.ma.core.MaskedArray.__rpow__().
ptp()
numpy.ma.core.ptp (obj, axis = None, out = None, fill_value = None, keepdims = np._NoValue)
Definition at line 6827 of file core.py.
put()
numpy.ma.core.put (a, indices, values, mode = 'raise')
Set storage-indexed locations to corresponding values.
This function is equivalent to `MaskedArray.put`, see that method
for details.
See Also
--------
MaskedArray.put
Definition at line 7262 of file core.py.
References put().
Referenced by put().
putmask()
numpy.ma.core.putmask (a, mask, values)
Changes elements of an array based on conditional and input values.
This is the masked array version of `numpy.putmask`, for details see
`numpy.putmask`.
See Also
--------
numpy.putmask
Notes
-----
Using a masked array as `values` will **not** transform a `ndarray` into
a `MaskedArray`.
Definition at line 7281 of file core.py.
References getdata(), getmask(), getmaskarray(), and make_mask_none().
reshape()
numpy.ma.core.reshape (a, new_shape, order = 'C')
Returns an array containing the same data with a new shape.
Refer to `MaskedArray.reshape` for full documentation.
See Also
--------
MaskedArray.reshape : equivalent function
Definition at line 7358 of file core.py.
References reshape().
Referenced by numpy.ma.extras.isin(), and reshape().
resize()
numpy.ma.core.resize (x, new_shape)
Return a new masked array with the specified size and shape.
This is the masked equivalent of the `numpy.resize` function. The new
array is filled with repeated copies of `x` (in the order that the
data are stored in memory). If `x` is masked, the new array will be
masked, and the new mask will be a repetition of the old one.
See Also
--------
numpy.resize : Equivalent function in the top level NumPy module.
Examples
--------
>>> import numpy.ma as ma
>>> a = ma.array([[1, 2] ,[3, 4]])
>>> a[0, 1] = ma.masked
>>> a
masked_array(
  data=[[1, --],
        [3, 4]],
  mask=[[False,  True],
        [False, False]],
  fill_value=999999)
>>> np.resize(a, (3, 3))
masked_array(
  data=[[1, 2, 3],
        [4, 1, 2],
        [3, 4, 1]],
  mask=False,
  fill_value=999999)
>>> ma.resize(a, (3, 3))
masked_array(
  data=[[1, --, 3],
        [4, 1, --],
        [3, 4, 1]],
  mask=[[False,  True, False],
        [False, False,  True],
        [False, False, False]],
  fill_value=999999)
A MaskedArray is always returned, regardless of the input type.
>>> a = np.array([[1, 2] ,[3, 4]])
>>> ma.resize(a, (3, 3))
masked_array(
  data=[[1, 2, 3],
        [4, 1, 2],
        [3, 4, 1]],
  mask=False,
  fill_value=999999)
Definition at line 7377 of file core.py.
References get_masked_subclass(), and getmask().
right_shift()
numpy.ma.core.right_shift (a, n)
Shift the bits of an integer to the right.
This is the masked array version of `numpy.right_shift`, for details
see that function.
See Also
--------
numpy.right_shift
Examples
--------
>>> import numpy.ma as ma
>>> x = [11, 3, 8, 1]
>>> mask = [0, 0, 0, 1]
>>> masked_x = ma.masked_array(x, mask)
>>> masked_x
masked_array(data=[11, 3, 8, --],
             mask=[False, False, False,  True],
       fill_value=999999)
>>> ma.right_shift(masked_x,1)
masked_array(data=[5, 1, 4, --],
             mask=[False, False, False,  True],
       fill_value=999999)
Definition at line 7226 of file core.py.
References filled(), and getmask().
round_()
numpy.ma.core.round_ (a, decimals = 0, out = None)
Return a copy of a, rounded to 'decimals' places.
When 'decimals' is negative, it specifies the number of positions
to the left of the decimal point.  The real and imaginary parts of
complex numbers are rounded separately. Nothing is done if the
array is not of float type and 'decimals' is greater than or equal
to 0.
Parameters
----------
decimals : int
    Number of decimals to round to. May be negative.
out : array_like
    Existing array to use for output.
    If not given, returns a default copy of a.
Notes
-----
If out is given and does not have a mask attribute, the mask of a
is lost!
Examples
--------
>>> import numpy.ma as ma
>>> x = [11.2, -3.973, 0.801, -1.41]
>>> mask = [0, 0, 0, 1]
>>> masked_x = ma.masked_array(x, mask)
>>> masked_x
masked_array(data=[11.2, -3.973, 0.801, --],
             mask=[False, False, False, True],
    fill_value=1e+20)
>>> ma.round_(masked_x)
masked_array(data=[11.0, -4.0, 1.0, --],
             mask=[False, False, False, True],
    fill_value=1e+20)
>>> ma.round(masked_x, decimals=1)
masked_array(data=[11.2, -4.0, 0.8, --],
             mask=[False, False, False, True],
    fill_value=1e+20)
>>> ma.round_(masked_x, decimals=-1)
masked_array(data=[10.0, -0.0, 0.0, --],
             mask=[False, False, False, True],
    fill_value=1e+20)
Definition at line 7769 of file core.py.
References getdata(), and getmask().
set_fill_value()
numpy.ma.core.set_fill_value (a, fill_value)
Set the filling value of a, if a is a masked array.
This function changes the fill value of the masked array `a` in place.
If `a` is not a masked array, the function returns silently, without
doing anything.
Parameters
----------
a : array_like
    Input array.
fill_value : dtype
    Filling value. A consistency test is performed to make sure
    the value is compatible with the dtype of `a`.
Returns
-------
None
    Nothing returned by this function.
See Also
--------
maximum_fill_value : Return the default fill value for a dtype.
MaskedArray.fill_value : Return current fill value.
MaskedArray.set_fill_value : Equivalent method.
Examples
--------
>>> import numpy.ma as ma
>>> a = np.arange(5)
>>> a
array([0, 1, 2, 3, 4])
>>> a = ma.masked_where(a < 3, a)
>>> a
masked_array(data=[--, --, --, 3, 4],
             mask=[ True,  True,  True, False, False],
       fill_value=999999)
>>> ma.set_fill_value(a, -999)
>>> a
masked_array(data=[--, --, --, 3, 4],
             mask=[ True,  True,  True, False, False],
       fill_value=-999)
Nothing happens if `a` is not a masked array.
>>> a = list(range(5))
>>> a
[0, 1, 2, 3, 4]
>>> ma.set_fill_value(a, 100)
>>> a
[0, 1, 2, 3, 4]
>>> a = np.arange(5)
>>> a
array([0, 1, 2, 3, 4])
>>> ma.set_fill_value(a, 100)
>>> a
array([0, 1, 2, 3, 4])
Definition at line 477 of file core.py.
shape()
numpy.ma.core.shape (obj)
Definition at line 7451 of file core.py.
size()
numpy.ma.core.size (obj, axis = None)
Definition at line 7457 of file core.py.
sort()
numpy.ma.core.sort (a, axis = -1, kind = None, order = None, endwith = True, fill_value = None)
Return a sorted copy of the masked array.
Equivalent to creating a copy of the array
and applying the  MaskedArray ``sort()`` method.
Refer to ``MaskedArray.sort`` for the full documentation
See Also
--------
MaskedArray.sort : equivalent method
Examples
--------
>>> import numpy.ma as ma
>>> x = [11.2, -3.973, 0.801, -1.41]
>>> mask = [0, 0, 0, 1]
>>> masked_x = ma.masked_array(x, mask)
>>> masked_x
masked_array(data=[11.2, -3.973, 0.801, --],
             mask=[False, False, False,  True],
       fill_value=1e+20)
>>> ma.sort(masked_x)
masked_array(data=[-3.973, 0.801, 11.2, --],
             mask=[False, False, False,  True],
       fill_value=1e+20)
Definition at line 7016 of file core.py.
take()
numpy.ma.core.take (a, indices, axis = None, out = None, mode = 'raise')
Definition at line 6914 of file core.py.
Referenced by numpy.ma.extras.apply_along_axis().
transpose()
numpy.ma.core.transpose (a, axes = None)
Permute the dimensions of an array.
This function is exactly equivalent to `numpy.transpose`.
See Also
--------
numpy.transpose : Equivalent function in top-level NumPy module.
Examples
--------
>>> import numpy.ma as ma
>>> x = ma.arange(4).reshape((2,2))
>>> x[1, 1] = ma.masked
>>> x
masked_array(
  data=[[0, 1],
        [2, --]],
  mask=[[False, False],
        [False,  True]],
  fill_value=999999)
>>> ma.transpose(x)
masked_array(
  data=[[0, 2],
        [1, --]],
  mask=[[False, False],
        [False,  True]],
  fill_value=999999)
Definition at line 7320 of file core.py.
References transpose().
Referenced by transpose().
where()
numpy.ma.core.where (condition, x = _NoValue, y = _NoValue)
Extra functions #.
Return a masked array with elements from `x` or `y`, depending on condition.
.. note::
    When only `condition` is provided, this function is identical to
    `nonzero`. The rest of this documentation covers only the case where
    all three arguments are provided.
Parameters
----------
condition : array_like, bool
    Where True, yield `x`, otherwise yield `y`.
x, y : array_like, optional
    Values from which to choose. `x`, `y` and `condition` need to be
    broadcastable to some shape.
Returns
-------
out : MaskedArray
    An masked array with `masked` elements where the condition is masked,
    elements from `x` where `condition` is True, and elements from `y`
    elsewhere.
See Also
--------
numpy.where : Equivalent function in the top-level NumPy module.
nonzero : The function that is called when x and y are omitted
Examples
--------
>>> x = np.ma.array(np.arange(9.).reshape(3, 3), mask=[[0, 1, 0],
...                                                    [1, 0, 1],
...                                                    [0, 1, 0]])
>>> x
masked_array(
  data=[[0.0, --, 2.0],
        [--, 4.0, --],
        [6.0, --, 8.0]],
  mask=[[False,  True, False],
        [ True, False,  True],
        [False,  True, False]],
  fill_value=1e+20)
>>> np.ma.where(x > 5, x, -3.1416)
masked_array(
  data=[[-3.1416, --, -3.1416],
        [--, -3.1416, --],
        [6.0, --, 8.0]],
  mask=[[False,  True, False],
        [ True, False,  True],
        [False,  True, False]],
  fill_value=1e+20)
Definition at line 7603 of file core.py.
References _shrink_mask(), filled(), getdata(), and getmaskarray().
Variable Documentation
__all__
list numpy.ma.core.__all__ private
Definition at line 45 of file core.py.
__doc__
numpy.ma.core.__doc__ private
Definition at line 6674 of file core.py.
_legacy_print_templates
numpy.ma.core._legacy_print_templates protected
Initial value:
=  dict(
    long_std=textwrap.dedent(),
    long_flx=textwrap.dedent(),
    short_std=textwrap.dedent(),
    short_flx=textwrap.dedent()
)
Definition at line 2441 of file core.py.
abs
numpy.ma.core.abs = _MaskedUnaryOperation(umath.absolute)
Definition at line 1210 of file core.py.
add
numpy.ma.core.add = _MaskedBinaryOperation(umath.add)
Definition at line 1240 of file core.py.
all
numpy.ma.core.all = _frommethod('all')
Definition at line 6885 of file core.py.
alltrue
numpy.ma.core.alltrue = _MaskedBinaryOperation(umath.logical_and, 1, 1).reduce
Definition at line 1257 of file core.py.
angle
numpy.ma.core.angle = _MaskedUnaryOperation(angle)
Definition at line 1211 of file core.py.
anomalies
numpy.ma.core.anomalies = _frommethod('anom')
Definition at line 6886 of file core.py.
any
numpy.ma.core.any = _frommethod('any')
Definition at line 6887 of file core.py.
arange
numpy.ma.core.arange
Initial value:
=  _convert2ma(
    'arange',
    params=dict(fill_value=None, hardmask=False),
    np_ret='arange : ndarray',
    np_ma_ret='arange : MaskedArray',
)
Definition at line 8450 of file core.py.
arccos
numpy.ma.core.arccos
Initial value:
=  _MaskedUnaryOperation(umath.arccos, 0.0,
                               _DomainCheckInterval(-1.0, 1.0))
Definition at line 1232 of file core.py.
arccosh
numpy.ma.core.arccosh
Initial value:
=  _MaskedUnaryOperation(umath.arccosh, 1.0,
                                _DomainGreaterEqual(1.0))
Definition at line 1234 of file core.py.
arcsin
numpy.ma.core.arcsin
Initial value:
=  _MaskedUnaryOperation(umath.arcsin, 0.0,
                               _DomainCheckInterval(-1.0, 1.0))
Definition at line 1230 of file core.py.
arcsinh
numpy.ma.core.arcsinh = _MaskedUnaryOperation(umath.arcsinh)
Definition at line 1206 of file core.py.
arctan
numpy.ma.core.arctan = _MaskedUnaryOperation(umath.arctan)
Definition at line 1205 of file core.py.
arctan2
numpy.ma.core.arctan2 = _MaskedBinaryOperation(umath.arctan2, 0.0, 1.0)
Definition at line 1243 of file core.py.
arctanh
numpy.ma.core.arctanh
Initial value:
=  _MaskedUnaryOperation(umath.arctanh, 0.0,
                                _DomainCheckInterval(-1.0 + 1e-15, 1.0 - 1e-15))
Definition at line 1236 of file core.py.
argmax
numpy.ma.core.argmax = _frommethod('argmax')
Definition at line 6999 of file core.py.
argmin
numpy.ma.core.argmin = _frommethod('argmin')
Definition at line 6998 of file core.py.
around
numpy.ma.core.around = _MaskedUnaryOperation(np.round_)
Definition at line 1216 of file core.py.
bitwise_and
numpy.ma.core.bitwise_and = _MaskedBinaryOperation(umath.bitwise_and)
Definition at line 1261 of file core.py.
bitwise_or
numpy.ma.core.bitwise_or = _MaskedBinaryOperation(umath.bitwise_or)
Definition at line 1262 of file core.py.
bitwise_xor
numpy.ma.core.bitwise_xor = _MaskedBinaryOperation(umath.bitwise_xor)
Definition at line 1263 of file core.py.
ceil
numpy.ma.core.ceil = _MaskedUnaryOperation(umath.ceil)
Definition at line 1215 of file core.py.
clip
numpy.ma.core.clip
Initial value:
=  _convert2ma(
    'clip',
    params=dict(fill_value=None, hardmask=False),
    np_ret='clipped_array : ndarray',
    np_ma_ret='clipped_array : MaskedArray',
)
Definition at line 8456 of file core.py.
compress
numpy.ma.core.compress = _frommethod('compress', reversed=True)
Definition at line 6888 of file core.py.
conjugate
numpy.ma.core.conjugate = _MaskedUnaryOperation(umath.conjugate)
Definition at line 1202 of file core.py.
copy
numpy.ma.core.copy = _frommethod('copy')
Definition at line 6891 of file core.py.
cos
numpy.ma.core.cos = _MaskedUnaryOperation(umath.cos)
Definition at line 1204 of file core.py.
cosh
numpy.ma.core.cosh = _MaskedUnaryOperation(umath.cosh)
Definition at line 1208 of file core.py.
count
numpy.ma.core.count = _frommethod('count')
Definition at line 6912 of file core.py.
cumprod
numpy.ma.core.cumprod = _frommethod('cumprod')
Definition at line 6889 of file core.py.
cumsum
numpy.ma.core.cumsum = _frommethod('cumsum')
Definition at line 6890 of file core.py.
default_filler
dict numpy.ma.core.default_filler
Initial value:
=  {'b': True,
                  'c': 1.e20 + 0.0j,
                  'f': 1.e20,
                  'i': 999999,
                  'O': '?',
                  'S': b'N/A',
                  'u': 999999,
                  'V': b'???',
                  'U': 'N/A'
                  }
Definition at line 170 of file core.py.
diagonal
numpy.ma.core.diagonal = _frommethod('diagonal')
Definition at line 6892 of file core.py.
divide
numpy.ma.core.divide = _DomainedBinaryOperation(umath.divide, _DomainSafeDivide(), 0, 1)
Definition at line 1267 of file core.py.
empty
numpy.ma.core.empty
Initial value:
=  _convert2ma(
    'empty',
    params=dict(fill_value=None, hardmask=False),
    np_ret='out : ndarray',
    np_ma_ret='out : MaskedArray',
)
Definition at line 8462 of file core.py.
empty_like
numpy.ma.core.empty_like
Initial value:
=  _convert2ma(
    'empty_like',
    np_ret='out : ndarray',
    np_ma_ret='out : MaskedArray',
)
Definition at line 8468 of file core.py.
equal
numpy.ma.core.equal = _MaskedBinaryOperation(umath.equal)
Definition at line 1244 of file core.py.
exp
numpy.ma.core.exp = _MaskedUnaryOperation(umath.exp)
Definition at line 1201 of file core.py.
fabs
numpy.ma.core.fabs = _MaskedUnaryOperation(umath.fabs)
Definition at line 1212 of file core.py.
float_types_list
list numpy.ma.core.float_types_list
Initial value:
=  [np.half, np.single, np.double, np.longdouble,
                    np.csingle, np.cdouble, np.clongdouble]
Definition at line 187 of file core.py.
floor
numpy.ma.core.floor = _MaskedUnaryOperation(umath.floor)
Definition at line 1214 of file core.py.
floor_divide
numpy.ma.core.floor_divide
Initial value:
=  _DomainedBinaryOperation(umath.floor_divide,
                                        _DomainSafeDivide(), 0, 1)
Definition at line 1270 of file core.py.
fmod
numpy.ma.core.fmod = _DomainedBinaryOperation(umath.fmod, _DomainSafeDivide(), 0, 1)
Definition at line 1274 of file core.py.
frombuffer
numpy.ma.core.frombuffer
Initial value:
=  _convert2ma(
    'frombuffer',
    np_ret='out : ndarray',
    np_ma_ret='out: MaskedArray',
)
Definition at line 8473 of file core.py.
fromfunction
numpy.ma.core.fromfunction
Initial value:
=  _convert2ma(
   'fromfunction',
   np_ret='fromfunction : any',
   np_ma_ret='fromfunction: MaskedArray',
)
Definition at line 8478 of file core.py.
get_data
numpy.ma.core.get_data = getdata
Definition at line 722 of file core.py.
get_mask
numpy.ma.core.get_mask = getmask
Definition at line 1421 of file core.py.
greater
numpy.ma.core.greater = _MaskedBinaryOperation(umath.greater)
Definition at line 1254 of file core.py.
greater_equal
numpy.ma.core.greater_equal = _MaskedBinaryOperation(umath.greater_equal)
Definition at line 1250 of file core.py.
harden_mask
numpy.ma.core.harden_mask = _frommethod('harden_mask')
Definition at line 6893 of file core.py.
hypot
numpy.ma.core.hypot = _MaskedBinaryOperation(umath.hypot)
Definition at line 1264 of file core.py.
identity
numpy.ma.core.identity
Initial value:
=  _convert2ma(
    'identity',
    params=dict(fill_value=None, hardmask=False),
    np_ret='out : ndarray',
    np_ma_ret='out : MaskedArray',
)
Definition at line 8483 of file core.py.
ids
numpy.ma.core.ids = _frommethod('ids')
Definition at line 6894 of file core.py.
indices
numpy.ma.core.indices
Initial value:
=  _convert2ma(
    'indices',
    params=dict(fill_value=None, hardmask=False),
    np_ret='grid : one ndarray or tuple of ndarrays',
    np_ma_ret='grid : one MaskedArray or tuple of MaskedArrays',
)
Definition at line 8489 of file core.py.
innerproduct
numpy.ma.core.innerproduct = inner
Definition at line 7942 of file core.py.
isarray
numpy.ma.core.isarray = isMaskedArray
Definition at line 6536 of file core.py.
isMA
numpy.ma.core.isMA = isMaskedArray
Definition at line 6537 of file core.py.
less
numpy.ma.core.less = _MaskedBinaryOperation(umath.less)
Definition at line 1252 of file core.py.
less_equal
numpy.ma.core.less_equal = _MaskedBinaryOperation(umath.less_equal)
Definition at line 1248 of file core.py.
log
numpy.ma.core.log
Initial value:
=  _MaskedUnaryOperation(umath.log, 1.0,
                            _DomainGreater(0.0))
Definition at line 1222 of file core.py.
log10
numpy.ma.core.log10
Initial value:
=  _MaskedUnaryOperation(umath.log10, 1.0,
                              _DomainGreater(0.0))
Definition at line 1226 of file core.py.
log2
numpy.ma.core.log2
Initial value:
=  _MaskedUnaryOperation(umath.log2, 1.0,
                             _DomainGreater(0.0))
Definition at line 1224 of file core.py.
logical_and
numpy.ma.core.logical_and = _MaskedBinaryOperation(umath.logical_and)
Definition at line 1256 of file core.py.
logical_not
numpy.ma.core.logical_not = _MaskedUnaryOperation(umath.logical_not)
Definition at line 1217 of file core.py.
logical_or
numpy.ma.core.logical_or = _MaskedBinaryOperation(umath.logical_or)
Definition at line 1258 of file core.py.
logical_xor
numpy.ma.core.logical_xor = _MaskedBinaryOperation(umath.logical_xor)
Definition at line 1260 of file core.py.
masked
numpy.ma.core.masked = MaskedConstant()
Definition at line 6656 of file core.py.
masked_array
numpy.ma.core.masked_array = MaskedArray
Definition at line 6657 of file core.py.
masked_print_option
numpy.ma.core.masked_print_option = _MaskedPrintOption('--')
Definition at line 2420 of file core.py.
MaskType
numpy.ma.core.MaskType = np.bool_
Definition at line 81 of file core.py.
max_filler
numpy.ma.core.max_filler = ntypes._minvals
Definition at line 189 of file core.py.
maximum
numpy.ma.core.maximum = _extrema_operation(umath.maximum, greater, maximum_fill_value)
Definition at line 6895 of file core.py.
mean
numpy.ma.core.mean = _frommethod('mean')
Definition at line 6896 of file core.py.
min_filler
numpy.ma.core.min_filler = ntypes._maxvals
Definition at line 193 of file core.py.
minimum
numpy.ma.core.minimum = _extrema_operation(umath.minimum, less, minimum_fill_value)
Definition at line 6897 of file core.py.
mod
numpy.ma.core.mod = _DomainedBinaryOperation(umath.mod, _DomainSafeDivide(), 0, 1)
Definition at line 1275 of file core.py.
multiply
numpy.ma.core.multiply = _MaskedBinaryOperation(umath.multiply, 1, 1)
Definition at line 1242 of file core.py.
negative
numpy.ma.core.negative = _MaskedUnaryOperation(umath.negative)
Definition at line 1213 of file core.py.
nomask
numpy.ma.core.nomask = MaskType(0)
Definition at line 82 of file core.py.
nonzero
numpy.ma.core.nonzero = _frommethod('nonzero')
Definition at line 6898 of file core.py.
not_equal
numpy.ma.core.not_equal = _MaskedBinaryOperation(umath.not_equal)
Definition at line 1246 of file core.py.
ones
numpy.ma.core.ones
Initial value:
=  _convert2ma(
    'ones',
    params=dict(fill_value=None, hardmask=False),
    np_ret='out : ndarray',
    np_ma_ret='out : MaskedArray',
)
Definition at line 8495 of file core.py.
ones_like
numpy.ma.core.ones_like
Initial value:
=  _convert2ma(
    'ones_like',
    np_ret='out : ndarray',
    np_ma_ret='out : MaskedArray',
)
Definition at line 8501 of file core.py.
outerproduct
numpy.ma.core.outerproduct = outer
Definition at line 7960 of file core.py.
prod
numpy.ma.core.prod = _frommethod('prod')
Definition at line 6899 of file core.py.
product
numpy.ma.core.product = _frommethod('prod')
Definition at line 6900 of file core.py.
ravel
numpy.ma.core.ravel = _frommethod('ravel')
Definition at line 6901 of file core.py.
reduce
numpy.ma.core.reduce
Definition at line 1245 of file core.py.
remainder
numpy.ma.core.remainder
Initial value:
=  _DomainedBinaryOperation(umath.remainder,
                                     _DomainSafeDivide(), 0, 1)
Definition at line 1272 of file core.py.
repeat
numpy.ma.core.repeat = _frommethod('repeat')
Definition at line 6902 of file core.py.
round
numpy.ma.core.round = round_
Definition at line 7822 of file core.py.
shrink_mask
numpy.ma.core.shrink_mask = _frommethod('shrink_mask')
Definition at line 6903 of file core.py.
sin
numpy.ma.core.sin = _MaskedUnaryOperation(umath.sin)
Definition at line 1203 of file core.py.
sinh
numpy.ma.core.sinh = _MaskedUnaryOperation(umath.sinh)
Definition at line 1207 of file core.py.
soften_mask
numpy.ma.core.soften_mask = _frommethod('soften_mask')
Definition at line 6904 of file core.py.
sometrue
numpy.ma.core.sometrue = logical_or.reduce
Definition at line 1259 of file core.py.
sqrt
numpy.ma.core.sqrt
Initial value:
=  _MaskedUnaryOperation(umath.sqrt, 0.0,
                             _DomainGreaterEqual(0.0))
Definition at line 1220 of file core.py.
squeeze
numpy.ma.core.squeeze
Initial value:
=  _convert2ma(
    'squeeze',
    params=dict(fill_value=None, hardmask=False),
    np_ret='squeezed : ndarray',
    np_ma_ret='squeezed : MaskedArray',
)
Definition at line 8506 of file core.py.
std
numpy.ma.core.std = _frommethod('std')
Definition at line 6905 of file core.py.
subtract
numpy.ma.core.subtract = _MaskedBinaryOperation(umath.subtract)
Definition at line 1241 of file core.py.
sum
numpy.ma.core.sum = _frommethod('sum')
Definition at line 6906 of file core.py.
swapaxes
numpy.ma.core.swapaxes = _frommethod('swapaxes')
Definition at line 6907 of file core.py.
tan
numpy.ma.core.tan
Initial value:
=  _MaskedUnaryOperation(umath.tan, 0.0,
                            _DomainTan(1e-35))
Definition at line 1228 of file core.py.
tanh
numpy.ma.core.tanh = _MaskedUnaryOperation(umath.tanh)
Definition at line 1209 of file core.py.
trace
numpy.ma.core.trace = _frommethod('trace')
Definition at line 6909 of file core.py.
true_divide
numpy.ma.core.true_divide
Initial value:
=  _DomainedBinaryOperation(umath.true_divide,
                                       _DomainSafeDivide(), 0, 1)
Definition at line 1268 of file core.py.
ufunc_domain
dict numpy.ma.core.ufunc_domain = {}
Ufuncs #.
Definition at line 793 of file core.py.
ufunc_fills
dict numpy.ma.core.ufunc_fills = {}
Definition at line 794 of file core.py.
var
numpy.ma.core.var = _frommethod('var')
Definition at line 6910 of file core.py.
zeros
numpy.ma.core.zeros
Initial value:
=  _convert2ma(
    'zeros',
    params=dict(fill_value=None, hardmask=False),
    np_ret='out : ndarray',
    np_ma_ret='out : MaskedArray',
)
Definition at line 8512 of file core.py.
zeros_like
numpy.ma.core.zeros_like
Initial value:
=  _convert2ma(
    'zeros_like',
    np_ret='out : ndarray',
    np_ma_ret='out : MaskedArray',
)
Definition at line 8518 of file core.py.