Code Cloning Analysis: sklearn.ensemble._gb Namespace Reference
sklearn.ensemble._gb Namespace Reference
Classes
class BaseGradientBoosting
class GradientBoostingClassifier
class GradientBoostingRegressor
class VerboseReporter
Functions
_safe_divide (numerator, denominator)
_init_raw_predictions (X, estimator, loss, use_predict_proba)
_update_terminal_regions (loss, tree, X, y, neg_gradient, raw_prediction, sample_weight, sample_mask, learning_rate=0.1, k=0)
set_huber_delta (loss, y_true, raw_prediction, sample_weight=None)
Variables
_LOSSES = _LOSSES.copy()
Detailed Description
Gradient Boosted Regression Trees.
This module contains methods for fitting gradient boosted regression trees for
both classification and regression.
The module structure is the following:
- The ``BaseGradientBoosting`` base class implements a common ``fit`` method
  for all the estimators in the module. Regression and classification
  only differ in the concrete ``LossFunction`` used.
- ``GradientBoostingClassifier`` implements gradient boosting for
  classification problems.
- ``GradientBoostingRegressor`` implements gradient boosting for
  regression problems.
Function Documentation
_init_raw_predictions()
sklearn.ensemble._gb._init_raw_predictions (X, estimator, loss, use_predict_proba) protected
Return the initial raw predictions.
Parameters
----------
X : ndarray of shape (n_samples, n_features)
    The data array.
estimator : object
    The estimator to use to compute the predictions.
loss : BaseLoss
    An instance of a loss function class.
use_predict_proba : bool
    Whether estimator.predict_proba is used instead of estimator.predict.
Returns
-------
raw_predictions : ndarray of shape (n_samples, K)
    The initial raw predictions. K is equal to 1 for binary
    classification and regression, and equal to the number of classes
    for multiclass classification. ``raw_predictions`` is casted
    into float64.
Definition at line 86 of file _gb.py.
Referenced by sklearn.ensemble._gb.BaseGradientBoosting._raw_predict_init(), and sklearn.ensemble._gb.BaseGradientBoosting.fit().
_safe_divide()
sklearn.ensemble._gb._safe_divide (numerator, denominator) protected
Prevents overflow and division by zero.
Definition at line 65 of file _gb.py.
Referenced by _update_terminal_regions().
_update_terminal_regions()
sklearn.ensemble._gb._update_terminal_regions (loss, tree, X, y, neg_gradient, raw_prediction, sample_weight, sample_mask, learning_rate = 0.1, k = 0) protected
Update the leaf values to be predicted by the tree and raw_prediction.
The current raw predictions of the model (of this stage) are updated.
Additionally, the terminal regions (=leaves) of the given tree are updated as well.
This corresponds to the line search step in "Greedy Function Approximation" by
Friedman, Algorithm 1 step 5.
Update equals:
    argmin_{x} loss(y_true, raw_prediction_old + x * tree.value)
For non-trivial cases like the Binomial loss, the update has no closed formula and
is an approximation, again, see the Friedman paper.
Also note that the update formula for the SquaredError is the identity. Therefore,
in this case, the leaf values don't need an update and only the raw_predictions are
updated (with the learning rate included).
Parameters
----------
loss : BaseLoss
tree : tree.Tree
    The tree object.
X : ndarray of shape (n_samples, n_features)
    The data array.
y : ndarray of shape (n_samples,)
    The target labels.
neg_gradient : ndarray of shape (n_samples,)
    The negative gradient.
raw_prediction : ndarray of shape (n_samples, n_trees_per_iteration)
    The raw predictions (i.e. values from the tree leaves) of the
    tree ensemble at iteration ``i - 1``.
sample_weight : ndarray of shape (n_samples,)
    The weight of each sample.
sample_mask : ndarray of shape (n_samples,)
    The sample mask to be used.
learning_rate : float, default=0.1
    Learning rate shrinks the contribution of each tree by
     ``learning_rate``.
k : int, default=0
    The index of the estimator being updated.
Definition at line 128 of file _gb.py.
References _safe_divide().
set_huber_delta()
sklearn.ensemble._gb.set_huber_delta (loss, y_true, raw_prediction, sample_weight = None)
Calculate and set self.closs.delta based on self.quantile.
Definition at line 266 of file _gb.py.
Variable Documentation
_LOSSES
sklearn.ensemble._gb._LOSSES = _LOSSES.copy() protected
Definition at line 56 of file _gb.py.