Code Cloning Analysis: sklearn.model_selection._split Namespace Reference
sklearn.model_selection._split Namespace Reference
Classes
class _BaseKFold
class _CVIterableWrapper
class _RepeatedSplits
class _UnsupportedGroupCVMixin
class BaseCrossValidator
class BaseShuffleSplit
class GroupKFold
class GroupsConsumerMixin
class GroupShuffleSplit
class KFold
class LeaveOneGroupOut
class LeaveOneOut
class LeavePGroupsOut
class LeavePOut
class PredefinedSplit
class RepeatedKFold
class RepeatedStratifiedKFold
class ShuffleSplit
class StratifiedGroupKFold
class StratifiedKFold
class StratifiedShuffleSplit
class TimeSeriesSplit
Functions
_validate_shuffle_split (n_samples, test_size, train_size, default_test_size=None)
check_cv (cv=5, y=None, *, classifier=False)
train_test_split (*arrays, test_size=None, train_size=None, random_state=None, shuffle=True, stratify=None)
_pprint (params, offset=0, printer=repr)
_build_repr (self)
_yields_constant_splits (cv)
Variables
list __all__
Detailed Description
The :mod:`sklearn.model_selection._split` module includes classes and
functions to split the data based on a preset strategy.
Function Documentation
_build_repr()
sklearn.model_selection._split._build_repr (self) protected
Definition at line 3007 of file _split.py.
_pprint()
sklearn.model_selection._split._pprint (params, offset = 0, printer = repr) protected
Pretty print the dictionary 'params'
Parameters
----------
params : dict
    The dictionary to pretty print
offset : int, default=0
    The offset in characters to add at the begin of each line.
printer : callable, default=repr
    The function to convert entries to strings, typically
    the builtin str or repr
Definition at line 2957 of file _split.py.
References _pprint().
Referenced by _pprint().
_validate_shuffle_split()
sklearn.model_selection._split._validate_shuffle_split (n_samples, test_size, train_size, default_test_size = None) protected
Validation helper to check if the train/test sizes are meaningful w.r.t. the
size of the data (n_samples).
Definition at line 2433 of file _split.py.
Referenced by sklearn.model_selection._split.BaseShuffleSplit._iter_indices(), sklearn.model_selection._split.StratifiedShuffleSplit._iter_indices(), and train_test_split().
_yields_constant_splits()
sklearn.model_selection._split._yields_constant_splits (cv) protected
Definition at line 3047 of file _split.py.
check_cv()
sklearn.model_selection._split.check_cv (cv = 5, y = None, * , classifier = False)
Input checker utility for building a cross-validator.
Parameters
----------
cv : int, cross-validation generator, iterable or None, default=5
    Determines the cross-validation splitting strategy.
    Possible inputs for cv are:
    - None, to use the default 5-fold cross validation,
    - integer, to specify the number of folds.
    - :term:`CV splitter`,
    - An iterable that generates (train, test) splits as arrays of indices.
    For integer/None inputs, if classifier is True and ``y`` is either
    binary or multiclass, :class:`StratifiedKFold` is used. In all other
    cases, :class:`KFold` is used.
    Refer :ref:`User Guide <cross_validation>` for the various
    cross-validation strategies that can be used here.
    .. versionchanged:: 0.22
        ``cv`` default value changed from 3-fold to 5-fold.
y : array-like, default=None
    The target variable for supervised learning problems.
classifier : bool, default=False
    Whether the task is a classification task, in which case
    stratified KFold will be used.
Returns
-------
checked_cv : a cross-validator instance.
    The return value is a cross-validator which generates the train/test
    splits via the ``split`` method.
Examples
--------
>>> from sklearn.model_selection import check_cv
>>> check_cv(cv=5, y=None, classifier=False)
KFold(...)
>>> check_cv(cv=5, y=[1, 1, 0, 0, 0, 0], classifier=True)
StratifiedKFold(...)
Definition at line 2685 of file _split.py.
train_test_split()
sklearn.model_selection._split.train_test_split (* arrays, test_size = None, train_size = None, random_state = None, shuffle = True, stratify = None)
Split arrays or matrices into random train and test subsets.
Quick utility that wraps input validation,
``next(ShuffleSplit().split(X, y))``, and application to input data
into a single call for splitting (and optionally subsampling) data into a
one-liner.
Read more in the :ref:`User Guide <cross_validation>`.
Parameters
----------
*arrays : sequence of indexables with same length / shape[0]
    Allowed inputs are lists, numpy arrays, scipy-sparse
    matrices or pandas dataframes.
test_size : float or int, default=None
    If float, should be between 0.0 and 1.0 and represent the proportion
    of the dataset to include in the test split. If int, represents the
    absolute number of test samples. If None, the value is set to the
    complement of the train size. If ``train_size`` is also None, it will
    be set to 0.25.
train_size : float or int, default=None
    If float, should be between 0.0 and 1.0 and represent the
    proportion of the dataset to include in the train split. If
    int, represents the absolute number of train samples. If None,
    the value is automatically set to the complement of the test size.
random_state : int, RandomState instance or None, default=None
    Controls the shuffling applied to the data before applying the split.
    Pass an int for reproducible output across multiple function calls.
    See :term:`Glossary <random_state>`.
shuffle : bool, default=True
    Whether or not to shuffle the data before splitting. If shuffle=False
    then stratify must be None.
stratify : array-like, default=None
    If not None, data is split in a stratified fashion, using this as
    the class labels.
    Read more in the :ref:`User Guide <stratification>`.
Returns
-------
splitting : list, length=2 * len(arrays)
    List containing train-test split of inputs.
    .. versionadded:: 0.16
        If the input is sparse, the output will be a
        ``scipy.sparse.csr_matrix``. Else, output type is the same as the
        input type.
Examples
--------
>>> import numpy as np
>>> from sklearn.model_selection import train_test_split
>>> X, y = np.arange(10).reshape((5, 2)), range(5)
>>> X
array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])
>>> list(y)
[0, 1, 2, 3, 4]
>>> X_train, X_test, y_train, y_test = train_test_split(
...     X, y, test_size=0.33, random_state=42)
...
>>> X_train
array([[4, 5],
       [0, 1],
       [6, 7]])
>>> y_train
[2, 0, 3]
>>> X_test
array([[2, 3],
       [8, 9]])
>>> y_test
[1, 4]
>>> train_test_split(y, shuffle=False)
[[0, 1, 2], [3, 4]]
>>> from sklearn import datasets
>>> iris = datasets.load_iris(as_frame=True)
>>> X, y = iris['data'], iris['target']
>>> X.head()
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2
>>> y.head()
0    0
1    0
2    0
3    0
4    0
...
>>> X_train, X_test, y_train, y_test = train_test_split(
... X, y, test_size=0.33, random_state=42)
...
>>> X_train.head()
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
96                 5.7               2.9                4.2               1.3
105                7.6               3.0                6.6               2.1
66                 5.6               3.0                4.5               1.5
0                  5.1               3.5                1.4               0.2
122                7.7               2.8                6.7               2.0
>>> y_train.head()
96     1
105    2
66     1
0      0
122    2
...
>>> X_test.head()
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
73                 6.1               2.8                4.7               1.2
18                 5.7               3.8                1.7               0.3
118                7.7               2.6                6.9               2.3
78                 6.0               2.9                4.5               1.5
76                 6.8               2.8                4.8               1.4
>>> y_test.head()
73     1
18     0
118    2
78     1
76     1
...
Definition at line 2770 of file _split.py.
References _validate_shuffle_split().
Variable Documentation
__all__
list sklearn.model_selection._split.__all__ private
Initial value:
=  [
    "BaseCrossValidator",
    "GroupKFold",
    "GroupShuffleSplit",
    "KFold",
    "LeaveOneGroupOut",
    "LeaveOneOut",
    "LeavePGroupsOut",
    "LeavePOut",
    "PredefinedSplit",
    "RepeatedKFold",
    "RepeatedStratifiedKFold",
    "ShuffleSplit",
    "StratifiedGroupKFold",
    "StratifiedKFold",
    "StratifiedShuffleSplit",
    "check_cv",
    "train_test_split",
]
Definition at line 38 of file _split.py.