Code Cloning Analysis: joblib.externals.loky.backend.queues.Queue Class Reference
joblib.externals.loky.backend.queues.Queue Class Reference
Public Member Functions
__init__ (self, maxsize=0, reducers=None, ctx=None)
__getstate__ (self)
__setstate__ (self, state)
Protected Member Functions
_start_thread (self)
_on_queue_feeder_error (self, e, obj)
Static Protected Member Functions
_feed (buffer, notempty, send_bytes, writelock, close, reducers, ignore_epipe, onerror, queue_sem)
Protected Attributes
_reducers = reducers
_ignore_epipe
_maxsize
_reader
_writer
_rlock
_wlock
_sem
_opid
_thread
_jointhread
_close
Detailed Description
Definition at line 30 of file queues.py.
Constructor & Destructor Documentation
__init__()
joblib.externals.loky.backend.queues.Queue.__init__ (self, maxsize = 0, reducers = None, ctx = None)
Definition at line 31 of file queues.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__getstate__()
joblib.externals.loky.backend.queues.Queue.__getstate__ (self)
Definition at line 36 of file queues.py.
Referenced by numpy.ma.core.MaskedArray.__reduce__(), and numpy.ma.mrecords.MaskedRecords.__reduce__().
__setstate__()
joblib.externals.loky.backend.queues.Queue.__setstate__ (self, state)
Definition at line 50 of file queues.py.
_feed()
joblib.externals.loky.backend.queues.Queue._feed (buffer, notempty, send_bytes, writelock, close, reducers, ignore_epipe, onerror, queue_sem) static protected
Definition at line 119 of file queues.py.
_on_queue_feeder_error()
joblib.externals.loky.backend.queues.Queue._on_queue_feeder_error (self, e, obj) protected
Private API hook called when feeding data in the background thread
raises an exception.  For overriding by concurrent.futures.
Reimplemented in joblib.externals.loky.process_executor._SafeQueue.
Definition at line 186 of file queues.py.
_start_thread()
joblib.externals.loky.backend.queues.Queue._start_thread (self) protected
Definition at line 68 of file queues.py.
Member Data Documentation
_close
joblib.externals.loky.backend.queues.Queue._close protected
Initial value:
=  util.Finalize(
            self,
            Queue._finalize_close,
            [self._buffer, self._notempty],
            exitpriority=10,
        )
Definition at line 110 of file queues.py.
_ignore_epipe
joblib.externals.loky.backend.queues.Queue._ignore_epipe protected
Definition at line 39 of file queues.py.
_jointhread
joblib.externals.loky.backend.queues.Queue._jointhread protected
Initial value:
=  util.Finalize(
                self._thread,
                Queue._finalize_join,
                [weakref.ref(self._thread)],
                exitpriority=-5,
            )
Definition at line 102 of file queues.py.
_maxsize
joblib.externals.loky.backend.queues.Queue._maxsize protected
Definition at line 40 of file queues.py.
_opid
joblib.externals.loky.backend.queues.Queue._opid protected
Definition at line 47 of file queues.py.
_reader
joblib.externals.loky.backend.queues.Queue._reader protected
Definition at line 41 of file queues.py.
Referenced by pandas.io.parsers.c_parser_wrapper.CParserWrapper._set_noconvert_columns(), pandas.io.excel._base.ExcelFile.close(), pandas.io.excel._base.ExcelFile.parse(), and pip._vendor.distlib.index.PackageIndex.run_command().
_reducers
joblib.externals.loky.backend.queues.Queue._reducers = reducers protected
Definition at line 33 of file queues.py.
_rlock
joblib.externals.loky.backend.queues.Queue._rlock protected
Definition at line 44 of file queues.py.
_sem
joblib.externals.loky.backend.queues.Queue._sem protected
Definition at line 46 of file queues.py.
_thread
joblib.externals.loky.backend.queues.Queue._thread protected
Initial value:
=  threading.Thread(
            target=Queue._feed,
            args=(
                self._buffer,
                self._notempty,
                self._send_bytes,
                self._wlock,
                self._writer.close,
                self._reducers,
                self._ignore_epipe,
                self._on_queue_feeder_error,
                self._sem,
            ),
            name="QueueFeederThread",
        )
Definition at line 73 of file queues.py.
_wlock
joblib.externals.loky.backend.queues.Queue._wlock protected
Definition at line 45 of file queues.py.
_writer
joblib.externals.loky.backend.queues.Queue._writer protected
Definition at line 42 of file queues.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/joblib/externals/loky/backend/queues.py