Code Cloning Analysis: packaging.version._BaseVersion Class Reference
packaging.version._BaseVersion Class Reference
Public Member Functions
int __hash__ (self)
bool __lt__ (self, _BaseVersion other)
bool __le__ (self, _BaseVersion other)
bool __eq__ (self, object other)
bool __ge__ (self, _BaseVersion other)
bool __gt__ (self, _BaseVersion other)
bool __ne__ (self, object other)
Static Protected Attributes
tuple _key [Any, ...]
Detailed Description
Definition at line 69 of file version.py.
Member Function Documentation
__eq__()
bool packaging.version._BaseVersion.__eq__ (self, object other)
Definition at line 90 of file version.py.
Referenced by pandas.core.dtypes.base.ExtensionDtype.__eq__(), pandas.io.pytables.IndexCol.__eq__(), pip._vendor.msgpack.ext.Timestamp.__ne__(), pip._vendor.distlib.version.Matcher.match(), and pandas.core.dtypes.dtypes.PeriodDtype.na_value().
__ge__()
bool packaging.version._BaseVersion.__ge__ (self, _BaseVersion other)
Definition at line 96 of file version.py.
__gt__()
bool packaging.version._BaseVersion.__gt__ (self, _BaseVersion other)
Definition at line 102 of file version.py.
__hash__()
int packaging.version._BaseVersion.__hash__ (self)
Definition at line 72 of file version.py.
Referenced by pip._vendor.rich.style.Style.pick_first().
__le__()
bool packaging.version._BaseVersion.__le__ (self, _BaseVersion other)
Definition at line 84 of file version.py.
__lt__()
bool packaging.version._BaseVersion.__lt__ (self, _BaseVersion other)
Definition at line 78 of file version.py.
__ne__()
bool packaging.version._BaseVersion.__ne__ (self, object other)
Definition at line 108 of file version.py.
Member Data Documentation
_key
packaging.version._BaseVersion._key [Any, ...] static protected
Definition at line 70 of file version.py.
Referenced by packaging.version.Version.__init__().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/packaging/version.py