Code Cloning Analysis: numpy._utils._pep440.LegacyVersion Class Reference
numpy._utils._pep440.LegacyVersion Class Reference
Public Member Functions
__init__ (self, version)
__str__ (self)
__repr__ (self)
public (self)
base_version (self)
local (self)
is_prerelease (self)
is_postrelease (self)
Public Member Functions inherited from numpy._utils._pep440._BaseVersion
__hash__ (self)
__lt__ (self, other)
__le__ (self, other)
__eq__ (self, other)
__ge__ (self, other)
__gt__ (self, other)
__ne__ (self, other)
Protected Attributes
_version = str(version)
Protected Attributes inherited from numpy._utils._pep440._BaseVersion
_key
Additional Inherited Members
Protected Member Functions inherited from numpy._utils._pep440._BaseVersion
_compare (self, other, method)
Detailed Description
Definition at line 165 of file _pep440.py.
Constructor & Destructor Documentation
__init__()
numpy._utils._pep440.LegacyVersion.__init__ (self, version)
Definition at line 167 of file _pep440.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__repr__()
numpy._utils._pep440.LegacyVersion.__repr__ (self)
Definition at line 174 of file _pep440.py.
__str__()
numpy._utils._pep440.LegacyVersion.__str__ (self)
Definition at line 171 of file _pep440.py.
Referenced by numpy.polynomial._polybase.ABCPolyBase._get_coefficients().
base_version()
numpy._utils._pep440.LegacyVersion.base_version (self)
Definition at line 182 of file _pep440.py.
is_postrelease()
numpy._utils._pep440.LegacyVersion.is_postrelease (self)
Definition at line 194 of file _pep440.py.
is_prerelease()
numpy._utils._pep440.LegacyVersion.is_prerelease (self)
Definition at line 190 of file _pep440.py.
local()
numpy._utils._pep440.LegacyVersion.local (self)
Definition at line 186 of file _pep440.py.
Referenced by packaging.version.Version.__str__().
public()
numpy._utils._pep440.LegacyVersion.public (self)
Definition at line 178 of file _pep440.py.
Member Data Documentation
_version
numpy._utils._pep440.LegacyVersion._version = str(version) protected
Definition at line 168 of file _pep440.py.
Referenced by packaging.version.Version.__init__(), pip._internal.resolution.resolvelib.candidates._InstallRequirementBackedCandidate._check_metadata_consistency(), packaging.version.Version.dev(), packaging.version.Version.epoch(), packaging.version.Version.local(), pip._internal.resolution.resolvelib.candidates._InstallRequirementBackedCandidate.name(), pip._internal.resolution.resolvelib.candidates.AlreadyInstalledCandidate.name(), pip._internal.resolution.resolvelib.candidates.RequiresPythonCandidate.name(), packaging.version.Version.post(), packaging.version.Version.pre(), and packaging.version.Version.release().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/_utils/_pep440.py