Code Cloning Analysis: sklearn.linear_model._ridge Namespace Reference
sklearn.linear_model._ridge Namespace Reference
Classes
class _BaseRidge
class _BaseRidgeCV
class _IdentityClassifier
class _IdentityRegressor
class _RidgeClassifierMixin
class _RidgeGCV
class _X_CenterStackOp
class _XT_CenterStackOp
class Ridge
class RidgeClassifier
class RidgeClassifierCV
class RidgeCV
Functions
_get_rescaled_operator (X, X_offset, sample_weight_sqrt)
_solve_sparse_cg (X, y, alpha, max_iter=None, tol=1e-4, verbose=0, X_offset=None, X_scale=None, sample_weight_sqrt=None)
_solve_lsqr (X, y, *, alpha, fit_intercept=True, max_iter=None, tol=1e-4, X_offset=None, X_scale=None, sample_weight_sqrt=None)
_solve_cholesky (X, y, alpha)
_solve_cholesky_kernel (K, y, alpha, sample_weight=None, copy=False)
_solve_svd (X, y, alpha, xp=None)
_solve_lbfgs (X, y, alpha, positive=True, max_iter=None, tol=1e-4, X_offset=None, X_scale=None, sample_weight_sqrt=None)
_get_valid_accept_sparse (is_X_sparse, solver)
ridge_regression (X, y, alpha, *, sample_weight=None, solver="auto", max_iter=None, tol=1e-4, verbose=0, positive=False, random_state=None, return_n_iter=False, return_intercept=False, check_input=True)
_ridge_regression (X, y, alpha, sample_weight=None, solver="auto", max_iter=None, tol=1e-4, verbose=0, positive=False, random_state=None, return_n_iter=False, return_intercept=False, return_solver=False, X_scale=None, X_offset=None, check_input=True, fit_intercept=False)
resolve_solver (solver, positive, return_intercept, is_sparse, xp)
resolve_solver_for_numpy (positive, return_intercept, is_sparse)
_check_gcv_mode (X, gcv_mode)
_find_smallest_angle (query, vectors)
Detailed Description
Ridge regression
Function Documentation
_check_gcv_mode()
sklearn.linear_model._ridge._check_gcv_mode (X, gcv_mode) protected
Definition at line 1581 of file _ridge.py.
_find_smallest_angle()
sklearn.linear_model._ridge._find_smallest_angle (query, vectors) protected
Find the column of vectors that is most aligned with the query.
Both query and the columns of vectors must have their l2 norm equal to 1.
Parameters
----------
query : ndarray of shape (n_samples,)
    Normalized query vector.
vectors : ndarray of shape (n_samples, n_features)
    Vectors to which we compare query, as columns. Must be normalized.
Definition at line 1591 of file _ridge.py.
Referenced by sklearn.linear_model._ridge._RidgeGCV._solve_eigen_covariance_intercept(), sklearn.linear_model._ridge._RidgeGCV._solve_eigen_gram(), and sklearn.linear_model._ridge._RidgeGCV._solve_svd_design_matrix().
_get_rescaled_operator()
sklearn.linear_model._ridge._get_rescaled_operator (X, X_offset, sample_weight_sqrt) protected
Create LinearOperator for matrix products with implicit centering.
Matrix product `LinearOperator @ coef` returns `(X - X_offset) @ coef`.
Definition at line 56 of file _ridge.py.
References _get_rescaled_operator().
Referenced by _get_rescaled_operator(), and _solve_lsqr().
_get_valid_accept_sparse()
sklearn.linear_model._ridge._get_valid_accept_sparse (is_X_sparse, solver) protected
Definition at line 368 of file _ridge.py.
_ridge_regression()
sklearn.linear_model._ridge._ridge_regression (X, y, alpha, sample_weight = None, solver = "auto", max_iter = None, tol = 1e-4, verbose = 0, positive = False, random_state = None, return_n_iter = False, return_intercept = False, return_solver = False, X_scale = None, X_offset = None, check_input = True, fit_intercept = False) protected
Definition at line 597 of file _ridge.py.
_solve_cholesky()
sklearn.linear_model._ridge._solve_cholesky (X, y, alpha) protected
Definition at line 201 of file _ridge.py.
_solve_cholesky_kernel()
sklearn.linear_model._ridge._solve_cholesky_kernel (K, y, alpha, sample_weight = None, copy = False) protected
Definition at line 223 of file _ridge.py.
_solve_lbfgs()
sklearn.linear_model._ridge._solve_lbfgs (X, y, alpha, positive = True, max_iter = None, tol = 1e-4, X_offset = None, X_scale = None, sample_weight_sqrt = None) protected
Solve ridge regression with LBFGS.
The main purpose is fitting with forcing coefficients to be positive.
For unconstrained ridge regression, there are faster dedicated solver methods.
Note that with positive bounds on the coefficients, LBFGS seems faster
than scipy.optimize.lsq_linear.
Definition at line 297 of file _ridge.py.
Referenced by ridge_regression().
_solve_lsqr()
sklearn.linear_model._ridge._solve_lsqr (X, y, * , alpha, fit_intercept = True, max_iter = None, tol = 1e-4, X_offset = None, X_scale = None, sample_weight_sqrt = None) protected
Solve Ridge regression via LSQR.
We expect that y is always mean centered.
If X is dense, we expect it to be mean centered such that we can solve
    ||y - Xw||_2^2 + alpha * ||w||_2^2
If X is sparse, we expect X_offset to be given such that we can solve
    ||y - (X - X_offset)w||_2^2 + alpha * ||w||_2^2
With sample weights S=diag(sample_weight), this becomes
    ||sqrt(S) (y - (X - X_offset) w)||_2^2 + alpha * ||w||_2^2
and we expect y and X to already be rescaled, i.e. sqrt(S) @ y, sqrt(S) @ X. In
this case, X_offset is the sample_weight weighted mean of X before scaling by
sqrt(S). The objective then reads
   ||y - (X - sqrt(S) X_offset) w)||_2^2 + alpha * ||w||_2^2
Definition at line 145 of file _ridge.py.
References _get_rescaled_operator().
Referenced by ridge_regression().
_solve_sparse_cg()
sklearn.linear_model._ridge._solve_sparse_cg (X, y, alpha, max_iter = None, tol = 1e-4, verbose = 0, X_offset = None, X_scale = None, sample_weight_sqrt = None) protected
Definition at line 72 of file _ridge.py.
_solve_svd()
sklearn.linear_model._ridge._solve_svd (X, y, alpha, xp = None) protected
Definition at line 285 of file _ridge.py.
resolve_solver()
sklearn.linear_model._ridge.resolve_solver (solver, positive, return_intercept, is_sparse, xp)
Definition at line 826 of file _ridge.py.
resolve_solver_for_numpy()
sklearn.linear_model._ridge.resolve_solver_for_numpy (positive, return_intercept, is_sparse)
Definition at line 858 of file _ridge.py.
ridge_regression()
sklearn.linear_model._ridge.ridge_regression (X, y, alpha, * , sample_weight = None, solver = "auto", max_iter = None, tol = 1e-4, verbose = 0, positive = False, random_state = None, return_n_iter = False, return_intercept = False, check_input = True)
Solve the ridge equation by the method of normal equations.
Read more in the :ref:`User Guide <ridge_regression>`.
Parameters
----------
X : {array-like, sparse matrix, LinearOperator} of shape \
    (n_samples, n_features)
    Training data.
y : array-like of shape (n_samples,) or (n_samples, n_targets)
    Target values.
alpha : float or array-like of shape (n_targets,)
    Constant that multiplies the L2 term, controlling regularization
    strength. `alpha` must be a non-negative float i.e. in `[0, inf)`.
    When `alpha = 0`, the objective is equivalent to ordinary least
    squares, solved by the :class:`LinearRegression` object. For numerical
    reasons, using `alpha = 0` with the `Ridge` object is not advised.
    Instead, you should use the :class:`LinearRegression` object.
    If an array is passed, penalties are assumed to be specific to the
    targets. Hence they must correspond in number.
sample_weight : float or array-like of shape (n_samples,), default=None
    Individual weights for each sample. If given a float, every sample
    will have the same weight. If sample_weight is not None and
    solver='auto', the solver will be set to 'cholesky'.
    .. versionadded:: 0.17
solver : {'auto', 'svd', 'cholesky', 'lsqr', 'sparse_cg', \
        'sag', 'saga', 'lbfgs'}, default='auto'
    Solver to use in the computational routines:
    - 'auto' chooses the solver automatically based on the type of data.
    - 'svd' uses a Singular Value Decomposition of X to compute the Ridge
      coefficients. It is the most stable solver, in particular more stable
      for singular matrices than 'cholesky' at the cost of being slower.
    - 'cholesky' uses the standard scipy.linalg.solve function to
      obtain a closed-form solution via a Cholesky decomposition of
      dot(X.T, X)
    - 'sparse_cg' uses the conjugate gradient solver as found in
      scipy.sparse.linalg.cg. As an iterative algorithm, this solver is
      more appropriate than 'cholesky' for large-scale data
      (possibility to set `tol` and `max_iter`).
    - 'lsqr' uses the dedicated regularized least-squares routine
      scipy.sparse.linalg.lsqr. It is the fastest and uses an iterative
      procedure.
    - 'sag' uses a Stochastic Average Gradient descent, and 'saga' uses
      its improved, unbiased version named SAGA. Both methods also use an
      iterative procedure, and are often faster than other solvers when
      both n_samples and n_features are large. Note that 'sag' and
      'saga' fast convergence is only guaranteed on features with
      approximately the same scale. You can preprocess the data with a
      scaler from sklearn.preprocessing.
    - 'lbfgs' uses L-BFGS-B algorithm implemented in
      `scipy.optimize.minimize`. It can be used only when `positive`
      is True.
    All solvers except 'svd' support both dense and sparse data. However, only
    'lsqr', 'sag', 'sparse_cg', and 'lbfgs' support sparse input when
    `fit_intercept` is True.
    .. versionadded:: 0.17
       Stochastic Average Gradient descent solver.
    .. versionadded:: 0.19
       SAGA solver.
max_iter : int, default=None
    Maximum number of iterations for conjugate gradient solver.
    For the 'sparse_cg' and 'lsqr' solvers, the default value is determined
    by scipy.sparse.linalg. For 'sag' and saga solver, the default value is
    1000. For 'lbfgs' solver, the default value is 15000.
tol : float, default=1e-4
    Precision of the solution. Note that `tol` has no effect for solvers 'svd' and
    'cholesky'.
    .. versionchanged:: 1.2
       Default value changed from 1e-3 to 1e-4 for consistency with other linear
       models.
verbose : int, default=0
    Verbosity level. Setting verbose > 0 will display additional
    information depending on the solver used.
positive : bool, default=False
    When set to ``True``, forces the coefficients to be positive.
    Only 'lbfgs' solver is supported in this case.
random_state : int, RandomState instance, default=None
    Used when ``solver`` == 'sag' or 'saga' to shuffle the data.
    See :term:`Glossary <random_state>` for details.
return_n_iter : bool, default=False
    If True, the method also returns `n_iter`, the actual number of
    iteration performed by the solver.
    .. versionadded:: 0.17
return_intercept : bool, default=False
    If True and if X is sparse, the method also returns the intercept,
    and the solver is automatically changed to 'sag'. This is only a
    temporary fix for fitting the intercept with sparse data. For dense
    data, use sklearn.linear_model._preprocess_data before your regression.
    .. versionadded:: 0.17
check_input : bool, default=True
    If False, the input arrays X and y will not be checked.
    .. versionadded:: 0.21
Returns
-------
coef : ndarray of shape (n_features,) or (n_targets, n_features)
    Weight vector(s).
n_iter : int, optional
    The actual number of iteration performed by the solver.
    Only returned if `return_n_iter` is True.
intercept : float or ndarray of shape (n_targets,)
    The intercept of the model. Only returned if `return_intercept`
    is True and if X is a scipy sparse array.
Notes
-----
This function won't compute the intercept.
Regularization improves the conditioning of the problem and
reduces the variance of the estimates. Larger values specify stronger
regularization. Alpha corresponds to ``1 / (2C)`` in other linear
models such as :class:`~sklearn.linear_model.LogisticRegression` or
:class:`~sklearn.svm.LinearSVC`. If an array is passed, penalties are
assumed to be specific to the targets. Hence they must correspond in
number.
Examples
--------
>>> import numpy as np
>>> from sklearn.datasets import make_regression
>>> from sklearn.linear_model import ridge_regression
>>> rng = np.random.RandomState(0)
>>> X = rng.randn(100, 4)
>>> y = 2.0 * X[:, 0] - 1.0 * X[:, 1] + 0.1 * rng.standard_normal(100)
>>> coef, intercept = ridge_regression(X, y, alpha=1.0, return_intercept=True,
...                                    random_state=0)
>>> coef
array([ 1.97, -1., -2.69e-3, -9.27e-4 ])
>>> intercept
np.float64(-.0012)
Definition at line 401 of file _ridge.py.
References _solve_lbfgs(), and _solve_lsqr().