Code Cloning Analysis: mplot3d.art3d Namespace Reference
mplot3d.art3d Namespace Reference
Classes
class Collection3D
class Line3D
class Line3DCollection
class Patch3D
class Patch3DCollection
class Path3DCollection
class PathPatch3D
class Poly3DCollection
class Text3D
Functions
_norm_angle (a)
_norm_text_angle (a)
get_dir_vector (zdir)
_viewlim_mask (xs, ys, zs, axes)
text_2d_to_3d (obj, z=0, zdir='z', axlim_clip=False)
line_2d_to_3d (line, zs=0, zdir='z', axlim_clip=False)
_path_to_3d_segment (path, zs=0, zdir='z')
_paths_to_3d_segments (paths, zs=0, zdir='z')
_path_to_3d_segment_with_codes (path, zs=0, zdir='z')
_paths_to_3d_segments_with_codes (paths, zs=0, zdir='z')
collection_2d_to_3d (col, zs=0, zdir='z', axlim_clip=False)
line_collection_2d_to_3d (col, zs=0, zdir='z', axlim_clip=False)
_get_patch_verts (patch)
patch_2d_to_3d (patch, z=0, zdir='z', axlim_clip=False)
pathpatch_2d_to_3d (pathpatch, z=0, zdir='z')
patch_collection_2d_to_3d (col, zs=0, zdir='z', depthshade=True, axlim_clip=False)
poly_collection_2d_to_3d (col, zs=0, zdir='z', axlim_clip=False)
juggle_axes (xs, ys, zs, zdir)
rotate_axes (xs, ys, zs, zdir)
_zalpha (colors, zs)
_all_points_on_plane (xs, ys, zs, atol=1e-8)
_generate_normals (polygons)
_shade_colors (color, normals, lightsource=None)
Detailed Description
Module containing 3D artist code and functions to convert 2D
artists into 3D versions which can be added to an Axes3D.
Function Documentation
_all_points_on_plane()
mplot3d.art3d._all_points_on_plane (xs, ys, zs, atol = 1e-8) protected
Check if all points are on the same plane. Note that NaN values are
ignored.
Parameters
----------
xs, ys, zs : array-like
    The x, y, and z coordinates of the points.
atol : float, default: 1e-8
    The tolerance for the equality check.
Definition at line 1307 of file art3d.py.
_generate_normals()
mplot3d.art3d._generate_normals (polygons) protected
Compute the normals of a list of polygons, one normal per polygon.
Normals point towards the viewer for a face with its vertices in
counterclockwise order, following the right hand rule.
Uses three points equally spaced around the polygon. This method assumes
that the points are in a plane. Otherwise, more than one shade is required,
which is not supported.
Parameters
----------
polygons : list of (M_i, 3) array-like, or (..., M, 3) array-like
    A sequence of polygons to compute normals for, which can have
    varying numbers of vertices. If the polygons all have the same
    number of vertices and array is passed, then the operation will
    be vectorized.
Returns
-------
normals : (..., 3) array
    A normal vector estimated for the polygon.
Definition at line 1348 of file art3d.py.
Referenced by mplot3d.art3d.Poly3DCollection.__init__().
_get_patch_verts()
mplot3d.art3d._get_patch_verts (patch) protected
Return a list of vertices for the path of a patch.
Definition at line 600 of file art3d.py.
Referenced by patch_2d_to_3d().
_norm_angle()
mplot3d.art3d._norm_angle (a) protected
Return the given angle normalized to -180 < *a* <= 180 degrees.
Definition at line 26 of file art3d.py.
_norm_text_angle()
mplot3d.art3d._norm_text_angle (a) protected
Return the given angle normalized to -90 < *a* <= 90 degrees.
Definition at line 34 of file art3d.py.
Referenced by mplot3d.art3d.Text3D.set_3d_properties().
_path_to_3d_segment()
mplot3d.art3d._path_to_3d_segment (path, zs = 0, zdir = 'z') protected
Convert a path to a 3D segment.
Definition at line 346 of file art3d.py.
References juggle_axes().
Referenced by _paths_to_3d_segments().
_path_to_3d_segment_with_codes()
mplot3d.art3d._path_to_3d_segment_with_codes (path, zs = 0, zdir = 'z') protected
Convert a path to a 3D segment with path codes.
Definition at line 370 of file art3d.py.
References juggle_axes().
Referenced by _paths_to_3d_segments_with_codes().
_paths_to_3d_segments()
mplot3d.art3d._paths_to_3d_segments (paths, zs = 0, zdir = 'z') protected
Convert paths from a collection object to 3D segments.
Definition at line 356 of file art3d.py.
References _path_to_3d_segment().
Referenced by line_collection_2d_to_3d().
_paths_to_3d_segments_with_codes()
mplot3d.art3d._paths_to_3d_segments_with_codes (paths, zs = 0, zdir = 'z') protected
Convert paths from a collection object to 3D segments with path codes.
Definition at line 385 of file art3d.py.
References _path_to_3d_segment_with_codes().
Referenced by poly_collection_2d_to_3d().
_shade_colors()
mplot3d.art3d._shade_colors (color, normals, lightsource = None) protected
Shade *color* using normal vectors given by *normals*,
assuming a *lightsource* (using default position if not given).
*color* can also be an array of the same length as *normals*.
Definition at line 1392 of file art3d.py.
Referenced by mplot3d.art3d.Poly3DCollection.__init__().
_viewlim_mask()
mplot3d.art3d._viewlim_mask (xs, ys, zs, axes) protected
Return original points with points outside the axes view limits masked.
Parameters
----------
xs, ys, zs : array-like
    The points to mask.
axes : Axes3D
    The axes to use for the view limits.
Returns
-------
xs_masked, ys_masked, zs_masked : np.ma.array
    The masked points.
Definition at line 76 of file art3d.py.
Referenced by mplot3d.art3d.Collection3D.do_3d_projection(), mplot3d.art3d.Line3DCollection.do_3d_projection(), mplot3d.art3d.Poly3DCollection.do_3d_projection(), mplot3d.art3d.Line3D.get_data_3d(), mplot3d.art3d.Patch3D.get_path(), mplot3d.art3d.Patch3DCollection.set_3d_properties(), mplot3d.art3d.PathPatch3D.set_3d_properties(), mplot3d.art3d.Text3D.set_3d_properties(), and mplot3d.art3d.Path3DCollection.set_depthshade().
_zalpha()
mplot3d.art3d._zalpha (colors, zs) protected
Modify the alphas of the color list according to depth.
Definition at line 1293 of file art3d.py.
Referenced by mplot3d.art3d.Patch3DCollection.set_3d_properties(), and mplot3d.art3d.Path3DCollection.set_depthshade().
collection_2d_to_3d()
mplot3d.art3d.collection_2d_to_3d (col, zs = 0, zdir = 'z', axlim_clip = False)
Convert a `.Collection` to a `.Collection3D` object.
Definition at line 416 of file art3d.py.
References juggle_axes().
get_dir_vector()
mplot3d.art3d.get_dir_vector (zdir)
Return a direction vector.
Parameters
----------
zdir : {'x', 'y', 'z', None, 3-tuple}
    The direction. Possible values are:
    - 'x': equivalent to (1, 0, 0)
    - 'y': equivalent to (0, 1, 0)
    - 'z': equivalent to (0, 0, 1)
    - *None*: equivalent to (0, 0, 0)
    - an iterable (x, y, z) is converted to an array
Returns
-------
x, y, z : array
    The direction vector.
Definition at line 42 of file art3d.py.
Referenced by mplot3d.art3d.Text3D.set_3d_properties(), and mplot3d.art3d.Text3D.set_position_3d().
juggle_axes()
mplot3d.art3d.juggle_axes (xs, ys, zs, zdir)
Reorder coordinates so that 2D *xs*, *ys* can be plotted in the plane
orthogonal to *zdir*. *zdir* is normally 'x', 'y' or 'z'. However, if
*zdir* starts with a '-' it is interpreted as a compensation for
`rotate_axes`.
Definition at line 1262 of file art3d.py.
References rotate_axes().
Referenced by _path_to_3d_segment(), _path_to_3d_segment_with_codes(), collection_2d_to_3d(), mplot3d.art3d.Line3D.set_3d_properties(), mplot3d.art3d.Patch3D.set_3d_properties(), mplot3d.art3d.Patch3DCollection.set_3d_properties(), and mplot3d.art3d.Path3DCollection.set_3d_properties().
line_2d_to_3d()
mplot3d.art3d.line_2d_to_3d (line, zs = 0, zdir = 'z', axlim_clip = False)
Convert a `.Line2D` to a `.Line3D` object.
Parameters
----------
zs : float
    The location along the *zdir* axis in 3D space to position the line.
zdir : {'x', 'y', 'z'}
    Plane to plot line orthogonal to. Default: 'z'.
    See `.get_dir_vector` for a description of the values.
axlim_clip : bool, default: False
    Whether to hide lines with an endpoint outside the axes view limits.
Definition at line 327 of file art3d.py.
line_collection_2d_to_3d()
mplot3d.art3d.line_collection_2d_to_3d (col, zs = 0, zdir = 'z', axlim_clip = False)
Convert a `.LineCollection` to a `.Line3DCollection` object.
Definition at line 472 of file art3d.py.
References _paths_to_3d_segments().
patch_2d_to_3d()
mplot3d.art3d.patch_2d_to_3d (patch, z = 0, zdir = 'z', axlim_clip = False)
Convert a `.Patch` to a `.Patch3D` object.
Definition at line 608 of file art3d.py.
References _get_patch_verts().
patch_collection_2d_to_3d()
mplot3d.art3d.patch_collection_2d_to_3d (col, zs = 0, zdir = 'z', depthshade = True, axlim_clip = False)
Convert a `.PatchCollection` into a `.Patch3DCollection` object
(or a `.PathCollection` into a `.Path3DCollection` object).
Parameters
----------
col : `~matplotlib.collections.PatchCollection` or \
`~matplotlib.collections.PathCollection`
    The collection to convert.
zs : float or array of floats
    The location or locations to place the patches in the collection along
    the *zdir* axis. Default: 0.
zdir : {'x', 'y', 'z'}
    The axis in which to place the patches. Default: "z".
    See `.get_dir_vector` for a description of the values.
depthshade : bool, default: True
    Whether to shade the patches to give a sense of depth.
axlim_clip : bool, default: False
    Whether to hide patches with a vertex outside the axes view limits.
Definition at line 926 of file art3d.py.
pathpatch_2d_to_3d()
mplot3d.art3d.pathpatch_2d_to_3d (pathpatch, z = 0, zdir = 'z')
Convert a `.PathPatch` to a `.PathPatch3D` object.
Definition at line 615 of file art3d.py.
poly_collection_2d_to_3d()
mplot3d.art3d.poly_collection_2d_to_3d (col, zs = 0, zdir = 'z', axlim_clip = False)
Convert a `.PolyCollection` into a `.Poly3DCollection` object.
Parameters
----------
col : `~matplotlib.collections.PolyCollection`
    The collection to convert.
zs : float or array of floats
    The location or locations to place the polygons in the collection along
    the *zdir* axis. Default: 0.
zdir : {'x', 'y', 'z'}
    The axis in which to place the patches. Default: 'z'.
    See `.get_dir_vector` for a description of the values.
Definition at line 1239 of file art3d.py.
References _paths_to_3d_segments_with_codes().
rotate_axes()
mplot3d.art3d.rotate_axes (xs, ys, zs, zdir)
Reorder coordinates so that the axes are rotated with *zdir* along
the original z axis. Prepending the axis with a '-' does the
inverse transform, so *zdir* can be 'x', '-x', 'y', '-y', 'z' or '-z'.
Definition at line 1279 of file art3d.py.
Referenced by juggle_axes().
text_2d_to_3d()
mplot3d.art3d.text_2d_to_3d (obj, z = 0, zdir = 'z', axlim_clip = False)
Convert a `.Text` to a `.Text3D` object.
Parameters
----------
z : float
    The z-position in 3D space.
zdir : {'x', 'y', 'z', 3-tuple}
    The direction of the text. Default: 'z'.
    See `.get_dir_vector` for a description of the values.
axlim_clip : bool, default: False
    Whether to hide text outside the axes view limits.
Definition at line 207 of file art3d.py.