Code Cloning Analysis: fontTools.feaLib.parser.SymbolTable Class Reference
fontTools.feaLib.parser.SymbolTable Class Reference
Public Member Functions
__init__ (self)
enter_scope (self)
exit_scope (self)
define (self, name, item)
resolve (self, name)
Public Attributes
list scopes_ = [{}]
Detailed Description
Definition at line 2361 of file parser.py.
Constructor & Destructor Documentation
__init__()
fontTools.feaLib.parser.SymbolTable.__init__ (self)
Definition at line 2362 of file parser.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
define()
fontTools.feaLib.parser.SymbolTable.define (self, name, item)
Definition at line 2371 of file parser.py.
enter_scope()
fontTools.feaLib.parser.SymbolTable.enter_scope (self)
Definition at line 2365 of file parser.py.
exit_scope()
fontTools.feaLib.parser.SymbolTable.exit_scope (self)
Definition at line 2368 of file parser.py.
resolve()
fontTools.feaLib.parser.SymbolTable.resolve (self, name)
Definition at line 2374 of file parser.py.
Referenced by pip._vendor.distlib.compat.BaseConfigurator.configure_custom(), and pip._vendor.distlib.compat.BaseConfigurator.ext_convert().
Member Data Documentation
scopes_
fontTools.feaLib.parser.SymbolTable.scopes_ = [{}]
Definition at line 2363 of file parser.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/feaLib/parser.py