Code Cloning Analysis: joblib.test.test_parallel Namespace Reference
joblib.test.test_parallel Namespace Reference
Classes
class FakeParallelBackend
class MyBackend
class MyExceptionWithFinickyInit
class ParameterizedParallelBackend
Functions
get_default_backend_instance ()
get_workers (backend)
division (x, y)
square (x)
exception_raiser (x, custom_exception=False)
interrupt_raiser (x)
f (x, y=0, z=0)
_active_backend_type ()
parallel_func (inner_n_jobs, backend)
test_cpu_count ()
test_effective_n_jobs ()
test_effective_n_jobs_None (context, backend_n_jobs, expected_n_jobs)
test_simple_parallel (backend, n_jobs, verbose)
Test parallel.
test_parallel_pretty_print (backend, n_jobs)
test_main_thread_renamed_no_warning (backend, monkeypatch)
_assert_warning_nested (backend, inner_n_jobs, expected)
test_nested_parallel_warnings (parent_backend, child_backend, expected)
test_background_thread_parallelism (backend)
nested_loop (backend)
test_nested_loop (parent_backend, child_backend)
raise_exception (backend)
test_nested_loop_with_exception_with_loky ()
test_mutate_input_with_threads ()
test_parallel_kwargs (n_jobs)
test_parallel_as_context_manager (backend)
test_parallel_pickling ()
test_parallel_byteorder_corruption (byteorder, max_nbytes)
test_parallel_timeout_success (backend)
test_parallel_timeout_fail (backend)
test_parallel_timeout_fail_with_generator (backend, return_as)
test_error_capture (backend)
test_error_in_task_iterator (backend)
consumer (queue, item)
test_dispatch_one_job (backend, batch_size, expected_queue)
test_dispatch_multiprocessing (backend)
test_batching_auto_threading ()
test_batching_auto_subprocesses (backend)
test_exception_dispatch ()
nested_function_inner (i)
nested_function_outer (i)
test_nested_exception_dispatch (backend)
test_invalid_backend ()
test_invalid_njobs (backend)
test_njobs_converted_to_int (backend, n_jobs)
test_register_parallel_backend ()
test_overwrite_default_backend ()
test_backend_no_multiprocessing ()
check_backend_context_manager (context, backend_name)
test_backend_context_manager (monkeypatch, backend, context)
test_parameterized_backend_context_manager (monkeypatch, context)
test_directly_parameterized_backend_context_manager (context)
sleep_and_return_pid ()
get_nested_pids ()
test_nested_backend_context_manager (context, backend)
test_nested_backend_in_sequential (backend, n_jobs, context)
check_nesting_level (context, inner_backend, expected_level)
test_backend_nesting_level (context, outer_backend, inner_backend)
test_retrieval_context (context, with_retrieve_callback)
test_invalid_batch_size (batch_size)
Test helpers.
test_dispatch_race_condition (n_tasks, n_jobs, pre_dispatch, batch_size)
test_default_mp_context ()
test_no_blas_crash_or_freeze_with_subprocesses (backend)
test_parallel_with_interactively_defined_functions (backend)
test_parallel_with_unpicklable_functions_in_args (backend, define_func, callable_position, tmpdir)
test_parallel_with_interactively_defined_functions_loky (tmpdir)
test_parallel_with_interactively_defined_bound_method_loky (tmpdir)
test_parallel_with_exhausted_iterator ()
check_memmap (a)
test_auto_memmap_on_arrays_from_generator (backend)
identity (arg)
test_memmap_with_big_offset (tmpdir)
test_warning_about_timeout_not_supported_by_backend ()
set_list_value (input_list, index, value)
test_parallel_return_order_with_return_as_generator_parameter (n_jobs)
_sqrt_with_delay (e, delay)
_test_parallel_unordered_generator_returns_fastest_first (backend, n_jobs)
test_parallel_unordered_generator_returns_fastest_first (backend, n_jobs)
test_abort_backend (n_jobs, backend)
get_large_object (arg)
_test_deadlock_with_generator (backend, return_as, n_jobs)
test_deadlock_with_generator (backend, return_as, n_jobs)
test_multiple_generator_call (backend, return_as, n_jobs)
test_multiple_generator_call_managed (backend, return_as, n_jobs)
test_multiple_generator_call_separated (backend, return_as_1, return_as_2, n_jobs)
test_multiple_generator_call_separated_gc (backend, return_as_1, return_as_2, error)
test_memmapping_leaks (backend, tmpdir)
test_lambda_expression (backend)
test_backend_batch_statistics_reset (backend)
test_backend_hinting_and_constraints (context)
test_backend_hinting_always_running (n_jobs, prefer)
test_backend_hinting_and_constraints_with_custom_backends (capsys, context)
test_invalid_backend_hinting_and_constraints ()
_recursive_backend_info (limit=3, **kwargs)
test_nested_parallelism_limit (context, backend)
_recursive_parallel (nesting_limit=None)
test_thread_bomb_mitigation (context, backend)
_run_parallel_sum ()
test_parallel_thread_limit (backend)
test_dask_backend_when_dask_not_installed (context)
test_zero_worker_backend (context)
test_globals_update_at_each_parallel_call ()
_check_numpy_threadpool_limits ()
Test environment variable in child env, in particular for limiting the maximal number of threads in C-library threadpools.
_parent_max_num_threads_for (child_module, parent_info)
check_child_num_threads (workers_info, parent_info, num_threads)
test_threadpool_limitation_in_child_loky (n_jobs)
test_threadpool_limitation_in_child_context (context, n_jobs, inner_max_num_threads)
test_threadpool_limitation_in_child_override (context, n_jobs, var_name)
test_loky_reuse_workers (n_jobs)
_set_initialized (status)
_check_status (status, n_jobs, wait_workers=False)
test_initializer_context (n_jobs, backend, context)
test_initializer_parallel (n_jobs, backend)
test_initializer_reused (n_jobs)
test_initializer_not_reused (n_jobs)
Variables
posix = None
parallel_sum = None
distributed = None
RETURN_GENERATOR_BACKENDS = BACKENDS.copy()
list ALL_VALID_BACKENDS = [None] + sorted(BACKENDS.keys())
list PROCESS_BACKENDS = []
list PARALLEL_BACKENDS = PROCESS_BACKENDS + ["threading"]
list all_backends_for_context_manager = PARALLEL_BACKENDS[:]
str UNPICKLABLE_CALLABLE_SCRIPT_TEMPLATE_NO_MAIN
str UNPICKLABLE_CALLABLE_SCRIPT_TEMPLATE_MAIN
str SQUARE_MAIN
str SQUARE_LOCAL
str SQUARE_LAMBDA
str INTERACTIVE_DEFINED_FUNCTION_AND_CLASS_SCRIPT_CONTENT
str INTERACTIVELY_DEFINED_SUBCLASS_WITH_METHOD_SCRIPT_CONTENT
Detailed Description
Test the parallel module.
Function Documentation
_active_backend_type()
joblib.test.test_parallel._active_backend_type () protected
Definition at line 143 of file test_parallel.py.
_assert_warning_nested()
joblib.test.test_parallel._assert_warning_nested (backend, inner_n_jobs, expected) protected
Definition at line 258 of file test_parallel.py.
_check_numpy_threadpool_limits()
joblib.test.test_parallel._check_numpy_threadpool_limits () protected
Test environment variable in child env, in particular for limiting the maximal number of threads in C-library threadpools.
Definition at line 1983 of file test_parallel.py.
References _check_numpy_threadpool_limits(), and threadpoolctl.threadpool_info().
Referenced by _check_numpy_threadpool_limits().
_check_status()
joblib.test.test_parallel._check_status (status, n_jobs, wait_workers = False) protected
Definition at line 2141 of file test_parallel.py.
_parent_max_num_threads_for()
joblib.test.test_parallel._parent_max_num_threads_for (child_module, parent_info) protected
Definition at line 1995 of file test_parallel.py.
_recursive_backend_info()
joblib.test.test_parallel._recursive_backend_info (limit = 3, ** kwargs) protected
Perform nested parallel calls and introspect the backend on the way
Definition at line 1824 of file test_parallel.py.
References _recursive_backend_info().
Referenced by _recursive_backend_info().
_recursive_parallel()
joblib.test.test_parallel._recursive_parallel (nesting_limit = None) protected
A horrible function that does recursive parallel calls
Definition at line 1855 of file test_parallel.py.
References _recursive_parallel().
Referenced by _recursive_parallel().
_run_parallel_sum()
joblib.test.test_parallel._run_parallel_sum () protected
Definition at line 1888 of file test_parallel.py.
_set_initialized()
joblib.test.test_parallel._set_initialized (status) protected
Definition at line 2137 of file test_parallel.py.
_sqrt_with_delay()
joblib.test.test_parallel._sqrt_with_delay (e, delay) protected
Definition at line 1414 of file test_parallel.py.
_test_deadlock_with_generator()
joblib.test.test_parallel._test_deadlock_with_generator (backend, return_as, n_jobs) protected
Definition at line 1472 of file test_parallel.py.
_test_parallel_unordered_generator_returns_fastest_first()
joblib.test.test_parallel._test_parallel_unordered_generator_returns_fastest_first (backend, n_jobs) protected
Definition at line 1424 of file test_parallel.py.
check_backend_context_manager()
joblib.test.test_parallel.check_backend_context_manager (context, backend_name)
Definition at line 827 of file test_parallel.py.
check_child_num_threads()
joblib.test.test_parallel.check_child_num_threads (workers_info, parent_info, num_threads)
Definition at line 2004 of file test_parallel.py.
check_memmap()
joblib.test.test_parallel.check_memmap (a)
Definition at line 1326 of file test_parallel.py.
check_nesting_level()
joblib.test.test_parallel.check_nesting_level (context, inner_backend, expected_level)
Definition at line 996 of file test_parallel.py.
consumer()
joblib.test.test_parallel.consumer (queue, item)
Definition at line 583 of file test_parallel.py.
division()
joblib.test.test_parallel.division (x, y)
Definition at line 106 of file test_parallel.py.
exception_raiser()
joblib.test.test_parallel.exception_raiser (x, custom_exception = False)
Definition at line 121 of file test_parallel.py.
f()
joblib.test.test_parallel.f (x, y = 0, z = 0)
A module-level function so that it can be spawn with
multiprocessing.
Definition at line 136 of file test_parallel.py.
get_default_backend_instance()
joblib.test.test_parallel.get_default_backend_instance ()
Definition at line 94 of file test_parallel.py.
get_large_object()
joblib.test.test_parallel.get_large_object (arg)
Definition at line 1462 of file test_parallel.py.
get_nested_pids()
joblib.test.test_parallel.get_nested_pids ()
Definition at line 932 of file test_parallel.py.
get_workers()
joblib.test.test_parallel.get_workers (backend)
Definition at line 102 of file test_parallel.py.
identity()
joblib.test.test_parallel.identity (arg)
Definition at line 1362 of file test_parallel.py.
interrupt_raiser()
joblib.test.test_parallel.interrupt_raiser (x)
Definition at line 131 of file test_parallel.py.
nested_function_inner()
joblib.test.test_parallel.nested_function_inner (i)
Definition at line 706 of file test_parallel.py.
nested_function_outer()
joblib.test.test_parallel.nested_function_outer (i)
Definition at line 710 of file test_parallel.py.
nested_loop()
joblib.test.test_parallel.nested_loop (backend)
Definition at line 336 of file test_parallel.py.
parallel_func()
joblib.test.test_parallel.parallel_func (inner_n_jobs, backend)
Definition at line 147 of file test_parallel.py.
raise_exception()
joblib.test.test_parallel.raise_exception (backend)
Definition at line 348 of file test_parallel.py.
set_list_value()
joblib.test.test_parallel.set_list_value (input_list, index, value)
Definition at line 1393 of file test_parallel.py.
sleep_and_return_pid()
joblib.test.test_parallel.sleep_and_return_pid ()
Definition at line 927 of file test_parallel.py.
square()
joblib.test.test_parallel.square (x)
Definition at line 110 of file test_parallel.py.
test_abort_backend()
joblib.test.test_parallel.test_abort_backend (n_jobs, backend)
Definition at line 1453 of file test_parallel.py.
test_auto_memmap_on_arrays_from_generator()
joblib.test.test_parallel.test_auto_memmap_on_arrays_from_generator (backend)
Definition at line 1335 of file test_parallel.py.
test_backend_batch_statistics_reset()
joblib.test.test_parallel.test_backend_batch_statistics_reset (backend)
Test that a parallel backend correctly resets its batch statistics.
Definition at line 1661 of file test_parallel.py.
test_backend_context_manager()
joblib.test.test_parallel.test_backend_context_manager (monkeypatch, backend, context)
Definition at line 855 of file test_parallel.py.
test_backend_hinting_always_running()
joblib.test.test_parallel.test_backend_hinting_always_running (n_jobs, prefer)
Definition at line 1733 of file test_parallel.py.
test_backend_hinting_and_constraints()
joblib.test.test_parallel.test_backend_hinting_and_constraints (context)
Definition at line 1685 of file test_parallel.py.
test_backend_hinting_and_constraints_with_custom_backends()
joblib.test.test_parallel.test_backend_hinting_and_constraints_with_custom_backends (capsys, context)
Definition at line 1749 of file test_parallel.py.
test_backend_nesting_level()
joblib.test.test_parallel.test_backend_nesting_level (context, outer_backend, inner_backend)
Definition at line 1009 of file test_parallel.py.
test_backend_no_multiprocessing()
joblib.test.test_parallel.test_backend_no_multiprocessing ()
Definition at line 818 of file test_parallel.py.
test_background_thread_parallelism()
joblib.test.test_parallel.test_background_thread_parallelism (backend)
Definition at line 321 of file test_parallel.py.
test_batching_auto_subprocesses()
joblib.test.test_parallel.test_batching_auto_subprocesses (backend)
Definition at line 688 of file test_parallel.py.
test_batching_auto_threading()
joblib.test.test_parallel.test_batching_auto_threading ()
Definition at line 676 of file test_parallel.py.
test_cpu_count()
joblib.test.test_parallel.test_cpu_count ()
Definition at line 154 of file test_parallel.py.
test_dask_backend_when_dask_not_installed()
joblib.test.test_parallel.test_dask_backend_when_dask_not_installed (context)
Definition at line 1922 of file test_parallel.py.
test_deadlock_with_generator()
joblib.test.test_parallel.test_deadlock_with_generator (backend, return_as, n_jobs)
Definition at line 1486 of file test_parallel.py.
test_default_mp_context()
joblib.test.test_parallel.test_default_mp_context ()
Definition at line 1088 of file test_parallel.py.
test_directly_parameterized_backend_context_manager()
joblib.test.test_parallel.test_directly_parameterized_backend_context_manager (context)
Definition at line 907 of file test_parallel.py.
test_dispatch_multiprocessing()
joblib.test.test_parallel.test_dispatch_multiprocessing (backend)
Check that using pre_dispatch Parallel does indeed dispatch items
lazily.
Definition at line 646 of file test_parallel.py.
test_dispatch_one_job()
joblib.test.test_parallel.test_dispatch_one_job (backend, batch_size, expected_queue)
Test that with only one job, Parallel does act as a iterator.
Definition at line 628 of file test_parallel.py.
test_dispatch_race_condition()
joblib.test.test_parallel.test_dispatch_race_condition (n_tasks, n_jobs, pre_dispatch, batch_size)
Definition at line 1077 of file test_parallel.py.
test_effective_n_jobs()
joblib.test.test_parallel.test_effective_n_jobs ()
Definition at line 158 of file test_parallel.py.
test_effective_n_jobs_None()
joblib.test.test_parallel.test_effective_n_jobs_None (context, backend_n_jobs, expected_n_jobs)
Definition at line 169 of file test_parallel.py.
test_error_capture()
joblib.test.test_parallel.test_error_capture (backend)
Definition at line 489 of file test_parallel.py.
test_error_in_task_iterator()
joblib.test.test_parallel.test_error_in_task_iterator (backend)
Definition at line 561 of file test_parallel.py.
test_exception_dispatch()
joblib.test.test_parallel.test_exception_dispatch ()
Make sure that exception raised during dispatch are indeed captured
Definition at line 698 of file test_parallel.py.
test_globals_update_at_each_parallel_call()
joblib.test.test_parallel.test_globals_update_at_each_parallel_call ()
Definition at line 1947 of file test_parallel.py.
test_initializer_context()
joblib.test.test_parallel.test_initializer_context (n_jobs, backend, context)
Definition at line 2168 of file test_parallel.py.
test_initializer_not_reused()
joblib.test.test_parallel.test_initializer_not_reused (n_jobs)
Definition at line 2228 of file test_parallel.py.
test_initializer_parallel()
joblib.test.test_parallel.test_initializer_parallel (n_jobs, backend)
Definition at line 2186 of file test_parallel.py.
test_initializer_reused()
joblib.test.test_parallel.test_initializer_reused (n_jobs)
Definition at line 2202 of file test_parallel.py.
test_invalid_backend()
joblib.test.test_parallel.test_invalid_backend ()
Definition at line 753 of file test_parallel.py.
test_invalid_backend_hinting_and_constraints()
joblib.test.test_parallel.test_invalid_backend_hinting_and_constraints ()
Definition at line 1803 of file test_parallel.py.
test_invalid_batch_size()
joblib.test.test_parallel.test_invalid_batch_size (batch_size)
Test helpers.
Definition at line 1056 of file test_parallel.py.
test_invalid_njobs()
joblib.test.test_parallel.test_invalid_njobs (backend)
Definition at line 767 of file test_parallel.py.
test_lambda_expression()
joblib.test.test_parallel.test_lambda_expression (backend)
Definition at line 1651 of file test_parallel.py.
test_loky_reuse_workers()
joblib.test.test_parallel.test_loky_reuse_workers (n_jobs)
Definition at line 2117 of file test_parallel.py.
test_main_thread_renamed_no_warning()
joblib.test.test_parallel.test_main_thread_renamed_no_warning (backend, monkeypatch)
Definition at line 216 of file test_parallel.py.
test_memmap_with_big_offset()
joblib.test.test_parallel.test_memmap_with_big_offset (tmpdir)
Definition at line 1368 of file test_parallel.py.
test_memmapping_leaks()
joblib.test.test_parallel.test_memmapping_leaks (backend, tmpdir)
Definition at line 1614 of file test_parallel.py.
test_multiple_generator_call()
joblib.test.test_parallel.test_multiple_generator_call (backend, return_as, n_jobs)
Definition at line 1493 of file test_parallel.py.
test_multiple_generator_call_managed()
joblib.test.test_parallel.test_multiple_generator_call_managed (backend, return_as, n_jobs)
Definition at line 1515 of file test_parallel.py.
test_multiple_generator_call_separated()
joblib.test.test_parallel.test_multiple_generator_call_separated (backend, return_as_1, return_as_2, n_jobs)
Definition at line 1538 of file test_parallel.py.
test_multiple_generator_call_separated_gc()
joblib.test.test_parallel.test_multiple_generator_call_separated_gc (backend, return_as_1, return_as_2, error)
Definition at line 1567 of file test_parallel.py.
test_mutate_input_with_threads()
joblib.test.test_parallel.test_mutate_input_with_threads ()
Input is mutable when using the threading backend
Definition at line 359 of file test_parallel.py.
test_nested_backend_context_manager()
joblib.test.test_parallel.test_nested_backend_context_manager (context, backend)
Definition at line 958 of file test_parallel.py.
test_nested_backend_in_sequential()
joblib.test.test_parallel.test_nested_backend_in_sequential (backend, n_jobs, context)
Definition at line 972 of file test_parallel.py.
test_nested_exception_dispatch()
joblib.test.test_parallel.test_nested_exception_dispatch (backend)
Ensure errors for nested joblib cases gets propagated
We rely on the Python 3 built-in __cause__ system that already
report this kind of information to the user.
Definition at line 717 of file test_parallel.py.
test_nested_loop()
joblib.test.test_parallel.test_nested_loop (parent_backend, child_backend)
Definition at line 342 of file test_parallel.py.
test_nested_loop_with_exception_with_loky()
joblib.test.test_parallel.test_nested_loop_with_exception_with_loky ()
Definition at line 353 of file test_parallel.py.
test_nested_parallel_warnings()
joblib.test.test_parallel.test_nested_parallel_warnings (parent_backend, child_backend, expected)
Definition at line 294 of file test_parallel.py.
test_nested_parallelism_limit()
joblib.test.test_parallel.test_nested_parallelism_limit (context, backend)
Definition at line 1841 of file test_parallel.py.
test_njobs_converted_to_int()
joblib.test.test_parallel.test_njobs_converted_to_int (backend, n_jobs)
Definition at line 788 of file test_parallel.py.
test_no_blas_crash_or_freeze_with_subprocesses()
joblib.test.test_parallel.test_no_blas_crash_or_freeze_with_subprocesses (backend)
Definition at line 1099 of file test_parallel.py.
test_overwrite_default_backend()
joblib.test.test_parallel.test_overwrite_default_backend ()
Definition at line 805 of file test_parallel.py.
test_parallel_as_context_manager()
joblib.test.test_parallel.test_parallel_as_context_manager (backend)
Definition at line 376 of file test_parallel.py.
test_parallel_byteorder_corruption()
joblib.test.test_parallel.test_parallel_byteorder_corruption (byteorder, max_nbytes)
Definition at line 425 of file test_parallel.py.
test_parallel_kwargs()
joblib.test.test_parallel.test_parallel_kwargs (n_jobs)
Check the keyword argument processing of pmap.
Definition at line 367 of file test_parallel.py.
test_parallel_pickling()
joblib.test.test_parallel.test_parallel_pickling ()
Check that pmap captures the errors when it is passed an object
that cannot be pickled.
Definition at line 406 of file test_parallel.py.
test_parallel_pretty_print()
joblib.test.test_parallel.test_parallel_pretty_print (backend, n_jobs)
Definition at line 195 of file test_parallel.py.
test_parallel_return_order_with_return_as_generator_parameter()
joblib.test.test_parallel.test_parallel_return_order_with_return_as_generator_parameter (n_jobs)
Definition at line 1399 of file test_parallel.py.
test_parallel_thread_limit()
joblib.test.test_parallel.test_parallel_thread_limit (backend)
Definition at line 1905 of file test_parallel.py.
test_parallel_timeout_fail()
joblib.test.test_parallel.test_parallel_timeout_fail (backend)
Definition at line 458 of file test_parallel.py.
test_parallel_timeout_fail_with_generator()
joblib.test.test_parallel.test_parallel_timeout_fail_with_generator (backend, return_as)
Definition at line 469 of file test_parallel.py.
test_parallel_timeout_success()
joblib.test.test_parallel.test_parallel_timeout_success (backend)
Definition at line 444 of file test_parallel.py.
test_parallel_unordered_generator_returns_fastest_first()
joblib.test.test_parallel.test_parallel_unordered_generator_returns_fastest_first (backend, n_jobs)
Definition at line 1447 of file test_parallel.py.
test_parallel_with_exhausted_iterator()
joblib.test.test_parallel.test_parallel_with_exhausted_iterator ()
Definition at line 1321 of file test_parallel.py.
test_parallel_with_interactively_defined_bound_method_loky()
joblib.test.test_parallel.test_parallel_with_interactively_defined_bound_method_loky (tmpdir)
Definition at line 1310 of file test_parallel.py.
test_parallel_with_interactively_defined_functions()
joblib.test.test_parallel.test_parallel_with_interactively_defined_functions (backend)
Definition at line 1139 of file test_parallel.py.
test_parallel_with_interactively_defined_functions_loky()
joblib.test.test_parallel.test_parallel_with_interactively_defined_functions_loky (tmpdir)
Definition at line 1271 of file test_parallel.py.
test_parallel_with_unpicklable_functions_in_args()
joblib.test.test_parallel.test_parallel_with_unpicklable_functions_in_args (backend, define_func, callable_position, tmpdir)
Definition at line 1205 of file test_parallel.py.
test_parameterized_backend_context_manager()
joblib.test.test_parallel.test_parameterized_backend_context_manager (monkeypatch, context)
Definition at line 887 of file test_parallel.py.
test_register_parallel_backend()
joblib.test.test_parallel.test_register_parallel_backend ()
Definition at line 796 of file test_parallel.py.
test_retrieval_context()
joblib.test.test_parallel.test_retrieval_context (context, with_retrieve_callback)
Definition at line 1026 of file test_parallel.py.
test_simple_parallel()
joblib.test.test_parallel.test_simple_parallel (backend, n_jobs, verbose)
Test parallel.
Definition at line 187 of file test_parallel.py.
test_thread_bomb_mitigation()
joblib.test.test_parallel.test_thread_bomb_mitigation (context, backend)
Definition at line 1863 of file test_parallel.py.
test_threadpool_limitation_in_child_context()
joblib.test.test_parallel.test_threadpool_limitation_in_child_context (context, n_jobs, inner_max_num_threads)
Definition at line 2049 of file test_parallel.py.
test_threadpool_limitation_in_child_loky()
joblib.test.test_parallel.test_threadpool_limitation_in_child_loky (n_jobs)
Definition at line 2020 of file test_parallel.py.
test_threadpool_limitation_in_child_override()
joblib.test.test_parallel.test_threadpool_limitation_in_child_override (context, n_jobs, var_name)
Definition at line 2080 of file test_parallel.py.
test_warning_about_timeout_not_supported_by_backend()
joblib.test.test_parallel.test_warning_about_timeout_not_supported_by_backend ()
Definition at line 1380 of file test_parallel.py.
test_zero_worker_backend()
joblib.test.test_parallel.test_zero_worker_backend (context)
Definition at line 1928 of file test_parallel.py.
Variable Documentation
all_backends_for_context_manager
list joblib.test.test_parallel.all_backends_for_context_manager = PARALLEL_BACKENDS[:]
Definition at line 848 of file test_parallel.py.
ALL_VALID_BACKENDS
list joblib.test.test_parallel.ALL_VALID_BACKENDS = [None] + sorted(BACKENDS.keys())
Definition at line 80 of file test_parallel.py.
distributed
joblib.test.test_parallel.distributed = None
Definition at line 56 of file test_parallel.py.
INTERACTIVE_DEFINED_FUNCTION_AND_CLASS_SCRIPT_CONTENT
str joblib.test.test_parallel.INTERACTIVE_DEFINED_FUNCTION_AND_CLASS_SCRIPT_CONTENT
Definition at line 1227 of file test_parallel.py.
INTERACTIVELY_DEFINED_SUBCLASS_WITH_METHOD_SCRIPT_CONTENT
str joblib.test.test_parallel.INTERACTIVELY_DEFINED_SUBCLASS_WITH_METHOD_SCRIPT_CONTENT
Initial value:
=  """\
import sys
# Make sure that joblib is importable in the subprocess launching this
# script. This is needed in case we run the tests from the joblib root
# folder without having installed joblib
sys.path.insert(0, {joblib_root_folder!r})
from joblib import Parallel, delayed, hash
import multiprocessing as mp
mp.util.log_to_stderr(5)
class MyList(list):
    '''MyList is interactively defined by MyList.append is a built-in'''
    def __hash__(self):
        # XXX: workaround limitation in cloudpickle
        return hash(self).__hash__()
l = MyList()
print(Parallel(backend="loky", n_jobs=2)(
    delayed(l.append)(i) for i in range(3)
))
""".format(joblib_root_folder=os.path.dirname(os.path.dirname(joblib.__file__)))
Definition at line 1284 of file test_parallel.py.
PARALLEL_BACKENDS
list joblib.test.test_parallel.PARALLEL_BACKENDS = PROCESS_BACKENDS + ["threading"]
Definition at line 87 of file test_parallel.py.
parallel_sum
joblib.test.test_parallel.parallel_sum = None
Definition at line 51 of file test_parallel.py.
posix
joblib.test.test_parallel.posix = None
Definition at line 46 of file test_parallel.py.
PROCESS_BACKENDS
list joblib.test.test_parallel.PROCESS_BACKENDS = []
Definition at line 84 of file test_parallel.py.
RETURN_GENERATOR_BACKENDS
joblib.test.test_parallel.RETURN_GENERATOR_BACKENDS = BACKENDS.copy()
Definition at line 77 of file test_parallel.py.
SQUARE_LAMBDA
str joblib.test.test_parallel.SQUARE_LAMBDA
Initial value:
=  """\
square = lambda x: x ** 2
"""
Definition at line 1196 of file test_parallel.py.
SQUARE_LOCAL
str joblib.test.test_parallel.SQUARE_LOCAL
Initial value:
=  """\
def gen_square():
    def square(x):
        return x ** 2
    return square
square = gen_square()
"""
Definition at line 1189 of file test_parallel.py.
SQUARE_MAIN
str joblib.test.test_parallel.SQUARE_MAIN
Initial value:
=  """\
def square(x):
    return x ** 2
"""
Definition at line 1185 of file test_parallel.py.
UNPICKLABLE_CALLABLE_SCRIPT_TEMPLATE_MAIN
str joblib.test.test_parallel.UNPICKLABLE_CALLABLE_SCRIPT_TEMPLATE_MAIN
Definition at line 1153 of file test_parallel.py.
UNPICKLABLE_CALLABLE_SCRIPT_TEMPLATE_NO_MAIN
str joblib.test.test_parallel.UNPICKLABLE_CALLABLE_SCRIPT_TEMPLATE_NO_MAIN
Initial value:
=  """\
from joblib import Parallel, delayed
def square(x):
    return x ** 2
backend = "{}"
if backend == "spawn":
    from multiprocessing import get_context
    backend = get_context(backend)
print(Parallel(n_jobs=2, backend=backend)(
      delayed(square)(i) for i in range(5)))
"""
Definition at line 1121 of file test_parallel.py.