Code Cloning Analysis: fontTools.designspaceLib.AxisMappingDescriptor Class Reference
fontTools.designspaceLib.AxisMappingDescriptor Class Reference
Public Member Functions
__init__ (self, *, inputLocation=None, outputLocation=None, description=None, groupDescription=None)
Public Member Functions inherited from fontTools.designspaceLib.SimpleDescriptor
compare (self, other)
__repr__ (self)
Public Member Functions inherited from fontTools.designspaceLib.AsDictMixin
asdict (self)
Public Attributes
SimpleLocationDict inputLocation = inputLocation or {}
SimpleLocationDict outputLocation = outputLocation or {}
description = description
groupDescription = groupDescription
Additional Inherited Members
Protected Attributes inherited from fontTools.designspaceLib.SimpleDescriptor
_attrs
Detailed Description
Represents the axis mapping element: mapping an input location
to an output location in the designspace.
.. code:: python
    m1 = AxisMappingDescriptor()
    m1.inputLocation = {"weight": 900, "width": 150}
    m1.outputLocation = {"weight": 870}
.. code:: xml
    <mappings>
        <mapping>
            <input>
                <dimension name="weight" xvalue="900"/>
                <dimension name="width" xvalue="150"/>
            </input>
            <output>
                <dimension name="weight" xvalue="870"/>
            </output>
        </mapping>
    </mappings>
Definition at line 453 of file __init__.py.
Constructor & Destructor Documentation
__init__()
fontTools.designspaceLib.AxisMappingDescriptor.__init__ (self, * , inputLocation = None, outputLocation = None, description = None, groupDescription = None)
Definition at line 480 of file __init__.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Data Documentation
description
fontTools.designspaceLib.AxisMappingDescriptor.description = description
Definition at line 502 of file __init__.py.
Referenced by pandas.io.pytables.IndexCol.col(), fontTools.ttLib.tables.otConverters.BaseConverter.getVarIndexOffset(), pandas.io.pytables.GenericTable.indexables(), and pandas.io.pytables.Table.indexables().
groupDescription
fontTools.designspaceLib.AxisMappingDescriptor.groupDescription = groupDescription
Definition at line 509 of file __init__.py.
inputLocation
SimpleLocationDict fontTools.designspaceLib.AxisMappingDescriptor.inputLocation = inputLocation or {}
Definition at line 488 of file __init__.py.
outputLocation
SimpleLocationDict fontTools.designspaceLib.AxisMappingDescriptor.outputLocation = outputLocation or {}
Definition at line 495 of file __init__.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/designspaceLib/__init__.py