Code Cloning Analysis: scipy._lib._util Namespace Reference
scipy._lib._util Namespace Reference
Classes
class _FunctionWrapper
class Generator
class MapWrapper
Functions
_lazywhere (cond, arrays, f, fillvalue=None, f2=None)
_lazyselect (condlist, choicelist, arrays, default=0)
_aligned_zeros (shape, dtype=float, order="C", align=None)
_prune_array (array)
float float_factorial (int n)
check_random_state (seed)
_asarray_validated (a, check_finite=True, sparse_ok=False, objects_ok=False, mask_ok=False, as_inexact=False)
_validate_int (k, name, minimum=None)
getfullargspec_no_self (func)
rng_integers (gen, low, high=None, size=None, dtype='int64', endpoint=False)
_fixed_default_rng (seed=1638083107694713882823079058616272161)
_rng_html_rewrite (func)
_argmin (a, keepdims=False, axis=None)
_first_nonnan (a, axis)
_nan_allsame (a, axis, keepdims=False)
_contains_nan (a, nan_policy='propagate', use_summation=True, policies=None)
_rename_parameter (old_name, new_name, dep_version=None)
_rng_spawn (rng, n_children)
_get_nan (*data)
Variables
IntNumber = Union[int, np.integer]
DecimalNumber = Union[float, np.floating, np.integer]
SeedType
GeneratorType
FullArgSpec
Function Documentation
_aligned_zeros()
scipy._lib._util._aligned_zeros (shape, dtype = float, order = "C", align = None) protected
Allocate a new ndarray with aligned memory.
Primary use case for this currently is working around a f2py issue
in NumPy 1.9.1, where dtype.alignment is such that np.zeros() does
not necessarily create arrays aligned up to it.
Definition at line 118 of file _util.py.
_argmin()
scipy._lib._util._argmin (a, keepdims = False, axis = None) protected
argmin with a `keepdims` parameter.
See https://github.com/numpy/numpy/issues/8710
If axis is not None, a.shape[axis] must be greater than 0.
Definition at line 535 of file _util.py.
Referenced by _first_nonnan().
_asarray_validated()
scipy._lib._util._asarray_validated (a, check_finite = True, sparse_ok = False, objects_ok = False, mask_ok = False, as_inexact = False) protected
Helper function for SciPy argument validation.
Many SciPy linear algebra functions do support arbitrary array-like
input arguments. Examples of commonly unsupported inputs include
matrices containing inf/nan, sparse matrix representations, and
matrices with complicated elements.
Parameters
----------
a : array_like
    The array-like input.
check_finite : bool, optional
    Whether to check that the input matrices contain only finite numbers.
    Disabling may give a performance gain, but may result in problems
    (crashes, non-termination) if the inputs do contain infinities or NaNs.
    Default: True
sparse_ok : bool, optional
    True if scipy sparse matrices are allowed.
objects_ok : bool, optional
    True if arrays with dype('O') are allowed.
mask_ok : bool, optional
    True if masked arrays are allowed.
as_inexact : bool, optional
    True to convert the input array to a np.inexact dtype.
Returns
-------
ret : ndarray
    The converted validated array.
Definition at line 194 of file _util.py.
_contains_nan()
scipy._lib._util._contains_nan (a, nan_policy = 'propagate', use_summation = True, policies = None) protected
Definition at line 629 of file _util.py.
_first_nonnan()
scipy._lib._util._first_nonnan (a, axis) protected
Return the first non-nan value along the given axis.
If a slice is all nan, nan is returned for that slice.
The shape of the return value corresponds to ``keepdims=True``.
Examples
--------
>>> import numpy as np
>>> nan = np.nan
>>> a = np.array([[ 3.,  3., nan,  3.],
                  [ 1., nan,  2.,  4.],
                  [nan, nan,  9., -1.],
                  [nan,  5.,  4.,  3.],
                  [ 2.,  2.,  2.,  2.],
                  [nan, nan, nan, nan]])
>>> _first_nonnan(a, axis=0)
array([[3., 3., 2., 3.]])
>>> _first_nonnan(a, axis=1)
array([[ 3.],
       [ 1.],
       [ 9.],
       [ 5.],
       [ 2.],
       [nan]])
Definition at line 549 of file _util.py.
References _argmin().
Referenced by _nan_allsame().
_fixed_default_rng()
scipy._lib._util._fixed_default_rng (seed = 1638083107694713882823079058616272161) protected
Context with a fixed np.random.default_rng seed.
Definition at line 502 of file _util.py.
_get_nan()
scipy._lib._util._get_nan (* data) protected
Definition at line 727 of file _util.py.
_lazyselect()
scipy._lib._util._lazyselect (condlist, choicelist, arrays, default = 0) protected
Mimic `np.select(condlist, choicelist)`.
Notice, it assumes that all `arrays` are of the same shape or can be
broadcasted together.
All functions in `choicelist` must accept array arguments in the order
given in `arrays` and must return an array of the same shape as broadcasted
`arrays`.
Examples
--------
>>> import numpy as np
>>> x = np.arange(6)
>>> np.select([x <3, x > 3], [x**2, x**3], default=0)
array([  0,   1,   4,   0,  64, 125])
>>> _lazyselect([x < 3, x > 3], [lambda x: x**2, lambda x: x**3], (x,))
array([   0.,    1.,    4.,   0.,   64.,  125.])
>>> a = -np.ones_like(x)
>>> _lazyselect([x < 3, x > 3],
...             [lambda x, a: x**2, lambda x, a: a * x**3],
...             (x, a), default=np.nan)
array([   0.,    1.,    4.,   nan,  -64., -125.])
Definition at line 78 of file _util.py.
_lazywhere()
scipy._lib._util._lazywhere (cond, arrays, f, fillvalue = None, f2 = None) protected
np.where(cond, x, fillvalue) always evaluates x even where cond is False.
This one only evaluates f(arr1[cond], arr2[cond], ...).
Examples
--------
>>> import numpy as np
>>> a, b = np.array([1, 2, 3, 4]), np.array([5, 6, 7, 8])
>>> def f(a, b):
...     return a*b
>>> _lazywhere(a > 2, (a, b), f, np.nan)
array([ nan,  nan,  21.,  32.])
Notice, it assumes that all `arrays` are of the same shape, or can be
broadcasted together.
Definition at line 37 of file _util.py.
_nan_allsame()
scipy._lib._util._nan_allsame (a, axis, keepdims = False) protected
Determine if the values along an axis are all the same.
nan values are ignored.
`a` must be a numpy array.
`axis` is assumed to be normalized; that is, 0 <= axis < a.ndim.
For an axis of length 0, the result is True.  That is, we adopt the
convention that ``allsame([])`` is True. (There are no values in the
input that are different.)
`True` is returned for slices that are all nan--not because all the
values are the same, but because this is equivalent to ``allsame([])``.
Examples
--------
>>> import numpy as np
>>> a = np.array([[ 3.,  3., nan,  3.],
                  [ 1., nan,  2.,  4.],
                  [nan, nan,  9., -1.],
                  [nan,  5.,  4.,  3.],
                  [ 2.,  2.,  2.,  2.],
                  [nan, nan, nan, nan]])
>>> _nan_allsame(a, axis=1, keepdims=True)
array([[ True],
       [False],
       [False],
       [False],
       [ True],
       [ True]])
Definition at line 581 of file _util.py.
References _first_nonnan().
_prune_array()
scipy._lib._util._prune_array (array) protected
Return an array equivalent to the input array. If the input
array is a view of a much larger array, copy its contents to a
newly allocated array. Otherwise, return the input unchanged.
Definition at line 144 of file _util.py.
_rename_parameter()
scipy._lib._util._rename_parameter (old_name, new_name, dep_version = None) protected
Generate decorator for backward-compatible keyword renaming.
Apply the decorator generated by `_rename_parameter` to functions with a
recently renamed parameter to maintain backward-compatibility.
After decoration, the function behaves as follows:
If only the new parameter is passed into the function, behave as usual.
If only the old parameter is passed into the function (as a keyword), raise
a DeprecationWarning if `dep_version` is provided, and behave as usual
otherwise.
If both old and new parameters are passed into the function, raise a
DeprecationWarning if `dep_version` is provided, and raise the appropriate
TypeError (function got multiple values for argument).
Parameters
----------
old_name : str
    Old name of parameter
new_name : str
    New name of parameter
dep_version : str, optional
    Version of SciPy in which old parameter was deprecated in the format
    'X.Y.Z'. If supplied, the deprecation message will indicate that
    support for the old parameter will be removed in version 'X.Y+2.Z'
Notes
-----
Untested with functions that accept *args. Probably won't work as written.
Definition at line 663 of file _util.py.
_rng_html_rewrite()
scipy._lib._util._rng_html_rewrite (func) protected
Rewrite the HTML rendering of ``np.random.default_rng``.
This is intended to decorate
``numpydoc.docscrape_sphinx.SphinxDocString._str_examples``.
Examples are only run by Sphinx when there are plot involved. Even so,
it does not change the result values getting printed.
Definition at line 512 of file _util.py.
_rng_spawn()
scipy._lib._util._rng_spawn (rng, n_children) protected
Definition at line 718 of file _util.py.
_validate_int()
scipy._lib._util._validate_int (k, name, minimum = None) protected
Validate a scalar integer.
This functon can be used to validate an argument to a function
that expects the value to be an integer.  It uses `operator.index`
to validate the value (so, for example, k=2.0 results in a
TypeError).
Parameters
----------
k : int
    The value to be validated.
name : str
    The name of the parameter.
minimum : int, optional
    An optional lower bound.
Definition at line 250 of file _util.py.
check_random_state()
scipy._lib._util.check_random_state (seed)
Turn `seed` into a `np.random.RandomState` instance.
Parameters
----------
seed : {None, int, `numpy.random.Generator`, `numpy.random.RandomState`}, optional
    If `seed` is None (or `np.random`), the `numpy.random.RandomState`
    singleton is used.
    If `seed` is an int, a new ``RandomState`` instance is used,
    seeded with `seed`.
    If `seed` is already a ``Generator`` or ``RandomState`` instance then
    that instance is used.
Returns
-------
seed : {`numpy.random.Generator`, `numpy.random.RandomState`}
    Random number generator.
Definition at line 164 of file _util.py.
float_factorial()
float scipy._lib._util.float_factorial (int n)
Compute the factorial and return as a float
Returns infinity when result is too large for a double
Definition at line 154 of file _util.py.
getfullargspec_no_self()
scipy._lib._util.getfullargspec_no_self (func)
inspect.getfullargspec replacement using inspect.signature.
If func is a bound method, do not list the 'self' parameter.
Parameters
----------
func : callable
    A callable to inspect
Returns
-------
fullargspec : FullArgSpec(args, varargs, varkw, defaults, kwonlyargs,
                          kwonlydefaults, annotations)
    NOTE: if the first argument of `func` is self, it is *not*, I repeat
    *not*, included in fullargspec.args.
    This is done for consistency between inspect.getargspec() under
    Python 2.x, and inspect.signature() under Python 3.x.
Definition at line 296 of file _util.py.
rng_integers()
scipy._lib._util.rng_integers (gen, low, high = None, size = None, dtype = 'int64', endpoint = False)
Return random integers from low (inclusive) to high (exclusive), or if
endpoint=True, low (inclusive) to high (inclusive). Replaces
`RandomState.randint` (with endpoint=False) and
`RandomState.random_integers` (with endpoint=True).
Return random integers from the "discrete uniform" distribution of the
specified dtype. If high is None (the default), then results are from
0 to low.
Parameters
----------
gen : {None, np.random.RandomState, np.random.Generator}
    Random number generator. If None, then the np.random.RandomState
    singleton is used.
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    high=None, in which case this parameter is 0 and this value is used
    for high).
high : int or array-like of ints
    If provided, one above the largest (signed) integer to be drawn from
    the distribution (see above for behavior if high=None). If array-like,
    must contain integer values.
size : array-like of ints, optional
    Output shape. If the given shape is, e.g., (m, n, k), then m * n * k
    samples are drawn. Default is None, in which case a single value is
    returned.
dtype : {str, dtype}, optional
    Desired dtype of the result. All dtypes are determined by their name,
    i.e., 'int64', 'int', etc, so byteorder is not available and a specific
    precision may have different C types depending on the platform.
    The default value is np.int_.
endpoint : bool, optional
    If True, sample from the interval [low, high] instead of the default
    [low, high) Defaults to False.
Returns
-------
out: int or ndarray of ints
    size-shaped array of random integers from the appropriate distribution,
    or a single such random int if size not provided.
Definition at line 437 of file _util.py.
Variable Documentation
DecimalNumber
scipy._lib._util.DecimalNumber = Union[float, np.floating, np.integer]
Definition at line 20 of file _util.py.
FullArgSpec
scipy._lib._util.FullArgSpec
Initial value:
=  namedtuple('FullArgSpec',
                         ['args', 'varargs', 'varkw', 'defaults',
                          'kwonlyargs', 'kwonlydefaults', 'annotations'])
Definition at line 291 of file _util.py.
GeneratorType
scipy._lib._util.GeneratorType
Initial value:
=  TypeVar("GeneratorType", bound=Union[np.random.Generator,
                                                         np.random.RandomState])
Definition at line 27 of file _util.py.
IntNumber
scipy._lib._util.IntNumber = Union[int, np.integer]
Definition at line 19 of file _util.py.
SeedType
scipy._lib._util.SeedType
Initial value:
=  Optional[Union[IntNumber, np.random.Generator,
                              np.random.RandomState]]
Definition at line 25 of file _util.py.