Code Cloning Analysis: matplotlib.ticker.MaxNLocator Class Reference
matplotlib.ticker.MaxNLocator Class Reference
Public Member Functions
__init__ (self, nbins=None, **kwargs)
set_params (self, **kwargs)
__call__ (self)
tick_values (self, vmin, vmax)
view_limits (self, dmin, dmax)
Public Member Functions inherited from matplotlib.ticker.Locator
__call__ (self)
raise_if_exceeds (self, locs)
nonsingular (self, v0, v1)
Public Member Functions inherited from matplotlib.ticker.TickHelper
set_axis (self, axis)
create_dummy_axis (self, **kwargs)
Static Public Attributes
default_params
Static Public Attributes inherited from matplotlib.ticker.Locator
int MAXTICKS = 1000
Static Public Attributes inherited from matplotlib.ticker.TickHelper
axis = None
Protected Member Functions
_raw_ticks (self, vmin, vmax)
Static Protected Member Functions
_validate_steps (steps)
_staircase (steps)
Protected Attributes
str _nbins = kwargs.pop('nbins')
_symmetric = kwargs.pop('symmetric')
_prune = prune
_min_n_ticks = max(1, kwargs.pop('min_n_ticks'))
_steps = np.array([1, 1.5, 2, 2.5, 3, 4, 5, 6, 8, 10])
_extended_steps = self._staircase(self._steps)
_integer = kwargs.pop('integer')
Detailed Description
Place evenly spaced ticks, with a cap on the total number of ticks.
Finds nice tick locations with no more than :math:`nbins + 1` ticks being within the
view limits. Locations beyond the limits are added to support autoscaling.
Definition at line 2042 of file ticker.py.
Constructor & Destructor Documentation
__init__()
matplotlib.ticker.MaxNLocator.__init__ (self, nbins = None, ** kwargs)
Parameters
----------
nbins : int or 'auto', default: 10
    Maximum number of intervals; one less than max number of
    ticks.  If the string 'auto', the number of bins will be
    automatically determined based on the length of the axis.
steps : array-like, optional
    Sequence of acceptable tick multiples, starting with 1 and
    ending with 10. For example, if ``steps=[1, 2, 4, 5, 10]``,
    ``20, 40, 60`` or ``0.4, 0.6, 0.8`` would be possible
    sets of ticks because they are multiples of 2.
    ``30, 60, 90`` would not be generated because 3 does not
    appear in this example list of steps.
integer : bool, default: False
    If True, ticks will take only integer values, provided at least
    *min_n_ticks* integers are found within the view limits.
symmetric : bool, default: False
    If True, autoscaling will result in a range symmetric about zero.
prune : {'lower', 'upper', 'both', None}, default: None
    Remove the 'lower' tick, the 'upper' tick, or ticks on 'both' sides
    *if they fall exactly on an axis' edge* (this typically occurs when
    :rc:`axes.autolimit_mode` is 'round_numbers').  Removing such ticks
    is mostly useful for stacked or ganged plots, where the upper tick
    of an Axes overlaps with the lower tick of the axes above it.
min_n_ticks : int, default: 2
    Relax *nbins* and *integer* constraints if necessary to obtain
    this minimum number of ticks.
Definition at line 2056 of file ticker.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__call__()
matplotlib.ticker.MaxNLocator.__call__ (self)
Definition at line 2228 of file ticker.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), and scipy.interpolate._fitpack2.SphereBivariateSpline.ev().
_raw_ticks()
matplotlib.ticker.MaxNLocator._raw_ticks (self, vmin, vmax) protected
Generate a list of tick locations including the range *vmin* to
*vmax*.  In some applications, one or both of the end locations
will not be needed, in which case they are trimmed off
elsewhere.
Definition at line 2159 of file ticker.py.
_staircase()
matplotlib.ticker.MaxNLocator._staircase (steps) static protected
Definition at line 2111 of file ticker.py.
_validate_steps()
matplotlib.ticker.MaxNLocator._validate_steps (steps) static protected
Definition at line 2096 of file ticker.py.
Referenced by sklearn.pipeline.Pipeline._fit().
set_params()
matplotlib.ticker.MaxNLocator.set_params (self, ** kwargs)
Set parameters for this locator.
Parameters
----------
nbins : int or 'auto', optional
    see `.MaxNLocator`
steps : array-like, optional
    see `.MaxNLocator`
integer : bool, optional
    see `.MaxNLocator`
symmetric : bool, optional
    see `.MaxNLocator`
prune : {'lower', 'upper', 'both', None}, optional
    see `.MaxNLocator`
min_n_ticks : int, optional
    see `.MaxNLocator`
Reimplemented from matplotlib.ticker.Locator.
Reimplemented in matplotlib.ticker.LogitLocator.
Definition at line 2116 of file ticker.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.theta().
tick_values()
matplotlib.ticker.MaxNLocator.tick_values (self, vmin, vmax)
Return the values of the located ticks given **vmin** and **vmax**.
.. note::
    To get tick locations with the vmin and vmax values defined
    automatically for the associated ``axis`` simply call
    the Locator instance::
        >>> print(type(loc))
        <type 'Locator'>
        >>> print(loc())
        [1, 2, 3, 4]
Reimplemented from matplotlib.ticker.Locator.
Reimplemented in matplotlib.ticker.LogitLocator.
Definition at line 2232 of file ticker.py.
view_limits()
matplotlib.ticker.MaxNLocator.view_limits (self, vmin, vmax)
Select a scale for the range from vmin to vmax.
Subclasses should override this method to change locator behaviour.
Reimplemented from matplotlib.ticker.Locator.
Definition at line 2249 of file ticker.py.
Member Data Documentation
_extended_steps
matplotlib.ticker.MaxNLocator._extended_steps = self._staircase(self._steps) protected
Definition at line 2153 of file ticker.py.
_integer
matplotlib.ticker.MaxNLocator._integer = kwargs.pop('integer') protected
Definition at line 2155 of file ticker.py.
_min_n_ticks
matplotlib.ticker.MaxNLocator._min_n_ticks = max(1, kwargs.pop('min_n_ticks')) protected
Definition at line 2146 of file ticker.py.
_nbins
str matplotlib.ticker.MaxNLocator._nbins = kwargs.pop('nbins') protected
Definition at line 2136 of file ticker.py.
_prune
matplotlib.ticker.MaxNLocator._prune = prune protected
Definition at line 2144 of file ticker.py.
_steps
matplotlib.ticker.MaxNLocator._steps = np.array([1, 1.5, 2, 2.5, 3, 4, 5, 6, 8, 10]) protected
Definition at line 2150 of file ticker.py.
_symmetric
matplotlib.ticker.MaxNLocator._symmetric = kwargs.pop('symmetric') protected
Definition at line 2140 of file ticker.py.
default_params
matplotlib.ticker.MaxNLocator.default_params static
Initial value:
=  dict(nbins=10,
                          steps=None,
                          integer=False,
                          symmetric=False,
                          prune=None,
                          min_n_ticks=2)
Definition at line 2049 of file ticker.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/ticker.py