Code Cloning Analysis: fontTools.varLib.varStore Namespace Reference
fontTools.varLib.varStore Namespace Reference
Classes
class _Encoding
class _EncodingDict
class OnlineVarStoreBuilder
class VarStoreInstancer
Functions
_getLocationKey (loc)
VarData_addItem (self, deltas, *, round=round)
VarRegion_get_support (self, fvar_axes)
VarStore___bool__ (self)
VarStore_subset_varidxes (self, varIdxes, optimize=True, retainFirstMap=False, advIdxes=set(), *, VarData="VarData")
VarStore_prune_regions (self, *, VarData="VarData", VarRegionList="VarRegionList")
_visit (self, func)
_Device_recordVarIdx (self, s)
Object_collect_device_varidxes (self, varidxes)
_Device_mapVarIdx (self, mapping, done)
Object_remap_device_varidxes (self, varidxes_map)
VarStore_optimize (self, use_NO_VARIATION_INDEX=True, quantization=1)
main (args=None)
Variables
NO_VARIATION_INDEX = ot.NO_VARIATION_INDEX
addItem
get_support
__bool__
subset_varidxes
prune_regions
collect_device_varidxes
remap_device_varidxes
optimize
ItemCount = len(self.Item)
VarRegionAxis
list VarData
int DeltaFormat = 0x8000:
int EndSize
int StartSize = varIdx >> 16
VarDataCount = len(self.VarData)
Function Documentation
_Device_mapVarIdx()
fontTools.varLib.varStore._Device_mapVarIdx (self, mapping, done) protected
Map VarIdx in this Device table (if any) through mapping.
Definition at line 381 of file varStore.py.
References _visit().
_Device_recordVarIdx()
fontTools.varLib.varStore._Device_recordVarIdx (self, s) protected
Add VarIdx in this Device table (if any) to the set s.
Definition at line 366 of file varStore.py.
References _visit().
_getLocationKey()
fontTools.varLib.varStore._getLocationKey (loc) protected
Definition at line 20 of file varStore.py.
_visit()
fontTools.varLib.varStore._visit (self, func) protected
Recurse down from self, if type of an object is ot.Device,
call func() on it.  Works on otData-style classes.
Definition at line 344 of file varStore.py.
References _visit().
Referenced by _Device_mapVarIdx(), _Device_recordVarIdx(), and _visit().
main()
fontTools.varLib.varStore.main (args = None)
Optimize a font's GDEF variation store
Definition at line 688 of file varStore.py.
Object_collect_device_varidxes()
fontTools.varLib.varStore.Object_collect_device_varidxes (self, varidxes)
Definition at line 372 of file varStore.py.
Object_remap_device_varidxes()
fontTools.varLib.varStore.Object_remap_device_varidxes (self, varidxes_map)
Definition at line 392 of file varStore.py.
VarData_addItem()
fontTools.varLib.varStore.VarData_addItem (self, deltas, * , round = round)
Definition at line 159 of file varStore.py.
VarRegion_get_support()
fontTools.varLib.varStore.VarRegion_get_support (self, fvar_axes)
Definition at line 176 of file varStore.py.
VarStore___bool__()
fontTools.varLib.varStore.VarStore___bool__ (self)
Definition at line 187 of file varStore.py.
VarStore_optimize()
fontTools.varLib.varStore.VarStore_optimize (self, use_NO_VARIATION_INDEX = True, quantization = 1)
Optimize storage. Returns mapping from old VarIdxes to new ones.
Definition at line 492 of file varStore.py.
VarStore_prune_regions()
fontTools.varLib.varStore.VarStore_prune_regions (self, * , VarData = "VarData", VarRegionList = "VarRegionList")
Remove unused VarRegions.
Definition at line 316 of file varStore.py.
VarStore_subset_varidxes()
fontTools.varLib.varStore.VarStore_subset_varidxes (self, varIdxes, optimize = True, retainFirstMap = False, advIdxes = set(), * , VarData = "VarData")
Definition at line 248 of file varStore.py.
Variable Documentation
__bool__
fontTools.varLib.varStore.__bool__ private
Definition at line 191 of file varStore.py.
addItem
fontTools.varLib.varStore.addItem
Definition at line 173 of file varStore.py.
collect_device_varidxes
fontTools.varLib.varStore.collect_device_varidxes
Definition at line 377 of file varStore.py.
DeltaFormat
int fontTools.varLib.varStore.DeltaFormat = 0x8000:
Definition at line 368 of file varStore.py.
EndSize
int fontTools.varLib.varStore.EndSize
Definition at line 369 of file varStore.py.
get_support
fontTools.varLib.varStore.get_support
Definition at line 184 of file varStore.py.
ItemCount
fontTools.varLib.varStore.ItemCount = len(self.Item)
Definition at line 170 of file varStore.py.
NO_VARIATION_INDEX
fontTools.varLib.varStore.NO_VARIATION_INDEX = ot.NO_VARIATION_INDEX
Definition at line 16 of file varStore.py.
optimize
fontTools.varLib.varStore.optimize
Definition at line 685 of file varStore.py.
prune_regions
fontTools.varLib.varStore.prune_regions
Definition at line 341 of file varStore.py.
remap_device_varidxes
fontTools.varLib.varStore.remap_device_varidxes
Definition at line 397 of file varStore.py.
StartSize
int fontTools.varLib.varStore.StartSize = varIdx >> 16
Definition at line 388 of file varStore.py.
subset_varidxes
fontTools.varLib.varStore.subset_varidxes
Definition at line 313 of file varStore.py.
VarData
fontTools.varLib.varStore.VarData
Definition at line 188 of file varStore.py.
VarDataCount
fontTools.varLib.varStore.VarDataCount = len(self.VarData)
Definition at line 674 of file varStore.py.
VarRegionAxis
fontTools.varLib.varStore.VarRegionAxis
Definition at line 179 of file varStore.py.