Code Cloning Analysis: pip._vendor.tenacity.wait.wait_base Class Reference
pip._vendor.tenacity.wait.wait_base Class Reference
Public Member Functions
float __call__ (self, "RetryCallState" retry_state)
"wait_combine" __add__ (self, "wait_base" other)
typing.Union["wait_combine", "wait_base"] __radd__ (self, "wait_base" other)
Detailed Description
Abstract base class for wait strategies.
Definition at line 27 of file wait.py.
Member Function Documentation
__add__()
"wait_combine" pip._vendor.tenacity.wait.wait_base.__add__ (self, "wait_base" other)
Definition at line 34 of file wait.py.
Referenced by scipy.signal._ltisys.StateSpace.__add__(), scipy.sparse.linalg._interface.LinearOperator._rdot(), and scipy.sparse._base._spbase.power().
__call__()
float pip._vendor.tenacity.wait.wait_base.__call__ (self, "RetryCallState" retry_state)
Definition at line 31 of file wait.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), and scipy.interpolate._fitpack2.SphereBivariateSpline.ev().
__radd__()
typing.Union["wait_combine", "wait_base"] pip._vendor.tenacity.wait.wait_base.__radd__ (self, "wait_base" other)
Definition at line 37 of file wait.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pip/_vendor/tenacity/wait.py