Code Cloning Analysis: pandas.io.stata.StataWriterUTF8 Class Reference
pandas.io.stata.StataWriterUTF8 Class Reference
Public Member Functions
None __init__ (self, FilePath|WriteBuffer[bytes] fname, DataFrame data, dict[Hashable, str]|None convert_dates=None, bool write_index=True, str|None byteorder=None, datetime|None time_stamp=None, str|None data_label=None, dict[Hashable, str]|None variable_labels=None, Sequence[Hashable]|None convert_strl=None, int|None version=None, CompressionOptions compression="infer", StorageOptions|None storage_options=None, *, dict[Hashable, dict[float, str]]|None value_labels=None)
Public Member Functions inherited from pandas.io.stata.StataWriter117
None __init__ (self, FilePath|WriteBuffer[bytes] fname, DataFrame data, dict[Hashable, str]|None convert_dates=None, bool write_index=True, str|None byteorder=None, datetime|None time_stamp=None, str|None data_label=None, dict[Hashable, str]|None variable_labels=None, Sequence[Hashable]|None convert_strl=None, CompressionOptions compression="infer", StorageOptions|None storage_options=None, *, dict[Hashable, dict[float, str]]|None value_labels=None)
Public Member Functions inherited from pandas.io.stata.StataWriter
None __init__ (self, FilePath|WriteBuffer[bytes] fname, DataFrame data, dict[Hashable, str]|None convert_dates=None, bool write_index=True, str|None byteorder=None, datetime|None time_stamp=None, str|None data_label=None, dict[Hashable, str]|None variable_labels=None, CompressionOptions compression="infer", StorageOptions|None storage_options=None, *, dict[Hashable, dict[float, str]]|None value_labels=None)
None write_file (self)
Public Member Functions inherited from pandas.io.stata.StataParser
None __init__ (self)
Protected Member Functions
str _validate_variable_name (self, str name)
Protected Member Functions inherited from pandas.io.stata.StataWriter117
None _update_map (self, str tag)
None _write_header (self, str|None data_label=None, datetime|None time_stamp=None)
None _write_map (self)
None _write_variable_types (self)
None _write_varnames (self)
None _write_sortlist (self)
None _write_formats (self)
None _write_value_label_names (self)
None _write_variable_labels (self)
None _write_characteristics (self)
None _write_data (self, records)
None _write_strls (self)
None _write_expansion_fields (self)
None _write_value_labels (self)
None _write_file_close_tag (self)
None _update_strl_names (self)
DataFrame _convert_strls (self, DataFrame data)
None _set_formats_and_types (self, Series dtypes)
Protected Member Functions inherited from pandas.io.stata.StataWriter
None _write (self, str to_write)
None _write_bytes (self, bytes value)
list[StataNonCatValueLabel] _prepare_non_cat_value_labels (self, DataFrame data)
DataFrame _prepare_categoricals (self, DataFrame data)
DataFrame _replace_nans (self, DataFrame data)
DataFrame _check_column_names (self, DataFrame data)
None _prepare_pandas (self, DataFrame data)
None _encode_strings (self)
None _close (self)
np.rec.recarray _prepare_data (self)
bytes _null_terminate_bytes (self, str s)
Additional Inherited Members
Public Attributes inherited from pandas.io.stata.StataWriter
data = data
storage_options = storage_options
dict type_converters = {253: np.int32, 252: np.int16, 251: np.int8}
list fmtlist = []
list typlist = []
nobs = self._prepare_categoricals(data)
nvar = data.shape
varlist = data.columns.tolist()
handles = self.storage_options,
Public Attributes inherited from pandas.io.stata.StataParser
DTYPE_MAP
dict DTYPE_MAP_XML
TYPE_MAP = list(tuple(range(251)) + tuple("bhlfd"))
dict TYPE_MAP_XML
dict VALID_RANGE
dict OLD_TYPE_MAPPING
dict MISSING_VALUES
dict NUMPY_TYPE_MAP
dict RESERVED_WORDS
Static Protected Member Functions inherited from pandas.io.stata.StataWriter117
bytes _tag (str|bytes val, str tag)
Static Protected Member Functions inherited from pandas.io.stata.StataWriter
str _null_terminate_str (str s)
Protected Attributes inherited from pandas.io.stata.StataWriter117
list _convert_strl = []
dict _map = {}
str _strl_blob = b""
Protected Attributes inherited from pandas.io.stata.StataWriter
dict _convert_dates = {} if convert_dates is None else convert_dates
_write_index = write_index
_time_stamp = time_stamp
_data_label = data_label
_variable_labels = variable_labels
_non_cat_value_labels = value_labels
list _value_labels = []
_has_value_labels = np.array([], dtype=bool)
_compression = compression
IO[bytes]|None _output_file = None
dict _converted_names = {}
_byteorder = _set_endianness(byteorder)
_fname = fname
Static Protected Attributes inherited from pandas.io.stata.StataWriter117
int _dta_version = 117
Static Protected Attributes inherited from pandas.io.stata.StataWriter
int _max_string_length = 244
Literal _encoding = "latin-1"
Detailed Description
Stata binary dta file writing in Stata 15 (118) and 16 (119) formats
DTA 118 and 119 format files support unicode string data (both fixed
and strL) format. Unicode is also supported in value labels, variable
labels and the dataset label. Format 119 is automatically used if the
file contains more than 32,767 variables.
Parameters
----------
fname : path (string), buffer or path object
    string, path object (pathlib.Path or py._path.local.LocalPath) or
    object implementing a binary write() functions. If using a buffer
    then the buffer will not be automatically closed after the file
    is written.
data : DataFrame
    Input to save
convert_dates : dict, default None
    Dictionary mapping columns containing datetime types to stata internal
    format to use when writing the dates. Options are 'tc', 'td', 'tm',
    'tw', 'th', 'tq', 'ty'. Column can be either an integer or a name.
    Datetime columns that do not have a conversion type specified will be
    converted to 'tc'. Raises NotImplementedError if a datetime column has
    timezone information
write_index : bool, default True
    Write the index to Stata dataset.
byteorder : str, default None
    Can be ">", "<", "little", or "big". default is `sys.byteorder`
time_stamp : datetime, default None
    A datetime to use as file creation date.  Default is the current time
data_label : str, default None
    A label for the data set.  Must be 80 characters or smaller.
variable_labels : dict, default None
    Dictionary containing columns as keys and variable labels as values.
    Each label must be 80 characters or smaller.
convert_strl : list, default None
    List of columns names to convert to Stata StrL format.  Columns with
    more than 2045 characters are automatically written as StrL.
    Smaller columns can be converted by including the column name.  Using
    StrLs can reduce output file size when strings are longer than 8
    characters, and either frequently repeated or sparse.
version : int, default None
    The dta version to use. By default, uses the size of data to determine
    the version. 118 is used if data.shape[1] <= 32767, and 119 is used
    for storing larger DataFrames.
{compression_options}
    .. versionchanged:: 1.4.0 Zstandard support.
value_labels : dict of dicts
    Dictionary containing columns as keys and dictionaries of column value
    to labels as values. The combined length of all labels for a single
    variable must be 32,000 characters or smaller.
    .. versionadded:: 1.4.0
Returns
-------
StataWriterUTF8
    The instance has a write_file method, which will write the file to the
    given `fname`.
Raises
------
NotImplementedError
    * If datetimes contain timezone information
ValueError
    * Columns listed in convert_dates are neither datetime64[ns]
      or datetime
    * Column dtype is not representable in Stata
    * Column listed in convert_dates is not in DataFrame
    * Categorical label contains more than 32,000 characters
Examples
--------
Using Unicode data and column names
>>> from pandas.io.stata import StataWriterUTF8
>>> data = pd.DataFrame([[1.0, 1, '']], columns=['a', '', ''])
>>> writer = StataWriterUTF8('./data_file.dta', data)
>>> writer.write_file()
Directly write a zip file
>>> compression = {"method": "zip", "archive_name": "data_file.dta"}
>>> writer = StataWriterUTF8('./data_file.zip', data, compression=compression)
>>> writer.write_file()
Or with long strings stored in strl format
>>> data = pd.DataFrame([[' relatively long tring'], [''], ['']],
...                     columns=['strls'])
>>> writer = StataWriterUTF8('./data_file_with_long_strings.dta', data,
...                          convert_strl=['strls'])
>>> writer.write_file()
Definition at line 3590 of file stata.py.
Constructor & Destructor Documentation
__init__()
None pandas.io.stata.StataWriterUTF8.__init__ (self, FilePath | WriteBuffer[bytes] fname, DataFrame data, dict[Hashable, str] | None convert_dates = None, bool write_index = True, str | None byteorder = None, datetime | None time_stamp = None, str | None data_label = None, dict[Hashable, str] | None variable_labels = None, Sequence[Hashable] | None convert_strl = None, int | None version = None, CompressionOptions compression = "infer", StorageOptions | None storage_options = None, * , dict[Hashable, dict[float, str]] | None value_labels = None)
Definition at line 3689 of file stata.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_validate_variable_name()
str pandas.io.stata.StataWriterUTF8._validate_variable_name (self, str name) protected
Validate variable names for Stata export.
Parameters
----------
name : str
    Variable name
Returns
-------
str
    The validated name with invalid characters replaced with
    underscores.
Notes
-----
Stata 118+ support most unicode characters. The only limitation is in
the ascii range where the characters supported are a-z, A-Z, 0-9 and _.
Reimplemented from pandas.io.stata.StataWriter.
Definition at line 3733 of file stata.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/io/stata.py