Code Cloning Analysis: scipy.fft._pocketfft.tests.test_basic._TestIFFTBase Class Reference
scipy.fft._pocketfft.tests.test_basic._TestIFFTBase Class Reference
Public Member Functions
setup_method (self)
test_definition (self)
test_definition_real (self)
test_djbfft (self)
test_random_complex (self)
test_random_real (self)
test_size_accuracy (self)
test_invalid_sizes (self)
Public Attributes
cdt = np.array([1,2,3,4,5], dtype=self.rdt)
rtol = fft(ifft(x))
rdt
Detailed Description
Definition at line 195 of file test_basic.py.
Member Function Documentation
setup_method()
scipy.fft._pocketfft.tests.test_basic._TestIFFTBase.setup_method (self)
Definition at line 196 of file test_basic.py.
test_definition()
scipy.fft._pocketfft.tests.test_basic._TestIFFTBase.test_definition (self)
Definition at line 199 of file test_basic.py.
test_definition_real()
scipy.fft._pocketfft.tests.test_basic._TestIFFTBase.test_definition_real (self)
Definition at line 209 of file test_basic.py.
test_djbfft()
scipy.fft._pocketfft.tests.test_basic._TestIFFTBase.test_djbfft (self)
Definition at line 220 of file test_basic.py.
test_invalid_sizes()
scipy.fft._pocketfft.tests.test_basic._TestIFFTBase.test_invalid_sizes (self)
Definition at line 267 of file test_basic.py.
test_random_complex()
scipy.fft._pocketfft.tests.test_basic._TestIFFTBase.test_random_complex (self)
Definition at line 230 of file test_basic.py.
test_random_real()
scipy.fft._pocketfft.tests.test_basic._TestIFFTBase.test_random_real (self)
Definition at line 241 of file test_basic.py.
test_size_accuracy()
scipy.fft._pocketfft.tests.test_basic._TestIFFTBase.test_size_accuracy (self)
Definition at line 251 of file test_basic.py.
Member Data Documentation
cdt
scipy.fft._pocketfft.tests.test_basic._TestIFFTBase.cdt = np.array([1,2,3,4,5], dtype=self.rdt)
Definition at line 203 of file test_basic.py.
rdt
scipy.fft._pocketfft.tests.test_basic._TestIFFTBase.rdt
Definition at line 257 of file test_basic.py.
rtol
scipy.fft._pocketfft.tests.test_basic._TestIFFTBase.rtol = fft(ifft(x))
Definition at line 257 of file test_basic.py.
Referenced by scipy.optimize._zeros_py.TOMS748Solver.get_status(), scipy.optimize._zeros_py.TOMS748Solver.iterate(), scipy.integrate._ode.dop853.reset(), scipy.integrate._ode.dopri5.reset(), scipy.integrate._ode.lsoda.reset(), scipy.integrate._ode.vode.reset(), scipy.integrate._ode.zvode.reset(), scipy.optimize.tests.test_zeros.TestScalarRootFinders.run_tests(), sklearn.neighbors._kde.KernelDensity.score_samples(), scipy.stats.tests.test_resampling.TestPermutationTest.test_against_spearmanr_in_R(), and scipy.stats.tests.test_resampling.TestPermutationTest.test_with_ties().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/fft/_pocketfft/tests/test_basic.py