Code Cloning Analysis: scipy.optimize._remove_redundancy Namespace Reference
scipy.optimize._remove_redundancy Namespace Reference
Functions
_row_count (A)
_get_densest (A, eligibleRows)
_remove_zero_rows (A, b)
bg_update_dense (plu, perm_r, v, j)
_remove_redundancy_pivot_dense (A, rhs, true_rank=None)
_remove_redundancy_pivot_sparse (A, rhs)
_remove_redundancy_svd (A, b)
_remove_redundancy_id (A, rhs, rank=None, randomized=True)
Detailed Description
Routines for removing redundant (linearly dependent) equations from linear
programming equality constraints.
Function Documentation
_get_densest()
scipy.optimize._remove_redundancy._get_densest (A, eligibleRows) protected
Returns the index of the densest row of A. Ignores rows that are not
eligible for consideration.
Parameters
----------
A : 2-D array
    An array representing a matrix
eligibleRows : 1-D logical array
    Values indicate whether the corresponding row of A is eligible
    to be considered
Returns
-------
i_densest : int
    Index of the densest row in A eligible for consideration
Definition at line 35 of file _remove_redundancy.py.
References _row_count().
Referenced by _remove_redundancy_svd().
_remove_redundancy_id()
scipy.optimize._remove_redundancy._remove_redundancy_id (A, rhs, rank = None, randomized = True) protected
Eliminates redundant equations from a system of equations.
Eliminates redundant equations from system of equations defined by Ax = b
and identifies infeasibilities.
Parameters
----------
A : 2-D array
    An array representing the left-hand side of a system of equations
rhs : 1-D array
    An array representing the right-hand side of a system of equations
rank : int, optional
    The rank of A
randomized: bool, optional
    True for randomized interpolative decomposition
Returns
-------
A : 2-D array
    An array representing the left-hand side of a system of equations
rhs : 1-D array
    An array representing the right-hand side of a system of equations
status: int
    An integer indicating the status of the system
    0: No infeasibility identified
    2: Trivially infeasible
message : str
    A string descriptor of the exit status of the optimization.
Definition at line 454 of file _remove_redundancy.py.
References _remove_zero_rows().
_remove_redundancy_pivot_dense()
scipy.optimize._remove_redundancy._remove_redundancy_pivot_dense (A, rhs, true_rank = None) protected
Eliminates redundant equations from system of equations defined by Ax = b
and identifies infeasibilities.
Parameters
----------
A : 2-D sparse matrix
    An matrix representing the left-hand side of a system of equations
rhs : 1-D array
    An array representing the right-hand side of a system of equations
Returns
-------
A : 2-D sparse matrix
    A matrix representing the left-hand side of a system of equations
rhs : 1-D array
    An array representing the right-hand side of a system of equations
status: int
    An integer indicating the status of the system
    0: No infeasibility identified
    2: Trivially infeasible
message : str
    A string descriptor of the exit status of the optimization.
References
----------
.. [2] Andersen, Erling D. "Finding all linearly dependent rows in
       large-scale linear programming." Optimization Methods and Software
       6.3 (1995): 219-227.
Definition at line 108 of file _remove_redundancy.py.
References _remove_zero_rows().
_remove_redundancy_pivot_sparse()
scipy.optimize._remove_redundancy._remove_redundancy_pivot_sparse (A, rhs) protected
Eliminates redundant equations from system of equations defined by Ax = b
and identifies infeasibilities.
Parameters
----------
A : 2-D sparse matrix
    An matrix representing the left-hand side of a system of equations
rhs : 1-D array
    An array representing the right-hand side of a system of equations
Returns
-------
A : 2-D sparse matrix
    A matrix representing the left-hand side of a system of equations
rhs : 1-D array
    An array representing the right-hand side of a system of equations
status: int
    An integer indicating the status of the system
    0: No infeasibility identified
    2: Trivially infeasible
message : str
    A string descriptor of the exit status of the optimization.
References
----------
.. [2] Andersen, Erling D. "Finding all linearly dependent rows in
       large-scale linear programming." Optimization Methods and Software
       6.3 (1995): 219-227.
Definition at line 235 of file _remove_redundancy.py.
References _remove_zero_rows().
_remove_redundancy_svd()
scipy.optimize._remove_redundancy._remove_redundancy_svd (A, b) protected
Eliminates redundant equations from system of equations defined by Ax = b
and identifies infeasibilities.
Parameters
----------
A : 2-D array
    An array representing the left-hand side of a system of equations
b : 1-D array
    An array representing the right-hand side of a system of equations
Returns
-------
A : 2-D array
    An array representing the left-hand side of a system of equations
b : 1-D array
    An array representing the right-hand side of a system of equations
status: int
    An integer indicating the status of the system
    0: No infeasibility identified
    2: Trivially infeasible
message : str
    A string descriptor of the exit status of the optimization.
References
----------
.. [2] Andersen, Erling D. "Finding all linearly dependent rows in
       large-scale linear programming." Optimization Methods and Software
       6.3 (1995): 219-227.
Definition at line 362 of file _remove_redundancy.py.
References _get_densest(), and _remove_zero_rows().
_remove_zero_rows()
scipy.optimize._remove_redundancy._remove_zero_rows (A, b) protected
Eliminates trivial equations from system of equations defined by Ax = b
and identifies trivial infeasibilities
Parameters
----------
A : 2-D array
    An array representing the left-hand side of a system of equations
b : 1-D array
    An array representing the right-hand side of a system of equations
Returns
-------
A : 2-D array
    An array representing the left-hand side of a system of equations
b : 1-D array
    An array representing the right-hand side of a system of equations
status: int
    An integer indicating the status of the removal operation
    0: No infeasibility identified
    2: Trivially infeasible
message : str
    A string descriptor of the exit status of the optimization.
Definition at line 58 of file _remove_redundancy.py.
References _row_count().
Referenced by _remove_redundancy_id(), _remove_redundancy_pivot_dense(), _remove_redundancy_pivot_sparse(), and _remove_redundancy_svd().
_row_count()
scipy.optimize._remove_redundancy._row_count (A) protected
Counts the number of nonzeros in each row of input array A.
Nonzeros are defined as any element with absolute value greater than
tol = 1e-13. This value should probably be an input to the function.
Parameters
----------
A : 2-D array
    An array representing a matrix
Returns
-------
rowcount : 1-D array
    Number of nonzeros in each row of A
Definition at line 14 of file _remove_redundancy.py.
Referenced by _get_densest(), and _remove_zero_rows().
bg_update_dense()
scipy.optimize._remove_redundancy.bg_update_dense (plu, perm_r, v, j)
Definition at line 96 of file _remove_redundancy.py.