Code Cloning Analysis: axisartist.axis_artist.AttributeCopier Class Reference
axisartist.axis_artist.AttributeCopier Class Reference
Public Member Functions
get_ref_artist (self)
get_attribute_from_ref_artist (self, attr_name)
Detailed Description
Definition at line 93 of file axis_artist.py.
Member Function Documentation
get_attribute_from_ref_artist()
axisartist.axis_artist.AttributeCopier.get_attribute_from_ref_artist (self, attr_name)
Definition at line 101 of file axis_artist.py.
Referenced by axisartist.axis_artist.Ticks.get_color(), axisartist.axis_artist.Ticks.get_markeredgecolor(), axisartist.axis_artist.Ticks.get_markeredgewidth(), and axisartist.axis_artist.AxisLabel.set_axis_direction().
get_ref_artist()
axisartist.axis_artist.AttributeCopier.get_ref_artist (self)
Return the underlying artist that actually defines some properties
(e.g., color) of this artist.
Reimplemented in axisartist.axis_artist.AxisLabel, axisartist.axis_artist.TickLabels, and axisartist.axis_artist.Ticks.
Definition at line 94 of file axis_artist.py.
References get_ref_artist().
Referenced by get_ref_artist().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/mpl_toolkits/axisartist/axis_artist.py