Code Cloning Analysis: scipy.linalg.blas Namespace Reference
scipy.linalg.blas Namespace Reference
Functions
find_best_blas_type (arrays=(), dtype=None)
_get_funcs (names, arrays, dtype, lib_name, fmodule, cmodule, fmodule_name, cmodule_name, alias, ilp64=False)
_memoize_get_funcs (func)
get_blas_funcs (names, arrays=(), dtype=None, ilp64=False)
Variables
list __all__ = ['get_blas_funcs', 'find_best_blas_type']
_cblas = None
bool HAS_ILP64 = True
_fblas_64 = None
empty_module = None
dict _type_score = {x: 1 for x in '?bBhHef'}
dict _type_conv
dict _blas_alias
Detailed Description
Low-level BLAS functions (:mod:`scipy.linalg.blas`)
===================================================
This module contains low-level functions from the BLAS library.
.. versionadded:: 0.12.0
.. note::
   The common ``overwrite_<>`` option in many routines, allows the
   input arrays to be overwritten to avoid extra memory allocation.
   However this requires the array to satisfy two conditions
   which are memory order and the data type to match exactly the
   order and the type expected by the routine.
   As an example, if you pass a double precision float array to any
   ``S....`` routine which expects single precision arguments, f2py
   will create an intermediate array to match the argument types and
   overwriting will be performed on that intermediate array.
   Similarly, if a C-contiguous array is passed, f2py will pass a
   FORTRAN-contiguous array internally. Please make sure that these
   details are satisfied. More information can be found in the f2py
   documentation.
.. warning::
   These functions do little to no error checking.
   It is possible to cause crashes by mis-using them,
   so prefer using the higher-level routines in `scipy.linalg`.
Finding functions
-----------------
.. autosummary::
   :toctree: generated/
   get_blas_funcs
   find_best_blas_type
BLAS Level 1 functions
----------------------
.. autosummary::
   :toctree: generated/
   caxpy
   ccopy
   cdotc
   cdotu
   crotg
   cscal
   csrot
   csscal
   cswap
   dasum
   daxpy
   dcopy
   ddot
   dnrm2
   drot
   drotg
   drotm
   drotmg
   dscal
   dswap
   dzasum
   dznrm2
   icamax
   idamax
   isamax
   izamax
   sasum
   saxpy
   scasum
   scnrm2
   scopy
   sdot
   snrm2
   srot
   srotg
   srotm
   srotmg
   sscal
   sswap
   zaxpy
   zcopy
   zdotc
   zdotu
   zdrot
   zdscal
   zrotg
   zscal
   zswap
BLAS Level 2 functions
----------------------
.. autosummary::
   :toctree: generated/
   sgbmv
   sgemv
   sger
   ssbmv
   sspr
   sspr2
   ssymv
   ssyr
   ssyr2
   stbmv
   stpsv
   strmv
   strsv
   dgbmv
   dgemv
   dger
   dsbmv
   dspr
   dspr2
   dsymv
   dsyr
   dsyr2
   dtbmv
   dtpsv
   dtrmv
   dtrsv
   cgbmv
   cgemv
   cgerc
   cgeru
   chbmv
   chemv
   cher
   cher2
   chpmv
   chpr
   chpr2
   ctbmv
   ctbsv
   ctpmv
   ctpsv
   ctrmv
   ctrsv
   csyr
   zgbmv
   zgemv
   zgerc
   zgeru
   zhbmv
   zhemv
   zher
   zher2
   zhpmv
   zhpr
   zhpr2
   ztbmv
   ztbsv
   ztpmv
   ztrmv
   ztrsv
   zsyr
BLAS Level 3 functions
----------------------
.. autosummary::
   :toctree: generated/
   sgemm
   ssymm
   ssyr2k
   ssyrk
   strmm
   strsm
   dgemm
   dsymm
   dsyr2k
   dsyrk
   dtrmm
   dtrsm
   cgemm
   chemm
   cher2k
   cherk
   csymm
   csyr2k
   csyrk
   ctrmm
   ctrsm
   zgemm
   zhemm
   zher2k
   zherk
   zsymm
   zsyr2k
   zsyrk
   ztrmm
   ztrsm
Function Documentation
_get_funcs()
scipy.linalg.blas._get_funcs (names, arrays, dtype, lib_name, fmodule, cmodule, fmodule_name, cmodule_name, alias, ilp64 = False) protected
Return available BLAS/LAPACK functions.
Used also in lapack.py. See get_blas_funcs for docstring.
Definition at line 326 of file blas.py.
References find_best_blas_type().
Referenced by get_blas_funcs(), and scipy.linalg.lapack.get_lapack_funcs().
_memoize_get_funcs()
scipy.linalg.blas._memoize_get_funcs (func) protected
Memoized fast path for _get_funcs instances
Definition at line 377 of file blas.py.
find_best_blas_type()
scipy.linalg.blas.find_best_blas_type (arrays = (), dtype = None)
Find best-matching BLAS/LAPACK type.
Arrays are used to determine the optimal prefix of BLAS routines.
Parameters
----------
arrays : sequence of ndarrays, optional
    Arrays can be given to determine optimal prefix of BLAS
    routines. If not given, double-precision routines will be
    used, otherwise the most generic type in arrays will be used.
dtype : str or dtype, optional
    Data-type specifier. Not used if `arrays` is non-empty.
Returns
-------
prefix : str
    BLAS/LAPACK prefix character.
dtype : dtype
    Inferred Numpy data type.
prefer_fortran : bool
    Whether to prefer Fortran order routines over C order.
Examples
--------
>>> import numpy as np
>>> import scipy.linalg.blas as bla
>>> rng = np.random.default_rng()
>>> a = rng.random((10,15))
>>> b = np.asfortranarray(a)  # Change the memory layout order
>>> bla.find_best_blas_type((a,))
('d', dtype('float64'), False)
>>> bla.find_best_blas_type((a*1j,))
('z', dtype('complex128'), False)
>>> bla.find_best_blas_type((b,))
('d', dtype('float64'), True)
Definition at line 259 of file blas.py.
Referenced by _get_funcs().
get_blas_funcs()
scipy.linalg.blas.get_blas_funcs (names, arrays = (), dtype = None, ilp64 = False)
Return available BLAS function objects from names.
Arrays are used to determine the optimal prefix of BLAS routines.
Parameters
----------
names : str or sequence of str
    Name(s) of BLAS functions without type prefix.
arrays : sequence of ndarrays, optional
    Arrays can be given to determine optimal prefix of BLAS
    routines. If not given, double-precision routines will be
    used, otherwise the most generic type in arrays will be used.
dtype : str or dtype, optional
    Data-type specifier. Not used if `arrays` is non-empty.
ilp64 : {True, False, 'preferred'}, optional
    Whether to return ILP64 routine variant.
    Choosing 'preferred' returns ILP64 routine if available,
    and otherwise the 32-bit routine. Default: False
Returns
-------
funcs : list
    List containing the found function(s).
Notes
-----
This routine automatically chooses between Fortran/C
interfaces. Fortran code is used whenever possible for arrays with
column major order. In all other cases, C code is preferred.
In BLAS, the naming convention is that all functions start with a
type prefix, which depends on the type of the principal
matrix. These can be one of {'s', 'd', 'c', 'z'} for the NumPy
types {float32, float64, complex64, complex128} respectively.
The code and the dtype are stored in attributes `typecode` and `dtype`
of the returned functions.
Examples
--------
>>> import numpy as np
>>> import scipy.linalg as LA
>>> rng = np.random.default_rng()
>>> a = rng.random((3,2))
>>> x_gemv = LA.get_blas_funcs('gemv', (a,))
>>> x_gemv.typecode
'd'
>>> x_gemv = LA.get_blas_funcs('gemv',(a*1j,))
>>> x_gemv.typecode
'z'
Definition at line 412 of file blas.py.
References _get_funcs().
Referenced by scipy.linalg.tests.test_lapack.TestTbtrs.test_invalid_matrix_shapes().
Variable Documentation
__all__
list scipy.linalg.blas.__all__ = ['get_blas_funcs', 'find_best_blas_type'] private
Definition at line 208 of file blas.py.
_blas_alias
dict scipy.linalg.blas._blas_alias protected
Initial value:
=  {'cnrm2': 'scnrm2', 'znrm2': 'dznrm2',
               'cdot': 'cdotc', 'zdot': 'zdotc',
               'cger': 'cgerc', 'zger': 'zgerc',
               'sdotc': 'sdot', 'sdotu': 'sdot',
               'ddotc': 'ddot', 'ddotu': 'ddot'}
Definition at line 252 of file blas.py.
_cblas
scipy.linalg.blas._cblas = None protected
Definition at line 217 of file blas.py.
_fblas_64
scipy.linalg.blas._fblas_64 = None protected
Definition at line 224 of file blas.py.
_type_conv
dict scipy.linalg.blas._type_conv protected
Initial value:
=  {1: ('s', _np.dtype('float32')),
              2: ('d', _np.dtype('float64')),
              3: ('c', _np.dtype('complex64')),
              4: ('z', _np.dtype('complex128'))}
Definition at line 246 of file blas.py.
_type_score
dict scipy.linalg.blas._type_score = {x: 1 for x in '?bBhHef'} protected
Definition at line 238 of file blas.py.
empty_module
scipy.linalg.blas.empty_module = None
Definition at line 227 of file blas.py.
HAS_ILP64
bool scipy.linalg.blas.HAS_ILP64 = True
Definition at line 221 of file blas.py.