Code Cloning Analysis: joblib._dask.Batch Class Reference
joblib._dask.Batch Class Reference
Public Member Functions
__init__ (self, tasks)
__call__ (self, tasks=None)
__repr__ (self)
Protected Attributes
_num_tasks
_mixed
_funcname = _make_tasks_summary(tasks)
Detailed Description
dask-compatible wrapper that executes a batch of tasks
Definition at line 116 of file _dask.py.
Constructor & Destructor Documentation
__init__()
joblib._dask.Batch.__init__ (self, tasks)
Definition at line 119 of file _dask.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__call__()
joblib._dask.Batch.__call__ (self, tasks = None)
Definition at line 124 of file _dask.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), scipy.interpolate._fitpack2.SphereBivariateSpline.ev(), matplotlib.ticker.Formatter.format_data(), and matplotlib.ticker.LogFormatter.format_data().
__repr__()
joblib._dask.Batch.__repr__ (self)
Definition at line 131 of file _dask.py.
Member Data Documentation
_funcname
joblib._dask.Batch._funcname = _make_tasks_summary(tasks) protected
Definition at line 122 of file _dask.py.
_mixed
joblib._dask.Batch._mixed protected
Definition at line 122 of file _dask.py.
_num_tasks
joblib._dask.Batch._num_tasks protected
Definition at line 122 of file _dask.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/joblib/_dask.py