Code Cloning Analysis: pip._vendor.six.Module_six_moves_urllib Class Reference
pip._vendor.six.Module_six_moves_urllib Class Reference
Public Member Functions
__dir__ (self)
Static Public Attributes
parse = _importer._get_module("moves.urllib_parse")
error = _importer._get_module("moves.urllib_error")
request = _importer._get_module("moves.urllib_request")
response = _importer._get_module("moves.urllib_response")
robotparser = _importer._get_module("moves.urllib_robotparser")
Static Private Attributes
list __path__ = []
Detailed Description
Create a six.moves.urllib namespace that resembles the Python 3 namespace
Definition at line 493 of file six.py.
Member Function Documentation
__dir__()
pip._vendor.six.Module_six_moves_urllib.__dir__ (self)
Definition at line 503 of file six.py.
Member Data Documentation
__path__
list pip._vendor.six.Module_six_moves_urllib.__path__ = [] static private
Definition at line 496 of file six.py.
error
pip._vendor.six.Module_six_moves_urllib.error = _importer._get_module("moves.urllib_error") static
Definition at line 498 of file six.py.
Referenced by pip._internal.cli.parser.ConfigOptionParser._update_defaults(), and matplotlib.sphinxext.plot_directive.PlotDirective.run().
parse
pip._vendor.six.Module_six_moves_urllib.parse = _importer._get_module("moves.urllib_parse") static
Definition at line 497 of file six.py.
Referenced by pandas.io.formats.css.CSSResolver.__call__(), fontTools.t1Lib.T1Font.getGlyphSet(), and pip._vendor.rich.style.Style.normalize().
request
pip._vendor.six.Module_six_moves_urllib.request = _importer._get_module("moves.urllib_request") static
Definition at line 499 of file six.py.
Referenced by pip._vendor.requests.sessions.Session.delete(), pip._vendor.requests.sessions.Session.get(), pip._vendor.requests.sessions.Session.head(), pip._vendor.requests.sessions.Session.options(), pip._vendor.requests.sessions.Session.patch(), pip._vendor.requests.sessions.Session.post(), and pip._vendor.requests.sessions.Session.put().
response
pip._vendor.six.Module_six_moves_urllib.response = _importer._get_module("moves.urllib_response") static
Definition at line 500 of file six.py.
Referenced by sklearn.inspection._plot.decision_boundary.DecisionBoundaryDisplay.plot().
robotparser
pip._vendor.six.Module_six_moves_urllib.robotparser = _importer._get_module("moves.urllib_robotparser") static
Definition at line 501 of file six.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pip/_vendor/six.py