Code Cloning Analysis: pandas.core.indexers.objects.GroupbyIndexer Class Reference
pandas.core.indexers.objects.GroupbyIndexer Class Reference
Public Member Functions
None __init__ (self, np.ndarray|None index_array=None, int|BaseIndexer window_size=0, dict|None groupby_indices=None, type[BaseIndexer] window_indexer=BaseIndexer, dict|None indexer_kwargs=None, **kwargs)
tuple[np.ndarray, np.ndarray] get_window_bounds (self, int num_values=0, int|None min_periods=None, bool|None center=None, str|None closed=None, int|None step=None)
Public Member Functions inherited from pandas.core.indexers.objects.BaseIndexer
None __init__ (self, np.ndarray|None index_array=None, int window_size=0, **kwargs)
Public Attributes
groupby_indices = groupby_indices or {}
window_indexer = window_indexer
indexer_kwargs = indexer_kwargs.copy() if indexer_kwargs else {}
Public Attributes inherited from pandas.core.indexers.objects.BaseIndexer
index_array = index_array
window_size = window_size
Detailed Description
Calculate bounds to compute groupby rolling, mimicking df.groupby().rolling()
Definition at line 348 of file objects.py.
Constructor & Destructor Documentation
__init__()
None pandas.core.indexers.objects.GroupbyIndexer.__init__ (self, np.ndarray | None index_array = None, int | BaseIndexer window_size = 0, dict | None groupby_indices = None, type[BaseIndexer] window_indexer = BaseIndexer, dict | None indexer_kwargs = None, ** kwargs)
Parameters
----------
index_array : np.ndarray or None
    np.ndarray of the index of the original object that we are performing
    a chained groupby operation over. This index has been pre-sorted relative to
    the groups
window_size : int or BaseIndexer
    window size during the windowing operation
groupby_indices : dict or None
    dict of {group label: [positional index of rows belonging to the group]}
window_indexer : BaseIndexer
    BaseIndexer class determining the start and end bounds of each group
indexer_kwargs : dict or None
    Custom kwargs to be passed to window_indexer
**kwargs :
    keyword arguments that will be available when get_window_bounds is called
Definition at line 351 of file objects.py.
References __init__(), groupby_indices, pandas.core.indexers.objects.BaseIndexer.index_array, indexer_kwargs, window_indexer, and pandas.core.indexers.objects.BaseIndexer.window_size.
Referenced by __init__(), sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
get_window_bounds()
tuple[np.ndarray, np.ndarray] pandas.core.indexers.objects.GroupbyIndexer.get_window_bounds (self, int num_values = 0, int | None min_periods = None, bool | None center = None, str | None closed = None, int | None step = None)
Reimplemented from pandas.core.indexers.objects.BaseIndexer.
Definition at line 388 of file objects.py.
Member Data Documentation
groupby_indices
pandas.core.indexers.objects.GroupbyIndexer.groupby_indices = groupby_indices or {}
Definition at line 378 of file objects.py.
Referenced by __init__().
indexer_kwargs
pandas.core.indexers.objects.GroupbyIndexer.indexer_kwargs = indexer_kwargs.copy() if indexer_kwargs else {}
Definition at line 380 of file objects.py.
Referenced by __init__().
window_indexer
pandas.core.indexers.objects.GroupbyIndexer.window_indexer = window_indexer
Definition at line 379 of file objects.py.
Referenced by __init__().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/core/indexers/objects.py