Code Cloning Analysis: matplotlib.dates Namespace Reference
matplotlib.dates Namespace Reference
Classes
class _SwitchableDateConverter
class AutoDateFormatter
class AutoDateLocator
class ConciseDateConverter
class ConciseDateFormatter
class DateConverter
class DateFormatter
date tick locators and formatters ###
class DateLocator
class DayLocator
class HourLocator
class MicrosecondLocator
class MinuteLocator
class MonthLocator
class RRuleLocator
class rrulewrapper
class SecondLocator
class WeekdayLocator
class YearLocator
Functions
_get_tzinfo (tz=None)
_reset_epoch_test_example ()
set_epoch (epoch)
get_epoch ()
_dt64_to_ordinalf (d)
_from_ordinalf (x, tz=None)
datestr2num (d, default=None)
date2num (d)
num2date (x, tz=None)
num2timedelta (x)
drange (dstart, dend, delta)
_wrap_in_tex (text)
Variables
tuple __all__
_log = logging.getLogger(__name__)
UTC = datetime.timezone.utc
EPOCH_OFFSET = float(datetime.datetime(1970, 1, 1).toordinal())
int MICROSECONDLY = SECONDLY + 1
int HOURS_PER_DAY = 24.
int MIN_PER_HOUR = 60.
int SEC_PER_MIN = 60.
int MONTHS_PER_YEAR = 12.
int DAYS_PER_WEEK = 7.
int DAYS_PER_MONTH = 30.
float DAYS_PER_YEAR = 365.0
int MINUTES_PER_DAY = MIN_PER_HOUR * HOURS_PER_DAY
int SEC_PER_HOUR = SEC_PER_MIN * MIN_PER_HOUR
int SEC_PER_DAY = SEC_PER_HOUR * HOURS_PER_DAY
int SEC_PER_WEEK = SEC_PER_DAY * DAYS_PER_WEEK
int MUSECONDS_PER_DAY = 1e6 * SEC_PER_DAY
MONDAY
TUESDAY
WEDNESDAY
THURSDAY
FRIDAY
SATURDAY
SUNDAY
tuple WEEKDAYS = (MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY)
_epoch = None
_from_ordinalf_np_vectorized = np.vectorize(_from_ordinalf, otypes="O")
_dateutil_parser_parse_np_vectorized = np.vectorize(dateutil.parser.parse)
_ordinalf_to_timedelta_np_vectorized
Detailed Description
Matplotlib provides sophisticated date plotting capabilities, standing on the
shoulders of python :mod:`datetime` and the add-on module dateutil_.
By default, Matplotlib uses the units machinery described in
`~matplotlib.units` to convert `datetime.datetime`, and `numpy.datetime64`
objects when plotted on an x- or y-axis. The user does not
need to do anything for dates to be formatted, but dates often have strict
formatting needs, so this module provides many tick locators and formatters.
A basic example using `numpy.datetime64` is::
    import numpy as np
    times = np.arange(np.datetime64('2001-01-02'),
                      np.datetime64('2002-02-03'), np.timedelta64(75, 'm'))
    y = np.random.randn(len(times))
    fig, ax = plt.subplots()
    ax.plot(times, y)
.. seealso::
    - :doc:`/gallery/text_labels_and_annotations/date`
    - :doc:`/gallery/ticks/date_concise_formatter`
    - :doc:`/gallery/ticks/date_demo_convert`
.. _date-format:
Matplotlib date format
----------------------
Matplotlib represents dates using floating point numbers specifying the number
of days since a default epoch of 1970-01-01 UTC; for example,
1970-01-01, 06:00 is the floating point number 0.25. The formatters and
locators require the use of `datetime.datetime` objects, so only dates between
year 0001 and 9999 can be represented.  Microsecond precision
is achievable for (approximately) 70 years on either side of the epoch, and
20 microseconds for the rest of the allowable range of dates (year 0001 to
9999). The epoch can be changed at import time via `.dates.set_epoch` or
:rc:`date.epoch` to other dates if necessary; see
:doc:`/gallery/ticks/date_precision_and_epochs` for a discussion.
.. note::
   Before Matplotlib 3.3, the epoch was 0000-12-31 which lost modern
   microsecond precision and also made the default axis limit of 0 an invalid
   datetime.  In 3.3 the epoch was changed as above.  To convert old
   ordinal floats to the new epoch, users can do::
     new_ordinal = old_ordinal + mdates.date2num(np.datetime64('0000-12-31'))
There are a number of helper functions to convert between :mod:`datetime`
objects and Matplotlib dates:
.. currentmodule:: matplotlib.dates
.. autosummary::
   :nosignatures:
   datestr2num
   date2num
   num2date
   num2timedelta
   drange
   set_epoch
   get_epoch
.. note::
   Like Python's `datetime.datetime`, Matplotlib uses the Gregorian calendar
   for all conversions between dates and floating point numbers. This practice
   is not universal, and calendar differences can cause confusing
   differences between what Python and Matplotlib give as the number of days
   since 0001-01-01 and what other software and databases yield.  For
   example, the US Naval Observatory uses a calendar that switches
   from Julian to Gregorian in October, 1582.  Hence, using their
   calculator, the number of days between 0001-01-01 and 2006-04-01 is
   732403, whereas using the Gregorian calendar via the datetime
   module we find::
     In [1]: date(2006, 4, 1).toordinal() - date(1, 1, 1).toordinal()
     Out[1]: 732401
All the Matplotlib date converters, locators and formatters are timezone aware.
If no explicit timezone is provided, :rc:`timezone` is assumed, provided as a
string.  If you want to use a different timezone, pass the *tz* keyword
argument of `num2date` to any date tick locators or formatters you create. This
can be either a `datetime.tzinfo` instance or a string with the timezone name
that can be parsed by `~dateutil.tz.gettz`.
A wide range of specific and general purpose date tick locators and
formatters are provided in this module.  See
:mod:`matplotlib.ticker` for general information on tick locators
and formatters.  These are described below.
The dateutil_ module provides additional code to handle date ticking, making it
easy to place ticks on any kinds of dates.  See examples below.
.. _dateutil: https://dateutil.readthedocs.io
.. _date-locators:
Date tick locators
------------------
Most of the date tick locators can locate single or multiple ticks. For example::
    # import constants for the days of the week
    from matplotlib.dates import MO, TU, WE, TH, FR, SA, SU
    # tick on Mondays every week
    loc = WeekdayLocator(byweekday=MO, tz=tz)
    # tick on Mondays and Saturdays
    loc = WeekdayLocator(byweekday=(MO, SA))
In addition, most of the constructors take an interval argument::
    # tick on Mondays every second week
    loc = WeekdayLocator(byweekday=MO, interval=2)
The rrule locator allows completely general date ticking::
    # tick every 5th easter
    rule = rrulewrapper(YEARLY, byeaster=1, interval=5)
    loc = RRuleLocator(rule)
The available date tick locators are:
* `MicrosecondLocator`: Locate microseconds.
* `SecondLocator`: Locate seconds.
* `MinuteLocator`: Locate minutes.
* `HourLocator`: Locate hours.
* `DayLocator`: Locate specified days of the month.
* `WeekdayLocator`: Locate days of the week, e.g., MO, TU.
* `MonthLocator`: Locate months, e.g., 7 for July.
* `YearLocator`: Locate years that are multiples of base.
* `RRuleLocator`: Locate using a `rrulewrapper`.
  `rrulewrapper` is a simple wrapper around dateutil_'s `dateutil.rrule`
  which allow almost arbitrary date tick specifications.
  See :doc:`rrule example </gallery/ticks/date_demo_rrule>`.
* `AutoDateLocator`: On autoscale, this class picks the best `DateLocator`
  (e.g., `RRuleLocator`) to set the view limits and the tick locations.  If
  called with ``interval_multiples=True`` it will make ticks line up with
  sensible multiples of the tick intervals.  For example, if the interval is
  4 hours, it will pick hours 0, 4, 8, etc. as ticks.  This behaviour is not
  guaranteed by default.
.. _date-formatters:
Date formatters
---------------
The available date formatters are:
* `AutoDateFormatter`: attempts to figure out the best format to use.  This is
  most useful when used with the `AutoDateLocator`.
* `ConciseDateFormatter`: also attempts to figure out the best format to use,
  and to make the format as compact as possible while still having complete
  date information.  This is most useful when used with the `AutoDateLocator`.
* `DateFormatter`: use `~datetime.datetime.strftime` format strings.
Function Documentation
_dt64_to_ordinalf()
matplotlib.dates._dt64_to_ordinalf (d) protected
Convert `numpy.datetime64` or an `numpy.ndarray` of those types to
Gregorian date as UTC float relative to the epoch (see `.get_epoch`).
Roundoff is float64 precision.  Practically: microseconds for dates
between 290301 BC, 294241 AD, milliseconds for larger dates
(see `numpy.datetime64`).
Definition at line 310 of file dates.py.
References get_epoch().
Referenced by date2num().
_from_ordinalf()
matplotlib.dates._from_ordinalf (x, tz = None) protected
Convert Gregorian float of the date, preserving hours, minutes,
seconds and microseconds.  Return value is a `.datetime`.
The input date *x* is a float in ordinal days at UTC, and the output will
be the specified `.datetime` object corresponding to that time in
timezone *tz*, or if *tz* is ``None``, in the timezone specified in
:rc:`timezone`.
Definition at line 334 of file dates.py.
References _get_tzinfo(), and get_epoch().
_get_tzinfo()
matplotlib.dates._get_tzinfo (tz = None) protected
Generate `~datetime.tzinfo` from a string or return `~datetime.tzinfo`.
If None, retrieve the preferred timezone from the rcParams dictionary.
Definition at line 208 of file dates.py.
Referenced by matplotlib.dates.DateFormatter.__init__(), matplotlib.dates.DateLocator.__init__(), _from_ordinalf(), num2date(), and matplotlib.dates.DateLocator.set_tzinfo().
_reset_epoch_test_example()
matplotlib.dates._reset_epoch_test_example () protected
Reset the Matplotlib date epoch so it can be set again.
Only for use in tests and examples.
Definition at line 256 of file dates.py.
_wrap_in_tex()
matplotlib.dates._wrap_in_tex (text) protected
Definition at line 551 of file dates.py.
date2num()
matplotlib.dates.date2num (d)
Convert datetime objects to Matplotlib dates.
Parameters
----------
d : `datetime.datetime` or `numpy.datetime64` or sequences of these
Returns
-------
float or sequence of floats
    Number of days since the epoch.  See `.get_epoch` for the
    epoch, which can be changed by :rc:`date.epoch` or `.set_epoch`.  If
    the epoch is "1970-01-01T00:00:00" (default) then noon Jan 1 1970
    ("1970-01-01T12:00:00") returns 0.5.
Notes
-----
The Gregorian calendar is assumed; this is not universal practice.
For details see the module docstring.
Definition at line 405 of file dates.py.
References _dt64_to_ordinalf().
Referenced by matplotlib.dates.DateConverter.convert(), datestr2num(), drange(), matplotlib.dates.AutoDateLocator.get_locator(), matplotlib.dates.AutoDateLocator.nonsingular(), matplotlib.dates.DateLocator.nonsingular(), matplotlib.dates.MicrosecondLocator.tick_values(), and matplotlib.dates.RRuleLocator.tick_values().
datestr2num()
matplotlib.dates.datestr2num (d, default = None)
Convert a date string to a datenum using `dateutil.parser.parse`.
Parameters
----------
d : str or sequence of str
    The dates to convert.
default : datetime.datetime, optional
    The default date to use when fields are missing in *d*.
Definition at line 379 of file dates.py.
References date2num().
drange()
matplotlib.dates.drange (dstart, dend, delta)
Return a sequence of equally spaced Matplotlib dates.
The dates start at *dstart* and reach up to, but not including *dend*.
They are spaced by *delta*.
Parameters
----------
dstart, dend : `~datetime.datetime`
    The date limits.
delta : `datetime.timedelta`
    Spacing of the dates.
Returns
-------
`numpy.array`
    A list floats representing Matplotlib dates.
Definition at line 510 of file dates.py.
References date2num().
get_epoch()
matplotlib.dates.get_epoch ()
Get the epoch used by `.dates`.
Returns
-------
epoch : str
    String for the epoch (parsable by `numpy.datetime64`).
Definition at line 295 of file dates.py.
Referenced by _dt64_to_ordinalf(), and _from_ordinalf().
num2date()
matplotlib.dates.num2date (x, tz = None)
Convert Matplotlib dates to `~datetime.datetime` objects.
Parameters
----------
x : float or sequence of floats
    Number of days (fraction part represents hours, minutes, seconds)
    since the epoch.  See `.get_epoch` for the
    epoch, which can be changed by :rc:`date.epoch` or `.set_epoch`.
tz : str or `~datetime.tzinfo`, default: :rc:`timezone`
    Timezone of *x*. If a string, *tz* is passed to `dateutil.tz`.
Returns
-------
`~datetime.datetime` or sequence of `~datetime.datetime`
    Dates are returned in timezone *tz*.
    If *x* is a sequence, a sequence of `~datetime.datetime` objects will
    be returned.
Notes
-----
The Gregorian calendar is assumed; this is not universal practice.
For details, see the module docstring.
Definition at line 457 of file dates.py.
References _get_tzinfo().
Referenced by matplotlib.dates.DateFormatter.__init__(), matplotlib.dates.DateLocator.datalim_to_dt(), matplotlib.dates.ConciseDateFormatter.format_data_short(), matplotlib.dates.ConciseDateFormatter.format_ticks(), matplotlib.tests.test_axes.test_specgram_origin_kwarg(), and matplotlib.dates.DateLocator.viewlim_to_dt().
num2timedelta()
matplotlib.dates.num2timedelta (x)
Convert number of days to a `~datetime.timedelta` object.
If *x* is a sequence, a sequence of `~datetime.timedelta` objects will
be returned.
Parameters
----------
x : float, sequence of floats
    Number of days. The fraction part represents hours, minutes, seconds.
Returns
-------
`datetime.timedelta` or list[`datetime.timedelta`]
Definition at line 491 of file dates.py.
set_epoch()
matplotlib.dates.set_epoch (epoch)
Set the epoch (origin for dates) for datetime calculations.
The default epoch is :rc:`date.epoch`.
If microsecond accuracy is desired, the date being plotted needs to be
within approximately 70 years of the epoch. Matplotlib internally
represents dates as days since the epoch, so floating point dynamic
range needs to be within a factor of 2^52.
`~.dates.set_epoch` must be called before any dates are converted
(i.e. near the import section) or a RuntimeError will be raised.
See also :doc:`/gallery/ticks/date_precision_and_epochs`.
Parameters
----------
epoch : str
    valid UTC date parsable by `numpy.datetime64` (do not include
    timezone).
Definition at line 266 of file dates.py.
Variable Documentation
__all__
tuple matplotlib.dates.__all__ private
Initial value:
=  ('datestr2num', 'date2num', 'num2date', 'num2timedelta', 'drange',
           'set_epoch', 'get_epoch', 'DateFormatter', 'ConciseDateFormatter',
           'AutoDateFormatter', 'DateLocator', 'RRuleLocator',
           'AutoDateLocator', 'YearLocator', 'MonthLocator', 'WeekdayLocator',
           'DayLocator', 'HourLocator', 'MinuteLocator',
           'SecondLocator', 'MicrosecondLocator',
           'rrule', 'MO', 'TU', 'WE', 'TH', 'FR', 'SA', 'SU',
           'YEARLY', 'MONTHLY', 'WEEKLY', 'DAILY',
           'HOURLY', 'MINUTELY', 'SECONDLY', 'MICROSECONDLY', 'relativedelta',
           'DateConverter', 'ConciseDateConverter', 'rrulewrapper')
Definition at line 192 of file dates.py.
_dateutil_parser_parse_np_vectorized
matplotlib.dates._dateutil_parser_parse_np_vectorized = np.vectorize(dateutil.parser.parse) protected
Definition at line 376 of file dates.py.
_epoch
matplotlib.dates._epoch = None protected
Definition at line 253 of file dates.py.
_from_ordinalf_np_vectorized
matplotlib.dates._from_ordinalf_np_vectorized = np.vectorize(_from_ordinalf, otypes="O") protected
Definition at line 374 of file dates.py.
_log
matplotlib.dates._log = logging.getLogger(__name__) protected
Definition at line 204 of file dates.py.
_ordinalf_to_timedelta_np_vectorized
matplotlib.dates._ordinalf_to_timedelta_np_vectorized protected
Initial value:
=  np.vectorize(
    lambda x: datetime.timedelta(days=x), otypes="O")
Definition at line 487 of file dates.py.
DAYS_PER_MONTH
int matplotlib.dates.DAYS_PER_MONTH = 30.
Definition at line 237 of file dates.py.
DAYS_PER_WEEK
int matplotlib.dates.DAYS_PER_WEEK = 7.
Definition at line 236 of file dates.py.
DAYS_PER_YEAR
float matplotlib.dates.DAYS_PER_YEAR = 365.0
Definition at line 238 of file dates.py.
EPOCH_OFFSET
matplotlib.dates.EPOCH_OFFSET = float(datetime.datetime(1970, 1, 1).toordinal())
Definition at line 228 of file dates.py.
FRIDAY
matplotlib.dates.FRIDAY
Definition at line 248 of file dates.py.
HOURS_PER_DAY
int matplotlib.dates.HOURS_PER_DAY = 24.
Definition at line 231 of file dates.py.
MICROSECONDLY
int matplotlib.dates.MICROSECONDLY = SECONDLY + 1
Definition at line 230 of file dates.py.
MIN_PER_HOUR
int matplotlib.dates.MIN_PER_HOUR = 60.
Definition at line 232 of file dates.py.
MINUTES_PER_DAY
int matplotlib.dates.MINUTES_PER_DAY = MIN_PER_HOUR * HOURS_PER_DAY
Definition at line 240 of file dates.py.
MONDAY
matplotlib.dates.MONDAY
Definition at line 248 of file dates.py.
MONTHS_PER_YEAR
int matplotlib.dates.MONTHS_PER_YEAR = 12.
Definition at line 234 of file dates.py.
MUSECONDS_PER_DAY
int matplotlib.dates.MUSECONDS_PER_DAY = 1e6 * SEC_PER_DAY
Definition at line 246 of file dates.py.
SATURDAY
matplotlib.dates.SATURDAY
Definition at line 248 of file dates.py.
SEC_PER_DAY
int matplotlib.dates.SEC_PER_DAY = SEC_PER_HOUR * HOURS_PER_DAY
Definition at line 243 of file dates.py.
SEC_PER_HOUR
int matplotlib.dates.SEC_PER_HOUR = SEC_PER_MIN * MIN_PER_HOUR
Definition at line 242 of file dates.py.
SEC_PER_MIN
int matplotlib.dates.SEC_PER_MIN = 60.
Definition at line 233 of file dates.py.
SEC_PER_WEEK
int matplotlib.dates.SEC_PER_WEEK = SEC_PER_DAY * DAYS_PER_WEEK
Definition at line 244 of file dates.py.
SUNDAY
matplotlib.dates.SUNDAY
Definition at line 248 of file dates.py.
THURSDAY
matplotlib.dates.THURSDAY
Definition at line 248 of file dates.py.
TUESDAY
matplotlib.dates.TUESDAY
Definition at line 248 of file dates.py.
UTC
matplotlib.dates.UTC = datetime.timezone.utc
Definition at line 205 of file dates.py.
WEDNESDAY
matplotlib.dates.WEDNESDAY
Definition at line 248 of file dates.py.
WEEKDAYS
tuple matplotlib.dates.WEEKDAYS = (MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY)
Definition at line 250 of file dates.py.