Code Cloning Analysis: axisartist.axislines.AxesZero Class Reference
axisartist.axislines.AxesZero Class Reference
Public Member Functions
clear (self)
Public Member Functions inherited from axisartist.axislines.Axes
__init__ (self, *args, grid_helper=None, **kwargs)
toggle_axisline (self, b=None)
axis (self)
get_grid_helper (self)
grid (self, visible=None, which='major', axis="both", **kwargs)
get_children (self)
new_fixed_axis (self, loc, offset=None)
new_floating_axis (self, nth_coord, value, axis_direction="bottom")
Public Attributes
patch
Public Attributes inherited from axisartist.axislines.Axes
gridlines
Additional Inherited Members
Protected Attributes inherited from axisartist.axislines.Axes
bool _axisline_on = True
_grid_helper = grid_helper if grid_helper else GridHelperRectlinear(self)
_axislines = mpl_axes.Axes.AxisDict(self)
Detailed Description
Definition at line 462 of file axislines.py.
Member Function Documentation
clear()
axisartist.axislines.AxesZero.clear (self)
Reimplemented from axisartist.axislines.Axes.
Definition at line 464 of file axislines.py.
Referenced by matplotlib.projections.geo.AitoffAxes.InvertedAitoffTransform.inverted(), matplotlib.projections.geo.HammerAxes.InvertedHammerTransform.inverted(), matplotlib.projections.geo.LambertAxes.InvertedLambertTransform.inverted(), and matplotlib.projections.geo.MollweideAxes.InvertedMollweideTransform.inverted().
Member Data Documentation
patch
axisartist.axislines.AxesZero.patch
Definition at line 474 of file axislines.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/mpl_toolkits/axisartist/axislines.py