Code Cloning Analysis: pandas.io.parquet Namespace Reference
pandas.io.parquet Namespace Reference
Classes
class BaseImpl
class FastParquetImpl
class PyArrowImpl
Functions
BaseImpl get_engine (str engine)
tuple[ FilePath|ReadBuffer[bytes]|WriteBuffer[bytes], IOHandles[bytes]|None, Any] _get_path_or_handle (FilePath|ReadBuffer[bytes]|WriteBuffer[bytes] path, Any fs, StorageOptions|None storage_options=None, str mode="rb", bool is_dir=False)
bytes|None to_parquet (DataFrame df, FilePath|WriteBuffer[bytes]|None path=None, str engine="auto", str|None compression="snappy", bool|None index=None, StorageOptions|None storage_options=None, list[str]|None partition_cols=None, Any filesystem=None, **kwargs)
DataFrame read_parquet (FilePath|ReadBuffer[bytes] path, str engine="auto", list[str]|None columns=None, StorageOptions|None storage_options=None, bool|lib.NoDefault use_nullable_dtypes=lib.no_default, DtypeBackend|lib.NoDefault dtype_backend=lib.no_default, Any filesystem=None, list[tuple]|list[list[tuple]]|None filters=None, **kwargs)
Detailed Description
 parquet compat
Function Documentation
_get_path_or_handle()
tuple[ FilePath | ReadBuffer[bytes] | WriteBuffer[bytes], IOHandles[bytes] | None, Any ] pandas.io.parquet._get_path_or_handle (FilePath | ReadBuffer[bytes] | WriteBuffer[bytes] path, Any fs, StorageOptions | None storage_options = None, str mode = "rb", bool is_dir = False) protected
File handling for PyArrow.
Definition at line 86 of file parquet.py.
get_engine()
BaseImpl pandas.io.parquet.get_engine (str engine)
return our implementation
Definition at line 52 of file parquet.py.
Referenced by read_parquet(), and to_parquet().
read_parquet()
DataFrame pandas.io.parquet.read_parquet (FilePath | ReadBuffer[bytes] path, str engine = "auto", list[str] | None columns = None, StorageOptions | None storage_options = None, bool | lib.NoDefault use_nullable_dtypes = lib.no_default, DtypeBackend | lib.NoDefault dtype_backend = lib.no_default, Any filesystem = None, list[tuple] | list[list[tuple]] | None filters = None, ** kwargs)
Load a parquet object from the file path, returning a DataFrame.
Parameters
----------
path : str, path object or file-like object
    String, path object (implementing ``os.PathLike[str]``), or file-like
    object implementing a binary ``read()`` function.
    The string could be a URL. Valid URL schemes include http, ftp, s3,
    gs, and file. For file URLs, a host is expected. A local file could be:
    ``file://localhost/path/to/table.parquet``.
    A file URL can also be a path to a directory that contains multiple
    partitioned parquet files. Both pyarrow and fastparquet support
    paths to directories as well as file URLs. A directory path could be:
    ``file://localhost/path/to/tables`` or ``s3://bucket/partition_dir``.
engine : {{'auto', 'pyarrow', 'fastparquet'}}, default 'auto'
    Parquet library to use. If 'auto', then the option
    ``io.parquet.engine`` is used. The default ``io.parquet.engine``
    behavior is to try 'pyarrow', falling back to 'fastparquet' if
    'pyarrow' is unavailable.
    When using the ``'pyarrow'`` engine and no storage options are provided
    and a filesystem is implemented by both ``pyarrow.fs`` and ``fsspec``
    (e.g. "s3://"), then the ``pyarrow.fs`` filesystem is attempted first.
    Use the filesystem keyword with an instantiated fsspec filesystem
    if you wish to use its implementation.
columns : list, default=None
    If not None, only these columns will be read from the file.
{storage_options}
    .. versionadded:: 1.3.0
use_nullable_dtypes : bool, default False
    If True, use dtypes that use ``pd.NA`` as missing value indicator
    for the resulting DataFrame. (only applicable for the ``pyarrow``
    engine)
    As new dtypes are added that support ``pd.NA`` in the future, the
    output with this option will change to use those dtypes.
    Note: this is an experimental option, and behaviour (e.g. additional
    support dtypes) may change without notice.
    .. deprecated:: 2.0
dtype_backend : {{'numpy_nullable', 'pyarrow'}}, default 'numpy_nullable'
    Back-end data type applied to the resultant :class:`DataFrame`
    (still experimental). Behaviour is as follows:
    * ``"numpy_nullable"``: returns nullable-dtype-backed :class:`DataFrame`
      (default).
    * ``"pyarrow"``: returns pyarrow-backed nullable :class:`ArrowDtype`
      DataFrame.
    .. versionadded:: 2.0
filesystem : fsspec or pyarrow filesystem, default None
    Filesystem object to use when reading the parquet file. Only implemented
    for ``engine="pyarrow"``.
    .. versionadded:: 2.1.0
filters : List[Tuple] or List[List[Tuple]], default None
    To filter out data.
    Filter syntax: [[(column, op, val), ...],...]
    where op is [==, =, >, >=, <, <=, !=, in, not in]
    The innermost tuples are transposed into a set of filters applied
    through an `AND` operation.
    The outer list combines these sets of filters through an `OR`
    operation.
    A single list of tuples can also be used, meaning that no `OR`
    operation between set of filters is to be conducted.
    Using this argument will NOT result in row-wise filtering of the final
    partitions unless ``engine="pyarrow"`` is also specified.  For
    other engines, filtering is only performed at the partition level, that is,
    to prevent the loading of some row-groups and/or files.
    .. versionadded:: 2.1.0
**kwargs
    Any additional kwargs are passed to the engine.
Returns
-------
DataFrame
See Also
--------
DataFrame.to_parquet : Create a parquet object that serializes a DataFrame.
Examples
--------
>>> original_df = pd.DataFrame(
...     {{"foo": range(5), "bar": range(5, 10)}}
...)
>>> original_df
   foo  bar
0    0    5
1    1    6
2    2    7
3    3    8
4    4    9
>>> df_parquet_bytes = original_df.to_parquet()
>>> from io import BytesIO
>>> restored_df = pd.read_parquet(BytesIO(df_parquet_bytes))
>>> restored_df
   foo  bar
0    0    5
1    1    6
2    2    7
3    3    8
4    4    9
>>> restored_df.equals(original_df)
True
>>> restored_bar = pd.read_parquet(BytesIO(df_parquet_bytes), columns=["bar"])
>>> restored_bar
    bar
0    5
1    6
2    7
3    8
4    9
>>> restored_bar.equals(original_df[['bar']])
True
The function uses `kwargs` that are passed directly to the engine.
In the following example, we use the `filters` argument of the pyarrow
engine to filter the rows of the DataFrame.
Since `pyarrow` is the default engine, we can omit the `engine` argument.
Note that the `filters` argument is implemented by the `pyarrow` engine,
which can benefit from multithreading and also potentially be more
economical in terms of memory.
>>> sel = [("foo", ">", 2)]
>>> restored_part = pd.read_parquet(BytesIO(df_parquet_bytes), filters=sel)
>>> restored_part
    foo  bar
0    3    8
1    4    9
Definition at line 501 of file parquet.py.
References get_engine().
to_parquet()
bytes | None pandas.io.parquet.to_parquet (DataFrame df, FilePath | WriteBuffer[bytes] | None path = None, str engine = "auto", str | None compression = "snappy", bool | None index = None, StorageOptions | None storage_options = None, list[str] | None partition_cols = None, Any filesystem = None, ** kwargs)
Write a DataFrame to the parquet format.
Parameters
----------
df : DataFrame
path : str, path object, file-like object, or None, default None
    String, path object (implementing ``os.PathLike[str]``), or file-like
    object implementing a binary ``write()`` function. If None, the result is
    returned as bytes. If a string, it will be used as Root Directory path
    when writing a partitioned dataset. The engine fastparquet does not
    accept file-like objects.
engine : {{'auto', 'pyarrow', 'fastparquet'}}, default 'auto'
    Parquet library to use. If 'auto', then the option
    ``io.parquet.engine`` is used. The default ``io.parquet.engine``
    behavior is to try 'pyarrow', falling back to 'fastparquet' if
    'pyarrow' is unavailable.
    When using the ``'pyarrow'`` engine and no storage options are provided
    and a filesystem is implemented by both ``pyarrow.fs`` and ``fsspec``
    (e.g. "s3://"), then the ``pyarrow.fs`` filesystem is attempted first.
    Use the filesystem keyword with an instantiated fsspec filesystem
    if you wish to use its implementation.
compression : {{'snappy', 'gzip', 'brotli', 'lz4', 'zstd', None}},
    default 'snappy'. Name of the compression to use. Use ``None``
    for no compression.
index : bool, default None
    If ``True``, include the dataframe's index(es) in the file output. If
    ``False``, they will not be written to the file.
    If ``None``, similar to ``True`` the dataframe's index(es)
    will be saved. However, instead of being saved as values,
    the RangeIndex will be stored as a range in the metadata so it
    doesn't require much space and is faster. Other indexes will
    be included as columns in the file output.
partition_cols : str or list, optional, default None
    Column names by which to partition the dataset.
    Columns are partitioned in the order they are given.
    Must be None if path is not a string.
{storage_options}
filesystem : fsspec or pyarrow filesystem, default None
    Filesystem object to use when reading the parquet file. Only implemented
    for ``engine="pyarrow"``.
    .. versionadded:: 2.1.0
kwargs
    Additional keyword arguments passed to the engine
Returns
-------
bytes if no path argument is provided else None
Definition at line 412 of file parquet.py.
References get_engine().