Code Cloning Analysis: scipy.stats._continuous_distns.laplace_asymmetric_gen Class Reference
scipy.stats._continuous_distns.laplace_asymmetric_gen Class Reference
Protected Member Functions
_shape_info (self)
_pdf (self, x, kappa)
_logpdf (self, x, kappa)
_cdf (self, x, kappa)
_sf (self, x, kappa)
_ppf (self, q, kappa)
_isf (self, q, kappa)
_stats (self, kappa)
_entropy (self, kappa)
Protected Member Functions inherited from scipy.stats._distn_infrastructure.rv_continuous
_attach_methods (self)
_updated_ctor_param (self)
_ppf_to_solve (self, x, q, *args)
_ppf_single (self, q, *args)
_mom_integ0 (self, x, m, *args)
_mom0_sc (self, m, *args)
_mom_integ1 (self, q, m, *args)
_mom1_sc (self, m, *args)
_logpxf (self, x, *args)
_cdf_single (self, x, *args)
_unpack_loc_scale (self, theta)
_nnlf_and_penalty (self, x, args)
_penalized_nnlf (self, theta, x)
_fitstart (self, data, args=None)
_reduce_func (self, args, kwds, data=None)
_moment_error (self, theta, x, data_moments)
_fit_loc_scale_support (self, data, *args)
_param_info (self)
_delta_cdf (self, x1, x2, *args, loc=0, scale=1)
Protected Member Functions inherited from scipy.stats._distn_infrastructure.rv_generic
_attach_argparser_methods (self)
_construct_argparser (self, meths_to_inspect, locscale_in, locscale_out)
_construct_doc (self, docdict, shapes_vals=None)
_construct_default_doc (self, longname=None, docdict=None, discrete='continuous')
_munp (self, n, *args)
_argcheck_rvs (self, *args, **kwargs)
_argcheck (self, *args)
_get_support (self, *args, **kwargs)
_support_mask (self, x, *args)
_open_support_mask (self, x, *args)
_rvs (self, *args, size=None, random_state=None)
_logcdf (self, x, *args)
_logsf (self, x, *args)
_nnlf (self, x, *args)
_nlff_and_penalty (self, x, args, log_fitfun)
_penalized_nlpsf (self, theta, x)
Additional Inherited Members
Public Member Functions inherited from scipy.stats._distn_infrastructure.rv_continuous
__init__ (self, momtype=1, a=None, b=None, xtol=1e-14, badvalue=None, name=None, longname=None, shapes=None, seed=None)
__getstate__ (self)
pdf (self, x, *args, **kwds)
logpdf (self, x, *args, **kwds)
cdf (self, x, *args, **kwds)
logcdf (self, x, *args, **kwds)
sf (self, x, *args, **kwds)
logsf (self, x, *args, **kwds)
ppf (self, q, *args, **kwds)
isf (self, q, *args, **kwds)
fit (self, data, *args, **kwds)
fit_loc_scale (self, data, *args)
expect (self, func=None, args=(), loc=0, scale=1, lb=None, ub=None, conditional=False, **kwds)
Public Member Functions inherited from scipy.stats._distn_infrastructure.rv_generic
__init__ (self, seed=None)
random_state (self)
random_state (self, seed)
__setstate__ (self, state)
freeze (self, *args, **kwds)
__call__ (self, *args, **kwds)
rvs (self, *args, **kwds)
stats (self, *args, **kwds)
entropy (self, *args, **kwds)
moment (self, order, *args, **kwds)
median (self, *args, **kwds)
mean (self, *args, **kwds)
var (self, *args, **kwds)
std (self, *args, **kwds)
interval (self, confidence, *args, **kwds)
support (self, *args, **kwargs)
nnlf (self, theta, x)
Public Attributes inherited from scipy.stats._distn_infrastructure.rv_continuous
b = b
xtol = xtol
int moment_type = momtype
vecentropy = vectorize(self._entropy, otypes='d')
generic_moment = vectorize(self._mom0_sc, otypes='d')
Public Attributes inherited from scipy.stats._distn_infrastructure.rv_generic
str shapes
int numargs = len(shapes)
name = doccer.docformat(self.__doc__, tempdict)
a
badvalue = zeros(i0.shape)
Protected Attributes inherited from scipy.stats._distn_infrastructure.rv_continuous
_ppfvec = vectorize(self._ppf_single, otypes='d')
_cdfvec = vectorize(self._cdf_single, otypes='d')
_ppf_to_solve
_mom_integ0
_mom_integ1
Protected Attributes inherited from scipy.stats._distn_infrastructure.rv_generic
tuple _stats_has_moments
_random_state = check_random_state(seed)
_ctor_param = state[0]
_parse_arg_template
Detailed Description
An asymmetric Laplace continuous random variable.
%(before_notes)s
See Also
--------
laplace : Laplace distribution
Notes
-----
The probability density function for `laplace_asymmetric` is
.. math::
   f(x, \kappa) &= \frac{1}{\kappa+\kappa^{-1}}\exp(-x\kappa),\quad x\ge0\\
                &= \frac{1}{\kappa+\kappa^{-1}}\exp(x/\kappa),\quad x<0\\
for :math:`-\infty < x < \infty`, :math:`\kappa > 0`.
`laplace_asymmetric` takes ``kappa`` as a shape parameter for
:math:`\kappa`. For :math:`\kappa = 1`, it is identical to a
Laplace distribution.
%(after_notes)s
References
----------
.. [1] "Asymmetric Laplace distribution", Wikipedia
        https://en.wikipedia.org/wiki/Asymmetric_Laplace_distribution
.. [2] Kozubowski TJ and Podgrski K. A Multivariate and
       Asymmetric Generalization of Laplace Distribution,
       Computational Statistics 15, 531--540 (2000).
       :doi:`10.1007/PL00022717`
%(example)s
Definition at line 5380 of file _continuous_distns.py.
Member Function Documentation
_cdf()
scipy.stats._continuous_distns.laplace_asymmetric_gen._cdf (self, x, kappa) protected
Reimplemented from scipy.stats._distn_infrastructure.rv_continuous.
Definition at line 5431 of file _continuous_distns.py.
Referenced by scipy.stats._discrete_distns.geom_gen._argcheck(), scipy.stats._discrete_distns.nbinom_gen._argcheck(), scipy.stats._discrete_distns.planck_gen._argcheck(), scipy.stats._discrete_distns.boltzmann_gen._get_support(), scipy.stats._discrete_distns.randint_gen._get_support(), scipy.stats._distn_infrastructure.rv_generic._get_support(), scipy.stats._distn_infrastructure.rv_generic._penalized_nlpsf(), scipy.stats._distn_infrastructure.rv_discrete._updated_ctor_param(), scipy.stats._distn_infrastructure.rv_discrete.cdf(), scipy.stats._multivariate.multivariate_normal_gen.cdf(), scipy.stats._multivariate.multivariate_t_gen.cdf(), and scipy.stats._multivariate.multivariate_normal_gen.logcdf().
_entropy()
scipy.stats._continuous_distns.laplace_asymmetric_gen._entropy (self, kappa) protected
Reimplemented from scipy.stats._distn_infrastructure.rv_continuous.
Definition at line 5467 of file _continuous_distns.py.
Referenced by scipy.stats._distn_infrastructure.rv_continuous._attach_methods(), scipy.stats._distn_infrastructure.rv_discrete._attach_methods(), scipy.stats._multivariate.invwishart_gen.entropy(), scipy.stats._multivariate.matrix_normal_gen.entropy(), scipy.stats._multivariate.multivariate_t_gen.entropy(), scipy.stats._multivariate.vonmises_fisher_gen.entropy(), and scipy.stats._multivariate.wishart_gen.entropy().
_isf()
scipy.stats._continuous_distns.laplace_asymmetric_gen._isf (self, q, kappa) protected
Reimplemented from scipy.stats._distn_infrastructure.rv_generic.
Definition at line 5452 of file _continuous_distns.py.
Referenced by scipy.stats._distn_infrastructure.rv_continuous.isf(), and scipy.stats._distn_infrastructure.rv_discrete.isf().
_logpdf()
scipy.stats._continuous_distns.laplace_asymmetric_gen._logpdf (self, x, kappa) protected
Reimplemented from scipy.stats._distn_infrastructure.rv_continuous.
Definition at line 5425 of file _continuous_distns.py.
Referenced by scipy.stats._continuous_distns.nakagami_gen._argcheck(), scipy.stats._continuous_distns.pearson3_gen._argcheck(), scipy.stats._continuous_distns.kappa4_gen._get_support(), scipy.stats._continuous_distns.reciprocal_gen._get_support(), scipy.stats._continuous_distns.truncnorm_gen._get_support(), scipy.stats._distn_infrastructure.rv_continuous._nnlf_and_penalty(), scipy.stats._distn_infrastructure.rv_continuous._updated_ctor_param(), scipy.stats._distn_infrastructure.rv_continuous.logpdf(), scipy.stats._multivariate.dirichlet_gen.logpdf(), scipy.stats._multivariate.invwishart_gen.logpdf(), scipy.stats._multivariate.matrix_normal_gen.logpdf(), scipy.stats._multivariate.multivariate_normal_gen.logpdf(), scipy.stats._multivariate.multivariate_t_gen.logpdf(), scipy.stats._multivariate.vonmises_fisher_gen.logpdf(), scipy.stats._multivariate.wishart_gen.logpdf(), scipy.stats._multivariate.dirichlet_gen.pdf(), scipy.stats._multivariate.multivariate_normal_gen.pdf(), scipy.stats._multivariate.multivariate_t_gen.pdf(), and scipy.stats._multivariate.vonmises_fisher_gen.pdf().
_pdf()
scipy.stats._continuous_distns.laplace_asymmetric_gen._pdf (self, x, kappa) protected
Reimplemented from scipy.stats._distn_infrastructure.rv_continuous.
Definition at line 5422 of file _continuous_distns.py.
_ppf()
scipy.stats._continuous_distns.laplace_asymmetric_gen._ppf (self, q, kappa) protected
Reimplemented from scipy.stats._distn_infrastructure.rv_generic.
Definition at line 5445 of file _continuous_distns.py.
Referenced by scipy.stats._distn_infrastructure.rv_generic._get_support(), scipy.stats._distn_infrastructure.rv_sample._get_support(), scipy.stats._distn_infrastructure.rv_continuous.expect(), scipy.stats._distn_infrastructure.rv_continuous.ppf(), and scipy.stats._distn_infrastructure.rv_discrete.ppf().
_sf()
scipy.stats._continuous_distns.laplace_asymmetric_gen._sf (self, x, kappa) protected
Reimplemented from scipy.stats._distn_infrastructure.rv_generic.
Definition at line 5438 of file _continuous_distns.py.
Referenced by scipy.stats._distn_infrastructure.rv_generic._get_support(), scipy.stats._distn_infrastructure.rv_continuous.sf(), and scipy.stats._distn_infrastructure.rv_discrete.sf().
_shape_info()
scipy.stats._continuous_distns.laplace_asymmetric_gen._shape_info (self) protected
Definition at line 5419 of file _continuous_distns.py.
Referenced by scipy.stats._distn_infrastructure.rv_continuous.expect(), and scipy.stats._distn_infrastructure.rv_discrete.expect().
_stats()
scipy.stats._continuous_distns.laplace_asymmetric_gen._stats (self, kappa) protected
Reimplemented from scipy.stats._distn_infrastructure.rv_generic.
Definition at line 5459 of file _continuous_distns.py.
Referenced by scipy.stats._distn_infrastructure.rv_generic.moment(), and scipy.stats._distn_infrastructure.rv_generic.stats().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/stats/_continuous_distns.py