Code Cloning Analysis: fontTools.ttLib.woff2 Namespace Reference
fontTools.ttLib.woff2 Namespace Reference
Classes
class WOFF2DirectoryEntry
class WOFF2FlavorData
class WOFF2GlyfTable
class WOFF2HmtxTable
class WOFF2LocaTable
class WOFF2Reader
class WOFF2Writer
Functions
getKnownTagIndex (tag)
unpackBase128 (data)
base128Size (n)
packBase128 (n)
unpack255UShort (data)
pack255UShort (value)
compress (input_file, output_file, transform_tables=None)
decompress (input_file, output_file)
main (args=None)
Variables
log = logging.getLogger("fontTools.ttLib.woff2")
bool haveBrotli = False
str woff2DirectoryFormat
woff2DirectorySize = sstruct.calcsize(woff2DirectoryFormat)
tuple woff2KnownTags
str woff2FlagsFormat
woff2FlagsSize = sstruct.calcsize(woff2FlagsFormat)
str woff2UnknownTagFormat
woff2UnknownTagSize = sstruct.calcsize(woff2UnknownTagFormat)
int woff2UnknownTagIndex = 0x3F
int woff2Base128MaxSize = 5
tuple woff2DirectoryEntryMaxSize
tuple woff2TransformedTableTags = ("glyf", "loca")
str woff2GlyfTableFormat
woff2GlyfTableFormatSize = sstruct.calcsize(woff2GlyfTableFormat)
str bboxFormat
int woff2OverlapSimpleBitmapFlag = 0x0001
Function Documentation
base128Size()
fontTools.ttLib.woff2.base128Size (n)
Return the length in bytes of a UIntBase128-encoded sequence with value n.
>>> base128Size(0)
1
>>> base128Size(24567)
3
>>> base128Size(2**32-1)
5
Definition at line 1391 of file woff2.py.
Referenced by packBase128().
compress()
fontTools.ttLib.woff2.compress (input_file, output_file, transform_tables = None)
Compress OpenType font to WOFF2.
Args:
        input_file: a file path, file or file-like object (open in binary mode)
                containing an OpenType font (either CFF- or TrueType-flavored).
        output_file: a file path, file or file-like object where to save the
                compressed WOFF2 font.
        transform_tables: Optional[Iterable[str]]: a set of table tags for which
                to enable preprocessing transformations. By default, only 'glyf'
                and 'loca' tables are transformed. An empty set means disable all
                transformations.
Definition at line 1498 of file woff2.py.
decompress()
fontTools.ttLib.woff2.decompress (input_file, output_file)
Decompress WOFF2 font to OpenType font.
Args:
        input_file: a file path, file or file-like object (open in binary mode)
                containing a compressed WOFF2 font.
        output_file: a file path, file or file-like object where to save the
                decompressed OpenType font.
Definition at line 1524 of file woff2.py.
getKnownTagIndex()
fontTools.ttLib.woff2.getKnownTagIndex (tag)
Return index of 'tag' in woff2KnownTags list. Return 63 if not found.
Definition at line 642 of file woff2.py.
Referenced by fontTools.ttLib.woff2.WOFF2Writer.__setitem__().
main()
fontTools.ttLib.woff2.main (args = None)
Compress and decompress WOFF2 fonts
Definition at line 1541 of file woff2.py.
pack255UShort()
fontTools.ttLib.woff2.pack255UShort (value)
Encode unsigned integer in range 0 to 65535 (inclusive) to a bytestring
using 255UInt16 variable-length encoding.
>>> pack255UShort(252) == b'\xfc'
True
>>> pack255UShort(506) == b'\xfe\x00'
True
>>> pack255UShort(762) == b'\xfd\x02\xfa'
True
Definition at line 1475 of file woff2.py.
Referenced by fontTools.ttLib.woff2.WOFF2GlyfTable.transform().
packBase128()
fontTools.ttLib.woff2.packBase128 (n)
Encode unsigned integer in range 0 to 2**32-1 (inclusive) to a string of
bytes using UIntBase128 variable-length encoding. Produce the shortest possible
encoding.
>>> packBase128(63) == b"\x3f"
True
>>> packBase128(2**32-1) == b'\x8f\xff\xff\xff\x7f'
True
Definition at line 1409 of file woff2.py.
References base128Size().
unpack255UShort()
fontTools.ttLib.woff2.unpack255UShort (data)
Read one to three bytes from 255UInt16-encoded input string, and return a
tuple containing the decoded integer plus any leftover data.
>>> unpack255UShort(bytechr(252))[0]
252
Note that some numbers (e.g. 506) can have multiple encodings:
>>> unpack255UShort(struct.pack("BB", 254, 0))[0]
506
>>> unpack255UShort(struct.pack("BB", 255, 253))[0]
506
>>> unpack255UShort(struct.pack("BBB", 253, 1, 250))[0]
506
Definition at line 1431 of file woff2.py.
Referenced by fontTools.ttLib.woff2.WOFF2GlyfTable.transform().
unpackBase128()
fontTools.ttLib.woff2.unpackBase128 (data)
Read one to five bytes from UIntBase128-encoded input string, and return
a tuple containing the decoded integer plus any leftover data.
>>> unpackBase128(b'\x3f\x00\x00') == (63, b"\x00\x00")
True
>>> unpackBase128(b'\x8f\xff\xff\xff\x7f')[0] == 4294967295
True
>>> unpackBase128(b'\x80\x80\x3f')  # doctest: +IGNORE_EXCEPTION_DETAIL
Traceback (most recent call last):
File "<stdin>", line 1, in ?
TTLibError: UIntBase128 value must not start with leading zeros
>>> unpackBase128(b'\x8f\xff\xff\xff\xff\x7f')[0]  # doctest: +IGNORE_EXCEPTION_DETAIL
Traceback (most recent call last):
File "<stdin>", line 1, in ?
TTLibError: UIntBase128-encoded sequence is longer than 5 bytes
>>> unpackBase128(b'\x90\x80\x80\x80\x00')[0]  # doctest: +IGNORE_EXCEPTION_DETAIL
Traceback (most recent call last):
File "<stdin>", line 1, in ?
TTLibError: UIntBase128 value exceeds 2**32-1
Definition at line 1346 of file woff2.py.
Variable Documentation
bboxFormat
str fontTools.ttLib.woff2.bboxFormat
Initial value:
=  """
        >   # big endian
        xMin:               h
        yMin:               h
        xMax:               h
        yMax:               h
"""
Definition at line 631 of file woff2.py.
haveBrotli
bool fontTools.ttLib.woff2.haveBrotli = False
Definition at line 33 of file woff2.py.
log
fontTools.ttLib.woff2.log = logging.getLogger("fontTools.ttLib.woff2")
Definition at line 31 of file woff2.py.
woff2Base128MaxSize
int fontTools.ttLib.woff2.woff2Base128MaxSize = 5
Definition at line 607 of file woff2.py.
woff2DirectoryEntryMaxSize
tuple fontTools.ttLib.woff2.woff2DirectoryEntryMaxSize
Initial value:
=  (
    woff2FlagsSize + woff2UnknownTagSize + 2 * woff2Base128MaxSize
)
Definition at line 608 of file woff2.py.
woff2DirectoryFormat
str fontTools.ttLib.woff2.woff2DirectoryFormat
Initial value:
=  """
        > # big endian
        signature:           4s   # "wOF2"
        sfntVersion:         4s
        length:              L    # total woff2 file size
        numTables:           H    # number of tables
        reserved:            H    # set to 0
        totalSfntSize:       L    # uncompressed size
        totalCompressedSize: L    # compressed size
        majorVersion:        H    # major version of WOFF file
        minorVersion:        H    # minor version of WOFF file
        metaOffset:          L    # offset to metadata block
        metaLength:          L    # length of compressed metadata
        metaOrigLength:      L    # length of uncompressed metadata
        privOffset:          L    # offset to private data block
        privLength:          L    # length of private data block
"""
Definition at line 505 of file woff2.py.
woff2DirectorySize
fontTools.ttLib.woff2.woff2DirectorySize = sstruct.calcsize(woff2DirectoryFormat)
Definition at line 523 of file woff2.py.
woff2FlagsFormat
str fontTools.ttLib.woff2.woff2FlagsFormat
Initial value:
=  """
        > # big endian
        flags: B  # table type and flags
"""
Definition at line 591 of file woff2.py.
woff2FlagsSize
fontTools.ttLib.woff2.woff2FlagsSize = sstruct.calcsize(woff2FlagsFormat)
Definition at line 596 of file woff2.py.
woff2GlyfTableFormat
str fontTools.ttLib.woff2.woff2GlyfTableFormat
Initial value:
=  """
        > # big endian
        version:                  H  # = 0x0000
        optionFlags:              H  # Bit 0: we have overlapSimpleBitmap[], Bits 1-15: reserved
        numGlyphs:                H  # Number of glyphs
        indexFormat:              H  # Offset format for loca table
        nContourStreamSize:       L  # Size of nContour stream
        nPointsStreamSize:        L  # Size of nPoints stream
        flagStreamSize:           L  # Size of flag stream
        glyphStreamSize:          L  # Size of glyph stream
        compositeStreamSize:      L  # Size of composite stream
        bboxStreamSize:           L  # Comnined size of bboxBitmap and bboxStream
        instructionStreamSize:    L  # Size of instruction stream
"""
Definition at line 614 of file woff2.py.
woff2GlyfTableFormatSize
fontTools.ttLib.woff2.woff2GlyfTableFormatSize = sstruct.calcsize(woff2GlyfTableFormat)
Definition at line 629 of file woff2.py.
woff2KnownTags
tuple fontTools.ttLib.woff2.woff2KnownTags
Definition at line 525 of file woff2.py.
woff2OverlapSimpleBitmapFlag
int fontTools.ttLib.woff2.woff2OverlapSimpleBitmapFlag = 0x0001
Definition at line 639 of file woff2.py.
woff2TransformedTableTags
tuple fontTools.ttLib.woff2.woff2TransformedTableTags = ("glyf", "loca")
Definition at line 612 of file woff2.py.
woff2UnknownTagFormat
str fontTools.ttLib.woff2.woff2UnknownTagFormat
Initial value:
=  """
        > # big endian
        tag: 4s  # 4-byte tag (optional)
"""
Definition at line 598 of file woff2.py.
woff2UnknownTagIndex
int fontTools.ttLib.woff2.woff2UnknownTagIndex = 0x3F
Definition at line 605 of file woff2.py.
woff2UnknownTagSize
fontTools.ttLib.woff2.woff2UnknownTagSize = sstruct.calcsize(woff2UnknownTagFormat)
Definition at line 603 of file woff2.py.