Code Cloning Analysis: pyparsing.diagram Namespace Reference
pyparsing.diagram Namespace Reference
Classes
class AnnotatedItem
class ConverterState
class EachItem
class EditablePartial
class ElementState
class NamedDiagram
Functions
str _make_bookmark (str s)
str _collapse_verbose_regex (str regex_str)
str railroad_to_html (list[NamedDiagram] diagrams, embed=False, **kwargs)
T resolve_partial (EditablePartial[T] partial)
list[NamedDiagram] to_railroad (pyparsing.ParserElement element, typing.Optional[dict] diagram_kwargs=None, int vertical=3, bool show_results_names=False, bool show_groups=False, bool show_hidden=False)
bool _should_vertical (int specification, Iterable[pyparsing.ParserElement] exprs)
bool _worth_extracting (pyparsing.ParserElement element)
_apply_diagram_item_enhancements (fn)
_visible_exprs (Iterable[pyparsing.ParserElement] exprs)
typing.Optional[EditablePartial] _to_diagram_element (pyparsing.ParserElement element, typing.Optional[EditablePartial] parent, ConverterState lookup=None, int vertical=None, int index=0, str name_hint=None, bool show_results_names=False, bool show_groups=False, bool show_hidden=False)
Variables
str jinja2_template_source
template = Template(jinja2_template_source)
dict _bookmark_lookup = {}
_bookmark_ids = itertools.count(start=1)
T = TypeVar("T")
Function Documentation
_apply_diagram_item_enhancements()
pyparsing.diagram._apply_diagram_item_enhancements (fn) protected
decorator to ensure enhancements to a diagram item (such as results name annotations)
get applied on return from _to_diagram_element (we do this since there are several
returns in _to_diagram_element)
Definition at line 444 of file __init__.py.
_collapse_verbose_regex()
str pyparsing.diagram._collapse_verbose_regex (str regex_str) protected
Definition at line 85 of file __init__.py.
_make_bookmark()
str pyparsing.diagram._make_bookmark (str s) protected
Converts a string into a valid HTML bookmark (ID or anchor name).
Definition at line 63 of file __init__.py.
_should_vertical()
bool pyparsing.diagram._should_vertical (int specification, Iterable[pyparsing.ParserElement] exprs) protected
Returns true if we should return a vertical list of elements
Definition at line 285 of file __init__.py.
Referenced by _to_diagram_element().
_to_diagram_element()
typing.Optional[EditablePartial] pyparsing.diagram._to_diagram_element (pyparsing.ParserElement element, typing.Optional[EditablePartial] parent, ConverterState lookup = None, int vertical = None, int index = 0, str name_hint = None, bool show_results_names = False, bool show_groups = False, bool show_hidden = False) protected
Recursively converts a PyParsing Element to a railroad Element
:param lookup: The shared converter state that keeps track of useful things
:param index: The index of this element within the parent
:param parent: The parent of this element in the output tree
:param vertical: Controls at what point we make a list of elements vertical. If this is an integer (the default),
it sets the threshold of the number of items before we go vertical. If True, always go vertical, if False, never
do so
:param name_hint: If provided, this will override the generated name
:param show_results_names: bool flag indicating whether to add annotations for results names
:param show_groups: bool flag indicating whether to show groups using bounding box
:param show_hidden: bool flag indicating whether to show elements that are typically hidden
:returns: The converted version of the input element, but as a Partial that hasn't yet been constructed
Definition at line 505 of file __init__.py.
References _should_vertical(), _to_diagram_element(), and _worth_extracting().
Referenced by _to_diagram_element(), and to_railroad().
_visible_exprs()
pyparsing.diagram._visible_exprs (Iterable[pyparsing.ParserElement] exprs) protected
Definition at line 491 of file __init__.py.
_worth_extracting()
bool pyparsing.diagram._worth_extracting (pyparsing.ParserElement element) protected
Returns true if this element is worth having its own sub-diagram. Simply, if any of its children
themselves have children, then its complex enough to extract
Definition at line 435 of file __init__.py.
Referenced by _to_diagram_element(), and pyparsing.diagram.ElementState.mark_for_extraction().
railroad_to_html()
str pyparsing.diagram.railroad_to_html (list[NamedDiagram] diagrams, embed = False, ** kwargs)
Given a list of NamedDiagram, produce a single HTML string that visualises those diagrams
:params kwargs: kwargs to be passed in to the template
Definition at line 180 of file __init__.py.
resolve_partial()
T pyparsing.diagram.resolve_partial (EditablePartial[T] partial)
Recursively resolves a collection of Partials into whatever type they are
Definition at line 207 of file __init__.py.
References resolve_partial().
Referenced by resolve_partial(), and to_railroad().
to_railroad()
list[NamedDiagram] pyparsing.diagram.to_railroad (pyparsing.ParserElement element, typing.Optional[dict] diagram_kwargs = None, int vertical = 3, bool show_results_names = False, bool show_groups = False, bool show_hidden = False)
Convert a pyparsing element tree into a list of diagrams. This is the recommended entrypoint to diagram
creation if you want to access the Railroad tree before it is converted to HTML
:param element: base element of the parser being diagrammed
:param diagram_kwargs: kwargs to pass to the Diagram() constructor
:param vertical: (optional) - int - limit at which number of alternatives should be
   shown vertically instead of horizontally
:param show_results_names - bool to indicate whether results name annotations should be
   included in the diagram
:param show_groups - bool to indicate whether groups should be highlighted with an unlabeled
   surrounding box
:param show_hidden - bool to indicate whether internal elements that are typically hidden
   should be shown
Definition at line 223 of file __init__.py.
References _to_diagram_element(), and resolve_partial().
Variable Documentation
_bookmark_ids
pyparsing.diagram._bookmark_ids = itertools.count(start=1) protected
Definition at line 61 of file __init__.py.
_bookmark_lookup
dict pyparsing.diagram._bookmark_lookup = {} protected
Definition at line 60 of file __init__.py.
jinja2_template_source
str pyparsing.diagram.jinja2_template_source
Definition at line 21 of file __init__.py.
T
pyparsing.diagram.T = TypeVar("T")
Definition at line 109 of file __init__.py.
template
pyparsing.diagram.template = Template(jinja2_template_source)
Definition at line 57 of file __init__.py.