Code Cloning Analysis: matplotlib.bezier Namespace Reference
matplotlib.bezier Namespace Reference
Classes
class BezierSegment
class NonIntersectingPathException
Functions
_comb (n, k)
get_intersection (cx1, cy1, cos_t1, sin_t1, cx2, cy2, cos_t2, sin_t2)
get_normal_points (cx, cy, cos_t, sin_t, length)
_de_casteljau1 (beta, t)
split_de_casteljau (beta, t)
find_bezier_t_intersecting_with_closedpath (bezier_point_at_t, inside_closedpath, t0=0., t1=1., tolerance=0.01)
split_bezier_intersecting_with_closedpath (bezier, inside_closedpath, tolerance=0.01)
split_path_inout (path, inside, tolerance=0.01, reorder_inout=False)
inside_circle (cx, cy, r)
get_cos_sin (x0, y0, x1, y1)
check_if_parallel (dx1, dy1, dx2, dy2, tolerance=1.e-5)
get_parallels (bezier2, width)
find_control_points (c1x, c1y, mmx, mmy, c2x, c2y)
make_wedged_bezier2 (bezier2, width, w1=1., wm=0.5, w2=0.)
Detailed Description
A module providing some utility functions regarding Bézier path manipulation.
Function Documentation
_comb()
matplotlib.bezier._comb (n, k) protected
Definition at line 17 of file bezier.py.
_de_casteljau1()
matplotlib.bezier._de_casteljau1 (beta, t) protected
Definition at line 90 of file bezier.py.
check_if_parallel()
matplotlib.bezier.check_if_parallel (dx1, dy1, dx2, dy2, tolerance = 1.e-5)
Check if two lines are parallel.
Parameters
----------
dx1, dy1, dx2, dy2 : float
    The gradients *dy*/*dx* of the two lines.
tolerance : float
    The angular tolerance in radians up to which the lines are considered
    parallel.
Returns
-------
is_parallel
    - 1 if two lines are parallel in same direction.
    - -1 if two lines are parallel in opposite direction.
    - False otherwise.
Definition at line 440 of file bezier.py.
Referenced by get_parallels().
find_bezier_t_intersecting_with_closedpath()
matplotlib.bezier.find_bezier_t_intersecting_with_closedpath (bezier_point_at_t, inside_closedpath, t0 = 0., t1 = 1., tolerance = 0.01)
Find the intersection of the Bézier curve with a closed path.
The intersection point *t* is approximated by two parameters *t0*, *t1*
such that *t0* <= *t* <= *t1*.
Search starts from *t0* and *t1* and uses a simple bisecting algorithm
therefore one of the end points must be inside the path while the other
doesn't. The search stops when the distance of the points parametrized by
*t0* and *t1* gets smaller than the given *tolerance*.
Parameters
----------
bezier_point_at_t : callable
    A function returning x, y coordinates of the Bézier at parameter *t*.
    It must have the signature::
        bezier_point_at_t(t: float) -> tuple[float, float]
inside_closedpath : callable
    A function returning True if a given point (x, y) is inside the
    closed path. It must have the signature::
        inside_closedpath(point: tuple[float, float]) -> bool
t0, t1 : float
    Start parameters for the search.
tolerance : float
    Maximal allowed distance between the final points.
Returns
-------
t0, t1 : float
    The Bézier path parameters.
Definition at line 113 of file bezier.py.
Referenced by split_bezier_intersecting_with_closedpath().
find_control_points()
matplotlib.bezier.find_control_points (c1x, c1y, mmx, mmy, c2x, c2y)
Find control points of the Bézier curve passing through (*c1x*, *c1y*),
(*mmx*, *mmy*), and (*c2x*, *c2y*), at parametric values 0, 0.5, and 1.
Definition at line 544 of file bezier.py.
Referenced by make_wedged_bezier2().
get_cos_sin()
matplotlib.bezier.get_cos_sin (x0, y0, x1, y1)
Definition at line 431 of file bezier.py.
get_intersection()
matplotlib.bezier.get_intersection (cx1, cy1, cos_t1, sin_t1, cx2, cy2, cos_t2, sin_t2)
Return the intersection between the line through (*cx1*, *cy1*) at angle
*t1* and the line through (*cx2*, *cy2*) at angle *t2*.
Definition at line 32 of file bezier.py.
Referenced by get_parallels().
get_normal_points()
matplotlib.bezier.get_normal_points (cx, cy, cos_t, sin_t, length)
For a line passing through (*cx*, *cy*) and having an angle *t*, return
locations of the two points located along its perpendicular line at the
distance of *length*.
Definition at line 65 of file bezier.py.
Referenced by get_parallels(), and make_wedged_bezier2().
get_parallels()
matplotlib.bezier.get_parallels (bezier2, width)
Given the quadratic Bézier control points *bezier2*, returns
control points of quadratic Bézier lines roughly parallel to given
one separated by *width*.
Definition at line 470 of file bezier.py.
References check_if_parallel(), get_intersection(), and get_normal_points().
inside_circle()
matplotlib.bezier.inside_circle (cx, cy, r)
Return a function that checks whether a point is in a circle with center
(*cx*, *cy*) and radius *r*.
The returned function has the signature::
    f(xy: tuple[float, float]) -> bool
Definition at line 412 of file bezier.py.
make_wedged_bezier2()
matplotlib.bezier.make_wedged_bezier2 (bezier2, width, w1 = 1., wm = 0.5, w2 = 0.)
Being similar to `get_parallels`, returns control points of two quadratic
Bézier lines having a width roughly parallel to given one separated by
*width*.
Definition at line 554 of file bezier.py.
References find_control_points(), and get_normal_points().
split_bezier_intersecting_with_closedpath()
matplotlib.bezier.split_bezier_intersecting_with_closedpath (bezier, inside_closedpath, tolerance = 0.01)
Split a Bézier curve into two at the intersection with a closed path.
Parameters
----------
bezier : (N, 2) array-like
    Control points of the Bézier segment. See `.BezierSegment`.
inside_closedpath : callable
    A function returning True if a given point (x, y) is inside the
    closed path. See also `.find_bezier_t_intersecting_with_closedpath`.
tolerance : float
    The tolerance for the intersection. See also
    `.find_bezier_t_intersecting_with_closedpath`.
Returns
-------
left, right
    Lists of control points for the two Bézier segments.
Definition at line 316 of file bezier.py.
References find_bezier_t_intersecting_with_closedpath(), and split_de_casteljau().
Referenced by split_path_inout().
split_de_casteljau()
matplotlib.bezier.split_de_casteljau (beta, t)
Split a Bézier segment defined by its control points *beta* into two
separate segments divided at *t* and return their control points.
Definition at line 95 of file bezier.py.
Referenced by split_bezier_intersecting_with_closedpath().
split_path_inout()
matplotlib.bezier.split_path_inout (path, inside, tolerance = 0.01, reorder_inout = False)
Divide a path into two segments at the point where ``inside(x, y)`` becomes
False.
Definition at line 351 of file bezier.py.
References split_bezier_intersecting_with_closedpath().