Code Cloning Analysis: numpy.f2py.symbolic Namespace Reference
numpy.f2py.symbolic Namespace Reference
Classes
class _FromStringWorker
class _Pair
class ArithOp
class Expr
class ExprWarning
class Language
class Op
class OpError
class Precedence
class RelOp
Functions
_pairs_add (d, k, v)
ewarn (message)
normalize (obj)
as_expr (obj)
as_symbol (obj)
as_number (obj, kind=4)
as_integer (obj, kind=4)
as_real (obj, kind=4)
as_string (obj, kind=1)
as_array (obj)
as_complex (real, imag=0)
as_apply (func, *args, **kwargs)
as_ternary (cond, expr1, expr2)
as_ref (expr)
as_deref (expr)
as_eq (left, right)
as_ne (left, right)
as_lt (left, right)
as_le (left, right)
as_gt (left, right)
as_ge (left, right)
as_terms (obj)
as_factors (obj)
as_term_coeff (obj)
as_numer_denom (obj)
_counter ()
eliminate_quotes (s)
insert_quotes (s, d)
replace_parenthesis (s)
_get_parenthesis_kind (s)
unreplace_parenthesis (s, d)
fromstring (s, language=Language.C)
Variables
list __all__ = ['Expr']
tuple integer_types = (int,)
tuple number_types = (int, float)
COUNTER = _counter()
Detailed Description
Fortran/C symbolic expressions
References:
- J3/21-007: Draft Fortran 202x. https://j3-fortran.org/doc/year/21/21-007.pdf
Copyright 1999 -- 2011 Pearu Peterson all rights reserved.
Copyright 2011 -- present NumPy Developers.
Permission to use, modify, and distribute this software is given under the
terms of the NumPy License.
NO WARRANTY IS EXPRESSED OR IMPLIED.  USE AT YOUR OWN RISK.
Function Documentation
_counter()
numpy.f2py.symbolic._counter () protected
Definition at line 1161 of file symbolic.py.
_get_parenthesis_kind()
numpy.f2py.symbolic._get_parenthesis_kind (s) protected
Definition at line 1255 of file symbolic.py.
_pairs_add()
numpy.f2py.symbolic._pairs_add (d, k, v) protected
Definition at line 136 of file symbolic.py.
as_apply()
numpy.f2py.symbolic.as_apply (func, * args, ** kwargs)
Return object as APPLY expression (function call, constructor, etc.)
Definition at line 1009 of file symbolic.py.
References as_expr().
Referenced by as_term_coeff(), normalize(), numpy.f2py.symbolic._FromStringWorker.process(), and numpy.f2py.symbolic.Expr.tostring().
as_array()
numpy.f2py.symbolic.as_array (obj)
Return object as ARRAY expression (array constant).
Definition at line 995 of file symbolic.py.
Referenced by numpy.f2py.symbolic._FromStringWorker.process(), and numpy.f2py.symbolic.Expr.substitute().
as_complex()
numpy.f2py.symbolic.as_complex (real, imag = 0)
Return object as COMPLEX expression (complex literal constant).
Definition at line 1003 of file symbolic.py.
References as_expr().
Referenced by as_expr(), numpy.f2py.symbolic._FromStringWorker.process(), and numpy.f2py.symbolic.Expr.tostring().
as_deref()
numpy.f2py.symbolic.as_deref (expr)
Return object as dereferencing expression.
Definition at line 1029 of file symbolic.py.
as_eq()
numpy.f2py.symbolic.as_eq (left, right)
Definition at line 1035 of file symbolic.py.
as_expr()
numpy.f2py.symbolic.as_expr (obj)
Convert non-Expr objects to Expr objects.
Definition at line 928 of file symbolic.py.
References as_complex(), as_number(), and as_string().
Referenced by as_apply(), as_complex(), and numpy.f2py.symbolic.Expr.tostring().
as_factors()
numpy.f2py.symbolic.as_factors (obj)
Return expression as FACTORS expression.
Definition at line 1074 of file symbolic.py.
References normalize().
Referenced by normalize(), and numpy.f2py.symbolic.Expr.tostring().
as_ge()
numpy.f2py.symbolic.as_ge (left, right)
Definition at line 1055 of file symbolic.py.
as_gt()
numpy.f2py.symbolic.as_gt (left, right)
Definition at line 1051 of file symbolic.py.
as_integer()
numpy.f2py.symbolic.as_integer (obj, kind = 4)
Return object as INTEGER constant.
Definition at line 963 of file symbolic.py.
Referenced by as_term_coeff(), as_terms(), and numpy.f2py.symbolic._FromStringWorker.process().
as_le()
numpy.f2py.symbolic.as_le (left, right)
Definition at line 1047 of file symbolic.py.
as_lt()
numpy.f2py.symbolic.as_lt (left, right)
Definition at line 1043 of file symbolic.py.
as_ne()
numpy.f2py.symbolic.as_ne (left, right)
Definition at line 1039 of file symbolic.py.
as_number()
numpy.f2py.symbolic.as_number (obj, kind = 4)
Return object as INTEGER or REAL constant.
Definition at line 950 of file symbolic.py.
Referenced by as_expr(), as_numer_denom(), numpy.f2py.symbolic.Expr.linear_solve(), normalize(), numpy.f2py.symbolic.Expr.substitute(), and numpy.f2py.symbolic.Expr.tostring().
as_numer_denom()
numpy.f2py.symbolic.as_numer_denom (obj)
Return expression as numer-denom pair.
Definition at line 1116 of file symbolic.py.
References as_number(), as_numer_denom(), and normalize().
Referenced by as_numer_denom(), and numpy.f2py.symbolic.Expr.linear_solve().
as_real()
numpy.f2py.symbolic.as_real (obj, kind = 4)
Return object as REAL constant.
Definition at line 974 of file symbolic.py.
Referenced by as_term_coeff(), as_terms(), numpy.f2py.symbolic._FromStringWorker.process(), and numpy.f2py.symbolic.Expr.tostring().
as_ref()
numpy.f2py.symbolic.as_ref (expr)
Return object as referencing expression.
Definition at line 1023 of file symbolic.py.
as_string()
numpy.f2py.symbolic.as_string (obj, kind = 1)
Return object as STRING expression (string literal constant).
Definition at line 989 of file symbolic.py.
Referenced by as_expr(), normalize(), and numpy.f2py.symbolic._FromStringWorker.process().
as_symbol()
numpy.f2py.symbolic.as_symbol (obj)
Return object as SYMBOL expression (variable or unparsed expression).
Definition at line 944 of file symbolic.py.
Referenced by numpy.f2py.symbolic._FromStringWorker.process().
as_term_coeff()
numpy.f2py.symbolic.as_term_coeff (obj)
Return expression as term-coefficient pair.
Definition at line 1095 of file symbolic.py.
References as_apply(), as_integer(), as_real(), as_term_coeff(), and normalize().
Referenced by as_term_coeff(), and normalize().
as_terms()
numpy.f2py.symbolic.as_terms (obj)
Return expression as TERMS expression.
Definition at line 1059 of file symbolic.py.
References as_integer(), as_real(), and normalize().
Referenced by numpy.f2py.symbolic.Expr.tostring().
as_ternary()
numpy.f2py.symbolic.as_ternary (cond, expr1, expr2)
Return object as TERNARY expression (cond?expr1:expr2).
Definition at line 1017 of file symbolic.py.
Referenced by numpy.f2py.symbolic._FromStringWorker.process().
eliminate_quotes()
numpy.f2py.symbolic.eliminate_quotes (s)
Replace quoted substrings of input string.
Return a new string and a mapping of replacements.
Definition at line 1172 of file symbolic.py.
ewarn()
numpy.f2py.symbolic.ewarn (message)
Definition at line 153 of file symbolic.py.
fromstring()
numpy.f2py.symbolic.fromstring (s, language = Language.C)
Create an expression from a string.
This is a "lazy" parser, that is, only arithmetic operations are
resolved, non-arithmetic operations are treated as symbols.
Definition at line 1271 of file symbolic.py.
Referenced by numpy.f2py.symbolic.Expr.parse().
insert_quotes()
numpy.f2py.symbolic.insert_quotes (s, d)
Inverse of eliminate_quotes.
Definition at line 1201 of file symbolic.py.
normalize()
numpy.f2py.symbolic.normalize (obj)
Normalize Expr and apply basic evaluation methods.
Definition at line 791 of file symbolic.py.
References as_apply(), as_factors(), as_number(), as_string(), as_term_coeff(), numpy.core.fromnumeric.max(), and normalize().
Referenced by as_factors(), as_numer_denom(), as_term_coeff(), as_terms(), normalize(), numpy.f2py.symbolic.Expr.substitute(), numpy.f2py.symbolic.Expr.tostring(), and numpy.f2py.symbolic.Expr.traverse().
replace_parenthesis()
numpy.f2py.symbolic.replace_parenthesis (s)
Replace substrings of input that are enclosed in parenthesis.
Return a new string and a mapping of replacements.
Definition at line 1212 of file symbolic.py.
References replace_parenthesis().
Referenced by numpy.f2py.symbolic._FromStringWorker.process(), and replace_parenthesis().
unreplace_parenthesis()
numpy.f2py.symbolic.unreplace_parenthesis (s, d)
Inverse of replace_parenthesis.
Definition at line 1260 of file symbolic.py.
Referenced by numpy.f2py.symbolic._FromStringWorker.process().
Variable Documentation
__all__
list numpy.f2py.symbolic.__all__ = ['Expr'] private
Definition at line 27 of file symbolic.py.
COUNTER
numpy.f2py.symbolic.COUNTER = _counter()
Definition at line 1169 of file symbolic.py.
integer_types
tuple numpy.f2py.symbolic.integer_types = (int,)
Definition at line 132 of file symbolic.py.
number_types
tuple numpy.f2py.symbolic.number_types = (int, float)
Definition at line 133 of file symbolic.py.