Code Cloning Analysis: numpy.core.tests.test_dtype Namespace Reference
numpy.core.tests.test_dtype Namespace Reference
Classes
class TestBuiltin
class TestClassGetItem
class TestDtypeAttributeDeletion
class TestDtypeAttributes
class TestDTypeClasses
class TestDTypeMakeCanonical
class TestFromCTypes
class TestFromDTypeAttribute
class TestMetadata
class TestMonsterType
class TestPickling
class TestPromotion
class TestRecord
class TestString
class TestStructuredDtypeSparseFields
class TestStructuredObjectRefcounting
class TestSubarray
class TestUserDType
Functions
assert_dtype_equal (a, b)
assert_dtype_not_equal (a, b)
iter_struct_object_dtypes ()
test_rational_dtype ()
test_dtypes_are_true ()
test_invalid_dtype_string ()
test_keyword_argument ()
test_ulong_dtype ()
test_result_type_integers_and_unitless_timedelta64 ()
test_creating_dtype_with_dtype_class_errors ()
Function Documentation
assert_dtype_equal()
numpy.core.tests.test_dtype.assert_dtype_equal (a, b)
Definition at line 25 of file test_dtype.py.
assert_dtype_not_equal()
numpy.core.tests.test_dtype.assert_dtype_not_equal (a, b)
Definition at line 30 of file test_dtype.py.
iter_struct_object_dtypes()
numpy.core.tests.test_dtype.iter_struct_object_dtypes ()
Iterates over a few complex dtypes and object pattern which
fill the array with a given object (defaults to a singleton).
Yields
------
dtype : dtype
pattern : tuple
    Structured tuple for use with `np.array`.
count : int
    Number of objects stored in the dtype.
singleton : object
    A singleton object. The returned pattern is constructed so that
    all objects inside the datatype are set to the singleton.
Definition at line 722 of file test_dtype.py.
Referenced by numpy.core.tests.test_dtype.TestStructuredObjectRefcounting.test_structured_object_create_delete(), numpy.core.tests.test_dtype.TestStructuredObjectRefcounting.test_structured_object_indexing(), and numpy.core.tests.test_dtype.TestStructuredObjectRefcounting.test_structured_object_item_setting().
test_creating_dtype_with_dtype_class_errors()
numpy.core.tests.test_dtype.test_creating_dtype_with_dtype_class_errors ()
Definition at line 1903 of file test_dtype.py.
test_dtypes_are_true()
numpy.core.tests.test_dtype.test_dtypes_are_true ()
Definition at line 1495 of file test_dtype.py.
test_invalid_dtype_string()
numpy.core.tests.test_dtype.test_invalid_dtype_string ()
Definition at line 1502 of file test_dtype.py.
test_keyword_argument()
numpy.core.tests.test_dtype.test_keyword_argument ()
Definition at line 1508 of file test_dtype.py.
test_rational_dtype()
numpy.core.tests.test_dtype.test_rational_dtype ()
Definition at line 1485 of file test_dtype.py.
test_result_type_integers_and_unitless_timedelta64()
numpy.core.tests.test_dtype.test_result_type_integers_and_unitless_timedelta64 ()
Definition at line 1895 of file test_dtype.py.
test_ulong_dtype()
numpy.core.tests.test_dtype.test_ulong_dtype ()
Definition at line 1513 of file test_dtype.py.