Code Cloning Analysis: scipy.signal.tests.test_fir_filter_design.TestFirwin Class Reference
scipy.signal.tests.test_fir_filter_design.TestFirwin Class Reference
Public Member Functions
check_response (self, h, expected_response, tol=.05)
test_response (self)
mse (self, h, bands)
test_scaling (self)
Detailed Description
Definition at line 38 of file test_fir_filter_design.py.
Member Function Documentation
check_response()
scipy.signal.tests.test_fir_filter_design.TestFirwin.check_response (self, h, expected_response, tol = .05)
Definition at line 40 of file test_fir_filter_design.py.
Referenced by test_scaling().
mse()
scipy.signal.tests.test_fir_filter_design.TestFirwin.mse (self, h, bands)
Compute mean squared error versus ideal response across frequency
band.
  h -- coefficients
  bands -- list of (left, right) tuples relative to 1==Nyquist of
    passbands
Definition at line 82 of file test_fir_filter_design.py.
References scipy.signal._filter_design.freqz().
Referenced by test_scaling().
test_response()
scipy.signal.tests.test_fir_filter_design.TestFirwin.test_response (self)
Definition at line 50 of file test_fir_filter_design.py.
test_scaling()
scipy.signal.tests.test_fir_filter_design.TestFirwin.test_scaling (self)
For one lowpass, bandpass, and highpass example filter, this test
checks two things:
  - the mean squared error over the frequency domain of the unscaled
    filter is smaller than the scaled filter (true for rectangular
    window)
  - the response of the scaled filter is exactly unity at the center
    of the first passband
Definition at line 98 of file test_fir_filter_design.py.
References check_response(), scipy.signal._fir_filter_design.firwin(), and mse().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/signal/tests/test_fir_filter_design.py