Code Cloning Analysis: scipy.stats._mstats_extras Namespace Reference
scipy.stats._mstats_extras Namespace Reference
Functions
hdquantiles (data, prob=list([.25,.5,.75]), axis=None, var=False)
hdmedian (data, axis=-1, var=False)
hdquantiles_sd (data, prob=list([.25,.5,.75]), axis=None)
trimmed_mean_ci (data, limits=(0.2, 0.2), inclusive=(True, True), alpha=0.05, axis=None)
mjci (data, prob=[0.25, 0.5, 0.75], axis=None)
mquantiles_cimj (data, prob=[0.25, 0.50, 0.75], alpha=0.05, axis=None)
median_cihs (data, alpha=0.05, axis=None)
compare_medians_ms (group_1, group_2, axis=None)
idealfourths (data, axis=None)
rsh (data, points=None)
Variables
list __all__
Detailed Description
Additional statistics functions with support for masked arrays.
Function Documentation
compare_medians_ms()
scipy.stats._mstats_extras.compare_medians_ms (group_1, group_2, axis = None)
Compares the medians from two independent groups along the given axis.
The comparison is performed using the McKean-Schrader estimate of the
standard error of the medians.
Parameters
----------
group_1 : array_like
    First dataset.  Has to be of size >=7.
group_2 : array_like
    Second dataset.  Has to be of size >=7.
axis : int, optional
    Axis along which the medians are estimated. If None, the arrays are
    flattened.  If `axis` is not None, then `group_1` and `group_2`
    should have the same shape.
Returns
-------
compare_medians_ms : {float, ndarray}
    If `axis` is None, then returns a float, otherwise returns a 1-D
    ndarray of floats with a length equal to the length of `group_1`
    along `axis`.
Examples
--------
>>> from scipy import stats
>>> a = [1, 2, 3, 4, 5, 6, 7]
>>> b = [8, 9, 10, 11, 12, 13, 14]
>>> stats.mstats.compare_medians_ms(a, b, axis=None)
1.0693225866553746e-05
The function is vectorized to compute along a given axis.
>>> import numpy as np
>>> rng = np.random.default_rng()
>>> x = rng.random(size=(3, 7))
>>> y = rng.random(size=(3, 8))
>>> stats.mstats.compare_medians_ms(x, y, axis=1)
array([0.36908985, 0.36092538, 0.2765313 ])
References
----------
.. [1] McKean, Joseph W., and Ronald M. Schrader. "A comparison of methods
   for studentizing the sample median." Communications in
   Statistics-Simulation and Computation 13.6 (1984): 751-773.
Definition at line 373 of file _mstats_extras.py.
hdmedian()
scipy.stats._mstats_extras.hdmedian (data, axis = -1, var = False)
Returns the Harrell-Davis estimate of the median along the given axis.
Parameters
----------
data : ndarray
    Data array.
axis : int, optional
    Axis along which to compute the quantiles. If None, use a flattened
    array.
var : bool, optional
    Whether to return the variance of the estimate.
Returns
-------
hdmedian : MaskedArray
    The median values.  If ``var=True``, the variance is returned inside
    the masked array.  E.g. for a 1-D array the shape change from (1,) to
    (2,).
Definition at line 103 of file _mstats_extras.py.
References hdquantiles().
hdquantiles()
scipy.stats._mstats_extras.hdquantiles (data, prob = list([.25,.5,.75]), axis = None, var = False)
Computes quantile estimates with the Harrell-Davis method.
The quantile estimates are calculated as a weighted linear combination
of order statistics.
Parameters
----------
data : array_like
    Data array.
prob : sequence, optional
    Sequence of quantiles to compute.
axis : int or None, optional
    Axis along which to compute the quantiles. If None, use a flattened
    array.
var : bool, optional
    Whether to return the variance of the estimate.
Returns
-------
hdquantiles : MaskedArray
    A (p,) array of quantiles (if `var` is False), or a (2,p) array of
    quantiles and variances (if `var` is True), where ``p`` is the
    number of quantiles.
See Also
--------
hdquantiles_sd
Definition at line 28 of file _mstats_extras.py.
Referenced by hdmedian().
hdquantiles_sd()
scipy.stats._mstats_extras.hdquantiles_sd (data, prob = list([.25,.5,.75]), axis = None)
The standard error of the Harrell-Davis quantile estimates by jackknife.
Parameters
----------
data : array_like
    Data array.
prob : sequence, optional
    Sequence of quantiles to compute.
axis : int, optional
    Axis along which to compute the quantiles. If None, use a flattened
    array.
Returns
-------
hdquantiles_sd : MaskedArray
    Standard error of the Harrell-Davis quantile estimates.
See Also
--------
hdquantiles
Definition at line 129 of file _mstats_extras.py.
idealfourths()
scipy.stats._mstats_extras.idealfourths (data, axis = None)
Returns an estimate of the lower and upper quartiles.
Uses the ideal fourths algorithm.
Parameters
----------
data : array_like
    Input array.
axis : int, optional
    Axis along which the quartiles are estimated. If None, the arrays are
    flattened.
Returns
-------
idealfourths : {list of floats, masked array}
    Returns the two internal values that divide `data` into four parts
    using the ideal fourths algorithm either along the flattened array
    (if `axis` is None) or along `axis` of `data`.
Definition at line 430 of file _mstats_extras.py.
Referenced by rsh().
median_cihs()
scipy.stats._mstats_extras.median_cihs (data, alpha = 0.05, axis = None)
Computes the alpha-level confidence interval for the median of the data.
Uses the Hettmasperger-Sheather method.
Parameters
----------
data : array_like
    Input data. Masked values are discarded. The input should be 1D only,
    or `axis` should be set to None.
alpha : float, optional
    Confidence level of the intervals.
axis : int or None, optional
    Axis along which to compute the quantiles. If None, use a flattened
    array.
Returns
-------
median_cihs
    Alpha level confidence interval.
Definition at line 322 of file _mstats_extras.py.
mjci()
scipy.stats._mstats_extras.mjci (data, prob = [0.25,0.5,0.75], axis = None)
Returns the Maritz-Jarrett estimators of the standard error of selected
experimental quantiles of the data.
Parameters
----------
data : ndarray
    Data array.
prob : sequence, optional
    Sequence of quantiles to compute.
axis : int or None, optional
    Axis along which to compute the quantiles. If None, use a flattened
    array.
Definition at line 243 of file _mstats_extras.py.
Referenced by mquantiles_cimj().
mquantiles_cimj()
scipy.stats._mstats_extras.mquantiles_cimj (data, prob = [0.25,0.50,0.75], alpha = 0.05, axis = None)
Computes the alpha confidence interval for the selected quantiles of the
data, with Maritz-Jarrett estimators.
Parameters
----------
data : ndarray
    Data array.
prob : sequence, optional
    Sequence of quantiles to compute.
alpha : float, optional
    Confidence level of the intervals.
axis : int or None, optional
    Axis along which to compute the quantiles.
    If None, use a flattened array.
Returns
-------
ci_lower : ndarray
    The lower boundaries of the confidence interval.  Of the same length as
    `prob`.
ci_upper : ndarray
    The upper boundaries of the confidence interval.  Of the same length as
    `prob`.
Definition at line 288 of file _mstats_extras.py.
References mjci().
rsh()
scipy.stats._mstats_extras.rsh (data, points = None)
Evaluates Rosenblatt's shifted histogram estimators for each data point.
Rosenblatt's estimator is a centered finite-difference approximation to the
derivative of the empirical cumulative distribution function.
Parameters
----------
data : sequence
    Input data, should be 1-D. Masked values are ignored.
points : sequence or None, optional
    Sequence of points where to evaluate Rosenblatt shifted histogram.
    If None, use the data.
Definition at line 470 of file _mstats_extras.py.
References idealfourths().
trimmed_mean_ci()
scipy.stats._mstats_extras.trimmed_mean_ci (data, limits = (0.2,0.2), inclusive = (True,True), alpha = 0.05, axis = None)
Selected confidence interval of the trimmed mean along the given axis.
Parameters
----------
data : array_like
    Input data.
limits : {None, tuple}, optional
    None or a two item tuple.
    Tuple of the percentages to cut on each side of the array, with respect
    to the number of unmasked data, as floats between 0. and 1. If ``n``
    is the number of unmasked data before trimming, then
    (``n * limits[0]``)th smallest data and (``n * limits[1]``)th
    largest data are masked.  The total number of unmasked data after
    trimming is ``n * (1. - sum(limits))``.
    The value of one limit can be set to None to indicate an open interval.
    Defaults to (0.2, 0.2).
inclusive : (2,) tuple of boolean, optional
    If relative==False, tuple indicating whether values exactly equal to
    the absolute limits are allowed.
    If relative==True, tuple indicating whether the number of data being
    masked on each side should be rounded (True) or truncated (False).
    Defaults to (True, True).
alpha : float, optional
    Confidence level of the intervals.
    Defaults to 0.05.
axis : int, optional
    Axis along which to cut. If None, uses a flattened version of `data`.
    Defaults to None.
Returns
-------
trimmed_mean_ci : (2,) ndarray
    The lower and upper confidence intervals of the trimmed data.
Definition at line 192 of file _mstats_extras.py.
Variable Documentation
__all__
list scipy.stats._mstats_extras.__all__ private
Initial value:
=  ['compare_medians_ms',
           'hdquantiles', 'hdmedian', 'hdquantiles_sd',
           'idealfourths',
           'median_cihs','mjci','mquantiles_cimj',
           'rsh',
           'trimmed_mean_ci',]
Definition at line 9 of file _mstats_extras.py.