Code Cloning Analysis: scipy.stats._covariance.CovViaPrecision Class Reference
scipy.stats._covariance.CovViaPrecision Class Reference
Public Member Functions
__init__ (self, precision, covariance=None)
Public Member Functions inherited from scipy.stats._covariance.Covariance
__init__ (self)
whiten (self, x)
colorize (self, x)
log_pdet (self)
rank (self)
covariance (self)
shape (self)
Protected Member Functions
_whiten (self, x)
_covariance (self)
_colorize (self, x)
Protected Member Functions inherited from scipy.stats._covariance.Covariance
_validate_matrix (self, A, name)
_validate_vector (self, A, name)
Protected Attributes
_chol_P = np.linalg.cholesky(precision)
_precision = precision
_cov_matrix = covariance
_shape = precision.shape
bool _allow_singular = False
Protected Attributes inherited from scipy.stats._covariance.Covariance
_log_pdet
_rank
Additional Inherited Members
Static Public Member Functions inherited from scipy.stats._covariance.Covariance
from_diagonal (diagonal)
from_precision (precision, covariance=None)
from_cholesky (cholesky)
from_eigendecomposition (eigendecomposition)
Detailed Description
Definition at line 463 of file _covariance.py.
Constructor & Destructor Documentation
__init__()
scipy.stats._covariance.CovViaPrecision.__init__ (self, precision, covariance = None)
Definition at line 465 of file _covariance.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
_colorize()
scipy.stats._covariance.CovViaPrecision._colorize (self, x) protected
Definition at line 490 of file _covariance.py.
Referenced by scipy.stats._covariance.Covariance.colorize().
_covariance()
scipy.stats._covariance.CovViaPrecision._covariance (self) protected
Definition at line 485 of file _covariance.py.
Referenced by scipy.stats._covariance.Covariance.covariance().
_whiten()
scipy.stats._covariance.CovViaPrecision._whiten (self, x) protected
Definition at line 481 of file _covariance.py.
Referenced by scipy.stats._covariance.Covariance.whiten().
Member Data Documentation
_allow_singular
bool scipy.stats._covariance.CovViaPrecision._allow_singular = False protected
Definition at line 479 of file _covariance.py.
_chol_P
scipy.stats._covariance.CovViaPrecision._chol_P = np.linalg.cholesky(precision) protected
Definition at line 473 of file _covariance.py.
_cov_matrix
scipy.stats._covariance.CovViaPrecision._cov_matrix = covariance protected
Definition at line 477 of file _covariance.py.
_precision
scipy.stats._covariance.CovViaPrecision._precision = precision protected
Definition at line 476 of file _covariance.py.
_shape
scipy.stats._covariance.CovViaPrecision._shape = precision.shape protected
Definition at line 478 of file _covariance.py.
Referenced by pandas.util._doctools.TablePlotter._get_cells(), scipy.sparse._matrix.spmatrix.get_shape(), pandas.util._doctools.TablePlotter.plot(), and scipy.stats._covariance.Covariance.shape().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/stats/_covariance.py