Code Cloning Analysis: matplotlib.cbook._UnhashDict Class Reference
matplotlib.cbook._UnhashDict Class Reference
Public Member Functions
__init__ (self, pairs)
__setitem__ (self, key, value)
__getitem__ (self, key)
pop (self, key, *args)
__iter__ (self)
Protected Attributes
dict _dict = {}
list _pairs = []
Detailed Description
A minimal dict-like class that also supports unhashable keys, storing them
in a list of key-value pairs.
This class only implements the interface needed for `CallbackRegistry`, and
tries to minimize the overhead for the hashable case.
Definition at line 143 of file cbook.py.
Constructor & Destructor Documentation
__init__()
matplotlib.cbook._UnhashDict.__init__ (self, pairs)
Definition at line 152 of file cbook.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__getitem__()
matplotlib.cbook._UnhashDict.__getitem__ (self, key)
Definition at line 169 of file cbook.py.
__iter__()
matplotlib.cbook._UnhashDict.__iter__ (self)
Definition at line 192 of file cbook.py.
__setitem__()
matplotlib.cbook._UnhashDict.__setitem__ (self, key, value)
Definition at line 158 of file cbook.py.
pop()
matplotlib.cbook._UnhashDict.pop (self, key, * args)
Definition at line 179 of file cbook.py.
Member Data Documentation
_dict
dict matplotlib.cbook._UnhashDict._dict = {} protected
Definition at line 153 of file cbook.py.
_pairs
matplotlib.cbook._UnhashDict._pairs = [] protected
Definition at line 154 of file cbook.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/cbook.py