Code Cloning Analysis: axes_grid1.parasite_axes.ParasiteAxesBase Class Reference
axes_grid1.parasite_axes.ParasiteAxesBase Class Reference
Public Member Functions
__init__ (self, parent_axes, aux_transform=None, *, viewlim_mode=None, **kwargs)
clear (self)
pick (self, mouseevent)
set_viewlim_mode (self, mode)
get_viewlim_mode (self)
Public Attributes
transAux = aux_transform
transAxes = self._parent_axes.transAxes
transData = self.transAux + self._parent_axes.transData
Protected Member Functions
_set_lim_and_transforms (self)
_sync_lims (self, parent)
Protected Attributes
_parent_axes = parent_axes
_get_lines = self._parent_axes._get_lines
_sync_lims
_xaxis_transform
_yaxis_transform
_viewlim_mode = mode
Detailed Description
Definition at line 8 of file parasite_axes.py.
Constructor & Destructor Documentation
__init__()
axes_grid1.parasite_axes.ParasiteAxesBase.__init__ (self, parent_axes, aux_transform = None, * , viewlim_mode = None, ** kwargs)
Definition at line 10 of file parasite_axes.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_set_lim_and_transforms()
axes_grid1.parasite_axes.ParasiteAxesBase._set_lim_and_transforms (self) protected
Definition at line 42 of file parasite_axes.py.
_sync_lims()
axes_grid1.parasite_axes.ParasiteAxesBase._sync_lims (self, parent) protected
Definition at line 60 of file parasite_axes.py.
clear()
axes_grid1.parasite_axes.ParasiteAxesBase.clear (self)
Definition at line 19 of file parasite_axes.py.
Referenced by matplotlib.projections.geo.AitoffAxes.InvertedAitoffTransform.inverted(), matplotlib.projections.geo.HammerAxes.InvertedHammerTransform.inverted(), matplotlib.projections.geo.LambertAxes.InvertedLambertTransform.inverted(), and matplotlib.projections.geo.MollweideAxes.InvertedMollweideTransform.inverted().
get_viewlim_mode()
axes_grid1.parasite_axes.ParasiteAxesBase.get_viewlim_mode (self)
Definition at line 57 of file parasite_axes.py.
pick()
axes_grid1.parasite_axes.ParasiteAxesBase.pick (self, mouseevent)
Definition at line 28 of file parasite_axes.py.
set_viewlim_mode()
axes_grid1.parasite_axes.ParasiteAxesBase.set_viewlim_mode (self, mode)
Definition at line 53 of file parasite_axes.py.
Member Data Documentation
_get_lines
axes_grid1.parasite_axes.ParasiteAxesBase._get_lines = self._parent_axes._get_lines protected
Definition at line 22 of file parasite_axes.py.
Referenced by pandas.io.parsers.python_parser.PythonParser.__init__().
_parent_axes
axes_grid1.parasite_axes.ParasiteAxesBase._parent_axes = parent_axes protected
Definition at line 12 of file parasite_axes.py.
_sync_lims
axes_grid1.parasite_axes.ParasiteAxesBase._sync_lims protected
Definition at line 24 of file parasite_axes.py.
_viewlim_mode
axes_grid1.parasite_axes.ParasiteAxesBase._viewlim_mode = mode protected
Definition at line 55 of file parasite_axes.py.
_xaxis_transform
axes_grid1.parasite_axes.ParasiteAxesBase._xaxis_transform protected
Initial value:
=  mtransforms.blended_transform_factory(
                self.transData, self.transAxes)
Definition at line 46 of file parasite_axes.py.
_yaxis_transform
axes_grid1.parasite_axes.ParasiteAxesBase._yaxis_transform protected
Initial value:
=  mtransforms.blended_transform_factory(
                self.transAxes, self.transData)
Definition at line 48 of file parasite_axes.py.
transAux
axes_grid1.parasite_axes.ParasiteAxesBase.transAux = aux_transform
Definition at line 13 of file parasite_axes.py.
transAxes
axes_grid1.parasite_axes.ParasiteAxesBase.transAxes = self._parent_axes.transAxes
Definition at line 44 of file parasite_axes.py.
transData
axes_grid1.parasite_axes.ParasiteAxesBase.transData = self.transAux + self._parent_axes.transData
Definition at line 45 of file parasite_axes.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/mpl_toolkits/axes_grid1/parasite_axes.py