Code Cloning Analysis: numpy.core._add_newdocs_scalars Namespace Reference
numpy.core._add_newdocs_scalars Namespace Reference
Functions
numeric_type_aliases (aliases)
Documentation for concrete scalar classes.
_get_platform_and_machine ()
add_newdoc_for_scalar_type (obj, fixed_aliases, doc)
Variables
possible_aliases
_system
_machine
str _doc_alias_string = f":Alias on this platform ({_system} {_machine}):"
Detailed Description
This file is separate from ``_add_newdocs.py`` so that it can be mocked out by
our sphinx ``conf.py`` during doc builds, where we want to avoid showing
platform-dependent information.
Function Documentation
_get_platform_and_machine()
numpy.core._add_newdocs_scalars._get_platform_and_machine () protected
Definition at line 54 of file _add_newdocs_scalars.py.
add_newdoc_for_scalar_type()
numpy.core._add_newdocs_scalars.add_newdoc_for_scalar_type (obj, fixed_aliases, doc)
Definition at line 71 of file _add_newdocs_scalars.py.
numeric_type_aliases()
numpy.core._add_newdocs_scalars.numeric_type_aliases (aliases)
Documentation for concrete scalar classes.
Definition at line 18 of file _add_newdocs_scalars.py.
References numpy.core.function_base.add_newdoc(), and numeric_type_aliases().
Referenced by numeric_type_aliases().
Variable Documentation
_doc_alias_string
str numpy.core._add_newdocs_scalars._doc_alias_string = f":Alias on this platform ({_system} {_machine}):" protected
Definition at line 68 of file _add_newdocs_scalars.py.
_machine
numpy.core._add_newdocs_scalars._machine protected
Definition at line 67 of file _add_newdocs_scalars.py.
_system
numpy.core._add_newdocs_scalars._system protected
Definition at line 67 of file _add_newdocs_scalars.py.
possible_aliases
numpy.core._add_newdocs_scalars.possible_aliases
Initial value:
=  numeric_type_aliases([
    ('int8', '8-bit signed integer (``-128`` to ``127``)'),
    ('int16', '16-bit signed integer (``-32_768`` to ``32_767``)'),
    ('int32', '32-bit signed integer (``-2_147_483_648`` to ``2_147_483_647``)'),
    ('int64', '64-bit signed integer (``-9_223_372_036_854_775_808`` to ``9_223_372_036_854_775_807``)'),
    ('intp', 'Signed integer large enough to fit pointer, compatible with C ``intptr_t``'),
    ('uint8', '8-bit unsigned integer (``0`` to ``255``)'),
    ('uint16', '16-bit unsigned integer (``0`` to ``65_535``)'),
    ('uint32', '32-bit unsigned integer (``0`` to ``4_294_967_295``)'),
    ('uint64', '64-bit unsigned integer (``0`` to ``18_446_744_073_709_551_615``)'),
    ('uintp', 'Unsigned integer large enough to fit pointer, compatible with C ``uintptr_t``'),
    ('float16', '16-bit-precision floating-point number type: sign bit, 5 bits exponent, 10 bits mantissa'),
    ('float32', '32-bit-precision floating-point number type: sign bit, 8 bits exponent, 23 bits mantissa'),
    ('float64', '64-bit precision floating-point number type: sign bit, 11 bits exponent, 52 bits mantissa'),
    ('float96', '96-bit extended-precision floating-point number type'),
    ('float128', '128-bit extended-precision floating-point number type'),
    ('complex64', 'Complex number type composed of 2 32-bit-precision floating-point numbers'),
    ('complex128', 'Complex number type composed of 2 64-bit-precision floating-point numbers'),
    ('complex192', 'Complex number type composed of 2 96-bit extended-precision floating-point numbers'),
    ('complex256', 'Complex number type composed of 2 128-bit extended-precision floating-point numbers'),
    ])
Definition at line 31 of file _add_newdocs_scalars.py.