Code Cloning Analysis: scipy.sparse.linalg._eigen.arpack.arpack Namespace Reference
scipy.sparse.linalg._eigen.arpack.arpack Namespace Reference
Classes
class _ArpackParams
class _SymmetricArpackParams
class _UnsymmetricArpackParams
class ArpackError
class ArpackNoConvergence
class IterInv
class IterOpInv
class LuInv
class SpLuInv
Functions
choose_ncv (k)
_aslinearoperator_with_dtype (m)
gmres_loose (A, b, tol)
_fast_spmatrix_to_csc (A, hermitian=False)
get_inv_matvec (M, hermitian=False, tol=0)
get_OPinv_matvec (A, M, sigma, hermitian=False, tol=0)
eigs (A, k=6, M=None, sigma=None, which='LM', v0=None, ncv=None, maxiter=None, tol=0, return_eigenvectors=True, Minv=None, OPinv=None, OPpart=None)
eigsh (A, k=6, M=None, sigma=None, which='LM', v0=None, ncv=None, maxiter=None, tol=0, return_eigenvectors=True, Minv=None, OPinv=None, mode='normal')
Variables
arpack_int = _arpack.timing.nbx.dtype
str __docformat__ = "restructuredtext en"
list __all__ = ['eigs', 'eigsh', 'ArpackError', 'ArpackNoConvergence']
dict _type_conv = {'f': 's', 'd': 'd', 'F': 'c', 'D': 'z'}
dict _ndigits = {'f': 5, 'd': 12, 'F': 5, 'D': 12}
dict DNAUPD_ERRORS
dict SNAUPD_ERRORS = DNAUPD_ERRORS
dict ZNAUPD_ERRORS = DNAUPD_ERRORS.copy()
dict CNAUPD_ERRORS = ZNAUPD_ERRORS
dict DSAUPD_ERRORS
dict SSAUPD_ERRORS = DSAUPD_ERRORS
dict DNEUPD_ERRORS
dict SNEUPD_ERRORS = DNEUPD_ERRORS.copy()
dict ZNEUPD_ERRORS
dict CNEUPD_ERRORS = ZNEUPD_ERRORS.copy()
dict DSEUPD_ERRORS
dict SSEUPD_ERRORS = DSEUPD_ERRORS.copy()
dict _SAUPD_ERRORS
dict _NAUPD_ERRORS
dict _SEUPD_ERRORS
dict _NEUPD_ERRORS
list _SEUPD_WHICH = ['LM', 'SM', 'LA', 'SA', 'BE']
list _NEUPD_WHICH = ['LM', 'SM', 'LR', 'SR', 'LI', 'SI']
_ARPACK_LOCK
Detailed Description
Find a few eigenvectors and eigenvalues of a matrix.
Uses ARPACK: https://github.com/opencollab/arpack-ng
Function Documentation
_aslinearoperator_with_dtype()
scipy.sparse.linalg._eigen.arpack.arpack._aslinearoperator_with_dtype (m) protected
Definition at line 899 of file arpack.py.
_fast_spmatrix_to_csc()
scipy.sparse.linalg._eigen.arpack.arpack._fast_spmatrix_to_csc (A, hermitian = False) protected
Convert sparse matrix to CSC (by transposing, if possible)
Definition at line 1039 of file arpack.py.
References _fast_spmatrix_to_csc(), scipy.sparse._construct.eye(), and scipy.sparse._base.issparse().
Referenced by _fast_spmatrix_to_csc().
choose_ncv()
scipy.sparse.linalg._eigen.arpack.arpack.choose_ncv (k)
Choose number of lanczos vectors based on target number
of singular/eigen values and vectors to compute, k.
Definition at line 302 of file arpack.py.
eigs()
scipy.sparse.linalg._eigen.arpack.arpack.eigs (A, k = 6, M = None, sigma = None, which = 'LM', v0 = None, ncv = None, maxiter = None, tol = 0, return_eigenvectors = True, Minv = None, OPinv = None, OPpart = None)
Find k eigenvalues and eigenvectors of the square matrix A.
Solves ``A @ x[i] = w[i] * x[i]``, the standard eigenvalue problem
for w[i] eigenvalues with corresponding eigenvectors x[i].
If M is specified, solves ``A @ x[i] = w[i] * M @ x[i]``, the
generalized eigenvalue problem for w[i] eigenvalues
with corresponding eigenvectors x[i]
Parameters
----------
A : ndarray, sparse matrix or LinearOperator
    An array, sparse matrix, or LinearOperator representing
    the operation ``A @ x``, where A is a real or complex square matrix.
k : int, optional
    The number of eigenvalues and eigenvectors desired.
    `k` must be smaller than N-1. It is not possible to compute all
    eigenvectors of a matrix.
M : ndarray, sparse matrix or LinearOperator, optional
    An array, sparse matrix, or LinearOperator representing
    the operation M@x for the generalized eigenvalue problem
        A @ x = w * M @ x.
    M must represent a real symmetric matrix if A is real, and must
    represent a complex Hermitian matrix if A is complex. For best
    results, the data type of M should be the same as that of A.
    Additionally:
        If `sigma` is None, M is positive definite
        If sigma is specified, M is positive semi-definite
    If sigma is None, eigs requires an operator to compute the solution
    of the linear equation ``M @ x = b``.  This is done internally via a
    (sparse) LU decomposition for an explicit matrix M, or via an
    iterative solver for a general linear operator.  Alternatively,
    the user can supply the matrix or operator Minv, which gives
    ``x = Minv @ b = M^-1 @ b``.
sigma : real or complex, optional
    Find eigenvalues near sigma using shift-invert mode.  This requires
    an operator to compute the solution of the linear system
    ``[A - sigma * M] @ x = b``, where M is the identity matrix if
    unspecified. This is computed internally via a (sparse) LU
    decomposition for explicit matrices A & M, or via an iterative
    solver if either A or M is a general linear operator.
    Alternatively, the user can supply the matrix or operator OPinv,
    which gives ``x = OPinv @ b = [A - sigma * M]^-1 @ b``.
    For a real matrix A, shift-invert can either be done in imaginary
    mode or real mode, specified by the parameter OPpart ('r' or 'i').
    Note that when sigma is specified, the keyword 'which' (below)
    refers to the shifted eigenvalues ``w'[i]`` where:
        If A is real and OPpart == 'r' (default),
          ``w'[i] = 1/2 * [1/(w[i]-sigma) + 1/(w[i]-conj(sigma))]``.
        If A is real and OPpart == 'i',
          ``w'[i] = 1/2i * [1/(w[i]-sigma) - 1/(w[i]-conj(sigma))]``.
        If A is complex, ``w'[i] = 1/(w[i]-sigma)``.
v0 : ndarray, optional
    Starting vector for iteration.
    Default: random
ncv : int, optional
    The number of Lanczos vectors generated
    `ncv` must be greater than `k`; it is recommended that ``ncv > 2*k``.
    Default: ``min(n, max(2*k + 1, 20))``
which : str, ['LM' | 'SM' | 'LR' | 'SR' | 'LI' | 'SI'], optional
    Which `k` eigenvectors and eigenvalues to find:
        'LM' : largest magnitude
        'SM' : smallest magnitude
        'LR' : largest real part
        'SR' : smallest real part
        'LI' : largest imaginary part
        'SI' : smallest imaginary part
    When sigma != None, 'which' refers to the shifted eigenvalues w'[i]
    (see discussion in 'sigma', above).  ARPACK is generally better
    at finding large values than small values.  If small eigenvalues are
    desired, consider using shift-invert mode for better performance.
maxiter : int, optional
    Maximum number of Arnoldi update iterations allowed
    Default: ``n*10``
tol : float, optional
    Relative accuracy for eigenvalues (stopping criterion)
    The default value of 0 implies machine precision.
return_eigenvectors : bool, optional
    Return eigenvectors (True) in addition to eigenvalues
Minv : ndarray, sparse matrix or LinearOperator, optional
    See notes in M, above.
OPinv : ndarray, sparse matrix or LinearOperator, optional
    See notes in sigma, above.
OPpart : {'r' or 'i'}, optional
    See notes in sigma, above
Returns
-------
w : ndarray
    Array of k eigenvalues.
v : ndarray
    An array of `k` eigenvectors.
    ``v[:, i]`` is the eigenvector corresponding to the eigenvalue w[i].
Raises
------
ArpackNoConvergence
    When the requested convergence is not obtained.
    The currently converged eigenvalues and eigenvectors can be found
    as ``eigenvalues`` and ``eigenvectors`` attributes of the exception
    object.
See Also
--------
eigsh : eigenvalues and eigenvectors for symmetric matrix A
svds : singular value decomposition for a matrix A
Notes
-----
This function is a wrapper to the ARPACK [1]_ SNEUPD, DNEUPD, CNEUPD,
ZNEUPD, functions which use the Implicitly Restarted Arnoldi Method to
find the eigenvalues and eigenvectors [2]_.
References
----------
.. [1] ARPACK Software, https://github.com/opencollab/arpack-ng
.. [2] R. B. Lehoucq, D. C. Sorensen, and C. Yang,  ARPACK USERS GUIDE:
   Solution of Large Scale Eigenvalue Problems by Implicitly Restarted
   Arnoldi Methods. SIAM, Philadelphia, PA, 1998.
Examples
--------
Find 6 eigenvectors of the identity matrix:
>>> import numpy as np
>>> from scipy.sparse.linalg import eigs
>>> id = np.eye(13)
>>> vals, vecs = eigs(id, k=6)
>>> vals
array([ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j])
>>> vecs.shape
(13, 6)
Definition at line 1102 of file arpack.py.
References scipy.sparse._base.issparse().
Referenced by eigsh(), and scipy.sparse.linalg._eigen.lobpcg.tests.test_lobpcg.test_eigs_consistency().
eigsh()
scipy.sparse.linalg._eigen.arpack.arpack.eigsh (A, k = 6, M = None, sigma = None, which = 'LM', v0 = None, ncv = None, maxiter = None, tol = 0, return_eigenvectors = True, Minv = None, OPinv = None, mode = 'normal')
Find k eigenvalues and eigenvectors of the real symmetric square matrix
or complex Hermitian matrix A.
Solves ``A @ x[i] = w[i] * x[i]``, the standard eigenvalue problem for
w[i] eigenvalues with corresponding eigenvectors x[i].
If M is specified, solves ``A @ x[i] = w[i] * M @ x[i]``, the
generalized eigenvalue problem for w[i] eigenvalues
with corresponding eigenvectors x[i].
Note that there is no specialized routine for the case when A is a complex
Hermitian matrix. In this case, ``eigsh()`` will call ``eigs()`` and return the
real parts of the eigenvalues thus obtained.
Parameters
----------
A : ndarray, sparse matrix or LinearOperator
    A square operator representing the operation ``A @ x``, where ``A`` is
    real symmetric or complex Hermitian. For buckling mode (see below)
    ``A`` must additionally be positive-definite.
k : int, optional
    The number of eigenvalues and eigenvectors desired.
    `k` must be smaller than N. It is not possible to compute all
    eigenvectors of a matrix.
Returns
-------
w : array
    Array of k eigenvalues.
v : array
    An array representing the `k` eigenvectors.  The column ``v[:, i]`` is
    the eigenvector corresponding to the eigenvalue ``w[i]``.
Other Parameters
----------------
M : An N x N matrix, array, sparse matrix, or linear operator representing
    the operation ``M @ x`` for the generalized eigenvalue problem
        A @ x = w * M @ x.
    M must represent a real symmetric matrix if A is real, and must
    represent a complex Hermitian matrix if A is complex. For best
    results, the data type of M should be the same as that of A.
    Additionally:
        If sigma is None, M is symmetric positive definite.
        If sigma is specified, M is symmetric positive semi-definite.
        In buckling mode, M is symmetric indefinite.
    If sigma is None, eigsh requires an operator to compute the solution
    of the linear equation ``M @ x = b``. This is done internally via a
    (sparse) LU decomposition for an explicit matrix M, or via an
    iterative solver for a general linear operator.  Alternatively,
    the user can supply the matrix or operator Minv, which gives
    ``x = Minv @ b = M^-1 @ b``.
sigma : real
    Find eigenvalues near sigma using shift-invert mode.  This requires
    an operator to compute the solution of the linear system
    ``[A - sigma * M] x = b``, where M is the identity matrix if
    unspecified.  This is computed internally via a (sparse) LU
    decomposition for explicit matrices A & M, or via an iterative
    solver if either A or M is a general linear operator.
    Alternatively, the user can supply the matrix or operator OPinv,
    which gives ``x = OPinv @ b = [A - sigma * M]^-1 @ b``.
    Note that when sigma is specified, the keyword 'which' refers to
    the shifted eigenvalues ``w'[i]`` where:
        if mode == 'normal', ``w'[i] = 1 / (w[i] - sigma)``.
        if mode == 'cayley', ``w'[i] = (w[i] + sigma) / (w[i] - sigma)``.
        if mode == 'buckling', ``w'[i] = w[i] / (w[i] - sigma)``.
    (see further discussion in 'mode' below)
v0 : ndarray, optional
    Starting vector for iteration.
    Default: random
ncv : int, optional
    The number of Lanczos vectors generated ncv must be greater than k and
    smaller than n; it is recommended that ``ncv > 2*k``.
    Default: ``min(n, max(2*k + 1, 20))``
which : str ['LM' | 'SM' | 'LA' | 'SA' | 'BE']
    If A is a complex Hermitian matrix, 'BE' is invalid.
    Which `k` eigenvectors and eigenvalues to find:
        'LM' : Largest (in magnitude) eigenvalues.
        'SM' : Smallest (in magnitude) eigenvalues.
        'LA' : Largest (algebraic) eigenvalues.
        'SA' : Smallest (algebraic) eigenvalues.
        'BE' : Half (k/2) from each end of the spectrum.
    When k is odd, return one more (k/2+1) from the high end.
    When sigma != None, 'which' refers to the shifted eigenvalues ``w'[i]``
    (see discussion in 'sigma', above).  ARPACK is generally better
    at finding large values than small values.  If small eigenvalues are
    desired, consider using shift-invert mode for better performance.
maxiter : int, optional
    Maximum number of Arnoldi update iterations allowed.
    Default: ``n*10``
tol : float
    Relative accuracy for eigenvalues (stopping criterion).
    The default value of 0 implies machine precision.
Minv : N x N matrix, array, sparse matrix, or LinearOperator
    See notes in M, above.
OPinv : N x N matrix, array, sparse matrix, or LinearOperator
    See notes in sigma, above.
return_eigenvectors : bool
    Return eigenvectors (True) in addition to eigenvalues.
    This value determines the order in which eigenvalues are sorted.
    The sort order is also dependent on the `which` variable.
        For which = 'LM' or 'SA':
            If `return_eigenvectors` is True, eigenvalues are sorted by
            algebraic value.
            If `return_eigenvectors` is False, eigenvalues are sorted by
            absolute value.
        For which = 'BE' or 'LA':
            eigenvalues are always sorted by algebraic value.
        For which = 'SM':
            If `return_eigenvectors` is True, eigenvalues are sorted by
            algebraic value.
            If `return_eigenvectors` is False, eigenvalues are sorted by
            decreasing absolute value.
mode : string ['normal' | 'buckling' | 'cayley']
    Specify strategy to use for shift-invert mode.  This argument applies
    only for real-valued A and sigma != None.  For shift-invert mode,
    ARPACK internally solves the eigenvalue problem
    ``OP @ x'[i] = w'[i] * B @ x'[i]``
    and transforms the resulting Ritz vectors x'[i] and Ritz values w'[i]
    into the desired eigenvectors and eigenvalues of the problem
    ``A @ x[i] = w[i] * M @ x[i]``.
    The modes are as follows:
        'normal' :
            OP = [A - sigma * M]^-1 @ M,
            B = M,
            w'[i] = 1 / (w[i] - sigma)
        'buckling' :
            OP = [A - sigma * M]^-1 @ A,
            B = A,
            w'[i] = w[i] / (w[i] - sigma)
        'cayley' :
            OP = [A - sigma * M]^-1 @ [A + sigma * M],
            B = M,
            w'[i] = (w[i] + sigma) / (w[i] - sigma)
    The choice of mode will affect which eigenvalues are selected by
    the keyword 'which', and can also impact the stability of
    convergence (see [2] for a discussion).
Raises
------
ArpackNoConvergence
    When the requested convergence is not obtained.
    The currently converged eigenvalues and eigenvectors can be found
    as ``eigenvalues`` and ``eigenvectors`` attributes of the exception
    object.
See Also
--------
eigs : eigenvalues and eigenvectors for a general (nonsymmetric) matrix A
svds : singular value decomposition for a matrix A
Notes
-----
This function is a wrapper to the ARPACK [1]_ SSEUPD and DSEUPD
functions which use the Implicitly Restarted Lanczos Method to
find the eigenvalues and eigenvectors [2]_.
References
----------
.. [1] ARPACK Software, https://github.com/opencollab/arpack-ng
.. [2] R. B. Lehoucq, D. C. Sorensen, and C. Yang,  ARPACK USERS GUIDE:
   Solution of Large Scale Eigenvalue Problems by Implicitly Restarted
   Arnoldi Methods. SIAM, Philadelphia, PA, 1998.
Examples
--------
>>> import numpy as np
>>> from scipy.sparse.linalg import eigsh
>>> identity = np.eye(13)
>>> eigenvalues, eigenvectors = eigsh(identity, k=6)
>>> eigenvalues
array([1., 1., 1., 1., 1., 1.])
>>> eigenvectors.shape
(13, 6)
Definition at line 1357 of file arpack.py.
References eigs(), and scipy.sparse._base.issparse().
Referenced by scipy.sparse.linalg._eigen._svds.svds().
get_inv_matvec()
scipy.sparse.linalg._eigen.arpack.arpack.get_inv_matvec (M, hermitian = False, tol = 0)
Definition at line 1051 of file arpack.py.
get_OPinv_matvec()
scipy.sparse.linalg._eigen.arpack.arpack.get_OPinv_matvec (A, M, sigma, hermitian = False, tol = 0)
Definition at line 1061 of file arpack.py.
gmres_loose()
scipy.sparse.linalg._eigen.arpack.arpack.gmres_loose (A, b, tol)
gmres with looser termination condition.
Definition at line 947 of file arpack.py.
References scipy.sparse.linalg._isolve.iterative.gmres().
Variable Documentation
__all__
list scipy.sparse.linalg._eigen.arpack.arpack.__all__ = ['eigs', 'eigsh', 'ArpackError', 'ArpackNoConvergence'] private
Definition at line 53 of file arpack.py.
__docformat__
str scipy.sparse.linalg._eigen.arpack.arpack.__docformat__ = "restructuredtext en" private
Definition at line 51 of file arpack.py.
_ARPACK_LOCK
scipy.sparse.linalg._eigen.arpack.arpack._ARPACK_LOCK protected
Initial value:
=  ReentrancyLock("Nested calls to eigs/eighs not allowed: "
                              "ARPACK is not re-entrant")
Definition at line 1098 of file arpack.py.
_NAUPD_ERRORS
dict scipy.sparse.linalg._eigen.arpack.arpack._NAUPD_ERRORS protected
Initial value:
=  {'d': DNAUPD_ERRORS,
                 's': SNAUPD_ERRORS,
                 'z': ZNAUPD_ERRORS,
                 'c': CNAUPD_ERRORS}
Definition at line 255 of file arpack.py.
_ndigits
dict scipy.sparse.linalg._eigen.arpack.arpack._ndigits = {'f': 5, 'd': 12, 'F': 5, 'D': 12} protected
Definition at line 57 of file arpack.py.
_NEUPD_ERRORS
dict scipy.sparse.linalg._eigen.arpack.arpack._NEUPD_ERRORS protected
Initial value:
=  {'d': DNEUPD_ERRORS,
                 's': SNEUPD_ERRORS,
                 'z': ZNEUPD_ERRORS,
                 'c': CNEUPD_ERRORS}
Definition at line 261 of file arpack.py.
_NEUPD_WHICH
list scipy.sparse.linalg._eigen.arpack.arpack._NEUPD_WHICH = ['LM', 'SM', 'LR', 'SR', 'LI', 'SI'] protected
Definition at line 270 of file arpack.py.
_SAUPD_ERRORS
dict scipy.sparse.linalg._eigen.arpack.arpack._SAUPD_ERRORS protected
Initial value:
=  {'d': DSAUPD_ERRORS,
                 's': SSAUPD_ERRORS}
Definition at line 253 of file arpack.py.
_SEUPD_ERRORS
dict scipy.sparse.linalg._eigen.arpack.arpack._SEUPD_ERRORS protected
Initial value:
=  {'d': DSEUPD_ERRORS,
                 's': SSEUPD_ERRORS}
Definition at line 259 of file arpack.py.
_SEUPD_WHICH
list scipy.sparse.linalg._eigen.arpack.arpack._SEUPD_WHICH = ['LM', 'SM', 'LA', 'SA', 'BE'] protected
Definition at line 267 of file arpack.py.
_type_conv
dict scipy.sparse.linalg._eigen.arpack.arpack._type_conv = {'f': 's', 'd': 'd', 'F': 'c', 'D': 'z'} protected
Definition at line 56 of file arpack.py.
arpack_int
scipy.sparse.linalg._eigen.arpack.arpack.arpack_int = _arpack.timing.nbx.dtype
Definition at line 49 of file arpack.py.
CNAUPD_ERRORS
dict scipy.sparse.linalg._eigen.arpack.arpack.CNAUPD_ERRORS = ZNAUPD_ERRORS
Definition at line 94 of file arpack.py.
CNEUPD_ERRORS
dict scipy.sparse.linalg._eigen.arpack.arpack.CNEUPD_ERRORS = ZNEUPD_ERRORS.copy()
Definition at line 210 of file arpack.py.
DNAUPD_ERRORS
dict scipy.sparse.linalg._eigen.arpack.arpack.DNAUPD_ERRORS
Initial value:
=  {
    0: "Normal exit.",
    1: "Maximum number of iterations taken. "
       "All possible eigenvalues of OP has been found. IPARAM(5) "
       "returns the number of wanted converged Ritz values.",
    2: "No longer an informational error. Deprecated starting "
       "with release 2 of ARPACK.",
    3: "No shifts could be applied during a cycle of the "
       "Implicitly restarted Arnoldi iteration. One possibility "
       "is to increase the size of NCV relative to NEV. ",
    -1: "N must be positive.",
    -2: "NEV must be positive.",
    -3: "NCV-NEV >= 2 and less than or equal to N.",
    -4: "The maximum number of Arnoldi update iterations allowed "
        "must be greater than zero.",
    -5: " WHICH must be one of 'LM', 'SM', 'LR', 'SR', 'LI', 'SI'",
    -6: "BMAT must be one of 'I' or 'G'.",
    -7: "Length of private work array WORKL is not sufficient.",
    -8: "Error return from LAPACK eigenvalue calculation;",
    -9: "Starting vector is zero.",
    -10: "IPARAM(7) must be 1,2,3,4.",
    -11: "IPARAM(7) = 1 and BMAT = 'G' are incompatible.",
    -12: "IPARAM(1) must be equal to 0 or 1.",
    -13: "NEV and WHICH = 'BE' are incompatible.",
    -9999: "Could not build an Arnoldi factorization. "
           "IPARAM(5) returns the size of the current Arnoldi "
           "factorization. The user is advised to check that "
           "enough workspace and array storage has been allocated."
}
Definition at line 59 of file arpack.py.
DNEUPD_ERRORS
dict scipy.sparse.linalg._eigen.arpack.arpack.DNEUPD_ERRORS
Definition at line 128 of file arpack.py.
DSAUPD_ERRORS
dict scipy.sparse.linalg._eigen.arpack.arpack.DSAUPD_ERRORS
Initial value:
=  {
    0: "Normal exit.",
    1: "Maximum number of iterations taken. "
       "All possible eigenvalues of OP has been found.",
    2: "No longer an informational error. Deprecated starting with "
       "release 2 of ARPACK.",
    3: "No shifts could be applied during a cycle of the Implicitly "
       "restarted Arnoldi iteration. One possibility is to increase "
       "the size of NCV relative to NEV. ",
    -1: "N must be positive.",
    -2: "NEV must be positive.",
    -3: "NCV must be greater than NEV and less than or equal to N.",
    -4: "The maximum number of Arnoldi update iterations allowed "
        "must be greater than zero.",
    -5: "WHICH must be one of 'LM', 'SM', 'LA', 'SA' or 'BE'.",
    -6: "BMAT must be one of 'I' or 'G'.",
    -7: "Length of private work array WORKL is not sufficient.",
    -8: "Error return from trid. eigenvalue calculation; "
        "Informational error from LAPACK routine dsteqr .",
    -9: "Starting vector is zero.",
    -10: "IPARAM(7) must be 1,2,3,4,5.",
    -11: "IPARAM(7) = 1 and BMAT = 'G' are incompatible.",
    -12: "IPARAM(1) must be equal to 0 or 1.",
    -13: "NEV and WHICH = 'BE' are incompatible. ",
    -9999: "Could not build an Arnoldi factorization. "
           "IPARAM(5) returns the size of the current Arnoldi "
           "factorization. The user is advised to check that "
           "enough workspace and array storage has been allocated.",
}
Definition at line 96 of file arpack.py.
DSEUPD_ERRORS
dict scipy.sparse.linalg._eigen.arpack.arpack.DSEUPD_ERRORS
Initial value:
=  {
    0: "Normal exit.",
    -1: "N must be positive.",
    -2: "NEV must be positive.",
    -3: "NCV must be greater than NEV and less than or equal to N.",
    -5: "WHICH must be one of 'LM', 'SM', 'LA', 'SA' or 'BE'.",
    -6: "BMAT must be one of 'I' or 'G'.",
    -7: "Length of private work WORKL array is not sufficient.",
    -8: ("Error return from trid. eigenvalue calculation; "
         "Information error from LAPACK routine dsteqr."),
    -9: "Starting vector is zero.",
    -10: "IPARAM(7) must be 1,2,3,4,5.",
    -11: "IPARAM(7) = 1 and BMAT = 'G' are incompatible.",
    -12: "NEV and WHICH = 'BE' are incompatible.",
    -14: "DSAUPD  did not find any eigenvalues to sufficient accuracy.",
    -15: "HOWMNY must be one of 'A' or 'S' if RVEC = .true.",
    -16: "HOWMNY = 'S' not yet implemented",
    -17: ("DSEUPD  got a different count of the number of converged "
          "Ritz values than DSAUPD  got.  This indicates the user "
          "probably made an error in passing data from DSAUPD  to "
          "DSEUPD  or that the data was modified before entering  "
          "DSEUPD.")
}
Definition at line 219 of file arpack.py.
SNAUPD_ERRORS
dict scipy.sparse.linalg._eigen.arpack.arpack.SNAUPD_ERRORS = DNAUPD_ERRORS
Definition at line 89 of file arpack.py.
SNEUPD_ERRORS
dict scipy.sparse.linalg._eigen.arpack.arpack.SNEUPD_ERRORS = DNEUPD_ERRORS.copy()
Definition at line 161 of file arpack.py.
SSAUPD_ERRORS
dict scipy.sparse.linalg._eigen.arpack.arpack.SSAUPD_ERRORS = DSAUPD_ERRORS
Definition at line 126 of file arpack.py.
SSEUPD_ERRORS
dict scipy.sparse.linalg._eigen.arpack.arpack.SSEUPD_ERRORS = DSEUPD_ERRORS.copy()
Definition at line 243 of file arpack.py.
ZNAUPD_ERRORS
dict scipy.sparse.linalg._eigen.arpack.arpack.ZNAUPD_ERRORS = DNAUPD_ERRORS.copy()
Definition at line 91 of file arpack.py.
ZNEUPD_ERRORS
dict scipy.sparse.linalg._eigen.arpack.arpack.ZNEUPD_ERRORS
Definition at line 178 of file arpack.py.