Code Cloning Analysis: scipy._lib.doccer Namespace Reference
scipy._lib.doccer Namespace Reference
Functions
docformat (docstring, docdict=None)
inherit_docstring_from (cls)
extend_notes_in_docstring (cls, notes)
replace_notes_in_docstring (cls, notes)
indentcount_lines (lines)
filldoc (docdict, unindent_params=True)
unindent_dict (docdict)
unindent_string (docstring)
doc_replace (obj, oldval, newval)
Variables
list __all__
Detailed Description
 Utilities to allow inserting docstring fragments for common
parameters into function and method docstrings
Function Documentation
doc_replace()
scipy._lib.doccer.doc_replace (obj, oldval, newval)
Decorator to take the docstring from obj, with oldval replaced by newval
Equivalent to ``func.__doc__ = obj.__doc__.replace(oldval, newval)``
Parameters
----------
obj : object
    The object to take the docstring from.
oldval : string
    The string to replace from the original docstring.
newval : string
    The string to replace ``oldval`` with.
Definition at line 254 of file doccer.py.
docformat()
scipy._lib.doccer.docformat (docstring, docdict = None)
 Fill a function docstring from variables in dictionary
Adapt the indent of the inserted docs
Parameters
----------
docstring : string
    docstring from function, possibly with dict formatting strings
docdict : dict, optional
    dictionary with keys that match the dict formatting strings
    and values that are docstring fragments to be inserted. The
    indentation of the inserted docstrings is set to match the
    minimum indentation of the ``docstring`` by adding this
    indentation to all lines of the inserted string, except the
    first.
Returns
-------
outstring : string
    string with requested ``docdict`` strings inserted
Examples
--------
>>> docformat(' Test string with %(value)s', {'value':'inserted value'})
' Test string with inserted value'
>>> docstring = 'First line\\n    Second line\\n    %(value)s'
>>> inserted_string = "indented\\nstring"
>>> docdict = {'value': inserted_string}
>>> docformat(docstring, docdict)
'First line\\n    Second line\\n    indented\\n    string'
Definition at line 13 of file doccer.py.
References indentcount_lines().
Referenced by filldoc().
extend_notes_in_docstring()
scipy._lib.doccer.extend_notes_in_docstring (cls, notes)
This decorator replaces the decorated function's docstring
with the docstring from corresponding method in `cls`.
It extends the 'Notes' section of that docstring to include
the given `notes`.
Definition at line 129 of file doccer.py.
filldoc()
scipy._lib.doccer.filldoc (docdict, unindent_params = True)
 Return docstring decorator using docdict variable dictionary
Parameters
----------
docdict : dictionary
    dictionary containing name, docstring fragment pairs
unindent_params : {False, True}, boolean, optional
    If True, strip common indentation from all parameters in
    docdict
Returns
-------
decfunc : function
    decorator that applies dictionary to input function docstring
Definition at line 205 of file doccer.py.
References docformat(), and unindent_dict().
indentcount_lines()
scipy._lib.doccer.indentcount_lines (lines)
 Minimum indent for all lines in line list
>>> lines = [' one', '  two', '   three']
>>> indentcount_lines(lines)
1
>>> lines = []
>>> indentcount_lines(lines)
0
>>> lines = [' one']
>>> indentcount_lines(lines)
1
>>> indentcount_lines(['    '])
0
Definition at line 180 of file doccer.py.
Referenced by docformat(), and unindent_string().
inherit_docstring_from()
scipy._lib.doccer.inherit_docstring_from (cls)
This decorator modifies the decorated function's docstring by
replacing occurrences of '%(super)s' with the docstring of the
method of the same name from the class `cls`.
If the decorated method has no docstring, it is simply given the
docstring of `cls`s method.
Parameters
----------
cls : Python class or instance
    A class with a method with the same name as the decorated method.
    The docstring of the method in this class replaces '%(super)s' in the
    docstring of the decorated method.
Returns
-------
f : function
    The decorator function that modifies the __doc__ attribute
    of its argument.
Examples
--------
In the following, the docstring for Bar.func created using the
docstring of `Foo.func`.
>>> class Foo:
...     def func(self):
...         '''Do something useful.'''
...         return
...
>>> class Bar(Foo):
...     @inherit_docstring_from(Foo)
...     def func(self):
...         '''%(super)s
...         Do it fast.
...         '''
...         return
...
>>> b = Bar()
>>> b.func.__doc__
'Do something useful.\n        Do it fast.\n        '
Definition at line 72 of file doccer.py.
replace_notes_in_docstring()
scipy._lib.doccer.replace_notes_in_docstring (cls, notes)
This decorator replaces the decorated function's docstring
with the docstring from corresponding method in `cls`.
It replaces the 'Notes' section of that docstring with
the given `notes`.
Definition at line 153 of file doccer.py.
unindent_dict()
scipy._lib.doccer.unindent_dict (docdict)
 Unindent all strings in a docdict
Definition at line 231 of file doccer.py.
References unindent_string().
Referenced by filldoc().
unindent_string()
scipy._lib.doccer.unindent_string (docstring)
 Set docstring to minimum indent for all lines, including first
>>> unindent_string(' two')
'two'
>>> unindent_string('  two\\n   three')
'two\\n three'
Definition at line 239 of file doccer.py.
References indentcount_lines().
Referenced by unindent_dict().
Variable Documentation
__all__
list scipy._lib.doccer.__all__ private
Initial value:
=  [
    'docformat', 'inherit_docstring_from', 'indentcount_lines',
    'filldoc', 'unindent_dict', 'unindent_string', 'extend_notes_in_docstring',
    'replace_notes_in_docstring', 'doc_replace'
]
Definition at line 6 of file doccer.py.