Code Cloning Analysis: matplotlib.mlab Namespace Reference
matplotlib.mlab Namespace Reference
Classes
class GaussianKDE
Functions
window_hanning (x)
window_none (x)
detrend (x, key=None, axis=None)
detrend_mean (x, axis=None)
detrend_none (x, axis=None)
detrend_linear (y)
_spectral_helper (x, y=None, NFFT=None, Fs=None, detrend_func=None, window=None, noverlap=None, pad_to=None, sides=None, scale_by_freq=None, mode=None)
_single_spectrum_helper (mode, x, Fs=None, window=None, pad_to=None, sides=None)
psd (x, NFFT=None, Fs=None, detrend=None, window=None, noverlap=None, pad_to=None, sides=None, scale_by_freq=None)
csd (x, y, NFFT=None, Fs=None, detrend=None, window=None, noverlap=None, pad_to=None, sides=None, scale_by_freq=None)
specgram (x, NFFT=None, Fs=None, detrend=None, window=None, noverlap=None, pad_to=None, sides=None, scale_by_freq=None, mode=None)
cohere (x, y, NFFT=256, Fs=2, detrend=detrend_none, window=window_hanning, noverlap=0, pad_to=None, sides='default', scale_by_freq=None)
Variables
Spectral
Single_Spectrum
PSD
str _single_spectrum_docs
complex_spectrum = functools.partial(_single_spectrum_helper, "complex")
__doc__
quantity
magnitude_spectrum = functools.partial(_single_spectrum_helper, "magnitude")
angle_spectrum = functools.partial(_single_spectrum_helper, "angle")
phase_spectrum = functools.partial(_single_spectrum_helper, "phase")
Detailed Description
Numerical Python functions written for compatibility with MATLAB
commands with the same names. Most numerical Python functions can be found in
the `NumPy`_ and `SciPy`_ libraries. What remains here is code for performing
spectral computations and kernel density estimations.
.. _NumPy: https://numpy.org
.. _SciPy: https://www.scipy.org
Spectral functions
------------------
`cohere`
    Coherence (normalized cross spectral density)
`csd`
    Cross spectral density using Welch's average periodogram
`detrend`
    Remove the mean or best fit line from an array
`psd`
    Power spectral density using Welch's average periodogram
`specgram`
    Spectrogram (spectrum over segments of time)
`complex_spectrum`
    Return the complex-valued frequency spectrum of a signal
`magnitude_spectrum`
    Return the magnitude of the frequency spectrum of a signal
`angle_spectrum`
    Return the angle (wrapped phase) of the frequency spectrum of a signal
`phase_spectrum`
    Return the phase (unwrapped angle) of the frequency spectrum of a signal
`detrend_mean`
    Remove the mean from a line.
`detrend_linear`
    Remove the best fit line from a line.
`detrend_none`
    Return the original line.
Function Documentation
_single_spectrum_helper()
matplotlib.mlab._single_spectrum_helper (mode, x, Fs = None, window = None, pad_to = None, sides = None) protected
Private helper implementing the commonality between the complex, magnitude,
angle, and phase spectrums.
Definition at line 376 of file mlab.py.
References _spectral_helper().
_spectral_helper()
matplotlib.mlab._spectral_helper (x, y = None, NFFT = None, Fs = None, detrend_func = None, window = None, noverlap = None, pad_to = None, sides = None, scale_by_freq = None, mode = None) protected
Private helper implementing the common parts between the psd, csd,
spectrogram and complex, magnitude, angle, and phase spectrums.
Definition at line 213 of file mlab.py.
References detrend().
Referenced by _single_spectrum_helper(), csd(), and specgram().
cohere()
matplotlib.mlab.cohere (x, y, NFFT = 256, Fs = 2, detrend = detrend_none, window = window_hanning, noverlap = 0, pad_to = None, sides = 'default', scale_by_freq = None)
The coherence between *x* and *y*.  Coherence is the normalized
cross spectral density:
.. math::
    C_{xy} = \frac{|P_{xy}|^2}{P_{xx}P_{yy}}
Parameters
----------
x, y
    Array or sequence containing the data
%(Spectral)s
%(PSD)s
noverlap : int, default: 0 (no overlap)
    The number of points of overlap between segments.
Returns
-------
Cxy : 1-D array
    The coherence vector.
freqs : 1-D array
        The frequencies for the elements in *Cxy*.
See Also
--------
:func:`psd`, :func:`csd` :
    For information about the methods used to compute :math:`P_{xy}`,
    :math:`P_{xx}` and :math:`P_{yy}`.
Definition at line 721 of file mlab.py.
References csd(), and psd().
csd()
matplotlib.mlab.csd (x, y, NFFT = None, Fs = None, detrend = None, window = None, noverlap = None, pad_to = None, sides = None, scale_by_freq = None)
Compute the cross-spectral density.
The cross spectral density :math:`P_{xy}` by Welch's average
periodogram method.  The vectors *x* and *y* are divided into
*NFFT* length segments.  Each segment is detrended by function
*detrend* and windowed by function *window*.  *noverlap* gives
the length of the overlap between segments.  The product of
the direct FFTs of *x* and *y* are averaged over each segment
to compute :math:`P_{xy}`, with a scaling to correct for power
loss due to windowing.
If len(*x*) < *NFFT* or len(*y*) < *NFFT*, they will be zero
padded to *NFFT*.
Parameters
----------
x, y : 1-D arrays or sequences
    Arrays or sequences containing the data
%(Spectral)s
%(PSD)s
noverlap : int, default: 0 (no overlap)
    The number of points of overlap between segments.
Returns
-------
Pxy : 1-D array
    The values for the cross spectrum :math:`P_{xy}` before scaling (real
    valued)
freqs : 1-D array
    The frequencies corresponding to the elements in *Pxy*
References
----------
Bendat & Piersol -- Random Data: Analysis and Measurement Procedures, John
Wiley & Sons (1986)
See Also
--------
psd : equivalent to setting ``y = x``.
Definition at line 518 of file mlab.py.
References _spectral_helper().
Referenced by cohere(), and psd().
detrend()
matplotlib.mlab.detrend (x, key = None, axis = None)
Return *x* with its trend removed.
Parameters
----------
x : array or sequence
    Array or sequence containing the data.
key : {'default', 'constant', 'mean', 'linear', 'none'} or function
    The detrending algorithm to use. 'default', 'mean', and 'constant' are
    the same as `detrend_mean`. 'linear' is the same as `detrend_linear`.
    'none' is the same as `detrend_none`. The default is 'mean'. See the
    corresponding functions for more details regarding the algorithms. Can
    also be a function that carries out the detrend operation.
axis : int
    The axis along which to do the detrending.
See Also
--------
detrend_mean : Implementation of the 'mean' algorithm.
detrend_linear : Implementation of the 'linear' algorithm.
detrend_none : Implementation of the 'none' algorithm.
Definition at line 80 of file mlab.py.
References detrend().
Referenced by _spectral_helper(), and detrend().
detrend_linear()
matplotlib.mlab.detrend_linear (y)
Return *x* minus best fit line; 'linear' detrending.
Parameters
----------
y : 0-D or 1-D array or sequence
    Array or sequence containing the data
See Also
--------
detrend_mean : Another detrend algorithm.
detrend_none : Another detrend algorithm.
detrend : A wrapper around all the detrend algorithms.
Definition at line 179 of file mlab.py.
detrend_mean()
matplotlib.mlab.detrend_mean (x, axis = None)
Return *x* minus the mean(*x*).
Parameters
----------
x : array or sequence
    Array or sequence containing the data
    Can have any dimensionality
axis : int
    The axis along which to take the mean.  See `numpy.mean` for a
    description of this argument.
See Also
--------
detrend_linear : Another detrend algorithm.
detrend_none : Another detrend algorithm.
detrend : A wrapper around all the detrend algorithms.
Definition at line 129 of file mlab.py.
detrend_none()
matplotlib.mlab.detrend_none (x, axis = None)
Return *x*: no detrending.
Parameters
----------
x : any object
    An object containing the data
axis : int
    This parameter is ignored.
    It is included for compatibility with detrend_mean
See Also
--------
detrend_mean : Another detrend algorithm.
detrend_linear : Another detrend algorithm.
detrend : A wrapper around all the detrend algorithms.
Definition at line 157 of file mlab.py.
psd()
matplotlib.mlab.psd (x, NFFT = None, Fs = None, detrend = None, window = None, noverlap = None, pad_to = None, sides = None, scale_by_freq = None)
Compute the power spectral density.
The power spectral density :math:`P_{xx}` by Welch's average
periodogram method.  The vector *x* is divided into *NFFT* length
segments.  Each segment is detrended by function *detrend* and
windowed by function *window*.  *noverlap* gives the length of
the overlap between segments.  The :math:`|\mathrm{fft}(i)|^2`
of each segment :math:`i` are averaged to compute :math:`P_{xx}`.
If len(*x*) < *NFFT*, it will be zero padded to *NFFT*.
Parameters
----------
x : 1-D array or sequence
    Array or sequence containing the data
%(Spectral)s
%(PSD)s
noverlap : int, default: 0 (no overlap)
    The number of points of overlap between segments.
Returns
-------
Pxx : 1-D array
    The values for the power spectrum :math:`P_{xx}` (real valued)
freqs : 1-D array
    The frequencies corresponding to the elements in *Pxx*
References
----------
Bendat & Piersol -- Random Data: Analysis and Measurement Procedures, John
Wiley & Sons (1986)
See Also
--------
specgram
    `specgram` differs in the default overlap; in not returning the mean of
    the segment periodograms; and in returning the times of the segments.
magnitude_spectrum : returns the magnitude spectrum.
csd : returns the spectral density between two signals.
Definition at line 462 of file mlab.py.
References csd().
Referenced by cohere().
specgram()
matplotlib.mlab.specgram (x, NFFT = None, Fs = None, detrend = None, window = None, noverlap = None, pad_to = None, sides = None, scale_by_freq = None, mode = None)
Compute a spectrogram.
Compute and plot a spectrogram of data in *x*.  Data are split into
*NFFT* length segments and the spectrum of each section is
computed.  The windowing function *window* is applied to each
segment, and the amount of overlap of each segment is
specified with *noverlap*.
Parameters
----------
x : array-like
    1-D array or sequence.
%(Spectral)s
%(PSD)s
noverlap : int, default: 128
    The number of points of overlap between blocks.
mode : str, default: 'psd'
    What sort of spectrum to use:
        'psd'
            Returns the power spectral density.
        'complex'
            Returns the complex-valued frequency spectrum.
        'magnitude'
            Returns the magnitude spectrum.
        'angle'
            Returns the phase spectrum without unwrapping.
        'phase'
            Returns the phase spectrum with unwrapping.
Returns
-------
spectrum : array-like
    2D array, columns are the periodograms of successive segments.
freqs : array-like
    1-D array, frequencies corresponding to the rows in *spectrum*.
t : array-like
    1-D array, the times corresponding to midpoints of segments
    (i.e the columns in *spectrum*).
See Also
--------
psd : differs in the overlap and in the return values.
complex_spectrum : similar, but with complex valued frequencies.
magnitude_spectrum : similar single segment when *mode* is 'magnitude'.
angle_spectrum : similar to single segment when *mode* is 'angle'.
phase_spectrum : similar to single segment when *mode* is 'phase'.
Notes
-----
*detrend* and *scale_by_freq* only apply when *mode* is set to 'psd'.
Definition at line 638 of file mlab.py.
References _spectral_helper().
window_hanning()
matplotlib.mlab.window_hanning (x)
Return *x* times the Hanning (or Hann) window of len(*x*).
See Also
--------
window_none : Another window algorithm.
Definition at line 58 of file mlab.py.
window_none()
matplotlib.mlab.window_none (x)
No window function; simply return *x*.
See Also
--------
window_hanning : Another window algorithm.
Definition at line 69 of file mlab.py.
Variable Documentation
__doc__
matplotlib.mlab.__doc__ private
Definition at line 620 of file mlab.py.
_single_spectrum_docs
str matplotlib.mlab._single_spectrum_docs protected
Definition at line 581 of file mlab.py.
angle_spectrum
matplotlib.mlab.angle_spectrum = functools.partial(_single_spectrum_helper, "angle")
Definition at line 627 of file mlab.py.
complex_spectrum
matplotlib.mlab.complex_spectrum = functools.partial(_single_spectrum_helper, "complex")
Definition at line 619 of file mlab.py.
magnitude_spectrum
matplotlib.mlab.magnitude_spectrum = functools.partial(_single_spectrum_helper, "magnitude")
Definition at line 623 of file mlab.py.
phase_spectrum
matplotlib.mlab.phase_spectrum = functools.partial(_single_spectrum_helper, "phase")
Definition at line 631 of file mlab.py.
PSD
matplotlib.mlab.PSD
Definition at line 430 of file mlab.py.
quantity
matplotlib.mlab.quantity
Definition at line 621 of file mlab.py.
Single_Spectrum
matplotlib.mlab.Single_Spectrum
Definition at line 421 of file mlab.py.
Spectral
matplotlib.mlab.Spectral
Definition at line 404 of file mlab.py.