Code Cloning Analysis: scipy.spatial.transform._rotation_spline Namespace Reference
scipy.spatial.transform._rotation_spline Namespace Reference
Classes
class RotationSpline
Functions
_create_skew_matrix (x)
_matrix_vector_product_of_stacks (A, b)
_angular_rate_to_rotvec_dot_matrix (rotvecs)
_rotvec_dot_to_angular_rate_matrix (rotvecs)
_angular_acceleration_nonlinear_term (rotvecs, rotvecs_dot)
_compute_angular_rate (rotvecs, rotvecs_dot)
_compute_angular_acceleration (rotvecs, rotvecs_dot, rotvecs_dot_dot)
_create_block_3_diagonal_matrix (A, B, d)
Function Documentation
_angular_acceleration_nonlinear_term()
scipy.spatial.transform._rotation_spline._angular_acceleration_nonlinear_term (rotvecs, rotvecs_dot) protected
Compute the non-linear term in angular acceleration.
The angular acceleration contains a quadratic term with respect to
the derivative of the rotation vector. This function computes that.
Parameters
----------
rotvecs : ndarray, shape (n, 3)
    Set of rotation vectors.
rotvecs_dot : ndarray, shape (n, 3)
    Set of rotation vector derivatives.
Returns
-------
ndarray, shape (n, 3)
Definition at line 107 of file _rotation_spline.py.
Referenced by _compute_angular_acceleration().
_angular_rate_to_rotvec_dot_matrix()
scipy.spatial.transform._rotation_spline._angular_rate_to_rotvec_dot_matrix (rotvecs) protected
Compute matrices to transform angular rates to rot. vector derivatives.
The matrices depend on the current attitude represented as a rotation
vector.
Parameters
----------
rotvecs : ndarray, shape (n, 3)
    Set of rotation vectors.
Returns
-------
ndarray, shape (n, 3, 3)
Definition at line 33 of file _rotation_spline.py.
References _create_skew_matrix().
_compute_angular_acceleration()
scipy.spatial.transform._rotation_spline._compute_angular_acceleration (rotvecs, rotvecs_dot, rotvecs_dot_dot) protected
Compute angular acceleration given rotation vector and its derivatives.
Parameters
----------
rotvecs : ndarray, shape (n, 3)
    Set of rotation vectors.
rotvecs_dot : ndarray, shape (n, 3)
    Set of rotation vector derivatives.
rotvecs_dot_dot : ndarray, shape (n, 3)
    Set of rotation vector second derivatives.
Returns
-------
ndarray, shape (n, 3)
Definition at line 172 of file _rotation_spline.py.
References _angular_acceleration_nonlinear_term(), and _compute_angular_rate().
Referenced by scipy.spatial.transform._rotation_spline.RotationSpline.__call__().
_compute_angular_rate()
scipy.spatial.transform._rotation_spline._compute_angular_rate (rotvecs, rotvecs_dot) protected
Compute angular rates given rotation vectors and its derivatives.
Parameters
----------
rotvecs : ndarray, shape (n, 3)
    Set of rotation vectors.
rotvecs_dot : ndarray, shape (n, 3)
    Set of rotation vector derivatives.
Returns
-------
ndarray, shape (n, 3)
Definition at line 154 of file _rotation_spline.py.
References _matrix_vector_product_of_stacks(), and _rotvec_dot_to_angular_rate_matrix().
Referenced by scipy.spatial.transform._rotation_spline.RotationSpline.__call__(), and _compute_angular_acceleration().
_create_block_3_diagonal_matrix()
scipy.spatial.transform._rotation_spline._create_block_3_diagonal_matrix (A, B, d) protected
Create a 3-diagonal block matrix as banded.
The matrix has the following structure:
    DB...
    ADB..
    .ADB.
    ..ADB
    ...AD
The blocks A, B and D are 3-by-3 matrices. The D matrices has the form
d * I.
Parameters
----------
A : ndarray, shape (n, 3, 3)
    Stack of A blocks.
B : ndarray, shape (n, 3, 3)
    Stack of B blocks.
d : ndarray, shape (n + 1,)
    Values for diagonal blocks.
Returns
-------
ndarray, shape (11, 3 * (n + 1))
    Matrix in the banded form as used by `scipy.linalg.solve_banded`.
Definition at line 192 of file _rotation_spline.py.
_create_skew_matrix()
scipy.spatial.transform._rotation_spline._create_skew_matrix (x) protected
Create skew-symmetric matrices corresponding to vectors.
Parameters
----------
x : ndarray, shape (n, 3)
    Set of vectors.
Returns
-------
ndarray, shape (n, 3, 3)
Definition at line 6 of file _rotation_spline.py.
Referenced by _angular_rate_to_rotvec_dot_matrix(), and _rotvec_dot_to_angular_rate_matrix().
_matrix_vector_product_of_stacks()
scipy.spatial.transform._rotation_spline._matrix_vector_product_of_stacks (A, b) protected
Compute the product of stack of matrices and vectors.
Definition at line 28 of file _rotation_spline.py.
Referenced by _compute_angular_rate().
_rotvec_dot_to_angular_rate_matrix()
scipy.spatial.transform._rotation_spline._rotvec_dot_to_angular_rate_matrix (rotvecs) protected
Compute matrices to transform rot. vector derivatives to angular rates.
The matrices depend on the current attitude represented as a rotation
vector.
Parameters
----------
rotvecs : ndarray, shape (n, 3)
    Set of rotation vectors.
Returns
-------
ndarray, shape (n, 3, 3)
Definition at line 68 of file _rotation_spline.py.
References _create_skew_matrix().
Referenced by _compute_angular_rate().