Code Cloning Analysis: pandas.tests.series.indexing.test_setitem.SetitemCastingEquivalents Class Reference
pandas.tests.series.indexing.test_setitem.SetitemCastingEquivalents Class Reference
Public Member Functions
is_inplace (self, obj, expected)
check_indexer (self, obj, key, expected, val, indexer, is_inplace)
test_int_key (self, obj, key, expected, warn, val, indexer_sli, is_inplace)
test_slice_key (self, obj, key, expected, warn, val, indexer_sli, is_inplace)
test_mask_key (self, obj, key, expected, warn, val, indexer_sli)
test_series_where (self, obj, key, expected, warn, val, is_inplace)
test_index_where (self, obj, key, expected, warn, val)
test_index_putmask (self, obj, key, expected, warn, val)
Static Public Attributes
id
Protected Member Functions
_check_inplace (self, is_inplace, orig, arr, obj)
Detailed Description
Check each of several methods that _should_ be equivalent to `obj[key] = val`
We assume that
    - obj.index is the default Index(range(len(obj)))
    - the setitem does not expand the obj
Definition at line 734 of file test_setitem.py.
Member Function Documentation
_check_inplace()
pandas.tests.series.indexing.test_setitem.SetitemCastingEquivalents._check_inplace (self, is_inplace, orig, arr, obj) protected
Definition at line 760 of file test_setitem.py.
Referenced by is_inplace().
check_indexer()
pandas.tests.series.indexing.test_setitem.SetitemCastingEquivalents.check_indexer (self, obj, key, expected, val, indexer, is_inplace)
Definition at line 750 of file test_setitem.py.
Referenced by is_inplace().
is_inplace()
pandas.tests.series.indexing.test_setitem.SetitemCastingEquivalents.is_inplace (self, obj, expected)
Whether we expect the setting to be in-place or not.
Reimplemented in pandas.tests.series.indexing.test_setitem.TestSetitemNADatetimeLikeDtype.
Definition at line 744 of file test_setitem.py.
References _check_inplace(), and check_indexer().
test_index_putmask()
pandas.tests.series.indexing.test_setitem.SetitemCastingEquivalents.test_index_putmask (self, obj, key, expected, warn, val)
Definition at line 884 of file test_setitem.py.
test_index_where()
pandas.tests.series.indexing.test_setitem.SetitemCastingEquivalents.test_index_where (self, obj, key, expected, warn, val)
Definition at line 876 of file test_setitem.py.
test_int_key()
pandas.tests.series.indexing.test_setitem.SetitemCastingEquivalents.test_int_key (self, obj, key, expected, warn, val, indexer_sli, is_inplace)
Definition at line 775 of file test_setitem.py.
test_mask_key()
pandas.tests.series.indexing.test_setitem.SetitemCastingEquivalents.test_mask_key (self, obj, key, expected, warn, val, indexer_sli)
Definition at line 832 of file test_setitem.py.
test_series_where()
pandas.tests.series.indexing.test_setitem.SetitemCastingEquivalents.test_series_where (self, obj, key, expected, warn, val, is_inplace)
Definition at line 849 of file test_setitem.py.
test_slice_key()
pandas.tests.series.indexing.test_setitem.SetitemCastingEquivalents.test_slice_key (self, obj, key, expected, warn, val, indexer_sli, is_inplace)
Definition at line 811 of file test_setitem.py.
Member Data Documentation
id
pandas.tests.series.indexing.test_setitem.SetitemCastingEquivalents.id static
Definition at line 905 of file test_setitem.py.
Referenced by scipy.cluster.hierarchy.ClusterNode.get_id(), pip._vendor.distro.distro.LinuxDistribution.info(), pip._vendor.distro.distro.LinuxDistribution.linux_distribution(), and pip._vendor.distro.distro.LinuxDistribution.version().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/tests/series/indexing/test_setitem.py