Code Cloning Analysis: pandas.io.formats.style_render Namespace Reference
pandas.io.formats.style_render Namespace Reference
Classes
class CSSDict
class StylerRenderer
class Tooltips
Functions
dict _element (str html_element, str|None html_class, Any value, bool is_visible, **kwargs)
tuple[int, int] _get_trimming_maximums (rn, cn, max_elements, max_rows=None, max_cols=None, float scaling_factor=0.8)
_get_level_lengths (Index index, bool sparsify, int max_index, Sequence[int]|None hidden_elements=None)
bool _is_visible (idx_row, idx_col, lengths)
CSSStyles format_table_styles (CSSStyles styles)
Any _default_formatter (Any x, int precision, bool thousands=False)
Callable _wrap_decimal_thousands (Callable formatter, str decimal, str|None thousands)
_str_escape (x, escape)
_render_href (x, format)
Callable _maybe_wrap_formatter (BaseFormatter|None formatter=None, str|None na_rep=None, int|None precision=None, str decimal=".", str|None thousands=None, str|None escape=None, str|None hyperlinks=None)
non_reducing_slice (Subset slice_)
CSSList maybe_convert_css_to_tuples (CSSProperties style)
list[int] refactor_levels (Level|list[Level]|None level, Index obj)
bool _parse_latex_table_wrapping (CSSStyles table_styles, str|None caption)
str|None _parse_latex_table_styles (CSSStyles table_styles, str selector)
str _parse_latex_cell_styles (CSSList latex_styles, str display_value, bool convert_css=False)
str _parse_latex_header_span (dict[str, Any] cell, str multirow_align, str multicol_align, bool wrap=False, bool convert_css=False)
str _parse_latex_options_strip (str|float value, str arg)
CSSList _parse_latex_css_conversion (CSSList styles)
str _escape_latex (str s)
str _math_mode_with_dollar (str s)
str _math_mode_with_parentheses (str s)
str _escape_latex_math (str s)
Variables
jinja2 = import_optional_dependency("jinja2", extra="DataFrame.style requires jinja2.")
BaseFormatter = Union[str, Callable]
ExtFormatter = Union[BaseFormatter, dict[Any, Optional[BaseFormatter]]]
CSSPair = tuple[str, Union[str, float]]
CSSList = list[CSSPair]
CSSProperties = Union[str, CSSList]
CSSStyles = list[CSSDict]
Subset = Union[slice, Sequence, Index]
Function Documentation
_default_formatter()
Any pandas.io.formats.style_render._default_formatter (Any x, int precision, bool thousands = False) protected
Format the display of a value
Parameters
----------
x : Any
    Input variable to be formatted
precision : Int
    Floating point precision used if ``x`` is float or complex.
thousands : bool, default False
    Whether to group digits with thousands separated with ",".
Returns
-------
value : Any
    Matches input type, or string if input is float or complex or int with sep.
Definition at line 1730 of file style_render.py.
_element()
dict pandas.io.formats.style_render._element (str html_element, str | None html_class, Any value, bool is_visible, ** kwargs) protected
Template to return container with information for a <td></td> or <th></th> element.
Definition at line 1562 of file style_render.py.
Referenced by pandas.io.formats.style_render.StylerRenderer._check_trim(), pandas.io.formats.style_render.StylerRenderer._generate_body_row(), pandas.io.formats.style_render.StylerRenderer._generate_col_header_row(), pandas.io.formats.style_render.StylerRenderer._generate_index_names_row(), and pandas.io.formats.style_render.StylerRenderer._generate_trimmed_row().
_escape_latex()
str pandas.io.formats.style_render._escape_latex (str s) protected
Replace the characters ``&``, ``%``, ``$``, ``#``, ``_``, ``{``, ``}``,
``~``, ``^``, and ``\`` in the string with LaTeX-safe sequences.
Use this if you need to display text that might contain such characters in LaTeX.
Parameters
----------
s : str
Input to be escaped
Return
------
str :
Escaped string
Definition at line 2360 of file style_render.py.
Referenced by _escape_latex_math(), _math_mode_with_dollar(), _math_mode_with_parentheses(), and _str_escape().
_escape_latex_math()
str pandas.io.formats.style_render._escape_latex_math (str s) protected
All characters in LaTeX math mode are preserved.
The substrings in LaTeX math mode, which either are surrounded
by two characters ``$`` or start with the character ``\‍(`` and end with ``\‍)``,
are preserved without escaping. Otherwise regular LaTeX escaping applies.
Parameters
----------
s : str
Input to be escaped
Return
------
str :
Escaped string
Definition at line 2464 of file style_render.py.
References _escape_latex(), _math_mode_with_dollar(), and _math_mode_with_parentheses().
Referenced by _str_escape().
_get_level_lengths()
pandas.io.formats.style_render._get_level_lengths (Index index, bool sparsify, int max_index, Sequence[int] | None hidden_elements = None) protected
Given an index, find the level length for each element.
Parameters
----------
index : Index
    Index or columns to determine lengths of each element
sparsify : bool
    Whether to hide or show each distinct element in a MultiIndex
max_index : int
    The maximum number of elements to analyse along the index due to trimming
hidden_elements : sequence of int
    Index positions of elements hidden from display in the index affecting
    length
Returns
-------
Dict :
    Result is a dictionary of (level, initial_position): span
Definition at line 1628 of file style_render.py.
Referenced by pandas.io.formats.style_render.StylerRenderer._translate(), and pandas.io.formats.style_render.StylerRenderer._translate_header().
_get_trimming_maximums()
tuple[int, int] pandas.io.formats.style_render._get_trimming_maximums (rn, cn, max_elements, max_rows = None, max_cols = None, float scaling_factor = 0.8) protected
Recursively reduce the number of rows and columns to satisfy max elements.
Parameters
----------
rn, cn : int
    The number of input rows / columns
max_elements : int
    The number of allowable elements
max_rows, max_cols : int, optional
    Directly specify an initial maximum rows or columns before compression.
scaling_factor : float
    Factor at which to reduce the number of rows / columns to fit.
Returns
-------
rn, cn : tuple
    New rn and cn values that satisfy the max_elements constraint
Definition at line 1583 of file style_render.py.
Referenced by pandas.io.formats.style_render.StylerRenderer._translate().
_is_visible()
bool pandas.io.formats.style_render._is_visible (idx_row, idx_col, lengths) protected
Index -> {(idx_row, idx_col): bool}).
Definition at line 1709 of file style_render.py.
Referenced by pandas.io.formats.style_render.StylerRenderer._generate_body_row(), pandas.io.formats.style_render.StylerRenderer._generate_col_header_row(), and pandas.io.formats.style_render.StylerRenderer._generate_index_names_row().
_math_mode_with_dollar()
str pandas.io.formats.style_render._math_mode_with_dollar (str s) protected
All characters in LaTeX math mode are preserved.
The substrings in LaTeX math mode, which start with
the character ``$`` and end with ``$``, are preserved
without escaping. Otherwise regular LaTeX escaping applies.
Parameters
----------
s : str
    Input to be escaped
Return
------
str :
    Escaped string
Definition at line 2395 of file style_render.py.
References _escape_latex().
Referenced by _escape_latex_math().
_math_mode_with_parentheses()
str pandas.io.formats.style_render._math_mode_with_parentheses (str s) protected
All characters in LaTeX math mode are preserved.
The substrings in LaTeX math mode, which start with
the character ``\‍(`` and end with ``\‍)``, are preserved
without escaping. Otherwise regular LaTeX escaping applies.
Parameters
----------
s : str
    Input to be escaped
Return
------
str :
    Escaped string
Definition at line 2428 of file style_render.py.
References _escape_latex().
Referenced by _escape_latex_math().
_maybe_wrap_formatter()
Callable pandas.io.formats.style_render._maybe_wrap_formatter (BaseFormatter | None formatter = None, str | None na_rep = None, int | None precision = None, str decimal = ".", str | None thousands = None, str | None escape = None, str | None hyperlinks = None) protected
Allows formatters to be expressed as str, callable or None, where None returns
a default formatting function. wraps with na_rep, and precision where they are
available.
Definition at line 1813 of file style_render.py.
References _render_href(), _str_escape(), and _wrap_decimal_thousands().
Referenced by pandas.io.formats.style_render.StylerRenderer.format(), and pandas.io.formats.style_render.StylerRenderer.format_index().
_parse_latex_cell_styles()
str pandas.io.formats.style_render._parse_latex_cell_styles (CSSList latex_styles, str display_value, bool convert_css = False) protected
Mutate the ``display_value`` string including LaTeX commands from ``latex_styles``.
This method builds a recursive latex chain of commands based on the
CSSList input, nested around ``display_value``.
If a CSS style is given as ('<command>', '<options>') this is translated to
'\<command><options>{display_value}', and this value is treated as the
display value for the next iteration.
The most recent style forms the inner component, for example for styles:
`[('c1', 'o1'), ('c2', 'o2')]` this returns: `\c1o1{\c2o2{display_value}}`
Sometimes latex commands have to be wrapped with curly braces in different ways:
We create some parsing flags to identify the different behaviours:
 - `--rwrap`        : `\<command><options>{<display_value>}`
 - `--wrap`         : `{\<command><options> <display_value>}`
 - `--nowrap`       : `\<command><options> <display_value>`
 - `--lwrap`        : `{\<command><options>} <display_value>`
 - `--dwrap`        : `{\<command><options>}{<display_value>}`
For example for styles:
`[('c1', 'o1--wrap'), ('c2', 'o2')]` this returns: `{\c1o1 \c2o2{display_value}}
Definition at line 2171 of file style_render.py.
References _parse_latex_css_conversion(), and _parse_latex_options_strip().
Referenced by _parse_latex_header_span().
_parse_latex_css_conversion()
CSSList pandas.io.formats.style_render._parse_latex_css_conversion (CSSList styles) protected
Convert CSS (attribute,value) pairs to equivalent LaTeX (command,options) pairs.
Ignore conversion if tagged with `--latex` option, skipped if no conversion found.
Definition at line 2284 of file style_render.py.
References _parse_latex_options_strip().
Referenced by _parse_latex_cell_styles().
_parse_latex_header_span()
str pandas.io.formats.style_render._parse_latex_header_span (dict[str, Any] cell, str multirow_align, str multicol_align, bool wrap = False, bool convert_css = False) protected
Refactor the cell `display_value` if a 'colspan' or 'rowspan' attribute is present.
'rowspan' and 'colspan' do not occur simultaneouly. If they are detected then
the `display_value` is altered to a LaTeX `multirow` or `multicol` command
respectively, with the appropriate cell-span.
``wrap`` is used to enclose the `display_value` in braces which is needed for
column headers using an siunitx package.
Requires the package {multirow}, whereas multicol support is usually built in
to the {tabular} environment.
Examples
--------
>>> cell = {'cellstyle': '', 'display_value':'text', 'attributes': 'colspan="3"'}
>>> _parse_latex_header_span(cell, 't', 'c')
'\\multicolumn{3}{c}{text}'
Definition at line 2219 of file style_render.py.
References _parse_latex_cell_styles().
_parse_latex_options_strip()
str pandas.io.formats.style_render._parse_latex_options_strip (str | float value, str arg) protected
Strip a css_value which may have latex wrapping arguments, css comment identifiers,
and whitespaces, to a valid string for latex options parsing.
For example: 'red /* --wrap */  ' --> 'red'
Definition at line 2274 of file style_render.py.
Referenced by _parse_latex_cell_styles(), and _parse_latex_css_conversion().
_parse_latex_table_styles()
str | None pandas.io.formats.style_render._parse_latex_table_styles (CSSStyles table_styles, str selector) protected
Return the first 'props' 'value' from ``tables_styles`` identified by ``selector``.
Examples
--------
>>> table_styles = [{'selector': 'foo', 'props': [('attr','value')]},
...                 {'selector': 'bar', 'props': [('attr', 'overwritten')]},
...                 {'selector': 'bar', 'props': [('a1', 'baz'), ('a2', 'ignore')]}]
>>> _parse_latex_table_styles(table_styles, selector='bar')
'baz'
Notes
-----
The replacement of "" with ":" is to avoid the CSS problem where ":" has structural
significance and cannot be used in LaTeX labels, but is often required by them.
Definition at line 2148 of file style_render.py.
_parse_latex_table_wrapping()
bool pandas.io.formats.style_render._parse_latex_table_wrapping (CSSStyles table_styles, str | None caption) protected
Indicate whether LaTeX {tabular} should be wrapped with a {table} environment.
Parses the `table_styles` and detects any selectors which must be included outside
of {tabular}, i.e. indicating that wrapping must occur, and therefore return True,
or if a caption exists and requires similar.
Definition at line 2132 of file style_render.py.
_render_href()
pandas.io.formats.style_render._render_href (x, format) protected
uses regex to detect a common URL pattern and converts to href tag in format.
Definition at line 1799 of file style_render.py.
Referenced by _maybe_wrap_formatter().
_str_escape()
pandas.io.formats.style_render._str_escape (x, escape) protected
if escaping: only use on str, else return input
Definition at line 1782 of file style_render.py.
References _escape_latex(), and _escape_latex_math().
Referenced by _maybe_wrap_formatter().
_wrap_decimal_thousands()
Callable pandas.io.formats.style_render._wrap_decimal_thousands (Callable formatter, str decimal, str | None thousands) protected
Takes a string formatting function and wraps logic to deal with thousands and
decimal parameters, in the case that they are non-standard and that the input
is a (float, complex, int).
Definition at line 1755 of file style_render.py.
Referenced by _maybe_wrap_formatter().
format_table_styles()
CSSStyles pandas.io.formats.style_render.format_table_styles (CSSStyles styles)
looks for multiple CSS selectors and separates them:
[{'selector': 'td, th', 'props': 'a:v;'}]
    ---> [{'selector': 'td', 'props': 'a:v;'},
          {'selector': 'th', 'props': 'a:v;'}]
Definition at line 1716 of file style_render.py.
Referenced by pandas.io.formats.style_render.StylerRenderer._translate().
maybe_convert_css_to_tuples()
CSSList pandas.io.formats.style_render.maybe_convert_css_to_tuples (CSSProperties style)
Convert css-string to sequence of tuples format if needed.
'color:red; border:1px solid black;' -> [('color', 'red'),
                                         ('border','1px solid red')]
Definition at line 1910 of file style_render.py.
Referenced by pandas.io.formats.style_render.Tooltips._class_styles().
non_reducing_slice()
pandas.io.formats.style_render.non_reducing_slice (Subset slice_)
Ensure that a slice doesn't reduce to a Series or Scalar.
Any user-passed `subset` should have this called on it
to make sure we're always working with DataFrames.
Definition at line 1867 of file style_render.py.
Referenced by pandas.io.formats.style_render.StylerRenderer.format().
refactor_levels()
list[int] pandas.io.formats.style_render.refactor_levels (Level | list[Level] | None level, Index obj)
Returns a consistent levels arg for use in ``hide_index`` or ``hide_columns``.
Parameters
----------
level : int, str, list
    Original ``level`` arg supplied to above methods.
obj:
    Either ``self.index`` or ``self.columns``
Returns
-------
list : refactored arg with a list of levels to hide
Definition at line 1932 of file style_render.py.
Referenced by pandas.io.formats.style_render.StylerRenderer.format_index(), and pandas.io.formats.style_render.StylerRenderer.relabel_index().
Variable Documentation
BaseFormatter
pandas.io.formats.style_render.BaseFormatter = Union[str, Callable]
Definition at line 51 of file style_render.py.
CSSList
pandas.io.formats.style_render.CSSList = list[CSSPair]
Definition at line 54 of file style_render.py.
CSSPair
pandas.io.formats.style_render.CSSPair = tuple[str, Union[str, float]]
Definition at line 53 of file style_render.py.
CSSProperties
pandas.io.formats.style_render.CSSProperties = Union[str, CSSList]
Definition at line 55 of file style_render.py.
CSSStyles
pandas.io.formats.style_render.CSSStyles = list[CSSDict]
Definition at line 63 of file style_render.py.
ExtFormatter
pandas.io.formats.style_render.ExtFormatter = Union[BaseFormatter, dict[Any, Optional[BaseFormatter]]]
Definition at line 52 of file style_render.py.
jinja2
pandas.io.formats.style_render.jinja2 = import_optional_dependency("jinja2", extra="DataFrame.style requires jinja2.")
Definition at line 48 of file style_render.py.
Subset
pandas.io.formats.style_render.Subset = Union[slice, Sequence, Index]
Definition at line 64 of file style_render.py.