Code Cloning Analysis: matplotlib.patches.ArrowStyle._Base Class Reference
matplotlib.patches.ArrowStyle._Base Class Reference
Public Member Functions
transmute (self, path, mutation_size, linewidth)
__call__ (self, path, mutation_size, linewidth, aspect_ratio=1.)
Static Public Member Functions
ensure_quadratic_bezier (path)
Detailed Description
Arrow Transmuter Base class
ArrowTransmuterBase and its derivatives are used to make a fancy
arrow around a given path. The __call__ method returns a path
(which will be used to create a PathPatch instance) and a boolean
value indicating the path is open therefore is not fillable.  This
class is not an artist and actual drawing of the fancy arrow is
done by the FancyArrowPatch class.
Definition at line 3217 of file patches.py.
Member Function Documentation
__call__()
matplotlib.patches.ArrowStyle._Base.__call__ (self, path, mutation_size, linewidth, aspect_ratio = 1.)
The __call__ method is a thin wrapper around the transmute method
and takes care of the aspect ratio.
Definition at line 3263 of file patches.py.
References transmute().
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), scipy.interpolate._fitpack2.SphereBivariateSpline.ev(), matplotlib.ticker.Formatter.format_data(), and matplotlib.ticker.LogFormatter.format_data().
ensure_quadratic_bezier()
matplotlib.patches.ArrowStyle._Base.ensure_quadratic_bezier (path) static
Some ArrowStyle classes only works with a simple quadratic
Bézier curve (created with `.ConnectionStyle.Arc3` or
`.ConnectionStyle.Angle3`). This static method checks if the
provided path is a simple quadratic Bézier curve and returns its
control points if true.
Definition at line 3234 of file patches.py.
Referenced by matplotlib.patches.ArrowStyle.Fancy.transmute(), matplotlib.patches.ArrowStyle.Simple.transmute(), and matplotlib.patches.ArrowStyle.Wedge.transmute().
transmute()
matplotlib.patches.ArrowStyle._Base.transmute (self, path, mutation_size, linewidth)
The transmute method is the very core of the ArrowStyle class and
must be overridden in the subclasses. It receives the *path*
object along which the arrow will be drawn, and the
*mutation_size*, with which the arrow head etc. will be scaled.
The *linewidth* may be used to adjust the path so that it does not
pass beyond the given points. It returns a tuple of a `.Path`
instance and a boolean. The boolean value indicate whether the
path can be filled or not. The return value can also be a list of
paths and list of booleans of the same length.
Reimplemented in matplotlib.patches.ArrowStyle._Curve, matplotlib.patches.ArrowStyle.Fancy, matplotlib.patches.ArrowStyle.Simple, and matplotlib.patches.ArrowStyle.Wedge.
Definition at line 3249 of file patches.py.
Referenced by __call__().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/patches.py