Code Cloning Analysis: fontTools.mtiLib.DeferredMapping Class Reference
fontTools.mtiLib.DeferredMapping Class Reference
Public Member Functions
__init__ (self)
addDeferredMapping (self, setter, sym, e)
applyDeferredMappings (self)
Protected Attributes
list _deferredMappings = []
Detailed Description
Definition at line 95 of file __init__.py.
Constructor & Destructor Documentation
__init__()
fontTools.mtiLib.DeferredMapping.__init__ (self)
Definition at line 96 of file __init__.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
addDeferredMapping()
fontTools.mtiLib.DeferredMapping.addDeferredMapping (self, setter, sym, e)
Definition at line 99 of file __init__.py.
applyDeferredMappings()
fontTools.mtiLib.DeferredMapping.applyDeferredMappings (self)
Definition at line 103 of file __init__.py.
Member Data Documentation
_deferredMappings
list fontTools.mtiLib.DeferredMapping._deferredMappings = [] protected
Definition at line 97 of file __init__.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/mtiLib/__init__.py