Code Cloning Analysis: scipy.io.tests.test_netcdf Namespace Reference
scipy.io.tests.test_netcdf Namespace Reference
Functions
make_simple (*args, **kwargs)
check_simple (ncfileobj)
assert_mask_matches (arr, expected_mask)
test_read_write_files ()
test_read_write_sio ()
test_bytes ()
test_encoded_fill_value ()
test_read_example_data ()
test_itemset_no_segfault_on_readonly ()
test_appending_issue_gh_8625 ()
test_write_invalid_dtype ()
test_flush_rewind ()
test_dtype_specifiers ()
test_ticket_1720 ()
test_mmaps_segfault ()
test_zero_dimensional_var ()
test_byte_gatts ()
test_open_append ()
test_append_recordDimension ()
test_maskandscale ()
test_read_withValuesNearFillValue ()
test_read_withNoFillValue ()
test_read_withFillValueAndMissingValue ()
test_read_withMissingValue ()
test_read_withFillValNaN ()
test_read_withChar ()
test_read_with2dVar ()
test_read_withMaskAndScaleFalse ()
Variables
TEST_DATA_PATH = pjoin(dirname(__file__), 'data')
int N_EG_ELS = 11
str VARTYPE_EG = 'b'
Detailed Description
 Tests for netcdf
Function Documentation
assert_mask_matches()
scipy.io.tests.test_netcdf.assert_mask_matches (arr, expected_mask)
Asserts that the mask of arr is effectively the same as expected_mask.
In contrast to numpy.ma.testutils.assert_mask_equal, this function allows
testing the 'mask' of a standard numpy array (the mask in this case is treated
as all False).
Parameters
----------
arr : ndarray or MaskedArray
    Array to test.
expected_mask : array_like of booleans
    A list giving the expected mask.
Definition at line 46 of file test_netcdf.py.
References assert_mask_matches(), and check_simple().
Referenced by assert_mask_matches().
check_simple()
scipy.io.tests.test_netcdf.check_simple (ncfileobj)
Example fileobj tests
Definition at line 38 of file test_netcdf.py.
Referenced by assert_mask_matches().
make_simple()
scipy.io.tests.test_netcdf.make_simple (* args, ** kwargs)
Definition at line 26 of file test_netcdf.py.
test_append_recordDimension()
scipy.io.tests.test_netcdf.test_append_recordDimension ()
Definition at line 401 of file test_netcdf.py.
test_appending_issue_gh_8625()
scipy.io.tests.test_netcdf.test_appending_issue_gh_8625 ()
Definition at line 256 of file test_netcdf.py.
test_byte_gatts()
scipy.io.tests.test_netcdf.test_byte_gatts ()
Definition at line 365 of file test_netcdf.py.
test_bytes()
scipy.io.tests.test_netcdf.test_bytes ()
Definition at line 172 of file test_netcdf.py.
test_dtype_specifiers()
scipy.io.tests.test_netcdf.test_dtype_specifiers ()
Definition at line 298 of file test_netcdf.py.
test_encoded_fill_value()
scipy.io.tests.test_netcdf.test_encoded_fill_value ()
Definition at line 221 of file test_netcdf.py.
test_flush_rewind()
scipy.io.tests.test_netcdf.test_flush_rewind ()
Definition at line 284 of file test_netcdf.py.
test_itemset_no_segfault_on_readonly()
scipy.io.tests.test_netcdf.test_itemset_no_segfault_on_readonly ()
Definition at line 241 of file test_netcdf.py.
test_maskandscale()
scipy.io.tests.test_netcdf.test_maskandscale ()
Definition at line 441 of file test_netcdf.py.
test_mmaps_segfault()
scipy.io.tests.test_netcdf.test_mmaps_segfault ()
Definition at line 332 of file test_netcdf.py.
test_open_append()
scipy.io.tests.test_netcdf.test_open_append ()
Definition at line 380 of file test_netcdf.py.
test_read_example_data()
scipy.io.tests.test_netcdf.test_read_example_data ()
Definition at line 232 of file test_netcdf.py.
test_read_with2dVar()
scipy.io.tests.test_netcdf.test_read_with2dVar ()
Definition at line 528 of file test_netcdf.py.
test_read_withChar()
scipy.io.tests.test_netcdf.test_read_withChar ()
Definition at line 522 of file test_netcdf.py.
test_read_withFillValNaN()
scipy.io.tests.test_netcdf.test_read_withFillValNaN ()
Definition at line 516 of file test_netcdf.py.
test_read_withFillValueAndMissingValue()
scipy.io.tests.test_netcdf.test_read_withFillValueAndMissingValue ()
Definition at line 498 of file test_netcdf.py.
test_read_withMaskAndScaleFalse()
scipy.io.tests.test_netcdf.test_read_withMaskAndScaleFalse ()
Definition at line 534 of file test_netcdf.py.
test_read_withMissingValue()
scipy.io.tests.test_netcdf.test_read_withMissingValue ()
Definition at line 508 of file test_netcdf.py.
test_read_withNoFillValue()
scipy.io.tests.test_netcdf.test_read_withNoFillValue ()
Definition at line 489 of file test_netcdf.py.
test_read_withValuesNearFillValue()
scipy.io.tests.test_netcdf.test_read_withValuesNearFillValue ()
Definition at line 482 of file test_netcdf.py.
test_read_write_files()
scipy.io.tests.test_netcdf.test_read_write_files ()
Definition at line 66 of file test_netcdf.py.
test_read_write_sio()
scipy.io.tests.test_netcdf.test_read_write_sio ()
Definition at line 144 of file test_netcdf.py.
test_ticket_1720()
scipy.io.tests.test_netcdf.test_ticket_1720 ()
Definition at line 309 of file test_netcdf.py.
test_write_invalid_dtype()
scipy.io.tests.test_netcdf.test_write_invalid_dtype ()
Definition at line 271 of file test_netcdf.py.
test_zero_dimensional_var()
scipy.io.tests.test_netcdf.test_zero_dimensional_var ()
Definition at line 355 of file test_netcdf.py.
Variable Documentation
N_EG_ELS
int scipy.io.tests.test_netcdf.N_EG_ELS = 11
Definition at line 21 of file test_netcdf.py.
TEST_DATA_PATH
scipy.io.tests.test_netcdf.TEST_DATA_PATH = pjoin(dirname(__file__), 'data')
Definition at line 19 of file test_netcdf.py.
VARTYPE_EG
str scipy.io.tests.test_netcdf.VARTYPE_EG = 'b'
Definition at line 22 of file test_netcdf.py.