Code Cloning Analysis: scipy.linalg._matfuncs_inv_ssq Namespace Reference
scipy.linalg._matfuncs_inv_ssq Namespace Reference
Classes
class _MatrixM1PowerOperator
class FractionalMatrixPowerError
class LogmError
class LogmExactlySingularWarning
class LogmNearlySingularWarning
class LogmRankWarning
Functions
_onenormest_m1_power (A, p, t=2, itmax=5, compute_v=False, compute_w=False)
_unwindk (z)
_briggs_helper_function (a, k)
_fractional_power_superdiag_entry (l1, l2, t12, p)
_logm_superdiag_entry (l1, l2, t12)
_inverse_squaring_helper (T0, theta)
_fractional_power_pade_constant (i, t)
_fractional_power_pade (R, t, m)
_remainder_matrix_power_triu (T, t)
_remainder_matrix_power (A, t)
_fractional_matrix_power (A, p)
_logm_triu (T)
_logm_force_nonsingular_triangular_matrix (T, inplace=False)
_logm (A)
Detailed Description
Matrix functions that use Pade approximation with inverse scaling and squaring.
Function Documentation
_briggs_helper_function()
scipy.linalg._matfuncs_inv_ssq._briggs_helper_function (a, k) protected
Computes r = a^(1 / (2^k)) - 1.
This is algorithm (2) of [1]_.
The purpose is to avoid a danger of subtractive cancellation.
For more computational efficiency it should probably be cythonized.
Parameters
----------
a : complex
    A complex number.
k : integer
    A nonnegative integer.
Returns
-------
r : complex
    The value r = a^(1 / (2^k)) - 1 computed with less cancellation.
Notes
-----
The algorithm as formulated in the reference does not handle k=0 or k=1
correctly, so these are special-cased in this implementation.
This function is intended to not allow `a` to belong to the closed
negative real axis, but this constraint is relaxed.
References
----------
.. [1] Awad H. Al-Mohy (2012)
       "A more accurate Briggs method for the logarithm",
       Numerical Algorithms, 59 : 393--402.
Definition at line 154 of file _matfuncs_inv_ssq.py.
Referenced by _inverse_squaring_helper().
_fractional_matrix_power()
scipy.linalg._matfuncs_inv_ssq._fractional_matrix_power (A, p) protected
Compute the fractional power of a matrix.
See the fractional_matrix_power docstring in matfuncs.py for more info.
Definition at line 671 of file _matfuncs_inv_ssq.py.
References _remainder_matrix_power(), scipy.linalg._matfuncs.funm(), and scipy.linalg._decomp_svd.svdvals().
Referenced by scipy.linalg._matfuncs.fractional_matrix_power().
_fractional_power_pade()
scipy.linalg._matfuncs_inv_ssq._fractional_power_pade (R, t, m) protected
Evaluate the Pade approximation of a fractional matrix power.
Evaluate the degree-m Pade approximation of R
to the fractional matrix power t using the continued fraction
in bottom-up fashion using algorithm (4.1) in [1]_.
Parameters
----------
R : (N, N) array_like
    Upper triangular matrix whose fractional power to evaluate.
t : float
    Fractional power between -1 and 1 exclusive.
m : positive integer
    Degree of Pade approximation.
Returns
-------
U : (N, N) array_like
    The degree-m Pade approximation of R to the fractional power t.
    This matrix will be upper triangular.
References
----------
.. [1] Nicholas J. Higham and Lijing lin (2011)
       "A Schur-Pade Algorithm for Fractional Powers of a Matrix."
       SIAM Journal on Matrix Analysis and Applications,
       32 (3). pp. 1056-1078. ISSN 0895-4798
Definition at line 467 of file _matfuncs_inv_ssq.py.
References scipy.linalg._basic.solve_triangular().
Referenced by _remainder_matrix_power_triu().
_fractional_power_pade_constant()
scipy.linalg._matfuncs_inv_ssq._fractional_power_pade_constant (i, t) protected
Definition at line 449 of file _matfuncs_inv_ssq.py.
_fractional_power_superdiag_entry()
scipy.linalg._matfuncs_inv_ssq._fractional_power_superdiag_entry (l1, l2, t12, p) protected
Compute a superdiagonal entry of a fractional matrix power.
This is Eq. (5.6) in [1]_.
Parameters
----------
l1 : complex
    A diagonal entry of the matrix.
l2 : complex
    A diagonal entry of the matrix.
t12 : complex
    A superdiagonal entry of the matrix.
p : float
    A fractional power.
Returns
-------
f12 : complex
    A superdiagonal entry of the fractional matrix power.
Notes
-----
Care has been taken to return a real number if possible when
all of the inputs are real numbers.
References
----------
.. [1] Nicholas J. Higham and Lijing lin (2011)
       "A Schur-Pade Algorithm for Fractional Powers of a Matrix."
       SIAM Journal on Matrix Analysis and Applications,
       32 (3). pp. 1056-1078. ISSN 0895-4798
Definition at line 209 of file _matfuncs_inv_ssq.py.
References _unwindk().
Referenced by _inverse_squaring_helper(), and _remainder_matrix_power_triu().
_inverse_squaring_helper()
scipy.linalg._matfuncs_inv_ssq._inverse_squaring_helper (T0, theta) protected
A helper function for inverse scaling and squaring for Pade approximation.
Parameters
----------
T0 : (N, N) array_like upper triangular
    Matrix involved in inverse scaling and squaring.
theta : indexable
    The values theta[1] .. theta[7] must be available.
    They represent bounds related to Pade approximation, and they depend
    on the matrix function which is being computed.
    For example, different values of theta are required for
    matrix logarithm than for fractional matrix power.
Returns
-------
R : (N, N) array_like upper triangular
    Composition of zero or more matrix square roots of T0, minus I.
s : non-negative integer
    Number of square roots taken.
m : positive integer
    The degree of the Pade approximation.
Notes
-----
This subroutine appears as a chunk of lines within
a couple of published algorithms; for example it appears
as lines 4--35 in algorithm (3.1) of [1]_, and
as lines 3--34 in algorithm (4.1) of [2]_.
The instances of 'goto line 38' in algorithm (3.1) of [1]_
probably mean 'goto line 36' and have been intepreted accordingly.
References
----------
.. [1] Nicholas J. Higham and Lijing Lin (2013)
       "An Improved Schur-Pade Algorithm for Fractional Powers
       of a Matrix and their Frechet Derivatives."
.. [2] Awad H. Al-Mohy and Nicholas J. Higham (2012)
       "Improved Inverse Scaling and Squaring Algorithms
       for the Matrix Logarithm."
       SIAM Journal on Scientific Computing, 34 (4). C152-C169.
       ISSN 1095-7197
Definition at line 312 of file _matfuncs_inv_ssq.py.
References _briggs_helper_function(), _fractional_power_superdiag_entry(), and _onenormest_m1_power().
Referenced by _logm_triu(), and _remainder_matrix_power_triu().
_logm()
scipy.linalg._matfuncs_inv_ssq._logm (A) protected
Compute the matrix logarithm.
See the logm docstring in matfuncs.py for more info.
Notes
-----
In this function we look at triangular matrices that are similar
to the input matrix. If any diagonal entry of such a triangular matrix
is exactly zero then the original matrix is singular.
The matrix logarithm does not exist for such matrices,
but in such cases we will pretend that the diagonal entries that are zero
are actually slightly positive by an ad-hoc amount, in the interest
of returning something more useful than NaN. This will cause a warning.
Definition at line 840 of file _matfuncs_inv_ssq.py.
References _logm_triu(), scipy.linalg._decomp_schur.rsf2csf(), and scipy.linalg._decomp_schur.schur().
Referenced by scipy.linalg._matfuncs.logm().
_logm_force_nonsingular_triangular_matrix()
scipy.linalg._matfuncs_inv_ssq._logm_force_nonsingular_triangular_matrix (T, inplace = False) protected
Definition at line 820 of file _matfuncs_inv_ssq.py.
_logm_superdiag_entry()
scipy.linalg._matfuncs_inv_ssq._logm_superdiag_entry (l1, l2, t12) protected
Compute a superdiagonal entry of a matrix logarithm.
This is like Eq. (11.28) in [1]_, except the determination of whether
l1 and l2 are sufficiently far apart has been modified.
Parameters
----------
l1 : complex
    A diagonal entry of the matrix.
l2 : complex
    A diagonal entry of the matrix.
t12 : complex
    A superdiagonal entry of the matrix.
Returns
-------
f12 : complex
    A superdiagonal entry of the matrix logarithm.
Notes
-----
Care has been taken to return a real number if possible when
all of the inputs are real numbers.
References
----------
.. [1] Nicholas J. Higham (2008)
       "Functions of Matrices: Theory and Computation"
       ISBN 978-0-898716-46-7
Definition at line 265 of file _matfuncs_inv_ssq.py.
References _unwindk().
Referenced by _logm_triu().
_logm_triu()
scipy.linalg._matfuncs_inv_ssq._logm_triu (T) protected
Compute matrix logarithm of an upper triangular matrix.
The matrix logarithm is the inverse of
expm: expm(logm(`T`)) == `T`
Parameters
----------
T : (N, N) array_like
    Upper triangular matrix whose logarithm to evaluate
Returns
-------
logm : (N, N) ndarray
    Matrix logarithm of `T`
References
----------
.. [1] Awad H. Al-Mohy and Nicholas J. Higham (2012)
       "Improved Inverse Scaling and Squaring Algorithms
       for the Matrix Logarithm."
       SIAM Journal on Scientific Computing, 34 (4). C152-C169.
       ISSN 1095-7197
.. [2] Nicholas J. Higham (2008)
       "Functions of Matrices: Theory and Computation"
       ISBN 978-0-898716-46-7
.. [3] Nicholas J. Higham and Lijing lin (2011)
       "A Schur-Pade Algorithm for Fractional Powers of a Matrix."
       SIAM Journal on Matrix Analysis and Applications,
       32 (3). pp. 1056-1078. ISSN 0895-4798
Definition at line 721 of file _matfuncs_inv_ssq.py.
References _inverse_squaring_helper(), _logm_superdiag_entry(), and scipy.linalg._basic.solve_triangular().
Referenced by _logm().
_onenormest_m1_power()
scipy.linalg._matfuncs_inv_ssq._onenormest_m1_power (A, p, t = 2, itmax = 5, compute_v = False, compute_w = False) protected
Efficiently estimate the 1-norm of (A - I)^p.
Parameters
----------
A : ndarray
    Matrix whose 1-norm of a power is to be computed.
p : int
    Non-negative integer power.
t : int, optional
    A positive parameter controlling the tradeoff between
    accuracy versus time and memory usage.
    Larger values take longer and use more memory
    but give more accurate output.
itmax : int, optional
    Use at most this many iterations.
compute_v : bool, optional
    Request a norm-maximizing linear operator input vector if True.
compute_w : bool, optional
    Request a norm-maximizing linear operator output vector if True.
Returns
-------
est : float
    An underestimate of the 1-norm of the sparse matrix.
v : ndarray, optional
    The vector such that ||Av||_1 == est*||v||_1.
    It can be thought of as an input to the linear operator
    that gives an output with particularly large norm.
w : ndarray, optional
    The vector Av which has relatively large 1-norm.
    It can be thought of as an output of the linear operator
    that is relatively large in norm compared to the input.
Definition at line 74 of file _matfuncs_inv_ssq.py.
Referenced by _inverse_squaring_helper().
_remainder_matrix_power()
scipy.linalg._matfuncs_inv_ssq._remainder_matrix_power (A, t) protected
Compute the fractional power of a matrix, for fractions -1 < t < 1.
This uses algorithm (3.1) of [1]_.
The Pade approximation itself uses algorithm (4.1) of [2]_.
Parameters
----------
A : (N, N) array_like
    Matrix whose fractional power to evaluate.
t : float
    Fractional power between -1 and 1 exclusive.
Returns
-------
X : (N, N) array_like
    The fractional power of the matrix.
References
----------
.. [1] Nicholas J. Higham and Lijing Lin (2013)
       "An Improved Schur-Pade Algorithm for Fractional Powers
       of a Matrix and their Frechet Derivatives."
.. [2] Nicholas J. Higham and Lijing lin (2011)
       "A Schur-Pade Algorithm for Fractional Powers of a Matrix."
       SIAM Journal on Matrix Analysis and Applications,
       32 (3). pp. 1056-1078. ISSN 0895-4798
Definition at line 596 of file _matfuncs_inv_ssq.py.
References _remainder_matrix_power_triu(), scipy.linalg._decomp_schur.rsf2csf(), and scipy.linalg._decomp_schur.schur().
Referenced by _fractional_matrix_power().
_remainder_matrix_power_triu()
scipy.linalg._matfuncs_inv_ssq._remainder_matrix_power_triu (T, t) protected
Compute a fractional power of an upper triangular matrix.
The fractional power is restricted to fractions -1 < t < 1.
This uses algorithm (3.1) of [1]_.
The Pade approximation itself uses algorithm (4.1) of [2]_.
Parameters
----------
T : (N, N) array_like
    Upper triangular matrix whose fractional power to evaluate.
t : float
    Fractional power between -1 and 1 exclusive.
Returns
-------
X : (N, N) array_like
    The fractional power of the matrix.
References
----------
.. [1] Nicholas J. Higham and Lijing Lin (2013)
       "An Improved Schur-Pade Algorithm for Fractional Powers
       of a Matrix and their Frechet Derivatives."
.. [2] Nicholas J. Higham and Lijing lin (2011)
       "A Schur-Pade Algorithm for Fractional Powers of a Matrix."
       SIAM Journal on Matrix Analysis and Applications,
       32 (3). pp. 1056-1078. ISSN 0895-4798
Definition at line 517 of file _matfuncs_inv_ssq.py.
References _fractional_power_pade(), _fractional_power_superdiag_entry(), and _inverse_squaring_helper().
Referenced by _remainder_matrix_power().
_unwindk()
scipy.linalg._matfuncs_inv_ssq._unwindk (z) protected
Compute the scalar unwinding number.
Uses Eq. (5.3) in [1]_, and should be equal to (z - log(exp(z)) / (2 pi i).
Note that this definition differs in sign from the original definition
in equations (5, 6) in [2]_.  The sign convention is justified in [3]_.
Parameters
----------
z : complex
    A complex number.
Returns
-------
unwinding_number : integer
    The scalar unwinding number of z.
References
----------
.. [1] Nicholas J. Higham and Lijing lin (2011)
       "A Schur-Pade Algorithm for Fractional Powers of a Matrix."
       SIAM Journal on Matrix Analysis and Applications,
       32 (3). pp. 1056-1078. ISSN 0895-4798
.. [2] Robert M. Corless and David J. Jeffrey,
       "The unwinding number." Newsletter ACM SIGSAM Bulletin
       Volume 30, Issue 2, June 1996, Pages 28-35.
.. [3] Russell Bradford and Robert M. Corless and James H. Davenport and
       David J. Jeffrey and Stephen M. Watt,
       "Reasoning about the elementary functions of complex analysis"
       Annals of Mathematics and Artificial Intelligence,
       36: 303-318, 2002.
Definition at line 115 of file _matfuncs_inv_ssq.py.
Referenced by _fractional_power_superdiag_entry(), and _logm_superdiag_entry().