Code Cloning Analysis: sklearn.datasets._base Namespace Reference
sklearn.datasets._base Namespace Reference
Functions
str get_data_home (data_home=None)
clear_data_home (data_home=None)
_convert_data_dataframe (caller_name, data, target, feature_names, target_names, sparse_data=False)
load_files (container_path, *, description=None, categories=None, load_content=True, shuffle=True, encoding=None, decode_error="strict", random_state=0, allowed_extensions=None)
load_csv_data (data_file_name, *, data_module=DATA_MODULE, descr_file_name=None, descr_module=DESCR_MODULE, encoding="utf-8")
load_gzip_compressed_csv_data (data_file_name, *, data_module=DATA_MODULE, descr_file_name=None, descr_module=DESCR_MODULE, encoding="utf-8", **kwargs)
load_descr (descr_file_name, *, descr_module=DESCR_MODULE, encoding="utf-8")
load_wine (*, return_X_y=False, as_frame=False)
load_iris (*, return_X_y=False, as_frame=False)
load_breast_cancer (*, return_X_y=False, as_frame=False)
load_digits (*, n_class=10, return_X_y=False, as_frame=False)
load_diabetes (*, return_X_y=False, as_frame=False, scaled=True)
load_linnerud (*, return_X_y=False, as_frame=False)
load_sample_images ()
load_sample_image (image_name)
_pkl_filepath (*args, **kwargs)
_sha256 (path)
_fetch_remote (remote, dirname=None, n_retries=3, delay=1)
_filter_filename (value, filter_dots=True)
_derive_folder_and_filename_from_url (url)
fetch_file (url, folder=None, local_filename=None, sha256=None, n_retries=3, delay=1)
Variables
str DATA_MODULE = "sklearn.datasets.data"
str DESCR_MODULE = "sklearn.datasets.descr"
str IMAGES_MODULE = "sklearn.datasets.images"
RemoteFileMetadata = namedtuple("RemoteFileMetadata", ["filename", "url", "checksum"])
Detailed Description
Base IO code for all datasets
Function Documentation
_convert_data_dataframe()
sklearn.datasets._base._convert_data_dataframe (caller_name, data, target, feature_names, target_names, sparse_data = False) protected
Definition at line 113 of file _base.py.
_derive_folder_and_filename_from_url()
sklearn.datasets._base._derive_folder_and_filename_from_url (url) protected
Definition at line 1561 of file _base.py.
_fetch_remote()
sklearn.datasets._base._fetch_remote (remote, dirname = None, n_retries = 3, delay = 1) protected
Helper function to download a remote dataset.
Fetch a dataset pointed by remote's url, save into path using remote's
filename and ensure its integrity based on the SHA256 checksum of the
downloaded file.
.. versionchanged:: 1.6
    If the file already exists locally and the SHA256 checksums match, the
    path to the local file is returned without re-downloading.
Parameters
----------
remote : RemoteFileMetadata
    Named tuple containing remote dataset meta information: url, filename
    and checksum.
dirname : str or Path, default=None
    Directory to save the file to. If None, the current working directory
    is used.
n_retries : int, default=3
    Number of retries when HTTP errors are encountered.
    .. versionadded:: 1.5
delay : int, default=1
    Number of seconds between retries.
    .. versionadded:: 1.5
Returns
-------
file_path: Path
    Full path of the created file.
Definition at line 1433 of file _base.py.
References _sha256().
Referenced by fetch_file().
_filter_filename()
sklearn.datasets._base._filter_filename (value, filter_dots = True) protected
Derive a name that is safe to use as filename from the given string.
Adapted from the `slugify` function of django:
https://github.com/django/django/blob/master/django/utils/text.py
Convert spaces or repeated dashes to single dashes. Replace characters that
aren't alphanumerics, underscores, hyphens or dots by underscores. Convert
to lowercase. Also strip leading and trailing whitespace, dashes, and
underscores.
Definition at line 1541 of file _base.py.
References _filter_filename().
Referenced by _filter_filename().
_pkl_filepath()
sklearn.datasets._base._pkl_filepath (* args, ** kwargs) protected
Return filename for Python 3 pickles
args[-1] is expected to be the ".pkl" filename. For compatibility with
older scikit-learn versions, a suffix is inserted before the extension.
_pkl_filepath('/path/to/folder', 'filename.pkl') returns
'/path/to/folder/filename_py3.pkl'
Definition at line 1403 of file _base.py.
_sha256()
sklearn.datasets._base._sha256 (path) protected
Calculate the sha256 hash of the file at path.
Definition at line 1420 of file _base.py.
Referenced by _fetch_remote().
clear_data_home()
sklearn.datasets._base.clear_data_home (data_home = None)
Delete all the content of the data home cache.
Parameters
----------
data_home : str or path-like, default=None
    The path to scikit-learn data directory. If `None`, the default path
    is `~/scikit_learn_data`.
Examples
--------
>>> from sklearn.datasets import clear_data_home
>>> clear_data_home()  # doctest: +SKIP
Definition at line 95 of file _base.py.
References get_data_home().
fetch_file()
sklearn.datasets._base.fetch_file (url, folder = None, local_filename = None, sha256 = None, n_retries = 3, delay = 1)
Fetch a file from the web if not already present in the local folder.
If the file already exists locally (and the SHA256 checksums match when
provided), the path to the local file is returned without re-downloading.
.. versionadded:: 1.6
Parameters
----------
url : str
    URL of the file to download.
folder : str or Path, default=None
    Directory to save the file to. If None, the file is downloaded in a
    folder with a name derived from the URL host name and path under
    scikit-learn data home folder.
local_filename : str, default=None
    Name of the file to save. If None, the filename is inferred from the
    URL.
sha256 : str, default=None
    SHA256 checksum of the file. If None, no checksum is verified.
n_retries : int, default=3
    Number of retries when HTTP errors are encountered.
delay : int, default=1
    Number of seconds between retries.
Returns
-------
file_path : Path
    Full path of the downloaded file.
Definition at line 1584 of file _base.py.
References _fetch_remote(), and get_data_home().
get_data_home()
str sklearn.datasets._base.get_data_home (data_home = None)
Return the path of the scikit-learn data directory.
This folder is used by some large dataset loaders to avoid downloading the
data several times.
By default the data directory is set to a folder named 'scikit_learn_data' in the
user home folder.
Alternatively, it can be set by the 'SCIKIT_LEARN_DATA' environment
variable or programmatically by giving an explicit folder path. The '~'
symbol is expanded to the user home folder.
If the folder does not already exist, it is automatically created.
Parameters
----------
data_home : str or path-like, default=None
    The path to scikit-learn data directory. If `None`, the default path
    is `~/scikit_learn_data`.
Returns
-------
data_home: str
    The path to scikit-learn data directory.
Examples
--------
>>> import os
>>> from sklearn.datasets import get_data_home
>>> data_home_path = get_data_home()
>>> os.path.exists(data_home_path)
True
Definition at line 48 of file _base.py.
Referenced by clear_data_home(), and fetch_file().
load_breast_cancer()
sklearn.datasets._base.load_breast_cancer (* , return_X_y = False, as_frame = False)
Load and return the breast cancer Wisconsin dataset (classification).
The breast cancer dataset is a classic and very easy binary classification
dataset.
=================   ==============
Classes                          2
Samples per class    212(M),357(B)
Samples total                  569
Dimensionality                  30
Features            real, positive
=================   ==============
The copy of UCI ML Breast Cancer Wisconsin (Diagnostic) dataset is
downloaded from:
https://archive.ics.uci.edu/dataset/17/breast+cancer+wisconsin+diagnostic
Read more in the :ref:`User Guide <breast_cancer_dataset>`.
Parameters
----------
return_X_y : bool, default=False
    If True, returns ``(data, target)`` instead of a Bunch object.
    See below for more information about the `data` and `target` object.
    .. versionadded:: 0.18
as_frame : bool, default=False
    If True, the data is a pandas DataFrame including columns with
    appropriate dtypes (numeric). The target is
    a pandas DataFrame or Series depending on the number of target columns.
    If `return_X_y` is True, then (`data`, `target`) will be pandas
    DataFrames or Series as described below.
    .. versionadded:: 0.23
Returns
-------
data : :class:`~sklearn.utils.Bunch`
    Dictionary-like object, with the following attributes.
    data : {ndarray, dataframe} of shape (569, 30)
        The data matrix. If `as_frame=True`, `data` will be a pandas
        DataFrame.
    target : {ndarray, Series} of shape (569,)
        The classification target. If `as_frame=True`, `target` will be
        a pandas Series.
    feature_names : ndarray of shape (30,)
        The names of the dataset columns.
    target_names : ndarray of shape (2,)
        The names of target classes.
    frame : DataFrame of shape (569, 31)
        Only present when `as_frame=True`. DataFrame with `data` and
        `target`.
        .. versionadded:: 0.23
    DESCR : str
        The full description of the dataset.
    filename : str
        The path to the location of the data.
        .. versionadded:: 0.20
(data, target) : tuple if ``return_X_y`` is True
    A tuple of two ndarrays by default. The first contains a 2D ndarray of
    shape (569, 30) with each row representing one sample and each column
    representing the features. The second ndarray of shape (569,) contains
    the target samples.  If `as_frame=True`, both arrays are pandas objects,
    i.e. `X` a dataframe and `y` a series.
    .. versionadded:: 0.18
Examples
--------
Let's say you are interested in the samples 10, 50, and 85, and want to
know their class name.
>>> from sklearn.datasets import load_breast_cancer
>>> data = load_breast_cancer()
>>> data.target[[10, 50, 85]]
array([0, 1, 0])
>>> list(data.target_names)
[np.str_('malignant'), np.str_('benign')]
Definition at line 753 of file _base.py.
References load_csv_data().
load_csv_data()
sklearn.datasets._base.load_csv_data (data_file_name, * , data_module = DATA_MODULE, descr_file_name = None, descr_module = DESCR_MODULE, encoding = "utf-8")
Loads `data_file_name` from `data_module with `importlib.resources`.
Parameters
----------
data_file_name : str
    Name of csv file to be loaded from `data_module/data_file_name`.
    For example `'wine_data.csv'`.
data_module : str or module, default='sklearn.datasets.data'
    Module where data lives. The default is `'sklearn.datasets.data'`.
descr_file_name : str, default=None
    Name of rst file to be loaded from `descr_module/descr_file_name`.
    For example `'wine_data.rst'`. See also :func:`load_descr`.
    If not None, also returns the corresponding description of
    the dataset.
descr_module : str or module, default='sklearn.datasets.descr'
    Module where `descr_file_name` lives. See also :func:`load_descr`.
    The default is `'sklearn.datasets.descr'`.
Returns
-------
data : ndarray of shape (n_samples, n_features)
    A 2D array with each row representing one sample and each column
    representing the features of a given sample.
target : ndarry of shape (n_samples,)
    A 1D array holding target variables for all the samples in `data`.
    For example target[0] is the target variable for data[0].
target_names : ndarry of shape (n_samples,)
    A 1D array containing the names of the classifications. For example
    target_names[0] is the name of the target[0] class.
descr : str, optional
    Description of the dataset (the content of `descr_file_name`).
    Only returned if `descr_file_name` is not None.
encoding : str, optional
    Text encoding of the CSV file.
    .. versionadded:: 1.4
Definition at line 325 of file _base.py.
References load_descr().
Referenced by load_breast_cancer(), load_iris(), and load_wine().
load_descr()
sklearn.datasets._base.load_descr (descr_file_name, * , descr_module = DESCR_MODULE, encoding = "utf-8")
Load `descr_file_name` from `descr_module` with `importlib.resources`.
Parameters
----------
descr_file_name : str, default=None
    Name of rst file to be loaded from `descr_module/descr_file_name`.
    For example `'wine_data.rst'`. See also :func:`load_descr`.
    If not None, also returns the corresponding description of
    the dataset.
descr_module : str or module, default='sklearn.datasets.descr'
    Module where `descr_file_name` lives. See also :func:`load_descr`.
    The default  is `'sklearn.datasets.descr'`.
encoding : str, default="utf-8"
    Name of the encoding that `descr_file_name` will be decoded with.
    The default is 'utf-8'.
    .. versionadded:: 1.4
Returns
-------
fdescr : str
    Content of `descr_file_name`.
Definition at line 464 of file _base.py.
Referenced by load_csv_data(), load_diabetes(), load_gzip_compressed_csv_data(), load_linnerud(), and load_sample_images().
load_diabetes()
sklearn.datasets._base.load_diabetes (* , return_X_y = False, as_frame = False, scaled = True)
Load and return the diabetes dataset (regression).
==============   ==================
Samples total    442
Dimensionality   10
Features         real, -.2 < x < .2
Targets          integer 25 - 346
==============   ==================
.. note::
   The meaning of each feature (i.e. `feature_names`) might be unclear
   (especially for `ltg`) as the documentation of the original dataset is
   not explicit. We provide information that seems correct in regard with
   the scientific literature in this field of research.
Read more in the :ref:`User Guide <diabetes_dataset>`.
Parameters
----------
return_X_y : bool, default=False
    If True, returns ``(data, target)`` instead of a Bunch object.
    See below for more information about the `data` and `target` object.
    .. versionadded:: 0.18
as_frame : bool, default=False
    If True, the data is a pandas DataFrame including columns with
    appropriate dtypes (numeric). The target is
    a pandas DataFrame or Series depending on the number of target columns.
    If `return_X_y` is True, then (`data`, `target`) will be pandas
    DataFrames or Series as described below.
    .. versionadded:: 0.23
scaled : bool, default=True
    If True, the feature variables are mean centered and scaled by the
    standard deviation times the square root of `n_samples`.
    If False, raw data is returned for the feature variables.
    .. versionadded:: 1.1
Returns
-------
data : :class:`~sklearn.utils.Bunch`
    Dictionary-like object, with the following attributes.
    data : {ndarray, dataframe} of shape (442, 10)
        The data matrix. If `as_frame=True`, `data` will be a pandas
        DataFrame.
    target: {ndarray, Series} of shape (442,)
        The regression target. If `as_frame=True`, `target` will be
        a pandas Series.
    feature_names: list
        The names of the dataset columns.
    frame: DataFrame of shape (442, 11)
        Only present when `as_frame=True`. DataFrame with `data` and
        `target`.
        .. versionadded:: 0.23
    DESCR: str
        The full description of the dataset.
    data_filename: str
        The path to the location of the data.
    target_filename: str
        The path to the location of the target.
(data, target) : tuple if ``return_X_y`` is True
    Returns a tuple of two ndarray of shape (n_samples, n_features)
    A 2D array with each row representing one sample and each column
    representing the features and/or target of a given sample.
    .. versionadded:: 0.18
Examples
--------
>>> from sklearn.datasets import load_diabetes
>>> diabetes = load_diabetes()
>>> diabetes.target[:3]
array([151.,  75., 141.])
>>> diabetes.data.shape
(442, 10)
Definition at line 1046 of file _base.py.
References load_descr(), and load_gzip_compressed_csv_data().
load_digits()
sklearn.datasets._base.load_digits (* , n_class = 10, return_X_y = False, as_frame = False)
Load and return the digits dataset (classification).
Each datapoint is a 8x8 image of a digit.
=================   ==============
Classes                         10
Samples per class             ~180
Samples total                 1797
Dimensionality                  64
Features             integers 0-16
=================   ==============
This is a copy of the test set of the UCI ML hand-written digits datasets
https://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits
Read more in the :ref:`User Guide <digits_dataset>`.
Parameters
----------
n_class : int, default=10
    The number of classes to return. Between 0 and 10.
return_X_y : bool, default=False
    If True, returns ``(data, target)`` instead of a Bunch object.
    See below for more information about the `data` and `target` object.
    .. versionadded:: 0.18
as_frame : bool, default=False
    If True, the data is a pandas DataFrame including columns with
    appropriate dtypes (numeric). The target is
    a pandas DataFrame or Series depending on the number of target columns.
    If `return_X_y` is True, then (`data`, `target`) will be pandas
    DataFrames or Series as described below.
    .. versionadded:: 0.23
Returns
-------
data : :class:`~sklearn.utils.Bunch`
    Dictionary-like object, with the following attributes.
    data : {ndarray, dataframe} of shape (1797, 64)
        The flattened data matrix. If `as_frame=True`, `data` will be
        a pandas DataFrame.
    target: {ndarray, Series} of shape (1797,)
        The classification target. If `as_frame=True`, `target` will be
        a pandas Series.
    feature_names: list
        The names of the dataset columns.
    target_names: list
        The names of target classes.
        .. versionadded:: 0.20
    frame: DataFrame of shape (1797, 65)
        Only present when `as_frame=True`. DataFrame with `data` and
        `target`.
        .. versionadded:: 0.23
    images: {ndarray} of shape (1797, 8, 8)
        The raw image data.
    DESCR: str
        The full description of the dataset.
(data, target) : tuple if ``return_X_y`` is True
    A tuple of two ndarrays by default. The first contains a 2D ndarray of
    shape (1797, 64) with each row representing one sample and each column
    representing the features. The second ndarray of shape (1797) contains
    the target samples.  If `as_frame=True`, both arrays are pandas objects,
    i.e. `X` a dataframe and `y` a series.
    .. versionadded:: 0.18
Examples
--------
To load the data and visualize the images::
    >>> from sklearn.datasets import load_digits
    >>> digits = load_digits()
    >>> print(digits.data.shape)
    (1797, 64)
    >>> import matplotlib.pyplot as plt
    >>> plt.matshow(digits.images[0], cmap="gray")
    <...>
    >>> plt.show()
Definition at line 910 of file _base.py.
References load_gzip_compressed_csv_data().
load_files()
sklearn.datasets._base.load_files (container_path, * , description = None, categories = None, load_content = True, shuffle = True, encoding = None, decode_error = "strict", random_state = 0, allowed_extensions = None)
Load text files with categories as subfolder names.
Individual samples are assumed to be files stored a two levels folder
structure such as the following:
.. code-block:: text
    container_folder/
        category_1_folder/
            file_1.txt
            file_2.txt
            ...
            file_42.txt
        category_2_folder/
            file_43.txt
            file_44.txt
            ...
The folder names are used as supervised signal label names. The individual
file names are not important.
This function does not try to extract features into a numpy array or scipy
sparse matrix. In addition, if load_content is false it does not try to
load the files in memory.
To use text files in a scikit-learn classification or clustering algorithm,
you will need to use the :mod:`~sklearn.feature_extraction.text` module to
build a feature extraction transformer that suits your problem.
If you set load_content=True, you should also specify the encoding of the
text using the 'encoding' parameter. For many modern text files, 'utf-8'
will be the correct encoding. If you leave encoding equal to None, then the
content will be made of bytes instead of Unicode, and you will not be able
to use most functions in :mod:`~sklearn.feature_extraction.text`.
Similar feature extractors should be built for other kind of unstructured
data input such as images, audio, video, ...
If you want files with a specific file extension (e.g. `.txt`) then you
can pass a list of those file extensions to `allowed_extensions`.
Read more in the :ref:`User Guide <datasets>`.
Parameters
----------
container_path : str
    Path to the main folder holding one subfolder per category.
description : str, default=None
    A paragraph describing the characteristic of the dataset: its source,
    reference, etc.
categories : list of str, default=None
    If None (default), load all the categories. If not None, list of
    category names to load (other categories ignored).
load_content : bool, default=True
    Whether to load or not the content of the different files. If true a
    'data' attribute containing the text information is present in the data
    structure returned. If not, a filenames attribute gives the path to the
    files.
shuffle : bool, default=True
    Whether or not to shuffle the data: might be important for models that
    make the assumption that the samples are independent and identically
    distributed (i.i.d.), such as stochastic gradient descent.
encoding : str, default=None
    If None, do not try to decode the content of the files (e.g. for images
    or other non-text content). If not None, encoding to use to decode text
    files to Unicode if load_content is True.
decode_error : {'strict', 'ignore', 'replace'}, default='strict'
    Instruction on what to do if a byte sequence is given to analyze that
    contains characters not of the given `encoding`. Passed as keyword
    argument 'errors' to bytes.decode.
random_state : int, RandomState instance or None, default=0
    Determines random number generation for dataset shuffling. Pass an int
    for reproducible output across multiple function calls.
    See :term:`Glossary <random_state>`.
allowed_extensions : list of str, default=None
    List of desired file extensions to filter the files to be loaded.
Returns
-------
data : :class:`~sklearn.utils.Bunch`
    Dictionary-like object, with the following attributes.
    data : list of str
        Only present when `load_content=True`.
        The raw text data to learn.
    target : ndarray
        The target labels (integer index).
    target_names : list
        The names of target classes.
    DESCR : str
        The full description of the dataset.
    filenames: ndarray
        The filenames holding the dataset.
Examples
--------
>>> from sklearn.datasets import load_files
>>> container_path = "./"
>>> load_files(container_path)  # doctest: +SKIP
Definition at line 145 of file _base.py.
load_gzip_compressed_csv_data()
sklearn.datasets._base.load_gzip_compressed_csv_data (data_file_name, * , data_module = DATA_MODULE, descr_file_name = None, descr_module = DESCR_MODULE, encoding = "utf-8", ** kwargs)
Loads gzip-compressed with `importlib.resources`.
1) Open resource file with `importlib.resources.open_binary`
2) Decompress file obj with `gzip.open`
3) Load decompressed data with `np.loadtxt`
Parameters
----------
data_file_name : str
    Name of gzip-compressed csv file  (`'*.csv.gz'`) to be loaded from
    `data_module/data_file_name`. For example `'diabetes_data.csv.gz'`.
data_module : str or module, default='sklearn.datasets.data'
    Module where data lives. The default is `'sklearn.datasets.data'`.
descr_file_name : str, default=None
    Name of rst file to be loaded from `descr_module/descr_file_name`.
    For example `'wine_data.rst'`. See also :func:`load_descr`.
    If not None, also returns the corresponding description of
    the dataset.
descr_module : str or module, default='sklearn.datasets.descr'
    Module where `descr_file_name` lives. See also :func:`load_descr`.
    The default  is `'sklearn.datasets.descr'`.
encoding : str, default="utf-8"
    Name of the encoding that the gzip-decompressed file will be
    decoded with. The default is 'utf-8'.
**kwargs : dict, optional
    Keyword arguments to be passed to `np.loadtxt`;
    e.g. delimiter=','.
Returns
-------
data : ndarray of shape (n_samples, n_features)
    A 2D array with each row representing one sample and each column
    representing the features and/or target of a given sample.
descr : str, optional
    Description of the dataset (the content of `descr_file_name`).
    Only returned if `descr_file_name` is not None.
Definition at line 399 of file _base.py.
References load_descr().
Referenced by load_diabetes(), and load_digits().
load_iris()
sklearn.datasets._base.load_iris (* , return_X_y = False, as_frame = False)
Load and return the iris dataset (classification).
The iris dataset is a classic and very easy multi-class classification
dataset.
=================   ==============
Classes                          3
Samples per class               50
Samples total                  150
Dimensionality                   4
Features            real, positive
=================   ==============
Read more in the :ref:`User Guide <iris_dataset>`.
.. versionchanged:: 0.20
    Fixed two wrong data points according to Fisher's paper.
    The new version is the same as in R, but not as in the UCI
    Machine Learning Repository.
Parameters
----------
return_X_y : bool, default=False
    If True, returns ``(data, target)`` instead of a Bunch object. See
    below for more information about the `data` and `target` object.
    .. versionadded:: 0.18
as_frame : bool, default=False
    If True, the data is a pandas DataFrame including columns with
    appropriate dtypes (numeric). The target is
    a pandas DataFrame or Series depending on the number of target columns.
    If `return_X_y` is True, then (`data`, `target`) will be pandas
    DataFrames or Series as described below.
    .. versionadded:: 0.23
Returns
-------
data : :class:`~sklearn.utils.Bunch`
    Dictionary-like object, with the following attributes.
    data : {ndarray, dataframe} of shape (150, 4)
        The data matrix. If `as_frame=True`, `data` will be a pandas
        DataFrame.
    target: {ndarray, Series} of shape (150,)
        The classification target. If `as_frame=True`, `target` will be
        a pandas Series.
    feature_names: list
        The names of the dataset columns.
    target_names: ndarray of shape (3, )
        The names of target classes.
    frame: DataFrame of shape (150, 5)
        Only present when `as_frame=True`. DataFrame with `data` and
        `target`.
        .. versionadded:: 0.23
    DESCR: str
        The full description of the dataset.
    filename: str
        The path to the location of the data.
        .. versionadded:: 0.20
(data, target) : tuple if ``return_X_y`` is True
    A tuple of two ndarray. The first containing a 2D array of shape
    (n_samples, n_features) with each row representing one sample and
    each column representing the features. The second ndarray of shape
    (n_samples,) containing the target samples.
    .. versionadded:: 0.18
Examples
--------
Let's say you are interested in the samples 10, 25, and 50, and want to
know their class name.
>>> from sklearn.datasets import load_iris
>>> data = load_iris()
>>> data.target[[10, 25, 50]]
array([0, 0, 1])
>>> list(data.target_names)
[np.str_('setosa'), np.str_('versicolor'), np.str_('virginica')]
See :ref:`sphx_glr_auto_examples_decomposition_plot_pca_iris.py` for a more
detailed example of how to work with the iris dataset.
Definition at line 625 of file _base.py.
References load_csv_data().
load_linnerud()
sklearn.datasets._base.load_linnerud (* , return_X_y = False, as_frame = False)
Load and return the physical exercise Linnerud dataset.
This dataset is suitable for multi-output regression tasks.
==============   ============================
Samples total    20
Dimensionality   3 (for both data and target)
Features         integer
Targets          integer
==============   ============================
Read more in the :ref:`User Guide <linnerrud_dataset>`.
Parameters
----------
return_X_y : bool, default=False
    If True, returns ``(data, target)`` instead of a Bunch object.
    See below for more information about the `data` and `target` object.
    .. versionadded:: 0.18
as_frame : bool, default=False
    If True, the data is a pandas DataFrame including columns with
    appropriate dtypes (numeric, string or categorical). The target is
    a pandas DataFrame or Series depending on the number of target columns.
    If `return_X_y` is True, then (`data`, `target`) will be pandas
    DataFrames or Series as described below.
    .. versionadded:: 0.23
Returns
-------
data : :class:`~sklearn.utils.Bunch`
    Dictionary-like object, with the following attributes.
    data : {ndarray, dataframe} of shape (20, 3)
        The data matrix. If `as_frame=True`, `data` will be a pandas
        DataFrame.
    target: {ndarray, dataframe} of shape (20, 3)
        The regression targets. If `as_frame=True`, `target` will be
        a pandas DataFrame.
    feature_names: list
        The names of the dataset columns.
    target_names: list
        The names of the target columns.
    frame: DataFrame of shape (20, 6)
        Only present when `as_frame=True`. DataFrame with `data` and
        `target`.
        .. versionadded:: 0.23
    DESCR: str
        The full description of the dataset.
    data_filename: str
        The path to the location of the data.
    target_filename: str
        The path to the location of the target.
        .. versionadded:: 0.20
(data, target) : tuple if ``return_X_y`` is True
    Returns a tuple of two ndarrays or dataframe of shape
    `(20, 3)`. Each row represents one sample and each column represents the
    features in `X` and a target in `y` of a given sample.
    .. versionadded:: 0.18
Examples
--------
>>> from sklearn.datasets import load_linnerud
>>> linnerud = load_linnerud()
>>> linnerud.data.shape
(20, 3)
>>> linnerud.target.shape
(20, 3)
Definition at line 1173 of file _base.py.
References load_descr().
load_sample_image()
sklearn.datasets._base.load_sample_image (image_name)
Load the numpy array of a single sample image.
Read more in the :ref:`User Guide <sample_images>`.
Parameters
----------
image_name : {`china.jpg`, `flower.jpg`}
    The name of the sample image loaded.
Returns
-------
img : 3D array
    The image as a numpy array: height x width x color.
Examples
--------
>>> from sklearn.datasets import load_sample_image
>>> china = load_sample_image('china.jpg')   # doctest: +SKIP
>>> china.dtype                              # doctest: +SKIP
dtype('uint8')
>>> china.shape                              # doctest: +SKIP
(427, 640, 3)
>>> flower = load_sample_image('flower.jpg') # doctest: +SKIP
>>> flower.dtype                             # doctest: +SKIP
dtype('uint8')
>>> flower.shape                             # doctest: +SKIP
(427, 640, 3)
Definition at line 1362 of file _base.py.
References load_sample_images().
load_sample_images()
sklearn.datasets._base.load_sample_images ()
Load sample images for image manipulation.
Loads both, ``china`` and ``flower``.
Read more in the :ref:`User Guide <sample_images>`.
Returns
-------
data : :class:`~sklearn.utils.Bunch`
    Dictionary-like object, with the following attributes.
    images : list of ndarray of shape (427, 640, 3)
        The two sample image.
    filenames : list
        The filenames for the images.
    DESCR : str
        The full description of the dataset.
Examples
--------
To load the data and visualize the images:
>>> from sklearn.datasets import load_sample_images
>>> dataset = load_sample_images()     #doctest: +SKIP
>>> len(dataset.images)                #doctest: +SKIP
2
>>> first_img_data = dataset.images[0] #doctest: +SKIP
>>> first_img_data.shape               #doctest: +SKIP
(427, 640, 3)
>>> first_img_data.dtype               #doctest: +SKIP
dtype('uint8')
Definition at line 1293 of file _base.py.
References load_descr().
Referenced by load_sample_image().
load_wine()
sklearn.datasets._base.load_wine (* , return_X_y = False, as_frame = False)
Load and return the wine dataset (classification).
.. versionadded:: 0.18
The wine dataset is a classic and very easy multi-class classification
dataset.
=================   ==============
Classes                          3
Samples per class        [59,71,48]
Samples total                  178
Dimensionality                  13
Features            real, positive
=================   ==============
The copy of UCI ML Wine Data Set dataset is downloaded and modified to fit
standard format from:
https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data
Read more in the :ref:`User Guide <wine_dataset>`.
Parameters
----------
return_X_y : bool, default=False
    If True, returns ``(data, target)`` instead of a Bunch object.
    See below for more information about the `data` and `target` object.
as_frame : bool, default=False
    If True, the data is a pandas DataFrame including columns with
    appropriate dtypes (numeric). The target is
    a pandas DataFrame or Series depending on the number of target columns.
    If `return_X_y` is True, then (`data`, `target`) will be pandas
    DataFrames or Series as described below.
    .. versionadded:: 0.23
Returns
-------
data : :class:`~sklearn.utils.Bunch`
    Dictionary-like object, with the following attributes.
    data : {ndarray, dataframe} of shape (178, 13)
        The data matrix. If `as_frame=True`, `data` will be a pandas
        DataFrame.
    target: {ndarray, Series} of shape (178,)
        The classification target. If `as_frame=True`, `target` will be
        a pandas Series.
    feature_names: list
        The names of the dataset columns.
    target_names: list
        The names of target classes.
    frame: DataFrame of shape (178, 14)
        Only present when `as_frame=True`. DataFrame with `data` and
        `target`.
        .. versionadded:: 0.23
    DESCR: str
        The full description of the dataset.
(data, target) : tuple if ``return_X_y`` is True
    A tuple of two ndarrays by default. The first contains a 2D array of shape
    (178, 13) with each row representing one sample and each column representing
    the features. The second array of shape (178,) contains the target samples.
Examples
--------
Let's say you are interested in the samples 10, 80, and 140, and want to
know their class name.
>>> from sklearn.datasets import load_wine
>>> data = load_wine()
>>> data.target[[10, 80, 140]]
array([0, 1, 2])
>>> list(data.target_names)
[np.str_('class_0'), np.str_('class_1'), np.str_('class_2')]
Definition at line 501 of file _base.py.
References load_csv_data().
Variable Documentation
DATA_MODULE
str sklearn.datasets._base.DATA_MODULE = "sklearn.datasets.data"
Definition at line 35 of file _base.py.
DESCR_MODULE
str sklearn.datasets._base.DESCR_MODULE = "sklearn.datasets.descr"
Definition at line 36 of file _base.py.
IMAGES_MODULE
str sklearn.datasets._base.IMAGES_MODULE = "sklearn.datasets.images"
Definition at line 37 of file _base.py.
RemoteFileMetadata
sklearn.datasets._base.RemoteFileMetadata = namedtuple("RemoteFileMetadata", ["filename", "url", "checksum"])
Definition at line 39 of file _base.py.