Code Cloning Analysis: pandas.tests.series.methods.test_drop_duplicates.TestSeriesDropDuplicates Class Reference
pandas.tests.series.methods.test_drop_duplicates.TestSeriesDropDuplicates Class Reference
Public Member Functions
dtype (self, request)
cat_series_unused_category (self, dtype, ordered)
test_drop_duplicates_categorical_non_bool (self, cat_series_unused_category)
test_drop_duplicates_categorical_non_bool_keeplast (self, cat_series_unused_category)
test_drop_duplicates_categorical_non_bool_keepfalse (self, cat_series_unused_category)
cat_series (self, dtype, ordered)
test_drop_duplicates_categorical_non_bool2 (self, cat_series)
test_drop_duplicates_categorical_non_bool2_keeplast (self, cat_series)
test_drop_duplicates_categorical_non_bool2_keepfalse (self, cat_series)
test_drop_duplicates_categorical_bool (self, ordered)
test_drop_duplicates_categorical_bool_na (self, nulls_fixture)
test_drop_duplicates_ignore_index (self)
test_duplicated_arrow_dtype (self)
test_drop_duplicates_arrow_strings (self)
Detailed Description
Definition at line 73 of file test_drop_duplicates.py.
Member Function Documentation
cat_series()
pandas.tests.series.methods.test_drop_duplicates.TestSeriesDropDuplicates.cat_series (self, dtype, ordered)
Definition at line 143 of file test_drop_duplicates.py.
cat_series_unused_category()
pandas.tests.series.methods.test_drop_duplicates.TestSeriesDropDuplicates.cat_series_unused_category (self, dtype, ordered)
Definition at line 81 of file test_drop_duplicates.py.
dtype()
pandas.tests.series.methods.test_drop_duplicates.TestSeriesDropDuplicates.dtype (self, request)
Definition at line 77 of file test_drop_duplicates.py.
Referenced by pandas.core.arrays.base.ExtensionScalarOpsMixin._create_method(), scipy.sparse._index.IndexMixin._getcol(), pandas.core.generic.NDFrame._inplace_method(), scipy.sparse._index.IndexMixin._raise_on_1d_array_slice(), pandas.core.strings.object_array.ObjectStringArrayMixin._str_map(), numpy.matrixlib.defmatrix.matrix.H(), numpy.core.records.record.pprint(), pandas.core.frame.DataFrame.quantile(), and pandas.core.generic.NDFrame.rank().
test_drop_duplicates_arrow_strings()
pandas.tests.series.methods.test_drop_duplicates.TestSeriesDropDuplicates.test_drop_duplicates_arrow_strings (self)
Definition at line 261 of file test_drop_duplicates.py.
test_drop_duplicates_categorical_bool()
pandas.tests.series.methods.test_drop_duplicates.TestSeriesDropDuplicates.test_drop_duplicates_categorical_bool (self, ordered)
Definition at line 200 of file test_drop_duplicates.py.
test_drop_duplicates_categorical_bool_na()
pandas.tests.series.methods.test_drop_duplicates.TestSeriesDropDuplicates.test_drop_duplicates_categorical_bool_na (self, nulls_fixture)
Definition at line 231 of file test_drop_duplicates.py.
test_drop_duplicates_categorical_non_bool()
pandas.tests.series.methods.test_drop_duplicates.TestSeriesDropDuplicates.test_drop_duplicates_categorical_non_bool (self, cat_series_unused_category)
Definition at line 90 of file test_drop_duplicates.py.
test_drop_duplicates_categorical_non_bool2()
pandas.tests.series.methods.test_drop_duplicates.TestSeriesDropDuplicates.test_drop_duplicates_categorical_non_bool2 (self, cat_series)
Definition at line 152 of file test_drop_duplicates.py.
test_drop_duplicates_categorical_non_bool2_keepfalse()
pandas.tests.series.methods.test_drop_duplicates.TestSeriesDropDuplicates.test_drop_duplicates_categorical_non_bool2_keepfalse (self, cat_series)
Definition at line 184 of file test_drop_duplicates.py.
test_drop_duplicates_categorical_non_bool2_keeplast()
pandas.tests.series.methods.test_drop_duplicates.TestSeriesDropDuplicates.test_drop_duplicates_categorical_non_bool2_keeplast (self, cat_series)
Definition at line 168 of file test_drop_duplicates.py.
test_drop_duplicates_categorical_non_bool_keepfalse()
pandas.tests.series.methods.test_drop_duplicates.TestSeriesDropDuplicates.test_drop_duplicates_categorical_non_bool_keepfalse (self, cat_series_unused_category)
Definition at line 124 of file test_drop_duplicates.py.
test_drop_duplicates_categorical_non_bool_keeplast()
pandas.tests.series.methods.test_drop_duplicates.TestSeriesDropDuplicates.test_drop_duplicates_categorical_non_bool_keeplast (self, cat_series_unused_category)
Definition at line 106 of file test_drop_duplicates.py.
test_drop_duplicates_ignore_index()
pandas.tests.series.methods.test_drop_duplicates.TestSeriesDropDuplicates.test_drop_duplicates_ignore_index (self)
Definition at line 247 of file test_drop_duplicates.py.
test_duplicated_arrow_dtype()
pandas.tests.series.methods.test_drop_duplicates.TestSeriesDropDuplicates.test_duplicated_arrow_dtype (self)
Definition at line 254 of file test_drop_duplicates.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/tests/series/methods/test_drop_duplicates.py