Code Cloning Analysis: matplotlib.ticker.FixedLocator Class Reference
matplotlib.ticker.FixedLocator Class Reference
Public Member Functions
__init__ (self, locs, nbins=None)
set_params (self, nbins=None)
__call__ (self)
tick_values (self, vmin, vmax)
Public Member Functions inherited from matplotlib.ticker.Locator
__call__ (self)
raise_if_exceeds (self, locs)
nonsingular (self, v0, v1)
view_limits (self, vmin, vmax)
Public Member Functions inherited from matplotlib.ticker.TickHelper
set_axis (self, axis)
create_dummy_axis (self, **kwargs)
Public Attributes
locs = np.asarray(locs)
nbins = max(nbins, 2) if nbins is not None else None
Additional Inherited Members
Static Public Attributes inherited from matplotlib.ticker.Locator
int MAXTICKS = 1000
Static Public Attributes inherited from matplotlib.ticker.TickHelper
axis = None
Detailed Description
Place ticks at a set of fixed values.
If *nbins* is None ticks are placed at all values. Otherwise, the *locs* array of
possible positions will be subsampled to keep the number of ticks
:math:`\leq nbins + 1`. The subsampling will be done to include the smallest
absolute value; for example, if zero is included in the array of possibilities, then
it will be included in the chosen ticks.
Definition at line 1768 of file ticker.py.
Constructor & Destructor Documentation
__init__()
matplotlib.ticker.FixedLocator.__init__ (self, locs, nbins = None)
Definition at line 1779 of file ticker.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__call__()
matplotlib.ticker.FixedLocator.__call__ (self)
Definition at line 1789 of file ticker.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), and scipy.interpolate._fitpack2.SphereBivariateSpline.ev().
set_params()
matplotlib.ticker.FixedLocator.set_params (self, nbins = None)
Set parameters within this locator.
Reimplemented from matplotlib.ticker.Locator.
Definition at line 1784 of file ticker.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.theta().
tick_values()
matplotlib.ticker.FixedLocator.tick_values (self, vmin, vmax)
Return the locations of the ticks.
.. note::
    Because the values are fixed, vmin and vmax are not used in this
    method.
Reimplemented from matplotlib.ticker.Locator.
Definition at line 1792 of file ticker.py.
Member Data Documentation
locs
matplotlib.ticker.FixedLocator.locs = np.asarray(locs)
Definition at line 1780 of file ticker.py.
nbins
matplotlib.ticker.FixedLocator.nbins = max(nbins, 2) if nbins is not None else None
Definition at line 1782 of file ticker.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/ticker.py