Code Cloning Analysis: sklearn.gaussian_process.kernels.Hyperparameter Class Reference
sklearn.gaussian_process.kernels.Hyperparameter Class Reference
Public Member Functions
__new__ (cls, name, value_type, bounds, n_elements=1, fixed=None)
__eq__ (self, other)
Public Attributes
name = other.name
value_type = other.value_type
bounds = other.bounds)
n_elements = other.n_elements
fixed = other.fixed
Static Private Attributes
tuple __slots__ = ()
Detailed Description
A kernel hyperparameter's specification in form of a namedtuple.
.. versionadded:: 0.18
Attributes
----------
name : str
    The name of the hyperparameter. Note that a kernel using a
    hyperparameter with name "x" must have the attributes self.x and
    self.x_bounds
value_type : str
    The type of the hyperparameter. Currently, only "numeric"
    hyperparameters are supported.
bounds : pair of floats >= 0 or "fixed"
    The lower and upper bound on the parameter. If n_elements>1, a pair
    of 1d array with n_elements each may be given alternatively. If
    the string "fixed" is passed as bounds, the hyperparameter's value
    cannot be changed.
n_elements : int, default=1
    The number of elements of the hyperparameter value. Defaults to 1,
    which corresponds to a scalar hyperparameter. n_elements > 1
    corresponds to a hyperparameter which is vector-valued,
    such as, e.g., anisotropic length-scales.
fixed : bool, default=None
    Whether the value of this hyperparameter is fixed, i.e., cannot be
    changed during hyperparameter tuning. If None is passed, the "fixed" is
    derived based on the given bounds.
Examples
--------
>>> from sklearn.gaussian_process.kernels import ConstantKernel
>>> from sklearn.datasets import make_friedman2
>>> from sklearn.gaussian_process import GaussianProcessRegressor
>>> from sklearn.gaussian_process.kernels import Hyperparameter
>>> X, y = make_friedman2(n_samples=50, noise=0, random_state=0)
>>> kernel = ConstantKernel(constant_value=1.0,
...    constant_value_bounds=(0.0, 10.0))
We can access each hyperparameter:
>>> for hyperparameter in kernel.hyperparameters:
...    print(hyperparameter)
Hyperparameter(name='constant_value', value_type='numeric',
bounds=array([[ 0., 10.]]), n_elements=1, fixed=False)
>>> params = kernel.get_params()
>>> for key in sorted(params): print(f"{key} : {params[key]}")
constant_value : 1.0
constant_value_bounds : (0.0, 10.0)
Definition at line 52 of file kernels.py.
Member Function Documentation
__eq__()
sklearn.gaussian_process.kernels.Hyperparameter.__eq__ (self, other)
Definition at line 141 of file kernels.py.
__new__()
sklearn.gaussian_process.kernels.Hyperparameter.__new__ (cls, name, value_type, bounds, n_elements = 1, fixed = None)
Definition at line 122 of file kernels.py.
Referenced by matplotlib.path.Path._fast_from_codes_and_verts(), pandas.core.generic.NDFrame._from_mgr(), pandas.core.arrays.string_.StringArray._from_sequence(), scipy.interpolate._fitpack2._BivariateSplineBase._from_tck(), scipy.interpolate._fitpack2.UnivariateSpline._from_tck(), matplotlib.colors.Colormap._get_rgba_and_mask(), pip._vendor.rich.style.Style.clear_meta_and_links(), matplotlib.colors.MultivarColormap.copy(), pip._vendor.rich.style.Style.copy(), pip._vendor.rich.style.Style.from_color(), pip._vendor.rich.json.JSON.from_data(), pip._vendor.rich.style.Style.from_meta(), matplotlib.colors.BivarColormap.lut(), pip._vendor.rich.style.Style.test(), pip._vendor.rich.style.Style.update_link(), and pip._vendor.rich.style.Style.without_color().
Member Data Documentation
__slots__
tuple sklearn.gaussian_process.kernels.Hyperparameter.__slots__ = () static private
Definition at line 120 of file kernels.py.
bounds
sklearn.gaussian_process.kernels.Hyperparameter.bounds = other.bounds)
Definition at line 145 of file kernels.py.
Referenced by sklearn.gaussian_process.kernels.Kernel._check_bounds_params(), and matplotlib.transforms.BboxBase.anchored().
fixed
sklearn.gaussian_process.kernels.Hyperparameter.fixed = other.fixed
Definition at line 147 of file kernels.py.
n_elements
sklearn.gaussian_process.kernels.Hyperparameter.n_elements = other.n_elements
Definition at line 146 of file kernels.py.
name
sklearn.gaussian_process.kernels.Hyperparameter.name = other.name
Definition at line 143 of file kernels.py.
Referenced by pip._vendor.pyparsing.core.Regex.__init__(), pandas.core.groupby.grouper.Grouping.group_arraylike(), pip._vendor.distro.distro.LinuxDistribution.linux_distribution(), and pip._internal.resolution.resolvelib.requirements.SpecifierRequirement.name().
value_type
sklearn.gaussian_process.kernels.Hyperparameter.value_type = other.value_type
Definition at line 144 of file kernels.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/sklearn/gaussian_process/kernels.py