Code Cloning Analysis: numpy.ma.tests.test_core.TestMaskedArrayMathMethods Class Reference
numpy.ma.tests.test_core.TestMaskedArrayMathMethods Class Reference
Public Member Functions
setup_method (self)
test_cumsumprod (self)
test_cumsumprod_with_output (self)
test_ptp (self)
test_add_object (self)
test_sum_object (self)
test_prod_object (self)
test_meananom_object (self)
test_anom_shape (self)
test_anom (self)
test_trace (self)
test_dot (self)
test_dot_shape_mismatch (self)
test_varmean_nomask (self)
test_varstd (self)
test_varstd_specialcases (self)
test_varstd_ddof (self)
test_diag (self)
test_axis_methods_nomask (self)
test_mean_overflow (self)
test_diff_with_prepend (self)
test_diff_with_append (self)
test_diff_with_dim_0 (self)
test_diff_with_n_0 (self)
Public Attributes
tuple d = (x, X, XX, m, mx, mX, mXX, m2x, m2X, m2XX)
Detailed Description
Definition at line 3860 of file test_core.py.
Member Function Documentation
setup_method()
numpy.ma.tests.test_core.TestMaskedArrayMathMethods.setup_method (self)
Definition at line 3862 of file test_core.py.
test_add_object()
numpy.ma.tests.test_core.TestMaskedArrayMathMethods.test_add_object (self)
Definition at line 3942 of file test_core.py.
test_anom()
numpy.ma.tests.test_core.TestMaskedArrayMathMethods.test_anom (self)
Definition at line 3975 of file test_core.py.
test_anom_shape()
numpy.ma.tests.test_core.TestMaskedArrayMathMethods.test_anom_shape (self)
Definition at line 3968 of file test_core.py.
test_axis_methods_nomask()
numpy.ma.tests.test_core.TestMaskedArrayMathMethods.test_axis_methods_nomask (self)
Definition at line 4139 of file test_core.py.
test_cumsumprod()
numpy.ma.tests.test_core.TestMaskedArrayMathMethods.test_cumsumprod (self)
Definition at line 3894 of file test_core.py.
test_cumsumprod_with_output()
numpy.ma.tests.test_core.TestMaskedArrayMathMethods.test_cumsumprod_with_output (self)
Definition at line 3907 of file test_core.py.
test_diag()
numpy.ma.tests.test_core.TestMaskedArrayMathMethods.test_diag (self)
Definition at line 4125 of file test_core.py.
test_diff_with_append()
numpy.ma.tests.test_core.TestMaskedArrayMathMethods.test_diff_with_append (self)
Definition at line 4180 of file test_core.py.
test_diff_with_dim_0()
numpy.ma.tests.test_core.TestMaskedArrayMathMethods.test_diff_with_dim_0 (self)
Definition at line 4193 of file test_core.py.
test_diff_with_n_0()
numpy.ma.tests.test_core.TestMaskedArrayMathMethods.test_diff_with_n_0 (self)
Definition at line 4200 of file test_core.py.
test_diff_with_prepend()
numpy.ma.tests.test_core.TestMaskedArrayMathMethods.test_diff_with_prepend (self)
Definition at line 4167 of file test_core.py.
test_dot()
numpy.ma.tests.test_core.TestMaskedArrayMathMethods.test_dot (self)
Definition at line 4007 of file test_core.py.
test_dot_shape_mismatch()
numpy.ma.tests.test_core.TestMaskedArrayMathMethods.test_dot_shape_mismatch (self)
Definition at line 4031 of file test_core.py.
test_mean_overflow()
numpy.ma.tests.test_core.TestMaskedArrayMathMethods.test_mean_overflow (self)
Definition at line 4160 of file test_core.py.
test_meananom_object()
numpy.ma.tests.test_core.TestMaskedArrayMathMethods.test_meananom_object (self)
Definition at line 3962 of file test_core.py.
test_prod_object()
numpy.ma.tests.test_core.TestMaskedArrayMathMethods.test_prod_object (self)
Definition at line 3955 of file test_core.py.
test_ptp()
numpy.ma.tests.test_core.TestMaskedArrayMathMethods.test_ptp (self)
Definition at line 3928 of file test_core.py.
test_sum_object()
numpy.ma.tests.test_core.TestMaskedArrayMathMethods.test_sum_object (self)
Definition at line 3948 of file test_core.py.
test_trace()
numpy.ma.tests.test_core.TestMaskedArrayMathMethods.test_trace (self)
Definition at line 3992 of file test_core.py.
test_varmean_nomask()
numpy.ma.tests.test_core.TestMaskedArrayMathMethods.test_varmean_nomask (self)
Definition at line 4040 of file test_core.py.
test_varstd()
numpy.ma.tests.test_core.TestMaskedArrayMathMethods.test_varstd (self)
Definition at line 4056 of file test_core.py.
test_varstd_ddof()
numpy.ma.tests.test_core.TestMaskedArrayMathMethods.test_varstd_ddof (self)
Definition at line 4113 of file test_core.py.
test_varstd_specialcases()
numpy.ma.tests.test_core.TestMaskedArrayMathMethods.test_varstd_specialcases (self)
Definition at line 4079 of file test_core.py.
Member Data Documentation
d
tuple numpy.ma.tests.test_core.TestMaskedArrayMathMethods.d = (x, X, XX, m, mx, mX, mXX, m2x, m2X, m2XX)
Definition at line 3892 of file test_core.py.
Referenced by scipy.interpolate._rbfinterp.RBFInterpolator.__call__(), scipy.interpolate._rbfinterp.RBFInterpolator._chunk_evaluator(), scipy.stats._qmc.PoissonDisk._hypersphere_surface_sample(), scipy.stats._qmc.PoissonDisk._hypersphere_volume_sample(), scipy.stats._qmc.PoissonDisk._initialize_grid_pool(), scipy.stats._qmc.Halton._random(), scipy.stats._qmc.PoissonDisk._random(), scipy.stats._qmc.Sobol._random(), scipy.stats._qmc.LatinHypercube._random_lhs(), scipy.stats._qmc.LatinHypercube._random_oa_lhs(), scipy.stats._qmc.Sobol._scramble(), scipy.sparse.linalg._expm_multiply.LazyOperatorNormInfo.alpha(), scipy.stats._kde.gaussian_kde.evaluate(), scipy.stats._qmc.Sobol.fast_forward(), scipy.stats._kde.gaussian_kde.integrate_box(), scipy.stats._kde.gaussian_kde.integrate_box_1d(), scipy.stats._kde.gaussian_kde.integrate_gaussian(), scipy.stats._kde.gaussian_kde.integrate_kde(), scipy.optimize._zeros_py.TOMS748Solver.iterate(), scipy.stats._kde.gaussian_kde.logpdf(), scipy.stats._kde.gaussian_kde.resample(), scipy.stats._kde.gaussian_kde.scotts_factor(), scipy.stats._kde.gaussian_kde.silverman_factor(), and scipy.optimize._zeros_py.TOMS748Solver.solve().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/ma/tests/test_core.py