Code Cloning Analysis: fontTools.ttLib.tables.S__i_l_f.Pass Class Reference
fontTools.ttLib.tables.S__i_l_f.Pass Class Reference
Public Member Functions
__init__ (self)
decompile (self, data, ttFont, version=2.0)
compile (self, ttFont, base, version=2.0)
toXML (self, writer, ttFont, version=2.0)
fromXML (self, name, attrs, content, ttFont, version=2.0)
Public Attributes
dict colMap = {}
list rules = []
list rulePreContexts = []
list ruleSortKeys = []
list ruleConstraints = []
str passConstraints = b""
list actions = []
list stateTrans = []
list startStates = []
minRulePreContext
maxRulePreContext
collisionThreshold = data[self.numRules :]
numTransitional = data[2 * self.numRules + 2 :]
numRules = len(self.actions)
tuple fsmOffset
tuple pcCode
tuple rcCode = self.pcCode + len(self.passConstraints)
tuple aCode = self.rcCode + len(constraintCode)
int oDebug = 0
Detailed Description
Definition at line 776 of file S__i_l_f.py.
Constructor & Destructor Documentation
__init__()
fontTools.ttLib.tables.S__i_l_f.Pass.__init__ (self)
Definition at line 777 of file S__i_l_f.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
compile()
fontTools.ttLib.tables.S__i_l_f.Pass.compile (self, ttFont, base, version = 2.0)
Definition at line 851 of file S__i_l_f.py.
Referenced by fontTools.ttLib.tables.TupleVariation.TupleVariation.getCoordWidth(), and PIL.FontFile.FontFile.save().
decompile()
fontTools.ttLib.tables.S__i_l_f.Pass.decompile (self, data, ttFont, version = 2.0)
Definition at line 788 of file S__i_l_f.py.
Referenced by fontTools.ttLib.tables._c_m_a_p.CmapSubtable.newSubtable().
fromXML()
fontTools.ttLib.tables.S__i_l_f.Pass.fromXML (self, name, attrs, content, ttFont, version = 2.0)
Definition at line 984 of file S__i_l_f.py.
toXML()
fontTools.ttLib.tables.S__i_l_f.Pass.toXML (self, writer, ttFont, version = 2.0)
Definition at line 922 of file S__i_l_f.py.
Member Data Documentation
aCode
tuple fontTools.ttLib.tables.S__i_l_f.Pass.aCode = self.rcCode + len(constraintCode)
Definition at line 897 of file S__i_l_f.py.
actions
fontTools.ttLib.tables.S__i_l_f.Pass.actions = []
Definition at line 784 of file S__i_l_f.py.
collisionThreshold
fontTools.ttLib.tables.S__i_l_f.Pass.collisionThreshold = data[self.numRules :]
Definition at line 816 of file S__i_l_f.py.
colMap
dict fontTools.ttLib.tables.S__i_l_f.Pass.colMap = {}
Definition at line 778 of file S__i_l_f.py.
fsmOffset
tuple fontTools.ttLib.tables.S__i_l_f.Pass.fsmOffset
Initial value:
=  (
            sstruct.calcsize(Silf_pass_format)
            + 8
            + len(passRanges) * 6
            + len(oRuleMap) * 2
            + 2 * oRuleMap[-1]
            + 2
            + 2 * len(self.startStates)
            + 3 * self.numRules
            + 3
            + 4 * self.numRules
            + 4
        )
Definition at line 880 of file S__i_l_f.py.
maxRulePreContext
fontTools.ttLib.tables.S__i_l_f.Pass.maxRulePreContext
Definition at line 802 of file S__i_l_f.py.
minRulePreContext
fontTools.ttLib.tables.S__i_l_f.Pass.minRulePreContext
Definition at line 802 of file S__i_l_f.py.
numRules
fontTools.ttLib.tables.S__i_l_f.Pass.numRules = len(self.actions)
Definition at line 879 of file S__i_l_f.py.
numTransitional
fontTools.ttLib.tables.S__i_l_f.Pass.numTransitional = data[2 * self.numRules + 2 :]
Definition at line 827 of file S__i_l_f.py.
oDebug
int fontTools.ttLib.tables.S__i_l_f.Pass.oDebug = 0
Definition at line 898 of file S__i_l_f.py.
passConstraints
fontTools.ttLib.tables.S__i_l_f.Pass.passConstraints = b""
Definition at line 783 of file S__i_l_f.py.
pcCode
tuple fontTools.ttLib.tables.S__i_l_f.Pass.pcCode
Initial value:
=  (
            self.fsmOffset + 2 * self.numTransitional * self.numColumns + 1 + base
        )
Definition at line 893 of file S__i_l_f.py.
rcCode
tuple fontTools.ttLib.tables.S__i_l_f.Pass.rcCode = self.pcCode + len(self.passConstraints)
Definition at line 896 of file S__i_l_f.py.
ruleConstraints
list fontTools.ttLib.tables.S__i_l_f.Pass.ruleConstraints = []
Definition at line 782 of file S__i_l_f.py.
rulePreContexts
list fontTools.ttLib.tables.S__i_l_f.Pass.rulePreContexts = []
Definition at line 780 of file S__i_l_f.py.
rules
fontTools.ttLib.tables.S__i_l_f.Pass.rules = []
Definition at line 779 of file S__i_l_f.py.
Referenced by pandas.tseries.holiday.AbstractHolidayCalendar.__init__(), packaging._tokenizer.Tokenizer.check(), pandas.tseries.holiday.AbstractHolidayCalendar.holidays(), and pandas.tseries.holiday.AbstractHolidayCalendar.merge().
ruleSortKeys
list fontTools.ttLib.tables.S__i_l_f.Pass.ruleSortKeys = []
Definition at line 781 of file S__i_l_f.py.
startStates
fontTools.ttLib.tables.S__i_l_f.Pass.startStates = []
Definition at line 786 of file S__i_l_f.py.
stateTrans
fontTools.ttLib.tables.S__i_l_f.Pass.stateTrans = []
Definition at line 785 of file S__i_l_f.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ttLib/tables/S__i_l_f.py