Code Cloning Analysis: pandas.core.tools.datetimes Namespace Reference
pandas.core.tools.datetimes Namespace Reference
Classes
class FulldatetimeDict
class YearMonthDayDict
Functions
str|None _guess_datetime_format_for_array (arr, bool|None dayfirst=False)
bool should_cache (ArrayConvertible arg, float unique_share=0.7, int|None check_count=None)
Series _maybe_cache (ArrayConvertible arg, str|None format, bool cache, Callable convert_listlike)
Index _box_as_indexlike (ArrayLike dt_array, bool utc=False, Hashable|None name=None)
Index _convert_and_box_cache (DatetimeScalarOrArrayConvertible arg, Series cache_array, Hashable|None name=None)
_convert_listlike_datetimes (arg, str|None format, Hashable|None name=None, bool utc=False, str|None unit=None, DateTimeErrorChoices errors="raise", bool|None dayfirst=None, bool|None yearfirst=None, bool exact=True)
Index _array_strptime_with_fallback (arg, name, bool utc, str fmt, bool exact, str errors)
Index _to_datetime_with_unit (arg, unit, name, bool utc, str errors)
_adjust_to_origin (arg, origin, unit)
Timestamp to_datetime (DatetimeScalar arg, DateTimeErrorChoices errors=..., bool dayfirst=..., bool yearfirst=..., bool utc=..., str|None format=..., bool exact=..., str|None unit=..., bool infer_datetime_format=..., origin=..., bool cache=...)
Series to_datetime (Series|DictConvertible arg, DateTimeErrorChoices errors=..., bool dayfirst=..., bool yearfirst=..., bool utc=..., str|None format=..., bool exact=..., str|None unit=..., bool infer_datetime_format=..., origin=..., bool cache=...)
DatetimeIndex to_datetime (list|tuple|Index|ArrayLike arg, DateTimeErrorChoices errors=..., bool dayfirst=..., bool yearfirst=..., bool utc=..., str|None format=..., bool exact=..., str|None unit=..., bool infer_datetime_format=..., origin=..., bool cache=...)
DatetimeIndex|Series|DatetimeScalar|NaTType|None to_datetime (DatetimeScalarOrArrayConvertible|DictConvertible arg, DateTimeErrorChoices errors="raise", bool dayfirst=False, bool yearfirst=False, bool utc=False, str|None format=None, bool|lib.NoDefault exact=lib.no_default, str|None unit=None, lib.NoDefault|bool infer_datetime_format=lib.no_default, str origin="unix", bool cache=True)
_assemble_from_unit_mappings (arg, DateTimeErrorChoices errors, bool utc)
Variables
ArrayConvertible = Union[list, tuple, AnyArrayLike]
Scalar = Union[float, str]
DatetimeScalar = Union[Scalar, date, np.datetime64]
DatetimeScalarOrArrayConvertible = Union[DatetimeScalar, ArrayConvertible]
DatetimeDictArg = Union[list[Scalar], tuple[Scalar, ...], AnyArrayLike]
DictConvertible = Union[FulldatetimeDict, "DataFrame"]
int start_caching_at = 50
dict _unit_map
list __all__
Function Documentation
_adjust_to_origin()
pandas.core.tools.datetimes._adjust_to_origin (arg, origin, unit) protected
Helper function for to_datetime.
Adjust input argument to the specified origin
Parameters
----------
arg : list, tuple, ndarray, Series, Index
    date to be adjusted
origin : 'julian' or Timestamp
    origin offset for the arg
unit : str
    passed unit from to_datetime, must be 'D'
Returns
-------
ndarray or scalar of adjusted date(s)
Definition at line 555 of file datetimes.py.
Referenced by to_datetime().
_array_strptime_with_fallback()
Index pandas.core.tools.datetimes._array_strptime_with_fallback (arg, name, bool utc, str fmt, bool exact, str errors) protected
Call array_strptime, with fallback behavior depending on 'errors'.
Definition at line 458 of file datetimes.py.
Referenced by _convert_listlike_datetimes().
_assemble_from_unit_mappings()
pandas.core.tools.datetimes._assemble_from_unit_mappings (arg, DateTimeErrorChoices errors, bool utc) protected
assemble the unit specified fields from the arg (DataFrame)
Return a Series for actual parsing
Parameters
----------
arg : DataFrame
errors : {'ignore', 'raise', 'coerce'}, default 'raise'
    - If :const:`'raise'`, then invalid parsing will raise an exception
    - If :const:`'coerce'`, then invalid parsing will be set as :const:`NaT`
    - If :const:`'ignore'`, then invalid parsing will return the input
utc : bool
    Whether to convert/localize timestamps to UTC.
Returns
-------
Series
Definition at line 1142 of file datetimes.py.
Referenced by to_datetime().
_box_as_indexlike()
Index pandas.core.tools.datetimes._box_as_indexlike (ArrayLike dt_array, bool utc = False, Hashable | None name = None) protected
Properly boxes the ndarray of datetimes to DatetimeIndex
if it is possible or to generic Index instead
Parameters
----------
dt_array: 1-d array
    Array of datetimes to be wrapped in an Index.
utc : bool
    Whether to convert/localize timestamps to UTC.
name : string, default None
    Name for a resulting index
Returns
-------
result : datetime of converted dates
    - DatetimeIndex if convertible to sole datetime64 type
    - general Index otherwise
Definition at line 261 of file datetimes.py.
Referenced by _convert_and_box_cache(), and _convert_listlike_datetimes().
_convert_and_box_cache()
Index pandas.core.tools.datetimes._convert_and_box_cache (DatetimeScalarOrArrayConvertible arg, Series cache_array, Hashable | None name = None) protected
Convert array of dates with a cache and wrap the result in an Index.
Parameters
----------
arg : integer, float, string, datetime, list, tuple, 1-d array, Series
cache_array : Series
    Cache of converted, unique dates
name : string, default None
    Name for a DatetimeIndex
Returns
-------
result : Index-like of converted dates
Definition at line 290 of file datetimes.py.
References _box_as_indexlike().
Referenced by to_datetime().
_convert_listlike_datetimes()
pandas.core.tools.datetimes._convert_listlike_datetimes (arg, str | None format, Hashable | None name = None, bool utc = False, str | None unit = None, DateTimeErrorChoices errors = "raise", bool | None dayfirst = None, bool | None yearfirst = None, bool exact = True) protected
Helper function for to_datetime. Performs the conversions of 1D listlike
of dates
Parameters
----------
arg : list, tuple, ndarray, Series, Index
    date to be parsed
name : object
    None or string for the Index name
utc : bool
    Whether to convert/localize timestamps to UTC.
unit : str
    None or string of the frequency of the passed data
errors : str
    error handing behaviors from to_datetime, 'raise', 'coerce', 'ignore'
dayfirst : bool
    dayfirst parsing behavior from to_datetime
yearfirst : bool
    yearfirst parsing behavior from to_datetime
exact : bool, default True
    exact format matching behavior from to_datetime
Returns
-------
Index-like of parsed dates
Definition at line 316 of file datetimes.py.
References _array_strptime_with_fallback(), _box_as_indexlike(), and _to_datetime_with_unit().
_guess_datetime_format_for_array()
str | None pandas.core.tools.datetimes._guess_datetime_format_for_array (arr, bool | None dayfirst = False) protected
Definition at line 128 of file datetimes.py.
_maybe_cache()
Series pandas.core.tools.datetimes._maybe_cache (ArrayConvertible arg, str | None format, bool cache, Callable convert_listlike) protected
Create a cache of unique dates from an array of dates
Parameters
----------
arg : listlike, tuple, 1-d array, Series
format : string
    Strftime format to parse time
cache : bool
    True attempts to create a cache of converted values
convert_listlike : function
    Conversion function to apply on dates
Returns
-------
cache_array : Series
    Cache of converted, unique dates. Can be empty
Definition at line 211 of file datetimes.py.
References should_cache().
Referenced by to_datetime().
_to_datetime_with_unit()
Index pandas.core.tools.datetimes._to_datetime_with_unit (arg, unit, name, bool utc, str errors) protected
to_datetime specalized to the case where a 'unit' is passed.
Definition at line 487 of file datetimes.py.
References _to_datetime_with_unit().
Referenced by _convert_listlike_datetimes(), and _to_datetime_with_unit().
should_cache()
bool pandas.core.tools.datetimes.should_cache (ArrayConvertible arg, float unique_share = 0.7, int | None check_count = None)
Decides whether to do caching.
If the percent of unique elements among `check_count` elements less
than `unique_share * 100` then we can do caching.
Parameters
----------
arg: listlike, tuple, 1-d array, Series
unique_share: float, default=0.7, optional
    0 < unique_share < 1
check_count: int, optional
    0 <= check_count <= len(arg)
Returns
-------
do_caching: bool
Notes
-----
By default for a sequence of less than 50 items in size, we don't do
caching; for the number of elements less than 5000, we take ten percent of
all elements to check for a uniqueness share; if the sequence size is more
than 5000, then we check only the first 500 elements.
All constants were chosen empirically by.
Definition at line 151 of file datetimes.py.
Referenced by _maybe_cache().
to_datetime() [1/4]
Timestamp pandas.core.tools.datetimes.to_datetime (DatetimeScalar arg, DateTimeErrorChoices errors = ..., bool dayfirst = ..., bool yearfirst = ..., bool utc = ..., str | None format = ..., bool exact = ..., str | None unit = ..., bool infer_datetime_format = ..., origin = ..., bool cache = ...)
Definition at line 628 of file datetimes.py.
to_datetime() [2/4]
DatetimeIndex | Series | DatetimeScalar | NaTType | None pandas.core.tools.datetimes.to_datetime (DatetimeScalarOrArrayConvertible | DictConvertible arg, DateTimeErrorChoices errors = "raise", bool dayfirst = False, bool yearfirst = False, bool utc = False, str | None format = None, bool | lib.NoDefault exact = lib.no_default, str | None unit = None, lib.NoDefault | bool infer_datetime_format = lib.no_default, str origin = "unix", bool cache = True)
Convert argument to datetime.
This function converts a scalar, array-like, :class:`Series` or
:class:`DataFrame`/dict-like to a pandas datetime object.
Parameters
----------
arg : int, float, str, datetime, list, tuple, 1-d array, Series, DataFrame/dict-like
    The object to convert to a datetime. If a :class:`DataFrame` is provided, the
    method expects minimally the following columns: :const:`"year"`,
    :const:`"month"`, :const:`"day"`. The column "year"
    must be specified in 4-digit format.
errors : {'ignore', 'raise', 'coerce'}, default 'raise'
    - If :const:`'raise'`, then invalid parsing will raise an exception.
    - If :const:`'coerce'`, then invalid parsing will be set as :const:`NaT`.
    - If :const:`'ignore'`, then invalid parsing will return the input.
dayfirst : bool, default False
    Specify a date parse order if `arg` is str or is list-like.
    If :const:`True`, parses dates with the day first, e.g. :const:`"10/11/12"`
    is parsed as :const:`2012-11-10`.
    .. warning::
        ``dayfirst=True`` is not strict, but will prefer to parse
        with day first.
yearfirst : bool, default False
    Specify a date parse order if `arg` is str or is list-like.
    - If :const:`True` parses dates with the year first, e.g.
      :const:`"10/11/12"` is parsed as :const:`2010-11-12`.
    - If both `dayfirst` and `yearfirst` are :const:`True`, `yearfirst` is
      preceded (same as :mod:`dateutil`).
    .. warning::
        ``yearfirst=True`` is not strict, but will prefer to parse
        with year first.
utc : bool, default False
    Control timezone-related parsing, localization and conversion.
    - If :const:`True`, the function *always* returns a timezone-aware
      UTC-localized :class:`Timestamp`, :class:`Series` or
      :class:`DatetimeIndex`. To do this, timezone-naive inputs are
      *localized* as UTC, while timezone-aware inputs are *converted* to UTC.
    - If :const:`False` (default), inputs will not be coerced to UTC.
      Timezone-naive inputs will remain naive, while timezone-aware ones
      will keep their time offsets. Limitations exist for mixed
      offsets (typically, daylight savings), see :ref:`Examples
      <to_datetime_tz_examples>` section for details.
    .. warning::
        In a future version of pandas, parsing datetimes with mixed time
        zones will raise an error unless `utc=True`.
        Please specify `utc=True` to opt in to the new behaviour
        and silence this warning. To create a `Series` with mixed offsets and
        `object` dtype, please use `apply` and `datetime.datetime.strptime`.
    See also: pandas general documentation about `timezone conversion and
    localization
    <https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html
    #time-zone-handling>`_.
format : str, default None
    The strftime to parse time, e.g. :const:`"%d/%m/%Y"`. See
    `strftime documentation
    <https://docs.python.org/3/library/datetime.html
    #strftime-and-strptime-behavior>`_ for more information on choices, though
    note that :const:`"%f"` will parse all the way up to nanoseconds.
    You can also pass:
    - "ISO8601", to parse any `ISO8601 <https://en.wikipedia.org/wiki/ISO_8601>`_
      time string (not necessarily in exactly the same format);
    - "mixed", to infer the format for each element individually. This is risky,
      and you should probably use it along with `dayfirst`.
    .. note::
        If a :class:`DataFrame` is passed, then `format` has no effect.
exact : bool, default True
    Control how `format` is used:
    - If :const:`True`, require an exact `format` match.
    - If :const:`False`, allow the `format` to match anywhere in the target
      string.
    Cannot be used alongside ``format='ISO8601'`` or ``format='mixed'``.
unit : str, default 'ns'
    The unit of the arg (D,s,ms,us,ns) denote the unit, which is an
    integer or float number. This will be based off the origin.
    Example, with ``unit='ms'`` and ``origin='unix'``, this would calculate
    the number of milliseconds to the unix epoch start.
infer_datetime_format : bool, default False
    If :const:`True` and no `format` is given, attempt to infer the format
    of the datetime strings based on the first non-NaN element,
    and if it can be inferred, switch to a faster method of parsing them.
    In some cases this can increase the parsing speed by ~5-10x.
    .. deprecated:: 2.0.0
        A strict version of this argument is now the default, passing it has
        no effect.
origin : scalar, default 'unix'
    Define the reference date. The numeric values would be parsed as number
    of units (defined by `unit`) since this reference date.
    - If :const:`'unix'` (or POSIX) time; origin is set to 1970-01-01.
    - If :const:`'julian'`, unit must be :const:`'D'`, and origin is set to
      beginning of Julian Calendar. Julian day number :const:`0` is assigned
      to the day starting at noon on January 1, 4713 BC.
    - If Timestamp convertible (Timestamp, dt.datetime, np.datetimt64 or date
      string), origin is set to Timestamp identified by origin.
    - If a float or integer, origin is the difference
      (in units determined by the ``unit`` argument) relative to 1970-01-01.
cache : bool, default True
    If :const:`True`, use a cache of unique, converted dates to apply the
    datetime conversion. May produce significant speed-up when parsing
    duplicate date strings, especially ones with timezone offsets. The cache
    is only used when there are at least 50 values. The presence of
    out-of-bounds values will render the cache unusable and may slow down
    parsing.
Returns
-------
datetime
    If parsing succeeded.
    Return type depends on input (types in parenthesis correspond to
    fallback in case of unsuccessful timezone or out-of-range timestamp
    parsing):
    - scalar: :class:`Timestamp` (or :class:`datetime.datetime`)
    - array-like: :class:`DatetimeIndex` (or :class:`Series` with
      :class:`object` dtype containing :class:`datetime.datetime`)
    - Series: :class:`Series` of :class:`datetime64` dtype (or
      :class:`Series` of :class:`object` dtype containing
      :class:`datetime.datetime`)
    - DataFrame: :class:`Series` of :class:`datetime64` dtype (or
      :class:`Series` of :class:`object` dtype containing
      :class:`datetime.datetime`)
Raises
------
ParserError
    When parsing a date from string fails.
ValueError
    When another datetime conversion error happens. For example when one
    of 'year', 'month', day' columns is missing in a :class:`DataFrame`, or
    when a Timezone-aware :class:`datetime.datetime` is found in an array-like
    of mixed time offsets, and ``utc=False``.
See Also
--------
DataFrame.astype : Cast argument to a specified dtype.
to_timedelta : Convert argument to timedelta.
convert_dtypes : Convert dtypes.
Notes
-----
Many input types are supported, and lead to different output types:
- **scalars** can be int, float, str, datetime object (from stdlib :mod:`datetime`
  module or :mod:`numpy`). They are converted to :class:`Timestamp` when
  possible, otherwise they are converted to :class:`datetime.datetime`.
  None/NaN/null scalars are converted to :const:`NaT`.
- **array-like** can contain int, float, str, datetime objects. They are
  converted to :class:`DatetimeIndex` when possible, otherwise they are
  converted to :class:`Index` with :class:`object` dtype, containing
  :class:`datetime.datetime`. None/NaN/null entries are converted to
  :const:`NaT` in both cases.
- **Series** are converted to :class:`Series` with :class:`datetime64`
  dtype when possible, otherwise they are converted to :class:`Series` with
  :class:`object` dtype, containing :class:`datetime.datetime`. None/NaN/null
  entries are converted to :const:`NaT` in both cases.
- **DataFrame/dict-like** are converted to :class:`Series` with
  :class:`datetime64` dtype. For each row a datetime is created from assembling
  the various dataframe columns. Column keys can be common abbreviations
  like ['year', 'month', 'day', 'minute', 'second', 'ms', 'us', 'ns']) or
  plurals of the same.
The following causes are responsible for :class:`datetime.datetime` objects
being returned (possibly inside an :class:`Index` or a :class:`Series` with
:class:`object` dtype) instead of a proper pandas designated type
(:class:`Timestamp`, :class:`DatetimeIndex` or :class:`Series`
with :class:`datetime64` dtype):
- when any input element is before :const:`Timestamp.min` or after
  :const:`Timestamp.max`, see `timestamp limitations
  <https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html
  #timeseries-timestamp-limits>`_.
- when ``utc=False`` (default) and the input is an array-like or
  :class:`Series` containing mixed naive/aware datetime, or aware with mixed
  time offsets. Note that this happens in the (quite frequent) situation when
  the timezone has a daylight savings policy. In that case you may wish to
  use ``utc=True``.
Examples
--------
**Handling various input formats**
Assembling a datetime from multiple columns of a :class:`DataFrame`. The keys
can be common abbreviations like ['year', 'month', 'day', 'minute', 'second',
'ms', 'us', 'ns']) or plurals of the same
>>> df = pd.DataFrame({'year': [2015, 2016],
...                    'month': [2, 3],
...                    'day': [4, 5]})
>>> pd.to_datetime(df)
0   2015-02-04
1   2016-03-05
dtype: datetime64[ns]
Using a unix epoch time
>>> pd.to_datetime(1490195805, unit='s')
Timestamp('2017-03-22 15:16:45')
>>> pd.to_datetime(1490195805433502912, unit='ns')
Timestamp('2017-03-22 15:16:45.433502912')
.. warning:: For float arg, precision rounding might happen. To prevent
    unexpected behavior use a fixed-width exact type.
Using a non-unix epoch origin
>>> pd.to_datetime([1, 2, 3], unit='D',
...                origin=pd.Timestamp('1960-01-01'))
DatetimeIndex(['1960-01-02', '1960-01-03', '1960-01-04'],
              dtype='datetime64[ns]', freq=None)
**Differences with strptime behavior**
:const:`"%f"` will parse all the way up to nanoseconds.
>>> pd.to_datetime('2018-10-26 12:00:00.0000000011',
...                format='%Y-%m-%d %H:%M:%S.%f')
Timestamp('2018-10-26 12:00:00.000000001')
**Non-convertible date/times**
Passing ``errors='coerce'`` will force an out-of-bounds date to :const:`NaT`,
in addition to forcing non-dates (or non-parseable dates) to :const:`NaT`.
>>> pd.to_datetime('13000101', format='%Y%m%d', errors='coerce')
NaT
.. _to_datetime_tz_examples:
**Timezones and time offsets**
The default behaviour (``utc=False``) is as follows:
- Timezone-naive inputs are converted to timezone-naive :class:`DatetimeIndex`:
>>> pd.to_datetime(['2018-10-26 12:00:00', '2018-10-26 13:00:15'])
DatetimeIndex(['2018-10-26 12:00:00', '2018-10-26 13:00:15'],
              dtype='datetime64[ns]', freq=None)
- Timezone-aware inputs *with constant time offset* are converted to
  timezone-aware :class:`DatetimeIndex`:
>>> pd.to_datetime(['2018-10-26 12:00 -0500', '2018-10-26 13:00 -0500'])
DatetimeIndex(['2018-10-26 12:00:00-05:00', '2018-10-26 13:00:00-05:00'],
              dtype='datetime64[ns, UTC-05:00]', freq=None)
- However, timezone-aware inputs *with mixed time offsets* (for example
  issued from a timezone with daylight savings, such as Europe/Paris)
  are **not successfully converted** to a :class:`DatetimeIndex`.
  Parsing datetimes with mixed time zones will show a warning unless
  `utc=True`. If you specify `utc=False` the warning below will be shown
  and a simple :class:`Index` containing :class:`datetime.datetime`
  objects will be returned:
>>> pd.to_datetime(['2020-10-25 02:00 +0200',
...                 '2020-10-25 04:00 +0100'])  # doctest: +SKIP
FutureWarning: In a future version of pandas, parsing datetimes with mixed
time zones will raise an error unless `utc=True`. Please specify `utc=True`
to opt in to the new behaviour and silence this warning. To create a `Series`
with mixed offsets and `object` dtype, please use `apply` and
`datetime.datetime.strptime`.
Index([2020-10-25 02:00:00+02:00, 2020-10-25 04:00:00+01:00],
      dtype='object')
- A mix of timezone-aware and timezone-naive inputs is also converted to
  a simple :class:`Index` containing :class:`datetime.datetime` objects:
>>> from datetime import datetime
>>> pd.to_datetime(["2020-01-01 01:00:00-01:00",
...                 datetime(2020, 1, 1, 3, 0)])  # doctest: +SKIP
FutureWarning: In a future version of pandas, parsing datetimes with mixed
time zones will raise an error unless `utc=True`. Please specify `utc=True`
to opt in to the new behaviour and silence this warning. To create a `Series`
with mixed offsets and `object` dtype, please use `apply` and
`datetime.datetime.strptime`.
Index([2020-01-01 01:00:00-01:00, 2020-01-01 03:00:00], dtype='object')
|
Setting ``utc=True`` solves most of the above issues:
- Timezone-naive inputs are *localized* as UTC
>>> pd.to_datetime(['2018-10-26 12:00', '2018-10-26 13:00'], utc=True)
DatetimeIndex(['2018-10-26 12:00:00+00:00', '2018-10-26 13:00:00+00:00'],
              dtype='datetime64[ns, UTC]', freq=None)
- Timezone-aware inputs are *converted* to UTC (the output represents the
  exact same datetime, but viewed from the UTC time offset `+00:00`).
>>> pd.to_datetime(['2018-10-26 12:00 -0530', '2018-10-26 12:00 -0500'],
...                utc=True)
DatetimeIndex(['2018-10-26 17:30:00+00:00', '2018-10-26 17:00:00+00:00'],
              dtype='datetime64[ns, UTC]', freq=None)
- Inputs can contain both string or datetime, the above
  rules still apply
>>> pd.to_datetime(['2018-10-26 12:00', datetime(2020, 1, 1, 18)], utc=True)
DatetimeIndex(['2018-10-26 12:00:00+00:00', '2020-01-01 18:00:00+00:00'],
              dtype='datetime64[ns, UTC]', freq=None)
Definition at line 678 of file datetimes.py.
References _adjust_to_origin(), _assemble_from_unit_mappings(), _convert_and_box_cache(), and _maybe_cache().
to_datetime() [3/4]
DatetimeIndex pandas.core.tools.datetimes.to_datetime (list | tuple | Index | ArrayLike arg, DateTimeErrorChoices errors = ..., bool dayfirst = ..., bool yearfirst = ..., bool utc = ..., str | None format = ..., bool exact = ..., str | None unit = ..., bool infer_datetime_format = ..., origin = ..., bool cache = ...)
Definition at line 662 of file datetimes.py.
to_datetime() [4/4]
Series pandas.core.tools.datetimes.to_datetime (Series | DictConvertible arg, DateTimeErrorChoices errors = ..., bool dayfirst = ..., bool yearfirst = ..., bool utc = ..., str | None format = ..., bool exact = ..., str | None unit = ..., bool infer_datetime_format = ..., origin = ..., bool cache = ...)
Definition at line 645 of file datetimes.py.
Variable Documentation
__all__
list pandas.core.tools.datetimes.__all__ private
Initial value:
=  [
    "DateParseError",
    "should_cache",
    "to_datetime",
]
Definition at line 1236 of file datetimes.py.
_unit_map
dict pandas.core.tools.datetimes._unit_map protected
Initial value:
=  {
    "year": "year",
    "years": "year",
    "month": "month",
    "months": "month",
    "day": "day",
    "days": "day",
    "hour": "h",
    "hours": "h",
    "minute": "m",
    "minutes": "m",
    "second": "s",
    "seconds": "s",
    "ms": "ms",
    "millisecond": "ms",
    "milliseconds": "ms",
    "us": "us",
    "microsecond": "us",
    "microseconds": "us",
    "ns": "ns",
    "nanosecond": "ns",
    "nanoseconds": "ns",
}
Definition at line 1117 of file datetimes.py.
ArrayConvertible
pandas.core.tools.datetimes.ArrayConvertible = Union[list, tuple, AnyArrayLike]
Definition at line 94 of file datetimes.py.
DatetimeDictArg
pandas.core.tools.datetimes.DatetimeDictArg = Union[list[Scalar], tuple[Scalar, ...], AnyArrayLike]
Definition at line 100 of file datetimes.py.
DatetimeScalar
pandas.core.tools.datetimes.DatetimeScalar = Union[Scalar, date, np.datetime64]
Definition at line 96 of file datetimes.py.
DatetimeScalarOrArrayConvertible
pandas.core.tools.datetimes.DatetimeScalarOrArrayConvertible = Union[DatetimeScalar, ArrayConvertible]
Definition at line 98 of file datetimes.py.
DictConvertible
pandas.core.tools.datetimes.DictConvertible = Union[FulldatetimeDict, "DataFrame"]
Definition at line 121 of file datetimes.py.
Scalar
pandas.core.tools.datetimes.Scalar = Union[float, str]
Definition at line 95 of file datetimes.py.
start_caching_at
int pandas.core.tools.datetimes.start_caching_at = 50
Definition at line 122 of file datetimes.py.