Code Cloning Analysis: scipy.linalg.tests.test_decomp_lu.TestLUSolve Class Reference
scipy.linalg.tests.test_decomp_lu.TestLUSolve Class Reference
Public Member Functions
setup_method (self)
test_lu (self)
test_check_finite (self)
Public Attributes
rng = np.random.default_rng(1682281250228846)
Detailed Description
Definition at line 246 of file test_decomp_lu.py.
Member Function Documentation
setup_method()
scipy.linalg.tests.test_decomp_lu.TestLUSolve.setup_method (self)
Definition at line 247 of file test_decomp_lu.py.
test_check_finite()
scipy.linalg.tests.test_decomp_lu.TestLUSolve.test_check_finite (self)
Definition at line 261 of file test_decomp_lu.py.
test_lu()
scipy.linalg.tests.test_decomp_lu.TestLUSolve.test_lu (self)
Definition at line 250 of file test_decomp_lu.py.
Member Data Documentation
rng
scipy.linalg.tests.test_decomp_lu.TestLUSolve.rng = np.random.default_rng(1682281250228846)
Definition at line 248 of file test_decomp_lu.py.
Referenced by scipy.stats._qmc.PoissonDisk._hypersphere_surface_sample(), scipy.stats._qmc.PoissonDisk._hypersphere_volume_sample(), scipy.stats._qmc.Halton._initialize_permutations(), scipy.stats._qmc.PoissonDisk._random(), scipy.stats._qmc.LatinHypercube._random_lhs(), scipy.stats._qmc.LatinHypercube._random_oa_lhs(), scipy.stats._qmc.Sobol._scramble(), sklearn.gaussian_process._gpc._BinaryGaussianProcessClassifierLaplace.fit(), and scipy.stats._qmc.QMCEngine.reset().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/linalg/tests/test_decomp_lu.py