Code Cloning Analysis: pandas._testing.asserters Namespace Reference
pandas._testing.asserters Namespace Reference
Functions
None assert_almost_equal (left, right, bool|Literal["equiv"] check_dtype="equiv", float rtol=1.0e-5, float atol=1.0e-8, **kwargs)
None _check_isinstance (left, right, cls)
None assert_dict_equal (left, right, bool compare_keys=True)
None assert_index_equal (Index left, Index right, bool|str exact="equiv", bool check_names=True, bool check_exact=True, bool check_categorical=True, bool check_order=True, float rtol=1.0e-5, float atol=1.0e-8, str obj="Index")
None assert_class_equal (left, right, bool|str exact=True, str obj="Input")
None assert_attr_equal (str attr, left, right, str obj="Attributes")
None assert_is_valid_plot_return_object (objs)
None assert_is_sorted (seq)
None assert_categorical_equal (left, right, bool check_dtype=True, bool check_category_order=True, str obj="Categorical")
None assert_interval_array_equal (left, right, bool|Literal["equiv"] exact="equiv", str obj="IntervalArray")
None assert_period_array_equal (left, right, str obj="PeriodArray")
None assert_datetime_array_equal (left, right, str obj="DatetimeArray", bool check_freq=True)
None assert_timedelta_array_equal (left, right, str obj="TimedeltaArray", bool check_freq=True)
NoReturn raise_assert_detail (obj, message, left, right, diff=None, first_diff=None, index_values=None)
None assert_numpy_array_equal (left, right, bool strict_nan=False, bool|Literal["equiv"] check_dtype=True, err_msg=None, check_same=None, str obj="numpy array", index_values=None)
None assert_extension_array_equal (left, right, bool|Literal["equiv"] check_dtype=True, index_values=None, bool|lib.NoDefault check_exact=lib.no_default, float|lib.NoDefault rtol=lib.no_default, float|lib.NoDefault atol=lib.no_default, str obj="ExtensionArray")
None assert_series_equal (left, right, bool|Literal["equiv"] check_dtype=True, bool|Literal["equiv"] check_index_type="equiv", bool check_series_type=True, bool check_names=True, bool|lib.NoDefault check_exact=lib.no_default, bool check_datetimelike_compat=False, bool check_categorical=True, bool check_category_order=True, bool check_freq=True, bool check_flags=True, float|lib.NoDefault rtol=lib.no_default, float|lib.NoDefault atol=lib.no_default, str obj="Series", *, bool check_index=True, bool check_like=False)
None assert_frame_equal (left, right, bool|Literal["equiv"] check_dtype=True, bool|Literal["equiv"] check_index_type="equiv", bool|Literal["equiv"] check_column_type="equiv", bool check_frame_type=True, bool check_names=True, bool by_blocks=False, bool|lib.NoDefault check_exact=lib.no_default, bool check_datetimelike_compat=False, bool check_categorical=True, bool check_like=False, bool check_freq=True, bool check_flags=True, float|lib.NoDefault rtol=lib.no_default, float|lib.NoDefault atol=lib.no_default, str obj="DataFrame")
None assert_equal (left, right, **kwargs)
None assert_sp_array_equal (left, right)
None assert_contains_all (iterable, dic)
None assert_copy (iter1, iter2, **eql_kwargs)
bool is_extension_array_dtype_and_needs_i8_conversion (DtypeObj left_dtype, DtypeObj right_dtype)
None assert_indexing_slices_equivalent (Series ser, slice l_slc, slice i_slc)
None assert_metadata_equivalent (DataFrame|Series left, DataFrame|Series|None right=None)
Function Documentation
_check_isinstance()
None pandas._testing.asserters._check_isinstance (left, right, cls) protected
Helper method for our assert_* methods that ensures that
the two objects being compared have the right type before
proceeding with the comparison.
Parameters
----------
left : The first object being compared.
right : The second object being compared.
cls : The class type to check against.
Raises
------
AssertionError : Either `left` or `right` is not an instance of `cls`.
Definition at line 148 of file asserters.py.
References _check_isinstance().
Referenced by _check_isinstance(), assert_categorical_equal(), assert_frame_equal(), assert_index_equal(), assert_interval_array_equal(), assert_numpy_array_equal(), assert_series_equal(), and assert_sp_array_equal().
assert_almost_equal()
None pandas._testing.asserters.assert_almost_equal (left, right, bool | Literal["equiv"] check_dtype = "equiv", float rtol = 1.0e-5, float atol = 1.0e-8, ** kwargs)
Check that the left and right objects are approximately equal.
By approximately equal, we refer to objects that are numbers or that
contain numbers which may be equivalent to specific levels of precision.
Parameters
----------
left : object
right : object
check_dtype : bool or {'equiv'}, default 'equiv'
    Check dtype if both a and b are the same type. If 'equiv' is passed in,
    then `RangeIndex` and `Index` with int64 dtype are also considered
    equivalent when doing type checking.
rtol : float, default 1e-5
    Relative tolerance.
atol : float, default 1e-8
    Absolute tolerance.
Definition at line 66 of file asserters.py.
References assert_class_equal(), assert_frame_equal(), assert_index_equal(), and assert_series_equal().
Referenced by assert_copy(), and assert_equal().
assert_attr_equal()
None pandas._testing.asserters.assert_attr_equal (str attr, left, right, str obj = "Attributes")
Check attributes are equal. Both objects must have attribute.
Parameters
----------
attr : str
    Attribute name being compared.
left : object
right : object
obj : str, default 'Attributes'
    Specify object name being compared, internally used to show appropriate
    assertion message
Definition at line 386 of file asserters.py.
Referenced by assert_categorical_equal(), assert_extension_array_equal(), assert_index_equal(), assert_interval_array_equal(), assert_numpy_array_equal(), assert_series_equal(), and assert_sp_array_equal().
assert_categorical_equal()
None pandas._testing.asserters.assert_categorical_equal (left, right, bool check_dtype = True, bool check_category_order = True, str obj = "Categorical")
Test that Categoricals are equivalent.
Parameters
----------
left : Categorical
right : Categorical
check_dtype : bool, default True
    Check that integer dtype of the codes are the same.
check_category_order : bool, default True
    Whether the order of the categories should be compared, which
    implies identical integer codes.  If False, only the resulting
    values are compared.  The ordered attribute is
    checked regardless.
obj : str, default 'Categorical'
    Specify object name being compared, internally used to show appropriate
    assertion message.
Definition at line 458 of file asserters.py.
References _check_isinstance(), assert_attr_equal(), assert_index_equal(), and assert_numpy_array_equal().
Referenced by assert_index_equal(), and assert_series_equal().
assert_class_equal()
None pandas._testing.asserters.assert_class_equal (left, right, bool | str exact = True, str obj = "Input")
Checks classes are equal.
Definition at line 352 of file asserters.py.
Referenced by assert_almost_equal(), assert_index_equal(), assert_numpy_array_equal(), and assert_series_equal().
assert_contains_all()
None pandas._testing.asserters.assert_contains_all (iterable, dic)
Definition at line 1395 of file asserters.py.
assert_copy()
None pandas._testing.asserters.assert_copy (iter1, iter2, ** eql_kwargs)
iter1, iter2: iterables that produce elements
comparable with assert_almost_equal
Checks that the elements are equal, but not
the same object. (Does not check that items
in sequences are also not the same object)
Definition at line 1400 of file asserters.py.
References assert_almost_equal().
assert_datetime_array_equal()
None pandas._testing.asserters.assert_datetime_array_equal (left, right, str obj = "DatetimeArray", bool check_freq = True)
Definition at line 557 of file asserters.py.
assert_dict_equal()
None pandas._testing.asserters.assert_dict_equal (left, right, bool compare_keys = True)
Definition at line 176 of file asserters.py.
assert_equal()
None pandas._testing.asserters.assert_equal (left, right, ** kwargs)
Wrapper for tm.assert_*_equal to dispatch to the appropriate test function.
Parameters
----------
left, right : Index, Series, DataFrame, ExtensionArray, or np.ndarray
    The two items to be compared.
**kwargs
    All keyword arguments are passed through to the underlying assert method.
Definition at line 1321 of file asserters.py.
References assert_almost_equal(), assert_extension_array_equal(), assert_frame_equal(), assert_index_equal(), assert_interval_array_equal(), assert_numpy_array_equal(), and assert_series_equal().
Referenced by assert_interval_array_equal().
assert_extension_array_equal()
None pandas._testing.asserters.assert_extension_array_equal (left, right, bool | Literal["equiv"] check_dtype = True, index_values = None, bool | lib.NoDefault check_exact = lib.no_default, float | lib.NoDefault rtol = lib.no_default, float | lib.NoDefault atol = lib.no_default, str obj = "ExtensionArray")
Check that left and right ExtensionArrays are equal.
Parameters
----------
left, right : ExtensionArray
    The two arrays to compare.
check_dtype : bool, default True
    Whether to check if the ExtensionArray dtypes are identical.
index_values : Index | numpy.ndarray, default None
    Optional index (shared by both left and right), used in output.
check_exact : bool, default False
    Whether to compare number exactly.
    .. versionchanged:: 2.2.0
        Defaults to True for integer dtypes if none of
        ``check_exact``, ``rtol`` and ``atol`` are specified.
rtol : float, default 1e-5
    Relative tolerance. Only used when check_exact is False.
atol : float, default 1e-8
    Absolute tolerance. Only used when check_exact is False.
obj : str, default 'ExtensionArray'
    Specify object name being compared, internally used to show appropriate
    assertion message.
    .. versionadded:: 2.0.0
Notes
-----
Missing values are checked separately from valid values.
A mask of missing values is computed for each and checked to match.
The remaining all-valid values are cast to object dtype and checked.
Examples
--------
>>> from pandas import testing as tm
>>> a = pd.Series([1, 2, 3, 4])
>>> b, c = a.array, a.array
>>> tm.assert_extension_array_equal(b, c)
Definition at line 703 of file asserters.py.
References assert_attr_equal(), and assert_numpy_array_equal().
Referenced by assert_equal(), assert_is_sorted(), and assert_series_equal().
assert_frame_equal()
None pandas._testing.asserters.assert_frame_equal (left, right, bool | Literal["equiv"] check_dtype = True, bool | Literal["equiv"] check_index_type = "equiv", bool | Literal["equiv"] check_column_type = "equiv", bool check_frame_type = True, bool check_names = True, bool by_blocks = False, bool | lib.NoDefault check_exact = lib.no_default, bool check_datetimelike_compat = False, bool check_categorical = True, bool check_like = False, bool check_freq = True, bool check_flags = True, float | lib.NoDefault rtol = lib.no_default, float | lib.NoDefault atol = lib.no_default, str obj = "DataFrame")
Check that left and right DataFrame are equal.
This function is intended to compare two DataFrames and output any
differences. It is mostly intended for use in unit tests.
Additional parameters allow varying the strictness of the
equality checks performed.
Parameters
----------
left : DataFrame
    First DataFrame to compare.
right : DataFrame
    Second DataFrame to compare.
check_dtype : bool, default True
    Whether to check the DataFrame dtype is identical.
check_index_type : bool or {'equiv'}, default 'equiv'
    Whether to check the Index class, dtype and inferred_type
    are identical.
check_column_type : bool or {'equiv'}, default 'equiv'
    Whether to check the columns class, dtype and inferred_type
    are identical. Is passed as the ``exact`` argument of
    :func:`assert_index_equal`.
check_frame_type : bool, default True
    Whether to check the DataFrame class is identical.
check_names : bool, default True
    Whether to check that the `names` attribute for both the `index`
    and `column` attributes of the DataFrame is identical.
by_blocks : bool, default False
    Specify how to compare internal data. If False, compare by columns.
    If True, compare by blocks.
check_exact : bool, default False
    Whether to compare number exactly.
    .. versionchanged:: 2.2.0
        Defaults to True for integer dtypes if none of
        ``check_exact``, ``rtol`` and ``atol`` are specified.
check_datetimelike_compat : bool, default False
    Compare datetime-like which is comparable ignoring dtype.
check_categorical : bool, default True
    Whether to compare internal Categorical exactly.
check_like : bool, default False
    If True, ignore the order of index & columns.
    Note: index labels must match their respective rows
    (same as in columns) - same labels must be with the same data.
check_freq : bool, default True
    Whether to check the `freq` attribute on a DatetimeIndex or TimedeltaIndex.
check_flags : bool, default True
    Whether to check the `flags` attribute.
rtol : float, default 1e-5
    Relative tolerance. Only used when check_exact is False.
atol : float, default 1e-8
    Absolute tolerance. Only used when check_exact is False.
obj : str, default 'DataFrame'
    Specify object name being compared, internally used to show appropriate
    assertion message.
See Also
--------
assert_series_equal : Equivalent method for asserting Series equality.
DataFrame.equals : Check DataFrame equality.
Examples
--------
This example shows comparing two DataFrames that are equal
but with columns of differing dtypes.
>>> from pandas.testing import assert_frame_equal
>>> df1 = pd.DataFrame({'a': [1, 2], 'b': [3, 4]})
>>> df2 = pd.DataFrame({'a': [1, 2], 'b': [3.0, 4.0]})
df1 equals itself.
>>> assert_frame_equal(df1, df1)
df1 differs from df2 as column 'b' is of a different type.
>>> assert_frame_equal(df1, df2)
Traceback (most recent call last):
...
AssertionError: Attributes of DataFrame.iloc[:, 1] (column name="b") are different
Attribute "dtype" are different
[left]:  int64
[right]: float64
Ignore differing dtypes in columns with check_dtype.
>>> assert_frame_equal(df1, df2, check_dtype=False)
Definition at line 1118 of file asserters.py.
References _check_isinstance(), assert_frame_equal(), assert_index_equal(), and assert_series_equal().
Referenced by assert_almost_equal(), assert_equal(), and assert_frame_equal().
assert_index_equal()
None pandas._testing.asserters.assert_index_equal (Index left, Index right, bool | str exact = "equiv", bool check_names = True, bool check_exact = True, bool check_categorical = True, bool check_order = True, float rtol = 1.0e-5, float atol = 1.0e-8, str obj = "Index")
Check that left and right Index are equal.
Parameters
----------
left : Index
right : Index
exact : bool or {'equiv'}, default 'equiv'
    Whether to check the Index class, dtype and inferred_type
    are identical. If 'equiv', then RangeIndex can be substituted for
    Index with an int64 dtype as well.
check_names : bool, default True
    Whether to check the names attribute.
check_exact : bool, default True
    Whether to compare number exactly.
check_categorical : bool, default True
    Whether to compare internal Categorical exactly.
check_order : bool, default True
    Whether to compare the order of index entries as well as their values.
    If True, both indexes must contain the same elements, in the same order.
    If False, both indexes must contain the same elements, but in any order.
rtol : float, default 1e-5
    Relative tolerance. Only used when check_exact is False.
atol : float, default 1e-8
    Absolute tolerance. Only used when check_exact is False.
obj : str, default 'Index'
    Specify object name being compared, internally used to show appropriate
    assertion message.
Examples
--------
>>> from pandas import testing as tm
>>> a = pd.Index([1, 2, 3])
>>> b = pd.Index([1, 2, 3])
>>> tm.assert_index_equal(a, b)
Definition at line 181 of file asserters.py.
References _check_isinstance(), assert_attr_equal(), assert_categorical_equal(), assert_class_equal(), assert_index_equal(), assert_interval_array_equal(), and assert_numpy_array_equal().
Referenced by assert_almost_equal(), assert_categorical_equal(), assert_equal(), assert_frame_equal(), assert_index_equal(), and assert_series_equal().
assert_indexing_slices_equivalent()
None pandas._testing.asserters.assert_indexing_slices_equivalent (Series ser, slice l_slc, slice i_slc)
Check that ser.iloc[i_slc] matches ser.loc[l_slc] and, if applicable,
ser[l_slc].
Definition at line 1434 of file asserters.py.
References assert_series_equal().
assert_interval_array_equal()
None pandas._testing.asserters.assert_interval_array_equal (left, right, bool | Literal["equiv"] exact = "equiv", str obj = "IntervalArray")
Test that two IntervalArrays are equivalent.
Parameters
----------
left, right : IntervalArray
    The IntervalArrays to compare.
exact : bool or {'equiv'}, default 'equiv'
    Whether to check the Index class, dtype and inferred_type
    are identical. If 'equiv', then RangeIndex can be substituted for
    Index with an int64 dtype as well.
obj : str, default 'IntervalArray'
    Specify object name being compared, internally used to show appropriate
    assertion message
Definition at line 519 of file asserters.py.
References _check_isinstance(), assert_attr_equal(), assert_equal(), and assert_numpy_array_equal().
Referenced by assert_equal(), assert_index_equal(), and assert_series_equal().
assert_is_sorted()
None pandas._testing.asserters.assert_is_sorted (seq)
Assert that the sequence is sorted.
Definition at line 447 of file asserters.py.
References assert_extension_array_equal(), and assert_numpy_array_equal().
assert_is_valid_plot_return_object()
None pandas._testing.asserters.assert_is_valid_plot_return_object (objs)
Definition at line 425 of file asserters.py.
assert_metadata_equivalent()
None pandas._testing.asserters.assert_metadata_equivalent (DataFrame | Series left, DataFrame | Series | None right = None)
Check that ._metadata attributes are equivalent.
Definition at line 1448 of file asserters.py.
assert_numpy_array_equal()
None pandas._testing.asserters.assert_numpy_array_equal (left, right, bool strict_nan = False, bool | Literal["equiv"] check_dtype = True, err_msg = None, check_same = None, str obj = "numpy array", index_values = None)
Check that 'np.ndarray' is equivalent.
Parameters
----------
left, right : numpy.ndarray or iterable
    The two arrays to be compared.
strict_nan : bool, default False
    If True, consider NaN and None to be different.
check_dtype : bool, default True
    Check dtype if both a and b are np.ndarray.
err_msg : str, default None
    If provided, used as assertion message.
check_same : None|'copy'|'same', default None
    Ensure left and right refer/do not refer to the same memory area.
obj : str, default 'numpy array'
    Specify object name being compared, internally used to show appropriate
    assertion message.
index_values : Index | numpy.ndarray, default None
    optional index (shared by both left and right), used in output.
Definition at line 623 of file asserters.py.
References _check_isinstance(), assert_attr_equal(), and assert_class_equal().
Referenced by assert_categorical_equal(), assert_equal(), assert_extension_array_equal(), assert_index_equal(), assert_interval_array_equal(), assert_is_sorted(), assert_series_equal(), and assert_sp_array_equal().
assert_period_array_equal()
None pandas._testing.asserters.assert_period_array_equal (left, right, str obj = "PeriodArray")
Definition at line 550 of file asserters.py.
assert_series_equal()
None pandas._testing.asserters.assert_series_equal (left, right, bool | Literal["equiv"] check_dtype = True, bool | Literal["equiv"] check_index_type = "equiv", bool check_series_type = True, bool check_names = True, bool | lib.NoDefault check_exact = lib.no_default, bool check_datetimelike_compat = False, bool check_categorical = True, bool check_category_order = True, bool check_freq = True, bool check_flags = True, float | lib.NoDefault rtol = lib.no_default, float | lib.NoDefault atol = lib.no_default, str obj = "Series", * , bool check_index = True, bool check_like = False)
Check that left and right Series are equal.
Parameters
----------
left : Series
right : Series
check_dtype : bool, default True
    Whether to check the Series dtype is identical.
check_index_type : bool or {'equiv'}, default 'equiv'
    Whether to check the Index class, dtype and inferred_type
    are identical.
check_series_type : bool, default True
     Whether to check the Series class is identical.
check_names : bool, default True
    Whether to check the Series and Index names attribute.
check_exact : bool, default False
    Whether to compare number exactly.
    .. versionchanged:: 2.2.0
        Defaults to True for integer dtypes if none of
        ``check_exact``, ``rtol`` and ``atol`` are specified.
check_datetimelike_compat : bool, default False
    Compare datetime-like which is comparable ignoring dtype.
check_categorical : bool, default True
    Whether to compare internal Categorical exactly.
check_category_order : bool, default True
    Whether to compare category order of internal Categoricals.
check_freq : bool, default True
    Whether to check the `freq` attribute on a DatetimeIndex or TimedeltaIndex.
check_flags : bool, default True
    Whether to check the `flags` attribute.
rtol : float, default 1e-5
    Relative tolerance. Only used when check_exact is False.
atol : float, default 1e-8
    Absolute tolerance. Only used when check_exact is False.
obj : str, default 'Series'
    Specify object name being compared, internally used to show appropriate
    assertion message.
check_index : bool, default True
    Whether to check index equivalence. If False, then compare only values.
    .. versionadded:: 1.3.0
check_like : bool, default False
    If True, ignore the order of the index. Must be False if check_index is False.
    Note: same labels must be with the same data.
    .. versionadded:: 1.5.0
Examples
--------
>>> from pandas import testing as tm
>>> a = pd.Series([1, 2, 3, 4])
>>> b = pd.Series([1, 2, 3, 4])
>>> tm.assert_series_equal(a, b)
Definition at line 851 of file asserters.py.
References _check_isinstance(), assert_attr_equal(), assert_categorical_equal(), assert_class_equal(), assert_extension_array_equal(), assert_index_equal(), assert_interval_array_equal(), assert_numpy_array_equal(), and is_extension_array_dtype_and_needs_i8_conversion().
Referenced by assert_almost_equal(), assert_equal(), assert_frame_equal(), and assert_indexing_slices_equivalent().
assert_sp_array_equal()
None pandas._testing.asserters.assert_sp_array_equal (left, right)
Check that the left and right SparseArray are equal.
Parameters
----------
left : SparseArray
right : SparseArray
Definition at line 1362 of file asserters.py.
References _check_isinstance(), assert_attr_equal(), and assert_numpy_array_equal().
assert_timedelta_array_equal()
None pandas._testing.asserters.assert_timedelta_array_equal (left, right, str obj = "TimedeltaArray", bool check_freq = True)
Definition at line 569 of file asserters.py.
is_extension_array_dtype_and_needs_i8_conversion()
bool pandas._testing.asserters.is_extension_array_dtype_and_needs_i8_conversion (DtypeObj left_dtype, DtypeObj right_dtype)
Checks that we have the combination of an ExtensionArraydtype and
a dtype that should be converted to int64
Returns
-------
bool
Related to issue #37609
Definition at line 1418 of file asserters.py.
Referenced by assert_series_equal().
raise_assert_detail()
NoReturn pandas._testing.asserters.raise_assert_detail (obj, message, left, right, diff = None, first_diff = None, index_values = None)
Definition at line 579 of file asserters.py.