Code Cloning Analysis: matplotlib.tri._trifinder.TrapezoidMapTriFinder Class Reference
matplotlib.tri._trifinder.TrapezoidMapTriFinder Class Reference
Public Member Functions
__init__ (self, triangulation)
__call__ (self, x, y)
Public Member Functions inherited from matplotlib.tri._trifinder.TriFinder
__init__ (self, triangulation)
__call__ (self, x, y)
Protected Member Functions
_get_tree_stats (self)
_initialize (self)
_print_tree (self)
Protected Attributes
_cpp_trifinder
Protected Attributes inherited from matplotlib.tri._trifinder.TriFinder
_triangulation = triangulation
Detailed Description
`~matplotlib.tri.TriFinder` class implemented using the trapezoid
map algorithm from the book "Computational Geometry, Algorithms and
Applications", second edition, by M. de Berg, M. van Kreveld, M. Overmars
and O. Schwarzkopf.
The triangulation must be valid, i.e. it must not have duplicate points,
triangles formed from colinear points, or overlapping triangles.  The
algorithm has some tolerance to triangles formed from colinear points, but
this should not be relied upon.
Definition at line 27 of file _trifinder.py.
Constructor & Destructor Documentation
__init__()
matplotlib.tri._trifinder.TrapezoidMapTriFinder.__init__ (self, triangulation)
Definition at line 40 of file _trifinder.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__call__()
matplotlib.tri._trifinder.TrapezoidMapTriFinder.__call__ (self, x, y)
Return an array containing the indices of the triangles in which the
specified *x*, *y* points lie, or -1 for points that do not lie within
a triangle.
*x*, *y* are array-like x and y coordinates of the same shape and any
number of dimensions.
Returns integer array with the same shape and *x* and *y*.
Definition at line 47 of file _trifinder.py.
References _cpp_trifinder.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), and scipy.interpolate._fitpack2.SphereBivariateSpline.ev().
_get_tree_stats()
matplotlib.tri._trifinder.TrapezoidMapTriFinder._get_tree_stats (self) protected
Return a python list containing the statistics about the node tree:
    0: number of nodes (tree size)
    1: number of unique nodes
    2: number of trapezoids (tree leaf nodes)
    3: number of unique trapezoids
    4: maximum parent count (max number of times a node is repeated in
           tree)
    5: maximum depth of tree (one more than the maximum number of
           comparisons needed to search through the tree)
    6: mean of all trapezoid depths (one more than the average number
           of comparisons needed to search through the tree)
Definition at line 68 of file _trifinder.py.
References _cpp_trifinder.
_initialize()
matplotlib.tri._trifinder.TrapezoidMapTriFinder._initialize (self) protected
Initialize the underlying C++ object.  Can be called multiple times if,
for example, the triangulation is modified.
Definition at line 84 of file _trifinder.py.
References _cpp_trifinder.
Referenced by sklearn.neural_network._multilayer_perceptron.BaseMultilayerPerceptron._backprop(), sklearn.mixture._gaussian_mixture.GaussianMixture._initialize_parameters(), and sklearn.neighbors._nca.NeighborhoodComponentsAnalysis.fit().
_print_tree()
matplotlib.tri._trifinder.TrapezoidMapTriFinder._print_tree (self) protected
Print a text representation of the node tree, which is useful for
debugging purposes.
Definition at line 91 of file _trifinder.py.
References _cpp_trifinder.
Member Data Documentation
_cpp_trifinder
matplotlib.tri._trifinder.TrapezoidMapTriFinder._cpp_trifinder protected
Initial value:
=  _tri.TrapezoidMapTriFinder(
            triangulation.get_cpp_triangulation())
Definition at line 43 of file _trifinder.py.
Referenced by __call__(), _get_tree_stats(), _initialize(), and _print_tree().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/tri/_trifinder.py