Code Cloning Analysis: contourpy.dechunk Namespace Reference
contourpy.dechunk Namespace Reference
Functions
cpy.FillReturn dechunk_filled (cpy.FillReturn filled, FillType|str fill_type)
cpy.LineReturn dechunk_lines (cpy.LineReturn lines, LineType|str line_type)
list[cpy.FillReturn] dechunk_multi_filled (list[cpy.FillReturn] multi_filled, FillType|str fill_type)
list[cpy.LineReturn] dechunk_multi_lines (list[cpy.LineReturn] multi_lines, LineType|str line_type)
Function Documentation
dechunk_filled()
cpy.FillReturn contourpy.dechunk.dechunk_filled (cpy.FillReturn filled, FillType | str fill_type)
Return the specified filled contours with chunked data moved into the first chunk.
Filled contours that are not chunked (``FillType.OuterCode`` and ``FillType.OuterOffset``) and
those that are but only contain a single chunk are returned unmodified. Individual polygons are
unchanged, they are not geometrically combined.
Args:
    filled (sequence of arrays): Filled contour data, such as returned by
        :meth:`.ContourGenerator.filled`.
    fill_type (FillType or str): Type of :meth:`~.ContourGenerator.filled` as enum or string
        equivalent.
Return:
    Filled contours in a single chunk.
.. versionadded:: 1.2.0
Definition at line 19 of file dechunk.py.
Referenced by dechunk_multi_filled().
dechunk_lines()
cpy.LineReturn contourpy.dechunk.dechunk_lines (cpy.LineReturn lines, LineType | str line_type)
Return the specified contour lines with chunked data moved into the first chunk.
Contour lines that are not chunked (``LineType.Separate`` and ``LineType.SeparateCode``) and
those that are but only contain a single chunk are returned unmodified. Individual lines are
unchanged, they are not geometrically combined.
Args:
    lines (sequence of arrays): Contour line data, such as returned by
        :meth:`.ContourGenerator.lines`.
    line_type (LineType or str): Type of :meth:`~.ContourGenerator.lines` as enum or string
        equivalent.
Return:
    Contour lines in a single chunk.
.. versionadded:: 1.2.0
Definition at line 90 of file dechunk.py.
Referenced by dechunk_multi_lines().
dechunk_multi_filled()
list[cpy.FillReturn] contourpy.dechunk.dechunk_multi_filled (list[cpy.FillReturn] multi_filled, FillType | str fill_type)
Return multiple sets of filled contours with chunked data moved into the first chunks.
Filled contours that are not chunked (``FillType.OuterCode`` and ``FillType.OuterOffset``) and
those that are but only contain a single chunk are returned unmodified. Individual polygons are
unchanged, they are not geometrically combined.
Args:
    multi_filled (nested sequence of arrays): Filled contour data, such as returned by
        :meth:`.ContourGenerator.multi_filled`.
    fill_type (FillType or str): Type of :meth:`~.ContourGenerator.filled` as enum or string
        equivalent.
Return:
    Multiple sets of filled contours in a single chunk.
.. versionadded:: 1.3.0
Definition at line 150 of file dechunk.py.
References dechunk_filled().
dechunk_multi_lines()
list[cpy.LineReturn] contourpy.dechunk.dechunk_multi_lines (list[cpy.LineReturn] multi_lines, LineType | str line_type)
Return multiple sets of contour lines with all chunked data moved into the first chunks.
Contour lines that are not chunked (``LineType.Separate`` and ``LineType.SeparateCode``) and
those that are but only contain a single chunk are returned unmodified. Individual lines are
unchanged, they are not geometrically combined.
Args:
    multi_lines (nested sequence of arrays): Contour line data, such as returned by
        :meth:`.ContourGenerator.multi_lines`.
    line_type (LineType or str): Type of :meth:`~.ContourGenerator.lines` as enum or string
        equivalent.
Return:
    Multiple sets of contour lines in a single chunk.
.. versionadded:: 1.3.0
Definition at line 180 of file dechunk.py.
References dechunk_lines().