Code Cloning Analysis: fontTools.designspaceLib.split Namespace Reference
fontTools.designspaceLib.split Namespace Reference
Functions
str defaultMakeInstanceFilename (DesignSpaceDocument doc, InstanceDescriptor instance, StatNames statNames)
Iterator[Tuple[SimpleLocationDict, DesignSpaceDocument]] splitInterpolable (DesignSpaceDocument doc, bool makeNames=True, bool expandLocations=True, MakeInstanceFilenameCallable makeInstanceFilename=defaultMakeInstanceFilename)
Iterator[Tuple[str, DesignSpaceDocument]] splitVariableFonts (DesignSpaceDocument doc, bool makeNames=False, bool expandLocations=False, MakeInstanceFilenameCallable makeInstanceFilename=defaultMakeInstanceFilename)
Dict[str, DesignSpaceDocument] convert5to4 (DesignSpaceDocument doc)
DesignSpaceDocument _extractSubSpace (DesignSpaceDocument doc, Region userRegion, *, bool keepVFs, bool makeNames, bool expandLocations, MakeInstanceFilenameCallable makeInstanceFilename)
ConditionSet _conditionSetFrom (List[Dict[str, Any]] conditionSet)
List[RuleDescriptor] _subsetRulesBasedOnConditions (List[RuleDescriptor] rules, Region designRegion)
Dict[str, float] _filterLocation (Region userRegion, Dict[str, float] location)
Variables
LOGGER = logging.getLogger(__name__)
MakeInstanceFilenameCallable
Detailed Description
Allows building all the variable fonts of a DesignSpace version 5 by
splitting the document into interpolable sub-space, then into each VF.
Function Documentation
_conditionSetFrom()
ConditionSet fontTools.designspaceLib.split._conditionSetFrom (List[Dict[str, Any]] conditionSet) protected
Definition at line 391 of file split.py.
_extractSubSpace()
DesignSpaceDocument fontTools.designspaceLib.split._extractSubSpace (DesignSpaceDocument doc, Region userRegion, * , bool keepVFs, bool makeNames, bool expandLocations, MakeInstanceFilenameCallable makeInstanceFilename) protected
Definition at line 175 of file split.py.
_filterLocation()
Dict[str, float] fontTools.designspaceLib.split._filterLocation (Region userRegion, Dict[str, float] location) protected
Definition at line 467 of file split.py.
_subsetRulesBasedOnConditions()
List[RuleDescriptor] fontTools.designspaceLib.split._subsetRulesBasedOnConditions (List[RuleDescriptor] rules, Region designRegion) protected
Definition at line 402 of file split.py.
convert5to4()
Dict[str, DesignSpaceDocument] fontTools.designspaceLib.split.convert5to4 (DesignSpaceDocument doc)
Convert each variable font listed in this document into a standalone
format 4 designspace. This can be used to compile all the variable fonts
from a format 5 designspace using tools that only know about format 4.
.. versionadded:: 5.0
Definition at line 158 of file split.py.
References splitInterpolable(), and splitVariableFonts().
defaultMakeInstanceFilename()
str fontTools.designspaceLib.split.defaultMakeInstanceFilename (DesignSpaceDocument doc, InstanceDescriptor instance, StatNames statNames)
Default callable to synthesize an instance filename
when makeNames=True, for instances that don't specify an instance name
in the designspace. This part of the name generation can be overriden
because it's not specified by the STAT table.
Definition at line 41 of file split.py.
splitInterpolable()
Iterator[Tuple[SimpleLocationDict, DesignSpaceDocument]] fontTools.designspaceLib.split.splitInterpolable (DesignSpaceDocument doc, bool makeNames = True, bool expandLocations = True, MakeInstanceFilenameCallable makeInstanceFilename = defaultMakeInstanceFilename)
Split the given DS5 into several interpolable sub-designspaces.
There are as many interpolable sub-spaces as there are combinations of
discrete axis values.
E.g. with axes:
    - italic (discrete) Upright or Italic
    - style (discrete) Sans or Serif
    - weight (continuous) 100 to 900
There are 4 sub-spaces in which the Weight axis should interpolate:
(Upright, Sans), (Upright, Serif), (Italic, Sans) and (Italic, Serif).
The sub-designspaces still include the full axis definitions and STAT data,
but the rules, sources, variable fonts, instances are trimmed down to only
keep what falls within the interpolable sub-space.
Args:
  - ``makeNames``: Whether to compute the instance family and style
    names using the STAT data.
  - ``expandLocations``: Whether to turn all locations into "full"
    locations, including implicit default axis values where missing.
  - ``makeInstanceFilename``: Callable to synthesize an instance filename
    when makeNames=True, for instances that don't specify an instance name
    in the designspace. This part of the name generation can be overridden
    because it's not specified by the STAT table.
.. versionadded:: 5.0
Definition at line 54 of file split.py.
Referenced by convert5to4().
splitVariableFonts()
Iterator[Tuple[str, DesignSpaceDocument]] fontTools.designspaceLib.split.splitVariableFonts (DesignSpaceDocument doc, bool makeNames = False, bool expandLocations = False, MakeInstanceFilenameCallable makeInstanceFilename = defaultMakeInstanceFilename)
Convert each variable font listed in this document into a standalone
designspace. This can be used to compile all the variable fonts from a
format 5 designspace using tools that can only deal with 1 VF at a time.
Args:
  - ``makeNames``: Whether to compute the instance family and style
    names using the STAT data.
  - ``expandLocations``: Whether to turn all locations into "full"
    locations, including implicit default axis values where missing.
  - ``makeInstanceFilename``: Callable to synthesize an instance filename
    when makeNames=True, for instances that don't specify an instance name
    in the designspace. This part of the name generation can be overridden
    because it's not specified by the STAT table.
.. versionadded:: 5.0
Definition at line 121 of file split.py.
Referenced by convert5to4().
Variable Documentation
LOGGER
fontTools.designspaceLib.split.LOGGER = logging.getLogger(__name__)
Definition at line 34 of file split.py.
MakeInstanceFilenameCallable
fontTools.designspaceLib.split.MakeInstanceFilenameCallable
Initial value:
=  Callable[
    [DesignSpaceDocument, InstanceDescriptor, StatNames], str
]
Definition at line 36 of file split.py.