Code Cloning Analysis: joblib.compressor.BZ2CompressorWrapper Class Reference
joblib.compressor.BZ2CompressorWrapper Class Reference
Public Member Functions
__init__ (self)
compressor_file (self, fileobj, compresslevel=None)
decompressor_file (self, fileobj)
Public Member Functions inherited from joblib.compressor.CompressorWrapper
__init__ (self, obj, prefix=b"", extension="")
Protected Member Functions
_check_versions (self)
Additional Inherited Members
Public Attributes inherited from joblib.compressor.CompressorWrapper
fileobj_factory = obj
prefix = prefix
extension = extension
Detailed Description
Definition at line 121 of file compressor.py.
Constructor & Destructor Documentation
__init__()
joblib.compressor.BZ2CompressorWrapper.__init__ (self)
Definition at line 125 of file compressor.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_check_versions()
joblib.compressor.BZ2CompressorWrapper._check_versions (self) protected
Definition at line 131 of file compressor.py.
Referenced by compressor_file(), joblib.compressor.LZ4CompressorWrapper.compressor_file(), decompressor_file(), and joblib.compressor.LZ4CompressorWrapper.decompressor_file().
compressor_file()
joblib.compressor.BZ2CompressorWrapper.compressor_file (self, fileobj, compresslevel = None)
Returns an instance of a compressor file object.
Reimplemented from joblib.compressor.CompressorWrapper.
Definition at line 137 of file compressor.py.
References _check_versions(), and joblib.compressor.CompressorWrapper.fileobj_factory.
decompressor_file()
joblib.compressor.BZ2CompressorWrapper.decompressor_file (self, fileobj)
Returns an instance of a decompressor file object.
Reimplemented from joblib.compressor.CompressorWrapper.
Definition at line 145 of file compressor.py.
References _check_versions(), and joblib.compressor.CompressorWrapper.fileobj_factory.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/joblib/compressor.py