Code Cloning Analysis: fontTools.varLib.multiVarStore.MultiVarStoreInstancer Class Reference
fontTools.varLib.multiVarStore.MultiVarStoreInstancer Class Reference
Public Member Functions
__init__ (self, multivarstore, fvar_axes, location={})
setLocation (self, location)
__getitem__ (self, varidx)
interpolateFromDeltas (self, varDataIndex, deltas)
Static Public Member Functions
interpolateFromDeltasAndScalars (deltas, scalars)
Public Attributes
fvar_axes = fvar_axes
location = dict(location)
Protected Member Functions
_clearCaches (self)
_getScalar (self, regionIdx)
Protected Attributes
_varData = multivarstore.MultiVarData if multivarstore else []
tuple _regions
dict _scalars = {}
Detailed Description
Definition at line 158 of file multiVarStore.py.
Constructor & Destructor Documentation
__init__()
fontTools.varLib.multiVarStore.MultiVarStoreInstancer.__init__ (self, multivarstore, fvar_axes, location = {})
Definition at line 159 of file multiVarStore.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__getitem__()
fontTools.varLib.multiVarStore.MultiVarStoreInstancer.__getitem__ (self, varidx)
Definition at line 196 of file multiVarStore.py.
_clearCaches()
fontTools.varLib.multiVarStore.MultiVarStoreInstancer._clearCaches (self) protected
Definition at line 172 of file multiVarStore.py.
_getScalar()
fontTools.varLib.multiVarStore.MultiVarStoreInstancer._getScalar (self, regionIdx) protected
Definition at line 175 of file multiVarStore.py.
interpolateFromDeltas()
fontTools.varLib.multiVarStore.MultiVarStoreInstancer.interpolateFromDeltas (self, varDataIndex, deltas)
Definition at line 205 of file multiVarStore.py.
interpolateFromDeltasAndScalars()
fontTools.varLib.multiVarStore.MultiVarStoreInstancer.interpolateFromDeltasAndScalars (deltas, scalars) static
Definition at line 184 of file multiVarStore.py.
setLocation()
fontTools.varLib.multiVarStore.MultiVarStoreInstancer.setLocation (self, location)
Definition at line 168 of file multiVarStore.py.
Member Data Documentation
_regions
tuple fontTools.varLib.multiVarStore.MultiVarStoreInstancer._regions protected
Initial value:
=  (
            multivarstore.SparseVarRegionList.Region if multivarstore else []
        )
Definition at line 163 of file multiVarStore.py.
_scalars
dict fontTools.varLib.multiVarStore.MultiVarStoreInstancer._scalars = {} protected
Definition at line 173 of file multiVarStore.py.
_varData
fontTools.varLib.multiVarStore.MultiVarStoreInstancer._varData = multivarstore.MultiVarData if multivarstore else [] protected
Definition at line 162 of file multiVarStore.py.
fvar_axes
fontTools.varLib.multiVarStore.MultiVarStoreInstancer.fvar_axes = fvar_axes
Definition at line 160 of file multiVarStore.py.
location
fontTools.varLib.multiVarStore.MultiVarStoreInstancer.location = dict(location)
Definition at line 169 of file multiVarStore.py.
Referenced by joblib._store_backends.StoreBackendMixin.__repr__(), pip._internal.metadata.pkg_resources.Distribution._metadata_impl(), joblib._store_backends.StoreBackendMixin.clear(), joblib._store_backends.StoreBackendMixin.clear_item(), joblib._store_backends.FileSystemStoreBackend.clear_location(), joblib._store_backends.StoreBackendMixin.clear_path(), joblib._store_backends.FileSystemStoreBackend.configure(), joblib._store_backends.StoreBackendMixin.contains_item(), joblib._store_backends.StoreBackendMixin.contains_path(), joblib._store_backends.StoreBackendMixin.dump_item(), pip._internal.metadata.base.BaseDistribution.editable_project_location(), joblib._store_backends.StoreBackendMixin.get_cached_func_code(), joblib._store_backends.StoreBackendMixin.get_cached_func_info(), joblib._store_backends.StoreBackendMixin.get_item_info(), joblib._store_backends.FileSystemStoreBackend.get_items(), joblib._store_backends.StoreBackendMixin.get_metadata(), pip._internal.metadata.base.BaseDistribution.installed_as_egg(), pip._internal.metadata.base.BaseDistribution.is_extra_provided(), joblib._store_backends.StoreBackendMixin.load_item(), pip._internal.metadata.pkg_resources.Distribution.location(), joblib._store_backends.StoreBackendMixin.store_cached_func_code(), and joblib._store_backends.StoreBackendMixin.store_metadata().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/varLib/multiVarStore.py