Code Cloning Analysis: sklearn._loss.tests.test_loss Namespace Reference
sklearn._loss.tests.test_loss Namespace Reference
Functions
loss_instance_name (param)
random_y_true_raw_prediction (loss, n_samples, y_bound=(-100, 100), raw_bound=(-5, 5), seed=42)
numerical_derivative (func, x, eps)
test_loss_boundary (loss)
test_loss_boundary_y_true (loss, y_true_success, y_true_fail)
test_loss_boundary_y_pred (loss, y_pred_success, y_pred_fail)
test_loss_on_specific_values (loss, y_true, raw_prediction, loss_true, gradient_true, hessian_true)
test_loss_dtype (loss, readonly_memmap, dtype_in, dtype_out, sample_weight, out1, out2, n_threads)
test_loss_same_as_C_functions (loss, sample_weight)
test_loss_gradients_are_the_same (loss, sample_weight, global_random_seed)
test_sample_weight_multiplies (loss, sample_weight, global_random_seed)
test_graceful_squeezing (loss)
test_loss_of_perfect_prediction (loss, sample_weight)
test_gradients_hessians_numerically (loss, sample_weight, global_random_seed)
test_derivatives (loss, x0, y_true)
test_loss_intercept_only (loss, sample_weight)
test_specific_fit_intercept_only (loss, func, random_dist, global_random_seed)
test_multinomial_loss_fit_intercept_only ()
test_multinomial_cy_gradient (global_random_seed)
test_binomial_and_multinomial_loss (global_random_seed)
test_binomial_vs_alternative_formulation (y_true, y_pred, global_dtype)
test_predict_proba (loss, global_random_seed)
test_init_gradient_and_hessians (loss, sample_weight, dtype, order)
test_init_gradient_and_hessian_raises (loss, params, err_msg)
test_loss_init_parameter_validation (loss, params, err_type, err_msg)
test_loss_pickle (loss)
test_tweedie_log_identity_consistency (p)
Variables
ALL_LOSSES = list(_LOSSES.values())
list LOSS_INSTANCES = [loss() for loss in ALL_LOSSES]
quantile
power
list Y_COMMON_PARAMS
list Y_TRUE_PARAMS
list Y_PRED_PARAMS
Function Documentation
loss_instance_name()
sklearn._loss.tests.test_loss.loss_instance_name (param)
Definition at line 52 of file test_loss.py.
numerical_derivative()
sklearn._loss.tests.test_loss.numerical_derivative (func, x, eps)
Helper function for numerical (first) derivatives.
Definition at line 104 of file test_loss.py.
Referenced by test_gradients_hessians_numerically().
random_y_true_raw_prediction()
sklearn._loss.tests.test_loss.random_y_true_raw_prediction (loss, n_samples, y_bound = (-100, 100), raw_bound = (-5, 5), seed = 42)
Random generate y_true and raw_prediction in valid range.
Definition at line 67 of file test_loss.py.
Referenced by test_graceful_squeezing(), test_gradients_hessians_numerically(), test_loss_dtype(), test_loss_gradients_are_the_same(), test_loss_pickle(), test_loss_same_as_C_functions(), test_multinomial_cy_gradient(), test_predict_proba(), test_sample_weight_multiplies(), and test_tweedie_log_identity_consistency().
test_binomial_and_multinomial_loss()
sklearn._loss.tests.test_loss.test_binomial_and_multinomial_loss (global_random_seed)
Test that multinomial loss with n_classes = 2 is the same as binomial loss.
Definition at line 1107 of file test_loss.py.
test_binomial_vs_alternative_formulation()
sklearn._loss.tests.test_loss.test_binomial_vs_alternative_formulation (y_true, y_pred, global_dtype)
Test that both formulations of the binomial deviance agree.
Often, the binomial deviance or log loss is written in terms of a variable
z in {-1, +1}, but we use y in {0, 1}, hence z = 2 * y - 1.
ESL II Eq. (10.18):
    -loglike(z, f) = log(1 + exp(-2 * z * f))
Note:
    - ESL 2*f = raw_prediction, hence the factor 2 of ESL disappears.
    - Deviance = -2*loglike + .., but HalfBinomialLoss is half of the
      deviance, hence the factor of 2 cancels in the comparison.
Definition at line 1126 of file test_loss.py.
test_derivatives()
sklearn._loss.tests.test_loss.test_derivatives (loss, x0, y_true)
Test that gradients are zero at the minimum of the loss.
We check this on a single value/sample using Halley's method with the
first and second order derivatives computed by the Loss instance.
Note that methods of Loss instances operate on arrays while the newton
root finder expects a scalar or a one-element array for this purpose.
Definition at line 898 of file test_loss.py.
test_graceful_squeezing()
sklearn._loss.tests.test_loss.test_graceful_squeezing (loss)
Test that reshaped raw_prediction gives same results.
Definition at line 709 of file test_loss.py.
References random_y_true_raw_prediction().
test_gradients_hessians_numerically()
sklearn._loss.tests.test_loss.test_gradients_hessians_numerically (loss, sample_weight, global_random_seed)
Test gradients and hessians with numerical derivatives.
Gradient should equal the numerical derivatives of the loss function.
Hessians should equal the numerical derivatives of gradients.
Definition at line 791 of file test_loss.py.
References numerical_derivative(), and random_y_true_raw_prediction().
test_init_gradient_and_hessian_raises()
sklearn._loss.tests.test_loss.test_init_gradient_and_hessian_raises (loss, params, err_msg)
Test that init_gradient_and_hessian raises errors for invalid input.
Definition at line 1254 of file test_loss.py.
test_init_gradient_and_hessians()
sklearn._loss.tests.test_loss.test_init_gradient_and_hessians (loss, sample_weight, dtype, order)
Test that init_gradient_and_hessian works as expected.
passing sample_weight to a loss correctly influences the constant_hessian
attribute, and consequently the shape of the hessian array.
Definition at line 1208 of file test_loss.py.
test_loss_boundary()
sklearn._loss.tests.test_loss.test_loss_boundary (loss)
Test interval ranges of y_true and y_pred in losses.
Definition at line 119 of file test_loss.py.
test_loss_boundary_y_pred()
sklearn._loss.tests.test_loss.test_loss_boundary_y_pred (loss, y_pred_success, y_pred_fail)
Test boundaries of y_pred for loss functions.
Definition at line 221 of file test_loss.py.
test_loss_boundary_y_true()
sklearn._loss.tests.test_loss.test_loss_boundary_y_true (loss, y_true_success, y_true_fail)
Test boundaries of y_true for loss functions.
Definition at line 209 of file test_loss.py.
test_loss_dtype()
sklearn._loss.tests.test_loss.test_loss_dtype (loss, readonly_memmap, dtype_in, dtype_out, sample_weight, out1, out2, n_threads)
Test acceptance of dtypes, readonly and writeable arrays in loss functions.
Check that loss accepts if all input arrays are either all float32 or all
float64, and all output arrays are either all float32 or all float64.
Also check that input arrays can be readonly, e.g. memory mapped.
Definition at line 384 of file test_loss.py.
References random_y_true_raw_prediction().
test_loss_gradients_are_the_same()
sklearn._loss.tests.test_loss.test_loss_gradients_are_the_same (loss, sample_weight, global_random_seed)
Test that loss and gradient are the same across different functions.
Also test that output arguments contain correct results.
Definition at line 558 of file test_loss.py.
References random_y_true_raw_prediction().
test_loss_init_parameter_validation()
sklearn._loss.tests.test_loss.test_loss_init_parameter_validation (loss, params, err_type, err_msg)
Test that loss raises errors for invalid input.
Definition at line 1292 of file test_loss.py.
test_loss_intercept_only()
sklearn._loss.tests.test_loss.test_loss_intercept_only (loss, sample_weight)
Test that fit_intercept_only returns the argmin of the loss.
Also test that the gradient is zero at the minimum.
Definition at line 946 of file test_loss.py.
test_loss_of_perfect_prediction()
sklearn._loss.tests.test_loss.test_loss_of_perfect_prediction (loss, sample_weight)
Test value of perfect predictions.
Loss of y_pred = y_true plus constant_to_optimal_zero should sums up to
zero.
Definition at line 741 of file test_loss.py.
test_loss_on_specific_values()
sklearn._loss.tests.test_loss.test_loss_on_specific_values (loss, y_true, raw_prediction, loss_true, gradient_true, hessian_true)
Test losses, gradients and hessians at specific values.
Definition at line 349 of file test_loss.py.
test_loss_pickle()
sklearn._loss.tests.test_loss.test_loss_pickle (loss)
Test that losses can be pickled.
Definition at line 1299 of file test_loss.py.
References random_y_true_raw_prediction().
test_loss_same_as_C_functions()
sklearn._loss.tests.test_loss.test_loss_same_as_C_functions (loss, sample_weight)
Test that Python and Cython functions return same results.
Definition at line 478 of file test_loss.py.
References random_y_true_raw_prediction().
test_multinomial_cy_gradient()
sklearn._loss.tests.test_loss.test_multinomial_cy_gradient (global_random_seed)
Test that Multinomial cy_gradient gives the same result as gradient.
CyHalfMultinomialLoss does not inherit from CyLossFunction and has a different API.
As a consequence, the functions like `loss` and `gradient` do not rely on `cy_loss`
and `cy_gradient`.
Definition at line 1077 of file test_loss.py.
References random_y_true_raw_prediction().
test_multinomial_loss_fit_intercept_only()
sklearn._loss.tests.test_loss.test_multinomial_loss_fit_intercept_only ()
Test that fit_intercept_only returns the mean functional for CCE.
Definition at line 1054 of file test_loss.py.
test_predict_proba()
sklearn._loss.tests.test_loss.test_predict_proba (loss, global_random_seed)
Test that predict_proba and gradient_proba work as expected.
Definition at line 1161 of file test_loss.py.
References random_y_true_raw_prediction().
test_sample_weight_multiplies()
sklearn._loss.tests.test_loss.test_sample_weight_multiplies (loss, sample_weight, global_random_seed)
Test sample weights in loss, gradients and hessians.
Make sure that passing sample weights to loss, gradient and hessian
computation methods is equivalent to multiplying by the weights.
Definition at line 639 of file test_loss.py.
References random_y_true_raw_prediction().
test_specific_fit_intercept_only()
sklearn._loss.tests.test_loss.test_specific_fit_intercept_only (loss, func, random_dist, global_random_seed)
Test that fit_intercept_only returns the correct functional.
We test the functional for specific, meaningful distributions, e.g.
squared error estimates the expectation of a probability distribution.
Definition at line 1023 of file test_loss.py.
test_tweedie_log_identity_consistency()
sklearn._loss.tests.test_loss.test_tweedie_log_identity_consistency (p)
Test for identical losses when only the link function is different.
Definition at line 1317 of file test_loss.py.
References random_y_true_raw_prediction().
Variable Documentation
ALL_LOSSES
sklearn._loss.tests.test_loss.ALL_LOSSES = list(_LOSSES.values())
Definition at line 33 of file test_loss.py.
LOSS_INSTANCES
list sklearn._loss.tests.test_loss.LOSS_INSTANCES = [loss() for loss in ALL_LOSSES]
Definition at line 35 of file test_loss.py.
power
sklearn._loss.tests.test_loss.power
Definition at line 40 of file test_loss.py.
quantile
sklearn._loss.tests.test_loss.quantile
Definition at line 38 of file test_loss.py.
Y_COMMON_PARAMS
list sklearn._loss.tests.test_loss.Y_COMMON_PARAMS
Initial value:
=  [
    # (loss, [y success], [y fail])
    (HalfSquaredError(), [-100, 0, 0.1, 100], [-np.inf, np.inf]),
    (AbsoluteError(), [-100, 0, 0.1, 100], [-np.inf, np.inf]),
    (PinballLoss(), [-100, 0, 0.1, 100], [-np.inf, np.inf]),
    (HuberLoss(), [-100, 0, 0.1, 100], [-np.inf, np.inf]),
    (HalfPoissonLoss(), [0.1, 100], [-np.inf, -3, -0.1, np.inf]),
    (HalfGammaLoss(), [0.1, 100], [-np.inf, -3, -0.1, 0, np.inf]),
    (HalfTweedieLoss(power=-3), [0.1, 100], [-np.inf, np.inf]),
    (HalfTweedieLoss(power=0), [0.1, 100], [-np.inf, np.inf]),
    (HalfTweedieLoss(power=1.5), [0.1, 100], [-np.inf, -3, -0.1, np.inf]),
    (HalfTweedieLoss(power=2), [0.1, 100], [-np.inf, -3, -0.1, 0, np.inf]),
    (HalfTweedieLoss(power=3), [0.1, 100], [-np.inf, -3, -0.1, 0, np.inf]),
    (HalfTweedieLossIdentity(power=-3), [0.1, 100], [-np.inf, np.inf]),
    (HalfTweedieLossIdentity(power=0), [-3, -0.1, 0, 0.1, 100], [-np.inf, np.inf]),
    (HalfTweedieLossIdentity(power=1.5), [0.1, 100], [-np.inf, -3, -0.1, np.inf]),
    (HalfTweedieLossIdentity(power=2), [0.1, 100], [-np.inf, -3, -0.1, 0, np.inf]),
    (HalfTweedieLossIdentity(power=3), [0.1, 100], [-np.inf, -3, -0.1, 0, np.inf]),
    (HalfBinomialLoss(), [0.1, 0.5, 0.9], [-np.inf, -1, 2, np.inf]),
    (HalfMultinomialLoss(), [], [-np.inf, -1, 1.1, np.inf]),
]
Definition at line 155 of file test_loss.py.
Y_PRED_PARAMS
list sklearn._loss.tests.test_loss.Y_PRED_PARAMS
Initial value:
=  [
    # (loss, [y success], [y fail])
    (HalfPoissonLoss(), [], [0]),
    (HalfTweedieLoss(power=-3), [], [-3, -0.1, 0]),
    (HalfTweedieLoss(power=0), [], [-3, -0.1, 0]),
    (HalfTweedieLoss(power=1.5), [], [0]),
    (HalfTweedieLossIdentity(power=-3), [], [-3, -0.1, 0]),
    (HalfTweedieLossIdentity(power=0), [-3, -0.1, 0], []),
    (HalfTweedieLossIdentity(power=1.5), [], [0]),
    (HalfBinomialLoss(), [], [0, 1]),
    (HalfMultinomialLoss(), [0.1, 0.5], [0, 1]),
]
Definition at line 191 of file test_loss.py.
Y_TRUE_PARAMS
list sklearn._loss.tests.test_loss.Y_TRUE_PARAMS
Initial value:
=  [  # type: ignore[var-annotated]
    # (loss, [y success], [y fail])
    (HalfPoissonLoss(), [0], []),
    (HuberLoss(), [0], []),
    (HalfTweedieLoss(power=-3), [-100, -0.1, 0], []),
    (HalfTweedieLoss(power=0), [-100, 0], []),
    (HalfTweedieLoss(power=1.5), [0], []),
    (HalfTweedieLossIdentity(power=-3), [-100, -0.1, 0], []),
    (HalfTweedieLossIdentity(power=0), [-100, 0], []),
    (HalfTweedieLossIdentity(power=1.5), [0], []),
    (HalfBinomialLoss(), [0, 1], []),
    (HalfMultinomialLoss(), [0.0, 1.0, 2], []),
]
Definition at line 178 of file test_loss.py.