Code Cloning Analysis: fontTools.voltLib.ast.PositionAttachCursiveDefinition Class Reference
fontTools.voltLib.ast.PositionAttachCursiveDefinition Class Reference
Public Member Functions
__init__ (self, coverages_exit, coverages_enter, location=None)
__str__ (self)
Public Member Functions inherited from fontTools.voltLib.ast.Element
__init__ (self, location=None)
build (self, builder)
__str__ (self)
Public Attributes
coverages_exit = coverages_exit
coverages_enter = coverages_enter
Public Attributes inherited from fontTools.voltLib.ast.Element
location = location
Detailed Description
Definition at line 344 of file ast.py.
Constructor & Destructor Documentation
__init__()
fontTools.voltLib.ast.PositionAttachCursiveDefinition.__init__ (self, coverages_exit, coverages_enter, location = None)
Definition at line 345 of file ast.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__str__()
fontTools.voltLib.ast.PositionAttachCursiveDefinition.__str__ (self)
Definition at line 350 of file ast.py.
Referenced by numpy.polynomial._polybase.ABCPolyBase._get_coefficients().
Member Data Documentation
coverages_enter
fontTools.voltLib.ast.PositionAttachCursiveDefinition.coverages_enter = coverages_enter
Definition at line 348 of file ast.py.
coverages_exit
fontTools.voltLib.ast.PositionAttachCursiveDefinition.coverages_exit = coverages_exit
Definition at line 347 of file ast.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/voltLib/ast.py