Code Cloning Analysis: pip._vendor.pyparsing.core.WordEnd Class Reference
pip._vendor.pyparsing.core.WordEnd Class Reference
Public Member Functions
__init__ (self, str word_chars=printables, *, str wordChars=printables)
parseImpl (self, instring, loc, doActions=True)
Public Member Functions inherited from pip._vendor.pyparsing.core.PositionToken
__init__ (self)
Public Member Functions inherited from pip._vendor.pyparsing.core.Token
__init__ (self)
Public Member Functions inherited from pip._vendor.pyparsing.core.ParserElement
using_each (cls, seq, **class_kwargs)
__init__ (self, bool savelist=False)
"ParserElement" suppress_warning (self, Diagnostics warning_type)
visit_all (self)
"ParserElement" copy (self)
"ParserElement" set_results_name (self, str name, bool list_all_matches=False, *, bool listAllMatches=False)
"ParserElement" set_break (self, bool break_flag=True)
"ParserElement" set_parse_action (self, *ParseAction fns, **kwargs)
"ParserElement" add_parse_action (self, *ParseAction fns, **kwargs)
"ParserElement" add_condition (self, *ParseCondition fns, **kwargs)
"ParserElement" set_fail_action (self, ParseFailAction fn)
int preParse (self, str instring, int loc)
postParse (self, instring, loc, tokenlist)
int try_parse (self, str instring, int loc, *, bool raise_fatal=False, bool do_actions=False)
bool can_parse_next (self, str instring, int loc, bool do_actions=False)
ParseResults parse_string (self, str instring, bool parse_all=False, *, bool parseAll=False)
Generator[Tuple[ParseResults, int, int], None, None] scan_string (self, str instring, int max_matches=_MAX_INT, bool overlap=False, *, bool debug=False, int maxMatches=_MAX_INT)
str transform_string (self, str instring, *, bool debug=False)
ParseResults search_string (self, str instring, int max_matches=_MAX_INT, *, bool debug=False, int maxMatches=_MAX_INT)
Generator[str, None, None] split (self, str instring, int maxsplit=_MAX_INT, bool include_separators=False, *, includeSeparators=False)
"ParserElement" __add__ (self, other)
"ParserElement" __radd__ (self, other)
"ParserElement" __sub__ (self, other)
"ParserElement" __rsub__ (self, other)
"ParserElement" __mul__ (self, other)
"ParserElement" __rmul__ (self, other)
"ParserElement" __or__ (self, other)
"ParserElement" __ror__ (self, other)
"ParserElement" __xor__ (self, other)
"ParserElement" __rxor__ (self, other)
"ParserElement" __and__ (self, other)
"ParserElement" __rand__ (self, other)
"ParserElement" __invert__ (self)
__getitem__ (self, key)
"ParserElement" __call__ (self, typing.Optional[str] name=None)
"ParserElement" suppress (self)
"ParserElement" ignore_whitespace (self, bool recursive=True)
"ParserElement" leave_whitespace (self, bool recursive=True)
"ParserElement" set_whitespace_chars (self, Union[Set[str], str] chars, bool copy_defaults=False)
"ParserElement" parse_with_tabs (self)
"ParserElement" ignore (self, "ParserElement" other)
"ParserElement" set_debug_actions (self, DebugStartAction start_action, DebugSuccessAction success_action, DebugExceptionAction exception_action)
"ParserElement" set_debug (self, bool flag=True, bool recurse=False)
str default_name (self)
"ParserElement" set_name (self, str name)
str name (self)
str __str__ (self)
str __repr__ (self)
"ParserElement" streamline (self)
List["ParserElement"] recurse (self)
None validate (self, validateTrace=None)
ParseResults parse_file (self, Union[str, Path, TextIO] file_or_filename, str encoding="utf-8", bool parse_all=False, *, bool parseAll=False)
__eq__ (self, other)
__hash__ (self)
bool matches (self, str test_string, bool parse_all=True, *, bool parseAll=True)
Tuple[bool, List[Tuple[str, Union[ParseResults, Exception]]]] run_tests (self, Union[str, List[str]] tests, bool parse_all=True, typing.Optional[Union["ParserElement", str]] comment="#", bool full_dump=True, bool print_results=True, bool failure_tests=False, typing.Optional[Callable[[str, ParseResults], str]] post_parse=None, typing.Optional[TextIO] file=None, bool with_line_numbers=False, *, bool parseAll=True, bool fullDump=True, bool printResults=True, bool failureTests=False, typing.Optional[Callable[[str, ParseResults], str]] postParse=None)
None create_diagram (self, Union[TextIO, Path, str] output_html, int vertical=3, bool show_results_names=False, bool show_groups=False, bool embed=False, **kwargs)
setResultsName (self)
setBreak (self)
setParseAction (self)
addParseAction (self)
addCondition (self)
setFailAction (self)
tryParse (self)
parseString (self)
scanString (self)
transformString (self)
searchString (self)
ignoreWhitespace (self)
leaveWhitespace (self)
setWhitespaceChars (self)
parseWithTabs (self)
setDebugActions (self)
setDebug (self)
setName (self)
parseFile (self)
runTests (self)
Public Attributes
wordChars = set(wordChars)
Public Attributes inherited from pip._vendor.pyparsing.core.ParserElement
List[ParseAction] parseAction = list()
typing.Optional[ParseFailAction] failAction = None
str customName = None
str resultsName = None
saveAsList = savelist
bool skipWhitespace = True
whiteChars = set(ParserElement.DEFAULT_WHITE_CHARS)
bool copyDefaultWhiteChars = True
bool mayReturnEmpty = False
bool keepTabs = False
List[] ignoreExprs = list()
bool debug = False
bool streamlined = False
bool mayIndexError = True
str errmsg = ""
bool modalResults = True
debugActions = self.DebugActions(None, None, None)
bool callPreparse = True
bool callDuringTry = False
list suppress_warnings_ = []
Additional Inherited Members
Static Public Member Functions inherited from pip._vendor.pyparsing.core.ParserElement
None set_default_whitespace_chars (str chars)
None inline_literals_using (type cls)
None reset_cache ()
None disable_memoization ()
None enable_left_recursion (typing.Optional[int] cache_size_limit=None, *, force=False)
None enable_packrat (int cache_size_limit=128, *, bool force=False)
inlineLiteralsUsing ()
setDefaultWhitespaceChars ()
enableLeftRecursion ()
enablePackrat ()
Static Public Attributes inherited from pip._vendor.pyparsing.core.ParserElement
str DEFAULT_WHITE_CHARS = " \n\t\r"
bool verbose_stacktrace = False
recursion_lock = RLock()
dict recursion_memos = {}
tuple packrat_cache
packrat_cache_lock = RLock()
list packrat_cache_stats = [0, 0]
bool canParseNext = can_parse_next
None resetCache = reset_cache
str defaultName = default_name
Protected Member Functions inherited from pip._vendor.pyparsing.core.Token
str _generateDefaultName (self)
Protected Member Functions inherited from pip._vendor.pyparsing.core.ParserElement
_setResultsName (self, name, listAllMatches=False)
int _skipIgnorables (self, str instring, int loc)
Tuple[int, ParseResults] _parseNoCache (self, instring, loc, doActions=True, callPreParse=True)
Tuple[int, ParseResults] _parseCache (self, instring, loc, doActions=True, callPreParse=True)
_checkRecursion (self, parseElementList)
Protected Attributes inherited from pip._vendor.pyparsing.core.ParserElement
typing.Optional[str] _defaultName = None
Static Protected Attributes inherited from pip._vendor.pyparsing.core.ParserElement
type _literalStringClass = None
Tuple[int, ParseResults] _parse = _parseNoCache
bool _packratEnabled = False
bool _left_recursion_enabled = False
Detailed Description
Matches if the current position is at the end of a :class:`Word`,
and is not followed by any character in a given set of ``word_chars``
(default= ``printables``). To emulate the ``\b`` behavior of
regular expressions, use ``WordEnd(alphanums)``. ``WordEnd``
will also match at the end of the string being parsed, or at the end
of a line.
Definition at line 3701 of file core.py.
Constructor & Destructor Documentation
__init__()
pip._vendor.pyparsing.core.WordEnd.__init__ (self, str word_chars = printables, * , str wordChars = printables)
Definition at line 3710 of file core.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
parseImpl()
pip._vendor.pyparsing.core.WordEnd.parseImpl (self, instring, loc, doActions = True)
Reimplemented from pip._vendor.pyparsing.core.ParserElement.
Definition at line 3717 of file core.py.
Referenced by pyparsing.core.ParserElement.set_fail_action().
Member Data Documentation
wordChars
pip._vendor.pyparsing.core.WordEnd.wordChars = set(wordChars)
Definition at line 3713 of file core.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pip/_vendor/pyparsing/core.py