Code Cloning Analysis: joblib._memmapping_reducer Namespace Reference
joblib._memmapping_reducer Namespace Reference
Classes
class _WeakArrayKeyMap
class ArrayMemmapForwardReducer
class TemporaryResourcesManager
Functions
_log_and_unlink (filename)
add_maybe_unlink_finalizer (memmap)
unlink_file (filename)
_get_backing_memmap (a)
_get_temp_dir (pool_folder_name, temp_folder=None)
has_shareable_memory (a)
_strided_from_memmap (filename, dtype, mode, offset, order, shape, strides, total_buffer_len, unlink_on_gc_collect)
_reduce_memmap_backed (a, m)
reduce_array_memmap_backward (a)
get_memmapping_reducers (forward_reducers=None, backward_reducers=None, temp_folder_resolver=None, max_nbytes=1e6, mmap_mode="r", verbose=0, prewarm=False, unlink_on_gc_collect=True, **kwargs)
Variables
WindowsError = type(None)
np = None
str SYSTEM_SHARED_MEM_FS = "/dev/shm"
SYSTEM_SHARED_MEM_FS_MIN_SIZE = int(2e9)
FOLDER_PERMISSIONS = stat.S_IRUSR | stat.S_IWUSR | stat.S_IXUSR
FILE_PERMISSIONS = stat.S_IRUSR | stat.S_IWUSR
JOBLIB_MMAPS = set()
Detailed Description
Reducer using memory mapping for numpy arrays
Function Documentation
_get_backing_memmap()
joblib._memmapping_reducer._get_backing_memmap (a) protected
Recursively look up the original np.memmap instance base if any.
Definition at line 160 of file _memmapping_reducer.py.
References _get_backing_memmap().
Referenced by _get_backing_memmap(), has_shareable_memory(), and reduce_array_memmap_backward().
_get_temp_dir()
joblib._memmapping_reducer._get_temp_dir (pool_folder_name, temp_folder = None) protected
Get the full path to a subfolder inside the temporary folder.
Parameters
----------
pool_folder_name : str
    Sub-folder name used for the serialization of a pool instance.
temp_folder: str, optional
    Folder to be used by the pool for memmapping large arrays
    for sharing memory with worker processes. If None, this will try in
    order:
    - a folder pointed by the JOBLIB_TEMP_FOLDER environment
      variable,
    - /dev/shm if the folder exists and is writable: this is a
      RAMdisk filesystem available by default on modern Linux
      distributions,
    - the default system temporary folder that can be
      overridden with TMP, TMPDIR or TEMP environment
      variables, typically /tmp under Unix operating systems.
Returns
-------
pool_folder : str
   full path to the temporary folder
use_shared_mem : bool
   whether the temporary folder is written to the system shared memory
   folder or some other temporary folder.
Definition at line 177 of file _memmapping_reducer.py.
_log_and_unlink()
joblib._memmapping_reducer._log_and_unlink (filename) protected
Definition at line 59 of file _memmapping_reducer.py.
_reduce_memmap_backed()
joblib._memmapping_reducer._reduce_memmap_backed (a, m) protected
Pickling reduction for memmap backed arrays.
a is expected to be an instance of np.ndarray (or np.memmap)
m is expected to be an instance of np.memmap on the top of the ``base``
attribute ancestry of a. ``m.base`` should be the real python mmap object.
Definition at line 283 of file _memmapping_reducer.py.
Referenced by reduce_array_memmap_backward().
_strided_from_memmap()
joblib._memmapping_reducer._strided_from_memmap (filename, dtype, mode, offset, order, shape, strides, total_buffer_len, unlink_on_gc_collect) protected
Reconstruct an array view on a memory mapped file.
Definition at line 241 of file _memmapping_reducer.py.
add_maybe_unlink_finalizer()
joblib._memmapping_reducer.add_maybe_unlink_finalizer (memmap)
Definition at line 71 of file _memmapping_reducer.py.
get_memmapping_reducers()
joblib._memmapping_reducer.get_memmapping_reducers (forward_reducers = None, backward_reducers = None, temp_folder_resolver = None, max_nbytes = 1e6, mmap_mode = "r", verbose = 0, prewarm = False, unlink_on_gc_collect = True, ** kwargs)
Construct a pair of memmapping reducer linked to a tmpdir.
This function manage the creation and the clean up of the temporary folders
underlying the memory maps and should be use to get the reducers necessary
to construct joblib pool or executor.
Definition at line 531 of file _memmapping_reducer.py.
has_shareable_memory()
joblib._memmapping_reducer.has_shareable_memory (a)
Return True if a is backed by some mmap buffer directly or not.
Definition at line 236 of file _memmapping_reducer.py.
References _get_backing_memmap().
reduce_array_memmap_backward()
joblib._memmapping_reducer.reduce_array_memmap_backward (a)
reduce a np.array or a np.memmap from a child process
Definition at line 343 of file _memmapping_reducer.py.
References _get_backing_memmap(), and _reduce_memmap_backed().
unlink_file()
joblib._memmapping_reducer.unlink_file (filename)
Wrapper around os.unlink with a retry mechanism.
The retry mechanism has been implemented primarily to overcome a race
condition happening during the finalizer of a np.memmap: when a process
holding the last reference to a mmap-backed np.memmap/np.array is about to
delete this array (and close the reference), it sends a maybe_unlink
request to the resource_tracker. This request can be processed faster than
it takes for the last reference of the memmap to be closed, yielding (on
Windows) a PermissionError in the resource_tracker loop.
Definition at line 80 of file _memmapping_reducer.py.
Variable Documentation
FILE_PERMISSIONS
joblib._memmapping_reducer.FILE_PERMISSIONS = stat.S_IRUSR | stat.S_IWUSR
Definition at line 50 of file _memmapping_reducer.py.
FOLDER_PERMISSIONS
joblib._memmapping_reducer.FOLDER_PERMISSIONS = stat.S_IRUSR | stat.S_IWUSR | stat.S_IXUSR
Definition at line 49 of file _memmapping_reducer.py.
JOBLIB_MMAPS
joblib._memmapping_reducer.JOBLIB_MMAPS = set()
Definition at line 56 of file _memmapping_reducer.py.
np
joblib._memmapping_reducer.np = None
Definition at line 31 of file _memmapping_reducer.py.
SYSTEM_SHARED_MEM_FS
str joblib._memmapping_reducer.SYSTEM_SHARED_MEM_FS = "/dev/shm"
Definition at line 40 of file _memmapping_reducer.py.
SYSTEM_SHARED_MEM_FS_MIN_SIZE
joblib._memmapping_reducer.SYSTEM_SHARED_MEM_FS_MIN_SIZE = int(2e9)
Definition at line 44 of file _memmapping_reducer.py.
WindowsError
joblib._memmapping_reducer.WindowsError = type(None)
Definition at line 25 of file _memmapping_reducer.py.