Code Cloning Analysis: pandas.tests.internals.test_internals Namespace Reference
pandas.tests.internals.test_internals Namespace Reference
Classes
class TestBlock
class TestBlockManager
class TestBlockPlacement
class TestCanHoldElement
class TestIndexing
class TestShouldStore
Functions
block_maker (request)
mgr ()
assert_block_equal (left, right)
get_numeric_mat (shape)
create_block (typestr, placement, item_shape=None, num_offset=0, maker=new_block)
create_single_mgr (typestr, num_rows=None)
create_mgr (descr, item_shape=None)
fblock ()
_as_array (mgr)
test_validate_ndim ()
test_block_shape ()
test_make_block_no_pandas_array (block_maker)
Variables
pytestmark = td.skip_array_manager_invalid_test
int N = 10
Function Documentation
_as_array()
pandas.tests.internals.test_internals._as_array (mgr) protected
Definition at line 891 of file test_internals.py.
assert_block_equal()
pandas.tests.internals.test_internals.assert_block_equal (left, right)
Definition at line 69 of file test_internals.py.
block_maker()
pandas.tests.internals.test_internals.block_maker (request)
Fixture to test both the internal new_block and pseudo-public make_block.
Definition at line 53 of file test_internals.py.
References create_mgr().
create_block()
pandas.tests.internals.test_internals.create_block (typestr, placement, item_shape = None, num_offset = 0, maker = new_block)
Supported typestr:
    * float, f8, f4, f2
    * int, i8, i4, i2, i1
    * uint, u8, u4, u2, u1
    * complex, c16, c8
    * bool
    * object, string, O
    * datetime, dt, M8[ns], M8[ns, tz]
    * timedelta, td, m8[ns]
    * sparse (SparseArray with fill_value=0.0)
    * sparse_na (SparseArray with fill_value=np.nan)
    * category, category2
Definition at line 87 of file test_internals.py.
References create_block().
Referenced by create_block(), create_mgr(), and pandas.tests.internals.test_internals.TestCanHoldElement.element().
create_mgr()
pandas.tests.internals.test_internals.create_mgr (descr, item_shape = None)
Construct BlockManager from string description.
String description syntax looks similar to np.matrix initializer.  It looks
like this::
    a,b,c: f8; d,e,f: i8
Rules are rather simple:
* see list of supported datatypes in `create_block` method
* components are semicolon-separated
* each component is `NAME,NAME,NAME: DTYPE_ID`
* whitespace around colons & semicolons are removed
* components with same DTYPE_ID are combined into single block
* to force multiple blocks with same dtype, use '-SUFFIX'::
    'a:f8-1; b:f8-2; c:f8-foobar'
Definition at line 186 of file test_internals.py.
References create_block().
Referenced by block_maker().
create_single_mgr()
pandas.tests.internals.test_internals.create_single_mgr (typestr, num_rows = None)
Definition at line 176 of file test_internals.py.
fblock()
pandas.tests.internals.test_internals.fblock ()
Definition at line 250 of file test_internals.py.
get_numeric_mat()
pandas.tests.internals.test_internals.get_numeric_mat (shape)
Definition at line 77 of file test_internals.py.
mgr()
pandas.tests.internals.test_internals.mgr ()
Definition at line 61 of file test_internals.py.
test_block_shape()
pandas.tests.internals.test_internals.test_block_shape ()
Definition at line 1391 of file test_internals.py.
test_make_block_no_pandas_array()
pandas.tests.internals.test_internals.test_make_block_no_pandas_array (block_maker)
Definition at line 1399 of file test_internals.py.
test_validate_ndim()
pandas.tests.internals.test_internals.test_validate_ndim ()
Definition at line 1382 of file test_internals.py.
Variable Documentation
N
int pandas.tests.internals.test_internals.N = 10
Definition at line 84 of file test_internals.py.
pytestmark
pandas.tests.internals.test_internals.pytestmark = td.skip_array_manager_invalid_test
Definition at line 49 of file test_internals.py.