Code Cloning Analysis: axes_grid1.inset_locator Namespace Reference
axes_grid1.inset_locator Namespace Reference
Classes
class _TransformedBboxWithCallback
class AnchoredLocatorBase
class AnchoredSizeLocator
class AnchoredZoomLocator
class BboxConnector
class BboxConnectorPatch
class BboxPatch
Functions
_add_inset_axes (parent_axes, axes_class, axes_kwargs, axes_locator)
inset_axes (parent_axes, width, height, loc='upper right', bbox_to_anchor=None, bbox_transform=None, axes_class=None, axes_kwargs=None, borderpad=0.5)
zoomed_inset_axes (parent_axes, zoom, loc='upper right', bbox_to_anchor=None, bbox_transform=None, axes_class=None, axes_kwargs=None, borderpad=0.5)
mark_inset (parent_axes, inset_axes, loc1, loc2, **kwargs)
Detailed Description
A collection of functions and objects for creating or placing inset axes.
Function Documentation
_add_inset_axes()
axes_grid1.inset_locator._add_inset_axes (parent_axes, axes_class, axes_kwargs, axes_locator) protected
Helper function to add an inset axes and disable navigation in it.
Definition at line 240 of file inset_locator.py.
Referenced by inset_axes(), and zoomed_inset_axes().
inset_axes()
axes_grid1.inset_locator.inset_axes (parent_axes, width, height, loc = 'upper right', bbox_to_anchor = None, bbox_transform = None, axes_class = None, axes_kwargs = None, borderpad = 0.5)
Create an inset axes with a given width and height.
Both sizes used can be specified either in inches or percentage.
For example,::
    inset_axes(parent_axes, width='40%%', height='30%%', loc='lower left')
creates in inset axes in the lower left corner of *parent_axes* which spans
over 30%% in height and 40%% in width of the *parent_axes*. Since the usage
of `.inset_axes` may become slightly tricky when exceeding such standard
cases, it is recommended to read :doc:`the examples
</gallery/axes_grid1/inset_locator_demo>`.
Notes
-----
The meaning of *bbox_to_anchor* and *bbox_to_transform* is interpreted
differently from that of legend. The value of bbox_to_anchor
(or the return value of its get_points method; the default is
*parent_axes.bbox*) is transformed by the bbox_transform (the default
is Identity transform) and then interpreted as points in the pixel
coordinate (which is dpi dependent).
Thus, following three calls are identical and creates an inset axes
with respect to the *parent_axes*::
   axins = inset_axes(parent_axes, "30%%", "40%%")
   axins = inset_axes(parent_axes, "30%%", "40%%",
                      bbox_to_anchor=parent_axes.bbox)
   axins = inset_axes(parent_axes, "30%%", "40%%",
                      bbox_to_anchor=(0, 0, 1, 1),
                      bbox_transform=parent_axes.transAxes)
Parameters
----------
parent_axes : `matplotlib.axes.Axes`
    Axes to place the inset axes.
width, height : float or str
    Size of the inset axes to create. If a float is provided, it is
    the size in inches, e.g. *width=1.3*. If a string is provided, it is
    the size in relative units, e.g. *width='40%%'*. By default, i.e. if
    neither *bbox_to_anchor* nor *bbox_transform* are specified, those
    are relative to the parent_axes. Otherwise, they are to be understood
    relative to the bounding box provided via *bbox_to_anchor*.
loc : str, default: 'upper right'
    Location to place the inset axes.  Valid locations are
    'upper left', 'upper center', 'upper right',
    'center left', 'center', 'center right',
    'lower left', 'lower center', 'lower right'.
    For backward compatibility, numeric values are accepted as well.
    See the parameter *loc* of `.Legend` for details.
bbox_to_anchor : tuple or `~matplotlib.transforms.BboxBase`, optional
    Bbox that the inset axes will be anchored to. If None,
    a tuple of (0, 0, 1, 1) is used if *bbox_transform* is set
    to *parent_axes.transAxes* or *parent_axes.figure.transFigure*.
    Otherwise, *parent_axes.bbox* is used. If a tuple, can be either
    [left, bottom, width, height], or [left, bottom].
    If the kwargs *width* and/or *height* are specified in relative units,
    the 2-tuple [left, bottom] cannot be used. Note that,
    unless *bbox_transform* is set, the units of the bounding box
    are interpreted in the pixel coordinate. When using *bbox_to_anchor*
    with tuple, it almost always makes sense to also specify
    a *bbox_transform*. This might often be the axes transform
    *parent_axes.transAxes*.
bbox_transform : `~matplotlib.transforms.Transform`, optional
    Transformation for the bbox that contains the inset axes.
    If None, a `.transforms.IdentityTransform` is used. The value
    of *bbox_to_anchor* (or the return value of its get_points method)
    is transformed by the *bbox_transform* and then interpreted
    as points in the pixel coordinate (which is dpi dependent).
    You may provide *bbox_to_anchor* in some normalized coordinate,
    and give an appropriate transform (e.g., *parent_axes.transAxes*).
axes_class : `~matplotlib.axes.Axes` type, default: `.HostAxes`
    The type of the newly created inset axes.
axes_kwargs : dict, optional
    Keyword arguments to pass to the constructor of the inset axes.
    Valid arguments include:
    %(Axes:kwdoc)s
borderpad : float, default: 0.5
    Padding between inset axes and the bbox_to_anchor.
    The units are axes font size, i.e. for a default font size of 10 points
    *borderpad = 0.5* is equivalent to a padding of 5 points.
Returns
-------
inset_axes : *axes_class*
    Inset axes object created.
Definition at line 254 of file inset_locator.py.
References _add_inset_axes().
mark_inset()
axes_grid1.inset_locator.mark_inset (parent_axes, inset_axes, loc1, loc2, ** kwargs)
Draw a box to mark the location of an area represented by an inset axes.
This function draws a box in *parent_axes* at the bounding box of
*inset_axes*, and shows a connection with the inset axes by drawing lines
at the corners, giving a "zoomed in" effect.
Parameters
----------
parent_axes : `~matplotlib.axes.Axes`
    Axes which contains the area of the inset axes.
inset_axes : `~matplotlib.axes.Axes`
    The inset axes.
loc1, loc2 : {1, 2, 3, 4}
    Corners to use for connecting the inset axes and the area in the
    parent axes.
**kwargs
    Patch properties for the lines and box drawn:
    %(Patch:kwdoc)s
Returns
-------
pp : `~matplotlib.patches.Patch`
    The patch drawn to represent the area of the inset axes.
p1, p2 : `~matplotlib.patches.Patch`
    The patches connecting two corners of the inset axes and its area.
Definition at line 471 of file inset_locator.py.
zoomed_inset_axes()
axes_grid1.inset_locator.zoomed_inset_axes (parent_axes, zoom, loc = 'upper right', bbox_to_anchor = None, bbox_transform = None, axes_class = None, axes_kwargs = None, borderpad = 0.5)
Create an anchored inset axes by scaling a parent axes. For usage, also see
:doc:`the examples </gallery/axes_grid1/inset_locator_demo2>`.
Parameters
----------
parent_axes : `~matplotlib.axes.Axes`
    Axes to place the inset axes.
zoom : float
    Scaling factor of the data axes. *zoom* > 1 will enlarge the
    coordinates (i.e., "zoomed in"), while *zoom* < 1 will shrink the
    coordinates (i.e., "zoomed out").
loc : str, default: 'upper right'
    Location to place the inset axes.  Valid locations are
    'upper left', 'upper center', 'upper right',
    'center left', 'center', 'center right',
    'lower left', 'lower center', 'lower right'.
    For backward compatibility, numeric values are accepted as well.
    See the parameter *loc* of `.Legend` for details.
bbox_to_anchor : tuple or `~matplotlib.transforms.BboxBase`, optional
    Bbox that the inset axes will be anchored to. If None,
    *parent_axes.bbox* is used. If a tuple, can be either
    [left, bottom, width, height], or [left, bottom].
    If the kwargs *width* and/or *height* are specified in relative units,
    the 2-tuple [left, bottom] cannot be used. Note that
    the units of the bounding box are determined through the transform
    in use. When using *bbox_to_anchor* it almost always makes sense to
    also specify a *bbox_transform*. This might often be the axes transform
    *parent_axes.transAxes*.
bbox_transform : `~matplotlib.transforms.Transform`, optional
    Transformation for the bbox that contains the inset axes.
    If None, a `.transforms.IdentityTransform` is used (i.e. pixel
    coordinates). This is useful when not providing any argument to
    *bbox_to_anchor*. When using *bbox_to_anchor* it almost always makes
    sense to also specify a *bbox_transform*. This might often be the
    axes transform *parent_axes.transAxes*. Inversely, when specifying
    the axes- or figure-transform here, be aware that not specifying
    *bbox_to_anchor* will use *parent_axes.bbox*, the units of which are
    in display (pixel) coordinates.
axes_class : `~matplotlib.axes.Axes` type, default: `.HostAxes`
    The type of the newly created inset axes.
axes_kwargs : dict, optional
    Keyword arguments to pass to the constructor of the inset axes.
    Valid arguments include:
    %(Axes:kwdoc)s
borderpad : float, default: 0.5
    Padding between inset axes and the bbox_to_anchor.
    The units are axes font size, i.e. for a default font size of 10 points
    *borderpad = 0.5* is equivalent to a padding of 5 points.
Returns
-------
inset_axes : *axes_class*
    Inset axes object created.
Definition at line 378 of file inset_locator.py.
References _add_inset_axes().