Code Cloning Analysis: joblib.externals.loky.backend.utils Namespace Reference
joblib.externals.loky.backend.utils Namespace Reference
Functions
kill_process_tree (process, use_psutil=True)
recursive_terminate (process, use_psutil=True)
_kill_process_tree_with_psutil (process)
_kill_process_tree_without_psutil (process)
_windows_taskkill_process_tree (pid)
_kill (pid)
_posix_recursive_kill (pid)
get_exitcodes_terminated_worker (processes)
_format_exitcodes (exitcodes)
_get_exitcode_name (exitcode)
Variables
psutil = None
Function Documentation
_format_exitcodes()
joblib.externals.loky.backend.utils._format_exitcodes (exitcodes) protected
Format a list of exit code with names of the signals if possible
Definition at line 155 of file utils.py.
Referenced by get_exitcodes_terminated_worker().
_get_exitcode_name()
joblib.externals.loky.backend.utils._get_exitcode_name (exitcode) protected
Definition at line 163 of file utils.py.
_kill()
joblib.externals.loky.backend.utils._kill (pid) protected
Definition at line 92 of file utils.py.
_kill_process_tree_with_psutil()
joblib.externals.loky.backend.utils._kill_process_tree_with_psutil (process) protected
Definition at line 33 of file utils.py.
_kill_process_tree_without_psutil()
joblib.externals.loky.backend.utils._kill_process_tree_without_psutil (process) protected
Terminate a process and its descendants.
Definition at line 54 of file utils.py.
References _posix_recursive_kill().
Referenced by kill_process_tree().
_posix_recursive_kill()
joblib.externals.loky.backend.utils._posix_recursive_kill (pid) protected
Recursively kill the descendants of a process before killing it.
Definition at line 108 of file utils.py.
References _posix_recursive_kill().
Referenced by _kill_process_tree_without_psutil(), and _posix_recursive_kill().
_windows_taskkill_process_tree()
joblib.externals.loky.backend.utils._windows_taskkill_process_tree (pid) protected
Definition at line 77 of file utils.py.
get_exitcodes_terminated_worker()
joblib.externals.loky.backend.utils.get_exitcodes_terminated_worker (processes)
Return a formatted string with the exitcodes of terminated workers.
If necessary, wait (up to .25s) for the system to correctly set the
exitcode of one terminated worker.
Definition at line 129 of file utils.py.
References _format_exitcodes().
kill_process_tree()
joblib.externals.loky.backend.utils.kill_process_tree (process, use_psutil = True)
Terminate process and its descendants with SIGKILL
Definition at line 16 of file utils.py.
References _kill_process_tree_without_psutil(), and kill_process_tree().
Referenced by kill_process_tree().
recursive_terminate()
joblib.externals.loky.backend.utils.recursive_terminate (process, use_psutil = True)
Definition at line 24 of file utils.py.
Variable Documentation
psutil
joblib.externals.loky.backend.utils.psutil = None
Definition at line 13 of file utils.py.