Code Cloning Analysis: sklearn.mixture.tests.test_gaussian_mixture.RandomData Class Reference
sklearn.mixture.tests.test_gaussian_mixture.RandomData Class Reference
Public Member Functions
__init__ (self, rng, n_samples=200, n_components=2, n_features=2, scale=50, dtype=np.float64)
Public Attributes
n_samples = n_samples
n_components = n_components
n_features = n_features
weights = rng.rand(n_components).astype(dtype)
means = rng.rand(n_components, n_features).astype(dtype) * scale
dict covariances
dict precisions
X
Y
Detailed Description
Definition at line 82 of file test_gaussian_mixture.py.
Constructor & Destructor Documentation
__init__()
sklearn.mixture.tests.test_gaussian_mixture.RandomData.__init__ (self, rng, n_samples = 200, n_components = 2, n_features = 2, scale = 50, dtype = np.float64)
Definition at line 83 of file test_gaussian_mixture.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params().
Member Data Documentation
covariances
dict sklearn.mixture.tests.test_gaussian_mixture.RandomData.covariances
Initial value:
=  {
            "spherical": 0.5 + rng.rand(n_components).astype(dtype),
            "diag": (0.5 + rng.rand(n_components, n_features).astype(dtype)) ** 2,
            "tied": make_spd_matrix(n_features, random_state=rng).astype(dtype),
            "full": np.array(
                [
                    make_spd_matrix(n_features, random_state=rng).astype(dtype) * 0.5
                    for _ in range(n_components)
                ]
            ),
        }
Definition at line 99 of file test_gaussian_mixture.py.
means
sklearn.mixture.tests.test_gaussian_mixture.RandomData.means = rng.rand(n_components, n_features).astype(dtype) * scale
Definition at line 98 of file test_gaussian_mixture.py.
n_components
sklearn.mixture.tests.test_gaussian_mixture.RandomData.n_components = n_components
Definition at line 93 of file test_gaussian_mixture.py.
Referenced by sklearn.neighbors._nca.NeighborhoodComponentsAnalysis._initialize(), sklearn.neighbors._nca.NeighborhoodComponentsAnalysis.fit(), sklearn.neural_network._rbm.BernoulliRBM.fit(), sklearn.random_projection.BaseRandomProjection.fit(), and sklearn.neural_network._rbm.BernoulliRBM.partial_fit().
n_features
sklearn.mixture.tests.test_gaussian_mixture.RandomData.n_features = n_features
Definition at line 94 of file test_gaussian_mixture.py.
n_samples
sklearn.mixture.tests.test_gaussian_mixture.RandomData.n_samples = n_samples
Definition at line 92 of file test_gaussian_mixture.py.
precisions
dict sklearn.mixture.tests.test_gaussian_mixture.RandomData.precisions
Initial value:
=  {
            "spherical": 1.0 / self.covariances["spherical"],
            "diag": 1.0 / self.covariances["diag"],
            "tied": linalg.inv(self.covariances["tied"]),
            "full": np.array(
                [linalg.inv(covariance) for covariance in self.covariances["full"]]
            ),
        }
Definition at line 110 of file test_gaussian_mixture.py.
weights
sklearn.mixture.tests.test_gaussian_mixture.RandomData.weights = rng.rand(n_components).astype(dtype)
Definition at line 96 of file test_gaussian_mixture.py.
Referenced by scipy.stats._kde.gaussian_kde._compute_covariance(), scipy.stats._kde.gaussian_kde.evaluate(), scipy.stats._kde.gaussian_kde.integrate_box(), scipy.stats._kde.gaussian_kde.integrate_box_1d(), scipy.stats._kde.gaussian_kde.integrate_gaussian(), scipy.stats._kde.gaussian_kde.logpdf(), scipy.stats._kde.gaussian_kde.marginal(), sklearn.neighbors._classification.KNeighborsClassifier.predict(), sklearn.neighbors._regression.KNeighborsRegressor.predict(), sklearn.neighbors._regression.RadiusNeighborsRegressor.predict(), sklearn.neighbors._classification.KNeighborsClassifier.predict_proba(), sklearn.neighbors._classification.RadiusNeighborsClassifier.predict_proba(), and scipy.stats._kde.gaussian_kde.resample().
X
sklearn.mixture.tests.test_gaussian_mixture.RandomData.X
Initial value:
=  dict(
            zip(
                COVARIANCE_TYPE,
                [
                    generate_data(
                        n_samples,
                        n_features,
                        self.weights,
                        self.means,
                        self.covariances,
                        covar_type,
                        dtype=dtype,
                    )
                    for covar_type in COVARIANCE_TYPE
                ],
            )
        )
Definition at line 119 of file test_gaussian_mixture.py.
Y
sklearn.mixture.tests.test_gaussian_mixture.RandomData.Y
Initial value:
=  np.hstack(
            [
                np.full(int(np.round(w * n_samples)), k, dtype=int)
                for k, w in enumerate(self.weights)
            ]
        )
Definition at line 136 of file test_gaussian_mixture.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/sklearn/mixture/tests/test_gaussian_mixture.py