Code Cloning Analysis: sklearn.metrics.cluster.tests.test_unsupervised Namespace Reference
sklearn.metrics.cluster.tests.test_unsupervised Namespace Reference
Functions
test_silhouette (sparse_container, sample_size)
test_cluster_size_1 ()
test_silhouette_paper_example ()
test_correct_labelsize ()
test_non_encoded_labels ()
test_non_numpy_labels ()
test_silhouette_nonzero_diag (dtype)
test_silhouette_samples_precomputed_sparse (sparse_container)
test_silhouette_samples_euclidean_sparse (sparse_container)
test_silhouette_reduce (sparse_container)
assert_raises_on_only_one_label (func)
assert_raises_on_all_points_same_cluster (func)
test_calinski_harabasz_score ()
test_davies_bouldin_score ()
test_silhouette_score_integer_precomputed ()
Function Documentation
assert_raises_on_all_points_same_cluster()
sklearn.metrics.cluster.tests.test_unsupervised.assert_raises_on_all_points_same_cluster (func)
Assert message when all point are in different clusters
Definition at line 335 of file test_unsupervised.py.
References assert_raises_on_all_points_same_cluster(), and assert_raises_on_only_one_label().
Referenced by assert_raises_on_all_points_same_cluster().
assert_raises_on_only_one_label()
sklearn.metrics.cluster.tests.test_unsupervised.assert_raises_on_only_one_label (func)
Assert message when there is only one label
Definition at line 328 of file test_unsupervised.py.
Referenced by assert_raises_on_all_points_same_cluster().
test_calinski_harabasz_score()
sklearn.metrics.cluster.tests.test_unsupervised.test_calinski_harabasz_score ()
Definition at line 342 of file test_unsupervised.py.
test_cluster_size_1()
sklearn.metrics.cluster.tests.test_unsupervised.test_cluster_size_1 ()
Definition at line 52 of file test_unsupervised.py.
test_correct_labelsize()
sklearn.metrics.cluster.tests.test_unsupervised.test_correct_labelsize ()
Definition at line 217 of file test_unsupervised.py.
test_davies_bouldin_score()
sklearn.metrics.cluster.tests.test_unsupervised.test_davies_bouldin_score ()
Definition at line 364 of file test_unsupervised.py.
test_non_encoded_labels()
sklearn.metrics.cluster.tests.test_unsupervised.test_non_encoded_labels ()
Definition at line 241 of file test_unsupervised.py.
test_non_numpy_labels()
sklearn.metrics.cluster.tests.test_unsupervised.test_non_numpy_labels ()
Definition at line 251 of file test_unsupervised.py.
test_silhouette()
sklearn.metrics.cluster.tests.test_unsupervised.test_silhouette (sparse_container, sample_size)
Definition at line 31 of file test_unsupervised.py.
test_silhouette_nonzero_diag()
sklearn.metrics.cluster.tests.test_unsupervised.test_silhouette_nonzero_diag (dtype)
Definition at line 259 of file test_unsupervised.py.
test_silhouette_paper_example()
sklearn.metrics.cluster.tests.test_unsupervised.test_silhouette_paper_example ()
Definition at line 75 of file test_unsupervised.py.
test_silhouette_reduce()
sklearn.metrics.cluster.tests.test_unsupervised.test_silhouette_reduce (sparse_container)
Check for non-CSR input to private method `_silhouette_reduce`.
Definition at line 314 of file test_unsupervised.py.
test_silhouette_samples_euclidean_sparse()
sklearn.metrics.cluster.tests.test_unsupervised.test_silhouette_samples_euclidean_sparse (sparse_container)
Check that silhouette_samples works for sparse matrices correctly.
Definition at line 299 of file test_unsupervised.py.
test_silhouette_samples_precomputed_sparse()
sklearn.metrics.cluster.tests.test_unsupervised.test_silhouette_samples_precomputed_sparse (sparse_container)
Check that silhouette_samples works for sparse matrices correctly.
Definition at line 283 of file test_unsupervised.py.
test_silhouette_score_integer_precomputed()
sklearn.metrics.cluster.tests.test_unsupervised.test_silhouette_score_integer_precomputed ()
Check that silhouette_score works for precomputed metrics that are integers.
Non-regression test for #22107.
Definition at line 399 of file test_unsupervised.py.