Code Cloning Analysis: fontTools.ufoLib.validators Namespace Reference
fontTools.ufoLib.validators Namespace Reference
Functions
isDictEnough (value)
genericTypeValidator (value, typ)
genericIntListValidator (values, validValues)
genericNonNegativeIntValidator (value)
genericNonNegativeNumberValidator (value)
genericDictValidator (value, prototype)
fontInfoStyleMapStyleNameValidator (value)
fontInfoOpenTypeGaspRangeRecordsValidator (value)
fontInfoOpenTypeHeadCreatedValidator (value)
fontInfoOpenTypeNameRecordsValidator (value)
fontInfoOpenTypeOS2WeightClassValidator (value)
fontInfoOpenTypeOS2WidthClassValidator (value)
fontInfoVersion2OpenTypeOS2PanoseValidator (values)
fontInfoVersion3OpenTypeOS2PanoseValidator (values)
fontInfoOpenTypeOS2FamilyClassValidator (values)
fontInfoPostscriptBluesValidator (values)
fontInfoPostscriptOtherBluesValidator (values)
fontInfoPostscriptStemsValidator (values)
fontInfoPostscriptWindowsCharacterSetValidator (value)
fontInfoWOFFMetadataUniqueIDValidator (value)
fontInfoWOFFMetadataVendorValidator (value)
fontInfoWOFFMetadataCreditsValidator (value)
fontInfoWOFFMetadataDescriptionValidator (value)
fontInfoWOFFMetadataLicenseValidator (value)
fontInfoWOFFMetadataTrademarkValidator (value)
fontInfoWOFFMetadataCopyrightValidator (value)
fontInfoWOFFMetadataLicenseeValidator (value)
fontInfoWOFFMetadataTextValue (value)
fontInfoWOFFMetadataExtensionsValidator (value)
fontInfoWOFFMetadataExtensionValidator (value)
fontInfoWOFFMetadataExtensionItemValidator (value)
fontInfoWOFFMetadataExtensionNameValidator (value)
fontInfoWOFFMetadataExtensionValueValidator (value)
guidelinesValidator (value, identifiers=None)
guidelineValidator (value)
anchorsValidator (value, identifiers=None)
anchorValidator (value)
identifierValidator (value)
colorValidator (value)
imageValidator (value)
pngValidator (path=None, data=None, fileObj=None)
layerContentsValidator (value, ufoPathOrFileSystem)
groupsValidator (value)
kerningValidator (data)
fontLibValidator (value)
glyphLibValidator (value)
Variables
_guidelineDictPrototype
_anchorDictPrototype
str pngSignature = b"\x89PNG\r\n\x1a\n"
_imageDictPrototype
str _bogusLibFormatMessage = "The lib data is not in the correct format: %s"
Detailed Description
Various low level data validators.
Function Documentation
anchorsValidator()
fontTools.ufoLib.validators.anchorsValidator (value, identifiers = None)
Version 3+.
Definition at line 642 of file validators.py.
References anchorValidator().
Referenced by fontTools.ufoLib.glifLib.validateLayerInfoVersion3Data(), and fontTools.ufoLib.glifLib.writeGlyphToString().
anchorValidator()
fontTools.ufoLib.validators.anchorValidator (value)
Version 3+.
Definition at line 670 of file validators.py.
References colorValidator(), genericDictValidator(), and identifierValidator().
Referenced by anchorsValidator().
colorValidator()
fontTools.ufoLib.validators.colorValidator (value)
Version 3+.
>>> colorValidator("0,0,0,0")
True
>>> colorValidator(".5,.5,.5,.5")
True
>>> colorValidator("0.5,0.5,0.5,0.5")
True
>>> colorValidator("1,1,1,1")
True
>>> colorValidator("2,0,0,0")
False
>>> colorValidator("0,2,0,0")
False
>>> colorValidator("0,0,2,0")
False
>>> colorValidator("0,0,0,2")
False
>>> colorValidator("1r,1,1,1")
False
>>> colorValidator("1,1g,1,1")
False
>>> colorValidator("1,1,1b,1")
False
>>> colorValidator("1,1,1,1a")
False
>>> colorValidator("1 1 1 1")
False
>>> colorValidator("1 1,1,1")
False
>>> colorValidator("1,1 1,1")
False
>>> colorValidator("1,1,1 1")
False
>>> colorValidator("1, 1, 1, 1")
True
Definition at line 728 of file validators.py.
Referenced by anchorValidator(), glyphLibValidator(), guidelineValidator(), and imageValidator().
fontInfoOpenTypeGaspRangeRecordsValidator()
fontTools.ufoLib.validators.fontInfoOpenTypeGaspRangeRecordsValidator (value)
Version 3+.
Definition at line 115 of file validators.py.
References genericDictValidator(), genericIntListValidator(), and genericNonNegativeIntValidator().
fontInfoOpenTypeHeadCreatedValidator()
fontTools.ufoLib.validators.fontInfoOpenTypeHeadCreatedValidator (value)
Version 2+.
Definition at line 143 of file validators.py.
fontInfoOpenTypeNameRecordsValidator()
fontTools.ufoLib.validators.fontInfoOpenTypeNameRecordsValidator (value)
Version 3+.
Definition at line 203 of file validators.py.
References genericDictValidator().
fontInfoOpenTypeOS2FamilyClassValidator()
fontTools.ufoLib.validators.fontInfoOpenTypeOS2FamilyClassValidator (values)
Version 2+.
Definition at line 278 of file validators.py.
fontInfoOpenTypeOS2WeightClassValidator()
fontTools.ufoLib.validators.fontInfoOpenTypeOS2WeightClassValidator (value)
Version 2+.
Definition at line 222 of file validators.py.
fontInfoOpenTypeOS2WidthClassValidator()
fontTools.ufoLib.validators.fontInfoOpenTypeOS2WidthClassValidator (value)
Version 2+.
Definition at line 233 of file validators.py.
fontInfoPostscriptBluesValidator()
fontTools.ufoLib.validators.fontInfoPostscriptBluesValidator (values)
Version 2+.
Definition at line 297 of file validators.py.
fontInfoPostscriptOtherBluesValidator()
fontTools.ufoLib.validators.fontInfoPostscriptOtherBluesValidator (values)
Version 2+.
Definition at line 313 of file validators.py.
fontInfoPostscriptStemsValidator()
fontTools.ufoLib.validators.fontInfoPostscriptStemsValidator (values)
Version 2+.
Definition at line 329 of file validators.py.
fontInfoPostscriptWindowsCharacterSetValidator()
fontTools.ufoLib.validators.fontInfoPostscriptWindowsCharacterSetValidator (value)
Version 2+.
Definition at line 343 of file validators.py.
fontInfoStyleMapStyleNameValidator()
fontTools.ufoLib.validators.fontInfoStyleMapStyleNameValidator (value)
Version 2+.
Definition at line 107 of file validators.py.
fontInfoVersion2OpenTypeOS2PanoseValidator()
fontTools.ufoLib.validators.fontInfoVersion2OpenTypeOS2PanoseValidator (values)
Version 2.
Definition at line 246 of file validators.py.
fontInfoVersion3OpenTypeOS2PanoseValidator()
fontTools.ufoLib.validators.fontInfoVersion3OpenTypeOS2PanoseValidator (values)
Version 3+.
Definition at line 261 of file validators.py.
fontInfoWOFFMetadataCopyrightValidator()
fontTools.ufoLib.validators.fontInfoWOFFMetadataCopyrightValidator (value)
Version 3+.
Definition at line 444 of file validators.py.
References fontInfoWOFFMetadataTextValue(), and genericDictValidator().
fontInfoWOFFMetadataCreditsValidator()
fontTools.ufoLib.validators.fontInfoWOFFMetadataCreditsValidator (value)
Version 3+.
Definition at line 380 of file validators.py.
References genericDictValidator().
fontInfoWOFFMetadataDescriptionValidator()
fontTools.ufoLib.validators.fontInfoWOFFMetadataDescriptionValidator (value)
Version 3+.
Definition at line 404 of file validators.py.
References fontInfoWOFFMetadataTextValue(), and genericDictValidator().
fontInfoWOFFMetadataExtensionItemValidator()
fontTools.ufoLib.validators.fontInfoWOFFMetadataExtensionItemValidator (value)
Version 3+.
Definition at line 517 of file validators.py.
References fontInfoWOFFMetadataExtensionNameValidator(), fontInfoWOFFMetadataExtensionValueValidator(), and genericDictValidator().
Referenced by fontInfoWOFFMetadataExtensionValidator().
fontInfoWOFFMetadataExtensionNameValidator()
fontTools.ufoLib.validators.fontInfoWOFFMetadataExtensionNameValidator (value)
Version 3+.
Definition at line 533 of file validators.py.
References genericDictValidator().
Referenced by fontInfoWOFFMetadataExtensionItemValidator(), and fontInfoWOFFMetadataExtensionValidator().
fontInfoWOFFMetadataExtensionsValidator()
fontTools.ufoLib.validators.fontInfoWOFFMetadataExtensionsValidator (value)
Version 3+.
Definition at line 486 of file validators.py.
References fontInfoWOFFMetadataExtensionValidator().
fontInfoWOFFMetadataExtensionValidator()
fontTools.ufoLib.validators.fontInfoWOFFMetadataExtensionValidator (value)
Version 3+.
Definition at line 500 of file validators.py.
References fontInfoWOFFMetadataExtensionItemValidator(), fontInfoWOFFMetadataExtensionNameValidator(), and genericDictValidator().
Referenced by fontInfoWOFFMetadataExtensionsValidator().
fontInfoWOFFMetadataExtensionValueValidator()
fontTools.ufoLib.validators.fontInfoWOFFMetadataExtensionValueValidator (value)
Version 3+.
Definition at line 550 of file validators.py.
References genericDictValidator().
Referenced by fontInfoWOFFMetadataExtensionItemValidator().
fontInfoWOFFMetadataLicenseeValidator()
fontTools.ufoLib.validators.fontInfoWOFFMetadataLicenseeValidator (value)
Version 3+.
Definition at line 457 of file validators.py.
References genericDictValidator().
fontInfoWOFFMetadataLicenseValidator()
fontTools.ufoLib.validators.fontInfoWOFFMetadataLicenseValidator (value)
Version 3+.
Definition at line 417 of file validators.py.
References fontInfoWOFFMetadataTextValue(), and genericDictValidator().
fontInfoWOFFMetadataTextValue()
fontTools.ufoLib.validators.fontInfoWOFFMetadataTextValue (value)
Version 3+.
Definition at line 469 of file validators.py.
References genericDictValidator().
Referenced by fontInfoWOFFMetadataCopyrightValidator(), fontInfoWOFFMetadataDescriptionValidator(), fontInfoWOFFMetadataLicenseValidator(), and fontInfoWOFFMetadataTrademarkValidator().
fontInfoWOFFMetadataTrademarkValidator()
fontTools.ufoLib.validators.fontInfoWOFFMetadataTrademarkValidator (value)
Version 3+.
Definition at line 431 of file validators.py.
References fontInfoWOFFMetadataTextValue(), and genericDictValidator().
fontInfoWOFFMetadataUniqueIDValidator()
fontTools.ufoLib.validators.fontInfoWOFFMetadataUniqueIDValidator (value)
Version 3+.
Definition at line 353 of file validators.py.
References genericDictValidator().
fontInfoWOFFMetadataVendorValidator()
fontTools.ufoLib.validators.fontInfoWOFFMetadataVendorValidator (value)
Version 3+.
Definition at line 363 of file validators.py.
References genericDictValidator().
fontLibValidator()
fontTools.ufoLib.validators.fontLibValidator (value)
Check the validity of the lib.
Version 3+ (though it's backwards compatible with UFO 1 and UFO 2).
>>> lib = {"foo" : "bar"}
>>> fontLibValidator(lib)
(True, None)
>>> lib = {"public.awesome" : "hello"}
>>> fontLibValidator(lib)
(True, None)
>>> lib = {"public.glyphOrder" : ["A", "C", "B"]}
>>> fontLibValidator(lib)
(True, None)
>>> lib = "hello"
>>> valid, msg = fontLibValidator(lib)
>>> valid
False
>>> print(msg)  # doctest: +ELLIPSIS
The lib data is not in the correct format: expected a dictionary, ...
>>> lib = {1: "hello"}
>>> valid, msg = fontLibValidator(lib)
>>> valid
False
>>> print(msg)
The lib key is not properly formatted: expected str, found int: 1
>>> lib = {"public.glyphOrder" : "hello"}
>>> valid, msg = fontLibValidator(lib)
>>> valid
False
>>> print(msg)  # doctest: +ELLIPSIS
public.glyphOrder is not properly formatted: expected list or tuple,...
>>> lib = {"public.glyphOrder" : ["A", 1, "B"]}
>>> valid, msg = fontLibValidator(lib)
>>> valid
False
>>> print(msg)  # doctest: +ELLIPSIS
public.glyphOrder is not properly formatted: expected str,...
Definition at line 1071 of file validators.py.
References isDictEnough().
Referenced by fontTools.ufoLib.UFOReader.readLib(), and fontTools.ufoLib.UFOWriter.writeLib().
genericDictValidator()
fontTools.ufoLib.validators.genericDictValidator (value, prototype)
Generic. (Added at version 3.)
Definition at line 73 of file validators.py.
Referenced by anchorValidator(), fontInfoOpenTypeGaspRangeRecordsValidator(), fontInfoOpenTypeNameRecordsValidator(), fontInfoWOFFMetadataCopyrightValidator(), fontInfoWOFFMetadataCreditsValidator(), fontInfoWOFFMetadataDescriptionValidator(), fontInfoWOFFMetadataExtensionItemValidator(), fontInfoWOFFMetadataExtensionNameValidator(), fontInfoWOFFMetadataExtensionValidator(), fontInfoWOFFMetadataExtensionValueValidator(), fontInfoWOFFMetadataLicenseeValidator(), fontInfoWOFFMetadataLicenseValidator(), fontInfoWOFFMetadataTextValue(), fontInfoWOFFMetadataTrademarkValidator(), fontInfoWOFFMetadataUniqueIDValidator(), fontInfoWOFFMetadataVendorValidator(), guidelineValidator(), and imageValidator().
genericIntListValidator()
fontTools.ufoLib.validators.genericIntListValidator (values, validValues)
Generic. (Added at version 2.)
Definition at line 35 of file validators.py.
Referenced by fontInfoOpenTypeGaspRangeRecordsValidator().
genericNonNegativeIntValidator()
fontTools.ufoLib.validators.genericNonNegativeIntValidator (value)
Generic. (Added at version 3.)
Definition at line 51 of file validators.py.
Referenced by fontInfoOpenTypeGaspRangeRecordsValidator().
genericNonNegativeNumberValidator()
fontTools.ufoLib.validators.genericNonNegativeNumberValidator (value)
Generic. (Added at version 3.)
Definition at line 62 of file validators.py.
genericTypeValidator()
fontTools.ufoLib.validators.genericTypeValidator (value, typ)
Generic. (Added at version 2.)
Definition at line 28 of file validators.py.
glyphLibValidator()
fontTools.ufoLib.validators.glyphLibValidator (value)
Check the validity of the lib.
Version 3+ (though it's backwards compatible with UFO 1 and UFO 2).
>>> lib = {"foo" : "bar"}
>>> glyphLibValidator(lib)
(True, None)
>>> lib = {"public.awesome" : "hello"}
>>> glyphLibValidator(lib)
(True, None)
>>> lib = {"public.markColor" : "1,0,0,0.5"}
>>> glyphLibValidator(lib)
(True, None)
>>> lib = {"public.markColor" : 1}
>>> valid, msg = glyphLibValidator(lib)
>>> valid
False
>>> print(msg)
public.markColor is not properly formatted.
Definition at line 1143 of file validators.py.
References colorValidator(), and isDictEnough().
Referenced by fontTools.ufoLib.glifLib.validateLayerInfoVersion3Data(), and fontTools.ufoLib.glifLib.writeGlyphToString().
groupsValidator()
fontTools.ufoLib.validators.groupsValidator (value)
Check the validity of the groups.
Version 3+ (though it's backwards compatible with UFO 1 and UFO 2).
>>> groups = {"A" : ["A", "A"], "A2" : ["A"]}
>>> groupsValidator(groups)
(True, None)
>>> groups = {"" : ["A"]}
>>> valid, msg = groupsValidator(groups)
>>> valid
False
>>> print(msg)
A group has an empty name.
>>> groups = {"public.awesome" : ["A"]}
>>> groupsValidator(groups)
(True, None)
>>> groups = {"public.kern1." : ["A"]}
>>> valid, msg = groupsValidator(groups)
>>> valid
False
>>> print(msg)
The group data contains a kerning group with an incomplete name.
>>> groups = {"public.kern2." : ["A"]}
>>> valid, msg = groupsValidator(groups)
>>> valid
False
>>> print(msg)
The group data contains a kerning group with an incomplete name.
>>> groups = {"public.kern1.A" : ["A"], "public.kern2.A" : ["A"]}
>>> groupsValidator(groups)
(True, None)
>>> groups = {"public.kern1.A1" : ["A"], "public.kern1.A2" : ["A"]}
>>> valid, msg = groupsValidator(groups)
>>> valid
False
>>> print(msg)
The glyph "A" occurs in too many kerning groups.
Definition at line 933 of file validators.py.
References isDictEnough().
Referenced by fontTools.ufoLib.UFOReader.readGroups(), and fontTools.ufoLib.UFOWriter.writeGroups().
guidelinesValidator()
fontTools.ufoLib.validators.guidelinesValidator (value, identifiers = None)
Version 3+.
Definition at line 572 of file validators.py.
References guidelineValidator().
Referenced by fontTools.ufoLib.glifLib.validateLayerInfoVersion3Data(), and fontTools.ufoLib.glifLib.writeGlyphToString().
guidelineValidator()
fontTools.ufoLib.validators.guidelineValidator (value)
Version 3+.
Definition at line 601 of file validators.py.
References colorValidator(), genericDictValidator(), and identifierValidator().
Referenced by guidelinesValidator().
identifierValidator()
fontTools.ufoLib.validators.identifierValidator (value)
Version 3+.
>>> identifierValidator("a")
True
>>> identifierValidator("")
False
>>> identifierValidator("a" * 101)
False
Definition at line 697 of file validators.py.
Referenced by fontTools.ufoLib.glifLib.GLIFPointPen.addComponent(), fontTools.ufoLib.glifLib.GLIFPointPen.addPoint(), anchorValidator(), fontTools.ufoLib.glifLib.GLIFPointPen.beginPath(), guidelineValidator(), and fontTools.ufoLib.glifLib.validateLayerInfoVersion3Data().
imageValidator()
fontTools.ufoLib.validators.imageValidator (value)
Version 3+.
Definition at line 817 of file validators.py.
References colorValidator(), and genericDictValidator().
Referenced by fontTools.ufoLib.glifLib.validateLayerInfoVersion3Data(), and fontTools.ufoLib.glifLib.writeGlyphToString().
isDictEnough()
fontTools.ufoLib.validators.isDictEnough (value)
Some objects will likely come in that aren't
dicts but are dict-ish enough.
Definition at line 15 of file validators.py.
Referenced by fontLibValidator(), glyphLibValidator(), groupsValidator(), and fontTools.ufoLib.UFOWriter.writeKerning().
kerningValidator()
fontTools.ufoLib.validators.kerningValidator (data)
Check the validity of the kerning data structure.
Version 3+ (though it's backwards compatible with UFO 1 and UFO 2).
>>> kerning = {"A" : {"B" : 100}}
>>> kerningValidator(kerning)
(True, None)
>>> kerning = {"A" : ["B"]}
>>> valid, msg = kerningValidator(kerning)
>>> valid
False
>>> print(msg)
The kerning data is not in the correct format.
>>> kerning = {"A" : {"B" : "100"}}
>>> valid, msg = kerningValidator(kerning)
>>> valid
False
>>> print(msg)
The kerning data is not in the correct format.
Definition at line 1025 of file validators.py.
Referenced by fontTools.ufoLib.UFOReader.readKerning().
layerContentsValidator()
fontTools.ufoLib.validators.layerContentsValidator (value, ufoPathOrFileSystem)
Check the validity of layercontents.plist.
Version 3+.
Definition at line 859 of file validators.py.
Referenced by fontTools.ufoLib.UFOReader._readLayerContents().
pngValidator()
fontTools.ufoLib.validators.pngValidator (path = None, data = None, fileObj = None)
Version 3+.
This checks the signature of the image data.
Definition at line 833 of file validators.py.
Referenced by fontTools.ufoLib.UFOReader.getImageDirectoryListing(), fontTools.ufoLib.UFOReader.readImage(), and fontTools.ufoLib.UFOWriter.writeImage().
Variable Documentation
_anchorDictPrototype
fontTools.ufoLib.validators._anchorDictPrototype protected
Initial value:
=  dict(
    x=((int, float), False),
    y=((int, float), False),
    name=(str, False),
    color=(str, False),
    identifier=(str, False),
)
Definition at line 661 of file validators.py.
_bogusLibFormatMessage
str fontTools.ufoLib.validators._bogusLibFormatMessage = "The lib data is not in the correct format: %s" protected
Definition at line 1068 of file validators.py.
_guidelineDictPrototype
fontTools.ufoLib.validators._guidelineDictPrototype protected
Initial value:
=  dict(
    x=((int, float), False),
    y=((int, float), False),
    angle=((int, float), False),
    name=(str, False),
    color=(str, False),
    identifier=(str, False),
)
Definition at line 591 of file validators.py.
_imageDictPrototype
fontTools.ufoLib.validators._imageDictPrototype protected
Initial value:
=  dict(
    fileName=(str, True),
    xScale=((int, float), False),
    xyScale=((int, float), False),
    yxScale=((int, float), False),
    yScale=((int, float), False),
    xOffset=((int, float), False),
    yOffset=((int, float), False),
    color=(str, False),
)
Definition at line 805 of file validators.py.
pngSignature
str fontTools.ufoLib.validators.pngSignature = b"\x89PNG\r\n\x1a\n"
Definition at line 803 of file validators.py.