Code Cloning Analysis: sklearn.datasets._species_distributions Namespace Reference
sklearn.datasets._species_distributions Namespace Reference
Functions
_load_coverage (F, header_length=6, dtype=np.int16)
_load_csv (F)
construct_grids (batch)
fetch_species_distributions (*, data_home=None, download_if_missing=True, n_retries=3, delay=1.0)
Variables
SAMPLES
COVERAGES
str DATA_ARCHIVE_NAME = "species_coverage.pkz"
logger = logging.getLogger(__name__)
Detailed Description
=============================
Species distribution dataset
=============================
This dataset represents the geographic distribution of species.
The dataset is provided by Phillips et. al. (2006).
The two species are:
 - `"Bradypus variegatus"
   <http://www.iucnredlist.org/details/3038/0>`_ ,
   the Brown-throated Sloth.
 - `"Microryzomys minutus"
   <http://www.iucnredlist.org/details/13408/0>`_ ,
   also known as the Forest Small Rice Rat, a rodent that lives in Peru,
   Colombia, Ecuador, Peru, and Venezuela.
References
----------
`"Maximum entropy modeling of species geographic distributions"
<http://rob.schapire.net/papers/ecolmod.pdf>`_ S. J. Phillips,
R. P. Anderson, R. E. Schapire - Ecological Modelling, 190:231-259, 2006.
Function Documentation
_load_coverage()
sklearn.datasets._species_distributions._load_coverage (F, header_length = 6, dtype = np.int16) protected
Load a coverage file from an open file object.
This will return a numpy array of the given dtype
Definition at line 67 of file _species_distributions.py.
Referenced by fetch_species_distributions().
_load_csv()
sklearn.datasets._species_distributions._load_csv (F) protected
Load csv file.
Parameters
----------
F : file object
    CSV file open in byte mode.
Returns
-------
rec : np.ndarray
    record array representing the data
Definition at line 83 of file _species_distributions.py.
Referenced by fetch_species_distributions().
construct_grids()
sklearn.datasets._species_distributions.construct_grids (batch)
Construct the map grid from the batch object
Parameters
----------
batch : Batch object
    The object returned by :func:`fetch_species_distributions`
Returns
-------
(xgrid, ygrid) : 1-D arrays
    The grid corresponding to the values in batch.coverages
Definition at line 103 of file _species_distributions.py.
fetch_species_distributions()
sklearn.datasets._species_distributions.fetch_species_distributions (* , data_home = None, download_if_missing = True, n_retries = 3, delay = 1.0)
Loader for species distribution dataset from Phillips et. al. (2006).
Read more in the :ref:`User Guide <species_distribution_dataset>`.
Parameters
----------
data_home : str or path-like, default=None
    Specify another download and cache folder for the datasets. By default
    all scikit-learn data is stored in '~/scikit_learn_data' subfolders.
download_if_missing : bool, default=True
    If False, raise an OSError if the data is not locally available
    instead of trying to download the data from the source site.
n_retries : int, default=3
    Number of retries when HTTP errors are encountered.
    .. versionadded:: 1.5
delay : float, default=1.0
    Number of seconds between retries.
    .. versionadded:: 1.5
Returns
-------
data : :class:`~sklearn.utils.Bunch`
    Dictionary-like object, with the following attributes.
    coverages : array, shape = [14, 1592, 1212]
        These represent the 14 features measured
        at each point of the map grid.
        The latitude/longitude values for the grid are discussed below.
        Missing data is represented by the value -9999.
    train : record array, shape = (1624,)
        The training points for the data.  Each point has three fields:
        - train['species'] is the species name
        - train['dd long'] is the longitude, in degrees
        - train['dd lat'] is the latitude, in degrees
    test : record array, shape = (620,)
        The test points for the data.  Same format as the training data.
    Nx, Ny : integers
        The number of longitudes (x) and latitudes (y) in the grid
    x_left_lower_corner, y_left_lower_corner : floats
        The (x,y) position of the lower-left corner, in degrees
    grid_size : float
        The spacing between points of the grid, in degrees
Notes
-----
This dataset represents the geographic distribution of species.
The dataset is provided by Phillips et. al. (2006).
The two species are:
- `"Bradypus variegatus"
  <http://www.iucnredlist.org/details/3038/0>`_ ,
  the Brown-throated Sloth.
- `"Microryzomys minutus"
  <http://www.iucnredlist.org/details/13408/0>`_ ,
  also known as the Forest Small Rice Rat, a rodent that lives in Peru,
  Colombia, Ecuador, Peru, and Venezuela.
References
----------
* `"Maximum entropy modeling of species geographic distributions"
  <http://rob.schapire.net/papers/ecolmod.pdf>`_
  S. J. Phillips, R. P. Anderson, R. E. Schapire - Ecological Modelling,
  190:231-259, 2006.
Examples
--------
>>> from sklearn.datasets import fetch_species_distributions
>>> species = fetch_species_distributions()
>>> species.train[:5]
array([(b'microryzomys_minutus', -64.7   , -17.85),
       (b'microryzomys_minutus', -67.8333, -16.3333),
       (b'microryzomys_minutus', -67.8833, -16.3   ),
       (b'microryzomys_minutus', -67.8   , -16.2667),
       (b'microryzomys_minutus', -67.9833, -15.9   )],
      dtype=[('species', 'S22'), ('dd long', '<f4'), ('dd lat', '<f4')])
For a more extended example,
see :ref:`sphx_glr_auto_examples_applications_plot_species_distribution_modeling.py`
Definition at line 139 of file _species_distributions.py.
References _load_coverage(), and _load_csv().
Variable Documentation
COVERAGES
sklearn.datasets._species_distributions.COVERAGES
Initial value:
=  RemoteFileMetadata(
    filename="coverages.zip",
    url="https://ndownloader.figshare.com/files/5976078",
    checksum="4d862674d72e79d6cee77e63b98651ec7926043ba7d39dcb31329cf3f6073807",
)
Definition at line 55 of file _species_distributions.py.
DATA_ARCHIVE_NAME
str sklearn.datasets._species_distributions.DATA_ARCHIVE_NAME = "species_coverage.pkz"
Definition at line 61 of file _species_distributions.py.
logger
sklearn.datasets._species_distributions.logger = logging.getLogger(__name__)
Definition at line 64 of file _species_distributions.py.
SAMPLES
sklearn.datasets._species_distributions.SAMPLES
Initial value:
=  RemoteFileMetadata(
    filename="samples.zip",
    url="https://ndownloader.figshare.com/files/5976075",
    checksum="abb07ad284ac50d9e6d20f1c4211e0fd3c098f7f85955e89d321ee8efe37ac28",
)
Definition at line 47 of file _species_distributions.py.