Code Cloning Analysis: sklearn.model_selection._split.StratifiedKFold Class Reference
sklearn.model_selection._split.StratifiedKFold Class Reference
Public Member Functions
__init__ (self, n_splits=5, *, shuffle=False, random_state=None)
split (self, X, y, groups=None)
Public Member Functions inherited from sklearn.model_selection._split._BaseKFold
__init__ (self, n_splits, *, shuffle, random_state)
get_n_splits (self, X=None, y=None, groups=None)
Public Member Functions inherited from sklearn.model_selection._split.BaseCrossValidator
__repr__ (self)
Protected Member Functions
_make_test_folds (self, X, y=None)
_iter_test_masks (self, X, y=None, groups=None)
Protected Member Functions inherited from sklearn.model_selection._split.BaseCrossValidator
_iter_test_indices (self, X=None, y=None, groups=None)
Additional Inherited Members
Public Attributes inherited from sklearn.model_selection._split._BaseKFold
n_splits = n_splits
shuffle = shuffle
random_state = random_state
Detailed Description
Class-wise stratified K-Fold cross-validator.
Provides train/test indices to split data in train/test sets.
This cross-validation object is a variation of KFold that returns
stratified folds. The folds are made by preserving the percentage of
samples for each class in `y` in a binary or multiclass classification
setting.
Read more in the :ref:`User Guide <stratified_k_fold>`.
For visualisation of cross-validation behaviour and
comparison between common scikit-learn split methods
refer to :ref:`sphx_glr_auto_examples_model_selection_plot_cv_indices.py`
.. note::
    Stratification on the class label solves an engineering problem rather
    than a statistical one. See :ref:`stratification` for more details.
Parameters
----------
n_splits : int, default=5
    Number of folds. Must be at least 2.
    .. versionchanged:: 0.22
        ``n_splits`` default value changed from 3 to 5.
shuffle : bool, default=False
    Whether to shuffle each class's samples before splitting into batches.
    Note that the samples within each split will not be shuffled.
random_state : int, RandomState instance or None, default=None
    When `shuffle` is True, `random_state` affects the ordering of the
    indices, which controls the randomness of each fold for each class.
    Otherwise, leave `random_state` as `None`.
    Pass an int for reproducible output across multiple function calls.
    See :term:`Glossary <random_state>`.
Examples
--------
>>> import numpy as np
>>> from sklearn.model_selection import StratifiedKFold
>>> X = np.array([[1, 2], [3, 4], [1, 2], [3, 4]])
>>> y = np.array([0, 0, 1, 1])
>>> skf = StratifiedKFold(n_splits=2)
>>> skf.get_n_splits(X, y)
2
>>> print(skf)
StratifiedKFold(n_splits=2, random_state=None, shuffle=False)
>>> for i, (train_index, test_index) in enumerate(skf.split(X, y)):
...     print(f"Fold {i}:")
...     print(f"  Train: index={train_index}")
...     print(f"  Test:  index={test_index}")
Fold 0:
  Train: index=[1 3]
  Test:  index=[0 2]
Fold 1:
  Train: index=[0 2]
  Test:  index=[1 3]
Notes
-----
The implementation is designed to:
* Generate test sets such that all contain the same distribution of
  classes, or as close as possible.
* Be invariant to class label: relabelling ``y = ["Happy", "Sad"]`` to
  ``y = [1, 0]`` should not change the indices generated.
* Preserve order dependencies in the dataset ordering, when
  ``shuffle=False``: all samples from class k in some test set were
  contiguous in y, or separated in y by samples from classes other than k.
* Generate test sets where the smallest and largest differ by at most one
  sample.
.. versionchanged:: 0.22
    The previous implementation did not follow the last constraint.
See Also
--------
RepeatedStratifiedKFold : Repeats Stratified K-Fold n times.
Definition at line 686 of file _split.py.
Constructor & Destructor Documentation
__init__()
sklearn.model_selection._split.StratifiedKFold.__init__ (self, n_splits = 5, * , shuffle = False, random_state = None)
Definition at line 770 of file _split.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params().
Member Function Documentation
_iter_test_masks()
sklearn.model_selection._split.StratifiedKFold._iter_test_masks (self, X, y = None, groups = None) protected
Generates boolean masks corresponding to test sets.
By default, delegates to _iter_test_indices(X, y, groups)
Reimplemented from sklearn.model_selection._split.BaseCrossValidator.
Definition at line 843 of file _split.py.
References _make_test_folds(), and sklearn.model_selection._split._BaseKFold.n_splits.
_make_test_folds()
sklearn.model_selection._split.StratifiedKFold._make_test_folds (self, X, y = None) protected
Definition at line 773 of file _split.py.
Referenced by _iter_test_masks().
split()
sklearn.model_selection._split.StratifiedKFold.split (self, X, y, groups = None)
Generate indices to split data into training and test set.
Parameters
----------
X : array-like of shape (n_samples, n_features)
    Training data, where `n_samples` is the number of samples
    and `n_features` is the number of features.
    Note that providing ``y`` is sufficient to generate the splits and
    hence ``np.zeros(n_samples)`` may be used as a placeholder for
    ``X`` instead of actual training data.
y : array-like of shape (n_samples,)
    The target variable for supervised learning problems.
    Stratification is done based on the y labels.
groups : object
    Always ignored, exists for compatibility.
Yields
------
train : ndarray
    The training set indices for that split.
test : ndarray
    The testing set indices for that split.
Notes
-----
Randomized CV splitters may return different results for each call of
split. You can make the results identical by setting `random_state`
to an integer.
Reimplemented from sklearn.model_selection._split._BaseKFold.
Definition at line 848 of file _split.py.
References split().
Referenced by split().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/sklearn/model_selection/_split.py