Code Cloning Analysis: joblib.pool.PicklingPool Class Reference
joblib.pool.PicklingPool Class Reference
Public Member Functions
__init__ (self, processes=None, forward_reducers=None, backward_reducers=None, **kwargs)
Protected Member Functions
_setup_queues (self)
Protected Attributes
_forward_reducers = forward_reducers
_backward_reducers = backward_reducers
_inqueue = CustomizablePicklingQueue(context, self._forward_reducers)
_outqueue = CustomizablePicklingQueue(context, self._backward_reducers)
_quick_put = self._inqueue._send
_quick_get = self._outqueue._recv
Detailed Description
Pool implementation with customizable pickling reducers.
This is useful to control how data is shipped between processes
and makes it possible to use shared memory without useless
copies induces by the default pickling methods of the original
objects passed as arguments to dispatch.
`forward_reducers` and `backward_reducers` are expected to be
dictionaries with key/values being `(type, callable)` pairs where
`callable` is a function that, given an instance of `type`, will return a
tuple `(constructor, tuple_of_objects)` to rebuild an instance out of the
pickled `tuple_of_objects` as would return a `__reduce__` method.
See the standard library documentation about pickling for more details.
Definition at line 176 of file pool.py.
Constructor & Destructor Documentation
__init__()
joblib.pool.PicklingPool.__init__ (self, processes = None, forward_reducers = None, backward_reducers = None, ** kwargs)
Definition at line 193 of file pool.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_setup_queues()
joblib.pool.PicklingPool._setup_queues (self) protected
Definition at line 206 of file pool.py.
Member Data Documentation
_backward_reducers
joblib.pool.PicklingPool._backward_reducers = backward_reducers protected
Definition at line 201 of file pool.py.
_forward_reducers
joblib.pool.PicklingPool._forward_reducers = forward_reducers protected
Definition at line 200 of file pool.py.
_inqueue
joblib.pool.PicklingPool._inqueue = CustomizablePicklingQueue(context, self._forward_reducers) protected
Definition at line 208 of file pool.py.
_outqueue
joblib.pool.PicklingPool._outqueue = CustomizablePicklingQueue(context, self._backward_reducers) protected
Definition at line 209 of file pool.py.
_quick_get
joblib.pool.PicklingPool._quick_get = self._outqueue._recv protected
Definition at line 211 of file pool.py.
_quick_put
joblib.pool.PicklingPool._quick_put = self._inqueue._send protected
Definition at line 210 of file pool.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/joblib/pool.py