Code Cloning Analysis: matplotlib.rcsetup Namespace Reference
matplotlib.rcsetup Namespace Reference
Classes
class __getattr__
class _DunderChecker
class _ignorecase
class ValidateInStrings
Functions
_listify_validator (scalar_validator, allow_stringlist=False, *, n=None, doc=None)
validate_any (s)
_validate_date (s)
validate_bool (b)
validate_axisbelow (s)
validate_dpi (s)
_make_type_validator (cls, *, allow_none=False)
_validate_marker (s)
_validate_pathlike (s)
validate_fonttype (s)
validate_backend (s)
_validate_toolbar (s)
validate_color_or_inherit (s)
validate_color_or_auto (s)
validate_color_for_prop_cycle (s)
_validate_color_or_linecolor (s)
validate_color (s)
_validate_cmap (s)
validate_aspect (s)
validate_fontsize_None (s)
validate_fontsize (s)
validate_fontweight (s)
validate_fontstretch (s)
validate_font_properties (s)
_validate_mathtext_fallback (s)
validate_whiskers (s)
validate_ps_distiller (s)
_validate_linestyle (ls)
validate_markevery (s)
validate_bbox (s)
validate_sketch (s)
_validate_greaterthan_minushalf (s)
_validate_greaterequal0_lessequal1 (s)
_validate_int_greaterequal0 (s)
validate_hatch (s)
_validate_minor_tick_ndivs (n)
cycler (*args, **kwargs)
_validate_legend_loc (loc)
validate_cycler (s)
validate_hist_bins (s)
_convert_validator_spec (key, conv)
Variables
validate_anylist = _listify_validator(validate_any)
validate_string = _make_type_validator(str)
validate_string_or_None = _make_type_validator(str, allow_none=True)
validate_stringlist
validate_int = _make_type_validator(int)
validate_int_or_None = _make_type_validator(int, allow_none=True)
validate_float = _make_type_validator(float)
validate_float_or_None = _make_type_validator(float, allow_none=True)
validate_floatlist
_validate_markerlist
_auto_backend_sentinel = object()
validate_colorlist
validate_fontsizelist = _listify_validator(validate_fontsize)
_validate_named_linestyle
validate_fillstyle
validate_fillstylelist = _listify_validator(validate_fillstyle)
validate_markeverylist = _listify_validator(validate_markevery)
validate_hatchlist = _listify_validator(validate_hatch)
validate_dashlist = _listify_validator(validate_floatlist)
dict _prop_validators
dict _prop_aliases
_validate_named_legend_loc
dict _validators
dict _hardcoded_defaults
Detailed Description
The rcsetup module contains the validation code for customization using
Matplotlib's rc settings.
Each rc setting is assigned a function used to validate any attempted changes
to that setting.  The validation functions are defined in the rcsetup module,
and are used to construct the rcParams global object which stores the settings
and is referenced throughout Matplotlib.
The default values of the rc settings are set in the default matplotlibrc file.
Any additions or deletions to the parameter set listed here should also be
propagated to the :file:`lib/matplotlib/mpl-data/matplotlibrc` in Matplotlib's
root source directory.
Function Documentation
_convert_validator_spec()
matplotlib.rcsetup._convert_validator_spec (key, conv) protected
Definition at line 893 of file rcsetup.py.
_listify_validator()
matplotlib.rcsetup._listify_validator (scalar_validator, allow_stringlist = False, * , n = None, doc = None) protected
Definition at line 97 of file rcsetup.py.
_make_type_validator()
matplotlib.rcsetup._make_type_validator (cls, * , allow_none = False) protected
Return a validator that converts inputs to *cls* or raises (and possibly
allows ``None`` as well).
Definition at line 185 of file rcsetup.py.
References _make_type_validator().
Referenced by _make_type_validator().
_validate_cmap()
matplotlib.rcsetup._validate_cmap (s) protected
Definition at line 361 of file rcsetup.py.
_validate_color_or_linecolor()
matplotlib.rcsetup._validate_color_or_linecolor (s) protected
Definition at line 311 of file rcsetup.py.
_validate_date()
matplotlib.rcsetup._validate_date (s) protected
Definition at line 142 of file rcsetup.py.
_validate_greaterequal0_lessequal1()
matplotlib.rcsetup._validate_greaterequal0_lessequal1 (s) protected
Definition at line 591 of file rcsetup.py.
_validate_greaterthan_minushalf()
matplotlib.rcsetup._validate_greaterthan_minushalf (s) protected
Definition at line 583 of file rcsetup.py.
_validate_int_greaterequal0()
matplotlib.rcsetup._validate_int_greaterequal0 (s) protected
Definition at line 599 of file rcsetup.py.
_validate_legend_loc()
matplotlib.rcsetup._validate_legend_loc (loc) protected
Confirm that loc is a type which rc.Params["legend.loc"] supports.
.. versionadded:: 3.8
Parameters
----------
loc : str | int | (float, float) | str((float, float))
    The location of the legend.
Returns
-------
loc : str | int | (float, float) or raise ValueError exception
    The location of the legend.
Definition at line 780 of file rcsetup.py.
_validate_linestyle()
matplotlib.rcsetup._validate_linestyle (ls) protected
A validator for all possible line styles, the named ones *and*
the on-off ink sequences.
Definition at line 474 of file rcsetup.py.
_validate_marker()
matplotlib.rcsetup._validate_marker (s) protected
Definition at line 223 of file rcsetup.py.
_validate_mathtext_fallback()
matplotlib.rcsetup._validate_mathtext_fallback (s) protected
Definition at line 431 of file rcsetup.py.
_validate_minor_tick_ndivs()
matplotlib.rcsetup._validate_minor_tick_ndivs (n) protected
Validate ndiv parameter related to the minor ticks.
It controls the number of minor ticks to be placed between
two major ticks.
Definition at line 626 of file rcsetup.py.
_validate_pathlike()
matplotlib.rcsetup._validate_pathlike (s) protected
Definition at line 237 of file rcsetup.py.
_validate_toolbar()
matplotlib.rcsetup._validate_toolbar (s) protected
Definition at line 281 of file rcsetup.py.
cycler()
matplotlib.rcsetup.cycler (* args, ** kwargs)
Create a `~cycler.Cycler` object much like :func:`cycler.cycler`,
but includes input validation.
Call signatures::
  cycler(cycler)
  cycler(label=values, label2=values2, ...)
  cycler(label, values)
Form 1 copies a given `~cycler.Cycler` object.
Form 2 creates a `~cycler.Cycler` which cycles over one or more
properties simultaneously. If multiple properties are given, their
value lists must have the same length.
Form 3 creates a `~cycler.Cycler` for a single property. This form
exists for compatibility with the original cycler. Its use is
discouraged in favor of the kwarg form, i.e. ``cycler(label=values)``.
Parameters
----------
cycler : Cycler
    Copy constructor for Cycler.
label : str
    The property key. Must be a valid `.Artist` property.
    For example, 'color' or 'linestyle'. Aliases are allowed,
    such as 'c' for 'color' and 'lw' for 'linewidth'.
values : iterable
    Finite-length iterable of the property values. These values
    are validated and will raise a ValueError if invalid.
Returns
-------
Cycler
    A new :class:`~cycler.Cycler` for the given properties.
Examples
--------
Creating a cycler for a single property:
>>> c = cycler(color=['red', 'green', 'blue'])
Creating a cycler for simultaneously cycling over multiple properties
(e.g. red circle, green plus, blue cross):
>>> c = cycler(color=['red', 'green', 'blue'],
...            marker=['o', '+', 'x'])
Definition at line 677 of file rcsetup.py.
References validate_cycler().
validate_any()
matplotlib.rcsetup.validate_any (s)
Definition at line 137 of file rcsetup.py.
validate_aspect()
matplotlib.rcsetup.validate_aspect (s)
Definition at line 366 of file rcsetup.py.
validate_axisbelow()
matplotlib.rcsetup.validate_axisbelow (s)
Definition at line 163 of file rcsetup.py.
validate_backend()
matplotlib.rcsetup.validate_backend (s)
Definition at line 272 of file rcsetup.py.
validate_bbox()
matplotlib.rcsetup.validate_bbox (s)
Definition at line 555 of file rcsetup.py.
validate_bool()
matplotlib.rcsetup.validate_bool (b)
Convert b to ``bool`` or raise.
Definition at line 151 of file rcsetup.py.
References validate_bool().
Referenced by validate_bool().
validate_color()
matplotlib.rcsetup.validate_color (s)
Return a valid color arg.
Definition at line 332 of file rcsetup.py.
Referenced by validate_color_or_inherit().
validate_color_for_prop_cycle()
matplotlib.rcsetup.validate_color_for_prop_cycle (s)
Definition at line 304 of file rcsetup.py.
validate_color_or_auto()
matplotlib.rcsetup.validate_color_or_auto (s)
Definition at line 298 of file rcsetup.py.
validate_color_or_inherit()
matplotlib.rcsetup.validate_color_or_inherit (s)
Return a valid color arg.
Definition at line 291 of file rcsetup.py.
References validate_color().
validate_cycler()
matplotlib.rcsetup.validate_cycler (s)
Return a Cycler object from a string repr or the object itself.
Definition at line 814 of file rcsetup.py.
Referenced by cycler().
validate_dpi()
matplotlib.rcsetup.validate_dpi (s)
Confirm s is string 'figure' or convert s to float or raise.
Definition at line 174 of file rcsetup.py.
validate_font_properties()
matplotlib.rcsetup.validate_font_properties (s)
Definition at line 426 of file rcsetup.py.
validate_fontsize()
matplotlib.rcsetup.validate_fontsize (s)
Definition at line 382 of file rcsetup.py.
validate_fontsize_None()
matplotlib.rcsetup.validate_fontsize_None (s)
Definition at line 375 of file rcsetup.py.
validate_fontstretch()
matplotlib.rcsetup.validate_fontstretch (s)
Definition at line 412 of file rcsetup.py.
validate_fonttype()
matplotlib.rcsetup.validate_fonttype (s)
Confirm that this is a Postscript or PDF font type that we know how to
convert to.
Definition at line 246 of file rcsetup.py.
validate_fontweight()
matplotlib.rcsetup.validate_fontweight (s)
Definition at line 399 of file rcsetup.py.
validate_hatch()
matplotlib.rcsetup.validate_hatch (s)
Validate a hatch pattern.
A hatch pattern string can have any sequence of the following
characters: ``\ / | - + * . x o O``.
Definition at line 607 of file rcsetup.py.
validate_hist_bins()
matplotlib.rcsetup.validate_hist_bins (s)
Definition at line 873 of file rcsetup.py.
validate_markevery()
matplotlib.rcsetup.validate_markevery (s)
Validate the markevery property of a Line2D object.
Parameters
----------
s : None, int, (int, int), slice, float, (float, float), or list[int]
Returns
-------
None, int, (int, int), slice, float, (float, float), or list[int]
Definition at line 518 of file rcsetup.py.
validate_ps_distiller()
matplotlib.rcsetup.validate_ps_distiller (s)
Definition at line 457 of file rcsetup.py.
validate_sketch()
matplotlib.rcsetup.validate_sketch (s)
Definition at line 569 of file rcsetup.py.
validate_whiskers()
matplotlib.rcsetup.validate_whiskers (s)
Definition at line 446 of file rcsetup.py.
Variable Documentation
_auto_backend_sentinel
matplotlib.rcsetup._auto_backend_sentinel = object() protected
Definition at line 269 of file rcsetup.py.
_hardcoded_defaults
dict matplotlib.rcsetup._hardcoded_defaults protected
Initial value:
=  {  # Defaults not inferred from
    # lib/matplotlib/mpl-data/matplotlibrc...
    # ... because they are private:
    "_internal.classic_mode": False,
    # ... because they are deprecated:
    # No current deprecations.
    # backend is handled separately when constructing rcParamsDefault.
}
Definition at line 1362 of file rcsetup.py.
_prop_aliases
dict matplotlib.rcsetup._prop_aliases protected
Initial value:
=  {
        'c': 'color',
        'lw': 'linewidth',
        'ls': 'linestyle',
        'fc': 'facecolor',
        'ec': 'edgecolor',
        'mfc': 'markerfacecolor',
        'mec': 'markeredgecolor',
        'mew': 'markeredgewidth',
        'ms': 'markersize',
    }
Definition at line 664 of file rcsetup.py.
_prop_validators
dict matplotlib.rcsetup._prop_validators protected
Initial value:
=  {
        'color': _listify_validator(validate_color_for_prop_cycle,
                                    allow_stringlist=True),
        'linewidth': validate_floatlist,
        'linestyle': _listify_validator(_validate_linestyle),
        'facecolor': validate_colorlist,
        'edgecolor': validate_colorlist,
        'joinstyle': _listify_validator(JoinStyle),
        'capstyle': _listify_validator(CapStyle),
        'fillstyle': validate_fillstylelist,
        'markerfacecolor': validate_colorlist,
        'markersize': validate_floatlist,
        'markeredgewidth': validate_floatlist,
        'markeredgecolor': validate_colorlist,
        'markevery': validate_markeverylist,
        'alpha': validate_floatlist,
        'marker': _validate_markerlist,
        'hatch': validate_hatchlist,
        'dashes': validate_dashlist,
    }
Definition at line 644 of file rcsetup.py.
_validate_markerlist
matplotlib.rcsetup._validate_markerlist protected
Initial value:
=  _listify_validator(
    _validate_marker, doc='return a list of markers')
Definition at line 233 of file rcsetup.py.
_validate_named_legend_loc
matplotlib.rcsetup._validate_named_legend_loc protected
Initial value:
=  ValidateInStrings(
    'legend.loc',
    [
        "best",
        "upper right", "upper left", "lower left", "lower right", "right",
        "center left", "center right", "lower center", "upper center",
        "center"],
    ignorecase=True)
Definition at line 770 of file rcsetup.py.
_validate_named_linestyle
matplotlib.rcsetup._validate_named_linestyle protected
Initial value:
=  ValidateInStrings(
    'linestyle',
    [*ls_mapper.keys(), *ls_mapper.values(), 'None', 'none', ' ', ''],
    ignorecase=True)
Definition at line 468 of file rcsetup.py.
_validators
dict matplotlib.rcsetup._validators protected
Definition at line 906 of file rcsetup.py.
validate_anylist
matplotlib.rcsetup.validate_anylist = _listify_validator(validate_any)
Definition at line 139 of file rcsetup.py.
validate_colorlist
matplotlib.rcsetup.validate_colorlist
Initial value:
=  _listify_validator(
    validate_color, allow_stringlist=True, doc='return a list of colorspecs')
Definition at line 357 of file rcsetup.py.
validate_dashlist
matplotlib.rcsetup.validate_dashlist = _listify_validator(validate_floatlist)
Definition at line 623 of file rcsetup.py.
validate_fillstyle
matplotlib.rcsetup.validate_fillstyle
Initial value:
=  ValidateInStrings(
    'markers.fillstyle', ['full', 'left', 'right', 'bottom', 'top', 'none'])
Definition at line 511 of file rcsetup.py.
validate_fillstylelist
matplotlib.rcsetup.validate_fillstylelist = _listify_validator(validate_fillstyle)
Definition at line 515 of file rcsetup.py.
validate_float
matplotlib.rcsetup.validate_float = _make_type_validator(float)
Definition at line 217 of file rcsetup.py.
validate_float_or_None
matplotlib.rcsetup.validate_float_or_None = _make_type_validator(float, allow_none=True)
Definition at line 218 of file rcsetup.py.
validate_floatlist
matplotlib.rcsetup.validate_floatlist
Initial value:
=  _listify_validator(
    validate_float, doc='return a list of floats')
Definition at line 219 of file rcsetup.py.
validate_fontsizelist
matplotlib.rcsetup.validate_fontsizelist = _listify_validator(validate_fontsize)
Definition at line 396 of file rcsetup.py.
validate_hatchlist
matplotlib.rcsetup.validate_hatchlist = _listify_validator(validate_hatch)
Definition at line 622 of file rcsetup.py.
validate_int
matplotlib.rcsetup.validate_int = _make_type_validator(int)
Definition at line 215 of file rcsetup.py.
validate_int_or_None
matplotlib.rcsetup.validate_int_or_None = _make_type_validator(int, allow_none=True)
Definition at line 216 of file rcsetup.py.
validate_markeverylist
matplotlib.rcsetup.validate_markeverylist = _listify_validator(validate_markevery)
Definition at line 552 of file rcsetup.py.
validate_string
matplotlib.rcsetup.validate_string = _make_type_validator(str)
Definition at line 211 of file rcsetup.py.
validate_string_or_None
matplotlib.rcsetup.validate_string_or_None = _make_type_validator(str, allow_none=True)
Definition at line 212 of file rcsetup.py.
validate_stringlist
matplotlib.rcsetup.validate_stringlist
Initial value:
=  _listify_validator(
    validate_string, doc='return a list of strings')
Definition at line 213 of file rcsetup.py.