Code Cloning Analysis: fontTools.voltLib.ast.Enum Class Reference
fontTools.voltLib.ast.Enum Class Reference
Public Member Functions
__init__ (self, enum, location=None)
__iter__ (self)
glyphSet (self, groups=None)
__str__ (self)
Public Member Functions inherited from fontTools.voltLib.ast.Element
__init__ (self, location=None)
build (self, builder)
__str__ (self)
Public Attributes
enum = enum
Public Attributes inherited from fontTools.voltLib.ast.Element
location = location
Detailed Description
An enum
Definition at line 122 of file ast.py.
Constructor & Destructor Documentation
__init__()
fontTools.voltLib.ast.Enum.__init__ (self, enum, location = None)
Definition at line 125 of file ast.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__iter__()
fontTools.voltLib.ast.Enum.__iter__ (self)
Definition at line 129 of file ast.py.
__str__()
fontTools.voltLib.ast.Enum.__str__ (self)
Definition at line 142 of file ast.py.
Referenced by numpy.polynomial._polybase.ABCPolyBase._get_coefficients().
glyphSet()
fontTools.voltLib.ast.Enum.glyphSet (self, groups = None)
Definition at line 133 of file ast.py.
Member Data Documentation
enum
fontTools.voltLib.ast.Enum.enum = enum
Definition at line 127 of file ast.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/voltLib/ast.py