Code Cloning Analysis: sklearn.metrics._plot.tests.test_roc_curve_display Namespace Reference
sklearn.metrics._plot.tests.test_roc_curve_display Namespace Reference
Functions
data_binary ()
_check_figure_axes_and_labels (display, pos_label)
test_roc_curve_display_plotting (pyplot, response_method, data_binary, with_sample_weight, drop_intermediate, with_strings, constructor_name, default_name)
test_roc_curve_plot_parameter_length_validation (pyplot, params, err_msg)
test_validate_plot_params (pyplot)
test_roc_curve_from_cv_results_param_validation (pyplot, data_binary)
test_roc_curve_display_from_cv_results_curve_kwargs (pyplot, data_binary, curve_kwargs)
test_roc_curve_display_estimator_name_deprecation (pyplot)
test_roc_curve_display_kwargs_deprecation (pyplot, data_binary, constructor_name)
test_roc_curve_display_plotting_from_cv_results (pyplot, data_binary, with_strings, with_sample_weight, response_method, drop_intermediate, curve_kwargs)
test_roc_curve_plot_legend_label (pyplot, data_binary, name, curve_kwargs, roc_auc)
test_roc_curve_from_cv_results_legend_label (pyplot, data_binary, name, curve_kwargs)
test_roc_curve_from_cv_results_curve_kwargs (pyplot, data_binary, curve_kwargs)
_check_chance_level (plot_chance_level, chance_level_kw, display)
test_roc_curve_chance_level_line (pyplot, data_binary, plot_chance_level, chance_level_kw, label, constructor_name)
test_roc_curve_chance_level_line_from_cv_results (pyplot, data_binary, plot_chance_level, chance_level_kw, curve_kwargs)
test_roc_curve_display_complex_pipeline (pyplot, data_binary, clf, constructor_name)
test_roc_curve_display_default_labels (pyplot, roc_auc, name, curve_kwargs, expected_labels)
_check_auc (display, constructor_name)
test_plot_roc_curve_pos_label (pyplot, response_method, constructor_name)
test_y_score_and_y_pred_specified_error ()
test_y_pred_deprecation_warning (pyplot)
test_plot_roc_curve_despine (pyplot, data_binary, despine, constructor_name)
Function Documentation
_check_auc()
sklearn.metrics._plot.tests.test_roc_curve_display._check_auc (display, constructor_name) protected
Definition at line 818 of file test_roc_curve_display.py.
_check_chance_level()
sklearn.metrics._plot.tests.test_roc_curve_display._check_chance_level (plot_chance_level, chance_level_kw, display) protected
Check chance level line and line styles correct.
Definition at line 600 of file test_roc_curve_display.py.
Referenced by test_roc_curve_chance_level_line(), and test_roc_curve_chance_level_line_from_cv_results().
_check_figure_axes_and_labels()
sklearn.metrics._plot.tests.test_roc_curve_display._check_figure_axes_and_labels (display, pos_label) protected
Check mpl axes and figure defaults are correct.
Definition at line 35 of file test_roc_curve_display.py.
Referenced by test_roc_curve_display_plotting(), and test_roc_curve_display_plotting_from_cv_results().
data_binary()
sklearn.metrics._plot.tests.test_roc_curve_display.data_binary ()
Definition at line 22 of file test_roc_curve_display.py.
test_plot_roc_curve_despine()
sklearn.metrics._plot.tests.test_roc_curve_display.test_plot_roc_curve_despine (pyplot, data_binary, despine, constructor_name)
Definition at line 960 of file test_roc_curve_display.py.
test_plot_roc_curve_pos_label()
sklearn.metrics._plot.tests.test_roc_curve_display.test_plot_roc_curve_pos_label (pyplot, response_method, constructor_name)
Definition at line 834 of file test_roc_curve_display.py.
test_roc_curve_chance_level_line()
sklearn.metrics._plot.tests.test_roc_curve_display.test_roc_curve_chance_level_line (pyplot, data_binary, plot_chance_level, chance_level_kw, label, constructor_name)
Check chance level plotting behavior of `from_predictions`, `from_estimator`.
Definition at line 643 of file test_roc_curve_display.py.
References _check_chance_level().
test_roc_curve_chance_level_line_from_cv_results()
sklearn.metrics._plot.tests.test_roc_curve_display.test_roc_curve_chance_level_line_from_cv_results (pyplot, data_binary, plot_chance_level, chance_level_kw, curve_kwargs)
Check chance level plotting behavior with `from_cv_results`.
Definition at line 712 of file test_roc_curve_display.py.
References _check_chance_level().
test_roc_curve_display_complex_pipeline()
sklearn.metrics._plot.tests.test_roc_curve_display.test_roc_curve_display_complex_pipeline (pyplot, data_binary, clf, constructor_name)
Check the behaviour with complex pipeline.
Definition at line 768 of file test_roc_curve_display.py.
test_roc_curve_display_default_labels()
sklearn.metrics._plot.tests.test_roc_curve_display.test_roc_curve_display_default_labels (pyplot, roc_auc, name, curve_kwargs, expected_labels)
Check the default labels used in the display.
Definition at line 805 of file test_roc_curve_display.py.
test_roc_curve_display_estimator_name_deprecation()
sklearn.metrics._plot.tests.test_roc_curve_display.test_roc_curve_display_estimator_name_deprecation (pyplot)
Check deprecation of `estimator_name`.
Definition at line 326 of file test_roc_curve_display.py.
test_roc_curve_display_from_cv_results_curve_kwargs()
sklearn.metrics._plot.tests.test_roc_curve_display.test_roc_curve_display_from_cv_results_curve_kwargs (pyplot, data_binary, curve_kwargs)
Check `curve_kwargs` correctly passed.
Definition at line 296 of file test_roc_curve_display.py.
test_roc_curve_display_kwargs_deprecation()
sklearn.metrics._plot.tests.test_roc_curve_display.test_roc_curve_display_kwargs_deprecation (pyplot, data_binary, constructor_name)
Check **kwargs deprecated correctly in favour of `curve_kwargs`.
Definition at line 338 of file test_roc_curve_display.py.
test_roc_curve_display_plotting()
sklearn.metrics._plot.tests.test_roc_curve_display.test_roc_curve_display_plotting (pyplot, response_method, data_binary, with_sample_weight, drop_intermediate, with_strings, constructor_name, default_name)
Check the overall plotting behaviour for single curve.
Definition at line 64 of file test_roc_curve_display.py.
References _check_figure_axes_and_labels().
test_roc_curve_display_plotting_from_cv_results()
sklearn.metrics._plot.tests.test_roc_curve_display.test_roc_curve_display_plotting_from_cv_results (pyplot, data_binary, with_strings, with_sample_weight, response_method, drop_intermediate, curve_kwargs)
Check overall plotting of `from_cv_results`.
Definition at line 383 of file test_roc_curve_display.py.
References _check_figure_axes_and_labels().
test_roc_curve_from_cv_results_curve_kwargs()
sklearn.metrics._plot.tests.test_roc_curve_display.test_roc_curve_from_cv_results_curve_kwargs (pyplot, data_binary, curve_kwargs)
Check line kwargs passed correctly in `from_cv_results`.
Definition at line 577 of file test_roc_curve_display.py.
test_roc_curve_from_cv_results_legend_label()
sklearn.metrics._plot.tests.test_roc_curve_display.test_roc_curve_from_cv_results_legend_label (pyplot, data_binary, name, curve_kwargs)
Check legend label correct with all `curve_kwargs`, `name` combinations.
Definition at line 529 of file test_roc_curve_display.py.
test_roc_curve_from_cv_results_param_validation()
sklearn.metrics._plot.tests.test_roc_curve_display.test_roc_curve_from_cv_results_param_validation (pyplot, data_binary)
Check parameter validation is correct.
Definition at line 227 of file test_roc_curve_display.py.
test_roc_curve_plot_legend_label()
sklearn.metrics._plot.tests.test_roc_curve_display.test_roc_curve_plot_legend_label (pyplot, data_binary, name, curve_kwargs, roc_auc)
Check legend label correct with all `curve_kwargs`, `name` combinations.
Definition at line 473 of file test_roc_curve_display.py.
test_roc_curve_plot_parameter_length_validation()
sklearn.metrics._plot.tests.test_roc_curve_display.test_roc_curve_plot_parameter_length_validation (pyplot, params, err_msg)
Check `plot` parameter length validation performed correctly.
Definition at line 189 of file test_roc_curve_display.py.
test_validate_plot_params()
sklearn.metrics._plot.tests.test_roc_curve_display.test_validate_plot_params (pyplot)
Check `_validate_plot_params` returns the correct variables.
Definition at line 200 of file test_roc_curve_display.py.
test_y_pred_deprecation_warning()
sklearn.metrics._plot.tests.test_roc_curve_display.test_y_pred_deprecation_warning (pyplot)
Check that a warning is raised when y_pred is specified.
Definition at line 940 of file test_roc_curve_display.py.
test_y_score_and_y_pred_specified_error()
sklearn.metrics._plot.tests.test_roc_curve_display.test_y_score_and_y_pred_specified_error ()
Check that an error is raised when both y_score and y_pred are specified.
Definition at line 927 of file test_roc_curve_display.py.