Code Cloning Analysis: dateutil.parser.isoparser.isoparser Class Reference
dateutil.parser.isoparser.isoparser Class Reference
Public Member Functions
__init__ (self, sep=None)
isoparse (self, dt_str)
parse_isodate (self, datestr)
parse_isotime (self, timestr)
parse_tzstr (self, tzstr, zero_as_utc=True)
Protected Member Functions
_parse_isodate (self, dt_str)
_parse_isodate_common (self, dt_str)
_parse_isodate_uncommon (self, dt_str)
_calculate_weekdate (self, year, week, day)
_parse_isotime (self, timestr)
_parse_tzstr (self, tzstr, zero_as_utc=True)
Protected Attributes
_sep = sep
Static Protected Attributes
str _DATE_SEP = b'-'
str _TIME_SEP = b':'
_FRACTION_REGEX = re.compile(b'[\\.,]([0-9]+)')
Detailed Description
Definition at line 42 of file isoparser.py.
Constructor & Destructor Documentation
__init__()
dateutil.parser.isoparser.isoparser.__init__ (self, sep = None)
:param sep:
    A single character that separates date and time portions. If
    ``None``, the parser will accept any single character.
    For strict ISO-8601 adherence, pass ``'T'``.
Definition at line 43 of file isoparser.py.
References _sep.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_calculate_weekdate()
dateutil.parser.isoparser.isoparser._calculate_weekdate (self, year, week, day) protected
Calculate the day of corresponding to the ISO year-week-day calendar.
This function is effectively the inverse of
:func:`datetime.date.isocalendar`.
:param year:
    The year in the ISO calendar
:param week:
    The week in the ISO calendar - range is [1, 53]
:param day:
    The day in the ISO calendar - range is [1 (MON), 7 (SUN)]
:return:
    Returns a :class:`datetime.date`
Definition at line 297 of file isoparser.py.
References _FRACTION_REGEX, _parse_tzstr(), and _TIME_SEP.
Referenced by parse_tzstr().
_parse_isodate()
dateutil.parser.isoparser.isoparser._parse_isodate (self, dt_str) protected
Definition at line 206 of file isoparser.py.
Referenced by isoparse(), and parse_isodate().
_parse_isodate_common()
dateutil.parser.isoparser.isoparser._parse_isodate_common (self, dt_str) protected
Definition at line 212 of file isoparser.py.
Referenced by parse_tzstr().
_parse_isodate_uncommon()
dateutil.parser.isoparser.isoparser._parse_isodate_uncommon (self, dt_str) protected
Definition at line 253 of file isoparser.py.
Referenced by parse_tzstr().
_parse_isotime()
dateutil.parser.isoparser.isoparser._parse_isotime (self, timestr) protected
Definition at line 330 of file isoparser.py.
Referenced by isoparse(), and parse_isotime().
_parse_tzstr()
dateutil.parser.isoparser.isoparser._parse_tzstr (self, tzstr, zero_as_utc = True) protected
Definition at line 383 of file isoparser.py.
Referenced by _calculate_weekdate(), and parse_tzstr().
isoparse()
dateutil.parser.isoparser.isoparser.isoparse (self, dt_str)
Parse an ISO-8601 datetime string into a :class:`datetime.datetime`.
An ISO-8601 datetime string consists of a date portion, followed
optionally by a time portion - the date and time portions are separated
by a single character separator, which is ``T`` in the official
standard. Incomplete date formats (such as ``YYYY-MM``) may *not* be
combined with a time portion.
Supported date formats are:
Common:
- ``YYYY``
- ``YYYY-MM``
- ``YYYY-MM-DD`` or ``YYYYMMDD``
Uncommon:
- ``YYYY-Www`` or ``YYYYWww`` - ISO week (day defaults to 0)
- ``YYYY-Www-D`` or ``YYYYWwwD`` - ISO week and day
The ISO week and day numbering follows the same logic as
:func:`datetime.date.isocalendar`.
Supported time formats are:
- ``hh``
- ``hh:mm`` or ``hhmm``
- ``hh:mm:ss`` or ``hhmmss``
- ``hh:mm:ss.ssssss`` (Up to 6 sub-second digits)
Midnight is a special case for `hh`, as the standard supports both
00:00 and 24:00 as a representation. The decimal separator can be
either a dot or a comma.
.. caution::
    Support for fractional components other than seconds is part of the
    ISO-8601 standard, but is not currently implemented in this parser.
Supported time zone offset formats are:
- `Z` (UTC)
- `±HH:MM`
- `±HHMM`
- `±HH`
Offsets will be represented as :class:`dateutil.tz.tzoffset` objects,
with the exception of UTC, which will be represented as
:class:`dateutil.tz.tzutc`. Time zone offsets equivalent to UTC (such
as `+00:00`) will also be represented as :class:`dateutil.tz.tzutc`.
:param dt_str:
    A string or stream containing only an ISO-8601 datetime string
:return:
    Returns a :class:`datetime.datetime` representing the string.
    Unspecified components default to their lowest value.
.. warning::
    As of version 2.7.0, the strictness of the parser should not be
    considered a stable part of the contract. Any valid ISO-8601 string
    that parses correctly with the default settings will continue to
    parse correctly in future versions, but invalid strings that
    currently fail (e.g. ``2017-01-01T00:00+00:00:00``) are not
    guaranteed to continue failing in future versions if they encode
    a valid date.
.. versionadded:: 2.7.0
Definition at line 60 of file isoparser.py.
References _parse_isodate(), _parse_isotime(), and _sep.
parse_isodate()
dateutil.parser.isoparser.isoparser.parse_isodate (self, datestr)
Parse the date portion of an ISO string.
:param datestr:
    The string portion of an ISO string, without a separator
:return:
    Returns a :class:`datetime.date` object
Definition at line 149 of file isoparser.py.
References _parse_isodate().
parse_isotime()
dateutil.parser.isoparser.isoparser.parse_isotime (self, timestr)
Parse the time portion of an ISO string.
:param timestr:
    The time portion of an ISO string, without a separator
:return:
    Returns a :class:`datetime.time` object
Definition at line 166 of file isoparser.py.
References _parse_isotime().
parse_tzstr()
dateutil.parser.isoparser.isoparser.parse_tzstr (self, tzstr, zero_as_utc = True)
Parse a valid ISO time zone string.
See :func:`isoparser.isoparse` for details on supported formats.
:param tzstr:
    A string representing an ISO time zone offset
:param zero_as_utc:
    Whether to return :class:`dateutil.tz.tzutc` for zero-offset zones
:return:
    Returns :class:`dateutil.tz.tzoffset` for offsets and
    :class:`dateutil.tz.tzutc` for ``Z`` and (if ``zero_as_utc`` is
    specified) offsets equivalent to UTC.
Definition at line 182 of file isoparser.py.
References _calculate_weekdate(), _DATE_SEP, _parse_isodate_common(), _parse_isodate_uncommon(), and _parse_tzstr().
Member Data Documentation
_DATE_SEP
str dateutil.parser.isoparser.isoparser._DATE_SEP = b'-' static protected
Definition at line 202 of file isoparser.py.
Referenced by parse_tzstr().
_FRACTION_REGEX
dateutil.parser.isoparser.isoparser._FRACTION_REGEX = re.compile(b'[\\.,]([0-9]+)') static protected
Definition at line 204 of file isoparser.py.
Referenced by _calculate_weekdate().
_sep
dateutil.parser.isoparser.isoparser._sep = sep protected
Definition at line 57 of file isoparser.py.
Referenced by __init__(), and isoparse().
_TIME_SEP
str dateutil.parser.isoparser.isoparser._TIME_SEP = b':' static protected
Definition at line 203 of file isoparser.py.
Referenced by _calculate_weekdate().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/dateutil/parser/isoparser.py