Code Cloning Analysis: scipy.optimize.tests.test__shgo.TestShgoArguments Class Reference
scipy.optimize.tests.test__shgo.TestShgoArguments Class Reference
Public Member Functions
test_1_1_simpl_iter (self)
test_1_2_simpl_iter (self)
test_2_1_sobol_iter (self)
test_2_2_sobol_iter (self)
test_3_1_disp_simplicial (self)
test_3_2_disp_sobol (self)
test_args_gh14589 (self)
test_4_1_known_f_min (self)
test_4_2_known_f_min (self)
test_4_4_known_f_min (self)
test_5_1_simplicial_argless (self)
test_5_2_sobol_argless (self)
test_6_1_simplicial_max_iter (self)
test_6_2_simplicial_min_iter (self)
test_7_1_minkwargs (self)
test_7_2_minkwargs (self)
test_7_3_minkwargs (self)
test_8_homology_group_diff (self)
test_9_cons_g (self)
test_10_finite_time (self)
test_11_f_min_0 (self)
test_12_sobol_inf_cons (self)
test_13_high_sobol (self)
test_14_local_iter (self)
test_15_min_every_iter (self)
test_16_disp_bounds_minimizer (self)
test_17_custom_sampling (self)
test_18_bounds_class (self)
test_19_parallelization (self)
test_20_constrained_args (self)
test_21_1_jac_true (self)
test_21_2_derivative_options (self, derivative)
test_21_3_hess_options_rosen (self)
test_21_arg_tuple_sobol (self)
Detailed Description
Definition at line 513 of file test__shgo.py.
Member Function Documentation
test_10_finite_time()
scipy.optimize.tests.test__shgo.TestShgoArguments.test_10_finite_time (self)
Test single function constraint passing
Definition at line 696 of file test__shgo.py.
test_11_f_min_0()
scipy.optimize.tests.test__shgo.TestShgoArguments.test_11_f_min_0 (self)
Test to cover the case where f_lowest == 0
Definition at line 708 of file test__shgo.py.
test_12_sobol_inf_cons()
scipy.optimize.tests.test__shgo.TestShgoArguments.test_12_sobol_inf_cons (self)
Test to cover the case where f_lowest == 0
Definition at line 719 of file test__shgo.py.
test_13_high_sobol()
scipy.optimize.tests.test__shgo.TestShgoArguments.test_13_high_sobol (self)
Test init of high-dimensional sobol sequences
Definition at line 730 of file test__shgo.py.
test_14_local_iter()
scipy.optimize.tests.test__shgo.TestShgoArguments.test_14_local_iter (self)
Test limited local iterations for a pseudo-global mode
Definition at line 741 of file test__shgo.py.
test_15_min_every_iter()
scipy.optimize.tests.test__shgo.TestShgoArguments.test_15_min_every_iter (self)
Test minimize every iter options and cover function cache
Definition at line 746 of file test__shgo.py.
test_16_disp_bounds_minimizer()
scipy.optimize.tests.test__shgo.TestShgoArguments.test_16_disp_bounds_minimizer (self)
Test disp=True with minimizers that do not support bounds
Definition at line 752 of file test__shgo.py.
test_17_custom_sampling()
scipy.optimize.tests.test__shgo.TestShgoArguments.test_17_custom_sampling (self)
Test the functionality to add custom sampling methods to shgo
Definition at line 759 of file test__shgo.py.
test_18_bounds_class()
scipy.optimize.tests.test__shgo.TestShgoArguments.test_18_bounds_class (self)
Definition at line 767 of file test__shgo.py.
test_19_parallelization()
scipy.optimize.tests.test__shgo.TestShgoArguments.test_19_parallelization (self)
Test the functionality to add custom sampling methods to shgo
Definition at line 788 of file test__shgo.py.
test_1_1_simpl_iter()
scipy.optimize.tests.test__shgo.TestShgoArguments.test_1_1_simpl_iter (self)
Iterative simplicial sampling on TestFunction 1 (multivariate)
Definition at line 514 of file test__shgo.py.
test_1_2_simpl_iter()
scipy.optimize.tests.test__shgo.TestShgoArguments.test_1_2_simpl_iter (self)
Iterative simplicial on TestFunction 2 (univariate)
Definition at line 518 of file test__shgo.py.
test_20_constrained_args()
scipy.optimize.tests.test__shgo.TestShgoArguments.test_20_constrained_args (self)
Test that constraints can be passed to arguments
Definition at line 798 of file test__shgo.py.
test_21_1_jac_true()
scipy.optimize.tests.test__shgo.TestShgoArguments.test_21_1_jac_true (self)
Test that shgo can handle objective functions that return the
gradient alongside the objective value. Fixes gh-13547
Definition at line 834 of file test__shgo.py.
References scipy.optimize._minimize.minimize().
test_21_2_derivative_options()
scipy.optimize.tests.test__shgo.TestShgoArguments.test_21_2_derivative_options (self, derivative)
shgo used to raise an error when passing `options` with 'jac'
# see gh-12963. check that this is resolved
Definition at line 864 of file test__shgo.py.
References scipy.optimize._minimize.minimize().
test_21_3_hess_options_rosen()
scipy.optimize.tests.test__shgo.TestShgoArguments.test_21_3_hess_options_rosen (self)
Ensure the Hessian gets passed correctly to the local minimizer
routine. Previous report gh-14533.
Definition at line 895 of file test__shgo.py.
References scipy.optimize._minimize.minimize().
test_21_arg_tuple_sobol()
scipy.optimize.tests.test__shgo.TestShgoArguments.test_21_arg_tuple_sobol (self)
shgo used to raise an error when passing `args` with Sobol sampling
# see gh-12114. check that this is resolved
Definition at line 910 of file test__shgo.py.
References scipy.optimize._minimize.minimize().
test_2_1_sobol_iter()
scipy.optimize.tests.test__shgo.TestShgoArguments.test_2_1_sobol_iter (self)
Iterative Sobol sampling on TestFunction 1 (multivariate)
Definition at line 524 of file test__shgo.py.
test_2_2_sobol_iter()
scipy.optimize.tests.test__shgo.TestShgoArguments.test_2_2_sobol_iter (self)
Iterative Sobol sampling on TestFunction 2 (univariate)
Definition at line 528 of file test__shgo.py.
test_3_1_disp_simplicial()
scipy.optimize.tests.test__shgo.TestShgoArguments.test_3_1_disp_simplicial (self)
Iterative sampling on TestFunction 1 and 2  (multi and univariate)
Definition at line 537 of file test__shgo.py.
test_3_2_disp_sobol()
scipy.optimize.tests.test__shgo.TestShgoArguments.test_3_2_disp_sobol (self)
Iterative sampling on TestFunction 1 and 2 (multi and univariate)
Definition at line 551 of file test__shgo.py.
test_4_1_known_f_min()
scipy.optimize.tests.test__shgo.TestShgoArguments.test_4_1_known_f_min (self)
Test known function minima stopping criteria
Definition at line 574 of file test__shgo.py.
test_4_2_known_f_min()
scipy.optimize.tests.test__shgo.TestShgoArguments.test_4_2_known_f_min (self)
Test Global mode limiting local evalutions
Definition at line 585 of file test__shgo.py.
test_4_4_known_f_min()
scipy.optimize.tests.test__shgo.TestShgoArguments.test_4_4_known_f_min (self)
Test Global mode limiting local evaluations for 1D funcs
Definition at line 597 of file test__shgo.py.
test_5_1_simplicial_argless()
scipy.optimize.tests.test__shgo.TestShgoArguments.test_5_1_simplicial_argless (self)
Test Default simplicial sampling settings on TestFunction 1
Definition at line 613 of file test__shgo.py.
test_5_2_sobol_argless()
scipy.optimize.tests.test__shgo.TestShgoArguments.test_5_2_sobol_argless (self)
Test Default sobol sampling settings on TestFunction 1
Definition at line 619 of file test__shgo.py.
test_6_1_simplicial_max_iter()
scipy.optimize.tests.test__shgo.TestShgoArguments.test_6_1_simplicial_max_iter (self)
Test that maximum iteration option works on TestFunction 3
Definition at line 626 of file test__shgo.py.
test_6_2_simplicial_min_iter()
scipy.optimize.tests.test__shgo.TestShgoArguments.test_6_2_simplicial_min_iter (self)
Test that maximum iteration option works on TestFunction 3
Definition at line 635 of file test__shgo.py.
test_7_1_minkwargs()
scipy.optimize.tests.test__shgo.TestShgoArguments.test_7_1_minkwargs (self)
Test the minimizer_kwargs arguments for solvers with constraints
Definition at line 644 of file test__shgo.py.
test_7_2_minkwargs()
scipy.optimize.tests.test__shgo.TestShgoArguments.test_7_2_minkwargs (self)
Test the minimizer_kwargs default inits
Definition at line 656 of file test__shgo.py.
test_7_3_minkwargs()
scipy.optimize.tests.test__shgo.TestShgoArguments.test_7_3_minkwargs (self)
Test minimizer_kwargs arguments for solvers without constraints
Definition at line 663 of file test__shgo.py.
test_8_homology_group_diff()
scipy.optimize.tests.test__shgo.TestShgoArguments.test_8_homology_group_diff (self)
Definition at line 683 of file test__shgo.py.
test_9_cons_g()
scipy.optimize.tests.test__shgo.TestShgoArguments.test_9_cons_g (self)
Test single function constraint passing
Definition at line 690 of file test__shgo.py.
test_args_gh14589()
scipy.optimize.tests.test__shgo.TestShgoArguments.test_args_gh14589 (self)
Using `args` used to cause `shgo` to fail; see #14589, #15986,
#16506
Definition at line 564 of file test__shgo.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/optimize/tests/test__shgo.py