Code Cloning Analysis: scipy.sparse.linalg._matfuncs Namespace Reference
scipy.sparse.linalg._matfuncs Namespace Reference
Classes
class _ExpmPadeHelper
class MatrixPowerOperator
class ProductOperator
Functions
inv (A)
_onenorm_matrix_power_nnm (A, p)
_is_upper_triangular (A)
_smart_matrix_product (A, B, alpha=None, structure=None)
_onenormest_matrix_power (A, p, t=2, itmax=5, compute_v=False, compute_w=False, structure=None)
_onenormest_product (operator_seq, t=2, itmax=5, compute_v=False, compute_w=False, structure=None)
expm (A)
_expm (A, use_exact_onenorm)
_solve_P_Q (U, V, structure=None)
_exp_sinch (a, x)
_eq_10_42 (lam_1, lam_2, t_12)
_fragment_2_1 (X, T, s)
_ell (A, m)
Variables
list __all__ = ['expm', 'inv']
str UPPER_TRIANGULAR = 'upper_triangular'
Detailed Description
Sparse matrix functions
Function Documentation
_ell()
scipy.sparse.linalg._matfuncs._ell (A, m) protected
A helper function for expm_2009.
Parameters
----------
A : linear operator
    A linear operator whose norm of power we care about.
m : int
    The power of the linear operator
Returns
-------
value : int
    A value related to a bound.
Definition at line 819 of file _matfuncs.py.
References _onenorm_matrix_power_nnm().
Referenced by expm().
_eq_10_42()
scipy.sparse.linalg._matfuncs._eq_10_42 (lam_1, lam_2, t_12) protected
Equation (10.42) of Functions of Matrices: Theory and Computation.
Notes
-----
This is a helper function for _fragment_2_1 of expm_2009.
Equation (10.42) is on page 251 in the section on Schur algorithms.
In particular, section 10.4.3 explains the Schur-Parlett algorithm.
expm([[lam_1, t_12], [0, lam_1])
=
[[exp(lam_1), t_12*exp((lam_1 + lam_2)/2)*sinch((lam_1 - lam_2)/2)],
[0, exp(lam_2)]
Definition at line 746 of file _matfuncs.py.
References _exp_sinch().
Referenced by _fragment_2_1().
_exp_sinch()
scipy.sparse.linalg._matfuncs._exp_sinch (a, x) protected
Stably evaluate exp(a)*sinh(x)/x
Notes
-----
The strategy of falling back to a sixth order Taylor expansion
was suggested by the Spallation Neutron Source docs
which was found on the internet by google search.
http://www.ornl.gov/~t6p/resources/xal/javadoc/gov/sns/tools/math/ElementaryFunction.html
The details of the cutoff point and the Horner-like evaluation
was picked without reference to anything in particular.
Note that sinch is not currently implemented in scipy.special,
whereas the "engineer's" definition of sinc is implemented.
The implementation of sinc involves a scaling factor of pi
that distinguishes it from the "mathematician's" version of sinc.
Definition at line 715 of file _matfuncs.py.
Referenced by _eq_10_42().
_expm()
scipy.sparse.linalg._matfuncs._expm (A, use_exact_onenorm) protected
Definition at line 593 of file _matfuncs.py.
_fragment_2_1()
scipy.sparse.linalg._matfuncs._fragment_2_1 (X, T, s) protected
A helper function for expm_2009.
Notes
-----
The argument X is modified in-place, but this modification is not the same
as the returned value of the function.
This function also takes pains to do things in ways that are compatible
with sparse matrices, for example by avoiding fancy indexing
and by using methods of the matrices whenever possible instead of
using functions of the numpy or scipy libraries themselves.
Definition at line 770 of file _matfuncs.py.
References _eq_10_42().
Referenced by expm().
_is_upper_triangular()
scipy.sparse.linalg._matfuncs._is_upper_triangular (A) protected
Definition at line 112 of file _matfuncs.py.
_onenorm_matrix_power_nnm()
scipy.sparse.linalg._matfuncs._onenorm_matrix_power_nnm (A, p) protected
Compute the 1-norm of a non-negative integer power of a non-negative matrix.
Parameters
----------
A : a square ndarray or matrix or sparse matrix
    Input matrix with non-negative entries.
p : non-negative integer
    The power to which the matrix is to be raised.
Returns
-------
out : float
    The 1-norm of the matrix power p of A.
Definition at line 79 of file _matfuncs.py.
References scipy.sparse._base.issparse().
Referenced by scipy.sparse.linalg.tests.test_matfuncs._burkardt_13_power(), and _ell().
_onenormest_matrix_power()
scipy.sparse.linalg._matfuncs._onenormest_matrix_power (A, p, t = 2, itmax = 5, compute_v = False, compute_w = False, structure = None) protected
Efficiently estimate the 1-norm of A^p.
Parameters
----------
A : ndarray
    Matrix whose 1-norm of a power is to be computed.
p : int
    Non-negative integer power.
t : int, optional
    A positive parameter controlling the tradeoff between
    accuracy versus time and memory usage.
    Larger values take longer and use more memory
    but give more accurate output.
itmax : int, optional
    Use at most this many iterations.
compute_v : bool, optional
    Request a norm-maximizing linear operator input vector if True.
compute_w : bool, optional
    Request a norm-maximizing linear operator output vector if True.
Returns
-------
est : float
    An underestimate of the 1-norm of the sparse matrix.
v : ndarray, optional
    The vector such that ||Av||_1 == est*||v||_1.
    It can be thought of as an input to the linear operator
    that gives an output with particularly large norm.
w : ndarray, optional
    The vector Av which has relatively large 1-norm.
    It can be thought of as an output of the linear operator
    that is relatively large in norm compared to the input.
Definition at line 253 of file _matfuncs.py.
Referenced by scipy.sparse.linalg._matfuncs._ExpmPadeHelper.__init__().
_onenormest_product()
scipy.sparse.linalg._matfuncs._onenormest_product (operator_seq, t = 2, itmax = 5, compute_v = False, compute_w = False, structure = None) protected
Efficiently estimate the 1-norm of the matrix product of the args.
Parameters
----------
operator_seq : linear operator sequence
    Matrices whose 1-norm of product is to be computed.
t : int, optional
    A positive parameter controlling the tradeoff between
    accuracy versus time and memory usage.
    Larger values take longer and use more memory
    but give more accurate output.
itmax : int, optional
    Use at most this many iterations.
compute_v : bool, optional
    Request a norm-maximizing linear operator input vector if True.
compute_w : bool, optional
    Request a norm-maximizing linear operator output vector if True.
structure : str, optional
    A string describing the structure of all operators.
    Only `upper_triangular` is currently supported.
Returns
-------
est : float
    An underestimate of the 1-norm of the sparse matrix.
v : ndarray, optional
    The vector such that ||Av||_1 == est*||v||_1.
    It can be thought of as an input to the linear operator
    that gives an output with particularly large norm.
w : ndarray, optional
    The vector Av which has relatively large 1-norm.
    It can be thought of as an output of the linear operator
    that is relatively large in norm compared to the input.
Definition at line 294 of file _matfuncs.py.
Referenced by scipy.sparse.linalg._matfuncs._ExpmPadeHelper.__init__().
_smart_matrix_product()
scipy.sparse.linalg._matfuncs._smart_matrix_product (A, B, alpha = None, structure = None) protected
A matrix product that knows about sparse and structured matrices.
Parameters
----------
A : 2d ndarray
    First matrix.
B : 2d ndarray
    Second matrix.
alpha : float
    The matrix product will be scaled by this constant.
structure : str, optional
    A string describing the structure of both matrices `A` and `B`.
    Only `upper_triangular` is currently supported.
Returns
-------
M : 2d ndarray
    Matrix product of A and B.
Definition at line 127 of file _matfuncs.py.
References scipy.sparse._base.issparse().
Referenced by scipy.sparse.linalg._matfuncs._ExpmPadeHelper.__init__(), scipy.sparse.linalg._matfuncs.MatrixPowerOperator._matmat(), and scipy.sparse.linalg._matfuncs.ProductOperator._matmat().
_solve_P_Q()
scipy.sparse.linalg._matfuncs._solve_P_Q (U, V, structure = None) protected
A helper function for expm_2009.
Parameters
----------
U : ndarray
    Pade numerator.
V : ndarray
    Pade denominator.
structure : str, optional
    A string describing the structure of both matrices `U` and `V`.
    Only `upper_triangular` is currently supported.
Notes
-----
The `structure` argument is inspired by similar args
for theano and cvxopt functions.
Definition at line 683 of file _matfuncs.py.
References scipy.sparse._base.issparse(), and scipy.sparse.linalg._dsolve.linsolve.spsolve().
Referenced by expm().
expm()
scipy.sparse.linalg._matfuncs.expm (A)
Compute the matrix exponential using Pade approximation.
Parameters
----------
A : (M,M) array_like or sparse matrix
    2D Array or Matrix (sparse or dense) to be exponentiated
Returns
-------
expA : (M,M) ndarray
    Matrix exponential of `A`
Notes
-----
This is algorithm (6.1) which is a simplification of algorithm (5.1).
.. versionadded:: 0.12.0
References
----------
.. [1] Awad H. Al-Mohy and Nicholas J. Higham (2009)
       "A New Scaling and Squaring Algorithm for the Matrix Exponential."
       SIAM Journal on Matrix Analysis and Applications.
       31 (3). pp. 970-989. ISSN 1095-7162
Examples
--------
>>> from scipy.sparse import csc_matrix
>>> from scipy.sparse.linalg import expm
>>> A = csc_matrix([[1, 0, 0], [0, 2, 0], [0, 0, 3]])
>>> A.toarray()
array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]], dtype=int64)
>>> Aexp = expm(A)
>>> Aexp
<3x3 sparse matrix of type '<class 'numpy.float64'>'
    with 3 stored elements in Compressed Sparse Column format>
>>> Aexp.toarray()
array([[  2.71828183,   0.        ,   0.        ],
       [  0.        ,   7.3890561 ,   0.        ],
       [  0.        ,   0.        ,  20.08553692]])
Definition at line 545 of file _matfuncs.py.
References _ell(), _fragment_2_1(), _solve_P_Q(), and scipy.sparse._base.issparse().
inv()
scipy.sparse.linalg._matfuncs.inv (A)
Compute the inverse of a sparse matrix
Parameters
----------
A : (M, M) sparse matrix
    square matrix to be inverted
Returns
-------
Ainv : (M, M) sparse matrix
    inverse of `A`
Notes
-----
This computes the sparse inverse of `A`. If the inverse of `A` is expected
to be non-sparse, it will likely be faster to convert `A` to dense and use
`scipy.linalg.inv`.
Examples
--------
>>> from scipy.sparse import csc_matrix
>>> from scipy.sparse.linalg import inv
>>> A = csc_matrix([[1., 0.], [1., 2.]])
>>> Ainv = inv(A)
>>> Ainv
<2x2 sparse matrix of type '<class 'numpy.float64'>'
    with 3 stored elements in Compressed Sparse Column format>
>>> A.dot(Ainv)
<2x2 sparse matrix of type '<class 'numpy.float64'>'
    with 2 stored elements in Compressed Sparse Column format>
>>> A.dot(Ainv).toarray()
array([[ 1.,  0.],
       [ 0.,  1.]])
.. versionadded:: 0.12.0
Definition at line 30 of file _matfuncs.py.
References scipy.sparse.linalg._dsolve.linsolve.spsolve().
Referenced by scipy.sparse.linalg._eigen.lobpcg.lobpcg._b_orthonormalize().
Variable Documentation
__all__
list scipy.sparse.linalg._matfuncs.__all__ = ['expm', 'inv'] private
Definition at line 11 of file _matfuncs.py.
UPPER_TRIANGULAR
str scipy.sparse.linalg._matfuncs.UPPER_TRIANGULAR = 'upper_triangular'
Definition at line 27 of file _matfuncs.py.