Code Cloning Analysis: matplotlib._mathtext.AutoHeightChar Class Reference
matplotlib._mathtext.AutoHeightChar Class Reference
Public Member Functions
__init__ (self, str c, float height, float depth, ParserState state, bool always=False, float|None factor=None)
Public Member Functions inherited from matplotlib._mathtext.Hlist
__init__ (self, T.Sequence[Node] elements, float w=0.0, T.Literal['additional', 'exactly'] m='additional', bool do_kern=True)
None kern (self)
None hpack (self, float w=0.0, T.Literal['additional', 'exactly'] m='additional')
Public Member Functions inherited from matplotlib._mathtext.List
__init__ (self, T.Sequence[Node] elements)
str __repr__ (self)
None shrink (self)
Public Member Functions inherited from matplotlib._mathtext.Box
None __init__ (self, float width, float height, float depth)
None render (self, Output output, float x1, float y1, float x2, float y2)
Public Member Functions inherited from matplotlib._mathtext.Node
None __init__ (self)
str __repr__ (self)
float get_kerning (self, Node|None next)
Additional Inherited Members
Public Attributes inherited from matplotlib._mathtext.List
int shift_amount = 0.
list children = [*elements]
int glue_set = 0.
int glue_sign = 0
int glue_order = 0
int glue_ratio = 0.
Public Attributes inherited from matplotlib._mathtext.Box
width = width
height = height
depth = depth
Public Attributes inherited from matplotlib._mathtext.Node
int size = 0
Protected Member Functions inherited from matplotlib._mathtext.List
None _set_glue (self, float x, int sign, list[float] totals, str error_type)
Detailed Description
A character as close to the given height and depth as possible.
When using a font with multiple height versions of some characters (such as
the BaKoMa fonts), the correct glyph will be selected, otherwise this will
always just return a scaled version of the glyph.
Definition at line 1523 of file _mathtext.py.
Constructor & Destructor Documentation
__init__()
matplotlib._mathtext.AutoHeightChar.__init__ (self, str c, float height, float depth, ParserState state, bool always = False, float | None factor = None)
Definition at line 1532 of file _mathtext.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/_mathtext.py