Code Cloning Analysis: numpy.core.arrayprint.StructuredVoidFormat Class Reference
numpy.core.arrayprint.StructuredVoidFormat Class Reference
Public Member Functions
__init__ (self, format_functions)
from_data (cls, data, **options)
__call__ (self, x)
Public Attributes
format_functions = format_functions
Detailed Description
Formatter for structured np.void objects.
This does not work on structured alias types like np.dtype(('i4', 'i2,i2')),
as alias scalars lose their field information, and the implementation
relies upon np.void.__getitem__.
Definition at line 1367 of file arrayprint.py.
Constructor & Destructor Documentation
__init__()
numpy.core.arrayprint.StructuredVoidFormat.__init__ (self, format_functions)
Definition at line 1375 of file arrayprint.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__call__()
numpy.core.arrayprint.StructuredVoidFormat.__call__ (self, x)
Definition at line 1392 of file arrayprint.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), and scipy.interpolate._fitpack2.SphereBivariateSpline.ev().
from_data()
numpy.core.arrayprint.StructuredVoidFormat.from_data (cls, data, ** options)
This is a second way to initialize StructuredVoidFormat, using the raw data
as input. Added to avoid changing the signature of __init__.
Definition at line 1379 of file arrayprint.py.
References numpy.core.arrayprint._get_format_function(), and format_functions.
Member Data Documentation
format_functions
numpy.core.arrayprint.StructuredVoidFormat.format_functions = format_functions
Definition at line 1376 of file arrayprint.py.
Referenced by from_data().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/core/arrayprint.py