Code Cloning Analysis: matplotlib.backends.backend_gtk3agg.FigureCanvasGTK3Agg Class Reference
matplotlib.backends.backend_gtk3agg.FigureCanvasGTK3Agg Class Reference
Public Member Functions
__init__ (self, figure)
on_draw_event (self, widget, ctx)
blit (self, bbox=None)
Public Member Functions inherited from matplotlib.backends.backend_agg.FigureCanvasAgg
copy_from_bbox (self, bbox)
restore_region (self, region, bbox=None, xy=None)
draw (self)
get_renderer (self)
tostring_argb (self)
buffer_rgba (self)
print_raw (self, filename_or_obj, *, metadata=None)
print_png (self, filename_or_obj, *, metadata=None, pil_kwargs=None)
print_to_buffer (self)
print_jpg (self, filename_or_obj, *, metadata=None, pil_kwargs=None)
print_tif (self, filename_or_obj, *, metadata=None, pil_kwargs=None)
print_webp (self, filename_or_obj, *, metadata=None, pil_kwargs=None)
Public Member Functions inherited from matplotlib.backend_bases.FigureCanvasBase
supports_blit (cls)
__init__ (self, figure=None)
new_manager (cls, figure, num)
is_saving (self)
inaxes (self, xy)
grab_mouse (self, ax)
release_mouse (self, ax)
set_cursor (self, cursor)
draw_idle (self, *args, **kwargs)
device_pixel_ratio (self)
get_width_height (self, *, physical=False)
get_supported_filetypes (cls)
get_supported_filetypes_grouped (cls)
print_figure (self, filename, dpi=None, facecolor=None, edgecolor=None, orientation='portrait', format=None, *, bbox_inches=None, pad_inches=None, bbox_extra_artists=None, backend=None, **kwargs)
get_default_filetype (cls)
get_default_filename (self)
mpl_connect (self, s, func)
mpl_disconnect (self, cid)
new_timer (self, interval=None, callbacks=None)
flush_events (self)
start_event_loop (self, timeout=0)
stop_event_loop (self)
Public Member Functions inherited from matplotlib.backends.backend_gtk3.FigureCanvasGTK3
__init__ (self, figure=None)
destroy (self)
set_cursor (self, cursor)
scroll_event (self, widget, event)
button_press_event (self, widget, event)
button_release_event (self, widget, event)
key_press_event (self, widget, event)
key_release_event (self, widget, event)
motion_notify_event (self, widget, event)
enter_notify_event (self, widget, event)
leave_notify_event (self, widget, event)
size_allocate (self, widget, allocation)
configure_event (self, widget, event)
draw (self)
draw_idle (self)
flush_events (self)
Protected Attributes
list _bbox_queue = []
Protected Attributes inherited from matplotlib.backend_bases.FigureCanvasBase
bool _is_idle_drawing = True
bool _is_saving = False
_button = None
_key = None
int _device_pixel_ratio = 1
bool _looping = True
Protected Attributes inherited from matplotlib.backends.backend_gtk3.FigureCanvasGTK3
int _idle_draw_id = 0
_rubberband_rect = None
_update_device_pixel_ratio
_post_draw
Additional Inherited Members
Public Attributes inherited from matplotlib.backends.backend_agg.FigureCanvasAgg
renderer = self.get_renderer()
Public Attributes inherited from matplotlib.backend_bases.FigureCanvasBase
figure = figure
manager = None
widgetlock = widgets.LockDraw()
mouse_grabber = None
toolbar = None
device_pixel_ratio
Public Attributes inherited from matplotlib.backends.backend_gtk3.FigureCanvasGTK3
scroll_event
button_press_event
button_release_event
configure_event
key_press_event
key_release_event
motion_notify_event
enter_notify_event
leave_notify_event
size_allocate
Static Public Attributes inherited from matplotlib.backends.backend_agg.FigureCanvasAgg
print_rgba = print_raw
print_jpeg = print_jpg
print_tiff = print_tif
Static Public Attributes inherited from matplotlib.backend_bases.FigureCanvasBase
required_interactive_framework = None
manager_class = _api.classproperty(lambda cls: FigureManagerBase)
list events
fixed_dpi = None
filetypes = _default_filetypes
Static Public Attributes inherited from matplotlib.backends.backend_gtk3.FigureCanvasGTK3
str required_interactive_framework = "gtk3"
manager_class = _api.classproperty(lambda cls: FigureManagerGTK3)
tuple event_mask
Protected Member Functions inherited from matplotlib.backends.backend_agg.FigureCanvasAgg
_print_pil (self, filename_or_obj, fmt, pil_kwargs, metadata=None)
Protected Member Functions inherited from matplotlib.backend_bases.FigureCanvasBase
_fix_ipython_backend2gui (cls)
_idle_draw_cntx (self)
_set_device_pixel_ratio (self, ratio)
_switch_canvas_and_return_print_method (self, fmt, backend=None)
Protected Member Functions inherited from matplotlib.backends.backend_gtk3.FigureCanvasGTK3
_mpl_coords (self, event=None)
_get_key (self, event)
_update_device_pixel_ratio (self, *args, **kwargs)
_draw_rubberband (self, rect)
_post_draw (self, widget, ctx)
Static Protected Member Functions inherited from matplotlib.backends.backend_gtk3.FigureCanvasGTK3
_mpl_buttons (event_state)
_mpl_modifiers (event_state, *, exclude=None)
Static Protected Attributes inherited from matplotlib.backends.backend_agg.FigureCanvasAgg
_lastKey = None
Static Protected Attributes inherited from matplotlib.backend_bases.FigureCanvasBase
_timer_cls = TimerBase
Properties inherited from matplotlib.backend_bases.FigureCanvasBase
callbacks = property(lambda self: self.figure._canvas_callbacks)
button_pick_id = property(lambda self: self.figure._button_pick_id)
scroll_pick_id = property(lambda self: self.figure._scroll_pick_id)
Detailed Description
Definition at line 10 of file backend_gtk3agg.py.
Constructor & Destructor Documentation
__init__()
matplotlib.backends.backend_gtk3agg.FigureCanvasGTK3Agg.__init__ (self, figure)
Definition at line 12 of file backend_gtk3agg.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
blit()
matplotlib.backends.backend_gtk3agg.FigureCanvasGTK3Agg.blit (self, bbox = None)
Blit the canvas in bbox (default entire canvas).
Reimplemented from matplotlib.backend_bases.FigureCanvasBase.
Definition at line 55 of file backend_gtk3agg.py.
References _bbox_queue, matplotlib.backend_bases.FigureCanvasBase.device_pixel_ratio, and matplotlib.backend_bases.FigureCanvasBase.figure.
on_draw_event()
matplotlib.backends.backend_gtk3agg.FigureCanvasGTK3Agg.on_draw_event (self, widget, ctx)
Reimplemented from matplotlib.backends.backend_gtk3.FigureCanvasGTK3.
Definition at line 16 of file backend_gtk3agg.py.
Referenced by matplotlib.backends.backend_gtk4.FigureCanvasGTK4._mpl_coords().
Member Data Documentation
_bbox_queue
matplotlib.backends.backend_gtk3agg.FigureCanvasGTK3Agg._bbox_queue = [] protected
Definition at line 14 of file backend_gtk3agg.py.
Referenced by blit().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/backends/backend_gtk3agg.py