Code Cloning Analysis: fontTools.otlLib.builder.AlternateSubstBuilder Class Reference
fontTools.otlLib.builder.AlternateSubstBuilder Class Reference
Public Member Functions
__init__ (self, font, location)
equals (self, other)
build (self)
getAlternateGlyphs (self)
add_subtable_break (self, location)
Public Member Functions inherited from fontTools.otlLib.builder.LookupBuilder
__init__ (self, font, location, table, lookup_type, extension=False)
promote_lookup_type (self, is_named_lookup)
inferGlyphClasses (self)
buildLookup_ (self, subtables)
buildMarkClasses_ (self, marks)
setBacktrackCoverage_ (self, prefix, subtable)
setLookAheadCoverage_ (self, suffix, subtable)
setInputCoverage_ (self, glyphs, subtable)
setCoverage_ (self, glyphs, subtable)
build_subst_subtables (self, mapping, klass)
bool can_add_mapping (self, _mapping)
Public Attributes
alternates = OrderedDict()
Public Attributes inherited from fontTools.otlLib.builder.LookupBuilder
font = font
glyphMap = font.getReverseGlyphMap()
location = location
table
lookup_type = table, lookup_type
int lookupflag = 0
markFilterSet = None
lookup_index = None
extension = extension
Additional Inherited Members
Static Public Attributes inherited from fontTools.otlLib.builder.LookupBuilder
str SUBTABLE_BREAK_ = "SUBTABLE_BREAK"
Detailed Description
Builds an Alternate Substitution (GSUB3) lookup.
Users are expected to manually add alternate glyph substitutions to
the ``alternates`` attribute after the object has been initialized,
e.g.::
    builder.alternates["A"] = ["A.alt1", "A.alt2"]
Attributes:
    font (``fontTools.TTLib.TTFont``): A font object.
    location: A string or tuple representing the location in the original
        source which produced this lookup.
    alternates: An ordered dictionary of alternates, mapping glyph names
        to a list of names of alternates.
    lookupflag (int): The lookup's flag
    markFilterSet: Either ``None`` if no mark filtering set is used, or
        an integer representing the filtering set to be used for this
        lookup. If a mark filtering set is provided,
        `LOOKUP_FLAG_USE_MARK_FILTERING_SET` will be set on the lookup's
        flags.
Definition at line 264 of file builder.py.
Constructor & Destructor Documentation
__init__()
fontTools.otlLib.builder.AlternateSubstBuilder.__init__ (self, font, location)
Definition at line 287 of file builder.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
add_subtable_break()
fontTools.otlLib.builder.AlternateSubstBuilder.add_subtable_break (self, location)
Add an explicit subtable break.
Args:
    location: A string or tuple representing the location in the
        original source which produced this break, or ``None`` if
        no location is provided.
Reimplemented from fontTools.otlLib.builder.LookupBuilder.
Definition at line 309 of file builder.py.
References alternates, and fontTools.otlLib.builder.LookupBuilder.SUBTABLE_BREAK_.
build()
fontTools.otlLib.builder.AlternateSubstBuilder.build (self)
Build the lookup.
Returns:
    An ``otTables.Lookup`` object representing the alternate
    substitution lookup.
Definition at line 294 of file builder.py.
References alternates, fontTools.otlLib.builder.LookupBuilder.build_subst_subtables(), and fontTools.otlLib.builder.LookupBuilder.buildLookup_().
equals()
fontTools.otlLib.builder.AlternateSubstBuilder.equals (self, other)
Reimplemented from fontTools.otlLib.builder.LookupBuilder.
Definition at line 291 of file builder.py.
Referenced by pandas.core.indexes.base.Index._join_level(), pandas.core.indexes.base.Index.difference(), pandas.core.indexes.base.Index.get_indexer(), pandas.core.indexes.base.Index.identical(), pandas.core.indexes.base.Index.intersection(), pandas.core.indexes.base.Index.reindex(), and pandas.core.indexes.base.Index.union().
getAlternateGlyphs()
fontTools.otlLib.builder.AlternateSubstBuilder.getAlternateGlyphs (self)
Helper for building 'aalt' features.
Reimplemented from fontTools.otlLib.builder.LookupBuilder.
Definition at line 306 of file builder.py.
References alternates.
Member Data Documentation
alternates
fontTools.otlLib.builder.AlternateSubstBuilder.alternates = OrderedDict()
Definition at line 289 of file builder.py.
Referenced by add_subtable_break(), build(), and getAlternateGlyphs().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/otlLib/builder.py