Code Cloning Analysis: pip._vendor.pyparsing.util.LRUMemo Class Reference
pip._vendor.pyparsing.util.LRUMemo Class Reference
Public Member Functions
__init__ (self, capacity)
__getitem__ (self, key)
__setitem__ (self, key, value)
__delitem__ (self, key)
clear (self)
Protected Attributes
_capacity = capacity
dict _active = {}
_memory = collections.OrderedDict()
Detailed Description
A memoizing mapping that retains `capacity` deleted items
The memo tracks retained items by their access order; once `capacity` items
are retained, the least recently used item is discarded.
Definition at line 129 of file util.py.
Constructor & Destructor Documentation
__init__()
pip._vendor.pyparsing.util.LRUMemo.__init__ (self, capacity)
Definition at line 137 of file util.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
__delitem__()
pip._vendor.pyparsing.util.LRUMemo.__delitem__ (self, key)
Definition at line 153 of file util.py.
__getitem__()
pip._vendor.pyparsing.util.LRUMemo.__getitem__ (self, key)
Definition at line 142 of file util.py.
__setitem__()
pip._vendor.pyparsing.util.LRUMemo.__setitem__ (self, key, value)
Definition at line 149 of file util.py.
clear()
pip._vendor.pyparsing.util.LRUMemo.clear (self)
Definition at line 163 of file util.py.
Referenced by matplotlib.projections.geo.AitoffAxes.InvertedAitoffTransform.inverted(), matplotlib.projections.geo.HammerAxes.InvertedHammerTransform.inverted(), matplotlib.projections.geo.LambertAxes.InvertedLambertTransform.inverted(), and matplotlib.projections.geo.MollweideAxes.InvertedMollweideTransform.inverted().
Member Data Documentation
_active
dict pip._vendor.pyparsing.util.LRUMemo._active = {} protected
Definition at line 139 of file util.py.
_capacity
pip._vendor.pyparsing.util.LRUMemo._capacity = capacity protected
Definition at line 138 of file util.py.
_memory
pip._vendor.pyparsing.util.LRUMemo._memory = collections.OrderedDict() protected
Definition at line 140 of file util.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pip/_vendor/pyparsing/util.py