Code Cloning Analysis: pip._vendor.pygments.formatters.bbcode.BBCodeFormatter Class Reference
pip._vendor.pygments.formatters.bbcode.BBCodeFormatter Class Reference
Public Member Functions
__init__ (self, **options)
format_unencoded (self, tokensource, outfile)
Public Member Functions inherited from pip._vendor.pygments.formatter.Formatter
__init__ (self, **options)
get_style_defs (self, arg='')
format (self, tokensource, outfile)
Public Attributes
dict styles = {}
Public Attributes inherited from pip._vendor.pygments.formatter.Formatter
style = _lookup_style(options.get('style', 'default'))
full = get_bool_opt(options, 'full', False)
title = options.get('title', '')
str encoding = options.get('encoding', None) or None
options = options
Protected Member Functions
_make_styles (self)
Protected Attributes
_code = get_bool_opt(options, 'codetag', False)
_mono = get_bool_opt(options, 'monofont', False)
Additional Inherited Members
Static Public Attributes inherited from pip._vendor.pygments.formatter.Formatter
name = None
list aliases = []
list filenames = []
bool unicodeoutput = True
Detailed Description
Format tokens with BBcodes. These formatting codes are used by many
bulletin boards, so you can highlight your sourcecode with pygments before
posting it there.
This formatter has no support for background colors and borders, as there
are no common BBcode tags for that.
Some board systems (e.g. phpBB) don't support colors in their [code] tag,
so you can't use the highlighting together with that tag.
Text in a [code] tag usually is shown with a monospace font (which this
formatter can do with the ``monofont`` option) and no spaces (which you
need for indentation) are removed.
Additional options accepted:
`style`
    The style to use, can be a string or a Style subclass (default:
    ``'default'``).
`codetag`
    If set to true, put the output into ``[code]`` tags (default:
    ``false``)
`monofont`
    If set to true, add a tag to show the code with a monospace font
    (default: ``false``).
Definition at line 18 of file bbcode.py.
Constructor & Destructor Documentation
__init__()
pip._vendor.pygments.formatters.bbcode.BBCodeFormatter.__init__ (self, ** options)
Definition at line 51 of file bbcode.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
_make_styles()
pip._vendor.pygments.formatters.bbcode.BBCodeFormatter._make_styles (self) protected
Definition at line 59 of file bbcode.py.
format_unencoded()
pip._vendor.pygments.formatters.bbcode.BBCodeFormatter.format_unencoded (self, tokensource, outfile)
Definition at line 78 of file bbcode.py.
Referenced by pip._vendor.pygments.formatter.Formatter.format().
Member Data Documentation
_code
pip._vendor.pygments.formatters.bbcode.BBCodeFormatter._code = get_bool_opt(options, 'codetag', False) protected
Definition at line 53 of file bbcode.py.
_mono
pip._vendor.pygments.formatters.bbcode.BBCodeFormatter._mono = get_bool_opt(options, 'monofont', False) protected
Definition at line 54 of file bbcode.py.
styles
dict pip._vendor.pygments.formatters.bbcode.BBCodeFormatter.styles = {}
Definition at line 56 of file bbcode.py.
Referenced by pip._vendor.pygments.formatters.img.ImageFormatter.__init__(), pip._vendor.pygments.formatters.img.ImageFormatter._create_drawables(), and pip._vendor.rich.theme.Theme.config().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pip/_vendor/pygments/formatters/bbcode.py