Code Cloning Analysis: fontTools.misc.arrayTools Namespace Reference
fontTools.misc.arrayTools Namespace Reference
Classes
class Vector
Functions
calcBounds (array)
calcIntBounds (array, round=otRound)
updateBounds (bounds, p, min=min, max=max)
pointInRect (p, rect)
pointsInRect (array, rect)
vectorLength (vector)
asInt16 (array)
normRect (rect)
scaleRect (rect, x, y)
offsetRect (rect, dx, dy)
insetRect (rect, dx, dy)
sectRect (rect1, rect2)
unionRect (rect1, rect2)
rectCenter (rect)
rectArea (rect)
intRect (rect)
quantizeRect (rect, factor=1)
pairwise (iterable, reverse=False)
_test ()
Detailed Description
Routines for calculating bounding boxes, point in rectangle calculations and
so on.
Function Documentation
_test()
fontTools.misc.arrayTools._test () protected
>>> import math
>>> calcBounds([])
(0, 0, 0, 0)
>>> calcBounds([(0, 40), (0, 100), (50, 50), (80, 10)])
(0, 10, 80, 100)
>>> updateBounds((0, 0, 0, 0), (100, 100))
(0, 0, 100, 100)
>>> pointInRect((50, 50), (0, 0, 100, 100))
True
>>> pointInRect((0, 0), (0, 0, 100, 100))
True
>>> pointInRect((100, 100), (0, 0, 100, 100))
True
>>> not pointInRect((101, 100), (0, 0, 100, 100))
True
>>> list(pointsInRect([(50, 50), (0, 0), (100, 100), (101, 100)], (0, 0, 100, 100)))
[True, True, True, False]
>>> vectorLength((3, 4))
5.0
>>> vectorLength((1, 1)) == math.sqrt(2)
True
>>> list(asInt16([0, 0.1, 0.5, 0.9]))
[0, 0, 1, 1]
>>> normRect((0, 10, 100, 200))
(0, 10, 100, 200)
>>> normRect((100, 200, 0, 10))
(0, 10, 100, 200)
>>> scaleRect((10, 20, 50, 150), 1.5, 2)
(15.0, 40, 75.0, 300)
>>> offsetRect((10, 20, 30, 40), 5, 6)
(15, 26, 35, 46)
>>> insetRect((10, 20, 50, 60), 5, 10)
(15, 30, 45, 50)
>>> insetRect((10, 20, 50, 60), -5, -10)
(5, 10, 55, 70)
>>> intersects, rect = sectRect((0, 10, 20, 30), (0, 40, 20, 50))
>>> not intersects
True
>>> intersects, rect = sectRect((0, 10, 20, 30), (5, 20, 35, 50))
>>> intersects
1
>>> rect
(5, 20, 20, 30)
>>> unionRect((0, 10, 20, 30), (0, 40, 20, 50))
(0, 10, 20, 50)
>>> rectCenter((0, 0, 100, 200))
(50.0, 100.0)
>>> rectCenter((0, 0, 100, 199.0))
(50.0, 99.5)
>>> intRect((0.9, 2.9, 3.1, 4.1))
(0, 2, 4, 5)
Definition at line 364 of file arrayTools.py.
asInt16()
fontTools.misc.arrayTools.asInt16 (array)
Round a list of floats to 16-bit signed integers.
Args:
    array: List of float values.
Returns:
    A list of rounded integers.
Definition at line 110 of file arrayTools.py.
calcBounds()
fontTools.misc.arrayTools.calcBounds (array)
Calculate the bounding rectangle of a 2D points array.
Args:
    array: A sequence of 2D tuples.
Returns:
    A four-item tuple representing the bounding rectangle ``(xMin, yMin, xMax, yMax)``.
Definition at line 11 of file arrayTools.py.
Referenced by calcIntBounds().
calcIntBounds()
fontTools.misc.arrayTools.calcIntBounds (array, round = otRound)
Calculate the integer bounding rectangle of a 2D points array.
Values are rounded to closest integer towards ``+Infinity`` using the
:func:`fontTools.misc.fixedTools.otRound` function by default, unless
an optional ``round`` function is passed.
Args:
    array: A sequence of 2D tuples.
    round: A rounding function of type ``f(x: float) -> int``.
Returns:
    A four-item tuple of integers representing the bounding rectangle:
    ``(xMin, yMin, xMax, yMax)``.
Definition at line 27 of file arrayTools.py.
References calcBounds().
insetRect()
fontTools.misc.arrayTools.insetRect (rect, dx, dy)
Inset a bounding box rectangle on all sides.
Args:
    rect: A bounding rectangle expressed as a tuple
        ``(xMin, yMin, xMax, yMax)``.
    dx: Amount to inset the rectangle along the X axis.
    dY: Amount to inset the rectangle along the Y axis.
Returns:
    An inset bounding rectangle.
Definition at line 173 of file arrayTools.py.
intRect()
fontTools.misc.arrayTools.intRect (rect)
Round a rectangle to integer values.
Guarantees that the resulting rectangle is NOT smaller than the original.
Args:
    rect: Bounding rectangle, expressed as tuples
        ``(xMin, yMin, xMax, yMax)``.
Returns:
    A rounded bounding rectangle.
Definition at line 267 of file arrayTools.py.
normRect()
fontTools.misc.arrayTools.normRect (rect)
Normalize a bounding box rectangle.
This function "turns the rectangle the right way up", so that the following
holds::
    xMin <= xMax and yMin <= yMax
Args:
    rect: A bounding rectangle expressed as a tuple
        ``(xMin, yMin, xMax, yMax)``.
Returns:
    A normalized bounding rectangle.
Definition at line 122 of file arrayTools.py.
Referenced by quantizeRect().
offsetRect()
fontTools.misc.arrayTools.offsetRect (rect, dx, dy)
Offset a bounding box rectangle.
Args:
    rect: A bounding rectangle expressed as a tuple
        ``(xMin, yMin, xMax, yMax)``.
    dx: Amount to offset the rectangle along the X axis.
    dY: Amount to offset the rectangle along the Y axis.
Returns:
    An offset bounding rectangle.
Definition at line 157 of file arrayTools.py.
pairwise()
fontTools.misc.arrayTools.pairwise (iterable, reverse = False)
Iterate over current and next items in iterable.
Args:
    iterable: An iterable
    reverse: If true, iterate in reverse order.
Returns:
    A iterable yielding two elements per iteration.
Example:
    >>> tuple(pairwise([]))
    ()
    >>> tuple(pairwise([], reverse=True))
    ()
    >>> tuple(pairwise([0]))
    ((0, 0),)
    >>> tuple(pairwise([0], reverse=True))
    ((0, 0),)
    >>> tuple(pairwise([0, 1]))
    ((0, 1), (1, 0))
    >>> tuple(pairwise([0, 1], reverse=True))
    ((1, 0), (0, 1))
    >>> tuple(pairwise([0, 1, 2]))
    ((0, 1), (1, 2), (2, 0))
    >>> tuple(pairwise([0, 1, 2], reverse=True))
    ((2, 1), (1, 0), (0, 2))
    >>> tuple(pairwise(['a', 'b', 'c', 'd']))
    (('a', 'b'), ('b', 'c'), ('c', 'd'), ('d', 'a'))
    >>> tuple(pairwise(['a', 'b', 'c', 'd'], reverse=True))
    (('d', 'c'), ('c', 'b'), ('b', 'a'), ('a', 'd'))
Definition at line 317 of file arrayTools.py.
pointInRect()
fontTools.misc.arrayTools.pointInRect (p, rect)
Test if a point is inside a bounding rectangle.
Args:
    p: A 2D tuple representing a point.
    rect: A bounding rectangle expressed as a tuple
        ``(xMin, yMin, xMax, yMax)``.
Returns:
    ``True`` if the point is inside the rectangle, ``False`` otherwise.
Definition at line 64 of file arrayTools.py.
pointsInRect()
fontTools.misc.arrayTools.pointsInRect (array, rect)
Determine which points are inside a bounding rectangle.
Args:
    array: A sequence of 2D tuples.
    rect: A bounding rectangle expressed as a tuple
        ``(xMin, yMin, xMax, yMax)``.
Returns:
    A list containing the points inside the rectangle.
Definition at line 80 of file arrayTools.py.
quantizeRect()
fontTools.misc.arrayTools.quantizeRect (rect, factor = 1)
>>> bounds = (72.3, -218.4, 1201.3, 919.1)
>>> quantizeRect(bounds)
(72, -219, 1202, 920)
>>> quantizeRect(bounds, factor=10)
(70, -220, 1210, 920)
>>> quantizeRect(bounds, factor=100)
(0, -300, 1300, 1000)
Definition at line 287 of file arrayTools.py.
References normRect().
rectArea()
fontTools.misc.arrayTools.rectArea (rect)
Determine rectangle area.
Args:
    rect: Bounding rectangle, expressed as tuples
        ``(xMin, yMin, xMax, yMax)``.
Returns:
    The area of the rectangle.
Definition at line 253 of file arrayTools.py.
rectCenter()
fontTools.misc.arrayTools.rectCenter (rect)
Determine rectangle center.
Args:
    rect: Bounding rectangle, expressed as tuples
        ``(xMin, yMin, xMax, yMax)``.
Returns:
    A 2D tuple representing the point at the center of the rectangle.
Definition at line 239 of file arrayTools.py.
scaleRect()
fontTools.misc.arrayTools.scaleRect (rect, x, y)
Scale a bounding box rectangle.
Args:
    rect: A bounding rectangle expressed as a tuple
        ``(xMin, yMin, xMax, yMax)``.
    x: Factor to scale the rectangle along the X axis.
    Y: Factor to scale the rectangle along the Y axis.
Returns:
    A scaled bounding rectangle.
Definition at line 141 of file arrayTools.py.
sectRect()
fontTools.misc.arrayTools.sectRect (rect1, rect2)
Test for rectangle-rectangle intersection.
Args:
    rect1: First bounding rectangle, expressed as tuples
        ``(xMin, yMin, xMax, yMax)``.
    rect2: Second bounding rectangle.
Returns:
    A boolean and a rectangle.
    If the input rectangles intersect, returns ``True`` and the intersecting
    rectangle. Returns ``False`` and ``(0, 0, 0, 0)`` if the input
    rectangles don't intersect.
Definition at line 189 of file arrayTools.py.
unionRect()
fontTools.misc.arrayTools.unionRect (rect1, rect2)
Determine union of bounding rectangles.
Args:
    rect1: First bounding rectangle, expressed as tuples
        ``(xMin, yMin, xMax, yMax)``.
    rect2: Second bounding rectangle.
Returns:
    The smallest rectangle in which both input rectangles are fully
    enclosed.
Definition at line 216 of file arrayTools.py.
updateBounds()
fontTools.misc.arrayTools.updateBounds (bounds, p, min = min, max = max)
Add a point to a bounding rectangle.
Args:
    bounds: A bounding rectangle expressed as a tuple
        ``(xMin, yMin, xMax, yMax), or None``.
    p: A 2D tuple representing a point.
    min,max: functions to compute the minimum and maximum.
Returns:
    The updated bounding rectangle ``(xMin, yMin, xMax, yMax)``.
Definition at line 45 of file arrayTools.py.
vectorLength()
fontTools.misc.arrayTools.vectorLength (vector)
Calculate the length of the given vector.
Args:
    vector: A 2D tuple.
Returns:
    The Euclidean length of the vector.
Definition at line 97 of file arrayTools.py.