Code Cloning Analysis: fontTools.misc.filesystem._walk.BoundWalker Class Reference
fontTools.misc.filesystem._walk.BoundWalker Class Reference
Public Member Functions
__init__ (self, FS fs)
Iterator[str] files (self, str path="/")
Iterator[str] dirs (self, str path="/")
Protected Member Functions
Iterator[tuple[str, Info|None]] _iter_walk (self, str path, Collection[str]|None namespaces=None)
Iterator[str] _filter (self, Callable[[str, Info], bool] include=lambda path, True info, str path="/", Collection[str]|None namespaces=None)
Protected Attributes
_fs = fs
Detailed Description
Definition at line 16 of file _walk.py.
Constructor & Destructor Documentation
__init__()
fontTools.misc.filesystem._walk.BoundWalker.__init__ (self, FS fs)
Definition at line 17 of file _walk.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_filter()
Iterator[str] fontTools.misc.filesystem._walk.BoundWalker._filter (self, Callable[[str, Info], bool] include = lambda path, True info, str path = "/", Collection[str] | None namespaces = None) protected
Definition at line 40 of file _walk.py.
Referenced by _iter_walk(), numpy.testing._private.utils.suppress_warnings.filter(), and numpy.testing._private.utils.suppress_warnings.record().
_iter_walk()
Iterator[tuple[str, Info | None]] fontTools.misc.filesystem._walk.BoundWalker._iter_walk (self, str path, Collection[str] | None namespaces = None) protected
Walk files using a *breadth first* search.
Definition at line 20 of file _walk.py.
References _filter(), _fs, and _iter_walk().
Referenced by _iter_walk().
dirs()
Iterator[str] fontTools.misc.filesystem._walk.BoundWalker.dirs (self, str path = "/")
Definition at line 54 of file _walk.py.
files()
Iterator[str] fontTools.misc.filesystem._walk.BoundWalker.files (self, str path = "/")
Definition at line 51 of file _walk.py.
Member Data Documentation
_fs
fontTools.misc.filesystem._walk.BoundWalker._fs = fs protected
Definition at line 18 of file _walk.py.
Referenced by _iter_walk().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/misc/filesystem/_walk.py