Code Cloning Analysis: numpy.core.tests.test_multiarray.TestArrayInterface.Foo Class Reference
numpy.core.tests.test_multiarray.TestArrayInterface.Foo Class Reference
Public Member Functions
__init__ (self, value)
__float__ (self)
__array_interface__ (self)
Public Attributes
value = value
dict iface = {'typestr': 'f8'}
Detailed Description
Definition at line 8535 of file test_multiarray.py.
Constructor & Destructor Documentation
__init__()
numpy.core.tests.test_multiarray.TestArrayInterface.Foo.__init__ (self, value)
Definition at line 8536 of file test_multiarray.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__array_interface__()
numpy.core.tests.test_multiarray.TestArrayInterface.Foo.__array_interface__ (self)
Definition at line 8544 of file test_multiarray.py.
Referenced by numpy.ma.core.MaskedArray.__array_finalize__().
__float__()
numpy.core.tests.test_multiarray.TestArrayInterface.Foo.__float__ (self)
Definition at line 8540 of file test_multiarray.py.
Member Data Documentation
iface
dict numpy.core.tests.test_multiarray.TestArrayInterface.Foo.iface = {'typestr': 'f8'}
Definition at line 8538 of file test_multiarray.py.
value
numpy.core.tests.test_multiarray.TestArrayInterface.Foo.value = value
Definition at line 8537 of file test_multiarray.py.
Referenced by sklearn.externals.array_api_extra._lib._at._AtOp.__str__(), sklearn.externals.array_api_extra._lib._backends.Backend.__str__(), pip._vendor.rich._inspect.Inspect._render(), pip._internal.models.link.LinkHash.as_hashes(), pip._internal.models.link.LinkHash.find_hash_url_fragment(), pip._internal.models.link.LinkHash.is_hash_allowed(), pandas.core.computation.ops.Term.update(), and pandas.io.stata.StataMissingValue.value().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/core/tests/test_multiarray.py