Code Cloning Analysis: scipy.linalg._decomp Namespace Reference
scipy.linalg._decomp Namespace Reference
Functions
_make_complex_eigvecs (w, vin, dtype)
_make_eigvals (alpha, beta, homogeneous_eigvals)
_geneig (a1, b1, left, right, overwrite_a, overwrite_b, homogeneous_eigvals)
eig (a, b=None, left=False, right=True, overwrite_a=False, overwrite_b=False, check_finite=True, homogeneous_eigvals=False)
eigh (a, b=None, lower=True, eigvals_only=False, overwrite_a=False, overwrite_b=False, turbo=False, eigvals=None, type=1, check_finite=True, subset_by_index=None, subset_by_value=None, driver=None)
_check_select (select, select_range, max_ev, max_len)
eig_banded (a_band, lower=False, eigvals_only=False, overwrite_a_band=False, select='a', select_range=None, max_ev=0, check_finite=True)
eigvals (a, b=None, overwrite_a=False, check_finite=True, homogeneous_eigvals=False)
eigvalsh (a, b=None, lower=True, overwrite_a=False, overwrite_b=False, turbo=False, eigvals=None, type=1, check_finite=True, subset_by_index=None, subset_by_value=None, driver=None)
eigvals_banded (a_band, lower=False, overwrite_a_band=False, select='a', select_range=None, check_finite=True)
eigvalsh_tridiagonal (d, e, select='a', select_range=None, check_finite=True, tol=0., lapack_driver='auto')
eigh_tridiagonal (d, e, eigvals_only=False, select='a', select_range=None, check_finite=True, tol=0., lapack_driver='auto')
_check_info (info, driver, positive='did not converge(LAPACK info=%d)')
hessenberg (a, calc_q=False, overwrite_a=False, check_finite=True)
cdf2rdf (w, v)
Variables
list __all__
_I = cast['F'](1j)
dict _conv_dict
Function Documentation
_check_info()
scipy.linalg._decomp._check_info (info, driver, positive = 'did not converge (LAPACK info=%d)') protected
Check info return value.
Definition at line 1365 of file _decomp.py.
Referenced by _make_complex_eigvecs(), eig(), eig_banded(), eigh_tridiagonal(), and hessenberg().
_check_select()
scipy.linalg._decomp._check_select (select, select_range, max_ev, max_len) protected
Check that select is valid, convert to Fortran style.
Definition at line 627 of file _decomp.py.
Referenced by eig_banded(), and eigh_tridiagonal().
_geneig()
scipy.linalg._decomp._geneig (a1, b1, left, right, overwrite_a, overwrite_b, homogeneous_eigvals) protected
Definition at line 74 of file _decomp.py.
_make_complex_eigvecs()
scipy.linalg._decomp._make_complex_eigvecs (w, vin, dtype) protected
Produce complex-valued eigenvectors from LAPACK DGGEV real-valued output
Definition at line 34 of file _decomp.py.
References _check_info(), _make_complex_eigvecs(), and scipy.linalg.lapack.get_lapack_funcs().
Referenced by _make_complex_eigvecs(), and eig().
_make_eigvals()
scipy.linalg._decomp._make_eigvals (alpha, beta, homogeneous_eigvals) protected
Definition at line 48 of file _decomp.py.
cdf2rdf()
scipy.linalg._decomp.cdf2rdf (w, v)
Converts complex eigenvalues ``w`` and eigenvectors ``v`` to real
eigenvalues in a block diagonal form ``wr`` and the associated real
eigenvectors ``vr``, such that::
    vr @ wr = X @ vr
continues to hold, where ``X`` is the original array for which ``w`` and
``v`` are the eigenvalues and eigenvectors.
.. versionadded:: 1.1.0
Parameters
----------
w : (..., M) array_like
    Complex or real eigenvalues, an array or stack of arrays
    Conjugate pairs must not be interleaved, else the wrong result
    will be produced. So ``[1+1j, 1, 1-1j]`` will give a correct result,
    but ``[1+1j, 2+1j, 1-1j, 2-1j]`` will not.
v : (..., M, M) array_like
    Complex or real eigenvectors, a square array or stack of square arrays.
Returns
-------
wr : (..., M, M) ndarray
    Real diagonal block form of eigenvalues
vr : (..., M, M) ndarray
    Real eigenvectors associated with ``wr``
See Also
--------
eig : Eigenvalues and right eigenvectors for non-symmetric arrays
rsf2csf : Convert real Schur form to complex Schur form
Notes
-----
``w``, ``v`` must be the eigenstructure for some *real* matrix ``X``.
For example, obtained by ``w, v = scipy.linalg.eig(X)`` or
``w, v = numpy.linalg.eig(X)`` in which case ``X`` can also represent
stacked arrays.
.. versionadded:: 1.1.0
Examples
--------
>>> import numpy as np
>>> X = np.array([[1, 2, 3], [0, 4, 5], [0, -5, 4]])
>>> X
array([[ 1,  2,  3],
       [ 0,  4,  5],
       [ 0, -5,  4]])
>>> from scipy import linalg
>>> w, v = linalg.eig(X)
>>> w
array([ 1.+0.j,  4.+5.j,  4.-5.j])
>>> v
array([[ 1.00000+0.j     , -0.01906-0.40016j, -0.01906+0.40016j],
       [ 0.00000+0.j     ,  0.00000-0.64788j,  0.00000+0.64788j],
       [ 0.00000+0.j     ,  0.64788+0.j     ,  0.64788-0.j     ]])
>>> wr, vr = linalg.cdf2rdf(w, v)
>>> wr
array([[ 1.,  0.,  0.],
       [ 0.,  4.,  5.],
       [ 0., -5.,  4.]])
>>> vr
array([[ 1.     ,  0.40016, -0.01906],
       [ 0.     ,  0.64788,  0.     ],
       [ 0.     ,  0.     ,  0.64788]])
>>> vr @ wr
array([[ 1.     ,  1.69593,  1.9246 ],
       [ 0.     ,  2.59153,  3.23942],
       [ 0.     , -3.23942,  2.59153]])
>>> X @ vr
array([[ 1.     ,  1.69593,  1.9246 ],
       [ 0.     ,  2.59153,  3.23942],
       [ 0.     , -3.23942,  2.59153]])
Definition at line 1455 of file _decomp.py.
eig()
scipy.linalg._decomp.eig (a, b = None, left = False, right = True, overwrite_a = False, overwrite_b = False, check_finite = True, homogeneous_eigvals = False)
Solve an ordinary or generalized eigenvalue problem of a square matrix.
Find eigenvalues w and right or left eigenvectors of a general matrix::
    a   vr[:,i] = w[i]        b   vr[:,i]
    a.H vl[:,i] = w[i].conj() b.H vl[:,i]
where ``.H`` is the Hermitian conjugation.
Parameters
----------
a : (M, M) array_like
    A complex or real matrix whose eigenvalues and eigenvectors
    will be computed.
b : (M, M) array_like, optional
    Right-hand side matrix in a generalized eigenvalue problem.
    Default is None, identity matrix is assumed.
left : bool, optional
    Whether to calculate and return left eigenvectors.  Default is False.
right : bool, optional
    Whether to calculate and return right eigenvectors.  Default is True.
overwrite_a : bool, optional
    Whether to overwrite `a`; may improve performance.  Default is False.
overwrite_b : bool, optional
    Whether to overwrite `b`; may improve performance.  Default is False.
check_finite : bool, optional
    Whether to check that the input matrices contain only finite numbers.
    Disabling may give a performance gain, but may result in problems
    (crashes, non-termination) if the inputs do contain infinities or NaNs.
homogeneous_eigvals : bool, optional
    If True, return the eigenvalues in homogeneous coordinates.
    In this case ``w`` is a (2, M) array so that::
        w[1,i] a vr[:,i] = w[0,i] b vr[:,i]
    Default is False.
Returns
-------
w : (M,) or (2, M) double or complex ndarray
    The eigenvalues, each repeated according to its
    multiplicity. The shape is (M,) unless
    ``homogeneous_eigvals=True``.
vl : (M, M) double or complex ndarray
    The normalized left eigenvector corresponding to the eigenvalue
    ``w[i]`` is the column vl[:,i]. Only returned if ``left=True``.
vr : (M, M) double or complex ndarray
    The normalized right eigenvector corresponding to the eigenvalue
    ``w[i]`` is the column ``vr[:,i]``.  Only returned if ``right=True``.
Raises
------
LinAlgError
    If eigenvalue computation does not converge.
See Also
--------
eigvals : eigenvalues of general arrays
eigh : Eigenvalues and right eigenvectors for symmetric/Hermitian arrays.
eig_banded : eigenvalues and right eigenvectors for symmetric/Hermitian
    band matrices
eigh_tridiagonal : eigenvalues and right eiegenvectors for
    symmetric/Hermitian tridiagonal matrices
Examples
--------
>>> import numpy as np
>>> from scipy import linalg
>>> a = np.array([[0., -1.], [1., 0.]])
>>> linalg.eigvals(a)
array([0.+1.j, 0.-1.j])
>>> b = np.array([[0., 1.], [1., 1.]])
>>> linalg.eigvals(a, b)
array([ 1.+0.j, -1.+0.j])
>>> a = np.array([[3., 0., 0.], [0., 8., 0.], [0., 0., 7.]])
>>> linalg.eigvals(a, homogeneous_eigvals=True)
array([[3.+0.j, 8.+0.j, 7.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j]])
>>> a = np.array([[0., -1.], [1., 0.]])
>>> linalg.eigvals(a) == linalg.eig(a)[0]
array([ True,  True])
>>> linalg.eig(a, left=True, right=False)[1] # normalized left eigenvector
array([[-0.70710678+0.j        , -0.70710678-0.j        ],
       [-0.        +0.70710678j, -0.        -0.70710678j]])
>>> linalg.eig(a, left=False, right=True)[1] # normalized right eigenvector
array([[0.70710678+0.j        , 0.70710678-0.j        ],
       [0.        -0.70710678j, 0.        +0.70710678j]])
Definition at line 116 of file _decomp.py.
References _check_info(), scipy.linalg.lapack._compute_lwork(), scipy.linalg._misc._datacopied(), _make_complex_eigvecs(), and scipy.linalg.lapack.get_lapack_funcs().
Referenced by eigvals().
eig_banded()
scipy.linalg._decomp.eig_banded (a_band, lower = False, eigvals_only = False, overwrite_a_band = False, select = 'a', select_range = None, max_ev = 0, check_finite = True)
Solve real symmetric or complex Hermitian band matrix eigenvalue problem.
Find eigenvalues w and optionally right eigenvectors v of a::
    a v[:,i] = w[i] v[:,i]
    v.H v    = identity
The matrix a is stored in a_band either in lower diagonal or upper
diagonal ordered form:
    a_band[u + i - j, j] == a[i,j]        (if upper form; i <= j)
    a_band[    i - j, j] == a[i,j]        (if lower form; i >= j)
where u is the number of bands above the diagonal.
Example of a_band (shape of a is (6,6), u=2)::
    upper form:
    *   *   a02 a13 a24 a35
    *   a01 a12 a23 a34 a45
    a00 a11 a22 a33 a44 a55
    lower form:
    a00 a11 a22 a33 a44 a55
    a10 a21 a32 a43 a54 *
    a20 a31 a42 a53 *   *
Cells marked with * are not used.
Parameters
----------
a_band : (u+1, M) array_like
    The bands of the M by M matrix a.
lower : bool, optional
    Is the matrix in the lower form. (Default is upper form)
eigvals_only : bool, optional
    Compute only the eigenvalues and no eigenvectors.
    (Default: calculate also eigenvectors)
overwrite_a_band : bool, optional
    Discard data in a_band (may enhance performance)
select : {'a', 'v', 'i'}, optional
    Which eigenvalues to calculate
    ======  ========================================
    select  calculated
    ======  ========================================
    'a'     All eigenvalues
    'v'     Eigenvalues in the interval (min, max]
    'i'     Eigenvalues with indices min <= i <= max
    ======  ========================================
select_range : (min, max), optional
    Range of selected eigenvalues
max_ev : int, optional
    For select=='v', maximum number of eigenvalues expected.
    For other values of select, has no meaning.
    In doubt, leave this parameter untouched.
check_finite : bool, optional
    Whether to check that the input matrix contains only finite numbers.
    Disabling may give a performance gain, but may result in problems
    (crashes, non-termination) if the inputs do contain infinities or NaNs.
Returns
-------
w : (M,) ndarray
    The eigenvalues, in ascending order, each repeated according to its
    multiplicity.
v : (M, M) float or complex ndarray
    The normalized eigenvector corresponding to the eigenvalue w[i] is
    the column v[:,i].
Raises
------
LinAlgError
    If eigenvalue computation does not converge.
See Also
--------
eigvals_banded : eigenvalues for symmetric/Hermitian band matrices
eig : eigenvalues and right eigenvectors of general arrays.
eigh : eigenvalues and right eigenvectors for symmetric/Hermitian arrays
eigh_tridiagonal : eigenvalues and right eigenvectors for
    symmetric/Hermitian tridiagonal matrices
Examples
--------
>>> import numpy as np
>>> from scipy.linalg import eig_banded
>>> A = np.array([[1, 5, 2, 0], [5, 2, 5, 2], [2, 5, 3, 5], [0, 2, 5, 4]])
>>> Ab = np.array([[1, 2, 3, 4], [5, 5, 5, 0], [2, 2, 0, 0]])
>>> w, v = eig_banded(Ab, lower=True)
>>> np.allclose(A @ v - v @ np.diag(w), np.zeros((4, 4)))
True
>>> w = eig_banded(Ab, lower=True, eigvals_only=True)
>>> w
array([-4.26200532, -2.22987175,  3.95222349, 12.53965359])
Request only the eigenvalues between ``[-3, 4]``
>>> w, v = eig_banded(Ab, lower=True, select='v', select_range=[-3, 4])
>>> w
array([-2.22987175,  3.95222349])
Definition at line 659 of file _decomp.py.
References _check_info(), _check_select(), scipy.linalg._misc._datacopied(), and scipy.linalg.lapack.get_lapack_funcs().
Referenced by eigvals_banded().
eigh()
scipy.linalg._decomp.eigh (a, b = None, lower = True, eigvals_only = False, overwrite_a = False, overwrite_b = False, turbo = False, eigvals = None, type = 1, check_finite = True, subset_by_index = None, subset_by_value = None, driver = None)
Solve a standard or generalized eigenvalue problem for a complex
Hermitian or real symmetric matrix.
Find eigenvalues array ``w`` and optionally eigenvectors array ``v`` of
array ``a``, where ``b`` is positive definite such that for every
eigenvalue λ (i-th entry of w) and its eigenvector ``vi`` (i-th column of
``v``) satisfies::
                  a @ vi = λ * b @ vi
    vi.conj().T @ a @ vi = λ
    vi.conj().T @ b @ vi = 1
In the standard problem, ``b`` is assumed to be the identity matrix.
Parameters
----------
a : (M, M) array_like
    A complex Hermitian or real symmetric matrix whose eigenvalues and
    eigenvectors will be computed.
b : (M, M) array_like, optional
    A complex Hermitian or real symmetric definite positive matrix in.
    If omitted, identity matrix is assumed.
lower : bool, optional
    Whether the pertinent array data is taken from the lower or upper
    triangle of ``a`` and, if applicable, ``b``. (Default: lower)
eigvals_only : bool, optional
    Whether to calculate only eigenvalues and no eigenvectors.
    (Default: both are calculated)
subset_by_index : iterable, optional
    If provided, this two-element iterable defines the start and the end
    indices of the desired eigenvalues (ascending order and 0-indexed).
    To return only the second smallest to fifth smallest eigenvalues,
    ``[1, 4]`` is used. ``[n-3, n-1]`` returns the largest three. Only
    available with "evr", "evx", and "gvx" drivers. The entries are
    directly converted to integers via ``int()``.
subset_by_value : iterable, optional
    If provided, this two-element iterable defines the half-open interval
    ``(a, b]`` that, if any, only the eigenvalues between these values
    are returned. Only available with "evr", "evx", and "gvx" drivers. Use
    ``np.inf`` for the unconstrained ends.
driver : str, optional
    Defines which LAPACK driver should be used. Valid options are "ev",
    "evd", "evr", "evx" for standard problems and "gv", "gvd", "gvx" for
    generalized (where b is not None) problems. See the Notes section.
    The default for standard problems is "evr". For generalized problems,
    "gvd" is used for full set, and "gvx" for subset requested cases.
type : int, optional
    For the generalized problems, this keyword specifies the problem type
    to be solved for ``w`` and ``v`` (only takes 1, 2, 3 as possible
    inputs)::
        1 =>     a @ v = w @ b @ v
        2 => a @ b @ v = w @ v
        3 => b @ a @ v = w @ v
    This keyword is ignored for standard problems.
overwrite_a : bool, optional
    Whether to overwrite data in ``a`` (may improve performance). Default
    is False.
overwrite_b : bool, optional
    Whether to overwrite data in ``b`` (may improve performance). Default
    is False.
check_finite : bool, optional
    Whether to check that the input matrices contain only finite numbers.
    Disabling may give a performance gain, but may result in problems
    (crashes, non-termination) if the inputs do contain infinities or NaNs.
turbo : bool, optional, deprecated
        .. deprecated:: 1.5.0
            `eigh` keyword argument `turbo` is deprecated in favour of
            ``driver=gvd`` keyword instead and will be removed in SciPy
            1.12.0.
eigvals : tuple (lo, hi), optional, deprecated
        .. deprecated:: 1.5.0
            `eigh` keyword argument `eigvals` is deprecated in favour of
            `subset_by_index` keyword instead and will be removed in SciPy
            1.12.0.
Returns
-------
w : (N,) ndarray
    The N (1<=N<=M) selected eigenvalues, in ascending order, each
    repeated according to its multiplicity.
v : (M, N) ndarray
    (if ``eigvals_only == False``)
Raises
------
LinAlgError
    If eigenvalue computation does not converge, an error occurred, or
    b matrix is not definite positive. Note that if input matrices are
    not symmetric or Hermitian, no error will be reported but results will
    be wrong.
See Also
--------
eigvalsh : eigenvalues of symmetric or Hermitian arrays
eig : eigenvalues and right eigenvectors for non-symmetric arrays
eigh_tridiagonal : eigenvalues and right eiegenvectors for
    symmetric/Hermitian tridiagonal matrices
Notes
-----
This function does not check the input array for being Hermitian/symmetric
in order to allow for representing arrays with only their upper/lower
triangular parts. Also, note that even though not taken into account,
finiteness check applies to the whole array and unaffected by "lower"
keyword.
This function uses LAPACK drivers for computations in all possible keyword
combinations, prefixed with ``sy`` if arrays are real and ``he`` if
complex, e.g., a float array with "evr" driver is solved via
"syevr", complex arrays with "gvx" driver problem is solved via "hegvx"
etc.
As a brief summary, the slowest and the most robust driver is the
classical ``<sy/he>ev`` which uses symmetric QR. ``<sy/he>evr`` is seen as
the optimal choice for the most general cases. However, there are certain
occasions that ``<sy/he>evd`` computes faster at the expense of more
memory usage. ``<sy/he>evx``, while still being faster than ``<sy/he>ev``,
often performs worse than the rest except when very few eigenvalues are
requested for large arrays though there is still no performance guarantee.
For the generalized problem, normalization with respect to the given
type argument::
        type 1 and 3 :      v.conj().T @ a @ v = w
        type 2       : inv(v).conj().T @ a @ inv(v) = w
        type 1 or 2  :      v.conj().T @ b @ v  = I
        type 3       : v.conj().T @ inv(b) @ v  = I
Examples
--------
>>> import numpy as np
>>> from scipy.linalg import eigh
>>> A = np.array([[6, 3, 1, 5], [3, 0, 5, 1], [1, 5, 6, 2], [5, 1, 2, 2]])
>>> w, v = eigh(A)
>>> np.allclose(A @ v - v @ np.diag(w), np.zeros((4, 4)))
True
Request only the eigenvalues
>>> w = eigh(A, eigvals_only=True)
Request eigenvalues that are less than 10.
>>> A = np.array([[34, -4, -10, -7, 2],
...               [-4, 7, 2, 12, 0],
...               [-10, 2, 44, 2, -19],
...               [-7, 12, 2, 79, -34],
...               [2, 0, -19, -34, 29]])
>>> eigh(A, eigvals_only=True, subset_by_value=[-np.inf, 10])
array([6.69199443e-07, 9.11938152e+00])
Request the second smallest eigenvalue and its eigenvector
>>> w, v = eigh(A, subset_by_index=[1, 1])
>>> w
array([9.11938152])
>>> v.shape  # only a single column is returned
(5, 1)
Definition at line 269 of file _decomp.py.
References scipy.linalg.lapack._compute_lwork(), scipy.linalg._misc._datacopied(), and scipy.linalg.lapack.get_lapack_funcs().
Referenced by eigvalsh(), scipy.linalg.tests.test_lapack.test_gejsv_NAG(), and scipy.linalg.tests.test_lapack.test_pteqr().
eigh_tridiagonal()
scipy.linalg._decomp.eigh_tridiagonal (d, e, eigvals_only = False, select = 'a', select_range = None, check_finite = True, tol = 0., lapack_driver = 'auto')
Solve eigenvalue problem for a real symmetric tridiagonal matrix.
Find eigenvalues `w` and optionally right eigenvectors `v` of ``a``::
    a v[:,i] = w[i] v[:,i]
    v.H v    = identity
For a real symmetric matrix ``a`` with diagonal elements `d` and
off-diagonal elements `e`.
Parameters
----------
d : ndarray, shape (ndim,)
    The diagonal elements of the array.
e : ndarray, shape (ndim-1,)
    The off-diagonal elements of the array.
select : {'a', 'v', 'i'}, optional
    Which eigenvalues to calculate
    ======  ========================================
    select  calculated
    ======  ========================================
    'a'     All eigenvalues
    'v'     Eigenvalues in the interval (min, max]
    'i'     Eigenvalues with indices min <= i <= max
    ======  ========================================
select_range : (min, max), optional
    Range of selected eigenvalues
check_finite : bool, optional
    Whether to check that the input matrix contains only finite numbers.
    Disabling may give a performance gain, but may result in problems
    (crashes, non-termination) if the inputs do contain infinities or NaNs.
tol : float
    The absolute tolerance to which each eigenvalue is required
    (only used when 'stebz' is the `lapack_driver`).
    An eigenvalue (or cluster) is considered to have converged if it
    lies in an interval of this width. If <= 0. (default),
    the value ``eps*|a|`` is used where eps is the machine precision,
    and ``|a|`` is the 1-norm of the matrix ``a``.
lapack_driver : str
    LAPACK function to use, can be 'auto', 'stemr', 'stebz', 'sterf',
    or 'stev'. When 'auto' (default), it will use 'stemr' if ``select='a'``
    and 'stebz' otherwise. When 'stebz' is used to find the eigenvalues and
    ``eigvals_only=False``, then a second LAPACK call (to ``?STEIN``) is
    used to find the corresponding eigenvectors. 'sterf' can only be
    used when ``eigvals_only=True`` and ``select='a'``. 'stev' can only
    be used when ``select='a'``.
Returns
-------
w : (M,) ndarray
    The eigenvalues, in ascending order, each repeated according to its
    multiplicity.
v : (M, M) ndarray
    The normalized eigenvector corresponding to the eigenvalue ``w[i]`` is
    the column ``v[:,i]``.
Raises
------
LinAlgError
    If eigenvalue computation does not converge.
See Also
--------
eigvalsh_tridiagonal : eigenvalues of symmetric/Hermitian tridiagonal
    matrices
eig : eigenvalues and right eigenvectors for non-symmetric arrays
eigh : eigenvalues and right eigenvectors for symmetric/Hermitian arrays
eig_banded : eigenvalues and right eigenvectors for symmetric/Hermitian
    band matrices
Notes
-----
This function makes use of LAPACK ``S/DSTEMR`` routines.
Examples
--------
>>> import numpy as np
>>> from scipy.linalg import eigh_tridiagonal
>>> d = 3*np.ones(4)
>>> e = -1*np.ones(3)
>>> w, v = eigh_tridiagonal(d, e)
>>> A = np.diag(d) + np.diag(e, k=1) + np.diag(e, k=-1)
>>> np.allclose(A @ v - v @ np.diag(w), np.zeros((4, 4)))
True
Definition at line 1203 of file _decomp.py.
References _check_info(), _check_select(), and scipy.linalg.lapack.get_lapack_funcs().
Referenced by eigvalsh_tridiagonal().
eigvals()
scipy.linalg._decomp.eigvals (a, b = None, overwrite_a = False, check_finite = True, homogeneous_eigvals = False)
Compute eigenvalues from an ordinary or generalized eigenvalue problem.
Find eigenvalues of a general matrix::
    a   vr[:,i] = w[i]        b   vr[:,i]
Parameters
----------
a : (M, M) array_like
    A complex or real matrix whose eigenvalues and eigenvectors
    will be computed.
b : (M, M) array_like, optional
    Right-hand side matrix in a generalized eigenvalue problem.
    If omitted, identity matrix is assumed.
overwrite_a : bool, optional
    Whether to overwrite data in a (may improve performance)
check_finite : bool, optional
    Whether to check that the input matrices contain only finite numbers.
    Disabling may give a performance gain, but may result in problems
    (crashes, non-termination) if the inputs do contain infinities
    or NaNs.
homogeneous_eigvals : bool, optional
    If True, return the eigenvalues in homogeneous coordinates.
    In this case ``w`` is a (2, M) array so that::
        w[1,i] a vr[:,i] = w[0,i] b vr[:,i]
    Default is False.
Returns
-------
w : (M,) or (2, M) double or complex ndarray
    The eigenvalues, each repeated according to its multiplicity
    but not in any specific order. The shape is (M,) unless
    ``homogeneous_eigvals=True``.
Raises
------
LinAlgError
    If eigenvalue computation does not converge
See Also
--------
eig : eigenvalues and right eigenvectors of general arrays.
eigvalsh : eigenvalues of symmetric or Hermitian arrays
eigvals_banded : eigenvalues for symmetric/Hermitian band matrices
eigvalsh_tridiagonal : eigenvalues of symmetric/Hermitian tridiagonal
    matrices
Examples
--------
>>> import numpy as np
>>> from scipy import linalg
>>> a = np.array([[0., -1.], [1., 0.]])
>>> linalg.eigvals(a)
array([0.+1.j, 0.-1.j])
>>> b = np.array([[0., 1.], [1., 1.]])
>>> linalg.eigvals(a, b)
array([ 1.+0.j, -1.+0.j])
>>> a = np.array([[3., 0., 0.], [0., 8., 0.], [0., 0., 7.]])
>>> linalg.eigvals(a, homogeneous_eigvals=True)
array([[3.+0.j, 8.+0.j, 7.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j]])
Definition at line 825 of file _decomp.py.
References eig().
Referenced by scipy.linalg._decomp_schur.rsf2csf().
eigvals_banded()
scipy.linalg._decomp.eigvals_banded (a_band, lower = False, overwrite_a_band = False, select = 'a', select_range = None, check_finite = True)
Solve real symmetric or complex Hermitian band matrix eigenvalue problem.
Find eigenvalues w of a::
    a v[:,i] = w[i] v[:,i]
    v.H v    = identity
The matrix a is stored in a_band either in lower diagonal or upper
diagonal ordered form:
    a_band[u + i - j, j] == a[i,j]        (if upper form; i <= j)
    a_band[    i - j, j] == a[i,j]        (if lower form; i >= j)
where u is the number of bands above the diagonal.
Example of a_band (shape of a is (6,6), u=2)::
    upper form:
    *   *   a02 a13 a24 a35
    *   a01 a12 a23 a34 a45
    a00 a11 a22 a33 a44 a55
    lower form:
    a00 a11 a22 a33 a44 a55
    a10 a21 a32 a43 a54 *
    a20 a31 a42 a53 *   *
Cells marked with * are not used.
Parameters
----------
a_band : (u+1, M) array_like
    The bands of the M by M matrix a.
lower : bool, optional
    Is the matrix in the lower form. (Default is upper form)
overwrite_a_band : bool, optional
    Discard data in a_band (may enhance performance)
select : {'a', 'v', 'i'}, optional
    Which eigenvalues to calculate
    ======  ========================================
    select  calculated
    ======  ========================================
    'a'     All eigenvalues
    'v'     Eigenvalues in the interval (min, max]
    'i'     Eigenvalues with indices min <= i <= max
    ======  ========================================
select_range : (min, max), optional
    Range of selected eigenvalues
check_finite : bool, optional
    Whether to check that the input matrix contains only finite numbers.
    Disabling may give a performance gain, but may result in problems
    (crashes, non-termination) if the inputs do contain infinities or NaNs.
Returns
-------
w : (M,) ndarray
    The eigenvalues, in ascending order, each repeated according to its
    multiplicity.
Raises
------
LinAlgError
    If eigenvalue computation does not converge.
See Also
--------
eig_banded : eigenvalues and right eigenvectors for symmetric/Hermitian
    band matrices
eigvalsh_tridiagonal : eigenvalues of symmetric/Hermitian tridiagonal
    matrices
eigvals : eigenvalues of general arrays
eigh : eigenvalues and right eigenvectors for symmetric/Hermitian arrays
eig : eigenvalues and right eigenvectors for non-symmetric arrays
Examples
--------
>>> import numpy as np
>>> from scipy.linalg import eigvals_banded
>>> A = np.array([[1, 5, 2, 0], [5, 2, 5, 2], [2, 5, 3, 5], [0, 2, 5, 4]])
>>> Ab = np.array([[1, 2, 3, 4], [5, 5, 5, 0], [2, 2, 0, 0]])
>>> w = eigvals_banded(Ab, lower=True)
>>> w
array([-4.26200532, -2.22987175,  3.95222349, 12.53965359])
Definition at line 1029 of file _decomp.py.
References eig_banded().
eigvalsh()
scipy.linalg._decomp.eigvalsh (a, b = None, lower = True, overwrite_a = False, overwrite_b = False, turbo = False, eigvals = None, type = 1, check_finite = True, subset_by_index = None, subset_by_value = None, driver = None)
Solves a standard or generalized eigenvalue problem for a complex
Hermitian or real symmetric matrix.
Find eigenvalues array ``w`` of array ``a``, where ``b`` is positive
definite such that for every eigenvalue λ (i-th entry of w) and its
eigenvector vi (i-th column of v) satisfies::
                  a @ vi = λ * b @ vi
    vi.conj().T @ a @ vi = λ
    vi.conj().T @ b @ vi = 1
In the standard problem, b is assumed to be the identity matrix.
Parameters
----------
a : (M, M) array_like
    A complex Hermitian or real symmetric matrix whose eigenvalues will
    be computed.
b : (M, M) array_like, optional
    A complex Hermitian or real symmetric definite positive matrix in.
    If omitted, identity matrix is assumed.
lower : bool, optional
    Whether the pertinent array data is taken from the lower or upper
    triangle of ``a`` and, if applicable, ``b``. (Default: lower)
overwrite_a : bool, optional
    Whether to overwrite data in ``a`` (may improve performance). Default
    is False.
overwrite_b : bool, optional
    Whether to overwrite data in ``b`` (may improve performance). Default
    is False.
type : int, optional
    For the generalized problems, this keyword specifies the problem type
    to be solved for ``w`` and ``v`` (only takes 1, 2, 3 as possible
    inputs)::
        1 =>     a @ v = w @ b @ v
        2 => a @ b @ v = w @ v
        3 => b @ a @ v = w @ v
    This keyword is ignored for standard problems.
check_finite : bool, optional
    Whether to check that the input matrices contain only finite numbers.
    Disabling may give a performance gain, but may result in problems
    (crashes, non-termination) if the inputs do contain infinities or NaNs.
subset_by_index : iterable, optional
    If provided, this two-element iterable defines the start and the end
    indices of the desired eigenvalues (ascending order and 0-indexed).
    To return only the second smallest to fifth smallest eigenvalues,
    ``[1, 4]`` is used. ``[n-3, n-1]`` returns the largest three. Only
    available with "evr", "evx", and "gvx" drivers. The entries are
    directly converted to integers via ``int()``.
subset_by_value : iterable, optional
    If provided, this two-element iterable defines the half-open interval
    ``(a, b]`` that, if any, only the eigenvalues between these values
    are returned. Only available with "evr", "evx", and "gvx" drivers. Use
    ``np.inf`` for the unconstrained ends.
driver : str, optional
    Defines which LAPACK driver should be used. Valid options are "ev",
    "evd", "evr", "evx" for standard problems and "gv", "gvd", "gvx" for
    generalized (where b is not None) problems. See the Notes section of
    `scipy.linalg.eigh`.
turbo : bool, optional, deprecated
    .. deprecated:: 1.5.0
        'eigvalsh' keyword argument `turbo` is deprecated in favor of
        ``driver=gvd`` option and will be removed in SciPy 1.12.0.
eigvals : tuple (lo, hi), optional
    .. deprecated:: 1.5.0
        'eigvalsh' keyword argument `eigvals` is deprecated in favor of
        `subset_by_index` option and will be removed in SciPy 1.12.0.
Returns
-------
w : (N,) ndarray
    The ``N`` (``1<=N<=M``) selected eigenvalues, in ascending order, each
    repeated according to its multiplicity.
Raises
------
LinAlgError
    If eigenvalue computation does not converge, an error occurred, or
    b matrix is not definite positive. Note that if input matrices are
    not symmetric or Hermitian, no error will be reported but results will
    be wrong.
See Also
--------
eigh : eigenvalues and right eigenvectors for symmetric/Hermitian arrays
eigvals : eigenvalues of general arrays
eigvals_banded : eigenvalues for symmetric/Hermitian band matrices
eigvalsh_tridiagonal : eigenvalues of symmetric/Hermitian tridiagonal
    matrices
Notes
-----
This function does not check the input array for being Hermitian/symmetric
in order to allow for representing arrays with only their upper/lower
triangular parts.
This function serves as a one-liner shorthand for `scipy.linalg.eigh` with
the option ``eigvals_only=True`` to get the eigenvalues and not the
eigenvectors. Here it is kept as a legacy convenience. It might be
beneficial to use the main function to have full control and to be a bit
more pythonic.
Examples
--------
For more examples see `scipy.linalg.eigh`.
>>> import numpy as np
>>> from scipy.linalg import eigvalsh
>>> A = np.array([[6, 3, 1, 5], [3, 0, 5, 1], [1, 5, 6, 2], [5, 1, 2, 2]])
>>> w = eigvalsh(A)
>>> w
array([-3.74637491, -0.76263923,  6.08502336, 12.42399079])
Definition at line 900 of file _decomp.py.
References eigh().
eigvalsh_tridiagonal()
scipy.linalg._decomp.eigvalsh_tridiagonal (d, e, select = 'a', select_range = None, check_finite = True, tol = 0., lapack_driver = 'auto')
Solve eigenvalue problem for a real symmetric tridiagonal matrix.
Find eigenvalues `w` of ``a``::
    a v[:,i] = w[i] v[:,i]
    v.H v    = identity
For a real symmetric matrix ``a`` with diagonal elements `d` and
off-diagonal elements `e`.
Parameters
----------
d : ndarray, shape (ndim,)
    The diagonal elements of the array.
e : ndarray, shape (ndim-1,)
    The off-diagonal elements of the array.
select : {'a', 'v', 'i'}, optional
    Which eigenvalues to calculate
    ======  ========================================
    select  calculated
    ======  ========================================
    'a'     All eigenvalues
    'v'     Eigenvalues in the interval (min, max]
    'i'     Eigenvalues with indices min <= i <= max
    ======  ========================================
select_range : (min, max), optional
    Range of selected eigenvalues
check_finite : bool, optional
    Whether to check that the input matrix contains only finite numbers.
    Disabling may give a performance gain, but may result in problems
    (crashes, non-termination) if the inputs do contain infinities or NaNs.
tol : float
    The absolute tolerance to which each eigenvalue is required
    (only used when ``lapack_driver='stebz'``).
    An eigenvalue (or cluster) is considered to have converged if it
    lies in an interval of this width. If <= 0. (default),
    the value ``eps*|a|`` is used where eps is the machine precision,
    and ``|a|`` is the 1-norm of the matrix ``a``.
lapack_driver : str
    LAPACK function to use, can be 'auto', 'stemr', 'stebz',  'sterf',
    or 'stev'. When 'auto' (default), it will use 'stemr' if ``select='a'``
    and 'stebz' otherwise. 'sterf' and 'stev' can only be used when
    ``select='a'``.
Returns
-------
w : (M,) ndarray
    The eigenvalues, in ascending order, each repeated according to its
    multiplicity.
Raises
------
LinAlgError
    If eigenvalue computation does not converge.
See Also
--------
eigh_tridiagonal : eigenvalues and right eiegenvectors for
    symmetric/Hermitian tridiagonal matrices
Examples
--------
>>> import numpy as np
>>> from scipy.linalg import eigvalsh_tridiagonal, eigvalsh
>>> d = 3*np.ones(4)
>>> e = -1*np.ones(3)
>>> w = eigvalsh_tridiagonal(d, e)
>>> A = np.diag(d) + np.diag(e, k=1) + np.diag(e, k=-1)
>>> w2 = eigvalsh(A)  # Verify with other eigenvalue routines
>>> np.allclose(w - w2, np.zeros(4))
True
Definition at line 1122 of file _decomp.py.
References eigh_tridiagonal().
hessenberg()
scipy.linalg._decomp.hessenberg (a, calc_q = False, overwrite_a = False, check_finite = True)
Compute Hessenberg form of a matrix.
The Hessenberg decomposition is::
    A = Q H Q^H
where `Q` is unitary/orthogonal and `H` has only zero elements below
the first sub-diagonal.
Parameters
----------
a : (M, M) array_like
    Matrix to bring into Hessenberg form.
calc_q : bool, optional
    Whether to compute the transformation matrix.  Default is False.
overwrite_a : bool, optional
    Whether to overwrite `a`; may improve performance.
    Default is False.
check_finite : bool, optional
    Whether to check that the input matrix contains only finite numbers.
    Disabling may give a performance gain, but may result in problems
    (crashes, non-termination) if the inputs do contain infinities or NaNs.
Returns
-------
H : (M, M) ndarray
    Hessenberg form of `a`.
Q : (M, M) ndarray
    Unitary/orthogonal similarity transformation matrix ``A = Q H Q^H``.
    Only returned if ``calc_q=True``.
Examples
--------
>>> import numpy as np
>>> from scipy.linalg import hessenberg
>>> A = np.array([[2, 5, 8, 7], [5, 2, 2, 8], [7, 5, 6, 6], [5, 4, 4, 8]])
>>> H, Q = hessenberg(A, calc_q=True)
>>> H
array([[  2.        , -11.65843866,   1.42005301,   0.25349066],
       [ -9.94987437,  14.53535354,  -5.31022304,   2.43081618],
       [  0.        ,  -1.83299243,   0.38969961,  -0.51527034],
       [  0.        ,   0.        ,  -3.83189513,   1.07494686]])
>>> np.allclose(Q @ H @ Q.conj().T - A, np.zeros((4, 4)))
True
Definition at line 1374 of file _decomp.py.
References _check_info(), scipy.linalg.lapack._compute_lwork(), scipy.linalg._misc._datacopied(), and scipy.linalg.lapack.get_lapack_funcs().
Variable Documentation
__all__
list scipy.linalg._decomp.__all__ private
Initial value:
=  ['eig', 'eigvals', 'eigh', 'eigvalsh',
           'eig_banded', 'eigvals_banded',
           'eigh_tridiagonal', 'eigvalsh_tridiagonal', 'hessenberg', 'cdf2rdf']
Definition at line 15 of file _decomp.py.
_conv_dict
dict scipy.linalg._decomp._conv_dict protected
Initial value:
=  {0: 0, 1: 1, 2: 2,
              'all': 0, 'value': 1, 'index': 2,
              'a': 0, 'v': 1, 'i': 2}
Definition at line 622 of file _decomp.py.
_I
scipy.linalg._decomp._I = cast['F'](1j) protected
Definition at line 31 of file _decomp.py.