Code Cloning Analysis: joblib.externals.loky.process_executor._ExecutorFlags Class Reference
joblib.externals.loky.process_executor._ExecutorFlags Class Reference
Public Member Functions
__init__ (self, shutdown_lock)
flag_as_shutting_down (self, kill_workers=None)
flag_as_broken (self, broken)
Public Attributes
bool shutdown = False
broken = None
bool kill_workers = False
shutdown_lock = shutdown_lock
Detailed Description
necessary references to maintain executor states without preventing gc
It permits to keep the information needed by executor_manager_thread
and crash_detection_thread to maintain the pool without preventing the
garbage collection of unreferenced executors.
Definition at line 141 of file process_executor.py.
Constructor & Destructor Documentation
__init__()
joblib.externals.loky.process_executor._ExecutorFlags.__init__ (self, shutdown_lock)
Definition at line 149 of file process_executor.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
flag_as_broken()
joblib.externals.loky.process_executor._ExecutorFlags.flag_as_broken (self, broken)
Definition at line 162 of file process_executor.py.
flag_as_shutting_down()
joblib.externals.loky.process_executor._ExecutorFlags.flag_as_shutting_down (self, kill_workers = None)
Definition at line 156 of file process_executor.py.
Member Data Documentation
broken
joblib.externals.loky.process_executor._ExecutorFlags.broken = None
Definition at line 152 of file process_executor.py.
kill_workers
bool joblib.externals.loky.process_executor._ExecutorFlags.kill_workers = False
Definition at line 153 of file process_executor.py.
shutdown
bool joblib.externals.loky.process_executor._ExecutorFlags.shutdown = False
Definition at line 151 of file process_executor.py.
Referenced by joblib.executor.MemmappingExecutor.get_memmapping_executor().
shutdown_lock
joblib.externals.loky.process_executor._ExecutorFlags.shutdown_lock = shutdown_lock
Definition at line 154 of file process_executor.py.
Referenced by joblib.externals.loky.process_executor._SafeQueue._on_queue_feeder_error().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py