Code Cloning Analysis: scipy.stats._multivariate.random_table_frozen Class Reference
scipy.stats._multivariate.random_table_frozen Class Reference
Public Member Functions
__init__ (self, row, col, *, seed=None)
logpmf (self, x)
pmf (self, x)
mean (self)
rvs (self, size=None, method=None, random_state=None)
Public Member Functions inherited from scipy.stats._multivariate.multi_rv_frozen
random_state (self)
random_state (self, seed)
Protected Attributes
_dist = random_table_gen(seed)
_params = self._dist._process_parameters(row, col)
Detailed Description
Definition at line 5625 of file _multivariate.py.
Constructor & Destructor Documentation
__init__()
scipy.stats._multivariate.random_table_frozen.__init__ (self, row, col, * , seed = None)
Definition at line 5626 of file _multivariate.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params().
Member Function Documentation
logpmf()
scipy.stats._multivariate.random_table_frozen.logpmf (self, x)
Definition at line 5635 of file _multivariate.py.
Referenced by scipy.stats._multivariate.dirichlet_multinomial_gen.pmf().
mean()
scipy.stats._multivariate.random_table_frozen.mean (self)
Definition at line 5641 of file _multivariate.py.
pmf()
scipy.stats._multivariate.random_table_frozen.pmf (self, x)
Definition at line 5638 of file _multivariate.py.
Referenced by scipy.stats._page_trend_test._PageL.pmf(), and scipy.stats._page_trend_test._PageL.sf().
rvs()
scipy.stats._multivariate.random_table_frozen.rvs (self, size = None, method = None, random_state = None)
Definition at line 5644 of file _multivariate.py.
Member Data Documentation
_dist
scipy.stats._multivariate.random_table_frozen._dist = random_table_gen(seed) protected
Definition at line 5627 of file _multivariate.py.
Referenced by scipy.stats._multivariate.uniform_direction_frozen.__init__(), scipy.stats._multivariate.vonmises_fisher_frozen.__init__(), scipy.stats._multivariate.vonmises_fisher_frozen.entropy(), scipy.stats._multivariate.vonmises_fisher_frozen.logpdf(), and scipy.stats._multivariate.vonmises_fisher_frozen.rvs().
_params
scipy.stats._multivariate.random_table_frozen._params = self._dist._process_parameters(row, col) protected
Definition at line 5628 of file _multivariate.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/stats/_multivariate.py