Code Cloning Analysis: scipy.signal.tests.test_peak_finding.TestFindPeaks Class Reference
scipy.signal.tests.test_peak_finding.TestFindPeaks Class Reference
Public Member Functions
test_constant (self)
test_plateau_size (self)
test_height_condition (self)
test_threshold_condition (self)
test_distance_condition (self)
test_prominence_condition (self)
test_width_condition (self)
test_properties (self)
test_raises (self)
test_wlen_smaller_plateau (self)
test_readonly_array (self, kwargs)
Static Public Attributes
dict property_keys
Detailed Description
Definition at line 603 of file test_peak_finding.py.
Member Function Documentation
test_constant()
scipy.signal.tests.test_peak_finding.TestFindPeaks.test_constant (self)
Test behavior for signal without local maxima.
Definition at line 610 of file test_peak_finding.py.
References scipy.signal._peak_finding.find_peaks(), and property_keys.
test_distance_condition()
scipy.signal.tests.test_peak_finding.TestFindPeaks.test_distance_condition (self)
Test distance condition for peaks.
Definition at line 673 of file test_peak_finding.py.
References scipy.signal._peak_finding.find_peaks().
test_height_condition()
scipy.signal.tests.test_peak_finding.TestFindPeaks.test_height_condition (self)
Test height condition for peaks.
Definition at line 646 of file test_peak_finding.py.
References scipy.signal._peak_finding.find_peaks().
test_plateau_size()
scipy.signal.tests.test_peak_finding.TestFindPeaks.test_plateau_size (self)
Test plateau size condition for peaks.
Definition at line 622 of file test_peak_finding.py.
References scipy.signal._peak_finding.find_peaks().
test_prominence_condition()
scipy.signal.tests.test_peak_finding.TestFindPeaks.test_prominence_condition (self)
Test prominence condition for peaks.
Definition at line 699 of file test_peak_finding.py.
References scipy.signal._peak_finding.find_peaks().
test_properties()
scipy.signal.tests.test_peak_finding.TestFindPeaks.test_properties (self)
Test returned properties.
Definition at line 731 of file test_peak_finding.py.
References scipy.signal._peak_finding.find_peaks(), and property_keys.
test_raises()
scipy.signal.tests.test_peak_finding.TestFindPeaks.test_raises (self)
Test exceptions raised by function.
Definition at line 744 of file test_peak_finding.py.
References scipy.signal._peak_finding.find_peaks().
test_readonly_array()
scipy.signal.tests.test_peak_finding.TestFindPeaks.test_readonly_array (self, kwargs)
Test readonly arrays are accepted.
Definition at line 780 of file test_peak_finding.py.
References scipy.signal._peak_finding.find_peaks().
test_threshold_condition()
scipy.signal.tests.test_peak_finding.TestFindPeaks.test_threshold_condition (self)
Test threshold condition for peaks.
Definition at line 658 of file test_peak_finding.py.
References scipy.signal._peak_finding.find_peaks().
test_width_condition()
scipy.signal.tests.test_peak_finding.TestFindPeaks.test_width_condition (self)
Test width condition for peaks.
Definition at line 718 of file test_peak_finding.py.
References scipy.signal._peak_finding.find_peaks().
test_wlen_smaller_plateau()
scipy.signal.tests.test_peak_finding.TestFindPeaks.test_wlen_smaller_plateau (self)
Test behavior of prominence and width calculation if the given window
length is smaller than a peak's plateau size.
Regression test for gh-9110.
Definition at line 757 of file test_peak_finding.py.
References scipy.signal._peak_finding.find_peaks().
Member Data Documentation
property_keys
dict scipy.signal.tests.test_peak_finding.TestFindPeaks.property_keys static
Initial value:
=  {'peak_heights', 'left_thresholds', 'right_thresholds',
                     'prominences', 'left_bases', 'right_bases', 'widths',
                     'width_heights', 'left_ips', 'right_ips'}
Definition at line 606 of file test_peak_finding.py.
Referenced by test_constant(), and test_properties().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/signal/tests/test_peak_finding.py