Code Cloning Analysis: matplotlib.hatch.SouthEastHatch Class Reference
matplotlib.hatch.SouthEastHatch Class Reference
Public Member Functions
__init__ (self, hatch, density)
set_vertices_and_codes (self, vertices, codes)
Public Attributes
num_lines
tuple num_vertices = (self.num_lines + 1) * 2
Detailed Description
Definition at line 67 of file hatch.py.
Constructor & Destructor Documentation
__init__()
matplotlib.hatch.SouthEastHatch.__init__ (self, hatch, density)
Definition at line 68 of file hatch.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
set_vertices_and_codes()
matplotlib.hatch.SouthEastHatch.set_vertices_and_codes (self, vertices, codes)
Definition at line 77 of file hatch.py.
Member Data Documentation
num_lines
matplotlib.hatch.SouthEastHatch.num_lines
Initial value:
=  int(
            (hatch.count('\\') + hatch.count('x') + hatch.count('X'))
            * density)
Definition at line 69 of file hatch.py.
num_vertices
tuple matplotlib.hatch.SouthEastHatch.num_vertices = (self.num_lines + 1) * 2
Definition at line 73 of file hatch.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/hatch.py