Code Cloning Analysis: pip._internal.cli.req_command.SessionCommandMixin Class Reference
pip._internal.cli.req_command.SessionCommandMixin Class Reference
Public Member Functions
None __init__ (self)
PipSession get_default_session (self, Values options)
Public Member Functions inherited from pip._internal.cli.command_context.CommandContextMixIn
None __init__ (self)
Generator[None, None, None] main_context (self)
_T enter_context (self, ContextManager[_T] context_provider)
Protected Member Functions
Optional[List[str]] _get_index_urls (cls, Values options)
PipSession _build_session (self, Values options, Optional[int] retries=None, Optional[int] timeout=None, bool fallback_to_certifi=False)
Protected Attributes
Optional[PipSession] _session = None
Protected Attributes inherited from pip._internal.cli.command_context.CommandContextMixIn
bool _in_main_context = False
_main_context = ExitStack()
Detailed Description
A class mixin for command classes needing _build_session().
Definition at line 68 of file req_command.py.
Constructor & Destructor Documentation
__init__()
None pip._internal.cli.req_command.SessionCommandMixin.__init__ (self)
Definition at line 74 of file req_command.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
_build_session()
PipSession pip._internal.cli.req_command.SessionCommandMixin._build_session (self, Values options, Optional[int] retries = None, Optional[int] timeout = None, bool fallback_to_certifi = False) protected
Definition at line 102 of file req_command.py.
Referenced by pip._internal.commands.index.IndexCommand._build_package_finder(), pip._internal.commands.list.ListCommand._build_package_finder(), get_default_session(), and pip._internal.cli.req_command.IndexGroupCommand.handle_pip_version_check().
_get_index_urls()
Optional[List[str]] pip._internal.cli.req_command.SessionCommandMixin._get_index_urls (cls, Values options) protected
Return a list of index urls from user-provided options.
Definition at line 79 of file req_command.py.
Referenced by get_default_session().
get_default_session()
PipSession pip._internal.cli.req_command.SessionCommandMixin.get_default_session (self, Values options)
Get a default-managed session.
Definition at line 92 of file req_command.py.
References _build_session(), _get_index_urls(), _session, and pip._internal.cli.command_context.CommandContextMixIn.enter_context().
Member Data Documentation
_session
Optional[PipSession] pip._internal.cli.req_command.SessionCommandMixin._session = None protected
Definition at line 76 of file req_command.py.
Referenced by pip._internal.network.download.BatchDownloader.__call__(), pip._internal.network.download.Downloader.__call__(), pip._internal.operations.prepare.RequirementPreparer._fetch_metadata_using_lazy_wheel(), pip._internal.network.lazy_wheel.LazyZipOverHTTP._stream_response(), get_default_session(), and pip._internal.req.req_file.RequirementsFileParser.parse().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pip/_internal/cli/req_command.py