Code Cloning Analysis: matplotlib.tri._triinterpolate.CubicTriInterpolator Class Reference
matplotlib.tri._triinterpolate.CubicTriInterpolator Class Reference
Public Member Functions
__init__ (self, triangulation, z, kind='min_E', trifinder=None, dz=None)
__call__ (self, x, y)
gradient (self, x, y)
Public Member Functions inherited from matplotlib.tri._triinterpolate.TriInterpolator
__init__ (self, triangulation, z, trifinder=None)
Protected Member Functions
_interpolate_single_key (self, return_key, tri_index, x, y)
_compute_dof (self, kind, dz=None)
Protected Member Functions inherited from matplotlib.tri._triinterpolate.TriInterpolator
_interpolate_multikeys (self, x, y, tri_index=None, return_keys=('z',))
Static Protected Member Functions
_get_alpha_vec (x, y, tris_pts)
_get_jacobian (tris_pts)
_compute_tri_eccentricities (tris_pts)
Protected Attributes
_triangles = compressed_triangles
_pts
_tris_pts = self._pts[self._triangles]
_eccs = self._compute_tri_eccentricities(self._tris_pts)
_dof = self._compute_dof(kind, dz=dz)
_ReferenceElement = _ReducedHCT_Element()
Protected Attributes inherited from matplotlib.tri._triinterpolate.TriInterpolator
_triangulation = triangulation
_z = np.asarray(z)
_trifinder = trifinder or self._triangulation.get_trifinder()
float _unit_x = 1.0
float _unit_y = 1.0
_tri_renum = None
Static Private Attributes
__doc__
Additional Inherited Members
Static Protected Attributes inherited from matplotlib.tri._triinterpolate.TriInterpolator
str _docstring__call__
str _docstringgradient
Detailed Description
Cubic interpolator on a triangular grid.
In one-dimension - on a segment - a cubic interpolating function is
defined by the values of the function and its derivative at both ends.
This is almost the same in 2D inside a triangle, except that the values
of the function and its 2 derivatives have to be defined at each triangle
node.
The CubicTriInterpolator takes the value of the function at each node -
provided by the user - and internally computes the value of the
derivatives, resulting in a smooth interpolation.
(As a special feature, the user can also impose the value of the
derivatives at each node, but this is not supposed to be the common
usage.)
Parameters
----------
triangulation : `~matplotlib.tri.Triangulation`
    The triangulation to interpolate over.
z : (npoints,) array-like
    Array of values, defined at grid points, to interpolate between.
kind : {'min_E', 'geom', 'user'}, optional
    Choice of the smoothing algorithm, in order to compute
    the interpolant derivatives (defaults to 'min_E'):
    - if 'min_E': (default) The derivatives at each node is computed
      to minimize a bending energy.
    - if 'geom': The derivatives at each node is computed as a
      weighted average of relevant triangle normals. To be used for
      speed optimization (large grids).
    - if 'user': The user provides the argument *dz*, no computation
      is hence needed.
trifinder : `~matplotlib.tri.TriFinder`, optional
    If not specified, the Triangulation's default TriFinder will
    be used by calling `.Triangulation.get_trifinder`.
dz : tuple of array-likes (dzdx, dzdy), optional
    Used only if  *kind* ='user'. In this case *dz* must be provided as
    (dzdx, dzdy) where dzdx, dzdy are arrays of the same shape as *z* and
    are the interpolant first derivatives at the *triangulation* points.
Methods
-------
`__call__` (x, y) : Returns interpolated values at (x, y) points.
`gradient` (x, y) : Returns interpolated derivatives at (x, y) points.
Notes
-----
This note is a bit technical and details how the cubic interpolation is
computed.
The interpolation is based on a Clough-Tocher subdivision scheme of
the *triangulation* mesh (to make it clearer, each triangle of the
grid will be divided in 3 child-triangles, and on each child triangle
the interpolated function is a cubic polynomial of the 2 coordinates).
This technique originates from FEM (Finite Element Method) analysis;
the element used is a reduced Hsieh-Clough-Tocher (HCT)
element. Its shape functions are described in [1]_.
The assembled function is guaranteed to be C1-smooth, i.e. it is
continuous and its first derivatives are also continuous (this
is easy to show inside the triangles but is also true when crossing the
edges).
In the default case (*kind* ='min_E'), the interpolant minimizes a
curvature energy on the functional space generated by the HCT element
shape functions - with imposed values but arbitrary derivatives at each
node. The minimized functional is the integral of the so-called total
curvature (implementation based on an algorithm from [2]_ - PCG sparse
solver):
.. math::
    E(z) = \frac{1}{2} \int_{\Omega} \left(
        \left( \frac{\partial^2{z}}{\partial{x}^2} \right)^2 +
        \left( \frac{\partial^2{z}}{\partial{y}^2} \right)^2 +
        2\left( \frac{\partial^2{z}}{\partial{y}\partial{x}} \right)^2
    \right) dx\,dy
If the case *kind* ='geom' is chosen by the user, a simple geometric
approximation is used (weighted average of the triangle normal
vectors), which could improve speed on very large grids.
References
----------
.. [1] Michel Bernadou, Kamal Hassan, "Basis functions for general
    Hsieh-Clough-Tocher triangles, complete or reduced.",
    International Journal for Numerical Methods in Engineering,
    17(5):784 - 789. 2.01.
.. [2] C.T. Kelley, "Iterative Methods for Optimization".
Definition at line 286 of file _triinterpolate.py.
Constructor & Destructor Documentation
__init__()
matplotlib.tri._triinterpolate.CubicTriInterpolator.__init__ (self, triangulation, z, kind = 'min_E', trifinder = None, dz = None)
Definition at line 379 of file _triinterpolate.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__call__()
matplotlib.tri._triinterpolate.CubicTriInterpolator.__call__ (self, x, y)
Definition at line 420 of file _triinterpolate.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), and scipy.interpolate._fitpack2.SphereBivariateSpline.ev().
_compute_dof()
matplotlib.tri._triinterpolate.CubicTriInterpolator._compute_dof (self, kind, dz = None) protected
Compute and return nodal dofs according to kind.
Parameters
----------
kind : {'min_E', 'geom', 'user'}
    Choice of the _DOF_estimator subclass to estimate the gradient.
dz : tuple of array-likes (dzdx, dzdy), optional
    Used only if *kind*=user; in this case passed to the
    :class:`_DOF_estimator_user`.
Returns
-------
array-like, shape (npts, 2)
    Estimation of the gradient at triangulation nodes (stored as
    degree of freedoms of reduced-HCT triangle elements).
Definition at line 448 of file _triinterpolate.py.
_compute_tri_eccentricities()
matplotlib.tri._triinterpolate.CubicTriInterpolator._compute_tri_eccentricities (tris_pts) static protected
Compute triangle eccentricities.
Parameters
----------
tris_pts : array like of dim 3 (shape: (nx, 3, 2))
    Coordinates of the triangles apexes.
Returns
-------
array like of dim 2 (shape: (nx, 3))
    The so-called eccentricity parameters [1] needed for HCT triangular
    element.
Definition at line 546 of file _triinterpolate.py.
References matplotlib.tri._triinterpolate._to_matrix_vectorized(), and matplotlib.tri._triinterpolate._transpose_vectorized().
_get_alpha_vec()
matplotlib.tri._triinterpolate.CubicTriInterpolator._get_alpha_vec (x, y, tris_pts) static protected
Fast (vectorized) function to compute barycentric coordinates alpha.
Parameters
----------
x, y : array-like of dim 1 (shape (nx,))
    Coordinates of the points whose points barycentric coordinates are
    requested.
tris_pts : array like of dim 3 (shape: (nx, 3, 2))
    Coordinates of the containing triangles apexes.
Returns
-------
array of dim 2 (shape (nx, 3))
    Barycentric coordinates of the points inside the containing
    triangles.
Definition at line 479 of file _triinterpolate.py.
References matplotlib.tri._triinterpolate._pseudo_inv22sym_vectorized(), matplotlib.tri._triinterpolate._to_matrix_vectorized(), and matplotlib.tri._triinterpolate._transpose_vectorized().
Referenced by _interpolate_single_key().
_get_jacobian()
matplotlib.tri._triinterpolate.CubicTriInterpolator._get_jacobian (tris_pts) static protected
Fast (vectorized) function to compute triangle jacobian matrix.
Parameters
----------
tris_pts : array like of dim 3 (shape: (nx, 3, 2))
    Coordinates of the containing triangles apexes.
Returns
-------
array of dim 3 (shape (nx, 2, 2))
    Barycentric coordinates of the points inside the containing
    triangles.
    J[itri, :, :] is the jacobian matrix at apex 0 of the triangle
    itri, so that the following (matrix) relationship holds:
       [dz/dksi] = [J] x [dz/dx]
    with x: global coordinates
         ksi: element parametric coordinates in triangle first apex
         local basis.
Definition at line 518 of file _triinterpolate.py.
References matplotlib.tri._triinterpolate._to_matrix_vectorized().
Referenced by _interpolate_single_key().
_interpolate_single_key()
matplotlib.tri._triinterpolate.CubicTriInterpolator._interpolate_single_key (self, return_key, tri_index, x, y) protected
Interpolate at points belonging to the triangulation
(inside an unmasked triangles).
Parameters
----------
return_key : {'z', 'dzdx', 'dzdy'}
    The requested values (z or its derivatives).
tri_index : 1D int array
    Valid triangle index (cannot be -1).
x, y : 1D arrays, same shape as `tri_index`
    Valid locations where interpolation is requested.
Returns
-------
1-d array
    Returned array of the same size as *tri_index*
Reimplemented from matplotlib.tri._triinterpolate.TriInterpolator.
Definition at line 430 of file _triinterpolate.py.
References _dof, _eccs, _get_alpha_vec(), _get_jacobian(), _ReferenceElement, and _tris_pts.
gradient()
matplotlib.tri._triinterpolate.CubicTriInterpolator.gradient (self, x, y)
Definition at line 425 of file _triinterpolate.py.
Member Data Documentation
__doc__
matplotlib.tri._triinterpolate.CubicTriInterpolator.__doc__ static private
Definition at line 423 of file _triinterpolate.py.
Referenced by scipy.stats._multivariate.multivariate_t_gen.__init__(), scipy.stats._distn_infrastructure.rv_discrete._attach_methods(), scipy.stats._distn_infrastructure.rv_generic._construct_default_doc(), scipy.stats._distn_infrastructure.rv_generic._construct_doc(), and pip._vendor.pygments.sphinxext.PygmentsDoc.document_lexers_overview().
_dof
matplotlib.tri._triinterpolate.CubicTriInterpolator._dof = self._compute_dof(kind, dz=dz) protected
Definition at line 416 of file _triinterpolate.py.
Referenced by _interpolate_single_key().
_eccs
matplotlib.tri._triinterpolate.CubicTriInterpolator._eccs = self._compute_tri_eccentricities(self._tris_pts) protected
Definition at line 413 of file _triinterpolate.py.
Referenced by _interpolate_single_key(), and matplotlib.tri._triinterpolate._DOF_estimator_min_E.compute_dz().
_pts
matplotlib.tri._triinterpolate.CubicTriInterpolator._pts protected
Initial value:
=  np.column_stack([compressed_x / self._unit_x,
                                     compressed_y / self._unit_y])
Definition at line 408 of file _triinterpolate.py.
Referenced by matplotlib.tri._triinterpolate._DOF_estimator_min_E.compute_dz().
_ReferenceElement
matplotlib.tri._triinterpolate.CubicTriInterpolator._ReferenceElement = _ReducedHCT_Element() protected
Definition at line 418 of file _triinterpolate.py.
Referenced by _interpolate_single_key().
_triangles
matplotlib.tri._triinterpolate.CubicTriInterpolator._triangles = compressed_triangles protected
Definition at line 399 of file _triinterpolate.py.
Referenced by matplotlib.tri._triinterpolate._DOF_estimator.compute_dof_from_df(), matplotlib.tri._triinterpolate._DOF_estimator_geom.compute_dz(), matplotlib.tri._triinterpolate._DOF_estimator_min_E.compute_dz(), matplotlib.tri._triinterpolate._DOF_estimator_geom.compute_geom_grads(), and matplotlib.tri._triinterpolate._DOF_estimator_geom.compute_geom_weights().
_tris_pts
matplotlib.tri._triinterpolate.CubicTriInterpolator._tris_pts = self._pts[self._triangles] protected
Definition at line 411 of file _triinterpolate.py.
Referenced by _interpolate_single_key(), matplotlib.tri._triinterpolate._DOF_estimator.compute_dof_from_df(), matplotlib.tri._triinterpolate._DOF_estimator_min_E.compute_dz(), matplotlib.tri._triinterpolate._DOF_estimator_geom.compute_geom_grads(), and matplotlib.tri._triinterpolate._DOF_estimator_geom.compute_geom_weights().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/tri/_triinterpolate.py