Code Cloning Analysis: scipy.stats._covariance.CovViaCholesky Class Reference
scipy.stats._covariance.CovViaCholesky Class Reference
Public Member Functions
__init__ (self, cholesky)
Public Member Functions inherited from scipy.stats._covariance.Covariance
__init__ (self)
whiten (self, x)
colorize (self, x)
log_pdet (self)
rank (self)
covariance (self)
shape (self)
Protected Member Functions
_whiten (self, x)
_colorize (self, x)
Protected Member Functions inherited from scipy.stats._covariance.Covariance
_validate_matrix (self, A, name)
_validate_vector (self, A, name)
Protected Attributes
_factor = L
_covariance = L @ L.T
_shape = L.shape
bool _allow_singular = False
Protected Attributes inherited from scipy.stats._covariance.Covariance
_log_pdet
_rank
Additional Inherited Members
Static Public Member Functions inherited from scipy.stats._covariance.Covariance
from_diagonal (diagonal)
from_precision (precision, covariance=None)
from_cholesky (cholesky)
from_eigendecomposition (eigendecomposition)
Detailed Description
Definition at line 536 of file _covariance.py.
Constructor & Destructor Documentation
__init__()
scipy.stats._covariance.CovViaCholesky.__init__ (self, cholesky)
Definition at line 538 of file _covariance.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
_colorize()
scipy.stats._covariance.CovViaCholesky._colorize (self, x) protected
Definition at line 552 of file _covariance.py.
Referenced by scipy.stats._covariance.Covariance.colorize().
_whiten()
scipy.stats._covariance.CovViaCholesky._whiten (self, x) protected
Definition at line 548 of file _covariance.py.
Referenced by scipy.stats._covariance.Covariance.whiten().
Member Data Documentation
_allow_singular
bool scipy.stats._covariance.CovViaCholesky._allow_singular = False protected
Definition at line 546 of file _covariance.py.
_covariance
scipy.stats._covariance.CovViaCholesky._covariance = L @ L.T protected
Definition at line 544 of file _covariance.py.
Referenced by scipy.stats._covariance.Covariance.covariance().
_factor
scipy.stats._covariance.CovViaCholesky._factor = L protected
Definition at line 541 of file _covariance.py.
_shape
scipy.stats._covariance.CovViaCholesky._shape = L.shape protected
Definition at line 545 of file _covariance.py.
Referenced by pandas.util._doctools.TablePlotter._get_cells(), scipy.sparse._matrix.spmatrix.get_shape(), pandas.util._doctools.TablePlotter.plot(), and scipy.stats._covariance.Covariance.shape().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/stats/_covariance.py