Code Cloning Analysis: numpy._utils._inspect Namespace Reference
numpy._utils._inspect Namespace Reference
Functions
ismethod (object)
isfunction (object)
iscode (object)
getargs (co)
getargspec (func)
getargvalues (frame)
joinseq (seq)
strseq (object, convert, join=joinseq)
formatargspec (args, varargs=None, varkw=None, defaults=None, formatarg=str, formatvarargs=lambda name:' *'+name, formatvarkw=lambda name:' **'+name, formatvalue=lambda value:'='+repr(value), join=joinseq)
formatargvalues (args, varargs, varkw, locals, formatarg=str, formatvarargs=lambda name:' *'+name, formatvarkw=lambda name:' **'+name, formatvalue=lambda value:'='+repr(value), join=joinseq)
Variables
list __all__ = ['getargspec', 'formatargspec']
CO_OPTIMIZED
CO_NEWLOCALS
CO_VARARGS
CO_VARKEYWORDS
Detailed Description
Subset of inspect module from upstream python
We use this instead of upstream because upstream inspect is slow to import, and
significantly contributes to numpy import times. Importing this copy has almost
no overhead.
Function Documentation
formatargspec()
numpy._utils._inspect.formatargspec (args, varargs = None, varkw = None, defaults = None, formatarg = str, formatvarargs = lambda name: '*' + name, formatvarkw = lambda name: '**' + name, formatvalue = lambda value: '=' + repr(value), join = joinseq)
Format an argument spec from the 4 values returned by getargspec.
The first four arguments are (args, varargs, varkw, defaults).  The
other four arguments are the corresponding optional formatting functions
that are called to turn names and values into strings.  The ninth
argument is an optional function to format the sequence of arguments.
Definition at line 140 of file _inspect.py.
References strseq().
formatargvalues()
numpy._utils._inspect.formatargvalues (args, varargs, varkw, locals, formatarg = str, formatvarargs = lambda name: '*' + name, formatvarkw = lambda name: '**' + name, formatvalue = lambda value: '=' + repr(value), join = joinseq)
Format an argument spec from the 4 values returned by getargvalues.
The first four arguments are (args, varargs, varkw, locals).  The
next four arguments are the corresponding optional formatting functions
that are called to turn names and values into strings.  The ninth
argument is an optional function to format the sequence of arguments.
Definition at line 168 of file _inspect.py.
References strseq().
getargs()
numpy._utils._inspect.getargs (co)
Get information about the arguments accepted by a code object.
Three things are returned: (args, varargs, varkw), where 'args' is
a list of argument names (possibly containing nested lists), and
'varargs' and 'varkw' are the names of the * and ** arguments or None.
Definition at line 65 of file _inspect.py.
References iscode().
Referenced by getargspec(), and getargvalues().
getargspec()
numpy._utils._inspect.getargspec (func)
Get the names and default values of a function's arguments.
A tuple of four things is returned: (args, varargs, varkw, defaults).
'args' is a list of the argument names (it may contain nested lists).
'varargs' and 'varkw' are the names of the * and ** arguments or None.
'defaults' is an n-tuple of the default values of the last n arguments.
Definition at line 96 of file _inspect.py.
References getargs(), isfunction(), and ismethod().
getargvalues()
numpy._utils._inspect.getargvalues (frame)
Get information about arguments passed into a particular frame.
A tuple of four things is returned: (args, varargs, varkw, locals).
'args' is a list of the argument names (it may contain nested lists).
'varargs' and 'varkw' are the names of the * and ** arguments or None.
'locals' is the locals dictionary of the given frame.
Definition at line 113 of file _inspect.py.
References getargs().
iscode()
numpy._utils._inspect.iscode (object)
Return true if the object is a code object.
Code objects provide these attributes:
    co_argcount     number of arguments (not including * or ** args)
    co_code         string of raw compiled bytecode
    co_consts       tuple of constants used in the bytecode
    co_filename     name of file in which this code object was created
    co_firstlineno  number of first line in Python source code
    co_flags        bitmap: 1=optimized | 2=newlocals | 4=*arg | 8=**arg
    co_lnotab       encoded mapping of line numbers to bytecode indices
    co_name         name with which this code object was defined
    co_names        tuple of names of local variables
    co_nlocals      number of local variables
    co_stacksize    virtual machine stack space required
    co_varnames     tuple of names of arguments and local variables
Definition at line 41 of file _inspect.py.
Referenced by getargs().
isfunction()
numpy._utils._inspect.isfunction (object)
Return true if the object is a user-defined function.
Function objects provide these attributes:
    __doc__         documentation string
    __name__        name with which this function was defined
    func_code       code object containing compiled function bytecode
    func_defaults   tuple of any default values for arguments
    func_doc        (same as __doc__)
    func_globals    global namespace in which this function was defined
    func_name       (same as __name__)
Definition at line 26 of file _inspect.py.
Referenced by getargspec().
ismethod()
numpy._utils._inspect.ismethod (object)
Return true if the object is an instance method.
Instance method objects provide these attributes:
    __doc__         documentation string
    __name__        name with which this method was defined
    im_class        class object in which this method belongs
    im_func         function object containing implementation of method
    im_self         instance to which this method is bound, or None
Definition at line 13 of file _inspect.py.
Referenced by getargspec().
joinseq()
numpy._utils._inspect.joinseq (seq)
Definition at line 125 of file _inspect.py.
strseq()
numpy._utils._inspect.strseq (object, convert, join = joinseq)
Recursively walk a sequence, stringifying each element.
Definition at line 131 of file _inspect.py.
References strseq().
Referenced by formatargspec(), formatargvalues(), and strseq().
Variable Documentation
__all__
list numpy._utils._inspect.__all__ = ['getargspec', 'formatargspec'] private
Definition at line 10 of file _inspect.py.
CO_NEWLOCALS
numpy._utils._inspect.CO_NEWLOCALS
Definition at line 63 of file _inspect.py.
CO_OPTIMIZED
numpy._utils._inspect.CO_OPTIMIZED
Definition at line 63 of file _inspect.py.
CO_VARARGS
numpy._utils._inspect.CO_VARARGS
Definition at line 63 of file _inspect.py.
CO_VARKEYWORDS
numpy._utils._inspect.CO_VARKEYWORDS
Definition at line 63 of file _inspect.py.