Code Cloning Analysis: joblib.externals.loky.initializers._ChainedInitializer Class Reference
joblib.externals.loky.initializers._ChainedInitializer Class Reference
Public Member Functions
__init__ (self, initializers)
__call__ (self, *chained_args)
Protected Attributes
_initializers = initializers
Detailed Description
Compound worker initializer
This is meant to be used in conjunction with _chain_initializers to
produce  the necessary chained_args list to be passed to __call__.
Definition at line 32 of file initializers.py.
Constructor & Destructor Documentation
__init__()
joblib.externals.loky.initializers._ChainedInitializer.__init__ (self, initializers)
Definition at line 39 of file initializers.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__call__()
joblib.externals.loky.initializers._ChainedInitializer.__call__ (self, * chained_args)
Definition at line 42 of file initializers.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), scipy.interpolate._fitpack2.SphereBivariateSpline.ev(), matplotlib.ticker.Formatter.format_data(), and matplotlib.ticker.LogFormatter.format_data().
Member Data Documentation
_initializers
joblib.externals.loky.initializers._ChainedInitializer._initializers = initializers protected
Definition at line 40 of file initializers.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/joblib/externals/loky/initializers.py