Code Cloning Analysis: dateutil.tz.tz Namespace Reference
dateutil.tz.tz Namespace Reference
Classes
class _nullcontext
class _ttinfo
class _tzfile
class _tzicalvtz
class _tzicalvtzcomp
class tzfile
class tzical
class tzlocal
class tzoffset
class tzrange
class tzstr
class tzutc
Functions
__get_gettz ()
datetime_exists (dt, tz=None)
datetime_ambiguous (dt, tz=None)
resolve_imaginary (dt)
_datetime_to_timestamp (dt)
_get_supported_offset (second_offset)
Variables
tzwin = None
ZERO = datetime.timedelta(0)
EPOCH = datetime.datetime(1970, 1, 1, 0, 0)
EPOCHORDINAL = EPOCH.toordinal()
UTC = tzutc()
list TZFILES = ["/etc/localtime", "localtime"]
list TZPATHS
gettz = __get_gettz()
__instances = weakref.WeakValueDictionary()
int __strong_cache_size = 8
__strong_cache = OrderedDict()
_cache_lock = _thread.allocate_lock()
Detailed Description
This module offers timezone implementations subclassing the abstract
:py:class:`datetime.tzinfo` type. There are classes to handle tzfile format
files (usually are in :file:`/etc/localtime`, :file:`/usr/share/zoneinfo`,
etc), TZ environment string (in all known formats), given ranges (with help
from relative deltas), local machine timezone, fixed offset timezone, and UTC
timezone.
Function Documentation
__get_gettz()
dateutil.tz.tz.__get_gettz () private
Definition at line 1470 of file tz.py.
_datetime_to_timestamp()
dateutil.tz.tz._datetime_to_timestamp (dt) protected
Convert a :class:`datetime.datetime` object to an epoch timestamp in
seconds since January 1, 1970, ignoring the time zone.
Definition at line 1809 of file tz.py.
Referenced by dateutil.tz.tz.tzfile._set_tzdata(), dateutil.tz.tz.tzfile.is_ambiguous(), and dateutil.tz.tz.tzlocal.is_ambiguous().
_get_supported_offset()
dateutil.tz.tz._get_supported_offset (second_offset) protected
Definition at line 1818 of file tz.py.
datetime_ambiguous()
dateutil.tz.tz.datetime_ambiguous (dt, tz = None)
Given a datetime and a time zone, determine whether or not a given datetime
is ambiguous (i.e if there are two times differentiated only by their DST
status).
:param dt:
    A :class:`datetime.datetime` (whose time zone will be ignored if ``tz``
    is provided.)
:param tz:
    A :class:`datetime.tzinfo` with support for the ``fold`` attribute. If
    ``None`` or not provided, the datetime's own time zone will be used.
:return:
    Returns a boolean value whether or not the "wall time" is ambiguous in
    ``tz``.
.. versionadded:: 2.6.0
Definition at line 1717 of file tz.py.
datetime_exists()
dateutil.tz.tz.datetime_exists (dt, tz = None)
Given a datetime and a time zone, determine whether or not a given datetime
would fall in a gap.
:param dt:
    A :class:`datetime.datetime` (whose time zone will be ignored if ``tz``
    is provided.)
:param tz:
    A :class:`datetime.tzinfo` with support for the ``fold`` attribute. If
    ``None`` or not provided, the datetime's own time zone will be used.
:return:
    Returns a boolean value whether or not the "wall time" exists in
    ``tz``.
.. versionadded:: 2.7.0
Definition at line 1683 of file tz.py.
Referenced by resolve_imaginary().
resolve_imaginary()
dateutil.tz.tz.resolve_imaginary (dt)
Given a datetime that may be imaginary, return an existing datetime.
This function assumes that an imaginary datetime represents what the
wall time would be in a zone had the offset transition not occurred, so
it will always fall forward by the transition's change in offset.
.. doctest::
    >>> from dateutil import tz
    >>> from datetime import datetime
    >>> NYC = tz.gettz('America/New_York')
    >>> print(tz.resolve_imaginary(datetime(2017, 3, 12, 2, 30, tzinfo=NYC)))
    2017-03-12 03:30:00-04:00
    >>> KIR = tz.gettz('Pacific/Kiritimati')
    >>> print(tz.resolve_imaginary(datetime(1995, 1, 1, 12, 30, tzinfo=KIR)))
    1995-01-02 12:30:00+14:00
As a note, :func:`datetime.astimezone` is guaranteed to produce a valid,
existing datetime, so a round-trip to and from UTC is sufficient to get
an extant datetime, however, this generally "falls back" to an earlier time
rather than falling forward to the STD side (though no guarantees are made
about this behavior).
:param dt:
    A :class:`datetime.datetime` which may or may not exist.
:return:
    Returns an existing :class:`datetime.datetime`. If ``dt`` was not
    imaginary, the datetime returned is guaranteed to be the same object
    passed to the function.
.. versionadded:: 2.7.0
Definition at line 1763 of file tz.py.
References datetime_exists().
Variable Documentation
__instances
dateutil.tz.tz.__instances = weakref.WeakValueDictionary() private
Definition at line 1547 of file tz.py.
__strong_cache
dateutil.tz.tz.__strong_cache = OrderedDict() private
Definition at line 1549 of file tz.py.
__strong_cache_size
int dateutil.tz.tz.__strong_cache_size = 8 private
Definition at line 1548 of file tz.py.
_cache_lock
dateutil.tz.tz._cache_lock = _thread.allocate_lock() protected
Definition at line 1550 of file tz.py.
EPOCH
dateutil.tz.tz.EPOCH = datetime.datetime(1970, 1, 1, 0, 0)
Definition at line 37 of file tz.py.
EPOCHORDINAL
dateutil.tz.tz.EPOCHORDINAL = EPOCH.toordinal()
Definition at line 38 of file tz.py.
gettz
dateutil.tz.tz.gettz = __get_gettz()
Definition at line 1679 of file tz.py.
TZFILES
list dateutil.tz.tz.TZFILES = ["/etc/localtime", "localtime"]
Definition at line 1460 of file tz.py.
TZPATHS
list dateutil.tz.tz.TZPATHS
Initial value:
=  ["/usr/share/zoneinfo",
               "/usr/lib/zoneinfo",
               "/usr/share/lib/zoneinfo",
               "/etc/zoneinfo"]
Definition at line 1461 of file tz.py.
tzwin
dateutil.tz.tz.tzwin = None
Definition at line 31 of file tz.py.
UTC
dateutil.tz.tz.UTC = tzutc()
Definition at line 129 of file tz.py.
ZERO
dateutil.tz.tz.ZERO = datetime.timedelta(0)
Definition at line 36 of file tz.py.