Code Cloning Analysis: pandas.plotting._matplotlib.converter.TimeFormatter Class Reference
pandas.plotting._matplotlib.converter.TimeFormatter Class Reference
Public Member Functions
None __init__ (self, locs)
str __call__ (self, x, int|None pos=0)
Public Member Functions inherited from matplotlib.ticker.Formatter
__call__ (self, x, pos=None)
format_ticks (self, values)
format_data (self, value)
format_data_short (self, value)
get_offset (self)
set_locs (self, locs)
Public Member Functions inherited from matplotlib.ticker.TickHelper
set_axis (self, axis)
create_dummy_axis (self, **kwargs)
Additional Inherited Members
Static Public Member Functions inherited from matplotlib.ticker.Formatter
fix_minus (s)
Static Public Attributes inherited from matplotlib.ticker.Formatter
list locs = []
Static Public Attributes inherited from matplotlib.ticker.TickHelper
axis = None
Protected Member Functions inherited from matplotlib.ticker.Formatter
_set_locator (self, locator)
Detailed Description
Definition at line 188 of file converter.py.
Constructor & Destructor Documentation
__init__()
None pandas.plotting._matplotlib.converter.TimeFormatter.__init__ (self, locs)
Definition at line 189 of file converter.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__call__()
str pandas.plotting._matplotlib.converter.TimeFormatter.__call__ (self, x, int | None pos = 0)
Return the time of day as a formatted string.
Parameters
----------
x : float
    The time of day specified as seconds since 00:00 (midnight),
    with up to microsecond precision.
pos
    Unused
Returns
-------
str
    A string in HH:MM:SS.mmmuuu format. Microseconds,
    milliseconds and seconds are only displayed if non-zero.
Definition at line 192 of file converter.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), and scipy.interpolate._fitpack2.SphereBivariateSpline.ev().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/plotting/_matplotlib/converter.py