Code Cloning Analysis: numpy.lib.tests.test__datasource.TestDataSourceExists Class Reference
numpy.lib.tests.test__datasource.TestDataSourceExists Class Reference
Public Member Functions
setup_method (self)
teardown_method (self)
test_ValidHTTP (self)
test_InvalidHTTP (self)
test_ValidFile (self)
test_InvalidFile (self)
Public Attributes
tmpdir = mkdtemp()
ds = datasource.DataSource(self.tmpdir)
Detailed Description
Definition at line 158 of file test__datasource.py.
Member Function Documentation
setup_method()
numpy.lib.tests.test__datasource.TestDataSourceExists.setup_method (self)
Definition at line 159 of file test__datasource.py.
teardown_method()
numpy.lib.tests.test__datasource.TestDataSourceExists.teardown_method (self)
Definition at line 163 of file test__datasource.py.
test_InvalidFile()
numpy.lib.tests.test__datasource.TestDataSourceExists.test_InvalidFile (self)
Definition at line 183 of file test__datasource.py.
test_InvalidHTTP()
numpy.lib.tests.test__datasource.TestDataSourceExists.test_InvalidHTTP (self)
Definition at line 170 of file test__datasource.py.
test_ValidFile()
numpy.lib.tests.test__datasource.TestDataSourceExists.test_ValidFile (self)
Definition at line 173 of file test__datasource.py.
test_ValidHTTP()
numpy.lib.tests.test__datasource.TestDataSourceExists.test_ValidHTTP (self)
Definition at line 167 of file test__datasource.py.
Member Data Documentation
ds
numpy.lib.tests.test__datasource.TestDataSourceExists.ds = datasource.DataSource(self.tmpdir)
Definition at line 161 of file test__datasource.py.
Referenced by scipy.optimize._nonlin.LowRankMatrix.collapse(), scipy.optimize._nonlin.LowRankMatrix.matvec(), scipy.optimize._nonlin.LowRankMatrix.restart_reduce(), scipy.optimize._nonlin.LowRankMatrix.rmatvec(), scipy.optimize._nonlin.LowRankMatrix.rsolve(), scipy.optimize._nonlin.LowRankMatrix.simple_reduce(), scipy.optimize._nonlin.LowRankMatrix.solve(), and scipy.optimize._nonlin.LowRankMatrix.svd_reduce().
tmpdir
numpy.lib.tests.test__datasource.TestDataSourceExists.tmpdir = mkdtemp()
Definition at line 160 of file test__datasource.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/lib/tests/test__datasource.py