Code Cloning Analysis: joblib.externals.loky.process_executor.ProcessPoolExecutor Class Reference
joblib.externals.loky.process_executor.ProcessPoolExecutor Class Reference
Public Member Functions
__init__ (self, max_workers=None, job_reducers=None, result_reducers=None, timeout=None, context=None, initializer=None, initargs=(), env=None)
submit (self, fn, *args, **kwargs)
map (self, fn, *iterables, **kwargs)
shutdown (self, wait=True, kill_workers=False)
Protected Member Functions
_setup_queues (self, job_reducers, result_reducers, queue_size=None)
_start_executor_manager_thread (self)
_adjust_process_count (self)
_ensure_executor_running (self)
Protected Attributes
_max_workers = cpu_count()
_context = context
_env = env
_initializer
_initargs
_timeout = timeout
_executor_manager_thread = None
dict _processes = {}
int _queue_count = 0
dict _pending_work_items = {}
list _running_work_items = []
_work_ids = queue.Queue()
_processes_management_lock = self._context.Lock()
_shutdown_lock = threading.Lock()
_executor_manager_thread_wakeup = _ThreadWakeup()
_flags = _ExecutorFlags(self._shutdown_lock)
_call_queue
_result_queue
Static Protected Attributes
_at_exit = None
Static Private Attributes
__doc__
Detailed Description
Definition at line 1053 of file process_executor.py.
Constructor & Destructor Documentation
__init__()
joblib.externals.loky.process_executor.ProcessPoolExecutor.__init__ (self, max_workers = None, job_reducers = None, result_reducers = None, timeout = None, context = None, initializer = None, initargs = (), env = None)
Initializes a new ProcessPoolExecutor instance.
Args:
    max_workers: int, optional (default: cpu_count())
        The maximum number of processes that can be used to execute the
        given calls. If None or not given then as many worker processes
        will be created as the number of CPUs the current process
        can use.
    job_reducers, result_reducers: dict(type: reducer_func)
        Custom reducer for pickling the jobs and the results from the
        Executor. If only `job_reducers` is provided, `result_reducer`
        will use the same reducers
    timeout: int, optional (default: None)
        Idle workers exit after timeout seconds. If a new job is
        submitted after the timeout, the executor will start enough
        new Python processes to make sure the pool of workers is full.
    context: A multiprocessing context to launch the workers. This
        object should provide SimpleQueue, Queue and Process.
    initializer: An callable used to initialize worker processes.
    initargs: A tuple of arguments to pass to the initializer.
    env: A dict of environment variable to overwrite in the child
        process. The environment variables are set before any module is
        loaded. Note that this only works with the loky context.
Definition at line 1057 of file process_executor.py.
References _call_queue, _context, _env, _executor_manager_thread, _executor_manager_thread_wakeup, _flags, _initargs, _initializer, _max_workers, _pending_work_items, _processes, _processes_management_lock, _queue_count, _result_queue, _running_work_items, _setup_queues(), _shutdown_lock, _timeout, and _work_ids.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_adjust_process_count()
joblib.externals.loky.process_executor.ProcessPoolExecutor._adjust_process_count (self) protected
Definition at line 1216 of file process_executor.py.
Referenced by _ensure_executor_running().
_ensure_executor_running()
joblib.externals.loky.process_executor.ProcessPoolExecutor._ensure_executor_running (self) protected
ensures all workers and management thread are running
Definition at line 1246 of file process_executor.py.
References _adjust_process_count(), _ensure_executor_running(), _executor_manager_thread_wakeup, _flags, _max_workers, _pending_work_items, _processes, _processes_management_lock, _queue_count, _start_executor_manager_thread(), and _work_ids.
Referenced by _ensure_executor_running().
_setup_queues()
joblib.externals.loky.process_executor.ProcessPoolExecutor._setup_queues (self, job_reducers, result_reducers, queue_size = None) protected
Definition at line 1162 of file process_executor.py.
Referenced by __init__().
_start_executor_manager_thread()
joblib.externals.loky.process_executor.ProcessPoolExecutor._start_executor_manager_thread (self) protected
Definition at line 1186 of file process_executor.py.
Referenced by _ensure_executor_running().
map()
joblib.externals.loky.process_executor.ProcessPoolExecutor.map (self, fn, * iterables, ** kwargs)
Returns an iterator equivalent to map(fn, iter).
Args:
    fn: A callable that will take as many arguments as there are
        passed iterables.
    timeout: The maximum number of seconds to wait. If None, then there
        is no limit on the wait time.
    chunksize: If greater than one, the iterables will be chopped into
        chunks of size chunksize and submitted to the process pool.
        If set to one, the items in the list will be sent one at a
        time.
Returns:
    An iterator equivalent to: map(func, *iterables) but the calls may
    be evaluated out-of-order.
Raises:
    TimeoutError: If the entire result iterator could not be generated
        before the given timeout.
    Exception: If fn(*args) raises for any values.
Reimplemented in joblib.executor._TestingMemmappingExecutor.
Definition at line 1283 of file process_executor.py.
References _call_queue, joblib.externals.loky.process_executor._chain_from_iterable_of_lists(), _executor_manager_thread, _executor_manager_thread_wakeup, _flags, joblib.externals.loky.process_executor._get_chunks(), _processes_management_lock, _result_queue, _shutdown_lock, and map().
Referenced by pandas.core.indexes.base.Index._format_flat(), pandas.core.frame.DataFrame.applymap(), pandas.io.formats.style.Styler.applymap(), pandas.core.indexes.base.Index.format(), pandas.core.indexes.datetimelike.DatetimeIndexOpsMixin.format(), map(), and pandas.io.formats.style.Styler.set_properties().
shutdown()
joblib.externals.loky.process_executor.ProcessPoolExecutor.shutdown (self, wait = True, kill_workers = False)
Definition at line 1317 of file process_executor.py.
Referenced by joblib.executor.MemmappingExecutor.get_memmapping_executor().
submit()
joblib.externals.loky.process_executor.ProcessPoolExecutor.submit (self, fn, * args, ** kwargs)
Definition at line 1253 of file process_executor.py.
Referenced by joblib.executor._TestingMemmappingExecutor.apply_async().
Member Data Documentation
__doc__
joblib.externals.loky.process_executor.ProcessPoolExecutor.__doc__ static private
Definition at line 1281 of file process_executor.py.
Referenced by scipy.stats._multivariate.multivariate_t_gen.__init__(), scipy.stats._distn_infrastructure.rv_discrete._attach_methods(), scipy.stats._distn_infrastructure.rv_generic._construct_default_doc(), scipy.stats._distn_infrastructure.rv_generic._construct_doc(), and pip._vendor.pygments.sphinxext.PygmentsDoc.document_lexers_overview().
_at_exit
joblib.externals.loky.process_executor.ProcessPoolExecutor._at_exit = None static protected
Definition at line 1055 of file process_executor.py.
_call_queue
joblib.externals.loky.process_executor.ProcessPoolExecutor._call_queue protected
Initial value:
=  _SafeQueue(
            max_size=queue_size,
            pending_work_items=self._pending_work_items,
            running_work_items=self._running_work_items,
            thread_wakeup=self._executor_manager_thread_wakeup,
            shutdown_lock=self._shutdown_lock,
            reducers=job_reducers,
            ctx=self._context,
        )
Definition at line 1168 of file process_executor.py.
Referenced by __init__(), and map().
_context
joblib.externals.loky.process_executor.ProcessPoolExecutor._context = context protected
Definition at line 1113 of file process_executor.py.
Referenced by __init__().
_env
joblib.externals.loky.process_executor.ProcessPoolExecutor._env = env protected
Definition at line 1114 of file process_executor.py.
Referenced by __init__().
_executor_manager_thread
joblib.externals.loky.process_executor.ProcessPoolExecutor._executor_manager_thread = None protected
Definition at line 1128 of file process_executor.py.
Referenced by __init__(), and map().
_executor_manager_thread_wakeup
joblib.externals.loky.process_executor.ProcessPoolExecutor._executor_manager_thread_wakeup = _ThreadWakeup() protected
Definition at line 1151 of file process_executor.py.
Referenced by __init__(), _ensure_executor_running(), and map().
_flags
joblib.externals.loky.process_executor.ProcessPoolExecutor._flags = _ExecutorFlags(self._shutdown_lock) protected
Definition at line 1155 of file process_executor.py.
Referenced by __init__(), _ensure_executor_running(), pandas.core.generic.NDFrame.flags(), and map().
_initargs
joblib.externals.loky.process_executor.ProcessPoolExecutor._initargs protected
Initial value:
=  _prepare_initializer(
            initializer, initargs
        )
Definition at line 1116 of file process_executor.py.
Referenced by __init__().
_initializer
joblib.externals.loky.process_executor.ProcessPoolExecutor._initializer protected
Definition at line 1116 of file process_executor.py.
Referenced by __init__().
_max_workers
joblib.externals.loky.process_executor.ProcessPoolExecutor._max_workers = cpu_count() protected
Definition at line 1095 of file process_executor.py.
Referenced by __init__(), _ensure_executor_running(), and joblib.externals.loky.reusable_executor._ReusablePoolExecutor._wait_job_completion().
_pending_work_items
dict joblib.externals.loky.process_executor.ProcessPoolExecutor._pending_work_items = {} protected
Definition at line 1136 of file process_executor.py.
Referenced by __init__(), _ensure_executor_running(), and joblib.externals.loky.reusable_executor._ReusablePoolExecutor._wait_job_completion().
_processes
joblib.externals.loky.process_executor.ProcessPoolExecutor._processes = {} protected
Definition at line 1131 of file process_executor.py.
Referenced by __init__(), and _ensure_executor_running().
_processes_management_lock
joblib.externals.loky.process_executor.ProcessPoolExecutor._processes_management_lock = self._context.Lock() protected
Definition at line 1139 of file process_executor.py.
Referenced by __init__(), _ensure_executor_running(), and map().
_queue_count
joblib.externals.loky.process_executor.ProcessPoolExecutor._queue_count = 0 protected
Definition at line 1135 of file process_executor.py.
Referenced by __init__(), and _ensure_executor_running().
_result_queue
joblib.externals.loky.process_executor.ProcessPoolExecutor._result_queue protected
Initial value:
=  SimpleQueue(
            reducers=result_reducers, ctx=self._context
        )
Definition at line 1182 of file process_executor.py.
Referenced by __init__(), and map().
_running_work_items
list joblib.externals.loky.process_executor.ProcessPoolExecutor._running_work_items = [] protected
Definition at line 1137 of file process_executor.py.
Referenced by __init__().
_shutdown_lock
joblib.externals.loky.process_executor.ProcessPoolExecutor._shutdown_lock = threading.Lock() protected
Definition at line 1141 of file process_executor.py.
Referenced by __init__(), and map().
_timeout
joblib.externals.loky.process_executor.ProcessPoolExecutor._timeout = timeout protected
Definition at line 1125 of file process_executor.py.
Referenced by __init__(), and pip._vendor.urllib3.contrib.securetransport.WrappedSocket.handshake().
_work_ids
joblib.externals.loky.process_executor.ProcessPoolExecutor._work_ids = queue.Queue() protected
Definition at line 1138 of file process_executor.py.
Referenced by __init__(), and _ensure_executor_running().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py