Code Cloning Analysis: pandas.tests.indexing.multiindex.test_setitem.TestMultiIndexSetItem Class Reference
pandas.tests.indexing.multiindex.test_setitem.TestMultiIndexSetItem Class Reference
Public Member Functions
check (self, target, indexers, value, compare_fn=assert_equal, expected=None)
test_setitem_multiindex (self)
test_setitem_multiindex2 (self)
test_setitem_multiindex3 (self)
test_multiindex_setitem (self)
test_multiindex_setitem2 (self)
test_multiindex_assignment (self)
test_multiindex_assignment_single_dtype (self, using_copy_on_write, warn_copy_on_write)
test_groupby_example (self)
test_series_setitem (self, multiindex_year_month_day_dataframe_random_data, warn_copy_on_write)
test_frame_getitem_setitem_boolean (self, multiindex_dataframe_random_data)
test_frame_getitem_setitem_multislice (self)
test_frame_setitem_multi_column (self)
test_frame_setitem_multi_column2 (self)
test_loc_getitem_tuple_plus_columns (self, multiindex_year_month_day_dataframe_random_data)
test_loc_getitem_setitem_slice_integers (self, frame_or_series)
test_setitem_change_dtype (self, multiindex_dataframe_random_data)
test_set_column_scalar_with_loc (self, multiindex_dataframe_random_data, using_copy_on_write, warn_copy_on_write)
test_nonunique_assignment_1750 (self)
test_astype_assignment_with_dups (self)
test_setitem_nonmonotonic (self)
Detailed Description
Definition at line 23 of file test_setitem.py.
Member Function Documentation
check()
pandas.tests.indexing.multiindex.test_setitem.TestMultiIndexSetItem.check (self, target, indexers, value, compare_fn = assert_equal, expected = None)
Definition at line 24 of file test_setitem.py.
Referenced by pandas.tests.indexing.test_floats.TestFloatIndexers.check(), pip._vendor.pygments.scanner.Scanner.test(), and pandas.tests.indexing.test_floats.TestFloatIndexers.test_integer_positional_indexing().
test_astype_assignment_with_dups()
pandas.tests.indexing.multiindex.test_setitem.TestMultiIndexSetItem.test_astype_assignment_with_dups (self)
Definition at line 460 of file test_setitem.py.
test_frame_getitem_setitem_boolean()
pandas.tests.indexing.multiindex.test_setitem.TestMultiIndexSetItem.test_frame_getitem_setitem_boolean (self, multiindex_dataframe_random_data)
Definition at line 301 of file test_setitem.py.
test_frame_getitem_setitem_multislice()
pandas.tests.indexing.multiindex.test_setitem.TestMultiIndexSetItem.test_frame_getitem_setitem_multislice (self)
Definition at line 326 of file test_setitem.py.
test_frame_setitem_multi_column()
pandas.tests.indexing.multiindex.test_setitem.TestMultiIndexSetItem.test_frame_setitem_multi_column (self)
Definition at line 349 of file test_setitem.py.
test_frame_setitem_multi_column2()
pandas.tests.indexing.multiindex.test_setitem.TestMultiIndexSetItem.test_frame_setitem_multi_column2 (self)
Definition at line 364 of file test_setitem.py.
test_groupby_example()
pandas.tests.indexing.multiindex.test_setitem.TestMultiIndexSetItem.test_groupby_example (self)
Definition at line 259 of file test_setitem.py.
test_loc_getitem_setitem_slice_integers()
pandas.tests.indexing.multiindex.test_setitem.TestMultiIndexSetItem.test_loc_getitem_setitem_slice_integers (self, frame_or_series)
Definition at line 399 of file test_setitem.py.
test_loc_getitem_tuple_plus_columns()
pandas.tests.indexing.multiindex.test_setitem.TestMultiIndexSetItem.test_loc_getitem_tuple_plus_columns (self, multiindex_year_month_day_dataframe_random_data)
Definition at line 387 of file test_setitem.py.
test_multiindex_assignment()
pandas.tests.indexing.multiindex.test_setitem.TestMultiIndexSetItem.test_multiindex_assignment (self)
Definition at line 188 of file test_setitem.py.
test_multiindex_assignment_single_dtype()
pandas.tests.indexing.multiindex.test_setitem.TestMultiIndexSetItem.test_multiindex_assignment_single_dtype (self, using_copy_on_write, warn_copy_on_write)
Definition at line 203 of file test_setitem.py.
test_multiindex_setitem()
pandas.tests.indexing.multiindex.test_setitem.TestMultiIndexSetItem.test_multiindex_setitem (self)
Definition at line 132 of file test_setitem.py.
test_multiindex_setitem2()
pandas.tests.indexing.multiindex.test_setitem.TestMultiIndexSetItem.test_multiindex_setitem2 (self)
Definition at line 157 of file test_setitem.py.
test_nonunique_assignment_1750()
pandas.tests.indexing.multiindex.test_setitem.TestMultiIndexSetItem.test_nonunique_assignment_1750 (self)
Definition at line 448 of file test_setitem.py.
test_series_setitem()
pandas.tests.indexing.multiindex.test_setitem.TestMultiIndexSetItem.test_series_setitem (self, multiindex_year_month_day_dataframe_random_data, warn_copy_on_write)
Definition at line 281 of file test_setitem.py.
test_set_column_scalar_with_loc()
pandas.tests.indexing.multiindex.test_setitem.TestMultiIndexSetItem.test_set_column_scalar_with_loc (self, multiindex_dataframe_random_data, using_copy_on_write, warn_copy_on_write)
Definition at line 429 of file test_setitem.py.
test_setitem_change_dtype()
pandas.tests.indexing.multiindex.test_setitem.TestMultiIndexSetItem.test_setitem_change_dtype (self, multiindex_dataframe_random_data)
Definition at line 418 of file test_setitem.py.
test_setitem_multiindex()
pandas.tests.indexing.multiindex.test_setitem.TestMultiIndexSetItem.test_setitem_multiindex (self)
Definition at line 31 of file test_setitem.py.
test_setitem_multiindex2()
pandas.tests.indexing.multiindex.test_setitem.TestMultiIndexSetItem.test_setitem_multiindex2 (self)
Definition at line 61 of file test_setitem.py.
test_setitem_multiindex3()
pandas.tests.indexing.multiindex.test_setitem.TestMultiIndexSetItem.test_setitem_multiindex3 (self)
Definition at line 80 of file test_setitem.py.
test_setitem_nonmonotonic()
pandas.tests.indexing.multiindex.test_setitem.TestMultiIndexSetItem.test_setitem_nonmonotonic (self)
Definition at line 470 of file test_setitem.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pandas/tests/indexing/multiindex/test_setitem.py