Code Cloning Analysis: matplotlib.hatch.VerticalHatch Class Reference
matplotlib.hatch.VerticalHatch Class Reference
Public Member Functions
__init__ (self, hatch, density)
set_vertices_and_codes (self, vertices, codes)
Public Attributes
num_lines = int((hatch.count('|') + hatch.count('+')) * density)
int num_vertices = self.num_lines * 2
Detailed Description
Definition at line 31 of file hatch.py.
Constructor & Destructor Documentation
__init__()
matplotlib.hatch.VerticalHatch.__init__ (self, hatch, density)
Definition at line 32 of file hatch.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
set_vertices_and_codes()
matplotlib.hatch.VerticalHatch.set_vertices_and_codes (self, vertices, codes)
Definition at line 36 of file hatch.py.
Member Data Documentation
num_lines
matplotlib.hatch.VerticalHatch.num_lines = int((hatch.count('|') + hatch.count('+')) * density)
Definition at line 33 of file hatch.py.
num_vertices
int matplotlib.hatch.VerticalHatch.num_vertices = self.num_lines * 2
Definition at line 34 of file hatch.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/hatch.py