Code Cloning Analysis: scipy.optimize.tests.test_linesearch Namespace Reference
scipy.optimize.tests.test_linesearch Namespace Reference
Classes
class TestLineSearch
Functions
assert_wolfe (s, phi, derphi, c1=1e-4, c2=0.9, err_msg="")
assert_armijo (s, phi, c1=1e-4, err_msg="")
assert_line_wolfe (x, p, s, f, fprime, **kw)
assert_line_armijo (x, p, s, f, **kw)
assert_fp_equal (x, y, err_msg="", nulp=50)
Detailed Description
Tests for line search routines
Function Documentation
assert_armijo()
scipy.optimize.tests.test_linesearch.assert_armijo (s, phi, c1 = 1e-4, err_msg = "")
Check that Armijo condition applies
Definition at line 27 of file test_linesearch.py.
References assert_armijo(), and assert_wolfe().
Referenced by assert_armijo().
assert_fp_equal()
scipy.optimize.tests.test_linesearch.assert_fp_equal (x, y, err_msg = "", nulp = 50)
Assert two arrays are equal, up to some floating-point rounding error
Definition at line 46 of file test_linesearch.py.
assert_line_armijo()
scipy.optimize.tests.test_linesearch.assert_line_armijo (x, p, s, f, ** kw)
Definition at line 42 of file test_linesearch.py.
assert_line_wolfe()
scipy.optimize.tests.test_linesearch.assert_line_wolfe (x, p, s, f, fprime, ** kw)
Definition at line 37 of file test_linesearch.py.
assert_wolfe()
scipy.optimize.tests.test_linesearch.assert_wolfe (s, phi, derphi, c1 = 1e-4, c2 = 0.9, err_msg = "")
Check that strong Wolfe conditions apply
Definition at line 12 of file test_linesearch.py.
Referenced by assert_armijo().