Code Cloning Analysis: pandas.core.internals.construction Namespace Reference
pandas.core.internals.construction Namespace Reference
Functions
Manager arrays_to_mgr (arrays, Index columns, index, *, DtypeObj|None dtype=None, bool verify_integrity=True, str|None typ=None, bool consolidate=True)
Manager rec_array_to_mgr (np.rec.recarray|np.ndarray data, index, columns, DtypeObj|None dtype, bool copy, str typ)
Manager mgr_to_mgr (mgr, str typ, bool copy=True)
Manager ndarray_to_mgr (values, index, columns, DtypeObj|None dtype, bool copy, str typ)
None _check_values_indices_shape_match (np.ndarray values, Index index, Index columns)
Manager dict_to_mgr (dict data, index, columns, *, DtypeObj|None dtype=None, str typ="block", bool copy=True)
tuple[list[ArrayLike], Index, Index] nested_data_to_arrays (Sequence data, Index|None columns, Index|None index, DtypeObj|None dtype)
bool treat_as_nested (data)
np.ndarray _prep_ndarraylike (values, bool copy=True)
np.ndarray _ensure_2d (np.ndarray values)
tuple[list[ArrayLike], list[Any]] _homogenize (data, Index index, DtypeObj|None dtype)
Index _extract_index (data)
tuple[list[ArrayLike], Index] reorder_arrays (list[ArrayLike] arrays, Index arr_columns, Index|None columns, int length)
Index _get_names_from_index (data)
tuple[Index, Index] _get_axes (int N, int K, Index|None index, Index|None columns)
dataclasses_to_dicts (data)
tuple[list[ArrayLike], Index] to_arrays (data, Index|None columns, DtypeObj|None dtype=None)
np.ndarray _list_to_arrays (list[tuple|list] data)
tuple[np.ndarray, Index] _list_of_series_to_arrays (list data, Index|None columns)
tuple[np.ndarray, Index] _list_of_dict_to_arrays (list[dict] data, Index|None columns)
tuple[list[ArrayLike], Index] _finalize_columns_and_data (np.ndarray content, Index|None columns, DtypeObj|None dtype)
Index _validate_or_indexify_columns (list[np.ndarray] content, Index|None columns)
list[ArrayLike] convert_object_array (list[npt.NDArray[np.object_]] content, DtypeObj|None dtype, str dtype_backend="numpy", bool coerce_float=False)
Detailed Description
Functions for preparing various inputs passed to the DataFrame or Series
constructors before passing them to a BlockManager.
Function Documentation
_check_values_indices_shape_match()
None pandas.core.internals.construction._check_values_indices_shape_match (np.ndarray values, Index index, Index columns) protected
Check that the shape implied by our axes matches the actual shape of the
data.
Definition at line 405 of file construction.py.
Referenced by mgr_to_mgr().
_ensure_2d()
np.ndarray pandas.core.internals.construction._ensure_2d (np.ndarray values) protected
Reshape 1D values, raise on anything else other than 2D.
Definition at line 585 of file construction.py.
Referenced by mgr_to_mgr(), and treat_as_nested().
_extract_index()
Index pandas.core.internals.construction._extract_index (data) protected
Try to infer an Index from the passed data, raise ValueError on failure.
Definition at line 638 of file construction.py.
Referenced by arrays_to_mgr(), and dict_to_mgr().
_finalize_columns_and_data()
tuple[list[ArrayLike], Index] pandas.core.internals.construction._finalize_columns_and_data (np.ndarray content, Index | None columns, DtypeObj | None dtype) protected
Ensure we have valid columns, cast object dtypes if possible.
Definition at line 928 of file construction.py.
References _validate_or_indexify_columns(), and convert_object_array().
Referenced by to_arrays().
_get_axes()
tuple[Index, Index] pandas.core.internals.construction._get_axes (int N, int K, Index | None index, Index | None columns) protected
Definition at line 742 of file construction.py.
_get_names_from_index()
Index pandas.core.internals.construction._get_names_from_index (data) protected
Definition at line 724 of file construction.py.
_homogenize()
tuple[list[ArrayLike], list[Any]] pandas.core.internals.construction._homogenize (data, Index index, DtypeObj | None dtype) protected
Definition at line 596 of file construction.py.
_list_of_dict_to_arrays()
tuple[np.ndarray, Index] pandas.core.internals.construction._list_of_dict_to_arrays (list[dict] data, Index | None columns) protected
Convert list of dicts to numpy arrays
if `columns` is not passed, column names are inferred from the records
- for OrderedDict and dicts, the column names match
  the key insertion-order from the first record to the last.
- For other kinds of dict-likes, the keys are lexically sorted.
Parameters
----------
data : iterable
    collection of records (OrderedDict, dict)
columns: iterables or None
Returns
-------
content : np.ndarray[object, ndim=2]
columns : Index
Definition at line 891 of file construction.py.
Referenced by to_arrays().
_list_of_series_to_arrays()
tuple[np.ndarray, Index] pandas.core.internals.construction._list_of_series_to_arrays (list data, Index | None columns) protected
Definition at line 860 of file construction.py.
_list_to_arrays()
np.ndarray pandas.core.internals.construction._list_to_arrays (list[tuple | list] data) protected
Definition at line 849 of file construction.py.
_prep_ndarraylike()
np.ndarray pandas.core.internals.construction._prep_ndarraylike (values, bool copy = True) protected
Definition at line 547 of file construction.py.
_validate_or_indexify_columns()
Index pandas.core.internals.construction._validate_or_indexify_columns (list[np.ndarray] content, Index | None columns) protected
If columns is None, make numbers as column names; Otherwise, validate that
columns have valid length.
Parameters
----------
content : list of np.ndarrays
columns : Index or None
Returns
-------
Index
    If columns is None, assign positional column index value as columns.
Raises
------
1. AssertionError when content is not composed of list of lists, and if
    length of columns is not equal to length of content.
2. ValueError when content is list of lists, but length of each sub-list
    is not equal
3. ValueError when content is list of lists, but length of sub-list is
    not equal to length of content
Definition at line 950 of file construction.py.
Referenced by _finalize_columns_and_data().
arrays_to_mgr()
Manager pandas.core.internals.construction.arrays_to_mgr (arrays, Index columns, index, * , DtypeObj | None dtype = None, bool verify_integrity = True, str | None typ = None, bool consolidate = True)
Segregate Series based on type and coerce into matrices.
Needs to handle a lot of exceptional cases.
Definition at line 96 of file construction.py.
References _extract_index().
Referenced by dict_to_mgr(), mgr_to_mgr(), and rec_array_to_mgr().
convert_object_array()
list[ArrayLike] pandas.core.internals.construction.convert_object_array (list[npt.NDArray[np.object_]] content, DtypeObj | None dtype, str dtype_backend = "numpy", bool coerce_float = False)
Internal function to convert object array.
Parameters
----------
content: List[np.ndarray]
dtype: np.dtype or ExtensionDtype
dtype_backend: Controls if nullable/pyarrow dtypes are returned.
coerce_float: Cast floats that are integers to int.
Returns
-------
List[ArrayLike]
Definition at line 1006 of file construction.py.
Referenced by _finalize_columns_and_data().
dataclasses_to_dicts()
pandas.core.internals.construction.dataclasses_to_dicts (data)
Converts a list of dataclass instances to a list of dictionaries.
Parameters
----------
data : List[Type[dataclass]]
Returns
--------
list_dict : List[dict]
Examples
--------
>>> from dataclasses import dataclass
>>> @dataclass
... class Point:
...     x: int
...     y: int
>>> dataclasses_to_dicts([Point(1, 2), Point(2, 3)])
[{'x': 1, 'y': 2}, {'x': 2, 'y': 3}]
Definition at line 760 of file construction.py.
dict_to_mgr()
Manager pandas.core.internals.construction.dict_to_mgr (dict data, index, columns, * , DtypeObj | None dtype = None, str typ = "block", bool copy = True)
Segregate Series based on type and coerce into matrices.
Needs to handle a lot of exceptional cases.
Used in DataFrame.__init__
Definition at line 423 of file construction.py.
References _extract_index(), and arrays_to_mgr().
mgr_to_mgr()
Manager pandas.core.internals.construction.mgr_to_mgr (mgr, str typ, bool copy = True)
Convert to specific type of Manager. Does not copy if the type is already
correct. Does not guarantee a copy otherwise. `copy` keyword only controls
whether conversion from Block->ArrayManager copies the 1D arrays.
Definition at line 196 of file construction.py.
References _check_values_indices_shape_match(), _ensure_2d(), and arrays_to_mgr().
ndarray_to_mgr()
Manager pandas.core.internals.construction.ndarray_to_mgr (values, index, columns, DtypeObj | None dtype, bool copy, str typ)
Definition at line 237 of file construction.py.
nested_data_to_arrays()
tuple[list[ArrayLike], Index, Index] pandas.core.internals.construction.nested_data_to_arrays (Sequence data, Index | None columns, Index | None index, DtypeObj | None dtype)
Convert a single sequence of arrays to multiple arrays.
Definition at line 506 of file construction.py.
References to_arrays().
rec_array_to_mgr()
Manager pandas.core.internals.construction.rec_array_to_mgr (np.rec.recarray | np.ndarray data, index, columns, DtypeObj | None dtype, bool copy, str typ)
Extract from a masked rec array and create the manager.
Definition at line 161 of file construction.py.
References arrays_to_mgr(), reorder_arrays(), and to_arrays().
reorder_arrays()
tuple[list[ArrayLike], Index] pandas.core.internals.construction.reorder_arrays (list[ArrayLike] arrays, Index arr_columns, Index | None columns, int length)
Pre-emptively (cheaply) reindex arrays with new columns.
Definition at line 697 of file construction.py.
Referenced by rec_array_to_mgr().
to_arrays()
tuple[list[ArrayLike], Index] pandas.core.internals.construction.to_arrays (data, Index | None columns, DtypeObj | None dtype = None)
Return list of arrays, columns.
Returns
-------
list[ArrayLike]
    These will become columns in a DataFrame.
Index
    This will become frame.columns.
Notes
-----
Ensures that len(result_arrays) == len(result_index).
Definition at line 793 of file construction.py.
References _finalize_columns_and_data(), and _list_of_dict_to_arrays().
Referenced by nested_data_to_arrays(), and rec_array_to_mgr().
treat_as_nested()
bool pandas.core.internals.construction.treat_as_nested (data)
Check if we should use nested_data_to_arrays.
Definition at line 532 of file construction.py.
References _ensure_2d().