Code Cloning Analysis: fontTools.ttLib.tables.E_B_L_C_.Strike Class Reference
fontTools.ttLib.tables.E_B_L_C_.Strike Class Reference
Public Member Functions
__init__ (self)
toXML (self, strikeIndex, writer, ttFont)
fromXML (self, name, attrs, content, ttFont, locator)
Public Attributes
bitmapSizeTable = BitmapSizeTable()
list indexSubTables = []
Detailed Description
Definition at line 270 of file E_B_L_C_.py.
Constructor & Destructor Documentation
__init__()
fontTools.ttLib.tables.E_B_L_C_.Strike.__init__ (self)
Definition at line 271 of file E_B_L_C_.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
fromXML()
fontTools.ttLib.tables.E_B_L_C_.Strike.fromXML (self, name, attrs, content, ttFont, locator)
Definition at line 288 of file E_B_L_C_.py.
toXML()
fontTools.ttLib.tables.E_B_L_C_.Strike.toXML (self, strikeIndex, writer, ttFont)
Definition at line 275 of file E_B_L_C_.py.
Member Data Documentation
bitmapSizeTable
fontTools.ttLib.tables.E_B_L_C_.Strike.bitmapSizeTable = BitmapSizeTable()
Definition at line 272 of file E_B_L_C_.py.
indexSubTables
list fontTools.ttLib.tables.E_B_L_C_.Strike.indexSubTables = []
Definition at line 273 of file E_B_L_C_.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ttLib/tables/E_B_L_C_.py