Code Cloning Analysis: scipy.special.tests.test_hyp2f1.TestHyp2f1 Class Reference
scipy.special.tests.test_hyp2f1.TestHyp2f1 Class Reference
Public Member Functions
test_c_non_positive_int (self, hyp2f1_test_case)
test_unital_argument (self, hyp2f1_test_case)
test_special_case_z_near_minus_1 (self, hyp2f1_test_case)
test_a_b_negative_int (self, hyp2f1_test_case)
test_a_b_neg_int_after_euler_hypergeometric_transformation (self, hyp2f1_test_case)
test_region1 (self, hyp2f1_test_case)
test_region2 (self, hyp2f1_test_case)
test_region4 (self, hyp2f1_test_case)
test_region5 (self, hyp2f1_test_case)
test_region6 (self, hyp2f1_test_case)
test_test_hyp2f1 (self)
Protected Member Functions
_get_test_parameters (self, test_method)
Detailed Description
Tests for hyp2f1 for complex values.
Expected values for test cases were computed using mpmath. See
`scipy.special._precompute.hyp2f1_data`. The verbose style of specifying
test cases is used for readability and to make it easier to mark individual
cases as expected to fail. Expected failures are used to highlight cases
where improvements are needed. See
`scipy.special._precompute.hyp2f1_data.make_hyp2f1_test_cases` for a
function to generate the boilerplate for the test cases.
Assertions have been added to each test to ensure that the test cases match
the situations that are intended. A final test `test_test_hyp2f1` checks
that the expected values in the test cases actually match what is computed
by mpmath. This test is marked slow even though it isn't particularly slow
so that it won't run by default on continuous integration builds.
Definition at line 58 of file test_hyp2f1.py.
Member Function Documentation
_get_test_parameters()
scipy.special.tests.test_hyp2f1.TestHyp2f1._get_test_parameters (self, test_method) protected
Get pytest.mark parameters for a test in this class.
Definition at line 2174 of file test_hyp2f1.py.
Referenced by test_test_hyp2f1().
test_a_b_neg_int_after_euler_hypergeometric_transformation()
scipy.special.tests.test_hyp2f1.TestHyp2f1.test_a_b_neg_int_after_euler_hypergeometric_transformation (self, hyp2f1_test_case)
Definition at line 522 of file test_hyp2f1.py.
test_a_b_negative_int()
scipy.special.tests.test_hyp2f1.TestHyp2f1.test_a_b_negative_int (self, hyp2f1_test_case)
Definition at line 462 of file test_hyp2f1.py.
test_c_non_positive_int()
scipy.special.tests.test_hyp2f1.TestHyp2f1.test_c_non_positive_int (self, hyp2f1_test_case)
Definition at line 190 of file test_hyp2f1.py.
test_region1()
scipy.special.tests.test_hyp2f1.TestHyp2f1.test_region1 (self, hyp2f1_test_case)
|z| < 0.9 and real(z) >= 0.
Definition at line 628 of file test_hyp2f1.py.
test_region2()
scipy.special.tests.test_hyp2f1.TestHyp2f1.test_region2 (self, hyp2f1_test_case)
|z| < 1 and real(z) < 0.
Definition at line 889 of file test_hyp2f1.py.
test_region4()
scipy.special.tests.test_hyp2f1.TestHyp2f1.test_region4 (self, hyp2f1_test_case)
0.9 <= |z| <= 1 and |1 - z| >= 1.
This region is unhandled by of the standard transformations and
needs special care.
Definition at line 1386 of file test_hyp2f1.py.
test_region5()
scipy.special.tests.test_hyp2f1.TestHyp2f1.test_region5 (self, hyp2f1_test_case)
1 < |z| < 1.1 and |1 - z| >= 0.9 and real(z) >= 0
Definition at line 1887 of file test_hyp2f1.py.
test_region6()
scipy.special.tests.test_hyp2f1.TestHyp2f1.test_region6 (self, hyp2f1_test_case)
|z| > 1 but not in region 5.
Definition at line 2138 of file test_hyp2f1.py.
test_special_case_z_near_minus_1()
scipy.special.tests.test_hyp2f1.TestHyp2f1.test_special_case_z_near_minus_1 (self, hyp2f1_test_case)
Tests for case z ~ -1, c ~ 1 + a - b
Expected answers computed using mpmath.
Definition at line 368 of file test_hyp2f1.py.
test_test_hyp2f1()
scipy.special.tests.test_hyp2f1.TestHyp2f1.test_test_hyp2f1 (self)
Test that expected values match what is computed by mpmath.
This gathers the parameters for the test cases out of the pytest marks.
The parameters are a, b, c, z, expected, rtol, where expected should
be the value of hyp2f1(a, b, c, z) computed with mpmath. The test
recomputes hyp2f1(a, b, c, z) using mpmath and verifies that expected
actually is the correct value. This allows the data for the tests to
live within the test code instead of an external datafile, while
avoiding having to compute the results with mpmath during the test,
except for when slow tests are being run.
Definition at line 2149 of file test_hyp2f1.py.
References _get_test_parameters(), and scipy.special.tests.test_hyp2f1.mp_hyp2f1().
test_unital_argument()
scipy.special.tests.test_hyp2f1.TestHyp2f1.test_unital_argument (self, hyp2f1_test_case)
Tests for case z = 1, c - a - b > 0.
Expected answers computed using mpmath.
Definition at line 311 of file test_hyp2f1.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/special/tests/test_hyp2f1.py