Code Cloning Analysis: scipy.interpolate._rbf.Rbf Class Reference
scipy.interpolate._rbf.Rbf Class Reference
Public Member Functions
__init__ (self, *args, **kwargs)
A (self)
__call__ (self, *args)
Public Attributes
function = getattr(self, "_h_"+self.function)
xi
N = self.xi.shape[-1]
str mode = kwargs.pop('mode', '1-D')
di = np.asarray(args[-1]).flatten()
norm = kwargs.pop('norm', 'euclidean')
epsilon = kwargs.pop('epsilon', None)
smooth = kwargs.pop('smooth', 0.0)
nodes = np.zeros((self.N, self._target_dim), dtype=self.di.dtype)
Protected Member Functions
_h_multiquadric (self, r)
_h_inverse_multiquadric (self, r)
_h_gaussian (self, r)
_h_linear (self, r)
_h_cubic (self, r)
_h_quintic (self, r)
_h_thin_plate (self, r)
_init_function (self, r)
_call_norm (self, x1, x2)
Protected Attributes
_function = getattr(self, func_name)
int _target_dim = 1
Detailed Description
Rbf(*args, **kwargs)
A class for radial basis function interpolation of functions from
N-D scattered data to an M-D domain.
.. legacy:: class
    `Rbf` is legacy code, for new usage please use `RBFInterpolator`
    instead.
Parameters
----------
*args : arrays
    x, y, z, ..., d, where x, y, z, ... are the coordinates of the nodes
    and d is the array of values at the nodes
function : str or callable, optional
    The radial basis function, based on the radius, r, given by the norm
    (default is Euclidean distance); the default is 'multiquadric'::
        'multiquadric': sqrt((r/self.epsilon)**2 + 1)
        'inverse': 1.0/sqrt((r/self.epsilon)**2 + 1)
        'gaussian': exp(-(r/self.epsilon)**2)
        'linear': r
        'cubic': r**3
        'quintic': r**5
        'thin_plate': r**2 * log(r)
    If callable, then it must take 2 arguments (self, r). The epsilon
    parameter will be available as self.epsilon. Other keyword
    arguments passed in will be available as well.
epsilon : float, optional
    Adjustable constant for gaussian or multiquadrics functions
    - defaults to approximate average distance between nodes (which is
    a good start).
smooth : float, optional
    Values greater than zero increase the smoothness of the
    approximation. 0 is for interpolation (default), the function will
    always go through the nodal points in this case.
norm : str, callable, optional
    A function that returns the 'distance' between two points, with
    inputs as arrays of positions (x, y, z, ...), and an output as an
    array of distance. E.g., the default: 'euclidean', such that the result
    is a matrix of the distances from each point in ``x1`` to each point in
    ``x2``. For more options, see documentation of
    `scipy.spatial.distances.cdist`.
mode : str, optional
    Mode of the interpolation, can be '1-D' (default) or 'N-D'. When it is
    '1-D' the data `d` will be considered as 1-D and flattened
    internally. When it is 'N-D' the data `d` is assumed to be an array of
    shape (n_samples, m), where m is the dimension of the target domain.
Attributes
----------
N : int
    The number of data points (as determined by the input arrays).
di : ndarray
    The 1-D array of data values at each of the data coordinates `xi`.
xi : ndarray
    The 2-D array of data coordinates.
function : str or callable
    The radial basis function. See description under Parameters.
epsilon : float
    Parameter used by gaussian or multiquadrics functions. See Parameters.
smooth : float
    Smoothing parameter. See description under Parameters.
norm : str or callable
    The distance function. See description under Parameters.
mode : str
    Mode of the interpolation. See description under Parameters.
nodes : ndarray
    A 1-D array of node values for the interpolation.
A : internal property, do not use
See Also
--------
RBFInterpolator
Examples
--------
>>> import numpy as np
>>> from scipy.interpolate import Rbf
>>> rng = np.random.default_rng()
>>> x, y, z, d = rng.random((4, 50))
>>> rbfi = Rbf(x, y, z, d)  # radial basis function interpolator instance
>>> xi = yi = zi = np.linspace(0, 1, 20)
>>> di = rbfi(xi, yi, zi)   # interpolated values
>>> di.shape
(20,)
Definition at line 55 of file _rbf.py.
Constructor & Destructor Documentation
__init__()
scipy.interpolate._rbf.Rbf.__init__ (self, * args, ** kwargs)
Definition at line 218 of file _rbf.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
__call__()
scipy.interpolate._rbf.Rbf.__call__ (self, * args)
Definition at line 280 of file _rbf.py.
_call_norm()
scipy.interpolate._rbf.Rbf._call_norm (self, x1, x2) protected
Definition at line 277 of file _rbf.py.
_h_cubic()
scipy.interpolate._rbf.Rbf._h_cubic (self, r) protected
Definition at line 163 of file _rbf.py.
_h_gaussian()
scipy.interpolate._rbf.Rbf._h_gaussian (self, r) protected
Definition at line 157 of file _rbf.py.
_h_inverse_multiquadric()
scipy.interpolate._rbf.Rbf._h_inverse_multiquadric (self, r) protected
Definition at line 154 of file _rbf.py.
_h_linear()
scipy.interpolate._rbf.Rbf._h_linear (self, r) protected
Definition at line 160 of file _rbf.py.
_h_multiquadric()
scipy.interpolate._rbf.Rbf._h_multiquadric (self, r) protected
Definition at line 151 of file _rbf.py.
_h_quintic()
scipy.interpolate._rbf.Rbf._h_quintic (self, r) protected
Definition at line 166 of file _rbf.py.
_h_thin_plate()
scipy.interpolate._rbf.Rbf._h_thin_plate (self, r) protected
Definition at line 169 of file _rbf.py.
_init_function()
scipy.interpolate._rbf.Rbf._init_function (self, r) protected
Definition at line 173 of file _rbf.py.
A()
scipy.interpolate._rbf.Rbf.A (self)
Definition at line 271 of file _rbf.py.
Member Data Documentation
_function
scipy.interpolate._rbf.Rbf._function = getattr(self, func_name) protected
Definition at line 184 of file _rbf.py.
_target_dim
scipy.interpolate._rbf.Rbf._target_dim = 1 protected
Definition at line 231 of file _rbf.py.
di
scipy.interpolate._rbf.Rbf.di = np.asarray(args[-1]).flatten()
Definition at line 230 of file _rbf.py.
epsilon
scipy.interpolate._rbf.Rbf.epsilon = kwargs.pop('epsilon', None)
Definition at line 242 of file _rbf.py.
Referenced by scipy.interpolate._rbfinterp.RBFInterpolator.__call__(), sklearn.neural_network._multilayer_perceptron.BaseMultilayerPerceptron._backprop(), scipy.interpolate._rbfinterp.RBFInterpolator._chunk_evaluator(), sklearn.svm._base.BaseLibSVM._decision_function(), sklearn.linear_model._stochastic_gradient.BaseSGD._get_loss_function(), sklearn.neural_network._stochastic_optimizers.AdamOptimizer._get_updates(), sklearn.svm._base.BaseLibSVM._validate_targets(), sklearn.linear_model._huber.HuberRegressor.fit(), sklearn.svm._classes.LinearSVR.fit(), sklearn.svm._base.BaseLibSVM.predict(), and sklearn.svm._base.BaseSVC.predict_log_proba().
function
scipy.interpolate._rbf.Rbf.function = getattr(self, "_h_"+self.function)
Definition at line 174 of file _rbf.py.
mode
str scipy.interpolate._rbf.Rbf.mode = kwargs.pop('mode', '1-D')
Definition at line 227 of file _rbf.py.
Referenced by scipy.io._netcdf.netcdf_file.__init__(), sklearn.covariance._graph_lasso.GraphicalLasso.fit(), sklearn.covariance._graph_lasso.GraphicalLassoCV.fit(), sklearn.cross_decomposition._pls._PLS.fit(), scipy.io._netcdf.netcdf_file.flush(), sklearn.neighbors._graph.KNeighborsTransformer.transform(), and sklearn.neighbors._graph.RadiusNeighborsTransformer.transform().
N
scipy.interpolate._rbf.Rbf.N = self.xi.shape[-1]
Definition at line 225 of file _rbf.py.
nodes
scipy.interpolate._rbf.Rbf.nodes = np.zeros((self.N, self._target_dim), dtype=self.di.dtype)
Definition at line 263 of file _rbf.py.
Referenced by sklearn.ensemble._hist_gradient_boosting.predictor.TreePredictor.compute_partial_dependence(), sklearn.ensemble._hist_gradient_boosting.predictor.TreePredictor.get_max_depth(), sklearn.ensemble._hist_gradient_boosting.predictor.TreePredictor.get_n_leaf_nodes(), sklearn.ensemble._hist_gradient_boosting.predictor.TreePredictor.predict(), and sklearn.ensemble._hist_gradient_boosting.predictor.TreePredictor.predict_binned().
norm
scipy.interpolate._rbf.Rbf.norm = kwargs.pop('norm', 'euclidean')
Definition at line 241 of file _rbf.py.
Referenced by matplotlib.contour.ContourSet.__init__(), matplotlib.contour.ContourSet._get_lowers_and_uppers(), matplotlib.contour.ContourSet._process_colors(), sklearn.naive_bayes.ComplementNB._update_feature_log_prob(), and sklearn.preprocessing._data.Normalizer.transform().
smooth
scipy.interpolate._rbf.Rbf.smooth = kwargs.pop('smooth', 0.0)
Definition at line 252 of file _rbf.py.
Referenced by sklearn.preprocessing._target_encoder.TargetEncoder._fit_encoding_binary_or_continuous().
xi
scipy.interpolate._rbf.Rbf.xi
Initial value:
=  np.asarray([np.asarray(a, dtype=np.float_).flatten()
                              for a in args[:-1]])
Definition at line 223 of file _rbf.py.
Referenced by sklearn.cluster._optics.OPTICS.fit().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/interpolate/_rbf.py