Code Cloning Analysis: scipy._lib._ccallback.LowLevelCallable Class Reference
scipy._lib._ccallback.LowLevelCallable Class Reference
Public Member Functions
__new__ (cls, function, user_data=None, signature=None)
__repr__ (self)
function (self)
user_data (self)
signature (self)
__getitem__ (self, idx)
from_cython (cls, module, name, user_data=None, signature=None)
Protected Member Functions
_parse_callback (cls, obj, user_data=None, signature=None)
Static Private Attributes
tuple __slots__ = ()
Detailed Description
Low-level callback function.
Some functions in SciPy take as arguments callback functions, which
can either be python callables or low-level compiled functions. Using
compiled callback functions can improve performance somewhat by
avoiding wrapping data in Python objects.
Such low-level functions in SciPy are wrapped in `LowLevelCallable`
objects, which can be constructed from function pointers obtained from
ctypes, cffi, Cython, or contained in Python `PyCapsule` objects.
.. seealso::
   Functions accepting low-level callables:
   `scipy.integrate.quad`, `scipy.ndimage.generic_filter`,
   `scipy.ndimage.generic_filter1d`, `scipy.ndimage.geometric_transform`
   Usage examples:
   :ref:`ndimage-ccallbacks`, :ref:`quad-callbacks`
Parameters
----------
function : {PyCapsule, ctypes function pointer, cffi function pointer}
    Low-level callback function.
user_data : {PyCapsule, ctypes void pointer, cffi void pointer}
    User data to pass on to the callback function.
signature : str, optional
    Signature of the function. If omitted, determined from *function*,
    if possible.
Attributes
----------
function
    Callback function given.
user_data
    User data given.
signature
    Signature of the function.
Methods
-------
from_cython
    Class method for constructing callables from Cython C-exported
    functions.
Notes
-----
The argument ``function`` can be one of:
- PyCapsule, whose name contains the C function signature
- ctypes function pointer
- cffi function pointer
The signature of the low-level callback must match one of those expected
by the routine it is passed to.
If constructing low-level functions from a PyCapsule, the name of the
capsule must be the corresponding signature, in the format::
    return_type (arg1_type, arg2_type, ...)
For example::
    "void (double)"
    "double (double, int *, void *)"
The context of a PyCapsule passed in as ``function`` is used as ``user_data``,
if an explicit value for ``user_data`` was not given.
Definition at line 26 of file _ccallback.py.
Member Function Documentation
__getitem__()
scipy._lib._ccallback.LowLevelCallable.__getitem__ (self, idx)
Definition at line 125 of file _ccallback.py.
__new__()
scipy._lib._ccallback.LowLevelCallable.__new__ (cls, function, user_data = None, signature = None)
Definition at line 104 of file _ccallback.py.
Referenced by matplotlib.path.Path._fast_from_codes_and_verts(), pandas.core.generic.NDFrame._from_mgr(), pandas.core.arrays.string_.StringArray._from_sequence(), scipy.interpolate._fitpack2._BivariateSplineBase._from_tck(), scipy.interpolate._fitpack2.UnivariateSpline._from_tck(), matplotlib.colors.Colormap._get_rgba_and_mask(), pip._vendor.rich.style.Style.clear_meta_and_links(), matplotlib.colors.MultivarColormap.copy(), pip._vendor.rich.style.Style.copy(), pip._vendor.rich.style.Style.from_color(), pip._vendor.rich.json.JSON.from_data(), pip._vendor.rich.style.Style.from_meta(), matplotlib.colors.BivarColormap.lut(), pip._vendor.rich.style.Style.test(), pip._vendor.rich.style.Style.update_link(), and pip._vendor.rich.style.Style.without_color().
__repr__()
scipy._lib._ccallback.LowLevelCallable.__repr__ (self)
Definition at line 110 of file _ccallback.py.
_parse_callback()
scipy._lib._ccallback.LowLevelCallable._parse_callback (cls, obj, user_data = None, signature = None) protected
Definition at line 154 of file _ccallback.py.
from_cython()
scipy._lib._ccallback.LowLevelCallable.from_cython (cls, module, name, user_data = None, signature = None)
Create a low-level callback function from an exported Cython function.
Parameters
----------
module : module
    Cython module where the exported function resides
name : str
    Name of the exported function
user_data : {PyCapsule, ctypes void pointer, cffi void pointer}, optional
    User data to pass on to the callback function.
signature : str, optional
    Signature of the function. If omitted, determined from *function*.
Definition at line 129 of file _ccallback.py.
function()
scipy._lib._ccallback.LowLevelCallable.function (self)
Definition at line 114 of file _ccallback.py.
signature()
scipy._lib._ccallback.LowLevelCallable.signature (self)
Definition at line 122 of file _ccallback.py.
Referenced by fontTools.ttLib.sfnt.SFNTReader.__getitem__().
user_data()
scipy._lib._ccallback.LowLevelCallable.user_data (self)
Definition at line 118 of file _ccallback.py.
Member Data Documentation
__slots__
tuple scipy._lib._ccallback.LowLevelCallable.__slots__ = () static private
Definition at line 102 of file _ccallback.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/scipy/_lib/_ccallback.py