Code Cloning Analysis: pandas.core.apply Namespace Reference
pandas.core.apply Namespace Reference
Classes
class Apply
class FrameApply
class FrameColumnApply
class FrameRowApply
class GroupByApply
class NDFrameApply
class ResamplerWindowApply
class SeriesApply
Functions
FrameApply frame_apply (DataFrame obj, AggFuncType func, Axis axis=0, bool raw=False, str|None result_type=None, Literal[False, "compat"] by_row="compat", str engine="python", dict[str, bool]|None engine_kwargs=None, args=None, kwargs=None)
tuple[bool, AggFuncType, tuple[str,...]|None, npt.NDArray[np.intp]|None] reconstruct_func (AggFuncType|None func, **kwargs)
bool is_multi_agg_with_relabel (**kwargs)
tuple[ MutableMapping[Hashable, list[AggFuncTypeBase]], tuple[str,...], npt.NDArray[np.intp],] normalize_keyword_aggregation (dict kwargs)
Sequence[tuple[Any, Any]] _make_unique_kwarg_list (Sequence[tuple[Any, Any]] seq)
dict[Hashable, Series] relabel_result (DataFrame|Series result, dict[str, list[Callable|str]] func, Iterable[Hashable] columns, Iterable[int] order)
DataFrame|Series reconstruct_and_relabel_result (result, func, **kwargs)
Sequence[Any] _managle_lambda_list (Sequence[Any] aggfuncs)
Any maybe_mangle_lambdas (Any agg_spec)
tuple[list[str], list[str|Callable[..., Any]]] validate_func_kwargs (dict kwargs)
bool include_axis (Literal["agg", "apply"] op_name, Series|DataFrame colg)
None warn_alias_replacement (AggObjType obj, Callable func, str alias)
Variables
ResType = dict[int, Any]
Function Documentation
_make_unique_kwarg_list()
Sequence[tuple[Any, Any]] pandas.core.apply._make_unique_kwarg_list (Sequence[tuple[Any, Any]] seq) protected
Uniquify aggfunc name of the pairs in the order list
Examples:
--------
>>> kwarg_list = [('a', '<lambda>'), ('a', '<lambda>'), ('b', '<lambda>')]
>>> _make_unique_kwarg_list(kwarg_list)
[('a', '<lambda>_0'), ('a', '<lambda>_1'), ('b', '<lambda>')]
Definition at line 1794 of file apply.py.
Referenced by normalize_keyword_aggregation().
_managle_lambda_list()
Sequence[Any] pandas.core.apply._managle_lambda_list (Sequence[Any] aggfuncs) protected
Possibly mangle a list of aggfuncs.
Parameters
----------
aggfuncs : Sequence
Returns
-------
mangled: list-like
    A new AggSpec sequence, where lambdas have been converted
    to have unique names.
Notes
-----
If just one aggfunc is passed, the name will not be mangled.
Definition at line 1921 of file apply.py.
Referenced by maybe_mangle_lambdas().
frame_apply()
FrameApply pandas.core.apply.frame_apply (DataFrame obj, AggFuncType func, Axis axis = 0, bool raw = False, str | None result_type = None, Literal[False, "compat"] by_row = "compat", str engine = "python", dict[str, bool] | None engine_kwargs = None, args = None, kwargs = None)
construct and return a row or column based frame apply object
Definition at line 82 of file apply.py.
References reconstruct_func().
include_axis()
bool pandas.core.apply.include_axis (Literal["agg", "apply"] op_name, Series | DataFrame colg)
Definition at line 2034 of file apply.py.
is_multi_agg_with_relabel()
bool pandas.core.apply.is_multi_agg_with_relabel (** kwargs)
Check whether kwargs passed to .agg look like multi-agg with relabeling.
Parameters
----------
**kwargs : dict
Returns
-------
bool
Examples
--------
>>> is_multi_agg_with_relabel(a="max")
False
>>> is_multi_agg_with_relabel(a_max=("a", "max"), a_min=("a", "min"))
True
>>> is_multi_agg_with_relabel()
False
Definition at line 1707 of file apply.py.
Referenced by reconstruct_func().
maybe_mangle_lambdas()
Any pandas.core.apply.maybe_mangle_lambdas (Any agg_spec)
Make new lambdas with unique names.
Parameters
----------
agg_spec : Any
    An argument to GroupBy.agg.
    Non-dict-like `agg_spec` are pass through as is.
    For dict-like `agg_spec` a new spec is returned
    with name-mangled lambdas.
Returns
-------
mangled : Any
    Same type as the input.
Examples
--------
>>> maybe_mangle_lambdas('sum')
'sum'
>>> maybe_mangle_lambdas([lambda: 1, lambda: 2])  # doctest: +SKIP
[<function __main__.<lambda_0>,
 <function pandas...._make_lambda.<locals>.f(*args, **kwargs)>]
Definition at line 1954 of file apply.py.
References _managle_lambda_list().
normalize_keyword_aggregation()
tuple[ MutableMapping[Hashable, list[AggFuncTypeBase]], tuple[str, ...], npt.NDArray[np.intp], ] pandas.core.apply.normalize_keyword_aggregation (dict kwargs)
Normalize user-provided "named aggregation" kwargs.
Transforms from the new ``Mapping[str, NamedAgg]`` style kwargs
to the old Dict[str, List[scalar]]].
Parameters
----------
kwargs : dict
Returns
-------
aggspec : dict
    The transformed kwargs.
columns : tuple[str, ...]
    The user-provided keys.
col_idx_order : List[int]
    List of columns indices.
Examples
--------
>>> normalize_keyword_aggregation({"output": ("input", "sum")})
(defaultdict(<class 'list'>, {'input': ['sum']}), ('output',), array([0]))
Definition at line 1733 of file apply.py.
References _make_unique_kwarg_list().
Referenced by reconstruct_func().
reconstruct_and_relabel_result()
DataFrame | Series pandas.core.apply.reconstruct_and_relabel_result (result, func, ** kwargs)
Definition at line 1894 of file apply.py.
reconstruct_func()
tuple[bool, AggFuncType, tuple[str, ...] | None, npt.NDArray[np.intp] | None] pandas.core.apply.reconstruct_func (AggFuncType | None func, ** kwargs)
This is the internal function to reconstruct func given if there is relabeling
or not and also normalize the keyword to get new order of columns.
If named aggregation is applied, `func` will be None, and kwargs contains the
column and aggregation function information to be parsed;
If named aggregation is not applied, `func` is either string (e.g. 'min') or
Callable, or list of them (e.g. ['min', np.max]), or the dictionary of column name
and str/Callable/list of them (e.g. {'A': 'min'}, or {'A': [np.min, lambda x: x]})
If relabeling is True, will return relabeling, reconstructed func, column
names, and the reconstructed order of columns.
If relabeling is False, the columns and order will be None.
Parameters
----------
func: agg function (e.g. 'min' or Callable) or list of agg functions
    (e.g. ['min', np.max]) or dictionary (e.g. {'A': ['min', np.max]}).
**kwargs: dict, kwargs used in is_multi_agg_with_relabel and
    normalize_keyword_aggregation function for relabelling
Returns
-------
relabelling: bool, if there is relabelling or not
func: normalized and mangled func
columns: tuple of column names
order: array of columns indices
Examples
--------
>>> reconstruct_func(None, **{"foo": ("col", "min")})
(True, defaultdict(<class 'list'>, {'col': ['min']}), ('foo',), array([0]))
>>> reconstruct_func("min")
(False, 'min', None, None)
Definition at line 1638 of file apply.py.
References is_multi_agg_with_relabel(), and normalize_keyword_aggregation().
Referenced by frame_apply(), and relabel_result().
relabel_result()
dict[Hashable, Series] pandas.core.apply.relabel_result (DataFrame | Series result, dict[str, list[Callable | str]] func, Iterable[Hashable] columns, Iterable[int] order)
Internal function to reorder result if relabelling is True for
dataframe.agg, and return the reordered result in dict.
Parameters:
----------
result: Result from aggregation
func: Dict of (column name, funcs)
columns: New columns name for relabelling
order: New order for relabelling
Examples
--------
>>> from pandas.core.apply import relabel_result
>>> result = pd.DataFrame(
...     {"A": [np.nan, 2, np.nan], "C": [6, np.nan, np.nan], "B": [np.nan, 4, 2.5]},
...     index=["max", "mean", "min"]
...)
>>> funcs = {"A": ["max"], "C": ["max"], "B": ["mean", "min"]}
>>> columns = ("foo", "aab", "bar", "dat")
>>> order = [0, 1, 2, 3]
>>> result_in_dict = relabel_result(result, funcs, columns, order)
>>> pd.DataFrame(result_in_dict, index=columns)
       A    C    B
foo  2.0  NaN  NaN
aab  NaN  6.0  NaN
bar  NaN  NaN  4.0
dat  NaN  NaN  2.5
Definition at line 1812 of file apply.py.
References reconstruct_func(), and relabel_result().
Referenced by relabel_result().
validate_func_kwargs()
tuple[list[str], list[str | Callable[..., Any]]] pandas.core.apply.validate_func_kwargs (dict kwargs)
Validates types of user-provided "named aggregation" kwargs.
`TypeError` is raised if aggfunc is not `str` or callable.
Parameters
----------
kwargs : dict
Returns
-------
columns : List[str]
    List of user-provided keys.
func : List[Union[str, callable[...,Any]]]
    List of user-provided aggfuncs
Examples
--------
>>> validate_func_kwargs({'one': 'min', 'two': 'max'})
(['one', 'two'], ['min', 'max'])
Definition at line 1998 of file apply.py.
warn_alias_replacement()
None pandas.core.apply.warn_alias_replacement (AggObjType obj, Callable func, str alias)
Definition at line 2040 of file apply.py.
Variable Documentation
ResType
pandas.core.apply.ResType = dict[int, Any]
Definition at line 79 of file apply.py.