Code Cloning Analysis: matplotlib.offsetbox.DraggableBase Class Reference
matplotlib.offsetbox.DraggableBase Class Reference
Public Member Functions
__init__ (self, ref_artist, use_blit=False)
on_motion (self, evt)
on_pick (self, evt)
on_release (self, event)
disconnect (self)
save_offset (self)
update_offset (self, dx, dy)
finalize_offset (self)
Public Attributes
ref_artist = ref_artist
bool got_artist = False
background = evt.y - self.mouse_y
mouse_x = evt.mouseevent.x
mouse_y = evt.mouseevent.y
Protected Member Functions
_check_still_parented (self)
Static Protected Member Functions
_picker (artist, mouseevent)
Protected Attributes
_picker
_use_blit = use_blit and self.canvas.supports_blit
list _disconnectors
Properties
canvas = property(lambda self: self.ref_artist.get_figure(root=True).canvas)
cids
Detailed Description
Helper base class for a draggable artist (legend, offsetbox).
Derived classes must override the following methods::
    def save_offset(self):
        '''
        Called when the object is picked for dragging; should save the
        reference position of the artist.
        '''
    def update_offset(self, dx, dy):
        '''
        Called during the dragging; (*dx*, *dy*) is the pixel offset from
        the point where the mouse drag started.
        '''
Optionally, you may override the following method::
    def finalize_offset(self):
        '''Called when the mouse is released.'''
In the current implementation of `.DraggableLegend` and
`DraggableAnnotation`, `update_offset` places the artists in display
coordinates, and `finalize_offset` recalculates their position in axes
coordinate and set a relevant attribute.
Definition at line 1460 of file offsetbox.py.
Constructor & Destructor Documentation
__init__()
matplotlib.offsetbox.DraggableBase.__init__ (self, ref_artist, use_blit = False)
Definition at line 1489 of file offsetbox.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_check_still_parented()
matplotlib.offsetbox.DraggableBase._check_still_parented (self) protected
Definition at line 1554 of file offsetbox.py.
_picker()
matplotlib.offsetbox.DraggableBase._picker (artist, mouseevent) static protected
Definition at line 1507 of file offsetbox.py.
Referenced by matplotlib.collections.Collection.contains().
disconnect()
matplotlib.offsetbox.DraggableBase.disconnect (self)
Disconnect the callbacks.
Definition at line 1561 of file offsetbox.py.
References _disconnectors.
finalize_offset()
matplotlib.offsetbox.DraggableBase.finalize_offset (self)
Definition at line 1572 of file offsetbox.py.
on_motion()
matplotlib.offsetbox.DraggableBase.on_motion (self, evt)
Definition at line 1516 of file offsetbox.py.
on_pick()
matplotlib.offsetbox.DraggableBase.on_pick (self, evt)
Definition at line 1529 of file offsetbox.py.
on_release()
matplotlib.offsetbox.DraggableBase.on_release (self, event)
Definition at line 1544 of file offsetbox.py.
save_offset()
matplotlib.offsetbox.DraggableBase.save_offset (self)
Definition at line 1566 of file offsetbox.py.
update_offset()
matplotlib.offsetbox.DraggableBase.update_offset (self, dx, dy)
Definition at line 1569 of file offsetbox.py.
Member Data Documentation
_disconnectors
list matplotlib.offsetbox.DraggableBase._disconnectors protected
Initial value:
=  [
            functools.partial(
                callbacks.disconnect, callbacks._connect_picklable(name, func))
            for name, func in [
                ("pick_event", self.on_pick),
                ("button_release_event", self.on_release),
                ("motion_notify_event", self.on_motion),
            ]
        ]
Definition at line 1496 of file offsetbox.py.
Referenced by disconnect().
_picker
matplotlib.offsetbox.DraggableBase._picker protected
Definition at line 1492 of file offsetbox.py.
Referenced by matplotlib.collections.Collection.contains(), matplotlib.text.Text.get_antialiased(), and matplotlib.patches.Patch.get_verts().
_use_blit
matplotlib.offsetbox.DraggableBase._use_blit = use_blit and self.canvas.supports_blit protected
Definition at line 1494 of file offsetbox.py.
background
matplotlib.offsetbox.DraggableBase.background = evt.y - self.mouse_y
Definition at line 1522 of file offsetbox.py.
Referenced by matplotlib.widgets.Cursor.clear(), matplotlib.widgets.Cursor.onmove(), matplotlib.widgets._SelectorWidget.update(), and matplotlib.widgets._SelectorWidget.update_background().
got_artist
bool matplotlib.offsetbox.DraggableBase.got_artist = False
Definition at line 1493 of file offsetbox.py.
mouse_x
matplotlib.offsetbox.DraggableBase.mouse_x = evt.mouseevent.x
Definition at line 1532 of file offsetbox.py.
mouse_y
matplotlib.offsetbox.DraggableBase.mouse_y = evt.mouseevent.y
Definition at line 1533 of file offsetbox.py.
ref_artist
matplotlib.offsetbox.DraggableBase.ref_artist = ref_artist
Definition at line 1490 of file offsetbox.py.
Property Documentation
canvas
matplotlib.offsetbox.DraggableBase.canvas = property(lambda self: self.ref_artist.get_figure(root=True).canvas) static
Definition at line 1512 of file offsetbox.py.
Referenced by matplotlib.widgets.Button.__init__(), matplotlib.widgets.CheckButtons.__init__(), matplotlib.widgets.RadioButtons.__init__(), matplotlib.widgets.CheckButtons._clear(), matplotlib.widgets.RadioButtons._clear(), matplotlib.backend_managers.ToolManager.add_tool(), matplotlib.widgets.CheckButtons.clear(), matplotlib.widgets.Cursor.clear(), matplotlib.widgets.AxesWidget.connect_event(), matplotlib.widgets.AxesWidget.disconnect_events(), matplotlib.widgets._SelectorWidget.ignore(), matplotlib.widgets.SpanSelector.new_axes(), matplotlib.widgets.Cursor.onmove(), matplotlib.widgets.PolygonSelector.onmove(), matplotlib.widgets.CheckButtons.set_active(), matplotlib.widgets.RadioButtons.set_active(), matplotlib.backend_managers.ToolManager.set_figure(), matplotlib.widgets._SelectorWidget.update(), and matplotlib.widgets._SelectorWidget.update_background().
cids
matplotlib.offsetbox.DraggableBase.cids static
Initial value:
=  property(lambda self: [
        disconnect.args[0] for disconnect in self._disconnectors[:2]])
Definition at line 1513 of file offsetbox.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/offsetbox.py