Code Cloning Analysis: sklearn.metrics.tests.test_ranking Namespace Reference
sklearn.metrics.tests.test_ranking Namespace Reference
Functions
make_prediction (dataset=None, binary=False)
_auc (y_true, y_score)
Tests.
_average_precision (y_true, y_score)
_average_precision_slow (y_true, y_score)
_partial_roc_auc_score (y_true, y_predict, max_fpr)
test_roc_curve (drop)
test_roc_curve_end_points ()
test_roc_returns_consistency ()
test_roc_curve_multi ()
test_roc_curve_confidence ()
test_roc_curve_hard ()
test_roc_curve_one_label ()
test_roc_curve_toydata ()
test_roc_curve_drop_intermediate ()
test_roc_curve_fpr_tpr_increasing ()
test_auc ()
test_auc_errors ()
test_multiclass_ovo_roc_auc_toydata (y_true, labels)
test_multiclass_ovo_roc_auc_toydata_binary (y_true, labels)
test_multiclass_ovr_roc_auc_toydata (y_true, labels)
test_perfect_imperfect_chance_multiclass_roc_auc (multi_class, average)
test_micro_averaged_ovr_roc_auc (global_random_seed)
test_roc_auc_score_multiclass_labels_error (msg, y_true, labels, multi_class)
test_roc_auc_score_multiclass_error (msg, kwargs)
test_auc_score_non_binary_class ()
test_binary_clf_curve_multiclass_error (curve_func)
test_binary_clf_curve_implicit_pos_label (curve_func)
test_binary_clf_curve_implicit_bytes_pos_label (curve_func, labels_type)
test_binary_clf_curve_zero_sample_weight (curve_func)
test_precision_recall_curve (drop)
_test_precision_recall_curve (y_true, y_score, drop)
test_precision_recall_curve_toydata (drop)
test_precision_recall_curve_drop_intermediate ()
test_average_precision_constant_values ()
test_average_precision_score_binary_pos_label_errors ()
test_average_precision_score_multilabel_pos_label_errors ()
test_average_precision_score_multiclass_pos_label_errors ()
test_score_scale_invariance ()
test_det_curve_toydata (y_true, y_score, expected_fpr, expected_fnr)
test_det_curve_drop_intermediate (y_true, y_score, expected_fpr, expected_fnr, drop_intermediate)
test_det_curve_tie_handling (y_true, y_score, expected_fpr, expected_fnr)
test_det_curve_sanity_check ()
test_det_curve_constant_scores (y_score)
test_det_curve_perfect_scores (y_true)
test_det_curve_bad_input (y_true, y_pred, err_msg)
test_det_curve_pos_label ()
check_lrap_toy (lrap_score)
check_zero_or_all_relevant_labels (lrap_score)
check_lrap_error_raised (lrap_score)
check_lrap_only_ties (lrap_score)
check_lrap_without_tie_and_increasing_score (lrap_score)
_my_lrap (y_true, y_score)
check_alternative_lrap_implementation (lrap_score, n_classes=5, n_samples=20, random_state=0)
test_label_ranking_avp (check, func)
test_lrap_error_raised ()
test_alternative_lrap_implementation (n_samples, n_classes, random_state)
test_lrap_sample_weighting_zero_labels ()
test_coverage_error ()
test_coverage_tie_handling ()
test_coverage_1d_error_message (y_true, y_score)
test_label_ranking_loss ()
test_label_ranking_loss_sparse (csr_container)
test_ranking_appropriate_input_shape ()
test_ranking_loss_ties_handling ()
test_dcg_score ()
_test_dcg_score_for (y_true, y_score)
test_dcg_ties ()
test_ndcg_ignore_ties_with_k ()
test_ndcg_negative_ndarray_error ()
test_ndcg_invariant ()
test_ndcg_toy_examples (ignore_ties)
test_ndcg_error_single_document ()
test_ndcg_score ()
_test_ndcg_score_for (y_true, y_score)
test_partial_roc_auc_score ()
test_top_k_accuracy_score (y_true, k, true_score)
test_top_k_accuracy_score_binary (y_score, k, true_score)
test_top_k_accuracy_score_multiclass_with_labels (y_true, true_score, labels, labels_as_ndarray)
test_top_k_accuracy_score_increasing ()
test_top_k_accuracy_score_ties (y_true, k, true_score)
test_top_k_accuracy_score_warning (y_true, k)
test_top_k_accuracy_score_error (y_true, y_score, labels, msg)
test_label_ranking_avg_precision_score_should_allow_csr_matrix_for_y_true_input (csr_container)
test_ranking_metric_pos_label_types (metric, classes)
test_roc_curve_with_probablity_estimates (global_random_seed)
Variables
list CURVE_FUNCS
Utilities for testing.
Function Documentation
_auc()
sklearn.metrics.tests.test_ranking._auc (y_true, y_score) protected
Tests.
Alternative implementation to check for correctness of
`roc_auc_score`.
Definition at line 104 of file test_ranking.py.
Referenced by _partial_roc_auc_score().
_average_precision()
sklearn.metrics.tests.test_ranking._average_precision (y_true, y_score) protected
Alternative implementation to check for correctness of
`average_precision_score`.
Note that this implementation fails on some edge cases.
For example, for constant predictions e.g. [0.5, 0.5, 0.5],
y_true = [1, 0, 0] returns an average precision of 0.33...
but y_true = [0, 0, 1] returns 1.0.
Definition at line 119 of file test_ranking.py.
Referenced by _partial_roc_auc_score().
_average_precision_slow()
sklearn.metrics.tests.test_ranking._average_precision_slow (y_true, y_score) protected
A second alternative implementation of average precision that closely
follows the Wikipedia article's definition (see References). This should
give identical results as `average_precision_score` for all inputs.
References
----------
.. [1] `Wikipedia entry for the Average precision
   <https://en.wikipedia.org/wiki/Average_precision>`_
Definition at line 149 of file test_ranking.py.
Referenced by _partial_roc_auc_score().
_my_lrap()
sklearn.metrics.tests.test_ranking._my_lrap (y_true, y_score) protected
Simple implementation of label ranking average precision
Definition at line 1545 of file test_ranking.py.
References _my_lrap().
Referenced by _my_lrap().
_partial_roc_auc_score()
sklearn.metrics.tests.test_ranking._partial_roc_auc_score (y_true, y_predict, max_fpr) protected
Alternative implementation to check for correctness of `roc_auc_score`
with `max_fpr` set.
Definition at line 168 of file test_ranking.py.
References _auc(), _average_precision(), _average_precision_slow(), and make_prediction().
Referenced by test_ndcg_error_single_document().
_test_dcg_score_for()
sklearn.metrics.tests.test_ranking._test_dcg_score_for (y_true, y_score) protected
Definition at line 1838 of file test_ranking.py.
_test_ndcg_score_for()
sklearn.metrics.tests.test_ranking._test_ndcg_score_for (y_true, y_score) protected
Definition at line 1954 of file test_ranking.py.
_test_precision_recall_curve()
sklearn.metrics.tests.test_ranking._test_precision_recall_curve (y_true, y_score, drop) protected
Definition at line 933 of file test_ranking.py.
check_alternative_lrap_implementation()
sklearn.metrics.tests.test_ranking.check_alternative_lrap_implementation (lrap_score, n_classes = 5, n_samples = 20, random_state = 0)
Definition at line 1583 of file test_ranking.py.
check_lrap_error_raised()
sklearn.metrics.tests.test_ranking.check_lrap_error_raised (lrap_score)
Definition at line 1477 of file test_ranking.py.
check_lrap_only_ties()
sklearn.metrics.tests.test_ranking.check_lrap_only_ties (lrap_score)
Definition at line 1503 of file test_ranking.py.
check_lrap_toy()
sklearn.metrics.tests.test_ranking.check_lrap_toy (lrap_score)
Definition at line 1395 of file test_ranking.py.
check_lrap_without_tie_and_increasing_score()
sklearn.metrics.tests.test_ranking.check_lrap_without_tie_and_increasing_score (lrap_score)
Definition at line 1518 of file test_ranking.py.
check_zero_or_all_relevant_labels()
sklearn.metrics.tests.test_ranking.check_zero_or_all_relevant_labels (lrap_score)
Definition at line 1454 of file test_ranking.py.
make_prediction()
sklearn.metrics.tests.test_ranking.make_prediction (dataset = None, binary = False)
Make some classification predictions on a toy dataset using a SVC
If binary is True restrict to a binary classification problem instead of a
multiclass classification problem
Definition at line 56 of file test_ranking.py.
Referenced by _partial_roc_auc_score(), test_ndcg_error_single_document(), and test_precision_recall_curve_drop_intermediate().
test_alternative_lrap_implementation()
sklearn.metrics.tests.test_ranking.test_alternative_lrap_implementation (n_samples, n_classes, random_state)
Definition at line 1636 of file test_ranking.py.
test_auc()
sklearn.metrics.tests.test_ranking.test_auc ()
Definition at line 456 of file test_ranking.py.
test_auc_errors()
sklearn.metrics.tests.test_ranking.test_auc_errors ()
Definition at line 475 of file test_ranking.py.
test_auc_score_non_binary_class()
sklearn.metrics.tests.test_ranking.test_auc_score_non_binary_class ()
Definition at line 820 of file test_ranking.py.
test_average_precision_constant_values()
sklearn.metrics.tests.test_ranking.test_average_precision_constant_values ()
Definition at line 1153 of file test_ranking.py.
test_average_precision_score_binary_pos_label_errors()
sklearn.metrics.tests.test_ranking.test_average_precision_score_binary_pos_label_errors ()
Definition at line 1167 of file test_ranking.py.
test_average_precision_score_multiclass_pos_label_errors()
sklearn.metrics.tests.test_ranking.test_average_precision_score_multiclass_pos_label_errors ()
Definition at line 1189 of file test_ranking.py.
test_average_precision_score_multilabel_pos_label_errors()
sklearn.metrics.tests.test_ranking.test_average_precision_score_multilabel_pos_label_errors ()
Definition at line 1176 of file test_ranking.py.
test_binary_clf_curve_implicit_bytes_pos_label()
sklearn.metrics.tests.test_ranking.test_binary_clf_curve_implicit_bytes_pos_label (curve_func, labels_type)
Definition at line 879 of file test_ranking.py.
test_binary_clf_curve_implicit_pos_label()
sklearn.metrics.tests.test_ranking.test_binary_clf_curve_implicit_pos_label (curve_func)
Definition at line 852 of file test_ranking.py.
test_binary_clf_curve_multiclass_error()
sklearn.metrics.tests.test_ranking.test_binary_clf_curve_multiclass_error (curve_func)
Definition at line 842 of file test_ranking.py.
test_binary_clf_curve_zero_sample_weight()
sklearn.metrics.tests.test_ranking.test_binary_clf_curve_zero_sample_weight (curve_func)
Definition at line 889 of file test_ranking.py.
test_coverage_1d_error_message()
sklearn.metrics.tests.test_ranking.test_coverage_1d_error_message (y_true, y_score)
Definition at line 1742 of file test_ranking.py.
test_coverage_error()
sklearn.metrics.tests.test_ranking.test_coverage_error ()
Definition at line 1663 of file test_ranking.py.
test_coverage_tie_handling()
sklearn.metrics.tests.test_ranking.test_coverage_tie_handling ()
Definition at line 1718 of file test_ranking.py.
test_dcg_score()
sklearn.metrics.tests.test_ranking.test_dcg_score ()
Definition at line 1830 of file test_ranking.py.
test_dcg_ties()
sklearn.metrics.tests.test_ranking.test_dcg_ties ()
Definition at line 1849 of file test_ranking.py.
test_det_curve_bad_input()
sklearn.metrics.tests.test_ranking.test_det_curve_bad_input (y_true, y_pred, err_msg)
Definition at line 1363 of file test_ranking.py.
test_det_curve_constant_scores()
sklearn.metrics.tests.test_ranking.test_det_curve_constant_scores (y_score)
Definition at line 1322 of file test_ranking.py.
test_det_curve_drop_intermediate()
sklearn.metrics.tests.test_ranking.test_det_curve_drop_intermediate (y_true, y_score, expected_fpr, expected_fnr, drop_intermediate)
Definition at line 1283 of file test_ranking.py.
test_det_curve_perfect_scores()
sklearn.metrics.tests.test_ranking.test_det_curve_perfect_scores (y_true)
Definition at line 1342 of file test_ranking.py.
test_det_curve_pos_label()
sklearn.metrics.tests.test_ranking.test_det_curve_pos_label ()
Definition at line 1369 of file test_ranking.py.
test_det_curve_sanity_check()
sklearn.metrics.tests.test_ranking.test_det_curve_sanity_check ()
Definition at line 1313 of file test_ranking.py.
test_det_curve_tie_handling()
sklearn.metrics.tests.test_ranking.test_det_curve_tie_handling (y_true, y_score, expected_fpr, expected_fnr)
Definition at line 1306 of file test_ranking.py.
test_det_curve_toydata()
sklearn.metrics.tests.test_ranking.test_det_curve_toydata (y_true, y_score, expected_fpr, expected_fnr)
Definition at line 1260 of file test_ranking.py.
test_label_ranking_avg_precision_score_should_allow_csr_matrix_for_y_true_input()
sklearn.metrics.tests.test_ranking.test_label_ranking_avg_precision_score_should_allow_csr_matrix_for_y_true_input (csr_container)
Definition at line 2222 of file test_ranking.py.
test_label_ranking_avp()
sklearn.metrics.tests.test_ranking.test_label_ranking_avp (check, func)
Definition at line 1625 of file test_ranking.py.
test_label_ranking_loss()
sklearn.metrics.tests.test_ranking.test_label_ranking_loss ()
Definition at line 1749 of file test_ranking.py.
test_label_ranking_loss_sparse()
sklearn.metrics.tests.test_ranking.test_label_ranking_loss_sparse (csr_container)
Definition at line 1793 of file test_ranking.py.
test_lrap_error_raised()
sklearn.metrics.tests.test_ranking.test_lrap_error_raised ()
Definition at line 1629 of file test_ranking.py.
test_lrap_sample_weighting_zero_labels()
sklearn.metrics.tests.test_ranking.test_lrap_sample_weighting_zero_labels ()
Definition at line 1642 of file test_ranking.py.
test_micro_averaged_ovr_roc_auc()
sklearn.metrics.tests.test_ranking.test_micro_averaged_ovr_roc_auc (global_random_seed)
Definition at line 672 of file test_ranking.py.
test_multiclass_ovo_roc_auc_toydata()
sklearn.metrics.tests.test_ranking.test_multiclass_ovo_roc_auc_toydata (y_true, labels)
Definition at line 501 of file test_ranking.py.
test_multiclass_ovo_roc_auc_toydata_binary()
sklearn.metrics.tests.test_ranking.test_multiclass_ovo_roc_auc_toydata_binary (y_true, labels)
Definition at line 558 of file test_ranking.py.
test_multiclass_ovr_roc_auc_toydata()
sklearn.metrics.tests.test_ranking.test_multiclass_ovr_roc_auc_toydata (y_true, labels)
Definition at line 596 of file test_ranking.py.
test_ndcg_error_single_document()
sklearn.metrics.tests.test_ranking.test_ndcg_error_single_document ()
Check that we raise an informative error message when trying to
compute NDCG with a single document.
Definition at line 1935 of file test_ranking.py.
References _partial_roc_auc_score(), and make_prediction().
test_ndcg_ignore_ties_with_k()
sklearn.metrics.tests.test_ranking.test_ndcg_ignore_ties_with_k ()
Definition at line 1869 of file test_ranking.py.
test_ndcg_invariant()
sklearn.metrics.tests.test_ranking.test_ndcg_invariant ()
Definition at line 1885 of file test_ranking.py.
test_ndcg_negative_ndarray_error()
sklearn.metrics.tests.test_ranking.test_ndcg_negative_ndarray_error ()
Check `ndcg_score` exception when `y_true` contains negative values.
Definition at line 1876 of file test_ranking.py.
test_ndcg_score()
sklearn.metrics.tests.test_ranking.test_ndcg_score ()
Definition at line 1946 of file test_ranking.py.
test_ndcg_toy_examples()
sklearn.metrics.tests.test_ranking.test_ndcg_toy_examples (ignore_ties)
Definition at line 1897 of file test_ranking.py.
test_partial_roc_auc_score()
sklearn.metrics.tests.test_ranking.test_partial_roc_auc_score ()
Definition at line 1970 of file test_ranking.py.
test_perfect_imperfect_chance_multiclass_roc_auc()
sklearn.metrics.tests.test_ranking.test_perfect_imperfect_chance_multiclass_roc_auc (multi_class, average)
Definition at line 638 of file test_ranking.py.
test_precision_recall_curve()
sklearn.metrics.tests.test_ranking.test_precision_recall_curve (drop)
Definition at line 902 of file test_ranking.py.
test_precision_recall_curve_drop_intermediate()
sklearn.metrics.tests.test_ranking.test_precision_recall_curve_drop_intermediate ()
Check the behaviour of the `drop_intermediate` parameter.
Definition at line 1119 of file test_ranking.py.
References make_prediction().
test_precision_recall_curve_toydata()
sklearn.metrics.tests.test_ranking.test_precision_recall_curve_toydata (drop)
Definition at line 956 of file test_ranking.py.
test_ranking_appropriate_input_shape()
sklearn.metrics.tests.test_ranking.test_ranking_appropriate_input_shape ()
Definition at line 1802 of file test_ranking.py.
test_ranking_loss_ties_handling()
sklearn.metrics.tests.test_ranking.test_ranking_loss_ties_handling ()
Definition at line 1818 of file test_ranking.py.
test_ranking_metric_pos_label_types()
sklearn.metrics.tests.test_ranking.test_ranking_metric_pos_label_types (metric, classes)
Check that the metric works with different types of `pos_label`.
We can expect `pos_label` to be a bool, an integer, a float, a string.
No error should be raised for those types.
Definition at line 2239 of file test_ranking.py.
test_roc_auc_score_multiclass_error()
sklearn.metrics.tests.test_ranking.test_roc_auc_score_multiclass_error (msg, kwargs)
Definition at line 808 of file test_ranking.py.
test_roc_auc_score_multiclass_labels_error()
sklearn.metrics.tests.test_ranking.test_roc_auc_score_multiclass_labels_error (msg, y_true, labels, multi_class)
Definition at line 764 of file test_ranking.py.
test_roc_curve()
sklearn.metrics.tests.test_ranking.test_roc_curve (drop)
Definition at line 197 of file test_ranking.py.
test_roc_curve_confidence()
sklearn.metrics.tests.test_ranking.test_roc_curve_confidence ()
Definition at line 250 of file test_ranking.py.
test_roc_curve_drop_intermediate()
sklearn.metrics.tests.test_ranking.test_roc_curve_drop_intermediate ()
Definition at line 430 of file test_ranking.py.
test_roc_curve_end_points()
sklearn.metrics.tests.test_ranking.test_roc_curve_end_points ()
Definition at line 210 of file test_ranking.py.
test_roc_curve_fpr_tpr_increasing()
sklearn.metrics.tests.test_ranking.test_roc_curve_fpr_tpr_increasing ()
Definition at line 444 of file test_ranking.py.
test_roc_curve_hard()
sklearn.metrics.tests.test_ranking.test_roc_curve_hard ()
Definition at line 261 of file test_ranking.py.
test_roc_curve_multi()
sklearn.metrics.tests.test_ranking.test_roc_curve_multi ()
Definition at line 242 of file test_ranking.py.
test_roc_curve_one_label()
sklearn.metrics.tests.test_ranking.test_roc_curve_one_label ()
Definition at line 289 of file test_ranking.py.
test_roc_curve_toydata()
sklearn.metrics.tests.test_ranking.test_roc_curve_toydata ()
Definition at line 316 of file test_ranking.py.
test_roc_curve_with_probablity_estimates()
sklearn.metrics.tests.test_ranking.test_roc_curve_with_probablity_estimates (global_random_seed)
Check that thresholds do not exceed 1.0 when `y_score` is a probability
estimate.
Non-regression test for:
https://github.com/scikit-learn/scikit-learn/issues/26193
Definition at line 2259 of file test_ranking.py.
test_roc_returns_consistency()
sklearn.metrics.tests.test_ranking.test_roc_returns_consistency ()
Definition at line 223 of file test_ranking.py.
test_score_scale_invariance()
sklearn.metrics.tests.test_ranking.test_score_scale_invariance ()
Definition at line 1210 of file test_ranking.py.
test_top_k_accuracy_score()
sklearn.metrics.tests.test_ranking.test_top_k_accuracy_score (y_true, k, true_score)
Definition at line 2004 of file test_ranking.py.
test_top_k_accuracy_score_binary()
sklearn.metrics.tests.test_ranking.test_top_k_accuracy_score_binary (y_score, k, true_score)
Definition at line 2028 of file test_ranking.py.
test_top_k_accuracy_score_error()
sklearn.metrics.tests.test_ranking.test_top_k_accuracy_score_error (y_true, y_score, labels, msg)
Definition at line 2216 of file test_ranking.py.
test_top_k_accuracy_score_increasing()
sklearn.metrics.tests.test_ranking.test_top_k_accuracy_score_increasing ()
Definition at line 2069 of file test_ranking.py.
test_top_k_accuracy_score_multiclass_with_labels()
sklearn.metrics.tests.test_ranking.test_top_k_accuracy_score_multiclass_with_labels (y_true, true_score, labels, labels_as_ndarray)
Test when labels and y_score are multiclass.
Definition at line 2050 of file test_ranking.py.
test_top_k_accuracy_score_ties()
sklearn.metrics.tests.test_ranking.test_top_k_accuracy_score_ties (y_true, k, true_score)
Definition at line 2096 of file test_ranking.py.
test_top_k_accuracy_score_warning()
sklearn.metrics.tests.test_ranking.test_top_k_accuracy_score_warning (y_true, k)
Definition at line 2116 of file test_ranking.py.
Variable Documentation
CURVE_FUNCS
list sklearn.metrics.tests.test_ranking.CURVE_FUNCS
Initial value:
=  [
    det_curve,
    precision_recall_curve,
    roc_curve,
]
Utilities for testing.
Definition at line 49 of file test_ranking.py.