Code Cloning Analysis: sklearn.linear_model._base Namespace Reference
sklearn.linear_model._base Namespace Reference
Classes
class LinearClassifierMixin
class LinearModel
class LinearRegression
class SparseCoefMixin
Functions
make_dataset (X, y, sample_weight, random_state=None)
_preprocess_data (X, y, *, fit_intercept, copy=True, copy_y=True, sample_weight=None, check_input=True)
_rescale_data (X, y, sample_weight, inplace=False)
_check_precomputed_gram_matrix (X, precompute, X_offset, X_scale, rtol=None, atol=1e-5)
_pre_fit (X, y, Xy, precompute, fit_intercept, copy, check_input=True, sample_weight=None)
Variables
float SPARSE_INTERCEPT_DECAY = 0.01
Detailed Description
Generalized Linear Models.
Function Documentation
_check_precomputed_gram_matrix()
sklearn.linear_model._base._check_precomputed_gram_matrix (X, precompute, X_offset, X_scale, rtol = None, atol = 1e-5) protected
Computes a single element of the gram matrix and compares it to
the corresponding element of the user supplied gram matrix.
If the values do not match a ValueError will be thrown.
Parameters
----------
X : ndarray of shape (n_samples, n_features)
    Data array.
precompute : array-like of shape (n_features, n_features)
    User-supplied gram matrix.
X_offset : ndarray of shape (n_features,)
    Array of feature means used to center design matrix.
X_scale : ndarray of shape (n_features,)
    Array of feature scale factors used to normalize design matrix.
rtol : float, default=None
    Relative tolerance; see numpy.allclose
    If None, it is set to 1e-4 for arrays of dtype numpy.float32 and 1e-7
    otherwise.
atol : float, default=1e-5
    absolute tolerance; see :func`numpy.allclose`. Note that the default
    here is more tolerant than the default for
    :func:`numpy.testing.assert_allclose`, where `atol=0`.
Raises
------
ValueError
    Raised when the provided Gram matrix is not consistent.
Definition at line 715 of file _base.py.
Referenced by _pre_fit().
_pre_fit()
sklearn.linear_model._base._pre_fit (X, y, Xy, precompute, fit_intercept, copy, check_input = True, sample_weight = None) protected
Function used at beginning of fit in linear models with L1 or L0 penalty.
This function applies _preprocess_data and additionally computes the gram matrix
`precompute` as needed as well as `Xy`.
Definition at line 779 of file _base.py.
References _check_precomputed_gram_matrix(), _preprocess_data(), and _rescale_data().
_preprocess_data()
sklearn.linear_model._base._preprocess_data (X, y, * , fit_intercept, copy = True, copy_y = True, sample_weight = None, check_input = True) protected
Common data preprocessing for fitting linear models.
This helper is in charge of the following steps:
- Ensure that `sample_weight` is an array or `None`.
- If `check_input=True`, perform standard input validation of `X`, `y`.
- Perform copies if requested to avoid side-effects in case of inplace
  modifications of the input.
Then, if `fit_intercept=True` this preprocessing centers both `X` and `y` as
follows:
    - if `X` is dense, center the data and
    store the mean vector in `X_offset`.
    - if `X` is sparse, store the mean in `X_offset`
    without centering `X`. The centering is expected to be handled by the
    linear solver where appropriate.
    - in either case, always center `y` and store the mean in `y_offset`.
    - both `X_offset` and `y_offset` are always weighted by `sample_weight`
      if not set to `None`.
If `fit_intercept=False`, no centering is performed and `X_offset`, `y_offset`
are set to zero.
Returns
-------
X_out : {ndarray, sparse matrix} of shape (n_samples, n_features)
    If copy=True a copy of the input X is triggered, otherwise operations are
    inplace.
    If input X is dense, then X_out is centered.
y_out : {ndarray, sparse matrix} of shape (n_samples,) or (n_samples, n_targets)
    Centered version of y. Possibly performed inplace on input y depending
    on the copy_y parameter.
X_offset : ndarray of shape (n_features,)
    The mean per column of input X.
y_offset : float or ndarray of shape (n_features,)
X_scale : ndarray of shape (n_features,)
    Always an array of ones. TODO: refactor the code base to make it
    possible to remove this unused variable.
Definition at line 108 of file _base.py.
Referenced by _pre_fit(), and sklearn.linear_model._base.LinearRegression.fit().
_rescale_data()
sklearn.linear_model._base._rescale_data (X, y, sample_weight, inplace = False) protected
Rescale data sample-wise by square root of sample_weight.
For many linear models, this enables easy support for sample_weight because
    (y - X w)' S (y - X w)
with S = diag(sample_weight) becomes
    ||y_rescaled - X_rescaled w||_2^2
when setting
    y_rescaled = sqrt(S) y
    X_rescaled = sqrt(S) X
Returns
-------
X_rescaled : {array-like, sparse matrix}
y_rescaled : {array-like, sparse matrix}
Definition at line 210 of file _base.py.
Referenced by _pre_fit(), and sklearn.linear_model._base.LinearRegression.fit().
make_dataset()
sklearn.linear_model._base.make_dataset (X, y, sample_weight, random_state = None)
Create ``Dataset`` abstraction for sparse and dense inputs.
This also returns the ``intercept_decay`` which is different
for sparse datasets.
Parameters
----------
X : array-like, shape (n_samples, n_features)
    Training data
y : array-like, shape (n_samples,)
    Target values.
sample_weight : numpy array of shape (n_samples,)
    The weight of each sample
random_state : int, RandomState instance or None (default)
    Determines random number generation for dataset random sampling. It is not
    used for dataset shuffling.
    Pass an int for reproducible output across multiple function calls.
    See :term:`Glossary <random_state>`.
Returns
-------
dataset
    The ``Dataset`` abstraction
intercept_decay
    The intercept decay
Definition at line 55 of file _base.py.
Variable Documentation
SPARSE_INTERCEPT_DECAY
float sklearn.linear_model._base.SPARSE_INTERCEPT_DECAY = 0.01
Definition at line 50 of file _base.py.