Code Cloning Analysis: matplotlib._docstring.Substitution Class Reference
matplotlib._docstring.Substitution Class Reference
Public Member Functions
__init__ (self, *args, **kwargs)
__call__ (self, func)
Public Attributes
params = args or kwargs
Detailed Description
A decorator that performs %-substitution on an object's docstring.
This decorator should be robust even if ``obj.__doc__`` is None (for
example, if -OO was passed to the interpreter).
Usage: construct a docstring.Substitution with a sequence or dictionary
suitable for performing substitution; then decorate a suitable function
with the constructed object, e.g.::
    sub_author_name = Substitution(author='Jason')
    @sub_author_name
    def some_function(x):
        "%(author)s wrote this function"
    # note that some_function.__doc__ is now "Jason wrote this function"
One can also use positional arguments::
    sub_first_last_names = Substitution('Edgar Allen', 'Poe')
    @sub_first_last_names
    def some_function(x):
        "%s %s wrote the Raven"
Definition at line 34 of file _docstring.py.
Constructor & Destructor Documentation
__init__()
matplotlib._docstring.Substitution.__init__ (self, * args, ** kwargs)
Definition at line 61 of file _docstring.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__call__()
matplotlib._docstring.Substitution.__call__ (self, func)
Definition at line 66 of file _docstring.py.
Referenced by scipy.interpolate._fitpack2.BivariateSpline.ev(), scipy.interpolate._fitpack2.SphereBivariateSpline.ev(), matplotlib.ticker.Formatter.format_data(), and matplotlib.ticker.LogFormatter.format_data().
Member Data Documentation
params
matplotlib._docstring.Substitution.params = args or kwargs
Definition at line 64 of file _docstring.py.
Referenced by numpy.core.getlimits.MachArLike._float_to_str(), scipy.stats._fit.FitResult.nllf(), scipy.stats._fit.FitResult.plot(), pip._vendor.requests.models.Request.prepare(), pip._vendor.requests.sessions.Session.prepare_request(), matplotlib._docstring._ArtistPropertiesSubstitution.register(), and pandas.util._decorators.Substitution.update().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/matplotlib/_docstring.py