Code Cloning Analysis: fontTools.misc.configTools.Options Class Reference
fontTools.misc.configTools.Options Class Reference
Public Member Functions
None __init__ (self, "Options" other=None)
Option register (self, str name, str help, Any default, Callable[[str], Any] parse, Optional[Callable[[Any], bool]] validate=None)
Option register_option (self, Option option)
bool is_registered (self, Option option)
Option __getitem__ (self, str key)
Iterator[str] __iter__ (self)
int __len__ (self)
str __repr__ (self)
Static Private Attributes
Dict __options [str, Option]
Detailed Description
Registry of available options for a given config system.
Define new options using the :meth:`register()` method.
Access existing options using the Mapping interface.
Definition at line 120 of file configTools.py.
Constructor & Destructor Documentation
__init__()
None fontTools.misc.configTools.Options.__init__ (self, "Options" other = None)
Definition at line 130 of file configTools.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__getitem__()
Option fontTools.misc.configTools.Options.__getitem__ (self, str key)
Definition at line 159 of file configTools.py.
__iter__()
Iterator[str] fontTools.misc.configTools.Options.__iter__ (self)
Definition at line 162 of file configTools.py.
__len__()
int fontTools.misc.configTools.Options.__len__ (self)
Definition at line 165 of file configTools.py.
__repr__()
str fontTools.misc.configTools.Options.__repr__ (self)
Definition at line 168 of file configTools.py.
is_registered()
bool fontTools.misc.configTools.Options.is_registered (self, Option option)
Return True if the same option object is already registered.
Definition at line 155 of file configTools.py.
References __options.
register()
Option fontTools.misc.configTools.Options.register (self, str name, str help, Any default, Callable[[str], Any] parse, Optional[Callable[[Any], bool]] validate = None)
Create and register a new option.
Definition at line 136 of file configTools.py.
References register_option().
register_option()
Option fontTools.misc.configTools.Options.register_option (self, Option option)
Register a new option.
Definition at line 147 of file configTools.py.
References __options.
Referenced by register().
Member Data Documentation
__options
Dict fontTools.misc.configTools.Options.__options [str, Option] static private
Definition at line 128 of file configTools.py.
Referenced by is_registered(), and register_option().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/misc/configTools.py