Code Cloning Analysis: sklearn.tests.test_public_functions Namespace Reference
sklearn.tests.test_public_functions Namespace Reference
Functions
_get_func_info (func_module)
_check_function_param_validation (func, func_name, func_params, required_params, parameter_constraints)
test_function_param_validation (func_module)
test_class_wrapper_param_validation (func_module, class_module)
Variables
list PARAM_VALIDATION_FUNCTION_LIST
list PARAM_VALIDATION_CLASS_WRAPPER_LIST
Function Documentation
_check_function_param_validation()
sklearn.tests.test_public_functions._check_function_param_validation (func, func_name, func_params, required_params, parameter_constraints) protected
Check that an informative error is raised when the value of a parameter does not
have an appropriate type or value.
Definition at line 39 of file test_public_functions.py.
Referenced by test_class_wrapper_param_validation(), and test_function_param_validation().
_get_func_info()
sklearn.tests.test_public_functions._get_func_info (func_module) protected
Definition at line 16 of file test_public_functions.py.
test_class_wrapper_param_validation()
sklearn.tests.test_public_functions.test_class_wrapper_param_validation (func_module, class_module)
Check param validation for public functions that are wrappers around
estimators.
Definition at line 381 of file test_public_functions.py.
References _check_function_param_validation().
test_function_param_validation()
sklearn.tests.test_public_functions.test_function_param_validation (func_module)
Check param validation for public functions that are not wrappers around
estimators.
Definition at line 338 of file test_public_functions.py.
References _check_function_param_validation().
Variable Documentation
PARAM_VALIDATION_CLASS_WRAPPER_LIST
list sklearn.tests.test_public_functions.PARAM_VALIDATION_CLASS_WRAPPER_LIST
Initial value:
=  [
    ("sklearn.cluster.affinity_propagation", "sklearn.cluster.AffinityPropagation"),
    ("sklearn.cluster.dbscan", "sklearn.cluster.DBSCAN"),
    ("sklearn.cluster.k_means", "sklearn.cluster.KMeans"),
    ("sklearn.cluster.mean_shift", "sklearn.cluster.MeanShift"),
    ("sklearn.cluster.spectral_clustering", "sklearn.cluster.SpectralClustering"),
    ("sklearn.covariance.graphical_lasso", "sklearn.covariance.GraphicalLasso"),
    ("sklearn.covariance.ledoit_wolf", "sklearn.covariance.LedoitWolf"),
    ("sklearn.covariance.oas", "sklearn.covariance.OAS"),
    ("sklearn.decomposition.dict_learning", "sklearn.decomposition.DictionaryLearning"),
    (
        "sklearn.decomposition.dict_learning_online",
        "sklearn.decomposition.MiniBatchDictionaryLearning",
    ),
    ("sklearn.decomposition.fastica", "sklearn.decomposition.FastICA"),
    ("sklearn.decomposition.non_negative_factorization", "sklearn.decomposition.NMF"),
    ("sklearn.preprocessing.maxabs_scale", "sklearn.preprocessing.MaxAbsScaler"),
    ("sklearn.preprocessing.minmax_scale", "sklearn.preprocessing.MinMaxScaler"),
    ("sklearn.preprocessing.power_transform", "sklearn.preprocessing.PowerTransformer"),
    (
        "sklearn.preprocessing.quantile_transform",
        "sklearn.preprocessing.QuantileTransformer",
    ),
    ("sklearn.preprocessing.robust_scale", "sklearn.preprocessing.RobustScaler"),
]
Definition at line 351 of file test_public_functions.py.
PARAM_VALIDATION_FUNCTION_LIST
list sklearn.tests.test_public_functions.PARAM_VALIDATION_FUNCTION_LIST
Definition at line 132 of file test_public_functions.py.