Code Cloning Analysis: pytz._FixedOffset Class Reference
pytz._FixedOffset Class Reference
Public Member Functions
__init__ (self, minutes)
utcoffset (self, dt)
__reduce__ (self)
dst (self, dt)
tzname (self, dt)
__repr__ (self)
localize (self, dt, is_dst=False)
normalize (self, dt, is_dst=False)
Static Public Attributes
zone = None
Protected Attributes
_minutes = minutes
_offset = datetime.timedelta(minutes=minutes)
Detailed Description
Definition at line 398 of file __init__.py.
Constructor & Destructor Documentation
__init__()
pytz._FixedOffset.__init__ (self, minutes)
Definition at line 402 of file __init__.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
__reduce__()
pytz._FixedOffset.__reduce__ (self)
Definition at line 411 of file __init__.py.
__repr__()
pytz._FixedOffset.__repr__ (self)
Definition at line 420 of file __init__.py.
dst()
pytz._FixedOffset.dst (self, dt)
Definition at line 414 of file __init__.py.
localize()
pytz._FixedOffset.localize (self, dt, is_dst = False)
Convert naive time to local time
Definition at line 423 of file __init__.py.
Referenced by pytz.tzinfo.DstTzInfo.dst(), pytz.tzinfo.DstTzInfo.localize(), pytz.tzinfo.DstTzInfo.tzname(), and pytz.tzinfo.DstTzInfo.utcoffset().
normalize()
pytz._FixedOffset.normalize (self, dt, is_dst = False)
Correct the timezone information on the given datetime
Definition at line 429 of file __init__.py.
tzname()
pytz._FixedOffset.tzname (self, dt)
Definition at line 417 of file __init__.py.
utcoffset()
pytz._FixedOffset.utcoffset (self, dt)
Definition at line 408 of file __init__.py.
Member Data Documentation
_minutes
pytz._FixedOffset._minutes = minutes protected
Definition at line 405 of file __init__.py.
_offset
pytz._FixedOffset._offset = datetime.timedelta(minutes=minutes) protected
Definition at line 406 of file __init__.py.
Referenced by matplotlib.table.Table._offset().
zone
pytz._FixedOffset.zone = None static
Definition at line 400 of file __init__.py.
Referenced by pytz.tzinfo.StaticTzInfo.normalize(), and pytz.tzinfo.DstTzInfo.tzname().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pytz/__init__.py