Code Cloning Analysis: numpy.core._internal._Stream Class Reference
numpy.core._internal._Stream Class Reference
Public Member Functions
__init__ (self, s)
advance (self, n)
consume (self, c)
consume_until (self, c)
next (self)
__bool__ (self)
Public Attributes
s = s
str byteorder = '@'
Detailed Description
Definition at line 616 of file _internal.py.
Constructor & Destructor Documentation
__init__()
numpy.core._internal._Stream.__init__ (self, s)
Definition at line 617 of file _internal.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
__bool__()
numpy.core._internal._Stream.__bool__ (self)
Definition at line 648 of file _internal.py.
advance()
numpy.core._internal._Stream.advance (self, n)
Definition at line 621 of file _internal.py.
Referenced by pip._vendor.rich.progress.Progress.track().
consume()
numpy.core._internal._Stream.consume (self, c)
Definition at line 626 of file _internal.py.
consume_until()
numpy.core._internal._Stream.consume_until (self, c)
Definition at line 632 of file _internal.py.
next()
numpy.core._internal._Stream.next (self)
Definition at line 645 of file _internal.py.
Member Data Documentation
byteorder
str numpy.core._internal._Stream.byteorder = '@'
Definition at line 619 of file _internal.py.
s
numpy.core._internal._Stream.s = s
Definition at line 618 of file _internal.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/numpy/core/_internal.py