Code Cloning Analysis: pip._vendor.chardet.codingstatemachine.CodingStateMachine Class Reference
pip._vendor.chardet.codingstatemachine.CodingStateMachine Class Reference
Public Member Functions
None __init__ (self, CodingStateMachineDict sm)
None reset (self)
int next_state (self, int c)
int get_current_charlen (self)
str get_coding_state_machine (self)
str language (self)
Public Attributes
bool active = True
logger = logging.getLogger(__name__)
Protected Attributes
_model = sm
int _curr_byte_pos = 0
int _curr_char_len = 0
_curr_state = MachineState.START
Detailed Description
A state machine to verify a byte sequence for a particular encoding. For
each byte the detector receives, it will feed that byte to every active
state machine available, one byte at a time. The state machine changes its
state based on its previous state and the byte it receives. There are 3
states in a state machine that are of interest to an auto-detector:
START state: This is the state to start with, or a legal byte sequence
             (i.e. a valid code point) for character has been identified.
ME state:  This indicates that the state machine identified a byte sequence
           that is specific to the charset it is designed for and that
           there is no other possible encoding which can contain this byte
           sequence. This will to lead to an immediate positive answer for
           the detector.
ERROR state: This indicates the state machine identified an illegal byte
             sequence for that encoding. This will lead to an immediate
             negative answer for this encoding. Detector will exclude this
             encoding from consideration from here on.
Definition at line 34 of file codingstatemachine.py.
Constructor & Destructor Documentation
__init__()
None pip._vendor.chardet.codingstatemachine.CodingStateMachine.__init__ (self, CodingStateMachineDict sm)
Definition at line 57 of file codingstatemachine.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), and scipy.stats._distn_infrastructure.rv_generic.random_state().
Member Function Documentation
get_coding_state_machine()
str pip._vendor.chardet.codingstatemachine.CodingStateMachine.get_coding_state_machine (self)
Definition at line 85 of file codingstatemachine.py.
get_current_charlen()
int pip._vendor.chardet.codingstatemachine.CodingStateMachine.get_current_charlen (self)
Definition at line 82 of file codingstatemachine.py.
language()
str pip._vendor.chardet.codingstatemachine.CodingStateMachine.language (self)
Definition at line 89 of file codingstatemachine.py.
next_state()
int pip._vendor.chardet.codingstatemachine.CodingStateMachine.next_state (self, int c)
Definition at line 69 of file codingstatemachine.py.
reset()
None pip._vendor.chardet.codingstatemachine.CodingStateMachine.reset (self)
Definition at line 66 of file codingstatemachine.py.
Referenced by scipy._lib._docscrape.Reader.__init__().
Member Data Documentation
_curr_byte_pos
int pip._vendor.chardet.codingstatemachine.CodingStateMachine._curr_byte_pos = 0 protected
Definition at line 59 of file codingstatemachine.py.
_curr_char_len
int pip._vendor.chardet.codingstatemachine.CodingStateMachine._curr_char_len = 0 protected
Definition at line 60 of file codingstatemachine.py.
_curr_state
pip._vendor.chardet.codingstatemachine.CodingStateMachine._curr_state = MachineState.START protected
Definition at line 61 of file codingstatemachine.py.
_model
pip._vendor.chardet.codingstatemachine.CodingStateMachine._model = sm protected
Definition at line 58 of file codingstatemachine.py.
active
bool pip._vendor.chardet.codingstatemachine.CodingStateMachine.active = True
Definition at line 62 of file codingstatemachine.py.
logger
pip._vendor.chardet.codingstatemachine.CodingStateMachine.logger = logging.getLogger(__name__)
Definition at line 63 of file codingstatemachine.py.
Referenced by pip._vendor.chardet.universaldetector.UniversalDetector.close().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/pip/_vendor/chardet/codingstatemachine.py