Code Cloning Analysis: matplotlib.colors Namespace Reference
matplotlib.colors Namespace Reference
Classes
class _ColorMapping
class AsinhNorm
class BivarColormap
class BivarColormapFromImage
class BoundaryNorm
class CenteredNorm
class ColorConverter
class Colormap
class ColorSequenceRegistry
class FuncNorm
class LightSource
class LinearSegmentedColormap
class ListedColormap
class MultivarColormap
class NoNorm
class Normalize
class PowerNorm
class SegmentedBivarColormap
class SymLogNorm
class TwoSlopeNorm
Functions
get_named_colors_mapping ()
_sanitize_extrema (ex)
_is_nth_color (c)
is_color_like (c)
_has_alpha_channel (c)
_check_color_like (**kwargs)
same_color (c1, c2)
to_rgba (c, alpha=None)
_to_rgba_no_colorcycle (c, alpha=None)
to_rgba_array (c, alpha=None)
to_rgb (c)
to_hex (c, keep_alpha=False)
_create_lookup_table (N, data, gamma=1.0)
End of backwards-compatible color-conversion API.
make_norm_from_scale (scale_cls, base_norm_cls=None, *, init=None)
_make_norm_from_scale (scale_cls, scale_args, scale_kwargs_items, base_norm_cls, bound_init_signature)
_create_empty_object_of_class (cls)
_picklable_norm_constructor (*args)
rgb_to_hsv (arr)
hsv_to_rgb (hsv)
_vector_magnitude (arr)
from_levels_and_colors (levels, colors, extend='neither')
Variables
dict _colors_full_map = {}
tuple _REPR_PNG_SIZE = (512, 64)
int _BIVAR_REPR_PNG_SIZE = 256
_color_sequences = ColorSequenceRegistry()
_nth_color_re = re.compile(r"\AC[0-9]+\Z")
cnames = CSS4_COLORS
Backwards-compatible color-conversion API.
hexColorPattern = re.compile(r"\A#[a-fA-F0-9]{6}\Z")
rgb2hex = to_hex
hex2color = to_rgb
colorConverter = ColorConverter()
LogNorm
__name__
__qualname__
__doc__
__module__
_scale
_trf = self._scale.get_transform()
vmax = self.process_value(value)
vmin = self.vmax:
Detailed Description
A module for converting numbers or color arguments to *RGB* or *RGBA*.
*RGB* and *RGBA* are sequences of, respectively, 3 or 4 floats in the
range 0-1.
This module includes functions and classes for color specification conversions,
and for mapping numbers to colors in a 1-D array of colors called a colormap.
Mapping data onto colors using a colormap typically involves two steps: a data
array is first mapped onto the range 0-1 using a subclass of `Normalize`,
then this number is mapped to a color using a subclass of `Colormap`.  Two
subclasses of `Colormap` provided here:  `LinearSegmentedColormap`, which uses
piecewise-linear interpolation to define colormaps, and `ListedColormap`, which
makes a colormap from a list of colors.
.. seealso::
  :ref:`colormap-manipulation` for examples of how to
  make colormaps and
  :ref:`colormaps` for a list of built-in colormaps.
  :ref:`colormapnorms` for more details about data
  normalization
  More colormaps are available at palettable_.
The module also provides functions for checking whether an object can be
interpreted as a color (`is_color_like`), for converting such an object
to an RGBA tuple (`to_rgba`) or to an HTML-like hex string in the
"#rrggbb" format (`to_hex`), and a sequence of colors to an (n, 4)
RGBA array (`to_rgba_array`).  Caching is used for efficiency.
Colors that Matplotlib recognizes are listed at
:ref:`colors_def`.
.. _palettable: https://jiffyclub.github.io/palettable/
.. _xkcd color survey: https://xkcd.com/color/rgb/
Function Documentation
_check_color_like()
matplotlib.colors._check_color_like (** kwargs) protected
For each *key, value* pair in *kwargs*, check that *value* is color-like.
Definition at line 243 of file colors.py.
References is_color_like().
_create_empty_object_of_class()
matplotlib.colors._create_empty_object_of_class (cls) protected
Definition at line 2721 of file colors.py.
_create_lookup_table()
matplotlib.colors._create_lookup_table (N, data, gamma = 1.0) protected
End of backwards-compatible color-conversion API.
    Create an *N* -element 1D lookup table.
    This assumes a mapping :math:`f : [0, 1] \rightarrow [0, 1]`. The returned
    data is an array of N values :math:`y = f(x)` where x is sampled from
    [0, 1].
    By default (*gamma* = 1) x is equidistantly sampled from [0, 1]. The
    *gamma* correction factor :math:`\gamma` distorts this equidistant
    sampling by :math:`x \rightarrow x^\gamma`.
    Parameters
    ----------
    N : int
        The number of elements of the created lookup table; at least 1.
    data : (M, 3) array-like or callable
        Defines the mapping :math:`f`.
        If a (M, 3) array-like, the rows define values (x, y0, y1).  The x
        values must start with x=0, end with x=1, and all x values be in
        increasing order.
        A value between :math:`x_i` and :math:`x_{i+1}` is mapped to the range
        :math:`y^1_{i-1} \ldots y^0_i` by linear interpolation.
        For the simple case of a y-continuous mapping, y0 and y1 are identical.
        The two values of y are to allow for discontinuous mapping functions.
        E.g. a sawtooth with a period of 0.2 and an amplitude of 1 would be::
            [(0, 1, 0), (0.2, 1, 0), (0.4, 1, 0), ..., [(1, 1, 0)]
        In the special case of ``N == 1``, by convention the returned value
        is y0 for x == 1.
        If *data* is a callable, it must accept and return numpy arrays::
           data(x : ndarray) -> ndarray
        and map values between 0 - 1 to 0 - 1.
    gamma : float
        Gamma correction factor for input distribution x of the mapping.
        See also https://en.wikipedia.org/wiki/Gamma_correction.
    Returns
    -------
    array
        The lookup table where ``lut[x * (N-1)]`` gives the closest value
        for values of x between 0 and 1.
    Notes
    -----
    This function is internally used for `.LinearSegmentedColormap`.
Definition at line 582 of file colors.py.
Referenced by matplotlib.colors.LinearSegmentedColormap._init().
_has_alpha_channel()
matplotlib.colors._has_alpha_channel (c) protected
Return whether *c* is a color with an alpha channel.
Definition at line 237 of file colors.py.
_is_nth_color()
matplotlib.colors._is_nth_color (c) protected
Return whether *c* can be interpreted as an item in the color cycle.
Definition at line 219 of file colors.py.
Referenced by is_color_like(), and to_rgba().
_make_norm_from_scale()
matplotlib.colors._make_norm_from_scale (scale_cls, scale_args, scale_kwargs_items, base_norm_cls, bound_init_signature) protected
Helper for `make_norm_from_scale`.
This function is split out to enable caching (in particular so that
different unpickles reuse the same class).  In order to do so,
- ``functools.partial`` *scale_cls* is expanded into ``func, args, kwargs``
  to allow memoizing returned norms (partial instances always compare
  unequal, but we can check identity based on ``func, args, kwargs``;
- *init* is replaced by *init_signature*, as signatures are picklable,
  unlike to arbitrary lambdas.
Definition at line 2613 of file colors.py.
References _make_norm_from_scale().
Referenced by _make_norm_from_scale(), and make_norm_from_scale().
_picklable_norm_constructor()
matplotlib.colors._picklable_norm_constructor (* args) protected
Definition at line 2725 of file colors.py.
_sanitize_extrema()
matplotlib.colors._sanitize_extrema (ex) protected
Definition at line 207 of file colors.py.
_to_rgba_no_colorcycle()
matplotlib.colors._to_rgba_no_colorcycle (c, alpha = None) protected
Convert *c* to an RGBA color, with no support for color-cycle syntax.
If *alpha* is given, force the alpha value of the returned RGBA tuple
to *alpha*. Otherwise, the alpha value from *c* is used, if it has alpha
information, or defaults to 1.
*alpha* is ignored for the color value ``"none"`` (case-insensitive),
which always maps to ``(0, 0, 0, 0)``.
Definition at line 325 of file colors.py.
Referenced by to_rgba().
_vector_magnitude()
matplotlib.colors._vector_magnitude (arr) protected
Definition at line 3221 of file colors.py.
from_levels_and_colors()
matplotlib.colors.from_levels_and_colors (levels, colors, extend = 'neither')
A helper routine to generate a cmap and a norm instance which
behave similar to contourf's levels and colors arguments.
Parameters
----------
levels : sequence of numbers
    The quantization levels used to construct the `BoundaryNorm`.
    Value ``v`` is quantized to level ``i`` if ``lev[i] <= v < lev[i+1]``.
colors : sequence of colors
    The fill color to use for each level. If *extend* is "neither" there
    must be ``n_level - 1`` colors. For an *extend* of "min" or "max" add
    one extra color, and for an *extend* of "both" add two colors.
extend : {'neither', 'min', 'max', 'both'}, optional
    The behaviour when a value falls out of range of the given levels.
    See `~.Axes.contourf` for details.
Returns
-------
cmap : `~matplotlib.colors.Colormap`
norm : `~matplotlib.colors.Normalize`
Definition at line 3661 of file colors.py.
get_named_colors_mapping()
matplotlib.colors.get_named_colors_mapping ()
Return the global mapping of names to named colors.
Definition at line 93 of file colors.py.
hsv_to_rgb()
matplotlib.colors.hsv_to_rgb (hsv)
Convert HSV values to RGB.
Parameters
----------
hsv : (..., 3) array-like
   All values assumed to be in range [0, 1]
Returns
-------
(..., 3) `~numpy.ndarray`
   Colors converted to RGB values in range [0, 1]
Definition at line 3139 of file colors.py.
Referenced by matplotlib.colors.LightSource.blend_hsv().
is_color_like()
matplotlib.colors.is_color_like (c)
Return whether *c* can be interpreted as an RGB(A) color.
Definition at line 224 of file colors.py.
References _is_nth_color(), and to_rgba().
Referenced by _check_color_like().
make_norm_from_scale()
matplotlib.colors.make_norm_from_scale (scale_cls, base_norm_cls = None, * , init = None)
Decorator for building a `.Normalize` subclass from a `~.scale.ScaleBase`
subclass.
After ::
    @make_norm_from_scale(scale_cls)
    class norm_cls(Normalize):
        ...
*norm_cls* is filled with methods so that normalization computations are
forwarded to *scale_cls* (i.e., *scale_cls* is the scale that would be used
for the colorbar of a mappable normalized with *norm_cls*).
If *init* is not passed, then the constructor signature of *norm_cls*
will be ``norm_cls(vmin=None, vmax=None, clip=False)``; these three
parameters will be forwarded to the base class (``Normalize.__init__``),
and a *scale_cls* object will be initialized with no arguments (other than
a dummy axis).
If the *scale_cls* constructor takes additional parameters, then *init*
should be passed to `make_norm_from_scale`.  It is a callable which is
*only* used for its signature.  First, this signature will become the
signature of *norm_cls*.  Second, the *norm_cls* constructor will bind the
parameters passed to it using this signature, extract the bound *vmin*,
*vmax*, and *clip* values, pass those to ``Normalize.__init__``, and
forward the remaining bound values (including any defaults defined by the
signature) to the *scale_cls* constructor.
Definition at line 2563 of file colors.py.
References _make_norm_from_scale().
rgb_to_hsv()
matplotlib.colors.rgb_to_hsv (arr)
Convert an array of float RGB values (in the range [0, 1]) to HSV values.
Parameters
----------
arr : (..., 3) array-like
   All values must be in the range [0, 1]
Returns
-------
(..., 3) `~numpy.ndarray`
   Colors converted to HSV values in range [0, 1]
Definition at line 3074 of file colors.py.
Referenced by matplotlib.colors.LightSource.blend_hsv().
same_color()
matplotlib.colors.same_color (c1, c2)
Return whether the colors *c1* and *c2* are the same.
*c1*, *c2* can be single colors or lists/arrays of colors.
Definition at line 259 of file colors.py.
References to_rgba_array().
to_hex()
matplotlib.colors.to_hex (c, keep_alpha = False)
Convert *c* to a hex color.
Parameters
----------
c : :ref:`color <colors_def>` or `numpy.ma.masked`
keep_alpha : bool, default: False
  If False, use the ``#rrggbb`` format, otherwise use ``#rrggbbaa``.
Returns
-------
str
  ``#rrggbb`` or ``#rrggbbaa`` hex color string
Definition at line 532 of file colors.py.
References to_rgba().
Referenced by matplotlib.colors.BivarColormap._repr_html_(), and matplotlib.colors.Colormap._repr_html_().
to_rgb()
matplotlib.colors.to_rgb (c)
Convert *c* to an RGB color, silently dropping the alpha channel.
Definition at line 527 of file colors.py.
References to_rgba().
to_rgba()
matplotlib.colors.to_rgba (c, alpha = None)
Convert *c* to an RGBA color.
Parameters
----------
c : Matplotlib color or ``np.ma.masked``
alpha : float, optional
    If *alpha* is given, force the alpha value of the returned RGBA tuple
    to *alpha*.
    If None, the alpha value from *c* is used. If *c* does not have an
    alpha channel, then alpha defaults to 1.
    *alpha* is ignored for the color value ``"none"`` (case-insensitive),
    which always maps to ``(0, 0, 0, 0)``.
Returns
-------
tuple
    Tuple of floats ``(r, g, b, a)``, where each channel (red, green, blue,
    alpha) can assume values between 0 and 1.
Definition at line 278 of file colors.py.
References _is_nth_color(), and _to_rgba_no_colorcycle().
Referenced by is_color_like(), matplotlib.colors.ColorSequenceRegistry.register(), matplotlib.colors.Colormap.set_bad(), matplotlib.colors.Colormap.set_over(), matplotlib.colors.Colormap.set_under(), to_hex(), to_rgb(), to_rgba_array(), matplotlib.colors.BivarColormap.with_extremes(), and matplotlib.colors.MultivarColormap.with_extremes().
to_rgba_array()
matplotlib.colors.to_rgba_array (c, alpha = None)
Convert *c* to a (n, 4) array of RGBA colors.
Parameters
----------
c : Matplotlib color or array of colors
    If *c* is a masked array, an `~numpy.ndarray` is returned with a
    (0, 0, 0, 0) row for each masked value or row in *c*.
alpha : float or sequence of floats, optional
    If *alpha* is given, force the alpha value of the returned RGBA tuple
    to *alpha*.
    If None, the alpha value from *c* is used. If *c* does not have an
    alpha channel, then alpha defaults to 1.
    *alpha* is ignored for the color value ``"none"`` (case-insensitive),
    which always maps to ``(0, 0, 0, 0)``.
    If *alpha* is a sequence and *c* is a single color, *c* will be
    repeated to match the length of *alpha*.
Returns
-------
array
    (n, 4) array of RGBA colors,  where each channel (red, green, blue,
    alpha) can assume values between 0 and 1.
Definition at line 419 of file colors.py.
References to_rgba().
Referenced by matplotlib.colors.ListedColormap._init(), matplotlib.colors.LinearSegmentedColormap.from_list(), and same_color().
Variable Documentation
__doc__
matplotlib.colors.__doc__ private
Definition at line 2769 of file colors.py.
__module__
matplotlib.colors.__module__ private
Definition at line 2640 of file colors.py.
__name__
matplotlib.colors.__name__ private
Definition at line 2768 of file colors.py.
__qualname__
matplotlib.colors.__qualname__ private
Definition at line 2768 of file colors.py.
_BIVAR_REPR_PNG_SIZE
int matplotlib.colors._BIVAR_REPR_PNG_SIZE = 256 protected
Definition at line 90 of file colors.py.
_color_sequences
matplotlib.colors._color_sequences = ColorSequenceRegistry() protected
Definition at line 204 of file colors.py.
_colors_full_map
matplotlib.colors._colors_full_map = {} protected
Definition at line 75 of file colors.py.
_nth_color_re
matplotlib.colors._nth_color_re = re.compile(r"\AC[0-9]+\Z") protected
Definition at line 216 of file colors.py.
_REPR_PNG_SIZE
tuple matplotlib.colors._REPR_PNG_SIZE = (512, 64) protected
Definition at line 89 of file colors.py.
_scale
matplotlib.colors._scale protected
Initial value:
=  functools.partial(
                scale_cls, *scale_args, **dict(scale_kwargs_items))(
                    axis=None, **ba.arguments)
Definition at line 2655 of file colors.py.
_trf
matplotlib.colors._trf = self._scale.get_transform() protected
Definition at line 2658 of file colors.py.
cnames
matplotlib.colors.cnames = CSS4_COLORS
Backwards-compatible color-conversion API.
Definition at line 557 of file colors.py.
colorConverter
matplotlib.colors.colorConverter = ColorConverter()
Definition at line 576 of file colors.py.
hex2color
matplotlib.colors.hex2color = to_rgb
Definition at line 560 of file colors.py.
hexColorPattern
matplotlib.colors.hexColorPattern = re.compile(r"\A#[a-fA-F0-9]{6}\Z")
Definition at line 558 of file colors.py.
LogNorm
matplotlib.colors.LogNorm
Initial value:
=  make_norm_from_scale(
    functools.partial(scale.LogScale, nonpositive="mask"))(Normalize)
Definition at line 2766 of file colors.py.
rgb2hex
matplotlib.colors.rgb2hex = to_hex
Definition at line 559 of file colors.py.
vmax
matplotlib.colors.vmax = self.process_value(value)
Definition at line 2668 of file colors.py.
vmin
matplotlib.colors.vmin = self.vmax:
Definition at line 2670 of file colors.py.