Code Cloning Analysis: pandas.tests.resample.test_datetime_index Namespace Reference
pandas.tests.resample.test_datetime_index Namespace Reference
Functions
_index_factory ()
_index_freq ()
_static_values (index)
unit (request)
simple_date_range_series ()
test_custom_grouper (index, unit)
test_custom_grouper_df (index, unit)
test_resample_basic (series, closed, expected, unit)
test_resample_integerarray (unit)
test_resample_basic_grouper (series, unit)
test_resample_string_kwargs (series, keyword, value, unit)
test_resample_how (series, downsample_method, unit)
test_resample_how_ohlc (series, unit)
test_resample_how_callables (unit)
test_resample_rounding (unit)
test_resample_basic_from_daily (unit)
test_resample_upsampling_picked_but_not_correct (unit)
test_resample_frame_basic_cy_funcs (f, unit)
test_resample_frame_basic_M_A (freq, unit)
test_resample_frame_basic_kind (freq, unit)
test_resample_upsample (unit)
test_resample_how_method (unit)
test_resample_extra_index_point (unit)
test_upsample_with_limit (unit)
test_nearest_upsample_with_limit (tz_aware_fixture, freq, rule, unit)
test_resample_ohlc (series, unit)
test_resample_ohlc_result (unit)
test_resample_ohlc_result_odd_period (unit)
test_resample_ohlc_dataframe (unit)
test_resample_dup_index ()
test_resample_reresample (unit)
test_resample_timestamp_to_period (simple_date_range_series, freq, expected_kwargs, unit)
test_ohlc_5min (unit)
test_downsample_non_unique (unit)
test_asfreq_non_unique (unit)
test_resample_axis1 (unit)
test_resample_anchored_ticks (freq, unit)
test_resample_single_group (end, unit)
test_resample_single_group_std (unit)
test_resample_offset (unit)
test_resample_origin (kwargs, unit)
test_resample_bad_origin (origin, unit)
test_resample_bad_offset (offset, unit)
test_resample_origin_prime_freq (unit)
test_resample_origin_with_tz (unit)
test_resample_origin_epoch_with_tz_day_vs_24h (unit)
test_resample_origin_with_day_freq_on_dst (unit)
test_resample_daily_anchored (unit)
test_resample_to_period_monthly_buglet (unit)
test_period_with_agg ()
test_resample_segfault (unit)
test_resample_dtype_preservation (unit)
test_resample_dtype_coercion (unit)
test_weekly_resample_buglet (unit)
test_monthly_resample_error (unit)
test_nanosecond_resample_error ()
test_resample_anchored_intraday (unit)
test_resample_anchored_intraday2 (unit)
test_resample_anchored_intraday3 (simple_date_range_series, unit)
test_resample_anchored_monthstart (simple_date_range_series, freq, unit)
test_resample_anchored_multiday (label, sec)
test_corner_cases (unit)
test_corner_cases_date (simple_date_range_series, unit)
test_anchored_lowercase_buglet (unit)
test_upsample_apply_functions (unit)
test_resample_not_monotonic (unit)
test_resample_median_bug_1688 (dtype, unit)
test_how_lambda_functions (simple_date_range_series, unit)
test_resample_unequal_times (unit)
test_resample_consistency (unit)
test_resample_timegrouper (dates, unit)
test_resample_timegrouper2 (dates, unit)
test_resample_nunique (unit)
test_resample_nunique_preserves_column_level_names (unit)
test_resample_nunique_with_date_gap (func, unit)
test_resample_group_info (n, k, unit)
test_resample_size (unit)
test_resample_across_dst ()
test_groupby_with_dst_time_change (unit)
test_resample_dst_anchor (unit)
test_resample_dst_anchor2 (unit)
test_downsample_across_dst (unit)
test_downsample_across_dst_weekly (unit)
test_downsample_across_dst_weekly_2 (unit)
test_downsample_dst_at_midnight (unit)
test_resample_with_nat (unit)
test_resample_datetime_values (unit)
test_resample_apply_with_additional_args (series, unit)
test_resample_apply_with_additional_args2 ()
test_resample_equivalent_offsets (n1, freq1, n2, freq2, k, unit)
test_get_timestamp_range_edges (first, last, freq, exp_first, exp_last, unit)
test_resample_apply_product (duplicates, unit)
test_resample_calendar_day_with_dst (str first, str last, str freq_in, str freq_out, str exp_last, unit)
test_resample_aggregate_functions_min_count (func, unit)
test_resample_unsigned_int (any_unsigned_int_numpy_dtype, unit)
test_long_rule_non_nano ()
test_resample_empty_series_with_tz ()
test_resample_M_Q_Y_A_deprecated (freq, freq_depr)
test_resample_BM_BQ_deprecated (freq, freq_depr)
test_resample_ms_closed_right (unit)
test_resample_c_b_closed_right (str freq, unit)
test_resample_b_55282 (unit)
test_arrow_timestamp_resample (tz)
Variables
list dates1
tuple dates2
list dates3 = [pd.NaT] + dates1 + [pd.NaT]
Function Documentation
_index_factory()
pandas.tests.resample.test_datetime_index._index_factory () protected
Definition at line 40 of file test_datetime_index.py.
_index_freq()
pandas.tests.resample.test_datetime_index._index_freq () protected
Definition at line 45 of file test_datetime_index.py.
_static_values()
pandas.tests.resample.test_datetime_index._static_values (index) protected
Definition at line 50 of file test_datetime_index.py.
simple_date_range_series()
pandas.tests.resample.test_datetime_index.simple_date_range_series ()
Series with date range index and random data for test purposes.
Definition at line 60 of file test_datetime_index.py.
References simple_date_range_series(), and pytz.timezone().
Referenced by simple_date_range_series().
test_anchored_lowercase_buglet()
pandas.tests.resample.test_datetime_index.test_anchored_lowercase_buglet (unit)
Definition at line 1272 of file test_datetime_index.py.
test_arrow_timestamp_resample()
pandas.tests.resample.test_datetime_index.test_arrow_timestamp_resample (tz)
Definition at line 2224 of file test_datetime_index.py.
test_asfreq_non_unique()
pandas.tests.resample.test_datetime_index.test_asfreq_non_unique (unit)
Definition at line 751 of file test_datetime_index.py.
test_corner_cases()
pandas.tests.resample.test_datetime_index.test_corner_cases (unit)
Definition at line 1250 of file test_datetime_index.py.
test_corner_cases_date()
pandas.tests.resample.test_datetime_index.test_corner_cases_date (simple_date_range_series, unit)
Definition at line 1261 of file test_datetime_index.py.
test_custom_grouper()
pandas.tests.resample.test_datetime_index.test_custom_grouper (index, unit)
Definition at line 72 of file test_datetime_index.py.
test_custom_grouper_df()
pandas.tests.resample.test_datetime_index.test_custom_grouper_df (index, unit)
Definition at line 108 of file test_datetime_index.py.
test_downsample_across_dst()
pandas.tests.resample.test_datetime_index.test_downsample_across_dst (unit)
Definition at line 1738 of file test_datetime_index.py.
test_downsample_across_dst_weekly()
pandas.tests.resample.test_datetime_index.test_downsample_across_dst_weekly (unit)
Definition at line 1751 of file test_datetime_index.py.
test_downsample_across_dst_weekly_2()
pandas.tests.resample.test_datetime_index.test_downsample_across_dst_weekly_2 (unit)
Definition at line 1770 of file test_datetime_index.py.
test_downsample_dst_at_midnight()
pandas.tests.resample.test_datetime_index.test_downsample_dst_at_midnight (unit)
Definition at line 1786 of file test_datetime_index.py.
test_downsample_non_unique()
pandas.tests.resample.test_datetime_index.test_downsample_non_unique (unit)
Definition at line 738 of file test_datetime_index.py.
test_get_timestamp_range_edges()
pandas.tests.resample.test_datetime_index.test_get_timestamp_range_edges (first, last, freq, exp_first, exp_last, unit)
Definition at line 1931 of file test_datetime_index.py.
test_groupby_with_dst_time_change()
pandas.tests.resample.test_datetime_index.test_groupby_with_dst_time_change (unit)
Definition at line 1607 of file test_datetime_index.py.
test_how_lambda_functions()
pandas.tests.resample.test_datetime_index.test_how_lambda_functions (simple_date_range_series, unit)
Definition at line 1334 of file test_datetime_index.py.
test_long_rule_non_nano()
pandas.tests.resample.test_datetime_index.test_long_rule_non_nano ()
Definition at line 2056 of file test_datetime_index.py.
test_monthly_resample_error()
pandas.tests.resample.test_datetime_index.test_monthly_resample_error (unit)
Definition at line 1138 of file test_datetime_index.py.
test_nanosecond_resample_error()
pandas.tests.resample.test_datetime_index.test_nanosecond_resample_error ()
Definition at line 1146 of file test_datetime_index.py.
test_nearest_upsample_with_limit()
pandas.tests.resample.test_datetime_index.test_nearest_upsample_with_limit (tz_aware_fixture, freq, rule, unit)
Definition at line 549 of file test_datetime_index.py.
test_ohlc_5min()
pandas.tests.resample.test_datetime_index.test_ohlc_5min (unit)
Definition at line 718 of file test_datetime_index.py.
test_period_with_agg()
pandas.tests.resample.test_datetime_index.test_period_with_agg ()
Definition at line 1052 of file test_datetime_index.py.
test_resample_across_dst()
pandas.tests.resample.test_datetime_index.test_resample_across_dst ()
Definition at line 1575 of file test_datetime_index.py.
test_resample_aggregate_functions_min_count()
pandas.tests.resample.test_datetime_index.test_resample_aggregate_functions_min_count (func, unit)
Definition at line 2020 of file test_datetime_index.py.
test_resample_anchored_intraday()
pandas.tests.resample.test_datetime_index.test_resample_anchored_intraday (unit)
Definition at line 1162 of file test_datetime_index.py.
test_resample_anchored_intraday2()
pandas.tests.resample.test_datetime_index.test_resample_anchored_intraday2 (unit)
Definition at line 1189 of file test_datetime_index.py.
test_resample_anchored_intraday3()
pandas.tests.resample.test_datetime_index.test_resample_anchored_intraday3 (simple_date_range_series, unit)
Definition at line 1217 of file test_datetime_index.py.
test_resample_anchored_monthstart()
pandas.tests.resample.test_datetime_index.test_resample_anchored_monthstart (simple_date_range_series, freq, unit)
Definition at line 1225 of file test_datetime_index.py.
test_resample_anchored_multiday()
pandas.tests.resample.test_datetime_index.test_resample_anchored_multiday (label, sec)
Definition at line 1232 of file test_datetime_index.py.
test_resample_anchored_ticks()
pandas.tests.resample.test_datetime_index.test_resample_anchored_ticks (freq, unit)
Definition at line 778 of file test_datetime_index.py.
test_resample_apply_product()
pandas.tests.resample.test_datetime_index.test_resample_apply_product (duplicates, unit)
Definition at line 1947 of file test_datetime_index.py.
test_resample_apply_with_additional_args()
pandas.tests.resample.test_datetime_index.test_resample_apply_with_additional_args (series, unit)
Definition at line 1857 of file test_datetime_index.py.
test_resample_apply_with_additional_args2()
pandas.tests.resample.test_datetime_index.test_resample_apply_with_additional_args2 ()
Definition at line 1875 of file test_datetime_index.py.
test_resample_axis1()
pandas.tests.resample.test_datetime_index.test_resample_axis1 (unit)
Definition at line 762 of file test_datetime_index.py.
test_resample_b_55282()
pandas.tests.resample.test_datetime_index.test_resample_b_55282 (unit)
Definition at line 2188 of file test_datetime_index.py.
test_resample_bad_offset()
pandas.tests.resample.test_datetime_index.test_resample_bad_offset (offset, unit)
Definition at line 868 of file test_datetime_index.py.
test_resample_bad_origin()
pandas.tests.resample.test_datetime_index.test_resample_bad_origin (origin, unit)
Definition at line 855 of file test_datetime_index.py.
test_resample_basic()
pandas.tests.resample.test_datetime_index.test_resample_basic (series, closed, expected, unit)
Definition at line 145 of file test_datetime_index.py.
test_resample_basic_from_daily()
pandas.tests.resample.test_datetime_index.test_resample_basic_from_daily (unit)
Definition at line 352 of file test_datetime_index.py.
test_resample_basic_grouper()
pandas.tests.resample.test_datetime_index.test_resample_basic_grouper (series, unit)
Definition at line 178 of file test_datetime_index.py.
test_resample_BM_BQ_deprecated()
pandas.tests.resample.test_datetime_index.test_resample_BM_BQ_deprecated (freq, freq_depr)
Definition at line 2129 of file test_datetime_index.py.
test_resample_c_b_closed_right()
pandas.tests.resample.test_datetime_index.test_resample_c_b_closed_right (str freq, unit)
Definition at line 2158 of file test_datetime_index.py.
test_resample_calendar_day_with_dst()
pandas.tests.resample.test_datetime_index.test_resample_calendar_day_with_dst (str first, str last, str freq_in, str freq_out, str exp_last, unit)
Definition at line 2004 of file test_datetime_index.py.
test_resample_consistency()
pandas.tests.resample.test_datetime_index.test_resample_consistency (unit)
Definition at line 1373 of file test_datetime_index.py.
test_resample_daily_anchored()
pandas.tests.resample.test_datetime_index.test_resample_daily_anchored (unit)
Definition at line 1029 of file test_datetime_index.py.
test_resample_datetime_values()
pandas.tests.resample.test_datetime_index.test_resample_datetime_values (unit)
Definition at line 1836 of file test_datetime_index.py.
test_resample_dst_anchor()
pandas.tests.resample.test_datetime_index.test_resample_dst_anchor (unit)
Definition at line 1626 of file test_datetime_index.py.
test_resample_dst_anchor2()
pandas.tests.resample.test_datetime_index.test_resample_dst_anchor2 (unit)
Definition at line 1646 of file test_datetime_index.py.
test_resample_dtype_coercion()
pandas.tests.resample.test_datetime_index.test_resample_dtype_coercion (unit)
Definition at line 1112 of file test_datetime_index.py.
test_resample_dtype_preservation()
pandas.tests.resample.test_datetime_index.test_resample_dtype_preservation (unit)
Definition at line 1091 of file test_datetime_index.py.
test_resample_dup_index()
pandas.tests.resample.test_datetime_index.test_resample_dup_index ()
Definition at line 664 of file test_datetime_index.py.
test_resample_empty_series_with_tz()
pandas.tests.resample.test_datetime_index.test_resample_empty_series_with_tz ()
Definition at line 2081 of file test_datetime_index.py.
test_resample_equivalent_offsets()
pandas.tests.resample.test_datetime_index.test_resample_equivalent_offsets (n1, freq1, n2, freq2, k, unit)
Definition at line 1908 of file test_datetime_index.py.
test_resample_extra_index_point()
pandas.tests.resample.test_datetime_index.test_resample_extra_index_point (unit)
Definition at line 527 of file test_datetime_index.py.
test_resample_frame_basic_cy_funcs()
pandas.tests.resample.test_datetime_index.test_resample_frame_basic_cy_funcs (f, unit)
Definition at line 441 of file test_datetime_index.py.
test_resample_frame_basic_kind()
pandas.tests.resample.test_datetime_index.test_resample_frame_basic_kind (freq, unit)
Definition at line 469 of file test_datetime_index.py.
test_resample_frame_basic_M_A()
pandas.tests.resample.test_datetime_index.test_resample_frame_basic_M_A (freq, unit)
Definition at line 457 of file test_datetime_index.py.
test_resample_group_info()
pandas.tests.resample.test_datetime_index.test_resample_group_info (n, k, unit)
Definition at line 1526 of file test_datetime_index.py.
test_resample_how()
pandas.tests.resample.test_datetime_index.test_resample_how (series, downsample_method, unit)
Definition at line 211 of file test_datetime_index.py.
test_resample_how_callables()
pandas.tests.resample.test_datetime_index.test_resample_how_callables (unit)
Definition at line 263 of file test_datetime_index.py.
test_resample_how_method()
pandas.tests.resample.test_datetime_index.test_resample_how_method (unit)
Definition at line 498 of file test_datetime_index.py.
test_resample_how_ohlc()
pandas.tests.resample.test_datetime_index.test_resample_how_ohlc (series, unit)
Definition at line 237 of file test_datetime_index.py.
test_resample_integerarray()
pandas.tests.resample.test_datetime_index.test_resample_integerarray (unit)
Definition at line 154 of file test_datetime_index.py.
test_resample_M_Q_Y_A_deprecated()
pandas.tests.resample.test_datetime_index.test_resample_M_Q_Y_A_deprecated (freq, freq_depr)
Definition at line 2109 of file test_datetime_index.py.
test_resample_median_bug_1688()
pandas.tests.resample.test_datetime_index.test_resample_median_bug_1688 (dtype, unit)
Definition at line 1314 of file test_datetime_index.py.
test_resample_ms_closed_right()
pandas.tests.resample.test_datetime_index.test_resample_ms_closed_right (unit)
Definition at line 2141 of file test_datetime_index.py.
test_resample_not_monotonic()
pandas.tests.resample.test_datetime_index.test_resample_not_monotonic (unit)
Definition at line 1289 of file test_datetime_index.py.
test_resample_nunique()
pandas.tests.resample.test_datetime_index.test_resample_nunique (unit)
Definition at line 1456 of file test_datetime_index.py.
test_resample_nunique_preserves_column_level_names()
pandas.tests.resample.test_datetime_index.test_resample_nunique_preserves_column_level_names (unit)
Definition at line 1487 of file test_datetime_index.py.
test_resample_nunique_with_date_gap()
pandas.tests.resample.test_datetime_index.test_resample_nunique_with_date_gap (func, unit)
Definition at line 1511 of file test_datetime_index.py.
test_resample_offset()
pandas.tests.resample.test_datetime_index.test_resample_offset (unit)
Definition at line 815 of file test_datetime_index.py.
test_resample_ohlc()
pandas.tests.resample.test_datetime_index.test_resample_ohlc (series, unit)
Definition at line 561 of file test_datetime_index.py.
test_resample_ohlc_dataframe()
pandas.tests.resample.test_datetime_index.test_resample_ohlc_dataframe (unit)
Definition at line 616 of file test_datetime_index.py.
test_resample_ohlc_result()
pandas.tests.resample.test_datetime_index.test_resample_ohlc_result (unit)
Definition at line 585 of file test_datetime_index.py.
test_resample_ohlc_result_odd_period()
pandas.tests.resample.test_datetime_index.test_resample_ohlc_result_odd_period (unit)
Definition at line 598 of file test_datetime_index.py.
test_resample_origin()
pandas.tests.resample.test_datetime_index.test_resample_origin (kwargs, unit)
Definition at line 839 of file test_datetime_index.py.
test_resample_origin_epoch_with_tz_day_vs_24h()
pandas.tests.resample.test_datetime_index.test_resample_origin_epoch_with_tz_day_vs_24h (unit)
Definition at line 946 of file test_datetime_index.py.
test_resample_origin_prime_freq()
pandas.tests.resample.test_datetime_index.test_resample_origin_prime_freq (unit)
Definition at line 876 of file test_datetime_index.py.
test_resample_origin_with_day_freq_on_dst()
pandas.tests.resample.test_datetime_index.test_resample_origin_with_day_freq_on_dst (unit)
Definition at line 974 of file test_datetime_index.py.
test_resample_origin_with_tz()
pandas.tests.resample.test_datetime_index.test_resample_origin_with_tz (unit)
Definition at line 913 of file test_datetime_index.py.
test_resample_reresample()
pandas.tests.resample.test_datetime_index.test_resample_reresample (unit)
Definition at line 684 of file test_datetime_index.py.
test_resample_rounding()
pandas.tests.resample.test_datetime_index.test_resample_rounding (unit)
Definition at line 288 of file test_datetime_index.py.
test_resample_segfault()
pandas.tests.resample.test_datetime_index.test_resample_segfault (unit)
Definition at line 1068 of file test_datetime_index.py.
test_resample_single_group()
pandas.tests.resample.test_datetime_index.test_resample_single_group (end, unit)
Definition at line 793 of file test_datetime_index.py.
test_resample_single_group_std()
pandas.tests.resample.test_datetime_index.test_resample_single_group_std (unit)
Definition at line 801 of file test_datetime_index.py.
test_resample_size()
pandas.tests.resample.test_datetime_index.test_resample_size (unit)
Definition at line 1555 of file test_datetime_index.py.
test_resample_string_kwargs()
pandas.tests.resample.test_datetime_index.test_resample_string_kwargs (series, keyword, value, unit)
Definition at line 198 of file test_datetime_index.py.
test_resample_timegrouper()
pandas.tests.resample.test_datetime_index.test_resample_timegrouper (dates, unit)
Definition at line 1412 of file test_datetime_index.py.
test_resample_timegrouper2()
pandas.tests.resample.test_datetime_index.test_resample_timegrouper2 (dates, unit)
Definition at line 1432 of file test_datetime_index.py.
test_resample_timestamp_to_period()
pandas.tests.resample.test_datetime_index.test_resample_timestamp_to_period (simple_date_range_series, freq, expected_kwargs, unit)
Definition at line 704 of file test_datetime_index.py.
test_resample_to_period_monthly_buglet()
pandas.tests.resample.test_datetime_index.test_resample_to_period_monthly_buglet (unit)
Definition at line 1039 of file test_datetime_index.py.
test_resample_unequal_times()
pandas.tests.resample.test_datetime_index.test_resample_unequal_times (unit)
Definition at line 1361 of file test_datetime_index.py.
test_resample_unsigned_int()
pandas.tests.resample.test_datetime_index.test_resample_unsigned_int (any_unsigned_int_numpy_dtype, unit)
Definition at line 2032 of file test_datetime_index.py.
test_resample_upsample()
pandas.tests.resample.test_datetime_index.test_resample_upsample (unit)
Definition at line 481 of file test_datetime_index.py.
test_resample_upsampling_picked_but_not_correct()
pandas.tests.resample.test_datetime_index.test_resample_upsampling_picked_but_not_correct (unit)
Definition at line 410 of file test_datetime_index.py.
test_resample_with_nat()
pandas.tests.resample.test_datetime_index.test_resample_with_nat (unit)
Definition at line 1804 of file test_datetime_index.py.
test_upsample_apply_functions()
pandas.tests.resample.test_datetime_index.test_upsample_apply_functions (unit)
Definition at line 1279 of file test_datetime_index.py.
test_upsample_with_limit()
pandas.tests.resample.test_datetime_index.test_upsample_with_limit (unit)
Definition at line 538 of file test_datetime_index.py.
test_weekly_resample_buglet()
pandas.tests.resample.test_datetime_index.test_weekly_resample_buglet (unit)
Definition at line 1128 of file test_datetime_index.py.
unit()
pandas.tests.resample.test_datetime_index.unit (request)
Definition at line 55 of file test_datetime_index.py.
Variable Documentation
dates1
list pandas.tests.resample.test_datetime_index.dates1
Initial value:
=  [
    datetime(2014, 10, 1),
    datetime(2014, 9, 3),
    datetime(2014, 11, 5),
    datetime(2014, 9, 5),
    datetime(2014, 10, 8),
    datetime(2014, 7, 15),
]
Definition at line 1396 of file test_datetime_index.py.
dates2
tuple pandas.tests.resample.test_datetime_index.dates2
Initial value:
=  (
    dates1[:2] + [pd.NaT] + dates1[2:4] + [pd.NaT] + dates1[4:]
)
Definition at line 1405 of file test_datetime_index.py.
dates3
list pandas.tests.resample.test_datetime_index.dates3 = [pd.NaT] + dates1 + [pd.NaT]
Definition at line 1408 of file test_datetime_index.py.