Code Cloning Analysis: fontTools.voltLib.parser.OrderedSymbolTable Class Reference
fontTools.voltLib.parser.OrderedSymbolTable Class Reference
Public Member Functions
__init__ (self)
enter_scope (self)
resolve (self, name, case_insensitive=False)
range (self, start, end)
Public Member Functions inherited from fontTools.voltLib.parser.SymbolTable
__init__ (self)
exit_scope (self)
define (self, name, item)
Additional Inherited Members
Public Attributes inherited from fontTools.voltLib.parser.SymbolTable
list scopes_ = [{}]
Detailed Description
Definition at line 648 of file parser.py.
Constructor & Destructor Documentation
__init__()
fontTools.voltLib.parser.OrderedSymbolTable.__init__ (self)
Definition at line 649 of file parser.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
enter_scope()
fontTools.voltLib.parser.OrderedSymbolTable.enter_scope (self)
Reimplemented from fontTools.voltLib.parser.SymbolTable.
Definition at line 652 of file parser.py.
range()
fontTools.voltLib.parser.OrderedSymbolTable.range (self, start, end)
Definition at line 658 of file parser.py.
resolve()
fontTools.voltLib.parser.OrderedSymbolTable.resolve (self, name, case_insensitive = False)
Reimplemented from fontTools.voltLib.parser.SymbolTable.
Definition at line 655 of file parser.py.
Referenced by pip._vendor.distlib.compat.BaseConfigurator.configure_custom(), and pip._vendor.distlib.compat.BaseConfigurator.ext_convert().
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/voltLib/parser.py