Code Cloning Analysis: fontTools.ufoLib.UFOWriter Class Reference
fontTools.ufoLib.UFOWriter Class Reference
Public Member Functions
__init__ (self, path, formatVersion=None, fileCreator="com.github.fonttools.ufoLib", structure=None, validate=True)
copyFromReader (self, reader, sourcePath, destPath)
writeBytesToPath (self, path, data)
getFileObjectForPath (self, path, mode="w", encoding=None)
removePath (self, path, force=False, removeEmptyParents=True)
setModificationTime (self)
setKerningGroupConversionRenameMaps (self, maps)
writeGroups (self, groups, validate=None)
writeInfo (self, info, validate=None)
writeKerning (self, kerning, validate=None)
writeLib (self, libDict, validate=None)
writeFeatures (self, features, validate=None)
writeLayerContents (self, layerOrder=None, validate=None)
getGlyphSet (self, layerName=None, defaultLayer=True, glyphNameToFileNameFunc=None, validateRead=None, validateWrite=None, expectContentsFile=False)
renameGlyphSet (self, layerName, newLayerName, defaultLayer=False)
deleteGlyphSet (self, layerName)
writeData (self, fileName, data)
removeData (self, fileName)
writeImage (self, fileName, data, validate=None)
removeImage (self, fileName, validate=None)
copyImageFromReader (self, reader, sourceFileName, destFileName, validate=None)
close (self)
Public Member Functions inherited from fontTools.ufoLib.UFOReader
__init__ (self, path, validate=True)
formatVersionTuple (self)
readBytesFromPath (self, path)
getReadFileForPath (self, path, encoding=None)
readMetaInfo (self, validate=None)
readGroups (self, validate=None)
getKerningGroupConversionRenameMaps (self, validate=None)
readInfo (self, info, validate=None)
readKerning (self, validate=None)
readLib (self, validate=None)
readFeatures (self)
getLayerNames (self, validate=None)
getDefaultLayerName (self, validate=None)
getCharacterMapping (self, layerName=None, validate=None)
getDataDirectoryListing (self)
getImageDirectoryListing (self, validate=None)
readData (self, fileName)
readImage (self, fileName, validate=None)
__enter__ (self)
__exit__ (self, exc_type, exc_value, exc_tb)
Public Member Functions inherited from fontTools.ufoLib._UFOBaseIO
getFileModificationTime (self, path)
Public Attributes
dict layerContents = {}
Public Attributes inherited from fontTools.ufoLib._UFOBaseIO
fs = plistlib.dumps(obj)
Static Public Attributes
removeFileForPath = removePath
Protected Member Functions
_get_fileCreator (self)
_writeMetaInfo (self)
_findDirectoryForLayerName (self, layerName)
_getDefaultGlyphSet (self, validateRead, validateWrite, glyphNameToFileNameFunc=None, expectContentsFile=False)
_getGlyphSetFormatVersion3 (self, validateRead, validateWrite, layerName=None, defaultLayer=True, glyphNameToFileNameFunc=None, expectContentsFile=False)
Protected Member Functions inherited from fontTools.ufoLib.UFOReader
_get_path (self)
_get_formatVersion (self)
_get_fileStructure (self)
_upConvertKerning (self, validate)
_readMetaInfo (self, validate=None)
_readGroups (self)
_readInfo (self, validate)
_readKerning (self)
_readLayerContents (self, validate)
Protected Member Functions inherited from fontTools.ufoLib._UFOBaseIO
_getPlist (self, fileName, default=None)
_writePlist (self, fileName, obj)
Protected Attributes
_fileCreator = fileCreator
_downConversionKerningData = None
Protected Attributes inherited from fontTools.ufoLib.UFOReader
bool _shouldClose = True
_fileStructure = structure
_path = fsdecode(path)
_validate = validate
_upConvertedKerningData = None
_formatVersion = data["formatVersionTuple"]
_dataFS = self.fs.opendir(DATA_DIRNAME)
_imagesFS = self.fs.opendir(IMAGES_DIRNAME)
Protected Attributes inherited from fontTools.ufoLib._UFOBaseIO
_havePreviousFile
Properties
fileCreator
Properties inherited from fontTools.ufoLib.UFOReader
path = property(_get_path, doc="The path of the UFO (DEPRECATED).")
formatVersion
fileStructure
Detailed Description
Write the various components of a .ufo.
Attributes:
    path: An :class:`os.PathLike` object pointing to the .ufo.
    formatVersion: the UFO format version as a tuple of integers (major, minor),
        or as a single integer for the major digit only (minor is implied to be 0).
        By default, the latest formatVersion will be used; currently it is 3.0,
        which is equivalent to formatVersion=(3, 0).
    fileCreator: The creator of the .ufo file. Defaults to
        `com.github.fonttools.ufoLib`.
    structure: The internal structure of the .ufo file: either `ZIP` or `PACKAGE`.
    validate: A boolean indicating if the data read should be validated. Defaults
        to `True`.
By default, the written data will be validated before writing. Set ``validate`` to
``False`` if you do not want to validate the data. Validation can also be overriden
on a per-method level if desired.
Raises:
    UnsupportedUFOFormat: An exception indicating that the requested UFO
        formatVersion is not supported.
Definition at line 887 of file __init__.py.
Constructor & Destructor Documentation
__init__()
fontTools.ufoLib.UFOWriter.__init__ (self, path, formatVersion = None, fileCreator = "com.github.fonttools.ufoLib", structure = None, validate = True)
Definition at line 911 of file __init__.py.
Referenced by sklearn.gaussian_process.kernels.Kernel.get_params(), scipy.stats._distn_infrastructure.rv_generic.random_state(), and pandas.plotting._misc._Options.reset().
Member Function Documentation
_findDirectoryForLayerName()
fontTools.ufoLib.UFOWriter._findDirectoryForLayerName (self, layerName) protected
Definition at line 1449 of file __init__.py.
Referenced by deleteGlyphSet(), and renameGlyphSet().
_get_fileCreator()
fontTools.ufoLib.UFOWriter._get_fileCreator (self) protected
Definition at line 1067 of file __init__.py.
_getDefaultGlyphSet()
fontTools.ufoLib.UFOWriter._getDefaultGlyphSet (self, validateRead, validateWrite, glyphNameToFileNameFunc = None, expectContentsFile = False) protected
Definition at line 1531 of file __init__.py.
Referenced by getGlyphSet().
_getGlyphSetFormatVersion3()
fontTools.ufoLib.UFOWriter._getGlyphSetFormatVersion3 (self, validateRead, validateWrite, layerName = None, defaultLayer = True, glyphNameToFileNameFunc = None, expectContentsFile = False) protected
Definition at line 1550 of file __init__.py.
Referenced by getGlyphSet().
_writeMetaInfo()
fontTools.ufoLib.UFOWriter._writeMetaInfo (self) protected
Definition at line 1188 of file __init__.py.
close()
fontTools.ufoLib.UFOWriter.close (self)
Reimplemented from fontTools.ufoLib.UFOReader.
Definition at line 1724 of file __init__.py.
Referenced by pandas.io.pytables.HDFStore.__contains__(), matplotlib.dviread.Dvi.__exit__(), matplotlib.backends.backend_pdf.PdfPages.__init__(), matplotlib.backends.backend_pgf.PdfPages.__init__(), pandas.io.parsers.python_parser.PythonParser.__init__(), pip._vendor.urllib3.util.ssltransport.SSLTransport.__init__(), pip._vendor.urllib3.contrib.securetransport.WrappedSocket._custom_validate(), pandas.io.excel._odfreader.ODFReader._get_row_repeat(), pip._vendor.urllib3.contrib.securetransport.WrappedSocket._raise_on_error(), matplotlib.dviread.Dvi._read(), pandas.io.parsers.c_parser_wrapper.CParserWrapper._set_noconvert_columns(), pandas.io.excel._base.ExcelWriter.check_extension(), numpy.lib.npyio.NpzFile.close(), pandas.io.common.IOHandles.close(), pandas.io.excel._base.ExcelFile.close(), pandas.io.json._json.JsonReader.close(), scipy.io._fortran.FortranFile.close(), scipy.io._netcdf.netcdf_file.close(), pandas.io.sas.sas7bdat.SAS7BDATReader.column_types(), PIL.ImageFile.Parser.feed(), pandas.io.sas.sas_xport.XportReader.get_chunk(), fontTools.ufoLib.glifLib.GlyphSet.getImageReferences(), pip._vendor.urllib3.contrib.securetransport.WrappedSocket.handshake(), pandas.io.pytables.HDFStore.open(), PIL.PngImagePlugin.ChunkStream.read(), PIL.ContainerIO.ContainerIO.readlines(), pandas.io.excel._odfreader.ODFReader.sheet_names(), and pip._vendor.urllib3.response.HTTPResponse.supports_chunked_reads().
copyFromReader()
fontTools.ufoLib.UFOWriter.copyFromReader (self, reader, sourcePath, destPath)
Copy the sourcePath in the provided UFOReader to destPath
in this writer. The paths must be relative. This works with
both individual files and directories.
Definition at line 1077 of file __init__.py.
References fontTools.ufoLib._UFOBaseIO.fs.
Referenced by copyImageFromReader().
copyImageFromReader()
fontTools.ufoLib.UFOWriter.copyImageFromReader (self, reader, sourceFileName, destFileName, validate = None)
Copy the sourceFileName in the provided UFOReader to destFileName
in this writer. This uses the most memory efficient method possible
for copying the data possible.
Definition at line 1708 of file __init__.py.
References fontTools.ufoLib.UFOReader._fileStructure, fontTools.ufoLib.UFOReader._formatVersion, fontTools.ufoLib._UFOBaseIO._havePreviousFile, fontTools.ufoLib.UFOReader._path, fontTools.ufoLib.UFOReader._validate, copyFromReader(), and fontTools.ufoLib._UFOBaseIO.fs.
deleteGlyphSet()
fontTools.ufoLib.UFOWriter.deleteGlyphSet (self, layerName)
Remove the glyph set matching layerName.
Definition at line 1652 of file __init__.py.
References _findDirectoryForLayerName(), fontTools.ufoLib.UFOReader._formatVersion, layerContents, and removePath().
getFileObjectForPath()
fontTools.ufoLib.UFOWriter.getFileObjectForPath (self, path, mode = "w", encoding = None)
Returns a file (or file-like) object for the
file at the given path. The path must be relative
to the UFO path. Returns None if the file does
not exist and the mode is "r" or "rb.
An encoding may be passed if the file is opened in text mode.
Note: The caller is responsible for closing the open file.
Definition at line 1120 of file __init__.py.
References fontTools.ufoLib._UFOBaseIO.fs.
getGlyphSet()
fontTools.ufoLib.UFOWriter.getGlyphSet (self, layerName = None, defaultLayer = True, glyphNameToFileNameFunc = None, validateRead = None, validateWrite = None, expectContentsFile = False)
Return the GlyphSet object associated with the
appropriate glyph directory in the .ufo.
If layerName is None, the default glyph set
will be used. The defaultLayer flag indictes
that the layer should be saved into the default
glyphs directory.
``validateRead`` will validate the read data, by default it is set to the
class's validate value, can be overridden.
``validateWrte`` will validate the written data, by default it is set to the
class's validate value, can be overridden.
``expectContentsFile`` will raise a GlifLibError if a contents.plist file is
not found on the glyph set file system. This should be set to ``True`` if you
are reading an existing UFO and ``False`` if you use ``getGlyphSet`` to create
a fresh glyph set.
Reimplemented from fontTools.ufoLib.UFOReader.
Definition at line 1465 of file __init__.py.
References fontTools.ufoLib.UFOReader._formatVersion, _getDefaultGlyphSet(), _getGlyphSetFormatVersion3(), fontTools.ufoLib.UFOReader._validate, fontTools.ufoLib._UFOBaseIO.fs, and layerContents.
removeData()
fontTools.ufoLib.UFOWriter.removeData (self, fileName)
Remove the file named fileName from the data directory.
Definition at line 1671 of file __init__.py.
References removePath().
removeImage()
fontTools.ufoLib.UFOWriter.removeImage (self, fileName, validate = None)
Remove the file named fileName from the
images directory.
Definition at line 1697 of file __init__.py.
References fontTools.ufoLib.UFOReader._formatVersion, and removePath().
removePath()
fontTools.ufoLib.UFOWriter.removePath (self, path, force = False, removeEmptyParents = True)
Remove the file (or directory) at path. The path
must be relative to the UFO.
Raises UFOLibError if the path doesn't exist.
If force=True, ignore non-existent paths.
If the directory where 'path' is located becomes empty, it will
be automatically removed, unless 'removeEmptyParents' is False.
Definition at line 1145 of file __init__.py.
References fontTools.ufoLib._UFOBaseIO.fs.
Referenced by deleteGlyphSet(), removeData(), removeImage(), writeFeatures(), writeGroups(), writeKerning(), and writeLib().
renameGlyphSet()
fontTools.ufoLib.UFOWriter.renameGlyphSet (self, layerName, newLayerName, defaultLayer = False)
Rename a glyph set.
Note: if a GlyphSet object has already been retrieved for
layerName, it is up to the caller to inform that object that
the directory it represents has changed.
Definition at line 1604 of file __init__.py.
References _findDirectoryForLayerName(), fontTools.ufoLib.UFOReader._formatVersion, fontTools.ufoLib._UFOBaseIO.fs, and layerContents.
setKerningGroupConversionRenameMaps()
fontTools.ufoLib.UFOWriter.setKerningGroupConversionRenameMaps (self, maps)
Set maps defining the renaming that should be done
when writing groups and kerning in UFO 1 and UFO 2.
This will effectively undo the conversion done when
UFOReader reads this data. The dictionary should have
this form::
        {
                "side1" : {"group name to use when writing" : "group name in data"},
                "side2" : {"group name to use when writing" : "group name in data"}
        }
This is the same form returned by UFOReader's
getKerningGroupConversionRenameMaps method.
Definition at line 1199 of file __init__.py.
References _downConversionKerningData, and fontTools.ufoLib.UFOReader._formatVersion.
setModificationTime()
fontTools.ufoLib.UFOWriter.setModificationTime (self)
Set the UFO modification time to the current time.
This is never called automatically. It is up to the
caller to call this when finished working on the UFO.
Definition at line 1172 of file __init__.py.
References _fileCreator, fontTools.ufoLib.UFOReader._formatVersion, fontTools.ufoLib.UFOReader._path, and fontTools.ufoLib._UFOBaseIO._writePlist().
writeBytesToPath()
fontTools.ufoLib.UFOWriter.writeBytesToPath (self, path, data)
Write bytes to a path relative to the UFO filesystem's root.
If writing to an existing UFO, check to see if data matches the data
that is already in the file at path; if so, the file is not rewritten
so that the modification date is preserved.
If needed, the directory tree for the given path will be built.
Definition at line 1100 of file __init__.py.
References fontTools.ufoLib._UFOBaseIO._havePreviousFile, and fontTools.ufoLib._UFOBaseIO.fs.
Referenced by writeData(), writeFeatures(), and writeImage().
writeData()
fontTools.ufoLib.UFOWriter.writeData (self, fileName, data)
Write data to fileName in the 'data' directory.
The data must be a bytes string.
Definition at line 1664 of file __init__.py.
References writeBytesToPath().
writeFeatures()
fontTools.ufoLib.UFOWriter.writeFeatures (self, features, validate = None)
Write features.fea. This method requires a
features string as an argument.
Definition at line 1403 of file __init__.py.
References fontTools.ufoLib.UFOReader._formatVersion, fontTools.ufoLib._UFOBaseIO._havePreviousFile, fontTools.ufoLib.UFOReader._validate, removePath(), and writeBytesToPath().
writeGroups()
fontTools.ufoLib.UFOWriter.writeGroups (self, groups, validate = None)
Write groups.plist. This method requires a
dict of glyph groups as an argument.
``validate`` will validate the data, by default it is set to the
class's validate value, can be overridden.
Definition at line 1224 of file __init__.py.
References _downConversionKerningData, fontTools.ufoLib.UFOReader._formatVersion, fontTools.ufoLib._UFOBaseIO._havePreviousFile, fontTools.ufoLib.UFOReader._validate, fontTools.ufoLib._UFOBaseIO._writePlist(), fontTools.ufoLib.validators.groupsValidator(), and removePath().
writeImage()
fontTools.ufoLib.UFOWriter.writeImage (self, fileName, data, validate = None)
Write data to fileName in the images directory.
The data must be a valid PNG.
Definition at line 1679 of file __init__.py.
References fontTools.ufoLib.UFOReader._formatVersion, fontTools.ufoLib.UFOReader._validate, fontTools.ufoLib.validators.pngValidator(), and writeBytesToPath().
writeInfo()
fontTools.ufoLib.UFOWriter.writeInfo (self, info, validate = None)
Write info.plist. This method requires an object
that supports getting attributes that follow the
fontinfo.plist version 2 specification. Attributes
will be taken from the given object and written
into the file.
``validate`` will validate the data, by default it is set to the
class's validate value, can be overridden.
Definition at line 1279 of file __init__.py.
References fontTools.ufoLib.UFOReader._formatVersion, fontTools.ufoLib.UFOReader._validate, fontTools.ufoLib._UFOBaseIO._writePlist(), fontTools.ufoLib.validateInfoVersion2Data(), and fontTools.ufoLib.validateInfoVersion3Data().
writeKerning()
fontTools.ufoLib.UFOWriter.writeKerning (self, kerning, validate = None)
Write kerning.plist. This method requires a
dict of kerning pairs as an argument.
This performs basic structural validation of the kerning,
but it does not check for compliance with the spec in
regards to conflicting pairs. The assumption is that the
kerning data being passed is standards compliant.
``validate`` will validate the data, by default it is set to the
class's validate value, can be overridden.
Definition at line 1325 of file __init__.py.
References _downConversionKerningData, fontTools.ufoLib.UFOReader._formatVersion, fontTools.ufoLib._UFOBaseIO._havePreviousFile, fontTools.ufoLib.UFOReader._validate, fontTools.ufoLib._UFOBaseIO._writePlist(), fontTools.ufoLib.validators.isDictEnough(), and removePath().
writeLayerContents()
fontTools.ufoLib.UFOWriter.writeLayerContents (self, layerOrder = None, validate = None)
Write the layercontents.plist file. This method  *must* be called
after all glyph sets have been written.
Definition at line 1422 of file __init__.py.
References fontTools.ufoLib.UFOReader._formatVersion, fontTools.ufoLib.UFOReader._validate, fontTools.ufoLib._UFOBaseIO._writePlist(), and layerContents.
writeLib()
fontTools.ufoLib.UFOWriter.writeLib (self, libDict, validate = None)
Write lib.plist. This method requires a
lib dict as an argument.
``validate`` will validate the data, by default it is set to the
class's validate value, can be overridden.
Definition at line 1382 of file __init__.py.
References fontTools.ufoLib._UFOBaseIO._havePreviousFile, fontTools.ufoLib.UFOReader._validate, fontTools.ufoLib._UFOBaseIO._writePlist(), fontTools.ufoLib.validators.fontLibValidator(), and removePath().
Member Data Documentation
_downConversionKerningData
fontTools.ufoLib.UFOWriter._downConversionKerningData = None protected
Definition at line 1035 of file __init__.py.
Referenced by setKerningGroupConversionRenameMaps(), writeGroups(), and writeKerning().
_fileCreator
fontTools.ufoLib.UFOWriter._fileCreator = fileCreator protected
Definition at line 1034 of file __init__.py.
Referenced by setModificationTime().
layerContents
dict fontTools.ufoLib.UFOWriter.layerContents = {}
Definition at line 1053 of file __init__.py.
Referenced by deleteGlyphSet(), getGlyphSet(), renameGlyphSet(), and writeLayerContents().
removeFileForPath
fontTools.ufoLib.UFOWriter.removeFileForPath = removePath static
Definition at line 1168 of file __init__.py.
Property Documentation
fileCreator
fontTools.ufoLib.UFOWriter.fileCreator static
Initial value:
=  property(
        _get_fileCreator,
        doc="The file creator of the UFO. This is set into metainfo.plist during __init__.",
    )
Definition at line 1070 of file __init__.py.
The documentation for this class was generated from the following file:
/home/jam/Research/IRES-2025/dev/src/llm-scripts/testing/hypothesis-testing/hyp-env/lib/python3.12/site-packages/fontTools/ufoLib/__init__.py